### ISSUE TITLE
HTML highlight parser error (like unclosed tags)

### ISSUE THREAD

**Issue by Kapcash** [Microsoft/vscode#55479] opened 2018-07-31 15:14 UTC
When writing some simple HTML, I would like to see at a glance whether my html is correct or not. Webstorm use to highlight the unclosed tag or the closing tag with no opening one for example.

I didn't found any extension implementing this behavior.

What I expect is something like:
![featurerequestvscode](https://user-images.githubusercontent.com/10612835/43468627-c6c38bb8-94e4-11e8-8a62-6ef6f1d97d71.png)

Here, I quickly see that my html isn't well formated. Even if modern browsers use heuristics to correctly parse the html, I think it's a needed feature to avoid such html errors.

Thanks! :)

**Comment by aeschli** [comment] 2018-07-31 21:27
duplicate of #23199

**Closed by aeschli** 2018-07-31 21:27 UTC
Labels: html
