### ISSUE TITLE
Task: removed tasks still available in "recently used"

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#94020] opened 2020-03-31 18:21 UTC
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

Testing #93746

Steps to Reproduce:

1. Create a `tasks.json` with one single task
2. Run the task with `Run Task`
3. Remove the `tasks.json`
4. `Run Task` still shows it because it's recently used

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment] 2020-04-01 08:30
duplicate of https://github.com/microsoft/vscode/issues/93931

**Closed by alexr00** 2020-04-01 08:30 UTC
