### ISSUE TITLE
Settings editor scrolls slowly when `workbench.list.smoothScrolling` enabled

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#104144] opened 2020-08-06 03:18 UTC
Issue Type: <b>Bug</b>

When `"workbench.list.smoothScrolling": false`:

* one mouse wheel scroll in extension view: moves 100px
* one mouse wheel scroll in settings editor: moves 100px

When `"workbench.list.smoothScrolling": true`:

* one mouse wheel scroll in extension view: moves 100px, with slight animation
* one mouse wheel scroll in settings editor: moves 15~25px, without animation

I'm using a Logitech G502 Lightspeed mouse, without any scrolling tweaking softwares.

![1](https://user-images.githubusercontent.com/1330321/89486703-388d9f00-d7d6-11ea-9021-52eb8401ee26.gif)

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:30:25.429Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment] 2020-08-06 04:56
I don't see this, any idea @joaomoreno

**Comment by joaomoreno** [comment] 2020-08-06 13:57
@roblourens I believe this setting is ignored for macOS.

Duplicate of https://github.com/microsoft/vscode/issues/102261

**Comment by joaomoreno** [comment] 2020-08-06 13:58
Actually not a duplicate. Interesting. I need to get my hands on a mouse to see if I can repro.

**Comment by jeanp413** [comment] 2020-08-11 23:28
Created a PR that fixes this: #104284

**Closed** 2020-09-07 13:53 UTC
Labels: bug, help wanted, list
