### ISSUE TITLE
Path Completion: Use File Icon for suggestions

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44860] opened 2018-03-01 19:51 UTC
Whether it comes from internal or external icon theme.

For example, this isn't really nice

![image](https://user-images.githubusercontent.com/4033249/36866103-37892144-1d46-11e8-9b94-7b1204a76d86.png)

Would be great to show js/ts icons there.

For html path completion it would be much nicer too.

This would probably require changes in `CompletionItemKind` in LSP.

@mjbvz think you might be interested too.

**Comment by mjbvz** [comment] 2018-03-01 19:54
Duplicate of #43204 which I closed as not worth the effort for js/ts. Html paths could be more interesting

**Comment by usernamehw** [comment] 2018-03-02 04:39
With modern module bundlers (like webpack) it's possible to import other files (`.css`, `.png`,...) from `js`. Icons would be helpful in that case too.

**Comment by dbaeumer** [comment] 2018-03-02 08:06
I am not sure what I should do with this. The `CompletionItemKind` has values for file and folder. There are no plans in the LSP to have CompletionItemKinds for different file types.

As @mjbvz pointed out he closed this request against TS. 

@octref any objection to close this issue?

**Comment by octref** [comment] 2018-03-02 08:28
@dbaeumer I do realize LSP isn't the right place to add support for this feature.
@jrieken I see #22206 and wondering if you can provide any input. We have the dynamically generated icon for type color -- wondering if the same can be done for type file.

**Comment by jrieken** [comment] 2018-03-02 08:48
The reason for keeping the number of completion item kinds is low is to lower the burden of implementing the LSP. It's not nice to require an implementor to bring along 50+ icons. Custom, extension defined, icons isn't the answer neither because then e.g. Eclipse-icons will be used inside VS Code leading to an alien-look. 

It's a fine line of finding an expressive set of common icons and we will never meet all demands but that's also the idea of it.

**Comment by octref** [comment] 2018-03-03 20:49
@jrieken Can we possibly make this a client-specific behavior. For example, when `CompletionItemKind` is file, read the filename in either label or textedit, match it against VS Code's matching rule for file icons, and use that icon for completion.

If other LSP clients don't have the file icon notion they can always provide one file icon.
It really helps to differentiate between the suggestion items. As @usernamehw said, Webpack allows you to import css/jpg/png/svg and whatever file Webpack's loader could resolve.

**Comment by jrieken** [comment] 2018-03-05 08:10
>  For example, when CompletionItemKind is file, read the filename in either label or textedit, match it against VS Code's matching rule for file icons, and use that icon for completion.


Hm, interesting idea I like. Maybe a little harder to magic-match than colors but we should give it a try

**Comment by jrieken** [comment] 2018-10-08 12:52
@mjbvz For this to work, we would need to get the full path (or at least the name with its extension), e.g. as documentation label...

**Comment by svipben** [comment] 2018-10-11 12:18
I don't even know how to express myself, @jrieken created `tabCompletion -> 'on'` and `localityBonus`. @octref is working on path completion icons. Guys, it's not even Christmas and I'm getting all my gifts. I'm sooo happy 😄

**Comment by jrieken** [comment] 2018-10-11 14:57
The one challenge here is how file icons look together with symbols icon. The former can be themed the latter not so this has potential for ugliness...

**Comment by svipben** [comment] 2018-10-16 09:19
@jrieken Looks very nice, amazing work!!! 🔥 

I have several questions:
1. It will adapt to the icon theme?
2. It will impact the performance of suggestions rendering? I'm asking cuz' sometimes I see `Loading...`in suggestion widget.
3. It will have a setting to enable/disable icons or it will be enabled by default to show icons?

My main concern is performance and the ability to use the same icons as selected in the icon theme.

**Comment by svipben** [comment] 2018-10-16 10:01
Thanks, @jrieken, I really appreciate your work and all the information. 👍

**Comment by neilsustc** [comment] 2018-10-16 10:34
Looks great! One small problem, the folder icon feels not right 😅

![image](https://user-images.githubusercontent.com/7588612/47010618-7324d400-d137-11e8-8c22-1d456709cbe6.png)

**Comment by jrieken** [comment] 2018-10-16 10:47
Yeah, it still needs some tweaks with alignment and it doesn't respect folder icons yet. The challenge is that some theme don't have an icon for folders...

**Comment by usernamehw** [comment] 2018-10-17 13:44
It seems to be aligned to top...
![screenshot 72](https://user-images.githubusercontent.com/9638156/47090176-07239800-d22b-11e8-8030-19ce7ba24f44.png)


And it's not working inside typescript import path completion... Is it intentional?

OS: Win10 x64 799bc78af597769a5dd5a6b002359ddae412b1be

**Comment by octref** [comment] 2018-10-17 17:07
I think for TS, they return import path without suffix and there is no way to guess the file icon from it.

**Comment by jrieken** [comment] 2018-10-18 07:28
> And it's not working inside typescript import path completion

@usernamehw  https://github.com/Microsoft/vscode/issues/44860#issuecomment-427820307


> It seems to be aligned to top...

Do you have a special config for the suggest font size?

**Comment by usernamehw** [comment] 2018-10-18 13:39
```json
"editor.suggestLineHeight": 40,
"editor.suggestFontSize": 20,
```

**Comment by Astrantia** [comment] 2018-10-18 14:19
@jrieken Can we add a configuration for this to enable/disable? Personally, I like this, but if someone dislikes it they will always be able to disable it from settings.

**Closed** 2018-10-23 13:15 UTC
Labels: feature-request, suggest

**Comment by octref** [comment] 2018-10-23 17:45
@jrieken I'm in a TS file and trying to do require, but TS LS returns all filenames without the suffix. Is there any way TS could update their `CompletionItem` so it displays the nice icons?

![image](https://user-images.githubusercontent.com/4033249/47379815-cefbd980-d6b0-11e8-8013-6c570e9dd693.png)

**Comment by jrieken** [comment] 2018-10-24 07:11
@octref please read https://github.com/Microsoft/vscode/issues/44860#issuecomment-427820307

**Comment by octref** [comment] 2018-10-24 16:14
@jrieken I see, I'll try to send a PR for TypeScript, so the `CompletionItem`s have label with suffixes like main.ts, router.js but the textedit doesn't contain the labels.

**Comment by usernamehw** [comment] 2018-10-27 11:49
Icons are way too small now. Is it possible to have them the same size as before?:

| Stable  | Insiders |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/9638156/47603611-38545300-d9f7-11e8-9b1b-4ea58bde0c1e.png) | ![after](https://user-images.githubusercontent.com/9638156/47603613-4013f780-d9f7-11e8-8e54-b7b175397edd.png) |
