### ISSUE TITLE
Sass Indented Flavor

### ISSUE THREAD

**Issue by Aamir2000** [microsoft/vscode#100005] opened 2020-06-12 14:49 UTC
>This is not a duplicate issue its created on request of a team member here : #99742

Some people like the pain old css way of doing stuff in preprocessors like sass and we do agree with that though we're not comparing it with the indented flavor of sass and now we've to again point out the fact that more and more people keep complaining that Vscode team keep referring to a extension called "Live Sass Compiler" and its kinda pointless to use that extension because Vscode itself has no syntax highlighting for that particular flavor which kinda make users experience looking like writing html in notepad which is obviously great in a nonsensical way.

**Comment by aeschli** [comment] 2020-06-16 08:19
Duplicate of #28456. We have no plans to add built-in support for indented sass.
Not only want we to share the load of development and maintenance, we also want to keep VSCode small.

https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented is one of these extension. It also provided syntax highlighting.

Help these extensions to get better by providing feedback or even help with PRs.

**Closed by aeschli** 2020-06-16 08:19 UTC

**Comment by Aamir2000** [comment] 2020-06-16 11:51
> Duplicate of #28456. We have no plans to add built-in support for indented sass.
> Not only want we to share the load of development and maintenance, we also want to keep VSCode small.
> 
> https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented is one of these extension. It also provided syntax highlighting.
> 
> Help these extensions to get better by providing feedback or even help with PRs.

Expected response well on that point I also wanna mention that issue you just tagged sir people seems to be complaining about same problem I mentioned here which kinda makes it even big of a deal, anyways I guess it's not really going anywhere for now and about keeping vscode small one more thing vscode itself sometimes lags out as our project grows and specially when companies like google gives us Angular like crappy bulky frameworks its kinda impossible to work with Vscode from what I and many other developers can tell so that's that issue solved hopefully atleast performance can be improved for big projects or is there a extension for that too ? lemme know wassup with that
