### ISSUE TITLE
Move Cell Diff View does not display any diffs

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#208564] opened 2024-03-25 08:24 UTC
Testing #208266

Move cell Timeline entry does not display diff of the cells having moved.

<img width="1469" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/b2fabc9d-dee9-440b-aa18-65b5f3d64284">

**Comment by DonJayamanne** [comment] 2024-03-25 12:14
Yeah, this will be challenging, 
Current design is to always collapse all new edits with the previous edit operations.
However if we stop collapsing all edits, then the only other alternative is to always display each save as `File Saved` as was done here https://github.com/microsoft/vscode/pull/208053

I.e. all operations will show up consistently as `File Saved`
Thoughts @rebornix /cc
I think that would be better than having a mix of `Move Cell`, `File Saved`, I.e. `File Saved` always is consistent and simple.
We can explore ways to make this more fine grained later,

**Comment by DonJayamanne** [comment] 2024-03-25 12:20
@bhavyaus You need to click the `Insert Cell` (the entry below the `Move Cell` item in time line) to be able to see the difference.
I.e. clicking the top most entry in the time line (chronologically last entry) does not show any diff, as it always show the latest state vs latest state.
I.e. this is by design, (this is how it also works with plain text files and time line entries)

hence, please click the item `Insert Cell` to see the diff against the latest and you should see the dif of moved cell.
Can you veriy it works as expected when you do that.

**Comment by DonJayamanne** [comment] 2024-03-25 12:32
From https://github.com/microsoft/vscode/issues/208563#issue-2205161140
>  Clicking on the Delete entry in the timeline view produced an empty diff editor:


Peng and I also made the same assumption, however thats how how its designed to work (i.e. plain text files work this way, hence the statement `by design`)
Closing as by design.

**Closed by DonJayamanne** 2024-03-25 12:32 UTC
Labels: info-needed, notebook, notebook-undo-redo
