### ISSUE TITLE
Code Commenting Doesn't Uncomment Block Comments

### ISSUE THREAD

**Issue by phocks** [Microsoft/vscode#25944] opened 2017-05-04 23:08 UTC
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. New Javascript React file

2. Seems to only try to do block commenting on jsx components like:
```
class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h1>Test App</h1>
        </div>
      </div>
    );
  }
}
```

3. Hit Cmd( or Ctrl)+/ to comment the whole code and it will put /* */ around it

4. Hit Cmd( or Ctrl)+/ and you expect it to uncomment, but it just puts line comments // on the selection 

![snip20170505_1](https://cloud.githubusercontent.com/assets/437566/25728429/5844827c-3172-11e7-8f6f-18f7ca7028c3.png)

**Comment by mjbvz** [comment] 2017-05-10 06:01
This is a duplicate of #19868. See https://github.com/Microsoft/vscode/issues/19868#issuecomment-277745476 for a possible workaround using the `Toggle Block Comment` command

@rebornix Is your thinking still the same on this issue?

**Comment by phocks** [comment] 2017-05-11 02:23
I still think this is a bug. If it detects and adds a block comment with cmd+/ then it should detect and remove the same block comment with cmd+/

Amy I wrong? Should I look at the source code and try to figure out a fix myself?

**Comment by rebornix** [comment] 2017-08-11 20:44
@mjbvz @phocks can you reproduce this issue? Right now running `cmd+/` will only add line comments.

**Comment by phocks** [comment] 2017-08-13 00:03
Yes this appears to be fixed in the latest version.

**Closed** 2017-08-13 03:36 UTC
Labels: duplicate, needs more info
