### ISSUE TITLE
Kill terminal instance action freezes VSCode

### ISSUE THREAD

**Issue by pavel-zhigulin** [microsoft/vscode#97102] opened 2020-05-06 22:25 UTC
- VSCode Version:
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- OS Version:
Name: Window 10 Pro
Version: 1909
Build: 18363.778

- Poweshell version
Name: ConsoleHost
Version: 5.1.18362.752
InstanceId: e261b089-1528-46e9-afac-303c031fc82b
UI: System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture: ru-RU
CurrentUICulture: en-US
PrivateData: Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled: True
IsRunspacePushed: False
Runspace: System.Management.Automation.Runspaces.LocalRunspace

Steps to Reproduce:

1. Set powershell as default integrated terminal
2. Assing "**Terminal: Split Terminal**" to <kbd>ctrl+shift+\\</kbd> shortcut
3. Assing "**Terminal: Kill the active terminal instance**" to <kbd>ctrl+D</kbd> shortcut and "terminalFocus" in _When expression_ column
4. Open integrated terminal and focus on it
5. Press <kbd>ctrl+shift+\\</kbd> which should create splitter terminal view and focus on new one
6. Press <kbd>ctrl+D</kbd> which will close right terminal
7. Repeat step 5 and 6. After second killing VSCode freezes forever until you kill it via task manager. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-05-07 10:09
Looks like duplicate of #2377 and/or #76548

/assign @Tyriar

**Closed** 2020-05-07 12:04 UTC
