### ISSUE TITLE
Source control - staged changes tree view inconsistent

### ISSUE THREAD

**Issue by HookyQR** [microsoft/vscode#82481] opened 2019-10-14 05:37 UTC
- VSCode Version: 1.39.1
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

## Setup:
1. In an active git repo, with existing commits.
2. Move a file between directories.
3. Set Source control view to tree view.
![image](https://user-images.githubusercontent.com/14353068/66730497-c9c90900-ee84-11e9-824c-2b59f88e2c35.png)

### Staging the addition first:
4a1. Stage the addition (untracked) part of the change: (displayed correctly)
![image](https://user-images.githubusercontent.com/14353068/66730534-f7ae4d80-ee84-11e9-9073-a88fb59cfbd5.png)
4a2. Stage the deletion part of the change:
![image](https://user-images.githubusercontent.com/14353068/66730548-0a288700-ee85-11e9-8bc0-300618960149.png)
Note that the Staged Changes tab is expanded in the image above. The **1** change badge is displayed, but the change(s) themselves are not.

### Staging all changes at once:
4b1. Stage all changes.
![image](https://user-images.githubusercontent.com/14353068/66730595-61c6f280-ee85-11e9-815c-2c77abc321ce.png)
Note that only the addition is shown, with no type badge.
4b2. Unstage the file (by clicking the `-` next to the file)
![image](https://user-images.githubusercontent.com/14353068/66730651-a0f54380-ee85-11e9-9dec-6656de8d45d5.png)
The deletion is now displayed correctly

### Staging the deletion first:
4c1. Stage the deletion - displays correctly. (same state as 4b2)
4c2. Stage the addition - displays correctly, with the Renamed badge.
![image](https://user-images.githubusercontent.com/14353068/66730848-af902a80-ee86-11e9-96d0-fc3198def40d.png)
4c3. Unstage the folder or the file change.
![image](https://user-images.githubusercontent.com/14353068/66730884-ed8d4e80-ee86-11e9-96f4-1e697892e1a1.png)
Only the Addition (Untracked) is unstaged. This is (for me) unexpected behaviour, but does not differ from the way the source control view acts on any Renamed file. I would expect, since I'm acting on a Renamed (ie the Untracked and the Deleted file(s)) that both actions would return to the Changes tab.

4a and 4b seem to be bugs caused by order of operation. 4c3 is, I guess, a feature request, but closely related.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2019-10-14 09:49
Thanks for the incredible repro steps @HookyQR. I can't reproduce this at all in 1.39.1 or Insiders, though...

Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

Can you reproduce this with `--disable-extensions`?

**Comment by HookyQR** [comment] 2019-10-15 00:22
Same problem on stable, with extensions disabled.

**Comment by HookyQR** [comment] 2019-10-15 00:25
Staging seems to have been fixed on the insiders build. Must have been a closed issue I didn't find. Any chance you can change 4c3 into a feature request for me though? 😉

**Comment by HookyQR** [comment] 2019-10-15 00:31
Maybe you fixed this one as a side effect in #82341. 👍

**Comment by joaomoreno** [comment] 2019-10-15 11:15
Possible but I don't think so... Especially since I can't repro on stable as well.

I'll close this for now. A new stable will come out this week. Let me know if you still see the issue on that one then. Thanks!

**Closed by joaomoreno** 2019-10-15 11:15 UTC
Labels: needs more info, new release

**Comment by HookyQR** [comment] 2019-10-16 00:40
Crazy times. Magic code. Thanks João!

**Comment by sploders101** [comment] 2019-10-29 23:06
I am having this issue as well. I'm not sure what @HookyQR means by 4c being a feature request, because the steps described are what currently happens. I am able to reproduce this on the specified version as well as 1.40.0-insider installed on linux from the snap store. When the deletion is staged first, it is displayed and marked properly. When the addition is staged first, the file disappears. Forcing a re-render (leaving the pane and coming back to it, or going to list view, then back to tree view) causes it to display properly again.

**Comment by joaomoreno** [comment] 2019-10-30 08:54
@sploders101 Can you send a screen recording showing me what you mean?
