### ISSUE TITLE
Whenever I try to install extension from Marketplace it shows error "end of central directory record signature not found"

### ISSUE THREAD

**Issue by pprathameshmore** [Microsoft/vscode#42229] opened 2018-01-27 00:16 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
python|ms-|0.9.1
cpptools|ms-|0.14.6
bootstrap-3-snippets|wcw|0.1.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2018-01-27 20:39
Duplicate of #42079

As a workaround, trying manually installing the extension

**Comment by joaomoreno** [comment] 2018-01-29 11:44
https://code.visualstudio.com/docs/setup/network

https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

**Comment by octref** [comment] 2018-02-23 01:38
@joaomoreno Maybe provide a more informative error message?
And is the cause of this issue incorrect config of proxy?

**Comment by lili21** [comment] 2018-02-24 11:04
Still have the problem. I am using 1.20.1.

**Comment by joaomoreno** [comment] 2018-02-26 10:11
Let's catch this bug and expose a download link for the extension VSIX.

**Comment by lili21** [comment] 2018-02-26 10:39
I tried to install extension manually. doesn't work after relaunch.

**Comment by octref** [comment] 2018-02-28 16:55
Might be of your interest:

https://github.com/thejoshwolfe/yauzl/issues/69
https://github.com/thejoshwolfe/yauzl/issues/72

**Comment by joaomoreno** [comment] 2018-03-01 14:50
Verification in dev:

Open https://github.com/Microsoft/vscode/blob/b51d61e3625330fb4e391082be7bea75ae0fb59e/src/vs/base/node/zip.ts#L123 and change the following line:

![screen shot 2018-03-01 at 15 44 35](https://user-images.githubusercontent.com/22350/36850693-bea8494a-1d67-11e8-8d9e-835ec4f38d68.png)

This will make the zip library fail on extract.

The experience should then go as such:

![screen shot 2018-03-01 at 15 46 27](https://user-images.githubusercontent.com/22350/36850694-bec236c0-1d67-11e8-9b6d-c39df8f3f81a.png)

![screen shot 2018-03-01 at 15 46 29](https://user-images.githubusercontent.com/22350/36850695-bedd72fa-1d67-11e8-9b6d-1b5c7cdade14.png)

**Comment by joaomoreno** [comment] 2018-04-11 07:35
That appears to be a separate issue.

**Closed by joaomoreno** 2018-04-11 07:35 UTC
Labels: bug, extensions, verified
