### ISSUE TITLE
add support for horizontal file browsing like ranger

### ISSUE THREAD

**Issue by basaran** [microsoft/vscode#104019] opened 2020-08-05 01:04 UTC
Hello, it could be more practical to use a ranger like horizontal file explorer for certain workloads, preferably merged into the terminal area to the bottom part of the window. Most of us keep a terminal open within vscode at all times, and when you use multiple editor groups, opening up the file explorer to the side disrupts the code view. 

At the moment, I'm using ranger within the terminal set to use vscode as default editor. It's working but, it lags a bit to open the files and the previews are not native. For concept, it would like something like this:

![image](https://user-images.githubusercontent.com/30809170/89359756-89957a00-d694-11ea-9ed1-6236b4831370.png)

**Comment by isidorn** [comment] 2020-08-05 07:34
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by yume-chan** [comment] 2020-08-05 15:49
Relates to #46585

If we have webview in views/panels, this feature can be provided by some extension.

**Comment by isidorn** [comment] 2020-08-05 16:27
Sounds good, let's close as duplicate of that one.

**Closed** 2020-08-05 16:28 UTC
Labels: *duplicate, feature-request, file-explorer
