### ISSUE TITLE
Arrow up / arrow down / indents

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#35254] opened 2017-09-27 20:43 UTC
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

There is some `function`, and `for` in it, so when you do some `Enter`'s to move down and then press "**arrow up**" or "**arrow down**" - your caret position will "fall through" all indents to the left, so user has to press Tab every time, to move the caret where it should be.

Annoying.

GIF:
![auto-indent](https://user-images.githubusercontent.com/24613274/30936552-e958a0e0-a3dc-11e7-8820-eccff0b2433f.gif)

**Comment by johnthad** [comment] 2017-09-29 15:36
I'm seeing this same behavior in VSC 1.16.1 on MacOS 10.10 and 10.11

**Comment by Kuraperunat** [comment] 2017-11-16 12:31
This is not just annoying, a fix for this is a prerequisite for some people including me to start using VSCode.

The problem is amplified when you have more indentations (especially in languages like C# with namespaces) cause you have to press tab multiple times to get to the current indentation. To be clear:

- Moving the caret up/down with arrows should always stay on the current block indentation
- Clicking an empty line should position caret to the selected block indentation
- Pressing tab **once** should get to the current block indentation

For the love of god fix this, Visual Studio has had this right for ages.

**Comment by felixfong227** [comment] 2018-10-29 18:35
I found out that by disabling the `Trim Auto Whitespace` can sort of fix this issue🤔
![image](https://user-images.githubusercontent.com/13918481/47671737-394dd600-dbeb-11e8-9d74-aa30d88c9900.png)
Hope this is what you are looking for, at least I'm very happy with my end result🎉
![ezgif-2-d6581aa66b23](https://user-images.githubusercontent.com/13918481/47672130-2687d100-dbec-11e8-888a-4d3c31e9497f.gif)

**Comment by alexdima** [comment] 2022-12-10 22:40
Let's track in #13960

**Closed by alexdima** 2022-12-10 22:40 UTC
Labels: editor-core, under-discussion, editor-commands
