### ISSUE TITLE
Inconsistent struct highlighting in case statements (C)

### ISSUE THREAD

**Issue by Saribro** [microsoft/vscode#73882] opened 2019-05-17 10:53 UTC
Issue Type: <b>Bug</b>

Struct highlighting in case statements differs between scoped and unscoped.

![vscode](https://user-images.githubusercontent.com/11048939/57923400-8309bf80-78a2-11e9-8e00-cd838d8af6e8.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
todo-tree|Gru|0.0.132
cpptools|ms-|0.23.1
awesome-vhdl|puo|0.0.1
tcl|sle|0.2.0

</details>

**Comment by jeff-hykin** [comment] 2019-05-18 03:16
This was caused by a change to the C++ syntax `jeff-hykin/cpp-textmate-grammar`. We went ahead and fixed the issue over there, if you want to get the fix right now install the `Better C++ Syntax` extension. The fix will eventually get pulled into VS Code if you're okay waiting though.

**Comment by Saribro** [comment] 2019-05-21 09:28
I have since seen other problems in the vscode highlighting that are fixed in `jeff-hykin/cpp-textmate-grammar`. Should I open separate issues for these, or is this one sufficient as placeholder for a general pull from upstream?

**Comment by alexr00** [comment] 2019-05-21 09:35
I pulled in the changes from `jeff-hykin/cpp-textmate-grammar` (thanks @jeff-hykin for commenting on this issue!). The updates will be in the next stable release and in the next release of insiders.

@Saribro, I usually pull in the grammar changes once per month, but when I know there's an issue causing people problems I might pull in the changes earlier.

**Closed by alexr00** 2019-05-21 09:35 UTC
