### ISSUE TITLE
VScode vs Container Docker

### ISSUE THREAD

**Issue by Ch3did** [microsoft/vscode#142470] opened 2022-02-08 05:02 UTC
Issue Type: <b>Bug</b>

After Vscode update to 1.64 every time i try to rebuild my repository on a docker container end with:
 ```
[2020-04-12T17:35:27.282Z] [PID 4968] [41541 ms] Stdin closed! 
[2020-04-12T17:35:27.285Z] [PID 4968] [41544 ms] Shell server terminated (code: 1, signal: null)
```
I tried to rollback to 1.62 what solves the container problem, but make's my `source code control tab` empty and stuck

Can anybody help???

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.13.0-28-generic
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2949)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|7.42GB (0.10GB free)|
|Process Argv|. --crash-reporter-id 3c66f9fe-9867-41ac-9ac1-7a076ce0885e --crash-reporter-id 3c66f9fe-9867-41ac-9ac1-7a076ce0885e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Docker Compose (Extend)|
|OS|Linux x64 5.13.0-28-generic|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3000)|
|Memory (System)|7.42GB (0.10GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.2.2
bracket-pair-colorizer-2|Coe|0.2.2
vscode-language-pack-pt-BR|MS-|1.64.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
python-extended-snippets|tus|0.0.1
vscode-icons|vsc|11.8.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
vscode-django|bat|1.8.0
toml|be5|0.6.0
python-preview|don|0.0.4
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.14.2
vscode-language-pack-pt-BR|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5330
autodocstring|njp|0.5.4
vscode-make|tec|1.0.2
python|tht|0.2.3
vscodeintellicode|Vis|1.2.16
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
pythonvs932:30410667
wslgetstartedc:30433508
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by lszomoru** [comment] 2022-03-01 16:13
@Ch3did, sorry for not getting back to you on this until now. As far as I remember there was a bug in `1.62.3` that could result in the Source Control viewlet not to render which I believe you are hitting. This has been resolved in upcoming releases, so I think that it would be important to track down the root cause of the failures to rebuild the repository so that you can use the latest version of VS Code.

Could you please share the steps that you are using to rebuild your repository in a container? Thanks!

**Closed** 2022-03-09 11:27 UTC
Labels: needs more info
