### ISSUE TITLE
Mini-map, when moves, covers some code

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#38738] opened 2017-11-20 02:42 UTC
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

The work space is split in two.
So, when you move the border between them, mini-map can cover 2-3 symbols of code, those which are the last in the most long lines.

![mini-map hides some code](https://user-images.githubusercontent.com/24613274/32999787-a53a5a44-cdac-11e7-84fa-934f2efc6f07.gif)

So it can be very confusing for the developer.

**Comment by roblourens** [comment] 2017-11-20 06:32
/duplicate of https://github.com/Microsoft/vscode/issues/21359

**Closed** 2017-11-20 06:33 UTC
Labels: *duplicate, editor
