### ISSUE TITLE
Issue : Copy with Syntax Highlighting as HTML does not have indent space on paste

### ISSUE THREAD

**Issue by aventador-dawn** [Microsoft/vscode#35414] opened 2017-09-30 07:09 UTC
- VSCode Version:1.16.1
- OS Version:Windows 7 64 Bit

Steps to Reproduce:

1.Select Source Code
2.Ctrl+Shift+P , Copy With Syntax Highlighting
3. Paste 

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/22929562/31043586-64c3d92e-a5dc-11e7-92f5-21345373004b.png)

But on paste (HTML) indent space is not there

![image](https://user-images.githubusercontent.com/22929562/31043578-46b773dc-a5dc-11e7-92ac-783ad38ec6d3.png)

**Comment by rebornix** [comment] 2018-09-18 19:55
Sorry for coming back on this issue too late. May I ask do you still run in to this issue and where do you paste the content?

**Comment by rebornix** [comment] 2018-09-18 20:01
If we run into this issue when pasting into another application, this is duplicate of https://github.com/Microsoft/vscode/issues/31829 . We use non-break-spaces in html but they are not being rendered as expected in some applications, we probably want to think about what we want to use there.

For pasting in VSCode, we will not trim all whitespaces so very likely it's above case.

**Closed** 2018-09-18 20:01 UTC
Labels: *duplicate, editor-clipboard, needs more info, under-discussion
