### ISSUE TITLE
Potential leak detected in breadcrumbs control

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64469] opened 2018-12-06 01:22 UTC
Issue Type: <b>Bug</b>

**repo**
1. Open a file with breadcrumbs
1. Keep splitting the editor multiple times and then closing the split editors again (with a dirty file, just hold down cmd+\ for a half second, then hold cmd+w until it brings up the save dialog. Close the dialog and repeat )

**Bug**
In devtools console, see:
```
[9b9] potential listener LEAK detected, having 604 listeners already. MOST frequent listener (87):
```
```
  at onThemeChange (./workbench/browser/labels.ts:76:35)
  at registerListeners (./workbench/browser/labels.ts:61:7)
  at call (./workbench/browser/labels.ts:281:2)
  at apply (./base/common/types.ts:165:6)
  at apply (./platform/instantiation/common/instantiationService.ts:104:19)
  at _createInstance (./platform/instantiation/common/instantiationService.ts:69:17)
  at createInstance (./workbench/browser/parts/editor/breadcrumbsControl.ts:81:42)
  at render (./base/browser/ui/breadcrumbs/breadcrumbsWidget.ts:329:7)
  at _renderItem (./base/browser/ui/breadcrumbs/breadcrumbsWidget.ts:318:9)
  at _render (./base/browser/ui/breadcrumbs/breadcrumbsWidget.ts:287:8)
  at setItems (./workbench/browser/parts/editor/breadcrumbsControl.ts:244:16)
  at updateBreadcrumbs (./workbench/browser/parts/editor/breadcrumbsControl.ts:248:2)
  at update (./workbench/browser/parts/editor/tabsTitleControl.ts:142:57)
  at updateBreadcrumbsControl (./workbench/browser/parts/editor/tabsTitleControl.ts:268:7)
  at openEditor (./workbench/browser/parts/editor/editorGroupView.ts:809:24)
  at doShowEditor (./workbench/browser/parts/editor/editorGroupView.ts:785:14)
  at doOpenEditor (./workbench/browser/parts/editor/editorGroupView.ts:744:14)
  at openEditor (./workbench/browser/parts/editor/editorGroupView.ts:920:9)
  at doMoveOrCopyEditorAcrossGroups (./workbench/browser/parts/editor/editorGroupView.ts:942:8)
  at copyEditor (./workbench/browser/parts/editor/editorCommands.ts:433:14)
  at splitEditor (./workbench/browser/parts/editor/editorActions.ts:73:2)
  at run (./workbench/common/actions.ts:113:42)
```

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_7104198|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by jrieken** [comment] 2018-12-06 08:17
/duplicate of https://github.com/Microsoft/vscode/issues/63655

**Closed** 2018-12-06 08:17 UTC
Labels: *duplicate, insiders
