### ISSUE TITLE
Wrong highlighting in PHP in JS in HTML attributes in PHP file 

### ISSUE THREAD

**Issue by jntx** [microsoft/vscode#85195] opened 2019-11-20 11:37 UTC
Issue Type: <b>Bug</b>

The code highlighting fails when you mix PHP code in the JS code inside an HTML attribute inside a PHP file.

This code fragment shows the behavior:
```
<?php
	// Non Javascript attribute is ok
?>
	<button data-stuff="document.location.href = '<?=$_SERVER["PHP_SELF"]."?p1=".$_REQUEST["p1"]."&p2=dosomething"?>';">:O</button>
<?php
	// Wrong highlighting happens in Javascript attributes
?>
	<button onclick="document.location.href = '<?=$_SERVER["PHP_SELF"]."?p1=".$_REQUEST["p1"]."&p2=dosomething"?>';">:O</button>
```
when the code is not on an event attribute (so it's not interpreted ad JS) the highlight is ok.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-intelephense-client|bme|1.2.3
vscode-diff|fab|1.4.0
vscode-sshfs|Kel|1.16.3
vscode-language-pack-it|MS-|1.40.2
remote-wsl|ms-|0.40.3
Go|ms-|0.11.9
notepadplusplus-keybindings|ms-|1.0.3
rust|rus|0.7.0
crates|ser|0.4.5

</details>

**Comment by alexr00** [comment] 2019-11-20 14:04
Pretty sure this is a duplicate of https://github.com/microsoft/vscode/issues/84401, since highlighting of languages within languages is not working right now.

**Comment by alexandrudima** [comment] 2019-11-20 15:19
@alexr00 Does not seem like a duplicate to me -- version 1.40.1 is stable. Grammar loading is busted in insiders only.

**Comment by alexr00** [comment] 2019-11-21 08:59
You are right, I didn't pay close enough attention to the version.

**Comment by alexandrudima** [comment] 2019-11-21 09:20
I can confirm the issue still reproduces even after fixing vscode-textmate (it is now fixed on master):

![image](https://user-images.githubusercontent.com/5047891/69324150-397ea080-0c48-11ea-80c7-4fc5a7fc6abd.png)

I think it is caused by the classic overrun problem where JS is used inside onclick and `<?=` is not injected at all places and probably misses JS strings...

**Comment by alexr00** [comment] 2019-11-25 09:56
Moved to PHP grammar repo: https://github.com/atom/language-php/issues/373

**Comment by alexr00** [comment] 2019-11-25 10:25
Looks like it might be an issue with what VS Code is doing.

**Closed** 2020-11-05 11:03 UTC
Labels: *out-of-scope, grammar

**Comment by ties-s** [comment] 2021-08-30 13:54
Any news on this?

**Comment by jntx** [comment] 2021-09-04 08:15
Checked in 1.60.0 and it is still there.
