### ISSUE TITLE
Electron stops rendering when Xbox Game Bar Performance Widget active

### ISSUE THREAD

**Issue by nickolasclarke** [microsoft/vscode#116824] opened 2021-02-17 03:30 UTC
Issue Type: <b>Bug</b>

Steps to reproduce on Win10:
1. Win+G to launch Xbox Game Bar
2. Activate "performance" widget
3. Launch vscode. Nothing is rendered.
4. disable performance widget
5. vscode begins to render

Secondary way to reproduce: 
1. Launch vscode, renders and uses
2. Activate "performance" widget as per above.
3. Notice that vscode no longer renders and appears frozen. 
4. Deactivate performance widget
5. vscode works properly again. 

![image](https://user-images.githubusercontent.com/2177320/108155419-15547e00-709c-11eb-889d-58394eaaf773.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.20GB free)|
|Process Argv|--crash-reporter-id f57c67b4-3b59-44a7-a24c-855e6ae6abd7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.22.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
material-theme|zhu|3.9.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-02-17 07:02
/duplicate of #116651 which offers a workaround.

**Closed** 2021-02-17 07:03 UTC
Labels: *duplicate

**Comment by nickolasclarke** [comment] 2021-02-17 07:06
@gjsjohnmurray much thanks.
