### ISSUE TITLE
Titles of bottom panels are missing when reloading VS Code with Notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119923] opened 2021-03-25 23:11 UTC
Version: 1.55.0-insider
Commit: 6ebe2a14f3722bc2582ecd8108d0a71dfdd46036
Date: 2021-03-25T16:23:16.288Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Install Jupyter Extesnion
2. Open a notebook
3. Open the terminal (ensure its at the bottom, see screenshot)
4. Reload VS Code
5. Notice how the headers/titles are missing from the termina/output panels.

@rebornix /cc

Question: What you do you call the titles/headers in the bottom panels? Would like to use the right lingo.

**WHile loading**
![Screen Shot 2021-03-25 at 16 08 21](https://user-images.githubusercontent.com/1948812/112555071-acd87b00-8d84-11eb-8778-2f06f527c34d.png)

**After some time its ok**
![Screen Shot 2021-03-25 at 16 08 30](https://user-images.githubusercontent.com/1948812/112555044-a0ecb900-8d84-11eb-8bd7-6867312e4d8d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment] 2021-03-25 23:12
/duplicate of https://github.com/microsoft/vscode/issues/119910 , which was originally reported by @DonJayamanne as well, thanks!

**Closed by rebornix** 2021-03-25 23:12 UTC

**Comment by DonJayamanne** [comment] 2021-03-25 23:33
Apologies for duplicates
