### ISSUE TITLE
Terminal starts with Powershell instead of default on start/restart

### ISSUE THREAD

**Issue by shivrick** [microsoft/vscode#132255] opened 2021-09-03 13:29 UTC
Issue Type: <b>Bug</b>

I have Git Bash as my default terminal.

If I leave the Terminal tab open/selected when I close or restart VS Code, the terminal tab starts up with Powershell.

If I have another tab (for example - output) selected when I close VS Code, when I start it back up, then switch to the terminal tab, the terminal starts with my default.
It also works correctly if I didn't have a terminal tab open at all - after starting, then selecting to open the terminal, the it will start with my default.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900T CPU @ 2.10GHz (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.63GB free)|
|Process Argv|. --crash-reporter-id d83701b2-cff9-47c0-9756-5e9260d8dc4e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
atlascode|atl|2.9.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
vscode-peacock|joh|3.9.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
java|red|0.81.0
vscode-yaml|red|0.22.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn321cf:30356811
pydsgst2:30361792
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by IllusionMH** [comment] 2021-09-03 13:49
/duplicate of #128763 (reproducible not only for remote)

**Closed** 2021-09-03 13:50 UTC
Labels: *duplicate, new release
