### ISSUE TITLE
Different result between external and integrated terminal when reading Cyrillic with encoding=GBK

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode#108993] opened 2020-10-20 07:10 UTC
- VSCode Version: 1.50.1
- OS Version: win10

Steps to Reproduce:

1. code:
```
class App {
  public static void main(String[] args) throws Exception {
    Scanner input = new Scanner(System.in);
    String word = input.nextLine();
    System.out.println(word);
  }
}
```
2.When running in external Command Prompt, input `Привет`, got the right output:
![image](https://user-images.githubusercontent.com/63043224/96552150-f6103480-12e5-11eb-85c6-4d88d9e3e5a4.png)

3.When running in integrated Terminal in vscode, nothing shown:
![tempsnip](https://user-images.githubusercontent.com/63043224/96552286-22c44c00-12e6-11eb-9576-decd510ad0d9.png)

4.Also, UTF-8 also doesn't help to show the output.

**[Edit]**

I've been keeping the terminal the same one during the project, but still nothing shown in vscode terminal:

**cmd: **

![tempsnip2](https://user-images.githubusercontent.com/63043224/97939143-42677400-1dbe-11eb-8bc1-00985a3440cf.png)

**PowerShell: **

![tempsnip](https://user-images.githubusercontent.com/63043224/97939253-4bf0dc00-1dbe-11eb-9ca7-ce8a2c2c64a6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2020-10-30 19:33
You're using cmd and powershell, that could very well be the cause for the difference?

**Comment by molly-w** [comment] 2020-11-03 02:23
> You're using cmd and powershell, that could very well be the cause for the difference?

Sorry for my confusing reproduction screenshots, but i was using the same one terminal during the project and i've edit my question.

**Comment by Tyriar** [comment] 2020-11-03 16:28
Can you run `ver` in cmd and paste in the results?

**Comment by molly-w** [comment] 2020-11-04 02:22
> Can you run `ver` in cmd and paste in the results?

![tempsnip](https://user-images.githubusercontent.com/63043224/98061768-a0ac5980-1e87-11eb-9472-5f1bd5ee95b8.png)

**Comment by Juniorkz13** [comment] 2021-05-20 20:38
Any fix for this? Having the same issue...

**Comment by Tyriar** [comment] 2021-05-25 12:57
Does the same thing happen in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)?

**Comment by molly-w** [comment] 2021-05-31 08:27
I don't try that, but the existed Terminal on my machine like cmd and powershell both has this problem.

**Comment by Tyriar** [comment] 2021-06-02 13:20
If it happens in Windows Terminal you would need to report it to https://github.com/microsoft/terminal

**Closed** 2021-06-10 11:27 UTC
Labels: bug, needs more info, terminal, windows
