### ISSUE TITLE
Test Explorer buttons don't show

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#78651] opened 2019-08-07 17:30 UTC
@rschiefer commented on [Tue Aug 06 2019](https://github.com/microsoft/vscode-python/issues/6880)

## Environment data

- VS Code version: 1.36.1
- Extension version (available under the Extensions sidebar): 2019.8.29288
- OS and version: Windows_NT x64 10.0.18362
- Python version (& distribution if applicable, e.g. Anaconda): 2/3

## Expected behaviour

Test explorer buttons/icons show normally for python unittest tests.

## Actual behaviour

When VSCode is started from folder in WSL ("code .") the buttons in the test explorer dont' show.

![image](https://user-images.githubusercontent.com/1071761/62591118-3081e300-b894-11e9-9ade-e3911c9b25e9.png)

## Steps to reproduce:
1. Open VSCode from WSL folder ("code .")
2. Go to Test Explorer and see the buttons/icons don't show
3. Close folder in VSCode then reopen to see buttons/icons 

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Info Python Extension: 2019-08-06 21:46:16: autoSelectInterpreter, Class name = f, completed in 657ms, Arg 1: undefined, Return Value: undefined
open-change.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
repl.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
refresh.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
debug.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
run-tests.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
console.ts:134 [Extension Host] Info Python Extension: 2019-08-06 21:46:23: Cached data exists ActivatedEnvironmentVariables, /mnt/c/Users/rschiefer/suture/suturesign-providerdata/Suture.DataPipeline.Provider
```

**Comment by DonJayamanne** [comment] 2019-08-07 17:30
## This isn't an extension issue

**Comment by octref** [comment] 2019-08-07 21:19
@alexr00 Possibly related to custom tree in https://github.com/microsoft/vscode/issues/78101?

**Comment by alexr00** [comment] 2019-08-08 07:40
Not related to the new tree since this is happening in 1.36.1. New tree adoption is in 1.37.0/insiders.

**Comment by alexr00** [comment] 2019-08-08 09:00
This is an issue with remote:
```
GET vscode-remote://wsl%2Bubuntu/home/alros/.vscode-server-insiders/extensions/ms-
python.python-2019.8.29288/resources/dark/start.svg 
net::ERR_NOT_IMPLEMENTED
```
If you open a folder in WSL you'll get that error with tree icons. If you open the same folder through recents, you won't get the error.

@jrieken did you do some icon fetching work that might be part of this?

**Comment by jrieken** [comment] 2019-08-08 09:14
/duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed** 2019-08-08 09:15 UTC
Labels: *duplicate
