### ISSUE TITLE
background-update for new version of VS Code in Ubuntu - or an apt-get repository

### ISSUE THREAD

**Issue by kaanoo2904** [Microsoft/vscode#7610] opened 2016-06-13 13:29 UTC
- VSCode Version: 1.3 Insider
- OS Version: Ubuntu 16.04

I use VS Code in both Windows and Ubuntu. In Windows, when a new version come, I click the update button and VS Code will be auto downloaded, installed and restarted when done. 
But in Ubuntu, we've to go to website, download a .deb and then install it manually. 
And that's a little annoyed since Insider channel gets new update every 2 days.

It'll be much better if we can have it automatically done like in windows - or even better - an apt-get repo for Linux systems.

**Comment by Tyriar** [comment] 2016-06-13 16:16
Duplicate of https://github.com/Microsoft/vscode/issues/2973

**Closed by Tyriar** 2016-06-13 16:16 UTC
Labels: feature-request
