### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by everdrone** [Microsoft/vscode#19753] opened 2017-02-02 21:29 UTC
- VSCode Version: 1.9
- OS Version: Windows 10

None of the installed extension are reloading, the `reload` button won't disappear.

![capture](https://cloud.githubusercontent.com/assets/22671061/22569176/cb17505a-e996-11e6-9f42-4f7a772293b8.PNG)

Anyway extensions are still on my machine, they just won't load.

**Comment by calebcartwright** [comment] 2017-02-03 00:57
Ditto

**Comment by calebcartwright** [comment] 2017-02-03 01:03
Might be a duplicate of #19685 (although that is 1.8.1) Mine was working just fine on 1.8.1, upgrade to 1.9 broke it

**Comment by tSte** [comment] 2017-02-03 08:38
The same here... but on Windows 8.1.

**Comment by M0ns1gn0r** [comment] 2017-02-03 10:07
The same for me, extensions broke after the upgrade (Win 8.1).

**Comment by sandy081** [comment] 2017-02-03 10:33
@everdrone Sorry that you get this unexpected experience. I am not seeing this behavior but I am on Mac. I would try to reproduce this on Windows. Mean while can you help us in knowing how did you get into this state... Are you seeing all installed extensions in Reload state after opening VS Code? Or there any steps to follow to get into this state. Thanks

**Comment by everdrone** [comment] 2017-02-03 10:42
@sandy081 There are no steps to follow to reproduce this behavior, i just opened VS Code and updated to 1.9 by clicking on the latest release popup message.

I also tried to start code with `code --disable-extensions`. tried to uninstall and reinstall some but nothing changed.

**Comment by tSte** [comment] 2017-02-03 10:56
@sandy081 It is very strange behavior, because:
- a colleague of mine did update right after me and she did not experience any problems at all (Win 10 x64)
- I tried to install back VSCode 1.8.1 and extensions did not have any "Reload" buttons, but they did not work. When I updated back to 1.9.0, extensions are still not working, and every one of them (except disabled ones) do have "Reload" buttons
- The `settings.json` does not recognize any extension-specific settings (it shows problems).
- Freshly installed extensions share similar behavior.

**Comment by sandy081** [comment] 2017-02-03 11:13
@tSte Thanks for sharing the information. Can you please open developer tools by doing
- Open command pallette (F1 or Ctrl+Shift+P)
- Look for the command `Toggle Developer Tools`
- Again open command pallette
- Look for command Reload Window

Look for any errors in the opened dev tools console, if there are please let us know.

**Comment by danielpunct** [comment] 2017-02-03 11:28
In my case it was because of an extension named Anloga, that could not be read properly. After I deleted the folder from extensions, from disk everything was ok.

**Comment by imaginarny** [comment] 2017-02-03 11:28
I experienced the very same problem on WIN10. I tried to update two PCs with almost identical VSCode setup. Both ended up with the same result.

Then I realized I had modified one of extensions to my likings and renamed to my very own. So you can consider it as a private and unpublished extension. Extensions like this one don't appear in VSCode extensions menu. Deleting the extension solved this issue.

So you could try the following:

* Check if you have any extension in your `%userprofile%\.vscode\extensions` folder which doesn't appear in VSCode extensions menu  
* Try to delete or move it from the folder and then restart VSCode

**Comment by tSte** [comment] 2017-02-03 11:28
For old extensions:
> mainThreadExtensionService.ts:110Failed to parse C:/Users/.../.vscode/extensions/vsdarkmod/package.json:

 _(this is my old theme from legacy times - I did not even realize that it is still there)_

> mainThreadExtensionService.ts:110
> TypeError: Cannot set property 'isBuiltin' of undefined
>     at t.validate (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:9146)
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:9835
>     at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
>     at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)
>     at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
>     at _error (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17256)
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:27555
>     at C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\graceful-fs\polyfills.js:284:29
>     at FSReqWrap.oncomplete (original-fs.js:123:15)

For freshly re-installed extensions:
Nothing except some keybinding warnings (Ctrl+Alt stuff) and two logs by extensions (activated csproj and vscode-icons)

**Comment by sandy081** [comment] 2017-02-03 11:39
@tSte Thanks for sharing the information, I will try to investigate why this is happening after upgrading to 1.9.

**Comment by sandy081** [comment] 2017-02-03 12:13
@aeschli Do you think is it related to the change [here](https://github.com/Microsoft/vscode/commit/3a67f92f5b52efc9929757d53df74a54bbd61f07)

**Comment by sandy081** [comment] 2017-02-03 12:14
@tSte Is it possible to provide the contents of package.json of that vsdarkmod extension?

**Comment by sandy081** [comment] 2017-02-03 12:34
@aeschli Looks like, forgot to return `null` for invalid extensions description jsons and is returning `undefined`. Unfortunately, our validator is checking only for `null`.

**Comment by tSte** [comment] 2017-02-03 12:46
@sandy081 I am sorry, but I can't :( `Shift+delete`-ed entire extension... I might have some backup on my external HDD though...

**Comment by sandy081** [comment] 2017-02-03 12:51
@tSte No worries.. I got the steps to reproduce it

- Open `package.json` of any extension from the installed extensions folder
- Edit it to make it invalid json.

Open VS Code and you see this behavior.

**Closed** 2017-02-03 13:29 UTC
Labels: bug, candidate, extensions, important

**Comment by sandy081** [comment] 2017-02-03 16:01
Pushed to 1.9 branch & master

**Comment by aeschli** [comment] 2017-02-07 11:42
verified in 3e400cc8ceefbb4440fe00f1d58002feea20c333

**Comment by gerane** [comment] 2017-03-06 16:10
I just upgraded to 1.11 and this is now happening on windows 10

**Comment by aeschli** [comment] 2017-03-07 09:31
@gerane Can you file a new issue with more information?
