### ISSUE TITLE
Korean characters [각간갇갈감갑갓강갖갗갘같갚갛] rendering issue

### ISSUE THREAD

**Issue by wonhyeongseo** [microsoft/vscode#72083] opened 2019-04-10 14:36 UTC
Issue Type: <b>Bug</b>

Hello, this is similar to #10769 except I couldn't find a solution.
I've opened an [issue on ibus](https://github.com/ibus/ibus/issues/2091), however from the reply I guess it isn't an IME issue like #10769 suggested.

Steps to reproduce: is the same as #10769

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.20GB (1.64GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.0
vsc-material-theme|Equ|2.8.2
gc-excelviewer|Gra|2.1.32
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
vscode-jest|Ort|2.9.2
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0
rust|rus|0.6.1
quokka-vscode|Wal|1.0.205
vscode-todo-highlight|way|1.0.4

</details>

**Comment by wonhyeongseo** [comment] 2019-04-17 04:34
Hello, are there any new updates to this issue?

**Comment by wonhyeongseo** [comment] 2019-05-11 09:58
Upon writing markdown, I noticed that in the preview tab, the characters render correctly! I hope this helps in solving the issue. Thank you very much.
![correctmarkdownpreviw](https://user-images.githubusercontent.com/29195190/57568174-aeae2500-741e-11e9-88e0-27aab90510fb.png)

**Comment by wonhyeongseo** [comment] 2019-06-17 09:46
In addition to the above, I found '갓' [gad] rendered to '가ㅆ' [gat] and '강' [gang] rendered to '가ㅈ' [ga-d]

**Comment by poby13** [comment] 2019-07-31 06:12
Same problem.

VS Code version: 1.36.1
OS Version: Linux Mint 19.2, Ubuntu 18.04

**Comment by alexandrudima** [comment] 2019-08-09 06:05
The preview tab uses a different font than the editor. For me, on the mac this gets rendered OK:
![image](https://user-images.githubusercontent.com/5047891/62757686-75686e00-ba7c-11e9-817d-fb9b9a505c87.png)

Have you tried using a different `editor.fontFamily` ?

**Comment by NEONKID** [comment] 2019-08-09 06:21
![Screenshot from 2019-08-09 15-21-00](https://user-images.githubusercontent.com/16149781/62758434-56d49800-bab9-11e9-9245-79d013065bde.png)

@alexandrudima 
Thanks, I have confirmed that there is a problem with the ```Droid Sans Fallback``` font in the default font-family used by Ubuntu. Since the font is excluded, it works normally. 

I think there is a problem with this font.

**Comment by alexandrudima** [comment] 2019-08-09 13:12
@NEONKID Thank you for following up. IIRC we added the fallback one `Droid Sans Fallback` for some emojis and special runic characters... I am sorry that it has issues with Korean characters...

But now that you could resolve it by simply tweaking the font family, I would close this on our side...

**Closed by alexandrudima** 2019-08-09 13:12 UTC
Labels: linux, needs more info
