### ISSUE TITLE
Copilot chat does not render LaTeX correctly

### ISSUE THREAD

**Issue by billti** [microsoft/vscode#223370] opened 2024-07-23 18:57 UTC
- VS Code Version: 1.91.1
- OS Version: macOS 14.5

LaTeX renders well in most GPT environments, and copilot is also trying to render LaTeX in VS Code chat agent, however it does not render correctly there. We are trying to build a chat agent the often returns equations in LaTeX form, so this is a major issue for us.

Steps to Reproduce:

1. Provide a prompt in the Chat sidebar that results in some LaTeX (my initial prompt below was `I'm writing a physics simulator, what is the correct equation to use to calculate a trajectory of an object?`)
2. Observe that it doesn't render correctly (see below bullet list after I informed it that it wasn't rendering correctly and it tried again with the same results)

<img width="584" alt="image" src="https://github.com/user-attachments/assets/87a1e665-d201-4703-9afb-f63dc99c4329">

**Comment by mjbvz** [comment] 2024-07-23 19:58
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/978

**Closed by mjbvz** 2024-07-23 19:58 UTC
