### ISSUE TITLE
How to detect shift shift key in VSCode?

### ISSUE THREAD

**Issue by kasecato** [microsoft/vscode#5280] opened 2016-04-14 22:11 UTC
- VSCode Version: 1.0.0
- OS Version: OS X El Capitan 10.11.4

Steps to Reproduce:

I'm trying to bind `quick open` (ctrl+p) command to `shift shift` (shift x2) keys like IntelliJ IDEA in VS Code Extension (TypeScript).

But `vscode.commands.registerCommand('type', (args) => args.text)` can't detect shfit key.

How can I detect shift shift key?

``` typescript
// VSCode v0.10.12 or higher (not working <= v0.10.11)
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('type', (args) => {

        vscode.window.showInformationMessage(args.text);

        vscode.commands.executeCommand('default:type', {
            text: args.text
        });
    });

    context.subscriptions.push(disposable);
}
```

**Comment by alexandrudima** [comment] 2016-04-28 11:23
That is a cool idea. Currently, the keybinding dispatching ignores only modifier keys (does not try to dispatch them unless they are accompanied by a non-modifier key).

**Comment by jpoon** [comment] 2016-09-12 09:11
@alexandrudima With the Vim extension, users can remap their vim keybindings. We're discovering that some key combinations don't get dispatched to the extension: https://github.com/VSCodeVim/Vim/issues/757. Particularly, `Ctrl` (ie. `Ctrl+a`). The only modifiers that seem to be dispatched are `Alt` and `Shift`.

**Comment by alexandrudima** [comment] 2016-09-12 10:54
@jpoon the keybindings.json use key codes. `ctrl-a` is correctly dispatched to extensions. e.g. here I have an extension that registers `ctrl-t` and it works correctly -- https://github.com/alexandrudima/vscode-lcov/blob/master/package.json#L109.

This issue is regarding registering a keybinding in the form of `shift shift` where only modifier keys are pressed.

Registering `type` is a take all or nothing. It is possible to unregister it via calling disposing the registration.

**Comment by jpoon** [comment] 2016-09-12 18:30
(this likely belongs in a separate issue, let me know if you want to move it)

What I mean is that registering  `type`, the `alt` and `shift` modifiers are dispatched. However, if you want to bind to the `ctrl` modifier, you need to make a separate entry in the `package.json` like you suggested above. Why does this need to be a separate action? It'd be great if `ctrl+key` also go through the `type` register.

As for the more than one question, what I'm seeing is:
1. I have VSCodeVim installed which registers the `type` command
2. I develop a new extension that attempts to also register the `type` command
3. When I run my new extension, VSCode spits out an error saying that the `type` ID is already spoken for.
This seems to imply that only one extension at a time can register the `type` command?

**Comment by alexandrudima** [comment] 2016-09-13 09:41
@jpoon This has a very simple reason. It is driven by our platform (web browser). Pressing a key combination can end up generating the following DOM events:
* `keydown`
* `keypress`
* `input`
* `compositionstart`
* `compositionupdate`
* `compositionend`
* `keyup`
* maybe more, every couple of years, a few new ones pop up, or new properties are added to them.

It all depends on the keyboard layout you have installed and the key combinations you press. For example:
* in the US keyboard layout, pressing `a` will generate a `keydown`, a `keypress`, an `input` and a `keyup`
* in the US keyboard layout, pressing `ctrl+a` will generate a couple `keydown`s and a couple `keyup`s
* the rule of thumb mostly is that a `keypress` and a `input` is sent if the key combination produces a visible character... mostly... you see sometimes even `Escape` produces a `keypress` even if it doesn't produce any visible input.
* in the Japanese/Hiragana IME, typing `sennsei` will generate many `keydown`s and `keyups`, a `compositionstart`, followed by multiple `compositionupdate`s, sometime a few `input` events and finally a `compositionend`
* the rule of thumb mostly is that you get visible produced characters in `compositionupdate` and in `input` events, meanwhile in `keydown` and `keyup` events you get **key codes**.
* Key codes basically consist of a number, for example key code `36` is sent when pressing the `Home` key. 
* As far as I could tell, the numbers sort of follow the values defined at https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx but of course they vary across browsers and Operating Systems
* the key codes are sort-of keyboard layout independ, except when they're not, because w3c thought it would be something too difficult for websites to deal with, so they dropped in this beauty -- http://www.w3.org/TR/DOM-Level-3-Events/#h-optionally-fixed-virtual-key-codes -- which for exampel Chromium has decided to implement, but only on macs! 

The relevant code is at:
* https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/keyboardEvent.ts#L12
* https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/keyCodes.ts#L22
* https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L39
* https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/textAreaHandler.ts#L130
* https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/controller/keyboardHandler.ts#L73
* some native stuff to make UI labels as close as possible to what the keyboard has likely printed on the physical key:
  * https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/electron-browser/nativeKeymap.ts#L212
  * https://github.com/Microsoft/node-native-keymap

I am certain there must be things I've missed in how this works, so I would love PRs improving things, while keeping in mind that everything must work in Windows, Linux, OSX, on Chrome, on IE9-11, on Edge and on Firefox.

I bubble this up in two conceptual different ways:
* `keybindings.json`: These are all interpreted on the `keydown` events, meaning they all work with **key codes**. So when you bind `ctrl+]` it really means `ctrl+VK_OEM_6`, in other words `ctrl+0xDD`. When the browser sends my way a `keydown` with the `e.keyCode` === `0xDD` and the `e.ctrlKey === true` I will invoke your command.
* `type`, `compositionstart` and `compositionend` - I have added these to our API for VIM emulation. They were not part of the API, but they are the only means to get visible input. If you are using these for something else than VIM, please don't. If necessary, I can throw in the registration of the command and check which extension registers these and have a whitelist. Most likely what you want needs to be a feature request that should be implemented through some other (possibly new) API.

**Comment by hastebrot** [comment] 2016-09-26 14:01
Indeed, would be nice if we could define this key binding in `keybindings.json`:

~~~json
{ "key": "shift shift", "command": "workbench.action.quick" }
~~~

**Comment by deecewan** [comment] 2017-06-04 07:28
Any progress on this?

**Comment by huy-lv** [comment] 2017-10-17 09:14
@hastebrot it does not work on vscode 1.17.1

**Comment by MrChriZ** [comment] 2017-10-31 14:07
Would like to see this.

**Comment by jedlikowski** [comment] 2017-12-19 10:55
Looks like Google Chrome now sends a keydown event when just the Shift key is pressed, with code 13. Should this be possible to implement now?

**Comment by gdbjohnson** [comment] 2018-01-21 20:21
I'll just add my ditto to this.

**Comment by Varkal** [comment] 2018-03-14 16:34
Any news on this ? (I'll wait relentlessly for this feature)

**Comment by MrBlaise** [comment] 2018-03-19 08:17
I would love this as well!

**Comment by jabacchetta** [comment] 2018-06-23 21:37
WebStorm's "search everywhere" feature with the `shift shift` shortcut combination is the one last feature I find myself missing in VS Code.

Using `shift shift` with quick open would be great.

**Comment by FlorisWarmenhoven** [comment] 2018-07-11 09:10
I'm currently using a workaround, taking advantage of BetterTouchTools.

You can mimic this behaviour by adding a new shortcut, in BTT and selecting the 'Key Sequence' (inside the keyboard tab).

![image](https://user-images.githubusercontent.com/15650071/42561937-c1a6adb2-84fa-11e8-83f2-f3d13c52a301.png)

Then press 'Record New Key Sequence' and press shift > shift. This is what it will look like. I didn't touch any of the settings.

![image](https://user-images.githubusercontent.com/15650071/42562011-e6d8c052-84fa-11e8-92fb-cf6f0c58f59e.png)

Save it, bind it to a key combination inside of VScode (I believe it's CMD + P by default). Et voilá! You have your desired functionality.

Of course, it would still be nicer if this was natively supported in VSCode without having to use third party software. Figured I'd share my solution anyway.

**Comment by leanderr** [comment] 2018-07-26 13:12
Workaround for Windows:
- Install Autohotkey
- Paste this in an Autohotkey Script
- Double Shift will result in CTRL+P being fired.

`
lastShift := 0
$Shift::
if ((A_TickCount - lastShift) <= 250)
	Send ^p
else
	Send {Shift}
lastShift := A_TickCount
return
`

**Comment by gulshan** [comment] 2018-10-04 03:40
I proposed something similar in #29407 which was closed. Did not see this issue. My +1.

**Comment by loopmode** [comment] 2019-03-01 11:00
I came here from https://github.com/Microsoft/vscode/issues/68832 ("Double Tap Commands"), which was closed as duplicate of this.

Not sure whether it fits into this issue, but I would suggest a somewhat different new feature: "Multi Tap Commands". 

I'd love to be able to bind this in `keybindings.json`:
```
  { "key": "ctrl+2*right",  "command": "workbench.action.splitEditorRight" }
```

I guess `2*shift` is just a special case of that.

Implementation _could_ be straight-forward. Avoiding performance issues shouldn't be too hard. Not sure about the syntax change to support some modifier like `/[0-9]\*/` or multi-platform support, but I guess it can all be robustly implemented. 

I guess there should be a new setting, e.g. "Multi Tap Detection Timeout" with a sensible default value and possible some restrictions, like a maximum allowed value, or that it's only available with modifier keys (to avoid false detections when typing..).

Then.. Some kind of global manager would have to detect multiple `keydown` events with the same keyCode using that occur within the timeout duration.

I guess there would be many useful possibilities.
I just want to split my editor into a second view using the arrow keys, but why not deploy your project to the staging server using `ctrl+shift+4*up`?

Lot's of guessing all in all.. it might also just be a can of worms. 😄

**Comment by mpivchev** [comment] 2019-03-22 22:31
Is there gonna be any update on this?

**Comment by rusnasonov** [comment] 2019-04-16 15:34
Another workaround for OSX using [Karabiner](https://pqrs.org/osx/karabiner/index.html).

Add this code to `rules` section in `$HOME/.config/karabiner/karabiner.json`

```
{
    "description": "double left shift to cmd+shift+p in VSCode",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "p",
                    "modifiers": [
                        "left_command",
                        "left_shift"
                    ]
                }
            ],
            "conditions": [
                {
                    "type": "variable_if",
                    "name": "left_shift pressed",
                    "value": 1
                },
                {
                    "type": "frontmost_application_if",
                    "bundle_identifiers": [
                        "^com\\.microsoft\\.VSCode$"
                    ]
                }
            ]
        },
        {
            "type": "basic",
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "set_variable": {
                        "name": "left_shift pressed",
                        "value": 1
                    }
                },
                {
                    "key_code": "left_shift"
                }
            ],
            "to_delayed_action": {
                "to_if_invoked": [
                    {
                        "set_variable": {
                            "name": "left_shift pressed",
                            "value": 0
                        }
                    }
                ],
                "to_if_canceled": [
                    {
                        "set_variable": {
                            "name": "left_shift pressed",
                            "value": 0
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by leeIco3** [comment] 2019-04-25 07:22
It would be great if this was supported on linux, ive missed search being double shift since moving from phpstorm.

**Comment by jonasmellquist** [comment] 2019-04-27 07:00
As @rusnasonov mentions Karabiner works like a charm
`brew cask install karabiner-elements`

Nest his snippet under _profiles_ -> _complex_modifications_ -> _rules_

With Karabiner it's possible to actually make Caps Lock relevant again :)
https://github.com/suliveevil/Capslock
https://github.com/pqrs-org/KE-complex_modifications

**Comment by leeIco3** [comment] 2019-04-29 07:05
@jonasmellquist 
Unfortunately thats only for macOS, I am using Ubuntu so am still hoping this gets fixed natively.

**Comment by dilroop** [comment] 2019-06-19 22:55
WE NEED DOUBLE SHIFT

**Comment by magdumnikhil** [comment] 2019-07-18 16:35
Even I think this would be great if implemented. User actions would be quicker.
Please conside this feature request.

**Comment by episodeyang** [comment] 2019-08-30 12:39
Feel bad for knocking off JetBrains, but they double-shift is really quite a killer feature.

**Comment by ninodinatale** [comment] 2019-08-31 10:00
> Feel bad for knocking off JetBrains, but they double-shift is really quite a killer feature.

This. Double-anything is - at least for me - a killer feature since I remapped a hell of a lot key bindings to double-command, double-option, double-control etc.

**Comment by jcollum-autodesk** [comment] 2019-10-02 21:50
I know it sounds a little defeatist but 2 years later and not much discussion from the team in a very large thread... Looks like you'll need to find an OS-specific workaround if you miss this feature from your IntelliJ days. I've used Karabiner in the past, it's good, give that a shot if you're on OSX.

**Comment by lenowng** [comment] 2019-10-23 03:39
migrated to fully use VSCode from Intellij lately and looking for the killer shortcut of `shift+shift` for `Go To File..`

+1 feature

**Comment by Akopylowe** [comment] 2019-11-13 12:17
Really for 3 years there is nothing?

**Comment by jonitiso** [comment] 2019-11-15 16:43
i want double shift please

**Comment by vargavince91** [comment] 2019-11-22 14:10
I usually feel bad for `+1` comments, but it feels like the double shift feature is not unreasonable.

I am/was using JetBrains products, and I know many of the keyboard shortcuts from their products. I'm now developing with TypeScript and honestly, vscode is great at handling .ts files. I don't want to re-learn all the key bindings, though, especially as for some languages, JetBrains editors just work better, so most likely, I'm going to use both editors.

**Comment by MarcoMatarazzo** [comment] 2019-11-25 14:53
As a generalization, it would be lovely to be able to actually use any modifier as a shortcut even when used alone. A shift-shift would then be just a chord of "shift" and "shift". I would also love to have a Textmate2-style vertical selection toggle (it's a plugin with it's own custom shortcut) pressing just ALT, once.

**Comment by Rody66** [comment] 2019-11-26 19:31
Here is an improved script from @leanderr for AutoHotkey:
It sends Ctrl+P when double shift is pressed.
```c
lastShift := 0
$Shift::
if ((A_TickCount - lastShift) <= 250 && IsVSCode()) {
    Send ^p ; or use ^n for goto symbol
} else {
    Send {Shift}
}
lastShift := A_TickCount
return

IsVSCode()
{
    WinGetActiveTitle, Title
    return InStr(Title, "Visual Studio Code")
}
```

And the next script calls Go To Definition when Mouse Middle Button is clicked.
```c
$MButton::
    goto_definition() {
        toolbarHeight := 110
        MouseGetPos, xpos, ypos
        if (IsVSCode() && ypos >= toolbarHeight) {
            Send {LButton}
            Send {F12}
        } else {
            Send, {MButton}
        }
    }
return

IsVSCode()
{
    WinGetActiveTitle, Title
    return InStr(Title, "Visual Studio Code")
}
```
The full script is in attachment.
[VSCodeDoubleShift.zip](https://github.com/microsoft/vscode/files/3893702/VSCodeDoubleShift.zip)
For win users just add it to auto start:
Win+R, type regex, go to 'Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' and add new String Value "C:\Program Files\AutoHotkey\AutoHotkey.exe" "HERE_PATH_TO_SCRIPT\VSCodeDoubleShift.ahk".
And don't forget to install AutoHotkey.

**Comment by arroyocode** [comment] 2019-12-02 08:32
+1 for double shift!

**Comment by saschamander** [comment] 2020-01-10 12:11
+1

**Comment by aloktripathy** [comment] 2020-01-19 14:12
+1

**Comment by MostHated** [comment] 2020-01-25 01:54
> 
> 
> Here is an improved script from @leanderr for AutoHotkey:
> It sends Ctrl+P when double shift is pressed.
> 
> ```c
> lastShift := 0
> $Shift::
> if ((A_TickCount - lastShift) <= 250 && IsVSCode()) {
>     Send ^p ; or use ^n for goto symbol
> } else {
>     Send {Shift}
> }
> lastShift := A_TickCount
> return
> 
> IsVSCode()
> {
>     WinGetActiveTitle, Title
>     return InStr(Title, "Visual Studio Code")
> }
> ```
> 
> And the next script calls Go To Definition when Mouse Middle Button is clicked (it's very useful and taken from IntelliJ too).
> 
> ```c
> $MButton::
>     goto_definition() {
>         toolbarHeight := 110
>         MouseGetPos, xpos, ypos
>         if (IsVSCode() && ypos >= toolbarHeight) {
>             Send {LButton}
>             Send {F12}
>         } else {
>             Send, {MButton}
>         }
>     }
> return
> 
> IsVSCode()
> {
>     WinGetActiveTitle, Title
>     return InStr(Title, "Visual Studio Code")
> }
> ```
> 
> The full script is in attachment.
> [VSCodeDoubleShift.zip](https://github.com/microsoft/vscode/files/3893702/VSCodeDoubleShift.zip)
> For win users just add it to auto start:
> Win+R, type regex, go to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` and add new String Value `"C:\Program Files\AutoHotkey\AutoHotkey.exe" "HERE_PATH_TO_SCRIPT\VSCodeDoubleShift.ahk"`.
> And don't forget to install AutoHotkey.

If anyone is like me and isn't a fan of messing with the registry more than necessary, you can press Win+R and put in "shell:startup" (without quotes), then in the window that comes up is shortcuts to applications that will start automatically. Right click and pick New, then Shortcut. It will have a box in which you can input the path to an application. There you can put in "C:\Program Files\AutoHotkey\AutoHotkey.exe" "HERE_PATH_TO_SCRIPT\VSCodeDoubleShift.ahk" (with the quotes) and it will start up automatically as well without changing the registry manually.

**Comment by RUSshy** [comment] 2020-03-11 21:22
more i use vscode, i become even more frustrated knowing such basic feature is not possible
it stacks up, what is this editor supposed to be? i see new updates every month, and yet nothing concrete

**Comment by randohinn** [comment] 2020-03-20 19:31
This is one thing that currently makes phpstorm good for me. Won't probably switch to VSCode until this is happening.

**Comment by istvandesign** [comment] 2020-03-27 16:54
I also want this for the new search editor, in IntelliJ it also copies the currently selected text into the search which is extremely useful.

**Comment by xxSkyy** [comment] 2020-04-13 14:23
Still waiting for ot, Happily now I can developing Ruby on Rails on both Mac and Windows cause wonderful WSL2, but sadly RubyMine doesnt work well with WSL so I had to move to VSCode on windows.
I'm not really into hotkeys for this. 
Shift shift is a killer to me. And I can bind double caps lock but why I cant double shift.

**Comment by somadeaki** [comment] 2020-04-14 16:10
Please implement this feature! It's been 4 years. Shift-shift doesn't sounds like that big of a deal, but it is incredibly convenient.

**Comment by jwang-net** [comment] 2020-05-07 16:52
Cosign on adding double shift

**Comment by tconroy** [comment] 2020-05-11 15:48
Lacking native support, are there any plugins / alternatives to accomplish this functionality? Would make switching between IntelliJ and VSCode much easier :)

**Comment by marcoValkyriweb** [comment] 2020-05-12 08:56
^ I'm frequently swapping between Jetbrains suite and VS Code (using Rider C# API and VS Code for Vue development), would be really nice to be able to keybind double shift to ctrl+p.

**Comment by bhagatparwinder** [comment] 2020-05-13 23:19
I fully support this mission. Double shift is so intutive to do!

**Comment by DoctorLogiq** [comment] 2020-05-24 00:19
+1 on double-shift. Ctrl+P is a 2-handed operation (unless you're one of those absolute **heathens** who actually **uses** Right-Ctrl) Shift-Shift is a one-handed operation, takes less brainpower and is just easier in every way!

**Comment by heartacker** [comment] 2020-06-16 08:31
additionally. how can I bind a shortcut `alt+space` as Suggestion shortcut  in VSCode, because  `ctrl+space` was binding as `IME chinese-english-switch` by WindowsOS-**CHINESE**-VERSION?

**Comment by xxSkyy** [comment] 2020-06-22 12:08
> additionally. how can I bind a shortcut `alt+space` as Suggestion shortcut in VSCode, because `ctrl+space` was binding as `IME chinese-english-switch` by WindowsOS-**CHINESE**-VERSION?

just disable this shortcut in windows settings

**Comment by lajcf** [comment] 2020-06-25 20:58
Incredibly useful feature, please implement it <3

**Comment by devnoot** [comment] 2020-07-01 21:59
If someone PRs this can it get merged in? `ctrl+p` blows in comparison to `shift shift`

**Comment by bartekpacia** [comment] 2020-09-13 18:20
+1, I want this badly

**Comment by Tandolf** [comment] 2020-09-18 15:59
Seriously Microsoft, for 4 years the community has asked for this and you havn't even responded.

**Comment by lon9man** [comment] 2020-09-18 16:24
Microsoft waits before some startup implements it and after that MS will buy them as company:)

**Comment by gulshan** [comment] 2020-09-22 10:39
The first comment was really promising-
>That is a cool idea. Currently, the keybinding dispatching ignores only modifier keys (does not try to dispatch them unless they are accompanied by a non-modifier key).

So technically, if the modifier keys are dispatched to bindings regardless of being accompanied by non-modifier keys, <kbd>Shift</kbd>, <kbd>Shift</kbd> or <kbd>Ctrl</kbd>, <kbd>Ctrl</kbd> keybindings become possible.

**Comment by TheEarlyNerd** [comment] 2020-09-28 17:15
This feature would be great.

**Comment by isycat** [comment] 2020-10-14 11:54
Genuine question: Does anyone have background on why such a popular and old request has not been acknowledged?

**Comment by luikore** [comment] 2020-10-16 03:23
With so much frustration I think:

- The internal architecture of VSCode must be very messy, so that no one can implement such simple features easily. (another example: API to get a list of open tabs)
- Developers are more focused on adding fancy features like "hover window" instead of the most fundamental usability problems.

**Comment by zillionare** [comment] 2020-11-21 09:13
+1 for this minor feature, really helpful

**Comment by ddadon10** [comment] 2020-11-22 15:04
@alexdima: How can we help you to implement this feature? Do you think the limitations you raised in 2016 are still around today? Thanks a lot 🙂

**Comment by g0rba4ev** [comment] 2020-11-27 22:19
+1 for this minor feature, really helpful

**Comment by FabianKoehnen** [comment] 2020-12-09 07:01
+1

**Comment by Alin01x** [comment] 2020-12-10 21:58
+1

**Comment by Curve** [comment] 2020-12-10 23:12
Could you guys stop writing `+1` and just use the reactions and "upvote" the post that way?
If you have nothing relevant just don't write anything in order to not spam the thread.
Thank you.

**Comment by RUSshy** [comment] 2020-12-11 03:02
@Curve it doesn't matter, Microsoft keep ignoring this post, so let's make it the most commented one, so someone at BlindAndBloatedSoft will maybe see it

+1

**Comment by MostHated** [comment] 2020-12-11 03:19
> @Curve it doesn't matter, Microsoft keep ignoring this post, so let's make it the most commented one, so someone at BlindAndBloatedSoft will maybe see it
> 
> +1

+1

**Comment by Curve** [comment] 2020-12-11 06:26
> @Curve it doesn't matter, Microsoft keep ignoring this post, so let's make it the most commented one, so someone at BlindAndBloatedSoft will maybe see it
> 
> +1

If it doesnt matter because they'll ignore it commenting `+1` wont really change anything either.
The only thing It'll do is spam everyones emails...

**Comment by backops-threed** [comment] 2021-01-03 00:06
+1

**Comment by andersonpem** [comment] 2021-01-12 20:29
+1 for this too.

**Comment by coding-for-money** [comment] 2021-01-19 07:31
why not use  commond+t?

**Comment by Curve** [comment] 2021-01-19 08:26
> why not use commond+t?

Because double shift is more convenient and a lot of developers are used to it because they used jetbrains products.

**Comment by PathToLife** [comment] 2021-01-24 12:50
I instinctively double press shift when I open vscode, all the time!

`⌘ + P` requires two hands
`Left-Shift, Left-Shift ` one hand

hopefully can bump up the priority for this command

**Comment by PathToLife** [comment] 2021-01-24 14:22
<img width="1868" alt="image" src="https://user-images.githubusercontent.com/12622625/105633124-beec8900-5ebb-11eb-93d3-561e90e9e9ae.png">

https://github.com/PathToLife/vscode/commit/5ed3c977bdcce2f9380fd9cfaea94097329ef167

This hack will make it work. I spent only 1 hour at 2am on this. please only look at it as a starting point ;)

Bugs (Known):
- will cause ctrl+shift+p to trigger ctrl+shift as a seperate shortcut.

Cons:
- will cause every shift press to activate as a cord

**Comment by PathToLife** [comment] 2021-01-25 04:23
Complexities of implementing this:

I originally thought that using the Chord system, which is the double key combination detection system "Ctrl+K, Ctrl+D", might be doable... but it turns out, no, here's why

Shift+AlphaNumeric will not work if shift was in Chord mode:
- If you press "shift" once, then press "shift+a" within 5 sec (to type uppercase A), then the quickOpen will trigger, typing A in the quickOpen window, instead of the editor window

Unwanted trigger when holding shift:
- holding shift will fire off "shift shift" on the dispatch() function repeatedly, therefore quickOpen will trigger

VSCode's underlying keybinding system does not check the time between key presses.
Therefore it's impossible to differentiate between 'rapid presses' of key, vs slow press.

Need to do a architecture modification while making sure that there's no regressions with existing keybindings, and with cross-platform mac, linux, windows, and with different country keyboards. :)

**Comment by yume-chan** [comment] 2021-01-25 04:36
I think shift + shift can only be implemented as a special case, like how alt + mouse click works.

And only shift + nothing should count as the first shift hit, means it must be processed in keyup event. The second is maybe able to be dispatched in keydown event.

**Comment by trajano** [comment] 2021-01-25 21:18
Maybe we should have a `+nothing` capability doesn't have to be in the GUI I can/should be able to put it in keybindings.json as 

    {
        "key": "shift+nothing shift+nothing",
        "command": "workbench.action.quickOpen"
    },

**Comment by yume-chan** [comment] 2021-01-26 17:09
> Maybe we should have a +nothing capability doesn't have to be in the GUI I can/should be able to put it in keybindings.json

I still don't think this will fit into Code's keybinding system.

1. `+nothing` is a special case that can only be detected in keyup (so you know there is no other keydown's in between), while all existing key bindings trigger at keydown
2. `shift+nothing shift+nothing` means you can wait arbitrary time between two keys, but generally we want two `shift` presses to happen within a short time span: the chance of hitting `shift` by mistake is much higher than other key combos, in this case requiring pressing an extra (any) key to cancel the chord is not convenient. Not mention that Chinese IMEs all use `shift` key to switch between Chinese and English input mode, so you really don't want to care about a _single_ `shift` press, only two.

But I still think a special case for `shift + shift` is feasible. Code already have many mouse shortcuts and keyboard + mouse shortcuts that are hardcoded (#3130). I think it possible to also hardcode `shift + shift` at first, and find better ways to generalize it in future. It maybe even simpler than modifying the already very complex keybinding system.

**Comment by PathToLife** [comment] 2021-01-26 17:52
> But I still think a special case for `shift + shift` is feasible.

Agreed, I'm thinking of implementing it as @hastebrot mentioned:
`{ "key": "shift shift", "command": "workbench.action.quickOpen" }`

> I think it possible to also hardcode `shift + shift` at first, and find better ways to generalize it in future.

I think by adding extra compatibility for other modifier keys such as the below will be a must to keep keybinds somewhat intuitive.
`{ "key": "ctrl ctrl", "command": "some other action" }`
`{ "key": "alt alt", "command": "some other action" }`
perhaps even:
`{ "key": "esc esc", "command": "workbench close project" }`

Should make a timeout function that is started when a modifier key is pressed (perhaps modifiers only for now?), then if the same key is pressed within the time limit, it fires of a single resolve as usual...

Of importance is not to resolve the keybind database twice (the search for keybind functionality, mentioned in code as a resolver function), potential big performance / battery drain? 

So probably put some sort of hardcode here?
https://github.com/PathToLife/vscode/blob/caac9511a7345fb8037d339f86524f6bb954466e/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L194

Otherwise we could go up the tree and hardcode here?
https://github.com/PathToLife/vscode/blob/caac9511a7345fb8037d339f86524f6bb954466e/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L259

Is this the mouse hardcode?
https://github.com/microsoft/vscode/blob/c4b514244e2651117b9990295730265f5b902436/src/vs/editor/browser/view/viewController.ts#L66

**Comment by trajano** [comment] 2021-01-26 17:56
maybe have real specific cases that get fired rather than trying to parse it.  Something like

* DoubleLShift
* DoubleRShift
* DoubleLCtrl
* DoubleRCtrl
* DoubleLAlt
* DoubleRAlt
* DoubleLCmd
* DoubleRCmd

I differentiated between L and R side so there can be an alternate mapping for the other side of the keyboard.  Something like LShift LShift for QuickOpen and RShift RShift to search for commands

**Comment by PathToLife** [comment] 2021-01-26 22:28
Good news,

Initial working implementation in this commit.

Feel free to give it a go!
Works fine on my mac.

https://github.com/PathToLife/vscode/commit/ae426b39b18ada243bf04d5ba3803430a15b23fa

I'll clean it up a bit later, in hindsight after getting a little more familiar with the codebase, I realised I've added a bunch of unecessary code regarding keybind -> dispatch string.

**Comment by yume-chan** [comment] 2021-01-26 23:29
@PathToLife Good job!

Looked a little bit into your changes, I think there are actual two parts: "allow dispatching single modifier key" and "time sensitive key chords".

For the second part I have some new idea: allowing declare max allowed interval in keybinding.json, and even declaring multiple keybindings with same key chords, but different max allowed intervals, mapping to different commands. I think this will enable many more interesting usages.

The default value is `Infinite`, that's how all existing keybindings work. Dispatching single modifier key is not tied to time sensitive key chords, if a user very want that, they can still declare a `shift shift` with `Infinite` max allowed interval.

I saw some performance concern. Maybe we can pre-parse keybindings.json to a `Map` between each key and all possible keybindings starting with it, so smashing any key will only need a O(1) search? I didn't know how keybindings resolve now.

**Comment by PathToLife** [comment] 2021-01-27 03:23
Thanks for the suggestions @yume-chan 

> For the second part I have some new ideas: allowing declare max allowed interval in keybindings.json, and even declaring multiple keybindings with same key chords, but different max allowed intervals, mapping to different commands. I think this will enable many more interesting usages.
I

> 
> The default value is `Infinite` if omitted, that's how all existing keybindings work. Dispatching single modifier key is not tied to time sensitive key chords, if a user very want that, they can still declare a `shift shift` with `Infinite` max allowed interval.

To detect other duration,  need to use `dateTime().now() - lastSameKeyPressedDateTime` to get the duration of every double keypress, then firing a resolver to check for keybind `resolve(keybind, timeDoublePressed)` In case of backspace, prepare for lag.

> Dispatching single modifier key is only the part that dispatches modifier keys at keyup. Mixing single modifier key with a normal key combo in a single key chord should also be possible, considering current usage of keybindings.json.

I think the current architecture's decision to use only one keyboard event? is cleaner, don't want to play with more events than usual

> I saw some performance concern. Maybe we can pre-parse keybindings.json to a `Map` between each key and all possible keybindings starting with it, so smashing any key will only need a O(1) search? I didn't know how keybindings resolve now.

It is already O(1), `keybindKeyCodeTokeyString[keycode: int]: keyCodeString[] // pseudo code, not ts`

**Comment by yume-chan** [comment] 2021-01-27 03:45
I thought by default Code will wait for second chord forever, but that's not the case. Now there is a hardcoded 5s timeout

https://github.com/microsoft/vscode/blob/d03925a88cb2afa8adceebab08784e99c61ad372/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L149-L152

So adding time sensitive keybindings should be pretty easy. I will try that when I have time, and I believe this is the proper way toward dispatching single modifiers.

**Comment by yume-chan** [comment] 2021-01-27 05:40
I have done my time sensitive key chords implementation at https://github.com/yume-chan/vscode/commit/300dd011430c10238b0b829dde4ffe4f16638a92

The core part is only 5 lines long:

https://github.com/yume-chan/vscode/commit/300dd011430c10238b0b829dde4ffe4f16638a92#diff-7bda82440de1deb3c14304313cd37fed2299a8778cef3a9dc2004543c8a3c76bR133

```ts
enterTime: chordEnterTime,
```

Record when did the first key chord was pressed.

https://github.com/yume-chan/vscode/commit/300dd011430c10238b0b829dde4ffe4f16638a92#diff-1bea564a53de9969cb7e8758c4a6d68e3f57fbcd6302f4761338f63cd4fc1f42R288

```ts
timeElapsed <= candidate.timeout
```

Compare time between two chords with declaration. It requires a first chord, so smashing Backspace won't get here unless you really have a keybinding for `Backspace SomethingElse`. It only adds one extra comparison if you don't use time sensitive key chords, and several more if you do use.

https://github.com/yume-chan/vscode/commit/300dd011430c10238b0b829dde4ffe4f16638a92#diff-1bea564a53de9969cb7e8758c4a6d68e3f57fbcd6302f4761338f63cd4fc1f42R323

```ts
else if (candidate.keypressParts.length > 1 && candidate.keypressParts[1] !== null) {
  candidateChords.push(candidate);
  maxChordTimeout = Math.max(maxChordTimeout, candidate.timeout);
}
```

Gather all candidate second key chord when first chord was pressed. `candidateChords` is only used for logging and `maxChordTimeout` is only used to exit chord mode early, so these are not must have, I really need only the first two changes.

https://user-images.githubusercontent.com/1330321/105947980-20238080-60a5-11eb-8599-e188403f28b8.mp4

**Closed** 2021-02-02 14:23 UTC
Labels: feature-request, keybindings

**Comment by kasecato** [comment] 2021-02-02 23:41
Thank you so much!

**Comment by andersonpem** [comment] 2021-02-11 19:03
I tested it. It works like a charm. Thanks for everyone who supported this feature. Now I won't get crazy anymore trying to use PHPStorm shortcuts on VS Code and Code shortcuts on PHPStorm, since I use both very often.

**Comment by rzhao271** [comment] 2021-02-24 19:32
Verified, though it seems that the shortcuts must be set in the json file rather than using the keyboard shortcut editor.

**Comment by PathToLife** [comment] 2021-02-24 20:07
> Verified, though it seems that the shortcuts must be set in the json file rather than using the keyboard shortcut editor.

There are now two types of dispatchers in the system.
1. The [NEW] modifier dispatcher, which listens to the keyup event, and is used solely for shift shift, alt alt, ctrl ctrl, + mac
2. The [EXISTING] normal dispatcher, which listens to the keydown event, and is used solely for [something]+[something] or a chord: [something]+[something]&[something]+[something]

The decision to add the [NEW] modifier dispatcher is because the [EXISTING] normal dispatcher does not allow for rapid, single modifier shortcut events - this is because the chord system implementation interferes and gives unwanted behavior:

For example, after enabling single modifier key support on [EXISTING] normal dispatcher:
- Pressing Shift once - Will activate a chord, any Shift keydown within 5 sec will activate the shortcut
- Pressing Shift+a - will not type "A" as expected, the Chord system will activate and prevent dispatch of 'shift' and 'a'

This introduces the problem in that:
**The shortcut editor relies on [EXISTING] normal dispatcher, thus it cannot detect the [NEW] modifier dispatcher**

I did have a initial implementation that made it so that the shortcut editor did work, however a by product of this was that the chord system activated on every shift press - which we don't want to happen.

Any changes that give support to shortcut editor would be may overly complex - at least for me -, and I feel would be better to have in a separate PR :)

Or even better - an overhaul of the keybinds system, including removal of hacks for the alt-select (mouse keys + keyboard keys).

**Comment by PathToLife** [comment] 2021-03-08 12:40
Has been released as of vscode version 1.54.1 :)

put this in your keybindings.json:

```
    {
        "key": "shift shift",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "alt alt",
        "command": "workbench.action.showCommands"
    }
```

Not sure what to do with ctrl ctrl, yet :)

**Comment by RUSshy** [comment] 2021-03-08 18:37
thanks a lot! this makes migrating from intellij to vscode much easier, and it makes opening the thing mush easier, just one finger!

**Comment by greg-arroyo** [comment] 2021-03-08 19:00
This is nothing but awesome. Really appreciate the effort to add this!
