### ISSUE TITLE
Intellisense list is unorganized

### ISSUE THREAD

**Issue by johhansantana** [Microsoft/vscode#55708] opened 2018-08-02 21:41 UTC
- VSCode Version: 1.21.1
- OS Version: 10.13.3

Steps to Reproduce:

1. Try to import a module like:
<img width="643" alt="screen shot 2018-08-02 at 5 35 15 pm" src="https://user-images.githubusercontent.com/9933887/43612482-7b741762-967a-11e8-90de-22bc64e5d95e.png">
It will not show the list organized and actually not highlight anything related to the import object.

In a react component it will hightlight the last used option but it's still not organized:
<img width="611" alt="screen shot 2018-08-02 at 5 34 40 pm" src="https://user-images.githubusercontent.com/9933887/43612578-c3e739b6-967a-11e8-8b4b-0eaabe4bd970.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-08-03 08:26
Duplicate of #1304 I believe

You can also try pushing those snippet suggestions to the bottom of the list by setting: `"editor.snippetSuggestions": "bottom"`

**Closed by mjbvz** 2018-08-03 08:26 UTC
Labels: javascript
