### ISSUE TITLE
bug in vs code that  do reduces user express 

### ISSUE THREAD

**Issue by vijayyadav1122** [microsoft/vscode#161636] opened 2022-09-23 19:45 UTC
sir this bug related to javascript 
   when i write a code in java script and i do declare a variable in .js file like var name = "vijay"; 
 then i have fine  'name' is deprecated. ts(6385)lib.dom.d.ts(17693,5): the delaration was marked as deprecated here 

i  attach screen shots

[](https://drive.google.com/drive/folders/1S3pkYmNDXSXrWNycveuNNrxGdE506aKq?usp=sharing)

about images  img 1 jb mouse leke jate h bina control key pressing krte huai
about images  img 2 jb mouse leke jate h  control key pressing krte huai
and in last image when click on with control key then opan new file and this file show a const name

**Comment by mjbvz** [comment] 2022-09-23 19:50
Duplicate of https://github.com/microsoft/TypeScript/issues/39534

**Closed by mjbvz** 2022-09-23 19:50 UTC
