### ISSUE TITLE
VSCode's Jupyter notebook is unable to open HTML file with Python & Pyviz

### ISSUE THREAD

**Issue by Scoodood** [microsoft/vscode#170742] opened 2023-01-07 02:43 UTC
Type: <b>Bug</b>

When I run the following code on the Jupyter notebook outside of VSCode on the Chrome browser, everything works just fine. The interactive Network graph properly functions within the Jupyter cell. When I switch to VSCode's Jupyter notebook and execute the same code, nothing happens. So I suspect it is big in VSCode.

```
import numpy as np
import networkx as nx
from pyvis import network as net

adjacency_matrix = [[0.5, 0.2, 0.3, 0], [0.1, 0.1, 0, 0.8], [0.3, 0, 0.4, 0.3], [0, 0.2, 0.2, 0.6]]
A = np.array(adjacency_matrix)
G = nx.from_numpy_matrix(A, create_using=nx.MultiDiGraph)
G2 = net.Network(notebook=True)
G2.from_nx(G)
G2.show('network_map.html')
```

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.92GB (36.43GB free)|
|Process Argv|--crash-reporter-id 03c1745e-56ff-468a-bdc2-2235eafd7902|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.17.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
partial-diff|ryu|1.4.3
vscode-fileutils|sle|3.5.0
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by rickhg12hs** [comment] 2023-01-31 16:42
Same as #172867?

**Comment by boardkeystown** [comment] 2023-11-10 02:20
yeah I have the same issue...

**Comment by DonJayamanne** [comment] 2023-12-01 01:34
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12689

**Closed by DonJayamanne** 2023-12-01 01:34 UTC
