### ISSUE TITLE
Git - keep english terms in the git extension

### ISSUE THREAD

**Issue by elturpin** [microsoft/vscode#232002] opened 2024-10-07 08:53 UTC
# Description
Regarding all the vocabulary used for the VCS commands, *i.e* "commit", "checkout", "cherry pick", "pull", "fetch" etc… the french localization is IMHO just confusing.

I feel that french speaking devs (tell me if its wrong for others) are used to english words for these different commands. To add to my point, the french localization sometimes includes the english words around parenthesis. 
![image](https://github.com/user-attachments/assets/2dabd4ed-5cf8-4e3c-a97a-4246f099f6cd)

Moreover, personally I think that it is important to understand what is the real command used behind the hood to allow the user to predict exactly what is going to happens when a button is clicked. If using the french word, i must first try to understand what is the command behind the localization, and it is very hard sometimes (ex: "Validation (Modifier)" for commit (amend)", it took me months to figure this one out)

# Proposal
In general, if the term reference a VCS command (like `git COMMAND`, or `git COMMAND --OPTION`), we should keep the english word.

ex:
+ commit => ~validation~
+ checkout => ~vérification~
+ cherry pick => ~faire une sélection~
+ pull => ~tirer~
+ push => ~envoyer~
+ amend => ~modifier~
+ and so on …

**Comment by lszomoru** [comment] 2024-12-22 10:48
Duplicate of [#202916](https://github.com/microsoft/vscode/issues/202916)

**Closed by lszomoru** 2024-12-22 10:48 UTC
Labels: bug, git, under-discussion
