### ISSUE TITLE
Sing in to Sync settings

### ISSUE THREAD

**Issue by Tahmidchy** [microsoft/vscode#233603] opened 2024-11-11 18:07 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

Hi, I am a Junior MERN Developer my favourite code editor is Vs code , actually in here i am create some setting my vs code and i am sing in to sync setting active for future i get my settings when i am switch my device.but recently my sing in to sync not working when i ma click this button no response. how can i solve this problem?

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.08GB free)|
|Process Argv|--crash-reporter-id 2559dc36-4706-4e84-8ec0-c91591f76d22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (158)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-css-formatter|aes|1.0.2
Coderslang|Agi|0.5.7
Coderslang23|Agi|0.6.6
emmet-keybindings|agu|1.2.1
project-manager|ale|12.8.0
stackoverflow-search|Ale|1.2.0
vscode-angular2-files|ale|1.6.4
angulardoc-vscode|Ang|6.1.3
html-end-tag-labels|ant|1.0.0
jsoncrack-vscode|Ayk|2.0.3
vscode-django|bat|1.15.0
vscode-custom-css|be5|7.4.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
emojisense|bie|0.10.0
markdown-preview-github-styles|bie|2.1.0
django|big|1.0.2
blackbox|Bla|1.4.64
vscode-tailwindcss|bra|0.12.13
vscode-toggle-quotes|Bri|0.3.6
vscode-standardjs-snippets|cap|0.9.0
emmet-jss|car|1.0.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
doxdocgen|csc|1.4.0
ng-html|dan|1.1.3
angular2-snippets|dan|1.0.21
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.3
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
mithril-emmet|Fal|0.7.7
file-icons|fil|1.1.0
vscode-firefox-debug|fir|2.9.11
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
shell-format|fox|7.2.5
vscode-angular-html|gha|2.13.0
github-linker|gim|0.2.5
codespaces|Git|1.17.3
vscode-pull-request-github|Git|0.100.1
live-sass|gle|6.1.2
gc-excelviewer|Gra|4.2.62
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
randomeverything|hel|0.0.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-htmlhint|HTM|1.0.5
rest-client|hum|0.25.1
dart-data-class-generator|hzg|0.5.4
vscode-cdnjs|Jak|0.19.0
hungry-delete|jas|1.7.0
polacode-2019|jef|0.6.1
pubspec-assist|jer|2.3.2
svg|joc|1.5.4
angular-file-changer|joh|0.0.4
angular-essentials|joh|18.0.0
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.31.2
angular-extension-pack|loi|1.1.2
MagicPython|mag|1.1.0
flutter-tree|mar|1.0.0
Angular2Tests|Mar|0.7.3
flutter-snippets|Mar|1.0.5
django-commands|Max|0.1.3
rainbow-csv|mec|3.12.0
vscode-django-boilerplate|Men|1.6.0
vscode-language-babel|mgm|0.0.40
code-beautifier|mic|2.3.3
formate|Mik|1.2.1
vscode-azureresourcegroups|ms-|0.9.9
vscode-docker|ms-|1.29.3
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.2
al|ms-|14.1.1180850
vscode-edge-devtools|ms-|2.1.6
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
atom-keybindings|ms-|3.3.0
azure-account|ms-|0.12.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2024.11.417
live-server|ms-|0.4.15
vscode-typescript-next|ms-|5.8.20241110
elmmet|nec|1.0.1
vs-html-to-css|nep|1.0.0
ng-fortytwo-vscode-extension|NG-|0.0.9
vscode-python-typehint|njq|1.5.1
angular-console|nrw|18.30.2
arrr|obe|0.1.3
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
tailwindcss-tune|omk|0.0.6
docthis|oou|0.8.2
explorer-exclude|Pet|1.3.2
material-icon-theme|PKi|5.13.0
postman-for-vscode|Pos|1.4.1
vscode-css-peek|pra|4.4.1
qsharp-lang-vscode|qua|1.10.1
quicktype|qui|23.0.170
karma-problem-matcher|rct|1.0.1
java|red|1.36.0
html-to-jsx|ria|0.0.1
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
angular-cli|seg|0.0.19
django-snippets|Sid|0.0.4
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
simontest|Sim|1.9.10
swdc-vscode|sof|2.8.3
vscode-purescript-emmet|spa|1.0.0
swift-lang|ssw|1.11.3
vscode-standard|sta|2.1.3
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.31
tabnine-vscode|Tab|3.187.0
vscode-djaneiro|the|1.4.2
vscode-pets|ton|1.27.0
cmake|twx|0.0.17
errorlens|use|3.20.0
vscode-lldb|vad|1.11.1
vscodeintellicode|Vis|1.3.2
vscode-icons|vsc|12.9.0
codetour|vsl|0.0.59
volar|Vue|2.1.10
gitblame|wad|11.1.1
console-ninja|Wal|1.0.368
quokka-vscode|Wal|1.0.660
vscode-todo-highlight|way|1.0.5
debug|web|0.27.0
jinja|who|0.0.8
eno|Wsc|2.3.53
snippet-creator|wwa|1.1.3
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
html-css-class-completion|Zig|1.20.0

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31177056

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-11-12 06:39
/duplicate of https://github.com/microsoft/vscode/issues/232516

**Closed** 2024-11-12 06:39 UTC
Labels: *duplicate, new release
