### ISSUE TITLE
Allow to disable hardcoded color profile selection

### ISSUE THREAD

**Issue by lediur** [Microsoft/vscode#51791] opened 2018-06-13 18:29 UTC
- VSCode Version: 1.25.0-insider `fa7ded2f007be6ae288b29392501f3dc34105abd` (with Electron 2.0.2)
- OS Version: Windows 10 Pro 17134

Steps to Reproduce:

0. Use monitors with specific color profiles (I have two external monitors and a laptop screen, all of which use different profiles corresponding to sRGB)
1. Open VSCode. Colors are rendered correctly.

  ![image](https://user-images.githubusercontent.com/1077648/41370576-e1ac166a-6efc-11e8-866d-d2aea00be6fb.png)

2. Disconnect and reconnect monitors.
3. VSCode / Electron refreshes color profiles and starts rendering colors incorrectly (washed out as if rendering sRGB on a display expecting Adobe RGB)

  ![image](https://user-images.githubusercontent.com/1077648/41370620-ff4c531a-6efc-11e8-8e81-de51bd58a731.png)

4. If you restart VSCode Insider (may have to restart all other instances of VSCode, including stable), the colors are correct again until monitor configuration is changed

Does this issue occur when all extensions are disabled?: Yes

May be related to https://github.com/electron/electron/issues/10732 and recent upgrade to Electron 2 (VSCode stable 1.24.0 doesn't exhibit this issue).

**Comment by thomasjo** [comment] 2018-06-14 21:11
See https://github.com/atom/atom/pull/17380.

**Comment by bpasero** [comment] 2018-06-15 06:33
@lediur can you give this a try:

* quit any running VSCode Insiders
* open `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\main.js`
* find the place where it reads `app.commandLine.appendSwitch("disable-mojo-local-storage");`
right after paste this: `app.commandLine.appendSwitch('force-color-profile', 'srgb');`
* save (you will need to save as admin I guess)
* start VSCode Insiders again
=> does the issue still reproduce?

**Comment by lediur** [comment] 2018-06-15 16:45
Thanks for the heads up @bpasero. I saw that workaround earlier in the aforementioned atom and electron issues but wasn't sure how to inject that into an installed version of VSCode.

I tested out the workaround and can confirm the issue no longer occurs.

**Comment by lediur** [comment] 2018-06-15 18:28
Hmm, I just unplugged my laptop and the issue actually appears to **not** have been fixed with that change.

**Comment by bpasero** [comment] 2018-06-16 09:13
@jasonrudolph @daviwil may I ask: any reason you guys decided to not change the default in https://github.com/atom/atom/pull/17380 to be `'force-color-profile': 'srgb'`? Is there a benefit from leaving this as Chrome decides to?

**Comment by jasonrudolph** [comment] 2018-06-18 21:46
> any reason you guys decided to not change the default in atom/atom#17380 to be `'force-color-profile': 'srgb'`? Is there a benefit from leaving this as Chrome decides to that you are aware of?

@bpasero: I have to admit that my experience working with color profiles is essentially nonexistent prior to https://github.com/atom/atom/pull/17380, but I'll try to explain our thinking. :sweat_smile:

Assume a developer has taken the time to calibrate the color profile for their display. As a result, they see that Photoshop (and various other apps) respect that color profile and render colors accordingly. The user has said, "When rendering colors on this display, apply these adjustments to ensure that colors are rendered correctly." If Atom always forces the color profile to sRGB, Atom is ignoring that user's instructions, and the user has no way to get Atom to render colors in accordance with the color profile. 🙁 

With that in mind, we've chosen to respect the color profile by default. For the subset of users that want apps like Photoshop to honor their color profile, but want Atom to ignore the color profile, we provide a configuration option that allows those users to force the color profile to sRGB in Atom. :atom: :art: 🙂 

I hope that context is helpful.

For what it's worth, I found this [doc from the Chrome team](https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40/edit) (shared in https://github.com/electron/electron/issues/10732#issuecomment-390288101) to be a valuable reference in understanding the background for Chrome's updated handling of color profiles.

**Comment by bpasero** [comment] 2018-06-19 05:02
@jasonrudolph thanks, that document is really helpful. It looks like not changing the defaults and having a setting is the right thing to do.

**Comment by bpasero** [comment] 2018-08-11 13:05
@lediur if you have the time could you see if [VSCode Exploration](https://az764295.vo.msecnd.net/exploration/b713d2fcc08c214d0cc5a81433d3c018d4b96384/VSCodeUserSetup-x64-1.27.0-exploration.exe) also looks good to you in terms of colors? It includes a variant of the fix on a newer Electron version that should restore the old behaviour completely.

**Comment by bpasero** [comment] 2018-08-21 06:37
Closing, with the update to 2.0.7 we are back to the Electron 1.7.x behaviour.

**Closed by bpasero** 2018-08-21 06:37 UTC
Labels: feature-request, workbench-electron
