### ISSUE TITLE
Explorer has `expand all` action enabled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155570] opened 2022-07-19 07:46 UTC
In today's Insiders `a74adedba8fb56d14f01f7950340dab33cfeae57`.

1. Expand some folders in the Explorer
2. Reload

🐛 You see this `expand all` icon:

![image](https://user-images.githubusercontent.com/22350/179695661-16b428e0-3620-4f67-8bf0-2aab1afb8c3f.png)

Related: https://github.com/microsoft/vscode/issues/155131

**Comment by gjsjohnmurray** [comment] 2022-07-19 07:55
Confirmed. The initial status of this button isn't being set correctly after reload. It corrects itself after I expand or collapse any folder in the tree.

**Comment by lramos15** [comment] 2022-07-19 13:54
@joaomoreno Just an FYI that expand all is expected since it is a heavily requested feature which we pulled in via community PR (although it works a bit weird at the moment due to the async data tree nature of the explorer but I'm not confident in resolving all nodes).

**Closed** 2022-07-19 16:26 UTC
Labels: bug, file-explorer

**Comment by joaomoreno** [comment] 2022-07-19 20:20
> @joaomoreno Just an FYI that expand all is expected since it is a heavily requested feature which we pulled in via community PR (although it works a bit weird at the moment due to the async data tree nature of the explorer but I'm not confident in resolving all nodes).

I didn't say otherwise. But now that you mention it, how are we planning on solving the _weird_ part? The fact that the explorer model is potentially huge and possibly infinite (think recursive FS links) is the reason we never added such an action here in the past. Not saying there isn't community demand (I'm sure there is) but we should create a coherent story and an _expand all_ icon which doesn't "expand all" is misleading. Maybe we should look into addressing the community's pain points in a more surgical way and find better UX affordances that can fix those?

**Comment by lramos15** [comment] 2022-07-19 20:32
> Maybe we should look into addressing the community's pain points in a more surgical way and find better UX affordances that can fix those?

Definitely agree. I'm happy to discuss with anyone who is interested. My initial brainstorm was try to expand a certain set of levels (i.e 5) which would cover most use cases. The biggest pain point with this feature at the moment is that when you initially open a workspace expand all doesn't do anything as we have not resolved any nodes. I will probably hold off shipping this feature in stable until we have a good user story.
