### ISSUE TITLE
Dragging sections in sidebar only changes cursor on hover which causes incorrect cursor display

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#37769] opened 2017-11-07 10:37 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|2.2.4
code-settings-sync|Sha|2.8.5
sort-lines|Tyr|1.3.0
quokka-vscode|Wal|1.0.75
path-intellisense|chr|1.4.2
githistory|don|0.2.3
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.3
php-intellisense|fel|1.5.4
code-runner|for|0.8.3
docthis|joe|0.6.0
ftp-sync|luk|0.3.3
theme-monokai-pro-vscode|mon|1.1.2
vscode-apache|mrm|1.1.1
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
typescript-javascript-grammar|ms-|0.0.24
vscode-code-outline|pat|0.0.12
stylelint|shi|0.30.0
vscode-coffeelint|slb|0.0.2
language-stylus|sys|1.8.0
es-quotes|vil|0.2.6
vscode-todo-highlight|way|0.5.11
twig|wha|1.0.2
vscode-import-cost|wix|2.5.1

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Have multiple sections on sidebar (e.g. workspace, commits, compare commits). I also have the code outline plugin which creates another section.
2. Place the cursor at the very bottom of the draggable area for that section, then hold down the mouse and drag downwards. If done at the right speed, the cursor and UI should be out of sync, which causes the incorrect cursor to display

Suggested fix:
Cursor should change not only on the hover event, but also when the mouse button is held-down on the dragging area. This would prevent the cursor flickering
[cursorbug.mov.zip](https://github.com/Microsoft/vscode/files/1449596/cursorbug.mov.zip)

I've attached a video showing the issue. The video is in MOV format since that's all QuickTime lets me export as.

**Comment by sandy081** [comment] 2017-12-04 09:09
@joaomoreno Shall we have a new label for view/split view related issues?

**Comment by joaomoreno** [comment] 2017-12-04 10:32
Usually I just put `workbench`.

**Comment by joaomoreno** [comment] 2017-12-04 10:33
@DannyJJK Would you like to fix this in a PR?

**Comment by bpasero** [comment] 2017-12-12 06:59
> Usually I just put workbench.

Please don't.

**Comment by bpasero** [comment] 2017-12-12 10:32
@joaomoreno it is still useful as workbench inbox tracker because the bot is assigning to me when using this label and then I go on and put the right labels.

**Comment by bpasero** [comment] 2018-03-25 12:13
Duplicate of https://github.com/Microsoft/vscode/issues/21675

**Closed by bpasero** 2018-03-25 12:13 UTC
Labels: bug, workbench-layout
