### ISSUE TITLE
Turn on ```editor.formatOnType``` for a particular language

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#15989] opened 2016-11-23 23:11 UTC
For the [Python](https://github.com/DonJayamanne/pythonVSCode) extension I have a custom [OnTypeFormattingEditProvider](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/typeFormatters/blockFormatProvider.ts) that ensures certain blocks of code are properly indented.

For instance if the user were to type the following code in Python:  
```python
if x == y:
    print(x)
    else:
```
After typing in the text ```print(x)``` at line 2, the user hits enter:  
- The cursor at this point will be indented and positioned under the letter ```p```   
- Then types the string ```else:```

In Python the position of ```else:``` is incorrect. It needs to be at the same indentation level as the corresponding ```if```.  This is where the OnTypeFormattingEditProvider comes in, it will automatically format that line (by removing the unnecessary white space).

It works as expected.

However, Python users will have to manually turn on the setting ```editor.formatOnType``` in their user or workspace settings. 

**I.e. almost everyone using this extension will miss out on this (very useful and crucial) feature.**  

- Is there a way for the extension to turn this on as a default value?  
I know I could manually alter the ```enditor.formatOnType``` value via code. Is that the right approach? Would that not affect other languages as well?  
- Or is there a way to turn this on for a specific language, ```Python``` in this case?

**Comment by gandhis1** [comment] 2016-11-23 23:17
Extension-user here. I second everything said here. Writing HTML in VS Code benefits from the default support of Emmet syntax. I think other languages/extension should be able to benefit from their own syntactical shortcuts, *out-of-the-box*.

**Comment by jrieken** [comment] 2016-11-24 08:35
duplicate of #14447

**Comment by DonJayamanne** [comment] 2016-11-24 10:26
@jrieken 
Not sure how this is a duplicate of #14447, besides that has been closed without a solution for this particular issue.

**Comment by jrieken** [comment] 2016-11-24 11:37
Yeah, I meant this #1587 and/or #13547

**Closed by jrieken** 2016-11-24 11:37 UTC
Labels: duplicate
