### ISSUE TITLE
Blurry by Zones

### ISSUE THREAD

**Issue by l33tli3s** [microsoft/vscode#124575] opened 2021-05-25 12:09 UTC
Issue Type: <b>Bug</b>

no steps required... for the last few days i've noticed sections of the desktop VS Code app getting blurry. It's only if the cursor is idling momentarily, but it grows outwards to eventually encompass the enitre window and none of the text can be read. Moving cursor over it or clicking on the window will cause it to come back into focus. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.17GB free)|
|Process Argv|C:\\Program Files\\7-Zip\\readme.txt --crash-reporter-id 07a75885-ceb9-46cd-b8b3-c15e10d26c99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (130)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
lua-debug|act|1.38.0
project-manager|ale|12.1.0
auto-add-brackets|ali|0.11.0
vscode-eclipse-keybindings|alp|0.13.0
asciidoctor-vscode|asc|2.8.9
code-gnu-global|aus|0.2.2
vscode-django|bat|1.6.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-node-readme|ben|3.0.2
LinkCheckMD|bla|0.3.1
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
markdown-julia|col|0.0.1
doxdocgen|csc|1.3.1
dart-code|Dar|3.22.0
vscode-markdownlint|Dav|0.41.0
ini-for-vscode|Dav|0.0.4
jshint|dba|0.11.0
vscode-eslint|dba|2.1.20
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.92
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.7
docs-yaml|doc|0.2.6
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
brackethighlighter|Dur|2.2.4
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.21
el-vsc-product-icon-theme|ElA|0.1.8
prettier-vscode|esb|6.4.0
file-icons|fil|1.0.29
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
shell-format|fox|7.1.0
vscode-pull-request-github|Git|0.26.0
gitlab-workflow|Git|3.20.1
go|gol|0.25.0
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
servermanager|int|2.0.4
vscode-objectscript|int|1.0.11
language-server|int|1.1.6
reg|ion|1.0.3
better-cpp-syntax|jef|1.15.5
vscode-gnupg-tool|JHe|1.3.9
nbpreviewer|jit|1.2.2
vscode-peacock|joh|3.9.1
svn-scm|joh|2.13.5
language-julia|jul|1.1.40
asciidoc-textmate|jur|0.1.2
intellij-idea-keybindings|k--|1.4.4
vsc-python-indent|Kev|1.14.2
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
vscode-checkpoints|mic|1.3.2
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.1.0
vscode-edge-devtools|ms-|1.1.9
mssql|ms-|1.10.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
atom-keybindings|ms-|3.0.9
brackets-keybindings|ms-|0.1.1
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0-insiders2
cpptools-extension-pack|ms-|1.0.0
js-debug-nightly|ms-|2021.5.2417
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2021.2.2
sublime-keybindings|ms-|4.0.9
vs-keybindings|ms-|0.2.1
cordova-tools|msj|2.2.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.4.2
sqltools|mtx|0.23.0
gremlins|nho|0.26.0
deepdark-material|Nim|3.3.0
autodocstring|njp|0.5.4
vetur|oct|0.33.1
platformio-ide|pla|2.3.2
polacode|pnp|0.3.4
quicktype|qui|12.0.46
subtle-brackets|raf|3.0.0
java|red|0.79.2
vscode-commons|red|0.0.6
synthwave-vscode|Rob|0.1.8
bash-debug|rog|0.3.9
py-snippets|RTG|1.0.1
django-intellisense|sha|0.0.2
trailing-spaces|sha|0.3.1
bunker|sld|1.1.6
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.4
vscode-readme-pattern|tho|1.3.0
python|tht|0.2.3
rf-intellisense|Tom|2.8.0
pdf|tom|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.33.1
vscode-maven|vsc|0.30.1
vim|vsc|1.20.3
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment] 2021-05-25 15:25
@l33tli3s can you attach a screen shot.

**Comment by IllusionMH** [comment] 2021-05-25 18:13
Based on description I would guess that it's duplicate of #92379

**Closed** 2021-06-02 11:51 UTC
Labels: needs more info, windows
