### ISSUE TITLE
The main menu and submenu of "custom title bar and menus" should use the same font

### ISSUE THREAD

**Issue by KanDisheng** [Microsoft/vscode#56290] opened 2018-08-14 02:34 UTC
Issue Type: <b>Bug</b>

The main menu and submenu of "custom title bar and menus" should use the same font. They are different now.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment] 2018-08-14 23:35
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/52537. It has been resolved in the latest insiders, though due to some refactoring, the localization of the menubar will need to be updated to show translation. If I am mistaken about this being a duplicate, please re-open and clarify.

**Closed by sbatten** 2018-08-14 23:35 UTC
Labels: new release
