### ISSUE TITLE
.bash_profile not sourced in integrated terminal on mac

### ISSUE THREAD

**Issue by jbw91** [Microsoft/vscode#7672] opened 2016-06-14 18:47 UTC
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Toggle open the integrated terminal from VS Code
2. Notice that it has not sourced from `.bash_profile` as terminal does when opening a new window.

I have to run `source ~/.bash_profile` every time I open the integrated terminal the first time after starting code.

Perhaps I've missed documentation somewhere about how to have it always source the `.bash_profile` file?

**Comment by jensvdh** [comment] 2016-06-14 20:19
I am seeing the same issue. I tried ~/.profile but that does not help either.

**Comment by Tyriar** [comment] 2016-06-14 20:56
Which is a duplicate of https://github.com/Microsoft/vscode/issues/7263 :stuck_out_tongue:

Closing, check that issue for workarounds until you can run bash as a login shell in 1.3.0.

**Closed by Tyriar** 2016-06-14 20:56 UTC

**Comment by Abhi347** [comment] 2016-09-14 23:38
I am still experiencing this issue in 1.5.2 in El Capitan. I had to source bash_profile everytime. I thought it was fixed in 1.3.0

**Comment by Tyriar** [comment] 2016-09-15 02:57
@Abhi347 the fix is to specify the -l argument as shellArgs in your settings.json file

**Comment by itanex** [comment] 2016-10-05 17:54
More specifically, you should add this to your `User Settings` file, unless it works better for your `Workspace Settings` file.

```json
{
    //... reduced for brevity
    "terminal.integrated.shellArgs.osx": [
        "-l"
    ]
}
```

**Comment by carlsmith** [comment] 2017-02-03 00:05
Just out of interest, @nabulsi, why the downvote?

**Comment by nabulsi** [comment] 2017-02-04 03:53
Hi,
@carlsmith 
That didn't fix my issue. This is what resolved my issue:
"terminal.integrated.shell.linux": "/bin/bash"

**Comment by carlsmith** [comment] 2017-02-04 18:34
Ah. Sorry. That makes sense.

**Comment by Sheljohn** [comment] 2017-03-17 12:31
@nabulsi You don't seem to be on OSX. Read the title of this issue.
