### ISSUE TITLE
Issue with Arabic output in the integrated terminal

### ISSUE THREAD

**Issue by abdullahahmeda** [Microsoft/vscode#72581] opened 2019-04-18 21:40 UTC
**Version**: 1.33.1
**OS**: Windows_NT x64 6.1.7601

**Issue**: Integrated terminal doesn't show Arabic words properly like so: https://ibb.co/4dt4FhQ
which should be something like this: https://ibb.co/K93VLK0.

What I noticed (which can help developers): 1. text is going LTR instead of RTL.
2. Alphabets are not overlapped and that's not true. alphabets in Arabic are overlapped.

**Comment by Tyriar** [comment] 2019-05-01 00:59
Duplicate of https://github.com/xtermjs/xterm.js/issues/701

**Closed by Tyriar** 2019-05-01 00:59 UTC
Labels: integrated-terminal
