### ISSUE TITLE
Crash when viewing Changelog of various extensions

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#69550] opened 2019-02-27 17:16 UTC
Issue Type: <b>Bug</b>

1. Go to Extensions tab.
2. Double-click an extension (happened with johnstoncode.svn-scm
 and vscode-ext.sync-rsync).
3. Click Changelog.
4. App spins for a few seconds then crashes.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
swagger-viewer|Arj|2.2.0
vscode-intelephense-client|bme|1.0.3
npm-intellisense|chr|1.3.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vscode-powertools|ego|0.28.1
php-debug|fel|1.12.6
vscode-pull-request-github|Git|0.4.0
svn-scm|joh|1.47.1
vscode-apache|mrm|1.2.0
python|ms-|2019.2.5416
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.2
java|red|0.39.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
sync-rsync|vsc|0.34.5
jinja|who|0.0.8

</details>

**Comment by sandy081** [comment] 2019-03-03 18:32
@jacobweber I cannot reproduce it. Is it possible to provide us the crash reports? Do you see any logs in the console (from developer tools) ?

**Comment by jacobweber** [comment] 2019-03-03 21:52
@sandy081 Sorry, I meant to include these...see [crashes.zip](https://github.com/Microsoft/vscode/files/2923736/crashes.zip). It's not happening right now, but if it happens again I'll check the console.

**Comment by sandy081** [comment] 2019-03-04 08:57
Closing this as it is not happening. Please reopen with necessary info when you see it again.

**Closed by sandy081** 2019-03-04 08:57 UTC
Labels: extensions, needs more info

**Comment by jacobweber** [comment] 2019-03-15 15:20
Happening again. It started after I clicked "Reload Required" on an updated extension. There was nothing special in the Developer Tools console, once I started it again after the crash.
