### ISSUE TITLE
Allow extending snippets or including snippets in snippet. 

### ISSUE THREAD

**Issue by akash-rajput** [microsoft/vscode#73702] opened 2019-05-14 05:00 UTC
This will allow to create commonly used parts to be used in snippets. Which will make the work organized.

**Comment by jrieken** [comment] 2019-05-14 16:01
Can clarity and provide a sample?

**Comment by akash-rajput** [comment] 2019-05-15 08:04
Sure, suppose I've a snippet to create company copyright. `copyr` again suppose I make another snippet `reactComp` for file skeleton & want to include `copyr` in `reactComp` which is not possible now If I'm not wrong.

We can have something  in `reactComp` like `body: [ "$__copyr", "rest stuff" ]` which will include one snippet in another. This will also help to make composing snippets & extending might have future scopre

**Comment by jrieken** [comment] 2019-05-15 16:17
Thanks for clarifying - marking this as dupe of https://github.com/microsoft/vscode/issues/63534 which is about project level variables which will enable this

**Comment by jrieken** [comment] 2019-05-15 16:17
/duplicate of https://github.com/microsoft/vscode/issues/63534

**Closed** 2019-05-15 16:18 UTC
Labels: *duplicate, needs more info, snippets
