### ISSUE TITLE
插件服务器挂掉了 marketplace  web 503 error 

### ISSUE THREAD

**Issue by xuntee** [Microsoft/vscode#57879] opened 2018-09-04 15:04 UTC
作为菜鸟 今天第一次下载使用 装好 一直无法切换中文 各种版本 下都不行 最后在 OUTPUT 窗口的  log(windows) 发现 Server returned 503  后来抓包 发现 https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery  无法访问 
url https://marketplace.visualstudio.com/
害我重装10+次  快快来帮我

**Comment by neilsustc** [comment] 2018-09-04 15:17
等，就可以了吧 😂

**Comment by igorbb** [comment] 2018-09-04 16:03
https://blogs.msdn.microsoft.com/vsoservice/?p=17405

Also this seems to be a duplicate of :

#57851

**Closed** 2018-09-04 17:48 UTC
Labels: *duplicate, extensions

**Comment by rockyr8** [comment] 2018-09-05 03:05
我也重装了一次,而且还重启了电脑.后来我才发现是微软的问题,
https://marketplace.visualstudio.com/

"Sorry! Our services aren't available right now.
We're working to restore all services as quickly as possible. Please check back soon.

Ref A: 733D59CE27294BF3AFA30407CD0F1E45 Ref B: BAYEDGE0510 Ref C: 2018-09-05T02:55:15Z"

**Comment by rockyr8** [comment] 2018-09-05 05:05
已经好了
