### ISSUE TITLE
No scrollbar visible in the Markdown preview when having a vertical editor layout

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19129] opened 2017-01-24 09:42 UTC
Testing  #19082

There is no vertical scrollbar in the Markdown preview

![no-scrollbar](https://cloud.githubusercontent.com/assets/5047891/22241946/c55802b2-e221-11e6-8506-5a513c6361d9.gif)

**Comment by mjbvz** [comment] 2017-01-24 21:31
This looks like a duplicate of #17617

**Closed by mjbvz** 2017-01-24 21:31 UTC
Labels: duplicate
