### ISSUE TITLE
Debug and tasks should fetch latest configuration from disk

### ISSUE THREAD

**Issue by damolina-ms** [Microsoft/vscode#3132] opened 2016-02-18 18:59 UTC
**Repro**
1. Create a "project" that uses command-line arguments. In my case, a node.js command-line tool.
2. Modify the "configuration.args" in associated launch.json 
3. Press F5 to debug 

**Issue**
Modifications to launch.json in step 2 would not be used for step 3 until launch.json is explicitly saved (Ctrl+S). 'launch.json' is a special file and should probably be automatically saved on F5 or at least user should be warned it is on a modified state.

Visual Studio Code
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:10:11.194Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by isidorn** [comment] 2016-02-19 09:24
We are actually saving all files on the debug session start, however there is a timing issue here. If you start a second debug session you will see that your changes are picked up.

The root cause here is that the configuration service is giving me a stale `launch.json` so forwarding to @bpasero 
To repro, change something in `launch.json`, notice that the change is not picked up on first debug launch, however it is picked up afterwards. I think we already looked into this issue some time ago but forgot what was the conclusion.

**Comment by bpasero** [comment] 2016-02-29 13:55
I am sure we have a dupe for this...

**Comment by bpasero** [comment] 2016-03-03 14:00
@isidorn even if the configuration service would react synchronously to the file getting saved, there is still a delay until the configuration service would read the file from disk and emit the configuration change event.

If you can suggest how this would work, let me know. Should we have a method on the configuration service to always fetch the config from disk and bypass the cache?

**Comment by isidorn** [comment] 2016-03-03 14:11
@bpasero having a method that bypasses the cache would work for me in this scenario, not sure if you want to add it though. Tasks might also benefit from this, run task would also need to bypass the cache for similar reasons. But where do we draw a line between using a configuration service and the file service to just read the content of the file?

**Comment by bpasero** [comment] 2016-03-03 14:49
No it would always go through the configuration service and never the file service. I agree that tasks should use it as well then.

**Comment by bpasero** [comment] 2016-04-18 17:55
Updating to reflect the issue exists for tasks as well.

**Comment by balachandar88** [comment] 2016-04-21 06:13
is there a fix for this issue?

**Comment by bpasero** [comment] 2016-04-21 06:29
This issue is currently assigned to the backlog. Every sprint we pick items from the backlog to plan for the current iteration. Please see https://github.com/Microsoft/vscode/wiki/Issue-Tracking#planning

**Comment by bpasero** [comment] 2016-04-21 11:49
@isidorn the change is for debug and tasks to fetch latest config from disk so that you do not get stale results. one use case to verify is to F5 with a dirty launch.json and making sure everything works including the dirty changes that get saved right after.

**Closed** 2016-04-21 11:48 UTC
Labels: bug

**Comment by isidorn** [comment] 2016-04-21 11:56
Awesome!

**Comment by balachandar88** [comment] 2016-04-21 15:23
@bpasero Great!!! you fixed the issue. If I download the latest visual studio code, will it be having the fix incorporated?

**Comment by bpasero** [comment] 2016-04-21 15:39
@balachandar88 end of month, next release!

**Comment by isidorn** [comment] 2016-04-28 15:13
@bpasero works great! Love that this got fixed

**Comment by bpasero** [comment] 2016-04-29 06:33
@isidorn nice!
