### ISSUE TITLE
Emmet Empty lines not removed during Wrap with Abbreviation

### ISSUE THREAD

**Issue by umnovI** [microsoft/vscode#65469] opened 2018-12-20 09:27 UTC
In Sublime Text if wrapping a few strings with one of them empty in tag empty strings are deleting. But in VS Code emmet wrapping this empty string in tag what being kind of annoying.
I didn't find any setting for emmet to prevent this behavior. So I think it would be great if there will be some sort of setting for it or maybe make it as behavior by default.

Sublime:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/30232564/50275394-4d29f180-0450-11e9-94b9-6a07d056e0b3.gif)
VS Code:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30232564/50275544-a4c85d00-0450-11e9-88ea-b11ab0bf98e4.gif)

**Comment by octref** [comment] 2018-12-20 18:09
I think the current behavior makes sense though. Do you have any official emmet documentation saying Sublime's behavior is the intended behavior?

**Comment by umnovI** [comment] 2018-12-20 20:07
Here is an answer about this behavior from @sergeche https://stackoverflow.com/questions/28256217/emmet-wrap-with-abbreviation-empty-lines

**Comment by octref** [comment] 2018-12-20 20:49
Makes sense. Marked as a feature request.

**Comment by umnovI** [comment] 2018-12-21 04:35
Thank you

**Comment by rzhao271** [comment] 2021-01-06 20:02
\closedWith dc5a3da

**Closed** 2021-01-06 20:03 UTC
Labels: bug, emmet, emmet-revamp, unreleased

**Comment by JacksonKearl** [comment] 2021-01-28 02:13
I'm seeing that wrap individual lines with abbreviation wraps the whole selection instead?

![recording (8)](https://user-images.githubusercontent.com/8586769/106080066-3cd2af00-60cb-11eb-97a0-bde597d73bd7.gif)

**Comment by rzhao271** [comment] 2021-01-28 17:54
@JacksonKearl that's the expected behaviour of wrapping with `p` now. Try wrapping with `p*`.
