### ISSUE TITLE
Should "Report Issue" work for built-in extensions in Running Extensions view?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#109781] opened 2020-10-31 10:20 UTC
1. Open Running Extensions 
1. Open context menu
1. Built-in extensions have disabled menu for `Report Issue`

![Screenshot (367)](https://user-images.githubusercontent.com/9638156/97776723-a8b08480-1b7b-11eb-8e69-eac6ece5aa1b.png)

**Comment by alexdima** [comment] 2020-11-06 10:51
@sandy081 I don't remember creating the "Report Issue" action, so I don't think I own it.
@isidorn Maybe you did this?

**Comment by isidorn** [comment] 2020-11-06 14:18
Yeah I did this.
Code pointer https://github.com/microsoft/vscode/blob/9f2ce5386713184ef65d1917e84eb6da8b480395/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L521

The issue here is that the JavaScript Debugger does not seem to provide the repository URI in the package.json
Thus the action gets disabled here https://github.com/microsoft/vscode/blob/9f2ce5386713184ef65d1917e84eb6da8b480395/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L543

@connor4312 can you maybe provide the repository information of the JavaScript debugger so this button gets enabled here?

**Comment by usernamehw** [comment] 2020-11-06 14:34
There are multiple built-in extensions with disabled menu item, like, `vscode.css-language-features`, `vscode.emmet`, ... (Not only js debugger).

**Comment by isidorn** [comment] 2020-11-06 14:39
Yeah none of them have a seperate repository. So you shuold just file in vscode repository
However for js-debug we have a sepearte repository so it makes sense to have that action enable.

**Comment by connor4312** [comment] 2020-11-09 17:02
I have an repository in the js-debug package.json. I think the issue is actually the line above:

https://github.com/microsoft/vscode/blob/9f2ce5386713184ef65d1917e84eb6da8b480395/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L542

I don't think this line is necessary. Deleting it will just have people who open issues on extensions in the vscode repo open them here, which is desirable.

**Comment by isidorn** [comment] 2020-11-09 18:50
Yeah, agree.

**Comment by usernamehw** [comment] 2020-11-10 15:45
**Report Issue** on `js-debug` opens this repository https://github.com/microsoft/vscode/issues . Some other built-in extensions still have disabled menu item.

**Comment by sandy081** [comment] 2020-12-03 13:53
@isidorn This action is available only for few builtin extensions (jsdebug, emmet) and this action reports issues in VS Code repository. IMO it shall be consistent and show this action for all builtin extensions. If repo is not found and extension is builtin we shall enable the action and create issue in VS Code repo. Let me know if you agree, if so shall I reopen this issue?

**Comment by isidorn** [comment] 2020-12-03 13:55
Works for me and let's reopen.
I am opening this for community contributions and adding help wanted

**Comment by chenjigeng** [comment] 2020-12-11 11:08
这里我觉得有两种方式来处理，一种是在每一个内置扩展的 package.json 都增加仓库属性，还有一种是在代码里，对扩展做判断，如果是内置扩展，则统一到 https://github.com/microsoft/vscode 提 issue

**Comment by chenjigeng** [comment] 2020-12-11 11:11
I think there are two ways to do it.
1. repository attributes need to be added to the package.json of each built-in extension
2.  In the runtimeExtensionsEditor.ts, judge the extension type. If it is a built-in extension, set the base url to https://github.com/microsoft/vscode.git.

I think 2 is better

**Comment by isidorn** [comment] 2020-12-11 14:33
Yeah let's go with 2.
Sounds like a good approach to me

**Comment by chenjigeng** [comment] 2020-12-11 14:37
@isidorn I have submitted a PR, please help CR

**Comment by isidorn** [comment] 2020-12-14 17:55
@chenjigeng thanks to your PR this is now fixed.

**Closed** 2020-12-14 17:54 UTC
Labels: bug, extensions, help wanted

**Comment by rzhao271** [comment] 2021-01-26 20:52
Fixed for built-in extensions, though just a note that it's still disabled for the github.codespaces extension.
