### ISSUE TITLE
Can't set up preferences-sync

### ISSUE THREAD

**Issue by binyamin** [microsoft/vscode#98185] opened 2020-05-19 15:57 UTC
Similar to #96374, except this was a fresh installation of VS Code Insiders.
I logged in to GitHub successfully. When I tried to turn on preferences sync, I received a notification which was a pretty version of the following log: (log level set to trace)
```
[2020-05-19 11:48:34.518] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","type":"GET","headers":{"Content-Type":"application/json","X-Client-Name":"code-insiders","X-Client-Version":"1.46.0-insider","X-Machine-Id":"4549c224-318c-47a6-9f6f-09177bac5159","X-Account-Type":"github","X-Machine-Session-Id":"07c13cfd-31fa-4f09-a47c-5eec152b3efd"}}
[2020-05-19 11:48:35.768] [userDataSync] [trace] Request finished {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":401}
```

- VSCode Version: 1.46.0-insider
- OS Version: Xubuntu 20.04

Steps to Reproduce:

1. Open up VS Code for the first time (I had just installed it).
2. Log in to GitHub.
3. Try to sync preferences

Does this issue occur when all extensions are disabled?: Yes
Extensions: none, since this was a fresh installation.

**Comment by b3u** [comment] 2020-05-19 17:32
It seems that the initial token or something was off, because it worked a couple hours later.

**Comment by RMacfarlane** [comment] 2020-05-20 19:11
@sandy081 I think this is a timing issue with what happens in the shared process - I just stepped through this and saw the "It looks like this is your first time syncing" dialog before the breakpoint in the `authenticationTokenService` was hit. So the sync is starting before the token gets set, but the token is getting correctly set

**Comment by sandy081** [comment] 2020-05-25 18:26
@RMacfarlane Thanks for the analysis.

I refactored sync code on the renderer few days ago and here is the code that turns on sync with first time sync dialog:

https://github.com/microsoft/vscode/blob/7e407b547294849e9a22b16e5aea28a56f88524c/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L211-L225

I see `first time sync dialog` waits now until the token is updated. 

I tried to repro this by placing break points in `authenticationTokenService` in shared process and at first time sync dialog in renderer. I see the break points are hit in sequence. Can you please help me in reproducing it, probably the steps that can cause this timing issue?

**Comment by RMacfarlane** [comment] 2020-11-03 23:16
I haven't been able to reproduce this on the latest insider's version, so am going to go ahead and close this.

**Closed by RMacfarlane** 2020-11-03 23:16 UTC
