### ISSUE TITLE
Hope that the built-in terminal support git bash or win10 bash

### ISSUE THREAD

**Issue by sbfkcel** [Microsoft/vscode#15229] opened 2016-11-09 07:03 UTC
- VSCode Version:1.7.1
- OS Version:win10 14931

Steps to Reproduce:
Cmd or powershell does not have a color highlight.
Suggest that the terminal can support git bash for windows or win10 ubuntu bash.

**Comment by Tyriar** [comment] 2016-11-11 05:19
Closing as duplicate of https://github.com/Microsoft/vscode/issues/14613 and https://github.com/Microsoft/vscode/issues/7345

**Closed by Tyriar** 2016-11-11 05:19 UTC
