### ISSUE TITLE
Find does not work with multiple lines

### ISSUE THREAD

**Issue by jtremback** [Microsoft/vscode#3879] opened 2016-03-08 19:54 UTC
With this file 

```
foo
    bar
    foo
    
foo
    bar
    foo

foo
    bar
    foo
    
```

Trying to find one of the blocks does not work, with cmd+F or cmd+D.

**Comment by Tyriar** [comment] 2016-03-08 20:02
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Closed by Tyriar** 2016-03-08 20:02 UTC
