### ISSUE TITLE
Do not reload Extension Tab instead keep it in memory just like with files

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#46085] opened 2018-03-19 07:10 UTC
- VSCode Version: 1.21.1
- OS Version: 10.13.3

Steps to Reproduce:

1. Open any Extension Tab, for example, `ESLint` & scroll down to the bottom (notice we are at the bottom of the page)
2. Then open another file by `CMD+N` or `CTRL+N`
3. Then switch back to `ESLint` example (now the whole page is reloaded again & we are at the top)

Proposed Solution:

Do the same procedure with 2 arbitrary long files & scroll to the bottom. Notice that when you switch between 2 files it keeps the scroll position & doesn't reload it again instead it keeps in memory. But Extensions Tab like `ESLint` reloads whole `ESLint` tab again instead of keeping it in memory.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment] 2018-03-19 12:38
Duplicate of #27498

**Closed** 2018-03-19 12:38 UTC
Labels: *duplicate, webview
