### ISSUE TITLE
Please let me hide the folder section in the explorer sidebar

### ISSUE THREAD

**Issue by bobbilljim** [microsoft/vscode#80435] opened 2019-09-05 22:02 UTC
You can hide every other section but not the folder one. I don't use it so it always just says "NO FOLDER OPENED". I would like to be able to hide it.

**Comment by isidorn** [comment] 2019-09-09 08:17
This is currently not possible by design, since Explorer is the "default" view thus we do not allow to hide it.
However this is a fair feature request, thus I am leaving it open and assigning to the backlog since we do not plan to tackle it now.

fyi @sandy081

**Comment by sandy081** [comment] 2019-09-11 07:29
We intentionally made explorer fixed as lot of users had issues with that in the past.

But, I think user here is talking about the `open folder view` in empty window which can be made hide-able.

**Comment by isidorn** [comment] 2019-09-11 13:30
Now it is possible to hide the Exmpty View. You can try this out in vscode insiders from Thursday and onward. Thanks

**Closed** 2019-09-11 13:30 UTC
Labels: feature-request, file-explorer

**Comment by bobbilljim** [comment] 2019-09-11 22:58
Thanks!
