### ISSUE TITLE
changelog opened when click collapse function/class/etc.

### ISSUE THREAD

**Issue by sqlProvider** [Microsoft/vscode#36470] opened 2017-10-18 08:26 UTC
- VSCode Version: Version 1.18.0-insider
- OS Version: MacOS Siera 10.12.6 (16G29)

Steps to Reproduce:

1. click collapse button [+]
2. open SCM changelog

Reproduces without extensions: Yes

**Comment by bluemner** [comment] 2017-10-18 15:53
![capture_bug_vscode](https://user-images.githubusercontent.com/3493458/31728478-0b97862e-b3f2-11e7-8c0f-eeaa0b96ac93.PNG)

- same on window & Linux x64 versions. 
resolution is 1366 x 768

**Comment by sqlProvider** [comment] 2017-10-19 08:12
is anyone interested?

**Comment by yume-chan** [comment] 2017-10-19 10:15
Duplicate of #36237

**Comment by mjbvz** [comment] 2017-10-19 17:05
Thanks @yume-chan! Yes this looks like a duplicate of #36237

Please try out today's VSCode insiders build which I believe contains the fix for this issue

**Closed by mjbvz** 2017-10-19 17:05 UTC
Labels: duplicate
