### ISSUE TITLE
restructured text syntax hangs on > character

### ISSUE THREAD

**Issue by zzzeek** [microsoft/vscode#151437] opened 2022-06-07 15:51 UTC
Issue Type: <b>Bug</b>

this seems to have occurred in a recent update.   open a new, blank file and use text as below.  The ">" character cannot be entered as the first character on a line, the > key has no effect.   > char can be placed by preceding it with another character first, then deleting the preceding character.

```
Python source code

.. sourcecode::

    >>> stmt = (
    ...     select()
    ... )
    Here is where doctest output goes.  But below this line, you can't type 
    the ">" character as the first character on a line

  
another example (try typing a > character as first char, doesn't work)::

    no > chars here

```

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.17.4-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3332)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.42GB (0.33GB free)|
|Process Argv|. --crash-reporter-id b6db541c-a710-475b-be24-bac12e8c23d5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by alexdima** [comment] 2022-10-23 11:41
Duplicate of https://github.com/microsoft/vscode/issues/149460

**Closed by alexdima** 2022-10-23 11:41 UTC
