### ISSUE TITLE
Losing "Recently Opened" quickopen entries

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89257] opened 2020-01-24 22:42 UTC
I keep noticing that my "recently opened" files are being cleared. This is what it looks like in my primary vscode repo where I was just editing this morning:

![image](https://user-images.githubusercontent.com/323878/73109283-951f1180-3eb7-11ea-9980-5d4728ff74d2.png)

I've noticed this in different workspaces recently but I haven't narrowed it down to a particular event or point in time where the data is lost. Did anything in this area change recently?

**Comment by bpasero** [comment] 2020-01-25 06:31
@roblourens to be clear, this is quick open (Cmd+P) you are talking about, not File > Open Recent > More... right?

Nothing changed there and if the list is gone it could be a storage issue with SQLite but then again, other things would probably also get lost.

Can you scan through your log files to see if something suspicious shows up?

PS: there is a command to clear all recently opened from that list, I am not sure you triggered this accidentally. We will also remove entries when we detect file events for deletions.

**Comment by roblourens** [comment] 2020-01-25 17:58
Yeah this is cmd+p. I haven't run the command to clear editor history. Looking through my commonly used workspaces, 3 of them have Recently Opened sections that are much shorter than they should be. I don't see any suspicious logs. I'll keep an eye on it.

**Comment by roblourens** [comment] 2020-02-01 21:05
It keeps happening. This is my primary debug adapter workspace

![image](https://user-images.githubusercontent.com/323878/73598745-f61a9b00-44f0-11ea-863a-963d0a22d83d.png)

Workspace storage `history.entries` is empty:

![image](https://user-images.githubusercontent.com/323878/73598879-421a0f80-44f2-11ea-9116-7a0f74f3ad2b.png)

I'll leave this open for me to investigate more since I seem to be the only one seeing it.

**Comment by bpasero** [comment] 2020-02-02 07:06
Let me add some logging around the history, I see that on startup I load it from storage but upon error the history will be reset to be empty and there is no logging to our log service. After I add it you could maybe check the logs.

I just confirmed that `history.entries` is stored per workspace and not globally.

**Comment by bpasero** [comment] 2020-02-04 08:36
There is now 2 trace logs for how many entries are persisted and loaded:

![image](https://user-images.githubusercontent.com/900690/73727448-c4dcdd80-4731-11ea-9b4d-4f3305ce8dc6.png)

In addition I am logging any errors that occur when loading a history entry. I just checked and it looks like even if a single editor fails to load, it will not take the entire history down, via:

https://github.com/microsoft/vscode/blob/12cf39dea3c87137d4bc1b96c16c4e0a19bd5122/src/vs/workbench/services/history/browser/history.ts#L890

**Comment by roblourens** [comment] 2020-02-04 17:00
Thanks! Should I run in trace mode all the time until I catch it breaking or do you mostly just want the error?

**Comment by bpasero** [comment] 2020-02-04 17:01
@roblourens yeah ideally we need both things. Is that too much? I can change the log level too.

**Comment by roblourens** [comment] 2020-02-04 17:10
No it's not a problem, I'll start doing that once we start releasing insiders again.

**Comment by roblourens** [comment] 2020-02-21 05:55
Has happened again lately but I haven't caught it in action or seen the relevant logs

**Comment by bpasero** [comment] 2020-02-21 06:30
@roblourens is this with just one insiders usage or is there web selfhost involved?

**Comment by s-zaw-fitatu** [comment] 2020-02-21 09:50
Hi. I also have issues with Quick Open (Ctrl + P). I've noticed that when I close VS Code few times, the entries are being cleared. Hopefully that will give you some clue ;)

**Comment by bpasero** [comment] 2020-02-21 10:09
@s-zaw-fitatu what platform? anything in the logs?

**Comment by s-zaw-fitatu** [comment] 2020-02-21 10:33
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

I don't know where are the logs... Could you tell me where can I find them and what to look for?

**Comment by bpasero** [comment] 2020-02-21 10:45
There is a command in the paltte to "Open logs foldr"

**Comment by s-zaw-fitatu** [comment] 2020-02-21 10:54
Ok. I'll let you know if I find anything.

**Comment by roblourens** [comment] 2020-02-21 18:31
I don't see any errors. One thing I see is the number changing, which I don't know if that's expected if I didn't delete anything from history.

```
20200220T070910/renderer31.log
78:[2020-02-20 14:06:54.105] [renderer31] [trace] [editor history] saving 0 entries
300:[2020-02-20 14:07:09.233] [renderer31] [trace] [editor history] saving 0 entries
506:[2020-02-20 14:07:20.350] [renderer31] [trace] [editor history] saving 0 entries
590:[2020-02-20 14:08:06.242] [renderer31] [trace] [editor history] saving 0 entries
782:[2020-02-20 14:08:21.413] [renderer31] [trace] [editor history] saving 0 entries
791:[2020-02-20 14:08:23.043] [renderer31] [trace] [editor history] saving 0 entries
914:[2020-02-20 14:08:34.611] [renderer31] [trace] [editor history] loading 0 entries
1115:[2020-02-20 14:08:43.139] [renderer31] [trace] [editor history] saving 1 entries
1126:[2020-02-20 14:08:44.547] [renderer31] [trace] [editor history] loading 1 entries
1340:[2020-02-20 14:09:11.099] [renderer31] [trace] [editor history] saving 1 entries
1351:[2020-02-20 14:09:12.144] [renderer31] [trace] [editor history] loading 1 entries
1577:[2020-02-20 14:10:03.071] [renderer31] [trace] [editor history] saving 1 entries
1851:[2020-02-20 14:10:16.910] [renderer31] [trace] [editor history] saving 0 entries
2078:[2020-02-20 14:10:27.845] [renderer31] [trace] [editor history] saving 0 entries
```

Full file 
[renderer31.log](https://github.com/microsoft/vscode/files/4237485/renderer31.log)

I have been running with trace mode most of the time but not 100% of the time

**Comment by s-zaw-fitatu** [comment] 2020-02-22 21:33
It happened again.

I have:
woken my laptop out of hibernation -> opened Vs Code -> immediately closed it -> changed my current git branch (separate PowerShell console) -> opened Code again -> hit CTRL + P and the list turned out to be empty again.

I should set log level to "Trace", right? Is there anything else, that should be set in a particular way? I'm running current, production version of VS Code and no `[editor history]` entries are logged to the console.

**Comment by s-zaw-fitatu** [comment] 2020-02-22 22:00
Ok, so I can confirm on 100%, that the Quick Open list is cleared each time VS Code is closed too fast.

1. I close the editor as soon as the "X" button on the title bar shows up.
2. When Code is opened again, the Quick Open list is empty.

**Comment by bpasero** [comment] 2020-02-23 10:23
@s-zaw-fitatu thanks, a regression from strict-init work we did. If you manage to close VSCode without using the history at all, I saved an empty set of editors.

**Closed** 2020-02-23 10:22 UTC
Labels: bug, workbench-state

**Comment by roblourens** [comment] 2020-02-23 21:30
Wow thanks for being much more observant than I was @s-zaw-fitatu!

**Comment by s-zaw-fitatu** [comment] 2020-02-23 21:42
I'm glad i could help :)
