### ISSUE TITLE
Extension Host Terminated

### ISSUE THREAD

**Issue by Vatsalsoni13** [microsoft/vscode#94869] opened 2020-04-10 06:24 UTC
Issue Type: <b>Bug</b>

Since the latest update 1.44 this problem:Extension Host Terminated has occured i have tried several online solutions , also re-installed it 5-6 times  but it didnt help.
Becasue of this non of the extensions are working

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by Vatsalsoni13** [comment] 2020-04-10 06:27
![Screenshot (24)](https://user-images.githubusercontent.com/53573748/78968488-5d248380-7b22-11ea-92eb-ac26cdbe8b46.png)
This is what is coming in console

**Comment by gjsjohnmurray** [comment] 2020-04-10 06:31
/duplicate of #94807 - do you use antivirus software? Which one? Has it deleted the file that is missing?

**Closed** 2020-04-10 06:32 UTC
Labels: *duplicate, new release

**Comment by Vatsalsoni13** [comment] 2020-04-10 06:35
yup, QuickHeal when vs code got updated it detected some file and repaired it .
![Screenshot (23)](https://user-images.githubusercontent.com/53573748/78969014-927da100-7b23-11ea-84c9-50f18a482f0a.png)

**Comment by gjsjohnmurray** [comment] 2020-04-10 06:40
That is the problem then. It needs to be reported to the AV vendor as a false positive.

**Comment by 9ightcor3** [comment] 2020-04-11 19:00
> yup, QuickHeal when vs code got updated it detected some file and repaired it .
> ![Screenshot (23)](https://user-images.githubusercontent.com/53573748/78969014-927da100-7b23-11ea-84c9-50f18a482f0a.png)

Was having the same damn issue, just viewed in the quarantine of QH, 
Thanks a lot!
Cheers!

**Comment by Malaya2184** [comment] 2020-04-13 08:35
i think you have some antivirus....
if you have quick heal total security then
go to the quick heal
->file folders
->exclude file folder from scanning
->add file i.e C:\Users\ (user file name e.g- hp...etc) \AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js
->save changes...
It is working perfectly....
