### ISSUE TITLE
VSCode Smoke Tests (Electron)        Localization

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134128] opened 2021-09-29 14:08 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=136910&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d

**Comment by dbaeumer** [comment] 2021-09-29 19:52
This failed to a reason unconnected to localization

```
  1) VSCode Smoke Tests (Electron)
       Localization
         starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-599139OgMIshbBWxc
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

Lets see if this shows up again.

**Comment by dbaeumer** [comment] 2021-09-30 07:44
I checked the last builds and they are all green. I close the issue since the failure was not caused by the localization code in the first place.

**Closed by dbaeumer** 2021-09-30 07:44 UTC
Labels: smoke-test-failure
