### ISSUE TITLE
Some lines in terminal output missing

### ISSUE THREAD

**Issue by paradajz** [Microsoft/vscode#72191] opened 2019-04-12 07:42 UTC
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

A strange issue happens in VScode when running some tasks. This is the (very ugly) batch script used for testing purposes:

    @echo off
    SET /A "index = 1"
    SET /A "count = 50"
    SET /A "number_of_pings = 2"
    :while
    if %index% leq %count% (
       echo The value of index is %index%
       SET /A "index = index + 1"
       for /L %%a In (0 1 %number_of_pings%) do (
    ping -n 1 -w 1.1.1.1 > nul
    )
       goto :while
    )

Normally, when run through CMD it produces the following output:

    The value of index is 1
    The value of index is 2
    The value of index is 3
    The value of index is 4
    The value of index is 5
    The value of index is 6
    The value of index is 7
    The value of index is 8
    The value of index is 9
    The value of index is 10
    The value of index is 11
    The value of index is 12
    The value of index is 13
    The value of index is 14
    The value of index is 15
    The value of index is 16
    The value of index is 17
    The value of index is 18
    The value of index is 19
    The value of index is 20
    The value of index is 21
    The value of index is 22
    The value of index is 23
    The value of index is 24
    The value of index is 25
    The value of index is 26
    The value of index is 27
    The value of index is 28
    The value of index is 29
    The value of index is 30
    The value of index is 31
    The value of index is 32
    The value of index is 33
    The value of index is 34
    The value of index is 35
    The value of index is 36
    The value of index is 37
    The value of index is 38
    The value of index is 39
    The value of index is 40
    The value of index is 41
    The value of index is 42
    The value of index is 43
    The value of index is 44
    The value of index is 45
    The value of index is 46
    The value of index is 47
    The value of index is 48
    The value of index is 49
    The value of index is 50

In VScode, I'm running this script through the following task:

    {
        "label": "test cmd", 
        "type": "shell", 
        "problemMatcher": [], 
        "command": "test.bat",
        "options": {
            "shell": {
                "executable": "C:\\Windows\\System32\\cmd.exe",
                "args": ["/C"],
            },
            "cwd": "${workspaceRoot}"
        }
    }, 

And this is the output in VScode terminal:

    > Executing task: test.bat <

    The value of index is 1

    The value of index is 12
    The value of index is 13
    The value of index is 14
    The value of index is 15
    The value of index is 16
    The value of index is 17
    The value of index is 18
    The value of index is 19
    The value of index is 20
    The value of index is 21
    The value of index is 22
    The value of index is 23
    The value of index is 24
    The value of index is 25
    The value of index is 26
    The value of index is 27
    The value of index is 28
    The value of index is 29
    The value of index is 30
    The value of index is 31
    The value of index is 32
    The value of index is 33
    The value of index is 34
    The value of index is 35
    The value of index is 36
    The value of index is 37
    The value of index is 38
    The value of index is 39
    The value of index is 40
    The value of index is 41
    The value of index is 42
    The value of index is 43
    The value of index is 44
    The value of index is 45
    The value of index is 46
    The value of index is 47
    The value of index is 48
    The value of index is 49
    The value of index is 50

    Terminal will be reused by tasks, press any key to close it.

Doesn't make much sense - I would expect if there is a timing issue that the first n lines wouldn't be shown, but in this case first line is printed normally. Running this multiple times results in same output.

**Comment by alexr00** [comment] 2019-04-12 08:21
Duplicate of #57803.

**Closed** 2019-04-12 08:21 UTC
Labels: *duplicate
