### ISSUE TITLE
Does not kill processes spawned by plugins, even after uninstall

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#25710] opened 2017-04-30 23:12 UTC
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OSX

Steps to Reproduce:

1. Flow running? No

        $ ps aux | grep flow
            36458   0.0  0.0  2433828    792 s002  S+    3:58PM   0:00.00 grep flow

2. `ext install vscode-flow-ide`

3. Flow running? Yes. Ok.

        $ ps aux | grep flow
        36745  77.2  5.5 27533024 930788   ??  R     4:01PM   1:10.21 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36896  75.6  2.9 27071692 486060   ??  R     4:03PM   0:23.35 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37162  74.8  1.5 26837004 249920   ??  R     4:03PM   0:14.13 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36660  67.3 26.2 36228108 4401732   ??  R     4:00PM   2:06.29 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36508   0.0  0.2 26673176  27236   ??  Ss    3:58PM   0:02.10 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37230   0.0  0.0  2432804    776 s002  S+    4:03PM   0:00.00 grep flow
        36514   0.0  0.0  2496456   2708   ??  S     3:58PM   0:00.92 ./node_modules/flow-bin/vendor/flow
        36512   0.0  0.0 26594388    224   ??  S     3:58PM   0:00.00 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36511   0.0  0.0 26594388    388   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36510   0.0  0.0 26594388    420   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36509   0.0  0.0 26594388    400   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .

4. Quit VSCode. Flow running? Yes. Not ok.

        $ ps aux | grep flow
        36745  77.2  5.5 27533024 930788   ??  R     4:01PM   1:10.21 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36896  75.6  2.9 27071692 486060   ??  R     4:03PM   0:23.35 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37162  74.8  1.5 26837004 249920   ??  R     4:03PM   0:14.13 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36660  67.3 26.2 36228108 4401732   ??  R     4:00PM   2:06.29 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36508   0.0  0.2 26673176  27236   ??  Ss    3:58PM   0:02.10 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37230   0.0  0.0  2432804    776 s002  S+    4:03PM   0:00.00 grep flow
        36514   0.0  0.0  2496456   2708   ??  S     3:58PM   0:00.92 ./node_modules/flow-bin/vendor/flow
        36512   0.0  0.0 26594388    224   ??  S     3:58PM   0:00.00 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36511   0.0  0.0 26594388    388   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36510   0.0  0.0 26594388    420   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36509   0.0  0.0 26594388    400   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .

5. Uninstall extension
6. Quit VSCode
7. Flow running? Yes. Not ok.

        $ ps aux | grep flow
        36745  77.2  5.5 27533024 930788   ??  R     4:01PM   1:10.21 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36896  75.6  2.9 27071692 486060   ??  R     4:03PM   0:23.35 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37162  74.8  1.5 26837004 249920   ??  R     4:03PM   0:14.13 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36660  67.3 26.2 36228108 4401732   ??  R     4:00PM   2:06.29 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36508   0.0  0.2 26673176  27236   ??  Ss    3:58PM   0:02.10 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        37230   0.0  0.0  2432804    776 s002  S+    4:03PM   0:00.00 grep flow
        36514   0.0  0.0  2496456   2708   ??  S     3:58PM   0:00.92 ./node_modules/flow-bin/vendor/flow
        36512   0.0  0.0 26594388    224   ??  S     3:58PM   0:00.00 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36511   0.0  0.0 26594388    388   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36510   0.0  0.0 26594388    420   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .
        36509   0.0  0.0 26594388    400   ??  S     3:58PM   0:00.02 ./node_modules/flow-bin/vendor/flow start --temp-dir /private/tmp/flow .

8. `pkill -9 -f 'flow'` peace at last

I'm not sure if this a problem with the specific extension, but VSCode should not allow processes spawned by extensions to stay running after the editor has quit. I almost completely locked up my computer trying out several Flowtype extensions, not realizing they were all spawning background tasks that didn't die.

I also now have no idea what other background processes VSCode has left open from extensions.

**Comment by kieferrm** [comment] 2017-05-01 23:26
Currently, the extensions are responsible for managing their own processes.  So, the flow extension needs to take care of taking down the processes it brought up. 

I agree that it would be safer if VS Code core would provide a mechanism that extensions could use and which would take care of managing processes. Extensions would have to opt-in. However, such a mechanism is not in place.

**Comment by kieferrm** [comment] 2017-05-01 23:26
@egamma FYI

**Comment by mjbvz** [comment] 2017-11-03 22:50
Duplicate of #26445 I believe

**Closed by mjbvz** 2017-11-03 22:51 UTC
Labels: duplicate, feature-request
