### ISSUE TITLE
Feature Request: Propose undefined method names as autocomplete suggestions

### ISSUE THREAD

**Issue by MartinHaeusler** [Microsoft/vscode#30881] opened 2017-07-17 20:04 UTC
Especially during UI coding, I repeatedly find myself in the following situation:

    ....
    <button onClick={this.handleClick} />

and `this.handleClick` is undefined. Next, I place the cursor in the class, and type...

    private handleClick(e: MouseEvent) {
    }

It would be super useful if `handleClick` would be offered as auto-complete suggestion by VSCode in this situation. In general, any undefined symbol name could be offered as a completion option when typing a new method. There's a pretty good chance in general that the name of a method-under-construction already appears as an undefined symbol somewhere else in the class. I don't know how technically challenging this feature would be, but it sure would come in handy.

**Comment by mjbvz** [comment] 2017-07-20 21:23
I believe we already included this functionality under the name "word based suggestions". The caveat is that word based suggestions are only shown in contexts where no other suggestions are available. This is documented in #21611 which also tracks a feature request to show word suggestions in more contexts

Closing as a duplicate of #21611

**Closed by mjbvz** 2017-07-20 21:23 UTC
Labels: duplicate, feature-request
