### ISSUE TITLE
Dock icon appears twice when starting code from Terminal

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode#163287] opened 2022-10-11 12:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: macOS 11.7

Steps to Reproduce:

1. Pin VS Code in the dock
2. Start `code` in Terminal.app – this will activate the pinned dock icon
3. Start another `code` in Terminal.app – this will briefly show a second dock icon, which disappears after a few seconds

I think the second dock icon should not appear even when opening another VS Code window from the command line.

https://user-images.githubusercontent.com/4377312/195093398-1e517be6-bbc6-4596-9d7e-c2e07e8e330c.mov

**Comment by rzhao271** [comment] 2022-10-17 17:30
Duplicate of https://github.com/microsoft/vscode/issues/139634

**Closed by rzhao271** 2022-10-17 17:30 UTC
