### ISSUE TITLE
Git Graph extension broken by Webview in 1.47

### ISSUE THREAD

**Issue by MaurGi** [microsoft/vscode#106667] opened 2020-09-14 15:59 UTC
- VSCode Version:
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version:
OS: Windows_NT x64 10.0.19041
WSL 2

Steps to Reproduce:

1. Install GitGraph extension on WSL2 Ubuntu
2. Launch the extension:
![image](https://user-images.githubusercontent.com/13138584/93109139-86fd4b80-f668-11ea-9a3c-d207b502a262.png)

See details here: 
https://github.com/mhutchie/vscode-git-graph/issues/378

Does this issue occur when all extensions are disabled?: No this is an issue with a specific extension

This does not repro with 1.46.1:
![image](https://user-images.githubusercontent.com/13138584/93111853-12c4a700-f66c-11ea-8625-12f12219378c.png)

**Comment by MaurGi** [comment] 2020-09-14 16:00
@mhutchie filed the bug here -

**Comment by mjbvz** [comment] 2020-09-14 17:57
What about in VS Code 1.49?

**Comment by mhutchie** [comment] 2020-09-17 21:21
Hi @mjbvz,

I haven't heard anything back from @MaurGi, however another user (@jpoles1) is getting this same WSL2 Webview Bug in Visual Studio Code 1.49.0 (reported in https://github.com/mhutchie/vscode-git-graph/issues/382).

**Comment by mjbvz** [comment] 2020-09-18 18:18
Ok, sounds like this is a duplicate of #105536 then

**Closed by mjbvz** 2020-09-18 18:18 UTC
Labels: needs more info
