### ISSUE TITLE
右键弹出菜单位置错误

### ISSUE THREAD

**Issue by liqianglai** [Microsoft/vscode#3042] opened 2016-02-16 06:03 UTC
### 右键弹出菜单位置错误

* 在放大的情况下（ctrl + +)，右键点击弹出的菜单，位置偏左，放大倍数越大，偏左越明显。

**Comment by egamma** [comment] 2016-02-16 07:39
Hello thanks for the issue, but please report issues in English.

**Comment by TheLevenCreations** [comment] 2016-02-16 14:33
+1

I met this issue too. If you use Ctrl++ to zoom in and use mouse to right click. The right menu will pop up with a floating position.


See the captured screenshots: https://github.com/TheLevenCreations/electron_typescript_template/blob/master/capture-1.gif

**Comment by liqianglai** [comment] 2016-02-17 09:08
@egamma My English is very weak, this issue as described in "TheLevenCreations"

**Comment by bpasero** [comment] 2016-02-29 14:01
@joaomoreno I believe this is an Electron issue?

**Comment by joaomoreno** [comment] 2016-02-29 15:01
Can everyone suddenly speak Chinese?

Closing as duplicate of #821.

**Closed by joaomoreno** 2016-02-29 15:01 UTC
Labels: workbench
