### ISSUE TITLE
TypeScript code editor detects unreachable code after switch statement, but it's not unreachable

### ISSUE THREAD

**Issue by emilmuller** [microsoft/vscode#95630] opened 2020-04-19 10:27 UTC
- VSCode Version: 1.44.2
- OS Version: Ubuntu 19

Steps to Reproduce:

```
enum MyEnum {
    A
}

function test(foo?: MyEnum) {
    switch (foo) {
        case MyEnum.A:
            throw new Error();
        // Have exhausted all possible enum values at this point
    }
    console.log("hello"); // <-- Complains that code is unreachable even though foo is optional and may be undefined, in which case the switch will not hit
}

test(); // Logs hello
```

Kind regards, Emil

**Comment by spahnke** [comment] 2020-04-19 12:08
Which TypeScript version are you using? I cannot reproduce with 3.8.3 or 3.9-nightly. The statement is only then marked as unreachable if I make the parameter required.

**Comment by blaise80** [comment] 2020-04-19 15:56
I dont know ...... I learn  the program c++

**Comment by emilmuller** [comment] 2020-04-20 05:14
Using 3.8.3, as can be observed at the bottom right:

![image](https://user-images.githubusercontent.com/2487546/79716288-91dccb80-82d6-11ea-9e8c-2ebc3d100ad8.png)

**Comment by mjbvz** [comment] 2020-04-20 05:20
Is strict null checking enabled?

**Comment by emilmuller** [comment] 2020-04-20 05:24
@mjbvz doesnt seem like it:

```
{
    "compilerOptions": {
        "target": "es2020",
        "module": "esnext",
        "jsx": "preserve",
        "strict": false,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "resolveJsonModule": true
    }
}
```

**Comment by mjbvz** [comment] 2020-04-20 18:26
That's the cause. If strict null checks are disabled, TS does will not consider that `foo` can be `undefined`.

**Closed by mjbvz** 2020-04-20 18:26 UTC
Labels: new release

**Comment by emilmuller** [comment] 2020-04-21 08:54
@mjbvz You may be correct, but this confuses me somewhat. I thought that if strict null checking was _enabled_, then null and undefined would **not** be a part of MyEnum's domain. And in the opposite case (this case), that null and undefined **would** be a part of MyEnum's domain.

Additionally, foo is marked as optional, so I have a hard time understanding that undefined should not be part of its domain, regardless of strict null checking being enabled or disabled.

**Comment by emilmuller** [comment] 2020-04-25 20:25
I guess we'll just mark it as-designed and hope it goes away then...

**Comment by mjbvz** [comment] 2020-04-25 20:59
Don't open duplicate issues to try to get a different answer

This is as-designed. `?` has effectively no meaning non strict null checked code. Save yourself a lot of trouble and enable strict null checking
