### ISSUE TITLE
JSDoc comments are ignored for destructured parameters despite support for obj.prop params

### ISSUE THREAD

**Issue by llamaluvr** [Microsoft/vscode#41296] opened 2018-01-08 16:30 UTC
Originally, https://github.com/Microsoft/vscode/issues/22980 was opened for VS Code ignoring JSDoc-specified types for destructured parameters. It was noted that handling for `obj.prop` style parameters was being handled on the TypeScript side in https://github.com/Microsoft/TypeScript/issues/11597 and the issue was closed. `obj.prop` style parameters do indeed work now, but only if you pass a single parameter for the object, and not if you use destructured parameters as used in the original VS Code issue. Destructured parameters are a common convention for exposing props in functional React components.

Example (where it doesn't work):

Here, a destructured parameter is used for a React functional component (which is really just a function). If I reference `user` inside of the Profile function, there will not be intellisense exposing the properties of the `User` type.

```js
class User {
  firstName;
  lastName;
  email;
}

/**
 * @param {Object} props
 * @param {User} props.user
 */
const Profile = ({ user }) => {
  // no intellisense for a reference to the user prop here
};
```

Example (where it works):

Here, a regular parameter is used for the React functional component. If I reference `props.user` inside of the Profile function, there will be intellisense exposing the properties of the `User` type.

```js
class User {
  firstName;
  lastName;
  email;
}

/**
 * @param {Object} props
 * @param {User} props.user
 */
const Profile = (props) => {
  // intellisense works for a reference to the props.user param here
};
```

- VSCode Version: 1.19.1
- OS Version: MacOS High Sierra 10.13.2

Steps to Reproduce:

1. Create a class
2. Create a function with a single destructured object as a parameter, where the object has a single property.
3. Add JSDoc comments to the function as shown above, where the parameter is an object, and the single property of the object parameter is the type of the class you created in step 1.
4. Try to use the property inside the function - you will not see intellisense.

Does this issue occur when all extensions are disabled?: Yes

**Comment by villasv** [comment] 2018-01-10 19:43
Confirmed with same version on Windows 10.

**Comment by cristovao-trevisan** [comment] 2018-01-12 16:52
I've had this problem for a while now. Should be tagged as a TypeScript problem, i think

**Comment by mjbvz** [comment] 2018-01-19 06:33
Duplicate of https://github.com/Microsoft/TypeScript/issues/16219 / https://github.com/Microsoft/TypeScript/issues/11859

**Closed by mjbvz** 2018-01-19 06:33 UTC
Labels: javascript, upstream
