### ISSUE TITLE
Santa hat

### ISSUE THREAD

**Issue by pancirno** [microsoft/vscode#87293] opened 2019-12-18 23:01 UTC
I think it would be nice if a small festive symbol would be added to the editor overlaying an icon for the time of December. It would be a nice gesture to people celebrating Christmas. We could also add more holidays in similar fashion such as Ramadan, Hanukkah, Black History Month and LGBT Pride Month.

**Comment by DominusVilicus** [comment] 2019-12-19 00:02
Maybe it's best if we don't make vscode political

**Comment by bmewburn** [comment] 2019-12-19 00:26
As long as it's not [orange](https://github.com/microsoft/vscode/issues/35783). That's where I draw the line.

**Comment by Yen** [comment] 2019-12-19 01:22
> Maybe it's best if we don't make vscode political

Is christmas political? We got a different coloured icon for halloween right? Something like a santa hat has very little to do with any religion and has been used all over the world to celebrate the event event in a non-christian way in non-christian countries by non-christian people, but I might be wrong. 😄

**Comment by Techman** [comment] 2019-12-19 01:37
Specifically regarding #87268:

Please reinstate the Santa hat. I am almost certain that it was a holiday gesture to have it included in the first place, and is not an attempt to inject religiously-charged themes into the editor. I appreciate the slight touch of the developers by adding a very small festive decoration to the editor.

**Comment by egamma** [comment] 2019-12-19 08:01
Duplicate of #87291

**Closed by egamma** 2019-12-19 08:01 UTC

**Comment by egamma** [comment] 2019-12-19 19:16
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
