### ISSUE TITLE
All of the vs code icons are missing!

### ISSUE THREAD

**Issue by yasanthachamara** [microsoft/vscode#103082] opened 2020-07-22 09:29 UTC
Issue Type: <b>Bug</b>

I have tried with a couple of fresh installs with removing AppData settings as well. But VS Code icons are replaced with some weird symbols like the font is missing or so.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/33784749/88160080-cf315c00-cc2b-11ea-96bb-5ed3d04c475b.png)

![image](https://user-images.githubusercontent.com/33784749/88160142-e2442c00-cc2b-11ea-83fa-b72e7806ed43.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.94GB (7.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.94776
remote-wsl|ms-|0.44.4
vscode-icons|vsc|10.2.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment] 2020-07-23 08:22
If you run `Developer: Toggle Developer Tools`, is there any errors in the console?

**Comment by deepak1556** [comment] 2020-07-23 08:59
Possible duplicate of https://github.com/microsoft/vscode/issues/97564

can you follow the steps mentioned here https://github.com/microsoft/vscode/issues/97564#issuecomment-627292788 to see if svg has correct mime type in your system.

**Comment by yasanthachamara** [comment] 2020-07-25 08:06
Content type was already 'image/svg+xml'

![image](https://user-images.githubusercontent.com/33784749/88452361-b1f2cc80-ce7b-11ea-9a88-eb091e81fa87.png)

**Comment by yasanthachamara** [comment] 2020-07-25 08:08
> 
> 
> If you run `Developer: Toggle Developer Tools`, is there any errors in the console?
> 
> cc @mjbvz @deepak1556

I don't see any errors.

![image](https://user-images.githubusercontent.com/33784749/88452422-2ded1480-ce7c-11ea-920d-58d3cd0ef013.png)

**Comment by deepak1556** [comment] 2020-08-06 02:02
Sorry the delayed response, thanks for the registry output which looks correct. Can you provide the log following

* Toggle developer tools > Network tab
* Click `Disable cache` option
* Reload window
* Export HAR file

**Comment by yasanthachamara** [comment] 2020-08-07 16:25
No worries @deepak1556 . Please find the HAR file attached.
[file.zip](https://github.com/microsoft/vscode/files/5042562/file.zip)

**Comment by deepak1556** [comment] 2020-08-08 04:03
Unfortunately the HAR only contains extension search, did you record with a full reload ? It should be something like the following


<img width="1026" alt="Screen Shot 2020-08-07 at 9 02 24 PM" src="https://user-images.githubusercontent.com/964386/89701994-57348880-d8f1-11ea-8bfe-0bd981b7c539.png">

**Comment by yasanthachamara** [comment] 2020-08-08 04:49
I have tried again and everything looks like the screenshot you mentioned. Please find the attachment.
[file.zip](https://github.com/microsoft/vscode/files/5044659/file.zip)

**Comment by deepak1556** [comment] 2020-08-08 06:33
okay the issue is with devtools exporting har, apparently its not exporting all the data, sorry about that. Do you see a request for `codicon.ttf` ? can you attach screenshot of that request if you see it.

<img width="696" alt="Screen Shot 2020-08-07 at 11 32 52 PM" src="https://user-images.githubusercontent.com/964386/89704136-56f2b800-d906-11ea-9da2-d1bf5c0fdcd6.png">

**Comment by yasanthachamara** [comment] 2020-08-08 08:21
Please find the request screenshot attached.

![Annotation 2020-08-08 135103](https://user-images.githubusercontent.com/33784749/89705855-4bdb6e80-d97e-11ea-99f1-24fa51ef79e4.jpg)

**Comment by yasanthachamara** [comment] 2020-08-29 04:30
Hi. Any update on this?

**Comment by joaomoreno** [comment] 2020-11-18 09:38
@deepak1556 Any more insights?

**Comment by deepak1556** [comment] 2020-11-18 10:40
Registry key mime-types are fine and network data is also fine. I don't see any issue with the runtime at this point.

@joaomoreno next step you can try is providing a minimal html that renders some icons using the codicon.ttf and see if there is any rendering issue on the user system.

**Comment by joaomoreno** [comment] 2020-11-19 15:30
@alexdima @bpasero Have you seen this before?

**Comment by alexdima** [comment] 2020-11-20 23:04
Sorry, never saw this.

**Closed** 2020-11-28 11:25 UTC
Labels: needs more info, windows
