### ISSUE TITLE
terminal find is different with editor find [line break]

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#213766] opened 2024-05-29 03:58 UTC
both stable and insiders

版本: 1.90.0-insider
提交: 05634b5fcdc02792b7f4546d1e56d4b87b5b9296
日期: 2024-05-28T20:42:06.977Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.90.0-insider Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

![image](https://github.com/microsoft/vscode/assets/1876302/d6abd90b-42ed-4f25-96b8-96fbd2d845f6)

**Comment by meganrogge** [comment] 2024-05-30 17:08
it's not clear what the issue is here, could you pls state steps to reproduce the issue?

**Comment by heartacker** [comment] 2024-06-04 03:08
@meganrogge can you see, In the second figure, the count items are line wrapped

**Comment by meganrogge** [comment] 2024-06-04 04:20
Yes thanks for pointing that out. We have less space in the terminal, so I think this is fine. Closing as designed.

**Closed** 2024-06-04 04:21 UTC
Labels: info-needed, *as-designed
