### ISSUE TITLE
Intellisense not working for Javascript (various versions)

### ISSUE THREAD

**Issue by roymtaylor** [microsoft/vscode#90161] opened 2020-02-06 18:49 UTC
I understand there are other folks with a similar issue, but I haven't been able to resolve this trying various things in others threads.

Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Install any version of VS Code 1.41 back to 1.35.1
2. When I go all the way back to 1.25.1, it works perfectly, with exactly the same setup and files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by fornit1917** [comment] 2020-02-06 19:20
I have similar problem. After instal npm packages, any autocomplete in js files does not work. At the same time, VS Code process actively uses CPU (like in endless loop).

If I remove node_modules folder, autocomplete works fine after VS code restart.
If I run "npm install", probleam appears again.

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Content of my package.json:

```
{
    "name": "vs-code-issue",
    "version": "1.0.0",
    "description": "Autocomplete in js files does not work after npm install",
    "main": "index.js",
    "scripts": {
        "dev-server": "webpack-dev-server --progress --colors --mode development",
        "build": "webpack --progress --colors --mode production",
        "build-dev": "webpack --progress --colors --mode development"
    },
    "author": "fornit1917",
    "license": "GPL-3.0",
    "devDependencies": {
        "@babel/core": "7.8.4",
        "@babel/plugin-proposal-class-properties": "7.8.3",
        "babel-loader": "8.0.6",
        "css-loader": "3.4.2",
        "cssnano": "4.1.10",
        "file-loader": "5.0.2",
        "html-webpack-plugin": "3.2.0",
        "mini-css-extract-plugin": "0.9.0",
        "node-sass": "4.13.1",
        "optimize-css-assets-webpack-plugin": "5.0.3",
        "sass-loader": "8.0.2",
        "webpack": "4.41.5",
        "webpack-cli": "3.3.10",
        "webpack-dev-server": "3.10.2"
    },
    "dependencies": {
        "vue": "2.6.11"
    }
}

```

**Comment by mjbvz** [comment] 2020-02-06 19:53
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by roymtaylor** [comment] 2020-02-06 20:05
No, the latest build of the Insiders version installed and works correctly.   Suggestions pop up immediately.   Previously I'd only get "text" suggestions with a "Ctrl-space".

**Comment by roymtaylor** [comment] 2020-02-06 20:06
--
Version: 1.42.0-insider (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-05T20:04:22.920Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134
--

Now it works fine.

**Comment by roymtaylor** [comment] 2020-02-06 20:08
Something else weird...on my old installs, I didn't have any "Typescript:" commands in the command palette.  Now they are all there.

**Comment by mjbvz** [comment] 2020-02-06 21:01
Sounds like you may have disable the built-in JS/TS extension

Closing since it works in insiders

**Closed** 2020-02-06 21:00 UTC
