### ISSUE TITLE
Feature Idea/Request: Don't line wrap tables to preserve table formatting.

### ISSUE THREAD

**Issue by blaylockbk** [microsoft/vscode#184086] opened 2023-06-01 16:25 UTC
Thanks @mjbvz for all you have done with supporting markdown in VS code. I use these features every day.

Here is an idea for a feature; (I have no idea if it's even possible.)

I have the "word wrap" setting turned on which works quite well for markdown text...
![image](https://github.com/microsoft/vscode-markdown-languageservice/assets/6249613/5fb7f466-3b48-4a50-80ab-8cceadbbbd70)

Except, making the window narrower ruins my beautifully formatted tables; this is hard to read and edit...
![image](https://github.com/microsoft/vscode-markdown-languageservice/assets/6249613/655c5880-2e85-420e-8fdc-092f8eaf9d85)

Could it be possible to line wrap everything _except_ the lines that represent a table? That way an editor of this file could read and edit the regular contents easily, but at a table they could scroll to see the whole table? 

![image](https://github.com/microsoft/vscode-markdown-languageservice/assets/6249613/8e06cd59-326d-4e92-b2ef-bc4a7ee545c3)

Thanks for the consideration.

**Comment by mjbvz** [comment] 2023-06-19 21:50
Duplicate of #171457

**Closed by mjbvz** 2023-06-19 21:50 UTC
