### ISSUE TITLE
Jupyter notebooks should obey `files.trimTrailingWhitespace` rule 

### ISSUE THREAD

**Issue by Philippe-cheype** [microsoft/vscode#190018] opened 2023-08-09 08:01 UTC
Hello!

This issue has in fact already been discussed over a year ago: #151982, but didn't get enough traction, so I'm trying again.

I understand how this feature would have been missed, but the fact that I'm able to open the command palette and execute manually `Trim Trailing Whitespace` indicated this is a sort of bug.

So the idea is that when we have trailing whitespace characters in a Jupyter Notebook, and in our VScode settings we have any of the following rules:
```
{
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "files.insertFinalNewline": true,
}
```
These rules should apply to the Notebook, but this doesn't work.

**Comment by rebornix** [comment] 2023-08-23 00:56
This is a duplicate of https://github.com/microsoft/vscode/issues/181905 and we have it on our iteration plan now.

**Closed by rebornix** 2023-08-23 00:56 UTC
