### ISSUE TITLE
script and style tags loses or incorrect auto-indent on .html file

### ISSUE THREAD

**Issue by soe-wai** [microsoft/vscode#87166] opened 2019-12-17 10:22 UTC
Issue Type: <b>Performance Issue</b>

when I typed script or style tags on indext.html or other html file extensions then hit tab or enter did'nt turn into auto-indentation next line with its right spaces or tabs, so how do I fix and where do I find to fix the problem above, thank you.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (1.48GB free)|
|Process Argv|D:\OneDrive\Desktop\fbp\JavaScript\d17|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    67	  5308	code main
    0	    58	  1320	   shared-process
    0	   149	  8752	   window (vscode-issues.html - d17 - Visual Studio Code)
    0	    97	   920	     extensionHost
    0	   110	  7460	       "C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=920
    0	    22	 11344	       electron_node server.js 
    0	    12	  3404	     watcherService 
    0	     5	  8096	       console-window-host (Windows internal process)
    0	    64	  9040	   window (Issue Reporter)
    1	   110	 10760	   gpu-process
    0	     9	 11832	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (vscode-issues.html - d17 - Visual Studio Code)
|    Folder (d17): 5 files
|      File types: html(5)
|      Conf files:;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
html-tag-wrapper|hwe|0.2.3
vscode-view-in-browser|kop|1.0.5
vscode-css-peek|pra|3.0.2
java|red|0.54.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.0
vscode-icons|vsc|9.6.0

</details>

**Comment by soe-wai** [comment] 2019-12-17 10:41
A Screen-cast For Issue As Follow.

[Vs Code Issue Report 2019-12-17 16-31-27.zip](https://github.com/microsoft/vscode/files/3972781/Vs.Code.Issue.Report.2019-12-17.16-31-27.zip)

**Comment by aeschli** [comment] 2019-12-18 10:09
caused by #86998. Marking as dup

**Closed by aeschli** 2019-12-18 10:09 UTC
