### ISSUE TITLE
Cannot use Ctrl + C / Ctrl + V anymore

### ISSUE THREAD

**Issue by Julisep** [Microsoft/vscode#17451] opened 2016-12-17 08:26 UTC
- VSCode Version: 1.8
- OS Version: Windows 10
Steps to Reproduce:

1.  Write something in the textfield.
2.  Open a terminal

When you now try to copy something from the textfield a warning will pop up, informing you that the terminal is not in focus.

**Comment by kieferrm** [comment] 2016-12-17 14:30
Duplicate of #17232.

**Closed by kieferrm** 2016-12-17 14:30 UTC
