### ISSUE TITLE
Debug: toggling inline breakpoints sometimes flashes the line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119486] opened 2021-03-22 16:45 UTC
Unfortunately I cannot really record this in a gif, but I see the line flashing briefly sometimes when toggling inline breakpoints.

**Comment by isidorn** [comment] 2021-03-22 18:04
Yes, the issue with this is that we are not doing delta's on a breakpoint line, but we get rid of them all and set them again.
I believe this is not an easy fix, thus for now assigning to next milestone and I might tackle it in debt week - though I am moving then so we'll see.

**Comment by isidorn** [comment] 2021-08-17 16:50
Duplicate of issue Joh filled. I can find it if you care.

**Closed** 2021-08-17 16:50 UTC
Labels: debug, debt, *duplicate
