### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by vibus** [Microsoft/vscode#51682] opened 2018-06-12 09:42 UTC
Command + click on a function is showing a pop up like the one we get during the merge conflicts....in merge conflicts its ok..but while taking to the function definition its annoying!...pls do the needful

**Comment by vibus** [comment] 2018-06-12 09:44
Here's the screenshot!

<img width="979" alt="screen shot 2018-06-12 at 3 13 38 pm" src="https://user-images.githubusercontent.com/40199973/41283064-3c400e9c-6e53-11e8-827c-ff0d87ae9a6a.png">

**Comment by jeanroldao** [comment] 2018-06-12 10:20
Hi, 
This is also happening to me, it is quite annoying, it basically happens when the functions are variables with arrow functions, it show 2 definitions instead of just one, one is for the variable declaration and the other is for the arrow function itself. 
I installed the old update from April and this doesn't happen, only happens in the latest update from May. 
I will keep using this old update for now.
Thanks.

**Comment by mjbvz** [comment] 2018-06-12 16:53
Duplicate of #51489

**Closed by mjbvz** 2018-06-12 16:53 UTC
