### ISSUE TITLE
Submenus on inline tree actions don't work

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#110083] opened 2020-11-06 13:21 UTC
With the submenu contribution point, this should work. However, there appears to be an issue with how the submenu is shown.

![recording (27)](https://user-images.githubusercontent.com/38270282/98370766-5d92e780-203b-11eb-92c4-635fe6fb17c9.gif)

I'm also happy to fix if this is something that should be solved at the custom tree level.

**Comment by sbatten** [comment] 2020-11-10 23:55
@alexr00 @joaomoreno 
The issue is that custom menu is using the shadow dom version to maintain focus, however the list widget is using transform3d which prevents anything from overflowing. custom tree views could opt out of using the shadow dom for now but since tree view items rely on focus/hover, the submenu button will disappear on click.

**Comment by sbatten** [comment] 2020-11-10 23:57
A basic extension for testing. Adds a test view to the explorer
[test-tree-view-item-submenus-0.0.1.zip](https://github.com/microsoft/vscode/files/5520848/test-tree-view-item-submenus-0.0.1.zip)

**Comment by eamodio** [comment] 2021-04-17 19:12
I am seeing a similar issue with submenus on tree items, as I just added a new feature using that in GitLens:

![menu](https://user-images.githubusercontent.com/641685/115124233-2f70e680-9f8f-11eb-88c0-86bfb0eded19.gif)

The menu seems to be trapped inside the bounds of the item.

**Comment by gjsjohnmurray** [comment] 2021-04-21 05:02
This is biting me too. One of my extensions would benefit from a submenu dropping down from an inline command button. Everything works beautifully now we have submenu support (:+1: @jrieken ), except for its inability to escape the cage of the treeview.

Is a solution likely to be feasible as a contributed PR, or is the problem too deep / fundamental?

**Comment by sbatten** [comment] 2021-06-25 19:18
assigning to @alexr00 to see if she wants to tackle this at the custom tree view level or it needs @joaomoreno's eyes in the list widget

**Comment by sbatten** [comment] 2021-10-07 23:28
I've addressed this issue by removing the shadow dom-ification of the dropdown menu for submenu actions, but this fix introduces the disappearing submenu item because focus is lost.

**Comment by doradsoft** [comment] 2023-06-28 08:48
Hey, any news on the disappearing submenu item? Couldn't find a dedicated issue for this. Thanks.

**Comment by alexr00** [comment] 2024-12-12 16:50
Seems to be fixed!

**Closed** 2024-12-12 16:50 UTC
Labels: bug, menus, workbench-views
