### ISSUE TITLE
feature request: improvement to auto suggestions in html documents

### ISSUE THREAD

**Issue by ramvalleru** [Microsoft/vscode#35697] opened 2017-10-06 09:46 UTC
- VSCode Version: 1.170
- OS Version: Windows 10

Auto suggestions is the best way to improve productivity but I found that VScode doesn't provide suggestions for some things like suggesting default parameters to select.

For Example, If I use 
`<link rel="" href="">`
It would be better if when placing the cursor inside "", a suggestion like stylesheet appears.

**Comment by aeschli** [comment] 2017-10-09 07:16
duplicate of #2037

**Closed by aeschli** 2017-10-09 07:16 UTC
Labels: html
