### ISSUE TITLE
Integrated Terminal osx zsh encode

### ISSUE THREAD

**Issue by DeividWillyan** [microsoft/vscode#111179] opened 2020-11-23 14:39 UTC
I'm using vscode, when opening the integrated terminal, the zsh encode is incorrect, where can I parameterize correctly?

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.4.0
```

![image](https://user-images.githubusercontent.com/15814994/99974818-36991d00-2d80-11eb-8d6a-3ed7a3af046b.png)

**Comment by meganrogge** [comment] 2020-11-23 16:56
duplicate of #87366

**Closed by meganrogge** 2020-11-23 16:56 UTC
Labels: *duplicate, *question
