### ISSUE TITLE
Screen reader announcement for chat response is too verbose

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#212788] opened 2024-05-15 09:06 UTC
Have a response that contains references to code, e.g. :

![image](https://github.com/microsoft/vscode/assets/900690/d2a21631-564c-41e5-897f-f90656b4ba2c)

Start screen reader and click on the response. Notice how the full URLs are being read out aloud which are very long.

Verbatim text:

```
The [`IPositionList`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A14%2C%22character%22%3A4%7D%5D "Game.ts") interface you've defined in TypeScript extends from a base interface [`Base.IList`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Flib%2FBase.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "lib/Base.ts"). This means that [`IPositionList`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A14%2C%22character%22%3A4%7D%5D "Game.ts") inherits all the properties and methods of [`Base.IList`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Flib%2FBase.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "lib/Base.ts") and adds some more specific ones. 

Here are the additional properties and methods in [`IPositionList`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FGame.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A14%2C%22character%22%3A4%7D%5D "Game.ts"):

- `data: Position;` This is a property of type [`Position`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A46%2C%22character%22%3A4%7D%5D "Position.ts"). It's not clear from the provided code what [`Position`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A46%2C%22character%22%3A4%7D%5D "Position.ts") is, but it's likely a custom type or interface defined elsewhere in your code.
- `push(pos: Position);` This is a method that takes a [`Position`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A46%2C%22character%22%3A4%7D%5D "Position.ts") object as an argument. The implementation of this method is not provided in the interface, it's expected to be provided in any class that implements this interface.
- `pop(): Position;` This is a method that doesn't take any arguments and returns a [`Position`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22external%22%3A%22file%3A%2F%2F%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2FPosition.ts%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A46%2C%22character%22%3A4%7D%5D "Position.ts") 
```

I think this stems from the fact that we just take the response as string here:

https://github.com/microsoft/vscode/blob/ffb2581f0866e2ec33d2853e593955e3e8535796/src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts#L35

**Comment by bpasero** [comment] 2024-05-15 13:00
@alexdima made a good point in our standup today: why are we not leveraging the HTML screen reader support for chat items but use `aria.alert`?

https://github.com/microsoft/vscode/blob/ffb2581f0866e2ec33d2853e593955e3e8535796/src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts#L41

**Comment by meganrogge** [comment] 2024-05-15 18:14
The HTML screen reader support requires users to enter different modes to navigate - browse/focus mode. Feedback from screen reader users suggested this is not user friendly. 

Users will examine content in detail in the chat accessible view, not here. Providing an overview of the response with aria alert is desired. This is similar to how sighted users see the response streaming in. Screen reader users press escape if they don't wish to hear the content.

**Comment by meganrogge** [comment] 2024-05-15 18:16
I agree it's not good that it's reading the full URLs. A similar problem is here https://github.com/microsoft/vscode/issues/210665 and my solution to that will be to remove those links and provide an alternate way of setting any keybindings which are undefined.

**Comment by rzhao271** [comment] 2024-05-30 16:07
LGTM now. I might've forgotten to update something.

**Comment by meganrogge** [comment] 2024-05-30 16:07
A screenshot of the text that was announced would help to know if this was fixed or not @rzhao271

**Comment by rzhao271** [comment] 2024-05-30 16:13
nvm. The symbols are good but the URLs still expand


![Screenshot showing URLs expanding in the speech visualizer in NVDA](https://github.com/microsoft/vscode/assets/7199958/5732b3ec-e5c3-4c0e-82b9-66113472b5ea)

**Comment by meganrogge** [comment] 2024-05-30 18:09
unclear how this could be happening as I'm using `renderStringAsPlaintext` https://github.com/microsoft/vscode/blob/122174250208c93bf9a8ebee92b4e414719444dc/src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts#L42

**Comment by meganrogge** [comment] 2024-05-30 18:17
figured it out

**Comment by sandy081** [comment] 2024-05-31 12:30
@meganrogge It is still reading the complete path for me.

**Comment by meganrogge** [comment] 2024-06-03 17:03
@rzhao271 and @sandy081 the complete path is expected. what's not expected is these chars `5B%7B%22%24m`

**Comment by meganrogge** [comment] 2024-06-03 17:41
going to see if I can repro on windows

**Comment by meganrogge** [comment] 2024-06-04 22:08
does not reproduce for me on windows either 😭 . It makes no sense that this would happen - @rzhao271 , we literally parse that stuff out. could you pls debug in oss here? 

https://github.com/microsoft/vscode/blob/2ed875cb65b53d5bd14b087e8adc99e869bfb806/src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts#L43

![Image](https://github.com/microsoft/vscode/assets/29464607/b3588704-5399-44fe-876b-9a240a37bcdb)

**Comment by rzhao271** [comment] 2024-06-07 18:51
I believe the issue is fixed now.
I notice that when the announcement is read out that the links are now announced correctly. ✅ 
When I click on the response, the links are read with the Markdown formatting again, but I believe that this behaviour is out of scope of the issue.

**Closed** 2024-06-07 19:06 UTC
Labels: bug, accessibility, under-discussion, chat
