### ISSUE TITLE
Reference search broken?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#26020] opened 2017-05-05 10:50 UTC
* open `vs/base/common/strings.ts`
* go to line 296 and search for references of `getLeadingWhitespace`
* 🐛 it shows no result tho there are usages
* search for references of other types (class members, locals) seems to work

**Comment by mjbvz** [comment] 2017-05-05 18:37
The root cause of this appears to be: https://github.com/Microsoft/TypeScript/issues/15452

This should be fixed on the TS side. I tested with 2.4 nightly and see the references working correctly:
<img width="971" alt="screen shot 2017-05-05 at 11 36 33 am" src="https://cloud.githubusercontent.com/assets/12821956/25759386/299be7a2-3187-11e7-9c2e-154f056c6f29.png">

The TS 2.3.3 update for this month should also fix this

**Closed by mjbvz** 2017-05-05 18:37 UTC
Labels: javascript, upstream
