### ISSUE TITLE
User Settings causes file can not load！

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#18089] opened 2017-01-04 08:45 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (0347c19753f279a0c56ab2c8833de844f3be0e5d, 2017-01-04T07:09:56.180Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|output-colorizer|IBM|0.0.9|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

---

Steps to Reproduce:

1.  open a file 
2.  open User Settings  and switch to opened file 

![1](https://cloud.githubusercontent.com/assets/8591065/21636292/07b4ee52-d29d-11e6-9978-1e50bab6efcd.gif)

**Comment by sandy081** [comment] 2017-01-04 09:10
Duplicate of #18055

**Closed by sandy081** 2017-01-04 09:10 UTC
Labels: duplicate
