### ISSUE TITLE
Invisible Code in Terminal

### ISSUE THREAD

**Issue by MonoNeon** [microsoft/vscode#214059] opened 2024-06-01 15:22 UTC
Type: <b>Bug</b>

I have just started using VS Code and installed CodeRunner to run python codes in terminal. But if I run the code for the 2nd time, part of the text becomes invisible. This continues after running the code until the terminal text reaches the end of screen. After that every text starts to become visible.

![TerminalIssue](https://github.com/microsoft/vscode/assets/170505081/cfabc3b1-19c3-4e8e-aebb-3702bdc56653)

I noticed that if the terminal is resized using cursor, the text becomes visible. Please see to this issue.

![ResizeIssue](https://github.com/microsoft/vscode/assets/170505081/ed1fc253-162a-418e-a430-9c219837593c)

- Python Version: Python 3.12.3
`Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32`
- VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
- OS version: Windows_NT x64 10.0.19045
- settings.json
`{
    "workbench.colorTheme": "Dracula",
    "editor.fontSize": 16,
    "git.enableSmartCommit": true,
    "editor.snippetSuggestions": "top",
    "window.zoomLevel": 2,
    "code-runner.runInTerminal": true,
    "code-runner.saveFileBeforeRun": true,
    "code-runner.ignoreSelection": true,
    "files.autoSave": "off",
    "editor.mouseWheelZoom": true,
    "python.analysis.completeFunctionParens": true,
    "code-runner.clearPreviousOutput": true
}`

Since I am new here, please mention if I need to add more to this.

Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.82GB free)|
|Process Argv|--crash-reporter-id 103f0ca9-01f1-47bd-a99d-d8fecc76195b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by meganrogge** [comment] 2024-06-03 16:00
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-06-03 16:00 UTC
