### ISSUE TITLE
Build-in Terminal and tooltips don't use subpixel rendering

### ISSUE THREAD

**Issue by octoploid** [Microsoft/vscode#17827] opened 2016-12-26 12:48 UTC
- VSCode Version: 1.8.1
- OS Version: Linux

The build-in Terminal and the code tooltips are rendered with only grayscale anti-aliasing.
The code itself and the rest of the GUI is rendered with subpixel anti-aliasing.

So please also enable subpixel rendering for the tooltips and the terminal.

Thanks.

**Comment by Tyriar** [comment] 2017-01-03 18:01
I tried adding these to the terminal's CSS and it made no difference:

```css
text-rendering: optimizeLegibility;
-webkit-font-smoothing: antialiased;
```

Could you elaborate on what you expect, ideally with before/after screenshots? You can open dev tools via the help menu and fiddle with the DOM from there. I also didn't notice anything in the editor's CSS either that would indicate some special AA treatment.

**Comment by octoploid** [comment] 2017-01-03 22:35
![2017-01-03-233308_1080x1920_scrot](https://cloud.githubusercontent.com/assets/327746/21625709/2dadc7a4-d20d-11e6-8c44-4c2850afa90b.png)

Here is an example. Note the subpixel rendering of the source code. 
The terminal and the tooltip are only rendered with greyscale.

I would expect subpixel rendering everywhere.

**Comment by Tyriar** [comment] 2017-01-04 18:39
Ah, I see what you mean. I actually don't see it anywhere. Do you have a special font installed and what distro/version?

**Comment by Tyriar** [comment] 2017-01-04 20:55
Thanks, I can reproduce on Ubuntu with:

```
gsettings set org.gnome.settings-daemon.plugins.xsettings rgba-order 'bgr' # default: 'rgb'
```

**Comment by Tyriar** [comment] 2017-01-04 20:59
@alexandrudima any ideas why this would be the case? I don't see any style differences between the two that make a difference.

**Comment by alexandrudima** [comment] 2017-01-21 14:59
@Tyriar Yes.

I recommend reading https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/

Specifically:
> ![image](https://cloud.githubusercontent.com/assets/5047891/22175292/5ec2a59c-dff2-11e6-9a26-d7430af0020e.png)

Please also note that subpixel aliasing gets turned off in other circumstances, such as using `window.zoomLevel != 0` or using scaling at the OS level.

**Comment by SailorMax** [comment] 2017-03-09 09:54
Possible problem in "DIV.terminal-wrapper active". But I can't find the reason and solution.

I can see difference in output texts if put two similar SPANs before it and inside it:
```html
<span style="font: 21px Consolas;position: absolute;top:0;background-color:black;color: #cd3131;">[+0 ~2 -0 !]</span>
<div class="terminal-wrapper active">
<span style="font: 21px Consolas;position: absolute;top:0;background-color:black;color: #cd3131;left: 200px;">[+0 ~2 -0 !]</span>
```

Looks at "!" at end of test string

**Comment by Tyriar** [comment] 2017-03-09 17:58
@SailorMax trying to repro this outside it seems to work initially, then if I disable the font style it goes away, re-enabling it doesn't add subpixel rendering back though :confused:

**Comment by SailorMax** [comment] 2017-03-10 09:02
Additional:
If setup to first SPAN z-index:1000, but second z-index:100 => broken will be first SPAN, but second ok :)
If open source of VSCode with our SPANs in latest Chrome, there is same problem.
We need Chromium developer for this bug :)

**Comment by SailorMax** [comment] 2017-03-10 09:08
Additional2:
Problem exists when in VSCode opened any file. If close all files, but leave only console, text will be fixed after 2 seconds (few times).

**Comment by bpasero** [comment] 2017-04-18 17:14
Btw I am seeing subpixel-antialiasing being used for the terminal on my Windows machine at home (running inside parallels with 125% scaling in Windows) but not at work. So this seems a bit random.

**Comment by Tyriar** [comment] 2017-04-18 17:21
@bpasero weird, I've never seen it working. I wouldn't notice without screenshotting and zooming in though.

**Comment by vvs** [comment] 2017-09-14 09:31
Yes, I see this fuzziness of the terminal fonts on my Windows machine, the screenshot is in #34362.

**Comment by Tyriar** [comment] 2017-09-14 16:14
@vvs you're observations are spot on, tomorrow insiders should be better (https://github.com/Microsoft/vscode/issues/34119), at least for the terminal (not sure if tooltip will have sub-pixel AA.

**Comment by octoploid** [comment] 2017-09-16 13:17
It seems to work now. With todays version 1.17.0 commit e6874a384 the terminal 
now uses sub-pixel AA.
Tooltips are still broken.

**Comment by Tyriar** [comment] 2017-09-28 15:50
@octoploid glad you noticed 😄 

There are a few caveats to the support right now so I'll keep this open; it doesn't work on tooltip still as well as text using 256 colors (not the standard 16 xterm colors), and text not on the default background color.

**Comment by erichiller** [comment] 2017-10-10 20:37
I'm seeing poor terminal text rendering in the newest release (September 2017) on Windows. The editor is fine, just the terminal.

**Comment by dquagebeur** [comment] 2017-10-10 20:48
Hi, me too. I'm on Xubuntu. Editor is still fine (as before update) but the terminal is 'broken' with lot of space between chars.

**Comment by asifm** [comment] 2017-10-10 20:54
Here too: blurry terminal after upgrading to the latest version (1.17.1) of VS Code. 
![image](https://user-images.githubusercontent.com/3958387/31409879-5cdcad60-addb-11e7-89d4-c5ed38ee4c57.png)

![image](https://user-images.githubusercontent.com/3958387/31409910-7cea5dd2-addb-11e7-92c2-dd33f35983c7.png)

**Comment by Tyriar** [comment] 2017-10-11 15:16
The 1.17.1 blurry font issue is tracked in https://github.com/Microsoft/vscode/issues/35991

**Comment by Tyriar** [comment] 2017-12-22 03:54
Closing this off as terminal now uses SPAA and the tooltip does not, just like in the editor (not sure why).

**Closed by Tyriar** 2017-12-22 03:54 UTC
Labels: bug, help wanted, integrated-terminal, upstream
