### ISSUE TITLE
Use the shortcut keys in the keyboard to lock the intellisense window

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode#166883] opened 2022-11-18 01:52 UTC
![image](https://user-images.githubusercontent.com/100815370/202598245-60c2e5da-933b-4967-ab61-0cc1ede2fd41.png)

Can I use the shortcut keys in the keyboard to lock the intellisense window, or use the keyboard to turn pages of it?

It is often troublesome to switch from the keyboard to the mouse when editing.

**Comment by mjbvz** [comment] 2022-12-01 16:19
Duplicate of #167264

**Closed by mjbvz** 2022-12-01 16:19 UTC
