### ISSUE TITLE
vscode under wsl following link accidentally to windows directory

### ISSUE THREAD

**Issue by hare0319** [microsoft/vscode#173910] opened 2023-02-09 09:09 UTC
Type: <b>Bug</b>

Having file structure like following under wsl subsystem:
- tsconfig.json
- conf
  - tsconfig.json
- src
  - lib
    - Cart.ts
  - main.ts

In "./conf/tsconfig.json" define path aliases with
```json
  "paths": {
      "$lib": ["../src/lib"],
      "$lib/*": ["../src/lib/*"]
  }
```

And in "./tsconfig.json" extends configuration with:
```json
  "extends": "./conf/tsconfig.json"
```

When ctrl-click the path of this "extends" to follow the link. vscode would issue an error of `The editor could not be opened because the file was not found.` And when following the suggestion to create the file, it actually create the file under windows file system, rather than wsl file system. The relative path is converted to absolute path like `/home/xx/test/conf/tsconfig.json`, and the `root` for this path is base on windows system, which is `C:\`. It is expected to be wsl root `\\wsl.localhost\Ubuntu\`.

However, in `./src/main.ts`, the path alias is recognised. `import Cart from '$lib\Cart'` is valid, and auto completion can suggest `$lib` when the statement is typing.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.56GB (3.41GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/scheng/Project/BNProj/BrNetGUI --remote=wsl+Ubuntu --crash-reporter-id 9e4a5040-55ec-47f6-8604-635af9f11c00|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|7.54GB (3.60GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|7.54GB (3.60GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-graphql-syntax|Gra|1.0.6
remote-wsl|ms-|0.75.1
material-icon-theme|PKi|4.23.1
vim|vsc|1.24.3
material-theme|zhu|3.15.6
vscode-tailwindcss|bra|0.9.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
vscode-deno|den|3.17.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-graphql|Gra|0.8.5
vscode-graphql-execution|Gra|0.1.7
vscode-graphql-syntax|Gra|1.0.6
playwright|ms-|1.0.7
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
vscode-thunder-client|ran|2.4.1
vscode-yaml|red|1.11.0
code-spell-checker|str|2.16.0
svelte-vscode|sve|107.0.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
89544117:30613380
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by mjbvz** [comment] 2023-02-20 15:45
Duplicate of #160979

**Closed by mjbvz** 2023-02-20 15:45 UTC
