### ISSUE TITLE
Multi session debug console missing output or showing wrong output

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83162] opened 2019-10-23 15:12 UTC
I have been debugging with two sessions simultaneously quite a lot this week and I have randomly seen the debug console lose output, or show output from session A when the dropdown shows session B.

I don't have good repro steps but it has happened several times. Here is a case when both happened:

![image](https://user-images.githubusercontent.com/323878/67407659-b4cb3480-f56c-11e9-9fd2-03fabc6719d9.png)

This is only the bottom of the debug output, and I can't scroll up. There should be more lines. Also this is not the output from the "Debug Server" session, it's from the "Run Tests" session.

**Comment by isidorn** [comment] 2019-10-23 16:34
Next two weeks I am out on vacation, thus assigning this to November
In the meantime let me know if you find nice repro steps.
Thanks a lot, really appreciate it

**Comment by isidorn** [comment] 2019-11-27 11:50
Closing as duplicate of https://github.com/microsoft/vscode/issues/83906
That issue is fixed, so if you still see this, please let me know and I can reopen

**Closed by isidorn** 2019-11-27 11:50 UTC
Labels: debug, under-discussion
