### ISSUE TITLE
Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by oliveolivia** [microsoft/vscode#88332] opened 2020-01-09 04:17 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2020-01-09 11:29
/duplicate of #74782

Please see steps in #74782 (comment) for current workaround.

**Closed** 2020-01-09 11:29 UTC
Labels: *duplicate, extensions
