### ISSUE TITLE
Emojis in the terminal offset the selection 1 per character

### ISSUE THREAD

**Issue by vikas027** [Microsoft/vscode#31694] opened 2017-07-29 01:25 UTC
### Environment
- VSCode Version: 1.14.2 (had the same issue in the previous version as well)
- OS Version: OS X 10.11.2

### Problem
See how a character (which is **=**)gets copied from the left and one character (which is **3**) from the right is skipped.
![vscode_issue](https://user-images.githubusercontent.com/6998650/28740974-366458be-7450-11e7-8c28-569221ad5578.gif)

### Steps to Reproduce:
Select a text from Integrated Terminal, copy it using right click or cmd+c, and then paste it somewhere

**Comment by rmunn** [comment] 2017-07-31 07:28
I suspect the :beer: emoji in the terminal prompt is probably responsible for this, and that this would be reproducible by having any emoji (or any other character from one of the supplimentary Unicode planes) in your prompt. If what I suspect is correct, changing your prompt to contain *two* beer emojis (i.e., :beer::beer:) would cause the selection to be off by two characters rather than one, because some part of the selection code is counting code units when it should be counting codepoints, or vice versa.

For anyone not aware of the difference between code units and code points: a code point is a single Unicode character, like [U+1F37A](http://www.fileformat.info/info/unicode/char/1f37a/index.htm). In UTF-8, that character is represented as the sequence `0xF0 0x9F 0x8D 0xBA`. In UTF-16, it's represented by the surrogate pair `0xD83C 0xDF7A`. A "code unit" is the individual units of those representations; so `0xF0` is a code unit in UTF-8, and `0xD83C` is a code unit in UTF-16. A single code unit will *always be the same size* in any given Unicode encoding (8 bits in UTF-8, 16 bits in UTF-16). But a single code point will *vary in size*. People working in UTF-8 are constantly aware of this, but people who work in UTF-16 often forget this point since so many UTF-16 codepoints are a single code unit long.

**Comment by rmunn** [comment] 2017-07-31 07:29
This might be related to https://github.com/Microsoft/vscode/issues/26038. It probably stems from a different cause ultimately, but looking at how https://github.com/Microsoft/vscode/issues/26038 was resolved is likely to help with fixing this bug.

**Comment by Tyriar** [comment] 2017-07-31 16:13
@rmunn you're exactly right, 🍺 is causing the problem. Created https://github.com/sourcelair/xterm.js/issues/826

#26038 is related but the case is different, the problem there was just that there was an extra span. For this issue it appears that the selection logic is simply counting an emoji as the wrong number of characters.

**Comment by Tyriar** [comment] 2017-10-20 22:57
This should be fixed in v1.18, closing for verification.

**Closed by Tyriar** 2017-10-20 22:57 UTC
Labels: bug, integrated-terminal
