### ISSUE TITLE
Editor minimap is often disappearing.

### ISSUE THREAD

**Issue by vincedani** [Microsoft/vscode#29845] opened 2017-06-29 11:18 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-81-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.11|
|armsnippet|artofshell|0.7.0|
|code-gnu-global|austin|0.2.2|
|arm|dan-c-underwood|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|gitlens|eamodio|4.2.0|
|clangcomplete|kube|0.0.6|
|MagicPython|magicstack|1.0.10|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|vscode-icons|robertohuertasm|7.10.1|
|python|tht13|0.2.3|;
---

Steps to Reproduce:

1. Enable minimap: Settings -> "editor.minimap.enabled": true
2. Use the editor. (I use for larger cpp files (~1000 rows)

**Comment by caudatecoder** [comment] 2017-06-29 13:49
Confirm.
OS: Linux 4.4.0-81-generic, VSCode: 1.13.1
It didn't happen until 1.13 update.
The problem occurs even with small files and fix(for a while) by window reloading.

**Comment by rossnichols** [comment] 2017-06-30 23:05
100% repro for me: click inside the popup UI created by "peek definition".

**Comment by alexandrudima** [comment] 2017-07-04 09:50
Duplicate of #28093

**Closed by alexandrudima** 2017-07-04 09:50 UTC
Labels: editor, editor-minimap
