### ISSUE TITLE
Extensions Don't Work After Insiders Update

### ISSUE THREAD

**Issue by rebeccazee** [microsoft/vscode#130257] opened 2021-08-06 12:48 UTC
Issue Type: <b>Bug</b>

I am using the insiders edition. It updated to the newest version just recently. I noticed that none of my installed extensions seem to work after the update. I can uninstall the extension and then that extension will work afterwards sa shown here:

For this particular extension I am showing uses source control but since none of the extensions seem to work anymore,  Visual Studio Code's Source Control just shows a category for changes as shown here:

When using this particular extension GitLens, it would show categories for Commits, Repositories, File History, Branches, Remotes, Stashes, Tags, Search & Compare as shown here:

If I close Visual Studio Code then the installed and enabled extensions get faded as if I disabled them as shown here.

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.22GB free)|
|Process Argv|--crash-reporter-id 14115fb5-c4f3-456d-a2da-8b22431f1a75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
gitlens-insiders|eam|2021.7.1905
vscode-html-css|ecm|1.10.2
remote-wsl|ms-|0.58.2
tabnine-vscode|Tab|3.4.21
vim|vsc|1.21.5
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt:30346833

```

</details>

**Comment by Mesteery** [comment] 2021-08-06 12:59
duplicate of https://github.com/microsoft/vscode/issues/130219

**Comment by rebeccazee** [comment] 2021-08-06 13:06
> duplicate of #130219

Thank you. I tried searching the issues if someone posted this already. I couldn't find it.

**Closed** 2021-08-06 13:10 UTC
