### ISSUE TITLE
Possible bug with highlighting current line

### ISSUE THREAD

**Issue by michael-yx-wu** [Microsoft/vscode#18795] opened 2017-01-19 16:00 UTC
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

In the attached gif, notice the weird colors on the right side of the screen. It looks like the lines are divided into buckets of 15 and the color changes as I move from one "bucket" to another. This is more noticeable in dark themes, but I observe the same effect when using light themes. 

![jan-19-2017 10-54-01](https://cloud.githubusercontent.com/assets/3681045/22113920/d7ff5400-de35-11e6-8a17-de170441ddf7.gif)

Could this be a MacOS Sierra issue? I'm using the `Settings Sync` package. I don't see on my other mac and the only difference I can think of is the other one is running MacOS El Capitain.

**Comment by alexandrudima** [comment] 2017-01-20 10:07
Indeed, it is a MacOS Sierra issue. Duplicate of #12473

**Closed by alexandrudima** 2017-01-20 10:07 UTC
Labels: editor
