### ISSUE TITLE
image zoom reversed

### ISSUE THREAD

**Issue by azatom** [microsoft/vscode#73676] opened 2019-05-13 17:13 UTC
Issue Type: <b>Bug</b>

On an opened image the pinch zoom in and out on touchpad is reversed. (All other programs works well, so it is not a windows setting. The percentage in status bar increases and the image is getting bigger when I close fingers on touchpad...)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by skprabhanjan** [comment] 2019-05-14 11:26
@mjbvz , This looks similar to https://github.com/microsoft/vscode/pull/61222.
So this change would require passing `window` instead of `container` [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/resourceViewer.ts#L499) and then using ctrlPressed similar to [this](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/resourceViewer.ts#L457) ?

**Comment by bpasero** [comment] 2019-05-14 17:23
I cannot reproduce.

**Comment by mjbvz** [comment] 2019-05-17 23:10
@azatom Can you please test this in the next [VS Code insiders build](https://code.visualstudio.com/insiders/)? #73775 looked into something similar

**Comment by warpdesign** [comment] 2019-05-20 11:46
@mjbvz Tested on a Surface Book with Windows 10 and the latest insider build appears to fix the problem.

I guess it's fixed in 4c1b302 and/or da5f838.

**Closed** 2019-05-21 17:53 UTC
Labels: help wanted, needs more info
