### ISSUE TITLE
"Open to the side" from Quick Open does not work if "Enable Preview From Quick Open" is checked 

### ISSUE THREAD

**Issue by maximilianschmitt** [microsoft/vscode#148254] opened 2022-04-27 11:40 UTC
Hitting `CMD+Enter` from Quick Open does not open to the side if `Enable Preview From Quick Open` is checked.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: macOS Monterey 12.3.1

Steps to Reproduce:

1. Uncheck the setting `Workbench › Editor: Enable Preview From Quick Open`
2. Hit `CMD+P` to open `Quick Open`
3. Open a file to the side from `Quick Open` by hitting `CMD+Enter`
4. The file does open to the side, even though it should

In this video you can see the behaviour in a VSCode instance with all extensions and custom settings disabled:

https://user-images.githubusercontent.com/3694962/165510224-0abfa63b-e9c1-410b-8918-eb89da2de212.mp4

**Comment by bpasero** [comment] 2022-04-27 12:08
I think we had decided that `Modifier+Enter` opens the editor in non-preview mode when preview editors are enabled in general. And when disabled, we use it to open to the side, so this works as intended currently.

**Comment by maximilianschmitt** [comment] 2022-04-27 12:29
@bpasero Thanks for the fast response! I understand. 

I have two thoughts:

- I use the `Modifier+K+Enter` to run the `View: Keep Editor` command after opening a preview editor which works fine at least for my workflow
- If we could customize the shortcut for `Modified+Enter` while `Quick Open` is open, we could have preview editors and also `Open to the side`. Currently, I cannot find a command for `Open to the side` though. Would it be possible to add an `Open to the side` command maybe?

**Comment by TylerLeonhardt** [comment] 2022-12-06 01:29
That would be covered when we do https://github.com/microsoft/vscode/issues/98479  so marking as a duplicate 

/duplicate https://github.com/microsoft/vscode/issues/98479

**Closed by TylerLeonhardt** 2022-12-06 01:29 UTC
