### ISSUE TITLE
semanticHighlighting: Support numbers in "constant" properties

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/vscode#92469] opened 2020-03-11 11:34 UTC
With the following code:

```ts
const colors = {
  RED: 'red',
  RED_PRIMARY: 'red',
  RED_500: 'red'
}
```

We get the following behaviour with the `semanticHighlighting` highlighting:

```ts
colors.RED // "RED" is highlighted
colors.RED_PRIMARY // "RED_PRIMARY" is highlighted
colors.RED_500 // "RED_500" is NOT highlighted... look, also Github highlights it :-)
```

I would expect **colors.RED_500** to be highlighted just like the two other properties.

This could maybe be considered a bug, but it could also be considered a lacking feature 😄

**Comment by IllusionMH** [comment] 2020-03-11 12:02
/needsMoreInfo

Could you provide screenshot?
What version do you use?
Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

I see no difference in highlight (VS Code Insiders)
![image](https://user-images.githubusercontent.com/1312662/76414065-4530d700-639f-11ea-887a-e2357751f756.png)

**Comment by christianalfoni** [comment] 2020-03-11 12:37
Hi there and thanks for the quick response!

I think I might have been confused by how the different themes does the highlighting. For example:

This is **Dracula Soft** without the `semanticHighlighting`:

<img width="228" alt="Screenshot 2020-03-11 at 13 31 08" src="https://user-images.githubusercontent.com/3956929/76417207-c0dd5480-639c-11ea-95a1-2d6a20f0fba8.png">

And this happens when I add the `semanticHighlighting`:

<img width="274" alt="Screenshot 2020-03-11 at 13 30 55" src="https://user-images.githubusercontent.com/3956929/76417224-caff5300-639c-11ea-983a-7e6a7f3a8c0e.png">

Though, with **Monokai Dimmed**, the complete opposite happens. This is without `semanticHighlighting`:

<img width="309" alt="Screenshot 2020-03-11 at 13 31 44" src="https://user-images.githubusercontent.com/3956929/76417285-e79b8b00-639c-11ea-8439-3af7d72c29a0.png">

And this is with `semanticHighlighting`:

<img width="277" alt="Screenshot 2020-03-11 at 13 31 55" src="https://user-images.githubusercontent.com/3956929/76417300-ee2a0280-639c-11ea-9457-e2396689f655.png">

To me it seems that `semanticHighlighting` seems to use the underlying color palette of the theme and does its own semantic behaviour on top, but accidentally chooses the "wrong" color?

**Comment by christianalfoni** [comment] 2020-03-11 12:44
Btw, I messed around with the config a bit:

```json
  "editor.tokenColorCustomizationsExperimental": {
    "property": {
      "foreground": "#f51b00"
    }
  }
```

Which results in this strange behaviour:

<img width="210" alt="Screenshot 2020-03-11 at 13 43 40" src="https://user-images.githubusercontent.com/3956929/76418126-5c22f980-639e-11ea-94f6-655e784c9c8f.png">

The underlying theme comes through

**Comment by christianalfoni** [comment] 2020-03-11 12:56
It looks to me that:

```
		<dict>
			<key>name</key>
			<string>User-defined constant</string>
			<key>scope</key>
			<string>constant.character, constant.other</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#be9af0</string>
			</dict>
		</dict>
```

User defined constants breaks? Maybe there is no term for that in the `semanticHighlighting`?

**Comment by IllusionMH** [comment] 2020-03-11 13:00
/cc @aeschli 

Strange, if you use RED500 (or RED200) there is an extra token
![image](https://user-images.githubusercontent.com/1312662/76418631-a2308b00-63a7-11ea-9c7a-a7540f484faf.png)

Unfortunately after couple of tests this token dissapeared.

**Comment by christianalfoni** [comment] 2020-03-11 13:03
Ah, look there, yeah... but it seems to be that `semanticHighlighting` does not support differentiating a property from a constant property then?

**Comment by aeschli** [comment] 2020-03-11 14:16
@christianalfoni How do you decide it a constant property? Because it is all uppercase?

**Comment by aeschli** [comment] 2020-03-11 14:32
I don't see any bugs with the example provided. When I try is, all X in `colors.X` get the same classification (property). Maybe this is right after editing and semantic highlighting has not yet been applied (I think that what @IllusionMH sees in his example)
![image](https://user-images.githubusercontent.com/6461412/76426531-7f07da80-63ab-11ea-8518-435ddfe351ad.png)

The difference to syntax highlighting is:
- object keys are classified as properties (can be discussed)
- we classify not as readonly, as that's not really sure. You could defined an interface where all the properties are marked as readonly

![image](https://user-images.githubusercontent.com/6461412/76427336-76fc6a80-63ac-11ea-9de0-599b51329019.png)

Here I see that we lack a rule to associate `property.readonly` to `variable.other.constant.property`. I will add that.

**Comment by christianalfoni** [comment] 2020-03-11 14:53
@aeschli Hi there!

Ah, this is great. Cause:

1. Yes, I see the semantic "overlay" is a bit delayed turning it on and off, so this is very likely what is being experienced

2. Adding `readonly` will actually fix the issue related to the library I work on, so that is supergreat!

And yeah, `constant` is meant as all uppercase :-)

**Comment by aeschli** [comment] 2020-03-16 11:00
Do you still see `RED_500` not highlighted? Is it always reproducible?

**Comment by christianalfoni** [comment] 2020-03-16 11:31
Oh, is this already released? Or how would I approach testing it?

**Comment by aeschli** [comment] 2020-03-16 12:55
It's in the latest insiders.

**Closed** 2020-03-23 13:36 UTC
Labels: needs more info

**Comment by christianalfoni** [comment] 2020-03-24 06:58
Hi there!

Very sorry for my late reply, but I found time to check this now and it works! Great 😄 👍 Thanks for looking into this!
