### ISSUE TITLE
issue accessing (writing?) to file from disk when open in vscode on macosx

### ISSUE THREAD

**Issue by sramam** [Microsoft/vscode#10951] opened 2016-08-25 12:28 UTC
- VSCode Version: 1.4.0
- OS Version: MacOSX

Steps to Reproduce:

Problem 1: VSCode gets into a very tight loop saving an open file.
It seems, if you save a file from VSCode and then make a modification to the same file from the shell, while the file is open in VSCode, it causes VSCode to go into a loop - saving the file continuously. 

1. Open a file in VSCode (e.g. package.json )
2. Remove a package from dependencies.
3. Save the file. 
4. Very quickly after (i tried 1-2 seconds after), 'npm install the_same_pkg -S' 

It causes the package.json tab in VSCode to go into a loop, toggling between the modified "circle" and close "x" in very quick succession.

The only way to recover seems to be to close the tab - at which point VSCode complains that 
there are unsaved changes. I've tried saving and not saving and not saving the perceived changes
from VScodes point-of-view. In either case, the npm modifications to package.json are lost. 

Killing the tab post modification-save from VSCode and then opening the file in a new tab does not seem to cause the same issue.

**Comment by bpasero** [comment] 2016-08-26 06:23
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by sramam** [comment] 2016-08-26 17:29
Thanks for the quick response.

You are spot-on - this does seem to be the problem. 
However, now I have different problem -  with ~30 extensions installed! 

Do you have ideas on how I can isolate which extension is causing the issue? 
Debug log? Or perhaps disabling all the extensions from the command line, and enabling them on one-by-one.

**Comment by bpasero** [comment] 2016-08-27 07:30
@sramam I fear there is no easy solution. I would first check if any of the extensions has an impact on text editors. Once we found the extension that is causing this I would be interested to find out the name and possibly sourcecode to see what kind of pattern is causing this.

Closing, since this is an extension issue. But please keep posting here for the findings.

**Closed by bpasero** 2016-08-27 07:30 UTC
Labels: needs more info, workbench
