### ISSUE TITLE
Find all references shows bogus results

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#22892] opened 2017-03-20 15:58 UTC
1. Do a find all references a couple of times
2. Notice that some results appear to highlight an empty line
3. After closing and reopening find all references widget result are no longer bogus

Notice that I only started seeing this today, it was working fine last week

Just try doing find all references a couple of times on the MenuRegistry [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L81)

![screen shot 2017-03-20 at 16 56 38](https://cloud.githubusercontent.com/assets/1926584/24108585/4dd5c5ba-0d8e-11e7-8ecb-bd8f8c5c6e0b.png)

**Comment by mjbvz** [comment] 2017-04-03 23:39
This looks like a duplicate of #22310. Did you change branches recently? Also, what version of TS is active in the workspace?

**Comment by isidorn** [comment] 2017-04-04 08:49
I do not know if I changed branches - this happened 15 days ago. 
I have tsc 2.1.4 installed.  This is our vscode repo and I have "typescript.check.tscVersion": false. So I am not sure which tsc you take in that case

**Comment by mjbvz** [comment] 2017-04-11 01:22
Ok, please let me know if you hit this again. I know that TypeScript can get goofy when switching branches though so I suspect this is a duplicate of #22310

**Closed by mjbvz** 2017-04-11 01:22 UTC
Labels: bug, duplicate, typescript
