### ISSUE TITLE
Wierd White lines appearing all over the workspace

### ISSUE THREAD

**Issue by srinathvs** [microsoft/vscode#117491] opened 2021-02-23 22:21 UTC
Issue Type: <b>Bug</b>

I am currently using Windows 10 and this started a couple of months ago, but this week, it has become unbearable. The White lines merely used to occlude my file explorer in my workspace, it was annoying and made reading names of files almost impossible, but it was still ok. this week was a new low even for this White line issue. Nhow it started intruding upon my code space, causing even greater issues while I am coding as well, I am not sure what could possibly fix this issue. I can only state that this issue also exists in the epic games launcher.

I am guessing this is an issue with the underlying JS framework and the graphics pipeline of my system not really working together properly. 

I am currently using a laptop with integrated and a discrete gpu. This problem is perisistent on windows 10.

The Atom code editor that also works on the same Electron JS framework does not have this issue. I have tried setting the global settings for the gpu being used to automatic and I have tried all the possible fixes listed online, but none have really worked for me.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.66GB free)|
|Process Argv|--crash-reporter-id 4a70d5f4-4666-491d-a3ea-29805fbc5464|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
path-intellisense|chr|2.3.0
vscode-html-css|ecm|1.10.2
glslx-vscode|eva|0.1.8
vscode-firefox-debug|fir|2.9.2
kite|kit|0.142.0
vs-color-picker|lih|1.0.0
csharp|ms-|1.23.9
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-wsl|ms-|0.53.4
open-html-in-browser|pea|2.1.3
vscode-css-peek|pra|4.1.0
java|red|0.75.0
vscode-yaml|red|0.15.0
html5-boilerplate|sid|1.1.1
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by IllusionMH** [comment] 2021-02-23 22:33
/needsMoreInfo

Could you please provide screenshot?

Does it look like this #93356 ?

**Comment by srinathvs** [comment] 2021-02-24 06:52
Yes, Andreii, that is exactly what my issue looks like as well. Apologies for not affixing the screenshot. I completely forgot about it. I just realized there was a thread for it already. Sent from Mail for Windows 10 From: Andrii DieievSent: Tuesday, February 23, 2021 4:34 PMTo: microsoft/vscodeCc: Srinath V.S.; AuthorSubject: Re: [microsoft/vscode] Wierd White lines appearing all over the workspace (#117491) /needsMoreInfoCould you please provide screenshot?Does it look like this #93356 ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by IllusionMH** [comment] 2021-02-24 12:53
This one is duplicate of #93356 then
See for current workaround https://github.com/microsoft/vscode/issues/93356#issuecomment-604657278 and also https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 as one of ways problem was resolved


@deepak1556 I've checked all related issues and wasn't able to find link for upstream issue. Do you know if there is one?

/assign @deepak1556

**Comment by deepak1556** [comment] 2021-02-24 18:09
Thanks for triaging the issue, the web playground was working fine so I had closed the other issues that a fix in runtime will come eventually with newer chromium updates, but doesn't seem to be the case. Will keep this open to investigate.

**Comment by srinathvs** [comment] 2021-02-24 18:12
Disabling thegpuu seems to have fixed the issue for  me as well. Thanks

**Comment by 8Observer8** [comment] 2022-07-12 09:46
Sometimes I have the same issue in VSCode v1.69.0, Windows 10 and Asus K53SV. See on top-right and bottom-left corners:

![image](https://user-images.githubusercontent.com/3908473/178461321-d6071893-c426-4f8f-8af1-23ee610ef660.png)

**Closed** 2022-12-12 18:59 UTC
Labels: upstream, windows, electron, gpu
