### ISSUE TITLE
Allow command palette width to be adjustable

### ISSUE THREAD

**Issue by johnnyoshika** [microsoft/vscode#122666] opened 2021-04-29 14:14 UTC
The command palette , ie the dialog that opens via:

* <kbd>CTRL</kbd>+<kbd>p</kbd>
* <kbd>Cmd</kbd>+<kbd>p</kbd>
* <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd>
* <kbd>Cmd</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd>

...can be too narrow for certain scenarios:

![image](https://user-images.githubusercontent.com/504505/116564637-04a15f00-a8ba-11eb-982a-2e02c69de63a.png)

Visual Studio (non Code version) allows resizing of the command palette:

![image](https://user-images.githubusercontent.com/504505/116565106-66fa5f80-a8ba-11eb-959a-4be6a3ca34e2.png)

It would be nice if VS Code allowed this.

**Comment by TylerLeonhardt** [comment] 2021-05-04 14:10
/duplicate of https://github.com/microsoft/vscode/issues/85374

**Closed** 2021-05-04 14:11 UTC
Labels: *duplicate
