### ISSUE TITLE
Linked libraries are not suggested with require/import

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#40036] opened 2017-12-11 17:00 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063

---

Steps to Reproduce:

1. cd into library 
2. run `npm link`
3. cd into the project that utilizes the library
4. run `npm link my-library`
5. open a `js` or `ts` file and do a `require` or `import` to get intellisense

Expected output:

Suggestions of the linked library should show up for autocompletion

Actual output:

Only non-linked libraries show up in the intellisense

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-12-11 18:16
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/20401 . Can you please try following up on that issue. It was marked as a duplicate of https://github.com/Microsoft/TypeScript/issues/8760

**Closed by mjbvz** 2017-12-11 18:16 UTC
Labels: javascript
