### ISSUE TITLE
wrong indentation detection for python

### ISSUE THREAD

**Issue by beantowel** [microsoft/vscode#62464] opened 2018-11-02 12:33 UTC
Issue Type: <b>Bug</b>

open a file including these line:
```python
def foo(bars):
    for bar in bars:
        pass
```
vs code will detect the indentation as `Spaces: 8`, where the correct indentation setting should be 4 spaces.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-38-lowlatency

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
thrift|cdu|0.0.1
vscode-markdownlint|Dav|0.21.0
code-runner|for|0.9.5
latex-workshop|Jam|5.13.0
racket|kar|0.0.3
vscode-clang|mit|0.2.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.2
cpptools|ms-|0.20.1
vscode-yaml|red|0.0.17
cmake|twx|0.0.17
clang-format|xav|1.6.2

</details>

**Comment by kieferrm** [comment] 2018-11-02 16:20
The auto indentation rules come from the Python extension. Please file the issue there: https://github.com/Microsoft/vscode-python/issues. Thanks!

**Comment by beantowel** [comment] 2018-11-03 04:48
> The auto indentation rules come from the Python extension. Please file the issue there: https://github.com/Microsoft/vscode-python/issues. Thanks!

i've tried disable all the extensions and reload the window, the problem still there.

**Comment by ccaspers** [comment] 2018-11-03 14:40
> > The auto indentation rules come from the Python extension. Please file the issue there: https://github.com/Microsoft/vscode-python/issues. Thanks!
> 
> i've tried disable all the extensions and reload the window, the problem still there.

Same here. The detected indentation is wrong, regardless of the python extension being enabled or not.

**Comment by teodorlu** [comment] 2019-03-18 13:36
I'm also encountering this issue.

* I do not have the `vscode-python` extension installed
* I can reproduce with the text below
* `code -version`: 1.32.3 a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 x64

```python
import contextlib


@contextlib.contextmanager
def readonly_odb(odbpath):
    import odbAccess
    odb = odbAccess.openOdb(path=odbpath, readOnly=True)
    try:
        yield odb
    finally:
        odb.close()


def testodb(odbpath):
    import odbAccess
    with readonly_odb(odbpath) as odb:
        pass


def main():
    testodb(r"C:\temp\smalloutput\BF-K11_004-p03_d90_2019-03-10.odb")
    pass
```

**Comment by prof7bit** [comment] 2019-04-04 07:40
This does **not** trigger the bug, it is detected as 4 spaces:
```python
class Foo:
    def bar(self):
        pass
```
This **does** trigger the bug and is detected as 8 spaces:

```python
def foo():
    for i in range(3):
        print(i)
```
All extensions are disabled.

It is the parenthesis on the first line that makes the difference! If I remove the () from the "def foo():" then without changing anything else it would correctly detect it as 4 spaces!

**Comment by lucasgcb** [comment] 2019-04-23 07:52
> It is the parenthesis on the first line that makes the difference! If I remove the () from the "def foo():" then without changing anything else it would correctly detect it as 4 spaces!

Can confirm. All my pytest files are quite annoying to deal with because of this.

**Comment by JackLiar** [comment] 2019-04-30 00:41
please fix this problem, it's really annoying...... :(

**Comment by JackLiar** [comment] 2019-04-30 00:46
on macOS 10.14.4/Ubuntu 17.04, vscode 1.33.1
```python
def foo:
    for i in range(3):
        print(i)
```
is wrong too

**Comment by head-wired** [comment] 2019-05-12 12:35
I have the same problem (Win 10 1809) vscode 1.33.1
automatic indentation is always a multiple of 8 (instead of 4) when pressing enter and going to a new line that requires an indentation change.

I'm pretty sure this worked correctly in the past.

**Comment by nuumio** [comment] 2019-05-24 07:11
Just ran into this with 1.34.0 on Ubuntu 18.04.2. Quite annoying especially in Python. I disabled all extensions and it still happens.

Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-50-generic

To reproduce create `foo.py` and write (with indent of 4 spaces):
```
def foo():
    if True:
        pass
```
Save, close and re-open `foo.py`. Add function `bar()` and indent is 8 spaces.
```
def foo():
    if True:
        pass

def bar():
        if True:
                pass
```
Workaround: Disable `Editor: Detect Indentation`.

**Comment by JAAdrian** [comment] 2019-07-08 18:59
> Just ran into this with 1.34.0 on Ubuntu 18.04.2. Quite annoying especially in Python. I disabled all extensions and it still happens.
> 
> Version: 1.34.0
> Commit: [a622c65](https://github.com/microsoft/vscode/commit/a622c65b2c713c890fcf4fbf07cf34049d5fe758)
> Date: 2019-05-15T21:55:35.507Z
> Electron: 3.1.8
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Linux x64 4.15.0-50-generic
> 
> To reproduce create `foo.py` and write (with indent of 4 spaces):
> 
> ```
> def foo():
>     if True:
>         pass
> ```
> 
> Save, close and re-open `foo.py`. Add function `bar()` and indent is 8 spaces.
> 
> ```
> def foo():
>     if True:
>         pass
> 
> def bar():
>         if True:
>                 pass
> ```
> 
> Workaround: Disable `Editor: Detect Indentation`.


I can confirm the same behavior on my side.

Version: 1.36.0
OS: Linux Mint 19 x64 5.0.0-20-generic

**Comment by rebornix** [comment] 2019-08-05 17:37
Close in favor of https://github.com/microsoft/vscode/issues/62143, which is fixed in master already.

**Closed by rebornix** 2019-08-05 17:37 UTC
Labels: bug, editor-autoindent

**Comment by stgoddv** [comment] 2019-09-17 01:13
I can confirm the same issue here.
I'm on ubuntu 

    def list(self, request):
        return self.get_paginated_response(serializer.data)

    def retrieve(self, request, pk=None):
            return Response(serializer.data)


Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Vs Code:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-27-generic
