### ISSUE TITLE
Git: hangs when opening git diff

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#23977] opened 2017-04-06 02:59 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|3.1.0|
|Go|lukehoban|0.6.57|
|cpptools|ms-vscode|0.10.5|
|Ruby|rebornix|0.10.4|
|java|redhat|0.1.0|
|vscode-open-in-github|sysoev|1.5.0|
|Material-theme|zhuangtongfa|2.3.5|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

1. click on a file from the source control/git panel
2. the diff fails to load.

Note the animated blue progress bars:
<img width="884" alt="screen shot 2017-04-05 at 10 58 13 pm" src="https://cloud.githubusercontent.com/assets/20231989/24735993/8dc2360a-1a53-11e7-8b22-434479dc856c.png">

**Comment by chrmarti** [comment] 2017-04-06 03:43
@josh-tepper Does this happen with all files or just with a specific one?

**Comment by josh-tepper** [comment] 2017-04-06 04:56
I actually can no longer reproduce this.  But it was happening for all files (both staged and not staged).  I will updated this bug if I am able to find a way to reproduce.  Let me know if there are any specific steps that you would like me to take!

**Comment by spocke** [comment] 2017-04-06 09:40
I can reproduce this issue on Ubuntu Linux running 1.11.0 it was working fine before the upgrade to the latest version I tried to disable all extensions but the problem is still happening on multiple projects so doesn't seem to be a local git problem of a specific project.

**Comment by joaomoreno** [comment] 2017-04-06 09:49
@josh-tepper @spocke Anything special about your workspace? Network shares? Symlinks?

**Comment by spocke** [comment] 2017-04-06 09:54
Right seem to have figured it out. It tries to connect to the git remote for some reason and I wasn't connected to the VPN. However not sure why it tries to do that thought the diffs where local only?

**Comment by joaomoreno** [comment] 2017-04-06 13:00
Good finding. Once you are connected to the VPN, does it work?

**Comment by melloc01** [comment] 2017-04-06 13:29
Happening here also.

- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-standardjs-snippets|capaj|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|monokai-plusplus|dcasella|1.3.0|
|dark-plus-plus-theme|DryWolf|0.0.9|
|vscode-javac|georgewfraser|0.0.30|
|docthis|joelday|0.4.3|
|vscode-styled-components|jpoissonnier|0.0.6|
|sublime-keybindings|ms-vscode|2.0.1|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|partial-diff|ryu1kn|0.2.0|
|gitblame|waderyan|1.3.0|;

**Comment by melloc01** [comment] 2017-04-06 13:30
I checked the developer tools, no errors there.

**Comment by melloc01** [comment] 2017-04-06 13:41
Humm.. after awhile the error appears. Yeah.. it seems to be related to DNS resolution.

```
shell.ts:475 net::ERR_NAME_RESOLUTION_FAILED

Error: net::ERR_NAME_RESOLUTION_FAILED
    at Error (native): Error: net::ERR_NAME_RESOLUTION_FAILED

Error: net::ERR_NAME_RESOLUTION_FAILED
    at Error (native)
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:15297)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

The remote is protected by a VPN, which I am in right now and can successfully `git pull` from there

**Comment by rhires** [comment] 2017-04-06 13:44
Combining this issue with mine (#23906) is. The issue here is better attended to and better documented.

**Comment by melloc01** [comment] 2017-04-06 13:48
Well... it is working right now.
But, after I restart it takes a while until it resolves the remote call.

- Why this call is affecting the source control diff?
**Note:** If I go Offline it loads the diff very quickly and it seems that the problem goes away.

**Comment by joaomoreno** [comment] 2017-04-06 13:55
Great to know guys, thanks for all the info!

**Comment by mkszepp** [comment] 2017-04-06 18:34
my problem is, that he is trying to load the file from local pc, but my files are on a network folder like `\\servername\webname`

![problem-fetch](https://cloud.githubusercontent.com/assets/19845290/24769817/1f245588-1b08-11e7-9f66-e3468db7f008.jpg)

**Comment by joaomoreno** [comment] 2017-04-07 13:21
@josh-tepper @spocke @melloc01 @rhires @juturu @crswll

Can you quickly give these bits a try?

- [Windows](https://az764295.vo.msecnd.net/insider/dc66fda881e66d7d2024dbe86f82bb805c3515b7/VSCode-win32-1.12.0-insider.zip)
- [macOS](https://az764295.vo.msecnd.net/insider/dc66fda881e66d7d2024dbe86f82bb805c3515b7/VSCode-darwin-insider-unsigned.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/dc66fda881e66d7d2024dbe86f82bb805c3515b7/code-insider-1.12.0-1491559368_amd64.tar.gz)
- [Linux 32bit](https://az764295.vo.msecnd.net/insider/dc66fda881e66d7d2024dbe86f82bb805c3515b7/code-insider-1.12.0-1491560389_i386.tar.gz)

**Comment by crswll** [comment] 2017-04-07 13:37
It works for me (macOS) but there's an interesting quirk. It shows the little loading thing over the git icon (which I've *never* seen) until I view a diff from the list (if the repo is unaccessible from my current network).

It works just fine when I'm on the right network in stable and Insiders.

**Comment by joaomoreno** [comment] 2017-04-07 13:38
Awesome. I just fixed the loading _thing_ in #24170 with another change.

**Comment by joaomoreno** [comment] 2017-04-07 14:05
Fixed by dc66fda88

**Closed** 2017-04-07 14:05 UTC
Labels: bug, git, important

**Comment by rhires** [comment] 2017-04-07 22:22
Yes. Works for me :-)

**Comment by rhires** [comment] 2017-04-08 00:07
Related issue: 
![screen shot 2017-04-07 at 8 03 32 pm](https://cloud.githubusercontent.com/assets/12577765/24823546/76dd8ad6-1bcd-11e7-8b7f-a8f37eddd7e6.png)

I have made a change, and yet my git view shows no change. In addition, it shows the little clock, rather than a "1" badge. Should this be a separate issue?

**Comment by isidorn** [comment] 2017-04-12 09:23
This is a larger change that touches all git operations. Adding verified after doing a code review since I can not reproduce this issue on my machine.

**Comment by crswll** [comment] 2017-04-13 11:50
@isidorn This happens when the remote repository can't be accessed and you're online. So, if the repo is only accessible over a VPN you'll see it.

**Comment by rhires** [comment] 2017-04-13 14:52
What does "remote" mean in this context? I would have thought that it's only the local changes on my machine in that directory/folder where git is keeping track of changes, rather than on some server somewhere...
