### ISSUE TITLE
editor.tokenColorCustomizations.textMateRules.settings.background not applied

### ISSUE THREAD

**Issue by bilogic** [Microsoft/vscode#32759] opened 2017-08-18 07:28 UTC
- VSCode Version: 1.15.1 x86
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Add to settings
```
 "editor.tokenColorCustomizations":
    {
        "textMateRules":[        
            {
                
                "name": "Invalid",                
                "scope": "invalid",
                "settings": {
                    "background": "#FF0000",
                    "foreground": "#FFFFFF"
                }
            }
        ],
        "strings": "#3ad900"        
    },    
```
2. ```foreground``` color #FFFFFF is applied, but ```background``` color #FF0000 is not, it remains as it is (#800F00)
3.  Using ```Generate color theme from current settings``` shows 2 sets of ```"Invalid"```
4.
```
		{
			"name": "Invalid",
			"scope": "invalid",
			"settings": {
				"background": "#800F00",
				"foreground": "#F8F8F8"
			}
		},
...
		{
			"name": "Invalid",
			"scope": "invalid",
			"settings": {
				"background": "#FF0000",
				"foreground": "#FFFFFF"
			}
		}
```
5. I'm expecting either set 1 or set 2 to be used, however, background is from set 1, foreground is from set 2.
6. Looks like a bug to me, or is it by design?

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-08-18 07:50
It's a known limitation.

duplicate of #3429

**Closed by aeschli** 2017-08-18 07:50 UTC
Labels: new release, workbench
