### ISSUE TITLE
Hot exit: Folders and Workspaces only

### ISSUE THREAD

**Issue by SirVeggie** [microsoft/vscode#108693] opened 2020-10-14 23:12 UTC
Currently the hot exit has the three options:
- Off
- OnExit
- OnExitAndWindowClose

I would like to see a new setting:
- OnWorkspaceClose (alternative suggestions: OnFolderClose, OnWindowClose)

I often open random single files with VSCode that I don't care about, so getting a dialog to discard them is good. Otherwise I have to manually discard them after opening VSCode next time.
However I like not having to discard or save Workspaces.

So I want hot exit on Window Close if it has a Workspace or a Folder open, but not when it doesn't, even when exiting.

The closest option of the three available ones is OnExitAndWindowClose.
What I want seems to be OnExitAndWindowClose without the OnExit part.

**Comment by Tyriar** [comment] 2020-11-02 21:02
The main reason the 2 settings OnExit and OnExitAndWindowClose exist was to allow the user to opt-in to allowing windows to "go missing" when a hot exit happens. In other words, if you only have OnExit set, when you close VS Code and reopen it, all backed up workspaces will display.

> So I want hot exit on Window Close if it has a Workspace or a Folder open, but not when it doesn't, even when exiting.

Hot exit cannot happen in an "empty workspace" (no folder opened), this is because there was never a mechanism for reopening these as they never has real identifiers.

Additionally, "window close" happens before "exit", so if hot exit was allowed on window close, it implicitly works on exit. I'm going to close this out as design as the feature is already complex enough without adding another case like this. I'd recommend just using OnExitAndWindowClose as it offers the most flexibility.

**Comment by SirVeggie** [comment] 2020-11-02 21:10
> Hot exit cannot happen in an "empty workspace" (no folder opened), this is because there was never a mechanism for reopening these as they never has real identifiers.

If I open only a single file, then there is no workspace/folder opened, and the explorer also says 'no folder opened'. However if this is the last vscode window open, then it will not prompt to save and instead will hot exit (it will preserve the files until next launch of vscode). So I am confused by your statement.

**Comment by SirVeggie** [comment] 2020-11-02 21:12
I just want an option that will in this specific case give me a prompt to save or discard like normal, while retaining the other OnExitAndWindowClose behaviour.

**Comment by Tyriar** [comment] 2020-11-02 21:15
I think that case you're talking about is when a single window is opened and it has no folder, this is because since it's the last window it's treated as an exit (on Linux or Windows), not a window close. That's not the case on macOS because the application can still be running without any windows.

**Comment by SirVeggie** [comment] 2020-11-02 21:41
Yes that is the case. On Windows (talking about windows with no folders open) when the closing window is not the last window, then an exit is not triggered, thus the window will prompt to save. However when the closing window is the last window, exit is triggered, thus not prompting to save and preserving that window's session instead.

This 'preservation of non-folder-windows on exit' behaviour is the one I want to disable.

Maybe some kind of logic like... when exiting, if 'window_count == 1 and !window.hasFolder' then prompt to save.

**Comment by Tyriar** [comment] 2020-11-03 16:41
Sorry but I'm going to close this off as designed as I don't believe such an option would get enough usage to warrant both the additional complexity another setting would present to the user add and the time it takes to implement/upkeep.

**Closed by Tyriar** 2020-11-03 16:41 UTC
Labels: *as-designed
