### ISSUE TITLE
Ability to open a file from the web 

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#137173] opened 2021-11-14 17:13 UTC
VSCode cannot open web resources.
Opening an URL should open the file in read-only mode.

For example if I don't have a file locally downloaded and just want to take a look at some CSS or JSON this would have the benefit to have the file opened in the same place where I do my work, with all the IntelliSense goodness. This eliminates the need to keep a browser beside the editor or needing to continuously download resources from the web and opening them.

**Comment by chrmarti** [comment] 2021-11-15 07:57
Not sure what kind of web resources you want to open, but there is the GitHub Repositories extension for browsing those: https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub

**Comment by yume-chan** [comment] 2021-11-15 08:01
I think it's same as #131773 (which has been closed)

**Comment by mhanuszh** [comment] 2021-11-17 20:57
> Not sure what kind of web resources you want to open, but there is the GitHub Repositories extension for browsing those: https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub

Yes, I'm aware of the GitHub Repositories extension, but it only works with Github repositories. My goal is to be able to open any online file.

> I think it's same as #131773 (which has been closed)

Yes, that is pretty much what I'm asking for. I'm sorry, but I wasn't able to find that issue when I was looking for existing issues with the same problem.


While this is not a necessary thing as the `curl` described in microsoft/vscode#131773 does work, I do believe that creating a native experience for opening network files would be a great QoL feature.

**Comment by chrmarti** [comment] 2021-11-18 08:24
Still not sure what kind of resource you would want to open, but this sounds like a corresponding extension might help accomplish this.

Closing this as duplicate of #131773.

**Closed by chrmarti** 2021-11-18 08:24 UTC
