### ISSUE TITLE
Spam Error: TextEditor disposed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30578] opened 2017-07-13 06:08 UTC
Our tests and also often the dev console are full of these errors:

```
Error: TextEditor disposed
    at MainThreadEditors.$trySetDecorations (file:///Users/travis/build/Microsoft/vscode/out/vs/workbench/api/electron-browser/mainThreadEditors.js:144:56)
    at MainThreadService.AbstractThreadService.handle (file:///Users/travis/build/Microsoft/vscode/out/vs/workbench/services/thread/common/abstractThreadService.js:25:27)
    at invokeHandler (file:///Users/travis/build/Microsoft/vscode/out/vs/platform/extensions/common/ipcRemoteCom.js:202:53)
    at receiveOneMessage (file:///Users/travis/build/Microsoft/vscode/out/vs/platform/extensions/common/ipcRemoteCom.js:166:36)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I see no value in showing this error other than making it hard to read the test results to find an actual problem. This one seems to be ignored for many releases now so I suggest to remove it.

E.g.:

![image](https://user-images.githubusercontent.com/900690/28151198-7e8d8c3c-6799-11e7-80ec-6520eac8663b.png)

via https://travis-ci.org/Microsoft/vscode/jobs/253065123#L3436

**Comment by jrieken** [comment] 2017-07-17 08:33
This is the merge decorator, add `console.log('HERE', new Error().stack);` to `extHostEditor#setDecoration`

```
HERE Error
    at ExtHostTextEditor.setDecorations (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/node/extHostTextEditor.ts:418:23)
    at __dirname.removeDecorations.Object.keys.forEach.decorationKey (/Users/jrieken/Code/vscode/extensions/merge-conflict/src/mergeDecorator.ts:248:12)
    at Array.forEach (native)
    at MergeDectorator.removeDecorations (/Users/jrieken/Code/vscode/extensions/merge-conflict/src/mergeDecorator.ts:241:33)
    at MergeDectorator.<anonymous> (/Users/jrieken/Code/vscode/extensions/merge-conflict/src/mergeDecorator.ts:185:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jrieken/Code/vscode/extensions/merge-conflict/out/mergeDecorator.js:4:58)
```

**Comment by joaomoreno** [comment] 2017-07-28 08:09
It's incredibly hard to read travis logs right now.

**Comment by chrmarti** [comment] 2017-07-28 14:04
@jrieken There is a check if the editor is in `window.visibleTextEditors`, but that doesn't seem to help. What is the correct way to check if the editor is not disposed?

**Comment by chrmarti** [comment] 2017-07-28 23:19
@jrieken Using `console.log('HERE', this._disposed, new Error().stack);` shows that `this._disposed` is still false when passing through `extHostEditor#setDecorations`. This seems to be a timing issue between extension host and main process.

**Comment by chrmarti** [comment] 2017-08-02 15:42
extHostTextEditor already logs a warning in _runOnProxy() when the editor is disposed at the time setDecorations() is called. If the editor in the extension host is not disposed, but the one in the renderer process is (and the error is logged), the disposal and the setting of decorations were triggered at a similar time in different processes and it seems best to recover from this silently.

I suggest to remove the error. If an error is still desired, I'd suggest to change the warning in extHostTextEditor's _runOnProxy() to an error.

**Comment by isidorn** [comment] 2017-08-03 08:42
@chrmarti could you please look into this since all other participants are on vacation? Or assign it to august if it is not critical for our relase

**Comment by chrmarti** [comment] 2017-08-03 15:53
I don't see it as critical for the release. It is log entries for operations that should not run and also are not run. This is without further side-effects. @joaomoreno labelled it as important with regard to the noise in the test runs. I'll postpone it to August if there are no objections.

**Comment by jrieken** [comment] 2017-08-14 08:39
Nice fix, not. The problem is explained here: https://github.com/Microsoft/vscode/issues/30578#issuecomment-315695596

**Comment by chrmarti** [comment] 2017-08-14 14:12
@jrieken This seems to be a race condition on the API's side. See https://github.com/Microsoft/vscode/issues/30578#issuecomment-318783240 .

**Comment by jrieken** [comment] 2017-08-14 16:17
> This seems to be a race condition on the API's side

That might well be but the "fix" of this picking this one call is a little lame, isn't it? If we understand this problem why don't we tackle it for all other calls like `tryRevealRange` etc. Why don't we handle this properly in the `_runOnProxy` with a well known error code? This just looks like a shortcut to me

**Comment by chrmarti** [comment] 2017-08-14 17:10
We wanted to make progress on this "important" issue in your absence without devising a general solution without your input.

**Comment by jrieken** [comment] 2017-08-15 07:48
I understand that, but I would have just removed the "important" label because this is really just debt

**Closed** 2017-08-16 09:29 UTC
Labels: debt, engineering
