### ISSUE TITLE
Integrated Terminal: Some characters not being rendered correctly

### ISSUE THREAD

**Issue by chitsaou** [Microsoft/vscode#34121] opened 2017-09-11 08:19 UTC
- VSCode Version: Version 1.17.0-insider (1.17.0-insider) `2c385b98066eebb8e39dfd98b1fcb8cc254196b6`
 2017-09-11T05:06:55.533Z
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. Open Integrated Terminal
2. type `echo "\xE2\x9E\x9C"` and hit enter. (Assume encoding is UTF-8)

The character `➜` (U+279C) is what I am using in command prompt.

Here is the result. As you can see it is not rendered correctly.

The font I am using is [Fira Mono](https://mozilla.github.io/Fira/).

![screen shot 2017-09-11 at 17 17 11](https://user-images.githubusercontent.com/10737/30264812-1d432b16-9715-11e7-8b93-5923e06d495e.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-09-11 15:32
Duplicate of https://github.com/Microsoft/vscode/issues/34138

**Closed by Tyriar** 2017-09-11 15:32 UTC
Labels: insiders
