### ISSUE TITLE
Allow setting key binding for clearing filter in explorer view

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#101230] opened 2020-06-28 13:22 UTC
The only key I can use is Esc to clear the filter.
It doesn’t seem possible to map his to any other key.

Can this be added to the key binding list?

![](https://code.visualstudio.com/assets/docs/getstarted/userinterface/file-explorer-filter.png)

**Comment by isidorn** [comment] 2020-06-29 12:23
This is a fair feature request against the list.
However this is a duplicate of https://github.com/microsoft/vscode/issues/66898
Which we already discussed we will not do. However maybe @joaomoreno changed his mind so forwarding also to him

**Comment by jasonwilliams** [comment] 2020-06-29 12:34
> Which we already discussed we will not do. 

@isidorn Could you explain why last time you didn’t want to do this? I couldn’t work it out from the last issue, I don’t see why you wouldn’t want users to be able to remap this?

**Comment by isidorn** [comment] 2020-06-29 12:38
Lack of time.
We do want this, but didn't have a chance to work on this.

**Comment by jasonwilliams** [comment] 2020-06-29 12:52
@joaomoreno @isidorn if this is something you do want to do (but don’t have time) does it need the votes, shouldn’t it go straight into the backlog?

It’s not like you need to decide whether it’s worth doing or not.

**Closed** 2020-10-30 14:17 UTC
Labels: *out-of-scope, feature-request, list
