### ISSUE TITLE
Menus show up all black frequently

### ISSUE THREAD

**Issue by nmeocisco** [microsoft/vscode#89255] opened 2020-01-24 21:00 UTC
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04.3 LTS

See attached screenshot. I am running vscode in Ubuntu 18.04.3 within VirtualBox 6.1.2 with the guest additions installed using the VMSVGA display device and 3D acceleration enabled. I am frequently getting a problem where when click on menus they show up completely black. This only happens after running for a little while and not initially when vscode starts. When this problem happens I restart vscode and the menus will then display fine, but eventually the problem will come back again.

![Screenshot_2020-01-24_15-52-00](https://user-images.githubusercontent.com/49691353/73103343-e0d6b880-3ec1-11ea-92ee-f36f1e63b726.png)

**Comment by tanant** [comment] 2020-01-24 22:35
Same symptoms here on my setup:

* VSCode Version: 1.41.1
* Host OS is Win10 1909 (18363.592) running Virtualbox 6.1.2 r135662
* Guest OS is  Debian Buster (10.2) / XFCE

Going to try run code for a bit with `--disable-gpu` to see if that has any impact.

**Comment by ferolivares98** [comment] 2020-01-25 12:16
Same here:
- VSCode Version: 1.41.1
- Host is Windows 10 (1809 - 17763.973) and VirtualBox 6.0.16 with dual monitor.
- Guest is Linux Mint 19.3 Tricia.

It seems to happen randomly and affects differents windows and the right click.

**Comment by tanant** [comment] 2020-01-30 01:30
So it's not the best datapoint, but so far so good with --disable-gpu. I don't know if it's placebo-ish, so I'll stop running code that way, and see if the problem resumes.

**Comment by nmeocisco** [comment] 2020-02-27 14:11
Just to follow up, I have tried using `--disable-gpu` as suggested for a while now and have not encountered the problem since, so it appears to be related to the GPU acceleration code.

**Comment by deepak1556** [comment] 2020-03-11 04:51
Thanks for the updates,  closing this as a duplicate of https://github.com/microsoft/vscode/issues/84745

Virtualbox issues linked at https://github.com/microsoft/vscode/issues/84745#issuecomment-561645280

Also you can disable gpu following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed by deepak1556** 2020-03-11 04:51 UTC
