### ISSUE TITLE
Can't debug node application

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#99526] opened 2020-06-06 16:22 UTC
As of the latest insiders version I cannot start node applications anymore. In the old version (with the old debugger) I would just press F5 and my launch config would start the application with the debugger attached. After the update without changing any configuration, the debugger attaches and detaches multiple times spamming the output console with text but the application itself is never started. There is no error and the debugging also doesn't stop.

I tried starting the application via *Node.js (preview)* as well. "debug" produces the same behaviour as my launch configuration. "start" **does** start the application but debugging obviously isn't working. However when it's finally running, restarting the application (Ctrl+Shift+F5) will crash VS Code entirely.

The application itself is working and also the `tsc` build isn't failing. I made the first screenshot using the same code base in VS Code stable and it worked just fine.

- VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
- OS version: Windows_NT x64 10.0.18362

**Steps to Reproduce:**

1. Open TS node application
2. Add launch configuration
3. Press F5

Does this issue occur when all extensions are disabled?: Yes

`.vscode/launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Programm ausführen (Debug)",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 9229,
        }
    ]
}
```

`package.json` (stripped):
```json
"main": "dist/index.js",
"scripts": {
    "build": "tsc",
    "prestart": "npm run build",
    "start": "node .",
    "debug": "npm run build && node --inspect-brk=9229 ."
}
```

**Console output before the update:**

![grafik](https://user-images.githubusercontent.com/11841072/83949057-f7066500-a821-11ea-9e63-245b6951fb6d.png)

**Console output since the update:**

![grafik](https://user-images.githubusercontent.com/11841072/83949087-2cab4e00-a822-11ea-8aeb-fc0f3de231bf.png)

**Comment by AdamCaoQAQ** [comment] 2020-06-08 14:10
I have the same problem，I had to use the stable version now ~ QAQ

**Comment by connor4312** [comment] 2020-06-08 17:37
Thanks for the issue! Insiders recently updated to our [new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly).

This debugger connects differently that the old debugger, which unfortunately is not compatible with `--inspect-brk` being called in a _nested_ script: we connect to processes by asking Node to `--require` a "bootloader" file before user code, and adding --inspect-brk will break in the bootloader before it's able to call back to vscode saying it's there to debug! If --inspect-brk is given directly in the `runtimeArgs`, we can rewrite it correctly, but since it's being invoked through npm in this case we can't do that.

Fortunately, VS Code does have a very nice API for doing what you're trying: tasks. You can create a file like this in `.vscode/tasks.json`:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "build",
      "problemMatcher": ["$tsc"], // since you mentioned TypeScript
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

And then update your launch config to be something like:

```
{
  "type": "pwa-node",
  "request": "launch",
  "name": "Programm ausführen (Debug)",
  "program": "${workspaceFolder}/main.js", // or your 'main' file
  "stopOnEntry": true,
  "preLaunchTask": "npm: build", // run the build script before our main program:
},
```

(note: there seems to be a bug with stopOnEntry on some platforms, I will issue a fix for that today)

---

While it is a goal of js-debug to have perfect launch parity with existing configurations, I do not think there's any reasonable way we can get around this nested --inspect-brk scenario -- and the bootloader strategy gives us significant additional capability in many scenarios. Therefore, I will close this as designed.

**Closed** 2020-06-08 17:37 UTC
Labels: *as-designed

**Comment by vainamov** [comment] 2020-06-11 06:49
> A common pattern is to have your prelaunch task be `tsc --watch` so that it incrementally builds when your code changes. In that case you will also want to change the `problemMatcher` to `$tsc-watch`

Unfortunately this blocks the execution of the launch script.

**Comment by connor4312** [comment] 2020-06-11 15:09
There are some extra properties you might need for the watch task: https://medium.com/@stigi/make-vs-code-typescript-even-more-5f20f3046109

**Comment by connor4312** [comment] 2020-07-11 18:07
Lots of people running into this. I'm working on a workaround and should have something ready in an hour or two.

**Comment by connor4312** [comment] 2020-07-11 19:12
Message posted on linked issues -- in this particular issue I still recommend tasks as the "right" way to do things, but in case other people land here:

> Hi, following up on this issue after feedback from you and other users. There are two things to know:
> 
> 1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.
> 
> 1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).
> 
> Happy Coding!
