### ISSUE TITLE
The Show Context button on a Seach: tab doesn't work if your workspace has a large number of files

### ISSUE THREAD

**Issue by rrysolutions** [microsoft/vscode#97848] opened 2020-05-14 21:09 UTC
- VSCode Version: 1.45.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Add a folder to VS Code that has a large number of files (mine had 7,874,044 files, a mixture of text files and binaries). All but 9,840 were in Excluded directories.
2. Do a search (mine resulted in just 11 results in 5 files). None of the files were in the excluded directories.
3. Click on "Open in editor"
4. Click on the "Show Context" button

This causes the blue progress thing to go across the top of the window endlessly. If it's stopped for any reason (e.g. clicking the context button again, switching tabs). The "Show Context" button no longer does anything (no context added, no progress Cylon). None of the search results were surrounded by context.

If I repeat this same test in a clean directory (a directory only contains files non-Excluded directories) then the context button works fine.

I've never tried to "wait out" the progress indicator. It may finish after a very long time. I don't know.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment] 2020-07-10 19:45
Thanks for filing this! I've been playing around with a bunch of large projects and unable to reproduce, I believe this is a duplicate of #97180 and should now be fixed. If you run into this in 1.47 please let me know :)

**Closed** 2020-07-10 19:46 UTC
Labels: search

**Comment by rrysolutions** [comment] 2020-07-14 03:03
Thanks for the update. I haven't seen the problem lately.

Best regards,
Ric
