### ISSUE TITLE
TypeError: value.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180188] opened 2023-04-18 07:06 UTC
```
ERR value.hasOwnProperty is not a function: TypeError: value.hasOwnProperty is not a function
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/telemetry/common/telemetryUtils.js:295:65
    at _cloneAndChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/objects.js:52:25)
    at cloneAndChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/objects.js:45:16)
    at cleanData (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/telemetry/common/telemetryUtils.js:293:45)
    at TelemetryService._log (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/telemetry/common/telemetryService.js:85:51)
    at TelemetryService.publicLog (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/telemetry/common/telemetryService.js:92:18)
    at TelemetryService.publicLog (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/telemetry/electron-sandbox/telemetryService.js:48:23)
    at WorkspaceTags.reportWorkspaceTags (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tags/electron-sandbox/workspaceTags.js:80:35)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tags/electron-sandbox/workspaceTags.js:42:36
```

**Comment by lramos15** [comment] 2023-04-18 14:31
Marking as duplicate of https://github.com/microsoft/vscode/issues/180196

**Closed by lramos15** 2023-04-18 14:31 UTC
Labels: bug, telemetry
