### ISSUE TITLE
Url encoded characters in Markdown relative paths

### ISSUE THREAD

**Issue by Guiorgy** [microsoft/vscode#121277] opened 2021-04-14 10:32 UTC
- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.19042(.867)

Problem:

A link in markdown like `[some C# file](C%23)/some.file` doesn't work in the peview (does nothing when pressed).
However, it does work as intended on **github.com**

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment] 2021-05-11 16:00
duplicate of #123228

**Closed** 2021-05-12 12:01 UTC
Labels: bug, help wanted, markdown
