### ISSUE TITLE
Graph bleeds into status bar when breakpoints exist

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#120749] opened 2021-04-07 17:17 UTC
Issue Type: <b>Bug</b>

See the recording.

![junk](https://user-images.githubusercontent.com/6726799/113907655-8a575080-97cd-11eb-9b8f-ee409918bb4b.gif)

Extension version: 0.0.14
VS Code version: Code - Insiders 1.56.0-insider (bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a, 2021-04-07T12:30:14.880Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.51GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 584c5b29-25dd-4f1c-a7c6-fb3b6998cbc6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment] 2021-04-07 17:23
Looks like the webview view size is incorrect

**Comment by mjbvz** [comment] 2021-04-07 19:43
Duplicate of #110450

**Closed by mjbvz** 2021-04-07 19:43 UTC
