### ISSUE TITLE
Integrated Terminal window become useless after resizing the side bar

### ISSUE THREAD

**Issue by kksevta** [Microsoft/vscode#9652] opened 2016-07-23 16:53 UTC
- VSCode Version:1.3.1
- OS Version: ubuntu 14.04

Steps to Reproduce:

1. open integrated terminal 
2. increase side bar width to max
3. resize it to original size and then try to type in terminal window.

**Comment by Tyriar** [comment] 2016-07-24 05:54
Can you take a screenshot of the issue?

**Comment by kksevta** [comment] 2016-07-24 06:13
Initial stage

![first](https://cloud.githubusercontent.com/assets/11193293/17082219/79a30764-5193-11e6-8fcb-0bc570236214.png)


Resized side bar to maximum width
![second](https://cloud.githubusercontent.com/assets/11193293/17082223/91119622-5193-11e6-9db0-97cbc2a6ee5b.png)


Resized side bar to original width
![third](https://cloud.githubusercontent.com/assets/11193293/17082225/acb53f6e-5193-11e6-928c-4c75538a2ee6.png)



after third stage everything just goes wrong in terminal window

**Comment by Tyriar** [comment] 2016-07-25 22:24
Typing after the third stage will restore the prompt line though, correct? I believe this is a duplicate of https://github.com/sourcelair/xterm.js/issues/103

**Comment by kksevta** [comment] 2016-07-27 13:54
Nope for me. 
The window is stuck till death!!

**Comment by Tyriar** [comment] 2016-07-27 18:09
Can you check the console for errors? (Help > Toggle Developer Tools)

**Comment by kksevta** [comment] 2016-07-29 14:10
no errors at all

**Comment by Tyriar** [comment] 2016-07-29 14:43
Does this happen in the Insiders build? https://code.visualstudio.com/insiders

**Comment by kksevta** [comment] 2016-08-30 05:14
well this is not happening with the latest release. 
typing something in terminal window restore the window properly.

**Comment by Tyriar** [comment] 2016-08-31 18:22
I'll close this off then, do note that the current situation how the output gets truncated and not restored it is not ideal and is being tracked in another issue. Typing should restore the prompt currently though.

**Closed by Tyriar** 2016-08-31 18:22 UTC
Labels: integrated-terminal, needs more info
