### ISSUE TITLE
vscode macOS not using git creds from keychain like terminal

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#119201] opened 2021-03-17 18:46 UTC
- VS Code Version: 1.54.3
- OS Version: 10.15.7

Steps to Reproduce:

1. Configuring git to use credentials from the macOS keychain: 'git config --global credential.helper osxkeychain'
2. Confirm that after cloning a repo, you can pull/push from a terminal using credentials
3. Open vscode in the same local repo and try to pull/push files

This shows error message: 'Make sure you configure your 'user.name' and 'user.email' in git.

Expected: use the same 'user.name' and 'user.email' in keychain like the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by RPwnage** [comment] 2021-03-18 12:51
So it works fine when all extensions are disabled?

**Comment by u84six** [comment] 2021-03-18 15:45
> So it works fine when all extensions are disabled?

Sorry, I've updated the issue with a "Yes". With all extensions disabled, the message still pops up.

**Comment by eamodio** [comment] 2021-04-14 06:14
Duplicate of many issues. See https://github.com/microsoft/vscode/issues/114433. You can set `git.requireGitUserConfig` to `false` to disable the new behavior

**Closed by eamodio** 2021-04-14 06:14 UTC

**Comment by u84six** [comment] 2021-04-14 15:53
What does setting git.requireGitUserConfig to false have anything to do with git using the macos keychain to access creds? I've looked at the dupe issue and I don't see anything about mac keychain
