### ISSUE TITLE
Multisave corrupts files

### ISSUE THREAD

**Issue by AquariusFR** [Microsoft/vscode#18438] opened 2017-01-12 09:36 UTC
When multisaving, some files are "corrupted", there is chunk of code added in a file.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|jshint|dbaeumer|0.10.15|
|Angular1|johnpapa|0.1.16|
|csstriggers|kisstkondoros|0.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|java|redhat|0.0.8|
|stylelint|shinnn|0.21.2|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment] 2017-01-12 10:19
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by AquariusFR** [comment] 2017-01-12 10:58
Ok, i'll try this.

**Comment by bpasero** [comment] 2017-01-16 06:06
@AquariusFR any result?

**Comment by bpasero** [comment] 2017-01-23 13:17
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2017-01-23 13:17 UTC
Labels: needs more info

**Comment by AquariusFR** [comment] 2017-01-23 14:16
Sorry, to be so long, I have a loss this week .. :'(

So i have just tried these steps and in a vanilla version of VS Code, there is no bug anymore.

This issue can stay closed.

**Comment by AquariusFR** [comment] 2017-01-23 14:18
i think this is **JS-CSS-HTML Formatter** (lonefy.vscode-JS-CSS-HTML-formatter) that makes that bug.
