### ISSUE TITLE
VSC is very slow

### ISSUE THREAD

**Issue by xcever** [microsoft/vscode#115562] opened 2021-02-01 19:35 UTC
## The issue
The problem is that my VSC is extremely slow, making it difficult to follow what I am typing, and correcting my writing smoothly.
I am currently making notes, having a single pdf open in firefox. The pdf behaves normally (scrolling, zooming etc.)
The VSC has a folder open containing to Markdown files with very few notes until now.

## Extensions
Extensions were initially enabled, however based on a tip on reddit I disabled all, as I was only working in Markdown.

## My apologies
I know too little about how to use VSC properly to make my own diagnosis. Thank you for your time and effort.

**Comment by IllusionMH** [comment] 2021-02-01 19:38
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Also please see https://github.com/microsoft/vscode/wiki/Performance-Issues to find steps that would provide more info for dev team.

**Comment by andrew-dixon** [comment] 2021-02-05 09:28
@xcever Are you using macOS Big Sur? If so, try closing VSCode and then running this command on the command line:

```
codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app
```

This issue is caused by a change in macOS Big Sur that affects Electron, which VSCode is based on. References:

https://blog.axosoft.com/workaround-gitkraken-big-sur-issues/

and

https://github.com/libuv/libuv/issues/3050

**Comment by xcever** [comment] 2021-02-05 18:57
Thank you everyone for your help. The problem seemed to resolve itself
after lenovo updated something and i retstarted the computer after that.

If the problem does arise again, i will try your instructions first.

Cheers!
V

**Closed** 2021-02-05 21:36 UTC
Labels: *not-reproducible
