### ISSUE TITLE
Call Stack window doesn't scroll to the active thread when a breakpoint is hit

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#68277] opened 2019-02-08 19:47 UTC
- VSCode Version: 1.31.0
- OS Version: Windows 10

Steps to Reproduce:

1. Use the C/C++ extension to debug our Microsoft.VSCode.CPP.Extension.exe.
2. Hit a breakpoint.

Bug: The call stack windows doesn't scroll to the thread that is active (paused on a breakpoint). Stepping causes some buggy scroll to occur, but it still doesn't scroll to the correct call stack. This makes it difficult to locate which thread call stack I'm currently debugging.

![image](https://user-images.githubusercontent.com/19859882/52502174-efd03800-2b96-11e9-8a06-21bde20d8dc8.png)

Does this issue occur when all extensions are disabled?: Yes, but needs the C/C++ extension to debug.

**Comment by sean-mcmanus** [comment] 2019-02-08 19:48
This is not a duplicate of the 2 issues mentioned by the bot.

**Comment by Jeff-Lewis** [comment] 2019-02-12 18:29
I get the same behavior debugging using [PowerShell extension](https://github.com/PowerShell/vscode-powershell/). I see the `Hit Line breakpoint on...` in the Terminal but the Explorer sections 'Variables' and 'Watch' are empty, which make it look like it's not debugging, but it is. If I manually select the a line in the Call Stack, then the explorer panes load with debug info. 

This occurs for most but not every launch configuration. For simple `debug this file...` type launches it appears to automatically select the top of the stack when a breakpoint is hit. Others it does not select any line in the stack. I'll have to spend some time isolating a simple repeatable case, which I won't be able to get to for a while...

**Comment by weinand** [comment] 2019-02-14 09:19
This issue is most likely a duplicate of #68616.

See my [comment](https://github.com/Microsoft/vscode/issues/68616#issuecomment-463248717) for an explanation what's happening.

In your screencast I see some deemphasized top frames which explain why you are running into this issue.

Do you have an option to turn "deemphasizing top frames" off?

/cc @isidorn

**Comment by pieandcakes** [comment] 2019-02-14 20:35
@weinand We don't do anything to signal that the frames are different. Is there something we should be sending in the protocol that we are not?

**Comment by pieandcakes** [comment] 2019-02-14 20:41
Also based on this [comment](https://github.com/Microsoft/vscode/issues/68616#issuecomment-463277731) should the pointer be on the first available frame in the stack with it marked in green?

**Comment by weinand** [comment] 2019-02-15 10:38
@weinand the first three frames are dimmed because they have no source. No, no you don't need to send anything special here.

Yes, if the first frame with source available is not the top frame, the pointer and the highlight should be green.

@isidorn when fixing #68616 please make sure that this works correctly.

**Comment by sean-mcmanus** [comment] 2019-02-15 20:43
@isidorn If this fix goes into Insiders, I can test our C++ scenario for you if you want.

**Comment by isidorn** [comment] 2019-02-25 12:52
@sean-mcmanus can you please verify this works correctly with latest vscode insiders?
Thank you

**Comment by sean-mcmanus** [comment] 2019-02-25 21:11
@isidorn The call stack is broken. It randomly won't scroll to the correct call stack, even when stepping or hitting breakpoints. For many cases it fails 100% of the time. Stepping is the main random case (50% failure?). I'm not able to observe any fixed behavior. I'm using:

Version: 1.32.0-insider (user setup)
Commit: 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment] 2019-02-26 11:36
Thanks for letting us know. For this we would aslo need the revealTo API which is probably coming for #68627
Reopening

**Comment by isidorn** [comment] 2019-02-26 16:45
@sean-mcmanus I can not reproduce this using the example in https://github.com/Microsoft/vscode/issues/68648
This feels like the same issue as https://github.com/Microsoft/vscode/issues/68627
When you say the call stack is broken you actually mean that the correct stack frame does not get revelead? Or it aslo does not get focussed? Or how exactly broken do you mean?

When this happens do you see some errors in F1 > developer tools > console

**Comment by sean-mcmanus** [comment] 2019-02-26 19:44
@isidorn Yeah, it could be #68627. By broken I mean the call stack that hit the "Paused on Breakpoint" is not scrolled to and it's not highlighted, making it hard to locate when there are 20+ threads. I'll send you an email with more screenshots.

There are no errors in the console.

**Comment by isidorn** [comment] 2019-02-27 11:08
It is alwas great when we have all the data in the issue, so no need for seperate emails.
Since I can not reproduce can you F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/2e7ae88cdd8ceb5f94dfad05b8b0f1e0391f0f18/src/vs/workbench/contrib/debug/electron-browser/callStackView.ts#L242) and investigate what is going on.
Also note that we are looking into #68648 and #68627 so once of those might fix this. In the meantime moving this one to march.

**Comment by sean-mcmanus** [comment] 2019-02-27 21:08
I got a repro and debugged it -- the updateSelectionAndReveal gets hit and the [element] is the correct call stack frame, but for some unknown reason the scroll and highlight fails. I got the exception "Errror: Data tree not not found: Microsoft.VSCode.CPP.Extension.exe!gcc_info::get_system_defaults..." with node "undefined", but I get those exceptions a lot so it could be "by design"? I'm not sure what else to look for when debugging. The repro probability seems higher the 1st time I debug and hit a breakpoint than with later calls.

Screenshot before updateSelectionAndReveal:
![image](https://user-images.githubusercontent.com/19859882/53522551-7473ef00-3a8f-11e9-9260-be578e3268ae.png)
Screenshot after updateSelectionAndReveal (no scrolling occurred):
![image](https://user-images.githubusercontent.com/19859882/53522978-6d99ac00-3a90-11e9-93e5-bceb6a576ab6.png)

I could wait for those other issues to be fixed.

**Comment by isidorn** [comment] 2019-03-01 13:36
@sean-mcmanus thanks for looking into this.
I think this will not get fixed by the other issues.
I plan to investigate this more next week. For than can you please give me a step by step repro so I look on my machine? Please note that I do not know C++, so providing a full simple reproducable repository would be great.

**Comment by lieff** [comment] 2019-03-12 14:27
I have same issue on Linux.

**Comment by isidorn** [comment] 2019-03-15 16:36
@joaomoreno here's another case of data tree node not found. Where I try to reveal something which is not known to the tree.
Smeels like a duplicate of https://github.com/Microsoft/vscode/issues/69950

So I suggest that we first fix that and then double check if this got fixed

**Comment by isidorn** [comment] 2019-03-21 14:38
@sean-mcmanus this should be fixed now. Can you please try it starting from Friday's vscode insiders. If you still see it let us know and we will reopen.

**Closed by isidorn** 2019-03-21 14:38 UTC
Labels: bug, debug

**Comment by alexr00** [comment] 2019-03-28 11:29
Verified because the probably duplicate is verified?

**Comment by isidorn** [comment] 2019-03-28 13:05
Yeah duplicate, removing bug label
