### ISSUE TITLE
API to get the scopes applied to the current position in the document

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7027] opened 2016-05-30 10:22 UTC
I couldn't find anything like this which would have removed the need for parsing some text in my extension.

https://atom.io/docs/api/v1.1.0/ScopeDescriptor

**Comment by warpdesign** [comment] 2016-06-29 09:16
What's the status on this ? I see it has been closed but doesn't seem to be mentionned anywhere else.

**Comment by alexandrudima** [comment] 2016-06-29 11:56
@warpdesign 

#7590 is a duplicate of this issue, so given this issue was created before #7590 I closed #7590 in favor of this one.

**Comment by indiejames** [comment] 2016-07-02 23:19
This would be very useful for my extension as well. I need to be able to get the brackets/parens containing the position while ignoring any brackets/parens inside strings or comments.

**Comment by chrmarti** [comment] 2016-07-05 23:34
👍 This would allow for features that need language specific knowledge, but can do without a full AST with bindings.

**Comment by hoovercj** [comment] 2016-08-12 12:02
This appears to be a duplicate of #580

**Comment by alexandrudima** [comment] 2016-08-15 10:45
Let's track in #580

**Closed by alexandrudima** 2016-08-15 10:45 UTC
Labels: api, duplicate, feature-request, tokenization
