### ISSUE TITLE
Integrated terminal buffer getting stuck

### ISSUE THREAD

**Issue by thiagomajesk** [Microsoft/vscode#46374] opened 2018-03-22 23:31 UTC
- VSCode Version: **1.21.1**
- OS Version: **Windows 10**
- Does this issue occur when all extensions are disabled?: **Yes**

Steps to reproduce: 
1. Use CMD or Powershell as the integrated terminal
3. Type anything on the terminal and the buffer will get stuck

![pm](https://user-images.githubusercontent.com/13930952/37803743-62a3f2f8-2e0f-11e8-82db-8ed4f1b40b95.gif)

**Comment by Tyriar** [comment] 2018-03-23 17:17
That's weird the lines don't seem to be clearing. Can you try closing all Windows and trying to reproduce using these:

```
code --disable-gpu
```

```
code --ignore-gpu-blacklist
```

**Comment by thiagomajesk** [comment] 2018-03-23 22:38
@Tyriar I've tried with both, still freezing

**Comment by Tyriar** [comment] 2018-03-23 23:16
@thiagomajesk by freezing do you mean corrupting? It appears that things are working just some characters are being printed over one another.

**Comment by thiagomajesk** [comment] 2018-03-23 23:37
@Tyriar I'm sorry poor choice of words. The problem is still **exactly** the same as I reported.

**Comment by Tyriar** [comment] 2018-03-27 17:11
I'm a bit stumped on this, I haven't seen any other reports and haven't experienced it myself. The fact that neither of those flags don't work means it's not GPU related.

Could you try with the Insiders build to see if it still happens? https://code.visualstudio.com/insiders

**Comment by thiagomajesk** [comment] 2018-03-27 23:05
@Tyriar I've found the problem by accident while reproducing my config settings to the insider's installation. This config seems to be the root of the problem:

```
 "workbench.colorCustomizations": {
        "terminal.background": "#0000"
    },
```

PS.: I tested other background colors and It seems to be happening only for black. I'm using `#010101` to have the same effect while this isn't fixed.

**Comment by Tyriar** [comment] 2018-03-28 16:42
@thiagomajesk awesome, thanks for finding the root cause. This is the case because `#RGBA` expands to `#RRGGBBAA` and you're setting an alpha value of 0. I think the fix here is to ignore `#RGBA` and `#RRGGBBAA` values.

**Comment by Tyriar** [comment] 2018-03-28 16:44
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1357

**Comment by robMaher84** [comment] 2018-05-09 14:01
@Tyriar I tried the above fix and it does not work for me

**Comment by Tyriar** [comment] 2018-05-11 15:46
@robMaher84 you might be seeing https://github.com/Microsoft/vscode/issues/49438 instead (which is now fixed)

**Comment by Tyriar** [comment] 2018-05-25 17:04
This should be fixed

**Closed by Tyriar** 2018-05-25 17:04 UTC
Labels: bug, integrated-terminal

**Comment by dbaeumer** [comment] 2018-05-31 10:56
Verified that a black background works now.
