### ISSUE TITLE
Support to set different themes against different file extensions

### ISSUE THREAD

**Issue by uyhung** [Microsoft/vscode#21866] opened 2017-03-03 08:42 UTC
Can we please support the ability to set different themes for different file extensions? Reason for that: sometimes a theme is suitable this file extension but not for the others. For example, in my opinion, HTML code looks best in Kimbie Dark theme, but C# code file is highlighted best in Monokai Dimmed theme, so that I want:
- set Monokai Dimmed as the common theme for the whole project
- especially for HTML file, use Kimbie Dark theme

If we can support that, I'm sure it would be one of the key feature make VS Code different with all other IDE such as Atom, Sublime etc.

**Comment by aeschli** [comment] 2017-03-15 15:30
duplicate of #20652

**Closed by aeschli** 2017-03-15 15:30 UTC
