### ISSUE TITLE
Images are always (read only)

### ISSUE THREAD

**Issue by snyderae13** [microsoft/vscode#130929] opened 2021-08-16 18:21 UTC
So I'm fairly new to software dev, and I have started an intro course. For some reason every time a add an image file, it shows that its (read-only) after the name, and when I add it to my webpage, for example, it will not work. I have checked the properties of the images and they are not marked read only when I view them in the file explorer, so I'm not sure what the problem is. I have also made sure that I have been given full control and permissions on my computer, seeing as I am the only user and also that I had bought this new windows laptop sunday, so I'm running out of ideas as to why it is doing this, any suggestions?

**Comment by snyderae13** [comment] 2021-08-16 20:26
![Screenshot (20)](https://user-images.githubusercontent.com/88518615/129625293-823b3356-0e95-4801-a41f-16af33ec5f68.png)

Here's a screenshot for reference

**Comment by lramos15** [comment] 2021-09-01 14:22
The image is marked as read only because you're opening it in a preview which doesn't allow image editing. If you were to open it in an image editor such as https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint you would see that it is not marked readonly. As for why your site isn't working with an image that I'm unaware of as the readonly you're seeing isn't a file modification.

**Comment by mjbvz** [comment] 2021-09-01 22:58
I don't think it's helpful to show `(readonly)` when a  custom editor does not support writing. My proposal is that we only show `(readonly)` if:

- The custom editor supports writing
- And the file resource is readonly

@lramos15  @bpasero Does the sound ok to you?

BTW Here's the relevant code: https://github.com/microsoft/vscode/blob/21887d672ab602c4ab84dd2c2a166fd2509f997a/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L239

**Comment by bpasero** [comment] 2021-09-02 04:04
@mjbvz `readonly` serves as a hint to the user that the editor is readonly and cannot be changed by the user. I am not entirely sure people would be able to tell the difference.

I think https://github.com/microsoft/vscode/issues/130526 is related, cc @misolori

**Comment by mjbvz** [comment] 2021-09-02 17:00
I agree it makes sense for custom editors the support writing, but showing `(readonly)` for every file opened in a readonly custom editor is unnecessary and confusing IMO. It always makes me think that the file on disk is readonly, and also makes the editor title longer than it needs to be because there's no action the user can ever take to make the file not be marked as readonly

We previously did not show `(readonly)` and never saw reports of users being confused as to why they could not save in the image preview

**Comment by bpasero** [comment] 2021-09-03 04:39
@mjbvz understood, but I think this is more an issue of the verbose label than the information it carries, so I would think that https://github.com/microsoft/vscode/issues/130526 resolves this, no?

**Comment by mjbvz** [comment] 2021-09-14 19:33
Ok, I'm going to close this as a duplicate of #130526 then. If we can show readonly in a much less obtrusive way, I agree it makes sense to be consistent

**Closed by mjbvz** 2021-09-14 19:33 UTC
Labels: under-discussion
