### ISSUE TITLE
vsce publish fails due to linting issue

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#10501] opened 2016-08-13 15:15 UTC
- VSCode Version: 1.4
- OS Version: OSX

I have an extension (https://github.com/cfjedimaster/htmlescape-vscode) that I'm trying to publish to the store. It tests fine in Code, but when I vsce publish, I get:

Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: node ./node_modules/vscode/bin/compile

Ok, it would be nice if it told me the error (grin), so I tried running the command directly:

src/extension.ts(112,9): error TS4091: Loop contains block-scoped variable 'editor' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.

So... I have something that works in Code, but isn't allowed by vsce?

**Comment by joaomoreno** [comment] 2016-08-15 10:02
Duplicate of Microsoft/vscode-vsce#111

As for the error itself, vsce just calls `node compile`, so ping @bpasero

**Closed by joaomoreno** 2016-08-15 10:02 UTC
Labels: duplicate
