### ISSUE TITLE
'The name org.freedesktop.secrets was not provided by any.service files' error after logging into Visual Studio Code for settings sync

### ISSUE THREAD

**Issue by SeemXD** [microsoft/vscode#131262] opened 2021-08-20 14:48 UTC
I don't know if this is a bug, but I'm using Visual Studio Code for Raspberry Pi OS. I'm using it on a Raspberry Pi 4 Model B, and I'm having trouble. After installing Visual Studio Code on my Raspberry Pi, I try to log in to sync settings. I log into my Microsoft account and I choose to 'merge' my settings. After that, I get a error saying:

Writing login information to the keychain failed with error 'The name org.freedesktop.secrets was not provided by any.service files'.

In the output panel, I choose 'Microsoft Authentication', and it says:
[Info  - 14:38:49.253] Logging in...
[Info  - 14:38:56.212] Exchanging login code for token
[Info  - 14:38:56.800] Exchanging login code for token success
[Info  - 14:38:56.810] Login successful
[Info  - 14:38:56.811] Token available from cache, expires in 3598993 milliseconds
[Info  - 14:38:56.881] Token available from cache, expires in 3598923 milliseconds
[Info  - 14:38:56.882] Token available from cache, expires in 3598922 milliseconds
[Error  - 14:38:58.534] Setting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files

Does anyone know what's going on? What's the problem?

**Comment by SeemXD** [comment] 2021-08-20 20:39
Hey, just wondering, does anyone know how to fix this?

**Comment by TylerLeonhardt** [comment] 2021-08-23 16:20
Looks like a duplicate of #130640. Installing `gnome-keyring` should get this working for you.

**Closed by TylerLeonhardt** 2021-08-23 16:20 UTC
