### ISSUE TITLE
Git authentication

### ISSUE THREAD

**Issue by PavlovicDzFilip** [Microsoft/vscode#2050] opened 2016-01-15 19:34 UTC
Trying to publish while the repo url contains username will still ask me for username. 
Leaving empty or filling in the username and password will result in authentication fail by remote server.

Example, 
repo url: https://FilipDz@bitbucket.org/FilipDz/baze.git
username: <empty> or FilipDz
password: ******
output:
remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
fatal: Authentication failed for 'https://FilipDz@bitbucket.org/FilipDz/node-baze.git/'

**Comment by joaomoreno** [comment] 2016-01-18 10:04
Duplicate of #1138

**Closed by joaomoreno** 2016-01-18 10:04 UTC
Labels: git
