### ISSUE TITLE
cannot start VSCode when offline

### ISSUE THREAD

**Issue by jdbruner** [Microsoft/vscode#61652] opened 2018-10-23 21:55 UTC
- VSCode Version: 1.28.2
- OS Version: Windows 1809 (x64)

Steps to Reproduce:

1. Turn on airplane mode
2. In a command window, type "code ."  It prints the following and exits:

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

It launches successfully when network connectivity is restored.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-10-23 22:54
Duplicate of #7570

**Closed by mjbvz** 2018-10-23 22:54 UTC
Labels: javascript
