### ISSUE TITLE
[JS coloring] same ‘var’ has different color

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#3442] opened 2016-02-25 06:05 UTC
version: 0.10.8
![image](https://cloud.githubusercontent.com/assets/7921431/13311297/4cde4e78-dbc8-11e5-8116-8ef45b9642b2.png)

after `format code`:
![image](https://cloud.githubusercontent.com/assets/7921431/13311323/8a28f13e-dbc8-11e5-9898-d0fc5187aa43.png)

**Comment by martinwoodward** [comment] 2016-02-25 08:31
You had me worried I was going to have to do some real work for a second there.

**Comment by aeschli** [comment] 2016-02-25 08:36
:-)

duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-02-25 08:36 UTC
