### ISSUE TITLE
search.quickOpen.includeSymbols ==> everything is slow!

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#42509] opened 2018-01-30 16:40 UTC
When `search.quickOpen.includeSymbols` is enabled, even non-symbol results (ie file name results) are slower.  To be more precise, the "recently opened" section shows up immediately, then, after an expected lag the symbols show up.  However, what is not expected is that the matching filenames do not show up until after the symbols show up.  Previously these results displayed immediately.

Problem -- often I'm looking for a particular file and the symbol results are unnecessary -- by waiting for the symbol results, my navigation becomes slower.  However, sometimes I do need a symbol result, so I can't disable this.

I recognize that the display order of the results (from top to bottom) is recents, then symbols, then filenames; nonetheless, I still wish the files would render quickly, then the symbols could fill in (between the recents/filenames) whenever those results became available. 

---

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.23
ActiveFileInStatusBar|Ros|1.0.3
gitignore|cod|0.5.0
githistory|don|0.3.8
gitlens|eam|7.5.7
jsonnet|hep|0.0.15
git-tree-compare|let|1.1.4
Go|luk|0.6.73
python|ms-|0.9.1
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
Ruby|reb|0.16.0
java|red|0.17.0
vscode-open-in-github|sys|1.6.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vscode-proto3|zxh|0.1.2

---

Steps to Reproduce:

1. set `"search.quickOpen.includeSymbols": true` in the settings
2. observe that the file results take a long time to render

Reproduces without extensions: N/A because the symbols come from the extensions

**Comment by roblourens** [comment] 2018-01-30 17:41
/duplicate of https://github.com/Microsoft/vscode/issues/27152

**Closed by roblourens** 2018-01-30 17:41 UTC
Labels: *duplicate, search
