### ISSUE TITLE
Documents opened via FileSystemProvider result in gargage text being displayed

### ISSUE THREAD

**Issue by grork** [Microsoft/vscode#47363] opened 2018-04-06 22:44 UTC
- VSCode Version: 1.23.9
- OS Version: Win10, 10.17133.0

Steps to Reproduce:
1. Open & Run the supplied extension (Sources are ttached)
2. Open Foo.txt in the virtual tree

Does this issue occur when all extensions are disabled?: Yes
[fileSystemProviderBuffer.zip](https://github.com/Microsoft/vscode/files/1885743/fileSystemProviderBuffer.zip)

![corruption](https://user-images.githubusercontent.com/1811056/38447290-4aff55ea-39b1-11e8-9483-0065895c8c08.png)

The buffer returned in my case is 'test', and no more.

**Comment by jrieken** [comment] 2018-04-09 07:40
This is a regression from https://github.com//Microsoft/vscode/commit/98d0b747c2ff33513cb4a1b5b6432b1ac338a958

**Comment by jrieken** [comment] 2018-04-09 07:41
This is now fixed in master.

**Closed by jrieken** 2018-04-09 07:41 UTC
Labels: bug, remote

**Comment by mjbvz** [comment] 2018-04-27 03:50
Tested with memfs file system provider since the linked to example is out of date. Not sure if this covers the original problem or not, but I did not see any gargage text
