### ISSUE TITLE
Latest Insiders build `cannot read property map of undefined`

### ISSUE THREAD

**Issue by juliancoleman** [microsoft/vscode#75353] opened 2019-06-12 16:33 UTC
Upon updating to this morning's release of the Insider's build, most, if not all views are completely inaccessible, resulting in a snackbar notification that reads `Cannot read property 'map' of undefined.`

This occurs when attempting to open the integrated Terminal, viewing the Extensions, attempting to open the workspace settings, clicking the gear icon in the bottom right, and opening the command palette. Possibly a ton of other places.

VSCode is otherwise non-functional

- VSCode Version: 1.36.0-insider
- OS Version: MacOS Mojave (10.14.5)

Steps to Reproduce:

1. Update to latest Insiders release
2. Navigate anywhere

Does this issue occur when all extensions are disabled?: Yes

**Comment by juliancoleman** [comment] 2019-06-12 16:36
Hotkeys themselves also otherwise do not work. Upon running into this issue, I reopened Code using `code-insiders --disable-extensions`, and have not reloaded the window since

**Comment by OmriSama** [comment] 2019-06-12 16:38
Duplicate of #75343

**Comment by shaneholloman** [comment] 2019-06-12 16:38
same problem - on a fresh ubuntu 19.04 machine

**Comment by shaneholloman** [comment] 2019-06-12 16:51
Anyone have a .deb of the previous version. I can't find a release page with changelog for code-insiders. [Snap](https://snapcraft.io/code-insiders) doesn't provide previous versions either: <https://snapcraft.io/code-insiders>

**Comment by OmriSama** [comment] 2019-06-12 16:55
Temporary fix:

```bash
$ sudo apt install code-insiders=1.36.0-1559798873
```

**Comment by juliancoleman** [comment] 2019-06-12 16:57
@OmriSama I'm on MacOS. Don't have access to `apt`

**Comment by shaneholloman** [comment] 2019-06-12 17:02
```bash
shaneholloman@ops:~$ sudo apt install code-insiders=1.36.0-1559798873
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "code-insiders", but there is a snap with that name.
Try "snap install code-insiders"

E: Unable to locate package code-insiders
shaneholloman@ops:~$ 
```

**Comment by juliancoleman** [comment] 2019-06-12 17:06
@shaneholloman have you also tried

```sh
sudo snap install code-insiders --classic
```

**Comment by OmriSama** [comment] 2019-06-12 17:06
> ```shell
> shaneholloman@ops:~$ sudo apt install code-insiders=1.36.0-1559798873
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 
> No apt package "code-insiders", but there is a snap with that name.
> Try "snap install code-insiders"
> 
> E: Unable to locate package code-insiders
> shaneholloman@ops:~$ 
> ```

Make sure you add `https://packages.microsoft.com/repos/vscode stable InRelease` to your apt sources.

https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

**Comment by shaneholloman** [comment] 2019-06-12 17:11
@OmriSama I just updated my [comment](https://github.com/microsoft/vscode/issues/75353#issuecomment-501366074)

`--classic` is failing version `--edge` --beta` and `--classic` are all the same failing version

**Comment by juliancoleman** [comment] 2019-06-12 17:12
@shaneholloman ah, you're right. Hopefully this can be resolved in the next couple hours

**Comment by mjbvz** [comment] 2019-06-12 18:19
Closing as duplicate of #75343

**Closed by mjbvz** 2019-06-12 18:19 UTC
