### ISSUE TITLE
ctrl+w on preview tab will close two tabs

### ISSUE THREAD

**Issue by czastack** [microsoft/vscode#86790] opened 2019-12-12 03:02 UTC
- VSCode Version: 1.40.2
- OS Version: Linux x64 4.15.0-72-generic (Ubuntu 16.04)

Steps to Reproduce:

1. Open a nornal file tab
2. Open a preview tab, such as markdown preview, Jupyter Notebook, image file
3. Press ctrl+w on the preview tab, then the preview tab and anthoter nornal file tab will close togeter
4. If no nornal file tab opened, the whole window will close.
5. If click on the Close button instead of ctrl+w, that is ok

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2019-12-12 18:41
@czastack I'm having trouble reproducing this issue. Just to confirm, this also happens when all extensions are disabled? Do you have any custom keybindings?

**Comment by brycefranzen** [comment] 2019-12-13 18:56
I opened an issue with a similar problem and it was closed as a duplicate, but it added further insight as to how to reproduce this:

Open 3 files. Select the far-right file.
Press cmd+w to close the tab.
Press cmd+w to close the next tab.

Notice the last two open tabs are closes simultaneously. This should only close ONE tab at a time.

This was NOT a bug in the previous version.
This appears to have been introduced in the recent update

Editor Version Information:
version: 1.41.0
commit: 9579eda
Date: 2019-12-11T17:58:38.338Z

Note this happens on ANY tab, NOT only "preview" tabs

**Comment by czastack** [comment] 2019-12-14 03:10
@RMacfarlane Yes. Ｗhen I disable all the extentions and move ~/.config/Code into other name, the isuue also happens. Are you trying to reproduce this issue on linux system?

**Comment by gregzuro** [comment] 2020-01-04 23:15
I see this on mac as well.  It's erratic, though.  Sometimes one tab closes, sometimes two.

**Comment by otafasd** [comment] 2020-02-03 06:36
VSCODE ver: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
OS ver: Ubuntu 18.04.3 LTS (64bit)

+1
In my case, I've never seted any keyboard shortcut.
ctrl +w always close my preivew window and source window 
( If source has any monification, pop up save or not question box )
It's very annoying problem.

**Comment by kaytwo** [comment] 2020-02-17 22:57
I can repro this in 1.42.1 in a clean install on linux.
1. Create a file, add some text, save it as .md
2. ctrl+shift+v to preview: this opens a preview tab
3. ctrl+w while the preview tab has focus
4. BOTH the preview tab and the .md source tab are closed

It appears to consume the ctrl+w twice: if tabs are rearranged (i.e. open a second file, and rearrange the tabs such that the second file is in bewteen the .md and the preview), whichever tab would have gotten focus after the preview was closed gets closed as well; if the preview tab is the only one remaining, the second ghost ctrl+w closes the window.

**Comment by scriptcoded** [comment] 2020-03-20 16:13
I'm experiencing this issue in the stable version, but not in insiders. Has it been fixed?

It's only happening for images, and not for plain-text files.

Stable version:
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

Insiders version:
Version: 1.44.0-insider
Commit: 64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed
Date: 2020-03-20T08:27:32.236Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

**Comment by wdscxsj** [comment] 2020-03-24 10:59
FWIW, after the `Ctrl+W` shortcut for `workbench.action.closeWindow` is deleted, this nagging issue never appears on my machine.

**Closed** 2020-04-17 21:14 UTC
Labels: bug, webview
