### ISSUE TITLE
Visual glitch: close tab button on dnd with shrink text

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#59063] opened 2018-09-20 19:28 UTC
Issue Type: <b>Bug</b>

Settings:
```json
"workbench.editor.tabSizing": "shrink",
```

```json
"tab.activeBackground": "#ff6a0015",
"tab.activeBorder": "#ff8f40",
"tab.activeForeground": "#61676c",
"tab.border": "#424d661a",
"tab.hoverBackground": "#ff6a0020",
"tab.inactiveBackground": "#fafafa",
"tab.inactiveForeground": "#9da2a6",
"tab.unfocusedActiveBorder": "#9da2a6",
"tab.unfocusedActiveForeground": "#9da2a6",
"tab.unfocusedInactiveForeground": "#9da2a6",
```
Trying to dnd tab:
![screenshot 49](https://user-images.githubusercontent.com/9638156/45841885-cfa4f700-bd23-11e8-806e-bde3cda3e2ea.png)

Probably the same is when srarting dnd in default `dark+` theme:
![screenshot 51](https://user-images.githubusercontent.com/9638156/45842046-3f1ae680-bd24-11e8-8351-a03c63235fdc.png)

VS Code version: Code - Insiders 1.28.0-insider (af3614909b837c46a260666cb7baab7a8468a9c8, 2018-09-20T14:09:20.109Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment] 2018-09-21 04:18
@Dari-K do you want to take this? It is possible that this is a regression from some work we did, though I cannot remember something during this milestone.

**Comment by bpasero** [comment] 2018-09-22 06:27
The second issue with the default dark theme is easy to fix, looks like this rule was competing:

```css
.monaco-workbench > .part.editor > .content.dragged-over .editor-group-container.active > .title .tabs-container > .tab.sizing-shrink.dragged-over:not(.active):not(.dragged) > .tab-label::after,
.monaco-workbench > .part.editor > .content.dragged-over .editor-group-container > .title .tabs-container > .tab.sizing-shrink.dragged-over:not(.dragged) > .tab-label::after {
	background: linear-gradient(to left, ${adjustedColorDrag}, transparent) !important;
}
```

Adding a `:not(.active)` to the second rule's `.editor-group-container` fixes it. I am not sure about the other issue when using the rules as outlined in the comment.

**Comment by Dari-K** [comment] 2018-09-28 17:59
I'm actually having trouble reproducing it, I saw it once on Light+ just after I switched to it, but I haven't been able to get it to happen again.

**Comment by bpasero** [comment] 2018-10-01 05:09
Also do not see it anymore, closing.

**Closed by bpasero** 2018-10-01 05:09 UTC
Labels: bug, help wanted, insiders, themes, workbench-tabs

**Comment by usernamehw** [comment] 2018-10-27 23:55
Did you try to reproduce the first bug with the tab theming provided in the issue description?
