### ISSUE TITLE
Can no longer open image files from the git viewlet

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33739] opened 2017-09-03 05:21 UTC
- Add a .png file to a git repo (or rename an existing one so it shows up in the Git viewlet)
- See the untracked PNG in the git viewlet
- Click on it

See `Git: cannot open file:///Users/roblou/code/vscode/resources/linux/code2.png. Detail: File seems to be binary and cannot be opened as text`

Previously, it would open the image.

**Comment by joaomoreno** [comment] 2017-09-04 07:42
#3935

**Comment by bpasero** [comment] 2017-09-05 15:44
This is a regression when the file is untracked and thus new should open like a normal file.

**Comment by roblourens** [comment] 2017-09-05 18:26
Thanks. I thought it had worked recently.

**Comment by joaomoreno** [comment] 2017-09-27 15:26
Dupe of #33850

**Closed by joaomoreno** 2017-09-27 15:26 UTC
Labels: git
