### ISSUE TITLE
Many links in Settings cannot be clicked in the Chinese environment

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#202073] opened 2024-01-09 12:47 UTC
![image](https://github.com/microsoft/vscode/assets/11473889/3754dc56-fede-4762-873c-3310c9a34999)

Reproduction steps:
1. Open https://insiders.vscode.dev/
2. Switch `zh-cn` language.
3. Use `cmd + ,` to call out Settings.
4. Search `showTabs` or any other keyword in this [document](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4123) that begins with `“#`.
5. You will find that many files have non-clickable links. For example, the screenshots are non-clickable links and normal clickable links, respectively.

![Uploading image.png…]()

Version: 1.86.0-insider
Commit: fb769554405bee9be16e21ceb0a496bd29126941
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by yiliang114** [comment] 2024-01-10 06:47
The main reason I think is that Chinese quotation `”“` marks cannot appear.

**Comment by rzhao271** [comment] 2024-05-30 21:28
I finally had some time to take a look and that setting has been fixed now.
However, I'll keep the issue open because I found more incorrect settings.
Thanks for reporting the issue and copying in the Unicode characters!

![Searching with a Chinese quotation mark in the query yields more incorrect results](https://github.com/microsoft/vscode/assets/7199958/e13c6f84-f3bd-4850-9aca-f4bc945f6ed1)

**Comment by rzhao271** [comment] 2024-05-30 21:37
I have just confirmed that searching for "« #" while the language is switched to French also reveals several mishandled settings.

**Comment by rzhao271** [comment] 2024-06-24 16:56
There are fewer mishandled settings, now.
The ones that remain come from built-in extensions rather than core settings.

Verification steps:
1. Switch to the Simplified Chinese language pack.
2. Search `“#` in the Settings editor.
3. Confirm that core settings such as editor.suggest.selectionMode _don't_ show up.

**Closed** 2024-06-24 18:03 UTC
Labels: bug, settings-editor, confirmed
