### ISSUE TITLE
Input bracket with selected word sometimes got weird behavior

### ISSUE THREAD

**Issue by yujinlin0224** [microsoft/vscode#157874] opened 2022-08-11 08:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: Windows 10 Pro (10.0.19044.1826)

Steps to Reproduce:

1. Write some code and save it.
2. Select a word.
3. Call `Developer: Reload Window` command.
4. Repeat input `[` or `{` and undo it, it will be happened randomly.

![bandicam 2022-08-11 15-54-47-366](https://user-images.githubusercontent.com/11353779/184092672-727be056-d938-4e2e-bbf8-37b084b34a01.gif)
In above gif, it do:
1. `return` is already selected
2. Press shift+[ and become `{return{`
3. Press ctrl+z and become `{`
4. Press ctrl+z again and become back to `return`
5. Do step 2 to 4 several times and always get weird behavior
6. Click other text and select `return` again
7. Press shift+[ and become `{return}`, finally normal!

**Comment by hediet** [comment] 2022-08-23 09:26
I don't understand the gif. What do you mean with weird behavior?
Can someone else reproduce?

**Comment by yujinlin0224** [comment] 2022-08-23 09:42
In gif, I believe `{return}` is expected when I select `return` and input `{`, but got `{return{`
Or is it also normal behavior?

**Comment by hediet** [comment] 2022-08-23 09:43
I understand, which language is that?

**Comment by yujinlin0224** [comment] 2022-08-23 09:43
Golang

**Comment by yujinlin0224** [comment] 2022-08-23 09:53
This is my vscode settings and exts: https://gist.github.com/yujinlin0224/ba1c2172c3932fecc1bb212a5f658342
That git is recorded when I disabled all exts.

**Comment by yujinlin0224** [comment] 2022-08-23 10:00
I just found when I switch IME to bopomofo en mode, this behavior happened, and english US IME is normal

https://user-images.githubusercontent.com/11353779/186130473-8520d205-f534-4afc-a38f-2e00019c7b30.mp4

**Comment by Germxu** [comment] 2022-08-28 11:54
In my issue #159290, it is not referred to one specific language, because I tried js、json, even markdown file still so.
It is also not random as this issue, it is consistent with VSCode starts high probability.

**Comment by yujinlin0224** [comment] 2022-08-28 14:27
@Germxu you are right, its not random, I can easily duplicate it in every language when I switch my IME to bopomofo

**Comment by yujinlin0224** [comment] 2022-10-30 15:50
Any update?

**Comment by alexdima** [comment] 2022-10-31 14:03
Duplicate of https://github.com/microsoft/vscode/issues/163115

**Closed by alexdima** 2022-10-31 14:03 UTC
Labels: bug, editor-input-IME

**Comment by yujinlin0224** [comment] 2022-10-31 14:52
@alexdima Confirmed that fixed in #147187, thanks a lot
