### ISSUE TITLE
Multiple instances of conhost.exe, powershell.exe, code.exe

### ISSUE THREAD

**Issue by MJNP** [Microsoft/vscode#60916] opened 2018-10-15 01:29 UTC
Hello,

With the latest update, I experience slowdown on my machine after 10+ minutes of using VSCode. 
Upon checking Task Manager (Process tab) it appears that there are a lot of "conhost.exe", "powershell.exe" and "code.exe" instances and among them, powershell uses 32MB of memory per instance.

Based on observation, these instances are being created as time passes by. It starts with 1 for each and then another 1 comes up and so on... Until such time the memory reaches 90-95% and makes the whole system slow and sometimes unresponsive.

As workaround, I close VSCode app every 10 minutes to free up resources and re-open it again.
Closing it dismisses all of the instances.

I assume VSCode attempts to run something but our network/firewall doesn't allow to do it which leaves these instances don't get terminated/closed properly. Thus, making them an orphan.

- 1.28.1
- Windows 7 64-bit

Steps to Reproduce:

1. Open VSCode
2. open a folder and do coding (as usual)
3. Check Task Manager (after 10 mins or so...)

![image](https://user-images.githubusercontent.com/5753259/46925159-0a692900-d05d-11e8-8290-ffae7bc1ccfc.png)

![image](https://user-images.githubusercontent.com/5753259/46925195-2a98e800-d05d-11e8-8c1f-9fa1f07d24b6.png)

![image](https://user-images.githubusercontent.com/5753259/46925205-3edce500-d05d-11e8-8058-059813f5e5b7.png)

**Comment by egamma** [comment] 2018-10-15 05:14
Duplicate of #60585

**Closed by egamma** 2018-10-15 05:14 UTC
