### ISSUE TITLE
VsCode will not close while trying to re-establish remote connection

### ISSUE THREAD

**Issue by cmbrose** [microsoft/vscode#137468] opened 2021-11-18 19:31 UTC
Does this issue occur when all extensions are disabled?: No, but can't get a remote without the extension :)

```
Version: 1.62.2 (system setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
Steps to Reproduce:

1. Connect to a codespace
2. Wait for it to suspend and vscode enters a trying to reconnect state (which won't succeed as the remote is gone)
3. Attempt to close vscode via the `X` button
4. No response from the `X` button, a lot of modals popping up

![close_vscode](https://user-images.githubusercontent.com/5447118/142484229-048bab6b-55f1-4917-89ea-4d29c89eee6a.gif)

**Comment by cmbrose** [comment] 2021-11-18 19:32
Possibly related to https://github.com/microsoft/vscode/issues/136358

**Comment by roblourens** [comment] 2021-11-18 23:25
Please try updating (.3 released today) and see if it works now

**Comment by cmbrose** [comment] 2021-11-18 23:35
Still mostly repros in 1.62.3, it does actually close when it gets to the error toast, but still goes through a lot of modals in the meantim
![close_vscode2](https://user-images.githubusercontent.com/5447118/142513464-bccd0478-621b-4900-9b42-710fb840c5ea.gif)
e:

**Comment by roblourens** [comment] 2021-11-19 00:18
@Tyriar is this related to #136358 or is codespaces blocking exit?

**Comment by vuppalaprasanth** [comment] 2021-11-19 11:23
its stays in the reconnecting loop! 
Is there a possibility that we can downgrade to 1.62.2 ? 
Thanks!

**Comment by Tyriar** [comment] 2021-11-19 13:50
@chrmarti @aeschli any ideas? The fix for the candidate was pretty straightforward; just swallow any errors that come about from the terminal shutting down. So I doubt this is related to the terminal.

**Comment by jkeech** [comment] 2021-11-19 19:01
I looked at the window logs when this happens, and it looks like it might still be a terminal veto issue? I'm on 1.62.3.

```
[2021-11-19 10:49:54.466] [renderer1] [error] {"isTrusted":true}
[2021-11-19 10:49:54.466] [renderer1] [info] [remote-connection][Management   ][a1114…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-11-19 10:49:54.466] [renderer1] [info] [remote-connection][Management   ][a1114…][reconnect] resolving connection...
[2021-11-19 10:49:54.477] [renderer1] [info] [remote-connection][ExtensionHost][cd6ec…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2021-11-19 10:49:54.478] [renderer1] [error] {"isTrusted":true}
[2021-11-19 10:49:54.478] [renderer1] [info] [remote-connection][ExtensionHost][cd6ec…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-11-19 10:49:54.478] [renderer1] [info] [remote-connection][ExtensionHost][cd6ec…][reconnect] resolving connection...
[2021-11-19 10:58:51.557] [renderer1] [warning] [lifecycle] onBeforeShutdown is taking a long time, pending operations: veto.terminal
[2021-11-19 10:58:54.865] [renderer1] [warning] [lifecycle] onBeforeShutdown is taking a long time, pending operations: veto.terminal
[2021-11-19 10:58:59.350] [renderer1] [warning] [lifecycle] onBeforeShutdown is taking a long time, pending operations: veto.terminal
[2021-11-19 10:59:03.798] [renderer1] [warning] [lifecycle] onBeforeShutdown is taking a long time, pending operations: veto.terminal
```

**Comment by jkeech** [comment] 2021-11-19 23:37
From what I can tell, it looks like the terminal veto check is hanging rather than throwing, so the try/catch solution might not be fully helping if it's not getting that far.

**Comment by Tyriar** [comment] 2021-11-22 19:35
Looking into it now. The warning seems to show after 5 seconds:

https://github.com/Microsoft/vscode/blob/0413d4a596931d8b3634e76382109adc94e8a81a/src/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.ts#L101-L103

**Comment by Tyriar** [comment] 2021-11-22 19:39
I think the root cause is the message to the persist the terminals to the remote side is going out but never getting a reply since the Codespace is suspended.

**Comment by Tyriar** [comment] 2021-11-22 19:47
Mostly seems to reproduce with a test resolver window and killing the server.

**Comment by Tyriar** [comment] 2021-11-22 20:04
Apparently https://github.com/microsoft/vscode/commit/5af09003bc2339612703e7f5bb1a97d97136ac07 never made it to the `main` branch which fixes my test resolver repro, but the issue says that it repro's in both 1.62.2 and 1.62.3 so it must be a different problem. Will keep looking.

**Comment by alexdima** [comment] 2021-11-22 20:25
@Tyriar All RPC calls done to the remote side will simply be queued up when the window is disconnected. These RPC calls will not throw an error as long as there is not a permanent connection error. That is how our reconnection is implemented, it happens transparently to the RPC proxy users. 

The state of the connection can be spied on using:
```
const connection = this.remoteAgentService.getConnection();
if (connection) {
	this._register(connection.onDidStateChange((e) => { console.log(e); }));
}
```

My personal suggestion would be to never include awaited RPC calls in the veto or shutdown path, because veto and shutdown should not take arbitrary time. It is possible that an RPC call takes up to 3 hrs until reconnection gives up.

**Comment by Tyriar** [comment] 2021-11-22 20:31
@alexdima thanks for the info, do you know if there an easy way to reproduce this case out of sources?

**Comment by Tyriar** [comment] 2021-11-22 20:35
> My personal suggestion would be to never include awaited RPC calls in the veto or shutdown path, because veto and shutdown should not take arbitrary time.

This is how the process revive stuff works in the terminal, it's disabled in web because of this limitation. I don't think persisting the terminal contents constantly is really an option due to the amount of changes that happen in the terminal. We could also do it similar to hot exit where it gets debounced, but that's a lot of disk IO for every command run in the terminal when it works pretty well now.

**Comment by alexdima** [comment] 2021-11-22 20:44
> do you know if there an easy way to reproduce this case out of sources?

I'm sorry, I don't quite know how to reproduce this specific case. From the OP:

> 1. Connect to a codespace
> 2. Wait for it to suspend and vscode enters a trying to reconnect state (which won't succeed as the remote is gone)

What I would expect here is that the Codespaces resolver would observe that the codespace is suspended and would either wake it up or throw a permanent reconnection error which would end our reconnection loop.

---

To simulate this from source, I think source changes would need to be done to the test resolver.  Maybe [this](https://github.com/microsoft/vscode/blob/cce62293cd2da6fa91bec93d74fec15029571085/extensions/vscode-test-resolver/src/extension.ts#L98) child process can be killed after a setTimeout of 5s and maybe the `doResolve` method can then proceed to always return the previous value it returned. But I am not 100% sure if this behavior would match the Codespaces resolver. The best would be to repro this with the Codespaces resolver and take a look at the window logs to see what it returns from its `resolve` call.

**Comment by Tyriar** [comment] 2021-11-22 23:02
I pushed a fix to allow waiting a maximum of 2 seconds for the persistence, this should only ever be hit on very high latency connections or when the remote is reconnecting like in this issue.

**Closed** 2021-11-22 23:01 UTC
Labels: bug, important, terminal

**Comment by alexr00** [comment] 2021-12-02 15:17
I'm not sure if I hit the exact cases described here, but I was able to get out of the codespace by using the x while a dialog was showing.
