### ISSUE TITLE
The Terminal

### ISSUE THREAD

**Issue by bharatsinghtanwar** [microsoft/vscode#74869] opened 2019-06-05 04:54 UTC
Issue Type: <b>Bug</b>

My terminal is not working. It shows " The terminal process command 'C:\msys64\usr\bin\bash.exe --login' failed to launch (exit code: 2)".

Please tell me how to fix it.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.10
python|ms-|2019.5.18426
cpptools|ms-|0.23.1

</details>

**Comment by Tyriar** [comment] 2019-06-05 13:29
This means the command quotes exited immediately or the path you're running doesn't exist. Closing as duplicate of https://github.com/microsoft/vscode/issues/72650 which aims to improve the error messaging.

**Closed by Tyriar** 2019-06-05 13:29 UTC
Labels: integrated-terminal
