### ISSUE TITLE
Broken font icons in terminal

### ISSUE THREAD

**Issue by pacifi5t** [microsoft/vscode#148857] opened 2022-05-05 23:43 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: Arch Linux x86_64 & macOS 12

I'm using powerlevel10k theme for my zsh shell. Up until now everything was fine. My MacBook has the same configuration (oh-my-zsh plugin manager, powerlevel10k theme, MesloLGS NF font) and after update the problem appeared.

How it was (1.66)
![image](https://user-images.githubusercontent.com/57317100/167093294-d3d8871d-64a8-46c2-83df-1b46171ef42a.png)

How it is now (1.67)
![image](https://user-images.githubusercontent.com/57317100/167093348-80ac3a36-bd5a-4f40-8251-1b157bc78064.png)

**Comment by NNCT2904** [comment] 2022-05-06 05:29
I believe that I have the same issue, I'm using p10k and zsh, my font is Caskaydia nerd font (not mono, the one with double-width icons). Before the update, it rendered fine. After the update, the icons got chopped in half.

Screenshot for the current vscode terminal:
![Screenshot-20220506151537-1127x196](https://user-images.githubusercontent.com/44821915/167072248-2a73b758-3856-4370-9953-532c78d2ea45.png)

This screenshot is from gnome-terminal since I cannot rollback vscode version, but this is how the vscode terminal used to be:
![image](https://user-images.githubusercontent.com/44821915/167072652-3a4ef5e8-1818-41d8-9e50-39a6b0ad4aa0.png)

**Comment by meganrogge** [comment] 2022-05-06 05:48
Have already fixed this upstream in xterm.js I believe. Will be fixed in insiders shortly when we update that

**Comment by albertosantini** [comment] 2022-05-06 05:59
Dupolicate https://github.com/microsoft/vscode/issues/146168?

**Comment by albertosantini** [comment] 2022-05-06 06:00
@meganrogge Ah ok... thanks

**Comment by fiechr** [comment] 2022-05-06 07:55
> Duplicate #146168?

I don't think so. This is not about colors but about the symbols being cut off.
Also, I've set `"terminal.integrated.minimumContrastRatio": 1`, which seems to be the fix for the other issue, and my icons are still cut off.

**Comment by pacifi5t** [comment] 2022-05-06 08:06
> I believe that I have the same issue, I'm using p10k and zsh, my font is Caskaydia nerd font (not mono, the one with double-width icons). Before the update, it rendered fine. After the update, the icons got chopped in half.
> 
> Screenshot for the current vscode terminal: ![Screenshot-20220506151537-1127x196](https://user-images.githubusercontent.com/44821915/167072248-2a73b758-3856-4370-9953-532c78d2ea45.png)
> 
> This screenshot is from gnome-terminal since I cannot rollback vscode version, but this is how the vscode terminal used to be: ![image](https://user-images.githubusercontent.com/44821915/167072652-3a4ef5e8-1818-41d8-9e50-39a6b0ad4aa0.png)

Actually, you can downgrade the VS Code if you install it from Chaotic AUR.

**Comment by pacifi5t** [comment] 2022-05-06 08:08
> Have already fixed this upstream in xterm.js I believe. Will be fixed in insiders shortly when we update that

Wow, that's great, thank you. Then I'll close the issue when the fix will arrive.

**Comment by fpiem** [comment] 2022-05-06 09:54
Same issue here on PopOS 20.04, using ZSH with PowerLevel10k and a NerdFont-patched version of SFMono.

**Comment by fiechr** [comment] 2022-05-06 10:04
> Have already fixed this upstream in xterm.js I believe. Will be fixed in insiders shortly when we update that

Any way we can confirm this by testing?

**Comment by meganrogge** [comment] 2022-05-06 16:08
@fiechr I am confident this will fix it. It would be helpful if you could verify that it's fixed once this issue gets the label `insiders-released` in a few days.

**Comment by mrcaidev** [comment] 2022-05-13 10:35
Same issue on Manjaro / zsh / p10k

![image](https://user-images.githubusercontent.com/78269445/168266269-6995f9f2-e7a4-42f0-a5fd-5dc099f21d23.png)

**Comment by yn4v4s** [comment] 2022-05-13 15:58
Just updated Insiders v1.68 to 113287ccc3be52dc3409d451a9b3416d133dca1a and the issue isn't yet fixed

**Comment by meganrogge** [comment] 2022-05-13 16:43
Not seeing any cut off icons in insider's - please include a screenshot and the name of the font you're using if you are
![Screen Shot 2022-05-13 at 9 42 38 AM](https://user-images.githubusercontent.com/29464607/168329256-c7d7d2cf-37c2-45d1-8908-6005a19d2c04.png)

**Comment by yn4v4s** [comment] 2022-05-13 17:20
@meganrogge 

![image](https://user-images.githubusercontent.com/35275827/168335390-409027c7-e94b-4bf6-b281-5ef9eba643be.png)

**Comment by ViaxCo** [comment] 2022-05-13 17:26
I used "MesloLGS NF" font with the same issue on insiders as well.

P.S: `"terminal.integrated.gpuAcceleration": "canvas"`: this setting seems to fix it temporarily until a fix is issued.

**Comment by meganrogge** [comment] 2022-05-13 18:31
Yes I can reproduce the problem by changing `gpuAcceleration`

**Comment by fiechr** [comment] 2022-05-13 18:49
> P.S: `"terminal.integrated.gpuAcceleration": "canvas"`: this setting seems to fix it temporarily until a fix is issued.

I'm still on the stable (non-insider) build and can confirm, that the issue goes away when setting GPU acceleration to "canvas".  Somewhere, I read this before, but it was pointing to another settings option that doesn't seem to exist anymore.

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.6-1-MANJARO
```

**Comment by Tyriar** [comment] 2022-05-23 18:38
This doesn't seem to happen on Windows
![image](https://user-images.githubusercontent.com/2193314/169885119-0b208d93-6572-412e-a3a9-d4c2b1e4fe85.png)

**Comment by Tyriar** [comment] 2022-05-23 18:51
Actually this appears to be fixed already, can repro in 1.67 but not in insiders

**Closed by Tyriar** 2022-05-23 18:51 UTC
Labels: bug, upstream, upstream-issue-linked, terminal-rendering

**Comment by Tyriar** [comment] 2022-05-23 19:04
To clarify my above comment, this is fixed in the webgl renderer but not the DOM renderer (tracked in https://github.com/xtermjs/xterm.js/issues/3807#issuecomment-1135035551). If you moved to `canvas` I recommend switching back to `auto` or `on` when this lands in stable as you'll get much better performance.

**Comment by Phong-Ly-CL** [comment] 2022-05-31 02:51
![image](https://user-images.githubusercontent.com/98797692/171082573-89194ad8-2418-4cc2-bf8d-09ac2a006b81.png)
![image](https://user-images.githubusercontent.com/98797692/171082937-69004ad9-3e7b-4be3-80b3-5af54e778e21.png)

This problem seems to be reproduced on ver. 1.67.2
Can anyone comfirm this please? Thank you so much.
Temporarily moved to `canvas` until fix

**Comment by Tyriar** [comment] 2022-05-31 13:14
@Phong-Ly-CL it's fixed in 1.68 which isn't out yet.

**Comment by Phong-Ly-CL** [comment] 2022-06-01 01:02
> 

Thank you for your reply.
I see, since this issue didn't appear in 1.67.1 so I thought it was fixed.

**Comment by fiechr** [comment] 2022-06-11 07:37
For me this issue is fixed now.

`terminal.integrated.gpuAcceleration` is set to "`auto`" and symbols in the terminal are still looking fine.

```
Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:49:57.055Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.9-1-MANJARO
```
