### ISSUE TITLE
Bug: Battery drain even when app off due to Shan.code-settings-sync extension

### ISSUE THREAD

**Issue by kpeluso** [microsoft/vscode#147707] opened 2022-04-19 16:29 UTC
Issue Type: <b>Performance Issue</b>

on brand new Apple 2022 Macbook Pro 14" M1

1. download vscode (universal mac version)
2. watch battery drain

I had >90% power 2hr ago and now I'm down to 46%, and I was using chrome but my mac tells me that vscode was using more power than anything else EVEN THOUGH I HAD YET TO TURN IT ON TODAY

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17100641/164051465-36d97e01-debb-42a6-9f4b-dfcc730d8497.png">

Please look at this insane amount of battery usage for an app that's turned off:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/17100641/164051790-c5d8df77-8ea9-4d73-9c26-aece34839917.png">

**Update**: It looks like there was a Code Helper (Renderer) (50803) task running from vscode that was using half of my CPU. I stopped that process. I opened vscode up again and it seems to be using a reasonable amount of CPU now (both that task and the Electron/other vscode-related tasks in total, that is). so maybe a background task just doesn't quit and slowly snowballs over time.

**Update**: Looks like everything is going fine now! So it must be due to some task that gets started right after install or first startup. Below, you can see my usage with vscode _off_ and _before_ I turned that task off, then I charged my comp, then I reopened vscode to do things and it's consuming expected amount of power.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/17100641/164106396-064f0493-5266-4bd3-ae25-2ca7593fc8d5.png">

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 8|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 8fff6564-6630-48c8-8217-d84848fc2769|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   26	   213	 47499	code main
    0	    66	 47506	   gpu-process
    0	    33	 47508	   utility-network-service
    0	   279	 47509	   window (Get Started)
    1	   164	 47532	   shared-process
    3	    66	 47535	     ptyHost
    1	    49	 47560	     fileWatcher
    0	     0	 47605	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	    98	 47534	   extensionHost
    0	    98	 47591	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaac:30438847

```

</details>

**Comment by himanshu-satija** [comment] 2022-05-04 09:24
I was worried after observing excessive battery drain on my brand new Macbook M1 pro(2021). It turn out I had the same issue. There was a Code Helper (Renderer) process that was running even after quitting vscode app, and consuming significant CPU time.

**Comment by madhusudhand** [comment] 2022-07-11 11:18
Recently I switched to 14" M1 Pro (2021) and VS code seems to be consuming significant amount of battery.
Where as previously my M1 Air (2021) it was working good.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1935113/178252939-3acf3e22-6b8f-4838-923d-ed4f44d2795c.png">

**Comment by asjadsaboor** [comment] 2022-07-19 19:12
I am facing same issue, any solution?

**Comment by madhusudhand** [comment] 2022-07-20 06:28
Kill the process `Code Helper (Renderer)` in activity monitor. After that it works fine for me.

Related ticket: https://github.com/microsoft/vscode/issues/101555

**Comment by makssie** [comment] 2022-07-20 12:33
Same problem here, it is very boring to kill every time the Code Helper (renderer) process. Is there any permanent solution?

**Comment by CreeperMaster719** [comment] 2022-07-22 01:08
I really hope there is one soon... My 16 inch MBP 2021 went from full to 10% in under two hours. It hit 198 in the energy tab of activity monitor, and it hit 432% cpu usage... Crazy bug!

**Comment by Vrq** [comment] 2022-08-02 16:26
Same thing here. Any chance for a response from @jrieken, @bpasero, @mjbvz or @Tyriar?

It looks like a high severity issue for Apple Silicon users.

**Comment by theJasonFan** [comment] 2022-08-06 17:21
Here's a related ticket #148226 that is still open. With many others reporting the same issue.

**Comment by brownsugar** [comment] 2022-08-22 06:06
Same problem for months...

It doesn't ALWAYS drain the battery but OFTEN.
Sometimes I restarts VSCode the problem will be resolved but after a few hours or another day, the problem could happened again.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/2935980/185850131-9c688766-133d-4787-b35b-d9fe8b1883d1.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/2935980/185849365-67db9971-e40b-408c-b635-714d2aff4c36.png">

```
Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

**Comment by rtfmanual** [comment] 2022-09-08 11:38
Same on a MBP 16 (late 2021)

**Comment by paragkatoch** [comment] 2022-09-30 07:57
I am on MacOS 13.0 and I am also experiencing high battery consumption of vscode. I believe it started when I updated vscode to the latest version

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/61873006/193220842-dd7e4bbc-163e-4fc1-9eb4-f47cab3eaec9.png">

<img width="478" alt="image" src="https://user-images.githubusercontent.com/61873006/193220938-22dd9bd8-a281-4578-b163-0cd84e8aca35.png">

**Comment by jrieken** [comment] 2022-10-04 07:03
VS Code runs a bunch of processes for various tasks (extensions, terminal, renderer, etc) and it looks like one of those is stuck and fails to terminate. 

Folks that experience this: please run `ps -p <PID> | pbcopy`. It will copy details of the bad process, esp. its command line arguments, to the clipboard. Please paste the details here. It will allow us to tell what kind of process this is. Thanks and Happy Coding

**Comment by Ashley-King** [comment] 2022-10-07 21:14
PID TTY           TIME CMD
88583 ??       134:20.61 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --inspect-port=0 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork --type=extensionHost --skipWorkspaceStorageLock

**Comment by jrieken** [comment] 2022-10-13 09:40
Thank @Ashley-King The `--type=extensionHost` part indicates the extension host process

**Comment by alexdima** [comment] 2022-10-24 14:40
@Ashley-King Do you always observe high CPU usage in the extension host process? Does this reproduce when starting VS Code with extensions disabled by killing all instances and launching `code --disable-extensions`?

---

VS Code shouldn't consume CPU when idle and I understand the frustration here, but to tackle this we need to find out which VS Code process consumes CPU when idle. So far @Ashley-King has pointed to the extension host process, which is the process where extensions execute. Please let us know if you encounter this and what process that is.

**Comment by Mariownyou** [comment] 2022-10-28 11:48
any fixes yet?

**Comment by emmaroland32** [comment] 2022-11-01 13:17
I am currently experiencing the same issue, my macbook pro M1 16GB 14inches went  from 100% to 15% in under 2 hours. This really sucks.

**Comment by Vrq** [comment] 2022-11-01 20:11
In my case VSCode keeps creating Code Helper processees which use >100% CPU.

One as example:
  PID TTY           TIME CMD
59556 ??         0:58.16 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Users/<username>/.vscode/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/y9/364wzmw17r782vhyjhbkjmxm0000gn/T/vscode-typescript501/08ec308f00f2298edab3/tscancellation-c7b293c21554046072e1.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc

**Comment by Ashley-King** [comment] 2022-11-02 21:49
@alexdima thanks for continuing to look into this. CPU usage decreases to normal levels when I launch with code --disable-extensions. 

I have disabled as many extensions as I can. But even with the ones I have left, which are necessary for productivity, I'm still getting > 100% CPU usage. If I have a chance to test this by disabling extensions one at a time I'll report back.

**Comment by Ashley-King** [comment] 2022-11-03 00:28
@alexdima well...I updated vscode with the october release and removed the old settings sync extension I had. That seemed to get rid of the issue for me. 🙄

**Comment by yotov** [comment] 2022-11-05 16:07
A great tool to find a bad extension - https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
In my case, the problem was settings sync, and there are many complains for high CPU in their issues.

**Comment by emmaroland32** [comment] 2022-11-17 13:53
> A great tool to find a bad extension - https://code.visualstudio.com/blogs/2021/02/16/extension-bisect In my case, the problem was settings sync, and there are many complains for high CPU in their issues.

Thanks for this, the vscode decreases to normal usage level once i uninstalled Settings Sync. Hate to let it go but its not worth my mac running for 1 hour at full charge. My battery health is already at 95% for a 3 months old Macbook Pro M1 14"

**Comment by alexepperly** [comment] 2022-11-19 02:20
This is still an issue on my 2022 MBP 14. I have tried killing all the related processes and disabling all of my extensions. I am probably going to have to restrict VSC usage to my PC.  

The amount of energy this is using -- even while turned off -- is single-handedly killing my battery.

Such a shame.  Great program in every other way.  I am so surprised there hasn't been a global fix for this yet.

**Comment by tamuratak** [comment] 2022-11-19 03:38
The extension [Shan.code-settings-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) should be marked deprecated at the marketplace at least for macOS as I suggested:

- https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-4061935

The cause is that the extension depends on the old version of `chokidar` which includes an incompatible native module.  The extension has been abandoned for years. We  cannot expect any updates to fix the issue. We had better consider adding some tweaks to VS Code.
Otherwise, users would keep encountering the same issue.

- https://github.com/shanalikhan/code-settings-sync/blob/eb332ba5e8180680e613e94be89119119c5638d1/package.json#L189

**Comment by dotesfera** [comment] 2022-11-25 21:01
Having the exact same issue. Is there a solution?

**Comment by Andrew3005** [comment] 2022-12-09 20:40
I have the same issue, just new mac

**Comment by AbdulrasheedAdediran** [comment] 2022-12-10 12:08
I had this issue for days until I uninstalled the settings sync extension.

**Comment by cyango** [comment] 2022-12-10 15:32
Can confirm, it was settings sync extension. Aleluia!

**Comment by isidorn** [comment] 2022-12-12 10:48
Thanks for opening this issue. We have reached out to Shan the author of the Settings Sync extension and he told us he would fix the issue in the next month.

My personal recommendation is to use the VS Code built-in Settings Sync functionality instead. More details here: https://code.visualstudio.com/docs/editor/settings-sync

**Comment by timvahlbrock** [comment] 2022-12-12 11:02
I don't have this extension installed, but still got the issue. However I'm developing my own extension, which uses a separate process as well, so I suspect the problem is caused there in my case. What I'm trying to say with this: Maybe just fixing the issue in the settings sync extension isn't enough, as this might occur again in other extensions.

**Comment by alexdima** [comment] 2022-12-12 13:04
@timvahlbrock You're right. Any extension can end up executing a lot of code and consuming a lot of CPU. If you find such a situation, please reach out to the extension author. You can use extension bisect to narrow down the problematic extension.

**Comment by timvahlbrock** [comment] 2022-12-12 15:21
I think that trying to find the draining extension using extension bisect could be really hard or impossible. As reported earlier by several users, the extension can still drain power, even if VSCode was terminated. So the reload of extension bisect wouldn't shut down the draining process. And if the process is shut down manually, the extension must start draining power again immediately (or pretty quick), for extension bisect to be useful. Or am I missing something? It would be nice, if it would somehow be possible, to check which extension started the draining process.

**Comment by timvahlbrock** [comment] 2022-12-12 16:34
> This is also possible, by using extension profiling: `F1 > Developer: Show Running Extensions` and pressing the `Start Extension Host Profile` button.

Oh okay, I wasn't aware of that. 👍

**Comment by miyurusankalpa** [comment] 2022-12-28 19:10
I am on a New M1 Air, with a clean install (no extensions) and just noticed this issue. It was making the laptop really hot while draining the battery. I was using the latest version(1.74.2) too.

This is issue also seems to be side tracked(by @alexdima) as a extension bug when the original report did not even have any extension installed. The original bug is still there.

**Comment by alexdima** [comment] 2022-12-30 16:23
Given the comments in this issue and the extra information we received, I chose to change this issue into a tracking item for the 100% CPU used by the `Shan.code-settings-sync` extension.

@miyurusankalpa If you are not using the `Shan.code-settings-sync` extension and experiencing high CPU usage from one of VS Code's processes, please take a look at https://github.com/microsoft/vscode/wiki/Performance-Issues#consuming-cpu and create a new issue pointing out the process which causes high CPU usage, your platform (universal or arm), etc and we can try to troubleshoot together what's going on. You can also link here to the new issue. Many thanks!

**Comment by isidorn** [comment] 2023-01-05 11:26
The extension author of the Settings Sync extension agreed that we mark it as deprecated until they fix the performance issue.
There is no follow up work on our side, thus I am closing this issue as done.
Everyone that is using the settings sync extension can use the built-in settings sync functionality instead https://code.visualstudio.com/docs/editor/settings-sync

![Image](https://user-images.githubusercontent.com/1926584/210769268-f41373db-1e43-4c4f-89f7-f005d50a128b.png)

**Closed by isidorn** 2023-01-05 11:26 UTC
Labels: freeze-slow-crash-leak, extension-host
