### ISSUE TITLE
ES6 template strings declared at the end of a ternary operator are incorrectly parsed

### ISSUE THREAD

**Issue by jabooth** [Microsoft/vscode#6337] opened 2016-05-13 08:45 UTC
- VSCode Version: 1.1.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Create a new text file `test.js`
2. Set the content to the following:
```js
let x = true ? '' : `${1}`
console.log('still part of the template!')
```
VS Code fails to parse the opening `` ` `` of the template string at the end of the ternary operator correctly. It therefore sees the final `` ` `` as an opening tick, and interprets the rest of the file as a template string:

<img width="356" alt="screenshot 2016-05-13 09 39 32" src="https://cloud.githubusercontent.com/assets/1312873/15242549/aedfa33e-18ee-11e6-9c3b-6ddf3a019bfb.png">

As a workaround you can wrap the failure case in parenthesis:
 ```js
let x = true ? '' : (`${1}`)
console.log('still part of the template!')
```
<img width="365" alt="screenshot 2016-05-13 09 42 34" src="https://cloud.githubusercontent.com/assets/1312873/15242603/0bf29504-18ef-11e6-822b-fb97977930d0.png">

**Comment by aeschli** [comment] 2016-05-13 18:47
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/141

**Closed by aeschli** 2016-05-13 18:47 UTC
