### ISSUE TITLE
Wrong indentation guides

### ISSUE THREAD

**Issue by stefanos82** [microsoft/vscode#82368] opened 2019-10-11 15:21 UTC
- VSCode Version: 1.39.1
- OS Version: Linux x64 5.2.0-3-amd64

As you can see, it highlights the previous matching bracket's indentation guides.

![image](https://user-images.githubusercontent.com/1777466/66663611-b420cd00-ec53-11e9-808c-c50322779eb9.png)

![image](https://user-images.githubusercontent.com/1777466/66663703-da466d00-ec53-11e9-9578-20ed52856913.png)

**Comment by alexandrudima** [comment] 2019-10-11 22:40
Duplicate of #49342

**Closed by alexandrudima** 2019-10-11 22:40 UTC
Labels: new release
