### ISSUE TITLE
Unable to open default `tasks.json` with a custom profile when using `Open User Tasks`

### ISSUE THREAD

**Issue by eFKaey** [microsoft/vscode#230769] opened 2024-10-08 06:59 UTC
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

### Steps to Reproduce:

1. Have a `tasks.json` file in the default profile.
2. Open a VSCode window with a custom profile. (Edit: Profile source of tasks is `Default`.)
3. Run `Tasks: Open User Tasks` from the command palette.

### Result:

Nothing.

### Remark:

If there is no default `tasks.json` file, running `Tasks: Open User Tasks` from the command palette will create one in the custom profile folder, not in the default profile folder.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.82GB (4.95GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/extern/src_xe10 --crash-reporter-id ed0f9ed2-513a-46cc-ae8e-47d791b72b33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
fastcompare|Dav|1.2.1
gitlens|eam|15.6.0
gc-excelviewer|Gra|4.2.62
todo-tree|Gru|0.0.226
highlight-cpp-parameters|mbl|0.7.2
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
powershell|ms-|2024.2.2
vscode-xml|red|0.27.1
text-marker|ryu|1.11.0
hexdiff|sj0|1.2.240121
vscode-fileutils|sle|3.10.3
rewrap|stk|1.16.3
code-spell-checker|str|3.0.1
code-spell-checker-german|str|2.3.2
cmantic|tde|0.9.0
pdf|tom|1.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by sandy081** [comment] 2024-10-25 12:51
@meganrogge Please investigate if it is an issue with tasks adopting to profiles

**Comment by meganrogge** [comment] 2024-10-25 15:46
What's the file path of your `tasks.json` file in the profile?

I believe this is not a bug, but a misunderstanding of how user vs workspace tasks work.

**Comment by eFKaey** [comment] 2024-10-25 16:42
> What's the file path of your `tasks.json` file in the profile?

`C:\Users\%USERNAME%\AppData\Roaming\Code\User\tasks.json`

> I believe this is not a bug, but a misunderstanding of how user vs workspace tasks work.

Maybe. I assumed it works like keybindings.  
Both files are located in `C:\Users\%USERNAME%\AppData\Roaming\Code\User`.  
In the profile settings under `Source`, both are configured as `Default`.

Can I use these keybindings in all profiles? Yes.  
Can I use these tasks in all profiles? Yes.  

Can I open `keybindings.json` from the default and other profiles? Yes.  
Can I open `tasks.json` from the default and other profiles? No, only from the default profile.

**Comment by meganrogge** [comment] 2024-10-25 17:14
I can reproduce the bug - if I create a profile and specify that I want tasks to come from some other profile (like the default one), when I switch to the created profile and open user tasks, they don't open. 

![Image](https://github.com/user-attachments/assets/fee9f2c2-c84a-4c6f-992a-d3be7b5aea2f)

**Comment by meganrogge** [comment] 2024-10-25 17:14
However, if I create user tasks in that new profile, then I can open them.

**Comment by meganrogge** [comment] 2024-10-25 17:15
@sandy081 where does settings sync pull the tasks from?

**Comment by meganrogge** [comment] 2024-12-08 16:29
Closing this as i've gotten no more reports of the issue

**Closed by meganrogge** 2024-12-08 16:29 UTC
