### ISSUE TITLE
TeX does not render in Markdown inside html elements

### ISSUE THREAD

**Issue by dannydarvish** [microsoft/vscode#130149] opened 2020-09-28 19:56 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open the following notebook: https://physics.bu.edu/~pankajm/ML-Notebooks/NB1_CII-ML_is_difficult.ipynb

2. Observe that the TeX in the undordered list in the second cell does not render. In Jupyter Notebook, it renders.

## Actual behavior

The TeX in the undordered list in the second cell does not render. In Jupyter Notebook, it renders.

## Expected behavior

The TeX in the undordered list in the second cell should render.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.9.111407
-   **VS Code version:** 1.49.2
-   **Setting python.jediEnabled:** true
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:** macOS 10.13.6
-   **Virtual environment:** N/A

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by mjbvz** [comment] 2021-08-05 05:54
The root cause appears to be that the notebook uses html `<ul>` and `<li>` elements that contain equations. 

If you use a normal markdown list, this works as expected:

```
- In the first case, the process that generates the underlying data is in the model class we are using to make predictions. For polynomial regression, this means that the functions $f(x_i)$ are themselves polynomials.
- In the second case, our data lies outside our model class. In the case of polynomial regression, this could correspond to the case where the $f(x_i)$ is a 10-th order polynomial but $g_\alpha(x;\theta_\alpha)$ are polynomials of order 1 or 3.
```

![Screen Shot 2021-08-04 at 10 54 11 PM](https://user-images.githubusercontent.com/12821956/128298539-3b0b4746-bcd7-4cdf-8258-b2a71a7573f5.png)


Updating title and marking as a feature request

**Closed** 2021-10-06 02:29 UTC
Labels: help wanted, feature-request, notebook-markdown
