### ISSUE TITLE
Select all selected words incorrectly

### ISSUE THREAD

**Issue by jerryzhou80** [Microsoft/vscode#16352] opened 2016-12-02 02:03 UTC
- VSCode Version: 1.6.0
- OS Version:  win 7

Steps to Reproduce:
1. Open VSCode

2. Input below content:
aeeb
ced

3. select 'e'

4. press Ctrl + F2, then has 2 cursors. But this case it should be 3 cursors.

**Comment by alexandrudima** [comment] 2017-05-21 10:38
Duplicate of #6661

**Closed by alexandrudima** 2017-05-21 10:38 UTC
Labels: bug, editor, editor-multicursor
