### ISSUE TITLE
First key press ignored

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25101] opened 2017-04-20 22:29 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (5590786c2f676ca2aee12b16cd01b4e0ac621984, 2017-04-20T08:32:34.121Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. New Untitled File
2. Press: a
3. Select: a
4. Press: a
5. Expected: Selection disappears and cursor is to the right of a.
6. Actual: Selection stays.

This only happens when overwriting with the same character.

**Comment by alexandrudima** [comment] 2017-05-03 21:24
Duplicate of #16520

**Closed by alexandrudima** 2017-05-03 21:24 UTC
Labels: bug, editor
