### ISSUE TITLE
[Linux] Open file or Open folder creates dialog behind active window

### ISSUE THREAD

**Issue by kathenas** [microsoft/vscode#146422] opened 2022-03-31 11:38 UTC
Native dialogs **Open file** or **Open folder** opening behind main window on RHEL 8/EL 8 clones.

This has only happened after updating to 1.66.0.

Desktop Environment: gnome.

https://user-images.githubusercontent.com/68813857/161046219-18409912-09af-4f77-ba08-f7b33a203fd5.mp4

**Comment by EvgeniyMakhmudov** [comment] 2022-04-07 19:13
The same problem on Linux Mint with Mate env after update to 1.66. I hope that will be fixed in 1.66.1 but it is not.

**Comment by jherico** [comment] 2022-04-14 20:32
Same behavior on Ubuntu 22.04 pre-release, but I was also seeing it on 20.04 before I upgraded yesterday.

```
Visual Studio Code

"Open File" is ready
```

and then I can get to the dialog by clicking on the toast or by using the switch-window shortcut key.  

Code About dialog output
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.15.0-25-generic
```

**Comment by bradym** [comment] 2022-04-15 15:35
Seeing the same issue, I  didn't find this ticket so I filed #147400 which I have now closed. Mentioning here in case there's anything useful on that ticket when this one gets worked on.

**Comment by carneeki** [comment] 2022-04-16 21:59
Also happening to me on Arch Linux with GNOME 42 under Wayland:

Help -> About as follows:

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.3-arch1-1
```

**Comment by gregersn** [comment] 2022-04-20 23:05
Same issue, Ubuntu 21.10, Cinnamon VM. 

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic
```

**Comment by 70m4c** [comment] 2022-04-27 08:15
Same issue on Arch Linux running VSCodium on Cinnamon.

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-13T00:16:29.523Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.4-zen1-1-zen
```

**Comment by kozhukalov** [comment] 2022-04-27 10:10
Same for me
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.4-100.fc34.x86_64
```

**Comment by KollegeX** [comment] 2022-04-28 08:00
Here as well
```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-04-02T14:00:30.308Z
Electron: 17.3.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.32-1-MANJARO
```

**Comment by embeddedt** [comment] 2022-04-30 13:01
Same issue using Arch and KDE Plasma.

```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-04-02T14:00:30.308Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.4-arch1-1

Operating System: Arch Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.4-arch1-1 (64-bit)
Graphics Platform: X11
```

**Comment by cmarincia** [comment] 2022-05-12 21:44
Same issue here using Solus Linux 4.1
```
Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-06T09:53:29+10:00
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.37-214.current
```

**Comment by wc7086** [comment] 2022-05-15 16:22
Same issue using Arch and KDE Plasma.
```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-10T21:35:59.370Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.7-arch1-1
```

**Comment by AlbanMinassian** [comment] 2022-05-19 09:22
Same problem  ubuntu 20 or 22:

code (v1.67.1)
first open dialog: right place
second et other open dialog: always behind application

sudo apt ugrade (code 1.67.1 to 1.67.2)
code
first open dialog: right place
second et other open dialog: always behind application

**Comment by SethBashamDev** [comment] 2022-05-22 22:12
Currently have this issue with Save As. Running Fedora 36 Workstation. 

VS Code installed via Microsoft repo not Snap/FlatPak

**Comment by eksperimental** [comment] 2022-05-27 08:12
> Currently have this issue with Save As. Running Fedora 36 Workstation.
> 
> VS Code installed via Microsoft repo not Snap/FlatPak

Seems like a temporary solution

**Comment by spectreseven1138** [comment] 2022-05-27 08:21
> > Currently have this issue with Save As. Running Fedora 36 Workstation.
> > VS Code installed via Microsoft repo not Snap/FlatPak
> 
> Seems like a temporary solution

I think they were just mentioning the setup they experienced the issue with, not suggesting it as a solution.

**Comment by eksperimental** [comment] 2022-05-27 08:22
> > > Currently have this issue with Save As. Running Fedora 36 Workstation.
> > > VS Code installed via Microsoft repo not Snap/FlatPak
> > 
> > 
> > Seems like a temporary solution
> 
> I think they were just mentioning the setup they experienced the issue with, not suggesting it as a solution.

That's why I say "temporary".

**Comment by spectreseven1138** [comment] 2022-05-27 08:27
> That's why I say "temporary".

I mean that it's not a solution at all, just that they experienced the bug using the MS repo version.

**Comment by eksperimental** [comment] 2022-05-27 08:29
> > That's why I say "temporary".
> 
> I mean that it's not a solution at all, just that they experienced the bug using the MS repo version.

It is a temporary solution for those who need to use the editor today.

**Comment by kathenas** [comment] 2022-05-27 11:56
> > > That's why I say "temporary".
> > 
> > 
> > I mean that it's not a solution at all, just that they experienced the bug using the MS repo version.
> 
> It is a temporary solution for those who need to use the editor today.

@SethBashamDev is stating they have the issue and that the version they are using is installed from the MS RPM repo. There is no mention of a temporary solution. Please refrain from adding noise to this bug report.

**Comment by eksperimental** [comment] 2022-05-27 14:19
> @SethBashamDev is stating they have the issue and that the version they are using is installed from the MS RPM repo. There is no mention of a temporary solution. Please refrain from adding noise to this bug report.

For those with this issue (like myself) or this issue https://github.com/microsoft/vscode/issues/150119 and not being able to use this app, INSTALLING FROM SNAP STORE allows you to use it for the time being.

**Comment by kathenas** [comment] 2022-05-27 17:37
> > @SethBashamDev is stating they have the issue and that the version they are using is installed from the MS RPM repo. There is no mention of a temporary solution. Please refrain from adding noise to this bug report.
> 
> I will rephrase myself then.
> 
> For those with this issue (like myself) or this issue #150119 and not being able to use this app, [INSTALLING FROM SNAP STORE](https://snapcraft.io/code) allows you to circumvent the issue for the time being.

On RHEL 8/AlmaLinux 8 I can happily use the app in this state. It is just a pain and the regression needs to be fixed.

For many using a snap or flatpak is not an option and it is certainly not a workaround. Some users are in firms and/or environments that requires software come from a validated trusted sources.

Yes, I agree that for some a snap or flatpak maybe an option, but for me and others it is no option at all.

**Comment by jflambert** [comment] 2022-06-15 18:12
It's a problem on Ubuntu 18.04

```
Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:49:57.055Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 4.15.0-187-generic
```

**Comment by mrtnlrsn** [comment] 2022-06-16 09:25
Also on Ubuntu 20.04

**But even worse:**
It no longer defaults to the same directory as the current file being edited. It shows recent files, and there is no easy way of getting into the directory of the current file!

**Comment by jflambert** [comment] 2022-06-16 12:49
> Also on Ubuntu 20.04
> 
> **But even worse:** It no longer defaults to the same directory as the current file being edited. It shows recent files, and there is no easy way of getting into the directory of the current file!

Yes, same behaviour. So aggravating

**Comment by xabolcs** [comment] 2022-06-16 13:19
> Also on Ubuntu 20.04
> 
> **But even worse:** It no longer defaults to the same directory as the current file being edited. It shows recent files, and there is no easy way of getting into the directory of the current file!

@mrtnlrsn, thats a different story: #151668, fixed and the fix is included in the ["May 2022 Recovery 1"](https://github.com/microsoft/vscode/milestone/191?closed=1) milestone.

**Comment by jay-brown** [comment] 2022-06-26 21:45
Same problem (file dialog is behind vscode window) on Mint:
OS Info:
```
    OS: Linux Mint 19.3 Tricia x86_64 
    DE: MATE 
    WM: Metacity (Marco) 
```
VS Code Info:
```
    Version: 1.68.1
    Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    Date: 2022-06-15T02:58:26.441Z
    Electron: 17.4.7
    Chromium: 98.0.4758.141
    Node.js: 16.13.0
    V8: 9.8.177.13-electron.0
    OS: Linux x64 5.11.16-051116-generic
```

**Comment by tristan957** [comment] 2022-06-27 14:27
This is because of the PR that made Electron use the XDG Desktop Portal. Unfortunately, the PR was merged without this issue and others like it being discovered. I have looked at the Chromium code to try to fix this, but it just isn't possible given everything I currently know. I have suggested to upstream that they might consider reverting the PR. I know @deepak1556 has done more work upstream near this code.

As a workaround, you could try `GTK_USE_PORTAL=0 code ...`. Will probably fix your issues.

**Comment by kathenas** [comment] 2022-06-27 18:40
On Mon, 2022-06-27 at 10:16 -0700, Tristan Partin wrote:
> This is because of the PR that made Electron use the XDG Desktop Portal. Unfortunately, the PR
> was merged without this issue and others like it being discovered. I have looked at the Chromium
> code to try to fix this, but it just isn't possible given everything I currently know. I have
> suggested to upstream that they might consider reverting the PR. I know @deepak1556 has done more
> work upstream near this code.
> As a workaround, you could try GTK_USE_PORTAL=0 code .... Will probably fix your issues.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

Suggested workaround does not work.

Regards

Phil

-- 
*** Playing the game for the games own sake. ***


Associations:

* Debian Maintainer (DM)
* Fedora/EPEL Maintainer.
* Contributor member of the AlmaLinux foundation.

WWW: https://kathenas.org

Buy Me a Coffee: https://www.buymeacoffee.com/kathenasorg

Twitter: @kathenasorg

Instagram: @kathenasorg

IRC: kathenas

GPG: 724AA9B52F024C8B

**Comment by RealZendor** [comment] 2022-06-28 17:47
Same for me:
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-121-generic

**Comment by DigiOhhh** [comment] 2022-06-30 10:49
Same here on KDE:

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-16T08:22:04.269Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.18.6-1-MANJARO
```

**Comment by deepak1556** [comment] 2022-07-01 15:09
Upstream issue https://github.com/electron/electron/issues/32857

**Comment by Awkwardcodergirl** [comment] 2022-07-04 19:50
Has anyone found a solution for this problem yet?

**Comment by JulienBERNU** [comment] 2022-07-06 06:57
Had the same issue... until I restarted VSCode. Now it's behaving. Worth a try... :)

**Comment by kathenas** [comment] 2022-07-06 07:06
On Tue, 2022-07-05 at 23:58 -0700, JulienBERNU wrote:
> Had the same issue... until I restarted VSCode. Now it's behaving. Worth a try... :)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

If you stated install source, platform etc. this comment may have some use. But the issue remains
and your comment is not helpful.

Regards

Phil

-- 
*** Playing the game for the games own sake. ***


Associations:

* Debian Maintainer (DM)
* Fedora/EPEL Maintainer.
* Contributor member of the AlmaLinux foundation.

WWW: https://kathenas.org

Buy Me a Coffee: https://www.buymeacoffee.com/kathenasorg

Twitter: @kathenasorg

Instagram: @kathenasorg

IRC: kathenas

GPG: 724AA9B52F024C8B

**Comment by ecm75** [comment] 2022-07-07 06:45
This above mentioned workaround works for me on Debian 11 not using Wayland:
`GTK_USE_PORTAL=0 code`

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.10.0-14-amd64
```

**Comment by ogrand** [comment] 2022-07-13 07:12
Same issue with latest code release (open dialog is behind vscode window).

Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:28:29.328Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.4.0-122-generic

Workaround `GTK_USE_PORTAL=0` code doesn't fix.

Regards

**Comment by phamphu232** [comment] 2022-07-13 07:40
Same issue

Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:28:29.328Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.4.0-121-generic

**Comment by Rayv1** [comment] 2022-07-13 08:18
same

Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:28:29.328Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.13.0-52-generic snap

**Comment by deepak1556** [comment] 2022-07-13 09:04
Thanks everyone for the inputs, at this time we know the root cause of the issue in upstream. I am going to lock this issue to avoid some noise. I will reopen the issue once a fix has been made.

**Closed** 2024-05-20 15:31 UTC
Labels: bug, upstream, linux, electron, confirmed, dialogs, upstream-issue-linked, native-file-dialog, electron-17-update
