### ISSUE TITLE
Html code formatting not working for angular Projects

### ISSUE THREAD

**Issue by abhi2kollam** [Microsoft/vscode#19812] opened 2017-02-03 09:21 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (723b20093d2f525e84cdf94a52f7695d1d539273, 2017-02-03T07:11:59.289Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|gitlens|eamodio|1.4.3|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.42|
|HTMLHint|mkaufman|0.3.3|
|debugger-for-chrome|msjsdiag|2.5.1|
|better-merge|pprice|0.5.1|
|theme-obsidian|rprouse|0.2.0|
|ayu|teabyii|0.2.1|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment] 2017-02-03 15:00
Please always a code example when filing an issue.

Note that we use [jsbeautify](http://jsbeautifier.org/) to format. Please also try your example there and maybe directly file the issue there.

**Comment by HookyQR** [comment] 2017-02-10 23:02
There's a bug in jsbeautify currently. This may be a duplicate of https://github.com/Microsoft/vscode/issues/18739

**Comment by aeschli** [comment] 2017-02-20 15:39
closing due to lack of additional information

**Closed by aeschli** 2017-02-20 15:39 UTC
Labels: needs more info
