### ISSUE TITLE
Removal of the Santa Hat and kowtowing to SJWs

### ISSUE THREAD

**Issue by JohnMH** [microsoft/vscode#87314] opened 2019-12-19 04:21 UTC
The removal of the santa hat, and kowtowing to a single SJW, is incredibly offensive to me. Please rectify this as soon as possible.

**Comment by tweakimp** [comment] 2019-12-19 07:42
Without a hat the settings icon may get cold

**Comment by egamma** [comment] 2019-12-19 08:02
duplicate of #87291

**Closed by egamma** 2019-12-19 08:02 UTC

**Comment by egamma** [comment] 2019-12-19 19:19
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
