### ISSUE TITLE
UI glitch in minimap and terminal panels when word wrapping

### ISSUE THREAD

**Issue by pingala98** [microsoft/vscode#99536] opened 2020-06-06 20:33 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
While typing in editor, when i reach the end of line from where minimap starts, the UI starts glitching out and editor becomes unusable untill i delete the extra characters from the line that caused this. 

Here is a video of the bug 
[https://youtu.be/A6Fom2hEgjI](url)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.56GB (0.66GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.0.1
bracket-pair-colorizer-2|Coe|0.1.4
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
better-cpp-syntax|jef|1.14.31

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment] 2020-06-08 15:33
@pingala98 it looks like that video is marked as private on YouTube, we can't see it.

**Comment by pingala98** [comment] 2020-06-08 22:46
@connor4312 
sorry for the trouble, I must have did it by mistake in hurry,
I corrected it now.
https://youtu.be/A6Fom2hEgjI 
Please help me resolve this issue, sometimes it becomes impossible to work.

**Comment by pingala98** [comment] 2020-06-09 14:40
@connor4312  @RMacfarlane 
Update: Just found out that the glitch is happening only when I am using the Victor mono font, as soon as i change the font family to consolas or droid sans, the issue immediately stops and starts again as soon as i revert font back to Victor mono,
Also turning font ligatures on or off has no effect.
I am happy that atleast my editor is usable again (with any other font) ,but i would really be thankful if anyone can help me identify this issue as I really love victor mono font.

**Comment by connor4312** [comment] 2021-07-07 20:00
Reassigning to you Peng since I think you own the minimap now?

**Comment by rebornix** [comment] 2021-07-07 23:43
I have this to the original owner

**Comment by alexdima** [comment] 2021-07-08 13:40
I think this is a duplicate of https://github.com/microsoft/vscode/issues/113877

@pingala98 Can you please check if this reproduces with the latest VS Code?

**Closed** 2021-07-16 11:25 UTC
Labels: editor-minimap, needs more info
