### ISSUE TITLE
Integrated terminal error: bash: __git_ps1: command not found

### ISSUE THREAD

**Issue by doovers** [Microsoft/vscode#9674] opened 2016-07-25 02:43 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

When using a custom bash prompt for git, the first message in VS Code integrated terminal on show is:

`bash: __git_ps1: command not found`

Steps to Reproduce:

1. Modify bash prompt (from .bash_profile):

```
# Change command prompt
source ~/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
export PS1="$green\u$purple\$(__git_ps1)$blue \W $ $reset"
```

2. Open integrated terminal in VS Code

Note: Config works fine in Terminal application.

**Comment by kieferrm** [comment] 2016-07-25 21:44
Duplicate of #9484.

**Closed by kieferrm** 2016-07-25 21:44 UTC
