### ISSUE TITLE
Keypair settings misaligned with dictionary settings when using Copy to Settings

### ISSUE THREAD

**Issue by jamisonbryant** [Microsoft/vscode#17195] opened 2016-12-14 21:25 UTC
- VSCode Version: 1.8.0
- OS Version: Win10 64-bit Bld. 1607

Steps to Reproduce:

1. Open settings.json in default Settings window
2. Click the pencil icon next to a dictionary-style setting (e.g. 'files.associations') and click "Copy to Settings"
3. Click the pencil icon next to a keypair-style setting (e.g. `editor.lineHeight`) and click "Copy to Settings"

Result: 

Observe dictionary-style setting is aligned correctly (1 indentation), but has a newline, a comma, and another newline after it which forces the keypair-style setting down. See attached for a screenshot.

![bug](https://cloud.githubusercontent.com/assets/6774110/21201693/f4edcb7e-c219-11e6-958e-545645881ded.PNG)

**Comment by sandy081** [comment] 2017-01-24 10:29
@aeschli FYI

**Comment by sandy081** [comment] 2017-01-25 14:59
@aeschli json edits are not returning correct positions in this case. Hence moving this to you.

**Comment by aeschli** [comment] 2017-01-25 16:34
duplicate of #19136

**Closed by aeschli** 2017-01-25 16:34 UTC
Labels: bug, config, json, workbench
