### ISSUE TITLE
gitbash clear command is jumps to top but keeps the previus log/text  in same plase 

### ISSUE THREAD

**Issue by Lev09** [Microsoft/vscode#51633] opened 2018-06-11 18:25 UTC
Issue Type: <b>Bug</b>

Open the terminal in VS code run any command ( for example `ls`) and then pres `ctrl+l` or just type `clear` command and press enter and you will see the issue.

This issue is an old one. And I guess it was solved once before. But now it came back again.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz (4 x 2667)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (1.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
Angular2|joh|6.1.1

</details>

**Comment by RMacfarlane** [comment] 2018-06-11 19:50
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/27219

**Closed** 2018-06-11 19:50 UTC
Labels: *duplicate, new release
