### ISSUE TITLE
Don't try to content assist in comments

### ISSUE THREAD

**Issue by pspi** [Microsoft/vscode#1657] opened 2015-12-26 06:18 UTC
Don't try to content assist / perform intellisense when writing a comment. Really really annoying, when every other word pops up suggestions. Don't want it.

Dupe of #538 that got closed but not fixed really though.

**Comment by felixfbecker** [comment] 2015-12-28 22:28
Imo word suggestions are often quite helpful. For example when I make a comment like "this is later called by ..." and VS Code automatically suggests the long method name as I type.

**Comment by Kroc** [comment] 2015-12-29 21:56
@fleixfbecker yes, but 'code' within comments should be escaped with backticks, the intellisense whilst writing comments is really slowing down my typing and interfering with expected spc/tab when writing prose.

**Comment by bpasero** [comment] 2016-01-13 06:31
I am hitting an issue in comments that is ugly. My intent is to write this inside a TS/JS file:

```
/**
 * this is set.
 */
```

However `set` is a snippet and typing "." completes it so I end up with:

```
/**
 * this is 
 public set .(v : string) {
     this. = v;
 }
 
 */
```

Typing undo here I end up with:
```
/** */
```

@alexandrudima fyi about the undo behaviour here which is not very helpful.

**Comment by jrieken** [comment] 2016-01-13 08:05
We should not add snippets inside comment, tho I am unsure if we know that when inserting them.

**Comment by alexandrudima** [comment] 2016-01-13 15:01
@bpasero Pushed fix for undo behavior in 2cdf977a3404f3e3a5d9600b0c50deb3255b2d71

**Comment by bpasero** [comment] 2016-01-13 15:04
@alexandrudima nice thanks!

**Comment by Kroc** [comment] 2016-01-13 18:11
A set of 'scopes' / 'escapes' could be provided for comments, primarily that triple slash enables a 'line of code' within a comment, where intellisense could be available.

**Comment by jrieken** [comment] 2016-01-13 18:39
yeah, #580 is about scopes et al - we don't have it yet in the ext host

**Comment by alexandrudima** [comment] 2016-01-14 09:44
@jrieken Should we try to make the IntelliSense request pass in the scopes besides the position?

**Comment by jrieken** [comment] 2016-01-14 09:50
That makes it related to #1172 which is about adding more contextual information to the provider. Two other options that I favour is either something like `TextDocument.scopesAtPosition/Offset` or the extend the document selector to know about scopes `{ language: 'javascript', scopes: 'comment.doc' }`. The latter might be easiest to implement since it's evaluated on the main side

**Comment by andy-hanson** [comment] 2016-01-18 02:20
It would also be nice to not have a leading `*` automatically added when I add a new line to a comment.

**Comment by jrieken** [comment] 2016-01-18 08:51
@andy-hanson For jsdoc that should actually happen.

**Comment by felixfbecker** [comment] 2016-01-18 09:47
@jrieken It does not for PHPDoc and I believe also not for JavaDoc.

**Comment by jrieken** [comment] 2016-01-18 10:39
for sure not

**Comment by andy-hanson** [comment] 2016-01-18 17:21
1) I am using typescript, but not jsdoc. Since jsdoc won't run on typescript files anyway, it's a strange assumption that any `/**` comments must be jsdoc.
2) [typedoc](https://github.com/sebastian-lenz/typedoc) does not require leading stars.
3) I tested on some js files and it looks like jsdoc does not require leading stars either.
In general, I would like it to always be possible to get the editor to stop interfering, regardless of the tools or coding styles it thinks I should be using.

**Comment by roslanr18** [comment] 2016-01-18 17:26
Pada 19/01/2016 1:22 PG, "Andy Hanson" <notifications@github.com> menulis:

**Comment by hoovercj** [comment] 2016-01-23 11:57
From https://github.com/Microsoft/vscode/issues/580#issuecomment-159401140
> From @egamma on November 2, 2015 8:16
> Exposing the scope names in the API is on the backlog, but will not make it into the November update.

I would like `TextDocument.scopesAtPosition/Offset`

**Comment by roslanr18** [comment] 2016-02-04 09:38
You have been invited to the following event.

Title: Samsung
When: Thu Feb 4, 2016 10am - 11am GMT (no daylight saving)
Where: http://opensource.samsung.com
Calendar: rnordin95@gmail.com
Who:
     * roslan nordin - organizer
     * licensing@fsf.org
     * Gmail Team
     * prime@gmail.com
     * lino lin
     * Microsoft/vscode
     * ezam fareeza
     * Triton Lite
     * candycrushjelly.techhelp@king.com
     * vivian hu
     * spw-play-support@cervomedia.com
     * vscode@noreply.github.com
     * hrydgard+ppsspp@gmail.com
     * support@npmjs.com
     * nizam ezam
     * Roslan Nordin
     *  
reply@reply.github.com
     * Candy Crush Jelly Saga
     * Inc.
     * Marketing
     * raimi nordin
     * kadz kadir
     * KingRoot Studio
     * Rasminah Rakib

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=MW84b3MwMGlrMjU1bzNsNTV1b3VpY2ZuZjggcmVwbHkrMDBmMzJmMTE0ZmE2NjJmMGFlMmQ2NTZmNjAxNWZjYzIwZjAzOWQyNzg3Y2NjNDU4OTJjZjAwMDAwMDAxMTJiNGUxNDg5MmExNjljZTA3NjJiZjNmQHJlcGx5LmdpdGh1Yi5jb20&tok=MTkjcm5vcmRpbjk1QGdtYWlsLmNvbTM2YzA4MGIwNGEzYWQ0OWYwOTBhMjIyMDUzMzk4Y2RiYjQwNDc5N2I&ctz=UTC&hl=en

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to modify your RSVP  
response. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by jrieken** [comment] 2016-03-08 09:03
I think the real issue is that 24x7 IntelliSense shouldn't be active in all cases, esp when a 'smart' completion provider is there but didn't produce a result. In such cases the textual provider should only become active if explicitly invoked (Cmd+Space).

**Comment by egamma** [comment] 2016-03-08 09:15
:1: and this should be the default behaviour. 

We could still provide a setting 'always include textual completions' for users that like the current behaviour.

**Comment by jrieken** [comment] 2016-03-08 09:20
agreed

**Comment by jrieken** [comment] 2016-03-08 16:46
An alternative idea is to configure what <kbd>Enter</kbd> should do when completions are shown. We could add an option to commit on <kbd>Tab</kbd> only (ala `editor.acceptSuggestionOnEnter`). That's helps us to know what the user actually wants. In addition, we can add <kbd>Shift+Enter</kbd> to accept a completion and <kbd>Shift+Tab</kbd> to insert a `tab`

**Comment by csholmq** [comment] 2016-03-08 17:26
@jrieken :+1: on the `editor.acceptSuggestionOnEnter: false`.

**Comment by lukehoban** [comment] 2016-03-09 22:17
@jrieken So was the decision not to do this:

>> I think the real issue is that 24x7 IntelliSense shouldn't be active in all cases, esp when a 'smart' completion provider is there but didn't produce a result. In such cases the textual provider should only become active if explicitly invoked (Cmd+Space).

> :+1: and this should be the default behaviour. We could still provide a setting 'always include textual completions' for users that like the current behaviour.

For the Go plugin, I know there are a number of users who would have liked that default behaviour (not showing completion lists with textual completion and snippets automatically when the Go completion provider has returned no results, only on cmd+space).

The `editor.acceptSuggestionOnEnter` approach seems like it won't fix the default experience, and turning this option on will degrade the experience in normal completion outside of the undesirable locations like comments and strings.  

It seems like the ultimate fix here is addressing a different problem than the core concern.  The suggestion you proposed in the quote above seems to fix the core concern.

**Comment by jrieken** [comment] 2016-03-11 16:28
We made this decision basically because we don't to step onto the toes of those that actually like textual completions everywhere. Also it wouldn't have helped in cases in which only textual completions are available, esp in markdown files. Last, it's aligned with what other editors do, so with muscle memory of those users.

**Comment by alexandrudima** [comment] 2016-03-21 16:39
Verified setting `editor.acceptSuggestionOnEnter` to `false` no longer makes `Enter` and accept key for suggestions

**Comment by natefinch** [comment] 2016-05-23 20:44
FWIW, I also find this to be super annoying.  I've never seen another editor suggest random words from the file when typing comments.  It's distracting and unhelpful.  I'm fine with having to set a value to turn it off, but please give me that ability... and I mean turning off suggestions in comments entirely.

I'm not sure why this issue is marked as closed... unless I'm missing something, there's been no proposed workaround for the problem of showing suggestions, only for turning off autocomplete on enter, which is more of a symptom than the actual disease.

**Comment by alexturek** [comment] 2016-11-04 21:24
Searching for `turn off suggestion in text files vscode` I get to https://github.com/Microsoft/vscode/issues/3137 which is closed as a dupe of https://github.com/Microsoft/vscode/issues/2496 which is closed as a dupe of this issue which... doesn't help me disable suggestions in a specific file format.

Has anyone actually solved this, or did that issue get conflated with the ability to completely disable intellisense? [The docs suggest it's still not possible to disable by file format.](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense)

**Comment by jimfoye** [comment] 2016-11-18 21:52
When hit <Enter> to start a new line in a comment, the editor often "helpfully" completes my sentence with something I don't want. I don't think I could put it any better than @natefinch did above. This is really annoying!

**Comment by jtzeng** [comment] 2016-12-01 05:15
Ah that's a shame. Guess I just have to disable it manually. :(

**Comment by DarrenCook** [comment] 2017-01-26 09:03
Could someone, who knows the code, suggest where a patch would go, and how it might work?

I guess we need a boolean function that will ask `isCursorInsideAComment()`, or `getCursorContext()` might be better, so we can distinguish between single-line comments, block comments, and javadoc comments (start with `/**`).

And then use that function (*) at the point where it decides if to show intellisense suggestions or not. I think the answer to the latter might be related to https://github.com/Microsoft/vscode/pull/1172  ?
*: based on a user setting, of course, so people who want to write code inside comments still can.

**Comment by JesperTreetop** [comment] 2017-01-31 14:40
Per the other comments, please reopen this or allow one of the "dupe" issues to be opened for the benefit of those of us who *don't want random word autocomplete when editing text files*. Since editing Markdown files is intended use to the extent that it gets special features like live preview, I think this deserves not to be clumped together with disabling autocomplete within comments (which is probably still a good idea).

**Comment by jrieken** [comment] 2017-01-31 15:32
FYI - Issue #719 is about refining the `editor.wordBasedSuggestion` further. So people that never want to see word-based suggestion can use `"editor.wordBasedSuggestions": false` already *today* . For those that don't want to see word-based suggestion for certain languages you can say `"[markdown]": { "editor.wordBasedSuggestions": false }` (available in *insiders today* or the January release). For #719  the plan is to extend the boolean-value with something that allows you to say word-based suggestion... 'not in comments' and/or 'not in strings'

**Comment by JesperTreetop** [comment] 2017-01-31 15:37
> For those that don't want to see word-based suggestion for certain languages you can say "[markdown]": { "editor.wordBasedSuggestions": false } (available in insiders today or the January release).

This is spectacular, since it was something that wasn't possible yet earlier in the thread. Awaiting the January release with bated breath. 😄

**Comment by jrieken** [comment] 2017-01-31 15:39
re https://github.com/Microsoft/vscode/issues/1657#issuecomment-276397642: Sorry, I deleted my comment because it contained a link to the wrong issue 🙃 

So, this is what I have suggested in https://github.com/Microsoft/vscode/issues/10819#issuecomment-275633990:

```json
"editor.wordBasedCompletion": true,
"[markdown]": {
  "editor.wordBasedCompletion": false
}
```

**Comment by jrieken** [comment] 2017-01-31 15:41
I have also reopened this issue because it has some many subscriber for the following change: In addition to the plain boolean that `editor.wordBasedCompletion` accepts today I want to extend it to something that allows to say *word base suggestion 'in comment only', 'in string only', 'nowhere'* etc

**Comment by alexturek** [comment] 2017-03-02 16:12
Hey, thank you to whoever added file-type specific editor settings. Now.. can we get all file types, and not just the four that exist? I'd be happy to open a PR if someone could point me to the right area.

I'm not sure why these were the only languages that made the cut :)

<img width="443" alt="screen shot 2017-03-02 at 8 11 48 am" src="https://cloud.githubusercontent.com/assets/175027/23515739/f11f2086-ff1f-11e6-84b4-fae9105aa08a.png">

**Comment by jrieken** [comment] 2017-03-08 09:44
The [additional configuration options](https://github.com/Microsoft/vscode/issues/1657#issuecomment-276398805) for word-based suggestion are now tracked in https://github.com/Microsoft/vscode/issues/9504 and are plan for March. Closing this issue as the remaining work will happen there. Happy Coding!

**Closed by jrieken** 2017-03-08 09:44 UTC
Labels: bug
