### ISSUE TITLE
Powerline fonts look bad in Terminal

### ISSUE THREAD

**Issue by nico-castell** [microsoft/vscode#120371] opened 2021-04-01 19:25 UTC
Issue Type: <b>Bug</b>

The terminal renders powerline characters incorrectly when starting a terminal.

Characters look like this:

![Screenshot](https://user-images.githubusercontent.com/74460331/113344174-1b7a8300-9307-11eb-892e-abb1fc6a962f.png)

**Steps to reproduce:**
1. Open Visual Studio Code
2. Open the integrated terminal

By the way, when you change the terminal font to another font, then back to the previous front, the terminal starts to render correctly, but you need to do this every time you open an integrated terminal.

1. Open terminal
2. Open settings (JSON)
3. Update the `terminal.integrated.fontFamily` setting:
  1. You read: `terminal.integrated.fontFamily = "Hack, monospace"`
  2. Rewrite to: `terminal.integrated.fontFamily = "monospace"`
  3. Save
  4. Rewrite to: `terminal.integrated.fontFamily = "Hack, monospace"`
  5. Save
  6. Terminal renders correctly

This is very similar to issue #120129, and I suspect it's for the same reason: the webgl renderer, which is now the default.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.71GB (0.25GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id e0cd88a6-c143-4203-9298-dc9a627fda3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by Tyriar** [comment] 2021-04-01 22:56
Yep this is a duplicate of that, thanks

/duplicate

**Closed by Tyriar** 2021-04-01 22:56 UTC
Labels: new release
