### ISSUE TITLE
Allow user to pick multiple options from showQuickPick list

### ISSUE THREAD

**Issue by hasit** [Microsoft/vscode#12925] opened 2016-09-28 18:44 UTC
I am making an extension for VSCode where I present the user with a list using `showQuickPick()` like so:

<img width="908" alt="screen shot 2016-09-28 at 11 40 55 am" src="https://cloud.githubusercontent.com/assets/1553055/18927371/75c0a820-8570-11e6-9843-0dc334839170.png">

From what I understand, this way allows user to only pick one item out of the whole list. Is there a way to allow user to pick multiple items? I could not find anything for this on the [vscode namespace API](https://code.visualstudio.com/docs/extensionAPI/vscode-api).

**Comment by jrieken** [comment] 2016-09-29 07:17
dupe of #238

**Closed by jrieken** 2016-09-29 07:17 UTC
Labels: api, feature-request, workbench

**Comment by hasit** [comment] 2016-09-29 07:31
@jrieken thank you. I look forward to an update on this.
