### ISSUE TITLE
JS/Ts language service keeps crashing when opening plain JS files

### ISSUE THREAD

**Issue by gfraser-solink** [microsoft/vscode#178447] opened 2023-03-27 19:13 UTC
Type: <b>Bug</b>

Most files in our projects are TS but opening certain JS files causes the JS/TS language service to keep crashing, causing VS Code to consume signficant battery power consistently. The only way to stop the service from crashing is to restart VS Code and refrain from opening any JS files and only stick to TS files.

VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.24GB free)|
|Process Argv|--crash-reporter-id 7fd2c184-bb1e-4e50-a0f4-fb174bf49e96|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jest-runner|fir|0.4.60
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
pythonb192cf:30669361
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by mosesfawole** [comment] 2023-03-27 19:43
This issue could be caused by a variety of factors, such as outdated extensions, conflicting extensions.
- Update your extensions, You can check for updates by going to the Extensions panel and clicking the "Update All" button.
- Disable conflicting extensions: Try disabling any other extensions that may be conflicting with the TypeScript and JavaScript language service. You can do this by going to the Extensions panel and disabling the extensions one by one until the issue is resolved
-Increase resources: If your machine has limited resources, you can try increasing the resources available to VS Code. You can do this by modifying the "max_memory_restart" and "max_old_space_size" settings in the VS Code settings.json file.

You can try any of these, hopefully it works

**Comment by mjbvz** [comment] 2023-03-27 19:43
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mosesfawole** [comment] 2023-03-27 19:59
Yeah it should reproduce in the insiders build 🤔

**Comment by gfraser-solink** [comment] 2023-03-28 13:46
My extensions are up to date. It's definitely not a system specs or resources issue either. Is there a way to enable verbose logging or something so we can see the reason it's crashing?

**Comment by mjbvz** [comment] 2023-04-04 18:38
@gfraser-solink Did you test in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by gfraser-solink** [comment] 2023-04-04 18:56
I'm not on the insiders build. This is the build I'm on currently and the issue is still occurring. It hasn't been a big enough issue for me to try a different build though since most of my work is in TS and those files work fine.

Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z

**Comment by mjbvz** [comment] 2023-04-04 23:16
Sorry but we really need you to test on insiders with extensions disabled. I'll close this if it's not a big issue

**Closed by mjbvz** 2023-04-04 23:16 UTC
Labels: info-needed
