### ISSUE TITLE
Maximize panel option is missing from (version 1.64)

### ISSUE THREAD

**Issue by tommybernaciak** [microsoft/vscode#142167] opened 2022-02-04 09:06 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: version 1.64
- OS Version:

Steps to Reproduce:

1. Open Terminal
2. Move it to Side Panel

Maximize Panel Size option is missing. it looks like it was removed from Side Panel only, I can still use it in the bottom panel. 

![Screenshot from 2022-02-04 10-00-31](https://user-images.githubusercontent.com/5927665/152501390-013f8d20-203f-4d83-9642-a23bd9481226.png)
![Screenshot from 2022-02-04 10-00-09](https://user-images.githubusercontent.com/5927665/152501392-01f837b9-8cfd-4c76-a736-b3cc5a675f00.png)

**Comment by IllusionMH** [comment] 2022-02-04 11:37
May be duplicate of #141094

**Comment by adam-arold** [comment] 2022-02-04 12:56
@tommybernaciak it never had the close or maximize options. This breaking change was introduced with `1.64.0`. Please close this issue and vote for both #141569 and #141569 .

**Comment by adam-arold** [comment] 2022-02-04 12:57
> I don't think that side panel ever had Close Panel and Maximize buttons.
> 
> Looks like related to #141569

Yea, it is the same issue 👆

**Comment by tommybernaciak** [comment] 2022-02-04 13:00
@adam-arold this is not true. I always worked this way, I opened the terminal on the right and when I wanted to see more and put it on full screen I just clicked Maximize button. It was always there until the recent update.

**Comment by IllusionMH** [comment] 2022-02-04 13:20
@tommybernaciak previously you were able to move Panel to side and it has Maximize button then.
Currently there is difference between Panel (now at the bottom, but could be moved to side previously) and Side Panel (opposite of Action Bar side).
Later never had Close button.

**Comment by superole** [comment] 2022-02-04 13:30
@IllusionMH, what do you mean _never had_? Isn't it brand new?! previously it was one dynamic position panel, now there are two static ones and the newcomer is lacking a very important feature.

**Comment by IllusionMH** [comment] 2022-02-04 13:43
They are treated and controlled as separate entities Panel and new entity Side Panel(Auxilary Panel, or "newcomer" from your message) never had these buttons.
I don't argue that it's big problem that new side panel missing this feature, I just pointing out that there is existing issue that covers this case (if you take comments into account).

**Closed** 2022-02-04 14:59 UTC
Labels: *duplicate

**Comment by adam-arold** [comment] 2022-02-05 19:13
> @adam-arold this is not true. I always worked this way, I opened the terminal on the right and when I wanted to see more and put it on full screen I just clicked Maximize button. It was always there until the recent update.

Yes, it is true for the **Panel** but it is not true for the **Side Panel** (the one they added with `1.64.0`. That's what I meant. My problem is also that the *Side Panel* doesn't have the maximize and the *Panel* can't be moved from the bottom to the right.
