### ISSUE TITLE
Renaming in sidebar loosing focus when new files are created in project

### ISSUE THREAD

**Issue by darcyrush** [microsoft/vscode#141920] opened 2022-02-01 08:22 UTC
When using F2 to rename a file or folder in the sidebar (./src) and a file is created elsewhere in the project (./built), focus is lost.

Searched existing issues, happens with extensions disabled. May be related to  #115716. Using nodemon and npm run build.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-44-generic
```

**Comment by JacksonKearl** [comment] 2022-02-01 17:59
Duplicate of #112293, been fixed in Insiders for a bit now and will be out in the next stable release (a couple days from now)

**Closed by JacksonKearl** 2022-02-01 17:59 UTC
