### ISSUE TITLE
Build failed: LinuxArm64LegacyServer build failed on dependencies installation stage

### ISSUE THREAD

**Issue by legomushroom** [microsoft/vscode#233738] opened 2024-11-13 01:03 UTC
Build: [link](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=304320&view=logs&s=8c33c0df-d88f-5234-2de1-c6b850533e85&j=c6d3aa27-fdbb-548f-1661-69ade68a4dac)

Dependencies installation for the `LinuxArm64LegacyServer` build fails for some reason, tried to re-run but no joy so far. 
@mjbvz [your change](https://github.com/microsoft/vscode/commit/ff60639413d9b770688de99874cd29c4eb196f99) looks like the most probable cause to me, please take a 👀 when you have a chance.

**Comment by deepak1556** [comment] 2024-11-13 03:50
Thanks for catching this. Reassigning to myself, although the above change triggered it. The root cause is something else.

**Closed** 2024-11-13 08:42 UTC
Labels: vscode-build
