### ISSUE TITLE
Debug hover is hiding when hovered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151019] opened 2022-06-01 18:56 UTC
Testing https://github.com/microsoft/vscode/issues/150321

Was debugging the drop-on-document extension sample on branch drop-file-transfer

![Recording 2022-06-01 at 11 55 05](https://user-images.githubusercontent.com/2193314/171480983-b820a832-fa35-4620-b471-02213eb89e47.gif)

Version: 1.68.0-insider (user setup)
Commit: 4589815e4849499c67125ff68563fa102646b869
Date: 2022-06-01T05:16:24.411Z
Electron: 17.4.6
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by roblourens** [comment] 2022-06-01 23:48
I think I triggered it once. I think that moving the cursor right before is part of it. I've also seen the hover shift a few pixels a second after appearing, and I wonder whether that is part of this.

**Comment by roblourens** [comment] 2022-06-02 00:03
Haven't really looked at this before but the hover is tied to a particular character, and I think it can get messed up when you hover a different character before your cursor gets to the hover widget, depending on timing.

https://github.com/microsoft/vscode/blob/339c3a9b60594411c62ea3ed9123a0b26cf722e9/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L449-L452

**Comment by Tyriar** [comment] 2022-06-02 14:47
It seemed to happen every time for that symbol, I don't think I'm changing characters in each case of the gif. Also the hover should be targeting the word range not just the character (maybe not though?).

**Comment by sumneko** [comment] 2022-07-07 16:04
![debug-hover](https://user-images.githubusercontent.com/5213431/177819102-bdeaaf51-943d-4c6e-9125-4383cb2c821e.gif)

I'm not sure if I should open a new issue.
When folding a item, the mouse position may leave the hover, makes hover disappear.

**Comment by StoneWolf** [comment] 2022-08-15 18:48
What's happening here is that as soon as your mouse cursor is outside of both the word being debugged and the debug hover, the debug hover disappears. There is a tiny empty space between the word and the debug hover (2px), so if your cursor ends up in this empty space, the hover disappears.

You can reproduce this by slowly moving your cursor up from the word to the debug hover. If you move if quick enough such that Windows "teleports" your cursor from the word to the hover, it won't happen.

An idea to get rid of this would be to add a "dead zone" of a few pixels around the debug hover, so that even  if you move your cursor a few pixels away from the hover, it wouldn't instantly hide.

**Comment by jespertheend** [comment] 2022-08-15 18:52
If a dead zone is the fix, sounds like this might be related to #156749 then.

**Comment by RLPHRE** [comment] 2022-09-09 15:27
Just wanted to leave a comment here and say that this is happening to me daily and it's super annoying.  I feel like I'm constantly hovering my mouse when debugging to make the dialog pop back up, or I'll dig deep in an object tooltip while debugging and then it will just disappear for seemingly no reason.

**Comment by roblourens** [comment] 2022-09-13 02:34
Quick notes -

The solution is to separate the code that computes the hover result from the code that shows the hover. Need to extract most of this method https://github.com/microsoft/vscode/blob/82f2db788bc1a9efb0d0c9dc5599947c457c087a/src/vs/workbench/contrib/debug/browser/debugHover.ts#L196 into a separate `DebugHoverComputer` class. That will be called from here https://github.com/microsoft/vscode/blob/82f2db788bc1a9efb0d0c9dc5599947c457c087a/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L371 so that it can 

- know the real range of the hovered expression, and only re-show the debug hover if that range changes
- show the hover in the correct location at the beginning of the expression, instead of at the cursor

I'm happy to accept a PR, or I will work on it when I find the time since it annoys me too!

**Comment by ak99372** [comment] 2022-09-28 17:51
Could we also have a settings for [**hover away delay**] in preferences that would 
 - delay hiding the popup and prevent closing the popup if the mouse went away and then back (within the delay time)?

(NOTE: This would no apply to click away which should still hide the popup instantly)

**Closed** 2022-10-07 22:39 UTC
Labels: bug, debug, papercut :drop_of_blood:

**Comment by weinand** [comment] 2022-10-27 14:38
I could not reproduce this anymore. Great work.
