### ISSUE TITLE
v1.60 ignores user preference of the integrated terminal and always launches PowerShell

### ISSUE THREAD

**Issue by yychang** [microsoft/vscode#132789] opened 2021-09-09 18:55 UTC
Issue Type: <b>Bug</b>

1. Start vscode
2. In terminal window, select "Command Prompt" as the default profile
3. Re-start vscode. Expect a cmd.exe terminal to be created, but pwsh terminal is created.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (49.48GB free)|
|Process Argv|--crash-reporter-id 18dedd10-cab9-4a6f-a79a-19fc2439d355|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
vscode-nmake-tools|Mic|4.0.210802003
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vim|vsc|1.21.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
dockerwalkthru:30344881
bridge0723:30353136

```

</details>

**Comment by IllusionMH** [comment] 2021-09-09 19:34
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-09 19:34 UTC
Labels: *duplicate
