### ISSUE TITLE
Windows: Opening VSCode as admin while already open as non-admin does nothing. 

### ISSUE THREAD

**Issue by bkkmbs** [Microsoft/vscode#8628] opened 2016-07-01 14:04 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 7 Service Pack 1

Steps to Reproduce:

1. Open Code like normal
2. Using any way to open vscode from windows (start menu link, desktop shortcut, program files, etc) right click and choose 'Run as Admin'.

VSCode just highlights the open vscode taskbar icon and doesn't do anything.

**Comment by bpasero** [comment] 2016-07-02 06:19
Yes, we currently do not support this scenario, sorry.

**Comment by joaomoreno** [comment] 2016-08-31 15:46
Duplicate of #1614

**Closed by joaomoreno** 2016-08-31 15:46 UTC
Labels: bug
