### ISSUE TITLE
Navigating "back" from a split editor sometimes navigates from the wrong side

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#46877] opened 2018-03-28 21:03 UTC
Issue Type: <b>Bug</b>

Open documents in split mode and do some navigation on both of them (follow links to type-definitions, etc.)
Then go to one of the sides and hit "back" a few times.

Expected: the selected side gets navigated back
Actual: If the file being navigated is also on the other unselected side, navigation goes randomly between the two sides of the split

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|63.92GB (45.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
rest

**Comment by bpasero** [comment] 2018-03-29 07:57
I would treat this as duplicate of https://github.com/Microsoft/vscode/issues/9526

**Closed by bpasero** 2018-03-29 07:57 UTC
Labels: workbench-history
