### ISSUE TITLE
Terminal: Bind Ctrl+C and Ctrl+V

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8408] opened 2016-06-28 17:55 UTC
Testing #8222 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

These might be similarly common as Ctrl+Ins / Shift+Ins.

**Comment by Tyriar** [comment] 2016-06-29 01:20
Duplicate of https://github.com/Microsoft/vscode/issues/6451

**Closed by Tyriar** 2016-06-29 01:20 UTC
