### ISSUE TITLE
Bracket Pair Colorization - Match active scope ruler and underline color to the brackets color

### ISSUE THREAD

**Issue by ElliotRG** [microsoft/vscode#133528] opened 2021-09-21 12:54 UTC
Hi,

I love the new feature! But I miss the option to have the indent guide ruler of the current scope/closure colorized the same color as the closing brackets. Also, it would be great to have underlined with the same color the closure opening line (such as a method or if condition header).

This styling option is available in the former Bracket Pair Colorizer extension and I would love to see integrated into the new feature in VS Code. It looked like this:

![image](https://user-images.githubusercontent.com/36522513/134174141-8040a0c2-82db-4e17-915c-2d411d290903.png)

Thanks!

**Comment by gjsjohnmurray** [comment] 2021-09-21 13:00
Your first request appears to be on the way - see PR #133509

/assign @hediet

**Comment by hediet** [comment] 2021-09-21 13:08
Duplicate of #131001.

**Closed by hediet** 2021-09-21 13:08 UTC
