### ISSUE TITLE
Opened file disappears after switching to Centered layout

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#52163] opened 2018-06-18 08:08 UTC
Issue Type: <b>Bug</b>

When I open a document, and switch to "Centered layout" (another issue: editor doesn't react on the first click), the document disappears. It is also not possible to open any other document  from the sidebar. However, all documents that are opened are still listed in sidebar in panel groups.

Steps:
1) Open any document
2) Switch to Centered Layout
3) Observe that the document will disappear and center panel is empty

Video:
![issue-centered-layout](https://user-images.githubusercontent.com/4237724/41524919-6ee5b8fc-72df-11e8-9491-a9c40e73d463.gif)

VS Code version: Code - Insiders 1.25.0-insider (777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429, 2018-06-18T05:15:57.671Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.24GB free)|
|Process Argv|E:\Programs\Documents\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
language-postcss|cpy|1.0.5
vscode-svgviewer|css|1.4.4
EditorConfig|Edi|0.12.4
vsc-material-theme|Equ|2.1.0
auto-close-tag|for|0.5.6
wordcounter|kir|1.2.2
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.14
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-duplicate|mrm|1.2.1
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10
code-spell-checker-czech|str|0.1.0
dictionary-completion|yzh|0.6.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2018-06-18 09:03
This is fixed in latest insiders.
If you can still reproduce with latest vscode insiders let us know and we will reopen this issue. Thanks

**Closed by isidorn** 2018-06-18 09:03 UTC

**Comment by alexdevero** [comment] 2018-06-18 09:49
Updated to the latest version of insiders and can confirm that I can't reproduce this issue anymore. Good job guys 👍 .

Version: 1.25.0-insider
Commit: c51cf862a9604dffe2e3e8792a4b0a45213869a3
Date: 2018-06-18T08:50:30.859Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by isidorn** [comment] 2018-06-18 09:58
Make note that some of your 18 extensions might be causing this.
So if you get the next stable update and you still get this issue I would disable extensions one by one until you find the root cause. THanks
