### ISSUE TITLE
Slow performance/High CPU utilization for syntax highlighting comments with built-in PowerShell extension

### ISSUE THREAD

**Issue by Wombatzoner** [Microsoft/vscode#56476] opened 2018-08-15 15:27 UTC
Issue Type: <b>Bug</b>

1) Create .ps1 file with the PowerShell comment block below in it.
2) Open the file in VS Code with the built-in  Powershell Language Basics extension enabled.

VS Code CPU utilization goes way up and it takes several minutes to complete the syntax highlighting.

Comment block:

```powershell
<#
.SYNOPSIS
    Script to send report on NAP Group Issues, Computer Aging, Misfiled Computer and Legacy OS via e-mail.
.DESCRIPTION
    Script to send report on NAP Group Issues, Computer Aging, Misfiled Computer and Legacy OS via e-mail.

    By name redacted - Organization redacted - e-mail redacted
.PARAMETER ConfigFile
    XML configuration file containing the script's settings.  Defaults to Report-NAPOS-Config.xml if not otherwise specified.
.NOTES
    By name redacted - Organization redacted - e-mail redacted

    v1.0 - Sep 19, 2014 - Initial release.
    v1.1 - Sep 26, 2014 - Added reporting on Windows XP and Server 2003 systems found.
                          Added Summary section, updated report wording.
    v1.2 - Oct 03, 2014 - Switched to pipeline output from OSCheck-BL instead of writing result to a file.
                          Checks IP of computers in top Computer container for a Organization redacted IP in addition to name starting with redacted.
                          Updated report wording.
    v1.3 - Oct 16, 2014 - Switched to CSS to control table formatting.
                          Computer name prefix and IP range to search for in top Computer containers now set as configuration variable.
                          Log-Item now sends output to the console and the log file.
    v2.0 - Oct 20, 2014 - Switched to XML file to store script options, CSS file to store style sheet.
    v2.1 - Oct 24, 2014 - Switched to regular expressions to specify search and exclude filters.
                          Streamlined report generation code.
    v2.2 - Oct 31, 2014 - Presence or absence of all report sections (NAP, Aging, Misfiled, Legacy OS) now set in the configuration file.
                          Search OU for all sections except Misfiled Computers now set in configuration file.
                          Moved section specific settings to their section of the config file.
                          Added support for inline timestamps for Subject, MessageHeader, and MessageFooter.
                          Added option to save copy of report to HTML file.
                          Updated report formatting and wording.
    v2.3 - Nov 07, 2014 - Configuration.ReportSettings.Aging.RemovalDays can now being empty or missing.
                          Fixed name anchors enclosing summary titles, which was causing a minor rendering issue in iOS Mail.
                          Added explicit loading of System.Web assembly to fix issue with calls to [System.Web.HttpUtility]::HtmlDecode().
                          Standardized formatting of calls to ConvertTo-Html and Select-Object.
    v2.4 - Nov 13, 2014 - Switched to pipeline output from NAP-Group-Check instead of writing result to a file.
                          Added support for -groupSearchBase setting required by NAP-Group-Check to verify NAP groups.
                          Added support for sorting report sections by their properties.
                          Changed ShowIfEmpty attributes to all lowercase per XML Schema specification.
    v2.5 - Dec 19, 2014 - Added support for checking MAB accounts for issues.
                          Improved Terminate-Script error reporting. Now using Throw to terminate script with error information.
                          Removed unused parameters from call to NAP-Group-Check.
                          Updated capitalization and spacing in the report text.
    v2.5.1 - Apr 26, 2016 - Now calling Send-MailMessage with -ErrorAction Stop so it throws an error for the try/catch block to catch.
                            Terminate-Script now uses $ErrorRecord.InvocationInfo.ScriptName instead of $MyInvocation.ScriptName.
                            Terminate-Script now throws $Message if $ErrorRecord not set.
    v2.5.2 - Mar 20, 2017 - Switched from System.Web.HttpUtility.HtmlDecode to System.Net.WebUtility.HtmlDecode to generate summary table.
    v2.6 - Oct 2, 2017 - Added option to specify a regex for OperatingSystemVersion in Configuration.ReportSettings.Legacy entries.
                         Added OperatingSystemVersion to the Legacy OS report tables.
                         Added Action column to age report section for easier use with computer removal script.
#>

```

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.10GB free)|
|Process Argv|C:\Users\eforsythe0002\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.2
xml|Dot|2.3.1
git-project-manager|fel|1.6.1

</details>

**Comment by Serega124** [comment] 2018-08-15 16:44
Bisected example:
```powershell
<#
                        .
#>
```

**Comment by Serega124** [comment] 2018-08-15 17:03
powershell.tmLanguage.json line 414 has catastrophic backtracking:
`(?:\\s*|#)+(\\.)`
Changing it to `(?:\\s?|#)+(\\.)` seems ok.

**Comment by Serega124** [comment] 2018-08-15 17:08
@aeschli already [reverted](https://github.com/Microsoft/vscode/commit/f125fe6fe1a278bc3e481cc43ba8c075dd73b942) it to older commit.

**Comment by aeschli** [comment] 2018-08-16 07:01
duplicate of #56430

**Closed by aeschli** 2018-08-16 07:01 UTC
Labels: new release
