### ISSUE TITLE
Terminals launched with invalid paths hang during creation and never emit onExit

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#31301] opened 2017-07-24 07:08 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. Open an empty folder with VSCode
2. Configure a new MSBuild task
3. Try building (execute task)

Expected: Fails gracefully somehow
Actual: Just spins forever and never dies until I manually kill the task.

Note: this also happens when I mistype a path or something in the command to a directory that say for example doesn't exist.  If the command is wrong in some way, the task will just spin forever.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment] 2017-08-03 14:28
The terminal doesn't send an onExit or any other event in this case so that the task system could determine that the process has finished / died. Steps to reproduce:

- Windows, no msbuild installed
- fresh workspace
- configure task runner
- select MSBuild from the list of templates
- F1 > Run Task > Select Build

Observe: the spinner never stops. Could can't even terminate the task.

The reason is that the shell actually fails to execute msbuild however the terminal never send an onExit event. Look at the process explorer there is a lingering vscode process of --type=terminal

<img width="521" alt="capture" src="https://user-images.githubusercontent.com/1931590/28926675-c7e6fa3c-7868-11e7-8024-aea1c31cc23a.png">

**Comment by Tyriar** [comment] 2017-08-21 21:24
I upgraded to node-pty@0.7.0 which may improve the problem, if not I'd guess this is related towinpty is not terminating the processes correctly.

**Comment by dbaeumer** [comment] 2017-08-24 20:23
I retested this and it is still happening under Insider today.

**Comment by Tyriar** [comment] 2017-08-28 17:43
terminalProcess stalls on this native call: https://github.com/Tyriar/node-pty/blob/a1d161cba7396849116b94d8fa6bb0041a9a7ea6/src/win/pty.cc#L87, meaning this function never returns https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L47

Not sure why a Node.js or native exception isn't happening.

**Comment by Tyriar** [comment] 2017-08-28 17:59
This has the same root cause as https://github.com/Microsoft/vscode/issues/31770

**Comment by Tyriar** [comment] 2017-08-28 19:54
Moving to September as this is a more involved change than I anticipated. More testing in Insiders would be ideal.

**Comment by dbaeumer** [comment] 2017-09-25 09:44
@Tyriar any news on this. Do I need to adopt something here ?

**Comment by Tyriar** [comment] 2017-09-26 05:34
No progress, I moved this to September before I knew that I would be out for 2 weeks in September.

**Comment by Tyriar** [comment] 2017-09-26 05:35
It does look like it affects Windows only.

**Comment by mattacosta** [comment] 2017-10-13 13:07
Hmm, I believe that I just came across this while trying to run some tests, and `tsc` exited with an error code. I was able to reproduce it using this:

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/program.js",
            "preLaunchTask": "errorcode"
        }
    ]
}
```
**tasks.json**
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "errorcode",
            "type": "shell",
            "command": "exit",
            "args": [
                "2"
            ]
        }
    ]
}
```

Everything works fine if the error code is changed to `0`.

**Comment by azydevelopment** [comment] 2018-05-23 08:11
Was this never solved?

**Comment by dbaeumer** [comment] 2018-05-23 08:16
@Tyriar when I last tested this I had the impression that this is still a bug and the terminal hangs (doesn't signal on exit).

**Comment by azydevelopment** [comment] 2018-08-09 23:02
Is this in line to be fixed btw?

**Comment by azydevelopment** [comment] 2018-08-25 08:14
This still happens btw when I'm doing my PowerShell development.....I have to keep restarting all of VSCode because my debugging sessions won't end properly.

**Comment by alexr00** [comment] 2018-09-14 22:55
@Tyriar, does this sound like something that will be fixed by conpty?

**Comment by Tyriar** [comment] 2018-09-15 02:54
@alexr00 it probably needs a check in node-pty that the file exists before attempting to fire it. It's possible that conpty would fix this but that would only fix it for newer Windows versions when the fix should work when we fallback to winpty.

**Comment by alexr00** [comment] 2018-09-18 16:53
@Tyriar There's already a `file_exists` check in node-pty before attempting to execute the file. I can't actually reproduce this with a garbage command in my task (ex. `"command": "notcmd.exe"`)
I do think I'm seeing this when I pass garbage in for the `args` that results in a failure though:
`> Executing task: cmd.exe /k c:\users\alros\desktop\nottestscript.bat <

'c:\users\alros\desktop\nottestscript.bat' is not recognized as an internal or external command,
operable program or batch file.`

**Closed** 2018-09-19 16:03 UTC
Labels: bug, integrated-terminal, windows
