### ISSUE TITLE
Auto dismiss messages

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#2732] opened 2016-02-05 10:18 UTC
Could you add API support to have timeout dismiss messages through the window.showInformationMessage (also warm and error message) API. Requiring the user to have to dismiss these manually can be intrusive if the message is not extremely pertinent. To avoid the user missing the message if they are using vscode at the time it appears it would be good to have a system where the message timeout does not begin until the window is in active use.

**Comment by jrieken** [comment] 2016-02-05 14:25
Because those messages are rendered very prominent their indent is that a user must react on them. Messages that don't have those characteristics should use the `setStatusBarMessage` API (or the more generic status bar api)

I am leaning towards closing. @tht13 What is the scenario in which the status bar API isn't sufficient but the message API is too strong?

**Comment by tht13** [comment] 2016-02-06 09:56
The scenario I had in mind was a notification that updates for vscode are downloading (another issue I was going to write) or the notification saying no updates are available. But these could be solved by a status bar message.

**Comment by jrieken** [comment] 2016-03-07 11:07
Yes - those things should be in the status bar.

**Closed by jrieken** 2016-03-07 11:07 UTC
Labels: api, feature-request

**Comment by lkytal** [comment] 2017-02-16 15:43
I would still propose to add a API like `showToast` as the `setStatusBarMessage` are sometimes too humble to notice.

**Comment by chrisalexander** [comment] 2017-03-04 18:06
Sorry to dig up something closed nearly a year ago but I agree with @lkytal here. I have an analyser which takes the current document, highlights two classes of word, and informs the user how many of each class was found. Telling the user the counts is something that a toast really does support where status bar and info message do not. The user needs to see the info in a prominent way (so status bar no good) and just needs to be informed about it without them needing to interact with it (so info message no good).

Please could the team reconsider an API which supports these two mechanisms? The status bar really is too subtle and can be quickly overwritten with something else by another extension.

**Comment by eug48** [comment] 2017-03-05 10:14
My use-case is auto-updating an extension which is under development. Many of our users would be not-so-technical and the current UI is too subtle.. First it shows an "Update Available" message with an "Install Update" button. If the update is started it creates a status bar item with download progress, but also shows a "Downloading update" message since our users are likely to not notice the status bar. Once the download completes we show a "Success" message and would like to dismiss "Downloading update".

**Comment by jeremychone** [comment] 2017-08-11 02:53
+1 on this requirement. The problem is that the StatusBarMessage is too subtle.

 I really wish we had something to notify the user that things went well but still be action less (e.g., not requiring them press close or esc)
