### ISSUE TITLE
Feature: Extensible minimap on mouse over

### ISSUE THREAD

**Issue by willemavjc** [microsoft/vscode#84245] opened 2019-11-08 10:40 UTC
Thanks for making with version 1.40 the minimap extensible on a predefined value (in Settings).

What would be great is the possibility to have a minimap minimized by default which would be able to expand on mouse over (via a checkbox parameter in Settings for example). 

This feature would be especially useful when working on screens smaller than 20" where workspace matters.

**Comment by willemavjc** [comment] 2019-11-08 10:42
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Combine New Minimap with Git Sidebar (#22563)](https://www.github.com/microsoft/vscode/issues/22563)
> * [Minimap enhancements (#24395)](https://www.github.com/microsoft/vscode/issues/24395)

It is not. I double checked. :)

**Comment by alexandrudima** [comment] 2019-11-08 11:57
Duplicate of https://github.com/microsoft/vscode/issues/40048

**Closed by alexandrudima** 2019-11-08 11:57 UTC
Labels: editor-minimap

**Comment by willemavjc** [comment] 2019-11-08 14:08
Mmh... Not a real duplicate as the feature described is not the same but if the other one comes to life, we could stay with the smallest sized.
