### ISSUE TITLE
korean letters '각, 강, ...' appear strangely

### ISSUE THREAD

**Issue by mrharrykim** [microsoft/vscode#118365] opened 2021-03-07 13:17 UTC
Issue Type: <b>Bug</b>

type 각, 강, etc.
It appears to be 가ㄱ,가ㅈ, etc.

-disclaimer
It's actually been encoded correctly but only appears to be strange.

VS Code version: Code - Insiders 1.55.0-insider (04770364fdc1bebeca9d1a257df2cacce06b35d6, 2021-03-05T15:40:18.961Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1535)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.91GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30268769
vsget980:30265949
vspre833cf:30267465

```

</details>

**Comment by alexdima** [comment] 2021-03-09 08:37
@HarryKim535 Could you perhaps also explain here in great detail the keys to press with their labels as they would be printed on a US keyboard (that is switched to the Korean keyboard layout in the OS)?

Here is an example of what I'm looking for: https://github.com/microsoft/vscode/wiki/IME-Test#windows-korean . 

This would be very helpful to try to reproduce the issue, as I don't speak Korean.

**Comment by HarryKim535** [comment] 2021-03-11 03:40
for the examples above I typed 'rkr, rkd' respectively.
It happens whenever I type rk(가) and add another consonant key.

**Comment by alexdima** [comment] 2021-06-05 13:27
@mrharrykim We believe this to be a problem with the default `"editor.fontFamily"` on Linux, `Droid Sans Mono`. Does this reproduce when installing e.g. Fira Code and configuring `"editor.fontFamily": "Fira Code"` ?

**Comment by mrharrykim** [comment] 2021-06-05 14:29
Yes. It persist. When I change the font family, the english letters does change but it has no effect on korean letters.

**Comment by alexdima** [comment] 2021-11-29 22:32
I am fairly confident that this was caused by us writing to the textarea (changing its value) during the `compositionstart` event. In other words, I think the fix for #138095 will also fix this issue. I would be very thankful if you could verify that the issue no longer reproduces using tomorrow's [Insiders](https://code.visualstudio.com/insiders/) that should be released in 9-10 hrs.

**Comment by alexr00** [comment] 2021-12-03 15:01
\closedWith 31fff5074d286d845d6de9e1bbc09aafa266a062

**Comment by rchiodo** [comment] 2021-12-03 17:34
/verified? Maybe this needs linux to repro. I couldn't repro on stable either.

**Comment by rzhao271** [comment] 2021-12-06 19:37
I can repro the original issue (typing rkr and rkd result in two characters rather than one) on my Xubuntu VM using fcitx and the Hangul layout.

**Comment by alexdima** [comment] 2021-12-07 16:25
@rzhao271 Thank you for testing. After more testing from my side, it looks like this was never an issue with input per-se. 

This is a display problem that is caused by the font family `Droid Sans Fallback` that is included in our Linux default. This issue was encountered before in https://github.com/microsoft/vscode/issues/72083

**Comment by alexdima** [comment] 2021-12-07 16:55
To verify, simply copy-paste the following in VS Code on Linux:
```
aa각aa
```
A single Korean glyph should be rendered:
![image](https://user-images.githubusercontent.com/5047891/145072220-b7203839-b64b-492c-b3fb-09b0e9db120a.png)

**Closed** 2021-12-07 16:56 UTC
Labels: bug, linux
