### ISSUE TITLE
Executing task depending on terminal

### ISSUE THREAD

**Issue by nikodz** [Microsoft/vscode#68150] opened 2019-02-07 18:40 UTC
Issue Type: <b>Bug</b>

While executing task at first after opening `VS Code - Insiders`  it shows output in terminal. At the end, if i press any key to close the tasks log in terminal, I have to reopen editor to run any other task again. Otherwise, it throws an exception `Failed to create terminal for task [TASK LABEL]`

VS Code version: Code - Insiders 1.32.0-insider (45c7f29565821668f4d010b25e3289953bd9ac71, 2019-02-07T10:25:31.179Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.83GB (6.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|0.4.1

</details>

**Comment by 123swk123** [comment] 2019-02-08 14:46
split terminal is not working as well error logs enclosed below

Uncaught TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:338)
    at Buffer._reflow (Buffer.ts:238)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1702)
    at Terminal.resize (Terminal.ts:51)
    at D._resize (terminalInstance.ts:1223)
    at decorators.ts:85
2notificationsAlerts.ts:40 The terminal process command '/bin/bash' failed to launch (exit code: 1)
t.onDidNotificationChange @ notificationsAlerts.ts:40

**Comment by vpereira01** [comment] 2019-02-08 16:19
Currently dealing with the (I think) same issue. I tried to run without extensions but the result is the same.

In the log (Window) I can see this:

> 
> [2019-02-08 16:11:42.745] [renderer8] [error] Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
>     at e.createTerminal (file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3314:132)
>     at l (file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3306:659)
>     at new Promise (<anonymous>)
>     at e.executeInTerminal (file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3305:990)
>     at file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3304:667
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> [2019-02-08 16:11:42.746] [renderer8] [error] Failed to create terminal for task dcompose down: Error: Failed to create terminal for task dcompose down
>     at e.executeInTerminal (file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3310:371)
>     at file:///C:/Users/FirstName LastName/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3304:667
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z

**Comment by nikodz** [comment] 2019-02-08 20:03
I reinstalled VS Code - Insider to user setup and I cannot repeat the error.

Here's info from `Help` -> `About`
> Version: 1.32.0-insider (user setup)
Commit: 709bf352b12de8284683bef94cb5984129bfc776
Date: 2019-02-08T14:53:26.555Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by 123swk123** [comment] 2019-02-10 01:40
i am still facing this issue with updated vscode as well.

> Version: 1.32.0-insider
> Commit: 709bf352b12de8284683bef94cb5984129bfc776
> Date: 2019-02-08T14:50:08.266Z
> Electron: 3.1.3
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Linux x64 4.20.7-042007-generic

**Comment by pjrader1** [comment] 2019-02-10 05:21
I'm having this same issue with 1.31.0 on Linux.
```
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.0-0.bpo.1-amd64
```

**Comment by mihaiconstantin** [comment] 2019-02-10 08:08
Same here with the following version:

```
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Context:

- when I run the task for the first time, it works
- then, after I close the terminal and try to run the task later I get `Failed to create terminal for task {task name}`

Output in `Log (Windows)` shows:

```
[2019-02-10 09:05:41.636] [renderer1] [error] Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at e.createTerminal (file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3314:132)
    at l (file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3308:58)
    at new Promise (<anonymous>)
    at e.executeInTerminal (file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3308:19)
    at file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3304:667
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-02-10 09:05:41.637] [renderer1] [error] Failed to create terminal for task {task name}: Error: Failed to create terminal for task run
    at e.executeInTerminal (file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3310:371)
    at file:///C:/Users/Mihai/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3304:667
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I simplified the file `tasks.json` to only run a `dir` command (i.e., more or less identical to what is on the documentation page for running tasks) and the issue still persists. Any idea what is causing this?

**Comment by mihaiconstantin** [comment] 2019-02-10 21:29
A workaround I found is to set the `panel` property to `dedicated` on all tasks. Now all my tasks have the following and the issue seems to be gone:

```json
"presentation": {
    "clear": true,
    "panel": "dedicated"
}
```

**Comment by Felix-Indoing** [comment] 2019-02-11 07:18
same issues here.

`
Version: 1.31.0
Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
Date: 2019-02-09T14:23:42.615Z
Electron: 2.0.16
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.20.7-arch1-1-ARCH
`

`
[2019-02-11 15:12:39.409] [renderer1] [info] no standard startup: not just one text editor
[2019-02-11 15:13:12.346] [renderer1] [error] Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at e.createTerminal (file:///usr/lib/code/out/vs/workbench/workbench.main.js:3315:132)
    at l (file:///usr/lib/code/out/vs/workbench/workbench.main.js:3309:58)
    at new Promise (<anonymous>)
    at e.executeInTerminal (file:///usr/lib/code/out/vs/workbench/workbench.main.js:3309:19)
    at file:///usr/lib/code/out/vs/workbench/workbench.main.js:3305:667
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-02-11 15:13:12.347] [renderer1] [error] Failed to create terminal for task installExtensions: Error: Failed to create terminal for task installExtensions
    at e.executeInTerminal (file:///usr/lib/code/out/vs/workbench/workbench.main.js:3311:371)
    at file:///usr/lib/code/out/vs/workbench/workbench.main.js:3305:667
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by alexr00** [comment] 2019-02-11 12:57
Duplicate of https://github.com/Microsoft/vscode/issues/68077

**Closed** 2019-02-11 13:05 UTC
