### ISSUE TITLE
Configuration values are missing from files on remote network drives

### ISSUE THREAD

**Issue by RobIsHere** [Microsoft/vscode#31667] opened 2017-07-28 14:07 UTC
When I open a folder from my server e.g. \\MYSERVER\some-project, all debug configurations are missing.

If I open the same folder from a drive letter, that is mapped to \\MYSERVER\some-project, all debug configurations work as expected.

==================================
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 
vsc-ember-frost|cie|0.0.2
vscode-eslint|dba|1.2.11
vscode-babel-coloring|dza|0.0.4
redux-snippets|jam|0.0.2
debugger-for-chrome|msj|3.1.6
code-settings-sync|Sha|2.8.2
vscode-react-native|vsm|0.4.0

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-07-28 14:47
This is due to the fact that we are missing file events from network locations. So debug does not get pinged by configuration service for a change
Forwarding to @bpasero  since he probably knows if this is a duplicate or this should be covered by #13665

**Comment by RobIsHere** [comment] 2017-07-28 14:57
To clarify this: I did _not change_ the launch.json. The launch.json was like today for at least a month, working well.

But vscode always deletes the Recent Folder Entry, when you forget to click on the drive-mapped network folder in explorer.

So I decided to open it via its network name. But then I can't debug.

As this incident happened at the same time with some other issues and updates, I wasted two hours to find the cause. At least please add this to an FAQ or docs.

**Comment by isidorn** [comment] 2017-07-28 15:14
Thanks for more details.
FYI we accept PRs for vscode-docs here https://github.com/microsoft/vscode-docs

**Comment by se-m** [comment] 2017-07-28 15:19
Problem exists even you mount network shares to folders
e.g. `mklink /d c:\proj \\server\share\foldername\`

vscode does not read not only debug config (launch.json), but also workspace settings (settings.json)

**Comment by bpasero** [comment] 2017-08-11 08:12
@RobIsHere do the configurations show up when you do a restart of VS Code? If not, then this imho is not a file watching problem.

**Comment by RobIsHere** [comment] 2017-08-11 08:24
I share your opinion. I restarted it a couple of times and they never showed up.

Unless you have done very unusual things in your code, this is no file watching problem. But that's what I already wrote above.

I'm on sailing holiday, so I can't do further testing now, sorry

**Comment by bpasero** [comment] 2017-08-11 09:01
Ok thanks, we should try to reproduce this somehow. I have heard issues like that in the past.

**Comment by bpasero** [comment] 2017-11-15 17:54
Does this still happen?

**Comment by RobIsHere** [comment] 2017-11-15 18:12
Yes. Version 1.18.0. In the screenshots below you can see one and only one project.
Its located on my MacBook. And shared from there via SMB.

When opened remote from my Windows 10 PC, You see the debug configs are missing (Keine Konfigurationen = No Configurations) and there is an indicator to work on the debug configs. Although the commands can be executed via shell.

Having this working would be quite cool, because the ios simulator only runs on a mac. So I would like to ssh-tunnel the react-native packager to the mac.

![debugconfigsmissing](https://user-images.githubusercontent.com/13229377/32852531-8641db5c-ca38-11e7-911f-98976319015e.PNG)

<img width="695" alt="bildschirmfoto 2017-11-15 um 19 01 13" src="https://user-images.githubusercontent.com/13229377/32852256-9fdeee70-ca37-11e7-89f4-fd151d1c7b8f.png">

**Comment by bpasero** [comment] 2017-11-16 07:13
@RobIsHere @se-m would you be willing to help out on this issue by setting up VS Code to run from its sources so that we can add some debug information? The steps how to get there are outlined here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by RobIsHere** [comment] 2017-11-16 07:22
Yes, of course. Just tell me the details.

**Comment by bpasero** [comment] 2017-11-16 07:29
@RobIsHere we can start by looking at [`loadWorkspaceConfigFiles`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configuration.ts#L220). This would be the place where we look for all JSON files within the `.vscode` folder and start to read the contents. Can you check if a) we find all the JSON files that are relevant and b) their file content is resolved from the [`resolveContents`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configuration.ts#L228) call?

**Comment by RobIsHere** [comment] 2017-11-17 09:49
I got it up and running. Sorry for the delay -msbuild and vc++ compiler automagically switched to localized error messages. I didn't understand anything because they translated technical terms to common speech. There's a switch for the UI, but not for msbuild and vc++. Finally looked up the error codes on the web to get the english messages and resolved it. If you know someone who knows how to switch the language to english without switching windows at all, help is very appreciated.

**Comment by RobIsHere** [comment] 2017-11-17 09:58
I've done some debugging and my opinion is that the bug is here or in the subroutines: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configuration.ts#L333

You can see that the return value looks wrong. ROBERTS-MBP is the network name of the other computer. The relative path pointing to the parent folder of a computer doesn't look right.

In spite of this, the folder configuration below looks ok. I can access file://roberts-mbp/dropfella/ via the chrome address bar.

![tofolderrelativepath](https://user-images.githubusercontent.com/13229377/32941237-648743aa-cb85-11e7-81f5-d35e6a6ea1d2.PNG)

**Comment by bpasero** [comment] 2017-11-17 10:02
@RobIsHere awesome, can you give me all the variable values you see in the `toFolderRelativePath` method? Specifically:
* `resource` (toString, fsPath)
* `toOSPath` value
* `this.folder.fsPath` (maybe also toString value)

And from where the method is called

**Comment by RobIsHere** [comment] 2017-11-17 10:10
resource.toString(): "file://roberts-mbp/Dropfella/.vscode/launch.json"
resource.fsPath: "\\ROBERTS-MBP\Dropfella\.vscode\launch.json"
this.folder.fsPath: "\\ROBERTS-MBP\Dropfella"

**Comment by RobIsHere** [comment] 2017-11-17 10:13
Sorry, the github editor changed the backslashes. This is corrected:
```
resource.toString(): "file://roberts-mbp/Dropfella/.vscode/launch.json"
resource.fsPath: "\\ROBERTS-MBP\Dropfella\.vscode\launch.json"
this.folder.fsPath: "\\ROBERTS-MBP\Dropfella"
```

**Comment by RobIsHere** [comment] 2017-11-17 10:40
Narrowed it down to https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L24

Run the function with
```
from = "\\ROBERTS-MBP\Dropfella", to = "\\ROBERTS-MBP\Dropfella\.vscode\launch.json"
```
and you get 
```
Return value "../..//ROBERTS-MBP/Dropfella/.vscode/launch.json"
```

**Comment by RobIsHere** [comment] 2017-11-17 11:05
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L167
calling getRoot("\\ROBERTS-MBP\Dropfella") returns "/"
calling getRoot on some subfolder works

So a comparison of the two roots is not equal.

See the screenshots:
![getroot](https://user-images.githubusercontent.com/13229377/32944283-4eeefd44-cb8f-11e7-8041-23e8c97900f8.PNG)
![getrootwithfile](https://user-images.githubusercontent.com/13229377/32944287-51ea8112-cb8f-11e7-80d6-02cf2d0caa53.PNG)

**Comment by bpasero** [comment] 2017-11-17 13:57
@RobIsHere great work, can you grab latest from master and see if the fix I pushed makes it any better?

@jrieken it looks like `path.relative('\\\\ROBERTS-MBP\\Dropfella', '\\\\ROBERTS-MBP\\Dropfella\\.vscode\\launch.json')` results in `../..//ROBERTS-MBP/Dropfella/.vscode/launch.json`. We need to either fix that method or use the node.js one. The problem is that all remaining clients of our `paths.relative` live in common (including glob.ts)...

**Comment by jrieken** [comment] 2017-11-17 14:16
I am not responsible for `path.relative` not a single of my code has survived there and "yes" it's completely broken because it doesn't respect the [`root`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L167) of a path. Use node-path whenever possible, ideally move all code to /node/ when requires it

**Comment by RobIsHere** [comment] 2017-11-19 11:50
The debug configurations don't appear.

The sourcemaps seem to be broken now, breakpoints stop on different rows than the one I'm targeting, so it's tedious to find it out.

Maybe tests of some of the involved methods could be a lot faster in dev time than try-and-error?

Just another thing, don't know if that's a problem: getRoot is e.g. also called from paths.normalize:
return paths.normalize(relative(this.folder.fsPath, resource.fsPath), toOSPath);
So I'm not 100% sure about the fix.

**Comment by bpasero** [comment] 2017-11-20 06:26
@RobIsHere I think I am able to reproduce now when I use the UNC localhost notation on Windows and open the root drive with a `.vscode` folder inside: `\\localhost\c$`. However after my fix I see the configurations showing up, and without they do not. 

To be on the safe side can you maybe try to reproduce with todays insider build that includes my fix? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2017-11-21 11:32
Closing for November, this should be fine now.

**Comment by RobIsHere** [comment] 2017-11-21 12:51
I think this is not working yet!

![stillnoconfigurations](https://user-images.githubusercontent.com/13229377/33073382-08a8c554-cec3-11e7-86d8-d9af7d32bb05.PNG)

**Comment by bpasero** [comment] 2017-11-22 06:04
@RobIsHere can you use insiders please, the screenshot looks like you are still running out of sources.

**Comment by se-m** [comment] 2017-11-22 18:14
Hi.
I checked the last one insiders build. On windows 7x64 all fine. Debug configuration appears. There is no watch and autoreload, so you should restart vscode (or close&open folder) to see your changes in configuration file, but its ok.
Tested in both variants: "network shares as folders" and "network shares as network drive"

Version 1.19.0-insider
commit 3afa3348c5cc8ee7fb29458e303cf476b0887f0a

**Comment by RobIsHere** [comment] 2017-11-22 18:18
Can you install and run insider build side by side with the "normal" build? I'm hesitating a little bit because I still need my dev machine at work ;)

**Comment by se-m** [comment] 2017-11-22 18:23
Get latest code from github (commit bce608e4bf1df5325c68d6f0fb2b5fdefcbebf02) and make it run. Configuration also appears.

**Comment by se-m** [comment] 2017-11-22 18:27
![image](https://user-images.githubusercontent.com/642156/33143763-f0e86410-cfcb-11e7-9569-4775f947cdf8.png)

**Comment by se-m** [comment] 2017-11-22 18:29
left normal build 1.18.0
center build from sources
right insider

same folder opened in all three

**Comment by RobIsHere** [comment] 2017-11-22 18:32
Your github is showing 14 changes. But doesn't show any in insiders or master.

At my machine (accessing a smb share on mac from windows) it's the opposite. I'm seeing my github changes only on the master branch, not in the normal build.

Could this also be related to the changed path resolution here?

**Comment by se-m** [comment] 2017-11-22 18:50
My git installation folder not in usual place. I wrote git.path and it show the same result (14)

**Comment by bpasero** [comment] 2017-11-23 06:08
@se-m great to hear. yeah file events might be broken in that setup, that is a known issue. Closing as fixed.

**Closed by bpasero** 2017-11-23 06:08 UTC
Labels: bug, config, needs more info

**Comment by RobIsHere** [comment] 2017-11-23 08:30
Thank you @bpasero! I can confirm that this works in the insider build.

( It still does not work on master branch. But because you already had this in mind, this is probably specific to your git workflow )

**Comment by dbaeumer** [comment] 2017-12-07 10:01
Marking as verified due to https://github.com/Microsoft/vscode/issues/31667#issuecomment-346555655
