### ISSUE TITLE
colorCustomizations per folder on multi-root workspace

### ISSUE THREAD

**Issue by Klaudioz** [microsoft/vscode#173817] opened 2023-02-08 14:45 UTC
Working with a multi-root workspace would be great for customizing each root folder's colors and, specifically, coloring the tabs differently, as there might be files with the same name in the different folders.

It was created [before](https://github.com/microsoft/vscode/issues/164368), but it was closed because it didn't get the 20 likes. I think it'd get them this time because I can't believe such a great feature doesn't exist. I like to work with a unique VScode folder, with a dozen of folders in a multi-root workspace.

**Comment by aeschli** [comment] 2023-02-14 19:43
Closing as duplicate of https://github.com/microsoft/vscode/issues/164368

Even if the requests gets more than 20 votes, I don't see how we would be able to implement that.

**Closed by aeschli** 2023-02-14 19:43 UTC

**Comment by Klaudioz** [comment] 2023-02-14 20:58
Thanks for your comment.
