### ISSUE TITLE
Even when downloading and installing the usersetup windows will only open whenrun by a local admin.

### ISSUE THREAD

**Issue by shoitinga** [microsoft/vscode#160171] opened 2022-09-06 11:39 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment] 2022-09-06 16:30
Did you accept the default location when you ran the installer?

Did you use "Run as administrator" when you ran the installer? I hope you didn't.

**Comment by shoitinga** [comment] 2022-09-07 07:22
Working on windows 11. First I downloaded the user version, installed, accepted default location.
Upon starting I only noticed a vague mirror window. Then a message appeared. Window not responding. 
I uninstalled and tried the administrator version, same problem. Only IT support was able to get it running, when they opened as domain administrator. Uninstalled it.
Tried the user version again, same problem.

**Comment by deepak1556** [comment] 2022-12-06 10:53
Given the issue is unique to your domain setup, it is hard to debug this further without reliable repro steps. Closing as out of scope.

**Closed** 2022-12-06 10:53 UTC
