### ISSUE TITLE
VSCode hangs when using (recursive?) JSDoc @typedef s

### ISSUE THREAD

**Issue by dcodeIO** [Microsoft/vscode#23958] opened 2017-04-05 21:54 UTC
- VSCode Version: 1.10.2
- OS Version: Win10

Steps to Reproduce:

1. Copy the following to a new file *but-typedefs.js* and open it in VSCode:

```js
/**
 * @typedef EnumDescriptor
 * @type {Object}
 * @property {Object.<string,number>} values Enum values
 * @property {Object.<string,*>} [options] Enum options
 */

/**
 * @typedef TypeDescriptor
 * @type {Object}
 * @property {Object.<string,*>} [options] Message type options
 * @property {Object.<string,OneOfDescriptor>} [oneofs] Oneof descriptors
 * @property {Object.<string,FieldDescriptor>} fields Field descriptors
 * @property {number[][]} [extensions] Extension ranges
 * @property {number[][]} [reserved] Reserved ranges
 * @property {boolean} [group=false] Whether a legacy group or not
 * @property {Object.<string,AnyNestedDescriptor>} [nested] Nested object descriptors
 */

/**
 * @typedef FieldDescriptor
 * @type {Object}
 * @property {string} [rule="optional"] Field rule
 * @property {string} type Field type
 * @property {number} id Field id
 * @property {Object.<string,*>} [options] Field options
 */

/**
 * @typedef ExtensionFieldDescriptor
 * @type {Object}
 * @property {string} [rule="optional"] Field rule
 * @property {string} type Field type
 * @property {number} id Field id
 * @property {string} extend Extended type
 * @property {Object.<string,*>} [options] Field options
 */

/**
 * @typedef MapFieldDescriptor
 * @type {Object}
 * @property {string} keyType Key type
 * @property {string} type Value type
 * @property {number} id Field id
 * @property {Object.<string,*>} [options] Field options
 */

/**
 * @typedef ExtensionMapFieldDescriptor
 * @type {Object}
 * @property {string} keyType Key type
 * @property {string} type Value type
 * @property {number} id Field id
 * @property {string} extend Extended type
 * @property {Object.<string,*>} [options] Field options
 */

/**
 * @typedef OneOfDescriptor
 * @type {Object}
 * @property {Array.<string>} oneof Oneof field names
 * @property {Object.<string,*>} [options] Oneof options
 */

/**
 * @typedef ServiceDescriptor
 * @type {Object}
 * @property {Object.<string,*>} [options] Service options
 * @property {Object.<string,MethodDescriptor>} methods Method descriptors
 * @property {Object.<string,AnyNestedDescriptor>} [nested] Nested object descriptors
 */

/**
 * @typedef MethodDescriptor
 * @type {Object}
 * @property {string} [type="rpc"] Method type
 * @property {string} requestType Request type
 * @property {string} responseType Response type
 * @property {boolean} [requestStream=false] Whether requests are streamed
 * @property {boolean} [responseStream=false] Whether responses are streamed
 * @property {Object.<string,*>} [options] Method options
 */

/**
 * @typedef NamespaceDescriptor
 * @type {Object}
 * @property {Object.<string,*>} [options] Namespace options
 * @property {Object.<string,AnyNestedDescriptor>} nested Nested object descriptors
 */

// VSCode hangs if the following typedef contains more than 5 types (at 5 it just lags a bit):

/**
 * Any nested object descriptor.
 * @typedef AnyNestedDescriptor
 * @type {EnumDescriptor|TypeDescriptor|ServiceDescriptor|ExtensionFieldDescriptor|ExtensionMapFieldDescriptor|NamespaceDescriptor}
 */
```

2. Get a coffee and come back later.

Profile:

![](http://i.imgur.com/T1v8D02.jpg)

I uninstalled all extensions to be sure, but I must admit that I haven't managed to test this on another machine, yet.

**Comment by mjbvz** [comment] 2017-04-05 22:26
Thanks @dcodeIO 

I'm able to reproduce this in 1.11 by copy and pasting in the provided string. From the trace, it looks like  an issue with either the TypeScript grammar or with our vscode-textmate engine and not with the TSServer directly. The TSServer trace also seems to suggest this but I'll confirm. Adding @alexandrudima to see if he has any thoughts here

**Comment by alexandrudima** [comment] 2017-04-06 23:07
TypeScript TM Grammar catastrophic backtracking regex. I can look up the issue I made on their repo ~ last week.

**Comment by mjbvz** [comment] 2017-04-07 00:41
Thanks @alexandrudima! Looks like this is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/435

**Closed by mjbvz** 2017-04-07 00:41 UTC
Labels: freeze-slow-crash, javascript, typescript, upstream
