### ISSUE TITLE
[Themes] `editorGroup.emptyBackground` makes commands illegible

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [microsoft/vscode#151184] opened 2022-06-03 00:33 UTC
Issue Type: <b>Bug</b>

1. Create a theme, or setting, that assigns `editorGroup.emptyBackground` to any opaque color (example below `#f8eff8`).

Actual result:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/6189778/171761593-c27d413e-e25f-4253-9023-4922a79a2e54.png">

Expected result:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/6189778/171761527-998677c2-825f-45ea-9a1f-86d992410381.png">

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 01677fdc-9726-42ce-bf2a-61d644ca3b62|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by bpasero** [comment] 2022-06-08 16:03
This is coming in from `src/vs/workbench/contrib/watermark/browser`

//cc @chrmarti

**Comment by bpasero** [comment] 2022-06-11 13:25
@lramos15 I think the fix is not good, I saw a slow editor loading and the watermark was shining through. I think with your change now, there is a time when the new editor is not yet there but the watermark is on top. Typically the watermark should go away as soon as a new editor starts to load, please check.

**Comment by lramos15** [comment] 2022-06-11 14:31
@bpasero Any ideas how I can reproduce a slow editor loading? Even open slower custom editors like the hex editor on my computer doesn't seem to cause any issues

**Comment by bpasero** [comment] 2022-06-11 14:56
![Recording 2022-06-11 at 16 55 46](https://user-images.githubusercontent.com/900690/173192988-23cb76ab-4d9e-450f-92fc-4bfb7ba40a71.gif)

I typically add this in `textFileEditorModel.resolve`:

```ts
if (this.resource.fsPath === '/Users/bpasero/Documents/ticino-playground/Features.ts') {
			await timeout(10000);
		}
```

**Comment by lramos15** [comment] 2022-06-28 14:11
I've reverted the Z-index change due to the watermark still showing on slow editor loads will investigate next milestone. Appears that the letter press and command hints are on two separate style sheets entirely.

**Comment by bhavyaus** [comment] 2023-12-19 18:45
This is fixed with recent changes to the watermark rendering.

**Closed by bhavyaus** 2023-12-19 18:45 UTC
Labels: bug, workbench-welcome, confirmed
