### ISSUE TITLE
ipynb files will no longer open without maximizing the VS code panel first

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#106673] opened 2020-09-14 17:12 UTC
- VSCode Version: 1.49
- OS Version: Windows 10

Steps to Reproduce:

1. Install Python extension
2. Open an ipynb file
3. Ipynb file will not generate any output (webview is empty) 
4. Command palette: 'Toggle Maximized Panel'
5. Open ipynb again
6. It suddenly works.

See this bug for more information:
 https://github.com/microsoft/vscode-python/issues/13901

Note this issues was also mentioned in https://github.com/microsoft/vscode/issues/106547 but hidden in the problem with URIs.

I also can't repro this with the cat coding example.

Does this issue occur when all extensions are disabled?: No

**Comment by rchiodo** [comment] 2020-09-14 17:14
Dupe of  #106587

**Comment by mjbvz** [comment] 2020-09-17 16:04
@rchiodo Can you investigate on the python side what isn't working. I don't see this with other custom editors in my testing

**Comment by rchiodo** [comment] 2020-09-17 17:34
Looking now. 

I can repro with our stable bits. 

Using our latest (main branch) bits it doesn't seem to be reproing. Still doing more testing as that doesn't make any sense. There shouldn't be any difference in our custom editor support between the two other than the enabling of the experiment.

**Comment by rchiodo** [comment] 2020-09-17 17:36
With our insider's branch (debug bits) there's a delay before the UI shows up. Almost like there's some sort of refresh that causes our HTML to be loaded.

**Comment by rchiodo** [comment] 2020-09-17 17:45
That might explain why the maximize panel workaround fixes it. It forces the refresh to occur.

**Comment by rchiodo** [comment] 2020-09-17 18:27
I can't repro with our latest bits even without debugging. Something else we did must have fixed this. It even works in stable with our latest bits.

**Comment by mjbvz** [comment] 2020-09-17 18:31
Ok, I confirmed that VS Code's call to `resolveCustomTextEditor` does not return until after the panel is maximized. The specific place we are waiting in the Python extension seems to be on this line:

<img width="1032" alt="Screen Shot 2020-09-17 at 11 28 37 AM" src="https://user-images.githubusercontent.com/12821956/93512431-26c11080-f8d9-11ea-8b12-314a650790b4.png">

**Comment by rchiodo** [comment] 2020-09-17 18:40
That explains it. I thought that was changed prior to our last release but it wasn't. There was a deadlock there with custom editor that we fixed about a month ago.
https://github.com/microsoft/vscode-python/commit/55b4573830f28f5c121a186230cd1265c7fca010#diff-9e5e7ee5707f9ac86acd62e81b582874

Thanks for tracking it down.

**Comment by mjbvz** [comment] 2020-09-18 18:19
Ok, closing this as an upstream issue then. Please test out the latest VS Code insiders and let me know if there are still any custom editor issues

**Closed by mjbvz** 2020-09-18 18:19 UTC
Labels: custom-editors, needs more info
