### ISSUE TITLE
How to rebind alt+click ?

### ISSUE THREAD

**Issue by natostanco** [Microsoft/vscode#6879] opened 2016-05-25 16:05 UTC
- VSCode Version: 1.1.1
- OS Version: linux 

The list of default keyboard shortcuts does not include `alt+click` or any other `click` commands. Is it possible to rebind them?

**Comment by Tyriar** [comment] 2016-05-25 17:43
Duplicate of #3091 and #3130

**Closed by Tyriar** 2016-05-25 17:43 UTC
