### ISSUE TITLE
Settings Editor overlaps with editor group highlight

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#194582] opened 2023-10-02 03:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

The bottom of the setting editor overlaps with the border of the editor group

![Image](https://github.com/microsoft/vscode/assets/876920/0fac6b1e-1a6e-43b3-9aed-bc6c4260eb37)

**Comment by rzhao271** [comment] 2023-10-02 17:24
Duplicate of #183503

**Closed by rzhao271** 2023-10-02 17:24 UTC
Labels: bug, settings-editor
