### ISSUE TITLE
Downloads under metered connection

### ISSUE THREAD

**Issue by AlexJPawlak** [microsoft/vscode#75195] opened 2019-06-10 11:03 UTC
Issue Type: <b>Feature Request</b>

Hello! Many Windows Apps honor metered connection and ask if they can download stuff in the background - VSCode went all in and just started downloading stuff it was missing. At the time it was fine for me as I'm on nearly unlimited metered plan, but for others it might be not so pleasant experience. 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mittalyashu** [comment] 2019-06-10 11:28
Maybe the title can be "Downloads under metered connection" @AlexJPawlak

**Comment by egamma** [comment] 2019-06-11 06:47
Duplicate of #60741

**Closed by egamma** 2019-06-11 06:47 UTC

**Comment by mittalyashu** [comment] 2019-06-11 07:26
Here's the issue created for the first time https://github.com/microsoft/vscode/issues/8540 and it was marked as out of scope.

@egamma @AlexJPawlak

**Comment by AlexJPawlak** [comment] 2019-06-11 20:12
OK - so #8540 was out of scope for that iteration, I get it. 3 years passed. The topic was picked up #60741 without being delivered without explanation. I would like to understand a bit more your reasoning behind it, as I'd not like to waste either your or mine time and still provide comments or feedback. Or is it misleading and you don't want new ideas?
#62615 said PR are welcome but otherwise this is out of scope. What is in scope and where can I read more on that? So my suggestions are more relevant for future. 

 @egamma  @mittalyashu

**Comment by mittalyashu** [comment] 2019-06-12 04:36
I understand how it felt when we post a feature request and it turns out to be out of scope.

It has also happened with me a few times, once I have posted a feature request for duplicating file and folder even though that feature should be part of every text editor but the reply from VS Code team was that this functionality can be extended by an extension and later they marked the issue as out of scope.

> I'd not like to waste either your or mine time and still provide comments or feedback. Or is it misleading and you don't want new ideas?

The idea is very good, even the Atom uses the similar concept of metered connection as it shows the list of plugins which can be updated.

> #62615 said PR are welcome but otherwise this is out of scope. What is in scope and where can I read more on that? So my suggestions are more relevant for the future.

A few months back VS Code started grooming the issues just to decrease the number of open issues that is one of the most few of the best issues were closed too.
