### ISSUE TITLE
More rounded corners in VS Code please!

### ISSUE THREAD

**Issue by 97I8TOE47K** [microsoft/vscode#145193] opened 2022-03-16 08:23 UTC
I believe that there are various places where rounded corners can be implemented, like buttons, drop-down buttons and hovers. This can give a really nice look to VS Code.

**Comment by gjsjohnmurray** [comment] 2022-03-16 08:48
Related to #144962

**Comment by IllusionMH** [comment] 2022-03-16 10:24
/duplicate of #140072 which is linked to #115641

**Closed** 2022-03-16 10:25 UTC
Labels: *duplicate, triage-needed
