### ISSUE TITLE
Git in Visual Studio Code removed all of files (source and images)

### ISSUE THREAD

**Issue by dnnabatame** [microsoft/vscode#80439] opened 2019-09-06 00:32 UTC
Issue Type: <b>Bug</b>

Visual Studio code (perhaps Git feature)  said to me that some changes has not tracked, and I pressed the button for "remove the change" and Git did "clear command" and cleared all of python and other files.
Actually I didn't use Git so I didn't think anything happen, but most of source code were cleared.  And I could not revert it!

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.16299

**Comment by benny-medflyt** [comment] 2019-09-07 18:14
This looks like a duplicate of #32405

**Comment by joaomoreno** [comment] 2019-09-10 09:36
https://github.com/microsoft/vscode/issues/32405#issuecomment-322155856

**Closed by joaomoreno** 2019-09-10 09:36 UTC
