### ISSUE TITLE
Git changes overlaps code folding arrow

### ISSUE THREAD

**Issue by notiv-nt** [microsoft/vscode#90755] opened 2020-02-15 14:11 UTC
- VSCode Version: 1.42.1
- OS Version: MacOS 10.14.6

Does this issue occur when all extensions are disabled?: Yes

![74589330-66f3a400-5015-11ea-9b81-e69be154be12](https://user-images.githubusercontent.com/10743009/74589365-cb166800-5015-11ea-93b5-023b6fd0e539.png)

Is there any way to hide this changes "button" (not the whole line)

-----
As a temporary solution, I moved this line to the left
```css
.monaco-editor .dirty-diff-glyph {
  left: 0px !important;
}
```

<img width="268" alt="Screen Shot 2020-02-15 at 9 08 23 PM" src="https://user-images.githubusercontent.com/10743009/74592963-856a9700-5037-11ea-9e17-5f19f1c7b267.png">
but still there’s very little space for this line

**Comment by notiv-nt** [comment] 2020-02-15 14:15
Still relevant
https://github.com/microsoft/vscode/issues/36237
https://github.com/microsoft/vscode/issues/36470#issuecomment-337973333

**Comment by gjsjohnmurray** [comment] 2020-02-15 17:32
Have you set any `scm.diffDecorations*` settings at user level or workspace level?

**Comment by notiv-nt** [comment] 2020-02-15 17:33
@gjsjohnmurray no

**Comment by gjsjohnmurray** [comment] 2020-02-15 17:35
Does it also happen with all extensions disabled? And with one of the default themes?

**Comment by notiv-nt** [comment] 2020-02-15 17:40
@gjsjohnmurray yes

**Comment by gjsjohnmurray** [comment] 2020-02-15 17:50
Re hiding, see https://stackoverflow.com/questions/43969277/how-can-you-disable-gutter-indicators-in-vs-code

**Comment by notiv-nt** [comment] 2020-02-15 17:57
I dont need to hide the whole line

**Comment by gjsjohnmurray** [comment] 2020-02-17 11:19
@notiv-nt do I understand correctly that you don't like how a section of the vertical marker bar widens out to become a sort of button when you hover over it? And/or that you don't like how this effect overlays the left of the folding marker if there is one on the relevant line?

**Comment by notiv-nt** [comment] 2020-02-17 11:25
@gjsjohnmurray the second one
it's just not convenient, I click on the arrow but for some reason changes open

**Comment by gjsjohnmurray** [comment] 2020-02-17 11:43
@notiv-nt odd that your click seems to hit the wrong target. I couldn't reproduce that, but I am on Windows rather than Mac.

As a workaround does this setting help?

```
"scm.diffDecorationsGutterWidth": 1
```

**Comment by notiv-nt** [comment] 2020-02-17 11:46
@gjsjohnmurray 
![image](https://user-images.githubusercontent.com/10743009/74651112-2ec69f80-5194-11ea-9ac8-c24e01dd1792.png)
a bit

**Comment by gjsjohnmurray** [comment] 2020-02-17 12:15
Interesting! I expected a 1px line above and below the wider bit. Here's what I see:

![image](https://user-images.githubusercontent.com/6726799/74652827-d0db8d00-517e-11ea-8ea3-3609058a514e.png)

Perhaps your display is high DPI?

**Comment by notiv-nt** [comment] 2020-02-17 12:18
@gjsjohnmurray the same behaviour on the external display

**Comment by gjsjohnmurray** [comment] 2020-02-17 12:23
@notiv-nt what does your slook like with  this setting?

```
"scm.diffDecorationsGutterWidth": 2
```

**Comment by notiv-nt** [comment] 2020-02-17 12:25
@gjsjohnmurray this option does not affect the button

**Comment by gjsjohnmurray** [comment] 2020-02-17 12:31
@notiv-nt yes, I know. But for me a smaller value prevents overlap with the fold control:

1px:

![image](https://user-images.githubusercontent.com/6726799/74654054-5e1fe100-5181-11ea-94aa-f918e394a1a9.png)

3px (default):

![image](https://user-images.githubusercontent.com/6726799/74654106-798aec00-5181-11ea-81bd-9be410a30fa5.png)

**Comment by joaomoreno** [comment] 2020-02-18 08:43
This is known and simply tolerated, since there is no official editor API to contribute lanes to the gutter. Also, both areas are easily clickable. Closing as won't fix.

**Comment by notiv-nt** [comment] 2020-02-18 10:07
@joaomoreno sometimes

**Closed** 2020-11-11 15:49 UTC
Labels: bug, wont-fix
