### ISSUE TITLE
Breakpoint in collapsed code is visible, but not usable

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#22300] opened 2017-03-09 14:26 UTC
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

Given:
```js
function f() {
    return 0;
}
```

1. Add a breakpoint at the `return` statement.
2. Collapse the function.
3. The breakpoint is still visible.
4. Right-click on it.
5. This gives me an option to "Add breakpoint". But I want to remove it.

**Comment by isidorn** [comment] 2017-03-10 10:30
Duplicate of https://github.com/Microsoft/vscode/issues/4812

**Closed by isidorn** 2017-03-10 10:30 UTC
Labels: debug
