### ISSUE TITLE
Allow to use Ctrl P/N for up and down navigation in quick open

### ISSUE THREAD

**Issue by kai-iak** [Microsoft/vscode#7876] opened 2016-06-20 02:36 UTC
- VSCode Version: 1.2.1
- OS Version: 10.11.5

Steps to Reproduce:
1. Invoke command palette
2. Begin typing a query i.e. ext
3. Attempt to move up/down the list with ctrl+p and ctrl+n

I installed the latest version of VS Code (1.2.1) on El Capitan. When I used the Atom (and ST2?) text editor and invoked the command palette I could cursor up/down the list using ctrl+p/ctrl+n.

For example, if I launch the command palette and search for extension I get the following list:

```
Extensions: Install Extension
Extensions: Show Extension Recommendations
Extensions: Show Installed Extensions
Extensions: Show Outdated Extensions
```

If I want to get to 'Show Installed Extensions' I would press ctrl+n twice in Atom. When I try doing this with VS Code nothing happens. In looking at the Default Keyboard Shortcuts there are:

```
{ "key": "ctrl+p", "command": "cursorUp", "when": "editorTextFocus" },
{ "key": "ctrl+n", "command": "cursorDown", "when": "editorTextFocus" },
```

**Comment by joaomoreno** [comment] 2016-07-06 13:53
Fixed by #7316

**Comment by joaomoreno** [comment] 2016-09-09 07:39
@bpasero Adding you since the changes are quick open widget, not in the tree.

**Comment by elemongw** [comment] 2016-10-11 19:22
@joaomoreno I can create a new patch to make it work as you liked (not needing enter to select). However my opinion on the matter is that it shouldn't work that way, ctrl+p/ctrl+n work universally as up and down arrows on mac (this is true for vscode too apart from quickOpenWidget as only part of my patch was reverted).

**Comment by wardw** [comment] 2016-12-21 13:58
Yes, useful to note that ctrl+p/ctrl+n work nicely when navigating the auto-complete popup. I agree with @elemongw that certainly on a mac, ctrl+p/ctrl+n are common aliases for up/down everywhere. I've always taken this as being originally of emacs heritage, so this behaviour is common on linux, too.

**Comment by bpasero** [comment] 2017-01-19 06:57
I added new commands `workbench.action.quickOpenSelectNext` and `workbench.action.quickOpenSelectPrevious` which on macOS are bound to `Ctrl+N` and `Ctrl+P` by default and work only when quick open is visible. 

The difference to the commands `workbench.action.quickOpenNavigateNext` and `workbench.action.quickOpenNavigatePrevious` is that upon releasing the key, the item will be opened.

**Closed** 2017-01-19 06:59 UTC
Labels: feature-request, verification-needed, workbench

**Comment by bpasero** [comment] 2017-01-23 17:53
**To verify:** 
On macOS you can use Ctrl+N and Ctrl+P to navigate inside the opened quick open up and down, similar to arrow up and arrow down.

**Comment by jrieken** [comment] 2017-01-24 16:05
@bpasero also `cmd+p` navigates in quick open (instead of changing the quick open topic to open file). Is that a regression from this?

**Comment by bpasero** [comment] 2017-01-24 16:26
@jrieken no this is actually behaviour we have ever since quick navigation in quick open to make @joaomoreno happy because he uses `Cmd+E` to bring up quick open and another `Cmd+E` to quickly open the element. 

Can be controlled via 
`
{ "key": "cmd+p", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }`

**Comment by jrieken** [comment] 2017-01-24 16:43
Unsure how this is related to `cmd+e`? I am talking about `cmd+p`. Do the following

* hit cmd+p, see file picker
* while file picker shows, hit F1, see command picker
* while command picker shows, hit cmd+p, some item selected

**Comment by bpasero** [comment] 2017-01-25 08:16
I removed Cmd+P and Cmd+E to select and execute the command when quick open is visible. The commands are still there if someone wants to keep it. Also fixes https://github.com/Microsoft/vscode/issues/10957

**Comment by danielmoi** [comment] 2017-02-02 19:39
Thank you for this fix @bpasero – my favourite feature in this release!
