### ISSUE TITLE
Takes long time to close large files, even when not saving

### ISSUE THREAD

**Issue by doorman02** [Microsoft/vscode#44130] opened 2018-02-21 14:35 UTC
### Issue Type
Bug

### Description

I have a 5 mb xml file that I need to view. When I close the file it takes couple of seconds to close.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.89GB (3.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
PowerShell|ms-|1.5.1

</details>
Reproduces only with extensions

**Comment by rebornix** [comment] 2018-02-22 05:37
@doorman02 is it possible that you can share the file or a similar file that can reproduce this issue?

**Comment by doorman02** [comment] 2018-02-22 09:55
Hi @rebornix I don't think it's the file. I searched for another large xml file on my harddrive and I found a 8mb file. The steps I am taking:

1. Drag and drop file into Visual Code
2. Press Alt + Shift + F to format the xml file.
3. Close file without saving changes, takes more than 30 seconds.

I have installed Xml Tools 1.9.2 extension for formatting xml. Could the problem be related to that?

**Comment by doorman02** [comment] 2018-02-22 20:18
Hi @rebornix  seems the issue is with the xml extension. If I don´t format the xml file it closes immediately. So I opened another bug issue here https://github.com/DotJoshJohnson/vscode-xml/issues/143

**Comment by doorman02** [comment] 2018-03-05 10:18
Hi, the author of the xml extension verified that the extension was not causing this hence re-opening the issue. For more info of what has been tested: https://github.com/DotJoshJohnson/vscode-xml/issues/143#event-1500453678

**Comment by rebornix** [comment] 2018-03-05 19:31
@doorman02 sorry didn't notice your last comment of the reproduce steps. It was caused by our file syncing code and it should be fixed now in Insider and you'll have it once we release a new Stable.

**Closed by rebornix** 2018-03-05 19:31 UTC
Labels: editor, needs more info

**Comment by doorman02** [comment] 2018-03-05 19:34
Great thanks :)
