### ISSUE TITLE
Unit test failure: FileQueryCacheState

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#162329] opened 2022-09-29 11:29 UTC
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=187155&view=results

```
1) FileQueryCacheState
       reuse old cacheKey until new cache is loaded:
     
  



2022-09-29T10:47:59.171Z pw:browser [pid=22999] <gracefully close start>
2022-09-29T10:47:59.686Z pw:browser [pid=22999] <process did exit: exitCode=0, signal=null>
2022-09-29T10:47:59.686Z pw:browser [pid=22999] starting temporary directories cleanup
2022-09-29T10:47:59.784Z pw:browser [pid=22999] finished temporary directories cleanup
2022-09-29T10:47:59.784Z pw:browser [pid=22999] <gracefully close end>
The followings tests are failing:
 - FileQueryCacheState reuse old cacheKey until new cache is loaded (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)
```

**Comment by bpasero** [comment] 2022-09-29 12:41
Heads up that I am not 100% convinced its an issue with the actual test. See https://github.com/microsoft/vscode/issues/162102 for a similar case.

**Comment by TylerLeonhardt** [comment] 2022-10-24 11:39
I will close this as a dupe of https://github.com/microsoft/vscode/issues/162102 until we have more info.

**Closed by TylerLeonhardt** 2022-10-24 11:39 UTC
Labels: unit-test-failure, web
