### ISSUE TITLE
Intellisense for class methods is not working

### ISSUE THREAD

**Issue by ebeloded** [Microsoft/vscode#28258] opened 2017-06-08 22:36 UTC
When I create a class by extending another class or implementing an interface, the editor doesn't offer any helpful suggestions.

Typescript Service can show an error when abstract methods are not implemented, or if method signature is incorrect, but there is no help from the editor when I'm in the process of implementing the class.

An obvious example of this is implementing React Components. I expect that when I trigger suggest within the class implementation, I would see all of ComponentLifecycle methods with their signatures. However, when I invoke the suggest widget, it shows a host of things in there, none of which are helpful, and none of those I need are actually present.

![screen shot 2017-06-09 at 05 01 56](https://user-images.githubusercontent.com/5859177/26952827-51c839e6-4cd1-11e7-9821-3f57c4a57c8a.png)

Is this a bug or am I doing something wrong? I tried it with the new TypeScript-React-Starter project, but the behavior was the same.

- VSCode Version: 1.12.2 
- OS Version: MacOS Sierra

**Comment by mjbvz** [comment] 2017-06-09 19:52
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/7158

This is fixed in the latest TypeScript 2.4 insiders which we will pick up for VSCode 1.14:

![screen shot 2017-06-09 at 12 51 00 pm](https://user-images.githubusercontent.com/12821956/26992196-5d288782-4d12-11e7-9d9f-f49c41814e73.png)

TS 2.4 should be in the VSCode insiders builds sometime next week

**Closed by mjbvz** 2017-06-09 19:52 UTC
Labels: duplicate, upstream

**Comment by mehwww** [comment] 2017-07-26 08:10
Still not working here
VSCode version: 1.14.2
