### ISSUE TITLE
Use Workspace Typescript causes settings to be ill-formatted

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12669] opened 2016-09-26 18:42 UTC
- VSCode Version: 1.6 Insiders
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Open a TS project and receives this notification
   ![image](https://cloud.githubusercontent.com/assets/4033249/18844463/2d3f7210-83d2-11e6-85f6-06b3a80e1623.png)
   Then click "Use Workspace Typescript"
2. Diff for `settings.json`

![image](https://cloud.githubusercontent.com/assets/4033249/18844491/4ae130a6-83d2-11e6-9ca5-4c486338316a.png)

**Comment by octref** [comment] 2016-10-25 16:37
@aeschli 

This still happens. Particularly any setting added right after a setting of list `[]` is ill-formatted.

**Comment by aeschli** [comment] 2017-01-26 10:02
duplicate of #19136

**Closed by aeschli** 2017-01-26 10:02 UTC
Labels: bug
