### ISSUE TITLE
Feature request: Add ability to center the display in Zen Mode

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode#35914] opened 2017-10-09 14:39 UTC
- VSCode Version: 1.18 Insiders
- OS Version:  OSX 10.12.6 Sierra

Steps to reproduce: Activate Zen Mode - Cmd K + Z

At the moment, in order to achieve the desired visual effect, I have to use the `split editor` feature and open a dummy file. It would be really good if there was a configurable way of getting the Zen Mode option to center/left pad the display.

![screen shot 2017-10-09 at 15 41 30](https://user-images.githubusercontent.com/260612/31343610-025e1cf8-ad08-11e7-8af5-b8714dfc918b.png)

**Comment by mjbvz** [comment] 2017-10-09 15:11
Duplicate of #15684

**Closed by mjbvz** 2017-10-09 15:11 UTC
Labels: duplicate, workbench
