### ISSUE TITLE
CSS: Complete property with semicolon setting does nothing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99080] opened 2020-06-02 12:42 UTC
Testing https://github.com/microsoft/vscode/issues/98900

I see no change at all when toggling `css.completion.completePropertyWithSemicolon`

![recording (8)](https://user-images.githubusercontent.com/22350/83521484-97395280-a4df-11ea-9e14-b265590742a4.gif)

**Comment by aeschli** [comment] 2020-06-02 15:16
This is caused by a bug in css which I fixed through hhttps://github.com/microsoft/vscode/issues/99108

**Comment by aeschli** [comment] 2020-06-02 15:17
marking as dup of #99108

**Closed by aeschli** 2020-06-02 15:17 UTC
Labels: bug

**Comment by dennisfhelt** [comment] 2020-06-17 23:40
I still can't keep the semicolon from automatically inserting itself even after unchecking the Complete Property With Semicolon box. I'm running it on Windows 10.
![semicolon-problem](https://user-images.githubusercontent.com/31455409/84961336-a5839300-b0c9-11ea-8d46-04d276e3a273.jpg)

**Comment by gorjiali** [comment] 2020-06-26 12:07
same problem

**Comment by aeschli** [comment] 2020-06-29 07:12
fixed by https://github.com/microsoft/vscode/issues/100684
