### ISSUE TITLE
I know its free and its Great BUT can you fix the middle click issue on Linux please?

### ISSUE THREAD

**Issue by i-frost** [Microsoft/vscode#16047] opened 2016-11-25 02:34 UTC
- VSCode Version:the latest
- OS Version:
Arch latest
Steps to Reproduce:
run vscode and select some thing and try and mouse middle click to paste it!
1. 
2.

**Comment by i-frost** [comment] 2016-11-25 02:37
It seems to be completly oblivious to what I have selected and tried to paste, it just paste something I copied with cntrl  C, sometime ago.

Please fix this its driving me nuts, I know you guys dont have much time but this a fundamental feature of Linux, I know its not a Microsoft Win Feature but it is amazing!

**Comment by rozzzly** [comment] 2016-11-27 23:18
Use `xbindkeys` (PROtip: xbindkeys_config, nice gui) to run something like `xmacroplay` which sends synthetic keystrokes to the focused input. I have a Logitech G700s mouse that has a total of 18 buttons/ways you can move the mouse. I also run Arch, if you want, I will share my configs.

**Comment by i-frost** [comment] 2016-11-27 23:44
Yes please rozzzly I can try your config, it seems to have been looked at as it is a little better, it works sometimes but not others.
If it doesn't work and I then go back and select text again and re-try middle click it works on second attempt consistently, not sure why it does not on first attempt.

**Comment by alexandrudima** [comment] 2016-11-30 09:34
@i-frost This is implemented behind the `editor.selectionClipboard` option, which is `true` by default, and it should be working. Is it possible you have some sort of special setup where the selection clipboard would not work in general, or is this perhaps a regression from our latest Electron update. @Tyriar does this feature still work for you? 

Implemented at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/selectionClipboard/electron-browser/selectionClipboard.ts#L19

**Comment by Tyriar** [comment] 2016-11-30 18:23
I've used it pretty much daily since it was added and it's never stopped working for me.

**Comment by i-frost** [comment] 2016-11-30 21:11
I checked my settings files and it was not set so I added it to my json file for good measure and it appears to be working fine now!

Thanks

**Comment by Tyriar** [comment] 2016-11-30 21:31
That's strange, it's been the default for several versions :confused:

**Comment by i-frost** [comment] 2016-11-30 21:56
Yer the whole scenario has been strange but it is working now so I'm happy!

I also did a OS update today and rebooted so maybe that fixed it.

**Comment by i-frost** [comment] 2016-11-30 22:42
Sadly I spoke too soon, it just did it again.

I right clicked on a function name and selected 'find all references' had a
look at the list in the reference window and then selected a module import
line in file on other window pane and then middle clicked to paste line
into a file I had done the find references in, but it pasted the function
name I was looking for references instead of the selected line. Although I
could clearly see in the other window the module line was selected.

I have 2 windows open side by side.

Strange thing is I cannot repeat the action if I redo what I described!

But it is much better than yesterday, so that is good:-)

**Comment by alexandrudima** [comment] 2016-12-01 09:18
@i-frost Given this works for you after the OS update / reboot I will close this issue for now. If you find specific steps which reproduce the last problem you've spotted, please reopen the issue.

**Closed by alexandrudima** 2016-12-01 09:19 UTC
Labels: linux, needs more info

**Comment by i-frost** [comment] 2017-01-17 09:54
Can you help me find out what is doing this please, I am getting pretty frustrated with it happening.

It as become worse since upgrading to :

Version 1.8.1
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by i-frost** [comment] 2017-01-17 10:56
If I use xorg-xsel to display what is in the current selection it does not correspond to the text I have just selected in the VScode window., if I then re-select the text it works.

This is not consistently happening and I can not recreate it on demand, but there must be a bug and I am using VScode 24/7 at the moment and its getting really annoying playing the pasting lottery!

It does not happen when selecting and pasting on the terminal or other apps, only if I have selected some text in the VScode window and try and paste it elsewhere.

**Comment by alexandrudima** [comment] 2017-01-21 01:07
@i-frost Maybe https://github.com/Microsoft/vscode/issues/17349#issuecomment-267882217 helps?

**Comment by i-frost** [comment] 2017-01-21 06:11
I'm not sure its the same thing as my problem.

I am not using tmux and my issue is just so random. sounds like the  #17349
<https://github.com/Microsoft/vscode/issues/17349#issuecomment-267882217> issue
is either working or not.

Also  ctrl+c ctrl+v works its just the middle mouse click which has the
random issue.

Thanks
