### ISSUE TITLE
VSCode hangs on Drag

### ISSUE THREAD

**Issue by britalmeida** [Microsoft/vscode#60094] opened 2018-10-07 10:47 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:
 - Drag a file tab (as if to reorder) or drag a watch variable.

Result:
VSCode will hang as soon as the drag starts. I can see the dragged item being painted next to the mouse cursor which retains the closed hand symbol.
VSCode now is irresponsive and has to be manually killed.

VS Code version: code-oss-dev 1.29.0 (Commit 82192c3bcb, Date 07/Oct/2018)
OS version: Linux x64 4.4.38

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3097)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.66GB (0.92GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
python|ms-|2018.8.0
cpptools|ms-|0.19.0
sublime-keybindings|ms-|4.0.0
vscode-icons|rob|7.27.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

(5 theme extensions excluded)

</details>

**Comment by britalmeida** [comment] 2018-10-07 13:55
Suggested issue #9915 seems unrelated.

**Comment by RMacfarlane** [comment] 2018-10-07 16:11
Duplicate of https://github.com/Microsoft/vscode/issues/57766

Try launching code with the `--disable-gpu` flag

**Closed by RMacfarlane** 2018-10-07 16:11 UTC
Labels: editor, editor-contrib
