### ISSUE TITLE
Feature Request: R language extension

### ISSUE THREAD

**Issue by asdncg** [Microsoft/vscode#11393] opened 2016-09-01 13:41 UTC
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:
1. 
2.

**Comment by asdncg** [comment] 2016-09-18 18:26
when?

**Comment by rwatts3** [comment] 2017-05-31 17:16
Will there be support for intellisense in R ? 
If so is there an expected timeline?

@chrisdias

**Comment by rwatts3** [comment] 2017-06-20 21:23
Wondering if we can get an update or info on whether or not this feature request will be honored.

**Comment by hoovercj** [comment] 2017-07-11 12:49
Is this a duplicate of #14393?

**Comment by mjbvz** [comment] 2017-11-02 20:56
Duplicate of #14393

**Closed by mjbvz** 2017-11-02 20:56 UTC
Labels: duplicate, extension-candidate, feature-request
