### ISSUE TITLE
Settings Sync cannot login whilst in SSH session

### ISSUE THREAD

**Issue by EricChen1248** [microsoft/vscode#104879] opened 2020-08-18 02:16 UTC
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install SSH remote extension
2. Connect SSH to remote host.
3. Attempt to sign in to settings sync

Does this issue occur when all extensions are disabled?: Yes/No
N/A, requires extension

**Comment by sandy081** [comment] 2020-08-19 16:17
What do you mean by cannot log in? At which step it is not working? Do you see any errors?

**Comment by zhenhua32** [comment] 2020-08-20 01:03
I have same question.

**Comment by RMacfarlane** [comment] 2020-08-25 18:24
Closing as a duplicate of https://github.com/microsoft/vscode/issues/104628

**Closed by RMacfarlane** 2020-08-25 18:24 UTC
