### ISSUE TITLE
Workspace: possible to have a file as path entry now

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#46014] opened 2018-03-17 07:25 UTC
Probably a consequence of fixing https://github.com/Microsoft/vscode/issues/44809

Steps to Reproduce:

1. add a file as workspace root

=> it shows up in the explorer and you can actually open it

![image](https://user-images.githubusercontent.com/900690/37552835-c43cd5a4-29bc-11e8-9027-4a027529644e.png)

We should imho not allow that and decorate this entry similar to a root folder but with an error. That goes into the direction of fixing https://github.com/Microsoft/vscode/issues/35092

**Comment by isidorn** [comment] 2018-03-19 09:30
I can not reproduce this. Here's what happens to me when I try to add a file to the workspace configuration file.
Are you doing something special for this or you simply edit the configuration file to point to a file.

Also that fix should have no effect on this behavior, I only changed the error notification, not the error propagation.

![screen shot 2018-03-19 at 10 29 15](https://user-images.githubusercontent.com/1926584/37587738-6c107e62-2b60-11e8-96b8-ffa1cd4702e6.png)

**Comment by bpasero** [comment] 2018-03-19 09:36
@isidorn reproduces for me in todays insider build:
* save a workspace
* open workspace file
* add package.json from that workspace folder

![image](https://user-images.githubusercontent.com/900690/37588041-567389e0-2b61-11e8-99d6-07f9d1bafd5a.png)

**Comment by bpasero** [comment] 2018-03-27 10:35
@isidorn a file now shows up like a normal folder even though it is not. you even see all the actions but none work:

![image](https://user-images.githubusercontent.com/900690/37962429-5c4c9e78-31bb-11e8-97d3-fe0cabba2c69.png)

I think we should show a decoration to indicate the root folder is invalid.

**Comment by bpasero** [comment] 2018-03-28 13:56
Maybe this is a timing issue again I think the decoration came in after a window reload.

**Comment by isidorn** [comment] 2018-03-28 17:19
The issue is [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerModel.ts#L121)

Namely my check if something is a nonexistent root requires that it is a directory and that it is not yer resolved. Which is wrong it should be nonexistent if it is a root and an error happened
Not something I want to change in endgame -> april

**Comment by isidorn** [comment] 2018-06-25 14:30
This is fixed in the latest and will be availble in tomorrow's insiders

**Closed by isidorn** 2018-06-25 14:30 UTC
Labels: bug, multi-root, verification-found
