### ISSUE TITLE
Debug toolbar contributed action not visible for custom group

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#69394] opened 2019-02-25 18:47 UTC
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69196

This might be the same root cause as https://github.com/Microsoft/vscode/issues/69340, but when adding a command with a group besides "navigation", the command is not visible

```
	"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		],
		"menus": {
			"debug/toolbar": [
				{
					"command": "extension.helloWorld",
					"group": "myGroup"
				}
			]
		}
	}
```

VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.2.0

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
gitlens|eam|9.5.1
vscode-pull-request-github-insiders|Git|1.56.0
graphql-for-vscode|kum|1.13.0
vscode-language-pack-de|MS-|1.32.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.2
polacode|pnp|0.2.2

</details>

**Comment by isidorn** [comment] 2019-02-26 08:34
Same root cause as the other issue, though still marking it as a bug so you can verify on latest insiders. THanks!

**Closed by isidorn** 2019-02-26 08:34 UTC
Labels: bug, debug
