### ISSUE TITLE
Terminal rendering is buggy

### ISSUE THREAD

**Issue by FGC-Hemang-Joshi** [microsoft/vscode#232117] opened 2024-10-24 05:15 UTC
Type: <b>Bug</b>

When my terminal has some output printed (eg.: via console log statements), it becomes buggy when I scroll through the output. Particularly, when the output is multi-lined, some of the lines duplicate while scrolling, making it hard to read the output.
Only when the output gets rendered for the first time, it appears proper/correct. if i resize the terminal window and scroll through previous outputs on the terminal, this bug starts appearing of lines getting duplicated. please resolve this ASAP. I have been noticing this bug since many months now.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631

**Comment by meganrogge** [comment] 2024-10-24 12:38
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-10-24 12:38 UTC
