### ISSUE TITLE
Terminal scrolling disabled after quitting vim

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#11234] opened 2016-08-30 17:18 UTC
Testing #11134.

- VSCode Version:  08/30 insiders
- OS Version: MacOS

Steps to Reproduce:
1. open integrated terminal
1. run a command with a long output such as `npm list -g`
1. open a long file in `vi` 
1. within vi enter `:q`
1. no scrollbar, mouse scrolling doesn't work anymore
1. resize the window
1. everything is back to working as expected

**Comment by Tyriar** [comment] 2016-08-31 21:26
Duplicate of #11244

**Closed by Tyriar** 2016-08-31 21:26 UTC
Labels: bug, integrated-terminal
