### ISSUE TITLE
[scss-css] Semicolon auto close & list of CSS property values (missing some atom's features)

### ISSUE THREAD

**Issue by evileyez** [Microsoft/vscode#34439] opened 2017-09-15 08:15 UTC
- VSCode Version: v. 1.16
- OS Version: Win 10 x64

I used to code my front-end in atom.io but now I've moved to VS Code and I really like it! I have in VS Code almost all features that atom.io has. But still missing 2 of them and no plugins or configs can help me as I understand.
So, they are: semicolon autoclose & list of CSS property values as it is performed in atom. Some screenshots are below:

First, I type a CSS property some letters, than select one I need and push Enter. And then such list appears:
![ex1](https://user-images.githubusercontent.com/23461482/30472913-03b6d586-9a07-11e7-9c4d-a53b5ca9cb30.jpg)

After I've selected a value I tap Enter and atom places automaticaly a semicolon ;
![ex2](https://user-images.githubusercontent.com/23461482/30472911-03afb10c-9a07-11e7-8f0f-d195fe5568d3.jpg)

So I wonder if any plugins which I don't know can help me? Or such features are/will be in future?
Thanks!

**Comment by aeschli** [comment] 2017-09-18 08:15
The first issue is #31948. The second is a duplicate of https://github.com/Microsoft/vscode/issues/34566 (similar: #34141).

**Closed by aeschli** 2017-09-18 08:15 UTC
Labels: css-less-sass, new release

**Comment by wheelhot** [comment] 2017-11-05 15:01
Wait, how do we enable this? Right now after I use emmet to add CSS Property, display: for example, it doesn't suggest me the valid CSS values.
