### ISSUE TITLE
Filters don't work in showOpenDialog

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35062] opened 2017-09-26 10:23 UTC
Testing #34821 on macOS

As soon as I add `filters: { 'TypeScript': ['*.ts'] }` to the options of `showOpenDialog`, I can no longer select any files, including `*.ts` files.

**Comment by jrieken** [comment] 2017-09-26 10:38
Scary... I only forward those...

**Comment by jrieken** [comment] 2017-09-27 09:46
Same, same but different. The doc isn't/wasn't correct and filters should not have `*.` as a prefix. Iff so nothing will match, it like saying `{ 'TypeScript': ['0xaf530balabla'] }`... Because nothing matches, nothing can be selected. Using `ts` et al makes it work

<img width="875" alt="screen shot 2017-09-27 at 11 43 12" src="https://user-images.githubusercontent.com/1794099/30906869-6ee3d162-a379-11e7-9f40-0e09e63786a0.png">

**Comment by jrieken** [comment] 2017-09-27 09:46
closing as duplicate of  #35063

**Closed by jrieken** 2017-09-27 09:46 UTC
Labels: api, bug
