### ISSUE TITLE
Explorer loses focus on Terminal scrolling output

### ISSUE THREAD

**Issue by martinrode** [microsoft/vscode#138369] opened 2021-12-02 21:01 UTC
Issue Type: <b>Bug</b>

* Make sure the Terminal window receives constant scrolling output (e.g. compile something)
* Try to rename a file in file tree of the Explorer
* On new output in the Terminal window the rename is canceled as the Explorer loses focus
* During such output it is impossible to rename a file
* This can be fixed by moving the scroll position in the Terminal slightly towards the top, the scrolling is not following the output anymore and the Explorer is not losing focus

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:14:33.711Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 86aba45f-50a4-463a-9ae4-0e2eb584748d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.4
vscode-css-formatter|aes|1.0.2
vscode-bazel|Baz|0.5.0
Nix|bbe|1.0.1
gotemplate|cas|0.4.0
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
go|gol|0.29.0
gc-excelviewer|Gra|4.0.45
svg|joc|1.4.14
eml|lei|0.4.0
rainbow-csv|mec|1.10.1
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.205.2
cpptools|ms-|1.7.1
material-icon-theme|PKi|4.11.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.2
code-clip-ring|Sir|0.4.0
rewrap|stk|1.15.4
lua|sum|2.5.1
even-better-toml|tam|0.14.2
pdf|tom|1.1.0
highlight-trailing-white-spaces|yba|0.0.2
luahelper|yin|0.2.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vscexrecpromptc:30404946
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998

```

</details>

**Comment by meganrogge** [comment] 2021-12-02 22:09
Thanks for the issue. I can't reproduce it. Can you please attach a gif?
![recording - 2021-12-02T140910 696](https://user-images.githubusercontent.com/29464607/144511138-70a362e7-4514-493d-ab3f-988f2195ca47.gif)

**Comment by martinrode** [comment] 2021-12-03 07:43
I am using ZSH, and start the rename with SPACE, but that really makes no difference. This bug has been there for a long time. Just never got around to report it.

Checking again, changing the scroll position in the Terminal does not stop the focus from being lost. But stopping the program running inside it does.

And no, there is no other activity on my desktop ;-).

![VS Code Focus Bug](https://user-images.githubusercontent.com/21123679/144563947-004615d6-2581-47fa-96d9-3012997d240b.gif)

**Comment by meganrogge** [comment] 2021-12-03 15:33
stopping the program from running should steal the focus from the explorer because that focuses the terminal.

**Comment by martinrode** [comment] 2021-12-03 15:35
> stopping the program from running should steal the focus from the explorer because that focuses the terminal.

Correct. What I meant is that in a quite terminal I don't see the lose focus problem in the explorer.

**Comment by meganrogge** [comment] 2021-12-03 15:36
whenever a terminal is focused, regardless of what's going on in it, the explorer loses focus by design. what are you seeing that is unexpected?

**Comment by martinrode** [comment] 2021-12-03 15:43
> whenever a terminal is focused, regardless of what's going on in it, the explorer loses focus by design. what are you seeing that is unexpected?

* The Explorer keeps losing focus (for me) if a program is active in the Terminal
* The Explorer is fine if no program is active in the Terminal

That's all I wanted to say. Sorry that this bug isn't 100% reproducible but it is 100% annoying.

**Comment by meganrogge** [comment] 2021-12-03 15:46
thanks for clarifying. i'll see if anyone else has reported this

**Comment by martinrode** [comment] 2021-12-03 15:59
* Just checked, it is NOT Go related. Happens in a Javascript project too. 
* It is also NOT related to the fact that the output wraps to the window in my test case and they do not in yours.
* It happens on a freshly started VS Code with only one workspace open
* I am on a M1 Air now, was on Intel before, same problem. Mac OS 11 + 12 
* Happens with ZSH as well as with BASH
* PROBLEMS, OUTPUT, DEBUG CONSOLE tabs are empty

**Comment by meganrogge** [comment] 2021-12-03 16:12
🤔 can't reproduce on a mac either
![recording (105)](https://user-images.githubusercontent.com/29464607/144635081-e536aac5-96d8-4992-b626-b3df1ba9c8d2.gif)

**Comment by martinrode** [comment] 2021-12-03 16:35
BTW: What tool are you using for the GIF creation?

**Comment by meganrogge** [comment] 2021-12-03 18:33
https://gifcap.dev/


> Megan, let it sit there. Don't finish the rename. Just open it and wait.
Waited for 30 seconds (not all of which is captured here bc would be too large to attach)
![recording (107)](https://user-images.githubusercontent.com/29464607/144654613-9d201f70-4765-4ca0-8e58-02eb8d42b7f6.gif)

**Comment by martinrode** [comment] 2021-12-03 20:04
mmh… can you try to walk with the cursor keys left and right a bit? really scratching my head here… maybe some extension I installed? anything suspicious in the list maybe?

**Comment by meganrogge** [comment] 2021-12-03 20:16
Can you run Extension Bisect?

**Comment by meganrogge** [comment] 2021-12-03 20:17
Also try on Insider's?

**Comment by martinrode** [comment] 2021-12-03 20:20
> Can you run Extension Bisect?

I can try next week if I find the time. Could you check against your list and let me know which of mine you don’t have?

**Comment by martinrode** [comment] 2021-12-03 20:21
> Also try on the [Insiders build](https://code.visualstudio.com/insiders)?

Will do ne t week! Good idea.

**Comment by meganrogge** [comment] 2021-12-03 20:23
i'll try on stable to reproduce it, but yes lmk if you can repro it on insider's

**Comment by meganrogge** [comment] 2021-12-03 20:24
doesn't reproduce on stable for me either

**Comment by Tyriar** [comment] 2021-12-06 14:23
My guess is it's one of your extensions, before any other steps I'd recommend closing all windows and trying to repro with `code --disable-extensions` as extensions can change focus.

**Closed** 2021-12-14 11:26 UTC
Labels: needs more info
