### ISSUE TITLE
Not able to run debug configurations named the same

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31579] opened 2017-07-27 13:59 UTC
Testing #31396

1. Have a workspace with `css` and `html` extensions.
2. Run `Launch Extension (css)` configuration -> Debug starts
3. Run `Launch Extension (html)` configuration

Observe that no new debug session is started.

**Comment by isidorn** [comment] 2017-07-27 14:00
@michelkaporin could you please share your repository on GitHub so I can inspect further why the second launch is not getting started.

What happens if you first launch html and then css?

**Comment by michelkaporin** [comment] 2017-07-27 14:04
@isidorn I am opening https://github.com/Microsoft/vscode/tree/master/extensions/css and https://github.com/Microsoft/vscode/tree/master/extensions/html as two separate folders in the same workspace.

No matter of order I don't get second launch config to run.

**Comment by weinand** [comment] 2017-07-27 14:05
Most likely a duplicate of #31533

**Comment by isidorn** [comment] 2017-07-27 14:11
Yes, a duplicate, sorry

**Closed by isidorn** 2017-07-27 14:11 UTC
Labels: debug, needs more info
