### ISSUE TITLE
1.11.1 has rendered code on remote linux host unusable

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vscode#24151] opened 2017-04-06 23:17 UTC
- VSCode Version: 1.11.1
- OS Version: fedora 20, centos 7.3, rhel 7.3

Steps to Reproduce:

1. install the update
2. open a file and try to navigate using the arrow keys or the usual navigation keys

arrow keys don't work
if you use the numeric keypad (num lock off) random chars ae inserted into the text
for a c++ file this basically destroyed the text

You do know, that linux machines are usually accessed via a ssh (e.g. putty) and x-forwarding...
The scan codes might not be working there 
Please provide a download of 1.10.x as this has rendered everything useless.

**Comment by chrmarti** [comment] 2017-04-06 23:23
Which keyboard layout are you using? U.S. English?

**Comment by alexandrudima** [comment] 2017-04-07 08:16
@yamcenutzer I believe this is a duplicate of #24107?

i.e. https://bugs.chromium.org/p/chromium/issues/detail?id=709242

Perhaps you can star the Chromium issue and jump in in case the Chromium team need more information on how to reproduce.

The workaround is: Use the following setting `"keyboard.dispatch": "keyCode"`.  Restart VS Code.

**Closed by alexandrudima** 2017-04-07 08:16 UTC
Labels: needs more info
