### ISSUE TITLE
[feature-request] [extension-candidate] Sidebar panel which provides one-click execution of package.json scripts

### ISSUE THREAD

**Issue by BellerophonM** [Microsoft/vscode#25048] opened 2017-04-20 01:11 UTC
For NPM projects, we should have a sidebar which lists and allows us to execute with a single click defined scripts in our package.json, as well as common tasks, and an output showing the execution trail of current script.

Feature-request extension-candidate

**Comment by mjbvz** [comment] 2017-04-20 04:28
Duplicate of #1777

Also, please checkout this extension to see if it offers some of the functionality you are after:  https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script

Our proposal for custom explores/side panels #12163 is still in a proposal state so I don't think an extension could offer this today

**Closed by mjbvz** 2017-04-20 04:28 UTC
Labels: duplicate, extension-candidate
