### ISSUE TITLE
Feature Request: Workspace-specific keybindings.json

### ISSUE THREAD

**Issue by dlee-nvisia** [Microsoft/vscode#18379] opened 2017-01-10 22:31 UTC
I am preparing to lead a workshop where I will be using VSCode as the suggested code editor. I've been able to bundle some useful settings, extensions and tasks directly for the class via the .vscode directory. Unfortunately, there is no way to bundle suggested keybindings for my project in the same way.

Technically, it seems relatively straightforward: the json format is already specified and keybindingResolver.ts is already wired up to take in the fixed native mappings and override them with the user-specific keybindings. This could either be extended to take two sets of overrides, or the workspace-specific ones could be concatenated to the user-specific override list.

Rather, I think the biggest problem is a matter of determining what .vscode/keybindings.json should do. Personally, I'd like to just use any keybindings found in that file first, then defer to user settings, then defer to native (just like the other .vscode config files), but before I consider working on a PR, I'd like to get some more opinions on what people think about this idea.

**Comment by mjbvz** [comment] 2017-01-10 22:46
I believe this is a duplicate of #10708 

Please take a look at @alexandrudima's response on that issue https://github.com/Microsoft/vscode/issues/10708#issuecomment-241330047 and let us know if the design concerns he brings up make sense

**Closed by mjbvz** 2017-01-10 22:46 UTC
Labels: duplicate, feature-request

**Comment by dlee-nvisia** [comment] 2017-01-10 22:48
Looks like my search accidentally excluded closed tickets! I think that will work for me. Thanks for the helpful tip.

On the upside, I can use this in my class right away!
