### ISSUE TITLE
> Issue Type: Bug

### ISSUE THREAD

**Issue by jace4511** [microsoft/vscode#113740] opened 2021-01-04 09:48 UTC
> Issue Type: Bug
> 
> 1. open a repository that requires github authentication
> 2. trigger a command such as `git pull` to trigger authentication
> 3. accept in the browser, which returns back to vscode (happens both when I allow the URL scheme and when I copy/paste the token into the "signing into" prompt)
> 4. I see `Error: certificate has expired`.
> 
> The github authentication output doesn't say much:
> 
> ```
> [Info  - 00:08:30.34] Logging in...
> [Info  - 00:08:40.313] Exchanging code for token...
> [Error  - 00:08:41.515] Error: certificate has expired
> ```
> 
> I first reported this 4 months ago on the GitHub Pull Requests extension:
> [microsoft/vscode-pull-request-github#1474](https://github.com/microsoft/vscode-pull-request-github/issues/1474)
> 
> The issue appears to be identical (except there's no stack trace this time). There are other users who commented on my report with the same or similar issues.
> 
> Now that authentication has moved to VSCode core I guess the report belongs here, particularly since it is reproducible with all extensions disabled.
> 
> I don't know if this is relevant, but I normally use SSH authentication to GitHub; git actions do not require authentication but extension actions do. I did a separate clone using HTTPS just to verify the issue happens for core actions as well.
> 
> VS Code version: Code 1.45.0 ([d69a79b](https://github.com/microsoft/vscode/commit/d69a79b73808559a91206d73d7717ff5f798f23c), 2020-05-07T15:57:33.467Z)
> OS version: Darwin x64 19.4.0
> 
> System Info
> Extensions disabled

_Originally posted by @jace4511 in https://github.com/microsoft/vscode/issues/97434#issuecomment-753603143_

**Comment by RMacfarlane** [comment] 2021-01-04 18:29
Duplicate of https://github.com/microsoft/vscode/issues/97434

**Closed by RMacfarlane** 2021-01-04 18:29 UTC
