### ISSUE TITLE
Title bar style custom: vscode icon overlaps file menu after restart

### ISSUE THREAD

**Issue by alisterlf** [Microsoft/vscode#53612] opened 2018-07-05 19:42 UTC
- VSCode Version: 1.25.0
- OS Version: Microsoft Windows [Version 10.0.16299.431]

Steps to Reproduce:

1. Press `F11` to enter fullscreen mode
1. Set `"window.titleBarStyle": "custom"`
2. Restart vscode
3. Press `F11` to exist fullscreen mode

![image](https://user-images.githubusercontent.com/764324/42344296-47aa6562-8072-11e8-9025-921462c79ce8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment] 2018-07-09 17:46
duplicate of #52952

**Closed by sbatten** 2018-07-09 17:46 UTC
Labels: new release
