### ISSUE TITLE
Crash upon click on File menu

### ISSUE THREAD

**Issue by janvorac** [microsoft/vscode#231831] opened 2024-10-21 12:26 UTC
Type: <b>Bug</b>

When I click on the File menu, code-insiders crashes.

VS Code version: Code - Insiders 1.95.0-insider (8965e51174c237ba2a7c4f7be991ffa0526892cb, 2024-10-16T05:04:09.933Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3747)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|15.35GB (7.35GB free)|
|Process Argv|--crash-reporter-id a312d65f-32be-493d-b7a5-dc6f40b91d05|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
parquet-explorer|Ada|1.2.1
vscode-github-actions|git|0.27.0
vscode-jsonnet|Gra|0.6.1
todo-tree|Gru|0.0.226
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.3
vsliveshare|ms-|1.0.5941
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
f3je6385:31013174
dvdeprecation:31040973
dwnewjupytercf:31046870
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
i21gd607:31141543
iacca1:31150324
notype1:31143044
showchatpanel:31139797
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by janvorac-solargis** [comment] 2024-10-21 12:28
Please, proved a way how I can send the *.dmp file to you. I cannot upload it here.

**Comment by gjsjohnmurray** [comment] 2024-10-21 13:28
/duplicate of https://github.com/microsoft/vscode/issues/230604

**Closed** 2024-10-21 13:29 UTC
Labels: *duplicate
