### ISSUE TITLE
Open VS Code in cmd then press Ctrl-c in the same cmd cause VS Code to exit (without save)

### ISSUE THREAD

**Issue by bertlea** [Microsoft/vscode#40617] opened 2017-12-21 05:07 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1

---

Steps to Reproduce:

1.  write some simple http request in node js and run it from command prompt (cmd)
2.  open the VC code for the source code of the node.js program.
3.  The program uses setInverval to get some data from remove http site every few seconds, and user use Ctrl-c to quit that program back to cmd.   But doing so, the VC Code just exits without warning nor save anything.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment] 2017-12-21 09:14
Can you share the program so we try to reproduce on our machines. Can you also reproduce with latest vscode inisiders from here https://code.visualstudio.com/insiders/

Let me get this stragith
1. You run program from command line
2. Open vscode with the repository you just ran
3. go back to command line and hit cmd + c -> and vscode closes?

**Comment by bertlea** [comment] 2017-12-22 02:45
I already updated to latest version (1.19.1) and the issue is still there.  But I got more insights after showing to my colleague.   I cannot share the original program yet as it contains some private data.  But it is basically is a node js program using http and https to issue simple GET request to external sites every minutes or so (like a ping tasks).   I need to revise the steps to reproduced this one as below:
1.  Open cmd and go to the source code folder of the node.js program.  Open the VS Code by issuing "code xxxx.js" and the VS code shows up with the source code of the program.
2.  Using the same cmd and run the testing program by issuing "node xxxxtest.js".  Notes, the xxxxtest.js will use the xxxx.js (ie. require xxxx.js in xxxxtest.js).
3.  After the xxxxtest.js is running, press Ctrl-c to stop it, then the VS Code will exist.

We found that if we use "call code xxxx.js", instead of just "code xxxx.js", the VS Code will not exit, but the cmd will show a message: "Rejected cached data from file: C:\Users\......82c5a1eeba\dialog-8d4eb24af88d6f20385024ad57b30163.code".   Looks like the cmd used to open VS Code keeps the VS Code under its management and Ctrl-c will kill it even it was running a node.js program.

Hope that helps.   I recall I do not experience such issue few months ago, so I suspect the issue is triggered by recent updates within 6 months.

**Comment by bertlea** [comment] 2017-12-22 03:01
Hi again.  I simplified the issue description as I found it has nothing to do with node.js.  You can simply reproduce it as below now:

1. Open cmd. then type "code" and press Enter to start VS Code.
2. In the same cmd, press Ctrl-c and the VS Code will exit without save anything.  You can do something in the cmd before pressing Ctrl-c and it will still kill the VS Code.

**Comment by joaomoreno** [comment] 2017-12-22 09:44
What are the contents of your `%PATH%` variable?

**Comment by bertlea** [comment] 2017-12-23 00:18
@joaomoreno  The path shown in cmd is below (I replaced real username with XXXX):

PATH=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\
WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program File
s\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\WindowsPow
erShell\v1.0\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\apps\brackets\command;C:\Program Fi
les\nodejs\;C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\XXXX\A
ppData\Local\Programs\Python\Python36-32\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common F
iles\Intel\WirelessCommon\;C:\bert\bin;C:\Program Files\Microsoft VS Code;C:\apps\fiddler;C:\Users\XX
XX\AppData\Roaming\npm

**Comment by bertlea** [comment] 2018-01-02 02:05
Hi guys, I found the issue only exist in my office's Windows 7 laptop, and my home's Windows 10 do not suffer from that.  I believe it is an installation problem on my office laptop.   I had an upgrade failed on that laptop before and I re-installed the program.  Maybe something went wrong when I re-installing it.  However, it will be nice if I know what went wrong and how to fix that.

**Comment by joaomoreno** [comment] 2018-01-08 10:22
Since it seems to be related to a specific machine, I'll close this. Glad you could localize the issue.

**Closed** 2018-01-08 10:22 UTC
Labels: needs more info
