### ISSUE TITLE
scrolling not smooth

### ISSUE THREAD

**Issue by Tantalus13A98B5F** [Microsoft/vscode#40007] opened 2017-12-11 09:03 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0

---

Steps to Reproduce:

1. When started, scrolling with touchpad is not smooth. Scrolling stops or jumps from time to time.
2. After reloading window, the problem is gone.

Reproduces without extensions: Yes

**Comment by pkos98** [comment] 2017-12-11 09:09
Having the same specs, I can confirm this behaviour.
But on Linux, the scrolling is working properly (smoothly) on the same machine.

**Comment by Tantalus13A98B5F** [comment] 2017-12-11 09:12
also toggle the devtools can solve this issue for a time...

**Comment by ZerofeniX** [comment] 2017-12-12 08:29
Having the same issue on my Surface Book 2. Scrolling with the touch pad is sometimes non-responsive but scrolling with the touch screen is a non-issue.

**Comment by Yidadaa** [comment] 2017-12-13 09:12
Having the same issue on Matebook X.
OS: Windows_NT x64 10.0.16299

**Comment by alexandrudima** [comment] 2017-12-13 09:46
Duplicate of #35191

**Closed by alexandrudima** 2017-12-13 09:46 UTC
Labels: editor, editor-core
