### ISSUE TITLE
Persist Debug pane information after debugging stops

### ISSUE THREAD

**Issue by Spacetornado** [microsoft/vscode#74297] opened 2019-05-24 18:55 UTC
(I tried searching for a duplicate request but couldn't find one.)

While developing scripts that interact with web APIs, the Debug pane (especially its Variables section) is very useful for inspecting the complex objects those APIs return. But the entire Debug pane gets cleared out when I stop debugging the script. I find myself having to expand complex objects multiple levels and take screenshots when I need to retain their structure/contents while writing code. But I can't copy/paste text from screenshots and it's a hassle to have to take them.

It would be great if there was an option for the information in the DEBUG pane to persist even after debugging stops, and only get cleared out once the user starts debugging the script/program again. I'm developing PowerShell scripts and using the official PowerShell extension.

**Comment by isidorn** [comment] 2019-05-27 14:24
This is a fair feature request, leaving it open and assigning to the backlog.
However the issue is that the debugee is no longer alive when the debugging ends, which would mean that elements which have not been expaneded yet can no longer be expanded. We could only show the information which the user has already expanded.

**Comment by Spacetornado** [comment] 2019-05-28 21:08
@isidorn Thanks for the info. Do you think it would be feasible / straightforward to add an "Expand All" button next to the "Collapse All" button on the VARIABLES section? That way the user could:

1. Start debugging.
2. Click Expand All in VARIABLES.
3. Stop debugging.
4. Continue writing code with all variables visible/expanded.

I realize it might be a significant performance hit based on the number & complexity of objects, but this would save a lot of expand clicks, and could be handy for other use cases as well. If so I could add this as a separate feature request (I searched open feature requests but couldn't find anything like that). If it's not feasible/straightforward, it's not really a big deal, as I'm usually only interested in a handful of objects/properties, and 1 to 3 levels of depth.

**Comment by isidorn** [comment] 2019-05-29 12:51
@Spacetornado the problam with the "Expand All" button is how deep should we expand? In theory it is possible to expand infinitily. And "Expand All" for just one level seems like it might not be what the user is looking for most of the time.
And yes it would be a performance hit against the debugger.

**Comment by Spacetornado** [comment] 2019-05-29 15:52
@isidorn That makes sense. If an "Expand Variables" feature was added, one possible implementation would have a setting for the number of levels to expand when it's clicked. It could be set to around 3 as the default, but the user could customize it to any number, with 0 representing infinity. Personally I would set it to around 5 or 6 as that's typically the maximum number of nesting levels I deal with, and I wouldn't mind the performance hit because it would save me many clicks (if I'm interested in a couple complex objects returned by two different APIs, and need to expand a few properties in each object to ~5 levels, that's around 20-30 clicks to do all the expansions manually).

**Closed** 2019-10-09 09:31 UTC
Labels: *out-of-scope, debug, feature-request
