### ISSUE TITLE
communication between the extension.ts and javascript loaded by html

### ISSUE THREAD

**Issue by stackerJobs** [Microsoft/vscode#10756] opened 2016-08-21 09:17 UTC
- VSCode Version:1.4.0
- OS Version:win10

Depend on the [#10392](https://github.com/Microsoft/vscode/issues/10392)
I have met the same problem too , I am looking for a way to achieve the communication between the extension.ts and javascript loaded in the html for that I want to 
perceive the action of active editor(e.g selectionchange ) in the preview html page without refresh the html page. Is there some advise?
 Any help will be appreciated!

**Comment by 928PJY** [comment] 2016-08-22 02:41
same question!I am try to communicate with file write/read , but I have to set a http-server , I wonder how does vscode access the local file？

**Comment by jrieken** [comment] 2016-08-22 07:59
dupe of #10392

**Closed by jrieken** 2016-08-22 07:59 UTC
