### ISSUE TITLE
Redundant error is shown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99134] opened 2020-06-02 16:30 UTC
Testing #98821

<img width="887" alt="image" src="https://user-images.githubusercontent.com/10746682/83544921-e93da080-a4fe-11ea-9547-61e5b9235d55.png">

It occurred to me when I closed the editor and opened the notebook from problems panel. Cant repro it again but filed it incase you know why it happens.

**Comment by jrieken** [comment] 2020-06-02 16:44
might be because the close event for a notebook is missing and then markers are't cleaned up

**Comment by jrieken** [comment] 2020-06-03 09:01
This should now be fixed with https://github.com/microsoft/vscode/issues/99142. Before, we would remove the project and create a new one, but we would never clean up markers...

**Comment by jrieken** [comment] 2020-06-03 09:01
/duplicate of https://github.com/microsoft/vscode/issues/99142

**Closed** 2020-06-03 09:02 UTC
Labels: *duplicate, bug, notebook
