### ISSUE TITLE
Snippet fails when cursor is not followed by a space

### ISSUE THREAD

**Issue by nachocab** [Microsoft/vscode#34248] opened 2017-09-12 21:18 UTC
Is there any way to force the snippet to run when the cursor is followed by a non-whitespace character?

![sep-12-2017 17-16-51](https://user-images.githubusercontent.com/27538/30348698-4e8809d4-97de-11e7-889a-06ba898e0178.gif)

**Comment by jrieken** [comment] 2017-09-13 13:28
> any way to force the snippet to run when the curs

Which snippet are you taking about? Can you share that with me?

**Comment by nachocab** [comment] 2017-09-13 14:18
Sure, any snippet. In this case it's `l`, if I type it and press tab it works. If the cursor is next to another letter (s) and I type `l` it doesn't work.

```
"assignment arrow": {
    "prefix": "l",
    "body": ["<- "],
    "description": "assignment arrow"
  }
```

**Comment by jrieken** [comment] 2017-09-13 16:00
> it and press tab it works

As in `editor.tabCompletion` or as in typing shows a suggest widget and tab inserts the selected item and it does do that when I not at the end of a word?

**Comment by nachocab** [comment] 2017-09-13 16:18
You can see it more clearly in the gif I uploaded. When the cursor is both preceded and followed by a space (or it's at the beginning of the line), if I type the `l`, the suggest widget appears and when I press tab, the snippet runs and the arrow appears. If the cursor is either not preceded or not followed by a space, the suggest widget does not appear and instead of the arrow, a space gets inserted after the `l`

**Comment by jrieken** [comment] 2017-09-14 07:39
Thanks, this is a duplicate of #32201

**Closed by jrieken** 2017-09-14 07:39 UTC
Labels: needs more info, snippets
