### ISSUE TITLE
Attach to process fails if node is started with custom port

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#46695] opened 2018-03-27 13:28 UTC
Testing #46582

elementary OS 0.4.1 Loki
Built on "Ubuntu 16.04.2 LTS"

node v8.9.1

- create foo.js
```js
setInterval(() => {
    console.log('ssss');
}, 1000);
```
- in the integrated terminal run 
`node --inspect=5445 ./foo.js bar`
- run the command `Debug: Attach to node process`
 
![image](https://user-images.githubusercontent.com/6461412/37970179-07a12322-31d3-11e8-9afb-65854cd8947b.png)

- pick the entry
- error: `Attach to process: cannot put process '796' in debug mode.`

**Comment by weinand** [comment] 2018-03-27 14:21
duplicate of #46685

**Closed** 2018-03-27 14:22 UTC
Labels: bug, debug
