### ISSUE TITLE
VSCode becomes too dim when Windows HDR is enabled

### ISSUE THREAD

**Issue by ErickXavier** [microsoft/vscode#106122] opened 2020-09-04 13:51 UTC
- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. Go to Window's Display Settings and enable "Play HDR games and apps"
2. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-09-04 14:57
Bot is correct, this is duplicate of issues above but original issue is #88491

Could you check if it's still reproducible for you in Insiders builds https://code.visualstudio.com/insiders/?

**Comment by WillerZ** [comment] 2020-09-06 23:00
I also have this problem with VScode and I do not have it with insiders

**Comment by aeschli** [comment] 2020-09-18 20:45
duplicate of  #88491

**Closed by aeschli** 2020-09-18 20:45 UTC
Labels: needs more info
