### ISSUE TITLE
task: build tsconfig.json wrong command line symbol

### ISSUE THREAD

**Issue by ysneo** [Microsoft/vscode#30563] opened 2017-07-13 03:31 UTC
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:`disable all extensions`
---

Steps to Reproduce:

1.  ts files build with tsconfig.json (I use task 2.0.0)
2. ![task](https://user-images.githubusercontent.com/17615113/28149105-a740a186-67bd-11e7-806f-4906fd2d146e.png)
3. ![fail](https://user-images.githubusercontent.com/17615113/28149137-e92a2950-67bd-11e7-84ff-b63e273b21ef.png)
4. `I change symbol ( \ ) to ( / )` , it works

![succeed](https://user-images.githubusercontent.com/17615113/28149223-a1f34318-67be-11e7-99de-a7d4e5418f8d.png)

**Comment by dbaeumer** [comment] 2017-07-13 09:18
@mjbvz this might not be fixable for the TypeScript extension without having API letting you detect the default shell used. We discussed this problem in other situations as well can currently we assume that under Windows '\' is the path separator but this is incorrect if people are using bash or other Linux shell or subsystems. Then the path separator is '/'.

Lets do the following for now: @mjbvz you can use the setting `"terminal.integrated.shell.windows"` to detect the shell if you want to fix this. 

I created https://github.com/Microsoft/vscode/issues/30592 to improve the general story here.

**Comment by alexr00** [comment] 2019-01-04 15:32
This has been fixed for all the built in task providers. Improving the cross platform path story is a dupe of #38381.

**Closed** 2019-01-04 15:33 UTC
Labels: *duplicate, WSL, bug, tasks
