### ISSUE TITLE
bad spacing for extension readme

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8307] opened 2016-06-28 10:35 UTC
![screen shot 2016-06-28 at 12 35 07](https://cloud.githubusercontent.com/assets/1794099/16412504/d91ea73c-3d2c-11e6-9f16-bc5b467c32f4.png)

**Comment by isidorn** [comment] 2016-06-28 10:38
If by bad spacing you are refering of missing of padding then dupe of #8251
If there is another issue here please let me know and I will reopen - thanks.

**Closed by isidorn** 2016-06-28 10:38 UTC
Labels: bug
