### ISSUE TITLE
Insert Emoji by Ctrl+Cmd+Space in code break the current line

### ISSUE THREAD

**Issue by nguyennb9** [Microsoft/vscode#23141] opened 2017-03-24 08:30 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|project-manager|alefragnani|0.13.5|
|theme-desertex|casualjim|0.0.6|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|json-tools|eriklynd|1.0.2|
|prettier-vscode|esbenp|0.11.0|
|flow-for-vscode|flowtype|0.5.0|
|vscode-icon-theme|jtlowe|1.5.0|
|Go|lukehoban|0.6.55|
|addDocComments|stevencl|0.0.8|
|react-beautify|taichi|0.3.0|;

---

Steps to Reproduce:

1. Go to any line of code, I usually insert Emoji in the HTML code or console.log in Javascript
2. Press Ctrl+Cmd+Space to open the Dialog to select Emoji
3. Navigate between Emoji by arrow buttons, press Enter to choose. Sometimes it will break the code, insert more space or comma character, sometimes it just insert exactly that Emoji

**Comment by alexandrudima** [comment] 2017-03-27 07:49
Duplicate of #4271

**Closed by alexandrudima** 2017-03-27 07:49 UTC
Labels: editor-input, mac
