### ISSUE TITLE
TypeScript quick fix (import suggestion) isn't working

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#49407] opened 2018-05-07 20:18 UTC
Issue Type: <b>Bug</b>

1. Add a reference that exists as an export of another file, without importing reference in the file.

Expected: Lightbulb pops on click that offers suggestions on where to import from.
Actual: Nothing.

VS Code version: Code - Insiders 1.24.0-insider (d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe, 2018-05-07T08:55:27.483Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (16.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.0.7
bracket-pair-colorizer|Coe|1.0.48
gitlens|eam|8.2.4
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
sort-typescript-imports|mic|1.4.1
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.4.3
polacode|pnp|0.2.2
project-snippets|reb|0.5.0
vscode-icons|rob|7.23.0
vscode-todo-highlight|way|0.5.12

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-05-07 20:35
Please share some example code and a description of your project structure

**Comment by martellaj** [comment] 2018-05-07 21:02
It's the OWA code base. A simple example is 2 TS files that live in the same directory. 1 file has an exported const. I attempt to use that export in the other TS file. Before I updated today, clicking on the import name would pop the lightbulb and ask me if I want to import. Now it doesn't do anything.

**Comment by mjbvz** [comment] 2018-05-07 21:10
Please create a small example project that demonstrates this problem. Sorry but I'm not  building owa

**Comment by mjbvz** [comment] 2018-05-07 21:47
No, the example in the vscode code base was helpful but the original issue was not actionable as filed. In the future, please provide a list of steps that anyone can follow to reproduce the problem.  You can find some suggestions for filing good issues here: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests 

The issue with `IUserFriendlyKeybinding` is that it is an interface. You get the suggestion if you use implements instead:

![screen shot 2018-05-07 at 2 39 24 pm](https://user-images.githubusercontent.com/12821956/39726613-77076ce8-5204-11e8-8192-2adb892b1f3c.png)

We probably should show the import quick fix too. I've opened https://github.com/Microsoft/TypeScript/issues/23945 to track this. Does this sound like the same root cause as the problem you were seeing?

**Comment by martellaj** [comment] 2018-05-07 22:15
Is there a new setting that needs to be enabled for this to work? I went back to the example I provided (using your code) and it still doesn't work for me on the version I'm on.

Here are my settings that would have any affect on this (I think). The rest are defaults.
![image](https://user-images.githubusercontent.com/1019478/39727900-6cb04986-5209-11e8-8588-764c69bfddc3.png)

**Comment by mjbvz** [comment] 2018-05-07 23:31
Same root cause as #49350. Will be fixed in the next insiders release

**Closed by mjbvz** 2018-05-07 23:31 UTC
Labels: javascript, needs more info, typescript

**Comment by martellaj** [comment] 2018-05-07 23:42
Yep. Thanks.
