### ISSUE TITLE
can't display image

### ISSUE THREAD

**Issue by diyijing** [microsoft/vscode#81357] opened 2019-09-24 06:42 UTC
Issue Type: <b>Bug</b>

try to open an image, png or jpg

VS Code version: Code - Insiders 1.39.0-insider (9f6a745027fc7b2a12495970f64625e24f410224, 2019-09-24T05:24:32.949Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.14.81.bm.7-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|31, 15, 9|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|-psn_0_11156131|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 4.14.81.bm.7-amd64|
|CPUs|Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz (4 x 2294)|
|Memory (System)|7.67GB (2.10GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
thrift|cdu|0.0.1
vscode-wxml|cod|0.1.9
riot-tag|cri|0.1.7
javascript-ejs-support|Dig|1.1.3
es7-react-js-snippets|dsz|2.4.3
Angular-BeastCode|Mik|8.0.10
vscode-language-pack-zh-hans|MS-|1.38.4
remote-containers|ms-|0.77.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.6
vscode-remote-extensionpack|ms-|0.17.0
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
vim|vsc|1.10.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.0.1
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
shell-format|fox|6.1.2
beautify|Hoo|1.5.0
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.38.4
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
Go|ms-|0.11.6
vetur|oct|0.22.3
remote-vscode|raf|1.1.0
java|red|0.49.0
vscode-yaml|red|0.5.3
vscode-leetcode|she|0.15.4
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
quokka-vscode|Wal|1.0.253
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment] 2019-09-25 23:27
Duplicate of #81434

**Closed by mjbvz** 2019-09-25 23:27 UTC
