### ISSUE TITLE
editor.action.quickFix Only Triggering on First Token of Fix Range

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#17569] opened 2016-12-20 00:43 UTC
Using `editor.action.quickFix`, it seems that I can only trigger the quick fix for the first token of the range. Here's an example from TypeScript:

```js
class BaseClass {
    constructor() { }
}

class SubClass extends BaseClass {
    constructor() {

    }
}
```

<img width="361" alt="screen shot 2016-12-19 at 4 40 28 pm" src="https://cloud.githubusercontent.com/assets/12821956/21334144/e2e745f6-c609-11e6-8a1e-a98143db54a3.png">

The quick fix error highlights the entire constructor of `SubClass`, but I can only trigger the quick fix action when the cursor is inside `constructor`

![dec-19-2016 16-41-36](https://cloud.githubusercontent.com/assets/12821956/21334154/05cd6c8a-c60a-11e6-9b47-9569cbcd70d3.gif)

The quick fix light bulb works as expected

**Comment by jrieken** [comment] 2017-03-02 11:40
dupe of https://github.com/Microsoft/vscode/issues/15488

**Closed by jrieken** 2017-03-02 11:40 UTC
