### ISSUE TITLE
 Direct copy problem from file manager to Vs Code

### ISSUE THREAD

**Issue by mojtabakheyri1997** [Microsoft/vscode#68778] opened 2019-02-15 11:52 UTC
Steps to Reproduce:

    1. Copy file needed from file manager
    2. Open Vs Code and Right-Click in folder project in Vs Code file explorer!
    3. Oh! Paste in inactive!

![screenshot_2019-02-15_15-26-02](https://user-images.githubusercontent.com/47574391/52855283-3513dd00-3136-11e9-9198-a56705e677c3.png)

Hi, I can copy and paste from the vs code file explorer to vs code file explorer , but I can't do it directly from the file manager to vs code file explorer! The paste button is inactive.
I did a search for the resolved the problem , but I didn't find a solution.
I need to open the project folder in the file manager to add the files needed from the file manager to the project.
Thanks .

- VSCode Version: 1.31.1
- OS Version: Linux x64 4.15.0-43-generic(Ubuntu 18.04)

Does this issue occur when all extensions are disabled?: Yes

**Comment by frobinsonj** [comment] 2019-02-15 12:13
Dupe of issue #164

**Comment by mojtabakheyri1997** [comment] 2019-02-15 12:19
> Duplicate of issue #164
Hi, Thanks
Therefore , the solution is only drag and drop the files , according to the issue #164.

**Closed** 2019-02-15 18:49 UTC
Labels: *duplicate, new release
