### ISSUE TITLE
Syntax highlighting broken for all Ansible extensions

### ISSUE THREAD

**Issue by Hayorti** [Microsoft/vscode#62322] opened 2018-10-31 20:16 UTC
Issue Type: <b>Bug</b>

Syntax highlighting for all Ansible extensions is now broken. I've confirmed that they still work on VSCode 1.28 (Stable).

VSCode Version:
- 1.29.0-insider
- 97ad72a02c351d6cde0fd32b41d9700a43e5964a

OS Version:
- macOS Mojave

Steps to reproduce:
1. Create a YAML (.yml) file and populate it with some key:value pairs
2. Open it, verify that YAML syntax highlighting kicks in
3. Install the "Ansible" module
4. Configure the following file association:
    "files.associations": {
        "*.yml": "ansible"
    }
5. Verify that the same YAML file used earlier is now formatted using "Ansible" highlighting, not "YAML"
6. Restart VSCode
7. Open the same YAML file as before and verify that, for some reason, "YAML" highlighting is used, not "ansible"

I noticed that if VSCode is in the state that it would be in at step 7, editing the file association's keys (eg. file type) and saving it kicks VSCode a little bit and it uses the correct highlighting for the rest of the session. And this happens with any file I associated with Ansible, not just files with a .yml extension.

This definitely happened relatively recently, but I don't know exactly when I saw it first or which version I was on.

**Comment by alexandrudima** [comment] 2018-11-01 07:37
Duplicate of #62030

**Closed by alexandrudima** 2018-11-01 07:37 UTC
Labels: languages basic
