### ISSUE TITLE
Repository names not shown properly in source control panel

### ISSUE THREAD

**Issue by twopelu** [microsoft/vscode#106406] opened 2020-09-10 13:47 UTC
Issue Type: <b>Bug</b>

After last update, the repository names are not shown properly in the source control panel, the name of the branch (right) overlaps the name of the repository (left) and the panel has to be extended to see the complete name. I think that the repository name should overlap the branch name so you can see the repo you are working on it at first sight.

![1](https://user-images.githubusercontent.com/12948190/92739184-e8799d80-f37c-11ea-9cd6-6d28bd4657b5.PNG)
![2](https://user-images.githubusercontent.com/12948190/92739190-e9aaca80-f37c-11ea-8468-b5d37ef544a7.PNG)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

**Comment by antcodd** [comment] 2020-09-11 03:06
This is a duplicate of #104801, though the screenshot here is helpful. That issue was closed, clearly there is disagreement over which part of the name is more important.

Personally I think a reasonable compromise would be to show at least some characters from the repository name. The current behaviour looks like a bug.
It might even make sense for one or both to display the end rather than the beginning of the name? The user can always hover of the string to get the full one, but only if there is some part of the string visible to hover over!

**Comment by joaomoreno** [comment] 2020-09-14 14:12
> The user can always hover over the string to get the full one, but only if there is some part of the string visible to hover over!

I've added a minimum width such that you can always see a bit of the name.

**Closed** 2020-09-14 14:12 UTC

**Comment by twopelu** [comment] 2020-09-14 22:02
> It might even make sense for one or both to display the end rather than the beginning of the name?

I think that this may vary a lot depending on your repo and branch naming conventions, probably there is no good answer :-)
