### ISSUE TITLE
Use top bar for all confirmation dialogs

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#19435] opened 2017-01-26 12:38 UTC
UX: currently, VS Code uses two styles of confirmation dialogs:

**1\. The top bar**

![image](https://cloud.githubusercontent.com/assets/101152/22330985/3de0a632-e3c9-11e6-8845-9647a48fd737.png)

**2\. System dialog**

![image](https://cloud.githubusercontent.com/assets/101152/22331557/6124e7b8-e3cc-11e6-9110-7585e5faf6e7.png)

It would be nice to unify those, I think that the first style fits the overall UI much better.

**Comment by bpasero** [comment] 2017-01-26 12:58
My 2 cents: we should move away from using the message bar as a way to ask for user input. This should only be used for information purpose.

**Comment by borekb** [comment] 2017-01-26 13:09
The real problem might be with modality, the message bar probably don't blocks the UI. (I generally dislike modal dialogs but understand some scenarios are "modal" by nature.)

Just from the perception point of view, the message bar UI feels much more pleasant and in-line with the rest of VSCode's UI.

**Comment by bpasero** [comment] 2017-01-26 13:14
While it is not blocking, the current UI is very bad as it overlaps with the editor-tabs row and typically always is in the way.

**Comment by isidorn** [comment] 2017-11-20 14:14
Duplicate of https://github.com/Microsoft/vscode/issues/1135

**Closed by isidorn** 2017-11-20 14:14 UTC
Labels: feature-request, ux, workbench-notifications
