### ISSUE TITLE
Ctrl+Scroll image zoom behaviour inconsistent with text zoom behaviour

### ISSUE THREAD

**Issue by senseibaka** [Microsoft/vscode#43149] opened 2018-02-08 00:29 UTC
When ctrl+scrolling an `image` in `vscode`:
* `up` translates to zoom `out`
* `down` translates to zoom `in`

When ctrl+scrolling `text` in `vscode`:
* `up` translates to zoom `in`
* `down` translates to zoom `out`

Behaviour of other apps (e.g. Chrome, Firefox, Paint, Paint.net), seems to indicate the default should be:
* `up` translates to `in`
* `down` translates to `out`

So,
* Can the default image zoom behaviour be internally consistent with the text zoom (`up` -> `in`, `down` -> `out`)?
* Can some sort of invert setting be added?

Thanks

**Comment by mjbvz** [comment] 2018-02-08 01:10
Duplicate of #43138

**Closed by mjbvz** 2018-02-08 01:10 UTC
Labels: editor, editor-core
