### ISSUE TITLE
Not getting intellisense for predefined common variables in task.json and launch.json.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4767] opened 2016-03-29 18:47 UTC
- VSCode Version:0.10.12-alpha
- OS Version: windows10

Steps to Reproduce:
1. Launch app and open any folder which contains .ts project
2. Add task.json file or select the node.js environment to generate launch.json.
3. Try to update the property value with predefined common variables like ${file},${cwd}, ${workspaceRoot} etc. in task.json or launch.json .
4. Verify intellisense should display for all the predefined common variables.

Actual: Intellisense is displaying only for ${workspaceRoot}.
![image](https://cloud.githubusercontent.com/assets/17735796/14119581/a96818e6-f5a3-11e5-8b51-2a92289e769e.png)

**Comment by isidorn** [comment] 2016-04-01 10:14
@v-pavanp how exactly do you get intelli-sense for ${workspaceRoot}? Can you give me steps? I do not get intelli-sense for any of those properties.
@aeschli is it possible for me to define these global variables which should always be offered in my schema?

**Comment by aeschli** [comment] 2016-04-01 17:28
@isidorn Not with the schema. But you could contribute your own completion provider.

**Comment by isidorn** [comment] 2017-11-13 10:15
@weinand let me know if you would love this feature and I can move it to november to investigate

**Comment by weinand** [comment] 2017-11-13 10:24
@isidorn yes, but only if it is low-hanging.

(I've only touched this because it had the wrong label).

**Comment by weinand** [comment] 2017-11-13 15:47
duplicate of #8370

**Closed by weinand** 2017-11-13 15:47 UTC
Labels: debug, feature-request, tasks
