### ISSUE TITLE
When the editor instance is zoomed (Ctrl +) the Markdown Preview gets clipped

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/vscode#22825] opened 2017-03-18 12:36 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-material|bcmarinacci|1.3.0|
|theme-seti|bialikover|0.0.1|
|vscode-eslint|dbaeumer|1.2.2|
|createuniqueid|donjayamanne|0.0.3|
|python|donjayamanne|0.5.5|
|genuuid|espresso3389|0.3.3|
|text-transform|florianloch|0.0.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|beautify|HookyQR|0.1.10|
|path-autocomplete|ionutvmi|1.1.0|
|theme-material-darker|jantto|0.0.1|
|docthis|joelday|0.3.3|
|FlatUI|lkytal|1.1.0|
|csharp|ms-vscode|1.4.0|
|debugger-for-chrome|msjsdiag|0.5.2|
|proto|peterj|0.0.2|
|seti-icons|qinjia|0.0.7|
|vscode-icons|robertohuertasm|4.1.0|
|vscode-flow|rtorr|276.3.0|
|theme-boxythemekit|trongthanh|0.0.3|;

---

Steps to Reproduce:

1. Start Markdown Splitview
2. Zoom UI using CTRL +

![image](https://cloud.githubusercontent.com/assets/231889/24072033/c39f6b62-0bdf-11e7-8c9d-e0b9d8de5590.png)

**Comment by mjbvz** [comment] 2017-03-18 20:39
Duplicate of #5745

**Closed by mjbvz** 2017-03-18 20:39 UTC
Labels: duplicate
