### ISSUE TITLE
Broken Editor Background color

### ISSUE THREAD

**Issue by McPrescott** [microsoft/vscode#91364] opened 2020-02-25 11:41 UTC
Issue Type: <b>Bug</b>

A picture says a thousand words, so:

![Screenshot from 2020-02-25 04-15-26](https://user-images.githubusercontent.com/20735042/75243452-2ae3e000-5787-11ea-8bc6-efec72b82ebb.png)

From what I've gathered it does not affect non-colored backgrounds (white, greys, black), and affects blue backgrounds most significantly. Another important point is that the affected regions change when the cursor is moved shown below.

![vscode-broken-background](https://user-images.githubusercontent.com/20735042/75244059-44d1f280-5788-11ea-8b36-edc259d0220e.gif)

Originally I thought that this was an error in the Synthwave theme and found another [very similar issue](https://github.com/robb0wen/synthwave-vscode/issues/128), and he is also on Ubuntu.

To attempt to resolve the issue I've disabled all extensions, reinstalled VsCode, installed a completely fresh version of insiders edition and none have resolved the problem.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (2.10GB free)|
|Process Argv|--user-data-dir /jmcp/conf/code/web/data --extensions-dir /jmcp/conf/code/web/extensions|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment] 2020-02-25 12:44
/duplisacte of #85452

See https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for workaround

**Comment by IllusionMH** [comment] 2020-02-25 13:40
/duplicate of #85452

See #85452 (comment) for workaround

(typo in initial comment, sorry for second second notification)

**Closed** 2020-02-25 13:40 UTC
Labels: *duplicate
