### ISSUE TITLE
C# not recognized

### ISSUE THREAD

**Issue by wcampospro** [microsoft/vscode#92184] opened 2020-03-06 22:17 UTC
Issue Type: <b>Bug</b>

When trying to use VSCode on CShapr projects it no longer works, it keeps asking to install the C# extension even if its already installed.
No Autocomplete works.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (23.57GB free)|
|Process Argv|C:/Users/wcampos/Documents/UnityProjects/GD56_OOP|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.9
eppz-code|epp|1.2.41
fontsize-shortcuts|fos|1.5.0
todo-tree|Gru|0.0.169
docomment|k--|0.1.8
unity-snippets-modified|lio|0.4.0
csharp|ms-|1.21.13
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.0.1
subtle-brackets|raf|3.0.0
explorer-exclude-vscode-extension|Red|1.2.0
code-settings-sync|Sha|3.4.3
unity-debug|Uni|2.7.2

</details>

**Comment by RobFosterNYC** [comment] 2020-03-06 22:28
Yup I can confirm, as this happen to me too.
.
![Screenshot_15](https://user-images.githubusercontent.com/18384135/76127534-e39fef80-5fcf-11ea-8318-a6e3648f7d6b.png)

**Comment by lutgensDev** [comment] 2020-03-07 02:32
Having the same issue. Looks like a potential change in naming convention? The prompt searches for an extension with @id:ms-vscode.csharp, while the extension now has a tag of @id:ms-dotnettools.csharp

**Comment by IllusionMH** [comment] 2020-03-07 04:18
/duplicate of #92153

You can install previous version for now. See https://github.com/OmniSharp/omnisharp-vscode/issues/3623#issuecomment-595561225 for current workaround

**Closed by IllusionMH** 2020-03-07 04:18 UTC
Labels: *duplicate
