### ISSUE TITLE
insiders: tslint cannot find local modules

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#35398] opened 2017-09-29 19:38 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
tslint|eg2|1.0.9
debugger-for-chrome|msj|3.3.1
vscode-docker|Pet|0.0.18
perforce|sle|2.2.1
autoimport|ste|1.2.2

Steps to Reproduce:

1. Install plugin egamma/TSLint or sqs/TSLint (TEMP multiroot-compat)
2. create multiple sub projects using lerna to manage dependencies
3. in package B `import * as A from '@pkggrp/A`
4. note that tslint reports on above line: `[ts] cannot find module '@pkggrp/A'`

Reproduces without extensions: NA
Reproduces with multiroot or nonmultiroot project (subprojects are not marked as roots for either case)
Does not reproduce in vscode 1.16.1
also reported in [tslint](https://github.com/Microsoft/vscode-tslint/issues/273)

**Comment by egamma** [comment] 2017-10-03 13:39
duplicate of https://github.com/Microsoft/vscode-tslint/issues/273

**Closed by egamma** 2017-10-03 13:39 UTC
