### ISSUE TITLE
Support swiftly fixing quick fix errors one after another

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194226] opened 2023-09-26 21:02 UTC
Testing #194072

Repro:

1. Create 2 errors on a line
2. cmd+.
3. enter
4. wait a second
5. cmd+.
6. enter

Doing this slowly works fine:

![Image](https://github.com/microsoft/vscode/assets/2193314/a8a8010f-39ac-429c-a6b7-ff9810ed47d3)

Doing it quickly fails:

![Image](https://github.com/microsoft/vscode/assets/2193314/a6db3c3e-6009-42d0-ae50-bc75a3ab376d)

**Comment by justschen** [comment] 2023-09-26 21:10
I've had some folks has mentioned this before as well (not just in the context of this feature) - It's an issue with how the diagnostics are formed. (like how sometimes you hit `ctrl + .` for the quickfix menu before the error shows up in anticipation of the quickfix being there)

Will do some exploration on how we can optimize this (may be resolved with how I'm handling multiple quickfixes, mentioned in your issue here https://github.com/microsoft/vscode/issues/194222)

**Comment by Tyriar** [comment] 2023-09-26 21:14
@justschen the error underline never went away though, so could we be optimistic about this and assume it's still valid if the range for that problem didn't change?

**Comment by justschen** [comment] 2023-09-26 21:20
You're right, that's interesting. I'll give it a look 🤔

**Comment by justschen** [comment] 2023-12-06 23:14
@mjbvz I think this might have something to do with the LSP side of things? I've seen some related issues about errors not being picked up fast enough and people hitting `ctrl + .` anticipating an error, but the diagnostics have not shown up yet.

**Comment by mjbvz** [comment] 2023-12-06 23:16
Yes seems like a duplicate of #117812. Right now we have to manage passing diagnostics to TS Server and these easily get out sync the server

**Closed by mjbvz** 2023-12-06 23:16 UTC
Labels: editor-code-actions
