### ISSUE TITLE
Typescript intellisense looks broken after dot completion

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1331] opened 2015-12-15 13:42 UTC
https://youtu.be/whtggr9RFXs
1. Trigger intellisense with <kdb>dot</kbd> works.
2. Manual trigger doesn't work

Video recorded at gitServices.ts#768

**Comment by joaomoreno** [comment] 2015-12-15 13:43
Works fine in JavaScript.

**Comment by dbaeumer** [comment] 2015-12-15 14:36
Did some investigation but wasn't able to reproduce. I also check that the position is the same whether the code assist is triggered by . or by hand.

**Comment by dbaeumer** [comment] 2016-11-15 19:54
Closing since I can't reproduce this anymore. Please ping if you still see the issue.

**Closed by dbaeumer** 2016-11-15 19:54 UTC
Labels: not-reproducible, typescript
