### ISSUE TITLE
Unable to connect to Extension Marketplace

### ISSUE THREAD

**Issue by JuvenileLad** [microsoft/vscode#128893] opened 2021-07-17 03:46 UTC
Issue Type: <b>Bug</b>

I am unable to connect to Entensions Marketplace even thought my internet connection is stable. There are no proxy or VPN issues whatsoever. Please look into it and provide me with a solution. 

VS Code version: VSCodium 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-16T00:15:55.196Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz (2 x 2526)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.65GB (3.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by tamuratak** [comment] 2021-07-17 05:02
Duplicate of #128583

**Closed** 2021-07-18 14:11 UTC
Labels: *duplicate, new release
