### ISSUE TITLE
Terminal links with different casing open multiple editors

### ISSUE THREAD

**Issue by Alias-777** [microsoft/vscode#75770] opened 2019-06-19 13:05 UTC
I'm using VScode mostly on Windows10 and have noticed that the links in the terminal are case sensitive. Each link that has an unique case configuration will be opened in a new tab. This brings a lot of navigation issues and frustrations and some unique problems.

Frustrating is that I always keep my tabs in a certain order. Now, if a script/executable generates a new tab to an already opened file, then I just might close the original tab which breaks my order and makes me frustrated. Also having the file opened and then seeing it jump to a new tab irritates me.

Issues are that if you have 2 or more tabs open to the same file and then you start editing both/all and then save one and then try to save the other one you get an - understandable modification time conflict - error:

![ss](https://user-images.githubusercontent.com/34722701/59765914-64328a80-929f-11e9-9ba5-c46206797f06.png)

Because you are writing to a file that's newer then your copy!

A side effect is also that the other case paths are just blindly added to the "Open Anything" [CTRL+P] menu., which then will open unique tabs for the same files as well! :(

![ss01](https://user-images.githubusercontent.com/34722701/59767304-503c5800-92a2-11e9-98e9-b7e5659471b0.png)

To simply reproduce my problem, create a new directory. I'm using c:\Test in my example. Make a .vscode dir and a Source dir. In the .vscode create a file named: "tasks,json" with the following content:

    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Run: Test.cmd",
                "type": "shell",
                "command": "cmd /C Source\\Test.cmd",
                "group": {
                    "kind": "build",
                    "isDefault": true
                },
                "problemMatcher": []
            },
        ]
    }

And in the Source directory create a file: "Test.cmd" with the following contents:

    @echo off

    REM: Output some test links
    echo 1. absolute-matched:    [ %cd%\Source\Test.cmd:4 ]
    echo 2. absolute-lower:      [ %cd%\source\test.cmd:5 ]
    echo 3. absolute-dir-lower:  [ %cd%\source\Test.cmd:6 ]

So our new C:\Test directory sould look as follows:

    C:\Test>tree c:\Test /F /A
    +---.vscode
    |       tasks.json
    |
    \---Source
            Test.cmd

Please note that my example is Case-Sensitive and you should use the same cases to get the same results.

Now run out task: `Run: Test.cmd` and control click the tree links in the terminal output. You should now have 3 tabs to the same file! Which are now also part of the "Open Anything" index.

Please fix this!, it is my number 1 irritation of this otherwise nice piece of software! VScode is my daily driver now when it comes to coding. Please, fix this!

**Comment by Alias-777** [comment] 2019-08-12 09:40
Hi,

I just wanted to add that opening files from the command line will yield the same results.

    code c:\Test\Source\Test.cmd
    code c:\Test\source\test.cmd
    code c:\Test\source\Test.cmd

This also effects MacOS - which I've tested personally - because the majority of Mac's out there will have a case-insensitive formatted file-system.

Also the opened multiple tabs to one file give problems with language plugins.

Here is a CPP example, it comes from my actual work:
![ss01](https://user-images.githubusercontent.com/34722701/62855967-e4033100-bcf3-11e9-9044-b472beb0213d.png)

which is enormously frustrating too me. The __FILE__ and __LINE__ macro's are - for what ever reason - lowered by Visual Studio. So any macro you write for tracing and debugging, based upon these definitions will produce lowered - and with that potentially inaccurate - links.

I'm experiencing this on a daily base and I've seen other languages behave maliciously as well.

From my side there is not much I can do about this other than writing a function that traverses all the directories and validates the case of those directories and the file. But that would still not resolve the command line problems.

Please fix this!

Thank you very much!

**Comment by LAK132** [comment] 2019-08-27 01:46
Perhaps this could be resolving to the case sensitive URL on case insensitive systems?

https://github.com/microsoft/vscode/blob/1.37.1/src/vs/platform/files/common/fileService.ts#L200

Then maybe this could be `return stat.resource`?

https://github.com/microsoft/vscode/blob/1.37.1/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L348

(I'm not even remotely familiar with this codebase, this is just a guess)

**Comment by Tyriar** [comment] 2019-10-09 18:04
@bpasero I think you've said this was by design in the past? I just ask the opener service to open the link and it opens multiple editors for the same file on case sensitive OS's.

**Comment by bpasero** [comment] 2019-10-09 18:25
Our editors are backed by resource identity. Different casing => different resources => different editors.

**Closed** 2019-10-09 18:25 UTC
Labels: *as-designed

**Comment by LAK132** [comment] 2019-10-09 22:27
The issue I have with this mentality is that this isn't how Windows works. Different casings can all refer to the same resource on disk, which is especially problematic when using MSVC which thinks it's a good idea to make all source code references lower case in the debugging binaries.

**Comment by Alias-777** [comment] 2019-10-09 23:30
Just because something is "designed" a certain way, does not disqualify it as a bug. Every bug is just doing what it's designed to do. Every flaw in the universe is just doing it because it's designed to do that. 

It seems like minor and simple request to just have the editor check if the file is already open. Do a case-insensitive comparison instead of a case-sensitive one. Both Mac and Windows use a case-insensitive filesystem., so you must check **case-insensitive** on filesystem resources. Not doing that will produce bugs in plugins and frustrations in users. Because then you are not using the filesystem as how it's "**designed**" to work. (you're introducing case-sensitivity in a system which is **designed** case-insensitive.)

A lot of plugins will behave badly in the current state of heaving multiple views/editors to one document... From a user perspective there is not mush you can do about it.

I've worked around this in my own situation by lowering all filenames and directory names in my project. Then it works as **intended** (because not working as intended is called a bug, not a design flaw). Anyone googling into this might try doing the same thing if you are using msbuild & _FILE_ macro.

I absolutely do not agree with calling this **bug** a design issue because simply Windows and macOS are not made for case-sensitivity. So i would still like to urge you to reconsider, please reopen the bug and fix it.!

Thanks a lot!

**Comment by bpasero** [comment] 2019-10-10 04:16
This is NOT as simple as you might think. Read https://github.com/microsoft/vscode/issues/12448#issuecomment-508526893 and all comments below.

**Comment by Alias-777** [comment] 2019-10-10 06:06
It's as simple as you want it to be. But you obviously not going to please everyone. But now i'm using one Visual Studio product msbuild & c++ to generate debug output and an other VScode which is not 100% incompatible with it. (unless you lower all your source files and directories).

I do - personally - think that protectionism towards 3dparty plugins is not the right mentality. Everybody who's in software one way or the other needs to know how filesystems work and how case-sensitivity plays a role. If plugin writers don't honer these things it is **not** up to you to make sure that there code won't bug. That would be up to them self, that's how software development works. You write something, you check it, if it bugs, fix it! 

You now have multiple editors to the same file... Which is a bug, so please fix it. 

Not fixing this for the sake of 3rdparty plugins seems kind of weird.

As a developer I receive updates of the libraries/frameworks that I use all the time. And every now and then one of these updates breaks/bugs my code. That's not a very pleasant thing, but also not anything that can't be fixed. It would be wrong of those developers not to implement new things or fix there bugs just to please me. The industry was not made to please developers, it was made to please the users! And from a VScode perspective, i'm a user.

But mostly the simple fact that developers can change there plugins code/bugs and users cant change the VScode behavior, should make the decision more easy.

No matter what you do, there's always a minority who suffers for the majority. That's part of life. It becomes unethical if the majority needs to suffer for the minority. Users are many, plugin developers are few.

Is it more easy for you now? ;p

have a lovely day,. 
Thanks!

**Comment by Alias-777** [comment] 2019-10-10 06:43
But, do you really need to redesign the whole plugin api just for this?

when opening a tab(aka editor or view): pseudo code.

    // when a new file opens
    function requestNewTab(tab newTab) {
        tab t = allTabs.contains(newTab.filename).insensitive();
        if (t!=null) {
            // we have a tab with a same name (insensitively checked)
           if (t->filename==newTab.filename.sensitive) {
               // the tab is already opened on all systems
               // link newTab to t
               linkTab(newTab, t)
           } else {
               dir = listdir(t->dir());
               // iterate over the dir and see if both t and newTab exist
               if (dir->checkUniqueFiles(t, newTab) [
                    // NewTab is unique, so open a new tab
                    open(newTab)
               } else {
                   // the file is not unique, link it to T
                   linkTab(newTab, t)
              }
        } else {
            // there was no tab with the same insensitive name
            open(newTab)
        }
    }


If you do something like that it should work on all the systems! Regardless of there case-sensitivity. And you don't need to redesign any 3rdparty api's. You can keep them as is. 

You should always separate filesystem api's and actual calls because of these kind of things. For example: you might want to fix separators on windows prior to opening a file. This will ensure it to work on all Windows systems and users/developers can then just use forward slashes.

The trick of writing good code is to expect everything but assume nothing. And keep backend (actual filesystem calls) and frontend (api design) separated.

Is it really not as simple as this?

Best Regards!

**Comment by LAK132** [comment] 2019-10-10 22:12
Compromise: When clicking a link in the terminal, *that link* is converted to its canonical form. If the canonical form is already open, then it will trivially jump to that editor right? If its not, then the user probably had the wrong version open to begin with. This way you aren't constantly polling the file system for canonical forms, just once when the user clicks the link. This would 100% fix my issues, I already have the case correct files open, it's just the C++ debug binaries that have the case wrong.
