### ISSUE TITLE
i cant run option properly

### ISSUE THREAD

**Issue by 123AmAy** [microsoft/vscode#200151] opened 2023-12-06 15:19 UTC
Type: <b>Bug</b>

sir as i am using run option its showing something like launch 

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
file-script-extension|fle|0.0.4
c-cpp-runner|fra|9.2.1
fig-unreleased|kir|0.0.1
cmake-tools|ms-|1.16.31
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
vscode-cpptest|Par|2023.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
scripts|zjf|0.0.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2023-12-06 17:02
Duplicate of #200152

**Closed by mjbvz** 2023-12-06 17:02 UTC
