### ISSUE TITLE
cannot prompt automatically for style properties in html

### ISSUE THREAD

**Issue by lhj19791428** [Microsoft/vscode#69956] opened 2019-03-07 13:22 UTC
- VSCode Version:1.31.1(use setup)
- OS Version:Windows_NT x64 6.3.9600

Steps to Reproduce:

1. my visual studio code version is 1.31.1(use setup)
2. I enter  <div style=""></div> in html file, 
3. I enter "text-align" css properties on style, cannot show any prompts.
4. after saving the html(a.html), open another  file and return to the previous html file(a.html).
5. focus on the style, when i input "text-align" again, an automatic prompt will appear,
6. above problem, entering any css properties will reproduce the problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lhj19791428** [comment] 2019-03-08 12:47
@joaomoreno can you reproduce the issue?

**Comment by aeschli** [comment] 2019-03-08 14:22
@lhj19791428 Can you add the sample code?

With prompt you probably mean quick suggestions.
Note that quick suggestions only appear when tying at the end of a word.

**Comment by lhj19791428** [comment] 2019-03-12 00:44
thanks for your response,
to following the code
![image](https://user-images.githubusercontent.com/4802807/54166845-058c9200-44a2-11e9-9280-5798cb9690f4.png)

i type "t", nothing prompted,
but i move the focus to other place ,
![image](https://user-images.githubusercontent.com/4802807/54166977-9b282180-44a2-11e9-9d4e-bb2e700b7105.png)


and then the focus goes back to where it was before, and delete the 't' letter,  i type 't' again, show prompt, the following picture
![image](https://user-images.githubusercontent.com/4802807/54167054-fc4ff500-44a2-11e9-817d-83e76b702dea.png)

looking forward to your reply;

**Comment by lhj19791428** [comment] 2019-03-18 23:52
@aeschli  can you reproduce the issue base on above the sample?

**Comment by aeschli** [comment] 2019-03-19 08:20
I'm afraid I'm not. I also don't have any idea why you would see a different behaviour.
![html-quicksuggest](https://user-images.githubusercontent.com/6461412/54590309-1bf99700-4a28-11e9-83fc-b31fef613284.gif)

**Comment by lhj19791428** [comment] 2019-03-19 23:56
Thanks for your response and demo,
I found the different node between your operation and  mine,
1、The double quotation marks are autocomplete after enter  ’style=‘ in my environment,
2、If i delete double quotation marks and manual input,  and then i enter "text-align" css properties on style,  show prompts. 

hopefully , this will help you reproduce the issue. thanks

**Comment by aeschli** [comment] 2019-03-20 09:43
@lhj19791428 Oh, interesting. Can you `Disable All Installed Extensions` to see if this is caused by an extension?
![image](https://user-images.githubusercontent.com/6461412/54674523-e377bd00-4afc-11e9-8705-477e03c4130c.png)

**Comment by lhj19791428** [comment] 2019-03-25 01:14
thanks for you response,
I uninstall all the installed extensions, the question persists,  and then i uninstall VS code ，install the latest version,
![image](https://user-images.githubusercontent.com/4802807/54889178-3a570b00-4ede-11e9-9d7d-ba476c50d76f.png)

unfortunately , the problem persists :(

**Comment by aeschli** [comment] 2019-03-25 09:58
Can you paste your example source code? And give key by key instructions.
What are your settings?
You say you type `=` and this automatically inserts the quotes as well? That's not something we do.

**Comment by lhj19791428** [comment] 2019-04-01 14:36
![GIF](https://user-images.githubusercontent.com/4802807/55335507-c6b09180-54cd-11e9-9f1d-b410a257199c.gif)

please the above operation, you type = and this automatically inserts the quotes, this time, i type "text", without any prompt. 
but while deleted the quotes and enter the quotes manually , show prompt,
and then i don't have any plug-ins installed in my environment.

**Comment by lhj19791428** [comment] 2019-04-02 15:50
@aeschli  looking forword to your response :)

**Comment by aeschli** [comment] 2019-04-03 08:08
@lhj19791428 Thanks now I see it!

**Comment by aeschli** [comment] 2019-04-03 08:34
Fixed by https://github.com/Microsoft/vscode-html-languageservice/commit/53cf62b77025a33af58b903ad6bc6d92306913ca

**Closed by aeschli** 2019-04-03 08:34 UTC
Labels: html

**Comment by aeschli** [comment] 2019-04-03 10:37
To verify, in a html file,
- do code assist after `<div sty`
- select `style`
- this should complete to style="" with code completion window reopened again

**Comment by lhj19791428** [comment] 2019-04-03 13:13
@aeschli  Yes, thanks for your response, looking forword to the next product patch.
