### ISSUE TITLE
Inconsistent behavior of symlink folder

### ISSUE THREAD

**Issue by LucaMoschella** [Microsoft/vscode#62913] opened 2018-11-11 10:19 UTC
- VSCode Version: 1.28.2
- OS Version: Linux (Manjaro)

Steps to Reproduce:

    mkdir folder
    ln -s folder folder_symlink
    touch folder/test.txt

1. Open in vscode the folder_symlink
2. Open test.txt
3. Open folder/test.txt and close it

Bug:
The file is duplicated with the symlink path and the real path in the _go to file_:
![image](https://user-images.githubusercontent.com/11019190/48311626-d244ff80-e5a2-11e8-9ee1-776e521c25e2.png)

The problem stays even if you close and re-open VSCode.

In my current project it stays even after switching folders some times, I don't know why.
It can become quite a problem with the breadcrumbs if the real path is on another disk:
![image](https://user-images.githubusercontent.com/11019190/48311658-7af35f00-e5a3-11e8-8960-c88dc6d32b6c.png)
Moreover, I'm pretty sure that I didn't open any files from their "real path" in this project...

**Comment by bpasero** [comment] 2018-11-18 17:05
This currently works as designed, we purely differentiate files only by there full resource (and thus path). If the path is different, even though they point to the same underlying file, we do not detect that case.

Closing as duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-11-18 17:05 UTC
