### ISSUE TITLE
Screen reader detects tab as space

### ISSUE THREAD

**Issue by leonardder** [microsoft/vscode#108729] opened 2020-10-15 11:44 UTC
Steps to Reproduce:

1. In notepad, Write a line that starts with a tab, e.g. `	hello`
2. Paste it into VS Code Insiders 1.51.0 (most recent build as of today)
3. The tab is reported as one space

Does this issue occur when all extensions are disabled?: Yes

**Comment by leonardder** [comment] 2020-10-15 11:44
cc @isidorn I tested this with NVDA and Narrator. I'm not sure how recent this is. Also did a quick search for a similar issue but couldn't find any.

**Comment by isidorn** [comment] 2020-10-19 10:18
@leonardder thanks for filling this, however duplicate of https://github.com/microsoft/vscode/issues/104673

**Closed by isidorn** 2020-10-19 10:18 UTC
