### ISSUE TITLE
ES7 React autocompletion

### ISSUE THREAD

**Issue by przemo098** [Microsoft/vscode#18343] opened 2017-01-09 21:55 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

Hello guys I'm currently writing code and I'm trying to use ES7 

![image](https://cloud.githubusercontent.com/assets/6282239/21785006/24b7b7a8-d6be-11e6-8342-80bc4ccfbf26.png)

Here I got autocompletion but inside component is nothing..

![image](https://cloud.githubusercontent.com/assets/6282239/21785095/6d4e49dc-d6be-11e6-8215-083709a82d0a.png)

Even that if I use old way everything works perfectly:

![image](https://cloud.githubusercontent.com/assets/6282239/21785143/9ccd04a0-d6be-11e6-8da4-f7c7b5a3dbe4.png)

Changing import to require is not helping..
I installes typings `typings install dt~react --global --save`

Someone know what is going on ?

**Comment by mjbvz** [comment] 2017-01-09 21:58
Looks like a duplicate of #18281

**Closed by mjbvz** 2017-01-09 21:58 UTC
Labels: duplicate

**Comment by przemo098** [comment] 2017-01-09 22:09
Guys I'm using JavaScript with ES7..
Not typescript...

**Comment by mjbvz** [comment] 2017-01-09 22:12
@przemo098 The TypeScript project is used to analyze both JS and TS code. The same root issue repos in both languages:

```js
class Foo {
    implementThis() {}
}

class Bar extends Foo {
    implementT  // no suggestions when typing here
}
```

I've moved this issue to TypeScript for tracking: https://github.com/Microsoft/TypeScript/issues/13372

Thanks
