### ISSUE TITLE
Long delay when previewing Markdown files

### ISSUE THREAD

**Issue by NiekPas** [Microsoft/vscode#15798] opened 2016-11-21 11:26 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10 build 14393.447

Steps to Reproduce:

1. Create a markdown files with approx. 30 lines of text.
2. Press ctrl+shift+v to preview the file

There is a very noticable delay before the preview is shown (~3 seconds). Of course this is not a huge issue, but this delay has not always been there (it was introduced, going from memory, around VS Code version 1.5 or 1.6), which leads me to believe it's a bug rather than an inevitable consequence of the parsing process.

**Comment by mjbvz** [comment] 2016-11-21 22:08
@NiekPas Can you please share the markdown file you are seeing this issue for? 30 lines of text is not a lot, and I'm unable to repo this in my testing using reasonably sized files (even up to 10000 lines takes under a second).

Thanks.

**Comment by NiekPas** [comment] 2016-11-22 13:43
@mjbvz I have this issue with every file, but only the first time I preview it. I just previewed a single-line file, and it took the same amount of time. The file in question: [2016-11-22.zip](https://github.com/Microsoft/vscode/files/606502/2016-11-22.zip).

I will verify whether I can reproduce on my other machine later.

**Comment by mjbvz** [comment] 2016-11-22 19:15
@NiekPas A small delay on first open is expected since we only load the required markdown to html converter packages when they are first used.

On an OSX machine with Code 1.7.1, this delay is only a quarter second, but the delay is a bit greater on my Windows 10 machine (more around 1 second or so), even though it has an SSD and is pretty beefy.  

If you can, try on some other machines as well and please let me know if those also show the same problem. Some general machine info, such as type and speed of drive, will also help with the investigation.

Thanks.

**Comment by NiekPas** [comment] 2016-11-23 08:50
The machine I am currently experiencing this on is an ASUS R556L.

Processor: Intel Core i5-5200U @ 2.20GHz
RAM: 8GB ddr3-1600
Storage: 250GB SSD (Kingston RBU-SC100S37240GE)

**Comment by mjbvz** [comment] 2017-09-07 22:46
I'm only able to reproduce this on windows and most of the time seems to be spend in the `require` calls. This is not something we can directly address besides minimizing the number of files that are loaded upfront. I've started doing this in but the majority of this issue seems to be upstream with Node on windows

Closing as upstream

**Closed by mjbvz** 2017-09-07 22:46 UTC
Labels: markdown, perf, upstream
