### ISSUE TITLE
Broken Debug Console

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#108202] opened 2020-10-06 18:40 UTC
- Reload the window, ensure debug console is never opened
- Start debugging a launch config with `"internalConsoleOptions": "neverOpen"` or a launch config that fails to start/attach so that the debug console is never opened
  - I first hit this with a launch config that started normally, but I don't know how that's possible
- Start a second launch config that also never causes the debug console to open
- Open the debug console
- It's empty

Get a notification for this error

![image](https://user-images.githubusercontent.com/323878/95244342-ae0def80-07c6-11eb-992b-9b5c58f9333e.png)

Hit the error in the debugger:

```
getActionViewItem (repl.ts:462)
actionViewItemProvider (viewPaneContainer.ts:299)
actionViewItemProvider (toolbar.ts:87)
(anonymous) (actionbar.ts:276)
push (actionbar.ts:261)
(anonymous) (toolbar.ts:167)
setActions (toolbar.ts:166)
setActions (viewPaneContainer.ts:483)
renderHeader (viewPaneContainer.ts:306)
render (paneview.ts:213)
render (viewPaneContainer.ts:271)
onDidAddViewDescriptors (viewPaneContainer.ts:1362)
create (viewPaneContainer.ts:1069)
create (panecomposite.ts:44)
showComposite (compositePart.ts:219)
doOpenComposite (compositePart.ts:150)
openComposite (compositePart.ts:114)
doOpenPanel (panelPart.ts:493)
openPanel (panelPart.ts:498)
run (panelActions.ts:189)
runAction (actions.ts:202)
run (actions.ts:194)
onClick (actionViewItems.ts:163)
(anonymous) (actionViewItems.ts:143)
processImmediate (internal/timers.js:439)
```

Seems that if the "select repl" action is valid at the time the viewPaneContainer is being created for the debug console, then it will invoke the actionViewItemProvider which assumes the tree has been instantiated already, but it hasn't yet, and it throws.

**Comment by roblourens** [comment] 2020-10-06 18:43
From https://github.com/microsoft/vscode/commit/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4

**Comment by roblourens** [comment] 2020-10-06 19:01
Actually it is easy to repro with the "VS Code" launch config. I guess I'm not sure what determines whether the debug console is shown or not when debugging starts because it is not shown for those configs.

**Comment by roblourens** [comment] 2020-10-06 19:20
But I don't understand why the debug console is not opened for me when I start this config. 

- Turn on "Smart" auto attach
- Run "Launch VS Code"
- I see it attach to some session that ends before it attaches to "Launch VS Code"
- Debug console does not open

---

- Disable auto attach
- Run "Launch VS Code"
- Debug console does open

And when the debug console does not open early and get a chance to initialize itself, that's when this bug is triggered.

**Comment by roblourens** [comment] 2020-10-06 22:07
It looks like @isidorn is out, so going ahead with a fix.

Decided to just revert the fix for https://github.com/microsoft/vscode/issues/107860

I think the right fix would be to figure out what the current session is without looking at the tree, which I think is possible but I'll leave that for @isidorn. Or, create the tree earlier.

**Comment by roblourens** [comment] 2020-10-06 23:57
Simplest repro steps

- Reload window, don't open debug console
- Set Auto attach -> Smart
- Run the "VS Code" launch config
- Try to open the debug console

**Comment by connor4312** [comment] 2020-10-07 01:15
@JacksonKearl did you verify when you merged? If not I was going to

**Closed** 2020-10-07 01:49 UTC
Labels: bug, candidate, debug

**Comment by roblourens** [comment] 2020-10-07 01:50
It will need to be verified but the build is not released yet

**Comment by roblourens** [comment] 2020-10-07 03:48
Now it is

**Comment by isidorn** [comment] 2020-10-19 11:50
@roblourens thanks for jumping on this and for finding the root cause.
