### ISSUE TITLE
GitHub Commit error after June VS Code update

### ISSUE THREAD

**Issue by Schlermie** [microsoft/vscode#154449] opened 2022-07-08 04:37 UTC
Issue Type: <b>Bug</b>

After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.

This is the command output:

> git -c user.useConfigOnly=true commit --quiet
Error: Bad status code: 500
    at ClientRequest.<anonymous> (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:487:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
Please supply the message using either -m or -F option.

This is the Git Log:

[2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms]
[2022-07-08T04:36:17.835Z] Error: Bad status code: 500
    at ClientRequest.<anonymous> (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:487:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
Please supply the message using either -m or -F option.
[2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms]
[2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.56GB free)|
|Process Argv|--crash-reporter-id b6d5ae76-63a0-48eb-aa8e-87fb9f164435|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1001902341
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by makz159** [comment] 2022-07-08 08:37
> Issue Type: Bug
> 
> After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.
> 
> This is the command output:
> 
> > git -c user.useConfigOnly=true commit --quiet
> > Error: Bad status code: 500
> > at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
> > at Object.onceWrapper (node:events:510:26)
> > at ClientRequest.emit (node:events:390:28)
> > at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
> > at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> > at Socket.socketOnData (node:_http_client:487:22)
> > at Socket.emit (node:events:390:28)
> > at addChunk (node:internal/streams/readable:315:12)
> > at readableAddChunk (node:internal/streams/readable:289:9)
> > at Socket.Readable.push (node:internal/streams/readable:228:10)
> > error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
> > Please supply the message using either -m or -F option.
> 
> This is the Git Log:
> 
> [2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms] [2022-07-08T04:36:17.835Z] Error: Bad status code: 500 at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470) at Object.onceWrapper (node:events:510:26) at ClientRequest.emit (node:events:390:28) at HTTPParser.parserOnIncomingClient (node:_http_client:623:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) at Socket.socketOnData (node:_http_client:487:22) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'. Please supply the message using either -m or -F option. [2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms] [2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]
> 
> VS Code version: Code 1.69.0 ([92d25e3](https://github.com/microsoft/vscode/commit/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9), 2022-07-07T05:28:36.503Z) OS version: Windows_NT x64 10.0.19043 Restricted Mode: No
> 
> System Info
> Extensions (6)
> A/B Experiments

I have the same issue. I can commit by doing "git commit -m "message for the commit". I guess the issue is that when you just do "F1 - > commit" it doesn't give you the option to supply a message and therefor you get the error " Please supply the message using either -m or -F option."

**Comment by makz159** [comment] 2022-07-08 11:31
> Issue Type: Bug
> 
> After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.
> 
> This is the command output:
> 
> > git -c user.useConfigOnly=true commit --quiet
> > Error: Bad status code: 500
> > at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
> > at Object.onceWrapper (node:events:510:26)
> > at ClientRequest.emit (node:events:390:28)
> > at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
> > at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> > at Socket.socketOnData (node:_http_client:487:22)
> > at Socket.emit (node:events:390:28)
> > at addChunk (node:internal/streams/readable:315:12)
> > at readableAddChunk (node:internal/streams/readable:289:9)
> > at Socket.Readable.push (node:internal/streams/readable:228:10)
> > error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
> > Please supply the message using either -m or -F option.
> 
> This is the Git Log:
> 
> [2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms] [2022-07-08T04:36:17.835Z] Error: Bad status code: 500 at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470) at Object.onceWrapper (node:events:510:26) at ClientRequest.emit (node:events:390:28) at HTTPParser.parserOnIncomingClient (node:_http_client:623:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) at Socket.socketOnData (node:_http_client:487:22) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'. Please supply the message using either -m or -F option. [2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms] [2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]
> 
> VS Code version: Code 1.69.0 ([92d25e3](https://github.com/microsoft/vscode/commit/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9), 2022-07-07T05:28:36.503Z) OS version: Windows_NT x64 10.0.19043 Restricted Mode: No
> 
> System Info
> Extensions (6)
> A/B Experiments

After reading the documentation I now understand the behavior :)
https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor

so just untick this if you want the old experience 
![image](https://user-images.githubusercontent.com/52601614/177984157-a0944ca5-8c3d-4cfa-9b07-b44aa03d0ed8.png)

**Comment by lszomoru** [comment] 2022-07-08 16:49
I have been trying to reproduce this issue in-house without much luck. Would you be able to create a gif recording (https://gifcap.dev) while reproducing the issue? Thank you very much in advance!

**Comment by CryptoCherie** [comment] 2022-07-08 18:59
ah thank you so much I have been trying to figure out how to fix this 500 error code for 2 days! Go figure all you have to do is untick a box....

**Comment by lszomoru** [comment] 2022-07-08 19:28
@CryptoCherie, apologies for the caused inconvenience. While toggling the setting to disable the new flow is a valid workaround, I do want to get to the bottom of the root cause and fix it. Are you able to reproruce the 500 error in all repositories or only some? If only in some, is there anything specific about those repositories? Could you please share a recording (https://gifcap.dev) when you reproduce the issue? Thank you!

**Comment by MarkAHamann** [comment] 2022-07-08 19:32
I get this pressing the new commit button with no text in the textbox using a remote environment where the other side has git version 2.7.4.

It hangs indefinitely, and to recover I need to reload the window.

Ideally, if there I'd no text I'd get a pop-up warning like if I try to commit with no staged changes.

**Comment by lszomoru** [comment] 2022-07-08 19:34
@MarkAHamann, thanks for the additional details.
Which extension are you using to connect to the remote environment? Remote-Containers? Remote-SSH? Remote-WSL?

**Comment by MarkAHamann** [comment] 2022-07-08 19:47
Remote-ssh. Windows 10 at my desk connected to Linux beast somewhere in the building.

**Comment by MarkAHamann** [comment] 2022-07-08 20:04
Also, it seems to be opening .git/COMMIT_EDITMSG into my open editors. Empty, of course, because I didn't have a commit message in the text box.

**Comment by lszomoru** [comment] 2022-07-08 20:13
@MarkAHamann, if you do not specify a commit message in the input than VS Code will open the `COMMIT_EDITMSG` file in an editor tab. you can use that to enter the commit message and close the editor to complete the commit operation. Closing the editor when it's contents are empty will cancel the commit operation. Is that the behaviour that you are seeing?

**Comment by MarkAHamann** [comment] 2022-07-08 20:21
Hmm... I hadn't really noticed that new file opening up until later. I just did a commit, got the open file, added a message, hit ctrl-s to save, and now it's still hung indefinitely. 

Wait, I just hit the little x to close the editor and it completed.

OK, I see what's going on now. Working as expected (though with new expectations). Pebcak.

**Comment by Danniel13** [comment] 2022-07-08 20:37
[makz159] Thanks a lot my friend @makz159, I could solved this bug c.

**Comment by Schlermie** [comment] 2022-07-09 02:16
@lszomoru See attachment for my gif recording while I reproduce the error. I've got a fairly streamlined setup. I don't have many VS Code extensions beyond Python, Jupyter and Git History. I haven't done any further attempts to rectify the problem since I filed the report last night; however, I now realize the problem seems to stem from my neglect to include a comment with my Commit. It would be nice if VS Code could fail more gracefully though. Thanks for your support. 

![Recording 2022-07-08 at 19 10 53](https://user-images.githubusercontent.com/22927507/178087845-0aa4f0b8-52f4-4e84-9c77-eeec4c233110.gif)

**Comment by Schlermie** [comment] 2022-07-09 02:48
@lszomoru I confirmed the Commit proceeds successfully if I simply enter a message in the empty Message field directly above the Commit button before I hit the Commit button. 

Do you want me to close this ticket or leave it open to track graceful resolution of the error reporting?

**Comment by Gauravself** [comment] 2022-07-09 04:24
> Issue Type: Bug
> 
> After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.
> 
> This is the command output:
> 
> > git -c user.useConfigOnly=true commit --quiet
> > Error: Bad status code: 500
> > at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
> > at Object.onceWrapper (node:events:510:26)
> > at ClientRequest.emit (node:events:390:28)
> > at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
> > at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> > at Socket.socketOnData (node:_http_client:487:22)
> > at Socket.emit (node:events:390:28)
> > at addChunk (node:internal/streams/readable:315:12)
> > at readableAddChunk (node:internal/streams/readable:289:9)
> > at Socket.Readable.push (node:internal/streams/readable:228:10)
> > error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
> > Please supply the message using either -m or -F option.
> 
> This is the Git Log:
> 
> [2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms] [2022-07-08T04:36:17.835Z] Error: Bad status code: 500 at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470) at Object.onceWrapper (node:events:510:26) at ClientRequest.emit (node:events:390:28) at HTTPParser.parserOnIncomingClient (node:_http_client:623:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) at Socket.socketOnData (node:_http_client:487:22) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'. Please supply the message using either -m or -F option. [2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms] [2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]
> 
> VS Code version: Code 1.69.0 ([92d25e3](https://github.com/microsoft/vscode/commit/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9), 2022-07-07T05:28:36.503Z) OS version: Windows_NT x64 10.0.19043 Restricted Mode: No
> 
> System Info
> Extensions (6)
> A/B Experiments

Provide a message or text while committing Files

**Comment by lszomoru** [comment] 2022-07-09 07:39
@Schlermie, thank you very much for the recording. We should keep the issue opened as this is clearly a problem that I have to address. One should be able to go through the commit flow even if a commit message is not provided [as illustrated](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor) in the release notes.

**Comment by lszomoru** [comment] 2022-07-09 08:05
@Schlermie, could you please reproduce the problem again, and then invoke the `Developer: Toggle Developer Tools` command and share the contents of the console? I have tracked down that code that fails but I need to understand the exact error that occurs as currenrly we only log the status code. Thank you!

**Comment by lszomoru** [comment] 2022-07-09 14:32
I have further looked at the code and my current hypothesis is that we are failing to open the `COMMIT_EDITMSG` file. At the moment we are assuming that the last argument passed to `git-editor-main.ts` is the path of this file but I think that assumption might be wrong. I am looking at testing out the fix first in Insiders before we port it to Stable so that it is included in the upcoming recovery release.

**Comment by FranciscoPombal** [comment] 2022-07-09 20:15
Could https://github.com/microsoft/vscode/issues/154503 be related to this one?

**Comment by Schlermie** [comment] 2022-07-09 23:30
> @Schlermie, could you please reproduce the problem again, and then invoke the `Developer: Toggle Developer Tools` command and share the contents of the console? I have tracked down that code that fails but I need to understand the exact error that occurs as currently we only log the status code. Thank you!

@lszomoru See attachment for my error reproduction, followed by invoking the Developer Tools.

![Recording 2022-07-09 at 16 28 09](https://user-images.githubusercontent.com/22927507/178125773-6f0c5651-b5b8-4374-a10a-23c0232714d8.gif)

**Comment by Schlermie** [comment] 2022-07-09 23:33
> @Schlermie, could you please check the version of git that you are using by running `git --version`? thanks!

'git --version' returns this:
**git version 2.28.0.windows.1**

**Comment by babakazizi** [comment] 2022-07-10 23:28
> Issue Type: Bug
> 
> After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.
> 
> This is the command output:
> 
> > git -c user.useConfigOnly=true commit --quiet
> > Error: Bad status code: 500
> > at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
> > at Object.onceWrapper (node:events:510:26)
> > at ClientRequest.emit (node:events:390:28)
> > at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
> > at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> > at Socket.socketOnData (node:_http_client:487:22)
> > at Socket.emit (node:events:390:28)
> > at addChunk (node:internal/streams/readable:315:12)
> > at readableAddChunk (node:internal/streams/readable:289:9)
> > at Socket.Readable.push (node:internal/streams/readable:228:10)
> > error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
> > Please supply the message using either -m or -F option.
> 
> This is the Git Log:
> 
> [2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms] [2022-07-08T04:36:17.835Z] Error: Bad status code: 500 at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470) at Object.onceWrapper (node:events:510:26) at ClientRequest.emit (node:events:390:28) at HTTPParser.parserOnIncomingClient (node:_http_client:623:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) at Socket.socketOnData (node:_http_client:487:22) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'. Please supply the message using either -m or -F option. [2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms] [2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]
> 
> VS Code version: Code 1.69.0 ([92d25e3](https://github.com/microsoft/vscode/commit/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9), 2022-07-07T05:28:36.503Z) OS version: Windows_NT x64 10.0.19043 Restricted Mode: No
> 
> System Info
> Extensions (6)
> A/B Experiments

**Comment by Michael-Obele** [comment] 2022-07-11 07:27
Thanks a million, this recent change they made was driving me crazy for the past 2 days. I use custom hot keys to commit and push my code, so I expect the text box to appear and ask for a message. This post just saved my sanity.

**Comment by Michael-Obele** [comment] 2022-07-11 07:27
> > Issue Type: Bug
> > After updating VS Code with the June update, I get an Error (Bad status code: 500) when I try to commit my code udpates to GitHub.
> > This is the command output:
> > > git -c user.useConfigOnly=true commit --quiet
> > > Error: Bad status code: 500
> > > at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470)
> > > at Object.onceWrapper (node:events:510:26)
> > > at ClientRequest.emit (node:events:390:28)
> > > at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
> > > at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> > > at Socket.socketOnData (node:_http_client:487:22)
> > > at Socket.emit (node:events:390:28)
> > > at addChunk (node:internal/streams/readable:315:12)
> > > at readableAddChunk (node:internal/streams/readable:289:9)
> > > at Socket.Readable.push (node:internal/streams/readable:228:10)
> > > error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'.
> > > Please supply the message using either -m or -F option.
> > 
> > 
> > This is the Git Log:
> > [2022-07-08T04:36:17.835Z] > git -c user.useConfigOnly=true commit --quiet [363ms] [2022-07-08T04:36:17.835Z] Error: Bad status code: 500 at ClientRequest. (c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor-main.js:1:470) at Object.onceWrapper (node:events:510:26) at ClientRequest.emit (node:events:390:28) at HTTPParser.parserOnIncomingClient (node:_http_client:623:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) at Socket.socketOnData (node:_http_client:487:22) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) error: There was a problem with the editor '"c:\Users\scott\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\git-editor.sh"'. Please supply the message using either -m or -F option. [2022-07-08T04:36:17.891Z] > git config --get-all user.name [52ms] [2022-07-08T04:36:17.948Z] > git config --get-all user.email [54ms]
> > VS Code version: Code 1.69.0 ([92d25e3](https://github.com/microsoft/vscode/commit/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9), 2022-07-07T05:28:36.503Z) OS version: Windows_NT x64 10.0.19043 Restricted Mode: No
> > System Info
> > Extensions (6)
> > A/B Experiments
> 
> After reading the documentation I now understand the behavior :) https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor
> 
> so just untick this if you want the old experience ![image](https://user-images.githubusercontent.com/52601614/177984157-a0944ca5-8c3d-4cfa-9b07-b44aa03d0ed8.png)

Thanks a million, this recent change they made was driving me crazy for the past 2 days. I use custom hot keys to commit and push my code, so I expect the text box to appear and ask for a message. This post just saved my sanity.

**Comment by connor4312** [comment] 2022-07-11 17:36
@lszomoru closing this for verification since the associated PR was merged.

**Closed by connor4312** 2022-07-11 17:36 UTC
Labels: bug, git, candidate, new release

**Comment by lszomoru** [comment] 2022-07-12 09:47
@rubensa, are you able to reproduce the problem with the latest Insiders release?

**Comment by rubensa** [comment] 2022-07-12 09:56
> @rubensa, are you able to reproduce the problem with the latest Insiders release?

@lszomoru I'll try to check.

**Comment by Deepakumar07** [comment] 2022-07-15 15:17
Thanks @makz159 , its resolved at my end
