### ISSUE TITLE
Typescipt editor stopped highlighting code in `${embedded code snippers}`

### ISSUE THREAD

**Issue by rzio** [Microsoft/vscode#14933] opened 2016-11-03 19:55 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14955
- Extensions:

|Extension|Author|Version|
|---|---|---|
|MochaSnippets|Alan|0.0.1|
|tslint|eg2|0.5.39|
|final-newline|samverschueren|0.2.0|
|sort-lines|Tyriar|1.1.0|

---

Steps to Reproduce:

1.
2.

**Comment by waderyan** [comment] 2016-11-03 21:44
@rzio can you provide a code sample for what you are seeing?

**Comment by rzio** [comment] 2016-11-03 22:57
[test.txt](https://github.com/Microsoft/vscode/files/570258/test.txt)
Just rename the file to test.ts and open in vscode.

**Comment by j-oliveras** [comment] 2016-11-03 22:57
Duplicate of #14926?

**Comment by rzio** [comment] 2016-11-03 22:58
Yep. Duplicate.

**Closed** 2016-11-03 22:58 UTC
Labels: js, needs more info
