### ISSUE TITLE
Allow adding non-workspace files from working files

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6142] opened 2016-05-05 20:21 UTC
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder
2. Open a file outside that folder
3. Drag the non-workspace file from working files to your open folder in explorer

You cannot move the non-workspace file into your project from working files. I'm guessing this might be by design based on #4893

**Comment by bpasero** [comment] 2016-05-06 06:13
Yeah, duplicate of #4893

**Closed by bpasero** 2016-05-06 06:13 UTC
Labels: files, v-test
