### ISSUE TITLE
Formatting Html Component Files Does Not Work

### ISSUE THREAD

**Issue by FoxNicolas** [Microsoft/vscode#5660] opened 2016-04-22 15:56 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a simple html component (Angular, Aurelia, etc.) file. For example: "my-component.html"
2. Set its content to something like: "`<template><div><div><img /></div></div></template>`" all on one line.
3. Press Alt+Shift+F to format the code.
4. Nothing happens.

Notes:

- Formatting other file types like TS, JS, and C# works fine.
- Formatting full HTML files works. For example, "`<html><head></head><body><div><div></div></div></body></html>`" formats fine.
- Code successfully recognizes the "Language Mode" for the component file but still doesn't work.

**Comment by aeschli** [comment] 2016-04-25 07:38
duplicate of #5426 

Please check my comment in #5426. You need the change the formatter settings if you want the content of `template` formatted.

**Closed by aeschli** 2016-04-25 07:38 UTC
Labels: html

**Comment by FoxNicolas** [comment] 2016-04-25 17:43
Sorry for not finding that on my own and thank you for your help @aeschli !
