### ISSUE TITLE
resourceScheme not available for editor/context

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#8766] opened 2016-07-05 18:17 UTC
- VSCode Version: 1.3.0-insider
- OS Version: Win7

@jrieken I'm trying to add specific editor/context menus to my TextDocumentContentProvider using my scheme 'hexdump', but this never show up when I right-click on the editor.

```javascript
  "contributes": {
    "commands": [
      {
        "command": "hexdump.hexdumpFile",
        "title": "Show hexdump for file"
      },
      {
        "command": "hexdump.editValue",
        "title": "Edit the value under the cursor"
      }
    ],
    "menus": {
      "explorer/context": [
        {
          "command": "hexdump.hexdumpFile"
        }
      ],
      "editor/context": [
        {
          "when": "resourceScheme == 'hexdump'",
          "command": "hexdump.editValue"
        }
      ]
    },
```

![image](https://cloud.githubusercontent.com/assets/7251102/16594774/e7166ad6-42b9-11e6-89b3-7d6010bb96a6.png)

Any idea what's happening ? You can take a look at the code in https://github.com/stef-levesque/vscode-hexdump

**Comment by jrieken** [comment] 2016-07-05 20:32
Sorry, for now we don't support the context keys `resourceScheme` and `resourceLangId` in the editor context menu but only for the title area and in the explorer. That's was the downside of a workaround we have to make to mitigate an oversight that was to risky to fix properly...

What you could do is to use the `editorLangId` context key which is (only) available in the editor. For instance you can make you virtual document URIs be like `hexdump:some/path/some/file.HEX` and associate a language to that ending. The language can be just a name and identifier - tho a special coloriser for hex would be cool.

**Comment by jrieken** [comment] 2016-07-05 20:32
@bpasero fyi

**Comment by stef-levesque** [comment] 2016-07-05 20:36
Ah I see... The language proposal seems like a good solution, I'll see what I can do.

Thanks for the quick response !

**Comment by bpasero** [comment] 2016-07-06 04:47
Related: https://github.com/Microsoft/vscode/issues/8579

**Comment by jrieken** [comment] 2016-07-13 07:57
Closing this as duplicate of #8579 since that's *all* what has to be done

**Closed by jrieken** 2016-07-13 07:57 UTC
Labels: bug, duplicate
