### ISSUE TITLE
I am getting this in the Java compilation . I don't Know Why ? 

### ISSUE THREAD

**Issue by S-P-Ks** [microsoft/vscode#117063] opened 2021-02-19 16:50 UTC
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support
- VS Code Version:
- OS Version:

I am getting this error . I don't Know why ?
Can Someone help me here ?

**Comment by IllusionMH** [comment] 2021-02-19 16:54
/duplicate of #115888

See https://github.com/microsoft/vscode/issues/115888#issuecomment-780762061 for workaround

**Closed** 2021-02-19 16:55 UTC
Labels: *duplicate
