### ISSUE TITLE
Themes don't apply to preview tab's icon

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#95916] opened 2020-04-22 19:57 UTC
Hey there! thanks a lot for a the awesome app as always.

- VSCode Version: 1.44.2
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

I guess these screenshots clearly show the problem:

<img width="755" alt="Screen Shot 1399-02-04 at 00 19 01" src="https://user-images.githubusercontent.com/2157285/80027162-8cf76200-84f8-11ea-9165-cc2ae12508f9.png">

<img width="671" alt="Screen Shot 1399-02-04 at 00 22 56" src="https://user-images.githubusercontent.com/2157285/80027195-9b457e00-84f8-11ea-9ad4-4109dd41e67b.png">

- The theme is [this](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-04-27 22:37
Duplicate of #90616

Webviews currently don't use real theme icons so their icons cannot be changed by extensions

**Closed by mjbvz** 2020-04-27 22:37 UTC
