### ISSUE TITLE
把logo给老子换回去！不然就用回sublime，换的什么臭logo！！！

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#36895] opened 2017-10-25 12:22 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.9.0-deepin12-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|0.0.2
python|don|0.7.0
Go|luk|0.6.66

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-25 17:43
This is not an appropriate or constructive way to file feedback. Please see our guide on how to submit issues properly: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md

Closing as duplicate of #35783

**Closed by mjbvz** 2017-10-25 17:43 UTC
Labels: extensions

**Comment by athinboy** [comment] 2017-10-26 01:52
@biij5698 
别在这丢中国人的脸了！

**Comment by MinghaoNi** [comment] 2017-10-26 04:49
@biij5698 
既没幽默感，又丢人！
