### ISSUE TITLE
Regression of 58388: Files imported from F5 tests are loaded twice on Windows (once via 'C:\', once via 'c:\') 

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#69569] opened 2019-02-28 01:15 UTC
Issue Type: <b>Bug</b>

https://github.com/Microsoft/vscode/issues/58388 appears to have regressed in Insiders (I can't repro it in stable).

Repro (Windows only):
1) git clone https://github.com/Microsoft/vscode-azurearmtools.git
2) npm run all
3) tests pass
4) load in vscode
5) set debug config to Launch Tests
6) F5
!) tests fail:
```
rejected promise not handled within 1 second: AssertionError [ERR_ASSERTION]: Setup failed
extensionHostProcess.js:700
stack trace: AssertionError [ERR_ASSERTION]: Setup failed
extensionHostProcess.js:700
    at mySetup.then (c:\Users\stephwe\Repos\vscode-azurearmtools\test\Treeview.test.ts:56:49)
```
This is caused by extension.bundle.ts getting loaded twice instead of once:
7) set a breakpoint at the top of extension.bundle.ts
8) F5
!) The breakpoint gets hit twice
EXPECTED: It should be cached and therefore only get hit once
It doesn't think it's cached because once it's loaded as "c:\Users\stephwe\Repos\vscode-azurearmtools\dist\extension.bundle.js" and the second time as "C:\Users\stephwe\Repos\vscode-azurearmtools\dist\extension.bundle.js".

VS Code version: Code - Insiders 1.32.0-insider (69249882e8717cf111e04330390107282e337559, 2019-02-27T21:19:19.351Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (15.65GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-antlr4|mik|2.1.1
vscode-cosmosdb|ms-|0.10.0
extension-manifest-editor|ms-|0.1.5
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|1.0.0
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.5.2
vscode-sort-json|ric|1.13.0
sort-lines|Tyr|1.8.0
win-ca|uko|2.4.0

</details>

**Comment by weinand** [comment] 2019-02-28 17:31
I don't see how VS Code is involved here: "extension.bundle.ts" is user code. Who should "cache" this?

**Comment by StephenWeatherford** [comment] 2019-02-28 22:36
Please see the original bug. Yes I am referring to node.js caching. This was a vscode problem before, although I don't understand the details. Nothing has changed in my code, and it works in stable but fails in Insiders.

> I suggest that you investigate where in your code the file is loaded and why the drive letters have different casing in those locations.

The two places this comes from are a) an import in my code, b) vscode loading test files.

**Comment by bpasero** [comment] 2019-03-01 13:06
@isidorn since you have pushed the fix previously. Maybe this is a regression from the work we did this milestone to use node.js path module everywher?

**Comment by isidorn** [comment] 2019-03-01 19:14
Yeah probably using node.js path breaked this.
We should check the casing of `extensionDevelopmentPath` as that was the cause last time.

**Comment by bpasero** [comment] 2019-03-02 10:15
@StephenWeatherford I cannot reproduce this issue, I just tried with Code Insiders:

Version: 1.32.0-insider (system setup)
Commit: 804373ac4d5c84e96c8086cee5b9be132df88837
Date: 2019-03-01T18:22:35.336Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Test runs fine:

![image](https://user-images.githubusercontent.com/900690/53680473-7a124480-3cdc-11e9-8ccf-187719991411.png)


Looks like an issue with your setup?

**Comment by aeschli** [comment] 2019-03-02 19:54
I might have caused that with https://github.com/Microsoft/vscode/blob/1e17319bfde04aefb34fd1b0648868dca208fa2c/src/vs/workbench/api/node/extHostExtensionService.ts#L617

Should always use 'resources.originalFSPath' which does not normalize anything.

I'll push a fix so you can verify that this is the problem.

**Comment by aeschli** [comment] 2019-03-02 20:07
Created https://github.com/Microsoft/vscode/pull/69716 as 1.32 candidate.

**Comment by aeschli** [comment] 2019-03-02 20:47
@StephenWeatherford I created a build that contains the my change. Can you verify if that fixes the issue?
[win32-x64-1.32.0-insider](https://az764295.vo.msecnd.net/insider/a053f98c80b2ddc88364469dea9069a3e1134c31/VSCode-win32-x64-1.32.0-insider.zip)
[win32-ia32-1.32.0-insider](https://az764295.vo.msecnd.net/insider/a053f98c80b2ddc88364469dea9069a3e1134c31/VSCode-win32-ia32-1.32.0-insider.zip)

**Comment by StephenWeatherford** [comment] 2019-03-03 02:24
Yep, that fixes it, thanks!  Any change you can create a unit test or something to make sure it doesn't break again?

**Closed** 2019-03-04 05:05 UTC
Labels: bug, candidate

**Comment by aeschli** [comment] 2019-03-06 16:15
verified by @StephenWeatherford
