### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43475] opened 2018-02-12 07:06 UTC
Issue Id: <b>6297e0aa-6693-c1dc-1a92-9880326445ab</b><br /><br />*Versions* <br />- 1.20.0<br />-  519088548b09221e9d590d2e10e14ec6d27ac79a<br />-  f2b21097100fc2fc0e84cc34f453c9a85a49a2bb<br />*Stack* <br />TypeError: Cannot read property 'size' of undefined<br />[/vs/base/browser/ui/list/listView.ts#L228:27 (size)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/list/listView.ts#L228:27 (size))<br />[/vs/base/browser/ui/list/listWidget.ts#L967:34 (elementHeight)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/list/listWidget.ts#L967:34 (elementHeight))<br />[/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L413:19 (reveal)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L413:19 (reveal))<br />[/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L377:7 (layoutSelectDropDown)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L377:7 (layoutSelectDropDown))<br />[/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L353:53 (renderSelectDropDown)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L353:53 (renderSelectDropDown))<br />[/vs/base/browser/ui/contextview/contextview.ts#L156:35 (render)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/contextview/contextview.ts#L156:35 (render))<br />[/vs/platform/contextview/browser/contextViewService.ts#L36:19 (show)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/platform/contextview/browser/contextViewService.ts#L36:19 (show))<br />[/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L351:27 (showContextView)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L351:27 (showContextView))<br />[/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L160:9 (showSelectDropDown)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L160:9 (showSelectDropDown))<br />

**Comment by octref** [comment] 2018-02-13 05:55
Actually seems to be caused by https://github.com/Microsoft/vscode/commit/9a5b6ebc08d530463203c75a92e0ea49b6becc73 so giving to @bpasero

**Comment by bpasero** [comment] 2018-02-13 07:10
@cleidigh fyi this came in as error telemetry

**Comment by cleidigh** [comment] 2018-02-15 02:10
@bpasero 
this looks like getElementHeight might be called on an uninitialized select.  the telemetry Stack trace doesn't give me a lot to go on and I cannot really reproduce since I cannot see telemetry.

is there any way to get more information on this?

**Comment by bpasero** [comment] 2018-02-15 05:25
@cleidigh no, not more than the stack is what we have

**Comment by isidorn** [comment] 2018-02-26 11:01
We might fix it with https://github.com/Microsoft/vscode/pull/44368
Though let's wait and see if @joaomoreno want to fix it on that level.

**Comment by joaomoreno** [comment] 2018-02-26 16:19
#44368 doesn't fix it, it just silently returns 0, which is very often not the right thing to do.

https://github.com/Microsoft/vscode/commit/db616b33097cb578cea924046fc38efc00d1c58f throws a more specific error message. List users should not pass in anything other than valid indexes to the list.

**Comment by joaomoreno** [comment] 2018-02-26 16:19
The bug is in [here](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L413). What happens if `getFocus()` returns `[]`?

**Comment by cleidigh** [comment] 2018-03-06 05:43
@joaomoreno 
@bpasero 
@isidorn 
@Tyriar 

As I mentioned in the other issue #45078 (same case and some were description)  the root cause it's not the Focus, it's the fact that we somehow end up with a misconfigured list.  I don't want to fix this with just a null check since it would still leave us with an error and an empty select box.

I can now reproduce this thanks to @IlyaBiryukov .
Somehow when terminal.dispose it's called from the extension , the select list gets destroyed .

I'm looking at the sequence now to see how the other terminals get destroyed incorrectly.

**Comment by cleidigh** [comment] 2018-03-07 01:42
@Tyriar 
I've done some tracing on this and determined that when the terminal created with an extension is disposed the current selected index passed to selectbox.selectOptions can be out of range by one
IF a user has created a terminal and then subsequently removes the terminal created by the extension
with terminal.dispose

The terminal index remains correct if the terminal created by the extension has focus when disposed.

Some of the behavior is in _removeTab but I don't think this is where it should be fixed.  I don't want to make any assumptions on this so I wanted your insight/determination on where to be fixed.

Simplest reproduction:

- manually create one terminal
- create terminal through the extension interface
- manually create a second terminal
- now there are three total terminals, terminal three - manually created has focus in the list and tab
- have the extension do terminal.dispose on the extension created terminal
- Drop-down header will become blank and an error thrown
- with the tracing I can see the call to setOptions has the correct options and length but the selected option is off by one (2) when it should be (1).

**Comment by cleidigh** [comment] 2018-03-15 03:47
@bpasero 
@Tyriar 
I'm overdue to fix this for the February recovery but, I have a couple issues:

- there are at least two problems:
1) improved boundary checking needed in new and old select box code
2) there seem to be at least one probably two scenarios where the terminal makes a
setOptions call with the selected option out of bounds

I did a fair amount of trace and debugging (see above)  and I am confident
with the fact that when a terminal is deleted from an extension this happens.
I can add boundary checking, question is what to do with an out of bound option

I wanted to add a new notification but I cannot call from the widget due to layering
I cannot return an error without changing all clients to deal with the error and perhaps notify the user.

it's not clear to me yet if #45300 @Tyriar references, but I bet he is correct and this is a related issue.

a force fix bounds checking selected and setting to zero can take care of the issue of the extension removing the terminal.  This ends up making the active terminal somewhat arbitrary and it is not the root cause of the problem.

I think I need some guidance on your best practices for error handling (telemetry, console and/or notifications)  understanding the way you guys like to do this is key for  future submissions.

I also need to know how you want to handle the clients, @Tyriar I don't think I know enough to fundamentally change your terminal instance handling.

**Comment by Tyriar** [comment] 2018-03-15 17:51
@cleidigh I'm a bit swamped at the moment but I'll try get to this for March

**Comment by cleidigh** [comment] 2018-03-16 01:54
@Tyriar 
no problem.  I'll continue to try and investigate, hopefully it won't be a problem if I have a couple of simple questions.  I think if I use balance checking on the select box side and force a terminal selection upon an extension 's disposal we will end up with a situation where the terminal has one perspective on selection in the select box has a different one so I don't think that really works.  The end requirement is both sides need the correct perspective 

do you agree?

regardless I'll keep pecking away at it  /-;)

**Comment by cleidigh** [comment] 2018-04-23 01:11
Fixed With #47445

**Closed by cleidigh** 2018-04-23 01:11 UTC
Labels: bug, dropdown, error-telemetry
