### ISSUE TITLE
 TypeScript language service died unexpectedly 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by CatoAntonsen** [Microsoft/vscode#20253] opened 2017-02-09 07:34 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|minify|HookyQR|0.3.0|
|team|ms-vsts|1.113.0|
|debugger-for-chrome|msjsdiag|2.5.2|

---

Steps to Reproduce:

1.Open a folder on a network share (\\\\server\sharename)
2. The error "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes" keeps popping up on top of the screen (actually showing, hiding, showing, hiding frequently) constantly

**Comment by devdoomari** [comment] 2017-02-09 07:41
what's your typescript version / output of tsc ?

**Comment by nguymin4** [comment] 2017-02-09 07:42
Sounds similar to #13874

**Comment by CatoAntonsen** [comment] 2017-02-09 09:17
Version 2.1.6

**Comment by rmunn** [comment] 2017-02-09 09:23
Are you using SharePoint? Lots of people have been reporting this same issue, which looks like it's caused by https://github.com/Microsoft/TypeScript/issues/13874

**Comment by CatoAntonsen** [comment] 2017-02-09 09:47
Yes, this is a library in SharePoint Online.

**Comment by mjbvz** [comment] 2017-02-09 19:27
Yes, this looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/13874

1.9.1 includes TypeScript 2.1.6 which should fix the crash. Please update and let me know if you still see this.

**Closed by mjbvz** 2017-02-09 19:27 UTC
