### ISSUE TITLE
Wrong type of comments for React JSX property

### ISSUE THREAD

**Issue by iou90** [Microsoft/vscode#23071] opened 2017-03-23 03:55 UTC
VSCode Version: 1.10.2
OS Version: macOS 10.12.3
Steps to Reproduce:

position cursor on a line of JSX property
press command + / to comment out the line
It will insert {/* */} instead of //

I think this issue relates [Wrong type of comments for React code](https://github.com/Microsoft/vscode/issues/6461)
It works correctly for previous version and it may break after 1.9.0 with this commit: [[jsx][tsx] Wrong type of comments for React code. Fixes](https://github.com/Microsoft/vscode/commit/d826ad6e4fd52d9997fd144531c952af13218146)

**Comment by mjbvz** [comment] 2017-03-23 04:55
I believe this is a duplicate of #20874

**Closed by mjbvz** 2017-03-23 04:55 UTC
Labels: bug, duplicate, javascript, typescript

**Comment by OliverJAsh** [comment] 2017-04-11 17:46
I'm not sure this is a dupe of #20874 as the bug occurs regardless of whether one is using spread or not.

**Comment by mjbvz** [comment] 2017-04-11 18:03
Yes, #20874 is not specific to using a spread. I've updated that bug's title to make this clear
