### ISSUE TITLE
Extension host crashed with OOM

### ISSUE THREAD

**Issue by pftbest** [Microsoft/vscode#33805] opened 2017-09-04 16:05 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.12.8-2-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
toml|be5|0.0.3
python|don|0.7.0
vscode-rust|kal|0.4.2
Go|luk|0.6.63
cpptools|ms-|0.12.3
java|red|0.9.0
rust|rus|0.2.2
code-spell-checker|str|1.3.9
gitblame|wad|2.1.0

---

Steps to Reproduce:
Happens randomly, low reproduce rate.

Reproduces without extensions: Unknown

log:
```
/opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing
scanNext @ /opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] (node:2302) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.logExtensionHostMessage @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29
/opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing
scanNext @ /opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356
/opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing
scanNext @ /opt/visual-studio-code/resources/app/node_modules/vscode-textmate/release/main.js:2356
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29 Extension Host
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/opt/visual-studio-code/libnode.so]
 2: 0x7f9394daf1b7 [/opt/visual-studio-code/libnode.so]
 3: 0x7f9394b0aa87 [/opt/visual-studio-code/libnode.so]
 4: 0x7f9394b0aa05 [/opt/visual-studio-code/libnode.so]
 5: v8::internal::Factory::NewTransitionArray(int) [/opt/visual-studio-code/libnode.so]
 6: 0x7f93945b049a [/opt/visual-studio-code/libnode.so]
 7: 0x7f939471f4a4 [/opt/visual-studio-code/libnode.so]
 8: 0x7f939471c36e [/opt/visual-studio-code/libnode.so]
 9: 0x7f939471c138 [/opt/visual-studio-code/libnode.so]
10: 0x7f939473541f [/opt/visual-studio-code/libnode.so]
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/opt/visual-studio-code/libnode.so]
12: 0x7f9394724834 [/opt/visual-studio-code/libnode.so]
13: 0x7f9394727eb8 [/opt/visual-studio-code/libnode.so]
14: 0x7f939472c504 [/opt/visual-studio-code/libnode.so]
15: 0x7f939472bc21 [/opt/visual-studio-code/libnode.so]
16: 0x7f939472abc7 [/opt/visual-studio-code/libnode.so]
17: 0x7f939468a9e5 [/opt/visual-studio-code/libnode.so]
18: 0x312286f04167

<--- Last few GCs --->

[2302:0x12a12aac8000]  2305088 ms: Mark-sweep 1404.8 (1480.6) -> 1404.8 (1479.6) MB, 1688.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1689 ms) last resort 
[2302:0x12a12aac8000]  2306771 ms: Mark-sweep 1404.8 (1479.6) -> 1404.8 (1479.6) MB, 1682.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x29dc103af729 <JS Object>
    0: builtin exit frame: defineProperty(aka defineProperty)(this=0x3c29fca82311 <undefined>,0x42bd7645119 <an Object with map 0x38cfdc391c99>,0x3c29fca83019 <String[4]: hour>,0x42bd76450e1 <an Object with map 0x38cfdc383179>)

    1: toDateTimeOptions(aka toDateTimeOptions) [native i18n.js:~912] [pc=0x312287668859](this=0x3c29fca82311 <undefined>,S=0x3c29fca82311 <undefined>,bN=0x29dc103c8741...


index.js:5 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
onError @ index.js:5
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:28
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t.onExit @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:29
```

**Comment by alexandrudima** [comment] 2017-09-28 09:50
@pftbest This appears to be a crash caused by the extension host process running out of memory. The most likely cause for this would be an extension with memory leaks. What extensions are you using, have you found any reproducible steps? (perhaps working with large files, etc.) ?

**Comment by pftbest** [comment] 2017-09-28 11:37
I was working with [rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) extension at the time of crash.

But I've not seen this crash anymore, so maybe they fixed it.

**Comment by alexandrudima** [comment] 2017-09-28 12:15
I will close this issue for now, as there is no code change I can do at this time to avoid OOM crashes... If you spot it again, and can give some steps, we can try to reproduce and investigate the root cause.

**Closed by alexandrudima** 2017-09-28 12:15 UTC
Labels: needs more info
