### ISSUE TITLE
File explorer in sidebar stays grey after renaming a file

### ISSUE THREAD

**Issue by 4kochi** [Microsoft/vscode#3822] opened 2016-03-08 09:31 UTC
When renaming a file the file explorer becomes grey. After hitting ENTER to confirm the changed name, the explorer view (file names) stays grey instead of becoming white. Does appear randomly. The working files view works as expected.

![bildschirmfoto 2016-03-08 um 10 22 18](https://cloud.githubusercontent.com/assets/1742426/13597381/96b56028-e518-11e5-8027-4b78448c13f4.png)

Using vs code v0.10.10-insider (5b5f4db87c10345b9d5c8d0bed745bcad4533135)
Max OSX 10.11.3

**Comment by bpasero** [comment] 2016-03-08 10:13
@joaomoreno does this ring a bell?

**Comment by joaomoreno** [comment] 2016-03-08 10:17
Duplicate of #3569

**Closed by joaomoreno** 2016-03-08 10:17 UTC
