### ISSUE TITLE
new Feature Request : double click file name in the taps to go full screen and vise versa

### ISSUE THREAD

**Issue by hosred** [Microsoft/vscode#39201] opened 2017-11-27 17:21 UTC
new Feature Request : double click file name in the taps to get the taps to full screen and vise versa , like eclipse IDE behavior . (this not Zen mode or normal full screen)

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
java|red|0.14.0
vscode-java-debug|vsc|0.3.1
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-11-28 05:38
Duplicate of https://github.com/Microsoft/vscode/issues/16927

**Closed by bpasero** 2017-11-28 05:38 UTC
Labels: workbench, workbench-layout
