### ISSUE TITLE
Terminal incorrectly wraps after 80 chars in remote ssh (bash)

### ISSUE THREAD

**Issue by mtene** [microsoft/vscode#122844] opened 2021-05-03 11:27 UTC
I'm experiencing incorrect line wrapping in the integrated terminal, identical to what is described in https://github.com/microsoft/vscode/issues/106668

This happens in a remote SSH connection where the shell is bash. If I switch to a workspace on the local machine, the problem does not manifest itself (git bash on Windows 10).

**Comment by meganrogge** [comment] 2021-05-03 14:53
What version of vscode are you using?

**Comment by mtene** [comment] 2021-05-05 12:42
Hi, sorry for being that brief. I'm currently using:

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment] 2021-05-05 15:31
Duplicate of #120810

**Closed** 2021-05-05 15:32 UTC
Labels: *duplicate
