### ISSUE TITLE
VS code actively reloads WebView's when tab is not in focus, any state changes to the WebView are cleared. This issue has existed since 2017.

### ISSUE THREAD

**Issue by okikio** [microsoft/vscode#108465] opened 2020-10-10 19:14 UTC
Issue Type: <b>Bug</b>

1. Open release notes, scroll down.
2. Open an extention Readme in a new tab, scroll down.
3. When you switch back to the release notes and vice versa, both the release notes and the extension readme have reloaded, and the scroll position is now at the top.

This might not seem like an important bug, but an unresolved issue was created in 2017, and still hasn't been solved. I've seen a bunch of other issues be closed and point to the 2017 issue, but it still has not yet been fixed, so, please before you close this issue look into this problem, it is infuriating to no end. 

Thanks for reading.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.16GB free)|
|Process Argv|--crash-reporter-id e8ef7672-e4cd-4d07-85ee-8327f961b3fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-monorepo-workspace|fol|1.2.0
vscode-edge-devtools|ms-|1.0.9
nunjucks|ron|0.3.0

</details>

**Comment by mjbvz** [comment] 2020-10-12 23:09
Duplicate of #27498 and #94945

**Closed by mjbvz** 2020-10-12 23:09 UTC
