### ISSUE TITLE
VS Code stopped auto completing on Update 1.60.1. -> Javascript React

### ISSUE THREAD

**Issue by bearsworth** [microsoft/vscode#133503] opened 2021-09-21 07:00 UTC
I'm using a Mac and for the past year have been able to get auto complete to work flawlessly on all updates. On this new update, suddenly auto complete using Javascript React no longer works. It works though when I revert back to 1.59.1 which was the previous July update.

At the moment I'm confused on what to change. Maybe an update plays with the auto complete.

On the newer update, I have checked my settings and they are identical to my old settings. I even changed auto complete to 'always' and still nothing works. This new version whatever happened has disabled auto complete for javascript react for me and possibly others.

**Comment by IllusionMH** [comment] 2021-09-21 10:38
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

What exactly you mean under autocomplete? Suggesting components from other files or just adding closing tags when you type `>`?

**Comment by bearsworth** [comment] 2021-09-21 19:59
Hi,

I have disabled extensions. Sorry what I meant was not auto complete but more so does not provide the closing tags. I'm using Javascript and Javascript React and neither of them provides closing tags anymore. They still give suggestions as to what I should type.

**Comment by IllusionMH** [comment] 2021-09-21 21:35
/duplicate of https://github.com/microsoft/TypeScript/issues/45802

You can try this extension to get TS version with the fix until it's released https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Closed** 2021-09-21 21:36 UTC
Labels: needs more info, *duplicate
