### ISSUE TITLE
Expose conditional background color theming for errors, warning, and info icons

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/vscode#108004] opened 2020-10-02 21:52 UTC
Issue Type: <b>Feature Request</b>

Is it possible to have conditional color theming for the Problems "Error", "Warning" and "Info" icons?

![image](https://user-images.githubusercontent.com/4434533/94972502-3c7c2b80-04be-11eb-8b37-76dc4a516f63.png)

Benefit would be to create a more obvious visual indicator, such as a bright background color, when a non-zero count occurs on any of these.

I did check this page https://code.visualstudio.com/api/references/theme-color but did not see anything other than ability to set the foreground color unconditionally.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment] 2020-10-03 07:06
Similar to #74886 but that didn't get enough upvotes to reach Backlog, so is closed. Pinging @misolori

**Comment by aeschli** [comment] 2020-10-12 11:50
duplicate of https://github.com/microsoft/vscode/issues/74886

**Closed by aeschli** 2020-10-12 11:50 UTC
