### ISSUE TITLE
No way to show custom hover in Tree/List via keyboard

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#209642] opened 2024-04-05 14:07 UTC
macOS, VS Code Insiders

1. Focus into explorer
4. Move focus via keyboard
5. Custom hover does not show. There is no command to trigger the custom hover to show 🐛 Like the activity bar, we have to make sure that the custom hover can be accessed in the tree/list only with the keyboard.

**Comment by benibenj** [comment] 2024-04-05 15:49
Would you suggest adding a keybinding to toggle the visibility of the custom hover of the html element which has focus?

**Comment by bpasero** [comment] 2024-04-28 07:04
Isn't this a duplicate of https://github.com/microsoft/vscode/issues/148640 ?

Btw we seem to be having this support for extension provided trees at least:

https://github.com/microsoft/vscode/blob/3012ebac4e47136115c5abc4f75aba8d9777e153/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L297-L302

**Comment by benibenj** [comment] 2024-04-29 13:19
I think it's good to have this one separate to #148640.

**Comment by benibenj** [comment] 2024-04-29 13:23
Solving this for all trees/lists is pretty hard as the tree/list does not know anything about the underlying elements. For extension trees it is much easier as they all consist of a label which the `treeview` creates and controls.

**Comment by benibenj** [comment] 2024-04-29 13:28
One option could be to utilize the `IListAccessibilityProvider` to get the tooltip. Currently it already provides `getAriaLabel(element: T): string | IObservable<string> | null;`

**Closed** 2024-05-03 14:11 UTC
Labels: accessibility, workbench-hover
