### ISSUE TITLE
Untitled editors hint shows surplus thing

### ISSUE THREAD

**Issue by tqacyp** [microsoft/vscode#123366] opened 2021-05-08 14:19 UTC
- VS Code Version: 1.56.0
- OS Version: Windows 21H1

Steps to Reproduce:

1.Open VS code
2.New a file

Does this issue occur when all extensions are disabled?: Yes

![picture1](https://img-kysic-1258722770.file.myqcloud.com/aa0a708ec7d93541407e743575ece061/641b8cd81acb6.png)
![picture2](https://img-kysic-1258722770.file.myqcloud.com/74b976cb5f893974dde67631000ea2ab/7637da246de8d.png)
Why here is a "{0}"?

**Comment by JacksonKearl** [comment] 2021-05-08 17:07
Duplicate of #123152

**Closed** 2021-05-08 17:07 UTC
Labels: new release
