### ISSUE TITLE
Git username and password prompt is not giving

### ISSUE THREAD

**Issue by moshfiqrony** [microsoft/vscode#137153] opened 2021-11-14 05:35 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: October 2021 (version 1.62)
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Do not store your credentials for git
2. Try Git pull or push in using vs code

Problem: I never stored my credentials for git. So whenever I performed any action it asked **username** and **password** from me. I want it that way. But today morning suddenly the prompt is not giving and when I run any git command it says **Access Denied**. 

Then I stored the credentials using `git config --global credential.helper store`. After that it is not prompting for **username** and **password** but not giving **Access Denied** as well.

Is there any bug in VS code that is why it is not prompting me for username and password. So when I store it it doesn't give Access Denied?

**Comment by gjsjohnmurray** [comment] 2021-11-14 07:19
Maybe #137063

Assuming you are on 1.62.2, does it downgrade to 1.62 work around the issue until a fix arrives?

**Comment by moshfiqrony** [comment] 2021-11-15 04:12
Yes @gjsjohnmurray I am 1.62.2

**Comment by gjsjohnmurray** [comment] 2021-11-15 14:42
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-15 14:43 UTC
Labels: *duplicate

**Comment by titipignataro** [comment] 2021-11-16 17:12
I'm going through the same problem
Same versions
    VS Code Version: October 2021 (version 1.62.2-1636665017)
    OS Version: Ubuntu 20.04.3 LTS
The workaround I found was to use default ubuntu terminal when I need to pull or push 
Thankyou for the reply, waiting for correction
