### ISSUE TITLE
Preferences Sync gear icon/number confusing

### ISSUE THREAD

**Issue by GaryBoone** [microsoft/vscode#94926] opened 2020-04-10 16:00 UTC
The new preferences sync puts a number over the gear icon to notify users that they need to sign in. This design is disturbing and confusing. It's disturbing because it's an optional feature. There is no requirement to do any action. There is no need to notify users about an unnecessary action. It disturbs unnecessarily.

It's confusing because as a user, I'm accustomed to the number on the gear icon alerting me that the editor has to be restarted for an update. But in this case, there was no update and selecting "Check for Updates..." revealed no new updates. So it's not clear what the notification was about. Worse, there was no obvious way to find out what it was about. Worse still, there was no obvious way to make it go away. (I'm unable to reproduce the start-up notification, but cmd-shift-p has a sign-in flow in it's drop-down menu.)

**Comment by IllusionMH** [comment] 2020-04-10 16:09
/duplicate of #94822

Please provide additional feedback there if needed.

**Closed** 2020-04-10 16:10 UTC
Labels: *duplicate
