### ISSUE TITLE
format-on-type saves the nesting level

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#10252] opened 2016-08-06 23:30 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 Redstone 1

Steps to Reproduce:
1. Run VS Code with `--disable-extensions`.
2. Set the `"editor.formatOnType": true` option in the editor settings.
3. Copy any code with whitespace at the beginning of the line.
4. Paste the code and press <kbd>Enter</kbd> (several times).

![2016-08-07_02-20-35](https://cloud.githubusercontent.com/assets/7034281/17459575/b9378432-5c46-11e6-8eea-13553c15d392.gif)

It seems this is to some extent relates to #7617.

**Comment by jrieken** [comment] 2016-08-08 07:29
@mrmlnc In what language is that? And what is your expected behaviour? And what is the whole code snippets?

**Comment by mrmlnc** [comment] 2016-08-08 07:37
@jrieken,

Language: `JavaScript`
Code snippert:

```js
'use strict';

const path = require('path');

module.exports = {
  rulesDirectory: [
    path.join(path.dirname(require.resolve('tslint-eslint-rules')), 'dist/rules'),
    path.dirname(require.resolve('tslint-microsoft-contrib'))
  ],
  rules: {
    'no-consecutive-blank-lines': true, // no-multiple-empty-lines
    'no-trailing-whitespace': true, // no-trailing-spaces
    'one-variable-per-declaration': true, // one-var + one-var-declaration-per-line
    '': true,
    '': true,  // <- Copy&Paste
    '': true
  }
};
```

It seems to me that after formatting spaces should be dropped to the level of nesting.

**Comment by jrieken** [comment] 2016-08-08 07:57
Thanks. It seems to be an issue with the indent logic. When hitting enter we first derive the indent for the new line and only then fire off 'format on type' which target the just completed line, not the line below...

**Comment by alexandrudima** [comment] 2016-08-08 14:07
@jrieken Sorry I don't get it -- Enter **must** be implemented synchronous and it does not wait for any language smarts -- because it could take between 5ms and 2hrs to get a reply to the format. Not sure what you're suggesting I should do?

**Comment by jrieken** [comment] 2016-08-08 14:12
Yeah, in total agreement. I believe my previous comment explains the same.

**Comment by alexandrudima** [comment] 2017-12-15 16:09
This appears to be fixed in the meantime.

**Closed by alexandrudima** 2017-12-15 16:09 UTC
Labels: as-designed, bug
