### ISSUE TITLE
Find command does not autopopulate search box with selected text in a notebook cell, different from regular editor behavior

### ISSUE THREAD

**Issue by vanossj** [microsoft/vscode#129699] opened 2021-07-28 14:24 UTC
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.02.2
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Remote

## Expected behaviour

When text is highlighted in the notebook view, pressing the find keyboard shortcut, e.g. ctrl+f, will populate the find search box with the highlighted text. This is how VS Code behaves for normal editor windows

## Actual behaviour

find search box is shown with last searched text

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. start a notebook
2. add some text to a cell
```Some random text```
3. double click the text `random` to select it
4. press ctrl+f to activate the find command
5. find search box is displayed but the prepopulated text is not `random`

![Copy text _ Untitled Project](https://user-images.githubusercontent.com/8310169/127339252-e4b8baee-3c4c-4777-9cd5-d58eb0d1c67e.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rebornix** [comment] 2021-08-02 19:54
/duplicate of https://github.com/microsoft/vscode/issues/129319

**Closed** 2021-08-02 20:01 UTC
Labels: *duplicate, feature-request, notebook
