### ISSUE TITLE
No JSON schema validation in 1.76.0

### ISSUE THREAD

**Issue by shuebner** [microsoft/vscode#176591] opened 2023-03-09 05:04 UTC
Does this issue occur when all extensions are disabled?: did not try

- VS Code Version: 1.76.0
- OS Version: Windows 11 Pro 10.0.22621

# Steps to Reproduce:

1. Install or update to 1.76.0
2. establish JSON schema validation via `.vscode/settings.json`, e. g. 
```json
{
  "json.schemas": [
    {
      "fileMatch": [
        "/samples/*.json",
      ],
      "url": "/schemas/sample.schema.json"
    }
  ]
}
```

# Actual Behavior:

no validation happens whatsoever
no error is displayed anywhere I can see

# Expected Behavior:

the globbed files are validated with the configured schema.
In 1.75.1, it still worked as expected.

# Relations

I guess this is related to #175803.

**Comment by Igorgro** [comment] 2023-03-16 09:16
@aeschli If we speak about #175803 - it still happens in 1.76.2

**Comment by ebw44** [comment] 2023-03-21 01:38
I have a similar problem with json schema not working at all, except for some small part in 'settings.json'. And even for 'settings.json', I get `Unknown Configuration Setting` for "json" object. The "[json]" object is allowed but nothing inside seems to be allowed. And tooltips are not working.
I was unable to get ride of the problem even disabling all the extension and removing my user setttings.json file.

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by shuebner** [comment] 2023-03-24 06:36
@aeschli Fixed on my Windows machine with 1.76.2.
I also get autocomplete in settings.json.

(I did not try with 1.76.1.)

**Comment by Igorgro** [comment] 2023-04-16 12:32
Still happens on Arch Linux with 1.77.3

**Comment by aeschli** [comment] 2023-05-03 20:49
https://github.com/microsoft/vscode/issues/175803 is unrelated (duplicate of #177142)

Closing the issue as duplicate of https://github.com/microsoft/vscode/issues/176296 (fixed by now)

**Closed by aeschli** 2023-05-03 20:49 UTC
