### ISSUE TITLE
Diff editor not working properly

### ISSUE THREAD

**Issue by xy6321** [microsoft/vscode#93257] opened 2020-03-23 17:21 UTC
Issue Type: **Bug**

1.In Version: 1.43.1, the word is no highlight.
![bug2](https://user-images.githubusercontent.com/29647299/77343738-27834a80-6d6d-11ea-92d3-9b291763ed5b.jpg)

2.But in Version:1.39.2, it has.
![bug1](https://user-images.githubusercontent.com/29647299/77343715-1df9e280-6d6d-11ea-86c4-8181cff38521.jpg)

- VSCode Version: 1.43.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Does this issue occur when all extensions are disabled? Yes

Here is test case:
<details><summary>File1</summary>
<p>

-rw-r--r-- 1 www root 2629516615 Mar 11 00:00 20200310.access.log
-rw-r--r-- 1 www root 2688097576 Mar 12 00:00 20200311.access.log
-rw-r--r-- 1 www root 3059667756 Mar 13 00:00 20200312.access.log
-rw-r--r-- 1 www root 3041483472 Mar 14 00:00 20200313.access.log
-rw-r--r-- 1 www root 2849999965 Mar 15 00:00 20200314.access.log
-rw-r--r-- 1 www root 2691161106 Mar 16 00:00 20200315.access.log
-rw-r--r-- 1 www root 2826765702 Mar 17 00:00 20200316.access.log
-rw-r--r-- 1 www root 2799996889 Mar 18 00:00 20200317.access.log
-rw-r--r-- 1 www root 2974733211 Mar 19 00:00 20200318.access.log
-rw-r--r-- 1 www root 3062803881 Mar 20 00:00 20200319.access.log
-rw-r--r-- 1 www root 2892241368 Mar 21 00:00 20200320.access.log
-rw-r--r-- 1 www root 2629516615 Mar 11 00:00 20200310.access.log
-rw-r--r-- 1 www root 2699997576 Mar 12 00:00 20200311.access.log
-rw-r--r-- 1 www root 3056745356 Mar 13 00:00 20200312.access.log
-rw-r--r-- 1 www root 3041483472 Mar 14 00:00 20200313.access.log
-rw-r--r-- 1 www root 2842223165 Mar 15 00:00 20200314.access.log
-rw-r--r-- 1 www root 2691161106 Mar 16 00:00 20200315.access.log
-rw-r--r-- 1 www root 2826765702 Mar 17 00:00 20200316.access.log
-rw-r--r-- 1 www root 2747276889 Mar 18 00:00 20200317.access.log
-rw-r--r-- 1 www root 2974733211 Mar 19 00:00 20200318.access.log
-rw-r--r-- 1 www root 3062803881 Mar 20 00:00 20200319.access.log
-rw-r--r-- 1 www root 2892241368 Mar 21 00:00 20200320.access.log

</p>
</details>

<details><summary>File2</summary>
<p>

-rw-r--r-- 1 root root 2629516615 Mar 11 02:34 20200310.access.log
-rw-r--r-- 1 root root 2688097576 Mar 12 02:54 20200311.access.log
-rw-r--r-- 1 root root 3059667756 Mar 13 03:06 20200312.access.log
-rw-r--r-- 1 root root 3041483472 Mar 14 03:06 20200313.access.log
-rw-r--r-- 1 root root 2842223165 Mar 15 03:14 20200314.access.log
-rw-r--r-- 1 root root 2691161106 Mar 16 02:58 20200315.access.log
-rw-r--r-- 1 root root 2826765702 Mar 17 03:10 20200316.access.log
-rw-r--r-- 1 root root 2747276889 Mar 18 02:59 20200317.access.log
-rw-r--r-- 1 root root 2974733211 Mar 19 03:04 20200318.access.log
-rw-r--r-- 1 root root 3062803881 Mar 20 03:06 20200319.access.log
-rw-r--r-- 1 root root 2892241368 Mar 21 03:10 20200320.access.log
-rw-r--r-- 1 root root 2629516615 Mar 11 02:34 20200310.access.log
-rw-r--r-- 1 root root 2688097576 Mar 12 02:54 20200311.access.log
-rw-r--r-- 1 root root 3059667756 Mar 13 03:06 20200312.access.log
-rw-r--r-- 1 root root 3041483472 Mar 14 03:06 20200313.access.log
-rw-r--r-- 1 root root 2842223165 Mar 15 03:14 20200314.access.log
-rw-r--r-- 1 root root 2691161106 Mar 16 02:58 20200315.access.log
-rw-r--r-- 1 root root 2826765702 Mar 17 03:10 20200316.access.log
-rw-r--r-- 1 root root 2747276889 Mar 18 02:59 20200317.access.log
-rw-r--r-- 1 root root 2974733211 Mar 19 03:04 20200318.access.log
-rw-r--r-- 1 root root 3062803881 Mar 20 03:06 20200319.access.log
-rw-r--r-- 1 root root 2892241368 Mar 21 03:10 20200320.access.log

</p>
</details>

**Comment by gjsjohnmurray** [comment] 2020-03-23 19:42
/confirm

Diff obtained using `File: Compare Active File With...`
Also reproduced on today's Insiders

```
Version: 1.44.0-insider (user setup)
Commit: 0926b534553f3ff2f0cff0a741550a97df199706
Date: 2020-03-23T08:40:59.737Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by bpasero** [comment] 2020-03-24 06:08
I found it easier to save both files (`file1.log` and `file2.log`) and then compare them. I can reproduce too, I am not seeing diffs for these 2 files even though lines differ.

**Comment by alexdima** [comment] 2020-03-24 12:48
Duplicate of #87054 . That issue did not reach 20 upvotes, so it got closed by the bot.

This is not a bug. Our diff editor is not optimized to be used with tabular data, so it does not execute char level diff when a diff chunk is over 20 lines. This is done for performance reasons and makes sense for comparing source code.

**Closed by alexdima** 2020-03-24 12:48 UTC
Labels: bug, confirmed, diff-editor

**Comment by gjsjohnmurray** [comment] 2020-03-24 16:12
@alexdima so it sounds like something changed since 1.39.2, right? Also, maybe reopen this issue now that it's a Backlog Candidate.

**Comment by alexdima** [comment] 2020-03-24 18:01
@gjsjohnmurray Yes, this was an intentional change -- see https://github.com/microsoft/vscode/issues/72823 -- the computation of the character level differences would end up stalling the entire diff computation up to leading to a timeout. And that happened with real source code. This sample does not contain source code, it contains the output of `ls`.

Please also see #87054 -- This stayed in Backlog candidates and did not receive 20 upvotes. Now this issue is a 100% duplicate of #87054 from the same OP. Issue #87054 did not receive a single community upvote in the past 3 months.
