### ISSUE TITLE
enlarge

### ISSUE THREAD

**Issue by MuNaiYi520** [Microsoft/vscode#15608] opened 2016-11-17 01:39 UTC
- VSCode Version:1.7.1
- OS [Version:] win10 14965

Steps to Reproduce:

1. as the picture shows
![image](https://cloud.githubusercontent.com/assets/7043494/20372904/867a1272-aca9-11e6-9d31-1439e77308d7.png)

**Comment by ramya-rao-a** [comment] 2016-11-17 05:27
Closing as duplicate of #15389. The fix is already in the insiders build. You can use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-17 05:27 UTC
