### ISSUE TITLE
Autosave feature terminates notebook execution

### ISSUE THREAD

**Issue by masus04** [microsoft/vscode#220052] opened 2024-07-05 10:20 UTC
### Metadata
- Does this issue occur when all extensions are disabled?: **Yes**
- VS Code Version: **1.91.0**
- OS Version: **Ubuntu 20.04.6 LTS**

### Problem Description
* Running a jupyter notebook cell automatically changes the file as the state of the notebook is saved to the file.
* Both onFocusChange and afterDelay autosave modes will save these changes, even if the cell is still running.
* Saving any changes in the notebook file interrupts the execution of the cell.
* Therefore the autosave feature can stop cell execution and is fundamentally incompatible with jupyter notebooks, especially when debugging.

### Steps to Reproduce basic case
1. Enable autosave in vs code settings
2. Create a jupyter notebook file `test.ipynb`
3. Create a code cell inside the notebook and add any python code to it
4. Add a breakpoint to any of the lines in the cell
5. Debug the cell
6. Navigate to a different file, then return to the notebook
7. The exeecution has been terminated

### Steps to reproduce import case
The execution is stopped instantly if the code in the cell imports and calls another module with a breakpoint, which leads to the module being opened in the editor:

1. Enable autosave in vs code settings
2. Create a file `test.py` and define a function in it
3. Add a breakpoint to any of the lines inside the function in `test.py`
4. Create a jupyter notebook file `test.ipynb` 
5. Create a code cell inside the notebook
6. In the cell, import and call the function from `test.py`
7. Debug the cell
8. The `test.py`file is opened, execution stops at the breakpoint and is terminated silently (as soon as the notebook file is saved in the background) 

### Expected behaviour
Debugging can be completed without any interruption. If necessary, autosaving is delayed until debugging/execution is completed.

**Comment by rebornix** [comment] 2024-07-23 01:20
@DonJayamanne we looked into similar issue in Jupyter with WSL.

**Comment by DonJayamanne** [comment] 2024-07-24 20:25
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15716#issuecomment-2248194807

**Closed by DonJayamanne** 2024-07-24 20:25 UTC
Labels: under-discussion
