### ISSUE TITLE
Variables are not recognized when compiling shellscript

### ISSUE THREAD

**Issue by horizonlines** [microsoft/vscode#177074] opened 2023-03-14 12:18 UTC
Type: <b>Bug</b>

When compiling the shellscript, the ‘$’ sign directly plus the variable name (such as ‘$name‘) will be recognized as a variable and the color (theme) of the variable I set will be applied, but if the variable is written in the form of ${name}, the system cannot recognize it correctly as a variable and give it a color. Even if I change the theme it still happens.
Before the recent update of vscode, I didn't have such problem. Is there any reason for the identification of shellscript variables?

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.89GB (5.53GB free)|
|Process Argv|--crash-reporter-id a3805755-601d-4321-b21a-5997a49fe8f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-syntax|bma|1.0.5
fortranbreaker|eki|0.0.4
code-runner|for|0.12.0
linter-gfortran|for|3.2.0
fortran|Gim|0.2.0
vscode-language-pack-zh-hans|MS-|1.76.2023030809
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
fortran-config-ini|she|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vscodeenable:30660116
pythonb192cf:30669361
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by RedCMD** [comment] 2023-03-15 00:56
https://github.com/microsoft/vscode/issues/176190#issuecomment-1464982285

**Comment by chrmarti** [comment] 2023-03-15 09:43
Closing as duplicate of https://github.com/microsoft/vscode/issues/176190. Thanks.

**Closed by chrmarti** 2023-03-15 09:43 UTC
Labels: triage-needed
