### ISSUE TITLE
Profiles indicator

### ISSUE THREAD

**Issue by andywillis** [microsoft/vscode#174727] opened 2023-02-17 23:20 UTC
At the moment it's not very clear what profile is currently being used. An indicator (i.e. its name) on the status bar would be very useful.

**Comment by gjsjohnmurray** [comment] 2023-02-18 10:21
This is coming, and can already be seen in Insiders.

![image](https://user-images.githubusercontent.com/6726799/219855201-c41cdf42-fecc-455b-959b-cf56960adc2c.png)

**Comment by isidorn** [comment] 2023-02-20 09:04
Thanks. Closing as duplicate of https://github.com/microsoft/vscode/issues/166983
fyi @sandy081

**Closed by isidorn** 2023-02-20 09:04 UTC
