### ISSUE TITLE
Tab Size in Workspace ignored in flavor of User if value is 4

### ISSUE THREAD

**Issue by bansan85** [microsoft/vscode#117565] opened 2021-02-24 11:06 UTC
Issue Type: <b>Bug</b>

  * Test 1 (wrong behavior):

**User preference**
Detect Indentation: False
Editor: Tab Size: 8

**Workspace preference**
Detect Indentation: False
Editor: Tab Size: 4

**.vscode\settings.json**
{
"editor.detectIndentation": false
}

With theses preferences, I have :

![image](https://user-images.githubusercontent.com/9248729/108991173-0a9b7980-7698-11eb-99cf-cda89918d891.png)

  * Test 2 (good behavior):

**User preference**
Detect Indentation: False
Editor: Tab Size: 8

**Workspace preference**
Detect Indentation: False
Editor: Tab Size: 2

**.vscode\settings.json**
{
"editor.detectIndentation": false,
"editor.tabSize": 2
}

With theses preferences, I have :

![image](https://user-images.githubusercontent.com/9248729/108991298-3880be00-7698-11eb-9ade-cc218b66c9c1.png)

  * Test 3 (workaround):

Explicitly write "editor.tabSize": 4 in ".vscode\settings.json"

**User preference**
Detect Indentation: False
Editor: Tab Size: 8

**Workspace preference**
Detect Indentation: False
Editor: Tab Size: 4

**.vscode\settings.json**
{
"editor.detectIndentation": false,
"editor.tabSize": 4
}

![image](https://user-images.githubusercontent.com/9248729/108991523-85649480-7698-11eb-8460-5cf6f250a9f6.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.22GB free)|
|Process Argv|--folder-uri file:///xxxx --crash-reporter-id 9e804104-ae65-40bd-95a1-dc98c1525162|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.2.0
pascal-formatter|ale|2.4.0
sftp|lix|1.12.9
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
cpptools|ms-|1.2.1
cellman-lang|vle|0.0.1

</details>

**Comment by aeschli** [comment] 2021-02-25 13:01
I'm not able to reproduce. In the sample source code, do you use spaces or tabs?
The indent lines look strange in the first example. Assigning to @alexdima

**Comment by alexdima** [comment] 2021-02-25 14:39
@bansan85 Can you please also attach the problematic file? The editor options affect new indentation inserted by the editor, it does not affect existing indentation in files.

**Comment by bansan85** [comment] 2021-02-26 07:41
I use space.
I compress the file because .json is forbidden.

[package.zip](https://github.com/microsoft/vscode/files/6048113/package.zip)

When I click-right > Format Document, the autoformat forces the respect of the visual.

**Comment by alexdima** [comment] 2021-02-26 08:15
Thank you for the file. I have verified the following:

I have configured:
```
"editor.detectIndentation": false,
"editor.tabSize": 8,
```

Then when I open the file you have provided I can see that the editor indentation settings are `Spaces: 8` as expected:
![image](https://user-images.githubusercontent.com/5047891/109273879-13648a80-7813-11eb-9a8d-afa46a0aa4d7.png)

The editor does not modify the file when it is opened. The editor will use these settings only when inserting additional new indentation. So AFAICT everything is working correctly.

**Comment by bansan85** [comment] 2021-02-26 09:40
@alexdima : thanks for your try. Can you try again like my first example?

Configure User preference :
"editor.detectIndentation": false,
"editor.tabSize": 8,

Be sure that in your current folder / workspace ".vscode\settings.json" don't have a ""editor.tabSize": ...".

Configure Workspace preference :
"editor.detectIndentation": false,
"editor.tabSize": 4 (default value)

Workspace preference should be more priority than User preference.

In my file, do you see an indent of 4 ? In my case, I see an indent of 8.

**Comment by alexdima** [comment] 2021-02-26 09:49
@bansan85 I have tried with your steps:
* I have created an empty folder `117565` (without any `.vscode` folder in it).
* I have added `117565/package.json` with the file contents you have provided.
* I have created a file `117565.code-workspace`:
```js
{
	"folders": [
		{
			"path": "117565"
		}
	],
	"settings": {
                "editor.detectIndentation": false,
                "editor.tabSize": 4
        }
}
```
* I have configured my user settings:
```js
{
	"workbench.colorTheme": "Default Light+",
	"editor.detectIndentation": false,
	"editor.tabSize": 8,
}
```
* Then I open the workspace and open the file and it opens with `Spaces: 4`
![image](https://user-images.githubusercontent.com/5047891/109284416-1e71e780-7820-11eb-858f-ed092d25334a.png)

Do you perhaps use an extension which overrides the editor settings? We offer API to extensions and extensions can change the VS Code indentation settings. Does this reproduce for you when disabling all extensions?

**Comment by bansan85** [comment] 2021-02-26 10:21
With your steps, I have the same behavior than you.

Now in 117565.code-workspace, remove the line "editor.tabSize": 4.
Open Preferences via Visual Studio Code. You can see that editor.tabSize is 8 in User and 4 in workspace. And despite that, I have an indent of 8, not 4.

OK, I got it! In Workspace tab, "Tab Size" is tagged "Modified in: User". I didn't get it that "Modified" means "Override". For me, Workspace is a more important setting than User.

**Comment by alexdima** [comment] 2021-02-26 12:18
@bansan85 I'm not sure what the outcome is. I think the outcome is that perhaps you find the settings editor UI confusing? But AFAICT everything works correctly.

**Comment by bansan85** [comment] 2021-02-26 12:55
@alexdima : Yes, I think it's a UI confusion. I will write a better mail with screenshot example to show what confused me.

**Comment by iamCristYe** [comment] 2021-03-04 07:56
possibly a duplicate of #58038 ?

**Comment by roblourens** [comment] 2021-05-25 23:19
If I understand what happened here correctly, I'd call it a dupe of #58038 (thanks @iamCristYe)

**Closed by roblourens** 2021-05-25 23:19 UTC
Labels: needs more info, settings-editor

**Comment by bansan85** [comment] 2021-05-26 20:01
Sorry to not have answer before. Yes, this issue looks to be a duplicated of #58038.

I just want to add an example of how Git Extensions solves this problem:

![image](https://user-images.githubusercontent.com/9248729/119723371-a7271080-be6d-11eb-859e-4982c14ccebf.png)

![image](https://user-images.githubusercontent.com/9248729/119723454-c160ee80-be6d-11eb-81f9-89725ec6e993.png)

![image](https://user-images.githubusercontent.com/9248729/119723503-cde54700-be6d-11eb-93ff-081393e71b6a.png)

I really like it. Except that for me, the last image "Effective" should be read only.
