### ISSUE TITLE
jsconfig {target: ES6} doesn't suppress error on => in .html files

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode#559] opened 2015-11-24 18:57 UTC
Any use of => in a script inside an HTML file produces an error and says you have to set target:ES6 in jsconfig.json. But doing so does not make the error go away - it only applies to .js files

**Comment by jrieken** [comment] 2015-12-04 11:02
Closing as duplicate of #455.

**Closed by jrieken** 2015-12-04 11:02 UTC
Labels: bug, js
