### ISSUE TITLE
VS Code intellisense does not suggest members of js object.

### ISSUE THREAD

**Issue by codingonHP** [Microsoft/vscode#8722] opened 2016-07-04 12:06 UTC
- VSCode Version:1.3.0 - insider
- OS Version: windows 7 enterprise

Steps to Reproduce:

1. Create a simple object like var person = { name = "foo" , age = 24 };
2. write person. (type dot). Nothing happens. Press ctrl + space, it shows no suggestion.

I just want to know is this the desired behavior ? I have tried the same thing in brackets and it works perfectly fine.
![vscode-code-suggestion-not-working](https://cloud.githubusercontent.com/assets/7105293/16559914/c8b2d11c-420d-11e6-938c-6960a8fb5d4b.png)

**Comment by joaomoreno** [comment] 2016-07-05 08:54
Duplicate of #3465

**Closed by joaomoreno** 2016-07-05 08:54 UTC
