### ISSUE TITLE
Keybindings: canceling popup context menu causes second menu to appear

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#23614] opened 2017-03-29 19:23 UTC
OS: Windows 7
Insiders 3-29

- select key binding line with keyboard
- press Shift-F10
- popup menu appears nearby
- press Escape
- first menu disappears
- second menu appears away from line
- this can be closed by Escape

**Comment by cleidigh** [comment] 2017-03-30 17:30
@sandy081 
did a little bit of debugging on this

my initial steps to reproduce have a subtle error
it has to do with the dictation key translation of DragonNaturallyspeaking(my voice program)

Using Shift-F10 works correctly and matches the pop-up context behavior
as found with another list oriented widget(SCM)
Using the Windows app key (at least ViaVoice control) seems to cause
two pop-up context events. I also have to try this with the Windows keyboard
to eliminate Dragon. 

This double event behavior does not occur with SCM using the same voice command/key translation
so I'm still thinking there is an issue here but not a big bug. perhaps the lower keyboard event
propagation propagates to events instead of consuming one and firing the on contextMenu callback

since I cannot use a keyboard this may take me a bit but I'll continue looking at it

**Comment by sandy081** [comment] 2017-11-27 10:37
Duplicate of #31850

**Closed** 2017-11-27 10:38 UTC
Labels: *duplicate, bug, keybindings-editor
