### ISSUE TITLE
Child debug sessions do not always show threads and stack traces

### ISSUE THREAD

**Issue by dgozman** [microsoft/vscode#77841] opened 2019-07-24 01:14 UTC
Hi,

I am trying to use vscode.debug.startDebugging in debug extension, passing a parentSession parameter. This produces a nice tree of debugging sessions in the call stack pane!

Example pseudo-code:
```
// ... get a root session
vscode.debug.startDebugging(folder, config, rootSession);
// ... get a child2 session
vscode.debug.startDebugging(folder, config, child2Session);
```

However, after some trial and error, I've found that non-leaf debugging session does not show any threads (I report multiple over Debug Adapter Protocol's ThreadsRequest). Also, when pausing in such a non-leaf debugging session, I do not see stack frames in the call stack pane, although the session itself is clearly marked as paused. 

Example pseudo-code:
```
// ... get a child3 session
child3.dap.onThreads => return {threads: [thread1, thread2]}
```

Please see screenshot for the reference:

<img width="327" alt="debugSessions" src="https://user-images.githubusercontent.com/9881434/61757302-d9005500-ad74-11e9-99b5-4d3685b7d8a1.png">

- VSCode Version: 1.36.1
- OS Version: macOS 10.14.5

Perhaps I am doing it wrong, but I wasn't able to find any documentation for this, unfortunately.

**Comment by isidorn** [comment] 2019-07-30 13:30
@dgozman  Thank you very much for reporting this.
Can you please create a reproducable sample by forking the vscode mock debug https://github.com/microsoft/vscode-mock-debug
That way I can easily reproduce this issue and try to fix it. And sorry for the slow response I was on vacation

**Comment by dgozman** [comment] 2019-07-31 21:05
@isidorn Here is a [branch](https://github.com/dgozman/vscode-mock-debug/tree/issue-77841) which shows the issue. Please run the "Extension" configuration and issue command "Trigger issue 77841". You will see a tree of debugging sessions in the call stack pane, all of them paused and only the deepest one showing a thread with call stack.

**Comment by isidorn** [comment] 2019-08-02 14:07
Thanks for the branch. I will look into this next week

**Comment by isidorn** [comment] 2019-08-13 14:55
@dgozman good catch. I pushed a fix, please try it out in vscode insiders from Wednesday onward https://code.visualstudio.com/insiders/
And let us know if the issue is fixed for you

**Closed** 2019-08-13 14:54 UTC
Labels: debug, under-discussion

**Comment by dgozman** [comment] 2019-08-28 21:41
@isidorn Thank you, seems to be fixed!

**Comment by isidorn** [comment] 2019-08-29 07:36
@dgozman Thanks for letting us know! Adding verified label.
