### ISSUE TITLE
Plots do not render in jupyter notebooks on remote container

### ISSUE THREAD

**Issue by daniel-scheliga** [microsoft/vscode#126845] opened 2021-06-18 12:41 UTC
## Environment data

- VS Code version: 1.57.0 (Universal)
- Jupyter Extension version (available under the Extensions sidebar): v2021.6.999406279
- Python Extension version (available under the Extensions sidebar): v2021.6.944021595
- OS (Mac) and version: Darwin x64 20.4.0 
- Python and/or Anaconda version: conda 4.10.0
- Type of virtual environment used (virtualenv): Kubernetes Pod
- Jupyter server running: Remote

## Expected behaviour
Plot rendering normally like:
![Screenshot 2021-06-18 at 14 12 02](https://user-images.githubusercontent.com/80388257/122561038-9ec38f00-d041-11eb-918e-8bb419310570.png)

## Actual behaviour
Error loading preloads: Failed to execute 'fetch' on 'Window': Failed to parse URL from ...
![Screenshot 2021-06-18 at 14 14 37](https://user-images.githubusercontent.com/80388257/122561102-b733a980-d041-11eb-859c-076ba0cd3444.png)

(When rendering plots locally instead of on a remote container weird behaviour can also be observed)
![Screenshot 2021-06-18 at 14 12 46](https://user-images.githubusercontent.com/80388257/122561373-11cd0580-d042-11eb-8757-ae95ea217a30.png)

## Steps to reproduce:
```python
from matplotlib import pyplot as plt
import numpy as np
img = np.random.rand(32*32*3).reshape(32,32,3)
plt.imshow(img)
```
Execute cell in a remote container.

Current workaround: choosing different output mimetype manually
![Screen-Recording-2021-06-18-at-14 19 08](https://user-images.githubusercontent.com/80388257/122561959-c36c3680-d042-11eb-9f44-c23cf002325a.gif)

Sadly changing the default display order for mimetypes in settings.json did not solve the problem for me.

**Comment by mjbvz** [comment] 2021-08-06 00:00
@daniel-scheliga Do you still see this issue in the latest VS Code release?

**Comment by seyuboglu** [comment] 2021-08-06 12:49
This is still happening for me

![image](https://user-images.githubusercontent.com/32822771/128512734-7d8fbbe5-3106-4588-be5d-12d4df02b096.png)



Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

**Comment by seyuboglu** [comment] 2021-08-09 14:14
After restarting my pod, I'm seeing a different error message. 

![image](https://user-images.githubusercontent.com/32822771/128720464-13921408-a274-438d-8b03-dd5c08189cdb.png)

Of the following mime-types, the built-in ones work as expected. However, like @daniel-scheliga, changing the priority order with `"notebook.displayOrder": ["image/pngkajsd"]`, doesn't fix the issue. 
![image](https://user-images.githubusercontent.com/32822771/128720603-0559ddf1-4158-45f8-92e6-3e337c078b33.png)


Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

**Comment by mjbvz** [comment] 2021-08-11 23:35
Possible a duplicate of #123494. Can you please testing this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? This should be listed as VS Code 1.60

**Comment by daniel-scheliga** [comment] 2021-08-12 07:46
> Possible a duplicate of #123494. Can you please testing this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? This should be listed as VS Code 1.60

Works for me. Thank you!

**Closed** 2021-08-12 18:52 UTC
Labels: *duplicate, notebook-output
