### ISSUE TITLE
Marketplace not working

### ISSUE THREAD

**Issue by Gil9091e10** [Microsoft/vscode#57894] opened 2018-09-04 18:36 UTC
Page for extensions download not working from yesterday. 

![image](https://user-images.githubusercontent.com/19364222/45050742-5b8a0400-b03f-11e8-970d-96b43265b6ee.png)

**Comment by rafr3** [comment] 2018-09-04 18:41
Checking for updates returns Error 503.

**Comment by RevoluPowered** [comment] 2018-09-04 18:44
See workaround for getting plugins until microsoft fixes azure.

This is a duplicate.

https://github.com/Microsoft/vscode/issues/57851

**Comment by mjbvz** [comment] 2018-09-04 20:44
Duplicate of #57851

**Closed by mjbvz** 2018-09-04 20:44 UTC
Labels: extensions
