### ISSUE TITLE
Zoom in on markdown preview makes the viewable area smaller

### ISSUE THREAD

**Issue by nicdoye** [Microsoft/vscode#21975] opened 2017-03-04 15:21 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|puppet|Borke|0.3.2|
|format-php|Kasik96|1.1.2|
|material-icon-theme|PKief|1.3.4|
|Chef|Pendrica|0.6.2|
|vscode-docker|PeterJausovec|0.0.12|
|Seti-theme|TsumiNa|0.0.1|
|cform|aws-scripting-guy|0.0.9|
|npm-intellisense|christian-kohler|1.3.0|
|python|donjayamanne|0.5.9|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|code-runner|formulahendry|0.6.12|
|puppetlinter|jgreat|0.1.3|
|VS-code-vagrantfile|marcostazi|0.0.4|
|ruby-rubocop|misogi|0.3.4|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|csharp|ms-vscode|1.7.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|java|redhat|0.0.11|;

---

Steps to Reproduce:

1. Open Markdown file
2. Cmd-Shift-V (Open Preview)
3. Preview is now the current tab.
4 Cmd-=
5. Each  repeated zoom makes the viewable area smaller and smaller, with an empty border appearing to the right and below

Screenshots attached showing no zoom, zoomed-in once, zoomed-in six-times.

<img width="1440" alt="no-zoom" src="https://cloud.githubusercontent.com/assets/59195/23579851/0290cd2c-00ee-11e7-8e27-af5b9dddc5e3.png">
<img width="1440" alt="zoom-level-1" src="https://cloud.githubusercontent.com/assets/59195/23579852/02913438-00ee-11e7-91f4-bff0c41716bd.png">
<img width="1440" alt="zoom-level-6" src="https://cloud.githubusercontent.com/assets/59195/23579853/02921722-00ee-11e7-9f94-236c7adcbe25.png">

**Comment by mjbvz** [comment] 2017-03-04 21:18
Duplicate of #5745

**Closed by mjbvz** 2017-03-04 21:18 UTC
Labels: duplicate, webview
