### ISSUE TITLE
After last update, incoming/outgoing commits not visible in sidebar

### ISSUE THREAD

**Issue by aureliusm** [microsoft/vscode#228422] opened 2024-09-13 07:33 UTC
Type: <b>Bug</b>

In the sidebar of the SOURCE CONTROL just below the Action button (e.g. "Commit & Push") there was a line which said if there are any unpushed or unpulled commits for the repository. That is now missing.

VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 57e0fad2-3537-454a-929d-5fad2e2bb8a1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.10
better-phpunit|cal|1.6.2
gitlens|eam|15.4.0
vue-format|feb|0.1.8
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
gitlab-workflow|Git|5.9.1
todo-tree|Gru|0.0.226
dotenv|mik|1.0.1
sftp|Nat|1.16.3
copy-branch-name|PKi|1.0.4
vscode-yaml|red|1.15.0
vscode-drupal|sta|0.4.4
svelte-vscode|sve|109.0.1
rainbow-bracket|tal|1.0.2
volar|Vue|2.1.6
material-theme|zhu|3.17.2
vue|znc|0.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
pme_test_c:31118331
fje88620:31121564

```

</details>

**Comment by aureliusm** [comment] 2024-09-13 07:38
Problem persists after updating to latest version.

**Comment by aureliusm** [comment] 2024-09-13 07:50
This is the screenshot of what I mean. The "Incoming/Outgoing" is missing.

<img width="264" alt="image" src="https://github.com/user-attachments/assets/a82419e0-d530-4621-b7ca-f86454b10447">

**Comment by aureliusm** [comment] 2024-09-13 07:54
I just saw that this was moved into a separate block (https://code.visualstudio.com/updates/v1_93#_source-control-graph-view). I really liked it here, because it only showed if it something was to be done. In the new panel it is always there and it is harder to spot change etc.

Is it possible to set it the way it was?

**Comment by gjsjohnmurray** [comment] 2024-09-13 08:03
/duplicate of https://github.com/microsoft/vscode/issues/227727

**Closed** 2024-09-13 08:03 UTC
Labels: *duplicate
