### ISSUE TITLE
Clear command in pwsh terminal leaves extra dot

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#143927] opened 2022-02-24 23:08 UTC
On the latest Insiders on Win10:

1. Run some commands in a pwsh terminal with shell integration enabled. I narrowed the terminal so that I had a multiline prompt.
2. Run a clear command.
3. :bug: There's a dot that seems to be left behind.

![Screenshot showing extra dot in gutter](https://user-images.githubusercontent.com/7199958/155622693-e86810b5-1bd8-4f8c-904b-06b8094733b4.PNG)

**Comment by meganrogge** [comment] 2022-02-24 23:36
Yep, fixed in OSS off of main 😄

**Comment by meganrogge** [comment] 2022-02-24 23:37
/duplicate of https://github.com/microsoft/vscode/issues/143784

**Closed by meganrogge** 2022-02-24 23:36 UTC
