### ISSUE TITLE
Option to sync settings across all profiles

### ISSUE THREAD

**Issue by sanketgandhi876** [microsoft/vscode#176721] opened 2023-03-10 04:55 UTC
Thank you for awesome profile feature. VSCode became faster because of this feature.

If user has multiple profiles then we need option to sync VSCode settings across all profiles. Even if some settings become invalid due to unavailability of extension in some profile but that is fine.

**Comment by anthonyvdotbe** [comment] 2023-03-10 07:40
@sanketgandhi876 this is a duplicate of #156144 Consider closing this issue and upvoting that one instead.

**Closed** 2023-03-10 07:55 UTC
