### ISSUE TITLE
Save all files shortcut

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#13233] opened 2016-10-05 06:51 UTC
@bpasero Sorry, that i have to reopen this, but there is no keyboard shortcut for this. I've checked it on two windows 10 pc's and an ubuntu pc. Are you using some other version or do i have to change some setting to enable it?

![image](https://cloud.githubusercontent.com/assets/6654388/19103709/ca52ac5e-8ad8-11e6-86fe-50e5d22cb739.png)

#13006

**Comment by bpasero** [comment] 2016-10-05 07:01
@mbeckenbach right, looks like I had configured it. You can change keybindings to your liking and assign one for the "Save All" too.

Closing as duplicate of https://github.com/Microsoft/vscode/issues/11433

**Closed by bpasero** 2016-10-05 07:01 UTC
