### ISSUE TITLE
Incorrect highlighting for markdown block quote code blocks

### ISSUE THREAD

**Issue by calebmer** [Microsoft/vscode#13602] opened 2016-10-12 14:40 UTC
- VSCode Version: 1.6.0
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Open a new file.
2. Set the syntax highlighting to “Markdown”
3. Type the following:

```
Highlighting **works**.

> ```bash
> $ cat file-in.txt > file-out.txt
> ```

Highlighting is **broken** below the code block.
```

Which will render:

![screen shot 2016-10-12 at 10 38 28 am](https://cloud.githubusercontent.com/assets/8282507/19314416/0c761f64-9068-11e6-9703-6f4c1c1f4bbd.png)

**Comment by gregvanl** [comment] 2016-10-13 16:50
Could be duplicate of https://github.com/Microsoft/vscode/issues/11480

**Comment by mjbvz** [comment] 2016-10-13 22:44
Duplicate of #12822

**Closed by mjbvz** 2016-10-13 22:44 UTC
Labels: duplicate
