### ISSUE TITLE
Lingering VS code processes when restarting to update

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#17565] opened 2016-12-19 22:15 UTC
- VSCode Version: 1.8.0
- OS Version: Windows 10 Pro, Version 1607, OS Build: 14393.576

Encountered this when updating to version 1.8.1

Lingering VS code processes in the background block it from updating itself

![toomany3](https://cloud.githubusercontent.com/assets/8478946/21331041/89c2b2b2-c60e-11e6-9cb7-27181f0cbe85.PNG)
![toomany2](https://cloud.githubusercontent.com/assets/8478946/21331042/89c2f90c-c60e-11e6-8d3b-838dd489d197.PNG)
![toomany](https://cloud.githubusercontent.com/assets/8478946/21331043/89cc303a-c60e-11e6-8f72-70fe9d2c1d49.PNG)

The processes you see here are besides the Setup process that was somewhere up the list

I had to manually kill the 6 processes you see here before I was able to update.

**Comment by joaomoreno** [comment] 2017-01-03 14:14
Any chance you can find out the full command line which spawned those processes?

**Comment by QwertyZW** [comment] 2017-01-04 12:15
Does VS Code/Setup/Update keep a log anywhere by default? I'm not familiar with windows 10's system log mechanisms/if it had any

**Comment by joaomoreno** [comment] 2017-01-04 13:50
No, but if you see them again, you can use [Process Hacker](http://processhacker.sourceforge.net/) to figure out each process' full command line.

**Comment by QwertyZW** [comment] 2017-02-02 19:30
![1](https://cloud.githubusercontent.com/assets/8478946/22564867/1826b266-e954-11e6-9fe9-53f219a44346.PNG)
![2](https://cloud.githubusercontent.com/assets/8478946/22564870/18358a2a-e954-11e6-81aa-19847432b218.PNG)
![3](https://cloud.githubusercontent.com/assets/8478946/22564871/1835a1e0-e954-11e6-9091-912c242bbaef.PNG)
![4](https://cloud.githubusercontent.com/assets/8478946/22564868/1834b154-e954-11e6-959d-f156b8f875d1.PNG)
![5](https://cloud.githubusercontent.com/assets/8478946/22564869/18357ff8-e954-11e6-95ba-0962f7c2d4f5.PNG)
![6](https://cloud.githubusercontent.com/assets/8478946/22564873/183807f0-e954-11e6-8063-2f3134adac22.PNG)
![7](https://cloud.githubusercontent.com/assets/8478946/22564872/1836c52a-e954-11e6-90f1-8329a2635f0f.PNG)
![8](https://cloud.githubusercontent.com/assets/8478946/22564874/1841fb48-e954-11e6-9451-327a14517692.PNG)

**Comment by joaomoreno** [comment] 2017-02-02 19:45
Thanks!

**Comment by joaomoreno** [comment] 2017-02-02 19:46
@mjbvz for TypeScript
@dbaeumer @aeschli for html/languageclient

**Comment by dbaeumer** [comment] 2017-02-03 09:33
I think the root cause of this is the extension host not shutting down. All other processes are started from the extension host and shutdown if they are asked to do so, the stream closes they use to listen on or when the process that started them disappears.

**Comment by dbaeumer** [comment] 2017-02-03 09:36
Adding @alexandrudima. The extension host under Windows is started in detach mode to support a proper shutdown sequence. However looking at the code I can only think about one case where the extension host wouldn't shutdown: if it is busy and can't process events. @QwertyZW in your case is the --extensionHost process consuming lots of CPU cycles?

**Comment by QwertyZW** [comment] 2017-02-03 15:49
@dbaeumer  Nope. All of them looked pretty idle to me. The only one that showed any activity was the 4th one from the top and even then it was only periodic spikes going no higher than 5%

**Comment by QwertyZW** [comment] 2017-02-03 16:23
The processes still linger in the background after aborting. Once I manually kill those processes I'm unable to recreate the situation again. Updating works fine afterwards. 

However if I keep them running, start a new window and try to update I run into the same problem.

It might be an issue related to suspending the processes (when putting comp to sleep) but I'm not sure. The system is always running/sleeping unless I shut it down for updates

**Comment by dbaeumer** [comment] 2017-02-06 10:23
@QwertyZW when you see it again will killing the process that has --extensionHost on the command line make all the other processes go away in a reasonable amount of time?

**Comment by QwertyZW** [comment] 2017-02-06 16:16
Will it make all the other processes go away? in 1.9 --extensionHost seems to be one of the main process' grandchildren.

**Comment by dbaeumer** [comment] 2017-02-06 16:39
Yes, it should make all the other processes go away

**Comment by mjbvz** [comment] 2017-03-21 22:48
@QwertyZW Can you please try upgrading to VSCode 1.10+ to pick up TS 2.2.1. Let me know if you still see the typescriptserver process hanging around. If you do, try collecting the TSS_LOGs as documented here: https://github.com/Microsoft/vscode/issues/21442#issuecomment-282903822

**Comment by QwertyZW** [comment] 2017-04-01 23:40
Upgraded to 1.10 a while back without a problem @mjbvz

**Comment by QwertyZW** [comment] 2017-06-01 01:42
Upgraded again several times from 1.10 through to 1.12.2.

I think this ticket can be closed now. Please feel free do to so if this ticket is not relevant anymore.

**Comment by alexandrudima** [comment] 2017-06-01 06:14
Thank you @QwertyZW 

I'll close this issue for now. We know we have a problem that sometimes the extension host process lingers around. We will try to tackle it with #26445

**Closed by alexandrudima** 2017-06-01 06:14 UTC
Labels: bug, needs more info, windows
