### ISSUE TITLE
Missing Code after self update

### ISSUE THREAD

**Issue by pineda97** [Microsoft/vscode#70234] opened 2019-03-11 16:38 UTC
Issue Type: <b>Bug</b>

VS Code updated itself with no warning and when it reopened the tabs I had open with unsaved changes went completely blank (no code within them).

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
compareit|in4|0.0.2

</details>

**Comment by V-ed** [comment] 2019-03-11 17:22
Duplicate of https://github.com/Microsoft/vscode/issues/69972

*Should* be fixed in the recovery release 1.32.2 (not yet released, see linked issue for more context)

Read this comment : https://github.com/Microsoft/vscode/issues/69972#issuecomment-470706961 before closing your VSCode window, you might still have a chance to retrieve your documents...

**Closed** 2019-03-12 15:46 UTC
Labels: *duplicate
