### ISSUE TITLE
"Find all references" not working

### ISSUE THREAD

**Issue by zjunweihit** [microsoft/vscode#74665] opened 2019-05-31 07:32 UTC
- VSCode Version: 1.33.1
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-50-generic
```
- OS Version: Ubuntu18.04 and Win10

Steps to Reproduce:

1. Install vscode by default
2. right click to show menu -> there is no "find all reference"
3. Shift+12, not working to find reference.
4. I tried both C/C++ 0.23.1 and C++ Intellisense 0.2.2

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2019-05-31 07:37
You reported this on 1.33.1. Are you able to upgrade to the current release (1.34) and reproduce it there? Even better, test it on Insiders.

If you can reproduce on latest please add screenshots / animations to clarify the steps.

**Comment by zjunweihit** [comment] 2019-05-31 08:25
Unfortunately 1.34 doesn't work either.
While it's described in below page, which seems the default setting for vscode.
  * https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_peek-references
  * https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

(BTW, I failed to install insider for now)
![Screenshot from 2019-05-31 16-18-32](https://user-images.githubusercontent.com/2871607/58691956-0b6a8300-83c0-11e9-9468-bafb00cb28c4.png)
![Screenshot from 2019-05-31 16-19-21](https://user-images.githubusercontent.com/2871607/58691961-0dccdd00-83c0-11e9-8530-d17f82fccd38.png)

**Comment by gjsjohnmurray** [comment] 2019-05-31 09:30
https://github.com/microsoft/vscode-cpptools/issues/15

Looks like "Find all references" isn't yet implemented in the C/C++ 0.23.1 extension. I didn't check the issue section of the repo of the other one you mentioned.

**Comment by zjunweihit** [comment] 2019-05-31 14:36
Exactly, it sounds related to "C/C++ ms-vscode.cpptools 0.23.1".
Cause it works fine with "C++ Intellisense austin.code-gnu-global 0.2.2".

**Comment by gjsjohnmurray** [comment] 2019-05-31 15:06
Please close this issue here. You may want to watch the one I linked above.

**Closed** 2019-05-31 17:14 UTC
Labels: *caused-by-extension

**Comment by zjunweihit** [comment] 2019-06-03 05:21
> Please close this issue here. You may want to watch the one I linked above.

yes, thanks for your info.
