### ISSUE TITLE
Variable expansion in task inputs

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/vscode#100133] opened 2020-06-14 18:30 UTC
It would be nice if variables like `${file}` were resolved in task inputs.

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "cat",
      "type": "shell",
      "command": "cat ${input:file}",
    },
    {
      "label": "echo",
      "type": "shell",
      "command": "echo ${input:echoOptions}",
    }
  ],
  "inputs": [
    {
      "id": "file",
      "type": "promptString",
      "default": "${file}",
      "description": "This also prints variables, as you can see: ${selectedText}",
    },
    {
      "id": "echoOptions",
      "type": "pickString",
      "description": "Things you can echo",
      "options": [
        {
          "label": "Selected text: ${selectedText}",
          "value": "${selectedText}"
        },
        {
          "label": "File: ${file}",
          "value": "${file}"
        }
      ]
    }
  ]
}
```

Cascading input variable expansion would be cool too, but probably more work than it's worth.

```json
{
  "inputs": [
    {
      "id": "input1",
      "type": "pickString",
      "description": "Pick a thing",
      "options": [
        {
          "label": "Thing 1",
          "value": "thing1"
        },
        {
          "label": "Thing 2",
          "value": "thing2"
        }
      ]
    },
    {
      "id": "input2",
      "type": "promptString",
      "default": "${input:input1}",
      "description": "Pick '${input:input1}' or something else?",
    }
  ]
}
```

**Comment by alexr00** [comment] 2020-06-15 12:57
Duplicate of https://github.com/microsoft/vscode/issues/64358

**Closed** 2020-06-15 12:58 UTC
Labels: *duplicate
