### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by tufeiping** [microsoft/vscode#139815] opened 2021-12-27 23:54 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49210:29)
    at getTargetOfExportAssignment (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49246:28)
    at resolveAlias (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at resolveExternalModuleSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49248:28)
    at resolveAlias (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47624:42)
    at c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47737:20)
    at initializeTypeChecker (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85010:21)
    at Object.createTypeChecker (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159898:21)
    at Proxy.getProgram (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168762:44)
    at c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
    at c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (c:\Users\tufei\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon Silver 3050U with Radeon Graphics    (2 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.94GB (6.56GB free)|
|Process Argv|--crash-reporter-id ef07fad8-d193-4368-869b-5354d55c8232|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-nginx-conf|ahm|0.1.3
vscode-sqlite|ale|0.14.0
vscode-eclipse-keybindings|alp|0.14.0
better-toml|bun|0.3.2
vscode-database-client2|cwe|4.3.6
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
vscode-eslint|dba|2.2.2
binary-plist|dni|0.8.0
redis|Dun|1.4.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
RunOnSave|eme|0.2.0
code-runner|for|0.11.6
copilot|Git|1.7.4421
go|gol|0.30.0
vscode-drawio|hed|1.6.3
run-code|iep|1.0.0
vscode-pont|jas|1.0.13
intellij-idea-keybindings|k--|1.5.0
xml-format|mik|1.1.2
vscode-language-pack-zh-hans|MS-|1.63.3
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-edge|msj|1.0.15
stats-bar|njz|0.5.0
vetur|oct|0.35.0
vscode-thunder-client|ran|1.9.1
nginx-formatter|ray|0.0.13
fabric8-analytics|red|0.3.5
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vscode-scss-formatter|sib|2.3.3
vscode-hexdump|sle|1.8.1
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
ReactSnippets|xab|2.4.0
clang-format|xav|1.9.0
markdown-pdf|yza|1.4.4
propertylist|zho|0.0.2
tconda|zhp|0.0.5
material-theme|zhu|3.13.8

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
py55gd98:30411514

```

</details>

**Comment by IllusionMH** [comment] 2021-12-28 06:57
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2021-12-28 06:58 UTC
Labels: *duplicate

**Comment by tufeiping** [comment] 2021-12-28 08:54
ok thx~~
