### ISSUE TITLE
terminal cannot display Chinese correctly

### ISSUE THREAD

**Issue by summerstream** [Microsoft/vscode#8035] opened 2016-06-23 07:22 UTC
Chinese words crowd together so user can not see them clearly.

**Comment by Tyriar** [comment] 2016-06-23 08:09
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-23 08:09 UTC
Labels: bug, integrated-terminal

**Comment by joaomoreno** [comment] 2016-09-02 09:02
@Tyriar Make sure you mark the issues as `duplicate` so they don't show up in the verification query. 👍
