### ISSUE TITLE
feature-request: pause extension like chrome plugin manager

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#7190] opened 2016-06-03 15:17 UTC
- VSCode Version: 1.1.1
- OS Version: oxs 10.11.4

In china, install extension is very slowly, sometime i want to pause one extension at some project

**Comment by jrieken** [comment] 2016-06-03 15:36
>  sometime i want to pause one extension at some project

what do you mean by pausing? pausing the download/install?

**Comment by builden** [comment] 2016-06-04 11:11
@jrieken I mean inactive extension, like this in chrome plugin manager
![image](https://cloud.githubusercontent.com/assets/9499016/15799234/13ecdbf2-2a88-11e6-9373-ec362f8ebfe6.png)

**Comment by rebornix** [comment] 2016-06-04 12:45
From the snapshot, I suppose what @builden wants is enabling/disabling installed extensions.

**Comment by joaomoreno** [comment] 2016-06-06 08:09
Duplicate of #2882

**Closed by joaomoreno** 2016-06-06 08:09 UTC
Labels: feature-request, needs more info
