### ISSUE TITLE
i cant work now on VS 

### ISSUE THREAD

**Issue by harrylog** [Microsoft/vscode#15163] opened 2016-11-08 11:43 UTC
.

**Comment by aeschli** [comment] 2016-11-08 13:48
@harrylog Can you add a description of the problem? What OS platform, what version..

**Comment by aeschli** [comment] 2016-11-08 14:30
duplicate of #15161?

**Comment by aeschli** [comment] 2016-11-15 14:56
Closing due to lack of information. Please reopen with data described above.

**Closed by aeschli** 2016-11-15 14:56 UTC
Labels: needs more info
