### ISSUE TITLE
XHR timeout: undefinedms - Extension download/Update Error & update vs code version

### ISSUE THREAD

**Issue by Jacobify** [microsoft/vscode#165577] opened 2022-11-05 04:43 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0
- OS Version:  Windows 10 Enterprise 19044.2006

There seems to be a problem regarding downloading/updating extensions and the vs code itself automatically. Tried a lot of security and firewall settings and made sure visual studio code is allowed through all networks. My system is connected through a ethernet connection if that is worth mentioning.

![2022-11-05 08_08_08-Window](https://user-images.githubusercontent.com/39615077/200101347-60fa9f53-f468-4c36-bacf-dba4cb6fe2a6.png)

**Comment by msh-shf** [comment] 2022-11-05 05:04
The same problem!!!

**Comment by Minktong** [comment] 2022-11-05 08:54
I also am having the same problem.

**Comment by sandy081** [comment] 2022-11-09 12:47
Can you please share your console & network logs in developer tools. F1 > Toggle Developer Tools.

I assume you have network issues connecting to the Marketplace. Is your machine behind any proxy or firewall settings?

**Comment by Jacobify** [comment] 2022-11-10 05:45
> Can you please share your console & network logs in developer tools. F1 > Toggle Developer Tools.
> 
> I assume you have network issues connecting to the Marketplace. Is your machine behind any proxy or firewall settings?

No it is not behind any proxy or firewall . Before version 1.71.0 I could download/update extensions just fine through vs code itself automatically or update the vs code software itself.  
![image](https://user-images.githubusercontent.com/39615077/201010302-76d19f02-2a85-4e9b-ad14-a1e492cc69cb.png)

![image](https://user-images.githubusercontent.com/39615077/201010352-1aa28997-ac87-4b4b-9495-1c704aeec0b2.png)

**Comment by sandy081** [comment] 2022-11-14 13:03
Logs clearly show that the device has issues connecting to Marketplace. @deepak1556 Hence assigning to you to check if there is any network related issues with VS Code.

**Comment by Jacobify** [comment] 2022-11-16 07:07
> Logs clearly show that the device has issues connecting to Marketplace. @deepak1556 Hence assigning to you to check if there is any network related issues with VS Code.

thanks for your attention and time @sandy081

**Comment by deepak1556** [comment] 2022-12-08 08:01
Does the issue persist with latest stable `1.74` ?

**Comment by Nummer42O** [comment] 2022-12-12 10:02
it still persists for me

```
~$ code --version
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
x64
```

![Screenshot from 2022-12-12 10-59-29](https://user-images.githubusercontent.com/63714738/207017055-a9da9add-6618-40eb-be6b-516c27790e01.png)

**Comment by deepak1556** [comment] 2022-12-12 10:35
Can you close all running instances of VSCode and launch with `--log-net-log=/tmp/netlog.json`, once the request fails, quit the application and attach the generated logs in this issue thread.

**Comment by andresMoreno96** [comment] 2022-12-12 14:20
In my case it was related to my region. Geofencing. 

I've added a vpn and switch my location from Europe to USA.

**Comment by Jacobify** [comment] 2022-12-21 10:57
> Does the issue persist with latest stable `1.74` ?

yes it still does

**Comment by deepak1556** [comment] 2022-12-21 11:16
@Jacobify can you provide the logs based on the steps from https://github.com/microsoft/vscode/issues/165577#issuecomment-1346245936, thanks!

**Comment by Jacobify** [comment] 2022-12-24 03:35
@deepak1556 I have updated my vs code and the problem is seem to be gone. I can download and update extensions without any problem . if the problem ever comes back I will provide the logs you wanted.

**Comment by deepak1556** [comment] 2022-12-26 13:02
Thanks for confirming, I will close this issue for now. Please reopen or file a new issue with relevant logs if the issue appears again.

**Closed by deepak1556** 2022-12-26 13:02 UTC
Labels: info-needed

**Comment by rama4zis** [comment] 2023-01-03 14:51
Hey, I got the same problem, my VS Code version 1.74.2
I can't update some extensions and download new one, I have tried to install manually then got same error

I try to uninstall some extension and install it again, it will give me same error
I can't update and install some new extensions

They keep giving me `[error] Error: XHR timeout: undefinedms`

**Comment by deepak1556** [comment] 2023-01-03 17:07
@rama4zis please provide the network log following the steps in https://github.com/microsoft/vscode/issues/165577#issuecomment-1346245936

**Comment by rama4zis** [comment] 2023-01-03 21:55
@deepak1556 Hey it's so funny, when today the problem was gone on my laptop, I don't really know what happened.
But I just try to update again today, and it works

But just 1 extension, I still can't update or install even with manual installation [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)

Maybe I think it just my internet, so I try using VPN and still cant install that

![image](https://user-images.githubusercontent.com/28669091/210447560-9405c8be-d7f4-42d9-8f37-f815e4452e71.png)

**Comment by filipeaguiar** [comment] 2023-01-10 19:02
I'm having the same issue for a while.

Here's the netlog.json as asked previously.
[netlog.zip](https://github.com/microsoft/vscode/files/10385903/netlog.zip)

**Comment by deepak1556** [comment] 2023-01-26 12:23
@filipeaguiar log shows connections are timed out from proxy server configured on your system. Issue is not actionable from our end.

**Comment by Hezavehir** [comment] 2023-02-01 21:47
Me too -_-
My Feature:
code --version: 1.74.3 x64
OS: Mint 21 based on Ubuntu 22.04

**Comment by z979054461** [comment] 2023-02-07 02:21
The same problem on 1.74.3!!!

**Comment by Jacobify** [comment] 2023-02-07 04:43
This problem comes and goes with every version released and has become a nightmare for me. before 1.75 I had to use a proxy to update/download extensions. On 1.75 it seems to be fixed , If I face the issue I will send you my logs here. @deepak1556

**Comment by Jacobify** [comment] 2023-02-07 04:45
> This problem comes and goes with every version released and has become a nightmare for me. before 1.75 I had to use a proxy to update/download extensions. On 1.75 it seems to be fixed , If I face the issue I will send you my logs here. 

Please reopen this issue @deepak1556

**Comment by deepak1556** [comment] 2023-02-07 05:12
> On 1.75 it seems to be fixed

@Jacobify if the issue is addressed with `1.75`, not sure why the issue should be reopened. Can you clarify ?

**Comment by Jacobify** [comment] 2023-02-07 05:14
I will reopen/create a new issue if the problem reappears.

**Comment by Jacobify** [comment] 2023-02-07 05:22
> The same problem on 1.74.3!!!

update your editor the latest version
