### ISSUE TITLE
Source Control does not work anymore

### ISSUE THREAD

**Issue by FuriouZz** [Microsoft/vscode#22701] opened 2017-03-15 22:45 UTC
Hello,

Since some builds, the source control panel seems to not working anymore. On the icon, a blue timer icon always visible. When I open the panel, no tracked file or modification appear.

- VSCode Version: 1.11.0-insider (1.11.0-insider) 6a002910356c6e087dd93e819e4ad54c68b9857a
- OS Version: OSX El Capitan 10.11.6

**Comment by joaomoreno** [comment] 2017-03-20 11:50
If you open the `Developer Tools`, is there an error?

**Comment by FuriouZz** [comment] 2017-03-21 20:20
I got one error =/ http://d.pr/v/AOBH

**Comment by joaomoreno** [comment] 2017-03-23 16:37
Can you repro if you launch Code with `code --disable-extensions`?

**Comment by FuriouZz** [comment] 2017-04-02 12:01
Same problem =/

**Comment by joaomoreno** [comment] 2017-04-06 08:21
If you try our latest stable (1.11), does it work?

**Comment by FuriouZz** [comment] 2017-04-11 08:32
I have no problem with the stable version. I have the Insider version in another computer and no problem reported. Maybe, my insider version is breaked =/. Is it possible to reset it ?

**Comment by joaomoreno** [comment] 2017-04-11 12:02
Try to fully reinstall it. 👍

**Comment by FuriouZz** [comment] 2017-04-12 19:11
I updated my stable version of VSCode and Source Control does not work anymore...

**Comment by FuriouZz** [comment] 2017-04-12 19:17
A new screencast with VSCode 1.11.1

http://d.pr/v/C36I

**Comment by joaomoreno** [comment] 2017-04-13 06:16
@FuriouZz Thanks for the screencast! It's a duplicate of #24598.

**Closed by joaomoreno** 2017-04-13 06:16 UTC
Labels: needs more info
