### ISSUE TITLE
Command center should be centered exactly

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#153622] opened 2022-06-28 23:28 UTC
Testing https://github.com/microsoft/vscode/issues/150262, which is admittedly the first time I've turned on the command center as I usually keep Code full screen.

I noticed that clicking the command center "jumps" the input -- the quickpick is slightly smaller and/or to the left of the command center.

![Kapture 2022-06-28 at 16 26 57](https://user-images.githubusercontent.com/2230985/176320769-0c5ac0bb-2acc-4660-aee5-c8dda89b2131.gif)

I'm guessing this is because the width of the navigation arrows is taken into account when centering. I think they should not be, and instead the input should be centered perfectly so that it aligns with the quick input box.

It would also be nice if the quick input box looked more like the command center input rather than an element we just throw on top of it...

**Comment by jrieken** [comment] 2022-06-29 07:32
Many things are happening here... Generally the whole command center (arrow btn and fake input btn) is centered but when space is tight it can go off. Also its width is dynamic and often not what the quick input is. We therefore hide the CC while quick pick shows. That helps with more "extreme" cases. We might be able to revisit this because CC is getting more likes and thereby rights to steal space from other toolbar elements.

> It would also be nice if the quick input box looked more like the command center input rather than an element we just throw on top of it...

For now the CC is just a glorified button but aligning the styles or re-using some parts might became a thing in the future. /cc @TylerLeonhardt

**Comment by jrieken** [comment] 2022-06-29 07:32
related to https://github.com/microsoft/vscode/issues/150984

**Comment by jrieken** [comment] 2022-09-29 16:45
folding this as /duplicate of https://github.com/microsoft/vscode/issues/150984

**Closed by jrieken** 2022-09-29 16:45 UTC
Labels: under-discussion, command-center
