### ISSUE TITLE
Intellisense with import splits string

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#41387] opened 2018-01-10 10:29 UTC
- VSCode Version: 1.19.1
- OS Version: Windows x64

Steps to Reproduce:

1. open a .ts file with some imports
2. move the mouse over a import's splitted path and press `ctrl`

Each word of the path gets independentely underlined:

![intellisensedefinition](https://user-images.githubusercontent.com/199648/34766686-7e42d698-f5f5-11e7-9c18-4eb0b5aefcfd.gif)

Shouldn't it underline the whole path/string instead ?

![vscodehighlight](https://user-images.githubusercontent.com/199648/34766899-83cbd884-f5f6-11e7-93c5-3ce0b13225cc.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2018-01-10 15:13
Duplicate of #10037

**Closed by mjbvz** 2018-01-10 15:13 UTC
Labels: javascript
