### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by jorromigl** [Microsoft/vscode#57865] opened 2018-09-04 12:51 UTC
Issue Type: <b>Bug</b>

I cant install any extensions.
When i'm looking for Apex extension i obtain "No extensions results", and this problem is happening with all the searchs.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

**Comment by haskellcamargo** [comment] 2018-09-04 12:58
This is happening because [the marketplace server](https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery) is unavailable.
Duplicate of #57864 and #57863

**Comment by igorbb** [comment] 2018-09-04 16:04
https://blogs.msdn.microsoft.com/vsoservice/?p=17405

Also this seems to be a duplicate of :

#57851

**Closed** 2018-09-04 17:48 UTC
Labels: *duplicate, extensions
