### ISSUE TITLE
Editor sticky scroll misses token colorization after reload/restart

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#202319] opened 2024-01-12 08:33 UTC
1. Scroll to a position where editor sticky scroll appears
2. Reload

🐛 Stick scroll is colorless. It comes back as soon as I scroll enough to make sticky scroll rerender.

https://github.com/microsoft/vscode/assets/22350/baf5fbc0-09c1-4acc-9496-e52bcd6885cb

**Comment by aiday-mar** [comment] 2024-01-17 10:35
Appears to be a duplicate of issue https://github.com/microsoft/vscode/issues/201727. This issue will be closed in favor of the other one.

**Closed by aiday-mar** 2024-01-17 10:35 UTC
