### ISSUE TITLE
A javascript error in the main process

### ISSUE THREAD

**Issue by Citizen-icon** [Microsoft/vscode#42781] opened 2018-02-02 02:59 UTC
- VSCode Version: 1.19.3
- OS Version: Windows 10  Enterprise  2016 LTSB

Steps to Reproduce:

1. double  `CTRL` show `listary` search bar . 
![image](https://user-images.githubusercontent.com/11224565/35714329-f9890fac-0806-11e8-911f-88866528764d.png)

2. select a file and `CTRL+O` . select `open with Code`
![image](https://user-images.githubusercontent.com/11224565/35714398-55233572-0807-11e8-9276-f580383dc3ae.png)

3. error:
![image](https://user-images.githubusercontent.com/11224565/35714428-82d7514c-0807-11e8-8d74-26807ab18e85.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-02-02 09:28
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Citizen-icon** [comment] 2018-02-02 09:36
Same.
![image](https://user-images.githubusercontent.com/11224565/35726338-8e3a8594-083f-11e8-9af3-c03f80dd24bf.png)
Then ...
![image](https://user-images.githubusercontent.com/11224565/35726359-9c00920e-083f-11e8-8f85-b4635da7f21d.png)

**Comment by bpasero** [comment] 2018-02-02 09:44
Looks like a duplicate of https://github.com/electron/electron/issues/10054 to me

**Closed by bpasero** 2018-02-02 09:44 UTC
Labels: needs more info

**Comment by Citizen-icon** [comment] 2018-02-02 10:03
it doesn't work.
![image](https://user-images.githubusercontent.com/11224565/35727261-7d8dc28a-0842-11e8-88c4-3a86b7693785.png)

**Comment by Citizen-icon** [comment] 2018-02-02 10:09
As long as I do not open the file with Listary, I can use VS Code normally.
