### ISSUE TITLE
Clicking in folder in file explorer doesn't expand children files

### ISSUE THREAD

**Issue by jcserracampos** [microsoft/vscode#116905] opened 2021-02-18 00:45 UTC
Issue Type: <b>Bug</b>

If I click in folder name it doesn't expand and show its descendents.

VS Code version: Code - Insiders 1.54.0-insider (3f0d8a14759cddea93f0dbddc12a4ef1e5586e86, 2021-02-17T07:40:31.870Z)
OS version: Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.33GB (8.76GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 719ce506-cf4f-4cb0-a397-3e6e240bdb2e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
bracket-pair-colorizer|Coe|1.0.61
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.39.0
xml|Dot|2.5.1
gitlens-insiders|eam|2021.2.1704
auto-close-tag|for|0.5.10
elixirlinter|iam|0.4.1
elixir-ls|Jak|0.6.5
vscode-edit-csv|jan|0.5.4
vscode-peacock|joh|3.9.1
haml|kar|1.3.1
vscode-fix-checksums|leh|1.1.0
rainbow-csv|mec|1.8.1
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.160.0
vsliveshare|ms-|1.0.3784
material-icon-theme|PKi|4.5.0
ruby|reb|0.28.1
synthwave-vscode|Rob|0.1.8
trailing-spaces|sha|0.3.1
vscode-wakatime|Wak|5.0.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
pythontb:30258533
coreuntitledfile:30249963
openwsldoc:30257849

```

</details>

**Comment by IllusionMH** [comment] 2021-02-18 01:06
/duplicate of #116804

See #115873 for details

**Closed** 2021-02-18 01:08 UTC
Labels: *duplicate
