### ISSUE TITLE
VS Code don't save large CSS file

### ISSUE THREAD

**Issue by zeeshanmulani** [Microsoft/vscode#14150] opened 2016-10-21 09:44 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: alefragnani.project-manager-0.10.0, HookyQR.minify-0.2.5, ms-vscode.Theme-1337-0.1.2

Steps to Reproduce:
1. Create a CSS file that have more than 4000 lines of code uncompressed
2. try to save the file. 
   ![issue](https://cloud.githubusercontent.com/assets/19655642/19594016/ad20e706-979c-11e6-84f1-fcccca06f0f8.png)

**Comment by zeeshanmulani** [comment] 2016-10-21 09:48
Error

![error](https://cloud.githubusercontent.com/assets/19655642/19594171/615d4dfe-979d-11e6-9eb9-e3129dcbd64d.png)

**Comment by bpasero** [comment] 2016-10-22 04:47
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-10-26 09:06
@zeeshanmulani ping

**Comment by zeeshanmulani** [comment] 2016-10-26 09:24
It's same

**Comment by bpasero** [comment] 2016-10-26 09:49
@zeeshanmulani are you able to attach the file for me to reproduce?

**Comment by zeeshanmulani** [comment] 2016-10-26 12:34
![screen](https://cloud.githubusercontent.com/assets/19655642/19726033/5106a744-9ba2-11e6-8f3c-34146b7782d2.png)

**Comment by bpasero** [comment] 2016-10-26 14:08
@zeeshanmulani and it still reproduces? can you share the file with me?

**Comment by bpasero** [comment] 2016-11-16 18:06
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-11-16 18:06 UTC
Labels: freeze-slow-crash, needs more info
