### ISSUE TITLE
Extension host messages flood and stall renderer

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#62693] opened 2018-11-07 04:37 UTC
- VSCode Version: 1.28.2
- OS Version: Windows 10 Pro 64 bit

Steps to Reproduce:

1. Whenever I edit any file on VS code it stops working. Before last update it was working perfect with the extensions I have installed on my setup. Below are the extensions list that I am using currently.

Extensions Installed:
1. VS Live Share Extension Pack (https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack)
2. Vetur (https://marketplace.visualstudio.com/items?itemName=octref.vetur)
3. TSLint (https://marketplace.visualstudio.com/items?itemName=eg2.tslint)
4. PHP Extension Pack (https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-pack)
5. jshint (https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint)
6. Git extension pack (https://marketplace.visualstudio.com/items?itemName=donjayamanne.git-extension-pack)
7. Azure Repos (https://marketplace.visualstudio.com/items?itemName=ms-vsts.team)
8. Eslint (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
9. GitHub Pull Requests (https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment] 2018-11-07 08:05
@iyashpal We are really keen on nailing down this issue but we have been able to reproduce yet. Can you please create CPU profile when things get slow. With that we can get a fix. 

To create profile, do this: Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by UweKeim** [comment] 2018-11-07 12:53
@jrieken "**able**" should read "**unable**", I guess?

**Comment by rtemred** [comment] 2018-11-08 02:41
I have same problem.

[Here](https://www.dropbox.com/s/uws6mkikyq75o9d/CPU-20181107T172643.cpuprofile?dl=0) CPU profile.

**Comment by jrieken** [comment] 2018-11-08 08:16
@rtemred Thanks. This is really help. From the profile it seems that VS Code is flooded with IPC messages and has trouble to keep up. 

<img width="668" alt="screenshot 2018-11-08 at 09 12 32" src="https://user-images.githubusercontent.com/1794099/48185867-a4f41980-e336-11e8-9360-eb8c47a6d4b6.png">


This might be related to https://github.com/Microsoft/vscode/issues/62421 and the question is where all these messages are being send from. Potential senders are file watching, search, and extensions. I don't think it search, which leaves extension and file watching. 

@rtemred What extension do you have installed (`code --list-extension`)? Also, do you have some kind of builder running, e.g. webpack-dev-server or something else that would generate loads of file events?

**Comment by rtemred** [comment] 2018-11-08 08:54
@jrieken here:
- alefragnani.Bookmarks
- alefragnani.project-manager
- alyaptsev.vscode-bemy
- annsk.alignment
- bradgashler.htmltagwrap
- christian-kohler.path-intellisense
- cpylua.language-postcss
- donjayamanne.githistory
- dracula-theme.theme-dracula
- JerryHong.autofilename
- lukasz-wronski.ftp-sync
- mechatroner.rainbow-csv
- mhmadhamster.postcss-language
- michelemelluso.code-beautifier
- midnightsyntax.vscode-wrap-console-log
- mrmlnc.vscode-apache
- ms-mssql.mssql
- ms-vscode.Theme-MaterialKit
- octref.vetur
- PKief.material-icon-theme
- robinbentley.sass-indented
- RolandGreim.sharecode
- Shan.code-settings-sync
- sleistner.vscode-fileutils
- sysoev.language-bemhtml
- Tyriar.sort-lines
- vincaslt.highlight-matching-tag
- volkov97.vscode-bemmet
- wayou.vscode-todo-highlight
- wmaurer.change-case
- zhuangtongfa.Material-theme

**Comment by chrmarti** [comment] 2018-11-08 09:38
@rtemred Try disabling `vincaslt.highlight-matching-tag` and see if that helps. If it doesn't, try disabling all extensions (start with `--disable-extensions` or `Reload Window With Extensions Disabled`).

**Comment by jrieken** [comment] 2018-11-08 10:21
We have seen the same profile from @vitorsemeano in #62588 and these are extension both have installed:

* `annsk.alignment`
* `donjayamanne.githistory`
* `dracula-theme.theme-dracula`
* `mechatroner.rainbow-csv`
* `michelemelluso.code-beautifier`
* `mrmlnc.vscode-apache`
* `vincaslt.highlight-matching-tag`
* `wayou.vscode-todo-highlight`

**Comment by jrieken** [comment] 2018-11-08 10:41
@rtemred, @vitorsemeano what kind of files are you guys editing when this happens? JSX, HTML, CSV? This is while typing and/or moving the cursor, right?

**Comment by vitorsemeano** [comment] 2018-11-08 11:03
This happens when i try to select something or write to the file, mostly selecting. I have seen this occurring in php, less, js, etc. When I select some text in a non stop matter on some random file it actually blocks the entire vscode for some seconds.

**Comment by rtemred** [comment] 2018-11-08 11:05
@jrieken yes it's while typing.  File types: js, less - for sure. Maybe postcss - not sure.

I disabled `vincaslt.highlight-matching-tag`.

I have disabled extension `vincaslt.highlight-matching-tag`. I will observe how VSC will behave. I will inform you tomorrow. This issue happens after a few hours of work. Then I reboot app. It's happens a couple of times a day.

**Comment by jrieken** [comment] 2018-11-08 11:11
Thank guys. Please keep us posted, we are currently looking at and testing those extensions.

**Comment by yyss8** [comment] 2018-11-08 15:57
I'm also having slimier issue and I had to restart vsc to have it fixed
I usually have 2-3 vsc running at same time and when one of them starts freezing, the rest of vsc still run ok.

here's the list of my installed extensions

- Beautify 1.4.7
- Chinese Language packet 
- Debugger for Java 0.15.0
- ESLint 1.7.0
- Java Extension Pack 0.4.0
- Java Test Runner 0.10.0
- Lnaguage Support for Java
- Laravel Blade Snippets 1.18.0
- Markdown All in One 1.7.0
- Maven for Java 0.11.1
- minify 0.3.0
- Vetur 0.13.0

and the CPU profile:

[CPU-20181108T003312.zip](https://github.com/Microsoft/vscode/files/2562452/CPU-20181108T003312.zip)

**Comment by jrieken** [comment] 2018-11-08 16:53
@yyss8 What version of VS Code are using here?

**Comment by yyss8** [comment] 2018-11-08 16:57
> @yyss8 What version of VS Code are using here?

v1.28.2 for x64, the latest version I think?

**Comment by jrieken** [comment] 2018-11-08 16:58
Thanks. What appears to be happening is that for a very long time (18secs) events are fired, from this one trace it looks like it's context keys...

<img width="324" alt="screenshot 2018-11-08 at 17 56 43" src="https://user-images.githubusercontent.com/1794099/48214245-d8a76180-e37f-11e8-9f7d-11235a9df3f0.png">

This is quite interesting but might unrelated to the behaviour others have been mentioning here.

**Comment by iyashpal** [comment] 2018-11-09 10:52
> 
> 
> @iyashpal We are really keen on nailing down this issue but we have been unable to reproduce yet. Can you please create CPU profile when things get slow. With that we can get a fix.
> 
> To create profile, do this: Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.
> 
> <img alt="screen shot 2017-09-28 at 09 44 31" width="380" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

Hi @jrieken sorry for late reply here is the CPU profile.
[CPU-20181109T161911.zip](https://github.com/Microsoft/vscode/files/2565552/CPU-20181109T161911.zip)

While recording the CPU Profile VS Code handed two times and the file I was editing it **.vue**.

Thanks!
Yash

**Comment by rtemred** [comment] 2018-11-09 13:04
Today has passed without `vincaslt.highlight-matching-tag` and this issue has not be.

**Comment by jrieken** [comment] 2018-11-12 08:00
@artdude543 thanks for the profile. what you are seeing is https://github.com/Microsoft/vscode/issues/62829#issuecomment-437314957

**Comment by rtemred** [comment] 2018-11-15 07:45
> Today has passed without `vincaslt.highlight-matching-tag` and this issue has not be.

I updated this extension (0.8.3), now VSC work fine.

**Comment by jrieken** [comment] 2018-11-15 07:55
That's good to hear. Yesterday we have also fixed a pretty bad listener leak which can show this behaviour (see https://github.com/Microsoft/vscode/issues/62970#issuecomment-438683094). Latest insider and the upcoming 1.29.1 release will contain a fix for this.

**Comment by jrieken** [comment] 2018-11-15 07:56
closing this has half duplicate and half caused-by-extension

**Closed** 2018-11-15 07:56 UTC
Labels: 1-28-x, needs more info
