### ISSUE TITLE
can't cmd+click this.xxx to its defination when value property used in a function property on object

### ISSUE THREAD

**Issue by Josscii** [microsoft/vscode#152573] opened 2022-06-19 02:42 UTC
Does this issue occur when all extensions are disabled?: YES

- VS Code Version: Version: 1.68.1
- OS Version: mac os 12.2.1

Steps to Reproduce:

```javascript
const test ={
  a: "a",
  b: function() {
    this.a = ""
    this.d();
  },
  c: function() {
    this.d();
  },
  d: function() {
  },
  e() {
    this.a = ""
    this.d();
  }
}
```

the problem is:

when a function property has a `this.xxx` such as `b` here, we can't cmd+click through this.xxx reference to its defination, while which doesn't has can, such as `c`.

and the wired thing is that, method `e` doesn't has this limiation.

**Comment by mjbvz** [comment] 2022-06-20 20:49
Duplicate of https://github.com/microsoft/TypeScript/issues/22058

**Closed by mjbvz** 2022-06-20 20:49 UTC
