### ISSUE TITLE
Toggle Integrated Terminal doesn't work in latest release (insiders)

### ISSUE THREAD

**Issue by bengry** [Microsoft/vscode#65165] opened 2018-12-16 16:19 UTC
Issue Type: <b>Bug</b>

1. Install the latest insiders release (1.31.0-insider -- ece3a90fb58986570d8afdfb16530c4dd8c743af).
(_Update: still happens with latest insiders - d85a16f2e4354f2850b4171f84fe0c94b0cea338_)
2. Press "Ctrl+\`" or via the Command Palette -> "Toggle Integrated Terminal" / Ctrl+`.
3. Nothing happens.

In VS Code (non insiders) everything works as expected - with the integrated terminal being shown and hidden with every key press.

VS Code version: Code - Insiders 1.31.0-insider (ece3a90fb58986570d8afdfb16530c4dd8c743af, 2018-12-14T06:13:54.375Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 10, 10|
|Memory (System)|16.00GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
ActiveFileInStatusBar|Ros|1.0.3
vscode-file-peek|abi|1.0.1
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.0.0
ng-template|Ang|0.1.11
bracket-pair-colorizer|Coe|1.0.61
language-postcss|cpy|1.0.5
gitlens|eam|9.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.41
prettier-vscode|esb|1.7.2
nasc-touchbar|fel|1.11.0
vscode-pull-request-github|Git|0.3.2
path-autocomplete|ion|1.13.1
RelativePath|jak|1.4.0
hungry-delete|jas|1.5.0
search-node-modules|jas|1.3.0
svg|joc|0.1.4
docthis|joe|0.7.1
expand-region|let|0.1.2
Angular-BeastCode|Mik|7.0.20
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.3.1071
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
copy-json-path|nid|0.0.5
vscode-jest|Ort|2.9.2
vscode-versionlens|pfl|0.22.0
debug-current|phi|0.1.0
nested-comments|phi|2.2.6
classlens|rex|0.7.1
postcss|ric|2.0.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.4
guides|spy|0.9.2
code-spell-checker|str|1.6.10
vscode-status-bar-format-toggle|tom|1.4.0
sensitive-replace|vil|0.1.1
vscodeintellicode|Vis|1.1.2
quokka-vscode|Wal|1.0.174
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
map-replace-js|Yuk|0.1.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by bengry** [comment] 2018-12-19 15:11
@Tyriar please advise here - I didn't see any activity here. Still happens with the latest insiders build (`d315b31c6b5cdca082b0a6e193306e4001586509`).

**Comment by Tyriar** [comment] 2018-12-19 19:07
@bengry I can't reproduce, is there anything in devtools console? (Help > Toggle Developer Tools)

**Comment by bengry** [comment] 2018-12-19 20:00
@Tyriar Just checked - no new messages in the devtools console when pressing Ctrl+`. I also tried disabling all of my extensions, just in case - still the same.

I do want to add that when choosing "Toggle integrated terminal" from the command palette, it does pop up the terminal, but not back down, the keystroke does nothing at all, ever. I do still have the same bindings in place, so it should work just the same:
![image](https://user-images.githubusercontent.com/260431/50244769-6f345d00-03d9-11e9-873b-64fc53cceef3.png)

**Comment by rebornix** [comment] 2018-12-19 20:39
@bengry do you happen to have extension page open? I have a feeling it shares the same root cause as https://github.com/Microsoft/vscode/issues/64724

**Comment by bengry** [comment] 2018-12-19 20:52
@rebornix Do you mean this page?:
![image](https://user-images.githubusercontent.com/260431/50247326-3cda2e00-03e0-11e9-9015-5433b8359a1b.png)

If so, I just tried it both with it, and on a random file being open - same thing.

I don't think it's related to it being trigged twice - but rather that Electron/VSC somehow using a different layout of the keys than the system's or something along those lines. If you look at my earlier comment, when I went to change the keybinding, then a) it worked just fine with any other key combination. b) it detected my keyboard's '`' key (which also shares '~' - this is the UK/European model of the MBP) as a § (which in my case is right next to the number bar, and shares it with ±). That's why I think the layout is the matter here.

**Comment by alexandrudima** [comment] 2019-01-07 09:19
We have lost the patch that "fixes" the Chromium key swap on ISO keyboards once we moved to Electron 3.0

**Comment by bpasero** [comment] 2019-01-07 10:38
@bengry can you try to reproduce with todays insider build?

**Comment by bpasero** [comment] 2019-01-07 10:39
Closing as duplicate of https://github.com/Microsoft/vscode/issues/65082

**Closed by bpasero** 2019-01-07 10:39 UTC
Labels: electron-3.0.x-update, keybindings

**Comment by bengry** [comment] 2019-01-07 16:01
@bpasero working after today's insiders build. Thanks!
