### ISSUE TITLE
After turning on formatOnSave some files are stuck in a loop of Saving.

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#13605] opened 2016-10-12 14:57 UTC
- VSCode Version: 1.6.0
- OS Version: Windows 10

The only way to get out of the loop is to click x on the file which brings up  a dialog asking to save.

these are my user settings:
```json
{
	"stylelint.enable": false,
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
		"**/dist": true,
		"**/typings": true,
		"**/tools": true
	},
	"explorer.autoReveal": false,
	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 10000,
	"files.trimTrailingWhitespace": true,
	"editor.formatOnSave": true
}

```

Steps to Reproduce:

1. 
2.

**Comment by jrieken** [comment] 2016-10-13 07:33
@sfabriece Can you reproduce this when running with the `--disableExtensions`-flag? Also the list of installed extension is needed to understand this. Last, the file type you are saving

**Comment by sfabriece** [comment] 2016-10-13 14:24
I'll investigate when I get back in about 3 hours.

**Comment by jrieken** [comment] 2016-10-17 13:57
@sfabriece ping

**Comment by pukhrajbal** [comment] 2016-10-17 22:11
Same issue happens for me on 1.6.1

**Comment by sfabriece** [comment] 2016-10-18 01:21
@jrieken I've removed some extensions i don't need. I'll report back.

**Comment by sfabriece** [comment] 2016-10-18 01:57
Running with the `--disableExtensions` flag didn't help.
here is the list of my extensions: 
![deps](https://cloud.githubusercontent.com/assets/3108592/19461688/fc2378a4-94e6-11e6-9c0d-9ca538e7a37c.png)

**Comment by jrieken** [comment] 2016-10-18 07:59
And you say it only happens when you have the `formatOnSave` enabled? The only thing it does is calling into extensions, so when running without them it is a no op. Do you see that with any file type or only some specific files, like JS, TS etc

**Comment by sfabriece** [comment] 2016-10-18 14:31
I'm using TS files and yes, the issue occurs only when the `formatOnSave is set to `true` in the user settings. Is there a way to verify that the `--disableExtensions` is enabled? Even though I started vscode from the terminal with the flag, I'm not sure that it actually run with it.

**Comment by jrieken** [comment] 2016-10-18 15:16
>  Even though I started vscode from the terminal with the flag, I'm not sure that it actually run with it.

The extension viewlet should be empty

**Comment by sfabriece** [comment] 2016-10-19 00:31
I'll try to  start without extensions and see if the problems persist.

**Comment by moanrose** [comment] 2016-10-19 07:55
I had a similar issue, it appears resolved when i disable the lonefy.vscode-JS-CSS-HTML-formatter extension. 
They even have an open issue for it:
https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/20

I dont know if you are using it..?

**Comment by jrieken** [comment] 2016-10-19 08:16
We track a related adoption item there as well: https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/30

**Comment by jrieken** [comment] 2016-10-25 15:30
closing as 'caused by extension' and until further information is supplied

**Closed by jrieken** 2016-10-25 15:30 UTC
Labels: needs more info
