### ISSUE TITLE
Parameter hints can be shown separately (to avoid overlapping with the code)

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode#212433] opened 2024-05-10 11:06 UTC
It would be nice if the box with function signature did not overlap with my code.
For example, it could be shifted to the right side or docked.
![image](https://github.com/microsoft/vscode/assets/8807043/fe169e01-eea5-4d4c-af0d-9f72b879c22d)

**Comment by T-256** [comment] 2024-05-10 11:52
duplicate of #149270

**Closed** 2024-12-09 21:58 UTC
Labels: *duplicate, editor-parameter-hints
