### ISSUE TITLE
git doesn't show error popup window

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#168854] opened 2022-12-12 10:41 UTC
Type: <b>Bug</b>

Git doesn't show anything when error occurs. It used to show a popup window to display the error.
The easiest way to reproduce this is cut you network and try to sync with remote repo. Nothing will happen. No error will show up.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.14.81.bm.23-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: |
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.74.12070927
remote-ssh|ms-|0.94.0
remote-explorer|ms-|0.0.3
material-icon-theme|PKi|4.22.0
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
prettier-vscode|esb|9.10.3
code-runner|for|0.11.8
shell-format|fox|7.2.2
vscode-language-pack-zh-hans|MS-|1.74.12070927
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
datetime|rid|2.2.2
code-spell-checker|str|2.12.0

</details>

**Comment by gjsjohnmurray** [comment] 2022-12-12 11:25
Maybe #168281, which 1.74.1 should resolve.

**Comment by lszomoru** [comment] 2022-12-12 13:39
@ladyrick, apologies for the inconvenience. This is already fixed in Insiders and will be in the next Stable recovery release.

**Comment by lszomoru** [comment] 2022-12-12 13:39
Closing as duplicate of https://github.com/microsoft/vscode/issues/168281.

**Closed by lszomoru** 2022-12-12 13:39 UTC
