### ISSUE TITLE
HTML comment formatting

### ISSUE THREAD

**Issue by saudes77** [Microsoft/vscode#48078] opened 2018-04-17 21:19 UTC
Issue Type: <b>Bug</b>

When I use html comments such as this,
`<!------------------------Gallery------------------------->`
the html following it is formatted/colored like if it's all part of the comment (in the case of my theme it's displayed in gray and italicized). Also, when I work on the code following the comment, none of the intellisense works. 

Basically, it seems that comments ending in more than two dashes are not being recognized as closed. I have used comments like this in other editors without an issue.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|7.90GB (0.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\VSCode workspaces\realdash-api.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.4.8
githistory|don|0.4.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1

</details>

**Comment by aeschli** [comment] 2018-04-18 07:45
duplicate of #13778.

See the HTML spec, your comment is invalid:

text must not ... contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-)

**Closed by aeschli** 2018-04-18 07:45 UTC
Labels: html

**Comment by LPProfit** [comment] 2018-05-10 14:54
Just want to note here that this only happens when there is an odd number of dashes at the end of a comment. Also, I cannot find any reference in the spec to the above restriction. Am I missing something? Thanks.

**Comment by aeschli** [comment] 2018-05-14 10:16
https://www.w3.org/TR/html51/syntax.html#comment
