### ISSUE TITLE
Misaligned Window Controls on macOS When Zen Mode is Active

### ISSUE THREAD

**Issue by milosdjakovic** [microsoft/vscode#218765] opened 2024-06-27 11:16 UTC
Does this issue occur when all extensions are disabled? **Yes**

- VS Code Version: 1.90.2
- OS Version: Sonoma 14.5 (Darwin arm64 23.5.0)

## Steps to Reproduce

1. Open Visual Studio Code
2. Open any project
3. Turn on "Zen Mode"
4. Run "Reload Window" 

Alternative Method:

1. Open Visual Studio Code
2. Open any project
3. Turn on "Zen Mode"
4. Close the Visual Studio Code window
5. Open any project (not a blank new window) in Visual Studio Code.

## Video
https://github.com/microsoft/vscode/assets/32454231/78ce7b0f-d6b3-47d8-befe-5fe90f6f03d3

## Expected Behavior
The window control buttons should be correctly aligned and placed in their designated positions.

## Actual Behavior
The window control buttons (close, minimize, and full screen) are displaced and not in the correct position within the UI under the following conditions:
- "Zen Mode" was activated in a previous session.
- A window is opened or reloaded within a project (not a blank window).
- The misalignment occurs while the window is initializing with "Zen Mode" still active.

## Workaround
To temporarily fix the issue, turn off "Zen Mode" and then reload the window. The window controls will snap back to their correct positions.

## Additional Context
The `Show Tabs` settings for both `Workbench` and `Zen Mode` are irrelevant. Each setting can be set to `none`, `single`, or `multiple`, and regardless of the combination of these values, the issue will still occur.

<details>
<summary><h2>Extensions</h2></summary>

```text
aaron-bond.better-comments
amazonwebservices.codewhisperer-for-command-line-companion
anteprimorac.html-end-tag-labels
astro-build.astro-vscode
biomejs.biome
bradlc.vscode-tailwindcss
britesnow.vscode-toggle-quotes
cardinal90.multi-cursor-case-preserve
chakrounanas.turbo-console-log
christian-kohler.path-intellisense
csstools.postcss
cucumberopen.cucumber-official
cweijan.vscode-mysql-client2
dart-code.dart-code
davidanson.vscode-markdownlint
dbaeumer.vscode-eslint
deerawan.vscode-faker
donjayamanne.githistory
dotjoshjohnson.xml
eamodio.gitlens
editorconfig.editorconfig
esbenp.prettier-vscode
exiasr.hadolint
foxundermoon.shell-format
github.copilot
github.copilot-chat
github.remotehub
github.vscode-pull-request-github
gruntfuggly.todo-tree
helgardrichard.helium-icon-theme
humao.rest-client
jeff-hykin.better-dockerfile-syntax
jeff-hykin.better-shellscript-syntax
johnpapa.vscode-peacock
louiswt.regexp-preview
mads-hartmann.bash-ide-vscode
mechatroner.rainbow-csv
mhutchie.git-graph
mikestead.dotenv
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-pack
mtxr.sqltools
nuxtr.nuxtr-vscode
oderwat.indent-rainbow
oven.bun-vscode
pmneo.tsimporter
redhat.vscode-xml
redhat.vscode-yaml
remisa.shellman
rogalmic.bash-debug
sdras.vue-vscode-snippets
sleistner.vscode-fileutils
stylelint.vscode-stylelint
tyriar.luna-paint
tyriar.sort-lines
unifiedjs.vscode-mdx
usernamehw.errorlens
vincaslt.highlight-matching-tag
vue.volar
woozy-masta.shell-script-ide
yoavbls.pretty-ts-errors
```
</details>

**Comment by curlyLasagna** [comment] 2024-06-30 20:20
I ran into the same issue, but occurs when toggling full screen in MacOS with zen mode on

My work around is to turn off zen mode in full screen

https://github.com/microsoft/vscode/assets/44715649/bb608ead-4aa8-464f-a1b3-61d3495fa8cd

**Comment by benibenj** [comment] 2024-07-01 07:38
Thanks for reporting this and giving a lot of context/video, this helps a lot! I tackled a similar bug this month which might also be the cause for this one, so it's possible it will be fixed in this weeks update. I'm still aware of another bug in this area, so if it won't be fixed in this weeks update, I hope to be able to fix it for the one next month.

**Comment by benibenj** [comment] 2024-07-01 07:40
These kind of bugs often are caused by the following two settings, could you let me know if you have modified one of these:
- `zenMode.restore`
- `zenMode.fullScreen`

**Comment by milosdjakovic** [comment] 2024-07-02 13:29
@benibenj,
Yes I have modified `zenMode.fullScreen`.
Here are all my modified settings related to `zenMode`:
```json
{
  "zenMode.centerLayout": false,
  "zenMode.fullScreen": false,
  "zenMode.hideLineNumbers": false,
  "zenMode.showTabs": "none",
{
```

**Comment by curlyLasagna** [comment] 2024-07-02 13:44
```json
"zenMode.fullScreen": false,
```

**Comment by milosdjakovic** [comment] 2024-07-04 14:57
@benibenj,
I no longer experience this issue after I updated Visual Studio Code to version `1.91.0`.

**Comment by benibenj** [comment] 2024-07-05 07:19
@milosdjakovic thanks for letting me know. @curlyLasagna have you updated? Do you still see it then?

**Comment by curlyLasagna** [comment] 2024-07-05 11:48
@benibenj Updated to `1.91.0` and no longer have this issue 🎉

**Comment by benibenj** [comment] 2024-07-05 12:21
Thank you both for letting me know! Closing the issue now

**Closed by benibenj** 2024-07-05 12:21 UTC
Labels: titlebar, workbench-zen
