### ISSUE TITLE
VSC crashes when left open for extended periods

### ISSUE THREAD

**Issue by craxal** [Microsoft/vscode#2618] opened 2016-02-01 17:52 UTC
I usually leave VSC running when I leave work for the day. But every following morning I come in and wake up my machine, I find a message informing me that VSC has crashed.

I should note that the machine VSC is running on is a virtual machine. I haven't observed issues with other machines.

**Comment by jrieken** [comment] 2016-02-02 07:50
I believe that's a dupe

**Comment by egamma** [comment] 2016-02-02 07:53
yes this is a dupe of #508

**Closed by egamma** 2016-02-02 07:53 UTC
