### ISSUE TITLE
crashing unexceptedly

### ISSUE THREAD

**Issue by Harjithundal** [microsoft/vscode#149424] opened 2022-05-13 06:48 UTC
Issue Type: <b>Bug</b>

from yesterday 12/05/2022
i m working in jupiter in some database stuff in python in sqlalchemy
and first time it crashed and poped up some message telling *close or *reopen the vscode or *Wait for Response

and now its happening again and again just for simple code also
i run small code that runs perfectly before this time its alaos facing isssue in that..
i can attch the screenshot what is popping up in window what i can see the attched file in here in writing issuees

kindly help to solve the problem i m in middle of my project
i can pay for the job if you can fix the issue
and explain me why it happened

its an urjent work reply me back as sooon as possible

Thanks...

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 6bffd291-9858-4ef9-a76f-30b1b173e295|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.5.0
vscode-log-viewer|ber|0.12.2
vscode-office|cwe|2.5.4
vscode-mysql|for|0.4.1
gc-excelviewer|Gra|4.2.54
nbpreviewer|jit|1.2.2
regionfolder|map|1.0.17
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.5.1001311010
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
view-in-browser|qin|0.0.5
java|red|1.6.0
swdc-vscode|sof|2.6.30
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
material-theme|zhu|3.13.29

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-05-13 06:55
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by jameswburton18** [comment] 2022-05-13 10:34
Fix: downgrading Pylance does the trick

https://github.com/microsoft/vscode/issues/149358#issuecomment-1125871918

**Comment by dbaeumer** [comment] 2022-05-13 12:52
Closing as duplicate of https://github.com/microsoft/vscode/issues/149358#issuecomment-1125871918

**Closed by dbaeumer** 2022-05-13 12:52 UTC
