### ISSUE TITLE
Add a setting to auto save after delay when stopped typing

### ISSUE THREAD

**Issue by liesislukas** [microsoft/vscode#46338] opened 2018-03-22 12:25 UTC
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOs 10.13.3 (17D102)

Steps to Reproduce:

1. run nodejs script with e.g. nodemon or some other watcher which restarts after file update
2. open javascript file and start typing
3. nodemon will detect file save event and will fire restart all the time during the typing and it will be huge CPU spike. It will throw type errors while you are in the middle of typing.

It should save after delay:

1. Type type type
2. wait _autoSaveDelay_ ms
3. save the file

Or we could have another option: `"files.autoSaveWhileTyping": false` and it would wait till no keyboard input for e.g. 250ms before autosaving, then wait for autoSaveDelay and then save.

Does this issue occur when all extensions are disabled?: Yes

**Comment by liesislukas** [comment] 2019-01-09 07:37
there could be an option to autosave when the editor loses focus. Because while typing you may stop to think and it could throw type errors easily. Or if autosave while typing, do it when no clear errors on file.

**Comment by aal89** [comment] 2019-02-28 15:09
I know you're asking for native functionality, so this is not a proper fix, but you can set a delay for `nodemon` too.

```
{
  "name": "nodemon",
  "homepage": "http://nodemon.io",
  "...": "... other standard package.json values",
  "nodemonConfig": {
    "ignore": ["test/*", "docs/*"],
    "delay": "2500"
  }
}
```

**Comment by fullstackwebdev** [comment] 2019-03-04 21:07
"autoSave" "afterDelay" is actually really buggy.  Because it doesn't wait until after you are done typing, it only waits after you have made changes, and it will autosave while you are still moving the cursor to another spot to make more changes.

The expected behavior should be -- wait until all keyboard input is done, then start the delay timer.  That way a user can move to the next spot (like a closing bracket a few lines down) without having to worry about racing against the editor saving a broken,due to the buggy delay code -- to then easily navigate to the next area, make changes, then wait for the delay to start to save.

it should be called "afterDelayFromChanges" and "afterDelay" should actually wait until .. there is a total delay in keyboard input. 

this is really nasty bug in my opinion, I am constantly having go to to 'autosave off' then make my changes, then turn autosave back on -- or all my nodemon watch tests will fail, unless I am fast enough to get to the next area (usually a closing bracket) needing changes.

**Comment by ryanpage42** [comment] 2019-05-27 17:18
This causes a lot of performance degradation for me. I'm also running nodemon and often the VSCode process will freeze due to poor save delay timing.

**Comment by minig0d** [comment] 2020-01-04 02:26
Completely agree with all the above.  In fact, I honestly don't understand why anyone would want it to save while they are actively interacting with the UI.

I would think be it default behavior or a separate setting that ideally it should wait for the app to be completely idle before starting the delay period.  And by idle, I mean not just keyboard interaction but mouse as well.

If you wanted to get REALLY technical, I'm kind of ok with mouse interaction outside of focus being considered "idle" but definitely if I'm actively typing or using the mouse within the file, I would not want the autosave delay to start counting down.

For those who code for long periods without a gap long enough for the autosave delay to kick in, there could be a new setting created that is basically "if we haven't autosaved in the past X minutes due to constant user activity, proceed with autosave anyway".  This way it's seemingly the best of both worlds.

**Comment by bpasero** [comment] 2020-01-10 16:59
@liesislukas and others, the code that triggers auto save today will work as requested: as long as the editor is being modified, the auto save is pushed out. You can see that from the code here: 
* https://github.com/microsoft/vscode/blob/26076a4de974ead31f97692a0d32f90d735645c0/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L524 is called every time you type into the editor
* https://github.com/microsoft/vscode/blob/26076a4de974ead31f97692a0d32f90d735645c0/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L564 will trigger the auto save if enabled
* https://github.com/microsoft/vscode/blob/26076a4de974ead31f97692a0d32f90d735645c0/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L599 finally will clear any previous scheduled auto saves

I am not sure what the original author saw or if it still applies, but I would go ahead and close this issue as invalid unless someone can show me an actual problem with auto save.

**Closed** 2020-01-22 07:34 UTC
Labels: needs more info
