### ISSUE TITLE
The commit button does not work when there is a # symbol in the description of the commit

### ISSUE THREAD

**Issue by OxxxHayFay** [microsoft/vscode#84463] opened 2019-11-11 08:52 UTC
- VSCode Version: 1.40.0

Steps to Reproduce:

1. Enter # symbol in a commit message field.
2. Commit button not work. No errors displayed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alperkay** [comment] 2019-11-11 09:24
i can confirm that i'm also experiencing the same issue.

**Comment by GiviZurabovich** [comment] 2019-11-11 09:32
Same problem

**Comment by gjsjohnmurray** [comment] 2019-11-11 09:51
/duplicate of #84201 
Upcoming recovery release (1.40.1) should resolve this.

**Closed** 2019-11-11 09:51 UTC
Labels: *duplicate, new release
