### ISSUE TITLE
Run code actions after saving the file

### ISSUE THREAD

**Issue by kurtextrem** [microsoft/vscode#221625] opened 2024-07-13 10:17 UTC
## Slow Code Actions on File Save
At times saving a file can be painfully slow. The cause can be multiple things, most likely slow extensions running code actions on save (so you're staring at a popup saying "Saving ...: getting actions from ..."). Now, well, you could bisect and disable the culprit extension. But what if eslint is slow? What if Biome is slow too? Running vscode with no extensions at all is not the solution. Disabling code actions on save also pretty much puts you back a century (as you no longer have formatting on save).

## Proposed Solution
A solution would be an option that does "save file instantly, apply code actions after". This way, you can ctrl+s, the file gets saved instantly and you can e.g. right away see the changes without waiting multiple seconds for code actions. Eslint fixes, prettier and whatever will then apply after the instant file save (possibly saving it again, or not, maybe also something to configure), so you care a little less about the slowness of the code actions. If you do a ctrl+s before the code actions have completed, it would save instantly again, discard the previous code actions run, and then re-run the code actions (basically a debounce mechanism).

**Comment by mjbvz** [comment] 2024-07-15 19:13
Slow code actions are annoying but this is not a good solution imo:

1. Saving without code actions/formatting can put  the file on disk in a bad state (invalid formatting or linting), which can mess up other tooling like watchers. Or the user may commit this file without realizing code actions haven't actually run 

1. You potentially end up having to save the file to disk twice with no clear feedback on when the second save will happen. Or if you don't save to disk automatically the second time, you end up with the file being randomly edited once code actions resolve

Have you tried filing issues against the extensions that have slow code actions?

**Comment by kurtextrem** [comment] 2024-07-15 19:20
The slow extension is eslint, which in turn is slow because of waiting for typescript. Also this is not a "me" problem only, if you ask on Twitter or in the dev community you'll find plenty of people experiencing this. 
As this would be an option (disabled by default?), you could think of it as remedy to an annoying issue slowing down impacted devs. Saving a file 7 seconds after Ctrl+s is quite literally worse than the two counter arguments you've mentioned

**Comment by mjbvz** [comment] 2024-07-15 20:03
> The slow extension is eslint

Then it should be fixed by eslint. If they truly can't make it any faster, then the action isn't a good fit to be run on save. You can setup a keybinding to run these code actions using `editor.action.sourceAction` instead

> Saving a file 7 seconds after Ctrl+s is quite literally worse than the two counter arguments you've mentioned

This doesn't address my points. The current behavior is deterministic and has a clear UX. We also identify why the save is taking so long so that the root cause (a misbehaving extension) can be addressed. If that doesn't work for you, you can disable code actions on save and use a command like I mention above

This proposal is a workaround that hides the root problem. It will get very limited use if it's not on by default and will also open up a whole new can of potential bugs and quirks, some of which are potentially quite bad

**Comment by justschen** [comment] 2024-12-11 22:07
closing as this is caused by an extension. also, users should now be able to cancel the save in the event of a long code action on save.

**Closed** 2024-12-11 22:07 UTC
Labels: *caused-by-extension, editor-code-actions
