### ISSUE TITLE
Position in file is lost when tabbing back and forth and find window is open

### ISSUE THREAD

**Issue by NickBack** [Microsoft/vscode#32772] opened 2017-08-18 10:32 UTC
- VSCode Version: 1.51.1 64bit
- OS Version: Windows 10

Steps to Reproduce:

You need the C# extension for this:

1. Open two actual C# files in Visual Studio Code.
2. Press Control + F to find something in one of the open files. Please note at roughly which line you are looking at.
3. Click the other tab or Ctrl+tab to switch.
4. Now click or ctrl+tab to switch back to the first file.
5. You will now be several lines below in the file than what you were previously.

If it doesn't happen the first time, repeat the tabbing back and forth a couple of times while keeping the find dialogue open.

I would expect I would be in the same place I left it.

This is related to the C# extension (and possibly similar extensions). I think it's because of the extra lines it adds (like the references). Not sure why it only happens when you have the find dialogue open.

Reproduces without extensions: No

**Comment by mattacosta** [comment] 2017-08-26 09:46
Probably a duplicate of #32397.

**Comment by rebornix** [comment] 2017-11-20 16:51
@NickBack can you provide a gif for better troubleshooting? The problem you described sounds familiar but I thought I fixed this issue from the very beginning.

**Closed** 2017-12-01 14:04 UTC
Labels: editor-find, needs more info
