### ISSUE TITLE
The behavior of terminal ICON when alt is pressed

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#187988] opened 2023-07-15 15:54 UTC
![1689436231812](https://github.com/microsoft/vscode/assets/48614781/c2709d8c-a9bb-49c4-a139-951a4a3c06ab)

all turned into split.....is it normal behavior

**Comment by joaomoreno** [comment] 2023-07-25 14:12
@Tyriar, this seems to be as designed:

- https://github.com/microsoft/vscode/blob/4f161d4dac46c54c25cb8ecc958e0f87377db767/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L399-L404
- https://github.com/microsoft/vscode/blob/4f161d4dac46c54c25cb8ecc958e0f87377db767/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L508-L513

**Comment by Tyriar** [comment] 2023-07-25 14:25
@joaomoreno it's by design they have alt actions, I sent this over as more feedback for the holding alt globally change.

**Comment by joaomoreno** [comment] 2023-07-25 16:12
Got it, closing as designed then, since the user just asks if this is normal.

**Closed by joaomoreno** 2023-07-25 16:12 UTC
