### ISSUE TITLE
Menus are gone?

### ISSUE THREAD

**Issue by LinuxJon92** [Microsoft/vscode#63173] opened 2018-11-14 23:20 UTC
Issue Type: <b>Bug</b>

Menus are gone/invinsible unless i have another windows open, everything was fine until the lastest update. https://imgur.com/a/E2uya0O

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor (2 x 3193)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.01GB (0.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by sbatten** [comment] 2018-11-15 18:08
Duplicate of https://github.com/Microsoft/vscode/issues/62593

Please see https://code.visualstudio.com/docs/setup/linux#_low-contrast-menu-bar for info on this issue.

**Closed by sbatten** 2018-11-15 18:08 UTC
Labels: new release
