### ISSUE TITLE
Markdown outline: strip `#` in headers

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#92104] opened 2020-03-05 18:18 UTC
![image](https://user-images.githubusercontent.com/4033249/76012170-ae5da980-5eca-11ea-989f-1c4ce0f3cb55.png)

They make it quite hard to read. The tree already indicates structure.

**Comment by mjbvz** [comment] 2020-03-05 20:16
Duplicate of #53992

**Closed by mjbvz** 2020-03-05 20:16 UTC
