### ISSUE TITLE
tab size shows up as 2 spaces but it is 4 spaces

### ISSUE THREAD

**Issue by davisnando** [Microsoft/vscode#42090] opened 2018-01-24 12:25 UTC
When I press tab and have everything on 4 spaces as tabsize it shows up as 2 spaces but It is actualy 4 spaces

![screenshot from 2018-01-24 13-20-45](https://user-images.githubusercontent.com/10762569/35332023-dfd0aa2e-0109-11e8-94b0-0811db5fe836.png)
The screenshot above is how a 4 spaces tab size shows up 

- VSCode Version: 1.19.2
- OS Version: ubuntu 17.10

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-01-26 08:24
@davisnando I'm not entirely sure what the problem is from your description (which is confusing). Is this a rendering issue (something off when rendering tabs) or a functional issue (inserts spaces when pressing Tab even though it is configured to insert tabs).

Here is how VS Code shows its configuration in the status bar: For example, this means it is configured to insert tabs and that they should be painted with the width of 4 spaces:
![image](https://user-images.githubusercontent.com/5047891/35430841-4b9f8984-027a-11e8-8cd4-7df5aaf24bc2.png)

Can you please clarify?

**Comment by davisnando** [comment] 2018-01-26 10:15
Its a rendering error 
This is my tab size:
![screenshot from 2018-01-26 11-08-44](https://user-images.githubusercontent.com/10762569/35434990-594f111c-0289-11e8-898a-129cfd7aa103.png)

vscode renders it as 2 spaces

This is when I enable renderwhitespace change to 'all' some dots are under my text:
![screenshot from 2018-01-26 11-13-48](https://user-images.githubusercontent.com/10762569/35435181-060c66ac-028a-11e8-9167-c9d30d409301.png)


If you look closely you can see that it renders a whitespace between the r and the e

**Comment by davisnando** [comment] 2018-01-26 12:30
This is what it looks like when you change the tab size to 1

![screenshot from 2018-01-26 13-28-24](https://user-images.githubusercontent.com/10762569/35439859-fdc3ddf0-029c-11e8-865b-f2e61e965f3e.png)

**Comment by alexandrudima** [comment] 2018-01-29 13:21
@davisnando 

What font do you use? What are your settings?

I believe there might be a glitch in the code where we read the width of `&nbsp;` or perhaps the font is simply very very weird.

**Comment by davisnando** [comment] 2018-01-29 13:43
I use the default font ```  "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"```

**Comment by davisnando** [comment] 2018-01-29 13:45
I changed the font and its normal now. Its the font thats glitching

**Comment by alexandrudima** [comment] 2018-01-29 13:59
I just tried 'Droid Sans Mono', but I cannot reproduce:

![image](https://user-images.githubusercontent.com/5047891/35513873-b5fb9d40-0504-11e8-9c04-161f3d2c11e5.png)

I don't know if the font is versioned or how to find out which version I have. I got to Ubuntu 17.10 by upgrading from 16.10, so I don't know if that makes a difference.

**Comment by davisnando** [comment] 2018-01-29 14:04
I had 16.10 then 17.04 and then 17.10 maybe that makes a difference But when I change to only 'Droid Sans Mono' it works too only when i have this ```"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"``` it wont work

**Comment by alexandrudima** [comment] 2018-01-29 15:31
I've tried all combinations I could think of, starting from:
```
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"
"editor.fontFamily": "'monospace', monospace, 'Droid Sans Fallback'"
"editor.fontFamily": "monospace, 'Droid Sans Fallback'"
"editor.fontFamily": "'Droid Sans Fallback'"
```

I still cannot reproduce... If you are able to change the font to something else that unblocks you, I'd say we can close this issue ...

**Closed** 2018-01-30 08:54 UTC
Labels: needs more info
