### ISSUE TITLE
No changes but still seems like it has changes

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#226786] opened 2024-08-27 16:28 UTC
Testing #226665

![image](https://github.com/user-attachments/assets/0ec58085-823e-4658-ae65-40d364bdb3e0)

This was a old notebook. Not really sure what the changes are, but it might be changes to the JSON itself, rather than the content. But, it is not clear from this view why it says there is a difference.

**Comment by DonJayamanne** [comment] 2024-08-27 20:13
@karthiknadig Please can you open the plain text diff viewer (icon on the trop right in editor toolbar area)

**Comment by karthiknadig** [comment] 2024-08-27 20:34
![image](https://github.com/user-attachments/assets/f821348e-f574-4d1e-a09c-f9067ac04637)

This is what it shows with plain text diff viewer

**Comment by DonJayamanne** [comment] 2024-08-27 21:17
Duplicate of https://github.com/microsoft/vscode/issues/208280

**Closed by DonJayamanne** 2024-08-27 21:17 UTC
Labels: bug, info-needed, notebook, notebook-diff
