### ISSUE TITLE
Trying to Search using variable length look-behind suggests enabling search.usePCRE2, but no such setting

### ISSUE THREAD

**Issue by peter-ovo** [microsoft/vscode#79109] opened 2019-08-14 11:52 UTC
- VSCode Version: 1.37.0

Steps to Reproduce:

1. ⇧⌘F (Open Find in Files)
2. Enter a regex with a _**non-constant** length_  look-behind, such as `(?<!a.*)b`
3. <img width="451" alt="Screenshot 2019-08-14 at 12 34 09" src="https://user-images.githubusercontent.com/53533395/63018922-e69b8d00-be91-11e9-95e9-c33eca97806d.png">
4. Click `Open Settings`
5. <img width="257" alt="Screenshot 2019-08-14 at 12 50 04" src="https://user-images.githubusercontent.com/53533395/63019086-5873d680-be92-11e9-8261-badea2626066.png">

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by IllusionMH** [comment] 2019-08-14 13:28
/needsMoreInfo

This flag was deprecated in 1.37 because these features should be enabled automatically https://code.visualstudio.com/updates/v1_37#_search-regex-features

Do you see any errors in DevTools (**Help > Toggle Developer Tools**) when you performs search?

**Comment by petevo** [comment] 2019-08-14 15:41
@IllusionMH No errors in the DevTools Console. I have also tried the same on the Insiders' build `ba69d8dcccaebbfaa94906503728eb7c3e45b9c1` without plugins, can also reproduce there.

**Comment by petevo** [comment] 2019-08-14 15:45
Realised that fixed-length look-behinds work, this only happens with variable-length ones.

**Comment by IllusionMH** [comment] 2019-08-14 16:04
Oh, looks like it is
/duplicate of #70156

**Comment by IllusionMH** [comment] 2019-08-14 16:19
@petevo do you see error message under the search field?
![image](https://user-images.githubusercontent.com/1312662/63037491-dc948100-bec7-11e9-987c-e2d50daf2ad7.png)


Probably I erroneously marked this as duplicate, because while inability to use variable length lookbehind can't be fixed, it make sense to use this issue to remove irrelevant error message in notification. @roblourens what do you think?

**Comment by roblourens** [comment] 2019-08-14 23:03
Yeah so when search returns a regex parse error, we suggest trying the PCRE2 setting because that supports some features that ripgrep by default doesn't. But, now that setting is deprecated because ripgrep is able to fall back on PCRE2 automatically. So this notification needs to be removed.

We could parse a better error message out of ripgrep's output but it's a bit of a pain and wouldn't be localized. e.g. in this case it looks like


```
regex could not be compiled with either the default regex engine or with PCRE2.

default regex engine error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (?<!a.*)b
    ^^^^
error: look-around, including look-ahead and look-behind, is not supported
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PCRE2 regex engine error:
PCRE2: error compiling pattern at offset 0: lookbehind assertion is not fixed length
```

**Comment by IllusionMH** [comment] 2019-08-15 10:26
Are there a lot of features that are supported in JS (Find) but not in PCRE2 (Find in Files)?

If it's only one - won't it be enough to search for `lookbehind assertion is not fixed length` and have specific error for this case only because it will work fine in Find, but not in Find in Files?

**Comment by roblourens** [comment] 2019-08-18 16:21
Trying it, it seems like JS doesn't support variable length lookaround either, it just doesn't show an error message. I don't think there are a lot of features that fall into this gap but I don't have a list.

Regarding localization, I could map ripgrep errors to localized errors, but most regex parse errors will actually just come from JS because first we try to parse the regex in JS. I don't want to try to localize those. There are a lot and we will just make it harder to google.

**Comment by IllusionMH** [comment] 2019-08-18 18:59
> Trying it, it seems like JS doesn't support variable length lookaround either, it just doesn't show an error message.

Strange. Just tried in VSCode DevTools, and it works just fine (in Chromium and same node version).

![image](https://user-images.githubusercontent.com/1312662/63228840-c78a5b80-c201-11e9-8013-b22374eaffe1.png)

Am I doing something wrong?

---

As for localization - I saw cases where message returned almost as is from engine and understand why it makes a little sense to localize other.

>  will just make it harder to google.

Nice point!

**Comment by roblourens** [comment] 2019-08-18 19:36
> Am I doing something wrong?

No, I am... I can't write regexes in the morning, you are correct.

**Closed** 2019-08-29 22:28 UTC
Labels: bug, search
