### ISSUE TITLE
Improve UX when VS Code can't reach Marketplace

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58588] opened 2018-09-13 09:27 UTC
Coming in as an item from the Marketplace outage postmortem analysis. We need to handle being offline and/or not being able to reach the Marketplace in a better way. It's hard to distinguish both scenarios (user offline vs marketplace offline) but we gotta see what we can come up with.

It would also be interesting it we could check some service status somewhere and inform the user that something is wrong in the service itself.

**Comment by egamma** [comment] 2018-09-13 10:03
Looks like a dupe of #57901

**Comment by sandy081** [comment] 2018-09-13 11:13
Duplicate of #57901

**Closed** 2018-09-13 11:13 UTC
Labels: *duplicate
