### ISSUE TITLE
[Question][ Suggestion] Side panel - extensions

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#9400] opened 2016-07-17 00:48 UTC
- VSCode Version: 1.4.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

The icons no longer appear when using the Visual Studio are standard width. It is possible to go back as it was? I think better to show the icon next to the name in the standard width ... if smaller, go diminishing until it is possible to see only the extension icon may not decrease more - minimum width would be the size of the extension icon.

Comparing versions:

1.2.1 - stable
![capturar](https://cloud.githubusercontent.com/assets/19866231/16898023/634005c2-4b9d-11e6-9e96-b39783ec3585.JPG)
1.3.0 - insider
![capturar2](https://cloud.githubusercontent.com/assets/19866231/16898030/85f91360-4b9d-11e6-919f-f569d1a3e781.JPG)
1.3.1 - stable
![capturar4](https://cloud.githubusercontent.com/assets/19866231/16898031/91b9017e-4b9d-11e6-94c3-44e2565dce38.JPG)
1.4.0 - insider
![capturar3](https://cloud.githubusercontent.com/assets/19866231/16898036/a5ed4f42-4b9d-11e6-9cc6-f77f8bb61e7a.JPG)
1.3.1 - stable x 1.4.0 - insider (default)
![capturar5](https://cloud.githubusercontent.com/assets/19866231/16898039/b6308086-4b9d-11e6-9e02-c444b802da41.JPG)
1.3.1 - stable x 1.4.0 - insider (Adjusted at least to appear extensions)
![capturar6](https://cloud.githubusercontent.com/assets/19866231/16898046/cf3ed596-4b9d-11e6-927a-54833c2f88a5.JPG)

I believe that the previous size of the other versions is enough for many tasks, not the loss of space in the workspace, if necessary leave the panel open.

**Comment by rebornix** [comment] 2016-07-17 05:14
Thanks @Tekbr for reporting this issue, it's duplicate of #9218 and we've got a fix for it.

**Closed by rebornix** 2016-07-17 05:14 UTC
