### ISSUE TITLE
Emmet --> w100p doesn't appear in the snippets list

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33269] opened 2017-08-28 15:33 UTC
- VSCode Version: 1.15.1
- OS Version: win7x64

**w100p** and **h100p** (and everything with "p" at the end) don't want to appear in the snippets list.
So, we cannot use "Enter" to expand it.
We can only force it to expand, using Tab.
Not good.

![w100p](https://user-images.githubusercontent.com/24613274/29780550-e4b6c5f6-8c1e-11e7-9daf-d43a0125af8e.gif)

**Comment by ramya-rao-a** [comment] 2017-08-28 22:15
Duplicate of https://github.com/Microsoft/vscode/issues/32277#issuecomment-321836737

**Closed by ramya-rao-a** 2017-08-28 22:15 UTC
Labels: emmet, new release

**Comment by user3323** [comment] 2017-09-02 14:44
@ramya-rao-a, hello!

Can you add "lsn" for `list-style: none;` ?

![image](https://user-images.githubusercontent.com/24613274/29996378-2d4d6fa0-9006-11e7-811a-528bc8ba3a12.png)

**Comment by ramya-rao-a** [comment] 2017-09-02 22:03
@user3323 The default css snippets used by Emmet 2.0 can be found here: https://github.com/emmetio/snippets/blob/master/css.json

Even if we add one for `list-style:none`, it will still have the issue of "none" taking focus for editing.
I have logged an upstream issue https://github.com/emmetio/css-snippets-resolver/issues/2 for this issue of the property value taking up focus. Let's continue the discussion there.
