### ISSUE TITLE
lagging on macpro

### ISSUE THREAD

**Issue by jimmymalhan** [microsoft/vscode#115546] opened 2021-02-01 15:05 UTC
Whenever I type a command,  I see a constant lag to purse on command. 
![Screen Shot 2021-02-01 at 7 04 05 AM](https://user-images.githubusercontent.com/32525076/106476235-b2d46e80-645b-11eb-9e47-f38bac1dcd14.png)

Note: It's less lagging on my older mac air 2015

**Comment by gjsjohnmurray** [comment] 2021-02-01 15:08
Is this VS Code Stable, 1.52.1 ? If so, can you try [Insiders](https://code.visualstudio.com/insiders/)? Else please wait for the 1.53 release which is expected by the end of this week.

**Comment by meganrogge** [comment] 2021-02-01 17:12
Duplicate of #111074

**Closed** 2021-02-01 17:12 UTC
Labels: *duplicate
