### ISSUE TITLE
Better Shortcut Key source declaration

### ISSUE THREAD

**Issue by shreym03** [microsoft/vscode#91683] opened 2020-02-27 12:18 UTC
Issue Type: <b>Feature Request</b>

It's a very small feature to request, but I want better information about which extensions or keymaps have implemented which shortcut keys in my VS Code Editor. Currently, when you want to see what was the source of the shortcut, it only shows it as "User" or  "Default".  But there are so many shortcuts that are created by extensions and keymaps that it tends to cause overlapping of functions. It would also make it easier to sort it out by precedence and would be a better quality of life feature

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: -

**Comment by Delapouite** [comment] 2020-05-07 07:49
Looks likes a duplicate of https://github.com/microsoft/vscode/issues/37034 which should be addressed by the PR https://github.com/microsoft/vscode/pull/95713

**Closed** 2020-05-07 12:08 UTC
Labels: *duplicate, keybindings-editor
