### ISSUE TITLE
Process Explorer doesn't work on WSL (screen size is bogus)

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#98590] opened 2020-05-26 14:41 UTC
Issue Type: <b>Bug</b>

1. Open a WSL window
2. Help > Open Process Explorer

![image](https://user-images.githubusercontent.com/8235156/82913925-e2ca8a00-9f3c-11ea-96fc-84eac1d207a9.png)

It looks similar to #75932.

A possible fix might be:
- https://github.com/microsoft/vscode/issues/75932#issuecomment-595848213
- [implementation](https://github.com/OmniSharp/omnisharp-vscode/pull/3634)

cc: @RMacfarlane 

VS Code version: Code - Insiders 1.46.0-insider (2591ede95a52400d5d22989b16706f9b8b4831da, 2020-05-22T21:13:15.709Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
graphql-for-vscode|kum|1.15.3
vscode-emacs-friendly|lfs|0.9.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
powershell-preview|ms-|2020.5.0
debugger-for-chrome|msj|4.12.8
material-theme|zhu|3.7.1

</details>

**Comment by allymparker** [comment] 2020-05-26 15:40
Seeing this too, trying to attach to a dotnet process in WSL 2 in both insiders and stable:

![image](https://user-images.githubusercontent.com/2056009/82920726-8d5ba080-9f6f-11ea-8b87-079b9874f211.png)

Version: 1.46.0-insider (user setup)
Commit: 8687508aa689b1f16d5f6ff317eb25bcf4544586
Date: 2020-05-26T05:47:43.684Z (9 hrs ago)
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by underchemist** [comment] 2020-06-13 20:40
Also experiencing this with WSL 2 trying to debug using gdb (Attach)

**Comment by carlossanlop** [comment] 2020-08-06 22:32
@weinand @JoeRobich
I am reproducing this issue when trying to bring up the prompt textbox to select the process ID of the process to attach.

Unfortunately, this PR https://github.com/OmniSharp/omnisharp-vscode/pull/3634 did not fix the original reported issue https://github.com/microsoft/vscode/issues/75932

My environment:

- WSL2 with Ubuntu 20.04.
- Omnisharp v1.22.1
- Visual Studio Code Insiders:
![image](https://user-images.githubusercontent.com/1175054/89589033-b616d680-d7f9-11ea-87ab-7f21348c4d92.png)

Is there a workaround? This issue has been around since at least June 2019.

**Comment by RMacfarlane** [comment] 2020-08-06 22:43
@9to8 You had a proposed fix for this a while ago that looked good to me, do you want to go ahead and check that in?

**Closed** 2020-08-11 17:38 UTC
Labels: bug, workbench-diagnostics
