### ISSUE TITLE
tsx In the 1.24.1 version manifestation

### ISSUE THREAD

**Issue by SunOfHomeBoy** [Microsoft/vscode#52532] opened 2018-06-21 02:15 UTC
- VSCode Version:
    版本 1.24.1
    提交 24f62626b222e9a8313213fb64b10d741a326288
    日期 2018-06-13T17:51:32.889Z
    Shell 1.7.12
    渲染器 58.0.3029.110
    Node 7.9.0
    架构 x64

- OS Version:
    win10Pro

Steps to Reproduce:

1. I wrote tsx with vue, but html label in tsx is can't fold

![image](https://user-images.githubusercontent.com/30047595/41694170-94fa288a-753b-11e8-8cf6-f49a3b489a24.png)

2. I hope the authorities can fix this bug as soon as possible

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SunOfHomeBoy** [comment] 2018-06-21 02:41
Every update comes with a problem, But that's a good thing！That means VSCode is making progress！
Thanks to Microsoft!

**Comment by mjbvz** [comment] 2018-06-21 06:10
Duplicate of #51266

See that issue for root cause and workaround

**Closed by mjbvz** 2018-06-21 06:10 UTC
Labels: extensions
