### ISSUE TITLE
Please allow webview for the side bar panel

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#51560] opened 2018-06-10 19:59 UTC
Hi,

I would like to suggest to open up the side bar panels for webviews.

My use case is the following: I'm developing a debug adapter and i'm displaying 
a memory viewer/editor in a webview.

It looks like this:
![image](https://user-images.githubusercontent.com/3081973/41205720-fac83fee-6cf8-11e8-8a97-512da75dfaab.jpeg)

It works but the problem is that when you step through the code the source files change
(depending on the program counter) and get focus. The same time the memory viewer (webview)
is hidden.

So it is very difficult to watch the memory and the program being stepped at the same time.

The best solution would be to put the memory viewer also in the side bar. So, even if the source file changes focus, the memory can still be viewed and is always visible.

**Comment by mjbvz** [comment] 2018-06-18 15:17
Duplicate of #46585

**Closed by mjbvz** 2018-06-18 15:17 UTC
Labels: debug, feature-request
