### ISSUE TITLE
[regression] Icons dont show in Explorer

### ISSUE THREAD

**Issue by venil7** [Microsoft/vscode#23536] opened 2017-03-29 09:25 UTC
- VSCode Version: Version 1.11.0-insider
Commit d98a518c5485bd7a47c70f5b3783f70efa5edcd6
Date 2017-03-29T06:11:14.271Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Windows7 enterprise SP1

Steps to Reproduce:

1. Open vs code
2. Observe icons are not displayed next to files and folders (empty gap is displayed instead, see pic)

![image](https://cloud.githubusercontent.com/assets/508022/24447781/04c434b4-146a-11e7-850a-9d8e768cb661.png)

**Comment by aeschli** [comment] 2017-03-29 09:26
duplicate of #23346

**Closed by aeschli** 2017-03-29 09:26 UTC
