### ISSUE TITLE
Startup of insiders is hung when opening anything

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#142786] opened 2022-02-10 23:52 UTC
Does this issue occur when all extensions are disabled?: Can't tell. Went away on restart

- VS Code Version: 1.65.0-insider (user setup)
Commit: 82a8bec63666b0883d9bf762ee2aaa87e9be9a3a
Date: 2022-02-10T05:16:36.093Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open a folder
2. Open a notebook

I get this:

![image](https://user-images.githubusercontent.com/19672699/153516472-46f55394-7f11-4208-a3b8-dd97d1cba52f.png)

**Comment by roblourens** [comment] 2022-02-11 00:49
I hit this once too

**Comment by deepak1556** [comment] 2022-02-14 07:25
This seems to be same as https://github.com/microsoft/vscode/issues/140114 but we didn't have a clear repro at that time. @alexdima is there any additional logs we can obtain to narrow down where exactly the extension host got stuck when trying to load extensions ?

**Comment by alexdima** [comment] 2022-02-14 15:35
Another occurrence in https://github.com/microsoft/vscode/issues/142766

**Comment by alexdima** [comment] 2022-02-22 14:32
@bpasero @deepak1556 Do we plan to ship stable with Electron 16? This might be a blocker.

**Comment by deepak1556** [comment] 2022-02-22 15:12
@alexdima yup the current plan is to ship this milestone.

Maybe we can add some additional logging to help narrow down where in the extension load code path things are getting stuck, this can help if we get similar reports once shipped to stable. Currently we had only a single occurrence of this issue for those who encountered it, so there is not much we could progress on diagnosing it. I didn't want to block the update because of that.

Also if we revert to Electron 13, we will on an EOL release line https://www.electronjs.org/blog/electron-17-0#end-of-support-for-13xy and anything > 13 will have render process reuse by default but the downside will be not having self hosted with insiders.

**Comment by alexdima** [comment] 2022-02-22 16:14
@deepak1556 I was able to reproduce when running `scripts\code.bat` and doing a few `Ctrl+R` on a Windows VM (i.e. slow machine). I am using a TS file with a compilation error and the hint is that the compilation error doesn't show. There is no other indication that something is wrong. I believe that this might be the same weird behavior around named pipes / sockets that do not send data we saw when we met some time ago trying out Playwright for Electron.

@bpasero @deepak1556  Could you please also try to reproduce?

**Comment by deepak1556** [comment] 2022-02-22 16:26
Oh was not aware of that, will give it a try. Thanks for the steps!

**Comment by bpasero** [comment] 2022-02-23 06:55
I tried to reproduce in my Windows 11 ARM VM and was not successful. Tried a few window reloads on a small TypeScript project with an editor open that has a compile error.

**Comment by deepak1556** [comment] 2022-02-23 07:45
@bpasero I am also on Windows 11 ARM vm and couldn't repro it so far, but the trick to repro it is to have some memory intensive tasks running in the background (building electron does the trick for me). I am now able to repro the issue.

**Comment by deepak1556** [comment] 2022-02-23 11:19
Created a minimal repro https://gist.github.com/deepak1556/59f981cd8a55cda92beadd6bf97330a9, that shows a ping/pong via nodejs sockets between renderer process and child process forked from the main process. After a couple of reloads, the server/renderer will get into a state were the async tasks gets queued up and does not process until another explicit task is executed to flush out the queue. 

An example state when event loop is paused:

```
Forked process: Child process created
Forked process: Connected to named pipe as client
[4124:0223/200645.092:INFO:CONSOLE(35)] "Connected to named pipe as server", source: file:///C:/Users/demohan/github/electron-quick-start/renderer.js (35)
Forked process: rec'd from server: pong!
[4124:0223/200658.631:INFO:CONSOLE(48)] "rec'd from client: ping 0", source: file:///C:/Users/demohan/github/electron-quick-start/renderer.js (48
```

At this point, executing a `setImmediate(() => { console.log('hello') })` resumes the loop for sometime but it gets to the bad state after a few more tasks. At first I thought it might be a side effect of the occlusion tracker on windows https://chromium.googlesource.com/chromium/src/+/master/docs/windows_native_window_occlusion_tracking.md that puts the renderer into a suspended state but the bug repros even when launching with `--disable-features=CalculateNativeWinOcclusion`. Pretty confident that this bug is what we are seeing at the larger scale with our extension host setup. Continuing to investigate why Electron renderer gets into this state, looks like a return of https://github.com/electron/electron/issues/1968 from the past with render process reuse enabled changes.

**Comment by zcbenz** [comment] 2022-02-25 08:44
It seems that after reloading the window, the IOCP will get into a weird state and event loop integration will stop functioning, so a workaround is to recreate the IOCP for each reload:

```patch
--- a/shell/common/node_bindings.cc
+++ b/shell/common/node_bindings.cc
@@ -576,7 +576,11 @@ void NodeBindings::LoadEnvironment(node::Environment* env) {
 }

 void NodeBindings::PrepareMessageLoop() {
-#if !BUILDFLAG(IS_WIN)
+#if BUILDFLAG(IS_WIN)
+  if (uv_loop_->iocp && uv_loop_->iocp != INVALID_HANDLE_VALUE)
+    CloseHandle(uv_loop_->iocp);
+  uv_loop_->iocp = CreateIoCompletionPort(INVALID_HANDLE_VALUE, NULL, 0, 2);
+#else
   int handle = uv_backend_fd(uv_loop_);

   // If the backend fd hasn't changed, don't proceed.
```

I'm still trying to figure out the root cause.

**Comment by deepak1556** [comment] 2022-02-25 10:26
Currently testing the above workaround with vscode.

**Comment by deepak1556** [comment] 2022-02-25 12:33
After a bit of testing, the extension host does not get unresponsive when the iocp is reinitialized on reload. Although, we now get a prompt that says `Reloading the window is taking longer than expected..` and it seems the issue arises from pending operation `join.closeStorage`. I will have to investigate why it regressed.

@zcbenz instead of reinitializing the iocp for the same process reload case, can we instead close the default uv loop and also perform the background thread cleanup which is usually done only during [~NodeBindings](https://github.com/electron/electron/blob/067cc8ae2b04ba40918a5f0c38f356c6e9cdfc7e/shell/common/node_bindings.cc#L328-L339), and reinitialize after reload ? Since we destroy the node environment for reload, I feel this should be safe to do, thoughts ?

**Comment by zcbenz** [comment] 2022-02-26 07:20
When navigating Chromium may load the new page before the old page is destroyed, so it is possible for multiple environments sharing the same loop in one process, and we probably don't have a good timing to close the default uv loop. But reinitializing IOCP has the same problem too.

In theory destroying and initializing Node.js environments should not affect the uv loop at all, by reading the code I couldn't find anywhere closing or initializing the uv loop, but somehow having multiple Node.js environments is making our node integration run into weird states, there were some efforts working around it (https://github.com/electron/electron/pull/25869 and https://github.com/electron/electron/pull/27582) but I think they are not fixing the root cause.

**Comment by zcbenz** [comment] 2022-03-02 23:01
It seems that the node integration only breaks when the first node environment is destroyed, everything works fine if we just create and destroy subframes or child windows. So I wonder if we can work around the problem by creating a dummy node environment in renderer before any web frame is created and keeping it alive forever.

The root cause is still mysterious to me though.

**Comment by deepak1556** [comment] 2022-03-08 11:21
I will put up a PR in Electron to further discuss this solution.

**Closed** 2022-03-25 03:29 UTC
Labels: bug, upstream, windows, extension-host, electron, confirmed, mitigated, electron-17-update

**Comment by rchiodo** [comment] 2022-03-25 22:39
/verified

Definitely working for me. Although I haven't repro'd this in while.
