### ISSUE TITLE
Import from any "node_modules" package points to the relative path instead of the package name

### ISSUE THREAD

**Issue by dukearena** [Microsoft/vscode#53937] opened 2018-07-10 08:26 UTC
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
OS: Win10

Steps to Reproduce:
1. In any typescript file, write a class name coming from a node_module package (as for example, TransferState from '@angular/platform-browser')
2. Click the bulb icon to display the import menu

Displayed items show only relative paths passing through node_modules, instead of the package name (see the picture below):

![image](https://user-images.githubusercontent.com/11449047/42497999-5c10352e-842b-11e8-8c43-e999e3526118.png)

Expected Result
```
Import 'TransferState' from module "@angular/platform-browser"
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jhage-accesso** [comment] 2018-07-10 12:10
Having this issue as well, working as expected in 1.24.1

**Comment by dotproto** [comment] 2018-07-10 15:24
Version: VS Code Version 1.25.0 
OS: macOS 10.13.5

I'm currently using the [Auto Import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport) extension to work around this issue.

![screen shot 2018-07-10 at 8 21 30 am](https://user-images.githubusercontent.com/1047763/42520096-4cb8b652-841a-11e8-867e-7d21fddb4414.png)

**Comment by dotproto** [comment] 2018-07-10 15:32
Just checked Insiders (1.26.0-insider) and I couldn't reproduce this issue. Hopefully 1.25 can be patched to address this issue.

**Comment by mjbvz** [comment] 2018-07-10 18:31
Duplicate of #53597

Either upgrade to VS Code insiders or upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-07-10 18:31 UTC
Labels: javascript

**Comment by starquake** [comment] 2018-07-11 09:04
Alternatively you can switch to using your workspace version by clicking on the version number at the bottom:
![image](https://user-images.githubusercontent.com/1044544/42561699-1530ab50-84fa-11e8-9190-74984144bde0.png)
And clicking `Use workspace version`
![image](https://user-images.githubusercontent.com/1044544/42561744-2b03e078-84fa-11e8-8d4d-7316b951abf1.png)
