### ISSUE TITLE
BUG: Tasks error: execvp(3) failed on Insiders

### ISSUE THREAD

**Issue by rishabh3112** [microsoft/vscode#75897] opened 2019-06-21 14:52 UTC
Hi! I have been working on C++ on VS Code Insiders with remote development on WSL1 for about 2 months. Today an update was released which raised this error.
```
execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1
```

- VSCode Version: 13.6.0-insider
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:
1. Have a `tasks.json` like below
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "g++ -pipe -O2 -std=c++11 ${file} -o ${workspaceRoot}/outputs/${fileBasename}.out",
            "group": "build"
        },
        {
            "label": "Build and Run",
            "type": "process",
            "command": "${workspaceRoot}/outputs/${fileBasename}.out",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "dependsOn": [
                "Build"
            ],
            "problemMatcher": []
        },
        {
            "label": "Build for Debug",
            "type": "shell",
            "command": "g++ ${file} -o ${workspaceRoot}/outputs/${fileBasename}.out -g -ggdb",
            "group": "build"
        }
    ]
}
```
2. Have `outputs` and `programs` folders in root.
3. Run task with file being open
4. This error is encountered
![image](https://user-images.githubusercontent.com/15812317/59930333-5aa45080-9460-11e9-8763-43d239da2a0a.png)

The command works fine when executed on the terminal.

Does this issue occur when all extensions are disabled?: Yes

Thanks for such awesome editor!

**Comment by yamcenutzer** [comment] 2019-06-21 16:52
same here,
Works in released version and previous insiders.
My remote is centos machine and the task in question is a bash script.

**Comment by bluesherpa** [comment] 2019-06-23 20:55
This problem is occurring for me as well.  It looks like a, extra " <" character is being added to the of the command when it is executed, illustrated in rishabh3112's screenshot.

**Comment by alexr00** [comment] 2019-06-24 06:42
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/757

**Closed** 2019-06-24 06:43 UTC
Labels: *duplicate, tasks
