### ISSUE TITLE
Can't use Git command line when Visual Studio Code is open

### ISSUE THREAD

**Issue by mateid** [Microsoft/vscode#987] opened 2015-12-03 20:40 UTC
It looks like Visual Studio Code locks some files and I can't use the command line Git client when it is open. Closing Visual Studio Code resolves this issue. The index.lock file did not exist when I checked for it so it must be preventing the command line client from working in some other way. Here's the output from the command line client:

Updating ca3f107..3e957b8
fatal: Unable to create 'C:/dev/GIS/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by Balrog30** [comment] 2015-12-03 21:42
I've had this occasionally myself. I'm pretty sure it happens when VSCode is checking with git to see if there are any remote changes, and changed files, etc. Usually it doesn't last long for me, but for very large repositories I could see it taking a while. Normally I see this when I try to pull from a remote and a simple retry works fine. I don't know what could be done about this except to make vscode's interactions with git configurable. Git uses file-based locking and if the repository is being updated it needs to be locked to keep integrity.

**Comment by HuanhuanSunMSFT** [comment] 2015-12-03 23:42
I've had this consistently, especially when doing a git rebase with VS code open.

**Comment by joaomoreno** [comment] 2015-12-04 09:28
Duplicate of #901

**Closed by joaomoreno** 2015-12-04 09:28 UTC
