### ISSUE TITLE
editor.cursorSurroundingLines interacts unexpectedly with mouse clicks

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#80997] opened 2019-09-16 16:53 UTC
If I click within the 'surrounding lines' region the editor scrolls begins scrolling unexpectedly. It thinks I'm trying to select text and everytime it moves the cursor within the desired range it selects some more text, moves, the cursor to the end of the selection, and repeats the process.

I can't click in the 'surrounding lines' region without highlighting several lines of text and scrolling further than I intended.

Expected:
1) When clicking within the 'surrounding lines' region it should not be treated as a selection event unless I drag my mouse while the left button is down.

2) When selecting text with the mouse the `editor.cursorSurroundingLines` should not be active. Let selection go to the edge of the screen. Then when the mouse button is released do the extra scrolling based on this setting. Selecting text with the keyboard does not need to be changed.

![Dumb](https://user-images.githubusercontent.com/484784/64977307-fe3aac80-d867-11e9-8f31-f13c0862011e.gif)

**Comment by ababak** [comment] 2019-09-17 07:53
That's definitely a very annoying bug. There is another issue on this matter: https://github.com/microsoft/vscode/issues/79935

**Comment by gjsjohnmurray** [comment] 2019-09-23 08:44
/duplicate of #79934 most likely, assuming @akbyrd isn't using the Insider build where that is already fixed.

**Closed** 2019-09-23 08:44 UTC
Labels: *duplicate

**Comment by akbyrd** [comment] 2019-09-23 16:34
@gjsjohnmurray Not an insiders build. 1.38 release.

**Comment by gjsjohnmurray** [comment] 2019-09-24 07:19
@akbyrd in which case there's a good chance your issue is already fixed. I suggest you retest when 1.39 is out (see #80591).
