### ISSUE TITLE
Poor setting search result ordering

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#105113] opened 2020-08-20 23:01 UTC
Issue Type: <b>Bug</b>

**Repro**
1. In the extensions view
1. Try searching for `default language` or `files default`

**Expected**
The `files: default language` setting shows up first

**Actual**
`files: default language` is often the third or second result:

![Screen Shot 2020-08-20 at 3 58 57 PM](https://user-images.githubusercontent.com/12821956/90834119-555dc280-e2fe-11ea-9b84-a3b1356f3154.png)

![Screen Shot 2020-08-20 at 3 59 07 PM](https://user-images.githubusercontent.com/12821956/90834129-5c84d080-e2fe-11ea-94ea-6d1489503384.png)

VS Code version: Code - Insiders 1.49.0-insider (8e872f41d4ba7807e58938bbf861ca6a22d534aa, 2020-08-20T05:32:51.717Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.24GB free)|
|Process Argv|-psn_0_54793278 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by rzhao271** [comment] 2023-12-05 20:52
Closing as a duplicate of #197773

**Closed by rzhao271** 2023-12-05 20:52 UTC
Labels: bug, settings-editor
