### ISSUE TITLE
vscode crashes when starting up at ubuntu 20.04

### ISSUE THREAD

**Issue by choucl** [microsoft/vscode#118727] opened 2021-03-11 14:38 UTC
The vscode was installed by apt. And it could be open for a few seconds, then it crashes automatically.

I tried to figure it out with the `code --verbose` command. It shows
```
[67802:0311/205929.505928:INFO:CONSOLE(626)] "%cTRACE color: #888 [File Watcher (node.js)] [CHANGED] /home/chou/.config/Code/logs/20210311T205927/telemetry.log", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
terminate called after throwing an instance of 'char const*'
/dev/fd/3: No such file or directory
Server response:
[67849:0311/205929.809879:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
```
The last line might be caused by the ssh-extension, so I have removed it manually from ~/.vscode/extensions.

But the problem still exists, I've also tried with the `--disable-extension flag`, but nothing changed.

The only way I can enter vscode now is by `sudo code --usr-data-dir` command. 

And here's the last few lines of `exthost.log` file:
```
[2021-03-11 22:07:54.814] [exthost] [debug] ProxyResolver#resolveProxy cached https://dc.services.visualstudio.com/api/profiles/AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217/appId DIRECT 
Error: Error for stack trace
	at Pe (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:3)
	at ProxyAgent.addRequest (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js:73:16)
	at new ClientRequest (_http_client.js:296:16)
	at Object.request (https.js:314:10)
	at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/agent-base/patch-core.js:23:20)
	at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/https-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
	at /usr/share/code/resources/app/node_modules.asar/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
	at Object.U [as request] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4165)
	at Function.e.makeRequest (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:7505)
	at Timeout.s [as _onTimeout] (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:17133)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[2021-03-11 22:07:55.351] [exthost] [info] extension host terminating: parent process 82934 does not exist anymore: kill ESRCH (code: ESRCH) (errno: ESRCH)
[2021-03-11 22:07:56.368] [exthost] [info] exiting with code 0
```
I wonder what would cause the problem, please help...

**Comment by th3void** [comment] 2021-03-11 15:04
Remove nodejs and vscode completely, after an apt autoremove and make an update, reinstall and nodejs and vscode and post the result.

**Comment by choucl** [comment] 2021-03-11 15:18
Sure. I have done the things above and the `--verbose` tells
```[92136:0311/230921.684765:INFO:CONSOLE(626)] "%cTRACE color: #888 Settings Sync: Getting accounts for github", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
[main 2021-03-11T15:09:21.721Z] menubarService#updateMenubar 1
terminate called after throwing an instance of 'char const*'
/dev/fd/3: No such file or directory
Server response:
```
and `exthost.log` tells 
```
[2021-03-11 23:09:21.723] [exthost] [debug] ProxyResolver#resolveProxy cached https://dc.services.visualstudio.com/api/profiles/AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217/appId DIRECT 
Error: Error for stack trace
	at Pe (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:3)
	at ProxyAgent.addRequest (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js:73:16)
	at new ClientRequest (_http_client.js:296:16)
	at Object.request (https.js:314:10)
	at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/agent-base/patch-core.js:23:20)
	at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/https-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
	at /usr/share/code/resources/app/node_modules.asar/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
	at Object.U [as request] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4165)
	at Function.e.makeRequest (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:7505)
	at Timeout.s [as _onTimeout] (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:17133)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[2021-03-11 23:09:22.314] [exthost] [info] extension host terminating: parent process 92195 does not exist anymore: kill ESRCH (code: ESRCH) (errno: ESRCH)
[2021-03-11 23:09:23.330] [exthost] [info] exiting with code 0
```
It was mostly the same at the beginning.

**Comment by choucl** [comment] 2021-03-12 10:04
The problem keep happening. But if I change to the insiders version, all the functionalities works fine, FYI

**Comment by Js-Brecht** [comment] 2021-03-17 05:38
I have the same problem on Ubuntu 20.10.  I don't think it's related specifically to vs-code, though.  It seems as though this crash is a side effect.

I am able to run `code-insiders` just fine on this machine, and I can run `code` or `code-insiders` on another computer (same operating system), using the same configurations.  I can even create a new user account on this computer, log into it and `code` works fine.  Log back into my normal user account, and `code` crashes with this exact error.

I have tried purging it, removing all the config files, wiping out nodejs, everything I can think of. I finally reinstalled using snap instead of the apt repository and it works.  It _**must**_ be something in the environment of my user account, but I can't seem to figure out what.

It's especially bizarre because it started happening randomly... went to bed one night and it was fine, woke up the next morning and it wouldn't start.  Thought maybe it had to do with some automatic library updates causing conflicts, but you would think that would effect the other user account, too. 

I wonder if this is more of an electron issue... I'm just not sure how to proceed with troubleshooting that.

**Comment by GodBleak** [comment] 2021-03-17 06:15
Same here.
I have removed vscode, all configuration directories, and reinstalled and the issue persists. I too have only had it work via snap.
`--verbose` output [here](https://pastebin.com/6ke7i5bS)

OS is Manjaro Linux 20.2.1 running KDE Plasma 5.21.2

**Comment by dac73** [comment] 2021-03-17 08:53
This happened to me also, and I think the problem is that I first installed the `snap` version, then removed it and installed the `deb` version. Now the `deb` version doesn't work. Looks like the `snap` installation messes with something, but I can't find where.

**Comment by tfnico** [comment] 2021-03-18 11:32
Similar fix for me. I've used the snap version for a few weeks and wanted to switch to the .deb version because of issues with keyboard shortcuts because of the input method ([see this issue](https://github.com/microsoft/vscode/issues/96041)).

Upon starting the app, it died after a few seconds every time with no visible error message. Even with `--disable-extensions` and a fresh `--user-data-dir` it crashed all the same.

I saw the following stack trace:

```
Error: Error for stack trace
        at Pe (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:3)
        at ProxyAgent.addRequest (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/index.js:73:16)
        at new ClientRequest (_http_client.js:296:16)
        at Object.request (https.js:314:10)
        at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/agent-base/patch-core.js:23:20)
        at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/https-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
        at /usr/share/code/resources/app/node_modules.asar/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
        at Object.U [as request] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4165)
        at Function.e.makeRequest (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:7505)
        at Timeout.s [as _onTimeout] (/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js:1:17133)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
```

Thanks to @dac73's hint above, I opened `Passwords and Keys` (keyring manager app on Ubuntu 20.04) and searched for "code", and found a Login entry `vscodevscode.github-authentication/github.auth` (probably because I authed there in order to use the Live Share extension). Removed it and now it works (also after re-authing with GitHub)!

**Comment by Tyriar** [comment] 2021-03-22 10:46
@RMacfarlane it seems saving an auth password in the snap and then using the deb will trigger a crash.

**Comment by RMacfarlane** [comment] 2021-03-22 17:10
Duplicate of https://github.com/microsoft/vscode/issues/116690

**Closed by RMacfarlane** 2021-03-22 17:10 UTC
Labels: authentication, freeze-slow-crash-leak, linux
