### ISSUE TITLE
[Inline Suggestions] Keyboard shortcut conflict with Emmet

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#127797] opened 2021-07-01 16:18 UTC
Some of the users of GitHub Copilot has reported that there's a keyboard shortcut conflict between the accepting inline suggestion and `emmet.triggerExpansionOnTab` setting. 

We should make sure that the keyboard shortcuts have the right precedence in this case. 
CC: @hediet

**Comment by hediet** [comment] 2021-07-01 17:00
I can reproduce the conflict with `emmet.triggerExpansionOnTab` with VS Code stable.
However, we already increased the priority of "Tab" in insiders. As I cannot reproduce it with VS Code Insiders, I think that already fixed it.

**Comment by TylerLeonhardt** [comment] 2021-07-06 20:37
I did this and noticed a conflict between emmet and copilot:

* set `emmet.triggerExpansionOnTab`
* type `span`
* Hit ESC to hide intellisense
* (copilot ghost text shows up)
* Hit TAB

Copilot suggestion is accepted. I'm not sure if this is expected or not.

@hediet can you provide a gif of how it didn't repro?
@Krzysztof-Cieslak can you also provide a gif of what you're doing so we have more context?

**Comment by hediet** [comment] 2021-07-07 07:57
> Copilot suggestion is accepted

This is exactly what I would expect to happen and I thought this issue was about.
You can hit ESC again to hide the inline suggestion and then tab to accept emmet.
You can also disable inline suggestions and trigger them manually (there is a command).

**Comment by TylerLeonhardt** [comment] 2021-07-07 13:57
Yeah that makes sense to be. Especially since the copilot suggestion is shown.

Me can close this again and I'll mark it as verified but @Krzysztof-Cieslak let us know if you have other feelings.

**Closed** 2021-07-07 13:57 UTC
Labels: bug, emmet, inline-completions, keybindings, verification-found

**Comment by melMass** [comment] 2021-08-09 01:03
I do see the copilot line but, suggesting to hit `tab`, but when I input tab it just adds a tab. Should I open a new issue?

Unfortunately, I have no access to the copilot repo even if I'm accepted and using the public beta, they did send me an invitation but it was already expired when I noticed.

**Comment by hediet** [comment] 2021-08-09 06:39
>  Should I open a new issue?

Please do that and ping me, thank you!

Can you figure out which other extension causes this?
Also, when copilot suggests an indentation, tab will only accept the indentation, not the full suggestion.

**Comment by bala0406** [comment] 2021-08-12 10:13
When I hit the tab to autocomplete the suggested code, it just adds a tab space. How to change the precedence for the tab key and several other shortcuts for GitHub copilot in VSCode?

**Comment by melMass** [comment] 2021-08-12 12:12
Thanks, I somehow missed @hediet response!

> When I hit the tab to autocomplete the suggested code, it just adds a tab space. 
 Yes, I think we have the same issue, let me open a new dedicated issue and I will tag you there.
