### ISSUE TITLE
Suggestion: semantic highlighting support

### ISSUE THREAD

**Issue by niieani** [Microsoft/vscode#1534] opened 2015-12-21 11:55 UTC
It would be great if VS Code supported the paradigm of semantic highlighting. 
In short, it makes syntax highlighting more useful, by varying the colors of the same syntax-types of different names in a given scope. This makes it easier to catch mistakes and to see the flow of variables (since every variable in a given scope has a unique color, yet based of the same color range).
Here's an in depth explanation of what is is with some examples: https://medium.com/@evnbr/coding-in-color-3a6db2743a1e#.n2zb9ohw8

Example - before:

![Before](https://cdn-images-1.medium.com/max/1760/1*CTbkJuYm0JUcHFTAgovAsg.png)

Example - after:

![After](https://cdn-images-1.medium.com/max/1760/1*TVSPOYO1z8GOVs3tuxNRqA.png)

**Comment by bpasero** [comment] 2015-12-21 12:59
@dbaeumer fyi

**Comment by Wosi** [comment] 2015-12-21 14:23
I think it's the same request as **"Provide an API for advanced source highlighting"**: https://github.com/Microsoft/vscode/issues/585

**Comment by egamma** [comment] 2015-12-21 19:57
Closing as a duplicate of #585

**Closed by egamma** 2015-12-21 19:57 UTC
Labels: feature-request
