### ISSUE TITLE
Output window sometimes doesn't display output

### ISSUE THREAD

**Issue by BenWeedon** [Microsoft/vscode#1622] opened 2015-12-24 00:30 UTC
When running a task (I'm running the default build task), and the output editor panel is closed, it sometimes opens up empty. I don't notice this bug if the output editor panel is already open and I run Ctrl+Shift+B; I only notice it when the panel is closed and Ctrl+Shift+B opens it up.

This does not happen every time, but I notice it most frequently (about 90% of the time) when the task being run is an invalid command (in my case, I was using g+ rather than g++).

The only extension I have installed is C++ IntelliSense

I'm running the latest version of VSCode on Windows 10.

**Comment by bpasero** [comment] 2015-12-24 08:50
Not sure if this is because of wrapping logic or something else, starting with @isidorn

**Comment by egamma** [comment] 2015-12-29 22:12
CC @dbaeumer

**Comment by dbaeumer** [comment] 2016-01-04 10:42
@BenWeedon: can you provide a workspace with a test file and a tasks.json that shows the problem. What value do you use for the showOutput property in the tasks.json

**Comment by BenWeedon** [comment] 2016-01-04 17:33
Sure thing! Here's a .zip of my test workspace. It just contains a basic test.cpp file and the tasks.json file, although the .cpp file probably doesn't matter at all. `showOutput` is set to "always".

[test_workspace.zip](https://github.com/Microsoft/vscode/files/77478/test_workspace.zip)

The tasks.json file tries to invoke the g+ command rather than g++, so it will result in an error. If the output tab is closed, and you run the build command (I'm doing it through CTRL+SHIFT+B), it will most frequently open up without any output in it. If the tab is already open, however, and you run the build command, it'll print the error output every time.

I haven't noticed this really at all for commands that take longer to display output (e.g. prints inside a running program, where the output window has already been open for a bit before the print takes place), so my best guess is that the "command not found" error output is printed too quickly, maybe before the output tab has a chance to fully initialize itself, so it misses that output.

**Comment by dbaeumer** [comment] 2016-01-05 10:11
@BenWeedon thanks for the test case. I was able to reproduce it. 

@bpasero as discussed, moving to you

**Comment by bpasero** [comment] 2016-01-05 18:43
@dbaeumer please debug this, someone calls clearOutput() and does not give any output, just add some console log statements into the onOutputReceived event: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputEditorInput.ts#L57

I suspect that the output is cleared and no new output is appended (= race condition).

**Comment by Wosi** [comment] 2016-01-06 19:10
I'm not sure if I face the same problem. In the latest version the output of my test task stops sometimes. I run a batch file (using Windows 10) which compiles the test project and runs the resulting exe. While the compiler output is always displayed the test output doesn't appear in approximately 40%  of all runs. When I run the batch from command line everything works fine. It used to work fine in VSCode before the December update.

**Comment by dbaeumer** [comment] 2016-01-20 14:53
I tracked this down to the fact that the promise we use was 'resolved' to early hence loosing output sometimes (we resolved the promise on child process exit not on stream close). This is fixed with the next update.

**Closed by dbaeumer** 2016-01-20 14:53 UTC
Labels: bug, tasks

**Comment by dbaeumer** [comment] 2016-01-27 11:09
To verify use test case from comment https://github.com/Microsoft/vscode/issues/1622#issuecomment-168746059

**Comment by MadhukarMoogala** [comment] 2017-03-19 06:58
I'm not sure if it is fixed I can recreate the behavior at my machine, I'm not able get output when I compile c++ code in VSCODE on Linux.
OS: Fedora Release 23
CodeL 1.10.2

Pl. check the link for problem reproduction.

http://autode.sk/2mIa2Gl
