### ISSUE TITLE
Error loading renderer preloads

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122894] opened 2021-05-04 05:09 UTC
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Create a renderer extension through yeoman generator, e.g.

```
"contributes": {
    "notebookOutputRenderer": [
      {
        "id": "better-jupyter-errors",
        "entrypoint": "./out/client/index.js",
        "displayName": "Better Jupyter Errors",
        "mimeTypes": [
          "application/x.notebook.error-traceback"
        ]
      }
    ]
  },
```
2. Open a notebook which has `errors` (e.g., a Jupyter cell which has errors)

```
{
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "too many values to unpack (expected 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-8-b7fe370ef34b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msegmentTime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"./2021/activity_6695646668.gpx\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdata\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdata\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mtime\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'Time'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mellapsed_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'Time'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmax\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'Time'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-7-f839f8fa0bb3>\u001b[0m in \u001b[0;36msegmentTime\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0msegmentTime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m     \u001b[0mtrack\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdata2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mprocess_gpx_to_df\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m     \u001b[0mcolumns\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m'Longitude'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'Latitude'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'Altitude'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'Time'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'Speed'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'Cadence'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m     \u001b[0mgpx_df2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDataFrame\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: too many values to unpack (expected 2)"
     ]
    }
   ],
   "source": [
    "data = segmentTime(\"./2021/activity_6695646668.gpx\")\n",
    "df = data[1]\n",
    "name = data[0]\n",
    "time = df['Time'].min()\n",
    "ellapsed_time = df['Time'].max() - df['Time'].min()\n",
    "cadence = data[1]['Cadence'].mean()\n",
    "max_cad = df['Cadence'].max()\n",
    "print(time.astimezone(pacific).strftime(\"%m/%d/%Y, %H:%M:%S %Z\"), name)\n",
    "print('time: ', ellapsed_time)\n",
    "print('cadence', cadence, 'max', max_cad)\n",
    "# ns = 1e-9 # number of seconds in a nanosecond\n",
    "# print(datetime.utcfromtimestamp(data[1][0:1].Time.astype(int) * ns))\n",
    "print(df.Speed.mean() * 60 * 60 / 1000)"
   ]
  }
```
3. Open the notebook

```
Error loading preloads:
Unexpected 404 requesting file:///Users/penlv/code/personal/better-jupyter-errors/out/client/index.js: Not Found
```

**Comment by rebornix** [comment] 2021-05-04 05:10
Not sure what's the root cause but it seems we verified this work well 5 days ago? https://github.com/microsoft/vscode/issues/119899#issuecomment-829448970 cc @roblourens

**Comment by connor4312** [comment] 2021-05-04 05:17
I made this change today but it works fine for me/in OSS https://github.com/microsoft/vscode/commit/514871273b26b77cb7b68772d5eff059ed1cad82

Does out/client/index.js actually exist?

**Comment by roblourens** [comment] 2021-05-04 05:20
If there's an issue, it could be related to my service worker changes last week? I can look at it tomorrow.

**Comment by rebornix** [comment] 2021-05-04 05:42
> Does out/client/index.js actually exist?

yes, the same code works in VS Code stable, but didn't work locally in either Insiders or OSS.

**Comment by roblourens** [comment] 2021-05-04 17:46
We don't include the renderer extension roots in the webview's `localResourceRoots`, and the renderer is not in `rendererRootsCache`. I can't figure out why it worked in stable, even with iframe webviews enabled, I think we probably just weren't checking the roots then, is that right @mjbvz? 

We set `localResourceRoots` on the webview here which initially doesn't contain the renderer path

https://github.com/microsoft/vscode/blob/6a841dd8d5ac9100f663e5b59b242777a47bba78/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1171-L1171

then when the output from the renderer is loaded, we try to update it here

https://github.com/microsoft/vscode/blob/6a841dd8d5ac9100f663e5b59b242777a47bba78/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1646-L1646

but that doesn't do anything

https://github.com/microsoft/vscode/blob/19cda32aafccb88db45622e7ae9be90cb71c9744/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts#L376-L376

**Comment by mjbvz** [comment] 2021-05-04 19:58
I tested using a new rendered extension on insiders (85f8ebf1687661c45fe2633bdd7f640164a20cc2) and couldn't reproduce on MacOS

**Comment by mjbvz** [comment] 2021-05-04 20:21
I confirmed that the requested resource is not listed in the `localResourceRoots`:

![Screen Shot 2021-05-04 at 1 17 33 PM](https://user-images.githubusercontent.com/12821956/117064468-17ad9800-acdb-11eb-8e71-ed3768f06c86.png)

No clue yet why this was working before but the no op line definitely explains it. I confirmed that the notebook passes in the correct list of `localResourceRoots` but never does anything with the value

**Comment by mjbvz** [comment] 2021-05-04 20:36
I pushed a fix that implements the noop. This api only seems to be used from notebooks so I think it's a relatively safe fix 

@rebornix Do you remember why the no op was originally added? Maybe we were trying to avoid reloading the backlayer webview?

**Closed** 2021-05-05 01:53 UTC
Labels: candidate
