### ISSUE TITLE
[BUG] scroll by ↑ or ↓ in settings - delete lines and items

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#37171] opened 2017-10-30 18:44 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

https://youtu.be/xCSw2wDm_2k

Reproduces without extensions: **Yes**

**Comment by sandy081** [comment] 2017-11-01 08:28
Duplicate of #34707

**Closed by sandy081** 2017-11-01 08:28 UTC
Labels: editor, settings
