### ISSUE TITLE
I cannot install extensions in my VS code. XHR failed: I also cannot go to extentions tab from  my browser..

### ISSUE THREAD

**Issue by snwlms** [Microsoft/vscode#38180] opened 2017-11-13 05:22 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-11-13 05:51
Assuming this is a duplicate of https://github.com/Microsoft/vscode/issues/38179

**Closed by bpasero** 2017-11-13 05:51 UTC
Labels: extensions
