### ISSUE TITLE
Always detecting multiple definitions of symbol when peek (Alt+F12) or goto defintions (F12)

### ISSUE THREAD

**Issue by diaszacharias** [microsoft/vscode#83029] opened 2019-10-22 04:38 UTC
Issue Type: <b>Bug</b>

Defined functions as below,
file1.js
```js
exports.Fn1=async function(){

}
exports.Fn2=async function(){

}
exports.Fn3=async function(){

}
```

calling functions in another file
file2.js
```js
var file1=require("./file1");
file1.Fn2();
```
Actual: When trying to goto/peek definition of Fn2 from file2.js, VS code shows two definitions (Note we defined only one definition in the symbol).

Expected: When peek/goto symbols, VS Code should goto symbol directly if only one definitions exist. And display the number of definitions in case of multiple.

Before some release back (dont remember the exact version), this was working as expected.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2019-10-22 18:27
Duplicate of https://github.com/microsoft/TypeScript/issues/33520

**Closed by mjbvz** 2019-10-22 18:27 UTC
