### ISSUE TITLE
Integration test: Flaky "default column when opening a file" test

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49175] opened 2018-05-04 06:24 UTC
cc @bpasero

This test seems related to: https://github.com/Microsoft/vscode/issues/25801

**Platform:** macOS
**Estimated Failure Rate:** 10%

I will comment it out for now and leave this issue so we address it soon.

---

https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=86&_a=summary

```
2018-05-04T00:24:16.5127160Z [0m  1) window namespace tests issue #25801 - default column when opening a file:
2018-05-04T00:24:16.5140870Z 
2018-05-04T00:24:16.5168600Z       [31mAssertionError: wanted fileName:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hadavkni/viewColumn:1 but got fileName:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/yrpngwfxg/viewColumn:2. a:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/nflzdm, b:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/yrpngwfxg, c:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hadavkni[0m
2018-05-04T00:24:16.5198900Z       [32m+ expected[0m [31m- actual[0m
2018-05-04T00:24:16.5212190Z 
2018-05-04T00:24:16.5238440Z       [31m-false[0m
2018-05-04T00:24:16.5274500Z       [32m+true[0m
2018-05-04T00:24:16.5303010Z       [0m[90m
2018-05-04T00:24:16.5330500Z       at Object.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:137:10)
2018-05-04T00:24:16.5358810Z       at step (extensions/vscode-api-tests/out/singlefolder-tests/window.test.js:36:23)
2018-05-04T00:24:16.5387310Z       at Object.f [as next] (extensions/vscode-api-tests/out/singlefolder-tests/window.test.js:17:53)
2018-05-04T00:24:16.5418720Z       at fulfilled (extensions/vscode-api-tests/out/singlefolder-tests/window.test.js:8:58)
2018-05-04T00:24:16.5443790Z       at <anonymous>
2018-05-04T00:24:16.5468460Z [0m
```

**Comment by jrieken** [comment] 2018-05-04 11:15
dupe of  #49125, actually not a flaky test but a real problem

**Closed by jrieken** 2018-05-04 11:15 UTC
Labels: broken-build, engineering, integration-test

**Comment by joaomoreno** [comment] 2018-05-04 12:40
@jrieken  Very cool!
