### ISSUE TITLE
JS Region Folding

### ISSUE THREAD

**Issue by WeberPJ** [Microsoft/vscode#47658] opened 2018-04-11 13:08 UTC
Issue Type: <b>Bug</b>

With the latest update, region folding (//#region, //#endregion) has stopped working properly. Simple example:

<code>
//#region PlugIns

class DefaultPlugIn {
    constructor (name) {
        this.name = name;
        this.initialized = false;
    }
    get Name () { return this.name; }
    Initialize () {
        this.initialized = true;
    }
}

//#endregion
</code>

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|Memory (System)|7.92GB (3.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.2
php-intellisense|fel|2.3.1
php-pack|fel|1.0.1
beautify|Hoo|1.3.0
search-node-modules|jas|1.3.0
webpack|jer|2.0.2
svn-scm|joh|1.29.0
node-module-intellisense|lei|1.5.0
python|ms-|2018.3.1
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.3.0
debugger-for-edge|msj|0.4.1
vscode-code-outline|pat|0.1.0
vscode-docker|Pet|0.0.26
code-spell-checker|str|1.6.6
nodejs-extension-pack|wad|0.1.9
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by mjbvz** [comment] 2018-04-11 17:59
Duplicate of #44530 

Setting `"typescript.experimental.syntaxFolding": false` will disable the new syntax based folding and should fix this issue.

**Closed by mjbvz** 2018-04-11 17:59 UTC
Labels: new release

**Comment by WeberPJ** [comment] 2018-04-11 18:30
Thanks Matt - that has indeed fixed the issue for me!
