### ISSUE TITLE
tsserver keeps crashing with jsconfig.json

### ISSUE THREAD

**Issue by wichert** [microsoft/vscode#89069] opened 2020-01-22 07:37 UTC
Issue Type: <b>Bug</b>

I have a create-react-app based project with a jsconfig.json file in the root without any TypeScript code. When I open the project in VSCode tsserver keeps crashing. jsconfig.json is very simple:

```json
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

Removing the file stops tsserver from crashing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>tsserver.log</summary>

```
Info 0    [8:25:38.623] Starting TS Server
Info 1    [8:25:38.623] Version: 3.7.3
Info 2    [8:25:38.623] Arguments: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/36/bwbtnsvd7p76vwkhrfq99dsr0000gn/T/vscode-typescript501/4b909ae7721f7439f4e1/tscancellation-a75b5e4575c35dc8643b.tmp* --logVerbosity normal --logFile /Users/wichert/Library/Application Support/Code/logs/20200120T124638/exthost12/vscode.typescript-language-features/tsserver-log-ziimfp/tsserver.log --globalPlugins typescript-tslint-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations /Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/Users/wichert/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [8:25:38.623] Platform: darwin NodeVersion: 12 CaseSensitive: false
Info 4    [8:25:38.632] Host information vscode
Info 5    [8:25:38.637] Search path: /Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp
Info 6    [8:25:38.638] For info: /Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp/webrtc.js :: Config file name: /Users/wichert/Crypho/crypho.web/jsconfig.json
Info 7    [8:25:38.638] Opened configuration file /Users/wichert/Crypho/crypho.web/jsconfig.json
Info 8    [8:25:38.705] Config: /Users/wichert/Crypho/crypho.web/jsconfig.json : {
 "rootNames": [
  … long list if .js and .jsx files

 ],
 "options": {
  "allowJs": true,
  "maxNodeModuleJsDepth": 2,
  "allowSyntheticDefaultImports": true,
  "skipLibCheck": true,
  "noEmit": true,
  "baseUrl": "/Users/wichert/Crypho/crypho.web/src",
  "configFilePath": "/Users/wichert/Crypho/crypho.web/jsconfig.json"
 }
}
Info 9    [8:25:38.708] Loading global plugin typescript-tslint-plugin
Info 10   [8:25:38.708] Enabling plugin typescript-tslint-plugin from candidate paths: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..,/Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/Users/wichert/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.4
Info 11   [8:25:38.708] Loading typescript-tslint-plugin from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules)
Info 12   [8:25:38.722] Loading typescript-tslint-plugin from /Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3 (resolved to /Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3/node_modules)
Info 13   [8:25:38.744] [typescript-tslint-plugin] "Create"
Info 14   [8:25:38.744] [typescript-tslint-plugin] "ConfigurationManager: Found configured project: /Users/wichert/Crypho/crypho.web/jsconfig.json"
Info 15   [8:25:38.745] [typescript-tslint-plugin] "loaded"
Info 16   [8:25:38.745] Plugin validation succeded
Info 17   [8:25:38.745] Loading global plugin @vsintellicode/typescript-intellicode-plugin
Info 18   [8:25:38.745] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..,/Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/Users/wichert/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.4
Info 19   [8:25:38.745] Loading @vsintellicode/typescript-intellicode-plugin from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules)
Info 20   [8:25:38.746] Loading @vsintellicode/typescript-intellicode-plugin from /Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3 (resolved to /Users/wichert/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3/node_modules)
Info 21   [8:25:38.746] Loading @vsintellicode/typescript-intellicode-plugin from /Users/wichert/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.4 (resolved to /Users/wichert/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.4/node_modules)
Info 22   [8:25:38.752] IntelliCode plugin: starting configuration: {"name":"@vsintellicode/typescript-intellicode-plugin","global":true}
Info 23   [8:25:38.752] Plugin validation succeded
Info 24   [8:25:38.796] Starting updateGraphWorker: Project: /Users/wichert/Crypho/crypho.web/jsconfig.json
Err 25    [8:25:43.337] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp/webrtc.js","fileContent":"…...","projectRootPath":"/Users/wichert/Crypho/crypho.web","scriptKindName":"JS"}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at declareSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29212:22)
        at bindThisPropertyAssignment (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31366:25)
        at bindWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31020:29)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30902:13)
        at bindConditionalExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30247:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29586:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindConditionalExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30247:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29586:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindExpressionStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30106:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29568:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:94
        at bindEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29511:21)
        at bindEachFunctionsFirst (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29611:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17622:24)
        at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17752:21)
        at bindEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29519:16)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29614:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bindContainer (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29435:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30916:21)
        at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17622:24)
        at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17825:24)
        at bindEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29519:16)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29614:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindCallExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30357:21)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29596:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindExpressionStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30106:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29568:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:94
        at bindEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29511:21)
        at bindEachFunctionsFirst (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29605:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bindContainer (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29435:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30916:21)
        at bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29068:17)
        at Object.bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29005:9)
        at initializeTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:64384:20)
        at Object.createTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33622:9)
        at Object.getTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:95612:79)
        at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130645:21)
        at Proxy.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130727:13)
        at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135078:53)
        at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135021:42)
        at ConfiguredProject.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135869:63)
        at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137362:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138186:44)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
        at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
Info 26   [8:25:43.337] Structure before ensureProjectForOpenFiles:
Info 27   [8:25:43.338] Project '/Users/wichert/Crypho/crypho.web/jsconfig.json' (Configured) 0
Info 27   [8:25:43.338] 	Files (0)

Info 27   [8:25:43.338] -----------------------------------------------
Info 27   [8:25:43.338] Open files: 
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp/webrtc.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/husher.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/index.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/call-manager.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/webrtc.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/CallHandler.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 27   [8:25:43.338] Structure after ensureProjectForOpenFiles:
Info 28   [8:25:43.338] Project '/Users/wichert/Crypho/crypho.web/jsconfig.json' (Configured) 0
Info 28   [8:25:43.338] 	Files (0)

Info 28   [8:25:43.338] -----------------------------------------------
Info 28   [8:25:43.338] Open files: 
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp/webrtc.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/husher.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/index.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/call-manager.js ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/webrtc.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] 	FileName: /Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/CallHandler.jsx ProjectRootPath: /Users/wichert/Crypho/crypho.web
Info 28   [8:25:43.338] got projects updated in background, updating diagnostics for /Users/wichert/Crypho/crypho.web/src/crypho.core/xmpp/webrtc.js,/Users/wichert/Crypho/crypho.web/src/crypho.core/husher.js,/Users/wichert/Crypho/crypho.web/src/index.jsx,/Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/call-manager.js,/Users/wichert/Crypho/crypho.web/src/webrtc.jsx,/Users/wichert/Crypho/crypho.web/src/crypho.core/rtc/CallHandler.jsx
```
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 8, 6|
|Memory (System)|32.00GB (10.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cucumberautocomplete|ale|2.14.1
swagger-viewer|Arj|2.2.2
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
xml|Dot|2.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.18.0
gc-excelviewer|Gra|2.1.32
jsonnet|hep|0.1.0
plantuml|jeb|2.13.6
restructuredtext|lex|116.0.0
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
vscode-docker|ms-|0.9.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.1.58038
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
Go|ms-|0.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.5
vscode-jest|Ort|3.1.1
openapi-designer|phi|0.3.0
vscode-yaml|red|0.6.1
sass-indented|rob|1.5.1
rust|rus|0.7.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.4
material-theme|zhu|3.2.1

</details>

**Comment by wichert** [comment] 2020-01-22 07:38
As far as I can see this is not covered by existing issues.

**Comment by Nxt3** [comment] 2020-01-22 19:51
The same happens to me when I provide an override for `typescript.tsdk`.

Here are the logs:

```
[Info  - 19:39:40.103] <main> Forking...
[Info  - 19:39:40.107] <main> Starting...
[Error  - 19:40:24.573] ReaderError
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218987)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 19:40:24.576] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:217663)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218730)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 19:40:24.583] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:217663)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218730)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-01-22 20:46
@wichert  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

@Nxt3 Open a separate issue. That call stack suggests a different problem

**Comment by wichert** [comment] 2020-01-23 08:23
@mjbvz The insiders build (version 1.42.0-insider at commit `c4d53a19df8799f5d49a4f49a6900c499e6fa27c`) does not have this problem.

**Comment by mjbvz** [comment] 2020-01-23 18:34
Duplicate of https://github.com/microsoft/TypeScript/issues/35630

**Closed by mjbvz** 2020-01-23 18:34 UTC
Labels: needs more info, typescript
