### ISSUE TITLE
Feature request: expose date information as available variable(s) when creating snippets.

### ISSUE THREAD

**Issue by davidpaulhunt** [Microsoft/vscode#41631] opened 2018-01-15 17:40 UTC
Edit: Sorry if this is a terrible issue...

The current list of variables available when writing a snippet can be found [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables).

Existing variables expose great contextual information - such as current file, directory, line number, word, etc. Development happens so fast that information can become outdated, so knowing when some custom snippets were inserted could be useful. For example, when creating files or adding comments.

My current use case is a snippet that inserts copyright headers.

The key binding `ctrl+cmd_c` inserts the header:
```ts
/**
 * MyClass.ts
 * MyProjectName
 *
 * Created by David Hunt.
 * Copyright © Our Company Name, LLC. All rights reserved.
 */
```

It would help to include the date:
```ts
/**
 ...
 * Created by David Hunt on 1/15/18.
 ...
```
and could also apply to updates or comments:
```ts
/**
 * See stackoverflow issue: someurl.
 * Added 1/15/18.
 */
```

Doing so could mean a simple variable like `TM_CURRENT_DATE`, but that may not work for non-US users who's date format is different i/e _not_ month/day/year. Perhaps exposing the variables separately such as `TM_CURRENT_YEAR`, etc or localization can help?

I'd like to know if there is any interest in this. I know an extension could do this but it seems like overkill, but that could depend on potential use cases.

Thanks for any feedback.

**Comment by jrieken** [comment] 2018-01-15 18:01
Hm, this is dupe of many requests we have gotten around this but made a valid point. Adding variables for year, month, day and hour, minute, second makes sense. That will allow anyone to compose it's own date. So, yeah feel free to drop a PR

**Closed** 2018-01-17 19:38 UTC
Labels: help wanted, snippets

**Comment by davidpaulhunt** [comment] 2018-01-17 19:52
@jrieken Good to hear.

@usernamehw Thanks for the PR!
