### ISSUE TITLE
Keyboard Input not working in VSCODE

### ISSUE THREAD

**Issue by Pianist038801** [Microsoft/vscode#37695] opened 2017-11-06 07:10 UTC
VSCode is my favorite text editor. Nowadays I realized that keyboard input is not working on editor for several times.
Now I am stuck again.
In terminal window of VSCode, keyboard works.
But on edit screen, when I try to type sth, never works.

**Comment by xLobito** [comment] 2017-11-06 13:58
I have the same behavior with a stupid high RAM usage (Nearly 3 GB of use in idle state). It was working fine and out of nowhere this issue came to appear. 

VSCode Version: 1.17.2

**Comment by alexandrudima** [comment] 2017-11-06 15:45
Duplicate of #37003 which itself is a duplicate of #36575

TL;DR: please try using the insiders build or disabling some of your extensions. A fix will make it to the stable channel in the upcoming week.

**Closed** 2017-11-06 15:46 UTC
Labels: duplicate, editor, editor-input
