### ISSUE TITLE
[TypeScript] syntax highlighting when using Enum

### ISSUE THREAD

**Issue by Robouste** [microsoft/vscode#82839] opened 2019-10-18 12:39 UTC
Currently, Enums do not have a different color when used in code. (tested with all default theme, only monokai dimmed make a differentiation) 

In the example below, it becomes difficult to read.

![image](https://user-images.githubusercontent.com/5463032/67094568-699fd300-f1b4-11e9-9386-e15ea1f1e1a3.png)

Would be great to have this implemented.

And also for classes when using static methods:

![image](https://user-images.githubusercontent.com/5463032/67094875-f34fa080-f1b4-11e9-89f5-0369036670ef.png)

**Comment by mjbvz** [comment] 2019-10-18 18:32
Duplicate of #585

It's not possible to tell that `NumberFilterType` is an enum without support for semantic highlighting

**Closed by mjbvz** 2019-10-18 18:32 UTC
