### ISSUE TITLE
Visual Studio Live Share was unable to download needed dependencies to finish install

### ISSUE THREAD

**Issue by Kathy145** [Microsoft/vscode#45076] opened 2018-03-05 18:11 UTC
### Issue Type
Bug

### Description

I tried to install VS Live Share and though there are no dependencies the error message indicated that neeeded ones did not download.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|Load (avg)|2, 17, 26|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_49164|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.15
erb|Cra|0.0.1
solargraph|cas|0.12.0
vsliveshare|ms-|0.2.163
code-spell-checker|str|1.6.5

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by kieferrm** [comment] 2018-03-06 01:28
@Kathy145 After the extension is installed it installs further dependencies. It seems that's what failed. 

This might be a duplicate of your issue: https://github.com/MicrosoftDocs/live-share/issues/124. If not, pls file an issue in https://github.com/MicrosoftDocs/live-share.

**Closed by kieferrm** 2018-03-06 01:28 UTC
