### ISSUE TITLE
Toggle individual extensions on and off through Command Pallete and/or hotkey.

### ISSUE THREAD

**Issue by MichaelNecio** [Microsoft/vscode#22810] opened 2017-03-17 21:39 UTC
Currently you can disable all extensions through the Command Pallete, and you can disable individual extensions using the side bar, but it would be nice to be able to quickly disable/enable and extension via the Command Pallete. And this would be for extensions you do want to use with the current project and/or file type, but not all the time.

My use case for this would be toggling vim key bindings on and off, but I'm sure there are more.

**Comment by sandy081** [comment] 2018-09-24 16:47
Duplicate of #21099

**Closed** 2018-09-24 16:47 UTC
Labels: *duplicate, extensions, feature-request
