### ISSUE TITLE
Add MathJax support in Markdown Preview

### ISSUE THREAD

**Issue by raztd** [Microsoft/vscode#13657] opened 2016-10-13 08:50 UTC
https://github.com/mathjax/MathJax

Right now the Markdown Preview  does not interpret the MJ syntax correctly.
![mdpreview](https://cloud.githubusercontent.com/assets/6805609/19342491/bd54da14-913a-11e6-9ed5-170c5b44ba5a.jpg)

**Comment by mjbvz** [comment] 2016-10-13 22:46
Closing as duplicate of #6529

**Closed by mjbvz** 2016-10-13 22:46 UTC
Labels: duplicate, markdown

**Comment by goessner** [comment] 2016-12-14 22:33
see 

[Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath)
