### ISSUE TITLE
Crashes when move mouse to File

### ISSUE THREAD

**Issue by poskazz** [microsoft/vscode#230916] opened 2024-10-09 12:55 UTC
Type: <b>Bug</b>

subj, 
Version: 1.95.0-insider
Commit: a016ec9b66ffdd3ff0f831768b8e75be008a54e4
Date: 2024-10-09T05:04:08.601Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Linux x64 6.11.0-102007-tuxedo

VS Code version: Code - Insiders 1.95.0-insider (a016ec9b66ffdd3ff0f831768b8e75be008a54e4, 2024-10-09T05:04:08.601Z)
OS version: Linux x64 6.11.0-102007-tuxedo
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 3731)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|62.54GB (53.25GB free)|
|Process Argv|--crash-reporter-id 2d5a2def-eba6-49a4-a30a-33e64d5ccc8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
continue|Con|0.9.215
python-environment-manager|don|1.2.4
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.11.2024092501
python|ms-|2024.17.2024100801
vscode-pylance|ms-|2024.10.1
autodocstring|njp|0.6.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by IllusionMH** [comment] 2024-10-09 19:02
Looks like duplicate of #230604

**Closed** 2024-10-09 23:29 UTC
Labels: info-needed
