### ISSUE TITLE
Drag and drop code between tabs

### ISSUE THREAD

**Issue by amatosmstn** [Microsoft/vscode#44844] opened 2018-03-01 15:29 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

I have two opened tabs in a splitted editor. I have tried to drag a text from one tab to another and it does not allow it. 
Is there any way to do this already?

**Comment by bpasero** [comment] 2018-03-01 15:39
@amatosmstn to be clear, you want to drag and drop text of the editor, not the entire editor?

**Comment by amatosmstn** [comment] 2018-03-01 19:14
Yes.
I want to have two tabs, select a text from one and drag it to the other.
This drag function already exists; but within the same tab. I'm interested in this functionality to copy the text by dragging it while I press the Ctrl key.

**Comment by rebornix** [comment] 2018-09-21 18:55
Duplicate of https://github.com/Microsoft/vscode/issues/32387

**Closed** 2018-09-21 18:55 UTC
Labels: *duplicate, editor-drag-and-drop, feature-request
