### ISSUE TITLE
Add enum option to show whitespaces inside selection only

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#16392] opened 2016-12-02 15:57 UTC
So far `editor.renderWhitespace` accepts the following properties:

- all
- boundary
- none

I suggest we add a new option `selection` to only show whitespaces inside the current selected block of text. This can help conserving a readable code while getting insights when selecting a block of code.

**Comment by mjbvz** [comment] 2017-11-09 00:48
Duplicate of #1477

**Closed by mjbvz** 2017-11-09 00:48 UTC
Labels: duplicate, editor, editor-core, feature-request
