### ISSUE TITLE
VS Code Window in "Full screen mode" / Windows 10 is oversized

### ISSUE THREAD

**Issue by netsrotr** [microsoft/vscode#106918] opened 2020-09-17 07:11 UTC
Issue Type: <b>Bug</b>

Windows 10, newest version / 2004. I run VS Code on a second monitor in full screen mode (Samsung Display, connected to Laptop via HDMI). The windows desktop is configured to "extend" the Desktop (Laptop is Nr. 1, Monitor Nr. 2 and on the rightof the Laptop).
Now I consider VS Code Window is somewhat oversized, means: it shows a small portion of the Window Chrome also on the Laptop display (at the right side) while VSC is run fullscreen on the external second monitor (yellow marker on the right):
![image](https://user-images.githubusercontent.com/5443937/93432327-a8a73e80-f8c5-11ea-906a-b723b42b3c42.png)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-footnotes|bie|0.0.7
vscode-postgres|cko|1.1.11
FreeMarker|dco|0.0.9
svn-scm|joh|2.12.4
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.44.5
fluent-syntax-highlighting|pau|0.0.1
java|red|0.67.0
svn-scm-ext|spm|1.2.1
latex-support|tor|3.2.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by IllusionMH** [comment] 2020-09-17 08:10
/needsMoreInfo

Could you check if it's reproducible in Insiders version for you https://code.visualstudio.com/insiders/ ?

Most likely it's duplicate of #85310 that was recently fixed in Insiders builds.

**Comment by netsrotr** [comment] 2020-09-17 08:22
Just tested with

Version: 1.50.0-insider (user setup)
Commit: d1f267742169584db010716d92addf50d4cd8139
Date: 2020-09-17T07:24:47.609Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19041

Looks fine to me: no issue with insiders version.

**Comment by IllusionMH** [comment] 2020-09-17 08:32
/duplicate of #85310

Should be in stable with 1.50 release in early October

**Closed** 2020-09-17 08:33 UTC
Labels: *duplicate, needs more info
