### ISSUE TITLE
Cannot download remote file when simpleDialog is enabled

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#89815] opened 2020-01-31 19:14 UTC
Issue Type: <b>Bug</b>

1. Connect to a remote SSH server and open a folder
2. Set `files.simpleDialog.enable` to true
3. Right click a file in the explorer and choose download

The file dialog that's shown shows the remote machine's file tree instead of the local machine's. When `simpleDialog` is false, the native file dialog is shown for the local machine.

VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T13:51:59.883Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1028-azure

**Comment by isidorn** [comment] 2020-02-03 13:20
This seems to be the issue with the simpleDialog. The simpleDialog should show the local machine file tree for local uri.
Here's a code pointer how I am using the `fileDialogService`
https://github.com/microsoft/vscode/blob/547cf4e81f1262042915dcf7494ab03b5030b15e/src/vs/workbench/contrib/files/browser/fileActions.ts#L1033

Also assigning to you @alexr00 since you own the `simpleDialog`

**Comment by alexr00** [comment] 2020-02-03 14:18
@isidorn it looks the problem is here
https://github.com/microsoft/vscode/blob/a99b0779172d122c85b208e47134f3530bee1cd3/src/vs/workbench/contrib/files/browser/fileActions.ts#L1028

The defaultUri that is being passed to the file dialog is a remote URI. If you pass in a non-remote URI with a file scheme then it should work.

**Comment by isidorn** [comment] 2020-02-05 14:54
@alexr00 thanks for looking into this. 
@RMacfarlane I have pushed a potential fix for this. Once the insiders is again live off master can you try it out? Thanks!

**Closed** 2020-02-05 14:53 UTC
Labels: under-discussion
