### ISSUE TITLE
case of colorization error with inline string template

### ISSUE THREAD

**Issue by nippur72** [Microsoft/vscode#7922] opened 2016-06-21 10:24 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 7

The following code is not colorized properly in VSCODE (.ts file)
```
const funcText0 = true ? `` : `${funcName}`;
```
Screenshot:
![screen1](https://cloud.githubusercontent.com/assets/2598443/16226191/875b79b6-37aa-11e6-87b1-13f7d6eaedbb.png)
(but is correct in Visual Studio 2015).

**Comment by aeschli** [comment] 2016-06-23 06:55
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-06-23 06:55 UTC
Labels: typescript
