### ISSUE TITLE
Add a macro symbol kind for languages that have macros

### ISSUE THREAD

**Issue by nox** [Microsoft/vscode#17983] opened 2017-01-01 12:39 UTC
RustyCode advertises macros as simple functions because there is no specific symbol kind for macros.

https://github.com/saviorisdead/RustyCode/blob/dae6ac740e2b52466f8883da6a716faa8455d6de/src/rustSymbols.ts#L13

**Comment by jrieken** [comment] 2017-01-27 10:17
@nox Is that for completions or symbol search or both?

**Comment by nox** [comment] 2017-01-27 11:22
I filed this for symbol search, but I guess it could be used for context in completions too?

**Comment by nox** [comment] 2017-03-04 12:04
Any news on this?

**Comment by nox** [comment] 2017-03-25 12:08
Ping?

**Comment by jrieken** [comment] 2017-04-11 08:17
closing as dupe of https://github.com/Microsoft/vscode/issues/2628

**Closed by jrieken** 2017-04-11 08:17 UTC
Labels: api, feature-request
