### ISSUE TITLE
gitignored items not excluded from search

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#25730] opened 2017-05-01 13:31 UTC
A possible bug in _use .gitignore to ignore search inside files and folders_ #78.

I have this workspace open in VSCode 1.11:

| Path            | Contents |
| --------------- | -------- |
| /.gitignore     | a.txt    |
| /a.txt          | aaa      |
| /dir/.gitignore | b.txt    |
| /dir/b.txt      | aaa      |

Search for "aaa" with "Use Ignore Files" enabled yields this:

![image](https://cloud.githubusercontent.com/assets/101152/25580641/c4192f68-2e82-11e7-9546-2f348f144c8c.png)

These two search results shouldn't show up, should they? I've tried this on a workspace where Git repo actually exists (`.git` present) and where it doesn't with the same result.

Repro project: [gitignoresearch.zip](https://github.com/Microsoft/vscode/files/967908/gitignoresearch.zip)

**Comment by roblourens** [comment] 2017-05-24 23:39
Are the files open? They will still be searched if they are open.

**Comment by borekb** [comment] 2017-05-25 07:08
You're right, when I open `a.txt` but not `b.txt`, only `a.txt` shows up in the search results:

![image](https://cloud.githubusercontent.com/assets/101152/26439718/956e5a76-4129-11e7-80b2-4ed1f79bc9db.png)

Still, this feels like a bug / unexpected behavior to me. The search panel should follow gitignore rules if it has a toggle for it.

**Comment by roblourens** [comment] 2017-11-21 22:59
/duplicate of https://github.com/Microsoft/vscode/issues/31819

**Closed by roblourens** 2017-11-21 22:59 UTC
Labels: feature-request, search
