### ISSUE TITLE
Disabling some plugins doesn't work on 1.33.0

### ISSUE THREAD

**Issue by szhu** [Microsoft/vscode#71769] opened 2019-04-05 07:26 UTC
Issue Type: <b>Bug</b>

Some disabled plugins are no longer disabled after 1.33.0, even though they still show up in the UI as disabled. This is one example:

1. Install the Sourcegraph JS/TS extension: https://marketplace.visualstudio.com/items?itemName=sourcegraph.javascript-typescript
2. Disable the extension.
3. Reload the editor.
4. Hover over any JS/TS function. 

Expected: One definition shows up in the hovercard, provided by the built-in JS/TS extension.

Actual: Two sets of defintions show up. I'm pretty sure one of them is provided by the Sourcegraph extension, since it no longer appears after uninstalling the extension.

![image](https://user-images.githubusercontent.com/1570168/55611076-51e18f80-5739-11e9-82cb-631a4881e429.png)

This happens for some extensions but not for others. I'm still trying to figure out what the rule is.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 4|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv|-psn_0_6305283|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
fish|Ted|0.0.4
haml-lint|aki|0.0.3
Bookmarks|ale|10.4.2
copy-relative-path|ale|0.0.2
cucumberautocomplete|ale|2.13.1
deno-vscode|ame|0.0.4
unique-lines|bib|1.0.0
vscode-gemfile|bun|0.0.2
indented-block-highlighting|byi|1.0.7
box-comment|can|0.2.0
path-intellisense|chr|1.4.2
ruby-copy-reference|cie|0.1.4
bracket-pair-colorizer-2|Coe|0.0.28
dakara-foldplus|dak|1.3.2
vscode-markdownlint|Dav|0.25.1
vscode-eslint|dba|1.8.2
chmod|dle|1.1.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
RunOnSave|eme|0.0.18
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
vscode-language-todo|fir|1.2.3
vscode-pull-request-github|Git|0.6.0
bust-a-gem|gur|0.1.7
vscode-stylint|Haa|0.1.2
theme-macos-classic|hua|1.1.1
applescript|idl|0.14.2
diff-tool|jin|0.0.1
join-comment-aware|joh|0.0.3
markdown-table-formatter|jos|0.2.3
haml|kar|1.1.0
swift|Kas|0.0.3
vscode-sshfs|Kel|1.14.6
auto-comment-blocks|kev|1.0.1
fish-ide|lun|0.4.0
dotenv|mik|1.0.1
ruby-rubocop|mis|0.7.1
react-javascript-to-typescript-transform-vscode|moh|1.10.0
mssql|ms-|1.5.0
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.18
debugger-for-chrome|msj|4.11.3
diff|raf|0.0.1
ruby|reb|0.22.3
vscode-yaml|red|0.4.0
vscode-paste-and-indent|Rub|0.0.8
annotator|ryu|0.11.0
vscode-quick-open-related-files|sch|1.0.0
vscode-sql-beautify|sen|0.0.4
vscode-table-formatter|shu|1.2.1
slim|sia|0.1.2
fish-vscode|sky|0.2.1
vscode-fileutils|sle|2.13.5
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
language-stylus|sys|1.11.0
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.6.0
sort-lines|Tyr|1.8.0
vscode-wakatime|Wak|1.2.13
markdown-all-in-one|yzh|2.2.0
propertylist|zho|0.0.2

(2 theme extensions excluded)

</details>

**Comment by szhu** [comment] 2019-04-05 07:28
Sorry, this is a duplicate of #71752. I tried searching for this issue but couldn't find it. I was able to find the dupe really quickly by looking at the "new release" tag though.

**Comment by sandy081** [comment] 2019-04-08 08:24
Duplicate of #71752

**Closed** 2019-04-08 08:25 UTC
Labels: *duplicate, new release
