### ISSUE TITLE
Ability to use regex or do operations in User Snippets

### ISSUE THREAD

**Issue by SuhairZain** [Microsoft/vscode#18256] opened 2017-01-07 17:33 UTC
Hi,
This is not a bug, but rather a feature request. I saw [here](https://code.visualstudio.com/Docs/customization/userdefinedsnippets#_variables) that it's possible to use the filename within the snippets but what I need is to only use a part of it. For instance, I'd like to use the filename ResponsiveImage.jsx to automatically name the React Component as ResponsiveImage. Is this possible as of now or is it planned in any future releases?

**Comment by jrieken** [comment] 2017-01-09 09:07
closing this as dupe of #17395. Tho it is unsure when/if we tackle that because we already support the more general and powerful way of returning snippets from a completion provider. That has the freedom and can generate snippets dynamically

**Closed** 2017-01-09 09:07 UTC
Labels: duplicate

**Comment by SuhairZain** [comment] 2017-01-09 10:37
@jrieken 
I looked through open and closed issues including the linked one, but I didn't find any that was related to what I wanted. After reading the linked issue three times, I realized that that is exactly what I wanted. I'm sorry about creating a duplicate issue.

About returning snippets from a completion provider, I didn't get what you said. Could you kindly point me to the relevant docs? It'd be a great help.

**Comment by jrieken** [comment] 2017-01-09 11:12
Have a look at this small sample: https://github.com/Microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts#L15. It explains how to be a completion provider in general, then you create [`CompletionItems`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2378) with a `SnippetString`
