### ISSUE TITLE
dragging files in file explorer causes vscode to freeze

### ISSUE THREAD

**Issue by varunjayaraman** [Microsoft/vscode#26265] opened 2017-05-09 05:16 UTC
- VSCode Version: 1.12.1
- OS Version: 10.12.3

Steps to Reproduce:

1. Try dragging a file in the file explorer into a different folder
2. Vscode will freeze and you have to manually terminate the process

For context, i'm using a typescript project.

**Comment by egamma** [comment] 2017-05-09 07:05
@varunjayaraman cannot reproduce the issue given the information provided, can you add an animated gif that illustrates the problem.

**Comment by egamma** [comment] 2017-05-10 08:54
@varunjayaraman can you check whether this is a duplicate of #22114

**Comment by egamma** [comment] 2017-05-10 17:52
Without additional information we cannot act on this issue, please reopen this issue when you have additional insights.

**Comment by varunjayaraman** [comment] 2017-05-27 19:09
@egamma i can confirm the problem occurs when I open vscode from tmux. I think it's related to issue #26261 so maybe we could track both there?

**Comment by egamma** [comment] 2017-05-28 16:06
while related, this could be another issue, so I'll reopen this issue.

**Comment by bpasero** [comment] 2017-05-29 04:36
Should be ok after setting `set-option -g default-command "reattach-to-user-namespace -l zsh"`

**Closed by bpasero** 2017-05-29 04:36 UTC
