### ISSUE TITLE
Fonts suddenly became too big

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode#228925] opened 2024-09-18 08:57 UTC
Type: <b>Bug</b>

I have a very weird problem with menu and popup menu fonts - they are too big.

I've looked through all the settings with "font" in name, there is no one with size >= 14, and no one corresponding to "menu" or "submenu" or something like that. 

Neither googling, nor asking chatgpt help to find out how to decrease them. Please, help to find the setting name. 

![image](https://github.com/user-attachments/assets/78746414-75ec-4864-8da8-90ddb81f8603)

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-40-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 155H (22 x 4292)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.04GB (15.42GB free)|
|Process Argv|--crash-reporter-id 991ee029-5174-4671-aed6-18d04cc86596|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.5.0
project-manager|ale|12.8.0
zoomer|ant|0.3.1
vscode-django|bat|1.15.0
docs-view|bie|0.1.0
path-intellisense|chr|2.9.0
gitignore|cod|0.9.0
databricks|dat|2.4.2
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.5.1
code-runner|for|0.12.2
vscode-edit-csv|jan|0.10.0
vscode-icon-theme|jtl|1.6.6
vsc-python-indent|Kev|1.18.0
python-extension-pack|Leo|3.0.0
vscode-checkpoints|mic|1.3.3
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.5
vscodeintellicode-csharp|ms-|2.1.11
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
pylint|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
datawrangler|ms-|1.8.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vs-keybindings|ms-|0.2.1
one-dark-theme|msk|1.14.2
autodocstring|njp|0.6.1
git-file-history|pom|1.0.1
inline-sql-syntax|quf|2.16.0
vscode-yaml|red|1.15.0
gpack|Sey|2.0.0
markdown-preview-enhanced|shd|0.8.14
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-conventional-commits|viv|1.26.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.3
vscode-open-in-github|ziy|1.3.6

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564
iacca1:31138162
cc771715:31140165

```

</details>

**Comment by rzhao271** [comment] 2024-09-18 18:04
The only setting I know that could increase the font size of those menus is `window.zoomLevel`. I notice you also have the zoomer extension installed and wonder whether that could contribute to the issue.

If changing the setting or disabling the extension does not resolve the issue, let me know in which version of VS Code the issue started, and whether reverting to a previous version works.

**Comment by ibobak** [comment] 2024-09-18 20:05
I have "window.zoomLevel": 0,  and I've tried to set  -0.5, 1,  0.5 and other values, and it affects only the fonts which are inside (editor, explorer, etc.) but it doesn't affect the fonts of menus.   Besides, I've disabled zoomer, restarted VS Code - nothing changed.

**Comment by ibobak** [comment] 2024-09-18 20:07
This started from 1.91 or 1.92. Actually, I can set up a clean instance on VM (without account sync) and try to move the settings one by one to see which setting influence.  But this is troublesome a little bit.  Do you know other ways?

**Comment by ibobak** [comment] 2024-09-18 20:09
my settings
[settings.json.txt](https://github.com/user-attachments/files/17049822/settings.json.txt)

**Comment by rzhao271** [comment] 2024-09-19 00:54
I realized this issue is a duplicate of https://github.com/microsoft/vscode/issues/224515
See workaround at https://github.com/microsoft/vscode/issues/224515#issuecomment-2267264540

**Closed by rzhao271** 2024-09-19 00:54 UTC
Labels: info-needed
