### ISSUE TITLE
showTextDocument() should allow to set { pinned: false }

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#20850] opened 2017-02-18 06:52 UTC
- VSCode Version: `1.10.0-insider` 50f8848e44029ffabf0727de49cd18ae4069b4fe
- OS Version: macOS Sierra `10.12.3 (16D32)`

The `vscode.open` command seems to be the only way to open a document in a "preview" tab, but currently it steals focus. While `window.showTextDocument` doesn't have an option to show in a "preview" tab (might be a nice option as well), but does support `preserveFocus?: boolean`.

So right now, from an extension I can't seem to open a document in a preview tab, but also not steal focus.

As an example, I was attempting to open documents in a preview tab while using the `onDidSelectItem` event from `showQuickPick()`.

**Comment by bpasero** [comment] 2017-02-19 08:53
@eamodio why can you not use `showTextDocument(document: TextDocument, column?: ViewColumn, preserveFocus?: boolean)` ?

**Comment by eamodio** [comment] 2017-02-19 16:27
@bpasero `showTextDocument` doesn't open in a preview tab like `vscode.open` does

**Comment by bpasero** [comment] 2017-02-19 17:14
We should provide all these options from `showTextDocument` and not overload the already abused `vscode.open` command.

**Comment by eamodio** [comment] 2017-02-19 17:15
That definitely works for me! :)

**Comment by jrieken** [comment] 2017-02-20 08:22
dupe of #10568

**Closed by jrieken** 2017-02-20 08:22 UTC
Labels: api
