### ISSUE TITLE
Redo drop does not work for single file

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111639] opened 2020-12-01 15:39 UTC
Testing #111015

Ubuntu

- In the Ubuntu file explorer, select a file a drop in the VSCode explorer
- from the window menu, run `Edit > Undo`. Copy is undone :heavy_check_mark: 
- from the window menu, run `Edit > Redo`. Nothing happens

Interestingly, dropping 2 files and undo - redo works

**Comment by isidorn** [comment] 2020-12-02 13:02
For me I see something differently. In the last step the Redo works, however the file is brough back empty.

This is due to the fact that we pass `true` here as the `_undoesCreateOperation` https://github.com/microsoft/vscode/blob/f4187f22026ff6537f2ca8132ad3209fceb5071f/src/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.ts#L97

I have verified that passing `false` here actually fixes the issue.
Though I know @jrieken introduced this flag for a reason. Thus also assigning this issue to him

**Comment by jrieken** [comment] 2020-12-02 14:56
@isidorn Using `false` should be OK for that case. Basically that is there to know if delete in undoing a create operation. Create should be understood as "create empty file", not as copy or as re-create after delete.

**Comment by isidorn** [comment] 2020-12-02 15:29
@jrieken thanks. Pushed that fix then
@aeschli I understand I did not fix 100% the issue you were seeing, but a similar issue. However still closing this, and you can try with latest out of source and let me know if you still see something strange. I believe your original issue was also connected to the focus and is basically a dupe of https://github.com/microsoft/vscode/issues/111640

**Closed** 2020-12-02 15:28 UTC
Labels: bug, file-explorer

**Comment by jrieken** [comment] 2020-12-02 15:34
Thanks @isidorn. This is why all of this is so complicated: https://github.com/microsoft/vscode/issues/107379. The gist is that undo of create should only restore contents when create was invoked with contents, not if the context came later. Using your changes I have re-verified #107379 and things are happy

**Comment by isidorn** [comment] 2020-12-02 15:36
Thanks for re-verifiying.

**Comment by aeschli** [comment] 2020-12-04 14:49
Verified that setting the focus on the explorer solves the issue.
