### ISSUE TITLE
Search action icons always visible

### ISSUE THREAD

**Issue by ts-web** [microsoft/vscode#212518] opened 2024-05-11 20:21 UTC
Type: <b>Feature Request</b>

This one got me for a good while: "why don't my search results have the 'X' button?" I searched through the Settings, googled for answers, and finally found this one: https://github.com/microsoft/vscode/issues/87172.

It turns out that the actions are there, but if the search results are long enough, it pushes the action icons out of view.

https://github.com/microsoft/vscode/assets/1311744/50863753-d318-4272-8aa1-17eb0e064d39

That makes sense now, and I understand that in UI layouts you can't have both horiz scrolling _and_ horiz overflow (and horiz scrolling is great), but perhaps there is a solution:

Simpy make the action buttons floating at the right. They would obscure the line text,  but that can be mitigated with some padding-right and horiz scrolling.

Does it seem worth investigating whether we can make the action buttons always visible?

thx

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 5.15.0-105-generic
Modes:

**Comment by roblourens** [comment] 2024-05-13 18:42
This does only happen with horizontal scrolling enabled, but supporting floating buttons in that mode would be cool

**Comment by andreamah** [comment] 2024-05-27 23:03
This seems to be a duplicate of https://github.com/microsoft/vscode/issues/45717. Seems that we would need to take an extra look at horizontal scrolling in the search view to make it more polished.

**Closed by andreamah** 2024-05-27 23:03 UTC
