### ISSUE TITLE
The terminal process command "C:\Windows\system32\cmd.exe" failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by joseph1125** [Microsoft/vscode#20858] opened 2017-02-18 12:31 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10 1607 64bit

Steps to Reproduce:

1. Press Control + `
2. The terminal process command "C:\Windows\system32\cmd.exe" failed to launch (exit code: 1)

I'm aware that non-ascii characters in path may probably produce this issue, there is NO non-ascii characters in the path

This problem starts to occur once updated to version 1.9

Won't work after reinstalling VS Code

**Comment by joseph1125** [comment] 2017-02-18 12:38
It seems that the whole integrated terminal stopped working as I try to use Git Bash but still no luck.

**Comment by joseph1125** [comment] 2017-02-18 13:08
This problem DOES NOT occur in the insider build v1.10 .

**Comment by mrmlnc** [comment] 2017-02-18 13:31
Duplicate of #20100.

**Comment by Tyriar** [comment] 2017-02-21 19:11
Sounds like it will be fixed in the next build if it works in 1.10.

**Closed by Tyriar** 2017-02-21 19:11 UTC
