### ISSUE TITLE
SCM: Outgoing section didn't appear after fetch and merge

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#203863] opened 2024-01-31 07:50 UTC
Type: <b>Bug</b>

This morning I updated Insiders and all extensions, restarted it, then followed my standard procedure for updating my fork of microsoft/vscode which is:

1. Be on main locally.
2. Fetch From All Remotes
3. Merge from upstream/main

Normally when this completes the big blue button shows Sync Changes NN and below it an Outgoing section has a main header with a badge reporting NN.

This morning I saw the Sync Changes 74 but there was no Outgoing section.

![image](https://github.com/microsoft/vscode/assets/6726799/a01961ee-f276-44b1-81ca-7d596b69db10)

Running the Reload Window command made it appear.

![image](https://github.com/microsoft/vscode/assets/6726799/9927e003-9a69-4407-8f69-deab7ca56aca)

VS Code version: Code - Insiders 1.86.0-insider (8c08612b658a37f96892f8ed5a9c6e7a6667847d, 2024-01-30T21:44:10.295Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (0.19GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --enable-proposed-api georgejames.intersystems-serverdiff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
tsl-problem-matcher|amo|0.6.2
open-in-github-button|ant|0.1.1
vscode-opennewinstance|chr|0.0.12
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.1.0
vscode-open-in-github|fab|1.3.0
codespex|geo|0.1.4
intersystems-dxjetpack|geo|0.1.2
searchable-debug-console|geo|0.0.1
thefoldingstuff|geo|0.2.1
codespaces|Git|1.16.9
copilot|Git|1.156.0
copilot-chat|Git|0.12.2024013003
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
vscode-memfs|gjs|0.0.3-182309
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
vscode-pr-pinger|jri|0.0.6
workspace-storage-cleanup|meh|1.1.5
vscode-docker|ms-|1.28.0
debugpy|ms-|2023.3.13341008
python|ms-|2023.25.10292213
vscode-pylance|ms-|2024.1.102
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
azure-account|ms-|0.11.6
extension-test-runner|ms-|0.0.5
hexeditor|ms-|1.9.12
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.8
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.3.2024013010
material-icon-theme|PKi|4.33.0
material-product-icons|PKi|1.7.0
vscode-thunder-client|ran|2.17.1
vscode-xml|red|0.26.1
rest-book|tan|6.2.1
luna-paint|Tyr|0.16.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2024-02-13 07:43
I set the Trace logging level for the Git channel, and luckily the next time I performed my usual procedure (see above) I got the problem:

![image](https://github.com/microsoft/vscode/assets/6726799/2ded9e2a-6f56-4751-bc1a-37fd449f4e0a)

Here's the log at that point:

[Git.log](https://github.com/microsoft/vscode/files/14257568/Git.log)

Clicking the Refresh button made no difference to the appearance. Here's the logfile afterwards:

[Git.log](https://github.com/microsoft/vscode/files/14257607/Git.log)

Developer: Reload Window fixed it:

![image](https://github.com/microsoft/vscode/assets/6726799/7b8e32d1-b118-436b-a9fb-cb6f5f11f17f)

[Git.log](https://github.com/microsoft/vscode/files/14257619/Git.log)

**Comment by gjsjohnmurray** [comment] 2024-02-13 07:53
Now I have the opposite case, where the blue button doesn't offer Sync 15 but the Outgoing section still lists them and offers Push:

![image](https://github.com/microsoft/vscode/assets/6726799/8a79461b-6ff0-403f-ab1c-bac362eb2c3b)

[Git.log](https://github.com/microsoft/vscode/files/14257702/Git.log)

Refresh doesn't fix it, but Reload Window does:

**Comment by lszomoru** [comment] 2024-02-13 12:05
@gjsjohnmurray, thank you very much! The good news is that looking at the logs, I have pushed a fix for a bug, but it's not the issue that is causing the outgoing changes to be missing. Could you please confirm that value of the following settings? 
* scm.showIncomingChanges
* scm.showOutgoingChanges

I have not seen the "Sync Changes" button not showing before? Are you able to reproduce that consistently? Thanks!

**Comment by lszomoru** [comment] 2024-02-14 10:53
I think that I have finally been able to track down the root cause of this issue. The problem was not in the `vscode.git` extension but rather in VS Code core where due to some timing issues the necessary event handlers were not being registered. The latest VS Code Insiders release (version details below) contains the fix that I am pretty confident that it resolves the issue.

If you enable `debug` logging in VS Code, you should see the following entries in the "Window" channel:
```
2024-02-14 11:46:32.063 [debug] SCMTreeDataSource:onDidChangeVisibleRepositories - onDidChangeCurrentHistoryItemGroup listener added
2024-02-14 11:46:32.064 [debug] SCMViewPane:onDidChangeVisibleRepositories - onDidChangeCurrentHistoryItemGroup listener added
```


Hitting refresh should produce the following entries that confirms that the cache is being cleared before the tree is updated: 

```
2024-02-14 11:53:15.280 [debug] SCMTreeDataSource:onDidChangeCurrentHistoryItemGroup - cache cleared
2024-02-14 11:53:15.280 [debug] SCMViewPane:onDidChangeCurrentHistoryItemGroup - update children
```

Version information:
```
Version: 1.87.0-insider (Universal)
Commit: 4f2ff19ecacffa0aa4874db4d63ed4e899d98431
Date: 2024-02-14T05:47:52.262Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Closed by lszomoru** 2024-02-14 10:53 UTC
Labels: bug, git

**Comment by andreamah** [comment] 2024-02-22 17:54
@lszomoru do you have some verification steps? Seems that this sometimes didn't occur after a reload.

**Comment by andreamah** [comment] 2024-02-23 19:23
@gjsjohnmurray Have you been seeing this on the latest insiders?

**Comment by gjsjohnmurray** [comment] 2024-02-23 20:58
No, I haven't seen it for a while so I think we can declare this fixed.
