### ISSUE TITLE
Maximize editor group auto sizing stops working after closing the sidebar

### ISSUE THREAD

**Issue by rbingham** [microsoft/vscode#70083] opened 2019-03-08 18:31 UTC
When maximizing an editor group and switching between groups, the focused group will maximize. After opening or closing the sidebar, the maximizing stops happening. I have had this happen on linux as well.

Version information

Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:15:00.418Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Steps to Reproduce:

1. Open two tabs and place them in different editor groups
2. Maximize editor group
3. Switching between editor groups makes the focused group maximize
3. Open sidebar
5. Close sidebar
6. Switching between editor groups doesn't maximize focused group.

Does this issue occur when all extensions are disabled?: Yes

Gif of bug:

![error](https://user-images.githubusercontent.com/7032804/54047883-80e5ff00-4195-11e9-970e-e59b81ec9c11.gif)

**Comment by bpasero** [comment] 2019-03-11 10:39
@sbatten something to reconsider for the workbench grid, I can reproduce both with the old layout and the new one.

**Comment by bpasero** [comment] 2019-08-08 10:10
Duplicate of https://github.com/microsoft/vscode/issues/77901 ?

**Comment by rbingham** [comment] 2019-08-08 13:44
@bpasero #77901 would be a duplicate of this issue as this one was made back in march.

**Comment by Taugeshtu** [comment] 2020-03-12 12:50
Letting you guys know that it still reproduces on:
```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-88-generic
```
And is still a pain to deal with; to a point where I'm now going to revert to 1.24 after trying out the latest release.

**Comment by karanssh** [comment] 2021-07-29 06:56
Bump, I run into this in latest release as well:

```text
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic
```

**Closed** 2022-12-22 16:16 UTC
Labels: bug, layout
