### ISSUE TITLE
Tooltips with diagnostics messages should wrap at word boundaries

### ISSUE THREAD

**Issue by rherrmann** [Microsoft/vscode#57229] opened 2018-08-26 14:02 UTC
- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6

Tooltips showing compiler messages (others possibly, too?) do not wrap at word boundaries. This makes the message difficult to read, depending on where the text is wrapped.

Example:
<img width="498" alt="screen shot 2018-08-26 at 15 46 18" src="https://user-images.githubusercontent.com/607182/44628841-2e0acf80-a948-11e8-812f-a68a65b1ef1b.png">

Expected behaviour:
```
[ts] Argument of type '0' is not assignable to parameter of type
'Uri | null | undefined'.
```

**Comment by mjbvz** [comment] 2018-09-05 17:20
Duplicate of #54503

**Closed by mjbvz** 2018-09-05 17:20 UTC
Labels: editor, editor-wrapping
