### ISSUE TITLE
File explorer commits file names to disk before I've finished typing the name

### ISSUE THREAD

**Issue by bradharms** [microsoft/vscode#112503] opened 2020-12-14 21:18 UTC
- VSCode Version:

Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

- OS Version:

Mac OS Big Sur (11.0.1)

Steps to Reproduce:

1. Create a new file or right-click and rename a file or press enter from the file explorer. The means of activating the "rename" function doesn't seem to matter.
2. Wait a few seconds (the time it takes to happen is random; seems to be between 1-5 seconds), with or without typing anything
3. VSCode acts as if you had clicked off the rename field, or as if you had pressed "Enter". The partially-typed name is commited to disk. All registered rename triggers fire with the partially-typed name (ie. references to the name in import statements). 

Does this issue occur when all extensions are disabled?: **Yes**

- Additional Info

I thought maybe this was being caused by some kind of OS extension, but I've disabled all services related to user input and its still happening.

EDIT: Added some more details to the activation conditions

**Comment by jacobweber** [comment] 2020-12-15 00:39
Also seeing this on Mac OS 10.14.6. It only happens if I create the file just before renaming it (e.g. hit the keyboard shortcuts for copy, paste, and rename, one after another).

**Comment by jimmyhogoboom** [comment] 2020-12-15 02:57
I'm having a somewhat similar issue. It seems like the Explorer is refreshing every 5 seconds, which automatically submits any changes I was in the process of making and closes all but one top-level folder. Extremely frustrating.

I tried running the new bisect extensions feature, but the problem persisted.

**Comment by isidorn** [comment] 2020-12-15 08:52
@jacobweber  Thanks for filling this, however we made some improvements to the File Explorer in VS Code insiders.
Can you please try to reproduce with insiders and let me know if you still see this
https://code.visualstudio.com/insiders/

@jimmyhogoboom your issue sounds related but different, you should also try with vscode insiders and let us know

Thanks!

**Comment by jimmyhogoboom** [comment] 2020-12-15 15:25
@isidorn My issue is no longer present in Insiders!

If it helps, in the regular release my problem only seems to happen when I have uncommitted changes, when the VC tab does its periodic refresh.

**Comment by jimmyhogoboom** [comment] 2020-12-15 15:27
I take it back, it's still happening sometimes. When I returned to Code after writing that message, all of my files in the tree were collapsed.

**Comment by jacobweber** [comment] 2020-12-15 16:28
@isidorn I wasn't the original reported, but I did a quick test on Insiders and I don't see the bug.

**Comment by waynebloss** [comment] 2020-12-16 15:55
Here's a screencap of it happening to me on Manjaro (Arch) Linux. It seems to have started after the update to 1.52

https://imgur.com/a/e4woTt8

Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:43:50.597Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.80-2-MANJARO

**Comment by bradharms** [comment] 2020-12-16 17:24
I tried using the insider preview build and the issue is still occuring.

Version: 1.53.0-insider
Commit: 2f8dee4d87cf215fd2ece45aa4ecfb097b345788
Date: 2020-12-16T09:56:28.313Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.1.0

**Comment by bradharms** [comment] 2020-12-16 17:29
> Here's a screencap of it happening to me on Manjaro (Arch) Linux. It seems to have started after the update to 1.52
> 
> https://imgur.com/a/e4woTt8
> 
> Version: 1.52.0
> Commit: [940b5f4](https://github.com/microsoft/vscode/commit/940b5f4bb5fa47866a54529ed759d95d09ee80be)
> Date: 2020-12-10T22:43:50.597Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Linux x64 5.4.80-2-MANJARO

That looks like its probably the same issue.

**Comment by uchilaka** [comment] 2020-12-23 11:42
> https://code.visualstudio.com/insiders/

I'm checking this out now - noticed the same issue when I updated from 1.51.1 to 1.52.1. Rolling back to 1.51.1 made the issue go away. 

To clarify, when I say "the issue", I mean, VSCode bailing on file renames in the file explorer, often after the first few characters are struck.

**Comment by uchilaka** [comment] 2020-12-23 11:44
> @jacobweber Thanks for filling this, however we made some improvements to the File Explorer in VS Code insiders.
> Can you please try to reproduce with insiders and let me know if you still see this
> https://code.visualstudio.com/insiders/
> 
> @jimmyhogoboom your issue sounds related but different, you should also try with vscode insiders and let us know
> 
> Thanks!

I'm checking this out now - noticed the same issue when I updated from 1.51.1 to 1.52.1. Rolling back to 1.51.1 made the issue go away.

To clarify, when I say "the issue", I mean, VSCode bailing on file renames in the file explorer, often after the first few characters are struck.

**Comment by uchilaka** [comment] 2020-12-23 12:11
@jacobweber @

> @isidorn My issue is no longer present in Insiders!
> 
> If it helps, in the regular release my problem only seems to happen when I have uncommitted changes, when the VC tab does its periodic refresh.

For moi, it seems like 1.53.0-insider Insider fixes the issue. I created a small uncommitted set of changes and was still able to edit my file name with stable behavior vs. the 1.52.1 experience. 

![image](https://user-images.githubusercontent.com/2763396/102994965-19c24780-44ee-11eb-8479-6d52d5c2d1b6.png)

**Comment by uchilaka** [comment] 2020-12-23 12:13
> I take it back, it's still happening sometimes. When I returned to Code after writing that message, all of my files in the tree were collapsed.

@isidorn @jimmyhogoboom @bradharms  For moi, it seems like `1.53.0-insider` fixes the issue. I created a small uncommitted set of changes and was still able to edit my file name with stable behavior vs. the 1.52.1 experience. 

![image](https://user-images.githubusercontent.com/2763396/102994965-19c24780-44ee-11eb-8479-6d52d5c2d1b6.png)

**Comment by jamesongithub** [comment] 2020-12-29 19:40
this is happening to me when renaming or creating new files.. 

![image](https://user-images.githubusercontent.com/4452738/103309672-91024a80-49ca-11eb-9c15-f84e4e16dd47.png)

**Comment by etoler1841** [comment] 2021-01-08 17:11
Came here to report the same issue. Running v1.52.1 on Windows 10. I generally work in WSL (Ubuntu 18.04), but this doesn't seem to happen if I work in Windows directly.

**Comment by bradharms** [comment] 2021-01-11 18:08
I updated to the latest insider preview and I'm still having the issue.

```
Version: 1.53.0-insider
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:12:22.156Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.2.0
```

**Comment by devgutt** [comment] 2021-01-12 01:20
Same problem here on mac:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

**Comment by bradharms** [comment] 2021-01-12 18:53
I don't know if this helps, but I have noticed I can change a file's name indirectly if I do it using the "rename symbol" function on an import that references the file I want to rename, since the "symbol" in question is the actual file name.

![image](https://user-images.githubusercontent.com/1239044/104359147-941e3000-54cc-11eb-899e-9e09a2292df5.png)

**Comment by gom59** [comment] 2021-01-14 14:55
I am facing similar issues: all explorer actions seem to be shut down by some background refresh. Renaming a file is impossible (the rename window closes in less than a second), but also creating a folder is impossible (naming dialog opens/closes right away).
Same with all extensions disabled.
This is under Ubuntu 20.04.1 LTS

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-36-generic

**Comment by derwaldgeist** [comment] 2021-01-14 20:14
Same issue here. Some characters are used for the filename, others go into the newly created file. This is pretty annoying.

**Comment by Floriferous** [comment] 2021-01-21 15:51
This bug is about as frustrating as they get, the kind to make you want to throw your computer out of the window!

Downgrading to 1.51 fixes the issue: https://code.visualstudio.com/updates/v1_51

**Comment by isidorn** [comment] 2021-01-22 09:54
Hello users. Sorry about this.
However I can not reproduce this issue, so I need help.

If somebody can reproduce with https://code.visualstudio.com/insiders/
I would really appreciate exact steps. 

I only care about insiders, since I have pushed related fixes there and they should hit stable in 2 weeks. And I believe that most of the issues that users mention here are already fixed.

**Comment by jacobweber** [comment] 2021-01-22 15:56
Didn't happen for me on the latest Insiders build (running with my extensions enabled).

To reproduce it on the release build, I just select a file, and quickly type the keyboard shortcuts for copy, paste, and rename. The text field to rename the file appears, but disappears within a second.

**Comment by derwaldgeist** [comment] 2021-01-22 17:04
@isidorn Is there an easy way to migrate all your settings / plugins to Insider? It looks as if it doesn't pick them up automatically (which makes sense).

**Comment by jamesongithub** [comment] 2021-01-26 21:16
If you're using brew on osx, I reverted to 1.51.1 with this cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/1b3664573842c75866efe59ad2531a208782cf42/Casks/visual-studio-code.rb which seems to work

**Comment by isidorn** [comment] 2021-02-02 13:23
This should be fixed with stable that is coming out in a week, let me know if you still see it with that version and I can reopen then

**Closed by isidorn** 2021-02-02 13:23 UTC
Labels: file-explorer, needs more info

**Comment by derwaldgeist** [comment] 2021-02-02 17:03
Awesome, thanks!

**Comment by bradharms** [comment] 2021-02-08 21:25
I can confirm this issue seems to be resolved in the latest insider build.

**Comment by isidorn** [comment] 2021-02-09 08:38
@bradharms can you please create a new issue? Since this issue consits of 90% of users who no longer see this I believe.
So I would try to get fresh steps and a new discussion with only the people who are experiencing it.
Thanks a lot

**Comment by lmanerich** [comment] 2021-02-09 23:09
Working for me, not even using insider build.
Fixed in the stable release.

**Comment by bourquep** [comment] 2021-02-16 15:15
FWIW, I've found what is triggering the problem in stable 1.53.2 (haven't tested with insider yet):

When I have an integrated terminal session active (regardless of if the terminal is visible or not), the problem occurs.

If I `exit` my integrated terminal session, the problem goes away.

**Comment by bradharms** [comment] 2021-03-04 20:51
> FWIW, I've found what is triggering the problem in stable 1.53.2 (haven't tested with insider yet):
> 
> When I have an integrated terminal session active (regardless of if the terminal is visible or not), the problem occurs.
> 
> If I `exit` my integrated terminal session, the problem goes away.

It doesn't seem to matter what the terminal is doing for me. However I have noticed the problem doesn't happen for a short time after starting the app. It only occurs after about 8-12 seconds after boot.

I also tried deleting all folders related to vscode from my home folder and restarting.

**Comment by bradharms** [comment] 2021-03-04 21:45
I have identified the source of the problem.

This is not an issue with VSCode, at least not directly. The problem seems to be caused by an [external terminal emulator](https://iterm2.com/) I have running in the background. It's not the shell itself that's causing the problem, its the actual emulator. The problem occurs as long as I have an emulator window cd'd into my project directory, regardless of which shell I'm running inside. My guess is that it has to do with the status bar feature, which shows the git status for the current working directory.

**Comment by haykam821** [comment] 2021-03-05 00:08
I can reproduce this by creating a file externally, such as by running `sleep 5s; touch test.txt`. If I am creating or renaming a file, the input will automatically close when the file explorer updates, even if the created file is not visible or in another directory.
