### ISSUE TITLE
Host name always visible in Breadcrumbs: File Path for files, openned from remote file system

### ISSUE THREAD

**Issue by obratim** [microsoft/vscode#115865] opened 2021-02-05 11:40 UTC
Breadcrumbs are cool for local files, but when I edit a file from remote file system, it becames less informative:
![image](https://user-images.githubusercontent.com/41594422/107028645-e64a2c80-67be-11eb-984b-2975535ef5d7.png)
Here it is not clear, where the file is located.

If I open two files with the same name from different remote file systems, it became little more infrmative because of tab names:
![image](https://user-images.githubusercontent.com/41594422/107028957-4fca3b00-67bf-11eb-860e-e04a22f22a0a.png)

I think, breadcrumbs could become more informative, if there was the hostname for files from remote file systems.

**Comment by isidorn** [comment] 2021-02-05 13:07
@jrieken this is probably because the labels does not use the labels serivce for that part of the path. Similar to that other issue which you looked into.

**Comment by jrieken** [comment] 2021-02-05 13:56
Yes - breadcrumbs operate on paths, not labels. Also, breadcrumb elements have a picker which allows to navigate to its siblings and that doesn't make sense for hostnames because there is no way to discover them.

**Comment by jrieken** [comment] 2021-02-05 13:57
Closing this as designed

**Closed** 2021-02-05 13:57 UTC
Labels: *as-designed
