### ISSUE TITLE
Integrated terminal, chinese word has a bug

### ISSUE THREAD

**Issue by ihaving** [Microsoft/vscode#8598] opened 2016-07-01 06:16 UTC
![Uploading 20160701141656.jpg…]()

- VSCode Version:1.2.1
- OS Version:windows7 64bit

Steps to Reproduce:

1. Integrated terminal, show of chinese has a bug
2.

**Comment by bpasero** [comment] 2016-07-01 08:04
@ihaving can you provide more details?

**Comment by Tyriar** [comment] 2016-07-01 09:02
Most likely a duplicate of #7062, a lot is different now in 1.3.0

**Closed by Tyriar** 2016-07-01 09:02 UTC
Labels: integrated-terminal, needs more info

**Comment by liyuan-rey** [comment] 2016-07-01 13:26
i have the same issue, see the screen shot below. Not same with #7062, i have NOT resize the window.
![screen-shot-01](https://cloud.githubusercontent.com/assets/10598397/16522788/68ccc6b4-3fd2-11e6-81f1-e3034d58a844.png)

**Comment by Tyriar** [comment] 2016-07-01 17:11
@liyuan-rey yes it should be the same underlying issue (and fixed now).

**Comment by ihaving** [comment] 2016-08-02 01:37
@bpasero @Tyriar 
Thank you.

The latest version has fixed the bug.
thank you for your reply.

![qq 20160802093618](https://cloud.githubusercontent.com/assets/12592104/17314117/913d3c34-5894-11e6-8a02-bf5db81e4808.jpg)
