### ISSUE TITLE
Cannot Paste between files

### ISSUE THREAD

**Issue by supernoir** [Microsoft/vscode#17349] opened 2016-12-15 22:20 UTC
- VSCode Version: 1.8.0
- OS Version: 10.12.1

I can copy and cut, but not paste from one file to another. Sometimes it helped to restart VSCode, but in the past two days, not so much. I run 10.12.1 and VSC 1.8.0. I love VSC otherwise, but this is quite irritating. Pasting in other Apps (Atom/TextEdit) works fine.

**Comment by rebornix** [comment] 2016-12-15 22:40
@supernoir when you say cannot paste between files, do you mean that

* Copy content outside of VS Code and paste into a file in VS Code works
* Copy content from a file in VS Code and paste into applications outside of VS Code works

And do you mind toggling the developer tools `Help -> Toggle Developer Tools` and see whether there is any error when the pasting doesn't work?

**Comment by rebornix** [comment] 2016-12-16 22:03
One more thing to check: Can you try right click and choose `Paste` from the context menu to see if the pasting works?

**Comment by bpasero** [comment] 2016-12-17 10:56
@Tyriar @rebornix is this a duplicate of https://github.com/Microsoft/vscode/issues/17232 maybe? Otherwise please let me know if you still plan on fixing this for the 1.8.1 recovery build on Monday.

**Comment by supernoir** [comment] 2016-12-17 14:26
Sorry for taking a while to reply:
@rebornix Neither copying/pasting content from outside of VSC into a file in VSC works, nor vice versa. Copying / Pasting within VSC doesn't work either. Dev Tools throw no error at either action.
Copying/Pasting with the help of the context menu yields the same results as menu bar and keyboard shortcuts.

The issue sometimes goes away upon restarting the app (reload doesn't help), I would say about half of the time.

Thank you!

**Comment by rebornix** [comment] 2016-12-17 17:23
It might be a dup of https://github.com/Microsoft/vscode/issues/13366 . @supernoir can you confirm that you are running into the same issue as ppl in #13366 ran into? Especially when you open VS Code from command line (or the tip https://github.com/Microsoft/vscode/issues/13366#issuecomment-264425354)

Since invoking paste command from context menu and menu bar doesn't work as well, IMHO it's related to #13366, which is upstream and fixed on Dec 12 in Electron.  cc @joaomoreno @alexandrudima

**Comment by supernoir** [comment] 2016-12-19 00:04
@rebornix yes, I can copy/paste easily when I launch VSC with spotlight works, but from command line (using tmux) doesn't. If it is fixed you can close the issue.

**Comment by Tyriar** [comment] 2016-12-19 01:24
I cannot reproduce any weirdness with paste specifically on Windows 10 other than the fact that the terminal can override the copy command as in #17232 which could cause the clipboard to be empty. If you're not getting this warning:

> Cannot copy terminal selection when terminal does not have focus

Then I don't know what it could be.

Note that the terminal does have it's own paste command which now points to ctrl+v instead of ctrl+shift+v in 1.7, however it relies on a different context key (`terminalFocus`) to the new terminal ctrl+c keybinding (`terminalTextSelected`) that did not change in 1.7. If the issue was related to `terminalFocus` then the following keybindings would also be activated:

```json
{ "key": "ctrl+v",                "command": "workbench.action.terminal.paste",
                                     "when": "terminalFocus" },
{ "key": "ctrl+down",             "command": "workbench.action.terminal.scrollDown",
                                     "when": "terminalFocus" },
{ "key": "shift+pagedown",        "command": "workbench.action.terminal.scrollDownPage",
                                     "when": "terminalFocus" },
{ "key": "ctrl+end",              "command": "workbench.action.terminal.scrollToBottom",
                                     "when": "terminalFocus" },
{ "key": "ctrl+home",             "command": "workbench.action.terminal.scrollToTop",
                                     "when": "terminalFocus" },
{ "key": "ctrl+up",               "command": "workbench.action.terminal.scrollUp",
                                     "when": "terminalFocus" },
{ "key": "shift+pageup",          "command": "workbench.action.terminal.scrollUpPage",
                                     "when": "terminalFocus" },
```

One way to check for sure if it's related to `terminalFocus` is if you focus in the editor, press ctrl+v and then it wrongly pastes into the terminal.

**Comment by rebornix** [comment] 2016-12-19 04:57
Now with @supernoir 's info, we can confirm that it's dup of #13366, which is an external issue described in electron repo https://github.com/electron/electron/issues/916 .

For short: 
> OS X's clipboard API requires the process to run in a UI session, which might not be true if you are using tmux.

You can mitigate this issue by following https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard#mac-os-x-pasteboard-access-under-tmux-and-screen

**Comment by kieferrm** [comment] 2016-12-19 06:26
Thanks @rebornix. Closing as duplicate of #13366.

**Closed by kieferrm** 2016-12-19 06:26 UTC
Labels: candidate, important
