### ISSUE TITLE
macOS Mojava introduces white line on window

### ISSUE THREAD

**Issue by lukepighetti** [Microsoft/vscode#68789] opened 2019-02-15 15:35 UTC
I upgrade to Mojave and now all my VSC windows have this white line above the window. I did not find another issue on this, but if you know of one please reference and close! Thanks

<img width="541" alt="screen shot 2019-02-15 at 10 35 48 am" src="https://user-images.githubusercontent.com/666539/52866816-7b087b00-310d-11e9-93b4-79c5e380f596.png">

**Comment by kieferrm** [comment] 2019-02-15 18:59
@lukepighetti all windows of any app seem to have the white line when they have focus. I'd guess this is to make the focus window visible in the dark theme even when the titlebar is black.

**Comment by misolori** [comment] 2019-02-15 19:02
Duplicate of https://github.com/Microsoft/vscode/issues/54838

See https://github.com/Microsoft/vscode/issues/62414#issuecomment-439687271 for the explanation:
>My understanding of these issues so far is that this is "intended behavior" on Mojave. macOS adds these color highlights to the window to match the theme under the assumption that the apps theme matches the OS theme. (This assumption is based on the `NSRequiresAquaSystemAppearance` key)
>
>If you're using a VS Code light theme with Mojave dark mode this is just going to happen unless Apple change there mind on enforcing this weird window border or someone finds a hidden window style for turning it off in native land.

**Closed by misolori** 2019-02-15 19:02 UTC

**Comment by lukepighetti** [comment] 2019-02-16 17:22
@misolori https://github.com/electron/electron/issues/13164#issuecomment-462099631
