### ISSUE TITLE
Import paths are not updated by folder rename

### ISSUE THREAD

**Issue by shairez** [Microsoft/vscode#53233] opened 2018-06-28 12:11 UTC
Issue Type: <b>Bug</b>

1. Rename a folder
2. See that the import path of the file inside that folder didn't update

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (8.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
angular1-code-snippets|ale|0.0.3
ng-template|Ang|0.1.9
angulardoc-vscode|Ang|6.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
githistory|don|0.4.0
tslint|eg2|1.0.28
vscode-todo-plus|fab|1.7.1
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
angular2-switcher|inf|0.1.6
Angular1|joh|0.2.0
Angular2|joh|2.12.0
expand-region|let|0.1.2
vscode-todo|Mat|0.8.0
prettify-json|moh|0.0.3
python|ms-|2018.1.0
azure-account|ms-|0.1.3
vsliveshare|ms-|0.2.151
debugger-for-chrome|msj|4.1.0
vscode-docker|Pet|0.0.22
vscode-icons|rob|7.22.0
vscode-coverage-gutters|rya|1.3.1
code-settings-sync|Sha|2.9.0
gitblame|wad|2.4.2
vscode-todo-highlight|way|0.5.11
vsc-angular-cli|web|1.0.0

(4 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-06-28 17:49
Duplicate of #50244

**Closed by mjbvz** 2018-06-28 17:49 UTC
Labels: typescript
