### ISSUE TITLE
vscode is very slower

### ISSUE THREAD

**Issue by github-lwc** [Microsoft/vscode#15391] opened 2016-11-12 00:44 UTC
Hello, when I run the following Python code, and sublime comparison, I found that the speed of the implementation of vcode is too slow, please fix this bug, thank you。

#cat test.py:
for i in range(1,200000,1):
    print i

**Comment by gertcuykens** [comment] 2016-11-12 04:50
hmm I fail to see what you are doing exactly? Are you sure this is not just python or one of the extensions you are using? Can't imagine if you run this in a shell you get a different result?

**Comment by aeschli** [comment] 2016-11-14 09:23
duplicate of #15404

**Closed by aeschli** 2016-11-14 09:23 UTC
