### ISSUE TITLE
Debug console scrolls near top after each evaluated line after exception raised in debug console

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#70331] opened 2019-03-12 18:49 UTC
Issue Type: <b>Bug</b>

See also https://github.com/Microsoft/vscode-python/issues/4725 - but note that `vscode-python` people say they 
> do not control the scrolling behavior of the debug console in VS Code

## Expected behaviour

Debug console behaves normally

## Actual behaviour

Debug console scrolls to top after each evaluated line

## Steps to reproduce:
1. Save this code as Bug.py:
```
import sys
sys.exit()
```
2. Enable breakpoints at "Uncaught exceptions"
3. Debug `Bug.py` in VS Code
4. When hitting SystemExit exception, run `print(1)` in Debug console.
5. Run `sys.exit()` a bunch of times (1-5 times) in the Debug console.
6. Notice that at one point, Debug console scrolls to top
7. Scroll to bottom of Debug console output
8. Run `print(2)` in Debug console.
9. Notice that you don't see `2` due to Debug console scrolling near top again.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|6.2.0
svn-scm|joh|1.47.1
python|ms-|2019.2.5558
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.2.7

</details>

**Comment by bersbersbers** [comment] 2019-03-12 19:41
> * [debug console shows top of window every time entering expression in console (#69207)](https://www.github.com/Microsoft/vscode/issues/69207)

Yes, looks like #69207 is a duplicate of this one, although #69207 does not have specific reproduction steps. This one does.

Also, it looks like they investigated 1.32.0-insider, while I am still seeing this in 1.32.1. Also, I can repro this in the latest insider build with only the Python extension and no settings changed whatsoever (see below). Finally, I must admit finding repro steps was a bit difficult. So I am not fully convinced this issue is fixed, as implied by #69207.

```
Version: 1.33.0-insider
Commit: 49c10b916705b6006f04d0701875098b26d1d70b
Date: 2019-03-12T06:17:28.991Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by isidorn** [comment] 2019-03-13 09:18
I can not reproduce this.
Can you attach a gif / video showing this
Also please try tomorrow's vscode insiders, we did some changes to the debug console which might influence this.

**Comment by bersbersbers** [comment] 2019-03-13 09:38
Sure, here's a GIF:
![2019-03-13_10-35-42](https://user-images.githubusercontent.com/12128514/54268660-05f95b80-457c-11e9-833d-e1e5226bbb02.gif)

**Comment by isidorn** [comment] 2019-03-13 14:35
I can not reproduce with node.
@DonJayamanne please try reproducing with python
@bersbersbers if you F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/900f10077c68796e7003cc9ad9fd9ace10ae1eda/src/vs/workbench/contrib/debug/electron-browser/repl.ts#L85) what do you see as scrollTop, scrollHeight and renderHeight at the exact moment when the debug console scrolls unexpectedly?

**Comment by razhangwei** [comment] 2019-03-13 14:37
I encountered exactly the same issue as @bersbersbers.

**Comment by isidorn** [comment] 2019-03-13 14:57
@razhangwei then you can also try to answer the quesionts i asked @bersbersbers . Get your hands dirty and do some debugging. Thanks

**Comment by bersbersbers** [comment] 2019-03-13 15:08
> @bersbersbers if you F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/900f10077c68796e7003cc9ad9fd9ace10ae1eda/src/vs/workbench/contrib/debug/electron-browser/repl.ts#L85) what do you see as scrollTop, scrollHeight and renderHeight at the exact moment when the debug console scrolls unexpectedly?

Breakpoint is hit twice per manual `sys.exit()`.

After the first time manually entering `sys.exit()`, with the breakpoint hit at line 85:

    scrollTop = 0, scrollHeight = 19, renderHeight = 214
    scrollTop = 0, scrollHeight = 480, renderHeight = 214

After the second time manually entering `sys.exit()`:

    scrollTop = 266, scrollHeight = 480, renderHeight = 214
    scrollTop = 266, scrollHeight = 80, renderHeight = 214 (*)

After (*), debug console is scrolled to top. I noticed that **during** (*), the debug console is empty, but not during any of the other breakpoint hits.

**Comment by DonJayamanne** [comment] 2019-03-13 15:23
Yes, I too can replicate this issue.

**Comment by isidorn** [comment] 2019-03-13 15:44
Ok, thanks for help everybody.
I can repro on my mac. Investigating...

**Comment by isidorn** [comment] 2019-03-13 16:18
After investigating and discussion with @joaomoreno we figured out it is a dup of https://github.com/Microsoft/vscode/issues/68385

**Comment by octref** [comment] 2019-04-21 16:07
Version: 1.34.0-insider
Commit: 750680d2f7ae563529501f8ec419d83ccf8ec325
Date: 2019-04-19T19:59:19.092Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

This issue is not fixed in latest Insider and bugs me every day:

![gif](https://user-images.githubusercontent.com/4033249/56472554-c80e1380-6414-11e9-81cc-4be4b8bc7f04.gif)

**Comment by pranav08** [comment] 2019-04-22 08:45
I'm facing this since few months now. Any clue on how to avoid this issue!

**Comment by kepeterson** [comment] 2019-04-22 17:00
https://github.com/Microsoft/vscode/issues/71737

Check the insider release and see if it's fixed for you (it was for me). It seems the maintainers have chosen to leave this broken for everyone until their next major release next month which is unfortunate.

**Comment by octref** [comment] 2019-04-22 23:11
@kepeterson I'm on Insiders, it's not fixed for me..

Version: 1.34.0-insider
Commit: 750680d
Date: 2019-04-19T19:59:19.092Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

**Comment by alexrada** [comment] 2019-05-01 13:16
I have the same issue.
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-34-generic snap

**Comment by nbara** [comment] 2019-05-16 09:13
Also having this issue, even on the latest Insiders version (1.34.20-insider)

See gif here :  
https://github.com/microsoft/vscode/issues/71737#issuecomment-492986211

**Comment by wot48** [comment] 2019-05-17 02:16
Same issue here.

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:09.080Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 10.0.17134

**Comment by nazariydolfin** [comment] 2019-05-17 14:03
please do not close this issue. I am experiencing same problem:

VSCode version: 1.33.1    

System Software Overview:

      System Version: macOS 10.14.4 (18E226)
      Kernel Version: Darwin 18.5.0
      Boot Volume: Mac OS
      Boot Mode: Normal
      Computer Name: iMac001
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days 6 minutes

**Comment by isidorn** [comment] 2019-05-24 14:07
@octref sorry that this is a pain. I am looking into it but can not reproduce.
Can you provide exact steps please?

**Comment by bersbersbers** [comment] 2019-05-24 15:29
Hi @isidorn, OP here. I can still repro the bug in official 1.34.0, so this is certainly not fixed. However, my repro steps from the original description do not work any longer as running `sys.exit()` actually ends the process that is debugged. I managed to repro the same issue with `throw 1`. So these are my current repro steps:

1. Save this code as Bug.py:
```
breakpoint()
print(0)
```
2. Debug `Bug.py` in VS Code
3. When hitting the breakpoint, run `print(1)` in Debug console.
4. Run `throw 1` a bunch of times (1-5 times) in the Debug console.
5. Notice that at one point, Debug console scrolls up quite a bit
6. Scroll to bottom of Debug console output
7. Run `print(2)` in Debug console.
8. Notice that you don't see `2` due to Debug console scrolling near top again.

Here's a gif as well.
![6YmdHy3AB5](https://user-images.githubusercontent.com/12128514/58339218-642e9e80-7e49-11e9-92ce-0a48814e2ad8.gif)

**Comment by isidorn** [comment] 2019-06-10 12:31
@bersbersbers we have pushed a fix with the help of @jeanp413 
Please try it with VSCode insiders starting from Tuesday which will have the fix. Thank you

**Closed** 2019-06-10 12:31 UTC
Labels: debug

**Comment by bersbersbers** [comment] 2019-06-25 09:38
I have just checked
```
Version: 1.36.0-insider (user setup)
Commit: e80dd4f217db6e230d311a87fdf4276f740f6445
Date: 2019-06-25T05:19:01.461Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
and it seems to me the issue is gone, thank you! (Of course, I will be more confident once an actual release has the fix as I haven't re-setup insiders the exact same way I use my release version - let's hope for the best!)

**Comment by isidorn** [comment] 2019-06-25 10:36
Thanks. Adding verified label. Let us know how it goes once you get the stable update.

**Comment by bersbersbers** [comment] 2019-07-03 19:19
Stable looks good to me, too, thanks!
