### ISSUE TITLE
视图错误

### ISSUE THREAD

**Issue by AkiraKiwi** [Microsoft/vscode#32680] opened 2017-08-17 02:16 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.10.0
python|don|0.7.0
easy-icons|jam|0.3.1
cpptools|ms-|0.12.2
PowerShell|ms-|1.4.1
java|red|0.8.0
background|sha|1.1.15
markdown-preview-enhanced|shd|0.2.5
python|tht|0.2.3
debug|web|0.21.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1.在拉伸侧栏的时候，会出现如图中所示的“黑线”
![image](https://user-images.githubusercontent.com/22570971/29393198-fbbd4402-8334-11e7-88a5-5f2b69865624.png)

Reproduces without extensions: Yes/No

**Comment by CnSimonChan** [comment] 2017-08-17 02:24
Translation:

> ## Rendering problem
>
>When resizing the sidebar, a black line as the screenshot shows appears.

Maybe a dup of #32677, looks like same symptom.

**Comment by AkiraKiwi** [comment] 2017-08-17 02:36
Yeah, it's the same as #32677

**Comment by aeschli** [comment] 2017-08-17 09:45
duplicate of #32677

**Closed by aeschli** 2017-08-17 09:45 UTC
Labels: new release
