### ISSUE TITLE
Intellisense occasionally stops working

### ISSUE THREAD

**Issue by jmusser73** [Microsoft/vscode#26237] opened 2017-05-08 20:08 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-angular-components-intellisense|ipatalas|0.6.1|
|vue|jcbuisson|0.1.5|
|vscode-todo-parser|minhthai|1.8.9|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|better-merge|pprice|0.6.0|
|html-preview-vscode|tht13|0.1.1|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. Pressing ctrl + space shows the context menu with intellisense results, but will just say "Loading..." until I restart VSCode.  After which it will work again.

**Comment by mjbvz** [comment] 2017-05-10 06:07
First, does this problem happen if you disable all extensions? Try running code using the `--disable-extensions` flag to test if an extension is the root cause

If the issue still occurs, please try collecting the TSServer logs to help us investigate this:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue
3. Run the `Open TSServer log File` command and share the `tsserver.log` file

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment] 2017-05-16 04:55
Closing as not actionable without more information

**Closed by mjbvz** 2017-05-16 04:55 UTC
Labels: javascript, needs more info, typescript
