### ISSUE TITLE
Undo incorrectly applies autocompletion

### ISSUE THREAD

**Issue by macp3o** [Microsoft/vscode#61124] opened 2018-10-17 07:58 UTC
Issue Type: <b>Bug</b>

**Suggested solution**: Disable autocompletion during undo.

**Steps to reproduce the problem**:
1. Enter the following code in an html file: `<script>text</script>`
2. Delete the closing `>` of the `<script>` tag. yielding `<scripttext</script>`
3. Press Ctl+Z to undo. Undo should restore the deleted `>` only and show the original code from step 1. However, we get `<script></script>text</script>` (notice the extra `</script>`).

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:34.132Z)
OS version: Linux ia32 4.4.0-137-generic

**Comment by aeschli** [comment] 2018-10-17 08:59
duplicate of https://github.com/Microsoft/vscode/issues/34484

**Closed by aeschli** 2018-10-17 08:59 UTC
Labels: html
