### ISSUE TITLE
Vscode auto format spaces before and after curly brackets

### ISSUE THREAD

**Issue by johnyousif** [Microsoft/vscode#24722] opened 2017-04-13 22:10 UTC
The auto formatting on vscode is great but in jsx if you do e.g.

Import {NamedExport} from 'blah' 

The auto formatter will do:

Import { NamedExport } from 'blah' 

Which is rather annoying. The applicable settings are all set to false so please don't suggest setting any of the usual suspects to false as per stackoverflow and Twitter.

It seems like an issue in vscode itself.

Please advise.

**Comment by mjbvz** [comment] 2017-04-13 22:50
Yes, formatting control of spaces around brackets is currently not exposed. #18043 tracks adding this setting. We should be able to pick up support for this formatting option this month

Closing as a duplicate of #18043

**Closed by mjbvz** 2017-04-13 22:50 UTC
Labels: duplicate, format, javascript, typescript
