### ISSUE TITLE
[Feature Request] Profiles like Chrome, Firefox, etc.

### ISSUE THREAD

**Issue by lwxbr** [Microsoft/vscode#63637] opened 2018-11-22 11:26 UTC
Good day, What is the possibility of VS Code having a scheme of profiles like browsers do (bookmarks, history, extensions) to save extensions, configs, settings, themes and etc? I'm not against the feature of export settings, but sync config is better.

**Comment by sandy081** [comment] 2018-11-23 09:59
Duplicate of #2743

**Closed by sandy081** 2018-11-23 09:59 UTC
Labels: config
