### ISSUE TITLE
How do I delete a cell?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117702] opened 2021-02-25 20:22 UTC
I accidentally added a new cell locally in the endgame issues notebook but I don't know how to delete it while in notebooks view :c

![recording (4)](https://user-images.githubusercontent.com/7199958/109211988-d8efe480-7763-11eb-8ece-8f489245a9ad.gif)

Edit: I'm on Codespaces. There also is a rendering glitch at the bottom since I resized the window to record the demo, but I'm assuming that's another issue.

**Comment by rebornix** [comment] 2021-02-25 21:34
/duplicate of https://github.com/microsoft/vscode/issues/117693 thanks!

**Closed by rebornix** 2021-02-25 21:34 UTC
