### ISSUE TITLE
Typescript/Javascript Server Crashing Multiple Times on Ubuntu 20.04 LTS.

### ISSUE THREAD

**Issue by Labham-Jain** [microsoft/vscode#130558] opened 2021-08-11 08:58 UTC
Issue Type: <b>Bug</b>

1. open material ui react javascript project.
2. start create-react-app server using yarn. 
3. Wait for initialization of TS/JS intellisense server
4. You'll get alert of ts/js server crashed 5 times.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-25-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1999)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 4, 3|
|Memory (System)|11.57GB (6.43GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b96ca806-f8a7-4cc2-8924-c9df4aa964a3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.1.0
JavaScriptSnippets|nat|0.2.0
material-icon-theme|PKi|4.9.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30350414

```

</details>

**Comment by gorbunovav** [comment] 2021-08-13 15:10
@mjbvz I am experiencing this issue opening projects inside WSL running Ubuntu 20.04 distro.
The issue is present on VSCode 1.59 version even with all extensions disabled (except the Remote Development Pack).
VSCode uses built-in Typescript by default, changing it to the project one doesn't have any effect on the issue.

With the insiders build everything works ok even with all workspace extensions enabled.

**Comment by Labham-Jain** [comment] 2021-08-17 06:46
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?


No, It isn't throwing the issue...

**Comment by mjbvz** [comment] 2021-08-17 17:02
Ok, closing since it sounds like it was already fixed then (or an extension was causing the issue)

**Closed by mjbvz** 2021-08-17 17:02 UTC
Labels: needs more info
