### ISSUE TITLE
Windows: window dimensions shrink after waking up from sleep

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#12447] opened 2016-09-22 12:50 UTC
- VSCode Version: 1.5.2
- OS Version: win 10

Steps to Reproduce:
1. open vs code in maximum window.
2. let win 10 go to sleep
3. login and vscode window shrink to small size and went to top left corner

**Comment by chrmarti** [comment] 2016-09-22 17:50
Could not reproduce. Does this reproduce consistently on your machine?

**Comment by khaled-hossain-code** [comment] 2016-09-24 03:39
I am not sure why it is not regenerating but might the following image will give a clear understanding of my problem. step 3 show the size of vscode after I log in from sleep.

[url=http://postimg.org/image/4mvhct3dz/][img]http://s15.postimg.org/4mvhct3dz/step3.png[/img][/url]

[url=http://postimg.org/image/tu6dd26hz/][img]http://s15.postimg.org/tu6dd26hz/step2.png[/img][/url]

[url=http://postimg.org/image/lpy98bk2v/][img]http://s15.postimg.org/lpy98bk2v/step1.png[/img][/url]

**Comment by chrmarti** [comment] 2016-09-26 14:41
The windows has extra buttons in its title bar. Where are these coming from? Some window manager extension?

**Comment by khaled-hossain-code** [comment] 2016-09-27 08:29
its built in win10 feature when I plug in two monitor I get this feature.

**Comment by bpasero** [comment] 2017-11-14 17:25
@khaled-hossain-code still happening with latest?

**Comment by khaled-hossain-code** [comment] 2017-11-15 06:40
@bpasero I have switched to mac os and in macos its working fine.

**Comment by bpasero** [comment] 2017-11-15 06:55
Ok, closing until we see this again.

**Closed by bpasero** 2017-11-15 06:55 UTC
Labels: electron, needs more info, upstream
