### ISSUE TITLE
Tabs no longer show dirty / modified files

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#13524] opened 2016-10-11 17:01 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: DotJoshJohnson.xml-1.6.0, Shan.code-settings-sync-2.3.1, donjayamanne.python-0.3.24, groksrc.haml-0.0.2, lukehoban.Go-0.6.43, ms-vscode.csharp-1.4.1, rebornix.Ruby-0.9.0

Steps to Reproduce:

1. macOS Sierra, install VSCode
2. Open / edit multiple files -- note the editor no longer display any indication of the files being "dirty"

**Comment by isidorn** [comment] 2016-10-11 20:50
Do you have auto save turned on maybe?
If not, can you paste your user / workspace settings?

Thanks!

**Comment by brendandixon** [comment] 2016-10-11 22:48
@isidorn Sigh. I do have AutoSave on. I didn't stop to think about the relationship. Though, I would still expect the dirty indicator to appear in-between auto-save events...

**Comment by isidorn** [comment] 2016-10-12 06:28
@brendandixon I do not agree because the dirty indicator is then flashing and very distracting. I am an auto save user thus saying this from personal experience :)
Closing as designed

**Closed by isidorn** 2016-10-12 06:28 UTC
Labels: needs more info
