### ISSUE TITLE
menu bar does not have infinite height when window is maximised or placed at the top of the screen

### ISSUE THREAD

**Issue by a1291762** [microsoft/vscode#152119] opened 2022-06-14 21:38 UTC
Issue Type: <b>Bug</b>

The whole point of a menu bar at the top of the screen is that you can jam the mouse up and click on the menu without having to worry about "overshooting" the menu bar. But Visual Studio Code running on Ubuntu 20.04 breaks this by having a gap between the top of the menu bar and the top of the window.

The primary case that concerns me is when Visual Studio Code is maximised. A secondary case is when the window is not maximised, but placed at the top of the screen. In both cases, I would expect the menu bar to have infinite height, though I am generally more concerned with the first case (maximised window).

Running my mouse across the top of the screen it seems like the only controls that have infinite height are the 3 window controls (minimise, un-maximize, close).

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:49:57.055Z)
OS version: Linux x64 5.13.0-48-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.13GB (2.26GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b6ae8a48-6621-4d50-937f-56c18083912b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
expect|bda|1.0.1
vscode-raml|blz|3.0.1
vscode-modelines|chr|2.0.5
vscode-eslint|dba|2.2.2
bitbake|Eug|1.1.2
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.10.5
vscode-qt-for-python|sea|1.1.7
jenkinsfile-support|sec|0.1.0
trailing-spaces|sha|0.3.1
gitconfig|sid|2.0.1
ninja|sur|0.0.1
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
gitblame|wad|8.2.2
swig-tpl|zha|0.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by yume-chan** [comment] 2022-06-15 05:19
Duplicate of #150170

**Closed** 2022-06-15 17:50 UTC
