### ISSUE TITLE
Allow `createFileSystemWatcher` with custom exclude rules

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#169724] opened 2022-12-21 09:47 UTC
Given we make good progress on https://github.com/microsoft/vscode/issues/137872 we could enrich our file watcher API to allow an extension to provide glob patterns for exclude rules. We can then push these rules down directly to Parcel.

**Some things to consider:**
* we then should probably allow even recursive requests to go through when they are overlapping which we currently block
* if so, we need to revisit https://github.com/microsoft/vscode/issues/169609
* as for API, we then probably should have another `createFileSystemWatcher ` overload accepting `options`

**Comment by mrazauskas** [comment] 2023-01-25 19:33
Would this allow passing `include` and `exclude` to `workspace.createFileSystemWatcher` just like it works with `workspace.findFiles`? That would be perfect for wip extension I am currently developing.

To give more detail – the extension is wrapping a testing library, which selects test files using `include` and `exclude` globs. The globs are set through a config file (similar to `tsconfig.json`), hence each folder in a workspace can have different excludes.

Parsing the config file and passing `include` and `exclude` to `workspace.findFiles` works smooth. Also I can create watchers for each folder easily, but un-watching the excludes is cumbersome at the moment.

If I get it right, `files.watcherExclude` got the necessary upgrade recently. Would be very useful to have this issue fix at some point.

Thanks for the job you do!

**Comment by bpasero** [comment] 2023-01-26 05:27
Yes, I think the idea would be for an extension to have full `include` and `exclude` control over recursive and non-recursive watchers.

**Comment by eamodio** [comment] 2023-03-16 16:32
Can't wait for this -- I've tried adding not/exclude patterns in the `globPattern` that `createFileSystemWatcher` currently accepts, but they don't seem to work.

**Comment by lewisl9029** [comment] 2023-04-03 23:38
I'd love to see support for an array with multiple exclude globs. This has been a major pain point for me with the current findFiles API which only supports a single glob: https://github.com/microsoft/vscode/issues/38545

We can sort of hack together some custom logic to combine globs into a single string, but it's super brittle and can fail in unintuitive ways, and doesn't play nicely with the RelativePattern helper.

**Comment by bpasero** [comment] 2023-10-10 08:59
Proposal: https://github.com/microsoft/vscode/blob/29b69437ab854a60e94cd8dd863a6740ba645cd4/src/vscode-dts/vscode.proposed.createFileSystemWatcher.d.ts#L36

**Comment by Klaim** [comment] 2024-05-30 12:15
Just a note that I confirmed today that [#104251](https://github.com/microsoft/vscode/issues/104251) is still not fixed. It was closed as a duplicate of another issue which was also closed but is not enough to fix the issue. This issue seems to be a potential solution so just wanted to make sure that the issue I reported gets tested once this issue is fixed, or at least linked to this one.

**Closed** 2024-12-10 05:25 UTC
Labels: feature-request, api, file-watcher, *out-of-scope, api-proposal, keep

**Comment by bpasero** [comment] 2024-12-10 05:28
Given our very bad experience with running multiple overlapping file watchers on the same folders, this is unlikely to happen. Quite the opposite, in the future its more likely to have 1 recursive watcher per folder-tree that has no excludes and then implement dispatching from there to anyone interested based on glob patterns.
