### ISSUE TITLE
MX master 3 mouse horizontal scrolling

### ISSUE THREAD

**Issue by glend1** [microsoft/vscode#151891] opened 2022-06-12 18:15 UTC
Issue Type: <b>Bug</b>

The horizontal scroll on my mouse doesn't work on my computer until i try to scroll on a different window. then when I come back to vs code i am allowed to scroll horizontally.

I have not tested if this is per windows boot or if its per instance of vs code

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.72GB free)|
|Process Argv|--crash-reporter-id 4d041c0a-688f-4992-95b6-5a48a2b81905|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.6
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.7
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
todo-tree|Gru|0.0.215
vscode-drawio|hed|1.6.4
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
vscode-jest|Ort|4.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by ianrobertsFF** [comment] 2022-06-12 23:54
I will sporadically also have horizontal scrolling fail in VS code with an MX Master 1

**Comment by alexdima** [comment] 2022-10-22 17:08
Duplicate of #84136

**Closed by alexdima** 2022-10-22 17:08 UTC
