### ISSUE TITLE
[css] `appearance` property not supported

### ISSUE THREAD

**Issue by skube** [Microsoft/vscode#31773] opened 2017-07-31 19:42 UTC
- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a SCSS file with
`input {
   appearance: none;
}`
2. Use Cmd + Shift + M to open Problems Window
3. Notice warning: 
```
severity: 'Warning'
message: 'Unknown property.'
source: 'scss'
```

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-09-07 15:59
Duplicate of https://github.com/Microsoft/vscode-css-languageservice/issues/22

**Closed by aeschli** 2017-09-07 15:59 UTC
Labels: css-less-sass, feature-request
