### ISSUE TITLE
Hightlighted indent guides will disappeared when scroll mouse

### ISSUE THREAD

**Issue by frankyuan** [Microsoft/vscode#49198] opened 2018-05-04 10:50 UTC
Issue Type: <b>Bug</b>

1. Set "editorIndentGuide.activeBackground": "#ff0000" in workbench.colorCustomizations
2. Select an block(more than one screen) from top of block and show the indentguideline.
3. Scroll mouse down and indentguideline will disappeared.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.29GB free)|
|Process Argv|d:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.31
python|ms-|2018.4.0
csharp|ms-|1.14.0
vim|vsc|0.11.5

(1 theme extensions excluded)

</details>

**Comment by Yanpas** [comment] 2018-05-04 19:28
How does the bug look like:
![image](https://user-images.githubusercontent.com/7345761/39648320-7fc409c0-4fea-11e8-9645-18fb984a1c21.png)

**Comment by frankyuan** [comment] 2018-05-05 14:34
Select a block(more than a screen) from top of the block:
![image](https://user-images.githubusercontent.com/2581691/39664246-0b531d1e-50b3-11e8-9f5c-881b84d4431f.png)
Scroll down the mouse:
![image](https://user-images.githubusercontent.com/2581691/39664333-48397678-50b4-11e8-9079-ca214d8d9e0e.png)

Full Screen:
![image](https://user-images.githubusercontent.com/2581691/39664339-64aa3978-50b4-11e8-825e-b3cb9865eace.png)

**Comment by alexandrudima** [comment] 2018-05-07 07:34
Duplicate of #49173

**Closed by alexandrudima** 2018-05-07 07:34 UTC
Labels: new release
