### ISSUE TITLE
Keyboard Shortcut(s) Changed?

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#81552] opened 2019-09-27 15:28 UTC
Issue Type: <b>Bug</b>

On Windows, when did the default keyboard shortcut for "Task: Run Build Task" get removed? On Windows it used to be Ctrl-Shift-B. It exists on the MacOS, and the latest Exploration version it exists. Yes, I can add it back, but why was it removed?

VS Code version: Code - Insiders 1.39.0-insider (e0762af258c0b20320ed03f3871a41967acc4421, 2019-09-27T05:26:42.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (6.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
vscode-eslint|dba|1.9.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
output-colorizer|IBM|0.1.2
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
azure-account|ms-|0.8.4
csharp|ms-|1.21.3
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
vetur|oct|0.22.3
material-icon-theme|PKi|3.9.0
quicktype|qui|12.0.46
vscodeintellicode|Vis|1.1.9

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-09-27 18:33
Strange. I can see shortcut in TypeScript repo, but not in other repos. Event with extension disabled.

However default shortcut is still there, but not visible in Command palette (even with extensions disabled)
```
{ "key": "ctrl+shift+b",          "command": "workbench.action.tasks.build" },
```

**Comment by jtsom** [comment] 2019-09-27 18:38
Yep, it's not there as a default at all (only shows my "User" entry I had to make):

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13488/65793692-6b85f180-e134-11e9-95d3-2a366674b189.png">

**Comment by IllusionMH** [comment] 2019-09-27 19:45
I was able to reproduce this issue, but as mentioned above - I can see shortcut in workspace for TypeScript repo, but unable to see it in workspace for vscode repo or local folder that has `.vscode/tasks.json` and even task marked as default.

I switch between workspaces with File > Open recent.

**Comment by alexr00** [comment] 2019-09-30 09:47
In the keyboard shortcuts UI can you search for ctrl+shift+b to see if there is another binding? If an extension contributes a keybinding for ctrl+shift+b then it would override the default tasks build shortcut.

**Comment by jtsom** [comment] 2019-09-30 11:51
Nope. None that I'm aware of.

**Comment by IllusionMH** [comment] 2019-09-30 12:00
@alexr00 for me <kbd>Ctrl+Shift+B</kbd> became missing after few window reloads, opening another recent workspace (File > Open Recent or from Welcome tab), opening new windows (File > New Window).

Looks like there are cases when this shortcut is not added immediately. I captured case when shortcut was added only after I executed `>Preferences: Open Default Keyboard Shortcuts (JSON)` (no window reload or opening new window between these screenshots)
1) Before
![image](https://user-images.githubusercontent.com/1312662/65876646-6cb45a00-e392-11e9-8675-fdc46ec29889.png)
2) After opening 
![image](https://user-images.githubusercontent.com/1312662/65876755-ac7b4180-e392-11e9-9916-a868b859297d.png)

However I had cases when I found commented `workbench.action.tasks.build` in `// Here are other available commands: ` section.

**Comment by alexr00** [comment] 2019-09-30 12:13
@IllusionMH lots of good details, thank you. I just repro'd it and am investigating.

**Closed** 2019-09-30 13:14 UTC
Labels: bug, tasks

**Comment by alexr00** [comment] 2019-09-30 13:16
I repro'd this once then I couldn't get it to happen again. I've moved the registration of the keybinding to be earlier which I hope will fix it.

Please do download insiders tomorrow and see if it's still happening!

**Comment by IllusionMH** [comment] 2019-10-01 09:43
@alexr00 looks OK after update. 👍 
I've tried several times cases described above and haven't seen problem to reappear.

**Comment by alexr00** [comment] 2019-10-01 10:11
Thank you for verifying!
