### ISSUE TITLE
Annoying output tab pops up when scrollbar-color is used in an .scss file

### ISSUE THREAD

**Issue by k1sul1** [microsoft/vscode#77386] opened 2019-07-15 08:18 UTC
Issue Type: <b>Bug</b>

As the title states, whenever I add scrollbar-color property, output tab pops up and whines about something: 

```
Error while computing completions for [redacted]/App.scss: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /opt/visual-studio-code/resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:582641
```

As an user, I don't care whether or not you have autocomplete for a property, but I certainly do not want to see an error about it :slightly_smiling_face: 

Especially when that error is shown in a very intrusive way. It shifts all of my panes when it opens on the right, which is where I want to keep it. I keep it closed literally 99% of the time. For the sake of the screenshot, I put it on bottom.

![image](https://user-images.githubusercontent.com/2719615/61202720-f9833c00-a6f0-11e9-84f6-fd03986f2ef9.png)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 5.1.16-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2435)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|31.27GB (19.17GB free)|
|Process Argv|--disable-extensions
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by octref** [comment] 2019-07-15 16:48
Duplicate of #76572. You can use https://code.visualstudio.com/insiders/ for now.

**Closed by octref** 2019-07-15 16:48 UTC
Labels: needs more info
