### ISSUE TITLE
Extension recommendations do not include an immediate way to install them

### ISSUE THREAD

**Issue by fmorriso** [Microsoft/vscode#10615] opened 2016-08-17 12:30 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

When I receive a recommendation, such as one to install a special c-sharp helper extension, why do you tease me with just the recommendation and no *DIRECT* way to immediately install that recommended extension?

Why not include "Would you like to install this/these recommendation(s) now?" as part of the recommendation?  Don't just tease me.  Make it easy to follow through on the recommendation.

Steps to Reproduce:

1. Open up a single file with a .cs extension.
2. Look on in wonderment at the recommendation to install a special c-sharp helper extension with nothing on the screen to provide an IMMEDIATE, DIRECT way to install that recommended extension.

**Comment by joaomoreno** [comment] 2016-08-17 15:29
It is also benefit that we _drive_ users to the `@recommended` view, such that they learn that it exists. It could even show you other recommendations you wouldn't otherwise know about.

**Comment by joaomoreno** [comment] 2016-10-10 10:16
I'll close it as designed, since we want to drive people to the recommendations.

**Closed by joaomoreno** 2016-10-10 10:16 UTC
Labels: bug
