### ISSUE TITLE
Insecure repo warning shows up for freshly cloned repo

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#169353] opened 2022-12-16 01:27 UTC
Fresh Windows 11 VM, installed git via winget.

Checked out repo via VS Code's clone flow and got a warning after restart:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/8599/208000591-8a5b97a3-8856-4252-97ba-c6989e58da83.png">

Could VS Code prevent this somehow earlier in the process, when users are not authenticated?

**Comment by lszomoru** [comment] 2022-12-16 08:56
I am not sure what you mean. During the repository discovery phase, we call `git.exe` and that returns the fact that the repository is potentially unsafe. This has nothing to do with whether you have trusted the repository, or whether you are signed in to VS Code. `git.exe` inspects the ownership of the folder where the repository resides. I am suspecting that the folder in which you have cloned the repository is owned by the "Administrators" group.

**Comment by lszomoru** [comment] 2023-01-30 09:27
Closing this as duplicate of https://github.com/microsoft/vscode/issues/168109.

**Closed by lszomoru** 2023-01-30 09:27 UTC
Labels: bug, git
