### ISSUE TITLE
slight but annoying issue regarding writing Korean

### ISSUE THREAD

**Issue by tylershyoon** [Microsoft/vscode#65643] opened 2018-12-24 14:37 UTC
vscode version:1.30.1(1.30.1)
os version: macOS Mojave 10.14.2

I sometimes use vscode as a plain text editor, but every time I write Korean word and then press enter,
the the last two letter of that Korean word follows with the switched cursor and shown in the next line, which should have been remained on the previous line.

**Comment by rebornix** [comment] 2019-01-08 18:06
This issue was solved in Insiders which updates to Electron 3.0.x.

**Comment by rebornix** [comment] 2019-01-08 18:06
/duplicate of https://github.com/Microsoft/vscode/issues/65580

**Closed** 2019-01-08 18:06 UTC
Labels: *duplicate, editor-ime, mac
