### ISSUE TITLE
Extension/Snippet warning slowness

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#36796] opened 2017-10-24 05:33 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
text-transform|flo|0.1.0
vscode-icons|rob|7.16.0
wordpress-snippet|tun|1.1.2
sort-lines|Tyr|1.3.0
---

Hi
When I update vscode to 1.17.2, get some lags on:

- scrolling the page not continuously
- html tag suggestion
- some time, when I typing code, nothing show on monitor and after 1 sec, the typed code is displayed.
- delay on opening vscode

**I did not have this problem in previous versions and my extension on new and old versions not changed.**

**Comment by dtmkeng** [comment] 2017-10-24 06:25
me to

**Comment by linxiaoru** [comment] 2017-10-24 06:29
same here!

**Comment by DrMueller** [comment] 2017-10-24 07:24
Same here!

**Comment by dbaeumer** [comment] 2017-10-25 07:25
@jrieken assigning to you for awareness. I know nothing you can fix alone.

**Comment by jrieken** [comment] 2017-10-25 08:05
Are all "me too"s @dtmkeng @linxiaoru @DrMueller also on windows and vscode 1.17.2?

**Comment by jrieken** [comment] 2017-10-25 08:07
@michaelchiche and everyone else, please create a CPU profile and attach it here. How it's down is documented here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#creating-performance-profiles

**Comment by miladghiravani** [comment] 2017-10-25 15:31
@jrieken My CPU profile:
[CPU-20171025T185931.zip](https://github.com/Microsoft/vscode/files/1415169/CPU-20171025T185931.zip)

**Comment by jrieken** [comment] 2017-10-25 16:00
@miladghiravani Thanks for the additional information... There seems to be an issue with the `tungvn.wordpress-snippet`-snippets. We have a check in place that makes sure snippets use placeholders and not variables (some an old would confuse) and when we find a snippet like that we fix it and print a warning. It seems that there is a warning avalanche causes slowness.. 

I can reproduce locally, I'll make sure to get it fixed

**Comment by jrieken** [comment] 2017-10-25 16:59
@miladghiravani This should be a lot better with tomorrows insiders

**Closed** 2017-10-25 17:00 UTC
Labels: freeze-slow-crash, perf, snippets
