### ISSUE TITLE
The new version is severly damaged

### ISSUE THREAD

**Issue by druidgrove** [microsoft/vscode#99394] opened 2020-06-04 18:06 UTC
Issue Type: <b>Bug</b>

May 2020 (version 1.46)

All,

  Once I upgraded to this release my debugging experience has gone downhill, rapidly downhill.  
1. In previous releases entering debug mode cleared caches?? of chrome, such that new sessions had updated source.  This is no longer true, in most occurences I need to manually 'empty cache hard reload' from chrome.
1. Breakpoints come and go at will, I am often unable to set a breakpoint, dim red dot=>white dot outline.  Other times breakpoints are shown but the tool stops in some other function.
1. I am unable to terminate a debug session, closing chrome or using red box of debug window produces "No debug adapter, can not send 'terminate' dialog on bottom right.
1. Selecting items in search window opens a new uneditable version of the file, even though I have a version open under editing.  It is very disruptive to find out you are unable to edit when focused on an issue.

VS Code version: Code - Insiders 1.46.0-insider (2c1871d538c64df71af4902deba47d7fa4b53f27, 2020-06-01T10:32:27.369Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (2.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.7
vscode-gpm|axe|2.3.6
gltf-vscode|ces|2.2.10
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-browser-refresh|fab|1.1.5
code-coverage|mar|1.2.1
debugger-for-chrome|msj|4.12.8
LiveServer|rit|5.6.1
standard|shi|0.2.3
vscode-3dviewer|sle|0.1.0
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by druidgrove** [comment] 2020-06-04 18:07
Also I have an irritating "Chrome didnt shut down correctly" dialog window that comes up 90% of my debug sessions.

**Comment by druidgrove** [comment] 2020-06-04 18:10
Gosh I feel like such a complainer...but the debug console only displays my console.log output about 50% of the time.  I only see

"Note: Using the "preview" debug extension""

**Comment by druidgrove** [comment] 2020-06-13 18:51
Additionally the debug console clears when chrome page removed, this often contains diagnostics I wish to view.  Console should only clear during a new debug session.

**Comment by connor4312** [comment] 2020-06-16 18:08
Thank you for the feedback!

 1. I'm not able to reproduce this. With a small react app, I can change the app and get updates when the page automatically reloads. Testing the cache on this random page shows that it seems to be disabled correctly https://www.lagado.com/tools/cache-test However, there is an option `disableNetworkCache` that can be set to `false` to prevent the cache from being disabled--did that end up in your launch config somehow?
 2. Please share your launch config and some information about your app. Also, please set `trace: true` in your launch config and share the resulting log (its location will be printed in the Debug Console) when the bug happens.
 3. Please follow the instructions to enable the trace log and share that here.
 4. It sounds like the files/paths on your remote are not mapped with those on your disk. This will also prevent breakpoints from binding. Without knowing anything about your application, the easiest way to fix this in general is to compare the paths of the readonly file with the _real_ file, and then update the `webRoot` or the sourceMapOverrides so that the paths match up.
5. "didn't shut down correctly" should be fixed as of https://github.com/microsoft/vscode-js-debug/commit/95a3b0a7151ae43dcb36237c1479e209380178e8. By default we will now only close the tabs we're attached to, which allows Chrome to shut down gracefully once there are no more tabs. However it is possible that Chrome will get killed if you close VS Code while debugging; in this case we have no opportunity to do a graceful shutdown.

    It appears there's not any flag we can pass to disable the "restore session" prompt all the time -- there is [a workaround](https://superuser.com/questions/697618/getting-google-chrome-didnt-shut-down-correctly-every-week) by munging around in the user-data-dir but that seems fragile.

6. (and 7) This should be fixed as of https://github.com/microsoft/vscode-js-debug/commit/61f45d3d3ddffe6a5de88cb66429aa9bcbdcce75, but if you continue to see it please share a trace log! 

    Note that pages can still manually use `console.clear()`, for instance Webpack likes to do this when reloading depending on your configuration. I dislike 'losing' the logs we previously had but I don't want to ignore the call. Maybe an option for it would be useful.

**Comment by lcruz4** [comment] 2020-07-01 15:09
I've also seen that starting additional debug sessions no longer works at all. There's no error or feedback it just doesn't start the second session. Had to downgrade back to 1.45 to get it to work

**Comment by connor4312** [comment] 2020-07-30 16:18
Closing due to lack of info, please let us know if you continue to run into problems

**Closed by connor4312** 2020-07-30 16:18 UTC
Labels: needs more info

**Comment by lcruz4** [comment] 2020-07-30 16:26
No longer having the issue with additional debug sessions in 1.47
