### ISSUE TITLE
Snippets - A transformation by regex and condition on a variable fed by a choice does not give the expected result

### ISSUE THREAD

**Issue by FALLAI-Denis** [microsoft/vscode#139008] opened 2021-12-13 17:02 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows 10 "1909" x64

A transformation by regex and condition based on the result of the capture by regex, on a variable fed by a choice, does not give the expected result: it is always the chosen value which is returned, never the result of the expression of the condition.

The same construction applied to an entered variable, even fed by the default value, produces the expected result.

Steps to Reproduce:

1. create these 2 snippets

```
    "usecase1": {
      "description": "regex on input value",
      "scope": "plaintext",
      "prefix": "usecase1",
      "body": [
        "${1:OK}",
        "${1/(OK)/${1:?true:false}/}"
      ]
    },
    "usecase2": {
      "description": "regex on choice value",
      "scope": "plaintext",
      "prefix": "usecase2",
      "body": [
        "${1|OK,KO|}",
        "${1/(OK)/${1:?true:false}/}"
      ]
    },
```

2. create a .txt file

3. call "usecase1" snippet and accept "OK" default value: "true" is displayed as expected

4. call "usecase1" snippet and enter a value other than "OK": "false" is displayed as expected

5. call "usecase2" snippet and select "OK" value: "OK" is displayed... "true" is expected

6. call "usecase2" snippet and select "KO" value: "KO" is displayed... "false is expected

![RegEx_on_var_choice](https://user-images.githubusercontent.com/63861965/145854281-97619104-9c54-486e-aaa3-940b79568261.gif)

**Comment by jrieken** [comment] 2021-12-15 13:59
Choice is trigger suggest again, making this snippet transformation on nested suggestions which is something that's tracked here https://github.com/microsoft/vscode/issues/112362

**Comment by jrieken** [comment] 2021-12-15 13:59
/duplicate of https://github.com/microsoft/vscode/issues/112362

**Closed** 2021-12-15 14:00 UTC
Labels: *duplicate, snippets

**Comment by FALLAI-Denis** [comment] 2021-12-15 17:48
Hi,

It doesn't seem like the same problem to me...

#112362: nested snippets
#139008: regex on placeholder with choice
