### ISSUE TITLE
Git Prompts Not Visible

### ISSUE THREAD

**Issue by ShikharVerma2002** [microsoft/vscode#136815] opened 2021-11-10 03:18 UTC
Issue Type: <b>Bug</b>

using git push, pull, fetch, etc. used to produce a username and password prompt but now does not and is stuck.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.20GB free)|
|Process Argv|--crash-reporter-id 925cfa3e-b313-4f48-9c5a-611b179da259|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3693)|
|Memory (System)|7.73GB (7.31GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.10
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
better-cpp-syntax|jef|1.15.10
vscode-clangd|llv|0.1.13
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
live-server|ms-|0.2.9
pdf|tom|1.1.0
cmake|twx|0.0.17

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by abatollo** [comment] 2021-11-10 10:49
I' m having the same problem. Any possible solutions?

**Comment by lszomoru** [comment] 2021-11-10 11:05
I believe that this is a duplicate of https://github.com/microsoft/vscode/issues/136837 which is marked as a candidate.

**Closed** 2021-11-10 11:05 UTC
Labels: git, *duplicate
