### ISSUE TITLE
No response issue when open large compressed js

### ISSUE THREAD

**Issue by sorrymeika** [Microsoft/vscode#684] opened 2015-11-26 03:39 UTC

**Comment by egamma** [comment] 2015-11-26 09:25
Please verify that this isn't the same issue as #94.

If it isn't then please attach the file so that we can reproduce.

**Comment by guan6** [comment] 2015-11-27 06:47
I have encountered the same problem. vscode trying code Highlight of large compressed js?

My English is not good.

**Comment by egamma** [comment] 2015-11-27 07:48
duplicate of #139, which is fixed by now

**Closed by egamma** 2015-11-27 07:48 UTC
Labels: needs more info

**Comment by guan6** [comment] 2015-11-27 07:53
Thank you
