### ISSUE TITLE
RTL when arabic text

### ISSUE THREAD

**Issue by TaymoorAbdeen** [Microsoft/vscode#68901] opened 2019-02-18 07:56 UTC
Issue Type: <b>Feature Request</b>

it's very imprtant if is here RTL when arabic text

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment] 2019-02-18 15:53
Duplicate of #11770

**Closed by alexandrudima** 2019-02-18 15:53 UTC
