### ISSUE TITLE
Multi-byte characters are corrupted in integrated terminal.

### ISSUE THREAD

**Issue by ShuheiUda** [Microsoft/vscode#7277] opened 2016-06-07 00:01 UTC
- VSCode Version:1.2.0
- OS Version:10.0.10586

Steps to Reproduce:

1. [View] - [Toggle Integrated Terminal]
2. run some command
3. Multi-byte characters (ex. Japanese) are corrupted

![vscode](https://cloud.githubusercontent.com/assets/16984569/15841680/fbef5090-2c8d-11e6-9c4a-0fc4870cad84.png)

**Comment by Tyriar** [comment] 2016-06-07 02:09
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-07 02:09 UTC
