### ISSUE TITLE
Debugger Variables view displays incorrect variable name after SetVariables request returns ErrorResponse

### ISSUE THREAD

**Issue by justarandomgeek** [microsoft/vscode#107520] opened 2020-09-26 23:48 UTC
Issue Type: <b>Bug</b>

When editing a variable in Variables view, if the SetVariables request returns an ErrorResponse (success=false, message:string, but no body.error object), after displaying/dismissing the error the selected variable takes the name from some other valid variable in the window, until any other action causes variables to be refreshed at which time it resumes displaying the correct label.

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:35:02.163Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (24.81GB free)|
|Process Argv|--crash-reporter-id 1d78045f-7d02-46d4-981d-e8dc1b7d9885|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.20.0
git-graph|mhu|1.26.0
remote-wsl|ms-|0.44.5
indent-rainbow|ode|7.4.0
vscode-zipexplorer|sle|0.3.1
lua|sum|0.20.8
factorio-lua-api-autocomplete|svi|0.7.0

</details>

**Comment by isidorn** [comment] 2020-09-28 09:36
That sounds strange, I do not see how a variable could get a value of some other variable. It might show a stale value, thuogh I also find that strange.

Anyways
1) Can you please fork and modify [mock debug](https://github.com/microsoft/vscode-mock-debug) such that it always returns an error in the SetVariables method and that this issue is reproducable
2) If you see this issue always you can also set a breakpoint [here](https://github.com/microsoft/vscode/blob/2eb81bd71caad429e113cfde9e1f73022135be4c/src/vs/workbench/contrib/debug/common/debugModel.ts#L249) And check how the errorMessage is being used and why the wrong thing gets rendered

**Comment by justarandomgeek** [comment] 2020-09-28 15:19
it doesn't alwasy get the *value* only the *name* -  sometimes it continues showing the *value* from before the attempt to set it (of course, the one i screenshot below it decided to take the value too!). The error message is indeed correctly displayed before this occurs. I'll look at modifying Mock to reproduce this shortly.

Before:
![image](https://user-images.githubusercontent.com/5246445/94451143-0f591180-017c-11eb-806f-d99a5d8e1d9f.png)

with error (i just keyboard smashed some invalid syntax at it):
![image](https://user-images.githubusercontent.com/5246445/94451239-27c92c00-017c-11eb-8c9c-425340c86900.png)

After error:
![image](https://user-images.githubusercontent.com/5246445/94451284-331c5780-017c-11eb-81ef-f4eb22c6b1c2.png)

**Comment by justarandomgeek** [comment] 2020-09-28 22:57
I was able to reproduce this on Mock with this branch: https://github.com/justarandomgeek/vscode-mock-debug/tree/setVariables-fail

**Comment by isidorn** [comment] 2020-09-29 09:52
Thanks. Assigning to September so I investigate further.

**Comment by isidorn** [comment] 2020-10-01 10:31
Thanks for precise repro steps.
You can try out vscode insiders from Friday and let us know if the issue is also fixed on your side. Though I checked and seems to be good now.

**Closed** 2020-10-01 10:30 UTC
Labels: debug, needs more info

**Comment by justarandomgeek** [comment] 2020-10-02 14:06
Thank you, this does indeed seem to be fixed now on today's update!

**Comment by isidorn** [comment] 2020-10-02 14:18
Great, thanks for letting us know.
