### ISSUE TITLE
Markdown preview inconsistent editor opening

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#18276] opened 2017-01-08 15:23 UTC
- VSCode Version:
  - Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z) 
  - Code - Insiders 1.9.0-insider (83db3cad0c9a05dac75a7472b3b81b39ace243f7, 2017-01-06T07:10:22.163Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions (only in stable, Insiders has non):

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-refresh-html|bajdzis|0.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.4|
|color-info|bierner|0.2.1|
|php-autocomplete|bschulte|0.4.2|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|vscode-sql-connect|dvdbrink|0.2.1|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|0.0.12|
|php-pack|felixfbecker|1.0.0|
|prettify-json|mohsen1|0.0.3|
|vscode-apache|mrmlnc|1.1.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|debugger-for-edge|msjsdiag|0.4.1|
|Spell|seanmcbreen|0.9.1|
|vscode-sql-beautify|sensourceinc|0.0.4|
|stylelint|shinnn|0.21.1|
|vscode-csstree|smelukov|0.1.6|
|twig|TwentyChung|0.0.4|

---

Steps to Reproduce:

1. Create a markdown file
2. Click on the preview icon, a new tab is opened with the preview
3. go back to the markdown file and click on preview again, it goes back to the preview tab
4. split the editor area into two halves width one panel having the code and the other the preview
5. in the preview click on the show source button, it will go to the other panel and focus the editor
6. in the editor click on preview, this will open a new tab in the same panel with the preview and not focus the already open preview

What I expect in to happen when I have split the editor is both the preview and the show source button to focus the tab when it is already open, but preview opens a new one every time and show source doesn't.

**Comment by mjbvz** [comment] 2017-02-14 01:57
Thank your for the report. This looks like a duplicate of #8581

**Closed by mjbvz** 2017-02-14 01:57 UTC
Labels: duplicate, markdown
