### ISSUE TITLE
Terminal in the editor area get blank if change the area

### ISSUE THREAD

**Issue by StephD** [microsoft/vscode#140401] opened 2022-01-10 10:05 UTC
Does this issue occur when all extensions are disabled?: Yes/No
NO, for the first bug try but yes after try the bug a second time

- VS Code Version: 1.63
- OS Version:Windows 10.0.22000
- Bash version : GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

Steps to Reproduce:
1. Open visual studio code
2. Create 2 files tab
3. Drag 1 file into another area editor (To have 2 column with each file next to each other)
4. Open a terminal into the editor area
5. Drag the terminal to the other area.

What wrong for me. The terminal line, text, output just disappear. It's like there is nothing. If I drag back the terminal into the initial area, the content come back.
I try to launch vscode without extension and there is no problem.

I use bisect to see what extension could coz the problem BUT
- Sometimes, at the first bisect run (not extension loaded), the problem appear
- Other time, everything works fine then its not working so I click on "it's bad", then it's working again so "all good", then it's not working again so "it's bad". At the end, "bisect didn't detect any extension causing the problem"
- I tried another time and It could detect an extension that cause the problem. BUT, if I relaunch vscode without this extension (not just reload), the problem persist.

I tried bisect with my project and also from "code --disable-extensions"

In the pictures. 
1. First launch of vscode without extensions
![1First inital launch from no extension](https://user-images.githubusercontent.com/1171858/148748162-edda8a1a-90ee-4521-b6b2-5e579ed9ea0d.png)
2. First try of the bug, everything working fine
![2First drag of terminal](https://user-images.githubusercontent.com/1171858/148748170-b8515c17-1d76-496f-91c4-22eaa9a4673c.png)
3. Close the bash tab only and create another terminal (Re-try the bug)
![3I closed the bash and create another one](https://user-images.githubusercontent.com/1171858/148748175-0d25fd65-fec5-4571-a614-1b566136531c.png)
4. The bug appear
![4Here is the bug](https://user-images.githubusercontent.com/1171858/148748181-0b56c4f2-0b59-48fe-ba35-d56deda49b16.png)

Am I wrong into something? Could be problem with bash? 
Thanks

**Comment by mathieug** [comment] 2022-01-10 16:15
Same issue here, for weeks, on Mac OS (https://github.com/microsoft/vscode/issues/140425)

**Comment by meganrogge** [comment] 2022-01-11 04:01
/duplicate of #139222 already fixed in insider's

**Closed by meganrogge** 2022-01-11 04:01 UTC
