### ISSUE TITLE
Explorer periodically lose focus on renaming

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode#117116] opened 2021-02-20 07:48 UTC
- VS Code Version: 
- OS Version:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce: 

1. Press F2 on any file/directory
2. Do nothing for a while
3. Focus lost

I doubt anyone can reproduce it with the description. It only occur on my particular repo, maybe even with special state. Because I cannot reproduce the state with a new folder/workspace.

The only thing I can say the cause **must** be the git extension. From `Output` tab of Git extension. I can see it periodically flush out logs and filename editing focus lost immediately before/after the flush. And the content of each flush is:
```
> git status -z -u
> git status -z -u
> git symbolic-ref --short HEAD
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Warning: Failed to watch ref '<masked out on issue reporting>/refs/remotes/origin/master', is most likely packed.
> git config --get commit.template
> git config --get commit.template
> git ls-files --stage -- <masked out on issue reporting>
> git cat-file -s 7ddad5689c1788d424ca674d4f5aa2713d447022
> git show --textconv :<masked out on issue reporting>
```

And with a notification 
`TreeError [FileExplorer] Data tree node not found: [object Object]`

Does this issue occur when all extensions are disabled?: Yes/No

I cannot do this, because I am working on a remote workspace

**Comment by isidorn** [comment] 2021-02-22 08:38
Sounds liek a duplicate of https://github.com/microsoft/vscode/issues/112293
Can you please comment on that issue, so we have all the info in one place. Thank you

**Closed by isidorn** 2021-02-22 08:38 UTC
