### ISSUE TITLE
Feature Request: Add an API event to indicate when the sidebar viewlet changes

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#38870] opened 2017-11-21 12:06 UTC
This would be useful to decide when to display other views and also so my own extension can keep track of which view is currently open 8-)

**Comment by jrieken** [comment] 2017-12-01 14:51
> other views

What other views?

**Comment by Gruntfuggly** [comment] 2017-12-01 15:11
Explorer, Search, SCM, Debug and Extensions.

**Comment by jrieken** [comment] 2017-12-01 16:00
> own extension can keep track of which view is currently open

and that? what does your extension do with it?

**Comment by Gruntfuggly** [comment] 2017-12-01 17:07
My extesion is basically a replacement for the sidebar (https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar). 

Without knowing when a view has been activated there are cases where I lose sync with highlights.

**Comment by jrieken** [comment] 2017-12-04 08:20
> Without knowing when a view has been activated there are cases where I lose sync with highlights.

Not sure what a sync-highlight is? In case you doing this commands and menu (which I doubt) then you check-out context keys: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by Gruntfuggly** [comment] 2017-12-04 08:58
My extension highlights the currently selected view in the activity bar - when the current view is changed by  a menu command, there's no way of knowing it has changed.

Thanks for the suggestion of the context keys - I've already overwritten the default keys for changing the view, but it won't work if users have changed key definitions.

**Comment by jrieken** [comment] 2017-12-04 09:57
Tricky... I am closing this duplicate of #10471. We do have context-keys, like `explorerViewletVisible` or `gitViewletVisible` which reflect the UX state and the aforementioned issue is about exposing those to the API.

**Closed by jrieken** 2017-12-04 09:57 UTC
Labels: api, needs more info, under-discussion, ux

**Comment by Gruntfuggly** [comment] 2017-12-04 11:09
This isn't about context-keys - the user can change the currently sidebar viewlet using the menu, so it's not possible to know what view is currently visible. 8-(

**Comment by jrieken** [comment] 2017-12-04 11:12
> This isn't about context-keys

It is. Please try to understand how they work and how they are used before continuing to comment

**Comment by Gruntfuggly** [comment] 2017-12-04 12:26
Please can you explain how selecting "Find in Files" from the Edit menu is affected by context-keys? 

I have looked at the documentation here:
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts
but that only seems to allow the context to be defined for key presses.

I would be grateful if you could point me to any documentation or further info - thank you for your time.
