### ISSUE TITLE
Autocomplete importing JSX components wrong result

### ISSUE THREAD

**Issue by ablakey** [Microsoft/vscode#60417] opened 2018-10-10 01:57 UTC
I updated to the latest VSCode this morning and now my import autocomplete drops in an import call rather than autocompleting the component name and adding that import to the top of the file.

![peek 2018-10-09 21-50](https://user-images.githubusercontent.com/9021944/46708615-87377580-cc0d-11e8-8337-be1f3d1c33fa.gif)

I don't have a jsconfig file. I'm pretty sure it's basically optional as I haven't needed one for the few years I've been using VSCode. Maybe that's changed.

- VSCode Version: Version: 1.28.0
- OS Version: Ubuntu 16.04

Does this issue occur when all extensions are disabled?: Yes
Also tried with insiders, same result.

**Comment by biduone** [comment] 2018-10-10 03:33
emm...... , same issues

**Comment by zfeher** [comment] 2018-10-10 08:47
The same happens with plain old function imports in a javascript project as well. To reproduce just create 2 files where one exports some function and try too import that from the other file via code completion. 

Note: that you need to create a `jsconfig.json` where `checkJs` is set to true.

**Comment by mjbvz** [comment] 2018-10-10 18:28
Duplicate of Microsoft/TypeScript#27317

**Closed by mjbvz** 2018-10-10 18:28 UTC
Labels: javascript
