### ISSUE TITLE
Duplicate window  command seems to have regression

### ISSUE THREAD

**Issue by ranoy** [microsoft/vscode#102579] opened 2020-07-15 08:49 UTC
Issue Type: <b>Bug</b>

Hi Team,
Duplicate window command seems to have regression. When I tried it it opened workspsace.json file instead of opening the workspace being duplicated

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.2.1
ng-template|Ang|0.1000.3
lit-html|bie|1.11.1
sqlformatter|bre|0.0.7
path-intellisense|chr|2.2.1
angular-schematics|cyr|4.3.0
xml|Dot|2.5.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
json2ts|Gre|0.0.6
beautify|Hoo|1.5.0
html-tag-wrapper|hwe|0.2.3
compareit|in4|0.0.2
angular2-switcher|inf|0.3.3
open-file-from-path|jac|1.3.4
Angular2|joh|9.1.2
angular-extension-pack|loi|0.7.1
Angular2Tests|Mar|0.7.3
prettify-json|moh|0.0.3
python|ms-|2020.6.91350
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
ng-fortytwo-vscode-extension|NG-|0.0.9
typescript-hero|rbb|3.0.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.8.0
angular-follow-selector|san|1.2.0
simontest|Sim|1.8.8
sonarlint-vscode|Son|1.16.0
autoimport|ste|1.5.3
move-ts|str|1.12.0
lodash-snippets|tom|1.0.0
Angular2|UVB|0.4.1
vscode-icons|vsc|10.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-07-15 08:52
/duplicate of #102148 which will be fixed in upcoming 1.47.2 recovery release.

**Closed** 2020-07-15 08:54 UTC
Labels: *duplicate, new release
