### ISSUE TITLE
Debugger does not step into correct function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127345] opened 2021-06-28 16:48 UTC
**Steps:**
* run from `main`
* open `src/vs/workbench/services/editor/test/browser/editorService.test.ts`
* add a breakpoint into [here](https://github.com/microsoft/vscode/blob/60566458924b2cb60adc1918e324762c1aa91269/src/vs/workbench/services/editor/test/browser/editorService.test.ts#L281-L281)
* right click "Debug Test" in [here](https://github.com/microsoft/vscode/blob/60566458924b2cb60adc1918e324762c1aa91269/src/vs/workbench/services/editor/test/browser/editorService.test.ts#L181-L181)
* step into `await openEditor(untypedEditor)`

=> 🐛 you end up in a weird place

![recording](https://user-images.githubusercontent.com/900690/123673969-5d9d5d00-d841-11eb-85d1-29a6f0f291a4.gif)

**Comment by bpasero** [comment] 2021-06-29 07:37
Since this makes me stop wanting to use debug in VSCode, marking as important selfhosting blocker.

**Comment by bpasero** [comment] 2021-06-29 09:03
I think this may reproduce in devtools too, so lowering severity.

**Comment by connor4312** [comment] 2021-07-06 21:57
I can reproduce this consistently as well. It seems to be a "vanilla" behavior of the version of V8 in Electron. I don't think this is feasible to correct for in the debugger, we'd need to do source analysis and manually set a breakpoint where the function exists (and that will fail if TS doesn't know where the function is declared).

![](https://memes.peet.io/img/21-07-7a5efee7-9190-4384-91c5-72bc61ad216d.png)

However, I don't reproduce it when running in real (modern) Chrome. With the introduction of test run configurations in https://github.com/microsoft/vscode/issues/127096#issuecomment-868839093, I'll have an option to run unit tests in browser to avoid this issue.

cc @deepak1556 fyi. You can close this if you don't plan to take any action here (other than pulling in Electron updates)

**Comment by deepak1556** [comment] 2021-07-07 06:17
@connor4312 which version of chrome did you test with ? Also what are the minimal steps to test this on the web, I can bisect the chrome CL that fixed it and if its minimal will backport to our current version.

**Comment by connor4312** [comment] 2021-07-07 15:33
I tested with Chrome 91, by:

1. Modify line 149 in test/unit/browser/index.js to read `const browser = await playwright[browserType].launch({ headless: !Boolean(argv.debug), devtools: Boolean(argv.debug) });` (open the devtools)
1. Add a debugger; statement before the openEditor line so you pause there
1. `yarn test-browser --browser chromium --run .\out\vs\workbench\services\editor\test\browser\editorGroupsService.test.ts --debug`
1. Try to step into the `openEditor` line that Ben showed

**Comment by deepak1556** [comment] 2021-07-08 22:43
@connor4312 the issue does not repro in chromium 89 (current runtime of vscode insiders), can you confirm if my steps are correct [recording.gif.zip](https://github.com/microsoft/vscode/files/6787645/recording.gif.zip)


You can download version 89 from https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/843806/chrome-mac.zip

**Comment by connor4312** [comment] 2021-07-09 20:48
Okay, sorry, it actually works with stepping. Updated instructions:

1. Add a debugger; statement before the openEditor line so you pause there
2. `yarn test-browser --browser chromium --run .\out\vs\workbench\services\editor\test\browser\editorGroupsService.test.ts --debug`
3. After you hit the debugger, add a breakpoint on the next line
4. Continue
5. Step in
6. Land in the wrong place

The bad news is that, with these fixed instructions, I can also reproduce it on Chrome 🙁

**Comment by connor4312** [comment] 2021-07-09 21:15
I opened a bug for this here: https://bugs.chromium.org/p/chromium/issues/detail?id=1227841

**Comment by deepak1556** [comment] 2021-07-09 21:16
Great, thanks!

**Comment by piyushsoni** [comment] 2022-01-19 05:33
Just FYI, the Chromium bug has been closed as they want a reproducible test case inside Chromium and not in VS Code.

**Closed** 2022-12-12 19:43 UTC
Labels: upstream, debug, upstream-issue-linked, chromium, papercut :drop_of_blood:
