### ISSUE TITLE
no scrollbar on terminal

### ISSUE THREAD

**Issue by IGHARARI** [microsoft/vscode#126429] opened 2021-06-16 00:54 UTC
Issue Type: <b>Bug</b>

With the new UI/UX on the terminal, the scrollbar simply does not render when using the terminal docked on the right/left side. It does show on the bottom, but not on the sides.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1049-aws

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-eslint|dba|2.1.23
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701

</details>

**Comment by IllusionMH** [comment] 2021-06-16 01:25
/needsMoreInfo

Do you have terminal tabs on the left?
Can be duplicate of #125460 which should be fixed in Insiders builds. 

Is it reproducible in Insiders build? https://code.visualstudio.com/insiders/

**Closed** 2021-06-23 11:27 UTC
Labels: needs more info

**Comment by IGHARARI** [comment] 2021-06-23 16:39
I don't know if it's fixed on the insider's build (I haven't checked) but I know that I didn't have to do anything special for it to not have a scrollbar. Open a terminal (on windows btw) on the left side, or right side (just 1) run enough commands to have text scroll, no scrollbar is ever shown.

I can move the terminal to the bottom and the scrollbar will show, but when moving it back to the left or right, it won't.
