### ISSUE TITLE
[Update] cannot update: the setup files are corrupted

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7846] opened 2016-06-18 09:35 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10

On a computer which was running an old version of VSCode, I decided to update it. When clicking on the update popup that appeared, I got the following message:

![setup](https://cloud.githubusercontent.com/assets/199648/16170125/a0c4126e-3548-11e6-9fa0-c37fdeec431d.png)

Restarting VSCode and choosing "check for updates" brings the same message again.

**Comment by joaomoreno** [comment] 2016-06-21 07:34
Duplicate of #780

**Closed by joaomoreno** 2016-06-21 07:34 UTC
Labels: important, install-update
