### ISSUE TITLE
Cannot select Source Control ... menu items

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#73218] opened 2019-05-03 09:04 UTC
Issue Type: <b>Bug</b>

When the Height of the code window is less than will allow the entire Source Code ... menu to be displayed selecting it with the pointer makes it appear then immediately dissapear. 

It's thus impossble to select anyhting on the menu. You have to resize the window or use key access. You can alos drag the pointer down after selecting the menu.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (1.35GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
spellright|ban|3.0.38
toggle-format-on-save|cbr|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.6.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
html-slim-scss-css-class-completion|gen|1.5.14
vscode-pull-request-github|Git|0.6.0
gc-excelviewer|Gra|2.1.32
vscode-firefox-debug|hbe|1.7.11
search-node-modules|jas|1.3.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.11.3
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
stylelint|shi|0.49.0
vscodeintellicode|Vis|1.1.5
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2019-05-03 10:32
@SteveALee do you mean this?

![image](https://user-images.githubusercontent.com/6726799/57132230-d5bd8480-6d96-11e9-922a-3edd4b15e271.png)

Seems OK for me. Did you try running with all your extensions disabled?

![image](https://user-images.githubusercontent.com/6726799/57132317-1e753d80-6d97-11e9-9657-ba37ceb8c2c6.png)

**Comment by SteveALee** [comment] 2019-05-03 12:36
gjsjohnmurray yes but I have moved the entire have panel to the right side. Perhaps that is it as constrained in both directions?

I should have tried extension disable, sorry.will do when back on device.

**Comment by gjsjohnmurray** [comment] 2019-05-03 12:45
@SteveALee yes, I can repro it with `"workbench.sideBar.location": "right"`

**Comment by sbatten** [comment] 2019-05-06 18:34
@SteveALee I use right as the sidebar location as well but I don't have any issues when the height is too small, only the width. Can you share a screenshot of your window dimensions?

**Comment by SteveALee** [comment] 2019-05-07 08:15
@sbatten Sure. It's like this on both my monitors.

While doing this I found it requires code to be maximised in order to fail

![image](https://user-images.githubusercontent.com/618922/57284203-977ed880-70a8-11e9-8220-706a958a3be2.png)

**Comment by sbatten** [comment] 2019-05-07 17:44
Finally got it to reproduce. I think this may have been resolved by @joaomoreno  in Insiders. The menu now offsets to the left of the source control menu button so this doesn't happen.

@joaomoreno can you confirm if you made a fix here? Behavior seems to be different between Stable and Insiders.

**Comment by joaomoreno** [comment] 2019-05-09 07:50
@sbatten Unfortunately I haven't worked on this lately... Not sure why stable is different than insiders.

**Comment by sbatten** [comment] 2019-05-09 18:57
@joaomoreno figured it out, there is a difference between the two because my insiders has gitlens in the scm view and my stable has the separate view. When the toolbar is the only one in the view, it misbehaves. When there are multiple viewlets in the view, it works as desired

**Comment by SteveALee** [comment] 2019-05-09 19:12
Sorry to be that guy, but I have gitlens installed and DO get the problem.

To recap it only happens for when:

* Panel is on the right and
* code is exactly full screen height (eg maximized) and
* screen resolution is such that menu does not fit vertically

**Comment by SteveALee** [comment] 2019-05-09 19:13
I might not be understanding what "in the scm view" means.

**Comment by sbatten** [comment] 2019-05-09 21:13
@SteveALee you can opt to have gitlens put its views inside the SCM Viewlet instead of in its own view.

![image](https://user-images.githubusercontent.com/6561887/57487083-7cf15e80-7264-11e9-8740-d6ae9912e909.png)

Notice how the triple dot menu does not render unless hovered in this case. This toolbar behaves differently than the default setup.

**Comment by SteveALee** [comment] 2019-05-10 07:49
@shatter, ah thanks. Useful! With so many options in all the extensions I no longer find the time to scan the options, however useful they may be.

**Closed** 2019-05-23 09:08 UTC
Labels: bug, workbench-menu
