### ISSUE TITLE
Debug popovers do not work for class' fields/properties

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/vscode#7087] opened 2016-06-01 06:46 UTC
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.5

When debugging a unity project, debug popovers do not seem to be working for a class' fields/properties, but do work for local variables:

Hovering over the local variable `schedule` correctly shows its value:
![image](https://cloud.githubusercontent.com/assets/1172479/15700510/9760d532-27aa-11e6-9308-cd8a61921d43.png)

Hovering over the private field `data` does nothing, but it's values do appear on the left panel:
![image](https://cloud.githubusercontent.com/assets/1172479/15700567/fdd69b62-27aa-11e6-8d19-055cf00ef430.png)

Sorry if duplicate!

**Comment by isidorn** [comment] 2016-06-01 08:07
Dupe of https://github.com/Microsoft/vscode/issues/6042
As explained in that issue our hover logic is very limited atm. The issue here is that data property lives inside another `non-public members` property.

**Closed by isidorn** 2016-06-01 08:07 UTC
