### ISSUE TITLE
UI: Make workspace/foldings settings reflect more clearly true/false/unchanged

### ISSUE THREAD

**Issue by sliedes** [microsoft/vscode#219676] opened 2024-07-02 12:02 UTC
This issue is somewhat related to #188612, but I'd like to propose this as a mostly UI change to make the current functionality more clear.

Currently, for workspace or folder settings, we can see _(Modified elsewhere)_ for settings which have been set in the **User** settings:

![image](https://github.com/microsoft/vscode/assets/2307997/3a09dc4e-c181-402f-8c35-2a69b44ca80d)

It seems a bit unclear to me what the values of a checkbox actually mean in **Workspace** settings. My mental model, possibly wrong, is that the **Workspace** settings selectively override **User** settings. Generally, I would expect to have approximately three kinds of values (for boolean settings) in **Workspace** settings: **set to true at this level**, **set to false at this level**, and **leave unchanged** (which might be shown as **true** or **false** as inherited, though I'd hope in a different way than the previous two).

Instead, I see this, for example, for **Text Editor -> Multi-File Diff Editor**:

### User

[✔] Experimental: Enabled
[ ] Minimap: Autohide
[✔] Minimap: Enabled

### Workspace

[✔] Experimental: Enabled 
[ ] Minimap: Autohide
[✔] Minimap: Enabled

## Step 1

Now, in **User**, I unset **Experimental: Enabled**:

### User

[ ] Experimental: Enabled
[ ] Minimap: Autohide
[✔] Minimap: Enabled

### Workspace

[✔] Experimental: Enabled _(Modified in User)_
[ ] Minimap: Autohide
[✔] Minimap: Enabled

**Comment:** What does having the checkmark in **Workspace**'s version of **Experimental: Enabled** mean? I would expect it to mean that the setting is **true** at the **Workspace** level, either because it's overridden at the **Workspace** level or because it was inherited (though again I'd love the UI to distinguish between these). Though, to the best of my understanding, that setting actually is **false** at the **Workspace** level despite this checkbox mark, which I find very confusing; `workspace.json` does not contain the setting **multiDiffEditor.experimental.enabled**, and it is disabled at the **User** settings level.

## Step 2

I untoggle and retoggle **Workspace -> Experimental: Enabled** (i.e. click twice on the setting). Now, I have:

### User

[ ] Experimental: Enabled
[ ] Minimap: Autohide
[ ] Minimap: Enabled

### Workspace

[ ✔] Experimental: Enabled _(Also modified in User)_
[✔] Minimap: Autohide
[ ] Minimap: Enabled

(and now `workspace.json` shows the setting).

**Comment:** So, presumably in this case the word "also" is supposed to alert me to the fact that I have changed this setting here.

## Step 3

I untoggle **User->Experimental: Enabled**. Now I have:

### User

[ ] Experimental: Enabled _(Modified in Workspace)_
[ ] Minimap: Autohide
[✔] Minimap: Enabled

### Workspace

[ ✔] Experimental: Enabled
[ ] Minimap: Autohide
[✔] Minimap: Enabled

**Comment:** Apart from the _Modified in Workspace_ in **User** settings, this looks identical to Step 0. Now, though, the setting is **true** (set in `workspace.json`). I find it baffling that there is no difference in **Workspace** settings to Step 0 despite 1) me having changed that setting in **Workspace**; 2) that setting actually ending up being **true** instead of **false** in the **Workspace** level.

---

**Analysis:** To me, as a programmer, it would be clearest to think of the settings at the deeper levels (i.e. Workspace and Folder) as one of these options:

1. Set to true at this level
2. Set to false at this level
3. Inherit setting (which the UI should perhaps display distinctly as inherited as false or inherited as true)

Or for non-boolean settings,

1. Set to value X
2. Inherit setting (which the UI should show differently from the setting being set to that value at this level)

(and possibly a _reset to default at this level_ setting, but I think that's a different wishlist item).

**Comment by rzhao271** [comment] 2024-07-02 15:06
Near-duplicate of https://github.com/microsoft/vscode/issues/58038. Also see https://github.com/microsoft/vscode/issues/58038#issuecomment-1810678997.

Step 3 differs from Step 0 because the workspace setting has the modified indicator (blue bar) to the left of it, but I agree that the UI is very confusing.

**Comment by rzhao271** [comment] 2024-12-09 22:43
Closing in favour of #58038.

**Closed by rzhao271** 2024-12-09 22:43 UTC
