### ISSUE TITLE
Return Blue icon, please :( :'(

### ISSUE THREAD

**Issue by AnastasiyaFatPanda** [Microsoft/vscode#37585] opened 2017-11-03 06:58 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.4.2
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
auto-close-tag|for|0.5.2
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.4.0
code-settings-sync|Sha|2.8.4
open-in-browser|tec|1.1.0
gitblame|wad|2.2.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Stone-Zeng** [comment] 2017-11-03 07:18
It will be changed. Duplicate of #35783

**Closed** 2017-11-03 08:09 UTC
Labels: extensions
