### ISSUE TITLE
TypeScript: autocomplete not working for object parameters when called by "this." inside of its method

### ISSUE THREAD

**Issue by Arctomachine** [microsoft/vscode#138469] opened 2021-12-05 18:27 UTC
Issue Type: <b>Bug</b>

0. Create interface for object: foo, bar, getFooBar()
1. Create object. Autocomplete works for assignation of properties
![step1](https://user-images.githubusercontent.com/29041820/144758824-a81142aa-b0d4-4286-8f80-bd348c13884d.PNG)
2. Edit method. Try to call this.foo or this.bar. Autocomplete is not working
![step2](https://user-images.githubusercontent.com/29041820/144758857-0533ed58-527c-4492-baea-c1ee2da6be60.PNG)

Note: it works for JS.
![js - works](https://user-images.githubusercontent.com/29041820/144758867-5046130f-d3e2-4763-8bf5-428eea573eb3.PNG)

TypeScript: version 4.5.2, global installation via npm

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.45GB free)|
|Process Argv|--crash-reporter-id c3923252-f4c7-41d4-9c5b-cc258f8d34c9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
python-preview|don|0.0.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
elixirlinter|iam|0.4.1
elixir-ls|Jak|0.9.0
volar|joh|0.29.8
paste-html-as-jsx|leo|0.3.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vscode-react-native|msj|1.8.1
ruby|reb|0.28.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.14
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by mjbvz** [comment] 2021-12-06 17:31
Duplicate of https://github.com/microsoft/TypeScript/issues/22058

**Closed by mjbvz** 2021-12-06 17:31 UTC

**Comment by Arctomachine** [comment] 2021-12-13 15:49
Since this issue is known for almost 3 years by now, has any action been taken to resolve it in meantime?

**Comment by mjbvz** [comment] 2021-12-14 00:51
Try posting over on TypeScript
