### ISSUE TITLE
Better support to run VS Code via Wayland

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/vscode#1739] opened 2016-01-02 03:21 UTC
Upon opening VS Code with Wayland (tested with GNOME 3 and Sway), I get a message saying `Something has gone wrong.`. 

![screenshot from 2016-01-02 03-15-38](https://cloud.githubusercontent.com/assets/7232674/12073053/33971be6-b0ff-11e5-8444-ea2fe29ab5fe.png)

```
~ > visual-studio-code
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
```

If I close the error window instead of logging out, VS Code starts up fine.

![screenshot from 2016-01-02 03-15-46](https://cloud.githubusercontent.com/assets/7232674/12073054/33f1912a-b0ff-11e5-89e6-4ec808ee131a.png)
![screenshot from 2016-01-02 03-15-57](https://cloud.githubusercontent.com/assets/7232674/12073055/3464e24c-b0ff-11e5-8064-f370b611ad79.png)

**Comment by bpasero** [comment] 2016-01-03 12:12
@Manouchehri so you have wayland extension installed and this causes code to not start properly? I am having difficulties to understand if this is a bug in wayland or code.

**Comment by joaomoreno** [comment] 2016-01-05 09:00
Seems dupe of #1733

**Comment by Manouchehri** [comment] 2016-01-05 09:05
@bpasero Not sure what you mean by 'wayland extension'. Wayland isn't an extension, it's a display server protocol. VS Code does start, but I get that error message on every start and I have to close it to continue.

@joaomoreno I'm not sure, that seems unrelated to me. Despite the error message, my terminal does not freeze and continues to work fine.

**Comment by bpasero** [comment] 2016-01-05 17:02
@Manouchehri my feeling is that we do not support launching VS Code through wayland. We need to investigate more into that but for now only a bare Linux is supported.

**Comment by Manouchehri** [comment] 2016-01-05 17:09
@bpasero The thing is that it actually works perfectly, it's just that weird error message on startup that has to be closed out.

**Comment by bpasero** [comment] 2016-01-05 18:03
Help wanted :)

**Comment by jhasse** [comment] 2017-04-07 12:38
This should be fixed as soon as Chromium / Electron gets native Wayland support: https://bugs.chromium.org/p/chromium/issues/detail?id=578890

**Comment by karataliu** [comment] 2017-07-27 05:19
Just tried VSCode 1.14.2, it can almost work well on wayland 1.13.0 + sway 0.13.0.

The only pain point now is that the mouse pointer occasionally disappeared in main editor area.
By moving it to the the Activity bar and back can sometimes get the mouse back.

**Comment by bpasero** [comment] 2017-11-16 11:52
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Closed by bpasero** 2017-11-16 11:52 UTC
Labels: feature-request, linux, workbench

**Comment by jacktho** [comment] 2017-11-16 13:02
I recently tried 1.18 with Wayland and Gnome. I did not notice any issues including the cursor issue @karataliu experienced.

Note: I went back to Xorg for unrelated reasons so my testing time was limited.

**Comment by rightaway** [comment] 2017-12-02 14:00
@jacktho Why did you need to go back to Xorg?
