### ISSUE TITLE
Pyspark output table messed up

### ISSUE THREAD

**Issue by ismailymendes** [microsoft/vscode#144766] opened 2022-03-09 15:26 UTC
- VS Code Version: 1.65.1 (user setup)
- OS Version: Windows 10 21h2 19044.1566
- PySpark Version: 3.1.2

When using the command df.show() from pyspark, I get the following output with the table kinda messed up.
![vscodewrong](https://user-images.githubusercontent.com/28030782/157469036-c371875b-c008-444e-bf99-f12c6ca7e8a4.png)

But with VS Code Version 1.64.2 I get the perfect output with columns aligned correctly.
![vscoderight](https://user-images.githubusercontent.com/28030782/157471566-85f9cee2-2eb0-4faf-8e27-bc0837695d7a.png)

Is there a workaround for this? It looks like the new Vs Code uses a different font in the output.

**Comment by gjsjohnmurray** [comment] 2022-03-09 16:49
/duplicate of #143538 and will be fixed in upcoming 1.65.2

**Closed** 2022-03-09 16:49 UTC
Labels: *duplicate, new release
