### ISSUE TITLE
In VSC 1.40, window titles are missing in accessibility apps

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#84195] opened 2019-11-08 03:27 UTC
Issue Type: <b>Bug</b>

I use a program called [Witch](https://manytricks.com/witch/), on my Mac, to navigate between windows. It is useful for jumping to a specific VS Code window. The window's title appears in Witch, which is usually the workspace for that window.

However, since upgrading to VS Code 1.40.0, all window titles only appear as "(Untitled)". Was there a change regarding this recently? Perhaps related to Electron? This issue seems to affect any Mac app that relies on OS accessibility features to access a window's title.

To reproduce this issue, you must be using VSC 1.40, and have at least two windows open in VSC. Their titles will then appear as "(Untitled)" in any of a number of Mac accessibility apps, including Witch. I already tested with all extensions disabled. I tested with latest Insiders as of 2019-11-08. The issue does not exist in VSC 1.39.2.

**This setting *must* be enabled to cause this issue:**

```json
"window.newWindowDimensions": "maximized"
```

I'm on MacOS 10.14.6 (18G1012).

Screenshot:

![Witch screenshot](https://user-images.githubusercontent.com/343940/68447361-a9ebe300-01ad-11ea-8af9-04d407d4bc60.png)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment] 2019-11-08 09:37
@deepak1556 we do give the window a title here:

https://github.com/microsoft/vscode/blob/15bfc4022232afb4de238334b02e03919dcd73ea/src/vs/code/electron-main/window.ts#L129

I am not sure why "Untitled" would show up, but possibly a E6 regression in this case. 

@garyking do you see the same with other electron app, e.g. try Electron Fiddle: https://electronjs.org/fiddle

**Comment by OliverJAsh** [comment] 2019-11-08 14:37
Also seeing the same regression, except I'm using [Contexts](https://contexts.co/) instead of Witch.

**Comment by bpasero** [comment] 2019-11-08 14:56
@OliverJAsh @garyking do you see the same when you run a different Electron application such as Electron Fiddle: https://electronjs.org/fiddle

**Comment by OliverJAsh** [comment] 2019-11-08 15:20
The title seems to work with that:

<img width="717" alt="Screenshot 2019-11-08 at 15 19 19" src="https://user-images.githubusercontent.com/921609/68487587-43ada180-023b-11ea-864c-47e4100dc151.png">

**Comment by antonblock** [comment] 2019-11-08 17:49
Also seeing this with Contexts on MacOS 10.15.1. It began after upgrading to 1.40.0 yesterday.

![image](https://user-images.githubusercontent.com/1297166/68498947-160a2d80-0226-11ea-8c08-cc97be802e6a.png)

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by ltd** [comment] 2019-11-08 19:12
Also, seeing this with my hammerspoon scripts.  began with 1.40.0

**Comment by garyking** [comment] 2019-11-08 20:31
In the Mac Accessibility API, Witch retrieves the `AXTitle` property, which contains the window title. It seems like, in the case of VSC, the `AXTitle` property is blank. Other Electron apps, including Fiddle and Atom, have a proper `AXTitle` value for their windows.

**Comment by cscalfani** [comment] 2019-11-08 22:44
I'm seeing this in Witch too.

**Comment by bpasero** [comment] 2019-11-11 17:47
We do set the title in VSCode in 2 places:
* upon window creation: https://github.com/microsoft/vscode/blob/33e5678363c20a7ac6665cc88752ee00fc83cc0d/src/vs/code/electron-main/window.ts#L129
* each time the active editor changes we update the `window.title` element : https://github.com/microsoft/vscode/blob/33e5678363c20a7ac6665cc88752ee00fc83cc0d/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L215

I am not sure if there is a third place where we have to call something. What I wonder: are maybe certain characters not allowed in this value for screen readers? Dos it reproduce if you configure window.title to a fixed value such as: `"window.title": "vSCode"`

**Comment by OliverJAsh** [comment] 2019-11-11 17:57
> Dos it reproduce if you configure window.title to a fixed value such as: `"window.title": "vSCode"`

I just tried that with the title `foo` and I can still reproduce this bug.

**Comment by bpasero** [comment] 2019-11-11 18:10
Adding "help wanted" if someone wants to chime in and has an idea.

**Comment by cscalfani** [comment] 2019-11-11 20:30
Is `AXTitle` set anywhere? That's what Witch uses.

**Comment by bpasero** [comment] 2019-11-12 07:12
Well, if so it would need to be some API that we can use. I do not recall any explicit API in Electron that would set this but would assume the window title would just work.

**Comment by bpasero** [comment] 2019-11-12 07:12
Electron sources are here: https://github.com/atom/electron but they depend on all of Chromium too....

**Comment by jdecaron** [comment] 2019-11-12 15:44
I had this bug with Contexts, my other applications were fine. I reverted to 1.39 and it's working again. I confirm that this bug was introduced by 1.40.

**Comment by garyking** [comment] 2019-11-12 17:45
If someone has time, please consider finding the VSCode commit that introduced this bug, using `git bisect`. I currently have Node 12 installed, and am unable to setup `nvm`, so I can't build a VSC version older than 1.40.

**Comment by bpasero** [comment] 2019-11-12 17:54
@garyking you should be able to by just changing our warning in the build scripts, I think it would still work.

**Comment by garyking** [comment] 2019-11-12 19:58
I removed the check for the installed Node version in `build/npm/preinstall.js`, but building 1.40.0 showed a lot of errors.

**Comment by bpasero** [comment] 2019-11-13 06:30
Can you share?

**Comment by garyking** [comment] 2019-11-13 19:24
Here's what I did:

1. Check out `1.39.2` tag in Git.
2. Comment out in `preinstall.js`:

```js
const majorNodeVersion = parseInt(/^(\d+)\./.exec(process.versions.node)[1]);

if (majorNodeVersion < 8 || majorNodeVersion >= 11) {
	console.error('\033[1;31m*** Please use node >=8 and <11.\033[0;0m');
	err = true;
}
```

3. Run `yarn install`.
4. Run `./scripts/code.sh`.
5. Error:

```
gary@gary-mac:~/Downloads/Unsorted/cloned/vscode$ ./scripts/code.sh
[14:21:37] Using gulpfile ~/Downloads/Unsorted/cloned/vscode/gulpfile.js
[14:21:37] Starting 'electron'...
[14:21:37] Starting clean-electron ...
[14:21:37] Finished clean-electron after 89 ms
[14:21:37] Starting electron ...
[14:21:40] Finished electron after 3859 ms
[14:21:40] Finished 'electron' after 3.96 s
[14:21:42] Syncronizing built-in extensions...
[14:21:42] You can manage built-in extensions with the --builtin flag
[14:21:42] Downloading extension: ms-vscode.node-debug@1.38.8 ...
[14:21:42] Downloading extension: ms-vscode.node-debug2@1.39.1 ...
[14:21:42] [marketplace] ms-vscode.references-view@0.0.30 ✔︎
[14:21:42] [marketplace] ms-vscode.node-debug ✔︎
[14:21:43] [marketplace] ms-vscode.node-debug2 ✔︎
./.build/electron/Code - OSS.app/Contents/MacOS/Electron[8229]: ../../third_party/electron_node/src/node_file.cc:897:void node::fs::InternalModuleStat(const FunctionCallbackInfo<v8::Value> &): Assertion `args[0]->IsString()' failed.
 1: 0x10c15e515 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10c15d039 node::AddPromiseHook(v8::Isolate*, void (*)(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>, void*), void*) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10c191db6 node::DecodeWrite(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10849f0a8 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1084689bd v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x108467fca v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x108daf9ce v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Users/gary/Downloads/Unsorted/cloned/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x20b70f5886a6
 9: 0x20b70f5886a6
Received signal 6
 [0x0001091edb0c]
 [0x0001091ed9f1]
 [0x7fff74444b5d]
 [0x7ffee9d50ea0]
 [0x7fff742fe6a6]
 [0x00010c15e522]
 [0x00010c15d039]
 [0x00010c191db6]
 [0x00010849f0a8]
 [0x0001084689bd]
 [0x000108467fca]
 [0x000108daf9ce]
 [0x20b70f5886a6]
 [0x20b70f5886a6]
[end of stack trace]
Abort trap: 6
gary@gary-mac:~/Downloads/Unsorted/cloned/vscode$
```

**Comment by deepak1556** [comment] 2019-11-13 19:45
@garyking all the steps look ok, i think you have the sources already compiled since I don't see any compile step in `./scripts/code.sh` step ?, can you run `git clean -xfd` and rerun steps 1-5 again ?

**Comment by garyking** [comment] 2019-11-13 21:18
@deepak1556 Thanks that fixed it. It still takes about 10 minutes to build, each time I check out a commit, but it's better than nothing...

@bpasero This bug was introduced in this commit: https://github.com/microsoft/vscode/commit/23956cc5e22616a90e01fa639d12b920ea77566d

I'm not sure if the bug was introduced by the Electron upgrade, or any of the other changes made in the commit, but that's beyond my expertise at this point...

**Comment by bpasero** [comment] 2019-11-14 06:11
@garyking thanks for verifying this is due to the Electron 6 update. I am still open to suggestions how to fix this then, given it is not coming from VSCode's own sources.

**Comment by garyking** [comment] 2019-11-14 17:41
I assume the issue is a combination of things with VSC and Electron, since the issue does not reproduce in other Electron apps.

**Comment by cscalfani** [comment] 2019-11-16 21:10
In the meantime, you can use ^W to switch windows inside of VSCode.

**Comment by yoadsn** [comment] 2019-11-18 19:00
I use Contexts so suffer as well... BUT I used to use HyperSwitch - reinstalled and tested it - still shows the correct titles with VSC 1.4.
So, either Witch and Contexts should do whatever HyperSwitch does or someone has to nose dive into Electron V4-V6 diffs.. including Chromiums libs.. 😱

**Comment by nyrf** [comment] 2019-11-28 18:54
Have some problem with Contexts.

**Comment by jryans** [comment] 2019-12-10 20:32
This appears to be regression upstream with Electron. I have submitted https://github.com/electron/electron/pull/21462 with a potential fix, so hopefully that can land, be backported, and then we can update VS Code with the fixed version.

To summarise the problem, Electron's `AtomNSWindow` [implements](https://github.com/electron/electron/blob/a6d142a112ccc0cecd33c83ff59479f4485614ba/shell/browser/ui/cocoa/atom_ns_window.mm#L105) `accessibilityAttributeValue` to provide various accessibility info to the OS, including window titles.

Chromium 75 [changed to](https://chromium.googlesource.com/chromium/src/+/69a6b7a326b993bb2faa33ae93ccc80101719d35%5E%21/) Apple's [newer accessibility API](https://developer.apple.com/documentation/appkit/nsaccessibility?language=objc) for window titles in the super class that `AtomNSWindow` inherits from. macOS still supports both the old and new style APIs, but it will prefer the new style if it is implemented. This means the Electron window title is being ignored because the newer API at the Chromium level has taken precedence.

This is a regression has been present since Electron 6.0.0 (the first release including the Chromium change above).

**Comment by bpasero** [comment] 2019-12-11 06:19
@jryans thanks a lot ❤️

**Comment by yoadsn** [comment] 2019-12-12 14:49
@jryans Thank You! One thing I can't figure out is how one application (Hyper-Switch) is able to show the titles and another (Contexts and more..) cannot.
If it's OSX that ignores the titles - all external applications should not be able to access this information.
Any idea?

**Comment by jryans** [comment] 2019-12-12 15:02
Hard to be sure without reversing each app... but at least on my system, the window title was correct in window managers such as the built-in Mission Control view but empty via accessibility APIs. So, Contexts and other affected apps are presumably using accessibility, while HyperSwitch must be using some other data source perhaps like Mission Control does.

**Comment by sergei-dyshel** [comment] 2019-12-12 21:29
@yoadsn 
Accessibility API ([`NSAccessibilityTitleAttribute`](https://developer.apple.com/documentation/appkit/nsaccessibilitytitleattribute?language=objc))isn't the only way to get window title. There is also [`CGWindowListCopyWindowInfo`](https://developer.apple.com/documentation/coregraphics/1455137-cgwindowlistcopywindowinfo) which does report correct title of vscode windows and may be probably used by HyperSwitch.

**Comment by rg-manytricks** [comment] 2019-12-13 20:17
> @yoadsn
> Accessibility API ([`NSAccessibilityTitleAttribute`](https://developer.apple.com/documentation/appkit/nsaccessibilitytitleattribute?language=objc))isn't the only way to get window title. There is also [`CGWindowListCopyWindowInfo`](https://developer.apple.com/documentation/coregraphics/1455137-cgwindowlistcopywindowinfo) which does report correct title of vscode windows and may be probably used by HyperSwitch.

The problem with that method is that it doesn't allow interactions with the window—closing, minimizing, etc. must be done via Accessibility. So for our app Witch, it's a non-solution, unfortunately.

-rob.

**Comment by mjclemente** [comment] 2019-12-13 20:41
@rg-manytricks Huge fan of your app - use it constantly - hoping the upstream fix resolves this. It's really frustrating.

**Closed** 2019-12-14 01:08 UTC
Labels: electron, electron-6.0.x-update, help wanted, needs more info, upstream

**Comment by ltd** [comment] 2019-12-17 06:55
confirm, seeing titles in the latest insider build.

**Comment by ariofrio** [comment] 2020-01-09 16:12
FWIW, this also affects conditional activation groups in BetterTouchTool.
