### ISSUE TITLE
Chinese font-rendering error with the "window.titleBarStyle": "custom"

### ISSUE THREAD

**Issue by lyhzh** [Microsoft/vscode#53672] opened 2018-07-06 08:22 UTC
- VSCode Version: Visual Studio 1.25
- OS Version: Windows 10

When " window. titlebar style": " custom", the menu text in the secondary menu and edit area of the menu bar is too sharp.

当 "window.titleBarStyle": "custom" 时 ， 菜单栏的二级菜单和编辑区域的菜单文本过于锐利

![secondary menu 1](https://img.vim-cn.com/b6/00ab61b98ac880b26336a1822b71867fb4ca2a.png)
![secondary menu 2](https://img.vim-cn.com/a5/ffb17ff0d72cfeaa39e04028f6481e671e55d8.png)
![edit area menu](https://img.vim-cn.com/60/3a27506f36216223d18bd5c67c4eb955e7246b.png)

**Comment by sbatten** [comment] 2018-07-09 18:49
related to #52537

**Comment by Tyriar** [comment] 2018-07-09 20:29
This may be a duplicate of https://github.com/Microsoft/vscode/issues/53076 actually?

**Comment by sbatten** [comment] 2018-07-30 03:45
font size was adjusted to be higher earlier in the milestone so this should solved. Thanks for the information.

**Closed by sbatten** 2018-07-30 03:45 UTC
Labels: bug, workbench-menu
