### ISSUE TITLE
[VSC-Web] Service Workers blocked due to "3p" domain

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#194002] opened 2023-09-25 15:38 UTC
See: [https://github<i>.</i>com/microsoft/vscode/issues/142813#issuecomment-1598095339](https://github.com/microsoft/vscode/issues/142813#issuecomment-1598095339)

&#x2D;---

Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Embedder: vscode.dev

**Comment by mjbvz** [comment] 2023-09-25 16:47
Duplicate of https://github.com/microsoft/vscode/issues/142813#issuecomment-1598095339

We use a third party domain to keep webviews isolated from the main VS Code window

**Closed by mjbvz** 2023-09-25 16:47 UTC
Labels: triage-needed
