### ISSUE TITLE
Parameter hints should prefer to not obscure code above the typed code

### ISSUE THREAD

**Issue by AndrejMitrovic** [microsoft/vscode#224608] opened 2024-08-02 17:13 UTC
Here is an example of two pop-ups based on the scrolling position in the buffer:

### Example 1:

![Capture](https://github.com/user-attachments/assets/0785dede-5991-4409-9ebd-d1d4189e3e3d)

This is the most common example that occurs for me. Here I wanted to log out the parameters of a function but the popup obscures the list of parameter names.

### Example 2:

![Capture2](https://github.com/user-attachments/assets/66d69872-b327-4501-95d6-580ee0c29e4c)

In this example the pop-up happened to occur below the code. 

But this version is fine. It makes sense to show the popup below the code. Because I typically can't pass in arguments that are declared **below** or **after** the piece of code I'm writing. At least this is true in most procedural languages like Javascript.

There's a few reasons this is a nagging problem:
- The Escape key doesn't make the popup go away. Instead I have to either physically click on it before I can press Escape to hide it, or just click somewhere else to hide it. It's annoying.
- There is no transparency options for the popup. At least this would alleviate the issue a bit.

I do not want to disable parameter hints because they're very useful. But when the popup constantly obscures variables and symbols that I'm trying to pass into the function it makes this feature annoying to use.

**Comment by mjbvz** [comment] 2024-08-05 20:12
Duplicate of #33752

**Closed by mjbvz** 2024-08-05 20:12 UTC
Labels: editor-parameter-hints
