### ISSUE TITLE
Smoke Test fails: CSS - verifies that warning becomes an error once setting changed failed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#67746] opened 2019-02-01 14:19 UTC
It failed for me under Windows 3 times out of three runs.

**Comment by dbaeumer** [comment] 2019-02-01 14:19
Test manually with @aeschli and it works

**Comment by aeschli** [comment] 2019-02-26 11:14
Problem is with `settingsEditor.addUserSetting`
`{}"css.lint.emptyRules": "error"`

Only seems to happen on Dirks machine, works for me on Linux and Windows

**Comment by aeschli** [comment] 2019-10-09 20:36
Closing as not reproducible

**Closed by aeschli** 2019-10-09 20:36 UTC
