### ISSUE TITLE
Extension activation failure notification is not helpful in restricted mode

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125418] opened 2021-06-03 17:42 UTC
Without customizing settings, after opening an empty window, I get this

![image](https://user-images.githubusercontent.com/876920/120688629-1e553980-c458-11eb-983c-d21e4d819d1a.png)

The `git` extension is probably disabled because of trust, but the notification asks me to enable and reload, after clicking on the button, I get another notification.

![image](https://user-images.githubusercontent.com/876920/120688665-26ad7480-c458-11eb-9089-da260c5ba9d1.png)

**Comment by lszomoru** [comment] 2021-06-03 17:50
/duplicate

Duplicate of #122448

**Closed** 2021-06-03 17:50 UTC
Labels: *duplicate, bug, workspace-trust
