### ISSUE TITLE
js 提示问题

### ISSUE THREAD

**Issue by spitWind** [Microsoft/vscode#44800] opened 2018-03-01 08:23 UTC
### Issue Type
Bug

### Description

var a={};
a.b=new Date();
a.b.//
无法对b 的类型进行提示

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|Memory (System)|7.89GB (2.98GB free)|
|Process Argv|F:\Program Files (x86)\MicrosofVC\Code.exe|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
docthis|joe|0.6.0
typings-autoinstaller|jvi|1.2.0
node-module-intellisense|lei|1.5.0
cpptools|ms-|0.15.0
ejs-language-support|Qas|0.0.1
prettify|whi|0.0.2

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-03-01 08:29
Duplicate of https://github.com/Microsoft/TypeScript/issues/10868

**Closed by mjbvz** 2018-03-01 08:29 UTC
