### ISSUE TITLE
Task dependants

### ISSUE THREAD

**Issue by guestieng** [microsoft/vscode#119172] opened 2021-03-17 10:46 UTC
For a "task" one can define a "dependsOn" array, 
the listed tasks of which are performed beforehand.

Now, it would be nice to also allow something like this the other way around:
being able to define an array like "dependants" in which one can list tasks that are performed
in dependence on the current one, i.e., afterwards.

Otherwise, I see that one can define "wrapping" tasks which may only contain a corresponding "dependsOn" array.
But then it would helpful to allow for defining locally and globally available tasks ("private" or "global"), i.e. the opportunity to "hide" tasks outside of a "tasks array" scope.

**Comment by alexr00** [comment] 2021-03-17 11:52
duplicate of https://github.com/microsoft/vscode/issues/117823

**Closed by alexr00** 2021-03-17 11:52 UTC
