### ISSUE TITLE
New CSS property "contain"

### ISSUE THREAD

**Issue by acupofspirt** [Microsoft/vscode#14439] opened 2016-10-25 14:06 UTC
- VSCode Version: 1.6.1
- OS Version: Win 7 SP1

Steps to Reproduce:

1. Open any .css file.
2. Write 'contain: ...'.
3. Get warning "[css] Unknown property".

According to [spec](https://drafts.csswg.org/css-containment) we've got new CSS property 'contain'. Yep, I know that it's draft still, but people are already using it in production and they don't want to get warnings about that. Can you add this property to whitelist?

**Comment by aeschli** [comment] 2016-10-26 10:37
duplicate of #10840

**Closed by aeschli** 2016-10-26 10:37 UTC
