### ISSUE TITLE
not able to  authenticate github

### ISSUE THREAD

**Issue by aknain** [microsoft/vscode#106815] opened 2020-09-16 02:35 UTC
Issue Type: <b>Performance Issue</b>

i want to sync my github account to VS code . but when i try to authenticate it takes me to git hub websuite and then final giiving an error message "oh an error occured, please restart the sign in process from the editor: "
can i get some help in this issue. 

thanks in advance.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.79GB (0.24GB free)|
|Process Argv|--crash-reporter-id 779eb86f-3688-4088-8fd4-8faaaa5479b9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    70	   796	code main
    0	    14	   516	   crashpad-handler
    0	    67	  3080	   shared-process
    0	   132	 13172	   window (Welcome - diin - Visual Studio Code)
    0	     5	  8908	     console-window-host (Windows internal process)
    0	    31	 11144	     searchService
    0	   142	 11776	     extensionHost
    0	    64	 17200	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	 18360	     watcherService 
    0	    11	  9872	       console-window-host (Windows internal process)
    0	    25	 13996	   utility
    2	    62	 15392	   window (Issue Reporter)
    2	   146	 19288	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.20.0
git-graph|mhu|1.26.0
vsliveshare|ms-|1.0.2740
indent-rainbow|ode|7.4.0
git-mob|Ric|1.7.0
vscode-text-tables|Rom|0.1.5
git-merger|sha|0.4.1
vscode-status-bar-format-toggle|tom|2.0.0
vscode-icons|vsc|10.2.0

</details>

**Comment by RMacfarlane** [comment] 2020-11-03 17:11
Closing as a duplicate of https://github.com/microsoft/vscode/issues/108304

**Closed by RMacfarlane** 2020-11-03 17:11 UTC
