### ISSUE TITLE
Recently Opened Folders are not showing

### ISSUE THREAD

**Issue by sharat** [Microsoft/vscode#69633] opened 2019-03-01 03:55 UTC
Issue Type: <b>Bug</b>

Open one or more folder with Visual Studio Code (I've .net core and angular projects).
Right Click on Visual Studio Icon on macOS dock.
It shows random folders other than the previously opened ones

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.19.3
gitlens|eam|9.5.1
csharpextensions|jch|1.3.0
docomment|k--|0.1.6
swift|Kas|0.0.3
vscode-azurefunctions|ms-|0.15.0
python|ms-|2019.2.5433
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vscode-docker|Pet|0.5.2
ruby|reb|0.22.2
java|red|0.39.0
swiftlint|shi|0.1.3
sonarlint-vscode|Son|1.6.0
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.1.3
application-insights|Vis|0.4.2
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2

</details>

**Comment by bpasero** [comment] 2019-03-01 13:09
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sharat** [comment] 2019-03-01 14:05
Finally redirected URL shows "Not Found" - https://update.code.visualstudio.com/latest/darwin/insider

<img width="580" alt="screen shot 2019-03-01 at 6 51 41 pm" src="https://user-images.githubusercontent.com/405971/53643052-198df380-3c59-11e9-8f2f-93d381e44d7a.png">

**Comment by bpasero** [comment] 2019-03-01 14:13
@sharat hold on it looks like we have some build trouble. Meanwhile you can use this link to download a Exploration build (which is similar): https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip

**Comment by sharat** [comment] 2019-03-01 14:22
Hey @bpasero I find it's working fine with the exploratory build provided. I played around a while and it works. I tried with stable build as well and it's still not working!

**Comment by bpasero** [comment] 2019-03-01 14:27
@sharat does it work after you cleared that list by using the clear action from "File > Open Recent"?

**Comment by sharat** [comment] 2019-03-01 14:50
I tried clearing the list with stable build and the behavior is inconsistent.

1. I dragged multiple folders (3 of them) and quit. the recent list did not update
2. I dragged the same folders one by one, closed them and finally quit VS Code. The recent list updated
3. I dragged in another 2 folders and quit VS Code, the list did not budge
4. When I drag in a single folder, it get updated. That's what I observed so far.

**Comment by bpasero** [comment] 2019-03-01 14:58
@sharat we always update the list in the dock menu based on the contents of the "File > Open Recent" list. Can you check if those two correlate at least?

**Comment by sharat** [comment] 2019-03-01 15:02
No, the list is not in sync.

<img width="511" alt="screen shot 2019-03-01 at 8 30 40 pm" src="https://user-images.githubusercontent.com/405971/53646386-11d24d00-3c61-11e9-97b1-8b9898d3ab4c.png">

<img width="257" alt="screen shot 2019-03-01 at 8 30 50 pm" src="https://user-images.githubusercontent.com/405971/53646387-11d24d00-3c61-11e9-9e21-fc353520ef04.png">

**Comment by bpasero** [comment] 2019-03-01 15:17
Ok thanks, I will mark this as a duplicate of https://github.com/Microsoft/vscode/issues/65978 and we should continue the discussion there.

**Closed by bpasero** 2019-03-01 15:17 UTC
Labels: electron, mac, needs more info, upstream

**Comment by bpasero** [comment] 2019-03-01 15:21
@sharat does a restart change anything or an uninstall and reinstall?

**Comment by sharat** [comment] 2019-03-01 15:25
I started seeing this issue with a recent update. It was working before. I haven't tried an uninstall but tried everything else, mentioned.

**Comment by sharat** [comment] 2019-03-01 15:30
@bpasero I re-installed VS Code. Confirmed that 

1. Recent list get updated when a single folder is opened.
2. Recent list and Dock's recent list are in sync
3. There's no update when 2 or more folders are dragged to VS Code on Dock. (I usually hit `code .` from Terminal, the behavior is same though)

**Comment by bpasero** [comment] 2019-03-01 17:29
@sharat wait, dropping multiple folders is different. this will result in a single window opening with an "untitled" workspace containing these folders. Only when you save this untitled workspace (via File menu e.g.) should it appear as entry.

**Comment by sharat** [comment] 2019-03-02 04:28
@bpasero Yes, this behavior started appearing after I cleared the recent file list as you instructed. Previously, even opening a single folder wasn't making any difference in the recently opened list. Sorry about the confusion.

**Comment by bpasero** [comment] 2019-03-02 07:23
@sharat so it looks like everything works as expected again?
