### ISSUE TITLE
Settings bad layout after toggling v/h editor layout

### ISSUE THREAD

**Issue by lessneek** [microsoft/vscode#89247] opened 2020-01-24 18:39 UTC
Issue Type: <b>Bug</b>

1. Open the Settings tab (Ctrl+,)
2. Open an empty tab (Ctrl+2)
3. Toggle horizontal/vertical editor layout (Alt+Shift+0)
4. ...
5. Profit.

![image](https://user-images.githubusercontent.com/289916/73094580-eb10ab00-3ef1-11ea-9d77-ce7fac1215cd.png)

VS Code version: Code - OSS 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-20T11:11:01.597Z)
OS version: Linux x64 5.4.13-3-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4103)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.63GB (1.88GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
gitlens|eam|10.2.0
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1
nim|kos|0.6.4
cpptools|ms-|0.26.3
material-icon-theme|PKi|3.9.2
debug|web|0.24.0

(1 theme extensions excluded)

</details>

**Comment by cat-kitten** [comment] 2020-01-24 19:49
![image](https://user-images.githubusercontent.com/31485942/73098901-06c88100-3ef3-11ea-8781-96b185b4342c.png)
I can confirm, this bug occurs in the normal VS code version (non-oss) as well. I have Windows 10 and C/C++, Dart and Python extensions installed

**Comment by roblourens** [comment] 2020-01-26 00:39
Yikes

**Comment by roblourens** [comment] 2020-03-31 02:16
Going to close this as a dupe of https://github.com/microsoft/vscode/issues/89943, still investigating there.

**Closed by roblourens** 2020-03-31 02:16 UTC
Labels: bug, settings-editor
