### ISSUE TITLE
Enable support for opening multiple folders in workspace

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#5711] opened 2016-04-24 07:09 UTC
It'd be great if we can open more than one folder in the workspace

**Comment by bpasero** [comment] 2016-04-27 19:19
Closing as duplicate of #2686

**Comment by bpasero** [comment] 2016-04-27 19:21
https://github.com/Microsoft/vscode/issues/396

**Closed by bpasero** 2016-04-27 19:21 UTC
Labels: feature-request, workbench
