### ISSUE TITLE
Password being shown in terminal with local echo enabled

### ISSUE THREAD

**Issue by yw662** [microsoft/vscode#110359] opened 2020-11-11 00:35 UTC
- VSCode Version: 1.51.0
- OS Version: windows 19041

Steps to Reproduce:

1. open a remote terminal, and try sth. requiring a password (like `sudo`)
2. type the password, and it will be shown on screen

Does this issue occur when all extensions are disabled?: Yes/No
No for windows since I need remote-wsl or remote-ssh. Not sure what may happen on Linux/Mac though.

**Comment by yw662** [comment] 2020-11-11 00:35
fix a typo

**Comment by meganrogge** [comment] 2020-11-11 02:57
not able to reproduce this in WSL can you pls include a [gif](https://gifcap.dev/)

![recording (33)](https://user-images.githubusercontent.com/29464607/98759681-762a3700-2386-11eb-8e24-6a1b54dbe211.gif)

**Comment by yw662** [comment] 2020-11-11 10:48
I am not able to reproduce it with wsl either. However it occurs with high latency connection, using ssh. I think it won't be an issue for wsl.

However when I set latency to 0, or a very low value:

![recording](https://user-images.githubusercontent.com/34736747/98802484-3be18980-23c8-11eb-8a28-9ee9aaaccf8d.gif)

**Comment by yw662** [comment] 2020-11-11 20:16
The remote OS is Clear Linux (the one from Intel).

However I don't think it is about OS. It is about latency.

**Comment by connor4312** [comment] 2020-11-11 21:07
Thanks, indeed the pattern is slightly different with its prompt. Instead I have taken a better approach to this where typeahead is only shown after the first prediction for a line has been confirmed, which should be a more resilient fix for this.

**Closed** 2020-11-11 21:08 UTC
Labels: bug, integrated-terminal-local-echo

**Comment by YipYipX4** [comment] 2020-11-17 19:02
@connor4312 Does your typeahead logic stop at new lines?  What if a fast typist types in a sudo command, presses Enter and immediately starts typing their password (out of habit)?  The new line echoed back may act as confirmation of the typeahead buffer and then the password characters may be revealed.

Sorry for nitpicking on a closed issue, but I think it is important to get this right.  Imagine you are giving a (virtual) demo to a large audience and then VSCode reveals your password to the entire audience!

**Comment by JacksonKearl** [comment] 2020-12-07 19:56
@yw662 is this now working for you?

**Comment by yw662** [comment] 2020-12-07 20:53
Haven't got a chance to test it out on insider. Is it shipped to stable ?

**Comment by connor4312** [comment] 2020-12-07 20:57
Not yet, it will be in a few days

**Comment by JacksonKearl** [comment] 2020-12-07 23:02
I haven't been able to get Clear Linux up in either a container or Parallels VM so going to release my lock..

**Comment by JacksonKearl** [comment] 2020-12-07 23:19
Verfied via remote-ssh to an azure clear instance.
