### ISSUE TITLE
Marketplace request times out

### ISSUE THREAD

**Issue by Simon-HN** [Microsoft/vscode#36508] opened 2017-10-18 18:06 UTC
Im not sure where to post this issue, but im having trouble reaching marketplace.visualstudio.com both through browsers and extensions in vscode. In vscode, when I try to search for extensions I get this error after a while: "XHR failed:".

I'm not behind any proxy and I can reach all other sites just fine, the problem started about a week ago.
Done the basic things as restarting router, trying on another computer etc.

Here are some additional information:

Pinged these sites:
```
vscode-update.azurewebsites.net -> Request timed out
vscode.blob.core.windows.net -> Request timed out
marketplace.visualstudio.com -> Request timed out
www.gallerycdn.vsassets.io -> OK
rink.hockeyapp.net -> Request timed out
```

nslookup for marketplace.visualstudio.com gives me:
```
Server:  router.asus.com
Address:  192.168.1.1

Non-authoritative answer:
Name:    marketplace.visualstudio.com
Address:  13.85.19.92
```

Tracert for marketplace.visualstudio.com:

```
  1    <1 ms    <1 ms    <1 ms  router.asus.com [192.168.1.1]
  2     1 ms     1 ms     1 ms  xxx
  3    <1 ms    <1 ms    <1 ms  xxx
  4    <1 ms    <1 ms    <1 ms  xxx
  5    <1 ms    <1 ms    <1 ms  xxx
  6     1 ms    <1 ms    <1 ms  xxx
  7     5 ms     5 ms     5 ms  mlm-cr1.link.netatonce.net [85.195.62.38]
  8     6 ms     6 ms     6 ms  netnod-ix-cph-1500.microsoft.com [195.69.117.181]
  9     6 ms     5 ms     5 ms  ae0-0.cph30-96cbe-1a.ntwk.msn.net [198.206.164.26]
 10    29 ms    29 ms    29 ms  ae10-0.amb-96cbe-1a.ntwk.msn.net [198.206.164.28]
 11   132 ms   132 ms   132 ms  be-61-0.ibr01.amb.ntwk.msn.net [104.44.9.132]
 12   134 ms   133 ms   134 ms  be-5-0.ibr01.lts.ntwk.msn.net [104.44.4.233]
 13   133 ms   132 ms   133 ms  be-1-0.ibr02.lts.ntwk.msn.net [104.44.4.220]
 14   132 ms   132 ms   132 ms  be-2-0.ibr02.lon30.ntwk.msn.net [104.44.5.40]
 15   132 ms   132 ms   132 ms  be-8-0.ibr02.nyc04.ntwk.msn.net [104.44.5.28]
 16   132 ms   132 ms   133 ms  be-4-0.ibr02.nyc04.ntwk.msn.net [104.44.4.29]
 17   132 ms   132 ms   133 ms  be-3-0.ibr02.was05.ntwk.msn.net [104.44.4.26]
 18   133 ms   133 ms   134 ms  be-1-0.ibr01.cnr01.bn6.ntwk.msn.net [104.44.4.159]
 19   135 ms   132 ms   133 ms  be-3-0.ibr01.bn1.ntwk.msn.net [104.44.4.49]
 20   132 ms   134 ms   132 ms  be-1-0.ibr01.atb.ntwk.msn.net [104.44.4.38]
 21   132 ms   134 ms   133 ms  be-6-0.ibr02.sn4.ntwk.msn.net [104.44.4.47]
 22   131 ms   131 ms   131 ms  ae81-0.sn4-96cbe-1a.ntwk.msn.net [104.44.9.89]
 23     *        *        *     Request timed out.
```

Anyone have an idea?

**Comment by mjbvz** [comment] 2017-10-19 00:13
Duplicate of #34385

@joaomoreno Does any of this additional info help with the investigation of the problem?

**Comment by joaomoreno** [comment] 2017-10-19 08:12
@Simon-HN Can you run an `nslookup` for all those 5 domains?

**Comment by Simon-HN** [comment] 2017-10-19 16:58
@joaomoreno Sure, here goes:

```
Server:  router.asus.com
Address:  192.168.1.1

Non-authoritative answer:
Name:    marketplace.visualstudio.com
Address:  13.85.19.92

Non-authoritative answer:
Name:    waws-prod-bay-049.cloudapp.net
Address:  40.83.182.206
Aliases:  vscode-update.azurewebsites.net
          waws-prod-bay-049.vip.azurewebsites.windows.net

Non-authoritative answer:
Name:    blob.am5prdstr07a.store.core.windows.net
Address:  13.95.96.184
Aliases:  vscode.blob.core.windows.net

Non-authoritative answer:
Name:    cs10.wpc.v0cdn.net
Addresses:  2606:2800:133:f17:19e8:2356:251b:2a9
          68.232.34.200
Aliases:  www.gallerycdn.vsassets.io
          35563.wpc.azureedge.net

Non-authoritative answer:
Name:    stadiumvpc-265910089.us-east-1.elb.amazonaws.com
Addresses:  54.83.87.53
          34.236.136.190
          34.198.2.49
          52.7.206.234
          52.21.94.161
          34.228.205.158
          54.210.117.1
          52.204.92.23
Aliases:  rink.hockeyapp.net
```

**Closed** 2017-10-19 17:33 UTC
Labels: duplicate, needs more info

**Comment by Simon-HN** [comment] 2017-10-19 17:35
And now it just started working again... I have no idea why but if it helps I can run the commands again.
