### ISSUE TITLE
javascript.updateImportsOnFileMove.enabled will destroy your project in some cases

### ISSUE THREAD

**Issue by mschipperheyn** [Microsoft/vscode#53754] opened 2018-07-06 22:13 UTC
When I was prompted if I always wanted to always automatically update the references if I moved a file, I thought nothing of it and clicked yes. Imagine my surprise when vscode opened up hundreds of files in my project and started inserting references to some files far outside of the project space. My cpu went into overdrive

Killing vscode didn't help. It started right up doing it when I restarted. Scary. In the end, manually editing the settings file ("javascript.updateImportsOnFileMove.enabled": "always => never") proved the way to turn it off.

- VSCode Version: 1.25.0
- OS Version: Mac High Sierra

Steps to Reproduce:

I don't know and I don't care. I will never use this function again.
As far as I can tell most, perhaps all, of the affected imports had an @ in them, e.g. "@lingui/react": "2.0.7"

This should never have happened. Vscode should not process every file in the project to check for file links and change them, only files you move (as advertised). Also it should imho never blindly start importing references outside of the project directory. That makes no sense to me. 

My assumption is that it looked for the node_modules/package file up the tree for some reason, I assume because of the @ sign, but not sure.

**Comment by mjbvz** [comment] 2018-07-06 22:40
Duplicate of https://github.com/Microsoft/TypeScript/issues/24914

The next VS Code insiders build picks up TypeScript 3.0. Try that or manually install `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Let me know if you run into the issue again after updating

**Closed by mjbvz** 2018-07-06 22:40 UTC
Labels: new release

**Comment by PeteJodo** [comment] 2018-07-06 22:42
This just happened to me and vscode is basically unusable for me now. Every time I try to boot vscode, it freezes since I accidentally closed vscode when trying to close all the tabs that were updated (which included a very large number of files from node_modules) and so when booting, it hangs trying to reopen all those files again from what I assume is some cache of unsaved data.

Where does the data for tracking what files are open live and is it safe to remove?

**Comment by Shenmin-Z** [comment] 2018-07-26 03:18
I had the same issue and it is really annoying. If you are using typescript, notice that there is another option:

`typescript.updateImportsOnFileMove.enabled`
