### ISSUE TITLE
Integrated terminal rows get cut off when custom value for editor.fontSize is used

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#15420] opened 2016-11-13 08:19 UTC
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install zsh and oh-my-zsh
2. Start VSCode and open integrated terminal

It is nice to have #13554 fixed but the terminal starts with first-line text not shown properly.

![screenshot from 2016-11-13 16-16-14](https://cloud.githubusercontent.com/assets/4662568/20244431/c8cb26ce-a9bc-11e6-8bfa-3e4a370d70da.png)

**Comment by Tyriar** [comment] 2016-11-14 18:14
Do you have a `window.zoomLevel` set in your `settings.json` file? Might be a duplicate of zoom not being supported properly https://github.com/Microsoft/vscode/issues/12810

**Comment by renkun-ken** [comment] 2016-11-15 01:35
I don't set `window.zoomLevel` in my `settings.json`. 

In my `settings.json`,

```json
"editor.fontFamily": "Ubuntu Mono",
"editor.fontSize": 18
```

I notice that when I comment `"editor.fontSize": 18`, the integrated terminal looks perfect. When the font size is set above 14, this problem occurs as the text in the terminal does not correctly scale up.

**Comment by Tyriar** [comment] 2016-11-15 21:50
Thanks for the info, it seems to be related to the relayout logic not properly using `editor.fontSize`.

**Comment by Tyriar** [comment] 2017-01-06 18:18
The terminal font size no longer falls back to editor.fontSize as one is the editor and the other the workbench which should scale independently, they just share the same default. There is a scale issue similar to this still happening though here https://github.com/Microsoft/vscode/issues/14479

**Closed by Tyriar** 2017-01-06 18:18 UTC
Labels: bug, help wanted, integrated-terminal
