### ISSUE TITLE
When you open vs code this error always appears: Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by rafsboy** [Microsoft/vscode#24674] opened 2017-04-13 11:32 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|Angular2|johnpapa|2.2.3|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|debugger-for-chrome|msjsdiag|3.0.1|
|ionic2-snippets|oudZy|1.0.0|
|typescript-hero|rbbit|0.12.0|
|autoimport|steoates|1.2.2|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1.  I open vs code
2. in developer tools this erro, Extension host terminated unexpectedly. Code:  3221225477  Signal:  null

**Comment by jrieken** [comment] 2017-04-13 12:05
Can you try again without extensions enabled? Like so `code --disable-extensions`. Thanks

**Comment by DeltaCharlieAlpha** [comment] 2017-04-13 21:55
I am seeing the same behavior.  I have no extensions in common with the original poster and when I run with the --disable-extensions, I see the same behavior (Extension host terminated unexpectedly.  Please reload the window to recover).  Reloading the window only brings up the same error a little later.

Version 1.11.2
Date 2017-04-13T08:0311.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

(Why isn't the "about box editable so I can cut and paste that info?)

**Comment by jrieken** [comment] 2017-04-14 07:21
closing as dupe of https://github.com/Microsoft/vscode/issues/24742

**Closed by jrieken** 2017-04-14 07:21 UTC
Labels: needs more info
