### ISSUE TITLE
menu issue in file explorer section

### ISSUE THREAD

**Issue by RajrupDasid** [microsoft/vscode#130560] opened 2021-08-11 09:06 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version:Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.10.56-1-MANJARO

Steps to Reproduce:

1.There is a view error in right click , in file explorer section
2.If you right click on a folder , drop down menu should need to freeze there , but that's not the thing going on
if i right click on a folder to create a file inside it , the menu in coming but for a fraction of a second , then automatically maven project section has been  selected and there's no way to close that section.
3.I am currently working on a django project while doing that i notice this issue. my be you will have same problem on 
other project folder too,
4. i am going to use touch <file name> for this time ,until the problem is solved.

**Comment by isidorn** [comment] 2021-08-11 10:13
Can you please clarify what you are trying to say? Can you provide a picture? 
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment] 2021-08-11 11:52
Most likely duplicate of #113175 or #114391

**Closed** 2021-08-11 11:55 UTC
Labels: needs more info, file-explorer, *duplicate

**Comment by RajrupDasid** [comment] 2021-08-12 18:02
> Most likely duplicate of #113175 or #114391

Yes absolutely , i completely wipe vscode and reinstalled it , but again same issue , my problem same as #113175
