### ISSUE TITLE
Endless waiting for build tasks in workspace file

### ISSUE THREAD

**Issue by sergju** [microsoft/vscode#162922] opened 2022-10-07 09:47 UTC
Type: <b>Bug</b>

Endless waiting for build tasks in workspace file.
New release  1.72.0
After press Ctrl+Shift+B to run default task - no task started and message "Fetching build tasks..." in status bar

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-12100F (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (24.51GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bubuntuwork22/home/serg_ju/work/Restr/prj/RestrExoPlayer.code-workspace --crash-reporter-id f9f0c7ec-238a-4b1f-925b-ef864a120a31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: UbuntuWork22|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i3-12100F (8 x 3302)|
|Memory (System)|15.62GB (14.52GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
better-cpp-syntax|jef|1.16.1
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.2
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
code-settings-sync|Sha|3.4.3
gitstash|art|5.1.0
githistory|don|0.6.19
githd|hui|2.3.3
git-graph|mhu|1.30.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.4
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by meganrogge** [comment] 2022-10-07 13:35
Can you provide me w your tasks.json? And does this always reproduce? A gif would be helpful

**Comment by sergju** [comment] 2022-10-07 14:02
tasks in workspace file.
I just copied the file with other name and it works.

**Comment by sergju** [comment] 2022-10-07 14:13
[test1.zip](https://github.com/microsoft/vscode/files/9734618/test1.zip)
I remove most stuff from file and made it simple, but problem still exists.

**Comment by sergju** [comment] 2022-10-07 14:45
Hmmm. I copied with other name, but after couple runs problem appeared again...

**Comment by davidpcaldwell** [comment] 2022-10-12 13:41
I can confirm there's been a significant performance regression in the Tasks implementation. For me, it manifests because I have a keybinding like this:
```
{
    "key": "alt+p",
    "command": "workbench.action.tasks.runTask"
}
```
... and when I hit Option-P on my Mac (one is Intel, the other is Apple Silicon), there's a significant delay before the list pops up. It used to be instantaneous.

I keep my VSCode pretty up to date, but not zealously, so I am guessing this happened in 1.72 or 1.72.1.

**Comment by meganrogge** [comment] 2022-10-12 14:15
Fixed in insiders

**Closed by meganrogge** 2022-10-12 14:15 UTC
Labels: info-needed, tasks
