### ISSUE TITLE
Some cells not rendered in a notebook

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#122584] opened 2021-04-28 21:36 UTC
@whippingdot commented on [Sat Apr 24 2021](https://github.com/microsoft/vscode-jupyter/issues/5624)

## Environment data

-   VS Code version: 1.56.0-insider(user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.777186939
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows, 20H2
-   Python and/or Anaconda version: Python 3.8.5 64-bit (conda), 2020.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): I think Conda
-   Jupyter server running: Local

## Expected behavior

All the cells to load in

## Actual behavior

The first three cells don't load in but the rest do. By this I mean when I scroll to the top the first cell I see is the fourth cell. If I try scrolling further, I can't and I see that the scroll bar is at its max too. Also if I press the run all button the first three cells also run (i know this because I take inputs and the input dialogue still occurs).

## Steps to reproduce:

I think this might only be a problem with the current notebook I am using, so I don't know how you would replicate this. For now maybe:

1. Create 22 cells with the last two markdown and the rest python.

2. Try reloading the notebook a couple times and see if the first few don't load.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

There is a lot so I don't know what to paste here...
```
XXX
```

</p>
</details>

---

@joyceerhl commented on [Sat Apr 24 2021](https://github.com/microsoft/vscode-jupyter/issues/5624#issuecomment-826137716)

@whippingdot This sounds bad if it's hitting lots of users. Can you share the notebook by any chance? Or post a GIF/screenshot? I can't reproduce it though--I created 22 cells with the last 2 markdown and the rest Python like you said, and reloaded 5x but the cells are definitely showing for me.

As for the logs, if you could paste all of them under the Jupyter output panel that would be helpful. Thanks in advance!

---

@whippingdot commented on [Sun Apr 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5624#issuecomment-826272235)

One thing to note - this is only happening on one computer. I don't really use that computer so it isn't a major problem, but I am pretty sure it isn't a problem with everyone. On the other computers it works. Also I can't seem to share the notebook, so I will just share a video:

https://user-images.githubusercontent.com/64354499/115984300-fa364b00-a5c3-11eb-85bf-5343cfeea69e.mp4

**Comment by joyceerhl** [comment] 2021-04-28 21:36
@whippingdot Could you provide a zip archive containing the problematic notebook? It would help us try to reproduce the problem.

**Comment by whippingdot** [comment] 2021-04-29 05:39
Sorry if this is a dumb question but how do I create a zip archive? And also how do I provide it to you...can I send that type of file in a comment?

**Comment by joyceerhl** [comment] 2021-04-29 06:22
@whippingdot You can create a zip archive by opening the file explorer, selecting the ipynb file and using the Zip button under the share tab:
![image](https://user-images.githubusercontent.com/30305945/116509505-44475700-a878-11eb-8863-cd49d4d8ed00.png)

You can then attach the zip archive to a comment in this thread by dragging and dropping, selecting or pasting it.

**Comment by whippingdot** [comment] 2021-04-29 06:23
I know you can attach files by doing that - I just didn't know if .zip files would work in GitHub

**Comment by whippingdot** [comment] 2021-04-29 06:24
[Assignment Answers.zip](https://github.com/microsoft/vscode/files/6396661/Assignment.Answers.zip)

Here you go

**Comment by rebornix** [comment] 2021-04-29 20:56
I was not able to reproduce the issue with the file shared. @whippingdot can you help check if you see any logs by opening "Toggle Developer Tools" from command palette?

**Comment by whippingdot** [comment] 2021-04-30 11:47
Ok, I am not on that computer for another 10 days so I will respond in some time (please ping me in like 11 days incase I forget)

**Comment by whippingdot** [comment] 2021-07-20 13:18
Hey I don't think this issue is there anymore, so close it if you want to. I don't use that other computer much anyway. I will comment again if I see another issue.

**Comment by rebornix** [comment] 2021-08-04 00:00
We had a fix for this particular, let's reopen if we are seeing it again.

**Closed by rebornix** 2021-08-04 00:00 UTC
Labels: needs more info

**Comment by matthewneiman** [comment] 2021-08-23 11:27
This is happening to me in a couple of notebooks.
Currently in one that is 12 cells long. I opened it this morning just fine, but now I opened it again, and the first three cells don't show.
I can run the notebook, and the missing cells run (I have imports in them..) but I can't see or modify them.

**Comment by whippingdot** [comment] 2021-08-24 08:54
> EDIT
I just made a copy of the notebook. It opened just fine, with the first three lines showing.

This must mean that it is a problem with out notebooks maybe
