### ISSUE TITLE
JSX Comments (mixed modes)

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#11844] opened 2016-09-11 13:10 UTC
- VSCode Version: 1.5.1
- OS Version: Fedora 24

Steps to Reproduce:
1. Try to put a comment on a JSX row
2. The comment is "//" instead of "{/*".

**Comment by wallverb** [comment] 2016-09-12 13:10
https://github.com/Microsoft/vscode/issues/7658

**Comment by mjbvz** [comment] 2017-01-12 01:12
Closing as duplicate of #7658

**Closed by mjbvz** 2017-01-12 01:12 UTC
Labels: duplicate, feature-request, languages basic
