### ISSUE TITLE
Text from 'Restart' command is not selectable

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode#149662] opened 2022-05-15 11:54 UTC
## Environment data

-   VS Code version: 1.67.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.2
-   OS (Windows | Mac | Linux distro) and version: linux (debian testing)
-   Python and/or Anaconda version: python 3.9.12, conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Steps to reproduce:
* Create an interactive jupyter window.
* Click the button 'Restart' at the top of the pane.
* In the output cell that it generates, try to select the text with the mouse by position the mouse at the beginning, holding a left click, and moving the mouse towards the right.

## Expected behavior:
Should select the text ("Restarted 'Python --version-- (--kernel name--)' kernel").

## Actual behavior:
Selects the cell as an image and visually moves it as I move the mouse.

**Comment by greazer** [comment] 2022-05-16 20:11
Being able to select label text in notebook cells is a vscode core issue

**Comment by amunger** [comment] 2022-08-16 17:17
Drag and drop should be disabled since the notebook is read only

**Comment by david-cortes** [comment] 2022-08-16 18:00
> Drag and drop should be disabled since the notebook is read only

One can still copy text from executed commands in the interactive jupyter interpreter window.

**Comment by amunger** [comment] 2022-08-16 20:20
sorry, that was just a note on how to resolve this issue, not disagreeing with the issue itself

**Comment by amunger** [comment] 2022-12-08 21:41
duplicate of https://github.com/microsoft/vscode/issues/149662

**Comment by roblourens** [comment] 2022-12-29 22:11
This seems fixed now right @amunger?

**Closed by roblourens** 2022-12-29 22:11 UTC
Labels: bug, notebook-dnd, interactive-window

**Comment by david-cortes** [comment] 2022-12-30 17:13
@roblourens Still reprodcible in vscode 1.74.2.

**Comment by roblourens** [comment] 2022-12-30 17:21
You'll see it fixed in the Insiders release. Hasn't been released to stable yet.
