### ISSUE TITLE
Powershell opening on Terminal in first instance despite default

### ISSUE THREAD

**Issue by ssoworld** [microsoft/vscode#138999] opened 2021-12-10 13:57 UTC
- VSCode Version: 1.63.0
- Local OS Version: Windows 10 20H2
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs: Unable to find source log that indicates terminal launch

Steps to Reproduce:

1. Open VSCode
2. press CTRL+~ to open terminal

Killing the terminal and executing step 2 will open the default terminal (Git Bash for me)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/6534994/145584310-9ba93c21-2464-4e5c-a22c-eaa255491f35.png)

**Comment by meganrogge** [comment] 2021-12-13 18:47
also see the icon, indicates that the default profile is likely undefined so we use the fallback

**Comment by Tyriar** [comment] 2021-12-14 17:00
Maybe not related to remote?

@ssoworld I see this in your report:

> Remote Extension/Connection Type: SSH/Docker/WSL

What type of window were you in where you saw this? You can take a screenshot of the bottom left corner of the window to tell us this.

**Comment by ssoworld** [comment] 2021-12-15 00:35
Yeah that was in error. It was not any of those

-Scott Onson

________________________________

**Comment by schattenmann80** [comment] 2021-12-16 07:49
I have the same issue. And I'am working remote with SSH.
This issue was fixed, but it came back with the last update.

**Comment by Tolga-Karahan** [comment] 2021-12-20 08:00
It also gives me powershell when I typed code inside wsl and open the vs code. Any solution for that?

**Comment by edorgeville** [comment] 2021-12-20 13:44
Re-setting the default terminal profile and restarting VSCode fixed the issue for me:
1. CTRL+Shift+P
2. Type `default profile`
3. Select `Terminal: Select Default Profile`
4. Select `Git Bash`
5. Restart VSCode
If you had the Terminal tab open, it will reopen after restart, and should be using Git Bash.

**Comment by Tolga-Karahan** [comment] 2021-12-20 14:19
> 
Yeah, you can use Git bash in that way but the real problem in my case is VS Code sees files inside wsl as an extension of windows filesystem. I suppose because of that it opens powershell instead of bash and also when I want to point out a Python interpreter inside the wsl it directs me to root of windows filesystem.

**Comment by WORMSS** [comment] 2022-01-11 10:41
Additional Info:

```
1) Open VSCode
2) Kill ALL the terminals - Observe the terminal panel close
3) Close VSCode
4) Open VSCode again - Observe no terminal panel
5a) Menu-bar > Terminal > New Terminal (Ctrl+Shift+') - Observe Terminal Panel opens with Git Bash.
```
vs
```
1) Open VSCode
2) Kill ALL the terminals - Observe the terminal panel close
3) Close VSCode
4) Open VSCode again - Observe no terminal panel
5b) Menu-bar > View > Terminal (Ctrl+') - Observe Terminal Panel opens with PowerShell
6) Kill the PowerShell terminal - Observe the terminal panel close
7) Menu-bar > View > Terminal (Ctrl+') - Observe Terminal Panel opens with Git Bash
```

Hope these steps help.

**Comment by rongem** [comment] 2022-01-25 05:50
I have the same issue, too. But there is one difference to #132150: 
After a reboot, it opens Powershell every time. When opening VS Code several times during a windows session, some of the times the correctly configured git bash is opened. So maybe this could be related to caching oder something like that.

**Comment by bavoceulemans** [comment] 2022-01-31 09:00
My default is Git Bash but I get Powershell on every first launch after a Windows reboot.

**Comment by markedwards** [comment] 2022-02-12 11:28
This ticket appears to be Windows-specific, but there are also issues with the incorrect terminal type being opened after a window reloads on other platforms.  Tasks related to those are getting marked as duplicates of this.

Does this task cover Linux and OS X issues as well?

**Comment by alvaromerinog** [comment] 2022-03-05 20:30
Hello there! I found a bug in the line 921 of the file ./src/vs/workbench/contrib/terminal/browser/terminalService.ts. It never enters in the next condition when the terminal profiles are not loaded already because !Array() is always false.
```typescript
if (!this._terminalProfileService.availableProfiles) {
```
I hope it can be helpful. See you soon.

**Comment by wrhighfield** [comment] 2022-04-23 14:12
It has something to do with the -nologo arg and automatic updates for me.

Even though my default terminal is set to bash as well, whenever there is a new version of Powershell VSCode starts with a Powershell terminal until I upgrade to the latest version -> close all terminals in VSCode -> shut VSCode down and restart.  It will work fine until the next update.  Users of Windows Terminal have the option of using the -nologo arg to suppress this, not sure if there is some workaround for VSCode users.

**Comment by alexr00** [comment] 2022-06-30 13:05
What would you expect the behavior to be with terminal reattach? 
1. I had closed my SSH remote window after testing something else.
2. I set my default Windows profile to be "Git Bash".
3. I reconnected to it to verify this issue.
4. I got reconnected to my PowerShell terminal.

**Comment by alexr00** [comment] 2022-06-30 13:07
Actually, I see this repro even when not reattaching.

**Comment by Tyriar** [comment] 2022-07-05 17:47
I was seeing it pretty consistently when my default shell was pwsh on Code - OSS/macOS

**Comment by meganrogge** [comment] 2022-07-06 15:41
not able to reproduce this in insider's on macOS

**Comment by meganrogge** [comment] 2022-07-06 15:42
interesting - can reproduce in OSS though on macOS

**Comment by meganrogge** [comment] 2022-07-06 15:54
removing this throttle fixes it https://github.com/microsoft/vscode/blob/b0bc9dd1f91e0dd07dd5564b57abb32b1ca43a06/src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts#L100-L103

**Comment by meganrogge** [comment] 2022-07-06 16:34
yes when `profilesReady` has been awaited, the length of the available profiles is still 0

**Comment by Tyriar** [comment] 2022-07-06 16:35
@meganrogge is this 5 seconds too little? Does changing that to a large number like 60000 also fix the problem? https://github.com/microsoft/vscode/blob/2e0e882ac5997526583fd4e9e204ee77bdd534d8/src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts#L70

**Comment by meganrogge** [comment] 2022-07-06 16:37
yes

**Comment by Tyriar** [comment] 2022-07-06 16:44
Great! The problem must be the shared process + pty host takes too long to startup sometimes. So if it's more than 5 seconds we create it using the fallback shell launch config and then still wait for the start up anyway. How about we change it to 20 seconds and then change the barrier open to:

```ts
			if (!this._profilesReadyBarrier.isOpen()) {
				// log warning that it took 20 seconds to resolve terminal profiles
				this._profilesReadyBarrier.open();
			}
```

**Closed** 2022-07-07 01:59 UTC
Labels: bug, verification-found, terminal-process
