### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by jomliu** [microsoft/vscode#139780] opened 2021-12-27 02:31 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49210:29)
    at getTargetOfExportAssignment (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49246:28)
    at resolveAlias (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at resolveExternalModuleSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49248:28)
    at resolveAlias (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at initializeTypeChecker (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:85010:21)
    at Object.createTypeChecker (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/home/jomliu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0050
Fetching remote diagnostics for 'SSH: myDocker' failed: Canceled
Fetching remote diagnostics for 'SSH: myDev' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (2.77GB free)|
|Process Argv|--crash-reporter-id e5417d69-5700-4146-9f52-96ef9bb02eb9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: myDev|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0050|
|CPUs|Intel(R) Xeon(R) Gold 61xx CPU (8 x 2494)|
|Memory (System)|15.35GB (7.10GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: myDocker' failed: Canceled

Fetching remote diagnostics for 'SSH: myDev' failed: Canceled
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
vim|vsc|1.21.10
vscode-intelephense-client|bme|1.8.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-jest-runner|fir|0.4.47
shell-format|fox|7.2.2
vsc-commitizen|jas|0.8.0
vscode-commitizen|Kni|1.0.2
i18n-ally|lok|2.8.1
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
gradle-language|nac|0.2.3
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
psi-header|psi|1.15.2
rdhelper|RDM|1.6.30
java|red|1.2.0
vscode-yaml|red|1.2.2
bash-debug|rog|0.3.9
zsh-debug|rog|0.1.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by IllusionMH** [comment] 2021-12-27 04:54
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2021-12-27 05:03 UTC
Labels: *duplicate
