### ISSUE TITLE
Providing commands with titles programatically.

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/vscode#71207] opened 2019-03-26 18:02 UTC
### Problem

Currently, commands are only visible in the UI if they are defined in the extension's `package.json`:

https://code.visualstudio.com/api/references/contribution-points#contributes.commands

```json
"contributes": {
    "commands": [{
        "command": "extension.sayHello",
        "title": "Hello World",
        "category": "Hello"
    }]
}
```

And this way it is visible in the command palette:

![image](https://user-images.githubusercontent.com/15987992/55021072-61344080-4fb5-11e9-9506-9b4f734659b3.png)

However, if you register the command using the `vscode.commands.registerCommand` API, it does not accept a 'title' parameter, and it does not make it available in the command palette.

### Feature Request

Add a programatic capability to define (and dispose) user-facing commands to extensions. One possible API could be:

```ts
    export function registerUserCommand(
      command: string,
      title: string,                         // the additional parameter, similar to the "title" field in package.json
      callback: (...args: any[]) => any,
      thisArg?: any,
    ): Disposable;
```

### Use Case

I'm building a number of extensions that augment the editing experience for users with actions like `launch XYZ debugger`, or `Collect metrics for XYZ project`. I cannot define these commands in `package.json` because both their titles and availability are defined based on the project contents, which need to be analyzed when the extension activates.

**Comment by usernamehw** [comment] 2019-03-26 18:20
Duplicate of #1422

**Closed** 2019-03-26 18:27 UTC
Labels: *duplicate
