### ISSUE TITLE
Fix VS Code - Remote SSH to not autocorrect Username in TCP Tunneling Session

### ISSUE THREAD

**Issue by NTNguyen13** [microsoft/vscode#92474] opened 2020-03-11 12:03 UTC
Hi, I'm trying to use VS Code to remote ssh to a host, through a TCP Tunneling session.

**My information**

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Steps to Reproduce:**

1. Setup TCP Tunneling to a host (e.g: using AnyDesk). Example: address and port is now: 127.0.0.1:322, username: `host_username`
2. Use VS Code (Remote SSH Extension) to `Add new SSH Host`: ssh host_username@127.0.0.1:322.
Then I try to connect to that host, the user name is now changed to `my_windows_username`, and the connection is `my_windows_username@127.0.0.1:322`, hence, I cannot connect to it.

I checked the config, they are still correct:
```
Host 127.0.0.1:322
  HostName 127.0.0.1:322
  User host_username

```

I think that the problem is within the Remote SSH Extension, how can I fix that?

**Comment by FIAPT** [comment] 2020-03-11 12:26
possible duplicate of #92459 

Did you try to downgrade to Remote SSH Extension 0.49.0?

**Comment by NTNguyen13** [comment] 2020-03-12 02:12
@FIAPT I have just tried to downgradee, but it still does not work. This only happens when I tried to add this add a host into config, I can still ssh through TCP tunneling, but I have to enter the address everytime.

**Comment by mjcrouch** [comment] 2020-03-12 09:15
You may have the same issue I did - 
Are you using 'git for windows' as your compatible ssh client?

git bash can end up using a different home directory than your real user home.

For example when I open git bash, it starts off in my P: drive instead of my C: user directory

I had to copy the generated configuration from C:\users\myuser\.ssh to P:\.ssh

**Comment by roblourens** [comment] 2020-03-16 18:52
This is https://github.com/microsoft/vscode-remote-release/issues/2512

**Closed by roblourens** 2020-03-16 18:52 UTC
