### ISSUE TITLE
When middle mouse button selected ends on empty line, clipboard is pasted

### ISSUE THREAD

**Issue by meelkor** [microsoft/vscode#49527] opened 2018-05-09 11:11 UTC
- VSCode Version: 1.23.0
- OS Version: Linux version 4.16.5-1-ARCH

Steps to Reproduce:

1. Make sure you have X middle mouse button pasting enabled
2. Start middle mouse button column selection on any line
3. Stop with mouse cursor on empty line
4. X's paste event is not handled or something and clipboard is pasted at each cursor

Stopping at non-empty line works as expected though. Actually I am not sure which behavior is correct, but I believe it should not differ depending on last line's content.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2019-10-17 14:22
Duplicate of #49693

**Closed by alexandrudima** 2019-10-17 14:22 UTC
Labels: editor-clipboard, help wanted, linux, under-discussion
