### ISSUE TITLE
Unable to locate phpcs

### ISSUE THREAD

**Issue by monikait** [Microsoft/vscode#37803] opened 2017-11-08 07:39 UTC
- VSCode Version: 1.17.2
- OS Version: Window 10

Steps to Reproduce:

1. when I write a php tag and copy and php code into php file
2.

Reproduces without extensions: Yes/No  Yes

**Comment by maxibanki** [comment] 2017-11-09 07:20
Duplicate of ikappas/vscode-phpcs/issues/8. You have the vscode-phpcs extension installed which requires to have phpcs globally installed on your system. (Set the executable to the PATH variable). So he can't find the executable and throws this error.

**Closed** 2017-11-09 16:59 UTC
Labels: php
