### ISSUE TITLE
The latest version of the custom code snippet does not work~

### ISSUE THREAD

**Issue by xbears** [Microsoft/vscode#25969] opened 2017-05-05 02:31 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
The latest version of the custom code snippet does not work~

```
"ajax to jquery": {
  "prefix": "ajaxj",
  "body": [
    "$.ajax({",
    "	type: '$1',",
    "	url: '$2',",
    "	data: '',",
    "	dataType: 'json',",
    "	beforeSend: function() {",
    "	}",
    "})",
    ".done(function(res) {",
    "	if('ok' === res.ret && res.data.success) {",
    "	}else{",
    "	}",
    "});"
  ],
  "description": "ajax to jquery"
}
```

ajaxj =>
```
  $.ajax({
  
  ,
  
  ,
  
  ,
  
  ,
  
  .done(function(res) {
  
  [object Object]
  [object Object]
  ,
  });
```

**Comment by songtm** [comment] 2017-05-05 02:45
the plugin C# (version 1.9.0) stopped working too.

**Comment by Moerj** [comment] 2017-05-05 13:45
me too
![qq20170505-214215 2x](https://cloud.githubusercontent.com/assets/13795438/25747994/107e5804-31dc-11e7-9e53-238a460f061f.jpg)
![qq20170505-214429 2x](https://cloud.githubusercontent.com/assets/13795438/25747995/107fd40e-31dc-11e7-8cba-864f4a466e25.jpg)

**Comment by Moerj** [comment] 2017-05-05 13:49
![qq20170505-214734 2x](https://cloud.githubusercontent.com/assets/13795438/25748151/bf6e3096-31dc-11e7-91d9-2ad099262a53.jpg)


this problem is rewrite the space indent to \t. And it work

**Comment by Moerj** [comment] 2017-05-05 13:55
#25938

**Comment by aeschli** [comment] 2017-05-05 15:07
Correct, duplicate of #25938

**Closed by aeschli** 2017-05-05 15:07 UTC
