### ISSUE TITLE
(Duplicate) Request: Reveal in tree (In Open Editors context menu)

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode#9540] opened 2016-07-20 15:31 UTC
Hi there, I believe this has not been requested yet after my search.

What I want is to be able to right click on files in the `Open Editors` and have an option `Reveal in tree` which would find the file in vscode tree. That option could be listed right before `Reveal in explorer`.

That feature would be awesome as I am currently working with an angular project. I sometimes open a `controller` and find myself adding a depedency which is then needed in the `component`, so an option like that could save time in a big project.

**Comment by wallverb** [comment] 2016-07-20 16:35
There is a command in Command Palette 'Files: Show Active File in Explorer' and you could bind a key to it, but I agree that would be nice to have it under right click as well.

**Comment by MLefebvreICO** [comment] 2016-07-20 16:40
Good to know, thanks ! I'll use that for now, but I keep thinking that the right click could be great :smile:

**Comment by kieferrm** [comment] 2016-07-21 18:05
Closing as duplicate of #7124.

**Closed by kieferrm** 2016-07-21 18:05 UTC
