### ISSUE TITLE
Authentication blocks extension integration test

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#102426] opened 2020-07-13 20:43 UTC
Issue Type: <b>Bug</b>

* Install GitHub PR and Issues, authenticate
* Run extension integration test https://github.com/rebornix/vscode-extension-samples/tree/rebornix/notebook-test/notebook-test-sample
* The auth prompt blocks the tests to run

![image](https://user-images.githubusercontent.com/876920/87351814-d612ed00-c50e-11ea-8632-9c29a7602e69.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4

</details>

**Comment by TylerLeonhardt** [comment] 2020-07-13 20:45
I have also seen this same behavior... but the "blocker" was the prompt to update my version of `git.exe`

**Comment by RMacfarlane** [comment] 2020-07-13 20:51
Duplicate of https://github.com/microsoft/vscode-internalbacklog/issues/1016

**Closed by RMacfarlane** 2020-07-13 20:51 UTC
