### ISSUE TITLE
Typescript syntax highlighting breaks when using a variable with the prefix 'var' inside a template literal

### ISSUE THREAD

**Issue by peterkooijmans** [Microsoft/vscode#3837] opened 2016-03-08 12:23 UTC
I noticed this after upgrading vscode to version 0.10.10. A screenshot demonstrating the problem:

![screenshot](http://i.imgur.com/oi4Hc7s.png)

**Comment by thorn0** [comment] 2016-03-08 14:06
It's not only in template literals: 
![image](https://cloud.githubusercontent.com/assets/94334/13603693/a7e0f34c-e547-11e5-82cf-127334c6527e.png)

**Comment by felixfbecker** [comment] 2016-03-08 14:14
https://github.com/Microsoft/TypeScript-TmLanguage/issues/112

**Comment by aeschli** [comment] 2016-03-09 11:00
Caused by https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

Will be fixed in the March release.

**Closed by aeschli** 2016-03-09 11:00 UTC

**Comment by thorn0** [comment] 2016-03-12 09:26
Is there an easy way to update these grammar files separately?

**Comment by aeschli** [comment] 2016-03-12 13:42
No sorry, no easy way. I will notify you when the first insiders for of the March build is ready (should be next week).

**Comment by aeschli** [comment] 2016-03-21 14:27
You can get the insiders build here: https://code.visualstudio.com/insiders

**Comment by thorn0** [comment] 2016-03-21 16:55
Thanks. How do I switch the UI language to English?
