### ISSUE TITLE
Autocomplete across files

### ISSUE THREAD

**Issue by jachymcz** [Microsoft/vscode#24668] opened 2017-04-13 10:07 UTC
I switched to VSC from Atom and one very useful feature I miss is autocomplete across opened documents. So for example, I have 3 files opened and in file 1 I have a variable called "thisIsExample". I switch to File 2 and start typing thisI... and VSC would auto-complete from the other file. 
This currently works, but the auto-compete, AFAIK only works within the opened file, but it is extremely useful when you can do this with all the opened files in the editor because if for example you have files that work together and use the same variables you dont have to switch to the other one just to check what you called it. In Atom this was possible.

**Comment by jrieken** [comment] 2017-04-13 10:17
dupe of #20886

**Closed by jrieken** 2017-04-13 10:17 UTC
Labels: suggest
