### ISSUE TITLE
CSS Url() Path not  intelliSense

### ISSUE THREAD

**Issue by GiantLiu** [Microsoft/vscode#40203] opened 2017-12-14 09:23 UTC
- VSCode Version:1.81.1
- OS Version:Win 10

Steps to Reproduce:

1.CSS Url() Path not  intelliSense

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment] 2017-12-14 22:19
Are you saying you are not getting path intellisense inside Url()?

**Comment by GiantLiu** [comment] 2017-12-15 01:26
yes.in css file .set class background url().
eq: background: url(/PMimages/M14/gp1211/close.jpg)
input "url(/" or "url(../", i need intellisense "PMimages".
but now the vscode not support

**Comment by GiantLiu** [comment] 2017-12-15 01:28
if input src="" in css file
the css file has intellisense path

**Comment by aeschli** [comment] 2017-12-15 08:54
duplicate of #2037

**Closed by aeschli** 2017-12-15 08:54 UTC
Labels: css-less-sass
