### ISSUE TITLE
Debug: setting expression and hit-count at the same time does not hit anything

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14369] opened 2016-10-25 08:59 UTC
Testing #13211
- I run a simple extension with a command
- I defined 2 conditions for when the command gets executed: expression and hit-count

=> the breakpoint is never being hit

I can provide more steps to reproduce but maybe this scenario is not even supported?

**Comment by isidorn** [comment] 2016-10-25 09:00
It is supported, if the breakpoint is not being hit it is coming from the adapter, thus assigning to @weinand

**Comment by weinand** [comment] 2016-10-26 13:06
Works fine for me. I was using this example:
```js
var i = 0;
for (i = 0; i < 100; i++) {
	console.log(i);
}
```
As a condition I used `i % 10 === 0` and as a hit count `% 2`

With this the execution stopped for i == 10, 30, 50, 70, ...

**Comment by bpasero** [comment] 2016-10-26 14:13
Not sure if related but I was debugging an extension.

**Comment by weinand** [comment] 2016-10-26 14:19
I tried my snippet in an extension and still works fine

**Comment by rkeithhill** [comment] 2016-11-05 16:19
I have implemented hit count support in the PowerShell extension (well, PR is waiting to be accepted) and in my testing, both the condition and hitCondition come through to the debug adapter.  After that, it is up to the debug adapter to do the right thing.

> setting both expressions on a breakpoint seems to be a bit fragile. 

I noticed this too. You have to hit enter and not just change the value and select the drop down to change from say Expression to Hit Count (or vice versa).  If you do the latter, your change doesn't take.  But when you press enter to accept a value the UI goes away.  So if you want to set both, the UI is a tiny bit tedious.  

@weinand What's up with the value you used `% 2`?  The UI says `Hit Count` but in the protocol it is `hitCondition`.  Looks like `%2` is short for `hitCount % 2 == 0`?  For PowerShell I only allow an integer for this (using int.TryParse to pull out that int).  Hmm, am I missing an important scenario by only allowing a number?  I guess I'm used to Visual Studio's conditional breakpoint taking only numbers e.g.:

![image](https://cloud.githubusercontent.com/assets/5177512/20031635/61af3340-a340-11e6-9677-25d99a3a18a9.png)

I also agree on the hover tip, need to see both conditions. Looks like that has been fixed already. Yay!

**Comment by weinand** [comment] 2016-11-05 18:29
@rkeithhill The debug protocol does not specify the syntax of the hit count expression. So you are free to accept and validate whatever you want. For node I'm basically using the same as the xDebug protocol for php. But the node implementation does not yet validate what it receives.

**Comment by weinand** [comment] 2016-11-05 18:31
Assigning to @isidorn since the issue at hand seems to be more of an UX problem.

**Comment by isidorn** [comment] 2016-11-07 14:35
Closing this as there are no steps and I can not reproduce any of the mentioned issues.
I can always set both hit cound and expression to a breakpoint and the hover now shows that.
I can always hit breakpoints if they have both hit count and condition - also when debugging extensions.

Please reopen if you still see this on your machine and try to find steps - if not ping me and I wlll come to your machines. Thanks

**Closed by isidorn** 2016-11-07 14:35 UTC
Labels: bug, debug

**Comment by rkeithhill** [comment] 2016-11-07 17:22
For me, the only issue that exists here is that the dropdown UI does not save the current value when switching between Expression and Hit Count.  I know the watermark text says to hit press Enter but I think a fair number or folks will type an Expression, hit the drop down to set the Hit Count, then they press Enter.  In this scenario only the Hit Count is accepted.  The condition expression is not.

**Comment by isidorn** [comment] 2016-11-08 08:44
@rkeithhill got it -> for that I have created the issue https://github.com/Microsoft/vscode/issues/15151

**Comment by bpasero** [comment] 2016-12-08 10:29
@isidorn @weinand is it expected that if I define both hit count and expression, the breakpoint is only hit when the hit count expression is met?

Here is my repro:
* simple hello world extension
* breakpoint inside the command handler for hello world
* hit count: 2
* expression: console !== null

=> breakpoint only gets hit when executing the hello world command twice

**Comment by isidorn** [comment] 2016-12-08 10:31
This is up to the debug adapter to decide. But from how I understand it both conditions need to be true in order for the breakpoint to be hit.

**Comment by weinand** [comment] 2016-12-08 10:47
Sure both conditions need to be true in order to 'break'.
