### ISSUE TITLE
Variable replacement in tasks.json produces "/"-less paths in cygwin since 1.32

### ISSUE THREAD

**Issue by yarcod** [Microsoft/vscode#70211] opened 2019-03-11 13:16 UTC
- VSCode Version: 1.32
- OS Version: Windows 7, cygwin

Steps to Reproduce:

1. Create a task which uses VSCode's variable replacement, e.g. ${relativeFile}.
2. Echo the result to cygwin terminal.
3. The output will have paths written without any separators, i.e., "/". 

Does this issue occur when all extensions are disabled?: Yes

This used to work perfectly until 1.32 (I think that's when it broke, but fairly recently anyway). This issue is not present if you add an option to use Windows cmd instead; that will show a fully usable path.

**Comment by alexr00** [comment] 2019-03-12 14:36
Looks like a duplicate of #70050, where the relative file's path separators are Windows path separators.

**Comment by alexr00** [comment] 2019-03-12 15:28
Actually, this might not be a duplicate. I will investigate more.

**Comment by alexr00** [comment] 2019-03-12 16:14
@yarcod how do you use Cygwin for your integrated terminal?

**Comment by dwarcake** [comment] 2019-03-12 16:26
Dunno for OP but I use git-bash as my default shell and seem to have the same problem

Snippet of our tasks.json file:
```
{
            "label": "Run aut",
            "group": "none",
            "type": "shell",
            "args": ["some_conenction", "@${relativeFile}"],
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            },
```

**Comment by alexr00** [comment] 2019-03-13 09:58
Since the only instances of this happening are with relativeFile, this is a duplicate of #70050. See that issue for all the info, but relativeFile was incorrect. It is now fixed and has OS specific path separators.

**Closed by alexr00** 2019-03-13 09:58 UTC
Labels: needs more info

**Comment by yarcod** [comment] 2019-03-14 08:16
Sorry for the late reply! I looked at the possible duplicate and saw two things that did not align with my issue:
 * The issue was limited to ${relativeFile} specifically, while I'm having issues with _all_ variable replacements -- even ${workspaceFolder}. See below for more details.
 * This problem only appears in cygwin and works great in cmd. 

Cygwin in used like this:
"terminal.integrated.shell.windows": "C:\\cygwin\\bin\\bash.exe",
    "terminal.integrated.env.windows": {
       "CHERE_INVOKING": "1"
     },
    "terminal.integrated.shellArgs.windows": [
       "--login"
    ],

The task I am using looks like this:
{
            "label": "Get SWC name",
            "type": "shell",
            "command": ".vscode/get_swc_name.sh",
            "args": [
                "${relativeFile}"
            ],
            "group": "build",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "presentation": {
                "reveal": "never",
                "echo": false,
                "showReuseMessage": false
            }
        },
Inside of that shell script I have placed an Echo command to see that the right path was chosen, and that path now comes without slashes.
