### ISSUE TITLE
Can we enable the open specific folder only

### ISSUE THREAD

**Issue by Vince-vegas** [microsoft/vscode#130364] opened 2021-08-08 16:44 UTC
It's great if we can have the options in vscode that could open a specific folder and the **workspace** only focus on that desired folder and the others should disappear temporarily unless we click the option that exit the **focus specific folder** only.

because if we have 20 folders in one project and every folders has 20 files

We need that functionality that focuses on a specific folder, thanksssssss microsoft.

**Comment by IllusionMH** [comment] 2021-08-08 23:28
I think it duplicate of #41860 or #95182 or similar requests.

At this moment you can use `files.exclude` to hide folders/files, and then comment/uncomment necessary.
Or check extensions like [Toggle Excluded Files
](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) to show/hide all excluded or something closer to your request.

**Closed** 2021-08-09 12:30 UTC
Labels: file-explorer, *duplicate
