### ISSUE TITLE
"Rename symbol" when instance property is assigned to itself does not work

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#57456] opened 2018-08-28 20:44 UTC
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: Mac 10.13.5 (17F77)

Steps to Reproduce:

1. Use the following code:

```
class Test {
  constructor() {
    this.a = this.a.bind(this);
  }

  a() {
    return 'a';
  }
}
```

2. With the cursor on the `a` in `a()`, run "Rename symbol", and rename it to something else. The symbol in `this.a = ` will not rename.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-09-04 18:45
I can't repo using VS Code insiders with TypeScript 3.0.1: 

![sep-04-2018 11-44-43](https://user-images.githubusercontent.com/12821956/45051118-f7177680-b037-11e8-94ac-0f519a989627.gif)

Please provide more information about your project setup. Have you configured the typescript.tsdk setting?

**Comment by garyking** [comment] 2018-09-05 00:12
I reproduced with the latest Insiders, all default settings, no project settings, just a folder with one file.

![rename symbol](https://user-images.githubusercontent.com/343940/45063943-daeaf800-b07e-11e8-8d1c-06a5450ee916.gif)

**Comment by mjbvz** [comment] 2018-09-05 02:46
Thanks. Upon further investigation, this issue is a duplicate of https://github.com/Microsoft/TypeScript/issues/18171

**Closed by mjbvz** 2018-09-05 02:46 UTC
Labels: needs more info, typescript
