### ISSUE TITLE
The change window should allow you to highlight and copy text

### ISSUE THREAD

**Issue by AcademyOfF** [microsoft/vscode#117996] opened 2021-03-02 21:21 UTC
![image](https://user-images.githubusercontent.com/51732963/109716231-7038ab80-7b59-11eb-92e9-53bb00c72600.png)

This is for typescript code if that makes a difference.

Here is the change window I'm referring to:

![image](https://user-images.githubusercontent.com/51732963/109716299-8cd4e380-7b59-11eb-9b34-14dc2f503dcc.png)

I'd like to be able to highlight and copy text in there. Frequently, I take two steps forward and want to take one step back. This window only gives me the option to *see* what one step back would look like. I'd like to be able to copy some of the text so I can just paste it over the current file.

I mean no offense with this comment, I'm just trying to be helpful: I think the way Intellij IDEA handles this dialog (in general, not just for this feature) is extremely user-friendly and could serve as inspiration.

thanks!

**Comment by IllusionMH** [comment] 2021-03-02 23:32
/duplicate of #8226

I understand frustration but that's limitation of current implementation that's not easy to workaround.

While you can't select with mouse, you can copy content as described in https://github.com/microsoft/vscode/issues/8226#issuecomment-528103843

**Closed** 2021-03-02 23:33 UTC
Labels: *duplicate
