### ISSUE TITLE
jupyter notebook diff showed weirdly in diff viewer

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#211133] opened 2024-04-23 17:14 UTC
Testing #210903

1. created a jupyter notebook
2. add a cell that just says "abcs"
3. save it
4. use command "view untracked changes"
5. see the following which only shows the meta-data, does not show the "abcs" text anywhere
![image](https://github.com/microsoft/vscode/assets/26030610/7dea1e3a-392b-4822-b20e-cbf150b5ec3b)

if you instead click on the untracked changes from the source control you get this view which I assume is the intended result?
![image](https://github.com/microsoft/vscode/assets/26030610/aee71410-af59-4d91-86cd-43b1976f184e)

**Comment by lszomoru** [comment] 2024-04-23 19:22
Adding @hediet and @rebornix as I don't believe this is a git extension issue.

**Comment by rebornix** [comment] 2024-12-09 19:22
"view untracked changes" should probably open notebook diff editor in this case.

**Comment by DonJayamanne** [comment] 2024-12-10 00:44
Duplicate of https://github.com/microsoft/vscode/issues/199613

**Closed by DonJayamanne** 2024-12-10 00:44 UTC
Labels: bug, notebook
