### ISSUE TITLE
JSDoc snippet has some spacing issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21541] opened 2017-02-28 06:02 UTC
See attached video I would expect a space after the second parameter and also for the summary in the beginning:

![panel-red](https://cloud.githubusercontent.com/assets/900690/23393552/eac56602-fd83-11e6-80ad-cefe1fec57ee.gif)

**Comment by matheusrocha89** [comment] 2017-02-28 11:56
@bpasero I want to help to fix this, do you know where should I start?

**Comment by bpasero** [comment] 2017-02-28 12:00
@matheusrocha89 I suggest to let @mjbvz comment

**Comment by mjbvz** [comment] 2017-02-28 22:10
@bpasero I was unable to repo this in an new workspace but can in the VSCode workspace. I believe tslint is the root cause. It removes the trailing whitespace on format. Can you confirm that?

**Comment by bpasero** [comment] 2017-03-01 05:10
@mjbvz I am not running with format on save, but maybe our defaults kick in? here are my settings:

```json
{
	"files.autoSave": "afterDelay",
	"editor.wordWrap": "off",
	"editor.folding": false,
	"explorer.openEditors.visible": 0,
	"workbench.editor.showTabs": false,
	"workbench.editor.enablePreview": false,
	"typescript.check.tscVersion": false,
	"window.zoomLevel": 1,
	"terminal.integrated.fontFamily": "Menlo",
	"terminal.integrated.fontSize": 12,
	"terminal.integrated.lineHeight": 1.6,
	"extensions.autoUpdate": true,
	"diffEditor.renderIndicators": false,
	"window.titleBarStyle": "custom",
	"workbench.welcome.enabled": false,
	"terminal.integrated.shell.osx": "/Users/bpasero/bin/vscode-shell",
	"git.confirmSync": false,
    "debug.inlineValues": true,
    "workbench.colorTheme": "Default Light+"
}
```

**Comment by zkirill** [comment] 2017-03-12 19:48
Wouldn't this violate tslint (no-trailing-whitespace)?

**Comment by mjbvz** [comment] 2017-03-14 01:35
The vscode workspace has `"files.trimTrailingWhitespace": true,` which I believe is causing this

**Comment by mjbvz** [comment] 2017-03-22 20:40
Closing this as a duplicate of #15070

**Closed by mjbvz** 2017-03-22 20:40 UTC
Labels: duplicate, format, javascript, typescript
