### ISSUE TITLE
Lone child folder always expands when `explorer.compactFolders` is disabled

### ISSUE THREAD

**Issue by dkaste** [microsoft/vscode#130732] opened 2021-08-13 00:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Fedora 34

Steps to Reproduce:

1. Ensure that the setting `explorer.compactFolders` is **disabled**
2. Create folder `a`
2. Create folder `a/b` (this must be the only child folder in `a`)
3. Create file `a/b/c`
4. Collapse all folders in sidebar explorer
5. Expand folder `a`
6. Observe that `b` is also unexpectedly expanded

**Comment by jeanp413** [comment] 2021-08-13 18:54
That's intended and is a feature of the tree to auto-expand nodes with a single children
https://github.com/microsoft/vscode/blob/53f597fe6b3df8da082264b644f8ce80b49d8dd3/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L408

**Comment by lramos15** [comment] 2022-12-28 16:30
Closing this is it is as designed as jeanp413 points out. Will use https://github.com/microsoft/vscode/issues/145510 for tracking.

**Closed by lramos15** 2022-12-28 16:30 UTC
Labels: bug, help wanted, file-explorer
