### ISSUE TITLE
Tooltip info overlapped with "read less" icon "x" for vcformat related property

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode#106217] opened 2020-09-07 07:56 UTC
VSCode Version: VSCode 1.48.2
Steps to Reproduce:

1. Install VSCode
2. Install C++ extension
3. Open file "settings.json"
4. Input vcformat related property and check the tooltip info

Expected:
The tooltip info display correctly

Actual:
Tooltip info overlapped with "read less" icon "x" 
(Repro on Windows, Linux and Mac)

Mac:
![image](https://user-images.githubusercontent.com/37648162/92362449-98070380-f122-11ea-837b-7808dc1bcb6a.png)

![image](https://user-images.githubusercontent.com/37648162/92362472-a05f3e80-f122-11ea-8bde-647ebf50eb0a.png)

Linux:
![image](https://user-images.githubusercontent.com/37648162/92362402-89205100-f122-11ea-92b1-923c946c71a5.png)

Windows:
![image](https://user-images.githubusercontent.com/37648162/92362294-61c98400-f122-11ea-903e-11309d951242.png)

**Comment by alexr00** [comment] 2020-09-07 10:14
Duplicate of https://github.com/microsoft/vscode/issues/106169

**Closed by alexr00** 2020-09-07 10:14 UTC
