### ISSUE TITLE
search keybinding text resets

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#34873] opened 2017-09-23 09:08 UTC
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. search a keybinding in keyboard shortcut tab, like typing `delete` in text area.
2.go to another tab like task.json
3. go back to keyboard shortcuts tab, text area is empty. the `delete` keyword is not there.

vscode suppose to store the `delete` keyword and also the search result

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment] 2017-11-27 08:37
Duplicate of #23543

**Closed** 2017-11-27 08:37 UTC
Labels: *duplicate, settings-editor
