### ISSUE TITLE
Allow key bindings to chain commands

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6617] opened 2016-05-21 20:53 UTC
Currently I think the only way to perform multiple commands in succession is to create an extension. It would be good if this was supported by keybindings.json. 

See http://stackoverflow.com/q/37009184/1156119

**Comment by Tyriar** [comment] 2016-11-11 22:03
Suggested syntax, it also shows how useful it can be:

```js
{
  "key": "ctrl+`",
  "command": [
    "workbench.action.toggleMaximizedPanel"
    "workbench.action.terminal.focus"
  ],
  "when": "!terminalFocus"
}
```

**Comment by Tyriar** [comment] 2016-11-22 20:54
https://marketplace.visualstudio.com/items?itemName=geddski.macros looks like a workaround for this for now.

**Comment by whitecolor** [comment] 2017-04-07 03:39
This would be useful to have outof the box.

**Comment by usernamehw** [comment] 2018-01-02 20:21
@Tyriar, isn't this a duplicate of https://github.com/Microsoft/vscode/issues/871 ?

**Comment by Tyriar** [comment] 2018-01-02 20:52
@usernamehw looks like it, thanks!

**Closed** 2018-01-02 20:52 UTC
Labels: *duplicate, feature-request, keybindings
