### ISSUE TITLE
Theme is not working properly with VSCode 1.41.1

### ISSUE THREAD

**Issue by JalpeshVadgama** [microsoft/vscode#87952] opened 2020-01-01 06:07 UTC
Current  VScode Version 1.4.1. It seems to be broken in lots of themes there are some blocks which show under a different color.

Here are the deatils. 

Here is my Visual Studio Code version
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

I'm using on my ThinkPad and resolution is 2560 * 1440.

Please see attached screenshot. You can see that there are some places where colors are not proper. I'm sure others who have got updated will have the same issue.

**Shades of purple theme:**:

<img width="1111" alt="bug2" src="https://user-images.githubusercontent.com/5141580/71638531-60d57e00-2c88-11ea-910f-e72d1c437bf5.png">

<img width="1074" alt="bug1" src="https://user-images.githubusercontent.com/5141580/71638533-6763f580-2c88-11ea-938a-683fe060c947.png">

**Material theme:**:

<img width="1277" alt="bug3" src="https://user-images.githubusercontent.com/5141580/71638541-9ed2a200-2c88-11ea-9181-71c21c55456a.png">

**MoonLight theme:**:

<img width="1277" alt="bug3" src="https://user-images.githubusercontent.com/5141580/71638633-fd991b00-2c8a-11ea-8d13-c19a508083ea.png">

<img width="1265" alt="bug4" src="https://user-images.githubusercontent.com/5141580/71638636-02f66580-2c8b-11ea-9db8-48c9df0f8831.png">

I have also tried removing all the extension and customization and still, the problem persist. Even tried using windows insider edition but problem is still there.

Please fix this asap. Let me know if more information required.

**Comment by Mudassar045** [comment] 2020-01-01 06:53
> Current VScode Version 1.4.1. It seems to be broken in lots of themes there are some blocks which show under a different color.
> 
> Here are the deatils.
> 
> Here is my Visual Studio Code version
> Version: 1.41.1 (user setup)
> Commit: [26076a4](https://github.com/microsoft/vscode/commit/26076a4de974ead31f97692a0d32f90d735645c0)
> Date: 2019-12-18T14:58:56.166Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.18362
> 
> I'm using on my ThinkPad and resolution is 2560 * 1440.
> 
> Please see attached screenshot. You can see that there are some places where colors are not proper. I'm sure others who have got updated will have the same issue.
> 
> **Shades of purple theme:**:
> 
> <img alt="bug2" width="1111" src="https://user-images.githubusercontent.com/5141580/71638531-60d57e00-2c88-11ea-910f-e72d1c437bf5.png">
> 
> <img alt="bug1" width="1074" src="https://user-images.githubusercontent.com/5141580/71638533-6763f580-2c88-11ea-938a-683fe060c947.png">
> 
> **Material theme:**:
> 
> <img alt="bug3" width="1277" src="https://user-images.githubusercontent.com/5141580/71638541-9ed2a200-2c88-11ea-9181-71c21c55456a.png">
> 
> **MoonLight theme:**:
> 
> <img alt="bug3" width="1277" src="https://user-images.githubusercontent.com/5141580/71638633-fd991b00-2c8a-11ea-8d13-c19a508083ea.png">
> 
> <img alt="bug4" width="1265" src="https://user-images.githubusercontent.com/5141580/71638636-02f66580-2c8b-11ea-9db8-48c9df0f8831.png">
> 
> I have also tried removing all the extension and customization and still, the problem persist. Even tried using windows insider edition but problem is still there.
> 
> Please fix this asap. Let me know if more information required.

Yes facing the same issue.
Version: 1.41.1
OS: Linux x64 5.0.0-37-generic
**Night Owl** by Sarah Drasner
![theme-breaking-night-owl](https://user-images.githubusercontent.com/24487349/71638865-40f48900-2c8d-11ea-8294-309621b659c1.png)

**Comment by aeschli** [comment] 2020-01-03 12:35
This is an Electron/Chromium issue. When code with `--disable-gpu`, this issues do not show.
@bpasero @deepak1556

**Comment by aeschli** [comment] 2020-01-03 12:36
Duplicate of https://github.com/microsoft/vscode/issues/87097

**Closed by aeschli** 2020-01-03 12:36 UTC

**Comment by JalpeshVadgama** [comment] 2020-01-06 06:17
So when can we expect a permanent fix for this?

**Comment by aeschli** [comment] 2020-01-06 08:31
@JalpeshVadgama I don't know. First we must understand where the problem lies. Electron, chromium, graphic driver, and then hope that component can provide an update.
