### ISSUE TITLE
Auto indent cannot be turned off

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/vscode#78674] opened 2019-08-08 04:57 UTC
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18 LTS

Steps to Reproduce:
My setting file has 
    "editor.autoIndent": false,
    "editor.detectIndentation": false,
    "editor.highlightActiveIndentGuide": false,
    "editor.renderIndentGuides": false,
    "editor.wrappingIndent": "none",
    "workbench.tree.renderIndentGuides": "none",
    "editor.insertSpaces": false

1. Create a text file, eg 1.txt
2. Press tab -> "aaa" -> press enter

Observed: 
Then 2nd line starts with indent automatically.
![image](https://user-images.githubusercontent.com/12282281/62676040-44921700-b95e-11e9-8c22-778904d75430.png)

Expected
Then 2nd line should not with indent automatically. It should not have a indent.

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9527KGG** [comment] 2019-08-08 05:00
I just want to basic/notepad experience. So I want to turn it off. Thanks.

**Comment by octref** [comment] 2019-08-09 15:30
Duplicate of #5446.

**Closed by octref** 2019-08-09 15:30 UTC

**Comment by 9527KGG** [comment] 2019-08-09 17:15
5446 is more than 3 years old. Come on, please do sth.
