### ISSUE TITLE
Add an option to choose if comments should be automatically folded with code

### ISSUE THREAD

**Issue by mundodisco8** [microsoft/vscode#111876] opened 2020-12-04 10:32 UTC
#### The feature

Provide a toggle that allows users to select if comments should remain unfolded when using autofolding with `fold all` or `fold level X`.

#### Explanation

When I fold my code with "Fold All" or "Fold Level X", my comments are folded too. I use decorated comment blocks to separate areas of my code thematically, and I like to keep the details of a function visible even if the code is collapsed. The current behaviour of folding comments clashes a bit with my workflow, as I have to unfold a bunch of areas after the autofold. Also, I use VS Code to edit files that I might also change at some point on the IDE provided by my manufacturer (I mostly use VS Code for embedded dev). These external changes sometimes trigger a general code unfold, so I have to frequently autofold my code.

I see how some users would like the current behaviour to be kept (or even be the default), so that's why I suggest that this behaviour could be controlled by a flag in the settings. The setting would affect autofolding only, while keeping comments foldable by clicking on the downward pointing arrow thingy.

I mainly use C/C++ and Python, but I guess other languages could benefit, as long as their folding range providers tell VS Code what is a comment and what is not. I created a feature request in the C/C++ extension but they pointed out that this should probably be handed by VS Code (https://github.com/microsoft/vscode-cpptools/issues/6615).

#### Example
1. Write a multiline comment
2. Autofold all the file or its level
3. Comments are automatically collapsed.

![Folding](https://user-images.githubusercontent.com/8402707/101152853-8945c500-361b-11eb-9a24-5c8305e99caf.gif)

#### Expected Behaviour

With the new flag set to "don't autofold comments", all code is folded, but comments are not

![101017458-09a7ef80-3562-11eb-96b9-1cb6e33a1c0d](https://user-images.githubusercontent.com/8402707/101153027-c14d0800-361b-11eb-9469-43d61127e9fe.png)

**Comment by aeschli** [comment] 2020-12-04 11:09
duplicate of #48556

**Closed by aeschli** 2020-12-04 11:09 UTC
