### ISSUE TITLE
Cannot click on chrome dev tools "Paused in debugger"  overlay with custom titlebar

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55444] opened 2018-07-31 09:36 UTC
Steps to Reproduce:

1. On windows using custom title bar
2. Open chrome dev tools for editor and set a breakpoint that will be hit. Hit that breakpoint
3. Try clicking on the arrow in the paused in debugger menu

![screen shot 2018-07-31 at 11 34 48 am](https://user-images.githubusercontent.com/12821956/43451684-cc37c8cc-94b5-11e8-9690-5c4e0fa6bd30.png)

**Bug**
You cannot click on the area of the popup that is on top of the title bar. You can click on the very bottom edge of the popup where it is not overlapping with the title bar

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment] 2018-07-31 19:01
duplicate of #54544

**Closed by sbatten** 2018-07-31 19:01 UTC
