### ISSUE TITLE
Error with keyboard layout switc

### ISSUE THREAD

**Issue by prospero78** [microsoft/vscode#84200] opened 2019-11-08 05:20 UTC
Issue Type: <b>Bug</b>

Wuth im switch keyboard layout -- active editor lost focus input.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2550K CPU @ 3.40GHz (4 x 3068)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 1|
|Memory (System)|7.75GB (3.42GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
golang-tdd|joa|0.0.9
go-prof|Max|0.0.4
rainbow-csv|mec|1.3.1
vscode-language-pack-ru|MS-|1.40.2
python|ms-|2019.10.44104
Go|ms-|0.11.9
color-highlight|nau|2.3.0
go-critic|nev|0.1.0
goasm|qui|0.0.4
code-settings-sync|Sha|3.4.3
go-mod-grapher|xmt|1.1.1

</details>

**Comment by alexandrudima** [comment] 2019-11-08 08:22
@prospero78 I am sorry, I don't fully understand what do you mean? What exact steps are you doing, what is happening and what is expected?

**Comment by prospero78** [comment] 2019-11-11 05:07
Im press <Alt>-<Shift> for change keyboard layout and this moment active editor lost focus.
In Geany/Kate/etc this behavior not detect. Wath im press <Shift><Alt> -- keyboard swith process have normal end.

**Comment by alexandrudima** [comment] 2019-11-11 07:40
Possible duplicate of https://github.com/microsoft/vscode/issues/84227

**Closed** 2019-11-11 22:05 UTC
Labels: needs more info
