### ISSUE TITLE
Debug with Nodejs and nodemon keep getting restart upon 'Attach to Process'

### ISSUE THREAD

**Issue by alemhnan** [Microsoft/vscode#21783] opened 2017-03-02 14:50 UTC
- VSCode Version: 1.10.1
- OS Version: Mac 10.12.3
- Node Version: 6.10.0

Steps to Reproduce:

1. Launch a node process in console with nodemon `nodemon --debug server.js`
2. Click `Attach to Process` in vcode.
3. The server will be restarted by nodemon even though no files are changed
4. vcode throws and error: `Request 'evaluate' was cancelled because Node.js is unresponsive.`

Before this release the nodemon wasn't detecing changes all the workflow was fine. Now if the server is slow to start I cannot attach vscode to it. I tried to use the timeout option in launch.json with no luck.

**Comment by isidorn** [comment] 2017-03-03 10:11
I believe duplicate of https://github.com/Microsoft/vscode/issues/21681

**Closed by isidorn** 2017-03-03 10:11 UTC
