### ISSUE TITLE
VSCode does not format HTML template elements

### ISSUE THREAD

**Issue by MannikJ** [Microsoft/vscode#7125] opened 2016-06-02 09:25 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10

I figured out that the built-in formatter does nothing when applied to an HTML template element. As far as I see it is really the template tag and all it's content that is completely ignored by the formatter. 
Other HTML files are formatted properly. When using modern component-based frameworks like Aurelia, you're writing nothing else than templates and for me auto-formatting is indispensable.

Steps to reproduce:

1. create a .html file
2. paste in an example template with messed up indentation like:

		<template>
		<require from="components/nav-bar.html"></require>
		<require from="bootstrap/css/bootstrap.css"></require>
		<nav-bar router.bind="router"></nav-bar>
		<div class="page-host">
		<router-view></router-view>
		</div>
		</template>

3. Press _Alt+Shift+F_ to format the file

**Comment by aeschli** [comment] 2016-06-15 20:14
duplicate of #5426

**Closed by aeschli** 2016-06-15 20:14 UTC
