### ISSUE TITLE
[js] highlight method & function references

### ISSUE THREAD

**Issue by sebreh** [Microsoft/vscode#3886] opened 2016-03-08 21:13 UTC
In VS Code (0.10.10 or earlier), methods are not highlighted. I know [a lot of work](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9732534-improve-syntax-coloring) has gone into improving the highlighting, but to me method calls is one of the most important ones to highlight, and a showstopper personally for working effectively with my code. Here is a comparison screenshot of a code snippet in Atom and VS Code. As you can see, Atom highlights the method names as expected (blue), but in VS Code variables and methods are all the same.

<img width="485" alt="atom_vs_vscode" src="https://cloud.githubusercontent.com/assets/328169/13616643/1a929480-e57b-11e5-82ad-a15f0d5f232a.png">

This does not seem to be theme specific either, since I tried it with the `--disable-extensions` flag too using the default theme.

I hope this is fairly easy to add, because I am extremely impressed with the speed and overall features of VS Code, and would love to be able to use it full time!

Keep up the good work :+1:

**Comment by lepkon** [comment] 2016-03-09 04:09
I fullyagree, in fact I have switched to Atom for that ONE reason and only use VScode for git as I can easily copy and paste comment to git.

**Comment by felixfbecker** [comment] 2016-03-09 08:57
To be fair, Atom's color theme is _extremely_ colorful, it almost looks childish to me. So I would not want Code's theme to look completely like Atom's. But look at this snippet in Code:
![image](https://cloud.githubusercontent.com/assets/10532611/13629956/c7b70a22-e5dc-11e5-9a63-2dfc63ee2bfe.png)
```ts
Promise.all(connections.map(connection =>
    connection.sendBreakpointListCommand()
        .then(response => Promise.all(
            response.breakpoints
                .filter(breakpoint => breakpoint instanceof xdebug.ExceptionBreakpoint)
                .map(breakpoint => breakpoint.remove())
        ))
        .then(() => {
```

8 lines of TypeScript code without any color at all. It feels like I'm programming in Notepad. I know, this also contains some bugs, for example `instanceof` should be highlighted as a keyword. But even then, at least in the Dark/Light+ themes, syntax highlighting should not be restricted to only color keywords, strings, comments and symbols.

**Comment by dmurawsky** [comment] 2016-03-09 16:40
I used to have function and method highlighting but it's gone since the update that added code-folding

**Comment by aeschli** [comment] 2016-03-10 09:12
@dmurawsky What theme were you using? Is it with JavaScript? In the default themes we never had an method and function _references_ highlighting. We highlight the _definitions_ in the Light+/Dark+ themes. Make sure you are using one of these.

**Comment by dmurawsky** [comment] 2016-03-10 14:12
Nice! I went to Preferences -> Color Theme and switched it from "Dark (Visual Studio)" to "Dark+ (default dark)" and got even more coloring than I had before.

**Comment by felixfbecker** [comment] 2016-03-10 14:22
@aeschli my screenshot from above is with Dark+ though.

**Comment by aeschli** [comment] 2016-03-10 14:45
@felixfbecker Your code snippet happens to contain no element that we color. Except 'instanceof' which is a https://github.com/Microsoft/TypeScript-TmLanguage/issues/37

That happens to be the design of our default themes.

**Comment by felixfbecker** [comment] 2016-03-10 16:35
@aeschli Yeah, and I think that is not appropiate for a "colorful" Dark+ theme. At least one of
 - method names (`.then()`, `.all()`)
 - properties (`response.breakpoints`)
 - operators (`=>`)
 - variables (`connections`)

should get a some color. It seriously feels like I'm writing in Notepad, it is hard to read the code. I have snippets like this everywhere.

**Comment by jefkoslowski** [comment] 2016-03-15 13:22
I totally agree with the OP. Please, support method/function highlight like Atom/ST does. Another screenshot (source https://twitter.com/markgdyr/status/709717800860913664):

![VS Code](http://i.imgur.com/gCD3ttF.png)

> To be fair, Atom's color theme is extremely colorful, it almost looks childish to me. So I would not want Code's theme to look completely like Atom's.

I think this should be a theme author decision, its not VS Code responsibility.

**Comment by egamma** [comment] 2016-07-04 09:22
For now we have made an extension available that is based on the atom-js grammar, please give it a try.

Extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

**Comment by sebreh** [comment] 2016-07-04 10:30
Nice! Mostly works except that arguments to global functions doesn't seem to be properly identified and highlighted. They all end up the same color. See screenshot to compare to instance method:

<img width="462" alt="screen shot 2016-07-04 at 12 29 46" src="https://cloud.githubusercontent.com/assets/328169/16557967/060bcb5c-41e3-11e6-8687-40324b4f8768.png">

In the screenshot, I would expect the string argument to the global function to have the same green color as the one passed to the instance method.

**Comment by whitecolor** [comment] 2016-08-21 19:06
Needed for typescript

**Comment by emzero** [comment] 2016-09-22 20:11
What's the status on this? 
Are the people on https://github.com/Microsoft/TypeScript-TmLanguage working on it?

**Comment by emzero** [comment] 2016-09-27 00:24
This has just been implemented in the Typescript TextMate grammar files.
https://github.com/Microsoft/TypeScript-TmLanguage/pull/270

Will it be released in the next VSCode version?

**Comment by saada** [comment] 2016-10-26 21:58
@egamma that's nice but it doesn't work with all themes :(

**Comment by egamma** [comment] 2016-10-28 21:31
@emzero yes, the next version of vscode will include the new tmGrammar out of the box. 

You can give it a try from our  [insiders build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) today: http://code.visualstudio.com/Download#insiders

**Comment by emzero** [comment] 2016-10-28 21:39
@egamma I'm already using the insiders build but with the "Latest TypeScript and JavaScript Grammar" extension. Not sure if this is needed or not.

**Comment by egamma** [comment] 2016-10-31 13:13
@emzero you no longer need the extension, it is included in the typescript/javascript support that comes with the insiders version.

**Comment by mjbvz** [comment] 2016-11-18 23:11
I just tried out some of the example snippets that have been shared, and the bulk of the identified issue seem to have been resolved in 1.7+. Here's screenshots using the dark+ theme:

![screen shot 2016-11-18 at 3 02 00 pm](https://cloud.githubusercontent.com/assets/12821956/20449788/64243fe8-ada0-11e6-9583-7a5d3d509788.png)

![screen shot 2016-11-18 at 3 06 09 pm](https://cloud.githubusercontent.com/assets/12821956/20449807/830f332c-ada0-11e6-8102-2b6b63bcbd02.png)

![screen shot 2016-11-18 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/12821956/20449795/693cbd16-ada0-11e6-9b78-22bcebdff774.png)


Most of the built in themes also seem to work, although some are intentionally less colorful:

![nov-18-2016 15-09-06](https://cloud.githubusercontent.com/assets/12821956/20449866/e8ee1b04-ada0-11e6-8dbc-678ec68b5dbf.gif)


Closing this issue, but please open bugs if you notice any problems or have ideas on how syntax highlighting could be further improved. 

Thanks.

**Closed by mjbvz** 2016-11-18 23:11 UTC
Labels: feature-request, js, themes

**Comment by omerdn1** [comment] 2017-08-17 16:08
What are you guys using to highlight references? This feature does not come with my VSCode by default and I've tried some extensions that didn't work.

**Comment by mjbvz** [comment] 2017-08-18 07:07
@omerdn1 I don't understand what you are asking here. Can you please file a new issue with a small example and an explanation of the expected behavior
