### ISSUE TITLE
take linebreaks into account when searching

### ISSUE THREAD

**Issue by Vict0rSch** [Microsoft/vscode#54559] opened 2018-07-18 09:54 UTC
I want to replace 

```javascript
import Dialog, {
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  withMobileDialog,
} from 'material-ui/Dialog';
```

with 

```javascript
import DialogActions from '@material-ui/core/DialogActions';
import DialogContent from '@material-ui/core/DialogContent';
import DialogContentText from '@material-ui/core/DialogContentText';
import DialogTitle from '@material-ui/core/DialogTitle';
import withMobileDialog from '@material-ui/core/withMobileDialog';
```

Ideally, when selecting the former code, `cmd + shift + f` would search for other occurances **taking linebreaks into account** and I'd be able to replace with the latter code  **taking linebreaks into account** again. 

Right now, the text searched for is single-lined into `import Dialog, {   DialogActions,   DialogContent,   DialogContentText,   DialogTitle,   withMobileDialog, } from 'material-ui/Dialog';` which has no occurrences as it is split on several lines in the code.

**Comment by sandy081** [comment] 2018-07-19 15:30
Duplicate of #13155

**Closed** 2018-07-19 15:37 UTC
Labels: *duplicate, search, search-replace
