### ISSUE TITLE
Debug hover should have flexible horizontal size

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode#6815] opened 2016-05-24 16:00 UTC
> From https://github.com/OmniSharp/omnisharp-vscode/issues/370 as part of @gregg-miskelly's request.

When you hover over a variable and expand some variables on debug mode, you see the text is not fitting the box:

![image](https://cloud.githubusercontent.com/assets/328122/15507248/bb6c7d2a-21c2-11e6-84ca-b34feaa7e22e.png)

VS Code Info:

```
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:38:00.094Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

dotnet CLI info:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by isidorn** [comment] 2016-05-25 07:56
Yes, currently the debug hover has fixed size. For inspecting long variables we recommend using the debug console.

**Comment by weinand** [comment] 2017-04-05 10:35
duplicate of #1976

**Closed by weinand** 2017-04-05 10:35 UTC
Labels: debug, feature-request
