### ISSUE TITLE
Opening file with source:line breaks Cmd+D "Add Next Occurance"

### ISSUE THREAD

**Issue by bbugh** [microsoft/vscode#79460] opened 2019-08-19 17:24 UTC
- VSCode Version: 1.37.1
- OS Version: Mac 10.12.6

**Issue**

Here's a weird one for you! This is 100% reproducible, and only appeared recently.

Whenever I open Visual Studio Code using line numbers (from iTerm2 shortcut or others), the Cmd+D shortcut key to select other instances doesn't work until the VSCode window loses and regains focus.

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

**Part 1**

1. Have iTerm2
2. Cmd + Click on a file name 
3. Once VSCode opens, Cmd+D on some text that should have another match
4. Notice that the "Selection" menu item at the top flashes as activated, but no new matching selections are selected

**Part 2**
1. Click around in VSCode, in the same editor, other editors, etc.
2. Press Cmd+D
3. Notice that the "Selection" menu item at the top flashes as activated, but no new matching selections are selected

**Part 3**
1. Cmd+Tab to another window
2. Cmd+Tab back to VSCode
3. Notice that the Cmd+D key shortcut is now working as expected.

**Comment by alexandrudima** [comment] 2019-08-20 12:47
@bpasero Could we have some bug where we don't know the current focused window at the beginning and then we don't send the command invocation?

Possibly related -- #71553

**Comment by bpasero** [comment] 2019-08-20 12:54
> @bpasero Could we have some bug where we don't know the current focused window at the beginning and then we don't send the command invocation?

@alexandrudima how can we detect a keypress in the first place if the window is not focused? Are you maybe thinking of macOS where all keys go through the top level menu and not the active window? But this seems to be Windows...

**Comment by bbugh** [comment] 2019-08-20 12:58
Hi, I clarified in the first message that it's Mac OS. I originally pasted in the version number but didn't specify that it was Mac, sorry about that.

**Comment by bpasero** [comment] 2019-08-20 13:02
Got it, moving to @sbatten who owns menu interactions.

**Comment by bbugh** [comment] 2019-08-20 13:05
#71553 does seem possibly related, but opening files from the command line (for me) does not exhibit the behavior I described in the issue. I am able to Cmd+D fine in that scenario.

I tried a couple of other ideas:

- `code Gemfile` -> Cmd+D works fine
- `Cmd+Left Click on the Gemfile` -> Cmd+D works fine
- `Cmd+Left Click on "Gemfile:97"` -> Cmd+D does not work. 

It appears to be related to however VSCode is opening files and going to a specific line number.

**Comment by alexandrudima** [comment] 2019-08-20 14:14
@bpasero The menu bar calls `IWindowService.sendToFocused` -- [here it is](https://github.com/microsoft/vscode/blob/3d5238589ece772a028a79611422a92f0f6caea7/src/vs/platform/menubar/electron-main/menubar.ts#L727). Since the menu bar is flashing, it means it is eating up the keybinding so the keybinding does not make it to the renderer and we are relying on `vscode:runAction` to be sent from the main process to the window...

My guess would be that the `IWindowService.sendToFocused` is not working sometimes, when launched in very specific ways. I could reproduce #71553 on my mac with https://github.com/microsoft/vscode/issues/71553#issuecomment-479049768.

**Comment by bpasero** [comment] 2019-08-20 14:32
@alexandrudima I tried to setup https://github.com/microsoft/vscode/issues/71553#issuecomment-479049768 and my menu bar does not flash and `Cmd+D` works to select words, here is proof:

![before](https://user-images.githubusercontent.com/900690/63356430-0cc89d80-c368-11e9-9c02-991703969c6b.gif)

I used a fresh user data dir to rule out the possibility of a setting having an impact. What are you doing different?

**Comment by bpasero** [comment] 2019-08-20 14:36
@alexandrudima oh, now that I actually look into the menu code, [this seems very fishy](https://github.com/microsoft/vscode/blob/d746dccedab9233d24f1cac2e131e8aca8b4d263/src/vs/platform/menubar/electron-main/menubar.ts#L702):

```ts
// We make sure to not run actions when the window has no focus, this helps
// for https://github.com/Microsoft/vscode/issues/25907 and specifically for
// https://github.com/Microsoft/vscode/issues/11928
// Still allow to run when the last active window is minimized though for
// https://github.com/Microsoft/vscode/issues/63000
let activeWindow = this.windowsMainService.getFocusedWindow();
if (!activeWindow) {
	const lastActiveWindow = this.windowsMainService.getLastActiveWindow();
	if (lastActiveWindow && lastActiveWindow.isMinimized()) {
		activeWindow = lastActiveWindow;
	}
}
```

@sbatten it looks like we fail to send the action to the last active window at least? any particular reason?

**Comment by sbatten** [comment] 2019-08-21 05:49
@bpasero based on the issues in the comments, it seems like that would break things elsewhere, no? That whole section has you for *git blame*.

**Comment by bpasero** [comment] 2019-08-21 07:31
Ok, I think it is fine to leave the code as it is but then I wonder why starting Code from the command line would not correctly put focus into the window that opens. Or at least, why Electron would not return the window back that is opening. 

To clarify: it is the same window that gets opened, not a new one right?

Do people see the window with inactive title color? Does it visually look focused?

**Comment by bbugh** [comment] 2019-08-21 10:53
Correct, it is the same OS window that gets opened. VS Code is visually (and behaviorally) active, I am able to move the cursor, type, run commands, select text, etc. 

However, while testing your inquiry I found a new data point. **This issue only happens if the file is already open in an editor. If the file is being opened into a new editor, it works as expected.**

**Reproduction**

1. Close all editor groups
1. `Cmd+Click` open a file with a name/line number (like `Gemfile:18`)
1. Notice `Cmd+D` works.
1. Return to terminal, `Cmd+Click` the same file name/line number
1. Notice `Cmd+D` does not work.
1. Open any QuickPick (`Cmd+T`, `Cmd+P`, etc.)
1. Close the QuickPick with `Escape` or by clicking anywhere else on the Code window.
1. Notice `Cmd+D` works again

**Related shortcut keys not working**

I noticed while doing these reproduction steps, that this issue also affects the `Shift+Cmd+L` "Select All Occurrences" shortcut.

**Additional Testing**

I wondered if this issue affected other "what's under the cursor?" commands, and they seem to be working fine.

- I activated "Developer: Inspect TM Scopes" with a shortcut key, and it showed the correct scope in both scenarios.
- "Go to Symbol in Workspace" with `Cmd+T` (which defaults to whatever is under the cursor) and it correctly read what was under the cursor. 

Hope this helps.

**Comment by bpasero** [comment] 2019-08-21 11:36
@bbugh do other keybindings like `Cmd+W` work in that case and close the editor? Because if yes, then this would be an issue inside the workbench/editor and not outside.

**Comment by bbugh** [comment] 2019-08-21 12:58
Yes, all of the other editor shortcuts I’ve tried work fine. I usually don’t even notice an issue opening files from the terminal unless I try to select occurrences. The issue seems to be isolated to the “select matches” behavior shortcuts.

**Comment by bpasero** [comment] 2019-08-21 13:33
@alexandrudima is there anything specific to that command compared to closing editor?

**Comment by alexandrudima** [comment] 2019-08-22 21:00
No, not that I can think of.

**Comment by bpasero** [comment] 2019-08-23 07:36
@bbugh can you do an experiment and run "code --verbose" which will print a log statement to the console everytime a command is executed and then check the dev tools console for output? Should look like this:

![before](https://user-images.githubusercontent.com/900690/63575085-84c1de00-c589-11e9-86a7-17d9f9d1beb2.gif)

**Comment by bbugh** [comment] 2019-08-23 16:07
@bpasero Here's a gist with the logs, reproducing the issue. I put a break where I first opened the file (`Cmd+D` works), then another break when I opened it the second time (when `Cmd+D` doesn't work). Both times I selected a word and tried to select all instances, but I didn't see any logs related to that.

https://gist.github.com/bbugh/b01c2c591fbd9a6afeb86ea1c2271a1f

**Comment by bbugh** [comment] 2019-08-23 18:46
@bpasero the image didn't load on my phone earlier and I misunderstood what you meant. I re-ran vscode with `code --verbose`, then opened the developer console. I reproduced the issue. 

When the issue is happening, `Cmd+D` does not show anything in the developer console. When the issue is not happening, `CommandService#executeCommand editor.action.addSelectionToNextFindMatch` correctly shows up in the console.

It appears that something is preventing the command from activating altogether.

**Comment by bpasero** [comment] 2019-08-24 06:39
@bbugh would you be willing to try to reproduce this running VSCode out of sources so that we can debug this further? There are instructions at https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by bpasero** [comment] 2019-09-04 09:06
@bbugh can you do this:
* download and run this [build](https://az764295.vo.msecnd.net/insider/109add76dad3dd1cbe05215d26cb62be6dbfdc47/VSCode-darwin-insider.zip)
* from the command line with `code-insiders --verbose`
* do your keybinding thing until it fails
* attach the output you see from the console

I added some logging for forwarding commands to the window.

**Comment by bbugh** [comment] 2019-09-04 13:00
@bpasero thank you for the reminder. 

1. I created a new user account so there would be external/configuration interference. 
1. I downloaded that build and ran with `--verbose`
1. I was unable to reproduce the issue using your insider 1.38 version. 
1. I was able to immediately reproduce the issue with the installed latest public `1.37`.

I recorded the reproduction if you'd like to see it, but it seems like 1.38 fixed the issue?

**Comment by bpasero** [comment] 2019-09-04 13:30
@bbugh hm it should be version 1.39 though, can you check? Could it be by accident you got updated (actually downgraded)? Maybe disable updates from settings to be safe.

![image](https://user-images.githubusercontent.com/900690/64259183-e63e6100-cf28-11e9-8156-912705eabc12.png)

**Comment by bbugh** [comment] 2019-09-04 15:57
Sorry, you're right, it was 1.39. 

```
Version: 1.39.0-insider
Commit: 109add76dad3dd1cbe05215d26cb62be6dbfdc47
Date: 2019-09-04T05:24:38.192Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by bpasero** [comment] 2019-09-04 16:07
Wow good to know, looks like my changes fixed it then.

**Comment by bpasero** [comment] 2019-09-05 09:18
@bbugh still good with latest insider release from today? Then I would go ahead and close this.

**Comment by bpasero** [comment] 2019-09-10 05:19
Please report back otherwise.

**Closed** 2019-09-10 05:18 UTC
Labels: keybindings, mac, needs more info, workbench-menu

**Comment by bpasero** [comment] 2019-09-10 06:46
Actually duplicate of https://github.com/microsoft/vscode/issues/71553#issuecomment-520189587
