### ISSUE TITLE
Webview layer scroll position jumps around when scrolling up 

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96481] opened 2020-04-28 20:25 UTC
```
Version: 1.45.0-insider (user setup)
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:36:25.810Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Recording: https://memes.peet.io/img/20-04-9263f800-d242-4cbf-917f-b1c919ec9f84.webm

**Comment by rebornix** [comment] 2020-04-29 00:15
@connor4312 do you see this issue all the time? I think it's because some scroll events are missed and then the view position are not set correctly.

**Comment by connor4312** [comment] 2020-04-29 16:23
Hm, I'm not able to have this happen on a new instance today / after updating Insiders.

**Comment by rebornix** [comment] 2020-05-01 00:33
Fixed via https://github.com/microsoft/vscode/commit/e58fca86ce62a874f229df908c2ea2a78c9cda9e . @connor4312 please help try again from master or with tomorrow's Insiders, if you can't reproduce it, you can call it a verified.

**Closed by rebornix** 2020-05-01 00:33 UTC
Labels: bug, notebook
