### ISSUE TITLE
Webview steals keyboard focus/keybindings

### ISSUE THREAD

**Issue by babramczyk** [microsoft/vscode#113927] opened 2021-01-06 17:58 UTC
- VSCode Version: 1.52.1
- OS Version: macOS 10.15.6

## The Problem

When opening a preview (i.e. for markdown), keyboard events stop working. Sometimes they stop working right away, other times it takes a few seconds

Steps to Reproduce:

There's many ways to reproduce this, but this one encapsulates the problem

1. Open a markdown file
2. Enter the command to open the preview (default `⌘K + V`) (this will focus the webview preview)
3. Emit a keybinding for something (e.g. `⌘⇧P` to open the command palette)
4. Focus the webview again (in the command palette example, you can just press Esc)
5. Try another keybinding

The first one or two times, the keybindings work. But eventually, whenever that webview has focus, no keybindings seem to do anything. I'm guessing because the webview is capturing them without propagating them..?

Does this issue occur when all extensions are disabled?: Yes

## Video

In the video, even the screencast mode isn't picking up, but at the end when nothing is happening, I press `⌘⇧P` a few times.

https://user-images.githubusercontent.com/16885191/103803682-8113e780-5016-11eb-84aa-5481e1254a40.mov

**Comment by mjbvz** [comment] 2021-01-07 02:08
Duplicate of #110276

**Closed by mjbvz** 2021-01-07 02:08 UTC

**Comment by jace4511** [comment] 2021-01-07 02:53
> * VSCode Version: 1.52.1
> * OS Version: macOS 10.15.6
> 
> ## The Problem
> When opening a preview (i.e. for markdown), keyboard events stop working. Sometimes they stop working right away, other times it takes a few seconds
> 
> Steps to Reproduce:
> 
> There's many ways to reproduce this, but this one encapsulates the problem
> 
> 1. Open a markdown file
> 2. Enter the command to open the preview (default `⌘K + V`) (this will focus the webview preview)
> 3. Emit a keybinding for something (e.g. `⌘⇧P` to open the command palette)
> 4. Focus the webview again (in the command palette example, you can just press Esc)
> 5. Try another keybinding
> 
> The first one or two times, the keybindings work. But eventually, whenever that webview has focus, no keybindings seem to do anything. I'm guessing because the webview is capturing them without propagating them..?
> 
> Does this issue occur when all extensions are disabled?: Yes
> 
> ## Video
> In the video, even the screencast mode isn't picking up, but at the end when nothing is happening, I press `⌘⇧P` a few times.
> 
>  Screen.Recording.2021-01-06.at.11.55.29.AM.mov
