### ISSUE TITLE
Show Hover: Disable three dots abbreviation (Ctrl+K Ctrl+I)

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#66405] opened 2019-01-11 15:53 UTC
- VSCode Version: 1.30.2

Steps to Reproduce:

1. Hover over a variable on TypeScript or click `Ctrl+K, Ctrl+I` 
2. Select all and copy
3. Paste

You get these abbreviations:

```
let ffprobe_video_stream: {
    index: number;
    codec_name: string;
    codec_long_name: string;
    profile: string;
    codec_type: string;
    codec_time_base: string;
    codec_tag_string: string;
    codec_tag: string;
    width: number;
    height: number;
    ... 22 more ...;
    tags: {
        ...;
    };
}
```

The copy & pasted type is not usable anymore, it worked with previous vscode. I don't want the abbreviations with three dots. I constantly copy & paste type definitions, now I have to go to the definition to get them.

Here is the process why I even need them: 

I sometimes copy & paste JSON objects, and get their type using that hover tooltip, used to work. 

I sometimes copy & paste API type definitions to the React components (so that I don't make unneccessary dependencies between API and the component), and clean up the extra props. Now I can't do that either.

In my opinion you should not need to abbreviate that hover box, it has scrollbars and stuff. It was usable how it was.

**Comment by Ciantic** [comment] 2019-01-11 16:04
Here is the first use case:

Paste this to VSCode:
```
let ffprobe_video_stream = {
    index: 1,
    codec_name: "h264",
    codec_long_name: "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
    profile: "High",
    codec_type: "video",
    codec_time_base: "1/48",
    codec_tag_string: "avc1",
    codec_tag: "0x31637661",
    width: 1280,
    height: 720,
    coded_width: 1280,
    coded_height: 720,
    has_b_frames: 0,
    sample_aspect_ratio: "1:1",
    display_aspect_ratio: "16:9",
    pix_fmt: "yuv420p",
    level: 31,
    chroma_location: "left",
    refs: 1,
    is_avc: "true",
    nal_length_size: "4",
    r_frame_rate: "24/1",
    avg_frame_rate: "24/1",
    time_base: "1/24000",
    start_pts: 0,
    start_time: "0.000000",
    duration_ts: 14315000,
    duration: "596.458333",
    bit_rate: "1991287",
    bits_per_raw_sample: "8",
    nb_frames: "14315",
    disposition: {
        default: 1,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0
    },
    tags: {
        creation_time: "2010-01-10T08:29:06.000000Z",
        language: "und",
        handler_name: "(C) 2007 Google Inc. v08.13.2007."
    }
};
```
How do you get the type definition of that? It's not possible anymore, previously I could just hover it and get the type, remove the object and keep on going.

**Comment by mjbvz** [comment] 2019-01-11 18:51
Duplicate of https://github.com/Microsoft/TypeScript/issues/25784 and falls under #64566

Hovers are optimized for readability. Displaying giant type infos in the hover is generally not very helpful but #64566 tracks allowing collapsed areas of a hover (the `...`) to be expanded

**Closed by mjbvz** 2019-01-11 18:51 UTC
Labels: editor-hover, new release, typescript
