### ISSUE TITLE
Expose hidesExplorerArrows as user setting

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#56248] opened 2018-08-13 07:51 UTC
Hi, the top level icons-theme configuration `hidesExplorerArrows`is not exposed as user setting. My theme extension set it to `true` to hide arrows but users can't change it through vscode settings.

Is there a way to override it?

**Comment by nealot** [comment] 2018-08-13 18:49
Could this apply globally? i.e. enabling the option adds them to the outline, breadcrumbs, other extensions using the tree api, etc...

**Comment by aeschli** [comment] 2018-08-16 15:10
duplicate of #45400

**Closed by aeschli** 2018-08-16 15:10 UTC
Labels: feature-request, themes
