### ISSUE TITLE
New install of VSC x64 on Windows hogs CPU renders machine unresponsive

### ISSUE THREAD

**Issue by Mehuge** [Microsoft/vscode#33941] opened 2017-09-07 13:25 UTC
- VSCode Version: 1.15.1
- OS Version: Windows Server 2012 R2 (2GB Ram - It's a VM)

Steps to Reproduce:

1. Install VSC x64 or x32
2. Open Task Manager
3. Launch
4. Watch machine grind to a halt

![image](https://user-images.githubusercontent.com/99895/30164748-71d3e2a8-93d5-11e7-8dd2-13d003557c28.png)

Image shows the issue.  The issue happens with or without the folder opened in VSC (it was an issue directly from first launch).

Can't even close VSC with X or File->Exit, have to end task.

No extensions were installed, it was a clean install.  
Running with code --disable-extensions shows the same issue.

I uninstalled and installed the 32 bit version, and I get exactly the same problem.

Have now uninstalled completely.

**Comment by roblourens** [comment] 2017-09-07 17:38
We just published a new release. Could you tell me whether this happens with 1.16?

**Comment by ben-denzer** [comment] 2017-09-07 20:36
![vscode](https://user-images.githubusercontent.com/14027108/30184024-5041a494-93d1-11e7-904b-b1b5b45e2ea2.png)

I'm not the OP, and I have a pretty decent setup (I7 processor with 32g RAM), but I'm not seeing anything with 1.16.0 - didn't notice anything wrong with the older version either.

**Comment by Mehuge** [comment] 2017-09-08 08:49
Same issue with 1.16.0

![image](https://user-images.githubusercontent.com/99895/30203725-ed72ab4c-947a-11e7-8983-61461f257341.png)

It's been running a few minutes and has not yet shown the welcome screen.

**Comment by roblourens** [comment] 2017-09-08 15:47
Where are you launching it from? So it has never launched successfully?

Can you delete the `C:\Users\user\AppData\Roaming\Code` folder and try again?

**Comment by Mehuge** [comment] 2017-09-08 16:00
I am launching it from the desktop icon.

I removed the `Roaming\Code` folder, and relaunched and its still hogging CPU.

**Comment by roblourens** [comment] 2017-09-08 16:06
What happens if you start it from the command line with `--prof-startup`? It should create a couple cpuprofile files in your user directory.

**Comment by roblourens** [comment] 2017-09-08 16:06
And can you just try reinstalling?

**Comment by Mehuge** [comment] 2017-09-08 16:22
Starting with --prof-startup does create a 4d2b_main.cpuprofile.txt
Same issue after uninstalling, deleting Roaming\Code and reinstalling.

**Comment by roblourens** [comment] 2017-09-08 16:52
Can you upload it? Might shed some light on what it's doing instead of starting up.

**Comment by Mehuge** [comment] 2017-09-08 16:57
[4d2b_main.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1288590/4d2b_main.cpuprofile.zip)

Sorry, couldn't see the upload option before.  Must not have been looking very hard, cause it's quite obvious!

**Comment by roblourens** [comment] 2017-09-08 17:22
Looks like it spends 24s on `Menu` after `createBrowserWindow`, don't know what that means... then at the very end, it's doing something else, then a couple seconds doing nothing... @jrieken, @Tyriar?

**Comment by roblourens** [comment] 2017-09-08 17:23
Any way you can try adding more RAM to the VM?

**Comment by Mehuge** [comment] 2017-09-08 17:50
I will have to ask the admin, but yes I can almost certainly bump it up.  Will be Monday now though (UK time here).

**Comment by Tyriar** [comment] 2017-09-08 18:32
+@bpasero

**Comment by bpasero** [comment] 2017-09-09 05:56
@Mehuge single-CPU VM?

**Comment by Mehuge** [comment] 2017-09-09 07:32
![image](https://user-images.githubusercontent.com/99895/30238142-28baa6b4-9539-11e7-8888-b097d51fb196.png)
![image](https://user-images.githubusercontent.com/99895/30238155-54c9b8d0-9539-11e7-9c1c-994e25e8acc0.png)

**Comment by bpasero** [comment] 2017-09-09 07:36
I am not finding the duplicate right now, but running VSCode on a single-CPU VM leads to this.

**Comment by jrieken** [comment] 2017-09-11 07:03
this one: https://github.com/Microsoft/vscode/issues/17097. We rely heavily on multiple processes which doesn't work well on single core machines.

**Comment by Mehuge** [comment] 2017-09-11 09:05
FYI re #issuecomment-328164482 upped memory to 4GB made no difference.

**Comment by jrieken** [comment] 2017-09-11 12:57
how about upping cpu count?

**Comment by Mehuge** [comment] 2017-09-11 14:08
I think we know the issue is single CPU on a VM, I don't plan on making any further changes to the VM.

**Comment by jrieken** [comment] 2017-09-11 15:17
ok. closing as dupe of #17097

**Closed by jrieken** 2017-09-11 15:17 UTC
Labels: duplicate, freeze-slow-crash, needs more info
