### ISSUE TITLE
Terminal: prompt jumps up when splitting terminal (to the bottom)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81749] opened 2019-10-01 13:14 UTC
Seems to only happen when the panel is on the right (this is on macOS).

![before](https://user-images.githubusercontent.com/900690/65965023-37753e00-e45e-11e9-92a0-daa9fa4ea50d.gif)

**Comment by Tyriar** [comment] 2019-10-25 18:16
This happens because terminals at bottom aligned with the panel, so splitting them can change the top padding. The bottom alignment is there so that resizing the panel/window doesn't change the position of the grid. Closing off as designed for now as I don't think it's worth supporting top alignment just for this.

**Closed by Tyriar** 2019-10-25 18:16 UTC
Labels: bug, integrated-terminal, polish
