### ISSUE TITLE
Suggestions for improving the "Find All References" window

### ISSUE THREAD

**Issue by EliasCK** [Microsoft/vscode#31720] opened 2017-07-30 05:41 UTC
In its current state, it is really tedious to browse all references via this window. 

![rr](https://user-images.githubusercontent.com/11874914/28750773-d4d38782-74f4-11e7-98a0-a6d4b041e59c.png)

I need to expand each file in order to view the source, even if the file only contains one reference. Imagine putting each file on your desktop in its own folder. That's what this feels like^^

Here are some suggestions for customizations I would like:

Make an option to completely disable grouping references a collapsed folder. So instead of having the list look like this:
```
File1.cs                               (1)
   some reference
File2.cs                               (1)
   another reference
   third reference
```
I would prefer it if it looked like this:
```
some reference                  File1.cs (19)
another reference               File2.cs (13)
third reference                 File2.cs (47)
```
Then I would be able to just browse using only the arrow up and down keys, without thinking about what files to expand first.

I also wish there was a non-inline mode for it. 

There are many cases where I'm not interested in seeing or browsing the code of all the references. I just want to know, does x file have references to it or not.  And the window shows up, in line. pushing the code down I'm looking at, and showing new code which I'm not interested in seeing is super annoying.

A mode where it would casually show up to the right as a list would be great. And instead of drawing the preview in line, it would open a new tab as soon as I've clicked the arrow down/up key, and use that tab as the preview window as I browse the list. Hitting escape would then close it, and take me back to where I came from. And hitting return open the tab for real.

The list showing up to the right would also improve the overview a great deal as you would be able to view take up all the space vertically and view more of the list at once.

**Comment by DouglasLivingstone** [comment] 2017-11-24 17:44
> I also wish there was a non-inline mode for it.

In Visual Studio I'm in the habit of using the find all references window in the same way as the text search results window, treating a find all references search as just a smarter version of the find in all files command. I'd quite like the find all references command to show its results in the same place and in a similar format to the Search panel (via Ctrl+Shift+F).

**Comment by nikopavlica** [comment] 2018-01-12 08:32
When thinking about this feature, don't forget about moving the search results into its own tab:  https://github.com/Microsoft/vscode/issues/23931

IMO, both features are must-have and should coexist :)

**Comment by pdf** [comment] 2018-01-20 23:02
Duplicate of #22261

**Closed** 2018-01-22 09:02 UTC
Labels: *duplicate, editor, ux
