### ISSUE TITLE
[0.10.7] Should a developer's name show up in source for insiders build?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2688] opened 2016-02-04 02:43 UTC
I know we're not talking release quality code, that this is still beta...but I do wonder if `Insiders.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/bin/omnisharp' with process id 47120...` should be there. The error is that Omnisharp is not starting "[ERROR:OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion." 
But the main question is if code should include developers' names or be more generically named.

**Comment by jrieken** [comment] 2016-02-04 08:27
Yeah, that's the publisher name the extension. We will make it proper soon.

**Comment by jrieken** [comment] 2016-02-04 09:04
closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/7

**Closed by jrieken** 2016-02-04 09:04 UTC
