### ISSUE TITLE
when shortcut alt + f is pressed, tags like <u aria-hidden = "true">N</u>ew File are visible in place of New File

### ISSUE THREAD

**Issue by dreamco43** [Microsoft/vscode#58264] opened 2018-09-08 18:35 UTC
Issue Type: <b>Bug</b>

any of these:
alt + f
alt + e
alt + s
alt + v
alt + g

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.28GB free)|
|Process Argv|C:\Users\sanket\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0

</details>

**Comment by mjbvz** [comment] 2018-09-08 20:07
Duplicate of #58156

**Closed by mjbvz** 2018-09-08 20:07 UTC
Labels: insiders
