### ISSUE TITLE
Sometimes Webview iFrame never load

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#70809] opened 2019-03-20 08:16 UTC
- VSCode Version: 1.32.3
- OS Version: Microsoft Windows [Version 10.0.17763.379]

Does this issue occur when all extensions are disabled?: N/A

Unfortunately, I cannot provid steps to reproduce this issue, it is very unstable.

First of the first, I think this may be Chromium's issue, but I'm not sure.

As we know, iframe won't be rendered until it is appended:

```javascript
const frame = document.createElement('iframe');
console.log(frame.contentWindow);
document.body.appendChild(frame);
console.log(frame.contentWindow);
```

The first console log is `null`, and the 2nd is a `Window` object.

VS Code does the same thing, create an iframe for webview, then append it to body:

https://github.com/Microsoft/vscode/blob/4828d90120276b81cd9d8dc252292ced48ec430a/src/vs/workbench/contrib/webview/electron-browser/webview-pre.js#L290

Thus, the `newFrame` should have both `contentDocument` and `contentWindow`, and all of us should be happy.

However, this issue on my side makes me very confused:

![Snipaste_2019-03-20_16-05-07](https://user-images.githubusercontent.com/1621293/54668480-f654b680-4b29-11e9-9280-33d040cb5757.png)

The webveiw is just all blank, and an error says cannot read property 'focus' of null. The error occued at https://github.com/Microsoft/vscode/blob/4828d90120276b81cd9d8dc252292ced48ec430a/src/vs/workbench/contrib/webview/electron-browser/webview-pre.js#L186

I also try to inspect the element inside webview, and what I see is just empty in the iframe, no `#document`

![Snipaste_2019-03-20_16-08-05](https://user-images.githubusercontent.com/1621293/54668714-82ff7480-4b2a-11e9-8f46-84387e2ac07b.png)

This issue is very boring because I cannot reproduce it on my local machine everytime. Instead, I can reproduce it very frequently on Azure VM.

Here's the information of the testing VM on Azure, and I hope it helps.

* Location: East US
* Size: Standard D2 v3 (2 vcpus, 8 GB memory)
* Operating system: Windows 10 Pro, Version 1809

**Comment by mjbvz** [comment] 2019-03-21 00:45
Duplicate of #70790 I believe. Will track this issue there

**Closed by mjbvz** 2019-03-21 00:45 UTC
