### ISSUE TITLE
Error while Syncing on fresh install

### ISSUE THREAD

**Issue by Faizan-Pasha** [microsoft/vscode#186800] opened 2023-06-30 22:18 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: MacOS 13.4.1 (22F82)

Steps to Reproduce:

1. Log into the vs code
2. Click on the profile icon > Turn on Settings Sync...

Error:

![Screenshot 2023-07-01 at 3 43 19 AM](https://github.com/microsoft/vscode/assets/32414659/7c783993-de95-43c6-b11a-da4bd94df225)

**Comment by joyceerhl** [comment] 2023-06-30 22:26
I just reproduced this myself on insiders.vscode.dev as well as VS Code desktop

**Comment by joyceerhl** [comment] 2023-06-30 22:28
Duplicate of https://github.com/microsoft/vscode/issues/186793

**Closed by joyceerhl** 2023-06-30 22:28 UTC
