### ISSUE TITLE
Problems toggle visibility of warnings/errors.

### ISSUE THREAD

**Issue by tksuoran** [Microsoft/vscode#50449] opened 2018-05-25 09:50 UTC
I would like to be able to show/hide warnings so that I would only see errors. Currently if there are plenty of warnings and errors, it is difficult to find few important errors in large amount of less important warnings. It should be possible to toggle visibility of errors and warnings in problems.

**Comment by sandy081** [comment] 2018-05-25 12:48
Duplicate of #41114

**Closed** 2018-05-25 12:48 UTC
Labels: *duplicate, error-list
