### ISSUE TITLE
[regression] Code completion of string in JSON file produces extra quote

### ISSUE THREAD

**Issue by HighCommander4** [microsoft/vscode#231765] opened 2024-10-20 00:24 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Debian 11

**Steps to Reproduce**

1. Create a file named `test.json` with the following content (`^` indicates the cursor location):
    ```json
    {
      "values": [
        {
          "key": "value"
        },
        {
          ^
        }
      ]
    }
    ```
2. At the indicated cursor location (`^`), type a double quote (`"`). Note that this causes vscode to auto-insert a second quote after the cursor. (This, in and of itself, is fine.)
3. Trigger code completion (if it's not triggerred automatically). Select `key` which is offered as a result.

**Actual results**

The resulting file content is:

```json
{
  "values": [
    {
      "key": "value"
    },
    {
      "key""
    }
  ]
}
```

Not the extra quote after `"key"`.

**Expected results**

The resulting file content is:

```json
{
  "values": [
    {
      "key": "value"
    },
    {
      "key"
    }
  ]
}
```

This is a regression in vscode 1.94 compared to 1.93.

**Comment by RedCMD** [comment] 2024-10-20 00:42
related https://github.com/microsoft/vscode/issues/231224

**Comment by aeschli** [comment] 2024-10-22 09:39
I'm not able to reproduce. I suspect this is caused by https://github.com/microsoft/vscode/issues/231224

Closing as dup of https://github.com/microsoft/vscode/issues/231224

**Closed by aeschli** 2024-10-22 09:39 UTC

**Comment by RedCMD** [comment] 2024-10-22 10:11
@aeschli the bug only appears after restarting vscode with the file open
