### ISSUE TITLE
Markdown outline is not ordered correctly with 10+ headings

### ISSUE THREAD

**Issue by Studio384** [Microsoft/vscode#65734] opened 2018-12-27 14:46 UTC
When writing a markdown file and reaching 11 headings (no matter of which size they are), Visual Studio will start throwing them around in the Outline panel without any sense of order.

- VSCode Version: 1.30.1 and 1.31 (21/12/2018)
- OS Version: Windows 10 version 1809

Steps to Reproduce:

1. Create a markdown file
2. Open the Outline panel
3. Add at least 11 headings

![capture](https://user-images.githubusercontent.com/1693592/50483996-86cda000-09ee-11e9-8a8a-2199234b0987.PNG)

Removing any random heading will result in Outline showing the correct order.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-12-28 00:44
Duplicate of #63040

Also see #63611 on how to change to sort the items in the outline by position

**Closed by mjbvz** 2018-12-28 00:44 UTC
Labels: markdown

**Comment by nik-shornikov** [comment] 2018-12-31 02:12
Honestly.. this is a small-impact BUG. The cat-and-mouse here is approaching the levels that make me want to say, no, Microsoft is not operating in a new way. Just marketing.
How could this behavior be something someone would want? If it could’nt, please explain where the garbage behavior is from, and leave open until fixed.

**Comment by fbehrens** [comment] 2019-01-29 21:10
Hi @mjbvz , i have stumbled also into this, worked out a repro, tested with latest insiders, and figured out the limitation, and that changing the `Sort Order` seem to fix the issue.

My feedback is, that the normal user will stumble into this, when he starts to have a complex md with more than 10 same level heading in markdown. Then its hard to find out where and how things went wrong... which is annoying

Would it be possible to change the default sort order for this?

also: All linked issues have the label `*dublicate`. is there an original issue for this ?

Thanks for contributing to my favorite editor.

**Comment by Studio384** [comment] 2019-01-30 08:05
#50834 is the "original" issue, but that does not seem right. #50834 is a request to change the sorting in files, this is a request to disable it altogether because it is unwanted behavior in a Markdown file.
