### ISSUE TITLE
source control collapses repos and wont show changes

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#110575] opened 2020-11-13 13:56 UTC
Issue Type: <b>Bug</b>

it seems a recent upgrade made the source control collapse repos and won't show changes

I change files, they auto save, and I don't see that there are new changes to commit.

there is a tiny tiny indicator in the branch name, but not as useful as having th modified files visible

VS Code version: Code - Insiders 1.52.0-insider (ee46c1f89ebb213e0827886f1688c0fbb55be49f, 2020-11-13T06:04:37.031Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|-psn_0_1003765|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
markdown-toc|Ala|1.5.6
inline-hasher|ale|1.0.0
spellright|ban|3.0.52
git-temporal-vscode|bee|1.0.0
better-toml|bun|0.3.2
hadolint|exi|0.3.0
terraform|has|2.3.0
gitlab-ci-templates|jgs|0.3.0
markdown-shortcuts|mdi|0.12.0
vscode-docker|ms-|1.7.0
vscode-yaml-sort|Pas|2.7.2
errorlens|Phi|1.1.3
git-file-history|pom|1.0.1
vscode-yaml|red|0.12.0
vscode-gitweblinks|red|1.8.1
vscode-nginx|sha|0.6.0
shellcheck|tim|0.12.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.0.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-11-13 17:06
Does this also happen with all your extensions disabled? In fact, since you're running Insiders you may like to try the new extension bisect feature implemented recently by @jrieken 

Search Command Palette for the word "bisect"

**Comment by KlausC** [comment] 2020-12-09 09:24
I have the same issue with vscode 1.51.1 on Fedora33

**Comment by eamodio** [comment] 2021-01-13 06:05
Duplicate of #112537

**Closed by eamodio** 2021-01-13 06:05 UTC
Labels: *duplicate
