### ISSUE TITLE
missing 1.21 package as RPM

### ISSUE THREAD

**Issue by raytracer-dreamwalker** [Microsoft/vscode#45781] opened 2018-03-14 16:43 UTC
Steps to Reproduce:
Go to: https://packages.microsoft.com/yumrepos/vscode/
Latest release is "code-1.20.1-1518536126.el7.x86_64.rpm"

**Comment by joshsleeper** [comment] 2018-03-14 17:44
duplicate of https://github.com/Microsoft/vscode/issues/45500

just hard to find that one with github search because neither "yum" nor "rpm" find it.

**Closed** 2018-03-14 20:26 UTC
Labels: install-update

**Comment by Tyriar** [comment] 2018-03-15 14:37
https://github.com/Microsoft/vscode/issues/45868
