### ISSUE TITLE
Multicursor cut/paste does not paste

### ISSUE THREAD

**Issue by ds0nt** [Microsoft/vscode#18223] opened 2017-01-06 15:13 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.38-1-MANJARO
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|

---

Steps to Reproduce:

1. select a few lines (press alt and use the mouse, or use alt+shift+up/down, or multiselect using search)
2. press ctrl + x to cut the lines
3. press ctrl + v to paste the lines
4. the lines don't paste
5. go to a new line and paste
6. the lines still don't paste

**Comment by alexandrudima** [comment] 2017-01-09 10:53
@ds0nt this works for me, I just tried in Ubuntu.

Does this reproduce only when having multiple cursors or with any selection?

**Comment by ravid7000** [comment] 2017-01-17 08:22
One more issue something like this:

![vs-code-bug](https://cloud.githubusercontent.com/assets/16535293/22012819/fa7db18c-dcbb-11e6-89be-5a313647af62.gif)

- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: macOS Sierra 10.12.2 (16C67)

Steps to Reproduce:

1. Copy any text.
2. Multiselect same word with ctrl/cmd+d
3. Paste text and see the result.

**Comment by alexandrudima** [comment] 2017-01-21 13:38
@ravid7000 Thank you. Extracted your issue to #18976. Closing this one until OP provides more information.

**Closed by alexandrudima** 2017-01-21 13:38 UTC
Labels: needs more info

**Comment by ds0nt** [comment] 2017-01-23 00:46
Don't select the text. Simply put a cursor on each line and press ctrl+x.

Actually I've noticed now that it doesn't work with single lines either.

In Atom, if I ctrl+x a line, then it cuts the line. And I can paste it
elsewhere. Seems in vscode it just erased the line...

At any time in vscode, pressing ctrl x with nothing selected cuts a whole
line. You can then paste it elsewhere. This does not work with multiple
cursors, or single cursors.

**Comment by alexandrudima** [comment] 2017-01-23 08:34
@ds0nt This works for me quite well. Perhaps you have disabled it via `"editor.emptySelectionClipboard"` (that should be true for ctrl+c/ctrl+x to copy/paste whole lines when the selection is empty ?
