### ISSUE TITLE
JavaScript class private fields with '#'

### ISSUE THREAD

**Issue by M-Nayeem** [Microsoft/vscode#72867] opened 2019-04-25 14:35 UTC
See #56566.

The proposal is now stage 3 (like many features that _have_ already been implemented in VS Code) and is even implemented in Google Chrome 74 - stable as of earlier this week. I think it should be revisited and this should probably be kept open until it is implemented or actually cancelled.

**Comment by M-Nayeem** [comment] 2019-04-25 14:39
Although, I guess it's the case that this feature is harder to implement than those other features and should be held off for longer. Nevertheless.

**Comment by mjbvz** [comment] 2019-04-25 18:10
Duplicate of https://github.com/Microsoft/TypeScript/issues/9950

**Closed by mjbvz** 2019-04-25 18:10 UTC

**Comment by M-Nayeem** [comment] 2019-04-25 18:21
Just to be clear, I'm talking about syntax highlighting for JavaScript. Does that feed from TypeScript's language specification somehow?

**Comment by mjbvz** [comment] 2019-04-25 18:24
Yes, TypeScript powers our JavaScript intellisense
