### ISSUE TITLE
[object Object] extension title

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#162091] opened 2022-09-27 23:54 UTC
I clicked "Check for Extension Updates" to get the latest "Remote SSH: Editing Configuration Files" extension release

Saw this
<img width="436" alt="image" src="https://user-images.githubusercontent.com/323878/192657151-dd5ccfa1-e327-48f2-bd12-a2048fc39d1c.png">

Clicked to reload, searched and saw this
<img width="457" alt="image" src="https://user-images.githubusercontent.com/323878/192657202-c352f18b-7a74-46ba-962a-6bfa38e06acf.png">

But when I clear the search, the title is correct
<img width="433" alt="image" src="https://user-images.githubusercontent.com/323878/192657377-c1a2c584-2d51-4dde-a1a0-632f55c43983.png">

**Comment by roblourens** [comment] 2022-09-28 05:17
And marketplace https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit

The extension name is localized, I will publish a version without a localized name first thing tomorrow.

The entry in package.nls.json looks like this

```
    "displayName": {
        "message": "Remote - SSH: Editing Configuration Files",
        "comment": [
            "{Locked='Remote - SSH:'}",
            "Do not translate 'Remote - SSH:'. It is a specific name."
        ]
    },
```

I guess we don't know how to handle that for the extension name? cc @TylerLeonhardt I didn't set this up, I'm not sure if it's done wrong in remote-ssh or if there's an issue in the extension publish process?

**Comment by sandy081** [comment] 2022-09-28 07:05
Marketplace does not support localisation of display name yet.

**Comment by gjsjohnmurray** [comment] 2022-09-28 09:45
This is also affecting Stable:

![image](https://user-images.githubusercontent.com/6726799/192747157-0daa124a-5428-42f3-ae76-23a94363ef31.png)

**Comment by TylerLeonhardt** [comment] 2022-09-28 14:22
This is a dupe of https://github.com/microsoft/vscode/issues/161798#issuecomment-1259139763

And I still need to make an issue in VSMarketplace... once I do that, I'll close this since it's out of our control.

**Comment by gjsjohnmurray** [comment] 2022-09-28 14:44
Meanwhile, upstream issue for this particular extension is https://github.com/microsoft/vscode-remote-release/issues/7262

I guess they need to back out their l10n changes until VSMarketplace can handle them.

**Closed** 2022-09-28 16:18 UTC
