### ISSUE TITLE
Collapsing XML isn't working correctly

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#5575] opened 2016-04-20 21:09 UTC
- VSCode Version: 1.0.1-insiders
- OS Version: Windows 10 RTM

Steps to Reproduce:

1. Open `Microsoft.PowerShell.Commands.Management.dll-Help.xml` 
2. Collapse the first `<command:syntax>` XML element you come across
3. Notice that the collapsing is prematurely canceled

![image](https://cloud.githubusercontent.com/assets/466713/14690564/e374e2ae-0709-11e6-99f7-fa936e227315.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by Tyriar** [comment] 2016-04-21 00:56
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/3422, @pcgeek86 can you verify with the XML you're using?

**Comment by pcgeek86** [comment] 2016-04-21 02:27
@Tyriar sure, it's the `c:\windows\system32\windowspowershell\v1.0\en-US\Microsoft.PowerShell.Commands.Management.dll-help.xml` file.

**Closed** 2016-04-21 05:01 UTC
Labels: needs more info
