### ISSUE TITLE
Support settings.json5

### ISSUE THREAD

**Issue by BlackHole1** [microsoft/vscode#168400] opened 2022-12-08 06:13 UTC
JSON format itself does not support comments. However, in VSCode's settings.json file, VSCode has implemented a special way to support comments, which is not the standard way described by the JSON specification. It can be seen as a hack. This way cannot be used in other JSON files and is not recommended.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/8198408/206371117-8dc3e036-b046-40b9-b4e9-73a785ab6567.png">

JSON5 (a superset of JSON) currently supports annotations and has other features such as single quotes.

**In general, we consider JSON files to be more suitable for carrying data. And JSON5 is more suitable for project/program configuration**

Ref: https://json5.org/

**Comment by aeschli** [comment] 2022-12-09 10:08
Duplicate of https://github.com/microsoft/vscode/issues/100688

We still have no plans to change the format of the settings files. There is no real problem in using our 'own' JSON-like file format, for which we also offer the editors and a node module for programmatic consumption.
Also we trend towards the setting UI as the default way of changing settings,

**Closed by aeschli** 2022-12-09 10:08 UTC
