### ISSUE TITLE
Integrated terminal scrolling not working in oh-my-zsh

### ISSUE THREAD

**Issue by richarddavenport** [Microsoft/vscode#7817] opened 2016-06-17 14:28 UTC
- VSCode Version: 1.3.0-insider 93e65224d7598017bfa0b188a0d82b66a2ee9698
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Make more content in the integrated terminal than can fit in the panel.
2. Try scrolling to the top of the content. Doesn't work for me...

**Comment by Tyriar** [comment] 2016-06-21 17:57
Are you scrolling using mouse/trackpad? Can you try <kbd>ctrl</kbd>+<kbd>shift</kbd>+arrow/page up/page down (or whatever the OS X equivalent is).

**Comment by wallverb** [comment] 2016-06-22 04:19
1. shift+fn+up/down arrow allows to scroll on my OSX 10.11.5 (insider build)
2. Scrolling with trackpad does not scroll
3. Trying to highlight more text from terminal that is visible does not trigger scroll (although this also does not work in 1.2.1)

**Comment by richarddavenport** [comment] 2016-06-22 20:10
@wallverb is right. Their points are all correct.

**Comment by masonicboom** [comment] 2016-06-23 22:07
I have experienced this. However, I am able to scroll with the trackpad if I place the cursor over the left side of the terminal (where my content is). If I move the cursor too far to the right, I cannot scroll.

Maybe the scrollable element is assuming the minimum width necessary to contain the terminal text, rather than occupying the full width of the terminal.

**Comment by Tyriar** [comment] 2016-06-24 02:58
@masonicboom that is expected on stable, on the insiders build scrolling *should* be working as expected.

**Comment by Tyriar** [comment] 2016-06-25 00:25
I can't reproduce on Insiders, two finger trackpad scroll seems to work just fine? OS X Yosemite 10.10.5 on a 2014 MacBook Pro.

**Comment by wallverb** [comment] 2016-06-26 14:44
@Tyriar let me know if I can help somehow to troubleshoot this issue, still not working for me Version 1.3.0-insider (1.3.0-insider) de66522e06d74752d48d92e934dcd026050355ba OS X 10.11.15 - 2012 Macbook Pro

**Comment by Tyriar** [comment] 2016-06-27 08:41
@wallverb would you be able to pull down https://github.com/sourcelair/xterm.js and check if you can reproduce on the [demo](https://github.com/sourcelair/xterm.js#demo)?

**Comment by wallverb** [comment] 2016-06-27 14:41
@Tyriar pulled down and started demo - scrolling works fine, let me know what to do next :)

**Comment by wallverb** [comment] 2016-06-27 14:48
Found the difference, in `xterm.js` around lines `1132-1136` in this piece of code:
```
// allow mousewheel scrolling in
      // the shell for example
      on(el, wheelEvent, function(ev) {
        if (self.mouseEvents) return;
        if (self.applicationKeypad) return;
        if (ev.type === 'DOMMouseScroll') {
          self.scrollDisp(ev.detail < 0 ? -1 : 1);
        } else {
          self.scrollDisp(ev.wheelDeltaY > 0 ? -1 : 1);
        }
        return self.cancel(ev);
      });
```

In vscode `self.applicationKeypad` is `true` that's why it's returning while xterm.js demo has this value set to `false`

**Comment by wallverb** [comment] 2016-06-27 14:54
The reason while it's set to true is due to this flow:

`internal/child_process.js` line `444`:
`handleMessage(target, message, undefined);` where `message={type: 'data', content: "[K[?1h="}'

which then calls:
`terminalInstance.ts` line `47`
`this.xterm.write(message.content);`

which then does:
`xterm.js` line `1722`

```
 // ESC = Application Keypad (DECPAM).
              case '=':
                this.log('Serial port requested application keypad.');
                this.applicationKeypad = true;
                this.state = normal;
                break;
```

I hope it helps

**Comment by Tyriar** [comment] 2016-06-27 17:20
Interesting... Can you check what `message.content` is in this case? Whatever it is, it seems to be telling xterm to enter the application keypad mode.

**Comment by wallverb** [comment] 2016-06-28 13:47
Message content is:
`[0m[27m[24m[J[01;32m➜  [36msolution[00m [K`
and
`[?1h=`

which renders it as:
![image](https://cloud.githubusercontent.com/assets/1723815/16417778/325f255a-3d15-11e6-8865-ca43555b8804.png)

**Comment by wallverb** [comment] 2016-06-28 14:38
Submitted bug at xterm.js repo: https://github.com/sourcelair/xterm.js/issues/151

**Comment by Tyriar** [comment] 2016-06-28 20:39
Thanks for investigating this @wallverb! :+1:

**Comment by niwsa** [comment] 2016-07-04 11:03
I am facing scrolling issues in ubuntu 14.04,VSCode version 1.2.1.On scrolling up the text in the console goes far left sometimes and invisible at other times.

**Comment by Tyriar** [comment] 2016-07-04 11:30
@niwsa those should be fixed in the upcoming v1.3.0, This issue is about scrolling not working at all using the trackpad.

**Comment by arastu** [comment] 2016-07-11 02:45
also not work in ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

and vscode:
```
Visual Studio Code v1.3.0
```

**Comment by Tyriar** [comment] 2016-07-11 05:19
@arastu there is a bug in 1.3.0 that if you resize the terminal window you can no longer scroll in that area, unfortunately it snuck into the library we use just before the release. Does it work all the time if you scroll with the cursor on the left side of the terminal?

**Comment by richarddavenport** [comment] 2016-07-11 16:25
@wallverb I think this is specific to oh my zsh, or at least a zsh that is printing an `=` character. In my oh my zsh theme I also have an `=` character, but without oh my zsh I do not and scrolling is working. Is there anyway to filter out that character and still have it work?

**Comment by Tyriar** [comment] 2016-07-11 16:51
@richarddavenport just tried on my macbook and zsh works fine, I'll update the title accordingly. Since this is an upstream issue, let's centralize discussions in https://github.com/sourcelair/xterm.js/issues/151

**Comment by richarddavenport** [comment] 2016-07-15 15:38
@Tyriar @wallverb I opened [an issue](https://github.com/robbyrussell/oh-my-zsh/issues/5228) with oh my zsh and found there is [a fix](https://github.com/robbyrussell/oh-my-zsh/pull/5113) for this issue. I'm running with [this branch](https://github.com/apjanke/oh-my-zsh/tree/ditch-smkx) right now, and scrolling is working!

**Comment by ext0** [comment] 2016-07-28 19:26
The fix I had was setting the "width" CSS styling property of the "monoco-scrollable-element" to 100%. This immediately completely fixed the issue.

**Comment by Tyriar** [comment] 2016-07-28 20:28
@ext0 FYI that element was removed either in 1.3.0 or in the upcoming 1.4.0.

**Comment by ext0** [comment] 2016-07-28 20:30
@Tyriar Ah gotchya, I haven't updated yet. Good to know!

**Comment by technbuzz** [comment] 2016-08-14 17:37
I am also facing same issue on Windows 10 with VS Code V1.4.0. Ctrl+shift+up/down also not working.

**Comment by Tyriar** [comment] 2016-08-15 16:54
@technbuzz this is to do with oh-my-zsh, ctrl+up/down should scroll the terminal on Windows in the latest [Insiders build](https://code.visualstudio.com/insiders).

**Comment by drptbl** [comment] 2016-08-30 15:34
Same issue on MAC. Please fix, it's really annoying :(.

**Comment by richarddavenport** [comment] 2016-08-31 22:06
@drptbl The issue is open for OS X, as stated in the opening comment. It's also an upstream issue, meaning that there are other projects that need to be fixed before this one can be fixed. [Here's a workaround.](https://github.com/Microsoft/vscode/issues/7817#issuecomment-232987226)

**Comment by yeluoqiuzhi** [comment] 2016-09-12 02:52
It's really annoying!!!

**Comment by Tyriar** [comment] 2016-09-26 03:50
This should be fixed in the next insiders build.

**Closed by Tyriar** 2016-09-26 03:50 UTC
Labels: bug, integrated-terminal, upstream

**Comment by StefanoChiodino** [comment] 2017-08-21 17:11
I'm having the same problem with zhs and bash. Most of the time it scrolls, sometimes it doesn't!

VSC 1.15.1

**Comment by Tyriar** [comment] 2017-08-21 18:25
@StefanoChiodino please create a new issue with more details
