### ISSUE TITLE
Some extensions shown on the marketplace are not listed from the IDE

### ISSUE THREAD

**Issue by soullivaneuh** [microsoft/vscode#113362] opened 2020-12-23 23:18 UTC
- VSCode Version: 1.51.1
- OS Version: Manjaro 20

Steps to Reproduce:

1. Open the extensions tab
2. Search the following extension: "CodeStream"

The extension is not shown on the list result, but it seems to exist on your marketplace: https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream

This bug happens on many extension. For example this one: https://marketplace.visualstudio.com/items?itemName=rpinski.shebang-snippets

This also prevents [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) plugin to download the registered extension of my list.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tamuratak** [comment] 2020-12-24 04:16
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by soullivaneuh** [comment] 2021-01-04 09:25
Indeed, but it was close by the author for "Archlinux problem" reason.

I disagree. Apparently the only problem is the update of vscode to `1.49.1-1` by Archlinux, but the bug looks to be introduced on this release according to the records.

**Comment by yume-chan** [comment] 2021-01-04 09:58
> but the bug looks to be introduced on this release according to the records.

That package is NOT built and provided by Microsoft. Some packagers decided to switch to OpenVSX, not Microsoft.

You should reach the maintainer for help. Filing issue (again) here is not helpful.

**Closed** 2021-01-06 12:36 UTC

**Comment by soullivaneuh** [comment] 2021-01-25 11:55
For anyone struggling with this issue for ArchLinux, it can be solved with ease by installing this package hack: https://aur.archlinux.org/packages/code-marketplace/
