### ISSUE TITLE
CustomizedMenuWorkbenchToolBar writing to disposed disposableStore

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#173188] opened 2023-02-02 19:29 UTC
From https://dev.azure.com/vscode/VSCode/_build/results?buildId=84973&view=logs&j=295c9730-2c20-520e-70a6-194d1bff9914&t=24aeac89-8044-5903-4e2c-c1ef0563a20a

```
[4120:0202/080808.180:INFO:CONSOLE(168)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/lifecycle.js:168:34)
    at CustomizedMenuWorkbenchToolBar.setActions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/platform/actions/browser/toolbar.js:95:42)
    at CustomizedMenuWorkbenchToolBar.updateToolbar (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/contrib/inlineCompletions/browser/inlineSuggestionHintsWidget.js:268:18)
    at CustomizedMenuWorkbenchToolBar.setAdditionalSecondaryActions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/contrib/inlineCompletions/browser/inlineSuggestionHintsWidget.js:272:18)
    at InlineSuggestionHintsContentWidget.update (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/contrib/inlineCompletions/browser/inlineSuggestionHintsWidget.js:151:26)
    at InlineSuggestionHintsWidget.update (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/contrib/inlineCompletions/browser/inlineSuggestionHintsWidget.js:58:29)
    at vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/contrib/inlineCompletions/browser/inlineSuggestionHintsWidget.js:87:69
    at Listener.invoke (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:450:27)
    at EventDeliveryQueue.deliver (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:582:38)
    at Emitter.fire (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:544:37)
    at vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/browser/widget/codeEditorWidget.js:1383:48
    at Listener.invoke (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:450:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:582:38)
    at Emitter.fire (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/event.js:544:37)
    at EditorConfiguration._recomputeOptions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/browser/config/editorConfiguration.js:50:31)
    at EditorConfiguration.updateOptions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/browser/config/editorConfiguration.js:95:18)
    at CodeEditorWidget.updateOptions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/editor/browser/widget/codeEditorWidget.js:123:33)
    at NativeTextFileEditor.updateEditorControlOptions (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/browser/parts/editor/textCodeEditor.js:35:33)
    at NativeTextFileEditor.updateEditorConfiguration (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/browser/parts/editor/textEditor.js:178:22)
    at vscode-file://vsco
```

**Comment by hediet** [comment] 2023-02-20 22:51
Duplicate of #173193

**Closed by hediet** 2023-02-20 22:51 UTC
Labels: bug, debt, inline-completions
