### ISSUE TITLE
Code coloring Shell Script Edge Case

### ISSUE THREAD

**Issue by CTaeumel** [microsoft/vscode#173547] opened 2023-02-06 11:28 UTC
Type: <b>Bug</b>

1. Create a new file with the language mode "Shell Script"
2. Insert the following minimal example:
```
#!/bin/bash

############################### normal ###############################
var1="value"
echo "$var1"
echo "${var1}"

echo $variable
echo \
  $variable
echo \
  "$variable"
echo \
  "${variable}"

"echo" d"${variable}"
"echo" \
  "${variable}"
"echo" \
  d${variable}
"echo" \
  d"$variable"
"echo" \
  "d${variable}"

############################### example working ###############################
port="12345"
echo "${var1}"
echo "$var1"

fn1

############################### broken ###############################

"echo" \
  d"${variable}"

############################### example broken ###############################
port="12345"
echo "${var1}"
echo "$var1"

fn1
```
3. Profit (most things starting from line 36 have wrong colors)

Please note that this is a minimal example, I can give you a more realistic example if necessary.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bats|jet|0.1.9
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
remote-explorer|ms-|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983

```

</details>

**Comment by CTaeumel** [comment] 2023-02-06 11:28
![grafik](https://user-images.githubusercontent.com/31305055/216960089-47203d3f-c9bd-4717-919a-6c539f395197.png)

**Comment by CTaeumel** [comment] 2023-02-06 11:32
I think (even though I haven't tried to prove it) that this behaviour got introduced with a recent update, because I've noticed it in a file last changed on 2022-10-25.

**Comment by alexr00** [comment] 2023-02-06 14:56
Duplicate of https://github.com/microsoft/vscode/issues/173336.

Will be fixed in insiders tomorrow and stable with the next recovery release.

**Closed by alexr00** 2023-02-06 14:56 UTC
Labels: new release
