### ISSUE TITLE
Tokenize lines with >=20k chars in one line

### ISSUE THREAD

**Issue by h7ing** [Microsoft/vscode#5303] opened 2016-04-15 06:32 UTC
[testjson.txt](https://github.com/Microsoft/vscode/files/220437/testjson.txt)
- VSCode Version:1.0.0(and earlier versions)
- OS Version:Windows 7 professional SP1 64bit

Steps to Reproduce:
1. open testjson.txt
2. swith language mode to JSON

bug: no language highlight

**Comment by egamma** [comment] 2016-04-15 06:48
How large is the file? Can you reproduce with a smaller file.

**Comment by aeschli** [comment] 2016-04-15 09:07
I think the editor has has file size limit of 50MB. Tokenization is disabled for larger files

**Comment by h7ing** [comment] 2016-04-18 04:04
I think it's too much characters in one line cause the problem. I'll update the issue.
In the new test files:
[testjson_no_bug.txt](https://github.com/Microsoft/vscode/files/223047/testjson_no_bug.txt) has a line of JSON string with 19,999 characters, and JSON hightlight is normal.
[testjson_start_bug.txt](https://github.com/Microsoft/vscode/files/223054/testjson_start_bug.txt) has a line of JSON string with 20,000 characters can produce the bug.

**Comment by alexandrudima** [comment] 2016-07-11 16:26
That is correct.

The colorization is limited to lines with 20k characters. https://github.com/Microsoft/vscode/blob/master/src/vs/editor/node/textMate/TMSyntax.ts#L254

The reason is to introduce an indirect upper bound on the time taken to colorize a line.

I've seen files where grammars were going crazy for 5 minutes tokenizing a single very large line.

**Comment by usernamehw** [comment] 2019-02-18 20:17
/duplicate of #63639

New setting from vscode **1.32.0**
```json
"editor.maxTokenizationLineLength": 40000
```

**Closed** 2019-02-18 20:17 UTC
Labels: *duplicate, feature-request, tokenization
