### ISSUE TITLE
Code blocks are collapsing incorrectly

### ISSUE THREAD

**Issue by coaperator** [Microsoft/vscode#33227] opened 2017-08-28 00:19 UTC
- VSCode Version: latest
- OS Version: Win 10

Wrong:
![1](https://user-images.githubusercontent.com/6645911/29755379-8f9d9a90-8bb0-11e7-9e4b-dc647cb84a73.PNG)

Correctly:
![2](https://user-images.githubusercontent.com/6645911/29755371-58fe561e-8bb0-11e7-982e-8757497cb6c6.PNG)

How to fix?

**Comment by rcjsuen** [comment] 2017-08-28 01:22
The current behaviour is how VS Code works and is not exactly "incorrect".

In any case, this sounds like a duplicate of #3352.

**Comment by coaperator** [comment] 2017-08-28 03:27
@rcjsuen This is a very bad behavior. It is necessary to correct urgently.
In all editors the code is minimized as on the bottom picture.
This is familiar, understandable and convenient.
I can not go to VS Code because of this.

PS: I apologize for the double.

**Comment by Tyriar** [comment] 2017-08-28 14:59
This is as designed. A related discussion is going on here https://github.com/Microsoft/vscode/issues/3353

**Closed by Tyriar** 2017-08-28 14:59 UTC
