### ISSUE TITLE
apple silicon: `os.cpus()` returns `[]` (empty array)

### ISSUE THREAD

**Issue by codekitchen** [microsoft/vscode#112122] opened 2020-12-09 03:28 UTC
- VSCode Version: Visual Studio Code - Exploration
Version: 1.53.0-exploration
Commit: 47a314c25fea67c9b54fcb46aeaa15db31af33f8
Date: 2020-12-08T08:33:00.164Z (18 hrs ago)
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0
- OS Version: Big Sur 11.0.1

Steps to Reproduce:

1. Toggle the Developer Tools
2. Type in console: `require('os').cpus()`

Does this issue occur when all extensions are disabled?: Yes

Sorry if this is the wrong place to report this, as it seems likely this is actually an Electron issue, but I saw in some other issues that you're currently building your own custom Electron builds for Apple Silicon.

I was exploring why the Hashicorp Terraform extension was never finishing its initialization phase, and I tracked it down to the `fast-glob` npm package using `os.cpus().length` to determine how many workers to use. Granted, they should add a sanity check here, but this seems likely to cause other issues too.

**Comment by bpasero** [comment] 2021-04-28 16:02
I cannot reproduce this anymore with Electron 12:

![image](https://user-images.githubusercontent.com/900690/116435625-db49ea00-a84b-11eb-8d09-c973e6b839dd.png)

**Comment by deepak1556** [comment] 2021-04-28 20:29
Yup this is fixed with latest insiders and should be fixed with next stable release `1.56`. Thanks for checking @bpasero

**Closed by deepak1556** 2021-04-28 20:29 UTC
Labels: :apple: si, bug, electron, macos-big-sur
