### ISSUE TITLE
Resize grip on wrong side of application border

### ISSUE THREAD

**Issue by MaartenBent** [microsoft/vscode#102023] opened 2020-07-09 20:50 UTC
- VSCode Version: 1.47.0
- OS Version: Windows 10 x64 10.0.19041

Steps to Reproduce:

Move the mouse over the application border. Half-way over the scrollbar, the mouse changes into resize gripper, making half of the scrollbar useless.
Other applications, like explorer or notepad, do not have this issue. Here the mouse changes into a resize gripper once it leaves the application window.

vscode:
![vscode](https://user-images.githubusercontent.com/8088070/87091261-ae373700-c239-11ea-9de0-022d32a65fda.gif)

notepad:
![notepad](https://user-images.githubusercontent.com/8088070/87091271-b1cabe00-c239-11ea-969a-7d40300edb9f.gif)

1.46 has the same behavior.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment] 2020-07-10 16:22
@deepak1556 is this something we can control in electron?

**Comment by zbjornson** [comment] 2020-08-05 02:13
This might be what causes unexpected scrolling when trying to resize panes. Below, notice the cursor is east-west resize, but clicking causes the scrollbar to jump instead.

![102023](https://user-images.githubusercontent.com/469365/89363852-68318f80-d68e-11ea-84b5-88d99bf28bdf.gif)

(It looks like the cursor changes to a pointer just before clicking, but I haven't moved my mouse.)

Win10 x64 10.0.19041
VSCode 1.47.3 (and many earlier versions)

**Comment by rzhao271** [comment] 2021-01-08 21:15
Workaround: set `window.titleBarStyle` setting to `native`. Just confirmed that when it is set to `custom`, the issue occurs.

**Comment by rzhao271** [comment] 2022-10-07 22:24
Unable to reproduce the issue on Windows 11.
Does the issue still show up on Windows 10 with the latest VS Code?

**Comment by zbjornson** [comment] 2022-10-07 22:35
On Win 11, VS Code 1.71.2, I can't repro the OP, but I can repro what I posted above (cursor doesn't match click action; possibly #27247). I can open a new issue for what I posted if you think they're unrelated.

**Comment by rzhao271** [comment] 2022-10-07 23:37
I'm unable to repro on the latest Insiders with both the native and the custom titlebar. For me, if I move too much to the left, the cursor changes back to "normal" and the scrollbar fades back in. If I keep the cursor in such a place that it has the east-west appearance, clicking doesn't cause scrolling to occur, and the scrollbar remains transparent.

**Comment by dantmnf** [comment] 2022-10-11 14:17
The issue is still here, except that the "inset" region only responds to resize action. The resizing handle is still on the wrong side of the window border, just like in the attached video.



https://user-images.githubusercontent.com/2252500/195116078-a386ab26-ba30-49aa-9ed6-613d87bb42ed.mp4

**Comment by deepak1556** [comment] 2022-12-09 03:08
Upstream issue has been closed as `wontfix` https://github.com/electron/electron/issues/27247, closing as not actionable.

**Closed by deepak1556** 2022-12-09 03:08 UTC
Labels: bug, upstream, windows, electron, layout, confirmed, upstream-issue-linked
