### ISSUE TITLE
Sync throws on tag mismatch

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164824] opened 2022-10-27 17:30 UTC
1. Be on main branch
2. Click on the synchronize changes button in the left of the status bar 
3. :bug: sync changes throws, looks like I pulled a bad tag or something that then got force-pushed?

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/30305945/198358276-2455c53f-9404-4be1-939c-38bfefea64dc.png">

```

> git pull --tags origin main
From https://github.com/microsoft/vscode
 * branch                    main       -> FETCH_HEAD
 ! [rejected]                1.72.2     -> 1.72.2  (would clobber existing tag)
   1316bf789f9..0570a7678db  main       -> origin/main
```

Would be nice if this dialog had an action to resolve whatever the problem was, e.g. delete my local tag and pull. I'm also a little surprised that synchronize changes does anything with tags, I thought it was just for the current branch (which is what I want when I click the sync button).

**Comment by lszomoru** [comment] 2022-10-28 08:48
On the plan for November 2022.

**Comment by lszomoru** [comment] 2022-11-28 08:58
Closing as duplicate of #160822.

**Closed by lszomoru** 2022-11-28 08:58 UTC
Labels: bug, git
