### ISSUE TITLE
Terminal sometimes loses the ability to scroll

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#30840] opened 2017-07-17 08:02 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:  none

---

Steps to Reproduce:

1. Launch code.
2. Run build task.

At the time, there was a compiler error in my project, so the standard npm error stuff got output to the console, but I was unable to scroll up to see what tsc had output. Restarting vscode had no effect.

This is the error I get on the developer console when I click on the terminal window to give it focus:
```
Uncaught TypeError: Cannot read property 'NaN' of undefined
    at SelectionManager._onSingleClick (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:228:71)
    at SelectionManager._onMouseDown (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:192:22)
    at HTMLDivElement.SelectionManager._initListeners._mouseDownListener (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:53:67)
```

Reproduces without extensions: Yes

**Comment by mattacosta** [comment] 2017-07-17 08:10
Additional notes;

Right-clicking on the terminal window also causes:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.translateBufferLineToString (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\utils\BufferLine.js:11:29)
    at SelectionManager._getWordAt (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:328:33)
    at SelectionManager._selectWordAt (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:375:33)
    at SelectionManager._onDoubleClick (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:238:18)
    at SelectionManager._onMouseDown (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:195:22)
    at HTMLDivElement.SelectionManager._initListeners._mouseDownListener (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:53:67)
```

This appears to only happen to the terminal used for task output. Everything works normally when adding a standard terminal window.

**Comment by Tyriar** [comment] 2017-07-17 14:39
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/20505

Could you test this out on [Insiders](https://code.visualstudio.com/insiders)?

**Closed by Tyriar** 2017-07-17 14:39 UTC
Labels: integrated-terminal, new release
