### ISSUE TITLE
VSCode annoyingly autocompletes `"""` in Python to `""""`

### ISSUE THREAD

**Issue by chriskuech** [Microsoft/vscode#12976] opened 2016-09-29 05:59 UTC
- VSCode Version: 1.5.3
- OS Version: macOS 10.11.6

Steps to Reproduce:
1. Type `"""` on a new line
2. Observe that `"""` autocompletes to `""""` with the cursor before between the third and forth `"`.

**Comment by rmunn** [comment] 2016-09-29 08:34
This may need a language-specific solution. If so, then F# should be included in the solution, as it also uses Python-style triple-quoted strings.

**Comment by joshkehn** [comment] 2017-01-18 17:06
I can't reproduce this currently. 

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|django-html|bibhasdn|1.2.0|
|python|donjayamanne|0.5.5|
|gitlens|eamodio|1.4.1|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.9.3|
|preview-vscode|searKing|1.1.1|
|vscode-react-native|vsmobile|0.2.5|

**Comment by rebornix** [comment] 2017-07-14 18:48
This issue is obsolete. Close it first and reopen if anyone can reproduce.

**Closed by rebornix** 2017-07-14 18:48 UTC
Labels: bug, editor-brackets

**Comment by rmunn** [comment] 2017-07-20 15:08
Can still reproduce on latest VS Code with an F# script file, though the Python part of this issue seems to be fixed.

**Comment by rmunn** [comment] 2017-07-20 15:15
Repro steps:

1. Create new `script.fsx` file (with Ionide-fsharp extension installed)
2. Type `"""` (three double-quote characters).
3. Result: *four* double-quote characters, with the cursor between the third and the fourth.

Ionide-fsharp version: 2.27.15, latest released version of the extension as of 2017-07-20.
VS Code version: Insiders build, version 1.15.0-insider (commit cf9726da54472f1e268135a64abd4365b91109f4)

**Comment by rebornix** [comment] 2017-07-20 18:37
@rmunn thanks for your detailed reproduce steps. Already fixed and you can see the update from tomorrow's insider.
