### ISSUE TITLE
Vs code being closed when try to open a folder

### ISSUE THREAD

**Issue by iamridoydey** [microsoft/vscode#232171] opened 2024-10-24 17:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- **VS Code Version:** 1.94.2
- **OS Version:** Ubuntu 24.04

### Steps to Reproduce:

1. Launch Visual Studio Code.
2. Try to open a folder using the "Open Folder" option from the File menu or by dragging a folder into the VS Code window.

### Expected Behavior:

VS Code should open the selected folder without closing the application.

### Actual Behavior:

VS Code closes unexpectedly when attempting to open a folder.

### Additional Information:

- I have tried launching VS Code with the `--disable-extensions` flag, and the issue persists.
- There are no specific error messages displayed before the application closes.
- This issue began occurring after updating to version 1.94.2.

### Video Reference 
https://github.com/user-attachments/assets/23adc251-2f7a-411b-80dd-da6c81bc72d8

**Comment by gjsjohnmurray** [comment] 2024-10-24 20:59
Probably a duplicate of https://github.com/microsoft/vscode/issues/230454

**Comment by iamridoydey** [comment] 2024-10-25 01:45
@gjsjohnmurray i didn’t duplicate it. I was facing problem but i thought it will be okay after update. But it was not the case

**Comment by deepak1556** [comment] 2024-10-25 10:29
Are you using the snap package or deb package ? Please check if the issue persists with latest insiders https://code.visualstudio.com/insiders

**Comment by mpietras** [comment] 2024-10-25 12:18
This started happening to me this morning as well... 1.94.2. I disabled all extensions and clicking "Open Folder..." still immediately crashes VSCode.  Tried closing out the current folder and relaunching - now I cannot open one.  Launching from console seems to allow a folder to be opened that way, even with extensions enabled.

**Comment by gjsjohnmurray** [comment] 2024-10-25 12:47
Did you try the workaround from https://github.com/microsoft/vscode/issues/230454#issuecomment-2396957450?

**Comment by iamridoydey** [comment] 2024-10-26 05:34
I will take a look at this. Thanks @gjsjohnmurray

**Comment by iamridoydey** [comment] 2024-10-29 12:39
After reinstalling vs code in my system now it is working just fine.

**Comment by deepak1556** [comment] 2024-10-29 14:34
Closing per above comment, can reopen if the issue reappears with `1.95`

**Closed by deepak1556** 2024-10-29 14:34 UTC
Labels: freeze-slow-crash-leak, linux
