### ISSUE TITLE
explorer tree file selection when vscode window is not active

### ISSUE THREAD

**Issue by jk000** [microsoft/vscode#138062] opened 2021-11-29 14:59 UTC
Issue Type: <b>Bug</b>

When VSCode has a directory open in the explorer tree view, hovering over the listed files with the mouse changes the mouse to the pointer finger, and single-clicking any file will open the file in the editor.  This is normal.

However, if the VSCode window is not selected (e.g. click on the taskbar in Windows first), hovering over files in the explorer tree still gives the mouse pointer finger, but clicking on a file has no effect!

This is inconsistent with every other part of VSCode, for example clicking somewhere in the editor when the VSCode window is not selected will move the cursor to location clicked, with a single click.

This has been tested without extensions using "code --disable-extensions -n"

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (23.83GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/jkubeck/repos/optimizer --crash-reporter-id 86aef7c8-34b7-4f4b-b7eb-c668f469c4e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
blamer-vs|bea|0.5.2
insert-unicode|bru|0.13.1
cmake-format|che|0.6.11
overtype|DrM|0.4.0
todo-tree|Gru|0.0.214
svn-scm|joh|2.15.0
rainbow-csv|mec|1.10.1
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
gremlins|nho|0.26.0
unreal-engine-4-helper|ope|0.3.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.1
scala|sca|0.5.5
shader|sle|1.1.5
selectline-statusbar|tom|0.0.2
vscode-input-sequence|tom|0.2.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptc:30404946
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by JacksonKearl** [comment] 2021-12-02 00:13
Duplicate of #137551

**Closed by JacksonKearl** 2021-12-02 00:13 UTC
Labels: bug, file-explorer, windows
