### ISSUE TITLE
icon not seen in dock when open (OSX)

### ISSUE THREAD

**Issue by husninazer** [microsoft/vscode#80113] opened 2019-08-30 14:52 UTC
Issue Type: <b>Bug</b>

When visual code is open, the icon on the macOS dock could not be seen.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ftp-simple|hum|0.7.0
cpptools|ms-|0.25.0
vetur|oct|0.22.2
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by weinand** [comment] 2019-08-30 16:14
I don't see this behavior:

<img width="74" alt="2019-08-30_18-13-25" src="https://user-images.githubusercontent.com/1898161/64035781-e964d600-cb51-11e9-9e74-a91d37db8e0f.png">

Please reboot your Mac and see whether that makes a difference.

**Comment by husninazer** [comment] 2019-09-01 12:50
Hi,

Please check.

[image: Screenshot 2019-09-01 at 3.48.15 PM.png]
Husni Abdul Nazer
+91 9895 605 376 (INDIA)
+966 5383 66531 (K.S.A)
<http://in.linkedin.com/in/husninazer>

**Comment by weinand** [comment] 2019-09-01 14:37
Most likely a duplicate of #63068, usually running `killall Dock` in the terminal will fix this.

**Comment by weinand** [comment] 2019-09-03 10:00
Does "killall Dock" fix the issue?

**Comment by husninazer** [comment] 2019-09-06 16:58
Yes resolved now. Thanks slot.

**Closed** 2019-10-15 21:55 UTC
Labels: needs more info
