### ISSUE TITLE
Multiple debug sessions fail after a few seconds

### ISSUE THREAD

**Issue by weeco** [Microsoft/vscode#38375] opened 2017-11-15 03:42 UTC
- VSCode Version: 1.19.0-insider (older non insider versions as well)
- OS Version: Win 10

I want to launch and debug two sessions at once by using VSCode's compound feature. They start absolutely fine together and I can switch between them as desired. However after a few seconds one of the applications is apparently crashing (or disconnecting the debugger) showing this error message:
https://i.imgur.com/Bs8h0E1.png

The other process keeps running. Is it possible to debug two node processes at the same time or am I doing something wrong?

**That's my launch.json:**

```
{
    "version": "0.2.0",
    "compounds": [
      {
        "name": "TokenCreator+Express",
        "configurations": [ "Token Creator", "Express Server" ]
      }
    ],
    "configurations": [
        {
          "type": "node",
          "request": "launch",
          "name": "Token Creator",
          "program": "${workspaceRoot}/src/microservices/token-creator/token-creator.ts",
          "outFiles": [
            "${workspaceRoot}/dist/**/*.js"
          ],
          "console": "integratedTerminal",
          "smartStep": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Express Server",
            "program": "${workspaceRoot}/src/index.ts",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "console": "integratedTerminal",
            "smartStep": true,
            "runtimeArgs": [
                "--max-old-space-size=4096"
            ]
        }
    ]
}
```

Reproduces without extensions: Yes

In the integrated terminal I noticed it would not print any lines about starting the second application until I close the first application (which has been started first by the debugger). Basically it seems VSCode is trying to execute the "node app" command in the same powershell. Am I missing something in my configuration maybe?

**Comment by weeco** [comment] 2017-11-21 01:30
I was able to replicate the behavior on my Mac environment. Do you need more information or were you able to reproduce the issue yourself as well? I would be very happy to use multi debug sessions soon.

**Comment by auchenberg** [comment] 2017-11-21 03:03
@weeco This is most likely caused by your second launch config that's using `runtimeArgs`, which overrides the default `runtimeArgs` that puts Node into debug mode.

Try removing `runtimeArgs` or specify `--inspect=9000` + setting `port: 9000` in your config too.

**Comment by weeco** [comment] 2017-11-22 23:24
@auchenberg I removed the args from the launch config but I am facing the same issue.

**Comment by irissoftworks** [comment] 2017-12-03 17:03
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/37589.

It seriously impacts node multi root workspaces, as it's not possible to debug/launch multiple node processes from the same vscode instance, when using the integrated terminal. Using the internal console is not a valid workaround, as console logging will be mixed up between processes.

Looking at the code, it seems to me the integratedTerminalInstance property is there only for this purpose (launch) and is always reused in this situation. 

It seems like it would be better if this property wasn't there at all, as I don't see how reusing a terminal can be good in these circumstances, considering booting the same launch config will probably fail for most people anyway (i.e for any app that binds to a network port). 

In any case, if possible, the final solution should tie the terminal instance to the actual launch config.

**Comment by weinand** [comment] 2017-12-03 17:19
duplicate of #37589

**Closed by weinand** 2017-12-03 17:19 UTC
Labels: bug, debug, insiders
