### ISSUE TITLE
Too much indentation for files in Explorer with the Seti icon theme

### ISSUE THREAD

**Issue by sambauwens** [Microsoft/vscode#19066] opened 2017-01-23 17:35 UTC
When activating the `Seti` icon theme, there is too much identation for file icons, which makes it look like the files are contained in the preceding folder (`win32` in the screenshot):

![image](https://cloud.githubusercontent.com/assets/1354090/22214463/f440a582-e197-11e6-968c-60628fa9b712.png)

In contrast, for the `Minimal` icon theme the alignment is good:

![image](https://cloud.githubusercontent.com/assets/1354090/22214563/4e30cc34-e198-11e6-9a06-af709263bee1.png)

Steps to Reproduce:

1. Enable the `Seti (Visual Studio Code)` icon theme

I hope I posted the issue in the right repository, I checked the [vscode-themes](https://github.com/microsoft/vscode-themes) repo, but it doesn't seem to contain the Seti theme.

---

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|xml|DotJoshJohnson|1.6.1|
|vscode-great-icons|emmanuelbeziat|1.1.40|
|csharp|ms-vscode|1.6.0|
|PowerShell|ms-vscode|0.8.0|
|vs-keybindings|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.4.1|

**Comment by sambauwens** [comment] 2017-01-23 17:36
I also was able to reproduce the issue with all extensions disabled.

**Comment by bpasero** [comment] 2017-01-23 17:37
@sambauwens 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by dansteren** [comment] 2017-01-28 01:21
This problem drives me insane. I love the icons, but every time I try to figure out which directory my files are in I have to do a double take.

I think the main problem is that no folder icon is included. Seti essentially uses the little arrows to indicate a folder. If you look through other themes, most have a folder icon. Since Seti is missing it then the files appear to be indented an icon width more than they really are. 

So, it seems like Seti should either add a folder icon:
![seti-improved](https://cloud.githubusercontent.com/assets/5455419/22392916/d7b24980-e4bb-11e6-9ff0-ec881da3c20f.png)
(mockup)

or if no icon folder is present in an icon pack, vscode should adjust the padding so that arrows and icons align:
![seti-indented](https://cloud.githubusercontent.com/assets/5455419/22392997/c57caf5c-e4bc-11e6-9be8-d9654f7befda.png)
(mockup)

**Comment by mousetraps** [comment] 2017-01-30 02:13
As @bpasero mentioned, the new seti theme should now look like this (which is similar to @dansteren's second mockup), and is available in our latest [insiders builds](https://code.visualstudio.com/insiders), so let us know what you think!
![image](https://cloud.githubusercontent.com/assets/762848/22410526/4adfe0fa-e64e-11e6-87ea-f77975c45980.png)

Closing as it appears that this issue is resolved, but happy to reopen if you think otherwise. Happy coding!

**Closed by mousetraps** 2017-01-30 02:13 UTC
Labels: needs more info

**Comment by dansteren** [comment] 2017-02-04 22:45
Follow up note: This has been incorporated into the January build (v1.9). If anyone is still having issues they should download this build.

Thanks guys! :)
