### ISSUE TITLE
Add a setting for `problems.exclude`

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#43135] opened 2018-02-07 21:25 UTC
Add a setting for `problems.exclude` that will exclude problem results from A) the problems pane and B) the explorer problem decorations. Use the same syntax as `files.exclude` or `search.exclude`.

Example syntax:
```json
  "problems.exclude": {
    "**/BadProject1": true,
    "**/BadProject2": true,
    "**/GoodProject/BadFile": true,
    "**/GoodProject/BadFolder": true,
  },
```

**Comment by firelizzard18** [comment] 2018-02-07 21:26
Example usage - When I have code that I am no longer maintaining, but might need again at a later date, instead of outright deleting it, I 'archive' it by moving it into an `archive` directory. However, some VSCode extensions have no support for excluding directories from their validation, so they report problems for this code. **I would like to be able to exclude these directories via my proposed mechanism.** I.E.:

```json
"problems.exclude": {
    "**/archive/**: true
}
```

**Comment by firelizzard18** [comment] 2018-02-07 21:34
Example usage - I am working on a large ecosystem of C# projects, with many cross-repo dependencies. For my day-to-day work, I clone all of the relevant repositories into the same parent directory, and I use relative references for cross-repo dependencies. However, for continuous integration, I have all of the dependencies I need as submodules, and I update dependency references to point at a submodule instead of a sibling repo (I don't actually update any files; MSBuild is smart). However, OmniSharp gets very upset with this setup and reports hundreds or thousands of spurious errors (I didn't count). **So I would very much like to be able to exclude specific directories, such as the one where I have my submodules.**

Dev setup:

- Work
  - Apps (git)
    - MainApp
      - references `../../Libs/MainLib/MainLib.csproj`
  - Libs (git)
    - MainLib

CI setup:

- Apps (git)
  - .libs - **I want to exclude problems from this directory**
    - Libs (git submodule)
      - MainLib
  - MainApp
    - references `../.libs/Libs/MainLib/MainLib.csproj`

**Comment by sandy081** [comment] 2018-02-08 09:28
Duplicate of #22289

**Closed** 2018-02-08 09:28 UTC
Labels: *duplicate
