### ISSUE TITLE
typescript  Syntax Highlighting Issues ?: operator 

### ISSUE THREAD

**Issue by pranjithkumar** [Microsoft/vscode#4774] opened 2016-03-29 20:48 UTC
- VSCode Version:0.10.10
- OS Version:windows 10 

Steps to Reproduce:

1. type    
       `var a              = ENV === 'dev' ? "a" : "b";`
       
2. " : " is consider as variable type 

![err](https://cloud.githubusercontent.com/assets/2296934/14123335/a494c0b0-f61d-11e5-9974-2dc11a4de218.png)

**Comment by mquandalle** [comment] 2016-03-29 22:32
Reproduced in Version 0.10.13-insider.

**Comment by Tyriar** [comment] 2016-03-31 17:20
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by Tyriar** 2016-03-31 17:20 UTC
