### ISSUE TITLE
variable substitution in configuration

### ISSUE THREAD

**Issue by xymopen** [Microsoft/vscode#46501] opened 2018-03-25 16:47 UTC
Can we have variable substitution in configurations as in tasks, e.g
``` json
//settings.json
"java.home": "${env:JAVA_HOME}",
```
It would be very helpful for portable usage.
Thanks!

**Comment by sandy081** [comment] 2018-03-26 09:14
Duplicate of #2809

**Closed** 2018-03-26 09:14 UTC
Labels: *duplicate, config
