### ISSUE TITLE
I am trying to install extensions, and none of them work

### ISSUE THREAD

**Issue by AxelDeathBR** [microsoft/vscode#227919] opened 2024-09-08 21:07 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: windows 10

Steps to Reproduce:

1. It seems that it can't find the folder or create a folder. It was working normally when I turned on the computer a little while ago, but now it's not working and showing this error.

![image](https://github.com/user-attachments/assets/51d110c2-5dae-4e0e-b74c-b6984a27ec10)

**Comment by AxelDeathBR** [comment] 2024-09-08 21:13
Strangely, it creates the folder inside the project and reads it, but it doesn't work after opening the FTP extension to access the server files, it gives an error. Ideally, it should read from the root folder of VS Code.

![image](https://github.com/user-attachments/assets/73e72840-141b-43f2-9ad6-b112adedd824)

**Comment by Hupx07** [comment] 2024-09-08 21:19
I had the same problem and a minor stroke when I realized that the error was in the vscode update! Use version 1.92.2 and disable auto update!

**Comment by AxelDeathBR** [comment] 2024-09-08 21:31
> I had the same problem and a minor stroke when I realized that the error was in the vscode update! Use version 1.92.2 and disable auto update!

That was indeed the issue; it is normal in the version you mentioned. Thank you. However, it should be noted, and they should resolve this.

**Comment by gjsjohnmurray** [comment] 2024-09-08 21:53
/duplicate of https://github.com/microsoft/vscode/issues/227743

**Closed** 2024-09-08 21:54 UTC
Labels: *duplicate
