### ISSUE TITLE
dark plus syntax无法使用

### ISSUE THREAD

**Issue by FlashMan2008** [microsoft/vscode#178226] opened 2023-03-24 12:51 UTC
Type: <b>Bug</b>

在最新版本的vscode insiders中，dark plus syntax无法正常使用，具体表现为变量名无法着色，不知道这个bug的原因。最新版本的vscode（非insiders）中就不会出现这个bug。变量名无法着色真的很丑陋，望快速修复，谢谢。
（这个错误应该是vscode更新造成的）

VS Code version: Code - Insiders 1.77.0-insider (21ae43efaeaa83fe42d29903740bc322a53a8f0d, 2023-03-24T11:30:34.956Z)
OS version: Windows_NT x64 10.0.23403
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.09GB free)|
|Process Argv|--crash-reporter-id 3185e92a-4268-4e72-ac88-f2177ab3b00b|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|3.0.2
z-reader|aoo|1.1.7
exe-runner|bra|0.2.1
bracket-select|chu|2.0.2
read-novel|DaH|1.0.1
c-cpp-compile-run|dan|1.0.44
competitive-programming-helper|Div|5.10.0
vscode-html-css|ecm|1.13.1
chrome-dinosaur-game|gee|0.0.1
gc-excelviewer|Gra|4.2.56
latex-workshop|Jam|9.8.0
vscode-fix-checksums|leh|1.1.0
vsls-whiteboard|los|0.0.12
vscode-language-pack-zh-hans|MS-|1.77.2023032209
isort|ms-|2022.8.0
python|ms-|2023.5.10831011
vscode-pylance|ms-|2023.3.30
remote-wsl|ms-|0.77.0
cpptools|ms-|1.15.1
vsliveshare|ms-|1.0.5834
vsliveshare-pack|ms-|0.4.0
sftp|Nat|1.16.1
material-icon-theme|PKi|4.25.0
vscode-yaml|red|1.12.2
snake-trail|ric|0.6.0
trailing-spaces|sha|0.4.1
vscode-zipexplorer|sle|0.3.1
line-erase-game|tai|0.5.2
txt-syntax|xsh|0.2.2
commandlist|yam|1.1.0
vscode-preview-server|yui|1.3.0
markdown-all-in-one|yzh|3.5.0
visual-snake-code|Zho|1.0.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30659907
pythonb192cf:30661257
defaultazurewalk:30687958
pythonms35:30671666

```

</details>

**Comment by aeschli** [comment] 2023-03-24 13:42
duplicate of https://github.com/microsoft/vscode/issues/177823

**Closed by aeschli** 2023-03-24 13:42 UTC
Labels: info-needed, *english-please, translation-required-chinese-simplified
