### ISSUE TITLE
Feature request: panel as a separate window

### ISSUE THREAD

**Issue by DifficultNick** [Microsoft/vscode#39889] opened 2017-12-07 19:52 UTC
It would be nice to have an ability to drag panel as a separate window (like in Visual Studio).
For example if you use 2 monitors this feature will produce a lot of space and make work more pleasant.

**Comment by mjbvz** [comment] 2017-12-07 22:07
duplicate of #10121

**Closed by mjbvz** 2017-12-07 22:07 UTC
Labels: workbench, workbench-layout
