### ISSUE TITLE
Annoying behavior while opening files with some settings behind

### ISSUE THREAD

**Issue by ketonal** [Microsoft/vscode#19214] opened 2017-01-24 15:01 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jsrefactor|cmstead|0.5.3|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.3.4|
|docthis|joelday|0.3.9|
|es6-angular-snips|kasperkeso|0.0.3|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|startanyshell|remcoros|0.3.1|
|gitblame|waderyan|1.3.0|
|JavaScriptSnippets|xabikos|1.2.0|

---

It started when I added following items to my user settings:
    "editor.formatOnType": true,
    "editor.formatOnSave": true

Now whenever I open any file, it's marked as edited - this is very annoying because I can't simply close it - I have to confirm because of *imaginary* (the file didn't changed really) changes that I've done fo this file. 

Steps to Reproduce:

1. Add to your user settings following items:
    "editor.formatOnType": true,
    "editor.formatOnSave": true
2. Restart VSC, open any file - it's instantaneously marked as edited.

**Comment by bpasero** [comment] 2017-01-24 16:32
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ketonal** [comment] 2017-01-24 19:28
Ok @bpasero - seems you're right - with `--disable-extensions` the issue doesn't occur. Thanks - I'll file proper issue to an extension that is causing it.
One more question though - is there any other way to discover which extension is causing problems than manually disable/enable one at a time?

**Comment by ketonal** [comment] 2017-01-24 19:34
Nevermind - I just found it: `EditorConfig 0.3.4`;)

**Comment by mousetraps** [comment] 2017-01-24 21:40
Closing as it looks like the issue's resolved. Happy coding!

**Closed by mousetraps** 2017-01-24 21:40 UTC
Labels: caused-by-extension
