### ISSUE TITLE
Drag and drop selected text

### ISSUE THREAD

**Issue by Ed-Dikotope** [Microsoft/vscode#9034] opened 2016-07-10 18:04 UTC
I often miss this feature from other editors. I just would like a way to be able to drag and drop my selected text instead of a whole copy & paste operation. Thanks for Tabs by the way!! With this little feature I'll be super happy 😃 .

**Comment by JoshMcCullough** [comment] 2016-07-12 18:47
Yes, this is a great feature in Visual Studio which I often miss in VS Code.

**Comment by mahomedh** [comment] 2016-07-22 09:17
The lack of this feature is REALLY killing my productivity. So much so I may have to go back to sublime now.

Also looks like this may be a duplicate of https://github.com/Microsoft/vscode/issues/1046 which was logged in Dec 2015.

**Comment by alexandrudima** [comment] 2016-08-16 13:38
Let's track in #1046

**Closed by alexandrudima** 2016-08-16 13:38 UTC
Labels: duplicate, editor, editor-core, feature-request
