### ISSUE TITLE
Windows 10: Menubar items blurry

### ISSUE THREAD

**Issue by kostadinnm** [Microsoft/vscode#5217] opened 2016-04-13 07:36 UTC
![2016-04-13 10_24_57-vsc](https://cloud.githubusercontent.com/assets/18436405/14485869/6cf1bd8e-0162-11e6-8bee-aaec991be38c.png)
- VSCode Version: 0.10.11
- OS Version: Windows 10 64bit latest(all updates installed)

Steps to Reproduce:
1. Just open the editor and the menubar texts are blurry.

The items each menu triggers are ok.

Could this be because of the engine(Chromium) that Visual Studio Code shares with Atom editor(Atom is havig the same issue)?!

**Comment by kostadinnm** [comment] 2016-04-21 16:43
bpasero, I think it's not fixable in VSCode. Those who are interested into the details, may take a look at the discussion for Atom:
https://github.com/atom/atom/issues/11442

IMHO, it's a pity simple things like this typography issue are plaguing these wonderful new tools.

We came to an agreement to close the Atom's issue for now - do you think we should do it for VSCode as well?!

**Comment by bpasero** [comment] 2016-09-18 07:06
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-09-28 13:02
@kostadinnm since you voted down, you still see this? I am not being notified if you react like that, you gotta talk.

**Comment by kostadinnm** [comment] 2016-09-28 19:02
Of course I am, Benjamin. I guess, it should be visible elsewhere utilizing DirectWrite's sub-pixel positioning. Had you even tried follow the conversation with damieng on the Atom thread?!
The thing is it's just not clear who's acting up. Clear my mind - was VSCode Chromium-based?! I need to find some other programs that utilize DirectWrite's sub-pixel positioning and compare the fonts' rendering. Still, since I'd written it wouldn't be fixable from VSCode, I must have read sth about the real blur-maker.
Anyways, telling us you believe it's fixed - I'm not ok. It's just that - I expressed a feeling. In the Atom thread we made some conversation. Here, I pointed towards the constructive discussion and we are getting a "robotish" bloaty answer. Simply closing the issue would've been better.

**Comment by bpasero** [comment] 2016-09-29 05:19
@kostadinnm I apologise, I went over a lot of issues where I was asking the people to give our insider release a try and somehow I missed to ask this here. We updated VSCode 1.6.0 to a much newer Electron version which bundles Chrome 52. Can you give that one a try to see if the issue is fixed or not?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

Also please keep in mind that you seem to be the only one having this issue on Windows 10 as I have not heard back from anyone else and we have many 100k users on Windows 10 I believe.

**Comment by kostadinnm** [comment] 2016-09-29 09:07
No worries.

Here's what I get from the VSCode insiders 1.6.0(are you able to spot the difference between the two 'i'-symbols):
![2016-09-29 11_59_30-visual studio code - insiders](https://cloud.githubusercontent.com/assets/18436405/18947695/cf1aaa70-863c-11e6-92cf-74b2b91bb2cb.png)

It's not a surprise to me, as with the latest chrome browser has the same output in its settings.

Cheers,
Kostadin

**Comment by bpasero** [comment] 2016-09-29 10:21
<img width="1474" alt="screen shot 2016-09-29 at 12 20 55" src="https://cloud.githubusercontent.com/assets/900690/18950235/33d2377e-863f-11e6-8dda-f71366158431.png">

Looks like I am getting subpixel anti aliasing on my Windows 10. You say you get grayscale anti aliasing?

**Comment by bpasero** [comment] 2016-09-29 10:22
Actually you get subpixel anti aliasing but your result looks different compared to mine (which may not be surprising depending on the monitor hardware).

**Comment by kostadinnm** [comment] 2016-09-29 10:40
Mhm, I hadn't known that matters as well. I have four monitors I could test with. Two of which(some old Belinea 1945SW and one LG Monitor TV M2352) are nearby. It must be monitor-hardware inability on those. The other two are Asus ProArt PA246Q and BenQ BL3200PT.
I'll try my best to get them tested as well. I'm strictly using digital connections(DVI, HDMI) and RDP-ing between the machines(font-smoothing thicked), but I doubt the latter matters. Plus, VSCode is pretty lightweight and I may install it even on my weakest machine.

Cheers,
Kostadin

**Comment by kostadinnm** [comment] 2016-09-29 14:14
Wait, Benjamin, it's not my monitor hardware. Your screen shot has at least three different 'i'-symbols as well. It's a whole other issue described in this article:
[The price of smooth looks: Anti-aliased fonts hurt eyes and damage eyesight](http://annystudio.com/misc/anti-aliased-fonts-hurt/)
So, it's a generic OS-issue(to me). In fact, I haven't tested myself like it's described in the article(how long a person is able to read without feeling tired eyes), but the fact that I am able to detect it in my full hd screen makes me crazy.
And, just to make it all clear, since chromium is a web rendering engine sticking to the trends(allowing fancy fonts) in conjunction with the latest OS which assumes people are all using 4k monitors leads to that cramped small fonts feel.

**Comment by bpasero** [comment] 2016-09-29 14:18
@kostadinnm but you are saying you only have this issue with the menu bar items not inside VS Code right?

**Comment by kostadinnm** [comment] 2016-09-29 14:37
No, it's not in the menu only. Look at those 'i'-symbols:
![2016-09-29 17_22_33-java - visual studio code - insiders](https://cloud.githubusercontent.com/assets/18436405/18958110/36f2153e-866a-11e6-9483-f0a3c497cd4f.png)

In Atom and Google Chrome settings it's the same. I am getting really distracted by this.
Even the github-form that I am writing this comment from is using the same method(although a different browser) - what a downfall :(

Here's a petition in that regards:
[Bring sharp fonts back in Google Chrome (Disable DirectWrite)](https://www.change.org/p/google-inc-bring-sharp-fonts-back-in-google-chrome-disable-directwrite)

But, it's not only Google involved, the OS-development is also there - I found complains about not being able to disable ClearType on modern Windows and its equivalent on OS X.

**Comment by kostadinnm** [comment] 2016-10-02 16:04
Ok, I am taking my words back about the github-form and partially on the issue:
-I wasn't aware that font anti-aliasing is not working that well on small fonts. No anti-aliasing isn't an option as well - I tried it and its worse.
-The github-form is at least consistent across the symbols-rendering. Some seem blurry on my .285 pixel pitch monitor(the lowest dpi one I have, but shouldn't be any different on the highest, which has pixel pitch of 0.27), others are crisp. For example, the 'i' and the 'l' -symbols are pretty readable, while the 'm' has some little distortion in the middle and the 'u' is hard to get on the right. There are combinations of hw/sw anti-aliasing, font-size, symbol overlapping, etc that designers are setting as preferred for the browser to render. So, I guess for this form they did their best.
To recap - this shouldn't be misclasified as a general fault on any OS or browser engine. It's just the way anti-aliasing works.

Offtopic: I now have doubts on the petition(s) I linked. There's another one from the same person, which is more general. I don't really understand what's that wrong with DirectWrite/Direct2D vs GDI. To me non-antialiased small fonts are worse than anti-aliased. If it's only for the overlapping - I think I can bear it. If there's a discussion, it should be on "designing desktop views with dpi-aware font size". This means maintaining readability on the older monitors and smoothen text even further for the new 4K-screens. As simple as that :)

I've written this on the active thread, but should apply to Atom-users as well.

So, Benjamin, one more time - shall we close(not mark 'fixed') this one now!? Disclaimer: feel free to initiate technical improvement had you got to think it's a matter crippling VSCode-usability To me, it's still not quite ok, but, as now I know what's under the hood, I consider it normal and would just honor any improvement had anyone decides to dig in.

Cheers,
Kostadin

**Comment by damieng** [comment] 2016-10-02 16:18
The reason you get three different looking i's is because it is not only using sub-pixel rendering but sub-pixel positioning, probably using `DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL`

`DWRITE_RENDERING_MODE_CLEARTYPE_GDI_NATURAL` would probably be a better choice for the menu bar.

**Comment by bpasero** [comment] 2017-04-10 17:08
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by kostadinnm** [comment] 2017-04-13 10:48
No, same thing(in actual size the 'i' symbols in the menu are different):
![2017-04-13 13_43_47-untitled-1 - visual studio code - insiders](https://cloud.githubusercontent.com/assets/18436405/25001741/9295dc52-204f-11e7-99c5-b776acd55b79.png)
Best regards,
Kostadin

**Comment by bpasero** [comment] 2017-11-15 14:15
Still happening?

**Comment by kostadinnm** [comment] 2017-11-15 14:33
I uninstalled the preview, but with 1.18 it still is:
![2017-11-15 16_28_21-welcome - visual studio code](https://user-images.githubusercontent.com/18436405/32841299-9bad5efa-ca22-11e7-893d-dd0304916345.png)
Anyways, thanks for still being concerned :)

**Comment by kostadinnm** [comment] 2018-06-09 11:50
Has anyone bumped into this lately - it continues to tease me(comparing it to a python-biased editor)?!
Here's a link on the matter I'd been keeping in my outbox-drafts, but never shared, neither here, nor at the [atom-issue](https://github.com/atom/atom/issues/11442): [Subpixel accurate GPU rendering of text using a glyph atlas](http://rasmusbarr.github.io/blog/subpixelglyph.html). As most of the monitors nowadays are pretty wide, I guess removing that blurriness at the expense of widening the text could be at least configurable. It still may not help, but at least the issue isn't slaughtered by a lock-bot :)

Cheers,
Kostadin

**Comment by kostadinnm** [comment] 2018-07-07 14:44
Here's a screenshot of some options available on another editor:
![webstorm-settings](https://user-images.githubusercontent.com/18436405/42411870-8ff66e60-820c-11e8-96d6-392bbd5e49b8.jpg)
Zoom to notice how the right one(subpixel) is so much even in regards to the font rendering. It still needs adjustment(contrasting colors, font size), but the letters and spaces between them are rock consistent.

**Comment by bpasero** [comment] 2018-08-17 05:28
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.

**Closed by bpasero** 2018-08-17 05:28 UTC
Labels: electron, font-rendering, upstream, workbench-menu

**Comment by kostadinnm** [comment] 2018-08-17 17:51
That allows me to change the background through `titleBar.activeBackground`. What you imply is that soon those fonts should be adjustable and the user should be able to pick whatever(preferably anti-aliased) fonts they like?!
But that's not the point. It's the anti-aliasing method that's missing(even in the editor window where the code lives and I'm already tired of making screenshots). Otherwise there wouldn't have been such stackoverflow questions:
[Blurry/flickering text rendering in Electron](https://stackoverflow.com/questions/42878277/blurry-flickering-text-rendering-in-electron)
So again, should you close this vital eye-healthiness issue or help present it to someone who could give some more ![2018-08-17 20_47_41-test1 js - es6 - visual studio code](https://user-images.githubusercontent.com/18436405/44280931-e0fb6f00-a25e-11e8-8bc2-c1341bf3ce54.png) (isn't it ironic)?!
