### ISSUE TITLE
Combine New Minimap with Git Sidebar

### ISSUE THREAD

**Issue by bkentdev** [microsoft/vscode#22563] opened 2017-03-13 21:05 UTC
There are "two" many minimaps. 😆 
With the minimap and the old "git sidebar", there appear to be two minimaps. This is especially problematic when navigating/traversing a file by using each minimap. Its just confusing. They should be combined into one to minimize the confusion/user-friction in utilizing the new minimap feature:

![two-many-minimaps-2](https://cloud.githubusercontent.com/assets/10407384/23875201/cbd037be-07f5-11e7-9f9b-106fc4e8a7d4.gif)

- VSCode Version: 1.10.2
- OS Version: MacOS 10.12.2

Steps to Reproduce:

1. Enable mini-map
2. Navigate through a file using the minimap _and_ the git sidebar

**Comment by rmunn** [comment] 2017-03-15 09:55
Possibly related: https://github.com/Microsoft/vscode/issues/20853 and https://github.com/Microsoft/vscode/issues/20934. Both mention adding Git status to the minimap, but they also have several other suggestions, so this isn't precisely a duplicate of either one. Might be worth keeping one issue open per suggestion -- this one could be the "Git status" issue, while another could track the "find matches" suggestion from https://github.com/Microsoft/vscode/issues/20934, and so on.

**Comment by cyphernull** [comment] 2019-08-16 04:56
the minimap with git diff feature is still under development？

**Comment by RMacfarlane** [comment] 2019-10-10 22:21
There are several issues about combining the minimap and the scrollbar that I'm trying to consolidate right now. https://github.com/microsoft/vscode/issues/28653 has the most discussion and upvotes, so I'd like to use that one as the primary tracker of this work. This is something I'd really like to see done and something I plan to work on in the coming iterations. I'm closing this as a duplicate, please go upvote https://github.com/microsoft/vscode/issues/28653. Thank you!

**Closed by RMacfarlane** 2019-10-10 22:21 UTC
Labels: editor-minimap, feature-request
