### ISSUE TITLE
Online VS CODE Error Code Navigation

### ISSUE THREAD

**Issue by deepesh0102** [microsoft/vscode#149608] opened 2022-05-16 01:24 UTC
- VS Code Version: Online VS-CODE 
ver Github repository
- OS Version: Windows 11

Steps to Reproduce: 

1. Open VS-CODE online with the git repository
2. Open the file got for code navigation ( Ctrl+click (Cmd+click on macOS) ).

I am getting an Error. Error screenshot attached

![Screenshot 2022-05-16 064344](https://user-images.githubusercontent.com/16727830/168504402-d53bce61-36eb-420a-ac1d-7339076eee18.png)

**Comment by lszomoru** [comment] 2022-05-16 10:43
@deepesh0102, are you able to reproduce this issue all the time? If so, could you please do the following:
1. Open the Settings editor and set the value of the `remoteHub.logLevel` setting to  `debug`
2. Reload the window and try to reproduce the problem so that the error appears in the editor
3. Open the Output window by invoking the View -> Output menu
4. In the dropdown, choose "Remote Repositories"
5. Send out the contents of the output channel

**Comment by joyceerhl** [comment] 2022-05-16 13:50
Duplicate of https://github.com/microsoft/vscode/issues/146853

**Closed by joyceerhl** 2022-05-16 13:50 UTC
Labels: needs more info, vscode.dev
