### ISSUE TITLE
Needs ability to provide "user css" 

### ISSUE THREAD

**Issue by jsumners** [Microsoft/vscode#21798] opened 2017-03-02 16:20 UTC
- VSCode Version: 1.10.0
- OS Version: macOS 10.12.3

PR #14237 added a style that I have been eagerly waiting for. However, now that it has been released, it's still unusable for me. I have a theme installed that I like except for the styling around the cursor (`.monaco-editor .cursors-layer.cursor-block-outline-style > .cursor`). So the reasonable assumption would be that I can override that style with my own styling. But that isn't the case; vscode doesn't provide any way to specify user styles., e.g. in Atom select "Stylesheet..." from the Atom menu.

**Comment by balupton** [comment] 2017-03-03 03:53
I wish this was provided as it would solve two things:

1. Fixing font rendering for me: https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289

2. Overriding theme values - such as a background colour.

**Comment by hoovercj** [comment] 2017-03-03 09:15
Duplicate of the still open #11556 and #459

Similar closed issues:
#13732
#3570
#9004

**Comment by isidorn** [comment] 2017-03-03 10:27
Closing as duplicate
Thanks @hoovercj

**Closed by isidorn** 2017-03-03 10:27 UTC

**Comment by jsumners** [comment] 2017-03-03 13:23
So for at least a year people have been saying this feature is needed and no one has bothered?

**Comment by shalldie** [comment] 2017-06-30 20:11
So far, i want to custom my self css for a long long long time.

Man who agree with me?  give me a 👍

**Comment by hoovercj** [comment] 2017-06-30 20:16
@shalldie I believe the team has said elsewhere (and they'll correct me if I'm wrong) that they would prefer to avoid user css as it can prevent them from iterating on the underlying Dom structure to avoid breaking custom css. They want each api they release to be stable and long lived, and that doesn't work with custom css.

**Comment by jsumners** [comment] 2017-06-30 20:48
That's a load of garbage. The issue at hand would allow overriding a theme's CSS with user preferences. If it works in a theme, what would the difference be in applying another stylesheet on top of it?

**Comment by hoovercj** [comment] 2017-06-30 20:55
@jsumners Theme overrides are tracked in this issue #27894 and I have a PR for it here #29393
