### ISSUE TITLE
macOS Mojave: VSCode requests access to Contacts and Calendars

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#55236] opened 2018-07-27 12:25 UTC
- VSCode Version: 1.24.0
- OS Version: 10.14 (MacOS Mojave)

Steps to Reproduce:

1. Give it few minutes
2. You get multiple popups "Visual Studio Code" would like to access your calendar.

If the apps stays open for long you will get lots of them, as apparently a new set is generated every few minutes.

Does this issue occur when all extensions are disabled?: Yes/No

Similar https://github.com/atom/atom/issues/17687

**Comment by krupenja** [comment] 2018-07-28 23:53
This is not VSCode-specific: I have seen this with ~10 other apps, including non-Electron ones.

**Comment by bpasero** [comment] 2018-08-06 12:46
Yeah, unlikely something we are doing in Code.

**Comment by ssbarnea** [comment] 2018-08-06 14:25
@bpasero I think that if you do "code ~" and perform a search in files you will hit this bug.

Arguably this is related to the fact that now MacOS is displaying a popup for each read access attempted by any application on these sensitive locations (calendar, contacts,...).

Lots of apps are affected by this and the UX is awful. What is worse is that is likely that Apple will do nothing about it, considering it a feature. I would rather prefer a silent access denied response than an interactive popup that stacks! ... meaning 100 accesses = 100 popups to close!

While the bug is no specific to vscode, I still think that vscode needs to do something to avoid it, unless we want to be hit by huge number of complaints from the users.

**Comment by bpasero** [comment] 2018-08-12 17:04
Reopening to track this issue for Mojave. It likely boils down to be an Electron issue.

**Comment by bpasero** [comment] 2018-09-17 10:08
@ssbarnea @krupenja does this still happen with latest betas?

**Comment by ssbarnea** [comment] 2018-09-17 12:08
@bpasero I stopped using a git repo in $HOME root to avoid this issue, so I don't know.

**Comment by bpasero** [comment] 2018-09-17 13:09
Ok, I am asking because it looks like https://github.com/atom/atom/issues/17687 was closed.

**Comment by ssbarnea** [comment] 2018-09-17 13:17
Based on last comments on Atom sister bug, I am closing this too. Apple did some magic to avoid the annoying popup so we don't have to add extra code.

**Comment by hanssens** [comment] 2018-09-28 14:01
FWIW: Same for me happend just now. Opening a new instance of VS Code today resulted in these dialogs. I've rejected them with [Don't allow].

What I did:

- Worked on an existing VS Code instance for roughly a day
- Quit the app completely yesterday evening
- Reopend the same instance today (nothing happened)
- Opened a new instance of VS Code with Cmd+Shift+N and the access dialogs popped up

![2018-09-28_03-09-03_pm](https://user-images.githubusercontent.com/493382/46212840-456a1d80-c337-11e8-9060-cc2bbb0fe8e3.png)
![2018-09-28_03-09-10_pm](https://user-images.githubusercontent.com/493382/46212849-4a2ed180-c337-11e8-9b81-dea1cac3f215.png)
![2018-09-28_03-09-15_pm](https://user-images.githubusercontent.com/493382/46212853-4ef38580-c337-11e8-8488-05327dc11ad7.png)

I'm running VS Code v1.27.2 (1.27.2) on macOS 10.14 Mojave. Upgraded to Mojave four days ago and used VS Code every day until this suddenly popped up now.

**Comment by connorshea** [comment] 2018-10-02 22:59
I got the contacts dialog when trying to create a new snippet (Settings gear in the bottom left > User Snippets > New Global Snippets File). It seemed to coincide with the file dialog opening, though I'm pretty sure I've opened the file dialog multiple times in VS Code without this happening, so 🤷‍♂️ 

I've been running Mojave since it came out last Monday, not really sure why it only started appearing now.

<img width="532" alt="screen shot 2018-10-02 at 4 54 01 pm" src="https://user-images.githubusercontent.com/2977353/46381563-0fdd7100-c664-11e8-98ac-cdb996e65a68.png">

Versions: VS Code 1.27.2, macOS Mojave 10.14 (can provide more info if needed)

**Comment by RaedShari** [comment] 2018-10-06 18:36
I got the calendar, contacts, Photos dialogs. I opened my project using terminal `code .` when it was completely closed.

**Comment by samuela** [comment] 2018-10-10 23:37
I also just came across this. No idea how to really reproduce as I got this dialog after opening Calendar, with VSCode only unused in the background.

**Comment by consbulaquena** [comment] 2018-10-29 23:29
Yes, I even experience after upgrading to Mojave few days ago.
"Visual Studio Code" would like to access your photos. Then another popped up, "would like to access your contacts"

**Comment by johncrisostomo** [comment] 2018-11-05 07:14
Also got this multiple times today on Version 1.28.2 (1.28.2). I do not close my editors and just leave my Mac on sleep most of the time. So I am not sure what triggered it.

It first asked permission to access my contacts. After an hour it was asking permission to access my calendar. I declined both; and after a few hours it was asking to access my photos. Then I thought of Googling it and found this thread.

**Comment by igwejk** [comment] 2018-12-22 22:06
I as well have experienced this issue yesterday in `Code v 1.30.1`, `macOS Mojave v 10.14.2`.

**Comment by enriquenov** [comment] 2018-12-28 06:09
I had just experienced this same weird issue for the first time after weeks from the last comment. Seems like it will continue to persist until further notice.

**Comment by matpag** [comment] 2019-06-07 12:59
This is still happening to me with Mojave 10.14.5 and VS Code 1.35.0.

Mostly happen when trying to open a file with File -> Open...

**Comment by missmatsuko** [comment] 2019-06-20 17:32
Atom has a good support article on this:
https://discuss.atom.io/t/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/59291

**Comment by Tyriar** [comment] 2019-10-09 22:39
Closing as won't fix, see [atom's article](https://discuss.atom.io/t/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/59291) for the reason  and how to workaround the problem.

**Closed** 2019-10-09 22:39 UTC
Labels: *out-of-scope, electron, mac, mojave, upstream

**Comment by renjithspace** [comment] 2020-02-06 10:01
I receiving the same when I run electron app via node.

```
node electron-project/app.js // -> popup
```
<img width="532" alt="Screenshot 2020-02-06 at 3 27 23 PM" src="https://user-images.githubusercontent.com/11629673/73926315-6e200100-48f5-11ea-8cc3-67eb29ae3d00.png">
