### ISSUE TITLE
HTML Intellisense Broken in PHP file

### ISSUE THREAD

**Issue by chrisakatrace** [Microsoft/vscode#43462] opened 2018-02-12 04:01 UTC
### Issue Type
Bug

### Description

When I create a file with a ".php" extension the HTML intellisense no longer works. PHP files are primarily HTML, so this makes Visual Studio Code non-competitive for PHP coding.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|7.93GB (2.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.5
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.1
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
live-server-preview|neg|0.0.4
bootstrap4-vscode|the|3.0.0
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by aeschli** [comment] 2018-03-12 11:18
duplicate of https://github.com/Microsoft/vscode/issues/670

**Closed by aeschli** 2018-03-12 11:18 UTC
