### ISSUE TITLE
Two minor bugs in top bar on BigSur MacOS

### ISSUE THREAD

**Issue by smhk** [microsoft/vscode#110741] opened 2020-11-16 17:06 UTC
Issue Type: <b>Bug</b> (minor)

You're probably aware of this, hope it helps!

![Screen Shot 2020-11-16 at 11 03 09 AM](https://user-images.githubusercontent.com/3938526/99284170-8c5b4b80-27fb-11eb-8104-5da3a4bce5a3.png)

!! LOVE VSC !!

**Comment by misolori** [comment] 2020-11-16 18:36
Duplicate of https://github.com/microsoft/vscode/issues/106528

**Closed by misolori** 2020-11-16 18:36 UTC

**Comment by smhk** [comment] 2020-11-16 19:11
@misolori  thanks, you guys **_ROCK_** !!
