### ISSUE TITLE
Shift + Del will clear the clipboard's content

### ISSUE THREAD

**Issue by guoit** [Microsoft/vscode#56039] opened 2018-08-08 21:46 UTC
Issue Type: <b>Bug</b>

If I copy or cut text to clipboard, deleteing the line through Shift + Del will also clear the clipboard.

1. Type "abc" in a new line
2. Copy "abc" to clipboard with Ctrl + C
3. Delete the line with Shift + Del (may need to do this twice to completely delete the line)
4. Move cursor to any place and use Ctrl + V to paste the content in clipboard

Expected: "abc"
Observed: empty

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.27GB free)|
|Process Argv|D:\Program Files (x86)\Microsoft VS Code\Code.exe L:\py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12
python|ms-|2018.7.1
cpptools|ms-|0.17.7
python|tht|0.2.3

</details>

**Comment by ramya-rao-a** [comment] 2018-08-09 00:18
- Doesnt repro if Shift+Del is hit only once
- Doesnt repro if Shift+Del is hit after escaping the current selection

Looks like when pressing Shift+Del, what ever is getting deleted gets copied to the clipboard

**Comment by ris58h** [comment] 2018-08-09 14:35
@ramya-rao-a Isn't it a default behavior (the same as for CTRL+X) for Windows/Linux(some distros)?

**Comment by ragar005** [comment] 2018-08-09 16:22
when you click Shift+Del for the first time, actual content is copied to clipboard and also the content will be deleted at the same time. No need to do this twice.
When you do Shift+Del second time of course as the content is empty, the empty content is copied to the clipboard. So, when you paste it, it will be empty. 
Just do Shift+Del only once to delete and copy the content to the clipboard. This is not a bug according to me.

**Comment by ramya-rao-a** [comment] 2018-08-09 16:49
@ris58h You are right! So are you @ragar005.

I read the line `deleteing the line through Shift + Del` and assumed Shift+Del was meant for deleting lines.

Looking at our keyboard shortcuts, we have
Shift+Del for cut and Ctrl+Shift+K for deleting lines

![image](https://user-images.githubusercontent.com/16890566/43913245-682b3fde-9bb9-11e8-8bf9-28537072b4d1.png)

Closing as by design

**Closed by ramya-rao-a** 2018-08-09 16:49 UTC
Labels: bug, editor
