### ISSUE TITLE
Cannot read file from Folder

### ISSUE THREAD

**Issue by rishabh8** [Microsoft/vscode#1827] opened 2016-01-06 13:46 UTC
[c:/Program Files/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files/Microsoft VS Code/resources/app/extensions/csharp-o/package.json: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\extensions\csharp-o\package.json'

**Comment by joaomoreno** [comment] 2016-01-07 08:18
Before you fix this, can I ask you to zip up the contents of `c:\Program Files\Microsoft VS Code\resources\app\extensions\csharp-o` and upload them somewhere where I can look at?

You can fix this by simply deleting the `c:\Program Files\Microsoft VS Code\resources\app\extensions\csharp-o` directory using the Windows Explorer.

Duplicate of #1605.

**Closed by joaomoreno** 2016-01-07 08:18 UTC
