### ISSUE TITLE
An exception to the shortcut 'Ctrl + S' failed to perform an exact undo

### ISSUE THREAD

**Issue by 377960738** [microsoft/vscode#110280] opened 2020-11-10 03:44 UTC
Issue Type: <b>Bug</b>

When editing a document, when I press Ctrl + S for many times, and when I press Ctrl + Z to undo the modification, there will be abnormal performance. For example:
When I type the letter 'a' and press the key combination of 'CTRL + S' three times, when I want to cancel the letter 'A', I find that I need to operate the key combination of 'CTRL + Z' four times to cancel the letter 'A'. Is this a BUG?If so, please fix it.I didn't find this setting in any of the other editors I used, and I tested it with all the plug-ins disabled, and found that there was still a problem.Of course, when I submit bug reports, I enable the extensions That I have installed.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.85GB free)|
|Process Argv|--crash-reporter-id 3ac5d4aa-e0d9-4377-820c-b495552af323|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.5.4
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
tortoise-svn|fan|0.1.1
vue-format|feb|0.1.8
php-intellisense|fel|2.3.14
composer|ika|0.7.1
vue|jcb|0.1.5
vscode-phpfmt|kok|1.0.30
vs-color-picker|lih|1.0.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-zh-hans|MS-|1.51.2
powershell|ms-|2020.6.0
sublime-keybindings|ms-|4.0.7
team|ms-|1.161.1
php-docblocker|nei|2.1.0
vetur|oct|0.29.1
laravel-blade|one|1.24.0
minapp-vscode|qiu|2.2.2
vscode-flexbox-picker|Rax|0.0.1
java|red|0.70.0
vscode-xml|red|0.13.0
vscode-nginx|sha|0.6.0
php-formatter|Sop|0.2.4
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-icons|vsc|11.0.0
json|Zai|2.0.2
svn-helper|Zlo|1.0.3

</details>

**Comment by alexdima** [comment] 2020-11-12 13:55
Duplicate of #110141

**Closed by alexdima** 2020-11-12 13:55 UTC
