### ISSUE TITLE
Add property for all editor tabs to vscode.window namespace

### ISSUE THREAD

**Issue by PaulTFreedman** [Microsoft/vscode#36222] opened 2017-10-13 11:21 UTC
I was looking at writing an extension that changed the active tab when a mouse scroll event is detected but there don't appear to be any properties exposed that allow access to all the open tabs (editors). There is a property called activeTextEditor which contains the editor with focus and another one called visibleTextEditors which contains all the editors visible to the user. I would like another property that contains all of the text editors that the user has open.

For example if there is only 1 editor group open containing 3 files then the property would contain 3 elements.

I opened this already on the [vscode-extension-vscode](https://github.com/Microsoft/vscode-extension-vscode/issues/78) project but was told to post it here.

**Comment by jrieken** [comment] 2017-10-13 13:26
duplicate of #15178

**Closed by jrieken** 2017-10-13 13:26 UTC
Labels: api
