### ISSUE TITLE
React is poorly supported (especially .js file)

### ISSUE THREAD

**Issue by rui-infotrack** [Microsoft/vscode#1378] opened 2015-12-16 13:07 UTC
Created a test.js and wrote very simple React code. This is what I got:
<img width="494" alt="capture" src="https://cloud.githubusercontent.com/assets/12144265/11841504/e0ff8cce-a451-11e5-824e-ffb924872110.PNG">

To be honest, currently VS Code has very bad support of React syntax and it's basically useless. This issue has been there for quite some time... just wondering: is it going to be fixed?

**Comment by dbaeumer** [comment] 2015-12-16 13:10
@jrieken

**Comment by louy** [comment] 2015-12-16 13:32
You're probably missing Props & State interface types.

    interface Props { /*...*/ }
    interface State { /*...*/ }
    class MyComponent extends React.Component<Props, State> {
      // ...
    }

**Comment by jrieken** [comment] 2015-12-16 14:02
duplicate of #140

**Closed by jrieken** 2015-12-16 14:02 UTC
Labels: js

**Comment by rui-infotrack** [comment] 2015-12-16 22:11
@louy I wasn't using typescript. I just wrote some ES6 + React.

**Comment by louy** [comment] 2015-12-17 09:10
@rui-infotrack oh sorry. Ignore what I said then. Someone else was having the same problem with `tsx` and I must've overlooked your issue.
