### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by andriemc** [microsoft/vscode#226617] opened 2024-08-26 13:22 UTC
In atom you could edit the css of the editor, and that allowed for a lotta customizability.
What if we could get that same thing in VSCode? It would even make some of the requested features already available in the editor.

**Comment by aeschli** [comment] 2024-08-27 07:55
See https://github.com/microsoft/vscode/issues/168856#issuecomment-1346662409 why we don't want to go that way.

Closing as duplicate of https://github.com/microsoft/vscode/issues/459

**Closed by aeschli** 2024-08-27 07:55 UTC
