### ISSUE TITLE
C++ debugging broken as of VSCode 1.58

### ISSUE THREAD

**Issue by jonas-k** [microsoft/vscode#130419] opened 2021-08-09 17:36 UTC
Does this issue occur when all extensions are disabled?: No, since features of the extension itself are broken.

- VS Code Version: 1.58 / 1.59
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Install the C/C++ Extension from Microsoft or CodeLLDB by Vadim Chugunov
2. Configure a launch configuration similar to this
```
{
	"name": "Name",
	"preLaunchTask": "Build App",
	"type": "cppdbg",
	"MIMode": "lldb",
	"request": "launch",
	"expressions": "native",
	"cwd": "${workspaceFolder}",
	"program": "path/to/executable"
}
```
3. Try to debug

Observed behavior

- VSCode's status bar does not turn orange and breakpoints do not hit. The console works though.
Since both of the extensions mentioned stopped working in VSCode 1.58 I assume that the issue is in VSCode rather than in the extensions.

**Comment by jonas-k** [comment] 2021-08-10 04:52
As I mentioned in the bug description, I assume that the issue is in VSCode rather than in the extensions mentioned since both of these extensions stopped working after the update to VSCode 1.58, but work fine in 1.57.

**Comment by sean-mcmanus** [comment] 2021-08-11 01:32
@connor4312 We believe this is a VS Code bug/regression, because it started happening after a VS Code update and affects multiple debugger extensions.

**Comment by isidorn** [comment] 2021-08-11 13:59
@sean-mcmanus can you reproduce with latest vscode insiders? If yes with what debugger extensions can you reproduce since you say that it affect multiple? Thanks

**Comment by jonas-k** [comment] 2021-08-11 14:14
I just tested the latest insider build and with only the two mentioned extensions installed debugging worked as intended. Either it is fixed in the insider build or something else in my regular installation is causing the problems. I'll check my regular installation now for other possible causes and report back.

**Comment by jonas-k** [comment] 2021-08-11 14:36
I tested again and now both extensions stopped working. I did not change any settings. I just ran the CodeLLDB debugger (which worked initially) then tried the C/C++ Extension debugger (which did not work) and then tried the CodeLLDB debugger again which then also stopped working.
I also tried to delete the .vscode-insiders folder in my personal folder and installed the extensions again, but it seems that it is broken now.

**Comment by isidorn** [comment] 2021-08-11 14:38
Let's wait for @sean-mcmanus to investigate on the C++ side first. Once he provides more details we will know more.

**Comment by sean-mcmanus** [comment] 2021-08-11 17:00
@isidorn I haven't reproed the issue (and we haven't gotten widespread reports as far as I know). It might be something particular with the user's setup. @WardenGnaw is our debugger expert. He might know how to get more debugger logging/diagnostics.

**Comment by WardenGnaw** [comment] 2021-08-11 17:25
From the original issue in vscode-cpptools:
> The issue is that VSCode doesn't turn orange to indicate it is in debugging mode and that breakpoints don't work anymore.

It seems like the debug adapter has not activated so it would not produce any debug logs if we enable them in the `launch.json`

> I just ran the CodeLLDB debugger (which worked initially) then tried the C/C++ Extension debugger (which did not work) and then tried the CodeLLDB debugger again which then also stopped working.

This indicates that it seems to occur across extensions.

**Comment by jonas-k** [comment] 2021-08-13 10:20
I just did a bit more testing and found out how to get it back to working for one time before failing again:

1. delete the file ~/Library/Application Support/Code/CachedExtensions/user
2. restart VS Code
3. debug again

The contents of the user file created when launching VS Code are identical to the contents of the deleted version. I assume the the lack of this file triggers some reinitialization of the user extensions within VS Code that makes them work again for one session.

**Comment by nevikw39** [comment] 2021-08-16 06:11
Same problem on Intel MacBook Pro with Big Sur 11.5.1.
In 1.59, the external console starts, but the input doesn't work.
I've downgraded to 1.57, reinstalling C++ extension, and everything is fine.

**Comment by mikebeaton** [comment] 2021-08-30 20:10
I believe this issue is related to incorrect `cwd`. As others are reporting, my instance of lldb is not loading any symbols or other init files. A quick test `-exec shell pwd` shows that the current directory is the `program` directory, not the `cwd` directory as it should be. Further, copying the program files to the `cwd` directory and then running the program from there - as a test - makes everything work again.

**Comment by mikebeaton** [comment] 2021-08-31 15:01
@isidorn - Hopefully if what I think I've found (see immediately above) holds up, it should also be easily repeatable? Thanks!

**Comment by WardenGnaw** [comment] 2021-08-31 18:10
@mikebeaton Can you open an issue in the C++ extension for your issue? Its a bit separate since in your scenario the debug adapter is launched and there should be logs by adding the following to your `launch.json`.
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```
They should output to the `Debug Console` and please include those in the new issue. 

This issue is indicating the debug adapter never starts.

**Comment by mikebeaton** [comment] 2021-08-31 19:46
I had those enabled already, it's just mentioning lots of things that can't be found. Changing the directory as indicated, it can be found.

Also, I thought the issue was the same, because without the debug logs the only real difference is that, as the OP says, breakpoints are not hit.

Let me just double-check whether the issue for me is also related to v1.58 (it's definitely recent).

**Comment by mikebeaton** [comment] 2021-09-01 17:49
@WardenGnaw You are correct: I have a separate issue, which has already been reported a few hours ago (just now that I have pinned it down!): https://github.com/microsoft/vscode-cpptools/issues/8084

**Comment by isidorn** [comment] 2021-09-06 19:03
There are no action items on the vscode side. Thus closing this.

**Closed by isidorn** 2021-09-06 19:03 UTC
Labels: needs more info, debug

**Comment by mikebeaton** [comment] 2021-10-11 09:56
This is incorrect for me. My MacBook Pro does not have a Touchbar, and I still have the problem (I normally clicking the buttons in the debug toolbar using the mouse cursor).

**Comment by jonas-k** [comment] 2021-10-13 06:54
@isidorn, could we reopen this issue as I found a way to reproduce it now (see my comment above)?

**Comment by jonas-k** [comment] 2021-10-13 08:39
It turns out the error was on my side. I pressed the launch button instead of the launch and debug button. Thanks anyway.
