### ISSUE TITLE
Empty viewlet don't get sidebar focus indicator

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#88356] opened 2020-01-09 10:33 UTC
Empty explorer viewlet (no folder, hide all views). The proper white indicator doesn't show until I click in the empty viewlet:
![sidebar-indicator](https://user-images.githubusercontent.com/38270282/72059372-2c8a3f00-32d2-11ea-99b5-d7da74d20feb.gif)

Further context: https://github.com/microsoft/vscode/issues/86686

**Comment by sandy081** [comment] 2020-01-09 11:02
This is because there are no views to focus. Moving this to @misolori as nothing I can do here.

IMO this can be ignored as I don't think this is a practical scenario.

**Comment by misolori** [comment] 2020-01-21 17:22
@alexr00 do you have repro steps?

**Comment by alexr00** [comment] 2020-01-22 08:52
Open VS Code without a folder open
Open Explorer and hide all the views there
Open the Search viewlet
Reload
Open Explorer

I expect that the white indicator shows on the Explorer activity bar icon immediately, but instead I have to click in the empty explorer viewlet first.

**Comment by misolori** [comment] 2020-01-27 18:53
@alexr00 hmm...I'm not able to reproduce, but focus should always be made to the view when you click on the activity bar item. In your GIF, it appears that the explorer is missing the "empty view". Assigning to @isidorn to see if he knows more.

**Comment by isidorn** [comment] 2020-01-28 09:58
@alexr00 This is because you have all the views hidden and there is nothing to focus.
Just bring back the No Folder Open view via context menu and it should nicely work.
I can make this view not able to hide, however that does not make a lot of sense.

So the actual issue is that a View Container with no Views should focus itself and not try to pass focus to one of the containg view.
thus forwarding to @sbatten 
imho we can also not fix this

**Comment by isidorn** [comment] 2020-01-28 09:59
I will just go ahead and close as "will not fix". If @sbatten or @alexr00 are passionate feel free to reopen

**Closed by isidorn** 2020-01-28 09:59 UTC
