### ISSUE TITLE
Copy does not work with image in media-preview extension

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#171616] opened 2023-01-18 14:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.74.3 (on github.dev)
- OS Version: Linux, Gnome, Chrome

Steps to Reproduce:

1. Open an image in the media-preview extension
2. Right click on the image and select copy
3. Attempt to paste the image somewhere

Nothing happens. Also note that Cut and Paste make no sense here as menu items.

I assume that these are just the default context menu options from #54285 - perhaps these should be removed entirely from the preview extension and we could manually implement copy?

**Comment by vedantiitkgp** [comment] 2023-02-04 17:53
@VSCodeTriageBot assign this to me

**Comment by maski07** [comment] 2023-02-13 13:13
@a-stewart 
Are these the correct steps to reproduce the issue? 
I'm unable to verify it on my mac.
Can you provide more information?

<img width="950" alt="image" src="https://user-images.githubusercontent.com/40919162/218465806-7a38c6b8-4d68-4f23-9737-0fe08e8b7b60.png">

**Comment by Aperezpe** [comment] 2023-03-21 19:39
@mjbvz  I would like to wokr on this issue.

**Comment by StephenChips** [comment] 2023-04-01 15:23
@mjbvz I would like to try solving this issue.

**Comment by StephenChips** [comment] 2023-04-01 15:29
@a-stewart You right-click an image and select "copy", then you click a folder in VSCode's explorer and select "paste". The image should be pasted into that folder but it doesn't.

**Comment by balaji-sivasakthi** [comment] 2023-04-03 09:48
@StephenChips I would like to work on this issuse.

https://user-images.githubusercontent.com/65065614/229474677-e5d34f6f-1180-46ba-94d7-5b82d1458418.mp4

**Comment by StephenChips** [comment] 2023-04-03 13:31
> @StephenChips I would like to work on this issuse. @a-stewart here, I tried to copy and paste (Ctrl+v) it. But it doesn't work.

That is what I meant. The file isn't copied to the destination after you click paste.

**Comment by StephenChips** [comment] 2023-04-03 14:39
After a day of researching, I think I can explain why this issue happens.

Basically in the core webview module (see `src/vs/workbench/contrib/webview/browser/webview.contribution.ts`), three default context menu actions (cut, copy and paste) are added to the `WebviewContext` menu, which are accessible throught all webviews, and `image-previewer` happens to be one of them, so after you right-click anywhere in a image previewer, you will be able to see these three actions.

Take "copy" as an instance, after you clicks this actions, the editor will post an message to the image previewer, telling it to execute copying. If there is a correspondent listener for this perpose, the image will be copied, but unfortunately there isn't one.

This problem has existed for quite a bit of time. The original modification that cause this problem i here #65310, which is meant to allow users to copy selected text within an extension's README page. There is also a closed issue that describe such issue in #123301. Personally I think providing action *cut*, *copy* and *paste* for all webviews is a little bit hasty, since there are not universally required for each webview, and even some of them need, the subject to be copied may vary from different webviews, or even different places in a same webview.

I can solve it by disabling the default actions first (there is a option `preventDefaultContextMenuItems` to achieve this), then let image previewer to implement its own copy and cut functionality, but I think this is rather a quick and sloppy solution. There should be another better way to solve this issue.

**Comment by mjbvz** [comment] 2023-04-03 18:00
@StephenChips What about adding a `copy` handler [inside the image preview](https://github.com/microsoft/vscode/blob/2d63e7c1d0c8a260ab605c47f5361e40b6c900b2/extensions/media-preview/media/imagePreview.js#L1):

```
document.addEventListener('copy', () => {
    ...
})
```

**Closed** 2023-04-19 02:19 UTC
Labels: bug

**Comment by DonJayamanne** [comment] 2023-04-27 00:34
@mjbvz 
Here's what I tried
* VSC insiders without any extensions
* Open a folder with a *.png file
* Open the png file in vscode
* Right click and select `Copy`
* Paste into folder in vscode = does not work
* Paste into markdown cell in vscode = does not work

What am i doing wrong?

**Comment by mjbvz** [comment] 2023-04-27 16:25
Pasting image data into folders isn't supported by VS Code. Pasting into a notebook cells works fine for me though. To verify though you can also paste into an external image editor
