### ISSUE TITLE
Node debugger stalls when using util.inspect

### ISSUE THREAD

**Issue by benquarmby** [Microsoft/vscode#2753] opened 2016-02-06 02:19 UTC
Debugging a Node program that uses [util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options) hangs the underlying node process.

I stumbled across this while working on an app that depends on the Azure Storage SDK for Node (it uses util.inspect). I don't have a workaround for debugging right now, but the app works fine when running directly from the command line.

I've created a repro of the problem here:
https://gist.github.com/benquarmby/36f6c00947ad04509212

Steps:
- Create a script that invokes util.inspect on an object
- Place a breakpoint in the script *after* the call util.inspect
- Start debugging
- Observe that the breakpoint is not hit

Environment:
- VSCode 0.10.6
- Windows 10 x64
- Node 5.5 x64

**Comment by weinand** [comment] 2016-02-10 09:34
@benquarmby I could reproduce the same behaviour with node-inspector, so this is not a VS Code problem but a node problem, most likely a duplicate of https://github.com/nodejs/node/issues/4917.

It does not occur with node version < 4.2.6

**Closed by weinand** 2016-02-10 09:34 UTC
Labels: debug, upstream

**Comment by benquarmby** [comment] 2016-02-10 10:30
Right you are. I notice Node JS Tools for Visual Studio repros this bug also. Definitely a node problem and not VS Code specific.
