### ISSUE TITLE
VS Code start two times.

### ISSUE THREAD

**Issue by Remotion** [Microsoft/vscode#70079] opened 2019-03-08 17:10 UTC
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:

1. Double click Visual Studio Code icon on desktop.
Two instances of VS Code appears, some times silently losing all not saved files. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Funeoz** [comment] 2019-03-08 18:16
What happens when you click on "open" when you right-click the icon?

**Comment by mzji** [comment] 2019-03-09 03:22
Got the same issue. Click "open" on the context menu open two VS Code instances too.

**Comment by mzji** [comment] 2019-03-09 04:02
Looks like this is a duplicate of #70006

**Comment by Funeoz** [comment] 2019-03-09 10:06
Curious for me. It also happens when I don't save a project and then quit.

**Closed** 2019-03-11 07:45 UTC
Labels: new release
