### ISSUE TITLE
vertical/horizontal split window

### ISSUE THREAD

**Issue by Lallassu** [Microsoft/vscode#24998] opened 2017-04-19 07:19 UTC
It would be good if it was possible to split windows both horizontal and vertical at the same time. Right now it seems to only be possible to be one or the other for all window panes.

It would be great if it had support for same layout as for vim (:sp/:vsp). Hence, splitting one window pane horizontally and at the same time have two window panes horizontally divided.

**Comment by mjbvz** [comment] 2017-04-19 21:04
Thanks for request. This looks like a duplicate of #14909. Definitely on our radar

**Closed by mjbvz** 2017-04-19 21:04 UTC
Labels: duplicate, feature-request
