### ISSUE TITLE
Snippet completion of repeated tokens fails when first token autocompletes with a preceding character

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#11060] opened 2016-08-28 06:37 UTC
- VSCode Version: 1.4
- OS Version: Windows 10

Completing a snippet, where the `$1` token occurs more than once and where the first instance of the token is preceded by a character that triggers autocompletion in the editor, causes subsequent completions of the `$1` token to overwrite the preceding character with the preceding characters from the autocompletion.

![image](https://cloud.githubusercontent.com/assets/298883/18032075/edcc1a8e-6d3d-11e6-8205-79859bf17360.png)

![vscode-snippet-completion-bug](https://cloud.githubusercontent.com/assets/298883/18032063/7f365300-6d3d-11e6-9e03-228ccff321cc.gif)

**Steps to reproduce:**
1. Use the following snippet (or any snippet containing two or more instances of the `$1` token where the first token is preceded by an underscore:

``` json
{
    "prefix": "t1",
    "body": [
        "this._$1 = void 0;",
        "this.get('$1');"
    ]
}
```
1. Create a new file with the same language as the snippet. Enter the following into the editor:

``` js
this._foo = 1;
```
1. Use the snippet by typing `t1` into the editor on a subsequent line and pressing tab
2. Type `_foo` for the snippet completion and then press TAB to complete the snippet (which will also unwittingly trigger autocompletion)
3. The apostrophe preceding the second token is overwritten using the underscore from the autocompletion selection

**Workaround**

Pressing escape to cancel autocompletion before pressing tab to complete the snippet will stop autocompletion from ruining the snippet result.

**Comment by jrieken** [comment] 2016-08-29 07:54
Thanks. Nice find.

**Comment by ramya-rao-a** [comment] 2016-12-07 23:21
@jrieken Using the same repro steps as above, now when I hit Tab after entering foo, I get the below

````
this._foo = void 0;
this.get('foo_foo');
```

Am not sure what the expected behavior here is. Is it just that the apostrophe doesnt get swallowed by the underscore?

**Comment by jrieken** [comment] 2016-12-08 08:40
that's not good...

**Comment by jrieken** [comment] 2016-12-08 09:32
bummer... ![dec-08-2016 10-32-11](https://cloud.githubusercontent.com/assets/1794099/21004620/9fcd4cec-bd31-11e6-942e-e986179353dd.gif)

**Comment by jrieken** [comment] 2016-12-08 10:49
Actually, I was tricked by my own logic. The truth is that this isn't easy to get right. Completions are always computed based on the primary selection (the bold'ish cursor) and part of the computation is the completion provider saying how much it wants to overwrite left of it. In that sample `_f`. That string cannot be found left of the second cursor (it is `('`). Now as have two options: (1) ignore that suggestions because it cannot be applied to *all cursors* or (2) ignore the overwrite left property for secondary cursors when the selected text doesn't match.

**Comment by ramya-rao-a** [comment] 2016-12-08 19:36
I'd go with option 1. Suggestion while adding placeholder content in snippet: how much value does that add ?

BTW did this get closed by mistake? We should probably re-open it and move it to the next milestone

**Comment by jrieken** [comment] 2016-12-09 08:42
I closed this on purpose because I have implemented option 2 as I believe option 1 is less valuable.

**Closed** 2016-12-12 15:31 UTC
Labels: bug, snippets, suggest
