### ISSUE TITLE
markdown  The preview experience is poor!

### ISSUE THREAD

**Issue by saysmy** [microsoft/vscode#73560] opened 2019-05-10 02:14 UTC
Issue Type: <b>Feature Request</b>

Each time you open the markdown file, it will automatically close all the files opened on my right side, and then display the preview of md. This experience is extremely poor! Why do I have to force the file that is open on my right side to be closed? If the file on my right side is only temporarily saved, I still want to go back through ctrl+z. If you close it, I will not be able to retreat my code! I will also close all the files I have worked hard to open and cause me to find the code again!
Looking forward to improvement:
1. Do not force me to close my right file window, you can open a new tab
2. You can force a new third column or fourth column to split the column.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment] 2019-05-10 18:12
Duplicate of #54776 and #66132

**Closed by mjbvz** 2019-05-10 18:12 UTC
