### ISSUE TITLE
Git Discard All Changes fails with "ENAMETOOLONG"

### ISSUE THREAD

**Issue by kumarharsh** [microsoft/vscode#65693] opened 2018-12-26 14:29 UTC
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

1. Modify two thousand files in your working directory
2. Open the **Source Control** tab
3. Hover over the **Changes** sidebar group and click the **Discard All Changes** button.
4. VSCode throws a ENAMETOOLONG error.

Reported earlier at https://github.com/Microsoft/vscode/issues/23943, but the issue was closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kumarharsh** [comment] 2018-12-26 14:31
It's because vscode runs this command on clicking "Discard all changes":

```
git checkout -q -- file/path/1 file/path/2 file/path/3 file/path/4 file/path/5 file/path/6 ...
```

**Comment by kumarharsh** [comment] 2018-12-26 14:41
It seems like it's actually a shortcoming of git itself.
Using `git checkout -q -- .` can be a viable alternative, would you agree?

**Comment by o0rebelious0o** [comment] 2019-01-04 06:53
I have reproed this locally.  In my test repo, I can see that discarding 2001 modified files creates a command line which is 78949 characters long, but the windows limit is 32767, assuming node is calling CreateProcess under the covers, and based on the info provided here: https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553/.

The problem is, the UI for discard all changes, in commands.ts:cleanAll, is translating the cleanAll into a repository.ts:clean with a list of all of the modified files.  The repository itself doesn't know that this list of resources is all of the changes in the repository.

Furthermore, this issue doesn't affect only discard all changes.  I was able to select the top change, and scroll down then shift click to select a subset of all of the changes, then right click, and select discard to see the same ENAMETOOLONG error message.

Simply replacing `git checkout -q -- <files>` with `git checkout -q -- .` won't fix the real issue, which is that the git operations aren't sanity checking their length prior to attempting to spawn the git command.

I think the right fix would be to have either exec/exec2, or, _exec/spawn split any git commands which are too long into multiple commands.

**Comment by o0rebelious0o** [comment] 2019-01-04 19:38
But it won't fix the problem. As I mentioned, if I select a long subset of changes, not all, it still goes through the same code path and gives the same error.  If `git checkout -q --` gets called there, it will incorrectly revert all files, not just the ones selected.

**Comment by kumarharsh** [comment] 2019-01-05 03:47
That's correct... Perhaps some sort of batching needs to be implemented to handle these type of cases?

**Comment by Herohtar** [comment] 2019-05-13 19:21
The underlying issue is not specific to Discard All nor is it even specific to Discard in general. This affects any git command that has the potential of containing a long list of files -- if you select a large number of modified/added files and Stage/Unstage them, for example.

The problem is as @rcbevans stated: the command ends up being too long because it's just a concatenated list of files.

It looks like some commands (like `git reset`) support the `--stdin` flag which gets around the shell limits (see https://github.com/desktop/desktop/pull/2877), but it's not official and not every command allows it. Probably the best solution at the time is to check the length and break the command into multiple calls if it's too big. The SmartGit client does this, and it works well.

**Comment by slim-hmidi** [comment] 2019-07-31 08:19
I get the same issue. Is there any temporary solution to resolve that?

**Closed** 2019-08-06 15:53 UTC
Labels: bug, git, good first issue, help wanted

**Comment by kumarharsh** [comment] 2019-08-06 16:52
@joaomoreno is this fixed in a commit? or did you close it by mistake? or is there some other plan to tackle this?

**Comment by joaomoreno** [comment] 2019-08-07 07:37
@kumarharsh https://github.com/microsoft/vscode/pull/66095
