### ISSUE TITLE
Editor context menu wrong positon

### ISSUE THREAD

**Issue by CyberGuerro** [microsoft/vscode#123761] opened 2021-05-13 08:55 UTC
- VS Code Version: 1.56.1
- OS Version: Linux (Gentoo)

Steps to Reproduce:

1. open editor
2. right click inside of it
3. context menu is TOO CLOSE to the mouse pointer and automatically select the menu item.

Does this issue occur when all extensions are disabled?: Yes (ever)

Possible solution:
It would be enough to show the menu a more pixels far.

**Comment by IllusionMH** [comment] 2021-05-17 10:21
Looks like duplicate of #113175

**Closed** 2021-05-17 15:19 UTC
