### ISSUE TITLE
Menu: revisit spacing between menu items

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52925] opened 2018-06-26 10:35 UTC
Refs: #52854

I feel like we could have a bit more space between menu items compared to native menus:

![image](https://user-images.githubusercontent.com/900690/41906134-601467c4-793d-11e8-97dc-8d1cc245669f.png)

**Comment by sbatten** [comment] 2018-07-03 22:11
dupe of #52494

**Closed by sbatten** 2018-07-03 22:11 UTC
Labels: ux, workbench-menu
