### ISSUE TITLE
Markdown preview doesn't render when closing certain editor groups

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#173874] opened 2023-02-08 19:49 UTC
Repro:

Get in this state:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/2193314/217635940-fbd2b17f-4652-4ba7-babb-462cf0e62d6e.png">

Close the right editor group:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/2193314/217635993-3ad6dfd2-dc46-46ec-b4dd-5dafd30c12d4.png">

Version: 1.76.0-insider (user setup)
Commit: beb9ed3758624b918f918886bb904b0b62511c08
Date: 2023-02-08T12:47:14.528Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by mjbvz** [comment] 2023-02-28 22:17
Actually seems like a generic webview issue

**Comment by mjbvz** [comment] 2023-03-01 20:00
Fixed webview layout issue but now it seems like we also need a fix to the markdown extension

**Comment by mjbvz** [comment] 2023-03-01 20:05
Actually not a bug. If you have two editors `a.md` and `b.md` side but side with a preview below `a.md`, closing `b.md` switches focus to the preview tab. However the preview stays for the content of `b.md`

This is now a duplicate of #66132. 

To verify this issue:

1. Open two editors `a.md` and `b.md` side by side
2. Open a markdown preview below `a.md`
3. Close the entire `b.md` group and confirm that the preview still shows its contents

**Closed by mjbvz** 2023-03-01 20:05 UTC
Labels: bug, markdown, webview
