### ISSUE TITLE
Why is the entire vs code interface curved?

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode#233534] opened 2024-11-10 23:12 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.2
- OS Version: windows 11

Steps to Reproduce:

Why are there different padding here from different sides:
![Image](https://github.com/user-attachments/assets/44d9f56d-ffa0-4a97-8cc7-625609dd859a)

Why do I need this strip here? What role does she play?
![Image](https://github.com/user-attachments/assets/bf7d2359-868e-41cd-bd7d-cc972e53e130)

And why is the question on windows there is a vs code icon, but on Mac there is none. It could have been safely inserted into the Mac on the right, but you didn't do it, but you did this icon on Windows
![Image](https://github.com/user-attachments/assets/070d39f8-d580-4d01-85ee-044ee1f7c45b)
![Image](https://github.com/user-attachments/assets/2f21d794-301e-4cdc-ae8a-2b5ffa22a870)

**Comment by bpasero** [comment] 2024-11-15 05:39
Please report 1 problem per issue. Moving to @TylerLeonhardt for your report on unbalanced paddings in quick pick.

**Comment by TylerLeonhardt** [comment] 2024-11-15 06:06
the first issue (quick pick one) is a duplicate of https://github.com/microsoft/vscode/issues/233699

**Comment by TylerLeonhardt** [comment] 2024-11-15 06:14
moving to @sandy081 for your report on the keyboard shortcuts editor

**Comment by sandy081** [comment] 2024-11-15 07:49
> Why do I need this strip here? What role does she play?

It gives some padding between the side bar / auxilary bar  and the editor and make the editor look nicer with breathing space. Moving to @bpasero for the 3rd question about VS Code Icon.

**Comment by bpasero** [comment] 2024-11-15 08:04
We try to follow OS guidelines for how the custom title appears and Windows tends to have app icons there while macOS does not.

**Closed** 2024-11-15 08:04 UTC
Labels: *as-designed
