### ISSUE TITLE
No link definition found with markdown reference

### ISSUE THREAD

**Issue by Mister-Hope** [microsoft/vscode#163422] opened 2022-10-12 10:29 UTC
- VS Code Version: 1.72.1
- OS Version: Windows 11

Steps to Reproduce:

```md
...

- [vuepress-plugin-blog2][blog2]: Blog plugin for VuePress2

...

[blog2]: https://vuepress-theme-hope.github.io/v2/blog/
```

Getting:

```
No link definition found: 'vuepress-plugin-blog2' (link.no-such-reference)
```

I do think this is a incorrect warning,

**Comment by mjbvz** [comment] 2022-10-12 23:57
Duplicate of https://github.com/microsoft/vscode/issues/162691

**Closed by mjbvz** 2022-10-12 23:57 UTC
Labels: new release
