### ISSUE TITLE
Prevent extensions with bad performance from blocking critical extensions like VSCodeVim

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#93399] opened 2020-03-25 15:14 UTC
Sort of a repeat of #32763, though I'm not going to suggest running extensions in the main process.  Maybe now there's time to improve on this?

I ran into [this issue](https://github.com/alexdima/vscode-lcov/issues/26) with `vscode-lcov` tying up the extension host process and causing VSCodeVim to stop responding to keyboard input for several seconds.

I would be happy with any of the following solutions:
* Make all extensions run in their own processes
* Make all extensions run in a different Worker thread within the extension host process if possible
* Make it possible to request a dedicated process for specific extensions like VSCodeVim
* Automatically kill extensions that tie up the extension host for more than e.g. 250ms, and show an error message encouraging the user to report an issue to the extension's author telling them to do expensive work in a Worker thread.

**Comment by rebornix** [comment] 2020-04-17 21:44
/duplicate of https://github.com/microsoft/vscode/issues/75627

**Closed** 2020-04-17 21:45 UTC
Labels: *duplicate
