### ISSUE TITLE
TypeScript doesn't list document symbols

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#64804] opened 2018-12-11 14:11 UTC
Steps to reproduce

- clone https://github.com/Microsoft/lsif-typescript.git
- npm install
- open code
- open graph.ts
- trigger document symbols: observe the list is empty

<img width="814" alt="capture" src="https://user-images.githubusercontent.com/1931590/49805895-998d7700-fd56-11e8-8d99-fa884af61d39.png">

**Comment by dbaeumer** [comment] 2018-12-11 14:11
@mjbvz I am pretty sure that this used to work. Might be a regression that we need to fix.

**Comment by dbaeumer** [comment] 2018-12-11 14:15
If you open `lsif.ts` document symbols work. Even switch back to graph.ts works

**Comment by mjbvz** [comment] 2018-12-12 00:48
Duplicate of #64649 (same root cause)

Should be fixed in 1.31 builds

**Closed by mjbvz** 2018-12-12 00:48 UTC

**Comment by dbaeumer** [comment] 2018-12-12 10:10
@mjbvz do you mean 1.30.1 or 1.31 ? I have to say this is quite annoying if many customers get hit by this.
