### ISSUE TITLE
hover help is not available on attributes

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#16163] opened 2016-11-28 19:14 UTC
- VSCode Version: VSC Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open launch.json file 
2. Hover over the attributes and observe the result

**Comment by aeschli** [comment] 2016-11-29 07:44
duplicate of #16136

**Closed by aeschli** 2016-11-29 07:44 UTC
Labels: bug, json
