### ISSUE TITLE
JavaScript Files Loses Spaces on Save

### ISSUE THREAD

**Issue by jimpier** [Microsoft/vscode#24759] opened 2017-04-14 09:09 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|VisualStudioDarkTheme|Adrien|1.0.1|
|vscode-color|anseki|0.2.6|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|gitlens|eamodio|3.4.5|
|vscode-npm|fknop|3.3.0|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.15|
|vscode-github|KnisterPeter|0.12.1|
|code-beautifier|michelemelluso|1.7.2|
|motss-html-snippets|motss|0.2.3|
|mac-classic-theme|nkjoep|0.0.1|
|vscode-html-scss|P-de-Jong|0.0.42|
|vscode-css-peek|pranaygp|1.2.4|
|view-in-browser|qinjia|0.0.5|
|sass-indented|robinbentley|1.3.1|
|vscode-typings|typings|0.0.5|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|Material-theme|zhuangtongfa|2.4.16|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.open a .js file
2.write a function like this
function test(){（the cursor is here now）
}
2.press enter go to next line and press ctrl+s
then the cursor will go to the first column（will go to the fourth column is correct）

**Comment by mjbvz** [comment] 2017-04-14 20:25
My guess is that you have

```json
"files.trimTrailingWhitespace": true
```

enabled in your user or workspace settings. Can you confirm this?

If this is not the case, please try reproducing the issue with all extensions disabled by running `code --disabled-extensions` . This will let us know if one of the extensions is the root cause here

**Comment by mjbvz** [comment] 2017-04-20 22:46
Closing as  possibly caused by extension or setting

**Closed by mjbvz** 2017-04-20 22:46 UTC
Labels: javascript, needs more info
