### ISSUE TITLE
Screen cheese after closing the peek view

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#16348] opened 2016-12-01 22:35 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (be33bcdb2beb2d01c76ec8f830a70feaaa6721f5, 2016-12-01T09:41:08.588Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.8|
|theme-toothpaste|aalaap|0.0.1|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.2|
|tslint|eg2|0.6.7|
|vscode-npm-script|eg2|0.1.2|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|Ruby|rebornix|0.10.3|
|java|redhat|0.0.7|
|kustovscode|seanmcbreen|0.0.1|
|autoimport|steoates|1.2.2|
|gitblame|waderyan|1.3.0|
|vscode-open-in-github|ziyasal|1.2.2|

---

This is not reliably reproducible but I got it a couple of times using the following steps:

1. open a TS file
2. select a property and use 'Find All References' from the context menu
3. within the peek view make a change
4. close the peek view

![screen shot 2016-12-01 at 2 25 34 pm](https://cloud.githubusercontent.com/assets/4674940/20815585/550eccc0-b7d3-11e6-89b8-865ed38dc555.png)

**Comment by alexandrudima** [comment] 2016-12-02 16:10
@kieferrm I think this is a dup of #14107

* when scrolling with the mouse wheel we mark the last mouse wheel event target
* once marked, this dom node will be kept in the dom until scrolling in the opposite direction
* this is to support smooth scrolling, which gets broken if the initial mouse wheel target gets removed from the dom
* I think in this case, the mouse wheel (which can be triggered by two fingers on the trackpad) is very sensitive and if a dom node should be removed after such a "mouse wheel" event, we don't remove it thinking removing it would lead to janky scrolling.
* the tell-signs of the bug are:
  * it's always one line that appears in the viewport when it shouldn't
  * the line goes away when scrolling in the "opposite" vertical direction

@kieferrm Can you confirm it is #14107 ?

**Comment by jrieken** [comment] 2017-02-21 15:45
dupe of #14107

**Closed by jrieken** 2017-02-21 15:45 UTC
Labels: bug, editor
