### ISSUE TITLE
Text Not scrolling in multi-line edit select

### ISSUE THREAD

**Issue by bkercher** [microsoft/vscode#91288] opened 2020-02-24 16:08 UTC
Issue Type: <b>Bug</b>

1) Start with text file - say 100 lines long
2) Go to line 50
3) Use alt shift up or down arrow to select multiple lines - 2 or more
4) use up/down arrow to move mult-line selected region

Expected result
1) Page scrolls to keep multi-line select region in display area.
2) Multi-line select region is maintained when scrolling to ends of document

Actual result
1) No text scrolling occurs and multi-line cursor region disappears off the page. 
2) Multi-line select region exits when cursor reaches end of document and page scroll jumps to the location.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.10.0
vbscript-language-server-client|and|1.0.3
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|3.0.9
plsql|cas|0.0.5
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
tslint|eg2|1.0.44
vscode-firefox-debug|fir|2.6.1
code-runner|for|0.9.16
CppSnippets|har|0.0.14
beautify|Hoo|1.5.0
classic-asp|ili|0.0.4
classic-asp-html|jtj|0.1.2
docomment|k--|0.1.8
vbscript|kar|0.5.5
vscode-clangd|llv|0.0.20
vscode-JS-CSS-HTML-formatter|lon|0.2.3
VBScript|lug|0.0.2
add-to-globals|Min|1.0.2
vscode-clang|mit|0.2.3
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
csharp|ms-|1.21.12
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.1.0
vs-keybindings|ms-|0.2.0
html5-boilerplate|sid|1.0.3
vscode-hexdump|sle|1.7.2
vscode-terminal-here|Tyr|0.2.4
vs-asp-classic|wfe|0.0.4
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by alexdima** [comment] 2020-02-26 16:21
Duplicate of #6995

**Closed by alexdima** 2020-02-26 16:21 UTC
