### ISSUE TITLE
Nothing on Right Click - renderer1

### ISSUE THREAD

**Issue by Kai-Richardson** [microsoft/vscode#85730] opened 2019-11-27 22:36 UTC
Issue Type: <b>Bug</b>

Cannot right click on code to get context menu actions.
Tested on multiple projects/language types.

I'm using WSL2 & remoting in with it.

This error appears in Log (Window) ~1s after right click attempt:
```
[2019-11-27 14:31:38.033] [renderer1] [error] Cannot read property 'title' of undefined: TypeError: Cannot read property 'title' of undefined
    at _compareMenuItems (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1707:336)
    at Array.sort (<anonymous>)
    at e._build (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:144)
    at new e (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1705:658)
    at createMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1705:361)
    at e._getMenuActions (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1813:213)
    at e.showContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1813:77)
    at e._onContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1812:915)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:927
    at c.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:740)
    at s.n.onContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2141:461)
    at s.emitContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2021:595)
    at t.ViewController.emitContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1785:869)
    at g._onContextMenu (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2006:1006)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2005:257
    at HTMLDivElement.<anonymous> (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:554:273)
```

VS Code version: Code - Insiders 1.41.0-insider (615732feae7228502eab60919d67837f7a625e7c, 2019-11-27T05:37:07.864Z)
OS version: Windows_NT x64 10.0.19018
Remote OS version: Linux x64 4.19.79-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.79-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|14.50GB (13.02GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
bracket-pair-colorizer-2|Coe|0.0.28
byond-dm-language-support|gba|1.0.1
Kotlin|mat|1.7.0
remote-containers|ms-|0.86.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.41.0
vscode-remote-extensionpack|ms-|0.17.0
vscode-icons|vsc|9.6.0
jinja|who|0.0.8
project-manager|ale|10.9.1
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
c-cpp-compile-run|dan|1.0.5
vscode-markdownlint|Dav|0.32.0
git-extension-pack|don|0.1.3
githistory|don|0.4.6
python-extension-pack|don|1.6.0
gitlens|eam|10.2.0
whitespace-formatter|eet|0.1.0
vscode-npm-script|eg2|0.3.9
latex-workshop|Jam|8.4.2
quicktask|lky|3.5.5
MagicPython|mag|1.1.0
git-graph|mhu|1.19.1
python|ms-|2019.11.50794
cpptools|ms-|0.26.1
vsliveshare|ms-|1.0.1293
dm-langclient|pla|0.1.4
sass-indented|rob|1.5.1
bash-debug|rog|0.3.6
vscode-spotify|shy|3.1.0
vscode-make|tec|1.0.2
latex-utilities|tec|0.3.4
vscodeintellicode|Vis|1.2.0
vscode-arduino|vsc|0.2.28
vscode-wakatime|Wak|2.2.1
jinja|who|0.0.8
markdown-all-in-one|yzh|2.5.1
material-theme|zhu|3.1.2
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by gjsjohnmurray** [comment] 2019-11-27 22:52
/duplicate of #85671 which looks like it will be fixed in tomorrow's Insiders

**Closed** 2019-11-27 22:52 UTC
Labels: *duplicate
