### ISSUE TITLE
Snippets should have custom transforms

### ISSUE THREAD

**Issue by shobhitg** [Microsoft/vscode#35925] opened 2017-10-09 19:19 UTC
Snippets currently have a facility to transform input in predefined ways.

But those predefined ways are very limited.

* upcase
* downcase
* capitalize

What I would like to achieve is something more custom.

This is portion of a bigger snippet code that I am trying to work as smoothly as possible.

```
.ofType<GetLogicalSwitchesSearchAction>(GET_LOGICAL_SWITCHES_SEARCH_ACTION)
```

Right now I have to type the text twice. But if there is a way one could throw in custom logic, then I could simply type `GetLogicalSwitchesSearchAction` once and the 2nd part should intelligently fill up `GET_LOGICAL_SWITCHES_SEARCH_ACTION`.

Hence creating this issue to track this request for custom logic in snippets.

**Comment by jrieken** [comment] 2017-10-10 07:30
duplicate of #34683

**Closed by jrieken** 2017-10-10 07:30 UTC
