### ISSUE TITLE
OSX system services shortcuts not  recognized

### ISSUE THREAD

**Issue by unnamedcrewman** [Microsoft/vscode#1628] opened 2015-12-24 05:17 UTC
I'm really enjoying working with VSCode, and appreciate the work going on here.  One issue I'm having (OSX El Capitan) is that VSCode doesn't seem to recognize some of the system wide services keyboard shortcuts I've set up to work with text from any application.

I have some System Services that run scripts, which I activate via a mouse menu, and those work fine.  I have others that I activate via the keyboard. For example, I have a System Service to take selected text and use a shell script to append it to a special file.  I have a mouse menu item that invokes that service via the the keyboard shortcut I've defined:  Cmd-Shift-Alt-Ctrl-A.  This works just fine, but I cannot invoke the same service using the actual keys on the keyboard.

All the shortcuts I'm using have  Cmd-Shift-Alt-Ctrl as the modifiers, so I don't think there are any conflicts with existing keyboard shortcuts.  Other system wide keyboard shortcuts do work, so I'm not sure what the issue is with these particular, OSX System Services related ones.  Is it a problem with the modifiers, or is there some issue currently with OSX system services support?

**Comment by bpasero** [comment] 2015-12-24 08:56
@unnamedcrewman out of curiosity, does it work if you bind a simpler shortcut that is not yet taken by VS Code?

@alexandrudima fyi

**Comment by unnamedcrewman** [comment] 2015-12-24 15:47
Thanks for the quick response.

I rebound the shortcut to `ctrl+cmd+H` which is not listed, as far as I can tell, among the default keyboard shortcuts.  My "append selected text to file" script/Service works fine with these keys in Sublime Text, as well as text highlighted in the browser and so on.  However this key-binding still fails to work from VSCode.  I tried several other key binding combos that seemed unique, and all worked except in VSCode.

If it matters, the mouse shortcut I use is simply a [PopClip for Mac](http://pilotmoon.com/popclip/) plugin that runs the system service by name, rather than by invoking the keyboard shortcut.  The PopClip plugin works perfectly, which seems to suggest that the issue is not with the service itself interacting with VSCode, but rather something with the key-binding mechanism instead.

**Comment by alexandrudima** [comment] 2016-01-14 11:08
This is most likely caused by us keeping the input textarea empty. I can only imagine that this external tool works by finding the current focused UI element and extracting the selected text from it. So it is more likely that the shortcuts do work, its just that the external tool finds no selected text and there is no visible output in the file.

**Comment by alexandrudima** [comment] 2016-01-26 11:55
To investigate if a1bd50f63fd8185a13495ff3d4c67396109e4e71 fixes this too

**Comment by isidorn** [comment] 2016-01-28 16:48
This is a feature request which does not even appear to work in chrome and sublime text.
Moving it to the backlog

**Comment by unnamedcrewman** [comment] 2016-02-09 09:50
I can see how this is not really a bug, but I also think there is something here that is a bit more than a simple feature request because the conflict seems to be with some built in OSX functionality.

I wanted to clarify a couple of things in case there has been a bit of misunderstanding

@isidorn
I am using features built in to OSX: A system-wide keyboard shortcut (set through a built in OSX mechanism) that invokes an OSX System Service (append selected text to a specific file). The system-wide keyboard shortcut actually does invoke the system service correctly everywhere in the OS.  It works correctly on selected text in Chrome.  It works correctly on selected text in Sublime Text.  It works in every program I use, except for VSCode.  

@alexandrudima 
I'm not sure what you mean by "external tool", and so I apologize for any confusion.  As I mention above, the issue I'm having is with VSCode not recognizing  system-wide shortcuts, set through a built in OSX mechanism.  I've tried multiple key combos, and none of them work properly in VSCode, even thought they work everywhere else across the OS.  I don't think that the issue is the System Service itself not finding any selected text, because if I actually do use an external tool (instead of the system keyboard shortcut) to invoke the target service, it works perfectly---selected text in VSCode is recognized and appended to the desired file.  In other words, the actual system service can identify and can work with selected text in VSCode.  The problem is that VSCode does not appear to be registering the system-wide keyboard shortcut in OSX that normally invokes the service in every other program.

I have searched the VSCode key-binding file, and used several shortcuts that I could't find there ( e.g. `ctrl+cmd+H`), and none of them allow me to invoke the system service in VSCode, even though they work in every other program. It's possible that I'm still using a key-binding that conflicts with VSCode, but I don't know how else to confirm that.

I have upgraded to 0.10.8 and the issue still persists.

**Comment by julianlam** [comment] 2016-09-30 15:15
v1.5.3 and issue persists (as expected, since this discussion has stalled 😄 )

I wanted to bind some system services to global hotkeys, namely so I can switch between vscode, iterm, and chrome using Cmd-1/2/3. They work fine until I invoke the switch to vscode, and then I'm stuck since vscode seems to `e.preventDefault()` 😉

**Comment by XanderTigerclaw** [comment] 2017-02-03 05:15
I think the point is more that the standard macOS system-wide “Services” menu is completely missing (VSC v1.9.0); it’s meant to be under the application menu (i.e. Code → Services). Without it, no services are accessible from VSC and thus any custom (or default?) keyboard shortcuts won’t work.

Compare e.g. with TextMate 2, where the application menu subitems are:
- About TextMate
- Preferences…
- Check for Updates
- Services
- Hide TextMate
- Hide Others
- Show All
- Quit TextMate

instead for VSC, we have:
- About Visual Studio Code
- Check for Updates…
- Preferences
- Hide Visual Studio Code
- Hide Others
- Show All
- Quit Visual Studio Code

I don’t know how complex it is for VSC to support the system-wide Services menu…?

**Comment by 0x80** [comment] 2017-04-17 12:19
Bummer. I was trying to do the same as @julianlam . Would be nice to see this fixed!

**Comment by JeremyLoy** [comment] 2017-05-08 20:06
@XanderTigerclaw is headed down the correct path.  The VS application as a whole is not letting any OS Services shortcuts work (the menu doesn't even appear!) while VS has focus.

It is quite unfortunate for me, as I use ~5 different Services on a daily basis. The current workaround is to switch my focus to another application or the Desktop/Finder.  Not a huge problem, but a consistent and mild inconvenience.

**Comment by bpasero** [comment] 2017-05-09 10:26
Fixed via https://github.com/Microsoft/vscode/issues/26248

**Closed by bpasero** 2017-05-09 10:26 UTC
Labels: feature-request, mac
