### ISSUE TITLE
OSX - Rightclick on dock icon no longer shows workspaces

### ISSUE THREAD

**Issue by Nimja** [Microsoft/vscode#68502] opened 2019-02-12 08:52 UTC
Issue Type: <b>Bug</b>

I work with 2 workspaces in 2 windows. When VSCode opens, it only opens the last active one. Until very recently, a quick shortcut was to right-click the dock icon and select the other workspace. 

But workspaces no longer show up there?

**To Reproduce**
* Be on OSX
* Have 2 recent workspaces
* Open VSCode - last workspace opens.
* Right-click on Dock
    * **Expected**: Workspace can be selected and opens in new window.
    * **Currently**: Workspaces are not shown.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 17.7.0

**Comment by Nimja** [comment] 2019-02-12 09:59
No, that is not the same issue.

**Comment by bpasero** [comment] 2019-03-01 15:20
Duplicate of #57272

**Closed by bpasero** 2019-03-01 15:20 UTC
Labels: electron, upstream
