### ISSUE TITLE
Improve Install experience on Mac

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#2874] opened 2016-02-10 04:15 UTC
The thing that is missing for me most during the Mac install experience is moving VS Code.app to the Applications folder. Once it is there it is discoverable by spotlight and won't accidentally be deleted when cleaning out the download folder.

**Comment by Tyriar** [comment] 2016-02-10 17:06
Related https://github.com/Microsoft/vscode/issues/2859

**Comment by mjbvz** [comment] 2019-05-02 04:50
Duplicate of #5914

**Closed by mjbvz** 2019-05-02 04:50 UTC
Labels: feature-request, install-update, mac
