### ISSUE TITLE
hope change logo 

### ISSUE THREAD

**Issue by Tim-ls** [Microsoft/vscode#37516] opened 2017-11-02 12:27 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. this logo is so so so so ... ugly
2. Influence me to knock code

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-02 12:35
Duplicate of #35783
Have you already read [this](https://code.visualstudio.com/blogs/2017/10/24/theicon)?

**Comment by octref** [comment] 2017-11-02 18:35
https://code.visualstudio.com/blogs/2017/10/24/theicon

**Closed by octref** 2017-11-02 18:35 UTC

**Comment by sseen** [comment] 2017-11-09 01:05
Visual code team is good at writing, not icon design.
