### ISSUE TITLE
"Extension host terminated unexpectedly" on ftp syncronization

### ISSUE THREAD

**Issue by leoipiau** [microsoft/vscode#116727] opened 2021-02-15 20:35 UTC
Issue Type: <b>Bug</b>

Extension host crashes on ftp synchonization operations. I was using ftp-sync extensions,but I also tried to use ftp-simple and SFTP extensions and the problem remains.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.94GB free)|
|Process Argv|--crash-reporter-id 004152a9-0c04-401c-bfe2-0984b61ab430|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
vscode-eslint|dba|2.1.14
sf-pack|dub|1.1.0
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
node-module-intellisense|lei|1.5.0
ftp-sync|luk|0.3.9
dotenv|mik|1.0.1
vscode-docker|ms-|1.9.1
vscode-language-pack-pt-BR|MS-|1.53.2
remote-wsl|ms-|0.53.4
symfony-code-snippets|nad|0.2.4
symfony-super-console|nad|1.0.0
vscode-php-getters-setters|php|1.2.3
vscode-yaml|red|0.15.0
symfony-vscode|The|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by cmparrela** [comment] 2021-02-17 02:53
same problem here, I had to downgrade the version to keep using ftp sync

**Comment by cmparrela** [comment] 2021-02-17 03:02
Look that solution

https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-778684682

**Comment by alexdima** [comment] 2021-02-19 08:35
The root cause appears to be https://github.com/electron/electron/issues/27673

**Comment by deepak1556** [comment] 2021-02-20 22:51
The fix has been backported to Electron 11 https://github.com/electron/electron/pull/27766 and will be available in vscode next week.

**Comment by deepak1556** [comment] 2021-02-20 22:52
Merging to https://github.com/microsoft/vscode/issues/116260

**Closed by deepak1556** 2021-02-20 22:52 UTC
Labels: electron-11-update, extension-host, freeze-slow-crash-leak
