### ISSUE TITLE
VSCode Fails to Automatically Detect Git Path After Update to `1.94.0`

### ISSUE THREAD

**Issue by BowTiedRadone** [microsoft/vscode#230481] opened 2024-10-04 11:39 UTC
### Overview
After updating Visual Studio Code to version `1.94.0`, VS Code no longer automatically detects the Git executable path, even though Git is installed and accessible through the system terminal. This issue requires manual configuration of the Git path in VS Code settings, which was not necessary in previous versions

### Steps to Reproduce:
1. Update VS Code to version 1.94.0.
2. Ensure Git is installed and can be accessed via the terminal.
3. Open a project that is a Git repository in VS Code.
4. Navigate to the Source Control tab.
5. The Source Control tab will prompt to `Initialize repository` or `Publish to GitHub`

### Expected Behavior:
VS Code should automatically detect the Git path and allow interaction with the repository without manually configuring the `git.path` setting.

### Actual Behavior:
VS Code prompts to initialize a Git repository even when a valid .git folder is present. The issue is resolved only by manually setting the Git path via `Code > Settings > Settings > Git: Path`.

### Workaround:
Manually setting the Git path to the location of the Git executable (git.path) in the VS Code settings resolves the issue.

### Environment:
VS Code Version: 1.94.0
OS: macOS Sonoma 14.6.1
Git Version: 2.45.2 (Installed via Homebrew)

**Comment by lszomoru** [comment] 2024-10-04 12:14
@BowTiedRadone, after the update when VS Code started did you receive any notification that the "environment" could not be loaded? There is a known issues that results in the environment not getting loaded after an update. Could you try closing all instances of VS Code and launching it again?

**Comment by BowTiedRadone** [comment] 2024-10-04 13:26
Hi @lszomoru,
I don’t recall receiving any notification related to this issue. I tried restarting all instances of VS Code, but that didn’t resolve the problem. The only fix was manually specifying the Git path. Interestingly, the issue does not occur when using VS Code to SSH into an Ubuntu VM - Git is automatically detected there.

**Comment by lszomoru** [comment] 2024-10-04 16:01
@bpasero, are there any logs to troubleshoot loading the shell environment? Thanks!

**Comment by bpasero** [comment] 2024-10-04 19:25
Yeah just run with `--verbose` and check the main log for entries `resolveShellEnv`

**Comment by lszomoru** [comment] 2024-10-06 10:25
@BowTiedRadone, could you please try the flag from [this comment](https://github.com/microsoft/vscode/issues/230481#issuecomment-2394435189) and share the logs? Thanks!

**Comment by BowTiedRadone** [comment] 2024-10-07 10:05
@lszomoru please give me the full command and where to run it and I will run it.

**Comment by FrankRSC** [comment] 2024-10-23 18:54
Is there still no solution? When trying to activate an extension it does not work

**Comment by lszomoru** [comment] 2024-10-24 11:10
Could you please try the following:
1. Close all VS Code windows
2. From the terminal run `code --verbose`
3. After the VS Code launches go to the "View -> Output" menu
4. Use the dropdown to switch to the "Main" window and search for `resolveShellEnv`

**Comment by BowTiedRadone** [comment] 2024-10-24 14:48
Thank you. I did that, but I cannot find `resolveShellEnv` there:
```
2024-10-21 13:55:24.709 [info] update#setState idle
2024-10-21 13:55:30.352 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-21 13:55:54.712 [info] update#setState checking for updates
2024-10-21 13:55:57.515 [info] update#setState downloading
2024-10-21 13:56:24.625 [info] update#setState downloaded
2024-10-21 13:56:24.628 [info] update#setState ready
2024-10-21 13:57:46.999 [error] [UtilityProcessWorker]: terminated unexpectedly with code 7, signal: unknown
2024-10-21 13:57:47.055 [info] Extension host with pid 81175 exited with code: 0, signal: unknown.
2024-10-21 17:31:49.360 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-21 17:31:49.393 [info] Extension host with pid 81178 exited with code: 0, signal: unknown.
2024-10-22 11:41:27.730 [warning] No ptyHost heartbeat after 6 seconds
2024-10-22 11:57:41.748 [warning] No ptyHost heartbeat after 6 seconds
2024-10-23 00:47:11.959 [warning] No ptyHost heartbeat after 6 seconds
2024-10-23 05:20:39.942 [warning] No ptyHost heartbeat after 6 seconds
2024-10-23 09:14:18.915 [warning] No ptyHost heartbeat after 6 seconds
2024-10-23 17:12:10.703 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-23 17:12:10.734 [info] Extension host with pid 81174 exited with code: 0, signal: unknown.
2024-10-23 18:29:56.384 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-23 18:29:56.505 [info] Extension host with pid 81176 exited with code: 0, signal: unknown.
2024-10-24 10:00:06.281 [warning] No ptyHost heartbeat after 6 seconds
2024-10-24 10:17:27.129 [warning] No ptyHost heartbeat after 6 seconds
2024-10-24 17:42:19.094 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-24 17:42:19.325 [info] Extension host with pid 95731 exited with code: 0, signal: unknown.
2024-10-24 17:42:20.991 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-24 17:42:21.046 [info] Extension host with pid 69215 exited with code: 0, signal: unknown.
2024-10-24 17:42:22.809 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1829998016, signal: unknown
2024-10-24 17:42:22.881 [info] Extension host with pid 81177 exited with code: 0, signal: unknown.
2024-10-24 17:46:31.393 [info] Extension host with pid 11243 exited with code: 0, signal: unknown.
2024-10-24 17:46:31.399 [error] [UtilityProcessWorker]: terminated unexpectedly with code 64, signal: unknown
```

**Comment by lszomoru** [comment] 2024-10-24 18:16
@bpasero, any guidance on this would be appreciated. Thanks!

**Comment by bpasero** [comment] 2024-10-24 18:41
Well thats very likely not a `--verbose` log, compare with mine:

```
2024-10-24 20:40:22.497 [trace] [File Watcher (node.js)] Request to start watching: /Users/bpasero/Library/Application Support/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/Users/bpasero/Library/Application Support/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
2024-10-24 20:40:22.498 [debug] Starting VS Code
2024-10-24 20:40:22.498 [debug] from: /Applications/Visual Studio Code.app/Contents/Resources/app
...
```

**Comment by FrankRSC** [comment] 2024-10-24 20:02
> Could you please try the following:
> 
> 1. Close all VS Code windows
> 2. From the terminal run `code --verbose`
> 3. After the VS Code launches go to the "View -> Output" menu
> 4. Use the dropdown to switch to the "Main" window and search for `resolveShellEnv`

This helped me, I also couldn't find resolve ShellEnv but I was able to activate the extension and it worked

**Comment by omermizr** [comment] 2024-10-25 18:39
Same issue for me.
Started with `--verbose` and my log shows this a bunch of times:
```
[trace] resolveShellEnv(): skipped (VSCODE_CLI is set)

**Comment by bpasero** [comment] 2024-10-25 18:41
When you run VS Code from the command line, we do not resolve shell environment because it gets inherited from the command line.

**Comment by omermizr** [comment] 2024-10-25 18:52
Ok this is fixed for me!
My problem was specifically with MacOS and was caused by an update to XCode. The solution is to launch XCode and consent to the new T&Cs. More info here: https://stackoverflow.com/questions/25970043/git-and-xcode-why-do-i-have-to-agree-to-xcodes-tcs-to-use-git

While this problem is not with VSCode, it would be nice to propagate the CLI error to VSCode (instead of the vague "Failed to find git executable" error).

![Image](https://github.com/user-attachments/assets/5b8f8e7d-2660-4222-b7eb-dcf5b313daec)

**Comment by FrankRSC** [comment] 2024-10-31 00:53
I updated VSC and it failed again
use --verbose and look for resolveShellEnv
This is what I found

`[main 2024-10-31T00:47:38.035Z] resolveShellEnv(): skipped (Windows)`

**Comment by lszomoru** [comment] 2024-11-01 14:11
Adding @bpasero to confirm but it looks like on Windows we do not resolve the shell environment.

**Comment by bpasero** [comment] 2024-11-01 14:38
That is correct because on that OS the environment gets inherited from the OS. We only need to resolve the shell environment on POSIX.

**Closed** 2024-11-09 11:24 UTC
Labels: info-needed
