### ISSUE TITLE
[Accessibility] Add accessibility signal for progress status in notebooks

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#196396] opened 2023-10-24 13:48 UTC
Type: <b>Feature Request</b>

CC @meganrogge

I think progress status is used in many cases, but I encounter this when using Jupyter Notebook. If current cell execution takes a long time, sighted people may see some visual cues indicating its progress status. However, there is no non-visual indication for screen reader users. Please consider adding audio cues.

Also, please consider adding alert as an independent configuration for deaf-blind and braille users.

VS Code version: Code - Insiders 1.84.0-insider (7dff07893ac160244db210e574eccc05f1cba2cb, 2023-10-24T05:33:54.929Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by AFre100** [comment] 2023-10-24 16:07
@jooyoungseo thank you! Pretty sure this will be implemented, but I had a sidebar question: I’m always updating my audit of assistive audio in the wild—do you have any favorite progress audio cues you might name?

**Comment by meganrogge** [comment] 2023-10-26 17:24
Would also apply to settings search progress.

We have the in progress chat response cue already, should that be used?

**Comment by AFre100** [comment] 2023-10-30 16:00
@meganrogge would it make sense to implement the same system as Copilot chat progress -- i.e. only triggering after x seconds, looping every y seconds, leaving/returning to window, etc?

**Comment by jooyoungseo** [comment] 2023-10-30 16:16
If it is possible to estimate the progress ratio, I suggest an incremental tone just like [Gauge Sounds](https://dlee.org/jgauge/old/gauge_sounds.htm). Otherwise, using audio cue the same as Copilot Chat would be fine.

**Comment by AFre100** [comment] 2023-10-30 16:28
@jooyoungseo thanks! Love this idea. However, I'd really want to hear it in context to confirm that I'm understanding it right. I've searched w/out luck -- do you know how I might get a screen recording of it?

**Comment by AFre100** [comment] 2023-11-03 18:27
@jooyoungseo Just wanted to check in about this -- you don't have the gauge sounds implemented, do you? If so, might you send me a screen recording of it for more context, or do you have any leads on how I might get a hold of some footage?

**Comment by AFre100** [comment] 2023-11-15 15:56
@meganrogge @jooyoungseo  Having footage of the incremental tone system, like [Gauge Sounds](https://dlee.org/jgauge/old/gauge_sounds.htm) would still be helpful if Jooyoung, you have a way to make that happen. In the meantime though, I'm curious what you all think (?):

If scenarios where progress takes greater than x seconds create a significant enough pain point among screenreader users, I do think having a system like this would be greatly beneficial (like a realtime progress bar via visual feedback). 

From my understanding, there would need to be data that quantifies estimated percentage of completion, which informs the real time audio system as it increments. Flagging that we'd also need to investigate what that wait time threshold needs to be, in oder to justify the engineering needed for incrementing  — e.g. maybe it's >7, 12, 18 sec? 

If the issue isn't significant enough, then yes, we could use the chat progress audio loop system (or something similar).

**Comment by AFre100** [comment] 2024-01-05 22:15
> status is used in many cases, but I encounter this when using Jupyter Notebook. If current cell execution takes a long time, sighted people may see some visual cues indicating its progress status

@meganrogge  Trying to pick this conversation back up, since the speech to text ticket might be relevant. I have been working on this. Can you please send me screen grab videos of both the Settings search progress and Jupyter Notebook current cell execution examples? Thanks!

**Comment by amunger** [comment] 2024-01-05 23:38
Are you just trying to see what cell execution looks like? Here is an example.
We don't have a way to know how long the execution is going to take since it's executing arbitrary code, it could be hours.

![Recording 2024-01-05 at 15 34 03](https://github.com/microsoft/vscode/assets/2019016/6e86268d-f3d2-4789-b582-4fbe8fa8daf7)

I'm not sure about settings search - if I understand what this is referring to, I've never seen the search take longer than a few hundred milliseconds.

**Comment by AFre100** [comment] 2024-01-08 17:26
@amunger Thank you!

**Comment by AFre100** [comment] 2024-01-08 17:56
@amunger @meganrogge @jooyoungseo Just wanted to see if we can come to a consensus. What kind of wait times exist for these use cases? Is it usually max 2-3 seconds, does it ever last >5, 12, 18 sec? 

If we aren't using an incremental tone system, do we need an additional cue to indicate completion in cases where there are multiple progress statuses?

Microsoft team, what do we think about leveraging progress ratio calculation for an incremental tone system?

**Comment by meganrogge** [comment] 2024-01-08 18:07
Question, are we considering replacing the copilot in progress cue with this one? If so, it can last a long time - 30 seconds or more

**Comment by meganrogge** [comment] 2024-01-08 19:24
I believe I have answered your questions on the other issue @Afre100. 

Are there downsides to using an incremental tone system?

**Comment by AFre100** [comment] 2024-01-08 22:01
@meganrogge  thanks! Re downsides to incremental tones…Highly informative real time feedback is great, but it could be quite disruptive if triggered accidentally (more so than the CoPilot progress loop, as there is much more sound happening/beeping over time than that system). This doesn’t mean the appropriate guardrails can’t be placed to mitigate that, or that it couldn’t be justified. I’m going to speak to partners, team, contacts to research more to give you a full cost benefit analysis. 

As part of this research, It’s important to get footage/screen grabs of any incremental tone system in action, like [Gauge Sounds](https://dlee.org/jgauge/old/gauge_sounds.htm) which Jooyoung suggested. I haven't been able to find any w/in IDE's or similar and haven't heard back from him.  

If JooYoung is able to work with us on any of this, I could definitely use a meeting with you all to help clarify/align on the best way to solve for all of these progress indicator use cases. 

Also, would be great to know if people would want to end up switching windows/contexts while waiting for progress time on this interaction as well, if anyone knows

**Comment by AFre100** [comment] 2024-01-12 17:24
@meganrogge Where did the current version finally land with VSC CoPilot chat sounds, in terms of whether they're on by default when screen reader detected?

**Comment by meganrogge** [comment] 2024-01-16 16:30
`chatResponsePending` is on by default for screen reader users. The other two are opt in.

**Comment by AFre100** [comment] 2024-01-18 19:08
@meganrogge @jooyoungseo  et all,

Looping in @codeofdusk (Engineer in Accessibility Insights) who flagged a few things: 

1) Progress bars w/visual feedback for percentage often provide incremental tones through NVDA by default. Is it confirmed that this isn't available here, and is it available in any other instances of Progress Status? 

2) Is there any reason we can’t mark up those progress bars with the appropriate UIA or ARIA attributes?

(adding @rperez030 for awareness/unsilo-ing convos)

**Comment by meganrogge** [comment] 2024-01-18 19:37
I don't think our progress bars work with percentage and believe ours are custom vs native.

**Comment by AFre100** [comment] 2024-01-18 20:13
If it's a thing, how would ratio-based ARIA alerts play into this, if at all...is the idea that an incremental tone system would be less chaos than ratio-based ARIA alerts? (Because, if a screen reader voice is reading another window simultaneously, incrementing tones are easier to distinguish than the ARIA's 2nd voice)

**Comment by rperez030** [comment] 2024-01-18 20:29
@codeofdusk Is likely referring to aria progress bar https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role. A working example of this is present in devbox.microsoft.com where there is a loading status that uses this aria widget.  NVDA can be configured to either speak the status as percentage or play an incremental tone. Unfortunately, I don't believe there is complete support for this patter in JAWS, although I haven't tested that recently. In my opinion, this would only make sense if we can accurately estimate the completion time, and if it is long enough to matter. If we're thinking of communicating progress through audio cues, my first thought would be to use the same progress loop that is already in place for copilot chat, especially if there is no estimate.

**Comment by AFre100** [comment] 2024-01-18 21:36
That makes sense! What i'm stuck on is, it's unclear to me how much of a premium SR users put on incremental tone (indicating ratio/wait time, etc) over a progress loop (w/no ratio/wait time). 

Intuitively, the incremental system seems significantly better, but as I’m not an SR user, I’m seeking to learn and build consensus.

From a design perspective, if it’s beneficial enough to design/implement an incremental system, I believe we can address the potential disorientation for SR users who are familiar with the CoPilot Chat loop. For instance, we could develop an incremental system that builds upon the existing sound of the progress loop, modulating it to create a more robust, dynamic, and incremental version of what users are accustomed to.

(I’m curious about how many users are even aware of the CoPilot Chat loop, especially if our decisions depend on this.)

Penny for anyone's thoughts :)

**Comment by rperez030** [comment] 2024-01-18 23:08
premium SR users???

As a screen reader user myself, I would tell you that I like it, but don't consider it that important. I'm sure there are others that do, and that's why we have this feature request. There are also screen reader users that rely on percentage rather than tones for accurate progress. That's why it is a configurable setting in NVDA. Different people process information in different ways. 

Answering the question or whether it is worth investing in an incremental tones system would probably require a survey. For sure it would be a convenient feature for those who favor that type of feedback.

Regarding the copilot loop, if we are talking about screen reader users, I believe it is on by default when the screen reader mode is active, so anyone who uses a screen reader and uses the existing copilot flow is familiar with it.

**Comment by AFre100** [comment] 2024-01-19 21:34
@rperez030 To clarify, by "how much of a premium SR users put..." I'm referring to how much value SR users assign to  incremental tone (indicating ratio/wait time, etc) vs progress loop (w/no ratio/wait time). Sorry if that was unclear. You've actually answered that though in your awesome response already -- thank you!

**Comment by rperez030** [comment] 2024-01-19 21:37
Thank you! I'm glad because I wasn't sure whether I was helping you or confusing you even more.

**Comment by AFre100** [comment] 2024-01-24 16:43
@codeofdusk @rperez030 Do either of you know where I can hear/see recording/screengrabs of incremental tone in action? (I have access to the instructions/files for Gauge Sounds's release, but I'm trying to find examples of it, in action.). Thanks!

**Comment by AFre100** [comment] 2024-01-24 16:59
@amunger @meganrogge From an engineering perspective, is it known whether an incremental tone system, designed for the use cases mentioned here, could be repurposed and applied to other progress status situations?

**Comment by codeofdusk** [comment] 2024-01-24 17:04
> Do either of you know where I can hear/see recording/screengrabs of incremental tone in action?

Sure:
1. Install [NVDA](https://nvaccess.org).
2. With NVDA running, go to [this page](https://n6.io/progress_topco.html).

**Comment by AFre100** [comment] 2024-01-24 20:52
Huge thank you, @codeofdusk, for whipping that demo up for us! How do screen reader users (NVDA or other) using the progress bar "Beep" feature to perceive closeness to completion, given that there isn't a reference point for how high of a pitch "100% complete" sounds at the beginning of the interaction? 

If there's no reference, wouldn't that only offer a vague sense of closeness to completion, at best?  Maybe it's the kind of thing where power users have internalized a ballpark pitch range, or remind themselves of the range by auditioning the lowest/highest pitch in a menu, or just replacing it w/their own familiar sounds...

If this is an issue, I wonder if there's a way to communicate what the "100% complete" pitch would sound like at the beginning to denote pitch range? (E.g. a quick playback of lowest pitch followed by highest pitch at progress bar's start, or accessed via a menu.)

**Comment by jooyoungseo** [comment] 2024-01-24 21:22
For accurate value, screen reader users can employ speech alert along with the audio cues if they would like.

**Comment by AFre100** [comment] 2024-01-24 21:31
@jooyoungseo the repeated Current-to-reference playback was exactly what I imagined when I got looped into this! Do you think that'd be self explanatory enough to be clear, sans extra tutorial/explainers? 

If we think that'd end up feeling unnecessarily fussy, solving a non-problem w/yet more sound and cacophony, I'd love to know people's thoughts on that and act accordingly. 

But on paper, it a) sounds like it could provide more of a sense of completion ratio and b) could be designed to be way less abrasive-sounding than the existing incremental beep sounds I've heard, which might help mitigate the cacophony concern

**Comment by jooyoungseo** [comment] 2024-01-24 21:45
@AFre100 I think it's a matter of personal preference - some people will simply want to hear the current progressbar tone, while others will want to hear it alongside the reference tone to get a more detailed progression, and I'm fine with both. If you play the reference tone after the current tone, I think it's self-explanatory enough that screen reader users will quickly adapt and understand it without any training.

**Comment by codeofdusk** [comment] 2024-01-26 05:42
> How do screen reader users (NVDA or other) using the progress bar "Beep" feature to perceive closeness to completion, given that there isn't a reference point for how high of a pitch "100% complete" sounds at the beginning of the interaction?

I'm probably the wrong person to ask (I have [absolute pitch](https://en.wikipedia.org/wiki/Absolute_pitch) and have used NVDA for years) but I think people would develop a vague sense of the scale after using it for a while?

**Comment by codeofdusk** [comment] 2024-01-26 05:45
> I think it's a matter of personal preference

Agree with this – once I internalize the scale (either by using it a couple of times or through hearing the reference tone in isolation) I'd probably turn it off.

**Comment by meganrogge** [comment] 2024-03-27 19:12
@AFre100 what is your timeline for this?

**Comment by AFre100** [comment] 2024-03-28 16:54
@meganrogge checking in with a few parties -- will give you a detailed update by tomorrow!

**Comment by meganrogge** [comment] 2024-03-29 19:32
@rebornix and I discussed this with @jooyoungseo and Venkatesh today. 

We decided that we will likely:
- loop the progress sound while a single cell runs
- loop the progress until all cells have completed when run all cells is invoked

**Comment by AFre100** [comment] 2024-03-29 20:45
@meganrogge Nice, that makes sense! 

In other news, this morning, I sent out this [survey](https://forms.office.com/r/XfeQbP64zJ) about preference for incremental tone vs progress loop to program-l, and an internal Msft list. So far there are 8 responses. We could get another 20-30 responses by Tuesday (hard to tell). 

> 3 people strongly prefer an incremental tone system
> 3 people somewhat prefer an incremental tone system
> 1 person strongly prefers a progress loop
> 1 person has no preference

Do we want to definitely commit to a progress loop still, or shall we try to get more data about incremental vs loop?

**Comment by AFre100** [comment] 2024-03-29 21:28
@meganrogge If we're going with a progress sound loop, we're updating the existing Copilot Chat progress loop sound in order to be more globally usable, and improve upon some feedback (but still appropriate enough for the original interaction where it shouldn't cause any friction). So we can use this, as previously discussed.

We can deliver the progress loop update one month upon confirmation on whether we're going w/this direction (?).

Or, we can deliver the sounds for the incremental system 1-2 months upon confirmation. I suggest both engineering/design deciding a specific timeline together after one meeting because I think it could take some real time discussion sussing out what's possible in terms of real time audio processing in the code, (there could be some lightweight ways to do that are more efficient), and other variables. This could end up being more like 1 month depending on what we want/decide.

Thoughts?

**Comment by AFre100** [comment] 2024-04-01 15:20
Just checked out the survey again, at this time -- 7 prefer incremental (comprised of 4 strongly, 3 somewhat) vs 3 somewhat prefer progress loop sound, 1 has no pref. There are 3 "other" responses which prefer neither and want native, not custom progress bars

**Comment by meganrogge** [comment] 2024-04-01 15:22
@AFre100 I thought we agreed we want a different sound for chat response pending?

@jooyoungseo and @rperez030 do you have thoughts on reusing this sound vs having another? I'm worried it'll be confusing to reuse here.

**Comment by rperez030** [comment] 2024-04-01 15:57
> @jooyoungseo and @rperez030 do you have thoughts on reusing this sound vs having another? I'm worried it'll be confusing to reuse here.

I would strongly favor reusing the existing progress sound that we have become familiar with.

**Comment by meganrogge** [comment] 2024-04-01 16:22
Ok great, then I think we can close this when @amunger has added this for running notebook cells.

**Comment by AFre100** [comment] 2024-04-01 17:55
@meganrogge  heads up -- if progress loop is the consensus, we're most likely updating the existing Copilot Chat progress loop sound (which would be used here too). That's being done in order to improve upon some feedback. I expect it to be close enough to the original sound where it shouldn't cause any friction for users who depend on it. 

What's the next audio file delivery deadline for sound to be: 

a) implemented for any non-copilot chat use of progress status loop (notebook cells, settings search, etc)?

b) swapped into existing copilot chat usage

**Comment by meganrogge** [comment] 2024-04-01 18:02
Sounds good @AFre100. If we want this in by April, then April 17th

**Comment by AFre100** [comment] 2024-04-01 18:12
@meganrogge  thanks! And if it needed until the following release, that would be roughly one month later, a mid-May deadline, correct?

**Comment by rperez030** [comment] 2024-04-01 18:13
> @meganrogge heads up -- if progress loop is the consensus, we're most likely updating the existing Copilot Chat progress loop sound (which would be used here too).

curious how you will determine the ETA for copilot generation so that the progress sound can reflect reality.

**Comment by meganrogge** [comment] 2024-04-01 18:23
We cannot ATM determine the ETA, thus I don't think we should go with an incremental tone. Rather, we should play the sound every few seconds to indicate something is still happening.

**Comment by meganrogge** [comment] 2024-04-04 14:55
Another use case is in the scm view, when changes are getting committed or pushed, there's a progress bar. We should play the cue for this to indicate the non-visual state.


https://github.com/microsoft/vscode/assets/29464607/a6426eeb-2527-46bb-adf0-76d60ec5b542

**Comment by rperez030** [comment] 2024-04-05 14:59
> Another use case is in the scm view, when changes are getting committed or pushed, there's a progress bar. We should play the cue for this to indicate the non-visual state.
> 
>  Screen.Recording.2024-04-04.at.7.53.21.AM.mov

if the proper markup is used, screen readers such as NVDA that support the progress bar pattern can communicate that using their standard mechanism. I don't oppose providing a vS Code signal if we believe it to be valuable, but I would prioritize supporting established accessibility practices first whenever possible.

**Comment by meganrogge** [comment] 2024-04-05 15:14
That's a great point @rperez030. 

Does VoiceOver have a similar concept @rperez030 ? 

Is it the ARIA: progressbar role ?

**Comment by meganrogge** [comment] 2024-04-05 15:16
One concern I have with playing this audio cue in the SCM, chat response view, settings UI, etc is these could happen simultaneously, which would be very disruptive and confusing. 

The alternative would be to cancel one that's playing when focus is moved from that area, but I worry that is also a bad solution. 

Perhaps we can do as @rperez030 suggests for the cases that have an actual progress bar rendered (SCM, settings search UI, etc.) instead.

**Comment by rperez030** [comment] 2024-04-05 16:16
> That's a great point @rperez030.
> 
> Does VoiceOver have a similar concept @rperez030 ?
> 
> Is it the ARIA: progressbar role ?

Yes to all. I don't have Chrome install in this machine so cannot test chromium / voiceover support, but there is a working example to test here: https://github.com/microsoft/vscode/issues/196396#issuecomment-1908559313

**Comment by meganrogge** [comment] 2024-04-05 16:31
@amunger, unassigning myself as this issue is now strictly about notebooks adopting `chatResponsePending`. We should probably rename that and migrate the setting. LMK if you need help with that. 

Creating a separate issue about progress status in places with the progress bar, which we will add the role for as @rperez030 has suggested.

**Comment by AFre100** [comment] 2024-04-12 21:59
@meganrogge @amunger There's still the possibility that both notebook cell progress and chat response pending will take place, right? If, so, what did you all have in mind — keeping only one at a time via a focus shift/context switching? 

> One concern I have with playing this audio cue in the SCM, chat response view, settings UI, etc is these could happen simultaneously, which would be very disruptive and confusing.
> 
> The alternative would be to cancel one that's playing when focus is moved from that area, but I worry that is also a bad solution.
> 
> Perhaps we can do as @rperez030 suggests for the cases that have an actual progress bar rendered (SCM, settings search UI, etc.) instead, using this sound only for the cases that do not - notebook cell progress, chat response pending, etc.

**Comment by meganrogge** [comment] 2024-04-12 22:15
That's unlikely to happen. But yeah, we'll probably cancel based on focus

**Comment by AFre100** [comment] 2024-04-12 23:20
@meganrogge @amunger Feel free to use the existing chatResponsePending progress sound if we're antsy for notebooks to have a progress sound for April. Would be nice to start with the updated sound in this new use case but it's not worth blocking users from its use. Otherwise, I expect to have the updated progress sound for May (as discussed above), which would be used wherever chatResponsePending would be used.  (I'm OOF 4/17-4/24 just fyi.)

**Closed** 2024-04-18 14:28 UTC
Labels: feature-request, accessibility, notebook-accessibility, accessibility-signal

**Comment by venkateshpotluri** [comment] 2024-04-23 18:26
i've been taking advantage of these audio cues when running long-running operations in notebooks in the latest insider build, thank you for implementing this! I wanted to make a few suggestions based on my observations to improve the experience.
- determinant Vs. indeterminant progress bars could use different audio cues. I observe that VSCode plays the chat response pending sound for any operation that takes above a certain time. It may be useful to have a different sound as suggested by @jooyoungseo  that conveys the actual progress for long operations that surface this information (e.g. operations using the TQDM progress bars), with the chat response pending sound reserved for operations with indeterminant progress.
- option to set smart repeat frequency based on desired verbosity for determinant progress bars. The current experience results in an audio cue being played every few seconds irrespective of the duration of the operation. This could result in noisy output for long-running operations. For example, hearing an alert every 3 seconds for an operation that is expected to take a few hours may not be desirable. updates with lesser verbosity, combined with VSCode's ability to play these cues in the background could enable an amazing multi-tasking developer experience. TQDM progress bars provide the following information to screen readers which makes me think that smart repeat frequency may be possible: " 57%|█████▊    | 115/200 [1:55:47<1:25:38, 60.46s/it]"
- Option to disable audio cues when VSCode is out of focus. This may be less necessary if the alert frequency can be adjusted based on operation time for tasks that provide information for the runtime to be estimated as suggested in my previous point but may still be useful for long-running tasks where runtime cannot be estimated.
- potentially confusing reasons for progress. I do not have a suggestion yet on how to address this, but I notice that VSCode plays a few progress sounds when I wake my computer up even if there is no running operation. I work by connecting to a computer via remote-ssh so I am not sure if this sound is a result of my local IDE re-connecting to VSCode Server on the remote machine. Being able to identify what a progress bar corresponds to could be helpful.

**Comment by AFre100** [comment] 2024-04-24 23:20
@venkateshpotluri thanks! Checking this out when I return tomorrow. Stay tuned
