### ISSUE TITLE
Problem entries loops 

### ISSUE THREAD

**Issue by ckams** [Microsoft/vscode#56317] opened 2018-08-14 08:14 UTC
- VSCode Version: 1.26.0
- OS Version: Debian x64

Steps to Reproduce:

1. Start a project with multiples errors and warnings 
2. wait, and see:
  - The display of errors loops for a time—the number grows up to the maximum of errors and the count restarts from the beginning…
  - Problems hangs with the maximum number of errors, but the display is incomplete—not all errors appear—–and not update anymore

This issue does not occur when C# for Visual Studio Code (powered by OmniSharp) is disabled.

**Comment by sandy081** [comment] 2018-08-14 08:18
Can you please provide a video (gif) of the issue you are seeing?

**Comment by ckams** [comment] 2018-08-14 09:15
![vscode_1 26_2018-08-14 11-10](https://user-images.githubusercontent.com/32911942/44083019-6dbd38e8-9fa2-11e8-8221-9ff2b6652dda.gif)

**Comment by Domvel** [comment] 2018-08-14 14:18
Same here. The first line ist a non related (to a file) error. An not clickable. And sometime no line is clickable. Since 1.26. there is a bug. 

![image](https://user-images.githubusercontent.com/35452565/44097281-add21422-9fdd-11e8-8b0a-9504265bcc6b.png)

**Comment by Domvel** [comment] 2018-08-14 14:47
I tested the same on the version `1.25.1`. It's correct. See:
![image](https://user-images.githubusercontent.com/35452565/44098887-a4a764b6-9fe1-11e8-85ec-a5f955d7bfe6.png)

It's a bug in `1.26.0`

**Comment by FranklinWhale** [comment] 2018-08-14 15:31
I am experiencing the same `1.26.0` and confirm that the Problem Panel works normally when C# for Visual Studio Code (powered by OmniSharp) is disabled.
![looping](https://user-images.githubusercontent.com/8416067/44101285-aa31cede-a019-11e8-81a1-a8362462aca3.gif)

**Comment by Domvel** [comment] 2018-08-14 15:36
I recommand to use version `1.25.1` or another, but not `1.26.0` until this bug is fixed. I have no idea how to fix it.

**Comment by dchw** [comment] 2018-08-14 18:05
Yep, same issue here.

I am noticing that it only happens when the tab is focused, though If I introduce errors in my code while it is not focused, the number changes appropriately, and stays constant. I guess its a workaround, but not much of one.

So it must be something about the problems being focused that is triggering the error?

**Comment by GlenCFL** [comment] 2018-08-14 19:08
Callbacks provided to `vscode.workspace.onDidCloseTextDocument` are being invoked constantly, possibly erroneously. This causes Omnisharp C# to remove diagnostic errors over a short time span until it eventually finishes the project analysis, resets the diagnostics, and repeats.

With the Omnisharp C# extension:

- clone the repository (https://github.com/OmniSharp/omnisharp-vscode.git)
- install the NPM dependencies
- place a breakpoint in the file `src/features/diagnosticsProvider.ts` within the `_onDocumentRemove` function
- start a debug session for the extension
- open a directory containing a C# project (.csproj/.sln), open one of the C# files within a tab, and let the dependencies download

For me with VSCode 1.26.0, this breakpoint will constantly trigger, which C# isn't really programmed to deal with.

**Comment by demisx** [comment] 2018-08-15 00:45
Same here. After upgrading to 1.26.0 I see some bogus errors that have nothing to do with the code.

**Comment by angi-** [comment] 2018-08-15 05:35
I’m experiencing the exact same issue as @FranklinWhale with C#

**Comment by rvanmaanen** [comment] 2018-08-15 09:36
Same issue here

**Comment by sandy081** [comment] 2018-08-15 15:55
May I know if any of you were using quick fix from the problems panel while this issue has happened?

**Comment by sandy081** [comment] 2018-08-15 15:55
Also it would be great, if any of you can provide steps to reproduce this.

**Comment by FranklinWhale** [comment] 2018-08-15 16:08
Steps to reproduce:

1. In VS Code, install the C# extension
2. Create a folder
3. In the folder, run `dotnet new console`
4. Open the folder with VS Code
5. Open the Problems Panel
6. In workspace settings, add `"csharp.suppressHiddenDiagnostics": false`
7. In `Program.cs`, add `using System.Collections.Generic;`

**Comment by Domvel** [comment] 2018-08-15 16:15
In my case there are no steps. 😄 Just load a project (e.g. Ionic / Angular) and have one or more linter or syntax errors. Just have a error and look to the problems panel. 

<details>
 <summary>Click here to few my settings</summary>
```json
{
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.lineNumbers": "on",
  "editor.autoClosingBrackets": true,
  "editor.selectionHighlight": true,
  "editor.occurrencesHighlight": true,
  "editor.matchBrackets": true,
  "editor.insertSpaces": true,
  "editor.renderWhitespace": "all",
  "editor.scrollBeyondLastLine": true,
  "editor.minimap.enabled": true,
  "editor.renderControlCharacters": true,
  "editor.renderIndentGuides": true,
  "editor.trimAutoWhitespace": true,
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  "editor.minimap.showSlider": "always",
  "window.zoomLevel": 0,
  "beautify.tabSize": 2,
  "terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\cmd.exe",
  "workbench.startupEditor": "newUntitledFile",
  "explorer.confirmDragAndDrop": false,
  "extensions.ignoreRecommendations": false,
  "http.proxyStrictSSL": false,
  "workbench.statusBar.feedback.visible": false,
  "editor.suggestSelection": "first",
  "editor.fontSize": 15,
  "workbench.colorTheme": "One Dark Pro Vivid",
  "diffEditor.ignoreTrimWhitespace": true,
  "editor.rulers": [
    120
  ]
}
```
</details>

**Comment by sinbad** [comment] 2018-08-15 16:26
I can confirm this started happening with all my Unity C# projects with v 1.26.0, on Win10x64 + C# plugin v1.15.2. Constantly flicks between "No Problems" and the actual (correct) problems, which appear for 1s before disappearing again.

**Comment by sandy081** [comment] 2018-08-15 16:29
@FranklinWhale With your steps I see following. It looks like C# extension is continuously updating the diagnostics and hence problems view is getting updated.

![kapture 2018-08-15 at 18 26 16](https://user-images.githubusercontent.com/10746682/44159777-c38ca080-a0b8-11e8-966a-74eea52ffd46.gif)

@Domvel Looks like you have a different issue that problems view is showing bogus errors. Is it possible to steps to reproduce with some code samples?

**Comment by GlenCFL** [comment] 2018-08-15 16:35
I have the C# problem flickering issue fixed locally with some [modifications](https://github.com/GlenCFL/omnisharp-vscode/commit/532dddcc0a3d438b73d3e481406b99f985dfc540) to their diagnostics provider, though they seemed pretty confident that it was a VSCode issue over in their repository.

**Comment by Domvel** [comment] 2018-08-15 16:36
@sandy081 I want to create a demonstration project with short docs to reproduce this. But not sure at this moment. And I also ask some people if they have the same issue.

**Comment by FranklinWhale** [comment] 2018-08-15 16:40
@sandy081 The issue was reported in OmniSharp/omnisharp-vscode#2456 and it was closed

**Comment by dchw** [comment] 2018-08-15 17:07
I accidentially posted this earlier on #56371, sorry!

I am on macOS Mojave and here is a sample C# project that can reproduce this. I created it with `dotnet` commands at the command line exclusively.
[testProj.zip](https://github.com/Microsoft/vscode/files/2291036/testProj.zip)

**Comment by sandy081** [comment] 2018-08-15 17:54
As I said there are two issues:

1. Problems keep on showing in loops.

This is happening because, whenever problems for a file are shown, problems view asks for the code actions in that file by opening it and closing it after. Looks like the C# extension is reacting to these and generating diagnostics. 

@rchande Can the C# extension handles this? I will try to see if I can do a fix from our side.

2. Showing bogus problems.

Please refer to #56371 for this.

**Comment by rchande** [comment] 2018-08-15 18:39
@sandy081 Our [diagnostics provider](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/diagnosticsProvider.ts) tries to react to a variety of events and push diagnostics to a diagnostic collection. It sounds like Code has changed the way it processes/requests diagnostics internally. Can you help me understand exactly what chose changes were? It sounds like we can stop responding to file open/close to push diagnostics. Anything else?

**Comment by domske** [comment] 2018-08-15 21:51
Sometimes the error checker is looping. But also incorrect an buggy errors in problem panel. 
![vs-code-1-26-problems-panel-bug](https://user-images.githubusercontent.com/28209992/44175099-7d9a0180-a0e5-11e8-9f90-13328e171c86.png)

In the image you see a corrupt problem panel content. The errors are not clickable. The first error is not related to a source file. 
After restart of VS Code the panel works correctly. I did not yet figured out, how to reproduce. But this is only in version **1.26** for sure. Maybe a tslint (by egamma) extension issue? 

[demo-project.zip](https://github.com/Microsoft/vscode/files/2291823/demo-project.zip)

**Comment by Marconius6** [comment] 2018-08-16 02:25
I have this same issue on 1.26.0, on Windows; a colleague working on Mac said he had it too, but for him it resolved after restarting Code once.

I also noticed the number next to Problems updates as you'd expect when you have that tab open, BUT if you have any other tab open, or close that window entirely, the number always stays at whatever is highest. To me this says it's an error with the Problems tab specifically, and doesn't seem to be an issue with OmniSharp itself; also not that if you're looking at OmniSharp output, it does NOT produce additional output beyond the first time.

**Comment by Domvel** [comment] 2018-08-16 08:10
Of course . My case is more related to #56371.

**Comment by sandy081** [comment] 2018-08-16 10:30
To verify:

- Install c# extensions
- Download the [testProj.zip](https://github.com/Microsoft/vscode/files/2291036/testProj.zip)
- Open the project in VS Code
- Open Problems Panel and make sure that problems are shown without any looping.

**Comment by aeschli** [comment] 2018-08-16 11:07
Code reviewed

**Closed** 2018-08-16 11:50 UTC
Labels: bug, candidate, error-list

**Comment by aeschli** [comment] 2018-08-16 11:58
Verified in 1.26.1-stable
Commit: 49e7ddb857cda50c123f37f39cb1ef8894bf53bb
