### ISSUE TITLE
Startup time really long (specially with extensions)

### ISSUE THREAD

**Issue by dnano91** [Microsoft/vscode#36732] opened 2017-10-23 08:18 UTC
VS Code takes really long to start. I attached screenshots from the startup performance window where it is visible that extensions alone take over 5 seconds. This is a really annoying issue. But even without extensions VS Code takes about 5 secs. This might not seem too much of an issue for you (as i've read in another issue that you consider 5 seconds to be fast) but it still breaks my workflow (considering i'm using extensions) and is really annoying. I'd hate to switch to another Editor, as I've really come to love using code and it's getting better with every update, however performance is a major factor for me. If I just want to open a file quickly and modify or just view it, I have to wait over 10 seconds, which for me is not acceptable. 

- VSCode Version: 1.17.2
- OS Version: Win 10 1703

Reproduces without extensions: Partially

Starting with extensions
![with extensions](https://user-images.githubusercontent.com/4669823/31878287-e4e784d4-b7d9-11e7-9294-5043f078899f.PNG)
![with](https://user-images.githubusercontent.com/4669823/31878864-c7675fd6-b7db-11e7-9aa0-d21024849f96.PNG)

Starting without extensions:
![noext](https://user-images.githubusercontent.com/4669823/31877971-bf86ee42-b7d8-11e7-91a0-a8210496a3f3.PNG)

EDIT: I uninstalled the code spellchecker (took most of the time) and disabled the azure tools extensions (3 of them, need them occasionally) so I will have to check how this affects the startup time as I'm currently using code.

**Comment by jrieken** [comment] 2017-10-23 16:27
This is a duplicate of #22087 and we are sorry that there isn't a fix yet

**Closed by jrieken** 2017-10-23 16:27 UTC
Labels: perf
