### ISSUE TITLE
 Bad progress location: timeline

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#95093] opened 2020-04-13 07:11 UTC
Issue Id: <b>3bd46089-0550-d50c-4f16-0b523d2b44e7</b><br /><br />*Versions* <br />- 1.44.0<br />-  ea935488ec0e5415d4205c1f33ba332fd417f85a<br />*Stack* <br />Error: Bad progress location: timeline<br />[/vs/workbench/services/progress/browser/progressService.ts#64:9 (withProgress)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/services/progress/browser/progressService.ts#L64:9 (withProgress))<br />[/vs/workbench/contrib/timeline/browser/timelinePane.ts#559:41 (handleRequest)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L559:41 (handleRequest))<br />[/vs/workbench/contrib/timeline/browser/timelinePane.ts#536:7 (loadTimelineForSource)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L536:7 (loadTimelineForSource))<br />[/vs/workbench/contrib/timeline/browser/timelinePane.ts#476:26 (loadTimeline)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L476:26 (loadTimeline))<br />[/vs/workbench/contrib/timeline/browser/timelinePane.ts#281:7 (setUriCore)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L281:7 (setUriCore))<br />[/vs/workbench/contrib/timeline/browser/timelinePane.ts#337:7 (call)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L337:7 (call))<br />[/vs/base/common/event.ts#589:18 (fire)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/base/common/event.ts#L589:18 (fire))<br />[/vs/workbench/services/editor/browser/editorService.ts#139:32 (doHandleActiveEditorChangeEvent)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/services/editor/browser/editorService.ts#L139:32 (doHandleActiveEditorChangeEvent))<br />[/vs/workbench/services/editor/browser/editorService.ts#129:7 (handleActiveEditorChange)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/services/editor/browser/editorService.ts#L129:7 (handleActiveEditorChange))<br />[/vs/workbench/services/editor/browser/editorService.ts#147:9 (call)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/services/editor/browser/editorService.ts#L147:9 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#905:29](https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L905:29)<br />    at processTicksAndRejections (<REDACTED: user-file-path>:85:5)<br />    at asyn<br />

**Comment by eamodio** [comment] 2020-04-24 16:51
Duplicate of #96045

**Closed by eamodio** 2020-04-24 16:51 UTC
Labels: timeline
