### ISSUE TITLE
gitignore is not used for find in folder exclusion searching in subdirectory

### ISSUE THREAD

**Issue by eedwards-sk** [microsoft/vscode#81119] opened 2019-09-18 20:12 UTC
Issue Type: <b>Bug</b>

1. given a workspace folder structure:

```
/
/bar/.gitignore
/bar/baz/hello.txt
```

given `/bar/.gitignore`:
```
/baz/
```

given `/bar/baz/hello.txt`:
```
world
```

---

2. expected results

a) performing a "Find in Folder" search on `/bar` for "world" with exclusions enabled:

- no results (`/bar/.gitignore` is used)

---

3. actual results

a) performing a "Find in Folder" search on `/bar` for "world" with exclusions enabled:

- found `world` in `bar/baz/hello.txt` (`/bar/.gitignore` is not used)

---

Note:

a) performing a "Find in Folder" search on `/` for "world" with exclusions enabled:

- no results (`/bar/.gitignore` is used)

---

Comments:

From my testing it appears that:

- a `.gitignore` file present in the current or subdirectory of the search is ignored if the current directory being searched is itself a subdirectory

- a `.gitignore` file is ignored if it's in a parent directory of the current target folder (e.g. `/.gitignore` when searching in `/bar/`), even if that parent directory is the workspace folder root

---

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (4.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
haproxy|bma|0.1.2
better-toml|bun|0.3.2
solargraph|cas|0.21.1
json-tools|eri|1.0.2
url-encode|fle|1.1.0
shell-format|fox|6.1.1
vscode-systemd-support|han|0.1.1
workspacesort|ici|1.5.8
applescript|idl|0.18.1
json-escaper|jos|1.1.0
bash-ide-vscode|mad|1.3.3
autoconf|mae|0.1.0
terraform|mau|1.4.0
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
Go|ms-|0.11.4
powershell-preview|ms-|2019.5.0
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
bash-debug|rog|0.3.6
partial-diff|ryu|1.4.0
vscode-nginx|sha|0.6.0
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.8.1
propertylist|zho|0.0.2

</details>

**Comment by roblourens** [comment] 2019-09-21 20:32
> performing a "Find in Folder" search on /bar for "world" with exclusions enabled:

I assume you are using the "files to include" box in the search view?

I think this is essentially just because that pattern takes precedence over the `.gitignore`. ripgrep doesn't really give us a way to change that.

**Comment by eedwards-sk** [comment] 2019-09-23 16:50
> I assume you are using the "files to include" box in the search view?

That's correct.

> I think this is essentially just because that pattern takes precedence over the .gitignore. ripgrep doesn't really give us a way to change that.

That sucks.

**Comment by roblourens** [comment] 2019-09-24 16:13
> If I search on a subdir in my project, it's searching as a pattern rather than performing a search inside that directory?

Yeah, used to do it the other way, but there were issues with that, like getting files.exclude from the main workspace and `.gitignore` to be applied correctly.

**Comment by eedwards-sk** [comment] 2019-09-24 16:16
> there were issues with that, like getting files.exclude from the main workspace and .gitignore to be applied correctly.

Clearly there are issues with this solution, as well :)

**Comment by roblourens** [comment] 2019-10-10 00:58
Actually a duplicate of https://github.com/microsoft/vscode/issues/26574

**Closed by roblourens** 2019-10-10 00:58 UTC
Labels: search, under-discussion
