### ISSUE TITLE
The TypeScript shit is still going on

### ISSUE THREAD

**Issue by OlaLov** [Microsoft/vscode#20208] opened 2017-02-08 15:20 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.5|
|jquerysnippets|donjayamanne|0.0.1|
|json-tools|eriklynd|1.0.2|
|knockoutjs|furstenberg|0.1.0|
|beautify|HookyQR|0.7.3|
|minify|HookyQR|0.3.0|
|docthis|joelday|0.3.10|
|sp-tools|Mike|0.3.0|
|PowerShell|ms-vscode|0.9.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|debugger-for-chrome|msjsdiag|2.5.2|
|vs-code-office-ui-fabric|sivarajanraju|0.1.7|
|spremoteapi|SteveCurran|1.5.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.
2.

**Comment by dogmatic69** [comment] 2017-02-08 15:24
You should probably update the ticket you made 5 days ago, #19797

**Comment by mjbvz** [comment] 2017-02-08 19:03
Duplicate of #19797

**Closed by mjbvz** 2017-02-08 19:03 UTC
