### ISSUE TITLE
Synchronized scrolling in splited 2 or more tabs (pararell with both files in same time).

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#37940] opened 2017-11-09 13:03 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: none
---

Sometimes (like, if you want translate some texts) you need have opened two files. You can have file like as 

en.txt
ID C352 = "hello"
ID C353 = "goodbye"

and second file like.
sk.txt
ID C352 = "ahoj"
ID C353 = "dovidenia"

maybe if you want translate items from one file to second file, and you know you have words with same mean in same line in files, it's good to scroll synchronized with 2 "tabs" in splited editor.

(it's can be good also for other things, not only for translating). Because you sometimes need two files had scrolled at same with lines at same lines.

(sry for my English)

sketch/outline:

![screenshot_3](https://user-images.githubusercontent.com/31345346/32606913-5167271a-c557-11e7-9e24-f421cb4095b1.png)

And want scroll pararels with both files in the same time.

You can add switchable button for it (with this function).

**Comment by fabiospampinato** [comment] 2017-11-09 13:44
This is already sort of implemented for Markdown files, if you open the preview on the side and scroll it the source file will scroll as well. +1 for enabling support for all for all kind of files.

**Comment by solidxsnake** [comment] 2017-11-30 21:30
Bump. This would be very useful, and is standard in other editors (like N++).

I'm surprised it hasn't already been implemented, especially given the functionality is pretty much all there for Markdown.

**Comment by bpasero** [comment] 2018-04-18 16:43
Duplicate of https://github.com/Microsoft/vscode/issues/33110

**Closed by bpasero** 2018-04-18 16:43 UTC
Labels: feature-request, trackpad/scroll, workbench-editors
