### ISSUE TITLE
Format-on-type: Cursor on wrong side of edit

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12815] opened 2016-09-27 18:58 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

Testing #12633

1. "editor.formatOnType": true
2. Start with:
```
let app: any;
app.get('/', (req, res) => {
    res.send('Foo Bar');
});
```
3. Place caret after the comma at: '/',
4. Press enter
```
let app: any;
app.get('/',
    (req, res) => {
    res.send('Foo Bar');
});
```
5. Observe: Caret ends up at start of line with the added indentation to the right of it.
6. Expected: Indentation is added to the left of the caret.

**Comment by jrieken** [comment] 2016-09-28 08:13
@chrmarti at what point did save/formatOnSave happen?

**Comment by jrieken** [comment] 2016-09-28 10:23
Ah, now I understand... I was still in the format on save mind set but this is actually format on type... Maybe  a regression from moving to TS 2.0

**Comment by jrieken** [comment] 2016-09-28 13:31
The edit encloses the current cursor position (replace one whitespace with four). Adding @alexandrudima as you did the initial work here and need some consulting on this

![screen shot 2016-09-28 at 15 29 50](https://cloud.githubusercontent.com/assets/1794099/18915162/6eecd03a-8590-11e6-9237-dd2ed8d41dcd.png)

**Comment by alexandrudima** [comment] 2016-10-24 08:57
I don't think this is fixable except perhaps to drop the formatting edit and hope that line gets formatted later.

```
app.get('/',
| (req, res) => {
```

* before the edit, the cursor is before the space
* comes an edit that asks to replace the space with a tab
* after the edit, the cursor is **as designed** kept before the tab

There is no hint whatsoever that in this case the cursor should move to after the tab. Even more, it could be that there were 50 spaces between the cursor and the actual code being replaced with a single tab, in all cases I think it is fair that the cursor stays put, before the whitespace.

If this is not acceptable, then we need to make format on type sync and/or have it return a cursor end position.

**Comment by jrieken** [comment] 2016-10-24 10:11
closing as designed per alex' explanation

**Closed by jrieken** 2016-10-24 10:11 UTC
Labels: as-designed, bug, format

**Comment by cnshenj** [comment] 2016-11-14 19:37
Although this is "by design", it is not a good design. Please fix it.

Visual Studio does it properly, and I believe most of the editors also do it properly.
