### ISSUE TITLE
http.proxy

### ISSUE THREAD

**Issue by zengyun9032584** [Microsoft/vscode#23794] opened 2017-04-01 10:02 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|tslint|eg2|0.8.1|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.1.2|
|vscode-add-angular2-files|sebastianbaar|1.1.3|;

---

Steps to Reproduce:

1.I can download Extensions in VSCode version 1.7.1 by set proxy in settings.json file but i cat't download Extensions in current VSCode version  by the same manner.
2."http.proxy": "http://username:password@Proxy-site:8080/"

**Comment by joaomoreno** [comment] 2017-04-06 08:26
Duplicate of #22214

**Closed by joaomoreno** 2017-04-06 08:26 UTC
