### ISSUE TITLE
Sub-word navigation in Find dialog box

### ISSUE THREAD

**Issue by dubeg** [Microsoft/vscode#55914] opened 2018-08-06 21:53 UTC
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:11.471Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: ia32

If I invoke the Find panel  (`ctrl+f`), then try to use sub-word navigation, it will do it in the editor instead of the Find dialog's input.

My keybindings are as follow:

```
[
// Zoom.
{ "key": "ctrl+=", "command": "editor.action.fontZoomIn" },
{ "key": "ctrl+-", "command": "editor.action.fontZoomOut" },

// Sub-word navigation.
{ "key": "alt+right", "command": "cursorWordPartRight", "when": "textInputFocus" },
{ "key": "alt+left", "command": "cursorWordPartStartLeft", "when": "textInputFocus" },

// Sub-word selection.
{ "key": "alt+shift+right", "command": "cursorWordPartRightSelect", "when": "textInputFocus" },
{ "key": "alt+shift+left", "command": "cursorWordPartStartLeftSelect", "when": "textInputFocus" },

// // Word navigation.
{ "key": "ctrl+right", "command": "cursorWordStartRight", "when": "textInputFocus" },
{ "key": "ctrl+left", "command": "cursorWordEndLeft", "when": "textInputFocus" },

// // Word selection.
{ "key": "ctrl+shift+right", "command": "cursorWordEndRightSelect", "when": "textInputFocus" },
{ "key": "ctrl+shift+left", "command": "cursorWordStartLeftSelect", "when": "textInputFocus" },

]
```

**Comment by ramya-rao-a** [comment] 2018-08-06 23:41
@JacksonKearl Any chance this is related to other issue you were looking at https://github.com/Microsoft/vscode/issues/41855?

**Comment by JacksonKearl** [comment] 2018-08-06 23:45
It sounds similar, but that issue seemed to only effect actions which were also in the menu bar. Some of those keybindings tied to actions in the menu bar by default though, so it could be related somehow. 

@dubeg if you're on Windows could you try setting `"window.titleBarStyle": "custom"` and see if that helps? That fixed the other issue.

**Comment by V-ed** [comment] 2018-08-07 03:36
> Ideally, I'd have it in every bit of UI that can edit text: command palette/quick panel, renaming file/folder in Explorer panel, inputs in Search panel, etc.

That'd be a duplicate of #53498.

> If I invoke the Find panel (`ctrl+f`), then try to use sub-word navigation, it will do it in the editor instead of the Find dialog's input.

Not sure what you mean by here, it doesn't do that on my side - that when clause is preventing the keybind to trigger when not in the editor...

**Comment by dubeg** [comment] 2018-08-07 18:31
@JacksonKearl Just tried the setting, it didn't fix this issue (but the look is very nice).
@V-ed Alright, I'm removing that part then.

**Comment by rebornix** [comment] 2018-09-11 23:56
We don't have plans to do this in the near term but we can revisit this issue when we do the next roadmap planning.

**Closed** 2018-09-11 23:56 UTC
Labels: *out-of-scope, editor-find, feature-request
