### ISSUE TITLE
Terminal z-index prompt seems to go on top of scrollbar

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145404] opened 2022-03-18 15:34 UTC
![Screenshot showing the terminal prompt overlapping the bottom scrollbar when the terminal width is very narrow](https://user-images.githubusercontent.com/7199958/159033169-b429a7df-a3ff-46ca-a002-909ae20a17f4.PNG)

**Comment by meganrogge** [comment] 2022-03-18 22:11
Can you pls provide repro steps? Not sure what that image is indicating

**Comment by rzhao271** [comment] 2022-03-18 22:46
1. Shrink the panel to make the pwsh terminal really small
2. Shrink the VS code window to reduce its width so there's a scrollbar at the bottom
3. :bug: The prompt seems to cover the scrollbar

**Comment by Tyriar** [comment] 2022-12-13 00:13
Can repro, pretty minor issue but solving this could fix some other layout edge cases:



![Image](https://user-images.githubusercontent.com/2193314/207192237-11f14599-5fbc-40cb-a07d-2c98f94532af.png)

**Comment by Tyriar** [comment] 2022-12-29 18:54
This only happens when tabs are showing

**Comment by Tyriar** [comment] 2022-12-29 18:55
It also only starts when the terminal is < 180px

**Comment by Tyriar** [comment] 2022-12-29 18:56
Caused by this minimum:

https://github.com/microsoft/vscode/blob/5f1fec188f6b90f8fbffe17ddb9f5c4854e7af1e/src/vs/workbench/contrib/terminal/browser/terminalGroup.ts#L19-L22

**Comment by rzhao271** [comment] 2023-01-25 18:11
I can still get the issue to occur on the latest Insiders on Windows.
It is a small issue though, so feel free to mark it as a wontfix.

![The terminal prompt still goes over the scrollbar, like in the image originally posted to this issue.](https://user-images.githubusercontent.com/7199958/214639871-d2f89b96-c3e1-48fd-a148-c3dc6f6f8302.png)

**Comment by Tyriar** [comment] 2023-01-26 19:22
@rzhao271 that's the overall window's scroll bar, not the terminal view's scroll bar. 👍 as won't fix as things are expected to get a little wonky when the window is too small for the workbench.

**Closed by Tyriar** 2023-01-26 19:22 UTC
Labels: bug, verification-found, insiders-released, terminal-layout
