### ISSUE TITLE
Notifications with buttons should fly out after a timeout

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#44128] opened 2018-02-21 14:26 UTC
*This is a follow-up to #22388.*

**Summary**
Now that notifications appear in the lower-right corner, many users will expect them to well, behave like notifications and go away. Currently, notifications with buttons are permanent, and therefore require user interaction, even in scenarios where it is not required.

Example:

>![notification_action_required](https://user-images.githubusercontent.com/1007463/36484619-1385937e-16d7-11e8-9eab-150a6755553e.png)
>Figure 1: Attempting to debug a file without a launch configuration.

Here, the alternate workflow is obvious, (manually opening the launch.json file) which means that the notification should go away. This is arguably, also easier, since the explorer and debug panels are very close to each other, while the notification 'x' is on the other side of the screen.

Ideally, all notifications should have a timeout. This would also force developers to fix inappropriate API usage. Practically, notifications with buttons should probably remain in their old top-center position.

**Comment by bpasero** [comment] 2018-02-21 15:43
We thought about this but it is unlikely that we can do this easily because our API currently does not distinguish an important message box that the user should act on to a notification that just happens to have buttons. 

I think a requirement first would be to have proper API and then we could revisit this.

**Comment by bpasero** [comment] 2018-09-11 15:43
Closing "as designed".

**Closed by bpasero** 2018-09-11 15:43 UTC
Labels: feature-request, workbench-notifications
