### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.

### ISSUE THREAD

**Issue by TeNNoX** [microsoft/vscode#122291] opened 2021-04-27 09:24 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.4

**Steps to reproduce crash**
1. Open blank notebook
2. Write some JS code
3. Change cell language to typescript

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.
    at getOrCreateSourceFileByPath (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149163:34)
    at Object.getOrCreateSourceFile [as getSourceFile] (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149121:24)
    at findSourceFileWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107917:29)
    at findSourceFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107827:26)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107779:85
    at getSourceFileFromReferenceWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107746:34)
    at processSourceFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107779:13)
    at processRootFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107589:13)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106471:67
    at Object.forEach (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:190:30)
    at Object.createProgram (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106471:16)
    at synchronizeHostData (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149086:26)
    at Proxy.getProgram (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149178:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154091:53)
    at InferredProject.Project.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154021:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156193:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157750:26)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158024:97
    at Object.flatMap (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158024:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159079:46)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160954:28)
    at IOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:33)
    at IOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160989:35)
    at Interface.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.56.0-insider (633562da380f9161ea2fd783e561eed508cfbbea, 2021-04-26T05:13:49.678Z)
OS version: Linux x64 5.11.0-7612-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.29GB (0.22GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8e949339-a750-4f26-b3c4-4c93cef7e451|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-zipfs|arc|2.3.0
god|bas|0.0.100
solidity-extended|bea|3.0.2
markdown-mermaid|bie|1.9.2
mermaid-markdown-syntax-highlighting|bpr|1.2.0
simple-react-snippets|bur|1.2.3
vscode-standardjs-snippets|cap|0.8.15
ts-snippets|chr|1.1.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
gitlab-workflow|Git|3.18.0
vscode-graphql|Gra|0.3.15
todo-tree|Gru|0.0.212
npm-dependency-links|her|1.2.0
output-colorizer|IBM|0.1.2
vue-autoimport|ish|1.0.5
hungry-delete|jas|1.6.0
vscode-peacock|joh|3.9.1
intellij-idea-keybindings|k--|1.4.4
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.12.1
python|ms-|2021.5.772362017-dev
jupyter|ms-|2021.6.780948196
remote-containers|ms-|0.172.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
debugger-for-chrome|msj|4.12.12
abracadabra|nic|5.2.0
hocus-pocus|nic|1.7.0
vetur|oct|0.33.1
vue-vscode-snippets|sdr|2.2.0
vscode-scss-formatter|sib|2.1.0
autoimport|ste|1.5.4
sass-indented|syl|1.8.16
serverless-ide-vscode|Thr|0.5.31
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
vspre833:30267464
pythonptprofiler:30281269
vshan820cf:30276953
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by TeNNoX** [comment] 2021-04-27 09:27
TS Server logfile:
[tsserver.log](https://github.com/microsoft/vscode/files/6383439/tsserver.log)

**Comment by mjbvz** [comment] 2021-04-27 18:11
Duplicate of https://github.com/microsoft/TypeScript/issues/42613

**Closed by mjbvz** 2021-04-27 18:11 UTC
