### ISSUE TITLE
Auto-indent for Lua5.3 Is Driving Me Mad

### ISSUE THREAD

**Issue by the-geassed** [Microsoft/vscode#68911] opened 2019-02-18 10:30 UTC
Issue Type: <b>Bug</b>

Try using "if" statement inside a function, the "end" on a new line will automatically go to the head of the line ( without any indents!). 
The result is the same even after I uninstall every Lua-related extention. 
Never fussed about the detail settings for VSCode myself,  it took me some time before I could find the "editor.autoIndent" setting and disable the feature entirely.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by keithoconor** [comment] 2019-02-18 12:00
I'm seeing this too, and it only started happening in a recent version of VS Code. I'll see if I can figure out which one.

**Comment by idunbar** [comment] 2019-02-18 12:04
This issue is occurring for me as well with Lua 5.1 on macOS (10.14.1) with both versions 1.31.0 and 1.31.1. Reverting my installation to 1.30.2 causes the issue to go away.

Additionally it seems as though the issue is not limited to if-then-end blocks but affects auto indentation in general.

**Comment by wwsstt** [comment] 2019-02-18 13:03
I found this issue too, I reverted my release version to 1.30.2, and wait for the solusion...

**Comment by alexr00** [comment] 2019-02-18 15:23
Duplicate of #68876. I can reproduce this too.

**Closed** 2019-02-18 15:37 UTC
Labels: editor-autoindent
