### ISSUE TITLE
Navigation mouse buttons stopped working in latest release

### ISSUE THREAD

**Issue by EvgeniTT** [microsoft/vscode#77570] opened 2019-07-18 11:16 UTC
![Annotation 2019-07-18 141040](https://user-images.githubusercontent.com/49648229/61453292-62bfb500-a966-11e9-94b0-c29d8e375f20.png)

Does this issue occur when all extensions are disabled?: Yes, it does!

Since last update my mouse buttons for back and forward has stopped working.
I have attached a screenshot of my version.

**Comment by mjbvz** [comment] 2019-07-18 21:36
Duplicate of #71318

**Closed by mjbvz** 2019-07-18 21:36 UTC
