### ISSUE TITLE
PHP class name got wrong styling class (constant.other.php instead of support.class.php)

### ISSUE THREAD

**Issue by mmn6d6d6e** [Microsoft/vscode#45245] opened 2018-03-08 01:21 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 8.1 x64

Steps to Reproduce:

1. create new file
2. set language mode to php
3. `<?php`
`My\Package\Myclass::CONST; // Capitalized on first letter only`
`My\Package\MyClass::CONST; // Capitalized on first and middle`
4. change to other color theme like **Solarized Dark** to see color difference
5. OR use **Inspect TM Scope** and point to `Myclass` and `MyClass`

correct:
![image](https://user-images.githubusercontent.com/19344000/37127711-8ff301ac-22a9-11e8-9fcb-60f5c393ece7.png)

wrong:
![image](https://user-images.githubusercontent.com/19344000/37127718-94555d3a-22a9-11e8-8b0a-1be47beea28d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-03-08 02:06
/duplicate of https://github.com/Microsoft/vscode/issues/44032

**Closed by roblourens** 2018-03-08 02:06 UTC
Labels: *duplicate, php
