### ISSUE TITLE
Typescript tasks does not work when ussing git-bash for windows

### ISSUE THREAD

**Issue by jhm-ciberman** [Microsoft/vscode#38178] opened 2017-11-13 04:05 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.21
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
fontsize-shortcuts|fos|1.4.0
explorer-excluded-files|sad|1.0.0
ignore-gitignore|stu|1.0.1
terminal-tabs|Tyr|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Download git-bash for windows from https://git-for-windows.github.io/ (I currently have installed from http://cmder.net/ that bundles with git bash for windows, but it is the same)
2. Configure VSCode to use Git-bash for windows instaed of CMD. In your preferences: 
```
    "terminal.integrated.shell.windows": "PATH\\TO\\BASH\\FOR\\WINDOWS\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "--login",
        "-i"
    ],
```
3. Open a Typescript project and try to run any `tsc:` task from the `Tasks > Run Task` menu. The output in the console will be the following: (The project folder name is `f:\repos\public\docs_gm\` and local tsc IS installed from npm)
```
> Executing task: f:\repos\public\docs_gm\node_modules\.bin\tsc.cmd --watch -p "f:\repos\public\docs_gm\tsconfig.json" <

bash: f:repospublicdocs_gmnode_modules.bintsc.cmd: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-12-15 17:38
I think this is probably a support problem with tsc not working with git bash

**Comment by ComradeCow** [comment] 2017-12-15 18:33
I'm affected by this bug as well. We use the `tsc: watch` task to monitor TypeScript changes.  My current work around is to open git bash and run `tsc -w` to start my watcher.  That works regardless of what version of the TypeScript compiler and Git for Windows I have installed.

We recently updated our `tasks.json` file to version: 2.0 schema using the default options for `tsc: watch`, which generated the following `tasks.json` file:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

The that task works for my coworkers with CMD configured, but doesn't for me (since I use Git Bash).  However, when I backdate the tasks.json file to our previous version (below), the watcher build task starts as expected.

```
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "tsc watch",
            "command": "tsc",
            "isShellCommand": true,
            "args": ["-w", "-p", "."],
            "showOutput": "silent",
            "isBackground": true,
            "isBuildCommand": true,
            "problemMatcher": "$tsc-watch"
        }
    ]
```
I expected the two tasks to have roughly equivalent behavior to them (fire up the watcher and monitor my changes). Is there a change I should make to our build task to support using Bash in VSCode on Windows?

**Comment by dbaeumer** [comment] 2017-12-18 10:45
This is the same problem as with WSL. The underlying reason is that the pathes need / instead of \ and a special starting sequence. When run under Windows task assume a Windows terminal.

**Comment by dmitriyrepin** [comment] 2017-12-28 16:10
I have a similar issue. When the integrated terminal is configured to use bash, 
`"terminal.integrated.shell.windows":` "C:\\Program `Files\\Git\\bin\\bash.exe"`

the default typescript build task v 2.0.0 
`
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "problemMatcher": [
        "$tsc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "silent",
        "panel": "dedicated"
      }
    }
  ]
}`
`

tries to re-use this bash-based terminal while running the Windows tsc command:

> Executing task: e:\_Dev\_Prototypes\2017_WEB\gika-web\server\node_modules\.bin\tsc.cmd -p "e:\_Dev\_Prototypes\2017_WEB\gika-web\server\tsconfig.json" <

/usr/bin/bash: e:_Dev_Prototypes2017_WEBgika-webservernode_modules.bintsc.cmd: command not found
The terminal process terminated with exit code: 127

**Comment by ashelley** [comment] 2018-01-05 21:38
I'd like to confirm @dmitriyrepin 

.vscode/task.json
`
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "src\\tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ]
        }
    ]
}
`

.\node_modules\.bin\tsc --version
Version 2.6.2

when settings has this:

"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

the build in typescript tasks don't work (ctrl+shift+b) /build

![image](https://user-images.githubusercontent.com/3195045/34629617-a8cad8b0-f21d-11e7-8258-347ace850949.png)

`
/usr/bin/bash: c:inetpubwwwrootmyprojectnode_modules.bintsc.cmd: command not found
The terminal process terminated with exit code: 127
`

**Comment by StefanoChiodino** [comment] 2018-02-23 10:02
@ComradeCow solution worked for me, I polished it up a bit to make vscode happy about deprecations.
```
{
    "label": "tsc watch",
    "command": "tsc",
    "type": "shell",
    "args": ["-w", "-p", "."],
    "presentation": {
        "echo": true,
        "reveal": "never",
        "focus": false,
        "panel": "shared"
    },
    "isBackground": true,
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "problemMatcher": "$tsc-watch"
}
```

**Comment by anhallbe** [comment] 2018-05-08 09:39
In addition to the above solution, you could also change the shell for the specific task:

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"option": "watch",
			"options": {
				"shell": {
					"executable": "powershell.exe"
				}
			},
			"problemMatcher": [
				"$tsc-watch"
			],
			"group": "build"
		}
	]
```
...or make it windows-specific with the "windows" property

**Comment by jasonterando** [comment] 2018-05-19 14:03
@anhallbe  - Thanks!  Overriding the shell fixed a similar problem I was having with CMDER on Windows.

**Comment by oryandunn** [comment] 2018-09-12 21:48
> In addition to the above solution, you could also change the shell for the specific task:
> 
> ```
> {
> 	"version": "2.0.0",
> 	"tasks": [
> 		{
> 			"type": "typescript",
> 			"tsconfig": "tsconfig.json",
> 			"option": "watch",
> 			"options": {
> 				"shell": {
> 					"executable": "powershell.exe"
> 				}
> 			},
> 			"problemMatcher": [
> 				"$tsc-watch"
> 			],
> 			"group": "build"
> 		}
> 	]
> ```
> ...or make it windows-specific with the "windows" property

What would this look like with the windows specific tag?  I think I've tried putting "windows" at just about every level, some levels the editor complains, others it doesn't, but I've not found one that works.  I read through the tasks.json schema, but I'm not sure how accurate that is since the typescript type is not listed.

**Comment by RedTailBullet** [comment] 2018-11-27 08:41
My suggestion for fixing this is to separate the option for specifying the shell used. Instead of just letting user input the path to the executable like now, separate them into two options:
1. What should be used as the default integrated shell: Powershell, cmd or WSL bash?
2. And specify the path if you want to use another executable.

This way, VS Code can judge which shell is used and adjust the path of the tasks.

**Comment by alexr00** [comment] 2018-12-21 13:58
Duplicate of #35593

**Closed** 2018-12-21 13:59 UTC
Labels: *duplicate, WSL, feature-request, tasks
