### ISSUE TITLE
Cannot use captured groups in replace when searching a regex that contains multiple lines (\n)

### ISSUE THREAD

**Issue by SebLz** [Microsoft/vscode#63518] opened 2018-11-20 18:06 UTC
- VSCode Version: 1.29.1
- OS Version: Win 7 x64

It seems that when we search in multiple files using a regex that contains the "\n" sequence, we cannot use the captured groups in the replace field: 

Steps to Reproduce:

Multiline search with **non-**working replace ($1 & $2 are not replaced by their corresponding group)
![image](https://user-images.githubusercontent.com/190146/48793150-55c6c500-ecf6-11e8-8a4c-0eee809c19cc.png)

Multiline search with working replace ($1 & $2 are correctly replaced by their corresponding group)
![image](https://user-images.githubusercontent.com/190146/48793339-f1f0cc00-ecf6-11e8-88b0-e381c75be1e3.png)

**Comment by SebLz** [comment] 2018-11-20 21:23
This does not seem to be a duplicate of any of the bugs above. The example above contains a rather long regex, but even with very simple ones you can verify that the replace is broken as soon as a \n is in the regex:

- (.+) : $1 replace will work
- (.+)\n : $1 replace won't work

**Comment by roblourens** [comment] 2018-11-21 19:17
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/62980 - should be fixed in Insiders

**Closed by roblourens** 2018-11-21 19:17 UTC
