### ISSUE TITLE
Windows Server 2019 Terminal displays nothing on open

### ISSUE THREAD

**Issue by ARambazamba** [Microsoft/vscode#65666] opened 2018-12-25 14:00 UTC
- VSCode Version: 1.30.1
- OS Version: Windows Server 2019

Steps to Reproduce:

1. Open any project type (Angular, JS, .NET Core) in VS Code running on Windows Server 2019
2. Open Terminal
3. The Terminal does not display the initial prompt
4. Text that is typed will be displayed

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/16348023/50423444-a382a000-0855-11e9-9ed0-10ace027cad8.png)

**Comment by usernamehw** [comment] 2018-12-25 22:05
Duplicate of #57803 ?

**Closed** 2018-12-26 19:16 UTC
Labels: integrated-terminal
