### ISSUE TITLE
Scroll line up/down doesn't move cursor

### ISSUE THREAD

**Issue by ildar-shaimukhametov** [microsoft/vscode#124956] opened 2021-05-31 04:57 UTC
Issue Type: <b>Feature Request</b>

![image](https://user-images.githubusercontent.com/56554900/120141526-18601e00-c1f6-11eb-945a-5da882273512.png)

VS Code: cursor doesn't move while scrolling
![2](https://user-images.githubusercontent.com/56554900/120141470-febed680-c1f5-11eb-86af-a7577a0e9f8b.gif)

Visual Studio 2019: cursor moves while scrolling
![1](https://user-images.githubusercontent.com/56554900/120141609-3e85be00-c1f6-11eb-87b6-891d0cfe5b62.gif)

Request: can you do so that cursor moves as in Visual Studio 2019?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by alexdima** [comment] 2021-05-31 07:43
Duplicate of https://github.com/microsoft/vscode/issues/91867

See https://github.com/microsoft/vscode/issues/91867#issuecomment-593291891

**Closed by alexdima** 2021-05-31 07:43 UTC
