### ISSUE TITLE
The setting editor.overviewRulerLanes has no effect

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#83186] opened 2019-10-23 21:34 UTC
This happens in Insiders v1.40.0

- VSCode Version: 1.39.2
- OS Version: macOS 10.15

Steps to Reproduce:
1. Set `"editor.overviewRulerLanes": 1`
2. Notice that the overview ruler still shows 3 lanes

Does this issue occur when all extensions are disabled? Yes

**Comment by andrecasal** [comment] 2019-10-23 21:34
[Related StackOverflow question.](https://stackoverflow.com/questions/57979035/what-does-vs-code-editor-overviewrulerlanes-setting-does/)

**Comment by dhairyanadapara** [comment] 2019-10-24 03:41
@andrecasal, you are right the settings are getting overridden. Once it assigned to anyone I will ask them if this change is necessary or by design they have decided like this. :)

**Comment by alexandrudima** [comment] 2019-10-24 08:50
Fixed by https://github.com/microsoft/vscode/commit/e0d2ed907d1b22808c56127678fb436d604586a7

I've removed the setting from the JSON schema since it has no effect.

**Closed by alexandrudima** 2019-10-24 08:50 UTC

**Comment by dhairyanadapara** [comment] 2019-10-24 12:43
@alexandrudima I will start working on this issue and will raise PR.

**Comment by dhairyanadapara** [comment] 2019-10-24 15:13
@alexandrudima can you please re-open this issue?

**Comment by alexandrudima** [comment] 2019-10-24 18:36
@dhairyanadapara This issue has been fixed. I have linked the commit which fixes this in my previous comment. The fix is to remove the setting from user facing places, like the settings UI or `settings.json`.
