### ISSUE TITLE
[folding] Region missing for nested media queries

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46740] opened 2018-03-27 18:09 UTC
Testing #46535
The `-` symbol for folding is missing for the `@media` line below 

```
@mixin desktop {
  $desktop-width: 1024px;
  @media(min-width: #{$desktop-width}) {
    width: 500px;
    margin: 10px;
  }
}
```

**Comment by aeschli** [comment] 2018-03-28 21:02
The problem is the interpolation inside the media selector.
Duplicate of #46738

**Closed by aeschli** 2018-03-28 21:02 UTC
Labels: bug, css-less-sass, editor-folding
