### ISSUE TITLE
Integrated terminal redraws $PS1 repeatedly while typing

### ISSUE THREAD

**Issue by bluejekyll** [Microsoft/vscode#28638] opened 2017-06-13 16:11 UTC
- VSCode Version: 1.13
- OS Version: macOS 10.12.5, Ubuntu 14.04.5 LTS

Other env config:
- Shell: zsh
- Shell manager: oh-my-zsh + powerlevel9k

Steps to Reproduce:

1. I have left and right side zsh utilities in place
2. An extra path is added after the $PS1 when not typing
2.a this is a copy of the displayed path
2.b only the last two dir paths are displayed, these are duplicated in the shell when not typing

example of desired:
```console
.../parent-dir/current-dir >
```

example after upgrade to 1.13 (shell operates correctly pre 1.13 and system terminals):
```console
.../parent-dir/current-dir/parent-dir/current-dir >
```

3. start typing and the $PS1 reverts to normal (only while typing characters)
3.a this causes a flipflop between `.../parent-dir/current-dir` and `.../parent-dir/current-dir/parent-dir/current-dir` while typing.

I haven't tracked down yet where the conflict is coming from, i.e. is it zsh, oh-my-zsh, or powerlevel9k. Something did change after the 1.13 release, as there were no issues before with the same configuration.

**Comment by SachinMaharana** [comment] 2017-06-13 17:00
I am also facing the exact same issue(Using oh-my-zsh as well + agnoster theme). Image attached.
![deepinscreenshot20170613222913](https://user-images.githubusercontent.com/8871040/27094480-ce083858-5087-11e7-90ee-8a171db5822a.png)

**Comment by ramya-rao-a** [comment] 2017-06-13 18:48
Closing as duplicate of #26038

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-13 18:48 UTC
