### ISSUE TITLE
Code highlighting has changed

### ISSUE THREAD

**Issue by jjoselv** [microsoft/vscode#92572] opened 2020-03-12 11:18 UTC
Issue Type: <b>Bug</b>

Hi!

I reproduce it like this:
Prior to the latest update, a "console.log" statement is highlighted differently as in the previous (as weel as other parts, as imports and such)

I'm using JavaScript syntax but it also happens in JavaScript React.

Thanks!

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|41, 28, 15|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|-psn_0_10644006|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nsp|ada|1.0.1
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.1
githistory|don|0.6.2
es7-react-js-snippets|dsz|2.7.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.28
dotenv|mik|1.0.1
azure-account|ms-|0.8.8
vsliveshare|ms-|1.0.1742
vsliveshare-audio|ms-|0.1.80
debugger-for-chrome|msj|4.12.6
vscode-for-node-js-development-pack|nod|2.0.1
vscode-versionlens|pfl|0.25.0
material-icon-theme|PKi|4.0.1
prisma|Pri|0.0.25
vscode-graphql|Pri|0.2.2
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
vsfire|tob|1.4.1
lorem-ipsum|Tyr|1.2.0
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by stoffeastrom** [comment] 2020-03-12 12:11
Before:
![image](https://user-images.githubusercontent.com/682243/76520254-d87f1080-6462-11ea-8843-721013c9f35b.png) 
After:
![image](https://user-images.githubusercontent.com/682243/76520288-ec2a7700-6462-11ea-96bf-0001c903f73d.png)

**Comment by gjsjohnmurray** [comment] 2020-03-12 12:11
/duplicate of #90379

As a workaround you could disable semantic highlighting

**Closed** 2020-03-12 12:12 UTC
Labels: *duplicate, new release
