### ISSUE TITLE
[css] F2 duplicates dot when renaming classes in css

### ISSUE THREAD

**Issue by andrey6498** [Microsoft/vscode#56354] opened 2018-08-14 13:18 UTC
Issue Type: <b>Bug</b>

select `.classname`, press f2, rename it and hit enter. Result: `..newclassname`

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.95GB (0.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by ddragostinov** [comment] 2018-08-16 10:29
Hi, I would like to try to fix the issue. 

The problem is that word boundaries are computed without the dot, but the dot is displayed in the rename editor.

There are two ways in which this might be addressed:
1. The class name can be shown in the renameInputField without the .
2. The replacement can be done starting with dot

Which one is preferred?

**Comment by jrieken** [comment] 2018-08-16 10:33
The RenameProvider should use the API we have added for such cases: https://github.com/Microsoft/vscode/blob/699d778579995f2e423feef07437b275f4178c49/src/vs/vscode.d.ts#L2920-L2930

**Comment by ddragostinov** [comment] 2018-08-16 10:50
I don't see any calls to this function (and no implementations of it).

vscode/src/vs/editor/contrib/rename/rename.ts:54 checks: if (provider.resolveRenameLocation)
but there is nothing about prepareRename. 

Should I add a call to prepareRename if present and implement it in the renameProvider?

**Comment by aeschli** [comment] 2018-08-16 13:42
This needs to be fixed in the CSS language server witch runs in its own process communicating through the LSP.
`prepareRename` doesn't exist yet in the LSP, but luckily we can just fix this issue without that:

The bug is in the `vscode-css-languageservice`. The range of the edit should include the `.`.
https://github.com/Microsoft/vscode-css-languageservice/blob/8a0c85ea45ae2ca3f92da44ad34d5ba9649d12d5/src/services/cssNavigation.ts#L170

**Comment by octref** [comment] 2018-08-16 15:15
@ddragostinov Here's a contribution doc for CSS Language Service: https://github.com/Microsoft/vscode/blob/master/extensions/css-language-features/CONTRIBUTING.md

**Comment by ddragostinov** [comment] 2018-08-17 08:44
I see another problem here which is not only about the dot

Provided we have the following css:
```css
.body { background-color: red; }
body { background-color: yellow; }
```
If I click on one of the two selectors both get highlighted because the matching is done based on position and the "shortest" node is returned by getNodeAtOffset. Which results in the selector's identifier.

Should the behavior of findDocumentHighlights to be when we click an identifier of a selector to return the selector occurrence (e.g. SimpleSelector or ClassSelector)?

**Comment by aeschli** [comment] 2018-08-17 09:07
Yes, I think the problem is already in the findDocumentHighlights. It should highlight the ClassSelector and other ClassSelector of the same name and not match ElementNameSelector.

**Closed** 2018-09-24 17:11 UTC
Labels: bug, css-less-scss
