### ISSUE TITLE
"editor.wordBasedSuggestionsMode": "allDocuments" doesn't provide other open document words

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144857] opened 2022-03-10 18:41 UTC
Why here no suggestion item `abc` in file `b.js`.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/157733420-a8bb50ab-f42b-4769-bc19-3e196e45678b.png">

Seems work in markdown file:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/157733084-733dce6e-5f67-4cdb-93c3-1801c01daaa6.png">

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

@mattbierner

**Comment by jrieken** [comment] 2022-03-10 19:11
Please attach all files in source

**Comment by jrieken** [comment] 2022-03-10 19:13
This is actually a /duplicate of https://github.com/microsoft/vscode/issues/21611. As long as tsserver provides suggestions word-based suggestions won't show.

**Closed by jrieken** 2022-03-10 19:13 UTC
Labels: suggest
