### ISSUE TITLE
VoiceOver screen reader repeating all text entered with each character typed on Mac VS Code

### ISSUE THREAD

**Issue by keford** [microsoft/vscode#140220] opened 2022-01-06 14:49 UTC
Issue Type: <b>Bug</b>

1. Start VoiceOver.
2. Open any file.
3. Start typing.

Result:
The full text that you have entered is echoed back with each character typed.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 93b64371-544c-441c-98de-23303e474b41|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
py55gd98cf:30419166
vscexrecpromp3t1:30407762

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by isidorn** [comment] 2022-01-06 15:23
Since I can not 100% reproduce this, @keford can you please try with VS Code insiders https://code.visualstudio.com/insiders/

Can you reproduce for any file? How about an untitled file with the follow content
```
first line
second line |cursor
```

Do you get the suggest widget in between that might confuse VoiceOver since the TextBox got refocused?

**Comment by keford** [comment] 2022-01-06 17:35
This repros for me in the same fashion with the Insider build.  It happens as soon as I type any character and also with the specific content you used here.

From: Isidor Nikolic ***@***.***>
Date: Thursday, January 6, 2022 at 10:23 AM
To: microsoft/vscode ***@***.***>
Cc: Kelly Ford (CELA) ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] VoiceOver screen reader repeating all text entered with each character typed on Mac VS Code (Issue #140220)

Since I can not 100% reproduce this, @keford<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeford&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337948600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BNoYJGFuJcSUpM2SkklZnP96IaUQFxa78oxD04LFmUg%3D&reserved=0> can you please try with VS Code insiders https://code.visualstudio.com/insiders/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Finsiders%2F&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337998586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ngbimgiemp2j%2FHG5gtkHM84laCmJQdmeOLQ%2BcY86js0%3D&reserved=0>

Can you reproduce for any file? How about an untitled file with the follow content

first line

second line |cursor

Do you get the suggest widget in between that might confuse VoiceOver since the TextBox got refocused?

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F140220%23issuecomment-1006676267&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337998586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WVs6%2BedgXB3m1907Mkpkyb8YN9czwETcjFau8mQC5IU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT2VAIQAPTGIO4NIXRADQY3UUWXYPANCNFSM5LMP2M7Q&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337998586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VAt5RvgVcAtWFMq%2BPPiVG4vtLnWmFFVgxyDVtYCnOZ0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337998586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R84vFb90AqHNHtJ3xLq2gv5DHfmtdCzkzRFEtZhNRZA%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckeford%40microsoft.com%7C3962d9b9bfd04bb20fd808d9d1288b8d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637770794337998586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gwxdhJInLMKBJWJb%2BtCLLFau7Z0NnzJNy%2BFgwxEqpsA%3D&reserved=0>.

**Comment by Ashwinipola26** [comment] 2022-01-07 10:52
GitHubTags:#A11y_Visual Studio Code Client;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#Visual Studio Code Client;#WCAG1.3.1;#Info and Relationships;#MAC;#AINotInScope;#VoiceOver;#BM-VisualStudioCodeClient-MAC-Aug2021;

**Comment by isidorn** [comment] 2022-01-20 11:20
Our friend from VoiceOver found that "VS Code is incorrectly posting AXMenuOpened and AXMenuDestroyed notification each time user types a character, even though there’s no actual menu presented visually".
So it seems like the suggest widget or some other menu quickly shows and hides, but it is not visible. I tried to debug, but could not figure out which menu it is.

I am suspecting it is the suggest widget.
@jrieken can you please give this a try? Steps in my [comment above](https://github.com/microsoft/vscode/issues/140220#issuecomment-1006676267). So we are looking for a menu that might get rendered and disposed so it confuses VoiceOver.

**Comment by pitermach** [comment] 2022-01-20 15:13
That sounds about right, because every time this happens VoiceOver plays the "Menu opened" sound effect. Also, this problem seems to occur only if you type at the end of the file.

From my testing previous versions while reporting #131866, this issue was introduced with Code 1.59, version 1.58 doesn't exhibit this. It may be also related to chromium/Electron, because I've seen the menu sound playing over and over when typing in at least one more place (the Discord app) though there it only happens in the quick switcher box so it's less annoying.

**Comment by alextraub** [comment] 2022-01-23 00:15
I have encountered the same issue, although it happens consistently. 

Steps to reproduce:
1. Open any file in the editor
2. Type some non-whitespace characters
3. Type a space, delete the space, and type another space

This will cause all the text left of the cursor, up to the next whitespace character, to be duplicated.

**Comment by jrieken** [comment] 2022-01-27 14:27
@keford @pitermach We could still not quite yet reproduce this issue. I would like to narrow down on quick suggestions  - those show while typing and it's likely that the "to be typed word" is shown there. For now my ask is to try with this quick suggestions disabled, via `"editor.quickSuggestions": false` in settings.json. If the problem then goes away, we know it's quick suggestions. Thanks

**Comment by isidorn** [comment] 2022-01-27 15:25
In order to generalise this problem: how do users feel with the current suggest and editor interaction. This is very similar with NVDA (whenever suggest widget gets closed the editor label + line is re-read).
So my questions are:
1. When you explicitly open the suggest widget and you close it do you expect that the screen reader reads the editor label + content?
2. When the suggest widget opens automatically and closes - is it a bad experience that the editor content gets re-read?

My feeling is that in both cases the editor content should not be re-read and this is just noise. But would like to hear thoughts @jvesouza @zersiax @marcozehe @neurrone

@joanmarie Orca is behaving great here. Can you share what is your strategy with re-reading textarea content on focus so hopefully we influence other screen readers to do the same.

**Comment by Neurrone** [comment] 2022-01-27 15:28
I'm in favour of not reading automatically when the widget closes. I may change my mind when actually using it in the field, but this requires less effort to implement so I'm thinking we could start there and iterate as needed.

**Comment by isidorn** [comment] 2022-01-27 15:34
@Neurrone well the current behaviour is to read. And to not read might need change from the screen reader side. So that is why I would like to hear thoughts.

**Comment by zersiax** [comment] 2022-01-27 15:36
I would agree, this getting read each and every time is noise that doesn't help anything :)

**Comment by pitermach** [comment] 2022-01-27 15:53
@jrieken I changed the option to false and the issue is still happening.

To your other question, I do agree that there is a lot of noise at the moment which is down to the suggested accessible auto complete pattern. It's worth noting that native Windows/Mac apps handle auto complete scenarios much more gracefully and perhaps there should be some kind of aria spec to tap into those API's to avoid this in the future, but that's a topic for the people in charge of the spec :)

I liked when VSCode used to use a live region for autocomplete announcements, but I realise this doesn't work as well for braille displays. Perhaps having an option to select between the current system of focusing a list box or using live region announcements would be a good compromise?

**Comment by MarcoZehe** [comment] 2022-01-27 16:29
On Windows, the only two places I have seen autocomplete implemented well are:

1. The Start menu search box, when you start typing something, NVDA makes this ascending whooshing sound and reads the suggested results. If none is chosen, or continuing to type, and no results are available any more, the whooshing sound is descending, and focus remains in the text field without extra babble.
2. The NotePad++ editor and Derek Riemer's [accompanying NVDA add-on](https://addons.nvda-project.org/addons/notepadPlusPlus.en.html). That employs a similar behavior, by capturing the autocomplete suggestions and emulating the ascending and descending sounds, and speaking and brailling of auto suggest results.
On the Mac, as was suggested earlier, native apps handle this gracefully, with true popovers and such that fire the appropriate AX events when appearing and disappearing, without causing focus to jump back and forth overzealously. These aren't menus, but other kinds of popovers for which I am not sure there are WAI-ARIA equivalents yet. Like for the Windows and NotePad++ autocompletes, TBH. NotePad++ is also no Electron app, but mostly native components with a Scientilla edit box.

The way it is now -- and I haven't used VS Code in a while or I would have complained about it earlier -- it is definitely not a good user experience on both Windows and Mac. For Linux, since @joanmarie knows best what roles to use and events to fire, and because she's a Chromium contributor, I'm sure she made sure Chromium fires the events Orca likes. ;-)

Hope the above add-on and hint at NotePad++, which is available as open source, can help figure this out.

**Comment by pitermach** [comment] 2022-01-27 17:34
Screen recording is [here](https://cloud.tardis.pw/f/0d0756a32c9a4cbbb1d6/) - it was slightly too large for GH so had to put it somewhere else.

IIRC from the change logs from Joseph Lee's Windows 10 essentials NVDA add-on, UIA has something for auto complete suggestions as well, that's what the start menu uses and you could also see it in the Win 10 Mail app, Legacy Edge did it as well.

**Comment by MarcoZehe** [comment] 2022-01-27 17:42
So it is possible the UIA implementation in Chromium already fires those events. But because this is still incomplete, both JAWS and NVDA still use the IAccessible2 implementation to access Chromium instead. So, that version doesn't get these events, if they even exist there.

**Comment by isidorn** [comment] 2022-02-22 14:57
Thanks everybody for chiming in.
To clarify, there are two distinct issues here:
1. VoiceOver reads the whole editor title and editor content whenever editor gets focus (even if suggest widget gets closed)
2. VS Code seems to sometimes show and hide a menu very quickly when typing. Leading to editor re-focusing thus showing behaviour under 1

For 1 VoiceOver engineers informed me they are looking into a fix for this
For 2 we need better reproducable steps. @pitermach @keford can you reproduce this with latest [VS Code insiders](https://code.visualstudio.com/insiders/). Since we can not.

Since there are currently no action items on the VS Code side unassigning @jrieken and assigning to Backlog.

**Comment by pitermach** [comment] 2022-03-18 14:10
So I haven't needed to use Code in a while, but I just did some work on the latest Insider version now on Mac OS 12.3, and the issue seems to be gone. It's still happening on the stable version, but in the insider even after multiple restarts of VoiceOver and the code app it hasn't come back.


Version: 1.66.0-insider
Commit: d572d6e9d1282b352227916cb8f95bb2b03ddcaa
Date: 2022-03-18T05:27:56.753Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

**Comment by isidorn** [comment] 2022-03-18 17:55
@pitermach this is great to hear. It seems like the Electron 17 update fixed it.
Let's optimistically close this, and if other users are still seeing this we can reopen. Just comment here. Thanks!

**Closed by isidorn** 2022-03-18 17:55 UTC
Labels: upstream, macos, accessibility, a11ymas

**Comment by keford** [comment] 2022-03-18 20:52
I am no longer reproducing this on the Insider build but there seem to be new issues with the autosuggest items reading.  There is no indication when these appear.  If you down arrow, they are read but nothing is telling you that these have appeared.

Kelly


From: pitermach ***@***.***>
Date: Friday, March 18, 2022 at 9:10 AM
To: microsoft/vscode ***@***.***>
Cc: Kelly Ford (CELA) ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] VoiceOver screen reader repeating all text entered with each character typed on Mac VS Code (Issue #140220)

So I haven't needed to use Code in a while, but I just did some work on the latest Insider version now on Mac OS 12.3, and the issue seems to be gone. It's still happening on the stable version, but in the insider even after multiple restarts of VoiceOver and the code app it hasn't come back.

Version: 1.66.0-insider
Commit: d572d6e<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fcommit%2Fd572d6e9d1282b352227916cb8f95bb2b03ddcaa&data=04%7C01%7Ckeford%40microsoft.com%7Cd6871ad8d54d448d713f08da08e917d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637832094467107602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N9KTDHH7Y4nBKteOgaogdMCwcyCwyrQMVnDiAtLAKZk%3D&reserved=0>
Date: 2022-03-18T05:27:56.753Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

**Comment by isidorn** [comment] 2022-03-21 09:23
@keford would you mind opening a new issue for this? We would really appreciate it. Thanks!

**Comment by keford** [comment] 2022-03-21 13:00
I filed this as:

https://github.com/microsoft/vscode/issues/145550

Kelly

From: Isidor Nikolic ***@***.***>
Date: Monday, March 21, 2022 at 4:23 AM
To: microsoft/vscode ***@***.***>
Cc: Kelly Ford (CELA) ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] VoiceOver screen reader repeating all text entered with each character typed on Mac VS Code (Issue #140220)

@keford<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeford&data=04%7C01%7Ckeford%40microsoft.com%7Cc3d15fc97ac24482f99d08da0b1c844f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637834514354062265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1Tkz44tNIRXprZ4kZqL1QSQ0OceA4qfN2tssNVObO%2Fs%3D&reserved=0> would you mind opening a new issue for this? We would really appreciate it. Thanks!

**Comment by isidorn** [comment] 2022-03-21 13:06
@keaford thank you. I have commented on that issue.
