### ISSUE TITLE
Distribute 64bit Windows

### ISSUE THREAD

**Issue by ChristopherGLewis** [Microsoft/vscode#3977] opened 2016-03-10 19:31 UTC
VS Code 64 bit compile is desperately needed.

When you use the explorer extension "Open with Code" and are looking at files in c:\windows\System32 on a 64 bit OS, the File System Redirector gets in the way and sends you to the SysWOW64 directory, which may not contain your file.  UX is horrible.

For example, right click on C:\Windows\System32\BestPractices\v1.0\Models\Microsoft\Windows\WebServer\WebServer_Model.ps1 and select "Open with Code"

Code starts, but has a blank file in the editor that's dirty and ready for a save.

Since the 64 bit Explorer doesn't populate the SysNative tree there's no way to use the explorer extesion on this and similar files.

**Comment by gerane** [comment] 2016-06-13 12:30
This is bigger than just open, it will also create new files under the wrong directory, and save files under the wrong directory.

There are also issues with extensions. Take the Powershell Extension and PowerShell Editor Services(PSES). Through the PowerShell Extension, you can use PSES to write Editor Commands in  PowerShell and then execute them through the Command Palette. PSES properly hadnles 64 bit, but when it hands off to the editor, Code can't handle the translation.

A potential huge issue is editing a file under system32, and its editing the wrong file entirely and could potentially have a major impact on the user's system.

**Comment by joaomoreno** [comment] 2016-07-05 13:30
Duplicate of #507

**Closed by joaomoreno** 2016-07-05 13:30 UTC
Labels: feature-request
