### ISSUE TITLE
scroll to next/previous command should be circular

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141759] opened 2022-01-28 20:14 UTC
to be consistent with Monaco per feedback from @rebornix

**Comment by rebornix** [comment] 2022-01-28 20:18
The command name is `scroll to previous command` so to me it should always reveal it into view no matter the scroll top of the terminal.

**Comment by Tyriar** [comment] 2022-01-31 17:56
Closing as designed since the behavior seems more natural to me, it also matches Terminal.app

**Closed by Tyriar** 2022-01-31 17:56 UTC
Labels: polish, terminal
