### ISSUE TITLE
support for long / asynchronous call stacks in Node.js debugger

### ISSUE THREAD

**Issue by jokeyrhyme** [Microsoft/vscode#7507] opened 2016-06-09 23:31 UTC
- VSCode Version: `code --version` -> 1.3.0-insider
- OS Version: OS X 10.11.6 Beta (15G12a)

Steps to Reproduce:

1. start with this code

    ```js
    setTimeout(() => {
      Promise.resolve()
        .then(() => {
          throw new Error('catch me!')
        })  
    })
    ```

2. set a breakpoint on the `throw`, and debug in VSCode (as a Node.js project)

    ![screen shot 2016-06-10 at 09 19 15](https://cloud.githubusercontent.com/assets/479816/15949712/e93ec410-2eec-11e6-9225-e2ed32b36732.png)

    - observe that the Call Stack lists just a single frame.

3. debug this in Chrome, with DevTools, with "Async" checked (near the Call Stack and Breakpoints lists)

    ![screen shot 2016-06-10 at 09 19 05](https://cloud.githubusercontent.com/assets/479816/15949755/3bf4c98e-2eed-11e6-8924-faa2339c6f0a.png)

    - observe that the Call Stack lists multiple asynchronous frames

Whilst researching this, I did come across a similar feature request for node-inspector:

- https://github.com/node-inspector/node-inspector/issues/340

Being able to easily trace the asynchronous flow leading up to an exception (or a breakpoint) is an incredibly powerful tool in the JavaScript developer's arsenal.

It is interesting to note that this is not on by default in Chrome DevTools. Perhaps having this on all the time has considerable performance ramifications? I've had "Async" checked ever since it was announced, but I can imagine a release that turns this on by default could be met with developer confusion / frustration.

Would following Chrome's lead here and just providing a checkbox (or a flag in the debug configuration JSON) be the best initial approach?

**Comment by weinand** [comment] 2016-06-13 08:29
duplicate of https://github.com/Microsoft/vscode/issues/5552

**Closed by weinand** 2016-06-13 08:29 UTC
