### ISSUE TITLE
Cannot paste in search field because webview steals the paste

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#132641] opened 2021-09-08 11:40 UTC
```
Version: 1.61.0-insider (user setup)
Commit: 34861b8c8aa76b517f203743ad5b5d72ef5fcd81
Date: 2021-09-08T05:17:18.073Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
* I was selfhosting, I checkout a PR, then another one, then another one...
* I then moved away from the PR webview editor to another editor (I don't remember exactly what steps I took)
* I can no longer paste in e.g. the search viewlet
* The reason is because the `webview` handler for `Paste` takes over.
* Here is the log output after enabling the trace log level and the keyboard troubleshooting command:
```
[2021-09-08 13:33:18.400] [renderer6] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyV, keyCode: 86, key: v
[2021-09-08 13:33:18.400] [renderer6] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyV, keyCode: 52 ('V')
[2021-09-08 13:33:18.400] [renderer6] [info] [KeybindingService]: | Resolving ctrl+V
[2021-09-08 13:33:18.400] [renderer6] [info] [KeybindingService]: \ From 4 keybinding entries, matched editor.action.clipboardPasteAction, when: no when condition, source: built-in.
[2021-09-08 13:33:18.400] [renderer6] [trace] KeybindingService#dispatch Ctrl+V editor.action.clipboardPasteAction
[2021-09-08 13:33:18.400] [renderer6] [trace] CommandService#executeCommand editor.action.clipboardPasteAction
[2021-09-08 13:33:18.401] [renderer6] [trace] Executing Command 'editor.action.clipboardPasteAction' which has 6 bound.
[2021-09-08 13:33:18.401] [renderer6] [trace] Command 'editor.action.clipboardPasteAction' was handled by 'webview'.
[2021-09-08 13:33:18.631] [renderer6] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
[2021-09-08 13:33:18.934] [renderer6] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/132502164-aa89d020-f222-4a3b-b66e-55b035193335.gif)

The handler comes from [here](https://github.com/microsoft/vscode/blob/7392504f85d49732003f1e031c75e63fafae4de2/src/vs/workbench/contrib/webview/browser/webview.contribution.ts#L17-L38). It looks like there `IWebviewService.activeWebview.isFocused` evaluates to true even when the focus is somewhere else on the page.

> Note: After clicking on the webview editor tab and back in the search viewlet, paste works again, so presumably `IWebviewService.activeWebview.isFocused` now returns false again correctly.

Giving this important as we constantly have people complaining about Paste not working and it is just a huge burden on me to always get these issues. If `IWebviewService.activeWebview.isFocused` cannot be trusted, the command implementation that you register could just look at the `activeElement` and make a decision based on that.

**Comment by alexdima** [comment] 2021-09-08 14:26
@IllusionMH Thanks for trying to reproduce, although I could not find any clear steps. I am on latest Insiders from 9hrs ago.

**Comment by TylerLeonhardt** [comment] 2021-09-30 17:35
@alexdima duplicate of https://github.com/microsoft/vscode/issues/132641 ?

**Comment by alexdima** [comment] 2021-09-30 18:41
@TylerLeonhardt I have really tried to, but I do not understand the issue https://github.com/microsoft/vscode/issues/110528 . From my latest understanding it seemed that pasting works, but <kbd>Enter</kbd> does not work for them. In any case, I could never reproduce anything.

My understanding comes from https://github.com/microsoft/vscode/issues/110528#issuecomment-857541875 :

> The problem is not in pasting some text in some filed, but in entering it as in input. With pressing ENTER key which is not applicable to markdown.

**Comment by rebornix** [comment] 2021-10-01 16:46
Ran into this when following Live Preview's readme https://github.com/microsoft/vscode/issues/134292

**Closed** 2021-10-04 15:13 UTC
Labels: important, webview
