### ISSUE TITLE
Color selector pop-up disappearing after selecting a color in color slider

### ISSUE THREAD

**Issue by mackio-0** [microsoft/vscode#197432] opened 2023-11-04 07:32 UTC
Type: <b>Bug</b>

## Step-1
Add css color value (RGB, HSL, HEX) in a css file.  Then hover over said color to get color selector pop-up.

## Step-2

On right side of the pop up there are two sliders, rightmost one is for selecting color and left one before it is opacity selector. Click a value on opacity slider then click a color on color slider.

## The result

Instead of getting the color what you want, the pop-up will disappear and the color you selected is not applied. It is the same for opacity slider except that after pop-up disappear, the opacity you selected is added to original color value.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:28:21.782Z)
OS version: Linux x64 6.2.0-36-generic snap (Ubuntu 22.04.3 LTS, GNOME version 42.9)
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3249)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (10.22GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 57e5d36b-af69-456f-a8d8-95888be77c29|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
tailwind-documentation|alf|0.1.14
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.10.3
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
arrow-function-snippets|dei|3.5.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.4.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
better-cpp-syntax|jef|1.17.2
tailwind-config-viewer|Kal|0.0.85
tailwindcss-kit|Kal|1.0.4
vscode-scss|mrm|0.10.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.31.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
tailwind-fold|sti|0.1.0
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
console-ninja|Wal|1.0.250
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054

```

</details>

**Comment by aiday-mar** [comment] 2023-11-20 08:37
duplicate of https://github.com/microsoft/vscode/issues/197588#issuecomment-1818450461

**Closed by aiday-mar** 2023-11-20 08:37 UTC
