### ISSUE TITLE
Fuzzy search doing a bad job of prioritizing search results

### ISSUE THREAD

**Issue by PaddyMann** [Microsoft/vscode#35572] opened 2017-10-04 12:59 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
prettier-vscode|esb|0.24.0
atom-keybindings|ms-|3.0.2
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---

Steps to Reproduce:

If you've got a large code base, the fuzzy search picks up too much noise and doesn't prioritize the sensible results.

For example, I have a file `settings.html` that's in a directory called `participants`. So I search for `parti settings`.

Here's what VSCode shows:
![image](https://user-images.githubusercontent.com/362711/31176719-18c1a692-a914-11e7-97bd-4c785025d48d.png)

vs. Atom (with the file I'm after listed second):
![image](https://user-images.githubusercontent.com/362711/31176763-41b1dc3e-a914-11e7-9740-65177e18cf17.png)

This seems to have been an issue for a long time, but related issues have been closed without fixing it. e.g. https://github.com/Microsoft/vscode/issues/968

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-10-05 08:35
@PaddyMann did some tweaks in this area this week, can you either let me know if I could access the same sources (if open source) or give this insider build a try on it: https://az764295.vo.msecnd.net/insider/2e2613f7739c31832496f617356f5fb8eadc2ca1/VSCode-darwin-insider-unsigned.zip

**Comment by PaddyMann** [comment] 2017-10-05 08:54
You legend @bpasero - that works a treat 😄 

![image](https://user-images.githubusercontent.com/362711/31218697-6fb9cd9c-a9bb-11e7-9551-736ca8c2638a.png)

I'm not familiar with your release cycles - when will this drop into a full release?

**Comment by bpasero** [comment] 2017-10-05 09:04
@PaddyMann unfortunately another month because we just wrapped up our 1.17 release. But you can stay on our insider releases, they are typically quite stable.

Marking as duplicate of https://github.com/Microsoft/vscode/issues/34210

**Closed by bpasero** 2017-10-05 09:04 UTC
Labels: needs more info, quick-pick, workbench

**Comment by fluffynuts** [comment] 2017-10-20 08:20
This is a great improvement over the existing search! Would it be possible to have some way to make this search box wider? I have a rather deep solution, such that file searches, which are making far better hits now, are still not obvious until I mouse over each entry in the list to get the full text. At the moment. this search box only takes up like 1/4 of the width of my screen -- I have plenty of screen real estate which could make this easier to read, if I could just resize the box...

**Comment by sluongng** [comment] 2017-10-22 11:38
I have not follow discussions about this for long but have you guys considered giving user the option to choose their own search implementation? 

For example I want to use https://github.com/junegunn/fzf/ or https://github.com/lotabout/skim.

I wish to have configurable search options, similar to configurable run/debug settings. There I can link the search call to my own binary(ies) with parameters to further customize the search.

**Comment by grothkopp** [comment] 2017-10-25 10:14
<img width="624" alt="bildschirmfoto 2017-10-25 um 12 02 21" src="https://user-images.githubusercontent.com/25702/31993294-00eeeba0-b97d-11e7-89bd-b1e73770a641.png">
@bpasero I downloaded your insider build, but my results were not as great.
As you can see in the screenshot I have a directory named "lioshop" but the files in there are only listed on position 11 & 12 and not even all of them.
Here are some suggestions to improve the matching:
- make it "greedy". In the screenshot of @PaddyMann settings should match settings in settings.js and not setting + the s in the extension.
- make a priorisation like: 
1) longest match in file or path ("lioshop")
2) matching uppercase characters or first character in files (No one would probably search for ListOffersHistoryResponse by entering "lioshop", but "lohr" or "listhr")

**Comment by bpasero** [comment] 2017-10-25 10:22
@grothkopp this is a consequence of us always treating a match in the file name higher than anything else. There is still https://github.com/Microsoft/vscode/issues/25925 opened to cover that case.
