### ISSUE TITLE
Auto format code incorrectly with .js in React -native project.

### ISSUE THREAD

**Issue by hieutranagi47** [Microsoft/vscode#11619] opened 2016-09-07 07:50 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. I try to create a component:
// Create a react component.
var Weekdays = React.createClass({
    render: function() {
        return <View >
            < Text style = "red-color" >
                Day of the week:
            < /Text>
        < /View>;
    }
});
2. When I prompt Ctrl+S to save, the source code looks like so bad.
https://facebook.github.io/react-native/docs/tutorial.html

Please take a look at my issue, and let me know how to declare a new dom (ie <Text>  to help the code editor does not show me as an error ).
Thanks,
Hieu Tran

**Comment by ramya-rao-a** [comment] 2016-09-07 21:53
@hieutranagi47 I tried the sample code from the link you have mentioned (https://facebook.github.io/react-native/docs/tutorial.html), and things look good to me.

![image](https://cloud.githubusercontent.com/assets/16890566/18329953/e09b0ad0-750a-11e6-931c-e4bc98cb982c.png)


Can you provide a screenshot of your code and the formatting problem?

**Comment by hieutranagi47** [comment] 2016-09-08 04:46
Thanks Ramya,
Please take a look at my attached files.
![ctrl_s_prompt](https://cloud.githubusercontent.com/assets/15606737/18337342/d94060c8-75b9-11e6-8468-3e3ea18784c7.png)
![ctrl_z_it_should_be](https://cloud.githubusercontent.com/assets/15606737/18337341/d940515a-75b9-11e6-9d07-e18e9c105ac9.png)

**Comment by hieutranagi47** [comment] 2016-09-08 05:01
You can try to add some new code, then you prompt Ctrl+S to save it.

**Comment by ramya-rao-a** [comment] 2016-09-08 21:15
From your screenshots, after Save, there seems to be 1 red squiggly line in line 18.
Is that the problem?
When you hover on it, what does it say?

**Comment by hieutranagi47** [comment] 2016-09-09 03:56
![error-hint](https://cloud.githubusercontent.com/assets/15606737/18374986/f3b0b396-767b-11e6-941a-e41fc32f2d12.png)
I attached it, pleaes take a look at it.

**Comment by ramya-rao-a** [comment] 2016-09-09 04:07
Which extensions are you using?

**Comment by hieutranagi47** [comment] 2016-09-09 04:13
jshint 0.10.15 - Dirk Beaumer, downloaded: 58735, rate: 4.5 stars.
Currently I installed so many extensions into VSC.
![extensions](https://cloud.githubusercontent.com/assets/15606737/18375225/63b13970-767e-11e6-8033-3088377ad9df.png)

**Comment by ramya-rao-a** [comment] 2016-09-09 04:20
Since the error is coming from jshint, please move this issue to the repo for the extension for jshint. They would best be able to tell if this is caused by the extension or any of the VS Code APIs

**Comment by hieutranagi47** [comment] 2016-09-09 04:25
Ok! Thank Ramya so much!

**Comment by ramya-rao-a** [comment] 2016-09-09 04:39
@hieutranagi47 Closing this issue for now. We can reopen it if the extension authors get back saying that the problem is not with the extension

**Closed by ramya-rao-a** 2016-09-09 04:39 UTC
Labels: needs more info
