### ISSUE TITLE
File tab bar queues mouse middle clicks while modal dialog is active

### ISSUE THREAD

**Issue by zneak** [Microsoft/vscode#32991] opened 2017-08-22 23:35 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. Open new Code window
2. Create one new document and add any content to it, without saving
3. Create another new document and also add any content to it
4. Middle-mouse-click either document. A modal dialog appears asking if you want to close without saving. Do not dismiss it.
5. Middle-mouse-click the other document while the modal dialog is visible.
6. Dismiss the modal dialog using "Don't save" or "Cancel" (save probably works too, but I haven't tried it).

Expected behavior: while the modal dialog is active, events to the blocked window are discarded. When the modal dialog is dismissed, the second document to be middle-clicked is still alive and well.

Actual result: immediately after the modal dialog is dismissed, another one appears asking what to do with the second document that was middle-clicked, confirming that events are queued instead of discarded. This seems to work with an arbitrary number of documents. I have not tested other interactions (like double-clicking the tab bar to create a new document).

Other UI elements, like the file panel of the left bar, are blocked.

Reproduces without extensions: Probably? Don't think the Python extension impacts this.

**Comment by yume-chan** [comment] 2017-08-23 00:48
Duplicate of #31810, #11928

**Comment by Tyriar** [comment] 2017-08-23 15:33
Thanks @yume-chan :smiley:

**Closed by Tyriar** 2017-08-23 15:33 UTC
Labels: new release
