### ISSUE TITLE
Getting Started: Markdown images are relative to root, not the actual markdown file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122091] opened 2021-04-24 09:25 UTC
I had this structure:

./getting-started/1-image-editing-basics.md
./images/getting-started/history.png

I expected this to work but it didn't:

```
![](../images/getting-started/history.png)
```

This does work though, which won't work in the actual markdown preview when developing the markdown file:

```
![](images/getting-started/history.png)
```

**Comment by JacksonKearl** [comment] 2021-04-26 03:02
Good idea, thanks

**Comment by connor4312** [comment] 2021-04-30 21:58
I'm not sure how to test this / how the .md file is displayed, the API in https://github.com/microsoft/vscode/issues/119097 only defines descriptions inline in the package.json

**Comment by JacksonKearl** [comment] 2021-04-30 22:13
You can use a path ending in ".md": https://github.com/JacksonKearl/md-to-html/blob/main/package.json#L42

**Comment by connor4312** [comment] 2021-05-05 17:34
I tried to verify this by:

1. Taking the luna paint extension
2. Moving the getting started images to `Tyriar.luna-paint-0.5.0/extension/images`
3. Updating the paths, so for example `Tyriar.luna-paint-0.5.0/getting-started/2-pencil-tool.md` referenced `![](../images/2-pencil-tool.png)`
4. This resulted in a 404 at `https://eeddb5dd-130a-4150-9d4d-0f26e40335b0.vscode-webview-test.com/vscode-resource/file///c%3A/Users/Connor/.vscode-insiders/extensions/tyriar.luna-paint-0.5.0/images/2-line-preview.png` (thought that file exists)

**Comment by connor4312** [comment] 2021-05-05 17:35
However the default state in a subdirectory _did_ work... so the title of the issue is fixed in that they appear relative, but I'm guessing the extension root is not allowed to load in the webview

**Comment by JacksonKearl** [comment] 2021-05-05 17:38
Hm... we block access to resources above the markdown file itself via setting the webview's `localResourceRoots` to the markdown file's directory. But I see how this would be nice to have, `localResourceRoots` should probably be the extension's directory.

**Closed** 2021-05-06 23:34 UTC
Labels: bug, getting-started
