### ISSUE TITLE
Git doesn't work any more.

### ISSUE THREAD

**Issue by yPangXie** [Microsoft/vscode#24431] opened 2017-04-10 11:27 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|html-css-class-completion|Zignd|1.0.3|
|file-icons|file-icons|1.0.3|
|auto-rename-tag|formulahendry|0.0.11|
|path-autocomplete|ionutvmi|1.4.1|
|docthis|joelday|0.4.3|
|Go|lukehoban|0.6.59|
|vscode-icons|robertohuertasm|7.5.1|
|guides|spywhere|0.7.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Upgrade to v1.11.1
2. Open an git repo with some files untracked
3. Open the git tab from the left tab list
4. No files can be shown up in this tab.

After upgraded to the latest version(v1.11.1), I noticed that the git tab doesn't work any more, no more data can be shown up except a title "SOURCE CONTROL" and an empty input fields with a placeholder like the screenshot below.

Have tried to remove all the extensions and delete all my custom settings, git doesn't come back.

![image](https://cloud.githubusercontent.com/assets/12368943/24859526/8b1b7f00-1e23-11e7-82a9-b9d53774ec5c.png)

**Comment by Nikki1993** [comment] 2017-04-10 11:37
Can't reproduce. Works perfectly fine for new or old projects for me on macOS 10.12.4

Dumb question, do you have git installed? via homebrew or manually otherwise?

**Comment by yPangXie** [comment] 2017-04-10 12:59
Actually, It works well before upgrading to v1.11.1 and I didn't do anything else manually. It's an odd case..

**Comment by yPangXie** [comment] 2017-04-10 13:09
![image](https://cloud.githubusercontent.com/assets/12368943/24863067/e6fa5df6-1e31-11e7-9896-8b4165f14e5c.png)

Open "Developer Tools" and an error message was threw out

**Comment by joaomoreno** [comment] 2017-04-10 13:39
Thanks for the log!

**Comment by joaomoreno** [comment] 2017-04-10 13:45
I'm gonna ask you to do some surgery.

Please open the `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/out/askpass.js` file, go to line 20 and change

```ts
this.server.listen(0, 'localhost');
```

to

```ts
this.server.listen(0);
```

Does that make it work?

**Comment by yPangXie** [comment] 2017-04-10 13:52
The error message has gone, but git doesn't come back.

**Comment by joaomoreno** [comment] 2017-04-10 14:04
If you run `SCM: Switch SCM Provider`, do you see Git in the list?

**Comment by yPangXie** [comment] 2017-04-10 14:07
Nope, so there should be something wrong, right? @joaomoreno

**Comment by joaomoreno** [comment] 2017-04-10 14:09
I'm guessing there are no more errors in the dev tools?

**Comment by joaomoreno** [comment] 2017-04-10 14:10
Wanna do a live debug session? https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode24431

**Comment by yPangXie** [comment] 2017-04-10 14:16
Yes, no more error with dev tools.

But, sorry bro, it's not very convenience to do so since I am still working at office, how about to schedule another time, maybe the same time tomorrow?(I am in GMT+0800)

**Comment by joaomoreno** [comment] 2017-04-10 14:22
Yeah let's do that: 14:00 UTC time, same meeting URL.

**Comment by yPangXie** [comment] 2017-04-10 14:24
Thanks so much, U R awesome

**Comment by Earl-Brown** [comment] 2017-04-10 15:32
I am experiencing the same symptoms.

This is on my home computer - but my work computer is just fine.

Is there anything I could do to provide more clues?

**Comment by yPangXie** [comment] 2017-04-10 17:02
@joaomoreno Guess what, Git comes back after I did the steps below.

1. Disable Preview SCM
2. Enable Preview SCM

Done. 😂

**Comment by joaomoreno** [comment] 2017-04-10 17:53
Interesting! But it doesn't really make much sense... any chance you can get it back to the buggy state?

**Comment by TravisJN** [comment] 2017-04-10 21:16
I've had the same problem since updating to `1.11.1`. Disabling Preview SCM made everything work again (Thanks @yPangXie) but if I try to enable Preview SCM the issue comes back. Hope this info helps

**Comment by Earl-Brown** [comment] 2017-04-10 23:58
Nope, that didn't do it.

But I noticed "Switch SCM Provider" and when I selected that, I got "there are no entries to pick from"

That seems like a good reason for things to be misbehaving!

**Comment by LeCoupa** [comment] 2017-04-11 00:32
I had the same issue. @yPangXie's commands made the trick.

**Comment by yPangXie** [comment] 2017-04-11 01:30
@joaomoreno The bug will be back after "Enable Preview SCM", the same as @TravisJN

**Comment by keller35** [comment] 2017-04-11 02:49
I met the same issue, and it also work after setting "Enable Preview SCM".

**Comment by joaomoreno** [comment] 2017-04-11 06:20
@yPangXie Oh, so it didn't work for you?

@keller35 But it did for you?

You guys are really confusing me.

**Comment by guhuajun** [comment] 2017-04-11 07:23
I am satisfied after disabling preview SCM. The preview SCM consumes a lot of CPU.
@joaomoreno If you are developing vscode on Windows, you can use procexp.exe (https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) from Mark Russinovich to observe the behavior, vscode are creating a lot of git processes.

![default](https://cloud.githubusercontent.com/assets/14121694/24897042/f72f1368-1ec9-11e7-87b8-be2cff72621c.png)

**Comment by yPangXie** [comment] 2017-04-11 11:48
@joaomoreno It works for me after disabled preview SCM. And the bug will be back if I re-enabled preview SCM.

**Comment by NathanJPhillips** [comment] 2017-04-11 15:25
Is this issue related? https://github.com/Microsoft/vscode/issues/24516

**Comment by calebfaruki** [comment] 2017-04-13 03:37
When using Git with VSCode, you should make sure that you've installed Git so that it is available from Windows Command Prompt. Try reinstalling Git and checking the following option:
![screenshot](https://cloud.githubusercontent.com/assets/5914427/24989193/f7ca3770-1fd8-11e7-93d1-9c002fac3749.png)

**Comment by spademan** [comment] 2017-04-15 03:37
the same issue, but it only work when 'Disable Preview SCM',
it sick 😷  after i switch to  'Enable Preview SCM',

**Comment by Cldfire** [comment] 2017-04-17 01:15
Going to chime in and say that Git integration stopped working for me on Ubuntu 16.04 after the 1.11 update and that running `Disable Preview SCM` has returned Git integration to a working state for me as well.

Before running `Disable Preview SCM`, VS Code would not seem to recognize that a folder that contained a Git repo actually contained a Git repo, but for some odd reason would occasionally decide that there was indeed a repo after some random amount of time.

**Comment by joaomoreno** [comment] 2017-04-18 07:25
Guys, can you try out the latest [insider release](https://code.visualstudio.com/insiders)? Does it work for you?

**Comment by NathanJPhillips** [comment] 2017-04-18 10:06
Sorry for not testing that last week. Been busy. I can confirm that the 1.11.2 insider release does not fix it. `SCM: Disable Preview SCM` is a valid workaround for now.

**Comment by joaomoreno** [comment] 2017-04-21 07:18
@NathanJPhillips Let's keep your discussion in #24516

@yPangXie @keller35 @Earl-Brown @spademan Can you try out the latest [insider release](https://code.visualstudio.com/insiders)? Does it work for you?

**Comment by iyutao** [comment] 2017-04-21 08:08
only work after setting "Disable Preview SCM".  

VSCode version:  1.11.2 (1.11.2)
Os Info: OS X EI Capitan 10.11.6 (15G1217)

**Comment by joaomoreno** [comment] 2017-04-21 08:23
@iyutao Can you **please** try out the latest [insider release](https://code.visualstudio.com/insiders)?

**Comment by iyutao** [comment] 2017-04-21 09:37
@joaomoreno   'insider' has  the same problem

**Comment by joaomoreno** [comment] 2017-04-21 09:50
@iyutao Can you show me in a screenshot what exactly is wrong?

**Comment by iyutao** [comment] 2017-04-21 10:02
<img width="1279" alt="tt" src="https://cloud.githubusercontent.com/assets/2640050/25273008/9125f744-26bc-11e7-9e93-842f65dfd4fe.png">

**Comment by joaomoreno** [comment] 2017-04-21 10:47
Awesome. I just fixed that this morning. Does [this build](https://az764295.vo.msecnd.net/insider/6e45311b5781d6550f469d0381d97d0d92e48f6b/VSCode-darwin-insider-unsigned.zip) fix it for you?

**Comment by iyutao** [comment] 2017-04-21 11:06
Wait a moment. 
'this build' need a long time to download..

**Comment by iyutao** [comment] 2017-04-24 02:09
@joaomoreno download failed ...

**Comment by joaomoreno** [comment] 2017-04-24 07:06
How about this? https://az764295.vo.msecnd.net/insider/6e45311b5781d6550f469d0381d97d0d92e48f6b/VSCode-darwin-insider.zip

**Comment by iyutao** [comment] 2017-04-24 07:21
This version work well. Thanks ~

**Comment by joaomoreno** [comment] 2017-04-24 07:47
Closing as there have been many fixes in `master` related to this.

@yPangXie @keller35 @Earl-Brown @spademan Let me know if the [latest insider](https://az764295.vo.msecnd.net/insider/6e45311b5781d6550f469d0381d97d0d92e48f6b/VSCode-darwin-insider.zip) doesn't fix the issue for you.

**Comment by yPangXie** [comment] 2017-05-03 05:46
It works well for me. U r awesome! @joaomoreno

**Closed** 2017-05-04 08:01 UTC
Labels: needs more info
