### ISSUE TITLE
Some menu flashing white while open

### ISSUE THREAD

**Issue by TDL3** [microsoft/vscode#100291] opened 2020-06-16 13:38 UTC
- VSCode Version: 1.46.0
- OS Version: Linux 5.6.16-1-MANJARO x86_64 (manjaro 20.0.3 Lysia gnome edition)

This issue only happens on gnome version of manjaro linux, while kde and xfce versions do not have this issue, and it's a long going one since about 1.13.

Steps to Reproduce:

1. some menu flashing white while open as the gif below showed.

![flashing menus](https://user-images.githubusercontent.com/29535697/84780653-6812fd00-b018-11ea-8065-b8158e956ce2.gif)

Does this issue occur when all extensions are disabled?: No

Log:
`[main 2020-06-16T12:56:50.865Z] update#setState idle
[15349:0616/205650.899935:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:15375) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[15349:0616/205653.768376:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205653.885297:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205654.957437:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205655.581156:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205656.195578:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205656.722492:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205657.255629:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205657.697783:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205658.077685:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205658.635080:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205659.982788:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205701.116226:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205702.693147:ERROR:gles2_cmd_decoder.cc(4927)] [.RendererMainThread-0x2fb2551c0800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[15349:0616/205703.712932:ERROR:gles2_cmd_decoder.cc(4927)] [.RendererMainThread-0x2fb2551c0800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[15349:0616/205711.622361:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[15349:0616/205713.564271:ERROR:gles2_cmd_decoder.cc(4927)] [.RendererMainThread-0x2fb2551c0800]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
[15349:0616/205720.575327:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[main 2020-06-16T12:57:20.872Z] update#setState checking for updates
[main 2020-06-16T12:57:21.201Z] update#setState idle`

**Comment by IllusionMH** [comment] 2020-06-16 13:49
Looks like duplicate of #80798 could you check that one and close this if it's duplicate.

You can also check exploration build from #97270 (comment) to see if it helps (problem looks similar)

**Comment by TDL3** [comment] 2020-06-16 14:18
I've tested exploration build from #97270, and the issue has been fixed

**Comment by TDL3** [comment] 2020-06-16 14:19
> Looks like duplicate of #80798 could you check that one and close this if it's duplicate.
> 
> You can also check exploration build from #97270 (comment) to see if it helps (problem looks similar)

I've tested exploration build from #97270, and the issue has been fixed, thank you :+1:

**Closed** 2020-06-16 14:19 UTC

**Comment by IllusionMH** [comment] 2020-06-16 14:35
Looks like it depends on update to Electron 8, and currently it's in iteration flan for June but might be postponed due to other issues with new Electron.
