### ISSUE TITLE
Add documentation for `vscode-extension-resource`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44858] opened 2018-03-01 18:31 UTC
Extracted from #44677

Currently it's impossible to figure this out by API consumers.
I think the best way would probably be having a `webview-sample` in https://github.com/Microsoft/vscode-extension-samples that uses the proposed API, and put some notes down as MD file there. When it's time we can convert the documentation to a page on the website.

**Comment by mjbvz** [comment] 2018-03-01 18:52
Duplicate of #44739

**Closed by mjbvz** 2018-03-01 18:52 UTC
Labels: webview
