### ISSUE TITLE
Can't reload my old theme settings after update!

### ISSUE THREAD

**Issue by Bayramito** [microsoft/vscode#92788] opened 2020-03-16 14:41 UTC
Hi,

Today i just updated my VSCODE to the latest version avaiable.
But my theme settings, cannot be used after the update. I mean everything looking fine at the beginning but after 4-5 seconds later my color settings changing back again...

**Comment by ekscentrysytet** [comment] 2020-03-16 15:25
Same here, also noticed my Monokai theme colors has slightly changed

**Comment by eddyw** [comment] 2020-03-16 16:05
Same here, I just downloaded the vscode insiders version and it's fixed there .. apparently. I guess we just need to wait until they release it as stable. You could double check if insiders does in fact solve your issues too.

**Comment by aeschli** [comment] 2020-03-16 16:06
See https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting

duplicate of #92308

**Closed by aeschli** 2020-03-16 16:06 UTC
