### ISSUE TITLE
Panes resized after running Insider update

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#79035] opened 2019-08-13 12:32 UTC
Issue Type: <b>Bug</b>

After running the latest update to Insiders, the panes of the window resized to basically all take 1/2 of the screen. The included screenshots show before the update and after. (I didn't get to capture what also happens if the terminal pane was open - that also resizes to be very tall, taking up about 80% of the right pane. Reloading / relaunching does not show this behavior after the update.

VS Code version: Code - Insiders 1.38.0-insider (ffa22b268f451b5211abbe2d2a47e6b753b55b1a, 2019-08-13T07:27:53.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|12.00GB (7.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
ng-template|Ang|0.801.1
vscode-eslint|dba|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
output-colorizer|IBM|0.1.2
Angular2|joh|8.1.1
vscode-peacock|joh|3.0.1
vscode-azurefunctions|ms-|0.17.1
vscode-cosmosdb|ms-|0.10.2
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
vetur|oct|0.22.0
material-icon-theme|PKi|3.8.1
quicktype|qui|12.0.46
fabulous|raa|0.12.0
vscodeintellicode|Vis|1.1.9

(3 theme extensions excluded)

</details>

![before](https://user-images.githubusercontent.com/13488/62941748-cc37b580-bda4-11e9-816c-2c862980c8c7.PNG)

![after](https://user-images.githubusercontent.com/13488/62941752-ce9a0f80-bda4-11e9-80e3-a866d68c1442.PNG)

**Comment by gjsjohnmurray** [comment] 2019-08-13 12:54
Possible duplicate of #79020

**Closed** 2019-08-14 17:53 UTC
Labels: *duplicate
