### ISSUE TITLE
Cannot toggle word wrap in a diff editor

### ISSUE THREAD

**Issue by lijhello** [microsoft/vscode#111141] opened 2020-11-22 17:40 UTC
- VSCode Version:
- OS Version:

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Steps to Reproduce:

1. Compare selected
2. press Option + z

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lijhello** [comment] 2020-11-22 20:21
I have this in User Settings. When option+z is pressed, this setting doesn't change:
    "editor.wordWrap": "wordWrapColumn",

**Comment by gjsjohnmurray** [comment] 2020-11-22 23:07
Diff wrapping is coming in the next release. You can already get it by installing Insiders, which will coexist with Stable.

**Comment by alexdima** [comment] 2020-11-30 20:36
Duplicate of #11387

**Closed by alexdima** 2020-11-30 20:36 UTC
