### ISSUE TITLE
html comments work wrong

### ISSUE THREAD

**Issue by bootster** [Microsoft/vscode#15110] opened 2016-11-07 16:04 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

Steps to Reproduce:

```html
<!---------- this comment cause error --------->
<script src="init.js"></script>
<script src="drag_elem.js"></script>
<script src="create_elem.js"></script>

<!--  normal comment -->
<link rel="stylesheet" type="text/css" href="left/border/border.css">
<script src="left/border/border.js"></script>
```
paste code, see that end of the comment "-->" in first line does not work proper

**Comment by rebornix** [comment] 2016-11-07 16:12
Can you help format your description a little bit to help understand the problem?

**Comment by aeschli** [comment] 2016-11-07 16:20
Check out https://www.w3.org/TR/html5/syntax.html#comments:

> text must not ... contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-)

That's why the comment content is rendered red ('invalid')


duplicate of #13778

**Closed by aeschli** 2016-11-07 16:20 UTC
Labels: needs more info
