### ISSUE TITLE
Can't see what I'm writing in the Search Widget input field

### ISSUE THREAD

**Issue by lucarge** [Microsoft/vscode#33671] opened 2017-09-01 11:14 UTC
- VSCode Version: 1.15.1
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Open the search widget (cmd + F)

Expected Behaviour:

The input field has a reasonable width to see what I'm writing

Detected Behaviour:

The input field is a couple of pixel wide, and seeing what I'm writing is impossible.

Extra Notes:

I've experienced a regression in Version 1.15, since it has always been as expected before. I've also inspected the styles applied to the whole Search Widget, and it looks like the fixed width of 441px for the widget container is causing this issue.

Search widget as it looks on Version 1.15.1

![vscode_with_411px_costrain](https://user-images.githubusercontent.com/25553165/29967492-1b536d58-8f17-11e7-89c0-c4b2576ba3db.png)

Search widget without 411px width costrain

![vscode_without_411px_costrain](https://user-images.githubusercontent.com/25553165/29967493-1b556b80-8f17-11e7-9941-612057d4759b.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-09-01 17:03
Duplicate of #33349 (it starts a little messed up in some languages)

**Closed by roblourens** 2017-09-01 17:03 UTC
Labels: new release, search
