### ISSUE TITLE
Please allow us more flexible custom key binding

### ISSUE THREAD

**Issue by KahnDepot** [microsoft/vscode#136605] opened 2021-11-07 09:22 UTC
Please open more key binding rules!
To give a simple example, I hope to add a new instance window of vscode after pressing the 3 keys of space g n.
But the reality is that the key bindings that are not at the beginning of ctrl or cmd can only support up to 2 items. When you specify the combination of space g, it will stop receiving other sub-options.
This is bad for vim users, because the leader key of vim is very easy to use, but the vscode vim plugin cannot make the leader key valid outside the non-editor area.
This is a proposal worth considering. It is recommended to also add a leader-like key position in vscode to facilitate the operation of full keyboard users or develop more sub-options to receive.

**Comment by KahnDepot** [comment] 2021-11-07 09:27
There are still some users who are willing to define a set of key position rules by themselves instead of using the default ones.

**Comment by yume-chan** [comment] 2021-11-08 02:43
Duplicate of #6966

IIRC vim extension now uses `type` event for chords so it only accept keys in editors. But it may be possible to accept any chords by: 1. use one command for entering chords mode and set context 2. set key bindings with `when` clause and send keys to vim extension

**Closed** 2021-11-09 08:43 UTC
