### ISSUE TITLE
Problem with integrated terminal font rendering between characters in v1.55.2 as compared to v1.54.x 

### ISSUE THREAD

**Issue by MOrlassino** [microsoft/vscode#121551] opened 2021-04-17 13:43 UTC
- VS Code Version: 1.55.2
- OS Version: Windows 10 Professional 19042.928

Steps to Reproduce:

1. Set the VS Code integrated terminal to use 'Fira Code' or another powerline enabled font.  I do not see this issue in Windows Terminal using the same font and same SSH host.
2. Open a terminal that renders lines like that with powerline-go, in my case I was using the "Microsoft Remote - SSH" extension to access a Linux distro-based host that was running powerline-go.

Does this issue occur when all extensions are disabled?: Yes

![Screenshot 2021-04-17 084737](https://user-images.githubusercontent.com/892162/115115165-cb372e00-9f60-11eb-99b2-0002b5336088.png)

**Comment by IllusionMH** [comment] 2021-04-17 17:31
/duplicate of #120129

Shuld be fixed Insiders build https://code.visualstudio.com/insiders/

**Closed** 2021-04-17 17:31 UTC
Labels: *duplicate, new release
