### ISSUE TITLE
Powerline fonts in terminal incorrect

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#7116] opened 2016-06-02 06:27 UTC
- VSCode Version: 1.2.0-insiders
- OS Version: OSX

Steps to Reproduce:

1. Open Code from terminal
2. Open integrated terminal
3. See fonts are broken
4. This may be some Powerline font issue in tty but seems to work ok in Atom integrated terminal ok
5. Picture below shows code, bottom terminal is what it should look like
![screen shot 2016-06-02 at 07 24 53](https://cloud.githubusercontent.com/assets/105126/15735823/7e75af0e-2893-11e6-9ff3-141507cccd04.png)

**Comment by Tyriar** [comment] 2016-06-02 07:22
@jchannon I haven't used these before. Do I install from https://github.com/powerline/fonts and then use some special characters in my prompt?

**Comment by jchannon** [comment] 2016-06-02 08:42
Nope just use those fonts, install OH MY ZSH and then maybe set the theme
to be something like here:
https://coderwall.com/p/sun7za/mac-os-x-oh-my-zsh-theme-on-iterm2

**Comment by ibratoev** [comment] 2016-06-07 07:19
This might be caused by lack of proper locale. See #7301 for workaround.

**Comment by JuHwon** [comment] 2016-06-07 14:15
i am having the same issue on linux

**Comment by Sephizor** [comment] 2016-06-08 09:06
Same issue here on Linux, 1.2 release.

OS: Ubuntu Gnome 16.04
Shell: Zsh (oh-my-zsh)
Zsh theme: powerlevel9k
Font: Ubuntu Mono derivative Powerline Regular

**Comment by reaktivo** [comment] 2016-06-15 11:57
I had this issue on OS X, it has to do with the Terminal not using the `editor.fontFamily` setting, can you try setting your `terminal.integrated.fontFamily` to the same powerline font used in `editor.fontFamily`?

**Comment by JuHwon** [comment] 2016-06-15 12:11
setting the `terminal.integrated.fontFamily ` in my `User Settings` file fixed it. thx.

**Comment by jchannon** [comment] 2016-06-15 12:32
That seems to do the trick however, the colours are different and the right hand side seems off 

<img width="963" alt="screen shot 2016-06-15 at 13 31 21" src="https://cloud.githubusercontent.com/assets/105126/16079860/812b69f4-32fd-11e6-8fe2-0841fae1e731.png">

**Comment by reaktivo** [comment] 2016-06-15 12:37
Let's wait to get Terminal theme support, but that's another issue. About the time on the right, I guess the terminal is reporting incorrect terminal column width.

**Comment by Tyriar** [comment] 2016-06-15 18:03
Great to hear that the main issue is the font wasn't being set. In 1.3.0 the font's default fallback is `editor.fontFamily` but you can set it explicitly with `terminal.integrated.fontFamily` https://github.com/Microsoft/vscode/issues/6791

I'm going to close this off but these issues may still be blocking this:

- Terminal themes https://github.com/Microsoft/vscode/issues/6979
- Correctly represent full width characters https://github.com/Microsoft/vscode/issues/7448, https://github.com/sourcelair/xterm.js/issues/62

**Closed by Tyriar** 2016-06-15 18:03 UTC
Labels: bug, integrated-terminal

**Comment by xujipm** [comment] 2017-03-17 14:36
I am having the same issue on OS X with zsh

font, SourceCodePro+Powerline+AwesomeRegular
font source, https://github.com/stefano-meschiari/dotemacs/blob/master/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf

![image](https://cloud.githubusercontent.com/assets/3202911/24047880/0be399c6-0b62-11e7-9610-89fd7471f073.png)

**Comment by Tyriar** [comment] 2017-03-17 16:20
@xujipm try these instructions https://github.com/Microsoft/vscode/issues/15119#issuecomment-259248159

**Comment by xujipm** [comment] 2017-03-18 16:30
@Tyriar i have try that way, but didn't work~

**Comment by Gkjsdll** [comment] 2017-04-10 20:42
@xujipm I use the same font and this worked for me:
`"terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'"`
Note the single quotes inside of the double quotes.
![image](https://cloud.githubusercontent.com/assets/7777305/24881704/8e19b30a-1df3-11e7-99fc-74975e315348.png)

**Comment by LarryWachira** [comment] 2017-04-21 15:45
@Gkjsdll Thanks! Working fine now.

**Comment by jongear** [comment] 2017-04-27 14:39
@Gkjsdll Your solution worked!

**Comment by jpdoria** [comment] 2017-05-13 07:33
@Gkjsdll Cool! Thanks for the solution!

**Comment by outtoin** [comment] 2017-05-27 07:46
@Gkjsdll Nice Solution!

**Comment by Tyriar** [comment] 2017-05-30 21:08
Locking to prevent the solution above from being buried. If that doesn't work feel free to file a new issue and link it to this one.
