### ISSUE TITLE
Active tab difficult to see when tab text color is non-default

### ISSUE THREAD

**Issue by esseb** [microsoft/vscode#123251] opened 2021-05-07 07:26 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Use the default theme (Dark+)
2. Open multiple TypeScript files
3. Create an error in each file in order to make the tab text color red (this does not require an extension)

Actual result:

The only difference between the active tab and the other tabs is that the active has a slightly darker background and a close button, which is not enough for me to tell which tab is active without actively looking at all the tabs.

![Screenshot 2021-05-07 at 09 19 39](https://user-images.githubusercontent.com/207794/117412703-5dee3b80-af15-11eb-8c42-638ba179d654.png)

Further information:

When the tabs have the default text color it's easier to see which tab is active since it has a white text color while the other tabs have a gray text color. I usually don't have this many tabs open with TypeScript errors, when I notice that it's hard to see which tab is active it's because a lot of my open tabs have an orange text color, but I'm not sure what triggers that tab text color.

This issue has been reported before in https://github.com/microsoft/vscode/issues/122588 but was closed.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.57.0-insider (Universal) (fe23c2041f848d6c2f6bd27875112a37bcc82f84, 2021-05-06T05:50:00.296Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_4121582|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2ct:30286873
vscorehov:30295781

```

</details>

**Comment by misolori** [comment] 2021-05-07 18:55
You can always customize the active tab colors by adding this to your settings.json:

```json
    "workbench.colorCustomizations": {
        "tab.activeBackground": "#ff0000"
    }
```

and then find the right color that works for you. Or use the active tab border color setting:

![image](https://user-images.githubusercontent.com/35271042/117495823-fe9b2600-af2a-11eb-947f-dd7aa136bc0a.png)


```json
    "workbench.colorCustomizations": {
        "tab.activeBorderTop": "#007acc"
    }
```

You can [choose a different theme](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs) that may suite you preference. Hope this helps, will close this as it is by design.

**Comment by misolori** [comment] 2021-05-10 14:28
I misread the issue and thought this was about the current tab colors. Turns out that the decorators change the opacity on non-active tab text, so re-opening. Thanks to @bpasero for the ping.

**Comment by mirao** [comment] 2021-05-15 15:01
I can confirm the issue and I think it started in some of recent versions (one or two versions ago? I think that the active tab was lighter than inactive whereas now it's opposite. But not sure). It's hard for me to recognize which tab is active
![image](https://user-images.githubusercontent.com/12584138/118365857-ae613b00-b59e-11eb-9afb-7db43f5b7f78.png)

At least [the change of active background color](https://github.com/microsoft/vscode/issues/123251#issuecomment-834693343) helps me a bit, thanks @misolori 
![image](https://user-images.githubusercontent.com/12584138/118365848-a43f3c80-b59e-11eb-8313-05c077358324.png)

**Used SW:**
- VSCode 1.56.1, theme "Dark+"
- Ubuntu 20.10

**Closed** 2021-12-07 02:31 UTC
Labels: feature-request, themes, workbench-tabs, file-decorations
