### ISSUE TITLE
Multimple file edit

### ISSUE THREAD

**Issue by AgentRX** [microsoft/vscode#73707] opened 2019-05-14 06:24 UTC
Issue Type: <b>Bug</b>

I renamed Server.js to server.js BUT VS Code makes me available to edit both of them under Windows:))) It's funny and have a lot of conflicts...

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (10.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.56

</details>

**Comment by mjbvz** [comment] 2019-05-14 17:31
Duplicate of #12448

**Closed by mjbvz** 2019-05-14 17:31 UTC
