### ISSUE TITLE
`workbench.action.closeEditorsInGroup` does not close the group when tabs are disabled.

### ISSUE THREAD

**Issue by cleversprocket** [Microsoft/vscode#10438] opened 2016-08-11 17:05 UTC
- VSCode Version: 1.4.0 
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Disable Tabs by setting the rule `"workbench.editor.showTabs": false` in User settings settings.json and change the behavior of cmd+w by binding it to `workbench.action.closeEditorsInGroup` as mentioned in #6605 in Keyboard Shortcuts keybindings.json
2. Select a file to edit with cmd+p.
3. Repeat step 2 with several different files.
4. Open a new editor pane with cmd+2.
5. Use step 2 in the new pane to open a file for editing.
6. Repeat step 3 in the new pane.
7. Attempt to close the new pane with cmd+w then the first pane.

Expected Results:
The pane closes using cmd+w.

Actual Results:
cmd+w does not always close the group, just the file.

**Comment by bpasero** [comment] 2016-08-12 08:19
I cannot reproduce and here is the proof:

![untitled](https://cloud.githubusercontent.com/assets/900690/17616628/455974ce-6076-11e6-8679-994fda1b136c.gif)

My settings:

```
{
	"files.autoSave": "off",
	"editor.wrappingColumn": 3000,
	"window.openFilesInNewWindow": false,
	"window.zoomLevel": 1,
	"workbench.editor.showTabs": false
}
```

**Comment by bpasero** [comment] 2016-08-16 08:40
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-08-16 08:40 UTC
Labels: needs more info

**Comment by cleversprocket** [comment] 2016-08-16 18:56
Sorry for the late reply, I've been trying to reproduce since I reported it
but haven't. Thank for looking into it!

**Comment by bpasero** [comment] 2016-08-17 04:22
When this happens again, please use Help > Toggle Developer Tools to see if something gets logged to the console.
