### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by nicoabie** [microsoft/vscode#188501] opened 2023-07-21 14:21 UTC
Type: <b>Bug</b>

The JS/TS language service crashed 5 times in the last 5 Minutes.

Using VSCODE in MacStudio Ultra

No steps to replicate

VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Ultra (24 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|64.00GB (36.86GB free)|
|Process Argv|--crash-reporter-id 734fa62f-9d1f-4bd1-94f3-ab0fe8f3ea3b --crash-reporter-id 734fa62f-9d1f-4bd1-94f3-ab0fe8f3ea3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.11
vscode-eslint|dba|2.4.2
gitlens|eam|14.1.1
EditorConfig|Edi|0.16.4
copilot|Git|1.98.275
vscode-github-actions|git|0.25.8
vscode-docker|ms-|1.26.0
es6-string-html|Tob|2.12.1
quokka-vscode|Wal|1.0.549
pretty-ts-errors|yoa|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by mjbvz** [comment] 2023-07-21 17:06
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nicoabie** [comment] 2023-07-21 17:47
does not appear to happen

**Comment by mjbvz** [comment] 2023-07-21 17:48
Thanks for checking. Closing as this suggests the issue has already been fixed or is caused by one of your installed extensions

**Closed by mjbvz** 2023-07-21 17:48 UTC
Labels: info-needed
