### ISSUE TITLE
Add "find all reassignments/mutations" feature

### ISSUE THREAD

**Issue by Zzzen** [microsoft/vscode#45464] opened 2018-03-10 08:51 UTC
"find all references" is good, but I only care about reassignments/mutations to a property sometimes.

**Comment by jrieken** [comment] 2019-08-29 10:33
closing as dupe of #74237

**Closed** 2019-08-29 10:33 UTC
Labels: *duplicate, editor-symbols, feature-request

**Comment by sean-mcmanus** [comment] 2019-09-13 19:35
For C/C++ we're tracking this with https://github.com/microsoft/vscode-cpptools/issues/4043 .

It's not really a "type" of reference, but an additional property/column that only applies to variable references, so I don't think https://github.com/microsoft/vscode/issues/74237 is really the same issue, i.e. in VS, the "type" and Read/Write are separate.
