### ISSUE TITLE
[FR] Add option to disable icon bouncing in macOS's dock

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode#104365] opened 2020-08-10 11:05 UTC
When I have a remote workspace open, every single time that I come to my laptop after some disuse, the remote connection has been closed, and VSCode will keep spamming me with a bouncing dock icon to go and reconnect. Since it is [not possible](https://apple.stackexchange.com/questions/170773/disable-a-specific-app-from-ever-bouncing-in-dock) to disable the dock bouncing from the OS itself, the option needs to be built into VSCode itself.

**Comment by roblourens** [comment] 2020-08-12 04:31
@deepak1556 do you know what triggers this? Is it showing a native dialog?

Does setting `"workbench.dialogs.customEnabled": true` fix it?

**Comment by deepak1556** [comment] 2020-08-12 05:46
yup there is some kind of native dialog in play here that causes the bounce.

**Comment by NightMachinary** [comment] 2020-08-12 11:31
[**@Rob Lourens**](https://github.com/roblourens) commented on [Aug 12, 2020, 9:01 AM GMT+4:30](https://github.com/microsoft/vscode/issues/104365#issuecomment-672566405 "2020-08-12T04:31:51Z - Replied by Github Reply Comments"):
> [@deepak1556](https://github.com/deepak1556) do you know what triggers this? Is it showing a native dialog?
> 
> Does setting `"workbench.dialogs.customEnabled": true` fix it?

Where can I set it? The settings json doesn't recognize it:
![image](https://user-images.githubusercontent.com/36224762/90010425-10f67500-dcb5-11ea-8f27-ab304a92d080.png)

**Comment by roblourens** [comment] 2020-08-13 03:18
That's correct, it's actually an undocumented setting. Easy way to check if it's working- open a blank editor, type something, close it, you will get the "do you want to save this?" dialog, and it should be easy to tell if it's OS-native or custom.

**Comment by ylilarry** [comment] 2020-08-13 16:47
I'm new to this. How do I upvote this?

I'd also like to add that the issue is not bouncing but the alert dialog that forces user to act. 
I frequently have issue when trying to shutdown my macOS and there's a few vscode windows with disconnected ssh-remote session. The alert style dialog says something like "cannot connect to remote" and it forces you to either press the [reload window] button, or the [cancel] button. This is preventing my machine from shutting down until I close each of these alert dialogs. 

I believe this is the same macOS API that causes then dock app icon to bounce.

**Comment by NightMachinary** [comment] 2020-08-13 17:37
[**@ylilarry**](https://github.com/ylilarry) commented on [Aug 13, 2020, 9:17 PM GMT+4:30](https://github.com/microsoft/vscode/issues/104365#issuecomment-673587176 "2020-08-13T16:47:20Z - Replied by Github Reply Comments"):
> I'm new to this. How do I upvote this?
> 
> I'd also like to add that the issue is not bouncing but the alert dialog that forces user to act.  
> I frequently have issue when trying to shutdown my macOS and there's a few vscode windows with disconnected ssh-remote session. The alert style dialog says something like "cannot connect to remote" and it forces you to either press the \[reload window\] button, or the \[cancel\] button. This is preventing my machine from shutting down until I close each of these alert dialogs.
> 
> I believe this is the same macOS API that causes then dock app icon to bounce.

Today, I also noticed that if I click `cancel`, then I'd never be able to reconnect that window and would need to close the workspace and reopen it to connect to SSH again.

**Closed** 2020-10-12 02:31 UTC
Labels: feature-request, mac
