### ISSUE TITLE
Native Terminal: pgup/pgdown doesn't work in tmux

### ISSUE THREAD

**Issue by magic-lantern** [microsoft/vscode#75548] opened 2019-06-14 23:46 UTC
Issue Type: <b>Bug</b>

My host is macOS and I'm using the Terminal to SSH to a remote Linux x86_64 host. When I use tmux, pgup and pgdown do not go to tmux and thus appear to not work.

In tmux, to enter copy mode, you can press `Ctrl+b [` or `Ctrl+b PgUp`  (enter copy mode and scroll up one page) while the first works, the second does not. Also once I enter copy mode, arrow keys work just fine, but PgUp/PgDown still do not work.

I'm using the latest insiders build, but this problem also occurs on regular 1.35.1

VS Code version: Code - Insiders 1.36.0-insider (15b7c86d86319b187a5ef255c170184a8519c5af, 2019-06-14T10:36:51.530Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 4.4.0-150-generic

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
vscode-docker|Pet|0.6.2
vscode-icons|vsc|8.7.0
vscode-markdownlint|Dav|0.27.0
gitlens|eam|9.8.2
r|Iku|1.1.0
latex-workshop|Jam|7.0.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.5.18875
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by magic-lantern** [comment] 2019-06-14 23:47
As an FYI, I reviewed those bugs and they don't appear to cover this same issue.

**Comment by Tyriar** [comment] 2019-07-06 17:54
Works for me, do you have custom keybindings for page up/down? Can you share your keybindings.json and settings.json files?

**Comment by magic-lantern** [comment] 2019-07-06 21:17
I have no custom bindings that I am aware of neither in the OS nor VSCode.

Here's my keybindings.json file:

```
// Place your key bindings in this file to override the defaults
[
]
```

And my settings.json file:

```
{
    "telemetry.enableTelemetry": false,
    "editor.minimap.enabled": false,
    "window.title": "${activeEditorLong}${separator}${rootName}",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "vsicons.projectDetection.autoReload": true,
    "remote.SSH.showLoginTerminal": true,
    "workbench.iconTheme": "vscode-icons",
    "terminal.external.osxExec": "iTerm.app",
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    // Columns at which to show vertical rulers
    "editor.rulers": [119],
}
```

I noticed that the tmux not scrolling problem also occurs when I just open a local tmux session without first SSH to a remote machine.

This problem still occurs with the newer version of regular VS Code (1.36.0) and does NOT occur on same VS Code version running on Windows.

Could the problem be tmux version specific or macOS version specific? On macOS, I'm running tmux 2.9a; on Linux, I'm running tmux 2.1 - both exhibit the problem when the client is macOS.

**Comment by Tyriar** [comment] 2019-07-08 19:10
Ok I figured out what the problem is, it's these default keybindings on mac:

```ts
{ "key": "pageup",                "command": "workbench.action.terminal.scrollUpPage",
                                     "when": "terminalFocus" },
{ "key": "pagedown",              "command": "workbench.action.terminal.scrollDownPage",
                                     "when": "terminalFocus" },
```

On Linux and Windows they default to shift+pageup/down, the reason the default is different on macOS is because that's what it is on Terminal.app. I think there is a way to fix this and it's to add a new context key for when the terminal is in the alt buffer (ie. tmux, screen, vim, etc. are running) and don't scroll then but instead send the keys to the program. This is what Terminal.app appears to do and it makes a lot of sense because there is no scrollback when the alt buffer is active.

**Comment by magic-lantern** [comment] 2019-07-08 20:47
Thanks for the guidance and work around. I've tested the work around and it does work for me.

**Comment by Tyriar** [comment] 2019-10-09 18:02
Closing as designed, workaround is to removed the default keybindings. I don't think we should get in the business of changing terminal keybindings based on what the active terminal buffer is.

**Closed** 2019-10-09 18:02 UTC
Labels: *as-designed, bug, integrated-terminal, mac
