### ISSUE TITLE
Cannot rename files in folder with many files

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#96151] opened 2020-04-25 20:48 UTC
- VSCode Version: latest Insiders
- OS Version: Manjaro

Steps to Reproduce:

1. Get the code of `https://github.com/selfrefactor/rambda`
2. Open the project
3. Open `src` folder
4. Try to rename `both.js` file - this is successful
5. Try to rename `cond.js` file - this will not be succesful
7. Try to rename any other file below `cond.js` will also trigger the error.

VSCode goes in limbo as sidebar's background is dimmed and it remains dimmed until several other actions which include open other file, rename it and press `esc`. The point that it rename was not possible and I had to use OS's file explorer. Maybe it is related to the number of files in the folder as this folder maybe has more than 200 files.

I did look into the `Outputs` but I didn't see anything.

Does this issue occur when all extensions are disabled?: Yes

**Comment by selfrefactor** [comment] 2020-04-25 20:54
Ok, so this is definitely the same as the closed issue https://github.com/microsoft/vscode/issues/95315

**Comment by mjbvz** [comment] 2020-06-12 22:26
Duplicate of #95315 based on the description

**Closed by mjbvz** 2020-06-12 22:26 UTC
