### ISSUE TITLE
Large project: Hanging/freezing problem

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#43838] opened 2018-02-16 15:39 UTC
I've got a single project with ~10,000 .c and .h files in a single folder. Navigation thru VS Code causes CPU spikes and often hangs/freezes up to a point where a pop up appears asking me to select one of the three options. Namely Reopen, Keep Waiting, Close. System Win7-64 bit. Intel Xeon E3-1505M 2.80Ghz. 32 GB RAM.

- VSCode Version: 1.20.1
- OS Version: Win7 64-bit

Steps to Reproduce:

1. Load a project
2. Do regular stuff

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment] 2018-02-16 15:47
Can you please run `code --status` when the project is open and attach the output.

**Comment by bisherbas** [comment] 2018-02-16 15:56
While running the `code --status` command the same pop up window appeared. See attached. I selected Keep Waiting and I was able to copy the results eventually.

![image](https://user-images.githubusercontent.com/7196815/36316093-5c9b9758-1307-11e8-84c2-85f9c722f35d.png)

```
C:\Workspace\MyProject>code --status

Collecting CPU and memory information. This might take a couple of seconds.

Version:          Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS Version:       Windows_NT x64 6.1.7601
CPUs:             Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)
Memory (System):  31.88GB (18.34GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code\Code.exe
CPU %   Mem MB     PID  Process
    0       93   44896  code main
    0      687   58516     window (mkdoerl.c - Untitled (Workspace) - Visual Studio Code)
    0       37    5660       watcherService
   13      217   16744       extensionHost
    0       13   32660       electron-crash-reporter
    0       31   81424       terminal
    0        7   60688         winpty-process
    0        7   54792           C:\WINDOWS\system32\cmd.exe
    0       31   20092             electron_node cli.js
    0       52   27152               "C:\Program Files\Microsoft VS Code\Code.exe" --status
    0       23   36868                 gpu-process
    0      109   75268                 powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
    0       74   59868     gpu-process
    1       74   69548     shared-process
Workspace Stats:
|  Window (mkdoerl.c - Untitled (Workspace) - Visual Studio Code)
|    Folder (MyProject): 10455 files
|      File types: h(5795) c(4660)
|      Conf files: settings.json(1)
```

**Comment by bpasero** [comment] 2018-02-17 08:08
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bisherbas** [comment] 2018-02-17 14:33
@bpasero As I said in my message above (also provided screenshot), there aren't any extensions installed.

**Comment by bpasero** [comment] 2018-02-17 15:56
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bisherbas** [comment] 2018-02-19 12:42
@bpasero Problem persists.

![image](https://user-images.githubusercontent.com/7196815/36378345-729af632-1548-11e8-9e47-5e971a589f85.png)

**Comment by bpasero** [comment] 2018-02-20 06:03
@bisherbas does it reproduce if you run "code --disable-gpu"?

**Comment by bisherbas** [comment] 2018-02-20 18:01
@bpasero Unfortunately did not make a difference. Maybe it is a caching issue? Reason I am bring it up because the issue appears to be intermittent. Sometimes I can navigate thru code seamlessly for half an hour and other times it keeps freezing/crashing. I can confirm that this issue with the same large project is reproducible on another Win7 machine with similar configuration.

**Comment by bisherbas** [comment] 2018-02-28 03:32
Update: Issue seems to go away a few minutes after I first launch the app. If this is an expected behavior we can close the issue.

**Comment by jovere** [comment] 2018-03-01 14:01
I have a similar issue in Linux.  If I accidentally open a bitbake build folder, (contains over 1 million subfolders and files), it begins to ramp up processor usage almost immediately.  It completely pegs the system, and the entire OS UI freezes except for the mouse.  I can hover over the LXDE menu bar and a tooltip will pop up, but I can't click on anything.  I'm using the machine over Synergy, so when this happens, I try to plug in a USB keyboard and mouse... they don't even get acknowledged that they're plugged in and stay dark.

If I'm quick enough and try to close it (via the normal X), the window closes, but the process continues running in the background. And if I try to kill it, I just end up with a zombie process that won't die.  Even trying to reboot doesn't fix it, as the system just hangs on shutting down.  A hard reset seems the only way to fix it.

I used to open these previously without any issue.

Version Info:
```
Ubuntu 16.04 LTS with LXDE
```
```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:31:21.019Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by bisherbas** [comment] 2018-03-01 14:33
Thanks for reporting in. Hopefully expert devs will figure it out. If anyone tells me where I can find the relevant source code I will be happy to take a look at it and attempt a fix.

**Comment by bisherbas** [comment] 2018-03-07 19:46
Git panel looks crazy shortly after I launch VS Code with a workspace consists of ~10,000 `.c` and `.h` files. Would this additional info help identify the root cause? Below is only the last few lines shown in the Git panel. There are thousands of more lines showing `git rev-parse --show-toplevel`

```
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by bpasero** [comment] 2018-03-17 06:40
@joaomoreno on https://github.com/Microsoft/vscode/issues/43838#issuecomment-371261265

**Comment by joaomoreno** [comment] 2018-03-19 14:59
This is fine. They are short running processes and we use the to probe for git repositories.

**Comment by bisherbas** [comment] 2018-03-19 17:02
@joaomoreno Please go thru the whole thread. This is NOT fine actually. Thanks.

**Comment by joaomoreno** [comment] 2018-03-20 08:11
Oh, can you correlate the CPU spikes with the git processes?

**Comment by bisherbas** [comment] 2018-03-20 18:12
@joaomoreno Yes. See image below.

![code](https://user-images.githubusercontent.com/7196815/37674205-add8785c-2c48-11e8-897c-675eb56741b4.jpg)

**Comment by joaomoreno** [comment] 2018-03-21 07:36
That image doesn't show me a single `git.exe` process...

**Comment by bisherbas** [comment] 2018-03-21 12:42
@joaomoreno I will be happy to. But can you tell me how to get the "full command line of the code.exe"? Thanks.

**Comment by joaomoreno** [comment] 2018-03-22 08:30
In your screenshot there's a table; the last column of that table shows the full command line of all processes. I'd like to read the whole table column.

**Comment by bisherbas** [comment] 2018-03-22 13:39
@joaomoreno 

```
"C:\Program Files\Microsoft VS Code\Code.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=1462054ACBA8CCCC762A79FB0FA09DB3 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Program Files\Microsoft VS Code\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=1462054ACBA8CCCC762A79FB0FA09DB3 --renderer-client-id=8 --mojo-platform-channel-handle=1852 /prefetch:1
```

I know this command line does not show any `git` process but I can assure you that high CPU utilization and freezing/hanging problem occurs with large folders which are NOT `git` repository. I did an A-B-A test to confirm. I don't know how else I can help you root cause the issue. Please let me know.

Same folder with 10k files:

`git` repo -> No high CPU util or freezing.
NOT A `git` repo -> High CPU util and freezing.

**Comment by jovere** [comment] 2018-03-22 13:54
Perhaps it's an issue with the nesting check for repositories with the newer versions of VSCode.  I found my issue with the freezing was due to the Perforce plugin I had been using.  The plugin hadn't been updated, but after the VSCode update, my entire Linux PC would suddenly come to a screeching halt when I opened up a very huge bitbake build directory.  After removing that plugin, the issues seemed to go away.  Unfortunately, I can't copy it, since the entire computer becomes unresponsive, but the tool that was freezing my pc had the beginning of the following processes:

```
/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/.p4config -g !**/node_modules/**...
```

**Comment by bisherbas** [comment] 2018-05-06 20:55
@joaomoreno Any update?

**Comment by rezashamdani** [comment] 2018-07-18 07:17
latest version still have problem with this.

i have a php file which have over 24K lines, which will hang few second after i open it.

While splitting the file into 2 file seem fix the problem, but why does it matter with over 24K lines?

<img width="916" alt="screen shot 2018-07-18 at 2 11 09 pm" src="https://user-images.githubusercontent.com/3622787/42865705-b4b217a0-8a94-11e8-95a4-d1806afdcf1a.png">

![screen shot 2018-07-18 at 2 11 16 pm](https://user-images.githubusercontent.com/3622787/42865717-bcf5bb2e-8a94-11e8-8475-04bd75478c50.png)

**Comment by rezashamdani** [comment] 2018-08-01 03:38
Hi @jovere , thanks for the update.

I have tried to add "search.useRipgrep": false, but still freeze few seconds after loading the file.

**Closed** 2018-09-17 17:07 UTC
Labels: freeze-slow-crash, needs more info
