### ISSUE TITLE
can't connnect to remote ssh in 1.36.0

### ISSUE THREAD

**Issue by kabirz** [microsoft/vscode#76675] opened 2019-07-05 08:21 UTC
- VSCode Version: 1.36.0
- OS Version: windows 10

Steps to Reproduce:
Only first connect remote ssh successfully,  restart local vscode will can't connect again.(1.35.1 withot this issue)
remote process as bellow:
ps axu |grep vscode
huiping  18794  0.0  0.0  14264  3244 ?        S    15:37   0:00 sh /home/huiping/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/server.sh --enable-remote-auto-shutdown --port=0
huiping  18802  0.4  0.2 983252 66868 ?        Sl   15:37   0:01 /home/huiping/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/node /home/huiping/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/main.js --enable-remote-auto-shutdown --port=0
huiping  20941  0.0  0.0  15968  1012 pts/0    S+   15:44   0:00 grep --color=auto vscode

**if kill the process of 18802 , can connect to remote**
local vscode log as bellow:
Found existing installation at /home/huiping/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
> Checking server status with wget
> 
> http://10.239.4.100/: 2019-07-05 15:51:41 ERROR 503: Service Unavailable.
> de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
> 
"install" terminal command done
Received install output: de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
Server status check failed - waiting and retrying 28
> 
> Found existing installation at /home/huiping/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> 
> 
> http://10.239.4.100/: 2019-07-05 15:51:45 ERROR 503: Service Unavailable.
> de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
> 
"install" terminal command done
Received install output: de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
Server status check failed - waiting and retrying 29
> 
> Found existing installation at /home/huiping/.vscode-server/bin/0f3794b38477eea1
> 3fb47fbe15a42798e6129338...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status with wget
> 
> http://10.239.4.100/: 2019-07-05 15:51:49 ERROR 503: Service Unavailable.
> de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
> 
"install" terminal command done
Received install output: de46cd64-f440-4ee0-88bb-3ceeae0b9919##28##
Server status check failed - waiting and retrying 30

**Comment by saeedizadi** [comment] 2019-07-08 05:33
Is it going to be resolved soon?

**Comment by nufsty2** [comment] 2019-07-09 22:18
I have the same problem!

**Comment by hidehiko-t** [comment] 2019-07-10 02:10
I've got the same issue, and it works the workaround type "ps axu | grep vscode" and kill processes for vscode-server.
Client: Windows 10 + VSCode 1.36.0
Server: Ubuntu 18.04 + VSCode 1.36.0

**Comment by kabirz** [comment] 2019-07-10 03:08
I solved the problem.
 Add "no_proxy=127.0.0.1,localhost" to ~/.wgetrc, this issue will not exist.

**Comment by hidehiko-t** [comment] 2019-07-10 04:51
> I solved the problem.
> Add "no_proxy=127.0.0.1,localhost" to ~/.wgetrc, this issue will not exist.

It works, thank you!

**Comment by saeedizadi** [comment] 2019-07-10 05:51
> I solved the problem.
> Add "no_proxy=127.0.0.1,localhost" to ~/.wgetrc, this issue will not exist.

Didn't help

**Comment by roblourens** [comment] 2019-07-10 18:10
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/895

**Closed by roblourens** 2019-07-10 18:10 UTC
