### ISSUE TITLE
Incorrect syntax highlighting of a shellscript after a `<<`

### ISSUE THREAD

**Issue by senhalil** [microsoft/vscode#143381] opened 2022-02-18 15:52 UTC
Issue Type: <b>Bug</b>

I am not sure but I suspect this issue is related to https://github.com/microsoft/vscode/issues/77675

In any case, as you can see in the screenshot after a `<<`  vscode looses syntax highlighting completely.

![Screenshot from 2022-02-18 16-48-29](https://user-images.githubusercontent.com/20163961/154716447-be0dca4f-8b91-49a3-9d1c-a461a7ba1884.png)

The same line is shown fine on github.com https://github.com/git/git/blob/e2ac9141e64e2cd3e690d1b5fc848949827c09b4/gitk-git/gitk#L2057

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 4.15.0-166-generic
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.56GB (0.36GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4b396966-510d-4f03-82c8-6dd778f75072|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by alexr00** [comment] 2022-02-21 07:51
This is indeed a duplicate of https://github.com/microsoft/vscode/issues/77675. When we have a better-maintained shell script grammar issues like this can be fixed.

**Closed by alexr00** 2022-02-21 07:51 UTC
