### ISSUE TITLE
Autocompletion of HTML does not use cases and puts a closing tag with all lower case letters

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Microsoft/vscode#15641] opened 2016-11-17 12:52 UTC
- VSCode Version: 1.7.1 (1.7.1) 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
- OS Version: OSX 10.11.6 (15G1108)

Steps to Reproduce:

1. In a .html file open a custom tag
2. Try to close that tag with the autocomplate functionality of VS Code (Ctrl + Space > Tab)
3. The closing tag is in all lower case letters and ignores the casing of the original opening tag

Example:
input:

`<TestTag>`

-write `<`
- press "Ctrl + Space"
- press "Tab" to autocomplate the closing tag

output (result):
`<TestTag></testtag>`

In the previous 1.6.x version this used to work as expected leading to an output of 
`<TestTest></TestTest>` 

Is this a bug or a feature and if so how can I revert/fix it.

**Comment by aeschli** [comment] 2016-11-18 14:43
duplicate of #15033

**Closed by aeschli** 2016-11-18 14:43 UTC
Labels: duplicate, suggest
