### ISSUE TITLE
[bug] VSC intellisense stops working

### ISSUE THREAD

**Issue by paradox37** [Microsoft/vscode#20805] opened 2017-02-17 13:15 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

There is no specific step to reproduce this. Only thing that I think that triggers it is working in larger scss file. File has around 2000 lines.

And, intellisense just stops working in the middle of working in the file. After that, it wont suggest anything in any file, even colors stops appearing in scss file. I have to restart VSC to get it working again.

I disabled all extensions and same thing happens. I even disabled GitHub but problem remains.

**Comment by lucianobarauna** [comment] 2017-02-18 17:23
I am also going through the same problem both in js and html files this happened after upgrade to 1.9.1 plus in my case it happens in up to any size of file from 19 lines of code until 2000.

**Comment by jrieken** [comment] 2017-02-21 08:34
Sounds like a dupe

**Comment by aeschli** [comment] 2017-02-21 08:44
duplicate of #19840. You can verify the fix in the latest [insiders](https://code.visualstudio.com/insiders) build.

**Closed by aeschli** 2017-02-21 08:44 UTC
