### ISSUE TITLE
Add an icon or shortcut for local server in VS code.

### ISSUE THREAD

**Issue by akash1297** [microsoft/vscode#111870] opened 2020-12-04 08:12 UTC
Add an icon or shortcut for the local server in VS code, so that we can check our work directly from the editor instead of going to the folder and then accessing the file.

**Comment by gjsjohnmurray** [comment] 2020-12-04 08:30
What is "the local server"? Please explain your enhancement request in more detail. Maybe paste a screenshot with mockup annotations.

**Comment by akash1297** [comment] 2020-12-04 08:52
I mean that if I am writing a code in index.html file inside my VS code and suppose I want to RUN it on my browser(Chrome, Mozilla, etc..) to check whether my work is correct or not, for that there should be a shortcut key so that every time we don't have to open the index.html file externally. Or if there is any shortcut key do tell me.

**Comment by gjsjohnmurray** [comment] 2020-12-04 08:56
/duplicate of #111737

On that issue I suggested checking Marketplace for extensions that do this.

**Closed** 2020-12-04 08:57 UTC
Labels: *duplicate
