### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by juaneks77** [microsoft/vscode#104524] opened 2020-08-12 22:06 UTC
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200811

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at bindThisPropertyAssignment (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:41337:22)
    at bindWorker (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:41029:37)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40899:13)
    at bindExpressionStatement (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39964:13)
    at bindChildren (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39450:21)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40910:21)
    at c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:94
    at Object.forEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at bindEachFunctionsFirst (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:13)
    at bindChildren (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39496:21)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40910:21)
    at visitNode (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26832:24)
    at Object.forEachChild (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26962:21)
    at bindEachChild (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39401:16)
    at bindChildren (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39499:21)
    at bindContainer (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39348:17)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at Object.forEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at visitNodes (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26837:24)
    at Object.forEachChild (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:27152:21)
    at bindEachChild (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39401:16)
    at bindChildren (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39499:21)
    at bindContainer (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39383:17)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:94
    at Object.forEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at bindEachFunctionsFirst (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:13)
    at bindChildren (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39490:21)
    at bindContainer (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39348:17)
    at bind (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at bindSourceFile (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:38976:17)
    at Object.bindSourceFile (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:38916:9)
    at initializeTypeChecker (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:76465:20)
    at Object.createTypeChecker (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:42923:9)
    at Object.getTypeChecker (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:103469:79)
    at synchronizeHostData (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:143443:21)
    at Proxy.getProgram (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:143525:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:148382:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:148315:42)
    at ConfiguredProject.updateGraph (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:149249:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:150953:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:151860:44)
    at c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:152187:97
    at Object.flatMap (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:152187:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:153206:46)
    at c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155078:88
    at IOSession.Session.executeWithRequestId (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155069:28)
    at IOSession.Session.executeCommand (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155078:33)
    at IOSession.Session.onMessage (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155102:35)
    at Interface.<anonymous> (c:\Users\sistemas9\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:157318:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-08-17 21:36
Please fill in the template to the best of your ability. Include the project / file that causes this if possible

**Comment by mjbvz** [comment] 2020-08-25 02:53
Closing as duplicate of https://github.com/microsoft/TypeScript/issues/40098 

If you see this with the latest TS nightly builds, please share code that reproduces this

**Closed by mjbvz** 2020-08-25 02:53 UTC
Labels: needs more info, typescript
