### ISSUE TITLE
breakpoints stopped working after update to (1.32.1)

### ISSUE THREAD

**Issue by mgrybyk** [Microsoft/vscode#70160] opened 2019-03-10 14:49 UTC
- VSCode Version: Version 1.32.1 (1.32.1)
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. have project that spawns child processes
2. add breakpoint to any place, main or child process.

Does this issue occur when all extensions are disabled?: Yes

NOTE:
- downgrading to 1.31.1 resolves the problem 
- tried on different systems

**Comment by Eli-Goldberg** [comment] 2019-03-10 21:06
Probably duplicate of #70080

**Comment by mgrybyk** [comment] 2019-03-10 22:00
Most likely

**Comment by Hufe921** [comment] 2019-03-11 05:23
I have the same question

**Comment by joaomoreno** [comment] 2019-03-11 08:16
https://github.com/Microsoft/vscode/issues/70080

**Closed by joaomoreno** 2019-03-11 08:16 UTC
Labels: new release
