### ISSUE TITLE
TypeScript server crashes faster than ever

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24698] opened 2017-04-13 15:38 UTC
sorry, rant

Never famous for its stability `tsserver` has come to a new high of crashing every 2 minutes. To reproduce, open our source and navigate across some files. Find log files and output attached

```
[Info  - 5:30:05 PM] Using tsserver from location: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Error - 5:31:44 PM] TSServer exited with code: unknown
[Info  - 5:31:44 PM] Using tsserver from location: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
```

**Comment by jrieken** [comment] 2017-04-13 15:40
[Archive.zip](https://github.com/Microsoft/vscode/files/920135/Archive.zip)

**Comment by mjbvz** [comment] 2017-04-14 00:34
I don't see anything obvious in the logs. What version of TypeScript is active in the workspace? I just realized that we're still using TS 2.1.5 for VSCode. #24734 bumps us up to 2.2.2

**Comment by ecraig12345** [comment] 2017-04-14 03:02
Same issue here--TSServer crashes quickly/immediately for my large project on Windows Server 2012 R2, worse than it did before the most recent update. (A small project works fine.) The same large project is fine on my Mac, for some reason.

If someone tells me how to find log files, I can pass them on via email (project is not open source).

**Comment by jrieken** [comment] 2017-04-14 06:58
re https://github.com/Microsoft/vscode/issues/24698#issuecomment-294055701 - the status shows 2.2.2 but it is just our workspace

**Comment by mjbvz** [comment] 2017-04-14 21:02
@ecraig12345 To collect logs:

* Set `"typescript.tsserver.log": "verbose",`
* Restart VSCode and reproduce the issue
* Go to the output panel and share the output from the `TypeScript` section.

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

---

I don't see anything obvious in the logs but have been able to reproduce this issue in the VSCode main codebase several times. Let me try investigating more on my machine before we loop in some TS folks

**Comment by jrieken** [comment] 2017-04-26 15:11
Just crashed like this

```
[Info  - 5:04:11 PM] Using tsserver from location: /Users/jrieken/Code/vscode/node_modules/typescript/lib/tsserver.js
[Error - 5:10:05 PM] TSServer exited with code: unknown
[Error - 5:10:05 PM] 'occurrences' request failed with error.
Error: Service died.
    at Object.keys.forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:684:45)
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:683:37)
    at ChildProcess.childProcess.on (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:477:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 5:10:05 PM] Using tsserver from location: /Users/jrieken/Code/vscode/node_modules/typescript/lib/tsserver.js
```

**Comment by jrieken** [comment] 2017-04-26 15:12
The thing is that it never recovers from a crash. It talks about being started again but I'd say that's a lie because only refreshing the windows brings any TS functionality back

**Comment by ecraig12345** [comment] 2017-04-26 15:55
@mjbvz Thanks (belatedly)! Naturally as soon as I posted, tsserver started working much more consistently. If I start having major problems with crashes again, I'll send a log file.

**Comment by jrieken** [comment] 2017-05-03 13:41
btw - selfhosting on 2.3.2 (instead of 2.2.2) and there no improvement. Since the log seems pretty useless, what are the next steps to tackle this @mjbvz? This is a major blocker, esp. when moving/reading through files it makes me restart once every 5 minutes.

**Comment by mjbvz** [comment] 2017-05-05 02:34
One possible cause is #25807. This shows up in the typescript trace as a series of cancelled requests followed by a restart, and then more cancelled requests. However my fix only makes it so that we properly restart the tsserver, it does not actually prevent it from getting into the hung state to begin with

I'm continuing to look into this

**Comment by RichiCoder1** [comment] 2017-05-07 03:49
I've also been running into this issues. Typescript will struggle for a little while and then cease to work. It almost seems like it gets backed up.

**Comment by mjbvz** [comment] 2017-06-02 23:36
Closing this issue as it is too open ended. There have been fixes on our side and on the ts side with this most recent iteration. Please keep `typescript.tsserver.log` enabled and if you see a crash or hang, please open a new issue so that we can investigate further

**Closed by mjbvz** 2017-06-02 23:36 UTC
Labels: bug, important, typescript

**Comment by jrieken** [comment] 2017-06-06 07:18
>  Please keep typescript.tsserver.log enabled and if you see a crash or hang, please open a new issue so that we can investigate further

@mjbvz Did we learning anything from these log yet? Did we learn anything from running the server in debug mode? I don't think so and think it's a pretty bold move to just close this in the hope other fixes have closed this

**Comment by mjbvz** [comment] 2017-06-06 16:45
Yes we fixed several cancellation handling issues and opened a number of exception bugs against ts that could have been getting the server into a bad state

I closed this because catch-all issues like this have no clear done point and make tracking work difficult. Many of the crashes have different fundamental causes, and tracking individual crashes in separate issues makes it much easier to follow the investigation and eventual resolution

**Comment by jrieken** [comment] 2017-06-06 17:00
> I closed this because catch-all issues like this have no clear done point and make tracking work difficult. 

This isn't a catch-all issue but about [navigating in our sources](https://github.com/Microsoft/vscode/issues/24698#issue-221601612) and actually trivial to [reproduce](https://github.com/Microsoft/vscode/issues/28112#issuecomment-306520139) once you actually try it

**Comment by mjbvz** [comment] 2017-06-06 17:22
I have tried reproducing this, and we have tried collecting reports of crashes from developers in Redmond. We do not see crashes at anywhere near the level reported, perhaps a few times a week.

On this issue:

* Please give issues a title and description that makes the scope very clear. In this case, anyone who sees TS misbehaving will see this issue and may incorrectly believe that it is the correct issue for reporting their problem

* Specify what "done" looks like. Is this issue done when the TS server never crashes? When it crashes 10% less often than before? When we only crash in certain edge cases? That's why I suggest tracking the individual crashes in their own issues if possible

**Comment by RichiCoder1** [comment] 2017-06-06 17:23
Yup. I've been heads down in work so I haven't been able to come up with a repro or logs that aren't just TSServer Starting and Stopping constantly, but I can confirm I've constantly been running into this. I end up reloading VSCode 5-6 times a day just to relieve it.

**Comment by jrieken** [comment] 2017-06-06 18:02
> In this case, anyone who sees TS misbehaving will see this issue and may incorrectly believe that it is the correct issue for reporting their problem

You mean the two other people that are subscribed to this issue?

> That's why I suggest tracking the individual crashes in their own issues if possible

Nothing has been identified in this issue. By what criteria are suggesting to split them?

**Comment by ecraig12345** [comment] 2017-06-06 21:21
When I first commented on this issue, TSServer was crashing after just a few minutes. Now it's back to crashing a few times a day (and of course taking forever to start), which is still annoying but somewhat acceptable.

**Comment by RichiCoder1** [comment] 2017-06-07 17:40
[TSServerLog.txt](https://github.com/Microsoft/vscode/files/1058846/TSServerLog.txt)
Posted it to the other issue, but I'll add it here. Crashed about shortly I opened a TS file to start working.

**Comment by mjbvz** [comment] 2017-06-07 17:53
@RichiCoder1 Thanks, I've reopened https://github.com/Microsoft/vscode/issues/26141 so that we investigate further
