### ISSUE TITLE
Search now matches case even when "Match Case" is turned off

### ISSUE THREAD

**Issue by GottaCodeNow** [microsoft/vscode#87281] opened 2019-12-18 21:04 UTC
Version 1.41.0 
Date: 2019-12-11

I've noticed that now my searches are case sensitive even if the "Match Case" (Aa) is off/not highlighted.

![Search 1](https://user-images.githubusercontent.com/44888792/71123058-112e8700-219f-11ea-9805-fc407af24560.JPG)
![Search 2](https://user-images.githubusercontent.com/44888792/71123059-112e8700-219f-11ea-89e6-03a702082fb5.JPG)
![Search 3](https://user-images.githubusercontent.com/44888792/71123060-112e8700-219f-11ea-99ee-3aa6ff7c1eba.JPG)

**Comment by GottaCodeNow** [comment] 2019-12-18 21:22
Okay, I noticed a subtlety that may explain why this bug was missed: If you type in a search with all lower case letters, then the search will find both lower and upper case matches. But, if you capitalize even one letter in your search, then it will look for case matches regardless of the "Aa" (Match Case) setting.

All of my searches in the attached screen snippets have at least one capital letter.

**Comment by IllusionMH** [comment] 2019-12-19 00:06
Looks like duplicate of #83443

Please see https://github.com/microsoft/vscode/issues/83443#issuecomment-547176969 and try mentioned setting.

**Closed** 2020-05-07 11:23 UTC
Labels: needs more info, search
