### ISSUE TITLE
Perl's Indented HEREDOCs (a feature from Perl 5.26 onwards) are not correctly syntax highlighted

### ISSUE THREAD

**Issue by akarelas** [Microsoft/vscode#45106] opened 2018-03-06 02:52 UTC
- VSCode Version: 1.20.1
- OS Version: Ubuntu MATE Linux 16.04

Steps to Reproduce:

1. Write the following perl code in a file called `tobor.pl`, and view it on vscode editor:

```perl
#!/usr/bin/env perl

if (1 == 1) {
    print <<~"EOB";
        Hi there, how are you?
        My name is Tobor.
        EOB
    exit(0);
}
```

2. The syntax highlighting on vscode is not correct. EOB, exit(0), and the closing curly bracket should all have a different color than that of the block of text ("My name is Tobor", etc). Because they are not text to be printed, but commands that will be executed. Indented HEREDOCs are a feature of Perl 5.26 and onwards, and are denoted by the `~` to the left of EOB.. They are described here: https://www.effectiveperlprogramming.com/2016/12/strip-leading-spaces-from-here-docs-with-v5-26/ and are meant to make code which contains HEREDOCs look a lot nicer and properly indented.

Please see images in the comments, to see the problem without typing the code yourself.

Does this issue occur when all extensions are disabled?: Yes

**Comment by akarelas** [comment] 2018-03-06 02:56
This is the wrong highlighting:

![vscode-wrong-highlighting](https://user-images.githubusercontent.com/423822/37011775-4d0394f2-20fa-11e8-88a5-739f8b340e9b.png)

And this is a heredoc with correct highlighting (but in order to achieve correct highlighting on the current vscode, it's not an indented heredoc anymore):

![vscode-correct-highlighting](https://user-images.githubusercontent.com/423822/37011840-9daea5f4-20fa-11e8-971f-c0b0b379052a.png)

**Comment by aeschli** [comment] 2018-03-07 07:53
duplicate of https://github.com/textmate/perl.tmbundle/issues/26

**Closed by aeschli** 2018-03-07 07:53 UTC
Labels: grammar
