### ISSUE TITLE
Trusting a workspace in an editor should automatically proceed with extension installing

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122398] opened 2021-04-27 16:53 UTC
Testing #122228

1. I try to install an extension
2. I see this prompt and "learn more"
3. After reading it, I decide that I can trust the workspace and click "enable"
4. Now I have to manually go back and install the extension, but it would be nice to continue the process automatically.

**Comment by lszomoru** [comment] 2021-07-21 06:50
This is something that we have considered but we thought that it would be very confusing to take an action in the workspace trust editor (click on the trust button) which then would kick off an action that was taken previously. Closing the issue "by design".

**Closed by lszomoru** 2021-07-21 06:50 UTC
Labels: workspace-trust
