### ISSUE TITLE
Remote development still fails on 1.86.1

### ISSUE THREAD

**Issue by dagstuan** [microsoft/vscode#204745] opened 2024-02-08 17:31 UTC
Does this issue occur when all extensions are disabled?: No (Remote SSH needed)

- VS Code Version: 1.86.1
- OS Version: Mac OS Sonoma 14.3. Remote: Synology DSM 7.2.1-69057 Update 3

Steps to Reproduce:

1. Upgrade to 1.86.1
2. Attempt to connect to Synology with remote development
3. "Waiting for server log..." -> Eventual failure.

Downgrading to 1.85.2 works fine with the warning. I tried to delete the `.vscode-server` folder on the remote host, but the failure persists.

**Comment by onurhanak** [comment] 2024-02-08 20:35
Having the exact same issue with Remote SSH still. 

VS Code Version: 1.86.1
OS: Arch Linux

**Comment by cipherLord** [comment] 2024-02-09 05:43
It's not working for 1.85.2 since today for me.
OS: Mac Sonoma 14.3

**Comment by DouweM** [comment] 2024-02-12 02:27
@gjsjohnmurray is right, this is the same issue as https://github.com/microsoft/vscode/issues/204611. The fix (https://github.com/microsoft/vscode/pull/204660) is slated for release on [Feb 23, 2024](https://github.com/microsoft/vscode/milestone/255). 

As a workaround for the mean time, you can SSH into your Synology NAS and run the following to edit out the offending statement (`getconf LONG_BIT`):

```bash
sed -i 's|BITNESS=$(getconf LONG_BIT)|BITNESS="64"|g' $HOME/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/bin/helpers/check-requirements.sh
```

**Comment by deepak1556** [comment] 2024-02-12 04:33
@dagstuan can you confirm if the issue is addressed in our insiders version which should contain the fix mentioned above https://code.visualstudio.com/insiders

**Comment by stillhart** [comment] 2024-02-12 10:40
I am in a similar situation, MacOS Sonoma connecting to remote RHEL7

**Comment by dagstuan** [comment] 2024-02-12 11:02
@deepak1556 Yes this seems to be resolved with the insiders version. Thanks!

**Comment by deepak1556** [comment] 2024-02-12 11:18
Thanks for confirming, I will merge the issue to https://github.com/microsoft/vscode/issues/204611

@stillhart please open a separate issue at https://github.com/microsoft/vscode-remote-release with client and remote version information, remote logs.

**Closed by deepak1556** 2024-02-12 11:18 UTC
Labels: info-needed
