### ISSUE TITLE
alt+f5 doesn't work (toggles the window menus)

### ISSUE THREAD

**Issue by uriva** [microsoft/vscode#84834] opened 2019-11-14 15:12 UTC
Issue Type: <b>Bug</b>

alt+f5 should move to the next change, instead it just highlights the top menu.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-22-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.40GB (0.12GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.1.0
transformer|dak|1.6.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|3.5.1
gitlab-workflow|fat|2.1.1
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.3.1
nbpreviewer|jit|1.2.2
vscode-graphviz|joa|0.0.5
solidity|Jua|0.0.64
vscode-format-context-menu|lac|1.0.4
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
azure-account|ms-|0.8.7
cpptools|ms-|0.26.1
node-debug2|ms-|1.39.1
vsonline|ms-|1.0.1214
vscode-react-native|msj|0.13.1
java|red|0.52.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-proto3|zxh|0.3.0

</details>

**Comment by IllusionMH** [comment] 2019-11-14 16:45
/needsMoreInfo

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

What do you see in keyboard shortcuts (<kbd>F1</kbd> and `>Preferences: Open Keyboard Shortcuts`) if you search by `alt+f5`? 

Do you see something like
```json
    {
        "key": "alt+f5",
        "command": "-workbench.action.editor.nextChange",
        "when": "editorTextFocus"
    }
```

in your user `keybinding.json` (<kbd>F1</kbd> and `>Preferences: Open Keyboard Shortcuts (JSON)`) ?

**Comment by uriva** [comment] 2019-11-14 19:21
with extensions disabled it makes the vscode window smaller, as if you double click the app bar (no idea why)

**Comment by uriva** [comment] 2019-11-14 19:24
I see:
```
{ "key": "alt+f5",                "command": "workbench.action.compareEditor.nextChange",
                                     "when": "textCompareEditorVisible" },
```
and 
```
{ "key": "alt+f5",                "command": "workbench.action.editor.nextChange",
                                     "when": "editorTextFocus" },
```

**Comment by uriva** [comment] 2019-11-14 19:24
(I have no keyboard shortcut overrides of my own)

**Comment by Fi1osof** [comment] 2019-11-16 04:25
Have same issue after upgrade vscode. Alt+Tab focus on main menu instead change system language.

**Comment by egamma** [comment] 2019-11-18 15:46
Can you please follow this guide https://github.com/microsoft/vscode/wiki/Keybinding-Issues to narrow down the issue.

**Comment by duncanawoods** [comment] 2019-11-21 19:06
I think I have the same issue trying to do columnar selection using `shift-alt` and dragging. It puts focus on the window menus.

Also on Ubuntu 18.04.

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic

**Comment by alexandrudima** [comment] 2019-11-22 10:58
Very likely a duplicate of https://github.com/microsoft/vscode/issues/84227

**Comment by sbatten** [comment] 2019-11-22 23:08
yes, a duplicate, thanks @alexandrudima

**Closed by sbatten** 2019-11-22 23:08 UTC
Labels: linux
