### ISSUE TITLE
Closing a tab with ctrl-w sometimes also quits the window

### ISSUE THREAD

**Issue by gregersn** [microsoft/vscode#95041] opened 2020-04-12 09:30 UTC
- VSCode Version: 1.44
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open folder in vs code
2. Double click an image file (e.g. JPEG) so it is fully open, not preview
3. Pressing ctr-w if it is the only tab open also closes vs code

Does this issue occur when all extensions are disabled?: Yes

This also happens for other file types. If two tabs are open, and image is closed with ctrl-w the other tab is also closed.

**Comment by mjbvz** [comment] 2020-04-14 21:51
Duplicate of #82670

**Closed by mjbvz** 2020-04-14 21:51 UTC
