### ISSUE TITLE
erratic reporting of [ts] cannot find module in excluded directories

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode#7018] opened 2016-05-30 01:20 UTC
- VSCode Version: 1.1.1, 1.1.1-insider
- OS Version: OSX 10.11.5

I'm using `typings` to build `typings/` from `typings.json`, with `globalDependencies` specifying:

```
    "react-dom": "registry:dt/react-dom#0.14.0+20160412154040",
    "react": "registry:dt/react#0.14.0+20160423065914"
```

`src/client/hello.tsx` and `src/client/index.tsx` contain:

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
```

`code` and `code-insiders` report:

* `[ts] Cannot find module 'react'`
* `[ts] Cannot find module 'react-don'`

`src/client/something-else.tsx` contains the exact same lines, but `code` and `code-insiders` do not report errors.

… except, it's intermittent. I just switched back to `code`, and it's reporting errors in `hello.tsx` but not `index.tsx` this time.

Leaving `src/client` out of `tsconfig.exclude` eliminates the spurious and erratic errors, at the expense of longer build time and an extra step to remove the output. I'm using `webpack` with `ts-loader` to produce a single client output file, while also using `tsc` to produce my server side code.

**Comment by dbaeumer** [comment] 2016-05-30 12:54
@garthk can you share your project. This sounds like a setup problem with tsconfig.json but without having the folder layout and the content of some of the file it is hard to tell.

**Comment by shadowii** [comment] 2016-06-07 14:37
I'm running into the same issues. It's a mixed es6/typescript react project. Once in awhile, I can have two tsx files side by side, and one will complain about not being able to find the react module, while the other will not (with the exact same syntax `import * as React from "react";`). 

This is the current iteration of my tsconfig file. The previous iteration had ```"files": [
    "typings/index.d.ts"
  ]``` instead of the exclude section (I keep monkeying around with it in the hopes that it will work, but at this point, no matter what I seem to do, the issue still manifests). 

```
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "Scripts/Build"
  ]
}
```

I don't know if it matters, but VS2015 is typically open in the background.

**Comment by mocanu-razvan** [comment] 2016-06-12 08:51
I am experiencing similar problems with a full TypeScript project.

The relevant software versions are:
- Visual Studio Code: 1.2.0
- Node.js: 5.10.0
- OS: Windows 10

I have the following `tsconfig.json`:
```
{
  "compilerOptions": {
    "allowJs": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "outDir": "dist",
    "pretty": true,
    "target": "es5",
    "sourceMap": true,
    "sourceRoot": "lib"
  },
  "files": [
    "lib/main.ts",
    "typings/index.d.ts"
  ]
}
```

When opening files from the `lib` folder I got random errors about modules not being found. In other words, sometimes I got the errors, sometimes not.

After some time, I noticed it stabilized, i.e. no more errors were shown.

**Comment by dbaeumer** [comment] 2016-06-13 07:21
@mocanu-razvan I am pretty confident that this is caused by our files section. Adding a files sections limits our project to those two files and if you open other files not referenced by those two files then they end up in an isolated virtual project. You either need to leave out the files section (then all .ts files underneath the tsconfig.json file are automatically considered part of the project) or you need to list all files of your project in that section.

**Comment by mocanu-razvan** [comment] 2016-06-13 11:38
@dbaeumer Thanks for your hint. I guess I implicitly assumed that what is written in the TypeScript documentation applies to how Visual Studio Code works with the files:

> Any files that are referenced by those specified in the "files" property are also included.

It is much more convenient to just specify the entry point for the code and typings and let TypeScript figure out the rest. It would be obviously nice if Visual Studio Code could do the same. Do you think it would be possible to make Visual Studio Code work in this fashion?

**Comment by dbaeumer** [comment] 2016-06-14 07:39
@mocanu-razvan great. I will close the issue then.

**Closed by dbaeumer** 2016-06-14 07:39 UTC
Labels: needs more info, typescript

**Comment by rinogo** [comment] 2016-06-28 00:55
@dbaeumer I'm lucky to have found this Issue - this problem bit me pretty hard.  Perhaps a warning message can be shown in the "Problems" pane when a "virtual project" is active?  (A record of my problem on SO - http://stackoverflow.com/questions/37977444/how-to-make-vs-code-aware-of-globals)

Granted, this was certainly my "fault" since my `tsconfig.json` was configured wrong, but my project continued compiling and executing fine (I'm using webpack), so it never occurred to me that my `tsconfig.json` file might be misconfigured.

Just thought I'd provide some feedback in the hopes it can make VS Code a bit better for future noobs like me! :)

**Comment by dbaeumer** [comment] 2016-06-28 08:01
@rinogo fully agree. It is a feature request we have on the TS team
