### ISSUE TITLE
Usability: Overlap in integrated terminal

### ISSUE THREAD

**Issue by dianvaltodorov** [Microsoft/vscode#17262] opened 2016-12-15 07:24 UTC
- VSCode Version: 1.8
- OS Version: OS X El Capitam 10.11.6

Steps to Reproduce:

1. Open integrated terminal

<img width="814" alt="screen shot 2016-12-15 at 9 24 38 am" src="https://cloud.githubusercontent.com/assets/6150700/21215208/555bd576-c2a8-11e6-9384-c54b5abf5808.png">

**Comment by kaiwood** [comment] 2016-12-15 08:53
Dup of https://github.com/Microsoft/vscode/issues/15420

**Comment by kieferrm** [comment] 2016-12-16 02:07
Duplicate of #15420.

**Closed by kieferrm** 2016-12-16 02:07 UTC
