### ISSUE TITLE
definition javascript Object prompt error: [ts]  “;”

### ISSUE THREAD

**Issue by ganxunzou** [Microsoft/vscode#54868] opened 2018-07-23 13:48 UTC
![2018-07-23_214556](https://user-images.githubusercontent.com/5092728/43080342-214230fe-8ec2-11e8-8412-51681bf37825.jpg)

![2018-07-23_215005](https://user-images.githubusercontent.com/5092728/43080487-6b86a064-8ec2-11e8-8e8f-7269eb7c6a63.jpg)

**Comment by ganxunzou** [comment] 2018-07-23 13:52
![2018-07-23_215210](https://user-images.githubusercontent.com/5092728/43080629-aec10400-8ec2-11e8-85e7-4e38f56d06a1.jpg)

**Comment by ganxunzou** [comment] 2018-07-23 14:02
set `"typescript.validate.enable": false` is Ok

**Comment by mjbvz** [comment] 2018-07-23 18:08
Please share the text of the code along with all screenshots

**Comment by ehynds** [comment] 2018-07-24 12:44
This is a duplicate of #54261

**Comment by mjbvz** [comment] 2018-07-24 16:09
It is not

**Comment by ganxunzou** [comment] 2018-07-25 06:33
sorry `"typescript.validate.enable": false` is not ok. 

this is ok:
```
const config = {
  "": ""
}
```

**Comment by mjbvz** [comment] 2018-07-25 21:09
@ganxunzou Your first example is not a valid JavaScript file. The braces are interpreted as a block, not an object literal

**Closed by mjbvz** 2018-07-25 21:09 UTC
Labels: javascript, needs more info
