### ISSUE TITLE
Extension is disable but still running?

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#72386] opened 2019-04-16 04:55 UTC
Issue Type: <b>Bug</b>

As you can see, the extension in the screenshot is disabled but vscode is still trying to start it's language server?

![image](https://user-images.githubusercontent.com/30625381/56182936-9102c100-6014-11e9-8e5a-8a849a9bd0f1.png)

VS Code version: Code - Insiders 1.34.0-insider (4f212683c16977661ad51f8d13957de9d3280b30, 2019-04-15T14:12:07.955Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|-psn_0_6731371|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
pm2-explorer|ale|0.0.6
makeRunner|ale|0.1.2
sort-imports|ama|6.0.1
vscode-apollo|apo|1.5.2
vscode-custom-css|be5|3.0.3
vscode-intelephense-client|bme|1.0.13
better-phpunit|cal|1.4.0
twigcs|cer|0.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
vscode-storybook|cst|0.0.5
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.0
toggle-excluded-files|eam|1.6.0
graphviz-preview|EFa|1.3.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
file-icons|fil|1.0.16
graphviz-markdown-preview|gee|0.0.7
jira-plugin|gio|0.16.0
vscode-pull-request-github|Git|0.6.0
sass-lint|gle|1.0.5
vscode-test-explorer|hbe|2.9.3
svgeditor|hen|2.9.0
beautify|Hoo|1.4.11
rest-client|hum|0.21.2
phpcs|ika|1.0.5
smarty|imp|0.3.0
jenkinsfile-support|ivo|0.4.4
jenkins-pipeline-linter-connector|jan|1.1.7
webcomponent-generator|jer|1.0.4
puppet-vscode|jpo|0.18.0
php-cs-fixer|jun|0.1.118
npm-helper|kar|1.1.4
vscode-gutter-preview|kis|0.19.0
vscode-commitizen|Kni|0.8.2
php-symbols|lin|2.1.0
twig-language-2|mbl|0.7.6
php-namespace-resolver|Meh|1.1.7
dotenv|mik|1.0.1
references-view|ms-|0.0.26
debugger-for-chrome|msj|4.11.3
vscode-stencil-tools|nat|2.0.1
ts-prop-dag|nat|1.0.4
gremlins|nho|0.9.0
vscode-json-editor|nic|0.2.3
vscode-tap|num|1.0.2
vetur|oct|0.18.1
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.22.0
errorlens|Phi|1.1.3
material-icon-theme|PKi|3.7.0
vscode-css-peek|pra|2.2.0
ruby|reb|0.22.3
vscode-yaml|red|0.4.0
elastic|ria|0.13.3
make-auto-vars|rop|1.0.0
vscode-jest-test-adapter|rtb|0.2.0
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
sourcegraph|sou|1.0.14
vscode-taskexplorer|spm|1.14.3
easy-snippet-maker|tar|0.0.6
symfony-vscode|The|1.0.2
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.5.0
Snippet|vsc|0.4.3
vim|vsc|1.4.0
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
sort-js-object-keys|zen|1.0.6
vscode-plugin-drawio|zhf|1.0.9

(2 theme extensions excluded)

</details>

**Comment by bmewburn** [comment] 2019-04-16 08:43
I've also had a report of an extension running when disabled. https://github.com/bmewburn/vscode-intelephense/issues/420

**Comment by sandy081** [comment] 2019-04-17 17:25
Duplicate of https://github.com/Microsoft/vscode/issues/71752

**Closed by sandy081** 2019-04-17 17:25 UTC
Labels: extensions
