### ISSUE TITLE
open.vscode.dev having an option to do a full clone onto users machine (like "Open with GitHub Desktop")

### ISSUE THREAD

**Issue by jlperla** [microsoft/vscode#130741] opened 2021-08-13 04:33 UTC
Right now the https://open.vscode.dev/  option supports the user choosing a container of the new "remote repository" feature.  It would be great it if also supported just a vanilla clone and open in vscode.

I am thinking about an equivalent feature to the "Open in GitHub Desktop"option on all github repos - except opening in vscode directly instead.  See the following for the UI I mean:
![image](https://user-images.githubusercontent.com/13106721/129305156-4649e8b1-d00f-43b8-a0da-24d510c219ab.png)

To take it even further, it would be great inin that `Code` dropdown on a github repo it also had an option to "Open in VS Code"

**Comment by joyceerhl** [comment] 2022-12-06 20:02
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/24

**Closed by joyceerhl** 2022-12-06 20:02 UTC
