### ISSUE TITLE
formatOnSave make VSCode 1.6.0 going crazy on save

### ISSUE THREAD

**Issue by maroy1986** [Microsoft/vscode#13512] opened 2016-10-11 13:54 UTC
- VSCode Version: 1.6.0
- OS Version: Windows 10 Build 14393.222

Steps to Reproduce:

1. Open a JSON or HTML file (might apply to more files types)
2. Change something
3. Save and look at VSCode going crazy.

Quick video here : 
![formatonsavefreakoutlight](https://cloud.githubusercontent.com/assets/2490360/19272814/089588f6-8f98-11e6-8164-26d29ad5cfe0.gif)

Then, if you try to close the file, it will ask if you want to save the file, if you discard the change, sometime it will replace the whole file content with `null`.  Haven't been able to reproduce this one, happened one time when I record the video.

There's no error in the dev console and I disabled all my extension prior of making the reproduction video.

**Comment by isidorn** [comment] 2016-10-11 13:59
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/13462
Are you sure you ran with --disable-extensions
I can not reproduce on my win10 or os x machine

**Comment by maroy1986** [comment] 2016-10-11 14:11
I just tried again with disabling extension and I can't reproduce somehow... Before submitting the issue I really launch VSCode with the --disable-extensions, 110% sure of this but now, I can't reproduced. Furthermore, I narrowed it down to editorConfig extension. Sorry for the duplicate, I search before posting this one but didn't see it... You can close the issue I guess.

**Comment by isidorn** [comment] 2016-10-11 14:13
@maroy1986 for now I will close, but please let me know if you can repdorcue with --disable-extensions and I will reopen. Thanks a lot and can you make sure the issue is filled in the editorConfig extension repository.

**Closed by isidorn** 2016-10-11 14:13 UTC
Labels: duplicate, needs more info
