### ISSUE TITLE
vscode format js code is not i want

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#20905] opened 2017-02-20 05:33 UTC
- VSCode Version:1.9.1
- OS Version:1.12.3

```javascript
var test =true;
var a = test?1:2;
```

if i  `alt + shift + f` 

```javascript
var a = tets
    ?1
    :2

```
they are not my wanted

i need they are 

```
var a = test?1:2
```

![image](https://cloud.githubusercontent.com/assets/3990411/23113156/154eab5e-f771-11e6-8fd0-56fbaf75ca1a.png)

**Comment by schmuli** [comment] 2017-02-20 12:28
Try using: https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify

**Comment by mjbvz** [comment] 2017-02-21 19:49
@zhiqiang21 What extensions do you have installed? Can you also share your workspace settings. I'm unable to reproduce this

**Comment by zhiqiang21** [comment] 2017-02-22 00:00
my config is 

```javascript
// 将设置放入此文件中以覆盖默认设置
{
    // 控制字体系列。
    // "editor.fontFamily": "YaHei Consolas Hybrid",
    // 控制字体系列。
  "editor.fontFamily": " Monaco, 'Courier New', monospace",

    "files.autoSave": "onFocusChange",
    // 配置 glob 模式以排除文件和文件夹。
    "files.exclude": {
        "**/.idea": true,
        // "**/.gitignore": true,
        "**/.vscode": true,
        "npm-debug.log**": true,
        "**/.gitattributes": true
    },
    // 显示垂直标尺的列
    "editor.rulers": [
        80
    ],
    // 控制编辑器是否应呈现缩进参考线
    "editor.renderIndentGuides": true,
    "window.reopenFolders": "none",
    // 控制字体大小。
    "editor.fontSize": 15,
    // 控制在多少个字符后编辑器会自动换到下一行。将其设置为 0 则将打开视区宽度换行(自动换行)。将其设置为 -1 则将强制编辑器始终不换行。
    // "editor.wrappingColumn": 80,
    // 控制是否应换行。换行依据为 min(editor.wrappingColumn, viewportWidthInColumns)。
    // "editor.wordWrap": true,
    // Autoprefixer configuration options
    "TodoParser": {
        "exclude": [
            "cpp",
            "c"
        ],
        "include": [
            "js",
            "md"
        ],
        //排除的文件
        "folderExclude": [
            "node_modules",
            ".vscode"
        ],
        "only": [
            "sub-folder/sub-sub-folder"
        ],
        "markers": [
            "NOTE:",
            "REMINDER:"
        ]
    },
    // 配置是否从更新通道接收自动更新。更改后需要重启。
    "update.channel": "default",

    // 自动更新扩展
    "extensions.autoUpdate": true,

    // 启用后，将在保存文件时剪裁尾随空格。
    // "files.trimTrailingWhitespace": true,

    //保存的时候格式化代码
    // "editor.formatOnSave": true,

    // Which browsers you need to support.
    "autoprefixer.browsers": [
        "last 6 versions",
        "> 2%",
        "Firefox > 20"
    ],

    //在保存时自动修复一些警告
    "eslint.autoFixOnSave": true,

    "files.associations": {
        "*.tpl": "php",
        "*.inc": "html"
    },
    "git.confirmSync": false,

    "window.zoomLevel": 0,
    "editor.cursorStyle": "line",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "workbench.sideBar.location": "left",
    "sync.gist": "6535c0c5e860e58841c04d20edbe199b",
    "sync.lastUpload": "2017-01-07T01:34:14.620Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "1970-01-01T00:00:00.000Z",
    "sync.version": 244,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false,

    //是否关闭打开的编辑器窗口
    "explorer.openEditors.visible": 0,
    "eslint.options": {
        "configFile": "/Users/baidu/.eslintrc.js"
    },
    "terminal.external.osxExec": "iTerm.app",
    "window.showFullPath": true,
    "window.openFilesInNewWindow": "on",
    "editor.formatOnPaste": false,
    "workbench.welcome.enabled": false,
    "editor.formatOnSave": false,
    "editor.quickSuggestionsDelay": 8,
    "editor.wordWrap": true
}

```

**Comment by mjbvz** [comment] 2017-02-22 22:26
@zhiqiang21 Can you try disabling all extensions and seeing if this formatting still occurs? I don't see anything specific in your user settings that would cause this

**Comment by mjbvz** [comment] 2017-02-28 19:07
Closing as we need more info to investigate this. I suspect an extension is the root cause

**Closed by mjbvz** 2017-02-28 19:07 UTC
Labels: caused-by-extension, format, javascript, needs more info

**Comment by zhiqiang21** [comment] 2017-03-01 01:47
i disable all extensions .  it's not occurs!  Eventually I found because i install a extension `react-beautify`。

thanks for your help
