### ISSUE TITLE
Renaming is cancelled if a new file is created in the workspace

### ISSUE THREAD

**Issue by nrbabcock** [microsoft/vscode#115716] opened 2021-02-03 21:46 UTC
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Begin a long-running process which creates files within the workspace. In my example, it is a web scraping script downloading stock data.
2. Begin renaming a folder in the File Explorer sidebar
3. Every few seconds, as a new file is written, the rename is cancelled/completed

Note that this happens even in the case when the new files being created are not siblings or children of the folder being renamed -- they are hidden away in a different subfolder. But their creation causes the entire sidebar to refresh and cancels the rename operation/confirms the partially typed name.

![vscode-rename](https://user-images.githubusercontent.com/9583103/106813717-018a3000-6637-11eb-824f-855147c869e1.gif)

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by nrbabcock** [comment] 2021-02-03 21:48
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Renaming a file twice causes unwanted rename abortion (#115549)](https://www.github.com/microsoft/vscode/issues/115549)

Can confirm that this is not a duplicate.

Nice try though, bot.

**Comment by gjsjohnmurray** [comment] 2021-02-03 23:27
Looks like a duplicate of an issue fixed in the upcoming 1.53, expected this week.

**Comment by nrbabcock** [comment] 2021-02-03 23:29
> Looks like a duplicate of an issue fixed in the upcoming 1.53, expected this week.

That's great news, thanks :)

**Comment by gjsjohnmurray** [comment] 2021-02-04 05:07
/duplicate of #111652
If you still see the problem after 1.53 lands please reopen.

**Closed** 2021-02-04 05:08 UTC
Labels: *duplicate
