### ISSUE TITLE
Hard to set up non-trivial problem matcher

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#24260] opened 2017-04-07 20:01 UTC
Test tour #23385

When setting up the vue starter kit we had the following output structure:

- Errors in ./some/file.vue
  - Some error message line:column
  - Other error message line:column

Multiline patterns cannot match that.

**Comment by dbaeumer** [comment] 2017-04-10 08:36
This is exactly what a multi line problem matcher is for. However it is not trivial due to the nature of this not being trivial with regexp. What kind of matcher did you try?

Here is the matcher for eslint stylish matcher which have the same output structure:

```ts
		this.add('eslint-stylish', [
			{
				regexp: /^([^\s].*)$/,
				file: 1
			},
			{
				regexp: /^\s+(\d+):(\d+)\s+(error|warning|info)\s+(.+?)\s\s+(.*)$/,
				line: 1,
				character: 2,
				severity: 3,
				message: 4,
				code: 5,
				loop: true
			}
		]);

```

Please remember that this matcher is defined in code but the tasks.json offers the same kind of functionality. Key might be the `loop` property.

**Comment by chrmarti** [comment] 2017-04-10 17:43
Can I apply `loop` to more than just the last pattern? Each problem takes multiple lines in this case:
```
ERROR in ./src/components/About.vue
  error      semi      Extra semicolon                     
  /Users/chrmarti/Development/repos/vue-starter-kit/src/components/About.vue:18:28
        console.log(response);;;;
                              ^
  error  semi-spacing  Missing whitespace after semicolon  
  /Users/chrmarti/Development/repos/vue-starter-kit/src/components/About.vue:18:28
        console.log(response);;;;
                              ^
✖ 2 problems (2 errors, 0 warnings)
```

**Comment by Londovir** [comment] 2017-08-24 15:59
I would agree that having some way to designate a block of problem matcher regex entries as "loop true" would be beneficial in some cases. I'm working on an Angular 4 app that is running via a webpack-dev-server instance during development. Upon each save of a code file, the webpack instance recompiles the codebase and outputs any error. The problem is that the webpack instance will always output a blank line (\r) on the 1st line, then the error detail on the 2nd line, followed by a blank line (\r) on the 3rd line [if there's an additional error], followed by error detail on the 4th line, etc. For instance:

    Line 1:
    Line 2: ERROR in c:/TFSProjects/TOY/src/app/nominees.component.ts (6,30): Module "c:/TFSProjects/TOY/src/services/application/application.service" has no exported member 'NomineeInfo'.`
    Line 3:
    Line 4: ERROR in c:/TFSProjects/TOY/src/app/nominees/nominees.component.ts (6,55): Module '"c:/TFSProjects/TOY/src/services/application/application.service"' has no exported member 'SchoolNominationInfo'.

I can easily put in a regexp for `^\\s+` for my first regexp entry, followed by a far more detailed `^(ERROR|WARN)....` entry to catch all of the parts of the error message, and this works wonderfully, but it only catches the first reported error because the "loop" property only runs on the second regexp. You also cannot use JavaScript regex syntax (to my knowledge) such as `/^\\s+(ERROR|WARN)...$/gm` to try and do it with a single regexp.

If I could specify that the task problem matcher should look for looping matches against _both_ regexps, then it would work perfectly in this case (and likely others).

**Comment by alexr00** [comment] 2019-10-10 08:19
Would be solved by https://github.com/microsoft/vscode/issues/59337, so closing as duplicate.

**Closed by alexr00** 2019-10-10 08:19 UTC
Labels: feature-request, tasks
