### ISSUE TITLE
Target size of "Copy collaboration link", "Stop collaboration session" controls is less than 24x24px: A11y_Visual Studio Code_"Session Details ", "Help" sections_Target Size

### ISSUE THREAD

**Issue by Rama8345** [microsoft/vscode#209934] opened 2024-04-09 10:18 UTC
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

### Environment Details:

Application Name: Visual Studio Code
Edition Windows 11 Enterprise
Version 22H2
OS build 22621.3372
Visual Studio code
Version 1.87.2

### Github Tags:

#A11yTCS; #A11ySev2; #WCAG2.5.8; #DesktopApp; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Jan2024; #FTP; #Benchmark; #Win32; #A11yMAS;

### Pre-requisites:

Go to mouse settings and TAB to Additional mouse settings.
TAB to Browse and press ENTER.
[24x24.cur](https://microsoft-my.sharepoint.com/:u:/p/scottohara/ETmopeGhePhEqauAHj65FEsBotnZ1cozkonud-WfpYohog?e=B40D09&isSPOFile=1) download it and Apply.

### Repro Steps:

Open visual studio code application.
Install "Live share" extension.
TAB till "Share read/write" control and hit ENTER.
TAB till "Session Details ", "Help" sections.
Observe that Target size of "Copy collaboration link", "Stop collaboration session" controls is less than 24x24px.

### Actual Result:

Target size of "Copy collaboration link", "Stop collaboration session" controls is less than 24x24px.

### Expected Result:

Target size of "Copy collaboration link", "Stop collaboration session" controls should be at least 24x24 px to ensure that they are accessible to all users, including those with visual impairments.

### User Impact:

People with visual impairments may have difficulty using the "Copy collaboration link", "Stop collaboration session" controls if they are too small. The target size of 24x24 px ensures that the buttons are large enough to be seen and used easily. Without this size, people with visual impairments may not be able to access the content.

![Target size](https://github.com/microsoft/vscode/assets/115216656/0620be09-e4c2-4b16-9ac8-9af834c68520)

**Comment by meganrogge** [comment] 2024-04-10 14:32
are you suggesting that this is the case for all tree view toolbar actions? such as the ones in the SCM view?

Zooming in causes the buttons to be larger, enabling them to be viewed by visually impaired users. 

Can you pls provide a link to the guidance which suggests that at the default zoom level, buttons must be at least 24 by 24 px?

cc @isidorn for any historical discussion here.

<img width="410" alt="Screenshot 2024-04-10 at 7 29 44 AM" src="https://github.com/microsoft/vscode/assets/29464607/c5c6dfaa-b3cb-4553-9bd3-2a2ee054bf89">

**Comment by isidorn** [comment] 2024-04-10 15:51
I suggest to close this as designed. Since this works just well once the user is zoomed-in.

**Closed** 2024-04-10 17:41 UTC

**Comment by kapilvaishna** [comment] 2024-04-12 09:16
@meganrogge Here users with dexterity limitations and those who have difficulty with fine motor movement find it difficult to accurately activate small targets when there are other targets that are too close.it will not affect visually impaired users.
since it is a valid bug so could you please reactivated this bug.

**Comment by isidorn** [comment] 2024-04-12 09:37
@kapilvaishna users with dexterity limitations can use "F1 > zoom" command to zoom in the screen. Please read these docs https://code.visualstudio.com/docs/editor/accessibility#_zoom

**Comment by kapilvaishna** [comment] 2024-04-15 08:41
@isidorn Manly target size is for who have difficulty with fine motor movement find it difficult to accurately activate small targets when there are other targets that are too close. so, user with motor disability still block there. 
So could you please reopen the bug.

**Comment by kapilvaishna** [comment] 2024-04-15 08:59
@isidorn  yes I can zoom in with "Ctl +" and that time it will pass the target size. but as per Target size (WCAG2.5.8). We check the target size on default zoom level only. I will check once with SMEs about it and let you know.

**Comment by isidorn** [comment] 2024-04-15 09:10
@kapilvaishna thank you for your understanding and for checking with SME.

**Comment by Rama8345** [comment] 2024-04-17 08:36
@isidorn 
As per discussion with the SME's in Office hours they told to reopen the issue. Please reopen it.

**Comment by isidorn** [comment] 2024-04-17 08:39
@Rama8345 please tell them SME to reach out to me on Teams. My alias is inikolic

Also based on this description - this is a bug for live share. Live share can fix this by having a custom view and a large collaboration button. So not something that VS Code has to do.

Thank you
