### ISSUE TITLE
Click to Expand Tab on Split Screen Broken

### ISSUE THREAD

**Issue by teqnickels** [Microsoft/vscode#54504] opened 2018-07-17 19:19 UTC
Steps to Reproduce:

1. Open VSCode and view 2 files/tabs
2. Split one of the tabs right
3. Minimize/resize the right tab as much as possible by sliding the tab as far right as possible. 
4. Try single & double clicking into the minimized tab to expand it

This used action used to expand the minimized tab to open at about 80%. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-07-17 19:35
Duplicate of https://github.com/Microsoft/vscode/issues/51614

**Closed by bpasero** 2018-07-17 19:35 UTC
