### ISSUE TITLE
[js] No color to variables not in the same line as var

### ISSUE THREAD

**Issue by EthraZa** [Microsoft/vscode#4330] opened 2016-03-16 17:39 UTC
- VSCode Version: 0.10.11
- OS Version: Ubuntu 14.04
- Theme: Dark+ (dark default)

Steps to Reproduce:

1. Create file test.js
2. Add code to test.js
~~~
var a = 1, b = 2,
      c = 3, d = 4;
~~~
The a and b variables get colored (light blue on this theme), the c and d variables get no color (white on this theme).

Also, whe you use the variable it get no special color, but I'm not sure if this is intended. I would prefer it colored as well.

All variables get no color, nor the console.log (the hole line is white on this theme):
~~~
console.log(a,b,c,d);
~~~

**Comment by aeschli** [comment] 2016-03-17 07:20
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/121

**Closed by aeschli** 2016-03-17 07:20 UTC
