### ISSUE TITLE
Interactive window doesn't auto scroll to the bottom

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127544] opened 2021-06-29 19:06 UTC
Testing #127378

Run a cell like so:

```
import time
while (True):
    time.sleep(.1)
    print('*')
```

It should be scrolling the whole time.

**Comment by repied** [comment] 2021-07-15 14:10
The interactive window doesn't scroll automatically at all for me. Even when I execute cells one after another, the interactive window doesn't scroll.

![image](https://user-images.githubusercontent.com/15749663/125802262-976b6039-d2a3-483e-988b-bc8233b68a6a.png)

**Comment by joyceerhl** [comment] 2021-07-16 04:03
Fixed in latest build of Jupyter extension for VS Code Insiders and duplicate of https://github.com/microsoft/vscode-jupyter/issues/6603. 

@repied, this issue tracks the new native interactive window UI, which I'm assuming you explicitly opted into using `jupyter.enableNativeInteractiveWindow`? If so you should get the fix in the next stable VS Code (~3 weeks from now), or you can install VS Code Insiders to get the fix tonight. 

If the interactive window is not scrolling for you and you have not configured the setting I mentioned above, that is a bug, please open an issue at https://github.com/microsoft/vscode-jupyter. Thank you!

**Closed by joyceerhl** 2021-07-16 04:03 UTC
Labels: feature-request, interactive-window
