### ISSUE TITLE
⌘+P does not toggle"Go to file" any more on OSX

### ISSUE THREAD

**Issue by ronangaillard** [Microsoft/vscode#17687] opened 2016-12-21 15:20 UTC
- VSCode Version: 1.8.1
- OS Version: OSX 10.12.1

Steps to Reproduce:

1. Press ⌘+P
2. Test input does not show up

But triggering it using _Go->Go to file..._ works.

**Comment by egamma** [comment] 2016-12-21 16:03
I fail to reproduce this on OS X.

What key binding do you see in the `Go` menu assigned to `Go to File...` command?

**Comment by emattiazzi** [comment] 2016-12-21 16:19
Can't reproduce this error as well. 
Open your `keybindings.json` (Open with `⌘+Shift+P -> Open Keyboard Shortcuts` and check if you have the following line:
`{ "key": "cmd+p",                 "command": "workbench.action.quickOpen" }`

**Comment by ronangaillard** [comment] 2016-12-21 17:32
I do have `{ "key": "cmd+p", "command": "workbench.action.quickOpen" }` in `keybindings.json` .

I can reproduce bug after reinstalling VSCode, and even after reinstalling Mac OS X and VS Code. Always the same issue.

By the way `⌘+Shift+P` shorcut does not work also.

**Comment by egamma** [comment] 2016-12-22 13:14
@ronangaillard ⌘+P is one of the most popular short cuts of VS Code and I haven't seen reports from other OS X users having issues with it. Could it be that there is an issue with the ⌘+P key? Does this short cut work in other applications?

One option is to define another keybinding in `keybindings.json`

**Comment by ronangaillard** [comment] 2016-12-22 16:27
@egamma you're right that it is weird that no one else has this issue.

Affecting the shortcut to `⌘+M` works.

What is also weird is that the shortcut `⌘+P` worked before update, and that the P key and command key are working well.

**Comment by egamma** [comment] 2016-12-23 16:01
Assigning to @bpasero he might have other ideas what is going on.

**Comment by bpasero** [comment] 2017-01-02 09:35
@ronangaillard 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by life1347** [comment] 2017-01-03 12:09
https://github.com/Microsoft/vscode/issues/17884#issuecomment-270101410

**Comment by bpasero** [comment] 2017-01-03 13:00
@life1347 can you explain how that comment relates to this problem?

**Comment by life1347** [comment] 2017-01-15 11:23
Hi @bpasero 
My problem is that the hotkey shift+cmd+left cannot work properly, and I could reproduce the problem this problem after reinstalling VSCode. In the end, I tried the method described here([#227](http://forums.macrumors.com/threads/macos-10-12-sierra-post-bugs-and-fixes-here.1991731/page-10#post-23617306)) and problem solved. After some testing, I found that  /Users/<user>/Library/Preferences/com.apple.symbolichotkeys.plist may cause this problem. Once the plist is deleted everything goes well again.

**Comment by bpasero** [comment] 2017-01-16 06:04
@ronangaillard can you try what @life1347 suggests?

**Comment by ronangaillard** [comment] 2017-01-22 10:02
I do not have access to my mac yet, I'll try by the end of the week !

**Comment by bpasero** [comment] 2017-01-30 13:40
Assuming this works now, closing.

**Closed by bpasero** 2017-01-30 13:40 UTC
Labels: needs more info
