### ISSUE TITLE
Match highlighting in "recently opened" doesn't go away

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85844] opened 2019-11-29 23:35 UTC
I've seen this randomly a few times

- Open recently opened
- Type a few characters, open the match folder in a new window with cmd+enter
- In the original window, open recently opened again
- The match highlight is still there on some row

Seems to happen more when the target window was already open?

![image](https://user-images.githubusercontent.com/323878/69892729-9966ee00-12bd-11ea-8ad1-ec4efbc69ec1.png)

**Comment by chrmarti** [comment] 2019-12-02 08:09
Cannot reproduce. Is that the desktop client? Which platform?

**Comment by roblourens** [comment] 2019-12-02 19:10
Desktop client, mac.

**Comment by roblourens** [comment] 2019-12-02 19:11
It's not 100%, I can't repro it right now. But when it starts happening I've been able to hit it several times in a row. So if you've changed anything here, let me know where to set a breakpoint and I can try to debug next time.

**Comment by chrmarti** [comment] 2019-12-03 07:59
I think, it's connected to the new sorting flag. That's only used by the simple file dialog. Steps:
- `Ctrl + R`.
- Type 'vscode'.
- `Ctrl + O`.
- `Ctrl + R`.

I need to check why the highlighting is not always cleared.

**Comment by chrmarti** [comment] 2019-12-04 13:37
https://github.com/microsoft/vscode/commit/8bb358f24dba9545abaa7b4a2db02568fd7398d0 added checks that will return early if the label's text is still the same. That doesn't consider highlights and other options. Will do a PR for @sandy081 to review. (/cc @joaomoreno)

**Comment by isidorn** [comment] 2019-12-04 16:29
This fix breaks the active decoration in the compressed tree.
Due to that I will have to revert it. Since that issue is more sever than the highlighthing not going away some times. 
@chrmarti we can look together into a better fix for this.

![Screenshot 2019-12-04 at 17 27 39](https://user-images.githubusercontent.com/1926584/70160806-622c7e80-16bb-11ea-991a-71392ce67044.png)

**Comment by isidorn** [comment] 2019-12-04 16:35
I pushed a fix for this that does not break the compact tree. @roblourens let me know if you can still repro.

**Closed** 2019-12-04 16:35 UTC
Labels: bug, quick-pick
