### ISSUE TITLE
Smoke test: quick access is not running commands properly

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#105853] opened 2020-09-01 17:11 UTC
Testing #105750 on Linux

Smoke tests are using QuickAccess to run commands but in current master they are not running successfully:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/876920/91884548-13584900-ec3b-11ea-9462-e4b97429a6fc.png">

**Comment by bpasero** [comment] 2020-09-02 06:13
I did not touch quick open this milestone, @chrmarti ?

**Comment by bpasero** [comment] 2020-09-02 06:29
I can reproduce only when run against a insiders build, not out of sources. Hm, at least on my Linux I see that accessibility support is enabled for me, I am not sure if that is the same for you @rebornix if you check the status bar notification.

![image](https://user-images.githubusercontent.com/900690/91939627-765ae600-ecf6-11ea-8879-d4660a43288e.png)

If accessibility mode is enabled, I think quick open behaves differently and we do not automatically pre-select the first entry in quick open.

I suggest to fix this by having a command line flag that forces to disable any accessibility mode for smoke tests.

**Comment by isidorn** [comment] 2020-09-02 06:51
Alternative idea: quick pick could write to the user settings via this api 
`"editor.accessibilitySupport": "off"`
https://github.com/microsoft/vscode/blob/00754e4babebc9ee5aa881234bc16366c4f32aa9/test/automation/src/settings.ts#L17

Or smoke test could do it when it starts.

**Comment by bpasero** [comment] 2020-09-02 07:19
@isidorn Not sure, I think for writing to settings we need to use quick open to open settings. That is actually the test that fails here: opening settings.

**Comment by isidorn** [comment] 2020-09-02 07:27
Yeah you are right..
Alternative idea: it does not matter if we press down or not if there is just one item - there is no effect. Smoke test should handle even if the first item gets auto selected by always pressing down.

**Comment by bpasero** [comment] 2020-09-02 07:31
Actually we seem to be having a method [`selectQuickInputElement`](https://github.com/microsoft/vscode/blob/00754e4babebc9ee5aa881234bc16366c4f32aa9/test/automation/src/quickinput.ts#L42) which supports arrowing down, but if we expect the first element to be a match we typically don't go down.

Maybe @chrmarti could beef this method up to still go 1 down if he can detect that no element is selected in quick input.

**Comment by bpasero** [comment] 2020-09-02 12:29
Looking more into this it seems that on Linux we now detect accessibility mode a lot more aggressively than before. To reproduce:
* run `code --user-data-dir <fresh dir>` and compare that to
* `code-insiders --user-data-dir <fresh dir>

In insiders I see that accessibility mode has been enabled for me:

![image](https://user-images.githubusercontent.com/900690/91981108-a0c59700-ed28-11ea-8ff2-f3913763f713.png)

This does not happen with Code Stable, so I suspect a change maybe with the Electron 9 update?

Worth mentioning that I do have these tools installed in Ubuntu:

![image](https://user-images.githubusercontent.com/900690/91981166-b2a73a00-ed28-11ea-9a47-4f3622c10197.png)

But all the checkmarks are off.

**Comment by bpasero** [comment] 2020-09-02 12:32
OH false alarm! I had this configured in my `argv.json`:

`force-renderer-accessibility: true`

Once I removed this the smoketest works fine.

**Comment by bpasero** [comment] 2020-09-02 12:33
We currently do not support to change the location of that file, as such duplicate of https://github.com/microsoft/vscode/issues/84808

@rebornix let me know if this fix fixes it for you as well?

**Closed** 2020-09-03 06:18 UTC
Labels: needs more info, smoke-test-failure
