### ISSUE TITLE
vscode terminal disrespects `cls` command in windows

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#23227] opened 2017-03-26 01:30 UTC
say i have a batch file that starts with
```
cls 
```
which clears the output buffer of the console

when such batch file is run under vs the `cls` command gets ignored, the console still has all output from the previous commands

**Comment by Tyriar** [comment] 2017-03-29 20:55
I believe this is a duplicate of this: https://github.com/sourcelair/xterm.js/issues/106

**Closed by Tyriar** 2017-03-29 20:55 UTC
