### ISSUE TITLE
Python double quoted strings incorrectly tokenized as single quoted strings

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode#102934] opened 2020-07-20 09:23 UTC
Issue Type: <b>Bug</b>

The following custom setting will set both single and double quoted strings to red in python.
Expected to show single quoted strings in red and double in grey.

```
"editor.tokenColorCustomizations": {
        "[Atom One Dark]": {
            "textMateRules": [
                {
                    "scope":"string.quoted.single",
                    "settings": {
                        "foreground": "#FF0000",
                        "fontStyle": "bold"
                    }
                },
                {
                    "scope":"string.quoted.double",
                    "settings": {
                        "foreground": "#fff",
                        "fontStyle": "bold"
                    }
                }
            ]
        }
    }
```

Using developer inspect tokens shows both double and single quoted strings as `string.quoted.single.python`

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 4.15.0-109-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4384)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.36GB (7.03GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.4.0
gitstash|art|3.2.0
simple-react-snippets|bur|1.2.3
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
code-runner|for|0.11.0
todo-tree|Gru|0.0.178
svg|joc|1.3.6
docthis|joe|0.7.1
linter-gfortran|krv|2.2.1
restructuredtext|lex|129.0.0
rainbow-csv|mec|1.7.0
git-graph|mhu|1.24.0
code-beautifier|mic|2.3.3
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.3.1
python|ms-|2020.7.94776
vscode-pylance|ms-|2020.7.2
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-json-editor|nic|0.2.3
vscode-yaml|red|0.9.1
unique-window-colors|stu|1.0.51
latex-support|tor|3.2.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.1.0

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2020-07-21 14:33
Duplicate of https://github.com/MagicStack/MagicPython/issues/172

**Closed** 2020-07-21 14:33 UTC
Labels: grammar, upstream-issue-linked
