### ISSUE TITLE
Settings editor loses query when moved to a different editor group

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#147650] opened 2022-04-18 21:59 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open settings editor UI
2. Type in a query
3. Drag editor into a new editor group
4. :bug: query is lost

Not sure if regression but it's been rather annoying--this usually happens when I open the settings editor UI to look up a setting, it opens on top of my code editor, I drag it to the side so I can have it as a reference, and then my query (and therefore also the setting I was just looking at) is cleared

**Comment by rzhao271** [comment] 2022-04-18 22:16
Duplicate of https://github.com/microsoft/vscode/issues/133444

**Closed** 2022-04-18 22:16 UTC
Labels: *duplicate
