### ISSUE TITLE
Visual Studio Code Locks Up When Trying to Edit a header file.

### ISSUE THREAD

**Issue by jschwartzman** [microsoft/vscode#76921] opened 2019-07-09 01:41 UTC
Issue Type: <b>Bug</b>

Every time a switch to a header file, code locks up and does not respond to keystrokes or mouse clicks.  Code eventually tells you that the window is not responding. I disabled all extensions but problem still exists.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.15-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (4 x 3503)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.69GB (1.65GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
code-gnu-global|aus|0.2.2
masm|blt|0.0.3
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
Go|ms-|0.11.3
printcode|nob|3.0.0
theme-dawn2|p2w|1.0.1
RustyCode|sav|0.19.1
crates|ser|0.4.3

(3 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2019-07-09 07:46
Duplicate of https://github.com/microsoft/vscode/issues/76774
We rolled back the C++ grammar version match 1.35 so this will be fixed in 1.36.1. It is also already fixed in Insiders.

**Closed by alexr00** 2019-07-09 07:46 UTC
