### ISSUE TITLE
Jupyter Interactive Window view variables in new window similar to Spyder

### ISSUE THREAD

**Issue by thydzik** [microsoft/vscode#229467] opened 2024-09-24 02:41 UTC
Large string variables when viewing the variable in Interactive Window shall be enabled to click into to either select and copy or pop-up a larger field box with the full variable shown without any cutoff.

![image](https://github.com/user-attachments/assets/415f8a3d-6a3c-4f8e-84fa-065130ff19ca)

**Comment by amunger** [comment] 2024-09-24 16:50
try out the setting `"notebook.experimental.variablesView": true` and the new view should show up in the debug sidebar.
duplicate of https://github.com/microsoft/vscode-jupyter/issues/1148

**Closed by amunger** 2024-09-24 16:50 UTC
