### ISSUE TITLE
If you delete one line that is not the last line, the underline of the last line will not disappear

### ISSUE THREAD

**Issue by huzy96** [microsoft/vscode#82643] opened 2019-10-16 01:40 UTC
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/18290163/66881252-e4bc8a00-eff8-11e9-914e-f46c3acc7fd6.png)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.03GB free)|
|Process Argv|C:\Users\huzha\Desktop\marathon_cke.sh|
|Screen Reader|no|
|VM|60%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.34
vscode-language-pack-zh-hans|MS-|1.39.3

</details>

**Comment by roblourens** [comment] 2019-10-16 04:14
> Delete the last line of content, the last line of the hyperlink will not disappear

It looks like you had another line which you deleted and that left the underline for the link.

**Comment by alexandrudima** [comment] 2019-10-17 13:58
Duplicate of #48321

**Closed by alexandrudima** 2019-10-17 13:58 UTC
