### ISSUE TITLE
Automatic imports break with Flow's `import type`

### ISSUE THREAD

**Issue by karlhorky** [Microsoft/vscode#46425] opened 2018-03-23 14:45 UTC
VSCode Version: 1.21.1
OS Version: macOS 10.13.3 (17D102)

Re-submitting @jlyons-bgl's issue to ask for a re-consideration of it. Could an exception not be made for this one syntax?

I would just comment on the issue itself but it has been locked.

Original issue (#39743):

The new automatic import feature is great! But I have an issue when using it with Flow.

Starting with:

```js
import { TAccount } from './TAccount'
import type { SimilarTransactionJson, TAccountJson } from '../../types/BankingTypes'
```

and selecting an auto import Intellisense option I end up with:

```js
import { TAccount } from './TAccount'
import typeimport { Entry } from './Entry';
 { SimilarTransactionJson, TAccountJson } from '../../types/BankingTypes'
```

Reproduces without extensions: Yes

**Comment by karlhorky** [comment] 2018-03-23 14:50
I suppose this will just get closed with a "won't fix" like https://github.com/Microsoft/vscode/issues/44150#issuecomment-367450284 or https://github.com/Microsoft/vscode/issues/39743#issuecomment-349729597, but maybe it would be an idea to re-consider making a single exception for `import type`, since this will probably keep coming up.

**Comment by mjbvz** [comment] 2018-03-23 19:18
Yes, duplicate of those issues. We can't guarantee that the built-in js/ts extension will ever do the right thing for flow code even though it uses the `.js` file extension. Both the suggestions and the auto-imports need to come from the Flow vscode extension

**Closed by mjbvz** 2018-03-23 19:18 UTC
Labels: javascript
