### ISSUE TITLE
In the HTML file, the Emmet syntax for the CSS style tag is wrong.

### ISSUE THREAD

**Issue by mishengqiang** [Microsoft/vscode#13842] opened 2016-10-17 05:49 UTC
- VSCode Version:
 1.6.0 (1.6.0)
 e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
- OS Version:
 macOS Sierra 10.12

Steps to Reproduce:

1. 
![git](https://cloud.githubusercontent.com/assets/9413032/19426596/62fc390c-9470-11e6-83a9-93e8c45a1b04.gif)

**Comment by GaryChangCN** [comment] 2016-10-17 08:46
+1

**Comment by aeschli** [comment] 2016-10-17 14:00
duplicate of #11081

**Closed by aeschli** 2016-10-17 14:00 UTC
