### ISSUE TITLE
Column selection

### ISSUE THREAD

**Issue by SiriusGuo** [Microsoft/vscode#1515] opened 2015-12-21 01:48 UTC
Just a remark, though: the default key bindings for "Shrink/expand selection" (Shift+Alt+Left/Right) conflict with a feature that doesn't exist yet, but which I hope will be implemented someday: column selection. In Visual Studio, and many other editors, if you hold Alt at the same time as you change the selection with Shift+arrows, it changes the selection across multiple lines. So Shift+Alt+arrows should be reserved for column selection, unless you plan to never implement this (very useful) feature.

**Comment by bpasero** [comment] 2015-12-23 16:18
@alexandrudima fyi

**Comment by zry656565** [comment] 2015-12-29 07:41
So hope that Code can support such a useful feature.

**Comment by groksrc** [comment] 2016-01-27 18:36
I'd like to see this feature as well, much please and thanks!

**Comment by diegostamigni** [comment] 2016-02-10 12:30
+1

**Comment by alexandrudima** [comment] 2016-02-22 08:58
@SiriusGuo We support independent multiple cursors, which are slightly more powerful than column selection. So, you could use `Ctrl+Alt+Down/Up` to add more cursors and then regular `shift+left/right` to expand each cursor's selection. Or `ctrl+shift+left/right`, or `end`, etc.

@zry656565 @groksrc @diegostamigni Is there something I'm missing or can you get column selection and more with the multicursor support we already have?

![multicursor](https://cloud.githubusercontent.com/assets/5047891/13213644/a91acca0-d94a-11e5-98c1-f85425a4fcda.gif)

**Comment by groksrc** [comment] 2016-02-22 15:39
The multicursor support is nice, but it's a workaround for editing columns of text. On mac Ctrl+Alt+Down/Up writes a non-printable character instead of adding cursors. I have Command+Alt+Down/Up mapped with [Spectacle](https://github.com/eczarny/spectacle) for window management so that doesn't work either. The best I can do is Command+Click for new cursors. I'd like to be able to just Alt+Click/Drag to select an area of text for editing like Sublime.

**Comment by alexandrudima** [comment] 2016-02-22 16:55
@groksrc The default keybindings on mac are `cmd+alt+down/up`.

Perhaps Spectacle eats them up and they never reach us. Please try to edit your `keybindings.json` to change them. Specifically insert different keybindings in the `key` fields below:

```
[
{ "key": "ctrl+alt+up",           "command": "editor.action.insertCursorAbove",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+alt+down",         "command": "editor.action.insertCursorBelow",
                                     "when": "editorTextFocus" }
]
```

**Comment by groksrc** [comment] 2016-02-22 19:51
You are correct, Spectacle is eating them so they aren't reaching the editor. So these keybindings do work, but this still feels like a workaround. It's a lot of keystrokes to select something that's say 4 columns wide and 50 lines long.

Also, say you do something like add 4 cursors and select to the end of the line. Unless all of the lines are the same length your cursors are now in different columns. This is usually not what you want when doing columnar editing.

**Comment by riclf** [comment] 2016-02-27 02:15
Listen, vertical or column selection is a very simple concept, not including grander concepts like "multiple cursors". You put your cursor where you want to start, hold the Alt key down for the duration, and with the mouse move the cursor to the right and then down to create the desired box of selected text. One keystroke held down, the Alt Key, then a simple drawing action.  Please, don't make this thing be some fangled 3-finger salute!

**Comment by egamma** [comment] 2016-02-27 17:39
// @alexandrudima

**Comment by alexandrudima** [comment] 2016-02-29 16:42
@riclf Thank you for your input, I am really just trying to understand how the feature should work, I'm not trying to sell anything :).

I have pushed a change just now that adds column select with the mouse with the same modifiers as Visual Studio (Shift and Alt pressed), the key difference being currently our cursors cannot float on air (they get bounded by the text shape).

To better explain, here is VS:
![column-mouse-vs](https://cloud.githubusercontent.com/assets/5047891/13401144/47e9ea9e-df0b-11e5-8552-f2646376d763.gif)

Here is VSCode on master:
![column-mouse-vscode](https://cloud.githubusercontent.com/assets/5047891/13401213/8b01ad4e-df0b-11e5-9ef7-ff8cf3c14a1c.gif)

Is this different behaviour a deal-breaker when it comes to using column selection? Again, I am asking to understand how the feature should work and how it is being used so I can figure out how to implement it.

**Comment by groksrc** [comment] 2016-02-29 22:13
That works for me, what you have is the same as how it works in Sublime Text.

**Comment by riclf** [comment] 2016-02-29 22:26
Alexandru,

Thank you for reaching out. The way VS performs a vertical selection is the
³correct" way, in that it is the classic way we expect that action to
perform, coming from other editors.

Your second demo as VSCode performs on master is interesting and value but
not as an expected action. For that reason it leaves the expected vertical
selection unfulfilled.

The problem with the current VSCode behavior is that it specifies in the
design that my ³box² selection will always be to an ³end of line² condition
and include the CR. That is certainly not a real life case. A vertical
selection is my desired box of data, not necessarily always out to the CR.
The current implementation is not a verbal selection box behavior.

In a perfect world the classic VS way would be the default, implemented with
just an Alt Key and mouse draw.  Then maybe your current VSCode way with a
Alt+Shift  and mouse movement, as a secondary option. But it is not very
useable.

If I could only have one I would much prefer the expected classic  behavior,
as in VS, as that permits me to select the vertical data what I want/choose
and not be forced to include more data + CR¹s in my selection.

Can we have the classic behavior as implemented in VS?

Thanks for asking !

-Ric


Richard Fink
1160 Mission St, #2108
San Francisco, CA 94103
Tel:   415.409.6396
Cell:  415.302.7317
LinkedIn:  <www.linkedin.com/in/richardfink/>
<www.linkedin.com/in/richardfink/> Profile
<http://www.linkedin.com/in/richardfink/>
Twitter:  @ricfink <http://twitter.com/RicFink>
Web:  paylive.co <http://paylive.co>


From: Alexandru Dima <notifications@github.com>
Reply-To: Microsoft/vscode
<reply+00024fd8c356d6b52add6ef58a8d2cdf910414f32c50cf7292cf0000000112ec372a9
2a169ce0757d217@reply.github.com>
Date: Monday, February 29, 2016 at 8:43 AM
To: Microsoft/vscode <vscode@noreply.github.com>
Cc: Ric Fink <ric@richardfink.com>
Subject: Re: [vscode] Column selection (#1515)

@riclf <https://github.com/riclf>  Thank you for your input, I am really
just trying to understand how the feature should work, I'm not trying to
sell anything :).

I have pushed a change just now that adds column select with the mouse with
the same modifiers as Visual Studio (Shift and Alt pressed), the key
difference being currently our cursors cannot float on air (they get bounded
by the text shape).

To better explain, here is VS:
 <https://cloud.githubusercontent.com/assets/5047891/13401144/47e9ea9e-df0b-
11e5-8552-f2646376d763.gif>

Here is VSCode on master:
 <https://cloud.githubusercontent.com/assets/5047891/13401213/8b01ad4e-df0b-
11e5-9ef7-ff8cf3c14a1c.gif>

Is this different behaviour a deal-breaker when it comes to using column
selection? Again, I am asking to understand how the feature should work and
how it is being used so I can figure out how to implement it.


Reply to this email directly or view it on GitHub
<https://github.com/Microsoft/vscode/issues/1515#issuecomment-190282281> .

**Comment by Gimmeaphatbeat** [comment] 2016-03-02 12:09
@riclf, doesn't the 2nd example give the same 'result' as the 1st? It's just not as visually appealing.

**Comment by crisward** [comment] 2016-03-02 12:28
The second is how it works in sublime and atom, though I'd prefer just alt+drag like sublime.

Looking forward to this, working without it is painful...

**Comment by crisward** [comment] 2016-03-02 12:33
Interestingly, sublime doesn't put cursors on empty lines...

![multi-cursor](https://cloud.githubusercontent.com/assets/3109157/13460525/ffb7ba9e-e072-11e5-81c9-6e5f986dd005.gif)

**Comment by jcward** [comment] 2016-03-02 13:13
FYI, emacs CUA rectangle selection shows the rect on all lines (even empty lines.) While delete only affects populated lines (obviously) and never deletes a CR. Inserting even affects blank lines (e.g. the comment chars.) And I personally like to nav with arrows, not the mouse.

![test](https://cloud.githubusercontent.com/assets/2192439/13461217/63e032fc-e03d-11e5-869a-2c016bd7fddc.gif)

Cheers!

**Comment by mphaney** [comment] 2016-03-02 16:54
@egamma, thank you for being so attentive to this issue.  I saw your post on 1060 referring to this post as well :-)  I wholeheartedly agree that the multiple cursors are more powerful...but sometimes "simpler" is what's needed.  Is that not the heart and soul of Code in the first place?  The current behavior, using "Insert Cursor Above/Below" yields ok-but-not-perfect results:

![blockselectioncurrent](https://cloud.githubusercontent.com/assets/2546626/13467678/26495880-e054-11e5-9bbc-d3fb14574d3a.gif)

While I believe the desired behavior, some key combination (Alt seems traditional) and a mouse-drag is more flexible.  EditPlus, like the several editors above, also displays this:

![blockselectiondesired](https://cloud.githubusercontent.com/assets/2546626/13467708/47ad6b92-e054-11e5-8942-4e221223dc33.gif)

I'd sure love to see this idea revisited as it's one of the hold-ups for my adoption of Code as well.  Thank you again for all your hard work!

**Comment by ericwj** [comment] 2016-03-02 17:06
+1 for using Alt+Drag to select a rectangular area.

Plus, using multiple cursors is powerful in some situations, but the behaviour is very dependent on Codes word boundaries, which are odd imho.

At the very least, the selection crosses lines as demonstrated above in e.g. the @egamma post and I don't see how that would ever be useful or intended.

And I'm using Visual Studio Code along full Visual Studio most of the time. The key combinations are absolutely alien to me. I'm wondering why Visual Studio Code doesn't align with full Visual Studio - possibly after (or before) selecting a(nother) (built-in) keyboard configuration.

**Comment by dvlsg** [comment] 2016-03-03 00:19
@alexandrudima The gif of your VSCode master example looks fantastic! Maybe perfect, depending on whether or not cursors should be placed on empty lines. I've never really thought about it before, to be honest, but I've never come across any issues when using editors that skip the empty lines when using column selection.

I would love to see Middle Click Drag without any key modifiers as one of the shortcuts (or the option to rebind to mouse buttons -- is this available?) for column selection so I can select columns without my keyboard. This matches one of the shortcuts [sublime provides](https://www.sublimetext.com/docs/3/column_selection.html).

I've got two multi-cursor pieces which I don't think have been discussed yet. Maybe they're out of scope for this, since they don't really lead to selecting a specific block of columns. They do relate directly to multiple cursors, though.

The first is the ability to Ctrl + Left Click to insert another cursor. This would give users the flexibility to place multiple cursors wherever they need them, even if they do not line up as proper columns or are separated by multiple lines.

The second is the ability to run a Find (Ctrl + F) and then place cursors at every item which matches the find criteria (in sublime, Alt + Enter, also selects / highlights every match). Surprisingly useful / fast if you need to do something slightly more complicated than a find and replace. I've been finding myself using this in favor of find and replace entirely, and just typing out the replacements with those cursors.

**Comment by IntelOrca** [comment] 2016-03-03 00:32
I think ALT and click dragging should be implemented in the same way as VS. For this to work, VSCode needs to support virtual space, the idea is that you should be able to hold ALT and click anywhere in space and start typing. This will automatically insert spaces up to the cursor. Once this is supported it should make sense to be able to drag a box selection anywhere which will allow you to type characters all aligned the same column position - regardless of what the lengths of the lines are.

**Comment by glen-84** [comment] 2016-03-04 20:34
Is this not a duplicate of #84?

**Comment by mrange** [comment] 2016-03-05 15:25
As others has mentioned I think VS Code should allow the same behavior as VS does it (if that means supporting virtual space that is even better). "Insert Cursor Below" as it works today is only half-way there. To me this is very important.

**Comment by ccirello** [comment] 2016-03-10 09:46
+1

**Comment by jreadytalk** [comment] 2016-03-11 19:37
Notepad++ uses Alt+Drag, too.

**Comment by alexandrudima** [comment] 2016-03-14 20:21
Comes out in March

**Closed by alexandrudima** 2016-03-14 20:21 UTC
Labels: editor, feature-request

**Comment by replay111** [comment] 2016-03-16 09:15
Any idea/hint how to use column selection in OSX ? :D
cmd+alt+arrows(u/d) works fine, but I cant figure how to use mouse to select block

**Comment by crisward** [comment] 2016-03-16 10:01
This is not available yet, next release.

**Comment by mrange** [comment] 2016-03-16 18:37
Tried the insiders code today. While I do think the column selection behavior is a major improvement over previous behavior IMHO the lack of virtual space is limiting the use. Will look if there's an issue for this.

**Comment by groksrc** [comment] 2016-03-16 19:44
I'm having some trouble getting it to work at all on OSX or Ubuntu 15.04 VM. I have tried several things. I quit Spectacle to make sure nothing was hijacking my keystrokes. I also tried it reinstalling it: Version 0.10.12-insider (0.10.12-insider). Do I need to set up keybindings for it in keybindings.json?

**Comment by alexandrudima** [comment] 2016-03-17 07:41
@groksrc I could not find anymore free keybindings on Linux by default, so on Linux, you'd need to bind them in your `keybindings.json`. E.g.:

```
{ "key": "ctrl+shift+alt+down",   "command": "cursorColumnSelectDown",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+left",   "command": "cursorColumnSelectLeft",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+pageup", "command": "cursorColumnSelectPageUp",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+right",  "command": "cursorColumnSelectRight",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+alt+up",     "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
```

**Comment by Uristocles** [comment] 2016-03-21 14:02
Any suggestions for how to troubleshoot the keyboard shortcuts CTRL-ALT-UP and CTRL-ALT-DOWN on Windows? (Or key presses in general?)  Add Cursor works fine from Command Palette so I probably have some weird keyboard thing going on.

**Comment by crisward** [comment] 2016-03-21 14:15
Mac insiders build doesn't seem to have this feature? Am I missing something? (using alt drag)

**Comment by JVimes** [comment] 2016-03-21 18:07
What was the final verdict for arrow keys, and for mouse? Not having luck in my build of master on Windows. Was hoping for alt+shift+arrows, but seeing ctrl+shift+alt+arrows in key bindings and that's not working. Not seeing way with mouse.

**Comment by alexandrudima** [comment] 2016-03-21 18:12
@JVimes Shift+Alt for mouse and ctrl+shift+alt+arrows for keyboard by default.

I've heard that those modifiers might not work on all installations. To bind them to something more familiar:

```json
{ "key": "shift+alt+down",     "command": "cursorColumnSelectDown",
                                  "when": "editorTextFocus" },
{ "key": "shift+alt+left",     "command": "cursorColumnSelectLeft",
                                  "when": "editorTextFocus" },
{ "key": "shift+alt+pagedown", "command": "cursorColumnSelectPageDown",
                                  "when": "editorTextFocus" },
{ "key": "shift+alt+pageup",   "command": "cursorColumnSelectPageUp",
                                  "when": "editorTextFocus" },
{ "key": "shift+alt+right",    "command": "cursorColumnSelectRight",
                                  "when": "editorTextFocus" },
{ "key": "shift+alt+up",       "command": "cursorColumnSelectUp",
                                  "when": "editorTextFocus" }
```

**Comment by JVimes** [comment] 2016-03-21 18:32
@alexandrudima, Those shortcuts are good and work, but I expect them to be default on Windows. Mouse still doesn't work. Shift+Alt+drag ignores the location I started dragging at. Instead, it starts the box at the last cursor location.

**Comment by alexandrudima** [comment] 2016-03-21 20:08
I implemented what I have observed in Visual Studio (which was pointed in this thread as a good implementation of column selection): 

* Pressing Shift+Alt and then clicking will create a column selection anchored at the last cursor location going to the mouse location.

* Clicking and then pressing Shift+Alt will create a column selection anchored at the click location going to the mouse location.

Regarding the default shortcuts, they would be better, but they conflict with other default shortcuts we have already shipped with and I cannot "steal" them without annoying existing folks used to them.

**Comment by JVimes** [comment] 2016-03-21 20:31
@alexandrudima, Oh, I see, we're discussing a slightly different feature than I thought. Visual Studio and Notepad++ also support Alt+drag to do a column select, which I often use. I think it would be a good feature to include in this story.

**Comment by ericwj** [comment] 2016-03-22 05:04
Wouldn't it be great to be able to set a standard key binding profile without having to construct it by editing `keybindings.json` - that's quite hard and tedious. `keybindings.json` would still override the defaults in the profile. So VSCode could ship with a Visual Studio key binding in the box for people to simply select. That'd allow you to modify that profile with the sole argument that it aligns with Visual Studio.

**Comment by JVimes** [comment] 2016-03-22 06:42
Key binding schemes would be great as extensions. Might be able to do that now by modifying the current key bindings, but it would be better to modify the underlying defaults like @ericwj described. Just need factory defaults to take back over when the extension is uninstalled.

**Comment by chrispepper1989** [comment] 2016-04-05 15:32
is this implemented in the current stable vscode? or do i need to grab the latest from source?

**Comment by dvlsg** [comment] 2016-04-05 17:32
I know it works in the [insiders builds](https://code.visualstudio.com/Download#insiders).

To add to what others above are saying, I would also love to see functionality that starts the column selection from the point where you clicked (alt + left click drag, rebindable to middle click drag?) make it in to vscode. I think the shift-alt-leftclick version does add value, but it feels awkward to me, since I typically intend to start the column selection where I click.

**Comment by seva0stapenko** [comment] 2016-04-14 21:47
Tried column selection in VSCode 1.0. Well, rectangular selection does work, cutting and pasting back also works, but that's about it.
Cutting and pasting into a different part of the code does not work as expected. Both Notepad++ and VS remember that copied text was a rectangular block and paste it as a rectangular block.
VSCode treats copied block just like a regular text, so pasting it anywhere outside of the current multi-cursor context would create a mess.
It's good that the feature is being worked on, but it's not fully baked yet.

**Comment by glen-84** [comment] 2016-04-16 21:10
@JVimes @dvlsg I submitted #5402 for Alt+select behaviour.

**Comment by Inori** [comment] 2016-04-18 06:20
![mt](https://cloud.githubusercontent.com/assets/6732524/14595282/a00272d8-0570-11e6-99c9-3fde4a17a97d.gif)
How to select all the text matched by a regex search in column selection mode like sublime?

**Comment by Aarilight** [comment] 2016-06-07 09:48
Is it possible to rebind the keys that go with click+dragging? I searched the `keybindings.json` but can't find one for that. Trying to rebind it to just `alt` rather than `alt+shift`

**Comment by pavelnikolov** [comment] 2016-06-08 13:29
First a BIG THANK YOU to all of the contributors to this feature!!!! 
@Aarilight did you figure out how to do change the binding to just `Alt + drag`? `Alt+shit` is very annoying ?

**Comment by mind0n** [comment] 2016-07-09 04:13
I like this feature as well

**Comment by PhiLhoSoft** [comment] 2016-11-16 13:12
I agree with @seva0stapenko, I expected the same behavior that Visual Studio, which has been copied in Scintilla, thus in related editors like Notepad++ or SciTE.
When copying / cutting a rectangular selection, it puts a "MSDEVColumnSelect" empty flag (and a "Borland IDE Block Type" flag with byte 0x02) in the clipboard, so when pasting, each line of the block is pasted in a line of the destination.

![2016-11-16_13-59-15](https://cloud.githubusercontent.com/assets/1087902/20348339/333d34da-ac05-11e6-9026-2e548f3e7bef.png)

I made a Gif out of a manip in SciTE, showing cutting & pasting a column selection, and the reverse operation using drag'n'drop too.
Alas, I think VSCode still lacks even base D'n'D support... 😞 

![scite-rectangularselection](https://cloud.githubusercontent.com/assets/1087902/20348505/05204190-ac06-11e6-9193-65b46102c54c.gif)

**Comment by BHennen** [comment] 2016-12-04 22:35
I cannot get column selection to work for linux mint; alt+click doesn't do anything, in fact.

**Comment by dvlsg** [comment] 2016-12-08 17:24
@PhiLhoSoft that functionality could be problematic for some of the copy/pasting I do with column selection. Sometimes I want to take pieces out and move them somewhere else, but if VSCode pasted into the lines following my cursor, instead of making a new line for each one that I had, I would have a huge mess of code.

If I'm understanding the suggestion, in order to make that work, I would have to enter in a bunch of blank lines (and I would have to know exactly how many before being able to paste) in order to make sure that part of my column selection doesn't end up getting pasted inside another line which already has code? That seems like a pretty big hassle to me. Or am I misunderstanding?

**Comment by IntelOrca** [comment] 2016-12-08 17:42
@dvlsg In Visual Studio, if you paste on a blank line (a line with no non-whitespace characters) it will insert new lines into the document to fit your clipboard. Otherwise your clipboard lines will be inserted over the lines below your caret. This may be naive but I think it is what the user indents most of the time.

**Comment by riclf** [comment] 2016-12-08 18:13
@IntelOrca is right, and it is intuitive for the user to control the intention. Another easy way is to provide both options, one performed by also holding down the Alt Key. Lets not pretend this is hard stuff. Both column are necessary to have in an easy manner, either intuitive or by keystroke.

**Comment by dvlsg** [comment] 2016-12-08 20:26
@IntelOrca that seems like a fair distinction to me. I agree that it feels a bit naive, but you're probably right that it's what the user intends in most cases. I was unsure of exactly how visual studio handles it, so thank you for the insight. I think I would have pressed ctrl+left arrow to move all the cursors in the gif example, then pasted them from the moved multi-cursors, but I can see how being able to click one position would potentially be useful.

To add some potentially relevant information, here's how a couple other editors appear to handle it:

* Sublime
  * When N lines are copied
    * Paste with 1 cursor
      * all lines are pasted as is, including new lines, pushing text after the cursor down
    * Paste when M cursors
      * all N lines are pasted M times, following the functionality of pasting with 1 cursor
    * Paste when N cursor
      * each N line is pasted once, at each cursor corresponding to its line number

As far as I can tell (from the perspective of an end-user, anyways), sublime doesn't appear to distinguish between items copied from multiple cursors or single cursors stretched across multiple lines.

* Atom
  * Seems to be the same as sublime, basing it on the number of cursors you have when pasting vs the number of lines you have copied

**Comment by mrange** [comment] 2016-12-08 22:03
@dvlsg As you noted neither Sublime nor Atom supports the "correct" behavior but I heard that Emacs 24 does support it. Notepad++ and Powershell IDE (of all things) does it decently.

**Comment by Uristocles** [comment] 2016-12-23 22:40
Notepad++ handles this perfectly.Usually I'm not a fan of copy-cats but this is no time to be original with something that is already proven to work perfectly haha.
Just copy the way n++ does it.  :-)

**Comment by TKAB** [comment] 2017-07-14 10:05
For anyone searching: on **Mac** the default shortcut is `Cmd+Shift+Click`.

The behavior is a little different than in Sublime. You have to first click and then press Cmd+Shift, otherwise it will take the current cursor position as the origin.

**Comment by replay111** [comment] 2017-07-14 12:22
Hi,

as far as I can see the shortcut with mouse is alt + shift + mouse.  alt+cmd + arrow down works from keyboard.

**Comment by mikelward** [comment] 2017-07-15 17:58
Note that Alt+Shift+click doesn't work on Gnome 3 if `mouse-button-modifier` is set to Alt, which seems to be the default in some installations.  https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1704580

To fix, run

    gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Super>"

Or use Gnome Tweak Tool to change Windows -> Window Action Key.
