### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by p354139076** [microsoft/vscode#106623] opened 2020-09-14 06:10 UTC
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200913

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13450:55)
    at getTextOfNode (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13475:16)
    at Object.declarationNameToString (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:13787:66)
    at getDisplayName (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39842:53)
    at declareSymbol (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39956:111)
    at bindExportsPropertyAssignment (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:42066:17)
    at bindWorker (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41762:29)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41651:13)
    at bindExpressionStatement (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27618:24)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27522:21)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at visitNodes (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27440:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27620:24)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40134:17)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindCallExpressionFlow (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41077:21)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27631:24)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindCallExpressionFlow (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41081:21)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindReturnOrThrow (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40551:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40182:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40247:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at visitNode (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27435:24)
    at Object.forEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:27565:21)
    at bindEachChild (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40152:16)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40250:21)
    at bindContainer (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindCallExpressionFlow (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41077:21)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40229:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at bindExpressionStatement (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40716:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40201:21)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41662:21)
    at /Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:94
    at Object.forEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40149:16)
    at bindEachFunctionsFirst (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40142:13)
    at bindChildren (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40241:21)
    at bindContainer (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:40099:17)
    at bind (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:41665:21)
    at bindSourceFile (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39708:17)
    at Object.bindSourceFile (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:39647:9)
    at initializeTypeChecker (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:77643:20)
    at Object.createTypeChecker (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:43696:9)
    at Object.getTypeChecker (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:104892:79)
    at synchronizeHostData (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145287:21)
    at Proxy.getProgram (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:152797:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:153695:44)
    at /Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:97
    at Object.flatMap (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/panzhixuan/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200913/node_modules/typescript/lib/tsserver.js:155037:46)
```

**Comment by mjbvz** [comment] 2020-09-14 18:18
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:18 UTC
