### ISSUE TITLE
Editing string variable value removes newline characters '\n' in variables debug view

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#73975] opened 2019-05-20 00:24 UTC
Steps to Reproduce:

1. Start debugging and try to edit a string variable value containing newline characters `'\n'` in variables debug view.
2. Press enter (without modifying variable value), observe the value have been modified and the newline characters `'\n'` have been removed.
![bug-variablesview](https://user-images.githubusercontent.com/25115070/57990356-7e443780-7a6b-11e9-846f-99954527800c.gif)

**Comment by NizamLZ** [comment] 2019-05-22 15:20
Looking into it

**Comment by isidorn** [comment] 2019-05-23 14:07
@jeanp413 we have merged a PR which tackles this issue. Please try it out in tomorrows vscode insiders and let us know if the issue is fixed for you. Thank you

**Comment by jeanp413** [comment] 2019-05-25 02:22
@isidorn @NizamLZ I tested it but it generates the wrong value sometimes
![testcase](https://user-images.githubusercontent.com/25115070/58363325-c26a7a00-7e67-11e9-9265-8f2424ab312a.gif)

I did some research and it seems we also need to unscape the string when we get the new value from the input 
```typescript
export function replaceWhitespace(value: string): string {
	const map: { [x: string]: string } = { '\n': '\\n', '\r': '\\r', '\t': '\\t', '\b': '\\b', '\v': '\\v', '\f': '\\f' };
	return value.replace(/[\n\r\t\b\v\f]/g, char => map[char]);
}
function replaceEscapedWhitespace(value: string): string {
	const map: { [x: string]: string } = { '\\n': '\n', '\\r': '\r', '\\t': '\t', '\\b': '\b', '\\v': '\v', '\\f': '\f' };
	return value.replace(/\\[nrtbvf]/g, escapedWhitespace => map[escapedWhitespace]);
}
```
https://github.com/microsoft/vscode/blob/649d6befa1fed6a0610a9f12cbcea56688ecfbec/src/vs/workbench/contrib/debug/browser/baseDebugView.ts#L176
change this line ⬆️  to 
```typescript
options.onFinish(replaceEscapedWhitespace(inputBox.value), renamed);
```

**Comment by NizamLZ** [comment] 2019-05-25 08:33
@jeanp418 Thanks for testing. You want to submit a PR or should I?

**Comment by jeanp413** [comment] 2019-05-25 17:15
@NizamLZ go ahead 👍

**Comment by jeanp413** [comment] 2019-05-26 00:13
@isidorn @NizamLZ I did some more testing using the python extension and with both changes (the original PR and my suggestion) it breaks because the python extension also unescapes the newlines.
So I think we need to agree where the unescaping is done if in vscode or the extensions.
This is somewhat related to #73845

**Comment by isidorn** [comment] 2019-05-28 10:00
In theory VSCode should not modify the original values.
We only change them for presentation purposes.
@jeanp413 would you like to provide a PR which cleans this up?
And easy starting point would be just looking where the replaceWhitespace function is being used. And it should only be used to make something easier to read, not to change the actual value.

**Comment by jeanp413** [comment] 2019-05-29 16:01
@isidorn I looked at the places where `replaceWhitespace` is being used and I think those are OK. After reading the Debug Adapter Protocol have a few observations:
- Let's say an additional input widget, for editing a variable's value, exists (could be the case that another editor use this widget) that uses a `textarea` (instead of a `textinput`) then, for this widget, using escaped sequences is not needed while editing the value of a string variable. The new value obtained from this widget is send to the debugging extension and should be used as is (must not unescape the newlines) to update the variable value. In contrast using a `textinput`, we need to escape newlines and when sending the new value the extension should unescape them. But currently there's no way for an extension to know  when to unescaped or not a string. (if this is the case, this should be handled in the editor or update the DAP with an additional parameter in the request)
- Or strings values returned from the extension must always have newlines, etc, escaped and while editing them we always need to escape newlines,etc. (if this is the case then I'll open an issue in the node extension and I think `replaceWhitespace` would no longer be needed)

**Comment by Tyriar** [comment] 2019-05-29 22:59
It seems like the initial state of test3 on the variable pane should be "\\\n" based on how it's printed into the output. Going to reopen as the general issue doesn't seem to be fixed (editing a variable without making a change, changes it).

**Closed** 2019-10-09 09:32 UTC
Labels: *out-of-scope, bug, debug
