### ISSUE TITLE
ctrl+k, Ctrl+f use " instead of ' in ts file

### ISSUE THREAD

**Issue by MyGhJc** [Microsoft/vscode#36836] opened 2017-10-24 16:58 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.8
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.12
prettier-vscode|esb|0.24.0
angular-essentials|joh|0.3.2
Angular2|joh|2.10.0
team|ms-|1.122.0
debugger-for-chrome|msj|3.4.0
angular2-inline|nat|0.0.17
html-css-class-completion|Zig|1.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-24 22:03
It is unclear what the issue is. Please describe the problem and some steps to reproduce it

**Comment by mjbvz** [comment] 2017-10-30 18:55
Closing as not actionable without more information

**Closed by mjbvz** 2017-10-30 18:55 UTC
Labels: needs more info
