### ISSUE TITLE
Folding Breaks

### ISSUE THREAD

**Issue by JoeyPacini** [microsoft/vscode#97323] opened 2020-05-09 04:59 UTC
- VSCode Version: 1.45.0
- OS Version: Windows 10.0.18363.815

Don't know if it's a bug or if I mess up but... :  

Steps to Reproduce:

1. Add some comments folders.
2. Add another comments and a line of code then all folders dissapears.
3. I can't do any folder anymore.

<a href="https://gifyu.com/image/nLGl"><img src="https://s6.gifyu.com/images/VsCodeBug.gif" alt="Vs-Code-Bug" border="0"></a>

(Text that I type after the last comment seems to stay with the comments. I mean the little identation bar on the left)

Does this issue occur when all extensions are disabled?: Yes. With Insiders too.

I tried to change the editor.foldingStrategy option.
I disabled all extensions.

**Comment by aeschli** [comment] 2020-05-11 13:47
Looks like a TypeScript issie. Have this code:
```
//
//

/****************************
 * Variables & Data Types
 */

/*
var firstName = 'Joye';
console.log(firstName);

var second = 'yo';
console.log(firstName);
*/

/********
 * Some comment
 */

 var
```

No folding ranges are returned
(To verify, set a breakpoint in foldingModel.update)

**Comment by uloga** [comment] 2020-10-23 20:54
I have the same issues with html, css and typescript. Carrots disappear, once it's folded you can't unfold using carrots.

**Comment by mjbvz** [comment] 2021-05-06 01:23
Closing this since there hasn't been any real activity over the past year. If you are still running into this, please some simple steps to reproduce so we can investigate

**Closed by mjbvz** 2021-05-06 01:23 UTC
Labels: bug, editor-folding, javascript
