### ISSUE TITLE
Wrong auto-complete for $this

### ISSUE THREAD

**Issue by Leclex** [Microsoft/vscode#659] opened 2015-11-25 20:11 UTC
When I typed $this in PHP files, I selected auto-complete $this, then it becomed $$this actually.

**Comment by MA-Maddin** [comment] 2015-11-26 08:05
just want to confirm this issue.
Type **$_** and select **$_GET**, **$_POST** etc. and there will be $$
I guess this issue doesn't existed prior v0.10.1

**Comment by aeschli** [comment] 2015-11-26 08:19
duplicate of #86

**Closed by aeschli** 2015-11-26 08:19 UTC
