### ISSUE TITLE
[Jupyter Notebook Accessibility] Add default keybindings for SR users to go to the next and previous cells

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#189484] opened 2023-08-02 16:18 UTC
Type: <b>Feature Request</b>

When screen reader is used, `{"notebook.navigation.allowNavigateToSurroundingCells": false}` is set.

This means SR users may need to add some custom keybindings to go between cells. I suggest the following keybindings by default. (Please use CMD instead of Ctrl for Mac).

``` json
[
  {
    "key": "ctrl+pagedown",
    "command": "notebook.focusNextEditor",
    "when": "notebookEditorFocused"
  },
  {
    "key": "ctrl+pageup",
    "command": "notebook.focusPreviousEditor",
    "when": "notebookEditorFocused"
  }
]
```

VS Code version: Code - Insiders 1.81.0-insider (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:36:29.806Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jooyoungseo** [comment] 2023-08-02 17:16
@meganrogge -- For discoverability, it would be great if this could be added to the Notebook contextual help once this gets implemented.

**Comment by amunger** [comment] 2023-12-04 23:40
duplicate of https://github.com/microsoft/vscode/issues/176290

**Closed by amunger** 2023-12-04 23:40 UTC
Labels: accessibility
