### ISSUE TITLE
Is "Visual Studio Code for the Web" open source?

### ISSUE THREAD

**Issue by carljones4** [microsoft/vscode#136265] opened 2021-11-02 04:08 UTC
Hello- I would like to host the [web based version of VS Code](https://code.visualstudio.com/docs/editor/vscode-web) on my website.  Is it part of this open source repo?  Perhaps [this](https://github.com/microsoft/vscode/tree/main/src/vs/editor/standalone/browser) is it?

This question probably belongs on a forum rather than an 'issue', but apparently MS [likes it this way](https://github.com/Microsoft/vscode/issues/21685#issuecomment-283590971).

**Comment by Igorgro** [comment] 2021-11-02 05:03
Duplicate of https://github.com/microsoft/vscode/issues/136168

**Comment by joyceerhl** [comment] 2021-11-02 21:18
Closing as duplicate of #136168

**Closed by joyceerhl** 2021-11-02 21:18 UTC
Labels: *duplicate
