### ISSUE TITLE
"Cannot edit in read-only editor" when trying to edit .js file after debugging

### ISSUE THREAD

**Issue by psech** [microsoft/vscode#102991] opened 2020-07-21 05:12 UTC
- VSCode Version: 1.47.2
- OS Version: macOs Catalina 10.15.5

Similar to https://github.com/microsoft/vscode/issues/83784

Steps to Reproduce:

1. Debug a .js file
2. After debugging is completed try to edit a file

Sample debug config
```
{
      "type": "node",
      "request": "launch",
      "name": "Launch confluence-team-flags-debug",
      "envFile": "${workspaceFolder}/debug/.env",
      "program": "${workspaceFolder}/debug/confluence-team-flags-debug.js"
},
```

The project is nodejs12.x + serverless framework, no transpilation
```
  "dependencies": {
    "aws-sdk": "^2.659.0",
    "axios": "^0.19.0",
    "bottleneck": "^2.19.5",
    "json2csv": "^4.5.4",
    "moment": "^2.24.0"
  }
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by weinand** [comment] 2020-07-21 09:56
Please provide more detailed steps so that I can try to reproduce the issue.
You only have a single step and I do not understand how the title of this issue is related to your step 1.
In addition, how is your statement "export all env variables manually" related to the issue?

**Comment by ViljarVoidula** [comment] 2020-07-21 19:59
I managed to reproduce with following setup:
 Babel setup
```
 yarn init
 yarn add @babel/core @babel/node --save-dev
 yarn add @babel/preset-env
```

package.json

```
{
  "name": "debugger-fail",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Viljar",
  "license": "MIT",
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ],
    "sourceMaps": "inline",
    "retainLines": true
  },
  "dependencies": {
    "@babel/core": "^7.10.5",
    "@babel/node": "^7.10.5",
    "@babel/preset-env": "^7.10.4"
  }
}
```


index.js
```
const testObj = {foo:'bar'}
const testChain = testObj?.bar ?? '';
debugger
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/babel-node",
            "program": "${workspaceFolder}/index.js"
        }
    ]
}
```

https://github.com/microsoft/vscode/issues/83784#issuecomment-553347486

Might have same fundamental problem with babel runtime ?

**Comment by connor4312** [comment] 2020-07-21 22:59
This happens if there are files that Node.js is running which are not the same as the files on disk.

You (esp. @ViljarVoidula) can try the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) and see if it works there. Otherwise please collect a trace log using the following instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by ViljarVoidula** [comment] 2020-07-22 11:14
> This happens if there are files that Node.js is running which are not the same as the files on disk.
> 
> You (esp. @ViljarVoidula) can try the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) and see if it works there. Otherwise please collect a trace log using the following instructions:
> 
> > If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
> > warning This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to [connor@xbox.com](mailto:connor@xbox.com)

Thank you for reply . I've sent you the logs to your email

**Comment by connor4312** [comment] 2020-07-22 15:59
Thanks for the log! I believe your issue is already fixed in the [nightly build], can you give that a shot? https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by ViljarVoidula** [comment] 2020-07-22 16:05
> Thanks for the log! I believe your issue is already fixed in the [nightly build], can you give that a shot? https://github.com/microsoft/vscode-js-debug#nightly-extension

Sorry forgot to mention - same result with nightly build

**Comment by connor4312** [comment] 2020-07-22 16:17
Ok, could you please grab another log with the nightly build? Sorry for the additional work

**Comment by ViljarVoidula** [comment] 2020-07-22 16:25
> Ok, could you please grab another log with the nightly build? Sorry for the additional work

Sure, logs should land in your inbox briefly.

**Comment by connor4312** [comment] 2020-07-22 16:44
Okay, thanks! So with the nightly you're actually hitting a different issue which I fixed in Windows last week and _just_ fixed in OSX/Linux in https://github.com/microsoft/vscode-js-debug/commit/79fe0a95a5d65a6253ad2cc885489fd57cd83801. I think this should work for you if you give this one more shot in the next nightly (which will build at 5PM PST today, when this comment is ~7.5 hours old)

**Comment by ViljarVoidula** [comment] 2020-07-22 16:48
> Okay, thanks! So with the nightly you're actually hitting a different issue which I fixed in Windows last week and _just_ fixed in OSX/Linux in [microsoft/vscode-js-debug@79fe0a9](https://github.com/microsoft/vscode-js-debug/commit/79fe0a95a5d65a6253ad2cc885489fd57cd83801). I think this should work for you if you give this one more shot in the next nightly (which will build at 5PM PST today, when this comment is ~7.5 hours old)

Thank you ! I'll check it tomorrow ( +7.5h is night time for me )

**Comment by TimvdEijnden** [comment] 2020-07-23 12:59
@connor4312 I just installed the nightly using `@id:ms-vscode.js-debug-nightly` and tried on macOS, but it does not seem to work. It keeps opening the read-only version of the file. While this was working a few weeks ago.

Or is the next nightly not yet available?

**Comment by connor4312** [comment] 2020-07-23 14:21
You may be encountering a different issue. Please collect a trace log (instructions above)

**Comment by ViljarVoidula** [comment] 2020-07-23 14:23
> You may be encountering a different issue. Please collect a trace log (instructions above)

Linux solution works

**Comment by connor4312** [comment] 2020-07-23 14:24
Thanks for the confirmation!

**Comment by TimvdEijnden** [comment] 2020-07-27 12:52
@connor4312 For me it doesn't I collected logs and mailed them to you last friday.

**Comment by TimvdEijnden** [comment] 2020-07-29 14:11
@connor4312 my issue is fixed by adding

    "debug.javascript.usePreview": false

To my settings.json

**Comment by connor4312** [comment] 2020-07-30 15:47
@TimvdEijnden apologies for the delay.

This is actually an issue with babel-node that I fixed in the latest [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) of js-debug (in https://github.com/microsoft/vscode-js-debug/issues/636).

**Comment by connor4312** [comment] 2020-07-30 19:18
It looks like hashing was changed slightly in [this V8 commit](https://chromium.googlesource.com/chromium/src/third_party/WebKit/Source/platform/v8_inspector/+/f0978d22a767ee25e9da0312ec68b7307a06372e%5E%21/V8DebuggerAgentImpl.cpp) which I suspect is causing the Node 8 scripts not to match up precisely.

The original author hasn't responded, and for this particular issue I will mark as a wontfix with the workaround to either:

1. Update to Node 10 or higher
1. Set `"enableContentValidation": false` in your launch.json

**Closed** 2020-07-30 19:18 UTC
Labels: debug, wont-fix
