### ISSUE TITLE
If getStackTraceRequest returns an empty stack, the Resume button does not work

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#73090] opened 2019-04-30 15:33 UTC
If a debug adapter can't provide any frames and returns an empty array, for ex.:

```ts
protected stackTraceRequest(response: DebugProtocol.StackTraceResponse, args: DebugProtocol.StackTraceArguments): void {
	response.body = {
		stackFrames: [],
		totalFrames: 0,
	};
	this.sendResponse(response);
}
```

The Continue button no longer functions - it does not send a `continueRequest`. The same thing happens if you send an error response. As a workaround (since I have a debugger that can't provide a stack trace yet) I've had to provide a dummy stack frame in order for resume to work (sure, a debugger that can only pause and resume is not terribly useful, but this seems like strange behaviour from VS Code).

```ts
	response.body = {
		stackFrames: args.startFrame === 0 ? [
			{
				column: 0,
				id: -1,
				line: 0,
				name: "missing",
			},
		] : [],
		totalFrames: 0,
	};
```

**Comment by isidorn** [comment] 2019-04-30 20:32
If you would like this fixed can you please create a fork of the mock debug so I reproduce this issue on my machine. Thank you.

**Comment by DanTup** [comment] 2019-05-02 14:00
@isidorn you just need to paste the sample above over stackTraceRequest. I've pushed it here, as well as added logging to make it clear:

https://github.com/DanTup/vscode-repro-73090

The specific change looks like this:

https://github.com/DanTup/vscode-repro-73090/commit/a0a057227f19f3fbc2fc0acf7dfe0fc9c045ff9b

All it does is logs when it stops (on entry), when VS Code asks for a stack trace, and when it gets a continue request, and also returns an empty stack trace.

Run the extension, open a .md file and run it with mock debug. It'll print:

```
Stopped on entry!
Sending empty call stack!
```

Now click the Continue button and observe that it never prints "Continue was called!".

Let me know if you ahve any issues reproducing with this.

**Comment by isidorn** [comment] 2019-05-28 15:10
Thanks for the nice repro steps.
I have pushed a fix, you can try it out in tomorrow's vscode insiders and let us know if the issue is fixed for you.

**Closed** 2019-05-28 15:12 UTC
Labels: bug, debug

**Comment by DanTup** [comment] 2019-05-29 08:02
Fix looks good, thanks! :-)

**Comment by isidorn** [comment] 2019-05-29 08:04
Thanks, adding verified label.
