### ISSUE TITLE
Right mouse click on sidebar popup menu triggers instantly (Ubuntu 20.04 )

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#124019] opened 2021-05-17 08:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic snap

Steps to Reproduce:

1. Open any project
2. Right click on anything

The pop up menu spawns under the mouse and triggers instantly so we'll need to move the pop-up window a few pixels to the left of the mouse pointer location.

**Comment by IllusionMH** [comment] 2021-05-17 10:11
Looks like duplicate of #113175

**Closed** 2021-05-17 13:51 UTC
Labels: needs more info
