### ISSUE TITLE
Seed Search String From Selection option "never" is now ignored

### ISSUE THREAD

**Issue by kfrymire** [microsoft/vscode#187180] opened 2023-07-06 18:54 UTC
Type: <b>Bug</b>

1) Set "User" setting "Editor > Find: Seed Search String From Selection" to "never".
2) Close Settings
3) Select any text in the Editor
4) Press cmd+shift+f
!5) Selected text is auto-entered into search box even with "never" option selected.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:40:17.963Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv|--crash-reporter-id b0857a18-3e3e-49cc-809a-a294a8a01911|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
duplicate-file|axe|0.1.1
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
goto-documentation|cxf|0.0.1
vscode-eslint|dba|2.4.2
profiler-php-vscode|DEV|1.36.13417
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.19.0
url-encode|fle|1.1.0
auto-close-tag|for|0.5.14
vscode-edit-csv|jan|0.7.6
svg|joc|1.5.3
favorites|kdc|2.4.5
rainbow-csv|mec|3.7.0
dotenv|mik|1.0.1
ecdc|mit|1.8.0
vscode-apache|mrm|1.2.0
php-docblocker|nei|2.7.0
vetur|oct|0.37.3
laravel-blade|one|1.34.0
material-icon-theme|PKi|4.28.0
vscode-xml|red|0.25.0
vscode-yaml|red|1.13.0
vscode-simple-icons-rev|Sha|1.16.2
vscode-scss-formatter|sib|2.5.0
uridecode|sry|0.3.6
rewrap|stk|1.16.3
vscodeintellicode|Vis|1.2.30
twig|wha|1.0.2
change-case|wma|1.0.0
php-debug|xde|1.32.1
material-theme|zhu|3.15.18

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495

```

</details>

**Comment by amunger** [comment] 2023-12-14 00:16
duplicate of https://github.com/microsoft/vscode/issues/142864

**Closed by amunger** 2023-12-14 00:16 UTC
Labels: bug, editor-find
