### ISSUE TITLE
more options for custom view

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#50861] opened 2018-05-31 08:35 UTC
Hi,
I'm not sure if this is areally a feature request or if I missed something.

For my debug-adapter I would like to add a view to the side bar that displays memory contents.
So the user gets the ability to **read** memory **and** also **edit** memory.

It should look similar to this:

![image](https://user-images.githubusercontent.com/3081973/40771540-e016f200-64bd-11e8-8d34-7c8b336988df.jpeg)

I have found that I can contribute a view and make data available via the TreeDataProvider but that does not suit my needs as the memory dump is no tree.

Is there any possibility to add something different than a tree to a view?

Please note: I don't necessarily need an update of the debug-api offering more options for the 'view' would be sufficient.

**Comment by isidorn** [comment] 2018-05-31 08:44
Custom views are currently not supporting this.
Forwarding to @sandy081 since this might be a duplicate of an already open feature request

**Comment by sandy081** [comment] 2018-05-31 09:56
@maziac What kind of view/model are you looking at? At present we support Tree (tree + list) model.

**Comment by maziac** [comment] 2018-05-31 10:00
As you can see from the picture I would require lines with columns.
In the end every item (i.e. the 2 digit hex numbers like 5F) should be editable.

**Comment by sandy081** [comment] 2018-05-31 12:35
I see. We have web views which are still in preview mode. I think that is the right approach for your use case. But web views are shown in editor and not in side bar. I think this view might not be a good fit in side bar. Check this - https://github.com/Microsoft/vscode/issues/43713

**Comment by maziac** [comment] 2018-05-31 13:42
I'm not sure if this can help.
a) it's not in the side view (although I might could live with it but)
b) it's a preview. I.e. I would like to edit values in there.

**Comment by sandy081** [comment] 2018-05-31 14:08
IMO this is not a good fit for side bar and for tree view. 

@mjbvz Please advise if it can be done through web view.

Thanks.

**Comment by mjbvz** [comment] 2018-05-31 17:53
Yes this would be a good fit for a webview. Webviews can only go in editor positions currently. We may also allow them in sidebars at some point (#46585) but no promises on that 

Webviews can contain editors, UI, previews, pretty much anything. Here are the docs: https://code.visualstudio.com/docs/extensions/webview

**Closed by mjbvz** 2018-05-31 17:53 UTC
Labels: needs more info

**Comment by maziac** [comment] 2018-06-01 18:21
Hmm, I tried to use the web vieew as described in the tutorial, but it does nto work:
createWebView is not defined:
![image](https://user-images.githubusercontent.com/3081973/40856640-e0e03220-65d8-11e8-818c-b9479db9060c.jpeg)


Does it have something to do with the fact that my extension is a debug adapter?
