### ISSUE TITLE
Can't open some plugin market - xhr timeout

### ISSUE THREAD

**Issue by leguminosa** [microsoft/vscode#108087] opened 2020-10-05 04:29 UTC
Issue Type: <b>Bug</b>

some plugin in plugin market can't be opened.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 3254)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.44GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id f9567cb3-2186-4d15-8e30-e0d18366d79b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
go|gol|0.17.2

</details>

![image](https://user-images.githubusercontent.com/38403278/95040484-fa412d00-06fd-11eb-979d-213ed77bf623.png)
![image](https://user-images.githubusercontent.com/38403278/95040381-b0f0dd80-06fd-11eb-8950-5f15d8bef3ba.png)
![image](https://user-images.githubusercontent.com/38403278/95040400-c1a15380-06fd-11eb-8872-948912abc637.png)

**Comment by sandy081** [comment] 2020-10-05 13:12
Please check if you are able to access the Marketplace from the web portal - https://marketplace.visualstudio.com and able to download extensions?

**Comment by leguminosa** [comment] 2020-10-06 03:55
@sandy081 yes i can access the link you gave, and download them manually

in fact, inside vscode, when I force to click download (even tho the page hasn't been loaded successfully), after some time there will be pop up message prompt me to download manually, and it works like that.

So the issue is, I can't access store inside the vscode itself.

**Comment by leguminosa** [comment] 2020-10-06 03:55
because of this issue, I downloaded and installed my plugins (db, gitlens) this way.

**Comment by sandy081** [comment] 2020-10-07 13:50
Seems connection issues - hence assigning to @deepak1556 / @chrmarti if there are any proxy issues.

**Comment by deepak1556** [comment] 2020-10-07 20:08
Can you attach the log following these steps

* launch vscode with `code --log-net-log=<some-absolute-path>/netlog.json`
* Perform the steps that create the xhr timeout issue
* Quit the application

Attach the generated netlog.json, thanks!

**Comment by leguminosa** [comment] 2020-10-08 04:12
Some page can be opened (albeit with unnaturally slow loading), some page got xhr timeout like I described.
And all of them failed to download it (and prompting to download manually, which will succeed if I proceed to click it, it download on my browser)

[netlog.txt](https://github.com/microsoft/vscode/files/5345263/netlog.txt)

**Comment by deepak1556** [comment] 2020-10-08 07:00
Thanks for the log! there is no proxy involved here, all requests are direct connections.

interesting bit from one of the failed requests,

```
94: HTTP2_SESSION
bmewburn.gallerycdn.vsassets.io:443 (DIRECT)

t=19196 [st=  973]    HTTP2_SESSION_RECV_HEADERS
                      --> fin = false
                      --> :status: 200
                          content-encoding: gzip
                          accept-ranges: bytes
                          access-control-allow-origin: *
                          access-control-expose-headers: x-ms-request-id,Server,x-ms-version,Content-Type,Content-Encoding,Cache-Control,Last-Modified,ETag,x-ms-lease-status,x-ms-blob-type,Content-Length,Date,Transfer-Encoding
                          age: 4509885
                          cache-control: public, max-age=31536000
                          content-type: image/png
                          date: Thu, 08 Oct 2020 03:39:19 GMT
                          etag: 0x8D842363807C52C
                          last-modified: Sun, 16 Aug 2020 22:46:30 GMT
                          server: ECAcc (cgk/F909)
                          vary: Accept-Encoding
                          x-cache: HIT
                          x-ms-blob-type: BlockBlob
                          x-ms-lease-status: unlocked
                          x-ms-request-id: 409860b1-901e-003e-2720-74bc1d000000
                          x-ms-version: 2009-09-19
                          content-length: 11689
                      --> stream_id = 1
t=46829 [st=28606]    HTTP2_SESSION_PING
                      --> is_ack = false
                      --> type = "sent"
                      --> unique_id = 1


t=46974 [st=28751]    HTTP2_SESSION_CLOSE
                      --> description = "Error 101 reading from socket."
                      --> net_error = -101 (ERR_CONNECTION_RESET)
```

there is no `HTTP2_SESSION_RECV_DATA` frame after the headers frame and also the client sends a ping frame to check if the connection is idle, eventually the connection is reset.

It is not clear from the log if the reset was triggered by the server or DNS layer. Couple of things to try,

1) Can you try pointing to one of the public DNS servers and see if the issue continues ?

2) Also can you check if the issue happens with our exploration build https://github.com/microsoft/vscode/issues/107330#issuecomment-702950849 that comes with newer chromium runtime.

3) Another temporary workaround to check is to start code with  `--disable-http2` flag.

**Comment by leguminosa** [comment] 2020-10-08 08:42
i already use public google dns (8.8.8.8 and 8.8.4.4)

you mean that dns right? on wifi setting ipv4
![image](https://user-images.githubusercontent.com/38403278/95435427-c32c7f00-097c-11eb-94c3-8a1dece871d8.png)

**Comment by leguminosa** [comment] 2020-10-08 08:42
ill try opening code with --disable-http2 then

**Comment by leguminosa** [comment] 2020-10-08 11:43
there are no `--disable-http2` flag ? @deepak1556 
![image](https://user-images.githubusercontent.com/38403278/95454026-13640b00-0996-11eb-8e8d-b6ffd42cf735.png)

**Comment by deepak1556** [comment] 2020-10-08 19:20
Yup the DNS config looks good, as for the `--disable-http2` warning message, you can ignore it. The flag will still be passed down to the runtime.

Do you still see the error with the flag ? If so, can you provide another netlog with the `--disable-http2`

**Comment by deepak1556** [comment] 2020-10-08 20:12
Can you also confirm if the issue is present with the exploration builds https://github.com/microsoft/vscode/issues/107330#issuecomment-702950849

**Comment by leguminosa** [comment] 2020-10-09 03:28
here's the `netlog.json` with `disable-http2` option. It still happening (the xhr timeout)
[netlog.txt](https://github.com/microsoft/vscode/files/5352345/netlog.txt)

what do you mean about that exploration build? what should i do with that thread? the thread seems like unrelated to me.
I installed vscode via ubuntu software
```
❯ which code
/snap/bin/code
```
```
❯ code --version
1.50.0
93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
x64
```
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
```
❯ uname -a
Linux leguminosa-Latitude-5490 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by leguminosa** [comment] 2020-10-09 03:29
what is `code-exploration` ? You want me to install it on my machine too?

**Comment by deepak1556** [comment] 2020-10-09 03:31
`code-exploration` comes with a newer version of chromium, in this case it is chromium 87.

> You want me to install it on my machine too?

Yes please do so, I want to check if the issue is still present with latest chromium versions.

**Comment by leguminosa** [comment] 2020-10-09 04:33
which one should I try first? .deb or snap?

**Comment by deepak1556** [comment] 2020-10-09 04:48
anything is fine

**Comment by leguminosa** [comment] 2020-10-09 05:05
@deepak1556 
I downloaded the .deb version
im opening vscode exploration's plugin market and it behaves almost the same - it's loading very very long, but in the end it successfully loaded smh (even tho I doubt it is cleanly and completely loaded)

i ran the code via command `code-exploration --log-net-log=~/netlog-exploration.json .`
Here's the netlog
[netlog-exploration.txt](https://github.com/microsoft/vscode/files/5352628/netlog-exploration.txt)

**Comment by deepak1556** [comment] 2020-10-09 05:55
Thanks for the logs, I am pretty sure the problem is not at the client layer but rather in the middleware (firewall) or maybe server. To confirm,

* Start `code-exploration --log-net-log=~/netlog-exploration.json .` , you can also use the stable build
* In another terminal `sudo tcpdump -i <interface> -w vscode_net.pcap -s 0` , for the `<interface>` fill the network interface to capture the log `tcpdump --list-interfaces`, if you are not sure then use `any` as the value
* Do some extension queries and quit the app
* `Ctrl + c` the tcpdump session

Attach the netlog as well as pcap file.

**Comment by leguminosa** [comment] 2020-10-09 08:41
@deepak1556 
The plugin market can be opened (albeit with really long long loading time, but it's not xhr timeout like before)
but all of them failed when installing (look image attached below)

[netlog-exploration.json.txt](https://github.com/microsoft/vscode/files/5353585/netlog-exploration.json.txt)
[vscode_net.pcap.txt](https://github.com/microsoft/vscode/files/5353586/vscode_net.pcap.txt)

![image](https://user-images.githubusercontent.com/38403278/95561832-88dae480-0a45-11eb-95f9-444097524347.png)

**Comment by deepak1556** [comment] 2020-10-12 19:38
Thanks for the logs!

I compared two different requests,

1) azemoh.gallerycdn.vsassets.io:443 which had successful resource completion

[FIN, ACK]
[ACK]
[RST] -> this was sent by the client, can be confirmed with the source mac

<img width="1669" alt="Screen Shot 2020-10-12 at 11 45 43 AM" src="https://user-images.githubusercontent.com/964386/95783496-cd08f780-0c86-11eb-9884-8c16369148fa.png">

2) equinusocio.gallerycdn.vsassets.io:443 which had a connection reset error

[Application DATA]
[TCP Retransmission]
[RST] -> this is not from the client or server, some middleman is sending the packet

<img width="1678" alt="Screen Shot 2020-10-12 at 11 46 43 AM" src="https://user-images.githubusercontent.com/964386/95783777-646e4a80-0c87-11eb-8761-92ba96743bcb.png">


Which brings me to the question, are you on some kind of vpn ?

**Comment by leguminosa** [comment] 2020-10-13 04:12
if you ask about it yes, I'm working on some kind of custom vpn, but:
1. I have always been using it for the past 1 year, and it (this issue) never happened until recently
2. I also tried when not connecting to the vpn, the result is kinda the same

**Comment by deepak1556** [comment] 2020-10-13 04:29
> I also tried when not connecting to the vpn, the result is kinda the same

Can you provide the netlog and pcap for this case. 

Thanks for the details, I will confirm what is happening in the non-vpn case but so far since the problem is not on the client I don't have any solution, I don't have access to the server code to debug further.

**Comment by leguminosa** [comment] 2020-10-13 10:00
@deepak1556 
some of the page can load pretty quickly and normal, some other stuck on loading (like before - xhr timeout), but absolutely none of them could download successfully. al of them has taken a long amount of time before actually prompting fail to install and giving option to download manually (like attached in my attempt before)

[netlog-exploration.json.txt](https://github.com/microsoft/vscode/files/5370545/netlog-exploration.json.txt)

[vscode_net.pcap.txt](https://github.com/microsoft/vscode/files/5370537/vscode_net.pcap.txt)

**Comment by deepak1556** [comment] 2020-10-13 21:00
Yup I see the same RST packets sent from the server, I don't have concrete answers since the issue is not on the client, will forward this issue to the marketplace team for further debugging.

/cc @fiveisprime

**Comment by fiveisprime** [comment] 2020-11-05 16:56
@prashantvc can you have somebody from the engineering team take a look at this?

**Comment by prashantvc** [comment] 2020-11-09 07:51
@munishgoyal1 can we have someone take a look at this please?

**Comment by Emmanuelagbo-4** [comment] 2021-05-02 00:49
still having the issue XHR timeout

**Comment by Emmanuelagbo-4** [comment] 2021-05-03 06:04
Finally found a fix

My fix was allowing chrome(default browser) to access network in my firewall.
I followed the steps in this blog to do this https://quoramarketing.com/how-to-allow-chrome-to-access-the-network-in-your-firewall-or-antivirus-settings/

**Comment by chrmarti** [comment] 2021-05-04 12:25
Maybe related to https://github.com/microsoft/vscode/issues/34385.

**Comment by isidorn** [comment] 2021-08-19 10:33
Closing as outdated

**Closed by isidorn** 2021-08-19 10:33 UTC
Labels: linux, extensions, marketplace, network
