### ISSUE TITLE
Unexpected suggest scoring

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#167242] opened 2022-11-25 12:56 UTC
* open user `settings.json`
* do ctrl+space
* type `git.pull`
* observe that the textual suggestion "pull" comes before the `git.pullBeforeCheckout` suggestion 
* this behaves differently if using ctrl+space after typing

https://user-images.githubusercontent.com/5047891/203990466-c36b7a31-af43-4b45-8002-a086fa210546.mp4

**Comment by jrieken** [comment] 2022-11-25 15:30
Fishy... Word based and smart completions shouldn't show together to begin with

<img width="929" alt="Screenshot 2022-11-25 at 16 29 55" src="https://user-images.githubusercontent.com/1794099/204016376-2b2a4dae-06bd-457e-8501-1f9d79edcb6b.png">

**Comment by svipas** [comment] 2022-11-29 10:23
I was able to reproduce this like ~3 months ago in `settings.json`. Unfortunately, I cannot remember from which version it started.

**Comment by jrieken** [comment] 2022-11-30 13:57
Moving to December because this isn't a regression. The problem is two fold. When auto triggering completions we carry over existing completion items (e.g those from the JSON language server) and don't ask their providers again. We only ask all the other providers. In that case the bucket-logic fails, the higher ranked JSON completion doesn't cancel out the lower ranked word-based completion provider. That's why `pull`, `pullBeforeCheckout` etc are added to the mix. They then score higher because JSON's `git.pullBeforeCheckout`-suggestion uses as filter-text `"git.pullBeforeCheckout"` (leading quote) which scores lowers

**Closed** 2022-12-06 17:04 UTC
Labels: bug, suggest
