### ISSUE TITLE
Permanent Command Palette

### ISSUE THREAD

**Issue by rajdeepslather** [Microsoft/vscode#58749] opened 2018-09-15 21:39 UTC
I would like an option to make the command palette permanently visible as a toolbar or integrated in the new "custom" title bar.

I use the command palette a lot and many times I find myself using the palette with just a mouse by scrolling through the available commands or picking one of the recent file/commands from the list. I can navigate just fine after the pallet is open but in order to open the palette quickly I have to hit the keyboard shortcut. 

If the palette was permanently visible I could just pick the recent commands from it directly using a mouse.

I understand that navigation through a mouse might not be the top priority when it comes to palette design, but I hope that adding the option to make the palette permanent is not too big of a task.

**Comment by bpasero** [comment] 2018-09-17 08:40
I would treat this as duplicate of https://github.com/Microsoft/vscode/issues/41309

**Closed by bpasero** 2018-09-17 08:40 UTC
