### ISSUE TITLE
Debug Breakpoints view - unnecessary vertical scrollbar with horizontal scrolling enabled

### ISSUE THREAD

**Issue by RomanKornev** [Microsoft/vscode#68774] opened 2019-02-15 10:53 UTC
- VSCode Version: Version: 1.31.1 (user setup)
- OS Version: Win10 1809

After the new update, the breakpoint window cannot be resized. But it still has a scrollbar that can scroll a small amount. Caused by `"workbench.tree.horizontalScrolling": true`. But there is no horizontal scrollbar anywhere.

Steps to Reproduce:

1. `"workbench.tree.horizontalScrolling": true`
1. Add any number of breakpoints
2. Go to Debug - Breakpoints
3. It cannot be resized but can still be scrolled
![image](https://user-images.githubusercontent.com/5807561/52851267-bbc0be00-3126-11e9-9694-eeaec7d29aba.png)

Does this issue occur when all extensions are disabled?: Yes

Related #67643, #67441, #67620

**Comment by isidorn** [comment] 2019-02-18 14:44
This is a duplicate of some issue assigned to @joaomoreno 
@joaomoreno you know better which one, can you please close this as a duplicate of that one?

**Comment by joaomoreno** [comment] 2019-02-19 10:07
https://github.com/Microsoft/vscode/issues/67643

**Closed by joaomoreno** 2019-02-19 10:07 UTC
