### ISSUE TITLE
Code folding in JSX segments

### ISSUE THREAD

**Issue by lgaskill** [Microsoft/vscode#52329] opened 2018-06-19 12:48 UTC
Issue Type: <b>Bug</b>

Code folding is no longer available for JSX code segments within reactjs components.

Expected Results:
- When hovering over sections of JSX segments in reactJS components, collapse and expansion buttons are available in the side bar to fold and unfold sections.

Actual Results:
- No code folding actions are available in JSX segments.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_6301186|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.5.0
vscode-react-native|vsm|0.6.11

</details>

**Comment by mjbvz** [comment] 2018-06-19 16:37
Duplicate of #51266

**Closed by mjbvz** 2018-06-19 16:37 UTC
Labels: editor-folding, new release
