### ISSUE TITLE
When running out of source Process Explorer is empty

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62664] opened 2018-11-06 15:22 UTC
VS Code version: Code - Insiders 1.29.0-insider (9b2a7f4a83ca6a2d495463276a21157f398b41e7, 2018-11-02T13:35:17.219Z)
OS version: Darwin x64 18.2.0

When running out of source Process Explorer stays empty:

![2018-11-06_16-20-09](https://user-images.githubusercontent.com/1898161/48074004-3ac96080-e1e0-11e8-9d73-40fd2c772fb9.png)

**Comment by RMacfarlane** [comment] 2018-11-06 18:57
I'm not able to reproduce this - what's the output of running `--status`?

**Comment by RMacfarlane** [comment] 2018-12-04 18:58
Duplicate of https://github.com/Microsoft/vscode/issues/63437, have checked in a fix. The problem was that when reading the output of `ps`, we expected the decimal separator to always be `.`, when it was actually determined by locale

**Closed by RMacfarlane** 2018-12-04 18:58 UTC
Labels: *duplicate, insiders
