### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by polegithub** [Microsoft/vscode#24748] opened 2017-04-14 07:08 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1.Open vscode
2.Normally use it
3.Error: 扩展主机意外终止。请重新加载窗口以恢复。

What I have done: 
1. Version: 1.11.2, installed some extensions
Uninstall all extensions(扩展工具) -- Still Error:"扩展主机意外终止。请重新加载窗口以恢复"

2. Old version update to latest version:
2.1 remove vscode ,install a old version vscode(1.0.2,2016/06),# work well
2.2 vscode remind me to update version , i agreed, then update to  version 1.11.2
2.3 Error again:"扩展主机意外终止。请重新加载窗口以恢复"

<img width="1245" alt="2017-04-14 3 09 32" src="https://cloud.githubusercontent.com/assets/7831235/25036080/28cc8bce-2124-11e7-94b6-7b3b4a159ec6.png">

**Comment by polegithub** [comment] 2017-04-14 07:11
Same with #24742

**Comment by jrieken** [comment] 2017-04-14 07:17
close as dupe of https://github.com/Microsoft/vscode/issues/24742

**Closed by jrieken** 2017-04-14 07:17 UTC

**Comment by hustlibraco** [comment] 2017-06-01 08:33
I have same issue when I open a mapping project folder from Linux on Windows.
And It becomes ok wher I Close Git Manage in **settings.json**.
```
    "git.enabled": false,
    "git.path": null,
    "git.autofetch": false
```

**Comment by ForMySunny** [comment] 2017-08-08 04:45
@hustlibraco Hey friend, I just did as you said, but it didn't work :( I could make and save any changes except git= =

**Comment by ezirmusitua** [comment] 2017-08-18 02:00
Make sure the `git.exe` is actually in the "git.path"
