### ISSUE TITLE
Settings editor: blue focus ring is not around all elements

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208060] opened 2024-03-19 04:42 UTC
![image](https://github.com/microsoft/vscode/assets/900690/83330f6b-9c3e-49be-96fb-eba4a21ab702)

See on the bottom.

**Comment by rzhao271** [comment] 2024-03-19 15:41
Duplicate of #183503

**Closed** 2024-12-09 23:31 UTC
