### ISSUE TITLE
VS Code crashed and CANNOT be opened after restart to upgrade extensions

### ISSUE THREAD

**Issue by SuperJingke** [microsoft/vscode#221528] opened 2024-07-12 03:43 UTC
- VS Code Version: 1.91.1
- OS Version: macOS 11.7.10

For the latest version of VS Code, I navigated to the 'extension' tab, and clicked the 'restart to upgrade' button under the extensions. Then, the app automatically closed and didn't reopen the window. When I attempted to open the app, it refused to open and not be able to open it anymore.

**Comment by connectwithavinash** [comment] 2024-07-12 09:51
@SuperJingke Clean up the existing installation, and downgrade to an older version. Wait until some one releases a fix.

**Comment by gjsjohnmurray** [comment] 2024-07-12 10:01
> Wait until some one releases a fix.

@connectwithavinash - a fix for what? If the cause of the problem isn't identified how likely is that to happen?

**Comment by deepak1556** [comment] 2024-07-12 10:20
@SuperJingke can you provide the output of `code --verbose`

**Comment by connectwithavinash** [comment] 2024-07-15 09:33
@SuperJingke  @gjsjohnmurray Please Check below

- VS Code Version: 1.91.1
- OS Version: macOS 11.7.10

`[77102:0715/151504.383111:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /var/root/Library/Application Support/Code/Shared Dictionary/cache
[77102:0715/151504.384191:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /var/root/Library/Application Support/Code/Shared Dictionary/cache
[77102:0715/151504.384263:ERROR:simple_backend_impl.cc(751)] Simple Cache Backend: wrong file structure on disk: 1 path: /var/root/Library/Application Support/Code/Shared Dictionary/cache
[77102:0715/151504.386721:ERROR:disk_cache.cc(208)] Unable to create cache
[main 2024-07-15T09:45:04.388Z] [File Watcher (node.js)] Request to start watching: /var/root/Library/Application Support/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/var/root/Library/Application Support/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[77100:0715/151504.519694:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template
Segmentation fault: 11`

**Comment by deepak1556** [comment] 2024-07-15 10:56
@connectwithavinash there are two issues with your setup,

Applications user data folder is attempted to being created at `/var/root` and doesn't have appropriate permissions to do it. If the application is not installed as root then this path will not work and a lot more scenarios in the application will be broken. Ensure appropriate folder permissions or force the user data folder via `--user-data-dir` to fix this issue.

> [77100:0715/151504.519694:ERROR:node_bindings.cc(162)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template

Does seem related to https://github.com/microsoft/vscode/issues/219893, can you provide the output of `code --version --user-data-dir /tmp/vscode`

**Comment by connectwithavinash** [comment] 2024-07-15 16:41
@deepak1556 Re-installed 1.91.1, now everything works fine. Thanks for your hlep.

**Comment by SuperJingke** [comment] 2024-07-15 16:43
After I deleted the VS code app as well as the '**code**' folder and '**vscode-sqltools**' folder in the Library. The output of `code --version --user-data-dir /tmp/vscode`, it gives:
1.91.1
f1e16e1e6214d7c44d078b1f0607b2388f29d729
x64
After the re-installation, It seems okay now. 
And run the output of ` code --verbose`, it give a warning:
[3564:0715/123354.124391:WARNING:pref_notifier_impl.cc(60)] Init observer found at shutdown.
Does anyone know what's this mean? Thanks!

**Comment by deepak1556** [comment] 2024-07-15 17:09
the warning is unrelated and can be ignored. Closing as resolved for the original issue.

**Closed by deepak1556** 2024-07-15 17:09 UTC
Labels: info-needed
