### ISSUE TITLE
PLEASE! I adjure you! Shows window's text editor decorations on MiniMap 

### ISSUE THREAD

**Issue by cekkr** [microsoft/vscode#136360] opened 2021-11-03 14:31 UTC
I absolutely need the feature of showing text editor decorations on the MiniMap, for making more navigable my projects.

I also forked vscode for studying the code and I noticed two facts:
- Decorations could be easily implemented extending the yet existing rendering of text selection (although I admit it's a bit confusing)
-  It's a bit difficult to access to current decorations, seen that onDecorationsChanged doesn't pass an array with decorations and I'm too noob with vscode environment for obtaining it in the correct way

Anyway, I'm saying that for to mean that with the right guide I could directly implement the feature and then pull it, but since I would approach the vscode code only for this reason I might not write the code with the right guidelines principles. 

Seen that the request is not so difficult I really appreciate its implementation by the expert community.

You could also implement the option of showing on not the decoration on the MiniMap during the call of function vscode.window.createTextEditorDecorationType

Thank you,
Riccardo

**Comment by gjsjohnmurray** [comment] 2021-11-03 14:49
Looks like a duplicate of #82808

**Comment by cekkr** [comment] 2021-11-03 15:00
> Looks like a duplicate of #82808

Yes, there are a LOT of duplicate. So, please, can you implement this feature?

**Comment by alexdima** [comment] 2021-11-03 16:51
Let's track in #82808

**Closed by alexdima** 2021-11-03 16:51 UTC
