### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by Nouxx** [microsoft/vscode#72871] opened 2019-04-25 15:26 UTC
Issue Type: <b>Bug</b>

Hi,

For no apparent reason, my code colors have weirdly changed, adding white and blue tint even if my code is well formatted (see screenshot)

![image](https://user-images.githubusercontent.com/30227758/56747896-160d7900-677f-11e9-8276-f03fe43cb1d7.png)

Let me know if you need any information

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (16.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.6.1
vscode-scss-formatter|sib|1.4.1

</details>

**Comment by mjbvz** [comment] 2019-05-01 17:56
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, please share the text of the code along with screenshots

**Comment by mjbvz** [comment] 2019-05-10 18:41
Closing as likely duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/741, which should be fixed in insiders

**Closed by mjbvz** 2019-05-10 18:41 UTC
Labels: grammar, needs more info, typescript

**Comment by Nouxx** [comment] 2019-05-10 21:30
Hello, sorry for not giving you feedback. 
I also tried without any extensions, nothing changed
Hope this will be fixed, thanks!

**Comment by mjbvz** [comment] 2019-05-10 21:33
Please share the code as text

**Comment by Nouxx** [comment] 2019-05-10 21:37
```
import { Component, OnInit, Input, OnChanges, AfterViewChecked, ChangeDetectorRef, Output, EventEmitter } from '@angular/core';
import { IProperty, Property } from 'src/app/model/property.model';
import { InvariantsService } from 'src/app/services/crud/invariants.service';
import { IInvariant } from 'src/app/model/invariants.model';
import { TestService } from 'src/app/services/crud/test.service';
import { ITestCaseHeader } from 'src/app/model/testcase.model';
import { CdkDragDrop, moveItemInArray, transferArrayItem } from '@angular/cdk/drag-drop';
import { DraganddropService } from '../draganddrop.service';

@Component({
  selector: 'app-property',
  templateUrl: './property.component.html',
  styleUrls: ['./property.component.scss']
})
export class PropertyComponent implements OnInit, OnChanges, AfterViewChecked {

  @Input('propertiesByName') propertiesByName: Array<IProperty>;
  private propertyName: string;
  private propertyNameIsInvalid: boolean;

  // propertyValueAdded: sent when a new property value is added
  // in order to call addProperty() from parent component
  @Output() propertyValueAdded = new EventEmitter<string>();
  // propertyNameChanged: sent when the property name changed
  // in order to set the new propertyName as active
  @Output() propertyNameChanged = new EventEmitter<string>();

  private unassignedCountriesList: Array<String>;
  private showPropCountriesMainContent: boolean;
  private inv_countriesList: Array<IInvariant>;
  private inv_propertyTypeList: Array<IInvariant>;
  private propertiesList: Array<IProperty>;

  private testcaseheader: ITestCaseHeader;
  private showPropertyOptions: boolean;

  // unassigned country list
  private DragAndDropList: Array<string>;
  private DragAndDropId: string;

  constructor(
    private InvariantsService: InvariantsService,
    private TestService: TestService,
    private DragAndDropService: DraganddropService,
    private cdRef: ChangeDetectorRef
  ) { }

  ngAfterViewChecked() {
    // start the change detection only when the sub components (prop value) are loaded
    this.DragAndDropService.observablePropCountriesList.subscribe(r => { if (r) { this.DragAndDropList = r; } });
    this.cdRef.detectChanges();
  }

  ngOnChanges() {
    this.propertyNameIsInvalid = false;
    this.propertyName = this.propertiesByName[0].property;
  }

  ngOnInit() {
    this.propertyName = this.propertiesByName[0].property;
    this.showPropCountriesMainContent = true;
    this.unassignedCountriesList = new Array<string>();
    this.TestService.observableTestCase.subscribe(r => { this.testcaseheader = r.info; });
    this.DragAndDropService.observablePropCountriesList.subscribe(r => { if (r) { this.DragAndDropList = r; } });
    this.TestService.observableTestCaseProperties.subscribe(r => { this.propertiesList = r; });
    this.InvariantsService.observablePropertyTypeList.subscribe(r => { this.inv_propertyTypeList = r; });
    this.InvariantsService.observableCountriesList.subscribe(r => { this.inv_countriesList = r; if (r) { this.defineUnassginedCountries(); } });
    this.DragAndDropId = "propcountries-droplist-unassigned";
    this.DragAndDropService.addIDToPropCountriesList(this.DragAndDropId);
    this.showPropertyOptions = false;
    this.propertyNameIsInvalid = false;
  }

  dropCountry(event: CdkDragDrop<string[]>) {
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    } else {
      transferArrayItem(event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex);
    }
  }

  defineUnassginedCountries() {
    this.unassignedCountriesList = new Array<string>();
    this.inv_countriesList.forEach((country) => {
      let assigned = false;
      this.propertiesByName.forEach((prop) => {
        if (prop.country.includes(country.value)) {
          assigned = true;
        }
      })
      if (!assigned) { this.unassignedCountriesList.push(country.value); }
    });
  }

  addAPropertyValue() {
    this.propertyValueAdded.emit(this.propertyName);
  }

  // one way data binding has been implemented 
  // since we must ensure the property name that we are trying to insert
  // isn't already an existing property
  setPropertyName(newName: string) {
    var oldName = this.propertyName;
    if (this.propertiesList.find(p => p.property == newName)) {
      // property name already exists
      this.propertyNameIsInvalid = true;
    } else {
      // feeded property name doesn't exist 
      this.TestService.renameProperty(oldName, newName);
      this.propertyName = newName;
      this.propertyNameIsInvalid = false;
      this.propertyNameChanged.emit(this.propertyName);
    }
  }

  debug() {
    console.log(this.propertiesByName);
  }

}

```

**Comment by mjbvz** [comment] 2019-05-10 21:49
Thanks. I confirmed this is duplicate but we did not pull in the full fix this iteration. It will be in the 1.35 insiders
