### ISSUE TITLE
Extensions are not loading

### ISSUE THREAD

**Issue by lengeradam** [microsoft/vscode#206522] opened 2024-02-29 11:47 UTC
Does this issue occur when all extensions are disabled?: I can't see any extensions so I can't say.

- VS Code Version: 1.87.0
- OS Version: macOS 14.3.1 (23D60)

Steps to Reproduce:
1. Start VSCode
2. Switch to Extensions
3. No Extensions are displayed and it's stuck in loading mode (see screenshot).

![image](https://github.com/microsoft/vscode/assets/53938139/36d07551-e5ff-47f4-9b72-6ec9f2946fde)

**Comment by GabrielHangor** [comment] 2024-02-29 16:08
same

**Comment by diogovdias** [comment] 2024-02-29 16:11
Same!

**Comment by yhx-12243** [comment] 2024-02-29 16:12
Same!

**Comment by aswinprasad** [comment] 2024-02-29 17:01
Started facing same issue today.
VS Code version: 1.88.0-insider
OS version: Windows_NT x64 10.0.22621

**Comment by KhoaLee** [comment] 2024-03-01 03:27
Same on Mac Sonoma 14.3.1 despit of clearing cache and editor history. Still loading extensions tab to infinity and beyond

**Comment by Invecticus** [comment] 2024-03-01 03:47
Im having this issue as well, since it auto updated a few days ago.

**Comment by GabrielHangor** [comment] 2024-03-01 07:04
Smth wrong with the new release...

**Comment by zonterone** [comment] 2024-03-01 08:30
Have same issue on macos sonoma 14.3.1 and vscode Version: 1.87.0 (Universal)

**Comment by JulindM** [comment] 2024-03-01 14:02
Same issue here. Indefinitely loading, no errors, nothing.

Even starting with 
```sh
$ code --disable-extensions
```
it still never loads

Running with
```sh
$ code --verbose
```
shows also nothing relevant

**Comment by lucasfellipe3g** [comment] 2024-03-01 18:20
same here!

**Comment by ederhmaia** [comment] 2024-03-01 18:32
same

**Comment by mmmmmob** [comment] 2024-03-03 03:10
Same issue here, look up at developer console and found this error while loading extension page.

![SCR-20240303-jigs](https://github.com/microsoft/vscode/assets/141404845/186d0d78-de05-4530-9717-02a41de44506)

**Comment by powd** [comment] 2024-03-03 03:58
Same here.

<img width="594" alt="image" src="https://github.com/microsoft/vscode/assets/98982886/eda13739-53e5-41a0-8d71-74aa40f2dd59">

BTW, in my case this (if the extension problem is a root cause) has also increased the impact on the profiles—I can neither create a new profile (no errors are shown, but a profile is not created after clicking the button) nor see the contents of a profile (infinite loading occurs as well).

After temporarily downgrading VSC to 1.86.2 all works well again. ✌️

**Comment by gustavospriebe** [comment] 2024-03-04 02:01
i had to downgrade to 1.86.2 and disable automatic updates from VSCode. every time i restart my windows, i have to reinstall this version to make it work again.

**Comment by GabrielHangor** [comment] 2024-03-04 06:50
GJ MS GJ

**Comment by GabrielHangor** [comment] 2024-03-04 07:55
Come on they're not only not displayed they are also mostly not working

**Comment by sandy081** [comment] 2024-03-04 08:19
Very sorry about this. Those who are seeing this behaviour, can you please share following information?

- Set default log level to trace: F1 > Developer: Set Log Level > Trace (Use Double Checkmark on the far right)

![Image](https://github.com/microsoft/vscode/assets/10746682/5bbb8278-466c-4797-bb56-2155eb8b1e94)

- Restart VS Code
- Share following logs
  - F1 > Open View... > Shared
  - F1 > Open View... > Window

**Comment by mmmmmob** [comment] 2024-03-04 09:47
@sandy081 Hi, I'd love to help with sharing some log files, but I'm a bit confused about the method you mentioned. (Sorry, I'm a bit new to the issue report here 😅)

- I successfully set the log level to trace.
- Cannot find the option `Shared` on Open View. There's `Window` on my machine.
- After selecting `Window`, the below pane opened with an endless number of logs coming in. I'm not sure what to share with you here.
<img width="1507" alt="image" src="https://github.com/microsoft/vscode/assets/141404845/bd6a39eb-3c1e-4ad2-8372-30cec3e81241">

Could you please clarify more on which log file(s) I have to share with you? Or are there any steps that I missed? Thank you in advance. 🙏🏼

**Comment by sandy081** [comment] 2024-03-04 09:51
That explains, not having shared log implies the shared process (one of the VS Code core processes) has not started. This could be the reason for extensions not loading.

In this case, can you please share the main process log - `F1 > Open View... > Main`. Also please copy and paste the content of Window log.

**Comment by mmmmmob** [comment] 2024-03-04 10:46
Not sure if it's a correct log to share or not but hope this helps! 
https://gist.github.com/mmmmmob/b475fa65f0ffee1a010fb20986ff4636

> That explains, not having shared log implies the shared process (one of the VS Code core processes) has not started. This could be the reason for extensions not loading.
> 
> In this case, can you please share the main process log - `F1 > Open View... > Main`. Also please copy and paste the content of Window log.

**Comment by yimme** [comment] 2024-03-04 11:13
Here is my main log: [https://gist.github.com/yimme/b52b858d7ce768c2c0bef74175c61247](https://gist.github.com/yimme/b52b858d7ce768c2c0bef74175c61247)

**Comment by sandy081** [comment] 2024-03-04 11:15
@yimme Do you also not see **shared** log?

**Comment by sandy081** [comment] 2024-03-04 11:16
Also please share **window** log

**Comment by yimme** [comment] 2024-03-04 11:18
> @yimme Do you also not see **shared** log?

Correct, no shared log. 
Window log coming up!

**Comment by yimme** [comment] 2024-03-04 11:20
> Also please share **window** log

[https://gist.github.com/yimme/69c0e1ded88f1d3fef90eea1f76f9d83](https://gist.github.com/yimme/69c0e1ded88f1d3fef90eea1f76f9d83)

**Comment by deepak1556** [comment] 2024-03-04 17:02
From the logs seems like we are failing at ipcReady signal from shared process https://github.com/microsoft/vscode/blob/3e670468cacc479c19c81a72f6c88e14a67aa7a9/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L523

Can users provide the output of `code --status` from terminal while there is an active instance of VS Code window.

**Comment by nahue** [comment] 2024-03-04 17:05
> From the logs seems like we are failing at ipcReady signal from shared process
> 
> https://github.com/microsoft/vscode/blob/3e670468cacc479c19c81a72f6c88e14a67aa7a9/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L523
> 
> Can users provide the output of `code --status` from terminal while there is an active instance of VS Code window.

```code --status
{}

Version:          Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS Version:       Darwin arm64 23.2.0
CPUs:             Apple M1 Pro (10 x 24)
Memory (System):  16.00GB (0.09GB free)
Load (avg):       4, 5, 5
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 467ef1b0-14de-4a87-94ba-a46c3580bb41
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           enabled
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled

CPU %	Mem MB	   PID	Process
    1	   147	 32632	code main
    4	    66	 32636	   gpu-process
    0	    33	 32637	   utility-network-service
    4	   279	 32638	window [1] (scenario.py — be-app)
    0	    49	 32679	shared-process
    0	    49	 32680	fileWatcher [1]
    0	   213	 32686	extensionHost [1]
    0	    33	 32735	     /Users/nahuelchaves/code/concntric/be-app/venv/bin/python /Users/nahuelchaves/.vscode/extensions/charliermarsh.ruff-2024.12.0-darwin-arm64/bundled/tool/server.py
    0	   541	 33014	     electron-nodejs (bundle.js )
    0	    49	 33183	     electron-nodejs (server-node.js )
    0	    82	 33187	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/nahuelchaves/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=32686
    0	    49	 32698	ptyHost
    0	     0	 32710	     /bin/zsh -il
    0	     0	 32729	     /bin/zsh
    0	     0	 32936	     /bin/zsh

Workspace Stats:
|  Window (scenario.py — be-app)
|    Folder (be-app): more than 33439 files
|      File types: py(6308) pyc(3432) json(188) xlsx(155) html(155) txt(149)
|                  pdf(52) md(51) hpp(50) whl(35)
|      Conf files: dockerfile(14) github-actions(3) launch.json(1)
|                  settings.json(1)
|      Launch Configs: python```

**Comment by stephenhowells** [comment] 2024-03-04 17:09
> From the logs seems like we are failing at ipcReady signal from shared process
> 
> https://github.com/microsoft/vscode/blob/3e670468cacc479c19c81a72f6c88e14a67aa7a9/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L523
> 
> Can users provide the output of `code --status` from terminal while there is an active instance of VS Code window.
```
{}

Version:          Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS Version:       Darwin arm64 23.2.0
CPUs:             Apple M3 Max (16 x 24)
Memory (System):  64.00GB (0.09GB free)
Load (avg):       6, 4, 4
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id 1cf4cbd2-105f-4584-8b94-cd5412d6111a
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           enabled
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled

CPU %   Mem MB     PID  Process
    0      197   84673  code main
    0       66   84676     gpu-process
    0       66   84677     utility-network-service
    1      459   84678  window [1] (Select.vue — leap)
    0       66   84679  shared-process
    0       66   84680  fileWatcher [1]
    0      590   84681  extensionHost [1]
    0      131   84693       electron-nodejs (index.js )
   83      393   85195       electron-nodejs (server.js )
    1      197   85196       electron-nodejs (server.js )

Workspace Stats: 
|  Window (Select.vue — leap)
|    Folder (leap): 228 files
|      File types: js(60) ts(38) vue(26) json(17) mjs(14) map(10) css(7)
|                  ico(2) DS_Store(1) env(1)
|      Conf files: tsconfig.json(2) package.json(2) settings.json(1)
```

**Comment by deepak1556** [comment] 2024-03-04 17:12
Thanks, confirms there is no process crash. As a next step, please run our bisect tool `npx @vscode/vscode-bisect` to narrow down the commit that caused the regression.

**Comment by nahue** [comment] 2024-03-04 17:23
> Thanks, confirms there is no process crash. As a next step, please run our bisect tool `npx @vscode/vscode-bisect` to narrow down the commit that caused the regression.

Tried and every build is able to list extensions.

```
[build] deleting cache directory /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect
✔ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) …
✔ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) …
[build] fetching all builds from https://update.code.visualstudio.com/api/commits/insider/darwin-arm64?released=false...
[build] total 176 builds with roughly 7 steps
[build] downloading build from https://update.code.visualstudio.com/commit:1cfc62d46e6b9dd217cd485d7d4591136f421d70/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/1cfc62d46e6b9dd217cd485d7d4591136f421d70...
[build] starting desktop build 1cfc62d46e6b9dd217cd485d7d4591136f421d70...
✔ Is 1cfc62d46e6b9dd217cd485d7d4591136f421d70 good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:ebed3f2345cadd89179eb593154498450285e500/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/ebed3f2345cadd89179eb593154498450285e500...
[build] starting desktop build ebed3f2345cadd89179eb593154498450285e500...
✔ Is ebed3f2345cadd89179eb593154498450285e500 good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:7f07489455fda8bc1841b98b9b7e58b20b7ee3ef/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/7f07489455fda8bc1841b98b9b7e58b20b7ee3ef...
[build] starting desktop build 7f07489455fda8bc1841b98b9b7e58b20b7ee3ef...
✔ Is 7f07489455fda8bc1841b98b9b7e58b20b7ee3ef good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:13a2ba89a6159246bdf9b9d220c30a57eecfbd79/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/13a2ba89a6159246bdf9b9d220c30a57eecfbd79...
[build] starting desktop build 13a2ba89a6159246bdf9b9d220c30a57eecfbd79...
✔ Is 13a2ba89a6159246bdf9b9d220c30a57eecfbd79 good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:15a0f3c48f9315669c97f101a5d954464285e6ac/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/15a0f3c48f9315669c97f101a5d954464285e6ac...
[build] starting desktop build 15a0f3c48f9315669c97f101a5d954464285e6ac...
✔ Is 15a0f3c48f9315669c97f101a5d954464285e6ac good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:bb171489789c9a49e985a4a2c8694138d70d42c1/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/bb171489789c9a49e985a4a2c8694138d70d42c1...
[build] starting desktop build bb171489789c9a49e985a4a2c8694138d70d42c1...
✔ Is bb171489789c9a49e985a4a2c8694138d70d42c1 good or bad? › Good
[build] downloading build from https://update.code.visualstudio.com/commit:61187a0b6547df5911a0ee259f7afda46bac7ec3/darwin-universal/insider...
[build] unzipping build to /var/folders/9x/c9dkqlx93xx_vvr03bczs58m0000gn/T/vscode-bisect/.builds/61187a0b6547df5911a0ee259f7afda46bac7ec3...
[build] starting desktop build 61187a0b6547df5911a0ee259f7afda46bac7ec3...
✔ Is 61187a0b6547df5911a0ee259f7afda46bac7ec3 good or bad? › Good
[build] All builds are good!
```

**Comment by deepak1556** [comment] 2024-03-04 17:34
@nahue thanks, can you try the following

* Download and extract `1.87` into a temp folder, ex: `~/vscode-sanity-check`
* Start the application with following arguments `~/vscode-sanity-check/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --user-data-dir /tmp/vscode-sanity-check --extensions-dir /tmp/vscode-sanity-check-extensions`
* Confirm if the extension view fails to load

**Comment by nahue** [comment] 2024-03-04 18:15
> * ~/vscode-sanity-check/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --user-data-dir /tmp/vscode-sanity-check --extensions-dir /tmp/vscode-sanity-check-extensions

It works fine

![Captura de pantalla 2024-03-04 a la(s) 15 14 29](https://github.com/microsoft/vscode/assets/96837/8d94851b-fe5a-4a7a-bcc9-79553a5c26c1)

**Comment by nahue** [comment] 2024-03-04 18:16
maybe its a commonly used extension?

**Comment by deepak1556** [comment] 2024-03-04 18:25
Seems to be the case, can you also confirm if launching your default installation of VS Code stable with `code --disable-extensions` also resolves the issue ?

**Comment by nahue** [comment] 2024-03-04 18:28
that does not solve the issue, really strange

**Comment by nahue** [comment] 2024-03-04 18:29
Also tried removing everything in settings.json... same issue

**Comment by nahue** [comment] 2024-03-04 18:49
Also went from Universal to Apple Silicon build... same issue

**Comment by bpasero** [comment] 2024-03-04 18:57
@nahue thanks for being patient here to try out things. I am curious if possibly a setting you have configured in user or workspace settings might have any impact. Could you try to make the test in https://github.com/microsoft/vscode/issues/206522#issuecomment-1977116535 get closer to your real installation by copying over settings?

**Comment by nahue** [comment] 2024-03-04 19:09
> @nahue thanks for being patient here to try out things. I am curious if possibly a setting you have configured in user or workspace settings might have any impact. Could you try to make the test in [#206522 (comment)](https://github.com/microsoft/vscode/issues/206522#issuecomment-1977116535) get closer to your real installation by copying over settings, maybe with a restart of VS Code after you changed settings?

Summarizing my tests so far

* Sanity check build with my settings (after restart) - Extension List OK
* Sanity check build without any settings - Extension List OK
* Local installation without extensions - Extension List FAIL
* Local installation without extensions and clean settings.json file - Extension List FAIL

**Comment by bpasero** [comment] 2024-03-04 19:40
@nahue to clarify, you are opening the same folder in all these cases? Does it make any difference to try from an empty window? You can test so from the command line via adding a `--new-window` option.

This might be a wild guess: did you ever configure specific network proxy settings in your OS or in VS Code?

**Comment by nahue** [comment] 2024-03-04 19:55
@bpasero tried 

* Sanity check build with --new-window - Extension List OK
* Local installation without extensions with --new-window - Extension List FAIL

I dont have any specific network config, no VPN, no static IP, no weird settings in /etc/hosts, and no firewall

**Comment by bpasero** [comment] 2024-03-04 20:32
@nahue got 2 more ideas before I need to call it a day

1. can you see if running with `--no-cached-data` as command line flag helps?

2. can you copy the `User` folder from  your local installation folder (`/Users/<your name>/Library/Application Support/Code`) to the sanity check build folder (`/tmp/vscode-sanity-check`) to see if this reproduces the issue. This would copy more than just settings, also all UI state.

**Comment by deepak1556** [comment] 2024-03-05 02:53
@nahue thanks again for helping us identify the issue, can you also check the following in addition to the above two points from @bpasero 

* In your default installation, are you able to open the integrated terminal without issues ?
* To rule out any source modifications by an extension, can you check if `diff -rq /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out ~/vscode-sanity-check/Visual\ Studio\ Code.app/Contents/Resources/app/out` returns empty result ?

**Comment by nahue** [comment] 2024-03-05 02:56
Sorry guys i will check tomorrow morning, had to go out!

**Comment by mmmmmob** [comment] 2024-03-05 04:47
> @nahue thanks again for helping us identify the issue, can you also check the following in addition to the above two points from @bpasero
> 
> * In your default installation, are you able to open the integrated terminal without issues ?
> * To rule out any source modifications by an extension, can you check if `diff -rq /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out ~/vscode-sanity-check/Visual\ Studio\ Code.app/Contents/Resources/app/out` returns empty result ?

I just followed up with what you and @nahue done last night and found same result

- Extension loading on VSCode Bisect version works fine
- Sanity version also works fine
- Default installation still not loading

---

Here's my result from your request in the quote:

- Yes, I'm able to open integrated terminal on my default installation
- Here's my diff result from your command provided

```
Files /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js and /Users/theppitak/vscode-sanity-check/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js differ
Only in /Applications/Visual Studio Code.app/Contents/Resources/app/out: bootstrap-amd.js.apc.extension.backup
Files /Applications/Visual Studio Code.app/Contents/Resources/app/out/main.js and /Users/theppitak/vscode-sanity-check/Visual Studio Code.app/Contents/Resources/app/out/main.js differ
Only in /Applications/Visual Studio Code.app/Contents/Resources/app/out: main.js.apc.extension.backup
Only in /Applications/Visual Studio Code.app/Contents/Resources/app/out: modules
Only in /Applications/Visual Studio Code.app/Contents/Resources/app/out: patch
Only in /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench: workbench-apc-extension.html
```

**Comment by deepak1556** [comment] 2024-03-05 06:05
Thanks for following up! the diff results do stand out, look likes the VS Code sources are patched and based on the filenames seem like they come from this extension https://github.com/drcika/apc-extension. Are other affected users also have this extension installed ?

@mmmmmob can you move out `/Applications/Visual\ Studio\ Code.app` to some temp folder and replace with a fresh installation. Does the issue get resolved ? Helps confirm if the extension had an effect on this issue.

**Comment by yuuuxt** [comment] 2024-03-05 06:39
> Are other affected users also have this extension installed ?

I'm having this issue and I have `apc-extension` installed.

**Comment by mmmmmob** [comment] 2024-03-05 07:07
> can you move out `/Applications/Visual\ Studio\ Code.app` to some temp folder and replace with a fresh installation. Does the issue get resolved ? Helps confirm if the extension had an effect on this issue.+

@deepak1556 Happy to report that your assumption is correct! I just freshly installed VS Code from website and during first boot of the app the extension panel works fine. However there's a popup direct me to restart which might came from APC Extension. (rechecked on extension panel as shown in the picture below.)

I tried restart the app to apply APC extension settings but surprisingly extension panel also works fine now.

Before restart > ![SCR-20240305-mnee](https://github.com/microsoft/vscode/assets/141404845/021a7852-5738-45cc-892e-583377923aa6)

After restart > ![SCR-20240305-moqv](https://github.com/microsoft/vscode/assets/141404845/1917e3a6-3f40-4dcc-b4cf-a561ff85e5cf)

**Comment by deepak1556** [comment] 2024-03-05 07:36
Great, thanks a lot to everyone helping with the debugging and confirming the root cause!

Given this is caused by an extension that modifies our source, there is nothing actionable from our end. We should however have a signal if the source is modified to be able to catch these scenarios early on. I will follow-up on that. Closing this issue as resolved for now.

**Closed by deepak1556** 2024-03-05 07:36 UTC
Labels: extensions

**Comment by deepak1556** [comment] 2024-03-05 08:39
Confirmed that we do track the integrity of sources today and surface a notification to users via https://github.com/microsoft/vscode/blob/d73fa8b14a6c873958d00a7d7ad13fcb540a052c/src/vs/workbench/services/integrity/electron-sandbox/integrityService.ts#L85-L120. It is also added to issues created from our builtin issue reporter. We can add this data to trace logs as well for cases were the issues are created outside the application.

**Comment by joaomoreno** [comment] 2024-03-05 08:42
> We can add this data to trace logs as well for cases were the issues are created outside the application.

This is a great idea: https://github.com/microsoft/vscode/issues/206874

**Comment by GabrielHangor** [comment] 2024-03-05 08:59
Can confirm that after reinstalling the VS Code and uninstalling the APC extensions everything is working now...

**Comment by nahue** [comment] 2024-03-05 13:05
Cool thanks! i uninstalled the extension with ```code --uninstall-extension drcika.apc-extension``` and then replaced the vscode app

**Comment by JulindM** [comment] 2024-03-05 13:25
Referncing the issue over at https://github.com/drcika/apc-extension/issues/160#issuecomment-1978397126 the resolution is to simply disable the extension using it's quick action, update then enable again.

No need for cli commands or reinstalling vscode.

**Comment by concrete13377** [comment] 2024-03-27 05:53
no option to restart Apc

**Comment by mmmmmob** [comment] 2024-03-27 08:03
> no option to restart Apc

Have you try this command? https://github.com/drcika/apc-extension/issues/160#issuecomment-1978405102

**Comment by concrete13377** [comment] 2024-03-27 08:16
> > no option to restart Apc
> 
> Have you try this command? [drcika/apc-extension#160 (comment)](https://github.com/drcika/apc-extension/issues/160#issuecomment-1978405102)

<img width="457" alt="image" src="https://github.com/microsoft/vscode/assets/32034827/5ead5e94-b90e-42d8-b624-11a9f0c518ea">
