### ISSUE TITLE
Switch between view column is not working for WebView on Mac

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#100267] opened 2020-06-16 08:03 UTC
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Open a markdown file and open the preview window
2. Put the file and preview into different view columns, like:
<img width="1318" alt="Screen Shot 2020-06-16 at 4 01 07 PM" src="https://user-images.githubusercontent.com/6193897/84747987-9c6fc480-afea-11ea-9140-b819abf11f4c.png">

3. Use the keyboard shortcut (cmd + 1, cmd + 2) to switch the focus between the two view columns.
4. When the webview gets the focus, the focused view column cannot be switched using the keyboard shortcut anymore

> Note: This issue seems only occur on Mac, I do not observe this on Windows.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-11-05 20:26
Duplicate of #97992

**Closed by mjbvz** 2020-11-05 20:26 UTC
Labels: bug, keybindings, webview
