### ISSUE TITLE
 SplitLinesCollection: attempt to access a 'newer' model

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#44014] opened 2018-02-20 07:31 UTC
Issue Id: <b>b24f9f42-945e-8a78-02f2-b2da3f38b283</b><br /><br />*Versions* <br />- 1.20.1<br />*Stack* <br />Error: SplitLinesCollection: attempt to access a 'newer' model<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L180:9](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/common/viewModel/splitLinesCollection.ts#L180:9)<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L560:7 (_ensureValidState)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/common/viewModel/splitLinesCollection.ts#L560:7 (_ensureValidState))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L335:20 (getViewLineMinColumn)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/common/viewModel/viewModelImpl.ts#L335:20 (getViewLineMinColumn))<br />[/vs/editor/common/viewLayout/viewLinesViewportData.ts#L98:15 (getLineMinColumn)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/common/viewLayout/viewLinesViewportData.ts#L98:15 (getLineMinColumn))<br />[/vs/editor/browser/view/viewImpl.ts#L412:21](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L412:21)<br />[/vs/editor/browser/view/viewImpl.ts#L383:29 (_actualRender)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L383:29 (_actualRender))<br />[/vs/editor/browser/view/viewImpl.ts#L590:9 (func)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L590:9 (func))<br />[/vs/editor/browser/view/viewImpl.ts#L383:2 (safeInvokeNoArg)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L383:2 (safeInvokeNoArg))<br />[/vs/editor/browser/view/viewImpl.ts#L239:7 (_renderNow)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L239:7 (_renderNow))<br />[/vs/editor/browser/view/viewImpl.ts#L533:8 (_flushAccumulatedAndRenderNow)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/view/viewImpl.ts#L533:8 (_flushAccumulatedAndRenderNow))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#L323:13 (render)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/widget/codeEditorWidget.ts#L323:13 (render))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#L181:7 (render)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/editor/browser/widget/codeEditorWidget.ts#L181:7 (render))<br />[/vs/workbench/parts/debug/electron-browser/repl.ts#L256:17 (layout)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/workbench/parts/debug/electron-browser/repl.ts#L256:17 (layout))<br />[/vs/workbench/parts/debug/electron-browser/repl.ts#L202:8 (layout)](https://github.com/microsoft/vscode/blob/f88bbf9137d24d36d968ea6b2911786bfe103002/src/vs/workbench/parts/debug/electron-browser/repl.ts#L202:8 (layout))<br />

**Comment by alexandrudima** [comment] 2018-02-26 12:04
Duplicate of #29033

**Closed by alexandrudima** 2018-02-26 12:04 UTC
Labels: error-telemetry
