### ISSUE TITLE
Restart clears minimal document resize history

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#160773] opened 2022-09-13 09:44 UTC
Enable split view and resize a document to its minimal horizontal size
clicking the left and right document expands and shrinks the documents (very useful feature)

if the window size expands past the point when the document was resized. (either manually or simply shrinking a side pannel)
both documents will expand, rather than just the larger one (another bug/feature)
sadly the size at which it starts expanding is reset when vscode restarts
so everytime I shrink a side pannel after restarting, I then have to resize the small document again back down to its minimal size

**Comment by joaomoreno** [comment] 2022-09-13 12:07
This needs to be a setting at the splitview layer which makes sure that minimally sized views remain minimally sized, even as the layout expands.

**Comment by joaomoreno** [comment] 2022-09-13 12:08
Actually... duplicate of https://github.com/microsoft/vscode/issues/70083

**Closed by joaomoreno** 2022-09-13 12:08 UTC
Labels: feature-request, splitview-widget
