### ISSUE TITLE
Inconsistent behavior in search pane (cyrillic symbols)

### ISSUE THREAD

**Issue by ovcharenko-di** [microsoft/vscode#79447] opened 2019-08-19 13:58 UTC
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open new folder with some structure and files (language doesn't matter)
2. Create new file with at least 2 similar lines, but one is completely latin and one with cyrillic symbols with "_" in front (as shown on the screenshot below)
3. Open search pane and run search with the similar part of both strings
4. There are two hits in search results, but cyrillic string is missing first symbols.

![image](https://user-images.githubusercontent.com/24920942/63271289-7e3e1880-c2a2-11e9-8657-047d42608dee.png)

**Comment by roblourens** [comment] 2019-08-21 17:31
This is just due to the definition of `\b` but we should use our custom wordSeparator for this process too.

**Comment by roblourens** [comment] 2019-10-10 00:44
I think we need to be able to pass in the wordSeparators from the editor setting to this helper https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L595 called from searchModel.ts

**Comment by roblourens** [comment] 2019-10-27 23:39
Dupe of https://github.com/microsoft/vscode/issues/27280

**Closed by roblourens** 2019-10-27 23:39 UTC
Labels: bug, help wanted, search
