### ISSUE TITLE
Find in document hilights last typed character even though the find field is empty

### ISSUE THREAD

**Issue by Digvijay** [microsoft/vscode#73468] opened 2019-05-08 12:57 UTC
I have search existing issues to avoid creating duplicate but this is not reported it seems.

- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.4 (18E226)

Steps to Reproduce:

1. Open any document with text/code
2. Find (Cmd+F) for a word you know exists in document (e.g. bool)
3. Backspace until find field is blank
4. The last typed character is still hilighted in all locations
![image](https://user-images.githubusercontent.com/107279/57376916-73eb8900-71a1-11e9-8db5-17201a8baa3c.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by rebornix** [comment] 2019-08-07 18:25
/duplicate of https://github.com/microsoft/vscode/issues/45211

**Closed** 2019-08-07 18:25 UTC
Labels: *duplicate, bug, editor-find
