### ISSUE TITLE
Removal of the Santa Hat on vscode insiders is very offensive to me

### ISSUE THREAD

**Issue by LibraryFormid** [microsoft/vscode#87296] opened 2019-12-18 23:49 UTC
Removing the Santa Hat on vscode insiders is very offensive to me. Getting offended by one person is against my atheist religion. Bowing before SJW's as part of a product update is completely unacceptable. Please readd it immediately and make it your top priority. To me this is almost equally offensive as censorship.

- VSCode Version: 1.42.0-insider
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Get offended.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Jorji-Costava** [comment] 2019-12-18 23:51
comparing my religion to nazi germany is incredibly hateful, and I don't think this is a story microsoft wants getting to the news.

**Comment by LibraryFormid** [comment] 2019-12-18 23:54
> comparing my religion to nazi germany is incredibly hateful, and I don't think this is a story microsoft wants getting to the news.

Too late! Spreading it wide on the internet of the hilarity of binding to an SJW troll.

**Comment by Xaekai** [comment] 2019-12-19 01:55
Given that the article the original author linked was titled "What does _Judaism_ say about Christmas", the site it is hosted on is a self-identified religious text repository, and the article itself describes how Christmas is now de factor secular holiday, I believe the original issue author was incontestably **acting in bad faith**.

**Comment by Anonimista** [comment] 2019-12-19 05:45
Bring back the Santa hat!

**Comment by egamma** [comment] 2019-12-19 08:04
Duplicate of #87291

**Closed by egamma** 2019-12-19 08:04 UTC

**Comment by lukaszarczynski** [comment] 2019-12-19 12:18
You've changed this icon to _special snowflake_ xD Great idea
