### ISSUE TITLE
[Feature Request] Add Drag and drop to include image and js files in enclosed <img> and <script> tags

### ISSUE THREAD

**Issue by VissnuK** [Microsoft/vscode#46094] opened 2018-03-19 09:26 UTC
- VSCode Version: All Versions
- OS Version: All Platforms

Feature Desciption

1. Add Drag and drop to include image and js files in enclosed **`<img>`** and **`<script>`** tags.

**Comment by aeschli** [comment] 2018-03-19 14:51
duplicate of #5772

**Closed by aeschli** 2018-03-19 14:51 UTC
Labels: feature-request
