### ISSUE TITLE
Add an API for extensions to resolve variables in configurations

### ISSUE THREAD

**Issue by ChaosinaCan** [microsoft/vscode#70769] opened 2019-03-19 17:13 UTC
I would like to have a way for extensions to resolve strings containing variables like `${workspaceFolder}`, similarly to how this is done for tasks and other configuration.

I am trying to write an extension that hooks into a script which may be named differently in different projects. I will search for the script in a default location, but I've added a setting to allow a workspace to override the location as needed.

My code looks something like this:

```json
// package.json
...
"contributes": {
  "configuration": {
    "type": "object",
    "title": "My Extension",
    "properties": {
      "myext.entryPoint": {
        "type": "string",
        "default": ""
      }
    }
  }
```

```ts
import * as vscode from 'vscode';
import * as path from 'path';

function getEntryPoint() {
    const config = vscode.workspace.getConfiguration('myext');
    const entryPoint = config.get<string>('entryPoint');

    if (entryPoint) {
        return entryPoint;
    } else {
        // If the setting doesn't override the entry point, 
        // assume it is in the workspace folder with a default name.
        return path.join(vscode.workspace.rootPath, 'the_script.py');
    }
}
```

If I then create a workspace with these settings...

```json
// .vscode/settings.json
{
  "myext.entryPoint": "${workspaceFolder}/a_different_script.py"
}
```

...I see that `config.get('entryPoint')` returns exactly that string without resolving `${workspaceFolder}`, so I need to somehow resolve that variable. I have enough information to do a search and replace and resolve it on my own, but it would be much more convenient if I had some way to ask VS Code to resolve it, either by giving some form of access to [variableResolver.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/common/variableResolver.ts) or having WorkspaceConfiguration resolve the variables when I get them.

**Comment by isidorn** [comment] 2019-03-20 08:31
fyi @weinand @alexr00

**Comment by weinand** [comment] 2019-03-20 09:15
I think a fundamental problem is: why are we interpolating variables in "task.json" and "launch.json" but not in "settings.json".
Placing the substitution burden on clients that read configurations is IMO the wrong approach because it gives the impression that variables are supported in settings everywhere (which is not the case).
/cc @bpasero

**Comment by alexr00** [comment] 2019-03-20 09:40
I do think we need to be careful with variables in settings. I've had a request for allowing input variables in settings, which I don't think makes sense (when should a setting that requires input be resolved??) .

**Comment by isidorn** [comment] 2019-03-20 15:00
Related https://github.com/Microsoft/vscode/issues/2809

**Comment by no-stack-dub-sack** [comment] 2019-04-27 21:40
I also think it would be nice if variable interpolation was supported in settings.json, but I can see how the questions of when some of them should be resolved would be an issue. Maybe more limited support for settings.json, such as ${workspaceFolder} which should be constant.

**Comment by kejxu** [comment] 2019-08-20 00:56
we're having a very similar issue to this:

our debugger extension is going to parse a configuration and propagate the debug requests to language-specific debugger extensions (`vscode-python`, `vscode-cpptools`). 

for example, for the following configuration
```json
{
    "name": "debug",
    "type": "newtype",
    "request": "launch",
    "target": "${file}"
},
```
the target `${file}` points to an XML file that contains the actual launch requests. We need to actually parse that file and generate debug requests to the other debuggers.

Since we need access to `vscode.debug.startDebugging()`, this needs to take place inside `vscode.DebugConfigurationProvider.resolveDebugConfiguration()` (not the debug adapter). For this reason, we need an API to resolve VS Code variables manually (inside the extension's context).

**Comment by weinand** [comment] 2019-08-20 08:52
@kejxu please file a new issue for your request as your use case is sufficiently different from resolving variables in settings.

**Comment by kejxu** [comment] 2019-08-20 15:13
> @kejxu please file a new issue for your request as your use case is sufficiently different from resolving variables in settings.

thanks for the pointer! created https://github.com/microsoft/vscode/issues/79518

**Comment by jrieken** [comment] 2019-10-23 15:07
/duplicate of https://github.com/microsoft/vscode/issues/46471

**Closed** 2019-10-23 15:07 UTC
Labels: *duplicate, api, feature-request
