### ISSUE TITLE
Duplicate icon due to wrong wm-class when running VSCode with electron options under wayland

### ISSUE THREAD

**Issue by xuanruiqi** [microsoft/vscode#206554] opened 2024-02-29 18:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Launch VSCode under Wayland with electron options, say `code --ozone-platform-hint=auto` to have Electron run on native Wayland. I'm under GNOME.
2. Since this is an electron option rather than a VSCode option, of course it complains: Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
3. Code appears under an icon different from the pinned VSCode icon. It's grouped under code-url-handler.desktop. In the same manner as #61989.
4. Launching the GNOME Looking Glass shows that it indeed has wmclass code-url-hander as opposed to Code.

I've tested and it works all fine when I launch it without options, or only with VSCode options. I am not all that sure why WMClass is recognized as "code-url-handler" once you add the options.

Can confirm that this is a regression, since it worked fine on 1.86.2.

**Comment by xuanruiqi** [comment] 2024-02-29 19:02
Likely closely related to #154693.

**Comment by ReillyBrogan** [comment] 2024-03-07 19:27
> Likely closely related to #154693.

Not "closely related", literally the exact same issue. This behavior is a direct consequence of that issue, and would be fixed by fixing that issue.

This should be closed as a duplicate.

**Comment by xuanruiqi** [comment] 2024-03-13 09:05
> > Likely closely related to #154693.
> 
> Not "closely related", literally the exact same issue. This behavior is a direct consequence of that issue, and would be fixed by fixing that issue.
> 
> This should be closed as a duplicate.

Yes, fixing #154693 will fix this issue once and forever. That said, this is not a duplicate. There's definitely another regression sitting somewhere.

**Comment by ReillyBrogan** [comment] 2024-03-14 02:37
> > > Likely closely related to #154693.
> > 
> > 
> > Not "closely related", literally the exact same issue. This behavior is a direct consequence of that issue, and would be fixed by fixing that issue.
> > This should be closed as a duplicate.
> 
> Yes, fixing #154693 will fix this issue once and forever. That said, this is not a duplicate. There's definitely another regression sitting somewhere.

The change in behavior is that `1.87.0` started setting the `desktopName` key in the `package.json`. Electron reads from this key to set the appId, though it will fall back on the `productName` if not set. This means that packages that were previously overriding the `productName` now need to override the `desktopName` as well, which is a bug with that package. 

Regardless, the root cause of having "duplicate icons" is that the window appId does not match the name of the `.desktop` file. Which is the exact issue as described in #154693, and why there's no reason in having this open as it just splits attention on the issue tracker unnecessarily.

**Comment by ninelore** [comment] 2024-10-17 20:30
vscode sets the wm class to `code-url-handler` under conditions which i couldn't identify yet. This shouldnt happen since this basically signals to desktop environments that vscode and the url handler are different applications.

Fixing this and reverting #63750 should properly fix #61989.

**Comment by ReillyBrogan** [comment] 2024-10-17 20:35
This has been fixed by microsoft/vscode#231472

**Comment by deepak1556** [comment] 2024-10-17 23:40
/fixedWith https://github.com/microsoft/vscode/commit/8addf834f8b205756d0c7bd88a6bec3c1927523d

**Closed by deepak1556** 2024-10-17 23:40 UTC

**Comment by TylerLeonhardt** [comment] 2024-10-24 18:06
Hello! Can you give this a try with the [Insiders](http://code.visualstudio.com/insiders/) build and let us know if the issue is fixed?

**Comment by joshspicer** [comment] 2024-10-25 23:16
I'm now seeing the desired behavior in my local environment (see the before and after below).

Please let us know if repro steps if you're seeing otherwise, thanks!

![Image](https://github.com/user-attachments/assets/835f2ceb-36ee-462f-b3d2-a23909b6cd8a)
![Image](https://github.com/user-attachments/assets/5027e769-9da5-44c2-bc5a-a608e4835bb4)
