### ISSUE TITLE
Poor coloring of JS inside HTML in light theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12872] opened 2016-09-28 09:05 UTC
The light theme colors strings in the same value as keywords:

![image](https://cloud.githubusercontent.com/assets/900690/18907314/7e884760-856b-11e6-97c0-aa6a1c04ba9e.png)

Compared to dark theme:

![image](https://cloud.githubusercontent.com/assets/900690/18907327/889f2444-856b-11e6-8e67-bff12d519a44.png)

**Comment by aeschli** [comment] 2016-10-18 16:02
HTML strings are blue in the light theme (not sure why, but it's what the VS light theme always has done). Due to our flatting of scopes (bug #3008) the string.html color now wins against the normal string color.
Closing as duplicate of #3008

**Closed by aeschli** 2016-10-18 16:02 UTC
Labels: bug
