### ISSUE TITLE
Error ...Microsoft VS Code/resources/app/extensions/jrieken.vscode-omnisharp: Cannot read file package.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3970] opened 2016-03-10 16:52 UTC
The error in the title shows up after the users updated to 0.10.10.

I suspect that the extension could not be fully removed during the update since the OmniSharp server was running.

**Comment by joaomoreno** [comment] 2016-03-10 16:59
Duplicate of #1605

**Closed** 2016-03-10 16:59 UTC
Labels: install-update

**Comment by jrieken** [comment] 2016-03-11 07:45
@joaomoreno Are you sure that's a dupe? More folks seem to run into this with the 10.10 update and it seems our extension delete story is broken

**Comment by joaomoreno** [comment] 2016-03-11 08:36
This has nothing to do with the *extension delete story*. This is the update through Inno Setup. It's a bundled extension, not a user installed one.

On update, Inno Setup makes sure Code is shutdown. Code makes sure the renderers and main processes are shut down. The renderers make sure the extension hosts are shut down. The extension hosts call `deactivate` on the extensions. Apparently, Omnisharp fails to respect that and keeps something running long after Code is shutdown. Inno Seutp fails to remove the directory and moves on.

**Comment by jrieken** [comment] 2016-03-11 10:04
maybe we aren't waiting long enough ;-) since this seems to be reality should we be less strict wrt empty folders in the ext-folder?

**Comment by joaomoreno** [comment] 2016-03-11 10:26
Absolutely. All in for that.
