### ISSUE TITLE
html.format.wrapLineLength does not work as expected

### ISSUE THREAD

**Issue by scandinave** [Microsoft/vscode#32189] opened 2017-08-09 13:53 UTC
- VSCode Version: 1.14.2
- OS Version: Debian 8.8
Hi,
html.format.wrapLineLength is defined to 120 characters by default. But it does not count the whitespace at the start of line (indentation).

The result is Sonar that tell me that i don't respect coding rule.  For me it's an incorrect implementation of the max line  length feature. 

Cordially

**Comment by aeschli** [comment] 2017-08-16 07:15
duplicate of https://github.com/beautify-web/js-beautify/issues/1223

**Closed by aeschli** 2017-08-16 07:15 UTC
Labels: editor
