### ISSUE TITLE
Extra comma added when importing missing item

### ISSUE THREAD

**Issue by LukaszGrela** [microsoft/vscode#106735] opened 2020-09-15 08:04 UTC
Issue Type: <b>Bug</b>

With all extensions disabled I tried to add missing import and this works however it adds extra comma breaking the import statement.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by LukaszGrela** [comment] 2020-09-15 08:05
I mentioned that extensions are disabled... update vscodebot to check the `Extensions: none` :)

**Comment by aeschli** [comment] 2020-09-15 08:49
This is with TypeScript?

**Comment by mjbvz** [comment] 2020-09-15 17:25
The bot was correct. This is a duplicate of #105214 (https://github.com/microsoft/TypeScript/issues/40561)

**Closed by mjbvz** 2020-09-15 17:25 UTC

**Comment by tonix-tuft** [comment] 2020-09-19 09:28
I am facing this issue in JS files (no TypeScript).
