### ISSUE TITLE
Small problems in use

### ISSUE THREAD

**Issue by chenxiongbo111** [microsoft/vscode#117547] opened 2021-02-24 06:49 UTC
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

Issue Type: <b>Bug</b>

When using the terminal to submit code from the command line, GIT commit - M "prompt description" adds a description. Sogou input method (as well as ordinary input method) can't print Chinese characters, so switch to Microsoft input method. In the case of Chinese, punctuation and numbers are double

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.01GB free)|
|Process Argv|--crash-reporter-id 31d684b0-0b6c-41e3-a29b-9ecb2e386168|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
cssrem|cip|2.2.0
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.14
jquerysnippets|don|0.0.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.16
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.196
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
path-autocomplete|ion|1.17.1
vue|jcb|0.1.5
vscode-gutter-preview|kis|0.26.2
vscode-language-pack-zh-hans|MS-|1.53.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
vscode-react-native|msj|1.4.0
vetur|oct|0.32.0
nested-comments|phi|2.3.1
vscode-css-peek|pra|4.1.0
view-in-browser|qin|0.0.5
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|0.4.1
vscode-javascript-booster|sbu|14.0.1
background|sha|1.1.26
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.1.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by yume-chan** [comment] 2021-02-24 08:18
Duplicate of #115814

**Closed** 2021-02-24 17:52 UTC
Labels: *duplicate, *english-please, needs more info, translation-required-chinese-simplified
