### ISSUE TITLE
Duplication when typing Chinese Punctuation

### ISSUE THREAD

**Issue by begforname** [microsoft/vscode#157495] opened 2022-08-08 09:55 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS: Win 11

Steps to Reproduce:
I dont know whether it is a bug but cant figure it out. When typing Chinese punctuation like commas or periods, it will replace the present character and show twice, e.g. if typing a Chinese period after "...end", it will show “...en。。”. Thanks for any help in advance.

Screenshots (type a Chinese period):
![动画](https://user-images.githubusercontent.com/42715866/183639329-e56dc01e-9847-4701-a7ec-00b2125345c2.gif)

**Comment by alexdima** [comment] 2022-08-09 07:39
@begforname What OS are you using? Can you please also capture a screen recording?

**Comment by begforname** [comment] 2022-08-09 11:54
> @begforname What OS are you using? Can you please also capture a screen recording?

Win 11. Screenshots uploaded. And I have tried to disable my extensions one by one but no difference.

**Comment by aiday-mar** [comment] 2024-09-09 11:35
Verified that this does not happen with the setting `editor.experimentalEditContextEnabled` on Windows. This issue will be closed.

**Comment by ParadoxV5** [comment] 2024-10-03 19:56
I turned on `editor.experimentalEditContextEnabled`.
The “replace the present character” is fixed but “show twice” is still a bug.
E.g., typing a `。` after `...end`, now becomes `...end。。`.

* VS Code Version: Version: 1.94.0 (d78a74bcdf)
* OS: Win 11 (`Windows_NT x64 10.0.22635`)

**Comment by ParadoxV5** [comment] 2024-10-06 21:39
Update: it now swallows the character to the right.
E.g., typing a `“` before `begin...` now becomes `““egin...`

**Comment by aiday-mar** [comment] 2024-10-08 07:34
Hi I am testing on Windows and am not able to reproduce the problem. I am using Microsoft Chinese Pinyin to do this. Can I ask you where you are testing? On a browser or on desktop? Could I ask you to include a screen recording of this issue?

https://github.com/user-attachments/assets/e508a713-0bba-451e-b4b3-87c78ebb15af

**Comment by ParadoxV5** [comment] 2024-10-09 02:57
Hey @aiday-mar,

I tested again by disabling extensions and found that it seems to be caused by [Overtype](https://marketplace.visualstudio.com/items?itemName=DrMerfy.overtype) (#1012) or its presence.

Sorry about the confusion and thank you for your investigation.
(I’m on desktop too, for the matter)

**Comment by aiday-mar** [comment] 2024-10-09 07:09
Hi thanks for letting me know. I will close this issue then.

**Closed by aiday-mar** 2024-10-09 07:09 UTC
Labels: bug, windows, editor-input-IME, editor-edit-context

**Comment by ParadoxV5** [comment] 2024-10-09 19:12
* DrMerfy/vscode-overtype#19
