### ISSUE TITLE
Undoing git checkout

### ISSUE THREAD

**Issue by vojtatranta** [Microsoft/vscode#10679] opened 2016-08-18 21:44 UTC
This is an improvement I think:

I am used to from other editors that if I checkout some unstaged changes I don't loose that in fact. Because I can always undo them in my editor.

But with VS Code - event though I really like it - it is impossible. Because when I do `git checkout change-i-don-want.md` suddenly VS code forgets that there were some changes and "undo" (or `ctrl+Z`) is not impossible - changes are simply gone.

That is not a big deal but still - my editor should prevent me from doing mistakes and this is one very likely to happen.

**Comment by joaomoreno** [comment] 2016-08-19 07:30
Can you show me which other editors do this?

**Comment by vojtatranta** [comment] 2016-08-19 08:17
@joaomoreno well I have Atom (nuclide) and Sublime installed and both do this.

Because it seems as default behaviour that this just works. It is quite normal that an editor holds the state of a file in the memory and notifies when actual file is different from the state stored in memory.

I just want to be able to get back previously checkouted unstaged changes in VS Code.

**Comment by joaomoreno** [comment] 2016-08-19 13:30
Got it. Duplicate of #2908

**Closed by joaomoreno** 2016-08-19 13:30 UTC
Labels: needs more info
