### ISSUE TITLE
storageService not registered on launch VS Code in WSL

### ISSUE THREAD

**Issue by mycroft16** [microsoft/vscode#77744] opened 2019-07-22 09:35 UTC
- VSCode Version: 1.34.0
- OS Version: Ubuntu 18.04.2 LTS (WSL)

Steps to Reproduce:

1. Navigate to any project folder within WSL Ubuntu environment.
2. Launch code-insiders . with or without extensions

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Expected Result:
VS Code to launch normally and open my project

Actual Result:
/mnt/c/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: 37: /mnt/c/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: [createInstance] extensionManagementService depends on storageService which is NOT registered.
c:/Users/<user>/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslCode.sh: not found

**Comment by mjbvz** [comment] 2019-07-22 18:14
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

/needsMoreInfo

**Comment by bmisiak** [comment] 2019-07-22 20:23
Latest insiders build.
```Version: 1.37.0-insider (user setup)
Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
Date: 2019-07-22T07:16:47.743Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18932
```

```
[2019-07-22 20:21:11.291] Starting VS Code Server inside WSL (Ubuntu)
[2019-07-22 20:21:11.292] Extension version: 0.39.0, Windows build: 18932. Multi distro support: enabled. WSL path support: enabled
[2019-07-22 20:21:11.534] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server-insiders/bin/81ed55af79f01e9e64c3438558d2c2233e382a5a ] && echo found || echo missing"
[2019-07-22 20:21:11.703] No server install found on WSL, downloading server on client side: C:\Users\bmisi\AppData\Local\Temp\vscode-remote-wsl\81ed55af79f01e9e64c3438558d2c2233e382a5a\vscode-server-linux-x64.tar.gz
[2019-07-22 20:21:29.492] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "\"$(wslpath -u 'c:/Users/bmisi/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.0/scripts/wslServer.sh')\" '81ed55af79f01e9e64c3438558d2c2233e382a5a' 'insider' '.vscode-server-insiders' 'C:/Users/bmisi/AppData/Local/Temp/vscode-remote-wsl/81ed55af79f01e9e64c3438558d2c2233e382a5a/vscode-server-linux-x64.tar.gz' 0  " in c:\Users\bmisi\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0
[2019-07-22 20:21:29.842] WSL version: 4.19.43-microsoft-standard Ubuntu
[2019-07-22 20:21:29.842] Updating server...
[2019-07-22 20:21:29.842] Updating VS Code Server to version 81ed55af79f01e9e64c3438558d2c2233e382a5a
[2019-07-22 20:21:29.842] Removing previous installation...
[2019-07-22 20:21:29.842] 100%
[2019-07-22 20:21:29.842] Unpacking:   0%
[2019-07-22 20:21:32.2 27%
[2019-07-22 20:21:32.5 65%
[2019-07-22 20:21:33.7 66%
[2019-07-22 20:21:34.0 69%
[2019-07-22 20:21:34.3 99%
[2019-07-22 20:21:34.6100%
[2019-07-22 20:21:34.650] Starting server: /home/bm/.vscode-server-insiders/bin/81ed55af79f01e9e64c3438558d2c2233e382a5a/server.sh  --port=0 --enable-remote-auto-shutdown 
[2019-07-22 20:21:34.951] 
[2019-07-22 20:21:34.951] 
[2019-07-22 20:21:34.951] *
[2019-07-22 20:21:34.951] * Visual Studio Code Server
[2019-07-22 20:21:34.951] *
[2019-07-22 20:21:34.951] * Reminder: You may only use this software with Visual Studio family products,
[2019-07-22 20:21:34.951] * as described in the license https://aka.ms/vscode-remote/license
[2019-07-22 20:21:34.951] *
[2019-07-22 20:21:34.951] 
[2019-07-22 20:21:34.951] 
[2019-07-22 20:21:34.951] IP Address: 172.20.186.182
[2019-07-22 20:21:34.951] webview server listening on 46741
[2019-07-22 20:21:34.951] Extension host agent listening on 33079
[2019-07-22 20:21:34.965] WSL resolver response: 172.20.186.182:33079
[2019-07-22 20:21:34.965] [createInstance] extensionManagementService depends on storageService which is NOT registered.
```

**Comment by rosstex** [comment] 2019-07-23 02:00
Also ran into this issue.

**Comment by peshence** [comment] 2019-07-23 10:32
Also have this issue, but weirdly able to access stuff if I run VSCode-Insiders from the windows side

**Comment by ilaskaev** [comment] 2019-07-23 12:44
Started running into this issue as well once I updated my insider build, haven't done so in a few weeks.

```
Version: 1.37.0-insider (system setup)
Commit: e1d3dd53d17fb1529a002e4d6fb066db0a0bd385
Date: 2019-07-23T05:23:48.960Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

```
❯ code-insiders .
/c/Program Files/Microsoft VS Code Insiders/bin/code-insiders: 37: /c/Program Files/Microsoft VS Code Insiders/bin/code-insiders: [createInstance] extensionManagementService depends on storageService which is NOT registered./scripts/wslCode.sh: not found
```

**Comment by funkfreakout** [comment] 2019-07-23 14:55
@ilaskaev make sure you have the `remove development` extension installed (at least WSL functionalities which I think is currently in version `0.39.0`). You can do that running `code-insiders --locate-extension ms-vscode-remote.remote-wsl` on the shell. So you will have something like this as a the response: 
```
[createInstance] extensionManagementService depends on storageService which is NOT registered.
c:\Users\<USERNAME>\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.39.0
```
As you can see the first line is the error string which is loading when calling the command.

I know it is not the best solution but while waiting for the new release (in which I hope this problem is solved), just change the line on the code-insiders bash file so you just take the last line of the response.

In the file (located in your case in `\C:\Program Files\Microsoft VS Code Insiders\bin\code-insiders` I guess) change the line (in my case line 36) `WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID)` for `WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID | tail -1)` 

That should work as an temporary solution. I hope it works for you. 

Btw, this [issue](https://github.com/microsoft/vscode-remote-release/issues/1006) did help me a lot.

**Comment by ilaskaev** [comment] 2019-07-23 15:18
@funkfreakout Thanks, that helped, however in the process I also discovered another problem I had. Since last update, for whatever reason, the wsl extension got removed for me. I also had to reinstall it.

**Comment by aeschli** [comment] 2019-07-23 16:18
fixed by https://github.com/microsoft/vscode-remote-release/issues/1012

**Closed by aeschli** 2019-07-23 16:18 UTC

**Comment by wbuck** [comment] 2019-07-24 01:07
Was the fix for this issue released? I just ran into this issue tonight
