### ISSUE TITLE
File icon theme not working after update

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23620] opened 2017-03-29 20:44 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|EditorConfig|EditorConfig|0.6.2|
|git-project-manager|felipecaputo|1.2.1|
|seti-icons|qinjia|0.1.3|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.0.5|;

---

Updated to today's insiders and saw this:

![image](https://cloud.githubusercontent.com/assets/2193314/24475645/6b4839cc-1485-11e7-80da-11a7d57872da.png)

Error in console:

```
GET file:///C:/Users%C3%9Aimms.vscode-insiders%0Extensionsqinjia.seti-icons-0.1.3%0Fontsseti.woff net::ERR_FILE_NOT_FOUND
```

Actual path of woff file:

```
C:\Users\daimms\.vscode-insiders\extensions\qinjia.seti-icons-0.1.3\fonts\seti.woff
```

Reloading the window and restarting VS Code did not fix the issue.

**Comment by doublehelix** [comment] 2017-03-29 21:15
Confirmed...
The console error is `net::ERR_FILE_NOT_FOUND`
All references to icons (for ALL icon packs not just the one in the screenshot) seem to be missing the directory separator between folder names...

![2017-03-30](https://cloud.githubusercontent.com/assets/355130/24476911/d878126a-1520-11e7-8db0-4f0c214df219.png)

**Comment by Tyriar** [comment] 2017-03-29 21:21
@doublehelix thanks for chiming in, marked as important as someone else is seeing it

**Comment by doublehelix** [comment] 2017-03-29 21:30
Hey @Tyriar - Sorry I just realised I duplicated a lot of info there.
I was working on a fix as well in the hope to provide a PR. Will leave it assigned to Martin
Thanks.

**Comment by alvarollmenezes** [comment] 2017-03-29 21:35
Same. It is happening since yesterdays or the day before update I guess.

**Comment by wassim-azirar** [comment] 2017-03-29 22:04
I'm having the same error after update
![vscode](https://cloud.githubusercontent.com/assets/670586/24478771/6dfc42f6-14dc-11e7-982d-5a183cd23352.PNG)

**Comment by cleidigh** [comment] 2017-03-29 22:08
yup
Windows 7
same problem, all file icons...

**Comment by mehran-mousavi** [comment] 2017-03-29 22:25
Me too. I have same problem. 

Windows 10 Enterprise

Version 1.11.0-insider
Commit d98a518c5485bd7a47c70f5b3783f70efa5edcd6
Date 2017-03-29T06:11:14.271Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by zheung** [comment] 2017-03-30 00:50
global search bar have a ui problem when option is enable too...
![3](https://cloud.githubusercontent.com/assets/894004/24482675/c5e56562-1525-11e7-956d-fe713d4ff762.gif)

**Comment by aeschli** [comment] 2017-03-30 08:09
duplicate of #23346

**Closed by aeschli** 2017-03-30 08:09 UTC
Labels: bug, important
