### ISSUE TITLE
Display issues. White dots/blur

### ISSUE THREAD

**Issue by estebanrinconmora** [microsoft/vscode#123950] opened 2021-05-15 14:00 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Using multiple monitors, open VSCode full screen
2. Place mouse in other monitor and interact with other apps
3. White blurs and dots appear all over VSCode UI
![vscode-ui-blur](https://user-images.githubusercontent.com/47949246/118363993-5570b300-b55c-11eb-9ed4-b6c666add915.PNG)

![vscode-ui-blur2](https://user-images.githubusercontent.com/47949246/118364071-923caa00-b55c-11eb-9421-ab561077a7b6.PNG)

**Comment by IllusionMH** [comment] 2021-05-15 20:35
/duplicate of #92379 which is some upstream issue

Should work with `--disable-gpu` flag or more permanent disable https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration 

Also check https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 look like Nvidia drivers may also affect rendering of Electron apps, however looks like it doesn't help in your case.

**Closed** 2021-05-15 20:36 UTC
Labels: *duplicate, new release
