### ISSUE TITLE
Workspace extension is activated when debugging as UI extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#130450] opened 2021-08-10 00:36 UTC
cc @osortega

- Debug the Codespaces extension in vscode desktop
- Create a codespace
- Set a breakpoint in an extension command
- Run the command, it runs but the breakpoint is not hit

The problem is that extension is installed on the workspace (maybe settings sync?) and we activate the workspace extension when we are debugging the UI extension. It's ok that the extension is installed on the workspace, we should just not be activating it when debugging the UI version.

Also it sounds like this only happens when the workspace is first created. So maybe the extension is only activated when it is first installed but correctly not activated if it's already installed.

Here's logs showing the extension being activated in both EHs.

Local EH log
```
...
[2021-08-09 17:30:06.282] [exthost] [info] ExtensionService#_doActivateExtension GitHub.codespaces {"startup":false,"extensionId":{"value":"GitHub.codespaces","_lower":"github.codespaces"},"activationEvent":"onView:github.codespaces.explorer"}
[2021-08-09 17:30:06.282] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/osvaldortega/Documents/Projects/Cascade/vscode/codespaces/debug/src/extension.js
...
```

Remote EH log
```
[2021-08-10 00:30:52.204] [exthost] [info] extension host started
[2021-08-10 00:30:52.211] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/bb203183c0f48df020660d510c6ece02/vscode.lock': Lock acquired.
[2021-08-10 00:30:52.468] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-08-10 00:30:52.468] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/debug-auto-launch/dist/extension
[2021-08-10 00:30:52.472] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-10 00:30:52.472] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/git/dist/main
[2021-08-10 00:30:52.544] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github {"startup":true,"extensionId":{"value":"GitHub.vscode-pull-request-github","_lower":"github.vscode-pull-request-github"},"activationEvent":"*"}
[2021-08-10 00:30:52.544] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/codespace/.vscode-remote/extensions/github.vscode-pull-request-github-0.29.0/dist/extension
[2021-08-10 00:30:52.600] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":true,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"workspaceContains:package.json"}
[2021-08-10 00:30:52.600] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/npm/dist/npmMain
[2021-08-10 00:30:52.920] [exthost] [info] ExtensionService#_doActivateExtension GitHub.codespaces {"startup":false,"extensionId":{"value":"GitHub.codespaces","_lower":"github.codespaces"},"activationEvent":"*"}
[2021-08-10 00:30:52.921] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/codespace/.vscode-remote/extensions/github.codespaces-0.11.3/out/bundle/extension-node.js
[2021-08-10 00:30:53.716] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-10 00:30:53.716] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/github/dist/extension.js
[2021-08-10 00:30:54.299] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-08-10 00:30:54.299] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/ms-vscode.js-debug/src/extension.js
[2021-08-10 00:30:54.676] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-08-10 00:30:54.676] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/emmet/dist/node/emmetNodeMain
[2021-08-10 00:30:54.690] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-08-10 00:30:54.690] [exthost] [info] ExtensionService#loadCommonJSModule file:///vscode/bin/x64/379476f0e13988d90fab105c5c19e7abc8b1dea8/extensions/merge-conflict/dist/mergeConflictMain
[2021-08-10 00:30:54.694] [exthost] [info] eager extensions activated
[2021-08-10 00:30:55.753] [exthost] [warning] [GitHub.vscode-pull-request-github] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'githubIssues.queries', provide the URI of a resource or 'null' for any resource.
```

**Comment by osortega** [comment] 2021-08-10 19:40
Note that this is not only happening when debugging the UI version. It also happens on the normal flow of the extension.
When you create a new codespace, the workspace extension seem to interfere with the UI extension.

**Comment by osortega** [comment] 2021-08-16 17:46
@sandy081 is there any update on this issue?
This is causing every first activation of the extension to be broken when connecting through VS Code desktop.

cc @jkeech

**Comment by osortega** [comment] 2021-08-16 18:06
I tried it out this morning and seems to be fixed now.
If this was a known issue could we have a link to the fix to have a reference? 

Closing this issue.

**Comment by sandy081** [comment] 2021-08-20 09:56
Assigning @alexdima as it is related to extension activation.

**Comment by alexdima** [comment] 2021-08-20 21:10
What was the `extensionKind` of `GitHub.codespaces` when this was reproducible 11 days ago?

**Comment by jkeech** [comment] 2021-08-20 21:12
> What was the `extensionKind` of `GitHub.codespaces` when this was reproducible 11 days ago?

```
"extensionKind": [
		"ui",
		"workspace",
		"web"
	],
```

The extension kind has not changed in the past month.

**Comment by alexdima** [comment] 2021-09-27 20:04
> Also it sounds like this only happens when the workspace is first created. So maybe the extension is only activated when it is first installed but correctly not activated if it's already installed.

Reading this issue again, I think this is a duplicate of https://github.com/microsoft/vscode/issues/133434 . 

When I initially read this issue, I believed the problem is limited to debugging the Codespace extension (we pass in special arguments to VS Code and I believed those might have some problems), but it looks like there was a bug in the extension installation event handling code, where the Codespace would be always activated on the remote side after a new codespace was created. So debugging had nothing to do with it.

**Closed by alexdima** 2021-09-27 20:04 UTC
Labels: needs more info
