### ISSUE TITLE
Graphical Artifacts

### ISSUE THREAD

**Issue by JeffreyGarand** [microsoft/vscode#107260] opened 2020-09-22 21:31 UTC
Issue Type: <b>Bug</b>

Graphical artifacts appearing in the 'Terminal' (Gray to White squares).  Compiling Angular app. First appeared after most recent update.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:38.048Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3306)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
tslint|eg2|1.0.44
ftp-simple|hum|0.7.5
swift|Kas|0.2.0
python|ms-|2020.8.109390
debugger-for-chrome|msj|4.12.10
python|tht|0.2.3
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

![image](https://user-images.githubusercontent.com/46425145/93939829-70569480-fcf9-11ea-9ed2-b3661319f152.png)

**Comment by IllusionMH** [comment] 2020-09-22 22:00
/needsMoreInfo

Looks like duplicate of #106981
Do you have `window.zoomLevel` in settings? Do you have `terminal.integrated.rendererType` in settings?

/assign @Tyriar

**Closed** 2020-09-23 22:04 UTC
Labels: *duplicate, needs more info
