### ISSUE TITLE
The terminal IME composition view appears on top of text sometimes and keeps moving while typing

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11334] opened 2016-08-31 18:20 UTC
- VSCode Version: 1.5.0-Insiders
- OS Version: OSX

Steps to Reproduce:
1. Open Integrated Terminal
2. Switch to OSX's default Chinese IME
3. Type `nihao` and see the behavior.

![imeinterminal](https://cloud.githubusercontent.com/assets/876920/18140666/6009afec-6f6b-11e6-9683-7ffc956e97d2.gif)

Found this issue while verifying #9822.

**Comment by Tyriar** [comment] 2016-09-01 20:36
A fix to this will probably be too high risk due to the module refactor in xterm.js. Deferring to September since it's just a bit glitchy but should still work.

**Comment by Tyriar** [comment] 2016-09-17 07:59
Fixing this related upstream issue may fix this https://github.com/sourcelair/xterm.js/issues/273

**Comment by Tyriar** [comment] 2016-10-22 23:31
PR for this is out for upstream, if it isn't merged in time I can always cherry pick to the release branch on my fork https://github.com/sourcelair/xterm.js/pull/320

**Comment by Tyriar** [comment] 2016-10-23 02:35
I believe this will be fixed by the fix in https://github.com/Microsoft/vscode/issues/13229, not yet confirmed though.

**Comment by Tyriar** [comment] 2016-10-23 14:29
@rebornix this may be fixed, please verify. If not I'll need to learn how to use your IME :stuck_out_tongue:

**Comment by rebornix** [comment] 2016-10-24 16:24
@Tyriar since the `xterm-helper-textarea` is positioned as `absolute` and seems right now we only generate `left` for it, the `top` value is always `0`.

**Comment by Tyriar** [comment] 2016-10-24 18:27
PR is out upstream

**Comment by Tyriar** [comment] 2016-10-25 04:33
The commit broke the build and was reverted, waiting until code freeze is finished to add it back.

**Comment by jrieken** [comment] 2016-10-28 08:19
Assuming *Chinese IME* is *Pinyin Simplified* I cannot get this to work. These are my steps

* OS X, select Pinyin Simplified keyboard
* in editor type `ni`, select first suggestion
* in terminal type `ni`, select first suggestion, 🐛 it prompts to show all completions instead of inserting the character

![oct-28-2016 10-16-55](https://cloud.githubusercontent.com/assets/1794099/19799640/036dae40-9cf8-11e6-89da-3e9d7ec89286.gif)

**Comment by bpasero** [comment] 2016-10-28 09:24
Since this is not labeled important, moving out to November.

**Comment by Tyriar** [comment] 2016-10-28 14:38
@rebornix can you double check this?

**Comment by rebornix** [comment] 2016-10-29 05:59
I don't run into the issue @jrieken had, but when I typed first character, like `n`, the composition view is missing but after I typed `i`, the composition view is shown.

**Comment by Tyriar** [comment] 2016-10-29 12:09
Are you pressing tab to trigger the completion @jrieken?

**Comment by jrieken** [comment] 2016-10-31 08:14
No. I press `1` to select the suggestion. The suggestion show up as I type

**Comment by Tyriar** [comment] 2017-04-20 21:13
@rebornix can you still repro this on Mac?

**Comment by rebornix** [comment] 2017-04-20 22:05
I can still reproduce this problem.

**Comment by Tyriar** [comment] 2017-12-22 02:22
I can't see the original problem anymore but I do see the related https://github.com/xtermjs/xterm.js/issues/273 still which is tracked over there.

**Closed by Tyriar** 2017-12-22 02:22 UTC
Labels: bug, integrated-terminal, upstream
