### ISSUE TITLE
VSCode Typescript Intellisense slows to crawl after 5-10 minutes

### ISSUE THREAD

**Issue by philjones88** [Microsoft/vscode#18774] opened 2017-01-19 09:47 UTC
- VSCode Version: Insiders Version 1.9.0-insider (1.9.0-insider) 39d761bf1f4ce7ea605539bdba41a8727b3c7ce0
- OS Version: macOS Sierra 10.12.2 (16C67) (2013 rMBP, i7, 16GB RAM, 1TB SSD)

Steps to Reproduce:

1. Open large Angular (2.4.3) project and after a while (5-10 minutes) intellisense slows down to a crawl taking 5-15 seconds to generate. If you force it (ctrl + space?), it'll sit for a while with "Loading..."

Disabled most addons, only have:

* Angular VS Code TypeScript and HTML Snippets
* Angular Language Service (installed after this started happening)
* Auto-Open Markdown Preview
* Bootstrap 3 Snippets

Enabled.

I disabled other addons such as C#/Ionide-fsharp/etc.

**Comment by philjones88** [comment] 2017-01-25 18:02
I figured out it was because I was opening the whole of our product's code base folder, which includes C# .NET Core/CoreCLR projects etc.

If I open just the Angular 2 sub folder performance is better, however I still notice that VS Code's background processes (`Code - Insiders Helper`) can sometimes get stuck and eat up CPU causing my MBP's fan to spin up. I force quit them and it's fine.

**Comment by steelsojka** [comment] 2017-02-07 13:18
I have noticed this on a large Angular project. 1.8 was lightning fast with intellisense. 1.9 is taking about 6-10 seconds for just simple autocomplete. It's becoming almost unusable. I can provide any information needed to help resolve this issue.

**Comment by artaommahe** [comment] 2017-02-08 17:56
> I have noticed this on a large Angular project. 1.8 was lightning fast with intellisense. 1.9 is taking about 6-10 seconds for just simple autocomplete

Same here. 1.9 looks very slow, waiting for simple `import` statement autocomplete from 3 to 10 seconds

**Comment by mjbvz** [comment] 2017-02-08 23:31
VSCode 1.9 upgraded the bundled TypeScript version for 2.1.4 to 2.1.5. Perhaps there was a performance regression.

If you are seeing this problem in 1.9, please provide the following information to help us investigate:

* Are you using a custom `typescript.tsdk` setting? If you are, which version of TypeScript are you using?
* Do you have a `jsconfig/tsconfig` file and what does it look like?
* If you can share your project, that would be even more helpful. If not, can you provide a general description of it?

**Collect TSServer Traces**
1. Add the user setting: `"typescript.tsserver.trace": "verbose"`
1. Restart VSCode
1. Reproduce the problem.
1. Go to the output pane and paste up the output from the `TypeScript` section.

**Collect TSServer Logs**
If you're feeling up to it, this log would be very helpful as well

1. Exit VSCode
1. Set the [`TSS_LOG` log environment variable](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging)
   * For bash of Mac for example, `$export TSS_LOG="-level verbose -file /Users/${username-`whoami`}/tss.log"
1. Start VS Code from an environment with `TSS_LOG` set, by running `$ code` for example
1. Reproduce the problem
1. Share the `tss.log` file

Both the TypeScript trace and TSS_LOG files may contain the contents of source files and full path names.



You can also try downgrading to TypeScript 2.1.4 by [following these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

Thanks

**Comment by artaommahe** [comment] 2017-02-10 14:23
@mjbvz

> downgrading to TypeScript 2.1.4

Does not help.

> Collect TSServer Traces

Enabled tracing, opened vscode, wrote
```ts
import {  } from 'page-module/core/module';
```
pressed `Ctrl + Space` in brakets to autocomplete import, `page-module/core/module` has only one exported variable (with ~20 imports)

http://pastebin.com/5PN9Amyw
```sh
$ cat log | grep "Request took"
```
http://pastebin.com/xh8tjYW2
A lot of 10-30s requests

> Collect TSServer Logs

cant find how to set up logging, this does not create log file or write anything to created one
```sh
$ TSS_LOG="-level verbose -file /home/drow/temp/vscode-slow-issue/tsserver.log"
$ code
```

> Are you using a custom typescript.tsdk setting? If you are, which version of TypeScript are you using?

nope

> Do you have a jsconfig/tsconfig file and what does it look like?

http://pastebin.com/ZdwtEaSL
> If you can share your project, that would be even more helpful. If not, can you provide a general description of it?

cant share, ~60k loc angular 2 app, one tsconfig

Ubtuntu 16.04, VSCode Version 1.9.1

**Comment by mjbvz** [comment] 2017-02-22 00:59
Thanks. I believe this is a duplicate of #20815. TypeScript has a fix on their side and I also just checked in a fix on the VSCode side. Try out tonight's insiders build and let me know if you still see this

**Closed by mjbvz** 2017-02-22 00:59 UTC
Labels: duplicate, perf, typescript

**Comment by artaommahe** [comment] 2017-02-23 16:26
@mjbvz last insiders build works well, like 1.8, thx )
