### ISSUE TITLE
Removal of the Santa hat and kowtowing to a single fake user is offensive to me

### ISSUE THREAD

**Issue by JohnMH** [microsoft/vscode#87328] opened 2019-12-19 09:12 UTC
The removal of the santa hat, and kowtowing to a fake user, is incredibly offensive to me. Please reinstate the santa hat icon.

**Comment by MaurogDark** [comment] 2019-12-19 09:28
...Dissenter detected
...Stifling discussion
...Summoning egamma
...Issue closed in 3... 2... 1...

**Comment by egamma** [comment] 2019-12-19 09:42
Duplicate of #87291 pls see https://github.com/microsoft/vscode/issues/87291#issuecomment-567383802.

**Closed by egamma** 2019-12-19 09:42 UTC

**Comment by egamma** [comment] 2019-12-19 19:25
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
