### ISSUE TITLE
Peek Call Hierarchy Leaves Orphaned Popup

### ISSUE THREAD

**Issue by helsaawy** [microsoft/vscode#146255] opened 2022-03-29 14:44 UTC
Issue Type: <b>Bug</b>

When "Peek > Peek Call Hierarch" fails to find any callers, the pop-up/insert does not have any way to be closed, and is present across all tabs in the window.

When it first fails, it appears as so:
![issue](https://user-images.githubusercontent.com/84944216/160637967-73283f01-c955-4cc4-bafd-0eac8c235389.png)

But then stays present as a semi-transparent overlay across all files opened
![issue 2](https://user-images.githubusercontent.com/84944216/160637982-0b60aa18-7762-432e-a002-7fa484c15147.png)

"Developer: Reload Window" is currently the only way I can reset VS Code and remove it.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22581
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.59GB (40.56GB free)|
|Process Argv|--crash-reporter-id da3185c7-ddf9-4a2b-947d-aca61c60aade|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
better-toml|bun|0.3.2
gitlens|eam|12.0.5
vscode-great-icons|emm|2.1.84
go|gol|0.32.0
vscode-peacock|joh|4.0.1
vscode-dotnet-runtime|ms-|1.5.0
powershell|ms-|2021.12.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
rewrap|stk|1.16.3
code-spell-checker|str|2.1.9
vim|vsc|1.22.2
vscode-proto3|zxh|0.5.5

</details>

**Comment by jrieken** [comment] 2022-03-30 07:25
I cannot reproduce. What language and extension is this with? Do you see anything in DevTools error console? There should be a frame arround the peek window and that frame should have a `x` for closing it. Maybe there was an error that prevents the peek from properly being constructed

**Comment by jrieken** [comment] 2022-03-30 14:58
Best is to check dev tools console via F1 > Developer Tools > Console

**Comment by helsaawy** [comment] 2022-05-04 19:29
Hello,
The same issue arose again
The console log is:
```
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
D @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
D @ console.ts:137
log.ts:313   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
D @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
D @ console.ts:137
log.ts:313   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
D @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
D @ console.ts:137
log.ts:313   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
D @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
D @ console.ts:137
log.ts:313   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
log.ts:313   ERR Cannot read properties of undefined (reading 'size'): TypeError: Cannot read properties of undefined (reading 'size')
    at _e._cacheAndConvertItem (c:\Users\hamzaelsaawy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:121063)
    at c:\Users\hamzaelsaawy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:120546
    at Array.map (<anonymous>)
    at _e.provideCallsTo (c:\Users\hamzaelsaawy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:120526)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
log.ts:313   ERR no identifier found: Error: no identifier found
    at handleResponse (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4366:40)
    at processMessageQueue (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4204:13)
    at Immediate.<anonymous> (c:\Users\hamzaelsaawy\.vscode\extensions\golang.go-0.33.0\dist\goMain.js:4190:11)
    at processImmediate (node:internal/timers:464:21)
```
![orphan 1](https://user-images.githubusercontent.com/84944216/166811210-098cbb34-0a95-4da4-8c9f-12b70a6ceda9.png)

**Comment by jrieken** [comment] 2022-05-05 06:40
Thanks for the update. Likely rooted here: https://github.com/microsoft/vscode/blob/93fd393a0e200f3cc8038cef0e61b14a75fb1c21/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1665

**Comment by jrieken** [comment] 2022-07-04 14:50
I cannot reproduce with the assumed code place...

@helsaawy Do you still see this with latest VS Code?

**Comment by helsaawy** [comment] 2022-07-05 14:23
I have not seen it in a while, no
do you want me to close?

**Closed** 2022-07-05 14:31 UTC
Labels: needs more info, *not-reproducible, callhierarchy
