### ISSUE TITLE
Auto implements interface doesn't respect indentation settings

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#21723] opened 2017-03-02 08:39 UTC
- VSCode Version: 1.10.1
- OS Version: macOS

Steps to Reproduce:

1. `export class AppComponent implements OnInit {}`
2. Use the new tip to automatically implements interface methods.
3. Works, but doesn't respect the file indentation settings (it puts 4 spaces, while my file is configured with 2 spaces).

**Comment by mjbvz** [comment] 2017-03-03 23:11
I'm unable to reproduce this. In the status bar, it says `Spaces: 2`, correct?

Can you please share a complete example that demonstrates this problem

**Comment by cyrilletuzi** [comment] 2017-03-04 09:23
Yes, the status bar says "Spaces: 2" (it's Angular CLI project, configured with `.editorconfig` and the relevant extension, but I tried without the extension too, same problem).

My file is a very simple Angular file. I first have : 

```
import { Component, OnInit } from '@angular/core';

@Component({
  template: ``
})
export class AppComponent implements OnInit {}
```

Then I click on `AppComponent`, then on the the light bulb icon which appears on the left, then on "Implement interface OnInit", and it produces this : 

```
import { Component, OnInit } from '@angular/core';

@Component({
  template: ``
})
export class AppComponent implements OnInit {
    ngOnInit(): void {
      throw new Error('Method not implemented.');
    }
}
```

**Comment by mjbvz** [comment] 2017-03-06 23:06
To help us investigate:

* Add `"typescript.tsserver.trace": "verbose",` in your settings.
* Restart VSCode
* Reproduce the issue
* Go to `View -> output` and share the output from TypeScript

**Comment by cyrilletuzi** [comment] 2017-03-07 08:14
Here it is. Not sure that in the formatting part, it's normal to have both `identSize: 2` and `tabSize: 2`. My project is configured with 2 spaces, and I don't see anywhere in any settings something about tabs.

```
[Info  - 9:05:57 AM] Using tsserver from location: /path/to/project/node_modules/typescript/lib/tsserver.js
[Trace - 9:05:57 AM] Sending request: configure (0). Response expected: yes. Current queue length: 0
Arguments: {
    "hostInfo": "vscode"
}
[Trace - 9:05:58 AM] Response received: configure (0). Request took 357 ms. Success: true 
[Trace - 9:05:58 AM] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 4
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve"
    }
}
[Trace - 9:05:58 AM] Response received: compilerOptionsForInferredProjects (1). Request took 360 ms. Success: true 
Result: true
[Trace - 9:05:58 AM] Sending request: getSupportedCodeFixes (2). Response expected: yes. Current queue length: 3
[Trace - 9:05:58 AM] Response received: getSupportedCodeFixes (2). Request took 356 ms. Success: true 
Result: [
    "2304",
    "2339",
    "2377",
    "2420",
    "2503",
    "2515",
    "2653",
    "2663",
    "2686",
    "2689",
    "6133",
    "6138",
    "17009"
]
[Trace - 9:05:58 AM] Sending request: open (3). Response expected: no. Current queue length: 2
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "fileContent": "import { Component, OnInit } from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  template: `\n  <router-outlet></router-outlet>\n  `,\n  // styleUrls: ['./app.component.css']\n})\nexport class AppComponent implements OnInit {}\n",
    "scriptKindName": "TS"
}
[Trace - 9:05:58 AM] Sending request: getSupportedCodeFixes (4). Response expected: yes. Current queue length: 1
[Trace - 9:06:02 AM] Event received: configFileDiag (0).
Data: {
    "triggerFile": "/path/to/project/src/app/app.component.ts",
    "configFile": "/path/to/project/tsconfig.json",
    "diagnostics": []
}
[Trace - 9:06:02 AM] Response received: getSupportedCodeFixes (4). Request took 4618 ms. Success: true 
Result: [
    "2304",
    "2339",
    "2377",
    "2420",
    "2503",
    "2515",
    "2653",
    "2663",
    "2686",
    "2689",
    "6133",
    "6138",
    "17009"
]
[Trace - 9:06:02 AM] Sending request: geterr (5). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/path/to/project/src/app/app.component.ts"
    ]
}
[Trace - 9:06:02 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/path/to/project/src/app/app.component.ts",
    "diagnostics": []
}
[Trace - 9:06:04 AM] Event received: semanticDiag (0).
Data: {
    "file": "/path/to/project/src/app/app.component.ts",
    "diagnostics": [
        {
            "start": {
                "line": 16,
                "offset": 14
            },
            "end": {
                "line": 16,
                "offset": 26
            },
            "text": "Class 'AppComponent' incorrectly implements interface 'OnInit'.\n  Property 'ngOnInit' is missing in type 'AppComponent'.",
            "code": 2420
        }
    ]
}
[Trace - 9:06:04 AM] Event received: requestCompleted (0).
Data: {
    "request_seq": 5
}
[Trace - 9:06:05 AM] Sending request: quickinfo (6). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 21
}
[Trace - 9:06:05 AM] Response received: quickinfo (6). Request took 13 ms. Success: true 
Result: {
    "kind": "class",
    "kindModifiers": "export",
    "start": {
        "line": 16,
        "offset": 14
    },
    "end": {
        "line": 16,
        "offset": 26
    },
    "displayString": "class AppComponent",
    "documentation": ""
}
[Trace - 9:06:05 AM] Sending request: occurrences (7). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 21
}
[Trace - 9:06:05 AM] Response received: occurrences (7). Request took 11 ms. Success: true 
Result: [
    {
        "start": {
            "line": 16,
            "offset": 14
        },
        "end": {
            "line": 16,
            "offset": 26
        },
        "file": "/path/to/project/src/app/app.component.ts",
        "isWriteAccess": true
    }
]
[Trace - 9:06:05 AM] Sending request: getCodeFixes (8). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "startLine": 16,
    "endLine": 16,
    "startOffset": 14,
    "endOffset": 26,
    "errorCodes": [
        2420
    ]
}
[Trace - 9:06:05 AM] Response received: getCodeFixes (8). Request took 17 ms. Success: true 
Result: [
    {
        "description": "Implement interface 'OnInit'.",
        "changes": [
            {
                "fileName": "/path/to/project/src/app/app.component.ts",
                "textChanges": [
                    {
                        "start": {
                            "line": 16,
                            "offset": 46
                        },
                        "end": {
                            "line": 16,
                            "offset": 46
                        },
                        "newText": "ngOnInit(): void {\nthrow new Error('Method not implemented.');\n}\n"
                    }
                ]
            }
        ]
    }
]
[Trace - 9:06:08 AM] Sending request: change (9). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 46,
    "endLine": 16,
    "endOffset": 46,
    "insertString": "ngOnInit(): void {\nthrow new Error('Method not implemented.');\n}\n"
}
[Trace - 9:06:08 AM] Sending request: getCodeFixes (10). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "startLine": 16,
    "endLine": 16,
    "startOffset": 14,
    "endOffset": 26,
    "errorCodes": [
        2420
    ]
}
[Trace - 9:06:08 AM] Response received: getCodeFixes (10). Request took 82 ms. Success: true 
Result: []
[Trace - 9:06:08 AM] Sending request: configure (11). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "formatOptions": {
        "tabSize": 2,
        "indentSize": 2,
        "convertTabsToSpaces": true,
        "newLineCharacter": "\n",
        "insertSpaceAfterCommaDelimiter": true,
        "insertSpaceAfterSemicolonInForStatements": true,
        "insertSpaceBeforeAndAfterBinaryOperators": true,
        "insertSpaceAfterKeywordsInControlFlowStatements": true,
        "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
        "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
        "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
        "placeOpenBraceOnNewLineForFunctions": false,
        "placeOpenBraceOnNewLineForControlBlocks": false
    }
}
[Trace - 9:06:08 AM] Response received: configure (11). Request took 47 ms. Success: true 
[Trace - 9:06:08 AM] Sending request: format (12). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 1,
    "endLine": 20,
    "endOffset": 1
}
[Trace - 9:06:09 AM] Response received: format (12). Request took 60 ms. Success: true 
Result: [
    {
        "start": {
            "line": 16,
            "offset": 46
        },
        "end": {
            "line": 16,
            "offset": 46
        },
        "newText": "\n"
    },
    {
        "start": {
            "line": 16,
            "offset": 46
        },
        "end": {
            "line": 16,
            "offset": 46
        },
        "newText": "    "
    },
    {
        "start": {
            "line": 17,
            "offset": 1
        },
        "end": {
            "line": 17,
            "offset": 1
        },
        "newText": "      "
    },
    {
        "start": {
            "line": 18,
            "offset": 1
        },
        "end": {
            "line": 18,
            "offset": 1
        },
        "newText": "    "
    }
]
[Trace - 9:06:09 AM] Sending request: change (13). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 18,
    "offset": 1,
    "endLine": 18,
    "endOffset": 1,
    "insertString": "    "
}
[Trace - 9:06:09 AM] Sending request: change (14). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 17,
    "offset": 1,
    "endLine": 17,
    "endOffset": 1,
    "insertString": "      "
}
[Trace - 9:06:09 AM] Sending request: change (15). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 46,
    "endLine": 16,
    "endOffset": 46,
    "insertString": "    "
}
[Trace - 9:06:09 AM] Sending request: change (16). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "line": 16,
    "offset": 46,
    "endLine": 16,
    "endOffset": 46,
    "insertString": "\n"
}
[Trace - 9:06:09 AM] Sending request: getCodeFixes (17). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/path/to/project/src/app/app.component.ts",
    "startLine": 16,
    "endLine": 16,
    "startOffset": 14,
    "endOffset": 26,
    "errorCodes": [
        2420
    ]
}
[Trace - 9:06:09 AM] Response received: getCodeFixes (17). Request took 47 ms. Success: true 
Result: []
[Trace - 9:06:09 AM] Sending request: geterr (18). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/path/to/project/src/app/app.component.ts"
    ]
}
[Trace - 9:06:09 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/path/to/project/src/app/app.component.ts",
    "diagnostics": []
}
[Trace - 9:06:09 AM] Event received: semanticDiag (0).
Data: {
    "file": "/path/to/project/src/app/app.component.ts",
    "diagnostics": []
}
[Trace - 9:06:09 AM] Event received: requestCompleted (0).
Data: {
    "request_seq": 18
}
```

**Comment by mjbvz** [comment] 2017-03-08 02:01
@cyrilletuzi  Thank you for the traces. 

I believe that the issue is not with the quick fix itself, but with the TypeScript formatter. I can reproduce the same bug without using a quick fix, just by running format on a document. I've opened https://github.com/Microsoft/TypeScript/issues/14531 to track this formatting issue on the TypeScript side.

Closing as upstream

**Closed by mjbvz** 2017-03-08 02:01 UTC
Labels: format, typescript, upstream
