### ISSUE TITLE
CSHTML: script tags with type text/template no longer hightlight HTML syntax

### ISSUE THREAD

**Issue by JoshWhite** [Microsoft/vscode#26220] opened 2017-05-08 15:48 UTC
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. create .cshtml file
2. add script tag with type text/template
3. write HTML inside

EG:

```
<script id="myTemplate" type="text/template">
    <div>
        <ul>
            <li>my item</li>
        </ul>
    </div>
</script>
```
This was working until the most recent update...

**Comment by egamma** [comment] 2017-05-08 18:12
Duplicate of #25920 which we plan to fix in the next recovery build.

**Closed by egamma** 2017-05-08 18:12 UTC
Labels: duplicate
