### ISSUE TITLE
Display typescript information onClick in tooltip

### ISSUE THREAD

**Issue by KilianB** [microsoft/vscode#105569] opened 2020-08-28 09:29 UTC
As a developer I would like to be able to quickly inspect complex types.

![Tooltip](https://user-images.githubusercontent.com/9025925/91545348-37591900-e921-11ea-8cc8-114cf6cac6d8.png)

Right now there is no way to know how the shape of the Permission object looks like without interrupting the work flow and needing to jump to the definition file. 
From a user perspective the experience would be much more smooth if you the information could be presented to the user after a click on the name inside the tooltip window. Maybe either opening a second overlay tool tip or replace the content inside the tooltip and allow the user to navigate back to the original information.

Related to: https://github.com/microsoft/vscode/issues/6638 & https://github.com/microsoft/vscode/issues/94679 but instead of expanding the current information inspecting a single value would be fine. This has the advantage of not bloating the current display.

**Comment by mjbvz** [comment] 2020-08-28 18:41
Duplicate of #64566 (which also discusses hovers)

**Closed by mjbvz** 2020-08-28 18:41 UTC
