### ISSUE TITLE
JSDoc do not generate param for ES6 methods

### ISSUE THREAD

**Issue by zverx** [Microsoft/vscode#27729] opened 2017-05-31 11:19 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create ES6 methods for class
```
method = (num) => {
}
```
2. Enter over method /** and Tab

And see
```
/**
*
*/
```

without 
`* @param num`

**Comment by mjbvz** [comment] 2017-05-31 22:04
Thanks. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/14134

**Closed by mjbvz** 2017-05-31 22:04 UTC
Labels: duplicate, upstream
