### ISSUE TITLE
Collapse/Expand/Fold what ever it's called, add a button at the end of the block!!!!!!!

### ISSUE THREAD

**Issue by RUSshy** [microsoft/vscode#106854] opened 2020-09-16 11:35 UTC
In large function or blocks of code, i can't collapse if i am at the end of it, i have to scroll back the way up, or learn one of the millions shortcuts

Please add a button at the end

IntelliJ ideas got it, same for Eclipse, same for XCode same for Visual Studio

![Code_wFeEoo6eLG](https://user-images.githubusercontent.com/18348637/93331945-56144680-f821-11ea-857d-407f72a9b4c2.png)

**Comment by aeschli** [comment] 2020-09-16 13:23
duplicate of https://github.com/microsoft/vscode/issues/60670

**Closed by aeschli** 2020-09-16 13:23 UTC
