### ISSUE TITLE
Errors in integrated terminal when powershell used

### ISSUE THREAD

**Issue by stgolem** [Microsoft/vscode#7537] opened 2016-06-10 14:02 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 10 Insider

Steps to Reproduce:

1. Setup powershell as integrated terminal
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
2. Open intergarted terminal (powershell starts)
3. Type in "npm --version"

Error appears:

> npm --version
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
>  
> 
> Error: This socket is closed
>     at WriteStream.Socket._writeGeneric (net.js:672:19)
>     at WriteStream.Socket._write (net.js:724:8)
>     at doWrite (_stream_writable.js:307:12)
>     at writeOrBuffer (_stream_writable.js:293:5)
>     at WriteStream.Writable.write (_stream_writable.js:220:11)
>     at WriteStream.Socket.write (net.js:650:40)
>     at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
>     at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
>     at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
>     at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
>  3.9.2

**Comment by Tyriar** [comment] 2016-06-10 19:39
Duplicate of https://github.com/Microsoft/vscode/issues/7194

**Closed by Tyriar** 2016-06-10 19:39 UTC
