### ISSUE TITLE
Python and Jupyter extensions giving signature errors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#167559] opened 2022-11-29 15:45 UTC
## Platform Details
Version: 1.74.0-insider
Commit: 8b9891739b703b50547f506a7e2bc9565e52beff
Date: 2022-11-29T07:06:21.479Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic snap
Sandboxed: Yes

## Repro Steps

1. Have Python and Jupyter pre-release extensions installed
2. Try to switch Python and Jupyter between pre-release and release extensions.
3. 🐛 Will get signature errors

This seems to only effect my Ubuntu VM and not my Mac. 

Possibly related to https://github.com/microsoft/vscode/issues/164726 but this is an x86 VM and not connected to a remote

**Comment by sandy081** [comment] 2022-11-29 15:49
CC @isidorn: need to be investigated that there are issues with signing in this platform.

**Comment by isidorn** [comment] 2022-11-29 16:00
Yup. Let me ping Damon.

**Comment by GongT** [comment] 2022-11-29 22:42
```
2022-11-29 22:41:49.766 [info] Getting Manifest... github.copilot
2022-11-29 22:41:50.676 [info] Installing extension: github.copilot
2022-11-29 22:41:54.942 [error] Error while installing the extension: github.copilot
2022-11-29 22:41:54.943 [error] Failed to install extension. github.copilot
2022-11-29 22:41:54.943 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
2022-11-29 22:41:55.945 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
2022-11-29 22:41:55.945 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
2022-11-29 22:42:17.812 [info] Getting Manifest... yzhang.markdown-all-in-one
2022-11-29 22:42:18.863 [info] Installing extension: yzhang.markdown-all-in-one
2022-11-29 22:42:22.972 [error] Error while installing the extension: yzhang.markdown-all-in-one
2022-11-29 22:42:22.973 [error] Failed to install extension. yzhang.markdown-all-in-one
2022-11-29 22:42:22.973 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
2022-11-29 22:42:23.975 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
2022-11-29 22:42:23.975 [error] Signature: UnknownError
    at Cn.download (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:92:1603)
    at async V.h (/vscode/vscode-server-insiders/bin/linux-x64/8b9891739b703b50547f506a7e2bc9565e52beff-insider/out/vs/server/node/server.main.js:148:89897)
```

**Comment by dtivel** [comment] 2022-12-01 12:31
[This workaround](https://github.com/microsoft/vscode/issues/164726#issuecomment-1333508805) should allow the extensions to install.

**Comment by anribadrijania** [comment] 2023-01-16 15:02
this bug isn't fixed yet
![image](https://user-images.githubusercontent.com/118100142/212708536-f3cdc237-f889-4a96-a745-0996d3976324.png)

**Comment by isidorn** [comment] 2023-01-16 15:25
@anribadrijania you are using VS Code Stable, thus the bug you see is unrelated to the signature error. Please open a new issue.

Closing the above issue as duplicate of https://github.com/microsoft/vscode/issues/164726

**Closed by isidorn** 2023-01-16 15:25 UTC
Labels: bug, extensions
