### ISSUE TITLE
Typing "Settings" In Command Palette Does Not Select The Main Command

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#214574] opened 2024-06-07 09:09 UTC
This is in a fresh incognito tab:

![chrome_DswFepM2Ve](https://github.com/microsoft/vscode/assets/2931520/12db9e77-ddee-40a5-85e2-5fc46302d163)

"Preferences: Open Settings (UI)" or "Preferences: Open Settings (JSON)" should be selected.

There is so much unhelpful stuff here and the least helpful (the developer command) is selected first.

Related #214573

**Comment by TylerLeonhardt** [comment] 2024-06-07 18:58
duplicate of https://github.com/microsoft/vscode/issues/173767#issuecomment-2075149607

**Closed by TylerLeonhardt** 2024-06-07 18:58 UTC
Labels: papercut :drop_of_blood:
