### ISSUE TITLE
When minimizing vertically using Win+Left, the cursor is lost

### ISSUE THREAD

**Issue by miparnisari** [Microsoft/vscode#6046] opened 2016-05-02 19:03 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open the editor with a random text file and maximize it.
2. Place the cursor somewhere and see it blink.
3. Press Windows + Left so that VS Code occupies half the screen.
4. See that the cursor is lost and that if you type you cannot see it. If you maximize it again you can see what you typed.

This issue is not 100% repeatable.

**Comment by alexandrudima** [comment] 2016-05-06 19:24
@miparnisari I am not sure I understand what you mean that the cursor is lost. I have tried quite a number of times doing Windows + Left, Up, Right, etc. and I did not notice anything weird about it. Maybe can you please make a screenshot or even better, a screen recording gif, showing the problem to help me understand better what's wrong?

**Comment by miparnisari** [comment] 2016-05-08 20:23
Here you go:

![bug](https://cloud.githubusercontent.com/assets/5374887/15100198/9d4dd1e6-1541-11e6-8e00-9ee3d309b595.gif)

**Comment by Uriil** [comment] 2016-07-09 19:32
I had exactly same issue in VSCode version 1.3

And steps for reproducing were exactly the same. However, 5 mins later it was fixed somehow and now I can not reproduce it

**Comment by alexandrudima** [comment] 2016-07-11 16:12
fyi @bpasero Maybe related to the drop overlay thing?

**Comment by bpasero** [comment] 2016-07-11 16:15
@alexandrudima that is easy to proove by opening dev tools and checking if the overlay div is on top of the editor.

**Comment by bpasero** [comment] 2016-07-11 17:27
@miparnisari @Uriil to sort out the overlay issue, can you (when this happens), open dev tools (from help menu) and do as I show below in the GIF to see if there is a overlay DIV on top of the editor?

![editors](https://cloud.githubusercontent.com/assets/900690/16740041/794fa13c-479d-11e6-9bec-807970bf7743.gif)

Also, when the cursor is gone, can you type `document.activeElement` in the dev tools console to see which element actually has focus?

**Comment by bpasero** [comment] 2016-07-11 18:39
@miparnisari @Uriil can you try my solution in https://github.com/Microsoft/vscode/issues/9029#issuecomment-231825432 ?

**Comment by Uriil** [comment] 2016-07-11 19:21
@bpasero Ok, I will do it next time I see this bug

**Comment by bpasero** [comment] 2016-07-12 13:10
@miparnisari @Uriil sorry i was not aware this bug is for 1.0.0, in that case my workaround does not have any impact as tabs got introduced in 1.3. 

@alexandrudima I will leave this one open and assign it back to you to close it as you wish.

**Comment by alexandrudima** [comment] 2016-07-15 10:51
I tried and tried and could not reproduce with `winkey + left/right`, the cursor is always blinking correctly for me.

**Closed by alexandrudima** 2016-07-15 10:51 UTC
Labels: needs more info
