### ISSUE TITLE
Interpolation strings don't have colouring

### ISSUE THREAD

**Issue by Vannevelj** [Microsoft/vscode#52] opened 2015-11-18 16:18 UTC
After the update, interpolation strings in a plain `.js` file don't get highlighted anymore. Previous behaviour highlighted plain text, the `$` symbol and the interpolation braces. Now everything between *``* has no colouring at all.

	function sayHello(customer)
	{
		console.log(`Hello ${customer}`);
	}

![nocolours](https://cloud.githubusercontent.com/assets/2777107/11246534/59e31da4-8e18-11e5-883a-80d6fb8ff34b.PNG)

**Comment by Tyriar** [comment] 2015-11-18 16:49
This is applicable to many languages, ruby is another example whose syntax is "Hello #{customer}".

**Comment by mrhmouse** [comment] 2015-11-18 18:05
@Vannevelj could you link to a changeset from "before the update", where this was working? That would help someone track down the issue :smiley:

**Comment by eprickett** [comment] 2015-11-20 05:03
I noticed this problem immediately after allowing the IDE to update itself tonight (to 0.10.1). I was not paying attention to the 'before the update' version myself, but have only had the product (on my mac) since Nov 1 if that helps.

**Comment by ddcovery** [comment] 2015-11-20 09:13
in 0.9.2

![screenshot from 2015-11-20 10-10-40](https://cloud.githubusercontent.com/assets/6564217/11295913/0abd7262-8f6f-11e5-9508-870cf51ddce8.png)

in 0.10.1

![screenshot from 2015-11-20 10-12-43](https://cloud.githubusercontent.com/assets/6564217/11295951/46abdc6e-8f6f-11e5-8c19-11f8b36e2f3c.png)

**Comment by felixfbecker** [comment] 2015-11-21 17:31
I have the same issue

**Comment by aeschli** [comment] 2015-11-24 16:41
duplicate of #133

**Closed** 2015-11-24 16:51 UTC
Labels: bug
