### ISSUE TITLE
Jsx formatter inserts extra space in code block if last character is a right paren

### ISSUE THREAD

**Issue by joseph-iussa** [Microsoft/vscode#9455] opened 2016-07-18 20:26 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open VSCode (with no folders open).
2. Create a new blank file and save as 'test.jsx'.
3. Enter the following into the file: `<div>{new Date().toDateString()}</div>`.
4. Format the file.
5. The text will be altered to: `<div>{new Date().toDateString() }</div>`.

This also happens with JSX embedded in regular js files, the above is simply the most straightforward way of reproducing the problem.

**Comment by aeschli** [comment] 2016-07-21 07:24
duplicate of https://github.com/Microsoft/TypeScript/issues/9823

**Closed by aeschli** 2016-07-21 07:24 UTC
