### ISSUE TITLE
Import file extension not respected on file move

### ISSUE THREAD

**Issue by albertosantini** [Microsoft/vscode#51260] opened 2018-06-06 20:43 UTC
- VSCode Version: 1.24.0
- OS Version: Windows 10

Using "Update import paths when a file is moved or renamed" feature (in a js project), I noticed file extension of the file imported is removed.

The resulting url is not a valid import statement, because the file doesn't contain the extension.

Steps to Reproduce:

1. import { StatsTemplate } from "./stats.template.js";
2. Rename `stats.template.js` to `stats.templateFOO.js` (via vscode explorer)
3. Result: import { StatsTemplate } from "./stats.templateFOO";

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-06-06 23:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/24493

**Closed by mjbvz** 2018-06-06 23:56 UTC
Labels: new release
