### ISSUE TITLE
keyboard shortcuts: wrong interpretations of special keys (e.g. `[Equal]` is mistaken for `V`)

### ISSUE THREAD

**Issue by georglauterbach** [microsoft/vscode#173325] opened 2023-02-03 16:24 UTC
Type: <b>Bug</b>

1. Update VS Code (for me, it was from `1.74.1` to `1.75`)
2. User defined keybindings using scan codes (e.g. `[Equal]` or `[Semicolon]`) are interpreted incorrectly

![Screenshot from 2023-02-03 17-18-58](https://user-images.githubusercontent.com/44545919/216653544-7abfa3b9-1f8c-4f17-99c3-e8c54c65df78.png)

<details><summary>More details</summary>

I was literally unable to copy-paste inside VS Code because pasting was also `ctrl+v`..

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (11.48GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 82449883-a908-4a7a-be3e-fc9cf8042ab0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

---

superseeds #173324

---

</details>

---

### Known workarounds: 
* The fix is available in [latest Insiders](https://code.visualstudio.com/insiders/).
* **If you're using the US keyboard layout** you can edit your user `keybindings.json` and replace scan codes keybindings with key code keybindings e.g. `ctrl+[Equal]` => `ctrl+=`, `ctrl+[Semicolon]` => `ctrl+;`. Here's a table with the most common keys:

| Scan Code | Key Code |
|---|---|
| `[KeyA]` - `[KeyZ]` | `A` - `Z` |
| `[Digit0]` - `[Digit9]` | `0` - `9` |
| `[F1]` - `[F19]` | `F1` - `F19` |
| `[Minus]` | `-` |
| `[Equal]` | `=` |
| `[BracketLeft]` | `[` |
| `[BracketRight]` | `]` |
| `[Backslash]` | `\` |
| `[Semicolon]` | `;` |
| `[Quote]` | `'` |
| `[Backquote]` | `` ` `` |
| `[Comma]` | `,` |
| `[Period]` | `.` |
| `[Slash]` | `/` |
| `[IntlBackslash]` | `OEM_102` |
| `[IntlRo]` | `ABNT_C1` |

**Comment by georglauterbach** [comment] 2023-02-03 16:25
related: https://stackoverflow.com/questions/75336265/vscode-says-equal-key-is-v-keyboard-layout-messed-up

**Comment by goktan** [comment] 2023-02-03 17:12
I think this is not only `ctrl+v` but I have other keybindings stopped working just after this upgrade.

**Comment by georglauterbach** [comment] 2023-02-03 17:20
> I think this is not only `ctrl+v` but I have other keybindings stopped working just after this upgrade.

I adjusted the issue title accordingly. If you find out which one exactly, please let us know :)

**Comment by fernandosmither** [comment] 2023-02-03 18:05
Seriousloy annoying. Does anybody have a quick fix? beyond losing the [Equal] keybindings or downgrading versions

**Comment by fernandosmither** [comment] 2023-02-03 18:13
This is a rather urgent and serious bug :thinking: is there a way to give priority to this issue? @georglauterbach

**Comment by riidom** [comment] 2023-02-03 19:57
I have an affected `ctrl+equal` shortcut, remapped it to `ctrl+alt+equal`, which stays as-is. If you need a quick workaround.

**Comment by georglauterbach** [comment] 2023-02-04 00:24
> This is a rather urgent and serious bug :thinking: is there a way to give priority to this issue? @georglauterbach

I cannot adjust the issue (labels, etc.) myself, but I agree that this should have high priority.

**Comment by timoklein** [comment] 2023-02-04 06:31
The issue has messed up a lot of my custom shortcuts and is incredibly annoying:

- `[BracketRight]` is mapped to X.
- `[BracketLeft]` is mapped to W.
- `[Comma]` is mapped to F2.
- `[Equal]` is mapped to V.
- `[Minus]` is mapped to U.

These are the ones that have been affected for me from a quick glance. I'm shocked that this was released :0

**Comment by Baldomo** [comment] 2023-02-04 12:45
I have the same issue on VSCodium, on a US keyboard layout

```
Version: 1.75.0
Release: 23033
Commit: d48b950f7741008f7fb375881b45188dd73ecac4
Date: 2023-02-02T22:14:58.243Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.6-arch1-g14-1
Sandboxed: No
```

Additionally, these keycodes are also broken:

- `[Backquote]` is mapped to F1 but not when used with `ctrl+alt+[Backquote]` (that works as intended)
- `[Backslash]` is mapped to Y on both IT and US layouts (I assume it's the same for all layouts then)

**Comment by georglauterbach** [comment] 2023-02-04 14:17
ping @alexdima; this should probably have high priority as broken keyboard shortcuts really cut the experience of using VS Code short

**Comment by birgersp** [comment] 2023-02-04 15:13
I'm hoping this gets a high priority. It completely messed up a lot of my key bindings.

> These are the ones that have been affected for me from a quick glance. I'm shocked that this was released :0

Released on a friday :wink: Have a nice weekend ya'll!

**Comment by vaaski** [comment] 2023-02-04 15:57
For me on a german layout, `cmd+y` is `cmd+#` for some reason, now I can't redo anymore.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/17879327/216777139-95f224f1-0c74-4c3c-b10b-fa4637fa969c.png">

**Comment by M4he** [comment] 2023-02-04 19:04
> For me on a german layout, `cmd+y` is `cmd+#` for some reason, now I can't redo anymore.
> 
> <img alt="image" width="243" src="https://user-images.githubusercontent.com/17879327/216777139-95f224f1-0c74-4c3c-b10b-fa4637fa969c.png">
> 
> edit: just confirmed that this issue isn't present on 1.74.3

Can confirm.

Pressing `[Ctrl]+[#]` on the keyboard shortcut settings page with a German keyboard adds `"key": "ctrl+[Backslash]"` to `keybindings.json`. This behavior (config write) is the same on 1.74.x as well as 1.75.0. However, the interpretation of this (config read) is different:

On 1.74.x, this *used to work*, i.e. `ctrl+[Backslash]` in the config did correspond to a physical key press of `[Ctrl]+[#]` in the editor using a German keyboard.

However, on 1.75.0 this config entry reacts to a physical keypress of `[Ctrl]+[Y]` only. Thus, VSCode does not correctly interpret the `keybindings.json` entry it wrote itself (even if written with 1.75.0, this is not a config migration problem):

- config write: `[Ctrl]+[#]` -> "ctrl+[Backslash]"
- config read: "ctrl+[Backslash]" ->  `[Ctrl]+[Y]`

**Comment by hamzahamidi** [comment] 2023-02-05 03:27
Potential fix [here](https://github.com/microsoft/vscode/pull/173456).
The issue was introduced [here](https://github.com/microsoft/vscode/pull/169842).
The hashcode for scan codes and simple keys was not updated to distinguish between them.

**Comment by alexdima** [comment] 2023-02-05 17:00
@hamzahamidi Thank you for tracking this down! This is indeed caused by the implementations of `KeyCodeChord.getHashCode()` and `ScanCodeChord.getHashCode()`, which produce strings which overlap.

For example:
* a key code based binding like `ctrl+v` will have the hash code `100052`.
* a scan code based binding like `ctrl+[Equal]` will also have the hash code `100052`.

**Comment by russbert** [comment] 2023-02-05 18:59
> Potential fix [here](https://github.com/microsoft/vscode/pull/173456). The issue was introduced [here](https://github.com/microsoft/vscode/pull/169842). The hashcode for scan codes and simple keys was not updated to distinguish between them.

When is it possible to release this hotfix? It's pretty urgent.

**Comment by alexdima** [comment] 2023-02-05 19:44
> When is it possible to release this hotfix? It's pretty urgent.

I'm super sorry for this regression! I'm trying to get the change into tomorrow's Insiders and we'll very likely ship it with `1.75.1`. I've updated the issue description with a potential workaround which consists of editing the scan code based user bindings to use key code.

**Comment by Snouzy** [comment] 2023-02-05 19:54
any workaround for azerty keyboards ?

**Comment by vaaski** [comment] 2023-02-05 20:57
> any workaround for azerty keyboards ?

downgrading to 1.74.3 works

**Comment by russbert** [comment] 2023-02-05 22:04
The fix was merged. Thanks @alexdima and Thank you @hamzahamidi for the quick fix

**Comment by mrth2** [comment] 2023-02-06 10:42
anyone knows when will new version release to fix 1.75 key bindings issue?

**Comment by georglauterbach** [comment] 2023-02-06 10:44
> anyone knows when will new version release to fix 1.75 key bindings issue?

Most likely with 1.75.1.

**Comment by alexdima** [comment] 2023-02-06 16:21
Reopening to track the merge to stable

**Comment by FernandoMiguel** [comment] 2023-02-06 17:42
this seems to be fixed in the latest nightly
```
Version: 1.76.0-insider
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:39:44.179Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by Dexmaxter18** [comment] 2023-02-06 19:58
> Type: Bug
> 
>     1. Update VS Code (for me, it was from `1.74.1` to `1.75`)
> 
>     2. User defined keybindings using scan codes (e.g. `[Equal]` or `[Semicolon]`) are interpreted incorrectly
> 
> 
> ![Screenshot from 2023-02-03 17-18-58](https://user-images.githubusercontent.com/44545919/216653544-7abfa3b9-1f8c-4f17-99c3-e8c54c65df78.png)
> More details
> Extensions disabled
> ### Known workarounds:
> 
>     * The fix is available in [latest Insiders](https://code.visualstudio.com/insiders/).
> 
>     * **If you're using the US keyboard layout** you can edit your user `keybindings.json` and replace scan codes keybindings with key code keybindings e.g. `ctrl+[Equal]` => `ctrl+=`, `ctrl+[Semicolon]` => `ctrl+;`. Here's a table with the most common keys:
> 
> 
> Scan Code 	Key Code
> `[KeyA]` - `[KeyZ]` 	`A` - `Z`
> `[Digit0]` - `[Digit9]` 	`0` - `9`
> `[F1]` - `[F19]` 	`F1` - `F19`
> `[Minus]` 	`-`
> `[Equal]` 	`=`
> `[BracketLeft]` 	`[`
> `[BracketRight]` 	`]`
> `[Backslash]` 	`\`
> `[Semicolon]` 	`;`
> `[Quote]` 	`'`
> `[Backquote]` 	`` ` ``
> `[Comma]` 	`,`
> `[Period]` 	`.`
> `[Slash]` 	`/`
> `[IntlBackslash]` 	`OEM_102`
> `[IntlRo]` 	`ABNT_C1`
#same hare [Backquote] is replaced by F1
![Captura de pantalla de 2023-02-06 14-44-08](https://user-images.githubusercontent.com/80091828/217071825-0af3513f-4610-4bbf-a9da-7a38d4101edd.png)

**Comment by Dexmaxter18** [comment] 2023-02-06 20:03
same here [backquote] replaced by [F1]
![Captura de pantalla de 2023-02-06 14-44-08](https://user-images.githubusercontent.com/80091828/217072815-7c17c5b3-9e65-44fa-8c4b-ee70d51c9f1a.png)
#173325

**Comment by A7mdFathi** [comment] 2023-02-07 01:01
we can use vscode insider [here](https://code.visualstudio.com/insiders/#) as temporary replacement for stable version 
bug fixes in this version and we can use settings sync to get extensions and settings from stable

**Comment by alexdima** [comment] 2023-02-07 08:56
Verification steps:
* use Linux or macOS
* add the following to your `keybindings.json`:
```
{ "key": "cmd+[Equal]", "command": "actions.find" }
```
* Hover over `cmd+[Equal]`. It should not say "cmd+V for current keyboard layout".
* Press `cmd+v`. It should not trigger the find widget.

**Closed** 2023-02-07 08:56 UTC
Labels: important, candidate, regression

**Comment by niccolomineo** [comment] 2023-02-08 14:30
Hi, I don't mean to put pressure, but I'd like to ask how long it will take to take the fix to stable.

Thank you for your work.

**Comment by alexdima** [comment] 2023-02-08 14:39
> Hi, I don't mean to put pressure, but I'd like to ask how long it will take to take the fix to stable.

We plan to release `1.75.1` today or tomorrow.

**Comment by aeschli** [comment] 2023-02-08 15:16
Verified in stable release candidate (Version: 1.75.1 Commit: 30b39f04b4b323377f4131bc76a3b7bc5f60475d)
