### ISSUE TITLE
Comments pane doesn't show comments

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#74589] opened 2019-05-29 23:44 UTC
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.35.0-insider (6964233e81c68f5a5f34e7eb1da0836e1d539f14, 2019-05-29T05:18:15.943Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Repro**
Build and run [commet-sample from vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample).
1. Add a note (start a comment thread) and add several replies in to one file.
2. Add another note (start another comment thread) in the same file.
3. Open COMMENTS pane, and check out the comments.

Expected:
Both comment threads show up.

Actual:
Only the first comment thread is there. The second one appears as an empty line.

If you start another comment thread in another file, the COMMENTS pane will display the file name without the comment thread.

**Comment by IlyaBiryukov** [comment] 2019-05-30 00:57
Another repro, most likely caused by the same bug:
With the same `comment-sample`, add several comment threads into one document, then dispose of the `commentController` (you'd need to add another command that would call `commentController.dispose()`). The COMMENTS pane won't be cleared up. It'll have the document name and several empty lines below it.

**Comment by IlyaBiryukov** [comment] 2019-05-30 18:24
cc @rebornix

**Comment by rebornix** [comment] 2019-05-30 21:38
@IlyaBiryukov thanks for the bug report, appreciate that!

**Comment by isidorn** [comment] 2019-05-31 09:07
Could not verify this due to https://github.com/microsoft/vscode/issues/74668

**Comment by IlyaBiryukov** [comment] 2019-06-11 16:36
Still repros on
Version: 1.36.0-insider (system setup)
Commit: 7bc29bf67c17608b11e23a8497c8f1de5a0922cf
Date: 2019-06-11T08:32:47.289Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by IlyaBiryukov** [comment] 2019-06-11 16:37
@rebornix re-open the issue please? It still repros.

**Comment by isidorn** [comment] 2019-06-12 08:02
Let's reopen and assign to @rebornix and he can investigate more.

**Comment by rebornix** [comment] 2019-07-19 18:09
Already made some changes to the comments related code, now this issue can not be reproduced with below steps

* Debug Comment Sample
* Create a new comment thread
* Reply to the thread
* Open Comments Panel, both comments are displayed
* Open command palette, run "Remove All Notes"
* Comment Panel shows "There are no comments..."

Close it for now but we can reopen if you can still repro.

**Closed by rebornix** 2019-07-19 18:09 UTC
Labels: bug
