### ISSUE TITLE
Setting default build task for Typescript does nothing at all.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [Microsoft/vscode#31964] opened 2017-08-03 09:43 UTC
Following the steps in the VSCode documentation for Typescript here https://code.visualstudio.com/docs/languages/typescript

The procedure for "Step 3: Make the Typescript build the default" doesn't work. The tasks.json file is generated in the project ./vscode directory and the contents are correct, but when pressing CTRL+SHIFT+B instead of running the default build task it instead continues to pop up the build selection dropdown instead.

So how do I actually configure the default build task?

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.9.3
vscode-great-icons|emm|2.1.7
auto-close-tag|for|0.4.2
csharp|ms-|1.10.0
debugger-for-chrome|msj|3.1.4
vscode-css-peek|pra|1.2.4
html-css-class-completion|Zig|1.7.0

(1 theme extensions excluded)

**Comment by vintagenib** [comment] 2017-08-21 17:20
I'm having the same trouble with settings default rake tasks for build and test.  It is properly configured but I experience the same behaviour that @Neutrino-Sunset does.

[tasks.json.txt](https://github.com/Microsoft/vscode/files/1239623/tasks.json.txt)

**Comment by mjbvz** [comment] 2017-09-05 23:34
This issue was also reported in #32704, which was closed as a duplicate of #31977 which has since been fixed. 

I believe it should be fixed in the latest insiders builds

**Closed by mjbvz** 2017-09-05 23:34 UTC
Labels: bug, tasks
