### ISSUE TITLE
Saving a new file closes it

### ISSUE THREAD

**Issue by BrianL-STCU** [microsoft/vscode#114317] opened 2021-01-13 22:28 UTC
Issue Type: <b>Bug</b>

1. Ctrl+N to create a new file
2. Ctrl+S to save file
3. Provide a filename and hit enter (or click Save)
4. The tab for that file disappears

VS Code version: Code - Insiders 1.53.0-insider (9bfa4c1d55892571b5936599fd628a5bfb9ac1db, 2021-01-13T09:41:07.305Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (6.32GB free)|
|Process Argv|--crash-reporter-id 8b3ccbfd-d84c-4a53-b0cb-7a90a08f8211|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by BrianL-STCU** [comment] 2021-01-13 22:29
This does not appear to be a duplicate of either of those.

**Comment by yume-chan** [comment] 2021-01-14 07:27
Duplicate of #114272

**Comment by isidorn** [comment] 2021-01-14 10:47
Thanks @yume-chan !

**Closed** 2021-01-14 10:47 UTC
Labels: *duplicate
