### ISSUE TITLE
Loaded scripts view shows weird path in Chrome attach case

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#57596] opened 2018-08-30 10:35 UTC
Testing #57249

* launch Chrome with remote debugging on
* open https://microsoft.github.io/monaco-editor/
* connect to it from VS Code

Observe the weird path shown in hover:
![image](https://user-images.githubusercontent.com/5047891/44846616-205b8f80-ac51-11e8-8afd-aa20d9804e46.png)

**Comment by weinand** [comment] 2018-08-30 10:41
duplicate of #57545

**Closed by weinand** 2018-08-30 10:41 UTC
Labels: bug, debug
