### ISSUE TITLE
Allow to save without save participants

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#53376] opened 2018-06-30 10:13 UTC
Issue Type: <b>Bug</b>

This issue reproduces with the following settings:

```
"files.insertFinalNewline": true,
"files.trimFinalNewlines": true,
"files.trimTrailingWhitespace": true,
```

Also, to see whitespaces in diff editor:

```
"diffEditor.ignoreTrimWhitespace": false,
```

Steps to reproduce:

1. mkdir repro && cd repro
2. git init
3. Add `repro.txt` (attached): git add repro.txt && git commit

[repro.txt](https://github.com/Microsoft/vscode/files/2151603/repro.txt)

4. Open this directory in vscode
5. Open `repro.txt` in editor and replace "line 1" with "line 10"
6. Save file (Ctrl+S)
7. Open `repro.txt` in diff editor

Actual result:

![image](https://user-images.githubusercontent.com/993454/42124060-02648b1a-7c65-11e8-9862-99fab17f9d23.png)

8. Manually undo changes to lines you didn't change (all lines except "line 10"):

![image](https://user-images.githubusercontent.com/993454/42124077-46e03a28-7c65-11e8-9008-56390e66db79.png)

9. Save file (Ctrl+S)

Actual result: it's impossible to undo unwanted changes in diff editor.

![image](https://user-images.githubusercontent.com/993454/42124095-87983746-7c65-11e8-9621-832e28fcfc70.png)

It's only possible to undo auto formatting with a help of external editor or by temporary disabling settings mentioned above. Or am i missing something?

Possibly related issue: #38695. Also possibly related issue: #44075.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.0-112-generic

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
nightswitch-lite|gha|2.1.0
cpptools|ms-|0.17.5
Go|ms-|0.6.84
shader|sle|1.1.3
cmake|twx|0.0.17
vscode-todo-highlight|way|0.5.12
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-07-27 10:45
Those settings will edit the buffer when you save it to disk. That is the reason those settings exist.

@bpasero for your opinion: Arguably, we could have a "Save without participants" action to be able to save files with trailing newlines if trailing newlines are desirable and if the settings are turned on...

**Comment by alekseyt** [comment] 2018-07-27 16:30
Yeah, those are great settings and i deeply appreciate their existence. But please note that i originally submitted this issue for --> **diff editor** <--.

My point is that i have to use external editor to edit patch OR alternatively i could disable those setting, but as you've pointed out, that would defeat the purpose of having those setting. Vscode's diff editor is pretty neat and i enjoy using it, but i *have to* use external editor, not by choice, i *have to* because i can't undo unwanted changes to a patch.

From my perspective, diff editor just does unnecessary step. I can always format source code in editor if i want to.

**Comment by alexandrudima** [comment] 2018-07-30 12:20
@alekseyt I understand your point, but for us the diff editor is just a view onto a file. Currently, the exact same file saving logic executes regardless if a text buffer is being edited from a diff editor or from a regular editor. The text buffer doesn't know where the edits occur from. Then, the text buffer is saved to disk. So the fact that those edits were made from a diff editor or from a regular editor is not recorded anywhere. That's why I was suggesting we have a different save action that saves without save participants.

**Comment by bpasero** [comment] 2018-08-08 13:14
I think such an action would probably make sense. On the other hand, these settings are typically there for a reason so that a project ensures a certain code style. If the diff editor would not run these participants, it would defeat the purpose.

**Comment by bryanrsmith** [comment] 2018-08-08 19:13
I can't really speak to the diff editor use case (sorry if I caused any confusion by chiming in here). Personally I would use this action in the normal editor view with an alternate key binding when editing miscellaneous files outside of a project, or when making quick changes in another team's project that may not use a specific format. I imagine if such an action were implemented it could be configured for use in whichever view the user desired, correct?

**Comment by alekseyt** [comment] 2018-08-08 20:28
The reason why i filed this specifically for diff editor is because changelog has a value. Those settings are great and they serve their purpose, but sometimes maintaining a code style or overall code hygiene is not worth damaging history. It's simply not worth it, description of a line in source control has more value than absence of a random whitespace at the end of it. This might or might not be important for something like open-source projects when various often unrelated individuals are editing 7-10 years old lines, for example.

But the most strange part of it and the reason behind "bug" issue type is that launching external editor is more convenient than editing text file (diff) in-place. It's simply not possible to have both: those options enabled and revert unwanted changes from a diff.

As far as i'm aware Visual Studio has something similar (by default? formats only edited lines? no?), perhaps for a reason, maybe not, i don't know, maybe enough people pointed that out or something. Just my 2 cents.

**Comment by bpasero** [comment] 2018-09-20 16:41
Duplicate of https://github.com/Microsoft/vscode/issues/38695

**Closed by bpasero** 2018-09-20 16:41 UTC
Labels: feature-request, workbench-editors
