### ISSUE TITLE
Debugger does not detect soft links correctly

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#53443] opened 2018-07-02 12:57 UTC
I have seen more issues related to symlinks, but not exactly this one, that is why I am opening a new one.

My problem is that my whole C++ project is inside a soft link. When I use the VS Code debugger it works correctly (it detects my breakpoints and everything). But, when it stops in a breakpoint, it does it opening the file as a duplicate. The path of this file is the one without the symlink, it is the absolute hard path. I would expect VS Code to detect the soft link and not open a duplicate of the file.

When the duplicate file is open, I also get a problem with the Find and Replace tool. If I search for a piece of text of this file, the result appears twice, as if it were on different files.

 

- VSCode Version: 1.24.1
- OS Version: Ubuntu 16.04.4 LTS (Linux 4.13.0-45-generic)

Steps to Reproduce:

1. On linux, create a C++ project that is built with gmake. The whole project is located under a soft link.
2. Use VS Code debugger, and put a breakpoint anywhere. When the debugger hits the breakpoint, it will open the file as a duplicate.

**Comment by weinand** [comment] 2018-07-02 13:15
The C++ debugger you are using is only seeing the hard path to the file, it does not know anything about soft links.

Mapping hard paths back to symlinks automatically is difficult because VS Code does not know all the symlinks that exist. In addition there can be more than one symlink that covers the same hard path. To what symlink should VS Code map back?

The only solution that I can think of is to provide a user-configurable mapping mechanism, e.g. something like this:
```
"/some/hard/link/**": "/soft/link"
```

With this any path returned by the debugger that matches the left pattern would be mapped to the right pattern, e.g. "/some/hard/link/src/test.js" would become "/soft/link/src/test.js".

This mapping mechanism would not know anything about symlinks at all. It is just a general path making mechanism. The VS Code node-debugger already supports such a mapping mechanism.

**Comment by weinand** [comment] 2018-07-02 13:20
duplicate of #33861

**Closed** 2018-07-02 13:20 UTC
Labels: *duplicate, debug, feature-request

**Comment by dsanz006** [comment] 2018-07-02 15:50
I understand VS Code doesn't know anything about soft links, however it seems to use the soft link sometimes and the hard path some other times. In all my configuration files (**.code-workspace, tasks.json, launch.json...) I am setting all the paths relative to ${workspaceRoot}. VSCode seems to use the soft link for the **.code-workspace file, and the hard link for the tasks.json and launch.json files. That's what doesn't make sense to me, and that is why I am getting duplicates when debugging. In my opinion, if it doesn't know anything about soft links, it should always use absolute hard paths to avoid duplicates.

**Comment by weinand** [comment] 2018-07-02 16:15
I didn't say that VS Code doesn't know anything about soft links.
I said that the C++ debugger does not know anything about soft links.

VS Code understand symlinks and follows them correctly. 
But the C++ debugger doesn't. 
So any "hard" path returned by the debugger needs to be mapped to the original symlink.

And that's the problem VS Code cannot solve without help because the backward mapping is ambiguous.

**Comment by dsanz006** [comment] 2018-07-02 17:41
I understand, thank you.
