### ISSUE TITLE
selecting rtl text moves it

### ISSUE THREAD

**Issue by alondon17** [microsoft/vscode#146979] opened 2022-04-07 07:42 UTC
Issue Type: <b>Bug</b>
selcting hebrew text  with more than lone word in ltr environment  moves it visually while it's selected (deselcting puts it back to normal)
 for example  this
![image](https://user-images.githubusercontent.com/29633387/162146009-c281e188-a938-4451-aecd-3ee0a563258a.png)
![image](https://user-images.githubusercontent.com/29633387/162146115-ec9f110d-636e-4b4b-be94-6464d0f5d52c.png)
it makes it impossible to select a part of the text
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>
![image](https://user-images.githubusercontent.com/29633387/162146009-c281e188-a938-4451-aecd-3ee0a563258a.png)
![image](https://user-images.githubusercontent.com/29633387/162146115-ec9f110d-636e-4b4b-be94-6464d0f5d52c.png)

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.14GB free)|
|Process Argv|--crash-reporter-id 425eec6b-ed50-42ad-860e-367698058d73|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
path-intellisense|chr|2.8.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
prettier-vscode|esb|9.5.0
restore-terminals|Eth|1.1.7
nginx-formatter|ray|0.0.13
vscode-yaml|red|1.6.0

</details>

**Comment by alondon17** [comment] 2022-04-07 07:49
maybe while selected, the space is calculated are ltr?

**Comment by alondon17** [comment] 2022-04-07 07:55
![image](https://user-images.githubusercontent.com/29633387/162148855-c82ab2f2-3176-4dae-9440-499abbf852d0.png)
![image](https://user-images.githubusercontent.com/29633387/162149002-af989f36-a3f7-4c5a-a970-da8e1fb96ba2.png)
but here it seemingly converts the rest of the line to rtl??

**Comment by gjsjohnmurray** [comment] 2022-04-07 08:10
Likely fixed in the upcoming 1.66.1 recovery release, expected later today.

**Comment by alexdima** [comment] 2022-04-07 08:27
Duplicate of https://github.com/microsoft/vscode/issues/99589#issuecomment-1089033483 . A fix is already available in [VS Code Insiders](https://code.visualstudio.com/insiders/)

**Closed by alexdima** 2022-04-07 08:27 UTC
