### ISSUE TITLE
Quick switch window does not behave as expected

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55058] opened 2018-07-25 13:54 UTC
Refs: #54864

windows, have 3 vscode windows open

1. Quick switch window -> properly switched to another vscode window
2. Quick swithc window -> no switching happening 🐛

I would expect that using this command I can switch through all 3 vscode windows that are open

**Comment by sandy081** [comment] 2018-07-25 17:02
Duplicate of #54673

**Closed** 2018-07-25 17:03 UTC
Labels: *duplicate, bug
