### ISSUE TITLE
[ts] issues that are false positive

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#50413] opened 2018-05-24 18:58 UTC
- VSCode Version: 1.24.0-insider
- OS Version: macOS 10.13.3

I find this is hard to reproduce. But basically vscode is raising all sorts of issues like this in my `.js` files:
`[ts] 'translation' is declared but its value is never read`
`[ts] ',' expected.`
`[ts] Declaration or statement expected.`
`[ts] Unexpected token. A constructor, method, accessor, or property was expected.`
`[ts] Unterminated regular expression literal.`

That shouldn't be an issue, because the javascript code is perfect. It happens when you start typing/working on a piece of code. Then, the error appears and it doesn't go away. Sometimes, removing an empty line makes some errors go away, which doesn't make any sense.

**This wasn't happening before I updated to the latest insider version.**

Does this issue occur when all extensions are disabled?: Yes

**Comment by superheri** [comment] 2018-05-24 19:48
This has already been resolved

**Comment by mjbvz** [comment] 2018-05-24 20:12
Duplicate of #50405

**Closed by mjbvz** 2018-05-24 20:12 UTC
Labels: typescript
