### ISSUE TITLE
VSCode does not update on Multiuser Server, even when installed in User-Mode

### ISSUE THREAD

**Issue by MrFly72** [microsoft/vscode#224542] opened 2024-08-02 05:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.90.2
- OS Version: Server 2022

Steps to Reproduce:

1. Install an older version of VSCode with User Setup for two users on a server 2022 (Non-Admin-Mode UAC)
2. Start VSCode with both users and keep them both running an logged in (Non Admin Mode UAC)
3. Check for new version with one of the users and press update
4. The Install will fail, as it seems to detect the process of the other user, which it cannot even kill (and should even not try)
Expected behaviour would be to only look for processes of the current user and NOT all users on the server!

![image](https://github.com/user-attachments/assets/3f7bed95-9ef8-4a14-a75b-b8a39d9f5c38)
![image](https://github.com/user-attachments/assets/880f6e92-d18e-4048-9e86-fbe49e268bf5)

**Comment by MrFly72** [comment] 2024-08-02 05:32
Thank you Mr-Bot (hihi), but that is exactly what I wanted to do ;-)

**Comment by MrFly72** [comment] 2024-08-30 05:06
Any news on this?

**Comment by MrFly72** [comment] 2024-10-22 11:00
Hello? Somebody listening????
This is driving us nuts.
All the updates dont work and lets face it, this problem cannot be that difficult.
If I run the installer, it will install, so it is the autoupdate process which does the wrong check.

**Comment by MrFly72** [comment] 2024-10-26 16:15
@joaomoreno Any news on this?
This is really a problem in corporate environments, where you use admin-servers or even on multiuser terminalservers.
Cannot be difficult in my eyes?

**Comment by MrFly72** [comment] 2024-11-15 10:12
@joaomoreno Would be great to get a feedback on this

**Comment by joaomoreno** [comment] 2024-11-15 15:40
Duplicate of https://github.com/microsoft/vscode/issues/76641

**Closed by joaomoreno** 2024-11-15 15:40 UTC
