### ISSUE TITLE
Control extension identity in hoisted npm modules that are outside of the extension folder in extension development mode

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#126627] opened 2021-06-17 21:06 UTC
If extension development uses yarn to hoist npm packages up the directory tree, and the extension folder is in a sub-folder, VSCode doesn't recognize the extension if `require('vscode')` runs in a module that is in the hoisted packages. Because of this proposed APIs cannot be enabled and other VSC features that depend on the extension identity are broken.

Directory tree:
```
d:/src/Cascade/vscode
| --- liveshare/core/dist/src/file-system-provider/WorkspaceProvider.js <-- some of the extension code lives here.
|
| --- node_modules/ <-- yarn hoists the code here, including the code from the above folder.
       | --- @vs/liveshare-core/dist/src/file-system-provider/WorkspaceProvider.js <-- yarn created a symlink that points to the above .js file. 
|
| --- extension/ <-- extension folder. That's what --extensionDevelopmentPath points to.
       | --- package.json. It has "main": "src/out/extension"
       | --- src/out/extension.js <-- Extension entry point.
```

When code from `WorkspaceProvider.js` tries to require 'vscode', it fails to recognize the extension. 
Extension host logs:
```
[2021-06-17 11:32:38.850] [exthost] [warning] Could not identify extension for 'vscode' require call from d:\src\Cascade\vscode\liveshare\core\dist\src\file-system-provider\WorkspaceProvider.js. These are the extension path mappings: 
	d:\src\Cascade\vscode\extension -> ms-vsliveshare.vsliveshare
        ...
```

This issue is only relevant during development. Released extension uses webpack and doesn't have this issue.

So, the question is, how to tell vscode in extension development mode that some of the folders outside of the extension's directory still belong to the extension.

**Comment by jrieken** [comment] 2021-06-18 07:16
/duplicate of https://github.com/microsoft/vscode/issues/124820

**Closed** 2021-06-18 07:16 UTC
Labels: *duplicate

**Comment by IlyaBiryukov** [comment] 2021-06-18 16:18
@jrieken In my case, the symlinks are not the factor. Even if there were no symlinks at all, and all the files just existed in their respective locations, the issue would still occur. I don't think it's a dupe, unless, of course, if you're developing a solution that may fix both of the bugs.

**Comment by IlyaBiryukov** [comment] 2021-06-18 16:22
In case of #124820, npm link creates a symlink inside the extension directory's node_modules. In my case, `resolve('my_code')` loads the code from {extension_folder}../node_modules/my_code, which is outside of the extension folder whether symlinks are involved or not. The feature request is to be able to configure VSCode so it treats {extension_folder}../node_modules as belonging to the extension.
