### ISSUE TITLE
login shell in integrated terminal stopped working on 1.75.0

### ISSUE THREAD

**Issue by bluebrown** [microsoft/vscode#173277] opened 2023-02-03 10:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.75.0
- OS Version:  Linux WDE-N-W0410 5.15.79.1-microsoft-standard-WSL2  x86_64 GNU/Linux

Steps to Reproduce:

After updating vscode to 1.75.0, yesterday. The below config is not working anymore. Before that, I would get my configurations bound to running a login shell.

```json
  "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash",
            "args": [
                "-l"
            ]
        },
    },
```

Particularly, I use starship and have set this in ~/.bash_login. But my prompt is not using starship in vscode anymore.

```bash
cat ~/.bash_login 
#!/usr/bin/env bash

if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
fi

eval "$(starship init bash)"

eval "$(direnv hook bash)"
```

**Comment by meganrogge** [comment] 2023-02-03 13:45
Pretty sure this hasn't changed recently - for bash login shells, the `bash_profile` will be run if it exists instead of `bash_login`. So you probably have a `bash_profile` that's getting run. Removing that will cause the `bash_login` file to be executed.

**Comment by bluebrown** [comment] 2023-02-03 17:00
@meganrogge, I am sure that it was still working the minute before I closed VSCode, and it ran the auto update. When I opened vscode the next time, time it didn't work anymore.

There is also no bash_profile.  It also wouldn't pair well with the fact that my bash_login is indeed used, except for the in VsCodes integrated terminal. If that wasn't the case, I would not open the issue specifically with VS Code.

````bash
find ~ -maxdepth 1 -type f -name .bash_profile 
# wow such empty
```

I would appreciate if that could be opened again.

**Comment by bluebrown** [comment] 2023-02-03 17:33
Hm, I just noticed that it works when I click explicitly on the bash terminal to open a terminal.

So it appears to be linked to the default terminal. It does not work when I simply click the plus icorn or drag the lower edge of the editor up.

This is from the plus icon:

![terminal without login shell](https://user-images.githubusercontent.com/39703898/216668848-f6cf25de-b79f-438f-bf85-63eb42a36695.png)

And this is from using explcit bash 

![terminal with login shell](https://user-images.githubusercontent.com/39703898/216668931-a216e129-5349-4b32-9a8a-de8393fad9fc.png)

By explicit bash I mean the entry in the dropdown

![terminal dropdown](https://user-images.githubusercontent.com/39703898/216669034-cb3d2ba7-3860-4789-941b-8fa78047a7a2.png)

If you look closely, you see that the icons are also different for both terminal in the split. If I hover over them, both tsay the same thing. `Bash - Shell integrated (active)`.

**Comment by bluebrown** [comment] 2023-02-03 17:41
It is working now by selecting the default terminal. 

![default terminal selection](https://user-images.githubusercontent.com/39703898/216670493-2418facc-b2f7-4887-9cc6-15d94632f2f9.png)

Now the bash shell is also showing that it is the default in the dropdown

![image](https://user-images.githubusercontent.com/39703898/216670689-8a59b927-523d-4877-90bb-d16a48e2735d.png)

The strange part is, I do not have any other bash in the selection. So what was the default even set to?

**Comment by meganrogge** [comment] 2023-02-06 15:48
cannot reproduce even when I delete my default profile.

**Comment by Tyriar** [comment] 2023-02-06 15:52
@bluebrown does this only happen when you open the terminal panel, close the window and reopen it such that the panel gets "restored"? There have been bugs in the past around the first shell launched when the panel gets restored after startup.

**Comment by bluebrown** [comment] 2023-02-07 09:31
@Tyriar, before I set my default terminal, it would not work at all. Now, since I have the default terminal set, it behaves like you describe. When I open a new VS Code window, it's still using the "wrong" bash. I need to close the terminal and open a fresh one, for the login shell to work.

**Comment by sfsaccone** [comment] 2023-02-08 14:55
At the same time this issue appeared for me, in the Jan 2023 update, I also found that terminals take a much longer time to open and that there's a node process under heavy load. Should I open a new issue for this, or could it be related to this issue?

**Comment by akiekintveld** [comment] 2023-02-09 20:31
I'm seeing similar behavior to @bluebrown. When I reconnect to a Remote SSH host that had open integrated terminal tabs, they are re-opened as the built-in `bash` terminal profile, even though I have `terminal.integrated.defaultProfile.linux` set to a custom `fish` shell profile on this machine. Closing the tab and re-opening a new integrated terminal correctly picks my custom `fish` profile. This started after the Jan 2023 update.

**Comment by connor4312** [comment] 2023-04-27 19:27
What's the best way to verify this? I made an executable `~/.bash_login` file with the contents

```
#!/usr/bin/env bash
echo 'hi'
```

but I don't see "hi" being echo'ed.

**Comment by meganrogge** [comment] 2023-04-27 19:53
Yeah this is not working for me and I see we don't provide `-l` as `args`
![Screenshot 2023-04-27 at 12 52 11 PM](https://user-images.githubusercontent.com/29464607/234975935-186c363a-c032-497d-b0bf-bdee1c1b9baf.png)

**Comment by meganrogge** [comment] 2023-04-27 19:56
@connor4312 add something to your `~/.bash_profile` such as `echo login` and verify you see that

**Closed** 2023-04-27 19:55 UTC
Labels: bug, terminal-profiles, terminal-shell-bash

**Comment by tigerinus** [comment] 2023-05-25 14:10
I am still experiencing this issue under SSH Remote from Windows to Linux (ubuntu)

Which version is this issue fixed?

```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```
