### ISSUE TITLE
typescript language service dying

### ISSUE THREAD

**Issue by bboyle** [microsoft/vscode#152000] opened 2022-06-14 00:03 UTC
Issue Type: <b>Bug</b>

VSCode prompted me to report this. I don't know what the cause is, but it says it's "died unexpectedly 5 times in the last 5 minutes.

Code base is a large angular repo, typescript code, running automated tests with wallaby, spectator and jest.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (12.54GB free)|
|Process Argv|--crash-reporter-id c0f9198f-aacb-445e-afa3-3c1053bb8a6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.0.1
vscode-toggle-quotes|Bri|0.3.6
reverse-search|Dan|2.0.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.7
prettier-vscode|esb|9.5.0
todo-tree|Gru|0.0.215
output-colorizer|IBM|0.1.2
git-angular|Jhe|1.0.0
gremlins|nho|0.26.0
abracadabra|nic|6.13.0
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.8.0
rome|rom|0.8.0
ActiveFileInStatusBar|Ros|1.0.3
mdx|sil|0.1.0
addDocComments|ste|0.0.8
vscode-stylelint|sty|1.2.2
vscodeintellicode|Vis|1.2.21
vscode-typescript-vue-plugin|Vue|0.37.7
quokka-vscode|Wal|1.0.478
wallaby-vscode|Wal|1.0.338
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by HarmonyCB** [comment] 2022-06-14 08:45
We get the same, I believe it's somehow related to jest -> however this issue has been reported repeatedly and is automatically closed every time due to "lack of information" or "too old" - for the record, if someone wants me to debug this just let me know, I will provide whatever info you need for as long as it takes to solve it (but if you close this one due to "inactivity" I will be cross) -  it makes vscode unusable on our project as it crashes in tsserver.ts literally every 5 minutes.

**Comment by HarmonyCB** [comment] 2022-06-14 09:30
More info, sometimes it even opens tsserver.ts and / or a bunch of temporary files (leaving them open through the restart) - if there's a way to get the debugger to break on an extension crash I can probably also tell you why it's happening.

**Comment by bboyle** [comment] 2022-06-14 14:13
happy to provide more debug info or test things, just point me at what/where/how 😅

**Comment by mjbvz** [comment] 2022-06-14 17:49
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by bboyle** [comment] 2022-06-15 00:42
@mjbvz not seeing any typescript warnings in the insiders build

**Comment by HarmonyCB** [comment] 2022-06-15 08:56
I'll try this now too :)

**Comment by HarmonyCB** [comment] 2022-06-15 09:11
![image](https://user-images.githubusercontent.com/56916834/173790063-4f6f02df-9384-468c-8336-ede9be19c2d2.png)

![image](https://user-images.githubusercontent.com/56916834/173790166-52e437d5-e5fa-452d-920a-d5a54a61880d.png)

Yes it still happens for me in the insiders build. First screenshot is after it crashed and reloaded, second is my about page, let me know if you need more details - also sent "the authors" the crash dump.

**Comment by HarmonyCB** [comment] 2022-06-15 09:28
It also opened about 10 of these tabs after crashing in case that's useful
![image](https://user-images.githubusercontent.com/56916834/173794240-c40a2aae-0553-42b0-b963-139037eb9c45.png)

**Comment by HarmonyCB** [comment] 2022-06-15 09:29
like I said, seems somehow related to jest as it only SEEMS to happen for me on projects that are using jest for unit testing, but that could be a red-herring.

**Comment by bboyle** [comment] 2022-06-15 13:41
I went back to standard VSCode and disabled all extensions and that was good. I enabled Wallaby and Angular Language Service extensions and it's still be fine. I am using jest, but I have not enabled the jest extension.

**Comment by mjbvz** [comment] 2022-06-15 16:56
Thanks for checking. Closing this as caused by extension based on these comments (it's likely vscode-typescript-vue-plugin)

**Closed by mjbvz** 2022-06-15 16:56 UTC
Labels: needs more info

**Comment by HarmonyCB** [comment] 2022-06-16 08:20
Did you even read the comments? Bloody hell, do I have to re-open ANOTHER ticket on this? FFS

**Comment by HarmonyCB** [comment] 2022-06-16 08:22
I literally spent a bunch of time following your instructions, have NO plugins and it's still crashing in tsserver.ts in insider buildc any you close it? I'll make my own ticket and link to the multitude on this topic already :angry:
