### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by sardorocket** [Microsoft/vscode#50091] opened 2018-05-18 09:25 UTC
- VSCode Version: Version 1.23.1 (1.23.1) : d0182c3417d225529c6d5ad24b7572815d0de9ac
- OS Version: macOS 10.13.4 (17E202)

Steps to Reproduce:

1. Install support for any language (eg. TypeScript) from welcome screen (customise)
2. After installation you will see error message

<img width="479" alt="screen shot 2018-05-18 at 11 21 59" src="https://user-images.githubusercontent.com/15870134/40227246-3705fa64-5a8e-11e8-8a2a-8b9ee1c0d3a7.png">

**Comment by sandy081** [comment] 2018-05-22 08:34
Duplicate of #47550

**Closed** 2018-05-22 08:34 UTC
Labels: *duplicate
