### ISSUE TITLE
Collapsing XML Elements Fails to Hide Multiline Text

### ISSUE THREAD

**Issue by capavanni** [Microsoft/vscode#56141] opened 2018-08-10 10:27 UTC
- VSCode Version:

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

- OS Version:

Windows10

Steps to Reproduce:

1. Paste in following text and save as a .XML file, or set the content type to XML in the bottom right corner. (GitHub seems to mess up the formatting, here is a Gist https://gist.github.com/capavanni/382c98c9366ffd458acebd3b50c505d7 )

<?xml version="1.0" encoding="UTF-8"?>
<MyRootElement>
  <NestedElement>
    <AndAnother>
      <data><![CDATA[The
Quick
Brown
Fox
Jumped
Over
The
Lazy
Dog

]]></data>
    </AndAnother>
  </NestedElement>
</MyRootElement>

2. Collapse all elements with Ctrl+K Ctrl+0, or by clicking along the side.

3. You should know see the the XML is collapsed to the highest level elements, bar the text starting from "Quick".

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2018-09-14 07:26
duplicate of #46200.

**Closed** 2018-09-17 09:11 UTC
Labels: editor, editor-folding
