### ISSUE TITLE
 Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20080] opened 2017-02-06 21:09 UTC
Issue Id: <b>a876e3bc-590d-7979-433c-32d5fa6b1c27</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />TypeError: Cannot convert undefined or null to object<br />[/vs/platform/configuration/common/model.ts#L113:16 (keys)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/platform/configuration/common/model.ts#L113:16 (keys))<br />[/vs/workbench/services/configuration/common/model.ts#L82:36 (keys)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/configuration/common/model.ts#L82:36 (keys))<br />    at Array.forEach (native)<br />[/vs/workbench/services/configuration/common/model.ts#L80:52 (forEach)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/configuration/common/model.ts#L80:52 (forEach))<br />    at Array.forEach (native)<br />[/vs/workbench/services/configuration/common/model.ts#L79:21 (forEach)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/configuration/common/model.ts#L79:21 (forEach))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L178:41 (keys)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/configuration/node/configurationService.ts#L178:41 (keys))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L184:22 (keys)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/configuration/node/configurationService.ts#L184:22 (keys))<br />[/vs/workbench/api/node/mainThreadConfiguration.ts#L29:58 (values)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/mainThreadConfiguration.ts#L29:58 (values))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />

**Comment by kieferrm** [comment] 2017-02-06 21:10
1400 occurrences since 1.9.

**Comment by sandy081** [comment] 2017-02-07 08:00
Duplicate of #19773

**Closed by sandy081** 2017-02-07 08:00 UTC
