### ISSUE TITLE
string literals `` are not collapsed in editor

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#10045] opened 2016-08-02 16:22 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (e3758d2cdaae78082a08a45ae28ea1bed5f47e8c, 2016-07-29T18:41:58.915Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. write a string literal like
        let content =
`import React, { Component} from 'react';
import './${name}.css';
class ${name} extends Component {
    render() {
        return (
            <div className="${name}">
                main Component
            </div>
        );
    }
}

export default ${name};`

the editor does not recognize the string literal for collapsing it, 
instead it collapses on the line with class. 
this is also fine but it should recognize that it is a string template.

even worse the collapse mechanisme outside also seems to be mismatched then.

**Comment by aeschli** [comment] 2016-08-02 18:45
duplicate of #6294.
Note that the current folding strategy is based purely on indentation and is not aware of language features such as string literals. We have #3422 as the issue to support language aware folding.

**Closed by aeschli** 2016-08-02 18:45 UTC
Labels: folding
