### ISSUE TITLE
Outputs in VSCode Terminal inserted into or attached to end of startup command instead of displayed separately

### ISSUE THREAD

**Issue by Lumin-exdo** [microsoft/vscode#218253] opened 2024-06-26 07:48 UTC
![image](https://github.com/microsoft/vscode/assets/119757608/2d96b7bc-dd4e-401c-971f-2a76819c0e0a)
![image](https://github.com/microsoft/vscode/assets/119757608/56838caf-adc9-41da-82a0-815595dd70bf)
"a=0" and "10" was my result.
But after restoring the size of vscode window and maximize it again, the format automatically changes to normal as below:
[image](https://github.com/microsoft/vscode/assets/119757608/066b02c9-30d5-43b2-9c48-f29db9e0a0df)
I am using the 1.89.1 version. There is only the necessary settings.json which is generated automatically in my vscode.

**Comment by Lumin-exdo** [comment] 2024-06-27 12:34
@meganrogge Could you reproduce the problem I described on your terminal? I prefer to print the results to the terminal rather than print separately.

**Comment by meganrogge** [comment] 2024-07-08 15:42
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-12-10 13:24 UTC
Labels: upstream, windows, terminal-conpty
