### ISSUE TITLE
[JS] Auto quote close is not working properly when import package with autocomplete

### ISSUE THREAD

**Issue by BrunoQuaresma** [microsoft/vscode#88567] opened 2020-01-13 16:54 UTC
When I import a package the quote is not closing automatically. When I press `space` two quotes are inserted.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3165839/72275072-fe776880-360b-11ea-876b-127856399c53.gif)

Info:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by BrunoQuaresma** [comment] 2020-01-17 13:44
@mjbvz the issue persists even when I used VS Code insiders with all extensions disabled and no custom preferences.

**Comment by BrunoQuaresma** [comment] 2020-01-17 13:48
Extra info: I tried to use a diff keyboard settings US-international and Brazilian - Pro and the issue is the same.

**Comment by BrunoQuaresma** [comment] 2020-01-17 13:52
Ok, this bug is not happen when I use US keyboard.

<img width="252" alt="Screen Shot 2020-01-17 at 10 51 34" src="https://user-images.githubusercontent.com/3165839/72617301-6af9ac80-3917-11ea-9406-20b58df8fc60.png">

**Comment by mjbvz** [comment] 2020-01-17 16:26
@alexdima I think this is a generic issue with input on different keyboard layouts. Let me if you think this is js/ts specific

**Comment by alexdima** [comment] 2020-01-17 21:12
I believe the root cause is that suggestion items are not recomputed. Clear steps since the original gif was not obvious to me:
* switch keyboard layout to US International
* in a nodejs project (such that you get completions for `http`, `fs`, etc)
* type `import * as http from `
* press `'`
* (this enters accent composition mode)
* (the editor emits `onWillType`/`onDidType` events)
* completions are computed and presented
* press `<SPACE>`
* (this leaves accent composition mode)
* (the editor goes through the `replacePreviousChar` code path and I don't think it emits `onWillType`/`onDidType`, which is somewhat correct)
* I believe the completion items are not recomputed and the old ones are used
* accepting a suggestion will result in overwriting the second `'`.

@jrieken Can you please confirm this is what is going on? There is no selection change, just a document content change in this case. LMK if we need more editor API / events to cover this case.

**Comment by BrunoQuaresma** [comment] 2020-01-17 21:25
Basically what I do is:
- Open quote
- Start to type the package
- Auto complete is displayed
- I select the option and press enter
- When I press enter the last quote disappeared
- So I press space to see if the auto close works but when I do that two quotes are inserted.

I noticed this issue for keyboards layout where to put special characters like ç, á,â you have to use the opt key.

It happens to Brazilian Pro and US International on Mac.

**Comment by jrieken** [comment] 2020-01-20 08:29
Yeah, this is because we insert the item with `overwriteAfter: 1`. We do that because the second quote gets inserted while IntelliSense is active. This is the consequence or, fix for https://github.com/microsoft/vscode/issues/26012 (https://github.com/microsoft/vscode/commit/edcae85fd6a16807183ed2c8582c2d8cceace224) and that use-case might be happening more often. 

<img width="1145" alt="Screenshot 2020-01-20 at 09 22 16" src="https://user-images.githubusercontent.com/1794099/72710013-6aa32080-3b66-11ea-966f-8243c76a1afd.png">

@alexdima I am not sure how the editor can help me here.... Maybe we can know if/why extra characters have been inserted, e.g via auto bracket insertion or "from the keyboard" but I can see this being wrong in both cases...

**Comment by alexdima** [comment] 2020-01-22 16:17
@jrieken and I have agreed that this is caused by the composition end event currently working as `willCompositionEnd`. Changing the event to be `didCompositionEnd` means that the suggest model receives it after the auto-closing quote happened, and it will retrigger computation, making everything work OK.

**Closed** 2020-01-22 16:18 UTC
Labels: bug, suggest
