### ISSUE TITLE
Source control. Differences compare window freezes on a big file.

### ISSUE THREAD

**Issue by larssb** [Microsoft/vscode#56368] opened 2018-08-14 14:34 UTC
Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

----------

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

Issue Type: <b>Bug</b>

This file > https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1 freezes the VS Code source control differences compare window.

- VS Code version > 1.26.0

Error:
- I just get a "The window is no longer responding" prompt.
--> If I choose to click on "Reopen" the same issues occurs again.
- The error is repoducible every time I click on the file to see the changes in the source control window.

Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.43GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.30
Gradle|caz|1.1.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
python|don|0.7.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-npm-script|eg2|0.3.5
gitattributes|has|0.4.1
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vscode-docker|Pet|0.1.0
project-snippets|reb|0.5.0
java|red|0.29.0
vscode-icons|rob|7.25.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
gitblame|wad|2.4.4

</details>

**Comment by larssb** [comment] 2018-08-14 18:05
This happens on my Windows7 x64 client and on MacOS v10.13.6 (Beta).

**Comment by sandy081** [comment] 2018-08-15 10:26
Just opening the file hangs VS Code and I can confirm that this is not happening in 1.25 release

**Comment by aeschli** [comment] 2018-08-15 16:44
duplicate of #56430

**Closed by aeschli** 2018-08-15 16:44 UTC
Labels: candidate, freeze-slow-crash, new release
