### ISSUE TITLE
Cannot open .ipynb

### ISSUE THREAD

**Issue by jkrygel** [microsoft/vscode#106587] opened 2020-09-13 13:42 UTC
I'm using the latest release of vscode and it's python extension, and can no longer open .ipynb files. There are no issues with the files themselves, I work on them in jupyter notebook now. 
VScode just continuously "loads" when I try to open one of these files, that's all I need to do to reproduce the problem.

**Comment by gjsjohnmurray** [comment] 2020-09-13 14:43
Probably duplicate of #106534 and #106547

**Comment by rchiodo** [comment] 2020-09-14 17:13
It is mentioned in #106547 but this issue is not the same as the URI problem.

Root cause seems to be a rendering issue.
See the discussion here:
https://github.com/microsoft/vscode-python/issues/13901

**Comment by rchiodo** [comment] 2020-09-14 17:19
![maximize](https://user-images.githubusercontent.com/19672699/93117472-c54c3800-f673-11ea-8d4b-ffaad96e73b1.gif)

**Comment by rchiodo** [comment] 2020-09-14 19:31
This may also require this setting here to be set:
```json
    "python.experiments.optInto": [
        "CustomEditorSupport - experiment"
    ],
```

**Comment by rchiodo** [comment] 2020-09-14 19:31
That setting enables the usage of the custom editor API. This experiment was enabled by mistake on Friday 9/10.

**Comment by rebornix** [comment] 2020-09-24 18:05
@rchiodo what's the recommended fix/workaround for this issue?

**Comment by rchiodo** [comment] 2020-09-24 18:22
This should have resolved itself? Are you still seeing the issue?

**Comment by rebornix** [comment] 2020-10-07 22:15
Closing as no update after two weeks.

**Closed** 2020-10-07 22:15 UTC
