### ISSUE TITLE
VS Code not opening from terminal.

### ISSUE THREAD

**Issue by iDCoded** [microsoft/vscode#142321] opened 2022-02-06 11:06 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.64.0`
- OS Version: `Windows 10 - 20H2 (OS Build 19042.1466)`

Extra VSCode information: 
```
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Open the terminal and `cd` to a directory
2. Use the command `code .` to open the entire directory in **VS Code**

Expected Result:
Open the directory in VS Code.

Bug: 
![terminal](https://user-images.githubusercontent.com/65074550/152677817-d55a7447-aca0-4029-ad95-d0e388f1076d.png)

```
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Extra Information:
Previously, I was able to open **VS Code** from the terminal using the `code .` command. 
But all of a sudden, without making any changes, this command has stopped working and displaying the error.

**Comment by iDCoded** [comment] 2022-02-06 11:27
**Update** 

I was able to fix this issue by re-installing **VS Code**.

![installer](https://user-images.githubusercontent.com/65074550/152678634-9e85f205-f699-47c4-9755-9eb321dd971b.png)
 
But, I would still like to know the reason behind **VS Code** not opening from terminal even when it previously worked.

**Comment by miikaforma** [comment] 2022-02-07 08:24
I got the same issue. Got it working by copying the `.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli/code` to `.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code`.

**Comment by Eynorey** [comment] 2022-02-07 09:03
> I got the same issue. Got it working by copying the .vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli/code to .vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code.

I tried that, now it's complaining about `.vscode-server-server/bin/node: not found` 😅

**Comment by morkovka1337** [comment] 2022-02-07 10:51
I confirm the issue. I have a working setup of macOS laptop connecting to remote ubuntu desktop. After I have updated today to 1.64, I'm no longer able to open anything from the terminal using `code <file>` or `code <folder>`.

**Comment by iDCoded** [comment] 2022-02-07 13:38
> I confirm the issue. I have a working setup of macOS laptop connecting to remote ubuntu desktop. After I have updated today to 1.64, I'm no longer able to open anything from the terminal using `code <file>` or `code <folder>`.
> 
> Though I did not try reinstalling code yet.

Yes, the bug seems to occur after updating to `1.64`.
The only fix that seems to be working is just reinstalling **VSCode**.

**Comment by morkovka1337** [comment] 2022-02-07 14:48
I've tried reinstalling VS code both host and client, but it did not work for me. It only worked when I installed older (1.63) release of the VS code client version.
My client OS is MacOS Monterrey (M1), host is Ubuntu 18.04 x64.

**Comment by Tyriar** [comment] 2022-02-07 14:55
The reports are a bit all over the place, some seem like windows local windows, some are remote.

@aeschli `.vscode-server-server` duplicate `-server`?

**Comment by Eynorey** [comment] 2022-02-07 15:31
Here's what happened:
Setup:  Windows 10 21H1, WSL 2 running Ubuntu 20.04 LTS
1. VSCode auto-updated when I closed it (Windows UI).
2. running `code .` from WSL2 lead to it downloading + extracting version `5554b12acf27056905806867f251c859323ff7e9` of the remote, then failed with `~/.vscode-server-server/bin/code: not found`
3. Then I copied `~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli/code` to `~/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code`, after which it failed with `~/.vscode-server-server/bin/node: not found`
4. Then I opened VSCode regularly through Windows, and opening WSL directories/files from there works fine
5. **After that**, opening directories from the cli via `code ` works again

**Comment by aeschli** [comment] 2022-02-07 15:43
After the update it's important that users also update to the matching Remote-WSL extension: v0.64.2.

This happens automatically but might require a restart of VS Code.  
`.vscode-server-server` is caused by running an old version of Remote-WSL with VS code 1.64.
It can be deleted.

**Comment by aeschli** [comment] 2022-02-07 15:52
@morkovka1337 Can you explain more what your setup is? Are you using the Remote SSH extension?

**Comment by FindDefinition** [comment] 2022-02-08 04:49
same issue here. I access remote ubuntu 20.04 container in ubuntu 20.04 desktop via vscode remote-ssh and encounter this issue after upgrade vscode to 1.64. the Remote-SSH plugin version is 0.70.0.

**Comment by morkovka1337** [comment] 2022-02-08 06:02
> @morkovka1337 Can you explain more what your setup is? Are you using the Remote SSH extension?

Yes, I'm using remote-SSH extension v 0.70.0.

**Comment by aeschli** [comment] 2022-02-08 09:16
The issue with Remote-SSH is https://github.com/microsoft/vscode-remote-release/issues/6289.
The restored integrated terminal does not contain the new PATH. 

The workaround is to close the integrated terminal (use the trashcan in the view toolbar) and open a new one.
`env | grep remote-cli` should then return the PATH.

**Comment by aeschli** [comment] 2022-02-08 20:09
@morkovka1337 I think the problem is that you have `"terminal.integrated.inheritEnv"; false` configured. That doesn't go well together with the `code` command in the integrated terminal in remote windows. Can you set it to true?

**Comment by morkovka1337** [comment] 2022-02-09 07:15
> @morkovka1337 I think the problem is that you have `"terminal.integrated.inheritEnv"; false` configured. That doesn't go well together with the `code` command in the integrated terminal in remote windows. Can you set it to true?

@aeschli Yes, seems like this solves the problem, thank you!

**Comment by fluentmoheshwar** [comment] 2022-09-17 09:47
VS code isn't in path.

**Closed** 2022-09-19 12:05 UTC
Labels: workbench-cli
