### ISSUE TITLE
Bug in <script></script> tag

### ISSUE THREAD

**Issue by LaFlameMusa** [microsoft/vscode#118374] opened 2021-03-07 16:09 UTC
Issue Type: Bug

After writing the <script> </ script tag in HTML and putting any sign without closing the tag to the end, a bug occurs.
The sign starts generating by itself without stopping! 
Example: <script></script. = it generates points without stopping
or <script></scriptkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk 
like that.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.67GB free)|
|Process Argv|--crash-reporter-id 0fd63344-4261-4d40-b2d0-c953297c2ad7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
vscode-html-css|ecm|1.10.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
code-beautifier|mic|2.3.3
theme-monokai-pro-vscode|mon|1.1.18
easy-less|mrc|1.7.2
vscode-language-pack-ru|MS-|1.54.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
vscode-icons|vsc|11.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by LaFlameMusa** [comment] 2021-03-07 16:10
Баг до сих пор не исправлен.

**Comment by LaFlameMusa** [comment] 2021-03-07 17:22
I wrote description in English language.

**Comment by LaFlameMusa** [comment] 2021-03-07 17:23
I hope you got it, and if you need some more info, let me know.

**Comment by carljohnesan** [comment] 2021-03-07 17:34
> Баг до сих пор не исправлен.

Are you stupid? Though we're working all around the globe what's the international language? It's english. Change issue title

**Comment by aeschli** [comment] 2021-03-08 10:09
Does this reproduce with all extensions disabled? You can do that with the command `Developer: Run with Extensions Disabled`

**Comment by LaFlameMusa** [comment] 2021-03-08 16:02
> Does this reproduce with all extensions disabled? You can do that with the command `Developer: Run with Extensions Disabled`

i will try

**Comment by LaFlameMusa** [comment] 2021-03-08 16:02
> > Баг до сих пор не исправлен.
> 
> Are you stupid? Though we're working all around the globe what's the international language? It's english. Change issue title

sorry

**Comment by aeschli** [comment] 2021-03-08 16:32
duplicate of #117245

**Closed by aeschli** 2021-03-08 16:32 UTC
Labels: *english-please, needs more info, new release, translation-required-russian
