### ISSUE TITLE
Auth should ignore/drop extensions that aren't available anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117356] opened 2021-02-23 10:17 UTC
Testing #117290

Checkout the confusing screen capture below. For testing #117290 I have renamed my extension from `test-secrets` to `test-secrets2` (only id, not display name and hence the funny screen shot). The problem is that the auth logic still knows about the `test-secrets` extension although it doesn't exist anymore. I would assume the same happens in the real world when uninstalling an extension and IMO the auth-data should then be dropped

<img width="725" alt="Screenshot 2021-02-23 at 11 14 49" src="https://user-images.githubusercontent.com/1794099/108829411-71e9f880-75c8-11eb-9a56-a507ec6c84d4.png">

**Comment by TylerLeonhardt** [comment] 2021-12-08 00:44
duplicate of #123817

**Closed by TylerLeonhardt** 2021-12-08 00:44 UTC
Labels: feature-request, authentication
