### ISSUE TITLE
Automatically enable extension if installed from CLI

### ISSUE THREAD

**Issue by danixeee** [Microsoft/vscode#71491] opened 2019-03-30 21:00 UTC
I like the new feature where we do not have to reload a VS Code window when new extension is installed, however if extension is installed using _cli_ command `code --install-extensions test.vsix` it requires reloading to take the effect.

I am wondering if it is possible to accomplish the same thing from _cli_, _if VS Code instance is opened_?

Are there some other ways to install a new extension programmatically and to use them without reloading a window?

Thanks in advance.

**Comment by sandy081** [comment] 2019-04-01 07:47
Duplicate of https://github.com/Microsoft/vscode/issues/38607

**Closed** 2019-04-01 07:47 UTC
Labels: *duplicate, extensions
