### ISSUE TITLE
No auto scroll to where is typing when there's multi selection

### ISSUE THREAD

**Issue by AmirSavand** [Microsoft/vscode#28906] opened 2017-06-16 18:32 UTC
Multi select your code, scroll way down, start typing, no auto scroll/focus where you're typing.

```
OS: Windows 10
VS Code: 1.13.1
```

**Comment by alexandrudima** [comment] 2017-11-27 09:22
Duplicate of #6995

**Closed by alexandrudima** 2017-11-27 09:22 UTC
Labels: editor-multicursor
