### ISSUE TITLE
Terminal mouse handling doesn't allow click+drag

### ISSUE THREAD

**Issue by johan-boule** [microsoft/vscode#225208] opened 2024-08-09 02:34 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: MSDOS / Windows_NT x64 10.0.19045

Steps to Reproduce:

1. In the terminal, start an application with mouse support, like `tmux`
2. Click with the mouse, keep the button down, and drag the mouse

The tmux application sees a simple mouse click, while instead, it should select a text region within tmux's own clipboard.

**Comment by Tyriar** [comment] 2024-12-11 20:39
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-11 20:39 UTC
Labels: windows, confirmation-pending, terminal-input
