### ISSUE TITLE
touchbar_partfunction_error

### ISSUE THREAD

**Issue by Curry951015** [Microsoft/vscode#65046] opened 2018-12-14 03:47 UTC
Issue Type: <b>Bug</b>

When I tried my touchbar to debug, I failed. Even after Vscode was rebuilt , touchbar didnt work on debug. But other functions about touchbar worked well. In addition, touchbar on other apps worked as well. I hope u could tell me how to fix it.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.4
sftp|lix|1.8.3
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.0

</details>

**Comment by bpasero** [comment] 2018-12-17 06:02
@Curry951015 where did you see `touchbar_partfunction_error`?

**Comment by Curry951015** [comment] 2018-12-17 08:42
Well, I didnt see `touchbar_partfunction_error`. Thats just a name of that problem.

**Comment by bpasero** [comment] 2018-12-17 09:36
@Curry951015 to be clear, you talk about the macOS touchbar on top of the keyboard?

**Comment by Bill-Y-Mason** [comment] 2018-12-18 05:50
Experiencing the same issue here. Clicking on the debug button on the Touch Bar, which, of course,  is the display strip on top of the Macbook keyboard, I am prompted with a command palette to choose launch configuration to set up, even though a configuration already exists, and then nothing happens (debug doesn't start). The dedicated debug sidebar works fine though.

**Comment by HenryLiangzy** [comment] 2018-12-18 07:01
@Bill-Y-Mason also same issue, I think maybe the system update problem, I can use the Touch Bar to debug before I update the system. Since I install that Mojave update, it seems could not work well, my current system version is  10.14.2

**Comment by Bill-Y-Mason** [comment] 2018-12-18 07:10
@HenryLiangzy I don't think that's the issue. If memory serves me correctly, VS Code 1.29.1 worked fine with Mojave 10.14.2.

**Comment by bpasero** [comment] 2018-12-18 09:30
@isidorn I believe this fix will be part of our recovery release

**Comment by isidorn** [comment] 2018-12-18 09:35
Yes, this is a duplicate of https://github.com/Microsoft/vscode/issues/64450

**Closed by isidorn** 2018-12-18 09:35 UTC
Labels: debug
