### ISSUE TITLE
[Insiders] Changing cursor position with CTRL + RIGHT does not scroll window

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#23525] opened 2017-03-29 07:34 UTC
- VSCode Version: 1.11.0-insider (Commit a35c7da7b)
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

1. Have a text on one line that does not fit the current window horizontally so that you have to scroll left and right to navigate in that line
2. If you use <kbd>CTRL</kbd> + <kbd>RIGHT</kbd>, the cursor will jump to the start of each word but the window will not scroll with the cursor, so that the cursor position will be invisible after a short time.
3. If you use only the <kbd>RIGHT</kbd> key, the window will scroll with the cursor, so that is always visible

A picture (or a video) says more than words:
![scrolling problem](https://cloud.githubusercontent.com/assets/4070008/24443273/46f2fac6-1462-11e7-9a68-d27118fb6a7f.gif)

The Visual Studio Code instance has been started using the `--disable-extensions` parameter, so all installed extensions where deactivated.

**Comment by alexandrudima** [comment] 2017-03-29 19:11
Duplicate of #23354

**Closed by alexandrudima** 2017-03-29 19:11 UTC
