### ISSUE TITLE
Column selection paste is broken

### ISSUE THREAD

**Issue by brantPTS** [microsoft/vscode#96707] opened 2020-04-30 15:16 UTC
Issue Type: <b>Bug</b>

If you copy a column selection (shift+alt select) and try to paste it as a column selection (the primary use case for this), it does not paste in a column fashion, as it works it every other editor I have used (such as Notepad++ or Visual Studio). 

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.42GB free)|
|Process Argv|D:\local\PyTorchTesting\PyTorchTest1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.4.76186

</details>

**Comment by IllusionMH** [comment] 2020-04-30 15:51
Looks like duplicate of #5940

Could you check it and add more examples here if they are missing from that discussion please.

**Comment by brantPTS** [comment] 2020-04-30 20:53
@IllusionMH @alexdima @alexr00 

Now I see the problem - column copy paste can actually work, but only in the following case: 

1.  Make a column selection and copy text
2. Make a column selection of identical height in the destination location i.e., if you copied 4 rows, you need to select 4 rows with column selection mode 
3. Paste while the equivalent row count cursor active

In every other editor I have used, you only need to place your cursor at the starting point of where you want the column paste to go, and it infers an equal-height column select insert cursor.  If you try to do this in VS Code, it pastes the column selection as a normal selection. So the following scenario fails: 

1.  Make a column selection and copy text
2. Insert cursor where you want the column text to be inserted
3. Paste text

This does not work. You will end up with something like this (I tried copying a column of "e"'s to fix "Misspelld"):

Misspelle
e
e
ed text
Misspelld text
Misspelld text
Misspelld text

**Comment by alexdima** [comment] 2020-05-04 07:17
Let's track in #5940

**Closed by alexdima** 2020-05-04 07:17 UTC
