### ISSUE TITLE
Latest VS Code (1.53.0) breaks debug configs

### ISSUE THREAD

**Issue by TCourtneyOwen** [microsoft/vscode#115916] opened 2021-02-05 18:48 UTC
We noticed after upgrading to VS Code 1.53.0 that our launch.json debug configs no longer work.  Our debug configs invoke tasks defined in tasks.json.

Our launch.json config is as follows:

    {
      "name": "Excel Desktop (Edge Chromium)",
      "type": "edge",
      "request": "attach",
      "useWebView": "advanced",
      "port": 9229,
      "timeout": 600000,
      "webRoot": "${workspaceRoot}",
      "preLaunchTask": "Debug: Excel Desktop",
      "postDebugTask": "Stop Debug"
    },

And the prelaunchTask is defined in tasks.json as follows:

    {
      "label": "Debug: Excel Desktop",
      "type": "npm",
      "script": "start:desktop -- --app excel",
      "presentation": {
        "clear": true,
        "panel": "dedicated",
      },
      "problemMatcher": []
    },

When we try to initiate the Excel Desktop (Edge Chromium) debug config, we get the following error:

> Executing task: npm run "start:desktop -- --app excel" <

npm ERR! missing script: start:desktop -- --app excel

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cowen\AppData\Roaming\npm-cache\_logs\2021-02-05T00_02_33_429Z-debug.log
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c npm run "start:desktop -- --app excel"" terminated with exit code: 1.

The problem doesn't look to be with the task in task.json as we can invoke this separately with no problems.  Rather it appears to be an issue with the interaction between our launch.json config and tasks.json, presumably with the preLaunchTask option in launch.json.

We use these debug configs extensively in our project templates for Microsoft Office Add-in projects.  These templates are used by many, many customers of Microsoft so we will surely hear from some of them in the near future when they encounter this issue.

I work on the Microsoft Office Platform Extensibility team, so please feel free to reach out to me for more information.

Thanks,

Courtney Owen
SWE, OPX Team

**Comment by roblourens** [comment] 2021-02-05 19:08
Sounds related to https://github.com/microsoft/vscode/issues/115876

**Comment by roblourens** [comment] 2021-02-05 19:14
Unless it's different because

> The problem doesn't look to be with the task in task.json as we can invoke this separately with no problems. Rather it appears to be an issue with the interaction between our launch.json config and tasks.json, presumably with the preLaunchTask option in launch.json.

**Comment by xmedeko** [comment] 2021-02-06 20:38
Try to convert task type `npm` to `shell`, see https://github.com/microsoft/vscode/issues/115876#issuecomment-774539947

**Comment by alexr00** [comment] 2021-02-08 13:11
This is indeed a duplicate of https://github.com/microsoft/vscode/issues/115876

**Closed** 2021-02-08 13:11 UTC
Labels: *duplicate
