### ISSUE TITLE
Typescript highlighter broken if return type ends with a digit

### ISSUE THREAD

**Issue by giniedp** [Microsoft/vscode#9812] opened 2016-07-26 19:26 UTC
- VSCode Version: 1.3.1
- OS Version: OSX 10.10.5 

Steps to Reproduce:

1. declare a new class
2. write an instance function that returns a type whose name ends with a digit

`
    get texel():IVec2 { 
      return { x: 1.0 / this.width, y: 1.0 / this.height }
    }
`
The highlighting after the return type is broken.

**Comment by aeschli** [comment] 2016-07-27 10:02
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/188

**Closed by aeschli** 2016-07-27 10:02 UTC
Labels: typescript
