### ISSUE TITLE
Suggest Window wrong position

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#33115] opened 2017-08-24 22:31 UTC
- VSCode Version: 1.16 Insiders
- OS Version: macOS

Steps to Reproduce:
1. Type in the bottom of the document
2. Switch to another tab
3. Switch back
4. Scroll the window upwards, then type.

![suggest](https://user-images.githubusercontent.com/876920/29691714-25b4b14e-88e1-11e7-953f-d4caf3ad9d58.gif)

**Comment by ramya-rao-a** [comment] 2018-02-07 00:51
@rebornix I cannot repro. Do you still see this?

**Comment by ramya-rao-a** [comment] 2018-02-14 00:07
Though I cant get the same repro, here is another case

Use the below content in a css file
```
.foo {
  m
}

.bar {
  m
}
```

Trigger completions at `m` under `.foo`, you will see the suggest widget rightly positioned

![image](https://user-images.githubusercontent.com/16890566/36181052-dc709014-10d7-11e8-8ea6-da0235f20564.png)

Now presee escape, and take the cursor to the other `m` and trigger completions.

![image](https://user-images.githubusercontent.com/16890566/36181067-f74802f0-10d7-11e8-85f2-1640e8aa822e.png)

**Comment by ramya-rao-a** [comment] 2018-02-14 00:08
Fixed with https://github.com/Microsoft/vscode/commit/a8449c4f3b6cb96dee0d436a1f4661816aee0679

**Closed by ramya-rao-a** 2018-02-14 00:08 UTC
Labels: bug, suggest

**Comment by chrmarti** [comment] 2018-03-01 14:41
Cannot reproduce in 1.20.1. Any additional steps?

**Comment by ramya-rao-a** [comment] 2018-03-01 18:28
@chrmarti I can repro in 1.20.1 using the steps in https://github.com/Microsoft/vscode/issues/33115#issuecomment-365449153
