### ISSUE TITLE
Stick the directory name at the top of explorer if directory contains long list of sub directory or file causing overflow (Sticky Top)

### ISSUE THREAD

**Issue by ayushkumarbhadani** [microsoft/vscode#198584] opened 2023-11-18 08:22 UTC
Add a sticky feature to stick the directory at the top of the explorer so it will be easy to view the parent directory while scrolling through the subfolders or files inside. 

I have created an example in HTML and CSS for reference: [Link to codepen for reference](https://codepen.io/ayushkumarbhadani/pen/XWOVOYE)

Expected behaviour:
On expanding the directory, if the directory contains items more than scroll height then the directory should stick at the top so that the user can collapse it by clicking at the top. 

The idea came to my mind when I was scrolling through the node_modules directory and I had to scroll back all the way to the top to collapse the node_modules directory.

**Comment by gjsjohnmurray** [comment] 2023-11-18 14:29
/duplicate of https://github.com/microsoft/vscode/issues/161207

**Closed** 2023-11-18 14:30 UTC
Labels: *duplicate
