### ISSUE TITLE
[1.59.0] The terminal where a background task is running will be reused by another background task

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/vscode#130461] opened 2021-08-10 06:32 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.59.0
- OS Version: Windows 10

Steps to Reproduce:

1. `git clone https://github.com/kuojianlu/vscode-terminal-reused-issue.git`. Use VSCode to open it.
2. Click **Terminal** -> **Run Tasks...** -> **Start Apps**
3. Press **Ctrl+C** to terminate tasks **Run App 2** and **Run App 1**
![image](https://user-images.githubusercontent.com/37978464/128818845-52b14ef3-a2e2-4cde-82f2-970d55939e4b.png)
4. Kill (Delete) terminal **Run App 2**, **do not** kill (delete) **Run App 1**
![image](https://user-images.githubusercontent.com/37978464/128819094-390be5ca-903c-4590-b50e-56920e720a11.png)
5. Click **Terminal** -> **Run Tasks...** -> **Start Apps**
![image](https://user-images.githubusercontent.com/37978464/128819210-d138c785-8c44-4c0a-a876-8ce084ff944a.png)

**Comment by alexr00** [comment] 2021-08-11 07:56
I'm not able to reproduce this issue. Can you share any terminal related settings that you have set?

**Comment by kuojianlu** [comment] 2021-08-11 09:32
> Thanks for the sample repository! I'm not able to reproduce this issue. Can you share any terminal related settings that you have set?

Thanks for your quick reply. I suppose I do not have any special terminal settings. Did you do the step 4? I attach a gif screenshot screenshot here for your reference.

![screenshot](https://user-images.githubusercontent.com/37978464/129005304-fc757871-f44e-4b27-965e-7a66b05891ad.gif)

**Comment by alexr00** [comment] 2021-08-11 09:45
I can now repro. The npm install task failed in my setup, I had removed it. However, it's needed to repro the issue so I replaced it with an echo task.

**Comment by alexr00** [comment] 2021-08-11 09:54
Thanks for reporting this @kuojianlu. It has the same root cause as https://github.com/microsoft/vscode/issues/130277, so I will mark it as a duplicate of that issue.

**Closed** 2021-08-11 09:55 UTC
Labels: tasks, *duplicate
