### ISSUE TITLE
Visual Studio Code is no more compatible with Windows HD color

### ISSUE THREAD

**Issue by Anthony-Breneliere** [microsoft/vscode#93132] opened 2020-03-21 12:32 UTC
Some monitors like Samsung C32HG7x are too bright and require to use Windows HD color when using Windows Desktop (10 bits colors).

After upgrading from 1.41.x to 1.43.1

Steps to Reproduce:

1. Activate Windows HD color (10 bits color)
2. Launch Visual Studio Code. The Visual Studio Code windows is very dark, as if the SDR content appearance setting (in Windows 10 display settings) was set to zero. Some patches of the application displays with correct lightness. 

![20200321_124832](https://user-images.githubusercontent.com/6704165/77226397-5edcd600-6b78-11ea-89f1-3d643cf65da0.jpg)

**Comment by Anthony-Breneliere** [comment] 2020-03-21 12:48
I rolled back to 1.42.1 that does not have this issue.

**Comment by deepak1556** [comment] 2020-03-21 22:22
@Anthony-Breneliere this is a duplicate of https://github.com/microsoft/vscode/issues/88491 , please try the workaround mentioned in that issue and follow it for updates. I am merging the issues. Thanks!

**Closed by deepak1556** 2020-03-21 22:22 UTC
