### ISSUE TITLE
Unsure how edit sessions persist in list

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#156340] opened 2022-07-26 18:16 UTC
Testing #156211

- Stored 3 edit sessions in vscode.dev
- `Resume Edit Session` for one of them
- The selected edit session is removed from the Edit Sessions view
- If I resume another, that one is also removed, and the other session isn't added back
- I resume the third, and now there are no edit sessions listed in the Edit Sessions view

I had thought my edit sessions would persist in the list until I either committed the change or took some specific action to remove them. I thought there would be a way to jump between edit sessions to see which one I want to resume, similar to how I can jump between branches and they aren't deleted.

**Comment by joyceerhl** [comment] 2022-07-27 17:49
We delete edit sessions from the service after they have been resumed because we don't want to be storing them forever (storage is expensive). @andreamah also reported that this was unexpected https://github.com/microsoft/vscode/issues/153566, maybe we need some way to inform the user of this behavior.

**Comment by joyceerhl** [comment] 2022-07-27 17:50
Closing as duplicate of https://github.com/microsoft/vscode/issues/156368

**Closed by joyceerhl** 2022-07-27 17:50 UTC
