### ISSUE TITLE
Node.js can't autocomplete after update 0.10.10

### ISSUE THREAD

**Issue by qfdk** [Microsoft/vscode#3973] opened 2016-03-10 17:27 UTC
**Node.js** can't autocomplete after update 0.10.10, and i have  the `typings`...

If i try to user a new WS for test, __dirname can't underline to show me download it, and just reference works

**Comment by qfdk** [comment] 2016-03-10 17:28
![snip20160310_1](https://cloud.githubusercontent.com/assets/2404478/13678230/d980c40c-e6ed-11e5-9297-4ea2fb9fca6b.png)

**Comment by qfdk** [comment] 2016-03-10 17:28
but the vision 0.10.9 works, and it will update automatic .... i can;t lock it

**Comment by egamma** [comment] 2016-03-11 07:30
duplicate of https://github.com/Microsoft/vscode/issues/3936, work around is also provided in ths issue.

**Closed by egamma** 2016-03-11 07:30 UTC
