### ISSUE TITLE
VS Code 1.11.1 – Do not see Git repository

### ISSUE THREAD

**Issue by andrewmiko88** [Microsoft/vscode#24199] opened 2017-04-07 09:15 UTC
- VSCode Version: 1.11.1
- OS Version: Mac OSX 10.12.4

Steps to Reproduce:

1. Install latest update for VS Code
2. Reopen project with Git VCS

After latest update for VS Code, I can't use anymore Version Control tool in VS Code. It's not see that this project has Git.

I already tried to reinstall VS Code and updated Git – No success.

Any ideas? Thanks.

**Comment by andrewmiko88** [comment] 2017-04-07 09:20
Update:

I've created new folder and tried to clone project. Got an error like:
> command 'git.clone' not found

The VS Code seems that don't see Git executable in computer. Any thoughts why?

**Comment by joaomoreno** [comment] 2017-04-07 15:09
Can you take a screenshot of the error, or what you observe?

**Comment by VinceFanZ** [comment] 2017-04-08 06:22
<img width="1380" alt="wx20170408-141800 2x" src="https://cloud.githubusercontent.com/assets/7631809/24826345/a979a17a-1c66-11e7-9df2-65151a9e8f91.png">


same～～～

**Comment by Easy-wei** [comment] 2017-04-08 15:10
最新版的vscode的GIT功能崩了吗？我昨天系统和vscode同时更新了，结果powshell的位置莫名其妙错位，而且，git功能崩了，我以为全是windows10创意者更新的锅，看来各背一个啊。

**Comment by BJBigler** [comment] 2017-04-08 18:17
I see similar behavior on MacOS Sierra 10.12.4. Setting these git lines in settings.json as here stops the problem:

 "git.enabled": false,
 "git.autofetch": false

<img width="472" alt="screen shot 2017-04-07 at 21 42 48" src="https://cloud.githubusercontent.com/assets/15526337/24831350/e0ab60b2-1c65-11e7-8b71-2e667f88497a.png">

**Comment by andrewmiko88** [comment] 2017-04-10 07:55
@joaomoreno 

Here is Git settings:
`
    // Whether git is enabled
    "git.enabled": true,

    // Path to the git executable
    "git.path": "/usr/local/bin/git",

    // Whether auto refreshing is enabled
    "git.autorefresh": true,

    // Whether auto fetching is enabled
    "git.autofetch": true,

    // Confirm before synchronizing git repositories
    "git.confirmSync": true,

    // Controls the git badge counter
    "git.countBadge": "all",

    // Controls what type of branches are listed
    "git.checkoutType": "all",
`
And screenshot of problem:
[https://ibin.co/w800/3IZF2KiW6dYK.png](url)

**Comment by joaomoreno** [comment] 2017-04-10 08:54
@andrewmiko88 Can you check the `Developer Tools` for any errors?

**Comment by andrewmiko88** [comment] 2017-04-11 07:50
![screen shot 2017-04-11 at 10 49 36](https://cloud.githubusercontent.com/assets/5430147/24898172/9aada58e-1ea4-11e7-8472-e52979a386c2.png)

Only this one.

**Comment by joaomoreno** [comment] 2017-04-11 07:52
OK that's helpful, thanks! Duplicate of #24431

**Comment by joaomoreno** [comment] 2017-04-11 07:53
For now, you can run `SCM: Disable Preview SCM` as a workaround until next month.

**Closed by joaomoreno** 2017-04-11 07:52 UTC
Labels: needs more info

**Comment by andrewmiko88** [comment] 2017-04-11 09:52
> For now, you can run `SCM: Disable Preview SCM` as a workaround until next month.
Worked for me, thanks!

**Comment by Gerhard-Herbert** [comment] 2017-04-27 06:40
I had the same problem. The workarond worked for me as well.

**Comment by joaomoreno** [comment] 2017-04-27 06:49
@andrewmiko88 @Gerhard-Herbert Please try out our [insider release](https://code.visualstudio.com/insiders) without disabling the Preview SCM and let me know if all works there.

**Comment by Gerhard-Herbert** [comment] 2017-04-27 09:26
I tried it with the inseder release. Works well, thanks.

**Comment by dsome13** [comment] 2017-10-06 10:31
Thanks @qcha0s - that was my issue
