### ISSUE TITLE
New Sticky Scroll doesn't work properly

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#157293] opened 2022-08-05 16:56 UTC
Type: <b>Bug</b>

When using the new Sticky Scroll with a .NET API project, scrolling in a controller will only show any attributes as the "sticky" heading - [ApiController] - [HttpPost], etc. 

![image](https://user-images.githubusercontent.com/13488/183124906-333dc373-e47c-4c20-b0cb-ed8af11e80b5.png)

![image](https://user-images.githubusercontent.com/13488/183125026-c7a21206-2aaa-4f66-b230-094fe3873e73.png)

VS Code version: Code - Insiders 1.71.0-insider (73fd3f11032e7b83c2ae011b5516e6ddd19e3db2, 2022-08-05T07:36:58.753Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.52GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.1
ng-template|Ang|14.1.0
sync-scroll|dqi|1.3.0
vs-code-xml-format|fab|0.1.5
csharpextensions|kre|1.7.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.5
vscode-azurestorage|ms-|0.14.2
csharp|ms-|1.25.0
azure-account|ms-|0.11.1
hexeditor|ms-|1.9.8
material-icon-theme|PKi|4.19.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.17.1
hl7tools|Rob|1.14.2
msbuild-project-tools|tin|0.4.4
vscodeintellicode|Vis|1.2.22
jwt-debugger|yok|0.4.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by IllusionMH** [comment] 2022-08-05 21:19
Looks like duplicate of #157180, but not sure if devs would prefer that issue be for python only or for all languages

**Closed** 2022-08-08 19:15 UTC
Labels: editor-sticky-scroll
