### ISSUE TITLE
Saved files overwritten empty when HDD is full

### ISSUE THREAD

**Issue by dawesi** [Microsoft/vscode#72835] opened 2019-04-25 02:08 UTC
When the Hard Drive of a project becomes full, files save with NO content, but also with NO warning from VSC.

Fortunately it was only 3 files and 3 hours of work #sigh (only!) 

The only IDE on the planet that doesn't notify for this... then again it also doesn't support some well used standard brace intentations patterns also, so it's a B-grade editor  just on that level.

Get the basics right, then do fancy features... you just cost us half a day of work because you failed to implment basic file handling. Even notepad++ does this... VSC is beta... make it full version sometime soon please and cover off on IDE 101, before anything else... #bracingfail #fileiofail

**Comment by agiron123** [comment] 2019-04-25 02:26
I'm sorry that you had a bad experience with using VS Code when your hard drive was full. 

This sounds like an interesting problem to solve. To do so, let's get some steps to repro.
Couple questions that could be useful:
1. Operating system that you are using
2. Version of VS Code that you are currently using

If I were to try to reproduce this issue myself, here's what I would first try:
1. Create a windows VM with low hard drive space.
2. Install VS Code
3. Create and save a file

Doing a little bit of googling around, I found that there is a module called diskusage that we might be able to check out to find out more information about the hard drive of the computer that the user is on: https://www.npmjs.com/package/diskusage I still need to do some research on whether or not this works on electron.

Perhaps a naive solution here might be to check disk usage before saving a file and alerting the user that their disk space is low. Another solution would be to pre-emptively check every so often and alert the user when their disk space is low.

**Comment by bpasero** [comment] 2019-04-25 07:30
Duplicate of https://github.com/Microsoft/vscode/issues/34915

**Closed by bpasero** 2019-04-25 07:30 UTC
