### ISSUE TITLE
Bug in CSS with non standard RGB (RGBA)

### ISSUE THREAD

**Issue by kprkpr** [Microsoft/vscode#30603] opened 2017-07-13 10:40 UTC
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.11.9-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|1.4.3
shell-format|fox|1.0.0

---

Steps to Reproduce:

1. Open a CSS file
2. Insert a line like: 	"background-color: #db030399;" in a CSS style
Example:
div.errorF {
	background-color: #db030399;
	border: 2px solid red;
	border-radius: 0.5em;
	margin: 0.5em;
	padding-left: 1em;
	padding-right: 1em;
	display: inline-block;
}

Reproduces without extensions: Yes

VS Code says that this line excepts a value and invalids the rest of the block, and its a valid color with alpha

![captura de pantalla](https://user-images.githubusercontent.com/5132053/28162701-538e2526-67c8-11e7-81f6-60d71efd0c0b.png)

**Comment by chrmarti** [comment] 2017-07-13 15:15
Indeed: http://caniuse.com/#feat=css-rrggbbaa

**Comment by aeschli** [comment] 2017-07-17 01:12
duplicate of #7383

**Closed by aeschli** 2017-07-17 01:12 UTC
Labels: css-less-sass, new release
