### ISSUE TITLE
Copy paste files from native explorer to vscode

### ISSUE THREAD

**Issue by ninjaasmoke** [microsoft/vscode#89862] opened 2020-02-02 15:34 UTC
Issue Type: <b>Feature Request</b>

its impossible for me to paste files(like fonts into my flutter app), from a folder in the windows explorer.
i can drag and drop it but i have to create a different file and then drag and drop it

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment] 2020-02-03 13:23
This is a fair feature request however I believe there is a Chrome limtation which is preventing us from achieving this.
Thus assigning this to the backlog milestone

**Closed** 2020-05-19 11:38 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by starball5** [comment] 2023-02-10 03:45
Is this a duplicate of #130036 (subtask of #164)?
