### ISSUE TITLE
Can we get this request off the startup path, pretty pretty please

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#12672] opened 2016-09-26 19:43 UTC
Opening a folder when connected to VPN:

(Dev Tools doesn't want to save the profile)

`syncWithGallery`

I get it, it's a node/electron weirdo bug or something, but pretty pretty please, TPromise.timeout(5000)

btw @bpasero : I also think we do such a request in some other important process (main?) because it also takes 1-2s since I press the Open Folder until the window actually goes blank and loads something...

![image](https://cloud.githubusercontent.com/assets/5047891/18849157/50f277bc-843a-11e6-959c-ab3477cc08eb.png)

**Comment by bpasero** [comment] 2016-09-27 05:12
To my knowledge there is no HTTP request happening from when you picked a folder in the dialog until opening that folder.

**Comment by bpasero** [comment] 2016-09-27 07:50
Looks like https://github.com/Microsoft/vscode/issues/12087 is related/duplicate.

**Comment by joaomoreno** [comment] 2016-09-27 16:31
This is terrible, we might just move it to the shared process... thus not blocking editing... Although that will just make the shared process slow.

Closing as duplicate of #12087.

**Closed by joaomoreno** 2016-09-27 16:31 UTC
Labels: electron-update, freeze-slow-crash
