### ISSUE TITLE
how to set the other font family for keywords

### ISSUE THREAD

**Issue by coppyC** [Microsoft/vscode#40979] opened 2017-12-31 09:58 UTC
- VSCode Version: 1.19.1
- OS Version: Linux

Description:
My English is not very good and something can not express clearly.
Thanks for your reading.
I've been using vscode for a long time, and I really like it, but there is a feature that I do not know how to configure it, like configuring font styles in a theme,
```json
  "editor.tokenColorCustomizations": {
    "keywords": {
      "fontFamily": "monospace"
    }
}
```
like write it in setting
I think this is very useful, you can easily distinguish between keywords, but vscode does not seem to provide an implementation.
how to do it?

Reproduces without extensions: No

**Comment by usernamehw** [comment] 2017-12-31 14:39
Currently not possible. Duplicate of https://github.com/Microsoft/vscode/issues/36512

**Closed** 2018-01-02 14:27 UTC
