### ISSUE TITLE
When using Remote Development - OpenDialogOptions does not honour selectMany

### ISSUE THREAD

**Issue by mbwhite** [microsoft/vscode#132230] opened 2021-09-03 09:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:

- 
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version: Windows 10 with remote development to WSL2

Steps to Reproduce:

1. Using an extension a VSCode file selection dialog is created, this is set using these options
const openDialogOptions: vscode.OpenDialogOptions = {
                canSelectFiles: true,
                canSelectFolders: false,
                canSelectMany: true,
                openLabel: 'Select',
                filters: {
                    'Node Files': ['json']
                }
            }
2. Though this presents a dialog, and I can select a file, I can't select multiple files.. even with the `canSelectMany: true`
3. If this is run not using remote development, then the selection uses the native file selection and works as expected.

**Comment by alexr00** [comment] 2021-09-20 13:46
Duplicate of https://github.com/microsoft/vscode/issues/129959

**Closed by alexr00** 2021-09-20 13:46 UTC
