### ISSUE TITLE
editor.action.format does not use editor.insertSpaces?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#2505] opened 2016-01-28 16:24 UTC
i have it set to false but format replaces tabs with spaces and there is no tabify command to repair it? thanks

**Comment by aeschli** [comment] 2016-01-29 08:00
@rakkarage For what language do you see this?

**Comment by rakkarage** [comment] 2016-01-30 20:19
c#

**Comment by jrieken** [comment] 2016-02-01 14:51
duplicate of OmniSharp/omnisharp-vscode#26

**Closed by jrieken** 2016-02-01 14:51 UTC
