### ISSUE TITLE
VS Code - Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by anuraj** [microsoft/vscode#95106] opened 2020-04-13 10:10 UTC
- VSCode Version:1.44.0
- OS Version: Version 1909 (OS Build 18363.720)

Steps to Reproduce:

1. Open VS code using `code .` to a folder. 
2. VS Code showing `Extension host terminated unexpectedly.` error.

![image](https://user-images.githubusercontent.com/276411/79112765-f78ffb80-7d9c-11ea-98c6-00a401ccaed6.png)

Does this issue occur when all extensions are disabled?: Yes/No - Not sure.

**Comment by anuraj** [comment] 2020-04-13 10:37
I have un installed, re installed, removed all extensions - still issue exists.

**Comment by ibuli** [comment] 2020-04-13 10:42
I am experiencing the same issue from the last couple of days after updating to v1.44.0 (User setup).
I've also removed the `%UserFolder%\AppData\Roaming\Code` folder and `%UserFolder%\.vscode` folder and re-install the using User setup, but the issue persists.

**Comment by anuraj** [comment] 2020-04-13 10:51
Seems like my antivirus is causing the issue. But it is identifying a `JS.Nemucod.AF` - in this file - `Programs\Microsoft VS Code\_\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js` - and which is a [trojan or something](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=JS/Nemucod)

**Comment by ibuli** [comment] 2020-04-13 10:54
You are right, recently I've installed Quick Heal AV, which is quarantining `extensionHostProcess.js` the file. I've restored it and added it to exclude files.
This solved the problem.
![image](https://user-images.githubusercontent.com/7893167/79115327-2d37e300-7da3-11ea-9abd-15adfbaeb9d8.png)

**Comment by anuraj** [comment] 2020-04-13 11:20
Yeah, when I excluded that file it worked. But is that the real fix? or something wrong with the file?

**Comment by ibuli** [comment] 2020-04-13 11:36
I can't say exactly, but I tried to look up to that file, and it's a minified version.
Maybe from the vscode team, someone can enlighten us on that.
@alexdima

**Comment by alexdima** [comment] 2020-04-13 14:58
Duplicate of #94858

**Closed by alexdima** 2020-04-13 14:58 UTC
