### ISSUE TITLE
Edits lost because vscode reloads the file while editing it

### ISSUE THREAD

**Issue by RobIsHere** [Microsoft/vscode#25793] opened 2017-05-02 19:33 UTC
- VSCode Version: 1.11.2
- OS Version: Win 10

Steps to Reproduce:

1. Open a folder from a network share served by samba on ubuntu 16.04
2. Work for some hours in vscode
3. Eventually the file you are working on will reload (without any file change from elsewhere) and you loose all your edits
That happens about 1 time in 2 hours.

**Comment by bpasero** [comment] 2017-05-03 21:15
@RobIsHere to be clear, the editor was not dirty at the time your changes got overwritten, or was it?

**Comment by RobIsHere** [comment] 2017-05-03 21:22
It was dirty! The file reloads and all unsaved edits are just discarded.

I opened the file, wrote about 50 LOC in the file and then it flickered and my yet unsaved stuff was gone.

I'm using vscode for some time now and I'm very happy with it in general. This happened the first time after upgrading from 1.8.1 to current about 2 weeks ago. In 1.8.1 it never happened.

**Comment by bpasero** [comment] 2017-05-03 21:25
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by RobIsHere** [comment] 2017-05-03 21:30
Interesting thought. I'm only using quite common extensions like eslint. So i don't think so or you would have a lot more reports. But I'll try switching them off the next days.

**Comment by bpasero** [comment] 2017-05-20 06:03
@RobIsHere any results?

**Comment by RobIsHere** [comment] 2017-05-20 07:52
It didn't happen since then even with extensions on. The "fix" may also come as a side effect of changes I made for watchman https://facebook.github.io/watchman/docs/install.html#system-specific-preparation.

**Comment by bpasero** [comment] 2017-05-20 08:03
Ok closing until we see it again.

**Closed by bpasero** 2017-05-20 08:03 UTC
Labels: needs more info
