### ISSUE TITLE
CSS/SCSS intellisense: pseudo element adds extra colon

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15586] opened 2016-11-16 19:54 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (3408691c13470346a119141e57aa74b302464a4a, 2016-11-14T07:05:07.232Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.3|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.1.15|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.5.40|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|7.4.0|
|vscode-stylefmt|mrmlnc|2.0.1|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|stylelint|shinnn|0.18.2|
|theme-tesla|smlombardi|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. type a css selector, e.g. `.pb-font`
2. type a colon.  this brings up Intellisense
3. type `bef` to scroll to `::before`
4.  choose it
5. you now have `.pb-font:::before`, which is invalid

See gif:
![nov-16-2016 14-52-08](https://cloud.githubusercontent.com/assets/835148/20363247/81c9fb90-ac0c-11e6-82b5-f79ca27b7c25.gif)

**Comment by aeschli** [comment] 2016-11-23 20:08
duplicate of #14161.
I just updated the css language service in VSCode, you can try the fix in tomorrows insider build.

**Closed by aeschli** 2016-11-23 20:08 UTC
Labels: css-less-sass, suggest
