### ISSUE TITLE
Noticable delay in OutputEvents being displayed in the Debug Console

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51759] opened 2018-06-13 12:02 UTC
I had this raised against my extension - there's a (sub-second, but noticeable) delay between log events generated in an app and them appearing in the Debug Console. I put some timing in from when the event is generated on the mobile side and when I sent the `OutputEvent` and it was 0.03 milliseconds. This leads me to believe the delay is somewhere between the `OutputEvent` being sent and then being rendered back in the Debug Console (I don't think I can measure that without being able to show accurate timestamps as the Debug Console renders a line of text).

The delay is not great (like I say, sub-second) but it is pretty noticeable if the log is in response to some user action (say tapping somewhere in a mobile device being debugged). Since you don't make any promises about the latency here, I don't know if this is something you thing is acceptable but I figured since it was raised with me I should pass it along.

**Comment by isidorn** [comment] 2018-06-13 14:07
This is designed behavior. The debug console as an implementation detail is using a tree, and whenever new output arrives we refresh the whole tree - not the best approach but that is just life for now.
Thus each output arriving causes a tree refresh, and many outputs can cause many refreshes. Does we update the tree with a 300ms timeout.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L118

Here's an issue capturing that the debug console should move to some non tree implementation. Closing this as a duplicate of that https://github.com/Microsoft/vscode/issues/11462

**Closed by isidorn** 2018-06-13 14:07 UTC
Labels: debug, question

**Comment by DanTup** [comment] 2018-06-13 15:03
Gotcha! Thanks for the link; I did search for something related but didn't turn that one up.
