### ISSUE TITLE
Snippets do not always have expanded info window

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#46457] opened 2018-03-24 06:31 UTC
- VSCode Version: 1.22.0-ins
- OS Version:  win7x64

I'm not sure is it a bug of VS Code or extension, but anyway...

I use "Auto Import" extension:
![image](https://user-images.githubusercontent.com/24613274/37861161-7414faf4-2f3c-11e8-81bd-a9c0e6251831.png)

... and now I don't know why, but some of it's snippets don't have "expanded info window"
_(in the list of snippets it has orange icons)_

![auto import snippets 1](https://user-images.githubusercontent.com/24613274/37861146-27153962-2f3c-11e8-93d6-370d098e69cc.gif)

... and it's not only visually thing, but also it will cause of **_NOT_** auto-importing a file the user needs:

![auto import snippets 2](https://user-images.githubusercontent.com/24613274/37861206-2d87d1be-2f3d-11e8-9d4b-a02534e604d1.gif)

... as you can see, it can be "fixed" with deleting some letter(s) and re-trying.

**Comment by mjbvz** [comment] 2018-03-26 19:09
I believe this was fixed by 6c04bb4b642db30e7174cb6e35bbc3b124dcf563 . Please try the latest insiders build and let me know if you still see the issue

**Comment by user3323** [comment] 2018-04-02 16:10
@mjbvz 

nope, it's still not fixed!

```
Version 1.22.0-insider
Commit 6c22e21cdcd6811770ddcc0d8ac3174aaad03678
Date 2018-03-30T05:16:39.261Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by mjbvz** [comment] 2018-04-02 20:50
Thanks. Same symptom but different root cause. Opened https://github.com/Microsoft/TypeScript/issues/23087 to track this upstream

**Closed by mjbvz** 2018-04-02 20:50 UTC
Labels: bug
