### ISSUE TITLE
Revealing the cursor line does work in some cases when height is small and sticky scroll enabled

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#224787] opened 2024-08-05 08:50 UTC
Broken (`"editor.stickyScroll.enabled": true`):

![Image](https://github.com/user-attachments/assets/1181e7bd-efd2-4763-9aa1-9293c7a8ec3d)

Working (`"editor.stickyScroll.enabled": false`):

![Image](https://github.com/user-attachments/assets/4b82fbf3-e43d-46c1-a911-02ad085047f6)

In monaco playground:

[Broken](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#XQAAAAJiAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jdEZPszQLdU3xvs4q9fK6BBroG1MbThwgFObPaa2SvtYNbe33VvnIcvpqvbwTl-VfeqnBGZMJ9d5bVbdajyt_U58j9Iq9xshlnyQ2LXxfyZpCOBLHdpfwlfr7UqCC1rJQFDLl42n3jAge2TImcjUEFDJi5NDhm-ZpvZHUmeaoiyxoddo-OR6GKEKzKMr24tkq5cAEM-c32EOVhRrJRmLyisV0oHeVIr113_ZMQpA-BnONs0mzX43HvCCtTM8w3Lx9Iu9LumGe59tcX72MPnSk3Yt-vHeFLE35CM8cQv7G7fK7bIHcomGtqjO8T9vp9-Se85FHH__fCZ3AA):

![Image](https://github.com/user-attachments/assets/dc2e1d95-82e6-4b18-8461-ec4ad1a4b923)

[Working (sticky scrolling turned off)](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#XQAAAAJjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jdEZPszQLdU3xvs4q9fK6BBroG9MrThwgFObPaa2SvtYNbe33VvnIcvpqvbwTl-VfeqnBGZMJ9d5bVbdajyt_U58j9Iq9wLogjqlKtcQfAtXCSY-REO7x6DBnnZk8MdZys37BgSa0lWv26By677nzUX2VD6Iof4zMbAQnWFPb66M_ojAn-GjZZenu8ZPHqQHOE9KI7veyYZnn56moSKyIcZCC3_ZSzGLkZ2RF4PA-HLbyKgTu37ypblpmrk2Hvun2pDx-rwK_rzaeIQMxeAFuNRF61u26qMpHpjWHG911QQckEjR0zjkACpZ95C7nagjve3lW0mp2CD_6PtZ4A):

![Image](https://github.com/user-attachments/assets/c37ad583-e3be-4608-872a-768e243a4df4)

Since this affects monaco editor use-cases where the editor has a small height and sticky scrolling is enabled by default, I added the "important" label.

**Comment by aiday-mar** [comment] 2024-12-11 09:23
duplicate of https://github.com/microsoft/vscode/issues/227750. Closing this in favor of the other issue.

**Closed by aiday-mar** 2024-12-11 09:23 UTC
Labels: bug, important, editor-sticky-scroll
