### ISSUE TITLE
Aux window: Allowing search windows to be opened in a new window

### ISSUE THREAD

**Issue by danielpaz6** [microsoft/vscode#199856] opened 2023-12-02 13:38 UTC
I think it would be great that when searching globally for files/content, there will be an option to do so in a new window.
Much like Jetbrains editors do, an example:
![image](https://github.com/microsoft/vscode/assets/42693974/13590038-6fd2-4555-84a2-12ff085d397e)

**Comment by bpasero** [comment] 2023-12-03 07:15
You can do so via search editors:

![image](https://github.com/microsoft/vscode/assets/900690/8c23bca5-a0f6-454e-8b01-ceb0b0a8f561)

Otherwise, a duplicate of https://github.com/microsoft/vscode/issues/193267

**Closed by bpasero** 2023-12-03 07:15 UTC
Labels: workbench-auxwindow
