### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by zerdos** [microsoft/vscode#111969] opened 2020-12-06 19:15 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107131:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107166:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106903:50)
    at Object.finishCachingPerDirectoryResolution (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106908:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148280:38)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148211:42)
    at ConfiguredProject.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150849:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151747:44)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152070:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.9.12-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 4099)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.44GB (5.82GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id a8d7c841-bf50-4408-a21f-1f54748f6843|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
vscode-deno|den|2.3.3
gitlens|eam|11.0.6
vscode-styled-components|jpo|1.4.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.8.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
debugger-for-chrome|msj|4.12.11
vscode-versionlens|pfl|1.0.9
mdx|sil|0.1.0
code-spell-checker|str|1.10.2
vscode-mdx-preview|xyc|0.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-12-07 19:08
Duplicate of #111968

**Closed by mjbvz** 2020-12-07 19:08 UTC
