### ISSUE TITLE
Watcher service taking more than 100% CPU

### ISSUE THREAD

**Issue by vaidhyanathan93** [Microsoft/vscode#53577] opened 2018-07-05 09:04 UTC
Issue Type: <b>Bug</b>

For larger ruby projects with ember (ignored node and vendor modules). Even tough it is taking more than 99% CPU always .

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (3.15GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

<img width="1195" alt="screen shot 2018-07-05 at 2 30 05 pm" src="https://user-images.githubusercontent.com/3818495/42313473-821a553e-8060-11e8-8a3d-473cb9dc2bfd.png">

**Comment by bpasero** [comment] 2018-07-05 14:10
Duplicate of https://github.com/Microsoft/vscode/issues/3998

**Closed by bpasero** 2018-07-05 14:10 UTC
