### ISSUE TITLE
Traces of deleted links showing in editor when deleting

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#48321] opened 2018-04-21 09:20 UTC
Issue Type: <b>Bug</b>

1. For instance, execute `editor.action.deleteLines` (works with <kbd>backspace</kbd> for me too)
```







https://google.com      https://github.com


```
![traces](https://user-images.githubusercontent.com/9638156/39082575-30d1486e-455e-11e8-8b86-cf1aac8ca351.gif)

VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:17:25.189Z)
OS version: Windows_NT x64 10.0.16299

Can't reproduce in stable.

**Comment by usernamehw** [comment] 2018-04-21 19:55
Not only deleting, moving around too:
![moving](https://user-images.githubusercontent.com/9638156/39088236-134c06cc-45b7-11e8-8cd7-8b966a160b99.gif)

**Comment by alexandrudima** [comment] 2018-04-23 08:57
@usernamehw I cannot reproduce in stable, in insiders, or in master

Have you tried disabling all extensions? (perhaps you have an extension in insiders that you don't have in stable which causes this).

**Comment by usernamehw** [comment] 2018-04-23 14:06
That's what I usually do before submitting:
![text](https://user-images.githubusercontent.com/9638156/39131640-a2b22c8a-4718-11e8-9dd4-08d6e96688b4.gif)

**Comment by usernamehw** [comment] 2018-04-23 14:11
If I comment out everything in `settings.json` it doesn't reproduce...

**Comment by usernamehw** [comment] 2018-04-23 14:27
Reproduces even  with `code-insiders --disable-gpu`.

I have no idea but can you try `"editor.fontSize": 20,`

**Comment by alexandrudima** [comment] 2018-04-23 14:49
I can reproduce on Windows with the setting: `"editor.fontSize": 20`

This is most definitely a Chromium bug that came in via the Electron update (look how the unpainted area matches the tiles perfectly:

![image](https://user-images.githubusercontent.com/5047891/39134061-06597368-4716-11e8-93a7-2dfa1201de24.png)


![kapture 2018-04-23 at 16 48 33](https://user-images.githubusercontent.com/5047891/39134138-34ace100-4716-11e8-9bf7-5e7ab513216a.gif)

**Comment by bpasero** [comment] 2018-06-15 06:35
@alexandrudima can you also reproduce this issue if you add `app.commandLine.appendSwitch('force-color-profile', 'srgb')` into `src/main.js` around line 43?

**Comment by alexandrudima** [comment] 2018-06-18 09:08
@bpasero That extra command line switch appears to make no difference. I can still reproduce on Windows when using fontSize 20.

**Comment by bpasero** [comment] 2018-06-18 09:57
Thanks

**Comment by bpasero** [comment] 2018-08-10 16:57
@usernamehw would you be willing to give some feedback if you can still reproduce this issue with a newer build that uses a newer Chrome version? You can [download it from here](https://az764295.vo.msecnd.net/exploration/198d785facf747b1f26234807376c6b3da09ef7a/VSCodeUserSetup-x64-1.27.0-exploration.exe). You will notice a new "VS Code Exploration" application with an orange icon.

Thanks!

**Comment by bpasero** [comment] 2018-08-10 17:52
Thanks for testing ❤️

**Comment by bpasero** [comment] 2019-10-08 07:32
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by alexandrudima** [comment] 2019-10-08 14:06
I could reproduce wierdness around `text-decoration: underline` in Chrome Canary and I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1012248

**Comment by alexdima** [comment] 2021-02-03 16:25
[The issue I filed](https://bugs.chromium.org/p/chromium/issues/detail?id=1012248) against Chromium was duped against [another issue](https://bugs.chromium.org/p/chromium/issues/detail?id=896295). That issue was [marked fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=896295#c44) by the commit [58087bc84e8584962f39e6bea2b278a96ce3f848](https://chromium.googlesource.com/chromium/src/+/58087bc84e8584962f39e6bea2b278a96ce3f848).

Looking at https://chromium.googlesource.com/chromium/src/+/58087bc84e8584962f39e6bea2b278a96ce3f848/chrome/VERSION , this appears to have been shipped with Chromium `87.0.4277.0` and we are going to ship VS Code 1.53 with Chromium `87.0.4280.141` so I will optimistically close this.

@deepak1556 Please correct me if I'm wrong.

**Closed by alexdima** 2021-02-03 16:25 UTC
Labels: chromium, electron-2-update, fixed-in-electron-11, gpu, upstream, upstream-issue-linked

**Comment by deepak1556** [comment] 2021-02-03 18:07
Yup thats correct.

@alexdima another trick to find commits when they got first shipped is to use https://chromiumdash.appspot.com/commits and in the search box use `commit:<commit-hash>` which should give some elaborate results.
