### ISSUE TITLE
IndexDB filesystem provider does not support file watching

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117561] opened 2021-02-24 09:58 UTC
It looks like the IndexDB file system provider is not able to support watching:

https://github.com/microsoft/vscode/blob/f1d92e789602f9389114760636f21c1b6b91ec32/src/vs/platform/files/browser/indexedDBFileSystemProvider.ts#L229-L231

As a consequence, the storage implementation in the browser is unable to detect changes from other windows targeting global scope because it is using file watching for that purpose.

If we cannot support detecting changes from a different browser tab to the same IndexDB instance, then I think we have to close this "as designed".

//cc @sandy081

**Comment by sandy081** [comment] 2021-02-24 10:02
/duplicate

duplicate of https://github.com/microsoft/vscode/issues/107854

**Comment by sandy081** [comment] 2021-02-24 10:03
More info:

It seems `IndexedDB` is not having an API to listen to changes done in other tabs - 

Open Issue: https://github.com/w3c/IndexedDB/issues/51

We need to have a workaround in our code to trigger changes.

**Closed** 2021-02-24 10:03 UTC
Labels: *duplicate, web
