### ISSUE TITLE
Allow QuickPickItem to have file icons

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#232439] opened 2024-10-28 18:50 UTC
Currently, there is no explicit way to set the theme icon for items in `QuickPickItem`, `Terminal`, `TreeViewItem` to a specific language Icon.

TreeView supports an indirect way where you need to set `resourceUri` to a file (like `something.py`), and `iconPath` to `ThemeIcon.File`. This allows core to calculate the icon. But there is no way to say `iconPath = new ThemeIcon('python')`.

Such a feature is not available in QuickPicks or Terminal (`iconPath`). For `QuickPick`, the uses cases include selecting a start-up script or set of files for some task. For, `Terminal`, in python extension we can have dedicated terminal per file, and we would like to show the icon of the file there. 

Related: https://github.com/microsoft/vscode/issues/124363 , https://github.com/microsoft/vscode/issues/59826

**Comment by TylerLeonhardt** [comment] 2024-10-28 21:31
Martin owns ThemeIcon's... I'll let him drive this one. If you want a separate issue that is specific to QuickPick having a `resourceUri` like Trees, please create one and assign that to me.

**Comment by aeschli** [comment] 2024-10-29 16:00
There are two different types of icons:
- file icons: they are defined by the current file icon theme. There are file icon themes that don't show icons, and there are file icon themes that show the same icon for all files. Maybe there's an icon for `python` in there, maybe there are multiple as associations are based on file name, file extension and folder name and language
- product icons: A set of named icons. The ones you can reference in ThemeIcon

If your goal is to have the same icon as in the explorer or editor title: then use ThemeIcon.FILE and set a resource. We need a resource name for that given the multiple ways that associations work. The resource doesn't have to exist.

If you want to have a Python icon that is always available, but might not match what's in the explorer:
Ask for a new codicon for an icons called 'Python'

There's one thing we could do. Language providers have a way to contribute a default icon. It is used as a file icon if a theme does not define an icon. We could also register that one as a product icon.
- Only very few languages do that. Basically only exotic languages that are unknown to most file icon themes
- That icon will in the most cases not match the icon from file icon theme.

**Comment by karthiknadig** [comment] 2024-11-04 19:39
For Quickpick, Terminal, I want the `file icons`, that would address the issue that I have.

**Comment by aeschli** [comment] 2024-11-05 09:39
Ok, then assigning this issue to @TylerLeonhardt for Quick Pick...

**Comment by TylerLeonhardt** [comment] 2024-11-05 16:37
Based on the response @aeschli doesn't think we should allow the language id in the ThemeIcon and Karthik is satisfied with that answer so long as we address the gaps in QuickPick and Terminal APIs.

I already have a quick pick one https://github.com/microsoft/vscode/issues/59826 

@karthiknadig were you able to find a Terminal one?

If not, can you open one?
If so, or once that's opened, then we can mark this as a dupe of those, I think.

**Comment by karthiknadig** [comment] 2024-11-07 19:27
@TylerLeonhardt Created https://github.com/microsoft/vscode/issues/233354 for Terminals

**Comment by Tyriar** [comment] 2024-11-07 19:28
Should we close this in favor of https://github.com/microsoft/vscode/issues/59826?

**Closed** 2024-12-13 09:36 UTC
