### ISSUE TITLE
%resource_id% is not working in extension package.json

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#76319] opened 2019-06-28 23:29 UTC
Issue Type: <b>Bug</b>

Our extension (Live Share) supports localization by having `%resource_id%` descriptions and titles in its `package.json`. We ship `package.nls.json` and `package.nls.{lang}.json` with the English and localized strings.

It used to work before, and now VSCode doesn't recognize these `%resource_id%` and doesn't substitute them for localized/English resources

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (6.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IlyaBiryukov** [comment] 2019-06-28 23:29
cc @dbaeumer

**Comment by IlyaBiryukov** [comment] 2019-06-28 23:57
Maybe a dupe of #54111

**Comment by dbaeumer** [comment] 2019-07-01 07:09
@IlyaBiryukov can you provide me with an example. I tried to reproduce this locally and the strings look fine for me. 

<img width="641" alt="capture" src="https://user-images.githubusercontent.com/1931590/60417114-d9775700-9bdf-11e9-9256-83fa028144d6.png">

<img width="545" alt="capture" src="https://user-images.githubusercontent.com/1931590/60417161-fdd33380-9bdf-11e9-8548-7f9fed63c208.png">

**Comment by dbaeumer** [comment] 2019-07-01 07:12
VS Code version:

<img width="294" alt="capture" src="https://user-images.githubusercontent.com/1931590/60417286-51458180-9be0-11e9-9749-f58c56ad8f9f.png">

LiveShare: 1.0.471

**Comment by dbaeumer** [comment] 2019-07-01 07:13
Not a dupe of 5411

**Comment by dbaeumer** [comment] 2019-07-01 08:21
The place were I see this is here:

<img width="212" alt="capture" src="https://user-images.githubusercontent.com/1931590/60421382-03357b80-9bea-11e9-99b2-0f61aea01dc0.png">

**Comment by dbaeumer** [comment] 2019-07-01 08:25
@IlyaBiryukov  If this is the problem you see then this is a issue with Live Share since output channel names can't be configured in package.nls.json. They all come through code and I guess you are simply using the wrong key.

**Comment by IlyaBiryukov** [comment] 2019-07-01 17:30
I see the problem with the descriptions on the extension's Contributions page:
![image](https://user-images.githubusercontent.com/15989459/60455466-46441e80-9beb-11e9-8af1-fe41c40e4e9c.png)

**Comment by dbaeumer** [comment] 2019-07-01 20:18
@sandy081 can you please comment what the state here is. I always thought the extension editor is showing at lease the English strings. This is at least what he does for the built in extensions.

**Comment by dbaeumer** [comment] 2019-07-01 20:19
<img width="874" alt="capture" src="https://user-images.githubusercontent.com/1931590/60464221-3b6ea580-9c4e-11e9-8856-90201c2cd5df.png">

**Comment by dbaeumer** [comment] 2019-07-01 20:23
Then this could be a dup if #54111.

**Comment by dbaeumer** [comment] 2019-07-02 08:12
OK. I discussed this with @sandy081 and it is a dup of #54111.

**Closed by dbaeumer** 2019-07-02 08:12 UTC
Labels: needs more info
