### ISSUE TITLE
“Visual Studio Code.app” can’t be opened 

### ISSUE THREAD

**Issue by priyaka-xo** [microsoft/vscode#87040] opened 2019-12-15 23:13 UTC
I am trying to download Visual Studio Code version 1.41 on Mac. However, I get the following response:
"Visual Studio Code.app" can't be opened because Apple cannot check it for malicious software. 
This software needs to be updated. Contact the developer for more information.

Please advise.

**Comment by gjsjohnmurray** [comment] 2019-12-15 23:23
/duplicate of #74782 for which the resolution didn't land in time for 1.41. That ticket suggests workarounds.

**Closed** 2019-12-15 23:24 UTC
Labels: *duplicate, install-update
