### ISSUE TITLE
Terminal command decorations: Phrasing is odd

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#143705] opened 2022-02-23 11:04 UTC
Testing #143433

<img width="177" alt="image" src="https://user-images.githubusercontent.com/22350/155307046-fddb7262-0597-42ae-85c7-e483c9ac9103.png">

How about _Command executed **just** now and failed_?

**Comment by Tyriar** [comment] 2022-02-23 15:47
We use this helper for this: https://github.com/microsoft/vscode/blob/adb8450420fee8b22d04c2f808dd4e2caad62b0f/src/vs/base/common/date.ts#L15

It gives us "now", "x seconds ago", "y minutes ago", etc., special casing "now" would mean either bringing the 30 second magic number into terminal land or making the change globally which is a much bigger change I'm not comfortable doing. Since we use it the same as settings sync, about, auth, etc. I'm closing as designed.

**Closed by Tyriar** 2022-02-23 15:47 UTC
