### ISSUE TITLE
Not highlighting php $ variables

### ISSUE THREAD

**Issue by AdowTatep** [Microsoft/vscode#3035] opened 2016-02-15 23:40 UTC
Well, i remember pretty well that it was highlighting php variables with a blue color, is it a problem in my installed version?

**Comment by mattacosta** [comment] 2016-02-16 00:01
That's because they did used to highlight variables! However, it was a bug, because the old theme was designed to mimic the actual Visual Studio, which does not highlight variables. In order to make things prettier, we got new colorful Light+/Dark+ themes to compensate though. It is the default for new installations, but if you updated from a previous version, you were left on the old theme. Just change the theme from your command palette. :)

**Comment by AdowTatep** [comment] 2016-02-16 00:06
I see now, thanks a lot for the answer! I thought that it was that "php.validate.executablePath" thing, but when i fixed it, the variables weren't blue and i got stressed ¬¬'

:)

**Comment by egamma** [comment] 2016-02-16 07:50
Thanks @mattacosta for chiming in.

Closing since this has been addressed by the ligh/dark+ themes

**Closed by egamma** 2016-02-16 07:50 UTC

**Comment by Cisvhenriksen** [comment] 2016-04-28 13:57
Could we put this into Q&A of VS Code, just wasted hours on this annoying problem
