### ISSUE TITLE
Fold block comments doesn't work

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46653] opened 2018-03-27 09:39 UTC
re #46597

* open `/src/vs/base/common/arrays.ts`
* select F1 > Fold Block Comments
* 🐛 block comments aren't folded

**Comment by mjbvz** [comment] 2018-03-27 17:44
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Comment by mjbvz** [comment] 2018-03-27 17:45
Whoops, duplicated the wrong issue. This one is about  the `Fold Block comment command`

**Comment by mjbvz** [comment] 2018-05-07 21:50
Fixed by e628e8e7b26ad628763671d1f4b6190ae6e7f9a4. Currently also requires a build from TS master. We will pick up a TS insiders with the fix tomorrow.

**Closed by mjbvz** 2018-05-07 21:50 UTC
Labels: bug, javascript, typescript, upstream
