### ISSUE TITLE
Terminal window text becomes invisible upon typing

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#70135] opened 2019-03-09 21:07 UTC
- VSCode Version: 1.32.1
- OS Version: Windows 10 Pro 1809 17763.316

Steps to Reproduce:

1. Open a fresh Terminal window, which shows the default MOTD text
2. Start typing anything, the text will become invisible

![%pn 03-04-55 PM x](https://user-images.githubusercontent.com/16949253/54077377-042e5000-427d-11e9-80f6-883d5d10b0f9.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ghiscoding** [comment] 2019-03-10 05:14
@PassTheMayo 
This is probably fixed by using Conpty but you need 18309+ which you don't seem to have, it's only currently in Windows Insider Version. So at the end, it's probably a duplicate of #45693

![Conpty](https://user-images.githubusercontent.com/643976/54080934-1504b300-42c9-11e9-922d-f154b1d15c13.png)

**Comment by Tyriar** [comment] 2019-03-11 14:46
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Closed by Tyriar** 2019-03-11 14:46 UTC
Labels: new release
