### ISSUE TITLE
Disable New Git View submenus

### ISSUE THREAD

**Issue by sazzy4o** [microsoft/vscode#104886] opened 2020-08-18 04:29 UTC
## Background
I was wondering if there is a way to disable the [new git submenus](https://code.visualstudio.com/updates/v1_48#_git-overflow-menu-cleanup) or if this could be added as a feature. In the new git submenus it is now more difficult and to access frequently used features like "Push" and "Pull". In the old git menu these were near the top an easily accessible. I don't think these should be given the same precedence as features that will be infrequently used by most users like "Abort Rebase", "Rename Branch".

## Question
Is there a way to get the old (flat) git menu back?

#### Old git menu:
![image](https://user-images.githubusercontent.com/10637549/90470049-acce1980-e0d7-11ea-9d7c-857a1bab3e83.png)
#### New git submenu:
![image](https://user-images.githubusercontent.com/10637549/90470167-033b5800-e0d8-11ea-832f-7a0231910d7d.png)

**Comment by gjsjohnmurray** [comment] 2020-08-18 06:31
/duplicate of #104762, and as a workaround you may be interested in https://github.com/microsoft/vscode/issues/104762#issuecomment-674902220

**Closed** 2020-08-18 06:32 UTC
Labels: *duplicate
