### ISSUE TITLE
use chrome/electron's spell checker for comments and text documents

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#5292] opened 2016-04-15 01:57 UTC
- VSCode Version: 1.0.0
- OS Version: arch linux 64bit kernel 4.5

This is a feature request.

Currently the only spellchecker available is https://github.com/Microsoft/vscode-spell-check, which is slow if you have a crappy connection, and is insecure.

chrome has already a built in spell-checker, is there any way to use that rather than that extension? or aspell?

**Comment by OneOfOne** [comment] 2016-07-17 14:53
I hate to do this but bump?

I'd rather not use the spell-checker extension because:

1. it sends your data in plain text to the server.
2. well, it sends your data to the server.

**Comment by arashbehmand** [comment] 2016-09-04 15:19
+1

**Comment by mckennapsean** [comment] 2017-02-13 19:16
+1

As an update to the issue, `vscode-spell-check` was made secure (HTTPS) but is now unreliable due to issues with the underlying service (AfterTheDeadline).

I agree that an offline solution would be better and more ideal for sensitive text. I love to use vs-code with my markdown and pandoc files.

Another spell-checker extension is out there:
https://marketplace.visualstudio.com/items?itemName=swyphcosmo.spellchecker

It uses `hunspell` in the background, but I had mixed results with it compared to my personal favorite `aspell` which catches the most errors for me.

**Comment by OneOfOne** [comment] 2017-02-13 20:10
I completely understand Microsoft loves to send users' data to remote server, but how is this feature request not a high priority?

@mckennapsean thank you for pointing that extension out!

**Comment by mckennapsean** [comment] 2017-02-13 23:20
Glad to help!

I would say that spell-checking is something you can do with other tools, and most people program code with vs-code, not write novels or documents, which you can use other tools (like Word / Writer / Pages / Google Docs) for. If you are using vs-code to write, you can probably use command-line spell-checkers. But I agree that having this built-in, functional, and offline would be ideal - just you may not find all those features baked in but in an extension for now... perhaps time to write one!

**Comment by SommerEngineering** [comment] 2017-02-26 21:44
@mckennapsean Many students and scientists using LaTeX. There is a VS Code extension for LaTeX. It would be great to be able to write the own thesis in VS Code.

**Comment by mckennapsean** [comment] 2017-02-27 03:58
Oh I totally agree @SommerEngineering - I am actually writing up my dissertation using `pandoc` and `latexmk` with the _awesome_ tasks system built into the editor. My argument was that it may be a niche / less utilized feature than features relating more to code.

However, when it comes to Markdown, LaTeX, and even documentation, spelling is definitely a killer feature. I just think a good extension may come first, but time will tell. :)

**Comment by mjbvz** [comment] 2017-11-03 23:19
Duplicate of #20266 (I know this issue is the older of the two, but #20266 has more upvotes and comments)

**Closed by mjbvz** 2017-11-03 23:19 UTC
Labels: duplicate, feature-request
