### ISSUE TITLE
Scroll position lost on release notes

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#58007] opened 2018-09-05 21:57 UTC
When viewing release notes within VS Code, the scroll position is lost if I change to another tab and back again.

Also, it's not possible to drag the release notes tab to create tilings, as you can with any other tab.

**Comment by mjbvz** [comment] 2018-09-05 22:26
Duplicate of #45571

**Closed by mjbvz** 2018-09-05 22:26 UTC
