### ISSUE TITLE
Suggestion for multi-lines comments and folding

### ISSUE THREAD

**Issue by yveslange** [Microsoft/vscode#36399] opened 2017-10-17 09:09 UTC
- VSCode Version: 1.17.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write a multi-lines comment using `/** */`. Eg:
```javascript
/**
 * This is my comment
 * on multiple lines.
 */
```
2. Fold up the comment
```javascript
 /** ...
```

Reproduces without extensions: Yes

**Suggestion:**
It would be good to have the first line of the comment when folded. Eg:
```javascript
/** This is my comment...
```

Best regards

**Comment by mjbvz** [comment] 2017-10-17 17:39
Thanks. Looks like we are already tracking this with #31966

Closing as a duplicate of #31966

**Closed by mjbvz** 2017-10-17 17:39 UTC
Labels: duplicate, editor, editor-folding, new release
