### ISSUE TITLE
[Feature Request] Add inline git blame annotations

### ISSUE THREAD

**Issue by deadmeu** [microsoft/vscode#205424] opened 2024-02-17 08:58 UTC
One of the first things I (and I presume many other developers) do when installing a new text editor or IDE is to enable inline git blame annotations (either natively, if the editor supports it, or via an extension).

Inline git blame annotations make it extremely easy to see when a particular line was last modified without requiring the user to perform clicks in order to get that information.

Additionally, the user should be able to interact with this annotation by hovering the cursor over the text, in order to quickly get a more detailed view of the commit.

I think it makes sense to include this feature as a native feature within VS Code, rather than relying on third-party extensions, as VS Code already includes native git tooling and this highly popular feature builds upon existing features to provide a great QOL improvement and make it easier for developers (both new and old) to work with git.

**Comment by IllusionMH** [comment] 2024-02-18 04:57
As you've mentioned extensions in first part: have you tried [GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)?
I think it supports feature you are looking for and many other.

**Comment by Keavon** [comment] 2024-02-20 01:45
I found GitLens far too intrusive, but I've really liked the simple [Git Blame](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame) extension. It shows the blame information in the status bar, rather than inline, which differs from OP's request but I personally find this preferable since it's available at-a-glance but not constantly in the way of my coding.

**Comment by joaomoreno** [comment] 2024-07-18 07:13
Dupe of https://github.com/microsoft/vscode/issues/203841 ?

**Comment by lszomoru** [comment] 2024-07-22 09:59
No. https://github.com/microsoft/vscode/issues/203841 is git blame for the whole file that is being shown in the gutter.

**Comment by gayanper** [comment] 2024-08-21 19:02
Zed editor already has native support for git blame now https://github.com/zed-industries/zed/pull/10398, when are we going to get it natively in vscode ?

As everyone has told, Git Lense is really intrusive, even switching off pro feature, still they try to advertise their pro feature like the git graph. 100s of settings on each feature makes it really hard to get some simple thing done related to git. Recently I got rid of git lens and started to use default vscode support for day to day git operation which proves to be more efficient. what is missing is full repo log view (currently using Git Graph extension) and Git Blame, which doesn't have a very good alternative in market place.

**Comment by igorstr** [comment] 2024-10-20 22:53
Any updates on this topic?

**Closed** 2024-11-27 15:21 UTC
Labels: feature-request, git

**Comment by sanket-bhalerao** [comment] 2024-11-27 17:16
@lszomoru, can you give an example for the `git.blame.editorDecoration.template` setting?
i tried  "git.blame.editorDecoration.template": "{author} {summary} {date} {time} {hash}", it prints 
![Image](https://github.com/user-attachments/assets/be6e462d-3a55-468a-aaf0-a3020a468594)

**Comment by sanket-bhalerao** [comment] 2024-11-27 18:06
this feature is awesome. Kudos @lszomoru 👏

**Comment by sanket-bhalerao** [comment] 2024-12-01 13:39
The feature is working great. The blames come immediately (i felt some lag a couple of days ago, however it is smooth now).
i used the Gitlens extension mostly for the blames (the other thing i used for it was exploring the stashes and the rebase editor. i am hopeful that a `stash explorer` kind of feature will debut in VSCode sooner or later.)
Great feature.
Thank you.

**Comment by boraozgen** [comment] 2024-12-17 10:37
I don't know if this is the right place to give feedback, but here you go. I'm very glad that this was integrated into the editor and finally I can remove GitLens.

As for an improvement, I was used to the darker color of the decoration from GitLens (I use the Dark Modern theme), so the default color (`#777777`) was too bright for me. I adjusted it to `#555555` and now it's perfect. So maybe the default colors could be adjusted so that the decoration is more subtle.

**Comment by sanket-bhalerao** [comment] 2024-12-19 10:06
i have mine set to `"git.blame.editorDecorationForeground": "#f8f8ff3f"` 
i am using dark mode in vscode.
