### ISSUE TITLE
Function Required: No Record of History and Files

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#47441] opened 2018-04-08 17:06 UTC
Please add an option that, files I opened could not be kept when I open VS Code next time.
Because if I start VS Code, all the files I opened last time will be open again. Maybe it is useful for most people, but I'm sure there are still many people like me who don't like this.

And also, please add an option that, history can be not recorded for files.

**Comment by roblourens** [comment] 2018-04-09 04:55
"Clear Editor History" will clear the history in case that helps

**Comment by bpasero** [comment] 2018-04-18 05:33
Duplicate of https://github.com/Microsoft/vscode/issues/22613

**Closed by bpasero** 2018-04-18 05:33 UTC
Labels: feature-request, workbench-history, workbench-state
