### ISSUE TITLE
Global git ignore breaks if .gitconfig is outside %UserProfile% in Windows

### ISSUE THREAD

**Issue by thdoan** [microsoft/vscode#124053] opened 2021-05-17 18:45 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Add to your `.bashrc` or `.bash_profile`: `export HOME=/c/Users/<usename>/home`
2. Enter `git config --global core.excludesfile ~/.gitignore_global` in console
3. Add a file pattern to `~/.gitignore_global`
4. Add/Edit a file matching pattern in step 3 to the git repo
5. Enter `git status` in console to verify global ignore works
6. Load VS Code

Expected behavior: VS Code should ignore the modified file like git does in the console.

Actual behavior: VS Code shows the modified file under the Source Control tab.

It appears `.gitconfig` is not parsed if it is placed outside of `%UserProfile%` on the Windows platform.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (4.46GB free)|
|Process Argv|--crash-reporter-id 87146db6-51dd-47a9-a9fe-074405a51226|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
gitlens|eam|11.4.1
vscode-ts-whitespace-converter|joh|1.2.1
prophet|Sqr|1.4.17
sort-lines|Tyr|1.9.0
remove-empty-lines|use|0.0.6

</details>

**Comment by thdoan** [comment] 2021-05-17 18:57
One observation: when I right-click on the unstaged file in VS Code, I do NOT see a "Copy Path" command -- only "Copy Remote File Url", which contains this value:

`https://bitbucket.org/path/to/repo/src/<hash>/path/to/ignored/dir/<newfile>`

Strange. This is only a recent issue -- this file has been ignored by VS Code for awhile now, so I'm wondering if it's a regression after updating to new version.

**Comment by roblourens** [comment] 2021-05-17 22:31
The search setting `search.useGlobalIgnoreFiles` isn't actually relevant to the features in the git viewlet

**Comment by thdoan** [comment] 2021-05-17 23:26
@roblourens  ah then it makes sense that this file was properly ignored by vscode as recently as last week without me not setting `search.useGlobalIgnoreFiles` in my personal `settings.json`. I only looked into `search.useGlobalIgnoreFiles` because I thought the file is no longer ignored because this new setting was introduced and I needed to set it to `true`. 

Strange... if we rule out it's not related to `search.useGlobalIgnoreFiles` then do you know any other explanation why this file that is in my global gitignore file is correctly ignored by git in the console but is still showing up under unstaged changes in vscode?

**Comment by thdoan** [comment] 2021-05-17 23:40
I've been pondering recent changes I made over the weekend that might have led to this issue, and the only one I can think of is that I changed my git bash $HOME from `%UserProfile%` to `%UserProfile%/home` -- would this have an effect on vscode?

**Comment by thdoan** [comment] 2021-05-18 00:02
UPDATE: I think I have identified the root cause, and it could be a bug: on the Windows platform, if you put your `.gitconfig` file outside of `%UserProfile%` folder, then VS Code will not parse the global git ignore file. As soon as I moved my `.gitconfig` file from `%UserProfile%\home` back to `%UserProfile%`, the global ignore is recognized by VS Code again.

**Comment by lszomoru** [comment] 2022-12-13 13:46
@thdoan, apologies for not getting back to you on this issue until now. Looking at the messages in this issue it seems to me that your have tracked down the root cause of the issue and you have a workaround in place. As this is an edge case, and there was not much traffic on this issue from other users, I would like to go ahead and close this issue as we are not planning on making any improvements in this area in the near future.

**Closed by lszomoru** 2022-12-13 13:46 UTC
Labels: bug, git
