### ISSUE TITLE
Screen reader (NVDA) STOPS WORKING

### ISSUE THREAD

**Issue by HugoRasiuk** [microsoft/vscode#154581] opened 2022-07-09 00:02 UTC
Hemos e
Issue Type: <b>Bug</b>

I always use NVDA with VS Code. My setting for Editor: Accessibility Support is 'on'. In the nuew version of VS Code, when I change the window or minimize VS Code and then return to Vs Code window or maximize it, NVDA doesn´t speak again.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (12.03GB free)|
|Process Argv|--crash-reporter-id 424bd7fc-e4b7-479f-a5d5-7b03c5fb6d49|
|Screen Reader|yes|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.69.7060944
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1001902341
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

scrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by gjsjohnmurray** [comment] 2022-07-09 01:32
Does https://github.com/microsoft/vscode/issues/152291#issuecomment-1167303195 help?

**Comment by steverep** [comment] 2022-07-09 17:41
Yes this appears to be a duplicate of #152291.

**Comment by deepak1556** [comment] 2022-07-11 04:14
Merging to https://github.com/microsoft/vscode/issues/152291

**Closed by deepak1556** 2022-07-11 04:14 UTC
Labels: new release
