### ISSUE TITLE
Explorer: Can't create folder on newly created folder

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78153] opened 2019-07-30 09:18 UTC
1. Empty explorer
2. Click `New Folder` top action, name the folder and create it
3. Click `New Folder` again

Input box comes and goes.

**Comment by isidorn** [comment] 2019-07-31 15:03
Can not repro.
Do you click somewhere in the meantime?

What I can repro thought is that sometimes canceling the empty input box creates a folder with the previous name :hmm

**Comment by jeanp413** [comment] 2019-08-11 19:30
The first error is because the newly created element has `stale` set to true (in asyncDatatree) which triggers a refresh of the node which happens in the next event loop and the workaround in the explorerViewer with the [settimeout](https://github.com/microsoft/vscode/blob/5117a8e61fc0010f1c9723e34a4f757cb2487202/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L223-L231) doesn't work in that case

Second error is because the `explorerService.setEditable()` and `explorerService.select()` launch async operations and there is a "race condition" in IndexTreeModel because the splice method(which will be called by `setEditable` removing the new item) is being called after the `_setCollapsed` method(which is called by `select`)

**Comment by jthistle** [comment] 2019-08-15 16:02
I have a fix for this! It's very simple. I will post my PR soon.

**Closed** 2019-08-16 10:27 UTC
Labels: bug, file-explorer

**Comment by isidorn** [comment] 2019-08-16 10:30
Thanks for the feedback and for providing a PR.
However triying out your PR the issue is not always fixed for me.

Due to that and issues appearing from time to time I have decided to go back to our original approach and @joaomoreno and me devised.
It has some issues (I think this [one](https://github.com/microsoft/vscode/issues/72626)), but covers this case and many most other painful ones.

So please try it out in vscode insiders tomorrow and let us know how it behaves.

The whole blur event handling is rather tedius. An alternative would be to not react on blur events, which might be incosistent with how native explroer behave.

**Comment by jthistle** [comment] 2019-08-16 10:45
Ah, ok. I thought it seemed too simple a fix. Is it down to a race condition then? From what I could tell in the Chrome debugger it certainly looked a lot like that.

**Comment by isidorn** [comment] 2019-08-16 10:51
It is timing between blur events, creating new templates by the tree, adn dipososing of old templates. Not fun.

**Comment by jthistle** [comment] 2019-08-16 10:52
No, race conditions are never fun...

**Comment by jeanp413** [comment] 2019-08-17 21:15
With  b8974b0 applied I can repro #72626 again and this one:

![explorerbug_](https://user-images.githubusercontent.com/25115070/63216968-89a70d80-c103-11e9-8b0b-0e317b5206cc.gif)

**Comment by jeanp413** [comment] 2019-08-18 08:16
Created a PR that seems to fix all of the reported issues in case it's needed.
