### ISSUE TITLE
Restored terminals not working correctly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#137766] opened 2021-11-24 00:17 UTC
This has been happening for awhile

- Have some terminals open
- Reload the window
- The terminals are restored
- When I switch to the restored terminal, the focused tab doesn't update, and the terminal is not focused. If I click in the terminal, then it gets fixed
- And if I run the "Focus Terminal" command, it creates a new terminal instead of focusing the existing terminal
![Nov-23-2021 16-16-35](https://user-images.githubusercontent.com/323878/143148759-0b556814-0d04-4057-8474-1d94e3071d5c.gif)

It doesn't happen every time but I see it fairly often.

Also this gif is showing all the terminal tab titles disappearing when the broken tab is revealed. I haven't seen that before

**Comment by Tyriar** [comment] 2021-11-24 21:19
Related: https://github.com/microsoft/vscode/issues/137514

**Comment by Tyriar** [comment] 2021-11-24 21:20
Actually, I think it is a duplicate of that since you're reloading not restarting (the session contents restored message threw me off).

**Closed** 2021-11-24 21:21 UTC
Labels: bug, *duplicate, terminal-persistence
