### ISSUE TITLE
IntelliSense dies, code helper nearly at 100% CPU

### ISSUE THREAD

**Issue by DLevai94** [Microsoft/vscode#36038] opened 2017-10-11 08:43 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
material-icon-theme|PKi|2.2.2
vscode-eslint|dba|1.3.2
vscode-babel-coloring|dza|0.0.4
flow-for-vscode|flo|0.7.2
debugger-for-chrome|msj|3.3.1
highlight-matching-tag|vin|0.4.4
vscode-react-native|vsm|0.4.2
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

Activity monitor:
<img width="613" alt="screen shot 2017-10-11 at 10 41 29" src="https://user-images.githubusercontent.com/15244882/31430314-d0b999e2-ae70-11e7-93e5-4234f02255a5.png">

`ps aux 66529` result:
<img width="1677" alt="screen shot 2017-10-11 at 10 42 50" src="https://user-images.githubusercontent.com/15244882/31430411-0ed23b58-ae71-11e7-9607-4f017eb676ec.png">

---

Steps to Reproduce:

1. Open VSCode
2. Open a project

Reproduces without extensions: No

**Comment by drinktee** [comment] 2017-10-11 08:48
I met this too. IntelliSense show very slow.

**Comment by DLevai94** [comment] 2017-10-11 13:30
I've uninstalled some extensions. Same issue. <img width="1680" alt="screen shot 2017-10-11 at 15 27 41" src="https://user-images.githubusercontent.com/15244882/31443172-f5c76818-ae98-11e7-9fbf-fc675b9a477f.png">

**Comment by lancetharper** [comment] 2017-10-11 17:13
Code Helper continues to run at 100% CPU even after quitting VSCode

**Comment by mjbvz** [comment] 2017-10-11 21:30
@DLevai94 Does it reproduce if you disable all extensions? Can you share the full command line arguments of process with the high cpu usage

**Comment by eskild** [comment] 2017-10-13 06:51
I get similar symptoms in C++ context on Linux; ~/.vscode/extensions/ms-vscode.cpptools-0.13.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux runs at 100% continuously. I've now resorted to a small script that'll kill all such processes. Then it'll run and IntelliSense will be usable for a few minutes, and then we're back at 100%.

I finally got annoyed enough to attach gdb to the offending thread and got this trace; maybe it inspires some ideas. It smells like endless looping, perhaps due to wrong error handling in file I/O. I've often seen code that e.g. doesn't get it entirely right when, e.g., a file disappears under its feet and where it just keeps looping, reading from a file that no longer provides data. Particularly with sub-processes.

In my usecase I compile frequently, and part of our build process generates new C++ files that are then compiled into the final images. I wouldn't be surprised if VSCode got surprised about this "flapping" of files.

All the other processes are stuck in futex waits. Probably waiting for this one.

    #0  0x000000000073b3f9 in source_file_for_seq ()
    #1  0x000000000089982d in an_error_ptr_cmp::operator()(an_error* const&, an_error* const&) const ()
    #2  0x000000000089ae52 in an_error_manager::get_errors(std::__1::vector<an_error*, std::__1::allocator<an_error*> >&) ()
    #3  0x000000000053c6bd in edge::scoped_query_manager::get_filtered_errors_for_tu(edge::list<edge::error*>*, bool (*)(edge::error const&)) ()
    #4  0x000000000054484d in edge::an_edge_translation_unit_impl::get_filtered_errors_for_tu(edge::allocator*, edge::snapshot_session const*, bool (*)(edge::error const&), edge::isense_error_array*) ()
    #5  0x000000000050c2f0 in edge_intellisense_server_impl::handle_get_errors(microsoft::cpp::intellisense::GetErrorsRequest const&) ()
    #6  0x0000000000530c0d in work_queue::worker_proc() ()
    #7  0x000000000052d323 in std::__1::__function::__func<microsoft::vc::thread_pool::enqueue(std::__1::function<void ()>, std::__1::future<void>*)::{lambda()#1}, std::__1::allocator<{lambda()#1}>, void ()>::operator()() ()
    #8  0x00000000008bddbd in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
    #9  0x00000000008bdbad in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
    #10 0x00007f058bdcc184 in start_thread (arg=0x7f0583fff700) at pthread_create.c:312
    #11 0x00007f058baf1ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by DLevai94** [comment] 2017-10-13 09:41
@mjbvz I can't reproduce it with disabled extensions

**Comment by mjbvz** [comment] 2017-10-13 18:02
@eskild  Can you please try filing an issue against the c++ extension

@DLevai94 If you look at the full command line arguments of the process with high cpu usage, is there any indicator of which extension may be causing this?

**Comment by stkevintan** [comment] 2017-10-16 09:25
Comfirmed, at Windows 10 version 1.17.1

**Comment by mjbvz** [comment] 2017-10-26 23:01
Closing this issue as likely caused by an extension but we cannot investigate this without more info

@DLevai94 If you are still seeing this, please provide the full command line arguments of the code helper process with the high cpu usage

**Closed by mjbvz** 2017-10-26 23:01 UTC
Labels: javascript, needs more info
