### ISSUE TITLE
Unable to open VScode App

### ISSUE THREAD

**Issue by ankey87** [microsoft/vscode#89355] opened 2020-01-27 16:41 UTC
I keep getting an error that the application cannot be scanned for malicious content and needs to be updated. Need this for class tomorrow! Help!!!

**Comment by gjsjohnmurray** [comment] 2020-01-27 16:48
/duplicate of #74782, assuming you are on macOS (Catalina), which you didn't say.

**Closed** 2020-01-27 16:49 UTC
Labels: *duplicate, install-update
