### ISSUE TITLE
Opening data URI freezes VS Code

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#124942] opened 2021-05-30 19:42 UTC
Issue Type: <b>Bug</b>

I just CTRL+clicked a long data URI in a .css file and VS Code hung itself. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by dbaeumer** [comment] 2021-05-31 07:21
Starting with @aeschli because of css file.

**Comment by aeschli** [comment] 2021-05-31 12:37
Can you please add the small code sample that shows the link?

**Comment by frevds** [comment] 2021-05-31 13:33
Well no @aeschli, I can only add a big code sample for download: 
https://www.dropbox.com/s/pf4qt6xtj1bme03/vsc-datauri-issue.css?dl=1
VSCode reliably stops reacting when you try open the link.

**Comment by aeschli** [comment] 2021-06-01 17:47
The fix is to no longer show links for data URIs

**Comment by frevds** [comment] 2021-06-01 19:19
Yes, but what was the issue for the crash? 
On the other hand, having some kind of preview or other way of showing the data URI (if mimetype is image) would be benefitial for web developing (VSCode is natively equipped for showing such web content).

**Comment by aeschli** [comment] 2021-06-02 09:00
Once the css change is in (>= 1.58) the issue can still be reproduced by turning the data uri into a file:// - uri and clicking on it.

It seems the breadcrumbs view has problems with the resource URI with many path segments (over 2500 path segments)
![image](https://user-images.githubusercontent.com/6461412/120449918-29dd2d80-c390-11eb-9ea3-d591ebdbf6ca.png)

Also, there are messages printed to the console
event.ts:499 [477] potential listener LEAK detected, having 703 listeners already. MOST frequent listener (529):
check @ event.ts:499
_event._event @ event.ts:577
(anonymous) @ event.ts:92
(anonymous) @ event.ts:92
registerListeners @ labels.ts:156
i @ labels.ts:124
d @ labels.ts:258
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
render @ breadcrumbsControl.ts:133
_renderItem @ breadcrumbsWidget.ts:322
_render @ breadcrumbsWidget.ts:310
setItems @ breadcrumbsWidget.ts:279
U @ breadcrumbsControl.ts:305
update @ breadcrumbsControl.ts:311
openEditor @ tabsTitleControl.ts:405
doShowEditor @ editorGroupView.ts:1029
openEditor @ editorGroupView.ts:989
openEditor @ editorService.ts:523
async function (async)
openEditor @ editorService.ts:521
doOpenCodeEditor @ codeEditorService.ts:97
openCodeEditor @ codeEditorService.ts:70
open @ openerService.ts:82
open @ openerService.ts:183
async function (async)
open @ openerService.ts:176
M.resolve.then.L @ links.ts:332
Promise.then (async)
openLinkOccurrence @ links.ts:308
onEditorMouseUp @ links.ts:297
(anonymous) @ links.ts:151
fire @ event.ts:634
_onEditorMouseUp @ clickLinkGesture.ts:179
(anonymous) @ clickLinkGesture.ts:140
fire @ event.ts:634
oe.onMouseUp @ codeEditorWidget.ts:1662
emitMouseUp @ viewUserInputEvents.ts:76
emitMouseUp @ viewController.ts:310
_onMouseUp @ mouseHandler.ts:219
(anonymous) @ mouseHandler.ts:103
(anonymous) @ editorDom.ts:110
event.ts:500     at file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59226
    at Array.map (<anonymous>)
    at d.onDidChangeDecorations (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59219)
    at d.registerListeners (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:13379)
    at new i (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:12840)
    at new d (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:14923)
    at f._createInstance (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at f.createInstance (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at vo.render (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:30628)
    at f._renderItem (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2770)
    at f._render (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2630)
    at f.setItems (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2074)
    at U (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:34468)
    at ri.update (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:34571)
    at $t.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2577:11526)
    at Ci.doShowEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2653:16506)
    at Ci.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2653:16044)
    at x.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2491:25026)
    at async C.doOpenCodeEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:125440)

**Comment by aeschli** [comment] 2021-06-02 09:00
Once the css change is in (>= 1.58) the issue can still be reproduced by turning the data uri into a file:// - uri and clicking on it.

It seems the breadcrumbs view has problems with the resource URI with many path segments (over 2500 path segments)
![image](https://user-images.githubusercontent.com/6461412/120449918-29dd2d80-c390-11eb-9ea3-d591ebdbf6ca.png)

Also, there are messages printed to the console
event.ts:499 [477] potential listener LEAK detected, having 703 listeners already. MOST frequent listener (529):
check @ event.ts:499
_event._event @ event.ts:577
(anonymous) @ event.ts:92
(anonymous) @ event.ts:92
registerListeners @ labels.ts:156
i @ labels.ts:124
d @ labels.ts:258
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
render @ breadcrumbsControl.ts:133
_renderItem @ breadcrumbsWidget.ts:322
_render @ breadcrumbsWidget.ts:310
setItems @ breadcrumbsWidget.ts:279
U @ breadcrumbsControl.ts:305
update @ breadcrumbsControl.ts:311
openEditor @ tabsTitleControl.ts:405
doShowEditor @ editorGroupView.ts:1029
openEditor @ editorGroupView.ts:989
openEditor @ editorService.ts:523
async function (async)
openEditor @ editorService.ts:521
doOpenCodeEditor @ codeEditorService.ts:97
openCodeEditor @ codeEditorService.ts:70
open @ openerService.ts:82
open @ openerService.ts:183
async function (async)
open @ openerService.ts:176
M.resolve.then.L @ links.ts:332
Promise.then (async)
openLinkOccurrence @ links.ts:308
onEditorMouseUp @ links.ts:297
(anonymous) @ links.ts:151
fire @ event.ts:634
_onEditorMouseUp @ clickLinkGesture.ts:179
(anonymous) @ clickLinkGesture.ts:140
fire @ event.ts:634
oe.onMouseUp @ codeEditorWidget.ts:1662
emitMouseUp @ viewUserInputEvents.ts:76
emitMouseUp @ viewController.ts:310
_onMouseUp @ mouseHandler.ts:219
(anonymous) @ mouseHandler.ts:103
(anonymous) @ editorDom.ts:110
event.ts:500     at file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59226
    at Array.map (<anonymous>)
    at d.onDidChangeDecorations (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59219)
    at d.registerListeners (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:13379)
    at new i (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:12840)
    at new d (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:14923)
    at f._createInstance (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at f.createInstance (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at vo.render (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:30628)
    at f._renderItem (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2770)
    at f._render (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2630)
    at f.setItems (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:124:2074)
    at U (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:34468)
    at ri.update (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2009:34571)
    at $t.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2577:11526)
    at Ci.doShowEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2653:16506)
    at Ci.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2653:16044)
    at x.openEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2491:25026)
    at async C.doOpenCodeEditor (file:///C:/Users/martinae/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:125440)

**Comment by jrieken** [comment] 2021-06-07 09:56
Many thing go wrong here ;-) It starting going south by the link being detected not as data-uri but as relative uri. So, there is an attempt to open `file:///the/current/file.txt/data:image/png;base64;<load-of-data>`. Because this is now a proper scheme (`file`) breadcrumbs and the decoration service do their work. For them it seems like a file a very long path segment and that make them take a while...

<img width="647" alt="Screen Shot 2021-06-07 at 11 47 39" src="https://user-images.githubusercontent.com/1794099/120996818-f7b03f00-c786-11eb-8a76-2e544a09fefe.png">

**Comment by jrieken** [comment] 2021-06-07 10:14
<img width="656" alt="Screen Shot 2021-06-07 at 12 11 18" src="https://user-images.githubusercontent.com/1794099/120999522-802fdf00-c789-11eb-816b-23f337ca87e0.png">


@aeschli It seems that one of your extensions is creating these `ProtocolDocumentLink` instances (search shows usages in json, html, and css). The problem is that those links are false (joined with base) and when opened cause call kinds of issues. 

The workbench could protect against this but I wouldn't even know where because every single compare is falling apart, every storage is overflown etc...

**Comment by jrieken** [comment] 2021-06-07 10:28
I have pushed a change to drop too long links already on the extension host side

**Comment by aeschli** [comment] 2021-06-07 14:27
@jrieken Agree, the links are bogus, and I've pushed a fix in css to ignore data links. Just found it interesting that the breadcrumbs was running hot.
Dropping very long links makes sense, thanks for the fix.

**Closed by aeschli** 2021-06-07 14:27 UTC
Labels: bug, freeze-slow-crash-leak

**Comment by jrieken** [comment] 2021-06-07 14:31
Hugs of death
