### ISSUE TITLE
Can't open an ipynb from Windows explorer

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#145267] opened 2022-03-16 20:48 UTC
Version: 1.66.0-insider (user setup)
Commit: 6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f
Date: 2022-03-16T05:17:27.938Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22572

1. Trying to open a .ipyb file from Windows explorer results in this error:

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/11685408/158687936-309329b6-5140-4ae6-9092-ea1e296f322c.png">

I can open the same ipynb file from the VS Code file menu though.

**Comment by greazer** [comment] 2022-03-16 20:48
Assigning per suggestion from @rebornix.

**Comment by mjbvz** [comment] 2022-03-16 22:24
Duplicate of #122951

**Closed by mjbvz** 2022-03-16 22:24 UTC
