### ISSUE TITLE
Unexpected intellisense order with underscore prefix

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#66005] opened 2019-01-04 03:21 UTC
Maybe it's always done this and I'm only just hitting this, I think _addons should score best here:

![image](https://user-images.githubusercontent.com/2193314/50672376-91f37380-0f8c-11e9-95b2-36b6f8bcfacc.png)

Also the fact that the s and n are out of order in the best match is weird.

Not sure if this is TS or our algorithm?

**Comment by usernamehw** [comment] 2019-01-04 03:40
At least it shows up (unlike `$` at the beginning of the word).

**Comment by Tyriar** [comment] 2019-01-04 04:04
@usernamehw ?

![image](https://user-images.githubusercontent.com/2193314/50673467-c2d6a700-0f92-11e9-87ba-ad82807eb774.png)

**Comment by Tyriar** [comment] 2019-01-04 05:45
@usernamehw oh when you want `this.` filled in for you. The cause there is likely that tsserver isn't including those symbols to vscode. @mjbvz thoughts?

**Comment by mjbvz** [comment] 2019-01-05 02:52
@usernamehw I think `$` is treated like any other letter. `xaddon` also will not show in this case:

```js
class C {
	addon() { }
	_addon() { }
	xaddon() { }

	method() {
		addon|
	}
}
```

Not sure about why `_` is treated differently. We don't seem to be doing anything special on the TS side and after debugging through the suggest model I still don't understand. @jrieken do you know why completions with an `_` prefix would still show up here?

**Comment by DeminMaxim** [comment] 2019-01-06 02:40
Duplicate of # @jrieken

**Comment by jrieken** [comment] 2019-01-07 09:12
> @usernamehw I think $ is treated like any other letter.

Yes, unlike `_` and others is `$` not a listed a separator character and therefore it scores like a normal/weak characters. 

@Tyriar Nothing has changed in how we score. The `_addons` suggestion has a lower score because the first character didn't match, in contrast to `addOscHandler` - here also an upper-case character is hit which gives even more bonus points. The ordering can be configured via `editor.suggest.filterGraceful` but I am not yet sure how to tweak the rest...

**Comment by Tyriar** [comment] 2019-01-07 15:14
@jrieken thanks, will try running with `editor.suggest.filterGraceful` for a while. It's a shame I need to turn off the typo detection to get this though, ideally for me it would show all results from filterGraceful=true, but when the search term appears exactly somewhere in the result it should match higher, so for the OP screenshot:

```
_addons        // Scores highest despite the initial underscore
addonTest      // Te before s, not exact match
addOscHandler  // scHa before n, no s
_wrapAddonDispose
addDisposableListener
```

**Comment by jrieken** [comment] 2019-01-07 15:45
>  It's a shame I need to turn off the typo detection to get this though, ideally for me it would show all results from filterGraceful=true, but when the search term appears exactly somewhere in the result it should match higher, so for the OP screenshot:

I understand - it involves fiddling but I can try to penalise type-matches more.

**Closed** 2020-11-10 10:35 UTC
Labels: *out-of-scope, suggest, under-discussion
