### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by cfcodefans** [microsoft/vscode#212395] opened 2024-05-09 21:59 UTC
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: unifiedjs.vscode-mdx, VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700T (20 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (36.47GB free)|
|Process Argv|--crash-reporter-id 0aa270f1-402a-46e8-bf27-a18a3b9ffd6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
vscode-zipfs|arc|3.0.0
vscode-tailwindcss|bra|0.10.5
prettier-vscode|esb|10.4.0
go|gol|0.41.4
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
live-server|ms-|0.4.13
vscode-react-native|msj|1.13.0
vshaxe|nad|2.31.0
vscodeintellicode-completions|Vis|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
chatpanelc:31018788
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31043157
a69g1124:31038041
pythonprc:31039816
dwnewjupytercf:31039676

```

</details>

**Comment by mjbvz** [comment] 2024-09-23 22:19
Closing as most likely caused by one of the extensions listed in the issue text. Please try disabling these. If everything works with them disabled, file an issue agains those extension so they can investigate

**Closed by mjbvz** 2024-09-23 22:19 UTC
Labels: *caused-by-extension
