### ISSUE TITLE
No files listed under "Open Recent"

### ISSUE THREAD

**Issue by TSchremser** [microsoft/vscode#85373] opened 2019-11-22 08:41 UTC
Issue Type: <b>Bug</b>

Recently I cleared the files in "Open Recent" using the "Clear Recently Opened" command from the "File" menu. Since then files that I open won't be listed and "Open Recent" is always empty.

It works however to show me recently opened folders.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3512)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.6.0
xml|Dot|2.5.0
vscode-todo-plus|fab|4.14.1
gc-excelviewer|Gra|2.1.32
rest-client|hum|0.23.0
ilspy-vscode|ics|0.7.10
reg|ion|1.0.1
svn-scm|joh|2.1.3
hg|mrc|1.3.0
mssql|ms-|1.7.1
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
rss|rs|1.0.0
vscode-fileutils|sle|3.0.0
vscode-hexdump|sle|1.7.2
selectline-statusbar|tom|0.0.2
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.9.0

</details>

**Comment by egamma** [comment] 2019-11-22 09:29
Duplicate of #84421 that will be release in the next recovery build very soon.

**Closed by egamma** 2019-11-22 09:29 UTC
