### ISSUE TITLE
Trash and FileSystemProvider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48259] opened 2018-04-20 08:20 UTC
Today, when you delete a file you can asked if you want to move the file to trash. On remote file systems that must not exist and by default we should confirm permanent deletion. 

<img width="752" alt="screen shot 2018-04-19 at 12 26 18" src="https://user-images.githubusercontent.com/1794099/39038709-761c2af4-4484-11e8-94a5-f0747c02a6a6.png">

**Comment by isidorn** [comment] 2018-04-20 08:45
@jrieken Makes sense.
I can look at the uri and only if it is a `file` scheme to offer to go to trash
An alternative is to look into some central place to see what `FileSystemProvider` is responsible for my uri and then check if that `FileSystemProvider` is remote. Is there some place like that?

**Comment by jrieken** [comment] 2018-04-20 08:51
We could have something on `IFileService`, contributed providers have the notion of [`capabilities`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L187) and we could that in some form.

**Comment by isidorn** [comment] 2018-04-20 09:12
Yeah a `capability` makes sense. Assigning this to May to fix once we decide on the `capabilites` strategy

**Comment by cedric05** [comment] 2018-04-30 09:45
this issue seems to be good first issue. 
1) shall i work on it ? 
2) any other plans?
@isidorn @jrieken

**Comment by isidorn** [comment] 2018-05-18 13:02
We were focused on grid this milestone, next week I am on vacation, this is not for endgame -> June

**Comment by cedric05** [comment] 2018-05-18 15:32
@isidorn i vaguely tried even though you had plans.
please review #50114
i'm happy to close

**Comment by isidorn** [comment] 2018-06-21 15:11
Pushing this to July
@jrieken I could add a new capability, something like `supportsTrash`.
When would a FileSystem specify this, also on registration like `isReadonly`?

**Comment by jrieken** [comment] 2018-06-21 15:39
Yeah, maybe a capability but we don't really know where the trash can of a provider is...

**Comment by isidorn** [comment] 2018-06-21 16:05
Yeah the issue is if he supports it...

**Comment by gjsjohnmurray** [comment] 2018-11-29 12:58
Now more implementations of `FileSystemProvider` are appearing please can this issue be addressed soon? As things stand, users are given a false sense of security by being told their deleted file will be recoverable from the Recycle Bin.

**Comment by bpasero** [comment] 2019-03-20 17:41
@isidorn @jrieken this is coming up in my file service rework. I feel like the "trash" should not be part of a file system provider at all and thus should move out of the file service world. The only real possible trash implementation is for files on disk imho and that is what our UI implies also.

As of today there are only 2 users of the trash:
* the "Delete" action in the file explorer
* the bulk edit service

"Delete" Action: this action should move into electron-browser and directly use electron API to access the trash if and only if the file has a file:// scheme

Bulk Edit Service: imho this one should not move things to trash. I find it weird that an automated thing that runs fills stuff into the trash without user notice. 

Moving to March for consideration.

**Comment by jrieken** [comment] 2019-03-21 08:57
> The only real possible trash implementation is for files on disk imho and that is what our UI implies also.

Not so sure about that. Think of a file system that simply exposes my *nix-user account over sftp. The concept of a trash-can exists there and exposing that makes sense. In the end, trash is just a special folder into which files get moved instead of deleted.

**Comment by bpasero** [comment] 2019-03-21 09:23
I am fine either way, but I feel like we need to do a change at least that the dialog does not wrongly imply we move to the trash when we cannot.

**Comment by jrieken** [comment] 2019-03-21 09:43
Yeah, 💯. We should only show the dialog like that when there actually is support for trash

**Comment by isidorn** [comment] 2019-03-21 10:50
I can move the delete action into electron-browser and use electron API.
However the explorer is depending on that action, and that could have consequences that parts of the explore need to be moved back to electron-browser which does not make sense. So we should also fix how this action is contributed, that we can simply contributed from a .contribution file to the explorer menu.

**Comment by bpasero** [comment] 2019-03-25 08:26
@isidorn @jrieken I think having the capability is OK, I added it via https://github.com/Microsoft/vscode/commit/8288794f50dfd08e9fa23e950a57a61c0ff0c0e7 (`FileSystemProviderCapabilities.Trash = 1 << 12`)

This means that we now clearly tell the user that moving to trash does not work if the file system does not support it, which is better than before. Still, the full fix is to surface this in the UI, e.g. by not even showing the normal "Delete" action but "Delete Permanently" if the provider for the resource does not provide that. 

I also added `IFileService.hasCapability(resource, capability)` to ask for a capability given a resource. This currently returns a `Promise<boolean>` because of the activation of the provider which probably makes it less ideal for the action in the explorer. We can also change the method to a sync variant, though that might return wrong results if the provider is not activated yet...

I left the bulk edit service to use the trash and check for it, though I still think it should bypass the trash always.

**Comment by isidorn** [comment] 2019-03-27 13:26
Not for endgame. Will do it in debt week -> april

**Comment by isidorn** [comment] 2019-04-02 10:45
@bpasero yes, let's fix this nicely with context keys. I suggest:
* You make the `hasCapability` sync so I can nicely use it. Returning wrongs results if it is not activated yet is fine for my use case I believe
* I will add a context key "explorerResourceCanBeMovedToTrash". This context key will get updated as the explorer focus changes
* I will properly contribute the commands based on this context key so we always show the correct one

**Comment by isidorn** [comment] 2019-04-02 13:36
@bpasero I have changed the hasCapability to be sync. And I have introduced the context key "explorerResourceMoveableToTrash". So we do not show the move to trash command when it is not applicable.
I tried it out and works decent. Check it out and let me know what you think. Thanks

**Closed by isidorn** 2019-04-02 13:36 UTC
Labels: feature-request, file-explorer, remote

**Comment by bpasero** [comment] 2019-04-02 16:36
@isidorn you cannot really make a statement about a provider capability without awaiting to resolve it, do you? Now, if someone manages to ask for a capability before the provider has been activated, the code would make a wrong assumption, no?

**Comment by isidorn** [comment] 2019-04-03 09:03
@bpasero yes. If you ask a provider if it has a capability and it is not activated it would return false.
From a logical perspective this is not so contradictory since it is not activiated he has not capabilities currently for anything.
Otherwise the method should be called activateAndCheckCapability.
If this makes zero sense to you let me know and I can return it to be promise based and try to fix this on the explorer side.

**Comment by bpasero** [comment] 2019-04-03 09:30
@isidorn let's leave it and see if there is any issue 👍
