### ISSUE TITLE
German translation in Open URL dialog ("Eröffnungskurs") is wrong

### ISSUE THREAD

**Issue by tobbi** [microsoft/vscode#87299] opened 2019-12-19 00:24 UTC
- VSCode Version:
Version: 1.42.0-insider
Commit: 26f5dfcd76c9a02f116a706844611aeb09ae8c0b
Datum: 2019-12-18T10:32:01.697Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
- OS Version:Darwin x64 17.7.0

Steps to Reproduce:

1. Write a complete URL in VS Code.
2. Cmd+Click it

Wrong German translation "Eröffnungskurs" for Open button

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by IllusionMH** [comment] 2019-12-30 14:18
/duplicate of #87811

I know that this one was reported earlier, but #87811 has more context in description and same assignee.

**Closed** 2019-12-30 14:18 UTC
Labels: *duplicate
