### ISSUE TITLE
Language mode is detected wrongly for Dotenv files

### ISSUE THREAD

**Issue by volodymyr-nexxt** [microsoft/vscode#132269] opened 2021-09-03 14:56 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.60.0** (commit: **e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff**)
- OS Version: **macOS 10.15.6**

Steps to Reproduce:

1. Open a `.env` file
2. Immediately after I open the file, the detected language mode is "Environment variables" as expected, however, it's switched to "Ini" after a second.

The name of the file I used is just `.env`.

**Comment by gjsjohnmurray** [comment] 2021-09-03 15:00
See https://github.com/microsoft/vscode/issues/132173#issuecomment-912461828 for a pointer on how to disable language detection for a specific language mode.

**Comment by TylerLeonhardt** [comment] 2021-09-03 18:52
duplicate of #132173

**Closed** 2021-09-03 18:53 UTC
Labels: *duplicate, new release
