### ISSUE TITLE
Should user be notified if terminal integration doesn't work with a given prompt?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#141466] opened 2022-01-25 18:26 UTC
Testing #141339

I changed my pwsh prompt to "My Prompt ", and then terminal integration stopped working, but when I hovered over the terminal tab, it still said the feature was enabled. In other words, the feature fails gracefully, because I saw no notifications, console logs, or crashes, but at the same time, I wonder if there should be some way the user knows their prompt isn't supported, other than questioning why the feature isn't working for them.

**Comment by Tyriar** [comment] 2022-01-25 18:37
Was going to say there's nothing we can do but I think we can actually detect this case by looking out for multiple `133;C` sequences in a row. Could be a good first use of the remove capability?

**Comment by Tyriar** [comment] 2022-01-31 17:44
Think this is a duplicate of https://github.com/microsoft/vscode/issues/141764

**Closed by Tyriar** 2022-01-31 17:44 UTC
Labels: polish, terminal-shell-integration
