### ISSUE TITLE
Always default to enter the Source Control Bar first, when the Activity Bar Position is set to top and open a project on WSL

### ISSUE THREAD

**Issue by CcccFz** [microsoft/vscode#198166] opened 2023-11-14 01:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.84.2 (system setup)
- OS Version:  windows11 and WSL (ubuntu 20.02)

Steps to Reproduce:

1. Activity Bar Position is set to top
2. Open a project on WSL

Bug Desciption:
When the Activity Bar Position is set to top and open a project on WSL, it always default to enter the Source Control Bar first.
![image](https://github.com/microsoft/vscode/assets/11456678/f486cdee-ad09-4a3f-92fc-044cca43308e)

But when open a project on Windows, it is normal to enter the Explorer Bar first and does not have this problem.
![image](https://github.com/microsoft/vscode/assets/11456678/b3224c46-18fc-41a7-95f5-21c36865c033)

**Comment by lszomoru** [comment] 2023-11-14 13:22
@sandy081, could you please take a look at this? 
Am I doing something wrong or this is an issue with the activity bar on top? Thanks!

**Comment by sandy081** [comment] 2023-11-15 09:00
I am not able to reproduce this with SSH. I do not think it is not different than other remote. It would be great if you can repro it and share steps.

**Comment by CcccFz** [comment] 2023-11-17 02:45
![vscode](https://github.com/microsoft/vscode/assets/11456678/11e89563-8b3f-4530-a504-69052cb569ef)

@sandy081 This gif is steps to reproduce. I use the same project to open with windows11 (local) and wsl (remote) respectively

**Comment by sandy081** [comment] 2023-11-29 14:45
Does reloading the window with explorer view on focus, retains the explorer view? Also please try the same with other views like Debug.

**Comment by sandy081** [comment] 2024-01-17 08:53
Closing this because as requested information is not provided.

**Closed by sandy081** 2024-01-17 08:53 UTC
