### ISSUE TITLE
VScode rg process taking all the CPU MacBook Pro

### ISSUE THREAD

**Issue by gadatos** [microsoft/vscode#235527] opened 2024-12-06 22:20 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95
- OS Version: macOS 15.1.1
- 

Steps to Reproduce:

When I open the terminal in VS Code and delete anything from the command line, e.g., the node_modules folder, my computer freezes and many rg processes are launched.

I’ve already tried all the solutions from the previous thread.

My setup: • VS 
 • MacBook Pro M2 • macOS 15.1

**Comment by gadatos** [comment] 2024-12-07 07:53
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.3. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

The issue persists even in version 1.95.3. Here are the details.
![Image](https://github.com/user-attachments/assets/e2aa537d-eb25-4467-805a-2d506e4f5f45)

![Image](https://github.com/user-attachments/assets/d1afd769-f9fa-42ea-b3a6-8febb6652c03)

**Comment by justschen** [comment] 2024-12-13 01:26
looks like duplicate of https://github.com/microsoft/vscode/issues/233703. I'll close this for now, feel free to update that thread with any additional information, thanks!

**Closed by justschen** 2024-12-13 01:26 UTC
Labels: performance
