### ISSUE TITLE
Profile Select Bug

### ISSUE THREAD

**Issue by SunSeaLucky** [microsoft/vscode#225685] opened 2024-08-15 11:25 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.92.1 (user setup)
- OS Version: Windows NT x64 10.0.22631

Steps to Reproduce: Click `Profile` > `New Profile`. And I try to choose configure in my Profile. But once I click any one of the choices, all of them will be like the pic and all choices are no longer clickable with displaying "The profile should contain at least one configuration". 

I cannot make any one of them ticked even I uninstalled VSCode and cleared `%APPDATA%\Code` and `%USERPROFILE%\.vscode`. All the operations I can do now is only to press `Esc` to dismiss it.

![image](https://github.com/user-attachments/assets/1d6517b6-c1d1-4d39-807e-fb0761e208df)

**Comment by gjsjohnmurray** [comment] 2024-08-15 12:18
/duplicate of #224788 which offers a workaround.

**Closed** 2024-08-15 12:19 UTC
Labels: *duplicate, triage-needed
