### ISSUE TITLE
Crash, VS Code not starting

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/vscode#84914] opened 2019-11-15 12:54 UTC
- VSCode Version: Newest insiders version
- OS Version: WIN 10

Steps to Reproduce:

1. Start Code
2. Wait until message says that it is unresponsive
Tried with Code -n same respons
![image](https://user-images.githubusercontent.com/25152707/68944713-d0fa7400-07ae-11ea-8d28-10741a02e5c2.png)

Does this issue occur when all extensions are disabled?: Yes/No
Same response
![image](https://user-images.githubusercontent.com/25152707/68944831-29ca0c80-07af-11ea-963f-fe2c83aede29.png)

**Comment by chanhong** [comment] 2019-11-15 18:49
I have this same issue when I upgrade VS code to 1.40.1 on Windows 2016 with Citrix installed so I have to uninstall and install the previous version which is running just fine.

**Comment by Rukkulakki** [comment] 2019-11-18 09:07
I can confirm chanhongs solution. 
Uninstalled VS Code, and installed 1.39.2. And system is now back up and running.

**Comment by deepak1556** [comment] 2019-11-18 23:53
@Rukkulakki do you also have citrix installed ?

I don't know about citrix, what is it ? can you provide me simple steps to repro this issue ?

**Comment by Rukkulakki** [comment] 2019-11-19 07:53
@deepak1556 Citrix XenServer is for Server virtualization https://www.citrix.com/products/citrix-hypervisor/ 
I am connecting from Win 10 using Citrix Workspace 1909 (19.9.0.21) to a machine running Citrix XenServer (7.1.843) On that XenServer the VS Code 1.40.1 will hang when you try to start it.
After I downgraded it yesterday it worked all day, and this morning it has upgraded itself, and stopped working again.
Uninstalled 1.40.1 and reinstalled 1.39.2 and it runs again. So definitely something in the 1.40.1 version that is incompatible with the Citrix Environment.

**Comment by pilavdzic** [comment] 2019-11-19 18:49
Lots of the federal government uses Citrix, and requres developers to log into this from home so that all work is done within the secure environment. I hope a developer is able to reproduce this because I am running into this issue also, had to roll back to a previous version and now can no longer update which will become a major problem over time.

**Comment by deepak1556** [comment] 2019-11-20 07:29
Thanks for the context, can you check if launching `code --disable-gpu` helps ?

**Comment by Rukkulakki** [comment] 2019-11-20 07:40
Sorry, no effect
![image](https://user-images.githubusercontent.com/25152707/69218643-72981180-0b71-11ea-9640-a9293cc86a42.png)

**Comment by deepak1556** [comment] 2019-11-20 09:17
@Rukkulakki what does `code --disable-gpu --verbose` print ? Also is it possible for you attach the logs from the folder under `C:\Users\dt-sh\AppData\Roaming\Code\logs` or from within the editor if its responsive by using command palette `Developer: Open logs folder` ?

**Comment by Rukkulakki** [comment] 2019-11-20 10:02
C:\Users\dt-sh\AppData\Local\Programs\Microsoft VS Code>
 [main 2019-11-20T09:57:55.512Z] Starting VS Code
[main 2019-11-20T09:57:55.512Z] from: c:\Users\dt-sh\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2019-11-20T09:57:55.512Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': true,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false
}
[main 2019-11-20T09:57:55.512Z] Resolving machine identifier...
[main 2019-11-20T09:57:55.512Z] Resolved machine identifier: 7cb436188f53620334f99f533473353004f8a82ae5461f9fd352a4fac92a51bd (trueMachineId: undefined)
[main 2019-11-20T09:57:55.590Z] update#setState idle
[main 2019-11-20T09:57:55.590Z] [storage state.vscdb] open(c:\Users\dt-sh\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2019-11-20T09:57:55.590Z] lifecycle (main): phase changed (value: 2)
[main 2019-11-20T09:57:55.590Z] windowsManager#open
[main 2019-11-20T09:57:55.668Z] lifecycle (main): phase changed (value: 3)
[main 2019-11-20T09:57:55.683Z] telemetry/optInStatus { optIn: true }
[main 2019-11-20T09:57:55.683Z] telemetry/update:win32SetupTarget { target: 'user' }
[main 2019-11-20T09:57:55.683Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2019-11-20T09:57:55.855Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
[main 2019-11-20T09:57:55.918Z] [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 2019-11-20T09:57:55.918Z] [storage state.vscdb] getItems(): 53 rows
[main 2019-11-20T09:57:55.918Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2019-11-20T09:57:55.965Z] getShellEnvironment: running on Windows, skipping
[main 2019-11-20T09:57:56.027Z] [storage state.vscdb] updateItems(): insert(Map(2) {telemetry.lastSessionDate => Wed, 20 Nov 2019 09:55:43 GMT, telemetry.currentSessionDate => Wed, 20 Nov 2019 09:57:55 GMT}), delete(Set(0) {})
[main 2019-11-20T09:57:56.027Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2019-11-20T09:57:56.027Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Wed, 20 Nov 2019 09:55:43 GMT'),('telemetry.currentSessionDate','Wed, 20 Nov 2019 09:57:55 GMT')
[main 2019-11-20T09:57:56.027Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2019-11-20T09:58:25.595Z] update#checkForUpdates, state =  idle
[main 2019-11-20T09:58:25.595Z] update#setState checking for updates
[main 2019-11-20T09:58:25.595Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/stable/8795a9889db74563ddd43eb0a897a2384129a619
[main 2019-11-20T09:58:25.767Z] update#setState idle
[main 2019-11-20T09:58:25.767Z] telemetry/update:notAvailable { explicit: false }
[main 2019-11-20T09:58:25.861Z] [VS Code]: detected unresponsive
[main 2019-11-20T09:58:25.861Z] telemetry/windowerror { type: 1 }
[20191120T092047.zip](https://github.com/microsoft/vscode/files/3868534/20191120T092047.zip)
[20191120T105755.zip](https://github.com/microsoft/vscode/files/3868535/20191120T105755.zip)

**Comment by Rukkulakki** [comment] 2019-11-20 10:06
[logs.zip](https://github.com/microsoft/vscode/files/3868577/logs.zip)

**Comment by deepak1556** [comment] 2019-11-20 11:00
Thanks for the logs, I don't see anything that points to an issue except the window has become unresponsive. Is there a particular set of operations you perform before the freeze happens ? Does it happen even when operating on a simple text file ?

One last attempt at getting detailed log, can you follow the steps from https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows  and attach the crash report.

**Comment by pilavdzic** [comment] 2019-11-20 12:54
It happens as the app is trying to launch, before you can perform any
operations.

--disable-gpu made a black resizable window appear for me.

**Comment by Rukkulakki** [comment] 2019-11-20 13:02
You asking if it failed with a simple file made my try to start it with a reference to the Workspace folder. And although it was very slow to start, it actually managed to start without the error/message box about it being unresponsive. But it turned out to make the problem slightly worse.

Now running code.exe is just hanging, without notifying about it being unresponsive.
Running it from command prompt referencing folder returns as unresponsive after a little longer time than originally. Same result when referring to specific file.
Adding it to taskbar and starting a recent workspace from there also returns as unresponsive after a while.

Crash logfiles from just running code.exe before the original reference to a workspace.

[Code__PID__8088__Date__11_20_2019__Time_01_45_58PM__646__Log.txt](https://github.com/microsoft/vscode/files/3869268/Code__PID__8088__Date__11_20_2019__Time_01_45_58PM__646__Log.txt)
[Code__PID__13980__Date__11_20_2019__Time_01_45_59PM__255__Log.txt](https://github.com/microsoft/vscode/files/3869269/Code__PID__13980__Date__11_20_2019__Time_01_45_59PM__255__Log.txt)
[Code__PID__14412__Date__11_20_2019__Time_01_45_59PM__443__Log.txt](https://github.com/microsoft/vscode/files/3869270/Code__PID__14412__Date__11_20_2019__Time_01_45_59PM__443__Log.txt)
[Code__PID__3348__Date__11_20_2019__Time_01_45_58PM__443__Log.txt](https://github.com/microsoft/vscode/files/3869271/Code__PID__3348__Date__11_20_2019__Time_01_45_58PM__443__Log.txt)

**Comment by deepak1556** [comment] 2019-11-20 14:43
Thanks for the crash reports, based on it can say its related to https://support.citrix.com/article/CTX265011 , can you try the solution described there for VSCode executable ?

**Comment by deepak1556** [comment] 2019-11-20 18:20
Also for a more permanent fix to avoid Citrix installing hooks with VSCode , can try https://support.citrix.com/article/CTX224067 . This should help with future versions, not sure if your company policy will allow this but the previous solution should work as a temporary solution.

**Comment by Rukkulakki** [comment] 2019-11-20 18:25
I can confirm that the first Registry entry addition works! Have not tried the second yet, but will discuss it with the Citrix people. Thank you @deepak1556 
![image](https://user-images.githubusercontent.com/25152707/69266436-7062a100-0bcb-11ea-9538-4efa400a4e4b.png)

**Comment by deepak1556** [comment] 2019-11-20 18:56
Great, thanks for verifying. Closing this out as no further action can be taken on vscode end.

**Closed by deepak1556** 2019-11-20 18:56 UTC
Labels: needs more info

**Comment by pilavdzic** [comment] 2019-11-22 22:11
I am having the same issue when using Remote Desktop, only the registry key fix issue is not solving it for me, are there any other possible solutions to this?

**Comment by pilavdzic** [comment] 2019-11-22 22:16
Or perhaps I just don't understand how to do the registry fix correctly, the instructions say to edit CtxHook, but the screenshot above shows SfrHook

**Comment by dpalchuk** [comment] 2019-12-06 22:03
> I can confirm that the first Registry entry addition works! Have not tried the second yet, but will discuss it with the Citrix people. Thank you @deepak1556
> ![image](https://user-images.githubusercontent.com/25152707/69266436-7062a100-0bcb-11ea-9538-4efa400a4e4b.png)

Worked as well on 2016 RDS with Citrix.
