### ISSUE TITLE
TERMINAL works badly with national (Cyrillic) symbols

### ISSUE THREAD

**Issue by ms27** [Microsoft/vscode#26075] opened 2017-05-05 20:21 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|2.0.3|
|ejs-language-support|QassimFarid|0.0.1|;

---

Steps to Reproduce:

1. open Terminal
2. enter Cyrillic symbols

Result:

![2017-05-05_23-13-40](https://cloud.githubusercontent.com/assets/8489323/25762770/c0ca02f6-31e8-11e7-8ca9-1cd5190a8e4e.png)

**Comment by kieferrm** [comment] 2017-05-05 22:42
This is a duplicate of #19665.

**Closed by kieferrm** 2017-05-05 22:42 UTC
