### ISSUE TITLE
Document close events not triggering unless tab is focused first

### ISSUE THREAD

**Issue by freebroccolo** [Microsoft/vscode#13363] opened 2016-10-07 17:47 UTC
- VSCode Version: 1.5.3 or 1.6.0-insider or built from master (tried at ee9bb45d82dcc4343e32b01f8a626c3910248553)
- OS: macOS 10.12

It appears that when multiple documents are open in separate tabs, if you click to close one of the tabs which is *not the currently focused one*, the expected close events never trigger for the closed document.

The expected behavior is that the `onDidClose` or `onDidCloseTextDocument` events would trigger depending on whether or not one is using full or incremental synchronization. But if the tab which is closed is not focused first, the event never fires.

A practical consequence of this is that I use the close events to clear diagnostics, so if the user closes the tab for a non-focused document, the diagnostic messages are not cleared.

Note that this describes what happens with `vscode-languageserver-node` in my own extension, but based on observations of similar extensions which do not use the language server, the same issue occurs (e.g., diagnostics not cleared properly without focusing first).

**Comment by jrieken** [comment] 2016-10-08 06:24
Closing an editor doesn't always mean that the underlying document is being disposed. There are different strategies how/when the editor disposes the models

**Comment by jrieken** [comment] 2016-10-08 06:26
@freebroccolo Please add more precise steps, esp I need to know if those tab were just *fake* open. eg. after refreshing VS Code or if you have opened them both in that session. Also, I need to know if other editors slots are open.

Ideally, add the stripped down version your extension (using the API as you claim) and steps that allow me to reproduce

**Comment by freebroccolo** [comment] 2016-10-08 07:06
@jrieken Okay, I will try to provide more details later today, maybe along with a little animation.

But what I was observing earlier was basically like this:

1. open Code
2. open file1 (double click in tree view, opens in tab1)
3. open file2 (double click in tree view, opens in tab2)
4. focus tab2
5. edit file2 to trigger diagnostics
6. focus tab1 (diagnostics from file2 still show as expected)
7. click close button on tab2 without focusing
8. tab2 closes but close event (e.g., `onDidCloseTextDocument`) for file2 doesn't trigger (diagnostics still show since close event wasn't received to clear them)

Now if I replace step 7 with:

7a. focus tab2
7b. click close button on tab2

Then the `onDidCloseTextDocument` event does trigger and everything works as expected.

This behavior I'm describing happens with a fresh load of the Code editor, without refreshing or without loading via the extension (F5).

Until I get a chance to provide a stripped down example, you can see the relevant part of my extension code [here](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/server/session.ts#L13-L15).

**Comment by jrieken** [comment] 2016-10-08 07:20
Thanks

**Comment by jrieken** [comment] 2016-10-08 08:30
Ok - I can reproduce with an extension snippet like this

```ts

    vscode.workspace.onDidOpenTextDocument(doc => { 
        console.log('OPENED => ' + doc.uri.toString(true));
    });

    vscode.workspace.onDidCloseTextDocument(doc => { 
        console.log('CLOSED => ' + doc.uri.toString(true));
    });
```

Interesting fact is that you get the close event for file2 when closing file1 - likely because it's the last tab closing...

**Comment by jrieken** [comment] 2016-10-08 08:31
@bpasero Unsure if this is the file input memory leak that has been discussed?

**Comment by freebroccolo** [comment] 2016-10-08 16:34
Thanks for looking into this so quickly. I can also confirm that the close event for file2 does eventually trigger once both tabs are closed.

**Closed** 2016-10-13 13:43 UTC
Labels: bug
