### ISSUE TITLE
Terminal not showing docker command output

### ISSUE THREAD

**Issue by jlundy2** [microsoft/vscode#119087] opened 2021-03-16 14:29 UTC
Issue Type: <b>Bug</b>

Running with Ubuntu 18.04 remote. If I open a terminal and do the following none of the commands I run in the container show any output.

```
|⇒  docker run -it --rm alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
ba3557a56b15: Pull complete 
Digest: sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be
Status: Downloaded newer image for alpine:latest
/ # echo hello

/ # 
```

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (0.80GB free)|
|Process Argv|--crash-reporter-id 237d8660-01db-4de1-945f-ca2fcb5ed5f6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2591)|
|Memory (System)|12.37GB (7.03GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
packer|4op|0.2.0
remote-wsl|ms-|0.54.5
vim|vsc|1.18.9
jinja|who|0.0.8
terraform|has|2.8.2
vscode-docker|ms-|1.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by jlundy2** [comment] 2021-03-16 14:42
Docker shows output if run outside of vscode and if I switch to the output tab and back to the terminal the output is shown.

**Comment by meganrogge** [comment] 2021-03-29 17:04
Duplicate of #110232

**Closed** 2021-03-29 17:05 UTC
Labels: *duplicate, bug, integrated-terminal
