### ISSUE TITLE
vs code do not suite well when i use two monitors

### ISSUE THREAD

**Issue by Easy-wei** [Microsoft/vscode#18390] opened 2017-01-11 06:46 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-refresh-html|bajdzis|0.0.2|
|python|donjayamanne|0.5.5|
|vscode-flake8|jaysonsantos|0.0.4|
|vscode-icons|robertohuertasm|6.0.0|

---

Steps to Reproduce:

1.I always work in  two monitors,one is my labtop computer monitor ,one is a large external display .when I use both of them , VS code show clearly on the external display ,but not clearly on the labtop computer's display. Chrome can  show very clearly  on both of them.
2.

**Comment by Easy-wei** [comment] 2017-01-11 06:46
I always work in two monitors,one is my laptop computer monitor ,one is a large external display .when I use both of them , VS code show clearly on the external display ,but not clearly on the laptop computer's display. Chrome can show very clearly on both of them.

**Comment by mjbvz** [comment] 2017-01-11 18:57
This looks like a duplicate of #18390. Try running code with `--disable-gpu` and see if that resolves things

**Closed by mjbvz** 2017-01-11 18:57 UTC
Labels: duplicate
