### ISSUE TITLE
CSS nesting first-selector not highlight

### ISSUE THREAD

**Issue by tiger-with-wings** [microsoft/vscode#210893] opened 2024-04-22 09:51 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version: Darwin arm64 23.4.0

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/48421487/7aa3ccaf-6ed9-49b3-beb1-8c36ed9f93be)

**Comment by alexr00** [comment] 2024-04-22 12:48
Duplicate of upstream issue about supporting nesting: https://github.com/microsoft/vscode-css/issues/9

**Closed by alexr00** 2024-04-22 12:48 UTC
