### ISSUE TITLE
focus Hover really bother me while selection

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#199847] opened 2023-12-02 07:59 UTC
Does this issue occur when all extensions are disabled?: Yes

版本: 1.85.0-insider
提交: 94a3d7bac770b43ce97e9685715bef1a60d1a759
日期: 2023-12-01T19:00:37.339Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.85.0-insider Chrome/114.0.5735.289 Electron/25.9.6 Safari/537.36

Steps to Reproduce:

1. use mouse to select some text for futher operate, e.g. delete/copy and so on
2. but the focusHover is actived easily and prevent user to edit
3. the only thing is hit escap key
    4. but that will lost my selection
**I had to re-select the text and be careful not to trigger the focus hover**
please fix this @aiday-mar 
![focusHover](https://github.com/microsoft/vscode/assets/1876302/8a6429a7-0fe2-4afd-83ff-9f29ec0fb1f5)

**Comment by aiday-mar** [comment] 2023-12-04 13:56
Hi @heartacker I am not sure I understand the issue. When you focus on the hover, are you clicking on the hover or are you running `Show Or Focus Hover` ?

Is your feature request that when you escape a focused hover, that the previous selection remains as is?

**Comment by RedCMD** [comment] 2023-12-05 00:26
I cant reproduce the hover taking focus

when selecting text, no hovers should ever pop up and any current hovers should disappear

however I did find some interesting behaviour
2. hover over some text until a hover appears
4. move your mouse very quickly to some other text (before the hover disappears)
5. select the text
6. stop moving, but continue holding left click
7. A hover will pop up when it shouldn't

**Comment by aiday-mar** [comment] 2023-12-05 10:34
possibly related https://github.com/microsoft/vscode/issues/191785

**Comment by heartacker** [comment] 2023-12-05 14:24
can you  repeat my case?

**Comment by aiday-mar** [comment] 2023-12-05 14:34
I am not able to reproduce the issue of a hover appearing while a selection is under way. I will be on the lookout for the issues you described.

**Comment by heartacker** [comment] 2023-12-05 14:56
> I am not able to reproduce the issue of a hover appearing while a selection is under way. I will be on the lookout for the issues you described.

In fact, it's really easy to reproduce, and a lot of my colleagues have had this problem, if you're making a selection and you move your mouse slightly to the left or the right rather than just the left or the right

**Comment by aiday-mar** [comment] 2023-12-05 15:35
Ah yes my bad apologies, I will look into it when there is time.

**Comment by yulin96** [comment] 2023-12-06 12:50
@heartacker 
可能和翻译相关的插件有关
https://github.com/microsoft/vscode/pull/196891

**Comment by heartacker** [comment] 2023-12-06 14:18
> @heartacker 可能和翻译相关的插件有关 #196891
并不是，我已经很确定就是鼠标移动的时候，不小心进入了hover的范围

**Comment by staoran** [comment] 2023-12-07 02:18
I am also driven crazy by this problem, the hover box should not pop up when the mouse button is pressed.

**Comment by staoran** [comment] 2023-12-07 02:39
@heartacker 
This issue disappears after disabling Comment Translate, and it currently appears to be related to #196891.

**Comment by aiday-mar** [comment] 2023-12-07 08:15
Hi @staoran when you mention comment translate are you referring to the extension? As you mentioned we have changed the API slightly concerning the show hover action, and it could be that the fix should be done on the extension side. 

**Update**: After installing the comment translate extension I am able to reproduce this error. @heartacker do you also have this extension installed?

**Comment by aiday-mar** [comment] 2023-12-07 08:48
Ah I see, thanks a lot for the update. I do not speak Chinese so it was difficult for me to understand exactly what the conversation was about. Am I correct in understanding that once the other PR goes into the extension, the issue here should be fixed?

**Comment by staoran** [comment] 2023-12-07 08:56
Hi @aiday-mar .
Yes, your understanding is correct.😀
So I am now looking forward to the release of November 2023 (version 1.85).😂
How long do I have to wait?😀

**Comment by aiday-mar** [comment] 2023-12-07 09:02
Glad to hear :). The release should come out today I believe. If it does not, it should come out very soon (by next week in any case).

**Comment by aiday-mar** [comment] 2024-04-02 07:46
This issue should be fixed since the other PR is merged. This issue will be closed.

**Closed by aiday-mar** 2024-04-02 07:46 UTC
Labels: feature-request, editor-hover
