### ISSUE TITLE
Cannot create PR anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#165891] opened 2022-11-09 06:36 UTC
```
TypeError: Cannot read properties of undefined (reading 'availableBaseRemotes')
    at get initialized [as initialized] (webview-create-pr-view.js:377:19653)
    at webview-create-pr-view.js:377:54232
    at Root (webview-create-pr-view.js:377:57061)
    at oh (webview-create-pr-view.js:359:51845)
    at Rj (webview-create-pr-view.js:361:8389)
    at Qj (webview-create-pr-view.js:361:928)
    at Kj (webview-create-pr-view.js:361:831)
    at yj (webview-create-pr-view.js:359:88617)
    at Ig (webview-create-pr-view.js:359:85303)
    at bk (webview-create-pr-view.js:361:16511)
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/900690/200757038-57f89270-f3e0-4324-b9de-bdecb52f6b0f.png">

**Comment by alexr00** [comment] 2022-11-10 15:34
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4172

**Closed by alexr00** 2022-11-10 15:35 UTC
