### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mrichman** [Microsoft/vscode#11777] opened 2016-09-09 15:14 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Start VS Code

Setting `"http.proxyStrictSSL": false` has no effect.

![image](https://cloud.githubusercontent.com/assets/11228/18392110/82f1facc-767e-11e6-930c-8040e84032d9.png)

**Comment by svswaminathan** [comment] 2016-09-09 16:09
I just upgraded my VS Code to v1.5.1 and stuck with the same error. Getting this error upon opening any .net core projects in VS Code on Mac.

**Comment by davidostati** [comment] 2016-09-09 16:10
Same here with the latest version. It seems that it only affects Windows...

**Comment by seanmcbreen** [comment] 2016-09-09 18:34
We are tracking an SSL issue #11702 

The best work around for now is to try insiders http://code.visualstudio.com/insiders

**Comment by ramya-rao-a** [comment] 2016-09-09 20:02
@joaomoreno Duplicate of #11702 ?

**Closed** 2016-09-12 07:13 UTC
Labels: duplicate
