### ISSUE TITLE
After starting VS Code, I need to install the Dart extension every time

### ISSUE THREAD

**Issue by tiidacast-dev** [microsoft/vscode#189999] opened 2023-08-09 01:37 UTC
Type: <b>Bug</b>

After starting VS Code, I have to install the Dart extension every time, which is annoying.
It's happening with VS Code version July 2023 (version 1.81).

VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (20.21GB free)|
|Process Argv|--crash-reporter-id 4009137d-4113-46eb-b93e-310be26dcba1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
flutter-snippets|ale|3.0.0
vscode-neovim|asv|0.4.1
flutter|Dar|3.70.0
flutter-auto-import|dav|0.0.1
flutter-dependency-docs|djb|1.1.1
gitlens|eam|14.2.0
todo-tree|Gru|0.0.226
pubspec-assist|jer|2.3.2
flutter-tree|mar|1.0.0
compare-folders|mos|0.23.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.26.0
vscode-language-pack-ja|MS-|1.81.2023080209
vscode-kubernetes-tools|ms-|1.3.13
remote-containers|ms-|0.304.0
sqltools|mtx|0.28.0
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-pg|mtx|0.5.1
awesome-flutter-snippets|Nas|4.0.1
vscode-print|pdc|0.11.15
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.29.0
sqlite-viewer|qwt|0.3.13
vscode-yaml|red|1.14.0
trailing-spaces|sha|0.4.1
vscode-gradle|vsc|3.12.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by Librazy** [comment] 2023-08-09 07:55
Same for me with Github Copilot, Github Copilot Chat and Rust Analyzer while updating VSCode Insider on my Mac with remote workspace on Ubuntu 22.04

**Comment by Librazy** [comment] 2023-08-09 08:39
```
~/.vscode-server-insiders/extensions $ cat .obsolete 
{"github.copilot-chat-0.7.2023080701":true,"github.copilot-1.101.322":true,"rust-lang.rust-analyzer-0.4.1617":true}# 
```

**Comment by tiidacast-dev** [comment] 2023-08-09 10:40
> Thank you for your comment.
> Now I would like to proceed by downgrading VSCode.

After downgrading to the following version, I no longer need to constantly reinstall the Dart extension.

Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z
Electrons: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

**Comment by joyceerhl** [comment] 2023-08-10 00:45
This may be a duplicate of https://github.com/microsoft/vscode/issues/189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

**Comment by tiidacast-dev** [comment] 2023-08-10 04:52
> This may be a duplicate of #189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

I tried.
I no longer have to reinstall the Dart extension on VSCode startup.
thanks you!

**Closed** 2023-08-10 06:25 UTC
Labels: info-needed
