### ISSUE TITLE
please add keyboard shortcat for QuickFix menu 

### ISSUE THREAD

**Issue by n1rdeks** [microsoft/vscode#98868] opened 2020-05-30 12:33 UTC
Please add keyboard shortcat for QuickFix menu, not only arrow keys.
I have HHKB, without arrow keys. I use Emacs shortcuts for navigate menu.
Today work only arrow keys for goto next line.

**Comment by yume-chan** [comment] 2020-05-31 04:39
Duplicate of #88076

Please do a search before filing new issues.

**Closed** 2020-05-31 09:17 UTC
