### ISSUE TITLE
Support projects (workspaces)

### ISSUE THREAD

**Issue by 1st** [Microsoft/vscode#25241] opened 2017-04-24 18:04 UTC
It looks very strange that VS Code doesn't support ability to create and use projects. Workspace settings is a project settings. It's projects support already in this editor. But requires some polishing...

I found it uncomfortable for me to create new `.vscode` folder inside the source code directory. Some extensions put there own cache files. I don't like it (because if I work vis sshfs, then it means that each change of this cache file will be transferred, that I don't like to do).

It's why I propose to tune-up current workspace ideology and enable out-of-the-box projects support. All what you need - to create for each new project new folder in the `~/.vscode/` with appropriate local workspace `settings.json` file.

In the end, it will look like this:
```bash
~/.vscode/
    settings.json
    project1/
        settings.json
        cache_file_for_some_plugin
    project2/
        settings.json
```

This structure will work fine, because you have the same global setting for all projects, and local settings per project (workspace).

It will be good if you will make this change, and it will make life much easier out-of-the box.

**Comment by fabiospampinato** [comment] 2017-07-14 16:40
I don't think this should be the default behavior.

It breaks a couple of use cases:
- I store some projects within encrypted images, after this change some projects files will be moved to `~/...` and therefor, unless you are using full disk encryption, they will be stored in clear form.
- Now we can copy a project's folder to another machine and start to work on it pretty easily, with this change we would have to remind to copy whatever files are under `~/...`

Also, unless all extensions that do this get updated, there will always be an extension that pollutes `.vscode`.

I think your issue should be addressed in one of the following ways:
- If you have some particular extensions putting a lot of files under `.vscode` you should ask their developers to provide a setting for using a custom output directory.
- I've no idea if that's possible, but maybe you could blacklist `.vscode` in sshfs

**Comment by Tyriar** [comment] 2017-07-14 16:59
Closing this in favor of #396, while we didn't start out with this, we're moving towards a first class "workspace" concept (but clearly distinct from . You can ready about our current thinking more at the end of the issue.

Duplicate of #396

**Closed by Tyriar** 2017-07-14 16:59 UTC
Labels: config, feature-request, workbench
