### ISSUE TITLE
Lorem is still bugged

### ISSUE THREAD

**Issue by misharikw** [Microsoft/vscode#37218] opened 2017-10-31 09:21 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.22.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|5.7.1
vscode-html-css|ecm|0.1.8
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
code-runner|for|0.8.2
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.1.1
rest-client|hum|0.16.0
crane|Hvy|0.3.8
docthis|joe|0.6.0
Angular2|joh|2.10.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.66
MagicPython|mag|1.0.12
Angular-BeastCode|Mik|5.0.10
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
csharp|ms-|1.12.1
node-debug2|ms-|1.18.4
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
Ruby|reb|0.15.0
java|red|0.12.0
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
code-settings-sync|Sha|2.8.3
stylelint|shi|0.30.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.4
quokka-vscode|Wal|1.0.72
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.type lorem inside p tag
2. repeat on another line
![capture](https://user-images.githubusercontent.com/30925653/32216429-0bf46dbe-be36-11e7-80ed-c6c5a142c87f.JPG)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-10-31 09:33
Duplicate of #36300. Already fixed in the latest insider release.

**Comment by octref** [comment] 2017-10-31 22:41
@misharikw This is already fixed in insiders: https://code.visualstudio.com/insiders

You can also wait for next month's release in a week.

@maxibanki Thanks for helping!

**Closed by octref** 2017-10-31 22:41 UTC
