### ISSUE TITLE
Autocomplete in Visual Studio Code not working correctly (SASS,CSS,LESS)

### ISSUE THREAD

**Issue by htar** [Microsoft/vscode#25092] opened 2017-04-20 19:31 UTC
When using VSC the autocomplete function does not seem to work correctly. I can use things like bgc for background-color: but when i want the options for a property it just gives a list with all the options. I have made two screenshots to show the behaviour. I use Sass Indented as a plugin.

Edit: Autocompletion does work with a normal css file.
<img width="622" alt="wc4wj" src="https://cloud.githubusercontent.com/assets/4822479/25249419/7a7bce1c-261a-11e7-9ee4-7944ee5c7c0e.png">

<img width="547" alt="kof7w" src="https://cloud.githubusercontent.com/assets/4822479/25249394/6de2cb06-261a-11e7-934f-8f2953f5b7b9.png">

**Comment by aeschli** [comment] 2017-04-25 21:45
This looks like SASS, which we don't support out of the box (only SCSS).

**Comment by htar** [comment] 2017-04-26 12:11
in .scss we have this problem to
![screenshot from 2017-04-26 15-10-09](https://cloud.githubusercontent.com/assets/4822479/25433839/9554d04a-2a92-11e7-940d-8dc802c9c7d2.png)
![screenshot from 2017-04-26 15-09-27](https://cloud.githubusercontent.com/assets/4822479/25433838/95547082-2a92-11e7-924e-6379dfd07bf3.png)

**Comment by aeschli** [comment] 2017-04-26 13:14
The proposals in the screenshot look correct. Note that in SCSS you can nest rules so you will also get selector proposals inside a rule.

Please add a small code sample and list what you see and what you are expecting.

**Comment by htar** [comment] 2017-04-26 18:20
Hello

I have problems with auto complete, when I write for Emmet autocomplete displays options that are not acceptable in css 'box-decoration-break' 'stroke-dashoffset' and another. You can view this in screenshots.
so I can't using quickly   Emmet or another snippet 

Will be very good that I can disable default 'auto complete - snippet' in the settings or you turn off all bad autocomplete snippet in css scss less
![scss3](https://cloud.githubusercontent.com/assets/4822479/25449966/1a5a735c-2ac6-11e7-81fb-48912e9bcc3a.jpg)
![scss2](https://cloud.githubusercontent.com/assets/4822479/25449967/1a7362fe-2ac6-11e7-810b-bb7bc015015b.jpg)
![scss](https://cloud.githubusercontent.com/assets/4822479/25449968/1a82a552-2ac6-11e7-83f3-63d5dacfb35f.jpg)




![css](https://cloud.githubusercontent.com/assets/4822479/25449946/148ccc9a-2ac6-11e7-8879-c8863f3b3136.jpg)

**Comment by minipai** [comment] 2017-05-04 01:43
I have same issue.

syntax: scss
![screen shot 2017-05-04 at 11 41 32 am](https://cloud.githubusercontent.com/assets/239570/25688032/d25f3a48-30be-11e7-93c0-ac673982499f.png)

force set syntax to css:
![screen shot 2017-05-04 at 11 42 09 am](https://cloud.githubusercontent.com/assets/239570/25688033/d3fd2270-30be-11e7-9aa6-16b4d52be02a.png)

**Comment by aeschli** [comment] 2017-05-08 16:55
@htar If you want me to help, please help me understand the issue
Keep is simple, attach a sample code, write the reproducible steps and write what you expect.
Closing this issue.

@minipai That is #17578

**Closed by aeschli** 2017-05-08 16:55 UTC

**Comment by minipai** [comment] 2017-05-08 21:42
Thanks @aeschli,
For those googled to here, I solved the problem by disabled autocomplete in Sass and let Emmet take care of it.

**Comment by techsin** [comment] 2017-06-30 21:55
@minipai  How?

**Comment by minipai** [comment] 2017-07-01 15:05
in setting
```
    "[scss]": {
        "editor.quickSuggestions": false
    },
```
