### ISSUE TITLE
Register File Handling API metadata for common text/code files

### ISSUE THREAD

**Issue by rayfoss** [microsoft/vscode#143936] opened 2022-02-25 02:00 UTC
Allow a user to use their native File Browser on desktop to open a file in the vscode.dev PWA, directly. Without first opening the PWA.

This allows faster editing of multiple files and more seamless integration with the browser, as one can download a CSV and edit it without opening the app first or running the Electron based native app that will run slower/less battery efficiently in some systems compared to the PWA. It also makes it possible to run without additional permission in restrictive or cutting edge environments.

Example of what it looks like with the Excalidraw PWA (This is in no way a native App, this was installed by chrome from the URL):
![Screenshot 2022-02-03 16 37 04](https://user-images.githubusercontent.com/876076/152441127-f81e2f1e-9274-4bf6-9022-b4482971b1dc.png)

This API saw stable ungated support come in Chromium 98.

Not to be confused with the File System API's FileSystemHandler, which allows you to pick a file or directory for the PWA.

Sample code:
```
if ('launchQueue' in window) {
  launchQueue.setConsumer(launchParams => {
    if (!launchParams.files.length)
      return;

    const fileHandle = launchParams.files[0];
    // Handle the file:
    // https://github.com/WICG/file-system-access/blob/master/EXPLAINER.md#example-code
  });
}
```

Sources:

- https://github.com/WICG/file-handling/blob/main/explainer.md
- https://web.dev/file-handling/
- https://excalidraw.com/ PWA with support
- https://morning-bubbly-chauffeur.glitch.me/ PWA with support

**Comment by bpasero** [comment] 2022-02-25 16:14
Duplicate of https://github.com/microsoft/vscode/issues/135784

**Closed** 2022-02-25 18:02 UTC
Labels: triage-needed
