### ISSUE TITLE
[Feature] - Toggle Custom Editor (Improved markdown support)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#113298] opened 2020-12-22 15:39 UTC
This issue arises from the parent issue: https://github.com/microsoft/vscode/issues/84520

## Description
I would like to quickly toggle between 2 markdown states:
- Source Code editor (This is the state you currently get by default)
- Custom Editor (the preview editor you see when opening preview mode if the file is markdown)

Toggling between modes should take place in the same current window. This way you'll get a smooth create-read-modify experience. For references have a look at typora.io or notable.md where this is perfectly implemented.

### Persistent State
When toggling between 2 states i would like the states to be persistent.
What i mean by this, is if I toggle a document to preview mode, when I go to open another document, I'm still in preview mode until I toggle back. This is the behaviour of many other markdown viewers and is pretty standard at this point, if it can keep state across sessions that would be even better.

## Steps to reproduce:
Add this to your settings:
```json
  "workbench.editorAssociations": [
    {
      "viewType": "vscode.markdown.preview.editor",
      "filenamePattern": "*.md"
    }
  ],
```

Then open a markdown file, you can toggle state by calling "Reopen Editor with..." then selecting one of the 2 options. Opening a new file resets this choice.

## Requested changes

As per the discussion in https://github.com/microsoft/vscode/issues/84520 we would like to see a keyboard-shortcut which can toggle between these 2 states, and keep persistence.

## Implementation detail

https://github.com/microsoft/vscode/issues/84520#issuecomment-555770873

> @sverg1 This should likely not be a markdown specific command but a generic for custom editors. Something like: `toggle custom editor` that would switch between VS Code's standard text editor and the custom one (i.e. the markdown preview)
> 
> Here's where the custom editor commands live:
> 
> https://github.com/microsoft/vscode/blob/27a33ee6fe445094693df778ccec10f16a41deba/src/vs/workbench/contrib/customEditor/browser/commands.ts#L60
> 
> The `ICustomEditorService` and `IEditorService` should have the functionality you need to implement this:
> 
> * Getting the currently active editor.
> * Switching it to the custom editor or to the default text editor.
> 
> Since this change would be going into core VS Code, it should not hardcode anything markdown specific

**Comment by olajohn-ajiboye** [comment] 2020-12-27 20:14
@jasonwilliams @mjbvz . I would like to tackle this if it's not been worked on yet.

**Comment by jasonwilliams** [comment] 2020-12-28 00:25
@olajohn-ajiboye no one is working on this so feel free!

**Comment by olajohn-ajiboye** [comment] 2020-12-28 09:28
Thanks @jasonwilliams , I will start working on this. Am I able to ask for pointers from you if I need additional clarifications or who else can help?

**Comment by jasonwilliams** [comment] 2020-12-28 10:38
@olajohn-ajiboye sure you can ask here.

@mjbvz should hopefully be able to guide you too as he made the parent issue and created the custom editor

**Comment by mjbvz** [comment] 2021-01-16 01:26
The existing `Toggle editor type` command switches the type of the current editor so this feature request it to persist the choice too, correct? Maybe a new`Toggle default editor type` command?

To start, look at the `Toggle editor type` command:

https://github.com/microsoft/vscode/blob/64a14963f7b9a273ebadd51d7efca6cd4604cfd1/src/vs/workbench/browser/parts/editor/editorActions.ts#L1934

For the new command, you'll also want to save off the new setting. Here's an example of some code that does that:

https://github.com/microsoft/vscode/blob/6c4a00ce747356d0315ffcf7e819825a4796b222/src/vs/workbench/services/editor/common/editorOpenWith.ts#L140

**Comment by olajohn-ajiboye** [comment] 2021-01-16 02:46
Thanks for the heads-up @mjbvz , I will have another look at this.

**Comment by olajohn-ajiboye** [comment] 2021-01-21 11:27
Hey @jasonwilliams @mjbvz  , I am not able to reproduce the "Reopen Editor with..." option.  I was able to see this option before, but it seems gone. Could this be due to an update?
![Screenshot 2021-01-21 at 12 23 13](https://user-images.githubusercontent.com/33224920/105344896-d8ec4a00-5be3-11eb-8f08-a10a77c513ba.png)

**Comment by jasonwilliams** [comment] 2021-01-21 13:37
@olajohn-ajiboye what version of VSCode are you using? Are you using insiders or stable?

**Comment by olajohn-ajiboye** [comment] 2021-01-21 20:37
@jasonwilliams it's Version: 1.52.1. I am not sure if it's stable or insider.
![Screenshot 2021-01-21 at 21 33 04](https://user-images.githubusercontent.com/33224920/105409462-c9472280-5c30-11eb-83a4-120b3da16f88.png)

**Comment by jasonwilliams** [comment] 2021-03-07 09:29
@mjbvz you able to do something about that?

**Comment by jasonwilliams** [comment] 2021-03-07 09:32
@olajohn-ajiboye i think it’s only on insiders

**Comment by jasonwilliams** [comment] 2021-03-17 09:05
Can we reopen this? It’s being looked at

**Comment by jasonwilliams** [comment] 2021-03-17 22:25
@mjbvz what's the purpose of `Toggle editor type` again? Can that not be retrofitted with the purpose of changing from source-code to preview on markdowns (or cycling through custom editors) ?

**Comment by mjbvz** [comment] 2021-03-19 03:11
` Toggle editor type` toggles the type of the active editor. It's useful for quickly switching between a hex editor and a text editor for example

**Comment by jasonwilliams** [comment] 2022-07-26 12:51
@mjbvz is this issue still valid?

**Comment by mjbvz** [comment] 2022-12-05 23:38
Thanks @jasonwilliams. Yes I'll close this since I think this was addressed. Please open new issues if some part of this still isn't working as expected

**Closed by mjbvz** 2022-12-05 23:38 UTC
Labels: help wanted, feature-request, markdown
