### ISSUE TITLE
Cursor moves outside endqoute

### ISSUE THREAD

**Issue by abdnafees** [microsoft/vscode#139812] opened 2021-12-27 19:44 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 Pro 21H2 19044.1415

Whenever I type double quotes, the cursor moves outside to the right of the end quote. It is extremely annoying. I cannot find an appropriate setting to control this behaviour either. Is there a setting to control the cursor behaviour when typing quotes?
Steps to Reproduce:

1. Type single or double quotes in an HTML or JS file.
2. You will notice the cursor moving after the end quote before you being to type any value.

**Comment by ArturoDent** [comment] 2022-01-06 19:46
I can't reproduce this on W11, Insiders or Stable html or js files.  Try running the `Developer: Toggle Keyboard Shortcuts Troubleshooting` and report what is output when you type a `"` and it jumps beyond the closing `"`.

**Comment by alexdima** [comment] 2022-01-06 21:08
@abdnafees Does this reproduce when disabling all extensions? Are you using a US keyboard layout? Does this reproduce in any file type?

**Comment by keithbrink** [comment] 2022-01-10 11:13
![Screen Recording 2022-01-10 at 01 12 12 PM](https://user-images.githubusercontent.com/15267205/148756923-5e3cc0d7-1422-4637-9a79-b5d70e48eddc.gif)

This happens for me as well, here are the troubleshooting logs for keyboard shortcuts:

```
2022-01-10 13:12:13.507] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyC, keyCode: 67, key: c
[2022-01-10 13:12:13.507] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyC, keyCode: 33 ('C')
[2022-01-10 13:12:13.508] [renderer1] [info] [KeybindingService]: | Resolving [KeyC]
[2022-01-10 13:12:13.508] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:13.640] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyL, keyCode: 76, key: l
[2022-01-10 13:12:13.640] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyL, keyCode: 42 ('L')
[2022-01-10 13:12:13.640] [renderer1] [info] [KeybindingService]: | Resolving [KeyL]
[2022-01-10 13:12:13.640] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:13.756] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyA, keyCode: 65, key: a
[2022-01-10 13:12:13.756] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyA, keyCode: 31 ('A')
[2022-01-10 13:12:13.756] [renderer1] [info] [KeybindingService]: | Resolving [KeyA]
[2022-01-10 13:12:13.756] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:13.947] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyS, keyCode: 83, key: s
[2022-01-10 13:12:13.947] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyS, keyCode: 49 ('S')
[2022-01-10 13:12:13.947] [renderer1] [info] [KeybindingService]: | Resolving [KeyS]
[2022-01-10 13:12:13.947] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:14.043] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyS, keyCode: 83, key: s
[2022-01-10 13:12:14.043] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyS, keyCode: 49 ('S')
[2022-01-10 13:12:14.043] [renderer1] [info] [KeybindingService]: | Resolving [KeyS]
[2022-01-10 13:12:14.043] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:14.214] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Equal, keyCode: 187, key: =
[2022-01-10 13:12:14.214] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Equal, keyCode: 81 ('=')
[2022-01-10 13:12:14.214] [renderer1] [info] [KeybindingService]: | Resolving [Equal]
[2022-01-10 13:12:14.215] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:14.458] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftRight, keyCode: 16, key: Shift
[2022-01-10 13:12:14.458] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftRight, keyCode: 4 ('Shift')
[2022-01-10 13:12:14.458] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2022-01-10 13:12:14.514] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: Quote, keyCode: 222, key: "
[2022-01-10 13:12:14.514] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: Quote, keyCode: 90 (''')
[2022-01-10 13:12:14.514] [renderer1] [info] [KeybindingService]: | Resolving shift+[Quote]
[2022-01-10 13:12:14.515] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2022-01-10 13:12:14.598] [renderer1] [info] [KeybindingService]: + Ignoring single modifier shift due to it being pressed together with other keys.
```

**Comment by keithbrink** [comment] 2022-01-10 11:14
May be related to this issue: https://github.com/johnsoncodehk/volar/issues/840

**Comment by aeschli** [comment] 2022-01-14 10:01
The original issue is reported against 1.63.2 but html.autoCreateQuotes got added in 1.64. Also it's also only for html, not js.

Let's create a different issue for `html.autoCreateQuotes`.

**Comment by aeschli** [comment] 2022-01-14 10:10
@abdnafees We still need more additional information from you.
Can you confirm you are on 1.63 and you see the issue in both HTML and JS.
Can you add a screencast?

**Closed** 2022-01-21 11:25 UTC
Labels: needs more info

**Comment by thiagoschreck** [comment] 2022-02-18 01:10
I am also having this issue. Not much more information is needed as what happens is exactly what has been written here. Also using Win11 and writing HTML...

**Comment by thiagoschreck** [comment] 2022-02-18 12:23
> @thiagoschreck Please create a new issue, as in this particular case we were surprised that the OP reported the issue against `1.63.2`, which did not yet enable the `html.autoCreateQuotes` setting so we were wondering if it might be something else.

I'm sorry, I've been testing again and now I am noticing that, as you mentioned, this is happening because of the `html.autoCreateQuotes`. So I've got nothing new to report as [this ticket](https://github.com/microsoft/vscode/issues/140698) has already been opened.
