### ISSUE TITLE
Uri for Diagnostic doesn't respect the filesystem case sensitivity

### ISSUE THREAD

**Issue by go2sh** [Microsoft/vscode#64349] opened 2018-12-04 14:47 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create a DiagnosticCollection from an extension with the file uri all lowercase on an case-insensitive filesystem (e.g the output of cl.exe)
2. See the diagnostic showing up within a different file

![image](https://user-images.githubusercontent.com/150886/49449754-e06df080-f7db-11e8-8dd2-c4fe2ccbe9d1.png)

I checked, that with the correct case of the path the diagnostics get merged. I traced the bug back to the MarkerService, which uses the uri as key inside a map without checking the case.

**Comment by go2sh** [comment] 2018-12-05 11:39
Yes, the file gets opened multiple times, depending on which diagnostic you click. And also the diagnostics are only shown in the respective editor tab. Additionally, you can set breakpoints in those files, which get hit, but the correct file is opened, where the breakpoint is not shown.
![image](https://user-images.githubusercontent.com/150886/49511176-b0315b00-f88a-11e8-8bf4-fe40217dfd8f.png)
![image](https://user-images.githubusercontent.com/150886/49511201-c7704880-f88a-11e8-9d5a-b8e4e4a2bac9.png)

It would be nice, if the MarkerService would respect Filesystem case. Some tools on case-insensitive systems print paths lower case as the case doesn't matter like MSVC cl.exe.

**Comment by jrieken** [comment] 2018-12-05 11:55
> Yes, the file gets opened multiple times, depending on which diagnostic you click.

Adding @bpasero for opening the document multiple times - I was under the assumption that we normalise things before opening them...

**Comment by bpasero** [comment] 2018-12-05 12:00
> I was under the assumption that we normalise things before opening them...

There is no such thing as normalising something. We do not try anything but take the URI as it comes.

Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-12-05 12:00 UTC
Labels: lang-diagnostics, needs more info
