### ISSUE TITLE
Ouverture du terminal

### ISSUE THREAD

**Issue by chasset** [microsoft/vscode#96352] opened 2020-04-28 09:14 UTC
Issue Type: <b>Bug</b>

Bonjour,

Visual studio code est attaché à un container docker ubuntu bionic. Lorsque j’ouvre un nouveau terminal, il ne lit pas le fichier .profile de l’utilisateur mettant entre autres à jour le répertoire PATH.

Votre programme est génial.

Merci,

Pierre-Olivier

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container these:v1 (/sleepy_hermann)|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (4 x 2600)|
|Memory (System)|7.78GB (0.35GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.7.2
stan-vscode|iva|0.2.0
vscode-docker|ms-|1.1.0
vscode-language-pack-fr|MS-|1.44.2
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-singularity|onn|0.5.0
latex-support|tor|3.2.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.35.1
vscode-npm-script|eg2|0.3.11
beautify|Hoo|1.5.0
r|Iku|1.2.8
latex-workshop|Jam|8.9.0
vscode-insertdatestring|jsy|2.2.4
git-graph|mhu|1.22.0
vscode-language-pack-fr|MS-|1.44.2
vscode-typescript-tslint-plugin|ms-|1.2.3
uuid-generator|net|0.0.4
vscode-yaml|red|0.7.2
partial-diff|ryu|1.4.1
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by Tyriar** [comment] 2020-07-09 13:03
Terminal doesn't read .profile when attached to a container? @chrmarti guessing this is probably as designed as profile is to be run on login, not new terminal.

**Comment by chrmarti** [comment] 2020-07-10 07:26
We turned off reading the login environment because some containers overwrite PATH in their profile, overwriting any PATH set in the Dockerfile. We are discussing reading the interactive environment in https://github.com/microsoft/vscode-remote-release/issues/3224.

Closing as duplicate, we should probably support both.

**Closed by chrmarti** 2020-07-10 07:26 UTC
Labels: *english-please, needs more info, translation-required-french
