### ISSUE TITLE
Extend task configuration to run locally or remotely (ssh, devcontainer, etc.)

### ISSUE THREAD

**Issue by fbaeuerlein** [microsoft/vscode#109112] opened 2020-10-21 20:36 UTC
I'm missing a feature while developing within the devcontainer. I want to copy code on the host machine from the mapped workspace. So a distinguishing between executing a task remotely or locally would be a nice thing. Introducing a new property (e.g. `runAt`) that specifies where the task should run might be a posibility.

Example:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "My Task",
            "type": "shell",
            "command": "cp",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "args": [ "${workspaceFolder}/include/*", "/home/xyz/dev" ], 
            "runAt" : "local" // "remote", "both"
        }    ]
}

```

**Comment by alexr00** [comment] 2020-10-22 11:28
duplicate of https://github.com/microsoft/vscode-remote-release/issues/168

**Closed by alexr00** 2020-10-22 11:28 UTC
