### ISSUE TITLE
VS Code 1.95.3 starts *all* onTaskType extensions when debugging

### ISSUE THREAD

**Issue by chouzz** [microsoft/vscode#234323] opened 2024-11-21 07:33 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.3
- OS Version: windows 11

Steps to Reproduce:

1. Start Debugging (F5) with vscode extension development
2. rust analyzer has been activated by event `onTaskType:cargo`, and it reports error.

launch.json
```
{
	"version": "0.2.0",
	"configurations": [
	
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "npm: webpack"
		},
}
```
![Image](https://github.com/user-attachments/assets/19da4943-42d6-463b-a140-49da4653e71d)

This is a known issue and has been fixed before, but seems the fixes have been reverted in https://github.com/microsoft/vscode/pull/222204

Ref:
https://github.com/microsoft/vscode/issues/175821
https://github.com/microsoft/vscode/issues/192043
https://github.com/microsoft/vscode/issues/172065
https://github.com/microsoft/vscode/pull/221967
https://github.com/microsoft/vscode/pull/222204

**Comment by meganrogge** [comment] 2024-11-24 15:36
This happens by design, thus closing.

**Closed by meganrogge** 2024-11-24 15:36 UTC

**Comment by chouzz** [comment] 2024-11-26 02:29
@meganrogge 

I think it's designed for activated `rust analyzer` extension when debugging rust language but not designed for activated `rust analyzer` extension when debugging typescript.

**Comment by meganrogge** [comment] 2024-11-26 14:09
we have to activate all when debugging. there's no way around that at the moment.
