### ISSUE TITLE
Crash replacing huge txt file by regular expression

### ISSUE THREAD

**Issue by Atom2004** [microsoft/vscode#99738] opened 2020-06-10 08:44 UTC
Issue Type: <b>Bug</b>

1.open the tx_logic_hex_001.csv file
![image](https://user-images.githubusercontent.com/22042246/84246480-45c14100-ab39-11ea-8757-569fdb88df7f.png)
about 28M line and about 28M match.
2.search `[0-9]{1,4}\.[0-9]{1,},`
![image](https://user-images.githubusercontent.com/22042246/84246404-2cb89000-ab39-11ea-8d4f-3fbd1807c403.png)
3.replace all
4.then crash after few minutes.

VS Code version: Code - Insiders 1.46.0-insider (9f89da69154ac6c99dfa7c82986e2df95b7bbe0b, 2020-06-08T22:10:54.220Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (7.75GB free)|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.1
matlab|Gim|2.0.0
git-graph|mhu|1.23.0
python|ms-|2020.5.86398
cpptools|ms-|0.28.3

</details>

**Comment by Atom2004** [comment] 2020-06-10 09:47
the FILE tx_logic_hex_001.csv uploaded below.
https://drive.google.com/file/d/1N9_xrSDZzoDpbDbsi7U9ecBxmVru_OOp/view?usp=sharing

**Comment by rebornix** [comment] 2020-11-02 22:57
/duplicate of https://github.com/microsoft/vscode/issues/30874

**Closed** 2020-11-02 22:58 UTC
Labels: *duplicate, bug, editor-find, freeze-slow-crash-leak
