### ISSUE TITLE
Consider changing "Close" panel button to be "Hide"

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8018] opened 2016-06-22 18:58 UTC
Currently all panels feature a `x` button which when hovered say "Close". This is ambiguous for the terminal as to weather it will destroy the processes and potentially will be for other/future panels. I suggest changing this to a minimize/hide icon `-` with a tooltip that reads "Hide".

![image](https://cloud.githubusercontent.com/assets/2193314/16279615/a1323f20-3870-11e6-94f7-ec6b502a4d5f.png)

/cc @bgashler1 @bpasero @stevencl

**Comment by dbaeumer** [comment] 2016-06-22 19:59
Assigning to @bgashler1 since this is a overall UI issue

**Comment by bgashler1** [comment] 2016-06-24 02:27
After discussing this with others and thinking about it, I feel it's best we use a downward chevron arrow (collapse arrow).

This implies a non-destructive removal of a view and disambiguates the expected behavior some users have of an "X" in a terminal (terminating a process, removing history and closing the terminal).

**Closed** 2016-06-24 02:29 UTC
Labels: ux, workbench

**Comment by Tyriar** [comment] 2016-06-24 03:14
I'll leave the "Close" tooltip as is to keep it consistent with the command name
