### ISSUE TITLE
CPU hogging is back

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#12144] opened 2016-09-16 11:10 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (50bb7aad57cbf1924e28472de52734be49645558, 2016-09-15T06:05:10.053Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Since Recent upgrades
2. Code Insiders - Helper runs CPU to max

We've optimized all folders to exclude from watching. How do we get to the where this is actually happening. It was fine till about 2 releases back.
Does anyone else find the same?

<img width="989" alt="screenshot 2016-09-16 13 08 49" src="https://cloud.githubusercontent.com/assets/5508278/18584069/d3b89a84-7c0e-11e6-933b-6c1e9119983e.png">
[Sample of Code - Insiders Helper.txt](https://github.com/Microsoft/vscode/files/476684/Sample.of.Code.-.Insiders.Helper.txt)

**Comment by gerhardcit** [comment] 2016-09-16 11:36
Just updated:
- VSCode Version: Code - Insiders 1.6.0-insider (0619ede1e469ed23fbb214eaa0377625a402ca87, 2016-09-16T06:05:18.476Z)
- OS Version: Darwin x64 15.6.0

And it's already better. (No more CPU)

**Comment by gerhardcit** [comment] 2016-09-16 12:28
Nope, opening a very basic mainly typescript project... It goes again.
How do I find out which plugin on process it is..
I can see the process in Htop, but I don't get the plugin detail

**Comment by bpasero** [comment] 2016-09-16 14:05
@gerhardcit well, does it reproduce when you run code `code --disable-extensions`? If yes, this would not be extension related.

**Comment by eamodio** [comment] 2016-09-16 16:00
I've been experiencing the same thing, since 50bb7aad57cbf1924e28472de52734be49645558

VSCode Version: `Version 1.6.0-insider (1.6.0-insider)` 50bb7aad57cbf1924e28472de52734be49645558
OS Version: `OS X El Capitan Version 10.11.6 (15G1004)`

Even after closing vscode the `Code Insiders - Helper` still continues to run and needs to be manually killed. I've had this happen a handful of times since 50bb7aad57cbf1924e28472de52734be49645558 but I haven't yet experienced it with 0619ede1e469ed23fbb214eaa0377625a402ca87.

I have been doing a bunch of debugging of a vscode extension (in typescript) and vscode has also crashed quite a few times over that period. Although I haven't noticed a correlation with the crashes to the CPU hog. Also the last time I noticed it was this am, when I came back to my machine vscode was running since the day before and the helper was hogging 100% CPU. I don't remember my machine bogging (i.e. fan on) before I went to bed, but was this am.

I will definitely keep an eye out for it today.

**Comment by bpasero** [comment] 2016-09-16 16:36
@eamodio we need to identify which process of VS Code is running with high CPU. For that you can find the PID of the process that runs high in the activity monitor and then `ps aux | grep` <pid> to see the full command line arguments.

**Comment by eamodio** [comment] 2016-09-16 17:01
@bpasero if/when it happens again I'll be sure to grab it.

**Comment by wulftone** [comment] 2016-09-22 16:33
I just saw it this morning... found this issue. If it happens again I'll grab the full arguments from the process

**Comment by bpasero** [comment] 2016-09-24 06:08
@gerhardcit @eamodio @wulftone next time you see high CPU process please:

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. On Windows a tool like **Process Explorer** or **Process Hacker** helps.

Once you have the information please update this issue with it. Thanks!

**Comment by gerhardcit** [comment] 2016-09-25 09:23
@bpasero 
One process produces this:

```
gerhard$ ps aux | grep 63704
gerhard          63704  83.9  0.4  3504760  69200   ??  R    11:05AM   3:07.97 /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_12991587
gerhard          64122  79.4  1.6  4321776 266108   ??  S    11:15AM   3:03.05 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=F18BFC7B12B5FE4BF8D0EE6E02EBD76A --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=C951F3A9D99261E80508641E0566A2B8 --mojo-application-channel-token=1BD21D2DDB706A37EEEE5F8F63586AAF --channel=63704.3.1497268199
gerhard          63900   0.0  0.5  4245864  84380   ??  S    11:13AM   0:05.76 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=8421F1CDA36CB4B8D3D441A258AD7D34 --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=298349D3D0E95D1B98414D824840B582 --mojo-application-channel-token=1A2DECD9348F41FC69EF7D5029E97C36 --channel=63704.2.1190930935
gerhard          63706   0.0  0.1  2952604  23424   ??  S    11:05AM   0:03.25 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=gpu-process --channel=63704.0.1733902503 --mojo-application-channel-token=7B41891BB2A42CC1DEE54226EFD26620 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=16,36,49,50,51,55,57,65,66,72,75 --gpu-vendor-id=0x10de --gpu-device-id=0x0fe9 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0d26 --gpu-active-vendor-id=0x10de --gpu-active-device-id=0x0fe9
gerhard          64415   0.0  0.0  2444056    816 s022  S+   11:20AM   0:00.00 grep 63704
```

And another one:
```
gerhard$ ps aux | grep 64122
gerhard          64122  79.3  1.6  4317412 271640   ??  R    11:15AM   4:31.53 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=F18BFC7B12B5FE4BF8D0EE6E02EBD76A --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=C951F3A9D99261E80508641E0566A2B8 --mojo-application-channel-token=1BD21D2DDB706A37EEEE5F8F63586AAF --channel=63704.3.1497268199
gerhard          64452   0.0  0.0  2434840    800 s022  S+   11:22AM   0:00.00 grep 64122
```

**Comment by gerhardcit** [comment] 2016-09-25 13:39
@bpasero 
Working all well, then reorganised some folders, and after a while, and even after restart.
This
```
gerhard$ ps aux | grep 72508
gerhard          72508  81.7  0.5  3513772  85784   ??  S     3:30PM   4:33.32 /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
gerhard          72536  80.3  1.4  4294332 228800   ??  R     3:30PM   4:22.55 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=1D12D3B04CCE45A45B901C3637188151 --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=C28A9309BC49B42737674C4242DFF4C8 --mojo-application-channel-token=A3B8A778A8E27995F9494E528553574E --channel=72508.2.1120234896
gerhard          72521   0.0  1.2  4210760 209136   ??  S     3:30PM   0:11.32 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=DF691AB9BB84003286A698EDD2549265 --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=5A06CB7F93EB4DDA8DA66DA8BAFCE37B --mojo-application-channel-token=9DD7BFAED7E636BEBA1BD1A528D8E203 --channel=72508.1.195027062
gerhard          72509   0.0  0.3  2948348  50880   ??  S     3:30PM   0:02.94 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=gpu-process --channel=72508.0.80417803 --mojo-application-channel-token=6A571A0DA2F68C5C2680FC7BAF2A8CD3 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=16,36,49,50,51,55,57,65,66,72,75 --gpu-vendor-id=0x10de --gpu-device-id=0x0fe9 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0d26 --gpu-active-vendor-id=0x10de --gpu-active-device-id=0x0fe9
```

**Comment by bpasero** [comment] 2016-09-25 15:38
@gerhardcit when this happens, could you run a CPU profile so that we understand where the time is spend?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by eamodio** [comment] 2016-09-26 03:34
@bpasero 
I happened again but only noticed it after I closed vscode and one of the processes stuck around:
```
> ps aux | grep 15528
eric            15528  99.1  0.5  3298704  78112   ??  R    11:08PM  17:48.37 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --nolazy --debug-brk=42110 /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=extensionHost
eric            15591   0.0  0.7  4844016 111892   ??  S    11:08PM   0:16.88 /Users/eric/.vscode-insiders/extensions/ms-vscode.csharp-1.5.0-beta1/out/src/.omnisharp-coreclr/OmniSharp -s /Users/eric/Code/ion/faraday --hostPID 15528 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
eric            18153   0.0  0.0  2451236   2132 s000  S+   11:30PM   0:00.00 grep 15528
```

**Comment by bpasero** [comment] 2016-09-26 05:02
@eamodio for you it seems stuck in an extension and if you believe this is OmniSharp maybe it should be reported against their repository.

**Comment by bpasero** [comment] 2016-09-28 09:30
@gerhardcit ping

**Comment by gerhardcit** [comment] 2016-09-28 10:07
@bpasero , haven't been able to get it to stay high on CPU over the last 2 days.. but also went back to Code Std just to get some stuff done..
Just got build c94c824db64a88bd4909da2e84e44316dbf8e8fb so I'll get profiles next time it happens.

**Comment by bpasero** [comment] 2016-09-28 10:21
@gerhardcit thanks

**Comment by alloy** [comment] 2016-09-28 11:49
This is a profile from version 1.5.3 (not insider) on OS X 10.11.6. Just vertically scrolling two split-panes would result in ~100% CPU usage.

[CPU-20160928T134657.cpuprofile.txt](https://github.com/Microsoft/vscode/files/497917/CPU-20160928T134657.cpuprofile.txt)

**Comment by bpasero** [comment] 2016-09-28 12:25
@alloy can we create separate issues? I am not sure if the issues are all related.

@gerhardcit I assume you are not wildly scrolling and see CPU spikes?

**Comment by alloy** [comment] 2016-09-28 12:31
@bpasero Sure thing https://github.com/Microsoft/vscode/issues/12883

**Comment by gerhardcit** [comment] 2016-09-28 13:32
@bpasero , was capturing profiles, but ended up with 0 byte file size. 
However, it has not run away again. I recon you should close the issue and if it comes back we log it again. From my side it seems resolved somehow.
I have build c94c824db64a88bd4909da2e84e44316dbf8e8fb running.

**Comment by bpasero** [comment] 2016-09-28 13:38
More than happy to close it if it does not reproduce easily.

**Closed by bpasero** 2016-09-28 13:38 UTC
Labels: freeze-slow-crash, needs more info
