### ISSUE TITLE
Debugger is waiting a preLaunchTask (QEMU in waiting mode)

### ISSUE THREAD

**Issue by AIG-Livny** [microsoft/vscode#90288] opened 2020-02-08 14:04 UTC
I saw this https://github.com/microsoft/vscode/issues/6209 but it does not work for me, because QEMU doesn't write anything in console.

Debugger is waiting for the process to complete. Obviously, this process must be performed during debugging.
I am trying to run my program for ARM in QEMU:
launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug program",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}\\test.elf",
            "miDebuggerServerAddress": "localhost:9000",
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\gcc_arm\\bin\\arm-none-eabi-gdb.exe",
            "preLaunchTask": "Build and run",
        }
    ]
}
```

tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "make",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Run QEMU",
            "type": "shell",
            "isBackground": true,
            "command": "qemu-system-arm -S -gdb tcp::9000 -M lm3s811evb -kernel test.elf -nographic",
        },
        {
            "label": "Build and run",
            "dependsOrder":"sequence",
            "dependsOn": [
                "Build",
                "Run QEMU",
            ]
        }
    ]
}
```
As you can see, I run QEMU with the -S key. This forces QEMU to wait for the Debugger.
The console is empty at this time.
Everything works great if I run QEMU manually. 
Maybe there is some kind of function to start Debug without waiting for completion?
Or do I need to get QEMU to write something in console?
Is it possible to add such a function in VSCode?

**Comment by AIG-Livny** [comment] 2020-02-08 17:03
Hmm. This works:
tasks.json:
```
{
            "label": "Run QEMU",
            "type": "shell",
            "isBackground": true,
            "command": "echo Starting QEMU&qemu-system-arm -S -gdb tcp::9000 -M lm3s811evb -kernel test.elf -nographic",
            "problemMatcher": {
                "pattern": {
                    "regexp": "^(Starting QEMU)",
                    "line": 1,
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^(Starting QEMU)",
                    "endsPattern": "^(Starting QEMU)"
                }
            }
        },
```
launch.json:
`"preLaunchTask": "Run QEMU",`

But, this does not work:
tasks.json:
```
{
            "label": "Build",
            "type": "shell",
            "command": "make",
            "group": {
                "kind": "build",
                "isDefault": true
            },
        },
{
            "label": "Run QEMU",
            "type": "shell",
            "isBackground": true,
            "command": "echo Starting QEMU&qemu-system-arm -S -gdb tcp::9000 -M lm3s811evb -kernel test.elf -nographic",
            "problemMatcher": {
                "pattern": {
                    "regexp": "^(Starting QEMU)",
                    "line": 1,
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^(Starting QEMU)",
                    "endsPattern": "^(Starting QEMU)"
                }
            }
            
        },
{
            "label": "Build and run",
            "dependsOrder":"sequence",
            "dependsOn": [
                "Build",
                "Run QEMU",
            ]
        }
```
launch.json:
`"preLaunchTask": "Build and run",`

Oh...

**Comment by AIG-Livny** [comment] 2020-02-08 17:16
Ok, now it works as i wanted...
`"command": "make&echo Starting QEMU&qemu-system-arm -S -gdb tcp::9000 -M lm3s811evb -kernel test.elf -nographic",`

**Comment by isidorn** [comment] 2020-02-10 09:35
This is probably due to the `taskService` not sending correct events after a tusk has finished. Forward to @alexr00 as she might want to potentially investigate this. Thanks

**Comment by alexr00** [comment] 2020-02-10 11:11
Currently, having background tasks in a a 'dependsOn` is not supported. Duplicate of https://github.com/microsoft/vscode/issues/70283

**Closed** 2020-02-10 11:12 UTC
Labels: *duplicate
