### ISSUE TITLE
Debugger windows are all blank with the latest VS Code Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#67781] opened 2019-02-02 04:28 UTC
- VSCode Version: 1.31.0-insiders, starting with today's (Feb 1).
- OS Version: Win10

Steps to Reproduce:

1. Do C/C++ debugging via attach to process with the C/C++ extension with launch.json with
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "https://msdl.microsoft.com/download/symbols",
        }
2. Break into the debugger with the break button.

Bug: All the debugger windows are blank. Switching to the non-insiders VS Code fixes it for me.

Screenshot has some other extensions enabled, but it repros with those disabled too.
![image](https://user-images.githubusercontent.com/19859882/52159886-5fa66600-265f-11e9-96e4-4313f1e13787.png)

@pieandcakes @WardenGnaw Are responsible for the C/C++ debugger if you think it's their bug.

Does this issue occur when all extensions are disabled?: Yes (requires C/C++ debugging though).

**Comment by weinand** [comment] 2019-02-04 15:14
@sean-mcmanus could you please open the dev tools console (action "Toggle Developer Tools") and see whether there are any errors showing up on the console after attaching.

**Comment by sean-mcmanus** [comment] 2019-02-04 21:08
Oh, duh, I should have checked. Do these error help? Let me know if I should try other machines or something. It still repros with today's Insiders.
 
```
log.ts:173   ERR Cannot read property 'set' of undefined: TypeError: Cannot read property 'set' of undefined
    at e.renderElement (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5122:727)
    at e.renderElement (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1027:104)
    at e.renderElement (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:999:778)
    at e.renderElement (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:874:551)
    at e.insertItemInDOM (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:428:978)
    at e._splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:424:921)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:423:415)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:797
    at Array.forEach (<anonymous>)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:768)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:654
    at e.bufferEvents (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:83:840)
    at t.e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:610)
    at t.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1009:564)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:90:438)
    at e.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:97:769)
    at t.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1024:277)
    at n.e.render (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1041:310)
    at n.<anonymous> (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1037:369)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:33)
    at s (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:32:1008)
log.ts:173   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at e.removeItemFromDOM (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:430:300)
    at e._splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:423:725)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:423:415)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:797
    at Array.forEach (<anonymous>)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:768)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:654
    at e.bufferEvents (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:83:840)
    at t.e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:610)
    at t.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1009:564)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:90:438)
    at e.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:97:769)
    at t.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1024:277)
    at n.e.render (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1041:310)
    at n.<anonymous> (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1037:369)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:33)
    at s (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:32:1008)
log.ts:173   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at e.removeItemFromDOM (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:430:300)
    at e._splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:423:725)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:423:415)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:797
    at Array.forEach (<anonymous>)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:7:768)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:654
    at e.bufferEvents (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:83:840)
    at t.e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:882:610)
    at t.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1009:564)
    at e.splice (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:90:438)
    at e.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:97:769)
    at t.setChildren (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1024:277)
    at n.e.render (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1041:310)
    at n.<anonymous> (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1037:369)
    at file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:33)
    at s (file:///F:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:32:1008)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by weinand** [comment] 2019-02-04 21:49
@sean-mcmanus thanks, this is a duplicate of #67791.
The fix is already in the latest Insiders.

**Closed by weinand** 2019-02-04 21:49 UTC
Labels: bug, debug, important, needs more info
