### ISSUE TITLE
PHP syntax highlighting with Scope Resolution (::) and Ternary operator (?:)

### ISSUE THREAD

**Issue by Chofoteddy** [microsoft/vscode#79048] opened 2019-08-13 15:08 UTC
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a new tab and select format PHP (or open some file PHP empty).
2. Add any ternary operator with scope resolution operator on true statement.

```php
<?php

// Example code…
true ? Error::getMessage() : Error::getCode();
```

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/1615875/62952725-d4e2b880-bdb1-11e9-89b9-7ad7be00dcb9.png)

**Comment by alexr00** [comment] 2019-08-14 07:46
Duplicate of https://github.com/atom/language-php/issues/356

**Closed by alexr00** 2019-08-14 07:46 UTC
