### ISSUE TITLE
ES6 error property declarations

### ISSUE THREAD

**Issue by hamiltonia** [Microsoft/vscode#5055] opened 2016-04-06 22:16 UTC
Copy issue by @zhonshu from https://github.com/Microsoft/vscode-react-native/issues/199

`
renderPhotosList = () => {
if (this.state.showSelectPhotos) {
}
}
`
'property declarations' can only be used in a .ts file.
(property) MainPage. renderPhotosList: () => JSX.Element

in ES6 function bind this

**Comment by egamma** [comment] 2016-04-07 08:34
Duplicate of https://github.com/Microsoft/TypeScript/issues/6997 also see this comment https://github.com/Microsoft/TypeScript/issues/6997#issuecomment-184509014.

If you are on the insiders build then the work around is to disable the JS diagnostics from Salsa and to use eslint https://github.com/Microsoft/TypeScript/issues/6997#issuecomment-201721683.

[insiders build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) http://code.visualstudio.com/Download#insiders

**Closed by egamma** 2016-04-07 08:34 UTC

**Comment by mcMickJuice** [comment] 2016-07-12 12:48
thanks @egamma . 

FYI, insiders download path is https://code.visualstudio.com/insiders

**Comment by egamma** [comment] 2016-07-13 09:48
@mcMickJuice thanks, I've updated my comment. BTW, this change is now in stable since a while.
