### ISSUE TITLE
Can't edit multiple lines of HTML without deleting the block of code

### ISSUE THREAD

**Issue by drewskadoo** [Microsoft/vscode#13091] opened 2016-09-30 17:23 UTC
- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: macOS Sierra 10.12 (16A323)

Steps to Reproduce:

1. Using multiple cursors I am trying to change these div tags into p elements but it seems to highlight the block of HTML from the first cursor to my last cursor. In result always deletes the block of HTML instead of editing each line separately.

![possible-bug2](https://cloud.githubusercontent.com/assets/19215373/19000530/ef5ee268-86f7-11e6-8af6-bcee793ba45d.gif)

**Comment by Tyriar** [comment] 2016-10-03 18:06
@drewskadoo can you provide the example HTML and exact steps/keystrokes?

**Comment by drewskadoo** [comment] 2016-10-05 17:18
@Tyriar Hey Daniel I am trying to recreate the previous example but for whatever reason it's working as expected. Not to sure what I was doing to cause this but I will keep an eye out for it but at the moment it's working fine :).

**Comment by Tyriar** [comment] 2016-10-05 17:23
@drewskadoo let's close this off for now then, if you hit it again let us know about it. One thing we would want before looking into this if it's difficult to reproduce is a confirmed case of it occurring in the Insiders build since that's the latest version of the code https://code.visualstudio.com/insiders

**Closed by Tyriar** 2016-10-05 17:23 UTC
Labels: editor, needs more info
