### ISSUE TITLE
Visual code crash when opened

### ISSUE THREAD

**Issue by Ayushkothari47** [microsoft/vscode#183387] opened 2023-05-25 04:58 UTC
Type: <b>Performance Issue</b>

Hello Sir/Madam, I am using VScode from around 6months but now my VS code is crash and show message like window is not responding. And give me three option "Reopen", "Close", "Wait". And from 2-3 days it lag so much and delayed while opening it. I think it is cause of low space so it cleared used software and file but still it showing same problem. I have 8GB Ram pc with 512SSD and VScode take 15+ sec to opening and freeze all screen.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (3.47GB free)|
|Process Argv|--crash-reporter-id 503eba76-e84c-4064-ba7b-491a098109d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	 14080	code main
    0	   133	  4584	extensionHost [1]
    0	    24	 13500	     c:\Users\ayush\.vscode\extensions\ms-vscode.cpptools-1.16.0-win32-x64\bin\cpptools.exe
    0	     4	  7972	       "c:\Users\ayush\.vscode\extensions\ms-vscode.cpptools-1.16.0-win32-x64\bin\cpptools.exe"
    0	    17	 13044	         c:\Users\ayush\.vscode\extensions\ms-vscode.cpptools-1.16.0-win32-x64/bin/cpptools-srv.exe 13500 {D0C5C201-4E5F-4076-9D7B-F5CA9E653A78}
    0	    11	 15192	           console-window-host (Windows internal process)
    0	    11	 12808	       console-window-host (Windows internal process)
    0	    27	  9188	   crashpad-handler
    0	    50	 10092	   utility-network-service
    0	    82	 10232	fileWatcher [1]
    2	    87	 11016	window [2] (Issue Reporter)
    0	   150	 11560	   gpu-process
    0	   197	 14004	window [1] (program.c - Visual Studio Code)
    0	   144	 16208	shared-process
    0	    83	 11740	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
mobileview|cir|0.0.7
code-runner|for|0.12.0
vscode-language-babel|mgm|0.0.39
cpptools|ms-|1.16.0
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
zoombar-vscode|wra|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
cai9j608:30706077
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-05-25 05:59
/duplicate

Marking as duplicate of https://github.com/microsoft/vscode/issues/178962. Please let us know if McAfee is not installed on your PC, else use the instructions to resolve.

**Closed** 2023-05-25 06:00 UTC
Labels: *duplicate
