### ISSUE TITLE
Renamed dir name not recorded by IntelliSense

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#39408] opened 2017-12-01 09:24 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
ng-template|Ang|0.1.7
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
ionic3-vs-ionView-snippets|dan|1.0.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.4
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
ionic-preview|ion|0.0.15
cordova-dev-essentials|jew|0.0.1
ionic2-vscode|jgw|1.0.0
Angular2|joh|2.11.2
ionic-extension-pack|loi|0.0.1
debugger-for-chrome|msj|3.5.0
rxjs-snippets|pko|0.0.2
vscode-icons|rob|7.18.1
autoimport|ste|1.5.3
ionic2|Tha|3.0.1
sort-lines|Tyr|1.3.0
Angular2|UVB|0.4.1
cordova-tools|vsm|1.3.1
markdown-all-in-one|yzh|0.11.2

---

![image](https://user-images.githubusercontent.com/512816/33476200-6fb4e6ae-d681-11e7-851e-f79e2f6155ef.png)

Steps to Reproduce:

1. Copy and paste a directory in the VSC file tree
2. Rename the duplicated directory to remove the `.1` extension.
3. Use a Typescript component housed in the newly renamed directory
4. See reference to previous dir name, as in screenshot.

Presumably the Typescript plugin is involved, but perhaps the issue runs deeper.

Reproduces without extensions: Yes/No

**Comment by leegee** [comment] 2017-12-01 09:28
![image](https://user-images.githubusercontent.com/512816/33476452-5e2e0cde-d682-11e7-8e4c-1a3e23817032.png)

**Comment by kieferrm** [comment] 2017-12-01 16:58
/duplicate of #19439

The wording is not exactly the same, but technically it's the same issue.

**Closed by kieferrm** 2017-12-01 16:58 UTC
Labels: *duplicate
