### ISSUE TITLE
URL handlers can fail if registered too late on startup

### ISSUE THREAD

**Issue by loganlifts** [microsoft/vscode#222199] opened 2024-07-19 15:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: MacOS 14.5 (23F79)

Steps to Reproduce:
1. Close all VS Code windows but don't exit the application.
2. Go to an extension page in the VS Code Marketplace in your browser.
3. Click install on the extension page and allow your browser to open VS Code when prompted.
4. VS Code will open but it will show the welcome page rather than the extension page for the extension you're trying to install.

This does not occur if I keep a VS Code application window open or if I exit the application entirely before clicking install from the browser.

**Comment by sandy081** [comment] 2024-08-26 11:59
@bpasero This seems similar to https://github.com/microsoft/vscode/issues/73101 and the latter was fixed by adding a new workbench contribution that blocks the startup and caches the urls

https://github.com/microsoft/vscode/blob/a628b923ec0abdd3bbd289288b2339c2bf1a2809/src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts#L344-L377

Root cause seems to be that url handlers which are registered later are not being called by the main.

**Comment by bpasero** [comment] 2024-08-26 14:03
I do not see a problem with the work that @joaomoreno did with the bootstrap script for caching URLs except for these lines:

https://github.com/microsoft/vscode/blob/c0592918e90ab8ecb24a4fd010403b87474e29f1/src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts#L368-L370

We return early here because `authority` is `""`. At least with the links from the marketplace.

**Steps:**
* open vscode (oss is fine) and close all windows but do not quit
* from the command line run `scripts/code-cli.sh --open-url code-oss:extension/ms-vscode.vscode-speech`
* a window opens but the extension page does not

This works fine if a window is opened or VS Code is not running, so I suspect we only have a bug in the lines above.

@joaomoreno can you check?

**Comment by bpasero** [comment] 2024-08-27 06:37
Idea: when `open` is called we cache URIs that have not been handled and dispatch when `registerHandler` is called:

https://github.com/microsoft/vscode/blob/7473068e0d7b62bfd4ef4c8f6b86832448ff1d36/src/vs/platform/url/common/urlService.ts#L20-L28

**Closed** 2024-12-17 06:56 UTC
Labels: bug, *out-of-scope, confirmed, workbench-link

**Comment by bpasero** [comment] 2024-12-17 15:12
This is a very narrow case of reproduce, I would argue that most users are unlikely to hit (many macOS users are not even aware that VS Code can run without windows open). 

I had looked into https://github.com/microsoft/vscode/issues/222199#issuecomment-2311688699 back then and somehow hit a lot of regressions and bugs while attempting to do so. 

Given this was not even reported by more people and its cleanup iteration, closing as not planned.
