### ISSUE TITLE
The terminal output strange character when I following the link

### ISSUE THREAD

**Issue by liuycy** [microsoft/vscode#107400] opened 2020-09-25 02:35 UTC
- VSCode Version: 1.49.1 (system setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Serve a html with nodejs (my default terminal is wsl2)
2. Follow the link with "alt + click" (I had changed the "ctrl" to "alt")

![image](https://user-images.githubusercontent.com/55272688/94219189-d0775180-ff18-11ea-9c6e-22075c663ebf.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment] 2020-11-04 21:42
Duplicate of https://github.com/microsoft/vscode/issues/101136

**Closed by rzhao271** 2020-11-04 21:42 UTC
Labels: bug
