### ISSUE TITLE
Terminal layout

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#123121] opened 2021-05-06 12:43 UTC
Now I updated vs code right now and I don't like the terminal layout. The terminal layout was much better before. If possible please change back

**Comment by meganrogge** [comment] 2021-05-06 14:13
You can easily go back to the old way by setting terminal.integrated.tabs.enabled: false or by right clicking the terminal and choosing hide tabs in the context menu while we polish tabs this iteration.

**Comment by meganrogge** [comment] 2021-05-06 14:20
Duplicate of #123134

**Closed** 2021-05-06 14:21 UTC
Labels: *duplicate
