### ISSUE TITLE
GitHub PR: Comment isn't cached when starting a comment, switching editors, and coming back to comment

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#62274] opened 2018-10-31 11:49 UTC
I started a comment using '+' and entered some text. Then I switched to the PR description (which did still have some cached text in it). Then I switched back to the file with the comment I started. The comment was gone. 

Windows, with a multi root PR. Found testing #62184

**Comment by RMacfarlane** [comment] 2018-10-31 17:13
Duplicate of https://github.com/Microsoft/vscode/issues/62274

**Closed by RMacfarlane** 2018-10-31 17:13 UTC
