### ISSUE TITLE
Remote SSH: No Syntax Highlighting for Handlebars .hbs files

### ISSUE THREAD

**Issue by deanylev** [microsoft/vscode#167674] opened 2022-11-30 00:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: macOS 13.0.1

Steps to Reproduce:

1. Start a VS Code Remote SSH session
2. Open a .hbs file
3. The selected language at the bottom right is "Plain Text" and when clicking it, Handlebars is not available in the list

**Comment by alexr00** [comment] 2022-12-06 14:24
The extension thinks it needs to be installed on the SSH remote:
![image](https://user-images.githubusercontent.com/38270282/205935650-6ab8a1c2-1242-4c42-a5c0-32960ab829d1.png)

On it's own the handlebars extension doesn't need to be installed on the SSH remote, but the HTML languages features extension appears to be pulling it in with `htmlLanguageParticipants`. It seems like this is related to https://github.com/microsoft/vscode/issues/146730.

The problem is easily fixed by adding this to handlebars:
```
  "extensionKind": [
	"ui",
	"workspace"
  ],
```

But that might break https://github.com/microsoft/vscode/issues/146730.

**Comment by alexdima** [comment] 2022-12-06 19:34
@alexr00 Nice! Thanks for figuring this out! I initially believed this was a feature request to add a builtin handlebars grammar.

**Comment by aeschli** [comment] 2022-12-07 14:54
The handlebars could run on the renderer, but because it defines `htmlLanguageParticipants` it needs to run on workspace. https://github.com/microsoft/vscode/blob/386459dec0490aed8a67a1b94dc978a3307982eb/src/vs/workbench/services/extensions/common/extensionManifestPropertiesService.ts#L276

If `htmlLanguageParticipants` were an internal contribution point, we could define a `defaultExtensionKind: [ ui ]`, but we don't have a way for contributions to declare a contribution point (a contribution contribution)

So these are the possible solutions
- "extensionKind":  "ui", "workspace"] as @alexr00 suggests as it overwrites the detected extension kinds
- Implement a contribution contribution point

I go with the first one for now. @alexdima speak up if you disagree

**Closed** 2022-12-07 15:15 UTC
