### ISSUE TITLE
Tree view is empty

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#79371] opened 2019-08-17 21:09 UTC
This was originally reported as a bug in the Git Tree Compare extension: https://github.com/letmaik/vscode-git-tree-compare/issues/51 but its author @letmaik thinks that it might be a VSCode bug, maybe on macOS only.

What happens is that sometimes, I see an empty view instead of a normal tree:

<img width="356" alt="Screenshot 2019-07-23 at 10 29 01" src="https://user-images.githubusercontent.com/101152/61695965-b77f7900-ad34-11e9-911e-58f0f5cd017e.png">

When this happens and I open dev tools > console, I see this logged:

```
log.ts:173   ERR Bad progress location: workbench.view.explorer: Error: Bad progress location: workbench.view.explorer
    at Proxy.withProgress (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5111:20)
    at G.activate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4802:140)
    at G.setVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4796:799)
    at z.updateTreeVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4792:324)
    at _register.onDidChangeBodyVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4791:730)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:67)
    at z.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4785:52)
    at panels.filter.map.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4811:822)
    at Array.map (<anonymous>)
    at e.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4811:813)
    at e.showComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5100:754)
    at e.doOpenComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5098:591)
    at e.openComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5098:123)
    at e.doOpenViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5108:446)
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5107:827)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at e.openViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5107:744)
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5167:824)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at e.run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5167:373)
    at runAction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:369)
    at r.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:234)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:97)
    at e.onClick (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:864:519)
    at Immediate.options.options.isMenu.i.setImmediate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:864:75)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
log.ts:173   ERR Bad progress location: workbench.view.explorer: Error: Bad progress location: workbench.view.explorer
    at Proxy.withProgress (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5111:20)
    at q.t.instantiationService.createInstance.e [as withProgress] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4797:979)
    at q.getChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4803:583)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:981:31)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at a.createCancelablePromise (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:984)
    at Object.l [as createCancelablePromise] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:102:428)
    at X.doGetChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:956)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:586)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.doRefreshNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:373)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:231)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.doRefreshSubTree (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:162)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:980:9)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.refreshNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:979:810)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:979:570)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.refreshAndRenderNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:979:523)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:976:913)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.updateChildren (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:976:682)
    at X.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:976:476)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.setInput (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:976:292)
    at G.createTree (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4799:268)
    at G.activate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4802:106)
    at G.setVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4796:799)
    at z.updateTreeVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4792:324)
    at _register.onDidChangeBodyVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4791:730)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:67)
    at z.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4785:52)
    at panels.filter.map.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4811:822)
    at Array.map (<anonymous>)
    at e.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4811:813)
    at e.showComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5100:754)
    at e.doOpenComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5098:591)
    at e.openComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5098:123)
    at e.doOpenViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5108:446)
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5107:827)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at e.openViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5107:744)
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5167:824)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at e.run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5167:373)
    at runAction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:369)
    at r.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:234)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:237)
    at run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100:97)
    at e.onClick (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:864:519)
    at Immediate.options.options.isMenu.i.setImmediate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:864:75)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

When everything is alright (which is 99% of the time), these messages are not there.

I do not know how to reliably reproduce the issue. I also never saw it in any other tree, on with the Git Tree Compare view. 

- VSCode Version: 1.37.1
- OS Version: macOS (Darwin x64 18.7.0)

**Comment by isidorn** [comment] 2019-08-19 08:30
Custom tree -> @alexr00

**Comment by alexr00** [comment] 2019-08-20 16:15
Original bug was opened 28 days ago, so not new release at least.

@borekb we just added an additional bit of waiting in custom tree views. If you use insiders, you should be getting the update that contains the change in the next couple days. Since this looks like a timing issue I'd like to see if that waiting fixes the issue for you.

**Comment by borekb** [comment] 2019-08-20 17:26
Thank you. I have very rarely seen this but will be watching out for it and report back if it happens again.

**Comment by alexr00** [comment] 2019-09-18 10:37
Closing since no further reports.

**Comment by dalongi** [comment] 2019-10-21 20:48
@alexr00: I'm not sure if my cause is the same as @borekb, but I seem to be able to trigger a fairly reliable repro of "Bad Progress" error with custom view containers. 

- I have 2 viewcontainers, but only 1 is ever visible at a time.
- This is enabled by each viewcontainer having a View with a `when` clause. (One is `!isEnabled`, other is `isEnabled`)
- Inside my TreeDataProvider there is an async `getChildren`.
- Inside that `getChildren`, one codepath detects a specific condition and uses `executeCommand('setContext', ...)` to change `isEnabled` -> `!isEnabled`.
- This toggles which view and viewcontainer is visible.
- VS Code crashes with `Bad Progress Location` error.

I don't know this progress code, but does this point to any likely issue? (E.g. withProgress not handling the view disposing during the progress event?)

**Comment by alexr00** [comment] 2019-10-22 14:39
@dalongi thanks for the detail steps! Do you have an extension or repo I can try this with? I will be able to look at the issue sooner if so :)

**Comment by dalongi** [comment] 2019-10-22 15:59
I tried to get a minimal repro this morning but unfortunately haven't been
able to (and the extension is an internal/enterprise one, so cannot
share).The workaround I found may also help point to the issue. (Note: this
setup is wonky, the goal is to change the View Container Icon in a given
scenario, similar to a badge)

My previous setup was:
- container id: my-container
  - view id: my-view
- container id: my-container-alert
  - view id: my-view
- const treeDataProvider = new ...;
- registerTreeDataProvider('my-view', treeDataProvider)

My new setup that does not repro is:
- container id: my-container
  - view id: my-view
- container id: my-container-alert
  - view id: my-view-alert
- const treeDataProvider = new ...;
- registerTreeDataProvider('my-view', treeDataProvider)
- registerTreeDataProvider('my-view-alert', treeDataProvider)

**Comment by alexr00** [comment] 2020-01-23 16:17
This is happening because the extension has the same view listed more than once under various views in package.json. I can also see that's what the git tree view extension is doing in the OP. Having the same view in two different locations like that is not supported. The extension should register the view with a different ID in each location.

**Closed** 2020-01-23 16:18 UTC
Labels: *caused-by-extension, explorer-custom

**Comment by letmaik** [comment] 2020-01-23 16:22
@alexr00 Couldn't VS Code spit out an error if it detects such a situation? Linting the package.json by vsce would be even better.

**Comment by letmaik** [comment] 2020-01-27 22:03
@alexr00 I just had a look at my code to see if using different view ids (for essentially the same view) would be easy, but to be honest it would complicate things quite a bit. Since this works 99.9999% of the time it still looks like a VS Code bug to me. Allowing a single view to be moved to a different location should be easily supported with the technique we were using here (same view id, different when condition).

**Comment by letmaik** [comment] 2020-02-19 20:15
@alexr00 @sbatten With https://github.com/microsoft/vscode/commit/c303fc0ab24be137d4e365a024ec69cefbdfe979 my extension Git Tree Compare causes the new "A view with id `{0}` is already registered." error. Could you please comment on my last comment above?

**Comment by alexr00** [comment] 2020-02-20 13:11
If you change to use different view IDs does it still occur?

**Comment by letmaik** [comment] 2020-02-20 13:23
@alexr00 No, but that's not the issue. The issue is that existing extensions use the technique of identical view IDs so that a view can be displayed in one of multiple locations (never at the same time) based on some config option, and this seems to work just fine, except in some rare cases as described in this thread. In theory I can use different view IDs but that means I need to re-engineer how the extension works just to allow that it can be moved between different locations. Since this is non-trivial I will probably not do it and instead only allow a single location, which will likely upset users. Why is it so hard to *easily* support the case of displaying a view in one of multiple locations?

**Comment by sbatten** [comment] 2020-02-20 15:31
@letmaik with the work we are doing that caused this issue, users can move extension views without the need for extensions to support it. e.g. if your default location is to your own view container, a user will be able to drag the view into the explorer view with no additional work from you.

**Comment by letmaik** [comment] 2020-02-20 16:19
@sbatten Sounds good. Would that also support the case where a user can drag a view into the "explorer" container if by default it is located in the "explorer" container?

**Comment by sbatten** [comment] 2020-02-20 17:16
@letmaik, yep, it should be in tomorrow's insiders build
