### ISSUE TITLE
Debugger Step over out of sync

### ISSUE THREAD

**Issue by JSchatral** [microsoft/vscode#100295] opened 2020-06-16 14:16 UTC
Issue Type: <b>Bug</b>

Debugger Step over , Step in, Step out  very often out of sync with the source code lines in the souce code file  react-dom.development.js as an example. 
Please look at this:
const term = {data: {	products: products.map(product => ({ ...product, addedToCart: false }))	}, updateData: data => setContextData({ ...contextData, data: data })}
	debugger
	const [contextData, setContextData] = useState(term);

from https://github.com/RishikeshVedpathak/react-context-example

How can I solve this - Greetings from Germany J. Schatral

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (4 x 2610)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|14.27GB (4.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
vscode-eslint|dba|2.1.5
emulate|Die|1.4.0
vscode-babel-coloring|dza|0.0.4
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
sass-indented|rob|1.5.1

</details>

**Comment by connor4312** [comment] 2020-06-18 15:47
I'm not sure I completely understand your issue. Could you add simple reproduction steps, for example:

```
 1. I do one thing
 2. I do another thing
 3. I expect to see A, but actually B happens
```

**Comment by JSchatral** [comment] 2020-06-20 09:36
Okay - I do it for you step by step:
0. I download the repo from github
1. New Window under VC
2. Open Folder react-context-example-master after zip extraction
3. Open a Terminal Window and start "yarn install" - pease use yarn!
4. Type "yarn start" - localhost:3000 Chrome Window will be startet...
5. Type "F5" select Chrome, modify launch.json to localhost:3000
6. Start Debug again - okay - you should have a running Website
7. Set a breakpoint in /src/Home/index.js at line 9 and add a product to cart "ADD to cart" button
8. app stopps in Home/index.js line 9. Click F11 to step into... Click F11 4,5 or 10 times - you will see that the debugger stands in file "react-dom.development.js" not on the correct line 
Please look the screenshot:
![image](https://user-images.githubusercontent.com/29752945/85198610-46e92f80-b2ea-11ea-869b-515db3789e97.png)

Please give me an answer if you have the same result - I hobe it helps - Greeting from Germany
Mfg. J. Schatral

**Comment by connor4312** [comment] 2020-06-23 18:06
Thanks for the details!

This appears to be a duplicate of https://github.com/microsoft/vscode-js-debug/issues/487#issuecomment-636098158 and should be fixed if you install the latest `react-scripts` version.

**Closed by connor4312** 2020-06-23 18:06 UTC
Labels: debug, needs more info
