### ISSUE TITLE
UI's font size customization

### ISSUE THREAD

**Issue by namma-geniee** [Microsoft/vscode#40803] opened 2017-12-25 07:41 UTC
Please add new feature for customizing font-size of some UI's blocks, eg. tab, side bar, status bar... I really don't wanna change the zoom level.

Thank you!

**Comment by usernamehw** [comment] 2017-12-25 12:11
A duplicate of https://github.com/Microsoft/vscode/issues/519 ?

**Comment by namma-geniee** [comment] 2017-12-25 14:28
@usernamehw Yes! Yes!

**Closed** 2017-12-27 17:55 UTC
Labels: *duplicate, workbench
