### ISSUE TITLE
Prevent from scrolling out of popup.

### ISSUE THREAD

**Issue by hangacs** [microsoft/vscode#112525] opened 2020-12-15 06:00 UTC
Current problem.

Scroll up and down use mouse scroll wheel on documentation popup and if scrollbar scroll exceed scroll area, popup will disappear and vscode will continue scroll source code, which is annoying on long documentation.

![problem](https://user-images.githubusercontent.com/12413476/102176585-b0827900-3edc-11eb-83dd-dd8a27e3e203.gif)

Add an option to prevent editor from scrolling out of  popup or support keyboard navigation such as "End", "Home", "Down Arrow" in popup.

**Comment by Reeywhaar** [comment] 2020-12-15 13:54
duplicate of https://github.com/microsoft/vscode/issues/112373

**Closed** 2020-12-15 13:57 UTC
