### ISSUE TITLE
Debug launching before preLaunchTask ready when dependsOn task defined

### ISSUE THREAD

**Issue by halovanic** [Microsoft/vscode#54397] opened 2018-07-16 14:18 UTC
- VSCode Version: 1.26.0-insider (and 1.25.1)
- Commit: 6babef94104b27b252929324aa3c2d69cd38e9f2
- OS Version: Win10 x64

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Define a launch configuration with a preLaunchTask.
2. Define that preLaunchTask as a background task with a  (non-background) dependsOn task to execute before it.
3. Debug with the launch configuration.  The launch/debugger opens at what appears to be the completion of the dependsOn task, rather than when expected at the endsPattern of the preLaunchTask.  It is not immediate, but it is far too early.

Taking out the dependsOn task from the preLaunchTask definition results in the expected behavior: the debugger waits to launch at the point that the preLaunchTask prints a message matching the endsPattern.

Also, making the preLaunchTask a non-background task seems to have the expected behavior: the dependsOn task executes before the preLaunchTask before the launch configuration.

There is no difficulty outside of the launch: the tasks defined execute in the expected sequence and match problems whether they were started directly, or via the launch.  It's just that the debugger starts too early under these circumstances.  It also does not seem to be specific to any one launch extension.

Thanks,
Alex

launch.json:
```
{
"version": "0.2.0",
"configurations": [
    {
        "type": "chrome",
        "request": "launch",
        "name": "Debug in Chrome",
        "url": "https://localhost:3801",
        "webRoot": "${workspaceFolder}",
        "preLaunchTask": "Build and Watch",
    }
]
}
````
tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Install Packages",
            "type": "shell",
            "command": "yarn",
            "group": "build"
        },
        {
            "label": "Build and Watch",
            "dependsOn": "Install Packages",
            "type": "shell",
            "command": "yarn",
            "args": [
                "watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                {
                    "owner": "javascript",
                    "fileLocation": [
                        "relative",
                        "${workspaceFolder}"
                    ],
                    "pattern": [
                        {
                            "regexp": "(ERROR|WARNING) in (.*\\.js)",
                            "severity": 1,
                            "file": 2,
                        },
                        {
                            "regexp": "^.*$",
                        },
                        {
                            "regexp": "(.*)\\s\\((\\d+):(\\d+)\\)",
                            "message": 1,
                            "line": 2,
                            "column": 3
                        }
                    ],
                    "background": {
                        /* Problems are printed after this message. */
                        "beginsPattern": "Build Finished",
                        /* Matching Browsersync messaging. */
                        "endsPattern": "\\[TOOLKIT\\]",
                        "activeOnStart": true
                    }
                }
            ],
            "isBackground": true,
        }
    ]
}
```

**Comment by halovanic** [comment] 2018-07-16 14:32
I should also add that the only issue for me is just that the debugging browser launches before the website is ready: there is no actual problem with attaching or debugging, it just results in a "page could not be loaded" and having to manually refresh the browser.

If the preLaunchTask was already running prior to debug, then everything is fine too.

**Comment by isidorn** [comment] 2018-07-17 14:30
The issue here is that the `debugService` is waiting for the `Inactive` task event [here](https://github.com/Microsoft/vscode/blob/4e975a1bebd8e346a511339c8d177d8bf35a945a/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1077)
If the task depends on some other task, I would expect Inactive is only fired once all the tasks have completed -> forwarding to @dbaeumer 
Assign back to me if there is some other task API that I could use here which I am missing.

**Comment by dbaeumer** [comment] 2018-07-17 15:52
No your assumption is correct.

**Comment by dbaeumer** [comment] 2018-11-28 10:04
I looked into this and it is actually something debug needs to fix. The thing here is that two tasks are started but debug reacts in task inactive event without checking if the task it started is signalling the inactive event.

@isidorn you need to take the provided event into account. The event has either a `__task` property for which I guess you can do an identity compare with the task to started. If you fetched the task before and kept it around for a while you might compare the id. This will stay the same even if the task instance has changed. 

Moving back to debug

**Comment by isidorn** [comment] 2018-11-29 10:14
@dbaeumer thanks a lot for the investigation and for the fix
@EricJizbaMSFT @halovanic please verify in tomorrows vscode insiders that this fix actually fixes your issue. I just verified it does not break existing behavior. Thanks!

**Comment by EricJizbaMSFT** [comment] 2018-12-03 18:55
@isidorn I'm getting this every time I try to debug:
![screen shot 2018-12-03 at 10 51 35 am](https://user-images.githubusercontent.com/11282622/49394851-c8b63f80-f6e9-11e8-9e18-b3874901fd74.png)

I created a simple VS Code extension that replicates the bug when you F5:
https://github.com/EricJizbaMSFT/helloworldext

VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:12:08.874Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.71GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-cosmosdb|ms-|0.9.1
python|ms-|2018.11.0
azure-account|ms-|0.7.0
csharp|ms-|1.17.1
java|red|0.35.0
vscode-java-debug|vsc|0.15.0


</details>

**Comment by isidorn** [comment] 2018-12-04 09:53
Thanks for the repro steps, reopening and I plan to investigate later today / tomorrow

**Comment by isidorn** [comment] 2018-12-06 17:41
I can repro by cloning your repository.
So for this milestone I have decided to revert my "fix"

@dbaeumer @alexr00 the task ids that I am getting from the task service are not matching and so I can not detect that a task is started.

Assigning to @alexr00 and december to investigate than why the task ids are not matching.

To repro
1. Clone @EricJizbaMSFT repo
2. Set a breakpoint [here](https://github.com/Microsoft/vscode/blob/a427d31ec6fb8a76d527f348f998d538ab6ff0bd/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L729) and [here](https://github.com/Microsoft/vscode/blob/a427d31ec6fb8a76d527f348f998d538ab6ff0bd/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L724)
3. Start debugging and check the task ids I am getting are not matching the task.id

**Comment by dbaeumer** [comment] 2018-12-07 10:12
@alexr00 I quickly looked into this and there is something wired here. In this setup the terminal doesn't give us any `onExit` callback hence we end up in a very wired state. We do get the callback correctly for a single watch task. So not critical for today.

**Comment by dbaeumer** [comment] 2018-12-07 10:15
It does work if we give each task a dedicated panel

```typescript
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "reveal": "never",
                "panel": "dedicated"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "dependsOn": "npm: lint"
        },
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": "$tsc",
            "presentation": {
                "reveal": "never",
                "panel": "dedicated"
            },
        }
    ]
}
```

**Comment by alexr00** [comment] 2018-12-10 13:18
Based on @dbaeumer investigations, assigning back to @isidorn to listen for the right task.

**Closed** 2018-12-10 14:39 UTC
Labels: bug

**Comment by alexr00** [comment] 2018-12-11 14:43
Looked into it, and not having the right events is a duplicate of #64226, which is in turn a duplicate of #57803. The initial tsc compile lines simply never make it to the terminal which means our watching problem matcher can't fire the events we need. Until #57803 is fixed there is no good work around. Once you see the tsc compile start you can save a source file to cause the missing lines to print to the terminal.

**Comment by EricJizbaMSFT** [comment] 2018-12-14 17:57
@alexr00 I'm a little confused on if this is fixed or not. If it's not fixed - which issue should I track going forward?

**Comment by alexr00** [comment] 2018-12-17 08:35
There are two issues that contribute to what you're seeing:

#64865 was causing the terminal to not sent an onExit event. This issue is now fixed.
#57803 is causing the first couple terminal lines from tsc to not show. This is caused by Windows and the only fix for it is to upgrade past build 1809. This is the issue to track going forward, though I don't believe there will be a fix for it.

**Comment by aeschli** [comment] 2019-01-31 15:33
Steps to verify?
