### ISSUE TITLE
terminal display problem

### ISSUE THREAD

**Issue by goodideas** [Microsoft/vscode#72523] opened 2019-04-18 03:37 UTC
Issue Type: <b>Bug</b>

On terminal , if use `pwd` or other cmd , the result on terminal is incomplete , the underline is gone . 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4020)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (8.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
msg|ajs|0.1.1
ros|ajs|0.3.0
Doxygen|bbe|1.0.0
doxdocgen|csc|0.4.2
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
java|red|0.43.0
vscodeintellicode|Vis|1.1.5
vscode-arduino|vsc|0.2.25
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1

(1 theme extensions excluded)

</details>

**Comment by goodideas** [comment] 2019-04-18 06:21
![Screenshot from 2019-04-18 14-13-47](https://user-images.githubusercontent.com/4662474/56340633-0c1ad180-61e5-11e9-8696-dd2b26453b23.png)
My OS is Ubuntu 16.04 LTS

**Comment by yume-chan** [comment] 2019-04-18 07:38
looks like a duplicate of #35901

**Closed** 2019-04-18 14:36 UTC
Labels: integrated-terminal
