### ISSUE TITLE
syntaxFolding is not working in javascript-react Jsx section

### ISSUE THREAD

**Issue by YouWillBe** [Microsoft/vscode#51421] opened 2018-06-08 06:49 UTC
- VSCode Version:v1.24.0
- OS Version:Mac OS X High Sierra 10.13.5

Steps to Reproduce:

1.syntaxFolding is not working in javascript-react Jsx section

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by simida0852** [comment] 2018-06-08 06:57
I also encountered the same problem:sweat::sweat::sweat:

**Comment by YouWillBe** [comment] 2018-06-08 06:59
@simida0852 巧了，老铁

**Comment by mjbvz** [comment] 2018-06-08 08:27
Duplicate of #51266

**Closed by mjbvz** 2018-06-08 08:27 UTC
Labels: new release

**Comment by 1412108** [comment] 2018-06-19 09:09
Have this isssue fixed ?
