### ISSUE TITLE
Cursor width changes in the position zero of the line

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#60323] opened 2018-10-09 14:43 UTC
- VSCode Version: 1.28.0 
- OS Version: macOS Mojave

![](https://user-images.githubusercontent.com/2157285/46676944-71668800-cbee-11e8-9d20-d99d633c29b8.gif)

**Comment by usernamehw** [comment] 2018-10-09 14:56
Duplicate of #59328

**Closed** 2018-10-16 07:44 UTC
