### ISSUE TITLE
html-language-features incorrectly assumes there's an open workspace folder

### ISSUE THREAD

**Issue by jsayol** [Microsoft/vscode#65104] opened 2018-12-14 19:39 UTC
Issue Type: <b>Bug</b>

With the recent addition of support for custom HTML tags, the `html-language-features` extension incorrectly assumes that there is an open workspace folder.

https://github.com/Microsoft/vscode/blob/a50ee96c333167d5eed5b0fe99fe29ea88a2a943/extensions/html-language-features/client/src/htmlMain.ts#L55-L60

I've running into an error saying `Activating extension 'vscode.html-language-features' failed: Cannot read property '0' of undefined` while trying to open an untitled HTML document from another extension I'm developing.

### Steps to reproduce:
1. Create a new empty extension
2. Add the following code the new extension's `activate()` function:
	```ts
    vscode.workspace.openTextDocument({
        language: 'html',
        content: '<b>hello</b>'
      })
      .then(textDocument => {
        vscode.window.showTextDocument(textDocument);
      });
	```
3. Launch the extension

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.19.8-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 1220)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|9.75GB (1.89GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
xml|Dot|2.4.0
gitlens|eam|9.2.0
tslint|eg2|1.0.41
prettier-vscode|esb|1.7.2
vscode-yarn|gam|1.6.0
docthis|joe|0.7.1
contextualduplicate|laf|0.2.0
Angular-BeastCode|Mik|7.0.20
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.1
pegjs-language|Sir|0.1.0
vsfire|tob|1.3.2
markdown-all-in-one|yzh|1.8.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment] 2018-12-14 20:36
Duplicate of #64993.

**Closed by octref** 2018-12-14 20:36 UTC
Labels: new release
