### ISSUE TITLE
VS Code crashes with find widget on webview

### ISSUE THREAD

**Issue by scnwwu** [microsoft/vscode#201478] opened 2023-12-25 07:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a markdown file in VS Code
2. Press Ctrl+Shift+V, or perform command `Markdown: Open Preview`
3. In the preview page, press Ctrl+F to open the find widget
4. Type a character in the find widget to find, so that it highlights occurrences
5. Click the markdown editor tab
6. Click the preview tab, VS Code crashes

**Comment by mjbvz** [comment] 2024-08-02 21:12
Duplicate of #213147 (newer issues but has more discussion)

**Closed by mjbvz** 2024-08-02 21:12 UTC
Labels: freeze-slow-crash-leak, webview
