### ISSUE TITLE
Edge Tools Server crashes

### ISSUE THREAD

**Issue by bartroozendaal** [microsoft/vscode#146519] opened 2022-04-01 09:23 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: Windows 11Pro 21H2

Done actually know how to reproduce this, as it just happens at startup of vscode. These are the messages in the log:

[Info  - 11:07:28 AM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\dev\senses"
Trying to load shared version
Found hint at c:\Users\BartRoozendaal\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\BartRoozendaal\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\BartRoozendaal\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async t.Analyzer.validateTextDocument (c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async t.Analyzer.validateTextDocument (c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\BartRoozendaal\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Error - 11:07:30 AM] Connection to server got closed. Server will not be restarted.

**Comment by aeschli** [comment] 2022-04-04 07:05
This needs to be fixed in the vscode-edge-devtools extension.

Looking at the issues there I see it has already been reported.
Duplicate of https://github.com/microsoft/vscode-edge-devtools/issues/954

**Closed by aeschli** 2022-04-04 07:05 UTC
Labels: triage-needed
