### ISSUE TITLE
VS Code closing itself

### ISSUE THREAD

**Issue by mhmmd-ysf** [microsoft/vscode#92691] opened 2020-03-14 13:52 UTC
[Video](https://imgur.com/a/1ZJXwUb)
Type: <b>Bug</b>

sometimes the VS Code crash and closes itself, mainly when you switch out to other app while you're browsing extensions

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rebornix** [comment] 2020-03-15 20:53
/duplicate of https://github.com/microsoft/vscode/issues/92420

**Closed** 2020-03-16 02:50 UTC
Labels: *duplicate
