### ISSUE TITLE
smoothScrollingWorkaround seems to clash with custom title bars

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#65224] opened 2018-12-17 18:52 UTC
- VSCode Version: 1.30
- OS Version: Windows

Steps to Reproduce:

1. When having `"window.smoothScrollingWorkaround": true` custom window title bars seems to get rendered weirdly.

![image](https://user-images.githubusercontent.com/173559/50108313-bfe56380-01e9-11e9-99e1-73eac4d1775e.png)

Reported from Twitter, https://twitter.com/DRXDesign/status/1073202667781087232

**Comment by usernamehw** [comment] 2018-12-17 19:05
/duplicate of #63982 

List of settings that will disable custom title bar: https://github.com/Microsoft/vscode/issues/64967#issuecomment-446965079

**Closed** 2018-12-17 19:05 UTC
Labels: *duplicate
