### ISSUE TITLE
Git no longer detected

### ISSUE THREAD

**Issue by kahanu** [microsoft/vscode#138862] opened 2021-12-10 16:24 UTC
Issue Type: <b>Bug</b>

I'm not sure what happened, but I think after this last VS Code update, that it no longer detects my git repository.  I've been using VS Code and the built in source control feature for years and suddenly it thinks I don't have a .git folder, which I do.

Thankfully I was still able to do all the normal git commands via the CLI to push my latest changes to my remote repo.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.54GB free)|
|Process Argv|--crash-reporter-id 0d358951-55ab-48e2-8ec1-fb912c4c90c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ng-template|Ang|13.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
prettier-vscode|esb|9.0.0
vscode-test-explorer|hbe|2.21.1
Angular2|joh|12.0.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
remote-containers|ms-|0.209.4
test-adapter-converter|ms-|0.1.4
debugger-for-chrome|msj|4.13.0
angular-karma-test-explorer|raa|1.2.8
vscode-scss-formatter|sib|2.3.3
vscode-icons|vsc|11.8.0
quokka-vscode|Wal|1.0.431
wallaby-vscode|Wal|1.0.320

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-12-10 16:32
Maybe #138754

**Comment by lszomoru** [comment] 2021-12-10 17:32
@kahanu, sorry about that. I am investigating the issue as I believe that I have a repro.

**Comment by lszomoru** [comment] 2021-12-10 17:36
@kahanu, I take it back. Unfortunately I cannot reproduce the issue so I was wondering if you could try the following: 
1. Open the folder in VS Code, and go to `View -> Output` and send me the contents of the `Log (Extension Host)` channel.
2. From the command palette invoke the `Git: Show Git Output` command and see if that causes the extension to activate.

**Comment by kahanu** [comment] 2021-12-10 19:07
For 1) the console was blank.
For 2) that worked!  Hopefully this continues to work when I reopen next week.  But for now, thanks!

**Comment by lszomoru** [comment] 2021-12-10 19:22
Thanks! This does confirm that for some reason the `git` extension is not being activated. Performing the steps from 2) will force the extension to activate. Could you try launching VS Code using `code --disable-extensions` and see if that also resolves the problem. If it does then we need to track down the extension that causes the `git` extension not to activate so that we can further debug the issue.

**Comment by kahanu** [comment] 2021-12-11 01:29
Ok, a couple things.  This happens occasionally, where VS Code simply closes while I'm working.  I haven't discovered a pattern as to why, but the last time it did it was just after I was rebuilding my Angular project.  When I opened VS Code again, and made a change to a file, it was not picked up by the source control feature.

But launching `code --disable-extensions` did enable source control to pick up a saved change to a file.  I hope this helps.  I'm Ok with helping to debug this if I can.  I don't always check this feed, but I'll try to check it every so often.  Thanks.

**Comment by lszomoru** [comment] 2022-01-04 20:10
Thanks @kahanu for the additional details. If the issue reoccurs in the future you can use [the extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) in order to track down the culprit extension. I will be closing this issue for now, and please reopen it in case the issue reoccurs with all extensions being disabled.

**Closed by lszomoru** 2022-01-04 20:10 UTC
Labels: bug, git
