### ISSUE TITLE
onDidSaveTextDocument, unlike onWillSaveTextDocument, is called for internal files such as settings.json

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#122053] opened 2021-04-23 17:34 UTC
- VS Code Version: 1.55
- OS Version: Windows 8

Steps to Reproduce:

1. Subscribe to onDidSaveTextDocument
2. Change VSCode settings
3. Notice that the callback is called for settings.json

This doesn't happen for onWillSaveTextDocument, and I expected that each saved file goes through both. Also see no reason to be notified about settings.json, or at least give an option to ignore internal files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2021-04-26 06:59
I see no reason to ignore such files tbh. They are normal files like all others and you have an interest in knowing that they change. 

Adding @sandy081 for why the settings files aren't going through the text file service (which would trigger the onWillSave-flow).

**Comment by justanotheranonymoususer** [comment] 2021-04-26 07:17
I don't mind, but then add a flag to be able to ignore them.

**Comment by sandy081** [comment] 2021-04-27 13:06
I skip all save participants when it is a programmatic change - https://github.com/microsoft/vscode/blob/52cc4e6a0d5aff1f4827d90dda69c0ee35e3415a/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L201-L201

I do not do any special logic if user saves the file directly by opening the file.

**Comment by jrieken** [comment] 2021-04-27 13:32
Yeah. I think that makes sense. Closing as designed

**Closed** 2021-04-27 13:33 UTC
Labels: *as-designed, under-discussion

**Comment by justanotheranonymoususer** [comment] 2021-04-27 13:36
Why close? Why do I see settings.json in onDidSaveTextDocument then?

**Comment by jrieken** [comment] 2021-04-27 13:40
> Why do I see settings.json in onDidSaveTextDocument then

Because it is a text document and because it is being saved. You don't see the will-save event because we don't allow save-participation for some files

**Comment by justanotheranonymoususer** [comment] 2021-04-27 13:43
What's save-participation and where is it documented? I think it's not
intuitive that both callbacks are so similarly named yet so different.

**Comment by justanotheranonymoususer** [comment] 2021-04-27 13:47
Also, what's the best way to monitor for files that are saved from open
tabs by the user?
