### ISSUE TITLE
The 'protocol' parameter is ignored if node debugging starts from an extension

### ISSUE THREAD

**Issue by romanresh** [Microsoft/vscode#24762] opened 2017-04-14 09:55 UTC
- VSCode Version: 1.11.2
- OS Version: Win10
- Node Version: 7.7.4

Steps to Reproduce:

My extension starts debugging via this code:
```js
vscode.commands.executeCommand("vscode.startDebug", {
            "type": "node",
            "protocol": "auto", // this line I've added to prevent showing the 'deprecation' message
            "request": "launch",
            "name": "Launch current test(s) with TestCafe",
            "program": "${workspaceRoot}/node_modules/testcafe/lib/cli/index.js",
            "args": args,
            "cwd": "${workspaceRoot}"
        });
```

But I still see the warning: `(node:34248) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.`. 

It looks like the 'protocol' parameter is ignored. If I change its value to 'inspector' the deprecation message is not changed.

This is the full output:
`node --debug-brk=40687 --nolazy node_modules\testcafe\lib\cli\index.js chrome c:\Sources\2017.1\testcafe-tests\bootstrap\demos-gridview\Templates.js --test 'XXX' 
(node:34248) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:40687`

**Comment by romanresh** [comment] 2017-04-14 10:12
I forgot to mention that the 'protocol' parameters works correctly if I start debugging via F5 (without extension) on the same machine. So, this parameter is not ignored if it's set in launch.json.

**Comment by isidorn** [comment] 2017-04-24 08:53
Dupe of https://github.com/Microsoft/vscode/issues/21835

**Comment by isidorn** [comment] 2017-05-11 12:52
The issue is that startSession is not called when an object is passed to startDebug action.
More details https://github.com/Microsoft/vscode/issues/21835

**Comment by SAKryukov** [comment] 2017-07-17 11:46
It is not ignored. Tracing of vscode shows that instead of `type: "node"` `type: "node2"` is used.

Replace `node` with `node2` as a work-around.

It needs to be resolved. `node` and `node2` should either be merged with getting rid of `node2`, or at least it should be documented.

**Comment by weinand** [comment] 2017-08-22 16:35
`vscode.commands.executeCommand("vscode.startDebug")` has been deprecated.
The official API is now `vscode.debug.startDebugging` (see https://code.visualstudio.com/updates/v1_15#_debug-api-updates).
`startDebugging` honours the "protocol" attribute.

**Closed by weinand** 2017-08-22 16:35 UTC
Labels: bug, debug

**Comment by SAKryukov** [comment] 2017-09-18 03:54
Andre,

Thank you very much for your notification on `startDebugging` API. I successfully implemented it immediately after it appears in next VSCode version and then employed your explanations in response to my (incorrect, closed) issue report.

I use it in my VSCode plugin contribution [vscode-markdown-it-plugin-development-framework](https://github.com/SAKryukov/vscode-markdown-it-plugin-development-framework). Due to the deprecation in VSCode API you mentioned, release 4.0.0 is the major release; in its dependencies, it deprecates the use of VSCode prior to v.1.15.0 and documents it. This way, I have smooth transition, without incompatible versions.

Thank you.

—SA

**Comment by weinand** [comment] 2017-09-18 20:04
@SAKryukov great to hear that the new API works for you!
