### ISSUE TITLE
New Shortcut for "Focus Breadcrumbs" erased customized one and can't be modified

### ISSUE THREAD

**Issue by JeanPerriault** [microsoft/vscode#173268] opened 2023-02-03 09:21 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: macOS 12.6.2

Steps to Reproduce (:

1. Open dedicated view from top menu, Code -> Preferences -> Keyboard Shortcuts
2. In top search bar, type "Focus Breadcrumbs" or "cmd+[Period]" after clicking "Recording Keys" left button. There are two lines for breadcrumbs.focus (Source = System or Source = User, maybe this second entry has been created when I first tried to update the system shortcut)
3. Try to update the shortcut by clicking on line and entering a new one => changes are taken into account in the "Source = User" line. Maybe this is intended.
4. Now type in search bar "Add Line Comment". Once again two lines. Try to modify "Source = System" using "cmd+[Period]": you have a message stating that shortcut is already used, the "Source = User" is modified with "cmd+F3", which is absolutely not what I wanted.

Worth mentioning that I was already using this shortcut for "Add Line Comment" (I'm using very frequently), but that it has been reverted to default one by this 1.75.0 update...

In keybindings.json (supposed to override the defaults, I have those weird lines at the end: 

```json
// Place your key bindings in this file to override the defaultsauto[]
[
  {
    "key": "shift+alt+n",
    "command": "Notes.newNote"
  },
  {
    "key": "alt+n",
    "command": "-Notes.newNote"
  },
  {
    "key": "shift+alt+cmd+d",
    "command": "workbench.view.debug",
    "when": "viewContainer.workbench.view.debug.enabled"
  },
  {
    "key": "shift+cmd+d",
    "command": "-workbench.view.debug",
    "when": "viewContainer.workbench.view.debug.enabled"
  },
  {
    "key": "shift+cmd+d",
    "command": "editor.action.deleteLines",
    "when": "textInputFocus && !editorReadonly"
  },
  {
    "key": "shift+cmd+k",
    "command": "-editor.action.deleteLines",
    "when": "textInputFocus && !editorReadonly"
  },
  {
    "key": "numpad9",
    "command": "breadcrumbs.focus",
    "when": "breadcrumbsPossible && breadcrumbsVisible"
  },
  {
    "key": "cmd+[Period]",
    "command": "editor.action.addCommentLine",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "cmd+[Period]",
    "command": "-breadcrumbs.focus",
    "when": "breadcrumbsPossible && breadcrumbsVisible"
  },
  {
    "key": "cmd+k cmd+c",
    "command": "-editor.action.addCommentLine",
    "when": "editorTextFocus && !editorReadonly"
  }
]
```
I've tried to modify this file without success

**Comment by FlorianBarnier** [comment] 2023-02-03 09:45
I have the same problem since update 1.75.0. Not only "Focus Breadcrumbs" cannot be remapped, but it also seems to be the only shortcut that cannot be removed either.
There's also "cmd+[Comma]" which results in a "cmd+F2", which also broke another of my shortcut.

**Comment by benj2k** [comment] 2023-02-03 11:23
Same problem here.
VSCode 1.75.0
Ubuntu 22.04

**Comment by Victor-N-Suadicani** [comment] 2023-02-03 14:33
My keybindings were also just broken. Seems that previously this worked fine:
```json
	{
		"key": "ctrl+[Comma]",
		"command": "editor.action.showHover",
		"when": "editorTextFocus"
	},
```
But now it has to be this for some reason?
```json
	{
		"key": "ctrl+oem_comma",
		"command": "editor.action.showHover",
		"when": "editorTextFocus"
	},
```
Not a great experience to break the user's keyboard shortcuts :(

**Comment by mattchete** [comment] 2023-02-03 14:49
Same here

**Comment by rochesebastien** [comment] 2023-02-04 19:38
Same problem here...

**Comment by MohamedRahoui** [comment] 2023-02-05 04:58
+1

**Comment by Snouzy** [comment] 2023-02-05 10:03
same, productivity killer

**Comment by alexdima** [comment] 2023-02-05 21:01
Duplicate of #173325

**Closed by alexdima** 2023-02-05 21:01 UTC
Labels: new release

**Comment by FlorianBarnier** [comment] 2023-02-06 09:12
Unless I'm missing it, the other issue does not mention the fact that "Focus Breadcrumbs" cannot be remapped nor removed, which is going to cause conflicts even after the fix when trying to map a shortcut on "cmd+[Period]".
