### ISSUE TITLE
Markdown styles user setting.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#47068] opened 2018-04-02 04:33 UTC
Issue Type: <b>Bug</b>

No longer works with absolute path, this use to work.

   "markdown.styles": [
     "/Users/yadav/dev/docs/preview-md.css"
   ],

VS Code version: Code - Insiders 1.22.0-insider (6c22e21cdcd6811770ddcc0d8ac3174aaad03678, 2018-03-30T05:10:29.002Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
ng-template|Ang|0.1.9
vscode-markdownlint|Dav|0.14.1
EditorConfig|Edi|0.12.1
vsc-material-theme|Equ|1.5.1
material-icon-theme|PKi|3.2.6
sort-lines|Tyr|1.5.0
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.28
sort-typescript-imports|mic|1.4.1
angular2-inline|nat|0.0.17
npmsmartimporter|ref|3.0.0
language-stylus|sys|1.9.1
vim|vsc|0.11.3
better-align|wwm|1.1.6
markdown-pdf|yza|0.1.8

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-04-02 17:09
Duplicate of #45260. See that issue for rational for this change and workarounds

**Closed by mjbvz** 2018-04-02 17:09 UTC
Labels: insiders
