### ISSUE TITLE
Permission problem?

### ISSUE THREAD

**Issue by MJomaa** [Microsoft/vscode#2821] opened 2016-02-09 07:20 UTC
If I run VSCode as **root** from bash on Ubuntu/Xubuntu/Lubuntu/Kubuntu it doesn't respond on startup.
This problem occurred on fresh installs, in VMs, on both of my devices.
However running a quick ```chown -R root:root /``` fixed the problem (It is a local VM, so whatever).
[Disclaimer: Know what you do, do not copy paste that into your terminal]

Anyone else experienced the same on a Ubuntu based distro lately? On Debian/Arch it works just fine.

BTW: I couldn't install the omnisharp plugin for Atom because of the exact same reason.

**Comment by joaomoreno** [comment] 2016-02-09 09:35
Seems to be a duplicate of #2774

**Closed by joaomoreno** 2016-02-09 09:35 UTC
