### ISSUE TITLE
"files.exclude" does not match double-extension files with "when": "$(basename).ext"

### ISSUE THREAD

**Issue by nickspoons** [Microsoft/vscode#3760] opened 2016-03-07 02:10 UTC
It is not possible to match files with a double-extension using "$(basename).ext", i.e. ".js.map" or ".min.css".
You can currently workaround matching ".js.map" files by excluding the extention in the "when":
```
{
   "files.exclude": {
      "**/*.js": { "when": "$(basename).ts"},
      "**/*.js.map": { "when": "$(basename).ts"},   // Does nothing
      "**/*.js.map": { "when": "$(basename)"},      // Works
      "**/*.css": { "when": "$(basename).scss"},
      "**/*.min.css": { "when": "$(basename).scss"} // Does nothing
   }
}
```

Ideally I would like to use `"when": "$(basename).ext"` to exclude ".js" and ".js.map" transpiled Typescript files, and ".css" and ".min.css" transpiled and minified Sass or Less files:
```
{
   "files.exclude": {
      "**/*.js": { "when": "$(basename).ts"},
      "**/*.js.map": { "when": "$(basename).ts"},
      "**/*.css": { "when": "$(basename).scss"},
      "**/*.min.css": { "when": "$(basename).scss"}
   }
}
```

This issue could possibly be resolved by allowing regex expressions, as described in #1214

**Comment by bpasero** [comment] 2016-03-07 10:52
@nickspoons I am not sure how this would work even if #1214 gets implemented. You have a file `something.min.css` so the `$(basename)` will resolve to `something.min`. What you actually want to use is a `$(something)` that would resolve to `something` so that you can type `something.ts`, e.g.:

```json
{
   "files.exclude": {
      "**/*.min.css": { "when": "$(something).scss"}
   }
}
```

Would you agree?

**Comment by bpasero** [comment] 2016-03-24 13:39
marking as duplicate of https://github.com/Microsoft/vscode/issues/4642

**Closed by bpasero** 2016-03-24 13:39 UTC
Labels: bug
