### ISSUE TITLE
Create empty file, add content and cannot save.

### ISSUE THREAD

**Issue by kathenas** [microsoft/vscode#126749] opened 2021-06-19 18:13 UTC
Create empty file, add content and cannot save.

See screenshot. Empty file created and content added but 'Save'/'Save As...' not activated.

![Screenshot from 2021-06-19 19-09-36](https://user-images.githubusercontent.com/68813857/122651685-4f10c080-d132-11eb-9ff5-0cf7f84ecbc0.png)

Info....

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.0-0.bpo.7-amd64

**Comment by isidorn** [comment] 2021-06-22 12:07
I believe this is a duplicate of a known issue that @sbatten fixed, thus forwarding to him and he can close as dup

**Comment by sbatten** [comment] 2021-06-22 16:50
dupe https://github.com/microsoft/vscode/issues/126133

**Closed by sbatten** 2021-06-22 16:50 UTC
