### ISSUE TITLE
Ended up with duplicate views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96391] opened 2020-04-28 12:19 UTC
Testing https://github.com/microsoft/vscode/issues/96318

I'm not entirely sure how this happened, so feel free to close as unactionable. I was moving Gitlens Line History around (to panel, to terminal view container, to explorer, and back). Now I have two Line History views

![image](https://user-images.githubusercontent.com/38270282/80486288-3310f500-895b-11ea-9175-264ba698d36f.png)

**Comment by sbatten** [comment] 2020-04-28 17:14
feel free to unassign yourself sandy but that one is strange

**Comment by sandy081** [comment] 2020-04-28 17:20
Interested to see how this can be reproduced.

I am suspecting this can happen if ViewContainerModel triggers add event on visible descriptors

https://github.com/microsoft/vscode/blob/bbc69e235c9e7c86d582b23ee5a273c2b2b60095/src/vs/workbench/services/views/common/viewContainerModel.ts#L406-L410

Because similar thing happened while fixing - #96064.

**Comment by sandy081** [comment] 2020-04-28 17:22
Is it possible to get the global state when this happened? 

You can use the command `Developer: Log Storage Database Contents` to get it.

**Comment by sandy081** [comment] 2020-04-28 17:54
I suspect this is a duplicate of #96453

**Comment by sbatten** [comment] 2020-04-28 18:07
re-open if it repros after today.

**Closed by sbatten** 2020-04-28 18:07 UTC
Labels: bug, workbench-views
