### ISSUE TITLE
CSS syntax misspelled include

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode#40287] opened 2017-12-15 10:32 UTC
On [line 1061](https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json#L1061) of the CSS syantax, I believe it should be `#property-values` since `property-value` does not exist. This is just based on my limited understanding of Textmate grammars.

@aeschli

**Comment by aeschli** [comment] 2017-12-15 11:56
duplicate of #40157. I created https://github.com/atom/language-css/issues/133

**Closed by aeschli** 2017-12-15 11:56 UTC
Labels: css-less-sass
