### ISSUE TITLE
Opening a folder with custom scheme does not work (remote, desktop)

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#110352] opened 2020-11-10 21:49 UTC
- VSCode Version: 1.51.0-insider
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

Steps to Reproduce:

(Running an extension in Codespaces)

1. Execute this command to open a folder in the current window. The URI is from a [custom file system](https://github.com/microsoft/vscode-azurestorage/blob/4f15c16b60cdc9aff790343c4f69654a5e50d440/package.json#L34).
```typescript
await commands.executeCommand('vscode.openFolder', uri, false /* forceNewWindow */);
```
2. An error is thrown
<img width="460" alt="Screen Shot 2020-11-10 at 1 18 26 PM" src="https://user-images.githubusercontent.com/22795803/98736771-20d83080-235a-11eb-8426-e4c44f9fbf7a.png">

Hovering over the workspace folder shows this warning:
![image](https://user-images.githubusercontent.com/22795803/98736847-3a797800-235a-11eb-8b17-2cd25b397b01.png)

Clicking on the workspace folder throws this error:
![image](https://user-images.githubusercontent.com/22795803/98736878-46653a00-235a-11eb-8a88-e7c000b2f13c.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by bpasero** [comment] 2020-11-11 07:08
@wwlorey to clarify, you are connecting to a Codespace via web or desktop client?

**Comment by wwlorey** [comment] 2020-11-12 00:11
I was using the web client

**Comment by bpasero** [comment] 2020-11-12 07:50
@wwlorey did your window reload as a matter of adding a folder? or were you already inside a multi root context?

**Comment by wwlorey** [comment] 2020-11-12 21:53
The window reloaded when I opened a folder in the current window (not adding it to my workspace) so it replaced the folder I had open. I executed the command in a single root workspace

**Comment by isidorn** [comment] 2021-02-02 12:55
Are you still seeing this with latest?

**Comment by wwlorey** [comment] 2021-02-02 19:28
@isidorn trying this in both Codespaces stable and insiders redirects to this page: https://github.com/codespaces/

**Comment by isidorn** [comment] 2021-02-03 10:20
@wwlorey ok, if you can not access your old Codespace, can you reproduce with a new one?

**Comment by wwlorey** [comment] 2021-02-03 20:05
@isidorn I ran into the same problem when I created a new Codespace. When I attempt to open a folder in the current window, it kicks me back to the Codespaces landing page.

**Comment by bpasero** [comment] 2021-02-04 07:14
> When I attempt to open a folder in the current window, it kicks me back to the Codespaces landing page.

This sounds like a regression, maybe from the work on supporting "Open Recent" across workspaces.

@jkeech @legomushroom

**Comment by jkeech** [comment] 2021-02-04 21:15
@wwlorey, how are you opening the folder? Is it a folder in the same codespace, or a "Recent folder" from a different codespace? If it's a recent folder from a different codespace AND that folder was added to the recent folder list prior to about a week ago, it won't properly redirect to the new codespace.

We made a change about a week ago in how we store info in that recent folder entry which allows switching between codespaces, but only for entries added to the list after that time which has the necessary info in the entry.

It's also not fully solved yet -- if you switch codespaces through the recent folders list, it will only connect you back to the last-used folder instead of the requested folder, since the query param that includes the folder path gets dropped on the redirect through github.com auth for the codespace switch. That only applies when switching between codespaces though -- switching to other folders within the same codespace is expected to work.

**Comment by wwlorey** [comment] 2021-02-04 23:03
@jkeech The folder I'm opening is a virtual folder - specifically a blob container opened via the [Azure Storage Extension](https://github.com/microsoft/vscode-azurestorage).

**Comment by jkeech** [comment] 2021-02-04 23:13
> @jkeech The folder I'm opening is a virtual folder - specifically a blob container opened via the [Azure Storage Extension](https://github.com/microsoft/vscode-azurestorage).

Sorry, maybe my question wasn't clear. How is the folder open being invoked? Is this programmatically as listed above or via the File -> Open recent list? If programmatic, can you give an example uri that you are passing into the open folder command?

The screenshot above shows the `vsonline+` resolver scheme being used, but that's no longer used for GitHub Codespaces, so it should be a `vscode-remote://codespaces+{codespace_name}/{path}` uri for the open folder to work properly.

**Comment by jkeech** [comment] 2021-02-04 23:30
Ah, I don't think Codespaces allows opening virtual folders today directly, but you should be able to add a virtual folder to a VS Code workspace and then open the workspace. Does that work if you try it?

**Comment by jkeech** [comment] 2021-02-05 00:09
I just did some tests with the Azure Storage extension, and "Add to workspace" works properly when connected to the codespace from desktop VS Code. It doesn't work in the web. I've filed a bug to fix that.

When opening the virtual folder directly, it fails for different reasons on web and desktop. Both are partially related to the fact that the uri that is being opened has an `azurestorage` authority, so VS Code attempts to open it with the Azure Storage extension instead of tunneling it through the Github Codespaces extension. This results in desktop VS Code trying to open the Azure Storage url on the desktop side without even trying to connect to the codespace through the GitHub Codespaces resolver. Nesting the `azurestorage` uri inside of a vscode workspace file works around this issue since the workspace is opened through Codespaces and then the folder inside the codespace uses the virtual file system. I'm not sure the best way to solve this. @bpasero, any ideas?

**Comment by bpasero** [comment] 2021-02-09 07:13
@jkeech if I understand you correctly, the ask here is to support non remote (`vscode-file://`) folders to open in web in a codespace? Honestly I neither think we ever supported that nor think we support it currently, nor did we ever test this. So it is well possible that this is simply not implemented currently and could be well buggy.

**Comment by jkeech** [comment] 2021-02-09 07:25
@bpasero, the ask is to be able to connect to a virtual folder provided by a different extension from inside the remote codespace, referenced via a VS Code uri generated from https://github.com/microsoft/vscode-azurestorage/blob/bfd8683a4439dd379cd9a1695ad24d7bf7fef11f/src/AzureStorageFS.ts#L55.

The desktop scenario seems the most challenging, since the VS Code client parses the `azurestorage` uri passed in to the open folder command and attempts to resolve it with the Azure Storage extension. We would need to come up with a way to embed that uri inside of the codespace resolver uri so that the Codespaces remote resolver is invoked and then VS Code opens the virtual folder inside the codespace. We can workaround this by using a workspace file so that the workspace file is opened in the codespace, and then the workspace includes the virtual folder as a second hop, but I don't think there's currently a way to encode both the resolver authority for the codespace and the `azurestorage` virtual file system into a single VS Code uri without the workspace bridge in the middle. Hopefully that makes sense 😄.

**Comment by bpasero** [comment] 2021-02-09 07:32
@jkeech so this issue is wrongly labeled as "web"? Or did we just hijack this issue to support opening virtual folders in Codespace connected from desktop?

**Comment by jkeech** [comment] 2021-02-09 07:35
@bpasero, the issue is filed for web, but I tried it in both and both fail. I guess it could be treated as two separate issues. Web seems more solvable to me, even though it's not implemented, since the Codespaces embedder is always in the picture when resolving urls. We'd just need to change the web to allow schemes to be included in the query params on the folder to open and handle all of the parsing correctly. Is there anything else needed to handle this in web?

**Comment by jkeech** [comment] 2021-02-09 07:37
To clarify, I believe the web part of this is a Codespaces service issue, not a VS Code core issue. The desktop scenario needs some more thought though, and might require VS Code changes.

**Comment by bpasero** [comment] 2021-02-09 09:49
It seems to me the web piece is covered by https://github.com/microsoft/vssaas-planning/issues/2534 then.

**Comment by bpasero** [comment] 2021-02-19 12:34
@aeschli this seems like a missing thing / oversight from the work on remote. If an extension asks to open a folder, we probably need to preserve the `remoteAuthority` of that opening window in case the folder uses a custom scheme that is implemented by an extension that lives in the remote extension host. Otherwise we end up not being able to resolve the folder.

Here is what happens:
* a user installs an extension into the remote that implements a custom file system provider
* this extension has a command to open a window on said custom file scheme
* the user triggers this
* a new window opens, but it will be a local window without `remoteAuthority`
* the explorer tries to resolve the custom scheme, but fails because the extension is only available in the remote

Any ideas how to solve this? I guess the challenge would be to know wether the new window should inherit the `remoteAuthority` or not.

**Comment by bpasero** [comment] 2021-02-22 09:55
More findings & thoughts:
* it looks like [`IOpenEmptyWindowOptions`](https://github.com/microsoft/vscode/blob/a830cb5f74e5a487dd8a764c84e1fa38f3e763dd/src/vs/platform/windows/common/windows.ts#L50-L50) has support for passing in remote authority so maybe this should move to [`IBaseOpenWindowsOptions`](https://github.com/microsoft/vscode/blob/a830cb5f74e5a487dd8a764c84e1fa38f3e763dd/src/vs/platform/windows/common/windows.ts#L20-L20)
* there is weird code to get the `remoteAuthority` in on the main side via cli, I would strongly suggest to make this a real option and not hide within the CLI [1]

[1]

https://github.com/microsoft/vscode/blob/58e22bc5226e156f7ec356650547871dd4477646/src/vs/platform/windows/electron-main/windowsMainService.ts#L162-L166

**Closed** 2021-03-10 14:01 UTC
Labels: bug, remote

**Comment by wwlorey** [comment] 2021-03-19 21:05
I'm still running into this issue on 1.55.0-insider. It no longer kicks me to the codespaces landing page but it does show the original error when opening a remote folder in the current window or a new window.

![image](https://user-images.githubusercontent.com/22795803/111841725-a8f7b500-88bb-11eb-9bfd-d5831ac2454e.png)

**Comment by aeschli** [comment] 2021-03-23 12:39
@wwlorey Can you open a new issue with your steps? What's the URI that is being opened?
