### ISSUE TITLE
Code outline for entire workspace

### ISSUE THREAD

**Issue by pmunin** [Microsoft/vscode#32837] opened 2017-08-19 23:21 UTC
Feature request

Currently vscode displays CODE OUTLINE for current file only.
It would be great if there was a way to see code outline for all modules in the workspace (including full hierarchy of modules), not only for current file, like "Class view" or "Object explorer" in Visual Studio, 

- VSCode Version:
- OS Version:

**Comment by aeschli** [comment] 2017-08-21 07:08
duplicate of #5605

**Closed by aeschli** 2017-08-21 07:08 UTC
