### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:4 and sourceFile.scriptKind: 3, !entry: false

### ISSUE THREAD

**Issue by watscho** [microsoft/vscode#208067] opened 2024-03-19 07:18 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.4.2

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-vue-plugin-bundle` contributed by the `Vue.volar` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.88.0-insider (Universal) (9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a, 2024-03-18T05:50:07.245Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|--crash-reporter-id d1cb6b4b-5af4-4646-be46-b75d202322f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.11.51
npm-intellisense|chr|1.4.5
postcss|css|1.0.9
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|2024.3.1805
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
CSS-Modules-transform|jin|0.0.7
dotenv|mik|1.0.1
vscode-css-peek|pra|4.4.1
vscode-stylelint|sty|1.3.0
volar|Vue|2.0.6
vscode-wakatime|Wak|24.4.0
browserslist|web|1.1.0
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vscaat:30438846
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
pydisww2:30991134
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp2r6:30958154
pythonait:30973460
7ghi1836:30988844

```

</details>

**Comment by johnsoncodehk** [comment] 2024-03-22 00:32
Duplicate of microsoft/TypeScript/issues/57631

**Closed** 2024-03-25 08:12 UTC
