### ISSUE TITLE
snippets show 'undefined' in suggestion details

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2101] opened 2016-01-19 09:52 UTC
![screen shot 2016-01-19 at 10 51 33](https://cloud.githubusercontent.com/assets/1794099/12415214/b40f7a86-be9a-11e5-87c8-e89045937974.png)

**Comment by joaomoreno** [comment] 2016-01-19 09:56
Duplicate of #1969

**Closed by joaomoreno** 2016-01-19 09:56 UTC
Labels: bug
