### ISSUE TITLE
Inline chat does not expand sufficiently to show new lines

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#221598] opened 2024-07-12 19:07 UTC
Type the following in inline chat:

```
foo

bar

baz
```

Notice the bad behavior when typing the last line

https://github.com/user-attachments/assets/0256dbc9-654f-4807-83d0-8e41226ff77d

**Comment by jrieken** [comment] 2024-08-08 07:18
dupe of https://github.com/microsoft/vscode/issues/216843 but this should be fixed by having sticky scroll disabled

**Closed by jrieken** 2024-08-08 07:18 UTC
