### ISSUE TITLE
Indent guide disappears

### ISSUE THREAD

**Issue by anticitizen4** [Microsoft/vscode#49694] opened 2018-05-11 12:43 UTC
By indent guide I mean that line that indicates enslosing block.

- Version 1.23.0 (1.23.0)
- macOS 10.13.4

Have a block longer then screen height. Put cursor deep down. Scroll up until cursor is hidden. Indent guide remains, no problem here. Now place cursor at the top, scroll down until cursor is out of view. Now it disappears.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cristi-neagu** [comment] 2018-05-11 13:33
I can confirm this issue. I'm on version 1.23.1, on Windows 7.

**Comment by usernamehw** [comment] 2018-05-13 17:52
Duplicate of #49173

**Closed** 2018-05-14 10:55 UTC
Labels: *duplicate
