### ISSUE TITLE
Bug of Intellisense with JavaScript

### ISSUE THREAD

**Issue by abc1236762** [Microsoft/vscode#17339] opened 2016-12-15 19:04 UTC
- VSCode Version: 1.8.0
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Create a project folder and create `func.js`, `main.js`, and `jsconfig.json` in it.

`jsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "file": [
        "func.js"
    ]
}
```
`func.js`:
```javascript
function Test() {
    // ...
}
// ...
Test.a = function() {
    // ...
    var k = require('n');
    // ...
    return 0;
};
// ...
Test.prototype.b = function() {
    // ...
    var k = require('n');
    // ...
    return 1;
};
```
`main.js`:
```javascript
Test.a();
var test = new Test();
test.b();
```
2. Open main.js, and move mouse on `Test` or `a()` at line 1, the ToolTip shows `any`, move mouse on any words, the ToolTip shows the sentence that have `any`. Also autocomplete do not show `a` when I type `Test.` and `b` when I type `test.`.

3. Edit `func.js`, make lines which has `require` as comment, like :
```javascript
function Test() {
    // ...
}
// ...
Test.a = function() {
    // ...
    //var k = require('n');
    // ...
    return 0;
};
// ...
Test.prototype.b = function() {
    // ...
    //var k = require('n');
    // ...
    return 1;
};
```
4. Open main.js, and move mouse on `Test` at line 1 and line 2, the ToolTip shows `function Test(): void`, but move mouse on  `a()` at line 1, the ToolTip still shows `any`, move mouse on any words at line 2 and line 3, the ToolTip shows the sentence that haven't `any`. For example, `test` shows
```javascript
var test: {
    b: () => number;
}
```
5. Output `Test.a()` can get `0`, `test.b()` can get `1`. At Step 4, Visual Studio Code found the definition of `test.b()` as `Test.prototype.b` (move mouse on `b()` at line 3 and the ToolTip shows `(property) Test.b: () => number`), but not found the definition of `Test.a()` because move mouse on `a()` at line 1 and the ToolTip shows `any`. Also autocomplete show `b` when I type `test.`, but not show `a` when I type `Test.`.

Conclusion:
If the definition of the method or prototype of function in JavaScript have method `require()` in it, Intellisense in Visual Studio Code cannot find the definition of "that function, the prototype of that function, and the method of that function" at another JS file.
If the definition of the method or prototype of function in JavaScript do not have method `require()` in it, Intellisense in Visual Studio Code can find the definition of "that function, and the prototype of that function" at another JS file, but still cannot find the definition of method of that function at another JS file.

**Comment by mjbvz** [comment] 2016-12-15 19:22
Quick question: is `"main.js"` listed in the `"files"` section of the `jsconfig.json`?

**Comment by abc1236762** [comment] 2016-12-15 21:56
All problem still exist when `"main.js"` listed in the `"files"` section of the `jsconfig.json`.Also all problem still exist when `"files"` section has nothing.

**Comment by waderyan** [comment] 2016-12-16 18:55
I have reproduced this and it looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7046

@mjbvz can you look at the issue I posted and confirm if you think it is a duplicate?

**Comment by abc1236762** [comment] 2016-12-17 04:57
So method `require()` can impact on Intellisense work or not is a bug?

**Comment by mjbvz** [comment] 2016-12-19 21:57
@waderyan No, I think this is a different issue. You see the same using classes:

```js
class Test {
    foo() {
        var k = require('fs');
        return 1;
    }
}
```

```
var x = new Test();
// Type of `x` is any. If you remove the `require`, the type becomes `Test`.
```

From debugging, this looks like a TS issue. I'll move this issue over to them for tracking.

**Comment by mjbvz** [comment] 2016-12-19 21:59
This issue was moved to Microsoft/TypeScript#13033

**Closed by mjbvz** 2016-12-19 21:59 UTC
Labels: duplicate, intellisense, javascript
