### ISSUE TITLE
[JS] Syntax bug (Light+ theme) ?

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#2960] opened 2016-02-12 09:53 UTC
While editing a JS file, I noticed some problem that only happens with Light+ theme:

![themebug](https://cloud.githubusercontent.com/assets/199648/13003588/af167ac2-d176-11e5-875c-cd2c44bef945.jpg)

**Comment by warpdesign** [comment] 2016-02-12 10:03
I forgot to mention: it happens in 0.10.8-insiders as well as 0.10.8.

**Comment by SDemonUA** [comment] 2016-02-12 14:00
It affects all color schemes.
It happens after any < or > sign that not divided on left side with a space i.e. if you will write "i < some.length" there will be no problems.

**Comment by aeschli** [comment] 2016-02-12 16:18
@warpdesign Can you scroll up and find the first occurrence where things get the turquoise color?
Could be the < or > as @SDemonUA says, or the use of a keyword as a function name.

**Comment by warpdesign** [comment] 2016-02-12 16:46
@aeschli I checked and it's `j<datas` that triggers the bug. Writing `j < datas` instead fixes the problem.

Is this being worked on ?

**Comment by aeschli** [comment] 2016-02-12 20:01
Then it's a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11.
This has been reported several times so it got a lot of attention. I'm not sure what's the state, if it's hard to fix or how close we are with a fix. Feel free to comment in the issue.

**Closed by aeschli** 2016-02-12 20:01 UTC
