### ISSUE TITLE
Save Participants disables linting and takes forever to run.

### ISSUE THREAD

**Issue by ShaneSchroll** [microsoft/vscode#88149] opened 2020-01-06 17:29 UTC
This recently started showing up. Whenever I save a Twig file, a new process "Running Save Participants..." shows up at the bottom and takes 5+ seconds to run even on a Twig file with nothing in it. Then, after saving once, all linting, auto close tags, etc no longer work until I quit and reopen VSCode  - which obviously makes this unusable.

The linting breaks for all files, not just twig as soon a save is performed.
All "hovers" are broken, just stops at "loading.." when hovering for code info.

'Format on Save' is off in settings.
'Code Actions on Save' is off in settings.
'TimeOut for save participants' is 0 (settings say to use 0 to disable...)
Setting PHP to lint onType makes the process take 20+ seconds to save a file.

All extensions disabled - does the same thing, breaks all linting and takes forever to save.

I'm not sure when this was introduced, but the problem started when I updated to the December version a couple days ago and i'm looking into a way to rollback as VSCode is completely unusable in this state.

A reinstall did not solve the issue.
OS: MacOS Mojave

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment] 2020-01-06 22:27
Are you sure this reproduces with all extensions disabled? VS Code should not do anything to twig files by default

**Comment by ShaneSchroll** [comment] 2020-01-07 15:26
After more looking I had 1 hidden extension I missed. It is "Twig Language 2" by mblode. However, it has happened before with the other 2 Twig language packs in the extension library (one again by mblode, and the other by whatwedo). The issue seemingly disappeared again, though it has happened multiple times before. I'm not sure if there are certain circumstances when VSCode starts that it just doesn't load something properly. I can say that it has always been Twig files that present this issue (for me). Though usually a restart of VSCode resolves the issue. It's just odd that it crops up every now and again. This time it did not resolve after quitting and restarting multiple times, so I thought this time something might actually be broken.

To add further context, when the "Save participants" was running, it took about 5 mins for linting to start working again, which seems odd that this process requires that many resources that linting is "broken" for a few minutes (all languages). Is there maybe a conflict with the regular PHP server that is causing issues when using Twig - I don't think this is the case, but maybe there is a conflict. I do know that lintOnType being true in the settings made the save process take much longer.

**Comment by mjbvz** [comment] 2020-01-11 01:55
I'm closing this as caused by extension. Please follow with those extensions upstream

**Closed by mjbvz** 2020-01-11 01:55 UTC
Labels: needs more info

**Comment by Manubi** [comment] 2020-02-14 19:09
I have the same problem in a typescript file. How can I find out which extension is causing the problem?

**Comment by revelt** [comment] 2020-02-17 10:57
I've seen this issue raised many times already, it seems mixed-source code is causing this; linting or other processing plugin fails and "Save participants" drags on.

@mjbvz this bug needs to be tended on VSC side, you can't delegate to plugin maintainers forever; there are [29 closed issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+%22Save+Participants%22) with "Save participants", this bug does not happen on other code editors.

**Comment by mascardoso** [comment] 2020-02-18 11:04
I agree with @revelt 
This just keeps dragging and dragging and furthermore vscode is starting to feel glitchy for me specially when a feature like saving should just instant.

**Comment by mjbvz** [comment] 2020-02-18 16:10
@revelt So do you see this issue with all your installed extensions disabled?

**Comment by revelt** [comment] 2020-02-18 16:24
@mjbvz Thank you for following up. The bug is very sneaky, it seems it occurs only on mixed syntax code, specifically where language is not recognised. Shane (original poster) was using Twig, I was using Nunjucks in the morning, switching between Jinja and HTML syntaxes. That's when IDE freaked out with "Save Participants" bug. But then later, I went to work and been coding React/JSX happily all day today, no problems, "Save Participants" popup didn't appear, I was even switching between different React projects.

I'll try to recreate the bug. It's sneaky and I suspect syntax parsers break in mixed sources code.

**Comment by ShaneSchroll** [comment] 2020-02-18 19:40
@revelt @mjbvz  This is the case for me as well: mixed syntax code causes the issue. But, as Roy pointed out, it appears randomly. I've worked all day with twig/html and even react/jsx with no issues. Then other days it starts on the first save in a mixed syntax file.

I do have 'files.associations' pointing html to twig and vice-versa, which allows me to set the language as HTML, and keep twig parsing/linting/colorization, even though it is recognized as just html. The issue is still present even though it is no longer labelled as a "HTML (Twig)" file.

**Comment by mjbvz** [comment] 2020-02-18 21:49
What you expect VS Code to do here? From everything described so far, the linter extensions you have installed cause this problem and you can't expect VS Code to work around their bugs

So please file an issue against these extensions. Then, if the extension maintainers feel there is some underlying VS Code issue, they can always follow up with us

**Comment by AlexReff** [comment] 2020-02-21 23:11
I just started running into this issue, and in my case it appears as though it was due to having "source.fixAll": true" set in "editor.codeActionsOnSave" which was hanging in typescriptreact files (.tsx)

I don't think it's necessarily VSCode's responsibility to "fix the issue" if it's coming from extensions/linters, but having some way of identifying the underlying culprit would be helpful. I was unable to find any details about how to identify _what_ is actually hanging or being slow. This is the most recent discussion on the topic. Would you be able to provide instructions here, or a link, on how a user can dig into this? If people are easily able to identify the culprit themselves, that would help cut down on people opening issues for VSCode.
