### ISSUE TITLE
Incorrect terminal on open

### ISSUE THREAD

**Issue by Madpeterz** [microsoft/vscode#133034] opened 2021-09-13 21:03 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0 (user setup)
- OS Version: Windows 10 Pro + 21H1 + Feature Experience Pack 120.2212.3530.0

Steps to Reproduce:

1. Open vscode

Details:
When you open VScode the default terminal is opening as powershell and not the selected default (in my case cmd)
if  you select Terminal -> New terminal  cmd opens.
if you close the power shell terminal leaving only cmd and restart VScode powershell returns.
View -> Command palette -> Terminal: Select default profile does not correct this.
setting: "terminal.external.windowsExec" is set to "C:\\Windows\\System32\\cmd.exe"

**Comment by IllusionMH** [comment] 2021-09-13 21:15
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 21:16 UTC
Labels: *duplicate
