### ISSUE TITLE
Possible to support variables in settings.json?

### ISSUE THREAD

**Issue by tristan957-expero** [Microsoft/vscode#43351] opened 2018-02-09 20:52 UTC
- VSCode Version: 1.20
- OS Version: MacOS 10.13

Would it be possible to have variable support in the `settings.json` file.

An example of when this could be used:
A popular Java extension is called Lombok. To use Lombok with the Red Hat Java Extension, you have to change some arguments for language server. 2 of those arguments are full paths to the `lombok.jar` that Maven (Java build system). I work on a Linux machine and a MacOS machine. Maven stores downloaded JARs to `~/.m2`. On Linux `~` expands to `/home/username`, while on MacOS it expands to `/Users/user.name`. Now if I could use an environment variable in the `settings.json` file, I could keep the setting platform agnostic in the form of `${env:HOME}/.m2/path/to/lombok.jar`

**Comment by sandy081** [comment] 2018-02-13 11:08
Duplicate of #2809

**Closed** 2018-02-13 11:09 UTC
Labels: *duplicate, config
