### ISSUE TITLE
VSCode requires CXXABI 1.3.9 which is not available in CentOS 7

### ISSUE THREAD

**Issue by jheaff1** [microsoft/vscode#115851] opened 2021-02-05 10:20 UTC
- VSCode Version: 1.53.0
- OS Version: CentOS 7.9.2009. Kernel 3.10.0-1160.15.2.el7.x86_64

Steps to Reproduce:

1. Launch VSCode
2. Navigate to Terminal->New Terminal and the following error message appears:

```
The terminal process failed to launch: A native exception occurred during launch (/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node)).
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2021-02-05 10:25
This is mentioned in the changelog: https://code.visualstudio.com/updates/v1_53#_electron-11-update

**Comment by gjsjohnmurray** [comment] 2021-02-05 10:26
Thanks @yume-chan

/duplicate of #115784

**Closed** 2021-02-05 10:26 UTC
Labels: *duplicate, new release

**Comment by mimoralea** [comment] 2021-02-18 00:56
For those trying to get going:

`sudo yum downgrade code`

I had to downgrade until 1.52.1.

**Comment by jheaff1** [comment] 2021-02-18 07:50
I followed the instructions given here https://github.com/microsoft/vscode/issues/115784#issuecomment-776602788 and can run new versions of VSCode on CentOS 7 with no issues
