### ISSUE TITLE
Add SCM actions into explorer panel context menu

### ISSUE THREAD

**Issue by Ash258** [Microsoft/vscode#40844] opened 2017-12-26 19:16 UTC
It would be nice to have SCM context options on folder/file? (Like other editors/IDEs have).

![Example IntelliJ](https://image.prntscr.com/image/ZQXPCrg2SJ__swgFlhH-Vw.png "Example")

If you go through lots of changes its pain to scroll in GIT panel and select files. We cannot select just folder or filter in GIT panel.

![Archive and refactoring of repo](https://image.prntscr.com/image/y00o1BCMTZ2eb6pZfVvMSw.png "Archive and refactoring of repo")

It would be much easier if you can just right click folder in explorer panel and add it to stage.

**Comment by joaomoreno** [comment] 2018-01-08 10:01
Since your pain point is rather related to UX around the SCM panel, I'll close this as a duplicate of https://github.com/Microsoft/vscode/issues/14582

**Closed by joaomoreno** 2018-01-08 10:01 UTC
