### ISSUE TITLE
"New folder" doesn't focus input box after right click. Have to do it twice.

### ISSUE THREAD

**Issue by frumbert** [microsoft/vscode#143586] opened 2022-02-22 04:51 UTC
Does this issue occur when all extensions are disabled?: **Yes**/No

Previous issues of this appear closed but the bug still exists.

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:56.651Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
macos 11.6.4 (20G417), M1

Steps to Reproduce:

1. Do this on MAC OS
2. Have a workspace open.
3. Click off VS Code
4. Right click a folder in the explorer and choose new folder
5. Start typing - NOTHING
6. Click on VSCODE with the left mouse button
7. right click a folder in the explorer and choose new folder
8. Start typing - It Works!

**Comment by JacksonKearl** [comment] 2022-03-02 03:36
Duplicate of #143968.

**Closed** 2022-03-02 03:37 UTC
Labels: *duplicate
