### ISSUE TITLE
Crash when `Reveal in Explorer `

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#129047] opened 2021-07-20 11:53 UTC
Does this issue occur when all extensions are disabled?: Yes/No

both of stable and insider
```
版本: 1.58.2 (system setup)
提交: c3f126316369cd610563c75b1b1725e0679adfb3
日期: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.14393
```
```
版本: 1.59.0-insider (system setup)
提交: b805d2e94937976bb17d0439f57fcd3a9d423c31
日期: 2021-07-20T05:12:47.598Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.14393
```

Steps to Reproduce:

1.Reveal in Explorer
2.crash

**Comment by isidorn** [comment] 2021-07-26 13:19
I can not reproduce this issue. Can you please attach a video showing the problem?

**Comment by heartacker** [comment] 2021-07-27 02:07
> I can not reproduce this issue. Can you please attach a video showing the problem?

sometime it occur，and some time not

**Comment by isidorn** [comment] 2021-07-27 09:32
Then closing this since no good repro steps and nobody else is hitting this issue.
Sorry! But without good repro steps there is nothing we can do here

**Closed by isidorn** 2021-07-27 09:32 UTC
Labels: file-explorer, needs more info
