### ISSUE TITLE
Add options for positioning tool tips 

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#53496] opened 2018-07-03 17:34 UTC
I feel that tool tips in VS Code are hiding important information.

I rather find myself hitting &lt;ESC&gt; than actually reading a tool tip because the tool tip is constantly hiding information from a previous line which I need to refer to in order to complete my current line of code:
<br/>

![vs code tooltip](https://user-images.githubusercontent.com/9283914/42234673-92a58a34-7ef5-11e8-8748-e4f6d22aff0f.png)

<br/>
Can you please add options to have tool tips preferably displayed ...

- _below_ the current line
- with a custom x and y offset

NB: x and y offset values may be given in CSS "em" units.
<br/>

So for example, corresponding configuration settings might look like:
```
{  // Determines tool tip position, relative to current caret. Either "left" or "right" (default).
  editor.toolTip.xPosition: "left"

  // Determines tool tip position, relative to current caret. Either "above" (default) or "below".
,  editor.toolTip.yPosition: "below"

  // Tool tip frame's horizontal margin in regard to current caret position (in CSS "em" unit).
, editor.toolTip.xOffset: 2 

  // Tool tip frame's vertical margin in regard to current caret position (in CSS "em" unit).
, editor.toolTip.yOffset: .5 

}
```

If an editor's viewport doesn't provide enough space to show the tool tip at the desired position, the corresponding setting should (temporarily) be reversed for that tool tip, so it will fit the viewport again. (E.g. if there is not enough space below the current caret for showing the tooltip if `editor.toolTip.position: "below"`, then the tooltip should be displayed using `editor.toolTip.position: "above"`).

**Comment by jrieken** [comment] 2019-10-08 14:56
/duplicate of https://github.com/microsoft/vscode/issues/33752

**Closed** 2019-10-08 14:56 UTC
Labels: *duplicate, editor-parameter-hints, feature-request, ux
