### ISSUE TITLE
Download Broken?

### ISSUE THREAD

**Issue by kodaimaehata** [microsoft/vscode#74735] opened 2019-06-02 05:38 UTC
I called `npm install` at the root of extention folder and command exited with error code 1.

`
Detected VS Code engine version: ^1.26.0
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sf-cicd-config@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sf-cicd-config@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

Error happend at postinstall and it seems that the url below returns Internal Server Error.

https://vscode-update.azurewebsites.net/api/releases/stable

The link is broken or has temporary issue?

**Comment by justClouds** [comment] 2019-06-02 06:19
Possible duplicate of [#74732](https://github.com/microsoft/vscode/issues/74732) and [#74734](https://github.com/microsoft/vscode/issues/74734) and [#74737](https://github.com/microsoft/vscode/issues/74737).
Looks like there is a 'system wide' outage of all systems serving VS Code install/update.

**Closed** 2019-06-03 07:17 UTC
Labels: *duplicate
