### ISSUE TITLE
Unable to paste filenames from Finder

### ISSUE THREAD

**Issue by enricospada** [microsoft/vscode#146770] opened 2022-04-04 21:09 UTC
Issue Type: <b>Bug</b>

1 - select a file in Finder
2 - copy the item 
3 - paste the item in VSCode

expected result: the filename alone is pasted at the cursor
actual result: nothing is pasted (no response at all)

I can right-click and press OPT to "Copy as pathname", and that bit of text will paste just fine in VSCode. But up until last week I seemed to be able to just copy and paste the filename successfully. 

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 198fce6b-e4ee-44a7-ba81-090ccad03384|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
html-entities|chr|1.1.2
vscode-quick-select|dba|0.2.9
githistory|don|0.6.19
gitlens|eam|12.0.5
permute-lines|ear|1.1.0
vscode-commands|fab|1.4.3
auto-close-tag|for|0.5.14
beautify|Hoo|1.5.0
easy-snippet|inu|0.6.3
replace-curly-quotes|jin|1.1.0
vscode-gutter-preview|kis|0.30.0
diff-merge|mos|0.6.1
remote-repositories|ms-|0.4.0
gremlins|nho|0.26.0
material-product-icons|PKi|1.2.0
partial-diff|ryu|1.4.3
vscode-fileutils|sle|3.5.0
open-in-browser|tec|2.0.0
html-validate-vscode|Tob|0.2.0
vscode-status-bar-format-toggle|tom|3.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment] 2022-04-05 20:03
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by enricospada** [comment] 2022-04-05 22:06
Yes, this reproduces for me with the latest insiders build and all extensions disabled.

**Comment by bpasero** [comment] 2022-04-06 05:27
I would argue this is in the camp of "drag and drop", typically copy/paste is the accessible variant of the mouse-DND gesture. Moving to editor land.

**Comment by bpasero** [comment] 2022-04-06 05:34
I wonder if https://github.com/microsoft/vscode/issues/146867 is related and this is a recent regression.

**Comment by deepak1556** [comment] 2022-04-08 12:11
Only chromium change that went between 91 and 98 wrt to clipboard commands was https://chromium-review.googlesource.com/c/chromium/src/+/2927390 , do we use [EditContext](https://github.com/w3c/editing/blob/gh-pages/docs/EditContext/explainer.md) for our editor ?

**Comment by EvanBrownVTM** [comment] 2022-04-12 16:23
same issue

**Comment by hediet** [comment] 2022-04-13 06:49
> do we use EditContext for our editor ?

We don't. I'm not aware of any changes in this area. @alexdima, do you know something?

**Comment by communque** [comment] 2022-04-21 03:47
Any progress?  Copy-and-paste from Finder files to file names in the VS Code is a great feature.  Was using it every day... until it stopped working recently :(

**Comment by tb-jacob** [comment] 2022-04-25 19:13
Same issue.

**Comment by alexdima** [comment] 2022-04-26 07:21
After running `vscode-bisect`, it looks like this started in this range: https://github.com/microsoft/vscode/compare/f8c36556a2c305327f5417dc7f93220f39ed608f...2d8e93571421d69616e0ed7d7958e32abaf8d7d3

**Comment by joshuaiz** [comment] 2022-04-27 05:00
@tb-jacob I have the same workaround except using the Scrap Paper app for macOS. Copy to Scrap Paper, then copy to VS Code.

This is a screenshot of my Scrap Paper...it is all files I'm trying to paste into VS Code. If you mount React micro-apps to another app like me I am doing this like 18 times per day. Cool.

<img width="238" alt="CleanShot 2022-04-26 at 23 58 36@2x" src="https://user-images.githubusercontent.com/1096738/165443834-917d9e69-ac4e-414c-87b5-d0ef8fdaf9e5.png">

**Closed** 2022-04-27 21:10 UTC
Labels: bug, confirmed, regression, chromium, electron-17-update

**Comment by communque** [comment] 2022-05-25 14:22
On MacOS the new update completely fixes the issue!!
@PhilippeNguyen if you're on Mac and you want to copy/paste one or more full file paths from Finder, select one or more items, right-click for context menu, hold option button, choose "Copy 34 items as pathnames" then paste... actually anywhere.

**Comment by rayzinnz** [comment] 2022-05-26 02:57
> new update partially fixes, in that I can now paste the file/folder name. However, previously I could paste the entire absolute path

I have exactly the same problem on linux - partial fix. Has there been a new Issue # registered to get it fixed?
