### ISSUE TITLE
crashed after reload window

### ISSUE THREAD

**Issue by looading** [microsoft/vscode#132236] opened 2021-09-03 09:53 UTC
Issue Type: <b>Bug</b>

crashed after reload window

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 11, 10|
|Memory (System)|32.00GB (7.00GB free)|
|Process Argv|--crash-reporter-id 0610b461-2305-4ca6-8143-282cbe2a8db3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
npm-intellisense|chr|1.4.0
vscode-css-modules|cli|0.3.2
vscode-eslint|dba|2.1.23
vscode-dash|dee|2.4.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
coder|egr|0.1.233
prettier-vscode|esb|8.1.0
plantuml|jeb|2.15.1
vscode-mdx|Jou|0.2.3
vscode-styled-components|jpo|1.6.6
Kotlin|mat|1.7.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-next|ms-|4.5.20210902
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
vscode-jest|Ort|4.1.1
minapp-vscode|qiu|2.3.4
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
rust|rus|0.7.8
code-spell-checker|str|2.0.3
open-in-browser|tec|2.0.0
vscode-counter|uct|2.3.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0
vscode-import-cost|wix|2.15.0
vscode-caddyfile-syntax|zam|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedt:30351793
vsdyn321cf:30356811
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by jonwhittlestone** [comment] 2021-09-03 10:57
+1

**Comment by gjsjohnmurray** [comment] 2021-09-03 11:12
You haven't given much detail of the crash, but maybe #132238 applies?

**Comment by jonwhittlestone** [comment] 2021-09-03 15:38
it was indeed that, thanks.

**Comment by TylerLeonhardt** [comment] 2021-09-03 23:08
closing as duplicate of #132238

**Closed by TylerLeonhardt** 2021-09-03 23:08 UTC
Labels: new release
