### ISSUE TITLE
a bug with "Dvorak - QWERTY ⌘" layout

### ISSUE THREAD

**Issue by viosey** [Microsoft/vscode#26619] opened 2017-05-14 08:26 UTC
- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: macOS 10.12.4 (Sierra)

Steps to Reproduce:

1. add a `Dvorak - QWERTY ⌘` keyboard layout
2. press `⌘ + any-key` , It's still using Dvorak not QWERTY
>e.g.
press `⌘J`, it should be `⌘C`, but in vscode, it is still `⌘J`

**Comment by alexandrudima** [comment] 2017-05-15 14:29
@viosey for the Dvorak - QWERTY ⌘ keyboard layout we now default to dispatching on `keyCode`. We recognise the keyboard layout via the id `com.apple.keylayout.DVORAK-QWERTYCMD`.

Can you please open an editor, then run `F1 > Developer: Inspect key mappings`, save the output to a file and attach it here?

**Comment by viosey** [comment] 2017-05-15 17:00
I restart vscode, and it became normal, seems the bug will not reproduce every time.
The attach file is normal one, if this bug reproduces again, I will post it again.
[key-mapping.txt](https://github.com/Microsoft/vscode/files/1001784/key-mapping.txt)

**Comment by alexandrudima** [comment] 2017-05-15 17:18
:+1: - closing for now - please reopen if you find reproducible steps.

**Closed by alexandrudima** 2017-05-15 17:18 UTC
Labels: keyboard-layout, mac

**Comment by viosey** [comment] 2017-05-16 05:55
I found the reproducible steps.
1. Install this [Chinese pinyin Input](http://pinyin.sogou.com/mac/introduce.php)
2. Use `Dvorak - QWERTY ⌘` layout.
![](http://ww2.sinaimg.cn/large/006tNbRwgy1ffn5t1dseqj30e00ep75c.jpg)
3. And open vscode

The following is the error key-mapping
[key-mapping.txt](https://github.com/Microsoft/vscode/files/1003313/key-mapping.txt)

**Comment by alexandrudima** [comment] 2017-05-16 16:42
@viosey 

It appears this keyboard layout always identifies itself as `com.sogou.inputmethod.sogou.pinyin` (from your attached file), even when you have selected QWERTY ⌘ in the above dialog. In other words, we cannot detect when the input method is switched to QWERTY ⌘, as it just reports the same identifier.

You can workaround by using `"keyboard.dispatch": "keyCode"` and restarting VS Code in your settings. I don't believe there is any code change we can do on our side to detect when the input method is switched, since it reports the same identifier.

**Comment by viosey** [comment] 2017-05-17 06:49
Thanks!
`"keyboard.dispatch": "keyCode"` is work!
