### ISSUE TITLE
Extend/Shrink Selection Scope

### ISSUE THREAD

**Issue by Maxhodges** [Microsoft/vscode#32069] opened 2017-08-06 18:53 UTC
Users shall be able to successively select expanding logical blocks of code so that you can easily select any expression in the code by placing the caret somewhere inside it and pressing a shortcut.

Extends selection to the next containing node (for example, an expression, a paired tag, an entire conditional block, a method body, a class, a group of vararg arguments, etc.)

In plain text, with the caret anywhere in a word, the selection would extend to to the word, the sentence, the paragraph

Shrink does the opposite.

Examples

![ext1](https://user-images.githubusercontent.com/957271/29006090-f158a6be-7b23-11e7-9b52-f67ce1d57c4b.gif)
![ext2](https://user-images.githubusercontent.com/957271/29006092-f2e4302a-7b23-11e7-95ee-38ab89ac6f7a.gif)
![ext3](https://user-images.githubusercontent.com/957271/29006095-f4c3089e-7b23-11e7-8c08-661b1362d54f.gif)

**Comment by Maxhodges** [comment] 2017-08-06 19:05
multiple cursors? no problem!

![ext4](https://user-images.githubusercontent.com/957271/29006172-a5a46832-7b25-11e7-9b6a-5943da827bfb.gif)

**Comment by jrieken** [comment] 2017-10-26 09:48
dupe of #4795

**Closed by jrieken** 2017-10-26 09:48 UTC
Labels: duplicate, editor, editor-contrib, feature-request
