### ISSUE TITLE
Test: Improve automated issue management

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35003] opened 2017-09-26 00:03 UTC
Testing #32238

Complexity 2

- [x] Any OS: @bpasero 
- [ ] Any OS: @ramya-rao-a 

In one of our satellite repos or a personal repo:
- Make sure the VSCode bot is installed (Repo Settings > Integrations & Services)
- Configure automatic assignment by checking in a file `.github/assignment.yml` with:
```
{
    perform: true,
    assignees: [ yourgithubid ]
}
```
  - Verify new issues are automatically assigned to the listed (comma separated) GitHub accounts.
  - Verify that if you assign a new issue to someone before submitting it, no automatic assignment is done.

In our main repo, configure multiple assignees (e.g., for workbench) in: https://github.com/Microsoft/vscode/blob/master/.github/classifier.yml
- Verify only one of these assignees is assigned for that label and it is randomly picked.

Assigning @bpasero because he specifically asked for the random assignment and the classifier is really only operational on our main repo at this time.

**Comment by bpasero** [comment] 2017-09-26 07:46
I added @sandy081 and @isidorn with me to workbench, let's see how that turns out.

**Comment by ramya-rao-a** [comment] 2017-09-26 21:09
I can confirm that the workbench labelled issues are now being assigned to either @bpasero @isidorn or @sandy081

**Closed by ramya-rao-a** 2017-09-26 21:09 UTC
Labels: testplan-item
