### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by anayak-alphasense** [microsoft/vscode#74992] opened 2019-06-06 14:32 UTC
VS code is using very high CPU.
Issue Type: <b>Performance Issue</b>

Why VS code is using very high CPU Usage. 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   10	    74	 13196	code main
    1	    68	  4524	   window (Issue Reporter)
    0	    55	 12100	   shared-process
    0	   456	 12568	   gpu-process
    0	   255	 12632	   window (RSSFilterContent.tsx - frontend - Visual Studio Code)
    0	    47	 10524	     searchService
    0	    13	 10904	     watcherService 
    0	     5	 10928	       console-window-host (Windows internal process)
    0	   124	 11672	     extensionHost
    0	  1378	 11888	       electron_node tsserver.js 
    0	    19	  7668	         electron_node typingsInstaller.js typesMap.js 
    0	    22	 13680	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11672
    0	    11	 13192	     electron-crash-reporter
    0	     8	 13664	     winpty-process
    0	     9	 13724	       console-window-host (Windows internal process)
    0	     4	 13776	       C:\Windows\System32\cmd.exe
    0	    35	  6864	         "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" run build-dev
    0	     4	  1844	           electron_node config.js config.js 
    0	   417	  2564	             node   "C:\Users\AshishNa\Documents\AlphaSense\frontend\node_modules\.bin\\..\webpack\bin\webpack.js" --colors --config w/devapp.config.js
   37	   694	 13720	               "C:\Program Files\nodejs\node.exe" --max-old-space-size=2048 C:\Users\AshishNa\Documents\AlphaSense\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\service.js
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (RSSFilterContent.tsx - frontend - Visual Studio Code)
|    Folder (frontend): 3120 files
|      File types: svg(1014) ts(815) tsx(545) png(309) scss(172) js(41)
|                  woff(32) woff2(28) gif(25) psd(21)
|      Conf files: tslint.json(3) package.json(2) tsconfig.json(1) gulp.js(1);
```

</details>
Extensions: none

**Comment by egamma** [comment] 2019-06-07 08:38
Can you reproduce this in version 1.35?

**Comment by anayak-alphasense** [comment] 2019-06-07 12:48
@egamma  No I haven't tried in 1.35 But its using very high CPU in 1.34. So do you want me to update it to 1.35 ?

**Comment by hanneswidrig** [comment] 2019-06-07 13:13
@anayak-alphasense Performance issues got significantly better with the upgrade to TypeScript 3.5.x. VSCode's performance has improved immensely with the latest stable release.

**Comment by egamma** [comment] 2019-06-07 16:42
@anayak-alphasense yes please update to 1.35 and report back whether you still see the same performance issue.

**Comment by whitecolor** [comment] 2019-06-08 11:17
I'm using the latest insiders 1.35, i'm actually quite tired of this problem.

**Comment by egamma** [comment] 2019-06-09 12:11
@whitecolor please follow these steps to help us narrow down the problem https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by zenoven** [comment] 2019-06-10 02:48
same issue in 1.35.0, the VSC just suddenly run into this issue, exit VSC, restart, write some code and suddenly it just fired again and again. 

in the 1.34 version I have the same issue too, it's really annoying.

**Comment by egamma** [comment] 2019-06-10 09:37
@zenoven please follow this guide for how you can help us to narrow down performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues.

**Comment by anayak-alphasense** [comment] 2019-06-10 13:51
@egamma - I have updated to 1.35, but still the same issue persist. Could you please help me here?

**Comment by whitecolor** [comment] 2019-06-10 14:02
@anayak-alphasense in your process info it seems some webpack thing `fork-ts-checker-webpack-plugin` eats CPU.

**Comment by cesaraaron** [comment] 2019-06-10 21:30
Same problem here.
1.35 and even in insiders 1.36 c089daa858f34631f5f827ff8a0313bf1e2ded6d

It appears to be a problem with the integrated typescript server
![Screen Shot 2019-06-10 at 3 28 03 PM](https://user-images.githubusercontent.com/20180899/59228250-999af200-8b94-11e9-8e49-35b92826ef1b.png)

**Comment by mjbvz** [comment] 2019-06-20 06:53
@cesaraaron Please open a separate issue

@anayak-alphasense In your example, the high cpu usage looks like it is coming from a process you are running in the terminal. Can you confirm this?

**Comment by anayak-alphasense** [comment] 2019-06-20 07:05
@mjbvz - Agree, But the same code is running smooth in other systems, not sure exactly what is the issue with  my VS code.

**Comment by mjbvz** [comment] 2019-06-20 07:08
So if you run the exact same command line script from a terminal outside of VS Code—with the same working directory and environment as you use inside of VS Code—you don't see this issue?

**Comment by anayak-alphasense** [comment] 2019-06-20 07:27
Exactly, I tried running it via Got bash it worked smooth. Not sure if below screenshot can help you to find the issue
![tee](https://user-images.githubusercontent.com/46563185/59829371-e8961380-935a-11e9-893b-f0dbf5c18771.PNG)
![ttt](https://user-images.githubusercontent.com/46563185/59829382-edf35e00-935a-11e9-85de-eefb00467d71.PNG)

**Comment by mjbvz** [comment] 2019-06-20 17:31
@Tyriar can confirm but there isn't really much a cpu usage difference between your two examples, assuming those node processes are what you are running

**Comment by marques-p44** [comment] 2019-06-20 19:19
I'm also having an issue with typechecking and high CPU usage. It takes about 4 seconds for a typecheck to complete and show me an error, and the CPU for tsserver shoots up to 300% during that 4 seconds. I've disabled all extensions, even tried Insiders, still same issue. Here's a CPU profile:
[MCPU-20190620T190450.198Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/3311799/MCPU-20190620T190450.198Z.cpuprofile.txt)

**Comment by marques-p44** [comment] 2019-06-20 19:30
Ok, I think the issue has to do with my TS project. If I just use CRA to make a basic app, typescript is nice and fast again. I'm even using the same tsconfig.json file in the basic app, but no problems at all.

**Comment by mjbvz** [comment] 2019-06-21 21:54
@marques-p44 Please open a separate issue

**Comment by mjbvz** [comment] 2019-07-02 23:00
Closing more info is needed from the original poster to determine if this is actually an issue with VS Code

**Closed by mjbvz** 2019-07-02 23:00 UTC
Labels: needs more info, perf
