### ISSUE TITLE
Image file can not preview

### ISSUE THREAD

**Issue by zjhiphop** [microsoft/vscode#98306] opened 2020-05-21 08:08 UTC
Issue Type: <b>Bug</b>

Click any images inside project,  the image can not open and preview and directly focus to current file tab.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.7.0
flow-for-vscode|flo|1.5.0
vscode-codeql|Git|1.2.0
vscode-test-explorer|hbe|2.18.1
vscode-drawio|hed|0.4.0
vscode-docker|ms-|1.2.0
mssql|ms-|1.9.0
Go|ms-|0.14.2
vetur|oct|0.24.0
typescript-hero|rbb|3.0.0
vscode-leetcode|she|0.16.2
mdx|sil|0.1.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by leimao** [comment] 2020-05-25 03:41
This happens in Linux VS Code as well. We could not preview images in MarkDown in VS Code.

**Comment by mjbvz** [comment] 2020-05-26 22:01
@zjhiphop Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2020-06-02 03:45
@matt-deboer That's a duplicate of #98768 which should be fixed in the next insiders build

**Comment by mjbvz** [comment] 2020-06-02 03:46
Closing the original issue since it was reported on an outdated version of VS Code without enough information to investigate further

**Closed by mjbvz** 2020-06-02 03:46 UTC
Labels: needs more info
