### ISSUE TITLE
workspace.applyEdit doesn't work if file is opened from read-only file system provider

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#57032] opened 2018-08-22 17:21 UTC
Issue Type: <b>Bug</b>

If the file is open from a read-only file system provider (registered with ` vscode.workspace.registerFileSystemProvider(..., ..., { isReadonly: true } )`), `vscode.workspace.applyEdit` doesn't apply any edits to its buffer. It used to work in the previous version of insiders, and it works in the stable realease.

VS Code version: Code - Insiders 1.27.0-insider (e0a68266321d1518bc12428b71d80524461a275b, 2018-08-22T05:18:13.273Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (11.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.18.1
csharp|ms-|1.15.2

</details>

**Comment by jrieken** [comment] 2018-08-23 07:32
That actually makes sense to me... Since the files are readonly you cannot edit them. I believe an editor showing such files would also not be editable.

**Comment by isidorn** [comment] 2018-08-23 08:01
@IlyaBiryukov this also makes sense to me, I do not see what is the unexpected behavior here. If the file is read-only edits can not be applied to it. And yes the editor is not editable.
It used to work previously becuase this feature was not yet implemented https://github.com/Microsoft/vscode/issues/53257

**Comment by IlyaBiryukov** [comment] 2018-08-23 16:34
@isidorn the scenario we want to enable is a read-only collaboration session in Live Share, where the guest cannot make edits, but should be able to see edits done by the host. When the host makes edits, we propagate them to the guest and apply them with `vscode.workspace.applyEdit` to the document. 
If you prohibit this, how else can we update the files? 

@lostintangent FYI this will block read-only support in VSLS for vscode.

**Comment by IlyaBiryukov** [comment] 2018-08-23 16:42
Also, in #53257, I already pointed out that extension should be able to make edits to read-only file, and you agreed to that, what has changed since then?

> @IlyaBiryukov: About extension applying changes to a document opened from a read-only file system provider, *we do need that working*. The issue is the behavior of save. I think saving a document should just be disabled for read-only provider.

>> @bpasero commented on Jul 2
>> @IlyaBiryukov yeah good point, extensions still need to be able to make changes to the model in  case it updates. We could maybe change our model in a way that a readonly model never shows up as dirty to the user.

**Comment by IlyaBiryukov** [comment] 2018-08-23 16:56
One solution I see is, before applying edits, re-register the file system provider for the same scheme as not read-only, apply the changes, and then re-register the file system provider bask as read-only again. Though this approach looks very awkward and prone to races with other actions that would attempt to modify other files, like user editing.

**Comment by jrieken** [comment] 2018-08-24 07:07
> but should be able to see edits done by the host. When the host makes edits, we propagate them to the guest and apply them with vscode.workspace.applyEdit to the document.

Any reason you aren't using the [`FileSystemProvider#onDidChangeFile`](https://github.com/Microsoft/vscode/blob/c1126302de7261d7d2bf3ada2fbfda5cb881b244/src/vs/vscode.d.ts#L5361-L5366)-event for this?

**Comment by IlyaBiryukov** [comment] 2018-08-24 23:45
@jrieken What would you say about allowing `FileSystemProvider#onDidChangeFile` work with `WorkspaceEdit`? 
Then, instead of calling `vscode.workspace.applyEdit`, we'll make our file system provider raise `onDidChangeFile` with an instance of `WorkspaceEdit`, and you would apply it.
Will this design work for you?

cc @srivatsn, @grork

**Comment by isidorn** [comment] 2018-08-27 10:33
@IlyaBiryukov in order to unblock you for the following milestone I have reverted my change for #53257
So I will reopen that one and assign it to the next milestone.

As for the discussion on a possible solution for september let's continue here.

**Comment by jrieken** [comment] 2018-08-27 10:44
> Then, instead of calling vscode.workspace.applyEdit, we'll make our file system provider raise onDidChangeFile with an instance of WorkspaceEdit, and you would apply it.

Not sure. The file system provider is a few layers below that and talks plain bytes, no notion of text nor ranges etc.

> and customer experience hit (when the editor reloads the file due to changes, the cursor position and selection are lost; and if you wanted to maintain the cursor and selection,

The editor is (to some extend) smart when it comes to file change events for things it currently displays. There is some simple diff going and it tries to keep the view state stable but obviously it can not to magic.

The underlying problems seems to be different interpretations of *readonly*. For us it means a file can only be read and not be saved. Then, when a file cannot be saved we derive the fact that it cannot be edited. So, either we change that (not just short term but also long term) or we add more fine grain control, e.g. a file is readonly for entity X, but not for entity Y (honestly, something I'd like to avoid)

**Comment by IlyaBiryukov** [comment] 2018-08-27 23:29
@isidorn the issue still repros in Insiders 1.27.0-insider (3f8088b5c5f1d44b5e1af4a8e67448abbe66470e, 2018-08-27T07:36:47.732Z)

**Comment by isidorn** [comment] 2018-08-28 07:31
@IlyaBiryukov that build does not contain my revert, plese try again in todays insiders build. Thank you

**Comment by IlyaBiryukov** [comment] 2018-08-28 17:19
@isidorn today's insiders, 1.27.0, is good.

**Comment by jrieken** [comment] 2019-03-05 17:49
cc @legomushroom

**Closed** 2019-10-08 10:40 UTC
Labels: *out-of-scope, api, file-io, under-discussion
