### ISSUE TITLE
Provide a better amend commit experience

### ISSUE THREAD

**Issue by VazMike** [microsoft/vscode#115997] opened 2021-02-06 19:59 UTC
- VSCode Version: 1.54.0-insider
- OS Version: macOS Big Sur 11.2

Steps to Reproduce:

1. Go to SCM -> ... -> Commit -> Commit Staged/All (Amend)

<img width="694" alt="Screenshot 2021-02-06 at 22 49 43" src="https://user-images.githubusercontent.com/14861435/107128311-b63d7f00-68cd-11eb-8ae0-3e25aebecd85.png">

2. In earlier versions a prompt with a message of the last commit would show up and there you can change that message.
The prompt is missing now and there is no way to change the commit message using VS Code UI.

Does this issue occur when all extensions are disabled?: Yes

**Comment by VazMike** [comment] 2021-02-06 20:06
Bot hints me the #114204 issue the duplicate which is correct.
But that issue is closed and I'm still encountering the problem on the latest Insider version.

**Comment by yume-chan** [comment] 2021-02-07 02:15
> No quick-input anymore, we re-use the SCM input (which could have been hidden before this change).

_Originally posted by @eamodio in https://github.com/microsoft/vscode/issues/114204#issuecomment-769475341_

My understanding is that commit amend also reads message from the input box now (I tired and it did modify last commit message if I have something in the input box then commit amend), however that's not the best experience if I want to fix a typo in last commit message.

**Comment by VazMike** [comment] 2021-02-07 10:02
I agree, showing the last commit message was very convenient. And not only for fixing typos.
Recently I started using `prepare-commit-msg` git hook which appends issue number to the message (this makes commits visible in issues on GitHub).
Now every time I amend with VS Code UI the message appends extra references, e.g. after to 3 amend commits I'll get `fixing tests (\#123) (\#123) (\#123) (\#123)`.

Since SCM input is reused this issue is not a bug but a feature request. The feature is **view previous commit message**.

**Comment by eamodio** [comment] 2021-02-08 20:02
I hear you on this and would definitely like to improve the current amend experience. We will likely be doing some explorations in the next iteration (March).

**Comment by Sti2nd** [comment] 2021-04-30 15:07
This issue is pretty much a duplicate of #46994 which suggests using a chekbox for better amend experience, in case you didn't see #46994 @eamodio 😇

**Comment by lszomoru** [comment] 2023-12-14 12:50
"Commit (Amend)" is now available as a secondary action on the "Commit" action button. 
Clicking it would open the last commit message in the editor, where users can edit it before committing.

**Closed by lszomoru** 2023-12-14 12:50 UTC
Labels: feature-request, git
