### ISSUE TITLE
select certain files at the end of a large directory list => click "New file" button => nothing happens

### ISSUE THREAD

**Issue by chadlavi-casebook** [microsoft/vscode#95127] opened 2020-04-13 15:33 UTC
VSCodium Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-09T11:03:46.219Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. In the files sidebar, open a folder with 112+ files (for me, this happens with a folder that contains 118 markdown files)
2. scroll to the bottom of the list of files in that folder
3. click the last one to focus it
4. click the "New file" button in the file sidebar

EXPECTED: you are prompted to enter the new file's name
ACTUAL: some scrolling happens, but you are not prompted to enter the new file's name

This seems to happen for me with the 112th and further files -- if I select the 111th from the top file, then click "New file", it works as expected.

Does this issue occur when all extensions are disabled?: Yes

here's a video of this bug happening: https://send.firefox.com/download/17844e35c4d445eb/#7BqWYbGR0V4iXpo4p_Lybg

**Comment by isidorn** [comment] 2020-04-13 17:06
This works for me. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Also let me know if you are doing something different than me
![explorer](https://user-images.githubusercontent.com/1926584/79141298-d4277980-7db9-11ea-8ffa-6070398e638a.gif)

**Comment by chadlavi-casebook** [comment] 2020-04-13 17:16
@isidorn interesting! I wonder if this is specific to markdown files... 

FWIW this is reproducible with the same files on different macbooks.

I just tried it in VSCode insiders, and it is also reproducible there. 

I'm also able to reproduce it with the attached example... open `example/2020` in the file explorer, select the last item in the list, and the bug occurs (for me, anyway)

[example.zip](https://github.com/microsoft/vscode/files/4470714/example.zip)

**Comment by isidorn** [comment] 2020-04-13 18:10
I can reproduce with your example folder. Assigning to April to investigate what is the issue

**Comment by chadlavi-casebook** [comment] 2020-04-13 18:11
@isidorn thanks for the followup! Glad it's not user error, I was going nuts with this.

**Comment by isidorn** [comment] 2020-04-14 08:39
@chadlavi-casebook I have pushed a potential fix for this. I can no longer repro this issue. It would be great if you try vscode insiders tomorrow (wednesday) and let me know if you still see this. Thanks!

**Comment by chadlavi-casebook** [comment] 2020-04-14 12:40
@isidorn great, I'll update insiders tomorrow and let you know. Thanks!

**Comment by chadlavi-casebook** [comment] 2020-04-15 13:38
@isidorn yep, it's fixed for me in this morning's build of insiders. Thanks again!

**Comment by isidorn** [comment] 2020-04-15 13:53
Thanks, adding verified label.

**Comment by isidorn** [comment] 2020-04-23 14:05
Sorry but my solution for this issue was incorecct as it casued a regression https://github.com/microsoft/vscode/issues/95315
Due to that I had to revert my fix here. And due to that I will have to reopen this issue and I might tackle it in a smarter way in the future. Also a PR which fixes it is welcome.

**Comment by chadlavi-casebook** [comment] 2020-04-23 14:17
@isidorn oh wow, yeah I guess that is a bit of a regression!

And for anyone who comes to work on this in the future, I just found that the same bug is also exhibited if you use the command palette's "New file" command, not just if you click the new file button in the left sidebar.

**Comment by chadlavi-casebook** [comment] 2020-04-23 14:21
Ah I see, the real issue here is that the parent is not in view huh? I thought maybe it had to do with the number of files, but that's just incidental -- you could reproduce this with only 5 or 6 files in the folder but a really really short window so that the parent is scrolled out of view.

**Comment by isidorn** [comment] 2020-04-23 16:48
Yeah, exacty the issue is when the parent is not visible.
So we should reeal that, but due to the funkiness how the input box blur works that breaks the other issue.

**Comment by chadlavi-casebook** [comment] 2020-04-23 18:16
Well, for anyone else who comes here with the same issue: my not-perfect workaround is to focus the parent folder, then click New file. Note that simply scrolling the explorer so that the parent is in view isn't sufficient, the focused explorer item and the parent have to both be in view.

**Comment by chadlavi-casebook** [comment] 2020-04-23 18:18
(also if you change the Explorer: Sort Order preference to `modified`, your most recently edited files will appear directly beneath the parent, so this is less likely to happen)

**Comment by jeanp413** [comment] 2020-04-24 15:48
I wasn't able to reproduce this even after @isidorn reverted his commit so after some digging I found that the proper fix was 39419c6e586b6c6a53a36338d90eb74ac0ea63b7 so I this issue if resolved now
cc @chadlavi-casebook

**Comment by chadlavi-casebook** [comment] 2020-04-24 15:50
@jeanp413 oh neat! Thank you for the update.

What's your all's release cadence? Is this something that would probably show up in the May 2020 release?

**Comment by jeanp413** [comment] 2020-04-24 15:57
Yeah the fix will be in the May update, you could also test it for yourself right now in the insiders release  https://code.visualstudio.com/insiders/

**Comment by chadlavi-casebook** [comment] 2020-04-24 16:01
@jeanp413 yep, I can confirm that this is fixed for me in the latest version of insiders

**Comment by isidorn** [comment] 2020-04-24 18:15
@jeanp413 thanks a lot. You are correct that was a proper fix by Alex on our scrollable element.
Thus clsoing this. Thanks everybody.

**Closed by isidorn** 2020-04-24 18:15 UTC
Labels: bug, file-explorer
