### ISSUE TITLE
Keyboard shortcuts (copy, paste...) unexpectedly rebound

### ISSUE THREAD

**Issue by hungys** [Microsoft/vscode#28046] opened 2017-06-05 16:05 UTC
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Many macOS users found that the copy/paste keyboard shortcut becomes **not working randomly**, according to #24112 and #26344.

I also encountered this issue few moments ago and found something interesting:

**The keyboard shortcut of copy/paste still works but they have been rebound unexpectedly.**

Check the following screenshots, the copy/paste key were rebound to `control+option+command+c/v`, although it still shows `command+c/v` in the context menu of search area. With these weird shortcuts, I can successfully paste something to search area, without the need to reload the window or restart VS Code.

![](http://i.imgur.com/Mv4OnaU.png)

![](http://i.imgur.com/qKl26vY.png)

I still cannot figure out how to reproduce these changes of keybindings, but this fact may be helpful for further investigation.

**Comment by alexandrudima** [comment] 2017-06-06 06:31
@hungys This might be caused by one of your installed extensions, which might be defining additional keybindings for the copy/paste commands or removing the built-in ones.

Since macOS only allows us to list one keybinding in the top level menus, we list the most *powerful* one, i.e.: user defined, extensions defined, built-in. So if an extension defines `ctrl+shift+cmd+c` for copy, we will show that one in the menus.

Does this reproduce when running `code --disable-extensions` ?

The other users report that this shortcut works intermittently, is that the case for you or can you immediately reproduce?

Thanks for paying close attention and noticing! :heart:

**Comment by hungys** [comment] 2017-06-06 13:51
@alexandrudima 

> This might be caused by one of your installed extensions, which might be defining additional keybindings for the copy/paste commands or removing the built-in ones.

Can these be checked in contributions section of the extension page? Actually I didn't find any extension that defines such keybindings as their contributions. The followings are my installed extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|vsc-material-theme|Equinusocio|0.0.15|
|vscode-docker|PeterJausovec|0.0.15|
|llvm|RReverser|0.0.1|
|django-html|bibhasdn|1.2.0|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|3.6.0|
|tslint|eg2|0.15.0|
|code-runner|formulahendry|0.6.18|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|better-merge|pprice|0.7.0|
|vscode-icons|robertohuertasm|7.8.1|
|guides|spywhere|0.7.0|
|debug|webfreak|0.20.0|
|Material-theme|zhuangtongfa|2.8.4|;

> Does this reproduce when running code --disable-extensions ?

It's hard to say, because I don't exactly know when and how this issue will occur.

> The other users report that this shortcut works intermittently, is that the case for you or can you immediately reproduce?

It randomly occurs on non-editor area. But I'm not sure if there is anyone also found that the keyboard shortcuts had actually been rebound.

**Comment by alexandrudima** [comment] 2017-06-06 14:06
Adding @bpasero (since this appears to be menu related as well).

**Comment by bpasero** [comment] 2017-06-06 14:45
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by hungys** [comment] 2017-06-06 14:52
@bpasero 

I will definitely try it. But it may need some time to verify because this is a randomly occurred issue (actually I only encountered 3 times these few weeks), and I suspect it may be related to #26344.

**Comment by hungys** [comment] 2017-06-09 14:47
@alexandrudima @bpasero 

The issue still occurred on VS Code 1.13 with extensions disabled.

![](http://i.imgur.com/r1ia4fL.png)

Also, I captured all the menu so you can see that bunch of keyboard shortcuts were rebound. I personally don't think there's any extension (except keymap extension) would do this...

1. File

![](http://i.imgur.com/4SQFvyP.png)

![](http://i.imgur.com/9nbngFb.png)

2. Edit

![](http://i.imgur.com/fduCZpe.png)

![](http://i.imgur.com/eZtJJ8C.png)

3. Selection

![](http://i.imgur.com/gmNE5J3.png)

![](http://i.imgur.com/oPYPWf0.png)

4. View

![](http://i.imgur.com/DK9KYQ4.png)

![](http://i.imgur.com/uY0GF3N.png)

5. Go

![](http://i.imgur.com/VGjGc3R.png)

![](http://i.imgur.com/u6M2Egy.png)

6. Debug

![](http://i.imgur.com/7DI0wzb.png)

![](http://i.imgur.com/OEDqkTS.png)

**Comment by bpasero** [comment] 2017-06-09 17:02
@hungys does this happen randomly while the application is running (so you start and things are good and then suddenly the keys show up?). Or does this persist between restarts. Does it happen for more keys than copy/paste?

**Comment by hungys** [comment] 2017-06-09 17:15
@bpasero 

Randomly, starting from good, not persistent, and not frequently for me. (See #24112 and #26344)

When issue occurred,

- copy
    - only `control+option+command+c` works on search widget
    - `command+c` works on editor area, not sure for `control+option+command+c`
- paste
    - only `control+option+command+v` works on search widget
    - `command+v` works on editor area, not sure for `control+option+command+v`
- find
    - `command+f` works, not sure for `control+option+command+f`

I didn't test other keyboard shortcuts, need to wait until it occurs next time... then I'll try.

**Comment by bpasero** [comment] 2017-06-09 17:19
@hungys do these keys show up in the keybindings editor as well when this happens? can you share the contents of your keybindings.json file?

**Comment by hungys** [comment] 2017-06-09 17:27
@bpasero 

I didn't customize any keybinding, so there's basically an empty array in `keybindings.json`. Also I didn't install any keymap extension.

I did check the keybindings editor when issue occurred, but only for Paste (`editor.action.clipboardPasteAction`). It was`command+v`.

**Comment by bpasero** [comment] 2017-06-10 04:59
@hungys and so did the keybindings in the editor match with what you saw in the menu?

**Comment by hungys** [comment] 2017-06-10 05:04
@bpasero 

When issue occurs, at least **Paste** (`editor.action.clipboardPasteAction`) doesn't match. I didn't check them comprehensively.

Menus shows `control+option+command+v`
Keybindings editor shows `command+v`

However, at that time, `command+v` still works on editor area, but not on find widget and search panel. `control+option+command+v` works everywhere.

**Comment by bpasero** [comment] 2017-06-10 05:08
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by hungys** [comment] 2017-06-10 05:10
@bpasero 

OK. Not sure when it will happen. I'll let you know.

**Comment by alexandrudima** [comment] 2017-06-12 06:34
@hungys Not that I think more about it, this might also be caused by our mapping of default keybindings based on keyboard layouts. This might also depend on what keyboard layout you have activated and what OSX returns in the `TISCopyCurrentKeyboardInputSource` call we do. Which keyboard layouts do you regularly use?

When the issue occurs, could you  open an editor and run `F1 > Developer: Inspect Key Mappings`.

**Comment by kevingo** [comment] 2017-06-15 15:49
- VSCode Version: 1.13.1
- OS Version: macOS 10.11.1

Hi, I also encounter the same problem with @hungys situation. The copy/paste binds to the wired `ctrl+option+command+c` and `ctrl+option+command+v`.

After restarting vscode app, this problem goes away. I will update the `F1 > Developer: Inspect Key Mappings.` results when I occurs this problem next time.

**Comment by alexandrudima** [comment] 2017-06-16 06:55
@kevingo What input methods / keyboard layouts do you have installed on your OS ?

**Comment by alex-gvozden** [comment] 2017-06-20 08:51
I have this problem right now after new update....

**Comment by c01nd01r** [comment] 2017-06-20 09:45
I have the same issue.
VSCode  1.13.1 (1.13.1)
OS Version: MacOSX: 10.11.1

Using PC keyboard with ABC and Russian - PC keyboard layouts.

**Comment by bpasero** [comment] 2017-06-28 14:47
@alexandrudima is this a duplicate of https://github.com/Microsoft/vscode/issues/28237 ?

**Comment by alex-gvozden** [comment] 2017-06-28 14:58
I don't have this issue any more It seems it only occurred once after update

**Comment by alexandrudima** [comment] 2017-06-28 15:28
Closing as dup of #28237.

**Closed by alexandrudima** 2017-06-28 15:28 UTC
Labels: bug, needs more info
