### ISSUE TITLE
OSX - Not able to overwrite workbench.action.closeWindow keybinding

### ISSUE THREAD

**Issue by barthand** [Microsoft/vscode#6345] opened 2016-05-13 11:12 UTC
- VSCode Version: 1.1.0
- OS Version: OSX 10.10.5

Hi there,

First of all, thanks for all the great work around VS Code!

I'm having an issue with overriding keybinding for `cmd+w` (which by default closes currently opened tab). I'm trying to define following bindings in order to mimic the IntelliJ IDEA bindings:

```
|| Key              || Action                           ||
| cmd + w           | editor.action.smartSelect.grow    |
| cmd + shift + w   | editor.action.smartSelect.shrink  |
| cmd + f4          | workbench.action.closeWindow      |
```

Unfortunately, putting them into my keybindings doesn't result in any change.

Steps to Reproduce:

1. Press F1 and select _Preferences: Open Keyboard Shortcuts_
2. Put the following into your keybindings definition:

    ```
    // Place your key bindings in this file to overwrite the defaults
    [
        {
            "key": "cmd+f4",
            "command": "workbench.action.closeWindow",
            "when": "editorTextFocus"
        },
        {
            "key": "cmd+w",
            "command": "editor.action.smartSelect.grow",
            "when": "editorTextFocus"
        },
        {
            "key": "shift+cmd+w",
            "command": "editor.action.smartSelect.shrink",
            "when": "editorTextFocus"
        }
    ]
    ```

3. Restart VS Code
4. Try to expand selection using `Cmd+W`. 

**Expected result:**
Keystroke expands smart selection.

**Actual result:**
Currently opened window closes.

**Comment by bpasero** [comment] 2016-05-13 13:24
I cannot reproduce. Moving to @alexandrudima to see if there are some concerns with this approach.

**Comment by bpasero** [comment] 2016-05-13 13:24
The only thing I notice is that when the editor does not have focus, Cmd+W still closes the window so adding another rule to unbind the key should do it.

**Comment by barthand** [comment] 2016-05-21 16:01
Hi @bpasero,

Thanks for checking! After updating to 1.1.1 (def9e3) issue stopped to occur for me.

Sorry for troubling you! Please close the ticket.

**Closed** 2016-05-21 16:01 UTC

**Comment by alexandrudima** [comment] 2016-05-23 13:48
@bpasero This might have been caused by the top level menus not updating accelerators until a restart.
