### ISSUE TITLE
Paste in Markdown gets garbled

### ISSUE THREAD

**Issue by arvigeus** [microsoft/vscode#188125] opened 2023-07-18 02:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.0-insider
- OS Version: Fedora 38

Steps to Reproduce:

1. Input copied from Firefox:

```txt
    Registry: A service storing and distributing container images and related artifacts, with features like authentication, geo-replication, and more.

    Repository: A collection of container images or artifacts in a registry, identified by the same name but different tags.

    Artifact: An item within a registry associated with tags and layers, identified by a manifest.

    Manifest: A unique identifier generated when an artifact is pushed to the registry, specifying the artifact's layers.
```

2. Result when I paste it in VS Code:

```txt
[Title](../../../../..) [Title](../../../../..) [Title](../../../../..)
```

Everything I paste gets garbled. The only workaround so far is to change to plaintext.

**Comment by conradwt** [comment] 2023-07-19 18:18
I'm seeing a similar issue.  For example, when I paste the following:

```zsh
service:cwt-supergraph:Yb1witpWtR7zfEB6hEQPdA
```

I'm getting the following:

[Title](service:cwt-supergraph%253AYb1witpWtR7zfEB6hEQPdA)

instead of the following:

[Title](service:cwt-supergraph:Yb1witpWtR7zfEB6hEQPdA)

Finally, this isn't a link and it's not clear to me why it's generating a markdown link for the original input.  For now, I have changed `smart` to `never` for `Markdown › Editor › Paste Url As Formatted Link`.

**Comment by MeghanKulkarni** [comment] 2023-07-20 01:05
duplicate of https://github.com/microsoft/vscode/issues/187201

**Closed by MeghanKulkarni** 2023-07-20 01:05 UTC
Labels: bug, markdown
