### ISSUE TITLE
Unable to run npm build task

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#47314] opened 2018-04-06 12:04 UTC
Issue Type: <b>Bug</b>

I'm not sure what changed, but pressing `ctrl+shift+b` has stopped working for me since yesterday's insiders build.
```
> Executing task: npm run build <

-Command : The term '-Command' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ -Command npm run build
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundExc
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

The terminal process terminated with exit code: 1
```

tasks.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "identifier": "build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "silent",
                "panel": "shared"
            },
            "problemMatcher": "$tsc"
        }
    ]
}
```

The actual build command is a simple `tsc -p ./src`.

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 10.0.16299

Extensions: none

**Comment by dbaeumer** [comment] 2018-04-06 13:46
I can reproduce this on insider. It is not happening on 1.22.

**Comment by dbaeumer** [comment] 2018-04-06 13:55
Marking as important since this will very likely break most tasks executed in PowerShell.

**Comment by dbaeumer** [comment] 2018-04-06 13:58
This is the shell launch config in stable (1.22)

<img width="476" alt="capture" src="https://user-images.githubusercontent.com/1931590/38425152-5dd2907c-39b3-11e8-9383-dd58219514f2.png">

**Comment by Tyriar** [comment] 2018-04-06 19:11
@dbaeumer I don't think I changed anything in this area so i'm not sure what it could be. I have recently added some logging which should be very handy in getting to the root of this. @dbaeumer could you repro again when using `code-insiders --log trace`? This will tell us exactly what's being given to terminalProcess on creation.

**Comment by eamodio** [comment] 2018-04-06 19:15
@Tyriar I am seeing the same, and ran it with `code-insiders --log trace`. This is what I see:

```
[2018-04-06 15:13:07.162] [renderer1] [debug] Terminal process ready (id: 2, processId: 40452)
[2018-04-06 15:13:07.162] [renderer1] [debug] Terminal process message (id: 2) {"type":"pid","content":40452}
[2018-04-06 15:13:07.162] [renderer1] [debug] Terminal process message (id: 2) {"type":"title","content":"powershell.exe"}
[2018-04-06 15:13:07.181] [renderer1] [debug] Terminal process message (id: 2) {"type":"data","content":"\u001b[0m\u001b[0K"}
[2018-04-06 15:13:07.837] [renderer1] [debug] Terminal process message (id: 2) {"type":"data","content":"\u001b[0;31;91m-Command : The term '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was \u001b[0m\u001b[0K\u001b[?25l\r\n\u001b[0;31;91mincluded, verify that the path is correct and try again.\u001b[0m\u001b[0K\r\n\u001b[0;31;91mAt line:1 char:1\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ -Command npm run compile\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ ~~~~~~~~\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + FullyQualifiedErrorId : CommandNotFoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m \u001b[0m\u001b[0K\r\n\u001b[0K\u001b[?25h"}
[2018-04-06 15:13:08.149] [renderer1] [debug] Terminal process exit (id: 2) with code 1
[2018-04-06 15:13:08.149] [renderer1] [debug] Terminal process exit (id: 2) state 5
```

**Comment by Tyriar** [comment] 2018-04-06 19:42
@eamodio you should see a launching one, maybe you need to be on a later version of Insiders?

https://github.com/Microsoft/vscode/blob/4cd09ff11e44e2eabe75f3a8913610cbabf83379/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L708

**Comment by eamodio** [comment] 2018-04-06 20:27
@Tyriar sorry I didn't go back far enough

```
[2018-04-06 16:23:10.024] [renderer5] [trace] terminalInstance#ctor (id: 1) {"name":"Task - build","executable":"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","args":"-Command npm run build","waitOnExit":"Terminal will be reused by tasks, press any key to close it.","initialText":"\u001b[1m> Executing task: npm run build <\u001b[0m\n","cwd":"c:\\Users\\Eric\\code\\vscode-gitlens"}
[2018-04-06 16:23:10.026] [renderer5] [debug] Terminal process launching (id: 1) {"env":{ ... },"cwd":"c:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\workbench\\parts\\terminal\\node"}
[2018-04-06 16:23:10.373] [renderer5] [debug] Terminal process ready (id: 1, processId: 30848)
[2018-04-06 16:23:10.378] [renderer5] [debug] Terminal process message (id: 1) {"type":"pid","content":30848}
[2018-04-06 16:23:10.393] [renderer5] [debug] Terminal process message (id: 1) {"type":"title","content":"powershell.exe"}
[2018-04-06 16:23:10.394] [renderer5] [debug] Terminal process message (id: 1) {"type":"data","content":"\u001b[0m\u001b[0K"}
[2018-04-06 16:23:11.581] [renderer5] [debug] Terminal process message (id: 1) {"type":"data","content":"\u001b[0;31;91m-Command : The term '-Command' is not recognized as the name of a cmdlet, \u001b[0m\u001b[0K\u001b[?25l\r\n\u001b[0;31;91mfunction, script file, or operable program. Check the spelling of the name, \u001b[0m\u001b[0K\r\n\u001b[0;31;91mor if a path was included, verify that the path is correct and try again.\u001b[0m\u001b[0K\r\n\u001b[0;31;91mAt line:1 char:1\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ -Command npm run build\u001b[0m\u001b[0K\r\n\u001b[0;31;91m+ ~~~~~~~~\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandN \u001b[0m\u001b[0K\r\n\u001b[0;31;91m   otFoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m    + FullyQualifiedErrorId : CommandNotFoundException\u001b[0m\u001b[0K\r\n\u001b[0;31;91m \u001b[0m\u001b[0K\r\n\u001b[0K\u001b[?25h"}
[2018-04-06 16:23:11.880] [renderer5] [debug] Terminal process exit (id: 1) with code 1
[2018-04-06 16:23:11.880] [renderer5] [debug] Terminal process exit (id: 1) state 5
```

FYI, I snipped out all of the env stuff

**Comment by Tyriar** [comment] 2018-04-06 20:39
I could repro this, env variables of note are:

```
PTYCWD: "c:\Users\Daniel\Documents\dev\Tyriar\xterm.js"
PTYPID: "12544"
PTYSHELL: "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe"
PTYSHELLCMDLINE: "-Command npm run build"
```

**Comment by Tyriar** [comment] 2018-04-06 21:03
Doesn't seem to repro when running out of sources.

I believe this was caused by https://github.com/Microsoft/vscode/commit/94f56746956d53f7e30f11ca39a4cb7aec105ae6#diff-dc09948028c646a458fac5f5b5d32276R96 with the Electron 2 changes and this got reapplied after it was reverted. The correct return type for `getArgs` was actually `string[] | string` which is my bad really as I haven't gotten around to do proper types for node-pty (fyi @bpasero).

If someone could verify in Monday's build that would be great as I can't repro out of sources.

**Closed** 2018-04-06 21:04 UTC
Labels: important, insiders, integrated-terminal

**Comment by ghiscoding** [comment] 2018-04-07 18:01
@Tyriar 
I also have been having this problem since couple days and it is not fixed either on my side. I use `yarn` script commands and they all fail with similar output:

```bash
> Executing task: yarn start:dev <

-Command : The term '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -Command yarn start:dev
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The terminal process terminated with exit code: 1
```

One of the task failing has the following configuration
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Start Library Development",
      "type": "shell",
      "command": "yarn start:dev",
      "problemMatcher": []
    },
  ]
}
```

I will have to use the stable version until this is fixed.

**Comment by ShayBox** [comment] 2018-04-08 20:06
ok come on, you guys publish 3-4 insiders updates some days, and now you choose to not push one for 2 days, to fix a big problem that stops anyone using insiders and task runner. I want to get back to coding

**Comment by ghiscoding** [comment] 2018-04-08 20:09
@ShayBox 
There are no insiders push in weekend, regular cycle will be tomorrow

**Comment by mattacosta** [comment] 2018-04-09 00:10
The work around is to just type the command into a terminal yourself. If you have a watch task, this only needs to be done once as well.

**Comment by ghiscoding** [comment] 2018-04-12 03:38
I can confirm that this is fixed on my side.
