### ISSUE TITLE
JavaScript code highlight not working well after 0.10.10

### ISSUE THREAD

**Issue by evandroprogram** [Microsoft/vscode#3868] opened 2016-03-08 16:36 UTC
After update 0.10.10 the code highlight for javascript seems to be different, keywords like `function` `var` etc, are not highlighted. Also, when coding, after line break the cursor get back to the start of the line.

**Comment by biscoe916** [comment] 2016-03-08 16:43
+1

**Comment by evandroprogram** [comment] 2016-03-08 17:26
Seems to be related with issue #3791 
I tried the suggestions of the discussion, but seems not working, also, I don't like the idea of create configuration files for everything or add references directly on the file.

**Comment by rbozan** [comment] 2016-03-08 17:38
>  Also, when coding, after line break the cursor get back to the start of the line.

Currently having the same issue. You see the cursor aligned just fine for a frame after you press enter, and suddenly the cursor is at the start of the line.

**Comment by dwcares** [comment] 2016-03-08 18:38
+1. I don't have functional code highlight in js. it's not clear if there's a workaround. if there is, please post here

**Comment by nelsonlaquet** [comment] 2016-03-08 22:36
@evandroprogram for now, just go ahead and set "editor.formatOnType" to "false". That will fix the indentation problem... Though of course it will disable auto code formatting, which is disappointing. I'm sure there'll be a fix soon.

**Comment by aeschli** [comment] 2016-03-09 09:37
Syntax highlighting issue is a duplicate of https://github.com/Microsoft/vscode/issues/3903.
Workaround is to switch to the Dark+/Light+ default themes.

For all other JS issues (intellisense, indentation) please create separate issues.

**Closed by aeschli** 2016-03-09 09:37 UTC
