### ISSUE TITLE
Random pixels appearing in some places

### ISSUE THREAD

**Issue by valerymelou** [Microsoft/vscode#38307] opened 2017-11-14 09:24 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.13.0-1-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.11.3

---

Steps to Reproduce:

1. Just open the editor
2.

Reproduces without extensions: Yes

My editor is displaying random pixels in some places. Sorry I don't know how to be more clear about this. Take a close look at the picture to see what I mean.

Notable ones are in the User Settings tab, and near the ".vue" file association key.

![screenshot from 2017-11-14 10-13-40](https://user-images.githubusercontent.com/9080102/32772162-567f9454-c925-11e7-93f1-cee9adbfa26b.png)

**Comment by valerymelou** [comment] 2017-11-20 08:28
This might be related to #35675. Downgrading `libfreetype6` to `2.8` as suggested in the comments fixed the issue for me.

**Comment by yeahnoob** [comment] 2018-02-12 03:17
Or upgrading libfreetype6 to v2.9 (build from upstream source) also fixed the issue.
[freetype-2.9](https://sourceforge.net/projects/freetype/files/freetype2/2.9/)

**Comment by bpasero** [comment] 2018-03-16 06:21
Duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by bpasero** 2018-03-16 06:21 UTC
Labels: electron, font-rendering, upstream
