### ISSUE TITLE
Error Extension host terminated unexpectedly.  Every 3 minures after reloading window!

### ISSUE THREAD

**Issue by ddzmitry** [Microsoft/vscode#24742] opened 2017-04-14 04:17 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|html-class-suggestions|AndersEAndersen|1.0.7|
|vscode-database|bajdzis|1.2.0|
|vscode-styled-jsx|blanu|0.1.0|
|vscode-javascript-snippets|codepunkt|1.0.0|
|jshint|dbaeumer|0.10.15|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.9.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.1|
|react-native-react-redux|EQuimper|0.2.0|
|prettier-vscode|esbenp|0.13.0|
|php-intellisense|felixfbecker|1.1.5|
|javascript-unit-test-snippet|iZDT|1.0.0|
|react-component|jeremyrajan|1.0.0|
|cobalt2-Theme|kamranmackey|0.0.3|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-format|ryannaddy|0.0.6|
|react-beautify|taichi|0.3.0|
|jsx|TwentyChung|0.0.1|
|jsx-snippets|TwentyChung|0.0.1|
|expresssnippet|vladmrnv|0.1.0|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.VS Code sends message Error Extension host terminated unexpectedly.  Please reload to recover!
2. It does it every 2-3 minutes after I reload the window
3.tried to uninstall and install again, still the same issue

**Comment by ddzmitry** [comment] 2017-04-14 04:25
shell.ts:475 Invalid string length: RangeError: Invalid string length
    at Object.r [as stringify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:38622)
    at Function.e.request (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:136194)
    at Object.callOnRemote (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:134903)
    at t._callOnRemote (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:278169)
    at Object.$updateGroupResourceStates (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:277734)
    at e.set [as resourceStates] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:337633)
    at GitSCMProvider.onDidModelChange (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\git\out\scmProvider.js:88:46)
    at i (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\git\out\util.js:44:83)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:16423)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:20054)

**Comment by ngohungphuc** [comment] 2017-04-14 04:34
I'm also facing same issue. And after I get that error every package no longer work

**Comment by ddzmitry** [comment] 2017-04-14 04:35
It is been like this for last few days

**Comment by polegithub** [comment] 2017-04-14 07:10
I meet that problem again.
 #24748

**Comment by jrieken** [comment] 2017-04-14 07:23
@ddzmitry Does this happen for folders that aren't under git version control?

**Comment by ngohungphuc** [comment] 2017-04-14 07:24
@jrieken Happend for both git folder and not a git folder

**Comment by ddzmitry** [comment] 2017-04-15 10:51
@jrieken Both

**Comment by DeltaCharlieAlpha** [comment] 2017-04-17 18:07
I am seeing this problem continually no matter how I am using VS Code.  Are there any workarounds or ways to prevent this error?  It is quickly sapping my productivity and I may have to move to another editor while I wait for the fix if there isn't some way to prevent the issue.  If I could just see the tabs at the top of the screen to keep switching windows, etc, I could handle it and just leave the error up and ignore it for the most part.

**Comment by joaomoreno** [comment] 2017-04-18 07:28
@ddzmitry Where did you find that message? Can you share a screenshot?

@ngohungphuc Can you share a screenshot too?

**Comment by ngohungphuc** [comment] 2017-04-18 07:41
@joaomoreno 
This is [what](http://prntscr.com/exqogh)  I get when open developer console

**Comment by joaomoreno** [comment] 2017-04-18 08:48
@ngohungphuc Can you also try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by ngohungphuc** [comment] 2017-04-18 09:09
@joaomoreno Same error

**Comment by ddzmitry** [comment] 2017-04-18 11:30
@joaomoreno  the same error , and same picture

**Comment by joaomoreno** [comment] 2017-04-18 12:29
@ngohungphuc @ddzmitry Does this happen on any folder you open with Code? Even if you open a brand new window without any open folder?

**Comment by ddzmitry** [comment] 2017-04-18 12:46
@ngohungphuc yes it was, so here what I did
I went to AppData  => Local and delete all VSCode extensions, delete all affiliations with regular VS code, restarted computer.
Installed VS Code Insider, and it is being stable for last 2 hours, I have two projects one in PHP and one in React both running fine so far.

However THIS 'solution' didn't work with regular VS code.

**Comment by ddzmitry** [comment] 2017-04-18 12:47
![image](https://cloud.githubusercontent.com/assets/21366035/25131433/b44e5e42-2413-11e7-8432-6807e9020e07.png)

**Comment by PolymathWhiz** [comment] 2017-04-18 13:00
It happens to me too

**Comment by PolymathWhiz** [comment] 2017-04-18 13:01
I created an issue with issue id 24914. Attached is a screenshot

**Comment by PolymathWhiz** [comment] 2017-04-18 13:02
Since I started getting the error, I've been tempted to switch editors. Its really disturbing

**Comment by joaomoreno** [comment] 2017-04-18 13:04
@PolymathWhiz Sorry about that. Are you willing to do a screen sharing session right now with me, so we figure out what's wrong?

https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode17475

**Comment by PolymathWhiz** [comment] 2017-04-18 13:09
Currently not in the position to do that

**Comment by PolymathWhiz** [comment] 2017-04-18 13:10
But I can provide written aid

**Comment by joaomoreno** [comment] 2017-04-18 13:23
Just had an awesome chat with @ddzmitry, and we figured out that his issue is that he had a folder open which wasn't a git repository while at the same time there was a git repository in his home folder. This caused Code to handle that git repository which had many many open files.

This is definitely a dupe of #23976, I'll try to get a fix out today. The fix will try to catch these huge repository issues before they break the extension host.

The workaround for you guys is:

- Open the workspace folder in a shell and type `git rev-parse --show-toplevel`. This will tell you where the root of the git repository you have opened is.
- Evaluate whether this repository should exist or not. In @ddzmitry's case it was his user's home, which made no sense. He fixed it by simply removing that `.git` folder.

Once again, thanks @ddzmitry for your help!

**Closed by joaomoreno** 2017-04-18 13:23 UTC
Labels: important, needs more info

**Comment by ddzmitry** [comment] 2017-04-18 13:27
@joaomoreno Anytime! Thank you!

**Comment by PolymathWhiz** [comment] 2017-04-18 13:32
@joaomoreno please push the fix and let's make vscode better, together!

**Comment by wojstu** [comment] 2017-04-18 13:34
@joaomoreno thank you! the workaround is working fine:)

**Comment by ngohungphuc** [comment] 2017-04-18 13:38
Waiting for the fix.This error drive me crazy for a week

**Comment by joaomoreno** [comment] 2017-04-18 13:41
> 1. Open the workspace folder in a shell and type `git rev-parse --show-toplevel`. This will tell you where the root of the git repository you have opened is.
> 2. Evaluate whether this repository should exist or not. In @ddzmitry's case it was his user's home, which made no sense. He fixed it by simply removing that `.git` folder.

@ngohungphuc Can you look at these steps? They are the right fix.

**Comment by ngohungphuc** [comment] 2017-04-19 00:16
@joaomoreno I think when I try to open multiple folder in vs code that contain multiple .git folder it will break extension host

**Comment by PolymathWhiz** [comment] 2017-04-19 02:10
@ngohungphuc The permanent fix will likely come as an update soon

**Comment by ngohungphuc** [comment] 2017-04-19 02:33
Thank you guys

**Comment by joaomoreno** [comment] 2017-04-19 06:54
@PolymathWhiz The _permanent_ fix is a warning that you have opened a folder in a git repo that has too many active changes, so features will be limited. Prior to April, the Git features were disabled altogether.

Overall, it would be great if you could confirm that your scenario is indeed what I described above:

> git repository which had many many active changes

**Comment by joaomoreno** [comment] 2017-04-19 10:07
The latest insider update already has this fixed, care to give it a try?

- [Windows](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCodeSetup-1.12.0-insider.exe)
- [macOS](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCode-darwin-insider.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/code-insider-1.12.0-1492586320_amd64.tar.gz)

**Comment by chenyeah** [comment] 2017-04-24 07:49
@joaomoreno  vscode 1.12.0 also have this problem

**Comment by liyongfa** [comment] 2017-04-26 15:21
@ joamoreno vscode 1.12.0 also have this problem

**Comment by iAspace** [comment] 2017-05-04 23:51
I have also encountered this problem
![1](https://cloud.githubusercontent.com/assets/27795459/25729385/a30c49e4-3167-11e7-8db7-bfcbc2c05710.png)

**Comment by Jerusalemsbell** [comment] 2017-09-07 07:11
![image](https://user-images.githubusercontent.com/11695808/30150623-afd1b036-93de-11e7-9e4e-823ab03688ee.png)
still has the same problem in 1.15.1

**Comment by Jerusalemsbell** [comment] 2017-09-07 07:38
I try deleted D:\Program Files\Microsoft VS Code\resources\app\extensions\git folder. 
Then this issue has resolved.
Version 1.15.1

**Comment by JadeTao** [comment] 2017-09-23 16:02
hey, you guys did't fix  this bug at all.
it's so annoying that i choose Atom :<.
