### ISSUE TITLE
Search editor opens file from wrong directory when workspace has multiple directories opened

### ISSUE THREAD

**Issue by yourmsftacct** [microsoft/vscode#165398] opened 2022-11-03 17:25 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
- OS Version:  21h2 build 22000.675

Steps to Reproduce:

1. Create a workspace with two directories of the same name but different path, e.g. D:\a\b\x, D:\c\d\x
2. Use search editor to search for something where the result is a file like D:\c\d\x\result.txt
3. Double clicking on result vscode tries to open file D:\a\b\x\result.txt which doesn't exist.

**Comment by osortega** [comment] 2024-12-19 18:49
Duplicate of https://github.com/microsoft/vscode/issues/198159
Closing this

/duplicate

**Closed by osortega** 2024-12-19 18:49 UTC
Labels: bug, search, confirmed
