### ISSUE TITLE
Debug consoles cannot be deleted

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62418] opened 2018-11-01 21:37 UTC
VS code Insiders

- run cluster example
- stop all processes

Observe: there are many debug consoles but no way to get rid of them

<img width="339" alt="screenshot 2018-11-01 at 22 32 44" src="https://user-images.githubusercontent.com/1898161/47881520-a26d5d80-de26-11e8-9e29-9e607d3fdd72.png">

**Comment by isidorn** [comment] 2018-11-02 08:49
This is by design. I think this should simply be fixed via https://github.com/Microsoft/vscode/issues/62419

Closign this for now, we can reopen in the future if 62419 proves to not be a good solution

**Comment by weinand** [comment] 2018-11-02 11:53
Since Integrated terminal can be deleted, the same should be possible for debug consoles. 

Disabling multiple debug consoles doesn't help in deleting them.

**Comment by isidorn** [comment] 2018-11-12 14:46
We will add a title bar action to delete only when there is more than I console.
Deleting the console, only delets the console it does not interact with the running session in any way

**Closed** 2018-11-12 16:16 UTC
Labels: debug, debug-console, feature-request, verification-needed

**Comment by isidorn** [comment] 2018-11-12 16:17
We have decided not to render a new action delete, but instead to not show inactive debug console which got cleared.
This in practice means that you can press clear to get rid of outdated debug consoles.

To verify
1. Start debugging two debug sessions in the same time
2. Stop debugging them
3. Make sure that pressing clear removes the cleared debug console and that you can get rid of all except the last one standing
