### ISSUE TITLE
Add Prompt/Setting to Avoid Committing when Nothing is Staged.

### ISSUE THREAD

**Issue by skl131313** [Microsoft/vscode#21960] opened 2017-03-04 05:04 UTC
I've hit ctrl+enter too many times with nothing staged and it just commits everything. Having an extra prompt in that case would be nice.

Or, possibly add a setting that could be toggled on which wouldn't allow committing anything unless it has been staged first. So if nothing is staged, nothing would happen. Other than maybe an error saying nothing is staged to commit.

**Comment by sprinkle131313** [comment] 2017-03-08 05:28
@joaomoreno Not sure if it is a bug, it seems like it is the intended behavior. If nothing is staged then any changes that were made are committed. I would want different behavior (through a setting) that would make it so that any changes made first have to be staged. So that if you forget to stage the items you need first, all other changes don't get drawn into the commit.

**Comment by joaomoreno** [comment] 2017-04-25 15:18
#15613

**Closed by joaomoreno** 2017-04-25 15:18 UTC
Labels: bug, git
