### ISSUE TITLE
Hide opened file/explorer icons

### ISSUE THREAD

**Issue by Waldemar-Dassler** [Microsoft/vscode#41876] opened 2018-01-19 17:22 UTC
Hello!
How i can hide this lines?
![example](https://user-images.githubusercontent.com/25832802/35163047-0e0396f0-fd4e-11e7-8d59-b0be7256cf5a.png)

**Comment by bpasero** [comment] 2018-01-19 18:05
There is no way currently. Closing as duplicate of https://github.com/Microsoft/vscode/issues/33607

**Closed by bpasero** 2018-01-19 18:05 UTC
