### ISSUE TITLE
Can't match multiline occurrences

### ISSUE THREAD

**Issue by ahmetb** [microsoft/vscode#10588] opened 2016-08-16 16:24 UTC
- VSCode Version: 1.4.0

Steps to Reproduce:

In the image below you can see that the highlighted text actually appears 3 times but it can't match it once the highlighted part spans multiple lines. 

![image](https://cloud.githubusercontent.com/assets/159209/17636641/51fa5f28-6093-11e6-96e3-61442bdee5c8.png)

SublimeText works fine in this situation.

<details>
<summary>

in case it helps, the file is here</summary>

```
        "master": {
            "publisher": "Microsoft.OSTCExtensions",
            "type": "CustomScriptForLinux",
            "typeHandlerVersion": "1.4",
        "autoUpgradeMinorVersion": true,
            "settings": {
              "fileUris": "[variables('centosScripts')]",
              "commandToExecute": "[concat('bash elasticsearch-centos-install.sh -xn ', variables('esSettings').clusterName, ' -v ', variables('esSettings').version, ' -d ', variables('esSettings').discoveryHosts, variables('marvelParamValue'), variables('jmeterParamValue'), variables('cloudAzureParamValue'), variables('marvelExportParamValue'), variables('afsParamValue'))]"
            }
          },
        "client": {
            "publisher": "Microsoft.OSTCExtensions",
            "type": "CustomScriptForLinux",
            "typeHandlerVersion": "1.4",
        "autoUpgradeMinorVersion": true,
            "settings": {
              "fileUris": "[variables('centosScripts')]",
              "commandToExecute": "[concat('bash elasticsearch-centos-install.sh -yn ', variables('esSettings').clusterName, ' -v ', variables('esSettings').version, ' -d ', variables('esSettings').discoveryHosts, variables('marvelParamValue'), variables('jmeterParamValue'),  variables('cloudAzureParamValue'),variables('marvelExportParamValue'), variables('afsParamValue'))]"
            }
          },
        "data": {
          "publisher": "Microsoft.OSTCExtensions",
          "type": "CustomScriptForLinux",
          "typeHandlerVersion": "1.4",
      "autoUpgradeMinorVersion": true,
          "settings": {
            "fileUris": "[variables('centosScripts')]",
            "commandToExecute": "[concat('bash elasticsearch-centos-install.sh -zn ', variables('esSettings').clusterName, ' -v ', variables('esSettings').version, ' -d ', variables('esSettings').discoveryHosts, variables('marvelParamValue'), variables('jmeterParamValue'),  variables('cloudAzureParamValue'),variables('marvelExportParamValue'), variables('afsParamValue'))]"
          }
        },
```

</details>

**Comment by StrongRef** [comment] 2016-10-02 12:10
What is the expected result for lines with different indentation?
```
foo
bar


foo
   bar
```

If the first two lines are selected, should _"foo\n   bar"_ also be selected?

**Comment by hun1ahpu** [comment] 2016-12-11 14:43
@ahmetalpbalkan 👍 for idea

Some questions about possible implementation:
- UI: having multiline textbox for search it might cover significant part of the screen, especially in Replace mode. Sublime has similar problem but as the search view is at the bottom of the page it's not that intrusive. Should we consider limiting the max height and having scroll?
- Should it work the same way for In-Project search (ctrl+shift+F)?
- How it will work in combination with a regex?

@StrongRef : i would expect to match only if the number of spaces is the same. Using regex would work for other scenarios.

**Comment by alexandrudima** [comment] 2016-12-12 14:22
This has been implemented already. <kbd>ctrl</kbd>+<kbd>D</kbd> / <kbd>cmd</kbd>+<kbd>D</kbd> will work for multiline selections.

**Comment by hun1ahpu** [comment] 2016-12-12 18:06
@alexandrudima I'm not sure how ctrl+D is going to help. 
The problem in the issue is that you can't search for multi-line text (the text that spans over 2 or more consequent lines) without using regular expressions.
Ctrl+D if i understand correctly let's add next matching string into selection.

**Comment by alexandrudima** [comment] 2016-12-13 09:15
Interestingly, this works when seeding the find input via `ctrl+d` (programmatically), but does not work when pasting multiline text in the find input. Here I am doing `ctrl+d` followed by `ctrl+f`

![10588](https://cloud.githubusercontent.com/assets/5047891/21134202/004bc41a-c11d-11e6-86c4-716e50f593d2.gif)


Perhaps the find input dom node needs some multiline property set, or turned into a textarea. More work would be needed to make it auto-grow in height based on the number of lines it contains.

**Comment by alexandrudima** [comment] 2016-12-13 09:17
@hun1ahpu Also, the op does not clearly state what the specific problem is, i.e. it is left for interpretation what matching multiline occurences means. To me, it means `ctrl+d`, hence the label `beginner` and hence my closing the issue.

@ahmetalpbalkan What exactly do you mean?

**Comment by Anujan** [comment] 2016-12-30 20:24
@alexandrudima I think he means just by highlighting.
 
![vscode 10588](https://cloud.githubusercontent.com/assets/2387037/21572144/0bcdcd44-cea4-11e6-963e-66377127d1b3.gif)

**Comment by ahmetalpbalkan** [comment] 2016-12-30 20:53
Sorry for the latency here. I mean when I select multiline text, I should be able to ctrl+D to select other occurrences of the multiline text and be able to modify them together. You can see the Sublime Text for the desired behavior.

**Comment by mazamachi** [comment] 2017-08-19 08:10
I also want highlight when I select multiline (as @Anujan commented). Can I try fixing this?
As I am new to this repository, I would like to ask your comments about whether this feature is desirable.

**Comment by prog-rajkamal** [comment] 2017-10-01 15:54
@mazamachi 

 I took a look at the source code and this looks like a simple fix. If you don't mind, I want to try to fix this issue.

**Comment by varkor** [comment] 2019-09-07 12:12
The issue name should be updated to something like "Permit selectionHighlight for multiple lines". It does currently appear to be explicitly disabled (for no stated reason):
https://github.com/microsoft/vscode/blob/9089a79ecf76a25fccc7c232d80cdd374a7cc66e/src/vs/editor/contrib/wordHighlighter/wordHighlighter.ts#L320-L324
(Perhaps for performance reasons?)
It seems reasonable to up the line limit, make it configurable, or add a setting that enables multi-line selection highlighting.

With regards to how the feature should work, I think leading whitespace on each consecutive line should be ignored, to avoid false negatives with different indentations.

**Comment by dnlw07** [comment] 2020-02-19 17:37
Is it possible to add an option in setting to toggle multi-line selection?

**Closed** 2021-01-03 03:01 UTC
Labels: editor-find, feature-request
