### ISSUE TITLE
Alert or notify users when they hit the max line length supported by the editor

### ISSUE THREAD

**Issue by Calidus** [microsoft/vscode#74614] opened 2019-05-30 13:46 UTC
When the user paste or types text into the editor alert them when they hit the max length that the editor supports. 

User Story: I used JSON.stringify(someObject) which created a very long string. I copied that value and tried to paste it into code's editor. Code truncated the string and put three periods at the end of the line. I didn't know this until I tried to prettify the JSON and it failed.

**Comment by rebornix** [comment] 2019-05-30 23:42
@Calidus can you share some information about the json content you are copying, like length? There is no size limitation in the editor actually and we don't truncate the content from clipboard. So it would be great if we can have a stable reproduce.

**Comment by Calidus** [comment] 2019-05-31 12:14
I used the watch window to copy the value of the stringified object.

![image](https://user-images.githubusercontent.com/1683712/58704853-6463f800-837b-11e9-9e48-1d85ba3c6147.png)

Then I pasted it into the editor and scrolled to the end of the line:

![image](https://user-images.githubusercontent.com/1683712/58704934-a4c37600-837b-11e9-90e5-8df0fe6588c8.png)

The content was almost 11MB, when I pasted and saved it in notepad. Pasting it into Notepad did not truncate the value.

**Comment by Calidus** [comment] 2019-07-03 15:28
What other information would you like me to provide? I am still seeing this issue on version 1.35.1

**Comment by Calidus** [comment] 2019-07-08 18:52
So the editor won't display more than 10000 characters on a single line, this seems to be the root of the problem.

**Comment by Calidus** [comment] 2019-07-09 13:59
Turns out you can change this settings by editing the settings.json file [https://stackoverflow.com/questions/50862347/how-to-show-full-long-line-in-visual-studio-code-word-wrap-off/50863170#50863170](url)

I still believe some type of notification would be good to have for the user when the line length goes past the defined value in the settings file.

**Comment by rebornix** [comment] 2019-07-17 23:33
@Calidus sorry for not coming back quick as I was on vacation. If I understand correctly, the only issue you have right now is that the long line is not being displayed completely, instead of truncated?

**Comment by Calidus** [comment] 2019-07-18 12:14
Correct that data is still there it is just not rendered or accessible. Various extensions like those that prettify selected text also don't function properly because you can't select characters that are not rendered.

**Comment by rebornix** [comment] 2019-07-29 23:47
/duplicate of https://github.com/microsoft/vscode/issues/7772

**Closed** 2019-07-29 23:47 UTC
Labels: *duplicate, editor-rendering, feature-request
