### ISSUE TITLE
Markdown preview no longer shows images with whitespace in path

### ISSUE THREAD

**Issue by Platzer** [Microsoft/vscode#11933] opened 2016-09-13 07:35 UTC
- Visual Studio Code - Insiders
- Version 1.6.0-insider
- Commit 52bceb1207188ecfe8c5b1fbe841b60df512a08a
- Date 2016-09-12T06:10:26.275Z
- OS Version:

Steps to Reproduce:

1. Clone test repo https://github.com/Platzer/TestVscode-7898
2. Open Folder `TestVscode-7898` in VScode
3. Open `markdownfile.md` and preview

Issue is maybe related to #7898.

**Comment by mjbvz** [comment] 2016-09-27 20:25
This looks like a Duplicate of #7871 and #9555. The preview targets the CommonMark specification of markdown, which does not allow spaces in the link destination: http://spec.commonmark.org/0.26/#links

To work around this, try replacing spaces with `&#32;` in the name as per #7871 .

**Closed by mjbvz** 2016-09-27 20:25 UTC
Labels: duplicate, markdown
