### ISSUE TITLE
High CPU usage when just opening project folder

### ISSUE THREAD

**Issue by iamzhout** [Microsoft/vscode#17096] opened 2016-12-13 01:05 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 7 64bit

Steps to Reproduce:

1.  Open the project folder, and do nothing. (The project mainly consists of .java files)
2.  Can observe the CPU usage will jump from 10% to as high as 60%
3.  If more vscode window open with other project folder, the CPU usage will jump to more than 90%

the devtools console reports:
```
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

(1150) workbench.main.js:126 [FileWatcher] terminated unexpectedly (code: 2148734720, signal: null)
workbench.main.js:126 
e.onUnexpectedError @ workbench.main.js:126
(anonymous function) @ workbench.main.js:126
e.onUnexpectedError @ workbench.main.js:29
r @ workbench.main.js:29
e.onFileServiceError @ workbench.main.js:90
errorLogger @ workbench.main.js:90
e.onError @ workbench.main.js:89
(anonymous function) @ workbench.main.js:89
t.onExit @ workbench.main.js:89
(anonymous function) @ workbench.main.js:89
emitTwo @ events.js:106
emit @ events.js:191
ChildProcess._handle.onexit @ internal/child_process.js:215
```
note that the error number 1150 is continuous increasing at rate about 1/s.

the devtool CPU profile result for certain time period is as below:
```
22504.3 ms	22504.3 ms	(idle)	
1902.5 ms73.70 %	1902.5 ms73.70 %	spawn	
261.2 ms10.12 %	261.2 ms10.12 %	(program)	
102.1 ms3.96 %	106.9 ms4.14 %	normalizeSpawnArgumentschild_process.js:320	
24.6 ms0.95 %	1960.3 ms75.94 %	ChildProcess.spawninternal/child_process.js:267	
24.6 ms0.95 %	1960.3 ms75.94 %	exports.spawnchild_process.js:1	
24.6 ms0.95 %	1960.3 ms75.94 %	t.startWatcherworkbench.main.js:89	
24.6 ms0.95 %	1960.3 ms75.94 %	t.onExitworkbench.main.js:89	
24.6 ms0.95 %	1960.3 ms75.94 %	(anonymous function)workbench.main.js:89	
24.6 ms0.95 %	1960.3 ms75.94 %	emitTwoevents.js:1	
24.6 ms0.95 %	1960.3 ms75.94 %	emitevents.js:136	
24.6 ms0.95 %	1960.3 ms75.94 %	ChildProcess._handle.onexitinternal/child_process.js:181	
21.8 ms0.84 %	39.0 ms1.51 %	Socket._destroynet.js:459	
17.3 ms0.67 %	18.2 ms0.70 %	error	
12.9 ms0.50 %	12.9 ms0.50 %	(garbage collector)	
12.4 ms0.48 %	12.4 ms0.48 %	close	
12.4 ms0.48 %	64.7 ms2.50 %	emitNoneevents.js:1	
10.8 ms0.42 %	29.0 ms1.12 %	e.onUnexpe
```

**Comment by jrieken** [comment] 2016-12-13 08:03
@bpasero Is that a dupe of the infinite watcher launch/kill loop?

**Comment by bpasero** [comment] 2016-12-13 08:54
Yes looks like it: https://github.com/Microsoft/vscode/issues/16009

**Closed by bpasero** 2016-12-13 08:54 UTC
Labels: freeze-slow-crash, perf
