### ISSUE TITLE
upward menu can not keep open 

### ISSUE THREAD

**Issue by WangYuchenSJTU** [Microsoft/vscode#54983] opened 2018-07-25 05:17 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10 Enterprise version 1803 build 17134.167

Steps to Reproduce:

1. open explorer 
2. move the **OUTLINE** tab to the bottom of the VS code window
3. move the VS code window to the bottom of the screen
4. click **…** of **OUTLINE** tab
5. the **...** menu should be upward now, but it will close immediately
6. workaround: if you click and hold **…**, you can trigger upward menu items by release on them 

![vscodeuibug](https://user-images.githubusercontent.com/31466770/43179245-5ca78f20-9004-11e8-9f03-fc75143bfef2.gif)

This bug apply to any upward menu in side bar as far as I see. The cause of the bug **seems** to be that the position of upward menu (bottom-left corner) is set to the same as downward menu (top-left corner). Thus once an upward menu appear, you will immediately trigger a mouse release action on it and close the menu. 
![vscodeuibug](https://user-images.githubusercontent.com/31466770/43180881-fb69d8d6-900c-11e8-893e-4a3ea3e56672.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment] 2018-07-25 23:34
This only happens when using native menus.

**Comment by sbatten** [comment] 2018-07-26 17:08
duplicate of #52803

**Closed by sbatten** 2018-07-26 17:08 UTC
Labels: workbench-menu
