### ISSUE TITLE
Error applying any theme after last update

### ISSUE THREAD

**Issue by Beta6484** [microsoft/vscode#85006] opened 2019-11-18 05:31 UTC
After the last update the applied theme stopped working (One Dark Pro) and testing other themes returns the same error "Cannot read property 'id' of undefined".

- VSCode Version: 1.40
- OS Version: Windows 10

Steps to Reproduce:

1. Open vscode
2. Open extensions
3. Click on theme
4. Click on Set Color Theme

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2019-11-18 07:46
Looks like duplicate of #82610 (well done, bot)

**Comment by aeschli** [comment] 2019-11-18 08:11
closing as dup of #82610

**Closed by aeschli** 2019-11-18 08:11 UTC

**Comment by Beta6484** [comment] 2019-11-18 09:29
The duplicate problem quoted is October 15th, I work with vscode every day and this error occurred after restarting the application with the last update a few hours while I was working. After all, is there a solution?

**Comment by gjsjohnmurray** [comment] 2019-11-18 12:01
@Beta6484 are you able to try Insiders?

https://code.visualstudio.com/insiders/

**Comment by Beta6484** [comment] 2019-11-18 13:27
> @Beta6484 are you able to try Insiders?
> 
> https://code.visualstudio.com/insiders/

Just got a release (v3.0) with a fix for this issue, all working correctly now! Thank you very much for your attention :)

**Comment by Beta6484** [comment] 2019-11-18 13:28
> @Beta6484 are you able to try Insiders?
> 
> https://code.visualstudio.com/insiders/

I restarted vccode now and just got a release (v3.0) with a fix for this issue, all working correctly now! Thank you very much for your attention :)
