### ISSUE TITLE
Jupyter notebook toolbar on top of maximized panel

### ISSUE THREAD

**Issue by LK2341** [microsoft/vscode#179700] opened 2023-04-11 06:14 UTC
## Environment data
 
-   VS Code version: 1.77.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1000892223
-   Python Extension version (available under the Extensions sidebar): v2023.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 professional 22H2
-   Python and/or Anaconda version: Miniconda3 Windows 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When I toggle panel (Ctrl+J) and maximize it, the panel should cover the all the area on the right.

## Actual behaviour

However, if I first open a .ipynb file and then toggle panel and maximize it, the toolbar is on top of the maximized panel.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open any folder.
2. Create a .ipynb file and open it.
3. Toggle panel (Ctrl+J) and maximize it.
4. In my computer, I found the Jupyter notebook toolbar is on top of the maximized panel. Here is a GIF to show what happens.

![test](https://user-images.githubusercontent.com/130430855/231071369-6b08dd41-5a0e-4223-8025-437323437ab4.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.77.1, undefined, desktop)
Jupyter Extension Version: 2023.3.1000892223.
Python Extension Version: 2023.6.0.
Workspace folder d:\test
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTest'
info 13:44:33.526: LSP Notebooks experiment is enabled
info 13:55:49.987: Loading webview. View is notset
info 13:55:49.988: Loading web view...
info 13:55:49.989: Webview panel created.
info 13:55:51.531: Web view react rendered
```

</p>
</details>

**Comment by rebornix** [comment] 2023-04-11 17:23
The notebook widget is rendered outside of the grid view, and when maximizing the panel/terminal, it's not set to invisible or having it dimension shrunk to zero. Is this a regression from the grid system? @sbatten

**Comment by LK2341** [comment] 2023-04-12 01:23
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.77.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I've updated vscode to the lasted stable version 1.77.2 and the bug is still there.

**Comment by starball5** [comment] 2023-12-20 04:49
Is this not a duplicate of #179671?

**Comment by joaomoreno** [comment] 2024-01-12 10:36
@roblourens @rebornix @sbatten It's almost been one year of snowplowing. Let's move this to the Backlog if we have no plans on fixing it in the next week.

**Comment by sbatten** [comment] 2024-01-13 00:44
This cannot be fixed purely on the grid side of things because the notebook editor does not live in the grid but is controlled by something that does. We tell the editor layout that is no longer visible and its height is 0. The editor tells the notebook that it is no longer visible but gives it a height of 13. If the editor told the notebook the right height, things would work, or if the notebook listened to visibility changes and hid itself things would work.

**Closed** 2024-01-16 16:54 UTC
Labels: bug, workbench-editor-grid
