### ISSUE TITLE
weird highlight on javascript

### ISSUE THREAD

**Issue by WhiteCat6142** [Microsoft/vscode#5085] opened 2016-04-07 18:58 UTC
- VSCode Version:0.10.14-insider
- OS Version:Win7

Like below
if(s.indexOf("abc*:")===-1)continue;*

**Comment by Tyriar** [comment] 2016-04-07 19:21
What theme are you using and can you provide a screenshot?

**Comment by WhiteCat6142** [comment] 2016-04-07 20:10
![test](https://cloud.githubusercontent.com/assets/15012282/14365334/19226014-fd48-11e5-9474-7842a07cd71e.png)

**Comment by WhiteCat6142** [comment] 2016-04-07 20:17
I used Default(Dark+) theme,but theme doesn't affect this issue.
(Sorry for meanless code)

**Comment by Tyriar** [comment] 2016-04-07 20:19
Thanks :) this is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by Tyriar** 2016-04-07 20:19 UTC
