### ISSUE TITLE
Cell toolbar cutting of capital letters in rendered Markdown

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125335] opened 2021-06-02 20:38 UTC
![image](https://user-images.githubusercontent.com/4674940/120548883-be06bf00-c3a7-11eb-9510-5d352a71c419.png)

**Comment by misolori** [comment] 2021-06-02 22:52
Duplicate of #125167

**Closed by misolori** 2021-06-02 22:52 UTC
Labels: bug, notebook-layout, ux
