### ISSUE TITLE
Provide access to VS Code API in extension uninstall lifecycle hook

### ISSUE THREAD

**Issue by GabrielBB** [microsoft/vscode#45474] opened 2018-03-10 14:15 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce: Add this events to an extension code:

```
export function activate(context: vscode.ExtensionContext) {
vscode.workspace.getConfiguration().update('test', 'some text', ConfigurationTarget.Workspace);
}

export function deactivate(context: vscode.ExtensionContext) {
    vscode.workspace.getConfiguration().update('test', '', ConfigurationTarget.Workspace);
}
```

When it activates it updates but on deactivation it doesn't work. Im debugging and the code is running but with no effect. I also tried with ConfigurationTarget.Global.

**Comment by GabrielBB** [comment] 2018-03-10 18:39
Well, for now, I’m gonna put the settings as global and remove them after plugin uninstall thanks to this: https://stackoverflow.com/questions/49205613/how-to-execute-code-when-user-uninstalls-your-vscode-extension/49211345#49211345

**Comment by GabrielBB** [comment] 2018-03-11 04:44
I couldn't get it to work after extensions uninstall because the package "vscode" cannot be found when the uninstall hook executes my JS file with node.  I read that this is the normal behavior, i cannot use the vscode api in the uninstall hook then...

**Comment by sandy081** [comment] 2018-03-12 17:05
@GabrielBB Can you return the promise during deactivate and try?

```typescript
export function deactivate(context: vscode.ExtensionContext) {
    return vscode.workspace.getConfiguration().update('test', '', ConfigurationTarget.Workspace);
}
```

**Comment by GabrielBB** [comment] 2018-03-19 14:42
@sandy081 Just tried it, doesn't work. What i noticed debugging is that VS Code is not even waiting for the event code to fully execute. When i put a breakpoint in the return, it only lasts like 2 seconds, then the thread is getting killed or something. So for now, we cannot clean settings in deactivation nor in uninstall (https://github.com/Microsoft/vscode/issues/35006#issuecomment-372384164).

**Comment by sandy081** [comment] 2018-03-19 14:59
> What i noticed debugging is that VS Code is not even waiting for the event code to fully execute. When i put a breakpoint in the return, it only lasts like 2 seconds, then the thread is getting killed or something.

@alexandrudima Are you aware of this?

**Comment by GabrielBB** [comment] 2018-03-19 15:04
@sandy081 @alexandrudima I forgot to tell that this is happening while changing workspaces. I don’t know about other deactivation scenarios

**Comment by alexandrudima** [comment] 2018-03-29 12:35
This is as designed. The `deactivate` method is a place to clean up OS resources (kill spawned processes, etc.). It is not supported to initiate configuration edits and other such things. The reason is that the window renderer process does not wait for the extension host process. It goes down as soon as the user presses `x`.

**Comment by GabrielBB** [comment] 2018-03-29 13:36
@alexandrudima Understood. Well, i don't have options then since the uninstall hook can't access the vscode api. For now i'm manually going to the user settings json in your file system and editing it when the extension is uninstalled like this: https://github.com/GabrielBB/vscode-lombok/blob/master/src/uninstall.ts (Dirty solution lol) I will open a feature-request for vscodeapi in uninstall hook

**Comment by sandy081** [comment] 2018-03-29 16:21
@GabrielBB Makes sense. Please update the current issue to support for such api in uninstall hook.

**Comment by joaomoreno** [comment] 2018-07-17 08:29
An alternative is to declaratively mark settings which are meant to be deleted from the user settings file on uninstall.

**Comment by JimiC** [comment] 2018-09-07 10:33
Throwing an idea here. How about moving the `npm uninstall script` hook into the extension context, much like
```ts
export function uninstall(context: vscode.ExtensionContext) {
  // Execute uninstall code which has access to `vscode` API
}
```

**Comment by sandy081** [comment] 2018-09-11 10:53
@JimiC This does not help to update the configuration.

**Comment by sandy081** [comment] 2018-09-11 14:36
@JimiC I thought you just want to pass the context.

And we cannot pass complete VS Code API as it has too many methods which are not supposed to run during uninstall. 

If it is for clearing settings, why not VS Code do it out of the box when an extension is uninstalled like in [comment](https://github.com/Microsoft/vscode/issues/45474#issuecomment-405502972)

**Comment by JimiC** [comment] 2018-09-11 15:27
I hope you guys consider also that we are writing in the `globalState` too.

**Comment by GabrielBB** [comment] 2018-09-11 16:06
I also agree with the solution by @joaomoreno . I hope it is activated when extension is updated too. Just because if some setting was renamed in the newest version

**Comment by oreporan** [comment] 2019-03-09 17:12
any updates on this?
My extensions creates some workspace settings which I need to cleanup in case of uninstall

**Comment by GabrielBB** [comment] 2019-05-04 17:36
Any updates?

**Comment by sandy081** [comment] 2019-05-06 10:02
No updates yet.

**Comment by jdoklovic** [comment] 2019-09-25 19:13
Maybe I'm missing something, but shouldn't it be possible and fairly simple to add an uninstall hook with the exact same signature of the activate hook in the main extension file, **then** when a user clicks the uninstall button for the extension, simply ```await {extension}.uninstall(context)``` BEFORE actually doing the uninstall?

I'm not sure users understand that when they uninstall an extension, all of their user settings, workspace settings and globalState for the extension still exists.

**Comment by JimiC** [comment] 2019-09-26 10:30
The thing is that the uninstall hook works a bit unconventional.

From my observations the lifecycle goes like this:
1. User clicks `uninstall`
1. Extension marked as "obsolete"
1. On `vscode` restart `uninstall` script gets executed

On step 3 `vscode` can't call the extension as it's not loaded yet or it doesn't exist.

**Comment by jdoklovic** [comment] 2019-09-27 23:13
Right, but why not call extension.uninstall() when the user clicks uninstall to give the extension a chance to run cleanup routines, THEN mark it as obsolete and continue like it does today?

**Comment by GabrielBB** [comment] 2019-09-27 23:26
@jdoklovic + 1000

**Comment by jramsay** [comment] 2020-02-12 01:51
@jrieken: Is there currently a way to determine if an extension deactivate() is due to an uninstall? 

For Live Share I'm interested in disposing our vsls-agent.exe immediately after the _uninstall_ Live Share extension button is clicked. I could force kill our agent process on deactivate() if I could determine it was due to an uninstall. We keep our agent alive after reload for a few seconds so this impacts proper cleanup and can cause issues if a user attempts to reinstall the extension immediately after an uninstall (in this scenario the vsls-agent.exe in the target install path would still be locked).

**Comment by jrieken** [comment] 2020-02-12 07:28
afaik there is nothing to observe uninstall but a ping for @sandy081 for more insights

**Comment by sandy081** [comment] 2020-02-12 14:51
vscode:uninstall script is for post uninstall hook but this is called when extension is removed. We do not call it immediately after uninstall because the extension could be running on other windows.

**Comment by warrenbuckley** [comment] 2020-07-31 11:17
OK seems I have a related/same issue reported here - https://github.com/microsoft/vscode/issues/103688

**Closed** 2020-11-09 17:22 UTC
Labels: *out-of-scope, extensions, feature-request
