### ISSUE TITLE
Pressing Ctrl+W while renaming a file closes the active editor tab

### ISSUE THREAD

**Issue by teraflik** [microsoft/vscode#81144] opened 2019-09-19 07:45 UTC
Issue Type: <b>Bug</b>

While creating or renaming a file in the File Explorer, if Ctrl + W is pressed, the active editor window is closed, which looks like an unintended consequence of the keybinding.

The same keybinding (Ctrl + W) is disabled outside the editor's context, i.e. while any other pane is highlighted or any menu is opened, hence not closing the editor. But it seems to work while renaming a file in the File Explorer Tree, which ideally should not happen.

To reproduce the issue:
1. Start VSCode in any folder with some files in it.
2. Open any number of files from the File Explorer Panel.
3. Create a new file or rename any existing file in the File Explorer Panel.
4. Press Ctrl + W. The active editor is closed everytime you press Ctrl + W.

_If this is intended, sorry to bother, please close the issue._

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (0.61GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
swagger-viewer|Arj|2.2.2
EditorConfig|Edi|0.13.0
jsonnet|hep|0.1.0
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
Go|ms-|0.11.4
vscode-proto3|zxh|0.3.0

</details>

**Comment by IllusionMH** [comment] 2019-09-19 10:31
/question

> The same keybinding (Ctrl + W) is disabled outside the editor's context

I can't reproduce this issue - in my case editor tabs are closed every time - when I use Explores with keyboards, Typing commit message in VCS tab, typing/navigating in search panel. And when you check default shortcut configuration there are no `when` clause for this shortcut.

Terminal is of course an exception because it intercepts this keybinding.

If you really want to prevent this behavior you can disable default shortcut (second object) and add same shortcut with same action but with `when` clause.

```json
    {
        "key": "ctrl+w",
        "command": "workbench.action.closeActiveEditor",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeActiveEditor"
    }
```

Please let maintainers know if you are sure that this issue was closed by mistake.

**Closed** 2019-09-19 10:32 UTC
Labels: *question
