### ISSUE TITLE
Breadcrumb selection is broken

### ISSUE THREAD

**Issue by swatteau** [Microsoft/vscode#58079] opened 2018-09-06 15:25 UTC
- VSCode Version: 1.27.1
- OS Version: Linux x64

## Steps to Reproduce

1. Focus on the breadcrumbs menu
2. Use the up/down arrow keys to select any item in the list
3. Press the `Enter` key

## Expected result

Upon pressing the `Enter` key, the breadcrumbs menu should close and the editor should jump to the selected item.

## Actual result

Upon pressing the `Enter` key, the breadcrumbs menu stays open and the selection jumps back to the initial item (i.e. the one that is already highlighted at the time the menu is opened).

## Additional info

Does this issue occur when all extensions are disabled?: Yes
The bug is also present on 1.27.1-insider (commit `5944e81f3`).

**Comment by sambhare** [comment] 2018-09-06 15:40
Can confirm this is also the case on Windows x64. 
Pressing Ctrl+Enter does open the selected item in a new vertical split editor.

**Comment by swatteau** [comment] 2018-09-06 17:06
Pressing `Ctrl+Enter` works as expected for me as well.

As with `Enter`, pressing `Space` sends me back to the initial item but closes the breadcrumbs menu.

I can only make the `Enter` key work by first typing the first few letters of the symbol I want to jump to.

**Comment by jrieken** [comment] 2018-09-07 07:26
> Upon pressing the Enter key, the breadcrumbs menu should close and the editor should jump to the selected item.

Hm, I can't reproduce this. On what element are you pressing enter? A document symbol, a file, or a folder?

**Comment by jrieken** [comment] 2018-09-07 08:27
Do you have any special keybindings configured?

**Comment by swatteau** [comment] 2018-09-07 08:47
No, I try to stick as much as possible to the default keybindings so I have very few custom ones. Here they are : 

```json
[
    {
        "key": "ctrl+k ctrl+b",
        "command": "workbench.action.toggleSidebarVisibility"
    },
    {
        "key": "ctrl+k ctrl+j",
        "command": "workbench.action.togglePanel"
    },
    {
        "key": "ctrl+[Slash]",
        "command": "workbench.action.terminal.focus"
    }
]
```

**Comment by swatteau** [comment] 2018-09-07 08:59
I just made a test on a different computer with the same OS (Manjaro 17.1.12 KDE edition) and could reproduce the exact same problem. It was the first time VSCode was installed on this computer so there was no extension or custom settings.

When I have a bit more time, I'll try on a different OS.

**Comment by swatteau** [comment] 2018-09-07 14:07
I did a fresh install of Debian 9.5.0 with the Gnome desktop and VSCode 1.27.1 (no extension or custom settings) in a VirtualBox machine and got the same problem.

It might well be a Linux only problem but it is really easy to reproduce.

**Comment by jrieken** [comment] 2018-09-07 14:48
@bpasero this happens because on linux the list service doesn't 'eat' the enter (and then some other command happens)

**Comment by jrieken** [comment] 2018-09-07 14:53
Nah, not the list service but we somehow think that enter produces a printable character. That reveals the input box and moves focus. Then the list service, correctly, doesn't handle the enter anymore... 

<img width="615" alt="screen shot 2018-09-07 at 16 50 39" src="https://user-images.githubusercontent.com/1794099/45226145-6ef6d280-b2be-11e8-9f07-6ad421671f25.png">

**Comment by jrieken** [comment] 2018-09-07 15:06
Yeah, not so cool. Some background: It's quite hard to know what buttons on a keyboard and what combinations of those produce what character on screen. Therefore we have a little native node module that basically presses all buttons with all modifiers and returns the outcome "on screen". We build a lookup table from that information and us for this like this. That also explains why it is different on each OS, on each language, and keyboard. It seems that mac and windows don't produce a printable character but that linux produces `\n (13)` (which looks pretty correct to me).

I will update to logic to ignore certain outcomes... @swatteau @sambhare Thanks for the issue and please, please use [Insiders](https://code.visualstudio.com/insiders). I have made the change that caused this already a month ago and I would have loved that insider-usages would have caught this...

**Comment by swatteau** [comment] 2018-09-07 15:46
I'm not sure if I understand all the details of your investigation but just to let you know : at some point I tried to change the keybinding of the `breadcrumbs.selectFocused` action from `Enter` to something else (just in case there was something special about the `Enter` key). The result was still the same so I'm not sure if the fact that the character is printable has anything to do with this.

**Comment by jrieken** [comment] 2018-09-10 07:12
This is fixed is todays insiders: https://code.visualstudio.com/insiders/

**Comment by jrieken** [comment] 2018-09-10 14:36
Assigned to August Recovery for discussion.

**Comment by jrieken** [comment] 2018-09-11 08:44
Cherry picked the fix to the `release/1.27` branch

**Comment by jrieken** [comment] 2018-09-11 14:05
@swatteau @sambhare You guys try this with latest https://code.visualstudio.com/insiders/. Thanks

**Closed** 2018-09-11 14:04 UTC
Labels: breadcrumbs, bug, candidate, important

**Comment by sambhare** [comment] 2018-09-11 18:00
Tested on latest insiders, works great! Thanks for the quick fix!
