### ISSUE TITLE
Conflict between theme colors and user preferences

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/vscode#26303] opened 2017-05-09 11:39 UTC
- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4

**Steps to Reproduce:**

1. Set the `editor.lineHighlightBackground` and `editor.lineHighlightBorder` in a theme.
2. Set the `editor.renderLineHighlight`preference to `line`or `all` in user preferences.
3. The highlighted line is always shown as `all` because the `editor.lineHighlightBackground` setting has higher priority.

**Expected behavior:**

If the theme has colors set for the highlighted line for both background and border, it should only paint with the color selected in the user preferences.

Original report by @MariusVatasoiu on my theme: [vangware/dark-plus-material/issues/2](https://github.com/vangware/dark-plus-material/issues/2)

**Comment by aeschli** [comment] 2017-05-09 13:24
`editor.renderLineHighlight` is only about whether to show the current line in the editor and/or in the gutter (behind the scrollbar). 

But yes, there's an issue that you can't set border and background at the same time. This is a duplicate of #26017

**Closed by aeschli** 2017-05-09 13:24 UTC
