### ISSUE TITLE
VSCODE onFormatSave inserting custom spaces and not detecting indentation

### ISSUE THREAD

**Issue by basickarl** [Microsoft/vscode#17079] opened 2016-12-12 14:11 UTC
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04
Linux lnxkarlm 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce: I have no idea but I'll give you how the project is setup.

My issue is that vscode is automatically inserting 4 spaces into my code with formatOnSave when I open a new file which is already indented with 2 spaces.

settings.json
```
// Place your settings in this file to overwrite the default settings
{
  "editor.formatOnSave": true,
  "editor.fontSize": 13,
  "editor.insertSpaces": true,
  "editor.detectIndentation": true,
  "terminal.integrated.shell.linux": "/bin/bash"
}
```
working space:
```
// Place your settings in this file to overwrite default and user settings.
{
}
```

My files otherwise run on eslint with the following .eslintrc file:
```
{
  "root": true,
  "extends": "./node_modules/eslint-config-airbnb/base.js",
  "env": {
    "node": true,
    "es6": true
  },
  "rules": {
    // Relaxing, should remove them eventually
    "func-names": 0,
    "comma-dangle": 0,
    "no-unused-vars": [
      2,
      {
        "vars": "local",
        "args": "none"
      }
    ],
    "new-cap": 0,
    // Restricting
    "max-len": [
      2,
      100,
      2
    ],
    "arrow-parens": [
      2,
      "as-needed"
    ],
    "prefer-const": 2,
    "strict": 0
  },
  "globals": {
    "__rootDir": true,
    "describe": true,
    "before": true,
    "after": true,
    "it": true,
    "beforeEach": true,
    "afterEach": true
  },
  "parser": "babel-eslint"
}
```

I tried turning eslint off but the problem persists. 

How do i fix this? I first click on "Indent Using spaces" and choose "3". I then edit the file and save, this fixes the spacing from 4 to 3. Then I redo the step and select "2", edit and save and the file then rejumps to 2 spaces.

It states that my tab is set to 4 spaces. 

I don't understand as I have auto indentation set to true. Rest of the people in my project do not have any issues. Then again, none of them are using vscode.

Anymore info? Please ask!

**Comment by waderyan** [comment] 2017-01-12 01:27
@basickarl thank you for opening this issue and for the impeccable detail! 

I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/10335

**Comment by manast** [comment] 2017-01-13 15:24
I do not think this is a duplicate, I am suffering the same issue and it really is a PITA... I have been using Code for several years, and suddenly today this thing happens. Every time I save a modified file all the code is automatically indented to 4 spaces, even if the settings is explicitly set to 2 spaces, and also, why would the code be reformatted when saving? I don't want that...  My user settings:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.renderWhitespace": true,
    "javascript.validate.lint.comparisonOperatorsNotStrict": "warning",
    // Controls if the editor will insert spaces for tabs. If set to auto, the value will be guessed based on the opened file.
    "editor.insertSpaces": "true",
    "editor.tabSize": 2,
}
```

I am having the same issue when editing javascript or java...

**Comment by manast** [comment] 2017-01-13 15:32
For some reason is formatting on save (and formatting wrong), I cannot find a way to disable this function... :(

**Comment by manast** [comment] 2017-01-13 15:39
workaround for me was to roll back to code 1.5.3.

**Comment by basickarl** [comment] 2017-01-16 09:29
@manast I'll try a rollback and get back, see if it works.

**Comment by basickarl** [comment] 2017-01-16 09:33
@waderyan I checked the other issue and it's not related. We don't use TypeScript and the issue isn't affecting consistency. The formatting is consistent but it inserts 4 spaces instead of 2.

**Comment by waderyan** [comment] 2017-01-18 16:26
@basickarl understood. Thank you for investigating further. My mistake. Let me take a look at it again.

**Comment by basickarl** [comment] 2017-01-19 08:10
@waderyan No worries! Just ask if you need any information about my setup/build!

This affects me on both my laptops I must add. Both are running Linux (Ubuntu 16.04 [as stated above] and ElementaryOS Freya [which itself is based off of Ubuntu 14.04])

**Comment by mjbvz** [comment] 2017-04-11 22:43
@basickarl Are you still running into this issue with the latest VSCode release? 

If you are, please try collecting the TypeScript server log:

1. In VSCode 1.11, add a setting`"typescript.tsserver.log": "verbose"`
2. Reload VSCode and reproduce the issue
3. Run the `Open TS Server Log file command`
4. Share the output from there.

TypeScript powers both our JavaScript and TypeScript language features and provides document formatting functionality

**Comment by basickarl** [comment] 2017-04-12 08:02
@mjbvz I'll have a look into it!

**Comment by mjbvz** [comment] 2017-10-27 01:58
Closing this out. If anyone is  still running into this issue on the latest VS Code insiders builds, please open a new issue and I will take a look

**Closed by mjbvz** 2017-10-27 01:58 UTC
Labels: format, javascript, needs more info

**Comment by manast** [comment] 2017-10-27 07:38
As a complementary note, I managed to resolve my issue removing all config directories of VSCode in my mac, such as ~.vscode. After that the issue disappeared. Maybe some setting from version 1.5.3 that was incompatible with newer versions.
