### ISSUE TITLE
"editor.showFoldingControls": "always" option not effect on  version 1.17.2 (1.17.2).

### ISSUE THREAD

**Issue by hujianxin** [Microsoft/vscode#36705] opened 2017-10-22 15:00 UTC
"editor.showFoldingControls": "always" option not effect on  version 1.17.2 (1.17.2).

**Comment by yume-chan** [comment] 2017-10-23 02:15
Duplicate of #35839

**Comment by isidorn** [comment] 2017-10-23 08:10
@yume-chan Thanks, closing as duplicate

**Closed by isidorn** 2017-10-23 08:10 UTC
Labels: workbench
