### ISSUE TITLE
Open file/folder crashes VS Code in Ubuntu 24.04

### ISSUE THREAD

**Issue by erosman** [microsoft/vscode#213906] opened 2024-05-30 12:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Launch VS Code with an open folder
2. Select any of the following from the File menu and VS Code crashes immediately
  - Open File
  - Open Folder
  - Open Workspace from File

The following work:
- File -> Open Recent
- File -> New Window

The following causes a crash:
- File -> New Window -> Open File -> select a folder to open
- File -> New Window -> Open Folder -> select a folder to open

There could be an issue with the open file due to changes in GNOME 46 Nautilus.

**Comment by deepak1556** [comment] 2024-05-31 03:15
Can you confirm if the issue is present with latest insiders https://code.visualstudio.com/insiders

**Comment by erosman** [comment] 2024-05-31 04:39
> Can you confirm if the issue is present with latest insiders https://code.visualstudio.com/insiders

There is an error when trying to install.

![image](https://github.com/microsoft/vscode/assets/6458876/5bbda9e6-9deb-41ac-a128-fbfaf4483172)

**Comment by erosman** [comment] 2024-06-04 07:23
Can someone suggest a workaround for the time being?

**Comment by papanireal** [comment] 2024-06-04 09:40
Have the same issue with vscode installed through Ubuntu Snap. 
Tried the insiders and regular .deb packages and they work without the above mentioned issue.

**Comment by papanireal** [comment] 2024-06-04 11:42
> @papanireal Which version of Ubuntu are you using?

24.04

**Comment by erosman** [comment] 2024-06-04 14:36
I tried again with the latest `.deb` and there is still an error.

![image](https://github.com/microsoft/vscode/assets/6458876/41be81ea-a132-4bab-860c-2a5d1a619f80)

**Comment by Lexslogic** [comment] 2024-06-06 01:37
> Does this issue occur when all extensions are disabled?: Yes
> 
>     * VS Code Version: 1.89.1
> 
>     * OS Version: Ubuntu 24.04
> 
> 
> Steps to Reproduce:
> 
>     1. Launch VS Code with an open folder
> 
>     2. Select any of the following from the File menu and VS Code crashes immediately
> 
> 
>     * Open File
> 
>     * Open Folder
> 
>     * Open Workspace from File
> 
> 
> The following work:
> 
>     * File -> Open Recent
> 
>     * File -> New Window
> 
> 
> The following causes a crash:
> 
>     * File -> New Window -> Open File -> select a folder to open
> 
>     * File -> New Window -> Open Folder -> select a folder to open
> 
> 
> There could be an issue with the open file due to changes in GNOME 46 Nautilus.

I had the same problem since I updated VSCode today, it was instant closing, not even opening the main menu. What worked for me was uninstalling all vscode and autoremove after. Then, installing it from the official webpage .deb file, with that, I solve it

**Comment by erosman** [comment] 2024-06-06 05:49
@papanireal @Lexslogic Are you using Gnome 46 Wayland desktop?

> I had the same problem since I updated VSCode today, it was instant closing, not even opening the main menu. 

Same here after updating the VSCode from snap.

Next ....
- Uninstalled VS Code from App Center
- `autoremove --purge`
- Re-installed from App Center
- Same problem

Next ...
- Uninstalled VS Code from App Center
- `autoremove --purge`
- Downloaded `code_1.90.0-1717531825_amd64.deb` from https://code.visualstudio.com/Download
- Right-click -> Open With... -> GDebi Package Installer
- "Error: Dependency is not satisfiable: libglib 2.0-0 (>= 2.37.3)"
![image](https://github.com/microsoft/vscode/assets/6458876/85ab9669-f64e-4929-9152-8ed0b560137f)


### Error: Dependency is not satisfiable: libglib 2.0-0 (>= 2.37.3)

> [MySQL Workbench - Dependency Issue](https://forums.linuxmint.com/viewtopic.php?t=414160&sid=49b3301ad2ec9fd85f47b45a033f694c)
> You want the deb for ubuntu 22.04, not 23.10.

**Comment by erosman** [comment] 2024-06-06 07:36
See also:

- #212430
- #211762
- #204159
- #212494
-  #212633
- [VS Code Jupyter Crash Ubuntu 24.04](https://github.com/microsoft/vscode-jupyter/issues/15731)

**Comment by 0xfldr** [comment] 2024-06-06 11:27
I had the same issue for three days, but now the Vscode doesnt even start anymore
Please fix ASAP

**Comment by erosman** [comment] 2024-06-06 21:33
Does the following have any relevance?
If so, how can it be fixed?

`~/.config/Code/logs/20240607T005226/main.log`


> 2024-06-07 00:52:27.002 [info] update#setState idle
> 2024-06-07 00:52:27.935 [error] vscode-file: Refused to load resource /snap/code/159/usr/share/code/resources/app/extensions/theme-seti/icons/seti.woff from vscode-file: protocol (original URL: vscode-file://vscode-app/snap/code/159/usr/share/code/resources/app/extensions/theme-seti/icons/seti.woff)


However, there is no `/snap/code/159`

![image](https://github.com/microsoft/vscode/assets/6458876/14392bc4-7be7-4c1f-b1a5-638f36f43ad2)

**Comment by erosman** [comment] 2024-06-07 04:24
From [Visual Studio Code crashes on Ubuntu 22.04.4 LTS](https://stackoverflow.com/a/78588729/13086128)

> This also works (No need to reinstall or downgrade)
> 
> `code --in-process-gpu`

Above works for me too, although ...
```
$ code --in-process-gpu
Warning: 'in-process-gpu' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by arewageek** [comment] 2024-06-07 04:31
I got same issues today and have been unable to resolve this.
Vs code closes almost immediately I attempt to open it. I haven't installed any new extension since I last used it a few hours ago.

**Comment by arewageek** [comment] 2024-06-07 04:47
I just resolved mine now. I downloaded the deb file from vscode's site, installed it using:
`sudo dpkg -i [file_path/file_name.deb]`

This solved my isses:

Note: remember to uninstall the previous vscode you have before or after doing this avoid confusions

**Comment by erosman** [comment] 2024-06-07 09:43
I can also confirm that uninstalling via snap & manually installing `code_1.90.0-1717531825_amd64.deb` fixes the issue.

`sudo dpkg -i code_1.90.0-1717531825_amd64.deb`

It seems there is an issue with the `snap` code installation.

No errors in `~/.config/Code/logs/20240607T130517/main.log`

**Note:** Although I exported my settings and extensions before uninstal, `snap` uninstall didn't remove the extensions from `~/.vscode` and everything was there after manually installing above (which was great).

**Comment by valiko-ua** [comment] 2024-06-07 16:06
I also had VSCode crash but right now, after installing all the updates from apt-get and snap, VSCode works fine.
I didn't do any hacks to fix it myself (like disabling wayland, etc).

**Comment by thediveo** [comment] 2024-06-07 18:52
nope, snap code (160) is a total failure.

**Comment by gerardo-m** [comment] 2024-06-07 21:27
Same problem here:

vscode-file: Refused to load resource /snap/code/159/usr/share/code/resources/app/extensions/theme-seti/icons/seti.woff from vscode-file: protocol (original URL: vscode-file://vscode-app/snap/code/159/usr/share/code/resources/app/extensions/theme-seti/icons/seti.woff)

**Comment by OliverZott** [comment] 2024-06-09 14:23
Same here, but VS Code crashes immediately when starting it.

ubuntu 24.04
vs code 1.90

**Comment by illegal-instruction-co** [comment] 2024-06-10 08:34
> code --in-process-gpu

I had same issue and it also works for me.

**Comment by Olorunnisola01** [comment] 2024-06-10 13:12
If your VSCode crashes immediately you open it. Perhaps you have installed it through the App Center. To solve this issue, Uninstall VSCode from App Center and follow the following steps;

1) First, download and install the GPG key to trust packages from the Microsoft repository:
`wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
rm packages.microsoft.gpg`

2) Next, add the Visual Studio Code repository to your system's software sources list:
`echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list`

3) Finally, update your package lists and install Visual Studio Code:
sudo apt-get update
sudo apt-get install code


Following these 3 simple steps should definitely fix your issue. Have a great time coding with VSCode!

**Comment by eignatenkov** [comment] 2024-06-14 09:37
just updated the snap version, got 1.90.1 and it doesn't crash anymore

**Comment by jonaskahn** [comment] 2024-07-15 15:03
It's still crashed on Fedora even with the latest version :/

**Comment by vitorrios1001** [comment] 2024-09-20 12:11
> If your VSCode crashes immediately you open it. Perhaps you have installed it through the App Center. To solve this issue, Uninstall VSCode from App Center and follow the following steps;
> 
> 1. First, download and install the GPG key to trust packages from the Microsoft repository:
>    `wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ rm packages.microsoft.gpg`
> 2. Next, add the Visual Studio Code repository to your system's software sources list:
>    `echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list`
> 3. Finally, update your package lists and install Visual Studio Code:
>    `sudo apt-get update`
>    `sudo apt-get install code`
> 
> Following these 3 simple steps should definitely fix your issue. Have a great time coding with VSCode!

Thanks @Olorunnisola01 , it works perfect to me

**Comment by jonaskahn** [comment] 2024-09-24 06:40
The new veraion seems fixed problem

**Comment by postingforever** [comment] 2024-09-25 09:47
This is such a laughable problem to have for Microsoft when they can't stop bragging about how much they love open-source.

**Comment by asegarra** [comment] 2024-10-03 20:37
This is happening to me also with the latest snap version on Ubuntu 24.04, but it doesn't happen with all folders and of note it doesn't happen at all in Kubuntu 24.04 with plasma.

**Comment by jonaskahn** [comment] 2024-10-04 05:22
Who said it only happen on snap package is a liar. I am anti-snap person, it is a bug from VScode. Now they seems fix it

**Comment by edsonturbomkt** [comment] 2024-10-04 11:13
> I just resolved mine now. I downloaded the deb file from vscode's site, installed it using: `sudo dpkg -i [file_path/file_name.deb]`
> 
> This solved my isses:
> 
> Note: remember to uninstall the previous vscode you have before or after doing this avoid confusions

It solved for me. Thanks!

**Comment by BLKingLLC** [comment] 2024-10-05 13:55
None of those worked for me.  I removed via apt remove, reinstalled via dpkg -i with the latest deb, removed my recent folder, removed all vs folders from the home directory, rebooted, and nothing has worked. 
```
             /////////////                cuzimbob@pop-os 
         /////////////////////            --------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: Thelio thelio-b3 
   /////76767//7676767//////////////      Kernel: 6.9.3-76060903-generic 
  /////767676///*76767///////////////     Uptime: 15 mins 
 ///////767676///76767.///7676*///////    Packages: 2062 (dpkg), 11 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 2560x1080, 2560x1080 
///////////76767676//////7676//////////   DE: GNOME 42.9 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: 12th Gen Intel i7-12700K (20) @ 4.900GHz 
    /////767676767676767676767/////       GPU: Intel AlderLake-S GT1 
      ///////////////////////////         Memory: 10261MiB / 64058MiB 
         /////////////////////
             /////////////                                        
                                                                  


[1]+  Done                    code-insiders
```

It crashes as soon as I click the file menu.

**Comment by jakubgaba** [comment] 2024-10-05 16:58
Reproducing the issue is pretty easy... i uninstalled all extensions, nothing happened, i changed some settings in VScode nothing happened.
Gonna use for the moment different IDE

**Comment by shiqicao** [comment] 2024-10-07 01:06
hitting this issue again on 1.94.0 on ubuntu 24.04.1

**Comment by McBen** [comment] 2024-10-08 09:29
for me v1.94.0 freezes because opening `kdialog` will eat all memory

**Comment by jakubgaba** [comment] 2024-10-08 20:35
> Manually installing the deb file using: `sudo dpkg -i FILE_NAME` solved the problem!

This works perfectly i suggest to uninstall it from snap and install it from this official page [https://code.visualstudio.com/](url).
No need to downgrade it just click on .deb install and then use the command what @piedpipr wrote down. The case is closed

**Comment by BLKingLLC** [comment] 2024-10-09 00:46
APT auto-upgraded me to 1.95.0-insider today.  When I opened it up, I clicked the file menu, and bam! crash.  I ran ```sudo apt install code-insiders=1.93.0-1725459622```, and it downgraded to that version; when I opened it and clicked the File menu, nothing happened except the file menu opening.  So, it looks like anything greater than 1.93.0-1725xxx crashes.

**Comment by davideicardi** [comment] 2024-10-10 07:45
Some problem here. I have solved opening VS Code from the terminal (`code .`) on the right folder.

**Comment by jmp75** [comment] 2024-10-10 21:40
My most recent `sudo apt upgrade` brought xwayland as an uninvited guest. vscode terminal window started to be laggy, and there is lots of similar reports out there. I was trying to resolve an issue with laggy terminal following [this advice](https://github.com/microsoft/vscode/issues/169504#issuecomment-2014518757). It may or may not have improved things, but I still notice the "File..." menu crash described in the present issue.

## Environment

sourced from `deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main`

`code --version` with `alias code='code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland'`

```text
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
1.95.0-insider
a016ec9b66ffdd3ff0f831768b8e75be008a54e4
x64
```

`lsb_release -a`

```text
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

`echo $XDG_SESSION_TYPE`

wayland

**Comment by jmp75** [comment] 2024-10-10 22:44
downgrading to one of the 1.94 appears to resolve the "File..." crash issues:

```sh
apt-cache show code-insiders | grep Version
sudo apt install code-insiders=1.94.0-1727878717
```

**Comment by bradfox2** [comment] 2024-10-11 14:25
Still occuring with latest snap release on 24.04 when opening files on host machine.   Does not happen on remote servers.

**Comment by Le0nard** [comment] 2024-10-12 17:28
It keeps happening to me too with the latest version of VS 1.94.2 on my release: Ubuntu 24.04.1 LTS

**Comment by gititGoro** [comment] 2024-10-13 03:45
# Workaround until the fix comes in

Create a workspace file in the directory you want to open. In VScode, 
File -> Open Workspace from file...

Browse to the workspace file and open it.

To make a blank workspace file, open a VScode directory that already works for you. Save it as a workspace. Then copy the workspace file to the directory you want to open and rename the file to the name of the directory.

**Comment by 3vi1** [comment] 2024-10-13 22:57
> # Workaround until the fix comes in
> Create a workspace file in the directory you want to open. In VScode, File -> Open Workspace from file...
> 
> Browse to the workspace file and open it.
> 
> To make a blank workspace file, open a VScode directory that already works for you. Save it as a workspace. Then copy the workspace file to the directory you want to open and rename the file to the name of the directory.

I don't follow.  We can't use File->Open Workspace without crashing vscode, and a number of us doing certain types of development are not using workspaces at all.  And it still doesn't avoid the situation where we need to do things like File|SaveAs/NewFile/RevertFile/Preferences/OpenFolder/etc... and we will crash the app before we even think about it (I did this a half dozen times before downgrading).  The only workaround is to run an old version and that will quickly be a problem if you use certain extensions.

**Comment by jailan-ai** [comment] 2024-10-14 06:03
I have the same issue

**Comment by KNechaevWallarm** [comment] 2024-10-16 05:53
Faced the same problem (ubuntu 24). The reason was an installation way (from snap store) fixed by installing from official apt repository

**Comment by whoAmI-cslim** [comment] 2024-10-16 19:55
Not sure if this will help anyone else. I ran into this issue today. Every time I tried to click "File" -> "Open Folder..." it would cause vscode to crash. 

I opened the terminal, navigated to the folder that I wanted to open in vscode and simply typed "code *insert_filename*". Once it opened, I was able to then use "File" -> "Open Folder..." as I could in the past. 

I know this doesn't solve the issue per-say, but it seemed to fix the crash issue and allowed me to open folders again. 

**Ubuntu Version Info:**
```
> lsb_release -a

Distributor ID:	Ubuntu 

Description:	Ubuntu 24.04.1 LTS

Release:	24.04

Codename:	noble
```

**Comment by gribelu** [comment] 2024-10-16 20:24
> sudo apt install code-insiders=1.94.0-1727878717

This worked for me. It also seems to have something to do with the Copilot Chat extension but I'm not sure. I'm happy for now

**Comment by lucassith** [comment] 2024-10-17 06:27
arch linux, same happens for me

**Comment by andymacg** [comment] 2024-10-17 14:05
FYI there is another related issue where clicking "File" -> "Open Folder..." to any folder containing a .json file crashes VScode with different workarounds: https://github.com/MicrosoftDocs/intellicode/issues/520

**Comment by Shapedsundew9** [comment] 2024-10-19 21:31
Ubuntu 24.04 - suddenly doing the same for me today.

```
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic snap
```

Looks like a snap issue. Did

```
snap remove code
```

Then follow the instructions here to use apt: https://code.visualstudio.com/docs/setup/linux

Now all is well.

**Comment by IftikharZahid** [comment] 2024-10-20 02:25
> Ubuntu 24.04 - suddenly doing the same for me today.
> 
> ```
> Version: 1.94.2
> Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
> Date: 2024-10-09T16:08:44.566Z
> Electron: 30.5.1
> ElectronBuildId: 10262041
> Chromium: 124.0.6367.243
> Node.js: 20.16.0
> V8: 12.4.254.20-electron.0
> OS: Linux x64 6.8.0-47-generic snap
> ```
> 
> Looks like a snap issue. Did
> 
> ```
> snap remove code
> ```
> 
> Then follow the instructions here to use apt: https://code.visualstudio.com/docs/setup/linux
> 
> Now all is well.

My Problem Solved by this method. 
Thanks a lot..

**Comment by deltacastro** [comment] 2024-10-21 00:58
An alternative to open a folder in VSC, is using the Terminal. Go to the project path you need to open and use:

`code -n .`

**Comment by mohamad-hasan-sohan-ajini** [comment] 2024-10-21 17:33
installing with deb works for me

**Comment by dclgtm** [comment] 2024-10-22 08:13
> An alternative to open a folder in VSC, is using the Terminal. Go to the project path you need to open and use:
> 
> `code -n .`

was facing crash issue while using open folder option and `code porject-folder` seems to work.

```
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic snap
```

**Comment by maxmars** [comment] 2024-10-22 08:34
> Ubuntu 24.04 - suddenly doing the same for me today.
> 
> ```
> Version: 1.94.2
> Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
> Date: 2024-10-09T16:08:44.566Z
> Electron: 30.5.1
> ElectronBuildId: 10262041
> Chromium: 124.0.6367.243
> Node.js: 20.16.0
> V8: 12.4.254.20-electron.0
> OS: Linux x64 6.8.0-47-generic snap
> ```
> 
> Looks like a snap issue. Did
> 
> ```
> snap remove code
> ```
> 
> Then follow the instructions here to use apt: https://code.visualstudio.com/docs/setup/linux
> 
> Now all is well.

Ubuntu 24.04.1 .. This one solved the problem for me.

**Comment by Sartan4455** [comment] 2024-10-22 20:07
This is for vscode insiders, I install via apt.  Have the file menu crashes every time.  Ctrl-k ctrl-o works.
Description:	Ubuntu 24.04.1 LTS
Release:	24.04

apt list code-insiders                                                                                      
Listing... Done
code-insiders/stable,now 1.95.0-1729577238 amd64 [installed]


Version: 1.95.0-insider
Commit: defe52dc43e6f5d861f55600ff01f7553fac7eaf
Date: 2024-10-22T05:04:01.628Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Linux x64 6.5.0-44-generic

**Comment by itdsntwork** [comment] 2024-10-23 11:24
Running in verbose displays the error.

```
[101075:1023/142333.932239:FATAL:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[1023/141716.552067:ERROR:process_memory_range.cc(75)] read out of range
[1023/141716.553880:ERROR:directory_reader_posix.cc(43)] opendir /home/<user>/.config/Code - Insiders/Crashpad/attachments/7e9b5e85-d176-4b66-974d-278e49f5fcaf: No such file or directory (2)
```

**Comment by merl-dev** [comment] 2024-10-23 16:06
I had this problem yesterday, couldn't touch "File".  However, for some reason, reinstalled it today and it is working fine 
code-insiders client running
```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

1.95.0-insider
fe997185b5e6db94693ed6ef5456cfa4e8211edf
x64
```
connects to server also running code-insiders
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

1.95.0-insider
defe52dc43e6f5d861f55600ff01f7553fac7eaf
x64

```

**Comment by Sartan4455** [comment] 2024-10-23 16:38
I too installed today(apt xubuntu)

Description:	Ubuntu 24.04.1 LTS
Release:	24.04


Version: 1.95.0-insider
Commit: fe997185b5e6db94693ed6ef5456cfa4e8211edf
Date: 2024-10-23T05:06:13.568Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.5.0-44-generic

and the issue is no longer present - was it fixed by a different bug?

**Comment by rzhao271** [comment] 2024-10-23 18:09
Potential duplicate of https://github.com/microsoft/vscode/issues/230604, as merl-dev mentioned.

**Comment by itdsntwork** [comment] 2024-10-24 09:22
I got a full disk yesterday and started doing some desperate cleanup, and if I remember correctly I deleted contents of `/home/<user>/.config/Code - Insiders/User/workspaceStorage` and 
`/home/<user>/.config/Code - Insiders/User/History`

I found those folders to be ridiculously huge using the `Disk Usage Analytics` tool.

I'm not sure if this is a coincidence but after that, clicking file worked without crashing.

**Comment by ahmadw13** [comment] 2024-10-26 14:03
installing deb helped me, it seems like VSC is bugged in ubuntu app centre

**Comment by merl-dev** [comment] 2024-10-26 15:52
I did not mention that in both cases (client and server), `code-insiders`  was installed using snap and not apt/deb...

**Comment by deepak1556** [comment] 2024-10-28 07:09
Reports here had a mix of scenarios from two different bugs that affected [snap packages](https://github.com/microsoft/vscode/issues/230454)  as well as [deb](https://github.com/microsoft/vscode/issues/230604). Given both of them have been addressed in [latest insiders](https://code.visualstudio.com/insiders), I am closing this one. Please report if you are seeing otherwise.

**Closed by deepak1556** 2024-10-28 07:09 UTC
Labels: info-needed
