### ISSUE TITLE
Keep scroll position stable when closing a tab in the tab well

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#13001] opened 2016-09-29 13:32 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. open many files so that tabs are scrollable, have the first (left-most) tab active
2. scroll to the farthest (right-most) tabs
3. close a tab in that area
4. the whole tab bar scrolls back to the left-most position (active tab)

This leads to loss of focus and confusion. If I want to close multiple tabs there, I have to scroll to them each time I close one.

**Comment by bpasero** [comment] 2016-09-29 13:55
@PunchyRascal share a video? I think this behaviour is intentional if the first tab was active before opening the last one (we go back in MRU order and open it).

**Comment by PunchyRascal** [comment] 2016-09-29 15:11
![image](http://s14.postimg.org/fbx1opx0x/scrolling_tab_bar.gif)


I see no reason to generate focus to active tab since the tab never lost the focus, it is still open, I am just trying to close a few tabs at the end of the tab bar, I am not activating other tabs or closing active tab.

I edited the initial report for better clarity.

**Comment by bpasero** [comment] 2016-10-03 07:20
I am undecided how to best fix this because it might also cause in users reporting issues why the current tab is not revealed. I think eventually maybe it needs to boil down to a setting which sucks too. 

Maybe a delay could be added that after a close we only reveal the active tab after some timeout so that you can continue closing tabs without loosing context.

**Comment by PunchyRascal** [comment] 2016-10-03 08:51
But the active tab is still there, you are looking at it (its editor), while deciding to scroll *only* the tab bar to the right, on your own. Why should the editor force you to jump back each time you want to do something in that area? E.g. Netbeans don't do this.

The timeout idea seems even more confusing than the current situation.

The active tab could be re-revealed (if you think this behaviour is necessary, I don't) when you focus the editor again (since the active tab is still open there).

The question is, what are the benefits of the current implementation?

**Comment by bpasero** [comment] 2016-10-04 07:42
I hear you. Thus this is a fair and valid feature request 👍

**Comment by PunchyRascal** [comment] 2016-11-02 16:11
I would actually argue that this is a bug, it totally confuses you when you want to close a few tabs, and you're taken away for no reason.

**Comment by bpasero** [comment] 2017-03-08 16:41
@PunchyRascal  One of our explicit tab design decisions was to never show an editor without its context (aka without the tab it belongs to) as demonstrated here:

![image](https://cloud.githubusercontent.com/assets/900690/23713177/5c6e23dc-0425-11e7-89fc-97b8a3537b17.png)

I see the issue with rapidly closing multiple tabs that are not active, but I think once you leave the tabs area, the active one should get revealed.

I think https://github.com/Microsoft/vscode/issues/18965 is going a bit too much into the wrong direction. Can we not just track where the mouse is by listening to mouse enter / mouse exit on the tab and if we have to make the decision to reveal the active tab or not we just don't do it when the mouse is over a tab? On top of that I think we should then go ahead and reveal the tab when the mouse exists the tab area.

Does that make sense? Seems like a much simpler and better fix to me.

**Comment by PunchyRascal** [comment] 2017-03-08 17:07
Tracking mouse movement and restricting this fix to when user does not leave the tab area seems very confusing to me. 

I can only reiterate my previous comment https://github.com/Microsoft/vscode/issues/13001#issuecomment-251056419 - which I think addresses all the issues (no auto scrolling in tab bar on tab close, re-reveal of current file on editor focus).

**Comment by bpasero** [comment] 2017-03-09 05:48
@PunchyRascal but the editor is never loosing focus when you close an inactive tab. Do you mean to reveal again when the user clicks back into the editor?

**Comment by PunchyRascal** [comment] 2017-03-09 09:04
Well I just tried and I think it does lose the focus - but that of course depends on the definition of "losing focus" :) When I close any tab at all via mouse middle click and start typing, the open editor does not receive the keystrokes, so in a sense I would consider it not in focus.

**Comment by bpasero** [comment] 2017-03-09 09:29
@PunchyRascal that would be a severe bug, can you share a video? Here is how it works for me:

![panel-red](https://cloud.githubusercontent.com/assets/900690/23744062/303e4d76-04b3-11e7-8e34-05e3caa66374.gif)

(I am pressing the mouse middle click here to close)

**Comment by initialshl** [comment] 2017-03-09 11:10
It seems that the focus is lost when you close inactive tabs (using middle click or right-click menu), while closing your active tab activates the previous editor, hence the focus gained.

![vscode-tab-well-close](https://cloud.githubusercontent.com/assets/19281538/23747711/a61d379e-04fb-11e7-9ed6-98eb7ecae798.gif)

**Comment by PunchyRascal** [comment] 2017-03-09 11:25
It is difficult to demonstrate that the editor does not receive the keystrokes, but after closing the tab, I kept typing, but nothing happened.

![tab-bar-focus gif](https://cloud.githubusercontent.com/assets/821272/23748006/1faabdb4-04c2-11e7-9979-448aa9a07359.gif)

**Comment by bpasero** [comment] 2017-03-09 12:54
Oh yeah I can reproduce, that should be something to fix...

**Closed** 2017-03-09 15:12 UTC
Labels: feature-request, help wanted, workbench-tabs

**Comment by bpasero** [comment] 2017-03-09 15:13
Ok, let's see how it goes, I pushed a fix that ended up to be a larger refactoring (also for https://github.com/Microsoft/vscode/issues/22292) that is why I did not merge your PR. 

Let me know how it goes. The idea is that invoking close from within the tab container will not cause the active tab to be revealed (using the same flag to block revealing once).

**Comment by PunchyRascal** [comment] 2017-03-10 09:14
Just tried it, it's amazing, thanks :)

**Comment by bpasero** [comment] 2017-03-10 09:30
Cool. The only thing I am not doing, which maybe user might complain is that when focus moves back into the editor (if it was outside), we do not reveal the active tab. But that is actually also the behaviour today.

**Comment by isidorn** [comment] 2017-03-28 09:33
Adding verified by user
