### ISSUE TITLE
editor.selectionHighlight causing confusing highlighting noise when searching

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#62004] opened 2018-10-29 05:02 UTC
Issue Type: <b>Bug</b>

I'm using the search panel to search for text across an entire workspace. I have case sensitivty and whole word matching enabled. When I move selection through the results in the panel it opens the file containing the result for previewing. Because this selects the text of the current match, editor.selectionHighlight kicks in and highlights all the occurrances of the same text in the file. This doesn't respect the case sensitivity and whole word settings and ends up adding a ton of visual noise within the newly opened editor.

I'm reasonably certain this has not always happened and is a bug introduced recently. Also, this behavior does not match what happens when searching within a single editor, where spurious highlighting never occurs.

Ideally, selectionHighlight is disabled while the search panel is open. Or at the very least respects search settings so it isn't destroying the user's ability to see actual search results.

Expected (selectionHighlight disabled):
![image](https://user-images.githubusercontent.com/484784/47630179-9a4ab080-dafc-11e8-9a3a-defeb244416a.png)

Actual (selectionHighlight enabled):
![image](https://user-images.githubusercontent.com/484784/47630182-9e76ce00-dafc-11e8-9feb-e63f06f2f2d4.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.5
tortoise-svn|fan|0.1.1
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.9.1
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.93
PowerShell|ms-|1.9.0
code-settings-sync|Sha|3.2.0
shader|sle|1.1.4
Align|ste|0.2.0
unity-debug|Uni|2.6.6
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment] 2018-10-29 11:38
related #8050

**Comment by roblourens** [comment] 2022-12-13 23:57
The reason this works as expected in the editor find widget is that the selection highlight respects the editor's "match case" setting, which comes from the find widget but also affects cmd+D and the selection highlight.

Maybe we can set that option to match the search view in the editor when opening a search result. But it also makes sense that these two states are separate.

**Comment by eleanorjboyd** [comment] 2024-12-10 22:37
From Rob's comments it seems like this is expected behavior and thus a feature request to make this change. Since it is an old feature request with less than the required number of upvotes, I am closing it. Please let me know if you feel this is not the right course of action. Thanks!

**Closed by eleanorjboyd** 2024-12-10 22:37 UTC
Labels: feature-request, search

**Comment by akbyrd** [comment] 2024-12-10 22:54
Somewhere along the lines this got fixed.
