### ISSUE TITLE
Go to Definition says there are two definitions when there is only one

### ISSUE THREAD

**Issue by rob-ubnt** [Microsoft/vscode#53890] opened 2018-07-09 16:54 UTC
- VSCode Version: 1.25.0
- OS Version: macOS High Sierra Version 10.13.4

Steps to Reproduce:

1. Create a JavaScript file with nothing but the following very simple content:
    
    ```js
    const foo = bar => {
        console.log(`foobar`)
    }
    
    foo()
    ```
    
1. Place the cursor on `foo()`.
1. Click **Go** > **Go to Definition**.

Result: VS Code says there are two definitions:

![two-defs](https://user-images.githubusercontent.com/38537959/42464385-13084418-8366-11e8-8e3a-098359bcec2f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-07-09 17:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/24861

**Closed by mjbvz** 2018-07-09 17:17 UTC
Labels: new release, typescript
