### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by hyqhyq3** [Microsoft/vscode#6409] opened 2016-05-17 02:25 UTC
- VSCode Version: v1.1.0
- OS Version: Windows 7

Steps to Reproduce:

1. Check for updates
2. When network connection is bad, it will run the corrupted installer. I think it didn't check the downloaded installer's checksum.

**Comment by joaomoreno** [comment] 2016-05-24 08:59
Duplicate of #780.

**Closed by joaomoreno** 2016-05-24 08:59 UTC
Labels: bug
