### ISSUE TITLE
debugger shows incorrect value on hover when variable names nearly collide

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#19883] opened 2017-02-03 23:03 UTC
- VSCode Version: 1.9.0
- OS Version: osx, el cap

Steps to Reproduce:

1.  mkdir, init project, `npm i -S rxjs`
2. run a debug session on this file: https://gist.github.com/cdaringe/1f2aa8ee1adeef2a291b75870308022a
3. hover the mouse over `action$`, and note that it shows the value for `action`, which is against expectation

in the below example, you can easily see that `action` and `action$` are defined and in scope.  you can also see me hover over `action$` and that the popup renders the value for `action`.  you will _also note_ that the values listed at line end make the same mistake (i.e. line 29).  only the values the the debug pane on the left side of the screen show the correct values.
![screen shot 2017-02-03 at 2 57 47 pm](https://cloud.githubusercontent.com/assets/1003261/22611826/b2acc154-ea21-11e6-99a0-57a481ec7153.png)

**Comment by isidorn** [comment] 2017-02-06 15:12
Currently we are using a limited regex based word matcher which work across different languages.
In order to improve this the debug hover would need to have better language understanding.
Closing as a somewhat duplicate of https://github.com/Microsoft/vscode/issues/6042 and https://github.com/Microsoft/vscode/issues/2307

**Closed by isidorn** 2017-02-06 15:12 UTC
