### ISSUE TITLE
Settings editor: typing fast enough on open replaces my search with the previous one

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200941] opened 2023-12-15 09:58 UTC
Steps to Reproduce:

1.  have previously used the settings editor with a search input
2. close it
3. open it and quickly type before the previous search input comes in

=> 🐛 my search is replaced with the previous input

**Comment by rzhao271** [comment] 2023-12-15 17:39
Duplicate of #200085

**Closed by rzhao271** 2023-12-15 17:39 UTC
Labels: bug, settings-editor
