### ISSUE TITLE
Autocomplete/Intellisense not working

### ISSUE THREAD

**Issue by mahaveer0496** [Microsoft/vscode#30802] opened 2017-07-16 11:48 UTC
- VSCode Version: `1.14.1`
- OS Version: `Windows 10 Pro 64-Bit`

VScode stops showing suggestions after a few seconds. When VScode just starts everything works but after a few seconds its stops showing suggestions.

For example, when importing a module VScode used to show the available methods in that module or it would show the available methods for a function when `ctrl + space` was pressed but now it doesn't. Now it just shows the variables that I have used in that file.

I only use VScode for `React, React-Native` so this behavior is seen in JS files don't know about others.

Steps to Reproduce:

1. Maybe upgrade to latest version
2. Try to import some methods from a module or try to check available methods on a function

tried this `code --disable-extensions` to check but still getting that issue.
Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-17 16:36
@mahaveer0496 Can you please:

1. Check the `TypeScript` section of the output panel. Are there any errors printed?
1. Open the VSCode developer tools by running the `Toggle Developer Tools` command. Look in the console. Are there any errors printed there?

**Comment by PencilBow** [comment] 2017-07-17 23:18
Experiencing the same exact problem. 
environment:

- Windows 10 64bit
- VS code 1.14.1
- using react-native
- !!! using react-native-create-app
 
I highly suspect the create-app is the culprit as the issue does not show up when editing random .js files outside of my project folder.

When I checked my typescript console, it pooped out the following error.

> [Error  - 1:11:54 AM] 'occurrences' request failed with error.
> Error processing request. Project '/dev/null/inferredProject1*' does not contain document 'c:/users/cedri/appdata/local/microsoft/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
> Error: Project '/dev/null/inferredProject1*' does not contain document 'c:/users/cedri/appdata/local/microsoft/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
>     at Object.ThrowProjectDoesNotContainDocument (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:75718:23)
>     at InferredProject.Project.getScriptInfoForNormalizedPath (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77238:42)
>     at InferredProject.Project.getScriptInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77243:29)
>     at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76551:51)
>     at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76679:84
>     at Object.map (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1483:29)
>     at ModuleBuilder.getReferencedFileInfos (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76679:31)
>     at ModuleBuilder.updateFileReferences (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76708:42)
>     at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76693:30)
>     at ModuleBuilder.onProjectUpdateGraph (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76684:22)
> 

So far I haven't managed to find a solution through googling ...

**Comment by mahaveer0496** [comment] 2017-07-18 06:51
@PencilBow I don't use react-native-create-app or w.e but still get the problem so I think it is not the culprit.

**Comment by mahaveer0496** [comment] 2017-07-18 07:07
@mjbvz 
`typescript` section's output 
```
[Info  - 12:28:18 PM] Using tsserver from: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 12:28:18 PM] Forking TSServer
PATH: undefined
```
Dev Tools console output with `--disable-extensions` is empty
Dev Tools console output with extensions enabled is 

![screenshot 22](https://user-images.githubusercontent.com/23198481/28304553-c6221052-6bb5-11e7-96dd-c65ec44353b8.png)

**Comment by mahaveer0496** [comment] 2017-07-18 07:16
@mjbvz there are indentation problems with `Format document` as well
![capture](https://user-images.githubusercontent.com/23198481/28304794-ddd14924-6bb6-11e7-81fb-e7810fade6a2.PNG)

notice the indentation of `data, student, handleClick` , the last 2 are indented properly but `data` isnt

**Comment by PencilBow** [comment] 2017-07-18 10:34
@mahaveer0496 Seems the thing we have in common in the installation of flow (assuming from the extension you use). That said, I've tried uninstalling and configuring around and no results so far.

**Comment by MiyoAlpizar** [comment] 2017-07-18 10:52
I have the same issue after de update, weird thing btw, it used to work just once every time i opened the project, now it does not, I've tried uninstalling and reinstalling but no luck. =(

**Comment by mahaveer0496** [comment] 2017-07-18 17:26
@PencilBow yeah I've tried clean install, disable all extensions but no luck here either :(

**Comment by newtmitch** [comment] 2017-07-19 15:32
So because of the error I was seeing, I set `typescript.disableAutomaticTypeAcquisition` to `true` and restarted - the TS errors in the output went away for the same file that was having problems when it was set to its default of `false`. I tried it with a few more files from the server side of my project and it appears to be working so far. Interesting.

**Comment by mjbvz** [comment] 2017-07-19 21:33
Thanks. From the logs I believe this issue is a duplicate of #30425  / https://github.com/Microsoft/TypeScript/issues/17131 upstream. I'm working with the TS team to get a fix out soon

**Closed by mjbvz** 2017-07-19 21:33 UTC
Labels: duplicate, javascript, new release
