### ISSUE TITLE
JSON semantic selection: select line when expanding inside an array

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67346] opened 2019-01-29 10:09 UTC
Testing: https://github.com/Microsoft/vscode/issues/67277

See screen shot:

<img width="286" alt="capture" src="https://user-images.githubusercontent.com/1931590/51900678-33b48780-23b6-11e9-85e3-8a417c0a71af.png">

Expanding selection should now select the next line and then everything inside `[...]`

**Comment by dbaeumer** [comment] 2019-01-29 10:10
Same should happen inside of object literals.

**Comment by dbaeumer** [comment] 2019-01-29 10:12
May be we don't have enough keys left but wouldn't it make sense to distinguish between up/down arrow and left / right arrow. Left / right could then walk siblings up / down parents

**Comment by aeschli** [comment] 2019-01-29 10:19
> May be we don't have enough keys left but wouldn't it make sense to distinguish between up/down arrow and left / right arrow. Left / right could then walk siblings up / down parents

That would have to be a request for Joh...

**Comment by aeschli** [comment] 2019-01-31 08:53
Line selections are provided by the default selection provider. See https://github.com/Microsoft/vscode/issues/67383#issuecomment-459264666

mark as duplicate of #67383

@dbaeumer More keys seems to be unrelated to this. I suggest filing a new issue (for @jrieken) for this.

**Closed by aeschli** 2019-01-31 08:53 UTC
