### ISSUE TITLE
vscode extension develop webview Abnormal interface display

### ISSUE THREAD

**Issue by likui1123** [microsoft/vscode#208995] opened 2024-03-28 09:56 UTC
vscode version 1.81.1
**my html create a input** 

**The datalist option is not directly below the input**

![image](https://github.com/microsoft/vscode/assets/37236882/8273dde8-7a35-4c94-888e-b15f906359bf)

**in browser is normal**
![image](https://github.com/microsoft/vscode/assets/37236882/6df9bb62-3f8b-4f89-8326-93c7b5924975)

**Comment by mjbvz** [comment] 2024-03-28 19:12
Duplicate of [#129999](https://github.com/microsoft/vscode/issues/129999)

**Closed by mjbvz** 2024-03-28 19:12 UTC
