### ISSUE TITLE
The window is no longer responding in python language mode

### ISSUE THREAD

**Issue by jtr109** [Microsoft/vscode#56338] opened 2018-08-14 10:47 UTC
- VSCode Version: Version 1.26.0 (1.26.0)
- OS Version: macOS High Sierra version 10.13.6

Steps to Reproduce:

1. After I updated my vscode into the lasted version
2. I opened some file (more than one) with python code in my workspace.
3. The window freezed.
4. But I can still change to another window of vscode I had opened at time same time.
5. After I trying to click the frozen window. The dialog "The window is no longer responding" is shown and my CPU is full.
6. I try to get more information following [the comment in another issue](https://github.com/Microsoft/vscode/issues/30576#issuecomment-314995204) with developer tools.
7. I started it and clicked "stop" after reproduced the issue. The Profile could not stop and keep recording without anything report.
8. The crash neither logged in the app `Console` in mac.

Is there anybody can give me some help? Thanks!

Does this issue occur when all extensions are disabled?: Yes

-----

**update**:

The window frozen after I parsed the code below in a new file with python language mode. If I changed the language mode, it would not reproduced.

```python
record = {
    "headers": {k: str(v) for k, v in self.request.META.items() if k.startswith('HTTP_')}
}
```

-----

Some screenshot below:

![image](https://user-images.githubusercontent.com/13946679/44086753-1e9e9c9a-9ff0-11e8-983c-5de82ca663aa.png)

![image](https://user-images.githubusercontent.com/13946679/44086737-141a77d0-9ff0-11e8-8115-87a558165094.png)

![image](https://user-images.githubusercontent.com/13946679/44086939-c30f3136-9ff0-11e8-8a19-3aba5d6deb88.png)

![image](https://user-images.githubusercontent.com/13946679/44087474-88803b3a-9ff2-11e8-9b79-0fb9a73bfeb7.png)

![image](https://user-images.githubusercontent.com/13946679/44087365-34429374-9ff2-11e8-91bd-3a3b2b220d6c.png)

**Comment by jtr109** [comment] 2018-08-15 15:51
Try to provide more informations. I disabled all extensions include the python extension of vscode. Then I pasted the code and it reproduced again.

![image](https://user-images.githubusercontent.com/13946679/44157724-ade1a000-a0e5-11e8-9df6-c7b8f1fb506b.png)

**Comment by aeschli** [comment] 2018-08-15 16:01
duplicate of #56377

**Closed by aeschli** 2018-08-15 16:01 UTC
Labels: candidate, freeze-slow-crash, new release

**Comment by jtr109** [comment] 2018-08-15 23:13
@aeschli Thanks for solving it.
