### ISSUE TITLE
extra terminal history created after minimizing top sash

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#218925] opened 2024-06-27 16:14 UTC
1. open pwsh 7 (shell integration on, terminal experiment suggest disabled)
2. try scrolling up, and you should already be at the top.
3. `echo 'hello'`
4. still notice you can't scroll up to see anything else.
5. lower the sash until some of the text is out of the view.
6. Try scrolling up- there should be history above that just repeats your command a bunch (even though I only ran it max once before this take).

https://github.com/user-attachments/assets/9ab77cbd-453f-47f2-8e3a-0a4825eedc7b

**Comment by Tyriar** [comment] 2024-06-27 16:18
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/label terminal terminal-conpty windows

**Closed by Tyriar** 2024-06-27 16:18 UTC
