### ISSUE TITLE
Weird behavior when scrolling through the suggestion Dialog.

### ISSUE THREAD

**Issue by SyedMohammad-Hasan** [microsoft/vscode#144660] opened 2022-03-08 10:01 UTC
Issue type: <b>bug</b>

Weird behavior when scrolling through the suggestion dialog.  

https://user-images.githubusercontent.com/98533939/157211868-e6ad36b7-baab-4dfc-bf71-9afd8915d680.mp4

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0-insider
- OS Version: Linux x64 5.16.11-76051611-generic

**Comment by connor4312** [comment] 2022-03-08 16:28
I'm not sure I understand what the problem is from your video. When you're at the end of the suggestions list, hitting the down arrow again will wrap back to the top.

**Comment by SyedMohammad-Hasan** [comment] 2022-03-08 16:36
> I'm not sure I understand what the problem is from your video. When you're at the end of the suggestions list, hitting the down arrow again will wrap back to the top.

It's nothing. So, please do not focus on that part.

**Comment by connor4312** [comment] 2022-03-08 16:42
Oh, I see

**Comment by mjbvz** [comment] 2022-03-08 20:41
Duplicate of #144455

**Closed by mjbvz** 2022-03-08 20:41 UTC
Labels: suggest
