### ISSUE TITLE
Extension not Activating

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#104874] opened 2020-08-18 00:03 UTC
- VSCode Version: 1.48.0
- OS Version: Windows 10

When starting a debug session, the user is getting `Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate)`

The cpptools extension activates on the following:
```
"onDebugResolve:cppdbg"
"onLanguage:cpp"
"onLanguage:c"
```

They are opening a .c file and trying to start their launch session with a configuration with `"type": "cppdbg"`.

Does this issue occur when all extensions are disabled?: No

Is there any other information that may be helpful to investigate this issue?

------------------
Reporting on behalf of @JonJust
Related: https://github.com/microsoft/vscode-cpptools/issues/5975

**Comment by isidorn** [comment] 2020-08-18 09:07
@WardenGnaw thanks for reporting this, however we did not change anything in this area and I find it strange that all of a suddent it stopped working.
First of all, can you reproduce this, or just the user?
Can you reproduce with vscode insiders?

**Comment by weinand** [comment] 2020-08-18 09:15
@isidorn is "onDebugResolve:cppdbg" enough to activate an extension that provides the DA through factory code?
Was there a recent change in that area?

**Comment by isidorn** [comment] 2020-08-18 09:23
@weinand the only change which we did is to change order when we launch preLaunchTask, however that is only in Insiders and not in VS Code stable. So no other change that I am aware of.

Yes, even if the extension provides the DA through factory code we will still call the `onDebugResolve` since I believe the resolve configuration by providers will first be called [here](https://github.com/microsoft/vscode/blob/8a9659f3e352001e048937a775ebd04c3a69a104/src/vs/workbench/contrib/debug/browser/debugService.ts#L406) which will call the onDebugResolve activation.

**Comment by WardenGnaw** [comment] 2020-08-18 18:55
@isidorn I could not reprodouce this issue. However, is there any logs that @JonJust can get to show why this extension is failing?

**Comment by JonJust** [comment] 2020-08-18 18:57
> 
> 
> @isidorn I could not reprodouce this issue. However, is there any logs that @JonJust can get to show why this extension is failing?

Hi there! The console output appears as follows:

`Error: the description can't be converted into a problem matcher:
{
    "background": {
        "activeOnStart": true,
        "beginsPattern": "^.*debuggerReady.*$",
        "endsPattern": "^.*debuggerReady.*$"
    }
}

Error: the description can't be converted into a problem matcher:
{
    "background": {
        "activeOnStart": true,
        "beginsPattern": "^.*debuggerReady.*$",
        "endsPattern": "^.*debuggerReady.*$"
    }
}`

**Comment by weinand** [comment] 2020-08-19 08:38
@alexr00 do you recognise and understand the console output in the previous comment?

**Comment by alexr00** [comment] 2020-08-19 08:54
That output indicates that there is an invalid problem matcher. Specifically in this case it looks like the `problemMatcher` is missing a `pattern`.

**Comment by WardenGnaw** [comment] 2020-08-24 18:55
Would getting the output of `code --verbose` help with the activation issue?

**Comment by isidorn** [comment] 2020-10-30 14:24
Closing this as there was no action item from the discussion above.

**Closed by isidorn** 2020-10-30 14:24 UTC
Labels: debug, needs more info

**Comment by Dragon201701** [comment] 2020-11-27 04:11
Nope. I add `
"onDebugResolve": "cppdb",
            "onLanguage":"cpp",
`
Doesn't work.
