### ISSUE TITLE
Closing a group changes sizes of other group

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50675] opened 2018-05-29 14:25 UTC
Testing #50458

- add a new keybinding
```
    {
        "key": "Ctrl+0",
        "command": "layoutEditorGroups",
        "args": {
            "orientation": 1,
            "groups": [{ "size": 0.2 }, { "size": 0.2 }, { "size": 0.6, "groups": [{}, {}] }]
        }
    }
```
- invoke the keybinding: new empty groups are added with the sizes as specified
- close the group in the lower left corner
- the top group gets larger, and the middle group smaller: Strange

**Comment by bpasero** [comment] 2018-05-29 15:12
@joaomoreno this seems to be an issue in the grid widget

**Comment by joaomoreno** [comment] 2018-05-29 15:26
@bpasero This is very likely a dupe of #50564

**Closed** 2018-05-30 10:21 UTC
Labels: bug, workbench-grid
