### ISSUE TITLE
Setting `files.insertFinalNewline` inserts final newlines into notebook cells

### ISSUE THREAD

**Issue by fwcd** [microsoft/vscode#195223] opened 2023-10-10 08:17 UTC
Type: <b>Bug</b>

This felt a bit unexpected to me and I can't remember this happening in earlier versions of VSCode, so I would assume this is a regression: Setting `files.insertFinalNewline` should not insert final newlines into every cell of a Jupyter notebook. I use that setting to make sure that all files use a final newline in accordance with Unix conventions for files and in the case of notebooks I would expect it to save the underlying JSON file with a final newline, not the code cells themselves.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:13:10.518Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
ruby-debug|cas|0.3.5
vscode-eslint|dba|2.4.2
java-decompiler|dgi|0.0.3
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
curry|fwc|0.0.15
gyb|fwc|0.0.2
kotlin|fwc|0.2.32
go|gol|0.39.1
todo-tree|Gru|0.0.226
haskell|has|2.4.1
applescript|idl|0.25.0
latex-workshop|Jam|9.14.1
language-haskell|jus|3.6.0
openscad-language-support|Lea|1.2.5
restructuredtext|lex|189.3.0
vscode-clangd|llv|0.1.24
vscode-elixir|mjm|1.1.0
vscode-dotnet-runtime|ms-|1.8.0
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
hexeditor|ms-|1.9.12
remote-explorer|ms-|0.4.1
ppm-pgm-viewer-for-vscode|ngt|1.1.5
vala|pri|1.0.8
prolog|reb|0.0.4
ruby|reb|0.28.1
java|red|1.23.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1689
scala|sca|0.5.7
metals|sca|1.25.0
crates|ser|0.6.3
shader|sle|1.1.5
swift-lang|ssw|1.5.2
ninja|sur|0.0.1
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
errorlens|use|3.14.0
vscode-lldb|vad|1.10.0
non-breaking-space-highlighter|vik|0.0.3
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vim|vsc|1.26.1
debug|web|0.26.1
vscode-ruby|win|0.28.0
cuesheet|zgm|0.3.0

</details>

**Comment by Yoyokrazy** [comment] 2023-10-10 17:07
I believe this is close enough to the issue mentioned just above (#195011) to be closed as a duplicate. I will be looking into bringing in an `ipynb` specific override, as I see the value in having more granular control over the application of these whitespace related settings to notebooks.

> would expect it to save the underlying JSON file with a final newline

As for this, @fwcd, I believe that underlying JSON is already saved with a newline. Please file an issue if you are not seeing that happen.

**Closed by Yoyokrazy** 2023-10-10 17:07 UTC

**Comment by dime10** [comment] 2023-10-31 21:48
Would it be possible to reopen this issue?

I don't believe this issue is a duplicate of https://github.com/microsoft/vscode/issues/195011, because that issue is a feature request. However, the issue described here is clearly a bug, and I'm assuming bugs and feature requests are treated with different priorities.

**Comment by Yoyokrazy** [comment] 2023-11-03 17:48
Hi @dime10, thanks for your input on this issue. This issue isn't treated as a regression as the behavior was introduced intentionally and is just an adjustment to the way that the `files.xyz` whitespace settings are being respected within the different editor types. Discussions among the notebook team landed with us wanting to align cell-editor behavior with standard file editor behavior, and this led to the files whitespace settings being used in notebooks now. 

There will be a discussion in the future regarding a possible notebook-editor specific settings override, as it is clear that a number of notebook users are wanting the final newline behavior to be disabled at the minimum. If this behavior is causing any breaking behavior or is blocking anything that was previously functional, please let me know and I can take a look at this with a higher priority. For now, this will likely be addressed in a future iteration. 

This closed issue and #195011 are referring to the same behavior, and this issue has been closed in favor of tracking the conversation in that central location.

**Comment by RafalSkolasinski** [comment] 2023-11-04 14:11
> This issue isn't treated as a regression as the behavior was introduced intentionally

You may not call it a regression but for many people it is.

> ... blocking anything that was previously functional ...

It is basically blocks me from using notebooks via vs code as I would need to constantly changing `files.insertFinalNewline` back and forth....

**Comment by blakeNaccarato** [comment] 2023-11-07 00:04
Sorry for the noise, I'm cross-linking to the workaround I posted https://github.com/microsoft/vscode/issues/195011#issuecomment-1797050133 in the tangential open issue since it's relevant there, too.

**Comment by Yoyokrazy** [comment] 2023-11-07 17:21
Appreciate the input from folks. Currently working to push a quick change to separate the final newline behavior into a notebook specific setting until a solution or path forward for notebook specific settings is decided upon. I will update both this and the related issue with the setting name when things are merged.

> You may not call it a regression but for many people it is.

@RafalSkolasinski Hopefully this setting is able to fix your issues with newline behavior. For the sake of understanding the problem space, I would love to know what about the final newline inside code cells is becoming a blocker for you? In my mind this was a papercut as the worst behavior was a newline, but it's clear that this has a greater effect on many people's workflows.

**Comment by Yoyokrazy** [comment] 2023-11-07 21:13
This setting is now unreleased, so upon the next insider build you will be able to add the following to your settings json:

`"notebook.insertFinalNewline": false`

**Comment by ratulachakraborty** [comment] 2023-11-18 09:06
@Yoyokrazy By when can we expect this setting to be released? It would be really helpful

**Comment by Yoyokrazy** [comment] 2023-11-20 18:16
> By when can we expect this setting to be released? It would be really helpful

@ratulachakraborty could you clarify what you mean by released? This setting is already active in the current insiders build, however if you are referring to the stable release, the setting will be released with the next stable build of vscode (1.85) at the end of the month. Let me know if this doesn't quite answer your question.
