### ISSUE TITLE
SCM: Viewlet should improve "no repositories" messaging

### ISSUE THREAD

**Issue by stevehurcombe** [microsoft/vscode#61491] opened 2018-10-22 13:01 UTC
Issue Type: <b>Bug</b>

This is a new installation of VS Code and Git. 
I've reviewed other issues and I have verified the following:

1. Git can be found on the path. Git: Show Git Output displays:

  Looking for git in: C:\Program Files\Git\cmd\git.exe
  Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
  Looking for git in: C:\Program Files\Git\cmd\git.exe
  Looking for git in: d:\Program Files\Git\cmd\git.exe
  Using git 2.19.1.windows.1 from d:\Program Files\Git\cmd\git.exe

2. This is a brand new install of VS Code and a new install of Git.

3. The extension is enabled (I did try disabling and reenabling), no luck.

4. There are no icons on the source control pane, nor any ellipsis menus (...).

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3396)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by stevehurcombe** [comment] 2018-10-22 13:06
Screenshot.
![snap 2018-10-22 at 14 06 34](https://user-images.githubusercontent.com/2033186/47294010-b41f5b80-d603-11e8-8697-cacac8a0eafb.png)

**Comment by joaomoreno** [comment] 2018-10-22 21:08
Did you open a git repository at all?

**Comment by stevehurcombe** [comment] 2018-10-22 21:57
From with VS Code? No, there is no option to do that.

**Comment by stevehurcombe** [comment] 2018-10-23 12:45
I think this might just be a confusing message. I used the console to clone a repository and when I opened the folder in VS Code the source control pane worked as I expected it to. Once I closed the folder the same message reappeared. Coming from a Visual Studio & TFS world I was expecting a different experience. 

IMHO the message should clarify that Git is installed and functioning, you just need to used the console to clone a repository and open it...at least that's how I think it should work. Time to watch a few videos!

**Comment by pramodnitmz** [comment] 2018-10-26 18:03
click on extension type @disabled  you will see all disabled extension on of them will be git just enable(workstation)

**Comment by stevehurcombe** [comment] 2018-10-27 07:32
Thanks, I did that before posting. Have a look at my last comment. The widget gave the impression that it wasn't working, when it was.

**Comment by chrisweb** [comment] 2018-11-21 14:30
Actually just had the exact same problem

I opened vscode and it said "No source control providers registered."

![vscode_no_source_control](https://user-images.githubusercontent.com/297978/48847308-7ac44200-eda1-11e8-8dc4-5d8928c15a97.png)

So I googled vscode git support and followed the documentation: https://code.visualstudio.com/docs/editor/versioncontrol#_git-support

So I intalled git for window and ensured git was in the path, then just to be sure I restarted my PC

I reopend vscode and still had the exact same message "No source control providers registered.", so I assumed the git installation or something related to vscode was wrong, so I googled again and found this ticket first: https://github.com/Microsoft/vscode/issues/61522

in that ticket someone has the exact same problem, one comment said to press CTRL+SHIFT+P and then enter "Git: Show Git Output", which gave me:
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.19.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
```
so I realised vscode was indeed finding git, but somehow was expecting me to already have a git repo opened and finally the next comment of that ticket had the suggested solution which consisted off  manually creating a folder and do a manual git clone first,

So I went to the explorer opened a blank folder, then I opened a new vscode terminal panel, entered my git command, which opened the GitHub login window:

![vscode_git_login_window](https://user-images.githubusercontent.com/297978/48847341-93ccf300-eda1-11e8-8c08-133d89b40cb9.png)

and after login in it successfully cloned my repository and I could use git as expected.

Next time I reopened vscode it had finally realized that git is installed and working and hence did not show the "No source control providers registered." message anymore

in the ticket https://github.com/Microsoft/vscode/issues/61522 it says to come to this ticket here to see if the git workflow could be improved, this is why I wrote this explanation

So in my opinion it would be great if after installing git, vscode would at least show another message, even better would be if there was a button that says checkout your first repo or login to your git service provider and open a login panel, you click it, enter your credentials or the repo url and bam you are done :)

**Comment by bvandenbon** [comment] 2018-12-03 12:51
And that's also why I am here --> also confused about the "No source control providers registered".
I was just about to reinstall visual studio code, when I found this post. *pfew* :)

**Comment by ciscorucinski** [comment] 2019-01-19 06:20
I don't know if there is a difference between some of the images posted above. For example, @chrisweb has the Git Logo on his sidebar. I have also seen the 3 horizontal dots on some images. However, my VS Code is just like @stevehurcombe where there is no Git logo and not 3 horizontal dots.

There are no actions for me to take from the UI to fix this issue. That's just bad UX

**Comment by bvandenbon** [comment] 2019-01-19 12:52
I propose adding just a tiny bit more info.

> No source control providers registered. 
> Possible fix: clone a git repository in a terminal window.

where clicking the word terminal, will indeed just open a terminal.

**Comment by ciscorucinski** [comment] 2019-01-19 19:16
You know what people must do. They must clone a git repo. The set of commands to do that are very limited. 

Why not just allow users to enter in a `*.git` location and automatically clone the repo?

**Comment by KokoDoko** [comment] 2019-03-27 17:20
Has this issue been solved? I have suddenly been getting the `No source control providers registered` message when cloning an existing git repository. 

When using `Git: Show Git Output` in VS Code I get:
```
Looking for git in: usr/local/bin/git
Using git 2.17.1 from usr/local/bin/git
```
My repository is cloned from GitHub and has a `.gitignore` file. What else can I do to convince VS Code that a folder has version control?

**Comment by joaomoreno** [comment] 2019-03-28 07:13
@KokoDoko Did you configure `git.path`? If so, you forgot the leading `/` in `/usr/local/bin/git`.

**Comment by prageeth** [comment] 2019-04-08 08:08
SOLVED!!!

I just upgraded VS Code to the latest and had the same issue. What solved the issue? The solution posted by @pramodnitmz 

For some reason, during the upgrade the "Git" extension was disabled. All i had to do was go the the "extensions", then type `@disabled`. It will show all disabled extensions, in my case, "Git". Enabling the extension solved my issue.

**Comment by jamiecon** [comment] 2019-09-11 23:46
See https://stackoverflow.com/questions/46609255/git-missing-in-vs-code-no-source-control-providers for a sample of some confusion caused by this message.

**Comment by rhires** [comment] 2019-11-11 00:52
Just got moved to a new machine at work, and this issue popped up. I agree with someone who said that the message should say "Git is installed/working (whatever), but you're not in a git enabled repository. Would you like to create a new one or open a folder that has one?" well, that's the gist of it, anyway. And then those two options should be available for the user to act on...

**Comment by SnoopyGeeek** [comment] 2019-11-26 16:05
Hi, I solve this problem by changing the order of environment variables paths. Specifically, I move my desired searching scope of git upper and the problem just went away once I did so.

**Comment by rainabba** [comment] 2019-11-26 16:58
Fresh install of VSCode and Git on a brand new Windows 10 machine and despite git working in Terminal, PowerShell and WSL, AND the GitLab flow extension working, Source Control still reports "No source control providers registered". I've also tried after removing GitLab Flow and restarting just in case.

I have no disabled extensions. Authentication is working fine (I can use any of my terminals to successfully fetch). SmartGit works as expected when fired up (the point is to not have to though).

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
Git: 2.17.1 (WSL), 2.24.0.windows.2 (Windows)

**Comment by rainabba** [comment] 2019-11-26 17:14
As I'm now seeing "fatal: not a git repository (or any of the parent directories)", I wonder if it has nothing to do with Git or our projects, just the context the commands are run in.

**Comment by bowdenk7** [comment] 2020-01-16 19:10
Right now unless you are in a folder with an active source control provider, you get the following:
<img src="https://user-images.githubusercontent.com/820883/72374982-21635480-36c0-11ea-946d-82631fe57746.png" alt="alt text" width="300px">

I think we should be able to provide a little more direction. A user can be in a few different states when they're looking at this message:

- you want to use git
    - git is not installed
    - git is installed
        - not in a folder
        - in a folder without an initialized repo
- you want to use other version control (we'll call this svn/etc)
    - svn/etc is not installed 
    - svn/etc is installed
        - extension is not installed

## Proposal

First we detect whether there is a working git installation: 

**If we don't detect git installation** - show instructions on how/where to install git and a note about how to use other scm providers
<img src="https://user-images.githubusercontent.com/820883/72553646-03c3f580-384e-11ea-9fc4-a460abbc8d96.png" alt="alt text" width="300px">
Links:
  - [install git](https://git-scm.com/downloads)
  - [learn more](https://code.visualstudio.com/docs/editor/versioncontrol)
  - find and install - link to marketplace search `@category:"scm providers"`

**if we do detect a git installation** - we assume you want to use git
  - **if there isn't a folder open** - instruct the user to open a folder to get started (or clone a repository from GitHub?)
<img src="https://user-images.githubusercontent.com/820883/72554738-22c38700-3850-11ea-8feb-5cf34e8ded34.png" alt="alt text" width="300px">

`Clone from GitHub` would trigger the existing `Git: Clone` command 

  - **if there is a folder open with no `.git` folder** - provide the option to `git init` for the user
<img src="https://user-images.githubusercontent.com/820883/72554920-7c2bb600-3850-11ea-906d-3dc1ef1845e0.png" alt="alt text" width="300px">

**Comment by rhires** [comment] 2020-01-17 02:10
@bowdenk7 - I think you should just copy/paste what you wrote as a new request, because it's about much more than messaging. And this is a fantastic proposal!

**Comment by joaomoreno** [comment] 2020-02-17 11:18
@bowdenk7 Since https://github.com/microsoft/vscode/issues/89080 has landed, I have [adopted it in Git](https://github.com/microsoft/vscode/blob/cce81b98b9507b9f4baee1fcf4c9972e88d65a48/extensions/git/package.json#L1815-L1841). We now cover the following cases:

**Git extension is disabled**

![image](https://user-images.githubusercontent.com/22350/74649089-316aca00-517f-11ea-8172-85efae5a2830.png)

**No git installation found**

![image](https://user-images.githubusercontent.com/22350/74649057-22841780-517f-11ea-84d7-a3d8a568fcf9.png)

**No open folder**

![image](https://user-images.githubusercontent.com/22350/74649119-43e50380-517f-11ea-970d-9c3f56cc078d.png)

**No `.git` in current folder**

![image](https://user-images.githubusercontent.com/22350/74649157-56f7d380-517f-11ea-8650-1ec12c73bc56.png)

**No `.git` in current workspace**

![image](https://user-images.githubusercontent.com/22350/74649231-7262de80-517f-11ea-8e12-11d2b5810200.png)

**Closed by joaomoreno** 2020-02-17 11:18 UTC
Labels: feature-request, scm

**Comment by MadhaviGunapati610** [comment] 2020-02-18 10:22
> click on extension type @disabled you will see all disabled extension on of them will be git just enable(workstation)

Thank you. It is working perfect.
