### ISSUE TITLE
JS/TS: Multiline comment syntax doesn't handle */ if preceded by * on a newline

### ISSUE THREAD

**Issue by msikma** [Microsoft/vscode#64691] opened 2018-12-09 15:39 UTC
Issue Type: <b>Bug</b>

Create a Javascript multiline comment whose final line includes a `*`, any other characters, and finally a `*/`. Such as:

```js
/** Comment line 1
 * Comment line 2 */
const moreCodeHere = 'anything'
```

**Expected output:** the comment starts at `/**` and ends at `*/`. `moreCodeHere` has regular syntax highlighting.

**Actual output:** the syntax highlighter believes that the multiline comment is unclosed, so everything below it is highlighted as if it's a comment.

See example with working comments and one broken comment:

<img width="620" alt="screen shot 2018-12-09 at 16 33 27" src="https://user-images.githubusercontent.com/1507745/49699402-f3fccb00-fbd0-11e8-818c-7186f4ff405e.png">

[See source here.](https://gist.github.com/msikma/9018ae286f34b3999a58850d363336ef)

If one runs this small script in Node, it declares all three functions and logs all their names.

Note: if one changes the language of the document to Java, C, C++, CSS, PHP or any language that contains C-style multiline comments, the bug does not occur. As far as I can see it only happens with the Javascript and Typescript languages.

This affects Javascript and Typescript.

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3697)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.90GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-styled-jsx|bla|1.0.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
yarn-lock-syntax|mar|0.1.3
python|ms-|2018.11.0
cpptools|ms-|0.21.0-insiders
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
markdown-preview-enhanced|shd|0.3.11
fish-vscode|sky|0.2.1
ayu|tea|0.17.0

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-12-12 00:21
Duplicate of #64455

**Closed by mjbvz** 2018-12-12 00:21 UTC
Labels: insiders
