### ISSUE TITLE
Create folder GUI bug

### ISSUE THREAD

**Issue by Yurunsoft** [microsoft/vscode#90040] opened 2020-02-05 02:05 UTC
Issue Type: <b>Bug</b>

1. Right click
2. Create folder
3. input some chars
4. Press and drag to the left to release

GIF：

![GIF](https://user-images.githubusercontent.com/20104656/73804458-ce128c80-47bb-11ea-959a-0d44599914b5.gif)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.3.9
vscode-markdownlint|Dav|0.34.0
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
auto-js-vscodeext|hyb|0.2.3
composer|ika|0.7.1
markdown-shortcuts|mdi|0.12.0
hex-rgba-converter|med|1.0.4
php-namespace-resolver|Meh|1.1.8
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.41.2
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.49.0
remote-ssh-explorer|ms-|0.49.0
cpptools|ms-|0.26.3
Go|ms-|0.13.0
php-docblocker|nei|2.1.0
vetur|oct|0.23.0
vscode-php-getters-setters|php|1.2.3
minapp-vscode|qiu|2.2.2
java|red|0.55.1
vscode-xml|red|0.10.1
datetime|rid|1.0.5
code-settings-sync|Sha|3.4.3
vscode-java-pack|vsc|0.8.1
vscode-preview-server|yui|1.3.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by isidorn** [comment] 2020-02-05 09:13
I can not reproduce this.
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Yurunsoft** [comment] 2020-02-05 09:25
> I can not reproduce this.
> Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

reproduce too

![GIF](https://user-images.githubusercontent.com/20104656/73828553-60855100-47f9-11ea-90ed-700250303a46.gif)

**Comment by isidorn** [comment] 2020-02-05 09:57
I can not reproduce this both on macOS and Windows and I am doing the same thing as you.
Let's leave this open as see if more users hit this.

If you are interested in providing a PR which fixes this, here's a code poitner
https://github.com/microsoft/vscode/blob/1e057b73930c16738d31278a068b0d50eb476c28/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L362

**Comment by ishayle** [comment] 2020-02-09 09:37
reproduced as well, make sure you release the drag on the arrow icon.

**Comment by isidorn** [comment] 2020-02-11 09:53
@jeanp413 pushed a fix for this. Please try it out in VS Code insiders from Wednesday and let us know if you still see the issue. Thanks

**Closed** 2020-02-11 09:52 UTC
Labels: file-explorer, under-discussion

**Comment by Yurunsoft** [comment] 2020-02-12 02:49
@jeanp413 @isidorn 
Thanks, but have a new problem:
Input is cleared
![GIF](https://user-images.githubusercontent.com/20104656/74298660-4fc96380-4d42-11ea-9954-9121f7b395a3.gif)

**Comment by jeanp413** [comment] 2020-02-12 03:21
Yeah I also saw that, it's caused because when "expanding" the row element the tree refreshes and the previous value in the input is lost.
But I think that's not as critical as the previous behavior where the children got duplicated 😅
