### ISSUE TITLE
Slower startup performance

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117422] opened 2021-02-23 15:34 UTC
Between todays (bd74308b5abbbb2f5a5df0f0d8a3bef606652d36) and yesterdays (11cd76005bc7516dcc726d7389d0bce1744e5c85) insiders build we have lost around 300ms in startup time. The perf view  accounts this to 'connect to shared process'. 

> | connect to shared process                                       | 356      | [renderer]       | -                                       |

<img width="410" alt="Screenshot 2021-02-23 at 16 32 57" src="https://user-images.githubusercontent.com/1794099/108866770-cacf8600-75f4-11eb-8ba0-a4f93d3261d4.png">

**Comment by jrieken** [comment] 2021-02-23 15:49
Looking at the timer ticks it seems that something is happening very early on, after code loading is triggered and before the environment is asked for 😕 

<img width="1031" alt="Screenshot 2021-02-23 at 16 47 22" src="https://user-images.githubusercontent.com/1794099/108868747-d02dd000-75f6-11eb-928f-20afd8dba7e4.png">

**Comment by jrieken** [comment] 2021-02-23 15:57
The attached [Archive.zip](https://github.com/microsoft/vscode/files/6030067/Archive.zip) is two profiles of today and yesterday and it seems that time to load code just doubled 🤷 

<img width="531" alt="Screenshot 2021-02-23 at 16 55 46" src="https://user-images.githubusercontent.com/1794099/108869961-fbfd8580-75f7-11eb-83e5-096f1cade9d0.png">

**Comment by jrieken** [comment] 2021-02-23 16:01
Oh, I see. Looks like we updated Electron from 11.2.3 to 11.3

**Comment by bpasero** [comment] 2021-02-23 16:33
@jrieken it could still be my change that dropped the 3s delay for spawning the shared process. The impact of that is that the workbench window and shared process window will open almost at the same time (workbench will still start to load first). 

Btw, the time in the Perf editor maybe a bit misleading: we do NOT block the startup for the shared process connection yet since we do not need it for anything critical yet.

**Comment by deepak1556** [comment] 2021-02-24 05:23
The code loading difference should be a one off thing, can you try to take the profiles a couple of times. I got the same numbers https://github.com/microsoft/vscode/issues/117422#issuecomment-784305220 on windows and mac with both stable, insiders (11c) and (bd7).

Also I haven't noticed any differences in the numbers on my local testing. The only difference is the addition of new mark for `Connect to Shared Process`, can you confirm if that mark is not being counted towards the final ellapsed time which misleads the perf numbers given the shared process connection is async ?

**Comment by jrieken** [comment] 2021-02-24 07:13
> can you try to take the profiles a couple of times.

Of course I did that, the perf-machine also does that - that's why you ten entries in its row and first being much slower

**Comment by deepak1556** [comment] 2021-02-24 07:20
Does the `Connect to Shared Process` entry add up to the final elapsed time result ? That was added between the two insiders version.

**Comment by jrieken** [comment] 2021-02-24 08:20
No, it does not. Those are just arbitrary measurement between two "perf marks". Attaching the spread sheet I have from the perf marks (copy-paste the raw mark into excel). You can see that the marks are similar until code loading starts
[perf.xlsx.zip](https://github.com/microsoft/vscode/files/6034405/perf.xlsx.zip)

**Comment by jrieken** [comment] 2021-02-24 10:15
Telemetry shows similar results (for code loading and overall) @bpasero was `bd7` the first insiders build to include the faster shared process loading?

```
RawEventsVSCode
| where CommitHash == "11cd76005bc7516dcc726d7389d0bce1744e5c85" or CommitHash == "bd74308b5abbbb2f5a5df0f0d8a3bef606652d36"
| where EventName == "monacoworkbench/startuptimevaried"
| extend CodeLoadTime = toint(Measures["timers.ellapsedrequire"])
| extend Ellapsed = toint(Measures["ellapsed"])
| summarize percentiles(Ellapsed, 70, 95) by CommitHash
```


<img width="867" alt="Screenshot 2021-02-24 at 11 15 26" src="https://user-images.githubusercontent.com/1794099/108985693-9b228b80-7691-11eb-968a-317d1acbd859.png">

**Comment by bpasero** [comment] 2021-02-24 10:17
@jrieken @deepak1556 i pushed a change to move the shared process connection time to the end after workbench ready to make this a bit clearer:

![image](https://user-images.githubusercontent.com/900690/108985555-77f7dc00-7691-11eb-8d36-d32e0ae5377c.png)

The workbench does not await this connection. However given we now load 2 windows in parallel on startup, it is quite possible that the overall workbench loading time decreases. I am not sure that would explain slower code loading though, I would expect all numbers to be slower then.

If this reproduces locally, an easy test is to restore the delay we used to have and see if that helps:

```ts
this.lifecycleMainService.when(LifecycleMainPhase.AfterWindowOpen).then(async () => {
	await timeout(3000);
	this.afterWindowOpenBarrier.open();
});
```

in https://github.com/microsoft/vscode/blob/9d1e8fa608ae54b75fcddb609b20930c06620f33/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L54-L54

**Comment by jrieken** [comment] 2021-02-24 10:19
>  However given we now load 2 windows in parallel on startup, it is quite possible that the overall workbench loading time decreases. 

Telemetry actually suggests that's the case. Not sure what I am seeing for code loading, esp the `11c` build is weird because I see duplicated code-cache files that shouldn't exist..

> If this reproduces locally, an easy test is to restore the delay we used to have and see if that helps:

Can you please test that?

**Comment by bpasero** [comment] 2021-02-24 10:20
@jrieken yes that is the first build that includes this change: https://github.com/microsoft/vscode/commit/92c0878f39e8d8cad9c41615f96b4b4867687645

**Comment by bpasero** [comment] 2021-02-24 11:04
With https://github.com/microsoft/vscode/commit/01cfa2f8352f129fc922b2a9b3ec938f1bb93f84 I changed the delay away from "after first window opens" to "when first window connects". I hope this improves startup times, will run a new build now.

This is still not ideal because once shared process is required on startup, we don't want this waterfall. But I think it is better than having a random 3s delay because now:
* shared process will actually start sooner if the workbench is faster
* shared process will not slow down a super slow workbench that needs more than 3s

**Comment by deepak1556** [comment] 2021-02-25 02:06
I can't replicate the code loading issues on my system, I am gonna temporarily revert the electron version bump to see if it affects the perf bot. If it is isolated to just affecting older systems, can continue investigation accordingly with relevant trace data.

**Comment by deepak1556** [comment] 2021-02-25 07:29
Discussed with @bpasero offline, adding back the electron change. Plan is to monitor the change with shared process spawn logic that has been restored.

**Comment by jrieken** [comment] 2021-02-25 08:40
The last three insiders... Doesn't look like a good trend. Let's see what the perf machine says today

<img width="1080" alt="Screenshot 2021-02-25 at 09 39 27" src="https://user-images.githubusercontent.com/1794099/109126312-6411b000-774d-11eb-8131-15664cd00abb.png">

**Comment by jrieken** [comment] 2021-02-25 08:49
The comment above is a bad comparison because `93c` insiders is still too fresh (too little used). With @bpasero from yesterdays (`c47`) things are almost back to normal

<img width="1092" alt="Screenshot 2021-02-25 at 09 48 41" src="https://user-images.githubusercontent.com/1794099/109127371-a5ef2600-774e-11eb-8003-451c2084454e.png">

**Comment by bpasero** [comment] 2021-02-25 09:01
@jrieken interesting, that build doesn't even include latest change I did yesterday evening. Let's see what perf machine has to say today.

**Comment by jrieken** [comment] 2021-02-25 09:45
perf bot is happy with `59c31364c707ee962cc594389966801af4ce69bd` 👏 

<img width="430" alt="Screenshot 2021-02-25 at 10 45 29" src="https://user-images.githubusercontent.com/1794099/109134674-94aa1780-7756-11eb-9c75-4d53b6c1a776.png">

**Comment by bpasero** [comment] 2021-02-25 10:08
OK closing then. This might hit us in the future again depending on wether shared process becomes a blocking thing or not. Depends a lot on how fast we can make the shared process to start. The fact that it is a full `BrowserWindow` currently plays a role I guess.

**Closed by bpasero** 2021-02-25 10:08 UTC
Labels: important
