### ISSUE TITLE
Git checkout should create a tracking branch, if any remote contains a matching branch

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1329] opened 2015-12-15 11:34 UTC
Currently when you use quick open to "git checkout branch", the branch will be created even if the branch already exists in the remote. The command line does a better job and connects to the existing branch in that case.

**Comment by kelchm** [comment] 2016-05-18 15:08
This is related to #3385.  Definitely confusing behavior that will trip people up.

**Comment by joaomoreno** [comment] 2016-05-30 15:12
Closing as duplicate of #3385

**Closed by joaomoreno** 2016-05-30 15:12 UTC
Labels: feature-request, git
