### ISSUE TITLE
Unable to close PowerShell console from which "code ." have been executed

### ISSUE THREAD

**Issue by yooakim** [Microsoft/vscode#33256] opened 2017-08-28 12:23 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.3
docker-explorer|for|0.1.3
terraform|mau|0.0.16
PowerShell|ms-|1.4.1
vscode-docker|Pet|0.0.16

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open PowerShell session
2. Start code `code .`
3. Exit PowerShell console `exit`

The PowerShell session will not exit. here must be some session/process left behind wen starting code from the command line that prevents the PowerShell session from closing.

Reproduces without extensions: No

**Comment by ihalip** [comment] 2017-08-30 15:00
Repro'd with 1.15.1 on Windows 7. Mind if I look into this one?

**Comment by ihalip** [comment] 2017-09-01 18:35
@yooakim could you paste me the output of `Get-Command code`? Alternatively, could you check if setting the env variable `ELECTRON_NO_ATTACH_CONSOLE` to 1 before running code fixes your issue?

I've noticed I can consistently reproduce this issue when running the Code.exe binary in the install path but not when running the code.cmd batch script. This appears to happen because when running Code.exe directly the `ELECTRON_NO_ATTACH_CONSOLE` environment variable is not set.

**Comment by the-ress** [comment] 2017-09-27 08:41
I can reproduce this with code.cmd too.

I found out why it's happening, but I haven't got any solution (yet).

1. CLI `Code.exe` launches regular instance of `Code.exe` with `ELECTRON_NO_ATTACH_CONSOLE=1`  using `spawn` function. ([cli.ts#L94](https://github.com/Microsoft/vscode/blob/14699ba54eb57e73eb61a503421659eb04f41749/src/vs/code/node/cli.ts#L94))
2. `spawn` calls [`CreateProcessW`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx) with `bInheritHandles` set to true.
3. The new process isn't attached to the console, but inherits a few console handles keeping the console window open even when no process is attached to it anymore.

I tried setting a breakpoint on `CreateProcess` in WinDbg and changing `bInheritHandles` to false before continuing. Then it worked as expected.

Unfortunately the `bInheritHandles` value is hardcoded in Node ([process.c#L1084](https://github.com/nodejs/node/blob/8485a7c0b71fd1dd36947a6dd02b75387805d9b7/deps/uv/src/win/process.c#L1084)).

**Comment by joaomoreno** [comment] 2017-11-23 15:00
We won't fix this any time soon.

**Closed by joaomoreno** 2017-11-23 15:00 UTC
Labels: bug, help wanted, windows
