### ISSUE TITLE
Cannot right-click copy text from markdown preview window

### ISSUE THREAD

**Issue by rubinstuart** [microsoft/vscode#124829] opened 2021-05-28 12:24 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.56.2
- OS Version:Ubuntu 18.04

Steps to Reproduce:

1.Open a markdown file (.md)
2.Open the markdown preview window (F1, Markdown: Open Preview)
3.Highlight some text
4.Right-click and observe that no context menu appears, i.e. right-click does nothing.

Expected behavior is that when right-clicking, a menu appears with conventional options (copy, inspect, etc.).

**Comment by ArturoDent** [comment] 2021-05-30 04:23
I can reproduce this issue on W10 Stable but ***not*** in the Insiders Build:

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.21387

**Comment by mjbvz** [comment] 2021-06-12 00:27
Duplicate of #65310

**Closed by mjbvz** 2021-06-12 00:27 UTC
