### ISSUE TITLE
Git for Windows is never closed

### ISSUE THREAD

**Issue by Punishbear** [Microsoft/vscode#37535] opened 2017-11-02 16:04 UTC
Starting VS Code starts a background instance of "Git for Windows" which is never closed and eats up more and more RAM the longer it runs. Repeating this starts more and more instances, each eating more RAM over time.

- VSCode Version: 1.17.2 (x64)
- OS Version: Windows 10 Pro version 1511, Build 10586.1176

Steps to Reproduce:

1. Open VS Code
2. Close VS Code
3. Look at running background tasks
4. See an increasing number of "Git for Windows" instances with an increasing amount of used up RAM

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2017-11-06 14:01
Duplicate of #34684

**Closed by joaomoreno** 2017-11-06 14:01 UTC
Labels: git
