### ISSUE TITLE
Terminal closes instantly

### ISSUE THREAD

**Issue by SleeplessByte** [Microsoft/vscode#42523] opened 2018-01-30 18:09 UTC
- VSCode Version: Code - Insiders 1.20.0-insider
- OS Version: Windows_NT x64 10.0.16299

CPUs | Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3406)
-- | --
Memory (System) | 31.91GB (21.43GB free)
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%

Steps to Reproduce:

1. Startup
2. Open Terminal

Does this issue occur when all extensions are disabled?: Yes

Extension | Author (truncated) | Version
-- | -- | --
vscode-yarn-script | car | 0.0.1
vscode-eslint | dba | 1.4.4
tslint | eg2 | 1.0.24
code-runner | for | 0.8.7
ruby-linter | hoo | 1.0.0
docthis | joe | 0.6.0
vue | liu | 0.1.5
python | ms- | 0.9.1
csharp | ms- | 1.13.1
node-debug2 | ms- | 1.19.2
debugger-for-chrome | msj | 4.1.0
seti-icons | qin | 0.1.3
Ruby | reb | 0.16.0
PostCSS | ric | 1.0.1
vscode-icons | rob | 7.19.0
partial-diff | ryu | 0.5.1
vscode-react-native | vsm | 0.5.7
gitblame | wad | 2.2.0
ReactSnippets | xab | 1.7.0

Started happening today.

Opening terminal closes terminal instantly. No error messages in developer tools. No special characters in the path. All other tabs work (Ouput, Problems, Debug Console). 

Also happens when changing terminal to 
- git bash
- cmd.exe

Recently installed MSYS2 -- apart from that no terminal-like, no PATH additions.

NO errors in the developer tools. Only the following on startup:
```
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:253 [Extension Host] (node:49084) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead. (at Console.originalConsole.(anonymous function) [as error] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel-publishers\dist\src\console.pub.js:42:39))
```

**Comment by SleeplessByte** [comment] 2018-01-30 18:13
WORKS in the stable visual code studio:

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299

**Comment by maxibanki** [comment] 2018-01-30 18:14
I have the same issue with the Insider version.

**Comment by maxibanki** [comment] 2018-01-30 18:15
Duplicate of #42415

**Comment by SleeplessByte** [comment] 2018-01-30 18:21
@maxibanki I don't have those error messages.

**Comment by Tyriar** [comment] 2018-01-30 18:22
Should be fixed in latest insiders

**Closed by Tyriar** 2018-01-30 18:22 UTC
Labels: integrated-terminal
