### ISSUE TITLE
Feature Request: Allow root level configuration "defaultSnippets"

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#30834] opened 2017-07-17 06:59 UTC
Some extensions have very flexible and powerful configuration options, and sometimes these configuration options should be set together.

For example, for VS Code Power mode, I have included a few examples in the README of settings that when used together will have a certain effect. I'd like to make it easy for users to add those to their settings using snippets.

Ideally I would like users to be able to start typing "powermode" in settings.json and have a snippet suggestion show up that would complete to:

```
"powermode.enabled": true,
"powermode.enableShake": false
```

Unfortunately, the only way I've been able to do this is to create a "powermode" entry in my configuration like this:

```
"powermode": {
    "type": "object",
    "defaultSnippets": [
        {
            "label": "No shake",
            "body": {
                "enabled": true,
                "enableShake": false
            }
        }
    ]
},
```

The problem with this, though, is that the convention is to define settings in a single level, i.e. as "powermode.enabled" and "powermode.enableShake". I can go against this and define all my settings as properties on "powermode", but I'd rather not.

But there is one more reason why snippets in the root level are useful: It would allow people to contribute snippets that set settings across multiple extensions/built in settings.

In my case, "combos" in powermode rely on having the status bar visible, so adding `"workbench.statusBar.visible": true` might make sense.

**Comment by jrieken** [comment] 2017-07-17 09:47
dupe of #13182

**Closed by jrieken** 2017-07-17 09:47 UTC
Labels: workbench

**Comment by hoovercj** [comment] 2017-07-17 11:25
@jrieken I don't see how this is a dupe of that issue. I'm talking specifically about defaultSnippets contributed for settings.json, not about globally available snippets. These snippets should not show up for any other json files, and especially not in files that are not .json files

**Comment by jrieken** [comment] 2017-07-17 13:09
Yeah, please don't use the snippet word. If you want special suggestions just for `settings.json` you should write an extension that registered a completion item provider for just that file (the document selector supports that)

**Comment by hoovercj** [comment] 2017-07-17 14:04
I believe "snippet" is the correct word as it is what is used in the offical docs under the header ["Define Snippets in JSON Schemas"](https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas) which describes how snippets can be added to json schemas as values for a particular setting.

In the product today, working, I can say that a snippet should be offered as a completion for a particular key. In my example above, if I add the key "powermode" to the settings.json file, the snippet suggestion will appear.

This is a limitation, though, as it forces settings to be nested and does not allow snippets to be added across multiple root settings. My request here is this same syntax be supported at the root level of a configuration

In the meantime I can explore registering a completion provider
