### ISSUE TITLE
Delete Cell Diff View is empty

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#208563] opened 2024-03-25 08:20 UTC
Testing #208266

While Testing ^, I tried the steps to delete a cell and then view this action from the timeline view. Clicking on the Delete entry in the timeline view produced an empty diff editor:

<img width="1462" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/7cf08ffa-55d7-4aa7-8b91-f1572542e865">

**Comment by DonJayamanne** [comment] 2024-03-25 12:30
Duplicate of https://github.com/microsoft/vscode/issues/208564

**Closed by DonJayamanne** 2024-03-25 12:30 UTC

**Comment by DonJayamanne** [comment] 2024-03-25 12:31
>  Clicking on the Delete entry in the timeline view produced an empty diff editor:


This is how timeline entry works, you need to click the item before.
Peng and I also made the same assumption, however thats how how its designed to work (i.e. plain text files work this way, hence the statement `by design`)
