### ISSUE TITLE
Cannot collapse "Regions" or "Here Strings" in VC Code when working with the Microsoft PowerShell extension

### ISSUE THREAD

**Issue by EHBrant** [Microsoft/vscode#18787] opened 2017-01-19 14:29 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (215a0af33046d3940e665d46ecaeac9623f2f769, 2017-01-19T07:12:16.209Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.8.0|

---

Steps to Reproduce:

Hello 
With PowerShell code you can use #region and  #endregion which latter allows you to easily to collapse and expand sections of code.

Also Here Strings e.g.

@"
I am a here string
blah
blah
"@
are not seen as collapsible elements either

Can you please add the above functionality to make it far easier to work with PowerShell (and probably other extensions) in VS Code

Thanks in advance
ErnestBrant@outlook.com

**Comment by dbaeumer** [comment] 2017-01-20 07:47
@alexandrudima FYI.

**Comment by aeschli** [comment] 2017-01-20 10:40
duplicate of #3422

**Closed by aeschli** 2017-01-20 10:40 UTC
Labels: editor, editor-folding
