### ISSUE TITLE
There are task errors.Failed to create terminal for task compile.

### ISSUE THREAD

**Issue by qrqeea** [Microsoft/vscode#68532] opened 2019-02-12 16:10 UTC
Issue Type: <b>Bug</b>

I have two tasks name "compile" and "run".The task "run" depends on "compile".After updating to version 1.31 the task "run" doesn't work properly and it worked properly before updating.
Specifically,everytime I open the workspace,the task "run" can only run once.Then it shows "There are task errors.See the output for details" and "Failed to create terminal for task compile" if I run it again.However,the output shows nothing.
After some attempts,I find that this problems has something to do with tasks arrtibute "dependsOn".If I delete it,the problem disappears.However,it is not my intention.
My tasks are below.

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "compile",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "-std=c++11",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "${file}"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "echo": false,
                "focus": true,
            }
        },
        {
            "label": "run",
            "type": "shell",
            "dependsOn":["compile"],
            "command": "${fileDirname}/${fileBasenameNoExtension}",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "echo": false,
                "focus": true,
            }
        }
    ]
}

```
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (1.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
cpptools|ms-|0.21.0

</details>

**Comment by alexr00** [comment] 2019-02-12 16:35
Duplicate of #68077. The fix is already available in Insiders, and will go out to stable in the recovery build.

**Closed by alexr00** 2019-02-12 16:35 UTC
Labels: tasks
