### ISSUE TITLE
The install tip will show again after reload window

### ISSUE THREAD

**Issue by ZxBing0066** [Microsoft/vscode#33838] opened 2017-09-05 10:42 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.3
Angular2|UVB|0.4.1
string-converter|ada|0.0.9
Bookmarks|ale|0.16.0
markdown-preview-github-styles|bie|0.0.2
npm-intellisense|chr|1.3.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
githistory|don|0.2.3
python|don|0.7.0
es7-react-js-snippets|dsz|1.1.0
gitlens|eam|4.4.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.15
prettier-vscode|esb|0.23.1
vsc-travis-ci-status|fel|1.1.0
vscode-npm|fkn|3.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
webpack|jer|2.0.2
sublime-babel-vscode|jos|0.2.8
Go|luk|0.6.63
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.2.1
vscode-icons|rob|7.12.0
markdown-preview-enhanced|shd|0.2.8
sync-rsync|vsc|0.18.0
vscode-todo-highlight|way|0.5.11
webpack-progress|wk-|0.0.8
JavaScriptSnippets|xab|1.4.1

(7 theme extensions excluded)

---

Steps to Reproduce:

1. click install button on the store page, like https://marketplace.visualstudio.com/items?itemName=joshpeng.theme-charcoal-oceanicnext
2. back to vscode will see the tip of install the plugin and the store page 
3. close the tips and the page, reload the window, or just click the install button then reload, the tip and the store page will show again

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment] 2017-09-06 00:46
@ZxBing0066 

Can you share screenshot of the tips and the store page you are seeing in vscode?

**Comment by ZxBing0066** [comment] 2017-09-06 02:35
![image](https://ws2.sinaimg.cn/large/006tKfTcgy1fj9mzb13mlj31hq0qa77w.jpg)

I have clicked the install button, and close the store page, but when I reload the window, this will show again.

**Comment by ramya-rao-a** [comment] 2017-09-06 16:31
Do you see this with other extensions as well? 
Try installing any other extension.

**Comment by ZxBing0066** [comment] 2017-09-07 10:48
1. Open marketplace
![](https://ws2.sinaimg.cn/large/006tNc79gy1fjb6se6288j30xb0gdmyf.jpg)
2. Click install
![](https://ws2.sinaimg.cn/large/006tNc79gy1fjb6skb118j30ih06oq36.jpg)
3. Show tips in the vscode
![](https://ws2.sinaimg.cn/large/006tNc79gy1fjb6t2q82dj31il08lglw.jpg)
4. Close the tips
![](https://ws3.sinaimg.cn/large/006tNc79gy1fjb6tizquoj30r405idg1.jpg)
5. Reload windows
![](https://ws3.sinaimg.cn/large/006tNc79gy1fjb6u585iyj30p802vt8k.jpg)
6. The tips show again
![](https://ws2.sinaimg.cn/large/006tNc79gy1fjb6ub56zoj31ju06xweq.jpg)

This is very easy to Reproduce

**Comment by ramya-rao-a** [comment] 2017-09-08 01:05
Thanks @ZxBing0066 

I kept installing the extension and so couldn't repro.

**Comment by ramya-rao-a** [comment] 2017-09-25 17:53
The root cause for this is same as that for #34404
Closing this in favor of #34404

**Closed by ramya-rao-a** 2017-09-25 17:53 UTC
Labels: bug, duplicate, extensions
