### ISSUE TITLE
Garbled code output

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#13416] opened 2016-10-10 10:23 UTC
![h r v6wspvdg 3 u3zz rn](https://cloud.githubusercontent.com/assets/3353702/19233173/7c720380-8f16-11e6-9eb4-9a5a8597121d.png)
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by isidorn** [comment] 2016-10-10 13:03
Please provide exact steps how you end up in such output so we can reproduce the issue on our side. Do you also get that output if you run that command in a terminal.
In what exact vscode window do you see the garbled output?

**Comment by ydcoming** [comment] 2016-10-10 13:07
I compiled the typescript language, or ctrl+shift+b, my computer did not install the typescript environment

**Comment by ydcoming** [comment] 2016-10-10 13:07
我编译typescript 语言，或者ctrl+shift+b，我的电脑上没有安装typescript环境

**Comment by ydcoming** [comment] 2016-10-10 13:08
The terminal will not appear garbled

**Comment by isidorn** [comment] 2016-10-10 13:32
Our ansi output is pretty limited, I belive this is a duplicate of https://github.com/Microsoft/vscode/issues/8717

**Closed by isidorn** 2016-10-10 13:32 UTC
Labels: needs more info
