### ISSUE TITLE
Validation Check Failure in vscode yumrepo (linux)

### ISSUE THREAD

**Issue by Nickibubi** [microsoft/vscode#82347] opened 2019-10-11 09:40 UTC
- OS Version: OpenSuse Tumbleweed 20191007

Steps to Reproduce:

1. Get GnuPG key from https://packages.microsoft.com/keys/microsoft.asc 
2. Try to install vscode from https://packages.microsoft.com/yumrepos/vscode
3. Receiving Validation Check Failure:

"File repomd.xml from repository Visual Studio Code https://packages.microsoft.com/yumrepos/vscode
is signed with the following GnuPG key, but the integrity check failed: 

ID: EB3E94ADBE1229CF
Fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
Name: Microsoft (Release signing) <gpgsecurity@microsoft.com>
Created: 10/29/2015
Expires: Never

The file has been changed, either by accident or by an attacker,
since the repository creator signed it. Using it is a big risk
for the integrity and security of your system."

**Comment by blizzy78** [comment] 2019-10-11 12:46
Looks like a duplicate of #82317.

**Closed** 2019-10-11 13:13 UTC
Labels: *duplicate
