### ISSUE TITLE
Multiple item selection in explorer

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#34476] opened 2017-09-15 16:10 UTC
For deleting and reorganizing it would be nice to be able to select multiple files/directories in the explorer by holding down a modifier key while selecting.

**Comment by isidorn** [comment] 2017-09-18 09:24
Duplicate of https://github.com/Microsoft/vscode/issues/1023

**Closed by isidorn** 2017-09-18 09:24 UTC
Labels: workbench
