### ISSUE TITLE
Javascript Nullish coalescing operator syntax highlighting

### ISSUE THREAD

**Issue by donald-lendit** [microsoft/vscode#77974] opened 2019-07-26 08:07 UTC
## Title is description :D
This is an issue already have. https://github.com/Microsoft/vscode/issues/62872
I will ask you again because became `stage 3`. 

I would appreciate your consideration. thank you

TC39 - Nullish Coalescing
https://github.com/tc39/proposal-nullish-coalescing

**Comment by ChromeQ** [comment] 2019-07-29 12:39
For the time being I would recommend installing the VSCode extension: https://marketplace.visualstudio.com/items?itemName=Levi.nullish-coalescing-operator-grammar

**Comment by donald-lendit** [comment] 2019-07-29 13:28
> For the time being I would recommend installing the VSCode extension: https://marketplace.visualstudio.com/items?itemName=Levi.nullish-coalescing-operator-grammar

Thank you for your recommendation but.. unfortunately it's not working correctly on VueJS template and Script area.

**Comment by mjbvz** [comment] 2019-08-12 18:05
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/522

**Closed by mjbvz** 2019-08-12 18:05 UTC

**Comment by bondparkerbond** [comment] 2019-08-12 22:46
@mjbvz While Nullish Coalescing is a complementary proposal to optional chaining, they are two different proposals. [Nullish Coalescing](https://github.com/tc39/proposal-nullish-coalescing) and [Optional Chaining](https://github.com/TC39/proposal-optional-chaining) are both at stage 3, so it would make sense to implement them both together. However, they are two different proposals with different functionality, so I am unsure if they should both be tracked in the same [issue 522](https://github.com/microsoft/TypeScript-TmLanguage/issues/522)?
