### ISSUE TITLE
Cannot install VSCode Helper on new Mac, cannot update Insiders Build

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#32206] opened 2017-08-10 00:21 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:43:56.658Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Got a new MacBook Pro 15" 2017
2. Restored all apps via Time Machine to new Mac
3. For unrelated reasons, had to create a new User
4.  Copied VSCode insiders folder from my home folder on old Mac to new home folder
5. Copied settings from ~/Library on old Mac to same place on new Mac
6. Code Insiders opens, all settings, themes, extensions work, app works
7. Try to check for update.  Get this:

<img width="555" alt="screen shot 2017-08-09 at 8 13 13 pm" src="https://user-images.githubusercontent.com/835148/29149136-090b36d2-7d40-11e7-8ccf-166abb290a2e.png">

8. I type my admin password.  The gear menu indicates to restart to install, as always.
9. Choose "restart"

Nothing ever restarts.

10. Open Code again.  Process of the dialog repeats again.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-08-10 08:28
In the latest version of macOS the "SIP" feature (System Integrity Protection) requires that application autoupdate only works if the application is installed in the standard Application folder.
Please try this.

**Comment by joaomoreno** [comment] 2017-08-10 08:36
Locating it in the Application folder isn't sufficient. You need to remove the quarantine attribute from the application bundle.

Duplicate of https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150

**Closed by joaomoreno** 2017-08-10 08:36 UTC
Labels: insiders

**Comment by smlombardi** [comment] 2017-08-10 12:39
@joaomoreno I have tried the xattr fix from the other bug, to no avail.

Any other ideas?  I was updating Insiders daily on my other Mac, same OS.  This Mac has some sort of IT management on it, though, I think.

Doing `ls -lad /Applications` gives me
`drwxrwxr-x+ 158 root  admin  5372 Aug  9 19:46 /Applications/`

**Comment by smlombardi** [comment] 2017-08-10 18:58
I assume you mean put Visual Studio Code - Insiders into ~/Applications.  I will try that.

I noticed this in "output" earlier:  
`2017-08-10 14:56 Code - Insiders Helper[39933] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'`
