### ISSUE TITLE
Code hints come up too quickly

### ISSUE THREAD

**Issue by DouglasLapsley** [microsoft/vscode#141133] opened 2022-01-21 09:12 UTC
Code hints which appear when you roll over the code come up too quickly and over the top of things that I am about to click all the time.  This means that when working fast I keep clicking on the code hints rather than the code that I am trying to edit.  Suggest moving the hints further away from the code in question or leaving a little more of a delay before they appear.

**Comment by gjsjohnmurray** [comment] 2022-01-21 09:22
/duplicate of #139818 which is fixed in Insiders and will ship early next month.

**Closed** 2022-01-21 09:22 UTC
Labels: *duplicate
