### ISSUE TITLE
wsl.exe or bash.exe terminated with exit code: 259

### ISSUE THREAD

**Issue by anhdle14** [Microsoft/vscode#43850] opened 2018-02-16 18:32 UTC
### Issue Type
Bug

### Description

WSL on and "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe" or "bash.exe"
only open for 10s or less then crash.

I use cmd as an alternative, and no crash since, so it probably not wsl issue

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (d28f096018e2673a8437c788e3eed781ddb505ce, 2018-02-09T05:14:50.066Z)
OS version: Windows_NT x64 10.0.17101

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.95GB (7.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by egamma** [comment] 2018-02-18 14:30
Duplicate of #36994

**Closed by egamma** 2018-02-18 14:30 UTC
Labels: *duplicate
