### ISSUE TITLE
Editing files with breakpoints is completely broken

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#38355] opened 2017-11-14 21:44 UTC
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04 x64

Steps to Reproduce:

1. Add multiple breakpoints to a file
2. Edit the file in between the breakpoints.

No extensions are enabled.
When editing the file by inserting new lines between existing breakpoints, more and more breakpoints are added - some valid, some not. Most of the breakpoint decorations cannot be removed by clicking on them - the file must be closed and reopened to clear them.

Set 3 breakpoints:
![screenshot from 2017-11-14 21-45-34](https://user-images.githubusercontent.com/13035517/32806721-7e6cfcda-c985-11e7-9094-9aa01534e9b2.png)

Add and delete some new (empty) lines between the breakpoints and I end up with this:
![screenshot from 2017-11-14 21-46-43](https://user-images.githubusercontent.com/13035517/32806766-9d6756da-c985-11e7-9ddf-1d6f93020f30.png)

The extra breakpoints are stuck - they cannot be deleted by clicking on them.
A little more for your entertainment...
![aaa](https://user-images.githubusercontent.com/13035517/32807089-b5b527de-c986-11e7-8359-a58257742ed5.gif)

**Comment by weinand** [comment] 2017-11-14 23:10
Duplicate of #37880. Please try Insiders.

**Closed by weinand** 2017-11-14 23:10 UTC
Labels: debug, new release
