### ISSUE TITLE
vscode adding escapes to args supplied via launch.json configuration. python sys.argv sees VS code's arguments not those specified in launch.json.

### ISSUE THREAD

**Issue by AshleyT3** [microsoft/vscode#149391] opened 2022-05-12 20:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 (system setup)
- OS Version: 21H2 19044.1706
- Potentially related or duplicate Issues:
    - https://github.com/microsoft/vscode/issues/125934
    - https://github.com/microsoft/vscode/issues/108775

Steps to Reproduce:

1. Prepare VSCode for minimal Python development, meaning activate the Python extension.
2. Start VSCode, create a directory with a VSCode workspace.
3. Create a new Python script display_argv.py with the source code shown below.
4. Choose Run/Add Configuration or start debugging display_argv.py to kick off a prompt that ultimately causes a default launch.json to be created.
5. In the launch.json, add an "args" field with an array containing a single arg element of "C:\\". Note, in the example launch.json shown below, there are two slashes which are required by VSCode to satisfy its syntax checker since json requires escaping slash (and fwiw, VSCode fails to launch the script without escaping the slash).
6. Run or debug display_argv.py using the new launch.json configuration with the one argument. Notice that the `C:\` argument is received by Python as `C:\\` (4 characters). Effectively, VSCode is adding a character to the specified argument.

launch.json with C:\ argument:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": [
                "C:\\"
            ]
        }
    ]
}
```

display_argv.py:
```
import sys
print(sys.argv)
print(f"sys.argv[1]={sys.argv[1]} len={len(sys.argv[1])} sys.argv[1][-2]={sys.argv[1][-2]} sys.argv[1][-1]={sys.argv[1][-1]}")
```

The display_argv.py output observed upon repro:
```
['c:\\test\\display_argv.py', 'C:\\\\']
sys.argv[1]=C:\\ and is len=4 sys.argv[1][-2]=\ sys.argv[1][-1]=\
```

**Comment by nlarusstone** [comment] 2022-05-18 16:12
I'm also encountering this and it seems to be due to the most recent update:

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z (1 wk ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0
```

My configuration contains a `<` sign and it's getting escaped:

```json
        {
            "name": "Cluster",
            "type": "python",
            "justMyCode": false,
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "shell",
                "<",
                "${workspaceFolder}/launch_cluster.py"
            ],
            "preLaunchTask": "checkServer",
            "django": true
        },
```

Produces an error because the generated command is: `manage.py shell \< launch_cluster.py`

**Comment by roblourens** [comment] 2022-05-18 16:24
This will be fixed in 1.67.2 (releasing in a couple hours) https://github.com/microsoft/vscode/issues/148887

**Closed by roblourens** 2022-05-18 16:24 UTC

**Comment by jcollinsZF** [comment] 2022-05-19 22:35
I don't think this issue was fully fixed. I still see spaces being escaped. Here is a minimal reproducible example.

```json
{
  "name": "Example escaped launch.json config",
  "type": "python",
  "request": "launch",
  "program": "example.py",
  "args": [
    "foo bar"
  ]
},
```

I get the output:
```
/usr/bin/env /srv/venv/bin/python /root/.vscode-server/extensions/ms-python.python-2022.6.2/pythonFiles/lib/python/debugpy/launcher 44853 -- example.py foo\ bar
```
Notice how a slash was added between "foo" and "bar" `example.py foo\ bar`

In this contrived example I understand that I could fix this by using
```
  "args": [
    "foo",
    "bar"
  ]
```
But I cannot do that with how I actually want to use launch.json

My real world example is this:
```json
{
    "name": "Python: Django Debug Single Test",
    "type": "python",
    "request": "launch",
    "program": "${workspaceFolder}/manage.py",
    "args": [
        "test",
        "`echo -n ${relativeFileDirname} | tr \/ .`.${fileBasenameNoExtension}"
    ],
    "django": true
}
```
but every space in that second argument gets escaped and it breaks the command :(

**Comment by roblourens** [comment] 2022-05-20 17:58
The history is this - we were not fully escaping arguments, making it impossible to pass some special characters to a program as args. https://github.com/microsoft/vscode/issues/145265. I think we never intended to enable arbitrary shell scripts in launch.json args, but it worked because arg escaping was incomplete. My view is that args should be arguments passed to a program, not a shell script which only works in a particular shell.

Since lots of people were using < and > for input and output redirection, our compromise was not escaping those characters when they are alone in an arg. But other characters will be escaped so they can be passed literally to a program.

There might be another way you can get the same transformation like by doing it in your .py file. That would be platform-independent too. Not sure what are all the options that the python debugger has but maybe you can start a shell script.

**Comment by roblourens** [comment] 2022-05-20 20:41
If needed, we can continue this in https://github.com/microsoft/vscode/issues/149910
