### ISSUE TITLE
Two colons added when completing pseudo-selector in nested scss

### ISSUE THREAD

**Issue by thohe973** [Microsoft/vscode#30176] opened 2017-07-06 06:58 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write 
```
.foo { 
    .bar::bef
}
````
2. Tab or enter on the autocomplete suggestion for ::before
3. Result is
```
.foo { 
    .bar::::before
}
````

**Comment by aeschli** [comment] 2017-07-11 09:54
duplicate of #17726

**Closed by aeschli** 2017-07-11 09:54 UTC
