### ISSUE TITLE
Extremely slow Typescript intellisense and error checking in some files

### ISSUE THREAD

**Issue by Tesohh** [microsoft/vscode#156373] opened 2022-07-26 21:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Windows 10

Steps to Reproduce:

1. Edit a typescript file

Whenever I edit "medium" (about 300 lines) files i get unbearably slow intellisense and error checking. I see any errors i made after like 6 seconds from saving. And it happens every time. I already tried to bisect extensions and it's a little faster without extensions, but still very slow.

**Comment by mjbvz** [comment] 2022-07-26 22:29
Please share a file/project that demonstrates the issue

**Comment by Tesohh** [comment] 2022-07-26 23:13
Sure:
```ts
'use strict';
import Discord, {
  ButtonInteraction,
  CommandInteraction,
  MessageActionRow,
  ModalSubmitInteraction,
  SelectMenuInteraction,
} from 'discord.js';
import cnd from './cnd';
import { BagItem, EquipSlot, IUser, User } from './schemas';
import bad_words from 'bad-words';
import items from '../instances/items';
import { Item, Usable } from '../classes/items';

export function usr2author(user: Discord.User): Discord.EmbedAuthorData {
  return {
    name: user.username,
    iconURL: user.avatarURL() || '',
  };
}

export function makeSuccessEmbed(successMessage: string, ephemeral = false): Discord.InteractionReplyOptions {
  const successEmbed = new Discord.MessageEmbed()
    .setColor('GREEN')
    .setTitle(`Success`)
    .setDescription(successMessage)
    // .setFooter(feet(interaction))
    .setTimestamp();
  return {
    embeds: [successEmbed],
    ephemeral: ephemeral,
    components: [],
  };
}

export function makeErrorEmbed(what: string): Discord.InteractionReplyOptions {
  const errorEmbed = new Discord.MessageEmbed()
    .setColor('DARK_RED')
    .setTitle(`Error`)
    .setDescription('❌ ' + what)
    .setTimestamp();
  return {
    embeds: [errorEmbed],
    ephemeral: true,
    components: [],
  };
}

export function makeTransactionEmbed(value: number): Discord.InteractionReplyOptions {
  const errorEmbed = new Discord.MessageEmbed()
    .setColor(value < 0 ? 'RED' : 'GREEN')
    .setTitle(`${value < 0 ? '' : '+'}${value} ${cnd.coin}`)
    .setTimestamp();
  return {
    embeds: [errorEmbed],
    ephemeral: true,
    components: [],
  };
}

export function arrayPick<T>(a: T[]): T {
  return a[Math.floor(Math.random() * a.length)];
}

export function arrayShuffle(array: any[]): any[] {
  array = [...array];

  for (let index = array.length - 1; index > 0; index--) {
    const newIndex = Math.floor(Math.random() * (index + 1));
    [array[index], array[newIndex]] = [array[newIndex], array[index]];
  }

  return array;
}

export function fid(id: string): string {
  return id.toLowerCase().replace('_', '').replace('-', '').replace(' ', '');
}

export function upperFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export async function getUser(did: string): Promise<IUser | null> {
  return await User.findOne({ discordId: did });
}

export function type2num(
  type:
    | 'SUB_COMMAND'
    | 'SUB_COMMAND_GROUP'
    | 'STRING'
    | 'INTEGER'
    | 'BOOLEAN'
    | 'USER'
    | 'CHANNEL'
    | 'ROLE'
    | 'MENTIONABLE'
    | 'NUMBER'
): number {
  return (
    [
      'SUB_COMMAND',
      'SUB_COMMAND_GROUP',
      'STRING',
      'INTEGER',
      'BOOLEAN',
      'USER',
      'CHANNEL',
      'ROLE',
      'MENTIONABLE',
      'NUMBER',
    ].indexOf(type) + 1
  );
}

export const profFilter = new bad_words({ placeHolder: '*' });

// export function barSpitter(
//   value: number,
//   maxValue: number,
//   size: number,
//   fullCharacter: string, // keyof typeof cnd.bars
//   showPercentage = true
// ): string {
//   let percentage = value / maxValue; // Calculate the percentage of the bar
//   let progress = Math.round(size * percentage); // Calculate the number of square caracters to fill the progress side.
//   let emptyProgress = size - progress; // Calculate the number of dash caracters to fill the empty progress side.
//   if (value > maxValue) {
//     progress = size;
//     emptyProgress = 0;
//   } else if (value < 0) {
//     progress = 0;
//     emptyProgress = size;
//   }
//   // console.log(progress);
//   const progressText = fullCharacter.repeat(progress); // Repeat is creating a string with progress * caracters in it
//   const emptyProgressText = '<:emptybar:916749046780162110>'.repeat(
//     emptyProgress
//   ); // Repeat is creating a string with empty progress * caracters in it
//   const percentageText = Math.round(percentage * 100) + '%'; // Displaying the percentage of the bar

//   const bar = `<:barcornerleft:916749046608183296>${progressText}${emptyProgressText}<:barcornerright:916749046754988072>${
//     showPercentage ? '`' + percentageText + '`' : ''
//   }`;
//   // Creating the bar

//   return bar;
// }

export function getItem(id: string): Item | undefined {
  for (let i of items.flat()) {
    if (i.shorthands.includes(id)) {
      return i;
    }
  }
  // for (let index = 0; index < items.length; index++) {
  //   if (items[index].id == id) {
  //     console.log('PRESO: ' + items[index].id);
  //     return items[index];
  //   }
  // }
}

export const sleep = async (milliseconds: number) => {
  await new Promise((resolve) => setTimeout(resolve, milliseconds));
};

export function probability(probab: number) {
  return Math.random() * 100 < probab;
}

export async function buttonHandler(
  itr: CommandInteraction,
  buttonsTimeout: number,
  disabledButton?: MessageActionRow | MessageActionRow[],
  deferMap?: { [key: string]: boolean }
): Promise<[string | boolean, ButtonInteraction | undefined]> {
  let id: [string | boolean, ButtonInteraction | undefined] = ['', undefined];
  const filter = (i: ButtonInteraction) => i.user.id.toString() == itr.user.id;
  await itr.channel
    ?.awaitMessageComponent({
      filter: filter,
      idle: buttonsTimeout,
      componentType: 'BUTTON',
    })
    .then(async (buttonInteraction) => {
      const deferMapProcessed = deferMap || {};
      const defer = deferMapProcessed[buttonInteraction.customId] ?? true;

      if (!buttonInteraction.deferred && defer) {
        await buttonInteraction.deferUpdate();
      }
      id[0] = buttonInteraction.customId;
      id[1] = buttonInteraction;
    })
    .catch(async (err) => {
      if (err.message == 'Collector received no interactions before ending with reason: idle') {
        if (disabledButton != undefined)
          await itr.editReply({
            components: [disabledButton].flat(),
          });

        id[0] = false;
      }
    });

  return id;
}

export async function dropdownHandler(
  itr: CommandInteraction,
  selectId: string,
  selectTimeout: number,
  disabledSelect?: MessageActionRow
): Promise<string | boolean> {
  let id = '';
  const filter = (i: SelectMenuInteraction) => i.user.id.toString() == itr.user.id && i.customId == selectId;
  await itr.channel
    ?.awaitMessageComponent({
      filter: filter,
      idle: selectTimeout,
      componentType: 'SELECT_MENU',
    })
    .then(async (selectItr: SelectMenuInteraction) => {
      if (!selectItr.deferred) await selectItr.deferUpdate();
      id = selectItr.values[0];
    })
    .catch(async (err) => {
      if (err.message == 'Collector received no interactions before ending with reason: idle') {
        if (disabledSelect != undefined)
          await itr.editReply({
            components: [disabledSelect],
          });

        return false;
      }
    });

  return id;
}

export async function modalHandler(itr: CommandInteraction, id: string): Promise<ModalSubmitInteraction | boolean> {
  return await itr
    .awaitModalSubmit({
      time: 60000,
      filter: (i: ModalSubmitInteraction) => i.user.id.toString() == itr.user.id && i.customId == id,
    })
    .then((i) => {
      i.deferUpdate();
      return i;
    })
    .catch((e) => {
      console.log(e);
      return false;
    });
}

export function sliceIntoChunks<T>(arr: T[], chunkSize: number): T[][] {
  const res = [];
  for (let i = 0; i < arr.length; i += chunkSize) {
    const chunk = arr.slice(i, i + chunkSize);
    res.push(chunk);
  }
  return res;
}

export async function save(user: IUser | null): Promise<void> {
  user?.markModified('bag');
  user?.markModified('buildings');
  user?.markModified('stats');
  user?.markModified('permanentStats');
  user?.markModified('equipment');
  user?.markModified('skills');
  await user?.save();
}

export async function hasPlayerItem(userID: string, itemID: string, quantity?: number): Promise<boolean> {
  const user = await getUser(userID);
  if (user == null) return false;

  if (!user.bag[itemID]) return false;

  if (user.bag[itemID].stack < (quantity || 1)) return false;

  return true;
}

export async function removePlayerItem(userID: string, itemID: string, quantity = 1): Promise<boolean> {
  const user = await getUser(userID);

  if (getItem(itemID) == undefined) return false;
  if (!(await hasPlayerItem(userID, itemID, quantity))) return false;

  user!.bag[itemID].stack -= quantity;

  if (user!.bag[itemID].stack <= 0) delete user!.bag[itemID];
  await save(user);

  return true;
}

/** Dopo aver dato un oggetto bisogna sempre ricordarsi di usare registerPlayerItem() */
export async function givePlayerItem(itr: CommandInteraction, itemID: string, quantity = 1): Promise<boolean> {
  const userID = itr.user.id;

  const user = await getUser(userID);
  if (user == null) return false;

  const item = getItem(itemID);
  if (item == undefined) return false;

  if (!(await hasPlayerItem(userID, itemID))) user!.bag[itemID] = { stack: quantity };
  else user!.bag[itemID].stack += quantity;

  await save(user);
  return true;
}

export async function registerPlayerItem(itr: CommandInteraction, itemID: string) {
  const userID = itr.user.id;

  const user = await getUser(userID);
  if (user == null) return false;

  const item = getItem(itemID);
  if (item == undefined) return false;

  if (!user?.foundItems.includes(item.id)) {
    // deve essere item.id altrimenti se uso uno shorthand mi registra quello invece che l'id
    user?.foundItems.push(item.id);
    if (itr.replied)
      await itr.followUp({
        embeds: [item.getItemCard(user, 'quick')],
        ephemeral: true,
      });
    else
      await itr.user.send({
        embeds: [
          item.getItemCard(user, 'quick').setFooter({
            text: 'This message was sent to you in DMs because of a dev mistake, sorry!',
          }),
        ],
      });
  }
  await save(user);

  return true;
}

export function makeStorageString(storage: { [key: string]: BagItem }): string {
  let sortedStorage: { [key: string]: BagItem } = {};
  let toSort = [...Object.keys(storage)]
    .sort((a, b) => getItem(a)!.name.toLowerCase().localeCompare(getItem(b)!.name.toLowerCase()))
    .sort((a, b) => getItem(b)!.numericalRarity - getItem(a)!.numericalRarity); // alto -> basso

  for (let i of toSort) {
    sortedStorage[i] = storage[i];
  }

  let str = '';
  // .sort((a, b) => a.name.toLowerCase().localeCompare(b.name.toLowerCase()))
  // .sort((a, b) => a.numericalRarity - b.numericalRarity);
  for (let [k, v] of Object.entries(sortedStorage)) {
    let item = getItem(k);
    if (item != undefined) str += `${item.getInlineString()} \`x${v.stack}\`\n`;
  }
  return str || "It's Empty...";
}

export function makeEquipString(user: IUser, slot: EquipSlot) {
  const equipmentEmojis = {
    hat: '🧢',
    shirt: '👕',
    pants: '👖',
    bulletproof: '🦺',
    ring: '💍',
    necklace: '📿',
  };

  const item = getItem(user.equipment[slot].item);
  if (item == undefined) return `${equipmentEmojis[slot]} \`Empty\``;

  return item.getInlineString(true);
}

export function truncateString(str: string, length: number): string {
  let slicedName = str.substring(0, length);
  slicedName = slicedName.length < str.length ? slicedName + '…' : slicedName;
  return slicedName;
}

export function tooltip(surface: string, text: string, link = 'pyros.dev') {
  return `[${surface}](https://${link} "${text}")`;
}

/**
 * m: [m ,f, nb]
 */

const pronouns = {
  mr: ['Mr.', 'Ms.', 'Citizen'],
  his: ['his', 'her', 'their'],
  he: ['he', 'she', 'they'],
  male: ['Male', 'Female', 'Non Binary'],
  emojimale: ['🚹 Male', '🚺 Female', '<:nonbinary:999809402058059796> Non Binary'],
};
/**
 * Place in any MALE pronoun and recieve the right pronoun for the right person
 */
export function prm(user: IUser, key: keyof typeof pronouns): string {
  const gender2num = { male: 0, female: 1, nonbinary: 2 };
  return pronouns[key][gender2num[user.gender]];
}```

**Comment by Tesohh** [comment] 2022-07-26 23:47
if you're wondering, i'm making a discord bot using mongoose

**Comment by mjbvz** [comment] 2022-07-27 23:40
Thanks. This is a duplicate of https://github.com/Automattic/mongoose/issues/10349

**Closed by mjbvz** 2022-07-27 23:40 UTC
Labels: info-needed
