### ISSUE TITLE
Visual Studio Code extremely slow

### ISSUE THREAD

**Issue by GoddamnNoise** [microsoft/vscode#80815] opened 2019-09-12 18:38 UTC
Issue Type: <b>Performance Issue</b>

This poblem is happening since a few days ago. Visual Studio Code  is so slow I can't even work. Example: I type in a few characters and wait for Visual Studio Code  to make suggestions. While a week ago these suggestions appeared in less than a second, now i've to wait more than 10 seconds.

If I open a terminal and launch a top command, Visual Studio Code is consuming more than 100% of my CPU.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:51:09.716Z)
OS version: Linux x64 4.15.0-62-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2893)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|7.71GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   142	  5709	code main
    0	    39	  5711	   zygote
    1	   324	  5757	     window (atv-player.component.ts - arantia-npvr (área de trabajo) - Visual Studio Code)
    0	     0	  5776	       /bin/bash
   30	   339	  5785	       extensionHost
    4	   103	  6145	         electron_node tsserver.js 
    0	   103	  6252	         electron_node server.js 
    0	    79	  5805	       watcherService
    0	    71	  5843	       searchService
    0	    95	  5818	     shared-process
    0	     0	  6302	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6303	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    95	  6277	     window (Notificador de problemas)
    0	    47	  5748	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (atv-player.component.ts - arantia-npvr (área de trabajo) - Visual Studio Code)
|    Folder (atv3-fe): 847 files
|      File types: ts(278) html(91) css(88) png(84) jpg(36) json(19) js(10)
|                  ttf(6) svg(5) xml(2)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.7.0
ng-template|Ang|0.802.3
vscode-django|bat|0.19.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
git-extension-pack|don|0.1.3
githistory|don|0.4.6
python-extension-pack|don|1.6.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
RelativePath|jak|1.4.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
MagicPython|mag|1.1.0
Angular-BeastCode|Mik|8.0.10
vscode-language-pack-es|MS-|1.38.3
python|ms-|2019.9.34911
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
angular2-inline|nat|0.0.17
angular-console|nrw|8.1.2
material-icon-theme|PKi|3.9.0
typescript-hero|rbb|3.0.0
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.3.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6
ab-html-formatter|zov|0.0.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-09-13 17:27
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by GoddamnNoise** [comment] 2019-09-13 18:58
Hi, Matt,

I didn't know about VS Code Insiders existence. I'll give it a try on
monday when I'll go to work and I'll tell you if it happens again in VS
Code insiders with all extensions disabled.

Thanks a lot for your help!

- Ángel -

**Comment by o8e** [comment] 2019-09-16 13:25
I am also experiencing a very slow VSCode since the latest update. Especially when I `(cmd+shift+n)` a new window.

**Comment by GoddamnNoise** [comment] 2019-09-16 15:35
Hi again, Matt,

The problem doest not reproduce in the latest VS Code insiders buld with
all extensions disabled.

**Comment by mjbvz** [comment] 2019-09-16 17:47
Ok, this issue was either fixed by the insiders build or was caused by one of the extensions you had installed. You can follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect investigate which extension may have caused this

**Closed by mjbvz** 2019-09-16 17:47 UTC
Labels: needs more info
