### ISSUE TITLE
need a printable version of code files opened in VS code

### ISSUE THREAD

**Issue by sajuthankathurai** [microsoft/vscode#75462] opened 2019-06-14 01:09 UTC
I would like to take print out of my code files in VS code. So please provide an option to 

1. Print preview on click of Ctrl+p
2. Enable print option to print my contents

Currently if we want to print our code files, we need to copy code from vs code to MS word and then we print.

**Comment by mjbvz** [comment] 2019-06-14 01:46
Duplicate of #5953

**Closed by mjbvz** 2019-06-14 01:46 UTC
