### ISSUE TITLE
simpleFindWidget overlays part HTML webview, causing dead zone in upper-right

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode#36155] opened 2017-10-12 17:39 UTC
The recent release of 1.17.1 introduced a new "dead zone", an un-clickable area near the upper-right corner of the HTML preview / webview.  The actual `<webview>` is obscured by a `<div class="simple-find-part-wrapper"><div class="simple-find-part">...` that appears in the DOM just prior to it.

Note that this breaks ALL existing extensions that place UI controls in the upper-right of an HTML panel, so I would love to see an urgent fix for this.

I created a "reduced case" extension to test this, [source on GitHub here](https://github.com/emackey/browser-tester).  This extension contributes a single command called `Hello World`, that opens an HTML preview with a giant button in the upper-right.  This button turns green when hovered and orange when clicked.  The top line of the button is un-clickable and un-hoverable at all times.  Real extensions use smaller buttons, and those are completely obscured by this.

Here's my reduced-case extension being debugged.  You can see that `simple-find-part-wrapper` is completely obscuring part of the `webview`, making the extension's content unreachable.

![vscodedeadzone](https://user-images.githubusercontent.com/1235080/31510313-52b26c12-af52-11e7-80bb-9589ed388de8.png)

**Comment by emackey** [comment] 2017-10-12 17:43
Ah, sorry, this is a dup of #36051.

**Comment by mjbvz** [comment] 2017-10-12 17:43
Yes, this is a duplicate of #36051. Please try the latest insiders build which should fix this

**Closed by mjbvz** 2017-10-12 17:43 UTC

**Comment by emackey** [comment] 2017-10-12 17:44
Thanks.  This breaks my deployed extension though, any chance to get a fix out to the masses?  Or should I push a workaround for the month of October?

**Comment by mjbvz** [comment] 2017-10-12 19:59
Thanks. We talked about this, but the bug didn't meet the bar for the recovery builds. I'd like to make sure it doesn't cause any regressions with testing in insiders and then take it into the November release
