### ISSUE TITLE
ExtHostDocumentSaveParticipant: event delivery, overall timeout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133254] opened 2021-09-16 12:40 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=135037&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&l=31857

```
1) ExtHostDocumentSaveParticipant
       event delivery, overall timeout:

      1 === 2
      + expected - actual

      -1
      +2
      
  AssertionError@file:///Users/runner/work/1/s/test/unit/assert.js:184:21
  fail@file:///Users/runner/work/1/s/test/unit/assert.js:231:9
  strictEqual@file:///Users/runner/work/1/s/test/unit/assert.js:393:9
  @file:///Users/runner/work/1/s/out-build/vs/workbench/test/browser/api/extHostDocumentSaveParticipant.test.js:137:24
  promise callback*@file:///Users/runner/work/1/s/out-build/vs/workbench/test/browser/api/extHostDocumentSaveParticipant.test.js:133:79

```

I have seen issues with using `setTimeout` in browser unit tests before (esp. Firefox). Not sure what is going on there but I suspect that maybe playwright does not schedule `setTimeout` the same way a visible browser window does?

**Comment by jrieken** [comment] 2021-09-30 15:49
/duplicate of https://github.com/microsoft/vscode/issues/130910

**Closed** 2021-09-30 15:50 UTC
Labels: *duplicate, unit-test-failure, web
