### ISSUE TITLE
Window refuses to reload with an opened `iframe` based editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122736] opened 2021-04-30 15:44 UTC
I have seen this before but never figured out how to reproduce, but now that @isidorn reported https://github.com/microsoft/vscode/issues/119059#issuecomment-830163425 I was able to find the steps:

* test from a fresh user data dir and fresh extensions dir
* install the draw.io extension: `hediet.vscode-drawio`
* from the command palette pick "Draw IO: New Draw IO diagram"
* add some boxes so that the editor gets dirty
* open another editor (untitled is fine, this is only needed so that keyboard shortcuts work)
* reload window (from command palette)

=> 🐛  the window goes down but is actually not reloaded

If you follow the same steps but configure `"webview.experimental.useIframes": false` (where we then use `webview` element), I can no longer reproduce.

**Comment by bpasero** [comment] 2021-04-30 15:46
Running with `--verbose` shows that the main side continues unloading the window to prepare for a reload, but the call to `loadUrl` is actually never doing anything it seems.

![recording (1)](https://user-images.githubusercontent.com/900690/116720022-03685300-a9dc-11eb-8d42-24afc5450020.gif)

**Comment by bpasero** [comment] 2021-04-30 15:47
I wonder if this stack is related:

```
68870:0430/174531.425449:INFO:CONSOLE(627)] "%c  ERR color: #f33 A system error occurred (ESRCH, No such process): Error: ESRCH, No such process
    at G.enableInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2716:163)
    at cr.getInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1816:7533)
    at Ga.getInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2716:10051)
    at d._onDidChangeResponsiveChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1770:21028)
    at l.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1856)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2710:101152
    at l.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1816:6258
    at l.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at n._setResponsiveState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1770:8158)
    at n._checkUnresponsive (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1770:7987)
    at A.runner (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1770:7158)
    at A.doRun (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:17942)
    at A.onTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:17908)
```

**Comment by mjbvz** [comment] 2021-04-30 19:11
I can repo with drawio but it doesn't seem to happen in the hex editor. Not sure what's different between the two and I haven't found any obvious logs about the issue so far

**Comment by mjbvz** [comment] 2021-04-30 19:19
Ah I believe I've found it! This seems to be caused by a webview (the extension code) that has an unload listener that cancels window:

```ts
		window.addEventListener('beforeunload', (event) => {
				event.preventDefault();
				event.returnValue = '';
				return '';
})
```

If I add this to the hex editor, I can reproduce this problem. Iit does not seem related to the file's dirty state, I believe that drawIO only tries to cancel unload when it is dirty 

I think DrawIO should probably remove this code, but I can also see if there's some way to patch the webview environment to make `onBeforeUnload` uncancellable. Not sure if there's also an electron bug here or not since it's a little weird that iframes can block the entire app from reloading

**Comment by mjbvz** [comment] 2021-04-30 19:26
The simple repo:

1. In a md files, add:

```
<script>
window.addEventListener('beforeunload', (event) => {
    event.preventDefault();
    event.returnValue = '';
    return '';
})
</script>
```

2. Open the markdown preview to the side
3. Make sure scripts are enabled it the preview (there should be an alert if they are not)
4. Focus the webview and try to reload the window

**Comment by mjbvz** [comment] 2021-04-30 23:04
Closing for verification. Should be fixed in main and in release branch

**Closed by mjbvz** 2021-04-30 23:04 UTC
Labels: bug, candidate, freeze-slow-crash-leak, important, webview

**Comment by deepak1556** [comment] 2021-04-30 23:10
> I wonder if setting the returnValue causes electron to think that we are prompting the user?

That is correct and it is just following the behavior on the web.

Electron webview and the embedding page have a separate webContent in the main process, hence preventing unload in the webview didn't actually prevent the parent page from unloading, we have to check what chrome does for its webview and revisit this case.

As for iframes, same process or cross process iframes are still backed by the same webContent in the main process as the embedding page, hence unload listener can block the entire page from cleaning up. We can choose to disable this behavior, but just to note this is not a bug but rather intended behavior in the web.

@mjbvz if we are disallowing this scenario, what is the recommended way for extensions to do cleanup on shutdown. I believe drawIO case is a good example, where should they now perform the cleanups

**Comment by mjbvz** [comment] 2021-04-30 23:59
@deepak1556 Thanks for the background!

We don't want a webview to be able to block closing an editor tab (or the entire VS Code window). Since this hasn't been supported previously, I don't think we risk breaking many extensions with this change (as far as I can well, DrawIO only uses `beforeunload` because it pulls in the drawio library, not because the vs code extension explicitly added this)

**Comment by bpasero** [comment] 2021-05-01 09:22
Thanks 🙏
