### ISSUE TITLE
终端路径显示问题

### ISSUE THREAD

**Issue by lengyuxuan** [Microsoft/vscode#72524] opened 2019-04-18 03:47 UTC
Issue Type: <b>Bug</b>

终端选择的powershell，打开的时候路径出显示空白，实际上有内容

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.2
tslint|eg2|1.0.43
svn-scm|joh|1.48.0
vscode-language-pack-zh-hans|MS-|1.33.2
code-settings-sync|Sha|3.2.8
markdown-preview-enhanced|shd|0.3.13

</details>

**Comment by yume-chan** [comment] 2019-04-18 07:37
duplicate of #57803

**Comment by octref** [comment] 2019-04-20 23:04
https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423

**Closed by octref** 2019-04-20 23:04 UTC
