### ISSUE TITLE
Windows: dropdown selector empty after reload of window

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25700] opened 2017-04-30 14:53 UTC
On Windows:
- Start vscode
- switch to the output panel
- open the channel selector drop down

The drop down menu is empty:
![image](https://cloud.githubusercontent.com/assets/172399/25565331/90d1bb24-2dc5-11e7-941e-457d92ed48d0.png)

On second open the drop down menu is populated.

I've observed the same behaviour in the launch configuration drop down in the Debug viewlet.

**Comment by isidorn** [comment] 2017-05-02 05:34
@egamma I can not reproduce this both on the mac and windows. Please see the gif attached and let me know if you are doing something differnetly - thanks
![output](https://cloud.githubusercontent.com/assets/1926584/25605237/bcd4620e-2f09-11e7-9eb4-2aba5c5198d7.gif)

**Comment by egamma** [comment] 2017-05-02 06:44
You several attempts but I could just reproduce it again (see below)

This is the sequence:
- configure the workspace state so that the Output panel is visible
- reload window
- open the channel drop down

![image](https://cloud.githubusercontent.com/assets/172399/25606729/4e820590-2f13-11e7-9f55-fb537a7deb1d.png)

**Comment by egamma** [comment] 2017-05-02 06:47
These are the steps and a recording
- configure the workspace state so that the Output panel is visible
- reload window
- open the channel drop down

The problem happens after the 2nd reload window.

![empty-drop-down](https://cloud.githubusercontent.com/assets/172399/25606806/c67f5642-2f13-11e7-98bf-e5a2bbf58c76.gif)

**Comment by isidorn** [comment] 2017-05-02 08:02
Ok I can only reproduce it on windows - notice that it is a rendering issue, becuase when the dropdown is black it still has the correct model behind it.
Due to those two reasons I believe this is related to our electron update.
@bpasero thoughts?

**Comment by bpasero** [comment] 2017-05-02 08:12
@isidorn @egamma I see a little bit of weirdness, specifically the dropdown jumps up and down for me only when clicking for the first time. But I only see this when I reloaded the window, not on the first startup.

I do however not see the dropdown being totally broken.

**Comment by isidorn** [comment] 2017-05-02 08:58
I can not reproduce with the current stable which has an older electron version.
And for some reason I can also not repro it with the insiders on windows (I could see it one hour ago but no more).
Due to that I can also not reproduce it when running out of source for both electron versions.

@egamma do you get this conisstently? If yes can you try reproing when runnning out of source, if it repros just change the electron version in `package.json` to `1.4.6`

**Comment by dbaeumer** [comment] 2017-05-02 12:07
I can reproduce it under Windows running out of source. When run out of source you even see the drop down content rendered at the wrong position in VS Code Window. It is basically rendered in the middle of the window horizontally and in the lower third vertically. The drop down flashes there shortly and then disappears.

**Comment by dbaeumer** [comment] 2017-05-02 12:14
Was not able to reproduce on Electron 1.4.6

**Comment by bpasero** [comment] 2017-05-02 12:25
@dbaeumer can you reproduce when you try our current stable (1.11.x) with Electron 1.6.x? You should be able to update simply by taking the electronVersion from our current package.json file and rebuilding the native dependencies. This would hint if this is a CSS/theming regression of Electron update regression?

**Comment by dbaeumer** [comment] 2017-05-02 12:42
Here are more findings with the help of @joaomoreno 

- the initial rendering happens on the wrong position seems to use absolute screen coordinates instead of coordinates relative to the VS Code window

- I can reproduce this in source without a reload

Here is a screen cast showing what I see with the debug menu

![cast](https://cloud.githubusercontent.com/assets/1931590/25618016/600703ba-2f45-11e7-8e3d-ee87b5d9ce4f.gif)

@joaomoreno suggested the following as a workaround: we create a initial selection menu hidden/off screen to trigger some first run of the electron code. Further opening of the box should then be fine.

**Comment by dbaeumer** [comment] 2017-05-02 12:45
Starting with `--disable-gpu` still shows the problem.

**Comment by dbaeumer** [comment] 2017-05-02 12:48
@bpasero the problem doesn't reproduce using 1.11 and electron 1.6.6.

Another tip: to make the drop down stay on the screen simple press the drop down button and don't release it.

**Comment by bpasero** [comment] 2017-05-02 12:57
@dbaeumer thanks for trying. I wonder if this is zooming and/or scaling related. I can still not reproduce when changing zoom levels on the OS level, maybe you could try by checking this option:

![image](https://cloud.githubusercontent.com/assets/900690/25618534/9e0c6536-2f47-11e7-9d13-d6b500e3f5b9.png)

(make sure to restart between changing this setting)

**Comment by dbaeumer** [comment] 2017-05-02 12:59
It does reproduce for me on a 100% zooming setting. Will check with a different value.

**Comment by dbaeumer** [comment] 2017-05-02 13:01
Does reproduce with zoom level 150% as well.

**Comment by dbaeumer** [comment] 2017-05-02 13:16
@egamma I could reproduce this on my machine without reloading the window (on initial startup).

**Comment by dbaeumer** [comment] 2017-05-02 13:18
...interestingly only from source (script\code.bat). In VS Code insider I can only reproduce this on reload. Might be a timing problem then

**Comment by bpasero** [comment] 2017-05-02 15:04
@egamma @dbaeumer could someone that can reproduce physically sit together with someone that could try CSS/JS hacks to see if that changes anything? Can we just open the dropdown twice the first time we detect a click (things like that?).

**Comment by isidorn** [comment] 2017-05-03 07:39
I have a hard time doing something about this issue since I can not reproduce it (just tried again on win and does not repro both on Insiders and out of source). Not sure if my win machine being a VM has an effect

**Comment by dbaeumer** [comment] 2017-05-03 07:41
@isidorn it only reproduces if you don't open any other menu before since as @joaomoreno explained to me the menu and the drop down uses the same underlying Electron code.

**Comment by isidorn** [comment] 2017-05-03 07:48
@dbaeumer still does not reproduce for me in that case. I was trying exactly what you are explaining and showing in gifs

**Comment by joaomoreno** [comment] 2017-05-03 08:39
It always reproduces for me in Parallels.

I failed to come up with a workaround. We will have to release with this issue, release note it in the Electron section and file an issue to Electron about it. I leave this up to you @isidorn 

cc @egamma

**Comment by isidorn** [comment] 2017-05-03 08:46
@joaomoreno thanks!
I will update the release notes and will create an issue for Electron

**Comment by isidorn** [comment] 2017-05-03 15:36
I have updated the relase notes and created https://github.com/electron/electron/issues/9364
Moving milestone to backlog

**Comment by bpasero** [comment] 2017-06-09 09:17
This seems to be caused by us setting `backgroundThrottling` for the Window.

**Comment by isidorn** [comment] 2017-06-20 12:57
Can not repro with electron 1.7, so should be fixed when we update to latest

**Comment by CnSimonChan** [comment] 2017-08-17 03:23
I can reproduce this with 1.16.0-insider, electron 1.7.4.

![image](https://user-images.githubusercontent.com/1330321/29394653-50c8311a-833e-11e7-87a7-c424b1f72fd4.png)

**Comment by EbXpJ6bp** [comment] 2017-08-23 13:56
So can I. 
Electron 1.7.5, 1.16.0-insider 1c6f2f9a8012565adcc50616c3aa90cb444e8797

**Comment by cprogrammer1994** [comment] 2017-10-18 07:32
https://github.com/DonJayamanne/pythonVSCode/issues/1312 related

**Comment by bpasero** [comment] 2017-12-18 14:28
On Windows and Linux we are now using custom select box (via #37533)

**Closed by bpasero** 2017-12-18 14:28 UTC
Labels: bug, electron, upstream, windows
