### ISSUE TITLE
The window moves up when opening "Problem" panel

### ISSUE THREAD

**Issue by WEGFan** [Microsoft/vscode#69698] opened 2019-03-02 08:45 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Press `Ctrl + J` to bring up the bottom panel.
2. Click on `PROBLEMS`.
3. The whole window moves up.

Does this issue occur when all extensions are disabled?: Yes

![snipaste_2019-03-02_16-36-48](https://user-images.githubusercontent.com/7558201/53679657-43ebb980-3d0a-11e9-9100-9dcb083789ed.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
color-info|bie|0.5.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.24.0
vscode-new-file|dku|4.0.2
githistory|don|0.4.6
xml|Dot|2.4.0
json-tools|eri|1.0.2
code-runner|for|0.9.7
vdf|GEE|0.0.6
gc-excelviewer|Gra|2.1.29
todo-tree|Gru|0.0.120
beautify|Hoo|1.4.9
html-tag-wrapper|hwe|0.2.3
createtmpfile|jgo|0.0.3
vscode-pastery|max|0.0.4
select-highlight-minimap|mde|0.0.8
rainbow-csv|mec|1.0.0
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.2.5433
cpptools|ms-|0.21.0
vscode-json-editor|nic|0.2.3
java|red|0.40.0
vscode-sort-json|ric|1.13.0
code-stats-vscode|riu|1.0.13
vscode-icons|rob|8.2.0
partial-diff|ryu|1.4.0
vscode-open|san|0.1.0
code-settings-sync|Sha|3.2.5
vscode-fileutils|sle|2.13.5
vscode-hexdump|sle|1.7.2
html-preview-vscode|tht|0.2.5
scrolloff|tic|0.0.3
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
file-size|zh9|0.1.3
html-css-class-completion|Zig|1.18.0

</details>

**Comment by sandy081** [comment] 2019-03-03 18:59
@WEGFan Do you have experimental grid layout enabled?

**Comment by WEGFan** [comment] 2019-03-04 00:27
After disabling the experimental grid layout it doesn't have the bug.
Can't repro it in Insiders.

**Comment by sandy081** [comment] 2019-03-04 08:58
Duplicate of #67371

**Closed by sandy081** 2019-03-04 08:58 UTC
Labels: *duplicate, error-list, needs more info
