### ISSUE TITLE
JavaScript multiple variable declaration not highlighted correctly

### ISSUE THREAD

**Issue by micnic** [Microsoft/vscode#6034] opened 2016-05-02 08:14 UTC
- VSCode Version: 1.0.0

![screenshot](https://cloud.githubusercontent.com/assets/1449826/14949863/b48dcbde-104d-11e6-983e-c9a0ad4ee2c3.png)

I use multiple variable declaration in JavaScript, but only the first variable declaration is highlighted as a variable declaration, the rest of them are in the default variable color.

**Comment by aeschli** [comment] 2016-05-09 13:07
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/121

**Closed by aeschli** 2016-05-09 13:07 UTC
