### ISSUE TITLE
Error opening diff editor on issues notebook

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127483] opened 2021-06-29 14:25 UTC
Testing #127355

This works on some files (custom diff is shown) and fail on others:
![image](https://user-images.githubusercontent.com/9205389/123814402-f2fa2900-d8f5-11eb-8ec6-f3c0c1467f81.png)

**Comment by bpasero** [comment] 2021-06-29 14:45
There seems to be an error talking about `cells`.

**Comment by rebornix** [comment] 2021-07-01 03:55
@chrmarti can you double confirm that if you have screen reader optimzitation turned on?

**Comment by rebornix** [comment] 2021-07-01 04:06
For the cell uri error, the stable reproduce is

* Compare two notebook files
* Open the left side one from file explorer
* Close the newly opened notebook

Then it crashed, it seems the model behind the left side is disposed. This was a regression of inheriting from `DiffEditorInput`. Would love to sit together with @lramos15 tomorrow on a fix.

**Comment by rebornix** [comment] 2021-07-01 05:30
Fixed via 7d7ab1a144927f2a1b6bd57895800d724518cd11 and follow up issue https://github.com/microsoft/vscode/issues/127738

**Closed by rebornix** 2021-07-01 05:30 UTC
Labels: bug, notebook-diff
