### ISSUE TITLE
vscode:// schema for opening files doesn't work, says "Unable to open <file>: resource is not available"

### ISSUE THREAD

**Issue by xpl** [Microsoft/vscode#70328] opened 2019-03-12 18:01 UTC
Hi there. I am now developing a [nice-looking error displaying UI](https://github.com/xpl/panic-overlay) for browsers that allows for opening the error locations in VS Code by clicking on them. I've read in the docs that it is possible by using `vscode://file/full/path/to/file` schema:

https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls

However, it is not working on my machine. Please help me with that, as the feature is really cool and critical for being able to communicate with VSCode from a browser for a better webdev debugging experience!

---

- VSCode Version: 1.32.1
- OS Version: MacOS Mojave 10.14

Steps to Reproduce:

1. In VS Code, open a folder containing a `file.js`, open that file. Suppose that the file's full path is `/Users/xpl/test/file.js`

2. In Terminal.app, run `open vscode://file//Users/xpl/test/file.js` (or open that URL in a browser)

3. An error pops up (_"unable to open 'file.js': resource is not available"_):

<img width="470" alt="Screen Shot 2019-03-12 at 21 03 44" src="https://user-images.githubusercontent.com/1707/54224322-58019900-450a-11e9-8d2c-e5c94e061799.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2019-03-12 18:36
duplicate of #69998

**Comment by xpl** [comment] 2019-03-12 18:43
@yume-chan  Sorry for not noticing it, my bad :(

Also is it possible to open a file by a path _relative to the currently opened workspace folder_?

Like, for example, `vscode://workspace-file/foo/bar.js` (would open `${workspaceDir}/foo/bar.js`)? It would be really useful because it is not always possible to have a full path to the file, often only a relative path is available.

**Closed** 2019-03-13 00:08 UTC
Labels: new release
