### ISSUE TITLE
Bug: View: Toggle Word Wrap stopped working 1.9.0

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#20066] opened 2017-02-06 18:04 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.1|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|copy-relative-path|enochc|0.1.1|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.10|
|cpptools|ms-vscode|0.10.0|
|copy-file-name|nemesv|1.0.0|
|vscode-clearcase|OpenNingia|1.5.0|
|vscode-icons|robertohuertasm|7.2.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.2.1|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Press Alt-Z or Ctrl-Shift-P View: Toggle Word Wrap
2. Make window smaller than line length. Doesn't wrap. Used to work in 1.8.X

**Comment by BillDenton** [comment] 2017-02-06 18:05
Wrapping related settings (searched for wrap) in user settings:
   "editor.wrappingColumn": -1,
"editor.wordWrap": true

**Comment by Bill-Stewart** [comment] 2017-02-06 18:47
See current explanation in https://github.com/Microsoft/vscode/issues/19875. My opinion of the desired behavior is that it should work as follows:

**`wordWrap`** | **`wrappingColumn`** | **Explanation**
----------------|-------------------------|---------------
`false`               | any value                      | Lines will never wrap
`true`               | -1                                  | Lines will wrap at min(viewport_column, wrappingColumn)
`true`               | 0                                   | Lines will wrap at viewport_column
`true`               | >= 1                             | Lines will wrap at specified column

**Comment by BillDenton** [comment] 2017-02-06 18:54
This is duplicate of #19875. I've got it working as before by using:
"editor.wrappingColumn": 300,
"editor.wordWrap": true
Can someone mark this as a duplicate and close it?

**Comment by mjbvz** [comment] 2017-02-06 23:17
Thanks @BillDenton 

Closing as duplicate of #19875

**Closed by mjbvz** 2017-02-06 23:17 UTC
Labels: duplicate

**Comment by pborenstein** [comment] 2017-02-07 20:31
Is there a way to revisit this? I understand it's working as spec'ed, but as @Bill-Stewart notes, the spec is wrong. When `editor.wordWrap` is `false`, lines should _never_ wrap regardless of the setting of `editor.wrappingColumn`.

I don't know about anyone else, but when I say, "don't wrap", I don't mean "except when you feel otherwise."
