### ISSUE TITLE
GDB C/C++ debugger won't start, giving error

### ISSUE THREAD

**Issue by jonahcwest** [Microsoft/vscode#64948] opened 2018-12-13 04:13 UTC
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-3-amd64

Steps to Reproduce:

1. Create a C/C++ project.
2. Add a debug configuration with GDB.
3. Launch with or without debugging.

What happens:

The Debug Console displays:

    Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object

The program does not start and the external console stays empty.

- I have been able to reproduce this issue on Debian and Ubuntu. (Other platforms unknown.)
- I have only seen this happen with C/C++ debugging. (The only other configuration I have tried is Node.js. Could someone please try other configurations?)
- This began to occur after updating to 1.30.0, although this may be present in prior versions.

The C/C++ Extension must be enabled to use C/C++ debugging.

Screenshot:

![screenshot from 2018-12-12 20-57-07](https://user-images.githubusercontent.com/45053144/49915352-60d2c800-fe52-11e8-8db0-0c10d85071ec.png)

**Comment by Gaolious** [comment] 2018-12-13 06:12
I got a same error  after upgrade the code

```
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.4.0-134-generic
```

**Comment by Gaolious** [comment] 2018-12-13 06:41
It works find with 1.29.1 . (I've downgrade to 1.29.1)

url : https://code.visualstudio.com/updates/v1_29

![image](https://user-images.githubusercontent.com/21376837/49920401-734e0f80-feed-11e8-84ff-a8dfd3205c5f.png)

**Comment by jonahcwest** [comment] 2018-12-13 06:56
So this seems to be an issue in 1.30.0 only? I’ve tried the latest insider version and the bug is still present.

**Comment by converk** [comment] 2018-12-13 08:41
In version 1.29, I can debug normally. I ran into a problem in version 1.30.

**Comment by isidorn** [comment] 2018-12-13 10:08
I have tried reproducing this and could not. I tried with Ubuntu 16 and Mac OS X.
Here's my sample program and my `launch.json`

I believe this is an issue with the C++ extension thus I am moving it to the C++ repository.
If it turns out to be an issue with VSCode please let us know and we will look into a candidate fix.

```C++
#include <stdio.h>

int main(int argc, char *argv[]) {
    for (int i = 0; i < argc; i++) {
        fprintf(stdout, "argv[%d]: %s\n", i, argv[i]);
    }
    return 0;
}
```

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.out",
            "args": [
                "hello", "world", "!"
            ],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "/usr/bin/gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "C:\\MinGw\\bin\\gdb.exe"
            },
            "externalConsole": false
        }
    ]
}
```

![screenshot 2018-12-13 at 11 04 17](https://user-images.githubusercontent.com/1926584/49931371-03c52980-fec7-11e8-867b-a6723ab41a17.png)

**Comment by isidorn** [comment] 2018-12-13 10:13
Created issue in C++ extension repository. Follow the issue there for more details
https://github.com/Microsoft/vscode-cpptools/issues/2922

**Comment by newfla** [comment] 2018-12-13 10:49
use "externalConsole": false to solve the issue in launch.json

**Comment by weinand** [comment] 2018-12-13 13:22
Yep, a crash deep inside the C++ debug adapter occurs if "externalConsole" is true.
The C++ team needs to investigate why this happens.

**Comment by Gaolious** [comment] 2018-12-13 15:38
@jonahcwest

apt-get purge code
rm -rf ~/.vscode
rm -rf /tmp/MS*

and
install the prior version

**Comment by weinand** [comment] 2018-12-13 20:10
I was sending a RunInTerminalResponse without a body (which is a violation of the spec).
Sorry about that. I have pushed a fix.

I broke that 24 days ago but I wonder why nobody noticed this in Insiders.

**Closed** 2018-12-13 20:10 UTC
Labels: bug, debug

**Comment by marcocrio** [comment] 2018-12-24 04:08
> use "externalConsole": false to solve the issue in launch.json
I was having the same issue, this solved it

**Comment by marcocrio** [comment] 2018-12-24 04:10
> use "externalConsole": false to solve the issue in launch.json

I was having the same issue and this solved the problem, plus is less annoying than opening a new terminal all the time you want to debug
