### ISSUE TITLE
direction problem when using rtl content inside html tag

### ISSUE THREAD

**Issue by ARZarkesh** [microsoft/vscode#146400] opened 2022-03-31 08:39 UTC
Issue Type: <b>Bug</b>

1. create an html file
2. copy the following line into the file
<span>تست</span>

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.67GB free)|
|Process Argv|--crash-reporter-id a8438929-3290-4abb-a424-46295dd9be10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.7
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|12.0.5
copilot|Git|1.10.5413
volar|joh|0.33.10
i18n-ally|lok|2.8.1
vscode-typescript-next|ms-|4.7.20220330
material-icon-theme|PKi|4.15.0
vscode-stylelint|sty|1.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30463512

```

</details>

**Comment by yume-chan** [comment] 2022-03-31 09:34
Duplicate of #146354?

**Comment by hmbmirzaei** [comment] 2022-04-01 04:56
yes.

**Closed** 2022-04-01 07:34 UTC
Labels: new release
