### ISSUE TITLE
`workbench.action.focusActiveEditorGroup` doesn't work with `!editorFocus`

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94832] opened 2020-04-09 20:35 UTC
I've added the following keybinding
```
  {
    "key": "ctrl+shift+r",
    "command": "workbench.action.focusActiveEditorGroup",
    "when": "!editorFocus"
  },
```
This works any time focus isn't on the editor _except_ from the Output view. I've double checked the context keys and `editorFocus` is in fact false, as expected. Nothing else seems to be eating that specific keybinding and either removing the when clause or replacing it with `!editorFocus || inOutput` work correctly.

<details>
  <summary>Context with Output open and focus in an editor:</summary>

```
CppReferencesView.canMove: true
CppReferencesView.defaultViewLocation: true
CppRenameCandidatesView.canMove: true
CppRenameCandidatesView.defaultViewLocation: true
CppRenamePendingView.canMove: true
CppRenamePendingView.defaultViewLocation: true
acceptSuggestionOnEnter: true
accessibilityHelpWidgetVisible: false
accessibilityModeEnabled: false
activeEditor: "workbench.editors.files.textFileEditor"
activeEditorGroupEmpty: false
activeEditorGroupIndex: 2
activeEditorGroupLast: true
activeEditorIsReadonly: false
activeLogOutput: false
activePanel: "workbench.panel.output"
activeViewlet: ""
addToWorkspaceFolderRecommendations: false
addToWorkspaceRecommendations: false
atEndOfWord: false
authTokenStatus: "Initializing"
autoSaveAfterShortDelayContext: false
breakpointSelected: false
breakpointWidgetVisible: false
breakpointsExist: true
callHierarchyVisible: false
canNavigateBack: true
canNavigateForward: false
canNavigateToLastEditLocation: true
canRedo: true
canReopenClosedEditor: true
canUndo: true
config.breadcrumbs.enabled: false
config.diffEditor.ignoreTrimWhitespace: true
config.editor.columnSelection: false
config.editor.minimap.enabled: false
config.editor.renderControlCharacters: true
config.editor.renderWhitespace: "all"
config.files.autoSave: "off"
config.git.allowForcePush: false
config.git.enabled: true
config.materialTheme.accent: undefined
config.npm.enableScriptExplorer: false
config.remote.SSH.enableWebAccess: undefined
config.remote.SSH.useLocalServer: true
config.window.menuBarVisibility: "toggle"
config.workbench.activityBar.visible: false
config.workbench.editor.enablePreview: false
config.workbench.editor.showTabs: true
config.workbench.sideBar.location: "left"
config.workbench.statusBar.visible: true
conflictsSources: ""
customEditors: ""
debugConfigurationType: "cppvsdbg"
debugState: "inactive"
debugUx: "default"
detailsContainers.canMove: true
detailsContainers.defaultViewLocation: true
dirtyDiffVisible: false
dirtyWorkingCopies: true
editorAreaVisible: true
editorColumnSelection: false
editorFocus: true
editorHasCallHierarchyProvider: false
editorHasCodeActionsProvider: true
editorHasCodeLensProvider: true
editorHasCompletionItemProvider: true
editorHasDeclarationProvider: false
editorHasDefinitionProvider: false
editorHasDocumentFormattingProvider: true
editorHasDocumentHighlightProvider: false
editorHasDocumentSelectionFormattingProvider: true
editorHasDocumentSymbolProvider: true
editorHasHoverProvider: true
editorHasImplementationProvider: false
editorHasMultipleDocumentFormattingProvider: false
editorHasMultipleDocumentSelectionFormattingProvider: false
editorHasMultipleSelections: false
editorHasReferenceProvider: false
editorHasRenameProvider: false
editorHasSelection: false
editorHasSignatureHelpProvider: false
editorHasTypeDefinitionProvider: false
editorId: "vs.editor.ICodeEditor:4"
editorIsOpen: true
editorLangId: "jsonc"
editorPinned: true
editorReadonly: false
editorSimpleInput: false
editorTabMovesFocus: false
editorTextFocus: true
expressionSelected: false
extensions.builtInBasicsExtensionsList.canMove: false
extensions.builtInBasicsExtensionsList.defaultViewLocation: true
extensions.builtInExtensionsList.canMove: false
extensions.builtInExtensionsList.defaultViewLocation: true
extensions.builtInThemesExtensionsList.canMove: false
extensions.builtInThemesExtensionsList.defaultViewLocation: true
extensions.disabledExtensionList2.canMove: false
extensions.disabledExtensionList2.defaultViewLocation: true
extensions.disabledExtensionList.canMove: false
extensions.disabledExtensionList.defaultViewLocation: true
extensions.enabledExtensionList2.canMove: false
extensions.enabledExtensionList2.defaultViewLocation: true
extensions.enabledExtensionList.canMove: false
extensions.enabledExtensionList.defaultViewLocation: true
extensions.listView.canMove: false
extensions.listView.defaultViewLocation: true
extensions.otherrecommendedList.canMove: false
extensions.otherrecommendedList.defaultViewLocation: true
extensions.popularExtensionsList.canMove: false
extensions.popularExtensionsList.defaultViewLocation: true
extensions.recommendedList.canMove: false
extensions.recommendedList.defaultViewLocation: true
extensions.vscode-local.default.canMove: false
extensions.vscode-local.default.defaultViewLocation: true
extensions.vscode-local.installed.canMove: false
extensions.vscode-local.installed.defaultViewLocation: true
extensions.vscode-local.outdated.canMove: false
extensions.vscode-local.outdated.defaultViewLocation: true
extensions.workspaceRecommendedList.canMove: false
extensions.workspaceRecommendedList.defaultViewLocation: true
findInputFocussed: false
findWidgetVisible: false
focusedCustomEditorIsEditable: false
focusedSessionIsAttach: false
focusedView: ""
foldingEnabled: true
gitOpenRepositoryCount: "7"
groupActiveEditorDirty: false
groupEditorsCount: 1
hasNextTabstop: false
hasOtherSuggestions: false
hasPrevTabstop: false
hasSnippetCompletions: false
hasWordHighlights: false
inCommandsPicker: false
inDebugMode: false
inDiffEditor: false
inFilesPicker: false
inQuickOpen: false
inSnippetMode: false
inZenMode: false
inputFocus: true
isCenteredLayout: false
isDevelopment: false
isDominatedByLongLines: false
isFileSystemResource: true
isFullscreen: false
isInEmbeddedEditor: false
isLinux: false
isMac: false
isMacNative: false
isWeb: false
isWindows: true
isWordWrapMinified: false
jumpToCursorSupported: false
listAutomaticKeyboardNavigation: true
listSupportsKeyboardNavigation: true
loadedScriptsSupported: false
markersNavigationVisible: false
messageVisible: false
multiCursorModifier: "altKey"
multipleEditorGroups: true
notificationCenterVisible: false
notificationToastsVisible: false
npm.canMove: true
npm.defaultViewLocation: true
onTypeRenameInputVisible: false
openEditorsVisible: false
outline.active: true
outline.canMove: true
outline.defaultViewLocation: true
outputView.scrollLock: false
panelFocus: false
panelPosition: "right"
parameterHintsMultipleSignatures: false
parameterHintsVisible: false
refactorPreview.canMove: false
refactorPreview.defaultViewLocation: true
refactorPreview.enabled: false
referenceSearchVisible: false
references-view.tree.canMove: true
references-view.tree.defaultViewLocation: true
remoteAuthority: ""
remoteName: ""
renameInputVisible: false
replaceInputFocussed: false
resource: u {scheme: "vscode-userdata", authority: "", path: "/C:/Users/adbyrd/AppData/Roaming/Code/User/keybindings.json", query: "", fragment: "", …}
resourceExtname: ".json"
resourceFilename: "keybindings.json"
resourceLangId: "jsonc"
resourceScheme: "vscode-userdata"
resourceSet: true
restartFrameSupported: false
saveConflictResolutionContext: false
scmProvider: "scm0"
showUserDataSyncLocalBackupView: false
showUserDataSyncRemoteBackupView: false
sideBarFocus: false
sideBarVisible: false
splitEditorsVertically: false
sshHosts.active: true
sshHosts.canMove: true
sshHosts.defaultViewLocation: true
stepBackSupported: false
suggestWidgetDetailsVisible: false
suggestWidgetMultipleSuggestions: false
suggestWidgetVisible: false
suggestionCanResolve: false
suggestionHasInsertAndReplaceRange: false
suggestionMakesTextEdit: true
supportedCodeAction: ""
syncEnabled: false
syncStatus: "uninitialized"
targetsContainers.active: true
targetsContainers.canMove: true
targetsContainers.defaultViewLocation: true
targetsWsl.active: true
targetsWsl.canMove: true
targetsWsl.defaultViewLocation: true
taskRunning: false
terminalA11yTreeFocus: false
terminalFindWidgetFocused: false
terminalFindWidgetInputFocused: false
terminalFindWidgetVisible: false
terminalFocus: false
terminalIsOpen: true
terminalTextSelected: false
textCompareEditorActive: false
textCompareEditorVisible: false
textInputFocus: true
timeline.active: true
timeline.canMove: true
timeline.defaultViewLocation: true
treeView.CppReferencesView.enableCollapseAll: false
treeView.CppReferencesView.enableRefresh: false
treeView.CppRenameCandidatesView.enableCollapseAll: false
treeView.CppRenameCandidatesView.enableRefresh: false
treeView.CppRenamePendingView.enableCollapseAll: false
treeView.CppRenamePendingView.enableRefresh: false
treeView.detailsContainers.enableCollapseAll: false
treeView.detailsContainers.enableRefresh: false
treeView.npm.enableCollapseAll: true
treeView.npm.enableRefresh: false
treeView.references-view.tree.enableCollapseAll: false
treeView.references-view.tree.enableRefresh: false
treeView.sshHosts.enableCollapseAll: false
treeView.sshHosts.enableRefresh: false
treeView.targetsContainers.enableCollapseAll: false
treeView.targetsContainers.enableRefresh: false
treeView.targetsWsl.enableCollapseAll: false
treeView.targetsWsl.enableRefresh: false
treeView.workbench.views.sync.localBackupView.enableCollapseAll: true
treeView.workbench.views.sync.localBackupView.enableRefresh: true
treeView.workbench.views.sync.remoteBackupView.enableCollapseAll: true
treeView.workbench.views.sync.remoteBackupView.enableRefresh: true
updateState: "idle"
webviewFindWidgetFocused: false
webviewFindWidgetVisible: false
webviewHasOwnEditFunctions: false
workbench.debug.breakPointsView.active: true
workbench.debug.breakPointsView.canMove: true
workbench.debug.breakPointsView.defaultViewLocation: true
workbench.debug.callStackView.active: true
workbench.debug.callStackView.canMove: true
workbench.debug.callStackView.defaultViewLocation: true
workbench.debug.loadedScriptsView.canMove: true
workbench.debug.loadedScriptsView.defaultViewLocation: true
workbench.debug.variablesView.active: true
workbench.debug.variablesView.canMove: true
workbench.debug.variablesView.defaultViewLocation: true
workbench.debug.watchExpressionsView.active: true
workbench.debug.watchExpressionsView.canMove: true
workbench.debug.watchExpressionsView.defaultViewLocation: true
workbench.debug.welcome.canMove: false
workbench.debug.welcome.defaultViewLocation: true
workbench.explorer.fileView.active: true
workbench.explorer.fileView.canMove: false
workbench.explorer.fileView.defaultViewLocation: true
workbench.explorer.openEditorsView.canMove: true
workbench.explorer.openEditorsView.defaultViewLocation: true
workbench.panel.markers.view.active: true
workbench.panel.markers.view.canMove: true
workbench.panel.markers.view.defaultViewLocation: true
workbench.panel.output.active: true
workbench.panel.output.canMove: true
workbench.panel.output.defaultViewLocation: true
workbench.panel.output.visible: true
workbench.panel.repl.view.active: true
workbench.panel.repl.view.canMove: true
workbench.panel.repl.view.defaultViewLocation: true
workbench.panel.terminal.active: true
workbench.panel.terminal.canMove: true
workbench.panel.terminal.defaultViewLocation: true
workbench.panel.terminal.visible: false
workbench.view.search.active: true
workbench.view.search.canMove: true
workbench.view.search.defaultViewLocation: false
workbench.views.sync.localBackupView.canMove: true
workbench.views.sync.localBackupView.defaultViewLocation: true
workbench.views.sync.remoteBackupView.canMove: true
workbench.views.sync.remoteBackupView.defaultViewLocation: true
workbenchState: "workspace"
workspaceFolderCount: 18
workspaceFolderRecommendations: true
workspaceRecommendations: true
```
</details>

<details>
  <summary>Context with Output open and focus in Output:</summary>

```
CppReferencesView.canMove: true
CppReferencesView.defaultViewLocation: true
CppRenameCandidatesView.canMove: true
CppRenameCandidatesView.defaultViewLocation: true
CppRenamePendingView.canMove: true
CppRenamePendingView.defaultViewLocation: true
acceptSuggestionOnEnter: true
accessibilityHelpWidgetVisible: false
accessibilityModeEnabled: false
activeEditor: "workbench.editors.files.textFileEditor"
activeEditorGroupEmpty: false
activeEditorGroupIndex: 2
activeEditorGroupLast: true
activeEditorIsReadonly: false
activeLogOutput: false
activePanel: "workbench.panel.output"
activeViewlet: ""
addToWorkspaceFolderRecommendations: false
addToWorkspaceRecommendations: false
atEndOfWord: false
authTokenStatus: "Initializing"
autoSaveAfterShortDelayContext: false
breakpointSelected: false
breakpointWidgetVisible: false
breakpointsExist: true
callHierarchyVisible: false
canNavigateBack: true
canNavigateForward: false
canNavigateToLastEditLocation: true
canRedo: false
canReopenClosedEditor: true
canUndo: false
config.breadcrumbs.enabled: false
config.diffEditor.ignoreTrimWhitespace: true
config.editor.columnSelection: false
config.editor.minimap.enabled: false
config.editor.renderControlCharacters: true
config.editor.renderWhitespace: "all"
config.files.autoSave: "off"
config.git.allowForcePush: false
config.git.enabled: true
config.materialTheme.accent: undefined
config.npm.enableScriptExplorer: false
config.remote.SSH.enableWebAccess: undefined
config.remote.SSH.useLocalServer: true
config.window.menuBarVisibility: "toggle"
config.workbench.activityBar.visible: false
config.workbench.editor.enablePreview: false
config.workbench.editor.showTabs: true
config.workbench.sideBar.location: "left"
config.workbench.statusBar.visible: true
conflictsSources: ""
customEditors: ""
debugConfigurationType: "cppvsdbg"
debugState: "inactive"
debugUx: "default"
detailsContainers.canMove: true
detailsContainers.defaultViewLocation: true
dirtyDiffVisible: false
dirtyWorkingCopies: true
editorAreaVisible: true
editorColumnSelection: false
editorFocus: false
editorHasCallHierarchyProvider: false
editorHasCodeActionsProvider: true
editorHasCodeLensProvider: false
editorHasCompletionItemProvider: true
editorHasDeclarationProvider: false
editorHasDefinitionProvider: false
editorHasDocumentFormattingProvider: false
editorHasDocumentHighlightProvider: false
editorHasDocumentSelectionFormattingProvider: false
editorHasDocumentSymbolProvider: false
editorHasHoverProvider: false
editorHasImplementationProvider: false
editorHasMultipleDocumentFormattingProvider: false
editorHasMultipleDocumentSelectionFormattingProvider: false
editorHasMultipleSelections: false
editorHasReferenceProvider: false
editorHasRenameProvider: false
editorHasSelection: false
editorHasSignatureHelpProvider: false
editorHasTypeDefinitionProvider: false
editorId: "vs.editor.ICodeEditor:3"
editorIsOpen: true
editorLangId: "Log"
editorReadonly: true
editorSimpleInput: false
editorTabMovesFocus: true
editorTextFocus: false
expressionSelected: false
extensions.builtInBasicsExtensionsList.canMove: false
extensions.builtInBasicsExtensionsList.defaultViewLocation: true
extensions.builtInExtensionsList.canMove: false
extensions.builtInExtensionsList.defaultViewLocation: true
extensions.builtInThemesExtensionsList.canMove: false
extensions.builtInThemesExtensionsList.defaultViewLocation: true
extensions.disabledExtensionList2.canMove: false
extensions.disabledExtensionList2.defaultViewLocation: true
extensions.disabledExtensionList.canMove: false
extensions.disabledExtensionList.defaultViewLocation: true
extensions.enabledExtensionList2.canMove: false
extensions.enabledExtensionList2.defaultViewLocation: true
extensions.enabledExtensionList.canMove: false
extensions.enabledExtensionList.defaultViewLocation: true
extensions.listView.canMove: false
extensions.listView.defaultViewLocation: true
extensions.otherrecommendedList.canMove: false
extensions.otherrecommendedList.defaultViewLocation: true
extensions.popularExtensionsList.canMove: false
extensions.popularExtensionsList.defaultViewLocation: true
extensions.recommendedList.canMove: false
extensions.recommendedList.defaultViewLocation: true
extensions.vscode-local.default.canMove: false
extensions.vscode-local.default.defaultViewLocation: true
extensions.vscode-local.installed.canMove: false
extensions.vscode-local.installed.defaultViewLocation: true
extensions.vscode-local.outdated.canMove: false
extensions.vscode-local.outdated.defaultViewLocation: true
extensions.workspaceRecommendedList.canMove: false
extensions.workspaceRecommendedList.defaultViewLocation: true
findWidgetVisible: false
focusedCustomEditorIsEditable: false
focusedSessionIsAttach: false
focusedView: ""
foldingEnabled: false
gitOpenRepositoryCount: "7"
hasNextTabstop: false
hasOtherSuggestions: false
hasPrevTabstop: false
hasWordHighlights: false
inCommandsPicker: false
inDebugMode: false
inDiffEditor: false
inFilesPicker: false
inOutput: true
inQuickOpen: false
inSnippetMode: false
inZenMode: false
inputFocus: true
isCenteredLayout: false
isDevelopment: false
isDominatedByLongLines: false
isFullscreen: false
isInEmbeddedEditor: false
isLinux: false
isMac: false
isMacNative: false
isWeb: false
isWindows: true
isWordWrapMinified: false
jumpToCursorSupported: false
listAutomaticKeyboardNavigation: true
listSupportsKeyboardNavigation: true
loadedScriptsSupported: false
markersNavigationVisible: false
messageVisible: false
multiCursorModifier: "altKey"
multipleEditorGroups: true
notificationCenterVisible: false
notificationToastsVisible: false
npm.canMove: true
npm.defaultViewLocation: true
onTypeRenameInputVisible: false
openEditorsVisible: false
outline.active: true
outline.canMove: true
outline.defaultViewLocation: true
outputView.scrollLock: false
panelFocus: false
panelPosition: "right"
parameterHintsMultipleSignatures: false
parameterHintsVisible: false
refactorPreview.canMove: false
refactorPreview.defaultViewLocation: true
refactorPreview.enabled: false
referenceSearchVisible: false
references-view.tree.canMove: true
references-view.tree.defaultViewLocation: true
remoteAuthority: ""
remoteName: ""
renameInputVisible: false
restartFrameSupported: false
saveConflictResolutionContext: false
scmProvider: "scm0"
showUserDataSyncLocalBackupView: false
showUserDataSyncRemoteBackupView: false
sideBarFocus: false
sideBarVisible: false
splitEditorsVertically: false
sshHosts.active: true
sshHosts.canMove: true
sshHosts.defaultViewLocation: true
stepBackSupported: false
suggestWidgetDetailsVisible: false
suggestWidgetMultipleSuggestions: false
suggestWidgetVisible: false
suggestionCanResolve: false
suggestionHasInsertAndReplaceRange: false
suggestionMakesTextEdit: true
supportedCodeAction: ""
syncEnabled: false
syncStatus: "uninitialized"
targetsContainers.active: true
targetsContainers.canMove: true
targetsContainers.defaultViewLocation: true
targetsWsl.active: true
targetsWsl.canMove: true
targetsWsl.defaultViewLocation: true
taskRunning: false
terminalA11yTreeFocus: false
terminalFindWidgetFocused: false
terminalFindWidgetInputFocused: false
terminalFindWidgetVisible: false
terminalFocus: false
terminalIsOpen: true
terminalTextSelected: false
textCompareEditorActive: false
textCompareEditorVisible: false
textInputFocus: false
timeline.active: true
timeline.canMove: true
timeline.defaultViewLocation: true
treeView.CppReferencesView.enableCollapseAll: false
treeView.CppReferencesView.enableRefresh: false
treeView.CppRenameCandidatesView.enableCollapseAll: false
treeView.CppRenameCandidatesView.enableRefresh: false
treeView.CppRenamePendingView.enableCollapseAll: false
treeView.CppRenamePendingView.enableRefresh: false
treeView.detailsContainers.enableCollapseAll: false
treeView.detailsContainers.enableRefresh: false
treeView.npm.enableCollapseAll: true
treeView.npm.enableRefresh: false
treeView.references-view.tree.enableCollapseAll: false
treeView.references-view.tree.enableRefresh: false
treeView.sshHosts.enableCollapseAll: false
treeView.sshHosts.enableRefresh: false
treeView.targetsContainers.enableCollapseAll: false
treeView.targetsContainers.enableRefresh: false
treeView.targetsWsl.enableCollapseAll: false
treeView.targetsWsl.enableRefresh: false
treeView.workbench.views.sync.localBackupView.enableCollapseAll: true
treeView.workbench.views.sync.localBackupView.enableRefresh: true
treeView.workbench.views.sync.remoteBackupView.enableCollapseAll: true
treeView.workbench.views.sync.remoteBackupView.enableRefresh: true
updateState: "idle"
webviewFindWidgetFocused: false
webviewFindWidgetVisible: false
webviewHasOwnEditFunctions: false
workbench.debug.breakPointsView.active: true
workbench.debug.breakPointsView.canMove: true
workbench.debug.breakPointsView.defaultViewLocation: true
workbench.debug.callStackView.active: true
workbench.debug.callStackView.canMove: true
workbench.debug.callStackView.defaultViewLocation: true
workbench.debug.loadedScriptsView.canMove: true
workbench.debug.loadedScriptsView.defaultViewLocation: true
workbench.debug.variablesView.active: true
workbench.debug.variablesView.canMove: true
workbench.debug.variablesView.defaultViewLocation: true
workbench.debug.watchExpressionsView.active: true
workbench.debug.watchExpressionsView.canMove: true
workbench.debug.watchExpressionsView.defaultViewLocation: true
workbench.debug.welcome.canMove: false
workbench.debug.welcome.defaultViewLocation: true
workbench.explorer.fileView.active: true
workbench.explorer.fileView.canMove: false
workbench.explorer.fileView.defaultViewLocation: true
workbench.explorer.openEditorsView.canMove: true
workbench.explorer.openEditorsView.defaultViewLocation: true
workbench.panel.markers.view.active: true
workbench.panel.markers.view.canMove: true
workbench.panel.markers.view.defaultViewLocation: true
workbench.panel.output.active: true
workbench.panel.output.canMove: true
workbench.panel.output.defaultViewLocation: true
workbench.panel.output.visible: true
workbench.panel.repl.view.active: true
workbench.panel.repl.view.canMove: true
workbench.panel.repl.view.defaultViewLocation: true
workbench.panel.terminal.active: true
workbench.panel.terminal.canMove: true
workbench.panel.terminal.defaultViewLocation: true
workbench.panel.terminal.visible: false
workbench.view.search.active: true
workbench.view.search.canMove: true
workbench.view.search.defaultViewLocation: false
workbench.views.sync.localBackupView.canMove: true
workbench.views.sync.localBackupView.defaultViewLocation: true
workbench.views.sync.remoteBackupView.canMove: true
workbench.views.sync.remoteBackupView.defaultViewLocation: true
workbenchState: "workspace"
workspaceFolderCount: 18
workspaceFolderRecommendations: true
workspaceRecommendations: true
```
</details>

Version: 1.45.0-insider (user setup)
Commit: 2225d77536d12fea2eda04930f431a5eb0930bba
Date: 2020-04-09T09:22:11.706Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2020-04-14 09:04
Does it also works when you have debug console is opened and is focused?

**Comment by akbyrd** [comment] 2020-04-14 16:08
It works correctly with the debug console

**Comment by sandy081** [comment] 2020-06-11 18:40
Output view uses the editor to show content and hence `editorFocus` context also applies to it. Moreover most of the editor commands like `find` are also used in output editor and these commands use this context.

Hence I would suggest to add another condition to your context.

`"when": "!editorFocus || focusedView == workbench.panel.output"`

**Comment by akbyrd** [comment] 2020-06-11 18:56
As a user, I have no idea that the Output view is using editor infrastructure internally. I shouldn't have to know the list of things that use an editor internally to be able to create reliable keybindings. For one it's internal details leaking out, and second any views added in the future that happen to also use an editor internally will break my keybindings.

This is still a bug. Either other views like Output shouldn't set editor related context, or we need new context that can be relied upon to mean 'actually a code editor tab'. As 'editor' is by and large used to refer to 'actual code editor tabs', the first option is clearly preferred.

**Comment by sandy081** [comment] 2020-06-12 13:28
Yes I completely agree with you but at the same time `editorFocus` context key is an internal detail and that applies to all editors inside VS Code including Output. 

It seems there is need for a context key specific to workbench editors.

@alexdima @bpasero Let me know if you have any suggestions here.

**Comment by akbyrd** [comment] 2020-06-12 16:43
> editorFocus context key is an internal detail

Do mean that `editorFocus` specifically is internal, or all context keys in general?

Context keys are vital to being able to create keybindings. We can see that when looking at the default keybindings. And as keybindings are customizable by users, it's necessary for users to interact directly with them, Unless you limit keybindings to being able to change `key`, but only ever use the exact set of `command`/`when` pairs that ship with the application then context keys are user-facing.

Further, the built-in keybinding editor allows you to change the when expression.
![image](https://user-images.githubusercontent.com/484784/84525656-dc544600-ac90-11ea-8d46-a33980307876.png)

And `editorFocus` is in the public documentation!
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by akbyrd** [comment] 2020-09-01 16:22
I just confirmed this issue still exists on 1.48.2. I believe the conversation here already has all the information necessary.

**Comment by akbyrd** [comment] 2020-11-21 17:35
The needs more info tag was never removed after the last time I confirmed the issue. I don't believe any further info is necessary at the moment and that tag should be removed.

**Comment by sandy081** [comment] 2020-11-27 09:39
Unfortunately, there is no solution for this other than using `inOutput` context key because Output view is an editor itself. Hence closing this as designed.

@alexdima Please feel free to jump in if you other suggestions.

**Closed** 2020-11-27 09:39 UTC
Labels: *as-designed
