### ISSUE TITLE
Fold Toggle

### ISSUE THREAD

**Issue by Brocco** [microsoft/vscode#81057] opened 2019-09-17 15:50 UTC
Currently the keyboard shortcuts for folding are either "fold ___" or "unfold ___". What I would like to have is the behavior similar to cmd+/ which toggles comments, but for folding.

What I would like to see/have is the ability to bind a keyboard shortcut that would fold based upon the current line if unfolded, or unfold if it is folded.

Note: This would not need to be mapped by default, just an option that users could assign a shortcut to.

**Comment by aeschli** [comment] 2019-09-18 06:46
duplicate of #18549

**Closed by aeschli** 2019-09-18 06:46 UTC
