### ISSUE TITLE
"Peek Call Hierarchy" context menu not available while Peek is open

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#84740] opened 2019-11-13 21:45 UTC
Issue Type: <b>Bug</b>

This could be related to, or a dup of, #6857; However, that issue is more focused on cascading peek.

1. With VS Code open and an extension running providing Call Hierarchy suport:
    1. Right-click a valid location in the editor and select "Peek Call Hierarchy":
    ![image](https://user-images.githubusercontent.com/3902892/68806885-a3c98c80-061b-11ea-8177-77325200d1a3.png)
    1. Right-click a *different* valid location in the same editor.

Expected:

- "Peek Call Hierarchy" is available as an option at the new location.

Actual:

- "Peek Call Hierarchy" is hidden and the existing Peek window must be closed before the menu will reappear:
    ![image](https://user-images.githubusercontent.com/3902892/68806941-c065c480-061b-11ea-9aa4-d7fedb0bd597.png)

VS Code version: Code - OSS Dev 1.41.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment] 2019-11-14 06:04
/duplicate of https://github.com/microsoft/vscode/issues/6857

**Closed** 2019-11-14 06:04 UTC
Labels: *duplicate
