### ISSUE TITLE
Customize Code action list items

### ISSUE THREAD

**Issue by OoDeLally** [microsoft/vscode#123948] opened 2021-05-15 13:34 UTC
VSCode currently has built-in language features.
I am using Typescript, and I'm happy to have this convenient Code Action List:
![image](https://user-images.githubusercontent.com/1717629/118362926-2ffe9c00-b592-11eb-8ea3-21ce39e51b9f.png)

However, there are many items of this list that I never ever use, and they are just cluttering the list.

For example, I never use `Learn more about JS/TS Refactoring`. I understand it can be great for new users, but at some point it becomes clutter.

I also never use `Add missing function...`, as there are too many details about the missing function that VSCode cannot guess and it makes this feature not-good-enough-to-be-useful.

What I would like is being about to remove/hide the options I know will never use.

I've digged a bit in the source code to remove that `Learn more about JS/TS Refactoring`, and this item seems to be added here:
https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/commands/index.ts#L33

However, on my machine with the compiled code, I haven't been able to localize where this piece of code is located (I use the snap format).

In the short term, I would be glad to learn how to disable this on my machine, maybe by modifying the code on my running vscode.
Ideally of course, it would be awesome to be able to disabled some of the suggestions in the settings panel.

**Comment by mjbvz** [comment] 2021-05-19 19:04
Duplicate of #121374

**Closed by mjbvz** 2021-05-19 19:04 UTC
