### ISSUE TITLE
Typescript 4.0.2 No problems detected

### ISSUE THREAD

**Issue by kevingcfcb88** [microsoft/vscode#105787] opened 2020-09-01 04:28 UTC
- VSCode Version: 1.48.2
- OS Version: Debian 10

Steps to Reproduce:

1. Install globally typescript using npm install -g typescript.
2. Set typescript version:
```
{
  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
}
```
3. No errors are shown or marked on screen
![image](https://user-images.githubusercontent.com/8338747/91794503-72d13d00-ebd8-11ea-9a16-fe93969e6c5c.png)

4. Try to create a file tsconfig.json in the project's root path and the behavior is the same:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2016",
    "jsx": "preserve",
    "checkJs": true,
    "allowJs": true,
    "sourceMap": true
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-09-02 00:16
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by kevingcfcb88** [comment] 2020-09-02 06:09
Hi,

It looks like it is working using that version, just uninstall previous version install new version using .deb package.

Regards.

**Comment by mjbvz** [comment] 2020-09-08 23:07
Closing since 1.49 is the first build we officially support TS 4.0. Older builds usually work with newer TS version but this may not always be the case

**Closed by mjbvz** 2020-09-08 23:07 UTC
Labels: needs more info
