### ISSUE TITLE
Settings Sync: Ignore a setting locally

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89627] opened 2020-01-29 15:55 UTC
Refs: #89358

I tried to ignore the setting "editor.fontFamily" from being synced on linux (because I had issues with installing the nice coding fonts there).

So I added "editor.fontFamily" to the "sync.ignoredSettings" setting on linux.

But because "sync.ignoredSettings" is synced too, the setting now is ignored everywhere (which I didn't intend).

@sandy081 suggested to add "sync.ignoredSettings" to itself which seems to work..

But this approach appeared to be a kludge and it is very difficult to understand what is going on now. In order to understand whether a specific setting is synced, you have to check whether it is mentioned in the "sync.ignoredSettings" setting and then you have to check whether "sync.ignoredSettings" refers to itself...

What I would really like to have is a simple and direct way to exclude settings from syncing. E.g. adding a '!' as the first character of a settings name excludes it from syncing. Or nesting settings within a section named "!" or "nosync" excludes them all from syncing.

The "sync.ignoredSettings" approach is a bit ugly because it relies on another setting, which is again prone to another level of syncing complexity.

**Comment by sandy081** [comment] 2020-02-12 15:22
> But because "sync.ignoredSettings" is synced too, the setting now is ignored everywhere everywhere (which I didn't intend).

Is it that you want to ignore this setting on this machine or you want this to be synced only in linux platforms. This looks to me a scenario for platform specific settings.

**Comment by weinand** [comment] 2020-02-12 16:18
Yes, in this specific case I could have used a linux specific setting.
But in general excluding settings from sync by using another setting that needs to be excluded from sync remains tricky...

**Comment by sandy081** [comment] 2020-02-13 17:45
> But in general excluding settings from sync by using another setting that needs to be excluded from sync remains tricky...

Agreed. But this setting is synced by default because If a user ignore a setting then it is expected to be ignored everywhere.

I do not see a use case of ignoring a setting only on local machine.

**Comment by weinand** [comment] 2020-02-14 07:54
use case: for security reasons I do not want to leak a single setting to anywhere.

**Comment by sandy081** [comment] 2020-02-18 08:13
Do you mean value of the setting or the setting id?

**Comment by sandy081** [comment] 2020-02-25 15:58
Moving this to backlog and will get back to this if we get a use case to have ignored setting which should not be synced.

**Comment by sandy081** [comment] 2020-08-25 11:23
@jsejcksn your request is related to https://github.com/microsoft/vscode/issues/5595

**Comment by jsejcksn** [comment] 2020-08-25 22:36
> your request is related to https://github.com/microsoft/vscode/issues/5595

Thanks, yes a duplicate of [this comment](https://github.com/microsoft/vscode/issues/5595#issuecomment-632987054)

**Closed** 2020-11-16 14:47 UTC
Labels: *out-of-scope, settings-sync, under-discussion
