### ISSUE TITLE
Scrolling left side of preview mode doesn't scroll right side

### ISSUE THREAD

**Issue by timheuer** [Microsoft/vscode#31390] opened 2017-07-25 14:47 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6

---

Steps to Reproduce:

1. Open a MD file
2. Click the preview mode so that the doc is left source/right preview
3. Scroll the right preview doc
OBSERVE: left source doc scrolls
4. Scroll the left source doc
EXPECT: right preview doc scrolls
ACTUAL: right preview doc does not scroll in sync

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-07-26 04:25
Duplicate of #19459

**Closed by mjbvz** 2017-07-26 04:25 UTC
Labels: duplicate, markdown, new release
