### ISSUE TITLE
White blinks while navigating through menu bar

### ISSUE THREAD

**Issue by A-Fayez** [microsoft/vscode#83010] opened 2019-10-21 20:59 UTC
- VSCode Version: 1.38.1
- OS Version:Ubuntu 18.04 LTS

***UX bug explanation***
 - Navigating through menu bars produces a white blink before rendering the whole content which is annoying sometimes. 

***
![67242604-249acb80-f456-11e9-9d76-9885a1638e2c](https://user-images.githubusercontent.com/31468857/75129031-c154ca80-56cf-11ea-94f4-ec84ca759546.png)

Does this issue occur when all extensions are disabled?: Yes.

**Comment by sbatten** [comment] 2019-10-22 15:56
@A-Fayez please try to reproduce with the latest insiders build of VS Code which is built with a newer version of electron. https://code.visualstudio.com/insiders/

**Comment by A-Fayez** [comment] 2019-10-22 18:09
Thanks for your reply and consideration, unfortunately, the same issue remains both on VScode insiders --version 1.40.0 and VScode --version 1.39.2
Could be caused by other factors outside vscode?

**Comment by deepak1556** [comment] 2019-11-14 02:03
Might be a gpu issue, how does it look with running under `code --disable-gpu` flag ?

**Comment by A-Fayez** [comment] 2019-11-16 19:49
Still the same with ```code --disable-gpu```. The test was made when extensions are disabled.

**Comment by RonaldinhoL** [comment] 2020-03-13 13:10
the same problem.

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.23-1-MANJARO

**Comment by deepak1556** [comment] 2020-03-31 20:37
Closing this as duplicate of https://github.com/microsoft/vscode/issues/80798, please follow that issue for updates. Thanks!

**Closed by deepak1556** 2020-03-31 20:37 UTC
Labels: needs more info
