### ISSUE TITLE
Text in unified diff is not selectable

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#141740] opened 2022-01-28 16:53 UTC
When viewing diffs in git you can make the diff view unified via button or setting. All text in this view should be selectable.

**Comment by IllusionMH** [comment] 2022-01-28 19:47
/duplicate of #8226
Please upvote that issue.
Also see https://github.com/microsoft/vscode/issues/8226#issuecomment-528103843 for currently available solution.

**Closed** 2022-01-28 19:47 UTC
Labels: *duplicate
