### ISSUE TITLE
Integrated Terminal Processes Not Stopped on VSCode Close or Reload

### ISSUE THREAD

**Issue by kdawg1406** [Microsoft/vscode#32030] opened 2017-08-04 16:06 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10 Ent

Steps to Reproduce:

1. Using Vue.js CLI, create a new project
2. Open project with VSCode
3. Open integrated terminal
4. execute command:  npm run dev  (this will start up the auto reload feature of the Vue.js CLI and will launch the browser.)
5. Use the extensions tab and reload an extension or close VSCode.

Easy to follow steps for creating project and launching are here:  [https://vuejs.org/v2/guide/installation.html](https://vuejs.org/v2/guide/installation.html)

**Expected**:  VSCode would gracefully terminate the process running in the integrated command terminal. 

**Actual:** VSCode closes, but leaves the process started by the now closed integrated terminal running.  The only way to terminate the process is to use task manager.  This issue is very difficult to figure out the first time it happens.  In my case, I reloaded VSCode after starting up a terminal process.  When VSCode reopened, I tried re-running:  npm run dev.  I got a bizarre error about having the wrong version of Node.js installed on my machine.  An hour later I figured out what happened, but it was painful.

Please add a feature for VSCode to gracefully terminate any integrated terminal processes before it closes or reloads.

Thank you!!

Karl Shifflett
Microsoft MVP.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-08-04 21:22
Duplicate of https://github.com/Microsoft/vscode/issues/26807

**Closed by Tyriar** 2017-08-04 21:22 UTC
Labels: integrated-terminal
