### ISSUE TITLE
Intellisense speed issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10621] opened 2016-08-17 16:10 UTC
- VSCode Version: Code - Insiders 1.5.0-insider (55168276e4c0b6ec2404ac20af04eeed5f5b1000, 2016-08-17T06:04:29.075Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. When I type `db` slowly then its ok (first part of gif)
2. If I type `db` quickly then its bad (second part of gif

![gfjq4t96za](https://cloud.githubusercontent.com/assets/1723815/17743907/8b0f4d94-6473-11e6-9319-7396f0f775b3.gif)

**Comment by alexandrudima** [comment] 2016-08-18 06:12
fyi @jrieken

**Comment by joaomoreno** [comment] 2016-08-18 06:55
Yes I've been hitting this recently and it's hurting me too...

**Comment by joaomoreno** [comment] 2016-08-18 07:18
This to me is the worst, and I'm hitting it daily: I just type `this.` and I get `screen.` accepted...

![bug](https://cloud.githubusercontent.com/assets/22350/17765192/955294f8-6524-11e6-9f65-52abf1098cb1.gif)

Something definitely changed here.

**Comment by jrieken** [comment] 2016-08-18 08:07
Could be the changes I recently made (and am still making). Would be surprise if nothing breaks...

**Comment by joaomoreno** [comment] 2016-08-18 08:14
Having a tough time debugging it. It feels like when quickly typing `ab`, the `b` triggers a new context instead of figuring out it should still be in the same context as when `a` was pressed, just like what happens when both keypresses happen slowly.

**Comment by jrieken** [comment] 2016-08-18 08:21
I have merged my other changes, unsure about the context since I didn't touch that. I did change how suggestions are taken from the widget tho

**Comment by joaomoreno** [comment] 2016-08-18 08:28
I think this issue exists since before you started tackling this, yeah.

**Comment by jrieken** [comment] 2016-08-18 08:43
I can track [this](https://github.com/Microsoft/vscode/issues/10621#issuecomment-240643419) to the filtering in the completion model. Somehow we assume the wrong character count between triggering the request and after returning results.

![aug-18-2016 10-40-04](https://cloud.githubusercontent.com/assets/1794099/17767464/60c45648-6530-11e6-93ec-d548667fe76a.gif)

The gif shows that at pos 2 suggestion have been triggered and that 0 character have been typed such that it only uses `o` to filter/score. I believe that was caused by not using current word but overridebefore/after instead...

**Comment by jrieken** [comment] 2016-08-18 09:05
I have pushed https://github.com/Microsoft/vscode/commit/eb068a5d4e8c2820441ac296ca6e10bc1e8f3e95 that makes we filter properly when the cursor moved before we have a completion result (new CompletionModel). Before we would just take the current line content (plus n characters) and not knowing the delta. However, it doesn't really explain why we see this now since this code is in since a long time...

**Comment by joaomoreno** [comment] 2016-08-18 09:13
I have to argue that it's been around for longer than we think... Maybe something recent makes it more prominent?

**Comment by joaomoreno** [comment] 2016-08-18 09:24
I can confirm that after eb068a5, when hitting the keys at the very precise speed just as before, the behaviour changed to showing textual suggestions only:

![image](https://cloud.githubusercontent.com/assets/22350/17768833/40211254-6536-11e6-8d87-9757ebf75ba0.png)

😕

**Comment by jrieken** [comment] 2016-08-18 09:34
> Maybe something recent makes it more prominent?

Fully agree and after some thinking I believe it was [this](https://github.com/Microsoft/vscode/commit/2bc4681760511f113c663305e8d1a3d85a46d300) change. It made scoring not use the *currentWord* anymore but the *individual word* (based on overrideBefore + delta_count) which was correct before my change.

**Comment by jrieken** [comment] 2016-08-18 16:27
Closing we this should be fixed by above changes

**Closed by jrieken** 2016-08-18 16:27 UTC
Labels: bug, important
