### ISSUE TITLE
Detect links in Problems panel

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Microsoft/vscode#12156] opened 2016-09-16 15:03 UTC
- VSCode Version: 1.5.2 (1.5.2)
- OS Version: OSX 10.11.6 (15G1004)

Steps to Reproduce:
- Install the [TSLint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) extension.
- In an Angular 2 project install [codelyzer](https://www.npmjs.com/package/codelyzer)
- Make some mistake like not adding the implements OnInit and simply add the ngOnInit() { } in the Angular 2 Component:

import { Component, OnInit } from "@angular/core";

@Component({
    moduleId: module.id,
    selector: "sg-test",
    template: "`Test`"
})
export class ExamplesListDepth1Component {
    constructor() {

```
}

ngOnInit() {

}
```

}
- This will show an warning in the output of VS Code:
  ![vs code output](https://cloud.githubusercontent.com/assets/4989411/18590435/797c2fe4-7c37-11e6-9c90-4d6268a50875.png)
## Issue:

The output text contains an link with useful information provided by the codelyzer JS package but that link is not intractable by any means, I cannot click the link or copy the text to manually paste it in the browser.
## Expected/desired behavior

The text in the output to be intractable, best would be any http links to be directly clickable but simply letting us copy the output error/warnings would also be acceptable.

**Comment by sandy081** [comment] 2017-11-27 12:52
Duplicate of #11847

**Closed** 2017-11-27 12:52 UTC
Labels: *duplicate, error-list, feature-request
