### ISSUE TITLE
a problem on C++'s syntax highlighting when using a macro

### ISSUE THREAD

**Issue by ytakano** [Microsoft/vscode#16540] opened 2016-12-05 20:35 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|makeRunner|alexnesnes|0.1.1|
|language-haskell|justusadam|1.2.2|
|latexcompile|mathiasfrohlich|0.7.0|
|cpptools|ms-vscode|0.9.2|
|latex|ms-vscode|0.1.3|
|cmake|twxs|0.0.15|
|stylish-haskell|vigoo|0.0.8|

---

Steps to Reproduce:

1. add following macro at the top of a C++'s code

```
#define TIMESPECCMP(tvp, uvp, cmp)                  \
    (((tvp)->tv_sec == (uvp)->tv_sec) ?             \
        ((tvp)->tv_nsec cmp (uvp)->tv_nsec) :       \
        ((tvp)->tv_sec cmp (uvp)->tv_sec))
```

2. then the syntax highlighting does not highlight correctly

**Comment by aeschli** [comment] 2016-12-06 10:33
duplicate of https://github.com/atom/language-c/issues/185

**Closed by aeschli** 2016-12-06 10:33 UTC
