### ISSUE TITLE
IntelliSense for extensions.supportUntrustedWorkspaces doesn't show disabled extensions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122330] opened 2021-04-27 13:07 UTC
Testing #122230

* open workspace in restricted mode
* configure the `extensions.supportUntrustedWorkspaces`-setting
* :bug: IntelliSense suggestions extensions that don't require trust, like references view

<img width="546" alt="Screenshot 2021-04-27 at 15 05 56" src="https://user-images.githubusercontent.com/1794099/116246401-40c5aa00-a76a-11eb-8ad7-fadbffb5c40a.png">

**Comment by jrieken** [comment] 2021-04-27 13:18
Likely the same issue - extension that should be in there don't show up, like codespaces

<img width="935" alt="Screenshot 2021-04-27 at 15 17 52" src="https://user-images.githubusercontent.com/1794099/116248029-be3dea00-a76b-11eb-9742-ac8d3c697ed1.png">

**Comment by lszomoru** [comment] 2021-04-29 09:11
The intellisense should include all extensions that have a `main` property independent whether they support untrusted workspaces or not so that the user has full control to override the value. So that fact that the references view extension is included in the list of suggestions is by design.

Intellisense is currently provided through a built-in extension and as far as I can tell, extensions only have access to the list of extensions that are enabled. This is a problem since as you called out, these are the extensions that one might to add to the settings. I will see if we can either expand the API, or provide intellisense from `core` where we should have access to the full list of installed extensions.

**Comment by lszomoru** [comment] 2021-05-06 12:09
This has been fixed with b7b095cdf65c3097f9418c01ae0aac923ffa67dc

**Closed by lszomoru** 2021-05-06 12:09 UTC
Labels: bug, workspace-trust

**Comment by lszomoru** [comment] 2021-05-06 12:10
Verification steps:
* Open a workspace in restricted mode
* Open the `settings.json` file, and configure the `extensions.supportUntrustedWorkspaces`-setting
* Invoke intellisense and you should see extensions that are currently disabled
