### ISSUE TITLE
Provide command/keybinding to toggle "overlay hints"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129525] opened 2021-07-27 12:55 UTC
Testing #129381

This came up in our standup a while ago, not sure if it was captured in an issue.

I'm not that much of a fan of inlay hints because it shifts my code around, I disable codelens completely because I don't like this. What would be ideal for me would be some keybinding/modifier I can press to show the hints temporarily.

So instead of this:

![image](https://user-images.githubusercontent.com/2193314/127156529-aaff7c3b-12c3-4b16-98fd-8cc3f5b0af23.png)

Holding `alt` for example could show:

![image](https://user-images.githubusercontent.com/2193314/127156733-3e2ddf77-305c-4c58-82e3-7f84bec19830.png)

Or:

![image](https://user-images.githubusercontent.com/2193314/127156921-2d0ea239-2922-43fb-bc29-7cd86a83172d.png)

**Comment by Tyriar** [comment] 2021-07-27 12:57
If this is a possibility for the future, we may want to use a name more generic than `inlay` as that described how it is presented, not necessarily the underlying feature that exposes this information?

**Comment by hediet** [comment] 2021-07-27 13:26
> ![image](https://user-images.githubusercontent.com/2193314/127156921-2d0ea239-2922-43fb-bc29-7cd86a83172d.png)

I like that! But this is absolutely not doable with injected text.

**Comment by Tyriar** [comment] 2021-07-27 13:28
Yeah it wouldn't be injected text, probably a new capability in monaco? Is @mjbvz the right person to be assigned since this is a language agnostic monaco feature request?

**Comment by hediet** [comment] 2021-07-27 13:35
> Is @mjbvz the right person to be assigned since this is a language agnostic monaco feature request?

I think @jrieken did the initial implementation of inlay hints and @mjbvz the typescript integration that is new this milestone.
I just changed the rendering logic to use injected text instead of after/before css classes.

But yes, the underlying monaco feature request would be something for me and @alexdima, but I suggest to separate this inlay-hint related feature from the monaco features required to implement it.

**Comment by mjbvz** [comment] 2021-07-27 20:13
Duplicate of #128162

**Closed by mjbvz** 2021-07-27 20:13 UTC
