### ISSUE TITLE
Window activation in ozone-wayland is not working in 1.92

### ISSUE THREAD

**Issue by tokyo4j** [microsoft/vscode#225211] opened 2024-08-09 03:38 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Arch Linux (Wayland session in KDE Plasma 6.1.3)

Steps to Reproduce:

1. Open a directory with `code [directory path]` command
2. Minimize the opened VSCode window
3. Run `code [directory path]` again
4. Activation request is not sent

In `~/.config/code-flags.conf` (Arch Linux specific config file), I set following flags to run VSCode with:
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--enable-wayland-ime
```

"Activation request" here means `xdg_activation_v1::activate` request in Wayland protocol. When KWin compositor receives that request, it tells the panel to notify user that the window needs attention like below.

(Panel notifying that firefox window needs attention)
![kde-urgent](https://github.com/user-attachments/assets/01f7a226-1b3a-4098-a802-d3012d993a54)

Prior to version 1.92, xdg-activation requests were sent, which can be observed by running `WAYLAND_DEBUG=client code --log=debug --verbose | grep activation`:
```
$ WAYLAND_DEBUG=client code --log=debug --verbose | grep activation
...
[3516383.227]  -> xdg_activation_token_v1@50.set_serial(14320, wl_seat@10)
[3516383.231]  -> xdg_activation_token_v1@50.commit()
[3516387.191] xdg_activation_token_v1@50.done("not-granted-666")
[3516387.212]  -> xdg_activation_v1@23.activate("not-granted-666", wl_surface@31)
[3516387.216]  -> xdg_activation_token_v1@50.destroy()
```

**Comment by tokyo4j** [comment] 2024-08-09 03:42
I already upgraded 1.92.1 and the issue still happens. Then I reinstalled some recent versions of VSCode and found out 1.91.1 -> 1.92.0 introduced this bug.

**Comment by tokyo4j** [comment] 2024-08-09 04:14
Looks like this is a problem of Electron/Chromium. I installed electron 29.4 which VSCode 1.91.1 based on and tried following script:
```js
// In the main process.
const { app, BrowserWindow } = require("electron");

app.whenReady().then(() => {
  const win = new BrowserWindow({ width: 800, height: 600 });

  win.loadURL("https://github.com");

  setTimeout(() => {
    app.focus();
    console.log("requesting focus");
  }, 3000);
});
```

By running `WAYLAND_DEBUG=client electron29 --enable-features=UseOzonePlatform --ozone-platform=wayland main.js`, I confirmed activation requests are sent. However, they are not sent with the latest version (31.3) of Electron.

**Comment by gjsjohnmurray** [comment] 2024-08-09 08:54
pinging @deepak1556

**Comment by ReillyBrogan** [comment] 2024-10-19 19:26
This one should be fixed by the combination of #218245 (Electron added activation protocol support in v32.1.0) and #218245 (which fixed the app_id so the compositor knows which window to open in front of).

CC @deepak1556

**Comment by deepak1556** [comment] 2024-10-22 06:13
/fixedWith https://github.com/microsoft/vscode/commit/8422282f04e8401240d4bd2d1a1184d97080812e

**Closed by deepak1556** 2024-10-22 06:13 UTC
Labels: bug, upstream, linux, electron, regression, wayland

**Comment by TylerLeonhardt** [comment] 2024-10-24 18:06
Hello! Can you give this a try with the [Insiders](http://code.visualstudio.com/insiders/) build and let us know if the issue is fixed?

**Comment by tokyo4j** [comment] 2024-10-25 04:12
> Hello! Can you give this a try with the [Insiders](http://code.visualstudio.com/insiders/) build and let us know if the issue is fixed?

I tried the insider build and confirmed the issue is fixed. Thank you all for working on this!
