### ISSUE TITLE
文件多选问题

### ISSUE THREAD

**Issue by cxldada** [Microsoft/vscode#36103] opened 2017-10-12 01:42 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
beautify|Hoo|1.1.1
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.3.1
java|red|0.11.0
JavaScriptSnippets|xab|1.5.0

为什么目录树里面的文件不能按住shift进行多选 这个功能很需要啊

**Comment by caesay** [comment] 2017-10-12 04:46
This is a feature request for shift-key/shift-click support in the directory/file tree. I agree, this and cntrl-key support (replacing what cntrl-click currently does) would be great.

**Comment by cxldada** [comment] 2017-10-12 05:33
Hopefully the next version will be available


陈小龙


在2017年10月12日 12:47 ，Caelan Sayler<mailto:notifications@github.com>写道：


This is a feature request for shift-key/shift-click support in the directory/file tree. I agree, this and cntrl-key support (replacing what cntrl-click currently does) would be great.

**Comment by egamma** [comment] 2017-10-12 13:08
@caesay just to clarify by shift-click you mean support for multiple selection? This would be a duplicate of #1023.

**Comment by caesay** [comment] 2017-10-12 13:30
Yes, I was just clarifying what the post was about (multi selection, shift
click). It is indeed a duplicate.

**Comment by egamma** [comment] 2017-10-12 16:13
@caesay thanks, then I'm closing this one as a duplicate of #1023

**Closed by egamma** 2017-10-12 16:13 UTC
Labels: duplicate
