### ISSUE TITLE
Nested ternary condition containing link breaks syntax highlighting

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#6600] opened 2016-05-21 03:36 UTC
- VSCode Version:1.1.1
- OS Version:Windows 10

Steps to Reproduce:
1. Create a JS or TS file.
2.  Type a nested JS or TS ternary condition containing a string containing a link.

Ex:

`var a = true ? 0 : ('http://mySite.com' ? 1 : 0);`

![](http://puu.sh/oZu0Z.png)

Issue:
Breaks the syntax highlight for everything following the line.

**Comment by aeschli** [comment] 2016-05-23 12:57
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-05-23 12:57 UTC
