### ISSUE TITLE
User Settings in Problem view error

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#16873] opened 2016-12-08 00:20 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (af81c48568ce7419eb01e730fb830db93a105bbb, 2016-12-07T13:52:32.130Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.2|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.5|
|vscode-hexdump|slevesque|1.1.4|

---

Steps to Reproduce:

1. 
2.

![111](https://cloud.githubusercontent.com/assets/8591065/20992403/d5ceaa60-bd1e-11e6-9303-5d50af644485.gif)

**Comment by mjbvz** [comment] 2016-12-08 00:42
Thanks. I think this is a duplicate of #16842

**Closed by mjbvz** 2016-12-08 00:42 UTC
Labels: duplicate
