### ISSUE TITLE
Integrated Terminal crashes on startup

### ISSUE THREAD

**Issue by profabe** [Microsoft/vscode#8001] opened 2016-06-22 13:07 UTC
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Menu 'View'
2. Submenu 'Views'
3. Click on 'Integrated Terminal
![2016-06-22](https://cloud.githubusercontent.com/assets/7761828/16267607/f8e7a31c-388a-11e6-9f85-417d4cc9930a.png)
'

**Comment by Tyriar** [comment] 2016-06-23 03:48
@profabe can you open dev tools (Help > Toggle Developer Tools) and check for any errors in the console?

**Comment by profabe** [comment] 2016-06-23 05:26
@Tyriar many thanks for your quick response. Please see this screenshot.
![capture](https://cloud.githubusercontent.com/assets/7761828/16292646/b6cf8b3c-3913-11e6-82e5-f9c03ed88c4a.PNG)

**Comment by Tyriar** [comment] 2016-06-23 08:45
Do you have anything in your user settings.json file?

Also can you check what the `%COMSPEC%` environment variable points at?

**Comment by profabe** [comment] 2016-06-23 10:05
Please see the following screenshots.
![capture2](https://cloud.githubusercontent.com/assets/7761828/16299473/ce420b38-393a-11e6-8989-3ed8ac0d034d.PNG)
![capture](https://cloud.githubusercontent.com/assets/7761828/16299475/d0f9f822-393a-11e6-9af0-9c1ccf93a3ec.PNG)

**Comment by Tyriar** [comment] 2016-06-23 16:41
Does the same thing happen when you add this setting?

```json
"terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe"
```

**Comment by profabe** [comment] 2016-06-23 20:39
Still happens...
![capture](https://cloud.githubusercontent.com/assets/7761828/16319346/4526a67a-3993-11e6-8945-771fbeb79bc2.PNG)

**Comment by Tyriar** [comment] 2016-06-24 03:00
Last thing I can think of is try using the 64 bit cmd which is at:

```json
"terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\cmd.exe"
```

Unfortunately this is a bit tricky to debug due to the fix for https://github.com/Microsoft/vscode/issues/6469

Does this also happen on stable, or just insiders?

**Comment by profabe** [comment] 2016-06-24 13:43
It happens in both stable and insiders. Please note I just updated them to the latest version and applied the setting regarding 64 bit cmd . The error message seems to be different now:

![vscode](https://cloud.githubusercontent.com/assets/7761828/16339317/4f4b82a8-3a22-11e6-9254-6624d40420d6.PNG)

![vscodeinsiders](https://cloud.githubusercontent.com/assets/7761828/16339324/58f0aec8-3a22-11e6-9595-e02085e4ab74.PNG)

**Comment by profabe** [comment] 2016-06-24 17:53
Is there a Developer's Guide available to set up the environment? Perhaps debugging on my machine can help solving that issue.

**Comment by Tyriar** [comment] 2016-06-24 18:08
@profabe that won't help much beyond what you can already do. The terminal process ([terminalProcess.js](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js)), the thing that's crashing cannot be debugged as it's running in a different process.

Something you could do is make sure that `ENV` in [terminalService.ts' `createTerminalProcess function](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L187) is being filled as expected, in particular the `PTY*` environment variables. You can do this through devtools (Help > Toggle Developer Tools) by adding a breakpoint in `createTerminalProcess`.

You can see in [terminalProcess.js](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js) that `%PTYSHELL%` is called, passing in the args `%PTYSHELLARG1%`, `%PTYSHELLARG2%`, ... and the current working directory is set to `%PTYCWD%`.

**Comment by profabe** [comment] 2016-06-24 22:03
Something seems to be wrong when debugging. I can not set a breakpoint at line 146 and 147. Only before and after - something is wrong with the sourcemap, right? Also the env variables not being available as watch is rather strange. Did I do something wrong?

![capture](https://cloud.githubusercontent.com/assets/7761828/16351741/34ce2642-3a68-11e6-8f28-479d254a4ce2.PNG)

**Comment by Tyriar** [comment] 2016-06-24 22:34
I've experienced some issues before with sourcemaps, maybe you could try looking at the .js file and try using the variable name used there?

**Comment by profabe** [comment] 2016-06-25 14:02
The debugger only works in *.ts files not *.js files. I also tried to add some console.log statements, but the Developer Tools don't allow saving. Electron seems to be a biest in that matter. Can I somehow build a custom Visual Studio Code with these console.log statements in it? 

![capture](https://cloud.githubusercontent.com/assets/7761828/16357126/1e987f68-3aee-11e6-9f5c-798fe7b022f8.PNG)

**Comment by Tyriar** [comment] 2016-06-27 08:55
@profabe you can edit the editor files on the OS in an editor that has admin access. You can always [build a developer build](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source), it may be more work getting it working though.

**Comment by profabe** [comment] 2016-06-27 21:21
@Tyriar thanks for the hint - i managed to console log the variables:

- PTYSHELL: C:\Windows\SysWOW64\cmd.exe
- PTYCWD: c:\Users\Fabian Wohlschläger\Documents\Code\aspnetcore-workshop\MyNewApp

Both exist. Does this help to analyse the error?

**Comment by Tyriar** [comment] 2016-06-27 21:24
Great thanks. This is a duplicate of https://github.com/Microsoft/vscode/issues/7727 due to the `ä`. Pretty sure it's an upstream pty.js/winpty issue.

**Closed by Tyriar** 2016-06-27 21:24 UTC
Labels: integrated-terminal, needs more info
