### ISSUE TITLE
strange behavior of extension cache

### ISSUE THREAD

**Issue by slavik-lvovsky** [microsoft/vscode#109361] opened 2020-10-26 10:03 UTC
- VSCode Version: 1.50.0
- OS Version: Windows 10

Steps to Reproduce:

1. install globally latest version of generator-code package: npm i -g generator-code
2. create extension with one command that requires the globally install package:
const code = require(<... AppData\\Roaming\\npm\\node_modules\\generator-code>);
2.  run the command
3. install globally version 1.1.0 of generator-code package: npm i -g generator-code@1.1.0
4. restart vscode and run the command again

You get exception that shows that vscode tried to find code that is not available in the 1.1.0 version.
It seems that modules cache is not updated.

The exception that i got:

Activating extension 'slavik.ext-test-cwd' failed: Cannot find module 'C:\Users\I034050\AppData\Roaming\npm\node_modules\generator-code' Require stack: - c:\wing\ext-test-cwd\extension.js - c:\Users\I034050\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js - c:\Users\I034050\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js - c:\Users\I034050\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-10-26 10:29
Duplicate of https://www.github.com/microsoft/vscode/issues/108933

**Closed** 2020-10-26 10:30 UTC
Labels: *duplicate

**Comment by slavik-lvovsky** [comment] 2020-10-26 10:41
> Duplicate of https://www.github.com/microsoft/vscode/issues/108933
There is no response on my first issue. Please help me to understand whether it is a bug or not.
In my opinion it is a bug that is very easy to reproduce
