### ISSUE TITLE
Ligatures are broken using some themes for the shell script file type

### ISSUE THREAD

**Issue by daenney** [microsoft/vscode#100649] opened 2020-06-20 14:09 UTC
```
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.2-arch1-1
```

Steps to Reproduce:

1. Open a shell script file with a custom themes: no ligatures
2. Switch to Light/Dark or Kimbie Dark, ligatures are used

Using this simple shell script will do it, then switch between themes:
```
#!/usr/bin/env sh

test >= test
```

Does this issue occur when all extensions are disabled?: Yes

I'm having a very weird thing where on the Shell Script file type, when having ligatures enabled, the ligatures do not work when I use a custom theme, like [Nord](https://github.com/arcticicestudio/nord-visual-studio-code/issues/168). Ligatures work as expected when using a number of built-in themes, like VS Code's own dark/light themes, but others do exhibit the same issue, like Monokai. For some reason this appears to mainly affect the shell script file type.

Themes that work as expected, showing ligatures on the shell script type
* Light, Light+, Dark, Dark+, Kimbie Dark

Themes that don't show ligatures on the shell script type:
* Quiet Light, Solarized Light, Abyss, Monokai, Monokai Dimmed, Red, Solarized Dark, Tomorrow Night Blue, High Contrast

**Comment by aeschli** [comment] 2020-06-22 11:00
@alexdima You probably know whether ligatures depend on the token segments created or not.

**Comment by alexdima** [comment] 2020-06-28 09:19
@daenney I could not reproduce. I have tried with the following settings:

```
{
	"editor.fontFamily": "'Fira Code'",
	"editor.fontLigatures": true,
	"workbench.colorTheme": "Nord"
}
```

And ligatures render for me for your example:
![image](https://user-images.githubusercontent.com/5047891/85943579-37449900-b931-11ea-8ec8-6ec42e68c2a9.png)

**Comment by daenney** [comment] 2020-06-30 20:26
Interesting. I have the same settings, with the exception that the font I'm using is set to "Jetbrains Mono".

However, I think I've found something interesting.

Using 
```
if [ "$PAYLOAD_TYPE" != "PROTO" ]; then
    echo "Are ligatures broken?"
fi
```

I get ligatures.

But, the same code, written with `test` instead of `[`:

```
if test "$PAYLOAD_TYPE" != "PROTO"; then
    echo "Are ligatures broken?"
fi
```

And then I don't.

![ligatures](https://user-images.githubusercontent.com/569574/86173745-f9ea3200-bb0f-11ea-908b-1353b856d045.png)

**Comment by daenney** [comment] 2020-09-27 14:59
Hey, no fair. I provided more info.

**Comment by alexdima** [comment] 2020-12-09 09:08
I believe this was fixed in one of the recent vscode versions, when we enabled layoutNG by default. Here I am trying with the settings:
```
	"workbench.colorTheme": "Nord",
	"editor.fontFamily": "'JetBrains Mono'",
	"editor.fontLigatures": true
```

![image](https://user-images.githubusercontent.com/5047891/101608647-419daf80-3a06-11eb-9921-97da760dc89d.png)

I can confirm that this was fixed by layoutNG because when I launch `code-insiders --disable-features=LayoutNG` I can reproduce the old behavior:

![image](https://user-images.githubusercontent.com/5047891/101608792-74e03e80-3a06-11eb-96a3-a061b9eccc64.png)

**Closed by alexdima** 2020-12-09 09:08 UTC
Labels: linux, needs more info
