### ISSUE TITLE
Render tokens background color (as defined by TM themes)

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#29481] opened 2017-06-26 18:32 UTC
I'm currently experimenting on a modified syntax file for Javascript / Typescript where we can add a comment before or after a string to turn on syntax highlighting on template string for a specified syntax, ie, SQL, HTML, etc.

So far its been successful and I could see this be useful for other languages as well, ie, Markdown in a Python template string, and so on...

This is great, however, with syntax highlighting for template strings, in some context it becomes difficult to know where a template string begins or ends as all the text isn't the same color anymore. This could be easily addressed with background colors.

The issue is that VS Code doesn't allow background styling, making it difficult to see where a template string starts or ends.

**Comment by rmunn** [comment] 2017-08-04 04:01
Not a duplicate of #1751, but related since different background colors could be quite useful in #1751 as well.

**Comment by noinkling** [comment] 2017-10-11 03:20
> I'm currently experimenting on a modified syntax file for Javascript / Typescript where we can add a comment before or after a string to turn on syntax highlighting on template string for a specified syntax, ie, SQL, HTML, etc.

Has there been anything like this released? I'd love to get SQL highlighting inside strings, and comments would be a perfectly acceptable way of achieving this.

**Comment by subtleGradient** [comment] 2018-01-17 16:58
Yeah, I'm trying to bring my Brilliance White theme over from TextMate to vscode. I got it working in Atom, but it looks like the lack of background colors is a huge blocker :'(

**Comment by usernamehw** [comment] 2018-05-14 17:17
@aeschli, duplicate of #3429 ?

**Comment by aeschli** [comment] 2018-05-14 19:04
yes, dup of #3429. Thanks @usernamehw!

**Comment by usernamehw** [comment] 2018-06-10 11:53
@aeschli, so, is there a reason why this one still open?

**Closed** 2018-06-11 07:50 UTC
Labels: editor-rendering, feature-request
