### ISSUE TITLE
Syntax & Linting Errors not Displaying CSS

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#172232] opened 2023-01-24 18:07 UTC
Testing: https://github.com/microsoft/vscode/issues/172045

I am trying to test the CSS syntax and linting and am not getting errors on the following examples:
<img width="391" alt="Screenshot 2023-01-24 at 10 04 24 AM" src="https://user-images.githubusercontent.com/26030610/214373044-bcf28379-aea5-4c9a-8df6-07525ed75030.png">
<img width="380" alt="Screenshot 2023-01-24 at 10 04 32 AM" src="https://user-images.githubusercontent.com/26030610/214373050-4f01e20a-3d33-448d-8607-aacdd8991d65.png">

**Comment by aeschli** [comment] 2023-01-28 18:03
I'm not able to reproduce, I see the errors:
In a CSS file:
![image](https://user-images.githubusercontent.com/6461412/215283426-1bea2df9-5f8a-428d-8a6b-c73cd524960e.png)
In a HTML file:
![image](https://user-images.githubusercontent.com/6461412/215283438-440515e5-b9e9-4393-b36b-2898c55ad3c5.png)


Make sure your editor is in CSS / HTML mode and make sure there's no other error further up the file that confuses the parser.

**Comment by aeschli** [comment] 2023-01-28 18:37
Also check in the dev tools console whether the CSS (or HTML) language servers failed to start.

**Comment by eleanorjboyd** [comment] 2023-01-30 19:23
Hello! Now seeing the right error msg show up: 
![Screenshot 2023-01-30 at 11 22 55 AM](https://user-images.githubusercontent.com/26030610/215575248-cff7c9d7-c317-44e2-a0df-9bf51bf8d0f5.png)
![Screenshot 2023-01-30 at 11 22 43 AM](https://user-images.githubusercontent.com/26030610/215575258-35877a62-56ec-4c5a-a037-ab934be1eaf0.png)
![Screenshot 2023-01-30 at 11 22 49 AM](https://user-images.githubusercontent.com/26030610/215575256-385256b1-c555-4d0e-b6c4-6252a9202026.png)

**Comment by aeschli** [comment] 2023-01-31 07:33
Let's close the issue then. If you see it again, check the dev tools and language server outputs to get more info about what could be the problem.

**Closed by aeschli** 2023-01-31 07:33 UTC
Labels: info-needed
