### ISSUE TITLE
FileDecorationProvider intermittently fails

### ISSUE THREAD

**Issue by mattseddon** [microsoft/vscode#133210] opened 2021-09-16 02:22 UTC
Does this issue occur when all extensions are disabled?: No - I have raised https://github.com/microsoft/vscode-python/issues/17432 with the offending extension but I believe that something in VS Code may also be broken.

- VS Code Version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
- OS Version: Darwin x64 20.6.0

I am currently developing a data science extension for [iterative.ai](https://iterative.ai/) which will integrate VS Code with the [DVC cli](https://dvc.org/) (which is an open source Python project for versioning machine learning projects). Part of the extension is to do with large file management. In each repository we will have a list of `Uri`s that are `gitignored` but tracked by `DVC`. We want to deliver as native an experience as possible to users so we decorate these `Uri`s with colors that match up to the native git extension statuses (`gitDecoration.addedResourceForeground`, etc). 

We register our `FileDecorationProvider` as close as possible to the instantiation of the extension however, recently the decorations have (intermittently) started getting stomped by the `gitignore` decoration.

If I disable the Python extension then the decorations appear as expected but we would really like to be able to reliably run the extension in parallel with other extensions, especially `ms-python.python` (as we want to integrate with as much of the existing data science toolkit as possible).

I have looked into the source code and it appears that all of the decoration providers have the same weight applied. I am wondering if something has changed recently and also how our extension can be effected by the Python one in this way.
 
How are conflicts between `FileDecoration`s resolved?
Is there anything that can be done on my end to mitigate this issue?

Ideally we need a way to reliably register a `FileDecorationProvider` that will not be overwritten by the native git extension under unknown circumstances. The reason that I am raising a bug is because this worked up to a few days ago, I cannot find anything in the docs and I thought it was a solved problem. If this is a feature request then please let me know.

Steps to Reproduce:

1. Run extension in parallel with `ms-python.python`.
2. FileDecorations will intermittently be overwritten (static per session, i.e they work or they don't).

**Note**: When starting up our extension having the `ms-python.python` installed vs not installed takes instantiation time from < 20ms to ~300ms.

Thanks for taking the time to read this 👍🏻 . Please let me know if need any further details.

Extra details captured by `extension bisect`: 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 343c20dd-d8ac-482e-bcc6-2244d6ab7bb5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vshan820:30294714
vstes263cf:30335440
pythonvsuse255:30340121
vscod805cf:30301675
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
javagetstartedt:30364666
pydsgst2:30361792
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by karthiknadig** [comment] 2021-09-17 17:18
For VS Code team investigating this, we don't register a File decoration provider in the python extension. It is very strange that loading python extension is causing this. Is there anything in particular I need to look for with this?

**Comment by jrieken** [comment] 2021-09-20 07:01
> How are conflicts between FileDecorations resolved?

There is no conflict handling, multiple decorations are sorted by weight (which is the same for all extensions). When possible data is joined, like for text, and sometimes the "first" is taken, like color. 

> When starting up our extension having the ms-python.python installed vs not installed takes instantiation time from < 20ms to ~300ms.

@karthiknadig Does that ring a bell? My theory is that python loads slow and therefore prevent loading/activation of @mattseddon's extension. Therefore its decoration provider is register late, e.g after git's decoration provider.

**Comment by mattseddon** [comment] 2021-09-20 23:59
Thanks for confirmation @jrieken. We are currently working together to try and diagnose the actual cause of the issue ([in this thread](https://github.com/iterative/vscode-dvc/pull/819#discussion_r710717656)). We do plan to make the repo open source once we've got to an initial release but have sent you an invite now so that you can observe / participate if you want to.

Thanks again, 👍🏻

**Comment by karthiknadig** [comment] 2021-09-21 02:07
I can see that load time can be a possible issue. But why does the load time impact other extension's file decoration provider?

**Comment by mattseddon** [comment] 2021-09-21 04:23
> I can see that load time can be a possible issue. But why does the load time impact other extension's file decoration provider? i.e why does it matter that it got registered after git's decoration provider.

My understand from this:

> There is no conflict handling, multiple decorations are sorted by weight (which is the same for all extensions). When possible data is joined, like for text, and sometimes the "first" is taken, like color.

is that the color decorations from each `FileDecorationProvider` are displayed on the basis of when each was registered. It is a first come, first served basis.

@jrieken please correct me if I am wrong.

**Comment by jrieken** [comment] 2021-09-21 06:02
> is that the color decorations from each FileDecorationProvider are displayed on the basis of when each was registered. It is a first come, first served basis.

Correct - we [store](https://github.com/microsoft/vscode/blob/bcc715e15eca0163754bb82f22095b18d5f12ded/src/vs/workbench/services/decorations/browser/decorationsService.ts#L401) decoration provider into a linked list and ask them [in order](https://github.com/microsoft/vscode/blob/bcc715e15eca0163754bb82f22095b18d5f12ded/src/vs/workbench/services/decorations/browser/decorationsService.ts#L420)

**Comment by jrieken** [comment] 2021-09-21 14:05
I have pushed a change so that later decoration provider are asked for decorations first. Please try this out with tomorrows insiders

**Comment by mattseddon** [comment] 2021-09-22 01:32
@jrieken thanks so much for looking into this and making some changes to the code. It appears that I've fixed the original issue (see https://github.com/microsoft/vscode-python/issues/17432#issuecomment-924507077 for details). This change would still be really good. I've raised a draft PR to test against the insiders build once it is released (linked directly above).

Couple of follow up questions from me:

1. Roughly how long would it be before we could expect to see the change in a stable release?
2. Will this new method be documented somewhere? (less important for me)
2. Would being able to apply a weight to the decorations be a better long term solution? (we could then provide config options to users down the track so that they can reorder themselves).
3. (IF that is a good idea) How long would we have to wait for that?

**Comment by mattseddon** [comment] 2021-09-23 00:38
I can confirm that the change behaves as expected 👍🏻 .

**Comment by jrieken** [comment] 2021-09-23 10:40
> Would being able to apply a weight to the decorations be a better long term solution? (we could then provide config options to users down the track so that they can reorder themselves).

We avoid weights because eventually all weights will be at the highest possible value and the problem repeats (just with extra complexity...) It happens that N extension contributed features conflict and than extension-configuration is key, like uninstall one extension or make extensions configurable so that they allow to resolve conflicts (like a setting to not decorate ignore files etc) 

The lifo-approach for providers is something we are doing elsewehere (e.g. language providers) and that's the best we can do for now. I am closing this without further actions

**Comment by mattseddon** [comment] 2021-09-23 19:07
Thank you very much @jrieken. Will this go out with 1.61?

**Comment by jrieken** [comment] 2021-09-24 06:47
Of course it will

**Comment by mattseddon** [comment] 2021-09-24 06:59
Thank you!

**Comment by mattseddon** [comment] 2021-11-05 05:34
@jrieken there seems to have been a regression with this in the latest version.

I can see in the code that we've gone back from `shift` to `push` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/decorations/browser/decorationsService.ts#L266).

Was this intentional? Would a PR be welcome?

**Comment by jrieken** [comment] 2021-11-05 07:40
Oh, no... Sorry for that. Clear a regression, I guess my brain is wired to use `push` over `unshift`...

**Comment by jrieken** [comment] 2021-11-05 08:01
Pushed a fix. This time a test too 🙈

**Comment by mattseddon** [comment] 2021-11-05 08:02
Thank you @jrieken

**Closed** 2021-11-05 08:01 UTC
Labels: file-decorations
