### ISSUE TITLE
Reload Window doesn't work after I update

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#63700] opened 2018-11-23 21:51 UTC
Issue Type: <b>Bug</b>

On Linux after I do a general update using "apt-get", when the new version of code-insider is updated. I press CTRL+SHIFT+P and type "reload window".

What happen is all the running instances close and they don't get reloaded. This happens every time I do an update.

I then need to kill a running instance of code-insider before relaunching.

VS Code version: Code - Insiders 1.30.0-insider (04cbc78e23eeddc368d634ed52402dbc6f28ebc9, 2018-11-23T10:01:24.656Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 2|
|Memory (System)|15.66GB (4.94GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|9.3.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
solidity|Jua|0.0.47
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.16
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.34.0
language-stylus|sys|1.10.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.11.0
vscode-maven|vsc|0.11.2
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-11-26 10:16
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by rajinder-yadav** [comment] 2018-12-02 01:09
Did something break with how code-insider updates on Linux? I know before I could:

```sh
sudo apt-get update
```

This would update code-insider for me, no that doesn't happen. Also I keep seeing an update button for code-insider but I am unable to update as before?

```
yadav@source$ code-insiders --verbose
(code-insiders:9144): Gtk-WARNING **: 20:06:45.287: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(code-insiders:9144): Gtk-WARNING **: 20:06:45.287: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(code-insiders:9144): Gtk-WARNING **: 20:06:45.287: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[9177:1201/200645.775107:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 20:06:45] Sending env to running instance...
[main 20:06:46] Sent env to running instance. Terminating...
[main 20:06:46] Lifecycle#kill()
```

**Comment by rajinder-yadav** [comment] 2018-12-02 01:21
Just installed the code-insider debian pack for versionb 1.30.0-insider

```
yadav@source$ code-insiders --verbose
(code-insiders:13858): Gtk-WARNING **: 20:15:39.621: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(code-insiders:13858): Gtk-WARNING **: 20:15:39.621: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(code-insiders:13858): Gtk-WARNING **: 20:15:39.621: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[13892:1201/201540.094395:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 20:15:40] Starting VS Code
[main 20:15:40] from: /usr/share/code-insiders/resources/app
[main 20:15:40] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 20:15:40] Resolving machine identifier...
[main 20:15:40] Resolved machine identifier: e74965a1d85a0021452497f6348d4a577cb10e2fff5d60eab36217e0f30251c5
[main 20:15:40] update#setState idle
[main 20:15:40] windowsManager#open
[main 20:15:40] telemetry/optInStatus { optIn: true }
[13858:1201/201541.576528:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.587197:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.600498:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.626132:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.626363:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.628691:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.638083:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201541.821842:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.316245:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:42] IPC#vscode-workbenchReady
[main 20:15:42] windowsService#whenSharedProcessReady
[main 20:15:42] windowsService#getRecentlyOpened 1
[13858:1201/201542.329277:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:42] windowsService#setRepresentedFilename 1
[main 20:15:42] windowsService#isFocused 1
[13858:1201/201542.379010:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.380183:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.380567:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.380825:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:42] windowsService#startCrashReporter
[13858:1201/201542.518258:INFO:CONSOLE(1480)] "%cDEBUG", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1480)
[main 20:15:42] windowsService#getRecentlyOpened 1
[13858:1201/201542.592914:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.593526:INFO:CONSOLE(3233)] "%c[Extension Host] %cdebugger listening on port 31496", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3233)
[13858:1201/201542.672756:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.673113:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.695390:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.701866:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.711605:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:42] windowsService#setRepresentedFilename 1
[13858:1201/201542.801524:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.809651:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.820297:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201542.845870:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.006137:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.146884:INFO:CONSOLE(3230)] "Extension Host", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3230)
[13858:1201/201543.147101:INFO:CONSOLE(3230)] "%cDebugger listening on ws://127.0.0.1:31496/cfca08c5-f4aa-403a-8516-7dc2f3465e7d
For help see https://nodejs.org/en/docs/inspector
", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3230)
[13858:1201/201543.147246:INFO:CONSOLE(3231)] "console.groupEnd", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3231)
[13858:1201/201543.276617:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:43] IPC#vscode:broadcast vscode:changeColorTheme {"baseTheme":"vs-dark","background":"#21252b"}
[13858:1201/201543.277811:INFO:CONSOLE(1480)] "%cDEBUG", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1480)
[13858:1201/201543.308169:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.309003:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.319643:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.320418:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.320683:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.480056:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.727878:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:43] windowsService#isFocused 1
[13858:1201/201543.796631:INFO:CONSOLE(303)] "%c[IPC Library: File Watcher (chokidar)] %cStart watching: /home/yadav/dev/docs/guides]", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (303)
[13858:1201/201543.960279:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201543.960342:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:43] windowsService#getWindowCount
[13858:1201/201543.983666:INFO:CONSOLE(1480)] "%c INFO", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1480)
[13858:1201/201543.983718:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:43] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/insider/9878edb2a72ed4c4fd64811f9a58f06151810acf
[13858:1201/201544.004599:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.037551:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.038788:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.039740:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.047699:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.047764:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.048325:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.048693:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.048857:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.049102:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.049513:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.264730:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.266220:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.319339:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.376690:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.379321:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.379641:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.379732:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.381237:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.381275:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.381311:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.381334:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.393873:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.394136:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:15:44] windowsService#getWindowCount
[13858:1201/201544.594856:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.595398:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.640174:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.643163:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.652040:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.652784:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.652989:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.653665:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.654519:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.664523:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.664610:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.664641:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.664969:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.665024:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.665571:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.666365:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.666710:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.667216:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.667265:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.667673:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.667702:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.668592:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.727121:INFO:CONSOLE(1480)] "%cDEBUG", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1480)
[13858:1201/201544.731194:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.732914:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.740565:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.741054:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.741305:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.741358:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.741652:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.773087:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.774435:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.775262:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201544.856307:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[13858:1201/201552.826733:INFO:CONSOLE(1479)] "%cTRACE", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (1479)
[main 20:16:10] update#checkForUpdates, state =  idle
[main 20:16:10] update#setState checking for updates
[main 20:16:10] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/insider/9878edb2a72ed4c4fd64811f9a58f06151810acf
[main 20:16:10] update#setState idle
[main 20:16:10] telemetry/update:notAvailable { explicit: false }
```
[code-console.log](https://github.com/Microsoft/vscode/files/2636499/code-console.log)

**Comment by bpasero** [comment] 2018-12-02 06:49
+ @Tyriar

**Comment by rajinder-yadav** [comment] 2018-12-04 23:18
OK this time apt-get updated `code-insiders`. This is really inconsistent behavior. Sometimes I have to update with dkpg using manual download and other times not.

However code-insider still fails to reload, CTRL+SHIFT+P -> "Reload window" closes the running instance down only.

```
sudo apt-get update
sudo apt-get upgrade

Get:1 http://packages.microsoft.com/repos/vscode stable/main amd64 code-insiders amd64 1.30.0-1543916022 [45.0 MB]
...
Preparing to unpack .../2-code-insiders_1.30.0-1543916022_amd64.deb ...
...
Unpacking code-insiders (1.30.0-1543916022) over (1.30.0-1543558783) ...
...
Setting up code-insiders (1.30.0-1543916022) ...
```

**Comment by Tyriar** [comment] 2018-12-06 19:59
> On Linux after I do a general update using "apt-get", when the new version of code-insider is updated. I press CTRL+SHIFT+P and type "reload window".

You need to completely restart VS Code after you update, reload window won't work as the executable has been replaced. I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/5908

**Closed by Tyriar** 2018-12-06 19:59 UTC
Labels: insiders, needs more info

**Comment by rajinder-yadav** [comment] 2018-12-06 23:41
This use to work fine, for a long while this was my prcoess. Also apt-get stop working, after last update!

**Comment by rajinder-yadav** [comment] 2018-12-06 23:45
I will open a new bug for updating using `apt-get` which you closed without address, thanks :-D
