### ISSUE TITLE
Error running insiders tests on Travis Linux

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#45443] opened 2018-03-09 20:41 UTC
Since #45287 was fixed I updated the `vscode` package and pushed, but my tests are failing on Travis/Linux when they run against insiders. Mostly they just stall and there's no output for 10min so Travis terminates them, but one of the runs did give some output:

```text
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/Dart-Code/Dart-Code
Downloading VS Code into "/home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders" from: https://vscode-update.azurewebsites.net/1.22.0-insider/linux-x64/insider
Running extension tests: /home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/code-insiders /home/travis/build/Dart-Code/Dart-Code/test/test_projects/hello_world --extensionDevelopmentPath=/home/travis/build/Dart-Code/Dart-Code --extensionTestsPath=/home/travis/build/Dart-Code/Dart-Code/out/test/general
Xlib:  extension "RANDR" missing on display ":99.0".
Xlib:  extension "RANDR" missing on display ":99.0".
{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ 'vs/platform/log/node/spdlogService' ],
  detail: 
   Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (/home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/resources/app/out/vs/loader.js:15:513)
       at bindings (/home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/resources/app/node_modules.asar/bindings/bindings.js:81:44)
       at Object.<anonymous> (/home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/resources/app/node_modules.asar/spdlog/index.js:3:35) }
```

**Comment by DanTup** [comment] 2018-03-09 20:55
Btw - I set my tests up to run on Stable and Insiders now on Travis/AppVeyor. I don't know whether reporting when the fail is a) annoying because it's work-in-progress or b) useful because you might have unknowingly broken something. Please let me know if you have any preferences around this!

**Comment by joaomoreno** [comment] 2018-03-12 09:17
The problem is right there:

> `Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/build/Dart-Code/Dart-Code/.vscode-test/insiders/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)`

https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by DanTup** [comment] 2018-03-12 10:04
@joaomoreno Apologies, I got confused thinking Code would've fixed this at install time, but of course during test runs we're not installing it, we're just pulling a zip. Thanks for the link, [the fix](https://github.com/Dart-Code/Dart-Code/commit/67890c430f4c12718d7f7baa7570ab3386946009) worked great :-)

**Comment by DanTup** [comment] 2018-03-16 15:27
@joaomoreno Actually, this still isn't working..

I've added `libstdc++6` to my packages and it's installed at the top:

```text
The following additional packages will be installed:
  cpp-4.8 g++-4.8 gcc-4.8 gcc-4.8-base gir1.2-secret-1 libasan0 libatomic1
  libgcc-4.8-dev libgomp1 libitm1 libquadmath0 libsecret-1-0 libsecret-common
  libstdc++-4.8-dev libtsan0
Suggested packages:
  gcc-4.8-locales g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg
  gcc-4.8-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan0-dbg libtsan0-dbg libquadmath0-dbg libstdc++-4.8-doc
The following NEW packages will be installed:
  gir1.2-secret-1 libsecret-1-0 libsecret-1-dev libsecret-common
The following packages will be upgraded:
  cpp-4.8 g++-4.8 gcc-4.8 gcc-4.8-base libasan0 libatomic1 libgcc-4.8-dev
  libgomp1 libitm1 libquadmath0 libstdc++-4.8-dev libstdc++6 libtsan0
13 upgraded, 4 newly installed, 0 to remove and 141 not upgraded.
Need to get 31.1 MB of archives.
```

But I still get the original error. I've checked the travis file in the [example extension](https://github.com/codecov/example-typescript-vscode-extension/blob/master/.travis.yml) but it doesn't have any additional clues (I suspect maybe it would also fail against insiders).

I'm afraid I'm not familiar with Linux or these libraries, so I don't know how to fix (nor do I really understand the relationship between `libstdc++.so.6` and `GLIBCXX_3.4.21`.

**Comment by TheRealPiotrP** [comment] 2018-03-17 06:40
I am seeing the same symptoms in the C# Extension repo on vscode v1.1.8. Test execution stops at the same stage as described by @DanTup. I have not seen the error message reported above, however.

Is there  a flag I can set to obtain more verbose logs from the extension test host when this occurs?

**Comment by CarlosAzocar** [comment] 2018-03-19 11:48
@DanTup Apparently, GLIBCXX_3.4.21 is not available in gcc-4.8 - gcc-4.9. U need gcc > 5.

**Comment by DanTup** [comment] 2018-03-19 12:14
@CarlosAzocar I'm confused, the Travis file in the VS Code repo still references 4.9:

https://github.com/Microsoft/vscode/blob/master/.travis.yml

And it looks like its builds pass:

https://travis-ci.org/Microsoft/vscode/jobs/355311091

I'm wary of changing things to be different as if they break, I'll just be told I'm on the wrong version.

Anyway, I decided to try setting it to 5.0 and I got a weirder error:

```text
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release
Ign:2 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:5 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:6 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:7 http://dl.google.com/linux/chrome/deb stable Release
Ign:11 http://archive.ubuntu.com/ubuntu trusty InRelease
Hit:12 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Hit:13 https://dl.hhvm.com/ubuntu trusty InRelease
Hit:14 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Get:9 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:15 http://archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:17 http://archive.ubuntu.com/ubuntu trusty-backports InRelease
Ign:18 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Hit:19 http://archive.ubuntu.com/ubuntu trusty Release
Hit:20 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Hit:22 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
Hit:23 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:24 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Hit:25 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:26 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Hit:27 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:28 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Fetched 3,168 B in 2s (1,337 B/s)
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libsecret-1-dev libstdc++6 gcc-5.0" failed and exited with 100 during .
```

¯\_(ツ)_/¯

**Comment by DanTup** [comment] 2018-04-01 16:35
@joaomoreno This case is marked more-info-needed but I don't know what additional info I can provide. I've even tried copying all this out of your own tavis file:

```yaml
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsecret-1-dev
      - libstdc++6
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
```

However I still have the same issue. When this version of Code goes stable, I think lots of peoples CIs are going to break on Linux and I don't think it's clear how to fix it.

**Comment by DanTup** [comment] 2018-04-01 16:40
I found this which seems like the same issue, but it was fixed recently (yet my issue persists even today on Travis):

https://github.com/Microsoft/vscode/issues/46193

**Comment by joaomoreno** [comment] 2018-04-03 09:52
#46193 Seems related: we changed build machines recently.

Can you try using GCC 4.8 instead?

**Comment by DanTup** [comment] 2018-04-03 12:34
@joaomoreno First run seems to have worked; I'm just gonna force it a few more times since I can't remember if it was flaky or not (from the error I'd say no, but I have some recollection that it was flaky at some point).

**Comment by DanTup** [comment] 2018-04-03 12:42
Green again. I'm gonna merge this in and consider it working. I'll post back should I see it again.

I'll leave it to you if you want to close this case or investigate why it's broken on 4.9 (or not failing your own builds).

**Comment by joaomoreno** [comment] 2018-04-03 13:42
I'll close this then. 👍

**Closed by joaomoreno** 2018-04-03 13:42 UTC
Labels: needs more info
