### ISSUE TITLE
Provide clipboard access through the VSCode API

### ISSUE THREAD

**Issue by RoscoP** [Microsoft/vscode#10933] opened 2016-08-25 06:25 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 7

Feature Request:
It would be great to get access to the clipboard in the VSCode API.  My use case is very simple, I want to be able to put specific text into the clipboard when a button is pressed (relative path to a file).  I'm sure other extensions would benefit from clipboard access access as well.

**Comment by bpasero** [comment] 2016-08-25 12:16
@jrieken fyi

**Comment by jrieken** [comment] 2016-08-25 12:53
closing as duplicate of https://github.com/Microsoft/vscode/issues/217. Note that we don't have plan to expose the clipboard in the API but recommend the use of npm modules that do this, like: https://github.com/xavi-/node-copy-paste

**Closed by jrieken** 2016-08-25 12:53 UTC
Labels: api, feature-request
