### ISSUE TITLE
PHP code Syntax is not highlighted if is between a <style> tag

### ISSUE THREAD

**Issue by JavChz** [Microsoft/vscode#28833] opened 2017-06-15 18:41 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-stylus|sysoev|1.7.3|;

---

Steps to Reproduce:

1. PHP syntax won't work if is inside a <style> block  in a .php file (which affects lighly wordpress development)

![2017-06-15](https://user-images.githubusercontent.com/13250549/27196466-c72825ca-51c7-11e7-9dcc-e15575914cd9.png)

**Comment by ramya-rao-a** [comment] 2017-06-15 19:49
Duplicate of #28818

cc @roblourens

**Closed by ramya-rao-a** 2017-06-15 19:49 UTC
Labels: new release
