### ISSUE TITLE
Rename input widget should use text editor widget

### ISSUE THREAD

**Issue by leonardoanalista** [microsoft/vscode#32753] opened 2017-08-18 05:43 UTC
- VSCode Version: June 2017 (version 1.14)
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Given code;
```
import URLS from '..';

const contactUs = (
  <Link href={URLS.MY_WEBSITE}>
    contact us
  </Link>);
```
2. select variable name in import `URL`
3. press `F2` in order to rename variable
4. press shortcut to transform to lowercase (it must use shortcut to reproduce). In my case `OPT + CMD + L`
5. expected import line and code line to be transformed to lowercase.
6. result: only import is in lowercase

Reproduces without extensions: Yes

Thank you 
Leonardo Correa

**Comment by mjbvz** [comment] 2017-08-18 18:39
The bug is that `transform to lowercase` is being applied to the editor, not the rename input. I believe it is expected that `transform to lowercase` only works in the editor and not in input boxes, but we probably should not allow document edits while rename is active. 

One way to get this behavior today is to use a `when` clause on the keybinding so that the command is not active during rename:

```
	{
		"key": "alt+cmd+l",
		"command": "editor.action.transformToLowercase",
		"when": "editorFocus && !renameInputVisible"
	}
```

@jrieken Any thoughts on a proper solution here? This same issue applies to any command that transforms text

**Comment by leonardoanalista** [comment] 2017-08-19 10:29
Thanks for the reply. The whole point of this functionality is transformToLower[Upper]case when `editorFocus` and `renameInputVisible` - performing refactoring.

**Comment by leonardoanalista** [comment] 2017-08-19 10:35
Is there a callback or hook when the input text change? This way the editor could update or perform the refactoring as per usual.
Actually the shortcuts while rename input is visible is affecting the value on the editor immediately. We end up with inconsistent result different to the value on rename input. Really strange.

**Comment by jrieken** [comment] 2017-08-21 06:04
To make editor commands work, we need to use the editor (instead of text input) for the rename widegt.

**Comment by jrieken** [comment] 2019-12-11 08:10
/duplicate of https://github.com/microsoft/vscode/issues/53666

**Closed** 2019-12-11 08:10 UTC
Labels: *duplicate, feature-request, help wanted, rename
