### ISSUE TITLE
"Oriya" found in browsers.js

### ISSUE THREAD

**Issue by KevinMcMurry** [Microsoft/vscode#17631] opened 2016-12-20 23:23 UTC
Found in Tfs.Service\WebAccess\BuiltInExtensions\Content\CodeEditor\0.1.2\vs\languages\css\common\services\browsers.js

Guidance:
- if this is "our" term, please replace with "Odia"
- if references a browser support property or other external, please resolve by design
- if otherwise, please let me know, thanks

**Comment by egamma** [comment] 2016-12-21 15:47
This is a css-schema term. Resolving as by design.

**Closed by egamma** 2016-12-21 15:47 UTC
