### ISSUE TITLE
Allow to save files that need user elevation

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1614] opened 2015-12-23 12:54 UTC
I often need to edit config files (MySQL, PHP, Apache, ...) in directories like C:\Program Files that require administrative rights. When you open them with code and save the file it says "Permission denied". So I have to run Code with right click as administrator and then choose "open file" to open the file. Once, it is not possible to simply drag&drop the file into the elevated Code. The other problem is, once I already have code instance running without elevated rights (say I have my project open and now I need to edit a config) I cannot get another instance with elevated permissions. UAC asks for permissions and a new Code window opens, but it is not elevated, when I save it says permission denied. I have to close my project before I can get an elevated Code instance.

I don't know if that is a restriction of Windows but seeing that you can, for example, run a normal Powershell and an elevated Powershell side-by-side I think this should be possible. The optimal case of course would be if Code could elevate itself if it can't save a file because of insufficient permissions. But being able to run elevated and non-elevated side-by-side would already help a lot.

**Comment by felixfbecker** [comment] 2016-01-08 17:12
Notepad++ does this very well:
![image](https://cloud.githubusercontent.com/assets/10532611/12204266/5d16c136-b633-11e5-8e8d-554f3a9b14b9.png)

**Comment by sstjohn** [comment] 2016-01-25 22:33
I've got a debugger extension that needs to be run with privilege. On Linux, ```sudo code``` is sufficient to launch both vscode and the debugger as root; but due to this issue, my extension can't work on Windows.

**Comment by felixfbecker** [comment] 2016-01-25 23:12
@sstjohn You _can_ run Code as administrator on Windows, and that should inherit to all child processes. It is just not very good UX at the moment:
 - close _all_ open windows of Code
 - right click on Code and click "run as administrator" or type `code` in an elevated command line
 - open the desired file from inside Code with File > Open

**Comment by sstjohn** [comment] 2016-01-26 20:55
Oh I get it, I was trying to run multiple instances in the same login session with different privileges. Thanks for the pointer, I'd suggest this could use a little documentation at least.

**Comment by joggienl** [comment] 2016-02-12 23:11
This is somewhat related to this question http://stackoverflow.com/questions/31458077/mac-user-running-mamp-issues-trying-to-modify-files-inside-root-folder-eacce?noredirect=1#comment50887510_31458077

An item on uservoice also has been created: http://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8915236-visual-code-w-terminal-integrated-and-super-admin

Seems like there is a need for a os-independant solution to be able to edit files which need administrator password / elevated rights.

**Comment by regs01** [comment] 2016-04-01 20:49
@felixfbecker
just a prompt to elevate on save will save a lot of time.

**Comment by gerane** [comment] 2016-04-04 12:55
Even if I close all Code Instances, I cannot get an elevated Code on Windows. This makes Code unusable for my use cases. It doesn't matter if I use RunAs or execute code in an elevated cmd or powershell prompt, it is not elevated.

**Comment by felixfbecker** [comment] 2016-07-02 07:02
I think I found something that should help with this: https://www.npmjs.com/package/electron-sudo
It allows to run a process with privileged rights, cross-platform, by opening a platform-dependend prompt.
You could save all unsaved files in the temporary folder, then use electron-sudo to restart Code as admin, and re-open and save the unsaved files (I assume this is how Notepad++ does it).

**Comment by CasperTDK** [comment] 2016-08-15 18:56
+1

**Comment by artisticcheese** [comment] 2016-09-06 16:24
Please implement. That the only thing prevents me from deploying as default editor on servers instead of notepad++ which does it out of the box.

**Comment by third774** [comment] 2016-09-08 14:55
Would love to see VS Code handle this more gracefully!

**Comment by jontro** [comment] 2016-11-24 01:44
Sublime Text does this in a very nice way. It will only pop up an OS prompt asking to type in the password. The editor doesn't even restart (I guess it runs the save in a forked background process)

**Comment by emilast** [comment] 2016-12-05 16:07
I hit this problem every single day, it would be really nice if there was a way to fix this. My main problem is not being able to open new Code instances if already opened and running elevated. Opening a second instance non-elevated when choosing "Open with Code" in File Explorer would solve the main problem, but handling saves similarly to what Notepad++ is doing would be really neat as well.

**Comment by mgwhitfield** [comment] 2017-01-25 03:35
I go to the executable directory, goto compatability, switch *on* "run as administrator".  I am prompted to authorize elevated privileges when opening a directory in code (via context menu).  However, when running terminal inside elevated Code.exe process, the terminal *still* is not admin.

**Comment by Gringox** [comment] 2017-01-25 20:11
Any updates on this? It could be nice to have a prompt asking for the password like sublime or atom does

**Comment by mike-pt** [comment] 2017-03-16 17:55
+1

**Comment by zjalexander** [comment] 2017-04-10 17:51
This would also be useful for editing PowerShell scripts that use cmdlets which require escalation, such as ```Get-VMNetworkAdapter```

**Comment by digaomatias** [comment] 2017-04-17 20:40
Right now I'm installing notepad++ just because of this issue.

**Comment by iameli** [comment] 2017-04-28 04:01
I think Sublime's behavior is absolutely correct here, and also maybe should be its own ticket. "Better support running Code as administrator" is maybe also a valuable feature, but "automatically prompt for administrator permissions when attempting to save a privileged file" is I think what I'm asking for.

**Comment by bgelens** [comment] 2017-05-11 13:59
Although not being ment as such as a primary use case (I think), VS Code will be used in Windows/Linux System administration more and more as it starts to replace tools like ISE. 

In my case I'm editing scripts in one code instance which is not elevated and want to elevate another one to work with Desired state configuration which requires elevation... This is a hassle right now and off course it's not a good practice to just always start elevated as a workaround.

Another issue is, when I have an elevated instance running, context menu options like open with code don't work anymore as explorer is not elevated.

**Comment by Sujimoshi** [comment] 2017-05-17 10:34
+1

**Comment by Brendan-McCoy** [comment] 2017-05-18 14:26
Throwing out my usecase: I use separate login and admin credentials in my environment.

Because all of my privileges for shares, sharepoint, version control, etc are tied to my non-admin privileges, I usually run Code as that.  However, for powershell scripts especially, I often require an elevated powershell.

What I would like is the ability to create an elevated powershell from a non-elevated Code instance, being able to use my administrator credentials.  I would just launch Code from admin but then I lose access to my network resources, config, and plugins.

**Comment by corford** [comment] 2017-06-02 01:33
An issue I'm running in to is losing network shares when running vscode in elevated mode. I have a gitrepo on a linux guest VM exposed to a Windows 10 host via a samba share. I can't use vscode to work on this repo from within the Win10 host because the repo contains a few symlinks and currently* the only way to get Git for Windows to correctly support symlinks is to run it in elevated mode (or disable UAC completely).

* Fortunately a pull request got merged two days ago that enables support for Win10's improved symlinking capability so whenever the next Git for Windows release lands my issue will get resolved (Win7 users will still have the same problem though).

**Comment by corford** [comment] 2017-06-02 01:50
I'm running in to an issue with losing network shares when running vscode in elevated mode. I have a linux guest VM that exposes a repo via a samba share to a Windows 10 host. I can't easily use vscode to work in this repo on the Win 10 host because the repo contains a few symlinks and currently* the only way to get Git for Windows to work correctly with symlinks is to run it in elevated mode or disable UAC completely.

This workaround doesn't fix the problem: https://support.microsoft.com/en-gb/help/3035277/mapped-drives-are-not-available-from-an-elevated-prompt-when-uac-is-configured-to-prompt-for-credentials-in-windows

\* Fortunately, a pull request was merged two days ago that adds support for Win 10's new symlinking capabilities so whenever the next Git for Windows release lands my use case should work (since vscode will no longer need to run in elevated mode to get symlinks working without disabling UAC). Win7 users will still be stuck though.

**Comment by marvhen** [comment] 2017-07-11 20:04
+1

**Comment by Darnley** [comment] 2017-07-21 17:30
Please, build this function.
**+1!**

**Comment by sqbing** [comment] 2017-08-04 02:58
Really need this, will save a lot of time.

**Comment by TenaciousG** [comment] 2017-08-04 11:57
+1

**Comment by vskh** [comment] 2017-08-04 13:18
It would be also helpful if it was possible to run the instances of VSCode with and without elevated permissions simultaneously. I am not sure this limitation is caused by OS or the way VSCode is implemented.
I tend to use it as a regular user most of the time but sometimes there are tasks that require editor to have admin permissions. Currently, I have to close all existing windows of VSCode and open it as admin. After that, to switch to my regular work, I need to do the same - close all admin instances and start it as usual.

**Comment by cristianok** [comment] 2017-08-07 20:11
+1

**Comment by purportex** [comment] 2017-08-11 19:36
+1

**Comment by tenpaiyomi** [comment] 2017-08-14 07:47
+1

**Comment by rwspencer** [comment] 2017-08-22 16:30
+1

**Comment by Metis77** [comment] 2017-08-24 15:42
+1

**Comment by jontro** [comment] 2017-08-24 15:50
Can people please stop doing +1. It's causing a lot of noise to people subscribing to this issue and wont speed implementation up. Use the like button instead.

**Comment by artisticcheese** [comment] 2017-08-24 15:52
Where is `like` button exactly? I usually just subscribe to issue to identify another person waiting for a fix.

**Comment by regs01** [comment] 2017-08-24 16:52
I see no problem seeing those messages for important issues. If it's not important to you, you can always unsubscribe.

**Comment by jontro** [comment] 2017-08-24 17:12
@artisticcheese You can add a reaction ![image](https://user-images.githubusercontent.com/1257496/29678591-6bfc9d1a-88ff-11e7-8eaa-c65e2d7c6933.png)
@regs01 I am subscribing because as I am interested in updates to the issue and discussion about the implementation. A +1 clutters up the inbox and doesn't add value to the discussion. 

One of the big reasons for introducing Github Reactions was specifically to reduce noise as can be read here https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by infestus** [comment] 2017-10-10 10:38
+1

**Comment by andystod** [comment] 2017-10-17 10:00
+1

**Comment by kamil-kielczewski** [comment] 2017-10-18 14:18
still not implemented :( ... in Atom it works very well

**Comment by schwaerz** [comment] 2017-11-20 14:29
Btw.: Atom plugin can be found here: https://atom.io/packages/susave
Probably the implementation could be done similar?

**Comment by vnl** [comment] 2017-12-01 17:18
This is a good example: https://sourceforge.net/projects/nppsaveasadmin/ too 
Open as admin to save should be an alternative.

**Comment by kamil-kielczewski** [comment] 2017-12-01 20:55
I like vscode - however in atom you open "admin read-only" file as normal user eg. `/etc/hosts`, and when you try to save, atom ask you (using some system dialog) about admin password - you type it and file is just saved (look on image - polish lang). Why this simple behaviour is impossible in vscode ? 

![zrzut ekranu 2017-12-01 o 21 53 59](https://user-images.githubusercontent.com/15379981/33502914-337ed77e-d6e2-11e7-9c89-a4007eca7db5.png)

**Closed** 2017-12-12 15:03 UTC
Labels: feature-request, run-as-admin

**Comment by bpasero** [comment] 2017-12-12 15:06
Using [sudo-prompt](https://github.com/jorangreef/sudo-prompt) you can now retry to save as admin when saving fails. This will work on macOS, Linux and Windows:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/33891409-222c8fd0-df56-11e7-94db-173f30d8002d.gif)

There are some design decisions that I took that are worth mentioning where behaviour is maybe different from what others do:
* you will always first get the error message and from there you can save as admin
* each time you save you will have to authenticate again as admin
* you cannot create a file on disk as admin, the file has to exist on disk
* you cannot save readonly or hidden files

I think this is a good start, feedback welcome. This will be available in insiders as soon as we have released our 1.19 version this week.

**Comment by tenpaiyomi** [comment] 2017-12-12 15:12
@bpasero Any particular reason for those design decisions vs the standard behavior?  Namely, it automatically prompting if you don't have permission to save a file and allowing you to create/save readonly files, so long as you supply the permissions?  It seems like a step back in terms of UX to have those limitations.

**Comment by bpasero** [comment] 2017-12-12 15:30
@tenpaiyomi not sure what would define the "standard" behaviour really. E.g. I am not aware of UX guidelines for how to do this in a standard way.

I chose this way because I think executing an operation as root should be done with great care. I do not think an editor is the right tool for creating file/folder structures as admin user. 

As to getting repeated prompts and errors for each save, that is maybe something we could revisit later based on feedback. Here I am maybe overly cautious to prevent harm. However to justify my rationale: I find it a bit weird to just popup a login dialog out of nowhere. As a user you could have auto save enabled and that would mean typing and waiting for a short moment would suddenly bring up a (scary) modal dialog for logging in.

**Comment by tenpaiyomi** [comment] 2017-12-12 15:32
@bpasero When I say standard behavior, I more refer to how things generally tend to work.  For example, in Sublime Text, if I am editing a user that requires sudo to save, when I go to save it will automatically prompt me if my current permissions are not adequate.  It seems more intuitive to just prompt the user versus saying "Hey, you can't do that, you need to click this button to attempt to save again and then get prompted."

**Comment by kamil-kielczewski** [comment] 2017-12-12 15:40
@bpasero you write:

> I do not think an editor is the right tool for creating file/folder structures as admin user.

Could you explain why you thing in such way?

**Comment by bpasero** [comment] 2017-12-12 17:38
@tenpaiyomi yeah I get that, however there can be many reasons why I file cannot be written to. For example it could be readonly (which is unrelated to permissions), would you then expect that when you save as admin, the readonly flag should go away? And what if the file belongs to another user, would'nt it make more sense to ask to log in as that user instead of logging in as admin?

@kamil-kielczewski I think writing files as admin gets messy when it comes to permissions: Should the file/folder only be readable by the admin or any user? Should it be writeable by any user or only the admin? I think creating a file as admin at the minimum has to ask what permissions to use in that case where you are impersonating as admin. If you run the tool as admin, I think you are free to do whatever you want.

Btw when I checked ST, you are not able to create a file as admin by saving it to a location that needs admin privileges. So they seem to follow a similar model.

**Comment by kamil-kielczewski** [comment] 2017-12-12 17:48
@bpasero I think the editor should behave exactly as operating system (e.g. linux) - so when I create file (or similar folder) by editor I should get the same result as execute `sudo touch some_name`. My thinking is right?

**Comment by bpasero** [comment] 2017-12-14 15:21
I pushed some changes to allow to save a) readonly files and b) hidden files. For a) you will see an explicit action that explains what is going on:

![image](https://user-images.githubusercontent.com/900690/33999441-c883a82e-e0ea-11e7-867c-73758a7b52d8.png)

For b) we just truncate the file first before writing and then using `r+` mode to write. We already do this trick for regular saving when we see that saving fails on Windows. 

I still plan to look into making the experience on Windows a bit better. The prompt that shows up is a bit scary if you look at the details. Ideally we could elevate a child process of VS Code itself to admin rights so that the prompt shows the VSCode icon to the user.

**Comment by kamil-kielczewski** [comment] 2017-12-14 16:21
I really appreciate that you fix this issue. When new VSC update will be available I will test it and give feedback.

This fix will be helpful for many developers. 

Thank you :)

**Comment by bpasero** [comment] 2017-12-15 05:57
@kamil-kielczewski it should be available in todays insider release: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kamil-kielczewski** [comment] 2017-12-16 21:47
Ok @bpasero  I install and test you fixes:

Main functionality which I want: 
a) ability to save /etc/hosts by type admin password - works :)
b) save read-only files (by ask user do he really want it) - works :)
c) save hidden files - works :)  (hovewer i was able to edit hidden files only by drag and drop them from mac-finder to vscode)

Minor functionalities like:
a)  create file in protected (need admin privilidges) e.g. create file in /etc folder - doesn't work
b) see hidden folders and files - doesn't work (i think this option should be default set to fasle - but user should have ability to change it)

So to this point I am satisfied (however It will be good to have also minor functionalities; implement nice modal windows for user dialogs will be also nice feature)

Tank you :)

**Comment by bpasero** [comment] 2017-12-17 08:05
@kamil-kielczewski I suggest to open new issues for new feature requests. I am not sure I understand the issue with not seeing hidden folders and files.

**Comment by kamil-kielczewski** [comment] 2017-12-17 10:22
hm strange - may be it was my mistake - now I see hidden files. So everything ok :)  
Later I create new issues.
