### ISSUE TITLE
Proportional fonts are rendered as fixed width fonts in the terminal

### ISSUE THREAD

**Issue by mmzeeman** [microsoft/vscode#35681] opened 2017-10-06 06:26 UTC
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Select a proportional font. (I use https://blog.golang.org/go-fonts)
2. Open the terminal and do something. Text is rendered as if the font is a fixed width font.

<img width="1006" alt="screen shot 2017-10-06 at 08 23 37" src="https://user-images.githubusercontent.com/1024972/31265553-b1f7a800-aa6f-11e7-92a7-53227f4f1bb5.png">

Reproduces without extensions: Yes/No

**Comment by T8xi** [comment] 2017-10-06 09:39
I've the same results on Win 10 Pro x64 / VSCode 1.17.0 while using a custom "editor.fontFamily"-setting.
![grafik](https://user-images.githubusercontent.com/30469773/31271954-7e4c8c90-aa89-11e7-850e-5ac74f0edd63.png)

By using the standard font family the problem is gone
![grafik](https://user-images.githubusercontent.com/30469773/31272176-5519f1fe-aa8a-11e7-88ae-706b9ddc2bc9.png)
![grafik](https://user-images.githubusercontent.com/30469773/31272291-bf4f6428-aa8a-11e7-8110-f052fc137ef4.png)

**Comment by nickmccurdy** [comment] 2017-10-17 12:51
Proportional fonts are just as valid as monospace fonts for coding. It would be nice to have better rendering in the terminal since the extra spacing makes proportional fonts difficult to read (they seem to have even wider spacing than monospace fonts). For now I'm setting `terminal.integrated.fontFamily` to a monospace font similarly to @mmzeeman's tip.

**Comment by Gaolz** [comment] 2017-12-05 05:41
Update settings to "terminal.integrated.fontFamily": "Monaco", it works for me.

**Comment by Hideer** [comment] 2018-02-07 07:56
Resetting the font does not solve the problem.

**Comment by mmzeeman** [comment] 2018-02-07 13:05
You are right. It is a workaround, you have to use a monospaced font in the terminal.

**Comment by Tyriar** [comment] 2018-03-08 05:34
@Hideer you need to use a monospace font, variable width fonts are not supported within the terminal.

**Comment by matt3224** [comment] 2018-05-04 11:11
Hey, I'm in need of this `"terminal.integrated.letterSpacing": 0.25,` when will something like this be added, or is there a way I can achieve this currently?

**Comment by Tyriar** [comment] 2018-05-04 16:28
@matt3224 decimal letter spacing would only be added after proportional font support is added. Font rendering is currently done on a canvas and every character is drawn on a grid and their texture cached to boost performance, because of this their x,y coordinates need to be integers (otherwise they would be blurry).

**Comment by matt3224** [comment] 2018-05-04 16:30
@Tyriar how far along is the proportional font support?

**Comment by Tyriar** [comment] 2018-05-05 17:42
@matt3224 it's not planned

**Comment by rfgamaral** [comment] 2018-05-09 12:13
@Tyriar But you closed #35695 in favor of this one and now it's not planned? As far as I can see on xtermjs/xterm.js#1044, letter spacing is supported by xterm, right? So could we at least get that on VS Code?

I mean, I just wanted to have 1px more between each character because right now they just feel weird. And that 1px between each character would render the terminal much more closely to how Windows Command Prompt renders. It's just 1px, it's an integer and their texture could still be cached without a performance hit, right?

**Comment by Tyriar** [comment] 2018-05-09 17:07
@rfgamaral it was actually an oversight that I didn't bring in `letterSpacing` as a setting in vscode, this comment is wrong https://github.com/Microsoft/vscode/issues/35695#issuecomment-336171007, I must have missed it.

I'll add this in the May release as that's trivial. Tracking in https://github.com/Microsoft/vscode/issues/49566 to make sure it gets done/verified. Sorry about the hassle and thanks for calling this out.

**Comment by rfgamaral** [comment] 2018-05-09 17:13
@Tyriar No problem, thank you :)

**Comment by dulara1994** [comment] 2018-10-05 15:00
I had the same issue. because I imported settings from someone else. (I'm using linux, imported settings from a mac) 
Go to  Settings >  filter settings to show modified settings >> there i deleted everything in front of the font field. restart the IDE. 
if you import settings using a service such as Settings Sync. It may be because you are trying to use a font that is not currently installed on your computer. 
also a reminder usually terminals, code editors are only support mono-space fonts. 


![screenshot from 2018-10-05 20-28-00](https://user-images.githubusercontent.com/26034746/46542977-66091900-c8dd-11e8-917e-c48c5e7a9e25.png)

**Comment by Tyriar** [comment] 2018-10-05 17:36
@dulara1994 remember you can also use font fallbacks, so you can have `fonta, fontb, monospace` as your font config if the fonts aren't on all your OS's.

**Comment by Tyriar** [comment] 2019-10-08 15:23
Closing as font fix, you should be using a monospace font in a terminal. If you're experiencing this issue you can fix it by configuring the `terminal.integrated.fontFamily` setting to use a monospace font.

**Closed by Tyriar** 2019-10-08 15:23 UTC
Labels: feature-request, integrated-terminal
