### ISSUE TITLE
Unable to use ASUS smart gesture to scroll in VS Code.

### ISSUE THREAD

**Issue by Levikov** [Microsoft/vscode#17583] opened 2016-12-20 04:45 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. Asus N550JV + Windows 10 Pro build 14393.576 + VS Code 1.80 + 150% Screen Zoom
2.Move two fingers on the touchpad in code editing window. NO response.

**Comment by alexanderby** [comment] 2017-01-13 18:21
@Levikov How did you made it work at all? I have an Asus N550JV, Win 10 (and I'm using VSCode too :) ). When I install Asus Smart Gesture 4.0.12 or 2.2.5, touch pad is unusable, like the left button is always pressed while I'm moving a cursor. If I uninstall Smart Gesture, touchpad works as it should besides right-click is unstable and I cannot scroll anywhere. Did you have problems like that? I've already repaired my keyboard (the cable is overpressed by battery) like shown on this video https://www.youtube.com/watch?v=_2O5SmtefgA

**Comment by alexanderby** [comment] 2017-01-16 18:14
@Levikov Today it suddenly started to work (and in VSCode too). It didn't work since I bought this laptop, maybe some latest update fixed the issue.

**Comment by alexandrudima** [comment] 2017-01-21 13:46
We listen to `mousewheel` events coming in from Chromium. It is Chromium's job to emit `mousewheel` events when using two fingers on the trackpad. Closing here because there is no possible code change we can do in our code to make this work. If you experience issues, please look into reporting them to Chromium.

### To find out what Chromium version VS Code uses:

* Go to `Help` > `About` and look for the Renderer version

![image](https://cloud.githubusercontent.com/assets/5047891/22174828/fd47b564-dfe7-11e6-9a55-a119b4b08c3b.png)

* You can then proceed to install Chromium at the same version and try if your problem reproduces in that version.

### Known workarounds

For example, my trackpad (on a Surface Book) works correctly after "restoring" and then maximizing back the VS Code window (Possibly related #13612).

**Closed by alexandrudima** 2017-01-21 13:46 UTC
