### ISSUE TITLE
Feature Request: Modify extension settings from the extension's contributions page

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#45597] opened 2018-03-12 15:38 UTC
It would be nice if there was a facility to modify extension settings from the contributions page. As a minimum it would be nice to be able to click on an entry which would open the settings page and position the cursor at the selected setting.

Even nicer would be opening of the settings page with a filter that just showed the settings applicable to the extension.

Nicest of all would be the ability to modify the settings in place (on the contributions page). 

Although the vscode settings page does what it needs to do, it feels to me like one of the areas where Atom presents it in a much more friendly way.

**Comment by sandy081** [comment] 2018-09-24 16:51
Duplicate of #25012

**Closed** 2018-09-24 16:52 UTC
Labels: *duplicate, extensions, feature-request
