### ISSUE TITLE
Quick fix: select first entry by default

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21504] opened 2017-02-27 15:21 UTC
I think it would make some scenarios easier to type if the first suggestion of a quick fix was selected by default in the context menu. That way for many fixes all you need to type is `Cmd+.` and `Enter`.

**Comment by bpasero** [comment] 2017-02-27 15:52
Looks like the place where we open the quick fix menu is in https://github.com/Microsoft/vscode/blob/ben/next/src/vs/editor/contrib/quickFix/browser/quickFixWidget.ts#L49

If there are no objections I could provide a PR (looks like we also need API to allow to set the index of the menu entry that should be selected by default).

**Comment by jrieken** [comment] 2017-02-27 15:55
> If there are no objections I could provide a PR (looks like we also need API to allow to set the index of the menu entry that should be selected by default).

That won't work because code actions come from multiple provider which don't anything from each other. 

>  by default in the context menu.

Actually I don't know if the native context menu allows for a preselection

**Comment by jrieken** [comment] 2017-02-27 15:56
and actually a dupe of #13631

**Closed by jrieken** 2017-02-27 15:56 UTC
Labels: code-actions

**Comment by bpasero** [comment] 2017-02-27 16:06
@jrieken added my comment to https://github.com/Microsoft/vscode/issues/13631#issuecomment-282764036
