### ISSUE TITLE
.tsx highlighting issue with regex

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#91998] opened 2020-03-04 08:13 UTC
Issue Type: <b>Bug</b>

In the following line, the leading "!" confuses the highlighter: 

```
if (!/\.aspx(\?|$|#)/i.test(templateUrl)) {  // broken highlight
}
```

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment] 2020-03-04 10:46
/duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed** 2020-03-04 10:46 UTC
Labels: *duplicate
