### ISSUE TITLE
"super" keyword of JS is appeared as strikethrough.

### ISSUE THREAD

**Issue by alihasen** [microsoft/vscode#106653] opened 2020-09-14 12:20 UTC
The "super" keyword of JS is appearing as strikethrough when using in **React class**. Please find the attached screenshot.
file extension: js

- VSCode Version: 1.49.0
- OS Version: MacOS 10.15.5

![Screenshot 2020-09-14 at 5 32 31 PM](https://user-images.githubusercontent.com/31187812/93084847-4de9c900-f6b2-11ea-96b9-bca7e56c0e72.png)

Does this issue occur when all extensions are disabled?: I have no extensions installed.

**Comment by mjbvz** [comment] 2020-09-14 18:25
Duplicate of https://github.com/microsoft/TypeScript/issues/40511

**Closed by mjbvz** 2020-09-14 18:25 UTC
Labels: new release
