### ISSUE TITLE
ES6 support does not work

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#95] opened 2015-11-18 20:06 UTC
When I open any file in my ES6 Javascript project, every single line is underlined in red, with errors like:

![screen shot 2015-11-18 at 12 03 09 pm](https://cloud.githubusercontent.com/assets/79215/11252725/88d3c130-8dec-11e5-9b18-3f5bc4337bfe.png)
 
In my project's root, I have a `jsconfig.json` file with the following contents:

    {
		"compilerOptions": {
			"target": "ES6",
			"module": "commonjs"
		},
		"files": [
			"app/"
		]
	}

The file in question lives inside the `app` folder.

**Comment by DelvarWorld** [comment] 2015-11-18 20:10
Furthermore, could you please edit this blog post to make the images of text into actual text? http://blogs.msdn.com/b/vscode/archive/2015/07/06/vs-code-es6.aspx Classic Microsoft :)

**Comment by glen-84** [comment] 2015-11-18 22:04
Duplicate of #54?

**Comment by rob3c** [comment] 2015-11-19 00:51
filesGlob can be used outside of Atom by using a file watcher with the [tsconfig-glob](https://www.npmjs.com/package/tsconfig-glob) package on npm.

**Comment by jacogr** [comment] 2015-11-21 05:57
+1 There really is a very weird bug here. When placing the file in the root folder, on some projects, it works, on others it doesn't. Moving the file to the src folder does the trick. I have no resorted to stripping down the jsconfig.json completely... and no go.

```
{
  "compilerOptions": {
    "target": "ES6"
  }
}
```

To say the least, this is quite irritating and actually standing in the way on my team using this.

No, we are no going to place a jsconfig.json file in each root source folder, e.g. src/, specs, etc.

**Comment by joaomoreno** [comment] 2015-11-21 13:57
Related to #337

**Comment by wcastand** [comment] 2015-11-21 19:29
I think i found a way arround by putting a exclude instead of files:
```
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs"
	},
	"exclude": [
		"node_modules"
	]
}
```

**Comment by jacogr** [comment] 2015-11-22 06:19
Only using excludes here, some projects it works, others it doesn't.

Am not using "files" in any of the jsconfig.json project files.

**Comment by jrieken** [comment] 2015-12-04 11:03
duplicate of #703

**Closed by jrieken** 2015-12-04 11:03 UTC
Labels: js

**Comment by DelvarWorld** [comment] 2015-12-04 19:57
@jrieken my ticket is a dupe of a ticket made 8 days after mine?

**Comment by Arebee88** [comment] 2015-12-04 23:54
Having a garbage experience with typescript and vscode, just give up man. This thread has made up my mind.

**Comment by DelvarWorld** [comment] 2015-12-05 00:06
> Having a garbage experience with typescript and vscode, just give up man. This thread has made up my mind.
> @Arebee88 

:+1: it was crippled from launch, and instead of providing any kind of community support or hiring a community advocate, the devs just keep saying "VS code fully supports ES6."

A Microsoft product that has trouble with the filesystem?! Who would have guessed!

**Comment by egamma** [comment] 2015-12-07 10:06
@DelvarWorld , sorry, that you had an unhappy experience. We are about to close Issue #703. It wasn't a single issue but there were several issues behind the same symptom (and no, it wasn't a file system issue). The fix will be in the December update (pls see #917). 

>Not documented in any way!

We are always interested in improving our documentation. Please let us know what you would like to see in the JS documentation: https://code.visualstudio.com/Docs/languages/javascript. 

>Furthermore, could you please edit this blog post to make the images of text into actual text? >http://blogs.msdn.com/b/vscode/archive/2015/07/06/vs-code-es6.aspx Classic Microsoft :)

I was about to do it, but then there is a link to a repository with full source code at the end,

**Comment by DelvarWorld** [comment] 2015-12-07 19:33
> I was about to do it, but then there is a link to a repository with full source code at the end,

Do you think that when coming across a blog and seeing the block of text one needs embedded in an image, the first thing a developer is going to do is scroll to the end of the blog post looking for an unlabeled, obfuscated link to an unrelated part of a codebase? If you have the ability to do, please edit the blog post (and the documentation) to show text instead of an image. I don't see the point of intentionally making every developer have to scour for an external link they don't know exists, to a repository not obviously related to jsconfig.json, following it, losing context of the blog post, assuming they know exactly where to look for the file in the directory structure, then clicking on it.

Pushback against saving every single developer who comes to the blog and documentation because "there is a link" is disheartening. Please think of how newcomers approach your docs and tools.

**Comment by DelvarWorld** [comment] 2015-12-07 19:36
> Please let us know what you would like to see in the JS documentation 

Not sure if you're just messing with me now, since you quoted me asking where `filesGlob` is documented, and linked to a page that doesn't mention `filesGlob`, then asked me what should be added to the docs.

**Comment by egamma** [comment] 2015-12-07 22:34
>Not sure if you're just messing with me now, since you quoted me asking where  filesGlob  is documented

No messing around, but I was wondering whether 1) you have found the page I mentioned and 2) whether you have read the page. I'm interested since in the doc it is mentioned that:

>You can create a JavaScript project by dropping in a jsconfig.json file. It's a subset of tsconfig.json. 

The tsconfig.json does not support `filesGlob`, so neither does the jsconfig.json. `filesGlob` is an [Atom-typescript specific extension ](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md), Apologies, that you got pointed into this direction and we didn't correct this immediately.

**Comment by rui-infotrack** [comment] 2016-04-09 14:04
Well... apparently I'm not the only one who encountered this issue:
![capture](https://cloud.githubusercontent.com/assets/12144265/14403943/653ac048-fead-11e5-8cf7-1de7dddcaed4.PNG)
I think I do want to like VS Code but seriously guys... since you announced it, I've been paying attention to it and trying to use it. I do want to love it as it has much faster loading speed than Atom, considering they are both based on Electron.

However, sadly, you guys just keep disappointing. I just installed the latest insider version and the screenshot is what I got. So what's the problem? They're valid JS syntax... rest parameters? arrow functions? This is year 2016 and VS Code still says they're invalid...?!

It's a bit funny that MS always sucks at these front-end development things, always left behind by open source community... Now you guys open sourced but you can't even do this thing right... Such a disappointment... I mean why would I use VS Code instead of Sublime which never gives me these sort of problems... If you want your VS Code to shine, then make it functional first please.

Don't bother giving me jsconfig.json suggestion. I tried, it doesn't work AT ALL. And don't ask me to use TypeScript.

**Comment by egamma** [comment] 2016-04-11 12:37
>They're valid JS syntax... rest parameters?

@rui-infotrack your snippet is using Rest Spread Properties, which are not part of ES6 and therefore this construct is not yet supported. Please refer to Microsoft/TypeScript#2103 for background and check this comment https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-182195915.

To get the sublime behaviour you can disable diagnostics using the `javascript.validate.enable: false` setting. This setting is available in the [insiders channel](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) ([release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md)).

The recommendation is to use eslint together with the vscode-eslint extension to get validation, pls see this [documentation](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md#javascript-linters-eslint-jshint).

**Comment by ktei** [comment] 2016-04-17 04:15
@egamma, thank you for the help. I will give it a try. And sorry for my bad attitude

**Comment by rui-infotrack** [comment] 2016-04-17 05:18
@egamma Just want to say thank you. I tried and it worked well. With ESLint plugin, it works smoothly! I will try VS Code for some time and see how it goes.

**Comment by egamma** [comment] 2016-04-17 17:25
@rui-infotrack your welcome. I hope you now become a happy Code user 😄

**Comment by joma74** [comment] 2017-07-17 10:54
Observing/sharing following things on VS code 1.14.1 Linux(as well as before).

1) Code completion of tsc target values in jsconfig.json seem not in line with the typescript doc https://www.typescriptlang.org/docs/handbook/compiler-options.html and aformentioned vs code docus. 

To the effect that inline d.ts library definitions are not found/proposed, if i manually specify a tsc target value of "es6".
If i specify a tsc target value of "ES6" as per the typescript doc, d.ts library definitions are found and proposed. But jsconfig.json get's twiggled.

 2) Code completion of tsc lib values in jsconfig.json seem not in line with the typescript doc https://www.typescriptlang.org/docs/handbook/compiler-options.html. 

To the effect that inline tsc lib values in jsconfig.json are twiggled if not lowercased.

3) Hovering description tsc target values in jsconfig.json does not contain the value "es6".

4) Changes in jsconfig.json HAVE TO be followed by a restart of VS code. To take proper effect.

5) With tsc target ES6, intellisense twiggles Promise<void> to be '[js] Type 'Promise<void>' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.'

```js
   ...
   * @return {Promise<void>} as defined async
   */
  static async describeTestBy(description, story, severity, webdriverConfig) {
  ...
```
