### ISSUE TITLE
Markdown documents preview is broken

### ISSUE THREAD

**Issue by StanKirilov** [microsoft/vscode#123218] opened 2021-05-07 00:31 UTC
Issue Type: <b>Bug</b>

Repro:
1. Start latest version of Visual Studio Code
2. Open Markdown file
3. Click (or open task) to either Preview as side or full view

Expected:
New or split window is opened with the rendered preview of the Markdown document

Observed:
Bland new or split window is opened and nothing is render. The VS code shows the following message:

Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('vscode-webview://8f7e3023-2ed4-4a8e-9947-fec591011dad/') with script ('vscode-webview://8f7e3023-2ed4-4a8e-9947-fec591011dad/service-worker.js?platform=electron&id=8f7e3023-2ed4-4a8e-9947-fec591011dad&vscode-resource-origin=https%3A%2F%2F8f7e3023-2ed4-4a8e-9947-fec591011dad.vscode-webview-test.com'): ServiceWorker cannot be started.

Restarting the VS code or rebooting the PC doesn't help - the issue repro 100%

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (40 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|240.00GB (229.91GB free)|
|Process Argv|--crash-reporter-id 0a512a6f-e668-4785-ae2e-2bb3b02f451f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
markdown-mermaid|bie|1.9.2
LinkCheckMD|bla|0.3.1
doxdocgen|csc|1.2.2
vscode-markdownlint|Dav|0.40.4
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.4
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.89
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.7
docs-yaml|doc|0.2.6
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-codeql|Git|1.4.8
vscode-pull-request-github|Git|0.26.0
vscode-test-explorer|hbe|2.19.6
plantuml|jeb|2.14.5
better-cpp-syntax|jef|1.15.5
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
rust-analyzer|mat|0.2.583
vscode-azurevirtualmachines|ms-|0.3.0
vscode-logicapps|ms-|1.0.11
extension-manifest-editor|ms-|0.1.5
csharp|ms-|1.23.11
mssql|ms-|1.10.1
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
mono-debug|ms-|0.16.2
powershell|ms-|2021.2.2
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
vscode-yaml|red|0.18.0
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.13
vscode-arduino|vsc|0.4.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833cf:30267465
vshan820:30294714
vscus158:30286553

```

</details>

**Comment by mjbvz** [comment] 2021-05-07 00:33
Duplicate of #122951

**Closed by mjbvz** 2021-05-07 00:33 UTC
