### ISSUE TITLE
Folder Isolation Mode

### ISSUE THREAD

**Issue by wavecoders** [microsoft/vscode#97615] opened 2020-05-12 13:53 UTC
In Angular things can get crazy with all folders and files.
Would be nice if we could select multiple folders and select an isolation mode where we only see thoses folders and files in the files view.
Then select a button to return to the all files/folders view
This will make it easy to find and work on related files in a project

**Comment by isidorn** [comment] 2020-05-12 15:41
Duplicate of working sets feature. Please seach for it through the open issues

**Closed** 2020-05-12 15:42 UTC
Labels: *duplicate, file-explorer
