### ISSUE TITLE
vscode.debug.breakpoints is always empty on the first call

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#169699] opened 2022-12-21 00:57 UTC
- Set some breakpoints
- Access `vscode.debug.breakpoints` from an extension- it's an empty array
- Try again - it's full

Seems that we don't sync breakpoint into to the EH until the first call to one of the breakpoint properties

https://github.com/microsoft/vscode/blob/de7ce5adf31b43f210b5b94b287dbfe6416f449d/src/vs/workbench/api/common/extHostDebugService.ts#L197-L199

@isidorn do you have some context on this? It's a little confusing because I wouldn't expect sending breakpoint infos to be expensive, and I would expect to be able to access the breakpoints array immediately.

**Comment by isidorn** [comment] 2022-12-21 14:15
@roblourens I do not have more context. I believe @weinand is the author of this code.
I like your suggestion that we change this and actively sync the breakpoints into the EH (since it should not be expensive).

**Comment by weinand** [comment] 2022-12-21 14:56
The observed behavior is by design: we want to avoid that all breakpoints get transferred to **all** active extensions all the time.

**Comment by roblourens** [comment] 2022-12-29 18:47
Thanks @weinand, is the worry that it's too much data/too expensive? What's the solution for extensions that need to access the list of breakpoints?

**Comment by weinand** [comment] 2023-01-02 22:29
@roblourens yes, potentially too much data and traffic for **all** extensions.

>What's the solution for extensions that need to access the list of breakpoints?
adding a `debug.breakpoints;` to the `activate()` function of an extension will register the extension to receive live updates for `debug.breakpoints`.

**Comment by roblourens** [comment] 2023-01-03 04:50
Thanks, I don't really understand that though, it doesn't seem like that much traffic/data, compared to something like the full text of open documents. If it's going to work this way, I should document it in vscode.d.ts. But I might try doing some testing to remove this restriction because I think it's unexpected.

**Closed** 2023-06-30 22:05 UTC
Labels: debug, debt, under-discussion

**Comment by roblourens** [comment] 2023-06-30 22:06
Verification steps:

- Create an extension that can log the value of `vscode.debug.breakpoints.length`
- Set a breakpoint in any file
- Then trigger your extension to check the length of the breakpoints array
- ✅ It should log the correct value on the first try- previously it would have been 0 on the first access, then the correct value afterwards
