### ISSUE TITLE
No duplicated results in Find in Files

### ISSUE THREAD

**Issue by lijhj** [microsoft/vscode#132132] opened 2021-09-02 14:48 UTC
If there are more than one match in a line when find in files, can you just show one result for that line. Don't show multiple results for one line, but highlight them multiple times on one result . The duplicated items are annoyed when you work with lots of results.

![Screen Shot 2021-09-02 at 10 36 05 PM](https://user-images.githubusercontent.com/9011764/131863880-7f91ace9-d27a-4e63-851b-921bd397384a.png)

**Comment by IllusionMH** [comment] 2021-09-02 15:45
Duplicate of #31817 and more details about reasoning https://github.com/microsoft/vscode/issues/85333#issuecomment-557934563

**Comment by roblourens** [comment] 2021-09-02 16:20
Thanks @IllusionMH

**Closed by roblourens** 2021-09-02 16:20 UTC
