### ISSUE TITLE
Feature Request: Advance Snippet to add 'import' statement at start of the file

### ISSUE THREAD

**Issue by kalpesh3000** [microsoft/vscode#160961] opened 2022-09-15 06:04 UTC
The code snippets are the most helpful and productive tool to quickly add the code. To improve the feature it provides, there can be one more property added `bodyAtTop`. 

**Use Case**
Suppose you have a simple snippet to compose a component in the front end.
```
"Link": {
	"prefix": "link",
	"body": [
		"<Link to={$1}>",
		"  $0",
		"</Link>"
	],
	"description": "Link"
}
```
It will insert the `<Link>` component but not the import statement of a component, i.e., `import {Link} from 'react-router-dom'`. It can be very helpful if a snippet can do that. So updated snippet can be like below.

```
"Link": {
	"prefix": "link",
	"body": [
		"<Link$1 to={Routes$2.$3.path}>",
		"  $0",
		"</Link$1>"
	],
	"bodyAtTop": [
		"import {Link} from 'react-router-dom'"
	],
	"description": "Link"
}
```
Whatever is there in `bodyAtTop` will be inserted in the first line of the file.

**Comment by jrieken** [comment] 2022-09-15 07:09
This is a great idea but snippets are static and cannot run code to know what "atTop" means? Above the copyright header? Below the last import statement? I don't believe this can be done without running code and makes this issue a duplicate of https://github.com/microsoft/vscode/issues/10561

**Comment by jrieken** [comment] 2022-09-15 07:09
Alternatively, you can have an extension that does a snippet-style completion which does all the things "correctly"

**Closed by jrieken** 2022-09-15 07:09 UTC
Labels: snippets, under-discussion
