### ISSUE TITLE
Can't open txt which file size is 90M   

### ISSUE THREAD

**Issue by lizhaode** [Microsoft/vscode#5436] opened 2016-04-18 07:55 UTC
- VSCode Version:1.0
- OS Version:Windows 8.1

Steps to Reproduce:
1. Open a txt file which file size is 90MB
2. Can not open it

**Comment by alexandrudima** [comment] 2016-04-28 11:01
@lizhaode We enforce this limit as it could lead to an OOM crash.

I think we could raise the limit once we optimize the way in which we read a file.

Currently, we read it in chunks and concatenate them in one huge string, only to split the string up by newline characters again very soon thereafter. This causes unnecessary memory pressure on v8.

**Comment by lizhaode** [comment] 2016-04-29 04:48
@alexandrudima 
It is a great shame
I have to use sublime text,right now.I need to open a huge log file to search something.

**Comment by mjbvz** [comment] 2016-11-11 23:39
Closing as duplicate of #9832. See that issue for a more in-depth explanation of the problem and some possible improvements we are considering. Thanks.

**Closed by mjbvz** 2016-11-11 23:39 UTC
Labels: debt, duplicate
