### ISSUE TITLE
Integrated Terminal Rendering Issue with Starship Prompt in VSCode

### ISSUE THREAD

**Issue by TheRealSwayamShree** [microsoft/vscode#236133] opened 2024-12-14 17:51 UTC
Type: <b>Bug</b>

I'm encountering an issue with the integrated terminal in VSCode when using the Starship prompt. The `$username` and `$directory` portion of the prompt appears with extra blank spaces, which do not appear in Windows Terminal with the same configuration.

Steps to Reproduce:
1. Configure Starship with the following settings (see attached configuration file).
2. Set the terminal font to "CaskaydiaCove Nerd Font" in VSCode.
3. Open the VSCode terminal.

Expected Behavior:
- The prompt should render without additional spaces, consistent with its appearance in Windows Terminal.

Actual Behavior:
- Blank spaces appear around the `$user`  and `$directory` section of the prompt in the integrated terminal.

Environment:
- VSCode Version: 1.96
- OS: Microsoft Windows 11 Home Version: 10.0.22631 Build 22631
- Font: CaskaydiaCove Nerd Font
- Terminal: Integrated Terminal using PowerShell

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.04GB free)|
|Process Argv|--crash-reporter-id 6e0e71da-9aa2-45b9-8422-e962e7ff6a9d|
|Screen Reader|no|
|VM|0%|
</details>

## starship config:

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
[](bg:yellow fg:red)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:cyan)\
$c\
$nodejs\
$python\
[](fg:cyan bg:bright_black)\
$time\
[ ](fg:bright_black)\
$line_break$character"""

palette = 'caramel_light'

[palettes.caramel_light]
black='#3B302C'
red='#C85A54'
green='#7C9A62'
yellow='#D6AA5A'
blue='#89A5C7'
magenta='#B58696'
cyan='#6CA9A6'
white='#F5F0E6'
bright_black='#6D5E55'
bright_red='#D3756D'
bright_green='#98B27D'
bright_yellow='#E2BC76'
bright_blue='#A3BDD3'
bright_magenta='#C79DA6'
bright_cyan='#8ABBB8'
bright_white='#FFFFFF'

[os]
disabled = false
style = "bg:red fg:white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:white"
style_root = "bg:red fg:white"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"project" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:white bg:green)]($style)'

[git_status]
style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:white bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:red bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:red bg:red)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[time]
disabled = false
time_format = "%I:%M %P|%a %b %d %Y"
style = "bg:bright_black"
format = '[[  $time ](fg:white bg:bright_black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:blue)'
vimcmd_replace_symbol = '[](bold fg:blue)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

**Comment by meganrogge** [comment] 2024-12-16 16:28
does disabling `terminal.integrated.shellIntegration.enabled` fix it?

**Comment by Tyriar** [comment] 2024-12-19 13:30
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-19 13:30 UTC
Labels: info-needed
