### ISSUE TITLE
Google Japanese Input IME Suggestion window is not updated when editor.experimentalEditContextEnabled is enabled.

### ISSUE THREAD

**Issue by dhimetoro** [microsoft/vscode#228058] opened 2024-09-10 03:28 UTC
Type: <b>Bug</b>

When editor.experimentalEditContextEnabled is enabled, the Google Japanese Input IME suggestion window does not update while you are typing.

There is no problem when editor.experimentalEditContextEnabled is disabled.
Similarly, there is no problem with Microsoft IME, regardless of the setting of editor.experimentalEditContextEnabled.

Reproduction steps:
- Enable editor.experimentalEditContextEnabled and restart Visual Studio Code.
- Enable Google Japanese Input IME and type some characters.
- The contents of the suggestion window should update as you type, but they do not.

https://github.com/user-attachments/assets/69dd04dd-0999-414e-aef0-e6365d101eac

https://github.com/user-attachments/assets/1d320491-33b2-4210-8305-816bf736c236

VS Code version: Code - Insiders 1.94.0-insider (dc9412125d4e0a480593962ae2687e74e64af728, 2024-09-09T17:10:54.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (55.98GB free)|
|Process Argv|--crash-reporter-id 10b11618-d4e6-4d55-aedc-6f34beb13e63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.93.2024090409
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
cmake-tools|ms-|1.19.51
cpptools|ms-|1.22.2
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31111988
jh802675:31132134
e80f6927:31120813
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by aiday-mar** [comment] 2024-09-11 13:06
Hi thanks a lot for posting this issue. I was indeed able to reproduce this issue. After some investigation I was able to confirm that this bug does not exist when VS Code is on the electron version 32.0.1 (currently it is on 30.0.4). This bug seems to be caused by chromium and after we upgrade to a higher electron version, this should be fixed. cc @deepak1556

**Comment by aiday-mar** [comment] 2024-09-11 13:08
Here is a screen recording showing it working with electron 32.0.1 on VS Code.

https://github.com/user-attachments/assets/9cf43149-61a7-45ab-bc4f-7ed3ec1b4d9e

**Comment by aiday-mar** [comment] 2024-09-13 19:05
This issue will be closed.

**Closed by aiday-mar** 2024-09-13 19:05 UTC
Labels: upstream-issue-fixed, chromium, editor-edit-context
