### ISSUE TITLE
C Language (Cpptools extension) struct item completion not correct

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#23094] opened 2017-03-23 12:34 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.0|;

---

Steps to Reproduce:

if you have multi struct like:
typedef struct
{
    int a;
    int b;
}stA_t;

typedef struct
{
    int c;
    int d;
}stB_t;

define a struct like:
stA_t st_a;

when you used the auto completion
st_a when you input the point (.), you will get all struct item (a, b, c, d) in the auto completion window for notify. why not a, b for st_a ?

**Comment by sean-mcmanus** [comment] 2017-03-23 15:09
cpptools issues should be reported at https://github.com/Microsoft/vscode-cpptools/issues . The tracking issue is https://github.com/Microsoft/vscode-cpptools/issues/13 .

This is currently "by design" until we implement completion with the IntelliSense engine (i.e. the one used for Visual Studio 2017 completion). Our current completion (and other features) will include too much because it doesn't take the actual types into account when filtering and just uses a name lookup with some addition context, such as if there's a "." on the left, indicating we should return only members.

**Comment by mjbvz** [comment] 2017-03-23 20:41
Thanks @sean-mcmanus!

Yes, this looks like an issue with the cpptools extension and not core vscode. Closing as external

**Closed by mjbvz** 2017-03-23 20:41 UTC
Labels: caused-by-extension
