### ISSUE TITLE
HTML Formatter not working

### ISSUE THREAD

**Issue by jschrader00** [Microsoft/vscode#25027] opened 2017-04-19 17:23 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|
|nunjucks|ronnidc|0.2.3|;

---

Steps to Reproduce:

1. Opened HTML document (tried with several different ones, all have the .html extension)
2. Hit Shift+Alt+F

Before the most recent update this functionality was working and now it appears to be broken. I have not changed any extensions, settings, or anything about my installation whatsoever other than accepting the most recent update so I don't understand why the formatter is no longer working and can only conclude that something in the update broke this functionality

**Comment by mjbvz** [comment] 2017-04-19 18:13
Quick question: can you run the `format document` command using the command palette?

**Comment by jschrader00** [comment] 2017-04-19 18:57
Currently I am unable to run the 'format document' command in the command palette, is this a situation where I should uninstall and reinstall VSCode?

**Comment by aeschli** [comment] 2017-04-20 07:37
You didn't by chance disable the built-in html formatter with
`"html.format.enable": false,` ?

**Comment by winterlimelight** [comment] 2017-04-28 00:42
I'm the same. `Ctrl-Shift-P` plus `format document` returns no results in .html file, but does in .ts file
I have confirmed File > Preferences > Settings contains: "html.format.enable": true

Possibly related: my current open folder has "editor.detectIndentation": false in settings.json

VSCode v1.11.2 Commit 6eaebe3b...
Extensions: aurelia 0.3.2, C# 1.9.0, Docker 0.0.13, PowerShell 0.12.2

**Comment by cleidigh** [comment] 2017-05-01 18:28
@aeschli 
Windows7
Insiders 4-28 build

Just experienced the same problem last night.
verified html.format.enable true
no other formatting setups
Format document command from command palette does not work

**Comment by t03apt** [comment] 2017-05-04 13:17
Same issue here. I can't format selected text in html files with ctrl+k, ctrl+f. It works in other file types like .ts. It used to work for html as well.

**Comment by cleidigh** [comment] 2017-05-09 02:46
formatting is working in the latest insiders

**Comment by aeschli** [comment] 2017-05-26 20:16
Closing, I can't reproduce this

**Closed by aeschli** 2017-05-26 20:16 UTC
Labels: format, html, needs more info

**Comment by winterlimelight** [comment] 2017-05-30 01:29
Fair deal. I noted now it was working again for me with 1.12.2. There's also been some aurelia extension updates in the interim.

**Comment by chrisxue815** [comment] 2017-08-12 16:17
I thought html formatting was not working for me but it was just pretty slow on large files.

**Comment by aeschli** [comment] 2017-08-14 08:13
+1 on showing better progress if the operation takes longer.
We use http://jsbeautifier.org/ as the underlying html formatter. Can you try you code sample there and see if it is problem of the formatter? If not it might also be in our code that evaluates a minimal diff from the result.

**Comment by chrisxue815** [comment] 2017-08-15 22:08
Please find my original html here: https://jsfiddle.net/chrisxue815/hot1g5nw/
http://jsbeautifier.org/ finishes very fast (less than a second) with the default settings.
But it takes ~10 seconds if I paste back the original html and switch "Do not wrap lines" to "Wrap lines near 80 characters".
VS Code takes ~20 seconds on my laptop (Intel i5 2.7GHz).

**Comment by aeschli** [comment] 2017-08-16 08:08
In VSCode we run the HTML formatter with line_length of 120 characters. So it seems part of the slow down is really in the formatter. I created https://github.com/beautify-web/js-beautify/issues/1231

**Comment by aeschli** [comment] 2017-08-16 08:20
I traced the work we do and could not see anything obvious. The code that creates minimal edits uses only around 20ms. Tokenization (Syntax highlighting) takes around a second. Keeping closed for now.
