### ISSUE TITLE
GUI/Icons problem on MacOS

### ISSUE THREAD

**Issue by MrSpock** [Microsoft/vscode#28700] opened 2017-06-14 08:25 UTC
Hi,

After last upgrade from time to time I have some icon problems (see screenshot attached).
Sometimes it's ok - sometimes problems exists.I need to start/close app many time to get proper icon look and there seems to be no pattern how many times I need to repeat open/close procedure.
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: macOS Sierra 10.12.5 (16F73)

Steps to Reproduce:

1. Lauch Visual Studio 
![zrzut ekranu 2017-06-14 10 21 14](https://user-images.githubusercontent.com/681680/27122664-b3c23c78-50eb-11e7-8ce4-a9d767420b4a.png)

**Comment by opHASnoNAME** [comment] 2017-06-14 08:27
Same here, after installing any kind of plugin.

**Comment by MrSpock** [comment] 2017-06-14 08:29
After reading some other post - for me this happens whether I'm starting VSC from cli or by clicking app icon.
My env is zsh with following LC_*:

```
--- devel/rls_vscode ‹master› » env|grep LC
LC_CTYPE=pl_PL.UTF-8
--- devel/rls_vscode ‹master› »
```

**Comment by rohmanhm** [comment] 2017-06-14 08:39
Do you have tried to uninstall and reinstall vscode again?

**Comment by rohmanhm** [comment] 2017-06-14 08:40
https://github.com/Microsoft/vscode/issues/28345

**Comment by opHASnoNAME** [comment] 2017-06-14 08:41
Just installed it today

**Comment by rohmanhm** [comment] 2017-06-14 08:44
Just wait for new release. 
Fixed by https://github.com/Microsoft/vscode/commit/240cf011a18b037a1929cace7bf5a3086aac6dbe

**Comment by ramya-rao-a** [comment] 2017-06-14 16:44
Thanks @rohmanhm 

Duplicate of #28345

The fix is in Insiders and will be out in the recovery build for 1.13 which should be out soon

cc @bpasero

**Closed by ramya-rao-a** 2017-06-14 16:44 UTC
