### ISSUE TITLE
VS Code check JS

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#28127] opened 2017-06-06 18:04 UTC
- VSCode Version: 1.12
- OS Version: Linux Ubuntu 17.04

I'm using this setting:
```
"javascript.implicitProjectConfig.checkJs": true
```
This is something WOW, I even deleted Flow and not using it anymore, but left only this annoying problem, I can't add properties in req object....

However I can create it and no error/warning:

```
req.userId = decodedToken.userId;
```

But then I'm trying to use it in one of my routes I get the problem.

```
Property 'userId' does not exist on type 'Request',
```

But you can add properties in req object in your middleware, even Express is documented it https://expressjs.com/en/api.html#app.param. I can't use locals or to add it directly. I know it's definitions, but since this is VS Code I don't know where I need to open an issue.

**Comment by mjbvz** [comment] 2017-06-06 21:43
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10868 We currently do not recognize properties added to types after they are created. 

For express, try augmenting the `Request` interface by creating a `.d.t.s` file that defines the extra properties from your middleware:

```ts
declare namespace Express {
   export interface Request {
        user_id: string
    }
}
```

All request objects should now have a `user_id` property

**Closed by mjbvz** 2017-06-06 21:43 UTC
Labels: duplicate, javascript, typescript, upstream

**Comment by svipben** [comment] 2017-06-06 22:21
@mjbvz Thank you very much!
