### ISSUE TITLE
Extensions not loading and Terminal Integration broken after update

### ISSUE THREAD

**Issue by mtaylor769** [microsoft/vscode#160003] opened 2022-09-03 20:58 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: LTS
- OS Version: LTS

Steps to Reproduce:

1. Click on the "Extensions" tab and wait (and wait, and wait, and wait)
2. Click on a Terminal and wait (and wait and wait and wait), 
  2a. Search in vain on the internet for a solution
3. File bug report 

<img width="1366" alt="Screen Shot 2022-09-03 at 1 55 52 PM" src="https://user-images.githubusercontent.com/945227/188287463-967d9aaa-9558-4816-bb84-197a2d0ed4b2.png">

**Comment by gjsjohnmurray** [comment] 2022-09-03 21:11
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by natenho** [comment] 2022-09-03 22:39
Ok, I guess there is something wrong with the new version. Just opening an extension preview inside the extension tab is enough to show this

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

![image](https://user-images.githubusercontent.com/4236481/188289613-5cd44f87-c6ca-4daf-83cd-12a8aa42c623.png)

Bisect result
![image](https://user-images.githubusercontent.com/4236481/188289617-ef54121e-04c5-41a9-9ece-03cbd507937d.png)

**Comment by mtaylor769** [comment] 2022-09-04 00:31
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

I cannot get that far, but @natenho seems to have identified the issue, thanks.

**Comment by mtaylor769** [comment] 2022-09-04 00:38
Here is the output from the "Log (Extension Host)" panel:
```
[2022-09-02 22:07:33.776] [exthost] [info] Extension host with pid 2688 started
[2022-09-02 22:07:33.776] [exthost] [info] Skipping acquiring lock for /Users/mtaylor/Library/Application Support/Code/User/workspaceStorage/81df9cbee3859b64a03a10015984c98d.
[2022-09-02 22:07:34.223] [exthost] [info] ExtensionService#_doActivateExtension kevinglasson.cornflakes-linter, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:34.234] [exthost] [info] ExtensionService#_doActivateExtension KevinRose.vsc-python-indent, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:34.239] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.pylint
[2022-09-02 22:07:35.008] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:35.222] [exthost] [info] ExtensionService#_doActivateExtension njpwerner.autodocstring, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:35.274] [exthost] [info] ExtensionService#_doActivateExtension tht13.python, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:35.304] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:07:35.424] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.433] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-09-02 22:07:35.436] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.440] [exthost] [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.465] [exthost] [info] ExtensionService#_doActivateExtension cssho.vscode-svgviewer, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.487] [exthost] [info] ExtensionService#_doActivateExtension develax.daddy-jest, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.489] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-close-tag, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.490] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-rename-tag, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.581] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: true, activationEvent: '*', root cause: GitHub.vscode-pull-request-github
[2022-09-02 22:07:35.650] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.global-config, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.702] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.test-adapter-converter, startup: true, activationEvent: '*', root cause: hbenl.vscode-test-explorer
[2022-09-02 22:07:35.705] [exthost] [info] ExtensionService#_doActivateExtension IHunte.laravel-blade-wrapper, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.707] [exthost] [info] ExtensionService#_doActivateExtension johnpapa.vscode-peacock, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.716] [exthost] [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.758] [exthost] [info] ExtensionService#_doActivateExtension mrorz.language-gettext, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.759] [exthost] [info] ExtensionService#_doActivateExtension ms-mssql.data-workspace-vscode, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.831] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.921] [exthost] [info] ExtensionService#_doActivateExtension naumovs.color-highlight, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.948] [exthost] [info] ExtensionService#_doActivateExtension ryannaddy.vscode-format, startup: true, activationEvent: '*'
[2022-09-02 22:07:35.950] [exthost] [info] ExtensionService#_doActivateExtension Shan.code-settings-sync, startup: true, activationEvent: '*'
[2022-09-02 22:07:36.152] [exthost] [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons, startup: true, activationEvent: '*'
[2022-09-02 22:07:36.392] [exthost] [info] ExtensionService#_doActivateExtension wayou.vscode-todo-highlight, startup: true, activationEvent: '*'
[2022-09-02 22:07:36.733] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-09-02 22:07:46.273] [exthost] [info] Not activating extension 'lextudio.restructuredtext': Timed out while searching for 'workspaceContains' pattern **/*.rst
[2022-09-02 22:07:46.273] [exthost] [info] Not activating extension 'ms-python.pylint': Timed out while searching for 'workspaceContains' pattern *.py
[2022-09-02 22:07:46.273] [exthost] [info] Not activating extension 'ms-vscode.cmake-tools': Timed out while searching for 'workspaceContains' pattern */CMakeLists.txt,*/*/CMakeLists.txt,*/*/*/CMakeLists.txt
[2022-09-02 22:07:46.273] [exthost] [info] Not activating extension 'olback.bar': Timed out while searching for 'workspaceContains' pattern **/.vscode/bar.conf.json
[2022-09-02 22:07:46.273] [exthost] [info] Not activating extension 'zobo.php-intellisense': Timed out while searching for 'workspaceContains' pattern **/*.php
[2022-09-02 22:08:11.290] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-09-02 22:08:11.548] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-09-02 22:08:11.563] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2022-09-02 22:08:12.312] [exthost] [info] ExtensionService#_doActivateExtension hbenl.vscode-test-explorer, startup: true, activationEvent: '*'
[2022-09-02 22:08:12.501] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2022-09-02 22:08:12.732] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:12.915] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:13.036] [exthost] [info] ExtensionService#_doActivateExtension aaron-bond.better-comments, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:13.046] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.project-manager, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:13.112] [exthost] [info] ExtensionService#_doActivateExtension cweijan.vscode-mysql-client2, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:17.231] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:17.251] [exthost] [info] ExtensionService#_doActivateExtension dsznajder.es7-react-js-snippets, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:19.975] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:20.290] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onStartupFinished', root cause: esbenp.prettier-vscode
[2022-09-02 22:08:20.338] [exthost] [info] ExtensionService#_doActivateExtension felipecaputo.git-project-manager, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:20.549] [exthost] [info] ExtensionService#_doActivateExtension fnando.linter, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:20.743] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:20.941] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:21.118] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:21.229] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:21.468] [exthost] [info] ExtensionService#_doActivateExtension trunk.io, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:08:23.987] [exthost] [info] ExtensionService#_doActivateExtension lextudio.restructuredtext, startup: true, activationEvent: 'workspaceContains:**/*.rst'
[2022-09-02 22:08:26.871] [exthost] [info] ExtensionService#_doActivateExtension ms-python.pylint, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:08:26.978] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'onLanguage:python'
[2022-09-02 22:08:28.511] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-09-02 22:08:28.516] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-09-02 22:08:29.116] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-09-02 22:08:29.446] [exthost] [info] ExtensionService#_doActivateExtension rvest.vs-code-prettier-eslint, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-09-02 22:08:31.744] [exthost] [info] ExtensionService#_doActivateExtension kavod-io.vscode-jest-test-adapter, startup: true, activationEvent: '*'
[2022-09-02 22:08:47.397] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:10:34.471] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame, startup: false, activationEvent: 'onStartupFinished'
[2022-09-02 22:10:35.621] [exthost] [info] Eager extensions activated
```

**Comment by natenho** [comment] 2022-09-04 04:29
@mtaylor769 The problem that I mentioned was gone after a reboot. So it may not be related to your scenario. =/

**Comment by romeguarin** [comment] 2022-09-04 07:51
I have the same issue but the repro steps are different:

1. Open VS Code, with a preloaded directory from the previous session
2. Open a Terminal, this opens the current directory
3. Split Terminal, result here is VS code would display an error prompt saying: The terminal process failed to launch: Starting Directory (cwd) ... "<path of current directory>" does not exist. 
the error message shows the directory with double double quotes as well, but I don't remember setting this up like this within VS code

![image](https://user-images.githubusercontent.com/6064432/188303256-014caa98-849b-4ee7-9e78-70ba64a9be33.png)

**Comment by gjsjohnmurray** [comment] 2022-09-04 08:10
> I cannot get that far,

@mtaylor769 please try launching VS Code with the `--disable-extensions` argument.

**Comment by Pictor13** [comment] 2022-09-04 23:29
I've restarted VSCode many times and got the terminal crashing & closing itself with no error every time.
The terminal started to initialize correctly again, after running with `--disable-extensions`.
When running again without the flag, the terminal started to work again as expected.
Probably it reset something somewhere.

Give it a try!

**Comment by mtaylor769** [comment] 2022-09-06 16:50
Good morning, I trust everyone (in the U.S.) had a nice holiday? I've started VSCode with `--disable-extensions` as mentioned here. Once it's loaded a notification appeared saying "Extensions have been disabled." and a button saying "Reaload & Start Extensions?". Click, boom! I'll add this to my debugging notes for VSCode in case this happens again.

As far as I am concerned, this ticket can be closed, unless there are more comments from others.

**Comment by mtaylor769** [comment] 2022-09-07 20:08
Closing.

**Closed** 2022-09-07 20:07 UTC
