### ISSUE TITLE
Open browser [Node.js]

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#8318] opened 2016-06-28 11:03 UTC
Hi, is it possible to open the browser after starting a Node.js application? This feature can be appreciated in Node.js tools for visual studio.

Thanks.

**Comment by isidorn** [comment] 2016-06-28 13:33
This would need to come from the node debug adapter - thus forwarding to @weinand

**Comment by weinand** [comment] 2016-06-28 21:53
@sant123 this is not possible, but it is a valid feature request.

**Comment by sant123** [comment] 2016-06-28 23:47
Thank you @weinand ☺

**Comment by weinand** [comment] 2017-04-05 10:27
duplicate of #2405

**Closed by weinand** 2017-04-05 10:27 UTC
Labels: debug, feature-request
