### ISSUE TITLE
Search shows results for the same file twice if it's open as a differently-cased filename

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode#11607] opened 2016-09-06 22:21 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10

I'm not sure if it can be easily reproduced using plain VS Code, but if some extension screws up the file name case in e.g. a "definition provider", this will happen: https://github.com/hackwaly/vscode-ocaml/issues/56

Looks like file paths are used as keys somewhere and they are not normalized or something. Maybe it's not just search, but also other places.

**Comment by jrieken** [comment] 2016-09-07 07:18
@nadako Please include reproducible steps

**Comment by nadako** [comment] 2016-09-07 20:41
Hmm, that's gonna be hard, since my particular case requires a lot of setup (ocaml, merlin, vscode-ocaml extension), but I could try writing a sample extension that surfaces the issue...

**Comment by jrieken** [comment] 2016-09-27 12:27
closing since the issue still lack repo steps

**Closed by jrieken** 2016-09-27 12:27 UTC
Labels: needs more info
