### ISSUE TITLE
Intellisense slow loading snippets for `import` statements

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode#37943] opened 2017-11-09 13:14 UTC
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Launch VS Code.
2. Open `tmp.ts` file and **quick** enter text `import ` (with whitespace). If we enter it very slowly, then everything works as it should be.
3. Only first time VS Code not show snippet for `import`  statment.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-11-14 00:06
I can't reproduce this with 1.18 and Typescript 2.6.1. What version of TS are you using? Does this happen in all files or just in some of them?

**Comment by KostyaTretyak** [comment] 2017-11-14 09:46
@mjbvz, I reproduce this with VS Code 1.18.0, TypeScript v2.6.1. Ater I rollback to VS Code 1.17.2, this effect disappears (along with bug https://github.com/Microsoft/vscode/issues/37939).

**Comment by mjbvz** [comment] 2017-11-15 19:43
This sounds like https://github.com/Microsoft/TypeScript/issues/20047 A few other users have also been hitting this.

Can you please try collecting the TS Server log as I describe [in this comment](https://github.com/Microsoft/vscode/issues/36825#issuecomment-340124211)

**Comment by KostyaTretyak** [comment] 2017-11-15 19:49
> This sounds like Microsoft/TypeScript#20047 A few other users have also been hitting this.

No, I see this effect only on VS Code v1.18.0, not on v1.17.2.

> Can you please try collecting the TS Server log as I describe in this comment

Sorry, but I rollback to VS Code 1.17.2

**Comment by mjbvz** [comment] 2017-11-15 19:51
That issue is for 1.18 (TypeScript 2.6). Please try collecting the logs and either opening new issue against TypeScript or positing it on the one I created.

Closing as upstream

**Closed by mjbvz** 2017-11-15 19:51 UTC
Labels: javascript, needs more info
