### ISSUE TITLE
Find results in the settings editor do not show up in the scroll bar

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#51516] opened 2018-06-09 09:39 UTC
Not sure if this used to work but it's hard to find settings that you already have set because they don't show up in the scroll bar:

<img width="1058" alt="screen shot 2018-06-09 at 11 37 31 am" src="https://user-images.githubusercontent.com/2193314/41190132-8b4c1818-6bd9-11e8-8111-586d31ddf81f.png">

**Comment by sandy081** [comment] 2018-06-11 09:17
Duplicate of #39543

**Closed** 2018-06-11 09:18 UTC
Labels: *duplicate, settings-editor
