### ISSUE TITLE
Re: Allow tasks to run commands regardless of their output

### ISSUE THREAD

**Issue by guestieng** [microsoft/vscode#119169] opened 2021-03-17 10:07 UTC
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:

I refer to [#97161](https://github.com/microsoft/vscode/issues/97161#issue-614160952): I am experiencing exactly the same issue with error messages 
_"Cannot substitute command variable '\<command variable\>' because command did not return a result of type string."_.
This is quite unexpected behaviour.

**Comment by alexr00** [comment] 2021-03-17 11:10
Duplicate of https://github.com/microsoft/vscode/issues/97161

**Closed** 2021-03-17 11:10 UTC
Labels: *duplicate

**Comment by guestieng** [comment] 2021-03-17 12:21
It's a little confusing that all issue reports on this subject are being closed directly,
since this appears to be an unresolved bug, doesn't it?

**Comment by guestieng** [comment] 2021-03-18 11:19
It's a little confusing that all issue reports on this subject are being closed directly,
since this appears to be a bug, doesn't it?
