### ISSUE TITLE
License links to completely empty webpage

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8252] opened 2016-06-28 08:58 UTC
Testing #8215 

License button takes me to empty page:

* search for @popular
* pick HTML CSS Class Completion
* click on license in the header

https://marketplace.visualstudio.com/items/Zignd.html-css-class-completion/license

-> Completely empty webpage. What's up with that?

![image](https://cloud.githubusercontent.com/assets/5047891/16409696/29ef0462-3d1f-11e6-934d-083b69d17f8c.png)

**Comment by isidorn** [comment] 2016-06-28 09:02
I believe as designed, that extension does not have a license, however some extensions do e.g
https://marketplace.visualstudio.com/items/ms-vscode.wordcount/license

All in all, assigning to july and joao so he can decide if we can improve this.
IMHO it is up to the extension to upload the license to the marketplace

**Comment by alexandrudima** [comment] 2016-06-28 09:02
But can you also reach out to the marketplace contacts that they could show a good message?

**Comment by isidorn** [comment] 2016-06-28 09:13
@alexandrudima sent an email

**Comment by isidorn** [comment] 2016-06-28 18:03
Closing this as marketplace team will handle it. Quoting
"
Hi Isidor,
 
Thanks for reporting this issue to us. Our current behavior is if the publisher doesn’t provide a license link in the manifest we don’t display the link in the item details page. But looks like direct navigation to the link is still active. We’ll file an issue on our side and check on how we should be handling this scenario.
 
Thanks & Regards
Harysh
"

**Comment by alexandrudima** [comment] 2016-06-29 12:22
@isidorn What's the rush with closing this? 

In general, we have 124 open upstream bugs. Just because it's upstream doesn't mean we cannot try to work around it on our side.

Specifically, for this issue, here is an example of improving the user experience on our side:
* if an extension does not have a license, show the label "No License" and do not put a link that opens a browser
* imagine the marketplace fix their empty page - by rendering the text "No License" ... because what else could they do if an extension does not have a license? How is that a good user experience? We might want to go and workaround on our side.

Just my 2 cents.

**Comment by isidorn** [comment] 2016-06-29 12:29
@alexandrudima makes sense - let me reopen

**Comment by joaomoreno** [comment] 2016-07-12 09:27
cc @modigrv @hamenon

**Comment by hamenon** [comment] 2016-07-12 09:44
@alexandrudima Agree with your note. Today on the Marketplace website for instance if a license is not available we don't display the link in the resources section. We could have a similar behavior within the editor as well, with either text noting that the license has not been provided or just not display the link. I'll  follow up with the legal teams on whether there is some form of default license we can use.

**Comment by joaomoreno** [comment] 2016-07-12 13:20
@hamenon Or at least some information whether a license is available, in the extension query results.

**Comment by joaomoreno** [comment] 2016-08-17 14:11
Fixed! The link will not appear if the extension has no license.

**Closed by joaomoreno** 2016-08-17 14:11 UTC
Labels: extensions, upstream

**Comment by alexandrudima** [comment] 2016-08-17 15:14
@joaomoreno maybe set milestone to Aug so it gets verified

**Comment by Tyriar** [comment] 2016-08-31 22:34
I verified in some other issue already
