### ISSUE TITLE
Make outdated extension update prompt not count manually installed old version extensions in.

### ISSUE THREAD

**Issue by Xdminsy** [microsoft/vscode#131346] opened 2021-08-22 08:28 UTC
Say we can install a specific version of an extension, and an outdated update prompt shows a number badge.

So the problem here is, I just wanna lock an extension's version. I installed a specific old version extension, and I won't let it update, but now I have no way to tell vscode that it needs no update, vscode see it has a new version and always shows a badge numbered '1' on the sidebar, it's quite annoying.

We need a feature like other package managers have, lock specific extensions versions, so when checking new versions it can skip such locked extensions, sometimes maybe I just wanna try one old version a while to find regression, or sometimes I choose 

For example, I use vscode-vim 1.16 for the whole of last year, this extension has much more problems after this version and I can see they may never be fixed, so I don't need its new versions, I tried many times installing some new versions this year, the newer the problems arise more, I don't wanna see the badge '1' always shows on the sidebar because I have chosen the specific version.

I see some workaround says that I can make the badge's background transparent, but it's extremely strange way, this hides other extensions updates messages, and this operation lets vscode-vim easymotion hints to be transparent, so this workaround is quite not useful.

**Comment by sandy081** [comment] 2021-08-23 12:18
How did you install old version of an extension? Have you done it using the UI in extensions view?

**Comment by Xdminsy** [comment] 2021-08-23 12:25
Ah yes, I select "Install Another Version" in the manage menu of an extension.

**Comment by sandy081** [comment] 2021-08-23 12:28
If so, you shall not be seeing the outdated badge. Can you please try with another extension and see if you can repro it? If so, also provide steps you followed.

**Comment by Xdminsy** [comment] 2021-08-23 12:53
![w](https://user-images.githubusercontent.com/9005053/130449918-f655010a-f4fb-4bc4-9580-41cd467ed6af.gif)

Yes, I made a record, I download a new pure vscode 1.59.1 and make it portable, so it has no other extensions.

I just select a popular extension in the sidebar, say ESLint, and I see it seems I cannot directly install an old version.

So I first install it and then choose to install a specific old version.

And VSCode prompts me to update it because it is outdated.

**Comment by sandy081** [comment] 2021-08-24 13:27
/duplicate

Thanks for the repro. Duplicate of https://github.com/microsoft/vscode/issues/32505

**Closed** 2021-08-24 13:27 UTC
Labels: needs more info, *duplicate
