### ISSUE TITLE
when terminal address have Chinese， will be repeated

### ISSUE THREAD

**Issue by baixiaoyu2997** [Microsoft/vscode#28611] opened 2017-06-13 10:02 UTC
- VSCode Version:1.13.0
- OS Version:win10

Steps to Reproduce:

1.
![4](https://user-images.githubusercontent.com/9149999/27077311-366a5b40-5062-11e7-8839-6de72837afa0.png)

2.
![5](https://user-images.githubusercontent.com/9149999/27077358-6125169a-5062-11e7-94c1-6494e3f36e44.png)

**Comment by CherryDT** [comment] 2017-06-13 14:08
Duplicate of #26038

@baixiaoyu2997 As I understand, this is already fixed and will be released soon.

**Comment by ramya-rao-a** [comment] 2017-06-13 17:17
Thanks @CherryDT, that's right

**Closed by ramya-rao-a** 2017-06-13 17:17 UTC
Labels: new release
