### ISSUE TITLE
Add ability to copy removed code in snippet mode (Click on the left sideline in editor section)

### ISSUE THREAD

**Issue by IPR-Kaspar** [microsoft/vscode#85542] opened 2019-11-25 14:07 UTC
![image](https://user-images.githubusercontent.com/54580256/69546976-67901780-0f9d-11ea-8499-3be8e20026a4.png)

When I try to select green text it selects and I can copy it. The red code I can't select and copy if need it. Has to go to full mode with difference comparison to select it. Would be convenient to do it in snippet mode (Click on the left sideline in editor section)

**Comment by IllusionMH** [comment] 2019-11-25 14:36
/duplicate of #8226

See https://github.com/microsoft/vscode/issues/8226#issuecomment-528103843 for currently working approach

**Closed** 2019-11-25 14:36 UTC
Labels: *duplicate
