### ISSUE TITLE
Formatting adds newline to textarea when opening and closing tags are on different line

### ISSUE THREAD

**Issue by deMD** [Microsoft/vscode#59240] opened 2018-09-24 14:42 UTC
I am having a problem with the HTML formatter used in Visual Studio code. If I have a <textarea> with the **closing tag on a seperate line**, then when I format the file newlines are added between the opening and closing tags exponentially.

![2018-09-24_16-33-54](https://user-images.githubusercontent.com/22070292/45958797-a41e5700-c018-11e8-93bc-361efde494f7.gif)

- VSCode Version: 1.27.2
- OS Version: Windows 10 Enterprise 10.0.17134

Steps to Reproduce:
1. create a new html file
2. add `<textarea>[newline]<textarea>` 
3. save or format the file.
4. repeat step 3.

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by aeschli** [comment] 2018-09-24 19:16
duplicate of #58435, fixed in the latest insiders build.

**Closed by aeschli** 2018-09-24 19:16 UTC
Labels: html
