### ISSUE TITLE
A11y_Visual Studio Code_ Different Outputs_Usability: Outputs are not produced for Tasks, Extensions, Microsoft Authentication types.

### ISSUE THREAD

**Issue by Latha2564** [microsoft/vscode#131907] opened 2021-08-30 06:42 UTC
GitHubTags:#A11y_VSCode;#A11ySev4;#A11yTCS;#A11yUsable;#DesktopApp;#Visual Studio Code Client;#MAC;#AINotInScope;#Benchmark-VisualStudioCode-MAC-Aug2021

### Environment Details:​
Application Name: Visual Studio Code
Standard Violated: Usability

### Repro Steps:​
1.Open Visual Studio Code editor
2.Tab till any Program code tab and press enter.
3.Run the Code.
4.Verify the outputs for the Code using Short cut "Command+Shift+U".
5.Verify whether the output is appear for all types of Output or not.
### Actual Result:
 Outputs are not produced for Tasks, Extensions, Microsoft Authentication types,
### Expected Result: 
 Outputs should  be  produced for  all types of Output.
### User Impact:
 All users find difficult if the Outputs are not produced for Tasks, Extensions, Microsoft Authentication types.

**Comment by sandy081** [comment] 2021-09-13 13:29
Assigning to our accessibility expert @isidorn to get his insights first.

**Comment by isidorn** [comment] 2021-09-15 14:25
This is working as designed. 
The output gets produced when it makes sense, not for every channel. Since there is no Tasks output that channel will be empty.
This is nothing related to accessibility.

This video should clarify things regarding the output panel https://www.youtube.com/watch?v=ls6clvYr4Ow

**Closed by isidorn** 2021-09-15 14:25 UTC

**Comment by Latha2564** [comment] 2021-09-17 08:08
![131907](https://user-images.githubusercontent.com/89508906/133748012-0ad79436-28d6-40bd-a520-b3ca0f6894c4.gif)
