### ISSUE TITLE
Unable to copy all text in debug console

### ISSUE THREAD

**Issue by shevah** [Microsoft/vscode#13677] opened 2016-10-13 13:25 UTC
- VSCode Version: 1.6.0
- OS Version: Win 10 x64 pro

Steps to Reproduce:

1. Open a python file that contains the following lines:
```
for i in range(100):
    print i
```
2. Debug it (F5).
3. Try selecting the output from the debug console, you will notice that when 'ctrl+c' it, only 10 lines or so get copied.

Any ideas?

**Comment by isidorn** [comment] 2016-10-13 13:33
Duplicate of https://github.com/Microsoft/vscode/issues/2163

**Closed by isidorn** 2016-10-13 13:33 UTC
