### ISSUE TITLE
Using the context menu with the keyboard in explorer view does not act on the selected item

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#115282] opened 2021-01-28 04:05 UTC
/CC: @isidorn 

Issue Type: <b>Bug</b>

1. In the explorer view, arrow to a folder. Press the applications key, and choose "new folder"
2. Type the name for the new folder.

Expected: the new folder is created underneath the folder that was selected
Actual: folder is created underneath the root.

This problem also affects copy and paste operations, and I'd assume anything involving the context menu. 

This issue doesn't happen when using a mouse to right-click the item to activate the context menu.

It has a pretty large impact on my productivity, since I can't easily use the explorer view.

VS Code version: Code - Insiders 1.53.0-insider (9ee751e859d655e1e80fa0d57253304c01c65732, 2021-01-27T05:13:34.088Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.23GB (19.66GB free)|
|Process Argv|. --crash-reporter-id 1304d64e-abdb-456c-beb6-72c33120f731|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
remote-containers|ms-|0.156.0
vscode-versionlens|pfl|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600:30247031
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by IllusionMH** [comment] 2021-01-28 10:25
Application key === Context menu key? Then looks like duplicate of #109870

Another system wide shortcut <kbd>Shift</kbd>+<kbd>F10</kbd> works fine in the meantime.

**Comment by isidorn** [comment] 2021-01-28 10:59
Yeah, closing as dup. Can you please use the `Shift+F10` in the meantime @Neurrone 
@IllusionMH thanks for providing the information.

**Closed** 2021-01-28 11:00 UTC
Labels: *duplicate, file-explorer

**Comment by Neurrone** [comment] 2021-01-28 12:11
Thanks for the workaround - will follow the linked issue.
