### ISSUE TITLE
Feature Request - Intellisense - Sort by use frequency

### ISSUE THREAD

**Issue by tsummerall** [Microsoft/vscode#37548] opened 2017-11-02 19:05 UTC
Intellisense should keep track of how often particular items are selected by the user and have an option to modify the sort order of suggestions based on this.

For example when I type `console.`  I get the full list of console member functions sorted alphabetically even though 99% of the time I end up choosing `log`. After some period of use the `log` member function should appear at the top, perhaps in a "frequently used" area.

**Comment by jrieken** [comment] 2017-11-03 07:59
dupe of #22839

**Closed by jrieken** 2017-11-03 07:59 UTC
Labels: suggest
