### ISSUE TITLE
Feature Request: Execute highlighted code when debugging

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode#28907] opened 2017-06-16 19:07 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393

This is a feature request. It's a request to implement what the Chrome developer tools has. Currently, if you are debugged at a point in the JS code, you can highlight some code and when you mouse-over the code, it will execute it and show you the results. It's really useful and faster than copying and pasting into the debug console of VS Code. Here's what I'm talking about:

![image](https://user-images.githubusercontent.com/791996/27241065-1089e630-528c-11e7-9ab7-7376b731b069.png)

You can see that the web app is currently paused at line number 344 and `11 + 11` is highlighted. When I mouse over, a popup comes up and shows me the output. This would be really cool for debugging NodeJS or Chrome in VSCode.

**Comment by isidorn** [comment] 2017-06-19 08:59
Thanks for the feature request however this is a duplicate of https://github.com/Microsoft/vscode/issues/18058

We are accepting PRs

**Closed by isidorn** 2017-06-19 08:59 UTC
Labels: debug, new release

**Comment by AskYous** [comment] 2017-06-19 11:11
Cool. Thanks for the update.
