### ISSUE TITLE
Git: stage selected ranges does not work from normal editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#50797] opened 2018-05-30 14:33 UTC
Steps to Reproduce:

1. have a file with changes
2. select some lines
3. invoke "stage selected ranges" either from command palette or via keybinding

=> does not seem to work

**Comment by usernamehw** [comment] 2018-05-30 16:13
Duplicate of #42909

**Closed** 2018-05-31 07:20 UTC
Labels: bug, git, help wanted
