### ISSUE TITLE
Orca can't see breakpoints set in a file

### ISSUE THREAD

**Issue by ajborka** [microsoft/vscode#93345] opened 2020-03-25 01:45 UTC
@isidorn ,

Orca cannot see breakpoints defined in a file. I use Ubuntu 20.04, Orca master (3.37.1 pre), and vscode insiders build from last night. To reproduce, do the following:

* Start Orca.
* Start vscode insiders.
* Create a new file if one is not provided by default.
* Change the language to HTML5.
* Type 'html5' then press TAB on HTML:5 suggestion.
* Between the opening and closing body tags, insert an element such as div or h1.
* On the same line, press F9 to add a breakpoint. Orca will then announce that a breakpoint was added on the line number of the cursor, then repeat the filename.
* Press up arrow to move away from the line, then press down arrow to move back to the breakpoint.

Actual results: Orca reads the line of code as expected. However, there is no indication of a breakpoint.
Expected results: Orca should indicate a breakpoint on the line in which the breakpoint is set.

**Comment by isidorn** [comment] 2020-03-25 09:04
Duplicate of https://github.com/microsoft/vscode/issues/90842
Let's continue the discussion on that issue.
Our latest idea is that we potentialy use aria annotations for breakpoints
fyi @aleventhal @joanmarie

**Closed by isidorn** 2020-03-25 09:04 UTC
