### ISSUE TITLE
Auto fill all text when rename(F2) file or folder

### ISSUE THREAD

**Issue by shernk** [microsoft/vscode#123304] opened 2021-05-07 16:01 UTC
- VS Code Version: 1.56.0
- OS Version: Windows x64

Steps to Reproduce:

1. After click rename
- What you expected is:
![2 1](https://user-images.githubusercontent.com/31926953/117477291-089f4200-af88-11eb-99da-e8876b02ad02.png)
- The result showed is:
![1 1](https://user-images.githubusercontent.com/31926953/117477340-1654c780-af88-11eb-9fd6-02953b01cfc3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by nrayburn-tech** [comment] 2021-05-07 19:17
Duplicate of https://github.com/microsoft/vscode/issues/123044.

You can change to a theme other than Monokai to workaround this temporarily.

**Comment by isidorn** [comment] 2021-05-10 07:29
@nrayburn-tech thanks a lot for pointing out the duplicate 👏

**Closed** 2021-05-10 07:29 UTC
Labels: *duplicate
