### ISSUE TITLE
Typescript import auto completion not working in Insiders

### ISSUE THREAD

**Issue by avifatal** [Microsoft/vscode#61953] opened 2018-10-27 16:15 UTC
Hi,
I think one or two updates ago, the import was stoppoed working... see image bellow.

Any suggestions?
Thanks

![image](https://user-images.githubusercontent.com/12430740/47606447-6dbf6780-da1c-11e8-974f-28e0bd2b3ee5.png)

```
Visual Studio Code - Insiders
Version: 1.29.0-insider (system setup)
Commit: 4a29bd3731e40c07622bae0e9b0ac3b422b5672a
Date: 2018-10-25T05:48:41.485Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by mjbvz** [comment] 2018-10-29 19:03
Likely duplicate of https://github.com/Microsoft/TypeScript/issues/28149

Please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Closed** 2018-11-05 19:12 UTC
Labels: needs more info
