### ISSUE TITLE
Right order of keyboard shortcut

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#102637] opened 2020-07-15 20:44 UTC
Issue Type: <b>Bug</b>

When right click in html document, shows:
Format document (Shift+Alt+F)
The correct is:
Format document (Alt+Shift+F)

VS Code version: Code - Insiders 1.48.0-insider (cb31fc6ce2b4da3520392b622aa3ebc5b313533b, 2020-07-15T05:34:49.078Z)
OS version: Windows_NT x64 10.0.20161

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment] 2020-11-04 11:35
Duplicate of #62498

**Closed by alexdima** 2020-11-04 11:35 UTC
Labels: keybindings, menus
