### ISSUE TITLE
Issue Reporter: Support configuring data sent to extensions

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#46726] opened 2018-03-27 17:08 UTC
Continuation of https://github.com/Microsoft/vscode/issues/45673

Now that users can choose to file on extensions, extension authors should be able to specify additional data to include in the report. This could potentially include

- User settings
- `launch.json` information
- Metadata about the workspace (is it multiroot)
- Console errors
- Data specific to the extension

**Comment by Almenon** [comment] 2018-04-07 16:04
By default the extension log should definitley be included within the report.  Extension settings would also be very helpful.

**Comment by rkeithhill** [comment] 2018-07-08 16:50
To add to what @RMacfarlane says, the PowerShell extension would love to supply the `PowerShell version info` in this issue report.  We'd (and I suspect most extension authors) would like to see a list of all loaded extension versions.  There is sometimes "interface" between extensions and having this information can help determine if what a user is seeing might be a result of this.

Here is an example of the PowerShell version info and extension info we generate with our extension's bug report command:

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.137|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.137|
|BuildVersion|10.0.17134.137|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|code-settings-sync|Shan|2.9.2|
|cpptools|ms-vscode|0.17.6|
|csharp|ms-vscode|1.15.2|
|debugger-for-chrome|msjsdiag|4.7.0|
|EditorConfig|EditorConfig|0.12.4|
|githistory|donjayamanne|0.4.1|
|gitlens|eamodio|8.4.1|
|html-snippets|abusaidm|0.2.1|
|PowerShell|ms-vscode|1.7.0|
|sass-indented|robinbentley|1.4.9|
|theme-cobalt2|wesbos|2.1.6|
|tslint|eg2|1.0.33|
|vscode-eslint|dbaeumer|1.4.12|;

</details>

If we had this and there was a way to invoke the issue reporter programmatically, we would redirect bug report command to pop the issue reporter and probably, over time phase out our bug report command in favor of the built-in one.

**Comment by rkeithhill** [comment] 2018-07-08 16:54
Oh and we'd like to show them how to attach log files generated by the extension to the bug report e.g.:

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

**Comment by rkeithhill** [comment] 2018-07-08 16:57
> Extension settings would also be very helpful.

Yes!  But we would only need the non-default settings.

**Comment by bwateratmsft** [comment] 2020-11-19 19:17
The Docker extension along with several Azure extensions managed by @EricJizbaMSFT and @StephenWeatherford would really benefit from this as well.

**Comment by TylerLeonhardt** [comment] 2023-03-07 00:13
I'm thinking the best API for this kind of thing is a typical provider model:

```ts
interface IssueDataProvider {
    provideIssueData(): ProviderResult<string | MarkdownString>;
}

namespace env {
    export function registerIssueDataProvider(provider: IssueDataProvider): Disposable;
}
```

Reusing `env` seems reasonable since the environment could be important for the issue.

Also since `MarkdownString` has nice utilities for creating MarkdownStrings I think it's reasonable to include that in the result... though really at the end of the day we'll just be sending a string.

**Comment by gjsjohnmurray** [comment] 2023-03-07 06:46
Do you plan to make the Issue Reporter dialog give the user a preview of the data the extension wants to send? And/or an option to exclude it? When logged in at GitHub we only get to see issue contents after filing.

**Comment by TylerLeonhardt** [comment] 2023-03-07 15:35
> Do you plan to make the Issue Reporter dialog give the user a preview of the data the extension wants to send? And/or an option to exclude it?

Yes. Similar to when you open an issue on VS Code and it shows you the additional data that will be included in your issue... except probably more obvious since it's coming from a random extension instead of VS Code.

> When logged in at GitHub we only get to see issue contents after filing.

You have the ability to see all of it, today via the different "show more"s, just not in one big text area like you do on GitHub. I do want to have a preview button and that's https://github.com/microsoft/vscode/issues/117657

We did it the way that we did because there's a hard limit on number of characters that a browser can handle via a query parameter so if you're logged in we can simply use a POST to the issue API which will guarantee it's creation.

**Comment by bwateratmsft** [comment] 2023-03-07 15:47
Would some sort of state object be suitable, e.g., programmatically execute the "Report Issue..." command, with an object containing state that is subsequently passed into `provideIssueData()`. Primarily I'm thinking of passing along an error object, call stack, etc. from, e.g., an error toast, into the issue reporter.

**Comment by TylerLeonhardt** [comment] 2023-03-07 17:38
Yeah that's a good idea. I know we already have a command for launching the issue reporter with pre-filled data. I think it can probably be a bit more ergonomic.

**Comment by TylerLeonhardt** [comment] 2023-03-10 17:59
Some interesting data on how some extensions have implemented their own `Report Issue...` experience:

| Extension | Command name | Sample | Notes |
| --- | --- | --- | --- |
| Core | Help: Report Issue... | opens issue reporter | defaults to "Bug Report" |
| Core | Help: Report Performance Issue...  | opens issue reporter | defaults to "Performance Issue" |
| [Azure Account](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) | Azure Account: Report Issue... | [sample](https://github.com/microsoft/vscode-azure-account/issues/new?body=%0A%3C!--%20IMPORTANT%3A%20Please%20be%20sure%20to%20remove%20any%20private%20information%20before%20submitting.%20--%3E%0A%0ADoes%20this%20occur%20consistently%3F%20%3C!--%20TODO%3A%20Type%20Yes%20or%20No%20--%3E%0ARepro%20steps%3A%0A%3C!--%20TODO%3A%20Share%20the%20steps%20needed%20to%20reliably%20reproduce%20the%20problem.%20Please%20include%20actual%20and%20expected%20results.%20--%3E%0A%0A1.%0A2.%0A%0AVersion%3A%200.11.3%0AOS%3A%20darwin%0AOS%20Release%3A%2022.3.0%0AProduct%3A%20Visual%20Studio%20Code%20-%20Insiders%0AProduct%20Version%3A%201.77.0-insider%0ALanguage%3A%20en) | version info, os info, locale |
| [Codespaces](https://marketplace.visualstudio.com/items?itemName=GitHub.codespaces) | Codespaces: Report Issue | [sample](https://aka.ms/ghcs-support) | doesn't include any info. Goes to GitHub Support |
| [Codespaces](https://marketplace.visualstudio.com/items?itemName=GitHub.codespaces) | Codespaces: Send Feedback | [sample](https://github.com/community/community/discussions/categories/codespaces) | doesn't include any info. Goes to GitHub Discussions |
| [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) | Dev Containers: Report Issue... | opens issue reporter | issue reporter is completely blank |
| [Luna](https://marketplace.visualstudio.com/items?itemName=ms-vscode.luna-paint) | Luna > Help: Report Issue... | opens issue reporter | only extension is pre-filled |
| [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) | Pylance: Report Issue... | [sample](https://github.com/microsoft/pylance-release/issues/new?body=%0A%3C!--%0ARead%20the%20guidelines%20for%20%27Filing%20an%20issue%27.%0A%0A%27https://aka.ms/pylance-filing-an-issue%27%0A--%3E%0A%0A%3Ch3%3E%20Environment%20data%20%3C/h3%3E%0A%0A-%20%20%20Language%20Server%20version:%202023.3.11%0A-%20%20%20OS%20and%20version:%20darwin%20x64%0A-%20%20%20Python%20version%20(and%20distribution%20if%20applicable,%20e.g.%20Anaconda):%20%0A-%20%20%20python.analysis.indexing:%20true%0A-%20%20%20python.analysis.typeCheckingMode:%20basic%0A%0A%3Ch3%3E%20Code%20Snippet%20%3C/h3%3E%0A%0A%3C!--%0APlease%20provide%20a%20minimal,%20self-contained%20code%20snippet%20that%20reproduces%20the%20issue.%20If%20the%20code%20snippet%20uses%20any%20libraries,%20please%20specify%20the%20versions%20used.%0A%0ANote:%20If%20you%20think%20a%20GIF%20of%20what%20is%20happening%20would%20be%20helpful,%20consider%20tools%20like%20https://www.cockos.com/licecap/,%20https://github.com/phw/peek%20or%20https://www.screentogif.com/%20.%0A--%3E%0A%0A%60%60%60python%0AXXX%0A%60%60%60%0A%0A%3Ch3%3E%20Repro%20Steps%20%3C/h3%3E%0A%0A%3C!--%0AIf%20multiple%20steps%20are%20needed%20to%20reproduce%20the%20issue,%20please%20list%20the%20steps%20here.%20Delete%20this%20section%20if%20not%20needed.%0A--%3E%0A%0A1.%20XXX%0A%0A%3Ch3%3E%20Expected%20behavior%20%3C/h3%3E%0A%0AXXX%0A%0A%3Ch3%3E%20Actual%20behavior%20%3C/h3%3E%0A%0AXXX%0A%0A%3Ch3%3E%20Logs%20%3C/h3%3E%0A%0A%3C!--%0AEnable%20trace%20logging%20by%20adding%20%22python.analysis.logLevel%22:%20%22Trace%22%20to%20your%20settings.json%20configuration%20file.%0A%0AAdding%20this%20will%20cause%20a%20large%20amount%20of%20info%20to%20be%20printed%20to%20the%20Python%20output%20panel.%20This%20should%20not%20be%20left%20long%20term,%20as%20the%20performance%20impact%20of%20the%20logging%20is%20significant.%0A--%3E%0A%0A%60%60%60%0AXXX%0A%60%60%60%0A) | version info, os info, couple of setting values |
| [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) | Python: Report Issue... | opens issue reporter | template, python env info, couple of setting values |
| [Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) | Remote-SSH: Report Issue... | opens issue reporter | issue reporter is completely blank |
| [Remote Tunnels](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-tunnels) | Remote Tunnels: Report Issue... | opens issue reporter | issue reporter is completely blank |
| [PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell) | PowerShell: Upload Bug Report to GitHub | [sample](https://github.com/PowerShell/vscode-powershell/issues/new?body=Issue%20Description%0A=====%0A%0AI%20am%20experiencing%20a%20problem%20with...%0A%0AAttached%20Logs%0A=====%0A%0AFollow%20the%20instructions%20in%20the%20%5BREADME%5D(https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md)%20about%0Acapturing%20and%20sending%20logs.%0A%0AEnvironment%20Information%0A=====%0A%0AVisual%20Studio%20Code%0A-----%0A%0A%7C%20Name%20%7C%20Version%20%7C%0A%7C%20---%20%7C%20---%20%7C%0A%7C%20Operating%20System%20%7C%20Darwin%20x64%2022.3.0%20%7C%0A%7C%20VSCode%20%7C%201.77.0-insider%7C%0A%7C%20PowerShell%20Extension%20Version%20%7C%202023.2.1%20%7C%0A%0APowerShell%20Information%0A-----%0A%0A%7CName%7CValue%7C%0A%7C---%7C---%7C%0A%7CPSVersion%7C7.4.0-daily20230307.1%7C%0A%7CPSEdition%7CCore%7C%0A%7CGitCommitId%7C7.4.0-daily20230307.1%7C%0A%7COS%7CDarwin%2022.3.0%20Darwin%20Kernel%20Version%2022.3.0:%20Mon%20Jan%2030%2020:42:11%20PST%202023,%20root:xnu-8792.81.3~2/RELEASE_X86_64%7C%0A%7CPlatform%7CUnix%7C%0A%7CPSCompatibleVersions%7C1.0%202.0%203.0%204.0%205.0%205.1%206.0.0%206.1.0%206.2.0%207.0.0%207.1.0%207.2.0%207.3.0%207.4.0-daily20230307.1%7C%0A%7CPSRemotingProtocolVersion%7C2.3%7C%0A%7CSerializationVersion%7C1.1.0.1%7C%0A%7CWSManStackVersion%7C3.0%7C%0A%0A%0A%0AVisual%20Studio%20Code%20Extensions%0A-----%0A%0A%3Cdetails%3E%3Csummary%3EVisual%20Studio%20Code%20Extensions(Click%20to%20Expand)%3C/summary%3E%0A%0A%0A%7CExtension%7CAuthor%7CVersion%7C%0A%7C---%7C---%7C---%7C%0A%7Cazure-account%7Cms-vscode%7C0.11.3%7C%0A%7Cazure-repos%7Cms-vscode%7C0.29.2023030701%7C%0A%7Ccode-spell-checker%7Cstreetsidesoftware%7C2.19.0%7C%0A%7Ccodespaces%7CGitHub%7C1.13.10%7C%0A%7Ccopilot%7CGitHub%7C1.77.9225%7C%0A%7CEditorConfig%7CEditorConfig%7C0.16.4%7C%0A%7Cemojisense%7Cbierner%7C0.9.1%7C%0A%7Cesbuild-problem-matchers%7Cconnor4312%7C0.0.2%7C%0A%7Cgitlens%7Ceamodio%7C2023.3.704%7C%0A%7Cgremlins%7Cnhoizey%7C0.26.0%7C%0A%7Chandydandy-notebook%7Cjakearl%7C0.1.4%7C%0A%7Cindent-rainbow%7Coderwat%7C8.3.1%7C%0A%7Cisort%7Cms-python%7C2023.9.10591013%7C%0A%7Cjupyter%7Cms-toolsai%7C2023.3.1000681014%7C%0A%7Cjupyter-keymap%7Cms-toolsai%7C1.1.0%7C%0A%7Cjupyter-renderers%7Cms-toolsai%7C1.0.15%7C%0A%7Ckusto%7Cdonjayamanne%7C0.4.3%7C%0A%7Cluna-paint%7CTyriar%7C0.16.0%7C%0A%7Cmsft-todo-unofficial%7Ctylerleonhardt%7C0.0.17%7C%0A%7Cpowershell-preview%7Cms-vscode%7C2023.2.1%7C%0A%7Cprettier-vscode%7Cesbenp%7C9.10.4%7C%0A%7Cproject-manager%7Calefragnani%7C12.7.0%7C%0A%7Cpython%7Cms-python%7C2023.5.10661006%7C%0A%7Cremote-containers%7Cms-vscode-remote%7C0.283.0%7C%0A%7Cremote-explorer%7Cms-vscode%7C0.3.2023021509%7C%0A%7Cremote-repositories%7Cms-vscode%7C0.31.2023030701%7C%0A%7Cremote-server%7Cms-vscode%7C1.1.2023022709%7C%0A%7Cremote-ssh%7Cms-vscode-remote%7C0.99.2023030315%7C%0A%7Cremote-ssh-edit%7Cms-vscode-remote%7C0.84.0%7C%0A%7Cremotehub%7CGitHub%7C0.53.2023030701%7C%0A%7Cshell-runner-notebooks%7Ctylerleonhardt%7C0.0.2%7C%0A%7Ctemplate-string-converter%7Cmeganrogge%7C0.6.0%7C%0A%7Ctest-adapter-converter%7Cms-vscode%7C0.1.6%7C%0A%7Ctheme-panda%7Ctinkertrain%7C1.3.0%7C%0A%7Ctldraw-vscode%7Ctldraw-org%7C1.27.0%7C%0A%7Ctsl-problem-matcher%7Camodio%7C0.6.2%7C%0A%7Cvscode-ava-test-adapter%7Cgwenio%7C0.4.1%7C%0A%7Cvscode-commons%7Credhat%7C0.0.6%7C%0A%7Cvscode-eslint%7Cdbaeumer%7C2.4.0%7C%0A%7Cvscode-github-issue-notebooks%7Cms-vscode%7C0.0.128%7C%0A%7Cvscode-icons%7Cvscode-icons-team%7C12.2.0%7C%0A%7Cvscode-inline-values-powershell%7CTylerLeonhardt%7C0.0.7%7C%0A%7Cvscode-jupyter-cell-tags%7Cms-toolsai%7C0.1.6%7C%0A%7Cvscode-jupyter-docker-stack-connect%7Crebornix%7C0.0.2%7C%0A%7Cvscode-jupyter-slideshow%7Cms-toolsai%7C0.1.5%7C%0A%7Cvscode-language-pack-de%7CMS-CEINTL%7C1.76.2023030109%7C%0A%7Cvscode-language-pack-es%7CMS-CEINTL%7C1.76.2023030109%7C%0A%7Cvscode-language-pack-pt-BR%7CMS-CEINTL%7C1.76.2023030109%7C%0A%7Cvscode-mocha-test-adapter%7Chbenl%7C2.14.1%7C%0A%7Cvscode-postfix-ts%7Cipatalas%7C1.12.1%7C%0A%7Cvscode-pull-request-github%7CGitHub%7C0.61.2023030709%7C%0A%7Cvscode-pylance%7Cms-python%7C2023.3.11%7C%0A%7Cvscode-ruby%7Cwingrunr21%7C0.28.0%7C%0A%7Cvscode-selfhost-test-provider%7Cms-vscode%7C0.3.14%7C%0A%7Cvscode-terminalcommanddocs%7CTylerLeonhardt%7C0.0.2%7C%0A%7Cvscode-test-explorer%7Chbenl%7C2.21.1%7C%0A%7Cvscode-thunder-client%7Crangav%7C2.5.0%7C%0A%7Cvscode-xml%7Credhat%7C0.24.0%7C%0A%7Cvscode-yaml%7Credhat%7C1.11.0%7C;%0A%0A%3C/details%3E%0A%0A) | they include info but it gets lost due to new issue choose |
| [Project Manager]() | no command but Report Issue in a view | [sample](https://github.com/alefragnani/vscode-project-manager/issues/new/choose) | doesn't include any info |
| [Project Manager]() | no command but Provide Feedback in a view | [sample](https://twitter.com/intent/tweet?hashtags=project-manager&text=@code) | is a tweet |

For the remote extensions that open the issue reporter completely blank I believe it was a bug that I fixed a few days ago... they now should open with their extension pre-selected.

**Comment by TylerLeonhardt** [comment] 2023-03-10 18:39
Here's an iterative (hacked up) mockup of what the Issue Reporter could look like with the extension contributed data:
![image](https://user-images.githubusercontent.com/2644648/224394670-0b9ee8cb-7895-4ea4-82df-6c24ba3aa538.png)

words can change but the idea is that we widen the issue reporter to make way for a 2nd column being the data that the extension provides.

The current API proposal aligns with this model. The `vscode.openIssueReporter`, which allows you to specify [this](https://github.com/microsoft/vscode/blob/9fb5a524798fee34f66ae8dff9350b02e4630172/src/vs/workbench/contrib/issue/common/issue.contribution.ts#L53-L57):
```ts
interface OpenIssueReporterArgs {
	readonly extensionId?: string;
	readonly issueTitle?: string;
	readonly issueBody?: string;
}
```
would include an additional `extensionData` property or something that would allow for @bwateratmsft's ask to programmatically open the issue reporter with all this stuff in it. (in the future, proper API could wrap this command, but I'll leaving that out of scope for now since I have limited time)

Now I think these needs 2 additional things:

1. allowing an extension to control the Steps to Reproduce/title content so that extensions can make it easier for users to "file good steps" whatever that means for that extension. Requires more API... I'm thinking maybe an additional `IssueDataProvider#provideIssueTemplate(): ProviderResult<string | MarkdownString>` separate from gathering data so that the user can start filling in the template while the `provideIssueData` is finishing.
2. a good experience for extensions that don't use GitHub Issues (maybe they use GitLab, or even GitHub Discussions like Codespaces does) - I think this is all UI work in the issue reporter which I will mock up.

**Comment by bwateratmsft** [comment] 2023-03-10 18:53
That makes sense. For us, what we ultimately need is to be able to put data into the issue body--metadata like call stack, error, OS, extension-specific info, etc.--while still _requiring_ users to type something as well. We receive a considerable volume of issues where the user enters something into the title, but nothing in the details or repro steps, usually resulting in unactionable issues.

**Comment by TylerLeonhardt** [comment] 2023-03-10 20:30
So to address number 2, I was also thinking about GitHub Issue Forms. Here's what that could look like:
![image](https://user-images.githubusercontent.com/2644648/224421557-a358edcb-d85a-41c0-af9c-d542356b5cdd.png)
(again, hacked up)

In this case, maybe we could do something like this:
```ts
interface IssueUrlProvider {
    resolveIssueUrl(): ProviderResult<Url>;
}
```

Where this provider would gather up any info from the system and then query parameter-itize that information however it wants.

We would then give the user the ability to edit each query parameter to remove any sensitive stuff before the issue actually opens on the repo.

If we are opening a URL not on github.com, then we could also show the hostname in another field.

This would help for:
* Users of GitHub Issue Forms
* Users of non-GitHub sources

**Comment by TylerLeonhardt** [comment] 2023-03-10 21:03
I think that there is something to be said about both options.

```ts
interface IssueDataProvider {
    provideIssueTemplate(): ProviderResult<string | MarkdownString>;
    provideIssueData(): ProviderResult<string | MarkdownString>;
}
```

Pros:
* simplest to implement - no URL parsing or encoding. VS Code API takes care of that.
* can use the GitHub API to create the issue so we won't ever hit browser URL length limitations (which we have hit in the past... GH has an 8k limit)

Cons:
* Not flexible - only supports regular GitHub Markdown Issues

```ts
interface IssueUrlProvider {
    provideIssueUrl(): ProviderResult<Url>;
}
```

Pros:
* Ultimate flexibility to support any issue endpoint (be it GitHub or not)

Cons:
* harder to implement - extension must do URL parsing and encoding.
* Opening in a browser using query parameters has its limit (GitHub's is 8000 characters)

Ultimately I think "do both" is probably the right solution here because:
* the former allows existing extensions to continue leverage normal GitHub Issues and easily onboard.
* the ladder allows those extensions that aren't on GitHub or those that want to use GitHub _as_ their issue reporter to do so (treating the Issue Reporter in VS Code as a user 'Are you sure you want to send this info there?')

**Comment by brettcannon** [comment] 2023-03-13 17:50
Is there any way to make the data like the "Include" options that come baked in? Basically be checkboxes with the "show" link to show what's being included? I'm wondering if that might help  make all the data less ominous to users?

And I do appreciate manually sending in the template if you go the GitHub issues direction as we purposefully turn off the ability to open a new issue to direct users through our "Report Issue" command 😁.

Lastly, other than some select settings outside of what our extension provides, we include every setting that is set to a non-default value. We also anonymize any setting that is free-form in case there's PII, but otherwise include any setting the user specified. Not sure if it would make sense to do that automatically since the setting contributions are known to Python and the type details for those settings are also known.

**Comment by TylerLeonhardt** [comment] 2023-03-13 19:29
> Is there any way to make the data like the "Include" options that come baked in? Basically be checkboxes with the "show" link to show what's being included? I'm wondering if that might help make all the data less ominous to users?

I opted against this with the concern that since we don't own every extension in the marketplace, we can't be sure that their data capturing processes are up to par. So I aired on the side of caution and made the extension issue data front and center. I understand that this might increase the likelihood of an empty issue (the user just deletes the content) but I think that this cohort of "security cautious but not willing to scan data manually" is small compared to others.

> Lastly, other than some select settings outside of what our extension provides, we include every setting that is set to a non-default value. We also anonymize any setting that is free-form in case there's PII, but otherwise include any setting the user specified. Not sure if it would make sense to do that automatically since the setting contributions are known to Python and the type details for those settings are also known.

I think this is a good idea but it would make a good addition to this proposal rather than a replacement. I think there is still a need for data only available at runtime.

**Comment by eleanorjboyd** [comment] 2023-03-13 20:27
Excited about the proposal! @TylerLeonhardt I have a [github issue form for remote-ssh bugs](https://github.com/microsoft/vscode-remote-release/issues/new?assignees=eleanorjboyd&labels=ssh&template=a_remote_ssh_bug_form.yml&title=%5BRemote
-SSH+Bug%5D%3A+) which I would also love to port over to this new issue reporter. From what I can see, everything you have planned fits with the features I have for my issue form. The first comment I have is I am not sure if this is already planned but I have really appreciated having long items in dropdowns (this is done on the python report issue command so I assume that is done everywhere) but just wanted to bring it up as it does help keep issues visually cleaner even when we are gathering extensive logs.
<img width="871" alt="Screenshot 2023-03-13 at 1 24 25 PM" src="https://user-images.githubusercontent.com/26030610/224823991-f54cd30a-f60a-4811-a37b-7a5998126feb.png">

Secondly, will the issue reporter allow assigning tags or assignees? Since remote-ssh has all bug reports go through the remote-release repo I have my bug report form assigning it to me and adding "ssh" as a label for organizational purposes.

**Comment by TylerLeonhardt** [comment] 2023-03-13 21:08
@eleanorjboyd 

> I have really appreciated having long items in dropdowns (this is done on the python report issue command so I assume that is done everywhere) but just wanted to bring it up as it does help keep issues visually cleaner even when we are gathering extensive logs.

yeah we would collapse it in a dropdown on the issue for sure.

> Secondly, will the issue reporter allow assigning tags or assignees?

Users who aren't in the GH Org can't assign people or add tags so this doesn't seem useful to support. Instead, you could use an Issue Form Template which allows for a hardcoded list of assignees & labels.

**Comment by AnthonyLeonardoGracio** [comment] 2024-05-13 10:09
Hello! 

Is this already available through the VS Code API? I am not very familiar on how new APIs get merged, but I wanted to use this new capability in our own extension, so I was wondering what should I need to do in order to have access to this new API: if someone has a working example of a customized issue reporter, that would be very useful!

Regards,

**Comment by justschen** [comment] 2024-05-13 15:20
this is available ATM! extensions can contribute a command which will be triggered in the reporter when selecting their extension as long as they follow this menu contribution point:

``` json
"commands": [
    {
        "command": "extension.myCommand",
        "title": "Report Issue"
    }
],
    "menus": {
        "issue/reporter": [
            {
                "command": "extension.myCommand"
            }
        ]
    }
```

`extension.myCommand` will then run an `workbench.action.openIssueReporter` command with any information they want 👍 

check out https://code.visualstudio.com/updates/v1_87#_contributing-additional-data-in-issue-reporter for additional details.

here is also our internal testing item which has some additional instructions https://github.com/microsoft/vscode/issues/203094

**Closed by justschen** 2024-05-13 15:20 UTC
Labels: feature-request, on-testplan, issue-reporter, api-proposal
