### ISSUE TITLE
Peek references is currently scrolling to the wrong position

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#207879] opened 2024-03-15 19:44 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a code file (I'm using TypeScript) with a reference to a function defined at least 20-30 lines down in some other file.
2. Place the cursor on the reference and press shift+F12.
3. The peek references window displays with the referenced line appearing 5 lines below the visible scroll area of the peek code view.

I've tested with and without extensions loaded, and on two different projects - one which is a multiroot workspace and one which is not.

https://github.com/microsoft/vscode/assets/298883/da83b89a-3680-4b76-877a-6e32fddbf3cb

**Comment by axefrog** [comment] 2024-04-01 21:36
I guess everyone's on holiday... :-/

**Comment by axefrog** [comment] 2024-04-01 21:37
@jrieken Not sure if you missed this one? I can see that at least one other person is experiencing this too.

**Comment by jrieken** [comment] 2024-04-02 07:25
This seems correct, the first reference of `isFunction` is the import and that's shown when selecting the entry.

**Comment by axefrog** [comment] 2024-04-02 20:53
> This seems correct, the first reference of `isFunction` is the import and that's shown when selecting the entry.

@jrieken You didn't look properly. Maybe my video was unclear. If so, I apologise. I've made another video -- see below. The reference is always 5 lines _below_ the end of the scroll container. Yes, naturally if it's the first few lines of the document, the problem doesn't occur, because it would be impossible for those first few lines to be scrolled down below the bottom of the scroll container.

https://github.com/microsoft/vscode/assets/298883/fc5c68f4-c009-45f0-aa01-5ffd86ade164

**Comment by axefrog** [comment] 2024-04-04 18:06
@jrieken Please reopen this. I took the time to report an issue; it is discouraging and demotivating to take the time to report issues if they're going to be dismissed for invalid reasons and closed before even asking a followup question.

**Comment by jrieken** [comment] 2024-04-05 07:11
@axefrog please take a time to file a clean issue with precise minimal steps and a copy-paste friendly source code sample. A record is not that, it is ambiguous and painful to work with

**Comment by axefrog** [comment] 2024-04-05 17:38
> @axefrog please take a time to file a clean issue with precise minimal steps and a copy-paste friendly source code sample. A recording is not that, it is ambiguous and painful to work with

The issue I reported is a general UX issue that is applicable to any reference in any code. Shift + F12. Peek references. The scroll window is positioned incorrectly. I don't understand the pushback I'm getting.

**Comment by axefrog** [comment] 2024-04-05 17:39
@jrieken The issue I reported is a general UX issue that is applicable to any reference in any code. Shift + F12. Peek references. The scroll window is positioned incorrectly. I don't understand the pushback I'm getting.

**Comment by axefrog** [comment] 2024-04-05 22:38
@jrieken So I will infer from this that this is not an issue you're experiencing either in any multiroot workspaces or single-folder projects that you currently work on. As I mentioned earlier, the issue occurs for me in both kinds of environments, and happens even when I reload with extensions disabled. And in every case where the reference in the client area of the peek view appears in a file that is at least 21 lines in length, the reference appears exactly 5 lines _after_ the last line in the visible part of the scroll area (my figure of 21 refers to there being 16 lines in the peek view scroll area, plus 5 lines which is the offset from the end of the scroll area).

I'll try:

1. Creating a new profile and a new project to test with
2. Sizing the window up and down and trying with different desktop positions and so forth
3. Triple-checking everything with Canary

**Comment by axefrog** [comment] 2024-04-05 22:58
@jrieken I found the issue. In settings I have:

```json
{
  "editor.stickyScroll.maxLineCount": 20,
}
```

Any high value for that setting seems to mess up the scroll position. Do you want me to file a separate issue, or is this one okay?

**Comment by axefrog** [comment] 2024-05-10 03:47
@jrieken Do you want me to file a separate issue, or is this one okay?

**Comment by aiday-mar** [comment] 2024-05-13 09:40
Hi @axefrog thank you for narrowing down the issue. What is likely happening is that the editor is adjusting the vertical scroll position in order to avoid the line being hidden by the sticky scroll which is enabled in the peak view. I suggest to fix this, is to disable the sticky scroll in the peek view editor, it does not add much value there.

**Comment by axefrog** [comment] 2024-05-14 00:02
@aiday-mar Yes I started doing that back on April 6 when I discovered the issue. Nevertheless, it seems relevant for the VSCode dev team to know that their sticky scrolling feature breaks the peek references feature when configured for more than 2-3 levels of sticky indentation.

**Comment by aiday-mar** [comment] 2024-05-14 05:55
Yes so we can make the fix on our side, to permanently disable the sticky scroll within the peak view.

**Comment by aiday-mar** [comment] 2024-05-15 08:54
Alternatively I'll explore predicting the number of lines that will be shown on cursor move and adjusting the scroll position only if strictly needed. There is an issue here discussing this https://github.com/microsoft/vscode/issues/205918

**Comment by aiday-mar** [comment] 2024-12-12 16:21
Duplicate of https://github.com/microsoft/vscode/issues/227750

**Closed by aiday-mar** 2024-12-12 16:21 UTC
Labels: bug, editor-sticky-scroll
