### ISSUE TITLE
Improve search export format

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#68877] opened 2019-02-17 18:21 UTC
The `Copy All` action in the search pane is awesome, but the used format is not great.

1. Paths are not clickable, so navigating to them is a bit of a nightmare. just prefixing (and escaping, I guess) those paths with `file://` would make them clickable:

<img width="681" alt="screen shot 2019-02-17 at 19 14 40" src="https://user-images.githubusercontent.com/1812093/52917154-4e5c8b00-32e8-11e9-9a63-dba36785b41c.png">

2. Line ranges aren't clickable either. I'm not sure if there are APIs for making arbitrary text point to somewhere yet, but in the meantime maybe we could add another special clickable url for each match:

<img width="870" alt="screen shot 2019-02-17 at 19 17 35" src="https://user-images.githubusercontent.com/1812093/52917189-b4491280-32e8-11e9-8b81-0f5c38383e29.png">

It looks ugly, but it's way more useful.

3. Without syntax highlighting the whole document is kind of hard to read. At least some syntax highlighting for distinguishing between paths, ranges and code snippets would be nice. Ideally those code snippets should also get proper language-and-context-specific syntax highlight, but that sounds like a nightmare to implement.

**Comment by roblourens** [comment] 2019-02-17 20:41
I think https://github.com/Microsoft/vscode/issues/23931 is what you really want 😁 

What if I included a grammar that you can enable manually? e.g.

- Copy search results
- Paste into editor
- Run "Change Language Mode" or click on "Plain Text" in the status bar
- Select "Search results"
- See syntax-highlighted results with clickable links/ranges

Would that be useful and worth the effort of changing the language mode?

**Comment by fabiospampinato** [comment] 2019-02-17 20:59
> I think #23931 is what you really want 😁

Maybe 🤔 If those results would be searchable then yes, but if it would be implemented in a way that basically only enables performing multiple searches and retaining the results then no, because I wouldn't be able to perform a search inside the results.

> Would that be useful and worth the effort of changing the language mode?

Yes, it would be worth the effort for me. But I would probably take the opposite route: rather than letting me copy the results and then manually highlighting them I'd add an option for opening the results with the proper syntax highlight already, then if I only need the results in my clipboard I can copy them manually.

Perhaps both actions could be displayed.

**Comment by roblourens** [comment] 2019-02-17 23:16
This could be kind of cool. What do you think of this? The command could have a keyboard shortcut.

![feb-17-2019 15-15-54](https://user-images.githubusercontent.com/323878/52920966-f9f4e380-32c6-11e9-818e-a84aeb00b849.gif)

**Comment by fabiospampinato** [comment] 2019-02-17 23:32
@roblourens that was fast 😄 I like it a lot! I see ranges are underlined, so are they clickable too? If they are maybe you might want to do the same with the file paths and remove the `file://` prefix 🤔 

Other than that maybe a few improvements could be:

- Add a proper icon for the "Search Results" language.
- Use a more useful title for the editor, like `Search Results` or `Search Results: {query}` or something.
- Some people, especially those coming from Sublime and requesting #23931, might want to see some metadata inside the results too, Sublime writes this before the results: `Searching 0 files for "asd" (regex, case sensitive)`, something similar could be useful I guess.
- I would experiment with tweaking the color scheme a bit, those file paths are a bit difficult to read now, maybe if they were displayed in cyan the whole thing would look better. I'm also not sure if the colon after the range should be the same color as the range 🤔 

Well done!

**Comment by richtr** [comment] 2019-02-22 10:42
@roblourens [wrote](https://github.com/Microsoft/vscode/issues/68877#issuecomment-464506171):

> I think #23931 is what you really want 😁
> 
> What if I included a grammar that you can enable manually? e.g.
> 
> * Copy search results
> * Paste into editor
> * Run "Change Language Mode" or click on "Plain Text" in the status bar
> * Select "Search results"
> * See syntax-highlighted results with clickable links/ranges
> 

Regarding #23931 and the steps above, why not just add a `search.resultsLocation` param and leave `"search.location` as-is?

`search.resultsLocation` would take one of the following arguments: `same`, `tab`, `newtab`.

* `same` [default] - show search results output in the same location as `search.location`. Current search functionality would remain unchanged.
* `tab` - always drop search results in to a same tab. i.e. when a new search is made, replace the contents of a single "Search Results" tab with the new search results automatically.
* `newtab` - always drop search results in to a **new** tab. i.e. existing "Search Results" tab are not overwritten.

This approach would have additional benefits too:

* if `search.location === panel` and `search.resultsLocation === [tab|newtab]` then the panel height would be adjusted to not include the results location window height (leaving more space for Search Results tabs to display).
* in any other mode panel height and functionality remains unchanged from today.

**Comment by roblourens** [comment] 2019-02-22 18:36
@richtr A "real" fix for this is on the roadmap: https://github.com/Microsoft/vscode/wiki/Roadmap#workbench and tracked in #23931. It will take a lot of thought to make it a good experience. My experiment above is just thinking about how we could support this sort of thing without having to make any changes in vscode yet.

**Comment by fabiospampinato** [comment] 2019-03-11 21:11
It looks like somebody had the same idea: https://marketplace.visualstudio.com/items?itemName=travisthieman.better-search

**Comment by roblourens** [comment] 2019-10-09 22:30
I will close this as a dupe of https://github.com/microsoft/vscode/issues/23931, they go together

**Closed by roblourens** 2019-10-09 22:30 UTC
Labels: feature-request, search
