### ISSUE TITLE
Integrated Terminal fails on Bash on Ubuntu on Windows (pre-release)

### ISSUE THREAD

**Issue by mike-morrison** [Microsoft/vscode#8969] opened 2016-07-08 18:56 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (4c0676ab472a92f5269ac4995cdc81db8bc94896, 2016-07-08T15:19:23.853Z)
- OS Version: Windows_NT ia32 10.0.14371

I mainly wanted to get this documented, this may not be a supported scenario, but it is one I would like to request as an enhancement if its not.  I understand that Bash on Windows is pre-release.  Not expecting miracles, just wanted to get it on your radar.  This requires a machine in the Windows Insider program to test.

#### Steps to Reproduce:

1. Open the integrated terminal
2. Type "bash"
3. Type "1234567890"
4. Hit backspace 10 times

#### Expected Results:

All characters are deleted

#### Actual Results

All characters are not deleted, and cursor sometimes "jumps around" on the line being deleted.

**Comment by Tyriar** [comment] 2016-07-08 18:58
Duplicate of 7345

**Closed by Tyriar** 2016-07-08 18:58 UTC
