### ISSUE TITLE
Markdown smart paste not working when front matter exists

### ISSUE THREAD

**Issue by Alecton4** [microsoft/vscode#211060] opened 2024-04-23 09:31 UTC
Does this issue occur when all extensions are disabled?: Yes

Environment:

```text
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.7-1-default
```

Steps to Reproduce:

1. In settings: `"markdown.editor.pasteUrlAsFormattedLink.enabled": "smart",`
2. Create a new blank markdown file and paste a URL. Smart paste works.
3. Add the following front matter to the file:
   ```markdown
   ---
   ---
   ```
4. Paste a URL, smart paste will not work.

**Comment by mjbvz** [comment] 2024-04-23 17:44
Search "front matter": It's the first closed issue

Duplicate of #209267

**Closed by mjbvz** 2024-04-23 17:44 UTC
