### ISSUE TITLE
Other files wrongly shown in search within single root workspace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83298] opened 2019-10-25 11:22 UTC
Not sure what's happening here, I'm in a single-root WSL1 remote workspace with just xterm.js opened but search is presenting "Other files" for files within the folder:

![image](https://user-images.githubusercontent.com/2193314/67567507-d9471e00-f6de-11e9-8aa2-8af88bdd1603.png)

Version: 1.40.0-insider (user setup)
Commit: 85ebb0d0b97817c8ad91f90d1b955655056ef7b3
Date: 2019-10-25T08:51:24.579Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment] 2019-10-27 20:25
Is there anything in "files to include"?

![image](https://user-images.githubusercontent.com/323878/67641149-300a4e80-f8bd-11e9-96ea-f8d42090bcf9.png)

**Comment by roblourens** [comment] 2019-10-28 00:36
Nvm I am seeing this all over the place in some remote windows randomly and I don't think it's search specific, @isidorn 

![image](https://user-images.githubusercontent.com/323878/67644628-4fff3980-f8e0-11e9-8a9f-823f9b72e60b.png)

**Comment by roblourens** [comment] 2019-10-28 00:37
Or failing to dedupe these results, if I toString the 2 URIs, one has `+` in the authority and one is escaped.

![image](https://user-images.githubusercontent.com/323878/67644641-6f966200-f8e0-11e9-8974-f87eca8507b3.png)

I guess that could have come from search but nothing has changed.

**Comment by roblourens** [comment] 2019-10-28 00:52
What I see is that the workspace URI has `%2B` but the files have `+`, what would cause that difference? @jrieken ?

![image](https://user-images.githubusercontent.com/323878/67644845-27783f00-f8e2-11e9-9750-eed7ea4c86d3.png)

In windows that work, the workspace URI has `+`

**Comment by jrieken** [comment] 2019-10-28 08:26
I did change (fix) how Uris are externalised and the `+` character one of the character that don't get encoded anymore. @roblourens where to these uris come from? are they cached on disk and then read and used as strings (instead of URI objects)?

**Comment by jrieken** [comment] 2019-10-28 15:26
Can you add steps to reproduce https://github.com/microsoft/vscode/issues/83298#issue-512460443, https://github.com/microsoft/vscode/issues/83298#issuecomment-546752249, and https://github.com/microsoft/vscode/issues/83298#issuecomment-546752364. For the latter I understand how it could have been read from storage, for the 2nd I don't even know what's happening, and for the 1st I also don't know how to get there...

**Comment by roblourens** [comment] 2019-10-28 17:28
I think the issue is with folder that were previously persisted to Recently Opened. Now I can repro it easily

- Use Recently Opened to pick a folder that was added to that last some time ago (before you made that change probably)
- I see absolute paths everywhere - if I open a folder from the explorer, or do a text search, or use quick open

If I open a folder from "Open Folder" then I don't see it.

**Comment by jrieken** [comment] 2019-10-29 07:41
I will push a change to make sure that we encode the + to %2B. That is the easiest fix now. @aeschli, @bpasero: unsure who is owning the recent file list but it should re-create URI instances from their externalised string form otherwise we are forever stuck with these issues

**Comment by jrieken** [comment] 2019-10-29 07:42
Also note that after fixing this there will still be duplicates because the string-forms are used and affected insider users will have to remove those entries from history.

**Comment by bpasero** [comment] 2019-10-29 08:00
> unsure who is owning the recent file list but it should re-create URI instances from their externalised string form otherwise we are forever stuck with these issues

@jrieken can you file an issue about this for Martin so that we do not forget

**Comment by jrieken** [comment] 2019-10-29 08:04
I have actually checked with the history service and it seems to be doing the right things - which is using URI.parse. I will continue to drill into this, it might happen when calling URI.revive because that persists the externalised form...

**Comment by jrieken** [comment] 2019-10-29 08:48
@roblourens Can you share your `~/Application Support/Code - Insiders/storage.json` with me?

**Comment by roblourens** [comment] 2019-10-29 15:40
[storage.json.txt](https://github.com/microsoft/vscode/files/3784429/storage.json.txt)

**Comment by jrieken** [comment] 2019-10-30 09:58
fixed via 58479e80ab899402283b522da173c34867d7c78f

**Closed** 2019-10-30 09:59 UTC
Labels: bug, uri

**Comment by jrieken** [comment] 2019-10-30 11:17
trying to go forward with this: https://github.com/microsoft/vscode/issues/83645
