### ISSUE TITLE
"code . -r" refreshes all open windows, not only one

### ISSUE THREAD

**Issue by balexandre** [microsoft/vscode#126041] opened 2021-06-11 12:13 UTC
Does this issue occur when all extensions are disabled?: Yes (but Remote WSL is needed)

- VS Code Version: 1.57.0
- OS Version: Windows_NT x64 10.0.19043
- **Only under WSL**

### Steps to Reproduce:

1. open 2 or more VSCode windows (under WSL)
2. in one of the windows, open the terminal and run `code . -r`
3. all windows refresh, not only the one we request a refresh

### a simple demo

![1p9bfHV8D9](https://user-images.githubusercontent.com/45473/121792167-de2d4e00-cbf1-11eb-829c-56c456e57ec4.gif)

**Comment by aeschli** [comment] 2021-06-14 09:16
duplicate of https://github.com/microsoft/vscode/issues/121926

**Closed by aeschli** 2021-06-14 09:16 UTC
Labels: WSL, bug, new release, remote, workbench-cli
