### ISSUE TITLE
Untitled editor titles with special first line

### ISSUE THREAD

**Issue by redcoreit** [microsoft/vscode#90685] opened 2020-02-14 11:05 UTC
- VSCode Version: 1.42.1
- OS Version: 1909

Steps to Reproduce:

1. Open new VSCode instance
2. Open new file (with plain text language mode)
3. Write this in the first line `// a:`
4. Hit CTRL+S

Error: `Failed to save '// a:': [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
`

**Comment by IllusionMH** [comment] 2020-02-14 11:10
Looks like duplicate of #90433 but after some event problem was gone.

I would guess that you can try to close/reopen VS Code and/or reboot PC.

Next step - check if it's reproducible with all extensions disabled if you have autoformat on save enabled.
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`


/cc @bpasero

**Comment by redcoreit** [comment] 2020-02-14 11:29
It is a duplicate indeed, I wasn't able to find, sry.
FYI `Reload Window With Extensions Disabled` does not solving the problem.

Thank you for your help.

**Closed** 2020-02-14 11:29 UTC

**Comment by IllusionMH** [comment] 2020-02-14 11:37
> FYI Reload Window With Extensions Disabled does not solving the problem.

Then my assumption that extensions somehow receive wrong filename is wrong.

There should be a fix in Insiders builds so you can try those if this is critical for you. https://code.visualstudio.com/insiders/
