### ISSUE TITLE
Recent regression: `terminalIsOpen` when clause context breaks after opening and killing a terminal

### ISSUE THREAD

**Issue by aminomancer** [microsoft/vscode#211877] opened 2024-05-02 20:27 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045

### Steps to Reproduce:

1. Make keybindings like this (you need the second one to disable the system binding):
	```json
	{
	  "key": "ctrl+`",
	  "command": "workbench.action.terminal.newWithProfile",
	  "args": {
	    "profileName": "SomeProfileName"
	  },
	  "when": "!terminalIsOpen"
	},
	{
	  "key": "ctrl+`",
	  "command": "-workbench.action.terminal.toggleTerminal",
	  "when": "!terminalIsOpen"
	}
	```
2. Use the keybinding so that your custom terminal profile opens, then kill the active terminal using the kill button.
3. Use the keybinding again.

### Expected:

The keybinding continues to work while a terminal is not open.

### Actual:

The keybinding ceases to work after the first terminal has been opened. It seems that `terminalIsOpen` is only true if a terminal has never been opened. Or perhaps vscode fails to kill terminals. But I don't think that's the case, because the terminal I'm using (bash.exe) disappears from the task manager when I use the kill button.

I also tried using `terminalHasBeenCreated`, but this does not seem to work at all. It is never false.

**Comment by aminomancer** [comment] 2024-05-02 20:42
Using `workbench.action.inspectContextKeys` I found that the `terminalCount` flag is 1, even with no terminals open.

**Comment by meganrogge** [comment] 2024-05-02 21:42
>  It seems that terminalIsOpen is only true if a terminal has never been opened.

thanks for the report, if your statement above is true, I'd expect `terminalsOpen:false` after following these steps. But for me, it is true. 

1. create a terminal
2. kill it
3. create a terminal

**Comment by meganrogge** [comment] 2024-05-02 21:47
that keybinding works for me. i'd suggest using the command: `Developer: Toggle Keyboard Shortcuts Troubleshooting` to see what your issue could be

https://github.com/microsoft/vscode/assets/29464607/a84f6bb0-b6f9-4c0b-80f4-39179a1f7c81

**Comment by aminomancer** [comment] 2024-05-02 22:27
[vscodeTerminalIssue.webm](https://github.com/microsoft/vscode/assets/33384265/7e7d0cba-b45e-4b9a-a55d-152505d67c07)

**Comment by aminomancer** [comment] 2024-05-05 04:25
The bug is still closed despite the labels.

**Comment by manav014** [comment] 2024-07-13 00:55
I would like to work on this. Can anyone please assign this to me?

**Comment by manav014** [comment] 2024-07-13 18:00
I tried reproduce it as mentioned in https://github.com/microsoft/vscode/issues/211877#issuecomment-2091832186 . But it was working fine for me as well.

**Closed** 2024-07-15 14:28 UTC
Labels: bug, help wanted, terminal
