### ISSUE TITLE
Rightclick menu of commit msg textbox has wrong depth

### ISSUE THREAD

**Issue by darkvertex** [microsoft/vscode#114976] opened 2021-01-26 05:34 UTC
Issue Type: <b>Bug</b>

1. Rightclick on "Message" box in the Git panel.
2. Realize that the rightclick menu that came up is limited to the proportions of that side panel, even if the items are bigger than it. Screenshot below of what it looks like for me:

![image](https://user-images.githubusercontent.com/941331/105804570-1ea36c80-5f6e-11eb-8ec8-2f2bca3ea5bb.png)
(As you can see, the scrollbar from the Git panel is on top of the rightclick menu, which should  have rendered on top of everything, like most rightclick menus.)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (0.70GB free)|
|Process Argv|--crash-reporter-id e6ad97a0-e685-4833-aa9a-231f33d46067|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (120)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|12.1.4
vscode-usda-syntax|ani|0.2.0
vscode-color|ans|0.4.5
vscode-tidyhtml|anw|1.10.0
gitstash|art|3.3.1
atlascode|atl|2.8.5
QML|bbe|1.0.0
unique-lines|bib|1.0.0
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
mermaid-markdown-syntax-highlighting|bpr|1.2.0
sublime-duplicate-text|bri|0.2.5
vscode-toggle-quotes|Bri|0.3.3
path-intellisense|chr|2.3.0
coddx-alpha|cod|0.2.28
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
disableligatures|Coe|0.0.10
systemd-unit-file|coo|1.0.6
vscode-svgviewer|css|2.0.0
macros|ctf|0.0.4
transformer|dak|1.11.0
vscode-markdownlint|Dav|0.38.0
shebang-language-associator|dav|1.1.1
make-hidden|dev|3.0.3
githistory|don|0.6.14
gitlens|eam|11.1.3
simple-alignment|ear|1.0.0
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
LogFileHighlighter|emi|2.11.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.8.0
hadolint|exi|0.3.0
vscode-commands|fab|1.4.1
vscode-diff|fab|1.4.0
vscode-pyvmmonitor|fab|0.0.3
shell-format|fox|7.0.1
go|gol|0.21.1
gc-excelviewer|Gra|3.0.40
vscode-commandbar|gsp|0.3.1
vscode-test-explorer|hbe|2.19.5
live-html-previewer|hdg|0.3.0
asciidecorator|hel|0.2.0
vscode-ungit|Hir|2.2.3
rest-client|hum|0.24.4
output-colorizer|IBM|0.1.2
plantuml|jeb|2.14.1
better-dockerfile-syntax|jef|1.0.2
presentationmode|jsp|1.1.5
rpm-spec|Lau|0.3.1
pomodoro|lky|1.1.3
pop-n-lock-theme-vscode|Lux|3.31.0
code-groovy|mar|0.1.2
rainbow-csv|mec|1.8.0
vex|mel|0.5.2
git-graph|mhu|1.28.0
vscode-checkpoints|mic|1.3.1
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
prettify-json|moh|0.0.3
quicksnippet|mou|0.0.1
reminders|mrd|1.1.2
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.3484
debugger-for-chrome|msj|4.12.11
vscode-sanddance|msr|3.1.1
highlight-dodgy-characters|nac|1.0.0
autodocstring|njp|0.5.4
hide-gitignored|npx|1.1.0
indent-rainbow|ode|7.5.0
emoji|Per|0.0.3
material-icon-theme|PKi|4.5.0
gitlink|qez|0.5.1
quicktype|qui|12.0.46
todo-txt|rar|0.0.5
vscode-xml|red|0.14.0
vscode-yaml|red|0.14.0
synthwave-vscode|Rob|0.1.8
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
vscode-coverage-gutters|rya|2.6.0
partial-diff|ryu|1.4.1
jinjahtml|sam|0.16.0
blockalign|San|0.6.0
todotasks|san|0.5.0
mel|sat|0.1.2
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
shader|sle|1.1.4
music-time|sof|2.1.0
swdc-vscode|sof|2.4.2
vscode-smoothtype|spi|1.2.0
guides|spy|0.9.3
dot|Ste|0.0.1
graphviz-interactive-preview|tin|0.0.9
cmake|twx|0.0.17
luna-paint|Tyr|0.1.2
sort-lines|Tyr|1.9.0
alphabetical-sorter|ue|2.0.1
errorlens|use|3.2.4
snippet|vsc|0.8.1
vscode-wakatime|Wak|5.0.0
change-case|wma|1.0.0
sublime-commands|Zar|0.1.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspyt653:30244269
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by yume-chan** [comment] 2021-01-26 17:15
Duplicate of #113866

**Closed** 2021-01-26 20:22 UTC
Labels: *duplicate
