### ISSUE TITLE
Integrated terminal is restored with wrong shell

### ISSUE THREAD

**Issue by alexreg** [microsoft/vscode#132312] opened 2021-09-04 00:49 UTC
Issue Type: <b>Bug</b>

1. Use following settings for integrated terminal (on macOS).
```json
"terminal.integrated.profiles.osx": {
	"bash": {
		"path": [
			"/usr/local/bin/bash",
			"bash",
		],
		"icon": "terminal-bash",
	},
},
"terminal.integrated.defaultProfile.osx": "bash",
```
2. Open a workspace.
3. Open two integrated terminals using the (default) bash profile. This should work fine, i.e., the shell should be `/usr/local/bin/bash`.
4. Quit VS Code normally.
5. Restart VS code.
6. Observe that only one of the two integrated terminals is restored, and that the shell for this terminal is in fact the default for the current user according to the system, which is `/bin/bash` in this case, not `/usr/local/bin/bash`, which it should be.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 28, 34|
|Memory (System)|32.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id 15d3308c-caf5-4a84-98a0-ee5f295bcc42|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
spellright|ban|3.0.60
better-toml|bun|0.3.2
cake-vscode|cak|1.0.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.18
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
shell-format|fox|7.1.0
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
code-eol|jef|1.0.11
svg|joc|1.4.9
swift|Kas|0.2.0
bash-ide-vscode|mad|1.11.0
cortex-debug|mar|0.4.2
rust-analyzer|mat|0.4.0-dev
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
HTMLHint|mka|0.10.0
hg|mrc|1.7.1
vscode-autoprefixer|mrm|3.0.1
vscode-postcss-sorting|mrm|3.0.1
vscode-stylefmt|mrm|2.6.2
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
cpptools|ms-|1.6.0
mono-debug|ms-|0.16.2
vsliveshare|ms-|1.0.4761
finder-me|par|0.0.4
remote-vscode|raf|1.1.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
llvm|RRe|0.1.1
edit-with-shell|ryu|1.3.0
stylelint|shi|0.51.0
vscode-scss-formatter|sib|2.2.3
html5-boilerplate|sid|1.1.1
latex-support|tor|3.9.0
simple-rst|tro|1.4.0
lorem-ipsum|Tyr|1.3.0
vscode-terminal-here|Tyr|0.2.4
reopenclosedtab|uyi|1.1.0
vscode-lldb|vad|1.6.5
gitblame|wad|8.1.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pythonvspyt187cf:30361754
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by IllusionMH** [comment] 2021-09-04 03:07
/duplicate of #128763 (reproducible not only for remote)

**Closed** 2021-09-04 03:08 UTC
Labels: *duplicate, new release
