### ISSUE TITLE
Auto Import do not support interface/type

### ISSUE THREAD

**Issue by Lxxyx** [Microsoft/vscode#38309] opened 2017-11-14 09:52 UTC
- VSCode Version: 1.18.0

Steps to Reproduce:
1. git clone https://github.com/Lxxyx/auto-imports-cnpm.git
2. open project, edit index.js
3. type Network, but get nothing.

Interface:
![image](https://user-images.githubusercontent.com/13161470/32773418-bd7f3da8-c8ee-11e7-9656-f202540a3a9c.png)

Result:
![image](https://user-images.githubusercontent.com/13161470/32773452-d4e08678-c8ee-11e7-8234-2152af239271.png)

## Why

In flow.js project, I can use interface and type.
And in ts project, import interface or type is frequently.

Reproduces without extensions: No

**Comment by mjbvz** [comment] 2017-11-14 16:19
This is by design for JS. We only show type/interface suggestions when you are in a context that supports them, such as a JSDoc comment. TypeScript also only will show interface suggestions when you are in context where they make sense

We don't provide flow support out of the box, so anything specific to that language is out of scope

**Closed by mjbvz** 2017-11-14 16:19 UTC
Labels: as-designed, javascript, new release
