### ISSUE TITLE
Switching tab cause fold issues 

### ISSUE THREAD

**Issue by acttogreen** [microsoft/vscode#149617] opened 2022-05-16 06:51 UTC
Issue Type: <b>Bug</b>

first i try to type some code. Switch tabs to another file, then switch back to previous file. all my code became folded. its annoying. please help

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.26GB free)|
|Process Argv|D:\\Project\\WanganDorifto -g D:\\Project\\WanganDorifto\\Assets\\_Scripts\\Core\\GameManager.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
beardedicons|Bea|0.18.0
vscode-author-generator|edw|0.2.2
prettier-vscode|esb|9.5.0
font-switcher|eva|4.0.3
copilot|Git|1.20.5902
gitkraken-authentication|git|1.0.3
discord-vscode|icr|5.8.0
unity-code-snippets|kle|1.3.0
csharp|ms-|1.24.4
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
unity-logcat|sim|0.0.3
vscode-smoothtype|spi|1.2.0
author-tag|toj|1.0.2
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.21

(9 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2022-05-16 07:24
Please use the Start Extension Bisect command to investigate whether the issue is being caused by one of your extensions.

**Comment by aeschli** [comment] 2022-12-09 15:35
Reproducible steps are needed to find out more:
- the inputs of the files
- which sections are folded
- where do you click

**Comment by aeschli** [comment] 2022-12-14 14:15
Closing due to lack of additional information

**Closed by aeschli** 2022-12-14 14:15 UTC
Labels: info-needed, editor-folding
