### ISSUE TITLE
Git Version Control blocked

### ISSUE THREAD

**Issue by enzofoucaud** [microsoft/vscode#136858] opened 2021-11-10 13:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- Version : 1.62.1 (user setup)
- Commit : f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
- Date : 2021-11-05T10:57:55.946Z
- Electron : 13.5.2
- Chrome : 91.0.4472.164
- Node.js : 14.16.0
- V8 : 9.1.269.39-electron.0
- OS : Windows_NT x64 10.0.19043

Hello,

Git is blocked when I open my VSCode today.

I do a `git status` and I get this : 
```
On branch develop
Your branch is behind 'origin/develop' by 17 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .agola/config.yml
        modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

However, when I check the VSCode source control I have nothing
![image](https://user-images.githubusercontent.com/15039645/141117578-7a3a5d2d-728e-4cf2-af4a-40c083ae8ed3.png)
![image](https://user-images.githubusercontent.com/15039645/141117631-8c0b7b2a-dfb7-4530-9d0c-1e19ee6a8f4f.png)
it runs continuously

I could notice that the problem was present with Go but nothing sure.
All working this morning.

Best regards.

**Comment by lszomoru** [comment] 2021-11-10 14:13
This is a duplicate of #136837

**Closed by lszomoru** 2021-11-10 14:13 UTC
Labels: git
