### ISSUE TITLE
ctrl + N not working

### ISSUE THREAD

**Issue by cottrell** [microsoft/vscode#79368] opened 2019-08-17 20:13 UTC
Why not have a form in vscode that submits issues to github with the required content? 

ctrl + N and various other shortcuts sporadically stop working on Linux. I have not figured out the pattern yet. Manually going to the file menu and opening a new file works. There is nothing in my keybindings.json.

**Comment by gjsjohnmurray** [comment] 2019-08-17 20:15
> Why not have a form in vscode that submits issues to github with the required content?

Have you tried the 'Report Issue' option on the 'Help' menu?

**Comment by cottrell** [comment] 2019-08-19 19:39
https://github.com/microsoft/vscode/issues/79468

**Comment by cottrell** [comment] 2019-08-19 19:40
I'll leav it open for now but probably can just link to the one posted from vscode. I am trying to find a way to disable the git stuff to see if that does it. I do not see a git extension.

**Comment by alexandrudima** [comment] 2019-08-26 14:12
duplicate of #79468

**Closed by alexandrudima** 2019-08-26 14:12 UTC
