### ISSUE TITLE
"Go to definition" in typescript doesn't go to definition, but to type definition

### ISSUE THREAD

**Issue by novellizator** [Microsoft/vscode#40086] opened 2017-12-12 11:29 UTC
- VSCode Version: 1.18.1
- OS Version: macOS high Sierra

Steps to Reproduce:

1. open any source in typescript
2. right click on a symbol -> "go to definition"
3. VS Code opens the file with type definitions (mostly from definitelytyped) instead of real symbol definition. = it behaves the same way as "go to type definition"

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-12-12 23:51
Duplicate of https://github.com/Microsoft/TypeScript/issues/6209 / https://github.com/Microsoft/TypeScript/issues/16792

**Closed by mjbvz** 2017-12-12 23:51 UTC
Labels: typescript
