### ISSUE TITLE
Webview eats any key-chord

### ISSUE THREAD

**Issue by jmtb28** [microsoft/vscode#108493] opened 2020-10-11 17:57 UTC
Issue Type: <b>Bug</b>

1. Press `Ctrl` + `Shift` + `P`
2. Type "Code: Show Release Notes"
3. Press `Enter`
4. Press `Ctrl` + `K`
5. Press `Shift` + `Enter`

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 4.19.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics (4 x 2424)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|13.64GB (0.88GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 74c7044e-910e-472d-83e2-c96db17a09b9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-gitignore-generator|pio|1.0.2
material-icon-theme|PKi|4.3.0
code-settings-sync|Sha|3.4.3
licenser|ymo|1.5.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2020-10-12 08:37
@mjbvz seems pretty bad, it looks like once focus is inside `webview` any chord does not work. I can see the status bar showing a brief message that it waits for pressing the second keybinding, but this message goes away directly.

//cc @alexdima

**Comment by bpasero** [comment] 2020-10-12 08:37
I feel this is important given how prominent `webview` editors are. Also not sure if a recent regression or not.

**Comment by mjbvz** [comment] 2020-10-12 23:05
Duplicate of #100953

**Closed by mjbvz** 2020-10-12 23:05 UTC
Labels: bug, important, keybindings, webview
