### ISSUE TITLE
Support enum dropdown for configuration arrays in settings UI

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#80537] opened 2019-09-08 21:05 UTC
```json
     "myext.option": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "A",
              "B"
            ]
          }
      }
```

Currently (1.38), the settings UI only shows an enum dropdown when the setting is not an array. In the example above only an "Add Item" button is shown with free-text input. A dropdown would be better.

**Comment by letmaik** [comment] 2019-09-08 21:09
@chrmarti The vscodebot shouldn't suggest duplicate issues if they are from the same author (myself). It's quite unlikely that this would happen.

**Comment by chrmarti** [comment] 2019-09-09 07:15
@letmaik Good point, adding it to the bot's issues. Thanks.

**Comment by octref** [comment] 2019-09-11 20:59
Duplicate of #77458.

**Closed by octref** 2019-09-11 20:59 UTC
