### ISSUE TITLE
Performance Issue with TypeScript and JavaScript Language Features Extension in VS Code

### ISSUE THREAD

**Issue by otabekoff** [microsoft/vscode#227233] opened 2024-08-30 16:53 UTC
Does this issue occur when all extensions are disabled?: Yes

I've also tried Extension Bisect and found a JS Extension. But I've removed it. And the issue was still persisting even if I restarted VS Code app.

### How, story has come till here?

Two weeks ago new VS Code update has been installed automatically when I exited the VS Code app. Then, I didn't care about it. When I opened the next time, a "What's new" popup appeared showing changes. The updates were amazing.

However, since then, I've noticed some **lagginess** in JavaScript files with hint popups (IntelliSense) showing up slowly when something is typed. I don't know what to call the quick popup hints, so I refer to them as such. From that day, I started debugging the whole VSCode setup, including my extensions and settings. 

I've exported my settings, cleared VSCode caches, uninstalled VSCode, and freshly installed it again, but the issue persisted. There were no extensions installed, and it seemed suspicious. I also removed some data from my NVMe M2 SSD (C drive), leaving 35GB of free space, but this didn't help either. After several restarts, I found the **Built-in Extensions** section in VSCode's Extensions panel and thought of testing with those.

Surprisingly, when I disabled the **TypeScript and JavaScript Language Features** built-in extension, the issue was resolved! The hint popups began showing very quickly, just like in Monaco Editor examples. 

Now, I believe there is something wrong with this extension, or it needs optimization for quicker response times.

### VS Code Info:
- **VS Code Version:** 1.92.2
- **OS Version:** Windows_NT x64 10.0.22631 (Windows 11)
- **Electron:** 30.1.2
- **Node.js:** 20.14.0
- **V8:** 12.4.254.20-electron.0

### Steps to Reproduce:

1. Open a freshly installed VS Code app with no settings and no extensions.
2. Open a folder that includes any JavaScript file.
3. Write a `log` in the file and observe it takes 3-10 seconds for the IntelliSense hint popups to appear.
4. Go to the **Extensions View** (`Ctrl + Shift + X`) and open **Built-in Extensions** from the filter icon in the search box.
5. Find the extension named **TypeScript and JavaScript Language Features**.
6. Disable this extension and restart the extension host.
7. Go back to the JavaScript file and rewrite the log. You will notice the hint popups appear much faster.

### Expected Behavior:
The IntelliSense suggestions and hint popups should appear quickly while the TypeScript and JavaScript Language Features extension is enabled.

### Actual Behavior:
When the TypeScript and JavaScript Language Features extension is enabled, IntelliSense suggestions take 3-10 seconds to appear in JavaScript files.

### Additional Context:
Disabling this extension resolves the performance issue, but this is a critical extension for JavaScript and TypeScript development. It would be helpful to optimize the extension to reduce the delay.

### Related Info:
- This issue occurs with no other extensions installed.
- The issue persists even after clearing caches and reinstalling VS Code.

**Comment by otabekoff** [comment] 2024-08-31 01:42
Watch the whole video and see what's exactly happening:
https://github.com/user-attachments/assets/a6f37303-b8a2-45d4-ab3c-d6250c389c67

**Comment by otabekoff** [comment] 2024-08-31 07:31
@mjbvz Hi. Any news? You were assigned to this issue. Is there any ongoing works on this?

**Comment by mjbvz** [comment] 2024-09-03 20:33
Sorry but this is too long to read/watch. Please follow our issue reporting guidelines to make it more actionable, such as a minimal set of steps to reproduce the project (including any relevant example code)

**Comment by otabekoff** [comment] 2024-09-05 16:28
@mjbvs How you can say it is too long by adding `info-needed` badge yourself?

I've written it in a way that's clear and makes the problem clear. The text written above is not long. I just included the versions following what you wrote. I just wrote some text only. As for the video, I suggest you watch the second video. The first is optional.

However, it could be read and viewed ten times by now. This is the first time I've heard such a funny thing on GitHub. When everyone asks for more details, you say shorter. Then why did you add the "info needed" badge? Beautifully obscure.

**Comment by kvnlnt** [comment] 2024-09-11 21:53
This is happening to me now. The Typescript and Javascript Language Features plugin is taking 3-5-10 seconds to resolve anything: intellisense, organizing imports, saving. etc...taking a "running extensions" reveals the culprit of the ts/js lang feature plugin. Enablling/disabling proves it's the issue. This started last week for me on all my code bases including ones I haven't touched in months.

**Comment by mjbvz** [comment] 2024-09-23 21:55
Please share an example project and simple steps to reproduce the issue using it

**Comment by robbyemmert** [comment] 2024-12-12 22:42
I'm having this same issue with no plugins installed. This is affecting our team's productivity.

We've set typescript to exclude node_modules via tsconfig, and via .vscode/settings.json, but it's still adding file watchers to nearly every file in node_modules.

**Comment by mjbvz** [comment] 2024-12-12 23:25
@obbyemmert Please start by following  [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. If you're still seeing problems, go ahead and open a new issue so we can take a look. Be sure to include example code which causes this or the logs

Closing this issue since we can't investigate any further without an example project

**Closed by mjbvz** 2024-12-12 23:25 UTC
Labels: info-needed

**Comment by kunjolee** [comment] 2025-01-08 21:04
@mjbvz so bad you can't really help the community just because you don't want to read/watch a video.. I'm also having same issue

**Comment by sovetski** [comment] 2025-01-19 17:44
same here, this is a real problem, I will change my IDE if it continues

**Comment by dpertsin** [comment] 2025-01-22 12:01
Do we have any alternative, I have the same problem....

**Comment by mjbvz** [comment] 2025-01-23 23:25
If you're seeing performance problems, please open an new issue and share an example project so we can take a look

Videos are not useful in these cases becauseI they mean I have to watch over and over to try to recreate your code/project on my machine. This almost never results in a reproduction of the bug because the video is missing critical details
