### ISSUE TITLE
SCM history up and down arrows interfere with suggestions

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode#109184] opened 2020-10-22 18:50 UTC
Issue Type: <b>Bug</b>

**Repro**
1. Install the [emojisense extension](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)
1. Go to scm input.
1. Type `:` to see emojis
1. Try to use up and down arrows to navigate the list

**Bug**
The suggest widget closes and history navigation happens instead

VS Code version: Code - Insiders 1.51.0-insider (6c8c6008ef9d86e46b086a00f273b1fee5bd8c51, 2020-10-21T05:33:56.950Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|40.00GB (0.31GB free)|
|Process Argv|-psn_0_426088 --crash-reporter-id cefe23df-690f-4b1b-9ce9-e004d3be2745|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment] 2020-10-22 18:51
Duplicate of #109145

**Closed by mjbvz** 2020-10-22 18:51 UTC
