### ISSUE TITLE
TS syntax highlighter confuses apostrophe in Regexp literal

### ISSUE THREAD

**Issue by danielrentz** [microsoft/vscode#91537] opened 2020-02-26 08:29 UTC
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a TS file
2. Type:
`export const c1 = "abc";`
`if (!/^['"]$/.test(c1)) { }`
`export const c2 = 2;`

The code after the apostrophe in the RE will be rendered as string. The keywords "export const" in the third line will not be highlighted anymore.

Removing the exclamation mark before the RE lets the bug disappear, as well as enclosing the RE into parentheses.

**Comment by mjbvz** [comment] 2020-02-26 18:17
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-02-26 18:17 UTC
