### ISSUE TITLE
Search issue on VSCode ver 1.8.1

### ISSUE THREAD

**Issue by louisnguyen1012** [Microsoft/vscode#17718] opened 2016-12-22 06:42 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

1. Open search tab
2. Enter text and search
3. searching process cannot finish, and miss matched items.

![image](https://cloud.githubusercontent.com/assets/3841162/21417343/58731dc4-c84c-11e6-87f0-13c2093dffcf.png)

**Comment by bpasero** [comment] 2016-12-22 07:21
@louisnguyen1012 are you able to share the workspace with us?

**Comment by sergej-s** [comment] 2016-12-22 10:02
Hello! Search also doesn't work with network drives and network folders.

**Comment by chrmarti** [comment] 2016-12-22 13:44
@sergej-s Did it work in previous versions of VSCode?

**Comment by chrmarti** [comment] 2016-12-22 14:00
@louisnguyen1012 Could you check the console in the DevTools (Help > Toggle Developer Tools) for any messages?

**Comment by louisnguyen1012** [comment] 2016-12-29 08:54
Hi.

I am sorry for late response.

There is nothing on console of DevTools.
But I have a point: 
If I hibernate and resume my laptop, then this issue occurs. I also try to start VS Code with Administrator privilege.
If I turn off and restart laptop, it works well.

**Comment by sergej-s** [comment] 2016-12-29 18:56
@chrmarti I am sorry for the delay too.
I think that search worked with previous version, but I am not sure. Can't remember I searched something or not with prev versions.

**Comment by roblourens** [comment] 2017-01-03 19:16
When this happens, can you open Task Manager and check whether there is a process using lots of CPU, and let me know what you see? There may be a process related to antimalware running against our search process.

**Comment by louisnguyen1012** [comment] 2017-01-04 08:19
I observe my laptop, also my colleges', the CPU is just normal (<10%) when this issue occurs.

**Comment by chrmarti** [comment] 2017-01-04 08:45
@louisnguyen1012 and @sergej-s, to further isolate the issue: Does Quick Open (Ctrl+P, on OSX: Cmd+P) show all the expected files? (Disregard the 'recently opened' results, as these are persisted per workspace.)

Also, just make sure: Did you open a folder in VSCode? (Search shouldn't hang if you didn't, but we'd have to look at additional code than otherwise.)

**Comment by louisnguyen1012** [comment] 2017-01-04 11:00
1) Quick Open works well.
2) Yup, I opened my project folder in VS Code.

**Comment by sergej-s** [comment] 2017-01-11 09:10
The same as louisnguyen1012 said - Quick Open works fast, whole project folder was opened in VS Code.

Noticed that search finds results for some file if this file is opened in editor.

**Comment by roblourens** [comment] 2017-01-11 16:26
@sergej-s Is this also Windows? It sounds like other people are not seeing the problem consistently, do you see it every time? And

>When this happens, can you open Task Manager and check whether there is a process using lots of CPU, and let me know what you see? There may be a process related to antimalware running against our search process.

**Comment by sergej-s** [comment] 2017-01-12 09:13
@roblourens @chrmarti It seems I located cause of the problem in my case.
I used network drive (z:\) connected to project folder and opened whole disk z: in VS Code but not a subfolder z:\myproject. So if I open disk in VS then search doesn't work. If I open subfolder then search works.

Evn: Windows 10, account with user permissions, network drive connected to project folder.

**Comment by roblourens** [comment] 2017-01-12 18:36
When you say it doesn't work, do you mean the search shows the progress bar but never finds results, or some other problem? Could it be that it's just taking a long time to search the whole disk?

**Comment by roblourens** [comment] 2017-01-13 23:13
I am seeing this on Windows too, when searching all of C:/. I have a PR open to address it: #18533. Thanks for the report!

In this case, the issue will repro on Windows, and in cases where there are many many files, or IPC messages are slow to be delivered to the search worker processes. The symptoms would be that search at some point stops showing results, and never finishes.

**Comment by sergej-s** [comment] 2017-01-16 09:20
@roblourens Yes, search shows the progress bar, but never finds results. Please notice that I searched not disk c: where a lot of files but project folder which is mapped to drive (i.e. Z:) and search this drive.

**Comment by roblourens** [comment] 2017-01-17 15:52
Right, likely the same issue though.

**Comment by roblourens** [comment] 2017-01-23 19:56
@louisnguyen1012 @sergej-s I think the issue is now fixed in the Insider's build. Would really appreciate it if you try it out in Insider's or the next release and let me know.

Verifier: Search the C:\ drive on Windows. It may take a long time, but it should finish eventually.

**Comment by aglaberson** [comment] 2017-01-25 15:03
I'm having the same issue. Search is much, much slower and then stops completely at about 90%. How can I revert to the previous version?
![capture](https://cloud.githubusercontent.com/assets/18406070/22295590/6fba012e-e2e5-11e6-93ec-2e9566541e7b.PNG)

**Comment by roblourens** [comment] 2017-01-25 16:27
If it's the same issue, this should be fixed in the Insider's build or 1.9

**Comment by bpasero** [comment] 2017-01-26 14:55
@roblourens is there something to verify here?

**Comment by roblourens** [comment] 2017-01-26 15:35
Yes, search the C:\ drive on Windows. It may take a long time, but it should finish eventually.

**Comment by isidorn** [comment] 2017-01-26 15:56
I also get to 90% after a minute of searing on my root drive, after that some results pop up but progress remains at around 90% and vscode becomes unresponsive 
8 minutes later vscode is not unresponsive but very slow and progress still around 90%

![screen shot 2017-01-26 at 16 54 19](https://cloud.githubusercontent.com/assets/1926584/22338618/1bfabeb2-e3e8-11e6-8075-42f6b99635fd.png)

A bunch of errors in console
```
ipc.cp.ts:152 [IPC Library: Search] Uncaught Exception:  SyntaxError: Unexpected token  in JSON at position 0(anonymous function) @ ipc.cp.ts:152e.invoke @ callbackList.ts:63e.fire @ event.ts:118r @ event.ts:12emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
ipc.cp.ts:152 [IPC Library: Search] SyntaxError: Unexpected token  in JSON at position 0
    at Pipe.channel.onread (internal/child_process.js:448:28)
```

**Comment by roblourens** [comment] 2017-01-26 16:08
> 8 minutes later vscode is not unresponsive but very slow

I think this implies a different issue than the one I fixed. Was there high CPU usage? Did you notice from what process?

**Comment by roblourens** [comment] 2017-01-26 16:13
I'm not reproing this in either a VM or physical machine.

**Comment by roblourens** [comment] 2017-01-26 16:14
The 90% progress bar comes from the fact that we only register fake progress up to 90% - it doesn't really mean anything.

**Comment by isidorn** [comment] 2017-01-26 16:58
I can repro it easily on my vm which has 2gb ram.
No cpu spikes, I guess the vm just runs out of memory since it has a 2gb limit

**Comment by roblourens** [comment] 2017-01-26 17:54
Still no crash for me, it's just even slower.

**Comment by joaomoreno** [comment] 2017-01-27 08:34
It doesn't seem to be a regression of the original issue. Lowering severity and pushing to February.

Also, the search completed on my machine after some time. No crash.

**Comment by roblourens** [comment] 2017-01-27 17:15
I'm going to close this and open a new issue for what Isidor sees.

**Closed by roblourens** 2017-01-27 17:15 UTC
Labels: bug, search

**Comment by isidorn** [comment] 2017-02-24 14:24
Adding verified since it does not crash for me
