### ISSUE TITLE
Prompting every time the file is opened

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99164] opened 2020-06-02 17:44 UTC
Testing #98989

By default, opening a file with a special new line character prompts the user to fix or ignore the file. If I ignore the file and close and re-open it, I am prompted every time. This is quite annoying for the ignore case.

**Comment by alexdima** [comment] 2020-06-04 19:56
Duplicate of #99027

**Closed by alexdima** 2020-06-04 19:56 UTC
