### ISSUE TITLE
Debt - Revisit and improve the use of the editor inside the debug console

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12020] opened 2016-09-14 13:49 UTC

**Comment by egamma** [comment] 2016-10-04 10:46
One issue is that once you install the VIM extension, then line numbers show up in the text input field in the debug console.

![image](https://cloud.githubusercontent.com/assets/172399/19071444/71c11240-8a30-11e6-9c6c-747c7275780d.png)

**Comment by isidorn** [comment] 2018-03-20 09:14
Let's close this as a duplicate of https://github.com/Microsoft/vscode/issues/46112
Since that one is already referenced on the plan

**Closed by isidorn** 2018-03-20 09:14 UTC
Labels: debt, editor
