### ISSUE TITLE
snippets `tab` inserts a tab character instead of moving to next placeholder

### ISSUE THREAD

**Issue by sharkweek** [Microsoft/vscode#72771] opened 2019-04-23 17:07 UTC
- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

1. When I hit `tab` to move to the next placeholder, a tab character is inserted instead of moving to the next placeholder.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2019-04-23 17:16
please share the snippet you are inserting and the steps you are executing

**Comment by sharkweek** [comment] 2019-04-23 17:44
Hi, @jrieken! It seems to be happening on all snippets, but here is an example of one. It is scoped for markdown so I can create LaTeX math brackets when I'm documenting equations.

```js
"mathBrackets": {
	"description": "LaTeX math brackets",
	"prefix": "\\left",
	"body": [
		"\\left${1|(,[,{|} $2 \\right${3|),],}|}"
	]
}
```

**Comment by jrieken** [comment] 2019-04-24 07:11
Works for me... Do you have a special keybindings configuration? Can you reproduce this when extensions are disabled?

**Comment by sharkweek** [comment] 2019-04-24 15:17
No special keybindings, and yes, it also happens with all extensions disabled. I did a few consecutive updates so I'm not even sure when was the last version that worked properly.

**Comment by jrieken** [comment] 2019-04-25 07:06
This doesn't make sense, there must be something special here. Any custom setting? Can you attach more precise steps and/or a gif?

**Comment by jrieken** [comment] 2019-04-29 11:01
best-guess-closing this as dupe of https://github.com/Microsoft/vscode/issues/72862

**Closed** 2019-04-29 11:01 UTC
Labels: *duplicate, needs more info, snippets

**Comment by sharkweek** [comment] 2019-04-29 17:34
I don't know what happened, but it started working properly again. Thanks for the help!
