### ISSUE TITLE
Intellisense for external libraries  (except jquery) not working in script tag

### ISSUE THREAD

**Issue by realmerx** [Microsoft/vscode#63535] opened 2018-11-21 00:43 UTC
Issue Type: <b>Bug</b>

1. Create new html file with script tag. 
2. Create new javascript file
3.  create type definition file with following contents

    declare function testClient(string a): string;

4. Start typing testClient in javascript file - intellisense works
5. Start typing testClient in script tag - intellisense does not work

Odd thing is that if I start typing $.g (jquery $.get) then intellisense works even in script tag but go to definition does not work. But go to definition does work in javascript file for $.get() opening jquery type definition file.

There seems to be some bug reports similar to this but no explanation why it does work for jQuery.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

**Comment by mjbvz** [comment] 2018-11-27 02:14
Duplicate of #26338

**Closed by mjbvz** 2018-11-27 02:14 UTC
Labels: javascript
