### ISSUE TITLE
Custom editor should not open when viewing file in git diff view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#118764] opened 2021-03-11 21:48 UTC
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Install the Jupyter extension in VS Code stable.
2. Ensure you are opted out of the Native Notebooks experiment in your settings (see below for setting value) and delete `workbench.editorAssociations` if it's present in your user settings.json. This will force the Jupyter extension to use our custom editor implementation for displaying notebooks.
```
"jupyter.experiments.optOutFrom": [
    "NativeNotebookEditor",
  ],
```
Verify it looks like this, and not the new native notebooks UI:
![image](https://user-images.githubusercontent.com/30305945/110859464-50e40180-8270-11eb-8697-a48878887a11.png)

3. Create and save an ipynb file in a local git repo.
4. From the source control view open the ipynb file. It will open in the custom editor, preventing users from viewing the notebook diff.

Does this issue occur when all extensions are disabled?: No

/cc @ianmatthewhuff @greazer @rchiodo @davidkutu @DonJayamanne

**Comment by mjbvz** [comment] 2021-03-15 23:49
This is by-design for custom editors. The idea is that a custom editor should  provide a rich diff view that would be more useful than a simple json diff

The real notebook api should provide you a proper diff automatically but with custom editors, this is up to extensions

**Comment by rchiodo** [comment] 2021-03-16 00:18
@mjbvz is there a way for the custom editor to specify it doesn't support diffing? We don't plan on implementing our own diffing (well especially for notebooks since you guys have this already)

**Comment by mjbvz** [comment] 2021-03-16 00:27
No. Since custom editor are  stopgap for your notebook work, I don't think we have a good reason to add that functionality at this time

**Comment by DonJayamanne** [comment] 2021-03-23 17:37
@rebornix @kieferrm  Based on my recollection (in VS Code Sync meeting), I thought VS Code was going to look into this.

**Comment by kieferrm** [comment] 2021-03-23 23:21
Yeah, @mjbvz and I missed to talk about this one due to our weekly chat falling on Learning Day. We'll look into a fix for the forthcoming stable.

**Comment by mjbvz** [comment] 2021-03-23 23:37
@DonJayamanne Do you think this is a regression with the current VS Code insiders? I just tested this by doing the following:

1. Using the 
1. Change a tracked  `ipynb` file
2. In the source control view, click on the file in the `changes` section



Most of the time, this seems to just open up a single editor after a flash of another editor tab (although once or twice I ended up with the custom editor based notebooks really showing in a diff view).

https://user-images.githubusercontent.com/12821956/112232541-01012500-8bf6-11eb-8499-a0e04304e3d9.mp4

This behavior leads me to believe the python/jupyter extension is doing something custom when it detects a diff editor is being opened, since AFAIK other custom editors (such as the image preview) show in diff views since we originally shipped custom editors:

![Screen Shot 2021-03-23 at 4 20 14 PM](https://user-images.githubusercontent.com/12821956/112232368-aec00400-8bf5-11eb-888d-acbd963d5fab.png)


PS: how do you force insiders to use the custom editor python notebooks. The extension keeps writing `workbench.editorAssociations` for the new notebooks, even after I explicitly set it

**Comment by mjbvz** [comment] 2021-03-24 00:03
So in VS Code insiders, the difference I see is that the diff editor (the one labeled `(working tree)`) is not closed automatically when you click on a diff. However we still end up opening a regular file editor when clicking on the diff, which seems odd:

![Screen Shot 2021-03-23 at 4 57 42 PM](https://user-images.githubusercontent.com/12821956/112234115-04e27680-8bf9-11eb-92e0-b2de0800d74e.png)

I don't see this happening for other custom editors.


https://user-images.githubusercontent.com/12821956/112234374-a23daa80-8bf9-11eb-8349-88cb3880d4bd.mp4


@DonJayamanne @joyceerhl Is there code in the python extension side that opens this second editor when you open a differ?

**Comment by joyceerhl** [comment] 2021-03-24 00:41
When debugging the Jupyter extension and opening a custom editor from the source control view, `openCustomDocument` gets called, which causes us to load and show a notebook model: https://github.com/microsoft/vscode-jupyter/blob/94e89d24de8e0c643c248875adb141a259a386fe/src/client/datascience/notebookStorage/nativeEditorProvider.ts#L128-L142 I would think that `openCustomDocument` wouldn't be called for the diff view (at least that's the assumption we have made in our code).

**Comment by mjbvz** [comment] 2021-03-24 00:55
Custom editors should always have been used inside of diff views, so I'd be surprised if `openCustomDocument` was not being called. What you should see is two calls to `openCustomDocument`: one for the modified file and one for the original (this is the one with the `git:` scheme)

From the original issue description though, it seems like the expected behavior is that diffs would open in a plain text view (so you can diff the raw json). Is the correct? Or are you expecting that viewing the diff opens a the current file, which is the behavior I see in stable?

**Comment by joyceerhl** [comment] 2021-03-24 00:59
Yes I believe our expected behavior is for the diffs to open in a plain text view.

**Comment by mjbvz** [comment] 2021-03-24 01:05
@joyceerhl Is that what you see happening in  VS Code stable? If so, can you provide more details on your configuration because that does not match what I see

**Comment by mjbvz** [comment] 2021-03-24 01:24
As to why the diff editor is mysteriously disappearing when opening a diff:

* If you have preview editors enabled (`workbench.editor.enablePreview`) you get duplicate editors (the one marked `working tree` and the normal editor for the file). In my testing, this happens in both stable and insiders 

* I believe the root cause of the duplicated  is that `.reveal` is being called on the custom editor for the `file:` resource that makes up the diff view (this is the modified—i.e. on disk—version of the file). This causes a second editor to be opened instead of merely revealing the diff editor

On the VS Code side, calling `reveal` here should just reveal the diff editor instead of revealing the individual input in a new editor.

However `reveal` should really not be called when a custom editor is being opened. I debugged the Jupyter extension and here's the call stack that seems to lead to the problematic `reveal` call (this happens when just clicking to open a diff):

![Screen Shot 2021-03-23 at 6 21 43 PM](https://user-images.githubusercontent.com/12821956/112240018-c488f580-8c04-11eb-92ae-bd85b7c9f08c.png)

**Comment by mjbvz** [comment] 2021-03-24 21:10
@joyceerhl  Here's a video explaining the issue:

https://user-images.githubusercontent.com/12821956/112383443-5b5bbd80-8caa-11eb-89f9-acff1421ea16.mov

My proposal:

* In the Jupyter notebook extension, avoid the call to `reveal`. I'm guessing it's there for historical reasons. I'll look into submitting a PR

* In the future on the VS Code side (not for the upcoming stable) fix `reveal` for webviews that are in side-by-side editors

**Comment by mjbvz** [comment] 2021-03-24 21:23
Jupyter PR is up: https://github.com/microsoft/vscode-jupyter/pull/5276

**Comment by dovahcrow** [comment] 2021-04-01 02:44
Do we have any workarounds? It is quite annoying that every time I click an ipynb and the editor tab pops up.

**Comment by joyceerhl** [comment] 2021-04-01 03:30
The Jupyter extension released an update today containing a fix from @mjbvz which should address this https://github.com/microsoft/vscode-jupyter/releases/tag/2021.5.0

@dovahcrow I assume you have v2021.5.702919634 of the Jupyter extension installed? Could you please let us know if you have the latest Jupyter extension installed and the problem still persists?

**Comment by dovahcrow** [comment] 2021-04-01 06:42
@joyceerhl Sure I'd like have a try. May I ask if there's any documentation about how do I build the extension? It seems not released onto the vscode market. I still see version `v2021.3.684299474` in the market.

**Comment by joyceerhl** [comment] 2021-04-01 06:46
@dovahcrow After you upgrade your VS Code build to 1.55.0, you should be able to upgrade to v2021.5.702919634 of the Jupyter extension. Please let me know if that doesn't work.

**Comment by IanMatthewHuff** [comment] 2021-04-01 15:40
@dovahcrow Thanks for helping to confirm that for us.

**Comment by chenfeibo** [comment] 2021-04-06 00:17
I'm running Jupyter extension with version 2021.5.702919634 but this issue still repros. Which info/log shall I provide?

**Comment by jamesmyatt** [comment] 2021-04-06 13:16
I can confirm that I'm now getting rich editors on the left and right using v2021.5.702919634. I don't like it, since it doesn't highlight differences or synchronize scrolling in the two panes (i.e. it's not a _good_ diff view), but it is at least _a_ diff view, so I think this issue is fixed.

**Comment by mjbvz** [comment] 2021-04-20 23:09
To verify the VS Code side of the fix:

1. In the image editor, apply the diff

```diff
--- a/extensions/image-preview/src/preview.ts
+++ b/extensions/image-preview/src/preview.ts
@@ -48,6 +48,10 @@ export class PreviewManager implements vscode.CustomReadonlyEditorProvider {
 				this.setActivePreview(undefined);
 			}
 		});
+
+		setTimeout(() => {
+			webviewEditor.reveal();
+		}, 5000);
 	}
 
 	public get activePreview() { return this._activePreview; }
```

2. Now edit a committed image so it appears in the SCM change list
3. Click on the edited image in the change list to open the diff view
4. Click away to another editor in the same group (make sure the diff editor is not close)
5. After 5 seconds, confirm the diff editor itself is revealed instead of revealing one of the individual webviews

**Closed** 2021-04-20 23:09 UTC
Labels: bug, custom-editors
