### ISSUE TITLE
Markdown synchronized scrolling does not work with mouse wheel

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27526] opened 2017-05-30 10:06 UTC
Refs: #27350

1. Open a markdown file, open the preview to the side
2. Scroll through the markdown file using the mouse wheel
3. I would expect the preview is also being scrolled. It only gets scrolled once I move the cursor position

**Comment by mjbvz** [comment] 2017-05-30 15:49
Duplicate of #19459

**Closed by mjbvz** 2017-05-30 15:49 UTC
Labels: duplicate, markdown
