### ISSUE TITLE
scriptable terminal

### ISSUE THREAD

**Issue by bobmajdakjr** [Microsoft/vscode#7079] opened 2016-05-31 20:11 UTC
feature request: since the build system is kinda useless when build steps require multiple commands, being able to send commands to the integrated terminal from script.

my personal reason for this is that for skyrim modding, its a multiple step build system which requires the editor being wrapped by MO so that the app has access to the virtual directory. executing a batch script is out of the question as the commands need to be dynamically generated, plus the build system currently seems to spawn outside of the wrapped process.

**Comment by Tyriar** [comment] 2016-06-01 00:06
Duplicate of https://github.com/Microsoft/vscode/issues/7034

**Closed by Tyriar** 2016-06-01 00:06 UTC
