### ISSUE TITLE
Reuse settings in `contributes.configuration` section of extension's package.json

### ISSUE THREAD

**Issue by mcsknp** [microsoft/vscode#97662] opened 2020-05-13 02:47 UTC
When define available configurations for extension in `contributes.configuration` section of `package.json`, I can't reuse some properties for other like definitions in JSON schema.
As below:
```javascript
{
    // ...
    "contributes": {
        // ...
        "configuration": {
            "definitions": {
                "something": {
                    // ...
                }
            },
            "someconfig": {
                "$ref": "#/definitions/something" // or anyway to reference to above definitions
            }
            // ...
        }
        // ...
    }
    // ...
}
```

**Comment by aeschli** [comment] 2020-05-13 09:04
The configuration extension point only supports a subset of JSON schema: See   https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema.

`$ref` is not part of it.

I made it more explicit withhttps://github.com/microsoft/vscode-docs/commit/7108f817586e28808f969c4fb517d2b9b51ee001

We can allow the use of refs when we support  when we support "$id" references. #92042


duplicate of #81782

**Closed by aeschli** 2020-05-13 09:04 UTC
