### ISSUE TITLE
[html] formatting option "html.format.extraLiners" doesn't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#4261] opened 2016-03-15 15:28 UTC
testing #4066

- use this html:
```html
<HTML><HEAD><TITLE>Your Title Here</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER><HR> <a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site<H1>This is a Header</H1><H2>This is a Medium Header</H2> Send me mail at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>.<P> This is a new paragraph!<P><B>This is a new paragraph!</B><BR><B><I>This is a new sentence without a paragraph break, in bold italics.</I></B><HR></BODY></HTML>
```

- change `html.format.extraLiners` from `null` to `HEAD`

Observe: 
```html
<HTML>
<HEAD>
	<TITLE>Your Title Here</TITLE>
</HEAD>
<BODY BGCOLOR="FFFFFF">
	<CENTER>
		<IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER>
	<HR> <a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
	<H1>This is a Header</H1>
	<H2>This is a Medium Header</H2> Send me mail at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>.
	<P> This is a new paragraph!
		<P>
			<B>This is a new paragraph!</B>
			<BR>
			<B><I>This is a new sentence without a paragraph break, in bold italics.</I></B>
			<HR>
</BODY>
</HTML>
```

There is no extra line before the HEAD tag.

- change `html.format.extraLiners` to `null`

Observe: now there is an extra line before the HEAD and BODY tags:

```html
<HTML>

<HEAD>
	<TITLE>Your Title Here</TITLE>
</HEAD>

<BODY BGCOLOR="FFFFFF">
	<CENTER>
		<IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER>
	<HR> <a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
	<H1>This is a Header</H1>
	<H2>This is a Medium Header</H2> Send me mail at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>.
	<P> This is a new paragraph!
		<P>
			<B>This is a new paragraph!</B>
			<BR>
			<B><I>This is a new sentence without a paragraph break, in bold italics.</I></B>
			<HR>
</BODY>

</HTML>
```

**Comment by aeschli** [comment] 2016-03-16 16:15
fixed by 4b36383

**Closed by aeschli** 2016-03-16 16:15 UTC
Labels: bug, html

**Comment by enbo** [comment] 2016-06-04 22:41
- VSCode Version: Version 1.1.0 (1.1.0)
- OS Version: OS X 10.11.5 (15F34)

Steps to Reproduce:

1. Create an HTML file.
2. Paste the following into the HTML file:

    ```html
    <body>
      <h1></h1>
      <h2></h2>
      <h3></h3>
      <h4></h4>
      <h5></h5>
      <h6></h6>
      <address></address>
      <dl>
        <dd></dd>
        <dt></dt>
      </dl>
      <hr>
      <pre></pre>
    </body>
    ```
3. In your settings, add

    ```json
    "html.format.extraLiners": "h1, h2, h3, h4, h5, h6, address, dt, hr, pre"
    ```
4. Right-click on text in the HTML file, and select Format Code.
5. Nothing changes in the HTML file.

What should happen instead:
```html
<body>
  
  <h1></h1>
  
  <h2></h2>
  
  <h3></h3>
  
  <h4></h4>
  
  <h5></h5>
  
  <h6></h6>
  
  <address></address>
  <dl>
    <dd></dd>
    
    <dt></dt>
  </dl>
  
  <hr>
  
  <pre></pre>
</body>
```

**Comment by mlewand** [comment] 2017-02-21 07:47
It looks like there's a regression, as if VSCode would no longer respect `html.format.extraLiners` config.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jslint|ajhyndman|1.2.1|
|Bookmarks|alefragnani|0.11.0|
|ck4-test-mate|mlewand|0.0.1|
|jsrefactor|cmstead|0.5.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|copy-relative-path|enochc|0.1.1|
|beautify|HookyQR|0.8.4|
|copy-markdown-as-html|jerriepelser|1.0.0|
|docthis|joelday|0.4.0|
|copy-github-url|mattlott|0.1.0|
|vscode-exec-node|miramac|0.2.1|
|ecdc|mitchdenny|0.10.3|
|select-part-of-word|mlewand|0.2.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|promise-snippets|progre|0.2.3|
|vscode-open|sandcastle|0.1.0|
|code-settings-sync|Shan|2.4.4|
|code-spell-checker|streetsidesoftware|0.14.6|
|selectline-statusbar|tomoki1207|0.0.1|
|vscode-react-native|vsmobile|0.3.1|
|change-case|wmaurer|1.0.0|
|JasmineSnippets|xabikos|0.2.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. Set your `"html.format.extraLiners"` to `"head,body,div,p,/html"`.
1. Open new tab with `ctrl+n`.
1. Switch tab language to HTML.
1. Set a following markup:
	```html
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title></title>
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link href="css/style.css" rel="stylesheet">
		</head>
		<body>
			<div>foo</div>
			<div>foo</div>
			<div>foo</div>
			<p>foo</p>
			<p>foo</p>
			<p>foo</p>
		</body>
	</html>
	```
1. Press `ctrl+shift+f` to execute `Format Document` command.

## Expected

Lines are inserted also after `p` and `div` elements.

```html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title></title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="css/style.css" rel="stylesheet">
	</head>

	<body>
		<div>foo</div>

		<div>foo</div>

		<div>foo</div>

		<p>foo</p>

		<p>foo</p>

		<p>foo</p>

		</body>

</html>

```

## Actual

Missing new lines after `div` or `p`.

```html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title></title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="css/style.css" rel="stylesheet">
	</head>

	<body>
		<div>foo</div>
		<div>foo</div>
		<div>foo</div>
		<p>foo</p>
		<p>foo</p>
		<p>foo</p>
	</body>

</html>

```
