### ISSUE TITLE
Depreciated warning in the wrong place

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#117745] opened 2021-02-26 06:29 UTC
When writing javascript, vscode will put a strike through depreciated words found in object literal property declarations such as `const p = { name` until the colon is added. This seems like it is checking in the wrong place for this type of error as there are no depreciated words in this context.

**Comment by gjsjohnmurray** [comment] 2021-02-26 09:52
See #114725 for information and links

**Comment by mjbvz** [comment] 2021-02-26 21:14
Duplicate of https://github.com/microsoft/TypeScript/issues/18433

**Closed by mjbvz** 2021-02-26 21:14 UTC
