### ISSUE TITLE
Bring back Christmas Aesthetics 

### ISSUE THREAD

**Issue by Sanjay-B** [microsoft/vscode#87566] opened 2019-12-22 19:50 UTC
Hello. Before I begin, I know that religion is a sensitive topic but, please hear me out. 

Recently, a suggestion was made ( https://github.com/microsoft/vscode/issues/87268 ) to remove the Santa Hat since it relates to Christmas. While I understand that some things (icons, etc) can be referenced to religion, a lot of people (such as myself) enjoyed this small but, seasonal change. 

I’m almost surprised that this suggestion was taken seriously. To use religion as a way to take things down is morally wrong, especially when the icon was a mere red and white hat. Christmas has become more than just a Christian holiday, it’s a day where families no matter what religion or ethnic background can come together and make memories. Never in my entire life have I seen it as a Christian holiday, nor am I Christian to begin with. I’m aware that, I am not everyone’s opinion and while some may disagree, a simple middle ground would be to create seasonal aesthetics as a settings option and allow developers to toggle it on and off while keeping it off by default. 

Thanks.

**Comment by ItzLevvie** [comment] 2019-12-22 20:24
Duplicate of

**Comment by ItzLevvie** [comment] 2019-12-22 20:24
Duplicate of https://github.com/microsoft/vscode/issues/87440

**Comment by ItzLevvie** [comment] 2019-12-22 20:32
@Sanjay-B

**Comment by ItzLevvie** [comment] 2019-12-22 20:40
@Sanjay-B

Duplicate of https://github.com/microsoft/vscode/issues/87440#issue-540437717.

Please read the "**Looking forward…**" heading very very carefully. It has been added back in favor of an option which can be toggled on or off within the Settings menu.

**Comment by ItzLevvie** [comment] 2019-12-22 20:40
@Sanjay-B

Duplicate of https://github.com/microsoft/vscode/issues/87440#issue-540437717.

Please read the "**Looking forward…**" heading very very carefully. It has been added back in favor of an option, which can be toggled on or off within the Settings menu.

**Closed** 2019-12-22 22:33 UTC
Labels: *duplicate

**Comment by Visualizememe** [comment] 2019-12-22 22:57
Is this default behavior? Nobody knows about the feature if it isn't standardized. Those who get offended can simply disable it instead. For literally everyone else, it puts a smile on your face. It's not that big of a deal that everyone seem to make of it.

**Comment by knilecrack** [comment] 2019-12-23 17:39
use toggles for everything so you can avoid this type of stuff

**Comment by Zhigalin** [comment] 2020-01-04 11:34
@knilecrack
> use toggles for everything so you can avoid this type of stuff

The stuff to avoid is not the fixed icon design, the stuff to avoid is the `even a single person being offended is one too many` policy
