### ISSUE TITLE
Code gets committed although the pre-commit hook fails

### ISSUE THREAD

**Issue by 4kochi** [Microsoft/vscode#15897] opened 2016-11-22 16:08 UTC
- VSCode Version: 1.8.0-insider (f298203857dd6aebf096cb56de0c30b59e100d34)
- OS Version: macOS 10.12.1 (16B2657)

Steps to Reproduce:

1. Change some code
2. Commit code
3. Code gets committed, but the pre-commit hook fails

Here is the code of the pre-commit git hook:

```
#!/bin/sh

# Redirect output to stderr.
exec 1>&2

if [ "$(git status |sed 's/ *//g'|grep modified:)x" != 'x' ] ; then
  echo '### Changes: Running lint and test to avoid committing errors.'
  npm run test
  echo '### Tested.'
fi
```

When I run the commit command from the shell, the commit is aborted and the code is not committed

`git commit -m "Some stuff here"`

**Comment by joaomoreno** [comment] 2016-11-23 09:18
I can't reproduce this. When I set up the following hook, nothing gets committed in Code nor in the command line.

```
#!/bin/sh
exit 1
```

Your hook also seems a bit odd: it always returns 0. The contract with the `pre-commit` hook is to return non-zero on fail. You need to `exit` with the same exit code of `npm`.

```sh
#!/bin/sh

# Redirect output to stderr.
exec 1>&2

if [ "$(git status |sed 's/ *//g'|grep modified:)x" != 'x' ] ; then
  echo '### Changes: Running lint and test to avoid committing errors.'
  npm run test
  echo '### Tested.'
  exit $?
fi
```

**Closed by joaomoreno** 2016-11-23 09:18 UTC

**Comment by 4kochi** [comment] 2016-11-23 09:54
Thanks for your help. The problem was the last echo command `echo '### Tested.'`. It returns the code 0 and that would be used in `$?`. After removing the echo command all works fine.
