### ISSUE TITLE
STRG+C & STRG+V on files is not working.

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode#100951] opened 2020-06-24 12:56 UTC
Issue Type: <b>Bug</b>

Step 1: Mark a file with one click.
Step 2: Press STRG+C
Step 3: Mark a folder with one click
Step 4: Press STRG+V

Or is there a other way to copy files ?

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
ng-template|Ang|0.901.11
i18n-ally|ant|2.2.7
vscode-intelephense-client|bme|1.4.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.3.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.36.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
angular-extension-pack|dog|8.0.1
githistory|don|0.6.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.0
vue-inline-template|fai|1.0.1
vue-format|feb|0.1.8
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
vscode-lombok|Gab|1.0.1
vscode-codeql|Git|1.3.0
vscode-pull-request-github|Git|0.17.0
gitlab-workflow|Git|2.2.2
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
discord-vscode|icr|3.14.0
angular2-switcher|inf|0.3.3
docthis|joe|0.7.1
Angular2|joh|9.1.2
vscode-gutter-preview|kis|0.26.2
electron-debug|kod|18.11.1
refactorix|kri|0.3.6
graphql-for-vscode|kum|1.15.3
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|8.1.2
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.89148
typescript-javascript-grammar|ms-|0.0.53
vscode-js-profile-flame|ms-|0.0.5
vsliveshare|ms-|1.0.2377
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
vetur|oct|0.24.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.2.0
quicktype|qui|12.0.46
java|red|0.63.0
vscode-yaml|red|0.8.0
vscode-jest-test-adapter|rtb|0.2.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.9.0
tech-debt-tracker|Ste|0.27.4
move-ts|str|1.12.0
vscode-status-bar-format-toggle|tom|2.0.0
errorlens|use|3.1.1
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
quokka-vscode|Wal|1.0.301
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2020-06-24 13:00
Duplicate of #100797.

You can always copy files with terminal or your file manager.

**Closed** 2020-06-24 13:34 UTC
Labels: *duplicate
