### ISSUE TITLE
Terminal does not closed when drop down list is open

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#55285] opened 2018-07-28 02:01 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open Terminal
2. Open drop down list of terminals (do not close)
3. Then try to close terminal with **x**

Does this issue occur when all extensions are disabled?: Yes

Gif Demo:

![terminal-issue](https://user-images.githubusercontent.com/20873402/43351945-e3410e34-925d-11e8-8c46-9b5f73bb630c.gif)

**Comment by Tyriar** [comment] 2018-08-06 00:07
Looks like an issue with the dropdown and management of the panel, rather than an issue with the terminal.

**Comment by cleidigh** [comment] 2018-08-06 04:41
@isidorn 
@Tyriar  - I'm looping you back in because I found what I presume is a related issue that crashes
Code and may still be an interaction with the terminal.

First: I cannot reproduce the problem as originally stated in the issue.  My test:

Windows 7 - different from poster but I don't presume an issue
Master Commit hash f8420b48df76821d6ab65e03ad77befb3be58dcc 
latest for this evening

The related issue happens when the terminal is killed.  It does not appear to change if the drop-down
is selected or expanded.  There is always the possibility that my voice keyboard and mouse actions are just slightly different but I tried to make sure they were appropriate.  let me know what you think.

Reproduction:
- open panel with at least one terminal 
- Attempt to kill a terminal - use any of the following:
  - Click trash can
  - Focus trashcan with keyboard, select
  - F1 for commands, choose kill terminal

Result in all cases:


[10444:0806/000400.549:ERROR:gl_surface_egl.cc(744)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
[main 12:04:00 AM] update#ctor - updates are disabled
Debugger listening on ws://127.0.0.1:5876/bfc54ef2-4822-4c25-9231-24bc980042c9
For help see https://nodejs.org/en/docs/inspector
[10880:0806/000406.460:INFO:CONSOLE(182)] "%c INFO", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/log/common/log.js
(182)
[10880:0806/000406.864:INFO:CONSOLE(234)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (234)
[10880:0806/000407.259:INFO:CONSOLE(143)] "%c[Extension Host] %cdebugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/75888f65-5962-42f5-ace9-f30569188084", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (143)
[10880:0806/000408.257:INFO:CONSOLE(100)] "%c[Extension Host] %cvscode-icons is active! %c(at activate (C:\Users\Christopher Leidigh\.vscode-oss-dev\extensions\robertohuertasm.vscode-icons-7.12.0\out\src\index.js:50:13))", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/node/console.js (100)
[10880:0806/000639.839:INFO:CONSOLE(41)] "[uncaught exception]: Error: Pty seems to have been killed already", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (41)
[10880:0806/000639.839:INFO:CONSOLE(44)] "Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\node-pty\lib\windowsPtyAgent.js:83:13)
    at WindowsTerminal.<anonymous> (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\node-pty\lib\windowsTerminal.js:144:26)
    at WindowsTerminal._defer (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\node-pty\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.kill (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\node-pty\lib\windowsTerminal.js:139:14)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/node/terminalProcess.js:93:35", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (44)
[10880:0806/000640.372:VERBOSE1:CONSOLE(8192)] "Main._createAppUI: 45.85791015625ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[10880:0806/000640.423:VERBOSE1:CONSOLE(8192)] "Main._showAppUI: 47.576904296875ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[10880:0806/000640.518:VERBOSE1:CONSOLE(8192)] "Main._initializeTarget: 28.480224609375ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[10444:0806/000648.919:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.924:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.925:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.926:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.926:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.927:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.933:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.934:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.934:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.934:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.935:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[10444:0806/000648.935:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1

Terminal will be reused by tasks, press any key to close it.

**Comment by Tyriar** [comment] 2018-08-06 07:51
@cleidigh could be https://github.com/Microsoft/vscode/issues/31301 or https://github.com/Microsoft/vscode/issues/43169?

**Comment by cleidigh** [comment] 2018-08-06 21:53
@Tyriar 
a quick look at those issues and I see these are not in areas I am familiar with, is there something I can help with that you can point me to?

**Comment by Tyriar** [comment] 2018-08-07 18:55
@cleidigh isn't this issue unrelated to that though? This issue looks like it's a problem with the lifecycle of the dropdown and panel, rather than actually killing the terminal.

**Comment by cleidigh** [comment] 2018-08-08 19:36
@Tyriar 
I agree it looks like a lifecycle issue , but I just tried another experiment to isolate it:

Updated and built master a6d1949dca839af0f7e1e8cc323c6d9db5982f43

open 2 terminals
Use F1 and execute command: Kill terminal does not matter which one
Code crashes with same error above

Since in this case the select box is neither selected nor open, also the panel state does not change, stays open because they're still one terminal open, I would think this would be within the kill terminal path.

Sound correct?

**Comment by alexr00** [comment] 2018-09-12 20:41
I can't reproduce this with version 1.28.0-insider on Windows 10. Please re-open if it's still happening!

**Closed by alexr00** 2018-09-12 20:41 UTC
Labels: bug, dropdown, integrated-terminal, workbench-layout
