### ISSUE TITLE
Ayu light theme find all references broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23096] opened 2017-03-23 13:51 UTC
The find all references color is broken from today's insider in the Ayu Light theme that I use

![screen shot 2017-03-23 at 14 50 17](https://cloud.githubusercontent.com/assets/1926584/24250728/270920fc-0fd8-11e7-9ec8-f863ccc26c02.png)

**Comment by aeschli** [comment] 2017-03-23 14:50
duplicate of #23087

**Closed by aeschli** 2017-03-23 14:50 UTC
