### ISSUE TITLE
Search & replace with regex crash

### ISSUE THREAD

**Issue by eco747** [microsoft/vscode#120181] opened 2021-03-30 14:02 UTC
- VS Code Version: 1.54.3
- OS Version: windows 10

Steps to Reproduce:

1. create a .c file, save it
2. paste the text
```c
/*
  	Copyright 2014  xxx xxx (xxx [at] xxx [dot] com)
*/
```
3. open the search & replace window (ctrl+h)
4. select regex search 
5. paste the following text
```
^/*\s*(.*)*
```
6. press the s key
7. you are locked

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-03-30 14:05
/duplicate of #30874

Problem is in `(.*)*` you should make it more strict match or remove repetitions

**Closed** 2021-03-30 14:06 UTC
Labels: *duplicate
