### ISSUE TITLE
TypeScript busy/blocked when typing a new import

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18792] opened 2017-01-19 15:45 UTC
* open a TypeScript file and JSON file from our workspace
* make sure hovers in both work
* in the TS file, *type* an import
* 😴 TypeScript is dead for ~45seconds, JSON still alive which hints to me there is a problem with tsserver

![jan-19-2017 16-47-00](https://cloud.githubusercontent.com/assets/1794099/22113557/f0463912-de66-11e6-844d-81e7f4002a96.gif)

**Comment by joaomoreno** [comment] 2017-02-20 17:22
bump @mjbvz

**Comment by mjbvz** [comment] 2017-02-22 00:57
Closing as duplicate of #20815

**Closed by mjbvz** 2017-02-22 00:57 UTC
Labels: duplicate, important, typescript
