### ISSUE TITLE
Tree removeItemFromDOM throws when using dynamic heights

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65981] opened 2019-01-03 16:45 UTC
- See this null check I added - https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listView.ts#L378
- Comment it out
- Open the settings editor, scroll up and down quickly or resize the editor back and forth horizontally
- See exceptions thrown because it seems that it's calling `removeItemFromDOM` on an item that has not been added to the DOM

**Comment by joaomoreno** [comment] 2019-01-04 07:49
@roblourens Is it already using dynamic heights?

**Comment by roblourens** [comment] 2019-01-04 18:34
I still see it. Here are better steps.

- Comment out the null check
- Open the settings editor 
- Resize the sidebar to make the settings editor as narrow as possible
- Then resize the sidebar back to make the settings editor wide
- Scroll down a bit
- See a random gap between the last visible setting and the next one

![image](https://user-images.githubusercontent.com/323878/50704376-015c7800-100c-11e9-9253-caa55f1514ea.png)

- Scroll down further, get the exception

Stack:

```
TypeError: Cannot read property 'templateData' of null
ListView.removeItemFromDOM (/Users/roblou/code/vscode/src/vs/base/browser/ui/list/listView.ts:382)
ListView.render (/Users/roblou/code/vscode/src/vs/base/browser/ui/list/listView.ts:320)
ListView.onScroll (/Users/roblou/code/vscode/src/vs/base/browser/ui/list/listView.ts:453)
Emitter.fire (/Users/roblou/code/vscode/src/vs/base/common/event.ts:564)
(anonymous function) (/Users/roblou/code/vscode/src/vs/base/browser/ui/scrollbar/scrollableElement.ts:177)
Emitter.fire (/Users/roblou/code/vscode/src/vs/base/common/event.ts:562)
Scrollable._setState (/Users/roblou/code/vscode/src/vs/base/common/scrollable.ts:334)
Scrollable.setScrollPositionNow (/Users/roblou/code/vscode/src/vs/base/common/scrollable.ts:258)
AbstractScrollableElement._onMouseWheel (/Users/roblou/code/vscode/src/vs/base/browser/ui/scrollbar/scrollableElement.ts:376)
onMouseWheel (/Users/roblou/code/vscode/src/vs/base/browser/ui/scrollbar/scrollableElement.ts:312)
```

It's trying to remove index: 9 and `item.row` is null.

**Comment by joaomoreno** [comment] 2019-01-07 10:40
Yup can repro now!

**Comment by joaomoreno** [comment] 2019-01-07 14:43
I've fixed the issue and removed the `if`, so closing this.

I can still reproduce the issue in which the measurements are wrong, but I can't find anything wrong on my side. I'm very much convinced that it happens because of the 3 points in the previous comment, especially (2).

![screenshot cpma1u](https://user-images.githubusercontent.com/22350/50773601-8efcc980-1291-11e9-81f2-fe44ef7ae021.png)

I'll close this issue and create another one for you to address the widget's layout better. Let's see if it still keeps happening once you do.

**Closed** 2019-01-07 14:44 UTC
Labels: bug, tree
