### ISSUE TITLE
Resolve shell environment failed on 1.62.1

### ISSUE THREAD

**Issue by briankintz** [microsoft/vscode#136791] opened 2021-11-09 21:27 UTC
#### A possible workaround is to manually source the shell env in remote terminals
```sh
source ~/.bashrc
```

#### Another workaround is to downgrade to `1.62.0`

* configure `"update.mode": "none"` and install `1.62.0`:
* win x64: [win32-x64-user](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeUserSetup-x64-1.62.0.exe) | [win32-x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeSetup-x64-1.62.0.exe) | [win32-x64-archive](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-win32-x64-1.62.0.zip)
* win ia32: [win32-user](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeUserSetup-ia32-1.62.0.exe) | [win32](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeSetup-ia32-1.62.0.exe) | [win32-archive](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-win32-ia32-1.62.0.zip)
* win arm64: [win32-arm64-user](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeUserSetup-arm64-1.62.0.exe) | [win32-arm64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCodeSetup-arm64-1.62.0.exe) | [win32-arm64-archive](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-win32-arm64-1.62.0.zip)
* macOS: [macOS x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-darwin.zip) | [macOS arm64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-darwin-arm64.zip) | [macOS Universal](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/VSCode-darwin-universal.zip)
* Linux 64: [linux-x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/code-stable-x64-1635954380.tar.gz) | [linux-deb-x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/code_1.62.0-1635954068_amd64.deb) | [linux-rpm-x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/code-1.62.0-1635954170.el7.x86_64.rpm) | [linux-snap-x64](https://az764295.vo.msecnd.net/stable/b3318bc0524af3d74034b8bb8a64df0ccf35549a/code-stable-x64-1635954627.snap)

---

- VS Code Version: 1.62.1
- OS Version: Windows 10 21H1 / WSL2 / Ubuntu 20.10

After updating from 1.62.0 to 1.62.1, the full shell environment under WSL2 isn't loaded.

* Aliases from .bashrc work normally
* Additional configuration files like .profile are not loaded

The remote server log shows the following errors:

```
[2021-11-09 22:18:30.906] [remoteagent] [error] ptyHost was unable to resolve shell environment {}
[2021-11-09 22:18:31.090] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
```

Rolling back to 1.62.0 solves the problem

**Comment by sroby** [comment] 2021-11-09 21:56
I am having what appears to be the same issue with a SSH Remote host on the latest release. My .bashrc is sourced, but my .bash_profile no longer is. It seems the terminal no longer inherits the environment.

**Comment by briankintz** [comment] 2021-11-09 22:19
> Before updating VS Code today, I have never had this problem. (Is there any easy way to temporarily downgrade VS Code (on Windows), btw?)

1. Pick your desired OS variant from [the updates page](https://code.visualstudio.com/updates/v1_62)
2. Copy the download link
3. Paste into address bar and replace `1.62.1` with `1.62.0`
4. Press enter to download

For the Windows user installer it would be:

https://update.code.visualstudio.com/1.62.0/win32-x64-user/stable

**Comment by Taskle** [comment] 2021-11-09 23:46
WSL2 Ubuntu seems to be having some severe regressions with the release of v1.62.1 - I just filed https://github.com/microsoft/vscode/issues/136809 and I see that https://github.com/microsoft/vscode/issues/136799 is also WSL2 ubuntu-related - each seems to be issues related to SSH/connections via either the terminal or otherwise.

Hopeful someone at Microsoft can take a look soon! :)

**Comment by gabearrobo** [comment] 2021-11-10 03:14
> I am having what appears to be the same issue with a SSH Remote workspace on the latest release. My .bashrc is sourced, but my .bash_profile no longer is. It seems the terminal no longer inherits the environment.

I am having the same issue after updating VS Code to 1.62.1

**Comment by chrmarti** [comment] 2021-11-10 07:20
@alexdima This looks like a regression from the 1.62.1 fix. /fyi @aeschli

Likely duplicates: https://github.com/microsoft/vscode/issues/136814, https://github.com/microsoft/vscode/issues/136809, https://github.com/microsoft/vscode/issues/136799

**Comment by chrmarti** [comment] 2021-11-10 09:52
@deepak1556 Identified the fix in main: https://github.com/microsoft/vscode/commit/e08e4d3fe1079f6ccb1b781f6089d9e573b81ca6#diff-ba73d13771267ed61274b4094ee466e9ee2256307ae6cae5ef1161d0bfaebe67

Labelling as candidate for visibility.

**Comment by alexr00** [comment] 2021-11-10 10:22
Also impacting tasks in WSL: https://github.com/microsoft/vscode/issues/136799

**Comment by jefferai** [comment] 2021-11-10 13:39
Chiming in: took me a while to figure out why my Go setup that has been working for years suddenly wasn't working, and it's this bug; pathing sourced from `.profile` was no longer working.  Rolling back to 1.62.0 fixed my issues.

**Comment by sroby** [comment] 2021-11-10 15:53
@briankintz: Worked great, thank you!

And this indeed confirms that 1.62.1 was the culprit in my case.

**Comment by deepak1556** [comment] 2021-11-10 16:39
Fixed in https://github.com/microsoft/vscode/pull/136877

**Closed by deepak1556** 2021-11-10 16:39 UTC
Labels: bug, important, candidate, regression

**Comment by richtera** [comment] 2021-11-10 16:41
When will this go live? I had to restore 1.60 on my machine after messing around with shell setup for a long while.

**Comment by deepak1556** [comment] 2021-11-10 16:43
Verification steps:

* Install a WSL distro
* Create `~/.bash_profile` and some simple statement like `export TEST="hello"`
* Open VSCode and choose `New WSL window` from command palette
* In the WSL window terminal, `echo $TEST`
* It should print `hello`

**Comment by deepak1556** [comment] 2021-11-10 16:44
This will be available in `1.61.2` which is set to release Thursday PST this week, if there are any last minute candidates then the release will be pushed to next Tuesday PST

**Comment by richtera** [comment] 2021-11-10 16:44
That actually worked before. The problem I had was that clicking on a launch item that used npm, then that shell was not a login shell and it was trying to find npm on the windows side.

**Comment by deepak1556** [comment] 2021-11-10 16:45
@richtera can you check if the issue is present in latest insiders https://code.visualstudio.com/insiders which already contains the fix.

**Comment by richtera** [comment] 2021-11-10 16:48
@deepak1556 Ok that works. I guess both shell problems are related. Thank you.

**Comment by deepak1556** [comment] 2021-11-10 16:50
yup thanks for testing!

**Comment by briankintz** [comment] 2021-11-10 16:51
Confirmed my problems both with the shell and with tasks are fixed in the latest insiders build. Thanks @deepak1556!

**Comment by iamwwc** [comment] 2021-11-11 02:38
I guess this is the same problem https://github.com/microsoft/vscode/issues/136838

**Comment by arobertn** [comment] 2021-11-11 13:23
Argh, first time I needed to use a remote env in months and wouldn't you know it I hit this release. And the fix is coming out today even, but in a timezone after my workday is up!

**Comment by Stanzilla** [comment] 2021-11-13 02:09
What's the correct way to start a VSCode WSL instance that inherits the profile? Sometimes when I just call wsl.exe code . it does not inherit it.

**Comment by aeschli** [comment] 2021-11-15 11:43
@Stanzilla It should. Check out the WSL log for the entry `Using shell environment from invoking shell`. Setting `"remote.WSL.debug": true` will give more information about the env variables that are read and set.
Please file a new issue if it doesn't work.

**Comment by richtera** [comment] 2021-11-15 15:12
A lot of time I have to remove the code that distinguishes login and non-login shells in bashrc, otherwise some things like nvm, conda and so on won't get initialized. I think it might be worth it to review which parts of the system pass --login to bash or zsh during startup of Visual Studio Code.

**Comment by richtera** [comment] 2021-11-16 16:03
Hmmm, I am seeing this failing again in 1.62.2. My launch.json file no longer works, although everywhere else in terminal and javascript debugging terminal the environment is correct. It looks like the current version no longer opens up the terminal first so I can't see what's happening. I will enable remote.WSL.debug to see if that helps.

**Comment by richtera** [comment] 2021-11-16 16:07
Using remote.WSL.debug now shows
```sh
2021-11-16 11:05:58.260] [remoteagent] [info] Last EH closed, waiting before shutting down
[2021-11-16 11:06:01.707] [remoteagent] [info] [::ffff:172.24.192.1][ec64ed7f][ManagementConnection] New connection established.
[2021-11-16 11:06:01.711] [remoteagent] [info] [::ffff:172.24.192.1][5eb8c6ec][ExtensionHostConnection] New connection established.
[2021-11-16 11:06:01.712] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
[2021-11-16 11:06:01.717] [remoteagent] [info] [::ffff:172.24.192.1][5eb8c6ec][ExtensionHostConnection] <11294> Launched Extension Host Process.
[2021-11-16 11:06:19.201] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
```

**Comment by richtera** [comment] 2021-11-16 16:13
It works fine in the insider build
```
Version: 1.63.0-insider (user setup)
Commit: 6a25ae3a24929f35aabf8a051531c0716032e0a0
Date: 2021-11-16T05:14:38.726Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```
The failure is from this exact version.
```
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```
what's interesting is that after upgrading the insider build to the latest version the normal version started to work again.

**Comment by brybalicious** [comment] 2021-12-09 02:14
I'm on 1.63.0-insider and still getting this problem when trying to run live-server (which I installed as an npm package, not an extension) from a terminal in VSCode Insiders
