### ISSUE TITLE
Feature Request : Edit last commit message

### ISSUE THREAD

**Issue by fortinmike** [Microsoft/vscode#10846] opened 2016-08-23 15:53 UTC
I like the built-in Git support in Code, but I often need to switch back to SmartGit and the CLI for a specific feature: the ability to quickly edit the last commit message (unless already pushed), in one step.

Alternatively, it would be nice if undoing the last commit restored the commit message in the message field. It's almost the same feature, when you think about it. Might be a simple way to implement a first iteration of the feature.

**Comment by joaomoreno** [comment] 2016-08-24 07:58
Duplicate of #6190 #9796

This is already on the latest Insiders release.

**Closed by joaomoreno** 2016-08-24 07:58 UTC
Labels: duplicate

**Comment by fortinmike** [comment] 2016-08-24 12:37
Whoops, I searched only in open issues before posting. Sorry about that.

In glad to see that this will be included in the next Code release! Thanks to all involved.
