### ISSUE TITLE
Font ligatures not working properly with C and C++ syntax highlighting

### ISSUE THREAD

**Issue by SuperV1234** [Microsoft/vscode#17306] opened 2016-12-15 13:52 UTC
- VSCode Version: 1.7, 1.8, insiders
- OS Version: Windows 10, Arch Linux x64

---

Steps to Reproduce:

1. Set font to **"Fira Code"** (or any similar font which uses programming ligatures).
2. Enable ligatures with `"editor.fontLigatures": true`.
3. Write code for a lambda with trailing return type or a `->` access to a method.
4. The ligatures are not expanded correctly *(see screenshot below)*.

![incorrect ligatures with C++ syntax highlighting](http://i.imgur.com/BfAZujZ.png)

---

Setting the syntax to **"Plain Text"** makes the ligatures work correctly.

![correct ligatures with Plain Text syntax highlighting](http://i.imgur.com/kXMJc1J.png)

---

*(This also applies to other ligatures, not only `->`.)*

*(This also applies to C syntax highlighting.)*

**Comment by siegebell** [comment] 2016-12-15 14:54
This is a partial duplicate of #2870 - the C++ grammar is parsing `-` and `>` into separate tokens. If you are using a built-in grammar for C++, you should make a feature request to have `->` and other operators parsed as one token.

Or you can use [prettify-symbols-mode](https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode) - see [this thread](https://github.com/tonsky/FiraCode/issues/211) for a discussion on how to make it work for Fira Code.

**Comment by siegebell** [comment] 2016-12-15 14:58
Actually, I think this is a bug in the built-in C++ grammar. Commit 5598ee0 should be merging the two tokens, but while `-` is given scope `keyword.operator.c`, the grammar incorrectly assigns `>` scope `keyword.operator.comparison.c`.

**Comment by siegebell** [comment] 2016-12-15 15:52
related: atom/language-c#177

**Comment by aeschli** [comment] 2017-01-30 21:16
Thanks @siegebell for the analysis.
Closing as dup of atom/language-c#177

**Closed by aeschli** 2017-01-30 21:16 UTC
