### ISSUE TITLE
Settings editor TOC uncomfortably small

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145274] opened 2022-03-17 00:03 UTC
Tight fit here, and I can't make it larger. 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/8586769/158711071-1c29cdb3-0cf4-47bc-8fbd-b5bf6ca53143.png">

**Comment by rzhao271** [comment] 2022-03-17 02:03
Duplicate of https://github.com/microsoft/vscode/issues/145243

**Closed** 2022-03-17 02:04 UTC
Labels: *duplicate
