### ISSUE TITLE
The new terminal 

### ISSUE THREAD

**Issue by howardchn** [Microsoft/vscode#7303] opened 2016-06-07 07:36 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. ctrl + ` to open terminal view.
2. type "cls" then press "enter" key; the terminal displays not right.

**Comment by Tyriar** [comment] 2016-06-07 07:40
Duplicate of https://github.com/Microsoft/vscode/issues/6735

**Closed by Tyriar** 2016-06-07 07:40 UTC

**Comment by howardchn** [comment] 2016-06-07 07:44
Cool, thanks.
