### ISSUE TITLE
Bracket Pair Colorization does not work with begin / end

### ISSUE THREAD

**Issue by yurim108** [microsoft/vscode#133333] opened 2021-09-17 15:10 UTC
Issue Type: <b>Bug</b>

Create Test.al file and paste this code to test colorization of "begin" and "end":

```
codeunit 50108 Bracketing
{
    procedure TestBrackets()
    var
        i: Integer;
    begin
        if i = 0 then begin
            i := 1;
        end else begin
            i := 2;
        end;
        IsPending();
    end;

    procedure IsPending(): Boolean
    begin
        exit(true);
    end;
}
```

![grafik](https://user-images.githubusercontent.com/70197815/133805675-4bd6faa8-2d41-43b7-acb9-8cfbfef31b58.png)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.07GB free)|
|Process Argv|--crash-reporter-id 2dfe6807-7da9-4cf2-9aef-c4193b9304ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|3.0.16
al-toolbox|Bar|2.0.14
replacerules|bhu|0.4.1
al-codeactions|dav|1.0.7
githistory|don|0.6.18
gitlens|eam|11.6.0
todo-tree|Gru|0.0.214
rest-client|hum|0.24.5
al-test-runner|jam|0.6.0
al-object-designer|mar|0.2.4
vscode-docker|ms-|1.16.1
al|ms-|7.4.502459
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell|ms-|2021.9.0
snippet-creator|nik|0.0.5
createGUID|nwa|0.0.2
al-var-helper|ras|2.4.0
xliff-sync|rva|1.2.0
cosmo-azure-devops|tfe|0.11.35
vjeko-al-objid|vje|1.2.1
al-extension-pack|wal|1.0.14
crs-al-language-extension|wal|1.4.11
al-navigator|wbr|0.4.6

</details>

**Comment by hediet** [comment] 2021-09-18 14:49
Duplicate of #132162

**Closed** 2021-09-18 14:49 UTC
Labels: *duplicate
