### ISSUE TITLE
[simple-browser] support previewing local files

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#120820] opened 2021-04-08 11:19 UTC
Right now one is capable to preview URLs, but it would be nice if the simple browser can also resolve local files, i.e. right click on HTML and then preview. Supporting live reloading of local file on change would be nice too.

**Comment by akosyakov** [comment] 2021-04-08 11:34
I found https://open-vsx.org/extension/ritwickdey/LiveServer but I looks involving from user perspective. Simple browser being webview should be able already to load local content without starting an additional server?

**Comment by mjbvz** [comment] 2021-04-08 15:30
Duplicate of #12080

**Closed by mjbvz** 2021-04-08 15:30 UTC
