### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 4ms22251** [microsoft/vscode#79105] opened 2019-08-14 10:00 UTC
i can't download or install any extensions neither as vsix or from the editor itself.

- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.10240

![vscode](https://user-images.githubusercontent.com/48655708/63012622-d7fda780-be8a-11e9-8797-f32bf355d868.PNG)

**Comment by 4ms22251** [comment] 2019-08-14 10:03
> (Experimental duplicate detection)
when i try to download extensions manually the vsix files don't download completely.

**Comment by 4ms22251** [comment] 2019-08-14 10:04
can anyone help?

**Comment by gjsjohnmurray** [comment] 2019-08-14 10:22
/duplicate of #78783. Maybe you have a DNS issue.

Also, please use a more descriptive title on any future issues you create.

**Closed** 2019-08-14 10:22 UTC
Labels: *duplicate

**Comment by 4ms22251** [comment] 2019-08-14 10:37
> /duplicate of #78783. Maybe you have a DNS issue.
> 
> Also, please use a more descriptive title on any future issues you create.

i can search for the extensions but can't install any

**Comment by gjsjohnmurray** [comment] 2019-08-14 10:52
Are you willing to install the [Insiders build of VSCode](https://code.visualstudio.com/insiders/) alongside your current version? If yes, can you add extensions to it?
