### ISSUE TITLE
Cursor point to opposite direction when mouseover line number

### ISSUE THREAD

**Issue by sebdoucet** [microsoft/vscode#90829] opened 2020-02-17 14:34 UTC
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Activate line number on editor
2. Mouseover a line number

The arrow pointer is oriented to the left but should be oriented to the right as it was previously and expected due to the line selection when you click on the line number.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-02-17 15:03
Duplicate of #90707

**Closed** 2020-02-17 19:56 UTC
Labels: *duplicate
