### ISSUE TITLE
Long Token Foreground Make Token Inspect Invisible

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode#95416] opened 2020-04-16 07:38 UTC
![image](https://user-images.githubusercontent.com/24700207/79427425-56d45280-7fcd-11ea-8cdc-adc1214bd48e.png)

As you can see we can't see the semantic token type etc.. There should be a vertical scroll bar.

Steps to reproduce:

1) Enable "Developer: Inspect Editor Tokens and Scopes".
2) Type some token which has long description (typically foreground). For my screen TypeScript's `Number` is enough with semantic highlighting enabled.
3) You can't see the token type and some others property.

A simple fake solution will be to left-align the properties (instead of the current right-alignment) so the most are visible even when there are some long ones. Another solution will be to enable overflow, but that'll be hard since often there are not spaces so we don't have hints where to break line.

That happens for many tokens (on my laptop's screen) such as `Promise` and more, since the CSS selectors in "foreground" are usually big.

**Comment by aeschli** [comment] 2020-05-07 11:44
duplicate of #95936

**Closed by aeschli** 2020-05-07 11:44 UTC
