### ISSUE TITLE
Duplicate Paste in Jupyter Notebooks

### ISSUE THREAD

**Issue by massgh** [microsoft/vscode#102389] opened 2020-07-13 14:20 UTC
We have written the needed dat
Issue Type: <b>Bug</b>

When I do Ctrl + V, it pastes double in a jupyter notebook, it means it invokes systems paste and has its own paste options. How to keep only one paste working.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
python-preview|don|0.0.4
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-reveal|evi|4.0.3
matlab|Gim|2.0.0
fortran-ls|han|0.6.2
htext|Hun|1.4.1
latex-workshop|Jam|8.11.1
kite|kit|0.119.0
rainbow-csv|mec|1.7.0
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.7.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
code-settings-sync|Sha|3.4.3
python|tht|0.2.3
latex-support|tor|3.2.0
vscodeintellicode|Vis|1.2.9
txt-syntax|xsh|0.0.4

</details>
a into your clipboard because it was too large to send. Please paste.

**Comment by ArturoDent** [comment] 2020-07-13 17:44
probable duplicate of #101946

**Comment by mjbvz** [comment] 2020-07-13 18:36
Duplicate of #101946

**Closed by mjbvz** 2020-07-13 18:36 UTC
Labels: new release
