### ISSUE TITLE
go to symbol does not seem to recognize the methods of the vue file.

### ISSUE THREAD

**Issue by richex-cn** [microsoft/vscode#104087] opened 2020-08-05 15:48 UTC
- VSCode Version: 1.47.3
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Press Ctrl+Shift+O in `.vue` file.
2. Input function name.
3. Can not match any methods.

Does this issue occur when all extensions are disabled?: Yes

![20200805_233931](https://user-images.githubusercontent.com/25103518/89434410-17956180-d776-11ea-908c-ccce467f334b.png)

**Comment by IllusionMH** [comment] 2020-08-05 16:18
/causedByExtension

Functionality for `.vue` files provided by extension. Looks like duplicate of https://github.com/vuejs/vetur/issues/2058

**Closed** 2020-08-05 16:19 UTC
Labels: *caused-by-extension
