### ISSUE TITLE
Theme settings should be stored in user.json

### ISSUE THREAD

**Issue by djui** [Microsoft/vscode#10674] opened 2016-08-18 19:42 UTC
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: OS X/macOS 10.11.6 (15G31)

Steps to Reproduce:
1. Set theme
2. Check configuration files

Storing the selected theme in the `storage.json` is a bad idea for several reasons:
- `storage.json` seem to be meant to store temporary and local **state**.
  - The set theme can hardly be seen as neither temporary, not local state.
- Trying to make a sensible backup of settings is confusing, unncessarily hard, and error prone
  - To make a sensible backup, one has to (1) backup `/Users/abc/Library/Application Support/Code/storage.json` for the theme, (2) `$HOME/Library/Application Support/Code/User/*` for the _actual_ preferences, (3) `~/.vscode/*` for extensions. Spreading these out over multiple places is not the moment of least surprise.
  - Trying to make a sensible backup of settings can accidentally leak non-disclosable information. `storage.json` contains many file paths which potentially expose undesired information for the public. There is no easy way to just extract settings from that file that are not "recently used files" or "window locations".

Additionally, `workspaceStorage` should not be in `$HOME/Library/Application Support/Code/User` but rather in `/Users/abc/Library/Application Support/Code`. It follows the same criteria as `/Users/abc/Library/Application Support/Code/storage.json`.

**Comment by bpasero** [comment] 2016-08-19 07:18
I agree. @aeschli also fyi

I think as soon as we can programmatically change user.json via API we should consider to store the theme in settings.

**Comment by djui** [comment] 2016-08-19 07:25
Apologies if I sounded hard; I just reread my own post. It was meant as constructive critique for future work to make this the best editor experience possible, not https://xkcd.com/386/

**Comment by Jackbennett** [comment] 2016-12-06 11:10
related/duplicate of #7358 ?

**Comment by aeschli** [comment] 2016-12-06 13:37
correct. That's a dup of #7358

**Closed by aeschli** 2016-12-06 13:37 UTC
Labels: feature-request, workbench
