### ISSUE TITLE
VSCode file open dialog box does not respect display scaling from remote session

### ISSUE THREAD

**Issue by erbrown481** [microsoft/vscode#109254] opened 2020-10-23 17:41 UTC
Issue Type: <b>Bug</b>

1) Start from a host computer with > 100% display scale (e.g., 4K display)
2) Use remote desktop on host computer to connect to a second computer.
3) On second computer, start VSCode.
4) From VSCode, File/Open

Expect: To see properly scaled File/Open dialog

Actual: File/Open dialog is very small.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.21242

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (12.27GB free)|
|Process Argv|--crash-reporter-id 367f4029-8e58-4f78-862b-ae0609c27fbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
devinsights|Mic|2020.10.14-1
tdpcode|Mic|1.4.1
vscode-nmake-tools|Mic|3.0.200904004
sarif-viewer|MS-|3.2020.430009-insiders
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1

</details>

**Comment by alexr00** [comment] 2020-10-26 10:34
duplicate of https://www.github.com/microsoft/vscode/issues/89867

**Closed** 2020-10-26 10:34 UTC
Labels: *duplicate
