### ISSUE TITLE
Debug Console: can't copy paste, neither select all text, selection is lost while scrolling

### ISSUE THREAD

**Issue by darknessm0404** [Microsoft/vscode#1737] opened 2016-01-02 01:01 UTC
Tested with nodejs latest version and visual code latest december 2015 version:
While logging with console.log, we can't scroll AND select text, and we don't have the option to copy paste all the text.

**Comment by bpasero** [comment] 2016-01-03 12:01
This might be a dupe of a feature request.

**Comment by isidorn** [comment] 2016-01-04 09:19
Dup of #112

**Closed by isidorn** 2016-01-04 09:19 UTC
Labels: bug, debug
