### ISSUE TITLE
[Bug] TypeScript: Auto Completion List Omits Local Variables (vscode 1.79.2, typescript 5.1.3)

### ISSUE THREAD

**Issue by sinclairzx81** [microsoft/vscode#186134] opened 2023-06-26 06:31 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows 10
- TypeScript 5.1.3 (Works ok in 5.0.4)

Steps to Reproduce:

1. Specify a local variable in TypeScript
2. On next line, type the name of that variable
3. Observe that variable name does not show in code completion list.

### Screenshot

![image](https://github.com/microsoft/vscode/assets/3048342/1d41939a-1c95-4f16-9471-74e2fcf742dc)

### Expected

Local variable names should show first in auto complete list as typing the name of local variables results in autocomplete selecting invalid names. 

### Notes

This issue seems specific to TypeScript `5.1.3` (which is the default when installing vscode `1.79.2`). I have disabled all extensions as well as reinstalled vscode to try and rule out any configuration error. While the auto complete doesn't seem to list local variables, it does work when dotting `.` into the variable and listing its members.

Installing TypeScript `5.0.4` and selecting this version for the language service seems to resolve the issue (if this is helpful for a interim fix)

![image](https://github.com/microsoft/vscode/assets/3048342/19bbb29a-f508-4917-8403-a4e34c4a70e8)

**Comment by mjbvz** [comment] 2023-06-26 15:12
Duplicate of https://github.com/microsoft/TypeScript/issues/54654

**Closed by mjbvz** 2023-06-26 15:12 UTC
