### ISSUE TITLE
Custom Editor Webview Reloads When Dragged To Different Editor Group

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#166859] opened 2022-11-21 14:15 UTC
Notice how the custom editor reloads when the webview is dragged around (this is not a diff editor, but a custom one that visualizer a serialized diffing result for fixture tests):

Code_-_Insiders_K070Kkr3Vp.gif
![Code_-_Insiders_K070Kkr3Vp](https://user-images.githubusercontent.com/2931520/203076342-5755f7e1-2f10-4512-8249-e0a58232da66.gif)

For simple webviews, this has been fixed by https://github.com/microsoft/vscode/pull/114093:

Code_-_Insiders_cw5EXdmvco.gif
![Code_-_Insiders_cw5EXdmvco](https://user-images.githubusercontent.com/2931520/203076613-a80065a0-a802-4d3c-a2a7-203651ada014.gif)

**Comment by mjbvz** [comment] 2022-11-29 00:17
Duplicate of #86146

**Closed by mjbvz** 2022-11-29 00:17 UTC
