### ISSUE TITLE
Keyboard accessibility: Strange behavior when focusing item after text editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3373] opened 2016-02-23 22:16 UTC
#3246

When tab focus mode is on, doing the following:

- Select text editor
- Press <kbd>tab</kbd>
- At this point I have no idea what is focused as I can't see anything on the UI with a border.
 - Pressing <kbd>enter</kbd> will add a new line where the cursor was, pressing <kbd>enter</kbd> again will not add another line
 - Pressing <kbd>enter</kbd> will add a new line, pressing <kbd>backspace</kbd> and <kbd>enter</kbd> will add another new line

**Comment by alexandrudima** [comment] 2016-02-24 09:02
@Tyriar Can you please get the workbench in the same state as you had (the tab order is dependent on what you have opened) and open the developer tools and run this snippet:

```javascript
setInterval(function() { console.log(document.activeElement); }, 1000);
```

This will print every second the DOM element where the focus is. We then need to figure out who owns that elements and why there's no focus indication on it.

**Comment by Tyriar** [comment] 2016-02-24 19:51
It's focusing body:

```html
<body class="monaco-shell vs-dark vscode-theme-colorful-defaults-themes-dark_plus-tmTheme">
```

Immediately after the `textarea`.

**Comment by alexandrudima** [comment] 2016-02-25 08:47
Duplicate of #2327

**Closed by alexandrudima** 2016-02-25 08:47 UTC
Labels: bug, needs more info
