### ISSUE TITLE
Live Sass: Watch Sass link missing

### ISSUE THREAD

**Issue by turkishkitten** [microsoft/vscode#118567] opened 2021-03-09 18:11 UTC
My extensions are enabled for Live sass converter and live server but it is not showing up on my bar or anywhere and when  I look for it this is what it says. 

Command 'Live Sass: Watch Sass' resulted in an error (command 'liveSass.command.watchMySass' not found) IT world so any help is greatly appreciated. 
There is no Watch my sass to click either. 
Thanks Bonnie

**Comment by aeschli** [comment] 2021-03-10 08:55
Can you file this against the Live SASS extension?

Maybe it's a duplicate of https://github.com/ritwickdey/vscode-live-sass-compiler/issues/330

**Closed by aeschli** 2021-03-10 08:55 UTC

**Comment by turkishkitten** [comment] 2021-03-11 16:00
Well you closed my issue  Aeschli without solving the problem so I'm not sure what your solution is but the issue was live server Ritwikety dey extension is not being managed anymore so the current update doesn't work. I am using an older version and now everything is working.

**Comment by aeschli** [comment] 2021-03-11 16:09
I closed it as the fix needs to happen in the extension. I commented about the fix in  ritwickdey/vscode-live-sass-compiler#330.

This issue tracker is for issues in Visual Studio Code.
