### ISSUE TITLE
Editor service should not create untitled editors before overrides

### ISSUE THREAD

**Issue by abrasaxdeity** [microsoft/vscode#106012] opened 2020-09-03 07:13 UTC
Add a command to the existing custom editor sample extension

`{
	"command": "catCustoms.catScratch.new",
	"title": "Create new Cat Scratch Document",
	"category": "Cat Scratch"
}`

register command in extension.ts

`vscode.commands.registerCommand('catCustoms.catScratch.new', () => {
	vscode.workspace.openTextDocument({ language: 'catScratch', content: '' }).then(doc => {
		vscode.commands.executeCommand("vscode.openWith", doc.uri, "catCustoms.catScratch");
	});
});`

1. Open command palette and select Create new Cat Scratch Document - Untitled-1 tab opens
2. Close opened editor
3. Repeat 1. - Untitled-2 opens

Bug is in step 3, since Untitled-1 was previously closed name should be free for the new untitled file

**Comment by bpasero** [comment] 2020-09-03 07:47
I saw this recently and forgot to follow up: there is an easier repro for this and I think somewhere when custom text editors were added, we forgot to deal with untitled models properly. I think they are not getting freed up.

**Steps:**
* revert my change in https://github.com/microsoft/vscode/commit/7686b52a823e231dacda4e86d86932998cafab19
* run out of sources
* select File > New File
* you should get a picker to pick an editor
* click `ESC` to close picker
* repeat

=> 🐛  you see `Untitled-2` and this continues

![recording (2)](https://user-images.githubusercontent.com/900690/92086420-73312a00-edca-11ea-99b2-c68ba5fbb7f1.gif)

**Comment by bpasero** [comment] 2021-03-19 06:53
@lramos15 I think this will be part of your work: with the new override handling moving out of the editor group I think this should be fixed as well because we will no longer create an untitled editor input before the override has happened 👍

**Comment by lramos15** [comment] 2021-03-31 17:56
Optimistically closing. I wasn't able to get the repro steps above to work, but when I create new untitled files with the hex editor the number no longer increments.

**Comment by roblourens** [comment] 2021-04-29 16:49
I repro this with the original steps

**Comment by lramos15** [comment] 2021-05-06 15:35
@bpasero or @mjbvz I think I need some help with this one, I'm not sure where these models are getting created / why they're sticking around. I don't really see this else where just in this particular open flow.

**Comment by bpasero** [comment] 2021-05-06 15:39
Untitled text models typically get created through the [`IUntitledTextEditorModelManager.create`](https://github.com/microsoft/vscode/blob/df6d78a1695bdf9a1d4984231242ff1fd65247bb/src/vs/workbench/services/untitled/common/untitledTextEditorService.ts#L91-L93) method, but in theory you can also ask the `IEditorService#createEditorInput` method to create a untitled editor input with associated model for you when you pass in no resource and give contents in the arguments. 

I am not sure where in custom editor land untitled files are created.

**Comment by lramos15** [comment] 2021-05-06 19:34
It seems like openTextDocument creates a model, and then openWith creates a second one. I fixed properly disposing the openWith model here https://github.com/microsoft/vscode/commit/9f32d376b02dfcffa3e70d316d0f95524aea4c55 (At least I think, I'm not sure if it's expected that the editor input would be disposed in this service). However, I have no way to handle the openTextDocument model disposing as that isn't handled by the editor service flow. Seems like this feature request might cleanup this flow https://github.com/microsoft/vscode/issues/93441

**Comment by bpasero** [comment] 2021-05-07 06:47
I would argue that it should be the `IEditorService` that creates `EditorInput` from the untyped ones and that one should properly be disposed if it gets overridden by the editor override service. We are probably not there yet because we still allow someone to pass in an `EditorInput` to the `IEditorService` and then have questionable lifecycle issues.

As soon as everyone only uses untyped editor inputs, the lifecycle is a lot clearer and owned only by editor service and editor override service.

**Comment by bpasero** [comment] 2021-05-21 10:37
I have renamed the issue. I think https://github.com/microsoft/vscode/issues/121101 would probably fix this. The gist is that we should stay away from creating `UntitledTextEditorInput` in the editor service before the overrides because it is possible that an override kicks in and then the untitled text editor was created for no good reason and possibly leaks.

**Comment by bpasero** [comment] 2021-07-07 11:59
I think this can be closed?

**Comment by rzhao271** [comment] 2021-07-07 17:34
I can still reproduce the issue with the original steps.

**Comment by lramos15** [comment] 2021-07-07 19:28
Ah the steps aren't the same since custom editors don't properly implement the untitled factory yet. I'm not sure the best way to verify this @bpasero but I know it no longer creates the untitled input.

**Comment by bpasero** [comment] 2021-07-08 05:33
This should be the steps:
* install GH issue extension notebook
* from command line start vscode on a *.github-issues file that does not exist
* it should open a issue notebook editor
* close that
* File > New File
* it should be "Untitled-1"

**Closed** 2021-07-08 15:12 UTC
Labels: bug, workbench-editor-override, workbench-untitled-editors
