### ISSUE TITLE
VS Code window terminated unexpectedly (reason: 'crashed', code: '-1073741818')

### ISSUE THREAD

**Issue by s4shivam** [microsoft/vscode#189954] opened 2023-08-08 17:32 UTC
Description:

I decided to open VS Code in my old system after few months and VS Code decided that it doesn't want to. I am getting the below error:
the window terminated unexpectedly( reason: 'crashed', code: '-1073741818')
I have attached the screenshot as well. I've reinstalled it multiple times after reboot and before reboot.

Steps to Reproduce:
    1. Open VS Code.
    2. The window will terminate unexpectedly with the error message.

Expected Behavior:
VS Code should open and start without any errors.

Actual Behavior:
VS Code crashes with the error message.

Reproducible:
The issue is reproducible on my machine.

Environment:
    - OS: Windows 10  / 22H2 / 19045.3086
    - VS Code version: 1.81.0.0 (old version is unknown)
    - Extensions: unknown
    
Additional Information:
I have tried the following troubleshooting steps, but none of them have worked:
     - Reinstalling VS Code
     - Rebooting my machine

I am still not able to open VS Code. I would appreciate any help that can be provided to resolve this issue.

Screenshot:
![VS_Code_Error_1073741818](https://github.com/microsoft/vscode/assets/43890874/8c34e11f-0267-4db2-ac3b-c34eee84add1)

**Comment by alexr00** [comment] 2023-08-09 22:46
@s4shivam did you try the "New Window" button?

**Comment by s4shivam** [comment] 2023-08-10 15:18
Hi @alexr00 ,
I did click on "New Window" button but nothing seems to be happening after that.
Code.exe process ends automatically in the task manager

**Comment by s4shivam** [comment] 2023-08-10 15:20
Hi @alexr00 ,
I did click on "New Window" button but nothing seems to be happening after that.
The code.exe process ends automatically in the task manager

**Comment by alexr00** [comment] 2023-08-10 15:58
Thanks for confirming @s4shivam. Can you create and share a crash report as described in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report?

**Comment by s4shivam** [comment] 2023-08-11 14:13
I ran the command mentioned in the [wiki](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report) and it generated two directories and two files:

- attachments directory: This directory was empty.
- reports directory: This directory contained the `*.dmp` file.
- metadata file.
- setting.dat file.

I am attaching all of what was generated.

_Additionally, I would like to report that after running `code --crash-reporter-directory <absolute-path>` the VS code got launched and then it crashed with the same error for which I had raised this issue._

[VS Code-1073741818.zip](https://github.com/microsoft/vscode/files/12322227/VS.Code-1073741818.zip)

**Comment by deepak1556** [comment] 2023-08-25 03:32
Thanks for the crash logs, can you check if the issue repros when launching with a new user data directory using the following cli flags `code --user-data-dir C:\Users\<Replace with Valid path>\AppData\Local\Temp\CodeCrashTest`

**Comment by s4shivam** [comment] 2023-08-25 09:12
I was able to install a previous version(**1.50.1**) of VS code and then updated it into the latest version(**1.81.1**) without any issue. VSC is working fine now.

**Comment by deepak1556** [comment] 2023-08-25 10:28
Thanks for confirming, the original crash pointed to an issue with bad font cache hence I was asking to try with a new user data directory. Good to know that the issue is resolved with update.

**Closed by deepak1556** 2023-08-25 10:28 UTC
Labels: info-needed
