### ISSUE TITLE
I find a bug when i formatter my code

### ISSUE THREAD

**Issue by weichunren** [Microsoft/vscode#39003] opened 2017-11-23 03:40 UTC
At somewhere else is no problem,only on this code:

    <script type="text/javascript" charset="utf-8" src="__PUBLIC__/ue/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="__PUBLIC__/ue/ueditor.all.min.js"> </script>
    <script type="text/javascript" charset="utf-8" src="__PUBLIC__/ue/lang/zh-cn/zh-cn.js"></script>

When i  press down alt+shift+f, the second line code has been deleted,
this bug only in this file.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.3
crane|Hvy|0.3.8
phpcs|ika|0.7.0
search-node-modules|jas|1.2.0
php-cs-fixer|jun|0.1.47
ftp-sync|luk|0.3.3
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment] 2017-11-23 04:41
@weichunren 
Can you give a bit more information, a quick try with VSC 1.18.1 on Windows 7 using your three lines of code, I was not able to reproduce.

- Are the three lines of code the complete file?
- I am assuming this is in HTML file, yes?
- have you tried disabling all extensions?
- Do you possibly have conflicting Keybindings, check all assignments for conflicts.

**Comment by aeschli** [comment] 2017-11-23 09:29
I'm not able to reproduce either. Make sure all extensions are disaled.

**Comment by weichunren** [comment] 2017-11-24 02:06
Yes,this file is html.
Just now i has test it in my other pc, it 's no problem.
And i found a space in my code, when i delete the space ,then  i formatter my code is no problem.
I think the bug is because the space.

Two lines of code is different from a space.
before:
<script type="text/javascript" charset="utf-8" src="__PUBLIC__/ue/ueditor.all.min.js"> </script>
after:
<script type="text/javascript" charset="utf-8" src="__PUBLIC__/ue/ueditor.all.min.js"></script>

**Comment by shizengzhou** [comment] 2017-11-27 04:50
I  reproduce.
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.0
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.11.1
vscode-icons|rob|7.18.1



---
<img width="571" alt="format1" src="https://user-images.githubusercontent.com/24318019/33251367-1fea2b60-d371-11e7-91ed-41eaba491229.PNG">
<img width="571" alt="format2" src="https://user-images.githubusercontent.com/24318019/33251377-2a12baee-d371-11e7-8f65-7c23b6884ef0.PNG">

Steps to Reproduce:

1.  press down alt+shift+f to format the code
2.


Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-11-27 07:43
@shizengzhou Please paste the full example code here

**Comment by shizengzhou** [comment] 2017-11-27 08:41
@aeschli 
[test.zip](https://github.com/Microsoft/vscode/files/1505131/test.zip)

**Comment by aeschli** [comment] 2017-11-30 11:58
Thanks @shizengzhou, now I can reproduce in 1.18.1.
It's fixed in 1.19

**Closed by aeschli** 2017-11-30 11:58 UTC
Labels: html, needs more info

**Comment by aeschli** [comment] 2017-12-01 08:57
(duplicate of #36574)
