### ISSUE TITLE
Glitch on window with Remote-WSL Enabled

### ISSUE THREAD

**Issue by ashwinkumar1211** [microsoft/vscode#106365] opened 2020-08-24 11:37 UTC
BUG: Glitch on VSCode window with Remote-WSL Extension Enabled for Ubuntu 18.04 (Remote), Windows 10 (Local) 

- VSCode Version: 1.48.1
- Local OS Version: Windows 10 2004 OS Build : 19041.450
- Remote OS Version: Ubuntu 18.04 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Enable Microsoft Remote-WSL Extension
2. Scroll anywhere on the VScode Window

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

PS: Please Ignore the inside elements on the window. It is meant for showing the issue clearly

![Issue - WSL](https://user-images.githubusercontent.com/34165254/91040585-214f0e00-e62c-11ea-9d13-0e493ce17483.png)

**Comment by deepak1556** [comment] 2020-09-09 20:31
Duplicate of https://github.com/microsoft/vscode/issues/103673

You can disable hw acceleration for a workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Couple of details that would be helpful for further investigation,

* Does this issue repro with latest insiders https://code.visualstudio.com/insiders/ 

* Can you try https://vscode-web-test-playground.azurewebsites.net/ on chrome or edge and see if the issue persists.

* Paste the output of either `edge://gpu` from edge browser or `chrome://gpu` from chrome

* Attach the following profile.
  * Open window devtools
  * Go to performance tab
  * Enable advanced paint instrumentation under settings
  * Click start profiling and reload page icon
  * Hover the mouse into affected areas which causes the blur to go away
  * Download the profile

**Closed** 2020-09-17 11:23 UTC
Labels: gpu, needs more info, windows
