### ISSUE TITLE
Layout problems with bidirectional text lines

### ISSUE THREAD

**Issue by owenblacker** [microsoft/vscode#91074] opened 2020-02-20 12:00 UTC
- VSCode Version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
- OS Version: Windows_NT x64 10.0.16299
- OS locale: en-GB (British English)
- Does this issue occur when all extensions are disabled?: Yes
- Does this issue occur in the Insiders build?: Yes

I've just come across a bug in how VS Code handles bidi text on Windows. First off it gets it wrong in one way, but then it changes the display order to get it wrong in a whole different way when I triple-click to select the line.

The logical order of the text is _Hebr1 Hebr2 Hebr3 Latn1 Hebr4 Hebr5 Hebr6_. which should display RTL, with word Latn1 between Hebr3 (to the right) and Hebr4 (to the left), Hebr1 at the start (right) and Hebr6 at the end (left).

To start with, VS Code shows me the text in chunks, with chunks internally in the correct direction and the chunks in logical order: [Hebr3 Hebr2 Hebr1] [Latn1] [Hebr6 Hebr5 Hebr4]. But triple-click and I get each word internally in the correct direction (so _1rbeH_, as it were) but with the words in logical order (so _1rbeH 2rbeH 3rbeH Latn1 4rbeH 5rbeH 6rbeH_).

This behaviour occurs both if the bidi text is within a larger HTML file (surrounded by LTR text) or alone in a file (so just bidi text, mainly RTL, in an LTR operating system).

Steps to Reproduce:

1. Create a file that includes a line reading
                                                   אורך צילום הווידאו עד כ-5 דקות. גודל הקובץ: 1 דקה \ 600MB.
   This is 2 sentences:
   > אורך צילום הווידאו עד כ-5 דקות.
  and
   >  ‏גודל הקובץ: 1 דקה \ ‎600MB.
2. Triple click to select the whole line and it shows each word in order, with the line displaying LTR, with each word in its correct direction.

As an aside, the text order when selected might be deliberate — it could be considered a solution to issue https://github.com/microsoft/vscode/issues/83365

These screenshots show the bidi text when unselected, selected and on the page (in that order). There are 2 examples, 1 of text inside `<p> ... </p>` tags (attached as [Bidi text paragraph.html.txt](https://github.com/microsoft/vscode/files/4230566/Bidi.text.paragraph.html.txt)) and 1 of text alone on a line (attached as [Bidi text line.txt](https://github.com/microsoft/vscode/files/4230563/Bidi.text.line.txt)). In both cases, the screenshot from a browser (the non-monospaced font) is the correct word order for a user to read, and both screenshots from VS Code (monospaced) are incorrect in the ways described above. (The fonts are Open Sans Hebrew and Cousine.)

![Bidi text paragraph unselected](https://user-images.githubusercontent.com/376642/74931068-d501e780-53d6-11ea-996d-48ea564e1f4e.png)
![Bidi text paragraph selected](https://user-images.githubusercontent.com/376642/74931072-d6cbab00-53d6-11ea-8dc6-5c918769037c.png)
![Bidi text paragraph on page](https://user-images.githubusercontent.com/376642/74931073-d7fcd800-53d6-11ea-8370-1da7e9cece0f.png)

![Bidi text line unselected](https://user-images.githubusercontent.com/376642/74931080-d9c69b80-53d6-11ea-9273-d70f5f093a11.png)
![Bidi text line selected](https://user-images.githubusercontent.com/376642/74931087-db905f00-53d6-11ea-9d69-f31f64b7135a.png)
![Bidi text line on page](https://user-images.githubusercontent.com/376642/74931092-dcc18c00-53d6-11ea-9aa6-508f88598067.png)

**Comment by jgwl** [comment] 2020-03-27 16:39
This can also be reproduced by just highlighting any space character within the sentence. You can get it to jump back and forth by drag-selecting with the mouse, or shift-arrowkey-selecting. 
This was working previously to 1.42; I believe it's an introduced bug since then.

**Comment by alexdima** [comment] 2020-03-30 08:52
Duplicate of #90019

**Closed by alexdima** 2020-03-30 08:52 UTC
Labels: editor-rendering, feature-request
