### ISSUE TITLE
Support parsing recursive make build output messages from tasks.json

### ISSUE THREAD

**Issue by alessandrod** [microsoft/vscode#11663] opened 2016-09-08 03:10 UTC
- VSCode Version: master
- OS Version: any

I've been using vscode for a couple of days and I'm loving it. I'm a GStreamer (http://gstreamer.freedesktop.org) developer and I would like to be able to build gst with vscode.

GStreamer uses recursive make to build itself. The way it works is that you run make at the root of the project and then make descends in the nested directories and builds the files contained in them (I'm simplifying but that's the gist).

Here's what the build output looks like:

```
alessandro@june:~/src/gst1/head/gst-plugins-bad$ make --print-directory
make: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
make[1]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad'
Making all in gst-libs
make[2]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad/gst-libs'
Making all in gst
...
```

And here's what a build error looks like:

```
make[2]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad/sys'
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C applemedia
make[3]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad/sys/applemedia'
  CC       libgstapplemedia_la-vtdec.lo
vtdec.c:38:1: error: unknown type name 'FOO'
FOO
^
```

So as you can see the error references a relative filename (vtdec.c) and earlier in the output there's a line specifying in which directory the file is located (/Users/alessandro/src/gst1/head/gst-plugins-bad/sys/applemedia).

vscode already supports relative filenames in problem matchers by letting users specify a static filePrefix to be prefixed to filenames. I'm proposing to add a method for problem matchers to modify the filePrefix as they scan build output.

**Comment by alessandrod** [comment] 2016-09-08 03:15
Here's the tasks.json that I can use to parse the output https://gist.github.com/alessandrod/82f08750ee4c36860b3719765ad6140f

**Comment by dbaeumer** [comment] 2016-10-14 15:35
I looked at the PR and your problem and this is not solvable that way in a general way. The problem is that multi line matchers can only loop on the last match right now. They are made to loop over matches for a single file where usually the first line of the match is the file to be compiles and then all following lines contain errors.

I your case a matcher with the line prefix patch will only be able to match one error in a directory. If you have something like this:
```
make[3]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad/sys/applemedia'
  CC       libgstapplemedia_la-vtdec.lo
vtdec.c:38:1: error: unknown type name 'FOO'
  CC       libgstapplemedia_la-other.lo
other.c:38:1: error: unknown type name 'OTHER'
```
then that second error will not be matched because the pattern for the file prefix will not match anymore. 

The only solution I can think about right now is to have a file location matcher which people could specify of a matcher that looks backwards in the output. The backwards looking I actually want to avoid. This gets pretty complicated and requires that we always keep the whole output.

Is it ok to close the PR. If you want I can guide you to a solution for a file prefix matcher. But that is definitely more work.

**Comment by alessandrod** [comment] 2016-11-07 01:53
> I your case a matcher with the line prefix patch will only be able to match one error in a directory. If you have something like this:
> 
> make[3]: Entering directory `/Users/alessandro/src/gst1/head/gst-plugins-bad/sys/applemedia'
>   CC       libgstapplemedia_la-vtdec.lo
> vtdec.c:38:1: error: unknown type name 'FOO'
>   CC       libgstapplemedia_la-other.lo
> other.c:38:1: error: unknown type name 'OTHER'
> 
> then that second error will not be matched because the pattern for the file prefix will not match anymore.

That is why if you look at the pattern in tasks.json, I specified:

           "pattern": [
                {
                    "regexp": "^((.*): Entering directory `(.*)'|(.*))$",
                    "filePrefix": 3
                },

The |(.*) side essentially makes the "Entering directory..." pattern optional, and the matcher work for multiple errors in the same file and directory. Perhaps it's not the most elegant solution, but it does work and doesn't need buffering the whole output.

If you have a better approach in mind I'm more than happy to hear about it tho!

**Comment by dbaeumer** [comment] 2016-11-07 09:18
I didn't catch this, however I still think that this is not working in a general case. Reason being that the first match must cover 3 lines and all following matches must cover 2 lines and the multi line matcher will not handle that right now.

IMO a better and more explicit approach would be something like this (see fileLocation property):

```json
{
            "name": "make-compile",
            "owner": "cpp",
            "fileLocation": ["relative", { "regexp" : "^((.*): Entering directory `(.*)'$", "index": 3 }]
            "pattern": [
                {
                    "regexp": "CC (.*)"
                },
                {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            ]
        }
```

**Comment by alessandrod** [comment] 2016-11-07 23:53
> I didn't catch this, however I still think that this is not working in a general case. Reason being that the first match must cover 3 lines and all following matches must cover 2 lines and the multi line matcher will not handle that right now.

Oh that's true, I had missed that.

> IMO a better and more explicit approach would be something like this (see fileLocation property):

I like this, I'll give it a go.

**Comment by dbaeumer** [comment] 2016-11-08 15:14
Great. Let me know if you need help.

**Comment by evmar** [comment] 2016-12-14 00:03
By the way, for compatibility with other tools that parse the `make` output, the `ninja` build system (http://ninja-build.org) also emits lines like 
```
 Entering directory `foo'
```
(with same the funny quotes).

**Comment by xaljox** [comment] 2017-05-30 11:03
I tried the "fileLocation": ["relative", { "regexp" : "^((.*): Entering directory `(.*)'$", "index": 3 }]
stuff, but it doesn't seem to work. The moment I put the regexp stuff in the Tasks.json file, then nothing will work, even all the tasks are gone. Also the tasks not depending on the problemMatcher are no longer available, the whole tasks list turns empty.
Perhaps the best thing to do for the moment is to have some sort of postprocessing on the output.
Thus to have something like this in the tasks.json:
make -w 2>&1 | fixpaths
The program fixpaths processes the output of the make step and by parsing the entering and leaving directory statements it adjusts the warning and error lines, so it makes the correct absolute paths. The rest of the lines it just passes through or perhaps filter it a bit to have less noise.
When options like -j8 is used it gets tricky Then there is a set of possible open directories and thus a search must be performed which possible absolute path is valid.

**Comment by dbaeumer** [comment] 2017-05-31 11:11
Cool.

**Comment by db4** [comment] 2017-06-23 06:21
@dbaeumer 
> IMO a better and more explicit approach would be something like this (see fileLocation property):
> ```
> {
>             "name": "make-compile",
>             "owner": "cpp",
>             "fileLocation": ["relative", { "regexp" : "^((.*): Entering directory `(.*)'$", "index": 3 }]
>             "pattern": [
>                 {
>                     "regexp": "CC (.*)"
>                 },
>                 {
>                     "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
>                     "file": 1,
>                     "line": 2,
>                     "column": 3,
>                     "severity": 4,
>                     "message": 5
>                 }
>             ]
> }
> ```
Is `regexp` in `fileLocation` already supported or it's just you proposal for future versions of VS Code? I see no mention in https://code.visualstudio.com/docs/editor/tasks-appendix that regexp is allowed there.

**Comment by dbaeumer** [comment] 2017-06-23 08:37
No regexp in fileLocation is not supported.

**Comment by sergey-s-betke** [comment] 2018-06-19 12:11
There is workaround with GNU make output postprocessing: https://github.com/Metrolog/marks/commit/bc7bbc25a886a4ee895c943c32b6e7c1adbbd922

**Comment by DanTup** [comment] 2018-11-13 13:30
@dbaeumer Is this issue to cover code-based/dynamic problem matchers that aren't restricted to regex? (eg. if a tool had a JSON output format)? I think so based on other links here, but the title isn't very clear.

**Comment by dbaeumer** [comment] 2018-11-15 09:06
Yes, the solution for that problem will be to allow extensions to parse the output of the terminal themselves without the need of a problem matcher.

**Comment by buserror** [comment] 2019-07-05 12:36
So how was that particular problem fixed? I'm just trying vscode and sure enough, all of my projects use sub-make, as it's a pretty standard pattern for linux development.
There are countless references to this issue in other issues, but after reading the whole log, I can't find an actual solution.
Is the current solution still involves a post-process of the output?

**Comment by alexr00** [comment] 2019-07-08 10:09
You can probably solve this using `"fileLocation": "autoDetect"` in the problem matcher. This issue tracks adding a programmatic problem matcher.

**Comment by alexr00** [comment] 2019-10-10 10:04
With `"autoDetect"` this is now a dupe of https://github.com/microsoft/vscode/issues/59337

**Closed** 2019-10-10 10:04 UTC
Labels: *duplicate, feature-request, tasks

**Comment by yeggles** [comment] 2019-10-18 19:10
> With `"autoDetect"` this is now a dupe of #59337

Is it?  It doesn't work for me.  The only thing that seemed like it could work would be to allow regex expressions in the fileLocation setting.  On my company's project the Makefile of the project calls a good 50+ other Makefiles and before doing so the scripts change directory so any errors reported by the make command will have broken links due to the fact that it will it will ignore the change in directory.

**Comment by alexr00** [comment] 2019-10-21 08:57
This would also be solved by programatic problem matching, which is tracked by https://github.com/microsoft/vscode/issues/59337
