### ISSUE TITLE
Highlight Matching Tag is not working

### ISSUE THREAD

**Issue by kkabinuevo** [Microsoft/vscode#67802] opened 2019-02-03 04:29 UTC
- VSCode Version: Version 1.30.2 (1.30.2)
- OS Version: Mojave 10.14.2 (18C54)

Steps to Reproduce:
Recording of issue: https://im.ezgif.com/tmp/ezgif-1-e0c2f9875681.gif
1. I downloaded the extension, refreshed VS code, restarted my computer, etc, and nothing has worked.
2. As seen in the gif above, no matter where I click, nothing gets highlighted.

Does this issue occur when all extensions are disabled?: **No**

**Comment by dbaeumer** [comment] 2019-02-04 08:41
@kkabinuevo can you please provide more information. The link to the image / gif is not working.

**Comment by kkabinuevo** [comment] 2019-02-04 20:42
Hi @dbaeumer here's a youtube video link: 

https://youtu.be/2td1aGC0fJk

Not sure what happened to the gif

**Comment by KamasamaK** [comment] 2019-02-10 16:17
If you're having issues with the [Highlight Matching Tag extension](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag) then they should be posted to that extension's repo.

But I think this is just a matter of misunderstanding what the extension does. The code in your video contains no tags, so it's not going to highlight any. Try with an HTML file and you'll see what it is supposed to do.

**Comment by dbaeumer** [comment] 2019-02-18 09:38
@kkabinuevo I will close the issue since IMO there is no issue with VS Code itself. Please ping and provide steps on how to reproduce if you disagree.

**Closed by dbaeumer** 2019-02-18 09:38 UTC
Labels: extensions, needs more info
