### ISSUE TITLE
Character will duplicate when re-focus on tab

### ISSUE THREAD

**Issue by ethancfchen** [Microsoft/vscode#49660] opened 2018-05-11 02:40 UTC
- VSCode Version: 1.23.1
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. Open 2 file in VSCode.
2. Focus on another tab or open another app. (Unfocus current file tab)
3. Re-focus on previous file tab
4. Move the input cursor after a number or symbol by clicking.
5. Type the same character.
6. The character will duplicate itself automatically.

Does this issue occur when all extensions are disabled?: Yes

Screenshots:

![may-11-2018 10-36-58](https://user-images.githubusercontent.com/5051791/39903744-53cd2096-5507-11e8-9394-98631c45a994.gif)
![may-11-2018 10-37-11](https://user-images.githubusercontent.com/5051791/39903745-53f20d66-5507-11e8-84ff-f3aa3dd579e3.gif)
![may-11-2018 10-37-20](https://user-images.githubusercontent.com/5051791/39903746-541b5194-5507-11e8-8f63-78ae8d564d29.gif)

**Comment by ethancfchen** [comment] 2018-07-03 09:43
Any update?

**Comment by alexandrudima** [comment] 2018-09-19 07:13
Duplicate of #49480

**Closed by alexandrudima** 2018-09-19 07:13 UTC
Labels: bug
