### ISSUE TITLE
editing makes breakpoints view flicker if debug session is active

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6344] opened 2016-05-13 10:47 UTC
- VSCode Version: alpha

Steps to Reproduce:
- add some breakpoints to a source file
- start debug session
- edit the source file

Observe:
On every keystroke the breakpoints view refreshes (flickers).

**Comment by isidorn** [comment] 2016-05-16 10:14
Looked into this and the behavior I am seeing is that we refresh the breakpoints view on every keystroke if that keystroke is on a line that has a breakpoint.
This is necessery as that keystroke can potentially delete the line or add a new line and thus modify the line number of a breakpoint.

Since I can not reproduce this behavior if I type on any line that does not have a breakpoint I am closing this as designed. As I think the behavior is not that bad and in this case we have to refresh in order for the line numbers in the breakpoints view to be correct.

Let me know if you see this on every keystroke and I will reopen

**Comment by weinand** [comment] 2016-05-16 13:45
@isidorn this is the behavior in the latest:

![may-16-2016 15-41-02](https://cloud.githubusercontent.com/assets/1898161/15291189/f3f2e0e0-1b7c-11e6-9d40-66b77a6695c7.gif)

As you can see does the breakpoints view not only flicker, but resizes on every keystroke (even on a line that does not contain a breakpoint).

**Comment by isidorn** [comment] 2016-05-16 14:32
@weinand forgot to metnion this happens also on the line before and after the breakpoint.
Do you also see this behvaior if you type on line 1736 or 1740 in your example?

**Comment by weinand** [comment] 2016-05-16 16:01
@isidorn the flicker only occurs when editing the line with the breakpoint and the line before.

But in any case, the flickering in the breakpoints view is unnecessary and looks silly.

**Comment by isidorn** [comment] 2017-11-13 18:08
I can not see this in latest vscode insiders (did quite some refactoring in the debug editor model manager that probably fixed this).
Closing.
@weinand let me know if you still see this and I will reopen

**Closed by isidorn** 2017-11-13 18:08 UTC
Labels: bug, debug
