### ISSUE TITLE
Occasionally my text buffer will get scrambled (parts of it will get jumbled)

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#9104] opened 2016-07-11 23:45 UTC
- VSCode Version: 1.3.0
- OS Version:

Steps to Reproduce:
Sorry, no repro steps.

 Here's an example of the scrambled area - it appears characters from the beginning of many lines have been removed...

   private _startDownloadBlobsTask(
        sourceBlobFolder: string,
        destDiskFolder: string,
    defaultOverwriteIfEx i sts: boolean,
    items: CloudHub.Azure.IBlobContainerItem[],
    transf o rmDownloadFileNameAndPath?: (relativeBlobPath: string) => string
    oid {
    var groupActivity = new BlobDownloadGroupActivity(
    this._containerReference,
        sourceBlobFolder,
        destDiskFolder,
            ultOverwriteIfExists,
                mDownloadFileNameAndPath,
            ._activityLogManager,
            this._host,
            ._telemetry

            ivity.initialize();
        pActivity.addToActivityLog();
        groupActivity.start(items);

                his method from the UI, instead call BlobListViewModel openBlob,
            l call openSingleBlob.
    ic openSingleBlob(blob: CloudHub.Azure.IBlobContainerItem): Promise<any> {
    var sourceBlobFolder: string = StorageExplorerUtilities.getFolderFromFilePath(blob.FullName);
        return this._host.executeOperation("Environment.getTempDirectory", []).then((destinationFileFolder: string) => {
            var groupActivity = new BlobOpenGroupActivity(

**Comment by StephenWeatherford** [comment] 2016-07-11 23:45
Luckily this hasn't happened very often.

**Comment by bpasero** [comment] 2016-07-12 05:09
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment] 2016-07-13 23:32
@StephenWeatherford did you have a chance to run VS Code without extensions?

**Comment by StephenWeatherford** [comment] 2016-07-13 23:54
Hi.  As I mentioned, it rarely happens, so I have no repro to try out.  I think it might be related to format document (shift+alt+F) in the middle of a big refactoring.

Feel free to close, I just wanted you to know about it.  Thx.

**Comment by alexandrudima** [comment] 2016-07-14 09:29
@StephenWeatherford It looks like you are editing C# files. Please let us know if you find reproducible steps, we would love to track this down and figure out if it is a VS Code problem or one in the C# extension.

**Comment by alexandrudima** [comment] 2016-10-27 20:29
Closing after a number of days without a reply.

**Closed by alexandrudima** 2016-10-27 20:29 UTC
Labels: needs more info
