### ISSUE TITLE
Panel loses maximized state after toggling sidebar visibility

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#200583] opened 2023-12-11 19:36 UTC
- VS Code Version: stable
- OS Version: 

It was working fine in 1.81, after update to latest is broken

Steps to Reproduce:

1. Make sure sidebar is visible, e.g. explorer view
2. Maximize panel
3. Click on explorer icon in sidebar to hide sidebar
4. :bug: editor gets focused and panel size is restored

**Comment by jeanp413** [comment] 2023-12-11 19:40
PR fixing it https://github.com/microsoft/vscode/pull/200585

**Comment by sbatten** [comment] 2023-12-21 01:27
duplicate of https://github.com/microsoft/vscode/issues/195119

**Closed by sbatten** 2023-12-21 01:27 UTC
