### ISSUE TITLE
Allow styling or switching off git diff gutter highlights

### ISSUE THREAD

**Issue by nomad-software** [Microsoft/vscode#37975] opened 2017-11-09 18:26 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic

Can we have a new option to remove or at least colour the git diff gutter highlights please? They can be quite distracting.

![screenshot from 2017-11-09 18-17-34](https://user-images.githubusercontent.com/1413497/32622562-24dd2978-c57b-11e7-8b81-06deba81d398.png)

**Comment by usernamehw** [comment] 2017-11-10 02:17
@nomad-software Did you read my answer? `workbench.colorCustomizations` stopped working?

Also, this is a duplicate of https://github.com/Microsoft/vscode/issues/29241

**Closed** 2017-11-10 09:49 UTC
Labels: git, new release

**Comment by nomad-software** [comment] 2017-11-10 13:05
@usernamehw Have you got an example of using `workbench.colorCustomizations`?

**Comment by usernamehw** [comment] 2017-11-10 13:13
https://stackoverflow.com/questions/43969277/how-can-you-disable-gutter-indicators-in-vs-code/43973209#comment81367260_43973209
