### ISSUE TITLE
jsdoc intellisense is triggered when you move the cursor to a line ending in /**

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21178] opened 2017-02-22 18:05 UTC
#21031

For the following code:

```js
/**
 * Returns the minimum node from the heap.
 *
 * @return {Node} node The heap's minimum node or undefined if the heap is
 * empty.
 */
FibonacciHeap.prototype.findMinimum = function () {
  return this.minNode;
};
```

Steps to reproduce:

1. Put cursor at end of the second line (Returns the minimum...)
2. Press up, intellisense is triggered wrongly, making navigation with arrow keys difficult if you have block comments in your code. This also happens when navigating using page up/down.

![image](https://cloud.githubusercontent.com/assets/2193314/23225351/6822e72a-f8e6-11e6-9512-2f17c8f06079.png)

**Comment by mjbvz** [comment] 2017-02-22 19:02
Thanks. This is a duplicate of #21056. I'll check  in a fix shortly

**Closed by mjbvz** 2017-02-22 19:02 UTC
Labels: bug, duplicate, important, javascript
