### ISSUE TITLE
Closing quote mark is not overtyped as expected

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#78527] opened 2019-08-05 18:42 UTC
When a previous string in single quotes is present on the line, overtyping a double quote string's final quote mark does not work.

- Version: 1.37.0-insider (user setup)
- Commit: 4a03f7e7eff2560d2e53c029321870514d19a2aa
- Date: 2019-08-05T09:34:10.366Z
- OS: Windows_NT x64 6.3.9600 (Windows 8)

To Reproduce:

1. Type this:

![example](https://user-images.githubusercontent.com/5044802/62487107-9aac6200-b786-11e9-82fe-aac51fdba26b.png)

2. Type `"`, and observe that another quote mark is added.

![example2](https://user-images.githubusercontent.com/5044802/62487160-c0396b80-b786-11e9-9b94-e2763caaa2bd.PNG)

**Comment by alexandrudima** [comment] 2019-08-08 15:46
@kylrth Starting with the July release, `"` is overtyped only if the editor inserted it. e.g.:

![auto-closing-2](https://user-images.githubusercontent.com/5047891/62717352-051e0600-ba04-11e9-83a2-47305169671d.gif)

Do you think the change makes sense, or do you think we really need an option to go back to the old behaviour where `"` is always overtyped, even if it existed in the file before? (I have tried to avoid an option so far, hoping that the new behaviour makes more sense.... the editor overtypes only stuff that it auto-inserted).

This is something we changed recently to tackle #37315 . More details in https://github.com/microsoft/vscode/issues/37315#issuecomment-515200477

**Comment by kylrth** [comment] 2019-08-09 16:02
The problem is that I'm observing this behavior even though I've only just typed `"142` and VS Code has inserted the following `"` for me. Under the new behavior, I should still expect the closing quote mark to be eaten by the cursor when I type `"` at the end. This only happens when a double quote mark appears in single quotes earlier on the same line.

When I get home from work today I can record my screen to demonstrate the problem.

**Comment by kylrth** [comment] 2019-08-10 00:26
Here's an example:

![example](https://user-images.githubusercontent.com/5044802/62815117-6ebd1380-badb-11e9-9fb6-8add3c4a5c63.gif)

You can see how the double quote mark earlier on the line causes the last double quote mark to not be overtyped as it should.

**Comment by alexandrudima** [comment] 2019-08-12 08:29
I can reproduce this case also in 1.36.1, so it is not a regression from my recent changes. In fact, this specific case (of an odd count of `"`) reproduces since https://github.com/microsoft/vscode/commit/5b9d8b2d6cd201ab4267c026531856dc85d75fc4

**Closed** 2019-08-12 08:56 UTC
Labels: bug, editor-autoclosing

**Comment by haymez** [comment] 2019-08-12 17:13
> @kylrth Starting with the July release, `"` is overtyped only if the editor inserted it. e.g.:
> 
> ![auto-closing-2](https://user-images.githubusercontent.com/5047891/62717352-051e0600-ba04-11e9-83a2-47305169671d.gif)
> 
> Do you think the change makes sense, or do you think we really need an option to go back to the old behaviour where `"` is always overtyped, even if it existed in the file before? (I have tried to avoid an option so far, hoping that the new behaviour makes more sense.... the editor overtypes only stuff that it auto-inserted).
> 
> This is something we changed recently to tackle #37315 . More details in [#37315 (comment)](https://github.com/microsoft/vscode/issues/37315#issuecomment-515200477)

I think the change makes sense for people who were complaining about the previous behavior. I'm firmly in the camp that it makes things more confusing to sometimes overwrite a closing tag and sometimes not. Especially when it used to always swallow closing tags. I've grown quite used to it and definitely prefer that to the new behavior. Is there any way a setting could be added to modify this behavior? If there is an existing feature request for this setting let me know as I was unable to find one.
