### ISSUE TITLE
Regression issue with debug in WSL

### ISSUE THREAD

**Issue by wux5** [Microsoft/vscode#40345] opened 2017-12-16 11:21 UTC
Debug in WSL is broken on the latest version 1.19.0, it used to work in v1.18.
- VSCode Version: 1.19.0
- OS Version: Windows 10

Steps to Reproduce:

1. Setup a Typescript project (I guess it has the same issue with any NodeJS project), with a file server.ts
```js
console.log("testing..."); // Set a breakpoint here
```
2. Configure launch.json with:
```js
{
      "name": "Current TS File",
      "type": "node",
      "request": "launch",
      "useWSL": true,
      "program": "${workspaceFolder}/node_modules/ts-node/dist/_bin.js",
      "args": [
        "${relativeFile}"
      ],
      "cwd": "${workspaceFolder}",
      "protocol": "inspector"
}
```
3. Open server.ts, press F5 to run
4. Notice the error as attached. Obviously the path of the current file (${relativeFile}) is incorrect, it's supposed to be /src/server.ts, but the log in the debug console shows: \src\server.ts. This worked correctly in the previous version.

Reproduces without extensions: Yes
![vscode-debug](https://user-images.githubusercontent.com/20307897/34069954-b14b42cc-e20f-11e7-857f-9917b3bb8b94.PNG)

**Comment by weinand** [comment] 2017-12-18 09:54
duplicate of #40256

**Closed by weinand** 2017-12-18 09:54 UTC
Labels: debug
