### ISSUE TITLE
VS Code MacOS Universal Icon doesn't show up

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#120757] opened 2021-04-07 20:20 UTC
From Twitter: https://twitter.com/pjausovec/status/1379877534733529089

Visual Code icon is broken. MacOS version 11.2.3 and VS Code Version: 1.55.0 (Universal) 

![image](https://user-images.githubusercontent.com/9721254/113928657-1614b100-97bd-11eb-97e7-c6f71c41eabd.png)

**Comment by misolori** [comment] 2021-04-07 20:23
Duplicate of https://github.com/microsoft/vscode/issues/120305

**Closed by misolori** 2021-04-07 20:23 UTC
