### ISSUE TITLE
[Feature] StatusBarItem Support Context Menu

### ISSUE THREAD

**Issue by hawkerm** [microsoft/vscode#76437] opened 2019-07-01 22:44 UTC
It'd be great for the StatusBarItem to support a right-click function to show a custom context menu.  This would allow a great visual way for extension/behavior options based on whatever the extension is doing.

It should also be possible to have the default click action bring up the context menu instead.

This could also be useful for other areas of the UI where command icons are shown maybe like the top-right icon strip?

Seems like a good follow-on to work done from #3192?

**Comment by jrieken** [comment] 2019-10-08 09:41
/duplicate of https://github.com/microsoft/vscode/issues/27196

**Closed** 2019-10-08 09:41 UTC
Labels: *duplicate, feature-request, workbench-status
