### ISSUE TITLE
macOS Sierra: background artifacts

### ISSUE THREAD

**Issue by maxence-charriere** [Microsoft/vscode#12473] opened 2016-09-22 18:13 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:
1. just launch Visual studio on macOS Sierra

**Comment by maxence-charriere** [comment] 2016-09-22 18:14
<img width="1399" alt="screen shot 2016-09-22 at 20 13 57" src="https://cloud.githubusercontent.com/assets/2692731/18760382/1e4bbb8e-8101-11e6-83ba-e13b91f9e555.png">

**Comment by bpasero** [comment] 2016-09-22 18:15
@maxence-charriere can you try if this reproduces with our insider build too? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by maxence-charriere** [comment] 2016-09-22 18:15
<img width="1399" alt="screen shot 2016-09-22 at 20 14 58" src="https://cloud.githubusercontent.com/assets/2692731/18760427/48cec842-8101-11e6-8fc3-b7ef3a5b2009.png">

**Comment by maxence-charriere** [comment] 2016-09-22 18:19
is it 1.5.3 ?

**Comment by maxence-charriere** [comment] 2016-09-22 18:22
ok this one on Version 1.6.0-insider (1.6.0-insider):
<img width="1268" alt="screen shot 2016-09-22 at 20 21 26" src="https://cloud.githubusercontent.com/assets/2692731/18760657/487a243a-8102-11e6-8ca3-fdce68167e72.png">

**Comment by jaysylvester** [comment] 2016-09-23 03:23
I'm seeing this as well.

Not sure if this helps, but I'm also seeing a similar problem in Chrome, which I submitted to them also. Screenshot below is Daring Fireball in Safari vs. Chrome:

![safari-vs-chrome](https://cloud.githubusercontent.com/assets/2001324/18773232/3ca60f66-811b-11e6-8ef7-854a91e44900.jpg)

**Comment by mrmlnc** [comment] 2016-09-23 05:03
Hello, Chrome bug:

  * https://github.com/atom/atom/issues/12634
  * https://github.com/electron/electron/issues/7304

**Comment by bpasero** [comment] 2016-09-23 05:11
Thanks for linking the related issues here. The related chrome bug is: https://bugs.chromium.org/p/chromium/issues/detail?id=633805

**Comment by bpasero** [comment] 2016-09-23 05:12
@maxence-charriere @jaysylvester that issue talks about a possible fix using `--force-gpu-rasterization`, did you try that? maybe pass it to the starting of code?

**Comment by jaysylvester** [comment] 2016-09-23 05:24
@bpasero Just tried --force-gpu-rasterization with VS Code and that fixes it.

**Comment by bpasero** [comment] 2016-09-23 05:33
@jaysylvester great to hear that 👍

**Comment by maxence-charriere** [comment] 2016-09-23 10:49
how to use it? I tried code --force-gpu-rasterization on the console but nothing changed.

**Comment by bpasero** [comment] 2016-09-23 10:51
yeah, from the command line when launching an instance.

**Comment by l2dy** [comment] 2016-09-23 10:58
@maxence-charriere `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --force-gpu-rasterization`

**Comment by FabianLauer** [comment] 2016-09-23 20:40
@jaysylvester Thanks!

**Comment by FabianLauer** [comment] 2016-10-11 18:36
Since 1.6.0, I'm seeing some artifacts even with `--force-gpu-rasterization`.
Also, when setting `"window.zoomLevel"` to any value other than `0` the artifacts disappear, regardless of `--force-gpu-rasterization`.

**Comment by xgt001** [comment] 2016-10-18 05:31
@FabianLauer Thanks, that did the trick for me!

**Comment by shaneparsons** [comment] 2016-11-02 18:17
@FabianLauer that definitely reduces it, but I'm still seeing the artifacts flicker on / off quite often.

**Comment by brucecantarim** [comment] 2016-11-19 17:56
I still get some flickering, even with the workarounds, but it definitely helps.

I changed the "windows.zoomLevel" to 0.001 and did the /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --force-gpu-rasterization to launch VS Code via terminal.

Here are the warnings I received:
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5

**Comment by Gil80** [comment] 2016-11-20 23:06
how can I run Vs code with the argument --force-gpu-rasterization just by typing > code in terminal or when I click on the icon app?
 (using macSierra).

**Comment by Fenwil** [comment] 2016-11-29 15:35
I could solve it with `code --force-gpu-rasterization` but I only have that trouble when I connect to a external monitor. I have a MBP Retina 2015.

**Comment by xgt001** [comment] 2016-11-30 05:19
I still see jank on MacBook Pro (Retina, 13-inch, Mid 2014) even with --force-gpu-rasterization :(

**Comment by kision** [comment] 2016-12-09 06:10
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-gpu &

**Comment by michaeljcalkins** [comment] 2016-12-23 17:50
![screen shot 2016-12-23 at 9 48 07 am](https://cloud.githubusercontent.com/assets/8272012/21459654/16ea6ec6-c8f5-11e6-9d4d-67632a921b35.png)

This fixed the issue for me.  I just had the wrong color profile on my monitors I guess.

**Comment by FabianLauer** [comment] 2016-12-23 19:44
@michaeljcalkins Works for me too, awesome, thanks!

**Comment by xgt001** [comment] 2016-12-25 04:25
@michaeljcalkins thanks a lot for the workaround!

**Comment by pahnev** [comment] 2017-01-24 06:27
@michaeljcalkins it works, but I'd rather have correct colors on my monitors :)

**Comment by Gil80** [comment] 2017-02-01 06:30
The workaround is nice, yet people who use custom made .icc profiles are still faced with this issue.
Colour accuracy workflow is required for some.

**Comment by Jonathan0wh** [comment] 2017-02-09 09:16
Still have this issue with customized color profile. Using "--force-gpu-rasterization" didn't work, but "window.zoomLevel: 0.001" and "--disable-gpu" works. Mac Air 2014, Sierra 10.12.3.  
Hope this issue could be fixed sooner or latter.

**Comment by fbnlsr** [comment] 2017-02-09 09:55
Yeah this is a really problematic bug which makes some themes unusable.

Might be a tough one to fix though, as it's been active for so long.

**Comment by suyuTech** [comment] 2017-02-10 07:38
@michaeljcalkins Works for me too, awesome, thanks!

**Comment by tedmcdo** [comment] 2017-02-17 06:49
Please fix this bug soon. Switching to Atom until this gets sorted out, it's too annoying to use on a daily basis :(

**Comment by c-st** [comment] 2017-02-17 08:12
@tedmcdo Atom has the same issue. Have a look at: https://github.com/atom/atom/issues/12634

**Comment by tedmcdo** [comment] 2017-02-17 08:38
I guess I'm lucky then, as the issue does not occur in Atom for me. Hopefully the issue gets fixed permanently though.

**Comment by causztic** [comment] 2017-02-22 00:40
Thanks @FabianLauer! I changed the settings file to have a zoomlevel of 0.1 (something not noticeable), and now I can run it without any visual artifacts! Perhaps you guys can give it a shot

**Comment by Gil80** [comment] 2017-02-22 01:29
confirming that setting  "window.zoomLevel": 0.1 is a nice workaround for the GPU Artefacts issue

**Comment by causztic** [comment] 2017-02-22 02:29
@Gil80  keep in mind that if you change your zoom-levels in the editor and back, it will reset the zoomlevel in your setting to 0.0 and the artifacts will come back again.

**Comment by MichaelOstermann** [comment] 2017-03-02 10:17
This is a common issue I've seen been before when using 3d transforms in CSS like VSCode does - a couple of well placed `backface-visibility: hidden;` usually resolve this - tried it myself and managed to reduce those artifacts bit by bit.

**Comment by Fenwil** [comment] 2017-03-07 19:00
This issue I have it in some Electron Apps (Visual Studio Code and Hyper) but I fix it with @michaeljcalkins solution https://github.com/Microsoft/vscode/issues/12473#issuecomment-269024219 
![screen shot 2017-03-07 at 3 56 56 pm](https://cloud.githubusercontent.com/assets/2475912/23672928/22e325a8-034f-11e7-924b-749c3d13495f.png)
![screen shot 2017-03-07 at 3 57 02 pm](https://cloud.githubusercontent.com/assets/2475912/23672929/22e9dbbe-034f-11e7-9d95-668f95b3765c.png)

**Comment by fox1t** [comment] 2017-04-10 06:48
I can confirm that using "window.zoomLevel": 0.001 on macOS Sierra 10.12.4 fixes the problem. Now i am able to use my calibrated profile.

**Comment by bpasero** [comment] 2017-04-10 17:06
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by Codelica** [comment] 2017-04-10 17:52
Thanks for the heads up!

Insider build fixed it for me without any workarounds.  👍 

(Using a calibrated i1 color profile)

**Comment by jfieber** [comment] 2017-04-10 17:56
It does. The colors are substantially different than before. Side by side with the same theme, the insider version colors are way more saturated.

**Comment by bpasero** [comment] 2017-04-11 05:07
Awesome 👍

**Comment by am6377** [comment] 2017-04-16 22:41
didn't work. Had to set"window.zoomLevel": 0.001 and I still see screen flickers.

**Comment by bpasero** [comment] 2017-04-17 15:50
@am6377 are you on our insiders build?

**Comment by am6377** [comment] 2017-04-17 16:04
I was on insider build and then I switched to normal build to see if there
was any difference and for me there isn't.

**Comment by bpasero** [comment] 2017-04-17 16:23
So it looks like the Electron update is only resolving it for some people.

**Comment by epogue** [comment] 2017-04-17 18:54
@bpasero The Insiders update fixed the issue for me. No need for the zoomLevel hack now.

**Comment by am6377** [comment] 2017-04-17 20:46
@bpasero I tried #insider build but I can't use custom or other built-in display profile except for the standard color LCD which actually doesn't look really nice IRL. The only way it works for me is setting "window.zoomLevel": 0.001 and even with that I get lots of random screen flickers. 

<img width="1279" alt="screen shot 2017-04-17 at 4 39 48 pm" src="https://cloud.githubusercontent.com/assets/10854937/25104024/cbb70a34-238c-11e7-9671-9ddf077b1bdc.png">
<img width="1280" alt="screen shot 2017-04-17 at 4 40 02 pm" src="https://cloud.githubusercontent.com/assets/10854937/25104029/cdaebd3c-238c-11e7-80c0-7275fae79c1d.png">

**Comment by jfieber** [comment] 2017-04-17 21:27
With the current insiders build, using that specific profile (ITU-R BT.709-6), and the default dark theme, I'm not seeing the behavior, either on the built in display (5k iMac) or external display.  With the current non-insiders build, I initially thought the window.zoomLevel hack worked, but after using it for awhile, it was clear that it helped some, but didn't eliminate the issue.

**Comment by bpasero** [comment] 2017-04-26 15:28
The issue is resolved for me, I just verified that. No clue why some people are still seeing it though when trying our insiders build.

**Comment by Codelica** [comment] 2017-04-26 16:51
It fixed all 3 machines I use which have custom profiles.  Purely a *guess*, but maybe some people are downloading the normal version from the link posted (https://code.visualstudio.com/Download#insiders), not realizing the Insiders build is a text link at the bottom.

**Comment by bpasero** [comment] 2017-04-26 16:53
Yeah, sounds like it.

**Closed by bpasero** 2017-04-26 16:53 UTC
Labels: electron, upstream, workbench

**Comment by am6377** [comment] 2017-04-26 18:14
I would like to apologize to @bpasero and I would like to thank @Codelica because I realized I didn't download the insiders build. I thought the link with #insiders took to me to the insiders built. I didn't scroll down. The direct link to insiders is 
(https://code.visualstudio.com/insiders) WITHOUT the # 
My fault :)

**Comment by will-stone** [comment] 2017-05-12 09:53
Came across this issue when scratching my head that the background colour I was setting in my theme was showing differently on the screen (i.e. when checking it with the Digital Color Meter). I did download the Insiders build and I can confirm it's fixed there for me. Can I ask when this fix will roll out? Theming is feeling rather futile while my colours don't match :-(
