### ISSUE TITLE
[Question] Why CSS formatter is not included by default?

### ISSUE THREAD

**Issue by turbographics2000** [Microsoft/vscode#50785] opened 2018-05-30 12:58 UTC

**Comment by aeschli** [comment] 2018-05-30 15:54
There are extensions that provide formatting css. I'd suggest you try one of these.
IMO we should not package it all to VSCode. We want to share the maintenance work and want to keep the VSCode download small.

**Comment by aeschli** [comment] 2018-05-30 15:55
duplicate of #19166

**Closed by aeschli** 2018-05-30 15:55 UTC
Labels: css-less-sass
