### ISSUE TITLE
Error popup after ctrl + space

### ISSUE THREAD

**Issue by Sebola3461** [microsoft/vscode#161441] opened 2022-09-21 22:24 UTC
Type: <b>Bug</b>

- Go to any live-share session
- Use auto-import (ctrl+.)
- Try to use ctrl + space

Example: 
const collector = new Collector({
 // ctrl + space here
})

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz (4 x 2667)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.56GB free)|
|Process Argv|--crash-reporter-id 7f85b9a6-2b48-4b6b-926d-0f11fa838b31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.5723
material-icon-theme|PKi|4.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
vscccc:30566498

```

</details>

**Comment by mjbvz** [comment] 2022-09-22 20:11
Duplicate of https://github.com/MicrosoftDocs/live-share/issues/3108

**Closed by mjbvz** 2022-09-22 20:11 UTC
