### ISSUE TITLE
Code navigation/help not working

### ISSUE THREAD

**Issue by jay-morgan** [microsoft/vscode#144408] opened 2022-03-04 15:22 UTC
Issue Type: <b>Bug</b>

- Install the latest VS code containing this update
- Open any TS project
- Try to navigate between any functions via command & click/hover over code 
- The code description gets stuck loading and the bar that shows when the code is indexing does so continuously 

Intermittantly, this error will also keep appearing on screen every few minutes:
<img width="535" alt="Screenshot 2022-03-04 at 15 53 37" src="https://user-images.githubusercontent.com/17114407/156796121-f421c4fd-8126-437b-a0f3-35c57675bf45.png">

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (2.72GB free)|
|Process Argv|--crash-reporter-id cc9021b9-03ce-4d7c-94dd-5e2a907466c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.9.1
better-comments|aar|2.1.0
vscode-node-readme|ben|3.0.2
autofoldyeah|bob|1.0.6
better-toml|bun|0.3.2
better-phpunit|cal|1.5.3
npm-intellisense|chr|1.4.1
gitignore|cod|0.7.0
octicons|ctu|0.0.1
mustache|daw|1.1.1
vscode-eslint|dba|2.2.2
phptools-vscode|DEV|1.7.8717
xml|Dot|2.5.1
sf-pack|dub|1.1.0
gitlens|eam|12.0.1
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.3.0
vs-code-xml-format|fab|0.1.5
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.10
macros|ged|1.2.1
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
go|gol|0.31.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.6
php-cs-fixer|jun|0.2.10
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
mongodb-vscode|mon|0.8.0
theme-monokai-pro-vscode|mon|1.1.20
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.20.0
remote-containers|ms-|0.224.2
azure-account|ms-|0.10.0
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
polacode|pnp|0.3.4
vscode-yaml|red|1.4.0
rust|rus|0.7.8
fish-vscode|sky|0.2.1
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.1.7
symfony-vscode|The|1.0.2
tab-groups|usa|1.4.8
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343

```

</details>

**Comment by mjbvz** [comment] 2022-03-04 21:18
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jay-morgan** [comment] 2022-03-07 08:56
Hi @mjbvz, I've checked this morning and I get the same issue with the latest VS code insiders build with all extensions disabled.

**Comment by jay-morgan** [comment] 2022-03-07 11:15
@mjbvz I was able to resolve the issue by manually setting the Typescript Language mode to use the workspace setting rather than using the 'Use VS Code version' option. I did not consciously change this - so either this was accidental or it may still be related to the update. Hope this helps if anyone experiences a similar issue, and thanks again @mjbvz for taking a look 👍🏻

**Comment by mjbvz** [comment] 2022-03-07 22:43
What workspace version of TypeScript did you switch to? Unless you're on a really old TS version, using the workspace version should not be required

**Comment by jay-morgan** [comment] 2022-03-08 08:02
4.0.3

**Comment by mjbvz** [comment] 2022-03-08 23:52
Thanks. Yeah that's an older TS build but not ancient. If you can narrow down what causes this, I can take a look because new TS versions really should support running against old TS code and you will likely want to update someday

For now though I'm closing this since it seems like this issue is no longer blocking you

**Closed by mjbvz** 2022-03-08 23:52 UTC
Labels: needs more info
