### ISSUE TITLE
[themes] Incorrect syntax highlighting after destructured function arguments with a default value in JS

### ISSUE THREAD

**Issue by eldarshamukhamedov** [Microsoft/vscode#32743] opened 2017-08-17 23:18 UTC
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6 and Linux Mint 18

Steps to Reproduce:

1. Paste this into a JS file:
```js
const fn = ({
	one = 'one',
} = {}) => {
	const something = 'hello';
	return something;
};
```
2. Note that `const` and `return` keywords are not highlighted as reserved keywords:
![screen shot 2017-08-17 at 4 10 38 pm](https://user-images.githubusercontent.com/1694252/29437643-ad2729de-8366-11e7-9c5c-72073c5021fa.png)

Reproduces without extensions: Yes

Notes: Only occurs when the destructured object is formatted over multiple lines. Looks fine when the object is on a single line:
![screen shot 2017-08-17 at 4 10 48 pm](https://user-images.githubusercontent.com/1694252/29437743-5e59911a-8367-11e7-945b-e2721ec5757c.png)

This issue seems similar and possibly related to https://github.com/Microsoft/vscode/issues/3008

**Comment by mjbvz** [comment] 2017-08-17 23:20
Thanks for the report. This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/499

Closing as upstream

**Closed by mjbvz** 2017-08-17 23:20 UTC
Labels: grammar, javascript, new release, upstream
