### ISSUE TITLE
Weird display when Git has a remote host ID warning

### ISSUE THREAD

**Issue by j-norwood-young** [microsoft/vscode#178206] opened 2023-03-24 09:29 UTC
Type: <b>Bug</b>

If a Git remote host's key changes, and there is a key error, the warning message is something like:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
```

However, the Git error message box just shows the ampersands, and cuts off the rest of the message, which is pretty exciting at first until you figure out what's going on.

To reproduce, you could purposefully break your Github fingerprint in ~/.ssh/known_hosts, which would give you the error.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:53:46.528Z)
OS version: Darwin arm64 21.6.0

**Comment by j-norwood-young** [comment] 2023-03-24 09:32
This is what the modal looks like:

<img width="298" alt="Screenshot 2023-03-24 at 10 23 48" src="https://user-images.githubusercontent.com/387601/227481420-8c6f897b-e033-48c7-86af-97bb153f786a.png">

**Comment by lszomoru** [comment] 2023-12-12 09:40
Closing as duplicate of https://github.com/microsoft/vscode/issues/178235

**Closed by lszomoru** 2023-12-12 09:40 UTC
Labels: bug, git
