### ISSUE TITLE
Resolve file related ${} variable in tasks to have appropriate slash for shell

### ISSUE THREAD

**Issue by liukai234** [microsoft/vscode#84016] opened 2019-11-06 00:40 UTC
In the development of C + + in vscode under Windows version, the file separator in ${file} ,etc. is \\, while in Bash is /, which will cause that the development of C + + cannot be compiled after vscode uses bash integrated terminal.

**Comment by alexandrudima** [comment] 2019-11-06 07:10
@liukai234 In what file are you using the `${file}`?

**Comment by liukai234** [comment] 2019-11-06 08:33
> @liukai234 In what file are you using the `${file}`?
 The code is all of task.js,task.js is generated by the C / C + + extension, ${file} in line 20 of the code snippet
```javascript
{
    // https://go.microsoft.com/fwlink/?LinkId=733558
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "gcc.exe build active file",
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "command": "D:\\Program Files\\mingw64\\bin\\gcc.exe",
            "args": [
                "-g",
                "${file}", // This ${file} and second line below ${fileDirname}, ${fileBasenameNoExtension}
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "D:\\Program Files\\mingw64\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by alexr00** [comment] 2019-11-06 10:19
Sort of a duplicate of https://github.com/microsoft/vscode/issues/38381, but we can probably be better about resolving variables to have a slash that is correct for bash.

**Comment by tdjastrzebski** [comment] 2019-11-06 13:08
IMHO only forward slashes in path parameters should be allowed and used.
Windows supports them since long, long time ago.

**Closed** 2019-12-26 14:50 UTC
Labels: bug, tasks
