### ISSUE TITLE
Auto merge commits are not signed on ubuntu

### ISSUE THREAD

**Issue by nikodz** [microsoft/vscode#186605] opened 2023-06-29 08:03 UTC
Type: <b>Bug</b>

I have requirement on branch commits to be signed. I have configured commit sign with GPG and it works and I'm able to push commits.
While merging from another branch, VS Code automatically generats merge commit (in case of no conflict), but merge commit is not signed (not letting me to push). "Undo Last Commit" and committing it again manually works as a workaround.

VS Code version: Code - Insiders 1.80.0-insider (4649b5333370139d161e7b5d4f78ca13741efa35, 2023-06-28T08:04:29.699Z)
OS version: Linux x64 6.2.0-24-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|15.31GB (9.44GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id fa4bd95c-404d-49fa-baaf-1e9b5a15be36|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
copilot-chat|Git|0.3.2023062701
copilot-nightly|Git|1.93.195
vscode-github-actions|git|0.25.8
rest-client|hum|0.25.1
vscode-docker|ms-|1.25.1
csharp|ms-|1.26.0
volar|Vue|1.8.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
f8hc8238:30694864
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
bgfeh915:30769767
gsofb:30778559
dh2dc718:30776458
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
asynctokenver:30776452
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by lszomoru** [comment] 2024-12-12 08:51
Closing as duplicate of [#116913](https://github.com/microsoft/vscode/issues/116913)

**Closed by lszomoru** 2024-12-12 08:51 UTC
Labels: bug, git
