### ISSUE TITLE
Quick Fix actions have the wrong cursor type.

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#112804] opened 2020-12-18 09:37 UTC
- VSCode Version: 1.53
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Click on the quick fix button.
2. The list of actions appear, but the cursor is a text selection cursor when it should be a pointer.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-12-18 20:03
Works fine when clicking on the lightbulb:

![Screen Shot 2020-12-18 at 12 02 03 PM (2)](https://user-images.githubusercontent.com/12821956/102656595-f59aeb00-4128-11eb-8342-d99506588fbb.png)

But not when going through the problems menu:

![Screen Shot 2020-12-18 at 12 02 26 PM (2)](https://user-images.githubusercontent.com/12821956/102656649-09dee800-4129-11eb-9277-f2f9a9707a32.png)

**Comment by thebinarysearchtree** [comment] 2020-12-20 03:12
Does anybody know how to use devtools without making the popup menus and hover widgets disappear? Even pausing script execution doesn't work.

**Comment by thebinarysearchtree** [comment] 2020-12-20 12:16
It is because the hover widget is hidden and loses focus or something like that before the context menu is rendered. The lightbulb is not hidden when the context menu is shown, so there is no change in whatever is causing the problem.

**Comment by thebinarysearchtree** [comment] 2020-12-20 13:08
What is happening here is another kind of race condition. If you look at the code below, this.hide() tells the layout manager or whatever it is called that "at some point in the future, can you change the layout so that I am hidden. The problem is that the next line of code, which displays the context menu, usually finishes before the layout manager changes the layout. So it displays the context menu, but then the layout is changed and the context menu for whatever reason doesn't like things changing while it is being displayed.
```
disposables.add(this._renderAction(actionsElement, {
	label: nls.localize('quick fixes', "Quick Fix..."),
	commandId: QuickFixAction.Id,
	run: (target) => {
		showing = true;
		const controller = QuickFixController.get(this._editor);
		const elementPosition = dom.getDomNodePagePosition(target);
		// Hide the hover pre-emptively, otherwise the editor can close the code actions
		// context menu as well when using keyboard navigation
		this.hide();
		controller.showCodeActions(markerCodeActionTrigger, actions, {
			x: elementPosition.left + 6,
			y: elementPosition.top + elementPosition.height + 6
		});
	}
}));
```

**Comment by thebinarysearchtree** [comment] 2020-12-23 03:35
This appears to be due to the following process:

browser is asked to hide the element under the cursor
electron is asked to show the context menu

these two events are intertwined so that the browser first hides the element (or maybe not first), and then sets the cursor for the context menu, but then decides that because the element under the cursor has changed, it needs to check for the style of the new element that is now under the cursor, and then changes the cursor to whatever that styles says is the correct style and leaves it there.

You can add a 100ms delay to the call to create the actions list (the call after this.hide()), or you can use the approach I showed in #113230.

**Comment by sandy081** [comment] 2021-01-08 10:40
@thebinarysearchtree Thanks for detailed explanation. Whatever you said makes sense. I can add 100ms delay as workaround and fix this specific issue but #113230 appears after user hides the context menu without taking any action. Rather I would wait for the real fix.

**Comment by sandy081** [comment] 2021-01-08 10:40
Feel free to mark this as duplicate of #113230 if you think so

**Comment by rzhao271** [comment] 2021-01-08 16:44
Duplicate of #113230

**Closed** 2021-01-08 18:29 UTC
Labels: *duplicate
