### ISSUE TITLE
Edits to tasks.json don't take effect when Run Build Task is used (until a Reload Window is done)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#111538] opened 2020-11-30 20:38 UTC
- VSCode Version: Version: 1.52.0-insider (user setup) or 1.51.1
Commit: ac165d7f974d70212be80cb15eaecfc1fd20b21a
Date: 2020-11-30T17:36:25.607Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.19042
- OS: Host is Windows, remote target is Linux Ubuntu 20 (via WSL 2).

Steps to Reproduce:

1. Make a change to a task in tasks.json and run the task. For example, 
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "/usr/bin/gcc",
            "args": [
                "-Wall",
                "-DFOO='foo'",
                "${workspaceFolder}/test.c",
                "-o",
                "helloWorld"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "source": "gcc",
                "fileLocation": [
                    "autoDetect",
                    "${workspaceFolder}"
                ],
                "pattern": {
                    "regexp": "^(.*?):(\\d+):(\\d*):?\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
and add/remove the line with "-DFOO='foo'".

Bug: The changes to the tasks.json don't take effect until VS Code is reloaded. I originally wasn't reproing the bug with VS Code non-Insiders, but now I am.

See the screenshot:

![image](https://user-images.githubusercontent.com/19859882/100662130-53e26400-3309-11eb-9c9a-275b825f5c9d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-12-01 14:27
I think this a wsl file events issue. Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2310

**Closed by alexr00** 2020-12-01 14:27 UTC

**Comment by sean-mcmanus** [comment] 2020-12-01 18:18
Okay, you're right -- the issue goes away when I use a workspace that is on the remote Linux side.
