### ISSUE TITLE
Terminal process exit code 4294901760

### ISSUE THREAD

**Issue by hsmello** [microsoft/vscode#114830] opened 2021-01-23 12:22 UTC
Terminal does not open
message: 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.

**Comment by meganrogge** [comment] 2021-01-25 17:32
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by hsmello** [comment] 2021-01-25 22:07
@meganrogge , i am sorry for the incomplete report. thank you! details below:

This is the msg
![image](https://user-images.githubusercontent.com/60452857/105771755-f65d4300-5f58-11eb-9504-41f37f32f9e3.png)

settings.json
{
    "javascript.updateImportsOnFileMove.enabled": "always",
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "vue-html": "html",
        "razor": "html",
        "plaintext": "pug"
    },
    "window.zoomLevel": 0,
    "json.schemas": [
   
    ]
}

only one extension - REST Client 0.24.4

VS Code version 1.52.1 and i am on a windows 64-bit OS

**Comment by meganrogge** [comment] 2021-01-26 04:34
Thanks for the info. 

In the settings UI, what do you have the cwd set to?

**Comment by hsmello** [comment] 2021-01-26 20:35
hello!

it is empty

"terminal.integrated.cwd": ""

![image](https://user-images.githubusercontent.com/60452857/105901952-e6576900-6015-11eb-93b2-459c774637f5.png)

**Comment by meganrogge** [comment] 2021-01-27 03:25
Can you pls paste the output of this?

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by hsmello** [comment] 2021-01-27 20:36
Sure! Here it goes:

[2021-01-27 20:31:42.896] [renderer1] [trace] [storage state.vscdb] open(c:\Users\hugos\AppData\Roaming\Code\User\workspaceStorage\1611779409737\state.vscdb, retryOnBusy: true)
[2021-01-27 20:31:42.897] [renderer1] [trace] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[2021-01-27 20:31:42.897] [renderer1] [trace] [storage state.vscdb] getItems(): 24 rows
[2021-01-27 20:31:42.897] [renderer1] [trace] lifecycle: starting up (startup kind: 1)
[2021-01-27 20:31:42.897] [renderer1] [trace] lifecycle: phase changed (value: 2)
[2021-01-27 20:31:42.897] [renderer1] [trace] Skipping initializing user data in desktop
[2021-01-27 20:31:42.897] [renderer1] [trace] Layout#layout, height: 1040, width: 1920
[2021-01-27 20:31:42.897] [renderer1] [trace] workbench configuration {"_":[],"log":"trace","crash-reporter-id":"f4086fef-03f9-4b01-8563-5c2083bc95d7","logsPath":"C:\\Users\\hugos\\AppData\\Roaming\\Code\\logs\\20210127T203138","appRoot":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app","machineId":"fa7e6c8b380ee78e188f0c2d89cb8b54417d7829c96d17626484cb21c6c68a83","nodeCachedDataDir":"C:\\Users\\hugos\\AppData\\Roaming\\Code\\CachedData\\ea3859d4ba2f3e577a159bc91e3074c5d85c0523","mainPid":11868,"execPath":"C:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\1c64e14562e383b100206e84d562e431-1.52.1-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}"},"isInitialStartup":true,"backupPath":"C:\\Users\\hugos\\AppData\\Roaming\\Code\\Backups\\1611779409737","windowId":1,"sessionId":"window:1","logLevel":0,"zoomLevel":0,"colorScheme":{"dark":false,"highContrast":false},"autoDetectHighContrast":true,"maximized":true,"perfEntries":["main:started",1611779498601,"main:appReady",1611779498794,"willLoadMainBundle",1611779498800,"didLoadMainBundle",1611779498968,"main:loadWindow",1611779499197],"partsSplashPath":"C:\\Users\\hugos\\AppData\\Roaming\\Code\\rapid_render.json","os":{"release":"10.0.18363"}}
[2021-01-27 20:31:42.897] [renderer1] [trace] lifecycle: phase changed (value: 3)
[2021-01-27 20:31:42.897] [renderer1] [trace] Created Spdlogger
[2021-01-27 20:31:42.897] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {__$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1}}), delete(Set(1) {lifecyle.lastShutdownReason})
[2021-01-27 20:31:42.897] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2021-01-27 20:31:42.969] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:42.984] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:42.999] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:43.000] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1}')
[2021-01-27 20:31:43.469] [renderer1] [trace] Settings Sync: Initializing accounts
[2021-01-27 20:31:43.470] [renderer1] [trace] Settings Sync: Getting accounts for microsoft
[2021-01-27 20:31:43.528] [renderer1] [trace] [storage state.vscdb] Trace (event): DELETE FROM ItemTable WHERE key IN ('lifecyle.lastShutdownReason')
[2021-01-27 20:31:43.530] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\renderer1.log
[2021-01-27 20:31:43.555] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:43.559] [renderer1] [debug] User data changed
[2021-01-27 20:31:43.568] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\renderer1.log
[2021-01-27 20:31:43.569] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\output_1_20210127T203141
[2021-01-27 20:31:43.614] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\output_1_20210127T203141
[2021-01-27 20:31:43.621] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\output_1_20210127T203141
[2021-01-27 20:31:43.627] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2021-01-27 20:31:43.877] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\renderer1.log
[2021-01-27 20:31:43.877] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\output_1_20210127T203141
[2021-01-27 20:31:44.096] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\sharedprocess.log
[2021-01-27 20:31:44.231] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\exthost1
[2021-01-27 20:31:44.317] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\exthost1
[2021-01-27 20:31:44.361] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\telemetry.log
[2021-01-27 20:31:44.361] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\telemetry.log
[2021-01-27 20:31:44.365] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\telemetry.log
[2021-01-27 20:31:44.367] [renderer1] [trace] [File Watcher (node.js)] [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\userDataSync.log
[2021-01-27 20:31:44.585] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\sharedprocess.log
[2021-01-27 20:31:44.585] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\exthost1
[2021-01-27 20:31:44.586] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\telemetry.log
[2021-01-27 20:31:44.586] [renderer1] [trace] [File Watcher (node.js)] >> normalized [ADDED] c:\Users\hugos\AppData\Roaming\Code\logs\20210127T203138\userDataSync.log
[2021-01-27 20:31:44.605] [renderer1] [trace] CommandService#executeCommand extension.js-debug.clearAutoAttachVariables
[2021-01-27 20:31:44.669] [renderer1] [trace] lifecycle: phase changed (value: 4)
[2021-01-27 20:31:44.673] [renderer1] [trace] RequestService#request https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json
[2021-01-27 20:31:44.807] [renderer1] [trace] CommandService#executeCommand setContext
[2021-01-27 20:31:44.808] [renderer1] [trace] CommandService#executeCommand setContext
[2021-01-27 20:31:44.824] [renderer1] [trace] CommandService#executeCommand setContext
[2021-01-27 20:31:44.905] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {terminal.integrated.environmentVariableCollections => []}), delete(Set(0) {})
[2021-01-27 20:31:44.908] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2021-01-27 20:31:44.909] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('terminal.integrated.environmentVariableCollections','[]')
[2021-01-27 20:31:44.922] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2021-01-27 20:31:45.105] [renderer1] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-01-27 20:31:45.126] [renderer1] [trace] MainThreadTreeViews#$registerTreeViewDataProvider jsBrowserBreakpoints {"showCollapseAll":false,"canSelectMany":false}
[2021-01-27 20:31:45.146] [renderer1] [trace] Settings Sync: Updated accounts for microsoft
[2021-01-27 20:31:45.146] [renderer1] [trace] Settings Sync: Getting accounts for github
[2021-01-27 20:31:45.147] [renderer1] [trace] onWillActivateByEvent:  onAuthenticationRequest:github
[2021-01-27 20:31:45.220] [renderer1] [trace] Settings Sync: Updated accounts for github
[2021-01-27 20:31:45.224] [renderer1] [trace] Settings Sync: Account status changed from uninitialized to unavailable
[2021-01-27 20:31:45.225] [renderer1] [trace] Settings Sync: Accounts are initialized
[2021-01-27 20:31:45.907] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {terminal.integrated.environmentVariableCollections => [{"extensionIdentifier":"vscode.git","collection":[["VSCODE_GIT_IPC_HANDLE",{"value":"\\\\.\\pipe\\vscode-git-61a1a2d1bc-sock","type":1}],["GIT_ASKPASS",{"value":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh","type":1}],["VSCODE_GIT_ASKPASS_NODE",{"value":"C:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","type":1}],["VSCODE_GIT_ASKPASS_MAIN",{"value":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js","type":1}]]}]}), delete(Set(0) {})
[2021-01-27 20:31:45.910] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2021-01-27 20:31:45.910] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('terminal.integrated.environmentVariableCollections','[{"extensionIdentifier":"vscode.git","collection":[["VSCODE_GIT_IPC_HANDLE",{"value":"\\\\.\\pipe\\vscode-git-61a1a2d1bc-sock","type":1}],["GIT_ASKPASS",{"value":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh","type":1}],["VSCODE_GIT_ASKPASS_NODE",{"value":"C:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","type":1}],["VSCODE_GIT_ASKPASS_MAIN",{"value":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js","type":1}]]}]')
[2021-01-27 20:31:45.926] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2021-01-27 20:31:52.263] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2021-01-27 20:31:52.265] [renderer1] [trace] terminalInstance#ctor (id: 1) {}
[2021-01-27 20:31:52.684] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(2) {__$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1,"workbench.panel.hidden":0}, workbench.panel.hidden => false}), delete(Set(0) {})
[2021-01-27 20:31:52.728] [renderer1] [trace] IPty#spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [] {"name":"powershell.exe","cwd":"C:\\Users\\hugos","env":{"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\hugos\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_11868_UOZEAIBTXMXURKMY","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"DESKTOP-FH18CLT","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\hugos","LOCALAPPDATA":"C:\\Users\\hugos\\AppData\\Local","LOGONSERVER":"\\\\DESKTOP-FH18CLT","NUMBER_OF_PROCESSORS":"4","OneDrive":"C:\\Users\\hugos\\OneDrive - ISEG","OneDriveCommercial":"C:\\Users\\hugos\\OneDrive - ISEG","OneDriveConsumer":"C:\\Users\\hugos\\OneDrive","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","Path":"C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Plantronics\\Spokes3G\\;C:\\Program Files\\nodejs\\;C:\\Users\\hugos\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\hugos\\AppData\\Local\\GitHubDesktop\\bin;C:\\Program Files\\heroku\\bin;C:\\Users\\hugos\\AppData\\Roaming\\npm","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 101 Stepping 1, AuthenticAMD","PROCESSOR_LEVEL":"21","PROCESSOR_REVISION":"6501","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PROMPT":"$P$G","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SystemDrive":"C:","SystemRoot":"C:\\WINDOWS","TEMP":"C:\\Users\\hugos\\AppData\\Local\\Temp","TMP":"C:\\Users\\hugos\\AppData\\Local\\Temp","USERDOMAIN":"DESKTOP-FH18CLT","USERDOMAIN_ROAMINGPROFILE":"DESKTOP-FH18CLT","USERNAME":"hugos","USERPROFILE":"C:\\Users\\hugos","windir":"C:\\WINDOWS","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.52.1","LANG":"en_US.UTF-8","COLORTERM":"truecolor","VSCODE_GIT_IPC_HANDLE":"\\\\.\\pipe\\vscode-git-61a1a2d1bc-sock","GIT_ASKPASS":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh","VSCODE_GIT_ASKPASS_NODE":"C:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_GIT_ASKPASS_MAIN":"c:\\Users\\hugos\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js"},"cols":0,"rows":0,"useConpty":true,"conptyInheritCursor":false}
[2021-01-27 20:31:52.784] [renderer1] [debug] Terminal process ready (shellProcessId: 7996)
[2021-01-27 20:31:52.832] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2021-01-27 20:31:52.874] [renderer1] [trace] IPty#resize 261 11
[2021-01-27 20:31:52.882] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:52.964] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:52.968] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1,"workbench.panel.hidden":0}'),('workbench.panel.hidden','false')
[2021-01-27 20:31:52.972] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:52.976] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2021-01-27 20:31:53.177] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\hugos\AppData\Roaming\Code\User\globalStorage
[2021-01-27 20:31:53.179] [renderer1] [debug] User data changed
[2021-01-27 20:31:53.886] [renderer1] [trace] IPty#kill
[2021-01-27 20:31:53.902] [renderer1] [debug] Terminal process exit (id: 1) with code undefined
[2021-01-27 20:31:53.902] [renderer1] [debug] Terminal process exit (id: 1) state 5
[2021-01-27 20:31:53.903] [renderer1] [trace] terminalInstance#dispose (id: 1)
[2021-01-27 20:31:54.033] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {__$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1}}), delete(Set(1) {workbench.panel.hidden})
[2021-01-27 20:31:54.048] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2021-01-27 20:31:54.050] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.panel.placeholderPanels":1,"memento/workbench.parts.editor":1,"editors.mru":1,"history.entries":1,"memento/workbench.editor.walkThroughPart":1,"workbench.panel.repl":1,"vscode.debug-auto-launch":1,"terminal.integrated.environmentVariableCollections":1,"terminal.numberOfVisibleViews":0,"memento/workbench.editors.logViewer":1,"codelens/cache2":1}')
[2021-01-27 20:31:54.054] [renderer1] [trace] [storage state.vscdb] Trace (event): DELETE FROM ItemTable WHERE key IN ('workbench.panel.hidden')
[2021-01-27 20:31:54.054] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2021-01-27 20:31:56.607] [renderer1] [trace] KeybindingService#dispatch F1 workbench.action.showCommands
[2021-01-27 20:31:56.607] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2021-01-27 20:31:58.205] [renderer1] [trace] KeybindingService#dispatch Ctrl+V editor.action.clipboardPasteAction
[2021-01-27 20:31:58.205] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardPasteAction
[2021-01-27 20:31:59.401] [renderer1] [trace] CommandService#executeCommand workbench.action.openLogFile


also a prit of a part of it that might be easier to read
![image](https://user-images.githubusercontent.com/60452857/106050538-35b59c00-60df-11eb-9d46-76f73ce8b99d.png)

**Comment by meganrogge** [comment] 2021-01-27 21:40
Thanks for that info. I think this is a duplicate of this issue. https://github.com/microsoft/vscode/issues/100366#issuecomment-645322374

**Closed** 2021-01-27 21:41 UTC
Labels: *duplicate, integrated-terminal
