### ISSUE TITLE
Does not launch file in anaconda shell in VS Code

### ISSUE THREAD

**Issue by kosta2222** [microsoft/vscode#133137] opened 2021-09-15 06:50 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version:win32

Steps to Reproduce:

1.create file settings.json with with 

{
    "python.pythonPath": "D:\\user_win_home\\code\\python_new3\\test_keras_gensim\\envs\\python.exe",
    "terminal.integrated.profiles.windows": {
        
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/K", "activate",  "D:\\user_win_home\\code\\python_new3\\test_keras_gensim\\envs"],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "terminal.integrated.automationShell.windows":{
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/K", "activate",  "D:\\user_win_home\\code\\python_new3\\test_keras_gensim\\envs"],
            
        },
    },
    
    
}
2. Launch terminal (it comes as activated anaconda terminal)
3. Right mouse click on current Python file and Run Current Python File in Terminal
4. But VS Code Ide launches PowerShell Terminal with python interpreter and my file
5. In last version VS Code Ide I could launch python files in anaconda environment(shell)

**Comment by karthiknadig** [comment] 2021-09-27 16:42
@meganrogge  This looks like it is a duplicate of this VS Code issue https://github.com/microsoft/vscode/issues/132150

@kosta2222 Can you try with the latest insiders version of VS Code and see if it is addressed there?

**Comment by kosta2222** [comment] 2021-09-28 04:49
Not right now, now I use >python app.py in my anaconda shell.

  
>Понедельник, 27 сентября 2021, 19:43 +03:00 от Karthik Nadig ***@***.***>:
> 
> 
***@***.*** This looks like it is a duplicate of this VS Code issue  #132150
***@***.*** Can you try with the latest insiders version of VS Code and see if it is addressed there?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Константин Мухамеджанов Котибович

**Closed** 2021-09-28 21:50 UTC
Labels: needs more info
