### ISSUE TITLE
Built-in git extension can be disabled but not re-enabled

### ISSUE THREAD

**Issue by sunnycarter** [microsoft/vscode#154147] opened 2022-07-05 09:43 UTC
Issue Type: <b>Bug</b>

I had problems where vscode had lost my git.path. I tried to resolve this by disabling and re-enabling the Git built-in extension.  I could press Disable, and then Reload Required. After this, I went to Enable the extension, but hitting Enable throws the error 
"Cannot change enablement of Git Base extension because of its extension kind".

I can re-enable it for the workspace only, but this leaves me having disabled Git for all my workspaces, and only able to re-enable it on a per-workspace basis. I have many of them, so this is tedious and means I need to remember for any new workspace.

Surely if I am not allowed to Enable git globally because of its extension kind, I shouldn't be allowed to Disable it globally either, and get into this state??

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.06GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+metaswitch-dev/home/developer/code/vnfdgen2 --remote=wsl+metaswitch-dev --crash-reporter-id 308376c3-222d-4084-a187-c0517c2abd22|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: metaswitch-dev|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.42GB (8.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: metaswitch-dev|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.42GB (8.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: metaswitch-dev|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.42GB (8.55GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
yang|mar|0.1.3
vscode-azurevirtualmachines|ms-|0.6.2
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
rewrap|stk|1.16.3
armview|ben|0.4.6
git-diff-and-merge-tool|dav|1.0.5
gitlens|eam|12.1.1
go|gol|0.34.1
azure-pipelines|ms-|1.205.0
vscode-azureappservice|ms-|0.24.2
vscode-azurefunctions|ms-|1.7.3
vscode-azureresourcegroups|ms-|0.5.3
vscode-azurestaticwebapps|ms-|0.11.1
vscode-azurestorage|ms-|0.14.1
vscode-azurevirtualmachines|ms-|0.6.2
vscode-bicep|ms-|0.8.2
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.8.1
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.4.0
vsliveshare|ms-|1.0.5625
azurerm-vscode-tools|msa|0.15.7
autodocstring|njp|0.6.1
run-on-save|puc|1.5.1
rust-analyzer|rus|0.3.1115

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30519255
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by sandy081** [comment] 2022-07-06 17:55
Seems to me a duplicate of https://github.com/microsoft/vscode/issues/153171

@sunnycarter Can you please try our [insiders](https://code.visualstudio.com/insiders/) and check if you can still repro it?

**Comment by lszomoru** [comment] 2022-07-07 07:27
Closing as duplicate for now.

**Closed by lszomoru** 2022-07-07 07:27 UTC
Labels: bug, git, extensions
