### ISSUE TITLE
Font rendering in setting while searching looks ugly on Linux (KDE - Fedora)

### ISSUE THREAD

**Issue by voxelin** [microsoft/vscode#171475] opened 2023-01-17 10:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: KDE Plasma: 5.26.5, Fedora: 37, X11

Steps to Reproduce:

1. Open settings tab
2. Search for some param.

![image](https://user-images.githubusercontent.com/78281477/212878939-72d6cb6c-e090-482b-a49a-a81bf94b06cf.png)

**Comment by rzhao271** [comment] 2023-01-17 21:56
Duplicate of https://github.com/microsoft/vscode/issues/170699, but also, does this issue occur when running code with `--disable-gpu`?

**Closed** 2023-01-18 13:28 UTC
