### ISSUE TITLE
1.8.0 is getting crashed or not responding frequently

### ISSUE THREAD

**Issue by sivaecekrr** [Microsoft/vscode#17447] opened 2016-12-17 05:05 UTC
- VSCode Version: 1.8.0
- OS Version: Win 7 Enterprise, 16GB RAM

Steps to Reproduce:

1. Open a project, and open integrated terminal.

Visual Studio Code 1.8.0 is **getting crashed or not responding frequently**. I could not use VS Code efficiently.
VS Code is also taking lot of system memory. Can you suggest the solution.
FYI, I am login as user and not as administrator. Thanks in advance.

**Comment by kieferrm** [comment] 2016-12-17 14:45
@sivaecekrr what extensions have you installed? What kind of folder is it? Do you do anything else other than open the folder and open the terminal. Any commands you run? Do you open editors? If so, what type of files? Thanks!

**Comment by sivaecekrr** [comment] 2016-12-21 05:19
@kieferrm Installed angular1,angular2 by johnpapa and vscode-icons extensions. I have tried to open yeoman project folder which contain js files and tried to run grunt commands in the terminal.
After opening the VS Code and started typing, within some time it got stuck and not responding message shown and got crashed. 
Thanks.

**Comment by egamma** [comment] 2016-12-21 16:42
@sivaecekrr can you verify that you have the latest version of the vscode-icons extension installed. Older versions of this extensions relied on patching the VS Code application files. This has resulted in crashes. The latest version of vscode-icons is no longer doing this.

The other thing to try out is to start VS Code without any extensions by starting it up with the command line option `--disable-extensions`

**Comment by lilling** [comment] 2016-12-21 23:07
I have this problem to when I ran npm install on the integrated terminal.

I have this extensions:

![image](https://cloud.githubusercontent.com/assets/11631465/21409455/fffc5322-c7e2-11e6-8bc5-108379f51569.png)

**Comment by sivaecekrr** [comment] 2016-12-22 05:30
@egamma No luck even after disabling extension. I have latest extensions installed. When i run without elevated rights ctrl + ` open integrated terminal with empty window and it was loading...
Is admin rights is necessary to run VS Code ?
Thanks.

**Comment by egamma** [comment] 2016-12-22 13:24
@sivaecekrr 

>Is admin rights is necessary to run VS Code ?

No, we do not recommend to run VS Code with admin rights.

**Comment by sivaecekrr** [comment] 2016-12-22 13:28
But when i run with elevated access integrated terminal is working.
Is there any path where error logs getting generated ??

**Comment by yusijs** [comment] 2017-01-17 20:49
Fwiw, I'm having the exact same issue on Windows 10. Npm install & yarn both crash if ran in the integrated terminal.

**Comment by dbaeumer** [comment] 2017-01-18 08:26
@Tyriar any idea why the integrated terminal is causing problems when not run in admin mode?

**Comment by Tyriar** [comment] 2017-01-18 16:10
I haven't heard anything like this before.

@yusijs what do you mean by "crash" in the integrated terminal? VS Code crashes after it's run? npm/yarn error out (due to permissions)?

@sivaecekrr can you take a screenshot of what happens when you open the terminal? Also checking dev tools (Help > Toggle Developer Tools) console for errors would be useful.

**Comment by yusijs** [comment] 2017-01-18 16:22
Terrible wording on my part. In my defence, I was rly tired. 😴

Anyways, what happens is:

I start either yarn or npm install
Midway through the install freezes, and the entire VSCode window freezes. I then need to click X about 27 times (entire window is unclickable, except the top toolbar) before I get a prompt that the window is not responding. This happens other times as well, but seems to mainly happen during yarn / npm install. It's very frustrating, as integrated terminal is a lot easier than using cmd externally. This doesnt happen on debian, and havent tried reproducing on Win7, but def happens consistently on Win10.

**Comment by Tyriar** [comment] 2017-01-18 18:19
Does this happen when you run it through powershell?

Also are you on Windows 10 Insiders? There's a conhost/cmd.exe CPU issue on Insiders I'm aware of https://github.com/Microsoft/vscode/issues/18424

**Comment by yusijs** [comment] 2017-01-18 19:09
Not sure how I can use powershell integrated - it only gives me cmd.exe in the dropdown as far as I can recall. Not at my pc now, will look tomorrow to verify this. 

Not on insiders

**Comment by Tyriar** [comment] 2017-01-18 20:46
You can set powershell by adding this to your settings.json:

```js
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
```

**Comment by dbaeumer** [comment] 2017-01-21 15:19
@Tyriar assigning to you  to track down the terminal problem

**Comment by cgatian** [comment] 2017-02-01 01:27
Also occurs for me on two different Windows 10 machines.  
VSCode: 1.8.1
![image](https://cloud.githubusercontent.com/assets/1752170/22491454/877b140e-e7f1-11e6-8977-9f557dafd780.png)

Running `yarn add <module> -D` causes freeze.
* Dev tools does not show any errors, and remains unfrozen
* Running command in a separate window (not the integrated terminal) also freezes VS Code
* Tried running VSCode as Admin and did not change behavior.
* Disabling plugins prevents crash
     * How do I re-enable the extensions? Removing the command line did not work

**Comment by Tyriar** [comment] 2017-02-01 05:39
> - Running command in a separate window (not the integrated terminal) also freezes VS Code

Running `yarn` in an external terminal freezes VS Code?

**Comment by cgatian** [comment] 2017-02-01 12:11
@tyriar Yes. 

I don't know about just the yarn command, but npm install <DEP> and yarn add <DEP> do it.

**Comment by Tyriar** [comment] 2017-02-01 21:33
@cgatian you're likely seeing a different issue related to an extension (as it doesn't happen when you disabled them).

**Comment by snerks** [comment] 2017-02-28 15:16
I see that you have some Typescript-related extensions.

This issue may be similar to what you are seeing:
https://github.com/buehler/typescript-hero/issues/86

**Closed** 2017-03-01 18:50 UTC
Labels: freeze-slow-crash, needs more info
