### ISSUE TITLE
italic fonts between * * in markdown

### ISSUE THREAD

**Issue by Uykusu** [Microsoft/vscode#43629] opened 2018-02-14 02:01 UTC
### Issue Type
Bug

### Description

VS Code seems to show some differences between markdown tags in editor directly when editing markdown files. But the *italic* seems having a bug.
![markdown bug](https://user-images.githubusercontent.com/32985998/36184164-0b6d84ae-116d-11e8-9a84-ddd22c6dec6b.PNG)

In markdown syntax only when both sides of the * are space the * symbol will not be treated as a italic tag. However in VS Code if either side of the * are space this * symbol won't be treated as a italic tag.

Is it a feature or a bug? I'm not sure for certain.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.3.9600

**Comment by shobhitchittora** [comment] 2018-02-14 07:07
+1 on this. This exists in Code 1.20.0 (c63189d, 2018-02-07T17:09:39.780Z), but not in Code Insiders Version 1.21.0-insider (1.21.0-insider).

**Comment by shobhitchittora** [comment] 2018-02-14 07:12
Duplicate / Fixed in - #41466.

**Comment by iskandergaba** [comment] 2018-02-14 10:43
Also, when using `***text***` the editor weirdly leaves the last asterisk NOT highlighted.
![bug](https://user-images.githubusercontent.com/18679771/36200187-8b2cfa64-1184-11e8-9203-99cbf385e1d1.png)

**Comment by mjbvz** [comment] 2018-02-14 19:28
Duplicate of #43150. Should be fixed in the latest insiders

**Closed by mjbvz** 2018-02-14 19:28 UTC
Labels: markdown
