### ISSUE TITLE
Organize Imports Removes Aliased Imports

### ISSUE THREAD

**Issue by Bibliofile** [Microsoft/vscode#47362] opened 2018-04-06 22:30 UTC
Issue Type: <b>Bug</b>

1. Create the following files
    a.ts
    ```ts
    export const a = 1
    ```
    b.ts
    ```ts
    import { a as b } from './a'
    console.log(b * 5)
    ```

1. Run Organize Imports on `b.ts`

1. The import is removed, even though it is used.

VS Code version: Code - Insiders 1.23.0-insider (95101bf3f6d00105621cdddb639ea62b95ea2468, 2018-04-06T08:49:48.798Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
code-spell-checker|str|1.6.5

</details>

**Comment by Bibliofile** [comment] 2018-04-06 22:32
I also see this issue in the latest non-insiders version.

**Comment by mjbvz** [comment] 2018-04-06 22:34
Duplicate of #47310

**Closed by mjbvz** 2018-04-06 22:34 UTC
Labels: insiders
