### ISSUE TITLE
1.55.0 - Incorrect behavior for gotoLocation.multipleDeclarations

### ISSUE THREAD

**Issue by bmichotte** [microsoft/vscode#120627] opened 2021-04-06 12:21 UTC
- VS Code Version:
```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z (6 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
``` 
```
Version: 1.56.0-insider (Universal)
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:13:17.592Z (4 days ago)
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
``` 
- OS Version:
Big Sur 11.2.3

Does this issue occur when all extensions are disabled?: Yes

Hello,

with `editor.gotoLocation.multipleDeclarations` sets to `"goto"`

In a React/Typescript project, prior to 1.55.0, when you ⌘-click a Tag, you were sent to the component, now, you are sent to the type defintion of React. But if you ⌘-click on the closing tag, you are sent to the correct component.

You can see the problem here
![CleanShot 2021-04-02 at 10 45 39](https://user-images.githubusercontent.com/235510/113709704-1b9dc880-96e3-11eb-80fc-50925b7fadb7.gif)

**Comment by mjbvz** [comment] 2021-04-27 02:07
Duplicate of #121003. If you still see this in VS code insiders, please share a self contained example that demonstrates the issue (as text)

**Closed by mjbvz** 2021-04-27 02:07 UTC
