### ISSUE TITLE
Make history navigation aware of editor groups

### ISSUE THREAD

**Issue by xckai** [microsoft/vscode#9526] opened 2016-07-20 08:44 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.open a file in editor 1;
2.open same file in other editor 2(ctrl +2 side editor)
3. in editor 1 move cursor   to line 1 and then to line 2
4 in editor 2 move cursor to line 3 and then to line 4
5 click mouse backward button in editor 1 the cursor back to  line 4 but i want to line 1

It seems every file have one  cursor backward stack,and all side editor share it?
Regards

**Comment by bpasero** [comment] 2016-08-05 10:50
That might well be an issue, have to check.

**Comment by bpasero** [comment] 2016-08-08 15:08
Open for PRs here. Currently our Back/Forward navigation ignores the location of the editor in the UI. The code lives in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L222

**Comment by bpasero** [comment] 2017-09-08 07:26
Challenge here is what to do when a editor group moves, either via explicit gesture from the user or by closing a group to the left. I think it will be hard to restore whatever the user did over time.

**Comment by bpasero** [comment] 2018-05-24 10:37
Note to self:
* Add commands to navigate tabs in MRU order without picker (https://github.com/Microsoft/vscode/issues/15319)
* Add an editor picker that allows to navigate editors in MRU order across groups (https://github.com/Microsoft/vscode/issues/37366)

Having group-awareness in the history stack would enable both features:
* MRU navigation without picker requires to use the history stack in that specific group
* MRU navigation across groups requires a new view on the history that is group aware

**Comment by riverinyo** [comment] 2020-05-15 18:49
(VSCode 1.45.0, MacOS Catalina)

Split editor, navigates back to different editor:
1. open split editor on file A and move cursor to a different point.
2. go to definition from editor 1, which opens file B
3. go back moves the cursor on editor 2 and leave open file B in editor 1
=> Lost the reference I was looking at in both editors.

**Comment by tonysparks** [comment] 2020-10-09 19:01
Is this being prioritized? Much like @Matmo10 said, this issue is killing the experience for me.

**Comment by replay** [comment] 2020-10-09 20:53
This issue is a pain-point for me too.

**Comment by Timmmm** [comment] 2020-10-13 21:16
Made a simple attempt [here](https://github.com/Timmmm/vscode/commit/5529ddc166109efebb246b49cebe9355367a9f77) but it doesn't quite work right yet for the reasons explained in the commit history. Definitely need to think more about how it should work.

If someone wanted to do a survey of other sane editors (i.e. Qt Creator, Sublime Text, etc. not Eclipse or Vim) that would be great!

**Comment by Matmo10** [comment] 2020-10-14 06:03
IntelliJ/Webstorm gets this right IMO. The behavior there Just Works ™

**Comment by Timmmm** [comment] 2020-10-14 20:57
Hmm I think I don't understand this bug then, because as far as I can tell IntelliJ behaves the same as VSCode. The bug I want to solve is that going forward and back jumps you between editor groups - I want to stay within an editor group when I go forward and back.

Is this bug actually about an issue with having *the same file* open in different editor groups? The description isn't totally clear. Maybe someone could make a video of the issue.

**Comment by tlemo** [comment] 2020-10-14 22:37
Please take a look at the repro steps in #98216

**Comment by Timmmm** [comment] 2020-10-16 13:55
I see. Unfortunately this is not trivial to fix. Editors are represented by the `EditorInput` class, but VSCode treats editors for the same file as equivalent. `EditorInput` has no `id` field that is unique to each editor. Essentially the data model is like this:

**Comment by Timmmm** [comment] 2020-10-16 14:05
> It won't work properly if you... close entire editor groups though.

Actually I take that back. Editor groups have IDs that are stable even if you close other ones.

**Comment by tlemo** [comment] 2020-10-17 01:57
Thanks for the explanation. I'm not familiar with VS Code's internals, but from outside there is obvious per-editor state (cursor position for example), so I assume that this state must be tracked somehow and also have an identity. Am I wrong?

**Comment by Timmmm** [comment] 2020-10-17 13:13
Ok I have a basic implementation of this done now, there's one thorny issue: when you click in another editor to activate it in such a way that *also* moves the cursor, you get two events, sort of like this:

* `activeEditorChanged(group 1)`
* `editorSelectionChanged(group 1, line 20)`

Each of those creates a history event (the first one for the line where the cursor was previously). This means when you go `back()` in an editor after doing that it will jump to the original position of the cursor first.

The problem is there is no way to distinguish that case from when you activate an editor without moving the cursor (e.g. by clicking the tab), and then later move the cursor. It generates the exact same sequence of events but in that case you *do* want two history events.

Although actually I just tested and this was already an issue, so maybe it's fine to leave it.

**Comment by Timmmm** [comment] 2020-10-21 20:55
Ok here is a demo, the top is before - when you go back it goes to the wrong editor group. Bottom is after.

![navigation_fix_opt](https://user-images.githubusercontent.com/376842/96786293-f85ab780-13e7-11eb-955c-894d26248b82.gif)

And yes that is a glorious 5 MB, 16 colour GIF. Thanks Github for supporting modern video formats.

**Comment by tonysparks** [comment] 2021-04-02 13:56
This is still a major issue -- any plans on this getting addressed?

**Comment by labsurde** [comment] 2021-05-26 04:59
This issue has been open for long time and I have been looking forward to seeing this feature whenever a new version was released. :-)

I experience this issue especially when I edit a file with long line. In one editor _A_, I write my code in the file and , in another editor _B_ I refer to other piece of code in the same file.... but when I do `go back`, everything goes messy, making 'split editor' feature useless in my usage case. 

Please enhance this experience...!! Thanks!!!

**Comment by hongwen000** [comment] 2022-01-07 12:50
This problem is still here in 2022

**Comment by aloucks** [comment] 2022-01-07 17:40
It's extremely frustrating. I'm plagued by this issue daily. There needs to be an option to limit back and forward navigation to the current editor group.

**Comment by ppggff** [comment] 2022-01-27 04:13
@bpasero @yume-chan Any plan to fix this in 2022?

**Comment by jasonwilliams** [comment] 2022-02-02 23:14
Seems @Timmmm came close with https://github.com/microsoft/vscode/pull/109110 but it sort of faded, maybe someone needs to pick it up

**Closed** 2022-02-07 14:08 UTC
Labels: feature-request, workbench-history

**Comment by bpasero** [comment] 2022-02-07 14:13
With https://github.com/microsoft/vscode/pull/142152, standard navigation actions "Go Back", "Go Forward" and "Go Previous" now take the editor group into consideration when navigating. This means navigation is now strictly going through editors in editor groups as the editors changed and no longer seemingly random. 

Note that removing an editor group will drop all history entries from all editors for that group. This is a somewhat breaking change from how it used to be.

Moving an editor from one group to another will however preserve history.

I am open for feedback once this is available in insiders (tomorrow). You can give our preview releases a try from: https://code.visualstudio.com/insiders/
