### ISSUE TITLE
1.57.0 (macos): Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by daiyam** [microsoft/vscode#126185] opened 2021-06-13 22:07 UTC
When opening VSCode, I'm getting the error `Extension host terminated unexpectedly.`

In the Developer Tools, I'm getting the following errors:
```
ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, vscode.npm, vscode.debug-auto-launch, vscode.git
ERR Error: No authentication provider 'microsoft' is currently registered.
    at O.getSessions (authenticationService.ts:720)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async bi.getAccounts (userDataSyncWorkbenchService.ts:209)
    at async bi.update (userDataSyncWorkbenchService.ts:194)
    at async bi.initialize (userDataSyncWorkbenchService.ts:168)
    at async bi.waitAndInitialize (userDataSyncWorkbenchService.ts:149)
WARN Settings Sync: Accounts are not initialized
dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylibdyld: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylib
```

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: macOS 10.11

Steps to Reproduce:

1. Open VSCode
2. Open a project (for example vscode)

**Comment by febrifahmi** [comment] 2021-06-13 22:23
Looks like I have the same [issue](https://github.com/microsoft/vscode/issues/126150) also on my mac 10.11. Extension host terminated unexpectedly, the first message on debugger was:

> (node:528) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)


After "debugger attached, the the warning is `"IPC "Search" crashed with exit code null and signal SIGTRAP"`.

And then:

> dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylibdyld: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylib

And then the Extension host terminated.

**Comment by elder-n00b** [comment] 2021-06-14 03:51
Confirmed on 10.11.6.
I wonder how hard it is to check the OS version before updating?

**Comment by alexdima** [comment] 2021-06-14 17:01
Duplicate of https://github.com/microsoft/vscode/issues/125989


**Workaround:** none today, you can go back to `1.56.2` via [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin-universal.zip) and configure `update.mode` to `none` or `manual`.

**Closed by alexdima** 2021-06-14 17:01 UTC
Labels: new release

**Comment by jeanniton-mnr** [comment] 2021-06-20 09:46
> Duplicate of #125989
> 
> **Workaround:** none today, you can go back to `1.56.2` via [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin-universal.zip) and configure `update.mode` to `none` or `manual`.

Your solution is working for me.
Thank you
