### ISSUE TITLE
Structural selection ignored because of line selection

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67390] opened 2019-01-29 11:55 UTC
Issue Type: <b>Bug</b>

Testing #67277

I like the structural expansion:

![jan-29-2019 12-51-49](https://user-images.githubusercontent.com/9205389/51906661-e7247880-23c4-11e9-85d2-51e5eeeb4ef9.gif)

Line expansion can get in its way (note that at no stage is the entire array without the brackets selected):
![jan-29-2019 12-52-52](https://user-images.githubusercontent.com/9205389/51906726-133ff980-23c5-11e9-87c0-6b0089b2fd41.gif)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by aeschli** [comment] 2019-01-31 08:39
The line selections come from the default selection provider which merges into the semantic ranges. I personally think it makes sense to also provide line selections when expanding selection.
Moving to @jrieken for comments.

**Comment by jrieken** [comment] 2019-01-31 08:42
The line discussion is happening here: #67491

**Comment by jrieken** [comment] 2019-01-31 08:43
Looking at the second gif I agree with @chrmarti that the array should be selected and I don't think the the default line selection tampers with that.

**Comment by aeschli** [comment] 2019-01-31 10:09
![jan-29-2019 12-52-52](https://user-images.githubusercontent.com/9205389/51906726-133ff980-23c5-11e9-87c0-6b0089b2fd41.gif)

Hm, interesting.

The cursor starts just before the ']'. The first `expand` selects the bracket, placing the cursor after the bracket. The next expand then uses the position after the bracket, and the JSON selection provider wouldn't return the range inside the brackets anymore, as this is outside of the current position.

Without the line selection that wouldn't happen...

**Comment by jrieken** [comment] 2019-01-31 10:16
> he next expand then uses the position after the bracket, and the JSON selection provider wouldn't return the range inside the brackets anymore, as this is outside of the current position.

No, that's not how it works. All providers are asked for their ranges from the *same* position (there is only one request) and then ranges are merged. 

@aeschli Are you sure your provider computes the correct result in case above?

**Comment by aeschli** [comment] 2019-01-31 10:45
I can confirm that there's only one call.
For 
```
[

]
```
it returns both the ranges (inside and outside brackets):
```
[Trace - 11:43:31 AM] Received response '$/textDocument/selectionRange - (27)' in 3ms.
Result: [
    {
        "start": {
            "line": 0,
            "character": 1
        },
        "end": {
            "line": 2,
            "character": 0
        }
    },
    {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 2,
            "character": 1
        }
    }
]
```
Looks like the second invocation of `expand selection` decides to no longer use the inner selection.

**Comment by jrieken** [comment] 2019-01-31 10:58
Looks like an issue with the range merge logic...

**Comment by jrieken** [comment] 2019-01-31 12:05
That's now how it works - instead of expanding just the current line it expands more blocks/lines as described in #67491

![jan-31-2019 13-04-41](https://user-images.githubusercontent.com/1794099/52053130-d147bc80-2558-11e9-9660-43f69a4d3fcc.gif)

**Closed** 2019-01-31 13:02 UTC
Labels: bug, smart-select
