### ISSUE TITLE
Version 1.18.0 (1.18.0) Just Updated no longer folds code correctly 

### ISSUE THREAD

**Issue by macasas** [Microsoft/vscode#38438] opened 2017-11-15 18:21 UTC
Open a file that used to use code folding correctly, and now you have a plus sign and a small ... link where there is no code to expand.

CMD K CMD J to unfold everything, still have plus signs where there should be minus

Screenshots showing same blocks open and closed, both with +

![screen shot 2017-11-15 at 19 20 27](https://user-images.githubusercontent.com/910082/32853011-262b954e-ca3a-11e7-916d-714887f05107.png)

![screen shot 2017-11-15 at 19 20 40](https://user-images.githubusercontent.com/910082/32853016-2c27cd00-ca3a-11e7-89b6-b0a136eaa54a.png)

**Comment by macasas** [comment] 2017-11-15 18:29
If you put the cursor at the end of the line and hit Enter, it resets that individual fold, but life must be too short to do them all manually.

**Comment by roblourens** [comment] 2017-11-15 21:00
Does this happen every time? Only with a certain code snippet? If so can you post the code as text?

**Comment by aeschli** [comment] 2017-11-16 09:22
Can you check if there is anything in the dev console? Help > Toggle Developer Tools

**Comment by aeschli** [comment] 2017-11-17 11:59
I think this is a dup of #38527. It's fixed in the insiders build, so if you can verify that it's fixed now, that would be great.

**Comment by SidIcarus** [comment] 2017-11-17 16:03
@aeschli I believe it is as well

i didn't realize the root of the issue at first because the file was opened twice but on the second panel it was not focused so it took me a few minutes to wade through possibilities.

**Comment by aeschli** [comment] 2017-11-20 16:47
Thanks, closing as duplicate of #38527 then

**Closed by aeschli** 2017-11-20 16:47 UTC
Labels: editor, editor-folding, needs more info
