### ISSUE TITLE
Duplicate file tabs issue (related to path casing) is back

### ISSUE THREAD

**Issue by paterasMSFT** [Microsoft/vscode#49310] opened 2018-05-06 15:44 UTC
- VSCode Version: 1.23.0
- OS Version: Windows 10

The same file is opening multiple tabs. The only difference appears to be the that the casing of the paths of the two files is different.

This was an issue that I believe was resolved in 1.22, but I've seen it several times again in 1.23. Not sure how to reproduce. Previously it happened when something was renamed, but that doesn't seem to be the case anymore.

**Comment by bpasero** [comment] 2018-05-07 04:12
There was no fix made so far. Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-05-07 04:12 UTC
Labels: new release
