### ISSUE TITLE
No text wrapping of long problem descriptions from build task output.

### ISSUE THREAD

**Issue by Kile-D-Asmussen** [microsoft/vscode#136281] opened 2021-11-02 10:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Create C# programming project 
2. Configure build task to problem match in the usual manner
3. Generate a long problem message by e.g. incorrectly implementing an interface.
4. Increase font size and UI zoom level appropriately to a low vision user.
5. Press F8 to step to the long problem message.

Type: Accessibility.

Observed behavior:

The problem text detailing what is wrong with the code is too long to be displayed and trails off screen. Additionally for very long problem messages, the problem does not even display in the problems console pane.

Expected behavior:

The text should wrap. The problem exists even with a small font and no UI zoom, but is all the more pronounced for low vision users.

Workaround:

By mousing over the problem line in the console, the entire problem text is displayed as a tool tip, but only on the problem that is not currently being inspected.

Image example:

![wrap-text](https://user-images.githubusercontent.com/2027463/139827202-6777a1b9-15d9-462b-ac72-59ca2a0f5d83.png)

**Comment by jrieken** [comment] 2021-11-03 08:17
We don't wrap the text because error messages often use ASCII-art like formatting. However, the message itself can be scrolled horizontally when this happens. 

Closing this issue as duplicate of https://github.com/microsoft/vscode/issues/116338 which asks for making the scrollbar more prominent

**Comment by jrieken** [comment] 2021-11-03 08:18
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"languages-diagnostics"

**Closed by jrieken** 2021-11-03 08:17 UTC
Labels: languages-diagnostics
