### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by souru98** [microsoft/vscode#132679] opened 2021-09-08 17:35 UTC
Issue Type: <b>Bug</b>

bugs

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.57GB free)|
|Process Argv|--crash-reporter-id fa0710cb-6e14-4533-8dca-02665e773ea4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
vscode-browser-preview|auc|0.7.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
codestream|Cod|11.0.14
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
vscode-colorize|kam|0.11.1
vscode-github|Kni|0.30.6
start-git-bash|McC|1.2.1
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
material-icon-theme|PKi|4.10.0
rcore-unused-css-classes|rco|0.1.7
LiveServer|rit|5.6.1
git-merger|sha|0.4.1
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
expresssnippet|vla|0.2.4
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by IllusionMH** [comment] 2021-09-08 17:37
/needsMoreInfo

Please add problem description an steps to reproduce

**Comment by lramos15** [comment] 2021-09-09 19:07
Closing due toe lack of description.

**Closed by lramos15** 2021-09-09 19:07 UTC
Labels: needs more info
