### ISSUE TITLE
Extension host process runs at version N+1

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45547] opened 2018-03-12 06:45 UTC
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=f9a631b7-ec20-77a2-b86d-f37bc551096c

```
TypeError: Cannot read property 'map' of undefined
/vs/workbench/api/node/extHostDocumentsAndEditors.ts#118:24 (apply)
/vs/workbench/services/extensions/node/rpcProtocol.ts#174:16 (_doInvokeHandler)
/vs/workbench/services/extensions/node/rpcProtocol.ts#159:27 (_invokeHandler)
/vs/workbench/services/extensions/node/rpcProtocol.ts#108:39 (_receiveRequest)
/vs/workbench/services/extensions/node/rpcProtocol.ts#90:9 (_receiveOneMessage)
/vs/workbench/services/extensions/node/rpcProtocol.ts#33:65 (onMessage)
/vs/workbench/services/extensions/node/rpcProtocol.ts#213:4 (call)
/vs/base/common/event.ts#382:86 (call)
/vs/base/common/event.ts#142:15 (fire)
/vs/base/parts/ipc/node/ipc.net.ts#81:22
```

**Comment by jrieken** [comment] 2018-03-12 08:18
@alexandrudima This is visible ranges

**Comment by alexandrudima** [comment] 2018-03-12 09:21
The root cause is the following: `visibleRanges` is a new property added to a message in the extension host protocol in version 1.21.0.

@jrieken and I have looked at the code for a long period of time. The `visibleRanges` is always being set in the renderer process. The only possible explanation why `visibleRanges` would be not set is if the extension host is at version 1.21.0 and the renderer process is at version 1.20.1.

Also check the error telemetry. The renderer process is at 1.20.1 (it reports the error telemetry), while the stack only makes sense if the extension host process is at 1.21.0.

**Comment by joaomoreno** [comment] 2018-03-12 09:50
Closing original bug as it's an invalid stack trace. Created mac and linux follow-up issues.

**Closed** 2018-09-14 10:01 UTC
Labels: error-telemetry
