### ISSUE TITLE
Slow startup performance and random stuttering

### ISSUE THREAD

**Issue by LucasLundJensen** [microsoft/vscode#99066] opened 2020-06-02 11:48 UTC
Startup has been extremely slow for some reason, did a full reinstall of VSCode (also removed .vscode from %USERPROFILE% and Code folder from %APPDATA%) to see if it solved the issue which it didn't.

I do sometimes also have issues when I search via CTRL+P, it takes a second or two before the inputs get usable.

Additional details: _Not sure if this is anything in relation to VSCode, but I don't experience it on opening other applications._
Takes two~ seconds after searching for it in Windows and pressing ENTER, before the Windows Search disappears and the application starts launching.

[prof-729b.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4716875/prof-729b.extHost.cpuprofile.txt)
[prof-729b.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4716876/prof-729b.main.cpuprofile.txt)
[prof-729b.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4716877/prof-729b.renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2020-06-02 12:20
/duplicate of https://github.com/microsoft/vscode/issues/24884

There is something that causes spawning of processes to be slow. Like 4 to 5 seconds in your case: 

<img width="639" alt="Screenshot 2020-06-02 at 14 18 50" src="https://user-images.githubusercontent.com/1794099/83519375-217fb780-a4dc-11ea-8a06-813d6caff4a8.png">

That can be AV software or missing updates but seems to be different from machine to machine

**Closed by jrieken** 2020-06-02 12:20 UTC
Labels: perf-startup

**Comment by LucasLundJensen** [comment] 2020-06-02 12:40
Thanks for the quick help!
I was able to figure in my case it was either of these two updates that solved my issue, it was not my Antivirus as I disabled it for testing.

Feature Update to Windows 10 Version 1909 via Enablement Package (KB4517245)
Update for Microsoft Windows (KB4497165)
