### ISSUE TITLE
Check entire workspace for Problems - without opening all files in new tabs

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#47353] opened 2018-04-06 20:16 UTC
I want to check the entire workspace for errors, warnings, infos.
To do this, I need to open each file from the entire workspace.
I would like to be able to check all files at once.

This can be a command and/or a button in the Problems panel, whitch eneble or disable checking all files in workspace.

**Comment by mjbvz** [comment] 2018-04-06 22:05
Duplicate of #13953

**Closed by mjbvz** 2018-04-06 22:05 UTC
