### ISSUE TITLE
onDidCloseTextDocument called after a while

### ISSUE THREAD

**Issue by gianpatt** [microsoft/vscode#97522] opened 2020-05-11 16:06 UTC
I'm implementing a FileSystem provider over our database which is like a filesystem.
We have a mechanism to lock/unlock when we open the file in order to avoid that two people edit the file at the same time.
We need to have some callback in order to understand when can unlock the file.
The callback is called with a timer every two/three minutes but it's unusable. 

There are a lot of "duplicates" events that give you always the same information: the editor with a focus or visible but there is not any possibility to know the of Text Documents currently opened. 

Thanks 

- VSCode Version: 1.45
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Text Document
2. Close a Text Document 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2020-05-12 08:55
@gianpatt what is wrong with using `vscode.workspace.onDidCloseTextDocument` ?

**Comment by gianpatt** [comment] 2020-05-12 10:11
Hi @bpasero, it's called after a while after the user closed the TextEditor. It seems that there is a timer that will dispose the TextDocument after they are closed.

The call itself is ok but I need to unlock as soon as the user has clicked to the close button. I did not find any usable event to do this.

Thanks
Gian

**Comment by bpasero** [comment] 2020-05-12 10:12
@gianpatt can you send me an isolated extension code to reproduce this? I just briefly tried it and it seems the event was fired whenever I closed a tab.

**Comment by bpasero** [comment] 2020-05-12 10:13
Actually reading the JSDoc seems to signal that it is not a good candidate for your purpose:

> An event that is emitted when a [text document](#TextDocument) is disposed or when the language id
> of a text document [has been changed](#languages.setTextDocumentLanguage).
> 
> To add an event listener when a visible text document is closed, use the [TextEditor](#TextEditor) events in the
> [window](#window) namespace. Note that this event is not emitted when a [TextEditor](#TextEditor) is closed
> but the document remains open in another [visible text editor](#window.visibleTextEditors).

Did you try tht?

**Comment by jrieken** [comment] 2020-05-12 10:24
Yes - using `onDidCloseTextDocument` as signal wether an editor is open or not is bogous. There is also no guarantee when this event fires, and it's likely not what you expect. Yes, there are event to know when text editors change but note that tabs !== editor. You can read more here: https://github.com/microsoft/vscode/issues/15178#issuecomment-624512992

**Comment by gianpatt** [comment] 2020-05-12 10:41
Thank you both.

@bpasero The event on visible editor is not usable because it can be triggered when also when the user change tab (I cannot lock/unlock a resource when the user change tab, unfortunatly is the same behavior I noted with the FileSystemProvider::watch call that is called/disposed every time the text editor becomes active).

@jrieken You proposed API seems to be perfect for my use case. Any idea of when it will available for same test?

Really thanks
Gian

**Comment by jrieken** [comment] 2020-05-12 10:43
> Any idea of when it will available for same test?

idk - hopefully end of this month but it's on @eamodio 

closing this as dupe of the API request

**Closed by jrieken** 2020-05-12 10:43 UTC
Labels: needs more info
