### ISSUE TITLE
Automatic Indentation doesn't work for single line conditionals in C/C++

### ISSUE THREAD

**Issue by cseas** [microsoft/vscode#73547] opened 2019-05-09 19:16 UTC
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

Press Enter after typing an `if` or `for` statement in a C program without using curly braces.

Does this issue occur when all extensions are disabled?: Yes

Expected behaviour:
```
if(true)
    i++;

for(i=0; i<n; i++)
    j++;
```

Current behaviour:
```
if(true)
i++;

for(i=0; i<n; i++)
j++;
```

It's common in C/C++ programming to avoid using the curly braces after conditionals like `if` and `for` when the statement succeeding them is only one line. VSCode doesn't detect this and doesn't add an indentation automatically when enter is pressed. The indentation works fine with curly braces though. Would love this to be fixed since it disturbs the workflow and most other popular IDEs have this little feature already.

**Comment by rebornix** [comment] 2019-10-23 00:13
/duplicate of https://github.com/microsoft/vscode/issues/36148 . Our auto indentation is based on regex rules while it is not fully aware of the context/scope and it also doesn’t support different indentation formats.

**Closed** 2019-10-23 00:13 UTC
Labels: *duplicate, editor-autoindent, feature-request
