### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by SabinShree** [microsoft/vscode#108281] opened 2020-10-08 02:04 UTC
![image](https://user-images.githubusercontent.com/24645613/95406698-c141cc00-093a-11eb-8598-f37838df98af.png)
Display issue while using vscode. All other app are running normally.
Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-10-08 10:47
/duplicate of #93356

At this point workaround is either pass `--disable-gpu` on application start e.g. `code --disable-gpu`  or use steps in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed** 2020-10-08 10:48 UTC
Labels: *duplicate
