### ISSUE TITLE
Fagmented background fill on HiDPI display

### ISSUE THREAD

**Issue by hiddenman** [microsoft/vscode#91638] opened 2020-02-27 00:58 UTC
Issue Type: <b>Bug</b>

Hi there,

All themes on latest VS Code and even VS Code Insiders are rendered incorrectly on HiDPI displays (3840x2160): background is not filled to the whole screen, only around source code (see the screenshot).
Option --disable-gpu eliminates this issue.  All other Electron-based software work well (Skype, Spotify and so on).

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.5.6-050506-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 3599)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|62.34GB (39.73GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.9
vscode-markdownlint|Dav|0.34.0
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
code-settings-sync|Sha|3.4.3
bunker|sld|1.1.6
best-dark-themes-pack|the|1.0.1
material-theme|zhu|3.2.3

(76 theme extensions excluded)

</details>

![Screenshot from 2020-02-27 02-52-04](https://user-images.githubusercontent.com/4009515/75402254-0580de80-590d-11ea-890d-29be02c2dcea.png)

**Comment by IllusionMH** [comment] 2020-02-27 02:30
/duplicate of #85452
See https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for better approach to disable HW Acceleration without constantly passing flag.

> All other Electron-based software work well (Skype, Spotify and so on).

They definitely has different UI, customizability etc.
Maybe they even have have HWA disabled by default on Linux?

More details about possible action items to have a fix for this problem https://github.com/microsoft/vscode/issues/85452#issuecomment-558850951

**Closed** 2020-02-27 02:30 UTC
Labels: *duplicate

**Comment by hiddenman** [comment] 2020-02-27 08:11
> /duplicate of #85452
> See [#85452 (comment)](https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562) for better approach to disable HW Acceleration without constantly passing flag.
> 
> > All other Electron-based software work well (Skype, Spotify and so on).
> 
> They definitely has different UI, customizability etc.
> Maybe they even have have HWA disabled by default on Linux?
> 
> More details about possible action items to have a fix for this problem [#85452 (comment)](https://github.com/microsoft/vscode/issues/85452#issuecomment-558850951)

Hi,

Thank you. Yes, that's the same bug. Unfortunately, i can't comment on that bug. So i'll ask here:  is it the good decision to disable hardware acceleration?  VS Code will be slower in this case, won't it?
May be it's better to find the root cause of that behaviour and fix it?

Thank you.

**Comment by IllusionMH** [comment] 2020-02-28 10:02
>  is it the good decision to disable hardware acceleration? VS Code will be slower in this case, won't it?

I haven't noticed any difference, but I tried on Windows and on PCs without discrete GPU.

> May be it's better to find the root cause of that behaviour and fix it?

This is not comething VS Code tema controls so somebody needs to provide repro in Chromium per https://github.com/microsoft/vscode/issues/85452#issuecomment-558850951

Maybe @deepak1556 can provide more info about performance difference expectations.
