### ISSUE TITLE
Vs code crash for no reason

### ISSUE THREAD

**Issue by luisgzvs** [Microsoft/vscode#34393] opened 2017-09-14 16:20 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.1
codeception-snippets|die|0.0.4
vscode-great-icons|emm|2.1.16
beautify|Hoo|1.1.1
easy-icons|jam|0.3.1
debugger-for-chrome|msj|3.3.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.12.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open codecetjs project
2. Execute chromedriver
3. Execute selenium-standole start
4. Execute codeceptjs run --steps --verbose
5. App crashes 

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment] 2017-09-15 08:04
@luisgzvs Are you executing those from the integrated terminal ? Does VS Code crash also when executing those from an external terminal ?

**Comment by nategreen** [comment] 2017-09-15 18:59
I've been running into a similar issue. When I save a Sass (.SCSS) file while a gulp.js watch task is running in the integrated terminal, VS Code crashes. Not every time, though. (Not sure exactly what the steps are to reproduce, for me.)

Running the same tasks in an external terminal works fine, and no crashes.

**Comment by nategreen** [comment] 2017-09-15 19:01
I'm on version 1.16.1 of VS Code (x64) but am also on Windows 10.

**Comment by Tyriar** [comment] 2017-09-16 00:34
Might be a duplicate of https://github.com/Microsoft/vscode/issues/34301

**Comment by luisgzvs** [comment] 2017-09-18 20:58
@alexandrudima seems to be an issue of VS Code version 1.6, I've returned to the 1.5 version and issue is not happening again

**Comment by amanmavai** [comment] 2017-09-27 05:42
I am also getting a similar issue, When I am using 2 integrated terminals for running express server,vs code is crashing, this is happening in the latest version

**Comment by Tyriar** [comment] 2017-09-27 13:00
Duplicate https://github.com/Microsoft/vscode/issues/34301

**Closed by Tyriar** 2017-09-27 13:00 UTC
Labels: needs more info, new release
