### ISSUE TITLE
window.titleBarStyle=custom in full screen mode?

### ISSUE THREAD

**Issue by leromi** [Microsoft/vscode#54079] opened 2018-07-11 16:34 UTC
i like the `window.titleBarStyle=custom` setting, but with this feature enabled i lost access to the menubar  (autohide, with Alt) in full screen mode; is it possible to display the menubar in full screen mode as before but with the current theme applied (i use dark mode)?

**Comment by sbatten** [comment] 2018-07-12 17:34
duplicate of #52954

**Closed by sbatten** 2018-07-12 17:34 UTC
Labels: workbench-menu
