### ISSUE TITLE
Default outline action

### ISSUE THREAD

**Issue by murraycollingwood** [microsoft/vscode#74238] opened 2019-05-23 23:10 UTC
The recent changes in the default outline display has degraded it's usability.

Originally when opening a file the Outline would by default display the functions which was perfect, or the classes and functions. I'm always looking for a particular function in a file, and having them listed alphabetical is perfect. (I normally have only a single class per file so in general I only have a single list of functions for each file).

The current version however lists all functions constants and variables, this is really long as my files can be quite large (lots of functions). So I use the "collapse" button - this works in a file that only contains functions - the functions are all listed alphabetically. But in a class file the collapse function then shows all of the classes, and generally I only have one class per file, so it lists one class name. I then have to expand the class to see the functions. This is 2 clicks more than I want.

Can we please have the outline default to listing functions only? Or a setting that allows us to specify a default level of expansion.

**Comment by mjbvz** [comment] 2019-05-23 23:19
What language is this for?

**Comment by murraycollingwood** [comment] 2019-05-23 23:50
Personally I'm using PHP but I assumed this was a generic outline facility that worked the same across multiple languages.

I'm using the "PHP Intellephense" plugin. I checked with them first, they said they are simply supplying the list of values and the vscode are in charge of the default outline display and the behaviour of the outline.

**Comment by jrieken** [comment] 2019-05-24 06:18
/duplicate of https://github.com/microsoft/vscode/issues/58862

**Closed** 2019-05-24 06:18 UTC
Labels: *duplicate, outline
