### ISSUE TITLE
MacBook becomes non-interactive after VSCode processes seem to hang

### ISSUE THREAD

**Issue by callensm** [microsoft/vscode#100997] opened 2020-06-25 02:28 UTC
Issue Type: <b>Performance Issue</b>

Every now and then (several times a day) VSCode seems to have a process that will freeze/hang in the background, such as automated `git` file diffs, saving code files with auto-formatting, package import resolutions, etc., and subsequently makes the entire laptop being unusable.

Applications that were previously open are to be somewhat used, for example sending messages on Slack, but when I click on a new one from the dock to attempt to open it, I simply here the Mac error "__*donk*__" sound as if there is an invisible prompt somewhere requiring input before continuing. The only way to resolve it that I've figured out it to restart my MacBook and go back to what I was doing until it happens again.

(Sample infinitely hanging process that locks up laptop)
<img width="456" alt="Screen Shot 2020-06-25 at 7 57 57 AM" src="https://user-images.githubusercontent.com/13121516/85724347-bdef4100-b6b9-11ea-9eb5-caf42726722a.png">

I've watched the VSCode process explorer as well as Activity Monitor and don't see anything suspicious when the issue occurs. It's random, sometimes it happens immediately when opening VSCode, and sometimes it doesn't happen at all for a couple of hours.

I've searched high and low but can't seem to find any resolution for the issue.

Steps to Reproduce:

1. Open VSCode
2. Wait until process begins to hang after some interactions
3. Clicking on a new app on the dock causes "__*donk*__" error noise
4. Requires machine restart

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

Process Explorer Screenshot:
<img width="801" alt="Screen Shot 2020-06-25 at 8 07 32 AM" src="https://user-images.githubusercontent.com/13121516/85727034-4bcc2b80-b6bc-11ea-97c7-92f46d1652a6.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 2|
|Memory (System)|16.00GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    98	  1301	code main
    0	    98	  1303	   gpu-process
    1	    16	  1305	   utility
    0	   279	  1306	   window (packer_ami_build_test.go — secrets-mgmt-ami)
    0	    66	  1330	     extensionHost
    0	   524	  1361	       /Users/mcallen/workspace/go/bin/gopls -mode=stdio
    0	    33	  1331	     watcherService
    0	    33	  1334	     searchService
    0	    98	  1333	   shared-process
    0	     0	  1425	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  1422	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (packer_ami_build_test.go — secrets-mgmt-ami)
|    Folder (secrets-mgmt-ami): 726 files
|      File types: go(497) s(12) md(10) yml(8) mod(5) gitignore(4) tmpl(4)
|                  j2(3) txt(3) sum(2)
|      Conf files: makefile(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
Go|gol|0.14.4
terraform|has|2.0.2
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.8.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

Extension Profiling Results:
[CPU-20200625T132211.274Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/4831495/CPU-20200625T132211.274Z.cpuprofile.txt)

Result of `code --status` before issue begins (cannot execute once laptop has locked up):
```
Version:          Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS Version:       Darwin x64 19.5.0
CPUs:             Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)
Memory (System):  16.00GB (7.96GB free)
Load (avg):       13, 6, 2
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    82	  1167	code main
    0	    49	  1168	   gpu-process
    0	    16	  1170	   utility
    0	   295	  1171	   window (packer_ami_build_test.go — secrets-mgmt-ami)
    5	   115	  1194	     extensionHost
    0	   541	  1329	       /Users/mcallen/workspace/go/bin/gopls -mode=stdio
    0	     0	  1195	     /bin/zsh -l
    0	    49	  1208	     watcherService
    0	    33	  1306	     searchService
    0	    98	  1215	   shared-process
    0	     0	  1450	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (packer_ami_build_test.go — secrets-mgmt-ami)
|    Folder (secrets-mgmt-ami): 726 files
|      File types: go(497) s(12) md(10) yml(8) mod(5) gitignore(4) tmpl(4)
|                  j2(3) txt(3) sum(2)
|      Conf files: makefile(1)
```

Startup Profiling Results (only possible when issue doesn't occur because profiling will freeze):
[prof-826b.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4831611/prof-826b.renderer.cpuprofile.txt)
[prof-826b.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4831612/prof-826b.extHost.cpuprofile.txt)
[prof-826b.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4831613/prof-826b.main.cpuprofile.txt)

MacOS Crash Report:
[crash_report.txt](https://github.com/microsoft/vscode/files/4831926/crash_report.txt)

**Comment by bpasero** [comment] 2020-06-25 05:41
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by callensm** [comment] 2020-06-25 13:38
@bpasero I updated the original issue post with profiling data and screenshots as directed by the wiki you provided.

**Comment by bpasero** [comment] 2020-06-26 08:37
@callensm looks like you attached a crash report, does that mean VSCode crashes when this happens?

**Comment by callensm** [comment] 2020-06-26 13:11
@bpasero it doesn't necessarily crash in the sense you may be thinking most of the time. I can still type in the files and browser through a project directory, but i cannot save any changes, commit or push to the repository or do anything that changes the state of the project or VSCode's settings.

**Comment by bpasero** [comment] 2020-06-26 15:09
Ok, that CPU trace and memory unfortunately does not reveal much. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by callensm** [comment] 2020-06-26 16:05
Yes, the issue still is occurring while using the Insiders version of VSCode.

**Comment by bpasero** [comment] 2020-06-26 16:16
I am out of ideas and will likely close this issue in 7 days from now, given no repro steps, but adding @deepak1556 for final words.

**Closed** 2020-07-04 11:23 UTC
Labels: needs more info
