### ISSUE TITLE
Terminal kill button

### ISSUE THREAD

**Issue by MeghanshBansal** [microsoft/vscode#126445] opened 2021-06-16 06:42 UTC
Issue Type: <b>Feature Request</b>

Please add kill terminal button

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by yume-chan** [comment] 2021-06-16 07:21
Duplicate of #126225

**Closed** 2021-06-16 16:45 UTC
