### ISSUE TITLE
SCSS Syntax tag highlighting missing since 1.18

### ISSUE THREAD

**Issue by dariusrosendahl** [Microsoft/vscode#38774] opened 2017-11-20 11:51 UTC
- VSCode Version: 1.18
- OS Version: Windows 10

Steps to Reproduce:

1. Create a SCSS file and write an a { }
2. Create an element around the a { }. The syntax highlighting is now missing.

![2017-11-20 12_45_01- untitled-1 - quickstart workspace - visual studio code](https://user-images.githubusercontent.com/7299359/33017159-8c22f724-cdf1-11e7-8108-d575086b2d77.png)

Reproduces without extensions: Yes

**Comment by gbeumer** [comment] 2017-11-20 11:53
Same here

**Comment by JordynMarcellus** [comment] 2017-11-21 21:41
+1, 
VSCode version: 1.18.1
OS Version: OSX 10.12.6 (Sierra)

**Comment by Mikewalker24** [comment] 2017-11-21 21:44
Ditto. 
VSCode 1.18.1
OSX 10.12.6

**Comment by heymiguel** [comment] 2017-11-21 21:51
Same here.


VSCode 1.18.1
OSX 10.12.6

**Comment by mwilkins91** [comment] 2017-11-21 21:52
Me too 
VSCode: 1.18.1
OSX: 10.12.6

**Comment by aeschli** [comment] 2017-11-23 07:45
duplicate of #38001, fixed in 1.19

**Closed by aeschli** 2017-11-23 07:45 UTC
