### ISSUE TITLE
Support project specific extensions configuration with 'extensions.json' file in the '.vscode' folder

### ISSUE THREAD

**Issue by x-strong** [Microsoft/vscode#66429] opened 2019-01-12 14:43 UTC
Support project specific extensions configuration with 'extensions.json' file in the '.vscode' or a '.project'  folder to control the vscode to install/enable the required extensions specific to the project.

The configuration file 'extensions.json' may looks like the following example:
{
  "Prettier":{
    "version":"^1.0.0",
    "enable":true
  }
}

The configuration will instruct vscode to install the required extensions and enable or disable extensions configured in the 'extensions.json' file.

**Comment by RMacfarlane** [comment] 2019-01-12 18:12
Hey @x-strong, this looks like a duplicate of https://github.com/Microsoft/vscode/issues/15442. Please leave any feedback there. Thanks!

**Closed by RMacfarlane** 2019-01-12 18:12 UTC
Labels: extensions
