### ISSUE TITLE
Feature request: customized settings for specific files and folders

### ISSUE THREAD

**Issue by aaronkahlhamer** [Microsoft/vscode#50888] opened 2018-05-31 16:12 UTC
Similar to customized language modes...
```
"[typescript]": {
   "editor.formatOnSave": true,
}
```

...a method to customize settings for specific folders and files...

```
"[**/dist/, **/build/index.html]": {
   "editor.formatOnSave": false
}
```

**Comment by sandy081** [comment] 2018-06-01 08:27
Duplicate of #35350

**Closed** 2018-06-01 08:27 UTC
Labels: *duplicate, config
