### ISSUE TITLE
VSCODE flickers in full screen mode

### ISSUE THREAD

**Issue by soveckyFonarik** [microsoft/vscode#41513] opened 2018-01-12 07:25 UTC
Version 1.19.2
Fixation 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15: 55: 03.538Z
Shell 1.7.9
Drawer 58.0.3029.110
Host 7.9.0
Architecture x64

Steps to Reproduce:

1. press f11
2. coding....

there are unpleasant flickering, orange in full screen mode

**Comment by jhasse** [comment] 2018-01-12 08:58
On which operation system?

**Comment by bpasero** [comment] 2018-01-12 09:18
Can you share a screen cast?

**Comment by soveckyFonarik** [comment] 2018-01-12 09:22
@bpasero, Microsoft Windows [Version 10.0.16299.192]

**Comment by bpasero** [comment] 2018-01-12 09:28
@soveckyFonarik does it reproduce when you run "`code --disable-gpu`"?

**Comment by soveckyFonarik** [comment] 2018-01-12 17:00
@bpasero Cool, apparently my amd radeon hd 7750 is to blame? 👍 :D
with this flicker key I do not watch

**Comment by demestav** [comment] 2018-01-15 10:42
I am recently experiencing the same behavior on Ubuntu 16.04. Parts of the screen flicker briefly.

The `--disable-gpu` argument suggested by @bpasero seems to resolve the issue.

**Comment by Hammster** [comment] 2018-01-18 23:11
Had the same issue and `--disable-gpu` resolved it. My GPU is the R9 270X.

**Comment by radutomy** [comment] 2018-02-03 16:57
I'm experiencing the same flickers on Ubuntu 17.10. Very annoying

**Comment by iamruhul** [comment] 2018-03-18 11:33
same here in ubuntu!! I've been experiencing the issue for like 2-3 months. It's not a new issue

**Comment by slayer** [comment] 2018-04-26 10:56
Same on Ubuntu 17.10 with external monitor (in full screen mode only)

**Comment by n-3-0** [comment] 2018-05-20 20:06
I'm running Debian Sid, kernel `4.16.0-1-amd64`, with Intel HD Graphics 630 & NVIDIA GeForce GTX 1050 Mobile, and was able to remove all flickering in vsascode 1.23.1 with Bumblebee by not using `--disable-gpu`, and running `optirun code`.

**Comment by Duelsik** [comment] 2018-07-06 22:35
Same on `Ubuntu 18.04 LTS` with GTX1080Ti with removed stock drivers and installed latest nvidia drivers. `--disable-gpu` fixed problem.

**Comment by theFroh** [comment] 2018-07-09 05:53
Same on `Ubuntu 18.04` with a GeForce GT 610. 
However, for other GNOME users here's a workaround that seems to behave fine for me:

1. Open Settings > Keyboard
2. Search for "Toggle fullscreen mode" and assign a shortcut to it (I've chosen `Super+F11`)
3. *Instead* of using F11 or the application's own fullscreen mode, use GNOME's via your shortcut

This works without flickering for me, though I imagine it might not bring with it any GPU fullscreen optimisations (on that front it is probably better, performance-wise, than disabling GPU acceleration all together!).

**Comment by ylxdzsw** [comment] 2018-08-16 07:14
Hi, I'm experiencing the same problem on Manjaro with Gnome. Using Super+F11 to enter gnome's "fullscreen" mode does not help, while "--disable-gpu" fixed it for me.

**Comment by alexamy** [comment] 2018-08-18 13:26
Same problem with vscode 1.26.1, ubuntu Ubuntu 18.04.1
`--disable-gpu` solves the problem.

**Comment by mayrbenjamin92** [comment] 2018-08-30 13:10
Question: Is there anybody who does not have this issue? :D

**Comment by Hammster** [comment] 2018-08-31 10:02
Yes,  my windows machines don't have this issue.

**Comment by alexamy** [comment] 2018-08-31 10:05
I dont have this issue on windows too.

**Comment by radutomy** [comment] 2018-08-31 10:11
The issue is just on Linux-based systems.

**Comment by Hammster** [comment] 2018-08-31 12:06
@radutomy not entirely true, soveckyFonarik the issue creator has windows 10. The issue is more likely to be some error caused by electron or the driver/hardware constellation. 

Apparently most or maybe all nvidia-driver-* packages on linux are affected which explains the high density of this issue on Linux based systems. The strange part is it works on my gnome ubuntu 16.04 without any issues but my Debian installation still flickers on the same machine (Dualboot).

**Comment by SerhiiCho** [comment] 2018-09-13 10:56
Ubuntu 18.04 same issue, maybe it's related to Intel HD Graphics 520 (Skylake GT2) video card

**Comment by beavermml** [comment] 2018-09-14 09:34
Win10 Latest + VSCode 1.27.2 still has this issue.

**Comment by kaczorrrro** [comment] 2018-09-22 21:06
Same issue.
Ubuntu 18.04
GPU: Intel Corporation HD Graphics 5500

**Comment by jazieltan** [comment] 2018-09-25 07:03
Same Issue, Windows 10. Happens when switching tabs or switching apps.  
Vscode 1.27.2
AtI R9 280

**Comment by jazieltan** [comment] 2018-10-07 10:43
Just to add on. I've also experienced this on Git Kraken on fullscreen. and I come to understand that both VsCode and Git Kraken are built on electron. I have a feeling this is an issue with electron itself?

**Comment by freifrauvonbleifrei** [comment] 2018-10-10 08:34
I have the same problem - with Ubuntu 18.04.1. I see the flickering
- with and without --disable-gpu flag
- on fullscreen and windowed mode

**Comment by tkuraku** [comment] 2018-10-14 18:15
vscode was working perfectly. However, after update 1.28.1 I get a persistent flicker in the vscode window making it unusable.

OS: Centos 7.5
Graphics: AMD RX 470

**Comment by iahmedov** [comment] 2018-11-02 09:03
Same issue as @tkuraku described

VS Code Version: 1.28.2
Ubuntu: 16.04
Grpahics: Integrated

**Comment by matthewphilyaw** [comment] 2018-11-03 05:33
I have a similar issue I think. I'm currently running Feodora 29, but also noticed this issue on ubuntu 18.04 on the same hardware setup described below. 

For all my notes below I had started VS Code with the disable gpu flag.

Specifically I'm getting flicker when in full screen mode primarily when a tool tip pops in the explorer bar and my mouse runs through it (the cursors passes through the tool tip). This also seems to happen for tool tips in the tab bar as well, however not an issue for completion pop ups etc.

Oddly enough if I click to on a second monitor to put focus on what ever is on that monitor and then move my mouse back to VS Code (not clicking to bring focus back) and hover over items in the explorer that pop tool tips the flicker goes away. However, simply click to bring focus back to VS Code the flicker returns. 

A few other things that I have noted:
- Only happens for me in full screen mode
- Seems to only be triggered by mousing over tool tip or clicking into the VS Code from another monitor to gain focus on the window.
- Sometimes it clears up (e.g. I didn't restart the app) if there are fullscreen apps behind it (I had terminal app on the same workspace), but this doesn't always happen - bear in mind I'm also moving the window between workspaces when this clears up so that could be a factor as well. Not entirely sure how the window is handled as it moves between workspaces.
- It's not 100% clear what starts the flicker, its not something that is there from the start of the app. Just a moment ago it started after I clicked "open folder" from the explorer bar. Typically persist until I restart VS Code with the exception of what I noted about about how sometimes it clears up if another full screen app is behind it.
- The flicker for the most part is really the entire window disappearing exposing the desktop then the screen snaps back (it's really fast, but I can see the desktop as well as other apps behind the window). 
- I get the flicker on both monitors (see xrandr output below), which are different resolutions

System Info 
```
code --version
1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64

uname -a
Linux localhost.localdomain 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lspci -k | grep -EA3 VGA             
01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
	Subsystem: Gigabyte Technology Co., Ltd Device 371a
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia

cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  410.66  Wed Oct 10 12:01:53 CDT 2018
GCC version:  gcc version 8.2.1 20180801 (Red Hat 8.2.1-2) (GCC)

xrandr 
Screen 0: minimum 8 x 8, current 4160 x 1080, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 2560x1080+0+0 (normal left inverted right x axis y axis) 798mm x 334mm
   2560x1080     60.00*+
   1920x1080     60.00    59.94    50.00    29.97    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DVI-D-1 connected 1600x900+2560+0 (normal left inverted right x axis y axis) 442mm x 249mm
   1600x900      60.00*+
   1280x800      59.81  
   1280x720      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  


cat /usr/share/gnome/gnome-version.xml 
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>30</minor>
 <micro>1</micro>
 <distributor>GNOME.Org</distributor>
 <date>2018-09-26</date>
</gnome-version>

```

**Comment by eugenebnd** [comment] 2018-11-04 01:32
ubuntu 18.04 - same issue
Switched to wayland - no flickering
`--disable-gpu` is really not an option.
Guys, let's try to fix it.
Thanks!

**Comment by robzon** [comment] 2018-11-07 15:32
Having this issue on Ubuntu 18.10 on a Librem13 laptop.

**Comment by makanbeling** [comment] 2018-11-12 03:11
Got this issue in Ubuntu 18.10 with VSCode 1.28.2, please fix this soon.

**Comment by mofax** [comment] 2018-11-19 10:40
Upgraded my Dell XPS 13 9370 to Ubuntu 18.04 from 16.04 and started having this problem.

```bash
$ code --version
1.29.0
5f24c93878bd4bc645a4a17c620e2487b11005f9
x64

$ lsb_release -irc
Distributor ID:	Ubuntu
Release:	18.04
Codename:	bionic
```

**Comment by eldarshamukhamedov** [comment] 2018-12-01 06:05
I believe this is related to the version of Electron that is shipped with VSCode by default, which I believe is still 1.x? I first ran into this issue a few months back, when I switched to an Ubuntu 18.04 Dell XPS laptop. I noticed the same issues in another app, Slack, which also uses Electron 1.x. Same flickering, only on Linux, and only when the apps are fullscreen (or maximized) on an external 4K monitor. After trying a bunch of things, I switched to VSCode Insiders, which uses Electron 2.x, and the flickering went away. I know Insiders isn't for everyone, but maybe this will help someone until VSCode ships Electron 3.x, which seems to be in the works.

For VSCode devs, some symptoms:
1. "Flickering" isn't the perfect word to describe the effect. It actually looks like some DOM layers are either not rendered, or rendered partially.
2. Not unique to VSCode. Slack on Electron 1.x has the same flickering issues.
3. Only occurs when the editor window is larger than a certain size. When I have VSCode take up half the width of a 4K screen, flickering goes away, but as I stretch the window closer and closer to full width, the effect get worse and worse. I can repro this in VSCode and in Slack.
4. I have never seen this come up on macOS or Windows, despite using those VSCode builds heavily.

My hardware:
Ubuntu 18.04
Dell XPS 13 2018 9370
i7-8550U Processor
Intel® UHD Graphics 620

**Comment by snailuj** [comment] 2018-12-05 06:12
I had been experiencing the same problem intermittently for a couple weeks after setting "window.titleBarStyle": "custom". Setting it back to "native" as referred to by @mofax fixed it for me.

```
code --version
1.29.1

Distributor ID: Debian
Release:        9.6
Codename:       stretch
```

Using Dell 24" Ultrasharp UHD monitor and an AOC 27" UHD with onboard Intel graphics on an ASRock K6 Z370 mboard.

**Comment by DanielJoyce** [comment] 2018-12-15 00:43
Weird. Ubuntu 18.04 and setting title bar style to custom fixed it for me. 

Else the entire window when full screen would flicker in brightness...

**Comment by DanielJoyce** [comment] 2018-12-15 00:46
Okay switching back to native cured it there too.

**Comment by rahil051** [comment] 2018-12-20 05:49
@eldarshamukhamedov 
> "window.titleBarStyle": "native"

adding this configuration literally solves the problem for me. I remember that the last time I updated VSCode on my Mint Linux machine, the window title bar style was changed to Microsoft Windows style, and after that the flickering problem started to happen. The solution was to force the editor back to the native styled title bar.

**Comment by Akuukis** [comment] 2018-12-20 09:51
> "window.titleBarStyle": "native"

Had the same problem, solves also for me.

```
OS: Debian 9.5
Kernel: Linux 4.19.0-rc4-amd64
Videocard: ASUSTeK Computer Inc. Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] [1043:054d]
```

**Comment by mofax** [comment] 2018-12-21 06:47
another discovery I made on a different computer
if you set 
> "window.titleBarStyle": "native" 

but the flikering continues ... also add this
> `"terminal.integrated.rendererType": "dom",`

completely solved the flickers on all my machines, on both regular and insider releases

**Comment by dreamsComeTrue** [comment] 2018-12-29 15:10
--disable-gpu - did trick for me :)

**Comment by sohail042414** [comment] 2019-01-16 11:07
Add this worked for me, on ubuntu 16.04 .
"window.titleBarStyle": "native"

**Comment by dork1** [comment] 2019-02-12 08:02
On a fresh install and machine, changing my display resolution back to my 'recommended' setting did it for me it seems.

**Comment by DanielJoyce** [comment] 2019-02-12 19:21
For me it was "Dynamic Brightness" on my dell xps 13. Why they though this was a good idea I don't know. When sections on the screen got bright enough, it'd bounce off my shirt, triggering the light sensor, causing the brightness to adjust. Scrolling would cause a flicker as brighter areas of the screen would scroll into/out of view.

So dumb.

If you own a fancy laptop, check in the bios for "Dynamic Brightness" and turn it off.

**Comment by francisceril** [comment] 2019-03-05 17:10
--disable-gpu seems to solve for me as well. Now, how can I make this permanent?

**Comment by atharvajohri** [comment] 2019-04-11 11:45
"window.titleBarStyle": "native" . fixed it for me on my MacOS Mojave 10.14

**Comment by FDiskas** [comment] 2019-05-16 13:48
Same for me: :sleeping:
https://youtu.be/Wedcs-Pu-gw
```
Version: 1.34.20-insider
Commit: e83e24a0c9225becd7341e56952177a20d5d4629
Date: 2019-05-14T16:08:09.042Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-30deepin-generic
```

**Comment by methodbox** [comment] 2019-05-22 00:33
> On a fresh install and machine, changing my display resolution back to my 'recommended' setting did it for me it seems.

Are you saying _toggling_ to recommended and back to the setting you actually wanted, or just leaving it on Recommended? Because that's not really a solution.

**Comment by Wunkolo** [comment] 2019-06-27 05:18
I get this on windows as well. `--disable-gpu` seems to fix it.

When I press `F11` or when I enter Zen-Mode my screen flashes black and certain elements would vibrate around as well. I also notice that I get a shadowplay notification when going full-screen. That only tends to happen when a game is ran or something. I am on a 2080ti with driver version `425.31`. This seems to happen to others on Intel and AMD gpus though and might just be a rendering issue with Electron like some of the other tickets say.

I hope the `--disable-gpu` mitigation doesn't have to be required anymore.

**Comment by bpasero** [comment] 2019-10-09 18:36
This can be configured now. Closing as duplicate of https://github.com/microsoft/vscode/issues/15211

**Closed by bpasero** 2019-10-09 18:36 UTC
Labels: electron, gpu, needs more info, upstream
