### ISSUE TITLE
VSCode hangs while search is running

### ISSUE THREAD

**Issue by andrew-filippov** [Microsoft/vscode#22223] opened 2017-03-08 14:16 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|phpserver|brapifra|1.1.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|0.0.12|
|code-runner|formulahendry|0.5.1|
|Go|lukehoban|0.6.51|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.6.2|
|meteorhelper|ramonitor|0.1.3|;

---
Hello. After last update search feature was became unusable. Every time when I try to use it, app hangs and becomes totaly unresponsible.
Steps to Reproduce:

1. Use search textbox

**Comment by roblourens** [comment] 2017-03-08 19:31
Do you mean searching in one document, or the whole workspace? (ctrl+f vs ctrl+shift+f)?

Does it matter what you search for? Are you doing a regex search?

**Comment by andrew-filippov** [comment] 2017-03-09 07:23
Hi again. It was simple string searching (without regex) in the whole workspace. I'll try it with regex shortly.
It is Meteorjs + Reaction project with billion files, so searching may need some time. 
But until v1.10.1 searching was working without total UI freezing.

app had occupied to more RAM(see screenshot follow). At the some moment second process from screenshot was grub whole available system memory, and window was appeared with offer kill the program.
<a href="http://en.zimagez.com/zimage/screenshot2017-03-0909-13-32.php" target="_blank" title="Photo hosted by zimagez.com"><img src="http://en.zimagez.com/miniature/screenshot2017-03-0909-13-32.png" alt="Photo hosted by zimagez.com" /></a>

**Comment by andrew-filippov** [comment] 2017-03-09 07:25
Oh.. sorry I have closed this issue mistakenly.

**Comment by roblourens** [comment] 2017-03-12 22:41
Are there lots of results? Does it happen if you do a search that doesn't produce any results?

**Comment by andrew-filippov** [comment] 2017-03-13 17:03
well... when I try to search very common thing (in my case - string "is"), it was working something around 5..8 sec and return some results and label that it had found a few thousands entries and ask me to make more specific query.

when I have entered name of js function (in my case - string ".subscribe") which is used few hadred times in my project - it have started few search working processes. at the same time searching service has eaten something around 70% of CPU time and a lot of memory, and machine became unresponsible.

when I have entered some mess into search box, it also complete searching relatively quickly (~20-30 sec) and claim that nothing found.

**Comment by roblourens** [comment] 2017-03-13 17:15
Not sure what the problem is, but I plan to replace the search code entirely this month, so that should fix it.

**Comment by roblourens** [comment] 2017-03-27 03:30
Ripgrep search will be enabled by default in the March release, and has much better perf characteristics, so hopefully this is resolved by that.

**Comment by roblourens** [comment] 2017-03-27 03:31
Try it out in the Insiders' build if you like

**Closed by roblourens** 2017-03-27 03:30 UTC
Labels: search
