### ISSUE TITLE
Maximum open editors

### ISSUE THREAD

**Issue by ashkan-dev-86** [microsoft/vscode#171149] opened 2023-01-12 07:14 UTC
Type: <b>Bug</b>

I was set the value of limit to 9 and it was working but after I change it to 15 it still keeps open only 9 tabs

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment] 2023-01-12 10:06
Is this the setting you mean? Have you set 15 at the User level? Does Settings Editor warn you that the setting is also modified at the Workspace level?

![image](https://user-images.githubusercontent.com/6726799/212038111-645b65b6-a0f3-4751-9097-90680942ff16.png)

**Comment by ashkan-dev-86** [comment] 2023-01-13 10:42
> Is this the setting you mean? Have you set 15 at the User level? Does Settings Editor warn you that the setting is also modified at the Workspace level?
> 
> ![image](https://user-images.githubusercontent.com/6726799/212038111-645b65b6-a0f3-4751-9097-90680942ff16.png)

Yes, it did

**Comment by gjsjohnmurray** [comment] 2023-01-13 11:12
A setting at Workspace level will override one at User level.

**Comment by lramos15** [comment] 2023-01-18 15:40
Closing as cannot reproduce. Appears your workspace setting is overriding it.

**Closed by lramos15** 2023-01-18 15:40 UTC
