### ISSUE TITLE
Update 1.54.1 breaking MS Azure Functions Extension

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [microsoft/vscode#118572] opened 2021-03-09 19:16 UTC
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. install extension ms-azuretools.vscode-azurefunctions
2. create a simple azure function in C# to run locally
3. Start debugger
4. Debugger will fail with Cannot read property 'map' of undefined

This has also be reported in [extension](https://github.com/microsoft/vscode-azurefunctions/issues/2737) but based on the conversation in that thread and the fact that the extension hasn't changed and rolling back solves the problem that there must be something in the VS Code extension API that is breaking something.

Works with this version.
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Seems like an import bug so I thought I would raise the issue hear as well.

**Comment by nturinski** [comment] 2021-03-09 19:29
Related to https://github.com/microsoft/vscode/issues/118465

**Comment by TylerLeonhardt** [comment] 2021-03-09 19:56
Duplicate of #118465

**Closed** 2021-03-09 19:57 UTC
Labels: *duplicate
