### ISSUE TITLE
 On the integrated terminal, `ctrl + click` doesn't correctly open the file links with file URI schemes (file:///).

### ISSUE THREAD

**Issue by b4git** [microsoft/vscode#109696] opened 2020-10-29 20:08 UTC
- VSCode Version: 1.50.1
- OS Version: Windows 10, but running VSCODE with Remote WSL UBUNTU 20.04

Steps to Reproduce:

On the integrated terminal, `ctrl + click` on a normal file path such as `/mnt/c/myfile.js:20:10` opens it on the editor as expected. However, with file URI scheme links on the terminal such as `file:///mnt/c/myfile.js:20:10` it doesn't open the file, and gives a small pop-up notification  saying `Unable to open 'cwd': File is a directory`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2020-10-29 23:23
This works fine for me, does it do the same when you leave out `:20:10` or if you move myfile.js to another directory that wouldn't have any special permissions (like c:/users/you/documents)?

**Comment by b4git** [comment] 2020-10-30 01:47
@Tyriar My apologies if the environment and procedure to reproduce were not clear enough above.

This bug appears on  `bash` shells like `git-bash.exe` without WSL, or when using Remote WSL on Win 10 x64, so the path has to be Linux style (eg. `file:///mnt/c/myfile.js` instead of `file:///C:/myfile.js`). 

I can reproduce this issue by simply typing and control clicking `file:///mnt/c/myfile.js` on the terminal.

Example screenshot:
![image](https://user-images.githubusercontent.com/63267629/97649370-2e6dec00-1a25-11eb-812a-28b2347e479a.png)

**Comment by Tyriar** [comment] 2020-10-30 15:44
Oh yeah, it won't work there because `/mnt/c` isn't an actual path. I think supporting this is out of scope for vscode core as it's a quirk in git bash, but you could write an extension using the terminal link provider API to support links like this.

**Comment by b4git** [comment] 2020-10-31 05:48
@Tyriar 

It is very straight-forward to reproduce, so if you could, I would recommend you to reproduce and get familiar with the problem if you are interested. Anyways, here is the screenshot you requested:

![image](https://user-images.githubusercontent.com/63267629/97772203-c5fd3880-1b12-11eb-92e1-e42b93bdf96d.png)

**Comment by Tyriar** [comment] 2020-11-02 14:01
@b4git to be clear, I tried to reproduce it earlier and could not. I believe you but I couldn't make it happen. Thanks for the screenshot

**Comment by rzhao271** [comment] 2020-11-04 22:05
Cannot reproduce on the latest Insiders while running in WSL Ubuntu 20.04.
Links such as `file:///mnt/c/Users/raymondzhao/vscode/package.json:14:1` opened correctly for me.

Version: 1.51.0-insider (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-04T18:31:15.290Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment] 2020-11-06 00:34
There are reports that this happens for non-`file://` links too https://github.com/microsoft/vscode/issues/106687

**Comment by MBRGA** [comment] 2020-11-09 18:46
I am having this issue for the links in my terminal (Powershell, on Windows). I am getting "Open folder in New Window" for all of my file links.

![image](https://user-images.githubusercontent.com/6494474/98582295-744f6d80-22cb-11eb-98c9-b941944d29ee.png)

Screenshot is my testing if it happens with Write-Host, but I have the same issue with what's being output by `rustc`/`cargo`. 

The workspace root is the `src` folder above, but I did reorganise the project once or twice so that may have had an impact? The `git` root is the parent of the `src` folder, and was originally the workspace root too (although I was still having this issue with that setup).

There's nothing but defaults in `workspace.code-workspace` (both this version and the one in the parent folder). There are a couple of things in `launch.json` and `c_cpp_properties.json` in the `.vscode` folder. Behaviour hasn't changed whether I have `.vscode` as a subdirectory of `src`, or the parent folder.

**Comment by Tyriar** [comment] 2021-01-29 14:46
I tried again and unfortunately I can't reproduce, if anyone has better repro steps please let me know.

**Closed** 2021-01-29 14:46 UTC
Labels: *not-reproducible, bug, integrated-terminal, integrated-terminal-links, needs more info
