### ISSUE TITLE
Git Bash terminal doesn't launch at startup

### ISSUE THREAD

**Issue by bayrambayramli** [microsoft/vscode#132980] opened 2021-09-13 11:41 UTC
Issue Type: <b>Bug</b>

I've selected "Git Bash" as a default terminal shell but VSCode opens PowerShell each time I open it. I have to manually change it to Git Bash every time. 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|has|2.14.0
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
vscode-yaml|red|0.22.0

</details>

**Comment by bayrambayramli** [comment] 2021-09-13 11:46
User settings.json

#============
{
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.rightClickBehavior": "default",
    "redhat.telemetry.enabled": false,
    "window.zoomLevel": 1,
    "terminal.integrated.profiles.windows": {
		"PowerShell": {
			"source": "PowerShell",
			"icon": "terminal-powershell",
			"overrideName": true
		},
		"Command Prompt": {
			"path": [
				"${env:windir}\\Sysnative\\cmd.exe",
				"${env:windir}\\System32\\cmd.exe"
			],
			"args": [],
			"icon": "terminal-cmd"
		},
		"Git Bash": {
            "path": [
                "C:\\Program Files\\Git\\bin\\bash.exe",
            ],
            "args": ["--login"],
            "icon": "terminal-bash",
			"overrideName": true
		}
	}
}

**Comment by IllusionMH** [comment] 2021-09-13 11:52
/duplicate of #132150 and other for open in internal terminal

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 11:53 UTC
Labels: *duplicate
