### ISSUE TITLE
Ubuntu hotkeys

### ISSUE THREAD

**Issue by kbytin** [Microsoft/vscode#5946] opened 2016-04-28 13:31 UTC
- VSCode Version: 1.0.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Ctrl+Shift+Alt+Down - default ubuntu hotkeys to move window to other desktop

I set Ctrl+Shift+D for me right now, but it will be nice to have OS dependency of hotkeys out of the box

**Comment by Tyriar** [comment] 2016-05-12 08:43
Duplicate of https://github.com/Microsoft/vscode/issues/509

**Closed by Tyriar** 2016-05-12 08:43 UTC
