### ISSUE TITLE
Emmet 2.0: Gives inappropriate suggestions

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31044] opened 2017-07-19 13:42 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:31:43.209Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.27.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. type `p` for a `<p></p>` in an html file
2. Emmet suggests `param` instead.  I don't even know what that tag is.  It doesn't even offer the default paragraph tag.

![jul-19-2017 09-39-55](https://user-images.githubusercontent.com/835148/28369761-85c83fd4-6c66-11e7-8aa5-ec843db7c466.gif)

**Comment by michou** [comment] 2017-07-19 15:40
+1, although after deleting the generated `<param>` once, I'm able to convince Emmet to expand a `p` to `<p>|</p>`

**Comment by smlombardi** [comment] 2017-07-19 19:22
@michou Not me, it keeps suggesting param.

**Comment by ramya-rao-a** [comment] 2017-07-19 20:35
Duplicate of #31003

Please follow the discussion there.

**Closed by ramya-rao-a** 2017-07-19 20:35 UTC
Labels: emmet, insiders
