### ISSUE TITLE
Error formatting html

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#16675] opened 2016-12-06 15:01 UTC
- VSCode Version: Windows 10
- OS Version: 1.8.0 - insider a8d5b92

Steps to Reproduce:

-- Sorry for the English, I used Google Translator --

1. Formatting was strange compared to 1.7.2. All extensions disabled

![gif9](https://cloud.githubusercontent.com/assets/19866231/20930223/d272c3ae-bbb3-11e6-94b9-f54235e0d2d5.gif)

**Comment by aberman** [comment] 2016-12-14 23:39
+1.  Same issue here.

**Comment by aeschli** [comment] 2016-12-15 08:47
@Tekbr @aberman Can you paste the code snippet to reproduce?

**Comment by Tekbr** [comment] 2016-12-15 13:02
@aeschli 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div class="">
        <div class="" id="">
            <div class="">
                <h5>
			<b> Teste</b>
		</h5>
            </div>
            <hr style="margin-top: 10px;">
            <ol>
                <li>
                    <h5>
                           <img src="view/test.png" width="190" height="35" align="middle" />
		    </h5>
                </li>
            </ol>
        </div>
    </div>
    
</body>
</html>
```

**Comment by aberman** [comment] 2016-12-15 17:15
@aeschli , the HTML by @Tekbr exhibits the issue.  Thanks!

**Comment by adjeteyadjei** [comment] 2016-12-29 06:13
Same issue here. 
The formatting breaks after the **style** attribute.

**Comment by gmhispagnol** [comment] 2017-01-23 20:41
Same here. Any updates?

**Comment by aeschli** [comment] 2017-01-23 23:55
duplicate of #17849

**Closed by aeschli** 2017-01-23 23:55 UTC
