### ISSUE TITLE
Find in Files incompatible with latest OneDrive in Windows 10

### ISSUE THREAD

**Issue by aaronsace** [Microsoft/vscode#36850] opened 2017-10-24 21:50 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. Move folder contenting code files (.ps1) to OneDrive. 
2. Find in Files no longer searches within any of the file contents unless they are open for editing. (basically search simple doesn't work)

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-10-24 22:09
Dupe of #35433

**Closed by roblourens** 2017-10-24 22:09 UTC
Labels: search
