### ISSUE TITLE
TS version selector coming up after opening a newly clones folder

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#25559] opened 2017-04-27 14:58 UTC
In order to test #25332 I need to clone a repo I didn't have on my machine before. When I opened the workspace with `code-insiders .` without having run `npm install` before, I got the TS version prompt. 

I'd expected the prompt to come up when I open the first TS file and not on startup.

<img width="1029" alt="screen shot 2017-04-27 at 7 53 27 am" src="https://cloud.githubusercontent.com/assets/4674940/25489537/f51bc29a-2b1e-11e7-9ed9-86e8846f28dc.png">

**Comment by mjbvz** [comment] 2017-04-27 15:30
This is caused by the presence of the `tsconfig.json` file in this case. We activate the ts extension when it is present

The correct fix is probably to make the ts client lazily instantiated so that we only end up showing this dialog when the ts client is first really needed

**Comment by mjbvz** [comment] 2017-05-05 06:29
Fixed by d16e095

**Closed by mjbvz** 2017-05-05 06:29 UTC
Labels: bug, typescript
