### ISSUE TITLE
Extra pair of brackets after cmd-tabbing

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#54766] opened 2018-07-20 19:23 UTC
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Open a JS file. Type the following: `test.filter()`
2. With the cursor between the `()`, cmd-tab to another app, then switch back to VSC. Now type `(`. Rather than one more set of parens added, two sets are added, so that you end up with: `test.filter((()))`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-07-31 13:54
Duplicate of #49480

**Closed by alexandrudima** 2018-07-31 13:54 UTC
Labels: bug, editor-input, mac
