### ISSUE TITLE
git提交时输入中文内容有时会卡死输入框

### ISSUE THREAD

**Issue by dxq0126** [microsoft/vscode#114875] opened 2021-01-25 03:02 UTC
版本: 1.52.1 (user setup)
提交: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
日期: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.源代码管理
2.输入中文消息内容
3.输入框卡死，无法输入

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dxq0126** [comment] 2021-01-25 03:23
When I use Microsoft input method (Chinese language) to input content notes in source code management, it has a great probability that the input box will become stuck, which I encounter almost every time I submit.

I think this is probably a problem caused by Microsoft's input method. At present, I have replaced the input method. I hope I won't encounter such a problem again.

**Comment by yume-chan** [comment] 2021-01-25 06:10
Duplicate of #112621

Please wait for next release, or try Insiders Channel (https://code.visualstudio.com/insiders/)

**Comment by joaomoreno** [comment] 2021-01-25 08:41
This is already fixed in `master`, comes out next stable.

**Closed by joaomoreno** 2021-01-25 08:41 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
