### ISSUE TITLE
Ability to see disabled extensions in a json file

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#70392] opened 2019-03-13 11:49 UTC
As per the this closed issue [code --list-extensions-json, --list-extensions-enabled, --list-extensions-disabled #69090](https://github.com/Microsoft/vscode/issues/69090), I would like to extend on it and propose a solution:

> list all installed/disabled global/workspace extensions in their respective json files.

**why:** I would like to see disabled extensions listed in a json file so that I can quickly re-enable them in batches by modyfing that file. Note that it is different from "enable all extensions" option, since there are few extensions I want to keep disabled and re-enabling all others one by one isn't an option.  
I have encountered some settings / extension interference and while trying to locate the culprit, I had to disable/re-enable extensions while also playing with the settings. This was very uncomfortable.

**Comment by sandy081** [comment] 2019-03-15 15:17
Duplicate of https://github.com/Microsoft/vscode/issues/40239

**Closed** 2019-03-15 15:17 UTC
Labels: *duplicate, extensions
