### ISSUE TITLE
broken download url

### ISSUE THREAD

**Issue by theraw** [microsoft/vscode#188197] opened 2023-07-18 20:51 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: x
- OS Version: x

Steps to Reproduce:

1.  try to download https://code.visualstudio.com/ (tested insiders aswell)
2.  returns https://code.visualstudio.com/sha/undefined (tested from 2 different devices)

**Comment by HeinrichAD** [comment] 2023-07-18 20:58
Same goes for the download link inside the vscode server setup script <https://aka.ms/install-vscode-server/setup.sh>.

It says:
> Installing from https://aka.ms/vscode-server-launcher/x86_64-unknown-linux-musl

But instead of downloading the `code-server` binary it downloads the webpage <https://code.visualstudio.com/docs/remote/tunnels>.

**Comment by rzhao271** [comment] 2023-07-18 22:21
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496
I've identified the problem and I'm working on a fix.

**Closed by rzhao271** 2023-07-18 22:21 UTC

**Comment by rzhao271** [comment] 2023-07-19 18:51
@HeinrichAD I confirmed that that is an intentional change.
code-server has been replaced by Remote Tunnels.

**Comment by HeinrichAD** [comment] 2023-07-19 19:00
@rzhao271 thank you for the fast response.

That's sad for me because I wanted to do something like self-hosting <https://vscode.dev> for internal usage. So that my colleges could open their local files/projects and work on them from everywhere without installing vscode (and some internal extensions) or having their own directory on the server. As far as I read until now "Remote Tunnels" are not the right thing for me. If you have a tip for me, even if this is just the message that this is not supported, I would appreciate it.

**Comment by rzhao271** [comment] 2023-07-19 21:53
If you mean `serve-local`, that feature request is being tracked at https://github.com/microsoft/vscode/issues/168492

**Comment by Ali-Flt** [comment] 2023-08-21 00:04
@rzhao271 So shouldn't [the document](https://code.visualstudio.com/blogs/2022/07/07/vscode-server#_getting-started) be updated?

**Comment by rzhao271** [comment] 2023-08-21 21:29
@Ali-Flt the document was updated at https://code.visualstudio.com/blogs/2022/07/07/vscode-server#_a-remote-present-and-future.
