### ISSUE TITLE
High contrast focus border around extension list item gear is a bit wonky

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15858] opened 2016-11-22 04:37 UTC
- VSCode Version: Code 1.7.2 (7ba55c5, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.8.0-26-generic

![image](https://cloud.githubusercontent.com/assets/2193314/20511120/46f5f2a4-b02a-11e6-8437-675fe1e752d7.png)

**Comment by sandy081** [comment] 2017-01-10 11:05
Duplicate of #16876

**Closed by sandy081** 2017-01-10 11:05 UTC
Labels: accessibility, extensions
