### ISSUE TITLE
Can't type git commit message

### ISSUE THREAD

**Issue by zinwalin** [microsoft/vscode#113617] opened 2020-12-31 06:02 UTC
I can't type commit message, not sure why it happens.  

![image](https://user-images.githubusercontent.com/5416196/103396858-7964c680-4b70-11eb-9a07-c280a4be4b86.png)

**Comment by eamodio** [comment] 2021-01-04 20:59
Duplicate of #113527

**Closed by eamodio** 2021-01-04 20:59 UTC
