### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Fabianko** [microsoft/vscode#101771] opened 2020-07-06 01:04 UTC
**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. Open visual studio code
2. install deno and angular extensions
3.
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99888:161)
    at resolveModuleNamesWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100255:19)
    at processImportedModules (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101668:35)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101411:17)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:60
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:16)
    at synchronizeHostData (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138726:26)
    at Object.getProgram (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146581:44)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:97
    at Object.flatMap (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

**Comment by mjbvz** [comment] 2020-07-06 06:35
Duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-07-06 06:35 UTC
