### ISSUE TITLE
Disable webview context menu in media preview

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#175161] opened 2023-02-22 20:02 UTC
1. Open https://insiders.vscode.dev/github/microsoft/vscode-docs/blob/493bfd60c8f0e15519b5cf15f71fd6c1b2c1ff4d/release-notes/images/1_75/sash.mp4
2. Right click on image
3. :bug: The default webview context menu appears with 'cut', 'copy' and 'paste', but selecting each of those options does nothing

![image](https://user-images.githubusercontent.com/30305945/220745443-9c39d290-cf51-4755-aadd-afec5f55bc74.png)

**Comment by mjbvz** [comment] 2023-02-22 21:00
Duplicate of #171616

**Closed by mjbvz** 2023-02-22 21:00 UTC
