### ISSUE TITLE
Syntax Highlighting In JavaScript Broke After The Latest Update

### ISSUE THREAD

**Issue by MidSpike** [microsoft/vscode#92385] opened 2020-03-10 17:10 UTC
Issue Type: <b>Bug</b>

2000+ lines of javascript now show wonky colours in the wrong places for syntax highlighting. Specifically calling/defining methods are blue in some spots instead of yellow.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4785T CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
aspire-gsc|Asp|0.1.2
xml|Dot|2.5.0
vdf|GEE|0.0.6
discord-vscode|icr|3.13.0
Lua|key|0.0.9
python|ms-|2020.2.64397
remote-wsl|ms-|0.42.3
vsliveshare|ms-|1.0.1711
vscode-unitymeta|PTD|0.0.7
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
cod-sense|se2|1.0.1
comment-box|Sly|2.0.0
sass-indented|syl|1.7.5
python|tht|0.2.3

</details>

**Comment by rebornix** [comment] 2020-03-10 17:13
/duplicate of #92308 , thanks for your feedback!

**Closed** 2020-03-10 17:13 UTC
Labels: *duplicate, new release

**Comment by nurmohammed840** [comment] 2020-03-11 00:27
change setting : "editor.semanticHighlighting.enabled": false,
