### ISSUE TITLE
formatting document clears my code in the latest update

### ISSUE THREAD

**Issue by mubtxs** [Microsoft/vscode#22394] opened 2017-03-10 13:47 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vsc-ember-cli|felixrieseberg|0.3.2|
|beautify|HookyQR|0.8.1|
|rest-client|humao|0.12.2|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|vscode-docker|PeterJausovec|0.0.12|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|Ruby|rebornix|0.10.4|
|sass-indented|robinbentley|1.3.0|
|Spell|seanmcbreen|0.9.1|
|vscode-react-native|vsmobile|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment] 2017-03-10 21:01
We need more details.
In what kind of files does this happen?
Can you try disabling extensions `code --disable-extensions` to ensure that none of the extensions are causing this?

**Comment by weinand** [comment] 2017-03-14 21:49
This sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment] 2017-03-15 09:33
No reply -> closing.

**Closed by weinand** 2017-03-15 09:33 UTC
Labels: needs more info
