### ISSUE TITLE
Intellisense shows loading indefinitely

### ISSUE THREAD

**Issue by Ansal-Khan** [microsoft/vscode#87870] opened 2019-12-30 09:29 UTC
Issue Type: <b>Bug</b>

1. Open a project in visual studio code(React).
2.Try intellisense suggestion before doing npm install (Without node modules)
3.You can find the intellisense working perfectly.
4.Do npm install (add node modules) then try intellisense.
5.You can see it stuck at the loading text. no matter how much time you give.

This one have same effect even with all extensions deisabled.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (23.46GB free)|
|Process Argv|D:\react-workspace\brand-ui-ups\brand-app-ui-ansal|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by creeperyang** [comment] 2019-12-30 13:21
The same issue, and version info:

```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

Reopen the vscode will work correctly for minutes, and then Intellisense break down and always show   loading text when you hover any code.

**Comment by Ansal-Khan** [comment] 2019-12-30 13:28
@creeperyang 

I think the issue is with the version of vs code, and this is how I resolved it.

I removed vs code completely. even deleted the files in the following locations
%userprofile%\.vscode
%userprofile%\AppData\Roaming\Code
Then uninstalled VSCode.

Finally installed VSCode v 1.40.2
Also disabled auto update.
Now it works fine.

**Comment by creeperyang** [comment] 2019-12-31 02:50
> @creeperyang
> 
> I think the issue is with the version of vs code, and this is how I resolved it.
> 
> I removed vs code completely. even deleted the files in the following locations
> %userprofile%.vscode
> %userprofile%\AppData\Roaming\Code
> Then uninstalled VSCode.
> 
> Finally installed VSCode v 1.40.2
> Also disabled auto update.
> Now it works fine.

Thanks, I will try it.

**Comment by creeperyang** [comment] 2019-12-31 13:47
I just uninstall v1.41.1 and turn back to v1.40.2, and everything get back to normal.

**Comment by zhbun** [comment] 2020-01-02 08:24
I have the same issue, is there any other ways to solving

**Comment by dylanjmcdonald** [comment] 2020-01-03 05:02
Same issue here. IntelliSense auto imports stopped working randomly while working on a project.

Windows 10.0.18363
Visual Studio Code 1.41.1

Rolling back to 1.40.2 fixed the issue.

**Comment by mjbvz** [comment] 2020-01-06 23:09
@Ansal-Khan Is your code stored somewhere besides the `c:` drive?

**Comment by Ansal-Khan** [comment] 2020-01-07 05:38
> 
> 
> @Ansal-Khan Is your code stored somewhere besides the `c:` drive?

My code resides in a separate disk.

**Comment by zzx0106** [comment] 2020-01-07 10:20
If you delete the node_modules file , it will return to normal. I think the @type file of node_modules is not loaded normally by vscode1.4.1

**Comment by programgamer-real** [comment] 2020-01-07 14:56
Hi, I'm having the same issue. My project folder is on a separate drive, but the path to it has a symlink back to my C: drive for convenience. Could this be the source of the problem?

To be clear, I made it so that `C:\Users\Me\Source` links to `E:\Users\Me\Source`, which is where I actually store my source code for all my projects. I open my project folder with the symlink path that starts with C:

**Comment by mjbvz** [comment] 2020-01-07 19:22
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-07 19:22 UTC
Labels: javascript, needs more info
