### ISSUE TITLE
Expand TypeScript Interface in IntelliSense

### ISSUE THREAD

**Issue by arb** [Microsoft/vscode#6638] opened 2016-05-22 20:47 UTC
- VSCode Version: 1.1.1
- OS Version: OSX 10.10.5

When using the typescript definitions installed from definitely typed, the IntelliSense doesn't seem to want to expand things that are declared as "interfaces". I've attached a snippet below as an example.

![image](https://cloud.githubusercontent.com/assets/1591483/15456376/ac916b58-203c-11e6-9f6d-25e5bcff7ef1.png)

From this screen shot, I have no way of knowing what is expected from the IRouteConfiguration interface.

Am I missing a setting somewhere or is this working as intended and I have to click around before being able to learn what the shape of that interface is?

**Update** 
It appears that once you start filling out the object, it does give you hints about the value you are using, but it seems like you already need to have an idea of the shape of the object before you start typing.

**Comment by dbaeumer** [comment] 2016-05-23 10:37
@arb this is actually as designed. You can start with and empty literal and then fill it out using IntelliSense. IMO showing more information in the signature hover would only makes things more complicated. Think about a literal with many properties. 

I will close this since showing a literal type here will not improve things.

**Closed by dbaeumer** 2016-05-23 10:37 UTC
Labels: typescript

**Comment by arb** [comment] 2016-05-23 13:38
I see this issue has been closed... is there going to be any follow-up or explanation? Is this just how it works or am I doing something wrong?

**Comment by grovesNL** [comment] 2017-02-02 04:36
@dbaeumer: Is there a way to enable this behavior (either VS Code options or through language services or some low level API)? It would be very useful to see the interface definition in quick info, otherwise I can't determine which properties are required without navigating to the definition. Code complete is nice, but if it's an unfamiliar interface (i.e. a library), the user has no idea which letters to type to start the discovery. 

Specifically in my case I'm testing Monaco with external type declaration files, so peek/go to definition won't actually allow them to view the interface.

I would prefer to see expanded definition like you displayed above, which is what type aliases do by default. If classes could implement type aliases I would use them instead of interfaces in most cases, solely for this reason.

**Comment by dbaeumer** [comment] 2017-02-02 08:41
@grovesNL  No there is currently no option to control this.

**Comment by sgronblo** [comment] 2017-11-17 18:06
I understand that in some cases it can be unhelpful to be shown a fully expanded typescript interface. However, if you are doing some type level trickery with Omit, Pick, extending, intersecting. It would actually be quite great to be able to see that your combined interface type actually has the expected shape.
