### ISSUE TITLE
Feature to disable or close project temporarily without removing from workspace.

### ISSUE THREAD

**Issue by shinurox** [microsoft/vscode#90422] opened 2020-02-11 06:56 UTC
Currently if we are working on multiple projects, we do not have an option to temporarily disable projects from the workspace and focus only on a single project. This is something like the close project feature in eclipse IDE.

**Comment by isidorn** [comment] 2020-02-12 11:18
Duplicate of working sets which we are looking into as an extension. More details here https://github.com/microsoft/vscode/pull/87666

**Closed by isidorn** 2020-02-12 11:18 UTC
