### ISSUE TITLE
The typescript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by slender9168** [Microsoft/vscode#26594] opened 2017-05-13 10:43 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: none
---

error message:
TSServer exited with code: 3

Steps to Reproduce:
- don't know how to reproduce the issue
- it only occurs in the current project ( if i open another project with the same vscode version, the error doesn't occur & intellisense works fine )

- intellisense is not working

**Comment by slender9168** [comment] 2017-05-13 11:18
I've found the cause of the issue:

- after cloning the project & checking out different commits, i've found the commit that caused type script server to stop working

- it is a single line of code ( that was added accidentally  & seems to confuse the type script server )

import MainTabView from '../../../../../../bitbucket apps/2017/myProject/src/screens/MainTabView'

- the import goes way back in the hierarchy  ( above the project files ) & enters it again, i don't know how it got written  or what plugin caused this  bad import statement ( although it works )

- the intellisense is now working again.

**Comment by mjbvz** [comment] 2017-05-18 01:29
I'm unable to reproduce this issue in my testing with the latest VSCode insiders builds. If you encounter this again, please try collecting the TS Server log so that we can investigate:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue
3. Run the `Open TSServer log File` command and view the `tsserver.log` file

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this


Closing since the issues seems resolved

**Closed by mjbvz** 2017-05-18 01:29 UTC
