### ISSUE TITLE
Git command stage file does not work on Windows

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#23473] opened 2017-03-28 17:33 UTC
https://github.com/Microsoft/vscode/issues/23305

- VSCode Version: Insiders latest
- OS Version: Windows

Steps to Reproduce:

1. Make a small change to a file (say `package.json`)
2. Open the command palatte and choose Git: Stage File

I expect this to stage the file. 
Actual: does nothing. 

With the file
![image](https://cloud.githubusercontent.com/assets/2449568/24418758/e2da4226-13a1-11e7-9ce9-4dae666288e5.png)

With the diff view
![image](https://cloud.githubusercontent.com/assets/2449568/24419028/b4ba53a8-13a2-11e7-85b3-d5ce4a8f4468.png)

**Comment by joaomoreno** [comment] 2017-03-29 07:45
Dupe of #23416

**Closed by joaomoreno** 2017-03-29 07:45 UTC
