### ISSUE TITLE
Option to disable "Failed to save '...': The content on disk is newer." check

### ISSUE THREAD

**Issue by egonelbre** [microsoft/vscode#66035] opened 2019-01-04 16:22 UTC
I would like an option to disable dirty write checking:

> Failed to save 'xyz': The content on disk is newer. Please compare your version with the one on disk.

My workflow does include dirty writes and having to go through the merging is annoying.

Example: keeping dirty state in an open file then switching git branch to save and commit (that file only), then switching back to the previous branch.

**Comment by nim** [comment] 2019-04-12 22:54
I am too. Not being able to save is infuriating me. A vivid example of a fitch that should not be done.

**Comment by brianonn** [comment] 2019-09-27 21:35
I saw this for the first time today, there is no option to "Force save anyways, because I know better than my IDE" 

![Screen Shot 2019-09-27 at 14 33 45](https://user-images.githubusercontent.com/2781333/65803661-1518b300-e134-11e9-97a0-dc930dd649e2.png)

**Comment by Pomax** [comment] 2019-10-20 17:21
This is handled by the built-in "merge conflict" extension. Go to your extensions, show built-in extensions, and disable it. Developer life gets a lot better without it.

![image](https://user-images.githubusercontent.com/177243/67163412-5a8b6300-f323-11e9-9f11-ce9e9b4473ed.png)

**Comment by donnie-msft** [comment] 2019-11-06 21:40
It feels to me that VSCode used to refresh the file contents more often. 

Also if I make another edit to the file in VSCode, I'd expect that I would now "win" the race and my save would occur, but instead I'm stuck with "failed to save" errors. Even closing and reopening VSCode doesn't affect this. I have to close the file, say "don't save", then reopen the file to be able to make edits. Feels like a design change or regression?

**Closed** 2019-12-09 09:48 UTC
Labels: feature-request, file-io, workbench-editors

**Comment by bpasero** [comment] 2019-12-09 10:02
Pushed 2 changes to make this better:
* a new setting `files.preventSaveConflicts` that allows to turn off save conflict detection (this can be set on a folder level so that e.g. you can disable this selectively for network folders only)
* a way to overwrite a file directly from the notification selectively

![image](https://user-images.githubusercontent.com/900690/70426449-5a7e2880-1a73-11ea-82a2-adf455118e2b.png)

**Comment by bpasero** [comment] 2020-01-29 11:08
**Note:** setting name changed to `files.saveConflictResolution` and needs to be configured as `overwriteFileOnDisk` to disable the confirmation prompt.
