### ISSUE TITLE
debug.log

### ISSUE THREAD

**Issue by TalhaNoory** [microsoft/vscode#116692] opened 2021-02-15 13:11 UTC
Issue Type: <b>Bug</b>

Im having issues with VS Code keeps making those debug.logs, which really annoys me more than i could ever imagine.

I've been trying to fix it(preventing them form popping up).
They pop up like every single time i open a folder, og i open VS Code, and they just feel to me like SPAM.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment] 2021-02-15 13:16
/duplicate of #115874

Fix already released in 1.53.2

**Closed** 2021-02-15 13:17 UTC
Labels: *duplicate
