### ISSUE TITLE
Error while opening code

### ISSUE THREAD

**Issue by Siddh7040** [microsoft/vscode#183201] opened 2023-05-23 10:34 UTC
i have issue with opening visual studio code 
it's take much time to open after update to latest version -May
and problem with the extension named C/C++

![Screenshot_20230523_160317](https://github.com/microsoft/vscode/assets/134385189/fb79c1a7-51d7-43c5-a69a-23a27c4cf034)

**Comment by gjsjohnmurray** [comment] 2023-05-23 11:36
/duplicate

Marking as duplicate of https://github.com/microsoft/vscode/issues/178962. Please let us know if McAfee is not installed on your PC, else use the instructions to resolve.

**Comment by Siddh7040** [comment] 2023-05-23 11:38
> /duplicate
> 
> Marking as duplicate of #178962. Please let us know if McAfee is not installed on your PC, else use the instructions to resolve.

I have installed McAfee

**Closed** 2023-05-23 11:42 UTC
Labels: triage-needed

**Comment by Siddh7040** [comment] 2023-05-23 11:49
Issue is fixed through adding code.exe in excluded files in McAfee
