### ISSUE TITLE
Visual Studio Code will not start on Debian 8.5 over VNC

### ISSUE THREAD

**Issue by segadude** [Microsoft/vscode#9016] opened 2016-07-10 02:31 UTC
- VSCode Version: 1.3.0
- OS Version: Debian 8.5 jessie 64-bit

Steps to Reproduce:

1. Type "code" into the MATE terminal

When I try to start Visual Studio Code on my Debian machine, nothing happens. No window appears on the screen. I am using MATE on Debian 8.5 64-bit. When I type "code" and press enter, I can see that the code process appears in the MATE System Monitor and top for about 4 or 5 seconds, then closes. I get no error message in the terminal. Visual Studio Code used to work on this machine, but the last few releases would not start.

**Comment by Tyriar** [comment] 2016-07-10 23:38
Did you install via the deb package?

**Comment by segadude** [comment] 2016-07-10 23:48
Yes, I installed via the deb package.

**Comment by Tyriar** [comment] 2016-07-10 23:50
Can you launch it via the launcher? Is there any output with `code --verbose`?

**Comment by segadude** [comment] 2016-07-11 00:25
I apologize, I should have mentioned that this happens when I control the machine over VNC. I didn't because I thought Visual Studio Code also didn't work when I was using the machine normally.  When I tried it sitting in front of machine, it started fine. This is the output I get when I run `code --verbose` over VNC:

```
Xlib:  extension "XInputExtension" missing on display ":1.0".
Xlib:  extension "XInputExtension" missing on display ":1.0".
libGL error:
No matching fbConfigs or visuals found
libGL error:
failed to load driver: swrast
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
(8:19:36 PM) ### VSCode main.js ###
(8:19:36 PM) /usr/share/code/resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
Xlib:  extension "XInputExtension" missing on display ":1.0".
Xlib:  extension "XInputExtension" missing on display ":1.0".

```

**Comment by Tyriar** [comment] 2016-07-11 18:39
Ah, this is a duplicate of #3451 then. There's a workaround for it here https://github.com/Microsoft/vscode/issues/3451#issuecomment-227197582

**Closed by Tyriar** 2016-07-11 18:39 UTC
Labels: install-update, linux, needs more info
