### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by lamuertepeluda** [microsoft/vscode#138980] opened 2021-12-13 10:49 UTC
Issue Type: <b>Bug</b>

Since latest updates the popup keeps coming with this issue.

My project is a full-js / no TypeScript project. TypeScript is an indirect dev dependency. I have some submodules with the same dev tech stack as the main module.

Here are the logs

**TypeScript Version:** 4.5.2

**Steps to reproduce crash**
1. Launch VS Code
2. Open a JavaScript file
3. Wait a (very) few minutes

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/home/vito/.vscode-server/data/logs/20211213T112019/exthost1/vscode.typescript-language-features/tsserver-log-LwLFu9/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:57005:22)
    at getPropertyOfType (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:57665:24)
    at resolveESModuleSymbol (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49811:54)
    at getTargetOfNamespaceImport (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48996:28)
    at getTargetOfAliasDeclaration (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49230:28)
    at resolveAlias (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at getSymbol (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47833:38)
    at resolveNameHelper (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48125:34)
    at resolveName (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48108:20)
    at resolveEntityName (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49447:42)
    at getTargetOfExportSpecifier (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49187:17)
    at getTargetOfAliasDeclaration (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49237:28)
    at resolveAlias (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at resolveSymbol (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49265:67)
    at mergeSymbol (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47619:42)
    at /home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at mergeSymbol (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47643:21)
    at /home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at initializeTypeChecker (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:84991:21)
    at Object.createTypeChecker (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47390:9)
    at Object.getTypeChecker (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:114385:79)
    at synchronizeHostData (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:159863:21)
    at Object.getProgram (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:159984:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:164998:53)
    at ConfiguredProject.Project.updateGraph (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:164927:42)
    at ConfiguredProject.updateGraph (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:165920:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:167644:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:168727:44)
    at /home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:169067:97
    at Object.flatMap (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:169067:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:170225:46)
    at /home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172158:88
    at IOSession.Session.executeWithRequestId (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172149:28)
    at IOSession.Session.executeCommand (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172158:33)
    at IOSession.Session.onMessage (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172184:35)
    at Interface.<anonymous> (/home/vito/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:174789:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.16GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/vito/Development/MOTION_V3/motion-server --remote=wsl+Ubuntu-20.04 --crash-reporter-id 006d989c-3eb0-457a-9b1b-9a793c06989b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|7.77GB (1.76GB free)|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
jsdoc-markdown-highlighting|bie|0.0.1
bracket-pair-colorizer-2|Coe|0.2.1
mustache|daw|1.1.1
javascript-ejs-support|Dig|1.3.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-nginx-conf-hint|han|0.3.0
output-colorizer|IBM|0.1.2
vscode-peacock|joh|4.0.0
vscode-mdx|Jou|0.2.3
eml|lei|0.4.0
dotenv|mik|1.0.1
vscode-language-pack-it|MS-|1.63.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.11.0
mdx|sil|0.1.0
vscode-nginx|wil|0.7.2
vscode-nginx-conf|ahm|0.1.3
atlascode|atl|2.10.0
npm-intellisense|chr|1.4.0
format-json|Cle|1.0.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-todo-plus|fab|4.18.4
html-preview-vscode|geo|0.2.5
shortcuts|giz|0.0.1
vscode-nginx-conf-hint|han|0.3.0
beautify|Hoo|1.5.0
vscode-ansi|ili|1.1.2
vscode-angular-components-intellisense|ipa|1.0.0
dependency-cleaner|jac|1.0.4
vscode-edit-csv|jan|0.6.4
rainbow-csv|mec|1.10.1
openapi-lint|mer|1.2.0
git-graph|mhu|1.30.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.18.0
vscode-language-pack-it|MS-|1.63.2
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
color-highlight|nau|2.5.0
vscode-jest|Ort|4.2.1
prettier-vscode|pre|3.14.1
nginx-formatter|ray|0.0.13
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
partial-diff|ryu|1.4.3
file-tree-generator|Shi|1.1.1
mdx|sil|0.1.0
sass-indented|syl|1.8.18
vscode-nginx-format|tec|0.0.6
mdx-inline|vad|0.1.0
vscodeintellicode|Vis|1.2.14
docker|vsc|1.0.0
yaml|vsc|1.0.0
vscode-nginx|wil|0.7.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by IllusionMH** [comment] 2021-12-13 12:24
/duplicate of https://github.com/microsoft/TypeScript/issues/47038

Please provide information/code/config of how to reproduce this issue in linked TS issue.

**Closed** 2021-12-13 12:25 UTC
Labels: *duplicate
