### ISSUE TITLE
"Extension host terminated unexpectedly." with no extensions

### ISSUE THREAD

**Issue by Souk21** [microsoft/vscode#126237] opened 2021-06-14 13:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0 & 1.58.0 Insider (2021-06-14T05:12:28.099Z)
- OS Version: OSX 10.11.6
- Node v14.17.0
- Git v2.27.0

Steps to Reproduce:

1. Open a project (or an empty folder)
2. Error "Extension host terminated unexpectedly."

I tried disabling every extensions, running `code --disable-extensions`, deleting `Application Support/Code`, deleting  `~/.vscode`, reinstalling VSCode, downgrading and re-updating.
I'm also having the same issue with the insider release.
I don't have this issue with VSCode 1.56.2, so downgrading and disabling automatic updates work as a workaround.

Here's the console log:

![logs](https://i.imgur.com/RmCX13U.png "logs")

Here's the output "Log (Window)"

```
[2021-06-14 15:05:04.946] [renderer1] [error] Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.extension-editing, vscode.typescript-language-features, vscode.debug-auto-launch, vscode.git, vscode.npm
[2021-06-14 15:05:04.958] [renderer1] [error] Error: No authentication provider 'microsoft' is currently registered.
    at O.getSessions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2000:11965)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async bi.getAccounts (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2417:10540)
    at async bi.update (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2417:10277)
    at async bi.initialize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2417:9247)
    at async bi.waitAndInitialize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2417:8647)
[2021-06-14 15:05:04.958] [renderer1] [warning] Settings Sync: Accounts are not initialized
```

And here's the output "Log (Extensions Host)"

```
[2021-06-14 15:05:04.149] [exthost] [info] extension host started
[2021-06-14 15:05:04.247] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-06-14 15:05:04.247] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-06-14 15:05:04.262] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:typescript"}
[2021-06-14 15:05:04.262] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/extension-editing/dist/extensionEditingMain
[2021-06-14 15:05:04.279] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:typescript"}
[2021-06-14 15:05:04.279] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
[2021-06-14 15:05:04.333] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-06-14 15:05:04.333] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2021-06-14 15:05:04.335] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-14 15:05:04.335] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2021-06-14 15:05:04.356] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":true,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"workspaceContains:package.json"}
[2021-06-14 15:05:04.356] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/npm/dist/npmMain
```

Thank you

**Comment by alexdima** [comment] 2021-06-14 15:22
Duplicate of https://github.com/microsoft/vscode/issues/125989


**Workaround:** none today, you can go back to `1.56.2` via [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin-universal.zip) and configure `update.mode` to `none` or `manual`.

**Closed by alexdima** 2021-06-14 15:22 UTC
Labels: macos
