### ISSUE TITLE
SCM 'Sync' and 'publish' commands should be disabled when there is no remote

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19290] opened 2017-01-24 22:20 UTC
Testing https://github.com/Microsoft/vscode/issues/19049

In the Git viewlet, 'sync' and 'publish' under the '...' menu are disabled when the repo has no remotes. In the SCM viewlet, when I click 'sync', I see `fatal: No remote repository specified. Please, specify either a URL or a`. In the git output log, I see that there's a newline in the message at that point. Maybe when git output is shown directly as a notification, lines should be joined.

**Comment by joaomoreno** [comment] 2017-01-25 08:26
Duplicate of #19345

**Closed by joaomoreno** 2017-01-25 08:26 UTC
