### ISSUE TITLE
VSCode Insiders will not launch on OSX

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#20555] opened 2017-02-13 16:02 UTC
- VSCode Version: 1.10.0
- OS Version: 10.12.3

Steps to Reproduce:

1. Click icon in dock.  Dot shows, but then goes away, no launch
2. Command line: `code-insiders --disable-extensions`  nothing happens at all

Worked earlier today, before latest insiders build updated.

**Comment by smlombardi** [comment] 2017-02-13 16:09
I deleted these 2 files and relaunched and it works now.  This never happened before.

![screen shot 2017-02-13 at 11 08 29 am](https://cloud.githubusercontent.com/assets/835148/22891303/ea17a7a4-f1dc-11e6-9afe-73be47349f45.png)

**Comment by kaw2k** [comment] 2017-02-13 16:19
Same thing here, I deleted the same files and it's working now.

**Comment by aaronbalthaser** [comment] 2017-02-13 16:27
I also have the same problem. It started after I went to the extensions and an error was thrown. I don't know, I feel like these daily updates are fairly problematic since this is the second time in two weeks I have had a broken editor. This has already thrown me off for at least an hour at work. I understand mistakes are made but daily updates to me only opens the door to more errors. Honestly I don't understand how sufficient testing can be done.

**Comment by lmartins** [comment] 2017-02-13 16:47
Same problem here, except that it my case I don't have the two files listed above.

**Comment by smlombardi** [comment] 2017-02-13 20:51
@aaronbalthaser It's a nightly build, they occasionally could be broken.  Keep a copy of the release version handy in case.

**Comment by brunnopleffken** [comment] 2017-02-13 21:01
Same here. And I don't have those files in `~/Library/Application Support/Code - Insiders`.

OS : macOS 10.12.3

**Comment by eamodio** [comment] 2017-02-13 23:00
Similar problem here after trying to uninstall an extension. Vscode would launch but I'd just get errors opening the extensions viewlet. After deleting those 2 files all seems well again.

**Comment by adriancarriger** [comment] 2017-02-14 05:19
@brunnopleffken I didn't see the files at first because they're hidden in the regular Finder window.
  
Try using the command line:

- View directory: `ls ~/Library/Application\ Support/Code\ -\ Insiders` 
- Delete it: `rm ~/Library/Application\ Support/Code\ -\ Insiders/Code\ -\ Insiders-*`

The file keeps coming back after I start up VS Code Insiders.

**Comment by markgoodyear** [comment] 2017-02-14 10:58
Thanks @adriancarriger, worked for me. They keep coming back after launch for me also, so need to delete again after closing.

**Comment by joaomoreno** [comment] 2017-02-14 13:51
Definitely a duplicate of #20564, the same underlying issue.

Sorry for the hassle guys!

**Closed by joaomoreno** 2017-02-14 13:51 UTC

**Comment by alper** [comment] 2017-08-31 10:41
I'm not on insiders, but my VSCode would not launch either and following this thread I found a bunch of .sock files in the directory which I deleted and then everything worked again.

```
srwxr-xr-x    1 alper  staff      0 Mar 11 17:13 1.10.1-shared.sock=
srwxr-xr-x    1 alper  staff      0 Mar 23 18:57 1.10.2-shared.sock=
srwxr-xr-x    1 alper  staff      0 Apr 14 13:23 1.11.0-shared.sock=
srwxr-xr-x    1 alper  staff      0 May 22 16:14 1.11.2-shared.sock=
srwxr-xr-x    1 alper  staff      0 Jun 29 12:53 1.12.2-shared.sock=
srwxr-xr-x    1 alper  staff      0 Jun 15 11:20 1.13.0-shared.sock=
srwxr-xr-x    1 alper  staff      0 Aug 22 15:00 1.13.1-shared.sock=
srwxr-xr-x    1 alper  staff      0 Aug 29 09:29 1.15.1-main.sock=
srwxr-xr-x    1 alper  staff      0 Aug 29 09:29 1.15.1-shared.sock=
```

**Comment by donaldpipowitch** [comment] 2017-09-18 11:19
I'm also not on Insiders and regularly have the problem that VS Code won't open. Sadly I can't see any .sock files or something else which looks strange.
