### ISSUE TITLE
Terminal font is truncated

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [microsoft/vscode#123629] opened 2021-05-12 03:45 UTC
Issue Type: Bug

The terminal renders Hack Nerd Font characters incorrectly when starting a terminal.

Characters look like this:
![image](https://user-images.githubusercontent.com/41282358/117915138-4220d600-b317-11eb-8487-2574d22a4ad6.png)

Steps to reproduce:

Open Visual Studio Code
Open the integrated terminal
By the way, when you change the terminal font to another font, then back to the previous front, the terminal starts to render correctly, but you need to do this every time you open an integrated terminal.

Open terminal
Open settings (JSON)
Update the terminal.integrated.fontFamily setting:
You read: terminal.integrated.fontFamily = "Hack Nerd Font"
Rewrite to: terminal.integrated.fontFamily = "monospace"
Save
Rewrite to: terminal.integrated.fontFamily = "Hack Nerd Font"
Save
Terminal renders correctly
![image](https://user-images.githubusercontent.com/41282358/117915217-68df0c80-b317-11eb-8e84-4822577109cc.png)

VS Code version: 1.56.1 (Universal)
OS version: Darwin arm64 20.3.0

**Comment by meganrogge** [comment] 2021-05-13 16:52
Duplicate of #120129 /duplicate

**Comment by Tyriar** [comment] 2021-05-14 13:46
Looks like some "nerd font" chars are wide which we cut to single width.

**Comment by Tyriar** [comment] 2021-05-14 13:49
Upstream issue: https://github.com/xtermjs/xterm.js/issues/3342

**Comment by Tyriar** [comment] 2022-12-08 16:48
I believe this is fixed now

**Closed by Tyriar** 2022-12-08 16:48 UTC
Labels: bug, upstream, terminal, upstream-issue-linked, terminal-rendering
