### ISSUE TITLE
copy paste files bug

### ISSUE THREAD

**Issue by shachardas** [microsoft/vscode#186140] opened 2023-06-26 08:44 UTC
after copying and pasting a file in the file tree i no longer can copy-paste text.
it happens often, i copy a file and then every time i use the paste it outputs the file name.
i can copy other text, i can paste it in the terminal but when i try to paste in the code editor it will always output the filename i copied last.
it is fixed by refreshing the page but it happens every time i copy a file

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment] 2023-06-26 19:55
Duplicate of #185466

**Closed by mjbvz** 2023-06-26 19:55 UTC
