### ISSUE TITLE
Expected a JSON object, array or literal - when opening README.md

### ISSUE THREAD

**Issue by mkoflerAT** [microsoft/vscode#88250] opened 2020-01-07 23:47 UTC
Issue Type: <b>Bug</b>

1. Create repository in a new folder with 'git init'
2. Go there and open vscode with 'code .'
3. Add a README.md in there with a table-of-content in it
4. Make your first commit
5. Close the README.md and leave vscode - reopen the repository
6. Open README.md again
7. Language detection fails and the README.md is recognized as JSON

The content with the example table-of-contents is here:
https://github.com/mkoflerAT/vscode-expected-json-bug/commit/43660937a4299a4a5af8cbaf8d068ddf45a34221

The problems-tab in vscode is showing now:

**"Expected a JSON object, array or literal." within the (non-existent!) file:
"package.json /c/code/vscode-bug/ (git)**

The language auto-detection switched over to JSON instead of Markdown.
I don't get this - there is no 'package.json' within my repository and never has been one.
When you click on the error-message you end up in a version of README.md.

If you do additional commits the problem gets worse over time and the problem
starts to duplicate. Take a look at my git-repository (current README.md).

https://github.com/mkoflerAT/vscode-expected-json-bug

I really, really hope you can tackle this issue, because it has been driving me nuts
for days now.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (24.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.13
githd|hui|2.2.0
csharpextensions|jch|1.3.1
csharpfixformat|Leo|0.0.84
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
snippet-creator|nik|0.0.5
vetur|oct|0.22.6

</details>

**Comment by mkoflerAT** [comment] 2020-01-08 15:10
This is for sure not a duplicate - please review.

**Comment by connor4312** [comment] 2020-01-08 16:13
Does this reproduce with all extensions disabled?

**Comment by mkoflerAT** [comment] 2020-01-10 19:20
OK - I narrowed it down - the issue does happen with all extensions disabled.
So the extensions don't seem to be the cause of the problem. 😞 Any idea how to fix this?

**Comment by mkoflerAT** [comment] 2020-01-10 19:30
@connor4312 Yeah the issue does reproduce with all extensions disabled. Sorry that it took me two days to answer, but I first had to narrow it down to be sure to give a proper answer. My suspicion is, that vscode does not like version-numbers within headlines (like @roblourens has a h2-headline in markdown with ## 4.12.5). We should also decide where to continue the conversation about this but, since this issue is created twice now.

**Comment by roblourens** [comment] 2020-01-10 19:45
This doesn't repro with the NPM extension disabled @dbaeumer

**Comment by roblourens** [comment] 2020-01-10 19:45
Also important repro step for me. In Step 6, open README.md **from the SCM viewlet**

**Comment by mkoflerAT** [comment] 2020-01-10 19:50
Here's a screenshot to show the problem exists even, if all extensions are disabled:

![package-json-bug-all-extensions-disabled](https://github.com/mkoflerAT/vscode-expected-json-bug/blob/master/2020-01-10-203625-package.json-bug-all-extensions-disabled.png?raw=true)

For those who want to replicate. Usually I re-create the issue like this:
  * Open the README.md
  * Add some text
  * Close the README.md
  * Stage and commit (but don't push!)
  * git reset HEAD~
  * Open README.md again (eventually close vscode)

**Comment by roblourens** [comment] 2020-01-10 22:17
@mkoflerAT the NPM extension is a builtin extension so you can disable it by searching `@builtin`

**Comment by mkoflerAT** [comment] 2020-01-11 00:15
Unfortunately this didn't work for me. I disabled the extension "NPM support for VS Code" but the issue still keeps popping up again - is the extension the right one? I wonder if it has something to do with the installed version of NodeJS which is my in my case **v13.5.0**. (node --version).
And how can disabling an internal extension be the solution? I'm going to develop an ASP.NET Core 3.1.00 razorpages application and I will need some node-packages in it...

**Comment by roblourens** [comment] 2020-01-11 04:01
Nvm, I was able to repro it with the NPM extension disabled too. How about the JSON Language Features extension though? I think disabling that is doing it...

**Comment by mkoflerAT** [comment] 2020-01-11 20:25
Deactivating "JSON Language Features"-extension made the problem disappear so far. So it did the trick for me as well. But I wonder - don't I need this extension when developing ASP.NET Core Applications. Since it's a builtin extension it's rather important I assume?

**Comment by roblourens** [comment] 2020-01-12 17:49
It provides language features for JSON like autocomplete and syntax errors, and you can safely work without it, just knowing that those things won't work.

**Comment by mkoflerAT** [comment] 2020-01-13 01:05
OK - thank you for the explanation. Will this bug within the "JSON Language Features"-extension be fixed soon - or will the bug stay like it it is? Will here be an update, once the bug is fixed?

**Comment by aeschli** [comment] 2020-01-13 09:18
There seems to be a virtual text document `package.json` around, created by the `git` extension.

**Comment by joaomoreno** [comment] 2020-01-13 14:34
Classic, this issue comes up every time we change something with virtual documents. @sandy081 can we simply exclude everything `gitfs` as well in Problems?

**Comment by sandy081** [comment] 2020-01-15 12:33
Not sure if we have such filters already. I would not recommend to add such a filter to view. If we do not want them, they should not be entering into the system at all - Filtered at model level.  @jrieken FYI.

**Comment by joaomoreno** [comment] 2020-01-16 09:34
OK, this seems to be something other than what I thought.

> There seems to be a virtual text document `package.json` around, created by the `git` extension.

I'm pretty sure the git extension doesn't create this document, but it's coming from some other place. Investigating.

@egamma you hit this many many times in the past, we finally have a repro.

**Comment by joaomoreno** [comment] 2020-01-16 09:38
The `extension-editing` extension is creating the markers.

**Comment by chrmarti** [comment] 2020-01-26 20:09
@joaomoreno Cannot reproduce. What is the scheme of the document URI? We've fixed a similar issue (#36236) by ignoring files with 'git' scheme.

**Comment by joaomoreno** [comment] 2020-01-27 10:43
We can't repro anymore since I merged `gitfs` back into `git`, so the filtering is working. Also, the issue happens because the extension asks for the contents of a `git:.../package.json` file, which the git extensions simply resolves to the empty string, since the file doesn't exits in the repo and a non-existent file is as good as the empty string. We can close this.

**Closed by joaomoreno** 2020-01-27 10:43 UTC
Labels: bug, extensions-development, needs more info

**Comment by lithiumfox** [comment] 2020-01-28 02:30
Wait so what was the solution because I'm getting this error just starting out with git

**Comment by chrmarti** [comment] 2020-01-28 06:55
@lithiumfox This should be fixed in the latest VS Code Insiders build. There was a `gitfs` URI scheme for documents triggering it and that scheme is no longer in the code.
