### ISSUE TITLE
fail to reformat

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#14746] opened 2016-10-31 09:02 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: robertohuertasm.vscode-icons-3.0.7

Steps to Reproduce:

1.  write a wrong syntax
2. format
3. then it will fail

this bug don't show easily, but it can show up very often.

**Comment by weinand** [comment] 2016-10-31 09:27
@calidion syntax in what language?
Please provide reproducible steps and an example of the 'wrong syntax' that fails to format.

**Comment by calidion** [comment] 2016-10-31 09:49
@weinand 
it will show up occasionally, not 100%。
reloading will solve the problem.
language: javascript.
but the cause is definite: syntax errors.
everytime it fails the syntax checker will fail to parse and highlight.

**Comment by weinand** [comment] 2016-10-31 10:03
@calidion we need a screenshot that shows in what way "the syntax checker will fail to parse and highlight".

**Comment by calidion** [comment] 2016-10-31 10:39
@weinand 

ok, i will take one when it happens again.

**Comment by aeschli** [comment] 2016-11-07 11:20
Closing issue due to lack of additional information.

**Closed by aeschli** 2016-11-07 11:20 UTC
Labels: needs more info

**Comment by calidion** [comment] 2016-11-11 07:46
this problem can not be visually described!
I have just encounter again.
the only problem is that the format command doesn't work again.
screen shots won't help here.

**Comment by calidion** [comment] 2016-11-11 07:47
it seems nothing to do with syntax error.
please reopen it since it hasn't be solved.
