### ISSUE TITLE
The functions in JavaScript are not displayed

### ISSUE THREAD

**Issue by sergiotl** [Microsoft/vscode#5191] opened 2016-04-12 13:48 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10 pro

 In HTML document the functions in JavaScript are not displayed when using operator "." inside of `<script> </script>` label. For example, in version 0.10.6 I can use:

`<script>`
        `var myVar = document.(all functions appear listed here);`
`</script>`

However, in the current version, the functions are not shown. I have tried to install extensions to try to mitigate it, but the problem persists.

Any of you have the same problem?

Update:

When working in HTML within the `<script>` tag functions do not appear, but. if the language is changed to JavaScript on the bottom right, the functions appear correctly, but marks syntax errors throughout the document, the solution to this is to set the language HTML and restart VS Code.

**Comment by egamma** [comment] 2016-04-13 10:46
This is a known limitation of the new JavaScript infrastructure we are now using, sorry.

Closing as duplicate of #3465

**Closed by egamma** 2016-04-13 10:46 UTC
