### ISSUE TITLE
VSCode doesn't repond to keyboard input

### ISSUE THREAD

**Issue by Pianist038801** [Microsoft/vscode#37736] opened 2017-11-06 21:07 UTC
VSCode is my favorite text editor. Nowadays I realized that keyboard input is not working on editor for several times.
Now I am stuck again.
In terminal window of VSCode, keyboard works.
But on edit screen, when I try to type sth, never works.

**Comment by maximus12793** [comment] 2017-11-06 22:00
@Pianist038801 can you include repro steps? terminal/editor functionality is working for me, in addition any plugins you may have installed.

**Comment by pvoid** [comment] 2017-11-07 10:32
I have the same issue on my ubuntu. Not sure that it's related, but chrome updated recently on my laptop. Every time I am trying to type this appears in console

`shell.ts:454 Cannot read property 'value' of null: TypeError: Cannot read property 'value' of null
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29:25654
    at n.Class.derive._creator.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at e._activateByEvent (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29:25629)
    at e.activateByEvent (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29:25317)
    at t.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:1080233)
    at e.type (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:1291328)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:1530408
    at e.invoke (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:67540)
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:69263)
    at HTMLTextAreaElement.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:391462)`

**Comment by pvoid** [comment] 2017-11-07 11:03
In my case everything star working if I disable ms-vscode.cpptools. There is only one problem with it - I am using vscode for C++ programming :smile:

**Comment by alexandrudima** [comment] 2017-11-07 11:06
@pvoid From looking at the code, there should be at least one additional error before this error:

This is where the NPE happens for you: https://github.com/Microsoft/vscode/blob/968934c141223d252de6b5ba6257c52fc7a94bed/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L253

This is where the `proxy` comes from:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L152-L161

So I'd expect for you to see an additional error `Error received from starting extension host`.

**Comment by pvoid** [comment] 2017-11-07 11:19
@alexandrudima you are right. The first exception that I get in log just after VSCode starts is

`shell.ts:454 Invalid string length: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Object.t.stringify (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:22029)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:2444205
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:53561)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:57126)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:58954)
    at n.Class.derive._oncancel._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:58395)
    at l (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:61890)
    at n.Class.derive.join.r.forEach.$.then.o.(anonymous function) (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:62104)
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:53561)`

**Comment by alexandrudima** [comment] 2017-11-07 11:39
@pvoid The stack trace indicates that one of the parties (either the renderer process or the extension host process) tries to call `JSON.stringify` (serialize to a string) with an object that is so large that it goes beyond ~130MB or so where v8 begins to throw `RangeError: Invalid string length`. 

Most likely the extension host makes a request to the renderer process, and while trying to reply to it, the renderer process ends up needing to serialize a very large object; one that is so large that it cannot fit in a v8 string.

Perhaps it would be best for you to create an issue at https://github.com/Microsoft/vscode-cpptools . Perhaps it is something specific about your project that triggers this behaviour.

**Comment by pvoid** [comment] 2017-11-07 11:59
@alexandrudima I am not sure that the problem is related to my project. I got the first exception even before I open any project. Also even with disabled extension, VSCode is painfully slow in typing. Also, it takes almost 2 minutes to show the tab with extensions. Something changed in the environment (and it could, there were couple system updates since last time a ran vscode). There is only one record in log `Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.` Do you have any suggestions what I should check?

**Comment by Jefisovas** [comment] 2017-11-07 16:59
Same issue on OSX. VSCode does not respond to keyboard, lol...
Disabling cpp-tools resolves the issue...

**Comment by pvoid** [comment] 2017-11-08 09:19
Ok, I solved the problem by removing .vscode folder from home. No everything (including cpp-tools) works.

**Comment by michael-mayes** [comment] 2017-11-08 11:20
Looking in Process Explorer, I saw that the Intellisense process was not running

Uninstalling the extension and reinstalling it has brought the Intellisense process back and restored the ability to type

**Comment by sean-mcmanus** [comment] 2017-11-08 20:17
@alexandrudima The cpptools team doesn't have any idea how we could suddenly be causing the keyboard to not work. Our last update was October 19th, although we did update the clang-format we publish to 5.0 earlier last week. We have not been able to repro this problem yet. Any help resolving this would be appreciated.

**Comment by alexandrudima** [comment] 2017-11-13 14:52
@sean-mcmanus 

There are multiple things going wrong and the cause gets mixed up with the effects.

1. In 1.17, VSCode shipped with a bug where typing in the editor was blocked on the built-in emmet extension getting activated (#36575). @ramya-rao-a has fixed that in the meantime and 1.18 contains the fix.

2. emmet shares the extension host process with any other installed extensions. If emmet cannot start because another extension is causing the extension host process to crash or stall for very long times, this will lead to not being able to type in the editor (in 1.17), since typing is dispatching `onCommand:type` and emmet blocks it by having it as an activation event.

So, in 1.18 (already on stable channel), typing in the editor will be possible regardless of what the extension host process is doing. 

However, @pvoid, @Jefisovas  and @michael-mayes have all found it that the C++ extension *might have something to do with it*. @pvoid @Jefisovas @michael-mayes Do you perhaps have any extra information for @sean-mcmanus ? I suggest the investigation on the C++ extension side continues in https://github.com/Microsoft/vscode-cpptools/issues/1215

IMHO, typing in the editor being blocked was an effect of the extension host starting up very slowly, being busy or unresponsive.

**Closed by alexandrudima** 2017-11-13 14:52 UTC
Labels: needs more info

**Comment by michael-mayes** [comment] 2017-11-13 15:02
@alexandrudima @sean-mcmanus 

Thanks for the explanation

Also posted at Microsoft/vscode-cpptools#1215:

It looked in my case that the Intellisense process was not running. This was cured only by the re-installation of the  #C/C++ extension (*not* the re-installation of VS Code for clarity)

Is it possible that the inability for the C/C++ extension to detect the Intellisense process as running caused it to stall its completion of startup, so holding off the Emmet extension and preventing typing?

**Comment by alexandrudima** [comment] 2017-11-13 15:22
> Is it possible that the inability for the C/C++ extension to detect the Intellisense process as running caused it to stall its completion of startup, so holding off the Emmet extension and preventing typing?

All extensions share the same nodejs execution thread. If a certain extension `A` keeps the execution thread busy for a long time, or if it causes the entire process to crash, it will impact another extension `B`. But that should be the full extent of two extensions negatively affecting each other...
