### ISSUE TITLE
Integrated terminal prompt erases history output when remote directory was opened

### ISSUE THREAD

**Issue by milesxu** [microsoft/vscode#91817] opened 2020-02-29 15:49 UTC
- VSCode Version: 1.42.0/1, and vscode insiders with Remote SSH Nightly
- OS Version: Local: Windows 10 or Linux (test on x86-64 kernel 5.4)

[remote ssh terminal error.zip](https://github.com/microsoft/vscode/files/4270470/remote.ssh.terminal.error.zip)

The zip file contains a video which shows the error. 

Steps to Reproduce:

1. Use the newest vscode or  vscode insider and the remote ssh extension to connect to a remote host. I have tested with remote ssh nightly as well as 0.49, 0.48 and 0.47
2. Open a directory or workspace. **I have not encountered this error when no remote directory is opened.**
3. Open the integrated terminal, and then close it (with Ctrl+J) after executing some commands.
4. Reopen the terminal again, you will find that some of the history output will be deleted as the prompt has shifted up several lines by error.

Does this issue occur when all extensions are disabled?: Yes/No
Yes. I have tested on vscode insider only with Remote SSH Nightly installed.

**Comment by milesxu** [comment] 2020-02-29 15:53
I have checked submitted issues, and did not find one with similar error.

**Comment by Tyriar** [comment] 2020-03-02 14:45
Interesting, this looks like it could be a Windows only issue, are you sure you saw it on Linux?

> OS Version: Local: Windows 10 or Linux (test on x86-64 kernel 5.4)

Can you clarify this for which local and remote OS's, including the Windows build number (run `ver` in cmd.exe) whether it's both local and remote.

**Comment by milesxu** [comment] 2020-03-02 15:56
Hi @Tyriar, I have two client machines which run Linux and Windows respectively. **Both of Vscode on them** have encountered this error.
And the server runs Linux.
And, the error exists no matter how I choose which shell such as bash or zsh.

**Comment by Tyriar** [comment] 2020-04-06 16:05
> And the server runs Linux.

@milesxu oh ok, you're connecting to the same machine from both clients, I get it.

Can you enable [escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) and check what gets printed in the console when you try to repro?

**Comment by milesxu** [comment] 2020-04-07 15:42
![image](https://user-images.githubusercontent.com/2003731/78689662-29cad480-7929-11ea-9f22-0928a82f6fc9.png)
![image](https://user-images.githubusercontent.com/2003731/78689727-3d763b00-7929-11ea-8663-2aa2f4207529.png)

I have tried to copy the texts only, but I cannot make them readable. So I capture the screen above.

**Comment by milesxu** [comment] 2020-04-07 15:45
These images are captured when on a Windows 10 client which was connected to a Linux server by Remote SSH.

If you need debug info on a Linux client, I can capture some when I go to work tomorrow.

**Comment by Tyriar** [comment] 2020-04-07 17:04
Hmm, not exactly what I was expecting. Toggling it on should show this in the logs (even for remote workspaces) when any changes occur in the terminal:

![image](https://user-images.githubusercontent.com/2193314/78698366-1717b780-78b7-11ea-946c-ac85ce88ebac.png)

**Comment by milesxu** [comment] 2020-04-08 02:40
![DeepinScreenshot_select-area_20200408103435](https://user-images.githubusercontent.com/2003731/78738525-a8089480-7984-11ea-933e-bd00e02d2f2d.png)

I think the info surrounded by red rectangle is what you need. It's outputted when I close or open the terminal.

This is captured on a Linux client connected with a Linux server.

Sorry for the unreadable letters. If you can tell me how to set a font to show these letters, I will try again.

And I will capture another one on a Windows client again

**Comment by Tyriar** [comment] 2020-04-08 12:59
> Sorry for the unreadable letters. If you can tell me how to set a font to show these letters, I will try again.

Ok so the interesting part here is that `[A` part on the last line, that is your shell telling the terminal to move the cursor up, at which point it goes through the regular prompt (styles, erase current line and below, print prompt). I can't tell you _why_ it's happening but it's definitely your shell erasing the line as it's instructing the terminal to do so.

Something else we could check is to enable trace logging mode (F1, "log level"), then hide and show the terminal and then check the output channel "Log (Remote Extension Host)"

![image](https://user-images.githubusercontent.com/2193314/78786594-df177f80-795d-11ea-979a-e8b17ef080ba.png)

That will tell us what native calls are happening to the underlying pty. Looking for log messages containing `IPty#` like this:

```
[2020-04-08 05:56:45.612] [exthost] [trace] IPty#resize 203 26
```

**Comment by milesxu** [comment] 2020-04-08 13:20
![image](https://user-images.githubusercontent.com/2003731/78788488-78867600-79de-11ea-8aea-bca5debfed78.png)


Thanks a lot!

But if this is only the problem of my systems, why I have got this error on different clients?

And if this is the problem of my systems, could you please help me to find and solve this problem?

**Comment by Tyriar** [comment] 2020-04-08 14:27
@milesxu so this is what's logged from _only_ toggling visibility via ctrl+j? Is so, that's very likely the issue that it's getting resized to a very small size and then back up again:

![image](https://user-images.githubusercontent.com/2193314/78795831-52bf8980-796a-11ea-9412-70073c6bb603.png)

> But if this is only the problem of my systems, why I have got this error on different clients?

Pretty sure the issue is server side, not client.

**Comment by Tyriar** [comment] 2020-04-08 14:29
I can't reproduce here unfortunately though, toggle visibility always just resizes to the same size which shouldn't cause problems 🤔 

```
[2020-04-08 07:28:47.492] [exthost] [trace] IPty#resize 203 29
[2020-04-08 07:28:47.492] [exthost] [trace] IPty#resize 203 29
[2020-04-08 07:28:48.389] [exthost] [trace] IPty#resize 203 29
[2020-04-08 07:28:48.964] [exthost] [trace] IPty#resize 203 29
[2020-04-08 07:28:49.536] [exthost] [trace] IPty#resize 203 29
[2020-04-08 07:28:50.049] [exthost] [trace] IPty#resize 203 29
```

**Comment by milesxu** [comment] 2020-04-08 14:44
Yes, all your captured info is produced by vscode when I only use ctrl+j and ctrl+~.

So is there any other info can be traced by me to find the problem?

**Comment by Tyriar** [comment] 2020-04-08 19:25
@milesxu can you reproduce this on Linux locally? If so you could potentially debug it if you're up to it by checking when this gets called:

https://github.com/microsoft/vscode/blob/16a06751fe9da1a82c7791674e74db87ebd9dd10/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L247

**Comment by milesxu** [comment] 2020-04-09 03:17
@Tyriar I do no understand how to do.

Do you mean I should not use remote ssh, and debug vscode on a linux client?

Could you please tell me the detail steps?

**Comment by Tyriar** [comment] 2020-04-09 12:34
@milesxu if you can reproduce it in a regular local Linux window (not SSH) then you could debug by setting up the repo with these instructions https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

Don't feel obligated to do that of course. Additionally I have a feeling this is related to remote only as I've also had this reported for ssh as well here https://github.com/microsoft/vscode/issues/92258#issuecomment-610689047

**Comment by milesxu** [comment] 2020-04-11 14:34
It's a pity that I haven't got this error on local machines, neither Windows or Linux.

If I got it on Linux, I will try debugging it.

**Comment by finite-light** [comment] 2020-05-09 01:01
This issue appears to have been resolved in the new release.

**Comment by milesxu** [comment] 2020-05-09 06:16
I have some doubt about this.
It's true that I cannot find any text erased by prompt when I am using VS Code 1.45.
However, when I use tmux in a remote integrated terminal, each time when I reopen the terminal, there is a bright line flashing in it (but the contents in terminal are remained intact). 
Before VS Code 1.45, if I use tmux in a remote integrated terminal, reopen it would cause all the contents in tmux disappeared.

**Comment by finite-light** [comment] 2020-05-11 00:43
Yes, I also encountered this problem, the bright flashing line looks like the bottom status bar of tmux，anyway, there is not much inconvenience now for me :)

**Comment by karthikeyann** [comment] 2020-06-15 10:46
> This issue appears to have been resolved in the new release.

This issue appears in vs code insiders 1.47.0 with attached files inside in `${workspaceFolder}/.vscode/`

[settings.json.txt](https://github.com/microsoft/vscode/files/4779722/settings.json.txt)
[c_cpp_properties.json.txt](https://github.com/microsoft/vscode/files/4779723/c_cpp_properties.json.txt)
[launch.json.txt](https://github.com/microsoft/vscode/files/4779724/launch.json.txt)

If I remove these files and start fresh, this issue doesn't come.

**Closed** 2021-09-01 23:30 UTC
Labels: bug, terminal, *not-reproducible, remote
