### ISSUE TITLE
Support FileSystemProvider  with vscode cli

### ISSUE THREAD

**Issue by liximomo** [Microsoft/vscode#49731] opened 2018-05-12 02:03 UTC
I am working on an [extension](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs) that providing several file system schemes(sftp, ftp). It would be great that FileSystemProvider can  working through CLI:

```
code sftp://myhost/path/file_or_dir
```

**Comment by bpasero** [comment] 2018-05-14 07:40
Duplicate of https://github.com/Microsoft/vscode/issues/34770

**Closed by bpasero** 2018-05-14 07:40 UTC
Labels: remote
