### ISSUE TITLE
"A system error occurred (UNKNOWN: unknown error, stat [...])" when clicking on link to dvd drive

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59398] opened 2018-09-25 22:44 UTC
Testing #25600

**Repo**
1. On windows
1. With the dvd / cd drive configured as drive `D:`
1. In document, write a fake link to a file on `D:` such as: `file:///D:/v/D`
1. ctrl + click on link

**bug**
See a cryptic error message: `Unable to open 'D': A system error occurred (UNKNOWN: unknown error, stat 'd:\v\D').`

![screen shot 2018-09-25 at 3 43 20 pm](https://user-images.githubusercontent.com/12821956/46047361-bf04d000-c0d9-11e8-867f-88c6f7c50bfb.png)

We should show  a more friendly error message when `stat` fails

**Comment by bpasero** [comment] 2018-09-26 05:37
I am closing this as designed. Showing the raw error as it is emitted from node.js is what I want in this case because otherwise I would have a hard time to figure out what to look for. I do not think this is an issue that ever came up by a user and is like that since the beginning.

**Closed by bpasero** 2018-09-26 05:37 UTC
Labels: windows
