### ISSUE TITLE
Code Fold causes diagnostic/error appears at wrong location.

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/vscode#33786] opened 2017-09-04 10:25 UTC
- VSCode Version: 1.15.0
- OS Version: MacOSX/WIndows10

Steps to Reproduce:

1. Open a new TypeScript file. Enter 
```ts
var a = {
    test: unknwwn
}
```
The error correctly shows beneath variable `unknwwn`, says cannot find name.

<img width="448" alt="screen shot 2017-09-04 at 6 18 40 pm" src="https://user-images.githubusercontent.com/2883231/30022542-51567ca4-919e-11e7-8070-6c0d75678e32.png">

2. Collapse/fold the object literal, error occurs at the end of line. Change the variable name `a` to `adddd`, just adding some keys. Note, error is not located at the end of line.

<img width="415" alt="screen shot 2017-09-04 at 6 18 49 pm" src="https://user-images.githubusercontent.com/2883231/30022548-56c3988e-919e-11e7-80c5-3cd10b77cc31.png">

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-04-17 22:41
This has been fixed in the meantime via #36410
Also duplicate of #25350

**Closed by alexandrudima** 2018-04-17 22:41 UTC
Labels: bug
