### ISSUE TITLE
Spurious parse errors on JSON files

### ISSUE THREAD

**Issue by sequitur** [microsoft/vscode#120651] opened 2021-04-06 16:57 UTC
Issue Type: <b>Bug</b>

VSCode is showing dozens of parse errors as problems on innocuous JSON files in my project. Looks like the JSON language server is trying to parse partial or broken versions of the file and throwing those errors? This 21-line file shows 25 problems.

![err](https://user-images.githubusercontent.com/4242268/113749284-e17ef780-96df-11eb-9956-949556a912b3.png)

The file itself is definitely fine; I've experienced this problem with both package.json and tsconfig.json files that both npm and tsc can read just fine.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.29GB free)|
|Process Argv|--crash-reporter-id d1f01817-b065-4577-b067-4bc4bd487c26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ink|bru|1.3.1
powershell|ms-|2021.2.2
synthwave-vscode|Rob|0.1.8
tmlanguage|Tog|0.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by aeschli** [comment] 2021-04-07 13:04
Duplicate of https://github.com/Togusa09/vscode-tmlanguage/issues/24

You have to uninstall the tmlanguage extension.

**Closed by aeschli** 2021-04-07 13:04 UTC
