### ISSUE TITLE
File icon themes are not working (missing icons)

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#23567] opened 2017-03-29 13:21 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

I just updated to the latest insider build and I noticed that the file icon themes are not working, they are missing all of their icons. I've tried every theme I have installed. I've tried restarting VS Code a few times but the file icon theme icons do not show up. Here is a screenshot:

![file-icon-theme-not-working](https://cloud.githubusercontent.com/assets/190154/24456420/f517c034-1460-11e7-9d2f-d4502389f830.PNG)

**Comment by Equinox** [comment] 2017-03-29 13:28
Dupe of #23346.

**Closed** 2017-03-29 13:37 UTC

**Comment by frankhale** [comment] 2017-03-29 13:41
Sorry, I should have searched closed issues before I posted this.
