### ISSUE TITLE
Column selection with CJK character

### ISSUE THREAD

**Issue by ziofat** [Microsoft/vscode#9989] opened 2016-07-31 04:28 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10 64-bit

Steps to Reproduce:
1. Copy and paste the following Chinese, Japanese and English sentences to VS code.

```
人人生而自由，在尊严和权利上一律平等。
すべての人間は、生まれながらにして自由であり、かつ、尊厳と権利と について平等である。
All human beings are born free and equal in dignity and rights.
```

The sentences above are official translation of UDHR.
2. Use Shift + Alt + Click to select columns.

The behavior is:
![vscode](https://cloud.githubusercontent.com/assets/8521174/16713563/c33558c8-46ee-11e6-9c17-5a962782a5de.gif)

CJK characters are usually have double width than other characters. So visually the column of CJK characters and English characters are not same. When I use column selection to select CJK/English mixed codes this issue will affect the result.

The expected behavior is like what Sublime Text does:
![sublime](https://cloud.githubusercontent.com/assets/8521174/16713579/e4b0cce8-46ef-11e6-932e-df92c4453f4a.gif)

**Comment by Tyriar** [comment] 2016-08-01 17:48
I notice the CJK characters are also not aligned correctly. They should exactly as wide as 2 normal characters.

**Comment by ziofat** [comment] 2016-08-02 01:59
@Tyriar Actually they are. The Japanese line seems not aligned correctly is because the `、` symbol has weird width in VSCode. I checked and found this was my font settings issue and corrected it as Sublime Text. When using Yahei font, the `、` should be full width as general CJK characters.

And this is what it looks like:

![image](https://cloud.githubusercontent.com/assets/8521174/17314540/92909504-58a8-11e6-8977-27455d2dce8f.png)

**Comment by alexandrudima** [comment] 2016-08-02 12:56
The column selection is implemented with logical columns (not "screen columns") -- we definitely have similar issues for RTL text, for Bi-Di and for non-monospace fonts.

Implementing column selection with "screen columns" is IMHO difficult.

**Comment by ziofat** [comment] 2016-10-30 03:11
I think you don't need to think it as screen column, just make column selection smarter.
VSCode already treats the tab as 4-width length charcter (which can be set in preference), and CJK will be 2-width length in monospace font (it is not necessary to be available in preference because all monospace CJK font have same size.).
User can choose their font to suit the editor but not languages.

**Comment by alexandrudima** [comment] 2018-03-01 10:56
Duplicate of #22717

**Closed by alexandrudima** 2018-03-01 10:56 UTC
Labels: editor, feature-request
