### ISSUE TITLE
VSCode crashes when debugging code in Python Extension

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#69165] opened 2019-02-21 19:18 UTC
@Ronkiro commented on [Fri Feb 15 2019](https://github.com/Microsoft/vscode-python/issues/4417)

## Environment data
* VS Code version: 1.31.1
* Extension version (available under the Extensions sidebar): 2019.10
* OS and version: Windows 10 Enterprise, version 10.0.17134.590
* Python version (& distribution if applicable, e.g. Anaconda): Python 3.6
* Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

Normal use.

## Actual behaviour

Window suddenly crashes.

## Steps to reproduce:
1. Open VSCode with "code ."
2. Keep using

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
No info
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[Extension Host] debugger listening on port 24371
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger listening on ws://127.0.0.1:24371/4b397719-57f0-40fa-a574-1b549b523800
For help, see: https://nodejs.org/en/docs/inspector
log.ts:161  INFO no standard startup: not just one text editor
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger attached.
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger listening on ws://127.0.0.1:24371/4b397719-57f0-40fa-a574-1b549b523800
```

##Screenshots
[Error.png](http://oi67.tinypic.com/25p60di.jpg)
![25p60di](https://user-images.githubusercontent.com/1948812/52874957-ef402000-3107-11e9-9b81-62d7d8c0d408.jpg)

When clicking "Anular" it crashes the window.
[Crashed.png](http://oi63.tinypic.com/1zczpkn.jpg)
![1zczpkn](https://user-images.githubusercontent.com/1948812/52874970-f9621e80-3107-11e9-9cfe-b13e43000c81.jpg)

---

@ericsnowcurrently commented on [Wed Feb 20 2019](https://github.com/Microsoft/vscode-python/issues/4417#issuecomment-465697130)

Hi @Ronkiro, thanks for letting us know about this problem.

What version of VS Code are you using?  There's a good chance that this is an issue with VS Code rather than with the Python extension.

---

@Ronkiro commented on [Thu Feb 21 2019](https://github.com/Microsoft/vscode-python/issues/4417#issuecomment-466005605)

@ericsnowcurrently  Sorry, i really thought i wrote the versions info D:
(I updated the Issue with the info too)

Rewritting below:

## Environment data
* VS Code version: 1.31.1
* Extension version (available under the Extensions sidebar): 2019.10
* OS and version: Windows 10 Enterprise, version 10.0.17134.590
* Python version (& distribution if applicable, e.g. Anaconda): Python 3.6
* Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

**Comment by weinand** [comment] 2019-02-21 21:21
This does not seem to be debugger related.
But the dll mentioned in the error is winpty.
@Tyriar does this ring a bell?

**Comment by DonJayamanne** [comment] 2019-02-21 21:24
> But the dll mentioned in the error is winpty.

Yes, that was interesting, that's why I filed this issue up here.

**Comment by weinand** [comment] 2019-02-21 21:29
@DonJayamanne why does the title say "Debugger crashing VSCode". There is not a single mention of a debugger in the initial comment. The reproducible steps are just a meager "Keep using"...

**Comment by DonJayamanne** [comment] 2019-02-22 00:53
Apologies, updated the title.
@Ronkiro Please could you provide the necessary instructions to replicate this issue.

> The reproducible steps are just a meager "Keep using"...

I just copied the original issue from our repo (created by another user).

**Comment by Tyriar** [comment] 2019-02-22 13:04
There is a guard in place that prevents cols/rows to be <= 0 here:

https://github.com/Microsoft/node-pty/blob/1ce2e1e7be8e7395d17bfdc5c582069dbc39cba0/src/windowsTerminal.ts#L144-L147

This tells me that the expected terminal is not actually there, so this is likely a permissions problem or an anti-virus preventing winpty to launch a terminal. @Ronkiro are you on an enterprise system and/or do you have anti-virus software installed?

**Comment by Ronkiro** [comment] 2019-02-22 14:48
@DonJayamanne I really don't know how to reproduce. It simply crashed out of the blue while i were using it. Last time this occurred i wasn't even using the debugger, i were just coding.

@Tyriar Yes, i am on a enterprise system.  Windows 10 Enterprise, version 10.0.17134.590 to be more exact.
Also using an antivirus. A Kaspersky Endpoint Security version 11.0.1.90.

I have nearly same VSCode setup on my home (A W10 Home without antivirus) and never had the same issue at it. So makes sense (I don't use VSCode frequently there, though)

**Comment by Tyriar** [comment] 2019-02-22 17:56
Since this looks like some quirk with a winpty terminal being created and doesn't really look actionable to me, I'll close it off as a duplicate of https://github.com/Microsoft/vscode/issues/45693. The fix here is to wait for conpty support which is coming in Windows 1904

**Closed by Tyriar** 2019-02-22 17:56 UTC
Labels: integrated-terminal, needs more info
