### ISSUE TITLE
Layout control in the wrong place for RTL macOS

### ISSUE THREAD

**Issue by tom-programming** [microsoft/vscode#164397] opened 2022-10-23 20:00 UTC
Version of VS Code: 1.72.2

Your operating system: macOS 10.15.7

List of extensions that you have installed: none

**Reproducible steps (1... 2... 3...) that cause the issue:**

Set the OS language to Hebrew or Arabic. Then open VSCode

**What you expected to see, versus what you actually saw**

I expect to see the layout control buttons in the **left** side when the window is RTL, because in the right side there are the close/minimize/resize OS buttons.

Instead they are in the right side and the are basically impossible to click because they are covered with the window buttons.

See image:

<img width="86" alt="problem occuring" src="https://user-images.githubusercontent.com/29755050/197415426-a7e8995f-a14e-4b87-bf87-0534f1f3592f.png">

**Comment by rzhao271** [comment] 2022-10-26 18:37
Confirmed on macOS Monterey with the titlebar style set to "custom" and the system language set to Arabic.

**Comment by rzhao271** [comment] 2022-11-22 22:25
Related #161218

**Comment by rzhao271** [comment] 2022-11-23 15:49
Verification steps:
1. On macOS, switch the most preferred system language to a right-to-left language such as Arabic.
2. On VS Code Insiders, set the titlebar style to custom in the settings.
3. The traffic lights should still be on the left side.

**Comment by lramos15** [comment] 2022-12-01 19:04
@rzhao271 verified this, but isn't it expected that the traffic lights and WCO actually switch so that traffic lights are on the right and the WCO is on the left when using a RTL language?

**Comment by rzhao271** [comment] 2022-12-01 21:32
Reopening this issue because the current fix is even less usable, i.e. https://github.com/microsoft/vscode/issues/167543

**Comment by rzhao271** [comment] 2022-12-06 18:55
@sbatten and I looked into other programs on macOS, and it seems that all non-Electron-based programs have the traffic lights on the right side when the system language is Arabic. 

An invalid assumption I had was that because Windows set the location of the window controls overlay (WCO) depending on the _application language_, that macOS would do something similar. Instead, we should just move over the layout controls, as was originally asked.

Not a duplicate of https://github.com/microsoft/vscode/issues/161218

**Closed** 2023-02-11 00:34 UTC
Labels: bug, macos, titlebar, confirmed

**Comment by sbatten** [comment] 2023-02-17 23:51
Verification Steps:
1. On macOS, set your OS language to an RTL language such as Arabic.
2. Restart the machine
3. Start VS Code, traffic controls should be on the right side
4. Layout controls in the custom title bar should show to the left of the controls
