### ISSUE TITLE
Intellisense jumps to first item on the list after sometime

### ISSUE THREAD

**Issue by htmlHxcker** [microsoft/vscode#149146] opened 2022-05-10 09:47 UTC
Issue Type: <b>Bug</b>

1. Try to import a package or function (preferabbly stop after one letter has brought up Intellisense).
2. Use you arrow keys to go down the list and stop at any list item of your choice.
3. Wait for some time, around 30 seconds.
4. The cursor jumps back to the first item on the list.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by mjbvz** [comment] 2022-05-10 15:31
Which language is this for?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2022-05-23 23:21
Closing as caused by extension based on the last comment

**Closed by mjbvz** 2022-05-23 23:21 UTC
Labels: needs more info
