### ISSUE TITLE
can not start terminal

### ISSUE THREAD

**Issue by jdoc6** [microsoft/vscode#234487] opened 2024-11-23 21:41 UTC
Type: <b>Performance Issue</b>

I have a Max using an  Apple M1 chip . I downloaded VSC for Mac when I try to open a terminal I get this message:
the terminal process failed to launch: A native exception occurred during launch (posix_spawnp failed.)
I have tried everything I know to fix it, StackOverflow, GitHub but I can't get it to work.
Please Help

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id b00f2f32-d7dc-43e3-9037-221a411b6b76|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   213	  2348	code main
    0	    82	  2353	   gpu-process
    0	    33	  2354	   utility-network-service
    0	   147	  2394	shared-process
    0	     0	  8391	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  2406	ptyHost
    0	   344	  8256	window [3] (settings.json — NodeCourseVS)
    0	    66	  8272	fileWatcher [3]
    0	   131	  8273	extensionHost [3]
    0	    82	  8274	     /private/var/folders/j1/wq6djwqn3216dzc3w81t3z_r0000gn/T/AppTranslocation/8B351C06-4F82-4F94-9225-C993DC0670DD/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /private/var/folders/j1/wq6djwqn3216dzc3w81t3z_r0000gn/T/AppTranslocation/8B351C06-4F82-4F94-9225-C993DC0670DD/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=8273
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json — NodeCourseVS)
|    Folder (NodeCourseVS): 51 files
|      File types: js(13) json(12) hbs(4) txt(1) css(1) jpg(1)
|      Conf files: package.json(4) launch.json(1) settings.json(1)
|      Launch Configs: node-terminal(2);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by jdoc6** [comment] 2024-11-23 21:45
/

**Comment by meganrogge** [comment] 2024-11-24 15:41
Thoughts @deepak1556 ?

**Comment by meganrogge** [comment] 2024-12-08 16:24
closing as I cannot reproduce the issue

**Closed by meganrogge** 2024-12-08 16:24 UTC
