### ISSUE TITLE
Typescript syntax highlight not with class properties initialized as a nested object

### ISSUE THREAD

**Issue by JulioC** [Microsoft/vscode#20600] opened 2017-02-14 15:43 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.11.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.1.5|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.8.1|
|docthis|joelday|0.3.11|
|angular2|johnpapa|2.0.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|annotator|ryu1kn|0.10.1|
|code-settings-sync|Shan|2.4.3|
|spellchecker|swyphcosmo|1.2.9|
|ActionScript3|yopsolo|0.0.1|

---

Steps to Reproduce:

1. Create a Typescript with:

```typescript
class SomeClass {
  public nestedObject = {
    1: 'one',
    2: {
      text: 'two'
    },
    3: {
      text: 'two'
    },
  };

  constructor(private memberNumber: number) {
    doSomething();
  }

  public doSomething() {
  }
}
```

2. Syntax highlight gets messed up the `nestedObject` definition. Removing it, or leaving it with just `1: 'one'` fixes the syntax.

![](https://cloud.githubusercontent.com/assets/387794/22936065/82b7278a-f2bb-11e6-8948-bec189f93ac7.PNG)

**Comment by mjbvz** [comment] 2017-02-14 19:34
Thanks. I believe this is a duplicate of #20589

**Closed by mjbvz** 2017-02-14 19:34 UTC
Labels: duplicate, languages basic, typescript
