### ISSUE TITLE
Improper rendering of LaTeX inside markdown cells. 

### ISSUE THREAD

**Issue by SharonKartika** [microsoft/vscode#126625] opened 2021-06-12 16:20 UTC
## Environment data

-   VS Code version: 1.58.0-insider
-   Jupyter Extension version (available under the Extensions sidebar):  2021.7.928000153
-   Python Extension version (available under the Extensions sidebar): 2021.5.926500501
-   OS (Windows | Mac | Linux distro) and version: Ubuntu Linux 20.04
-   Python and/or Anaconda version: 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour
The following is expected when a latex equation is entered in a markdown cell. 

![image](https://user-images.githubusercontent.com/69861571/121782457-22efbf80-cbc7-11eb-9f90-d2804cf97532.png)

## Actual behaviour
In a markdown cell, enclosing an equation with '$$' produces the following output, instead of the expected LaTeX output. 

![image](https://user-images.githubusercontent.com/69861571/121782475-38fd8000-cbc7-11eb-9589-3a22a0eec5a2.png)

Sometimes the equations become difficult to read depending on their complexity. 

![image](https://user-images.githubusercontent.com/69861571/121782539-7c57ee80-cbc7-11eb-9d42-999f144f84d9.png)

## Steps to reproduce:

1. Create a markdown cell in VScode insiders, in a jupyter notebook.
2. Enter the following:
    ```
    $$
    \Gamma(a) = \int_0^{\infty} x^{a-1}e^{-x}dx
    $$
    ````
3. Run the cell

**Comment by mjbvz** [comment] 2021-08-04 04:47
Duplicate of #128490

**Closed by mjbvz** 2021-08-04 04:47 UTC
