### ISSUE TITLE
[Insiders] Broken Submodule Source Control view order

### ISSUE THREAD

**Issue by dchennaraidu** [microsoft/vscode#145886] opened 2022-03-23 13:18 UTC
Issue Type: <b>Bug</b>

1) Create a repo with name B
2) Create another repo with name A (Any repo name lexically smaller than first repo)
3) Add second repo (A) as submodule in B repo

Actual: In Source Control Side bar repo A is shown at the top

Desired: Repo B should be at the top followed by repo A

VS Code version: Code - Insiders 1.66.0-insider (2eebd2a0159af379057a58c8bcb519f95bfd6328, 2022-03-23T05:27:08.615Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 31040e07-41d1-42ee-ad16-eae0b78a5016|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.18.0
npm-intellisense|chr|1.4.1
vscode-sql-beautify|cla|0.3.5
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
copilot|Git|1.9.5350
vscode-pull-request-github|Git|0.38.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-oracle-format|mp|0.1.5
csharp|ms-|1.24.1
vscode-postgresql|ms-|0.3.0
azure-account|ms-|0.10.1
test-adapter-converter|ms-|0.1.5
polacode|pnp|0.3.4
vscode-xml|red|0.19.1
synthwave-vscode|Rob|0.1.11
markdown-preview-enhanced|shd|0.6.2

(1 theme extensions excluded)

</details>

**Comment by dchennaraidu** [comment] 2022-03-26 02:44
Kindly observe the repositories order

1.65.2: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
<img width="839" alt="image" src="https://user-images.githubusercontent.com/12108102/160221751-e28faab8-726a-4d40-b770-7ca195ac9213.png">

1.66.0-insider: c63ed49b4b164210301f4f8a09079aa4de53b870
<img width="919" alt="image" src="https://user-images.githubusercontent.com/12108102/160221788-93d44d9a-7ce4-4b9c-acd5-797e037a0b85.png">

Change Log: https://github.com/microsoft/vscode/compare/c63ed49b4b164210301f4f8a09079aa4de53b870...c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1

**Comment by dchennaraidu** [comment] 2022-03-26 02:56
Seems because of this change https://github.com/microsoft/vscode/pull/145264

**Comment by lszomoru** [comment] 2022-03-30 14:25
@dchennaraidu, we did indeed recently adjusted the order in which source control repositories are being displayed in the "Source Control Repositories" and "Source Control" views. To give you a little context, historically repositories were being showing in the order in which they were discovered. This worked well for folders/workspaces with a small number of repositories, but it certainly looked random (as discovery order can vary) for folders/workspaces with a large number of repositories and it was a real pain point.

We are considering providing more control over sorting the list of repositories other than by their name.

**Comment by lszomoru** [comment] 2022-03-31 07:58
Closing this issue as duplicate of https://github.com/microsoft/vscode/issues/146359

**Closed by lszomoru** 2022-03-31 07:58 UTC
Labels: feature-request, scm
