### ISSUE TITLE
Plugins stuck on installing for ever !!!

### ISSUE THREAD

**Issue by 8lbiasian** [Microsoft/vscode#28447] opened 2017-06-11 06:21 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. search for any plugin for example vscode-icons 
2. click install
3. its tell its installing and stuck on this stage =( 
no reaction no error nothing !! 

btw in macOs its working fine with me  last night but i try it today in windows but ...

**Comment by joaomoreno** [comment] 2017-06-14 08:55
Are you behind a proxy?

Can you send me your `~/.vscode/extensions` folder?

**Comment by 8lbiasian** [comment] 2017-06-14 08:58
@joaomoreno  no i dont use proxy

the folder is empty  !!

**Comment by joaomoreno** [comment] 2017-06-14 09:49
Can you open the Developer Tools? Any error/warning there?

**Comment by 8lbiasian** [comment] 2017-06-14 11:37
@joaomoreno nothing, empty and problem tab says there is no problem, output tab is empty 

and still when i click install its just stuck on the word installing

**Comment by joaomoreno** [comment] 2017-11-23 14:53
@8lbiasian Is this still an issue?

**Comment by 8lbiasian** [comment] 2017-11-24 11:27
@joaomoreno actually i delete the application from that time because the issue didn't solve, i try different PC with win 10 and same issue so i consider app working fine in Mac only i use for windows i choose another app to work with, but will try again for testing if it get solved or no. 

thanks for following.

**Comment by joaomoreno** [comment] 2017-11-24 17:37
Thanks, let me know what came out of it.

**Comment by 8lbiasian** [comment] 2017-12-09 12:18
sorry for the delay 
i try to uninstall previous version and install a fresh version with full delete or settings and register and every thing 

but again i still have same issue 

if i hit the Install button to any plugin its just show the word " Installing " and stuck on it never finish never show an error nothing 

i dono how to give more details on this 

this issue only happen on my Windows 10 

MacOS Elcapitan or Serria are work perfectly *-*

**Comment by joaomoreno** [comment] 2017-12-11 08:28
Can you send me your `~/.vscode/extensions` folder?

**Comment by 8lbiasian** [comment] 2017-12-11 09:55
@joaomoreno  in windows ? 

this folder is empty 

C:\Users\Eng Ahmed\.vscode\extensions 

nothing inside !!

**Comment by joaomoreno** [comment] 2017-12-11 13:48
@sandy081 Any thoughts?

**Comment by sandy081** [comment] 2017-12-11 17:26
@joaomoreno Not exactly.

One idea would be, I will add logging and ask user to reproduce it and check the logs with the new insiders version.

**Comment by 8lbiasian** [comment] 2017-12-11 18:32
@sandy081 yes actually i try to find a log but not found

**Comment by sandy081** [comment] 2017-12-12 08:10
@8lbiasian There are no logs yet. I pushed changes to log yesterday. Will let you know once it is available.

**Comment by sandy081** [comment] 2017-12-19 09:15
@8lbiasian Can you please try installing latest insiders [here](https://code.visualstudio.com/insiders/) and start code-insiders in trace mode `code-insiders --log=trace`. In VS Code, try installing and check the activity in output panel by opening the shared process log.

**Comment by 8lbiasian** [comment] 2017-12-19 15:52
@sandy081 thanks 

this is what happen 

```
[2017-12-19 19:35:38.890] [sharedprocess] [info] main {"machineId":"edd07cd94e2f53fff965e3e2e755624211ffd17e56ae617ec7aab585607317f3"}
[2017-12-19 19:35:38.901] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:35:38.902] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:35:39.027] [sharedprocess] [trace] Started scanning system extensions
[2017-12-19 19:35:39.027] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:35:39.028] [sharedprocess] [trace] Started scanning system extensions
[2017-12-19 19:35:39.028] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:35:39.028] [sharedprocess] [trace] Started scanning system extensions
[2017-12-19 19:35:39.028] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:35:39.028] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:35:39.033] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:35:39.045] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:35:39.060] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:35:39.071] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:35:39.154] [sharedprocess] [info] Scanned system extensions: 64
[2017-12-19 19:35:39.161] [sharedprocess] [info] Scanned system extensions: 64
[2017-12-19 19:35:39.164] [sharedprocess] [info] Scanned system extensions: 64
[2017-12-19 19:36:07.792] [sharedprocess] [trace] Started scanning system extensions
[2017-12-19 19:36:07.792] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:36:07.792] [sharedprocess] [trace] Started scanning system extensions
[2017-12-19 19:36:07.792] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:36:07.793] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:36:07.801] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:36:07.812] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:36:07.813] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:36:07.866] [sharedprocess] [info] Scanned system extensions: 64
[2017-12-19 19:36:07.875] [sharedprocess] [info] Scanned system extensions: 64
[2017-12-19 19:36:11.773] [sharedprocess] [info] Installing extension: vscode-icons
[2017-12-19 19:36:11.774] [sharedprocess] [trace] Started downloading extension: vscode-icons
[2017-12-19 19:37:20.188] [sharedprocess] [trace] Started scanning user extensions
[2017-12-19 19:37:20.189] [sharedprocess] [info] Scanned user extensions: 0
[2017-12-19 19:40:32.064] [sharedprocess] [info] Installing extension: vscode-eslint
[2017-12-19 19:40:32.064] [sharedprocess] [trace] Started downloading extension: vscode-eslint

```

i click on install the vscode icons but nothing happen i try to install the eslint also same thing as u can see

i switch also the log to window 

and its show this


```
[2017-12-19 19:35:37.135] [renderer1] [trace] openWorkbench configuration {"_":[],"log":"trace","appRoot":"c:\\Program Files\\Microsoft VS Code Insiders\\resources\\app","machineId":"edd07cd94e2f53fff965e3e2e755624211ffd17e56ae617ec7aab585607317f3","execPath":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\2d3c5e9bfed7243c2dbc20494b492904-1.20.0-insider-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\Eng Ahmed\\AppData\\Roaming\\Code - Insiders\\logs\\20171219T193535"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\Eng Ahmed\\AppData\\Roaming\\Code - Insiders\\CachedData\\2e55941ce82de979a1393dfce60c66b34401ff23","backupPath":"C:\\Users\\Eng Ahmed\\AppData\\Roaming\\Code - Insiders\\Backups\\1513697520619","windowId":1,"baseTheme":"vs-dark","backgroundColor":"#1e1e1e","perfEntries":["mark","main:started",1513697735388,0,"mark","main:appReady",1513697735456,0,"mark","main:loadWindow",1513697735839,0],"perfStartTime":1513697735388,"perfWindowLoadTime":1513697735839}
[2017-12-19 19:35:44.084] [renderer1] [error] Git model not found
[2017-12-19 19:36:07.963] [renderer1] [error] ENOENT: no such file or directory, mkdir 'C:\Users\Eng Ahmed\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Eng Ahmed\AppData\Local\Temp;C:': Error: ENOENT: no such file or directory, mkdir 'C:\Users\Eng Ahmed\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Eng Ahmed\AppData\Local\Temp;C:'
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:89:878)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-12-19 19:37:19.866] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalSettings
[2017-12-19 19:38:27.171] [renderer1] [trace] CommandService#executeCommand workbench.actions.view.problems
[2017-12-19 19:39:04.745] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2017-12-19 19:39:12.672] [renderer1] [trace] CommandService#executeCommand workbench.action.showLogs
[2017-12-19 19:41:16.831] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardCopyAction
[2017-12-19 19:41:22.391] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2017-12-19 19:41:30.761] [renderer1] [trace] CommandService#executeCommand workbench.action.showLogs
[2017-12-19 19:42:33.595] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardCopyAction

```

i dono if its related to an issue of folder permision or its require some application for downloading @@ 

is it need git ? cuz i got this error msg 

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Users\Eng Ahmed\AppData\Local\Programs\Git\cmd\git.exe
Git installation not found.

```

**Comment by 8lbiasian** [comment] 2017-12-23 04:12
@sandy081 any update ?!

**Comment by sandy081** [comment] 2018-01-08 10:14
@8lbiasian Thanks for the logs and it looks like downloading the extension from the market place is not finishing. May be there is an error while downloading. Do you see any error message?

I do not think `git` has anything to do with this. It is not related. 

Another interesting entry in the log is 

> ENOENT: no such file or directory, mkdir 'C:\Users\Eng Ahmed\AppData\Local\Temp;C:'

Looks like you do not have Temp directory, where we download the VSIX from market place. 

@joaomoreno Any insights?

**Comment by joaomoreno** [comment] 2018-01-08 11:02
@8lbiasian What is the value of the `%TEMP%` environment variable in your system?

**Comment by 8lbiasian** [comment] 2018-01-09 04:45
@sandy081  no error msg or anything coming 

@joaomoreno  this is the path 

     C:\Users\Eng Ahmed\AppData\Local\Temp

**Comment by 8lbiasian** [comment] 2018-01-09 04:48
@joaomoreno @sandy081 
i just take screenshot also from my env. var. window and showing the Temp 

![image](https://user-images.githubusercontent.com/2717113/34705426-dc733c9e-f519-11e7-81a1-bff99c655186.png)

**Comment by 8lbiasian** [comment] 2018-01-09 04:57
actually i try to delete the second entry in my env. 

and this is the log 


 [2018-01-09 08:41:56.305] [sharedprocess] [info] main {"machineId":"edd07cd94e2f53fff965e3e2e755624211ffd17e56ae617ec7aab585607317f3"}
[2018-01-09 08:41:56.341] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:41:58.697] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:41:58.698] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:42:00.155] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:42:00.157] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:42:12.028] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:42:12.075] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:42:12.076] [sharedprocess] [info] Scanned user extensions: 0
[2018-01-09 08:42:12.129] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:42:12.133] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:42:20.036] [sharedprocess] [info] Installing extension: vscode-icons
[2018-01-09 08:43:23.062] [sharedprocess] [info] Installing extension: Material-theme
[2018-01-09 08:43:24.251] [sharedprocess] [info] Downloaded extension: Material-theme
[2018-01-09 08:43:24.283] [sharedprocess] [info] Extracted extension to C:\Users\Eng Ahmed\.vscode-insiders\extensions\zhuangtongfa.material-theme-2.11.1: zhuangtongfa.material-theme-2.11.1
[2018-01-09 08:43:24.312] [sharedprocess] [info] Updated metadata of the extension: zhuangtongfa.material-theme-2.11.1
[2018-01-09 08:43:24.312] [sharedprocess] [info] Extensions installed successfully: zhuangtongfa.material-theme
[2018-01-09 08:43:24.448] [sharedprocess] [info] Scanned user extensions: 1
[2018-01-09 08:43:24.475] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:45:28.439] [sharedprocess] [info] Installing extension: vscode-eslint
[2018-01-09 08:45:28.514] [sharedprocess] [info] Downloaded extension: vscode-eslint
[2018-01-09 08:45:28.906] [sharedprocess] [info] Extracted extension to C:\Users\Eng Ahmed\.vscode-insiders\extensions\dbaeumer.vscode-eslint-1.4.3: dbaeumer.vscode-eslint-1.4.3
[2018-01-09 08:45:28.954] [sharedprocess] [info] Updated metadata of the extension: dbaeumer.vscode-eslint-1.4.3
[2018-01-09 08:45:28.954] [sharedprocess] [info] Extensions installed successfully: dbaeumer.vscode-eslint
[2018-01-09 08:45:29.082] [sharedprocess] [info] Scanned user extensions: 2
[2018-01-09 08:45:29.089] [sharedprocess] [info] Scanned user extensions: 2
[2018-01-09 08:45:29.133] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:45:29.139] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:45:41.102] [sharedprocess] [info] Installing extension: python
[2018-01-09 08:45:43.040] [sharedprocess] [info] Downloaded extension: python
[2018-01-09 08:45:59.062] [sharedprocess] [info] Extracted extension to C:\Users\Eng Ahmed\.vscode-insiders\extensions\ms-python.python-0.9.1: ms-python.python-0.9.1
[2018-01-09 08:45:59.344] [sharedprocess] [info] Updated metadata of the extension: ms-python.python-0.9.1
[2018-01-09 08:45:59.345] [sharedprocess] [info] Extensions installed successfully: ms-python.python
[2018-01-09 08:45:59.478] [sharedprocess] [info] Scanned user extensions: 3
[2018-01-09 08:45:59.486] [sharedprocess] [info] Scanned user extensions: 3
[2018-01-09 08:45:59.517] [sharedprocess] [info] Scanned system extensions: 64
[2018-01-09 08:45:59.523] [sharedprocess] [info] Scanned system extensions: 64


and its seems that its working now !!!! 

i think in vcode should not read the full value of TEMP !! 

'C:\Users\Eng Ahmed\AppData\Local\Temp;C:'

as u can see its read the ;C: which should be ignored 

i hope my issue give u an idea for a next update and improvement ^^

**Comment by sandy081** [comment] 2018-01-09 14:21
Thanks @8lbiasian 

@joaomoreno Is it a bug from our side that TEMP directory is not read properly? Otherwise we can close this issue.

**Comment by joaomoreno** [comment] 2018-01-09 16:16
@8lbiasian TEMP should always be a single directory, never a collection of directories. The problem was that in your system some process set it up as a list of directories using `;` as a delimiter. This is not supported in the TEMP variable, only in others e.g. PATH.

**Closed by joaomoreno** 2018-01-09 16:16 UTC
Labels: needs more info
