### ISSUE TITLE
how to go to definition with react className attribute

### ISSUE THREAD

**Issue by whisperfairy** [Microsoft/vscode#25686] opened 2017-04-30 03:39 UTC
- VSCode Version: 1.11.2
- OS Version:macos 10.12.1

how to locate to scss file when I use go to definition with className in *.jsx or *.tsx file
  `render() {
        return (
            <div className="app" >
            </div>  
        )
    }`

**Comment by aeschli** [comment] 2017-05-02 09:34
This is not supported out-of-the box. But https://github.com/Zignd/HTML-CSS-Class-Completion tries to solve that.

**Comment by mjbvz** [comment] 2017-08-22 23:10
Duplicate of #15568

**Closed by mjbvz** 2017-08-22 23:10 UTC
Labels: css-less-sass, duplicate, feature-request, typescript

**Comment by jasminecjc** [comment] 2017-09-21 04:05
Does this issue have a solution so far?

**Comment by mjbvz** [comment] 2017-09-22 19:53
@jasminecjc  No but we are tracking it with #15568

There also also some extensions that may provide this functionality
