### ISSUE TITLE
Can only stage files from command-line

### ISSUE THREAD

**Issue by cramse22** [microsoft/vscode#103492] opened 2020-07-28 14:48 UTC
Issue Type: <b>Bug</b>

open repo synced with GitHub, modify a file, click + next to file to stage.

Error will be generated that file is outside of the repository.

Workaround: use git add from command-line

The stage function in the VSCode interface is not working properly and it is only possible to stage a file or files from the command-link using the git add command such as:

git add -v -- .\changes

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:31:37.228Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz (2 x 3292)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (5.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
solargraph|cas|0.21.1
chef|che|1.7.0
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.36.1
vscode-yaml-validation|dja|0.0.1
gc-excelviewer|Gra|3.0.39
MagicPython|mag|1.1.0
python|ms-|2020.7.96456
powershell|ms-|2020.6.0
ruby|reb|0.27.0
vscode-yaml|red|0.9.1
MDTools|sea|1.0.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8
vscode-ruby|win|0.27.0

</details>

**Comment by IllusionMH** [comment] 2020-07-28 16:13
/needsMoreInfo

Looks like duplicate of #99881

What version of Git do you have installed?

**Comment by cramse22** [comment] 2020-07-28 16:18
Yes, it is in reference to the same issue.
I am using git version 2.12.0.windows.1

Regards,
CJ

CJ Ramseyer
Directory Services Engineering
ITO Foundational Services - Security Service

**Comment by cramse22** [comment] 2020-07-28 16:30
What I have Installed:

Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:31:37.228Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.14393


VSCode Installation where GUI Staging of files is still working (see attached):
Git version: git version 2.8.2.windows.1

Regards,
CJ


CJ Ramseyer
Directory Services Engineering
ITO Foundational Services - Security Service

**Comment by joaomoreno** [comment] 2020-07-30 08:31
Can you update to Git 2.27?

**Comment by cramse22** [comment] 2020-07-30 11:33
I can do that.  Can you share the proper update command for the version I have?
I tried to find the proper method for the version I have, but was not successful.

CJ Ramseyer
Directory Services Engineering
ITO Foundational Services - Security Service

**Comment by joaomoreno** [comment] 2020-07-30 12:14
I don't think there is a command to update it. You have to manually download and install Git from https://git-scm.com/

**Closed** 2020-08-07 11:23 UTC
Labels: needs more info
