### ISSUE TITLE
Sublime text like autocompletion

### ISSUE THREAD

**Issue by horvathgyozo** [Microsoft/vscode#36968] opened 2017-10-26 09:19 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 10

Is there any way to insert suggestion without opening the suggestion widget. What I want is similar how Sublime Text works. During typing if I press TAB it automatically completes the word based on the words in the current text. Pressing TAB again and again it cyclically completes it, so it goes through the available suggestions without opening the widget.
For example: I have a text "ally automatically", and for the next word I write "aly", then pressing TAB will autocomplete it to "ally", and pressing again TAB completes "automatically", again TAB --> "ally", and so on...
Is there any way to achieve this mechanism in VSCode?

**Comment by jrieken** [comment] 2017-10-27 08:08
dupe of #28215

**Closed** 2017-10-27 08:08 UTC
Labels: duplicate, editor, editor-core

**Comment by horvathgyozo** [comment] 2017-10-27 10:55
So, the answer, that right now it is not possible to autocomplete and cycle through the suggestions without opening the suggestion widget.
The referenced duplicate is different in a way that I do not want to open the popup/widget to include word based suggestions.
