### ISSUE TITLE
Type definitions in the arrow functions of the TypeScript are not highlighted

### ISSUE THREAD

**Issue by EagleEYErus** [Microsoft/vscode#43447] opened 2018-02-11 22:00 UTC
### Issue Type
Bug

### Description

If you use a regular function, then the syntax is highlighted normally, and if it is a pointer, then the type definitions are not highlighted in green.
I mean the code from 27 to 32 line

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
material-icon-theme|PKi|3.2.2
vscode-eslint|dba|1.4.5
prettier-vscode|esb|1.1.3
bem-expand|luk|0.1.4
code-beautifier|mic|1.7.2
dotenv|mik|1.0.0
HTMLHint|mka|0.4.0
vscode-pugbeautify|mrm|1.0.2
cpptools|ms-|0.14.6
node-debug2|ms-|1.19.3
sass-indented|rob|1.4.6
gi|rub|0.2.11
es6-mocha-snippets|spo|0.0.5
language-stylus|sys|1.8.0
vscode-react-native|vsm|0.5.7

(1 theme extensions excluded)

</details>
Reproduces only with extensions

![2018-02-12 0 49 43](https://user-images.githubusercontent.com/15634499/36079056-f8cac6a6-0f8f-11e8-9480-29c2c15bfb78.png)
![2018-02-12 0 49 29](https://user-images.githubusercontent.com/15634499/36079057-f8e61da2-0f8f-11e8-8b5e-e7559225b518.png)

**Comment by mjbvz** [comment] 2018-02-13 02:10
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/540

This is a known limitation of how our typescript textmate grammar works

**Closed by mjbvz** 2018-02-13 02:10 UTC

**Comment by sheetalkamat** [comment] 2018-03-06 23:20
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552
