### ISSUE TITLE
Fresh Windows 11 and fresh vscode. Error while turning on Settings Sync. No authentication providers are available.

### ISSUE THREAD

**Issue by vitorlfaria** [microsoft/vscode#232541] opened 2024-10-29 23:38 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0
- OS Version: Windows 11 Home

Steps to Reproduce:

1. New fresh installation of windows.
2. Install vscode.
3. Press backup and sync settings button.

Output pane:
- Settings Sync log:
2024-10-29 19:18:25.158 [info] Using settings sync service https://vscode-sync.trafficmanager.net/
2024-10-29 19:18:25.158 [info] Auto Sync is disabled.

- Github Aithentication log:
2024-10-29 19:18:37.368 [info] Reading sessions from keychain...
2024-10-29 19:18:37.368 [info] Getting sessions for all scopes...
2024-10-29 19:18:37.368 [info] Got 0 sessions for ...
2024-10-29 19:18:37.368 [info] Getting sessions for all scopes...
2024-10-29 19:18:37.368 [info] Got 0 sessions for ...
2024-10-29 19:18:37.368 [info] Getting sessions for all scopes...
2024-10-29 19:18:37.368 [info] Got 0 sessions for ...
2024-10-29 19:18:37.369 [info] Getting sessions for user:email...
2024-10-29 19:18:37.369 [info] Got 0 sessions for user:email...
2024-10-29 19:18:38.498 [info] Logging in with 'any' account...
2024-10-29 19:18:38.498 [info] Logging in for the following scopes: user:email
2024-10-29 19:18:38.502 [info] Trying without local server... (user:email)
2024-10-29 19:18:41.632 [info] Exchanging code for token...
2024-10-29 19:18:41.957 [info] Token exchange success!
2024-10-29 19:18:41.958 [info] Getting user info...
2024-10-29 19:18:42.310 [info] Got account info!
2024-10-29 19:18:42.312 [info] Storing 1 sessions...
2024-10-29 19:18:42.315 [info] Reading sessions from keychain...
2024-10-29 19:18:42.316 [info] Stored 1 sessions!
2024-10-29 19:18:42.316 [info] Login success!
2024-10-29 19:18:42.322 [info] Got stored sessions!
2024-10-29 19:18:42.322 [info] Got 1 verified sessions.
2024-10-29 20:28:47.020 [info] Getting sessions for all scopes...
2024-10-29 20:28:47.020 [info] Got 1 sessions for ...

- Microsoft Authentication log:
2024-10-29 19:18:37.312 [info] Getting sessions for all scopes...
2024-10-29 19:18:37.312 [info] Got 0 sessions for all scopes...
2024-10-29 19:18:37.313 [info] Getting sessions for all scopes...
2024-10-29 19:18:37.313 [info] Got 0 sessions for all scopes...
2024-10-29 19:18:37.314 [info]  for undefined
2024-10-29 19:18:37.314 [info] [email offline_access openid profile] Got 0 sessions

- Window log:
2024-10-29 19:18:24.531 [info] Started local extension host with pid 7136.
2024-10-29 19:18:27.826 [info] [perf] Render performance baseline is 27ms
2024-10-29 19:19:05.787 [warning] Settings pattern "application.*" doesn't match any settings
2024-10-29 19:19:19.223 [warning] Settings pattern "application.*" doesn't match any settings
2024-10-29 20:23:36.012 [warning] Settings pattern "application.*" doesn't match any settings
2024-10-29 20:28:47.062 [error] [uncaught exception in main]: Titlebar overlay is not enabled: Error: Titlebar overlay is not enabled
    at bu.updateWindowControls (file:///C:/Users/vitor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:71:49285)
    at bu.n (file:///C:/Users/vitor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:71:47098)
    at bu.Q (file:///C:/Users/vitor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:8705)
    at bu.tryClaimWindow (file:///C:/Users/vitor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:8475)
    at App.<anonymous> (file:///C:/Users/vitor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:9718)
    at App.emit (node:events:519:28)
    at n._init (node:electron/js2c/browser_init:2:12818)
    at openGuestWindow (node:electron/js2c/browser_init:2:101599)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89067)
    at WebContents.emit (node:events:519:28)
2024-10-29 20:30:56.527 [error] [network] #19: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled

**Comment by vitorlfaria** [comment] 2024-10-30 02:02
I don't know what caused this, but I left the vscode open for a few hours without touching it and now it worked.

@sandy081 what can I do with this issue? May I close it since its working now?

**Comment by codercodingthecode** [comment] 2024-10-30 07:34
Its most definitely a bug, I just installed vscode on a fresh windows installation and the same thing happened to me.
I still can't make it work though.

**Comment by vitorlfaria** [comment] 2024-10-30 10:20
@codercodingthecode Try this: In accounts (bottom left corner person icon) click `turn on cloud changes`, it'll ask you to login (I use github login). Restart your machine, open vscode and try to sync, it didn't work for me yet. Now don't close vscode, just wait at least 2 hours and try again. That was what miraculously worked for me.

**Comment by sandy081** [comment] 2024-10-31 14:33
/duplicate

This seems to be a duplicate of https://github.com/microsoft/vscode/issues/232516 - If some can reproduce it consistently please let me know

**Closed** 2024-10-31 14:33 UTC
Labels: *duplicate, new release
