### ISSUE TITLE
ZSH Terminal Bug in VS Code

### ISSUE THREAD

**Issue by KoltonG** [Microsoft/vscode#28656] opened 2017-06-13 19:44 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.9|
|vscode-wakatime|WakaTime|1.1.10|
|vscode-theme-onedark|akamud|2.0.2|
|vscode-eslint|dbaeumer|1.2.11|
|sass-lint|glen-84|0.0.4|
|name-that-color|guillaumedoutriaux|0.1.2|
|mssql|ms-mssql|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.3|
|color-highlight|naumovs|2.2.0|
|vscode-todo-highlight|wayou|0.5.5|;

---

Steps to Reproduce:

1. Open the terminal in VS Code

### Screenshot
This is what I see when opening up the terminal. It is showing the directory twice. This happened after the update today and it worked fine before. Please let me know if you require more information.
![screen shot 2017-06-13 at 4 37 36 pm](https://user-images.githubusercontent.com/3606121/27101123-d1e198d8-5056-11e7-88e0-629db50f1127.png)

**Comment by blitzd** [comment] 2017-06-13 19:58
Same issue, and it jumps to only showing it once when you're typing - but then back to twice when you stop.

**Comment by CherryDT** [comment] 2017-06-13 20:30
Yet another duplicate of #26038
The fix will be out soon, it's already done.

**Comment by ramya-rao-a** [comment] 2017-06-13 22:15
Thanks @CherryDT 

Yup, yet another duplicate of #26038
cc @Tyriar

**Closed by ramya-rao-a** 2017-06-13 22:15 UTC
