### ISSUE TITLE
Unable to install extensions behind firewall, no error message in UI

### ISSUE THREAD

**Issue by onybo** [Microsoft/vscode#11667] opened 2016-09-08 06:58 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
1. Ctrl-Shift-X to open Extensions
2. Select "Show recommended extensions" or "Show Popular Extensions"

For a time it will show a blue indicator going from left to right, over and over for some time. Then nothing.
No error message. No nothing

Expected result:
When selecting "Show Popular Extensions" a list of one or more extensions should be displayed.

I am behind a corporate firewall.
I have added the following to my user settings (in my actual setting w.x.y.z is my proxy ip address):

```
// The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
"http.proxy": "w.x.y.z:8080",
```

  "https.proxy": "http://w.x.y.z:8080",
    // Whether the proxy server certificate should be verified against the list of supplied CAs.
    "http.proxyStrictSSL": false

The same settings works in regular node environments. E.g. npm. Using the above settings I can use npm just fine.

I note that there is a an error message in the console in Developer Tools:
shell.ts:422 connect ETIMEDOUT 191.238.172.191:443

This ip address seems to be a Microsoft address, I am guessing it is the address of the marketplace?
Is it ignoring my settings in the user settings file?

**Comment by ywmail** [comment] 2016-09-09 03:28
When I use cntlm to translate the NTLM proxy to a none encrypted proxy, I alse get a problem in 1.5.1. When start the code, it promote `unable to verify the first certificate`.

**Comment by joaomoreno** [comment] 2016-09-09 07:46
@onybo Make sure you restart Code after changing the proxy settings.

**Comment by camilobg** [comment] 2017-02-15 12:46
Another one...
I think this error is relationed with firewall politics.

In corporate web the download always presents this error.
However at my home this error don't appear

My vscode version is 1.9.1

![vscode_error_download_extensions](https://cloud.githubusercontent.com/assets/25792561/22974907/ab5c392c-f36b-11e6-9f53-9a32b0a57e5e.png)

**Comment by joaomoreno** [comment] 2017-04-26 08:24
Closing as dupe of proxy issues.

**Closed by joaomoreno** 2017-04-26 08:24 UTC
Labels: needs more info
