### ISSUE TITLE
Support extensions hosted by a mirror

### ISSUE THREAD

**Issue by gatesn** [Microsoft/vscode#30090] opened 2017-07-04 13:18 UTC
It would be really useful to be able to add more extension repositories besides the marketplace. The use-case for this is either mirroring extensions, or for internal extensions that cannot be published publicly. 

The second part of this, would be to support *.vsix URLs in the `extensions.recommendations` configuration block.

**Comment by dbussanichpro** [comment] 2017-07-14 15:19
Our enterprise is behind a proxy that prevents us from accessing the marketplace. This is an important feature to us.

**Comment by cniweb** [comment] 2018-04-09 06:51
Our company is also behind a proxy that blocks our access to the marketplace.
In addition, a proxy authentication is required, which requires a password entry in the configuration. This would be a security violation.
The ability to target the Marketplace through an internally hosted mirror (such as Sonatype Nexus or JFrog Artefactory) is also an important feature for us.

**Comment by fredbcode** [comment] 2018-08-30 09:12
I completely agree, local mirror is a very useful feature

**Comment by mjbvz** [comment] 2019-05-01 23:34
Duplicate of #21839

**Closed by mjbvz** 2019-05-01 23:34 UTC
Labels: extensions, feature-request
