### ISSUE TITLE
Global search contains previous search

### ISSUE THREAD

**Issue by pim-pesochek** [microsoft/vscode#119860] opened 2021-03-25 09:25 UTC
Steps to reproduce
0. Explorer panel is visible, search panel is hidden
1. Select some text for searching
2. Press Shift+Cmd+F to open search panel
3. Search panel becomes visible
Actual behavior:
    Search textbox contains previous searched text
Expected behavior:
    Search textbox is updated with text selected in step 1

Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by JacksonKearl** [comment] 2021-03-25 17:27
Do you have any custom keybindings related to search? When I try this with an clean install I see the desired behavior: 
![Uploading recording (4).gif…]()

**Comment by gjsjohnmurray** [comment] 2021-03-25 18:01
Perhaps worth noting that if you have interacted with the first set of search results and dismissed some of them, then when you prime the search field again with different selection from an editor the new search won't actually run until you press Enter. I think this is by design, to avoid accidental loss of a laboriously-curated set of search results.

**Comment by fabb** [comment] 2021-04-01 08:00
i have the same issue as the OP. i use the IntelliJ Keymap but apart from that i don't have custom key mappings.
Note that when the search panel is already open and i select some text in the editor and press Shift+Cmd+F, then the text gets correctly added in the search field. Maybe some race condition?

**Comment by JacksonKearl** [comment] 2021-04-01 22:15
@fabb a change was made in 1.54 to the search actions, documented here: https://code.visualstudio.com/updates/v1_54#_changes-to-workspace-search-actions

In short it's now suggested to use `workbench.action.findInFiles` as opposed to `workbench.view.search`, as `findInFiles` more accurately describes the action taken, and allows for configuring where the search will occur based on `search.mode` (either in an editor or the search view). `workbench.view.search` will open the search view, but generally not run the search or modify it's contents. A similar issue https://github.com/microsoft/vscode/issues/120174 was created for the eclipse key mappings and fixed with a change to the eclipse keymap extension.

**Comment by fabb** [comment] 2021-04-02 05:22
Ok thanks, but then isn‘t it weird that when the search pane is already open, pressing Shift+Cmd+F with a selected text in the editor still does insert that text into the search field?

**Comment by JacksonKearl** [comment] 2021-04-02 05:42
The extension is configured to override the binding for cmd+shift+f to use workbench.view.search instead of the default workbench.action.findInFiles only when the search viewlet is not visible:

https://github.com/kasecato/vscode-intellij-idea-keybindings/blob/master/package.json#L401-L407

**Comment by fabb** [comment] 2021-04-02 05:53
Aaaaah, good find, thanks!

**Comment by fabb** [comment] 2021-04-02 06:54
i created a PR to fix it in the intellij keybinding: https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/216

@pim-pesochek do you use the intellij keybinding extension too? if yes then i'd say this issue could be closed.

**Comment by pim-pesochek** [comment] 2021-04-06 15:56
@fabb @JacksonKearl  Hi folks! Sorry for delay. Yes, I have installed plugin IntelliJ IDEA Keybindings in my VSCode.

**Comment by fabb** [comment] 2021-04-06 15:58
@pim-pesochek ok then the issue should be fixed when you update to the newest version of that extension. Please verify and close this issue if it is fixed.

**Closed** 2021-04-06 16:08 UTC
Labels: needs more info
