### ISSUE TITLE
The '$msCompile' problem matcher does not match an error

### ISSUE THREAD

**Issue by sys27** [microsoft/vscode#34660] opened 2017-09-19 21:33 UTC
Terminal reports that my solution has errors, but I dont see it inside problems tab.
Sample of error: d:\pew\!pew#\pew.resx : error MSB3103: Invalid Resx file. Could not find file 'd:\pew\!pew'. [d:\pew\!pew#\pew.csproj]

- VSCode Version: 1.16.1
- OS Version: Windows 10 Home x64
- C# project (.Net Core 2)

Steps to Reproduce:

1. Open VS Code
2. Open any folder.
3. Open terminal.
4. dotnet new classlib
5. Modify *.csproj and add reference to missing file:
```xml
<ItemGroup>
  <Compile Include="dhsajkdsk" />
</ItemGroup>
```
6. Build

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment] 2017-09-19 22:06
@sys27 Did you try logging this issue in the repo for the extension that is reporting the errors first?

**Comment by sys27** [comment] 2017-09-19 22:25
@ramya-rao-a no.
Do you mean to OmniSharp? But it is reproducible without extensions.

And also VS Code repo contains $msCompile matcher regexp: [problemMatcher.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts)

**Comment by ramya-rao-a** [comment] 2017-09-19 23:08
Ah, sorry my bad

**Comment by dbaeumer** [comment] 2017-09-20 08:33
The current msCompile problem matcher requires a location (line, column) in the error message. The workbench currently has no support for file errors. 

@jrieken any advice how to best create a file error. Should we use 0,0 as the location?

**Comment by jrieken** [comment] 2017-09-20 10:22
> The workbench currently has no support for file errors. @jrieken any advice how to best create a file error. Should we use 0,0 as the location?

Yes, sound like a winner. Tho we do try to map it the first word when opening the file

**Comment by rkeithhill** [comment] 2017-11-15 04:26
I'm seeing a related issue:

![image](https://user-images.githubusercontent.com/5177512/32818726-299e7bf0-c982-11e7-95fe-a9d3ab4b1b96.png)

If I click on that line (which is in the .csproj instead of the .cs file - weird), I get this error:

![image](https://user-images.githubusercontent.com/5177512/32818753-511ed9ae-c982-11e7-8835-6a487e8a6d5a.png)

The error is actually on line 540 of Connection.cs.  Somehow, it is getting the csproj file and source code file mixed up.  :-(

**Comment by rkeithhill** [comment] 2017-11-15 04:43
Looks like dotnet (MSBuild) is no longer outputting full paths but relative paths but is instead spitting out source code paths relative to the project path.  Fortunately it provides the full path to the project file.  Sigh...

```
21:71ms> dotnet publish --output c:\Users\Keith\GitHub\rkeithhill\PowerShell\debug --configuration Debug --framework net
coreapp2.0 --runtime win7-x64
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.PowerShell.CoreCLR.Eventing -> C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\Microsoft.PowerShell.CoreCLR.Eventing\bin\Debug\netcoreapp2.0\win7-x64\Microsoft.PowerShell.CoreCLR.Eventing.dll
  Microsoft.PowerShell.CoreCLR.Eventing -> c:\Users\Keith\GitHub\rkeithhill\PowerShell\debug\
  Microsoft.PowerShell.CoreCLR.Eventing -> C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\Microsoft.PowerShell.CoreCLR.Eventing\bin\Debug\netcoreapp2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll
  Microsoft.WSMan.Runtime -> C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\Microsoft.WSMan.Runtime\bin\Debug\netcoreapp2.0\win7-x64\Microsoft.WSMan.Runtime.dll
  Microsoft.WSMan.Runtime -> C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\Microsoft.WSMan.Runtime\bin\Debug\netcoreapp2.0\Microsoft.WSMan.Runtime.dll
  Microsoft.WSMan.Runtime -> c:\Users\Keith\GitHub\rkeithhill\PowerShell\debug\
engine\hostifaces\Connection.cs(540,75): error CS0117: 'RunspaceStrings' does not contain a definition for 'PrimaryRunspaceAlreadySet' [C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
```

The path to the file is `C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\System.Management.Automation\engine\hostifaces\Connection.cs`

**Comment by dbaeumer** [comment] 2017-11-15 07:59
@rkeithhill the advice here is to start msbuild with `/property:GenerateFullPaths=true` The problem is that with nested projects the pathes are relative the project file hence tracking them relative is quite combersome

**Comment by rkeithhill** [comment] 2017-11-15 16:25
That works. Thanks!

**Comment by graph** [comment] 2018-09-01 00:53
just to add the problem matcher doesn't match when the compiler reports a fatal error. I added an additional problem matcher just for the fatal error case.

**Comment by dbaeumer** [comment] 2018-09-03 07:57
@graph can you provide me with some sample of these fatal errors. Then I can tweak the regualer expression to match them.

**Comment by graph** [comment] 2018-09-03 22:33
See this post they look like this https://github.com/Microsoft/vscode/issues/34660#issuecomment-418032598

```
wordcount.cpp(57) : fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"
```

I already fixed all from my project. I don't remember how to trigger them. I have something like this to catch the fatal errors too

```
                    "pattern": {
                        "regexp": "^(\\..*)\\((\\d+)\\):[^:]*(warning|error) (.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 4
                    }
```
I have 2 patterns setup one for relative and one for absolute.

**Comment by dandrestor** [comment] 2018-10-01 05:56
I'm also seeing "fatal error" lines not being matched by the $mscompile matcher. On 0.19.0

**Comment by OlegBoulanov** [comment] 2019-10-17 18:31
Here is my problem:
VSCode/Ubuntu, 
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-30-generic

Output and Problems tabs:
CodeFile.cs(62,23): warning CA2007: Consider calling ConfigureAwait on the awaited task [/home/me/Projects/xxx/xxxLib/xxxLib.csproj]

Clicking on this line in Problems tab results with opening xxxLib.csproj file, not CodeFile.cs, as I'd expect

**Comment by alexr00** [comment] 2019-10-24 11:56
The original issue is not nicely solvable with the current problem matcher system. I recommend adding your own problem matcher to your local build task to handle this. Something like:
```
{
			regexp: /^(.*)? : (error|warning|info)\s(.+\d+):\s(.+)\s\[(.+)\]$/,
			kind: ProblemLocationKind.Location,
			file: 5,
			code: 3,
			message: 4
		}
```

**Comment by alexr00** [comment] 2019-10-24 11:56
duplicate of https://github.com/microsoft/vscode/issues/59337

**Closed** 2019-10-24 11:56 UTC
Labels: *duplicate, feature-request, tasks
