### ISSUE TITLE
Switch Chinese and English input mode inflict IDE can't work correctly

### ISSUE THREAD

**Issue by Mr-Eve** [microsoft/vscode#84449] opened 2019-11-11 04:18 UTC
- VSCode Version: 1.40.0
- OS Version: win10

Steps to Reproduce:

1. Under Chinese mode, try to input something without enter.
2. Switch to English mode, can't delete this line, and many operations are odd.

![2](https://user-images.githubusercontent.com/30228406/68560707-56171d80-047d-11ea-9033-8d33e9832285.gif)

**Comment by byyxx128** [comment] 2019-11-11 05:26
Just clarify some points:
1. "Chinese Mode" and "English Mode" mentioned by the author are actually the modes of IME rather than the display languages.
2. The author was using the "single line" mode of QQ IME. I saw the similar issues in other programs before, so I disabled the "single line" mode, then everything is fine so far. So I don't know if it is an issue of this IME.

As this IME is a Chinese IME, non-Chinese users may not be able to test it. Even a few people among Chinese users are using it, and only some of them turn on the "single line" mode, so...

Are you interested having a look at this issue? @rebornix

**Comment by byyxx128** [comment] 2019-11-11 05:30
Just clarify some points:
1. "Chinese Mode" and "English Mode" mentioned by the author are actually two input modes of IME rather than the display languages.
2. The author was using the "single line" mode of QQ IME. I saw the similar issues in other programs before, so I disabled the "single line" mode, then everything is fine so far. So I don't know if it is an issue of this IME.

As this IME is a Chinese IME, non-Chinese users may not be able to test it. Even a few people among Chinese users are using it, and only some of them turn on the "single line" mode, so...

Are you interested in having a look at this issue? @rebornix

**Comment by Eve-1995** [comment] 2019-11-11 06:07
I have used VSC for 2 years, and never meet this problem before. (I'm not sure if it is related to the version). 

And this troubled me a lot, because I need to communicate with workmates in Chinese and write code comment in Chinese. I have to switch language frequently.  My solution is reopen the file, in a conclude, this bother me a lot.

But now I find a perfect solution. Thanks @byyxx128 , your comment inspired me. I find in QQ IME setting as below. The red block means 'Input the holder text when switch language'.  And I check this radio, everything's fine. 

![image](https://user-images.githubusercontent.com/30228406/68564464-ab5a2b80-048b-11ea-998a-7e0c20a88073.png)

However, not all IME support this function, so I'm sure there is a few people are suffering.

**Comment by byyxx128** [comment] 2019-11-11 07:00
You are welcome. Coincidentally, I'm using QQ IME as well. That is the reason why I identified what IME you were using immediately.

Congratulations on finding a solution. But I don't think it could be a solution because it actually just avoids the triggering conditions for the issue. Therefore, we can continue to explore the real cause of this problem.

**Comment by byyxx128** [comment] 2019-11-11 07:05
You are welcome. Coincidentally, I'm using QQ IME as well. That is the reason why I identified what IME you were using immediately.

Congratulations on finding a solution. But I don't think it could be a solution because it actually just avoids the triggering conditions for the issue. Therefore, we can continue to explore the real cause of this problem.

Additionally, you can join the QQ group via 238135133 to give feedbacks of QQ IME.

**Comment by Eve-1995** [comment] 2019-11-11 07:12
I just know QQ IME has own group. I will submit a application for joining and feedback this issue. And my QQ IME can't update automatically, and this issue happens rencently. Therefore I still keep a doubt for VSC.

**Comment by rebornix** [comment] 2019-11-11 19:31
It sounds like an issue with QQ IME as mentioned above it happened in other applications too. Is there any link to the issue report to QQ IME?

**Comment by Mr-Eve** [comment] 2019-11-12 02:00
@rebornix  Thanks a lot to check this issue. 

This problem should appear in the past time if the reason is related to QQ IME. Because  I have never update the version of QQ IME. And I have reported this issue to the official group of QQ IME.

**Comment by jasonlyu123** [comment] 2019-11-14 06:31
Have the some problem with microsoft IME. It happen to keystrokes that doesn't trigger compositionupdate event during composition.

**Comment by byyxx128** [comment] 2019-11-14 14:44
I have same guess.
So this issue should continue to be investigated.

**Comment by byyxx128** [comment] 2019-11-14 15:01
As mentioned by @jasonlyu123 , this may be not related to a specific IME. I remembered I saw that before. but I don't remember details.
Basically, you know, Chinese IMEs have two methods of typing Chinese characters.
1. ![image](https://user-images.githubusercontent.com/20079289/68867825-771d7f80-06c4-11ea-87f2-3f7a24f9b9b5.png)
![image](https://user-images.githubusercontent.com/20079289/68867982-b3e97680-06c4-11ea-9a3d-c2a118c85142.png)
2. ![image](https://user-images.githubusercontent.com/20079289/68868022-c5328300-06c4-11ea-9200-d2618b1468d9.png)

The issue only occurred under the first way. And you should also know that most Chinese users use Sogou IME, and Sogou uses the second way, so... That is the reason why many people didn't see this problem before.

**Comment by Mr-Eve** [comment] 2019-11-14 16:32
It make sense! Should I close this issue?

**Comment by byyxx128** [comment] 2019-11-14 17:05
No, keep it open until the issue is fixed (or declared not to fix).

**Comment by doggy8088** [comment] 2019-11-18 03:51
I'm using Windows 10 built-in 微軟新注音輸入法(Microsoft New Phonetic IME). I'm suffering from this issue as well. I just record a short clip to demonstrate this issue on my PC.

![2019-11-18_11-48-55](https://user-images.githubusercontent.com/88981/69023385-86206c80-09f9-11ea-95ab-829ade09c108.gif)

**Comment by Mr-Eve** [comment] 2019-11-18 04:56
You can try to find some input settings via IME to solve this problem. @doggy8088 
BTW, The world is very small... I will see u in ngChina2019 : )

**Comment by doggy8088** [comment] 2019-11-18 14:41
@Mr-Eve I can't find any settings related to this problem.  This is definitely a bug.  Any suggestion?

See you soon! 😄

**Comment by Mr-Eve** [comment] 2019-11-18 15:02
@doggy8088 This problem really effect the state of work. I guess u wanna solve it as soon as possible.

Temparerily, u can switch another IME as a solution, u can find some settings based on the words of @byyxx128 .

**Comment by doggy8088** [comment] 2019-11-18 15:09
@Mr-Eve No no, I already solved this issue by downgrade my VSCode to 1.39! 😄

**Comment by byyxx128** [comment] 2019-11-18 15:11
All in all, it's definitely not a bug of any specific IME at least.
Is it related to this new feature?
https://code.visualstudio.com/updates/v1_40#_better-handling-for-unicode-combining-characters

**Comment by doggy8088** [comment] 2019-11-18 16:14
Could be. @rebornix

**Comment by jasonlyu123** [comment] 2019-11-20 02:20
@rebornix I found this problem also appear in the embed chrome dev tool. Maybe we'll just wait for next electron version bump and see if the problem persist.
![圖片](https://user-images.githubusercontent.com/36730922/69203470-6024d480-0b7f-11ea-8e4c-9d7e35ded4d1.png)

**Comment by doggy8088** [comment] 2019-11-20 12:03
@jasonlyu123  I can confirm that in my Chrome version `78.0.3904.97`. Did you see any upstream issue been opened?

**Comment by ck97756** [comment] 2019-12-04 04:08
I have this issue too.
VS Code version: 1.40.2

**Comment by doggy8088** [comment] 2019-12-19 01:25
After I upgrade to `1.41.0`, this issue still exists. This is really annoying! 😒

**Comment by doggy8088** [comment] 2020-01-13 08:29
@rebornix Do you have any upstream issues information?

**Comment by doggy8088** [comment] 2020-01-19 05:02
@Mr-Eve 你的標題有個錯字，是否可以請你修正？ `Swich` -> `Switch`

**Comment by Mr-Eve** [comment] 2020-01-19 05:03
> 
> 
> @Mr-Eve 你的標題有個錯字，是否可以請你修正？ `Swich` -> `Switch`

OK, thanks for reminding

**Comment by rebornix** [comment] 2020-01-27 19:18
Can anyone help confirm that you can see this issue in Dev Tools of latest Chrome? If so I can try to find an upstream issue and also see how to fix from our side in Electron.

**Comment by doggy8088** [comment] 2020-01-28 18:41
@rebornix I record a short video for you. Please check this out: https://youtu.be/PzRPH7hQmh8

**Comment by rebornix** [comment] 2020-01-29 00:22
@doggy8088 thanks! It looks like a chromium bug. We should validate this once we adopt a newer version of Electron. cc @deepak1556

**Comment by abc1236762** [comment] 2020-03-29 04:13
In vscode 1.43.2:
when windows 10 version 18363.720, no issue
when windows 10 version 19041.172 (insider), issue still exist
using Taiwan's Microsoft Bopomofo IME

**Comment by doggy8088** [comment] 2020-03-29 15:02
@abc1236762 I'm using `windows 10 version 18363.720` and `vscode 1.43.2`. There are still does have issue. I'm using Taiwan's Microsoft Bopomofo IME.

**Comment by abc1236762** [comment] 2020-03-29 16:25
in vscode 1.43.2 and windows 10 version 18363.720, the issue exist again to me, and when I reopen vscode, no issue.
seems sometimes happened to me, sometimes not.

**Comment by peienxie** [comment] 2020-05-14 01:24
when I upgraded to vscode 1.45.0 the issue is gone
switching between Chinese and English works perfect

**Comment by doggy8088** [comment] 2020-05-14 03:26
@peidaqi I don't think so. I still have this problem in my VSCode 1.45.0.

**Comment by jasonlyu123** [comment] 2020-05-14 03:42
The discussion has started to go circular. As @abc1236762 said. we don't know how to reproduce the issue. It just sometimes happened and resolved after restarting vs code. 

We could either 
1. find a way to reproduce it and found a workaround or report to the chrome team.
2. Just wait for a long enough period of time after each release and see if it resolved. 
if most people on this thread agreed on it resolved, just close this.

**Comment by doggy8088** [comment] 2020-05-14 04:07
@jasonlyu123 I can reproduce the problem anytime. If I know how to report to upstream, I can do the work, but I don't know where I can report to.

**Comment by jasonlyu123** [comment] 2020-05-14 04:13
how do you reproduce it? maybe we could at least tried to found a workaround.

**Comment by doggy8088** [comment] 2020-05-14 15:13
@jasonlyu123 Check this out: https://youtu.be/PzRPH7hQmh8

**Comment by doggy8088** [comment] 2020-05-14 15:17
I think @rebornix already know this. https://github.com/microsoft/vscode/issues/84449#issuecomment-578907589

![image](https://user-images.githubusercontent.com/88981/81952241-d4c16300-9638-11ea-9d55-2498a054e086.png)

**Comment by jasonlyu123** [comment] 2020-05-14 15:23
I didn't notice that was the way to reproduce it.  Sorry

**Comment by jasonlyu123** [comment] 2020-05-19 13:41
@doggy8088 保哥：
我試了一段時間終於發現要怎麼重現你的問題了，沒有發現你是切換輸入法，切換輸入法或是用游標切換中英模式幾乎百分之百可以重現問題，我在 chromium 的 edge 中也可重現一樣的問題，但可能是因為我大多是用 shift 鍵切換中英模式所以問題很少出現。

**Comment by doggy8088** [comment] 2020-08-24 14:18
@Mr-Eve  I think this issue has been solved by recent versions.

**Closed** 2020-08-25 11:34 UTC
Labels: bug, editor-input-IME, upstream
