### ISSUE TITLE
A lot of whitespace at the end of notebook

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94024] opened 2020-03-31 18:42 UTC
Testing #93742

* create a notebook with a single query: `repo:microsoft/vscode label:bug assignee:alexdima is:open`
* execute the query using the run button to the left of the editor
* observe that there is a large area of whitespace after the issues:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78063211-21eebb80-7390-11ea-94e3-d6a06015b1a0.gif)

**Comment by rebornix** [comment] 2020-03-31 23:01
/duplicate of https://github.com/microsoft/vscode/issues/93940, thanks!

**Closed** 2020-03-31 23:01 UTC
Labels: *duplicate, notebook
