### ISSUE TITLE
editor.codeActionsOnSave -> source.organizeImports will remove imports that are used in ES6 object literal

### ISSUE THREAD

**Issue by aghreed** [Microsoft/vscode#50132] opened 2018-05-18 20:05 UTC
- VSCode Version: 1.23.1
- OS Version: OSX 10.13.4

Steps to Reproduce:

1. Use the newly released "editor.codeActionsOnSave" "source.organizeImports" setting:
```
    "[typescript]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "[typescriptreact]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
```
2. Open up a file that has an import which is used in a ES6 object literal construction, such as:
```
import { navigation } from "./navigation";

export const app = {
    navigation,
    api: createApi(apiConfig),
    namespace: "example",
    ...
 };
```
3. Save the file, and the `import { navigation } from "./navigation";` line is removed, leaving `navigation` undefined.
 
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-05-18 20:19
Duplicate of #49193 

It is fixed in vscode insiders

**Closed by mjbvz** 2018-05-18 20:19 UTC
Labels: javascript
