### ISSUE TITLE
Bug when pasting HTML code

### ISSUE THREAD

**Issue by Hettand** [microsoft/vscode#229767] opened 2024-09-25 21:47 UTC
Type: <b>Bug</b>

Hi, when I paste HTML code, the first tag generates an extra closing tag. For example, this code:

<button type="button" class="btn btn-1 fc-1 fs-16 mx-1"> 
   <i class="fa-solid fa-calendar-days"></i> 
</button>
When I paste it, it looks like this:

<button type="button" class="btn btn-1 fc-1 fs-16 mx-1"></button> 
   <i class="fa-solid fa-calendar-days"></i> 
</button>

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.85GB (6.59GB free)|
|Process Argv|--crash-reporter-id 63885809-d420-46c8-a9f7-abe652a3e142|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
fje88620:31121564
iacca1:31144502
notype1cf:31143046

```

</details>

**Comment by IllusionMH** [comment] 2024-09-26 00:54
Your code samples aren't visible.

Please write them inside of code fences (` ``` ` before and after code block)

**Comment by aeschli** [comment] 2024-09-26 09:05
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-26 09:05 UTC
