### ISSUE TITLE
源代码管理无法识别git仓库以及其菜单内的"打开文件夹"按钮失效

### ISSUE THREAD

**Issue by z-Rayleigh** [microsoft/vscode#138718] opened 2021-12-09 09:04 UTC
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Issue Type: <b>Bug</b>

源代码管理无法识别git仓库以及其菜单内的"打开文件夹"按钮失效

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.45GB free)|
|Process Argv|--crash-reporter-id cf2a13d3-787b-459b-a8fd-0edb84f4f00d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
vscode-babel-transform|And|1.0.0
vscode-styled-jsx|bla|2.1.1
path-intellisense|chr|2.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
git-graph|mhu|1.30.0
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.10.0
vscode-filesize|mkx|3.1.0
easy-less|mrc|1.7.3
vscode-language-pack-zh-hans|MS-|1.63.2
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
vue-beautify|pea|2.0.4
vscode-css-peek|pra|4.2.0
view-in-browser|qin|0.0.5
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.1
code-settings-sync|Sha|3.4.3
js-jsx-snippets|sky|11.0.0
autoimport|ste|1.5.4
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30408636
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999

```

</details>

**Comment by CodeCrazy-ywt** [comment] 2021-12-09 09:52
The source code management cannotcrecognize git repo, and the "open folder" button doesn't work

**Comment by ryenus** [comment] 2021-12-11 15:09
Possible dupe of https://github.com/microsoft/vscode/issues/138754

**Closed** 2021-12-14 21:41 UTC
Labels: needs more info, *duplicate, *english-please, translation-required-chinese-simplified
