### ISSUE TITLE
VSCode doesn't open offline

### ISSUE THREAD

**Issue by wolf99** [Microsoft/vscode#63284] opened 2018-11-16 08:56 UTC
- VSCode Version: 1.29.0
- OS Version: 1809 & 1709

Steps to Reproduce:

1. Install VS Code 1.2.0 and open first time while connected to internet
2. Turn off data connection
3. Try to restart VS Code (it does not open at all, either from shortcuts or exe)

This is related to #7570. That issue is locked and limited, making it impossible to provide new information that may help the debug process.

In that issue, it is mentioned that the fix is expected in VSCode 1.28.0 https://github.com/Microsoft/vscode/issues/7570#issuecomment-423015980. We are now at 1.29.0 and the issue is still present.

The additional information that may help here, is that I noticed on my work laptop, that is running Windows 10 1709, does not have this problem - 1.29.0 appears to work fine with Flight mode enabled.

This issue is indeed a dupe of the mentioned issue (#7570), please add the additional data point from here to that (again, I can't because the issue is locked ☹️ ) before closing this one, thank you.

**Comment by nancym** [comment] 2018-11-16 12:05
Yes, please unlock issue #7570 so we can add information to help people work around this offline problem. Here's some info from me:

1. I **can** use VS Code offline on my device that's running Windows 10 Home 1803.
2. I can **not** use VS Code offline on my device that's running on Windows 10 Home 1809.

Because of this, I'm doing everything I can to prevent device 1 from auto upgrading to Windows 1809 😱 .

**Comment by usernamehw** [comment] 2018-11-16 13:46
It looks like this comment https://github.com/Microsoft/vscode/issues/7570#issuecomment-422815878 stated that **EXPLORATION BUILD** which uses newer version of Electron fixes it and not the stable/insiders. But I can be wrong since I never experienced the issue.

**Comment by nancym** [comment] 2018-11-16 14:02
I've read that too and I'd love to know how to get the "Exploration Build" of VS Code. Please someone post how to install that - thank you!

**Comment by usernamehw** [comment] 2018-11-16 14:34
Well, that exact comment that I linked has 3 links: for macOS, Windows and Linux

**Comment by usernamehw** [comment] 2018-11-16 21:35
VSCode version doesn't matter here. Exploration build currently testing **Electron 3** and not yet merged #52629.
>  I would have thought the issue either solved, or at least expected by the developers to be solved

That's an <kbd>upstream</kbd> issue. Issues with this tag - not problems inside vscode (usually not solvable). Sometimes some hacks created to workaround the issue if possible, but not for this one.

**Comment by bpasero** [comment] 2018-11-18 17:43
I do not think we need more info, thanks for helping though. According to people reporting back to us with the Exploration builds, this issue will get fixed once we move to Electron 3 which we are planning to do in Q1 2019.

Closing as duplicate of https://github.com/Microsoft/vscode/issues/7570

**Closed by bpasero** 2018-11-18 17:43 UTC

**Comment by wolf99** [comment] 2018-11-18 20:51
Thanks for the explanation both @bpasero & @usernamehw
