### ISSUE TITLE
dark themes are not behaving correctly & syntax highlighting issue for vue

### ISSUE THREAD

**Issue by cheersmas** [microsoft/vscode#155153] opened 2022-07-14 08:21 UTC
Issue Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.69.1 (Universal)
- OS Version: MacOS 12.0.1 (21A559) (M1)

Steps to Reproduce:

1. Switch to a dark theme on this version and access a `.vue` file. `Styles` as well as `script` tags are not highlighted as before. 
![image](https://user-images.githubusercontent.com/41203791/178936888-a9427e49-56b8-4c14-95e8-768f5703d2ab.png)
![image](https://user-images.githubusercontent.com/41203791/178936931-b22d26de-34f1-4548-9731-dae1561902a1.png)

> `Terminal` also has a different/lighter background color as before.

VS Code version: Code 1.69.1 (Universal) (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:51.333Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 2d4031f3-a2b5-415c-9066-cfb837c58782|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-tailwindcss|bra|0.8.6
npm-intellisense|chr|1.4.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
styled-components-snippets|jon|0.10.0
vscode-docker|ms-|1.22.1
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
vetur|oct|0.35.0
typescript-hero|rbb|3.0.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|3.1.1
vue-helper|she|2.4.7
sass-indented|syl|1.8.22
tldraw-vscode|tld|1.18.0
es6-string-html|Tob|2.12.0
vscode-status-bar-format-toggle|tom|3.0.0
vscodeintellicode|Vis|1.2.22
volar|Vue|0.38.5
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdc:30486549

```

</details>

**Comment by jserradellgaddexapp** [comment] 2022-07-14 11:20
Same to me
![CleanShot 2022-07-14 at 13 19 41](https://user-images.githubusercontent.com/92920915/178971112-50a78aeb-b3ab-4c0b-abf4-a308a6b7e064.png)

**Comment by AminulBD** [comment] 2022-07-14 11:35
Same issue here!

**Comment by aeschli** [comment] 2022-07-15 10:13
duplicate of https://github.com/microsoft/vscode/issues/152816

**Closed by aeschli** 2022-07-15 10:13 UTC
Labels: new release
