### ISSUE TITLE
Allow to run the same task in multiple copies

### ISSUE THREAD

**Issue by korenb** [Microsoft/vscode#65260] opened 2018-12-18 07:28 UTC
I have a watching task:
```
        {
            "label": "Start Client",
            "type": "shell",
            "command": "ng",
            "args": [
                "serve",
                "${input:appName}",
                "--configuration=${input:appCfg}",
                "--host=0.0.0.0",
                "--port=${input:httpPort}"
            ],
            "isBackground": true,
            "runOptions": {
                "reevaluateOnRerun": false
            },
            "problemMatcher": []
        }
```
so in `${input:appName}` option it may be a few different applications. And when i try to run this task over running one with different inputs then i get message _The task 'Start Client' is already active and in background mode._

here is example of inputs:
```
        {
            "id": "appName",
            "description": "The application you want to run",
            "type": "pickString",
            "default": "main-client",
            "options": ["main-client", "admin-client"]
        }
```

I want it to be able to run in multiple instances using different parameters

**Comment by alexr00** [comment] 2018-12-18 11:18
Allowing multiple of a task is a duplicate of https://github.com/Microsoft/vscode/issues/32264

**Closed** 2018-12-18 11:18 UTC
Labels: *duplicate, tasks
