### ISSUE TITLE
Feature request: Add number of selected lines to status bar

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#21628] opened 2017-03-01 12:58 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.2|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|matlab|Gimly81|0.5.0|
|status-bar-tasks|GuardRex|0.2.0|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.4.3|
|cpptools|ms-vscode|0.10.1|
|vscode-clearcase|OpenNingia|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.2.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Select some text.
2. Status bar shows (x selected), where x is the number of characters.
Please add the number of lines and columns when using block selection.
This would be very useful for quickly counting the number of lines and checking that you had selected the right number of lines.

**Comment by alexandrudima** [comment] 2017-03-01 15:33
This can be implemented by an extension.

**Comment by pedger** [comment] 2017-03-16 11:21
@bpasero suggested https://marketplace.visualstudio.com/items?itemName=tomoki1207.selectline-statusbar
on issue #932
(thanks)

**Comment by BillDenton** [comment] 2017-03-16 12:31
Thanks, that works OK. However, I think it would still be better if it was integrated. It already shows the number of selected characters, so IMHO it would be a logical extension to add the number of lines. This could fit inside the "(X selected)" message on the right.

**Comment by baslr** [comment] 2017-04-10 15:33
@BillDenton, right sometimes I want to know how many lines are selected.

**Comment by mjbvz** [comment] 2017-11-08 23:27
Duplicate of #932

**Closed by mjbvz** 2017-11-08 23:27 UTC
Labels: editor, extension-candidate, feature-request
