### ISSUE TITLE
Unable to render cell UI after opening Notebook file in remote window

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode#123494] opened 2021-05-10 18:15 UTC
- VS Code Version: 1.56.0
- OS Version: Win 10 Enterprise 21H1 19043.928

Steps to Reproduce:

1. Notebook is opened using showNotebookDocument API in remote window as the last step of the resolver.
2. The correct file is opened but there is no cell UI shown. An indeterminate loader is shown at the top of the file:
3. Closing the automatically opened file and manually opening it again results in the same issue.
4. Opening any other Notebook file from this point onwards results in the same issue.

![image](https://user-images.githubusercontent.com/6413608/117705387-d73d9680-b180-11eb-9fa4-bd1b0116282c.png)

Here is the output from the Developer Console:

![image](https://user-images.githubusercontent.com/6413608/117705478-f0dede00-b180-11eb-9d25-d6419e9dc6b0.png)

The relevant Jupyter logs are attached with this issue.
[jupyter_log_nb_open_issue.txt](https://github.com/microsoft/vscode/files/6454162/jupyter_log_nb_open_issue.txt)

**Comment by SiddhanthUnnithan** [comment] 2021-05-10 22:18
Adding @sevillal, @shsuman, @AbeOmor for tracking

**Comment by roblourens** [comment] 2021-05-10 22:44
This worked before right?

**Comment by roblourens** [comment] 2021-05-10 23:07
The basic scenario still works for me - using `showNotebookDocument` to open a notebook from the resolver. Tried with github-issues and jupyter.

**Comment by roblourens** [comment] 2021-05-10 23:11
Can you run "Set Log Level", pick Trace, try the scenario again, then share the log from the `Log (Window)` output channel? Otherwise we might have to debug together.

**Comment by SiddhanthUnnithan** [comment] 2021-05-10 23:14
[log_level-trace_nb_open_issue.txt](https://github.com/microsoft/vscode/files/6455444/log_level-trace_nb_open_issue.txt)

**Comment by SiddhanthUnnithan** [comment] 2021-05-10 23:15
Some more interesting behaviour. At some point the Notebook stops loading and its empty. If I move my cursor to the file I see the "+Code" and "+Markdown" hover-over options:

![image](https://user-images.githubusercontent.com/6413608/117735728-e5a0a800-b1aa-11eb-83dd-9d9131dc9685.png)

Even after clicking the two options I don't see cells in the Notebook.

**Comment by SiddhanthUnnithan** [comment] 2021-05-10 23:19
I clicked "+ Code" a number of times and saved the file. When opening it through the Azure ML Studio I see the following:

![image](https://user-images.githubusercontent.com/6413608/117735928-5cd63c00-b1ab-11eb-96a7-29f43440376a.png)

Looks like the edit and save works successfully and its just that I don't see the output in the window.

**Comment by SiddhanthUnnithan** [comment] 2021-05-10 23:22
One last thing I should mention - this only happens in a remote window wherein we call the showNotebookDocument API as part of the resolver. In a remote window that is created with a simpler resolver (just connect, don't try and open a Notebook) the Notebooks are rendered correctly:

![image](https://user-images.githubusercontent.com/6413608/117736157-d8d08400-b1ab-11eb-8342-9afa9efa94da.png)

**Comment by roblourens** [comment] 2021-05-11 01:14
I haven't used azure ml notebooks, how can I set up to repro this myself? Or if you'd prefer, I could try to debug this on a call tomorrow.

**Comment by SiddhanthUnnithan** [comment] 2021-05-11 02:42
I think a call would be best - let me find some time for the two of us and a few others for tomorrow.

**Comment by roblourens** [comment] 2021-05-12 04:03
Summary, the problem is with the way we pack a resource URI into another URI to be loaded in the webview here https://github.com/microsoft/vscode/blob/307cb32f306a527a30a5b1756e8bf548c141192c/src/vs/workbench/contrib/webview/common/webviewUri.ts#L15.

It's fixed by this large change https://github.com/microsoft/vscode/commit/b847eb35e7efc5d989f140de3a2a42ce1b1e51aa

and also by this change, which is potentially impactful https://github.com/microsoft/vscode/commit/05ef37c06a0142ae25c7588db3329ae34395a9b5 and too suspicious to prepare as a candidate.

It can also be worked around on the extension side by not putting uri-encoded slashes into the remote authority.

**Comment by roblourens** [comment] 2021-05-12 17:19
@mjbvz actually this isn't fixed in main which has your change. It's actually failing to load loader.js for some reason. Here's a vsix of ssh that will use URIs in this format

[remote-ssh-0.65.4.zip](https://github.com/microsoft/vscode/files/6467967/remote-ssh-0.65.4.zip)

**Comment by mjbvz** [comment] 2021-05-20 00:41
Worked towards addressing this with #123740 but haven't tested this scenario yet. We still may need a few changes in the notebook code to make sure all the JS files are loaded from the correct locations

**Comment by roblourens** [comment] 2021-06-02 23:27
I think this is good now... did you test this scenario with the encoded slash @mjbvz?

**Comment by rzhao271** [comment] 2021-06-09 18:47
I'm not sure why adding the label didn't cause the bot to ping. @connor4312 is that a known issue?
Meanwhile, @SiddhanthUnnithan I'm wondering if you can verify this issue on VS Code Insiders?

**Comment by roblourens** [comment] 2021-06-09 19:30
I can verify this one with my vsix. Azure ML made a change so they won't be impacted by the thing that was fixed here

**Comment by roblourens** [comment] 2021-06-09 20:18
Now I get this error

```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://vscode-remote%2Bssh-remote%2Bfoo%252fbar.vscode-resource.vscode-webview.net/home/roblou/.vscode-server-insiders/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/extensions/markdown-language-features/notebook-out/index.js
    at s (notebookWebviewPreloads.js:3)
    at c (notebookWebviewPreloads.js:3)
    at _load (notebookWebviewPreloads.js:3)
    at _.load (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.renderMarkdown (notebookWebviewPreloads.js:3)
    at Q (notebookWebviewPreloads.js:3)
    at U (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
```

**Comment by rzhao271** [comment] 2021-06-09 20:25
Forgot to mention that I discussed this offline with @SiddhanthUnnithan and they verified this offline on their end. @roblourens could that be another issue?

**Comment by roblourens** [comment] 2021-07-01 00:19
@mjbvz I think the error I posted above is the same as the discussion in https://github.com/microsoft/vscode-remote-release/issues/5250#issuecomment-866434193. An escaped percent sign is not allowed, seems that an escaped slash is not either? If I'm understanding the correctly, seems that we need to match the limitations of URL in our URL class

**Comment by mjbvz** [comment] 2021-07-01 17:33
@roblourens Can you share your updated repo steps. I just tested a basic notebook on remote ssh and it works fine:

![Screen Shot 2021-07-01 at 10 32 05 AM](https://user-images.githubusercontent.com/12821956/124166378-9d3d9200-da57-11eb-8da0-e1ce6e96e8b9.png)

**Comment by roblourens** [comment] 2021-07-01 23:33
It's probably easiest to just hack an encoded slash/percent sign into the URI that you create for the webview resources. I can send a build of remote-ssh that does this if you need it.

**Comment by mjbvz** [comment] 2021-08-07 02:34
Thanks for the example extension @roblourens. Using it, I see urls such as the following inside of webviews (I've connected to localhost):

```
https://vscode-remote%2Bssh-remote%2Blocalhost%3Dfoo%2Fbar.vscode-resource.vscode-webview.net/Users/matb/.vscode-server-oss/bin/49af1cbe00271ac2ea36cfc5f7352fe31a7b0094/extensions/markdown-math/preview-styles/index.css
```

This url does not seem to be valid. You can test this using `new Url(...)`. The encoded slash (`%2f`) seems to cause the issues here. This results in our service worker never even seeing requests for these resources

Digging into this a bit farther, here's an original URL that we get passed in a call to `asWebviewUri`:

```
vscode-remote://ssh-remote%2Blocalhost%3Dfoo%2Fbar/Users/matb/projects/vscode-docs/docs/java/images/java-project/lightweight-icon.PNG
```

The function transforms it into:

```
https://vscode-remote%2Bssh-remote%2Blocalhost%3Dfoo%2Fbar.vscode-resource.vscode-webview.net/Users/matb/projects/vscode-docs/docs/java/images/java-project/lightweight-icon.PNG
```

This second URL is invalid. However what's interesting is that if you simply replace `vscode-remote` with `https` in the original url, it also becomes invalid. I don't fully understand this yet but am looking to see if we can better encode the authority to avoid this

**Closed** 2021-08-09 18:24 UTC
Labels: bug, notebook
