### ISSUE TITLE
Webview Panels Dispose Bug

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158839] opened 2022-08-23 00:36 UTC
I was running into an issue where closing a webview panel on extension deactivating. When I add a root to a multi-root workspace, the extension is deactivated (which is expected), but the panel isn't disposed although I specifically ask it to. 

Repro steps in extension sample:
1. Use webview-sample extension sample.
2. Add code to close panel on deactivate:
```
export function deactivate() {
	CatCodingPanel.currentPanel?.dispose();
}
```
3. open a single-root workspace and start the extension sample (should have the webview appear).
4. Add another root to the workspace. The messages should stop (since the extension deactivated), but the panel still exists. :bug:

This is causing an issue in live preview where the preview persists when you add a root to a single-root workspace although the extension has deactivated. 😢 

I talked to Rob about this bug in live preview and he found that the issue was here:
https://github.com/microsoft/vscode/blob/dae1f74098a268de68b6acb27df615a9f486732e/src/vs/workbench/api/browser/mainThreadWebviewPanels.ts#L130

He mentioned that it was because the webview panels weren't being disposed properly.

cc: @roblourens

**Comment by roblourens** [comment] 2022-08-23 20:49
@mjbvz even if we don't restart the extension host when going from 1 -> 2 workspace folders, there are other cases where the EH will restart, like when it crashes or you just run the "Restart Extension Host" command. Why wouldn't you just close/clean up all the webview panels when that happens?

**Comment by mjbvz** [comment] 2022-08-23 20:53
Duplicate of #98603

@roblourens We trying to avoid abruptly closing webviews as they may contain unsaved work. There's not an elegant way to handle this for every webview, although we may be able to implement something for serializable webviews

**Closed by mjbvz** 2022-08-23 20:53 UTC
Labels: bug
