### ISSUE TITLE
Allow adding metadata to NotebookData and NotebookCellData

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#97077] opened 2020-05-06 15:44 UTC
- VSCode Version:  1.45.0-insider
- OS Version: OSX

The new api is as follows https://github.com/microsoft/vscode/blob/682b2bd92f27c81e4da3bd640a0181ce30da0759/src/vs/vscode.proposed.d.ts#L1692
The cell information in `NotebookData` is defined as `NotebookCellData`.

Is it possible for extension authors to add custom metadata to the `NotebookData` object such that it would flow over to the corresponding `NotebookDocument` object. Similarly can we add custom metadata to the `NotebookCellData`, such that when a cell is executed or similar, the original metadata in ipyng is in NotebookDocument and NotebookCell.

In our case when `NotebookContentProvider.executeCell(NotebookDocument, NotebookCell)` is invoked, we can get the kernel information from the NotebookDocument (originally stored in ipynb), similarly cell level metadata from NotebookCell.

Allowing extension authors to store such metadata also helps extension authors use a single model for both VS Code as well as our own use.
Else we'd need to maintain two models and map the two.

However in the case of cells, I don't think we can even perform such a mapping to get the original Jupyter cell metadata out of the VS Code cells.

@rebornix /cc

**Comment by rebornix** [comment] 2020-05-08 18:59
turns out to be duplicate of https://github.com/microsoft/vscode/issues/96433, let's track it here.

**Closed** 2020-05-08 19:00 UTC
Labels: *duplicate
