### ISSUE TITLE
Show Type Hierarchy for typescript

### ISSUE THREAD

**Issue by yurymann** [microsoft/vscode#198604] opened 2023-11-18 23:47 UTC
When choosing `Types: Show Type Hierarchy` command in a typescript project, _References_ pane shows "No results. Try running a previous search again:". The expected result would be showing the type hierarchy in _References_ pane, which works for Java and has just been implemented for Python: #4978. 

Is it possible to implement it? 
vscode already supports "Find All Implementations" and "Go to implementation" for typescript. It looks like all building blocks are there and just the UI needs to be added. This is crucial to visualise dependencies between classes and interfaces in a project with hundreds of classes and interfaces.

**Comment by mjbvz** [comment] 2023-11-20 16:26
Duplicate of https://github.com/microsoft/TypeScript/issues/45877

**Closed by mjbvz** 2023-11-20 16:26 UTC
