### ISSUE TITLE
Double-click to select text does not always work

### ISSUE THREAD

**Issue by jimbonator** [microsoft/vscode#84319] opened 2019-11-08 21:19 UTC
I've noticed recently that double-clicking to select text is picky.  I don't think this was the case in earlier versions.

To reproduce, I hover the I-beam over a word or symbol in the editor and double-click.  Sometimes I have to move the cursor a pixel or two either direction to reproduce.  It appears if the center of the I-beam is between characters, this bug can be repro'd consistently.

I also sometimes see the cursor change shape (get "fatter") when I shift it slightly over the text.  When it changes shape, I can reproduce this more consistently.

I've already tried futzing with system mouse controls (esp. double-click speed), but that makes no difference.  When I find the right location over the text, no amount of double-clicking will select it.  I've also tried switching color themes, but see the problem no matter which I try (incl. default themes).

(Mac OS 10.14.6.  All extensions disabled when testing.)

**Comment by uziel200** [comment] 2019-11-09 02:03
I have the same error from the 1.40.0 release

**Comment by brent-williams** [comment] 2019-11-16 03:28
I had zoomlevel -2, setting zoomlevel 0 seemed to fix the problem.  A poor workaround though as then the activity bar, explorer bar and other chrome are all huge and cannot otherwise be reduced in size.  Possibly this bug is regression of #1850.

**Comment by jimbonator** [comment] 2019-11-18 18:24
I'm also zoomed in.  If I reset zoom I can still reliably reproduce this problem, including the "fat I-beam" mentioned in the original report.

**Comment by brent-williams** [comment] 2019-11-19 08:37
Maybe other factors at work as well then.  I can repo with zoom at 2 and at -2, but cannot repo at 0.  Am on MacOS 10.15.1 w/ font 'Cascadia Code'.  Very trying bug.

**Comment by sourcegr** [comment] 2019-11-19 12:54
This must be a duplicate of #84319

**Comment by jimbonator** [comment] 2019-11-20 01:18
I've reset zoom to zero and reset my font family to both the default (`Menlo, Monaco, 'Courier New', monospace`) and merely `monospace`.  I've disabled all extensions and restarted VSCode (not merely reloaded the window).

It's more difficult to reproduce, but I think that's a function of the smaller typeface than the font family itself.  That is, finding the "sweet spot" between characters requires more sensitive mouse movements, but it's still there, in particular the "fat I-beam" I referred to before.

This may very well be a duplicate of #83150, it looks similar to the animation there (although I don't see the I-beam change shape).

**Comment by bkarlson** [comment] 2019-11-23 17:42
Confirming this on version below, utterly annoying. I thought my trackpad was dying, but thanks god it's only a VSCode bug :) 

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by brent-williams** [comment] 2019-11-28 00:16
Bug still there in 1.40.2.

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by lastobelus** [comment] 2019-12-02 04:08
this is a pretty big productivity killer, because it takes you right out of flow state. Especially frustrated when happens during setting up a multiple selection.

**Comment by antwan** [comment] 2019-12-03 18:41
+1, glad I'm not the only one noticing this.
It's super annoying, specially when you happen to paste the whole line instead of what you actually double clicked and intented to copy.

For the record the faulty behaviour actually puts the cursor when you double click instead of selecting word (i.e. two single clicks instead of one double click).

MacOS 10.14.6
VSCode: 1.40.1

**Comment by alexandrudima** [comment] 2019-12-05 14:28
Duplicate of #83150

**Closed by alexandrudima** 2019-12-05 14:28 UTC
Labels: editor-input, mac
