### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by b3cft** [microsoft/vscode#118220] opened 2021-03-05 15:20 UTC
Issue Type: <b>Bug</b>

Just recieved an new update, now get a little blue (1) on the Account Icon, with `sign in to sync settings` but clicking does nothing. 

I've tried closing and restarting app.

VS Code version: Code - Insiders 1.55.0-insider (567b82a0f9c31bd463af64997997730c5d0173cc, 2021-03-05T05:22:52.277Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (38.68GB free)|
|Process Argv|--crash-reporter-id d84130c3-89a0-47ae-a4ce-aa1e8a9d5382|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3792)|
|Memory (System)|50.17GB (45.36GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.7.0
remote-containers|ms-|0.163.0
remote-wsl|ms-|0.54.0
vim|vsc|1.18.9
aws-toolkit-vscode|ama|1.20.0
vscode-puppet|bit|0.4.5
vscode-markdownlint|Dav|0.39.0
gitlens|eam|11.3.0
rpm-spec|Lau|0.3.1
MagicPython|mag|1.1.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.619093157
autodocstring|njp|0.5.4
puppet-vscode|pup|1.1.0
vscode-yaml|red|0.16.0
trailing-spaces|sha|0.3.1
pretty-json|sup|0.0.4
serverless-ide-vscode|Thr|0.5.30
json2yaml|tux|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265947
vspre833:30267464

```

</details>

**Comment by uberkael** [comment] 2021-03-05 15:46
I can confirm this behavior.

**Comment by IllusionMH** [comment] 2021-03-05 16:05
/duplicate of #118194 (better to follow this issue for updates)

Fix is expected in next build.

**Closed** 2021-03-05 16:06 UTC
Labels: *duplicate
