### ISSUE TITLE
Explorer cuts the tree off. 

### ISSUE THREAD

**Issue by WEBhicham** [microsoft/vscode#92434] opened 2020-03-11 07:03 UTC
When you resize the explorer the explorer stop showing you the entire tree. It also seems that the tree is cut of in the middle somewhere

![bug_report](https://user-images.githubusercontent.com/27362642/76390949-a5f3eb80-636e-11ea-843d-44313f2f4224.gif)

- VSCode Version: 1.44-insiders build
- OS Version:  Microsoft Windows 10 Pro 10.0.17763 N/A Build 17763

Steps to Reproduce:

1. make your explorer bigger/smaller in width 
2. have enough file/folders in your explorer to see the difference 

Does this issue occur when all extensions are disabled?: Yes

**Comment by RBNico** [comment] 2020-03-11 07:04
Same here

**Comment by navin-moorthy** [comment] 2020-03-11 07:07
More Info on the same issue:

Version: 1.44.0-insider
Commit: eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc
Date: 2020-03-11T05:31:25.663Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by mattacosta** [comment] 2020-03-11 10:21
Duplicate of #92430 (which just got fixed).

**Comment by IllusionMH** [comment] 2020-03-11 11:04
/duplicate

Thanks @mattacosta

**Closed by IllusionMH** 2020-03-11 11:04 UTC
Labels: *duplicate
