### ISSUE TITLE
HTML Format does not work with attributes

### ISSUE THREAD

**Issue by damcify** [Microsoft/vscode#18270] opened 2017-01-08 10:04 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Create a file with the extension html and open in code
2. Add the following lines:
```
<head>
    <meta http-equiv="content-type" content="text/html; charset=us-ascii">
</head>
<div class="datagrid">
    <table cellpadding="7">
        <col width="100" />
        <thead>
            <tr>
                <th colspan="9" style="text-align: center">Week 31, Monday 1 August 2016</th>
</tr>
....
```
3. The last tag in this example is not aligned correctly. Any tag with attributes is left aligned.

**Comment by LostInBrittany** [comment] 2017-01-09 09:57
I think it's a dupe of #18081 and the format is broken due to the `style` attribute in your tag.
The issue seems corrected in vscode-insiders version.

**Comment by damcify** [comment] 2017-01-09 12:48
Thanks, this indeed seems to be a duplicate.

**Closed** 2017-01-09 12:48 UTC
