### ISSUE TITLE
Bring Code window to foreground when opening a file from the command line and reusing existing window

### ISSUE THREAD

**Issue by warkid** [Microsoft/vscode#159] opened 2015-11-19 07:55 UTC
Currently (on Windows) when you open a file via command line with *--reuse-window* the file is opened but Code just flashes its icon on the taskbar staying in background. 
Please consider adding a commandline option --bring-to-front or bring Code window to front regardless when  file is opened from the command line.

//VS Code 0.10.1 on Windows 7 Professional SP1

**Comment by bpasero** [comment] 2015-11-19 10:20
Duplicate of #167

**Closed by bpasero** 2015-11-19 10:20 UTC

**Comment by elad** [comment] 2016-01-19 15:57
As noted in #167, I don't believe this is a duplicate and suggest to reopen it.

**Comment by bpasero** [comment] 2016-01-19 16:03
@elad please explain exactly what you see going on and think is wrong

**Comment by elad** [comment] 2016-01-19 16:11
The issue title is more generic than the issue description.

Basically, I want Code to behave exactly like Sublime. If I have an open window, and I type in the command line "code file," I want the existing Code window to be brought to the front and the file opened in it. Right now, it always opens a new window.

**Comment by bpasero** [comment] 2016-01-19 16:16
@elad try `window.openFilesInNewWindow: false` in settings.

**Comment by elad** [comment] 2016-01-19 19:49
Thanks! :) First search result pointed to this issue, so I thought it wasn't implemented yet. Sorry for the noise!

**Comment by bpasero** [comment] 2016-01-20 06:16
:+1:
