### ISSUE TITLE
Can't push to remote

### ISSUE THREAD

**Issue by BeardedDaddy** [microsoft/vscode#134389] opened 2021-10-04 16:04 UTC
Issue Type: <b>Performance Issue</b>

When trying to publish changes.
It does not occur at startup.

> git push -u BeardDaddy/Learning-Python main
fatal: unable to read 9a77b637f22c2f519d70b46c2ba1847612ed599a
fatal: the remote end hung up unexpectedly
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/BeardedDaddy/
Learning-Python.git'

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.65GB free)|
|Process Argv|--crash-reporter-id 260634ff-654b-4f69-8e91-d3a070cbac8d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	  8380	code main
    0	    25	  8968	   crashpad-handler
    0	   153	 11760	   window (git-error-1633363265785 - Learning Python - Visual Studio Code)
    0	    69	 10264	     searchService
    0	   399	 12956	     extensionHost
    0	    79	  1412	       electron_node main.js 
    0	    19	  3852	       c:\Users\grevy\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.7.5\x86_64-pc-windows-gnu\TabNine.exe --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.2 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Cobalt2 vscode-theme-kind=Dark vscode-machine-id=d3b40ee4bf0ea84e16433aa8ff6ef54c07fbd781bbbc0f969302ff542a74dd4f vscode-is-new-app-install=false vscode-session-id=974340db-7b1e-4773-b60e-deac6043592c1633362745610 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=1
    0	    11	  9940	         console-window-host (Windows internal process)
    0	    20	 16012	         "C:\Users\grevy\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.7.5\x86_64-pc-windows-gnu\WD-TabNine.exe" --client vscode --client-metadata clientVersion=1.60.2 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Cobalt2 vscode-theme-kind=Dark vscode-machine-id=d3b40ee4bf0ea84e16433aa8ff6ef54c07fbd781bbbc0f969302ff542a74dd4f vscode-is-new-app-install=false vscode-session-id=974340db-7b1e-4773-b60e-deac6043592c1633362745610 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=1
    0	    86	 16296	         "c:\Users\grevy\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.7.5\x86_64-pc-windows-gnu\TabNine.exe" --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.2 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Cobalt2 vscode-theme-kind=Dark vscode-machine-id=d3b40ee4bf0ea84e16433aa8ff6ef54c07fbd781bbbc0f969302ff542a74dd4f vscode-is-new-app-install=false vscode-session-id=974340db-7b1e-4773-b60e-deac6043592c1633362745610 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=1 --no_bootstrap
    0	   415	  1284	           "c:\Users\grevy\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.7.5\x86_64-pc-windows-gnu\TabNine-deep-local.exe" --settings C:\Users\grevy\AppData\Roaming\TabNine\local.settingsSmall --settings-version 1 --client vscode --client-metadata clientVersion=1.60.2 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Cobalt2 vscode-theme-kind=Dark vscode-machine-id=d3b40ee4bf0ea84e16433aa8ff6ef54c07fbd781bbbc0f969302ff542a74dd4f vscode-is-new-app-install=false vscode-session-id=974340db-7b1e-4773-b60e-deac6043592c1633362745610 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=1
    0	    67	  4448	       electron_node serverMain.js 
    0	    69	  5552	       "C:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12956
    0	    89	 13616	       electron_node bundle.js 
    0	    15	 15512	     watcherService 
    0	    11	  5256	       console-window-host (Windows internal process)
    0	    78	 12608	   window (Issue Reporter)
    0	   139	 13204	   gpu-process
    0	   107	 15640	   shared-process
    0	    66	 15832	     ptyHost
    0	    39	 17176	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (git-error-1633363265785 - Learning Python - Visual Studio Code)
|    Folder (Learning Python): 1205 files
|      File types: py(517) pyc(505) exe(17) txt(7) json(2) tmpl(2) bat(2)
|                  pem(1) cfg(1) xml(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python(6);
```

</details>
<details><summary>Extensions (85)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-tomcat|ada|0.11.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|13.2.1
arepl|alm|2.0.3
gitkraken-glo|axo|1.1.1
vscode-django|bat|1.6.0
python-manifest-template|ben|1.0.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
create-task|Dag|0.0.2
vscode-markdownlint|Dav|0.44.4
vsc-invoke|dch|0.0.12
derivitec-python-snippets|der|1.1.1
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
git-cheatsheet|dzh|1.4.3
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
prettier-vscode|esb|9.0.0
vscode-postfix-python|fil|0.1.3
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-python-dev-extension-pack|fra|0.4.0
pythonsnippets|frh|1.0.2
vscode-pull-request-github|Git|0.30.0
vscode-test-explorer|hbe|2.21.1
vscode-test-explorer-liveshare|hbe|1.0.5
Python-autopep8|him|1.0.2
python-coding-conventions|igr|0.0.4
python-essentials|Jil|0.0.3
vsc-python-indent|Kev|1.14.2
kite|kit|0.147.0
python-extension-pack|Leo|1.1.0
python-traceback-jumper|lin|1.0.9
vscode-python-test-adapter|lit|0.7.0
MagicPython|mag|1.1.0
python-path|mge|0.0.11
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
test-adapter-converter|ms-|0.1.2
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
python-docs|Muk|0.8.3
python-coding-tools|nil|1.0.3
autodocstring|njp|0.5.4
vscode-python-typehint|njq|1.4.1
advanced-new-file|pat|1.2.2
python-string-sql|ptw|1.1.0
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0
python-template-snippets|Ric|1.2.0
LiveServer|rit|5.6.1
vscode-qt-for-python|sea|1.1.4
code-settings-sync|Sha|3.4.3
guides|spy|0.9.3
code-spell-checker|str|2.0.8
vscode-jetty|Sum|0.1.11
python-pack|Swe|0.1.15
tabnine-vscode|Tab|3.4.29
even-better-toml|tam|0.14.2
cython|tcw|0.1.0
python-editing-terminal|ted|1.0.6
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
vscode-spring-initializr|vsc|0.7.0
vscode-wakatime|Wak|17.0.8
jinja|who|0.0.8
vscode-import-cost|wix|2.15.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593:30376534

```

</details>

**Comment by lramos15** [comment] 2021-10-18 16:44
Can you try updating to the latest VS Code version and disabling all extensions. Also does pushing from the command line work and just not in VS code?

**Comment by kachkaev** [comment] 2021-10-30 15:49
Same issue on VSCode 1.61.2 on macOS. This might be to do with this setting in my `~/.gitconfig`:

```ini
[pull]
  ff = only
```

Here is why this preference is recommended (and hence might be common):
https://blog.sffc.xyz/post/185195398930/why-you-should-use-git-pull-ff-only-git-is-a

VSCode’s git sync worked well until recently, however `[pull]` → `ff = only` was set on my machine for quite a while. Looks like there was a change in actions behind VSCode’s UI, which did not account for a possible git preference. VSCode 1.61.2 calls `git pull --tags origin master` first, which is where the process gets stuck, even when there are no commits to fetch.

In the meantime, I’m running `git push` from a terminal as a workaround.

**Comment by JBlond** [comment] 2021-10-30 19:39
You are right, I have the fast forward option set. I didn't have that problem with VSCode before. I have that option since August last year. So that is a new behaviour

**Comment by JBlond** [comment] 2021-11-10 14:17
I found out what causes the issue.
It is the order. First, you do a local commit. Then VSCode does a git pull --tags origin BRANCHNAME. Of cause, it can't do that, since your local branch is ahead of the remote.

this happens when you have ff only in your git settings.

```ini
[pull]
	ff = only

```

**Comment by BeardedDaddy** [comment] 2021-11-12 07:54
Thanks for the tip!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vbrozik** [comment] 2021-11-16 11:17
This seems to be related to #135186 - there is a bug in Git 2.33.1 (limiting pull.ff=only functionality) which should have been fixed in 2.40.

**Comment by JBlond** [comment] 2021-11-16 11:28
I can confirm, that it works.

**Comment by kachkaev** [comment] 2021-11-16 12:16
Upgrading to git 2.34.0 and restarting VSCode helped me as well 🎉

**Closed** 2021-11-23 15:17 UTC
Labels: bug, upstream, git
