### ISSUE TITLE
Code format stopped working

### ISSUE THREAD

**Issue by Sampo123** [Microsoft/vscode#6801] opened 2016-05-24 13:32 UTC
- VSCode Version: 1.0.0
- OS Version: Debian Jessie

Steps to Reproduce:

Really hard to say once again. Everything was fine for a week or so but then the code format just does nothing. Which is a bitch. Also seems to start with random indentation time to times when for example { is added and enter pressed. 

Only error I got from the developer console is this:

/usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:1232
Grammar is in an endless loop - case 1

I know that these reports without real "how to reproduce" are sometimes a bit useless but just reporting so that somebody could help or take a note.

**Comment by aeschli** [comment] 2016-05-24 14:29
With what languages are you see this?
When format stops working, are other features still doing fine? E.g. Code completion, hovers....

**Comment by Sampo123** [comment] 2016-05-24 17:23
I'm using it with JavaScript. Intellisense and everything else are pretty much fine and even error checking works at normal level. Just the format stopped working. Only other noteworthy thing  is that VS Code seems to be bit off with indentation also at some points. Like when adding a curly bracket at the end of the line and then the cursor is between the curly brackets and I press enter it indents the bracket even though it kind of should not. But this does not seem to happen always. 

Is the error message any related? Could there be some debug flag or something that I could enable and see some explanation why nothing is happening when I try to format the code?

**Comment by aeschli** [comment] 2016-05-25 07:10
The error message is likely not related, but also very interesting. To find out more about it we would need the content of the file at that time.

**Comment by dbaeumer** [comment] 2016-05-25 07:52
@Sampo123 can you reproduce the formatting problem locally. If so can you please do the following.
- enable TS/JS logging via the setting:
```json
{
	"typescript.tsserver.trace": "messages"
}
```
- open the JS showing the behavior
- Bring Output view to front
- switch to channel typescript
- format the file
- attach the output to this issue.

**Comment by Sampo123** [comment] 2016-05-25 07:54
Hey, 

Thanks for your replies. I'll do that and get back to you this evening. I'm on other projects today so I'll need to do this when I get off so I'll try to get back to you later today, like in 7 hours or so :)

**Comment by OldrichDlouhy** [comment] 2016-05-25 10:33
I am getting the same issue with editing typescript ts and tsx files. Restarting the VS Code helps in some cases.

This is the text from the Output view:

Sending request: quickinfo (5255). Response expected: yes. Current queue length: 0
Response received: quickinfo (5255). Request took 26 ms. Success: false . Message: No content available.
Sending request: definition (5256). Response expected: yes. Current queue length: 0
Response received: definition (5256). Request took 27 ms. Success: false . Message: No content available.
Sending request: format (5257). Response expected: yes. Current queue length: 0
Response received: format (5257). Request took 4 ms. Success: false . Message: Error processing request. Debug Failure. False expression:

**Comment by dbaeumer** [comment] 2016-05-25 12:54
Actually I looks like the tsserver 'lost' the content of the file. Moving to the TS team.

**Comment by Sampo123** [comment] 2016-05-27 07:05
Same kind of behavior here as OldrichDlouhy said. It seems to have gone away for now. I'll get back when it comes back as it seems to be recurring problem.

**Comment by dbaeumer** [comment] 2016-05-27 07:56
@Sampo123 when you see the bahaviour could you please provide a trace as well to ensure it is the same root cause.

**Comment by leegee** [comment] 2016-06-09 10:12
`Format Code` often stops working here, on JavaScript.

Version info attached (would be nice if that dialog had text that could be clipboarded).

Doesn't work at all on the Insiders build (at least yesterday): says the extension is out of date, so I no longer use Insiders.

![image](https://cloud.githubusercontent.com/assets/512816/15926263/f6ace506-2e32-11e6-8a66-5cd3a522f735.png)

**Comment by dbaeumer** [comment] 2016-06-10 09:29
According to the trace this is a problem in the tsserver. Moving to the TS team.

@Sampo123 could you still provide the trace so that we can ensure your behaviour is caused by the same root cause

**Comment by dbaeumer** [comment] 2016-06-10 09:29
This issue was moved to Microsoft/TypeScript#9072

**Closed by dbaeumer** 2016-06-10 09:29 UTC
