### ISSUE TITLE
EH Debugging: breakpoints not hit in JavaScript

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33375] opened 2017-08-29 10:45 UTC
testing #33305 on Windows:

- create **JavaScript** hello world extension
- set breakpoints in lines 3, 11, 16, 20, 25
- press "F5" and wait until EH windows appears and is ready
- run "Hello" action

Observe: 
sometimes no breakpoint is hit, or only breakpoint on line 20 is hit.
I was never able to break on any other breakpoint.

**Comment by roblourens** [comment] 2017-08-29 21:59
Duplicate of #33373

**Closed by roblourens** 2017-08-29 21:59 UTC
Labels: bug, debug
