### ISSUE TITLE
Find-all-references takes me to the wrong location when there is collapsed code.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#19460] opened 2017-01-26 21:11 UTC
- VSCode Version: 1.9.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

* Write:
```ts
function f() {





    g();




}


function g() {
}
```

* Collapse `function f()`.
* Find-all-refs on `function g()`.
* Double-click on the first reference.

![screenshot](https://cloud.githubusercontent.com/assets/19274678/22350457/b120a238-e3c8-11e6-9201-4f81c7332f0d.jpg)

This is just a simple example. My real problem is that in a large document with lots of collapsed code, I get taken to the wrong location when navigating with find-all-refs.

**Comment by mousetraps** [comment] 2017-01-27 01:16
I can also reproduce this - what's particularly concerning is the random space this action adds to the editor between lines 8 and 9 - can't seem to get rid of it.

**Comment by alexandrudima** [comment] 2017-02-24 16:57
Mitigated with e96df57, but the arrow doesn't show up in the right position (due to how folding unfolds)

**Comment by alexandrudima** [comment] 2018-04-17 09:47
This has been fixed in the meantime:

![kapture 2018-04-17 at 11 47 01](https://user-images.githubusercontent.com/5047891/38862391-14a5040e-4235-11e8-9783-8ff1d048311b.gif)

**Closed by alexandrudima** 2018-04-17 09:47 UTC
Labels: bug, editor
