### ISSUE TITLE
editor loses focus when typing

### ISSUE THREAD

**Issue by JulieGirlGames** [microsoft/vscode#76220] opened 2019-06-27 00:48 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

The editor, specifically .TS file (don't know about other files), looses keyboard focus when typing faster. For example, cursor ends up several letters behind where I was typing without warning causing me to start typing in middle of words.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   115	   941	code main
    0	   115	   942	   gpu-process
    0	   328	   943	   window (game008.js — phaser-BxJS)
    0	   164	   963	     extensionHost
    0	   131	   967	       electron_node tsserver.js 
    0	    66	   994	         electron_node typingsInstaller.js typesMap.js 
    0	    33	   968	       electron_node server.js 
    0	    98	   971	       electron_node tslintServer.js 
    0	    82	  1246	       electron_node server.js 
    0	    49	   964	     watcherService
    0	   131	   990	   shared-process
    0	   770	  5532	   window (playGame.ts — jgg-4096)
    0	   229	  5533	     extensionHost
    0	   246	  5535	       electron_node tsserver.js 
    0	    82	  5568	         electron_node typingsInstaller.js typesMap.js 
    0	    49	  5536	       electron_node server.js 
    0	   229	  5539	       electron_node server.js 
    0	    82	  5540	       electron_node tslintServer.js 
    0	    49	  5579	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5533
    0	    49	  5534	     watcherService
    0	     0	  6651	     /bin/zsh -l
    0	    33	  6721	     searchService
    0	    82	  7139	   window (Issue Reporter)
    0	     0	  7141	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (playGame.ts — jgg-4096)
|  Window (game008.js — phaser-BxJS)
|    Folder (phaser-BxJS): 13 files
|      File types: js(8) json(2) md(1) html(1) png(1)
|      Conf files: package.json(1)
|    Folder (jgg-4096): 1471 files
|      File types: json(1435) ts(16) DS_Store(4) png(4) js(3) map(3) html(2)
|                  md(1) ico(1) gitignore(1)
|      Conf files: package.json(1) tsconfig.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
swift|Kas|0.0.3
json-to-ts|Mar|1.5.5
vscode-todo|Mat|0.8.0
jsx|Twe|0.0.1
vscode-file-peek|abi|1.0.1
typescript-react-snippets|abo|0.2.0
vscode-caniuse|aga|0.5.0
react-toolbox-snippets|ale|0.12.0
ng-template|Ang|0.800.0
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.18.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
vscode-ionic-snippets|fiv|1.1.0
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
emoji-code|idl|0.7.5
icon-fonts|idl|2.1.5
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|8.1.1
refactorix|kri|0.3.6
font-awesome-codes-css|med|0.1.1
vscode-scss|mrm|0.6.2
python|ms-|2019.6.22090
node-debug2|ms-|1.33.0
debugger-for-chrome|msj|4.11.5
vscode-react-native|msj|0.9.3
vscode-jest|Ort|2.9.2
polacode|pnp|0.3.2
quicktype|qui|12.0.46
vscode-bolt-language|smk|0.0.4
language-stylus|sys|1.11.0
react-beautify|tai|0.3.0
open-in-browser|tec|2.0.0
react-redux-es6-snippets|tim|2.1.0
vsfire|tob|1.4.1
lodash-snippets|tom|1.0.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
markdown-all-in-one|yzh|2.4.0
propertylist|zho|0.0.2

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2019-06-27 20:30
possible duplicate of https://github.com/microsoft/vscode/issues/71238

**Closed** 2019-07-25 21:42 UTC
Labels: *duplicate, bug, editor-core
