### ISSUE TITLE
JUpitere note books bank cells

### ISSUE THREAD

**Issue by yashmakwana0702** [microsoft/vscode#173517] opened 2023-02-06 04:50 UTC
Type: <b>Bug</b>

When I am using Jupiter notebooks some of the cells for code are hidden they are there but i can see the code.It had a hide fearture for whee only first line is visible with ... at the end to view full code now there is nothing.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.24GB free)|
|Process Argv|--crash-reporter-id c4693c3c-06ee-44c7-90e2-8c6832f85998|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|3.75GB (2.40GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0
atlascode|atl|3.0.1
gitlens|eam|13.2.0
outline-map|Ger|0.8.1
isort|ms-|2022.8.0
python|ms-|2023.3.10341119
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-rsp-ui|red|0.23.13
vscode-yaml|red|1.11.0
intellicode-api-usage-examples|Vis|0.2.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by TheProjectsGuy** [comment] 2023-02-06 07:04
@yashmakwana0702 Does it look like this issue: https://github.com/microsoft/vscode/issues/173300?

**Comment by rebornix** [comment] 2023-02-06 17:25
/duplicate of https://github.com/microsoft/vscode/issues/173590

**Closed by rebornix** 2023-02-06 17:25 UTC
Labels: bug
