### ISSUE TITLE
Allow users to block notifications from extensions.

### ISSUE THREAD

**Issue by samoldenburg** [microsoft/vscode#79645] opened 2019-08-22 14:10 UTC
Recently a plugin I use decided to start spamming notifications (https://github.com/bmewburn/vscode-intelephense). The plugin author does not want to remove them, but it is annoying for end users who still want to use the plugin to have to be harassed by a  plugin basically requesting payment for a premium license key daily.

I'm suggesting that VSCode allow users to block notifications entirely for an extension. This could be added to the little gear icon that pops up when a notification is displayed (and honestly, I was kind of surprised that option didn't exist already). Alternatively, it could be added to the gear in the extensions list as well if you want to allow users to re-enable/block from there.

![image](https://user-images.githubusercontent.com/6740074/63521688-8ec9db00-c4bc-11e9-9230-b032b0c3ce2d.png)

**Comment by RMacfarlane** [comment] 2019-08-22 14:26
Duplicate of https://github.com/microsoft/vscode/issues/41767

**Closed** 2019-08-22 14:27 UTC
Labels: *duplicate
