### ISSUE TITLE
"No timeline information was provided." for git history

### ISSUE THREAD

**Issue by Champitoad** [microsoft/vscode#99523] opened 2020-06-06 15:28 UTC
Issue Type: <b>Bug</b>

Normally, viewing a file tracked in git in the editor would fill the timeline with the git history of this file. I'm pretty sure it worked on my system at some point, but now whatever git-tracked file I open, I never get the timeline.

EDIT: it happens to work for some git repositories, i.e. if I just initialize one with simple text files.

EDIT2: now I managed to make it work for the problematic repositories by moving them in my home directory.

EDIT3: now it works for the original copies of the problematic repositories... not sure if we should keep the issue open, since it was still an odd behavior that someone else might encounter?

VS Code version: Code - OSS 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-17T22:31:53.325Z)
OS version: Linux x64 5.6.11-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (1.35GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions: none

**Comment by Champitoad** [comment] 2020-06-09 12:17
Ok I think I found the issue: when I open the folder using a path containing symlinks, I don't get the timeline, but I do if the path is free of symlinks. I was able to reproduce this with a fresh git repo, e.g.:
```bash
mkdir test
ln -s test link_to_test
cd test
git init .
touch foo
git add foo
git commit -am "Init"
echo "bar" > foo
git commit -am "Foo bar"
```
Then launching command `File: Open Folder...` on `test` I get the timeline, but not on `link_to_test`.

**Comment by mrdc** [comment] 2020-09-18 11:26
I'm having the same issue with Timeline - can confirm that it's somehow related to symlinks.

**Comment by mrdc** [comment] 2020-09-25 12:56
It self-fixed, then again stopped working - the same folders with symlinks. VS Code 1.49.1 and 1.49.2.

**Comment by mrdc** [comment] 2020-11-06 09:43
BTW GitLens works fine - everything is shown. But VS Code Timeline is empty

**Comment by mrdc** [comment] 2020-11-06 15:54
The same issue with the latest 1.51.0 update on Win 10 x64 1909.

**Comment by mrdc** [comment] 2020-11-07 21:01
Some update:

When I open Source Control -> Changes -> Click on changed file -> Diff File is Opened (Working Tree) and then Timeline starts to work - I see all my previous commits.

Repo is local with symbolic links in path
Git 2.29.1.windows.1
VS Code 1.51.0
Win 10 x64 1909

**Comment by rdanter** [comment] 2020-11-26 13:38
I see the same issue. Opening the workspace by browsing from the root works fine, but if I follow a symlink from my home dir then I see no timeline. I think that fairly conclusively points to symlinks being the cause somehow.

**Comment by NZambranoc** [comment] 2022-08-26 03:12
Same issue. 

doing what @mrdc  recommended makes it work.

**Comment by noontz** [comment] 2023-01-20 16:38
Same issue on some files, but not all

**Comment by J-Sorenson** [comment] 2023-02-07 23:21
Still getting intermittent issues with VS Code v1.72.2.  It's difficult to find a pattern on why it works with some files over others.

**Comment by OKRUgit** [comment] 2023-02-08 18:50
После добавления символических ссылок(linux) в домашнюю папку для удобства, шкала отказалась работать

**Comment by rrthomas** [comment] 2023-04-12 11:10
Indeed, it seems to be that it can't cope with symlinks. As reported by @Champitoad, if I re-open my workspace with the canonical path to it (which is quite inconvenient), I get the timeline information.

**Comment by lszomoru** [comment] 2023-12-12 09:52
Since the issue was last updated, we have added support for git repositories that have a symbolic link on their path. I will go ahead and optimistically close this issue, but in case you are still able to reproduce this with the latest version of VS Code please reopen the issue. Thanks!

**Closed by lszomoru** 2023-12-12 09:52 UTC
Labels: bug, timeline, timeline-git
