### ISSUE TITLE
Panel seems to overlap to the sidebar when sidebar is right

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37244] opened 2017-10-31 11:03 UTC
Testing: https://github.com/Microsoft/vscode/issues/36906

Steps to Reproduce:

1. put the sidebar to the right
2. put the panel vertically

It looks like some pixels of the panel overlap into the sidebar (see the scrollbar):

![image](https://user-images.githubusercontent.com/900690/32220826-780a93e6-be33-11e7-9ae8-63ad82ee4026.png)

**Comment by isidorn** [comment] 2017-10-31 14:39
I can not reproduce this. On what os are you and are you always seeing this?
If you inspect the elements do you see something which is clearly off?

**Comment by bpasero** [comment] 2017-10-31 15:10
@isidorn I tested all of the panel UX on Windows. I am always zoomed in +1 so maybe that is related.

**Comment by isidorn** [comment] 2017-11-01 10:31
@bpasero this is probably a duplicate of #37262
Can you please retest this with latest from source. Thanks a lot

**Closed by isidorn** 2017-11-01 10:31 UTC
Labels: needs more info

**Comment by bpasero** [comment] 2017-11-01 11:25
@isidorn seems better now

![image](https://user-images.githubusercontent.com/900690/32272738-ae1b0bb0-beff-11e7-9330-6526389fc04c.png)
