### ISSUE TITLE
Blinking window in fullscreen mode

### ISSUE THREAD

**Issue by limbosounds** [microsoft/vscode#37965] opened 2017-11-09 17:14 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
vscode-docker|Pet|0.0.21
sass-lint|gle|0.0.4
azure-account|ms-|0.1.3
sass-indented|rob|1.4.5
vscode-multiclip|sle|0.1.3

(22 theme extensions excluded)

---

Steps to Reproduce:

1. Go to Fullscreen mode (F11)
2. Hover on folder, file or (sic!) any block with title attribute in Chrome
3. Wait until title appears
4. Move mouse cursor out from the element

The result is the VSCode window blinks 1 time (per each 1-4 manipulation) - disappears for a few milliseconds and then appears again.

**Comment by anguspiv** [comment] 2017-11-09 18:19
Having the same issue:

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open VSCode
2. Click the maximize button in the top left corner of the window


Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-11-10 16:45
Can you also reproduce this with Chrome?
Can you also reproduce this with a barebone electron application?

@bpasero you might have additional questions

**Comment by bpasero** [comment] 2017-11-11 08:18
@antony-chopin does it reproduce when you run "`code --disable-gpu`"?

**Comment by antony-chopin** [comment] 2017-11-11 11:06
Ok, there is more information.

1. @isidorn The bug is **not** reproducible in Chrome. Can't say anything about another electron applications 'cause I have no it.
2. The bug appears only after appearing modals (like confirmation of moving/deleting files)
3. @bpasero The bug is **not** reproducible with `--disable-gpu`

I suppose, the bug is not reproducible in Chrome in case of absent any modals :)

**Comment by jeffrey-igaw** [comment] 2017-11-11 18:45
- Code Version : `1.18.0`, `commit : dcee2202`
- Node : 7.9.0
- Windows : Windows 10 Pro, 1709, 17025.1000
---

Yeah me too, but its not reproduced with `--disable-gpu`

**Comment by stanf0rd** [comment] 2018-03-25 19:55
The same issue on Ubuntu 18.04-beta, not reproduced with ```--disable-gpu```

**Comment by SerhiiCho** [comment] 2018-09-13 10:49
The same problem on Ubuntu 18.04, blinking in full screen mode when hover over a folder. It's been a while since the issue and nothing solved

**Comment by isidorn** [comment] 2019-10-08 09:58
Might be fixed on insiders with latest chrome, try it out in a couple of days when we jump on Chrome 71

**Closed** 2019-10-08 09:58 UTC
Labels: *out-of-scope, electron, upstream

**Comment by limbosounds** [comment] 2019-10-10 06:54
Bug is not appearing anymore, BTW :)

**Comment by isidorn** [comment] 2019-10-10 07:45
Great, thanks for letting us know.
