### ISSUE TITLE
Format on save no longer working if more than 1 formatter is available

### ISSUE THREAD

**Issue by Eldair** [Microsoft/vscode#70965] opened 2019-03-22 15:26 UTC
Issue Type: <b>Bug</b>

Format on save no longer working if more than 1 formatter is available.
Running format document command gives a list of formatters and by selecting the one I want it works. Is there some new option for defining default formatter?

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.3.0
color-info|bie|0.5.0
vscode-intelephense-client|bme|1.0.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.5.1
vscode-phpmd|eco|1.1.0
EditorConfig|Edi|0.13.0
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
phpcs|ika|1.0.5
autofilename|Jer|0.1.3
vscode-phpfmt|kok|1.0.30
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.6
debugger-for-chrome|msj|4.11.3
vetur|oct|0.17.0
material-icon-theme|PKi|3.6.3
polacode|pnp|0.2.2
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.7
vscode-fileutils|sle|2.13.5
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

(7 theme extensions excluded)

</details>

**Comment by iansan5653** [comment] 2019-03-22 18:09
Related discussion here: https://github.com/Microsoft/vscode/issues/41882#issuecomment-475311285

**Comment by jrieken** [comment] 2019-03-25 08:02
/duplicate of https://github.com/Microsoft/vscode/issues/41882#issuecomment-475281706

**Closed** 2019-03-25 08:03 UTC
Labels: *duplicate

**Comment by jrieken** [comment] 2019-03-25 08:04
@Eldair Because format on save is without UI we cannot show a picker. We can continue to pick some formatter but IMO it would be highly inconsistent. We are open for suggestions but the goal is that users configure formatters so that only one is active per file

**Comment by jrieken** [comment] 2019-03-25 13:29
fyi - I have pushed a change that picks the _first_ formatter for format on save. when this happens a status bar message is being printed, telling you which formatter has been picked

**Comment by Eldair** [comment] 2019-03-25 20:27
Hi,

Thank for the info and the update. I understand what the issue is, I thought there would be an option to select a formatter per language vs disable on extension which offer it as side effect (if a sole purpose of an extension is formatting than I agree it should be disabled if not in use).
Just an idea: dropdowns for all languages with a list of available formatters for selecting a desired one.
