### ISSUE TITLE
vscode insiders (after update) doesn't highlight and tell about TS errors

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#12441] opened 2016-09-22 10:57 UTC
- VSCode Version: insiders
- OS Version: windows 10

After todays update of vscode insiders stopped to highlight and tell about TS errors in some projects:

![image](https://cloud.githubusercontent.com/assets/736697/18745730/da6da6b2-80dc-11e6-9ffd-33c2d31a819c.png)

And this is another project (small) where errors are highlighted:
![image](https://cloud.githubusercontent.com/assets/736697/18745761/f517e91e-80dc-11e6-8a78-17c9b60b0c1a.png)

Both 2.1dev version of TS.

What may be the reason?

**Comment by whitecolor** [comment] 2016-09-22 14:01
it actually doesn't work in some files, and works in other of the same project, files are located in the same directory. And it all worked before update.

Insiders:
![image](https://cloud.githubusercontent.com/assets/736697/18750913/7fd7f42c-80f6-11e6-904c-c1d239ddf4ca.png)

The same files when project opened with stable VsCode:
![image](https://cloud.githubusercontent.com/assets/736697/18751045/f6e82b54-80f6-11e6-9664-d97cf3f66e20.png)

**Comment by chrmarti** [comment] 2016-09-22 17:11
Could you run with TS tracing enabled and past the output in the Output panel's TypeScript channel here:
```
"typescript.tsserver.trace": "verbose"
```

Could be related: #12390

**Comment by whitecolor** [comment] 2016-09-22 18:05
@chrmarti how to open and see Output panel's TypeScript channel?

**Comment by chrmarti** [comment] 2016-09-22 21:14
Yes, that goes in the settings.json. You can then open the Output panel with Ctrl+Shift+U and then switch to the TypeScript channel using the drop-down in the top-right corner of the Output panel.

**Comment by whitecolor** [comment] 2016-09-22 22:18
https://gist.github.com/whitecolor/92ee018b03085d7a34666f010a1c2860

**Comment by chrmarti** [comment] 2016-09-23 17:52
@whitecolor Thanks. I don't see any error in the terminal.ts though. Could you post the trace from when the bug shows? (E.g.: Change terminal.ts to have an error that is then not shown as such.)

**Comment by whitecolor** [comment] 2016-09-23 19:57
I'm not sure what I have to do for that? In the gist there is a file:
```
..-taskmate/src/drivers/terminal.ts",
```
And error are not reported in that file.

**Comment by chrmarti** [comment] 2016-09-23 22:00
I looked at the content of terminal.ts and did not see anything that I'd expect to trigger a compile error. Maybe I missed it?

**Comment by whitecolor** [comment] 2016-09-24 10:10
Ok I added:
https://gist.github.com/whitecolor/e0b42d8cb85f9edf5c79ef05432421c1

![image](https://cloud.githubusercontent.com/assets/736697/18807751/f7b5410c-8268-11e6-9c09-7269cee78ca1.png)

**Comment by whitecolor** [comment] 2016-09-25 07:08
Is this enoght? I actually encountered the same problem with stable vs code with another "import combinations", it looks weird.

**Comment by chrmarti** [comment] 2016-09-26 17:43
I don't see the 'x' being sent over, maybe the trace didn't capture that. There were other reports around TypeScript recently. @waderyan Is this one known?

**Comment by waderyan** [comment] 2016-09-26 17:45
@chrmarti I haven't seen this issue..

**Comment by chrmarti** [comment] 2016-09-26 18:02
@whitecolor Could you take another trace when you restart VS Code with no editor open and then open the file with the 'x' error already in? That should show a trace sending the entire file over and then asking for errors. Thanks.

**Comment by chrmarti** [comment] 2016-09-26 18:03
@whitecolor Also: Could you use the latest insider to make sure you have the latest fixes?

**Comment by whitecolor** [comment] 2016-09-26 20:44
@chrmarti updated, issue persist, made as you said
![image](https://cloud.githubusercontent.com/assets/736697/18851105/e42930f2-8453-11e6-8f5a-6f73b3f70a20.png)

gist:
https://gist.github.com/whitecolor/fbe761b635be0776d0cc80322d16db9b

**Comment by waderyan** [comment] 2016-09-26 21:34
@whitecolor thank you for working with us on solving this issue. 

What extensions do you have installed in stable and in insiders? 
Note that you can run code without any extensions by opening from the command line with `--disable-extensions` option. 

Can you give me some code I can clone or copy and paste into my editor? I am not able to reproduce. 

Here is what I am seeing in Stable right now.

![image](https://cloud.githubusercontent.com/assets/2449568/18852658/3d8b175e-83f6-11e6-85c5-6ed83e0fc911.png)

And this is what I see in Insiders. 

![image](https://cloud.githubusercontent.com/assets/2449568/18852647/34e171e8-83f6-11e6-8d4f-28c9874388c7.png)

**Comment by whitecolor** [comment] 2016-09-27 12:43
@waderyan
Hm I'm not sure but after latest update it seem to work alright, If I encounter this again I will try to figure out what extension may cause it.

**Comment by waderyan** [comment] 2016-09-27 16:41
Ok. Closing as fixed. Reopen if you discover it again.

**Closed by waderyan** 2016-09-27 16:41 UTC
Labels: bug, needs more info, typescript

**Comment by whitecolor** [comment] 2016-11-07 20:52
Seem to have the same issue in the project, seem ts server doesn't work properly or something.
![image](https://cloud.githubusercontent.com/assets/736697/20075294/762e9b1e-a555-11e6-85a2-2664a33d974d.png)

Using 2.1.0-dev201651105

How can I debug it, maybe get more informative output from the console?
