### ISSUE TITLE
Can't format sass files

### ISSUE THREAD

**Issue by saradeakin** [Microsoft/vscode#36092] opened 2017-10-11 18:48 UTC
Shift+Alf+F won't work in a sass file, it adds "Ï" to the code instead of formatting

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.10.0
vscode-css-formatter|aes|0.0.2
vscode-stylesheet-formatter|dba|0.2.0
vscode-style-formatter|dwe|1.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-sass-format|sas|1.1.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by smlombardi** [comment] 2017-10-11 18:50
shift-alt-F never worked with Sass files, AFAIK.  I installed [Stylefmt](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt) at the very beginning, and use that.

**Comment by aeschli** [comment] 2017-10-12 13:27
duplicate of #9450.

Scss formatting is provided by extensions..

**Closed by aeschli** 2017-10-12 13:27 UTC
Labels: css-less-sass
