### ISSUE TITLE
Java General profile template doesn't include Test Runner for Java even though it is include in the Extension Pack for Java

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#180589] opened 2023-04-22 03:31 UTC
- VS Code Version: 1.78 Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Profiles > Create Profiles
2. Select the Java General profile from the dropdown

The Extension Pack for Java is included and I believe that is where most of the other extensions are coming from.

![image](https://user-images.githubusercontent.com/12818376/233759775-27c907b9-6096-4955-a098-6b6c4b5cf348.png)

However the Extension Pack for Java includes the Test Runner for Java but it is not present in the Java General profile.

![image](https://user-images.githubusercontent.com/12818376/233759921-e11d5a6b-77ab-4fbf-a03c-02515e781333.png)

**Comment by isidorn** [comment] 2023-04-22 08:31
Sounds like a duplicate of https://github.com/microsoft/vscode/issues/180338

**Comment by isidorn** [comment] 2023-04-26 08:40
Nick from java team confirmed that he was trying out the profile. And that he might have by accident removed some extensions. He just sent an updated profile. So I will update them to tackle this issue.

**Comment by isidorn** [comment] 2023-04-26 13:39
Should be fixed with a PR I created. I expect this to land very soon. Thus closing.

**Closed by isidorn** 2023-04-26 13:39 UTC
Labels: bug, user-profiles
