### ISSUE TITLE
Delete key not working in file explorer

### ISSUE THREAD

**Issue by lifeofguenter** [microsoft/vscode#76880] opened 2019-07-08 13:29 UTC
- VSCode Version: 1.36.0 (x64)
- OS Version: Debian 10 (buster)

Steps to Reproduce:

1. Go to workspace / file explorer
2. Click on file
3. Press "del" on keyboard

Does this issue occur when all extensions are disabled?: Yes

Deleting the file via right-click-menu works, and also generally I can delete stuff with the keyboard (for example lines in the editor)

![Screenshot from 2019-07-08 15-28-22](https://user-images.githubusercontent.com/241073/60813973-0f46ad80-a195-11e9-943d-eb2e3786b672.png)

**Comment by isidorn** [comment] 2019-07-08 13:36
Duplicate, will be fixedi n the recovery release

**Closed by isidorn** 2019-07-08 13:36 UTC

**Comment by sgehrman** [comment] 2019-07-08 18:58
same problem

**Comment by matthiasdailey-ccri** [comment] 2019-07-10 17:22
Duplicate of https://github.com/microsoft/vscode/issues/76514
