### ISSUE TITLE
Custom menu: Use mouse down to activate menu

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55682] opened 2018-08-02 16:21 UTC
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2
Date: 2018-08-02T05:18:18.450Z

My first impression when using the custom menu was that its use feels a bit sluggish. I now think that's because on the Mac and on Elementary OS the menus appear on mouse down, while our menu appears on mouse up. Is that intentional?

**Comment by sbatten** [comment] 2018-08-08 02:08
essentially a duplicate of #52907

**Closed by sbatten** 2018-08-08 02:08 UTC
