### ISSUE TITLE
Could not load 'markdown.styles': *.css

### ISSUE THREAD

**Issue by sakronos** [Microsoft/vscode#71851] opened 2019-04-06 13:13 UTC
- VSCode Version:Code 1.33.0 (0dd516d, 2019-04-04T15:11:32.076Z)
- OS Version:Windows 10 1809 x64

settings.json is as follows
```
{
    "workbench.colorTheme": "Markdown Editor Yellow",
    "editor.fontFamily": " PingFang SC, ‘Hiragino Sans GB’, Helvetica ",
    "editor.fontSize": 16,
    "markdown.styles": [
        "md.css"
    ],
}
```
Steps to Reproduce:

1.Open a markdown file, and click open Preview to the Side
2.visual studio code NOTIFICATIONS show the warning: Could not load 'markdown.styles': md.css

In the previous version, it works properly.

**Comment by Yero-dev** [comment] 2019-04-06 13:41
.

**Comment by mjbvz** [comment] 2019-04-08 19:00
Duplicate of #71802

**Closed by mjbvz** 2019-04-08 19:00 UTC
Labels: new release
