### ISSUE TITLE
CompletionItem kind uses same icon for "property" and for "method"

### ISSUE THREAD

**Issue by APerricone** [Microsoft/vscode#65624] opened 2018-12-23 18:01 UTC
- VSCode Version: 1.30.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch a debugger
2. try to use autocomplete inside the debugger
3. see that alla symbols are the same

Does this issue occur when all extensions are disabled?: No

I am developing a debugger extension, and inside the autocomplete I see that the symbol is all the same:
![image](https://user-images.githubusercontent.com/22457168/50386295-41eef400-06e4-11e9-861c-05fed47ac656.png)

when the completionItem.type value is correctly valued:

![image](https://user-images.githubusercontent.com/22457168/50386364-10c2f380-06e5-11e9-9ad5-0d34809e58e5.png)

**Comment by APerricone** [comment] 2018-12-24 11:01
maybe is it a "feature request"?

**Comment by isidorn** [comment] 2018-12-27 09:40
I can reproduce this.

@jrieken the issue here is that no matter what `kind` I pass as the `CompletionItem` I always get the wrench icon.
Does the `kind` define what icon is used? Or is there somewhere else that I need to opt-in to the completion icons?

Code pointer https://github.com/Microsoft/vscode/blob/7a0c82612117d2e386d4cde10b485db055c87b61/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L485

**Comment by jrieken** [comment] 2018-12-27 10:34
Yes, `kind` defines the icon

**Comment by APerricone** [comment] 2018-12-27 10:45
maybe it is not relevant, but in [debugProtocol.ts#L1509](https://github.com/Microsoft/vscode-debugadapter-node/blob/64665fe18a0316b2a871df4b36cff214c28d2598/protocol/src/debugProtocol.ts#L1509) there is no kind...

**Comment by isidorn** [comment] 2018-12-27 11:13
Ok, after more investigation the issue is that the same icon is being used for "property" and for "method". For all other kinds the icon is diferent. Renaming and forwarding to @jrieken to decide what to do here.
@APerricone please use some other icon kind for now https://github.com/Microsoft/vscode/blob/2804e0d20511f6d0a826739efda3a5e0a75091a8/src/vs/editor/common/modes.ts#L328

**Comment by jrieken** [comment] 2018-12-27 11:56
That has always been like that. @isidorn do you even run your code?

**Comment by isidorn** [comment] 2018-12-27 12:50
Ok so it is as designed. Closing

**Closed by isidorn** 2018-12-27 12:50 UTC
Labels: under-discussion
