### ISSUE TITLE
c++ file open problem

### ISSUE THREAD

**Issue by guleryuz** [microsoft/vscode#76929] opened 2019-07-09 05:25 UTC
Issue Type: <b>Bug</b>

viusal studio code freezes when trying o open this c++ file. no c++ extension installed.
os: ubuntu

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4062)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.52GB (3.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
macros|ged|1.2.1
prettify-json|moh|0.0.3
vscode-language-pack-tr|MS-|1.36.2
mssql|ms-|1.6.0
python|ms-|2019.6.22090
napamacro-debug|nap|1.0.6
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.8.1
vscode-manifest-yaml|Piv|1.8.1
vscode-spring-boot|Piv|1.8.1
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5

</details>

**Comment by guleryuz** [comment] 2019-07-09 05:28
// Retrieve the variable named "data"
        NcVar data=dataFile.getVar("data");
        if(data.isNull()) return NC_ERR;
        data.getVar(dataIn);

        // Check the values.
        for (int i = 0; i < NX; i++)
            for (int j = 0; j < NY; j++)
                if (dataIn[i][j] != i * NY + j)
                    return NC_ERR;

        // The netCDF file is automatically closed by the NcFile destructor
        cout << "*** SUCCESS reading example file simple_xy.nc!" << endl;

        return 0;
    }catch(NcException& e)
    {
        e.what();
        cout<<"FAILURE*************************************"<<endl;
        return NC_ERR;
   }
}

**Comment by guleryuz** [comment] 2019-07-09 05:29
/* This is part of the netCDF package.
   Copyright 2006 University Corporation for Atmospheric Research/Unidata.
   See COPYRIGHT file for conditions of use.

   This is a very simple example which reads a 2D array of
   sample data produced by simple_xy_wr.cpp.

   This example is part of the netCDF tutorial:
   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-tutorial

   Full documentation of the netCDF C++ API can be found at:
   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-cxx

   $Id: simple_xy_rd.cpp,v 1.5 2010/02/11 22:36:43 russ Exp $
*/

#include <iostream>
#include <netcdf>
using namespace std;
using namespace netCDF;
using namespace netCDF::exceptions;

// We are reading 2D data, a 6 x 12 grid.
static const int NX = 6;
static const int NY = 12;

// Return this in event of a problem.
static const int NC_ERR = 2;

int main()
{
    try
    {
        // This is the array we will read.
        int dataIn[NX][NY];

        // Open the file for read access
        NcFile dataFile("simple_xy.nc", NcFile::read);

        // Retrieve the variable named "data"
        NcVar data=dataFile.getVar("data");
        if(data.isNull()) return NC_ERR;
        data.getVar(dataIn);

        // Check the values.
        for (int i = 0; i < NX; i++)
            for (int j = 0; j < NY; j++)
                if (dataIn[i][j] != i * NY + j)
                    return NC_ERR;

        // The netCDF file is automatically closed by the NcFile destructor
        cout << "*** SUCCESS reading example file simple_xy.nc!" << endl;

        return 0;
    }catch(NcException& e)
    {
        e.what();
        cout<<"FAILURE*************************************"<<endl;
        return NC_ERR;
    }
}

**Comment by guleryuz** [comment] 2019-07-09 05:30
`/* This is part of the netCDF package.
   Copyright 2006 University Corporation for Atmospheric Research/Unidata.
   See COPYRIGHT file for conditions of use.

   This is a very simple example which reads a 2D array of
   sample data produced by simple_xy_wr.cpp.

   This example is part of the netCDF tutorial:
   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-tutorial

   Full documentation of the netCDF C++ API can be found at:
   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-cxx

   $Id: simple_xy_rd.cpp,v 1.5 2010/02/11 22:36:43 russ Exp $
*/

#include <iostream>
#include <netcdf>
using namespace std;
using namespace netCDF;
using namespace netCDF::exceptions;

// We are reading 2D data, a 6 x 12 grid.
static const int NX = 6;
static const int NY = 12;

// Return this in event of a problem.
static const int NC_ERR = 2;

int main()
{
    try
    {
        // This is the array we will read.
        int dataIn[NX][NY];

        // Open the file for read access
        NcFile dataFile("simple_xy.nc", NcFile::read);

        // Retrieve the variable named "data"
        NcVar data=dataFile.getVar("data");
        if(data.isNull()) return NC_ERR;
        data.getVar(dataIn);

        // Check the values.
        for (int i = 0; i < NX; i++)
            for (int j = 0; j < NY; j++)
                if (dataIn[i][j] != i * NY + j)
                    return NC_ERR;

        // The netCDF file is automatically closed by the NcFile destructor
        cout << "*** SUCCESS reading example file simple_xy.nc!" << endl;

        return 0;
    }catch(NcException& e)
    {
        e.what();
        cout<<"FAILURE*************************************"<<endl;
        return NC_ERR;
    }
}`

**Comment by guleryuz** [comment] 2019-07-09 05:30
/* This is part of the netCDF package.
	   Copyright 2006 University Corporation for Atmospheric Research/Unidata.
	   See COPYRIGHT file for conditions of use.

	   This is a very simple example which reads a 2D array of
	   sample data produced by simple_xy_wr.cpp.

	   This example is part of the netCDF tutorial:
	   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-tutorial

	   Full documentation of the netCDF C++ API can be found at:
	   http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-cxx

	   $Id: simple_xy_rd.cpp,v 1.5 2010/02/11 22:36:43 russ Exp $
	*/

	#include <iostream>
	#include <netcdf>
	using namespace std;
	using namespace netCDF;
	using namespace netCDF::exceptions;

	// We are reading 2D data, a 6 x 12 grid.
	static const int NX = 6;
	static const int NY = 12;

	// Return this in event of a problem.
	static const int NC_ERR = 2;

	int main()
	{
	    try
	    {
		// This is the array we will read.
		int dataIn[NX][NY];

		// Open the file for read access
		NcFile dataFile("simple_xy.nc", NcFile::read);

		// Retrieve the variable named "data"
		NcVar data=dataFile.getVar("data");
		if(data.isNull()) return NC_ERR;
		data.getVar(dataIn);

		// Check the values.
		for (int i = 0; i < NX; i++)
		    for (int j = 0; j < NY; j++)
		        if (dataIn[i][j] != i * NY + j)
		            return NC_ERR;

		// The netCDF file is automatically closed by the NcFile destructor
		cout << "*** SUCCESS reading example file simple_xy.nc!" << endl;

		return 0;
	    }catch(NcException& e)
	    {
		e.what();
		cout<<"FAILURE*************************************"<<endl;
		return NC_ERR;
	    }
	}

**Comment by alexr00** [comment] 2019-07-09 07:59
Duplicate of #76774
We rolled back the C++ grammar version match 1.35 so this will be fixed in 1.36.1. It is also already fixed in Insiders.

**Closed by alexr00** 2019-07-09 07:59 UTC
