### ISSUE TITLE
Strikeout CompletionItems (and Symbols?) that are deprecated

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode#50972] opened 2018-06-01 20:56 UTC
<kbd>Ctrl</kbd>+<kbd>Space</kbd> is nice and all but when you are new to a library you just see a list of functions and you won't realize that some of them are deprecated. Would it be possible to add a strikeout line via the `line-through` `text-decoration` or some kind of icon overlay to indicate that something is deprecated?

![image](https://user-images.githubusercontent.com/15629116/40863113-beefd204-65bc-11e8-913e-dc1dda2862e5.png)

**Comment by octref** [comment] 2018-06-01 23:19
@jrieken I'm interested in this too, for deprecated html/css properties.

**Comment by ivanvoznyakovsky** [comment] 2018-08-17 12:46
it'd also be great to strikeout deprecated props/methods in the editor itself like webstorm does it. ie
<img width="565" alt="screen shot 2018-08-17 at 13 29 37" src="https://user-images.githubusercontent.com/4233080/44264220-0c139d80-a222-11e8-8aa8-23f373195be9.png">

**Comment by jcrben** [comment] 2018-11-28 18:57
Raised a couple times previously:
* https://github.com/Microsoft/vscode/issues/31159
* https://github.com/Microsoft/vscode/issues/10316 - recommends using extension with textDecoration API https://github.com/Microsoft/vscode/issues/10316#issuecomment-238474701

**Comment by KamasamaK** [comment] 2018-12-12 20:30
@jcrben Those are issues for language support. This issue is more general, and I _think_ this is an issue to support the `deprecated` property on the completion and symbol items in the [LSP spec](https://microsoft.github.io/language-server-protocol/specification) with a visual change.

When this is done, I would expect more language support would follow. It's possible that some language servers already do set that property but you don't know since VS Code ignores it.

Specifically on those issues, I don't agree with the notion that it should be done in a separate extension or that it should use the decorations API. Deprecation is a standard practice for languages, and JavaScript/TypeScript have [JSDoc](http://usejsdoc.org/tags-deprecated.html) to determine this, which is already being parsed and used for other tags.

**Comment by Tyler-Murphy** [comment] 2019-07-12 13:06
I'd like something [similar to this](https://github.com/microsoft/vscode/issues/77239). I'd like to be able to prevent deprecated things from showing up in the list of suggestions at all.

**Comment by jrieken** [comment] 2019-07-26 14:49
@kamranayub work on this is sitting here: https://github.com/microsoft/vscode/tree/joh/completionsDeprecated.

**Comment by michaeljsalo** [comment] 2019-08-06 16:23
I'm currently seeing lots of deprecated items in JavaScript suggestion lists.  A string variable for example offers the following methods.  The first four on the list are deprecated.  Would be nice to get them out of the way.
<img width="415" alt="Screen Shot 2019-08-06 at 10 46 41 AM" src="https://user-images.githubusercontent.com/1945279/62556650-f6d0be00-b83a-11e9-9488-08fa18d147fd.png">

**Comment by jrieken** [comment] 2019-08-21 16:22
adding @octref since his CSS language brain has deprecation-information

**Comment by octref** [comment] 2019-08-22 05:40
CSS now looks like this. I don't know if this is possible, but a strikeout overlay on top of the completion item's icon would be much easier to see for me.

![image](https://user-images.githubusercontent.com/4033249/63488328-75e10b80-c463-11e9-8538-e2a31e0b139b.png)

**Comment by jrieken** [comment] 2019-08-22 08:14
Slightly improved version which

* shows the line through
* doesn't show match highlights (no bold)
* renders the item slightly opaque 

<img width="372" alt="Screenshot 2019-08-22 at 10 13 15" src="https://user-images.githubusercontent.com/1794099/63498090-77dbb680-c4c5-11e9-9281-3dd51a0db17b.png">

**Comment by jrieken** [comment] 2019-08-22 12:52
The analog thing for symbols in outline and breadcrumb pickers, not in breadcrumb itself tho. I believe that would be too noisy, esp since the editor (e.g the thing under cursor) will already be annotated as deprecated. 

<img width="399" alt="Screenshot 2019-08-22 at 14 49 34" src="https://user-images.githubusercontent.com/1794099/63515992-60fc8a80-c4ec-11e9-80f0-678bc923f018.png">

**Comment by fbricon** [comment] 2019-08-22 14:52
Testing on vscode-java with initial deprecated support in jdt.ls, in Insiders build ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8 :
<img width="726" alt="Screen Shot 2019-08-22 at 4 49 05 PM" src="https://user-images.githubusercontent.com/148698/63524762-da9c7480-c4fc-11e9-9f4b-95d1136d9603.png">

I'll keep testing with newer builds next week.

cc @akaroml

**Comment by rcjsuen** [comment] 2019-08-22 15:16
What a time to be alive...

**Comment by jrieken** [comment] 2019-08-26 07:41
Closing. We have the UX for outline, workspace symbols, and completions. The API is proposed and will be finalised in https://github.com/microsoft/vscode/issues/23927

**Closed by jrieken** 2019-08-26 07:41 UTC
Labels: feature-request, suggest

**Comment by fbricon** [comment] 2019-08-26 14:49
@jrieken I tested today's insiders build (185308c0dd317d73fe4c19dea347582dee9650de 2019-08-26T09:43:06.818Z)  and I no longer see the completion/symboles striked through O_o. Is there something I need to enable in my extension now?

**Comment by jrieken** [comment] 2019-08-26 15:01
What version of the proposed API did you code this against?

**Comment by fbricon** [comment] 2019-08-26 15:07
latest LSP release. Which adds the deprecated property to completion items, workspace and document symbols.  completion items worked last week, as per my screenshot.
I tried to add vscode.proposed.d.ts by calling `npx vscode-dts dev`. But I'm not sure where the file is supposed to go. In my project root? my project source folder? Either way I don't get the strikethroughs.

**Comment by fbricon** [comment] 2019-08-26 15:09
enableProposedApi is set to true too. Wasn't necessary last week.

**Comment by jrieken** [comment] 2019-08-26 15:19
> latest LSP release.

I don't think that's weird up (@dbaeumer) yet. It might have worked by accident because the first proposal used the same names. The proposed API (`CompletionItem.tags`, `SymbolInformation#tags`) is described here: https://github.com/microsoft/vscode/issues/23927

**Comment by fbricon** [comment] 2019-08-26 15:27
do you plan to get VS Code support the deprecated properties of the current LSP version?
On the Java side, those new tags are not yet supported by the LSP4J bindings, so it'll take us more time to have that deprecated support that way.

**Comment by jrieken** [comment] 2019-08-26 15:34
LSP and vscode.d.ts are two separate things. The LSP-vscode-client fulfils the vscode.d.ts-contract, e.g it will map the deprecated-field that LSP defines onto the completion item tag that vscode.d.ts defines. The sequence is that we finalise the API next milestone, that LSP adopts the new API, and that things then come together. 

Since you are on the LSP side and since to my knowledge deprecation is already supported there (but not yet wired up), there is nothing you have to do

**Comment by fbricon** [comment] 2019-08-26 15:39
ok, can you please let me know when this is wired up in vscode then?

**Comment by danielhofinger** [comment] 2019-08-26 15:42
Hi Fred,

can you please remove me from your “subscribed”-list?

Thanks.

Best,
Daniel

Daniel Hofinger
Founder & Managing Director, Hofinger Ventures UG
A Mörfelder Landstraße 6-8, 60598 Frankfurt am Main
M +49 177 8431872
E daniel@hofinger.xyz
W www.hofinger.xyz
Hofinger Ventures UG (haftungsbeschränkt), Luisenstraße 34, 60316 Frankfurt am Main; Geschäftsführer: Daniel Hofinger; Amtsgericht Frankfurt am Main; HRB 108730; USt.-IdNr.: DE312772958; Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren, Veröffentlichen sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. The information contained in this message is confidential or protected by law. If you are not the intended recipient (or have received this e-mail in error), please notify the sender and delete this message. Any unauthorized publishing or copying of this message or unauthorized distribution of the information contained in this e-mail is strictly prohibited.

**Comment by fbricon** [comment] 2019-08-26 15:49
I didn't add you. But you can unsubscribe from notifications from this issue by clicking on the "Unsubscribe" button [here](https://github.com/microsoft/vscode/issues/50972).

**Comment by akaroml** [comment] 2019-08-27 03:56
> I didn't add you. But you can unsubscribe from notifications from this issue by clicking on the "Unsubscribe" button [here](https://github.com/microsoft/vscode/issues/50972).

Hey Fred, I think the `enableProposedApi` is no longer needed because the changes are already in the latest release of the `vscode-languageclient v5.3.0-next.9`. Could you try to upgrade the client to see whether it works? Thanks.

**Comment by dbaeumer** [comment] 2019-08-27 07:06
@jrieken is correct. It is not wired up yet. I only wire up new API if it is at least released in a stable build. I don't make a dependency on Insider in LSP libs (I once did and it confused a lot of users).

However you can implement this yourself using a custom middleware if you really need to do so.

**Comment by danielhofinger** [comment] 2019-08-27 07:14
Hi Dirk,

please remove me from CC, thanks.

Best,
Daniel

Daniel Hofinger
Founder & Managing Director, Hofinger Ventures UG
A Mörfelder Landstraße 6-8, 60598 Frankfurt am Main
M +49 177 8431872
E daniel@hofinger.xyz
W www.hofinger.xyz
Hofinger Ventures UG (haftungsbeschränkt), Luisenstraße 34, 60316 Frankfurt am Main; Geschäftsführer: Daniel Hofinger; Amtsgericht Frankfurt am Main; HRB 108730; USt.-IdNr.: DE312772958; Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren, Veröffentlichen sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. The information contained in this message is confidential or protected by law. If you are not the intended recipient (or have received this e-mail in error), please notify the sender and delete this message. Any unauthorized publishing or copying of this message or unauthorized distribution of the information contained in this e-mail is strictly prohibited.

**Comment by dbaeumer** [comment] 2019-08-27 07:37
@danielhofinger you need to unsubscribe yourself from the issue using the GitHub UI.

**Comment by danielhofinger** [comment] 2019-08-27 07:56
Alright, thanks! @dbaeumer

**Comment by fbricon** [comment] 2019-08-27 09:06
> @jrieken is correct. It is not wired up yet. I only wire up new API if it is at least released in a stable build. I don't make a dependency on Insider in LSP libs (I once did and it confused a lot of users).
> 
> However you can implement this yourself using a custom middleware if you really need to do so.

I don't think I'm gonna start messing with custom middleware code (don't even know what to do). So I'll just wait for you to wire things up in the insiders build at least

**Comment by Tyler-Murphy** [comment] 2019-09-16 15:20
https://github.com/microsoft/vscode/issues/77239 was marked as a duplicate of this issue and closed.

@jrieken [said](https://github.com/microsoft/vscode/issues/77239#issuecomment-510750548):

> I'd say this is a dupe of #50972 and it would be us adding some API flag and then allows users to configure how the suggest UX is handling that flag

Does the closure of this issue address #77239? Should https://github.com/microsoft/vscode/issues/77239 be reopened?
