### ISSUE TITLE
希望可以一个窗口打开多个项目

### ISSUE THREAD

**Issue by senmeng** [Microsoft/vscode#25970] opened 2017-05-05 02:47 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|auto-rename-tag|formulahendry|0.0.11|
|composer|ikappas|0.5.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.59|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|cpptools|ms-vscode|0.11.0|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1.
2.

**Comment by Leedehai** [comment] 2017-05-05 04:13
**Translation of the issue's title**: I hope to open multiple projects in one window.

Comment: I guess it is designed by purpose such that one can open at most one project in one window.. In Visual Studio it is the same case.

**Comment by egamma** [comment] 2017-05-05 08:37
Duplicate of #396

**Closed by egamma** 2017-05-05 08:37 UTC
