### ISSUE TITLE
Code is still runing after close it

### ISSUE THREAD

**Issue by PeterMX** [Microsoft/vscode#7694] opened 2016-06-15 06:11 UTC
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open code use it as normal
2. close it and you have this  _/usr/share/code/code ./terminalProcess_ still runing

I don't know if this is a problem but I guess this isn't normal!
![code](https://cloud.githubusercontent.com/assets/9899682/16069690/072c4fcc-3296-11e6-9c8e-e848a2e52586.png)

**Comment by PeterMX** [comment] 2016-06-15 06:13
sometimes process is just _/usr/share/code/code_

**Comment by PeterMX** [comment] 2016-06-15 06:16
"Durmiendo" means "Sleeping" in english

**Comment by joaomoreno** [comment] 2016-06-15 08:46
Duplicate of #7527

**Closed by joaomoreno** 2016-06-15 08:46 UTC
Labels: bug
