### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by yonifra** [microsoft/vscode#104156] opened 2020-08-06 07:54 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200805

**Steps to reproduce crash**
1. Just reloaded VSC

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:102650:161)
    at resolveModuleNamesWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:102873:26)
    at resolveModuleNamesReusingOldState (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103023:19)
    at processImportedModules (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104446:35)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104182:17)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104416:21
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104411:16)
    at findSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104179:21)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:85
    at getSourceFileFromReferenceWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103978:34)
    at processSourceFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:104011:13)
    at processRootFile (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:103834:13)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:102751:60
    at Object.forEach (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:102751:16)
    at synchronizeHostData (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:143359:26)
    at Proxy.getProgram (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:143451:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:148308:53)
    at ConfiguredProject.Project.updateGraph (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:148241:42)
    at ConfiguredProject.updateGraph (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:149175:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:150879:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:151786:44)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:152113:97
    at Object.flatMap (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:152113:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:153134:46)
    at /Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:155006:88
    at IOSession.Session.executeWithRequestId (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:154997:28)
    at IOSession.Session.executeCommand (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:155006:33)
    at IOSession.Session.onMessage (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:155030:35)
    at Interface.<anonymous> (/Users/jonathanfr/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200805/node_modules/typescript/lib/tsserver.js:157246:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
flutter-snippets|ale|2.0.0
react-pure-to-class-vscode|ang|1.1.8
gitstash|art|3.2.1
emojisense|bie|0.7.0
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.3
vs-code-can-do-that|bur|0.0.7
vscode-exports-autocomplete|cap|0.5.4
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
jsrefactor|cms|2.20.6
bracket-pair-colorizer-2|Coe|0.2.0
scaffolder-vscode|ctf|0.12.5
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
vscode-eslint|dba|2.1.8
vscode-dash|dee|2.4.0
vscode-deno|den|1.26.0
es7-react-js-snippets|dsz|2.8.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
vscode-jest-runner|fir|0.4.22
code-runner|for|0.11.0
vscode-yarn|gam|1.7.0
vscode-pull-request-github|Git|0.18.0
css2react|got|1.0.1
debug-visualizer|hed|1.1.0
rest-client|hum|0.24.1
RelativePath|jak|1.4.0
docthis|joe|0.7.1
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
inline-parameters|lia|0.2.1
git-graph|mhu|1.25.0
vscode-scss|mrm|0.9.0
python|ms-|2020.7.96456
js-debug-nightly|ms-|2020.8.517
node-debug2|ms-|1.42.5
vscode-typescript-next|ms-|4.1.20200805
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.17.0
color-highlight|nau|2.3.0
vscode-json-editor|nic|0.2.3
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.2.0
ponicode|Pon|0.22.1
vscode-css-peek|pra|4.0.0
vscode-yaml|red|0.9.1
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
vscode-spotify|shy|3.1.0
addDocComments|ste|0.0.8
code-spell-checker|str|1.9.0
vscode-field-lights|sve|0.0.11
svelte-vscode|sve|101.8.0
tabnine-vscode|Tab|2.9.0
vscode-status-bar-format-toggle|tom|2.0.0
lodash-snippets|tom|1.0.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
gistfs|vsl|0.1.8
gitdoc|vsl|0.0.6
dingo-vscode|Wal|1.0.7
quokka-vscode|Wal|1.0.312
wallaby-vscode|Wal|1.0.223
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.2.0
material-theme|zhu|3.8.5
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-08-06 18:39
Seems like a duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-08-06 18:39 UTC
