### ISSUE TITLE
Commenting problem

### ISSUE THREAD

**Issue by IMPrimph** [microsoft/vscode#108702] opened 2020-10-15 02:27 UTC
We have written the needed data into your clipboard because
Issue Type: <b>Bug</b>

In any CSS file, if I wrote some code and comment on it for the first time, it works fine.
But, when I write some more code and select all the parts (previously commented part "using Ctrl + A")and comment again, it's not working.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (3.00GB free)|
|Process Argv|--crash-reporter-id d387dc60-c945-40be-a4f1-77fe9107addc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.10
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
beautify|Hoo|1.5.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
csharp|ms-|1.23.3
python|ms-|2020.9.114305
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by hDmtP** [comment] 2020-10-15 04:13
@IMPrimph exactly same case here. In fact sometimes while writing CSS code under the style tag in an HTML code when I select some part of the CSS code and press ctrl+/ to comment it uses HTML comment(i.e. ) instead of CSS comment(/* */). I have to manually type /* */ to get my job done. I don't know if it's a fault in the settings of in the VS code.

**Comment by IMPrimph** [comment] 2020-10-15 05:11
@hDmtP 
Exactly, can't figure out the problem. Might be a bug.

**Comment by aeschli** [comment] 2020-10-15 09:14
Can you add small code sample with steps that show what's not working?

**Comment by IMPrimph** [comment] 2020-10-15 09:31
@aeschli 
This is the first part of the code I have written and commented:
`/* body {
  font-family: "Open Sans", sans-serif;
}

h1 {
  text-align: center;
} */
`
Then I wrote some more code:<br>
`/* body {
  font-family: "Open Sans", sans-serif;
}

h1 {
  text-align: center;
} */

#container div {
  width: 200px;
  height: 200px;
  text-align: center;
  font-size: 3em;
}
`
<br>

And now, when I tried to select all(Ctrl + A) and comment at once(Ctrl + /), the code is not getting commented:<br>
<br>
`/* body {
  font-family: "Open Sans", sans-serif;
}

h1 {
  text-align: center;
} */

#container div {
  width: 200px;
  height: 200px;
  text-align: center;
  font-size: 3em;
} */
`

<br>
Please check these four images for a clear explanation:
<img width="269" alt="Starting code" src="https://user-images.githubusercontent.com/68636066/96104982-1f504f80-0ef7-11eb-88e8-bdcc052245e1.PNG">
<img width="266" alt="Starting code commented" src="https://user-images.githubusercontent.com/68636066/96104986-211a1300-0ef7-11eb-801a-e83552baf09b.PNG">
<img width="239" alt="Added some more code" src="https://user-images.githubusercontent.com/68636066/96104989-21b2a980-0ef7-11eb-8061-851a81bb54c8.PNG">
<img width="259" alt="Then commented it" src="https://user-images.githubusercontent.com/68636066/96104993-21b2a980-0ef7-11eb-9cf4-623fc95ba1a1.PNG">

**Comment by hDmtP** [comment] 2020-10-15 12:41
@aeschli 
1. The code
![Screenshot 2020-10-15 175401](https://user-images.githubusercontent.com/65482473/96123506-88908c80-0f10-11eb-9a88-14b40022d4ad.png)
2.  I selected some CSS code under the <style> tag in the HTML code
![Screenshot 2020-10-15 175503](https://user-images.githubusercontent.com/65482473/96123656-c55c8380-0f10-11eb-9089-d2e16867308c.png)
3. As I pressed ctrl+/ to comment out it uses the HTML comment tag() instead of CSS comment tag(/* */)
![Screenshot 2020-10-15 175632](https://user-images.githubusercontent.com/65482473/96123740-e4f3ac00-0f10-11eb-9301-b968dcd938a2.png)
4. This is the manually typed comment of the same code
![Screenshot 2020-10-15 175950](https://user-images.githubusercontent.com/65482473/96125081-474cac80-0f11-11eb-8864-beedec48c731.png)

Note: The ctrl+/ is working in an individual .css file. I have also noticed that the shortcut also works in CSS code, embedded in an HTML code. But in my VS code, this process isn't working(as shown above). I will be thankful to know if it is a bug or a settings issue in my VS code.

**Comment by aeschli** [comment] 2020-10-15 15:41
@IMPrimph That's how the commenting feature works. It just adds comment tokens (e.g. `/*` `*/`) around the selected block, without processing the content.
To uncomment a block you must select just that comment.

@hDmtP That's an unrelated issue, but I'm not able to reproduce what you are seeing. I get the proper CSS comments  `/*` `*/`` when in CSS. Is the language mode `html` (check the status bar on the right). Does it reproduce with extensions disabled?

**Comment by hDmtP** [comment] 2020-10-15 16:57
@aeschli Yes the language mode is HTML and it reproduces with extensions disabled.

**Comment by IMPrimph** [comment] 2020-10-16 03:04
@aeschli 
I am not uncommenting.
See, when we write some 100lines of CSS at first and then comment it.
Again wrote 100 lines of CSS and use CTRL + A and comment. The previous 100 lines are commented well, but the next 100 lines are not getting commented on.
That is what I have depicted in the images.

**Comment by gjsjohnmurray** [comment] 2020-10-16 06:40
Slightly related to #107989. @aeschli can commenting logic easily discover language of code at cursor?

**Comment by hDmtP** [comment] 2020-10-16 06:42
@gjsjohnmurray 
Yeah, I also want to confirm this.

**Comment by aeschli** [comment] 2020-10-16 06:47
<img width="259" alt="Then commented it" src="https://user-images.githubusercontent.com/68636066/96104993-21b2a980-0ef7-11eb-9cf4-623fc95ba1a1.PNG">
@IMPrimph As seen in the screen shot, all the comment action does is adding the comment tokens (`/*` `*/`).
The commented content is intentionally not modified, e.g. no closing comment token ( `*/`) is escaped. that's left to the user.
That's how the comment command is intended to work.

**Comment by aeschli** [comment] 2020-10-16 06:48
@gjsjohnmurray I don't see how this is related to #107989.

**Comment by gjsjohnmurray** [comment] 2020-10-16 09:02
@hDmtP works OK for me:

![junk](https://user-images.githubusercontent.com/6726799/96236303-ca164b80-0f93-11eb-8311-fb718390056e.gif)

Or have I misunderstood your problem?

@aeschli ignore my previous comment. I now see block commenting is already smart enough to use the correct languageId

https://github.com/microsoft/vscode/blob/f3399d0c4b6a0bef63a95c53fcfe7f0f9d10dcf4/src/vs/editor/contrib/comment/blockCommentCommand.ts#L170

**Comment by hDmtP** [comment] 2020-10-16 09:08
Not only you @gjsjohnmurray I have also seen this feature working in other's VS code. But hell knows why negative in case of mine.

**Comment by KamasamaK** [comment] 2020-10-26 20:08
@hDmtP Can you highlight the same text, open the command palette, select "Developer: Inspect Editor Tokens and Scopes" and post a screenshot?

**Comment by aeschli** [comment] 2020-11-05 14:09
This issue has diverted into various topics. I believe the original issue was based on a misunderstanding. I'll close this and would be happy if new issues with code sample and reproducible steps are filed.

**Closed by aeschli** 2020-11-05 14:09 UTC
Labels: needs more info
