### ISSUE TITLE
Syntax highlighting on .cs files breaks when the open parentheses is on separate line to the rest of the method declaration

### ISSUE THREAD

**Issue by fantasticman** [microsoft/vscode#78461] opened 2019-08-05 02:30 UTC
Issue Type: <b>Bug</b>

Create a new file, set filetype to C#, with the following contents:
```cs
public class Test
{
    //This is fine:
    private void Fine()
    {
        int x = 0;
    }

    //This breaks highlighting:
    private void NotFine
    ()
    {
        int y = 1;
    }
}
```
Observe how the method name "NotFine" and following code loses it's usual highlighted colour and reverts to white.
Even though this may be an unusual convention for code, it is still correct C# and should still be highlighted correctly.

*edit*
I believe this happens on other languages as well, not just C#.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (1.02GB free)|
|Process Argv|-psn_0_40970|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
unity-debug|Uni|2.7.2

</details>

**Comment by alexr00** [comment] 2019-08-05 09:15
Duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/63

**Closed by alexr00** 2019-08-05 09:15 UTC
