### ISSUE TITLE
Cannot drag and drop between windows onto notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#125186] opened 2021-06-01 21:23 UTC
Testing #124848

1. Open a GitHub Issue notebook
2. Drag a file from another window onto the notebook

**Bug**
No drop indicator shows up and drop generally doesn't work

**Comment by rebornix** [comment] 2021-06-02 23:29
@mjbvz I'm not seeing this currently on Windows, do you have screen recording for what you were seeing?

**Comment by mjbvz** [comment] 2021-06-02 23:55
Dragging within a window seems to work ok in the current insiders build

Dragging between windows still doesn't work for me though

**Comment by bpasero** [comment] 2021-06-07 15:34
Hm weird, at first I thought it would be a duplicate of https://github.com/microsoft/vscode/issues/125187 assuming the notebook is a webview, but that does not seem to be the case.

**Comment by bpasero** [comment] 2021-06-08 13:47
Turns out this is because there is a `iframe` involved in the notebook:

![image](https://user-images.githubusercontent.com/900690/121196335-b1cfa580-c870-11eb-9811-3b0f5c370f27.png)

As such this is the same underlying issue as https://github.com/microsoft/vscode/issues/120973 I believe where the drag events do not bubble through the iframe into the listeners in the workbench

/duplicate https://github.com/microsoft/vscode/issues/120973

**Closed** 2021-06-08 13:47 UTC
Labels: *duplicate, bug, notebook, workbench-dnd
