### ISSUE TITLE
Terminal should support Cmd-K on the Mac

### ISSUE THREAD

**Issue by natesilva** [Microsoft/vscode#7429] opened 2016-06-08 17:18 UTC
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5 (15F34)

Kudos:

I love the new integrated terminal feature!

Task I am trying to do:

Clear the screen after typing a series of terminal commands.

Steps to Reproduce:

1. On a Mac, open the integrated terminal (e.g. Ctrl-`)
2. Type in a few commands.
3. Clear the screen by pressing Cmd-K. (Cmd-K is a standard key for clearing the screen in apps like Console, Terminal, the Safari and Chrome Web Inspectors, etc.)

It works, but VSCode thinks that is the first key of a multi-key command and waits for and swallows the next keypress. It should recognize Cmd-K in the context of the integrated terminal.

Other things I tried:

* Using the Unix `clear` command partly works. If you close and re-open the terminal, the previously “cleared” text reappears.

**Comment by Tyriar** [comment] 2016-06-09 04:34
Duplicate of https://github.com/Microsoft/vscode/issues/7240

**Closed by Tyriar** 2016-06-09 04:34 UTC
