### ISSUE TITLE
Minimap: can only click outside of current 'view'

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#20957] opened 2017-02-20 20:52 UTC
- VSCode Version: 1.10.0-insider
- OS Version: Windows 7

### Steps to Reproduce:

1. Open a file of decent length
2. Use the minimap to scroll somewhere:

![image](https://cloud.githubusercontent.com/assets/3329959/23141352/6f7faade-f784-11e6-8d2d-7f99db1f2829.png)

3. Try to fine-tune your view by clicking a bit lower in the minimap, but still inside the view pane box:

![image](https://cloud.githubusercontent.com/assets/3329959/23141355/766c38b2-f784-11e6-9695-2f6c226a7656.png)

### Expected result

* The editor should scroll a bit to match the newest click

### Actual result

* Nothing happens

**Comment by alexandrudima** [comment] 2017-02-27 15:52
Duplicate of #20935

**Closed by alexandrudima** 2017-02-27 15:52 UTC
