### ISSUE TITLE
Not able to open GitBash inside VS Code

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#52120] opened 2018-06-17 07:17 UTC
- VSCode Version: 1.24.1
- OS Version: Windows 10

Steps to Reproduce:

* https://youtu.be/nFDAwLhWa4M

**Comment by RMacfarlane** [comment] 2018-06-17 17:38
Duplicate of https://github.com/Microsoft/vscode/issues/7286, please try using `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"` instead

**Closed by RMacfarlane** 2018-06-17 17:38 UTC
Labels: integrated-terminal, new release
