### ISSUE TITLE
In the Explorer filetree, near the top, please include a filename filter box

### ISSUE THREAD

**Issue by NickVH-MS** [microsoft/vscode#121432] opened 2021-04-16 01:26 UTC
In the Explorer UI, when looking at a filetree, near the top, please include a filename filter box. In a way, it'd be sort of a search box but limited in scope only to filenames (which are likely cached in memory anyway), so it should be ultra-snappy.

**Comment by gjsjohnmurray** [comment] 2021-04-16 06:25
Are you aware that you can already search / filter the Explorer tree by typing characters when focused on it?

**Comment by IllusionMH** [comment] 2021-04-16 06:28
I think it's duplicate of #70646

**Comment by NickVH-MS** [comment] 2021-04-16 07:10
I see, I wasn't aware. I agree this is more or less a duplicate of #70646.

**Closed** 2021-04-16 07:11 UTC
Labels: *duplicate
