### ISSUE TITLE
Execute commands from Markdown

### ISSUE THREAD

**Issue by jjfvanderpol** [microsoft/vscode#130136] opened 2021-08-04 19:16 UTC
I would like to execute commands from a Markdown file (e.g. README.md), in the same manner as it is possible to link to an extension:  '[Python](vscode:extension/ms-python)'. This is useful for onboarding new users, by letting them read the documentation and execute commands making it an interactive experience.

Kind regards, 

Joris van der Pol

**Comment by mjbvz** [comment] 2021-08-12 02:12
Duplicate of #102532

Currently disabled by design

**Closed by mjbvz** 2021-08-12 02:12 UTC
