### ISSUE TITLE
Broken Settings Editor Actions

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#213913] opened 2024-05-30 13:51 UTC
![Code_-_Insiders_JypRdX9vJp](https://github.com/microsoft/vscode/assets/2931520/47bd3096-7bfe-4f9c-ae8b-35017c2a2fcd)

**Comment by rzhao271** [comment] 2024-05-30 14:47
This should be fixed on the latest Insiders.
Duplicate of https://github.com/microsoft/vscode/issues/213717

**Closed** 2024-05-30 14:58 UTC
Labels: info-needed
