### ISSUE TITLE
Sort imports in typescript can leave a lot of blank lines

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125398] opened 2021-06-03 14:33 UTC
Testing https://github.com/microsoft/vscode/issues/122593

It looks like if there are imports that span multiple lines you can end up with empty lines after running the sort imports action.

1. Open your clone of microsoft/vscode
2. Open the file abstractTaskService.ts
3. Command -> Source Action...
4. Choose "Sort Imports"

**Comment by mjbvz** [comment] 2021-06-03 15:51
Duplicate of https://github.com/microsoft/TypeScript/issues/22914 I believe

**Closed by mjbvz** 2021-06-03 15:51 UTC
