### ISSUE TITLE
Emmet with Umlauts not working

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#4960] opened 2016-04-05 13:18 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:

1. Make a new html page
2. Write using emmet and use umlauts

The current implementation of emmet doesn't seem to cope with umlauts very well. If tags have umlauts they are cut after the umlaut.

![vscode_issue](https://cloud.githubusercontent.com/assets/8189808/14283004/8646ca76-fb41-11e5-8bde-dfa4b5313c71.png)

**Comment by egamma** [comment] 2016-04-06 08:20
Suspect the issue is upstream. Found this closed issue https://github.com/emmetio/emmet/issues/212 but it is from 2013 and we have this version.

**Comment by egamma** [comment] 2016-04-07 09:26
Steps to reproduce:
- Insert  DatenSätze^^
- TAB
-> DatenSä<tze></tze>

I've reproduced it in several emmet integrations (sublime, atom), so this an emmet issue. I've filed https://github.com/emmetio/emmet/issues/439 against emmet.

**Comment by egamma** [comment] 2016-06-21 13:50
Closing, no action on upstream issue.

**Closed by egamma** 2016-06-21 13:50 UTC
Labels: upstream
