### ISSUE TITLE
[css] add property type validation

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6827] opened 2016-05-24 18:17 UTC
A red squiggle would be good here:

![image](https://cloud.githubusercontent.com/assets/2193314/15515044/f087defe-21a0-11e6-8ef1-28b6243db9b3.png)

**Comment by aeschli** [comment] 2017-11-22 16:33
duplicate of #8323

**Closed by aeschli** 2017-11-22 16:33 UTC
Labels: css-less-sass, feature-request
