### ISSUE TITLE
VSCode freezes if run as a background process on Linux (0.10.6)

### ISSUE THREAD

**Issue by RussBaz** [Microsoft/vscode#1940] opened 2016-01-12 05:08 UTC
I could start it easily from a terminal as a background process in Fedora 23 (using ampersand). However, after an upgrade to 0.10.6 (64bit), it freezes soon after opening. It was not the case in the previous versions.

I suspect it might be related to the git integration somehow. It freezes if a folder is under git source control. It does not freeze otherwise. When I run it with the verbose option, it stops right before prompting for my repository credentials (which it normally does if not frozen).

vscode:
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:26:42.359Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

git:
2.5.0

Normal start-up (with a git repository address being changed):
```text
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
### VSCode main.js ###
/home/rbazhenov/Software/VSCode-linux-x64/resources/app { pathArguments: [ '/home/rbazhenov/Projects/ec+' ],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded
Password for 'MYGITREPOADDRESS':
```

Failed start-up (freezes after opening):
```text
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
### VSCode main.js ###
/home/rbazhenov/Software/VSCode-linux-x64/resources/app { pathArguments: [ '/home/rbazhenov/Projects/ec+' ],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded
```

**Comment by mdsitton** [comment] 2016-02-12 23:17
I'm fairly sure I'm having the same issue but instead of just freezing vscode it's also freezing my whole desktop environment(cinnamon)

**Comment by mariusa** [comment] 2016-03-10 08:49
I also encounter freezing (using latest version now, but always got freezing since December when I start using it)
Using Fedora with default Gnome desktop.
$ uname -a
Linux localhost.localdomain 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Only vscode freezes, not anything else, after a few hours of usage.
Here's the terminal outout:

```
$ ./code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
### VSCode main.js ###
/home/data/apps/VSCode-linux-x64/resources/app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false,
  locale: undefined }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded
IPC#vscode-openFilePicker
IPC#vscode-openFilePicker
IPC#vscode-openFilePicker

<--- Last few GCs --->

96032349 ms: Mark-sweep 1394.7 (1457.6) -> 1394.7 (1457.6) MB, 2956.1 / 21 ms [allocation failure] [GC in old space requested].
96035276 ms: Mark-sweep 1394.7 (1457.6) -> 1394.7 (1457.6) MB, 2926.9 / 22 ms [allocation failure] [GC in old space requested].
96038180 ms: Mark-sweep 1394.7 (1457.6) -> 1394.7 (1457.6) MB, 2904.4 / 31 ms [last resort gc].
96041079 ms: Mark-sweep 1394.7 (1457.6) -> 1394.7 (1457.6) MB, 2898.1 / 29 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xa9cd183a859 <String[7]: file://>
    1: _completed [file:////home/data/apps/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:~23] [pc=0x187c6d132853] (this=0x1c379e06a469 <JS Object>,e=0x3a3a717041b9 <undefined>)
    2: arguments adaptor frame: 0->1
    6: bound  [native v8natives.js:1208] [pc=0x187c61da8cb0] (this=0xa9cd1846061 <JS Global Object>)

==== Details ========================================...

Failed to get crash dump id.
Report Id: 
[VS Code]: detected unresponsive
Lifecycle#window-all-closed
Lifecycle#before-quit
App#dispose: deleting running instance handle
```

**Comment by joaomoreno** [comment] 2016-03-10 09:16
@Tyriar is this solved with the new launcher?

**Comment by mariusa** [comment] 2016-03-10 21:45
For me it's freezing when launching in a terminal as
./code
and leaving the terminal open.
Will the fix mentioned address freezing in the next release? 
Thanks

**Comment by Tyriar** [comment] 2016-03-11 02:13
So the freezing happens when calling with `./code`, not just `./code &`? What console output are you getting? Does the window and/or UI appear?

What's coming in March may fix your problems, it's a new launch script and CLI. The launch logic past the command line args parsing hasn't changed much.

**Comment by mariusa** [comment] 2016-03-11 06:49
So the freezing happens when calling with ./code -- yes. 
It freezes after a few hours of usage, not instantly. VS Window remains frozen.
Console output is in the above comment, here's another 
```
[marius@localhost VSCode-linux-x64]$ ./code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
### VSCode main.js ###
/home/data/apps/VSCode-linux-x64/resources/app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false,
  locale: undefined }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded
IPC#vscode-openFilePicker
IPC#vscode-openFilePicker

<--- Last few GCs --->

68220044 ms: Mark-sweep 1395.1 (1457.6) -> 1395.1 (1457.6) MB, 3072.1 / 17 ms [allocation failure] [GC in old space requested].
68223139 ms: Mark-sweep 1395.1 (1457.6) -> 1395.1 (1457.6) MB, 3095.2 / 17 ms [allocation failure] [GC in old space requested].
68226240 ms: Mark-sweep 1395.1 (1457.6) -> 1395.1 (1457.6) MB, 3100.4 / 25 ms [last resort gc].
68229369 ms: Mark-sweep 1395.1 (1457.6) -> 1395.1 (1457.6) MB, 3129.3 / 25 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1460a833a859 <String[7]: file://>
    1: _completed [file:////home/data/apps/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:~23] [pc=0x10d614784c73] (this=0x1dcb3a08cef1 <JS Object>,e=0x950159041b9 <undefined>)
    2: arguments adaptor frame: 0->1
    6: bound  [native v8natives.js:1208] [pc=0x10d606d9c670] (this=0x1460a8346061 <JS Global Object>)

==== Details =======================================...

Failed to get crash dump id.

Lifecycle#window-before-close 1
Lifecycle#unload() 1
Lifecycle#window-before-close 1
Lifecycle#unload() 1
[VS Code]: detected unresponsive
Lifecycle#window-all-closed
Lifecycle#before-quit
App#dispose: deleting running instance handle
```

**Comment by Tyriar** [comment] 2016-04-04 15:53
@RussBaz @mariusa I can't reproduce this, can you try reproduce on the [latest insider's build](code.visualstudio.com/insiders) using the deb or rpm packages to install?

**Comment by mariusa** [comment] 2016-04-06 11:41
@Tyriar  installed the insiders rpm package 2 days ago, and now it froze.
There's no log to show, since I started it using the desktop shortcut.

Note that I haven't restarted vscode since starting it 2 days ago.

**Comment by Tyriar** [comment] 2016-04-06 16:11
@bpasero @joaomoreno have you two seen the issue before that @mariusa has been experiencing?

**Comment by bpasero** [comment] 2016-04-06 16:21
Is VS Code running out of memory after starting and causing it to crash?

**Comment by mariusa** [comment] 2016-04-06 21:18
If there's any data I could provide next time (please see previous console output), I'd be glad to, just let me know exactly what/how please.

**Comment by bpasero** [comment] 2016-04-07 05:24
To clarify: The freeze only happens when you open VS Code on a folder that prompts for git credentials?

**Comment by mdsitton** [comment] 2016-04-07 05:50
That is correct in my case. (some others sound like they may be having other issues?)

**Comment by bpasero** [comment] 2016-04-07 06:03
I tried to reproduce on Ubuntu 15 and I am not even getting the git login dialog there, but VS Code otherwise works fine. @joaomoreno what is needed to get the dialog on Linux?

**Comment by mariusa** [comment] 2016-04-07 07:22
>> The freeze only happens when you open VS Code on a folder that prompts for git credentials?
I have .git folders in the workspace, but it never asks me for credentials, and I use git only from command line. The freeze seems random to me, and unrelated to git.

**Comment by joaomoreno** [comment] 2016-04-07 07:39
@bpasero #1796

**Comment by bpasero** [comment] 2016-04-07 07:40
Maybe people have configured some special git credential helper that causes this?

**Comment by joaomoreno** [comment] 2016-06-01 07:41
Closing as duplicate of #1796.

**Closed by joaomoreno** 2016-06-01 07:41 UTC
Labels: bug, freeze-slow-crash, git, linux
