### ISSUE TITLE
markdown reference link not recognized

### ISSUE THREAD

**Issue by ShaMan123** [microsoft/vscode#163727] opened 2022-10-15 08:37 UTC
Type: <b>Bug</b>

In some syntax cases markdown reference links are not recognized.
e.g.

```md
recognized: [mdn][mdn]
unrecoginzed: [`mdn`][mdn]

[mdn]: https://developer.mozilla.org/en-US/
```

https://user-images.githubusercontent.com/34343793/195977536-0a764b81-8ecd-4bc3-a460-a59e9421fb48.mp4

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.10GB free)|
|Process Argv|C:\\Users\\DELL\\Desktop\\DEV\\fabric.js --crash-reporter-id ed04e42e-1d11-4683-872f-421f0db5bcc0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.9.0
vscode-pull-request-github|Git|0.50.0
better-cpp-syntax|jef|1.16.1
cmake-language-support-vscode|jos|0.0.5
vscode-docker|ms-|1.22.1
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.255.3
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.12.27
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5735
vsliveshare-audio|ms-|0.1.91
vscode-react-native|msj|1.9.3
vetur|oct|0.36.0
java|red|1.11.0
code-spell-checker|str|2.10.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by ShaMan123** [comment] 2022-10-15 08:40
kind of related to #162149

**Comment by mjbvz** [comment] 2022-10-17 16:39
Duplicate of https://github.com/microsoft/vscode-markdown-languageservice/issues/66

Already fixed in insiders

**Closed by mjbvz** 2022-10-17 16:39 UTC
Labels: new release

**Comment by ShaMan123** [comment] 2022-10-17 17:36
Thanks
