### ISSUE TITLE
type a slash (/) in a string (JavaScript) un-indents the line

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#139997] opened 2022-01-02 01:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a JavaScript (`foobar.js`) file with the following content
    ```
    function bla(dodo) {
      if (dodo) {
        let a = "[*]";
      }
    }
    ```
2. I have set the tab size to 2 characters and spaces
2. Place the cursor after the `*`
3. Press the `/` (slash) key
4. the line the cursor is on un-indents 1 step, now `let` is aligned with `if`

I discovered it in a line with a complex regular expression, and could reduce it to this string.

**Comment by joeljose350** [comment] 2022-01-02 09:22
I have the same issue on my Windows 11 machine.

```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by gjsjohnmurray** [comment] 2022-01-02 09:54
Please check your keybindings

https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by rioj7** [comment] 2022-01-02 10:33
@gjsjohnmurray 

Output of `Developer: Toggle Keyboard Shortcuts Troubleshooting`

```
[2022-01-02 11:27:21.243] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Slash, keyCode: 191, key: /
[2022-01-02 11:27:21.243] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Slash, keyCode: 85 ('/')
[2022-01-02 11:27:21.244] [renderer1] [info] [KeybindingService]: | Resolving /
[2022-01-02 11:27:21.244] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```

The behavior depends on the **content of the string**

* `let a = "[*";` it does **not** happen
* `let a = "*]";` it **does** happen

**Comment by ArturoDent** [comment] 2022-01-02 23:05
Strangely, I **cannot** reproduce this on Stable Build 1.63.2 but **can** on Insiders Build  

![reindent](https://user-images.githubusercontent.com/31813701/147891664-c915d15d-92dd-4b04-ba70-9f7579611dfe.gif)

Recent work on `indentationRules`?

**Comment by rebornix** [comment] 2022-12-13 00:36
It looks like that the indentation rules for JS is not covering this case. Currently the indentation rules for  auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.

**Closed by rebornix** 2022-12-13 00:36 UTC
Labels: editor-autoindent, under-discussion, wont-fix

**Comment by rioj7** [comment] 2022-12-14 08:43
@rebornix Then I have to live with this ;-). I never use formatters, they always break my layout or I have more work to configure them.

Auto indent and Backspace are enough for me.
