### ISSUE TITLE
if User includes node_modules to "files to include" vscode it should be able to search that folder

### ISSUE THREAD

**Issue by EsrefDurna** [microsoft/vscode#101170] opened 2020-06-26 23:39 UTC
- VSCode Version: latest
- OS Version: macos

Steps to Reproduce:

1. Right click to node_modules folder, 
2. Click to "Find in Folder"

if the user is including this folder vscode should have ignore "excluded folder" configuration also should ignore useIgnoreFildes
Because user is telling I want to search in this folder.

So include folder should be applied AFTER this rules, so if the user wants to include a folder to search they will able to.

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by yume-chan** [comment] 2020-06-27 02:27
Duplicate of #26574

**Closed** 2020-06-30 20:58 UTC
