### ISSUE TITLE
Windows: problems with symlinks with GIT scm

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#23683] opened 2017-03-30 16:33 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (bc9a7bb1f90557c271c39628b5a3cdd7dfbc750c, 2017-03-30T08:11:58.005Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|typings-installer|benjaminromano|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|theme-dracula|dracula-theme|1.8.0|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Theme-azure|gerane|0.0.2|
|docthis|joelday|0.4.3|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.6.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.7.0|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.0.13|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|vscode-hexdump|slevesque|1.2.1|
|eval|Stormspirit|0.0.6|
|omnipascal|Wosi|0.13.0|;

---

Steps to Reproduce:

1. Open a VSCode in a new workspace
2. In this workspace, create a directory symbolic link (in an admin terminal: ```mklink /D shared c:\```)
3. Open or create .gitignore file and add a new entry for "shared" and save

What happens:
In the git panel, "shared" appears in the list of changes with a "file" icon as if it was a file. Btw clicking on it does switch to the files panel but doesn't select the "shared" simlink.

What should happen?
"shared" should not appear in the changes list.

As you can see: typing "git status" in a command prompt doesn't show "shared" in the list of changes:

![gitproblemsymwindows](https://cloud.githubusercontent.com/assets/199648/24515247/4af78860-1577-11e7-8e4c-edb8b4df23f1.png)

**Comment by joaomoreno** [comment] 2017-03-30 20:00
Related to #5970?

**Comment by joaomoreno** [comment] 2017-03-30 20:00
And also, why on Earth would you attempt something like this?

**Comment by twoeo** [comment] 2017-06-19 14:53
The same problem.
I have 3 folder:
```
|- __shared
|- frontend
  |- shared  (Symlink to ../__shared)
|- backend 
    |- shared (Symlink to ../__shared)
```

And I open frontend folder and backend folder as 2 different project.
But they share code by symlink.

**Now the problem is: **
If I change files in shared , git changes will not show that.

Git repository is the root folder.

**Comment by joaomoreno** [comment] 2017-11-23 13:38
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Closed by joaomoreno** 2017-11-23 13:38 UTC
Labels: bug, git, help wanted
