### ISSUE TITLE
Incorrect background color for themes on insiders build

### ISSUE THREAD

**Issue by fzxt** [Microsoft/vscode#22463] opened 2017-03-11 23:08 UTC
Hello,

The background color for some themes don't seem to be showing correctly.

Consider the screenshot shown on this [theme](https://marketplace.visualstudio.com/items?itemName=sharksym.theme-cobalt0):

![image](https://cloud.githubusercontent.com/assets/8539864/23827537/0e603746-0684-11e7-94b0-2cb09bc6403e.png)

VSCode insiders after installing and selecting theme: 

![image](https://cloud.githubusercontent.com/assets/8539864/23827545/34fc1708-0684-11e7-93e2-02104ae18788.png)

It seems to be working fine on the non-insider version, though: 
![image](https://cloud.githubusercontent.com/assets/8539864/23827588/d2835432-0684-11e7-9a2f-14404229de3a.png)

I've tried disabling all extensions and enabling only desired themes to make sure no extensions are messing with it, as well as adjusting the background color in the .tmTheme of individual themes themselves, but neither helped.

- VSCode Version: Code - Insiders 1.11.0-insider (01091bb0831f7ce07db3cdc3ad66abb4141ffd8d, 2017-03-10T07:05:03.565Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.0|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-wakatime|WakaTime|1.1.3|
|project-manager|alefragnani|0.13.3|
|vscode-color|anseki|0.2.3|
|code-gnu-global|austin|0.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-instant-markdown|dbankier|1.0.0|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.9|
|theme-dracula|dracula-theme|1.2.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|file-icons|file-icons|1.0.3|
|auto-rename-tag|formulahendry|0.0.11|
|Theme-80s-pastel-dark|fzxt|0.0.1|
|Theme-Solarized-ocean|gerane|0.0.2|
|Theme-Zenburn|gerane|0.0.3|
|Angular2|johnpapa|2.0.3|
|vs-color-picker|lihui|0.6.0|
|markdown-shortcuts|mdickin|0.6.1|
|vscode-elixir|mjmcloug|0.1.1|
|cpptools|ms-vscode|0.10.2|
|debugger-for-chrome|msjsdiag|2.5.4|
|color-highlight|naumovs|1.3.2|
|indent-rainbow|oderwat|0.4.1|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|theme-gruvbox|saviorisdead|0.0.1|
|theme-cobalt0|sharksym|0.0.5|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1. Install a theme
2. Look at the background color

**Comment by ramya-rao-a** [comment] 2017-03-11 23:54
cc @alexandrudima

**Comment by jdc-cunningham** [comment] 2017-03-12 07:17
Hi, I just wanted to ask, what is that color-start-end bands that you have for the code blocks?

**Comment by arcticicestudio** [comment] 2017-03-12 08:23
I think this is a duplicate of #22361 which has already been fixed.

**Comment by fzxt** [comment] 2017-03-12 12:12
@jdc-cunningham https://github.com/oderwat/vscode-indent-rainbow

**Comment by jdc-cunningham** [comment] 2017-03-12 12:16
@fzxt

 Thank you

**Comment by ramya-rao-a** [comment] 2017-03-12 18:12
Thanks @arcticicestudio 
Closing as duplicate go #22361 
The next Insiders build on Monday will have the fix.

**Closed by ramya-rao-a** 2017-03-12 18:12 UTC
Labels: themes
