### ISSUE TITLE
Save Dialog not saving file

### ISSUE THREAD

**Issue by SSDiver2112** [Microsoft/vscode#21977] opened 2017-03-04 16:25 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.7.0|
|vs-keybindings|ms-vscode|0.1.3|;

---

After creating a new SQL file with the new New Query feature in the MSSQL Extension, closing the tab pops up the do you want to save message box, choosing save just closes the dialog and the query but does not save the file.

Steps to Reproduce:

1. ctrl shift P then choose SQL New Query.
2. Create Query
3. Close the tab before manually saving will open the Do you want to save message.
4. click Save and the dialog closes and the query closes, but is not saved.

**Comment by bpasero** [comment] 2017-03-04 16:47
@SSDiver2112 can you reproduce the same by opening a new untitled file (Ctrl+N), making some changes and closing the tab?

**Comment by SSDiver2112** [comment] 2017-03-04 18:02
Ctrl+N works correctly. Clicking Save Opens the SaveAs Dialog and allows the file to be saved. It only does it when I use the New Query option.

**Comment by bpasero** [comment] 2017-03-05 05:29
Ok I see what is happening, closing as duplicate of https://github.com/Microsoft/vscode-mssql/issues/762

**Closed by bpasero** 2017-03-05 05:29 UTC
