### ISSUE TITLE
Issue with the terminal logs

### ISSUE THREAD

**Issue by Gnaneshwar5a7** [microsoft/vscode#234239] opened 2024-11-20 05:31 UTC
Type: <b>Bug</b>

1. open vs code.
2. close all the terminals if open.
3. open a new terminal.
4. resize the terminal vertically.
5. observe the behaviour you will see multiple empty logs.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by Gnaneshwar5a7** [comment] 2024-11-20 05:36
Same issue with latest version also (1.95.3)

**Comment by meganrogge** [comment] 2024-11-21 00:59
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-11-21 00:59 UTC
