### ISSUE TITLE
Running "code ." on MacOS from terminal with non-latin characters in path opens non-existing file instead of current folder

### ISSUE THREAD

**Issue by vlad2135** [microsoft/vscode#134899] opened 2021-10-12 13:27 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Darwin X64 20.6.0 (macOS Big Sur 11.6)

Steps to Reproduce:
Execute in Terminal (iTerm2 in my case, but works in any terminal):

1. cd && mkdir -p ttt/рус/eng && cd ttt/рус/eng
2. code .

Expected results (as they were couple weeks ago): VSCode launches and opens current folder ttt/рус/eng
Actual results: VSCode launches without opened folder but with an editor tab for a new nonexisting file ~ttt/ÑÑÑ/eng

**Comment by gjsjohnmurray** [comment] 2021-10-12 13:32
Perhaps a duplicate of #134696

**Closed** 2021-10-12 16:25 UTC
Labels: *duplicate, new release
