### ISSUE TITLE
Transition into untitled workspace from WSL folder does not seem to work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114899] opened 2021-01-25 10:33 UTC
Steps to Reproduce:

1. open an empty window connected to WSL
2. open a single folder `/home/<name>/workspaces/jschardet`
3. click File > Add Folder to Workspace
4. select `/home/<name>/workspaces/electron-message-port`
5. the window reloads into the untitled workspace

However it never finishes to load and show the folders:

![image](https://user-images.githubusercontent.com/900690/105694278-1103cd80-5f01-11eb-957c-74cfec8af8e8.png)

Console shows:

```
ERR TreeError [FileExplorer] Tree element not found: [object Object]: Error: TreeError [FileExplorer] Tree element not found: [object Object]
    at u.getCompressedNode (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:56:62899)
    at u.setCollapsed (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:56:62410)
    at h.setCollapsed (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:56:65698)
    at C.collapse (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:265)
    at G.doRefreshNode (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20724)
    at async G.doRefreshSubTree (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20229)
    at async Promise.all (index 0)
    at async G.doRefreshSubTree (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20272)
    at async G.refreshAndRenderNode (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:19781)
    at async G._updateChildren (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:17022)
    at async G.setInput (file:///C:/Users/bpasero/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:163:16465)
```

**Comment by isidorn** [comment] 2021-01-25 11:20
Let's assign to January so we can investigate
Sounds similar to https://github.com/microsoft/vscode/issues/113562

@aeschli let me know if  there is some easy way to get into this state without WSL so I could investigate. I can also try to setup WSL on my Win VM

**Comment by isidorn** [comment] 2021-03-12 14:14
@aeschli friendly ping for this. Let me know how I can best help here :)

**Comment by aeschli** [comment] 2021-03-15 11:27
I'm not able to reproduce the issue. First folder with contents of https://github.com/aadsm/jschardet.git, second folder something else.
@bpasero Do you still see it? Any more steps to add?

@isidorn Maybe the error that is printed could be improved to more than `[object Object]

**Comment by bpasero** [comment] 2021-03-15 12:22
If you cannot reproduce feel free to close. I can verify in endgame week, don't have the setup anymore just now.

**Comment by isidorn** [comment] 2021-03-15 14:07
@aeschli makes sense, with this commit cd370fa2296 the error should now be more precise

**Comment by isidorn** [comment] 2021-03-16 13:43
Also let's close this one for now, and if Ben sees it again we can reopen.

**Closed by isidorn** 2021-03-16 13:43 UTC
Labels: bug, file-explorer, remote
