### ISSUE TITLE
Proposal: setting flag to disable js native interfaces

### ISSUE THREAD

**Issue by notgiorgi** [Microsoft/vscode#27899] opened 2017-06-02 07:35 UTC
Native interfaces like such:

![image](https://cloud.githubusercontent.com/assets/12987425/26715603/68ab03c2-4787-11e7-8ce8-9ce3b0cb129b.png)

always get in the way when I want to use snippets. There should be an option to turn them off or filter them.

**Comment by mjbvz** [comment] 2017-06-02 19:56
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/15750 We are planning to look into this next month

**Closed by mjbvz** 2017-06-02 19:56 UTC
Labels: duplicate, intellisense, javascript, upstream

**Comment by waaronking** [comment] 2017-08-05 00:51
@mjbvz do you know if this is still being looked into, or did it not make the list?

**Comment by mattbierner** [comment] 2017-08-05 01:19
This was shipped with ts 2.4, which was included in VS Code 1.14. Please file a new issue if you are still seeing unexpected suggestions

**Comment by waaronking** [comment] 2017-08-05 08:15
@mattbierner Thanks. Just for clarification before I create an issue, did it ship as a flag that can be set, or is it turned on by default?

**Comment by mattbierner** [comment] 2017-08-05 20:23
No setting, it is always enabled in TS 2.4
