### ISSUE TITLE
Can’t debug VS Code extensions on Codespaces on iPadOS

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#107386] opened 2020-09-24 22:25 UTC
- VSCode Version: Codespaces
- OS Version: iPadOS 13

Steps to Reproduce:

1. Open a VS Code extension on Codespaces
2. Build the extension
3. Open the Debug panel and click the Start/Play button
4. The debugging starts and you see the debug toolbar, but no `[Development ...]` window/tab appears.

> Running the same steps on MacOS (on Safari), works just fine. The only issue is Safari itself that _blocks_ the `[Development ...]` window. But simply clicking the block pop up button shows the `[Development ...`] window correctly.

Does this issue occur when all extensions are disabled?: Yes

Originally reported on #106997

**Comment by connor4312** [comment] 2020-10-14 22:12
Probable duplicate of https://github.com/github/codespaces/issues/1345

**Comment by connor4312** [comment] 2020-10-16 02:27
Thanks for the issue, this should be fixed in the next release of codespaces.

**Closed by connor4312** 2020-10-16 02:27 UTC
Labels: bug, ios, safari
