### ISSUE TITLE
search button in explorer tab

### ISSUE THREAD

**Issue by MMAPlayz** [microsoft/vscode#125382] opened 2021-06-03 11:37 UTC
Can you please add a search button that allows you to search up files because it is waste of time to go through all the files to see one file that we need. So please   add the search button in the explorer tab

**Comment by IllusionMH** [comment] 2021-06-03 11:47
/duplicate of #70646 + #66971

In the meantime `> Go To File` (<kbd>Ctrl</kbd>+<kbd>P</kbd>) actions provides fuzzy search for files or if it's resolved file (somewhere in expanded folders) - just start typing when explorer is in focus - this will activate filter

**Closed** 2021-06-03 11:47 UTC
Labels: *duplicate
