### ISSUE TITLE
Don't show unsaved changes icon when the file is unchanged

### ISSUE THREAD

**Issue by SpectralKH** [Microsoft/vscode#62471] opened 2018-11-02 13:36 UTC
I would expect there to be an issue for this already, but I could not find one.

If you open a file, type a character. Then instead of CMD+Z, you delete the character. Now the file shows this icon:
![image](https://user-images.githubusercontent.com/11315492/47918178-0d14ac80-deac-11e8-9bd1-486e1d1848f5.png)

This behaviour is unnecessary in my opinion, as the file is the same as the saved version. It can also cause a little confusion when it looks like the file has unsaved changes.

I would also suggest disabling "Compare with Saved" when this occurs.

**Comment by usernamehw** [comment] 2018-11-02 14:15
Duplicate of #919

**Closed** 2018-11-05 10:02 UTC
Labels: *duplicate
