### ISSUE TITLE
startSession not called when debug session started with vscode.startDebug

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#21835] opened 2017-03-02 21:53 UTC
- VSCode Version: 1.10.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Register a `startSession` command in an extension.
2. Register another command that calls `vscode.startDebug`.
3. Launch extension
4. Start debug session by selecting launch profile in Debug viewlet and clicking launch icon. - startSession` is called.
5. Stop session.
6. Invoke command from 2. - Session starts without invoking `startSession`.

**Comment by weinand** [comment] 2017-03-02 23:14
@indiejames I cannot reproduce your issue (but I do not really understand your step 6).

I've added this startDebug command to node-debug:
```ts
	context.subscriptions.push(vscode.commands.registerCommand('extension.node-debug.startDebug', config => {
		return {
			command: "node",
			args: [ context.asAbsolutePath("./out/node/nodeDebug.js") ]
		};
	}));
``` 

Then I've added breakpoints in both the 'startDebug' and the 'startSession' commands.
When launching a debug session, I first hit the 'startDebug' then 'startSession' breakpoints.

**Comment by indiejames** [comment] 2017-03-02 23:33
@weinand I'm doing things a little bit differently. I added the following to my extension.ts file

```
context.subscriptions.push(commands.registerCommand('extension.clojure.startSession', (config: any) => {
		console.log("Launch");
	}));
```

And the following under the debugger definition in launch.json

```
"startSessionCommand": "extension.clojure.startSession"
```

Then I set a breakpoint on the `console.log("Launch");` line. When I start the session by clicking the green triangle I hit the breakpoint. If I start the debug session by calling the complex command `vscode.startDebug` from another extension command the session starts but I never hit the breakpoint.

**Comment by weinand** [comment] 2017-03-02 23:35
@indiejames I misunderstood the issue and your steps.

**Comment by indiejames** [comment] 2017-03-02 23:37
I meant to say the debugger definitions in package.json.

**Comment by roblourens** [comment] 2017-03-31 17:14
So if `startDebug` is invoked from another command, `startSession` should be called? I don't see that happening. But it seems like if we did that, we'd just end up in a loop...

**Comment by indiejames** [comment] 2017-03-31 20:53
For what it's worth, this no longer applies to me. I changed my code to use the normal debug launch (button) approach and have my extension start on debug. Previously I was starting my extension first and using `startDebug` to launch my debugger/REPL via a command contributed by my extension.

**Comment by isidorn** [comment] 2017-04-03 06:41
Nothing urgent, moving to april

**Comment by isidorn** [comment] 2017-05-09 15:07
This should work fine now, unless the `startDebug` command is being passed a full configuration. Due to the way the code is structured we currently do not support that scenario and we will consider suporting it if more users ask for it.

So currently if the startDebug is invoked with no argumens or with the name of the configuration it should work just fine -> closing

**Closed by isidorn** 2017-05-09 15:07 UTC
Labels: bug, debug

**Comment by romanresh** [comment] 2017-05-10 07:36
Hi @isidorn. 

If `startDebug` doesn't support JSON with configuration, it makes sense to update documentation, because the JSON parameter is mentioned here: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

> `configuration` (optional) Name of the debug configuration from 'launch.json' to use. Or a configuration json object to use.

**Comment by isidorn** [comment] 2017-05-10 08:01
@romanresh startDebug supports JSON with configuration, just in that corner case it will not call the `startSession` command but take an alternate route to start a session.
For now we are treting this as a bug which we will look into if somebody actually hits it

**Comment by romanresh** [comment] 2017-05-11 10:34
@isidorn My original issue #24762 was duplicated on this one. The `protocol` option is ignored if debugging is started via the `vscode.startDebug` command:
```js
vscode.commands.executeCommand("vscode.startDebug", {
  "type": "node",
  "protocol": "inspector",
  "request": "launch",
  "name": "Launch current test(s) with TestCafe",
  "program": "${workspaceRoot}/node_modules/testcafe/lib/cli/index.js",
  "args": args,
  "cwd": "${workspaceRoot}"
});
```

Should I reopen my issue?

**Comment by roblourens** [comment] 2017-06-01 21:23
@isidorn, I don't understand what's different in 1.13. When I call `startDebug` with a config name, it runs `startSession`, same in 1.12 and 1.13. When I call it with a config object, it doesn't run startSession, but it looks like #24762 is covering that?

**Comment by isidorn** [comment] 2017-06-02 08:46
@roblourens yes that is already being covered by that issue or some other. Nothing changed in 1.13 this behavior was from before

**Comment by roblourens** [comment] 2017-06-02 16:26
So nothing to verify? Should it be on the May milestone?

**Comment by isidorn** [comment] 2017-06-02 16:53
@roblourens yeah nothing to verify here
