### ISSUE TITLE
Named Extension Sets

### ISSUE THREAD

**Issue by sharpninja** [microsoft/vscode#137792] opened 2021-11-24 13:22 UTC
Ability to save the currently enabled extensions as an "Extension Set" with a global manifest of sets that can be used to select an extension set.  Allow tagging "Extension Sets" with languages so that when a folder or workspaces is opened, matching extension sets would be recommended.

**Comment by IllusionMH** [comment] 2021-11-24 13:44
Looks like duplicate of #137505 which is duplicate of other requests linked there.

**Closed** 2021-11-29 08:31 UTC
Labels: *duplicate
