### ISSUE TITLE
Crashing of TS server

### ISSUE THREAD

**Issue by MBreeman** [microsoft/vscode#91887] opened 2020-03-02 12:11 UTC
Issue Type: <b>Bug</b>

VS code version: 1.42.1
OS: Ubuntu 19.10
How to reporduce:
Have an open TS window. Open a new window from there (ctrl+n). Create invalid TS script, e.g. 
123
456

Watch TS server crash

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|6, 4, 3|
|Memory (System)|15.52GB (1.52GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
prettify-json|moh|0.0.3
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
vscode-typescript-tslint-plugin|ms-|1.2.3
autoimport|ste|1.5.3
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by mjbvz** [comment] 2020-03-02 19:15
Duplicate of https://github.com/microsoft/TypeScript/issues/36681

Should be fixed in VS code 1.43

**Closed by mjbvz** 2020-03-02 19:15 UTC
