### ISSUE TITLE
Selecting value from dropdown options cause remaining HTML tags to disappear

### ISSUE THREAD

**Issue by sagarvd01** [Microsoft/vscode#30083] opened 2017-07-04 10:24 UTC
- VSCode Version: V 1.8.1
- OS Version: 10.0.14393 N/A Build 14393

Screen recording of Issue here 

[http://recordit.co/De1z2Mb049](http://recordit.co/De1z2Mb049)

Steps to Reproduce:

1. Type some html tag and close with it's pair tag.
2. Try to add an attribute to the tag and choose the value from drop down list.

Reproduces without extensions: Yes/No

**Comment by sagarvd01** [comment] 2017-07-10 10:24
@aeschli any update on this?

**Comment by aeschli** [comment] 2017-07-11 09:43
It's a duplicate of #30107. Please add your vote there.

**Closed by aeschli** 2017-07-11 09:43 UTC
Labels: html
