### ISSUE TITLE
vs throws error after autocomplete

### ISSUE THREAD

**Issue by Draethorian** [Microsoft/vscode#9981] opened 2016-07-30 15:29 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

![capture](https://cloud.githubusercontent.com/assets/19950085/17271422/34ccd588-567b-11e6-8d86-4a637822a5b0.PNG)

It actually works, but VSC  doesn't update

**Comment by kieferrm** [comment] 2016-08-02 05:02
@Draethorian pls provide reproducible steps. What was the content of the file before and after you invoked intellisense? Where was the cursor? The error message seems to indicate that the linter saw only `./like.componen` rather than the whole string. Did you perform any additional edits?

**Comment by dbaeumer** [comment] 2016-11-15 19:22
Closing since no additional information has been provided and I am not able to reproduce the issue.

**Closed by dbaeumer** 2016-11-15 19:22 UTC
Labels: needs more info, not-reproducible, typescript
