### ISSUE TITLE
jQuery not supported in new version

### ISSUE THREAD

**Issue by rkralston** [Microsoft/vscode#8954] opened 2016-07-08 14:34 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. This is an Angular2 application built with the CLI
2. I am loading jQuery in the index.html
3. I am using typings 1.3.0
4. I have jquery.d.ts installed in the typings directory and referenced in index.d.ts
5. The old version recognized jQuery. The new one does not.

I am trying to release production code and really need jQuery in my typescript.

**Comment by dbaeumer** [comment] 2016-07-11 14:46
If you newly generated the project you might be hit by https://github.com/angular/angular-cli/issues/684.

If not, can you share the project or an example reproducing it. With the steps above it is very hard to find out what is going wrong.

**Comment by rkralston** [comment] 2016-07-11 15:27
Not a new project.

angular-cli: 1.0.0-beta.6
node: 6.1.0
os: win32 x64

We are using a private repo on BitBucket. I think I am OK to share the project to an email address. I will double check with the university; if so, would it be OK to share it with your email?

**Comment by dbaeumer** [comment] 2016-07-12 07:33
Yes, that is OK for me.

**Comment by rkralston** [comment] 2016-07-12 15:56
I think I have it partly figured out. There is an inconsistency between VS Code's TS compiler and the Broccoli TS compiler and how they handle the setup files. I am attaching two sets of zipped TS configuration files one set works with VS Code and clears all of its errors. The other one works with the Broccoli compiler. The Broccoli settings break VS Code. The VS Code setting break Broccoli.
[broccoli_settings.zip](https://github.com/Microsoft/vscode/files/359764/broccoli_settings.zip)
[vs_code_settings.zip](https://github.com/Microsoft/vscode/files/359765/vs_code_settings.zip)

**Comment by rkralston** [comment] 2016-07-12 17:36
Since this is our authentication application, we created a new repo and sent you an invitation. Please let me know when you are finished so I can delete it.

**Comment by rkralston** [comment] 2016-07-12 17:36
Thanks

**Comment by dbaeumer** [comment] 2016-07-13 10:55
The problem is the tsconfig.json file. As soon as you list files in that file the project defined by the trsconfig.json file only consist out of these files. See https://code.visualstudio.com/docs/languages/typescript.

So if you afterwards open for example main.ts this file will get its own virtual project with no relation to the tsconfig.json file in root and therefore with no reference to the typings.

You can either move your typings into source or do the following:

- remove the files section from tsconfig.json
- add a refTypings.d.ts file inside the src folder with the following content
```ts
/// <reference path="../typings/index.d.ts" />
```

This made the project work for me.

**Comment by rkralston** [comment] 2016-07-13 14:02
Ja that works for VS Code, but it breaks Broccoli.





On Wed, Jul 13, 2016 at 5:56 AM -0500, "Dirk Bäumer" <notifications@github.com> wrote:





The problem is the tsconfig.json file. As soon as you list files in that file the project defined by the trsconfig.json file only consist out of these files. See https://code.visualstudio.com/docs/languages/typescript.

So if you afterwards open for example main.ts this file will get its own virtual project with no relation to the tsconfig.json file in root and therefore with no reference to the typings.

You can either move your typings into source or do the following:

- remove the files section from tsconfig.json
- add a refTypings.d.ts file inside the src folder with the following content
```ts
/// <reference path="../typings/index.d.ts" />
```

This made the project work for me.

---

**Comment by dbaeumer** [comment] 2016-07-13 14:24
@rkralston I don't know Broccoli well enough to say what is wrong. But the tsconfig section with the files section can't work in VS due to the fact how the tsconfig file is specified. Have you talked to the Broccoli. Might be a problem on their end.

**Comment by rkralston** [comment] 2016-07-13 14:31
I am also talking with the Angular2 CLI group at Google who are using that compiler.


The two zip files I attached show the changes I have tried that were mutually exclusive between the two compilers. I don't know if it was exactly what you proposed. I have a developer trying exactly what you proposed now.


However, I believe the issue is going to be a fundamental difference in how the two compilers do configuration.


I will also log an issue with Broccoli and link it to this one and the one in Angular2 CLI.





On Wed, Jul 13, 2016 at 9:25 AM -0500, "Dirk Bäumer" <notifications@github.com> wrote:





@rkralston I don't know Broccoli well enough to say what is wrong. But the tsconfig section with the files section can't work in VS due to the fact how the tsconfig file is specified. Have you talked to the Broccoli. Might be a problem on their end.

---

**Comment by alta189** [comment] 2016-07-13 19:46
@rkralston I was having the same issue. I was able to resolve it by changing the files section of tsconfig.json to 

```json
"files": [
    "main.ts",
    "typings.d.ts",
    "app/**/*.ts"
  ]
```

**Comment by rkralston** [comment] 2016-07-13 20:56
I tried several different permutations. It still appears to me that the two environments are exclusive.

This is odd, b/c two revisions of VS Code back, the "files" section worked OK with a little tinkering. Currently any entry there is turning everything else off.

Broccoli or Angular CLI, I'm really not sure which rely on this setting for TS configuration.

I could not find the place to start with Broccoli. I will see if Angular CLI can help from that side.

Not really sure how to proceed. I really like VS Code, but I'm committed to Angular2 CLI for front end development. VS2015 is not an option either. It keeps blowing up when I load an Angular project.

**Comment by rkralston** [comment] 2016-07-14 16:36
Looking at broccoli-typescript.js, it looks like CLI is using the 'files' key and excluding any *.d.ts that are not in that list. Can we remove that and use whatever files are in the directory?

**Comment by rkralston** [comment] 2016-07-14 16:41
Tried that, not good. Can we put that list in a different place since that is non-standards compliant?

**Comment by rkralston** [comment] 2016-07-14 16:51
I see what you are saying. Unfortunately, it looks like CLI is using that key, not necessarily the compiler. They are filtering typings inclusions with it to manage their compiler. When I remove their filter, it creates some serious issues. I will report that on the link above with CLI.

**Comment by dbaeumer** [comment] 2016-08-02 13:17
@rkralston sorry for not responding. Was on vacation :-). Could you find out anything on the CLI front ?

**Comment by rkralston** [comment] 2016-08-02 13:34
Ja. They have switched from SystemJS to WebPack. In doing so, they closed out all outstanding bugs of this nature. It will be in the next release, 11. That release is still pending so I only have their word on it.

If they did fix this, then Code should be happy and Angular2/Core 1.0 should work much better.

I will post here once I have tested their next release.

Thanks for your help.

**Comment by dbaeumer** [comment] 2016-08-03 13:51
Thanks for following up with the CLI team.

**Comment by dbaeumer** [comment] 2016-11-15 19:26
Closing the issue. @rkralston please ping if this still reproduces for you.

**Closed by dbaeumer** 2016-11-15 19:26 UTC
Labels: needs more info, typescript
