### ISSUE TITLE
Proposal: Ability to move Debugging bar - or auto-shift for long file location paths

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#6221] opened 2016-05-09 23:01 UTC
Is it possible to have the `debugging bar`? It's difficult to see the file currently being viewed in when you're stepping through a debug process.

It'd be nice for it to either (self-shift) for long *location paths* or be able to move it someplace yourself. When debugging through large Node applications you can't see exactly what file you're working on, or where it is located. You have to constantly hover over the tab to see it.

Love code otherwise, great job guys :)

**Comment by isidorn** [comment] 2016-05-10 06:04
Thanks for the suggestions however this is a dupe of #4580

**Closed by isidorn** 2016-05-10 06:04 UTC

**Comment by MarkPieszak** [comment] 2016-05-10 11:38
Ahhh I didn't find that one! Apologies.
Hopefully it's on the radar :)
