### ISSUE TITLE
Path variables should optionally be available in unix format

### ISSUE THREAD

**Issue by squelart** [Microsoft/vscode#57579] opened 2018-08-30 07:53 UTC
On Windows, I would like to use ${workspaceFolder} in a command that will be run in a unix-like environment (msys).

E.g., ${workspaceFolder} gives something like 'C:\work\prj', but instead I would like to get '/c/work/prj'.

**Comment by dbaeumer** [comment] 2018-08-30 07:56
You are referrring to variables in tasks.json. Right.

**Comment by squelart** [comment] 2018-08-30 08:04
Ah yes, that's right.

So in my project's tasks.json I could have something like:
... "tasks": [ { "windows": { "command": "\"\\msys\\start-shell.bat ${workspaceFolderUnix}/mach\"" } ...
And the last bit would resolve to '/c/work/repo/mach', instead of 'C:\work\repo/mach'.
(This start-shell.bat does a `bash.exe --login -i -c "%*"`, so the commands in "%*" are in the bash environment expecting unixy paths.)
Thanks!

**Comment by alexr00** [comment] 2019-01-04 11:09
The root of this issue is about better handling of paths across platforms. Duplicate of #38381.

**Closed** 2019-01-04 11:10 UTC
Labels: *duplicate, feature-request, tasks
