### ISSUE TITLE
there is no animation when clicking the synchronize changes button on status bar.

### ISSUE THREAD

**Issue by xiaoyueguang** [Microsoft/vscode#24172] opened 2017-04-07 05:44 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.5|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.2.0|
|vscode-html-css|ecmel|0.0.34|
|tortoise-svn|fantasytyx|0.1.1|
|php-intellisense|felixfbecker|1.1.4|
|flow-for-vscode|flowtype|0.5.0|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|emoji-code|idleberg|0.1.11|
|ftp-sync|lukasz-wronski|0.3.2|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-fileheader|mikey|0.0.2|
|vscode-autoprefixer|mrmlnc|2.0.0|
|mssql|ms-mssql|0.3.0|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|emoji|Perkovec|0.0.3|
|datetime|rid9|1.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|sass-indented|robinbentley|1.3.1|
|code-settings-sync|Shan|2.6.2|
|stylelint|shinnn|0.23.0|
|vscode-todo-highlight|wayou|0.4.14|;

---

Steps to Reproduce:

1.
2.

**Comment by jsynowiec** [comment] 2017-04-07 05:54
Duplicate of #23975

**Closed** 2017-04-07 06:05 UTC
