### ISSUE TITLE
CSS auto complete not work

### ISSUE THREAD

**Issue by valeri879** [Microsoft/vscode#20018] opened 2017-02-06 09:04 UTC
- VSCode Version: 1.9
- OS Version: Windows 10 Home

Steps to Reproduce:

1.  sometimes css auto complete not work for me

**Comment by bpasero** [comment] 2017-02-06 10:19
@valeri879 can you provide more details about your setup and extensions?

**Comment by valeri879** [comment] 2017-02-07 08:57
@bpasero I deleted all extensions and reinstall  `code` but after 1 day still not working auto complete

**Comment by aeschli** [comment] 2017-02-07 09:21
Can you paste the code example?
Can you open the developer tools (Help > Toggle Developer Tools) and see if there is anything in the console?

**Comment by valeri879** [comment] 2017-02-07 10:37
here is screenshot

![capture](https://cloud.githubusercontent.com/assets/6426966/22687809/f6de3172-ed42-11e6-80ea-541e12c5e310.PNG)

**Comment by valeri879** [comment] 2017-02-13 09:32
@aeschli @bpasero Guys help me please, I really like this editor, but without suggestion it's very useless

**Comment by aeschli** [comment] 2017-02-17 16:49
duplicate of #19840

**Closed by aeschli** 2017-02-17 16:49 UTC
Labels: needs more info
