### ISSUE TITLE
activation event: "onView:timeline" doesn't seem to work

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91723] opened 2020-02-27 23:30 UTC
I have a simple extension to contribute static timeline entries, but it does not seem to activate with `onView:timeline`.  Using `*` works fine.

**Comment by eamodio** [comment] 2020-03-02 20:41
We don't currently support any specific activation for the timeline view -- we will look into adding that in the future.

**Comment by eamodio** [comment] 2020-04-07 03:47
Duplicate of #94151

**Closed by eamodio** 2020-04-07 03:47 UTC
Labels: *duplicate, feature-request, timeline
