### ISSUE TITLE
Syntax highlighter results look differently in insider build

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#2637] opened 2016-02-02 09:27 UTC
Syntax highlighter shows different results in stable and insider build. I don't think it's intended.
Left: 0.10.6 
Right: 0.10.7 

![color2_dec15vsjan16](https://cloud.githubusercontent.com/assets/3448684/12744905/1d7c0b5e-c997-11e5-9fdd-c6dac1aee302.png)

**Comment by jrieken** [comment] 2016-02-02 09:38
@egamma fyi

**Comment by egamma** [comment] 2016-02-02 11:23
@wosi what theme did you use when creating the 0.10.6 typescript screenshot above, can you pls check? 

I can reproduce TypeScript on the right when using the Dark+ color theme in 0.10.7.
But I cannot reproduce what you show above in 0.10.6 when using the Dark+ color theme extension. To me 0.10.6 and 0.10.7 look the same. 

```TypeScript
declare var require: {
    (id: string): any;
    resolve(): string;
    cache: any;
    extensions: any;
}
```

**Comment by Wosi** [comment] 2016-02-02 12:27
@egamma 
I created the screenshot on a Windows 10 machine using VSCode 0.10.6 (stable) and 0.10.7 (insider) with the Dark+ theme.
I have currently no access to this machine, so I can't check it but I'm quite sure about this setup.

I made the screenshot below on a Windows 7 machine. The Dark+ theme shows the same here for TypeScript in both version 0.10.6 and 0.10.7. 

![color2_jan16_cas](https://cloud.githubusercontent.com/assets/3448684/12748911/afa33852-c9ad-11e5-8b76-8f322d58265a.png)

With OmniPascal I see the same differences on both machines. I'm not sure whether these changes have come due to API changes or a bug. I did't find anything about API changes with the highlighting engine. Please let me know if there are some.

**Comment by Wosi** [comment] 2016-02-02 23:40
@egamma I checked my environment again: The left side of the initial screenshot was made with 
VSCode 0.10.6 and Dark+ (Experimental) theme.

**Comment by egamma** [comment] 2016-02-03 08:16
@aeschli can you investigate into this
>With OmniPascal I see the same differences on both machines. I'm not sure whether these changes have come due to API changes or a bug. I did't find anything about API changes with the highlighting engine. Please let me know if there are some.

**Comment by aeschli** [comment] 2016-02-03 11:09
I can reproduce the different coloring for the OmnoPascal sample for the ifdef and type token
The first and last line use `annotation.block.objectpascal`, the type `type.objectpascal'.
The change of coloring was caused by my clean up of the token colors css. We used to have colors for both 'annotation' and 'type', but I removed them as both are not standard text mate scopes and caused unwanted matches to other scopes inside a type declaration.
The best would be if the OmniPascal could use `storage.type` for type names. For imports maybe use `keyword.control.import`. Which scopes to use is not so easy to decide. I'm been using https://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai and http://www.apeth.com/nonblog/stories/textmatebundle.html as a reference.

**Comment by Wosi** [comment] 2016-02-03 11:42
@aeschli Thanks a lot for your help! I was able to fix the `.plist` file. I replaced `annotation.block.objectpascal` with `token.metatag` so it looks exactly like it used before. In case you decide to delete this token too then I will replace it with `keyword.control.import` as you suggested.

**Comment by aeschli** [comment] 2016-02-03 12:56
On the Typescript issue, as mentioned by @egamma, there hasn't been any change for the last update. But of course the current coloring should be improved. I'm waiting for https://github.com/Microsoft/TypeScript-TmLanguage/issues/23 to be implemented, then we could give a better experience for object literals. 

I'm closing this issue as what you observed are the currently expected results.

**Closed by aeschli** 2016-02-03 12:56 UTC
Labels: stable-candiate
