### ISSUE TITLE
Generalize `TextEditor`-related APIs

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#31470] opened 2017-07-26 18:05 UTC
As far as I know there is no API for working with "non-text editors", for instance if we open an unsupported binary file it would be useful to be able to get it's path, so that we can provide some "Open in %APP%" commands for it.

What do you think?

**Comment by jrieken** [comment] 2017-07-27 07:31
duplicate of #14483

**Closed by jrieken** 2017-07-27 07:31 UTC
Labels: api
