### ISSUE TITLE
[folding] Provide an editor setting for always folding block comments

### ISSUE THREAD

**Issue by muhammadsammy** [microsoft/vscode#102889] opened 2020-07-19 11:05 UTC
It would be very nice to have a global setting that makes the editor always fold block comments instead of manually running `Fold All Block Comments` command for every file.

**Comment by aeschli** [comment] 2020-08-11 09:09
duplicate of https://github.com/microsoft/vscode/issues/40338

**Closed by aeschli** 2020-08-11 09:09 UTC
