### ISSUE TITLE
Difficult to see where Explorer Outline lands

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115202] opened 2021-01-27 08:52 UTC
Testing #114902

* open `.vscode/notebooks/my-work.github-issues` and click on the markdown outline entries
* it is difficult to see where the actual outline is because there is nothing rendered to indicate where I landed

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105966189-9b286f00-6084-11eb-95da-cbb3afa1ca62.gif)

As a comparison, in the editor there is some "current line" affordance to help with that (even if it is somewhat weak and does not flash):
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105966356-d460df00-6084-11eb-8792-fa875c9188cc.gif)

**Comment by jrieken** [comment] 2021-01-27 09:23
Yeah, fully agree. Internally we do set the selection to the cell in question but it seems that have no rendering unless the notebook editor has focus

**Comment by misolori** [comment] 2021-01-27 14:19
I believe this is being tracked in https://github.com/microsoft/vscode/issues/114219

**Comment by jrieken** [comment] 2021-01-27 14:46
I was thinking so

\duplicate of #114219

**Closed** 2021-01-27 14:46 UTC
Labels: *duplicate, notebook, under-discussion, ux
