### ISSUE TITLE
.config/Code/ dir gets large

### ISSUE THREAD

**Issue by maep--** [Microsoft/vscode#30718] opened 2017-07-14 15:20 UTC
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
cpptools|ms-|0.12.0
---

Problem:
VSCode consumes 600 MB of my home dir. In .config/Code/ User/, CachedData/ and Cache/ use about 200 MB each. Our home dirs are on a network drive and are limited by a quota. I have no say about it's size.

Some suggestions to mitigate this:

- In Linux caches should be stored in ~/.cache/ which I can symlink to local storage.
- Setting to change location of addons or large storage.
- Perhaps advertise how much space addons require

**Comment by Tyriar** [comment] 2017-07-14 17:35
Duplicate of https://github.com/Microsoft/vscode/issues/3884

**Closed by Tyriar** 2017-07-14 17:35 UTC
Labels: linux, new release
