### ISSUE TITLE
Use fuzzy match in `Select Language Mode` picker

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#47424] opened 2018-04-08 09:04 UTC
It now uses some poor kind of logic: takes in consideration only first letters of words (and UPPERCASED).

#### JavaScript:
`jsc`=> ✅ 
`jscpt` => ❌
`jpt` => ❌
`jcp` => ❌

**Comment by bpasero** [comment] 2018-04-08 10:02
Duplicate of https://github.com/Microsoft/vscode/issues/34088

**Closed by bpasero** 2018-04-08 10:02 UTC
Labels: editor
