### ISSUE TITLE
copying (Ctrl + C) selected text from the terminal terminates the current application that is running in it

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#7347] opened 2016-06-07 18:54 UTC
- VSCode Version: 1.2
- OS Version: Windows 7, x65

Steps to Reproduce:

1. Open the terminal from within VS code
2. Do `git log`
3. Observe a first page of the command output (while the pager is awaiting for continuation)
4. Select a piece of the output text.
5. Attempt to copy the selected piece using `Ctrl + C`
6. Observe `git log` terminated.

Expected: text copied while application is still running

:+1:

**Comment by Tyriar** [comment] 2016-06-07 19:02
Duplicate of https://github.com/Microsoft/vscode/issues/6451

**Closed by Tyriar** 2016-06-07 19:02 UTC
