### ISSUE TITLE
Rename symbol does not show complete symbol name

### ISSUE THREAD

**Issue by Jimmyzaurio** [microsoft/vscode#96098] opened 2020-04-24 22:14 UTC
Issue Type: <b>Bug</b>

Type a text with more than 16 characters
Set text cursor after the 16th characters and press F2 (rename symbol)
The small box will show the 15 characters that are behind the current cursor and the rest of the symbol name after the cursor.

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T05:57:41.076Z)
OS version: Windows_NT x64 10.0.19616

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (49.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-idl|kur|0.1.2
devinsights|Mic|2020.4.16-1
vscode-nmake-tools|Mic|3.0.200422007
cpptools|ms-|0.27.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2020-04-27 07:41
/duplicate of https://github.com/microsoft/vscode/issues/96013

**Closed** 2020-04-27 07:41 UTC
Labels: *duplicate

**Comment by jrieken** [comment] 2020-04-27 07:48
@Jimmyzaurio In what language have you seen this happening? There has been similar report but this isn't easily reproducable

<img width="509" alt="Screenshot 2020-04-27 at 09 47 42" src="https://user-images.githubusercontent.com/1794099/80347103-25307680-886c-11ea-9b13-f39c1a7ed0e8.png">

**Comment by jrieken** [comment] 2020-04-27 07:52
nvm - this happens with c, not with TS 🤷‍♂️
