### ISSUE TITLE
Account Sync in-app Authentication

### ISSUE THREAD

**Issue by Chiramisu** [microsoft/vscode#145348] opened 2022-03-17 19:32 UTC
Is it possible to authenticate with Microsoft or GitHub within the app rather than opening a browser window? If possible, I think this would be a more ideal implementation. Thank you for this native settings syncing feature.

**Comment by yume-chan** [comment] 2022-03-18 10:37
Users may have already signed in in their browsers. Signing in within the App means all users must re-enter their credentials.

**Comment by Chiramisu** [comment] 2022-03-18 19:00
I'm always signed in on my browser, and yet I STILL have to authenticate through the app, so clearly this doesn't matter. At least not in my experience. Perhaps you have some special configuration that allows your authentication token to be passed from your browser to VS Code? Though I would doubt this, and would be very concerned about the security implications of that.

**Comment by TylerLeonhardt** [comment] 2022-03-21 23:12
I'm not sure I understand the request. Are you expecting to type your username & password into a VS Code window instead of going to your browser and then coming back?

**Comment by Chiramisu** [comment] 2022-03-23 16:58
Many websites have an authentication API that can be used by desktop applications for secure authentication to the service / website via the app, without exposing your credentials to the app itself. Therefore, if this can be done securely in a similar fashion, I think this would be preferable.

**Comment by TylerLeonhardt** [comment] 2022-03-23 22:21
I'm sorry @Chiramisu. I'm not quite following. Do you have an example maybe of an app you like that does it this way?

**Comment by Chiramisu** [comment] 2022-03-30 02:22
Sure. Visual Studio. LOL. 😉

**Comment by TylerLeonhardt** [comment] 2022-04-02 04:09
I see! Ok so this is actually a duplicate of https://github.com/microsoft/vscode/issues/142080 so I'll close this in favor of that

**Closed by TylerLeonhardt** 2022-04-02 04:09 UTC
Labels: needs more info

**Comment by Chiramisu** [comment] 2022-04-07 18:48
Thank you sir. I did search before posting this, but didn't find that one. Good find. That indeed sounds like what I'm asking for. Cheers.
