### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Julio-Freitas** [microsoft/vscode#139814] opened 2021-12-27 20:49 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:27.690Z)
OS version: Linux x64 5.13.0-19-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|15.46GB (0.55GB free)|
|Process Argv|--unity-launch /home/julio/Documentos/LetrasAcademyFrontend --crash-reporter-id 6521ed1b-1acf-4156-8550-2ac7dfecd1e8 --crash-reporter-id 6521ed1b-1acf-4156-8550-2ac7dfecd1e8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.64.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804:30404766
vscop940:30404999
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t2:30407759
azactmsalcf:30409288

```

</details>

**Comment by IllusionMH** [comment] 2021-12-28 06:57
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2021-12-28 06:58 UTC
Labels: *duplicate
