### ISSUE TITLE
Undo delete while using RBL puts cell into weird state

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#134058] opened 2021-09-28 21:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Insiders
- OS Version: Mac

Steps to Reproduce:

1. Install jupyter extension
2. Start run by line for a cell
3. Delete that cell
4. Undo the delete of the cell
	5. Notice the `stop` indicator for the cell
5. Star run by line for another cell.
	6. Confirm this works
	7. Notice the stop indicator & the timer for the previous cell

@roblourens @DavidKutu /cc

**Comment by DavidKutu** [comment] 2021-09-28 21:46
I think this is a dupe of https://github.com/microsoft/vscode/issues/133782

**Closed** 2021-09-28 21:54 UTC
