### ISSUE TITLE
Entering path with slashes in quick open doesn't work anymore

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode#95322] opened 2020-04-15 10:54 UTC
Issue Type: <b>Bug</b>

After updating to the April insiders release, using quick open to paste/enter a path with slashes no longer works (win10 host, linux ssh remote):

![image](https://user-images.githubusercontent.com/179599/79329362-f3d4b400-7f17-11ea-81d4-66514b938c10.png)

when replacing the slashes with spaces it works though, but of course that's not practical when copying the path from somewhere else.

![image](https://user-images.githubusercontent.com/179599/79329347-ecada600-7f17-11ea-8000-9415b7f94949.png)

I think this might be a regression from #81169.

---

VS Code version: Code - Insiders 1.45.0-insider (1c36d747fbf113144d3bf82b0aa3cbd290714e38, 2020-04-15T05:37:18.376Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.14.83-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blackhole|
|OS|Linux x64 4.14.83-gentoo|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 1500)|
|Memory (System)|15.53GB (3.29GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
viml|dun|0.1.7
tmux|mal|0.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.12.0
gitconfig|sid|2.0.1
vscode-icons|vsc|10.1.1
vscode-module-templates|asb|0.4.0
quick-open-prefill-selection|col|0.0.1
vscode-eslint|dba|2.1.3
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.4.0
vscode-pull-request-github|Git|0.15.0
search-editor-apply-changes|jak|0.1.1
puppet-vscode|jpo|0.24.2
vsc-python-indent|Kev|1.8.1
restructuredtext|lex|126.0.0
MagicPython|mag|1.1.0
vscode-github-actions|me-|2.2.7
vscode-docker|ms-|1.0.0
python|ms-|2020.4.71763-dev
Go|ms-|0.13.1
vscode-yaml|red|0.7.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2020-04-16 04:47
Since this seems to be remote specific, I would argue this is a duplicate of https://github.com/microsoft/vscode/issues/94871

**Closed by bpasero** 2020-04-16 04:48 UTC
