### ISSUE TITLE
Git panel always displays "scanning" progress bar.

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#36756] opened 2017-10-23 14:50 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (c1be82537d9fda852a258851f48ea78b7fc8a7a3, 2017-10-23T05:12:06.273Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-eslint|dba|1.3.2
gitlens|eam|5.7.1
tslint|eg2|1.0.12
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.9.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.30.0
Align|ste|0.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Activate the source control page
2. the animated "scanning" bar runs continuously.

<img width="320" alt="screen shot 2017-10-23 at 10 48 32 am" src="https://user-images.githubusercontent.com/835148/31895709-ebc00046-b7df-11e7-9e68-51193684672b.png">

**Comment by maxibanki** [comment] 2017-10-23 15:31
Duplicate of #36754

**Closed** 2017-10-25 04:44 UTC
