### ISSUE TITLE
Tab close icon's usability can be improved

### ISSUE THREAD

**Issue by marcoms** [Microsoft/vscode#31227] opened 2017-07-21 21:07 UTC
Currently the active appearance of a tab close icon scales it by a small amount.

![close](https://user-images.githubusercontent.com/4211302/28482024-75747e78-6e5e-11e7-9339-4fe8e8c2c828.gif)

To me this has always felt a bit off, as it goes against a lot of clicking affordance that we see on most UIs, which is generally an altered background. Scaling or elevation works with material design because each element is usually its own card which can transform by itself.

I made a change in devtools using the `filter()` function for the active state, and I think it feels a lot more natural

![close-alt](https://user-images.githubusercontent.com/4211302/28482163-1cdc1c48-6e5f-11e7-8387-eefa9c521413.gif)

Also, since both the cursor is set to `pointer` on the entire tab, *and* there isn't hover state for the close icon, there's no hover affordance to the user to tell them that they are on something clickable. Probably either `cursor: pointer` should only be set on the icon .. or there should be a distinct hover state on the icon (like Atom)

>![close-atom 1](https://user-images.githubusercontent.com/4211302/28482529-ae2a1744-6e60-11e7-8fb4-9c2e94e92322.gif)
>--Atom example

**Comment by marcoms** [comment] 2017-07-21 23:23
Just realized this applies to all other components which use the `action-item` class

**Comment by rmunn** [comment] 2017-07-25 07:42
That third GIF, showing a different-colored background appearing over the close button when it is clickable, is an excellent idea. It provides immediate visual feedback of the *entire* active region (by "active region" I mean "if you click here, it will do something") available to click on. That idea gets a :+1: from me.

**Comment by marcoms** [comment] 2017-09-06 13:55
@bpasero Could I work on this or does it need some design work first?

**Comment by bpasero** [comment] 2017-09-06 14:00
I do not think we would easily accept a PR in this area because of:

> Just realized this applies to all other components which use the action-item class

Unless this was themable similar to our icons and colors.

**Comment by marcoms** [comment] 2017-09-06 14:24
Sorry not sure I understand. Could we not just edit this ruleset https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/actionbar/actionbar.css#L39 with something palette neutral like `rgba(255, 255, 255, 0.25)` for hover/focus, and `rgba(0, 0, 0, 0.25)` for active states

**Comment by bpasero** [comment] 2017-09-06 14:46
@marcoms yes we could, but this is going to every action and there maybe users that do not like the change. That is why I was indicating that something like that should ideally be configurable through settings and theming.

**Comment by marcoms** [comment] 2017-09-09 13:49
Doesn't vscode only allow the user to configure colors for the foreseeable future? Or is there plans to support more theming capabilities if that's what you mean?

**Comment by bpasero** [comment] 2017-12-03 15:47
Closing as designed, there are no plans to change this atm.

**Closed by bpasero** 2017-12-03 15:47 UTC
Labels: feature-request, ux, workbench-tabs
