### ISSUE TITLE
Default Terminal (WSL) Not Opening with VS Code Launch

### ISSUE THREAD

**Issue by LorenzoVicente** [microsoft/vscode#132753] opened 2021-09-09 13:11 UTC
Issue Type: <b>Bug</b>

Ever since this most recent release of VS Code (1.60.0), my default terminal of WSL no longer opens when I launch VS Code.  Instead, it opens PowerShell. I can exit out of PowerShell, then open a terminal window and WSL opens.

<details>
<summary>Terminal Configuration from settings.json</summary>

Here is the section of my settings.json file related to terminal configuration:
```
    "terminal.integrated.defaultProfile.windows": "WSL",
    "terminal.integrated.profiles.windows": {
      "WSL": {
        "path": "C:\\WINDOWS\\System32\\wsl.exe",
        "args": [
          "~"
        ],
        "icon": "terminal-ubuntu"
      },
      "Git Bash": {
        "source": "Git Bash",
        "icon": "terminal-bash"
      },
      "Command Prompt": {
        "path": [
          "${env:windir}\\System32\\cmd.exe"
        ],
        "args": ["/K cls && cd /D C:\\OD"],
        "icon": "terminal-cmd"
      },
      "PowerShell": {
        "source": "PowerShell",
        "icon": "terminal-powershell"
      }
    }
```
</details>

<details>
<summary>VS Code Version Info</summary>

Here is the current version information for VS Code:
```
Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
```
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.21GB free)|
|Process Argv|--crash-reporter-id 669c5aa9-cc1e-4a43-99fb-bb4bd0826854|
|Screen Reader|no|
|VM|0%|
</details>

<details><summary>Extensions (127)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
Bookmarks|ale|13.2.1
project-manager|ale|12.4.0
vscode-sqlite|ale|0.13.0
arepl|alm|2.0.3
to|ami|0.0.10
ng-template|Ang|12.2.0
asciidoctor-vscode|asc|2.8.9
vscode-django|bat|1.6.0
vagrant|bbe|0.5.0
springboot-extension-pack-extended|bud|0.0.1
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.43.2
vscode-springboot-developer-pack|dev|1.0.3
vscode-springboot-snippets|dev|1.2.0
java-decompiler|dgi|0.0.2
githistory|don|0.6.18
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
vscode-python-pack|dse|1.4.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
vscode-vibrancy|eyh|1.0.16
vscode-install-vsix|fab|1.4.0
git-project-manager|fel|1.7.1
opensslutils|ffa|1.1.1
vscode-firefox-debug|fir|2.9.4
shell-format|fox|7.1.0
vscode-lombok|Gab|1.0.1
angular-cli-task-provider|Gen|1.3.2
vscode-javac|geo|0.2.39
gitlab-workflow|Git|3.29.1
go|gol|0.27.2
cloudcode|goo|1.14.0
todo-tree|Gru|0.0.214
terraform|has|2.14.0
beautify|Hoo|1.5.0
smarty|imp|0.3.0
kubernetes-snippets|ipe|0.1.9
java-properties|ith|0.0.2
plantuml|jeb|2.15.1
vscode-gnupg-tool|JHe|1.3.9
vscode-java-dev-tools-pack|lar|1.0.0
MagicPython|mag|1.1.0
spring-boot-pack|mal|0.0.1
eclipse-new-java-project|mel|1.0.1
python-path|mge|0.0.11
mp-rest-client-generator-vscode-ext|Mic|0.1.2
mp-starter-vscode-ext|Mic|0.2.6
vscode-microprofile-pack|Mic|0.1.2
fluent-icons|mig|0.0.12
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-aks-tools|ms-|0.0.9
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
vscode-postgresql|ms-|0.3.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
sqltools|mtx|0.23.0
gradle-language|nac|0.2.3
vsc-mybatis|nik|1.2.0
vetur|oct|0.34.1
remote-kubernetes|Okt|0.3.4
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.27.0
vscode-manifest-yaml|Piv|1.27.0
vscode-spring-boot|Piv|1.27.0
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
ponicode|Pon|0.50.1
vscode-jsp|pth|0.0.3
java-ide-pack|pve|1.2.1
vscode-p3c|Rec|0.1.2
java|red|0.81.0
project-initializer|red|0.2.1
vscode-commons|red|0.0.6
vscode-community-server-connector|red|0.23.14
vscode-microprofile|red|0.3.0
vscode-openshift-connector|red|0.2.9
vscode-openshift-extension-pack|red|0.0.2
vscode-openshift-java-pack|red|0.0.2
vscode-quarkus|red|1.9.0
vscode-rsp-ui|red|0.23.9
vscode-server-connector|red|0.23.14
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
java-development-extensions-pack|ric|1.4.0
java-sysout|ric|1.0.1
vscode-gradle|ric|3.6.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.0
java-generate-setters-getters|soh|7.3.0
sonarlint-vscode|Son|2.1.2
vscode-jetty|Sum|0.1.11
prop2yaml|tan|0.1.0
ansible|tom|1.0.7
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
vscode-icons|vsc|11.6.0
Java-extension-pack|wal|0.0.3
footsteps|Wat|0.1.0
jinja|who|0.0.8
vscode-java-saber|You|0.1.2
markdown-all-in-one|yzh|3.4.0
vscode-ansible|zbr|0.4.6

(1 theme extensions excluded)

</details>

**Comment by albertosantini** [comment] 2021-09-09 14:47
It is a duplicate of #132150 (bug which is already fixed in Insiders build and supposed to be in upcoming Recovery release).

**Comment by IllusionMH** [comment] 2021-09-09 14:50
/duplicate
System default on VS Code launch is #132150 as mentioned above by @albertosantini

**Closed** 2021-09-09 14:51 UTC
Labels: *duplicate
