### ISSUE TITLE
Extensions not working after upgrade to 1.47.1

### ISSUE THREAD

**Issue by andriktr** [microsoft/vscode#102569] opened 2020-07-15 06:00 UTC
Hi, 
I'm running vscode version 1.47.1. It looks that after upgrade all my extensions not working anymore. All extensions are failing with the similar error: 
`Activating extension 'vscode-icons-team.vscode-icons' failed: The "path" argument must be of type string. Received type undefined.`
Any suggestions?

**Comment by dbaileyut** [comment] 2020-07-15 08:13
Looks like #102180

**Comment by andriktr** [comment] 2020-07-15 08:19
Seems so, yes

**Comment by allenyllee** [comment] 2020-07-16 14:00
I have the same problem too. Rollback to 1.46.1 everything works fine.

**Comment by sandy081** [comment] 2020-07-17 06:18
Probably a duplicate of #102082

Please follow this comment https://github.com/microsoft/vscode/issues/102082#issuecomment-657804049.

We made a fix and released new stable `1.47.1`. Can you please update and try ?

**Comment by andriktr** [comment] 2020-07-17 07:03
Just updated to the new version 1.47.2, but still getting the same, Also it seems that problem exists only when i run vs-code as admin user. Checked the %appdata%\code\user  extensions.json file is not exist there.

**Comment by sandy081** [comment] 2020-07-17 09:09
/duplicate

#102686

**Closed** 2020-07-17 09:09 UTC
Labels: *duplicate, needs more info
