### ISSUE TITLE
WebView not working on Ubuntu 21.10 dev branch

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#133575] opened 2021-09-22 04:21 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1, 1.61.0-insider
- OS Version: Ubuntu 21.10 (development branch)

Steps to Reproduce:

1. Launch VSCode release or insider
2. Open any WebView or Toggle Developer Tools
3. The WebView is blank and the Developer Tools panel are not open.

It is similar with #132455 but does not crash.

Start vscode with `--no-sandbox` could work (https://github.com/microsoft/vscode/issues/132455#issuecomment-924462278) but the gui performance does not look good.

**Comment by NoobTW** [comment] 2021-09-27 14:20
Same here.
- Does this issue occur when all extensions are disabled?: Yes
- VS Code version: 1.60.2 7f6ab5485bbc008386c4386d08766667e155244e x64
- OS Version: Ubuntu 21.10 Impish Indri (development branch)

Steps to Reproduce:
1. Launch VSCode
2. Crash.

Logs (Launch with `code --verbose`): https://pastebin.com/vu0a63YL

Start VSCode with `--no-sandbox` could work.

**Comment by mjbvz** [comment] 2021-09-27 20:28
This sounds like a duplicate of #125993

**Closed by mjbvz** 2021-09-27 20:28 UTC
Labels: *duplicate
