### ISSUE TITLE
change the debugger controls from a floating toolbar to a more in-line one?

### ISSUE THREAD

**Issue by devoncarew** [Microsoft/vscode#10724] opened 2016-08-19 21:35 UTC
- VSCode Version: 1.4.0
- OS Version: MacOS

I find that the floating debugger controls - while not taking up much space - can obscure tabs that I'm sometimes interested in seeing. I think moving the debugger controls to be in-line with the find controls would make the UI work a bit better.

<img width="455" alt="screen shot 2016-08-14 at 11 35 07 am" src="https://cloud.githubusercontent.com/assets/1269969/17824923/a5ab79aa-6619-11e6-88a9-9a32610ab54e.png">

If the debugger controls were in-line with the find (and the replace) controls, they would only obscure parts of the first few lines of a file instead of parts of the editor tabs. I think this would be an improvement. That in-line control could re-size as necessary to hold the debug panel, the find panel, and the replace panel.

**Comment by wallverb** [comment] 2016-08-19 23:47
I agree that current floating window gets in the way - especially if I have debugger running constantly. Maybe it could allow user to dock to couple of places. For me the best scenario would be like that:

![image](https://cloud.githubusercontent.com/assets/1723815/17827091/b55d90fa-6645-11e6-8c5e-7f7486700b8d.png)

**Comment by alexandrudima** [comment] 2016-08-22 08:11
fyi @weinand @stevencl

**Comment by isidorn** [comment] 2016-08-22 15:45
Somewhat of a duplicate of https://github.com/Microsoft/vscode/issues/9093
The bottomline issue is that we have to address the positioning of the debug toolbar and that is already captured in #9093, thus closing this one

**Closed by isidorn** 2016-08-22 15:45 UTC
Labels: debug, feature-request
