### ISSUE TITLE
Inconsistent undo/redo behavior in Ctrl-F field

### ISSUE THREAD

**Issue by obskyr** [microsoft/vscode#27035] opened 2017-05-21 16:28 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Press Ctrl-F
2. Type something into the field
3. Select some text in the file being edited
4. Press Ctrl-F again
5. Try to undo/redo using keyboard shortcuts

Characters will be deleted and added almost at random, based on the field's state before the contents were replaced in step 4. This seems to be because the undo/redo history stores characters being entered and deleted, but the replacement of the entire field contents *is not stored* on the field's history stack. If it were, an undo would simply revert the Ctrl-F field to its earlier state.

Other fields may have the same problem - the basic issue here is that an operation isn't being pushed to the history stack.

**Comment by rebornix** [comment] 2017-05-22 16:57
@obskyr I do occasionally run into this kind of issue when using the input box in Search Viewlet but I don't have a good repro. can you provide a gif to help troubleshoot?

**Comment by obskyr** [comment] 2017-05-22 17:14
@rebornix Sure! Here you go:

![Bug](https://cloud.githubusercontent.com/assets/4363779/26319969/6e2a0ef6-3f21-11e7-875d-497b0bb680cb.gif)

In this GIF, I:

1. Type "Hello!" into the main window
2. Press Ctrl-F
3. Type "abcdefg"
4. Select the "Hello!"
5. Press Ctrl-F
6. Press Ctrl-Z a few times
7. Press Ctrl-Shift-Z a few times
8. Press Ctrl-Z a few times
9. Press Ctrl-Shift-Z a few times
10. Press Ctrl-Z until it takes me out of the search field, and from there mess about with Ctrl-Z and Ctrl-Shift-Z a bit more

Also see this related buggy behavior:

![Bug 2](https://cloud.githubusercontent.com/assets/4363779/26320325/c904ac9a-3f22-11e7-884b-240065f75fb7.gif)


In this GIF, I:

1. Type "Hello!" into the main window
2. Select it
3. Press Ctrl-F
4. Press Ctrl-Z
5. Type lots of question marks in bewilderment as a second copy of "Hello!" appears where my cursor was in the main window (I've seen it appear in the middle of the word before, so I'm fairly certain it gets put where the cursor is/was.)

**Comment by rebornix** [comment] 2017-05-22 18:16
@obskyr I really appreciate your gif and reproduce steps :)

**Comment by rebornix** [comment] 2017-05-22 18:36
It's likely a browser issue as https://w3c.github.io/editing/execCommand.html#introduction is in draft and you can see weird behavior when playing Monaco Find Widget in Chromium but it's kind of good in Firefox.

**Comment by EmpireJones** [comment] 2018-08-21 19:51
@rebornix this bug seems to still exist and is super annoying. Is there a particular upstream project which we need to forward this issue to? monaco-editor ?

**Comment by rebornix** [comment] 2020-11-02 23:13
Now that we are using the shared history enabled input box, maybe we can improve the experience.

**Comment by sandy081** [comment] 2020-11-03 05:45
@rebornix Can you please elaborate what improvements you are expecting with history here?

**Comment by sandy081** [comment] 2020-11-13 11:46
Ping @rebornix ☝️

**Comment by rebornix** [comment] 2020-11-19 03:19
@sandy081 I found that `cmd+z` works in a weird way now in the find input, but I'm wondering if it's managed by the history feature

* Create an untitled text editor
* CMD+F to open the find widget, type in `abcdef`
* Focus the editor, type in `hello`
* CMD+F, which will replace the find input keyword to `hello`
* CMD+Z multiple times (in my test 4 times), and then the find input keyword becomes `hellohellohello`

**Comment by sandy081** [comment] 2020-11-19 18:22
I do not think cm+z is an history feature. Not sure who owns this. Sorry.

**Comment by amunger** [comment] 2022-12-13 18:14
this seems to be fixed now

**Closed by amunger** 2022-12-13 18:14 UTC
Labels: editor-find, under-discussion
