### ISSUE TITLE
Scrolling jumps around when scrolling outside of vs code

### ISSUE THREAD

**Issue by meeohh** [microsoft/vscode#83307] opened 2019-10-25 13:07 UTC
- VSCode Version: September 2019 (version 1.39)
- OS Version: Ubuntu 18.04.02 LTS

Steps to Reproduce:

1. Have an editor open on a certain file
2. Change the active window to some other application (chrome in my case)
3. Scroll around
4. Change the active window to vs code
5. On first scroll, the window jumps far away from where you were looking instead of scrolling properly

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2019-10-25 14:28
Duplicate of #28795

**Closed by alexandrudima** 2019-10-25 14:28 UTC
