### ISSUE TITLE
Help > Report Issue can't send issue

### ISSUE THREAD

**Issue by SleeplessByte** [Microsoft/vscode#42524] opened 2018-01-30 18:10 UTC
- VSCode Version: Code - Insiders 1.20.0-insider
- OS Version: Windows_NT x64 10.0.16299

CPUs | Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3406)
-- | --
Memory (System) | 31.91GB (21.59GB free)
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%

Steps to Reproduce:

1. Help > Report Issue
2. Fill in
3. Preview on Github

Does this issue occur when all extensions are disabled?: Yes

```
Object has been destroyed

Error: Object has been destroyed
    at WebContents.send (C:\Program Files\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:342:151
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:74:449)
    at Object.enter (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:77:778)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:79:573)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:79:14)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:342:786
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7): Error: Object has been destroyed

Error: Object has been destroyed
    at WebContents.send (C:\Program Files\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:342:151
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:74:449)
    at Object.enter (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:77:778)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:79:573)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:79:14)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:342:786
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:585)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by isidorn** [comment] 2018-01-31 08:53
This is acutally caused by our asar work
Should be fixed in latest insiders -> closing
@SleeplessByte let us know if you stilll see it with latests insiders

**Closed by isidorn** 2018-01-31 08:53 UTC
