### ISSUE TITLE
git diff don't work

### ISSUE THREAD

**Issue by Eyrum** [Microsoft/vscode#36022] opened 2017-10-11 06:19 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-jest|Ort|2.4.1
ReactSnippetsStandard|Tim|1.1.0
vscode-standardjs-snippets|cap|0.7.3
vscode-standardjs|che|1.2.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
reasonml|fre|1.0.2
ocaml|hac|0.6.41
MagicPython|mag|1.0.12
debugger-for-chrome|msj|3.3.1
vscode-scheme|sjh|0.3.1
vscode-react-native|vsm|0.4.2
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-11 09:54
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment] 2017-10-13 07:39
Closing, please reopen with more information.

**Closed by egamma** 2017-10-13 07:39 UTC
Labels: needs more info
