### ISSUE TITLE
Should peek editor close on ESC before suggest?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109727] opened 2020-10-30 10:27 UTC
Steps:
* bring up a peek references view for example (or call hierarchy)
* bring up intellisense suggest widget
* hit `ESC`

=> the peek editor closes

Shouldn't suggest close first?

Looks like this could be related to command weights, where the one for closing peek is > suggest. The suggest one is declared here:

https://github.com/microsoft/vscode/blob/6b7eabb7f2e31e3ee1d02bdc3ebaffccd3d19402/src/vs/editor/contrib/suggest/suggestController.ts#L623-L623

//cc @alexdima

**Comment by jrieken** [comment] 2020-11-03 08:39
This doesn't reproduce for me. @bpasero any special keybinding on your side?

![Nov-03-2020 09-39-06](https://user-images.githubusercontent.com/1794099/97964094-7e97d600-1db8-11eb-8b86-0d4ad31462c2.gif)

**Comment by bpasero** [comment] 2020-11-03 08:56
@jrieken yeah, suggest opened outside of peek, not inside.

**Comment by jrieken** [comment] 2020-11-03 09:01
Looks like we have this https://github.com/microsoft/vscode/blob/f3a23697a90f49276cdb4f5531e931f9d6134086/src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts#L361-L374

Depending on being inside or outside of peek we have different weights associated... No memories of why that is...

**Comment by bpasero** [comment] 2020-11-03 09:11
I had a similar issue where the `ESC` for notification toast was coming first (before workbench weight is higher than editor weight). Fixed it via https://github.com/microsoft/vscode/commit/2d7aacfa927dde260b6602f5fd45ff14d99c76d6 by explicitly having a reduced weight unless focus is inside the notification.

**Comment by jrieken** [comment] 2020-11-03 09:26
I finally saw what's the problem: some command here use the 'WorkbenchContrib' base weight while other use the one 'EditorContrib' base. The former wins boosts by 100 points and therefore things are off. Using only the editor base weight fixes this

**Comment by jrieken** [comment] 2020-11-10 07:57
Re-opening because this is causing trouble. With using only the editor base weight peek often looses against others, like search results etc

**Comment by bpasero** [comment] 2020-11-10 08:10
Yeah I also have seen weirdness, maybe I have built sufficient muscle memory around this that the current behaviour is actually better...

**Comment by jrieken** [comment] 2020-11-10 10:24
Yeah, closing as won't fix

**Closed by jrieken** 2020-11-10 10:25 UTC
Labels: bug, polish, suggest, ux, wont-fix
