### ISSUE TITLE
VS Code stops responding after opening extensionHostProces.js

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#42117] opened 2018-01-24 21:02 UTC
Repros on the latest VS Code Insider on Win10 (I haven't tried the non-Insider or Linux/Mac). I also have the TSLint extension, that's it.

While debugging our C++ extension, if I do step into such that it enters the extensionHostProcess.js, VS Code will stop responding. It's 100% reproducible. I tried to work around this via stepping out right after I stepped in, but it doesn't work.

![image](https://user-images.githubusercontent.com/19859882/35356212-9e0ae32a-0104-11e8-81e7-e440ba9ee712.png)

If you guys need complete repro details, you can clone our cpptools repository (https://github.com/Microsoft/vscode-cpptools/ ), launch extension, open a folder, create a .cpp file, do a Format Document, put a breakpoint on line 17 of `\Extension\src\LanguageServer\protocolFilter.ts` (the `let invoke3`) and then do step into 10 or so times until it the extensionHostProcess.js gets opened.

**Comment by isidorn** [comment] 2018-01-25 16:24
@sean-mcmanus I can not reproduce this. Can you please let me know what you are doing differently than me?
Please note that I tried both OS X and win and could not repro. 
![crash](https://user-images.githubusercontent.com/1926584/35398977-824d74fa-01f3-11e8-83b5-e12a06681615.gif)

**Comment by sean-mcmanus** [comment] 2018-01-25 19:12
Oh, sorry, it looks like you need to have some text in your .cpp file in order for the format breakpoint to be hit -- the breakpoint on the invoke3 line needs to be hit -- that's when you do the stepping into (I counted 9 times). But be sure not to set the breakpoint until the initial loading is finished -- the breakpoint should be hit as a result of the format document.

**Comment by isidorn** [comment] 2018-01-26 10:38
Now I did it with .cpp content and everything is fine. After 9 steps I end up in `extHostDocumentData.ts` and I can nicely continue stepping.

Let me know if there is something different I can do in order to reproduce this. You can also attach the cpp file on which you try.
Since i can not repro do you see this on all machines? Here's are more steps which can help us trace down this crash:

* F1 > Toggle Developer Tools > Select *Profile* tab
* Select *Record JavaScript CPU Profile*, select *Start*
* Now do your steps to make it not responding
* Stop recording, *Save* the profile, and attach it here. 

Also make sure to disable all other extension.
F1 > show running extensions view doing the cpu profile might also help to track down the problem

![crash](https://user-images.githubusercontent.com/1926584/35435962-e180e300-028c-11e8-926e-3dc26c5ec53c.gif)

**Comment by sean-mcmanus** [comment] 2018-01-26 21:17
Ah, it looks like this bug only repros on Win10+Insiders (not Linux+Insiders or Win10+Non-Insiders). It reproed when it breaks into extensionHostProces.js -- your screenshot shows it breaking into extHostDocumentData.ts. I don't know what causes the different file to be opened. Do you have enough info? It repros with all extensions disabled. It looks like this message in the Output window is related: `SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/89264676133f25c4990706c889a48eab277544f7/extensions\merge-conflict\out/codelensProvider.js.map` . I can't collect the JavaScript CPU Profile because it just gets stuck and never stop recording.
`
![image](https://user-images.githubusercontent.com/19859882/35461037-f17a7dee-029a-11e8-9c71-7c2e2cb2a676.png)

**Comment by sean-mcmanus** [comment] 2018-01-26 21:34
I uninstalled VS Code Insiders and reinstalled it and it stopped reproing for a few tries, but then it started to repro again all the time (I don't know of anything that changed).

**Comment by sean-mcmanus** [comment] 2018-01-26 21:43
Also, you have to wait when the extensionHostProcess.js open (stop doing Step Into, I think that's why it didn't repro for me earlier). One Code - Insiders.exe process ends up using 100% CPU on one core and memory usage keeps increasing unbounded. I could send you a dmp. I can't get the onig_scanner.node symbols to see the call stack.

**Comment by sean-mcmanus** [comment] 2018-01-26 21:46
Oh, the freeze repros simply when the extensionHostProcess.js is opened. The freeze repro in non-Insiders too. `"C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js"`

**Comment by sean-mcmanus** [comment] 2018-01-26 21:52
The freeze occurs while colorization is being done and the colorization isn't complete, so maybe that is the cause. It repros without the minimap.
![image](https://user-images.githubusercontent.com/19859882/35462284-262b1c92-02a0-11e8-8865-21ac168445aa.png)

**Comment by sean-mcmanus** [comment] 2018-01-26 22:22
Issue https://github.com/Microsoft/vscode/issues/40279 might have the same root cause, but it repros with PHP.

**Comment by isidorn** [comment] 2018-01-29 09:41
Yeah, it is due to coloring and textmate, assigning to @aeschli 
He can decide if to close as duplicate

**Comment by aeschli** [comment] 2018-01-29 11:09
Looks like the JS grammar goes into a endless loop with
```javascript
function t(){
return e.call(this,[t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),"-",t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),"-","4",t._randomHex(),t._randomHex(),t._randomHex(),"-",t._oneOf(t._timeHighBits),t._randomHex(),t._randomHex(),t._randomHex(),"-",t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex()].join(""))||this}
```

**Comment by aeschli** [comment] 2018-01-29 11:29
I created https://github.com/Microsoft/TypeScript-TmLanguage/issues/567

**Closed by aeschli** 2018-01-29 11:29 UTC
Labels: needs more info
