### ISSUE TITLE
Msys2 bash shell's file path problem

### ISSUE THREAD

**Issue by 1-riverfish** [microsoft/vscode#76393] opened 2019-07-01 07:44 UTC
About:

Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. install msys2 and gcc(use command pacman -S gcc in msys2)
2. configure vscode default shell to msys2's bash
3. write the default tasks.json file and use gcc in msys2 to compile the source file.
4. the file path is ${file} and the bash shell reports error "file path not valid". I supposed the problem is that bash shell only accepts unix style file path, however ${file} variable returns windows style file path, for example e:\CppPro\leetcode\longestPalindrome.cpp.

Does this issue occur when all extensions are disabled?: Yes/No
I not try because i need to use c++ extensions.

**Comment by alexr00** [comment] 2019-07-03 15:32
Sounds like a duplicate of https://github.com/microsoft/vscode/issues/38381, which is about supporting paths that don't match the path conventions of the system you're running on.

**Closed** 2019-07-03 15:32 UTC
Labels: *duplicate
