### ISSUE TITLE
Title of VS Code does not get updated once you select new project

### ISSUE THREAD

**Issue by ShettyAshwin** [Microsoft/vscode#9325] opened 2016-07-15 09:49 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Lets say we have two project, one root folder name is A and other  is B
2. Open the project A and go to file menu and click on open folder and Select folder B

You will see that title of the project remains A

**Comment by weinand** [comment] 2016-07-15 10:06
@ShettyAshwin I cannot reproduce this.
This issue might be caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: code --disable-extensions and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by kieferrm** [comment] 2016-07-21 14:39
Closing due to missing response.

**Closed by kieferrm** 2016-07-21 14:39 UTC
Labels: needs more info, not-reproducible
