### ISSUE TITLE
Extension uninstallation prompt should list dependencies when asking whether to uninstall them

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#48768] opened 2018-04-26 16:29 UTC
Currently it [says](https://github.com/Microsoft/vscode/blob/a9e16bab72ad8dda0fffb9bdcb44eac96679005b/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L559):
> Would you like to uninstall '{0}' only or its dependencies also?

And you can select "Extension Only", "Uninstall All", "Cancel".

At this point I'm unsure which extensions will get uninstalled if I click "Uninstall All". It should list the dependencies in the same prompt.

**Comment by sandy081** [comment] 2018-04-27 06:53
Duplicate of #14544

**Closed** 2018-04-27 06:53 UTC
Labels: *duplicate, extensions
