### ISSUE TITLE
ALT doesn't select the top menu in marketplace tabs

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#118489] opened 2021-03-08 23:54 UTC
Issue Type: <b>Bug</b>

whilst reading "Release Notes: 1.54.1" I attempted to try pressing ALT to highlight the top menu. It doesn't work. Switching to a tab that is for an open file - then ALT works. Switching back to the relase notes - ALT doesn't work.

There should be consistency. ALT should highlight the top menu.

Unfortuntately, it seems the marketplace is given special treatment: ALT doesn't work; pages don't cache and instead refresh every time you switch tabs; etc etc.

Claiming that vscode is just an editor is farcical. This isn't notepad or gedit. It has a whole marketplace, it runs plugins and supports automation. It already implements chromium... why can't you simply cache a marketplace page? I can open multiple files of several thousand lines simultaneously, yet it refuses to cache a simple plugin description page? Why? Scared that it will have to use some precious RAM?

It ruins the user experience.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.09GB (5.76GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id eb1c688b-c4e3-4232-85a1-c01025d91995|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.18.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.3.0
prettier-vscode|esb|5.9.2
restore-terminals|Eth|1.0.6
vscode-firefox-debug|fir|2.9.2
gauge|get|0.0.19
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.163.1
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.33.1
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by mjbvz** [comment] 2021-04-27 02:24
Duplicate of #121379

**Closed by mjbvz** 2021-04-27 02:24 UTC
Labels: webview
