### ISSUE TITLE
Launch menu should match in english also. Or how to disable i18n?

### ISSUE THREAD

**Issue by mattn** [Microsoft/vscode#5289] opened 2016-04-15 01:06 UTC
- VSCode Version: 1.0.0
- OS Version: Windows7 64bit

Steps to Reproduce:

1. type `CTRL-SHIFT-P`
2. type `install ext`

Before 1.0.0, we can get installation of extensions with typing `install ext`, but latest are not because `install extension` is translated to `拡張機能` in japanese.

![efa2b5478a55e89c](https://cloud.githubusercontent.com/assets/10111/14548428/bae3df3c-02f1-11e6-8cea-e68bd4c0385e.png)

![dbbf89b814f02335](https://cloud.githubusercontent.com/assets/10111/14548482/1bb6cd6a-02f2-11e6-956c-361e6fcc51a5.png)

:(

I'm happy if the launch menu have match with `install ext` also.

**Comment by vvakame** [comment] 2016-04-15 01:22
@mattn 
1. type `CTRL-SHIFT-P` 
2. choose `言語を構成する`
3. apply below settings

```
{
	// Defines VSCode's display language.
	// See http://go.microsoft.com/fwlink/?LinkId=761051 for a list of supported languages.
	// Changing the value requires to restart VSCode.
	"locale":"en-US"
}
```

**Comment by Treri** [comment] 2016-04-15 01:32
All commands should not be translated to locale specific commands.

## And they should only be **English**

same #5290

**Comment by mysticatea** [comment] 2016-04-15 01:52
FYI: duplicate of #4679, #4691, and #4696

**Comment by mattn** [comment] 2016-04-15 02:26
> All commands should not be translated to locale specific commands.

I don't mind that is translated in japanese but have trouble with matching with english. I don't have strong optinion.

**Closed** 2016-04-15 03:06 UTC
