### ISSUE TITLE
Touch Screen Support

### ISSUE THREAD

**Issue by Tukizz** [microsoft/vscode#111294] opened 2020-11-25 11:28 UTC
It will be awesome if Visual Studio Code can support touch screen monitor, cause it will be faster access from file to file and code to code without using trackpad or mouse if your laptop or screen support touch screen

I Using Chrome OS with Debian Linux integrated, and i install it via .deb package

**Comment by Tukizz** [comment] 2020-11-25 11:29
I Using Chrome OS with Debian Linux integrated, and i install it via .deb package

**Comment by egamma** [comment] 2020-11-25 18:30
Duplicate of #98218

**Closed by egamma** 2020-11-25 18:30 UTC
