### ISSUE TITLE
Cannot read property 'panel' of undefined

### ISSUE THREAD

**Issue by shimielder** [Microsoft/vscode#37039] opened 2017-10-27 12:28 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T04:19:22.491Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.2.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
vsc-material-theme|Equ|1.0.5
code-runner|for|0.8.2
extension-leaderboard|for|0.0.2
beautify|Hoo|1.1.1
intellij-idea-keybindings|k--|0.2.15
MagicPython|mag|1.0.12
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.4.0
material-icon-theme|PKi|2.2.4
python|tht|0.2.3
local-history|xyz|1.6.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Go to Extensions
2. Type anything on search form

Reproduces without extensions: Yes/No
No

**Comment by maxibanki** [comment] 2017-10-27 12:30
Duplicate of #37026

**Comment by dbaeumer** [comment] 2017-10-27 13:49
Closing as dup of #37026

**Closed by dbaeumer** 2017-10-27 13:49 UTC
Labels: extensions
