### ISSUE TITLE
Triggering workbench.action.terminal.toggleTerminal through shortcut does not focus on the terminal

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#43577] opened 2018-02-13 11:11 UTC
### Issue Type
Bug

### Description

Just press the keyboard shortcut you have assigned to the `workbench.action.terminal.toggleTerminal` action.

You will see that the terminal is not focused; focus still remains in the text editor.

This just started happening after the last update. Before, when toggling the terminal, it focused by default.

Workaround: press that same shortcut twice more. Now it pops up focused.

Just in case it matters: my default shell is Fish.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.14.16-300.fc27.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G (4 x 2095)|
|Load (avg)|2, 1, 1|
|Memory (System)|6.75GB (0.38GB free)|
|Process Argv|/usr/share/code/code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
Reproduces without extensions

**Comment by usernamehw** [comment] 2018-02-13 11:54
Duplicate of #40416 ?

**Closed** 2018-02-13 14:31 UTC
Labels: integrated-terminal
