### ISSUE TITLE
JavaScript auto completion can be triggered in unwanted places, which could sometimes be annoying.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#130659] opened 2021-08-12 08:10 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 7

Steps to Reproduce:

1. Type in certain JavaScript files.
2. Characters like `.` and `(` could trigger unwanted auto completion.

https://user-images.githubusercontent.com/8168391/129162202-0665a7ea-979f-4dcb-b79a-9605517852df.mp4

**Comment by IllusionMH** [comment] 2021-08-12 09:45
What do you see in this case (when you have this template suggested) if you press <kbd>Ctrl</kbd>+<kbd>.</kbd>? (use shortcut again to toggle suggestions details back to normal view later)

I would expect `.,;` in commit characters, but not `(`.
See https://github.com/microsoft/vscode/issues/130096#issuecomment-897489821

**Comment by IllusionMH** [comment] 2021-08-12 10:33
Yes, however I would expect word based suggestions (based on abc icon for `template`) this this won't be added to list.
For somehow similar code it doesn't have `(` in list.
![image](https://user-images.githubusercontent.com/1312662/129182210-df46295b-f404-43f3-85f3-c0d958697eda.png)

Otherwise it's duplicate of #130096

UPS. Strange. Even `map` on array doesn't have `(` in list 0_o
![image](https://user-images.githubusercontent.com/1312662/129182578-6adefa72-dca1-4e6c-bc86-9a3d345ab7b4.png)

**Comment by moloko** [comment] 2021-08-12 10:55
I'm getting something very similar to this too whenever attempting to type the spread operator inside an object/array...

https://user-images.githubusercontent.com/1249597/129185230-a2190f0d-a7a8-43c5-b734-9be94689e84d.mp4

I'm using:
> Version: 1.59.0
> Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
> Date: 2021-08-04T23:11:51.081Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Darwin arm64 20.6.0

And have disabled all extensions just to be sure it's not one of them causing this. I'm pretty certain this is a recent thing i.e. didn't happen in previous release of VSC.

**Comment by IllusionMH** [comment] 2021-08-12 11:05
@moloko you are showing exactly #130096

**Comment by masontien** [comment] 2021-08-12 13:14
I want Destructuring assignment ...  but😰
![Aug-12-2021 19-54-42](https://user-images.githubusercontent.com/85332201/129202864-a536d182-7e29-4043-b69c-02706384d1fd.gif)

**Comment by IllusionMH** [comment] 2021-08-12 13:59
Anyone who can't type their `...` should go to #130096 and upvote that issue.

This issue presents a bit different behavior for `(` not `.`. Leave it as it is now.

**Closed** 2021-08-12 22:23 UTC
Labels: *duplicate
