### ISSUE TITLE
Ctrl+c,s kills folding for according function

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#14748] opened 2016-10-31 09:41 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions: LaurentTreguier.vscode-simple-icons-0.2.0, MattiasPernhult.vscode-todo-0.8.0, PKief.material-icon-theme-1.1.3, PeterJausovec.vscode-docker-0.0.7, Zignd.html-css-class-completion-1.0.3, donjayamanne.githistory-0.1.0, emallin.phpunit-1.0.0, felixfbecker.php-intellisense-0.0.11, florianloch.text-transform-0.0.2, formulahendry.auto-close-tag-0.3.4, formulahendry.auto-rename-tag-0.0.7, linyang95.php-symbols-0.1.2, lukehoban.Go-0.6.47, ms-vscode.csharp-1.4.1, wcwhitehead.bootstrap-3-snippets-0.0.7

Just noticed this in GO by now

Steps to Reproduce:

1. open a go file and move into any function
2. select something
3. Press Ctrl and hold it
4. Press c then s, both while pressing ctrl
5. release ctrl

=> folding for any foldable code within this function is dead.

You can Ctrl+Tab twice (go to another file and come back) to get it back.

**Comment by aeschli** [comment] 2016-11-01 10:10
Sorry, can't reproduce on either Linux or Windows.
What do you mean by 'Folding is dead'? Can you attach a screenshot?
Ctrl+S is save and will trigger save participants like format on save. Are there any content changes happening?

**Comment by DasJott** [comment] 2016-11-01 10:36
It is perfectly reproducable here on Ubuntu 16.04.

I mean, that nothing - neither the function nor anything inside - is foldable anymore.

I know that ctrl+s is save. It's  reflex I do - even after just copying something. So wothout thinking I press ctrl+c,s and folding disappears from the method/function.

No content changes happening.

I made a Video. between selecting and moving the mouse again, I just pressed ctrl+c,s. You see, the folding dissappeared.
[FoldingError.mp4.zip](https://github.com/Microsoft/vscode/files/563801/FoldingError.mp4.zip)

**Comment by aeschli** [comment] 2016-11-03 15:56
Thanks for the video. Had some troubles opening it first, but VLC was able to play it.
@DasJott What happens if you invoke Fold all (Ctrl+K Ctrl+0) after the save? 

@bpasero Any idea? Any known issues where the focus is taken away on save?

**Comment by bpasero** [comment] 2016-11-03 16:33
@DasJott 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by DasJott** [comment] 2016-11-04 07:47
This morning I updated to 1.7.1 and I can not reproduce the issue anymore.
So it is at least a "not always".

I will watch this and see, whether it appears again and try to figure out, when.

If it keeps being solved, I will close this.

**Comment by aeschli** [comment] 2016-11-24 09:44
Closing for now. Please reopen when you see it again.

**Closed by aeschli** 2016-11-24 09:44 UTC

**Comment by DasJott** [comment] 2016-12-02 10:43
Seems to be fixed indeed.
