### ISSUE TITLE
Adding lines after a line with breakpoint set adds more breakpoints on each following line

### ISSUE THREAD

**Issue by dhmspector** [Microsoft/vscode#38553] opened 2017-11-16 20:49 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.14.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jupyter|don|1.1.4
tslint|eg2|1.0.22
vscode-npm-script|eg2|0.3.3
code-runner|for|0.8.3
live-code-runner|lab|2.0.0
node-module-intellisense|lei|1.4.0
MagicPython|mag|1.0.12
markdown-shortcuts|mdi|0.8.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
wordcount|ms-|0.1.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
markdown-preview-enhanced|shd|0.3.0
code-spell-checker|str|1.4.12
python|tht|0.2.3
tensorflow-snippets|vah|0.3.3

---

Steps to Reproduce:

1. Open a Javascript file
2. Set a breakpoint on a line
3. Go to the ned of the line with the newly set breakpoint and press enter to start a new line
4. Start typing on the new line

A new breakpoint will be created and will keep being created as you add more (non-empty) lines to the file .

Reproduces without extensions: Yes

**Comment by dhmspector** [comment] 2017-11-16 20:51
Update:  It actually looks like the original line where the break point is set is the actual breakpoint; the succeeding lines show a breakpoint enabled indicator, but where you click on them to remove them they stay in place and cannot be removed -- this looks to be more of a display update glitch.

**Comment by FancyBanana** [comment] 2017-11-16 21:00
I have similar problem. When file is modified more "ghost" breakpoints are added. The only way to get rid of them is to close and reopen the tab. Occurs after compiling typescript.

**Comment by dhmspector** [comment] 2017-11-16 21:07
YA Update: the "remove all breakpoints" command fails in this state... all the existing and phantom breakpoints are still in place.

**Comment by dhmspector** [comment] 2017-11-16 21:09
@FancyBanana - thanks for pointing out the open/close tab solution - solves the immediate "being able to debug" problem.

**Comment by weinand** [comment] 2017-11-16 23:07
Duplicate of #37880. Please try Insiders where the problem is fixed. Expect fix for Stable soon.

**Closed by weinand** 2017-11-16 23:07 UTC
Labels: debug, new release
