### ISSUE TITLE
macOS: Menu is not functional when window is minimized

### ISSUE THREAD

**Issue by zittix** [Microsoft/vscode#63000] opened 2018-11-13 08:23 UTC
- VSCode Version: 1.29.0
- OS Version: OS X Mojave 10.14.1

Steps to Reproduce:

1. Open a VSCode window
2. Minimize it by clicking the yellow (-) on the top left corner of the window
3. Either with the CMD-Shift-N or with the File->New Window menu, try to open a new window. Nothing appears

Does this issue occur when all extensions are disabled?: Yes

Screencast:
![screen recording 2018-11-13 at 09 19 31](https://user-images.githubusercontent.com/818748/48400108-bcac1300-e725-11e8-81f8-17e5bf2560ea.gif)

**Comment by bpasero** [comment] 2018-11-18 17:12
@sbatten I can reproduce, could this be menu related?

**Comment by zittix** [comment] 2018-11-19 08:01
FYI, I retested on latest 1.29.1, the issue is still there.

**Comment by bpasero** [comment] 2018-11-19 16:22
This seems to be a regression, I can see how the call ends up [here](https://github.com/Microsoft/vscode/blob/5e47cfc7c855d11fc6414b6c1f03f1ae5814e15e/src/vs/platform/menubar/electron-main/menubar.ts#L706) but then since no window is focused, nothing happens. 

We should fix this for November.

**Comment by sbatten** [comment] 2018-11-19 22:02
@bpasero I can reproduce this in much older versions of VS Code. I don't believe this is a regression. The same block existed in the old menu bar implementation. I explored ways of fixing this.

1) Listening to blur and focus events on the windows service and then querying the focused menu. I felt limited by the windows and windowsMain services as the lastActiveWindow event doesn't fire when a window is minimized. Semantically that seems incorrect. This solution would have the menu function as if there were no open windows. 

2) Keep the menubar fully enabled in this scenario but have a check to forward the fallback items through to the last focused / current active window.

**Comment by bpasero** [comment] 2018-11-20 05:50
@sbatten can we not just use the last active window in case the focused window returns null? After all we just need one window to operate the command right?

If this is not a regression, it is also not important.

**Comment by sbatten** [comment] 2018-11-20 18:13
@bpasero I don't fully understand the root cause of the issues that led to this check. You are assigned to those so I will leave that judgment to you. It seems to me like we would break the first case however.

**Comment by bpasero** [comment] 2018-11-22 14:58
Yeah, this is ugly because Electron does not give me any API to find out if a modal dialog is open or not. As such we have those ugly checks in place to check for the window being focused or not.

I pushed another check if the last active window is minimized to handle this case, but overall its still not a very nice solution.

**Closed by bpasero** 2018-11-22 14:58 UTC
Labels: bug
