### ISSUE TITLE
detect mode id based on content

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/vscode#73792] opened 2019-05-15 20:57 UTC
Issue Type: <b>Bug</b>

Given a document is opened of any extension type, if the content is json, it should detect json so it can be cloured, formatted and layed out

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (17.97GB free)|
|Process Argv|C:\temp\afile.anyExt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
pig|Gan|2.2.0
beautify|Hoo|1.5.0
rainbow-csv|mec|1.0.0
powershell|ms-|1.12.1
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2

</details>

**Comment by jrieken** [comment] 2019-10-08 14:09
/duplicate of https://github.com/microsoft/vscode/issues/80303

**Closed** 2019-10-08 14:10 UTC
Labels: *duplicate, feature-request, languages-basic
