### ISSUE TITLE
Provide extensions a way to localize their messages

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#21458] opened 2017-02-26 23:03 UTC
Hi there,

after publishing a well-known extension, we want to reach even more people, even them, who don't know English that well(like me). So, after all, we want that everybody understands how they can make there dreams come true with icons they like and how they contribute with there own icon-mapping. And the way, obviously, is: Having any message in there first language, but we need the help of you.

In fact, we are in need of the language settings. Could you provide us any way how we can determine which language the UI is?(in the best way via package.json, because the commands are just supporting one language) 

Thanks

**Comment by JimiC** [comment] 2017-02-26 23:13
Actually what @jens1o want to say is that we request that the command titles in the `package.json` of an extension can support i18n.

**Comment by dbaeumer** [comment] 2017-02-28 09:02
This is all supported :-) but not well documented. Best you take a look at one of our extensions to see how this is done. A good example can be found here: https://github.com/Microsoft/vscode/tree/master/extensions/php

The trick in the package.json is to use a %key% instead of a string and to provide package.nls.*.json files with the translations.

I will close the issue since the support is there. If you have further questions please ping me in this issue and I am glad to help.

**Closed by dbaeumer** 2017-02-28 09:02 UTC

**Comment by JimiC** [comment] 2017-02-28 09:15
@dbaeumer The lack of documentation surely is to blame cause I've looked into it and couldn't find a solution. Thanks for the info.

**Comment by JimiC** [comment] 2017-03-01 10:18
@dbaeumer Do the `package.nls.*.json` files need to be in the root folder?

**Comment by dbaeumer** [comment] 2017-03-01 11:58
Yes, they must be siblings to the package.json file right now.

**Comment by robertohuertasm** [comment] 2017-03-18 16:07
@dbaeumer we're trying to deploy the extension via `vsce publish` but we've found that `package.json` file gets modified and the placeholders get replaced by the English translations (my system is in English).

How we should proceed here? Is this supposed to be the expected behavior? Because this is not what we expected and it breaks our tests just before deploying as we check the integrity of the `package.json` file before the publication process.

**Comment by JimiC** [comment] 2017-03-18 16:10
Note here that `vsce package` works as expected.

**Comment by JimiC** [comment] 2017-03-18 17:12
Looks like @robertohuertasm has identified a bug in `vsce`.

**Comment by robertohuertasm** [comment] 2017-03-18 17:25
Yes, I think I did. You can take a look at the details:

- issue: [vscode-vsce#158](https://github.com/Microsoft/vscode-vsce/issues/158).
- PR: [vscode-vsce#159](https://github.com/Microsoft/vscode-vsce/pull/159)

**Comment by dbaeumer** [comment] 2017-03-20 10:07
@joaomoreno can you comment on vscode-vsce#158
