### ISSUE TITLE
Delete lines before the link causing weird blinking horizontal line

### ISSUE THREAD

**Issue by fuermosi777** [microsoft/vscode#77585] opened 2019-07-18 16:35 UTC
Issue Type: <b>Bug</b>

1. Open a new doc (Plain Text is fine).
2. Type "http://test.com"
3. Move cursor to the begining of the doc and press "Enter" for serveral times to create some empty lines.
4. Move cursor back to the begining of the doc
5. Press "Del" to remove those empty lines until only one line left (the line with text of the link)

Observed some horizontal lines in the bottom of the link and they are blinking the same as the cursor.

<img width="199" alt="Screen Shot 2019-07-18 at 9 32 58 AM" src="https://user-images.githubusercontent.com/7303373/61475247-3d6b8080-a93f-11e9-8af2-78bae58f232d.png">

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 6|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by usernamehw** [comment] 2019-07-18 20:36
Possible duplicate of #48321

**Closed** 2019-08-02 19:23 UTC
Labels: *duplicate, editor-contrib
