### ISSUE TITLE
Provide auto-updates for linux

### ISSUE THREAD

**Issue by kirtangajjar** [Microsoft/vscode#16054] opened 2016-11-25 09:56 UTC
Users on linux still have to go to website to download updates. 

This sucks :( Would be better if we could get auto-updates like windows and mac users.

**Comment by Tyriar** [comment] 2016-11-26 16:01
I agree :smiley: duplicate of https://github.com/Microsoft/vscode/issues/2973 and https://github.com/Microsoft/vscode/issues/229 (coming soon)

**Closed by Tyriar** 2016-11-26 16:01 UTC
