### ISSUE TITLE
Debugger shows wrong this context in fat arrow function. _this2 seems to be the correct one

### ISSUE THREAD

**Issue by mlostek** [Microsoft/vscode#57959] opened 2018-09-05 13:50 UTC
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: MacOS High Sierra 10.13.6 (17G65)

Steps to Reproduce:

Check this code below

```
class TrainerVideoContainer extends React.Component {

  ...
  shouldComponentUpdate(nextProps: Props) {
    const hasUpdated = (prop) => {
      return nextProps[prop] !== this.props[prop];
    }
    const shouldUpdate = ['A', 'B', 'C'].some(hasUpdated)
    return shouldUpdate;
  }

}
```

When setting a breakpoint inside `hasUpdated` the local this variable is showing wrong information. Also a watch is showing wrong information. The code itself runs fine, but the debugger assumes that `_this2` is the current used `this`. 

![bildschirmfoto 2018-09-05 um 15 48 08](https://user-images.githubusercontent.com/39261122/45097407-1d661080-b123-11e8-8ea6-e0ec7f86836c.JPG)

I guess this has to do with some babel transformations that are done but not reflected in the debugger. 

Is there some workaround for `this`?

**Comment by weinand** [comment] 2018-09-07 10:20
duplicate of #23143

**Closed by weinand** 2018-09-07 10:20 UTC
