### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by HunSeong77** [microsoft/vscode#149359] opened 2022-05-12 14:05 UTC
Issue Type: <b>Bug</b>

When I exit VS code, an error message is popped up.(update fail)
log file says it cannot find path C:\Users ... Microsoft VS Code\Code.exe
However I installed VScode in D:\Microsoft VS Code
I think there is some problem to find the path where it is installed.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.75GB free)|
|Process Argv|--crash-reporter-id 9c2b0520-6781-498d-a01a-ebbe72c91c5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.13
python|ms-|2022.4.1
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.2.0
veriloghdl|msh|1.5.3
indent-rainbow|ode|8.3.1
pdf|tom|1.2.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by joaomoreno** [comment] 2022-05-20 13:26
Duplicate of https://github.com/microsoft/vscode/issues/147408

**Closed by joaomoreno** 2022-05-20 13:26 UTC
