### ISSUE TITLE
Consolidate rendering updates on executing a cell

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#130655] opened 2021-08-12 07:39 UTC
Here are two animated gifs. One from Jupyter Lab, the other from VS Code. Both represent a slow-motion cell execution via Shift+Enter. Note that for VS Code, there are 4 renderings that are being done to resolve the cell run.In Jupyter Lab there are 2. 

There should only be 2. One to clear the output for the cell being run while it runs. This has the side effect of shifting all subsequent cells up temporarily. Then when the cell completes, a second update occurs that shows the output, which shifts all subsequent cells and output back down in one shot. 

In VS Code there are separate shifts of cells and markdown. This manifests itself as lots of jitter when executing cells in VS Code in quick succession. Jupyter Lab feels much less "nervous" and offers a better sense of stability.

![JupyterShiftEnterRendering](https://user-images.githubusercontent.com/11685408/129156199-10f5fd29-fa28-4e07-b9d6-989b812c9c38.gif)
![VSCodeShiftEnterRender](https://user-images.githubusercontent.com/11685408/129156195-68cf7391-6501-4bed-9485-e8e8dbc31312.gif)

**Comment by roblourens** [comment] 2021-08-12 14:54
The difference is that our markdown is in the webview, and this issue is really the core of https://github.com/microsoft/vscode/issues/126432. I haven't been optimistic about finding any way to improve it

**Comment by roblourens** [comment] 2021-08-20 00:13
Closing as dupe of the above

**Closed by roblourens** 2021-08-20 00:13 UTC
Labels: notebook, notebook-layout
