### ISSUE TITLE
Debug Repl: output of same value no longer aggregated

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27856] opened 2017-06-01 15:18 UTC
I am not sure when we lost support for this but we used to show a little number next to the output if the output was identical to the previous output, much like Chrome console works:

![image](https://cloud.githubusercontent.com/assets/900690/26686760/3efb5390-46ee-11e7-8b68-1ec8a38e84cd.png)

I am no longer seeing this in the repl:

![image](https://cloud.githubusercontent.com/assets/900690/26686777/4c318124-46ee-11e7-847e-cd3150f06961.png)

**Comment by isidorn** [comment] 2017-06-06 12:56
Please note that in your picture you are outputing an object which we never supported. Though what you are doing in chrome picture should work
```
for (var i = 0; i < 20; i++) {
    console.log("Hello world");
}
```

**Comment by weinand** [comment] 2017-06-28 14:19
running the for loop from above with the "legacy" protocol results in this:
![2017-06-28_16-17-44](https://user-images.githubusercontent.com/1898161/27641861-67d88fbe-5c1d-11e7-86c3-7b1b7fcdd727.png)

running it with "inspector" protocol in this:
![2017-06-28_16-19-01](https://user-images.githubusercontent.com/1898161/27641899-83f6997a-5c1d-11e7-8afa-bd8ef29cb766.png)

reopening.

**Comment by isidorn** [comment] 2017-06-28 14:53
The issue is how the events are coming from the node extensions, the following sample shows that everything is fine on the vsocde side
```
setInterval(() => {
    console.log("Hello world");

}, 50)
```

However the legacy adapter seems to append different pieces together when they are happening shortly afterwards.
I do not plan to fix this on the vscode side as I would have to split the output which is coming together by newlines which would bring me some other pain.
@weinand if you want you can tackle it on the adapter side, closing this as I plan to take no action

**Comment by weinand** [comment] 2017-06-28 15:18
I see.
Could you please explain what the blue number means for en end user?

**Comment by weinand** [comment] 2017-06-28 22:54
I'm in favour of disabling this feature for now because it does not provide a user experience that is understandable. Compare the console in Chrome Dev Tools with both VS Code protocols to understand what I mean.

E.g. compare the output of this snippet in the "inspector" protocol and Chrome Dev Tools:
```js
for (var i = 0; i < 20; i++) {
    console.log("Hello\nWorld");
}
```

**Comment by isidorn** [comment] 2017-06-29 07:24
I am fine disabling it. @bpasero objections?

**Comment by bpasero** [comment] 2017-06-29 07:46
No objections as I am not using this feature. Btw I verified this using extension debugging where it seems to work fine.

**Closed** 2017-06-29 08:00 UTC
Labels: bug, debug, debug-console, verification-found, verified

**Comment by isidorn** [comment] 2017-06-29 08:54
To verify: quickly try out if the repl properly shows strings sent from the adapter. And verify it does not concatanate them

**Comment by bpasero** [comment] 2017-06-30 07:52
Verified for EH debugging.
