### ISSUE TITLE
Does not reproduce videos

### ISSUE THREAD

**Issue by vincenzoml** [microsoft/vscode#179799] opened 2023-04-12 17:02 UTC
Type: <b>Bug</b>

I open a video from the side panel (file manager) and it just won't open it saying there was an error and asking if I want to open it using the standard text/binary editor.

VS Code version: Code - Insiders 1.78.0-insider (ea0e3e0d1fabf0622fbcacdc4fe1c7b73b34dc0b, 2023-04-07T05:20:50.322Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-60-generic
Remote OS version: Linux x64 5.15.0-60-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.31GB free)|
|Process Argv|--crash-reporter-id f5ad87d4-f668-42fd-9a6b-7f8f71c92641|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: ui4voxlogica @ ssh://pc-ciancia.isti.cnr.it|
|OS|Linux x64 5.15.0-60-generic|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|31.19GB (22.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container @ ssh://pc-ciancia.isti.cnr.it|
|OS|Linux x64 5.15.0-60-generic|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|31.19GB (22.02GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-styled-jsx|bla|2.1.1
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.289.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.0
remote-explorer|ms-|0.4.0
js-jsx-snippets|sky|11.0.1
githistory|don|0.6.20
gitlens|eam|13.5.0
git-graph|mhu|1.30.0
vscode-language-pack-it|MS-|1.77.2023041209
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
gitblame|wad|10.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
functionswalk:30687959
pythonms35:30671666
pythonfmttextcf:30710680
pythonclientmv:30700173
9b8hh234:30694863

```

</details>

**Comment by mjbvz** [comment] 2023-04-12 17:36
What type of video?

**Comment by vincenzoml** [comment] 2023-04-12 18:04
mp4, generated using ffmpeg, which used to work until say, one month ago.

**Comment by mjbvz** [comment] 2023-04-12 18:32
Can you please share a file which causes the issue?

**Comment by vincenzoml** [comment] 2023-04-12 18:49
Sure! 
https://user-images.githubusercontent.com/2283125/231555967-2caf4f18-353f-4ff5-bfe8-d337d825e32a.mp4

**Comment by ppizarror** [comment] 2023-04-12 19:32
![image](https://user-images.githubusercontent.com/12925256/231564930-6c5e9de9-bae9-4ced-836a-057d4439599d.png)

I tested the video and got no problems. Are you sure uploading to GitHub does not change the MIME type?

**Comment by vincenzoml** [comment] 2023-04-13 00:27
I am on vscode insiders, 1.78 ! 

<img width="928" alt="image" src="https://user-images.githubusercontent.com/2283125/231614575-c91f1ca6-56aa-42ab-b5d9-a4a7b8a85e4f.png">

**Comment by mjbvz** [comment] 2023-04-13 18:07
Duplicate of #179826 Should be fixed in insiders shortly

**Closed by mjbvz** 2023-04-13 18:07 UTC
Labels: info-needed
