### ISSUE TITLE
Context menu for tabs should include rename option

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#25891] opened 2017-05-04 12:30 UTC
- VSCode Version: 1.11.2
- OS Version: All

When I need to rename a file I'm working on, it would be nice to be able to do so from the right-click menu on its tab. Currently you can Reveal in Sidebar and then right-click to rename, but it would be nice to have Rename and even Delete options in the tab's context menu.

**Comment by yfdyh000** [comment] 2017-05-20 23:17
Duplicate of #21919.

**Comment by bpasero** [comment] 2017-09-09 07:24
https://github.com/Microsoft/vscode/issues/21919

**Closed by bpasero** 2017-09-09 07:24 UTC
Labels: extension-candidate, feature-request, workbench, workbench-tabs
