### ISSUE TITLE
Installed extensions should be listed in `settings.json`

### ISSUE THREAD

**Issue by NotWearingPants** [Microsoft/vscode#59745] opened 2018-10-01 15:01 UTC
The list of installed extensions should be kept in the `settings.json` file, along with whether they are enabled or not.

The reasoning for this is that developers want to keep the same setup when moving to a new computer, so usually programs have their entire configuration in a few files (e.g. `.vimrc` or `.bashrc`), and then you can just copy these few files to the new computer and have everything work the same.

Developers also sometimes save these config files in a git repository to have the benefits of version control, to have them backed up, and also to share with other developers.
E.g. https://github.com/wesbos/dotfiles
As you can see, WesBos has his `settings.json` in the repo, but the extensions he uses are listed in a separate markdown file with links to the extension marketplace.

Currently the files `settings.json` and `keybindings.json` (and maybe the `snippets` folder) can be used to reproduce a VSCode setup, but without the extensions.

To solve this I suggest keeping the list of installed extensions in `settings.json`, and having VSCode install/uninstall/enable/disable extensions when this list is changed.

For example:
```json5
{
    "editor.fontSize": 14,
    "extensions.installed": {
        "eamodio.gitlens": true,
        "ms-vscode.cpptools": false, // disabled
        "ms-python.python": true
    }
}
```

In the example the purpose of the booleans isn't so clear, so it may be better to have `{ "enabled": true }`, which also has the benefit of being able to expand the options in the future.

I went with an object instead of an array to enforce not having duplicates, but this is also assuming the order doesn't matter, if it does it may be better to use an array of objects, something like `{ "id": "ms-python.python", "enabled": true }`.

**Comment by RMacfarlane** [comment] 2018-10-01 17:52
There's a similar existing feature that doesn't completely satisfy this request, but would help. You can add an `extensions.json` file under the `.vscode` folder in a repo which lists recommended extensions for the repo. Users would see a prompt to install the list if they don't already have them when opening the repo. https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

https://github.com/Microsoft/vscode/issues/15442 is a request to extend the functionality of `extensions.json` to automatically install a list of extensions. Closing this issue as a duplicate of that, please continue discussion there. Thanks!

**Closed by RMacfarlane** 2018-10-01 17:52 UTC
Labels: extensions
