### ISSUE TITLE
NPM install fails as long as VSCode is open

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#30037] opened 2017-07-03 07:51 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.15.2|
|ng-template|Angular|0.1.4|
|vscode-svgviewer|cssho|1.4.2|
|vscode-markdownlint|DavidAnson|0.9.1|
|xml|DotJoshJohnson|1.9.2|
|vscode-style-formatter|dweber019|1.0.0|
|gitlens|eamodio|4.3.0|
|tslint|eg2|0.16.0|
|vsc-material-theme|Equinusocio|1.0.0|
|vscode-guid|heaths|1.0.0|
|vscode-icon-theme|jtlowe|1.5.0|
|docomment|k--kato|0.0.17|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|3.1.6|
|view-in-browser|qinjia|0.0.5|
|sass-indented|robinbentley|1.4.1|
|yo|samverschueren|0.9.3|
|MDTools|seanmcbreen|1.0.1|
|change-case|wmaurer|1.0.0|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|;

---

Steps to Reproduce:

1. Open or create an angular2 project
2. Open integrated terminal (Powershell) 
3. run npm i

I receive an error from npm 
`EPERM: operation not permitted, rename`

This happens as long as VSCode is open. When I close it, it works. Seems that VSCode or TypeScript is blocking something. See attached npm log 

[2017-07-03T07_36_18_871Z-debug.txt](https://github.com/Microsoft/vscode/files/1118817/2017-07-03T07_36_18_871Z-debug.txt)

**Comment by DickvdBrink** [comment] 2017-07-03 07:53
Duplicate of https://github.com/Microsoft/vscode/issues/28593

**Closed** 2017-07-03 09:31 UTC
