### ISSUE TITLE
Message error when you change editor.fontWeight for a number value

### ISSUE THREAD

**Issue by severomario** [microsoft/vscode#97273] opened 2020-05-08 16:24 UTC
- VSCode Version: 1.45.0
- OS Version: Windoes 10 Pro

Steps to Reproduce:

1. File > Preferences > Settings
2. Type **font** in the search field
3. Try to update the value in **Editor: Font Weight**
4. If you try to insert a number value the software will returns the following message: ``_Setting has an invalid type, expected "string". Fix in JSON_``

![image](https://user-images.githubusercontent.com/63346789/81349330-2e082000-9096-11ea-9d72-3e7291d3aa1f.png)

**Note:** In the previous version it worked perfectly.

![image](https://user-images.githubusercontent.com/63346789/81349393-4841fe00-9096-11ea-8ef9-38a829a26ded.png)

**Comment by roblourens** [comment] 2020-05-10 01:56
/duplicate of https://github.com/microsoft/vscode/issues/97192

**Closed** 2020-05-10 01:56 UTC
Labels: *duplicate, new release
