### ISSUE TITLE
After specifying range for each vscode.CompletionItem , Inllesense suggest list does not show all items which includes token. It only list object which starts with the token. 

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#138723] opened 2021-12-09 09:29 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.51.1
- OS Version:Windows 10 pro

To support intellisense in our VSCode extension, I have implemented vscode.CompletionItemProvider interface and call to provideCompletionItems() returns the list of vscode.CompletionList.

In the suggest list, only those items which starts with token gets displayed e.g. On typing ‘e’ from vscode editor in my extension, I return vscode.CompletionList which contains two items by name ‘emp’ and ‘mpe’ but in the suggest list only ‘emp’ gets listed but I want to list ‘mpe’ also .

To each vscode.CompletionItem I set range property , which I calculated using following method

getRange(document, position) {
        let pos = position.character;
        let text = document.lineAt(position.line).text;
        while (pos > 0 && text.charAt(pos) != ' ')
            pos--;
        let firstIndex = text.charAt(pos) == ' ' ? pos + 1 : pos;
        return new vscode.Range(new vscode.Position(position.line, firstIndex), position);
    }

So in my case for each vscode.CompletionItem range would be { (0,0 ), (0,1)}  -  I have typed one character at the start of first line.
(0,0) - represents line#0 and character position - 0
(0,1) - represents line#0 and character position -1

Please let me know what I need to do so that all items which includes token gets displayed in the suggest list?
I am not sure If I am using range property correctly or I need to do something else.

Thanks & Regards,
Ajay

**Comment by jrieken** [comment] 2021-12-09 10:19
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by jrieken** [comment] 2021-12-09 10:19
Please follow the guidance above and if those don't work provide a full sample that shows your problem

**Comment by ajaygera** [comment] 2021-12-09 11:45
Please find **Javascript** code and **Typescript** code:

Following is **Javascript** code:
getRange(document, position) {
        let pos = position.character;
        let text = document.lineAt(position.line).text;
        while (pos > 0 && text.charAt(pos) != ' ')
            pos--;
        let firstIndex = text.charAt(pos) == ' ' ? pos + 1 : pos;
        return new vscode.Range(new vscode.Position(position.line, firstIndex), position);
    }
    provideCompletionItems(document, position, token, context) {
        let range = this.getRange(document, position);

        let list = new vscode.CompletionList();

        let item1 = new vscode.CompletionItem("abc");
        item1.range = range;
        let item2 = new vscode.CompletionItem("cba");
        item2.range = range;
        let item3 = new vscode.CompletionItem("cab");
        item3.range = range;

        list.items.push(item1);
        list.items.push(item2);
        list.items.push(item3);
        return list;
    }
    resolveCompletionItem(item, token) {
        return null;
    }

-----------------------------------------------------------------------------
Following is **TypeScript** code:

private getRange(document:vscode.TextDocument,position: vscode.Position):vscode.Range{
        let pos = position.character;
        let text = document.lineAt(position.line).text;
        while(pos>0&&text.charAt(pos)!=' ')
            pos--;
        let firstIndex = text.charAt(pos)==' '?pos+1:pos;
        return new vscode.Range(
            new vscode.Position(position.line,firstIndex),
            position);
    }

    provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.ProviderResult<vscode.CompletionItem[] | vscode.CompletionList> {        
        let range:vscode.Range =  this.getRange(document, position);

        let list:vscode.CompletionList = new vscode.CompletionList();

        let item1:vscode.CompletionItem = new vscode.CompletionItem("abc");
        item1.range = range;
        let item2:vscode.CompletionItem = new vscode.CompletionItem("cba");
        item2.range = range;
        let item3:vscode.CompletionItem = new vscode.CompletionItem("cab");
        item3.range = range;

        list.items.push(item1);
        list.items.push(item2);
        list.items.push(item3);

        return list;        
    }

    resolveCompletionItem?(item: vscode.CompletionItem, token: vscode.CancellationToken): vscode.ProviderResult<vscode.CompletionItem> {
        return null;
    }

**Comment by ajaygera** [comment] 2021-12-09 11:49
With above code, On typing 'a' I see only one item "abc" but I want to see all three completion items which includes 'a'  i.e. "abc" ,  "cba" and "cab"

**Comment by jrieken** [comment] 2021-12-09 11:56
>  "cba" and "cab"

Those will be filtered because the don't consider them matching strongly.

**Comment by jrieken** [comment] 2021-12-09 11:57
/duplicate of https://github.com/microsoft/vscode/issues/53715

**Closed** 2021-12-09 11:57 UTC
Labels: needs more info, *duplicate, suggest

**Comment by ajaygera** [comment] 2021-12-09 12:18
@jrieken 
#53715 is opened since 30 months..
Does that mean that no VSCode extension can show items which includes token?
If there is way to fix this or work around then please share sample code.
