### ISSUE TITLE
onDidChangeTextDocument Api timing issue

### ISSUE THREAD

**Issue by aminroosta** [Microsoft/vscode#11339] opened 2016-08-31 20:18 UTC
- VSCode Version: 1.4.0-insider
- OS Version: El Capitan

Steps to Reproduce:

1. Enter some text in an editor window

<img width="551" alt="screen shot 2016-09-01 at 12 46 01 am" src="https://cloud.githubusercontent.com/assets/2920178/18144809/c8e231ca-6fdd-11e6-90d9-af9a6274a2b5.png">

**Comment by aminroosta** [comment] 2016-08-31 20:19
Related VsCodeVim issue https://github.com/VSCodeVim/Vim/issues/680

**Comment by bpasero** [comment] 2016-09-23 14:56
@jrieken what is the 2-minute executive summary of the problem ;)?

**Comment by jrieken** [comment] 2016-09-23 15:49
@bpasero Unsure if you want to know so short before the weekend 🙉 The problem is that we have one event source for [doc](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L109)[ument](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L150) changes and another for [dirty](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L76). So, one event is from the editor world and the other from the workbench world and we don't synchronise on them - so we first tell extensions a document has changes (and at that time it's not dirty) and on next tick we tell extensions a document is dirty. I have no clue how we bring all those things together yet...

**Comment by bpasero** [comment] 2016-09-23 17:16
got it, debt for next sprint.

**Comment by jrieken** [comment] 2016-10-24 12:50
It seems this cannot be fixed with a normal `setImmediate` hack

**Comment by bpasero** [comment] 2016-10-26 14:56
Probably be solved if we figure out https://github.com/Microsoft/vscode/issues/14275

**Comment by bpasero** [comment] 2016-10-27 07:03
Does not make sense to keep 2 issues open on the same problem. Continues in #14275

**Closed by bpasero** 2016-10-27 07:03 UTC
Labels: bug
