### ISSUE TITLE
Account Login Issue

### ISSUE THREAD

**Issue by rizkyyusfian** [microsoft/vscode#234973] opened 2024-12-02 11:12 UTC
Type: <b>Bug</b>

Every time I close vs code insider and reopen it again, vs code always asks me to log in. It looks like vs code does not save my login credentials even though I already login last time.

VS Code version: Code - Insiders 1.96.0-insider (2ed1e9b48c8f55e1b92322a992c6c12b1e86e444, 2024-12-02T05:06:23.390Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Windows_NT x64 10.0.22631

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.09GB free)|
|Process Argv|--crash-reporter-id a5b2e697-b183-4710-8987-86ce4a042674|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|s2if-1|
|OS|Windows_NT x64 10.0.22631|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|Memory (System)|31.70GB (16.81GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.88.5
remote-explorer|ms-|0.5.2024111900
remote-server|ms-|1.6.2024112109
material-icon-theme|PKi|5.14.1
python-environment-manager|don|1.2.4
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
copilot|Git|1.246.1234
copilot-chat|Git|0.23.2024120201
rest-client|hum|0.25.1
debugpy|ms-|2024.13.2024112901
python|ms-|2024.21.2024112901
vscode-pylance|ms-|2024.11.102
jupyter|ms-|2024.11.2024112701
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.2024102901
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
powershell|ms-|2024.4.0
java|red|1.37.2024112308
vscode-zipexplorer|sle|0.3.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.2024111106
vscode-java-debug|vsc|0.58.2024090204
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.2024091906
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.2024072906
sysinfo-vscode|wra|2.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179977
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31183120
5b1c1929:31184661

```

</details>

**Comment by TylerLeonhardt** [comment] 2024-12-03 00:22
What kind of account? GitHub or Microsoft?

**Comment by TylerLeonhardt** [comment] 2024-12-04 00:57
@rizkyyusfian can you try today's insiders with this setting:

```
"microsoft-authentication.implementation": "msal"
```

Make sure you restart VS Code afterwards.

**Comment by TylerLeonhardt** [comment] 2024-12-04 00:58
I'm thinking this is a duplicate of https://github.com/microsoft/vscode/issues/229456

**Closed** 2024-12-11 11:26 UTC
Labels: info-needed

**Comment by rizkyyusfian** [comment] 2024-12-11 12:15
Works, Thanks!
