### ISSUE TITLE
Left over Code Helper at 100%, even though Code not running

### ISSUE THREAD

**Issue by chaseadamsio** [Microsoft/vscode#25152] opened 2017-04-21 17:35 UTC
- VSCode Version: 1.11.2
- OS Version: 10.11.6

![image](https://cloud.githubusercontent.com/assets/1024544/25289356/1cee3596-267e-11e7-9d73-732bdd0ac6da.png)

Code has left over helper at 100% CPU.

process:

```
43561   ??  R     14:42.80 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
```

Steps to Reproduce:

I have no idea how to reproduce this, but this happens every time I use Code and I often have to clean up a number of (not just one) left over processes.

**Comment by alexandrudima** [comment] 2017-04-25 09:18
@chaseadamsio This is the extension host process. If it consumes 100% CPU this is a very good indicator that there is an extension (core or from marketplace) that ends up in an endless loop or a very intense computation.

@joaomoreno Perhaps this is related to moving the git functionality into an extension?

**Comment by joaomoreno** [comment] 2017-04-25 13:43
@alexandrudima Very likely not...

@chaseadamsio What extensions do you have installed? You should try to reproduce it. Then, once you know the steps, attempt to reproduce with `code --disable-extensions`.

Closing as a duplicate of #20893. You'll find more info on how to debug there.

**Closed by joaomoreno** 2017-04-25 13:43 UTC
Labels: needs more info
