### ISSUE TITLE
Scrolling is not as smooth as it used to be

### ISSUE THREAD

**Issue by mostergaard** [Microsoft/vscode#15089] opened 2016-11-07 11:02 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|

---

When working with a "high precision" touch pad and using the two finger scroll it doesn't seem as "smooth" in the code editor as it did in previous versions of VS Code. When you first starting moving the fingers it takes a bit of time before it starts moving and then it "jumps". Once the scrolling is activated it is smooth, but once you let go of the fingers on the touch pad and then start again, it again has a delay before the scroll starts.

It should work just as smooth as it does in e.g. Chrome or Edge. This to me was one of the great advantages with VS Code over the full VS, so I am sad that we've lost the smooth scrolling again.

I'm on a Dell XPS15 and the touch pad should be a top-of-the-line touchpad (high precision).

**Comment by alexandrudima** [comment] 2016-11-07 15:12
We believe this was a regression in Chromium 52 (that we are not sitting on due to Electron 1.3.8) that was in the meantime already fixed in Chromium 54. Let's track in #13612

**Closed by alexandrudima** 2016-11-07 15:12 UTC
