### ISSUE TITLE
Expand selection doesnt honor editor.wordSeparators

### ISSUE THREAD

**Issue by TobiaszCudnik** [Microsoft/vscode#8440] opened 2016-06-28 21:05 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Set editor.wordSeparators to "_"
2. Try to expand selection (alt+shift+right on linux) on "^a_b"

Expected: "^a$_b"
Result: "^a_b$"

**Comment by jrieken** [comment] 2016-06-29 07:22
Yes - it's based on the tokinizer info and not on word info. The whole thing should be redone

**Comment by TobiaszCudnik** [comment] 2016-06-29 07:57
Glad to hear that it's gonna be redone. Its one of the missing features for me after switching from webstorm.

**Comment by rozzzly** [comment] 2016-06-29 23:20
I totally agree with Tobias, webstorm's selection grow is awesome and I miss it dearly. There are a few extensions on the marketplace expand upon vscode's native functionality, but even with them, its still interior to webstorm's implementation imho.

**Comment by jrieken** [comment] 2016-07-05 09:35
Closing this as a dupe of #4795 which is also about improving/redoing word selection.

**Closed** 2016-07-13 10:48 UTC
Labels: bug, duplicate, editor
