### ISSUE TITLE
 e.text.substr is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3228] opened 2016-02-22 08:55 UTC
Issue Id: <b>37805625-bfb3-36ca-de37-e04bbd17e7b9</b><br /><br />*Versions* <br />- 0.10.8<br />-  149e7a0debf3e32f95978a606e00d3c09bcac3d6<br />-  45d69357c9eb068dd8e624f5b0fe461cd2078d88<br />*Stack* <br />TypeError: e.text.substr is not a function<br />    at e.<anonymous> (out/vs/workbench/workbench.main.js:40:17379) <no sourcemaps><br />    at e.doElement (out/vs/workbench/workbench.main.js:38:18496) <no sourcemaps><br />    at e.li (out/vs/workbench/workbench.main.js:38:17765) <no sourcemaps><br />    at e.renderMessage (out/vs/workbench/workbench.main.js:40:16633) <no sourcemaps><br />    at out/vs/workbench/workbench.main.js:40:16382 <no sourcemaps><br />    at Array.forEach (native)<br />    at e.<anonymous> (out/vs/workbench/workbench.main.js:40:16358) <no sourcemaps><br />    at e.doElement (out/vs/workbench/workbench.main.js:38:18496) <no sourcemaps><br />    at e.ul (out/vs/workbench/workbench.main.js:38:17641) <no sourcemaps><br />    at e.renderMessages (out/vs/workbench/workbench.main.js:40:16223) <no sourcemaps><br />

**Comment by joaomoreno** [comment] 2016-02-22 14:14
Duplicate of #3230

**Closed by joaomoreno** 2016-02-22 14:14 UTC
Labels: error-telemetry
