### ISSUE TITLE
Restart while extension host debugging doesn't do anything anymore

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#98993] opened 2020-06-01 23:03 UTC
Pressing the "Restart" button when debugging an extension doesn't seem to do anything anymore.

**Comment by isidorn** [comment] 2020-06-02 10:05
@eamodio thanks a lot for filling this issue. I can reproduce only with new js-debug.
The problem is the following, for pwa-extensionhost a session has a parent session and when we match the session ids on the renderer recieving end there is not match, since we send the child id and the extensino host expects a parent id.

Two potential fixes (which I verified work).

1. For `pwa-extensionhost` sessions we should return the `session.parentSession` [here](https://github.com/microsoft/vscode/blob/cb23f8792961d46891d540d49a6678daf65bd5ef/src/vs/workbench/contrib/debug/common/debugUtils.ts#L61)
2. When launching the new vscode window we should pass the debugId of the child session, so the matching done [here](https://github.com/microsoft/vscode/blob/cb23f8792961d46891d540d49a6678daf65bd5ef/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L116) matches 

Forwarding to @connor4312  and assigning to May since this is a regression
fyi @weinand

**Comment by weinand** [comment] 2020-06-02 10:12
yes, this severe regression needs to be fixed for May.

@isidorn 's proposal sounds good as a workaround for now but we need to tackle the fundamental issue of the bogus parent session.

**Comment by connor4312** [comment] 2020-06-02 15:33
This seems to have broken when I made a "fix" so that the child sessions would have the same debug type as their parent sessions (which we needed for some scenarios using context keys; previously all children were always "chrome" debug types). This appears to have broken it. Because this is severe I will patch the extension host so that we preserve that debug type for children.

I will leave this open for a proper fix from Isi, since it may still be the case that we have extension host children if the user wants to debug any spawned child processes (e.g. language or debug servers).

**Comment by isidorn** [comment] 2020-06-02 15:41
@connor4312 Ok since you fixed it on the Extensions side, moving this out of June since I do not plan to push anything on the vscode side then this week.

**Comment by isidorn** [comment] 2020-07-31 15:37
Restart EH works just fine for me with the newest TS starter extension sample.
@eamodio if you still see this feel free to reopen

**Closed by isidorn** 2020-07-31 15:37 UTC
Labels: bug, debug
