### ISSUE TITLE
ANSI Escape Sequence (displaying true color) didn't work on Terminal

### ISSUE THREAD

**Issue by ylazy** [microsoft/vscode#231628] opened 2024-10-18 03:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Windows 11 24H2

Steps to Reproduce:

The ANSI Escape sequence didn't work as expected on Terminal panel. RGB Color didn't work, but Bold or Dim are fine. See the screenshot bellow.

The same output, Debug Console displayed correctly:

![Image](https://github.com/user-attachments/assets/cc16d0c5-df0e-4efb-8799-68c78b715035)

But Terminal displayed incorrectly:

![Image](https://github.com/user-attachments/assets/1fc30f0b-290e-430d-a6ba-3b28d54a5027)

**Comment by ylazy** [comment] 2024-10-18 04:00
My settings:

```json
...
"terminal.integrated.drawBoldTextInBrightColors": false,
"terminal.integrated.minimumContrastRatio": 1,
...
```

**Comment by ylazy** [comment] 2024-10-18 05:14
simple test:

```batch
type hello.txt
```

download [hello.txt](https://github.com/user-attachments/files/17428526/hello.txt)

![Image](https://github.com/user-attachments/assets/d9584903-c3c5-4e98-a23a-a04f02227f03)

**Comment by reaby** [comment] 2024-10-20 16:35
vscode for WSL2: ansi not working in "DEBUG CONSOLE", but works nicely on terminal:

DEBUG CONSOLE:
![Image](https://github.com/user-attachments/assets/7312eb0b-1aae-44eb-9e6e-e05ed12b62f4)


TERMINAL:
![Image](https://github.com/user-attachments/assets/1408086a-36a5-46c9-abb3-fc8196d92204)

**Comment by DenizUgur** [comment] 2024-11-23 12:52
I'm experiencing a similar issue; the debug console does not display ANSI escape codes. Running on macOS 15.1 (arm64).

**Comment by roblourens** [comment] 2024-12-10 22:18
Can you share the code?

**Comment by ylazy** [comment] 2024-12-11 03:22
Hi everyone!
This issue is about the Terminal, not the Debug Console.

**Comment by roblourens** [comment] 2024-12-11 23:05
Ah the second set of screenshots threw me off. Can you share the code that produces the output in your original screenshot?

**Comment by ylazy** [comment] 2024-12-12 02:40
> simple test:
> 
> type hello.txt
> download [hello.txt](https://github.com/user-attachments/files/17428526/hello.txt)
> 
> ![Image](https://github.com/user-attachments/assets/d9584903-c3c5-4e98-a23a-a04f02227f03)



> Ah the second set of screenshots threw me off. Can you share the code that produces the output in your original screenshot?

I've already attached the `hello.txt` above.
Thank you!

**Comment by Tyriar** [comment] 2024-12-19 13:19
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-19 13:19 UTC
Labels: info-needed
