### ISSUE TITLE
Salse: inferred proposals not visually distinct from global identifiers

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2380] opened 2016-01-26 16:04 UTC
I would expect some visual difference between `name`, `lastName` and the rest of proposals

![screen shot 2016-01-26 at 17 02 02](https://cloud.githubusercontent.com/assets/1926584/12585978/abfe74e6-c44e-11e5-928f-7ad96c42a798.png)

**Comment by egamma** [comment] 2016-01-27 08:57
duplicate of #2169

**Closed by egamma** 2016-01-27 08:57 UTC
