### ISSUE TITLE
Can't search extensions from extensions sidebar 

### ISSUE THREAD

**Issue by holodezzz** [Microsoft/vscode#57871] opened 2018-09-04 14:38 UTC
OS Version: Ubuntu 18.04
I have installed vs code with anaconda and kept getting this error
```
Installing Extensions ...
Server returned 503
   Unable to install python extensions for VSCode!
   Check /home/sergey/anaconda3/vscode_inst.py.log for more info
   Do you wish to retry? [yes|no]
```
vscode_inst.py.log showed me this
```
ERROR:vscode_inst:installVSCodeExtenstions
Traceback (most recent call last):
  File "/home/sergey/anaconda3/pkgs/vscode_inst.py", line 281, in installVSCodeExtenstions
    subprocess.check_call(_vscode_ext_args, shell=CMD_REQ_SHELL)
  File "/home/sergey/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/share/code/bin/code', '--install-extension', 'ms-python.anaconda-extension-pack', '--user-data-dir=', '/home/sergey/.config/Code']' returned non-zero exit status 1
```
I have followed the instructions from issue #27864 but I have those marketplace details in the product.josn

**Comment by igorbb** [comment] 2018-09-04 16:03
https://blogs.msdn.microsoft.com/vsoservice/?p=17405

Also this seems to be a duplicate of :

#57851

**Closed** 2018-09-04 17:52 UTC
Labels: *duplicate, extensions
