### ISSUE TITLE
Any file path suggestions for JavaScript/TypeScript

### ISSUE THREAD

**Issue by mishannn** [microsoft/vscode#104985] opened 2020-08-19 11:29 UTC
Issue Type: <b>Feature Request</b>

I would like to be able to see all files in the list of suggested import paths, or the ability to filter these hints. Now only shows JS/TS files, but I want to import CSS or SVG files for example.
I used extensions such as Path Autocomplete and Path Intellisense, but they are inconvenient to use, since they do not work well with path aliases, and also cannot be used when trying to fix part of a path in the middle of a line

![image](https://user-images.githubusercontent.com/15077672/90629581-4b699000-e228-11ea-8421-54069217534b.png)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.5.0

**Comment by mjbvz** [comment] 2020-08-19 17:44
Duplicate of https://github.com/microsoft/TypeScript/issues/29334

**Closed by mjbvz** 2020-08-19 17:44 UTC
