### ISSUE TITLE
Bug: Explorer does not respect negated .gitignore rule

### ISSUE THREAD

**Issue by yatki** [microsoft/vscode#69035] opened 2019-02-20 09:55 UTC
- VSCode Version: Version 1.31.1 
- OS Version: Majove 10.14.3

Steps to Reproduce:

1. Create the following files:
- /test/example/ignored.js
- /test/.gitkeep
2. Add the following rules to .gitignore
```
test/*
!test/.gitkeep
```

In the explorer `.gitkeep` file is grayed out even though git recognises it.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by AnsonYeung** [comment] 2019-03-03 08:10
Just wanted to report this issue.  

The changes in the file will be reported in the git tab but it will be greyed out as well. On the explorer tab, there would be a letter `M` indicating the change but still greyed out.

**Comment by markspanbroek** [comment] 2019-05-16 15:25
This issue is related: #38112. According to [this comment](https://github.com/microsoft/vscode/issues/38112#issuecomment-344518805) it is caused by a bug in `git check-ignore`.

**Comment by jrieken** [comment] 2019-05-24 13:19
fixed via https://github.com/microsoft/vscode/pull/73890

**Closed by jrieken** 2019-05-24 13:19 UTC
Labels: feature-request, file-explorer
