### ISSUE TITLE
vscode locking git repo

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#7409] opened 2016-06-08 12:24 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a repo in vscode so that the git bindings are active, leave this running in the background
2. Do your git interaction with TortoiseGit as usual
3. Notice that tortoise will regularly and randomly give errors failing to perform various operations because the repository appears to be locked (ie, some other git client is performing an operation). Tortoise will usually offer a 'retry' button; clicking retry almost always completes the action as intended.

I've noticed this seems to be related to whether I have vscode running or not. I suspect vscode is semi-actively doing fetches or something?
I'm sure this is manually configurable, but I feel like it should be more intelligent than that... perhaps vscode may also silently be experiencing repo lock failures when I'm interacting with TortoiseGit, and perhaps vscode might take this as an indicator that I'm using a separate git client, and automatically (or offer to) reduce it's auto fetch behaviour?

I'm not actually sure it's fetching, it could be something else, I just notice that the problems with TortoiseGit complaining about repo locks only seem to happen while vscode is running in the background.

**Comment by joaomoreno** [comment] 2016-07-12 07:57
This happens due to a `status` call, not `fetch`.

Duplicate of #901. Now Code will not call `status` when in the background.

**Closed by joaomoreno** 2016-07-12 07:57 UTC
Labels: bug
