### ISSUE TITLE
search regexp "$" don't works on closed CRLF end-of-line file

### ISSUE THREAD

**Issue by wtnbgo** [Microsoft/vscode#45210] opened 2018-03-07 14:12 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create CRLF end-of-line file
2. Close the file 
3.  Search at left pain with regexp contains "$" that may match 1.'s file
4.  No results found
 
When the file is opened or the file is LF end-of-line file, it works fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-03-07 21:59
/duplicate of https://github.com/Microsoft/vscode/issues/36309

**Closed by roblourens** 2018-03-07 21:59 UTC
Labels: search
