### ISSUE TITLE
Korean input error

### ISSUE THREAD

**Issue by jinkyu-mirrappa** [microsoft/vscode#193159] opened 2023-09-15 01:06 UTC
Type: <b>Bug</b>

It cannot be used due to a serious problem in which the same letter is repeated, deleted, or completely different consonants are automatically entered when entering Korean.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (9.15GB free)|
|Process Argv|--crash-reporter-id df435d95-65fe-4ee6-9302-230a3fee21e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
multi-cursor-case-preserve|Car|1.0.5
vscode-eslint|dba|2.4.2
gitlens|eam|14.3.0
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.10.5
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-ko|MS-|1.82.2023091309
vscode-edge-devtools|ms-|2.1.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.30.1
LiveServer|rit|5.7.9
html-to-css-autocompletion|sol|1.1.2
vscode-icons|vsc|12.5.0
vim|vsc|1.26.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30835152
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by tamuratak** [comment] 2023-09-15 01:41
Duplicate of #192843 and https://github.com/VSCodeVim/Vim/issues/8570

**Closed** 2023-09-15 12:56 UTC
Labels: new release
