### ISSUE TITLE
Copy from terminal doesn't work [Windows/Insiders]

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#31902] opened 2017-08-02 08:55 UTC
Steps to Reproduce:

1. open the integrated terminal and have it output some text so that scrolling happens
2. scroll up a little and select some text (see screenshot1)
3. press ctrl+c
4. press ctrl+v

Screenshot1:
![copypaste1](https://user-images.githubusercontent.com/199648/28865591-b3b6fb8c-7770-11e7-95e9-68c7650695ae.gif)

What happens: terminal scrolls to the bottom and the text that was previously in the clipboard (here `that's not what I copied`) is pasted, instead of the one I just copied using ctrl+c

Now, if I don't end the selection (ie: release the left mouse button) before reaching the left side of the screen, it will work:

![copypaste2](https://user-images.githubusercontent.com/199648/28865599-b8bce0ba-7770-11e7-9549-fffeca4054cf.gif)

I am using the latest insider build (211ffdf) on Windows 10 (64bit).

I tried and could not reproduce the problem on a standard cmd prompt.

**Comment by Tyriar** [comment] 2017-08-02 16:24
@warpdesign to clarify, it's only happening when you release the mouse outside of the terminal?

**Comment by nico-onmap** [comment] 2017-08-03 08:41
@Tyriar Yes, releasing the mouse outside of `<div class="terminal-wrapper active></div>` triggers the bug.

**Comment by warpdesign** [comment] 2017-08-03 08:42
@Tyriar Yes, releasing the mouse outside of `<div class="terminal-wrapper active></div>` triggers the bug.

As long as I release the mouse inside this div it works as expected.

**Comment by warpdesign** [comment] 2017-10-13 12:32
Any idea when this will be fixed? It still happens in latest insiders build and is really annoying.

Does it still need the `needs more info` tag?

**Comment by Tyriar** [comment] 2017-10-30 18:40
Will be fixed when time allows, I'm pretty flooded with other issues atm though. It's open to PRs though. The root cause will likely be in https://github.com/sourcelair/xterm.js

**Comment by warpdesign** [comment] 2017-10-31 11:10
I played a little with xterm.js but I cannot reproduce the problem. When selecting text, even if I release the mouse outside of the terminal, term.getSelection() returns the correct selection.

**Comment by warpdesign** [comment] 2017-10-31 12:49
It seems like this action is not ran when the mouse is released outside of the terminal div:

```js
actionRegistry.registerWorkbenchAction(new SyncActionDescriptor(CopyTerminalSelectionAction, CopyTerminalSelectionAction.ID, CopyTerminalSelectionAction.LABEL, {
 	primary: KeyMod.CtrlCmd | KeyCode.KEY_C,
 	linux: { primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_C }
 }, ContextKeyExpr.and(KEYBINDING_CONTEXT_TERMINAL_TEXT_SELECTED, KEYBINDING_CONTEXT_TERMINAL_FOCUS)), 'Terminal: Copy Selection', category);
```

**Comment by warpdesign** [comment] 2017-10-31 12:52
One more thing I noticed, if I do the following:

 1. select some text and release the mouse outside of the terminal div
 2. hide the terminal panel (with `ctrl+ù`)
 3. show the terminal panel (with `ctrl+ù` again)
 4. press `ctrl+c `

The text is copied as expected: maybe there is something wrong with `KEYBINDING_CONTEXT_TERMINAL_FOCUS`: it seems terminal kind of loses focus when the mouse is being released outside of the terminal div.

**Comment by warpdesign** [comment] 2017-10-31 13:17
Actually, this is `KEYBINDING_CONTEXT_TERMINAL_TEXT_SELECTED` that's the problem: commenting it, copy/paste works after releasing the mouse outside of the terminal area.

**Comment by warpdesign** [comment] 2017-10-31 13:26
I think the problem is in `terminalInstance.ts`:

```ts
		this._instanceDisposables.push(dom.addDisposableListener(this._xterm.element, 'mouseup', (event: KeyboardEvent) => {
			// Wait until mouseup has propagated through the DOM before
			// evaluating the new selection state.
			setTimeout(() => this._refreshSelectionContextKey(), 0);
		}));
```

The `mouseup` event isn't triggered if the mouse is released outside of the xterm element, so the selection isn't refreshed in this case, and the `CopyTerminalSelectionAction` is not executed.

**Closed** 2017-12-27 14:59 UTC
Labels: bug, help wanted, integrated-terminal, upstream
