### ISSUE TITLE
FileSystemProvider: Switching file in the editor causes explorer incomplete sync

### ISSUE THREAD

**Issue by plus-** [microsoft/vscode#74006] opened 2019-05-20 16:28 UTC
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Implement a remote FileSystemProvider
2. In the explorer browse and open 2 different files Apple & Banana
    Apple uri is like so `scheme:/path/to/Apple`
3. After opening Banana go back to Apple from the editor title
4. The explorer will update without the children from the top parent folder containing Apple (in above example `path `will be empty). All other folders still have their children.
5. Also the "Refresh Explorer" button doesn't load that folder children.
6. Closing all files from that folder in the editor will fix the previous issue.

It may be related to the logic behind highlightning the current file in the explorer.

**Comment by plus-** [comment] 2019-05-21 15:34
I'm reopening this as I though it was an issue on my side but I have more information.

It happens only for the first folder defined in the vscode workspace, other folders works fine (although the current file is not highlighted in the explorer). If I switch around the remote filesystem in the workspace the issue is always happening on the first one defined.

I've checked the debugger and it only calls readDirectory for the first folder of the workspace when switching files in the editor.

**Comment by plus-** [comment] 2019-05-21 16:03
![example](https://i.imgur.com/JHrxsdo.gif)

**Comment by isidorn** [comment] 2019-05-24 09:26
Got it. Looks like a duplicate of https://github.com/microsoft/vscode/issues/73469
If you F1 > developer tools > console
Do you see some errors?

**Comment by plus-** [comment] 2019-05-24 09:50
No errors in the console.

**Comment by plus-** [comment] 2019-07-09 13:06
I've noticed the bug still exist in the VSCode Insiders version. Switching tabs remove the opened folder from the explorer like before, however now the refresh sometimes works (about half the time), the opened folder will reappear.

**Closed** 2019-10-09 09:32 UTC
Labels: *out-of-scope, file-explorer, needs more info
