### ISSUE TITLE
Highlight headings in Markown marked with equals or minus sign 

### ISSUE THREAD

**Issue by helmbold** [Microsoft/vscode#45296] opened 2018-03-08 13:50 UTC
In Markdown documents with headings marked with equals signs (`=====`) or minus signs ( `-----`) the line with these signs gets highlighted, but the words in the heading should be highlighted (too) to be consistent with headings marked with `#`. Currently it loosk like this.

![heading pung](https://user-images.githubusercontent.com/5079980/37154283-c5fb1b96-22df-11e8-899d-e22f1ee9ec2d.PNG)

**Comment by mjbvz** [comment] 2018-03-08 19:56
Duplicate of #9784

See [my comment](https://github.com/Microsoft/vscode/issues/22895#issuecomment-288629263) on why this is wont-fix

**Closed by mjbvz** 2018-03-08 19:56 UTC
