### ISSUE TITLE
1.49.0 Lense logic regression from 1.48.2

### ISSUE THREAD

**Issue by lifeart** [microsoft/vscode#106876] opened 2020-09-16 17:10 UTC
- VSCode Version: 1.49.0
- OS Version: Win/Mac/Linux

Steps to Reproduce:

1. install https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable
2. open https://github.com/Brain-up/brn/tree/master/frontend
2.5 open: frontend/app/app.js in 
3. wait 20 seconds (for extension initialization)
![image](https://user-images.githubusercontent.com/1360552/93369617-4fed8c80-f858-11ea-9001-9fa9251d3ded.png)
such Icon should appear on the bottom)
4. go-to frontend/app/components/exercise-steps/template.hbs
![image](https://user-images.githubusercontent.com/1360552/93369705-73183c00-f858-11ea-9e9d-ab2fa9e11e1a.png)
5. check Lenses on first line of a file, should be `_template_ | component | test`, try to move clicking on it, in some files lences will dissapear or appear partially.
![image](https://user-images.githubusercontent.com/1360552/93369759-85927580-f858-11ea-891d-c11a493fd845.png)

![image](https://user-images.githubusercontent.com/1360552/93369817-97741880-f858-11ea-9cd5-b492d21cb415.png)

Does this issue occur when all extensions are disabled?: Yes

this is how Lenses implemented: https://github.com/lifeart/vscode-ember/blob/master/src/lenses.ts#L106
last `|` should not appear, it should be one more lense link

**Comment by Alonski** [comment] 2020-09-16 18:44
Please help fix this

**Comment by lifeart** [comment] 2020-09-16 18:58
looks like it's codelense internal markup isssue, in devtools, I see nodes

![image](https://user-images.githubusercontent.com/1360552/93380316-c04fda00-f867-11ea-8422-2cfd49c81fd5.png)

**Comment by lifeart** [comment] 2020-09-16 19:04
looks related to: https://github.com/microsoft/vscode/issues/106718

**Comment by jrieken** [comment] 2020-09-17 08:47
Can you try with latest insiders (1.50.0, d1f267742169584db010716d92addf50d4cd8139) which has a fix for #106718

**Comment by lifeart** [comment] 2020-09-17 13:10
@jrieken I can confirm, it's working, thank you!

**Comment by jrieken** [comment] 2020-09-17 14:02
/duplicate of #106718

thanks for coming back to. closing as duplicate, we might also cherry-pick this for the recovery release

**Closed** 2020-09-17 14:03 UTC
Labels: *duplicate, code-lens

**Comment by jrieken** [comment] 2020-09-17 15:41
@lifeart Looking at https://github.com/lifeart/vscode-ember/blob/4e3153777fadc0fb5bec7477f30c8984695b594d/src/lenses.ts#L75. Are you maybe producing code lenses with trailing whitespace at the end? You can try to trim that in see if the issue then disappears (using 1.49)?
