### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by ademfrigui** [microsoft/vscode#121011] opened 2021-04-10 13:32 UTC
Issue Type: <b>Bug</b>

i have this bug https://ibb.co/54QkTZP , can i please get some help 

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.21GB free)|
|Process Argv|--crash-reporter-id 3a58aaad-6fe2-46c2-a07d-3677afe6859c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
el-vsc-product-icon-theme|ElA|0.1.8
prettier-vscode|esb|6.3.2
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
vshan820:30276952
vscus158cf:30286554

```

</details>

**Comment by SupinePandora43** [comment] 2021-04-10 17:39
Does other gpu applications looks good, eg Chrome, games on DirectX/OpenGL?
it may be a problem in your gpu.

**Comment by ademfrigui** [comment] 2021-04-10 19:54
> Does other gpu applications looks good, eg Chrome, games on DirectX/OpenGL?
> it may be a problem in your gpu.

every app looks just fine

**Comment by IllusionMH** [comment] 2021-04-10 20:05
/duplicate of #92379 which is some upstream issue

Should work with `--disable-gpu` flag or more permanent disable https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration 

Also check https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 look like Nvidia drivers may also affect rendering of Electron apps.

**Closed** 2021-04-10 20:05 UTC
Labels: *duplicate, new release

**Comment by ademfrigui** [comment] 2021-04-12 19:13
@IllusionMH thanks for the help
