### ISSUE TITLE
Developer Tools becomes all white when using Inspect Element on Windows

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#113530] opened 2020-12-29 08:29 UTC
* from master, on Windows
* run `scripts\code.bat`
* open an editor
* press Ctrl+F
* open developer tools
* use inspect and pick the find widget input
Observe how developer tools becomes all white and is no longer usable:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/103270485-54c5ee80-49b8-11eb-9bad-9e89ab6eeb0a.gif)

I'm going to give it important because it is really really annoying to not have Inspect Element.

**Comment by IllusionMH** [comment] 2020-12-29 10:37
Duplicate of #112172

**Closed** 2020-12-29 11:35 UTC
Labels: electron-11-update, important
