### ISSUE TITLE
Process Explorer and code --status only show some processes (OS X)

### ISSUE THREAD

**Issue by ehausen** [microsoft/vscode#66400] opened 2019-01-11 13:52 UTC
I'm trying to debug some occasionally appearing high CPU usage of _Code Helper_ processes on OS X.

In Process explorer or `code --status` I'm expecting something like this
 ![image](https://user-images.githubusercontent.com/6204129/51037211-3f334080-15b8-11e9-9bd2-98070b398d6e.png)
(image from: https://github.com/Microsoft/vscode/wiki/Performance-Issues)

But instead I see:
![screen shot 2019-01-11 at 15 38 46](https://user-images.githubusercontent.com/6204129/51037344-9b966000-15b8-11e9-8423-9eda1743a704.png)
 
and `code --status`
![screen shot 2019-01-11 at 15 50 53](https://user-images.githubusercontent.com/6204129/51037388-ba94f200-15b8-11e9-9694-b756a02c4492.png)

How can I find out what is causing some _code helper_ process to sometimes cause high cpu usage for awhile?

**Comment by ehausen** [comment] 2019-01-11 15:58
Activity monitor looks like this
![screen shot 2019-01-11 at 17 28 29](https://user-images.githubusercontent.com/6204129/51044690-5da23780-15ca-11e9-96b2-0108d9eba0eb.png)

@weinand thinks it looks like a bug

**Comment by RMacfarlane** [comment] 2019-10-25 21:52
Duplicate of https://github.com/microsoft/vscode/issues/53999

**Closed by RMacfarlane** 2019-10-25 21:52 UTC
Labels: bug, workbench-diagnostics
