### ISSUE TITLE
Grid layout breaks auto-expanding editor panes.

### ISSUE THREAD

**Issue by Taugeshtu** [Microsoft/vscode#53702] opened 2018-07-06 12:04 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:
1. Open three editors in horizontal arrangement fashion:
![screenshot_2](https://user-images.githubusercontent.com/6285293/42377651-cc4987e8-812c-11e8-9d9d-e05581d49546.png)
2. Squeeze the right-most one to minimal allowed size
3. Switch focus to the middle one, then to the squeezed one
4. Editor sizes DO NOT CHANGE

This didn't happen prior to 1.25 - editor panes, when one was contracted to a minimum, used to expand the one that's focused and squeeze those that were not in focus. This change (statically sized editor panes) completely breaks my workflow :(

What's worse - when going to "Zen" mode it leaves BIG WIDE STRIPES OF NOTHINGNESS on the sides! 
![screenshot_3](https://user-images.githubusercontent.com/6285293/42377865-d1e60978-812d-11e8-8a5c-aca859db75e7.png)
Are we going for a hip & cool new look of new-wave messengers suck as Viber and WhatsApp over _getting the job done in a functional manner_ now?

**Comment by Taugeshtu** [comment] 2018-07-06 12:18
This is the behaviour I came to absolutely love and utilize heavily:
![1_24_behaviorur](https://user-images.githubusercontent.com/6285293/42378316-910f9e6c-812f-11e8-9417-17b3f9145bbd.gif)

That way I don't lose track of the files I jump between while working on some feature, but when I jump between them I always have the one in focus maximized. 1.25-way, where the sizes don't change - no bueno.

**Comment by bpasero** [comment] 2018-07-06 12:32
Duplicate of https://github.com/Microsoft/vscode/issues/51614

**Closed** 2018-07-06 12:32 UTC
Labels: *duplicate, new release, workbench-grid

**Comment by bpasero** [comment] 2018-07-07 10:19
@Taugeshtu 

> What's worse - when going to "Zen" mode it leaves BIG WIDE STRIPES OF NOTHINGNESS on the sides!

You can disable this by configuring `"zenMode.centerLayout": false`
