### ISSUE TITLE
Feature-request: Request for Native FTP/SFTP Plugin

### ISSUE THREAD

**Issue by peterson-umoke** [Microsoft/vscode#47301] opened 2018-04-06 09:15 UTC
Please.... I am so In Love with VSCODE... Problem here is finding a standard FTP Plugin... Once I can you to sync with my online server and edit files online.. is it possible to have ftp come natively installed with the IDE... you know it will be a big plus.

**Comment by roblourens** [comment] 2018-04-06 16:57
/duplicate of https://github.com/Microsoft/vscode/issues/20861

**Closed** 2018-04-06 16:57 UTC
Labels: *duplicate
