### ISSUE TITLE
Status bar background color

### ISSUE THREAD

**Issue by joe-watkins** [Microsoft/vscode#1884] opened 2016-01-08 18:15 UTC
The blue color is very distracting.. a way to change the color of that would be great!

<img src="http://content.screencast.com/users/joe-watkins-emerge/folders/Snagit/media/412cd601-ba5d-4ccf-a0b5-25bc36237ff0/2016-01-08_10-14-31.png">

**Comment by Witcher42** [comment] 2016-01-22 09:52
+1!
I hate that color and that mysterious smiley face. Hoping there's a way to change the style of status bar.

**Comment by collinksmith** [comment] 2016-02-13 01:18
+1

**Comment by 4781121** [comment] 2016-02-14 05:25
+1

**Comment by RiCoTeRoX** [comment] 2016-02-29 15:46
+1

**Comment by wcharczuk** [comment] 2016-03-02 20:34
+1

**Comment by artemeff** [comment] 2016-03-03 20:54
+1

**Comment by Nimzozo** [comment] 2016-03-03 22:06
:-1: -1 I like it lol.

**Comment by bgashler1** [comment] 2016-03-23 19:03
Sorry for the delayed response on this issue.  We use blue within the status bar because it's consistent within the family of Visual Studio.  We may in the future open this and other things to customization via user style sheets.  Hopefully that will address any concerns you have with the color.

**Comment by ypyf** [comment] 2016-04-29 09:18
+1

**Comment by bjz** [comment] 2016-05-08 04:01
@bgashler1 I understand your desire to default to aligning with the VS branding, but the color is extremely distracting for some people. It would be great if you could at least have a user style sheet that would allow us to dim it down, or just set it to always be black. This is about the only thing that is preventing me from committing to your fantastic editor.

**Comment by ccknot** [comment] 2016-05-11 06:36
+1

**Comment by jmcooper** [comment] 2016-05-25 04:52
+1

**Comment by Tyriar** [comment] 2016-05-25 20:26
Reopening. This will likely be part of https://github.com/Microsoft/vscode/issues/1231

**Comment by Kenny-Wang** [comment] 2016-06-08 08:21
+1

**Comment by shubhamsizzles** [comment] 2016-06-11 08:32
If you look at the editor from a metre away, the only thing you will see is the deeply saturated status bar, which is actually pretty distracting while editing.

 Since  #1231 is now closed, it would be nice to have a option to tone it down a bit.

**Comment by Tyriar** [comment] 2016-06-12 02:19
@shubhamsizzles there were multiple levels of duplicates, follow the UI theme issue here https://github.com/Microsoft/vscode/issues/3112

**Comment by natdm** [comment] 2016-07-02 02:47
If the status bar distracts you from developing, maybe you have other issues?

I'm cool with the color. Blue in 'normal' conditions, orange-red in debug mode. Works for me.

**Comment by wcharczuk** [comment] 2016-07-02 02:55
> If the status bar is what distracts you from developing, maybe you have other issues? 

I'll take passive aggressive responses for 100, Alex.

**Comment by natdm** [comment] 2016-07-02 03:20
Not passive aggressive. 

Out of all the things to complain about in an IDE, the status bar at the bottom? Not bugs, lack of features to assist in more efficient development, language support, better debugging or GIT integration, lack of community, etc... (not saying VSC has these issues) but.. the color of the status bar at the bottom?

**Comment by shubhamsizzles** [comment] 2016-07-02 03:45
@natdm Well, guess what, UI does matter in an IDE/editor. If it were only for the features you mentioned not, we'd all be using vim/emacs

**Comment by glen-84** [comment] 2016-07-05 19:14
If #459 was implemented, this would be easy to change.

**Comment by dnaroid** [comment] 2016-07-06 14:32
`echo ".monaco-workbench>.part.statusbar{background-color:#000;}" | sudo tee -a /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.css`

**Comment by be5invis** [comment] 2016-07-08 00:21
My current CSS patch for Code:

```css
/***** PATCHES *****/
.monaco-workbench.hc-black { color: #FFF; background-color: #000; }
.monaco-workbench.hc-black .sidebar .separator 	{ background-color: #000; border: 1px solid #6FC3DF; }
.monaco-workbench.hc-black input,
.monaco-workbench.hc-black textarea {
	background-color: #000;
}
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled,
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled:hover {
	opacity: 1;
}
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled:before {
	opacity: .4;
}

.monaco-shell { font-family: "Iosevka", "Helvecita", "Inziu Iosevka SC", sans-serif}
.monaco-shell:lang(zh-Hans) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka SC", sans-serif}
.monaco-shell:lang(zh-Hant) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka CL", sans-serif}
.monaco-shell:lang(ja) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka J", sans-serif}
.monaco-workbench > .part > .content {font-size:11px}
.decorationsOverviewRuler{
	clip:rect(2px,13px,1000px,2px);
	margin-top: -2px;
	height:calc(100% + 4px);
}
.monaco-workbench.vs-dark .editor > .content > .editor-center,.monaco-workbench.vs-dark .editor > .content > .editor-right { border-left-color:#0a0a0a}
.monaco-workbench.vs-dark { background: #252525 }
.monaco-editor.vs-dark .git-dirty-modified-diff-glyph {	background-color: rgba(250,190,28,0.6) }
.explorer-viewlet .explorer-item-label, .explorer-viewlet .working-files-item-label { color: rgb(190, 190, 190) }
.vs-dark .monaco-tree .monaco-tree-row.selected { color: rgb(210, 210, 210) }
.vs-dark .monaco-tree .monaco-tree-row.focused, .vs-dark .monaco-tree .monaco-tree-row.selected { background: rgb(57,57,56)!important }
.vs-dark .monaco-tree .primary-action-bar,.vs-dark .monaco-tree.focused .monaco-tree-row.focused:not(.highlighted)>.content.actions>.primary-action-bar { background: none!important }
.monaco-workbench.no-workspace>.part.statusbar,.monaco-workbench > .part.statusbar {background: rgb(21,21,21)}
.monaco-workbench > .part.statusbar>.statusbar-item{opacity: 0.6}
.monaco-workbench>.part.panel>.title { border-top-color: rgba(255,255,255,0.1) }
.monaco-editor.vs-dark .git-dirty-modified-diff-glyph { background: none }
.monaco-editor.vs-dark .current-line {border: none}
.monaco-editor.vs-dark .selectionHighlight { background: rgba(173,214,255,0.1)}

.token.haskell { font-feature-settings: "XHS_" 1; }
.token.patel { font-feature-settings: "XPTL" 1; }

.explorer-open-editors .editor-group { visibility: hidden }
.explorer-open-editors .monaco-tree-row.expanded { margin-bottom: -22px }
.explorer-open-editors .monaco-tree-row + .monaco-tree-row.expanded { border-top: 1px solid rgba(255,255,255,0.05); margin-top: -1px }
```
I have to do this every update. Please support user CSS or UI themeing.

**Comment by rossHell** [comment] 2016-07-08 15:03
Really ? Distractive ? Are you not able to drive your eyes ? Never seen an issue for an IDE so stupid

**Comment by smlombardi** [comment] 2016-07-08 23:29
@be5invis Where is this file located?

**Comment by dracan** [comment] 2016-07-10 07:33
+1 Whilst I personally don't find it a distraction as such - I dislike that when making the editor fullscreen (F11) it's the only thing that stops the editor feeling completely seamless (for lack of a better word). Try loading the Atom editor in dark theme and make that fullscreen. It looks completely seamless. VSCode would look just as good (if not better) if it wasn't for this out of place blue bar at the bottom.

**Comment by smlombardi** [comment] 2016-07-10 17:51
I think it's really hideous in an otherwise attractive UI. It's not that it's blue (although grey would be better), it's too bright.  I have seen it looks better on Win 10 than on Mac (I am on Mac). But it's just a status bar, why should it command so much attention? 

For those commenting that we should "get a life" instead of complaining about something so "trivial", remember that the UI of an application is something you stare at all day.  It should please you as well as assist you. Even a simple way to color it in a theme or other editor pref would be appreciated.

**Comment by be5invis** [comment] 2016-07-11 17:57
Made an extension to patch your custom CSS into Code:

https://github.com/be5invis/vscode-custom-css
https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

Set the `vscode_custom_css.file` option to the CSS you’d like to apply and enable it.

**Comment by dominique-mueller** [comment] 2016-07-11 22:12
`vscode-custom-css` works like a charm! I patches my CSS with this one here: https://gist.github.com/dominique-mueller/0d9f5aec202804caca4881838685cfc4, in combination with the Oceanic dimmed theme.

**Comment by heidricha** [comment] 2016-09-14 13:46
I don't mind the default blue, my problem is, that it is blue for all VScode windows.

It would be fine to set the color quickly (right click on status bar??). when working with more than one window of VS code, I could be able to spot the window I need on the gnome task selection

anyway, sometimes the status bar is purple, or orange, which seems have specific meanings

**Comment by felippem** [comment] 2016-09-15 20:23
+1

**Comment by nfantone** [comment] 2016-09-16 10:47
@be5invis Tried your extension and working fantastic. A bit tedious if you are using Insiders, but great nonetheless. Cheers.

Incidentally, is there anyway to set icons on the sidebar using font faces, instead of `png` files?

**Comment by sysrpl** [comment] 2016-09-18 08:47
Help -> Toggle Developer Tools -> Console

> document.getElementById("workbench.parts.statusbar").style.color = "black"

**Comment by tylercubell** [comment] 2016-09-20 22:28
1. Install and enable https://github.com/be5invis/vscode-custom-css
2. Restart Visual Studio Code as Administrator
3. Create `style.css`:

    ```css
    .monaco-workbench.no-workspace>.part.statusbar {
      background-color: #333333 !important;
    }
    ```

4. File > Preferences > User Settings

    ```json
    {
        "vscode_custom_css.imports": [
            "file://path_to_css_file/style.css"
        ]
    }
    ```
5. F1 > Enable Custom CSS and JS
6. Restart Visual Studio Code

**Comment by Tyriar** [comment] 2016-09-20 23:19
Please keep in mind that this extension literally changes the source code of VS Code and you could very well run into issues if you install it. We have seen several cases of extensions like this corrupting the install and the only way to get it back is to reinstall vscode.

**Comment by tylercubell** [comment] 2016-09-20 23:37
@Tyriar With reference to #3112, #1231, #1833, and #76, it sounds like the proper way to achieve this result is through an official API, however it's been [on the backlog](https://github.com/Microsoft/vscode/issues/1231#issuecomment-166406454) for 10 months. Is there any update on when this API might get implemented?

**Comment by Tyriar** [comment] 2016-09-21 17:17
@tylercubell I asked the team and we're going to be looking at #3112 as part of this point on [our roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap#eliminate-adoption-blockers):

>Workbench theming, e.g.,support icons in explorer

It bugs me too as the theme I use has a much darker grey background that makes it look a bit awkward.

**Comment by WilldelaVega777** [comment] 2016-09-23 14:50
Any news on this? the vscode_custom_css hack doesn't seem to be working as 9/2016.

**Comment by nfantone** [comment] 2016-09-23 18:21
@WilldelaVega777 Well... did you read the post just above yours?

**Comment by gigapixel** [comment] 2016-09-25 16:28
+1

**Comment by stentor-me** [comment] 2016-09-28 06:08
+1

**Comment by kuangluvasuka** [comment] 2016-10-04 07:27
+1

**Comment by etoah** [comment] 2016-10-09 07:32
+10086

**Comment by csalv5** [comment] 2016-10-10 18:53
+1

Purple is ok, but blue is toooo bright/distracting

**Comment by etoah** [comment] 2016-10-11 10:02
+1

**Comment by nfantone** [comment] 2016-10-11 10:42
You know... there's a reason Github implemented _reactions_...

**Comment by FilipMiletic** [comment] 2016-10-11 11:46
If we could at least have an option to make it gray, like the rest of the UI. Because I need the info it contains, but it's still distracting me a lot.

**Comment by mistermark** [comment] 2016-10-14 13:31
+1

**Comment by pkieltyka** [comment] 2016-10-14 13:34
+10

**Comment by jaquinonesg** [comment] 2016-10-14 16:04
+1

**Comment by anh072** [comment] 2016-10-22 03:58
I hate that blue color

**Comment by smlombardi** [comment] 2016-10-26 19:32
@bgashler1 Theming would be nice, but a simple gray that relates to the sidebar and tree background would be enough.  Possibly behind a flag in preferences?

**Comment by pkieltyka** [comment] 2016-10-27 13:15
hey all - in the short term, this is a really good option that lets you customize the status bar css and apply a whole bunch of custom css: https://github.com/be5invis/vscode-custom-css

**Comment by tylercubell** [comment] 2016-10-27 14:52
@pkieltyka Did you even bother to read the comment history?

**Comment by pkieltyka** [comment] 2016-10-27 15:00
@tylercubell usually I do, my mistake

**Comment by subosito** [comment] 2016-10-27 15:43
Until it's supported officially, I decided to make a simple tool to customize my vscode status bar. You can check it on https://github.com/subosito/vscd.

Basically, it append custom css to `workbench.main.css` and then update the checksum on `product.json`, so vscode can render custom style and `Unsupported` message on title bar can be avoided.

**Comment by Tyriar** [comment] 2016-10-27 15:48
@subosito the checksum and warning is there for a reason. When extensions started modifying the source of VS Code we got a significant influx of issues that were hard to diagnose and wasted a lot of the team's time. Creating a tool this like **will** negatively affect the team's productivity and VS Code as a result.

**Comment by subosito** [comment] 2016-10-27 15:55
Thanks for the explanation @Tyriar, I was thinking about my personal customization (not an extension, just simple tool), didn't know about the impact to VS code team :|. While I am keeping this for my personal needs, I think you can delete my comments (including this one), so other people can stick to standard. I will add some warning to my repo as well.

By the way, thanks for creating Visual Studio Code, it's awesome :+1:

**Comment by nfantone** [comment] 2016-10-27 15:59
Well, it's not the first time extensions like that were created. In fact, there's one such extension among the **TOP 5** most popular ones in the market (* _[cough](https://github.com/robertohuertasm/vscode-icons)_ *).

This is truly striking from a sociological stand - things happening in this repo, I mean.

**Comment by ibuisic** [comment] 2016-11-02 11:11
+1

**Comment by dfucci** [comment] 2016-11-03 18:59
+1

**Comment by be5invis** [comment] 2016-11-04 23:17
Maybe, I say MAYBE, someone could implement an official theming function (or module, whatever) first and report afterwards. It is called 先斬後奏 in China.

**Comment by AlexCasa** [comment] 2016-11-11 22:56
Without using plugin, you can just open this file`workbench.main.css` and change `.monaco-workbench>.part.statusbar` from `background:#007acc;` to `background:#252526;` (gray).

**Comment by impaler** [comment] 2016-11-12 00:32
Thanks @AlexCasa hack worked, the file was located on linux at /usr/share/code/resources/app/out/vs/workbench/workbench.main.css

I look forward to be able to do this without editing minified css files :hurtrealbad:

**Comment by rgfx** [comment] 2016-11-12 20:52
File Location on windows 7

C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css

**Comment by geddski** [comment] 2016-11-15 20:03
it would be great to make skinning the entire UI possible

**Comment by 1-9** [comment] 2016-11-17 20:14
Blue status bar is distracting, please set the default to black (or some variation, so it doesn't stand out).

**Comment by itclinic** [comment] 2016-11-17 20:26
2559-11-18 3:15 GMT+07:00, Surya Kotamraju <notifications@github.com>:

**Comment by osminogin** [comment] 2016-11-18 11:47
If even all ok, one thing MUST be not ok. Microsoft style.

**Comment by bgashler1** [comment] 2016-11-23 22:12
While we work on enabling custom theming of the UI, we are considering the following changes to the default UI colors.

You'll notice we're thinking of muting the status bar.

![dark-01](https://cloud.githubusercontent.com/assets/11839736/20580149/a016b150-b185-11e6-845b-2d80c26222ae.png)
![light-01](https://cloud.githubusercontent.com/assets/11839736/20580373/cb52d280-b186-11e6-8526-12503483b8d7.png)


None of this is set in stone.  Would love to hear what you think.  Please use the GitHub reactions
![screen shot 2016-11-23 at 2 05 45 pm](https://cloud.githubusercontent.com/assets/11839736/20580218/f255eb5c-b185-11e6-8620-cb8c398b6455.png)
 so we can get a feel for how people like this.

**Comment by be5invis** [comment] 2016-11-23 22:14
@bgashler1 If the gray color is an opt-in, please, give us the ability to customize (and also, the other UI elements: color, size, spacing, typography, etc.)

**Comment by bgashler1** [comment] 2016-11-23 22:15
@be5invis we are working on enabling some UI theming capabilities as well #3112

**Comment by be5invis** [comment] 2016-11-23 22:39
@bgashler1 
For a theme builder, they want the theming capability not being limited in the area of colors. Using CSS is a final solution, though the theming power in Sublime Text works well either.

**Comment by faustinoaq** [comment] 2016-11-25 18:23
🙂 +1 [These captures](https://github.com/Microsoft/vscode/issues/1884#issuecomment-262642690) looks great!

**Comment by mathisonian** [comment] 2016-11-29 23:15
For OSX users trying to make the change @AlexCasa suggested, the file is located at:

```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css
```

**Comment by qcol** [comment] 2016-11-30 11:11
+1

**Comment by owenso** [comment] 2016-12-08 11:42
+1

**Comment by joeshub** [comment] 2016-12-09 00:09
@bgashler1 please remove the awkward smiley, or at least make it less weird. May I suggest something like this instead?
https://image.freepik.com/free-icon/comment-bubble-outline_318-27591.png

**Comment by bgashler1** [comment] 2016-12-09 01:23
@joeshub We are working on enabling people to remove UI by right-clicking on it.  @bpasero will it also be possible to do this with the smiley face?

**Comment by bpasero** [comment] 2016-12-09 05:38
Yeah probably. Note that we cannot (currently) allow users to hide things in the status bar because of the way how extensions can add things there in a very dynamic way.

**Comment by firstrow** [comment] 2016-12-09 10:28
+1

**Comment by bentx** [comment] 2016-12-14 03:01
Until this is implemented as a default feature, if anyone wants to use custom colors for UI elements, as well as disabling the smiley face, I created this extension. It doesn’t require manual css editing, everything is done from user settings. (note : it doesn’t trigger the “unsupported” mode)
https://github.com/bentx/vscode-custom-theme
https://marketplace.visualstudio.com/items?itemName=bentx.vscode-custom-theme

**Comment by Tyriar** [comment] 2016-12-14 04:16
@bentx this uses exactly the same technique as all the other extensions that trigger the unsupported mode because it overrides the CSS and JS files, you just disable the message...

**Comment by bentx** [comment] 2016-12-14 04:23
@Tyriar The only other extension I've seen for custom theming was loading a css file, I wanted everything to be manageable from user settings, it's less prompt to error and easier to use. I get the fact that you don't like it, since it "corrupts" the software, but since you're working on a future update regarding this, it shouldn't be a problem for long, right ? Meanwhile if theses extensions allow people to use VS code because they like it (as I do) and be comfortable with a GUI they use 8h+ a day, I think it's fair.

**Comment by Tyriar** [comment] 2016-12-14 05:03
@bentx it's just frustrating that we wasted a bunch of time investigating random crashes and bugs causes by these types of extensions so we added the message as a compromise, now the message is being disabled (for all other extensions too) meaning users of the extension may not even know that what it's doing.

**Comment by bentx** [comment] 2016-12-14 05:42
@Tyriar fair point. From my perspective the nagging message is annoying, but I agree on users not knowing what’s going on being a problem, as well as issues with screenshots without the [Unsupported] message. I updated the extension, the integrity check will stay enabled by default, and a setting entry has been added to disable it, for those who knows what they’re doing. There’s also a note on the README regarding user’s responsibility over this.

**Comment by Tyriar** [comment] 2016-12-14 06:18
@bentx thanks 😄 I can't wait to get more customization as well

**Comment by kaleo211** [comment] 2017-01-10 20:32
+1

**Comment by cor** [comment] 2017-01-18 11:43
Any updates on this?

**Comment by skillup** [comment] 2017-01-21 13:33
+1 Waiting for status bar color customization.

**Comment by equinusocio** [comment] 2017-01-24 16:11
Check https://github.com/Microsoft/vscode/issues/17608, we will have UI Api, and i will make material theme great again (lel)

**Comment by jchannon** [comment] 2017-02-03 10:21
So VSCode 1.9 is out, I don't think this issue is addressed with that, am I correct?

**Comment by equinusocio** [comment] 2017-02-03 10:24
@jchannon right.. :(

**Comment by GaryChangCN** [comment] 2017-02-05 08:10
.statusbar{background:#xxxxxx}  only this way to change status bar color ?

**Comment by Stromwerk** [comment] 2017-02-07 14:01
@GaryChangCN That is the only way to change it permanently. There is another method, although it only lasts until you reopen the editor. Using the Developer tools (Help-> Toggle Developer Tools) I manually change the color and remove the smiley. This lasts until I exit out completely out of VSCode, but that isn't a problem for me as normally I would open it at the start of a day and close it at the end.

**Comment by equinusocio** [comment] 2017-02-07 14:27
@Stromwerk Where do you put custom css?

**Comment by Stromwerk** [comment] 2017-02-07 15:21
@equinusocio I don't really put any custom css. I use the Developer Tools to change the values.

**Comment by skillup** [comment] 2017-02-07 15:25
@Stromwerk Thanks! This is so good now.

**Comment by equinusocio** [comment] 2017-02-07 15:38
@Stromwerk 
> .statusbar{background:#xxxxxx} only this way to change status bar color ?
> @GaryChangCN That is the only way to change it permanently....

**Comment by martinsuchan** [comment] 2017-02-14 10:59
Note it would be useful to have the top menubar theme-able as well, just like in the full Visual Studio:
![vscode](https://cloud.githubusercontent.com/assets/3041397/22926396/aa8ea206-f2ac-11e6-8cd9-650d4ed5e722.PNG)
![image](https://cloud.githubusercontent.com/assets/3041397/22926432/d6f54dae-f2ac-11e6-9cc5-73524b61eb7d.png)

**Comment by Tyriar** [comment] 2017-02-15 21:53
@martinsuchan I don't believe that's possible in https://github.com/electron/electron currently.

**Comment by equinusocio** [comment] 2017-02-15 22:06
@Tyriar Atom does.

**Comment by Tyriar** [comment] 2017-02-15 22:29
@equinusocio oh really? Not sure if we have anything tracking this but it should probably be a separate issue.

**Comment by rongsheng** [comment] 2017-02-15 22:51
+1

**Comment by martinsuchan** [comment] 2017-02-16 09:25
@Tyriar It's always possible to use custom HTML+CSS menu that will be indistinguishable from the native system menu,

**Comment by Tyriar** [comment] 2017-02-16 18:17
@martinsuchan indistinguishable is a strong word, you need to take into account:

- Look
- Accessibility
- System settings (font, menu scale, etc.)

Plus the menus may differ in minor ways between Windows versions.

**Comment by nomad-software** [comment] 2017-02-19 17:52
+1
Please, can we customise this? The bright blue against a dark colour scheme is extremely distracting!

**Comment by max-orhai** [comment] 2017-02-22 20:35
+1
I find bentx's vscode-custom-theme extension to be an acceptable workaround for now, but it would be really nice to see this as an official feature.

**Comment by xiaofengqinyu** [comment] 2017-03-01 08:55
you can change it with the following steps:
 1. ctrl+shift+p and input develop tool open develop tool
 2. choose element focus on status bar and find the css style
 3. edit the vscode css file(workbench.main.css) change the style
 4. save the file and reload your vscode

**Comment by chrisjimallen** [comment] 2017-03-01 08:58
Agree the blue is quite loud, but anyone who hates a :) needs to 'go home and rethink their life'

**Comment by steph643** [comment] 2017-03-07 10:16
+1

**Comment by rfgamaral** [comment] 2017-03-07 11:13
I'm using [CustomCSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) to customize VS Code UI similar to [So​Da​Reloaded](https://packagecontrol.io/packages/Theme%20-%20SoDaReloaded) Subliminal Text theme.

There's still a lot of things missing, a lot of things I want to do and customize (some I don't think are even possible) but for now, the status bar is one of those things that I had to "fix".

For anyone interested, check it out [here](https://gist.github.com/rfgamaral/2ab4ada056443250fa26b3b70644c78c).

**Comment by rogovdm** [comment] 2017-03-07 21:16
+1

**Comment by splurtcake** [comment] 2017-03-08 06:31
+1

**Comment by simoniz0r** [comment] 2017-03-12 10:51
I made a script based on https://github.com/Microsoft/vscode/issues/1884#issuecomment-230790242 because I got tired of editing the file to reset the color every time lol...
[Script Link](https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/vscodestatusbarcolor.sh)

**Comment by lednhatkhanh** [comment] 2017-03-12 12:26
+1 for this.

**Comment by stannynuytkens** [comment] 2017-03-14 07:52
`ctrl+k` + `ctrl+z` fixes the issue for me but it would indeed be nice to add customization to more UI parts.

**Comment by blueredcat** [comment] 2017-03-14 10:37
"We are working on enabling people to remove UI by right-clicking on it." I need to personally grease a 1000 poles at M$ to get this very small change done as the marketing department (who are 1 step away from full blown psychopathy) want it to remain.

**Comment by stannynuytkens** [comment] 2017-03-15 16:54
@blueredcat, why removing it? Styling or autohide or something will do, no?

**Comment by Brunorccrx** [comment] 2017-03-16 01:49
Like someone said already, just a gray/black option would be nice, this blue bar looks so odd on dark theme.

**Comment by cecilemuller** [comment] 2017-03-16 09:15
I think the cleanest way to handle it is exposing the setting to the theme, that way theme creators can provide color settings that fits the theme.

**Comment by equinusocio** [comment] 2017-03-16 09:58
Check https://github.com/Microsoft/vscode/issues/21923

**Comment by cyphunk** [comment] 2017-03-25 10:16
Installed from latest git source branch. They changed the color from blue to purple.

![2017-03-25-111158_1366x768_scrot](https://cloud.githubusercontent.com/assets/119662/24321412/62f7aca8-114c-11e7-8881-0d0259896f5e.png)

**Comment by jwigley** [comment] 2017-03-25 11:57
> Nothing seemed to work quickly. Now spent at least an hour or two on this horrible blue bar.

- Install [Custom Theme for Visual Studio](https://marketplace.visualstudio.com/items?itemName=bentx.vscode-custom-theme)
- Set `theme.statusbar.background.color` in your preferences.
- Done.

**Comment by bongraster** [comment] 2017-03-27 10:50
+1 for statusbar color & hiding this weird smiley

**Comment by kutsan** [comment] 2017-03-27 11:06
Well, it's actually pretty creepy smiley if you did look more than 5 seconds. Like, it's been watching you while you are writing code and giving us its evil smile. So, must be die.

**Comment by joe-watkins** [comment] 2017-03-27 15:27
Building upon @jwigley 's great recommendation, here's a detailed how-to:

1. Open Extensions: Mac: `Shift+command+X`, Windows: `Ctrl+Shift+X`, Linux: `Ctrl+Shift+X`
2. Search for `Custom theme for Visual Studio Code` and install that extension
3. Visit preferences: Mac: `Command+`, Windows/Linux: `File > Preferences > Settings`
4. In the right pane add `"theme.statusbar.background.color": "#161616"` (make hex your favorite color) e.g.

``` json
{
    "editor.fontSize": 16,
    "editor.tabSize": 2,
    "workbench.welcome.enabled": false,
    "theme.statusbar.background.color": "#161616"
}
```

5. Show All Commands: Mac: `Shift+command+P`, Windows: `Ctrl+Shift+P`, Linux: `Ctrl+Shift+P`
6. Search for `Theme` and activate `Custom theme: Apply`

**Comment by stannynuytkens** [comment] 2017-03-28 20:45
@joe-watkins `Running the contributed command:'theme.apply' failed.`

**Comment by joe-watkins** [comment] 2017-03-29 00:11
@stannynuytkens hmmm I dunno? You running latest version?

**Comment by bentx** [comment] 2017-03-29 02:06
@stannynuytkens make sure you're running as administrator on windows or have correct privileges on osx/linux, if still not working please open an issue I'll look into it

**Comment by bentx** [comment] 2017-03-29 03:11
It looks like this ticket could be closed soon, by looking at the latest sources, that's good news :)

```js
export const STATUS_BAR_BACKGROUND = registerColor('statusBarBackground', {
	dark: '#007ACC',
	light: '#007ACC',
	hc: null
}, nls.localize('statusBarBackground', "Standard status bar background color. The status bar is shown in the bottom of the window"));
```

That look like the theming capability we've been waiting for, go vscode team !

**Comment by Tyriar** [comment] 2017-03-29 03:23
> That look like the theming capability we've been waiting for, go vscode team !

Yes the start of workbench theming support will be part of the March update (1.11). You will be able to do this very soon, see https://github.com/Microsoft/vscode/issues/3112#issuecomment-289483970

**Comment by equinusocio** [comment] 2017-03-29 07:20
Where we will find the documentation about that?

**Comment by Tyriar** [comment] 2017-03-29 18:49
@equinusocio there will probably be some documentation in the release notes, most will likely be in 1.12.

**Comment by nojvek** [comment] 2017-03-30 23:43
I find the whole argument of `blue` visual studio absurd.  The blue would matter if there there was a vscode/visual studio logo , there is none in the status bar. Its not like users will get confused about what IDE they are using because the blue is changed to a subtle grey like what @bgashler1  has posted.

Simply put, the blue is so strong that it pulls attention away from code users are writing. This is literally a user experience issue. Please please please treat it as such.

**Comment by bpasero** [comment] 2017-04-01 19:01
With our work on workbench theming ([release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_11.md#workbench-theming-part-1)) you can now customise the color of the statusbar background. The relevant keys are:
* `statusBarBackground`: blue by default
* `statusBarNoFolderBackground`: purple by default
* `statusBarDebuggingBackground`: orange by default

Here is an example of how to change this via settings:

```json
"workbench.experimental.colorCustomizations": {
    "statusBarBackground": "#00EECC",
    "statusBarNoFolderBackground": "#CCEE00",
    "statusBarDebuggingBackground": "#CCFFFF"
}
```

It is likely that the name of the setting will change and we also think the color names are not final yet. 

As for being able to hide the smiley button in the status bar, I suggest to continue via https://github.com/Microsoft/vscode/issues/7893

Note: there are still a lot of colors missing from workbench theming support (continues via https://github.com/Microsoft/vscode/issues/3112) and there is still some issues with coloring icons in the status bar (continues via https://github.com/Microsoft/vscode/issues/23526).

**Closed by bpasero** 2017-04-01 19:01 UTC
Labels: feature-request

**Comment by HoNooD** [comment] 2017-04-03 14:09
I like the original blue statusbar, however, the lastest relase uses purple instead. I hate purple.

**Comment by Tyriar** [comment] 2017-04-03 14:11
@HoNooD the status bar has always been purple when no folder is opened.

**Comment by simoniz0r** [comment] 2017-04-05 23:49
Woo!!  This update is really nice!  Thank you guys so much; the ability to theme the entire workbench is great!

**Comment by stannynuytkens** [comment] 2017-04-06 18:37
Oh the [irony](http://imgur.com/SDZA1kB), lol! _(hint: titlebar color)_
Thanks guys, looking forward to theme the h*ll out of vscode!

**Comment by bmewburn** [comment] 2017-04-06 20:16
Everything is purple for me now. Quiet Light theme, status bar (with open folder), 1.11.1 on Debian Stretch :(
![screenshot from 2017-04-07 06-13-51](https://cloud.githubusercontent.com/assets/5885195/24773754/b9ea1872-1b59-11e7-91a6-e336d3874506.png)

**Comment by simoniz0r** [comment] 2017-04-06 22:10
That would be the theme.  Define the color of your status bar in the settings with the new experimental workbench setting.
```
"workbench.experimental.colorCustomizations": {
        "statusBarBackground" : "#1A1A1A",
        "statusBarNoFolderBackground" : "#0A0A0D",
        "statusBarDebuggingBackground": "#511f1f"
    }
```

**Comment by ClericPy** [comment] 2017-04-07 08:01
as sysrpl said, type like below and wait for new version
 
> Help -> Toggle Developer Tools -> Console
```js
document.getElementById("workbench.parts.statusbar").style["background-color"] = "#434343"
```

**Comment by stefangabos** [comment] 2017-04-21 09:36
lovely! now how to change the color of the white icons? :)

**Comment by Tyriar** [comment] 2017-04-21 16:06
@stefangabos do the icons not change with `statusBarForeground`?

![image](https://cloud.githubusercontent.com/assets/2193314/25286206/cfa995ac-2671-11e7-8672-1a60a28913ce.png)

**Comment by stefangabos** [comment] 2017-04-21 16:31
it seems to have no effect here
![nm9nnca](https://cloud.githubusercontent.com/assets/741165/25287163/05ffd10a-26c9-11e7-9d06-ce68e42aacf6.png)

**Comment by Tyriar** [comment] 2017-04-21 16:34
@stefangabos if you're on Insiders, I'd file a bug. Otherwise testing in [Insiders](https://code.visualstudio.com/insiders) might be a good idea.

**Comment by xconverge** [comment] 2017-04-24 17:01
@bpasero I know that this is a stretch but are there any plans to expose any of this through the extension API? Currently I am modifying settings on the fly and it seems like a bad hack...

Sorry for using an experimental feature right away :/ there was high demand..

https://github.com/VSCodeVim/Vim/issues/1056

![image](https://cloud.githubusercontent.com/assets/4219348/25161172/571ebf4e-246f-11e7-8bf3-26b7df2a4037.gif)

**Comment by bpasero** [comment] 2017-04-25 04:50
Currently no plans to expose this as API other than changing settings directly.

**Comment by yuhaozhang** [comment] 2017-05-05 21:28
For those of you who has tried the above solution but found it not working, this has not been changed to:

```
"workbench.colorCustomizations": {
        "statusBar.background" : "#1A1A1A",
        "statusBar.noFolderBackground" : "#0A0A0D",
        "statusBar.debuggingBackground": "#511f1f"
}
```

**Comment by stefangabos** [comment] 2017-05-06 05:06
This is working as expected in the new release. It can be closed as far as
I'm concerned. Thanks!

**Comment by pravdomil** [comment] 2017-05-25 09:54
@bgashler1  it's not consistent it's distracting, you Microsoft

**Comment by rogaha** [comment] 2017-06-06 14:46
👍 thanks for the tip @yuhaozhang! It worked like a charm!

**Comment by rogaha** [comment] 2017-06-06 14:53
I ended up with: 

```
"workbench.colorCustomizations": 
    {
        "statusBar.background" : "#303030",
        "statusBar.noFolderBackground" : "#222225",
        "statusBar.debuggingBackground": "#511f1f"
    }
```

### Preview
<img width="1476" alt="screen shot 2017-06-06 at 7 51 18 am" src="https://cloud.githubusercontent.com/assets/4483394/26835444/37b8762e-4a8d-11e7-9128-b71d803160ae.png">

**Comment by DreadKnight** [comment] 2017-06-17 03:59
@rogaha Awesome, that did it for me, thanks!
First time I'm using Visual Studio and that blue bar was distracting me big time, almost ditched this editor and went for the competition. I don't care about the whole family of Visual Studio editors if they want to stay flawed, but I must say awful consistency by design is bad.

**Comment by Haroenv** [comment] 2017-07-06 08:11
@bpasero could you close and lock this thread to make it clear that a solution is possible now with `workbench.colorCustomizations`? Thanks!

**Comment by gyurobenjamin** [comment] 2017-09-01 09:07
```json
"workbench.colorCustomizations": {
  "statusBar.background": "#2f2f2f"
},
```

**Comment by hbendalibraham** [comment] 2017-09-15 20:09
+1

**Comment by Tyriar** [comment] 2017-09-28 15:54
Themes can now set the status bar background. You can also override the colors by adding the following to your settings.json file:

```
"workbench.colorCustomizations": 
{
  "statusBar.background" : "#303030",
  "statusBar.noFolderBackground" : "#222225",
  "statusBar.debuggingBackground": "#511f1f"
}
```
