### ISSUE TITLE
Allow to open multiple project folders in the same window

### ISSUE THREAD

**Issue by induratized** [Microsoft/vscode#13066] opened 2016-09-30 09:12 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. Open a project folder in the editor
2. Now drag and drop another project folder in the same window
3. Observe that the previously open project is replaced with the new dragged and dropped project folder

Expectation: 
1. Just like editors like Sublime Brackets Atom, multiple project folders need to hooked to the tree in the left side bar

**Comment by bpasero** [comment] 2016-09-30 12:42
@induratized please invest the time to search for duplicates.

**Comment by stefcameron** [comment] 2016-11-05 19:22
This would be awesome... I have many projects that involve multiple folders and opening a parent folder ends-up including way more children folders than I want (and that Code should searching, indexing, etc.).

In order to implement this feature, I believe it would require a change to the way Code manages workspace settings. I think we'd need location-independent workspace settings (i.e. a another file type, outside of the current ./.vscode folder...), for example: <ws-name>.vscode file (located anywhere in the file system), loads Code when double-clicked, uses the JSON format (easily editable), specifies multi-folder paths, search exclusions, etc. Eventually, you could even use this file to enable/disable specific extensions and all sorts of other interesting things related to a "project" concept.

**Comment by nucleardreamer** [comment] 2016-11-11 18:31
Duplicate of #396

**Closed** 2016-11-14 17:41 UTC
Labels: feature-request, workbench
