### ISSUE TITLE
Quick Find Symbol/File showing unrelated symbols from VSCode typescript extension

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#5954] opened 2016-04-28 15:34 UTC
- VSCode Version: 1.1.0-insider
- OS Version: Win 10

Steps to Reproduce:

1. open the quick find panel (ctrl+)
2. type css

In addition to valid files/symbols, it shows symbols from `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\server\typescript\lib\lib.d.ts`

![codesymbol](https://cloud.githubusercontent.com/assets/199648/14891490/2b8c0dc0-0d67-11e6-9962-4e49c8e92f61.png)

I never opened this file and it's not part of my workspace.

**Comment by warpdesign** [comment] 2016-04-28 15:38
I just noticed that it also shows results from editor\node_modules\css-select\index.js although node_modules folder should be excluded.

**Comment by bpasero** [comment] 2016-04-29 06:44
We might want to have a setting to exclude *.d.ts files from this list.

**Comment by dbaeumer** [comment] 2016-05-09 12:38
@warpdesign do you exclude the node_modules folder in the tsconfig.json?

If we want to have such a setting then it needs to go into the tsconfig.json. The symbols shown in the list come from the tsserver and IMO showing the lib.d.ts is correct since these symbols are globally available.

**Comment by vincent-ly** [comment] 2016-05-17 06:31
@dbaeumer I thought node_modules are already excluded by the search.exclude portion of the user settings? I'm having the same issues where symbols from excluded folders appear on the search.

**Comment by dbaeumer** [comment] 2016-05-17 07:54
@vincent-ly search.exclude excludes them from full text search. If you want to exclude them from TS smartness you need to add a exclude property to the tsconfig.json as well.

**Comment by warpdesign** [comment] 2016-06-28 09:29
I'm having the same problem again (I had to reinstall vscode): @bpasero is there a setting to exclude *.d.ts files from this list ?

If not what should I add into tsconfig.json to exclude these files ?

Thank you

**Comment by bpasero** [comment] 2016-06-28 09:32
I am not sure why symbols from d.ts files would show up, @dbaeumer would know.

**Comment by dbaeumer** [comment] 2016-06-29 09:09
This happens when you once navigated to the lib.d.ts file. It looks like the tsserver then doesn't filter it correctly anymore. Since the file is open in the editor we sent an open event to the tsserver. Need to understand what we have to do in this case.

**Comment by dbaeumer** [comment] 2016-08-29 10:20
I can't reproduce this with the upcoming 1.5 bits anymore (even with an open lib.d.ts). I will close the issue. Please ping if you still see this in 1.5
![capture](https://cloud.githubusercontent.com/assets/1931590/18048519/eb1771f8-6de2-11e6-93e4-7d71d9457861.png)

**Closed by dbaeumer** 2016-08-29 10:20 UTC
Labels: bug, typescript

**Comment by bpasero** [comment] 2016-08-29 13:40
@dbaeumer this is because some changes made the symbols disappear in quick open due to timing. I now provide a setting so that you can force the symbols from showing up (see https://github.com/Microsoft/vscode/issues/4512). 

No matter what, please verify using Ctrl+T (open symbol) to be sure you hit the language service properly.

**Comment by dbaeumer** [comment] 2016-08-30 10:55
@bpasero  IMO showing symbols in Ctrl+T from lib.d.ts is wanted. They are valid global symbols you might want to navigate to.

**Comment by dbaeumer** [comment] 2016-08-30 10:59
I enabled the new setting "search.quickOpen.includeSymbols" and it does show Symbols from the lib.d.ts. If the setting is enabled I argue that it is OK to show them.

**Comment by dbaeumer** [comment] 2016-08-30 11:01
The questionable part is if you do pure JS development. If we think that these symbols shouldn't show up then we need to make this happen in the tsserver. Currently the types in the project show up even the onces from typings.

@bpasero any take?

**Comment by bpasero** [comment] 2016-08-30 12:33
@dbaeumer I do not think I would expect types from showing up if I am working against a JS project where the concept of types does not exist.

**Comment by dbaeumer** [comment] 2016-08-30 12:46
OK. Opened https://github.com/Microsoft/TypeScript/issues/10606
