### ISSUE TITLE
VS Code keeps crashing after update

### ISSUE THREAD

**Issue by VErwin** [Microsoft/vscode#63086] opened 2018-11-14 04:51 UTC
Issue Type: <b>Bug</b>

VS Code never crashed before the Oct. 2018 update (which was pushed to me today).  It has crased 3 times in the last hour since the update.  I am not doing anything particularily demanding.  I am updating a .js file, viewing it in my browser, then modifying, saving, viewing in browser again.  Application hangs after a few saves and crashes.  I lose my most recent edits if I haven't saved them before the application crashed.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:46:32.773Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz (4 x 2666)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.25GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by VErwin** [comment] 2018-11-14 05:05
this is NOT a dupe of (#62628).  

This occurs if the HTML file is still loading due to a JS loop (that wasn't closed properly).  Before the update, if this happened, I would close the HTML file in Windows Edge and the infinite loop did not effect VS Code.  Now it is effecting VS Code and causes the application to crash if I do not close the HTML file.

**Comment by andrewcourtice** [comment] 2018-11-14 06:20
I can confirm this is also happening for me since the latest update.

![image](https://user-images.githubusercontent.com/11718453/48463451-c3bb4a00-e827-11e8-8983-6bc44a46d10d.png)

![image](https://user-images.githubusercontent.com/11718453/48463806-0d586480-e829-11e8-9ba6-e03a3c4c344b.png)

**Comment by ZSH-HSZ** [comment] 2018-11-14 07:33
same problem， macOS 10.14.0

**Comment by QuentinMaypic** [comment] 2018-11-14 09:40
Same problem Ubuntu 18.04

**Comment by umnovI** [comment] 2018-11-14 09:59
Same problem Ubuntu 16.04

**Comment by rilut** [comment] 2018-11-14 10:59
same issue with VSCode 1.29.0 on macOS Mojave 10.14

**Comment by joseph1125** [comment] 2018-11-14 15:13
duplicate of #62970

**Comment by roblourens** [comment] 2018-11-14 18:23
Does clearing notifications help?

**Comment by VErwin** [comment] 2018-11-14 20:47
I just opened VS Code and cleared notifications.  I will start working and see!

**Comment by VErwin** [comment] 2018-11-14 21:48
So far that appears to do the trick.  No crashes (so far).  PS - tell the team the "icon lady from 2007 - 2012" says 'hi'.

**Comment by roblourens** [comment] 2018-11-14 22:20
We have pushed a possible fix to Insiders. Would appreciate if everyone checks out our insiders build to verify that you don't see this issue there: https://code.visualstudio.com/insiders/

**Closed by roblourens** 2018-11-14 22:20 UTC
Labels: needs more info, new release
