### ISSUE TITLE
Can not open file contain backslash in filename

### ISSUE THREAD

**Issue by stephentt-me** [Microsoft/vscode#58447] opened 2018-09-11 17:45 UTC
- VSCode Version: 1.27.1
- OS Version: Linux `4.18.6-arch1-1-ARCH`

Steps to Reproduce:

1. Create a file name with a backslash `touch index.html\\`. It's should create a file named `index.html\`
2. Using VSCode open the folder contain that file. (I am using `code .`)
3. In the sidebar click that file.
4. Message error appear: `Unable to open 'index.html': File not found (file:///.../index.html/).` File can not opened.

In addition, if you create file named `touch hello\\world`. The sidebar only show a file named `world`. Can not open that file too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-09-12 07:08
Duplicate of https://github.com/Microsoft/vscode/issues/55084

**Closed by bpasero** 2018-09-12 07:08 UTC
