### ISSUE TITLE
Integrated terminal destroys part of the input on return

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#201115] opened 2023-12-18 11:38 UTC
Type: <b>Bug</b>

When returning to open terminal and trying to access command history, about 100% of the time the first "arrow up" key press will be partly eaten by the terminal. See picture.

![image](https://github.com/microsoft/vscode/assets/6532485/95a6c1da-adc8-4e59-aa7f-8f279b6d58b5)

Extra info: Shell is a Cygwin bash.
Legacy console is not enabled.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.19GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment] 2023-12-18 16:59
Could you pls run the command `Developer: Set Log Level` -> `Terminal` -> `trace`, use up arrow, and provide the logs?

**Comment by meganrogge** [comment] 2023-12-18 18:05
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-12-18 18:05 UTC
Labels: info-needed

**Comment by AnrDaemon** [comment] 2023-12-31 12:03
I disagree with your conclusion. This looks like an issue is not in the terminal itself, but in how you handle the closing/reopening of the terminal view.
