### ISSUE TITLE
terminal decorations are misaligned when in side panel

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143778] opened 2022-02-23 18:06 UTC
Testing #143433

1. Drag terminal into side panel
2. :bug: decorations render on top of output text, nothing happens when you click on the decorations

**Comment by meganrogge** [comment] 2022-02-23 19:55
same for dragging and dropping into the editor area

**Comment by meganrogge** [comment] 2022-02-23 23:10
related #143137

**Comment by meganrogge** [comment] 2022-02-24 16:49
Their alignment is wrong, but the context menus work for me.
![Recording 2022-02-24 at 10 49 26](https://user-images.githubusercontent.com/29464607/155569568-ee6442be-72e2-414b-9d1c-75a32c2b263d.gif)

**Comment by meganrogge** [comment] 2022-02-24 16:53
original issue was a duplicate of https://github.com/microsoft/vscode/issues/143703

Renaming to address the alignment issue

**Closed** 2022-02-24 19:24 UTC
Labels: bug, terminal-command-decoration

**Comment by joyceerhl** [comment] 2022-02-25 18:54
The decorations might benefit from a little padding when in the side panel:
 
![image](https://user-images.githubusercontent.com/30305945/155771630-addbe2be-a4c0-4863-a8dd-bd613b2239a9.png)

Versus in the bottom panel:

![image](https://user-images.githubusercontent.com/30305945/155771718-b21f4d19-833b-4303-9d99-f383a5c9e9b2.png)

**Comment by meganrogge** [comment] 2022-02-25 19:04
I agree that it looks quite cramped there.

You'll also see it looking similarly cramped for split terminals (besides the first one). That's because we have `10px` of left padding for those vs `20px` for the first split. I don't think we plan to change this. Thoughts @Tyriar ? 

One option would be to decrease the size of the icon so that there's more room.

**Comment by Tyriar** [comment] 2022-02-25 22:38
We could add a dedicated 20px column there when shell integration is on, regardless of split status? Similar to how disabling folding will hide the folding column in the editor. Shall we capture this improvement in another issue?
