### ISSUE TITLE
VS Code Doesn't show credentials prompt on Ubuntu 21.04/21.10

### ISSUE THREAD

**Issue by caiocampos** [microsoft/vscode#137318] opened 2021-11-16 17:27 UTC
Issue Type: <b>Bug</b>

The git integration is no longer prompting for the password and it always gives an authentication error when I try to perform actions on git, in the integrated terminal the error also occurs, but in the system bash it works correctly 

![Captura de tela de 2021-11-16 14-24-38](https://user-images.githubusercontent.com/20524962/142034815-28b8676d-71c5-4bc5-afe6-8762247d8424.png)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.13.0-21-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|7.63GB (0.14GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f50e9d05-9a65-47ce-b744-ea13ce9eb288|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.45.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
go|gol|0.29.0
vscode-language-pack-pt-BR|MS-|1.62.3
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|1.0.0
rust|rus|0.7.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-16 21:54
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 21:56 UTC
Labels: *duplicate
