### ISSUE TITLE
i := 1 - Syntax error

### ISSUE THREAD

**Issue by apovetkin** [Microsoft/vscode#42354] opened 2018-01-29 19:14 UTC
- VSCode Version: 1.19.2
- OS Version: 10.0.14393

Steps to Reproduce:

Watch the video with the issue
https://youtu.be/Iew17mpwSCw

1. In VS Code use i := 1

Does this issue occur when all extensions are disabled?: Yes/No

I disabled the GO extension and no problems after that

**Comment by alexandrudima** [comment] 2018-01-30 10:34
Duplicate of https://github.com/Microsoft/vscode-go/issues/1487

**Closed by alexandrudima** 2018-01-30 10:34 UTC
Labels: extensions

**Comment by apovetkin** [comment] 2018-01-30 17:38
Hi,

You closed both issues because they are duplicates, but the issue is not fixed.

Thanks,
Alex
________________________________

**Comment by alexandrudima** [comment] 2018-01-31 13:00
@apovetkin I closed this issue. The one you created in the `vscode-go` repository remains opened -- https://github.com/Microsoft/vscode-go/issues/1487
