### ISSUE TITLE
[html] autocomplete should produce more context-specific results

### ISSUE THREAD

**Issue by smalllong** [Microsoft/vscode#19114] opened 2017-01-24 07:57 UTC
- VSCode Version: 1.8.1

Steps to Reproduce:

When I type '<' in a &lt;html&gt;&lt;/html&gt;, the full version visual studio would give me an assist of &lt;head&gt; and &lt;body&gt;. However, in vscode, all the tags(including inappropriate tags) will appear, which is not concise.

**Comment by aeschli** [comment] 2017-06-26 06:31
duplicate of #375

**Closed by aeschli** 2017-06-26 06:31 UTC
Labels: feature-request, html
