### ISSUE TITLE
Windows Start-up

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33859] opened 2017-09-05 20:26 UTC
[4496_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1278792/4496_renderer.cpuprofile.txt)
[4496_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1278793/4496_main.cpuprofile.txt)

- VSCode Version: <code>Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)</code>
- Memory (System): <code>15.93GB (7.17GB free)</code>
- Memory (Process): <code>172.36MB working set (172.36MB peak, 141.15MB private, 42.44MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|53|
|main|app.isReady => window.loadUrl()|325|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|611|
|renderer|require(workbench.main.js)|1416|
|renderer|create extension host => extensions onReady()|2051|
|renderer|restore viewlet|1235|
|renderer|restore editor view state|2876|
|renderer|overall workbench load|3210|
|main + renderer|start => extensions ready|4708|
|main + renderer|start => workbench ready|5784|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`4496_main.cpuprofile.txt`
-`4496_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-09-06 15:29
I'd suspect death by 1000 paper cuts, there are some interesting bit here

**Main Process**

<img width="421" alt="screen shot 2017-09-06 at 17 14 36" src="https://user-images.githubusercontent.com/1794099/30119713-ed15b504-9326-11e7-84a8-1b03ea14560e.png">

You pay ~50ms for spawning a process for getting the mac address/machine id. We only need that for the marketplace and @joaomoreno was nice to fix it recently. @seanmcbreen You should really be using insiders!


**Renderer Process**

No single big thing that is slow/bad/etc. I do a couple of (small) issues that we could resolve

*Slow Collator*

Very early on we spend around 100ms for setting up a collator. That is slow and might have gotten slower with the latest Electron update, at l have never seen this before. @bpasero to implement something smarter as I believe we only use this for comparing (explorer) files names. We could be lazy and only load/init this if we encounter a filename for compare that doesn't use ASCII. 

<img width="721" alt="screen shot 2017-09-06 at 16 21 28" src="https://user-images.githubusercontent.com/1794099/30119595-8a773314-9326-11e7-92ce-d23b295a260c.png">


*Slow process.bind*

This is node/atom way to load a C++ library. No clue why it so slow in your run...

<img width="300" alt="screen shot 2017-09-06 at 16 33 02" src="https://user-images.githubusercontent.com/1794099/30119752-08d86cdc-9327-11e7-9948-ab74316635ee.png">


*InnerArrayForEach*

There is a lot of forEach going on at startup, needs deeper understanding. The profile might be misleading, things look more fine grained when debugging out of source. That might just be the place where we construct the (empty) workbench. 

<img width="976" alt="screen shot 2017-09-06 at 16 30 24" src="https://user-images.githubusercontent.com/1794099/30119770-163187d8-9327-11e7-8cbb-68bb0fef5833.png">

**Comment by bpasero** [comment] 2017-09-06 15:56
@seanmcbreen does this reproduce if you run with a different user data directory? If you run "`code --user-data-dir=<some empty dir>`" it would bypass any previous accumulated data from all the sessions before. One theory we have is that maybe the contents of the data directory turned large enough so that the startup gets slow.

**Comment by bpasero** [comment] 2017-09-06 16:09
We use the `Collator` not only to sort non-ASCII file names but also to sort more naturally when numbers are part of the name (see [`numeric`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) option). 

We use this today in quick open, explorer and SCM viewlet. I think we can probably ditch it though with our own implementation, even though it might not be 100% correct if it turns out to be a performance issue.

**Comment by bpasero** [comment] 2017-09-06 16:16
On my Windows box, the Collator does not even show up in the trace. I wonder what configuration can cause this to be slow (e.g. depending on the languages installed on Windows maybe?)

**Comment by seanmcbreen** [comment] 2017-09-07 23:53
Here you go...  Started with
`code --user-data-dir c:\src\datadir --prof-startup`
[9034_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1286387/9034_renderer.cpuprofile.txt)
[9034_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1286386/9034_main.cpuprofile.txt)



- VSCode Version: <code>Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)</code>
- Memory (System): <code>15.93GB (8.50GB free)</code>
- Memory (Process): <code>161.02MB working set (228.16MB peak, 137.07MB private, 45.15MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|3947|
|main|app.isReady => window.loadUrl()|332|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|520|
|renderer|require(workbench.main.js)|1423|
|renderer|create extension host => extensions onReady()|1613|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|1289|
|main + renderer|start => extensions ready|7926|
|main + renderer|start => workbench ready|7519|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`9034_main.cpuprofile.txt`
-`9034_renderer.cpuprofile.txt`

**Comment by seanmcbreen** [comment] 2017-09-07 23:54
Since it's not listed I'm using Code 32-bit i.e. ia32

**Comment by jrieken** [comment] 2017-09-08 08:15
@seanmcbreen While it is interesting (and frustrating) to see electron/node taking 4secs to signal readiness to us, you should have taken that trace also with the 1.15.1 (as before). It makes it hard to compare otherwise

**Comment by jrieken** [comment] 2017-09-08 12:59
Apart form this being a profile on a different version/product, the render portion doesn't show anything the render portion of the former profile does, the same is true for the main portion...

**Comment by seanmcbreen** [comment] 2017-09-08 16:22
Doh yes I upgraded with the release yesterday.  What is the best bet - would you like me to downgrade and try another profile?  The bottom line is in the most recent profile I had a staggeringly long start-up 7.5s (seams like Electron) is their nothing we can do there?

**Comment by bpasero** [comment] 2017-09-08 16:26
@seanmcbreen do you have large contents in any of these folders?

![image](https://user-images.githubusercontent.com/900690/30221337-2ac23dbc-94c3-11e7-894d-07701d35e42b.png)

**Comment by seanmcbreen** [comment] 2017-09-08 17:22
I'll check -  I don;t have that PC with me today so will do so on Monday.

**Comment by seanmcbreen** [comment] 2017-09-11 22:33
Local storage = 263KB
Cache = 85.6Mb
CachedData = 1.16Gb
GPU Cache = 4.56Gb
User = 144Mb

Everything else is 250 bytes..

**Comment by seanmcbreen** [comment] 2017-09-11 22:37
While I'm here a prof-startup on stable

- VSCode Version: <code>Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)</code>
- Memory (System): <code>15.93GB (8.79GB free)</code>
- Memory (Process): <code>161.36MB working set (161.71MB peak, 133.41MB private, 41.94MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|3909|
|main|app.isReady => window.loadUrl()|348|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|578|
|renderer|require(workbench.main.js)|762|
|renderer|create extension host => extensions onReady()|1770|
|renderer|restore viewlet|1434|
|renderer|restore editor view state|1745|
|renderer|overall workbench load|2017|
|main + renderer|start => extensions ready|7427|
|main + renderer|start => workbench ready|7651|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`1465_main.cpuprofile.txt`
[1465_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1294258/1465_renderer.cpuprofile.txt)
[1465_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1294259/1465_main.cpuprofile.txt)


-`1465_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-09-12 07:08
Madness... This looks very much like https://github.com/electron/electron/issues/1487 (our tracking item https://github.com/Microsoft/vscode/issues/22087). What AV software are you using on that machine?

**Comment by seanmcbreen** [comment] 2017-09-13 07:45
I'm just using the stock Windows 10 install - so I guess Defender - that's true on all my PCs.

**Comment by seanmcbreen** [comment] 2017-09-13 07:47
Here is another good one I just grabbed on my home PC...  I captured this with Insiders as I did a stable start that was ultra slow so thought I would try my luck - I got lucky.

- VSCode Version: <code>Code - Insiders 1.17.0-insider (ac167c41bababe6c47180012723fa2bc52610ff4, 2017-09-07T05:24:04.020Z)</code>
- OS Version: <code>Windows_NT x64 10.0.15063</code>
- CPUs: <code>AMD Phenom(tm) II X6 1035T Processor (6 x 2594)</code>
- Memory (System): <code>12.00GB (5.79GB free)</code>
- Memory (Process): <code>233.52MB working set (233.52MB peak, 200.10MB private, 61.22MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|7007|
|main|app.isReady => window.loadUrl()|600|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1095|
|renderer|require(workbench.main.js)|2692|
|renderer|create extension host => extensions onReady()|1702|
|renderer|restore viewlet|1103|
|renderer|restore editor view state|1|
|renderer|overall workbench load|1437|
|main + renderer|start => extensions ready|13203|
|main + renderer|start => workbench ready|12892|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`dc40_main.cpuprofile.txt`
-`dc40_renderer.cpuprofile.txt`
[dc40_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1298642/dc40_renderer.cpuprofile.txt)
[dc40_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1298643/dc40_main.cpuprofile.txt)

**Comment by bpasero** [comment] 2017-09-13 16:00
@seanmcbreen @jrieken fyi with a bare Electron app I can reproduce that app.on("ready") takes in the order of 4s on my Win10 image, compared to 20ms when trying with 1.6.6. Interestingly 1.8.0 is also much faster. I filed https://github.com/electron/electron/issues/10506

**Comment by jrieken** [comment] 2017-11-13 11:35
closing this as a dupe of https://github.com/Microsoft/vscode/issues/22087

**Closed by jrieken** 2017-11-13 11:35 UTC
Labels: perf-profile
