### ISSUE TITLE
[Windows 10]Terminal:Chinese characters were overlapped

### ISSUE THREAD

**Issue by WalterZou** [Microsoft/vscode#8165] opened 2016-06-27 02:07 UTC
- VSCode Version:1.2.1
- OS Version:Windows 10 (Language:Chinese Simplified)

Steps to Reproduce:

1. `Ctrl`+`~`,open terminal
2. Chinese characters were overlapped like this:
![qq 20160627095958](https://cloud.githubusercontent.com/assets/3727208/16366776/df01409e-3c4e-11e6-957e-ec9ab9f6896b.png)

**Comment by fantacytyx** [comment] 2016-06-27 02:19
提问题前做好先搜索下要提的问题是否有人反馈过了。
你个问题已经有很多人反馈。并且已经修复了。

**Comment by Tyriar** [comment] 2016-06-27 10:14
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-27 10:14 UTC
Labels: integrated-terminal
