### ISSUE TITLE
Remote Dev using SSH not working on Rasp Pi Zero W

### ISSUE THREAD

**Issue by BitKnitting** [microsoft/vscode#88296] opened 2020-01-08 17:10 UTC
Issue Type: <b>Bug</b>

Have been successful using remote dev using SSH on Rasp Pi 3 B+.

Not successful on Rasp Pi ZeroW.

OS is the same (Raspbian Buster Lite 4.19 w/ updates).

Could not establish connection to "192.168.86.24". The remote host's architecture is not supported.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 17.7.0
Fetching remote diagnostics for 'SSH' failed: The remote host's architecture is not supported
Fetching remote diagnostics for 'SSH' failed: The remote host's architecture is not supported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The remote host's architecture is not supported

Fetching remote diagnostics for 'SSH' failed: The remote host's architecture is not supported
</details>Extensions: none

**Comment by IllusionMH** [comment] 2020-01-08 17:17
/causedByExtension

Looks like duplicate of https://github.com/microsoft/vscode-remote-release/issues/669
In any case issue should be reported in https://github.com/microsoft/vscode-remote-release/issues repo

**Closed** 2020-01-08 17:18 UTC
Labels: *caused-by-extension
