### ISSUE TITLE
wrong color for variable names

### ISSUE THREAD

**Issue by davidxujiayang** [microsoft/vscode#98882] opened 2020-05-30 23:46 UTC
- VSCode Version: 1.46.0-insider
- OS Version: Linux x64 5.4.0-31-generic

Steps to Reproduce:

1. open a python file and type "forcing = 0.5"

Does this issue occur when all extensions are disabled?: Yes

I notice that if you have reserved words included in variable names it will be colored incorrectly. For example variable named "forcing" will be colored as in the picture.
![image](https://user-images.githubusercontent.com/24285886/83341148-016ab100-a2ae-11ea-908a-dae0982adc5d.png)

**Comment by serenedu** [comment] 2020-05-31 02:14
Seems like a theme issue, mine works fine

**Comment by yume-chan** [comment] 2020-05-31 04:34
Please use the issue template or the `Help: Report Issue` command in Code itself to file new issues. Which includes essential information for resolving your bug.

Also, which language are you programming in?

**Comment by davidxujiayang** [comment] 2020-05-31 07:32
@yume-chan Thanks for replying. Sorry for carelessly removing the template, I followed it and edited the issue. I'm programming in python

**Comment by davidxujiayang** [comment] 2020-05-31 07:34
@serenedu Thanks for the reply. I disabled all extensions but it still behaves like this in python. In "color theme" in the options, I'm using Dark+. I don't remember if I configured the theme myself, is there a way to check that?

**Comment by alexr00** [comment] 2020-06-02 12:38
I'm also not able to reproduce the issue:
![image](https://user-images.githubusercontent.com/38270282/83520845-a4097680-a4de-11ea-9253-23ce7e036c00.png)
This is using the Dark+ theme. If there are more steps to get a repro, please do add them and I'll look again.

**Closed** 2020-06-02 12:39 UTC
Labels: *not-reproducible
