### ISSUE TITLE
Auto import quotes sign should be configured by tslint.json for Typescript

### ISSUE THREAD

**Issue by sergous** [Microsoft/vscode#23559] opened 2017-03-29 12:01 UTC
- VSCode Version: 1.10.2
- OS Version: windows 10

Steps to Reproduce:

1. add to tslint.json
```
{"rules": {
 "quotemark": [true, "single"],
}}
```
2. Add to a.ts 
`export const a = 1;`
3. Add to b.ts
a
3. Click on auto suggestion, then import
4. See imported string with tslint warning about double quotes

Expect:
import with single quotes with no warning

**Comment by rozzzly** [comment] 2017-03-29 15:07
Alternatively, it could check for other imports and use the quote style those do. Perhaps read `.editorconfig`

**Comment by devrelm** [comment] 2017-03-31 14:49
I'm really interested in this getting fixed up, but it looks like it's a dup of #21424, which itself was closed as being tracked by Microsoft/TypeScript#13270.

**Comment by mjbvz** [comment] 2017-04-03 17:29
Yes, thanks @devrelm. This is a duplicate of Microsoft/TypeScript#13270 and really should be fixed upstream on the TypeScript side

**Closed by mjbvz** 2017-04-03 17:29 UTC
Labels: upstream

**Comment by MetodoDigital** [comment] 2017-05-18 11:33
As @adyavanapalli very well mentioned, you can edit the **_typescript.json_** file to get around this issue on `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/` for MacOS and `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\` for Windows.

Thx buddy.

**Comment by cengkuru** [comment] 2017-09-22 07:56
adding  "prettier.singleQuote":true, did the trick for me

**Comment by bjareczek** [comment] 2017-10-10 11:11
Howdy @cengkuru ... where did you add prettier.singleQuote?  Seems unrecognized in VS user settings.  Thx!

**Comment by LukaszGrela** [comment] 2017-11-01 21:40
@bjareczek I presume it is a plugin to the VS/VSC
