### ISSUE TITLE
Error: EFILE -> VSCode don't open then the computer is on airplane mode or wi-fi disabled.

### ISSUE THREAD

**Issue by gustavosatheler** [Microsoft/vscode#61498] opened 2018-10-22 13:46 UTC
- VSCode Version: 1.26.0
- OS Version: Windows 10 Home Single Language (1809)
- OS Build: 17763.104

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce the error:
**1. Turn on airplane mode or disable Wi-fi**
**2. Open the terminal**
**3. Insert the command:**
`code .` or `code . --disable-extensions`
**4. Then the following error will appear:** 

```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

Image of error
![image](https://user-images.githubusercontent.com/6925493/47296083-a0fe9280-d5e7-11e8-8c9f-5fae832585fa.png)

**Comment by mjbvz** [comment] 2018-10-22 19:48
Duplicate of #61044

**Closed by mjbvz** 2018-10-22 19:48 UTC
Labels: javascript
