### ISSUE TITLE
The newest vscode update broke debugging in older AL extensions 

### ISSUE THREAD

**Issue by dannoe** [microsoft/vscode#112357] opened 2020-12-12 11:32 UTC
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

The newest vscode update just broke old vscode AL extensions (see https://github.com/microsoft/al) which are required for older versions of business central / dynamics NAV.

Steps to Reproduce:

1. Open AL project with vscode
2. Install old AL extension (e.g. v3.0.168874) [direct link on marketplace](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/3.0.168874/vspackage)
3. Try to publish your AL project with F5
4. Get the following error: 
``` Couldn't find a debug adapter descriptor for debug type 'al' (extension might have failed to activate) ```

![grafik](https://user-images.githubusercontent.com/7450586/101979786-f11d9080-3c57-11eb-851e-47cfa6a82e74.png)

Does this issue occur when all extensions are disabled?: Yes/No
AL extension is required for debugging.

I posted this to both repos (see https://github.com/microsoft/AL/issues/6368) because I don't know which Team is responsible for fixing this.

**Comment by isidorn** [comment] 2020-12-14 09:30
Thanks for filing this against the AL extension, let's close this until their team investigates initialy.
If they discover the issue is on the VS Code side we can reopen this one.
Thanks!

**Closed by isidorn** 2020-12-14 09:30 UTC
Labels: debug
