### ISSUE TITLE
Add support to making the window transparent

### ISSUE THREAD

**Issue by SamZiggler** [Microsoft/vscode#27241] opened 2017-05-25 09:39 UTC
Right now you can't make the window transparent

**Comment by roblourens** [comment] 2017-05-25 17:29
Partially transparent like terminals sometimes can do? Not sure whether Electron supports that.

**Comment by Tekbr** [comment] 2017-05-25 17:34
Similar or duplicate of #12578, no?

**Comment by roblourens** [comment] 2017-05-25 17:35
Yes, thanks

**Closed by roblourens** 2017-05-25 17:35 UTC
Labels: feature-request, ux
