### ISSUE TITLE
Support for multiple terminals

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6708] opened 2016-05-24 05:27 UTC
I think pretty early on we will get the feature request to support multiple terminals. As soon as you run a program from the terminal, you cannot use it anymore. 

Maybe we just allow to create new terminals with an action from the terminal panel and show all opened terminals from a dropdown similar to output channels?

We did this in Monaco on Azure:

![image](https://cloud.githubusercontent.com/assets/900690/15492968/e747b8e8-2180-11e6-999f-0e6a822cb5c3.png)

**Comment by Tyriar** [comment] 2016-05-24 21:04
Duplicate of https://github.com/Microsoft/vscode/issues/6458

**Closed by Tyriar** 2016-05-24 21:04 UTC
Labels: feature-request, integrated-terminal
