### ISSUE TITLE
Command palette doesn't contains extensions command

### ISSUE THREAD

**Issue by maxtar** [Microsoft/vscode#32718] opened 2017-08-17 12:28 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
markdown-toc|Ala|1.5.6
better-toml|bun|0.2.0
gitignore|cod|0.5.0
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
LogFileHighlighter|emi|1.1.1
code-runner|for|0.6.33
gc-excelviewer|Gra|1.1.15
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.15.1
output-colorizer|IBM|0.1.2
Ionide-fsharp|Ion|2.33.0
Ionide-Paket|Ion|1.7.3
Angular2|joh|2.4.0
intellij-idea-keybindings|k--|0.2.13
vscode-github|Kni|0.18.1
Go|luk|0.6.63
Kotlin|mat|1.3.0
markdown-shortcuts|mdi|0.8.1
vscode-todo-parser|min|1.9.1
mssql|ms-|1.1.0
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
sublime-keybindings|ms-|2.9.1
vscode-docker|Pet|0.0.16
java|red|0.8.0
todotasks|san|0.5.0
preview-vscode|sea|1.1.5
vscode-table-formatter|shu|1.2.1
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.6
code-spell-checker-russian|str|0.1.1

---

Hi, I don't understand why, but my I couldn't run extensions command from palette. I just install different extensions for markdown. Ant in one moment I mention that palette does not contains any extensions command.
I've tried remove extensions. I've removed c:\Users\<username>\AppData\Roaming\Code\ directory. But all these steps didn't help me.
Reinstall didn't help.
Please help. What else I must to do?

Reproduces without extensions: Yes

**Comment by maxtar** [comment] 2017-08-17 14:45
Hm, Strange behavior. I've copied Go extension command "Go: Current GOPATH" and all commands returned to palette!

**Comment by Platzer** [comment] 2017-08-17 15:12
Just updated `Ionide-fsharp` to `2.33.1` and my commands are back 🤔

**Comment by maxtar** [comment] 2017-08-17 19:29
@Platzer I will check when to be at work tommorow. May be I've update too.

**Comment by joaomoreno** [comment] 2017-08-18 07:09
Let us know what you find.

**Comment by maxtar** [comment] 2017-08-18 08:31
Yeap. My Ionide-fsharp updated to 2.33.1 too and now all works!

**Comment by joaomoreno** [comment] 2017-08-18 10:01
Duplicate of #32673

**Closed by joaomoreno** 2017-08-18 10:01 UTC
Labels: markdown, needs more info, new release
