### ISSUE TITLE
False file content display on startup

### ISSUE THREAD

**Issue by faliagas** [microsoft/vscode#74036] opened 2019-05-21 05:22 UTC
After opening a C++ file in a computer A that was previously edited in another computer B, the content of the file displayed is not the current content but the previously saved file in computer A. Here are two screenshots:
1. File as opened by vs code (false content) and gedit (Ubuntu 19.04).
![vscode-Screenshot from 2019-05-21 08-03-00](https://user-images.githubusercontent.com/28477635/58070194-cdd84f80-7ba0-11e9-91bb-79e9ebee837d.png)
2. File as displayed by vs code after closing _without saving_ and reopening (correctly displayed), and gedit (Ubuntu 19.04).
![vscode-Screenshot from 2019-05-21 08-04-46](https://user-images.githubusercontent.com/28477635/58070289-29a2d880-7ba1-11e9-8163-04abd1130996.png)

**Comment by alexr00** [comment] 2019-05-21 08:42
@faliagas it looks like the file in your first screen shot has been edited (see the dot next to the file name in the tab). Is it possible that you closed VS Code with an unsaved edit in the file? VS Code will restore your unsaved file upon re-opening.

**Comment by faliagas** [comment] 2019-05-21 10:42
@alexr00  I am sure I saved the file before closing VS Code. This problem has appeared at least 4-5 times. One can tell that something is not OK from the little circle next to the file name in the editor tab.

**Comment by bpasero** [comment] 2019-05-23 15:34
Closing as designed, a file that has changes will not restore from disk. The first screenshot shows the file is dirty.

**Closed by bpasero** 2019-05-23 15:34 UTC
Labels: needs more info

**Comment by faliagas** [comment] 2019-05-23 19:41
The file has no changes because the other editor on the right opens it
correctly. The file was opened in vs code immediately after booting and
nothing was changed. IT WAS OPENED AS MODIFIED STRAIGHT FROM THE BEGINNING.
The version of the file that appears in vs code is exactly the file as it
was in the previous day. It seems that vs code uses some kind of file
caching, and, I think, this is where the problem is.
