### ISSUE TITLE
git diff broken in 1.86

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#204239] opened 2024-02-03 13:49 UTC
Type: <b>Bug</b>

Since updating to 1.86, when I open a git diff in VSCode, I see the latest version of the file on both sides, showing no differences (except that word wrap is off on the left & on on the right... it's on everywhere else)... if I stage a file, open the diff, then unstage the file, then I see the correct diff like I've always seen before

likely related: the new +- buttons next to Changes & Staged Changes show the same behavior (although while playing with it, I did have one time where I saw the correct diff on the first file)

at one point I restarted VSCode, which seemed to resolve the issue, but it was only temporary. once I started editing files again the issue returned

not sure if it's relevant or not, but... in all cases, the changes were saved to disk... the git change indicators in the left gutter of open files are not affected by this issue, they continue to work as the always have, showing up as I edit, clearing when I stage the change

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.13GB free)|
|Process Argv|--file-uri file:///c%3A/src/AF4JM.code-workspace --crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
case-change|Aka|1.0.2
rtf|ale|2.7.0
spellright|ban|3.0.122
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-mermaid|bie|1.21.0
markdown-yaml-preamble|bie|0.1.0
vscode-tldr|bmu|1.0.0
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.20
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
EditorConfig|Edi|0.16.4
vscode-macros|EXC|1.4.1
git-project-manager|fel|1.8.2
url-encode|fle|1.1.0
shell-format|fox|7.2.5
matlab|Gim|3.0.2
vscode-pull-request-github|Git|0.80.0
gc-excelviewer|Gra|4.2.58
vscode-markdown-footnote|hou|1.0.0
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
path-autocomplete|ion|1.25.0
mediawiki|jak|2.1.0
anki|jas|1.3.1
markdown-katex|jef|0.1.4
vscode-peacock|joh|4.2.2
gpg|jva|1.1.1
zotero|mbl|0.1.11
markdown-shortcuts|mdi|0.12.0
debugpy|ms-|2024.0.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.6
azurecli|ms-|0.6.0
hexeditor|ms-|1.9.13
live-server|ms-|0.4.13
vscode-yaml|red|1.14.0
vscode-zipexplorer|sle|0.3.1
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.7.0
org-mode|vsc|1.0.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-02-03 18:38
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by af4jm** [comment] 2024-02-04 13:46
I can duplicate this in Insiders with no extensions loaded (... however, that opening & closing revealed more details I didn't realize previously...

I only see the buggy behavior with changes made in this session... if I close & reopen VSCode, changes that were staged before VSCode opened render correctly... new changes stop rendering when they're staged (and when I say "stop rendering" I mean no red & green highlights, because both sides of the diff tab contain the new code)

side notes:

- I'm no longer seeing the no word wrap on the left in VSCode (& I never saw it in Insiders), so not sure what was up with that... I know that there are often visual artifacts in one side of the diff editor (e.g. valid relative paths get yellow squiggles on one side but not the other), so guess I'll put this one in that category... who cares? I'll see that in the main editor, I just want the diff in the diff viewer
- I forgot to try Insiders before I submitted because it was so obvious that only 1 thing changed, but I'll try to remember that just to make sure it hasn't been fixed already... but, I don't appreciate being asked to go on a wild goose chase bisecting extensions

**Comment by Timmmm** [comment] 2024-05-03 07:21
I'm hitting this too on two completely different machines (Windows and Linux). The issue is if you click the diff button on a staged file just after staging it, for some reason it opens the working tree diff (which has no differences). If you reload the window so it starts with the file already staged then the button correctly opens the index diff.

I reproduced this with no extensions enabled.

I think the reason this enormous bug has gone unnoticed for so long (I only just looked into it because I assumed that surely they would fix something as broken as this...), is that it only happens if you have this setting:

```
    "git.openDiffOnClick": false,
```

Do you guys have that set?

**Comment by af4jm** [comment] 2024-05-07 15:46
yes, I do have that setting... and if I comment it out, I see the correct behavior

**Comment by lszomoru** [comment] 2024-05-29 14:47
Sorry for not getting back to you on this. Could any of you experiencing this issue provide a screen recording illustrating the issue (https://gifcap.dev)? Thank you very much in advance!

**Comment by Timmmm** [comment] 2024-05-29 21:21
Ugh I can't seem to reproduce it at the moment - *sometimes* it does work, but I haven't found the exact pattern. So you'll have to use your imagination, but basically you click the diff button for a file (two circles connected by arrows) and it opens a diff view but there are no differences between the files on the left and right of the view.

Next time it happens I'll try to record it.

**Comment by lszomoru** [comment] 2024-05-30 07:41
Are you able to reproduce the issue if you disable the `git.optimisticUpdate` setting? Thanks!

**Comment by Timmmm** [comment] 2024-05-30 10:19
Didn't seem to make any difference - I still can't reproduce it, sorry. What does that setting actually do? It doesn't seem to make any difference to behaviour and I don't understand the description:

![image](https://github.com/microsoft/vscode/assets/376842/9aadee78-ee9b-4d97-88a4-83d92a87f4d2)

The Source Control view still automatically updates even if I have that off.

**Comment by af4jm** [comment] 2024-05-30 22:38
@lszomoru if I add `"git.openDiffOnClick": false` to my settings I can repro, without it I can't repro... just recorded with gitcap, waiting for it to render so I can get a link

**Comment by af4jm** [comment] 2024-05-30 23:56
![](https://1drv.ms/i/s!Auy35hyaQsjmnpB70oGx2DvOlOjaXg?e=YLgT5J)

**Comment by lszomoru** [comment] 2024-07-25 14:24
@af4jm, could you please re-upload the recording as it looks like it is not available at the link any more. Thanks!

**Comment by af4jm** [comment] 2024-07-25 15:31
> @af4jm, could you please re-upload the recording as it looks like it is not available at the link any more. Thanks! 

i will try tonight... on vacay this week, so might need to wait until I'm back on the work PC Monday

**Comment by lszomoru** [comment] 2024-08-26 10:14
@af4jm, any news on the recording? Thank you!

**Comment by af4jm** [comment] 2024-08-26 10:28
![Recording 2024-08-26 at 06 28 08](https://github.com/user-attachments/assets/f1353378-065f-4869-911c-38847f86bfa7)

**Comment by lszomoru** [comment] 2024-08-28 14:24
@af4jm, thanks again! I have a fix but it will not make the cut for the August 2024 release so it will be in the September 2024 release.

**Closed** 2024-08-30 12:01 UTC
Labels: bug, git, confirmed

**Comment by lszomoru** [comment] 2024-09-27 14:08
Verification steps:
1. Launch VS Code Insiders
2. Set `git.openDiffOnClick` to `false`
3. Open a file, modify it and save it
4. Open the Source Control view and click on "Open Changes" action
    * Confirm that the diff is rendered correctly 
6. Click on the "Stage Changes" action
7. Click on "Open Changes" action
    * Confirm that the diff is rendered correctly
