### ISSUE TITLE
Inline styles break document formatting for HTML

### ISSUE THREAD

**Issue by admilne** [Microsoft/vscode#19666] opened 2017-02-01 09:55 UTC
![screen shot 2017-02-01 at 09 51 59](https://cloud.githubusercontent.com/assets/1877394/22502266/234777a2-e864-11e6-9eb4-9f36d472959c.png)
![screen shot 2017-02-01 at 09 51 31](https://cloud.githubusercontent.com/assets/1877394/22502265/23430032-e864-11e6-85b5-c51c3888c6b1.png)

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|vscode-theme-onedark|akamud|0.3.1|
|project-manager|alefragnani|0.13.1|
|php-intellisense|felixfbecker|0.0.12|
|vscode-scss|mrmlnc|0.6.0|
|sass-indented|robinbentley|1.3.0|

---

When using the format document command, the formatting breaks if there are inline styles in a HTML document. One screenshot shows the code with an inline style, which makes the next paragraph indent incorrectly. The other shows code with no inline style and the formatting works fine.

**Comment by aeschli** [comment] 2017-02-01 15:59
duplicate of #17849

**Closed by aeschli** 2017-02-01 15:59 UTC
