### ISSUE TITLE
new settings editor should not automatically remove a setting from the json when it is set to any value explicitly

### ISSUE THREAD

**Issue by geekley** [Microsoft/vscode#58901] opened 2018-09-18 18:39 UTC
_(not sure if this is a feature request or a bug, since it was intentional)_

**Default settings may change.**  
When users explicitly set a setting to a value, they expect to have a guarantee that the setting they chose explicitly will not change in the future, even if the default happens to change.

However, when you use the new settings editor to change a setting back to a value that happens to be the default, it removes the setting from the json.  
This is not only wrong, but also unnecessary, since the settings editor already has a simple way to track modified settings and reset a setting to its default value:
![reset-setting](https://user-images.githubusercontent.com/38332912/45707170-881c4080-bb54-11e8-8c6e-089db0ac728e.png)

I strongly think the current behavior is incorrect, because these two things are completely different when we think about **user intention**:
- explicitly wanting a value that happens to be the default
- accepting whatever the default is for that setting

An example of why I think this sort of thing is important:  
https://money.cnn.com/2018/06/07/technology/facebook-public-post-error/index.html
It may be an extreme example, but you get the point.

This incorrect behavior is the sole reason I was still using the json to edit my settings, and it became more of a concern now that the new editor is the default.

The correct behavior should be:
- When setting the value explicilty, mark the setting as modified/overriden and keep the setting in the json, even if it happens to be equal to the default. The user wants the guarantee that the setting will have THAT value, and a way to remember that such value was explicitly chosen by them.
- When choosing "Reset Setting", remove the setting from the json, because the user wants to accept whatever the default is, even if it changes later. Mark the setting as not modified/overriden.

If possible, change the text and semantics of "modified" settings to "overriden" settings.

**Comment by roblourens** [comment] 2018-09-19 17:58
Duplicate of https://github.com/Microsoft/vscode/issues/58038

**Closed by roblourens** 2018-09-19 17:58 UTC
