### ISSUE TITLE
System-level settings

### ISSUE THREAD

**Issue by dandrestor** [Microsoft/vscode#73300] opened 2019-05-05 10:19 UTC
Could you add support for a third level of settings, something that is at the system level, that is, host-dependent? There are some settings that could be more easily managed in this way, such as UI zoom level, fonts, proxy, etc.

**Comment by RMacfarlane** [comment] 2019-05-05 15:21
Duplicate of https://github.com/Microsoft/vscode/issues/5595

**Closed by RMacfarlane** 2019-05-05 15:21 UTC
