### ISSUE TITLE
Add terminal window(terminal service) in workbench

### ISSUE THREAD

**Issue by javagg** [Microsoft/vscode#528] opened 2015-11-24 06:20 UTC
The workbench on visual studio online on Azure has a nice power-shell terminal to let user work with their workplace in cloud. Other mature IDE products also have term window in their workbench. That way, user can interactively exec some command without switch between desktop and vscode window.

**Comment by Tyriar** [comment] 2016-05-27 23:19
Duplicate of https://github.com/Microsoft/vscode/issues/143, it's coming in the next stable release!

**Closed by Tyriar** 2016-05-27 23:19 UTC
Labels: feature-request
