### ISSUE TITLE
我开启了自动更新，为什么更新后，我以前的配置全部给重置了？关键的问题，现在还不知道怎么配置了！！我想怎么函数名 function 后面加一个空格，还有那个自动添加的分号符；；；怎么拿掉？

### ISSUE THREAD

**Issue by zhaojianshu** [Microsoft/vscode#36611] opened 2017-10-20 03:28 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
cssrem|cip|0.0.3
vscode-markdownlint|Dav|0.10.1
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
react-redux-react-router-snippets|dis|0.3.5
githistory|don|0.2.3
xml|Dot|1.9.2
es7-react-js-snippets|dsz|1.1.3
gitlens|eam|5.7.1
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
react-native-react-redux|EQu|1.4.1
auto-close-tag|for|0.5.1
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
typings-autoinstaller|jvi|1.2.0
node-debug2|ms-|1.18.3
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
java|red|0.12.0
jsx|Twe|0.0.1
vscode-react-native|vsm|0.4.3
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-20 03:30
Duplicate of #36610

**Closed by mjbvz** 2017-10-20 03:30 UTC
Labels: javascript, new release
