### ISSUE TITLE
Crashes on Open

### ISSUE THREAD

**Issue by mikeal** [Microsoft/vscode#6181] opened 2016-05-07 00:54 UTC
- VSCode Version:
Latest from website as of today, I can't get it open to check the actual version.
- OS Version:
OS X El Capitan 10.11.4 (15E65)

Steps to Reproduce:

1. Open VSCode.
2. Crash

I found this message in the console. It's an Electron message so I figure this is the issue.

5/6/16 5:53:57.739 PM Electron[90811]: Error loading /Users/mikeal/Library/Application Support/SIMBL/Plugins/megazoomer.bundle/Contents/MacOS/megazoomer:  dlopen(/Users/mikeal/Library/Application Support/SIMBL/Plugins/megazoomer.bundle/Contents/MacOS/megazoomer, 265): no suitable image found.  Did find:
	/Users/mikeal/Library/Application Support/SIMBL/Plugins/megazoomer.bundle/Contents/MacOS/megazoomer: no matching architecture in universal wrapper
5/6/16 5:53:58.676 PM Electron[11354]: CGSSetWindowTitle: Invalid window

**Comment by bpasero** [comment] 2016-05-07 08:30
@mikeal can you try to run it from the console, like `./VSCode.app/Contents/MacOS/Electron`

**Comment by bpasero** [comment] 2016-05-13 05:06
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-05-13 05:06 UTC
Labels: needs more info

**Comment by mjbrender** [comment] 2016-08-15 13:58
Hey @bpasero, just ran into this one. 

* Running 1.4.0 according to `code -v`
* OS X 10.11.6

Launching from terminal or through .app file crashes with: 

```
8/15/16 6:50:35.429 AM Electron[70239]: CGSSetWindowTitle: Invalid window
```

I ran Electron like you requested (at `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`) without error, but didn't see anything launch. Console showed the same error: 

```
8/15/16 6:57:18.131 AM Electron[70239]: CGSSetWindowTitle: Invalid window
```

Lmk what I could do to help troubleshoot next.

**Comment by bpasero** [comment] 2016-08-15 14:17
@mjbrender please do not hijack issues that are closed, instead file a new issue with reproducible steps and all the details.

**Comment by mjbrender** [comment] 2016-08-15 15:29
I'm good opening a new issue, though you may want to note there's no sign of this preference in your CONTRIBUTING.md file. It is also a common (and often helpful) practice to reopen unresolved issues as opposed to cluttering backlog with a new one. 

No hijacking intended - only context to help clarify the issue.

**Comment by bpasero** [comment] 2016-08-15 18:34
If only people on GH would read our guidelines, you might be the first :-)
