### ISSUE TITLE
Add progress bar to the statusbar

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#563] opened 2015-11-24 20:45 UTC
_From @SamVerschueren on November 18, 2015 13:50_

Is it possible to show a progress bar or something to the status bar?

And is there any documentation regarding adding a statusbar item?

_Copied from original issue: Microsoft/vscode-extensionbuilders#126_

**Comment by seanmcbreen** [comment] 2015-11-24 20:45
_From @jrieken on November 18, 2015 13:53_

not really, we should support animated gif or even some css-animatations...

**Comment by seanmcbreen** [comment] 2015-11-24 20:45
_From @SamVerschueren on November 18, 2015 13:55_

@jrieken Thanks! Is it possible to provide me a small sample of the statusbar api? The documentation is empty.

**Comment by seanmcbreen** [comment] 2015-11-24 20:45
_From @SamVerschueren on November 18, 2015 14:13_

Found an example in [wordcount](https://github.com/Microsoft/vscode-wordcount/blob/master/extension.ts).

**Comment by seanmcbreen** [comment] 2015-11-24 20:45
_From @SamVerschueren on November 18, 2015 14:31_

Nothing we can't solve with [elegant-spinner](https://github.com/sindresorhus/elegant-spinner) ;)

![progress](https://cloud.githubusercontent.com/assets/1913805/11243643/6fc2cdc2-8e09-11e5-8754-1f4f08570419.gif)

PS: It's a lot smoother then on the gif...

**Comment by seanmcbreen** [comment] 2015-11-24 20:45
_From @jrieken on November 19, 2015 10:19_

:+1:

**Comment by tht13** [comment] 2016-03-10 15:59
Is there any progress with this? Vscode uses animated icons itself for both Git Sync and Task running, if someone can point me to the files, I'd be happy to look into doing a PR :smile:

**Comment by jrieken** [comment] 2016-03-11 08:21
sorry, no update yet. taking as input for a broader icons/glyph story which includes status bar, symbol icons (e.g. for symbol search et al), editor decorations etc

**Comment by indiejames** [comment] 2017-01-06 17:54
What ever happened to this?

**Comment by bpasero** [comment] 2017-01-16 17:06
I think @jrieken is working on this.

**Comment by dfroze** [comment] 2017-01-16 17:15
Hmm, seems a bit related to my post  #17300 , but needs more then just a simple animation, some information near to it would be great

**Comment by jrieken** [comment] 2017-01-16 17:23
Closing as dupe of #18066

**Closed by jrieken** 2017-01-16 17:23 UTC
Labels: api, feature-request, workbench
