### ISSUE TITLE
regression: ctrl-click in terminal doesn't handle trailing ':' in file:line:col: links

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#144778] opened 2022-03-09 19:52 UTC
Issue Type: <b>Bug</b>

regression: https://github.com/microsoft/vscode/issues/101155

i use this _all the time_, and this got broken _again_ with the latest update.

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (15.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (19.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (19.61GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkraken-authentication|git|1.0.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
gitlens|eam|12.0.2
autoscrolldown|fox|1.2.1
gitkraken-authentication|git|1.0.3
cpptools|ms-|1.8.4

</details>

**Comment by Spongman** [comment] 2022-03-09 20:08
ok, it looks like it's a little more subtle than that issue. sometimes ctrl-clicking a link in the terminal window shows the pre-populated search-by-files popup, and then navigates to the correct location. other times it just opens the file directly and puts the cursor at the stsart of line #1 regardless of the value in the terminal link.

**Comment by Spongman** [comment] 2022-03-09 20:17
it also seems like there's some kind of background processing going on. sometimes the links in the terminal don't update immediately and sometimes hovering on a newly typed line shows the link in the location as if that line had not been typed (ie in the location of where the previous line was before it scrolled up).

**Comment by Spongman** [comment] 2022-03-09 20:36
here's a demo: https://youtu.be/Mtd5mNdnR_s

- first i click a link to `main.cpp:5`, it opens the popup as usual, and then correctly navigates to line 5.
- then i click a link to `platformio.ini:5`. this time it immediately opens the file (no popup) and fails to navigate to the correct line. note that the clicked link in the terminal _does_ underline the `:5` part.

**Comment by Tyriar** [comment] 2022-03-15 15:46
I can reproduce this in stable and it appears to be fixed already in Insiders, could you verify your problems is fixed in https://code.visualstudio.com/insiders?

**Comment by Spongman** [comment] 2022-03-25 20:50
no. this is NOT fixed in 1.66.0-insider. please reopen.

**Comment by Tyriar** [comment] 2022-03-28 13:33
Can reproduce, here are more specific steps:

1. Ensure shell integration is _disabled_
2. Create a file in the root folder that will not match any other file in the workspace
3. `# <thefile>:5`, 🐛 it will open to line 1

**Comment by Spongman** [comment] 2022-03-28 16:39
i can confirm that the problem seems to go away if i enable shell integration.

**Comment by Alizter** [comment] 2022-07-07 12:44
The supposed fix has broken other link detection.VS Code no longer picks up
```
"test-suite/tools/gen_rules/gen_rules.ml", line 309, characters 6-13
```
Only the file name is highlighted.

**Comment by Tyriar** [comment] 2022-07-07 12:54
@Alizter I don't think the `, characters x-y` part was ever supported but line works for me:

![image](https://user-images.githubusercontent.com/2193314/177778122-f27964ee-aa05-4dde-923a-dd24f6eeb8bc.png)

This works with and without shell integration enabled.

Did you create the terminal in the parent folder of `test-suite`?

**Comment by Alizter** [comment] 2022-07-07 13:03
@Tyriar In previous versions of code, the entire thing was highlighted. Notably before `ctrl` was required to click on links.

> Did you create the terminal in the parent folder of `test-suite`?

Yes.

**Comment by Tyriar** [comment] 2022-07-07 14:17
> In previous versions of code, the entire thing was highlighted. Notably before ctrl was required to click on links.

@Alizter the patterns are defined here:

https://github.com/microsoft/vscode/blob/f52f2ed7b5f50dac9aa71e899d12078c31020ca0/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts#L49-L59

The file did move I think 6-12 months ago, but searching recent git history for "characters" comes up with zero results.

Also ctrl was always required to click links if I'm remembering right (maybe not very early on several years ago?).

> > Did you create the terminal in the parent folder of test-suite?
>
> Yes.

Can you create a new issue with repro steps? It's a different problem then what's tracked here.

**Comment by Tyriar** [comment] 2022-07-08 12:34
@Alizter `"<path>", line <n>` is supported as shown above from this line:

https://github.com/microsoft/vscode/blob/96f310e3ebee05189f03e974713ec1c666b15b6a/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts#L53

`, lines x-y` however isn't, it was a feature request here https://github.com/microsoft/vscode/issues/144837 but got closed off as it didn't get enough votes. Is this confusion around both `characters` and `lines` not being supported but `line` being supported?

**Comment by peternann** [comment] 2022-09-25 13:27
Found my way here because V1.71.2 doesn't seem to understand Jest references like "myfile.ts:12:56".
It DOES underline the right characters, right up to the '6', but when ctrl-clicked it pops the 'partial match' selector.

It's a perfect match to a local file - I expect it should just jump straight to the line, right?

**Comment by Tyriar** [comment] 2022-12-07 20:47
I fixed the trailing colon problem yesterday in https://github.com/microsoft/vscode/pull/168240 which will land in insiders in a few days (after 1.74.0 stable goes out).

This is specifically about the issue in the top comment which points at https://github.com/microsoft/vscode/issues/101155:

```
File.cpp:52:32: error: blah blah blah
```

The fix specifically targeted [word links](https://code.visualstudio.com/docs/terminal/basics#_links), this is the type of link above as it's missing the path indicators (eg. `./<path>`, `/<path>`, etc.). There are other types of links which I also believe are fine but please open an issue with a specific repro if you find an edge case that isn't working.

**Closed by Tyriar** 2022-12-07 20:47 UTC
Labels: bug, confirmation-pending, terminal-links

**Comment by TylerLeonhardt** [comment] 2023-01-25 23:00
@Tyriar just to make sure I test the right thing, can you give steps?

**Comment by Tyriar** [comment] 2023-01-26 18:45
A word link (those that need ctrl/cmd held) should include the :line:col. Just verified it myself:

![image](https://user-images.githubusercontent.com/2193314/214922777-1488e702-e65c-4bbe-8a7f-8d0c75227125.png)
<img width="99" alt="image" src="https://user-images.githubusercontent.com/2193314/214922867-79392e2b-916a-4f05-b345-9f2e12b2ec73.png">
