### ISSUE TITLE
[Markdown Syntax] Splitting lines causes formatting to not work

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#19949] opened 2017-02-05 01:47 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open a markdown file with the following text:
  ```markdown
  **_NOTE_: Broken highlighting
  when a line break introduced.**
  ```

## Expected Output:

All the text within the `**` is marked as bold.

## Actual Output:

Only the text within `_` is italicised but the bold style between `**` is not applied.

## NOTE: This renders correctly as expected in the preview. It's just the editor syntax that's broken.

![capture](https://cloud.githubusercontent.com/assets/10473142/22623036/13bb6d40-eb73-11e6-84b7-15fdc59e73de.PNG)

**Comment by mjbvz** [comment] 2017-02-06 18:51
Thanks for the detailed report. Closing as duplicate of #1837. We currently can't handle inline element split across multiple lines like this

**Closed by mjbvz** 2017-02-06 18:51 UTC
Labels: duplicate, markdown
