### ISSUE TITLE
VSCodeInsider_VSOnline_Keyboard:Tooltip is not accessible by the keyboard.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88954] opened 2020-01-20 08:16 UTC
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10​

**Repro Steps:​**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer"
4. Navigate till "VS ONLINE" control .
5. Check the tooltip is accessible or not for the below control.
![image](https://user-images.githubusercontent.com/55909580/72709842-c03df400-3b8b-11ea-8bd4-eea75413b9e5.png)

**Actual:**
Tooltip is not  accessible by the keyboard.Here it available whenever user mouse over on that icon.

**Expected:​**
Tooltip  should be accessible by the keyboard. When the above mentioned control  receives the keyboard focus the tooltip should be visible.

**Same issue observed for the below scenario:**
**1.Extension_VisualStudioOnlin**e
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Navigate  right panel till "Extension: Visual Studio Online"
![image](https://user-images.githubusercontent.com/55909580/72709974-072be980-3b8c-11ea-8c9f-30cd5f5ca20b.png)

Note:Tool tip information is not available for the keyboard user and also tool tip information is not announces by the screen reader.

**​User Impact:​**
Keyboard only user does not get tooltip information if it is not visible when keyboard focus present on the control.
[88954_VSCodeInsider_VSOnline_Keyboard.pptx](https://github.com/microsoft/vscode/files/4085108/88954_VSCodeInsider_VSOnline_Keyboard.pptx)

**Comment by isidorn** [comment] 2020-01-20 10:33
Duplicate of https://github.com/microsoft/vscode/issues/88792

**Closed by isidorn** 2020-01-20 10:33 UTC
