### ISSUE TITLE
Organize Imports "optionally" sort imports case sensitive

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#49181] opened 2018-05-04 07:26 UTC
- VSCode Version:  1.23.0
- OS Version:  Windows 10 1803

Steps to Reproduce:

1.  Enable ```"editor.codeActionsOnSave": {"source.organizeImports": true}``` in the user settings
2.  Save a TS file with imports that have mixed cased imports ```import {aClass, BClass, cClass, DClass} "..."}```

Does this issue occur when all extensions are disabled?: Yes

Can we get an option to sort the imports case insensitive - I would suggest mirroring the TSLint settings: https://palantir.github.io/tslint/rules/ordered-imports/

**Comment by mjbvz** [comment] 2018-05-04 17:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/23366

**Closed by mjbvz** 2018-05-04 17:47 UTC
Labels: new release
