### ISSUE TITLE
RenameProvider.prepareRename confusing behavior

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#145543] opened 2022-03-21 10:43 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.66.0-insider (Universal) Commit: db0525ff4ba814780e901a5b9e399aaf596b9b20
- OS Version: macOS Big Sur 11.6

Seemingly related issues:
https://github.com/microsoft/vscode/issues/58394
https://github.com/microsoft/vscode/issues/85157

The comment for prepareRename says
```
* *Note: * This function should throw an error or return a rejected thenable when the provided location
* doesn't allow for a rename.
```
Which, after reading, I thought was great so I started implementing it. However these don't expect as you'd think:
```typescript
// this actually allows the rename which it shouldn't
throw new Error("Reason for why the rename is disallowed");
// this also allows the rename but I don't mind since I don't enjoy throwing strings
throw "Reason for why the rename is disallowed";
// also allows the rename
return new Promise.reject("Reason for why the rename is disallowed");
```
while these almost work 
```typescript
// this shows the string "Error" to the user which isn't very helpful
throw new Error();
// this shows that "an unknown error has occured when..." to the user which alos isn't very helpful
throw undefined;
// also shows that "an unknown error has occured when..."
return new Promise.reject(undefined);
```
what actually works the way I want it to:
```typescript
// this shows "Reason for why the rename is disallowed" to the user
const e = new Error();
e.name = "Reason for why the rename is disallowed";
throw e;
```
and that is my current implementation which works for me but took a while to figure out. So in my opinion the implementation should be changed to allow throwing errors with messages and rejecting strings or prepareRename's comment should be expanded on.

**Comment by jrieken** [comment] 2022-03-21 11:24
Can provide a complete code sample please. All these options in below's snippet work for me

```ts
	vscode.languages.registerRenameProvider('plainText', new class implements vscode.RenameProvider {

		prepareRename(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.Range | { range: vscode.Range; placeholder: string; }> {
			throw "Throw String"
			// throw new Error("Throw Error")
			// return Promise.reject("Promise reject")
		}

		provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newName: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.WorkspaceEdit> {
			return undefined;
		}
	})
```

**Comment by MrAndersen1** [comment] 2022-03-21 11:43
Yes, of course!
```typescript
const renameProvider: vscode.RenameProvider = {
	provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newNodeName: string, token: vscode.CancellationToken) {
		return undefined;
	},
	prepareRename(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.Range | { range: vscode.Range, placeholder: string }> {
		throw new Error("Renaming dissallowed");
	}
}

vscode.languages.registerRenameProvider("typescript", renameProvider)
```

When i try this on 'plaintext' I get working behavior too which surprised me, but with 'typescript' it fails.

**Comment by MrAndersen1** [comment] 2022-03-21 11:55
I created a new typescript file containing
```typescript
let a: any;
```
and triggered rename on "a" and it lets me rename it. But if anything else could interfere I can try to provide more details if you need.

**Comment by jrieken** [comment] 2022-03-21 11:58
> When i try this on 'plaintext' I get working behavior too which surprised me, but with 'typescript' it fails.

How does it fail? Did you disable the builtin TypeScript extension before trying?

**Comment by MrAndersen1** [comment] 2022-03-21 12:17
It fails by allowing the rename, the rename popup appears allowing you to enter a new name and if you press enter it will go through with the rename.

I did not disable the builtin TypeScript extension no and I don't know how to do that, sorry, but I'm all for trying.

**Comment by MrAndersen1** [comment] 2022-03-21 12:33
Oh, I tried reading up on it a little and if I didn't have a tsconfig.json file in the workspace then the renaming worked as it should have (as in it's disallowed).

**Comment by jrieken** [comment] 2022-03-21 13:18
> I did not disable the builtin TypeScript extension no and I don't know how to do that, sorry, but I'm all for trying.

<img width="439" alt="Screenshot 2022-03-21 at 14 17 31" src="https://user-images.githubusercontent.com/1794099/159268919-5e055f12-c32c-4a16-95ac-2a534da5c006.png">

**Comment by jrieken** [comment] 2022-03-21 13:38
/duplicate of https://github.com/microsoft/vscode/issues/115354

Close this as dupe. When having multiple extensions signing up as rename provider it isn't obvious which one will take precedence.

**Closed by jrieken** 2022-03-21 13:38 UTC
Labels: needs more info, api, rename
