### ISSUE TITLE
Launch config resolving happens at an incorrect time

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34252] opened 2017-09-12 22:07 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

- Clone the repo in this issue: https://github.com/Microsoft/vscode-chrome-debug/issues/501
- Try the `Electron: Main` config
- Even though all fields are set up correctly, it looks up main.js in the package.json and tries to launch it with node. In stable it doesn't do this

![image](https://user-images.githubusercontent.com/323878/30350522-da8d30f2-97cb-11e7-9820-efa314bfe382.png)

**Comment by isidorn** [comment] 2017-09-13 09:09
@roblourens the issue is that launch config in your sample has `"request": "launch"` and has no `program` field specified. Thus @weinand provider aggresively overwrites it [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L70)

Assigning to @weinand to make that check less strict

**Closed** 2017-09-13 10:38 UTC
Labels: bug, insiders

**Comment by weinand** [comment] 2017-09-13 10:40
Yes, the missing `program` attribute was triggering the code that tries to find a program. But the `program` attribute is no longer mandatory.
