### ISSUE TITLE
[css] Support CSS :has() pseudo-class

### ISSUE THREAD

**Issue by BenjaminAster** [microsoft/vscode#147353] opened 2022-04-13 07:52 UTC
With the new CSS functional pseudo class `:has()`, you can start a selector function with `>`, `+` or `~` ([see specification](https://www.w3.org/TR/selectors-4/#relational)). However, VSCode shows a syntax error when using these.
```css
.foo:has(> .bar) {
	/* selects all foos that have a bar as a direct child */
	/* ==> syntax error in VSCode */
}

.foo:has(+ .bar) {
	/* selects all foos that are immediately followed by a bar */
	/* ==> syntax error in VSCode */
}

.foo:has(~ .bar) {
	/* selects all foos that are followerd by a bar */
	/* ==> syntax error in VSCode */
}
```

**Comment by taroken6** [comment] 2022-06-27 20:41
Hi @aeschli 
I'd like to take a shot at this

**Comment by aeschli** [comment] 2022-06-28 09:03
@taroken6 Cool, the code is in https://github.com/microsoft/vscode-css-languageservice.

The code to adopt is around here: https://github.com/microsoft/vscode-css-languageservice/blob/main/src/parser/cssParser.ts#L1409

See the readme for guidance how to run the tests.

**Comment by ExE-Boss** [comment] 2022-07-01 12:58
Duplicate of <https://github.com/microsoft/vscode-css-languageservice/issues/250>

**Closed** 2022-09-02 06:25 UTC
Labels: feature-request, css-less-scss
