### ISSUE TITLE
Extract refactorings in Playground try to create new file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53113] opened 2018-06-27 09:29 UTC
Issue Type: <b>Bug</b>

Extracting an expression in the "Refactoring via Extraction" snippet includes a 'new file' edit and fails with:

```
ERR Error: Failed to create file walkThroughSnippet:/Users/chrmarti/Development/repos/vscode/out/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#4.js
    at new FileOperationError (files.ts:610)
    at remoteFileService.ts:471
    at ExceptionPromise_ctor.ErrorPromise_then [as then] (winjs.base.js:1451)
    at RemoteFileService.createFile (remoteFileService.ts:465)
    at BulkEdit.<anonymous> (bulkEditService.ts:346)
    at step (bulkEditService.js:50)
    at Object.next (bulkEditService.js:31)
    at fulfilled (bulkEditService.js:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109)
```

VS Code version: code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Users/chrmarti/Development/repos/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-processes|and|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.0
Go|ms-|0.6.83
vscode-docker|Pet|0.0.27

</details>

**Comment by mjbvz** [comment] 2019-02-05 23:55
Duplicate of #51575

**Closed by mjbvz** 2019-02-05 23:55 UTC
Labels: bug, typescript, workbench-welcome
