### ISSUE TITLE
Not clear enough if an extension reload is needed or not

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#67347] opened 2019-01-29 10:11 UTC
Refs: #67243

Currently for some uninstalls / disablement a reload is needed and for some (when they are not activated or there is no code) a reload is not needed.
The only difference in the UX is the reload button which imho is a very small affordance.

When the extension requires a reload it is in a sort of a broken state and I suggest to somehow make this more obvious to the user.
IMHO a user will never understand when a reload is needed and when it is not, and that may be just fine. But make sure to let a user more aware that he actually needs to reload to be completely free of the extension

fyi @misolori @alexandrudima

**Comment by sandy081** [comment] 2019-01-29 11:42
Duplicate of #66931

**Closed** 2019-01-29 11:42 UTC
Labels: *duplicate
