### ISSUE TITLE
Bracket pair highlighting for LaTeX equations

### ISSUE THREAD

**Issue by ZhangSongyi** [microsoft/vscode#137774] opened 2021-11-24 03:03 UTC
Does this issue occur when all extensions are disabled?: No, except the [LaTex Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) extension.

- VS Code Version: 1.62.3
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create `.tex` file
2. Input code like below

```
$\left\{ aaa \right.$
$x \in [a, b)$
$y \in (c, d]$
```
Expected:
For L1, `\left\{` and `\right.` should be colorized as the same color, since they are marked as bracket pair [here](https://github.com/James-Yu/LaTeX-Workshop/blob/d2ae37cf274eca85513c9b339168215d876b69a2/syntax/latex-language-configuration.json#L16).
This notation is widely used to represent the piecewise function.

For L2 and L3, which represent the semi-open and semi-closed interval, the bracket should be matched even if they're not the same.

Actual:
![image](https://user-images.githubusercontent.com/12276998/143161276-7acacd40-076a-4492-aaab-140f6d82e5a0.png)

The highlighting of these bracket pairs are confused and affects the following highlighting.
For L1, it is an unexpected behavior and should be fixed.
For L2 and L3, I know it's hard to have a perfect solution, however, here is an idea:
Define a hierarchical context from the document. The bracket pair matching in the child context keeps an individual counter, which will not be affected or affect that in the parent contex. The boundary of the child context can be defined differently per language, like `$`, `\begin{equation}`, `\end{equation}` in LaTeX, and ``` in Markdown etc.

**Comment by ZhangSongyi** [comment] 2021-11-24 15:01
@hediet I think this issue should also have been labeled as `bug`, since the behavior on L1 is unexpected.

**Comment by hediet** [comment] 2021-11-24 15:14
The issue is that the latex extension should not mark `[` ... `]` as bracket pair if `[` ... `)` can appear as balanced bracket pair in the source.

Alternatively, `[` ... `)` and `(` ... `]` should also be marked as matching bracket pair.

**Comment by ZhangSongyi** [comment] 2021-11-26 01:24
Thanks @hediet for reply.
1. The bracket pair `[`...`]` cannot be removed since it is the indicator of the optional parameters in the syntax of LaTeX.
2. Adding `(`...`]` and `[`...`)` to the matching bracket pair list seems to solve the problem, shown as L1-2, L4-5 in the code snippet below (I just modified it in the local storage of the extension). However, since `[`...`]`, `(`...`)`, `(`...`]` and `[`...`)` are all marked as bracket pair, I'm not sure whether it will cause other problems. If there is no conflict, I will submit a PR to the owner of the plugin.
3. On this issue, I still retain my original proposal. Mathematicians are likely to create unbalanced bracket pairs in the equations, which we can't predict in advance and write as a configuration file. As a contrast, marking the equation region (a configurable interface per language) isolated to the rest of the source should be a better idea.
4. The mismatched issue  on `\left\{`...`\right.` is still unsolved. As shown in L3, they are resolved as matched bracket pair (identified by the frame on click) but colorized differently. Moreover, it affects the color level of all subsequent brackets. 

```
$x \in [a, b)$
$y \in (c, d]$
$\left\{ colorized differently! \right.$
$x \in [a, b)$
$y \in (c, d]$
\} % not matched but colorized identically
```
![image](https://user-images.githubusercontent.com/12276998/143512768-f078976d-71d9-4d4c-a139-f2d69c3bc417.png)

**Comment by ZhangSongyi** [comment] 2021-11-29 09:05
@hediet The patch done in https://github.com/James-Yu/LaTeX-Workshop/issues/2985 haven't fully solve this issue, especially the 4th item in my last post. I believe this is a bug in the colorization system.

**Comment by hediet** [comment] 2021-11-29 10:43
Can you provide a screenshot?

**Comment by ZhangSongyi** [comment] 2021-11-29 11:49
> Can you provide a screenshot?

The screenshot in the last post is the actual status after applying the patch of the LaTeX workshop. 

> Is this registered as bracket pair?

Yes. `\left\{...\right.` is registered as a bracket pair [here](https://github.com/James-Yu/LaTeX-Workshop/blob/02dcacc2638962c1feb6206f7b8b277c95e6de25/syntax/latex-language-configuration.json#L18). The frame shown on them also indicate they're matched. What actually goes wrong is the colorization system.

**Comment by hediet** [comment] 2021-12-03 10:44
This is the problem: `\left\{` is not a single token. Even worse, it consists of multiple tokens of different kinds.
However, in order to match a bracket, all tokens must have the same token metadata.

If you parse `\left\{` as a single token in the text mate grammar, it should work.
Otherwise, please let me know.

**Closed by hediet** 2021-12-03 10:44 UTC
Labels: feature-request, bracket-pair-colorization

**Comment by ZhangSongyi** [comment] 2021-12-04 13:09
Sorry, I don't think this issue is identical to #138058.
In #138058, `a{...}b` is registered as a **colorized bracket pair** for Typescript, but not registered as a **bracket pair** for Typescript. However, in LaTeX, `\left\{...\right.` does.

Heres comes the problem: Facing the same issue that the bracket pair contains mutiple tokens, the built-in bracket pair matching system works properly (shown in the figures below), but the colorzation is wrong. I suppose these two features should  share the same Internal mechanism, so the inconsistent behavior doesn't make sense.

![image](https://user-images.githubusercontent.com/12276998/144710298-e07829d1-7dd8-4752-9f9b-02db1ba1c3d2.png)
☝️Typescript demo after applying settings in #138058. Note that only `{...}` is marked as bracket pair instead of `a{...}b`.

![image](https://user-images.githubusercontent.com/12276998/144710379-e5966706-a148-4521-9d3d-40c9ec4f60b1.png)
☝️For this issue. Note that the whole `\left\{...\right.` is marked as bracket pair.

If these two features works independently, I think it is also unreasonable. In what cases do you think we need to colorize brackets that are not matched as bracket pair?

For about the mutiple entrance in the setting, I think there're two solutions:
- Settings in `editor.language.colorizedBracketPairs` are automaticly added into the matched bracket pair list.
- For the items in `editor.language.colorizedBracketPairs`, only the item exists in the matched bracket pair list works.

---

> If you mark \left\{ as a single token in the text mate grammar, it should work (currently \left is something and \{ is a something different).

@hediet Is there a more detailed tutorial to do that?

**Comment by hediet** [comment] 2021-12-06 09:40
> I suppose these two features should share the same Internal mechanism, so the inconsistent behavior doesn't make sense.

They don't use the same mechanism, for [algorithmic reasons](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization).

I agree that this is inconsistent and not good. We plan to use the new mechanism for the bracket pair highlighting feature, then it will be consistent again (and it will not be recognized as bracket pair in both cases).
The new mechanism is much faster than the old mechanism after some initial processing time. Unfortunately this initial processing time can get quite high for extremely large documents.

> Is there a more detailed tutorial to do that?

Unfortunately not. You would need to add a rule for `\\left\\{` somewhere in [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.tmLanguage.json).

**Comment by ZhangSongyi** [comment] 2021-12-06 11:29
>  it will not be recognized as bracket pair in both cases

Got that. Then I think it would better to inform the author of the relevant extensions (i.e., @jlelong, the maintainer of the LaTeX-Workshop) in advance, allowing them to modify the bracket pair matching rules to fit the upcoming new mechanism.

**Comment by jlelong** [comment] 2021-12-06 14:24
@ZhangSongyi  Thanks for forwarding this to me!

> You would need to add a rule for `\left\{` somewhere

Do you mean that the textmate grammar should assign the same most inner scope to every token in `\left\{`.

![Dec-06-2021 15-23-05](https://user-images.githubusercontent.com/2910140/144862848-79bd2027-3e1f-4cfe-8c69-0d64b48c2432.gif)

For the case of `\left\{`, it is sufficient to remove the scope `punctuation.definition.constant.math.tex` assigned to `\`

**Comment by hediet** [comment] 2021-12-06 14:29
> Do you mean that the textmate grammar should assign the same most inner scope to every token in \left\{
    
Yes. The current algorithm iterates over all tokens and looks for brackets inside of them.
However, a sequence of tokens with equal attributes are treated as a single token.

Thus, a bracket that spans multiple different tokens is currently not matched.
