### ISSUE TITLE
View SCM command shown twice in Command Palette

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#19684] opened 2017-02-01 18:42 UTC
- VSCode Version:1.9.0 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open Command Palette and SCM: Enable Preview SCM. Reload VS Code.
2. Reopen Command Palette and type "SCM"
3. Two View: View SCM commands are shown, one without a keybinding and one with.

![twoscm](https://cloud.githubusercontent.com/assets/12818376/22520921/051d28b0-e86b-11e6-9de7-a7f46689d553.png)

The View menu View SCM does not show the keyboard shortcut.

**Comment by Tekbr** [comment] 2017-02-01 19:04
Duplicate of #19638

**Comment by joaomoreno** [comment] 2017-02-02 08:27
Won't fix. This is a consequence of having a "Preview SCM" toggle and only reproduces when the Preview is enabled. Will disappear once the "Preview" disappears.

**Closed by joaomoreno** 2017-02-02 08:27 UTC
