### ISSUE TITLE
Failed to execute 'btoa' on 'Window'

### ISSUE THREAD

**Issue by Evian-Zhang** [microsoft/vscode#108431] opened 2020-10-10 03:01 UTC
- VSCode Version: 1.50.0
- OS Version: macOS 11.0 beta (20A5384c)

Steps to Reproduce:

1. Use hex editor to open any binary file.

It shows error:

> Unable to open 'xxx': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

Does this issue occur when all extensions are disabled?: Yes

**Comment by hediet** [comment] 2020-10-12 06:35
This seems to depend on non ASCII characters being used in the path or filename of the file being opened. It also seems to happen with the drawio extension. I cannot reproduce it in 1.50 though.

**Comment by bpasero** [comment] 2020-10-13 06:16
Closing since extensions are involved, if this issue reproduces without extensions, please comment back and we can reopen.

**Comment by hediet** [comment] 2020-10-13 07:11
@bpasero but what if this is a bug in the custom editor api? Then it can only happen when an extension is involved!

This bug has several indicators that it is not caused by the extension, but by vscode.
* the drawio extension doesn't use btoa in the webview or in the extension
* it doesn't send the filename to the webview, but the error involves "window" and only happens when a file with Chinese characters is involved

But yeah, I cannot reproduce it on my setup. However, I already got two reports.

**Comment by bpasero** [comment] 2020-10-13 07:20
@mjbvz this seems to be suspicious:

https://github.com/microsoft/vscode/blob/3b99352509cb2bf0cfc65fc567cea100e4a8a279/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L350-L350

**Comment by mjbvz** [comment] 2020-10-14 00:05
To verify:

1. Install hex editor extension 
1. Create a new file called `😀`
1. Run `reopen with` to open it using the hex editor

**Closed** 2020-10-14 00:06 UTC
Labels: bug, custom-editors
