### ISSUE TITLE
delete thai language charactor

### ISSUE THREAD

**Issue by Blankz** [microsoft/vscode#85518] opened 2019-11-25 04:55 UTC
Issue Type: <b>Bug</b>

when i delete charactor thai language like "น้อง"
it 4 charactor  but when delete น้ It delete same time

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 8|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.6.0
flutter|Dar|3.6.0

</details>

**Comment by alexdima** [comment] 2020-01-20 20:44
Duplicate of #84897

**Closed by alexdima** 2020-01-20 20:44 UTC
