### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by memoryC** [microsoft/vscode#174879] opened 2023-02-21 01:24 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230220

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33949:11)
    at parseSimpleUnaryExpression (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33582:16)
    at parseUnaryExpressionOrHigher (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33550:35)
    at parseBinaryExpressionOrHigher (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33468:25)
    at parseAssignmentExpressionOrHigher (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33141:18)
    at parseExpression (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33107:16)
    at doOutsideOfContext (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30804:12)
    at allowInAnd (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30825:12)
    at parseExpressionOrLabeledStatement (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34619:24)
    at parseStatement (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34851:12)
    at parseListElement (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31575:12)
    at parseList (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31560:19)
    at parseSourceFileWorker (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30620:24)
    at Object.parseSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30453:20)
    at createSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30314:21)
    at createLanguageServiceSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135115:22)
    at acquireOrUpdateDocument (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:132037:26)
    at Object.acquireDocumentWithKey (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:131962:12)
    at getOrCreateSourceFileByPath (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135440:31)
    at Object.getOrCreateSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135420:14)
    at c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135352:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117119:24)
    at findSourceFileWorker (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119451:23)
    at findSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119371:20)
    at c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119320:22
    at getSourceFileFromReferenceWorker (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119289:26)
    at processSourceFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119318:5)
    at processRootFile (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119114:5)
    at c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:41
    at forEach (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2309:22)
    at createProgram (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:5)
    at synchronizeHostData (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135376:15)
    at Object.getProgram (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135448:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:172060:41)
    at ConfiguredProject2.updateGraph (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:171997:32)
    at ConfiguredProject2.updateGraph (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:173179:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:174786:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:175877:26)
    at c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:64
    at flatMap (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2557:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:24)
    at updateOpen (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:177302:29)
    at c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:69
    at IpcIOSession.executeWithRequestId (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179861:14)
    at IpcIOSession.executeCommand (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:29)
    at IpcIOSession.onMessage (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179911:51)
    at process.<anonymous> (c:\Users\LC\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:181479:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.25300
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.42GB (11.94GB free)|
|Process Argv|--crash-reporter-id 3cb82683-c303-45fb-8e72-223f9e27fff2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.7
path-intellisense|chr|2.8.4
cssrem|cip|3.0.2
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.75.2023021509
vscode-typescript-next|ms-|5.0.202302200
java|red|1.15.0
git-commit-plugin|red|1.1.2
vue-vscode-snippets|sdr|3.1.1
autoimport|ste|1.5.4
tabnine-vscode|Tab|3.6.38
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.10.1
vscode-spring-initializr|vsc|0.11.2
volar|Vue|1.1.5
vscode-typescript-vue-plugin|Vue|1.1.5
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982
vsctsb:30662444

```

</details>

**Comment by mjbvz** [comment] 2023-02-21 02:26
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:26 UTC
