### ISSUE TITLE
100% cpu load on single CPU system

### ISSUE THREAD

**Issue by pm100** [Microsoft/vscode#28378] opened 2017-06-09 20:06 UTC
vs code consume 100% on a single CPU system. Real hardware may not have single CPU but single CPU vms are common (its hyper v default for example). It consumes 100% when first opened after install, I didnt even get a chance to do anything

**Comment by bpasero** [comment] 2017-06-13 04:19
It is true that we do not run well on a single CPU, this has been reported before already but I do not find the issue atm.

**Comment by pm100** [comment] 2017-06-13 14:34
This was a system rendered unusable by simply installing and opening vscode. Took me 10 mins to get task manager open in order to kill it. No other sw running on it. 4gb, 1 cpu hyperv vm running server datacenter. I installed notepad++ instead



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by jrieken** [comment] 2017-06-13 14:39
dupe of https://github.com/Microsoft/vscode/issues/17097

**Closed by jrieken** 2017-06-13 14:39 UTC
Labels: perf
