### ISSUE TITLE
can not enable inline change for git repo on remote ssh servers.

### ISSUE THREAD

**Issue by liqilei** [microsoft/vscode#119928] opened 2021-03-26 00:59 UTC
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. can not enable inline change for git repo on remote ssh servers. Can not see the colour bar (green or red). But I can see it in my local environment. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by liqilei** [comment] 2021-03-29 19:57
I found this problem was caused by symbolic link. i.e. ln -s

**Comment by lszomoru** [comment] 2022-12-13 15:05
Closing as duplicate of https://github.com/microsoft/vscode/issues/5970.

**Closed by lszomoru** 2022-12-13 15:05 UTC
Labels: bug, help wanted, git
