### ISSUE TITLE
No option to change submenu dynamically from code

### ISSUE THREAD

**Issue by codenetw** [microsoft/vscode#146184] opened 2022-03-28 12:14 UTC
I have a config file that shows the menu structure.
I need to change the scope-to submenu dynamically from the code, now I don’t see such an opportunity.

```"menus": {	
			"explorer/context": [
				{
					"label": "Scope",
					"submenu": "scope",
					"group": "1_modification@1"
				}
			  ],
			  "scope": [
					{
						"command": "scope.create",				
						"group": "1_navigation"
					},
					{
						"command": "scope.remove",
						"group": "1_navigation"				
					},
					{																	
						"group": "navigation",		
						"submenu": "scope-to"			
					}
				
			  ],
			  "scope-to": []
		  },
		  "submenus": [
			{
			  	"id": "scope",
			  	"label": "Scope",
			  	"group": "1_modification@1"
			},
			{
				"id": "scope-to",
				"label": "Add to scope"
			}
		  ]

```

**Comment by gjsjohnmurray** [comment] 2022-03-28 12:46
Previously requested at https://github.com/microsoft/vscode/issues/9827#issuecomment-619989638

As things are, all we can do is define all possible submenu items in package.json and use a custom context key to show only the the ones needed at any particular time.

**Comment by jrieken** [comment] 2022-03-28 13:20
/duplicate of https://github.com/microsoft/vscode/issues/110218

**Closed** 2022-03-28 13:20 UTC
Labels: *duplicate, menus
