### ISSUE TITLE
Bug when typing Chinese

### ISSUE THREAD

**Issue by linklelinklelin** [microsoft/vscode#91525] opened 2020-02-26 06:23 UTC
Issue Type: <b>Bug</b>

When typing Chinese in VScode, the candidate box cloud not follow the cursor as it should.
Both the macOS inputting method and the Sogou have the problem.

![bug](https://tva1.sinaimg.cn/large/0082zybply1gc9s0mo39wj32140bkgpb.jpg)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
latex-workshop|Jam|8.7.2
evermonkey|mic|2.4.5
vscode-clang|mit|0.2.3
theme-monokai-pro-vscode|mon|1.1.15
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
vsliveshare|ms-|1.0.1653
java|red|0.57.0
markdown-preview-enhanced|shd|0.5.2
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
markdown-pdf|yza|1.4.2
swig|zhu|0.0.5

(5 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2020-02-27 00:16
@wangbh0722 can you share the screenshot when using native macOS input method? Do you run into this issue always ?

**Comment by wangbh0722** [comment] 2020-02-27 08:02
![bug](https://tva1.sinaimg.cn/large/0082zybply1gcb0n7u4c2j31hs078422.jpg)
here's the native macOS input method.
Acturally I run into this issue every time when editing documents with Chinese.

**Comment by rebornix** [comment] 2020-02-27 16:41
@wangbh0722 it seems you are editing markdown file with preview open to the side, is this correct?

**Comment by wangbh0722** [comment] 2020-02-28 02:58
Acturally In that case I'm editing a latex file, but it happens when editing markdown file too. In fact it happens when i'm editing every document with Chinese in it.
Here is the screenshot when I close the preview window.
![bug3](https://tva1.sinaimg.cn/large/00831rSTly1gcbx9618iyj32l807442c.jpg)

And here's a screen shot when I'm editing a YAML file.
![bug4](https://tva1.sinaimg.cn/large/00831rSTly1gcbxeigc58j321007utbw.jpg)

in fact the problem is that the candidate box will get farther as I type in one row. At the beginning of the row it is ok. Just as this:
![bug4](https://tva1.sinaimg.cn/large/00831rSTly1gcbxi5b7k3j32lc06aq5z.jpg)

![bug5](https://tva1.sinaimg.cn/large/00831rSTly1gcbxim9fbpj32hk04ago1.jpg)

![bug6](https://tva1.sinaimg.cn/large/00831rSTly1gcbxiznrkmj32lc04wacv.jpg)

**Comment by wangbh0722** [comment] 2020-02-29 01:03
I just found that the same issue had been posted here [typing non-breaking chinese(may be non-english) will cause input method's candidate box getting farther and farther away (#85845)](https://www.github.com/microsoft/vscode/issues/85845) and it hasn't been solved yet.

**Comment by wangbh0722** [comment] 2020-03-10 03:20
So have you found the reason of this issue? And how long should I wait before it is fixed?

**Comment by wangbh0722** [comment] 2020-05-15 15:08
I've just found that this issue won't appear when using Mojave. Only Macs using Catalina have this problem.

**Comment by linklelinklelin** [comment] 2020-06-23 06:27
So how long will it be before you fix this bug... Now I'm using macOS Big Sur and the bug
still exsit.

**Comment by rebornix** [comment] 2020-07-22 18:42
It's a duplicate of https://github.com/microsoft/vscode/issues/85845, there is a limitation of the browser API and it's hard to fix this issue.

**Closed by rebornix** 2020-07-22 18:42 UTC
Labels: needs more info
