### ISSUE TITLE
Allow users to disable striping of source control decorators

### ISSUE THREAD

**Issue by mkalvas** [microsoft/vscode#146442] opened 2022-03-31 15:19 UTC
Issue Type: <b>Feature Request</b>

Following [the update to source control decorators in 1.66](https://code.visualstudio.com/updates/v1_66#_updated-source-control-decorators), users are forced to have striping over their modified lines.

I believe that the VS Code team has made such an effort to allow even the smallest of customizations to our environments that this is a bit of a miss. Users should be able to customize whether they see stripes or not.

There are two ways that I see to do this

1. Create a setting for `editorGutter.modifiedForeground` that can be set for the stripe color, transparently keeping striping as an option but allowing people to set this and `editorGutter.modifiedBackground` to the same color and making it appear solid.
2. Create a setting that disables striping, though this would likely be more work under the hood to use different CSS based on that.

One other thing to note. The current striping color is set to `editor.background` instead of `editorGutter.background` which I find odd. If I have a white editor background, a black gutter, and a yellow setting for my `editorGutter.modifiedBackground`, my stripes are now yellow and white on a black background. If anything, it should use the same color as the gutter for the background to ensure this weird (highly inaccessible) situation won't happen and it would always appear "transparent" to the gutter.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

**Comment by tycode** [comment] 2022-03-31 16:39
Hi @mkalvas, I'm glad to see someone open this issue as I was going to report the same.

The Release Notes makes clear that the reason for the change is for accessibility.

In my case, the striping pattern messes with my eyes to the point I can't concentrate on coding. This is probably partially due to the fact that the stripes don't line up from one line to the next - there's a duplicate line of pixels between lines of text (see image).
![image](https://user-images.githubusercontent.com/683985/161103822-94f11f30-68c1-48e3-a6b1-84a03f9b3bf7.png)
But even if the pattern was correct, I imagine I'd still have a problem with it. So there is an accessibility reason to make this optional.

I had to spend the next half hour constructing a monkey-patch to effectively revert this before I could do anything else. In case anyone else is interested, i.e. has a similar problem and needs something to work with before there's an update to properly address this, I'm providing it here. You'll need to use "Help > Toggle Developer Tools" and paste this in the console on each new/reloaded window.

**Standard warning: pasting random code from the internet in the console is dangerous if you don't know what the code does.** This is a benign CSS addition, but I encourage you to check that for yourself if you wish to use it :)

    (function(){var x = document.createElement('style');
    x.innerText = ('.monaco-editor .dirty-diff-modified'+
    '{background: none; border-left: 3px solid #71b9e3;}'+
    '.monaco-editor .dirty-diff-modified:before'+
    '{transform: none; background-image: none; background-color: #71b9e3;}');
    document.head.appendChild(x);})();

**Comment by valentjn** [comment] 2022-03-31 17:24
The non-continuous pattern is also bugging me more than it probably should. Not sure if we should open another issue for this as this issue here is about allowing users to disable the pattern altogether.

**Comment by mkalvas** [comment] 2022-03-31 17:47
@valentjn I went back and forth between feature and bug but since the release docs for 1.66 that I linked indicate this was a desired, known change, I felt like it's "working".

But I think I understand what you're saying about the issue with the pattern not quite working right. I think that might just be a fact of life based on screen resolutions, pixels, etc. though. Not sure there's much that could be done about a diagonal line consisting only of a few pixels looking jagged. Though it does seem like something that should be considered by the team in the overall design of a feature like this.

**Comment by homoky** [comment] 2022-04-01 07:11
Thanks for the new feature. Is is somehow possible to change background of whole row that match the decorator?

**Comment by aeschli** [comment] 2022-04-01 07:40
Maybe a duplicate of #146220?

**Comment by misolori** [comment] 2022-04-01 16:01
Yes, this is a duplicate of https://github.com/microsoft/vscode/issues/146220 please subscribe to that issue

**Closed by misolori** 2022-04-01 16:01 UTC
Labels: git, new release
