### ISSUE TITLE
Feature Request: Split Editors both Horizontally and Vertically

### ISSUE THREAD

**Issue by plambhsa** [Microsoft/vscode#50961] opened 2018-06-01 17:43 UTC
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

This is a feature request only.

I'd love to be able to split the editor both horizontally and vertically. Right now, you can only do it one or the other way. The sort of exception is when you have them split horizontally and in one of the two groups you open the git diff viewer. Then the differences are shown next to each other. I realize that it's not really an exception, because the diff is treated as a single file, but it's close to what I'm talking about.

Here's an example:

![screenshot 26](https://user-images.githubusercontent.com/14982471/40855079-a7793e52-6590-11e8-9d04-1efa01bd84c6.png)

It would be great to be able to split like this. Style files don't always need a full width, so I'd like to be able to place 2 or 3 style files in the bottom half, and an HTML and/or JS file in the top, for example. 

There's a plugin for Sublime Text, [Origami](https://github.com/SublimeText/Origami), that demonstrates what I'm talking about perfectly.

**Comment by mjbvz** [comment] 2018-06-01 18:42
Duplicate of #14909

**Closed by mjbvz** 2018-06-01 18:42 UTC
