### ISSUE TITLE
The .gitignore file logo is GitHub's logo

### ISSUE THREAD

**Issue by brycepj** [Microsoft/vscode#28435] opened 2017-06-10 21:04 UTC
<img width="179" alt="screen shot 2017-06-10 at 4 56 48 pm" src="https://user-images.githubusercontent.com/5140329/27006281-097d4f40-4dfe-11e7-9fc3-15bfc6295e9b.png">

`.gitignore` files are [a convention of Git](https://git-scm.com/docs/gitignore). GitHub is a git hosting service and private corporation, among many others, that use this convention.

vscode should be using one of the [git logos](https://git-scm.com/downloads/logos) for .gitignore and other git-related file types.

**Comment by thadjbullet** [comment] 2017-06-11 14:37
What file icons pack do you use?

**Comment by yfdyh000** [comment] 2017-06-11 16:41
Looks the icon from "Seti" theme.
https://github.com/Microsoft/vscode/blob/2f76c44632b0d47ba97f66fbc158c763628e30b3/extensions/theme-seti/icons/vs-seti-icon-theme.json#L714

**Comment by tropetre** [comment] 2017-06-12 06:09
Noticed this as well. Glad I wasn't the only one to notice. It is indeed the "vs-seti" theme. This issue is not present in "simpler-icons" theme.

**Comment by himrathana** [comment] 2017-06-12 06:13
widnows10

**Comment by himrathana** [comment] 2017-06-12 08:45
am sorry my brather. that me make the powerbaun. play with you all make am sorry.  hoo my brather all sms and call that you looking in the inter. becuse they are make all. that my brather think. and talk about me. bey bey good luck for you😌😌😌😌😌😌😌

________________________________

**Comment by aeschli** [comment] 2017-06-14 07:53
duplicate of #28300

**Closed by aeschli** 2017-06-14 07:53 UTC
