### ISSUE TITLE
[json] Text proposals in package.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9777] opened 2016-07-26 12:54 UTC
Refs #9744

- VSCode Version: insider
- OS Version: os x

Steps to Reproduce:

1.  open typescript/package.json
2. go inside grammers and trigger intelli-sense
3. I get text proposals - I thought the point is that we now do not show text proposals in json suggestions

![screen shot 2016-07-26 at 14 52 10](https://cloud.githubusercontent.com/assets/1926584/17138465/b8fff5b2-5340-11e6-807f-73fbc70d07a6.png)

**Comment by isidorn** [comment] 2016-07-26 13:04
Another issue that I have with the new approach is that as a user I am never sure when can I expect text proposals and when not. They seem to appear at random times

**Comment by aeschli** [comment] 2016-07-26 13:25
Do you find the text proposals useful? Would you rather see them or never?

**Comment by isidorn** [comment] 2016-07-26 13:27
I think we should either show them consistently or never show them.
My personal preference is to never show them, but I think the more imporant is what feedback did we get from our users.

**Comment by aeschli** [comment] 2016-07-26 13:29
Define 'consistently'...

**Comment by isidorn** [comment] 2016-07-26 13:31
Something like:
* only inside strings
* only for a values of a property that have value string, or not value type specified

If we can not easily explain/decide when we show them then we should not show them imho

**Comment by aeschli** [comment] 2016-07-27 16:04
@isidorn I can't reproduce the issue above anymore.
No sure if caused by an improvement or if you had a syntax error somewhere up in the file that caused the text proposals to show up.
I removed the empty string proposals and improved the word proposals. Please have a look.

**Comment by isidorn** [comment] 2016-07-28 07:34
I can still reproduce it, I do not have syntax errors. Just take a clean vscode repo, open package.json of typescrtip and trigger inteli-sense on end of line 60

**Comment by aeschli** [comment] 2016-07-28 07:59
![typescript-package-json](https://cloud.githubusercontent.com/assets/6461412/17205183/ed77d354-54a9-11e6-94c6-d34334528717.gif)

Version 1.4.0-insider
Commit 6ef86d5f85a531caa59bfb1715469fcfaa8d2efd
Date 2016-07-28T07:20:25.358Z

**Comment by isidorn** [comment] 2016-07-28 08:29
Did you also try it on your mac? Not saying it is releated but that is the only thing that differs?
If you want you can also debug it on my machine.

Also I do not think this is critical

**Comment by aeschli** [comment] 2016-07-28 12:46
Can't reproduce on Mac either. Tested with 
Version 1.4.0-insider (1.4.0-insider)
8d28c302aba4a284bd6dc27a842cd0bf9fb8d612

**Comment by isidorn** [comment] 2016-07-28 13:02
@aeschli drop by my machine anytime if you want to investiagte
I see it on latest vscode 6ef86d5f85a531caa59bfb1715469fcfaa8d2efd

**Comment by aeschli** [comment] 2016-07-28 16:49
Isi disabled all snippets on code completion. Bug is that the default proposals have kind snippet.

**Comment by aeschli** [comment] 2016-07-28 16:51
fixed by Microsoft/vscode-json-languageservice#2b006283ea54

**Closed** 2016-07-28 16:52 UTC
Labels: bug, json, verification-found
