### ISSUE TITLE
Duplicate files opened from problems view

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#62773] opened 2018-11-08 10:10 UTC
My build process reports errors such as:
`/home/nscott/workspace/asldev/aslcore/emcs/asl-emcs-subsystem-cms-gui/./AssetsTable.h:25:21: fatal error: ./Asset.h: No such file or directory`
My problem matcher matches this and creates:
![image](https://user-images.githubusercontent.com/376658/48191737-d02e3700-e33d-11e8-9b69-b3b2c3d4477b.png)
When I then click on it, it opens another instance of the file which is already open:
![image](https://user-images.githubusercontent.com/376658/48191802-fbb12180-e33d-11e8-976a-6384da2bf416.png)

This appears to be related to several closed issues, but also this open issue:
https://github.com/Microsoft/vscode/issues/12448

However, this specifically mentions Windows and OSX, whereas my issue is under Ubuntu.

**Comment by fleaz** [comment] 2018-11-08 11:14
Have the same issue with 1.26.1 on most recent macOS.
Appears that one file is opened with a relative and one file is opened with a absolut path and VSCode doesn't recognize it's the same file.

<img width="569" alt="screenshot 2018-11-08 at 12 11 12" src="https://user-images.githubusercontent.com/2489598/48195372-c6adca80-e34f-11e8-9ee8-47b5fd74007b.png">

**Comment by sandy081** [comment] 2018-11-12 14:05
Moving to workbench as the problems view asks the workbench to open the resource given the URL. I think the workbench has to handle duplicates/relative etc.,

**Comment by bpasero** [comment] 2018-11-18 17:01
@Gruntfuggly can you right click on each entry and copy the full absolute path to see if there is a difference?

**Comment by bpasero** [comment] 2018-11-19 09:36
@Gruntfuggly it is possible that we choke over the fact that the paths that are reported are not absolute but include a `/./.` As such the URI is different but the path will be normalized to be the same. Is it possible for you to configure the build to not produce such URIs?

**Comment by bpasero** [comment] 2018-11-19 13:20
Meanwhile, closing as duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-11-19 13:20 UTC
Labels: needs more info
