### ISSUE TITLE
Explore enabling ESM based extensions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#135450] opened 2021-10-20 06:02 UTC
Bringing up #116056 again

VS Code extensions currently use commonJS modules. However Native ECMAScript modules (ESM) are quickly becoming the standard across various JavaScript environments. We should explore what it would require to enable ESM based extensions for VS Code

As background, Node 12 introduced experimental support for modules and  Node 14 moved them to stable. The TypeScript team is also currently working to support compiling to node12 compatible modules with TypeScript 4.5: https://github.com/microsoft/TypeScript/pull/44501

**Comment by jrieken** [comment] 2021-11-01 08:14
actually, /duplicate of https://github.com/microsoft/vscode/issues/130367

**Closed by jrieken** 2021-11-01 08:14 UTC
Labels: extension-host, under-discussion
