### ISSUE TITLE
zsh history not working after update

### ISSUE THREAD

**Issue by pwegmueller** [microsoft/vscode#168396] opened 2022-12-08 05:44 UTC
Type: <b>Bug</b>

zsh history in terminal is not working anymore. MacOS - apple silicon chip

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by EricYangXD** [comment] 2022-12-08 07:10
I'm having the same problem. 
 
macOS -  Intel Core i7
VS Code version: Code 1.74.0
macOS version: 13.0.1 (22A400)

**Comment by jiangzm** [comment] 2022-12-08 07:19
`echo $HISTFILE` 
using a new profile directory without the default profile (current user).

**Comment by pepelsbey** [comment] 2022-12-08 12:10
I can confirm the same problem with the zsh history

```
Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:37:54.581Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

Also, I can’t type Cyrillic letters anymore. This might be related:

https://user-images.githubusercontent.com/105274/206443255-d262d0d9-a57f-4566-a8b8-aa5174925fc6.mov

**Comment by pepelsbey** [comment] 2022-12-08 12:18
Reinstalled 1.73, and now it works fine again

https://user-images.githubusercontent.com/105274/206444592-a971b564-6726-4592-96f5-1a70488a36fd.mov

https://code.visualstudio.com/updates/v1_73

**Comment by illuspas** [comment] 2022-12-08 13:48
+1

**Comment by ProfFan** [comment] 2022-12-08 14:51
```
echo $HISTFILE                                                                                                                                                                                   /var/folders/mw/96tsjxxxxxxxxxw0000gn/T/xxx-code-zsh/.zsh_history
```
Can confirm this bug on my M1 macOS Ventura

**Comment by alexm-atbay** [comment] 2022-12-08 14:51
Updated to 1.74 and vscode now uses it's own history file:
$HISTFILE -> /var/folders/zc/3p6k6jwj3ql9_r6q_smnz53r0000gn/T/alexmirkin-code-zsh/.zsh_history

instead of /Users/alexmirkin/.zsh_history

any way to change it?

**Comment by meganrogge** [comment] 2022-12-08 16:25
A way to work around this for now is to set the `HISTFILE` in your `.zshrc`. For example:

`HISTFILE=/Users/meganrogge/.zsh_history`

**Comment by WhatsThatItsPat** [comment] 2022-12-08 16:43
> A way to work around this for now is to set the `HISTFILE` in your `.zshrc`. For example:
> 
> `HISTFILE=/Users/meganrogge/.zsh_history`

Or `HISTFILE="$HOME/.zsh_history"`

**Comment by ozeebee** [comment] 2022-12-09 08:06
Same issue here.
I confirm setting `HISTFILE` variable directly in `.zshrc` does the trick (until this is fixed).
However, If you have like me, an indirection to load vars from another file (ex: `source $HOME/.zshrc.local`), and you have your `HISTFILE` defined therein, it does not work.
So, it **must** be defined directly in `.zshrc`.

**Comment by khawerrind** [comment] 2022-12-09 08:21
This helped me to solve the issue https://github.com/cantino/mcfly/issues/273#issuecomment-1208848236

**Comment by conradwt** [comment] 2022-12-09 22:09
I was able to resolve this issue by disabling the setting: `terminal.integrated.shellIntegration.enabled`.  For example,

![Screen Shot 2022-12-09 at 2 06 35 PM](https://user-images.githubusercontent.com/20219/206803415-1019ed27-7992-4e70-bad9-909500d34406.png)

```zsh
➜ printenv HISTFILE
/Users/conradwt/.zsh_history
```

Thus, one doesn't need to set the HISTFILE within `$HOME/.zshrc` file.  Finally, a better fix for people may be to disable this setting, `terminal.integrated.shellIntegration.enabled`, by default.

**Comment by meganrogge** [comment] 2022-12-09 22:13
@conradwt that is not what I'd suggest as it will prevent you from using features. This will soon be fixed in our recovery release.

**Comment by pwegmueller** [comment] 2022-12-10 22:22
@meganrogge thanks - did the trick for me as well.

**Comment by nth-zik** [comment] 2022-12-12 02:11
Y

> I was able to resolve this issue by disabling the setting: `terminal.integrated.shellIntegration.enabled`. For example,
> 
> ![Screen Shot 2022-12-09 at 2 06 35 PM](https://user-images.githubusercontent.com/20219/206803415-1019ed27-7992-4e70-bad9-909500d34406.png)
> 
> ```shell
> ➜ printenv HISTFILE
> /Users/conradwt/.zsh_history
> ```
> 
> Thus, one doesn't need to set the HISTFILE within `$HOME/.zshrc` file. Finally, a better fix for people may be to disable this setting, `terminal.integrated.shellIntegration.enabled`, by default.

Thank for the trick, it's work again now

**Comment by vinothpandian** [comment] 2022-12-12 16:56
Instead of disabling `terminal.integrated.shellIntegration.enabled` and lose features or modifying `$HOME/.zshrc`, we can add HISTFILE env var in vscode terminal env as a temporary workaround.

```
"terminal.integrated.env.osx": {
    "HISTFILE": "$HOME/.zsh_history"
  }
```

**Comment by conradwt** [comment] 2022-12-13 00:33
@vinothpandian In general, I would prefer to set this setting within `.zshrc` because I prefer that VSCode inherits any and all terminal-related settings from macOS.

**Comment by rebornix** [comment] 2022-12-13 00:56
Fix ported to release branch already.

**Closed by rebornix** 2022-12-13 00:56 UTC
Labels: bug, candidate, confirmed, terminal-shell-zsh
