### ISSUE TITLE
Persistent hackable CSS stylesheet

### ISSUE THREAD

**Issue by andraz** [Microsoft/vscode#42336] opened 2018-01-29 15:13 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-31-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
autofoldyeah|bob|1.0.6
prettier-vscode-semistandard|bys|0.22.1
tslint|eg2|1.0.24
sublime-keybindings|ms-|3.0.3

---

This feature already enables anyone to edit any part of the application GUI by using proper CSS selectors. How to make it persistent and easier to use?

Use case: override ugly courier font in console, debugger popup and in multiple other places.

![tooltip_001](https://user-images.githubusercontent.com/8480981/35517325-68703e3c-050e-11e8-90ec-725880746ded.png)

Steps to Reproduce:

1. Open Help > Developer Tools
2. Open Elements tab
3. Expand <head>
4. Right click on last <style> and select "Edit as HTML"
5. Add any CSS you wish

**Comment by usernamehw** [comment] 2018-01-29 15:18
Duplicate of https://github.com/Microsoft/vscode/issues/459

**Closed** 2018-01-29 15:48 UTC
Labels: css-less-sass
