### ISSUE TITLE
Minor bug - Deleting a previewable file (md) temporarily disables visibility of first document selected

### ISSUE THREAD

**Issue by colibrae** [Microsoft/vscode#44393] opened 2018-02-26 08:02 UTC
I don't think this is platform related

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a markdown file, open it up, with automatic preview enabled (is this configurable?)
2. Delete markdown file, previewer flags an error that the file is missing, close all currently open visible documents, and open a new one
3. New document doesn't appear at first, unless you open another one first.

Not a serious bug, but a bug nevertheless. Preview window should respond to deletion by closing not just an error notification.

**Comment by mjbvz** [comment] 2018-02-28 08:57
Duplicate of #12033

**Closed by mjbvz** 2018-02-28 08:57 UTC
Labels: markdown

**Comment by colibrae** [comment] 2018-02-28 09:44
It is not a duplicate. When this bug happens, the first source window you open other than the markdown does not appear, until you open a second one. I thought my bug description was quite clear.
