### ISSUE TITLE
Feature request : Custom search extension

### ISSUE THREAD

**Issue by giltho** [microsoft/vscode#85113] opened 2019-11-19 11:34 UTC
Hello,
I've tried searching for that issue but I couldn't find it.

I'm trying to write a vscode extension that would create another search view. The syntax for searching/replacing would be using [Comby](https://comby.dev).
I've tried playing with view containers / views, but they only allow tree views for now. I cannot create a view that has input boxes.

Is there a way of doing that ? If not I think it would be a nice enhancement.

Thank you !

**Comment by egamma** [comment] 2019-11-19 14:52
Duplicate of https://github.com/microsoft/vscode/issues/83911

**Closed by egamma** 2019-11-19 14:52 UTC
