### ISSUE TITLE
User settings file overwritten after setting window.autoDetectColorScheme

### ISSUE THREAD

**Issue by Madd0g** [microsoft/vscode#90282] opened 2020-02-08 08:43 UTC
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.2.0

Steps to Reproduce:

1. Edit settings.json, define `workbench.preferredLightColorTheme` and `workbench.preferredDarkColorTheme` and `window.autoDetectColorScheme: true`
2. Switch OSX between dark/light
3. Settings file became empty and contains ONLY 

```json
{
  "workbench.colorTheme": "One Monokai"
}
```
I tried reproducing this again with an empty settings file and it hasn't happened again.

**Comment by sandy081** [comment] 2020-02-20 09:00
Can't reproduce this. Any other steps which I am missing here?

**Comment by Madd0g** [comment] 2020-02-20 09:52
@sandy081 - I couldn't reproduce it again 5 minutes after it happened (and it hasn't happened since then), but since I remembered the exact steps that caused it, I thought I should open an issue just in case.

**Comment by sandy081** [comment] 2020-02-20 10:14
Not sure if I can be helpful without able to repro it.

**Comment by pvinis** [comment] 2020-02-22 07:19
Can I highjack this issue and say that `"workbench.colorTheme"` should not be in the user settings if the automatic switch is on? Or at least it shouldn't be changed by vscode for the user. That file is for me to tell vscode what to do. Not for vscode to tell me what it did. My dotfiles are changing depending on the time of day now, and that's not the way it should be.

**Comment by sandy081** [comment] 2020-02-23 14:26
I would recommend to open a new issue for your new request.

Closing this issue.

**Closed by sandy081** 2020-02-23 14:26 UTC
Labels: needs more info

**Comment by Madd0g** [comment] 2020-03-20 19:09
The settings files just got cleared for me again :(

Steps:

1. I switched to a light mode on my mac (latest catalina)
2. My git commit failed for some tag-related reason, I turned off "fetch all tags when pulling"
3. I got a popup asking me if I want to fetch periodically, I said yes

Somewhere along these steps (step 1 is my guess, since the original problem was with light/dark mode too), my settings file got reset, I'm left with this:

![image](https://user-images.githubusercontent.com/1171003/77197683-dc361700-6aa2-11ea-9602-f096ce7ef723.png)

losing all settings is traumatic, I have only a month old backup at this point, please reopen.

More notes: I had like 6 editors open at once, very likely that the json settings file was open in one of them, I often edit it directly and rarely close tabs.
