### ISSUE TITLE
Add lightbulb refactor helper to move code to an existing file

### ISSUE THREAD

**Issue by mekwall** [microsoft/vscode#88597] opened 2020-01-14 09:26 UTC
I would like to see a lightbulb refactor helper similar to the "Move to a new file" helper but instead move it to an existing file in the code base.

**Comment by mjbvz** [comment] 2020-01-14 20:35
Duplicate of https://github.com/microsoft/TypeScript/issues/29988

**Closed by mjbvz** 2020-01-14 20:35 UTC
