### ISSUE TITLE
Cursor insert position incorrectly moved when window is repositioned

### ISSUE THREAD

**Issue by individuwill** [microsoft/vscode#45539] opened 2018-03-12 02:21 UTC
Issue Type: <b>Bug</b>

# Reproduce
* Put VSCode window in an un-maximized window.
* Open and begin to edit a file of any type (tested python, txt, and go).
* Type some characters or a sentence, and leave the text cursor indicator at the end.
* Use the mouse and move the window in any direction.
* Type your next character.

# Expecting
Text that is typed after the window moves should resume where the cursor insert point was.

# Actual Result
Text cursor insert point is moved back by 1 character for the first character typed, then jumped to the original insert position for the remaining charcters.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (1.86GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
better-toml|bun|0.3.2
githistory|don|0.4.0
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-icons|rob|7.21.0
rust|rus|0.4.0
vscode-lldb|vad|0.8.0
debug|web|0.21.2
jinja|who|0.0.8

</details>
Reproduces without extensions

**Comment by alexandrudima** [comment] 2018-03-26 20:29
@bpasero duplicate of #38163

See https://github.com/Microsoft/vscode/issues/38163#issuecomment-345230613

**Closed** 2019-10-09 08:13 UTC
Labels: *out-of-scope, electron, mac, upstream
