### ISSUE TITLE
After Update to v1.39.1 in Windows 10 Pro All Extensions Stay Disabled

### ISSUE THREAD

**Issue by arsari** [microsoft/vscode#82446] opened 2019-10-13 01:28 UTC
I update VSCode from v1.38.1 to v1.39.1 in Windows 19 Pro and all the extensions were disabled by the update. I enable the extensions but they stay in the Disable section even when they were enabled. I close the program and when open it all the extensions were disabled by the program again. I have a Mac Mojave where I do the update too and this issue does not happen.

**Comment by diego1araujo** [comment] 2019-10-13 02:43
which version of windows are you running? for me its ok on windows 10 pro 1903.

**Comment by arsari** [comment] 2019-10-13 02:44
Windows 10 Pro v10.0.18362 Build 18362

**Comment by lieene** [comment] 2019-10-13 07:39
Same issue here
And i found  node debugger azure pipelines fielded and disabled
![image](https://user-images.githubusercontent.com/575947/66712451-5d400280-edcf-11e9-8b3b-955425050d62.png)

**Comment by jakopo87** [comment] 2019-10-14 09:58
I have the same issue, as workaround i downgraded to 1.38.1 through chocolatey:
`choco install vscode --version=1.38.1`

**Comment by jrieken** [comment] 2019-10-14 12:17
/duplicate of https://github.com/microsoft/vscode/issues/82359

**Closed** 2019-10-14 12:17 UTC
Labels: *duplicate
