### ISSUE TITLE
'${MODULES_SILENT_SHELL_DEBUG:-0}' can not be resolved because the command has no value.

### ISSUE THREAD

**Issue by twiest** [microsoft/vscode#82611] opened 2019-10-15 14:35 UTC
![image](https://user-images.githubusercontent.com/732867/66840876-ba09fd00-ef36-11e9-9dcc-bbb13a0c91dd.png)

When trying to debug a golang program or unit test I get the above error message.

- VSCode Version: code 1.39.1-1570750844.el7.x86_64
- OS Version: Fedora 29 x86_64

Steps to Reproduce:
1. Install code-insiders on Fedora 29 x86_64
2. Enable `go` language extension
3. Attempt to debug either a golang program or a golang unit test
4. Notice the error as in the picture of:
   '${MODULES_SILENT_SHELL_DEBUG:-0}' can not be resolved because the command has no value.

Does this issue occur when all extensions are disabled?: Yes/No
* When I disable extensions and then try to debug a `go` program, I get "Configured debug type 'go' is not supported."

Additional Information:
* I searched the vscode github issues and didn't find anything related.
* I installed code-insiders today and the problem is there as well.
* Multiple people on my team have this exact same problem, so I don't believe it is my setup.
* I downgraded to code-1.38.1-1568209352.el7.x86_64 and `go` language debugging works there.

**Comment by roblourens** [comment] 2019-10-15 16:53
Please file this issue on the vscode-go extension.

**Comment by twiest** [comment] 2019-10-15 18:03
There is already a [bug](https://github.com/microsoft/vscode-go/issues/2831) on the `vscode-go` repo, but this bug seems like it's in `vscode` proper as multiple language (go and python) are showing the same problem.

**Comment by roblourens** [comment] 2019-10-15 18:38
Sounds like it works in 1.38 @isidorn

**Comment by isidorn** [comment] 2019-10-16 09:13
This error is coming from [here](https://github.com/Microsoft/vscode/blob/c417a4874aa901c31bd619ecb7c1219032267290/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L291)
@alexr00 Did we cahnge something how we replace commands in the resolver service?

**Comment by alexr00** [comment] 2019-10-16 09:20
@twiest can you share your launch.json?

**Comment by isidorn** [comment] 2019-10-16 09:34
@twiest aslo why do you say it is a python problem? Is there an open issue for pythong as well? Can you point us to that?

@ramya-rao-a are you adding dynamically commands to the launch.json? Can you please clarify if you add `MODULES_SILENT_SHELL_DEBUG` and if yes how

I was unable to reproduce this using a simplifed approach: I wrote an extension which contributes a command, adds it to the launch configuration in the resolve steps and the command gets nicely resolved.

**Comment by ulodciv** [comment] 2019-10-16 10:19
@isidorn I think @twiest is trying to say that this affects not just Python, but other languages. Since this issue was initially closed, he and I and others mentioned in the [vscode-go issue](https://github.com/microsoft/vscode-go/issues/2831) that this issue arises also with vscode with Python, and seems to happen with version >=1.39

@alexr00  I get the error with no or any launch.json, such as this basic one:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

```

**Comment by isidorn** [comment] 2019-10-16 10:25
@ulodciv I can not reproduce this, your launch config works just fine for me. Can you please aslo open an issue in the vscode python repository so they get aware of this https://github.com/microsoft/vscode-python
@DonJayamanne are you adding MODULES_SILENT_SHELL_DEBUG somehow to the launch configuration. I could not find that string in your repository.

**Comment by ulodciv** [comment] 2019-10-16 10:38
As requested by @isidorn I filed https://github.com/microsoft/vscode-python/issues/8012

**Comment by zaro** [comment] 2019-10-16 12:16
can confirm the same issue with python flask. After I updated vscode to
```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64
```
I see the same message when I try to start debugger with python flask app.

Here is the launch.json, but there were no changes in the launch.json or python version, only vscode update.
```
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true,
            "pathMappings": []
        }
```

**Comment by alexr00** [comment] 2019-10-16 13:33
@zaro, @ulodciv, @twiest do you have a repo I could clone with this issue? We have tried various launch.json and haven't been able to reproduce.

**Comment by DonJayamanne** [comment] 2019-10-16 14:41
> are you adding MODULES_SILENT_SHELL_DEBUG somehow to the launch configuration. I could not find that string in your repository.

No we are not.

**Comment by vholten** [comment] 2019-10-16 14:42
`MODULES_SILENT_SHELL_DEBUG` and `MODULES_USE_COMPAT_VERSION` come from the [environment-modules package](http://modules.sourceforge.net/).

To confirm that this package causes the problems with debugging in VS Code, I partially disabled the environment-modules package by moving the files modules.sh and modules.csh out of /etc/profile.d and rebooted. After rebooting, debugging in VS code worked without problems.

I can't use this as a workaround however because I need the environment-modules package.

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64
```

**Comment by twiest** [comment] 2019-10-16 15:20
> @twiest can you share your launch.json?

@alexr00 [Here](https://github.com/twiest/vscode-workspaces/blob/master/hive/vscode/launch.json#L7-L24) is the launch config that I'm trying to use.

**Comment by ramya-rao-a** [comment] 2019-10-16 15:44
> @ramya-rao-a are you adding dynamically commands to the launch.json? Can you please clarify if you add MODULES_SILENT_SHELL_DEBUG and if yes how. Searching for that string in the Go repository produced no results.

We are not adding any commands dynamically. Either are we adding the MODULES_SILENT_SHELL_DEBUG.

For reference, https://github.com/microsoft/vscode-go/blob/0.11.7/src/goDebugConfiguration.ts#L30 is where we edit the debug configuration. We tweak a few Go related env variables and update some default configurations, that's all.

As per the issue in vscode-go, downgrading VS Code has helped people

**Comment by zaro** [comment] 2019-10-17 07:14
@alexr00 I can't provide you with the repo, but really there is nothing special about this repo, it's simply flask application, and I ave been using the python debugger on it for more than a year, It broke only after upgrading to vscode 1.39.

I do  have environtment-modules installed though my Fedora 30.

**Comment by ulodciv** [comment] 2019-10-17 07:36
My workaround was to remove `environment-modules`:

`sudo dnf remove environment-modules`

Debugging tests works fine now.

**Comment by alexr00** [comment] 2019-10-17 08:19
I have pushed a change I think will fix this issue. Please @ulodciv @zaro @twiest @vholten can you try the next version of our insiders build (https://code.visualstudio.com/insiders/)? I won't be able to verify this otherwise.

**Comment by zaro** [comment] 2019-10-17 08:55
Downloaded the insider build, installed Python extension, and tried to start debugger on my project but I see the same error as before, here is the About from the insiders build:
```
Version: 1.40.0-insider
Commit: 6a2d035b7157cb135b51d2d3ca3b3c0ee0fc4ad6
Date: 2019-10-17T05:28:08.880Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64
```

**Comment by alexr00** [comment] 2019-10-17 09:00
@zaro thanks for trying so fast, but you were too fast for me :) I'm making a build for you to try, but it isn't ready yet.

**Comment by alexr00** [comment] 2019-10-17 10:32
Builds for testing this fix out.
Linux tar:
https://az764295.vo.msecnd.net/insider/99ba33dc9d17e09a5cf427dbb164777780ca8d11/code-insider-1571306968.tar.gz
deb:
https://az764295.vo.msecnd.net/insider/99ba33dc9d17e09a5cf427dbb164777780ca8d11/code-insiders_1.40.0-1571307015_amd64.deb
rpm:
https://az764295.vo.msecnd.net/insider/99ba33dc9d17e09a5cf427dbb164777780ca8d11/code-insiders-1.40.0-1571307162.el7.x86_64.rpm
snap:
https://az764295.vo.msecnd.net/insider/99ba33dc9d17e09a5cf427dbb164777780ca8d11/code-insider-1571307417.snap
Windows:
https://az764295.vo.msecnd.net/insider/99ba33dc9d17e09a5cf427dbb164777780ca8d11/VSCodeSetup-x64-1.40.0-insider.exe

**Comment by zaro** [comment] 2019-10-17 12:22
@alexr00 just tested the Linux Tar, and the debugger started normally for me. The issue is resolved with this build.

**Comment by twiest** [comment] 2019-10-17 13:51
@alexr00 I tested the Linux Tarball release and I was able to debug my go program with it.

Looks like your fixed worked, thanks!

**Comment by alexr00** [comment] 2019-10-17 14:34
@zaro Thank you for testing! Other folks who are seeing this, please use insiders until we can get this fix to stable. I expect it won't make it into stable until the 1.40 release, but if we have another release before that we'll include it.

@weinand FYI.

**Closed by alexr00** 2019-10-17 14:34 UTC
Labels: debug, under-discussion

**Comment by ramya-rao-a** [comment] 2019-10-17 17:12
The Go extension does not use the environment-modules package in `resolveDebugConfiguration`. The only thing it does blindly is read the user provided env variables from settings and apply it to the `env` in the debug configuration.

**Comment by weinand** [comment] 2019-10-17 18:20
@ramya-rao-a the "environment-modules package" is never used directly in VS Code. But this package adds environment variables that VS Code inherits.

@twiest does any of the Python environment variables that you keep in settings contain the `${MODULES_SILENT_SHELL_DEBUG:-0}` pattern?

**Comment by twiest** [comment] 2019-10-17 18:42
@weinand I'm not using python. I'm using golang. For golang, I don't have any environment variables in settings. Here is the [settings.json](https://github.com/twiest/vscode-workspaces/blob/master/hive/vscode/settings.json) file I'm using.

**Comment by weinand** [comment] 2019-10-30 12:12
The error message for undefined variables no longer shows up.
