### ISSUE TITLE
HTML in PHP file

### ISSUE THREAD

**Issue by ArmenPoghosyan** [Microsoft/vscode#10262] opened 2016-08-07 08:04 UTC
- VSCode Version:  1.4.0
- OS Version: Windows 10.14393 x64

In php file, when writing HTML Tags, there is highlighting all same tags, not pairs...
![default](https://cloud.githubusercontent.com/assets/13648747/17461259/0a54a25a-5c97-11e6-8057-f0713e472aa9.PNG)

**Comment by aeschli** [comment] 2016-08-07 20:00
duplicate of https://github.com/Microsoft/vscode/issues/2915

**Closed by aeschli** 2016-08-07 20:00 UTC
