### ISSUE TITLE
GitHub issue notebook on Codespace prompts me to authorize every other minute

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108277] opened 2020-10-07 23:51 UTC
* Browser: Edge
* OS: macOS

While using github issue notebook, I'm prompt with "The extension 'GitHub Issue Notebooks' wants to sign in using GitHub. " every other time when I type or execute a query.

**Comment by RMacfarlane** [comment] 2020-11-03 19:21
Closing as a duplicate of https://github.com/microsoft/vscode-internalbacklog/issues/1588

**Closed by RMacfarlane** 2020-11-03 19:21 UTC
Labels: authentication, bug, important
