### ISSUE TITLE
Overflow menu in notebooks is not clickable

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129703] opened 2021-07-28 16:44 UTC
Issue Type: <b>Bug</b>

WHen clicking the overflow menu, I can't seem to click on it anymore. It just flashes on and off.

VS Code version: Code - Insiders 1.59.0-insider (e437d424c5e6de97632f5513229c7ebc2cf27a32, 2021-07-28T05:13:47.114Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (16.10GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
python|ms-|2021.8.1068685406-dev
vscode-pylance|ms-|2021.7.6-pre.1
jupyter|ms-|2021.8.1074296055
remote-containers|ms-|0.189.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
js-debug-nightly|ms-|2021.7.2717
live-server|ms-|0.2.5
vscode-typescript-next|ms-|4.4.20210727

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by rebornix** [comment] 2021-07-28 16:49
I think this is a duplicate of https://github.com/microsoft/vscode/issues/129587

**Closed** 2021-07-28 16:49 UTC
Labels: *duplicate, notebook

**Comment by rchiodo** [comment] 2021-07-28 16:54
Probably a dupe, but the other bug was in the interactive window. It might be pulling focus on purpose?
