### ISSUE TITLE
WSL default distro Error.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#120522] opened 2021-04-05 01:46 UTC
Issue Type: <b>Bug</b>

At Terminal I change my terminal option select.
If I select my wsl default distro.
It works like "C:\WINDOWS\System32\wsl.exe '-d', Ubuntu(기본값)"

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3311)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (9.84GB free)|
|Process Argv|D:\\06Code\\Raspberry.code-workspace --crash-reporter-id 7e517d39-2a31-4ff6-9306-59b50deeebe1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql-client2|cwe|3.6.7
vscode-markdownlint|Dav|0.40.1
vscode-eslint|dba|2.1.19
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|6.3.1
vscode-pull-request-github|Git|0.25.0
vscode-power-mode|hoo|2.2.0
vscode-sshfs|Kel|1.20.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.6.0
material-product-icons|PKi|1.0.4
vscode-jsp|pth|0.0.3
java|red|0.76.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by mpasteur** [comment] 2021-04-06 15:32
Duplicate of #120321

**Comment by meganrogge** [comment] 2021-04-08 03:32
Duplicate of #120321

**Closed** 2021-04-08 03:33 UTC
Labels: *duplicate
