### ISSUE TITLE
Hide the bottom left branch information and use the reload window function with vscode extension

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#65680] opened 2018-12-26 02:37 UTC
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

1. My plugin has a lot of statusBar, the branch information in the lower left corner is too long, so my own statusBar can't be displayed.
2. I want to use the reload window function in my extension, but I didn't find it on the documentation.
3. I want to add a filter to the treeProvider, similar to the outline search box, but not found in the document.

**Comment by yume-chan** [comment] 2018-12-26 15:12
For 2: Maybe you can invoke the `workbench.action.reloadWindow` command in your extension?

**Comment by octref** [comment] 2018-12-28 01:52
1. AFAIK you can't.
2. As @yume-chan mentioned, you can read https://code.visualstudio.com/api/extension-guides/command and https://code.visualstudio.com/api/references/commands.
3. @sandy081

**Comment by chnliquan** [comment] 2018-12-28 02:16
> For 2: Maybe you can invoke the `workbench.action.reloadWindow` command in your extension?

thanks for your reply, but i can not found the  `workbench.action.reloadWindow` command https://code.visualstudio.com/api/references/commands

**Comment by chnliquan** [comment] 2018-12-28 02:18
> 1. AFAIK you can't.
> 2. As @yume-chan mentioned, you can read https://code.visualstudio.com/api/extension-guides/command and https://code.visualstudio.com/api/references/commands.
> 3. @sandy081

i am not found the command in the links you provider

**Comment by chnliquan** [comment] 2019-01-02 09:20
> from https://code.visualstudio.com/api/references/commands
> 
> > This document lists a **subset** of Visual Studio Code commands ...
> 
> from https://code.visualstudio.com/api/extension-guides/command
> 
> > To find available commands:
> > 
> > * [Browse the keyboard shortcuts](https://code.visualstudio.com/docs/getstarted/keybindings)
> 
> All commands can be invoked by `vscode.commands.executeCommand`, no matter it's built-in or contributed by extensions.
> 
> A full list of commands can be found in the keyboard shortcut editor. I discovered the id of `workbench.action.reloadWindow` command this way.
> 
> ![image](https://user-images.githubusercontent.com/1330321/50500241-f42f0e80-0a8a-11e9-997b-4a57d8c8adf6.png)

i see, thanks a lot

**Comment by sandy081** [comment] 2019-01-03 14:53
Duplicate of https://github.com/Microsoft/vscode/issues/50062

**Closed by sandy081** 2019-01-03 14:53 UTC
Labels: *duplicate, explorer-custom
