### ISSUE TITLE
When Windows is in High Contrast theme, VSCode starts in High Contrast theme and then immediately switches to the right one

### ISSUE THREAD

**Issue by p10tr3k** [microsoft/vscode#98393] opened 2020-05-22 19:07 UTC
Issue Type: <b>Bug</b>

When Windows is in High Contrast theme, VSCode starts in High Contrast theme and then immediately switches to the right one
I didn't notice this issue before.
![VSCodeThemeIssue](https://user-images.githubusercontent.com/11059246/82701289-30f73900-9c70-11ea-859a-5537c1ad6743.gif)

Steps to reproduce:
1. Set Windows theme to dark high contrast

2. Run VSCode

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (23.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.18

</details>

**Comment by isidorn** [comment] 2020-05-26 09:35
This is a theme issue, not an accessibility issue, thus removing tag and myself.
I am not sure where we apply the High Contrast theme automaticallt. @aeschli might know more and provide a code pointer.

**Comment by aeschli** [comment] 2020-08-28 15:21
duplicate of #105489

**Closed** 2020-08-28 15:21 UTC
Labels: themes
