### ISSUE TITLE
Settings editor: File -> Exclude field tabbing issue

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107791] opened 2020-09-30 09:01 UTC
Testing #107610

Add a new exclude pattern. Notice that a lot of stuff is read out that IMO is unnecessary (e.g. workspace name, ....)

**Comment by roblourens** [comment] 2020-10-01 16:26
I don't hear this @dbaeumer. But I do see some other weird tabbing behavior that I will have to look into.

**Comment by roblourens** [comment] 2020-10-06 18:15
@isidorn One issue is that I hear the pattern twice when focusing a row because we set `title` and `aria-label` on the same element and NVDA and Voiceover read both of them. Do you know what best practice is here? It seems like we shouldn't count on `title` alone. Other lists set `title` on a child element, and I could arbitrarily add some child container for `title` here but that's weird.

**Comment by isidorn** [comment] 2020-10-20 15:15
We should set both the `title` and the `aria-label` and it is up to the screen reader to de-dupe this. 
Orca on linux for example handles this correctly. I belive Voice Over also and there is this issue on NVDA side https://github.com/nvaccess/nvda/issues/7841

**Comment by tgriff** [comment] 2022-01-03 16:38
Here's a gif that shows how there is a focusable element at the top of each extension setting page where the screen reader announces the extension's <publisher>.<name>. I would expect "displayName" to be read instead, but it seems as if maybe this element shouldn't be focusable in the first place.
![settings_header_repro](https://user-images.githubusercontent.com/34492055/147955618-9ee5b151-6bd1-4a32-ac3f-0e3045f021e7.gif)

**Comment by rzhao271** [comment] 2022-01-03 19:28
I confirmed that https://github.com/microsoft/vscode/issues/107791#issuecomment-704458164 is fixed in NVDA 2021.3.1 (ref https://github.com/nvaccess/nvda/issues/7841#issuecomment-940227709).
I noticed the glob pattern setting descriptions have links on the text "here", though, and that isn't so good: https://webaccess.berkeley.edu/ask-pecan/click-here.

**Closed** 2022-01-03 20:30 UTC
Labels: bug, accessibility, settings-editor
