### ISSUE TITLE
360 delete tsserver.js

### ISSUE THREAD

**Issue by muyuqiu001** [Microsoft/vscode#20552] opened 2017-02-13 15:21 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.53|

---

Steps to Reproduce:

open VSCode
`路径 c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib 未指向有效的 tsserver 安装。请回退到捆绑的 TypeScript 版本。`

:white_check_mark: 
![image](https://cloud.githubusercontent.com/assets/971514/22889123/069c823a-f243-11e6-8d0a-3651e5ff91f5.png)

**Comment by mjbvz** [comment] 2017-02-13 21:30
Duplicate of #20496 

360 has been causing problems with TypeScript. You have two options:

* Uninstall 360, or at least add the VSCode TypeScript path to its exemption list. The office VSCode downloads ship with the official npm releases of TypeScript. 360 is incorrectly marking these files as trojans for some reason. 
* Install a custom version of TypeScript and [use it with the `typescript.tsdk` setting](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2017-02-13 21:30 UTC
Labels: External
