### ISSUE TITLE
provide profile function for different programming language

### ISSUE THREAD

**Issue by Ikki-Dai** [Microsoft/vscode#69434] opened 2019-02-26 08:08 UTC
Issue Type: <b>Feature Request</b>

provide extension profile for different programming language

it could be a configuration for different profile :
once user choose 'javascript' profile, only plugins such as 'ESlinit', 'javascript code snippets' will be load and while user choose 'java' profile, only 'Java Extension Pack' , 'maven for java' will be load. it doesn't mean install or uninstall, and it could be a 'blind tricks'

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sandy081** [comment] 2019-02-27 15:36
Duplicate of https://github.com/Microsoft/vscode/issues/39272

**Closed by sandy081** 2019-02-27 15:36 UTC
Labels: *duplicate, extensions
