### ISSUE TITLE
file explorer files type icons

### ISSUE THREAD

**Issue by tommasov** [Microsoft/vscode#55758] opened 2018-08-03 12:44 UTC
Issue Type: <b>Feature Request</b>

Vs code should has different icons for common file types when selected as default editor in file explorer.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17723

**Comment by misolori** [comment] 2018-08-03 16:37
Duplicate of #4845

**Closed by misolori** 2018-08-03 16:37 UTC
