### ISSUE TITLE
Pressing 'CTR + NUM+/NUM-' increases/decreases the font size in the search bar of the settings

### ISSUE THREAD

**Issue by TechMky** [Microsoft/vscode#63682] opened 2018-11-23 09:51 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 10 Home Edition version 1803 Build 17134.407

Steps to Reproduce:

1. Click on 'File' --> 'Preferences' --> 'Settings'
2. Type any text in the search bar.
3. Press 'CTR + NUM+/NUM-' multiple times to see the text being increased/decreased and getting clipped.

Initial State:
![capture](https://user-images.githubusercontent.com/25933059/48937055-fb667800-ef32-11e8-907d-36658b48fbdf.JPG)

After using 'CTR + NUM+'
![capture](https://user-images.githubusercontent.com/25933059/48937169-48e2e500-ef33-11e8-85da-9d43bd3c1a84.JPG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-11-26 23:10
Dupe of https://github.com/Microsoft/vscode/issues/58784

**Closed by roblourens** 2018-11-26 23:10 UTC
Labels: search
