### ISSUE TITLE
how to install c# plugin for vscode?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2074] opened 2016-01-18 02:38 UTC
anyone can tell me the details about how to install c# plugin for vscode .

by the way, i have asked question "#2003",but i don't understand the following answer , anyone can help me ?

The source is currently in transit and will move to the OmniSharp org. What you need to do is this:

find the extension folder for ./script/code in your home dir, like ~/.code-oss-build-dev/extension
add a sym link that points to the omnisharp extension (for now from your installation, soon from the github project)

**Comment by isidorn** [comment] 2016-01-18 09:03
This is a duplicate of #2003 please keep the discussion under that issue. Feel free to ask more questions there.

**Closed by isidorn** 2016-01-18 09:03 UTC
