### ISSUE TITLE
On macOS Catalina, when in full screen mode, the traffic light button display is misaligned

### ISSUE THREAD

**Issue by hzbd** [microsoft/vscode#169199] opened 2022-12-15 01:13 UTC
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/3000843/207748941-ba681e18-6e35-459e-a8f0-6766c374436f.png">

The first full screen display works fine. But when switching to other windows page, the traffic lights cannot be fully displayed when switching back.

- VS Code Version: 
```
Version: 1.74.1 (Universal)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 19.6.0
Sandboxed: No
```
- OS Version: 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/3000843/207748294-f1d245ba-383e-46a2-b9b2-79cade376596.png">

**Comment by hzbd** [comment] 2022-12-15 01:13
https://github.com/microsoft/vscode/issues/159862

**Comment by TLovers** [comment] 2022-12-21 06:43
<img width="275" alt="image" src="https://user-images.githubusercontent.com/26561694/208838369-06a629ae-5771-4585-a774-7943d5c94183.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/26561694/208838754-c6c08c17-dfb0-428f-911d-9590dd7b525d.png">
same problem

**Comment by rzhao271** [comment] 2023-01-25 00:06
I'm unable to reproduce the issue on 1.74.3 on Catalina on Parallels.
I'm wondering how you switched between the full screen windows?

**Comment by hzbd** [comment] 2023-01-25 13:17
At this time, homebrew no longer supports macos Catalina, and it will cause many problems when installing other software. So I decided to solve this problem by upgrading macos version(to 12.6.2) .

**Comment by deepak1556** [comment] 2023-01-25 13:35
Thanks for the follow-up, closing per https://github.com/microsoft/vscode/issues/169199#issuecomment-1403593340

**Closed by deepak1556** 2023-01-25 13:35 UTC
Labels: bug, info-needed, macos-catalina, confirmation-pending
