### ISSUE TITLE
Also disable the dependencies of the extension 'X'?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#56073] opened 2018-08-09 10:52 UTC
This question is bizzare and I don't understand why we would offer to do this.

Steps:
* install https://github.com/Microsoft/vscode-pull-request-github from the Releases vsix
* [use it...]
* decide you want to disable it for now
![image](https://user-images.githubusercontent.com/5047891/43894595-e48e7564-9bd2-11e8-8290-7bd6fd32bf2d.png)

Why would I ever want to disable dependencies which **are not named** and in this case it would be the built in git extension? See [here](https://github.com/Microsoft/vscode-pull-request-github/blob/fc6013905f315a9ea40df3e92649c82d0a5584a7/package.json#L22-L24)

This is super bizzare and IMHO we should remove this popup from the product, I don't understand why we would ever implement such a thing.

**Comment by sandy081** [comment] 2018-08-13 11:52
Duplicate of #55072

**Closed** 2018-08-13 11:52 UTC
Labels: *duplicate, extensions
