### ISSUE TITLE
Code mangles PATH variable that it's opened with

### ISSUE THREAD

**Issue by alexwhittemore** [Microsoft/vscode#56125] opened 2018-08-10 02:38 UTC
Using Insiders, just to be certain (impacts current release also)

- VSCode Version: 1.26.0-insider
- OS Version: macOS 10.13.6

Steps to Reproduce:
With a completely virgin install of macOS
1. At a system terminal, set $PATH to something interesting, then launch code:
```
extra-super-virgin-macos:~ alexw$ export PATH="/Users/alexw/Desktop:$PATH"
extra-super-virgin-macos:~ alexw$ echo $PATH
/Users/alexw/Desktop:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
extra-super-virgin-macos:~ alexw$ code-insiders --disable-gpu
```
2. In the vscode integrated terminal, show $PATH:
```
extra-super-virgin-macos:~ alexw$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexw/Desktop
```
That is to say, somehow, at some point, Code is taking the first item(s?) in my PATH and tacking them on the end instead, which, of course, alters the entire behavior of any shells with the altered version.

Does this issue occur when all extensions are disabled?: Yes (none installed at all)

**Comment by alexwhittemore** [comment] 2018-08-10 02:46
Does not seem to be related to 30847.

**Comment by ramya-rao-a** [comment] 2018-08-11 20:40
What do you see when you type `process.env['PATH']` in the console? Help -> Toggle Developer Tools -> Console

**Comment by alexwhittemore** [comment] 2018-08-11 23:18
The same- whatever my base system path is, with whatever prepended customizations somehow appended instead.

**Comment by alexwhittemore** [comment] 2018-08-12 20:46
In a system terminal (looks like VMWare did something since last I was testing this):
```
Alexs-MBP-2018:~ 
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public
Alexs-MBP-2018:~ 
› bash -l
Alexs-MBP-2018:~ 
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public
```
typically I'd `workon my_env; code .`

When I do that, I get this in the Code terminal:
```
Alexs-MBP-2018:~/Development/Python/Plotter
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/alexw/.virtualenvs/py3_plotter/bin
Alexs-MBP-2018:~/Development/Python/Plotter
› bash -l
Alexs-MBP-2018:~/Development/Python/Plotter
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/alexw/.virtualenvs/py3_plotter/bin
```

I'm not quite sure what `bash -l` is supposed to accomplish; it doesn't seem to be doing anything interesting.

**Comment by Tyriar** [comment] 2018-08-13 17:59
@alexwhittemore can you also try this?

```bash
echo $PATH
export PATH="/Users/alexw/Desktop:$PATH"
bash -l
echo $PATH
```

I'm trying to identify whether code is running your login shell script again which is pushing `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` to the front of `$PATH`.

Relevant code pointer:

https://github.com/Microsoft/vscode/blob/5e5f6fc6ec785a602f1444500264f18d136b5e87/src/vs/code/node/shellEnv.ts#L78-L95

**Comment by alexwhittemore** [comment] 2018-08-13 18:59
Ohhhhhhh interesting. That certainly looks to be what's happening:

```
Alexs-MBP-2018:~ 
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public
Alexs-MBP-2018:~ 
› export PATH="/Users/alexw/Desktop:$PATH"
Alexs-MBP-2018:~ 
› bash -l
Alexs-MBP-2018:~ 
› echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/alexw/Desktop
```

**Comment by segevfiner** [comment] 2018-08-13 23:04
Related/duplicate of https://github.com/Microsoft/vscode/issues/55144 ?

**Comment by alexwhittemore** [comment] 2018-08-13 23:45
@segevfiner I'm not sure about duplicate, but it sounds like it's related enough that perhaps your PR fixes it? 

I've never compiled so much as an electron hello world, so I'm not sure how to go about testing your PR myself, but if I get a little more time than I have now, I'll look into it. 

In the mean time, if you'd be willing to try it for me, the test case is pretty straightforward:

(system terminal:)
``` bash
$ export PATH=~/Desktop:$PATH
$ echo $PATH
# should spit back "/Users/You/Desktop:/rest/of/your/PATH"
$ code .
```
(at code integrated terminal:)
``` bash
$ echo $PATH
# if failed:
# /rest/of/your/path:/Users/You/Desktop
# If fixed:
# /Users/You/Desktop:/rest/of/your/path
```

**Comment by alexwhittemore** [comment] 2018-08-16 23:04
Hmm @segevfiner I just noticed a behavior that does make this seem highly related - if I launch `code .` from a separate terminal NOT in a virtualenv, code adopts the environment of the first-opened window. In my case, that one was opened inside a virtualenv, and has a mangled path and the $VIRTUAL_ENV set.

**Comment by Tyriar** [comment] 2018-08-21 22:53
@alexwhittemore I think given that bash -l repros this, you should be able to fix this by tweaking your launch scripts, you want to make them idempotent (don't break things if they're run multiple times).

**Closed by Tyriar** 2018-08-21 22:53 UTC
Labels: integrated-terminal, needs more info

**Comment by alexwhittemore** [comment] 2018-08-22 00:04
I think I'm confused - what launch scripts? And what about them would take a perfectly fine path and do this nonsense to it?

**Comment by Tyriar** [comment] 2018-08-22 18:40
Linux handles the profile and rc scripts differently and imo in a superior way, Windows is completely different so I do think this is a mac only problem. Here are the main differences:

- Linux will run your *profile* script (ie. the login script) when you login to the system, when you launch a terminal Linux will run your .bashrc file
- macOS will run your *profile* script when you launch a terminal

This caused a whole bunch of headaches a long time ago and I eventually caved and make macOS launch a login script within the terminal https://github.com/Microsoft/vscode/issues/20145#issuecomment-278172268, but that causes a whole bunch of other issues.

I don't normally do what you're trying to do, but I'm sure there's a proper way you're meant to do it. I also recommend reading up on the difference between `.bashrc`/`.bash_profile` and login shells/non-login shells.

**Comment by Tyriar** [comment] 2018-08-22 18:57
Related: https://github.com/Microsoft/vscode/pull/55194

**Comment by alexwhittemore** [comment] 2018-08-23 03:16
So I think the end result here is that two things are conspiring against my "virtualenv + code ." workflow, making it nowhere near as effective on Mac as on Win or Linux:

1) path_helper does awful things to a pre-existing $PATH variable, re-ordering PATH for any shell opened as login ("Why ever would you want your PATH to have the same order?! I'm a LOGIN shell! The original shell! The SUPREME shell!"). I can't simply disable path_helper, since other things expect it to be functional. And therefore it will be a pain in my neck forever, so long as Code needs to start in a login shell.

I can work around that at least a couple different ways - set a breadcrumb like OLD_PATH when I activate a virtualenv, and restore that to $PATH in bashrc. Or detect custom path items and blindly restore them to the front of the line. Or, application-specific, detect VIRTUAL_ENV and reactivate it blindly.

But then despite any of those, I still run into

2) Code windows don't support independent, differing environments. Subsequently-opened windows always inherit environment variables from the existing windows, and that will forever break, for example, working on two different virtualenvs in two different windows.

So I guess the Code workflow is just inherently worse on Mac than Windows, until there's first-class support for virtualenvs in the vscode Python plugin :(

**Comment by Tyriar** [comment] 2018-08-23 18:11
I'd recommend joining the discussion over at https://github.com/Microsoft/vscode/issues/15452, also for Python specifically I'm not sure if the python extension has a nice workaround for handling virtualenv or not https://github.com/Microsoft/vscode-python

**Comment by alexwhittemore** [comment] 2018-08-23 18:15
> also for Python specifically I'm not sure if the python extension has a nice workaround for handling virtualenv or not 

My understanding is, at this juncture, it's a discussion-in-progress.

**Comment by segevfiner** [comment] 2018-08-23 18:34
> I'd recommend joining the discussion over at #15452, also for Python specifically I'm not sure if the python extension has a nice workaround for handling virtualenv or not https://github.com/Microsoft/vscode-python

They have a separate "Create Terminal" command that creates a terminal with the active Python environment. But due to API limitations, this is a separate command and as such by default terminals are created using VS Code's environment via the default command.

**Comment by Tyriar** [comment] 2018-08-23 20:07
@segevfiner sure, you could replace the keybinding though if it's all you want to use:

```json
{ "key": "ctrl+`", "command": "thepythoncommand" }
```

You can even make this the default only when you have a Python file opened:

```json
{ "key": "ctrl+`", "command": "thepythoncommand", "when": "editorLangId == 'markdown'" }
```
