### ISSUE TITLE
[html] Accepting intellisense suggestion replaces text

### ISSUE THREAD

**Issue by ranjithkt** [microsoft/vscode#67948] opened 2019-02-05 22:34 UTC
About editor-acceptSuggestion:

When editing HTML document, I get intellisense suggestions for tags and attributes, but when I press "Tab" (or "Enter"), it replaces the text which is just rightside of the cursor. Lets say I have a list item "&lt;li&gt;Go back&lt;/li&gt;" and if I want to change the text inside the list to a link, I move the cursor between ">" an "G" to start typing. I type "<a" and the editor shows suggestion, now I press Enter. Now the text becomse "&lt;li&gt;<a back&lt;li&gt;" instead of "&lt;li&gt;<aGo back&lt;li&gt;". It just replaces the text beside the cursor instead of inserting the suggestion. This makes it very hard while editing code, I have to always make sure there is a space beside the cursor before accepting a suggestion. Can you please provide a setting for this if not everyone can agree on this?

**Comment by octref** [comment] 2019-02-13 06:57
@aeschli I argue we should drop cases like `<d|iv></div>` completion and make the completion not replacing what's after the cursor, what do you think?

**Comment by aeschli** [comment] 2019-07-18 11:10
duplicate of #41206

**Closed by aeschli** 2019-07-18 11:10 UTC
Labels: html, under-discussion
