### ISSUE TITLE
Copy files directly between remote and local when using remote-development

### ISSUE THREAD

**Issue by Michaelvll** [microsoft/vscode#75151] opened 2019-06-09 14:29 UTC
Hi, 
I am wondering if it is possible to download and upload files and folders by directly dragging them between the local machine and the remote workspace when using remote development. It would be nice to have that. :)

**Comment by egamma** [comment] 2019-06-10 08:11
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/393

**Closed by egamma** 2019-06-10 08:11 UTC
Labels: *duplicate
