### ISSUE TITLE
Collapsible region expansion in editor is broken

### ISSUE THREAD

**Issue by sivadeilra** [microsoft/vscode#136801] opened 2021-11-09 22:15 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I just allowed VS Code to upgrade. After upgrading, I opened an existing project. VS Code re-loaded all of its state, including whether specific regions are collapsed or not in a specific file.

One region is collapsed, but I can't get the editor to expand the region. The |> expansion control isn't being shown, when I hover near the line numbers. I basically can't edit this file any more.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22481
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3990X 64-Core Processor  (64 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.88GB (161.77GB free)|
|Process Argv|d:\\ruget --crash-reporter-id 84c0d38f-5ad4-4c41-8add-7d96991638c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
midl3-language-server|Ale|0.0.26
gitlens|eam|11.6.1
rust-analyzer|mat|0.2.809
vscode-azdo-codereview|Mic|1.2020.1217001
vscode-nmake-tools|Mic|4.0.211025002
wavework|Mic|1.2021.1026007
prettify-json|moh|0.0.3
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
sarif-viewer|MS-|3.0.2
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
powershell|ms-|2021.10.2
crates|ser|0.5.10
sort-lines|Tyr|1.9.0
vscode-lldb|vad|1.6.10
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-10 04:43
/gifPlease

Also, please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Zereges** [comment] 2021-11-15 13:23
I am facing the same issue. With Extension bisect I identified this
![image](https://user-images.githubusercontent.com/7399594/141787505-b1bb3a57-2c9a-4da2-8c4d-ee6a02a7b767.png)

It can be reproduced by opening a workspace containing a single file (i.e. HelloWorld.cs with classes (no C#10)) like `code WorkSpace WorkSpace/HelloWorld.cs`. The VS opens the workspace and file and collapsing/expanding sections of code works for few seconds (until said extension initializes, I assume) and then it disappears.

![image](https://user-images.githubusercontent.com/7399594/141789056-f1150367-7999-4b80-bdec-a39c2db97394.png)

few seconds later

![image](https://user-images.githubusercontent.com/7399594/141789064-4771ce19-16df-4fe4-a01d-7323e2c1a423.png)

Sorry, but windows can't take a screenshot with a mouse pointer visible.

**Comment by Zereges** [comment] 2021-11-29 15:19
Any updates? Still in need for more info? @gjsjohnmurray

**Comment by gjsjohnmurray** [comment] 2021-11-29 16:06
> Any updates? Still in need for more info? @gjsjohnmurray

Issue is assigned to @aeschli

**Comment by aeschli** [comment] 2021-11-29 16:57
Looks like the the csharp extension does not return a folding range. 
Can you file the issue here: https://github.com/OmniSharp/omnisharp-vscode/issues ?

**Comment by aeschli** [comment] 2021-11-29 16:57
Looks like the the csharp extension does not return a folding range. 
Can you file the issue here: https://github.com/OmniSharp/omnisharp-vscode/issues ?

**Closed by aeschli** 2021-11-29 16:57 UTC
Labels: needs more info

**Comment by sivadeilra** [comment] 2021-11-29 20:31
This is still happening, with _all_ language services, on my system.  C++ and Rust both support collapsible regions, but it's not working in VS Code any more.

What information can we provide to help you diagnose this?
