### ISSUE TITLE
Completion selection change unexpected

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode#41501] opened 2018-01-12 02:01 UTC
I think this is relate to the [smarter Intelisense](https://code.visualstudio.com/updates/v1_19#_smarter-intellisense),
> In this release, we've updated IntelliSense to remember what you have selected in such cases. Select const for the con prefix once and it will be the top match in the future.
which supposed to we have option to disable it.

I expecting still on the top selection, but somehow the selection jump to the bottom. 
Relate to: https://github.com/Microsoft/vscode-go/issues/1444

Normal behavior, if I want to select other I will navigate using the cursor or type more to narrow the options. This is just fine.

But selection jump from one to another is unexpected.

- VSCode Version: 1.19.1
- OS Version: macOS high Sierra 10.13.2

Steps to Reproduce:

1. See the video
![completion-selection-jump-to-bottom](https://user-images.githubusercontent.com/166053/34856082-ca96a7a0-f775-11e7-9930-785dbf677cb6.gif)

Does this issue occur when all extensions are disabled?: Yes/No (hasn't test yet)

**Comment by jrieken** [comment] 2018-01-12 15:44
dupe of https://github.com/Microsoft/vscode/issues/41060

**Closed by jrieken** 2018-01-12 15:44 UTC
Labels: editor
