### ISSUE TITLE
VS Code tries to get Call Stack data after a breakpoint resumption

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode#103611] opened 2020-07-30 07:51 UTC
- VSCode Version: 1.47.3
- OS Version: macOS 10.15.5

Hello, this is [Cordova Tools](https://github.com/microsoft/vscode-cordova) team. Now we are reimplementing the debugger within the extension with [vscode-js-debug](https://github.com/microsoft/vscode-js-debug) usage.
While debugging some applications (e.g. [Ionic](https://ionicframework.com/) Angular based) we faced such a behavior that after a breakpoint resumption VS Code sometimes opens additional tab with a source script. For example like this one:
![image](https://user-images.githubusercontent.com/33267199/88888610-4fb51580-d247-11ea-83c3-2ffb4d92a75f.png)
We found out that this happens if we try to resume a breakpoint within 2-3 second after the stop. If we wait a bit more after the stop, VS Code won't open a tab with a source code after a resumption. We also found [the code](https://github.com/microsoft/vscode/blob/1.47.3/src/vs/workbench/contrib/debug/browser/debugSession.ts#L784-L815) that handles stop events. Then we tried to debug it and revealed that for some reasons the `onDidStop` handler continues to work after a breakpoint resumption. In such a situation [this condition](https://github.com/microsoft/vscode/blob/1.47.3/src/vs/workbench/contrib/debug/browser/debugSession.ts#L809) becomes `true` (since `focusedStackFrame` is `undefined`), and then in [this part of the code](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/debugSession.ts#L798-L809) VS Code sends to `js-debug` debugger the `Source` request, and the debugger sends the `Debugger.getScriptSource` request to an application. Thus, we get a source script after a breakpoint resumption.
It seems that there might be some conflicts in async functions work and data sharing between them in `js-debug`.
Could you please tell us what can we do to fix it?
We can provide a demo if needed.

**Comment by isidorn** [comment] 2020-07-30 09:07
Hi, thanks for filling this. First forwarding to @connor4312 as he owns js-debug

If you would like us to investigate more on the vscode side it would be great if you fork and make changes to mock debug so we can reproduce this issue locally https://github.com/microsoft/vscode-mock-debug

**Comment by connor4312** [comment] 2020-07-30 19:28
@RedMickey are you able to collect a `trace: true` log from js-debug? That would help us clearly see the order of events here.

From what you're saying it sounds like the issue lies in the VS Code side of things with js-debug acting as a simple server responding to its requests, but the log will help us determine what's happening with greater certainty.

**Comment by RedMickey** [comment] 2020-07-31 08:40
Hi, @connor4312, I attach logs:
- [`js-debug` logs](https://github.com/microsoft/vscode/files/5005960/vscode-debugadapter-0.json.gz)
- [CDP proxy logs](https://github.com/microsoft/vscode/files/5005965/logCor6318.txt)

**Comment by connor4312** [comment] 2020-07-31 15:04
Okay, thanks. This looks like maybe a VS Code bug.

1. We get a stopped event
1. VS Code requests and we respond with the first stack frame, which exists in a file on disk
1. Immediately after VS Code asks for the rest of the stack trace, the user also requests the debugger to continue
1. We respond with the remaining stack trace. 
1. Then it looks like VS Code tries to open the first frame in that trace (i.e. the second stack frame) 🐛 

![](https://memes.peet.io/img/20-07-66299dcc-a24c-4a1e-8d28-c6fd27d3af32.png)

cc @isidorn. I can probably make some synthetic example with js-debug or mock-debug if it would be helpful

**Comment by isidorn** [comment] 2020-07-31 15:11
@connor4312 if it is not too much effort a repro with js-debug or mock-debug would be helpful.
Alternative here's the code that fetches the callstack, there are some timeouts so I understand how an unexpected thing might happen in some corner case
https://github.com/microsoft/vscode/blob/a3dd5c3b75b2a8c3523ae0dc9828c2391bdc723e/src/vs/workbench/contrib/debug/common/debugModel.ts#L928

**Comment by connor4312** [comment] 2020-08-03 16:51
Here's a branch: https://github.com/microsoft/vscode-mock-debug/tree/async-stack-ordering-bug

I tested it by using the default config with `stopOnEntry` 'debugging' the mock debug readme.

**Comment by isidorn** [comment] 2020-08-03 17:33
@connor4312 thanks, assigning to me and to July so I investigate more.

**Comment by isidorn** [comment] 2020-08-05 14:14
@connor4312 just looked into your repro, and for me it works just fine. I start debugging with `stopOnEntry` the readme.md in mock repository and I can properly step over statements and they get nicely rendered. Am I doing something wrong?

@RedMickey @connor4312  Also you can not repro if delayed [stack trace loading](https://github.com/microsoft/vscode/blob/1a2a371c487d29b6dec33579c5f106f53a9d7fb7/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L1573) is set to false, correct.

![recording (1)](https://user-images.githubusercontent.com/1926584/89423161-75a25480-d736-11ea-8838-1d0be2140b62.gif)

**Comment by connor4312** [comment] 2020-08-05 15:29
Try just clicking 'continue' after you stop on the first line

**Comment by isidorn** [comment] 2020-08-12 15:03
Thanks for the repro case.
I have pushed a fix for this. Now the stack trace will also respect `CancellationTokens`, which means if the user presses continue vscode will send a `cancel` request to the debug adapter and will ignore any late responses from the debug adapter.

I have verified that this fixes the repro case.
@RedMickey it would be great if you can also try this with latest vscode insiders from Friday (since then this should be released) and then let us know if it is ok for you. Thanks

**Closed** 2020-08-12 15:13 UTC
Labels: debug

**Comment by SounD120** [comment] 2020-08-14 08:59
Hi @isidorn . Tested in both Mock Debug and Cordova Tools scenarios. Doesn't reproduces anymore. Thank you.

**Comment by isidorn** [comment] 2020-08-14 09:00
@SounD120 thanks for letting us know. Adding verified label.
