### ISSUE TITLE
The minimap in Datk Theme

### ISSUE THREAD

**Issue by qishengmoming** [microsoft/vscode#138391] opened 2021-12-03 07:19 UTC
Issue Type: <b>Feature Request</b>

The minimap on the right side of the editor will make the navigation block where the current page is located invisible in the case of dark theme
![image](https://user-images.githubusercontent.com/68181938/144563396-410d1402-41da-4e54-9197-4fb2e866920c.png)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alexdima** [comment] 2021-12-03 14:16
@qishengmoming I am not sure I understand what the problem is. From the attached screenshot, everything looks in order.

**Comment by qishengmoming** [comment] 2021-12-04 02:14
What I’m trying to say is that under the light color theme, it’s easy to see the gray block in the minimap that indicates the current page, as shown in the image below, while the gray block in the dark mode is not so easy to be seen.
![image](https://user-images.githubusercontent.com/68181938/144693334-377c2e25-0cb6-4708-baac-0ddd9334f7a7.png)

**Comment by alexdima** [comment] 2021-12-07 09:22
These colors are customizable. Their names are:
* `minimapSlider.background`
* `minimapSlider.hoverBackground`
* `minimapSlider.activeBackground`

@misolori assigning to you if you think we need to tweak these colors for our default themes.

**Comment by misolori** [comment] 2022-02-03 17:39
This really depends on the file you have open:

<img width="308" alt="CleanShot 2022-02-03 at 09 38 22@2x" src="https://user-images.githubusercontent.com/35271042/152397863-59fe8f7a-0a2c-4430-98a8-f40477d840ea.png">

As Alex has mentioned there are certain color tokens you can use to tweak them to your liking and there are other themes available as well. Appreciate the feedback and if this theme continues to re-appear we can take a look again.

**Closed by misolori** 2022-02-03 17:39 UTC
