### ISSUE TITLE
Failed to create file or rename to 'aux'

### ISSUE THREAD

**Issue by asssrias** [microsoft/vscode#235704] opened 2024-12-10 07:26 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Win11 24H2 26100.2314

Steps to Reproduce:

1. Create new file or just rename, and name as 'aux.h' or 'aux.cpp'
2. Show 'The name aux is not valid as a file or folder name. Please choose a different name.' Failed to save file

**Comment by ZooDoo4U** [comment] 2024-12-10 07:59
Honestly this sounds like the issue is by design...  Windows has reserved file name , without looking further you'll have this errors with:

prn
aux 
con

Old age... I thought there are 5 i can only remember 3....   Searching...

Do not use the following reserved names for the name of a file:
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

**Comment by asssrias** [comment] 2024-12-10 08:05
> Honestly this sounds like the issue is by design... Windows has reserved file name more a hold over from MS-DOS, and backward compatibility... Wiithout looking further you'll have this errors with:
> 
> prn aux con
> 
> Old age... I thought there are 5 i can only remember 3.... Searching, i found...
> 
> Do not use the following reserved names for the name of a file: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

Thx. I try to manually rename to 'aux.h' in file explorer, and it success. But when I create a folder name 'aux', it shows an errror. I think 'aux.h' is legal as file name.

**Comment by ZooDoo4U** [comment] 2024-12-10 13:31
Either way i don't think even using the file name portion at all is wise exactly for the reason mentioned be it a file or dir,  I would think this will be closed by design...

**Closed** 2024-12-16 19:39 UTC
Labels: windows, *as-designed
