### ISSUE TITLE
"javascript.suggest.completeFunctionCalls" but without parameter signature.

### ISSUE THREAD

**Issue by RayPS** [microsoft/vscode#111084] opened 2020-11-21 09:24 UTC
<img width="587" alt="Screen Shot 2020-11-21 at 17 18 17" src="https://user-images.githubusercontent.com/1941540/99873062-91feca00-2c1d-11eb-974b-a9351ac63c3e.png">

When `"javascript.suggest.completeFunctionCalls"` is enabled, VS Code always complete its parameter signatures, doesn't that conflict with the **ParameterHints** feature?
It would be nice if we have another option for it instead of just on and off.
For example:
```javascript
{
    "javascript.suggest.completeFunctionCalls": "always",
    "javascript.suggest.completeFunctionCalls": "withoutParameterSignature",
    "javascript.suggest.completeFunctionCalls": "never"
}
```
After:
<img width="551" alt="Screen Shot 2020-11-21 at 17 20 34" src="https://user-images.githubusercontent.com/1941540/99873861-ec982600-2c1d-11eb-9080-98c440fb7582.png">

**Comment by mjbvz** [comment] 2020-11-24 08:03
Duplicate of #109997

**Closed by mjbvz** 2020-11-24 08:03 UTC
