### ISSUE TITLE
Support undo a WorkspaceEdit

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#77190] opened 2019-07-11 09:04 UTC
VS Code client supports applying two kinds of changes in a workspace edit:
- text change
- resource change (CreateFile | RenameFile | DeleteFile)

But when the user is clicking `ctrl+z`, it only undo the text changes from currently opened file, not all changes from a workspace edit. Even don't support undo file operations such as CreateFile/RenameFile/DeleteFile at all.

Usually from the perspective of a user, i will consider all changes caused by one UI operation as a action unit, they should be applied or undo together instead of separately.

**Comment by OrkhanAlikhanov** [comment] 2019-07-11 09:37
Just for information, in IntelliJ undo stacks are separate for project tree (explorer) as well as for each file.

**Comment by Eskibear** [comment] 2019-07-11 15:16
I need this too. 
I'm working on implementing a quickfix code action that creates a class for Java users. That is, actually, to create a file and fill in some snippet. Currently I can use a WorkspaceEdit to 1) create a file, 2) insert some content. But it's impossible to undo them together, the created file won't be deleted.  By undo the action, the user finally has the empty file left, which is not expected.

**Comment by jrieken** [comment] 2020-09-29 15:09
done. actually dupe of https://github.com/microsoft/vscode/issues/101789

**Closed by jrieken** 2020-09-29 15:09 UTC
Labels: feature-request, undo-redo, workspace-edit
