### ISSUE TITLE
VS Code "and still" won't open in a Linux xrdp session

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#35530] opened 2017-10-03 15:14 UTC
I still can't believe that twice this issue has been closed without any resolution:
https://github.com/Microsoft/vscode/issues/12233
https://github.com/Microsoft/vscode/issues/27369 

In my own opinion, this still an open issue!

So, if a Windows Admin decide to remote connect to a Linux box, so they can't use VS Code. 

- VSCode Version: 1.17.0
- OS Version: Ubuntu 16.04.3

Steps to Reproduce:

1. Setup *xrdp:
```
sudo apt-get install tightvncserver
sudo apt-get install xrdp
sudo apt-get install xubuntu-desktop
echo "xfce4-session" > ~/.xsession
sudo gedit ~/.xsession
sudo service xrdp restart
```
*note: It's known that xrdp works only on 2D desktops, so either MATE and xubuntu need to be installed.

2. From Windows use RDP app to connect to Linux.

3. Open Code, but won't open and there are no errors displayed.

Workaround:
This time around I resolved the issue by narrowing the following Hack in two steps:

1. Copy the system file 'libxcb.so.1.1.0' to the VS Code Insider folder:
```
copy /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/share/code-insider
```
2. Last execute the sed stream editor command to alter value:
```
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/share/code-insider/libxcb.so.1.1.0
```
After these step were completed, I was able to open VS Code Insider on a xrdp session.
must important I didn't have to alter the system file "libxcb.so.1.1.0" as in previous posts was done in the "/usr/lib/x86_64-linux-gnu/" location.

(Below image shows implemented hack)
![xrpd_vscode](https://user-images.githubusercontent.com/19892435/31132367-9bc62c56-a82a-11e7-94cb-16a3db125d2b.png)

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment] 2017-10-03 15:28
We seem to be tracking this as #3451 as you might be aware.

**Comment by MaximoTrinidad** [comment] 2017-10-03 17:02
Hi @chrmarti,

Thanks for the heads up!

:)

**Comment by chrmarti** [comment] 2017-10-04 18:08
I'm closing this as a duplicate of #3451. This is not to say that it is fixed, but that there already is an issue tracking it.

**Closed by chrmarti** 2017-10-04 18:08 UTC
Labels: install-update
