### ISSUE TITLE
Adding new cell toolbar is not discoverable when there is just one cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96559] opened 2020-04-29 11:11 UTC
#96279

![Kapture 2020-04-29 at 13 10 36](https://user-images.githubusercontent.com/10746682/80589644-dc6af000-8a1a-11ea-98c4-831193841a2e.gif)

**Comment by rebornix** [comment] 2020-06-29 21:32
/duplicate of https://github.com/microsoft/vscode/issues/96446 .

**Closed by rebornix** 2020-06-29 21:32 UTC
Labels: notebook, polish, ux
