### ISSUE TITLE
can‘t find Git

### ISSUE THREAD

**Issue by screamsyk** [Microsoft/vscode#40240] opened 2017-12-15 01:56 UTC
- VSCode Version:1.19
- OS Version:

Steps to Reproduce:

1.I install Git in E
2.Update VSCode to 1.19
3.Open my file ,can't find git in C
4. Other version of VSCode can find Git

Reproduces without extensions: Yes/No

**Comment by auchenberg** [comment] 2017-12-15 02:18
Most likely a duplicate of https://github.com/Microsoft/vscode/issues/40240

**Comment by ramya-rao-a** [comment] 2017-12-15 02:53
This is being tracked in #40229

**Closed by ramya-rao-a** 2017-12-15 02:53 UTC
Labels: git
