### ISSUE TITLE
consider a "cleanupTask" for launch configs

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#44285] opened 2018-02-23 16:46 UTC
From @chrisdias:
Scenario: Shut down function runtime after debugging

This "cleanupTask" task would run after the debuggee has terminated.
In case of a restarted session, it would run at the very end, not on every "restart".

The "cleanupTask" would be predefined attribute of every "launch" config (and maybe of every "attach" config too).

@chrisdias Please note that this is different from the "postLaunchTask" which runs after the debuggee has started. So this feature request is not a duplicate of https://github.com/Microsoft/vscode/issues/2405.

**Comment by isidorn** [comment] 2018-02-23 18:46
Duplicate of https://github.com/Microsoft/vscode/issues/11522

**Closed by isidorn** 2018-02-23 18:46 UTC
Labels: debug, feature-request
