### ISSUE TITLE
Sourcemaps (breakpoints) when attaching to a node process don't seem to work anymore

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#67895] opened 2019-02-04 22:36 UTC
Issue Type: <b>Bug</b>

They still work fine in 1.30. I also checked the `.scripts` output and it looks like the sourcemap is getting used and the file mappings are correct, so I'm really unsure what is going on. I also verified the `.scripts` outputs the same in 1.30 as 1.31 and 1.30 works, but 1.31 doesn't.

VS Code version: Code - Insiders 1.31.0-insider (5ab047b584d974033e0c5ce529ea74a869355b87, 2019-02-04T15:32:22.547Z)
OS version: Windows_NT x64 10.0.18329

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment] 2019-02-05 02:49
Silly vscodebot, this is not terminal related.
/cc @isidorn @weinand

**Comment by corbob** [comment] 2019-02-05 03:41
I don't know if this is related, but if feels related: I just found that I cannot set breakpoints in TypeScript files in insiders. I can still set breakpoints in C# and PowerShell files though.

I have same insiders build as eamodio and same Windows version.

**Comment by weinand** [comment] 2019-02-05 09:04
@corbob do you really mean "I cannot set breakpoints" or are you just not hitting breakpoints?

**Comment by eamodio** [comment] 2019-02-05 09:12
I can set them, they just show up as `unverified` and won't break

**Comment by weinand** [comment] 2019-02-05 09:17
@eamodio I cannot reproduce this problem with the latest Insiders on Windows for the "hello world" extension. Do you see the issue with Extension debugging or when debugging a plain TypeScript project?

**Comment by eamodio** [comment] 2019-02-05 09:20
@weinand I only see it when attaching to a node process, e.g. a language server

**Comment by weinand** [comment] 2019-02-05 10:37
Hitting breakpoints works for me (at least on macOS) when following these steps:
* Open VS Code’s LSP Sample: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample
* `npm install` from the LSP Sample directory
* Launch Client
* Now “Attach server”
* setting breakpoint `onCompletion` (server.ts:182)
* open plain text file "foo.txt" and press Control-Space to trigger completion

**Comment by corbob** [comment] 2019-02-06 13:42
@weinand I was unable to set breakpoints. I've since been able to test on another system with the same build of Windows and it worked fine. I did some hunting and found the Code - Insiders folder here: `C:\Users\corbob\AppData\Roaming\Code - Insiders` After renaming to `Code - Insiders.bak` I relaunched VSCode and was able to set breakpoints again 🤷‍♂️

**Comment by weinand** [comment] 2019-02-06 14:27
@corbob thanks, but your issue is unrelated to this one.

**Comment by Mellbourn** [comment] 2019-02-07 09:09
We are having this problem too: suddenly breakpoints have become "unverified" in our project. It is nodejs and TypeScript. 
MacOS 10.14.3
Visual Studio Code 1.30 and 1.31

For two developers, breakpoints were first working and then out of nowhere they stopped working. Began yesterday in 1.30 and happened again today in 1.31

**Comment by weinand** [comment] 2019-02-07 09:20
@Mellbourn is this when debugging an extension?
If no, what version of node.js are you using?
Did you upgrade node.js to a newer version when the problem started?

**Comment by Mellbourn** [comment] 2019-02-07 09:25
No, debugging ordinary server code.
This has happened for us on both node version 8.11.3 and 10.14.1.
We were not upgrading node when it happened.

**Comment by roblourens** [comment] 2019-02-07 17:55
You could 

- Run `.scripts` in the console to see whether your files/sourcemaps are resolved correctly
- Set `"trace": true` in the launch config, run again, and post the log here

**Comment by eamodio** [comment] 2019-02-08 03:19
@weinand @roblourens I tried to reproduce it with the lsp sample and couldn't (even after I added a webpack build for it)

But I did find that if I remove this from my `webpack.config.js`
```
output: {
    ...
    devtoolModuleFilenameTemplate: "file:///[absolute-resource-path]"
}
```

And instead use this in my `launch.config`
```
"sourceMapPathOverrides": {
	"webpack:///./~/*": "${workspaceRoot}/node_modules/*",
	"webpack:///./*": "${workspaceRoot}/*",
	"webpack:///*": "*"
}
```

But if I switch back to 1.30 with the same code and source maps the original works fine.

**Comment by eamodio** [comment] 2019-02-08 03:38
Actually it doesn't look like the `sourceMapPathOverrides` made a difference -- but setting `"cwd": "${workspaceFolder}"` on the `launch.config` did

**Comment by jpike88** [comment] 2019-02-09 07:46
Just got this issue after upgrading to 1.31, my chrome debug source maps aren't resolving.

**Comment by eamodio** [comment] 2019-04-09 03:08
Even after setting `cwd` above, I was still getting intermittent failures. But I've finally got to the bottom of them now. I was using `"outFiles": ["${workspaceFolder}/dist/**/*.js"]` in my launch config for my node.js attach, but I was also outputting more than 1 build to the `dist` folder:
![image](https://user-images.githubusercontent.com/641685/55770561-c460b100-5a52-11e9-99f6-47ab870282c5.png)

Even though I was attaching to the process running `agent.js`, it seems like sometimes the `agent-pkg.js.map` was actually getting used -- which didn't line up, so "unverified breakpoints".

Once I changed to this: `"outFiles": ["${workspaceFolder}/dist/agent.js"]`, attaching always works now.

**Comment by roblourens** [comment] 2019-04-11 15:40
Yes, we don't do a good job with source files that are mapped by multiple sourcemaps. Glad you figured it out!

**Closed** 2019-04-11 15:40 UTC
Labels: debug, needs more info

**Comment by eamodio** [comment] 2019-04-11 23:23
@roblourens can this be reopened and reframed to make handling that case better?

**Comment by roblourens** [comment] 2019-04-11 23:41
There is an issue here: https://github.com/Microsoft/vscode-chrome-debug-core/issues/315

We are actually working on a large refactoring of the debug adapter which would fix this, but I have no idea when it will be ready.
