### ISSUE TITLE
C# syntax highlighting broken around literal strings @"..."

### ISSUE THREAD

**Issue by af4jm** [Microsoft/vscode#6325] opened 2016-05-12 15:34 UTC
Not sure what the heck it's doing, but sometimes it ignores @" and sometimes it doesn't.
Attached is screen shot showing bogus highlighting and .cs source file used to create that screen shot (extension changed to .txt to enable upload).
Note that it highlights correct in both VS15 & VS13

- VSCode Version: 1.1.0-insider
- OS Version: Win7 & Win10

![vscodeissue-csliteralstrings](https://cloud.githubusercontent.com/assets/849948/15220382/4f488c42-1835-11e6-9a86-945d684e5abd.png)
[SharedConstants.cs.txt](https://github.com/Microsoft/vscode/files/261681/SharedConstants.cs.txt)

**Comment by isidorn** [comment] 2016-05-12 19:12
Not sure who contributes the highlighting, if it is the extension then this should be moved to 
https://github.com/OmniSharp/omnisharp-vscode
@aeschli can clarify

**Comment by af4jm** [comment] 2016-05-12 20:17
Created as issue 316 over there, but I would swear it behaved the same before I installed that extension.

**Comment by aeschli** [comment] 2016-05-13 18:48
duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/316

**Closed by aeschli** 2016-05-13 18:48 UTC
