### ISSUE TITLE
Selecting text is slow, switching tabs to a file with selected text is also very slow (seconds)

### ISSUE THREAD

**Issue by jisuo** [microsoft/vscode#146237] opened 2022-03-29 08:16 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Mac OS Monterey 12.3

Steps to Reproduce:

1. Select text in one tab, the more you select the slower it gets. 
2. Go to another tab and then click the tab with selected text again, the more text selected the longer delay (seconds)

The Performance profiler I did was 33MB so cannot include it here, but just a screenshot after selecting 30 lines of code and switching tabs (about 600ms to switch tab):

![image](https://user-images.githubusercontent.com/321012/160565663-27d8528e-782f-489d-871a-acabfbfe2d16.png)

Edit for more information:

I opened a new VS Code window, pasted this code snippet into two different tabs without saving (it doesn't matter what it is):

```
import React from "react";
import PropTypes from "prop-types";
import "./Button.css";

export default class Button extends React.Component {
  static propTypes = {
    name: PropTypes.string,
    orange: PropTypes.bool,
    wide: PropTypes.bool,
    clickHandler: PropTypes.func,
  };

  handleClick = () => {
    this.props.clickHandler(this.props.name);
  };

  render() {
    const className = [
      "component-button",
      this.props.orange ? "orange" : "",
      this.props.wide ? "wide" : "",
    ];

    return (
      <div className={className.join(" ").trim()}>
        <button onClick={this.handleClick}>{this.props.name}</button>
      </div>
    );
  }
}
```

**Comment by hediet** [comment] 2022-03-30 08:05
Can you share your settings?

**Comment by jisuo** [comment] 2022-03-30 13:18
@hediet 

Here are the settings:

```
{
  "editor.fontFamily": "Dank Mono",
  "editor.fontSize": 18,
  "editor.fontLigatures": true,
  "editor.tabSize": 2,
  "workbench.editor.enablePreview": false,
  "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
  "editor.formatOnSave": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "explorer.confirmDelete": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "javascript.preferences.quoteStyle": "single",
  "explorer.confirmDragAndDrop": false,
  "workbench.sideBar.location": "left",
  "editor.linkedEditing": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "explorer.compactFolders": false,
  "files.watcherExclude": {
    "**/.DS_Store": true,
    "**/.git": true,
    "**/build/**": true,
    "**/dist/**": true,
    "**/node_modules": true,
    "**/node_modules/**": true
  },
  "files.exclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/build/**": true,
    "**/dist/**": true,
    "**/node_modules": true,
    "**/node_modules/**": true
  },
  "search.exclude": {
    "**/.DS_Store": true,
    "**/build/**": true,
    "**/dist/**": true,
    "**/node_modules/**": true
  },
  "workbench.iconTheme": "Monokai Pro (Filter Machine) Icons",
  "window.autoDetectColorScheme": true,
  "workbench.colorTheme": "Default Light+"
}
```

**Comment by hediet** [comment] 2022-03-30 15:05
Unfortunately, I still cannot reproduce (I don't have your font installed though). Can you reproduce it on a different computer?

**Comment by jisuo** [comment] 2022-03-30 18:59
@hediet  Holy shit, that comment made me try changing to another font (Fira Code) and issue is gone. Changed back and issue is back. It's the font! I'm not sure if the the font is broken or if VS Code has a bug with it, maybe worth checking out though?

**Comment by hediet** [comment] 2022-03-31 09:58
Is it slow in other editors? Or in this playground: https://microsoft.github.io/monaco-editor/playground.html

Maybe it is an electron issue. We don't do anything different for different fonts.

**Comment by deepak1556** [comment] 2022-03-31 13:27
Does the issue also repro with `1.66` ?

**Comment by jisuo** [comment] 2022-03-31 14:52
@hediet Not sure how I would repro it in that playground, tried `* {font-family: 'Dank Mono'; font-size: 18px;}` but didn't load font. I'll see what other editors I can try in.

@deepak1556 yes, repro in latest 1.66

**Comment by jisuo** [comment] 2022-03-31 15:01
@hediet I tried Sublime Text 4, Webstorm and Atom no issues there, only VS Code.

**Comment by deepak1556** [comment] 2022-03-31 16:18
Font rendering is delegated to the chromium runtime, @jisuo can you do another test with the same font settings using https://vscode.dev/ on your chrome/edge browser ?

**Comment by jisuo** [comment] 2022-04-01 09:01
@deepak1556 Yes it reproduces on https://vscode.dev/. If I use another font like Menlo everything is fine.

**Comment by deepak1556** [comment] 2022-04-01 10:58
Thanks for confirming, in that case we should be able to repro with the playground as well, let's try it one more time,

Can you open https://microsoft.github.io/monaco-editor/playground.html and paste the following,

```
monaco.editor.create(document.getElementById('container'), {
	language: 'javascript',
        fontFamily: 'Dank Mono',
        fontSize: 18,
        fontLigatures: true
});
```

Once you run the above snippet, you should have editor container with the required font. If you can confirm the issue with this setup, as a next step please file an issue at https://bugs.chromium.org/p/chromium/issues/list with this minimal example so that it can be investigated in the runtime.

**Comment by deepak1556** [comment] 2022-04-01 12:07
Thanks for creating the issue 👍

**Comment by deepak1556** [comment] 2022-12-13 11:19
Closing since upstream issue has been closed as `wontfix`

**Closed by deepak1556** 2022-12-13 11:19 UTC
Labels: freeze-slow-crash-leak, upstream-issue-linked, chromium
