### ISSUE TITLE
[Debug] Cannot launch node2 debug configuration for electron application

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#19681] opened 2017-02-01 16:54 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 8.1 x64

I have an electron application. When using `"type": "node"` in `launch.config` debugging is going fine. When I change to `"type": "node2"`, I get the following error message at the start:

> Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5372).

Restarting VS Code doesn't help.

I've noticed that when using `"type": "node"`, I get the following output in Debug Console:
`c:\dev\myApp/node_modules/.bin/electron.cmd --debug-brk=11978 c:\dev\myApp --enable-logging --remote-debugging-port=9222 built\app.js `

And for `"type": "node2"`:
`c:\dev\myApp/node_modules/.bin/electron.cmd --inspect=5372 --debug-brk c:\dev\myApp --enable-logging --remote-debugging-port=9222 built\app.js `

In `"node"` case VS Code uses `--debug-brk=11978` parameter and in `"node2"` case it uses `--inspect=5372`.

**Comment by auchenberg** [comment] 2017-02-01 22:42
This is caused by Electron hasn't landed the newest version of V8, which includes `V8_inspector` that's required by our new Node debugger. 

https://github.com/electron/electron/issues/6634

**Comment by roblourens** [comment] 2017-02-02 18:26
Yep, what @auchenberg said

**Closed by roblourens** 2017-02-02 18:26 UTC
