### ISSUE TITLE
Make colorDecorators optional through settings

### ISSUE THREAD

**Issue by ricklamers** [Microsoft/vscode#17873] opened 2016-12-28 13:07 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

I don't know whether this is the place to submit this, please do correct me if this is not the place.

My suggestion: allow a user to disable the color decorators that appear in the editor (e.g. in .css files with #fff color codes).

I think they're added in this file: https://github.com/Microsoft/vscode/blob/a29692641df855658855f46f71432d5e1b3c7ae5/extensions/html/client/src/colorDecorators.ts

![image](https://cloud.githubusercontent.com/assets/1309307/21522566/f2503d64-cd06-11e6-8fbb-0d71f1603a3c.png)

**Comment by aeschli** [comment] 2017-03-02 14:16
duplicate of #10943, fixed for the February build.

**Closed by aeschli** 2017-03-02 14:16 UTC
