### ISSUE TITLE
C support for markdown is broken

### ISSUE THREAD

**Issue by LoZack19** [microsoft/vscode#118300] opened 2021-03-06 07:27 UTC
Issue Type: <b>Bug</b>

```c
// some C code here
```

The syntax highlight works unpredictably. Sometimes it works, other times it does not.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.11.2-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.64GB (12.08GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 969073c0-8cee-45c7-964d-b29b21ef1233|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
language-gas-x86|bas|0.0.2
prettier-vscode|esb|5.9.2
bash-ide-vscode|mad|1.11.0
python|ms-|2021.2.625869727
jupyter|ms-|2021.2.603412351
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.3912
linux-desktop-file|nic|0.0.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by mjbvz** [comment] 2021-03-08 19:13
Please provides an example of code that doesn't work 

/needsMoreInfo

**Comment by LoZack19** [comment] 2021-03-09 14:07
```c
int savebuffer(FILE* File, char* buffer);
```
Everything in the brackets doesn't get highlighted. Also in here the same thing:
```c
char* loadfile(FILE* File);
```

but not here:
```c
void empty(char* buffer, int size);
```

I **suspect** that it has to to  with the fact that FILE is made of capital letters. Indeed everything that follows a capital letter... not sure though.

**Comment by mjbvz** [comment] 2021-03-22 23:46
Duplicate of #112787

Also see https://github.com/microsoft/vscode/issues/4769#issuecomment-204005332 about the root cause of this: `$base`

@aeschli @alexr00 Let me know if there's anything we can do to improve this because it keeps getting reported every few months. It's not markdown specific, but our markdown grammar is probably the heaviest user of nested grammars

**Closed by mjbvz** 2021-03-22 23:46 UTC
Labels: markdown, needs more info
