### ISSUE TITLE
banckground color broken

### ISSUE THREAD

**Issue by ocazuer** [Microsoft/vscode#16906] opened 2016-12-08 09:43 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|matlab|Gimly81|0.4.0|
|beautify|HookyQR|0.6.2|
|html-snippets|abusaidm|0.0.18|
|vscode-css-formatter|aeschli|0.0.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.5|
|vscode-html-css|ecmel|0.0.30|
|vscode-csscomb|mrmlnc|3.2.4|
|cpptools|ms-vscode|0.9.2|
|qub-xml|qub|0.3.0|
|vscode-icons|robertohuertasm|4.0.5|
|sass-indented|robinbentley|1.2.1|
|jinja|wholroyd|0.0.7|

---

Steps to Reproduce:

1. change all setting to defaut
2. find that background is broken 

![2016-12-08 5 38 06](https://cloud.githubusercontent.com/assets/22286839/21004897/a33b8952-bd6d-11e6-9cbc-6429f7bdf8eb.png)

**Comment by alexandrudima** [comment] 2016-12-08 13:28
This looks like a Chromium issue around working with the GPU.

@ocazuer Does this reproduce when closing vscode and launching with `code --disable-gpu` ?

**Comment by ocazuer** [comment] 2016-12-08 13:54
No, my background is fine after using "--disable-gpu".

My computer is MacBook 12-inch 2016 with Intel Core m3 and macOS Sierra
10.12.1. Hope this help.

Alexandru Dima <notifications@github.com>于2016年12月8日周四 下午9:29写道：

**Comment by bpasero** [comment] 2016-12-08 14:02
https://github.com/Microsoft/vscode/issues/12473

**Closed by bpasero** 2016-12-08 14:02 UTC
Labels: needs more info
