### ISSUE TITLE
Terminal split cwd doesn't work with unicode

### ISSUE THREAD

**Issue by zhuxinzeng** [microsoft/vscode#92835] opened 2020-03-17 09:08 UTC
Issue Type: <b>Bug</b>

终端 shell CWD“/Users/mac/Documents/\xe6\xaf\x95\xe8\xae\xbe\xe9\xa1\xb9\xe7\x9b\xae/\xe6\xaf\x95\xe8\xae\xbe\xe9\xa1\xb9\xe7\x9b\xae\xe6\xb5\x8b\xe8\xaf\x95\xe7\x89\x88\xe6\x9c\xac”不存在

Google translate:

Terminal shell CWD "/ Users / mac / Documents / \ xe6 \ xaf \ x95 \ xe8 \ xae \ xbe \ xe9 \ xa1 \ xb9 \ xe7 \ x9b \ xae / \ xe6 \ xaf \ x95 \ xe8 \ xae \ xbe \ xe9 \ xa1 \ xb9 \ xe7 \ x9b \ xae \ xe6 \ xb5 \ x8b \ xe8 \ xaf \ x95 \ xe7 \ x89 \ x88 \ xe6 \ x9c \ xac "does not exist

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
vscode-ant-design-vue-helper|ant|1.0.6
vscode-database|baj|2.2.0
vscode-standardjs-snippets|cap|0.8.9
vscode-standardjs|che|1.2.3
jsrefactor|cms|2.20.5
vscode-eslint|dba|2.1.1
jquerysnippets|don|0.0.1
vscode-element-helper|Ele|0.5.6
beautify|Hoo|1.5.0
jquery-snippets|Hri|1.0.0
highlight-icemode|ice|0.0.6
csharpextensions|jch|1.3.1
docomment|k--|0.1.8
csharpfixformat|Leo|0.0.84
vue-alias-skip|lih|0.0.18
vscode-language-babel|mgm|0.0.26
vscode-language-pack-zh-hans|MS-|1.43.7
csharp|ms-|1.21.14
js-atom-grammar|ms-|0.1.14
typescript-javascript-grammar|ms-|0.0.53
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
java|red|0.58.0
mongo-snippets-for-node-js|roe|1.0.23
vue-vscode-snippets|sdr|1.8.0
vscode-leetcode|she|0.16.1
element-ui-snippets|SS|0.3.5
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-03-17 10:32
Please give more information, maybe a screenshot.

**Comment by zhuxinzeng** [comment] 2020-03-17 11:51
When doing Vue project, open two terminals. Report errors



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Martin Aeschlimann <notifications@github.com&gt;
发送时间: 2020年3月17日 18:33
收件人: microsoft/vscode <vscode@noreply.github.com&gt;
抄送: 朱信增 <321094948@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[microsoft/vscode] VS code开两个终端报错 (#92835)





 
Please give more information, maybe a screenshot.

**Comment by aeschli** [comment] 2020-03-18 11:43
Sorry, I don't underatand the issue. Please add more description, screenshot, steps...

**Comment by zhuxinzeng** [comment] 2020-03-21 01:58
Display error when splitting terminal
![image](https://user-images.githubusercontent.com/37398041/77217089-802ec980-6b5a-11ea-8b21-f7feb24f01a4.png)

**Comment by Tyriar** [comment] 2020-03-23 14:50
@zhuxinzeng can you paste in the full path that it's trying to open? `/Users/mac/Documents/<something>/<somethingelse>`

**Comment by raykle** [comment] 2020-05-12 15:11
I have the same issue. I download the `Insiders` version and it still happens.

Steps to Reproduce in `Code - Insiders`:
1. Download the Insiders version;
2. Open Code Insider, don't open any folder;
3. Open the integrated terminal, It's in the cwd of `~`;
4. Make a folder named `测试`；
5. `cd ./测试`;
6. Click the button `Split Terminal`;
7. Fails with the error `The terminal shell CWD "/Users/guomin/\xe6\xb5\x8b\xe8\xaf\x95" does not exist`;

The Code Insider is newly downloaded, and it has _NO_ installed extends, _NO_ user settings.

I record a video, wish it helps. It's really puzzled.

[20200512-230543-HD.mp4.zip](https://github.com/microsoft/vscode/files/4616440/20200512-230543-HD.mp4.zip)

**Comment by rzhao271** [comment] 2020-11-04 23:51
Duplicate of #83496

**Closed by rzhao271** 2020-11-04 23:51 UTC
Labels: bug, integrated-terminal
