### ISSUE TITLE
"Couldn't start client JSON Language Server" error

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#43317] opened 2018-02-09 13:53 UTC
I'm getting this error when opening launch.json on my Mac (pretty sure it doesn't happen on my PC). Restarting Code code has had no effect.

<img width="1050" alt="screen shot 2018-02-09 at 13 49 32" src="https://user-images.githubusercontent.com/1078012/36030679-14d29406-0da0-11e8-9042-908ef6b3f701.png">

As far as I can tell, the Code Helper it's looking for does exist at that location:

<img width="744" alt="screen shot 2018-02-09 at 13 52 09" src="https://user-images.githubusercontent.com/1078012/36030801-7ee0487a-0da0-11e8-91d4-1cc3fccfc972.png">

<img width="746" alt="screen shot 2018-02-09 at 13 51 52" src="https://user-images.githubusercontent.com/1078012/36030806-840e756a-0da0-11e8-8065-3e4aa45625d9.png">

Anything I can do to debug (it's possible uninstalling/reinstalling Code will fix; but there may be value in understanding what's happened?)

**Comment by DanTup** [comment] 2018-02-09 13:55
The other path mentioned also seems to exist:

<img width="604" alt="screen shot 2018-02-09 at 13 54 31" src="https://user-images.githubusercontent.com/1078012/36030887-d06a209e-0da0-11e8-8374-44bf2ef5b88f.png">

**Comment by DanTup** [comment] 2018-02-09 14:01
Trying to run it manually gives this error, seems like there's no Resources folder inside Code Helper?

<img width="1135" alt="screen shot 2018-02-09 at 13 59 20" src="https://user-images.githubusercontent.com/1078012/36031147-a925be8e-0da1-11e8-9e7a-3d5f83a1d661.png">

**Comment by aeschli** [comment] 2018-02-09 17:21
@DanTup In what build do you see this?

**Comment by DanTup** [comment] 2018-02-09 17:25
Stable 1.20.0, it auto updated to it a few nights ago

**Comment by aeschli** [comment] 2018-02-09 17:31
I tried with 1.20 c63189deaa8e620f650cc28792b8f5f3363f2c5b, and all seems to work for me.
I can open debug.json.

Can you reinstall VSCode ?

**Comment by DanTup** [comment] 2018-02-09 18:14
I deleted it from Applications then downloaded using the Stable link on the website; extracted the zip, dragged the .app into Applications and launched. Same thing :(

**Comment by aeschli** [comment] 2018-02-12 08:33
Also make sure that all instances of VSCode are closed.
cc @joaomoreno

**Comment by DanTup** [comment] 2018-02-12 08:44
It was completely closed before I deleted it. I even launched the .app I extract directly from another location and had the same issue (though the paths were different, pointing at a temp location where Mac OS seemed to have put the app to run it).

I just downloaded the Mac package again (from [here](https://go.microsoft.com/fwlink/?LinkID=620882)) on my PC and opened it up and I can see there's no `resources` folder inside the path from the error message up top.

![Missing resources](https://user-images.githubusercontent.com/1078012/36088808-9b9cadb4-0fd0-11e8-8a9b-e4f855f6669e.png)

Does this not happen for any of you if you install/run the official package being served up (I don't think running from the repo commit is a good test)?

**Comment by joaomoreno** [comment] 2018-02-12 09:24
@DanTup Close all files in Code. Shutdown Code. Open Code. Open devtools. Any errors there?

Now, open `launch.json`. Do the errors come up then?

**Comment by DanTup** [comment] 2018-02-12 10:21
Strangely, I cannot repro this today. I'd definitely closed all Code windows and rebooted (many times) between the update and experiencing this (restarting again was one of the first things I did before raising). I also completely removed and reinstalled it and still had the issue.

I don't know what project I had open at the time, but I tried a few now and can't repro (I tried with launch.json open already and also opening it after loading, and I tried in both the main instance and the dev host).

I'll do some more testing later, but I'm kinda baffled by this; it absolutely wasn't just a case of not restarting Code since the update, that I'm positive of.

**Comment by joaomoreno** [comment] 2018-02-12 10:56
Alright, let us know if it comes back.

**Comment by DanTup** [comment] 2018-02-12 13:41
Hit it again - but on my PC this time! So it's not isolated to Mac :(

```text
[Error - 13:38:06] Starting client failed
Error: spawn C:\Program Files (x86)\Microsoft VS Code\Code.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

![PC](https://user-images.githubusercontent.com/1078012/36099323-20e215f8-0ffa-11e8-82d8-2c26f4102cc5.png)

I tried closing and re-opening the projects, but it didn't occur the second time... I'll try and do some more debugging after lunch.

**Comment by joaomoreno** [comment] 2018-02-12 13:46
OK, let me know if you can repro it better. cc @bpasero @alexandrudima for more eyes on this

**Comment by DanTup** [comment] 2018-02-12 14:17
Ok, there is something super-funky going on.

Here's the repo I'm opening:

https://github.com/DanTup/cambridge/

It's at the latest changeset (afcd54195cab5083229debe62de0e9922cb40cb1).

When I open the workspace I sometimes see the following change automatically appear. I do not know what's causing this `../cambridge-tests` folder to be added (I know that the original author does have another repo of tests, but I don't know why Code is deciding to add it to my workspace or where it even got the info about it from).

![Change](https://user-images.githubusercontent.com/1078012/36100718-1e9b9bde-0fff-11e8-93ad-950e4b8dfa4f.png)

Once that Change has been made, any subsequent loads result in the error I posted above.

**Comment by DanTup** [comment] 2018-02-12 14:19
I did a search for `cambridge-tests` across that folder and turned up only two entries in the readme. I'm am completely baffled about where Code is getting a reference to try and inject into the `.code-workspace` file (or why that causes this crash).

**Comment by DanTup** [comment] 2018-02-12 14:28
Ok, the plot thickens :/

I have something weird going on that is probably (hopefully) unrelated to Code. When I click "discard changes" on the file in the myscreenshot above, it flickers and then shows as if it's modified again but says "This file is empty" in GitHub desktop (normally this message appears when line endings are different, the file isn't actually empty). If I do "discard changes" again, then it flickers and becomes that diff above (WTF?). I can literally flip between those two states just clicking Discard changes!

Of course, whatever is causing that is probably not a Code issue. However, the changes shown above (eg. there is a path to that folder that doesn't exist) seem to be causing the error in Code (that does seem like a Chrome bug).

**Comment by DanTup** [comment] 2018-02-12 14:33
I don't even...

(Code is not running)

![github](https://user-images.githubusercontent.com/1078012/36101566-9fd8c242-1001-11e8-86c6-e09c1e41be91.gif)

**Comment by DanTup** [comment] 2018-02-12 14:39
Oh wow, the casing of the filename is changing. I guess this repo must have two files with different casing... I can fix that!

Once I've sorted that, I'll see if I can repro this error with just the bad path.

**Comment by DanTup** [comment] 2018-02-12 14:49
Ok, I can repro this by putting the bad path into the top of any `.code-workspace` file:

```js
{
	"folders": [
		{
			"path": "../testse-tests"
		},
		{
			"path": "M:\\Coding\\Applications\\flutter\\packages\\flutter_tools"
		},
		{
			"path": "M:\\Coding\\Applications\\flutter\\dev\\devicelab"
		}
	],
	"settings": {
	}
}
```

**Comment by joaomoreno** [comment] 2018-02-12 15:26
I've very confused now. What exactly happens when you put _the bad path into the top of any `.code-workspace` file_?

**Comment by DanTup** [comment] 2018-02-12 15:28
Apologies, I've been confused too!

Basically the bug is that if there is a bad path in the code-workspace file (like the `"path": "../testse-tests"` in my previous comment) then when you open that workspace in Code, you'll get the JSON service error.

**Comment by DanTup** [comment] 2018-02-12 15:29
I've removed the comments from when I was digging into this that turned out to be unrelated, hopefully it reads better now.

**Comment by joaomoreno** [comment] 2018-02-12 15:45
Awesome, thanks. Seems like a great find!

**Comment by DanTup** [comment] 2018-02-12 15:47
Yep, sorry. The repo I was using had a relative path to another repo that was normally checked out alongside it, so it was referencing a missing folder for me.

**Comment by aeschli** [comment] 2018-02-12 16:44
The problem is that when the language client spawns the language server it uses the first workspace folder as the cwd of the process.

**Comment by aeschli** [comment] 2018-02-12 16:53
There are multiple other exceptions in the console:
- git (@joaomoreno)
```
[Extension Host] rejected promise not handled within 1 second (at Console.originalConsole.(anonymous function) [as warn] (/home/aeschli/workspaces/vscode/extensions/git/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))
```

-ripgrep (@roblourens)
```
[Extension Host] [IPC Library: Search] spawn /usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg ENOENT (at /usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/searchApp.js:147:153) (at Console.originalConsole.(anonymous function) [as error] (/usr/share/code-insiders/resources/app/extensions/git/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))
```

I'll add a test to the language server, but I wonder if we should filter such folders from the API? @bpasero

**Comment by DanTup** [comment] 2018-02-12 17:04
> The problem is that when the language client spawns the language server it uses the first workspace folder as the cwd of the process.

What happens if you just don't set a `cwd`? It can't be used for anything important if you're just arbitrarily picking one? 😀

**Comment by bpasero** [comment] 2018-02-12 17:26
@aeschli I would not do that, an extension has to always assume that a workspace folder of a multi root configuration is invalid (for example, a user might have a workspace where some folders point to an external hard disk which is not always connected). 

It is true that this never happened before where you could only open a single folder which always had to exist. However, I would not want to add some throw-away code to handle the "first folder" case specifically because that one is deprecated API anyways.

It is good to force extensions to think about the case where the first (or any) folder is not there, extensions need to deal with this imho.

**Comment by aeschli** [comment] 2018-02-13 11:19
https://github.com/Microsoft/vscode-languageserver-node/issues/310 is the issue on the LSP side.

**Comment by aeschli** [comment] 2018-02-13 11:24
Created https://github.com/Microsoft/vscode/issues/43580 and https://github.com/Microsoft/vscode/issues/43579 for the git and ripgrep errors

**Comment by alexandrudima** [comment] 2018-02-13 14:05
Related: #43493

**Comment by joaomoreno** [comment] 2018-02-14 09:07
@bpasero I'm not so convinced that is the case. We're forcing all extensions to simultaneously check for `fs.exists`. Why shouldn't this be handled by the platform? As an extension author, I assume that if the API tells me the workspace has folders A, B, C, I think it's very reasonable to assume that those folders exist. Every extension will do so.

**Comment by bpasero** [comment] 2018-02-14 18:27
@joaomoreno but it is not that easy, an extension might want to use the new API to change workspace folders and now suddenly those that do not exist on disk are not showing up anymore? I think we are telling the wrong story to extensions if we decide to not include those that currently are not existing on disk.

**Comment by bpasero** [comment] 2018-02-15 05:26
@roblourens I was not referring to adding a folder that does not exist but managing the set of workspace folders in any way (e.g. that could also include showing a workspace folder picker to do some more stuff with it). 

I think it boils down to the question what `WorkspaceFolder` is defined as: the list of folders as defined in the workspace configuration file (my preference), or the list of folders that actually exist on disk.

**Comment by aeschli** [comment] 2018-02-16 14:04
Closing as the JSON language server has been fixed.

**Closed by aeschli** 2018-02-16 14:04 UTC
Labels: bug, json
