### ISSUE TITLE
SCM: incomming/outgoing revert features 1.92.

### ISSUE THREAD

**Issue by zizeca** [microsoft/vscode#228099] opened 2024-09-10 12:21 UTC
if the features has been removed in the new version, please add a features that will show all the difference between the branches that was in version 1.92
![Screenshot from 2024-09-10 15-02-01](https://github.com/user-attachments/assets/a7830d88-106c-4c7a-bf05-3ea93835613c)
![Screenshot from 2024-09-10 15-16-17](https://github.com/user-attachments/assets/57a6fd13-4803-418b-b0c7-676730c1a6da)

**Comment by lszomoru** [comment] 2024-12-10 12:44
Closing as duplicate of [#227727](https://github.com/microsoft/vscode/issues/227727)

**Closed by lszomoru** 2024-12-10 12:44 UTC
Labels: feature-request, scm
