### ISSUE TITLE
it can't select all words in search box

### ISSUE THREAD

**Issue by Sweechirly** [microsoft/vscode#93547] opened 2020-03-27 03:42 UTC
Issue Type: <b>Feature Request</b>

When I edit an file, I use ctrl + f to search something, but i can't use ctrl + A or mouse to select all words in the search box

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sportshead** [comment] 2020-03-27 08:15
Can't reproduce. Try adding screenshots

**Comment by rebornix** [comment] 2020-06-25 18:08
I can't reproduce this issue and since there is no more information provided, I'll close it for now.

**Closed by rebornix** 2020-06-25 18:08 UTC
