### ISSUE TITLE
Scroll position should not change when returning to file

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#32397] opened 2017-08-12 23:54 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (0b6da14128b4e61e331193f18786e8db2792a643, 2017-08-11T19:30:08.812Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

**Description**
The scroll position moves down as references are retrieved. For large files, the position can be many lines away.

**Steps to Reproduce:**
1. Set `typescript.referencesCodeLens.enabled` to `true`.
2. Open any TS file (easiest to see when the file contains an enum).
3. View a different file.
4. Return to the original file.

![scroll-codelens](https://user-images.githubusercontent.com/1007463/29244961-ce0934fe-7f7d-11e7-9722-fcf382066fa5.gif)

**Comment by bpasero** [comment] 2017-08-15 19:04
Related to CodeLense?

**Comment by distante** [comment] 2017-08-24 09:26
I just enabled `referencesCodeLens` and notice the same. We lost the place where we are even if the references were already loaded.

**Comment by eamodio** [comment] 2017-09-12 01:17
I am seeing the same and it only happens with code lens enabled. I see it in `1.16` but much more pronounced in `1.17.0-insider` 2c385b98066eebb8e39dfd98b1fcb8cc254196b6

**Comment by GregoryLawruszczuk** [comment] 2017-09-19 13:05
Had this happen as well. Changing "typescript.referencesCodeLens.enabled" to false helped.

The same/very similar problem occurs with the Git Lens extension (https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens ) with "gitlens.codeLens.enabled": true. This one might be less pronounced. Probably because the extension adds fewer lines than TypeScript CodeLens.

Windows 10, 64bit. VSCode 1.16.1, but I'm sure it was a problem before this version.

**Comment by eteisman** [comment] 2017-10-30 10:33
I have noticed the same behavior: after switching a tab, and then back the editor has scrolled away from its previous position. After setting "typescript.referencesCodeLens.enabled" to false this behavior disappeared.

With referencesCodeLens enabled, just switching tabs and back again, loses the previous cursor position.

**Comment by jrieken** [comment] 2017-11-23 14:17
dupe of #19917

**Closed by jrieken** 2017-11-23 14:17 UTC
Labels: bug, code-lens, editor
