### ISSUE TITLE
Changing the teminal tab name.

### ISSUE THREAD

**Issue by JostCrow** [Microsoft/vscode#10069] opened 2016-08-03 08:50 UTC
- VSCode Version: 1.4.0-insider
- OS Version: ElementaryOS

I am using the intergrated terminal. It works great I only have one wish. Is it possible to name the terminal. I use multiple tabs and the problem is that I get multiple tabs with the same name. 

![screenshot from 2016-08-03 10 39 30](https://cloud.githubusercontent.com/assets/390575/17359709/1b34fa70-5968-11e6-9d60-df06cdafa735.png)

**Comment by Tyriar** [comment] 2016-08-03 18:31
Duplicate of https://github.com/Microsoft/vscode/issues/10023, I'm curious how you want to be able to rename (command, context menu, button, etc.).

**Closed by Tyriar** 2016-08-03 18:31 UTC
