### ISSUE TITLE
Additional commands appear for the second debugging

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/vscode#211755] opened 2024-04-25 06:44 UTC
In the first debugging, the terminal command is as follows
![image](https://github.com/microsoft/vscode-python-debugger/assets/108051416/be5f6d90-a39a-4db4-bb88-ac2f249a16d3)

When debugging for the second time, the `cd` command appears
![image](https://github.com/microsoft/vscode-python-debugger/assets/108051416/33c342d5-6b10-4992-8c76-faaf9b38c10b)

If you delete the terminal and debug again, it is the same as the first debugging.

The problem is that if you repeat the debugging in the same terminal, the subsequent debugging will show additional `cd` commands.

In addition, the following occurred during the test.
![image](https://github.com/microsoft/vscode-python-debugger/assets/108051416/756b9d67-48d8-4493-97e8-644f1d3f0f7c)

**Comment by karthiknadig** [comment] 2024-05-30 20:11
@Tyriar This is showing `nonce` in the terminal it looks like.

**Comment by karthiknadig** [comment] 2024-05-30 20:12
This is a shell integration issue. Basically, the DAP `run-in-terminal` handling done by DAP client in core is what sends the command to the terminal.

**Comment by Tyriar** [comment] 2024-12-18 16:59
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-18 16:59 UTC

**Comment by starball5** [comment] 2024-12-21 05:22
Would such an upstream issue also potentially be responsible for something like https://stackoverflow.com/q/79290118/11107541 ?

**Comment by Tyriar** [comment] 2025-01-07 13:56
@starball5 yes
