### ISSUE TITLE
Selections reveal horizontally delayed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173755] opened 2023-02-08 05:42 UTC
Since a few weeks now I notice how a selection that is out of the viewport horizontally only reveals with a slight delay. Here I am navigating between 2 editors:
![Recording 2023-02-08 at 06 41 52](https://user-images.githubusercontent.com/900690/217444737-be5d3770-6320-4b27-8925-418b463f7cb8.gif)

**Comment by alexdima** [comment] 2023-02-23 23:06
I can't reproduce anymore on latest. I believe this was fixed via https://github.com/microsoft/vscode/pull/174266

**Closed by alexdima** 2023-02-23 23:06 UTC
Labels: bug, editor-core
