### ISSUE TITLE
Change debug stop icon back to solid

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#77540] opened 2019-07-17 18:53 UTC
Wanted:

![image](https://user-images.githubusercontent.com/4033249/61403086-63364e00-a889-11e9-95fc-0800b2e92bf6.png)

Not wanted:

![image](https://user-images.githubusercontent.com/4033249/61403098-69c4c580-a889-11e9-81da-b21d86453c74.png)

**Comment by misolori** [comment] 2019-10-07 18:30
Closing this as a duplicate of #79130 since that will allow you to configure the icons to your own liking. Please upvote that issue.

**Closed by misolori** 2019-10-07 18:30 UTC
Labels: icons-product

**Comment by octref** [comment] 2019-10-16 18:59
I'm arguing that the **default** should be the very-easy-to-read red block, not the ability to customize that icon.
