### ISSUE TITLE
previewHTML doesn't expand to full editor with

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#24432] opened 2017-04-10 12:17 UTC
- VSCode Version: 1.11.1
- OS Version: 10.12.4

Steps to Reproduce:

1. Open any .md file with the markdown preview extension (or use any other extension that works with previewHTML).
2. See the vertical scrollbar is not at the right hand side but a good part moved to the left. I might be wrong but it looks as if that is the size used by the minimap (if switched on).

**Comment by jrieken** [comment] 2017-04-10 13:01
dupe of #5745

**Closed by jrieken** 2017-04-10 13:01 UTC
