### ISSUE TITLE
IntelliSense list item overlap.

### ISSUE THREAD

**Issue by maorui2014** [Microsoft/vscode#5382] opened 2016-04-16 08:16 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10 1511 - 10586

Steps to Reproduce:

1. Generate a New Extension (yeoman -> TypeScript)
2. src/extension.ts
3. 
![image](https://cloud.githubusercontent.com/assets/18439500/14579905/e8b8b1e2-03ed-11e6-892a-74223da1e721.png)

**Comment by joaomoreno** [comment] 2016-04-18 06:58
Duplicate of #3464

**Closed by joaomoreno** 2016-04-18 06:58 UTC
