### ISSUE TITLE
Extension debug: no longer able to run extension tests from debug

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21106] opened 2017-02-22 11:08 UTC
Steps to Reproduce:

1. hello world TS extension
2. run tests

![image](https://cloud.githubusercontent.com/assets/900690/23209015/ad205554-f8f7-11e6-86c1-c9b9dc28b7ed.png)

This works in stable.

**Comment by weinand** [comment] 2017-02-22 11:43
@jrieken the missing dialog.js is an indication that this problem occurs early in VS Code before hitting the debugger code. Could your changes to the test infrastructure result in this issue?


nothing has changed in the node-debug backend.

**Comment by jrieken** [comment] 2017-02-22 12:05
@weinand My changes aren't merged yet

**Comment by weinand** [comment] 2017-02-22 13:48
The problem is that we are no longer starting the extension host with debugBrk.

**Closed** 2017-02-22 17:24 UTC
Labels: bug, debug, important
