### ISSUE TITLE
Autocomplete issue with Ionic2/Angular2

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#18176] opened 2017-01-05 16:15 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a new Ionic 2 application
2. Open app.component.ts
3. Add a new import for a new page (you should probably make it via the Ionic CLI first, imagine we have one called CatsPage)

As I type

    import { CatsPage } from '.

VSC will suggest zone.js as soon as I type that last period. I'm trying to type .. though, but when I type the second ., VSC auto inserts zone.js.

I've recorded a video you can see here: http://youtu.be/_01hRIZ9yGc?hd=1

It's easy enough to fix, just annoying.

**Comment by danbucholtz** [comment] 2017-01-05 17:13
This is driving me nuts too. I haven't noticed this until today. Has something changed with autocomplete recently?

Whenever I try to write an `import` statement such as:

```
import { Something } from '../some-module
```

It autocomplete to
```
import { Something } from 'zone.js'
```

Thanks,
Dan

**Comment by jbw91** [comment] 2017-01-06 20:06
This is super frustrating for me as well. Tried checking extensions but it didn't seem to be any I had.

**Comment by mjbvz** [comment] 2017-01-06 21:52
Closing as duplicate of #17770

**Closed by mjbvz** 2017-01-06 21:52 UTC
Labels: duplicate
