### ISSUE TITLE
'tab' key stopped working in json file; moves focus away from editor 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8458] opened 2016-06-28 22:31 UTC
Platform: OS X

I was editing a launch.json file when suddenly the tab key stopped working. Instead of inserting a 'tab' character (and indenting a json line) it was moving focus away from the editor.

Sorry, but I don't have better steps.

@aeschli you saw the same, right?

**Comment by bpasero** [comment] 2016-06-29 04:55
Maybe emmet?

**Comment by aeschli** [comment] 2016-06-29 06:05
When I saw it (sorry, no reproducing steps), tab was changing focus. But the 'Accessibility mode' was not showing and turning it on and off didn't make a difference.

**Comment by alexandrudima** [comment] 2016-06-29 06:54
It must be this "Accessibility moves focus" thing. I think :)

**Comment by alexandrudima** [comment] 2016-06-29 11:14
It is caused by us reusing the same keybindingService instance across different editor widget instances --- reproducible when opening a read-only file (such as default settings) and then switching to an editable file

**Comment by jrieken** [comment] 2016-06-29 15:10
Affects many keybindings - issue is that editor somehow things it's under a different context than it actually is...

**Comment by jrieken** [comment] 2016-06-29 15:16
Steps show a different problem but have the same source as I believe:

* open two files in two editor slots
* refresh the workbench to get a fresh state
* swap the editor slots
* in slot one, hit `Cmd+F`
* now hit `ESC`

⚡ the find box doesn't close...

**Comment by jrieken** [comment] 2016-06-29 15:36
@bpasero I need help to know when the editor get reparented or even better a stable dom element that is moved with the editor and that encloses the title & editor

**Comment by bpasero** [comment] 2016-06-29 16:10
Low risk fix idea is to move the data-attribute when moving editors. The larger change to actually move the editor container DOM nodes might be more risky.

**Comment by jrieken** [comment] 2016-06-30 14:19
Current status is that @bpasero investigates into making the titlebar and editor sit under a parent dom element that is being moved/reparented on editor shuffle. If that is too risky or too much, I will revert https://github.com/Microsoft/vscode/commit/a3fd673d1e68dcceeef54327103a2644ce36f69f#diff-2e9d856a679081c7f84828600f59c10d which means we loose access to editor context keys for menu item selection (like no `when: "editorHasSelection`) Effectively menu item then can only use `resourceScheme` and `resourceLangId`.

**Comment by bpasero** [comment] 2016-06-30 14:31
I am looking into this for half the day now and still try to find a fix that does not break everything. The assumption in the editor part is that title and editor container never move when you move an editor, only the editor gets reparented. Introducing a container that contains title and editor breaks this assumption, so it needs more work than just introducing a container somewhere.

On the other hand, I am also looking why I need to reparent the editor widget. It might also be possible to just change the inputs in the editors when moving editors around so that an editor - once created - never looses its parent containers.

Tricky bit is the case where a group closes, because that means that potentially 2 active editors (CENTER, RIGHT), move to new positions (LEFT, CENTER). There the fact that we reparent is actually nice.

**Comment by jrieken** [comment] 2016-06-30 15:03
Yeah, no rushing. Reverting is OK for me, the `resourceScheme` and `resourceLangId` are enough to get  a decent menu item contribution - see markdown. We can still unleash the beast of full context key control at a later point.

**Comment by bpasero** [comment] 2016-06-30 15:17
@jrieken I was not aware you could revert but still support the markdown case. if that is possible I suggest to do that for June and do a proper fix for July (either moving the whole thing around or preventing the editor reparenting).

**Comment by jrieken** [comment] 2016-06-30 15:29
Yeah, the change was to tell the editor *not* to create its own keybinding context but reuse the current one. That meant the `editorXYZ` context keys have become visible to the everyone in that editor slot - namely the menu items. But since the editor moves without its context we see these issues. Now, making the editor use it's own context again, mostly solves this issue. Tho it means the editor cannot use the `resourceXYZ` keys and vice versa.

**Comment by bpasero** [comment] 2016-06-30 16:25
Extracted https://github.com/Microsoft/vscode/issues/8579

I do believe we can close this one given your revert.

**Closed** 2016-07-01 05:59 UTC
Labels: bug, important
