### ISSUE TITLE
Default Snippet doesn't respect spaces typed

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#42784] opened 2018-02-02 03:23 UTC
- VSCode Version: Version 1.20.0-insider
- OS Version: 10.13.3

Steps to Reproduce:
1. Type in a JSON file with defaultSnippets
2. Type ':' 
3. Press space
4. Select default snippet
5. Expect space before snippet to still be there - actual result is space is deleted

I would really like for the default snippet to adhere to the formatter if possible. Or even put the space there for me so I don't have to think about it. But at the least I think it should keep the space if it's typed

![bug](https://user-images.githubusercontent.com/1192452/35715101-5df836ca-0785-11e8-80b9-816c5c50aa7f.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment] 2018-02-05 08:53
I'm not able to reproduce with the following sample:
bar.json
```json
{
	"$schema": "./bar.schema.json",
	"foo": 
}
```
bar.schema.json
```json
{
	"type": "object",
	"properties": {
		"foo": {
			"required": [
				"id"
			],
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"defaultSnippets" : [{
				"body": "goo"
			}]
		}
	}
}
```

Can you add a schema and sample that shows this?

**Comment by hipstersmoothie** [comment] 2018-02-05 18:28
bar.schema.json
```json
{
	"type": "object",
	"properties": {
		"foo": {
			"required": [
				"id"
			],
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"defaultSnippets" : [{
				"body": {
                    "id": "$1"
                }
			}]
		}
	}
}
```

bar.json
```json
{
	"$schema": "./bar.schema.json",
	"foo"
}
```

Steps:
1. Type all of bar.json
2. Type a ':' just after "foo" 
3. Hit space
4. Hit enter to select default snippet
5. expect space to still be there

NOTE: bug is not there if i enter two spaces before hitting enter

I would also expect a space to be inserted in this situation also:

Steps:
1. Type all of bar.json
2. Type a ':' just after "foo" 
3. Hit enter to select default snippet
4. expect space be there

**Comment by aeschli** [comment] 2018-02-07 09:43
This looks like a bug in the completion processor when filtering the proposals after typing space:
```
   "items": [
        {
            "kind": 9,
            "label": "{\"id\":\"\"}",
            "insertText": "{\n\t\"id\": \"$1\"\n}",
            "insertTextFormat": 2,
            "filterText": "{\n\t\"id\": \"$1\"\n}",
            "textEdit": {
                "range": {
                    "start": {
                        "line": 2,
                        "character": 7
                    },
                    "end": {
                        "line": 2,
                        "character": 7
                    }
                },
                "newText": "{\n\t\"id\": \"$1\"\n}"
            }
        }
    ],
    "isIncomplete": false
```
After typing the space, the proposal still is considered valid, but not after two spaces. Not sure what the intended bahaviour is. If the proposals should stay valid after spaces, the text edit range should be updated to the new offset.

I admit that the new lines in the insertText are confusing. I fixed the JSON language service to not contain new lines in the insert text. With that change, the proposals are now filtered after the first space.

However, moving to @jrieken to clarify the expected behaviour.

**Comment by jrieken** [comment] 2018-02-26 16:03
That's not how suggestions work. You trigger suggestions, you type more characters to narrow down the result set, you select a suggestion which is then inserted from the trigger position. I agree this is a weird case because you type a space but in principal it's just suggestions.

**Closed** 2018-02-26 16:03 UTC
Labels: as-designed

**Comment by aeschli** [comment] 2018-02-26 16:19
@jrieken But I there's something weird about the filtering behaviour. It's not clear at all that after typing a space the proposal is still considered valid. It seems that it only happens when the insertText contains newline characters.

**Comment by jrieken** [comment] 2018-02-26 16:29
Well, filterText contains a space
