### ISSUE TITLE
VScode not sourcing .profile / ENV issues

### ISSUE THREAD

**Issue by blackliner** [microsoft/vscode#123280] opened 2021-05-07 12:03 UTC
It seems, that VScode now does some different things when creating the initial ENV of a terminal. If I compare the `PATH` of the VScode terminal and a Windows Terminal instance, I see differences that would point to VScode not sourcing .profile 🤔 

In my case this manifests in python packages not being found and other strange issues, all related to a half-setup ENV

```
Version: 1.57.0-insider (user setup)
Commit: 6bee0f2f3fea9df1ad45344f09b2a139c93b384f
Date: 2021-05-07T08:43:06.427Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21370
```

Steps to Reproduce:

1. see description above

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment] 2021-05-07 18:08
Duplicate of #123072

**Closed** 2021-05-07 18:09 UTC
Labels: *duplicate
