### ISSUE TITLE
Proxy popup not working

### ISSUE THREAD

**Issue by aagobbo** [microsoft/vscode#104819] opened 2020-08-17 13:18 UTC
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open Code
2. The proxy popup appears
3. try to click ok or cancel and they won't work

Does this issue occur when all extensions are disabled?: No

Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by aagobbo** [comment] 2020-08-17 13:19
[netlog.json.txt](https://github.com/microsoft/vscode/files/5084416/netlog.json.txt)

**Comment by ota-meshi** [comment] 2020-08-17 13:55
Duplicate of #104603

**Comment by aagobbo** [comment] 2020-08-17 14:10
The [#104603](https://github.com/microsoft/vscode/issues/104603#issuecomment-673852503) workaround worked for me , now I'm able to click on ok, but the proxy isn't working.

[netlog.json.txt](https://github.com/microsoft/vscode/files/5084745/netlog.json.txt)

**Closed** 2020-08-18 07:34 UTC
Labels: *duplicate, new release
