### ISSUE TITLE
Add context filter to new feature

### ISSUE THREAD

**Issue by DavidBabel** [microsoft/vscode#72676] opened 2019-04-21 10:49 UTC
I enjoy a lot this new feature 👍 
```js
"editor.suggest.filteredTypes": {
  "snippet": false,
  "class": false
}
```

But it will be awesome if we can manage some context for it, for example : 
```js
"editor.suggest.filteredTypes": {
  "snippet": {
    "onSuggest": false,
    "onRequest": true,
    // and maybe in bonus
    "inImportsStatement": false,
    "inFunction": false
  },
  "class": false
}
```

The `onSuggest` is the natural intellisense while typing.
The `onRequest` is the explicit `ctrl+space` intellisense invocation.

And in bonus we can imagine : 
The `inImportsStatement` could represent this cursor position : 
```js
import { | } from 'mylib';
```
The `inFunction` is explicit.

There may be a tons of useful filter for this feature, and it should really be considered.

**Comment by jrieken** [comment] 2019-10-08 09:37
/duplicate of https://github.com/microsoft/vscode/issues/58112

**Closed** 2019-10-08 09:37 UTC
Labels: *duplicate, feature-request, suggest
