### ISSUE TITLE
Git output shows --allow-empty-message command after commit 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4838] opened 2016-03-31 22:33 UTC
- VSCode Version: 0.10.12-alpha (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Modify a file 
2. Stage changes and add a commit message.
3. Show Git output

Actual:
Git output shows the --allow-empty-message command during the commit, but a message is required when using commit in VS Code

Is this by design? I notice it does show the commit message after pushing to GitHub.

**Comment by joaomoreno** [comment] 2016-04-04 15:01
Closing as "by design".

**Closed by joaomoreno** 2016-04-04 15:01 UTC
Labels: git, v-test
