### ISSUE TITLE
Changing Language modes for cells permanently

### ISSUE THREAD

**Issue by teddywaweru** [microsoft/vscode#140673] opened 2022-01-13 20:52 UTC
Not sure if VS Code allows for this, but would it be possible to permanently change a cell's language mode even after the text editor is closed? This is applicable in my case when running SQL scripts in Jupyter cells. Currently, once the text editor is closed, the user has to manually change each cell, which is futile if the editor is to be closed later.

**Comment by teddywaweru** [comment] 2022-01-14 06:36
That would make sense, but I'm unable to reproduce it. I've tried opening a new Jupyter Notebook in a new editor instance without the kernel selected & randomly changing the cell languages. Upon saving the document, all the cells immediately refreshed & defaulted back to Python Language on the open editor. The only other language change that 'sticks' is the markdown, which is also expected for .ipynb files... 
I still think it's the extension name that provides VS Code with the languages mode, & why they'd appear as the first ones on the list(also why the kernel suggestions would be Python env.s).
Thank you for your time on this...Hopefully there'll be a breakthrough. 👍

**Comment by greazer** [comment] 2022-02-15 20:58
Doesn't appear that changing the language for a cell is persisted at all, on opening the ipynb as json, language is not stored per cell. I expected to see something in the cell metadata. Even if there is no metadata notebook standard for this, it seems like we should be persisting and setting it ourselves so the user can actually make use of the language selectors as intended.

**Comment by rebornix** [comment] 2022-02-16 19:21
@roblourens I think we should think about saving the language info in custom cell metadata when users pick a language which is different from the global language (say Python).

**Comment by rebornix** [comment] 2022-03-15 01:14
This particular issue is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/4757. It's related to polyglot and cell magics. I don't think we currently have a story for it yet. @greazer you have put it in the March milestone, do you expect anything in particular for this to be done this month?

**Closed** 2022-03-16 00:12 UTC
Labels: bug, nb-golden, notebook-serialization
