### ISSUE TITLE
ES6 syntax highlight seems not working

### ISSUE THREAD

**Issue by leechen** [Microsoft/vscode#4082] opened 2016-03-13 06:32 UTC
I updated to latest version, the syntax highlight is only partially working for ES6. Here is my jsconfig.json at the root of project:
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}

keywords such as "if", "return", "default" are colored correctly, but keywords such as "let", "import" are not. I am using react with file extension as .js

**Comment by aeschli** [comment] 2016-03-14 09:09
duplicate of #3903

**Closed by aeschli** 2016-03-14 09:09 UTC
