### ISSUE TITLE
python coding folding（python 代码折叠问题）

### ISSUE THREAD

**Issue by zhuhonglinX** [Microsoft/vscode#34871] opened 2017-09-23 07:55 UTC
![image](https://user-images.githubusercontent.com/17999964/30771292-bdd93b1e-a076-11e7-9cca-73428e973126.png)

如图，当我将python代码折叠起来时，函数与函数之间的空行也会被收起来，我希望及时折叠后的函数之间能有空行，参考 sublime text 的 python 折叠
As shown in the figure, when I put the python code folded up, the blank line between the functions will be put away, I hope that the functions can be folded between the blank line.

**Comment by wangweixuan** [comment] 2017-09-23 12:52
Duplicate of #3353.
It should be fixed in the next release.

**Comment by zhuhonglinX** [comment] 2017-09-24 01:52
thank you!

**Closed** 2017-09-25 13:42 UTC
Labels: editor, editor-folding
