### ISSUE TITLE
Ctrl-clicking a link shows 'no definition found' error

### ISSUE THREAD

**Issue by Benjamin-Davies** [Microsoft/vscode#26269] opened 2017-05-09 06:00 UTC
- VSCode Version: 1.10.2 & 1.12.1
- OS Version: Windows 10 Home - Version 1607

Ctrl-clicking a link shows 'no definition found' error, as well as opening the link.
Please note I have only tested this in javascript.

![giphy](https://cloud.githubusercontent.com/assets/25046874/25869265/d04c6c96-3553-11e7-8a8e-b21ecef41fe7.gif)

Steps to Reproduce:
1. Place a commented link,
2. Control click the link,

**Comment by egamma** [comment] 2017-05-09 07:13
@Benjamin-Davies can you please clarify the steps to reproduce this problem by including an animated gif.

**Comment by King66** [comment] 2017-05-10 05:54
https://github.com/Microsoft/vscode/issues/23978

**Comment by egamma** [comment] 2017-05-10 07:32
@King66 thanks for tracking down the duplication.
Closing as a duplicate of @23978

**Closed by egamma** 2017-05-10 07:32 UTC
Labels: duplicate
