### ISSUE TITLE
Visual Code should reopen files that was closed when reloading

### ISSUE THREAD

**Issue by oxydron** [Microsoft/vscode#16146] opened 2016-11-28 13:32 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 8.1 Pro N

Steps to Reproduce:

1. Open some documents
2. Install a plugin
3. Reopen Visual Code to use the new plugin

After this, every window is closed, then I need to re-open them.

**Comment by chrmarti** [comment] 2016-11-29 00:13
Duplicate of #207

**Closed by chrmarti** 2016-11-29 00:13 UTC
Labels: duplicate
