### ISSUE TITLE
HTML formatting is a mess

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#20237] opened 2017-02-08 23:58 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open the [attached HTML file](https://github.com/Microsoft/vscode/files/762267/Reporting.zip) in VS Code.
2. Format the file using keyboard shortcut `<SHIFT>+<ALT>+<F>`.
1. Look at the JavaScript code inside the html file ...

![vscode html formatting result](https://cloud.githubusercontent.com/assets/9283914/22763042/b8843978-ee62-11e6-8a79-a5b96a4399ef.png)

---
**[settings.json.zip](https://github.com/Microsoft/vscode/files/762271/settings.json.zip)**

**Comment by mjbvz** [comment] 2017-02-09 02:22
I believe this is a duplicate of  #19813

A fix is checked into master and we plan on releasing a 1.9.1 recovery build with the fix as well

**Closed by mjbvz** 2017-02-09 02:22 UTC
Labels: duplicate, format
