### ISSUE TITLE
Vscode 1.12 no longer obeys 'sortText' in completion items (from language server)

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#26096] opened 2017-05-06 00:01 UTC
- VSCode Version: VSCode Version: 1.12 (latest today May 5th 2017)
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Install this vsix file: http://s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-concourse-0.0.2-201705052220.vsix
2. Create a text file called 'pipeline.yml' and put this text in it:

```
resources:
- name: fff
  type: foo
  <*>
```

The `<*>` marks the spot where to put the cursor. So delete it, and put your cursor there.

Press CTRL-SPACE to invoke content assist.

The order of the content assist items that appears in vscode 1.11 is like this and is the correct order:

- check_every
- source
- ← groups
- ← jobs
- ← resource_types
- ← - name

After updating to vscode 1.12 today, the order changed to this:

- ← groups
- ← jobs
- ← resource_types
- ← - name
- check_every
- source

The completion items my extension produces explicitly sets a `sortText` to get exactly the desired ordering. Somehow, it seems like VScode 1.12 no longer consults the sort text but instead just uses the label for sorting. I double-checked that my extension indeed sets the sort-text. Below is some log output showing `${sortText}:${label}` for these completion items as 'proof'.

```
00000: check_every
00001: source
00002: ← groups
00003: ← jobs
00004: ← resource_types
00005: ← - name
```

**Comment by kdvolder** [comment] 2017-05-06 00:10
I uninstalled vscode 1.12 and am sticking with 1.11 for now. Unfortunately this little bug put completion items in almost the opposite order of what I'd want. The `←` means the completion applies to a further removed context (requires a de-indent in the yml structure). So they tend to be the ones that are least interesting and should go on the bottom. Unfortunately, the current sorting mechanic actually puts the labels with the most arrows right at the top).

**Comment by egamma** [comment] 2017-05-08 07:29
@kdvolder you can change the sort order of snippets by using the setting ` "editor.snippetSuggestions": "bottom",`

**Comment by martinlippert** [comment] 2017-05-08 08:42
@egamma how is the sorting of snippet suggestions related to the sorting of completion items? I think @kdvolder refers to the sorting of completion items only.

**Comment by jrieken** [comment] 2017-05-08 08:46
@martinlippert A completion item can be of kind `snippet` which makes it conform to the `snippetSuggestions`-sorting rules

**Comment by martinlippert** [comment] 2017-05-08 08:48
You mean we should change the completion items that we would like to show up first to be of kind `snippet`and then change the settings? (all as a workaround)?!?

**Comment by martinlippert** [comment] 2017-05-08 08:51
If the sortText issue gets fixed in a recovery release, I think we would prefer to wait for that before we release the updates of our language servers... :-)

**Comment by jrieken** [comment] 2017-05-08 10:38
> You mean we should change the completion items that we would like to show up first to be of kind snippetand then change the settings? (all as a workaround)?!?

No, my question was if your (unsure if @kdvolder and you work on the same extension) extension uses the snippet type or if you have ordinary/mixed completion items. There has been no change to `sortText` but a change that sorting updates when more text is being typed. That makes is two steps: no text left of the cursor and items get sorted lexicographical using label or sortText, when there is text left of the cursor we rank each item wrt how well it matches that text and sort by those ranks. (Before we kept the sorting stable but revealed the best match, often resulting in the second, third best match being far away)

**Comment by jrieken** [comment] 2017-05-08 10:55
So, what happens with the step from [above](https://github.com/Microsoft/vscode/issues/26096#issue-226719584) is a little more complicated. When I said above *"text left of the cursor"* it actually means the text an individual suggestion selects for being replaced with its insert text. For above sample (see below screen shot) there are a few completions that select the leading two whitespaces for replacement while some other don't. That makes some completions get a score according to how well they match and some don't get a score because no text for matches yet. When comparing all of them we favour those that are more [specific](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/completionModel.ts#L156)

![screen shot 2017-05-08 at 12 45 37](https://cloud.githubusercontent.com/assets/1794099/25801236/e116d466-33ec-11e7-90fe-7372f4de505f.png)

Unsure what to do next with this, but this isn't the issue that snippets now get demoted. @egamma I'll pick a better issue which is about snippets and our (now) unlucky default to sort them at the bottom. This issue is still to be discussed.

**Comment by jrieken** [comment] 2017-05-08 10:56
Using https://github.com/Microsoft/vscode/issues/26182 to track the unhappy snippet sorting

**Comment by martinlippert** [comment] 2017-05-08 14:52
So basically we would like to list proposals that do not replace the two whitespaces first and then proposals that do replace those two whitespaces in front of that line. Is there a combination of properties for the completion items that would allow this to work?

**Comment by martinlippert** [comment] 2017-05-08 14:54
what would happen if we remove the two leading whitespaces on the `filterText`?

**Comment by kdvolder** [comment] 2017-05-08 16:29
If we remove the whitespace from filtertext the items disapear completey. It took me some time to figure this out. I guess the 'filter' picks up the text in the edit range and matches that against the filter text. Since that text starts with spaces (so we can replace the leading space to cause a 'de-indent' effect) we have to include spaces in our filter text.

**Comment by kdvolder** [comment] 2017-05-08 17:14
>  or if you have ordinary/mixed completion items

All our items are the same w.r.t. to using snippets (all of them have snippet flag turned on). Not all of them really need it, but it was easier to just always turn it on rather than trying to determine precisely when its needed or not).

So I think Jim's right. This has nothing to do with sorting of snippets versus non-snippets.

After Jim's explanation about different sorting strategies depending on whether we have text left of cursor or not. I think I understand what's happening (thanks Jim). To paraphrase the 'deindented' proposals score higher because they select some spaces in front of the cursor, which makes them be considered 'more specific' than the ones that don't. Correct?

I think I understand the motivations behind vscode sorting rules when 'more text is being typed', to allow for filtering a completion list without having to make another request on the language server after I typed some extra character(s).

The thing is, your rules for 'more text is being typed' are already being used even though I haven't actually typed anything yet. So maybe that is wrong? It seems to me that, at least, immediatly after asking the language-server for a list of completions, you should assume its 'sortText' reflects the intended sorting order accurately and not try to second-guess sorting order based on other heuristics.

The fact that the language-server sets sortText explicitly rather than just leave it blank, should be taken as pretty strong evidence the server is trying to enforce a very particular ordering.

**Comment by martinlippert** [comment] 2017-05-09 16:45
Hmmm... This is blocking us from shipping an update for your language servers at the moment. So I would love to learn whether there is a workaround possible to get our proposals showing up in the "right" order (from the point of view of our language server) or if we need to wait for a change or fix in vscode. Any suggestions or ideas?

**Comment by jrieken** [comment] 2017-05-10 07:55
> The thing is, your rules for 'more text is being typed' are already being used even though I haven't actually typed anything yet. So maybe that is wrong?

Well, not necessarily agreeing because the two spaces have been typed (or smartly inserted). I think the problem is more towards the score-algorithm we run. That makes no a difference if a space matches with a space or if two other letters match. Let we think about trimming whitespace (or ignoring) when running the scoring-logic. That will then land in insiders soon'ish (end of this week, early next week) but won't make the cut for the recovery release

**Comment by martinlippert** [comment] 2017-05-10 09:57
Can you explain the exact logic of how proposals are sorted? I am confused how filterText, sortText, and the "magic" that you described above is playing together. Maybe if I understand the exact meaning of those and their combined behavior, I can dive deeper. That would be awesome.

(also a pointer to the code would be great, then I would parse the logic from the code myself...) :-)

**Comment by kdvolder** [comment] 2017-05-10 15:46
> Well, not necessarily agreeing because the two spaces have been typed

My point was if they were typed, it was before making the CA request to the server. So what I mean is, the server new about the spaces and has exactly answered a list of items with exactly intended sorting order, for exactly the current contents in the editor. So there should be no uncertainty on how the server intended the items to be sorted. So... applying these heuristics in such a case seems like a mistake to me.

But yes, I understand its complex :-)

Your idea of special casing and ignoring leading white-space to be counted as 'matching' will probably return some sanity in this case.

> and some things in the API (sortText, filterText) became weaker.

I wonder whether this effectively makes `sortText` obsolete, it seems language server now has very little, if any control over the sorting order of its completions. Are there actually any cases where `sortText` still has an effect now?

**Comment by jrieken** [comment] 2017-05-10 15:53
> So... applying these heuristics in such a case seems like a mistake to me.

I understand where you are coming from but the problem is that most language service return results based on a different positon, like the `console.lo` case which returns more than `log`. Unsure if would then still be able to filter out other member suggestions...

> Are there actually any cases where sortText still has an effect now?

Only when no suggestion has selected a word yet (left of the cursor), a sample would be `console.<cursor>` with `log`, et al. Then we would use the sort text.

**Comment by kdvolder** [comment] 2017-05-10 15:59
What would happen if we made our completions lazy resolved (in which case, I guess you do not have the edit ranges, until its time to apply the completions). How would things work in this case? 

I'm asking because I'm wondering if this could be a possible workaround for us to have to `sortText` count again.

**Comment by kdvolder** [comment] 2017-05-10 16:15
> most language service return results based on a different positon, like the console.lo case which returns more than log. Unsure if would then still be able to filter out other member suggestions...

To be honest that's a bit of surprise to me. I thought it was up to the server to return a precise list and not rely on smarts in the client to do the job. So our server(s) returns precise results based on the current document state. I see how supporting 'sloppy' servers kind of makes this not so straightforward to resolve. 

Would you be able to use the presence of an explicit `sortText` as a strong enough signal that the server is 'precise' and you could back of the heuristics *only* in that case?

**Comment by kdvolder** [comment] 2017-05-10 19:06
> What would happen if we made our completions lazy resolved

While I have no idea about exactly how the detailed sorting mechanics in vscode play out.... Yep. Looks like that works as a workaround for us. It seems that by depriving vscode the info about the `editText` in the unresolved completion items, we are falling back to sorting based on `sortText` for this example. 

I feel a little uncomfortable about this to be honest. It works now for this case, it seems, but it feels too much like a fluke/hack and I fear it might break again in future vscode releases.

So I'd still like @jrieken (if/when you have the time) to explain how the sorting mechanics for unresolved items which only compute edits upon resolution are (supposed to be) sorted/filtered in general. (I.e. lacking the edit-range, what precisely will filter text be matched against? Since, obviously its not being matched against the text inside the edit range in this case).

**Comment by jrieken** [comment] 2017-05-11 07:02
> So I'd still like @jrieken (if/when you have the time) to explain how the sorting mechanics for unresolved items which only compute edits upon resolution are (supposed to be) sorted/filtered in general.

In the absence of an text edit we fallback to use the current word which is computed using a language specific regex.

**Comment by martinlippert** [comment] 2017-05-11 10:07
@jrieken many many thanks for all the details, much much appreciated. I think this is indeed an interesting discussion. The question how you divide the control over the content-assist proposals between the editor (client) and the language server is indeed complex and difficult.

We try to be very very smart about which proposals to deliver to the client and in which sequence they should be presented to the user in order to provide the best possible user experience. We do that because we think the language server deeply understands the context and the structure of the file and what proposals make the most sense in a certain situation.

On the other hand it seems like you have to deal with language servers that aren't that smart, so that the editor needs to do a bunch of work in order to provide an excellent user experience. This is the reason why you implemented the new ranking that affects the ordering of proposals after they got delivered (and maybe pre-sorted) by the language server - if I understand this correctly.

Can you explain in more detail what those language servers exactly return for those not-so-smart completion proposals? (for example for the console.log/debug/error case) Do they return a sortText at all? Or do they rely on the client to sort them? And match them against existing characters?

One of my thoughts was: if a language server explicitly provides a sortText to put the completion proposals in an order, the client should not override this sorting.

**Comment by martinlippert** [comment] 2017-05-11 10:09
@jrieken can you point me to a few language servers that return those non-sorted proposals, like the console.log/error/debug case? Would love to take a look myself to understand this in more detail. Many many thanks!!!

**Comment by jrieken** [comment] 2017-05-15 15:56
> On the other hand it seems like you have to deal with language servers that aren't that smart, so that the editor needs to do a bunch of work in order to provide an excellent user experience. 

Yeah, and we don't actually think that this is a bad thing because it allows us to sort and filter by our rules. Sample (I am aware of) are TypeScript and Roslyn for C# and they always suggest completions based on the 'larger scope'. For instance, workspace symbol search doesn't usually work like this and we get very different behaviours between different languages, e.g some only do prefix search, some do camel-case search but not subsequent-match search etc etc.

**Comment by kdvolder** [comment] 2017-05-15 16:25
> e.g some only do prefix search, some do camel-case search but not subsequent-match search etc etc.

Hmm, yeah, but if a language server is doing 'prefix search' in the completions, then it doesn't matter whether vscode is capable of a more 'fuzzy' matching logics, since there will only be prefix-matched results in the pool you have to match against.

I think the only way to really make this consistent between different servers would be to more precisely describe in the LSP document what exactly a server is expected to return and what kind of search and filtering is applied on the client side. I don't think LSP spec is very clear on this at the moment. (Which is not a VScode issue I know, but something to raise against the Spec, I'll ponder it some more, but I'll probably raise a 'request for clarification' with the spec about this.

Anyhoo... just being practical at the moment, I think the most reasonable thing to do about the vscode issue right now, is maybe simply don't match against spaces for the 'scoring' of completions, like you proposed. Since they are effectively 'invisible' and, as a user, they don't feel like they are part of my 'query' I think that just makes good sense.

**Comment by martinlippert** [comment] 2017-05-17 08:18
> Yeah, and we don't actually think that this is a bad thing because it allows us to sort and filter by our rules. Sample (I am aware of) are TypeScript and Roslyn for C# and they always suggest completions based on the 'larger scope'. For instance, workspace symbol search doesn't usually work like this and we get very different behaviours between different languages, e.g some only do prefix search, some do camel-case search but not subsequent-match search etc etc.

@jrieken fully understand and agree to the solution to ignore the spaces for the moment. However, I would love to learn more about what you would suggest how our language server should implement those completion proposals in the future. I think Kris described what we would like to offer to the user (as completion proposals, including the sequence/sorting in which they should appear). But let me know if you have more questions about that. Would love to hear your advice on this.

**Comment by jrieken** [comment] 2017-05-23 14:58
Understood, the spec isn't very clear in that area and sortText-bit became weak after the latest changes.

Wrt how to filter on the server, I would suggest to go with a subsequent-substring-matcher. That is easy to implement, fast at runtime and enables all sort of prefix, camel-case, and fuzzy filtering in the editor. In fact, our filter performs this checks [always](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/filters.ts#L471) to know if further (expensive) matching will pay off. It will block super smart features like accounting for [typos](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/filters.ts#L666) etc but if you want to filter on the server, go with that one. 

On the `sortText` topic another idea has been discussed in https://github.com/Microsoft/vscode/issues/26944#issuecomment-303319615. When an item has a `sortText`-property we could use that when computing the rank. That will only define the value of the (sort-)rank, not if the item appears for which we use `filterText` or `label`. Challenge is that most completions define the `sortText`-property as an absolute value like `0001`, `0002`, `0003` etc. We might be lucky tho: Scoring absolute values will likely always yield in a rank of -1, in which case we fallback to the initial sort which is solely based on the sort text. Ideas, feedback?

**Comment by kdvolder** [comment] 2017-05-23 15:33
> Ideas, feedback. 

Just some vague thoughts :-) 

About the 'absolute values' like '0001', '0002' etc. In our case, this is because we use a kind of pattern matching to filter the completions and this matcher also returns a 'score'. So we want to have the items appear in the order with the highest score first. The absolute values are merely a roundabout way to accomplish that goal.

The good news is that, for the most part, the goals of our sorting/scoring are much in line with what vscode does. I.e. to try and put the things that 'match better to what a user typed' at the top.

So for the most part, I think that a user wouldn't notice that 'sortText' isn't quite working the same way as the server intended, since, the end-result will usually be very similar anyway. The only thing here that made this obviously wrong was the unfortunate interpretation of space in the match. 

The bad news... We also incorporate some heuristics that aren't purely based on textual matching but relate to some kind of 'distance' between originating context. I think these heuristics mostly matter when the user's query itself is 'weak' (e.g. empty string) or when there are several matches that are textually very similar, but come from different contexts. For example several context may have properties with identical names. So, in other words, even though I 'typed a strong query' it still doesn't strongly distinguish two matches, because they are textually identical. This is when the sorting based on 'contextual distance' would really need to come into play.

So summarizing, I think this is where we are at:

- if the 'query' is empty, you have a score of -1 and fall back on sortText => good (especially if we to the special case for leading spaces).
- if the 'query' is 'strong', you show the best matches textually 
     => good, except when several 'good' matches are virtually indistinguishable based on textual matching rules. This is when things only the server knows about, such as 'contextual distance' would need to come into play.

**Closed** 2017-05-24 15:59 UTC
Labels: bug, suggest

**Comment by jrieken** [comment] 2017-05-26 09:21
This is fixed by ignoring leading whitespace when doing the ranking and filtering. After discussions with @aeschli we decided that `sortText` is used for the initial sort and that we sort by rank as soon as there is something to rank against. With the improved whitespace ignore-behaviour this should now be a lot more logical.

**Comment by kdvolder** [comment] 2017-05-26 15:21
What about adding another special case for when there is a ranking, but the ranking of two items are identical. Maybe it make sense to also consider the original sortText to order such elements relative to each other. I think that that should tie up the last loose end:

> ... => good, except when several 'good' matches are virtually indistinguishable based on textual matching rules. This is when things only the server knows about, such as 'contextual distance' would need to come into play.

**Comment by jrieken** [comment] 2017-05-26 17:07
That's exactly how it is [implemented](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/completionModel.ts#L177), when score (of the ranking operation) is equal to another score we fall back to the initial sorting which is based on `sortText` and/or `label`

**Comment by roblourens** [comment] 2017-06-06 00:25
Hm, tl;dr for verification?

**Comment by jrieken** [comment] 2017-06-06 07:51
to *verify* have a completion item provider (extension) that returns two items. One with sort text `aaa` and label `ABCabc` and another one wth sort text `zzz` and label `ABC_abc`. Trigger suggest on an empty line, suggestions should be sorted based the sort text (`[ABCabc, ABC_abc]`, type `a` sorting shouldn't change, type another `a` sorting should be changed now to `[ABC_abc, ABCabc]`
