### ISSUE TITLE
[feature request] support for CSS nested syntax (CSS Nesting Module)

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#200456] opened 2023-12-09 20:13 UTC
The new syntax is describe in the [CSS Nesting Module](https://www.w3.org/TR/css-nesting-1/).

And here's the [Mozilla MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting).

It works in all browsers today!

Example code:

```js
.foo {
  background: royalblue;

  @media (min-width: 500px) {
    background: deeppink;
  }
}
```

Syntax currently breaks when using CSS nesting features:

https://github.com/microsoft/vscode/assets/297678/5d6c83b3-bdea-48ef-ae10-9e91c8088ed4

**Comment by aeschli** [comment] 2023-12-11 13:59
duplicate of https://github.com/microsoft/vscode/issues/147824

We're waiting for support in syntax highlighting: https://github.com/microsoft/vscode-css/issues/9

**Closed by aeschli** 2023-12-11 13:59 UTC
