### ISSUE TITLE
Rush node_modules autocomplete fail

### ISSUE THREAD

**Issue by totomakers** [microsoft/vscode#80743] opened 2019-09-11 20:09 UTC
- VSCode Version: 1.38.0
- OS Version: Windows_NT x64 (10.0.17134)

Steps to Reproduce:

1. Clone https://github.com/RDeluxe/rush-repro-955
2. Go to ` libraries/dtos/src/dtos/user.ts`
   You will have a compiler error. Normally vscode should be able to auto import the missing decorators from class-validator

**Additional informations:** 

+ Related issues 
  + https://github.com/microsoft/web-build-tools/issues/955 
  + https://github.com/microsoft/TypeScript/issues/28689
+ Webstorm autocomplete works
+ The [repo](https://github.com/RDeluxe/rush-repro-955) use [rushjs](https://rushjs.io/) with [pnpm](https://pnpm.js.org/)

Rush strategy is to create a clean `node_modules` tree in `/common/temp/node_modules`.
After that rush create for each "packages" a new `node_modules` tree with symlink.

![Imgur](https://i.imgur.com/rA6RATF.jpg)

**Comment by mjbvz** [comment] 2019-09-14 00:54
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new)

(Although this may be a duplicate of https://github.com/microsoft/TypeScript/issues/28689)

**Closed by mjbvz** 2019-09-14 00:54 UTC
