### ISSUE TITLE
Remote file/folder picker should allow me to create files / folders

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89442] opened 2020-01-28 11:16 UTC
![capture](https://user-images.githubusercontent.com/1931590/73259378-fc92d500-41c7-11ea-8e5a-8f3c0210b55f.png)

**Comment by alexr00** [comment] 2020-01-28 14:22
Duplicate of https://github.com/microsoft/vscode/issues/71425

**Closed** 2020-01-28 14:23 UTC
Labels: *duplicate
