### ISSUE TITLE
Expand selection destroys multiple cursors context

### ISSUE THREAD

**Issue by arjamizo** [Microsoft/vscode#40516] opened 2017-12-19 13:17 UTC
- VSCode Version: 
```
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version: Ubuntu 16.04

Steps to Reproduce:

0. run `code --disable-extensions`
1. open document (html for example)
2. add multiple cursors (`alt+shift+up/down`, `ctrl+mouse clicks` | `shift+mouse clicks` (depends on current config))
3. press `alt+shift+left`|`right`
4. observe losing multicursor

Reproduces without extensions: Yes

**Comment by jrieken** [comment] 2018-01-03 10:20
dupe of #4795

**Closed by jrieken** 2018-01-03 10:20 UTC
Labels: editor
