### ISSUE TITLE
hangs while opening HTML file

### ISSUE THREAD

**Issue by alfalabs** [Microsoft/vscode#4830] opened 2016-03-31 14:10 UTC
- VSCode Version:0.10.11
- OS Version:Win7

While opening HTML file, toast message appears:

> [Info] HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait.

then windows popup titled Visual Studio Code:

> The window is no longer responding
> You can reopen or close the window or keep waiting.

Steps to Reproduce:
1. open an HTML file

**Comment by aeschli** [comment] 2016-03-31 16:19
@alfalabs Do you have any extensions installed that could cause that? In the built-in HTML support we don't do any fetching of CSS.

**Comment by alfalabs** [comment] 2016-03-31 16:31
@aeschli 
Yes, I installed VScode yesterday and a bunch of extensions before running it.
I would expect that a third party extension should never cause VScode to hang.
This issue should be reopened as to protect VScode from bad extensions.

**Comment by egamma** [comment] 2016-04-02 16:19
@alfalabs reopening, but now please provide detailled information about your setup:
- which extensions do you have installed
- attach the html file that caused the hang

**Comment by alfalabs** [comment] 2016-04-05 12:43
@aeschli @egamma 
In my original post, the offensive extension is mentioned in message: " HTML CSS Class Completion"
Here is the link: https://github.com/Zignd/HTML-CSS-Class-Completion
Attached is the index.html file

[index.zip](https://github.com/Microsoft/vscode/files/204451/index.zip)

**Comment by egamma** [comment] 2016-04-06 08:08
// CC @alexandrudima

**Comment by zalayeto** [comment] 2016-07-29 10:01
It is happening to me as well. I'm also using HTML Class Completion extension.

**Comment by levka9** [comment] 2016-07-29 19:19
I've same issue.

![image](https://cloud.githubusercontent.com/assets/1710431/17260683/718ce54a-55da-11e6-9413-
20a276e7a02f.png)

**Comment by mrmlnc** [comment] 2016-07-29 19:31
@levka9, please, update the image.

**Comment by ventsislav-georgiev** [comment] 2016-08-17 11:25
It is still reproducible with the latest version: `1.4.0`
This extension (https://github.com/Zignd/HTML-CSS-Class-Completion) is causing VSCode to freeze and even the dialog that pops-up (`Wait`, `Reopen`, `Close`) does not handle it.

I am able to reproduce it when I open `html` file in a fairly big project. It is not reproducible with smaller projects. It may be related to specific CSS loading or something and not to the project size itself.

**Comment by davidrensh** [comment] 2016-08-25 02:22
Resolved by uninstall HTML Class Completion extension in one click with restart vs code.

**Comment by KioriSun** [comment] 2016-09-23 18:56
I've had this problem also, and in the previous version even major crashes.
Removed the extension.

**Comment by alexandrudima** [comment] 2016-09-26 22:31
I have tried to reproduce with the HTML contents of `index.zip` and failed to do so.

I can continue to investigate @ventsislav-georgiev @davidrensh @KioriSun -- is it perhaps something about the folders you open? Does this extension traverse all the files in a folder, possibly unbounded?

**Comment by hanumanc** [comment] 2016-10-06 05:42
Faced same issue problem. Thank you.
Resolved by uninstall HTML Class Completion extension

**Comment by KioriSun** [comment] 2016-10-09 15:56
@alexandrudima my folder had thousands of files(and css's with thousands of lines), and I always had some .php files pre opened, but even if not, after a certain point it got stuck on the whole "CSS Class Completion: Fetching CSS rules from CSS files, please wait."
I guess it was just way too many files for the extension to handle. It's weird also because it didn't happen when i installed it right away, but rather after a few open and closes of the program.
Try using this with a really big project and see how it goes.

**Comment by alexandrudima** [comment] 2016-10-27 20:11
The workaround so far is everyone is recommending to uninstall the extension. I suggest we implement a registry of known "slow" extensions and show this in vs code next to the extension. i.e. "This extension is known to cause performance problems". We cannot protect against high CPU code, we are not an OS.

**Comment by alexandrudima** [comment] 2016-12-06 14:33
At this point everyone is in agreement that this is an issue with the extension, therefore nothing actionable for me.

**Closed by alexandrudima** 2016-12-06 14:33 UTC
Labels: freeze-slow-crash, needs more info
