### ISSUE TITLE
vscode is using my whole bandwidth

### ISSUE THREAD

**Issue by yasharne** [microsoft/vscode#98435] opened 2020-05-23 15:40 UTC
- VSCode Version: 1.45.1
- OS Version: ubuntu 18.04 5.3.0-53-generic

Steps to Reproduce:

1. install `IBM Blockchain Platform` package failed due to errors described [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2355)
2. I realized I have consumed 90Gb in six hours
3. I used nethogs to see which process is using the most bandwidth and realized this process is using the most:
```
yashar   14890  7.2  0.3 415812 58660 ?        Sl   19:35   1:19 /usr/share/code/code --type=utility --field-trial-handle=7522302350733503515,14802299922319282458,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --no-sandbox --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --service-request-channel-token=2187307998966465767 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```
here is the netdata output for the bandwidth usage, I stopped vscode after a while:
![image](https://user-images.githubusercontent.com/7656049/82734519-b4785f00-9d30-11ea-86ca-3491ae00b8cb.png)
`vscode` has used up to 40Mb/s

Does this issue occur when all extensions are disabled?: No

**Comment by sstone1** [comment] 2020-05-26 07:48
@kieferrm @sandy081 this is most likely a duplicate of #98366 - the marketplace entries for our extension seem to be corrupted such that it repeatedly downloads an older version than the one we've published.

**Closed** 2020-05-26 14:43 UTC
Labels: *duplicate, important
