### ISSUE TITLE
Terminal widths not correctly restored after reload

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#117367] opened 2021-02-23 11:13 UTC
Testing #117265

Version: 1.54.0-insider
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:17:41.287Z
OS: Linux x64 5.8.0-43-generic

- open a terminal and split it
- change the size to make one smaller than the other
- reload window with the command from the command prompt. Terminals have the same width again

![terminal-restore-sizes](https://user-images.githubusercontent.com/6461412/108835905-6e5a6f80-75d0-11eb-9e8b-30b00161c9b2.gif)

**Comment by Tyriar** [comment] 2021-02-23 18:31
I hit this as well last week, you reloaded too quickly after changing the size as saving the state is debounced. Closing as designed

**Comment by eamodio** [comment] 2021-02-23 18:54
I've waited over 10s, multiple times and I never seem to get the split size restored.

**Comment by meganrogge** [comment] 2021-02-23 19:59
@eamodio I can't reproduce that. Can you pls attach a gif?

**Comment by eamodio** [comment] 2021-02-23 21:37
![terminal](https://user-images.githubusercontent.com/641685/108911573-68c35080-75f5-11eb-9b15-eb973d8fdbd9.gif)

**Comment by meganrogge** [comment] 2021-02-23 21:42
Can now repro this thanks

**Closed** 2021-02-25 04:32 UTC
Labels: bug, integrated-terminal
