### ISSUE TITLE
Downloading VS Code insiders from @vscode/test-electron is repeatedly failing today

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#224295] opened 2024-07-30 13:13 UTC
Today, almost all of my test runs on Insiders builds are failing because the `@vscode/test-electron` package is failing to download the Insiders build of VS Code from GitHub actions:

```
Running flutter_test_debug tests folder in workspace flutter_hello_world
Attempting to download VS Code attempt #1
- Resolving version...
✔ Validated version: insiders
- Found at https://update.code.visualstudio.com/latest/darwin-arm64/insider?released=true
✖ Error downloading, retrying (attempt 1 of 3): @vscode/test-electron request timeout out after 15000ms
- Found at https://update.code.visualstudio.com/latest/darwin-arm64/insider?released=true
✖ Error downloading, retrying (attempt 3 of 3): connect ECONNREFUSED 13.107.246.69:443
- Found at https://update.code.visualstudio.com/latest/darwin-arm64/insider?released=true
✔ Found at https://update.code.visualstudio.com/latest/darwin-arm64/insider?released=true
- Downloading (125.64 MB)
✔ Downloaded VS Code into /Users/runner/work/Dart-Code/Dart-Code/.vscode-test/vscode-darwin-arm64-insiders
- Resolving version...
Running tests with pre-downloaded VS Code
✔ Validated version: insiders
TimeoutError: @vscode/test-electron request timeout out after 30000ms
############################################################
```

It does sometimes work, so re-running the job multiple times often causes it to pass, but the huge majority of attempts are failing.

**Comment by DanTup** [comment] 2024-07-30 13:23
Ah, yes - there's a lot of red on https://azure.status.microsoft/en-gb/status. I guess this is all related.

**Comment by rzhao271** [comment] 2024-12-19 18:01
I assume the issue is resolved by now. Let me know if it isn't.

**Closed by rzhao271** 2024-12-19 18:01 UTC
