### ISSUE TITLE
Custom snippets - prefixes made of symbols

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32427] opened 2017-08-13 18:51 UTC
- VSCode Version: 1.15
- OS Version: win7x64

My snippet in "javascript.json" file:

```
"(function() {...})()": {
  "prefix": "()()",
  "body": [
    "(function() {",
    "\t",
    "})()"
  ],
  "description": "(function() {...})()"
}
```

So, the prefix is just made of symbols - ()()
It will show snippet for "f()()", and it will show snippet for "()()f", but not just ()()
Has it been made like this for a reason, or is it a bug?

**Comment by jrieken** [comment] 2017-08-17 07:19
Assuming you talk about 24x7 Intellisense (please confirm), then 'yes' this is on purpose because we only automatically compute suggestions when a *word* is being typed. In all other places, IntelliSense needs to invoked manually (Ctrl+Space). Alternatively, you can enable tab-completion and hit tab to expand a snippet.

**Comment by user3323** [comment] 2017-08-18 10:10
@jrieken 
Shame on me, but I don't know how to check do I use Intellisense 24/7 or not :) Can you help?

**Comment by jrieken** [comment] 2017-08-18 12:49
> Shame on me, but I don't know how to check do I use Intellisense 24/7 or not :)

No worries, the default is 'on' so it's likely that you use it. In JavaScript just type a word like `con` and check that after the first character IntelliSense is shown (without you needed to press ctrl+space)

**Comment by user3323** [comment] 2017-08-20 00:24
OK, I got it. Yeah, I have IntelliSense on 24/7.

**Comment by jrieken** [comment] 2017-08-21 06:09
Ok, thanks. I am closing this as a duplicate of #32201 which is about different trigger rules for 24x7 IntelliSense.

**Closed** 2017-08-21 06:09 UTC
Labels: duplicate, snippets
