### ISSUE TITLE
Errors deploying emmet abbreviations in scss files

### ISSUE THREAD

**Issue by denisneposeda** [microsoft/vscode#113153] opened 2020-12-19 13:19 UTC
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch
2. Create SCSS file
3. You write an abbreviation for emmet "v: h", but when used instead of visibility: hidden; it turns out v: map-has-key.

This is the problem with most emmet shortcuts. After update 1.52, there was such a bug and mostly shows math functions. I think it has something to do with "98041: Emmet ignores selection on Evaluate Math Expression".

I ask you to solve this problem, because writing emmet in scss is real hell right now.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment] 2020-12-31 21:23
@denisneposeda we've upgraded to a newer version of Emmet. 

For CSS, Instead of writing `v: h` you can now write `v:h` or `vh` directly.

For SCSS, both `v:h` and `vh` should work, but only `vh` works right now for some reason, so I will mark this issue as a bug.

**Comment by rzhao271** [comment] 2020-12-31 21:26
Duplicate of #112675

**Closed** 2020-12-31 21:54 UTC
Labels: *duplicate, bug, emmet
