### ISSUE TITLE
vscode timeout waiting for debuger

### ISSUE THREAD

**Issue by canvas-J** [Microsoft/vscode#60633] opened 2018-10-11 12:49 UTC
Issue Type: <b>Bug</b>

vscode timeout waiting for debuger
i can't debugger my program or run any program anymore
please check and repair this as soon as possible

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.3.1
vscode-markdownlint|Dav|0.20.0
diff-tool|jin|0.0.1
vscode-language-pack-zh-hans|MS-|1.28.2
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.0
vscode-yaml|red|0.0.17
codelf|unb|10.7.0

</details>

**Comment by egamma** [comment] 2018-10-11 14:36
In order to repair, please provide detailed steps so that we can reproduce the problem, e.g., what language are you debugging, when do you get the timout, what is your launch configuration.

**Comment by PCJimmmy** [comment] 2018-10-11 15:04
Piling on - this just happened to me also.  Running a script yesterday that worked perfectly well.  Updated VS code and did a reboot.  Timeout message - timeout waiting for debugger.  Had this happen two days on my second PC - I did foolish thing and submitted a bug report.  It was closed as the closer claimed the issue must be the python extension.  In the middle of a full fresh clean install of windows on that machine.  I had updated VS code on that one also.
Apparently in my case steps to reproduce are to update to latest vs code - than reboot PC.

Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

running Python 3.6.5 64-bit - anaconda distribution

using the base Python extension and the anaconda extension on both machines.

I hit F5 to run the script - no color change to the Python status strip - than after a short time the timeout message.

**Comment by PCJimmmy** [comment] 2018-10-11 15:11
windows 10 pro - version 1809 - fast track have had this build since 9/15/2018.  Assume that was another example of closed issue that came back to bite hard :)

**Comment by wau** [comment] 2018-10-12 00:19
Getting same VSCode timeout message  issue after the October 9, 2018—KB4462919 Windows Update.
![image](https://user-images.githubusercontent.com/22864465/46840613-eb834200-cd91-11e8-85c9-9c0f0b784041.png)

OS          Version	10.0.17134 Build 17134
VS Code Version     1.28.1

Temporary fix is to revert your last Windows Update.

**Comment by PCJimmmy** [comment] 2018-10-12 01:05
KB4462919 - seems an unlikely suspect to me.  I have the issue on a standard Win configuration, likely having this update and on a 2nd PC that's on the fast track, a full generation apart.  This second machine just went bad today after a reboot, but my guess would be that it saw this KB a month or more ago.  

Does the revert get you out of version 1.28.1 of VS?  Also think that my first machine failed with this error before the 10/9 date - but since I am just did a full clean windows installation I can't check that anymore.  Seen a few other issues listed for json errors, but I am such a newbie at this that I could not tell you if my json is pretty or pink.  Will update after the clean install done - its takes a month of sundays to get anaconda python back to running condition for tensorflow/keras.

**Comment by PCJimmmy** [comment] 2018-10-12 01:34
Wau - I was turning chicken as I was installing a fresh version of anaconda and am going with the 1.27.2 VS code install.  KB4469... is now buried in my fresh install of windows and baked in like a burnt cookie.  When I first submitted a bug report the other day on this issue it was quickly closed blaming the extension.  I don't think there was a legit investigation on that closing.  

Will try your suggestion later tonight on the fresh install if 1.27.2 also has the issue.  If present in 1.27.2 than a good chance the extension is the issue.

My second machine running a time critical script on Spyder (I do love the VS look and layout in comparison) so will not get a chance to try your fix on it for a day or two.

**Comment by canvas-J** [comment] 2018-10-12 02:49
Add the following setting:
"python.terminal.activateEnvironment": false
worked for me too，Thank you very much！
VS Code version: Code 1.28.1
OS version: Windows_NT x64 10.0.17134

**Comment by egamma** [comment] 2018-10-12 07:17
This looks like an issue with the Python debugger, please continue the discussion in the repository of this extension.

**Closed by egamma** 2018-10-12 07:17 UTC
Labels: needs more info
