### ISSUE TITLE
Active indent guide disappears when cursor is not visible

### ISSUE THREAD

**Issue by coastermcgee** [Microsoft/vscode#49572] opened 2018-05-09 20:35 UTC
If the cursor is not visible, the newly added (as of version 1.23) highlighted indent guides disappear.  This is especially frustrating when scrolling through lengthy blocks of indented code.

- VSCode Version: 1.23.0
- OS Version: MacOS 10.13.4 

Steps to Reproduce:
1. Place cursor inside a code block and see the highlighted indent guide appear for that block
2. Scroll down so that the cursor is no longer visible.
3. See the highlighted indent guide disappear.

Does this issue occur when all extensions are disabled?: Yes

<img width="323" alt="screen shot 2018-05-09 at 4 26 13 pm" src="https://user-images.githubusercontent.com/24684963/39838233-c8b33d08-53a6-11e8-8933-ece7c31ebca0.png">

<img width="341" alt="screen shot 2018-05-09 at 4 26 43 pm" src="https://user-images.githubusercontent.com/24684963/39838241-d323eda0-53a6-11e8-9022-b1e51e775ab2.png">

**Comment by alexandrudima** [comment] 2018-05-11 07:45
Duplicate of #49173

**Closed by alexandrudima** 2018-05-11 07:45 UTC
