### ISSUE TITLE
Less than operator, <, in for loop breaks some typescript syntax highlighting

### ISSUE THREAD

**Issue by Gregroam** [Microsoft/vscode#2473] opened 2016-01-28 00:08 UTC
When writing a class, method names have their own syntax color, but if I use the less than operator, <, in a for loop in a method, all methods after that have their name appear as white instead of their normal syntax color.

[Image of problem](http://postimg.org/image/c4n3y0r1r/)

Edit: Also causes syntax highlighting in other places to also be buggy. (Eg changing the if highlighting to method highlighting)

**Comment by aeschli** [comment] 2016-01-28 08:44
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-01-28 08:44 UTC
