### ISSUE TITLE
code-icon.svg - net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#97413] opened 2020-05-10 16:37 UTC
Env:
```
Version: 1.45.0 (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Steps to Reproduce:**

1. Open VSCode
2. Run Help -> Release Note

![obraz](https://user-images.githubusercontent.com/30685349/81504981-b41da400-92ec-11ea-8c8f-568cf090c4c9.png)

**Does this issue occur when all extensions are disabled?:** 
To be honest I haven't checked (sorry) but I think it has nothing to do with extensions.

**Comment by uniqeorn** [comment] 2020-05-10 17:53
The first time in the new update I have been trying out my phone

**Comment by Tyriar** [comment] 2020-05-11 21:58
Can repro:

![image](https://user-images.githubusercontent.com/2193314/81616123-c86aab00-9397-11ea-8413-8216000a2a13.png)
![image](https://user-images.githubusercontent.com/2193314/81616152-d7515d80-9397-11ea-8c27-aa4fd9e6800d.png)

**Comment by mjbvz** [comment] 2020-05-11 22:15
Duplicate of https://github.com/microsoft/vscode/issues/97218

**Closed by mjbvz** 2020-05-11 22:15 UTC
