### ISSUE TITLE
希望能有进入文件夹的功能。

### ISSUE THREAD

**Issue by DengMingHao** [Microsoft/vscode#46531] opened 2018-03-26 08:46 UTC
- VSCode Version: 1.21.1
- OS Version: win 7 旗舰版

目前vs code可以设定一个工作专区，一个工作专区下可以有多个项目。这样，带来两个体验问题。

问题：
1、如果，我想用CRTL + P快速打开当前我编辑的项目中的某个文件，其他项目同名的文件也会搜索出来。
2、有时候，一个项目下有很多文件夹。虽然，可以配置将它们隐藏掉。但是，实际项目中比较难以执行。如果，我想专注修改某个文件夹下的多个文件。这样，我会被其他文件干扰到。

期待功能：
可以右击文件夹 --> 进入文件夹。
在这个模式下，搜索文件、查看文件夹列表。将会局限在于这个文件夹中。

参考：
HBuilder 编辑器

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment] 2018-03-26 11:37
@DengMingHao can you please provide the description in English. I don't speak your language.

@octref @rebornix can you help once more.

**Comment by DengMingHao** [comment] 2018-03-27 06:26
title: I hope to have the function of entering the folder.
At present, vs code can set a work area, and there can be multiple projects under a work area.This brings two problems of experience.
  problem:
1. If I want to use CRTL + P to quickly open a file in the project I am currently editing, other files with the same name will also be searched.
2. Sometimes, there are many folders under a project.Although, you can configure them to be hidden.However, it is more difficult to implement in actual projects.If I want to focus on modifying multiple files under a folder.In this way, I will be disturbed by other documents.
Expecting function:
  You can right - click the folder-- > enter the folder.
In this mode, search for files, view the list of folders.It will be limited to this folder.
  reference:
HBuilder Editor

**Comment by bpasero** [comment] 2018-03-27 08:02
I would mark this as duplicate of https://github.com/Microsoft/vscode/issues/41860

**Closed by bpasero** 2018-03-27 08:02 UTC
Labels: needs more info
