### ISSUE TITLE
Hash Sum mismatch (Jan 2019)

### ISSUE THREAD

**Issue by kamleshrao** [Microsoft/vscode#66339] opened 2019-01-10 13:30 UTC
Using VSCode since more than a year.  Suddenly today (10-Jan-2019 18:50 IST) when I run Ubuntu package updates, I am getting **"Hash sum mismatch"** error. 

> Get:20 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [87.2 kB]
Err:20 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages   
  Hash Sum mismatch
Fetched 218 kB in 7s (30.7 kB/s)                                               
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

I have seen the same issue earlier 3-4 times  (reported in 2017 and 2018)in this GitHub issue list, which is closed.  Hope Microsoft Team ensure that once the issue is closed, it does not repeat again.

**Environment Details:** 
Version: 1.30.2
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Ubuntu 16.04 LTS Linux x64 4.15.0-43-generic

Steps to Reproduce:

1. `sudo apt-get update`

**Comment by RMacfarlane** [comment] 2019-01-10 18:11
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/66339, let's track this there

**Closed by RMacfarlane** 2019-01-10 18:11 UTC
Labels: install-update
