### ISSUE TITLE
C/C++ class and macro highlighting

### ISSUE THREAD

**Issue by sillydan1** [Microsoft/vscode#16768] opened 2016-12-06 23:19 UTC
- VSCode Version: 1.7.2
- OS Version: Debian 8.6 Jessie
In C/C++ highlighting assigns classes various different CSS tokens. It would give a much better overview of the code if classes was highlighted correctly.
Example:
````
class MyClass { };

MyClass mc = new MyClass();
```` 
the MyClass words get inconsistently highlighted.
Macros, when used like this, have inconsistent highlighting: 
```
#define DLLEXPORT __attribute__((visibility("default")))
class DLLEXPORT MyClass { };
```
I believe these issues are connected.

**Comment by aeschli** [comment] 2016-12-07 08:23
Please always file separate issue for each problem.

The macro issue is likely a duplicate of https://github.com/atom/language-c/issues/173.

The class issue looks like a bug in the grammar. 'MyClass mc ' is parsed in a single token

**Comment by aeschli** [comment] 2016-12-07 08:24
This issue was moved to atom/language-c#186

**Closed by aeschli** 2016-12-07 08:24 UTC
Labels: languages basic
