### ISSUE TITLE
Error: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by jdhines** [Microsoft/vscode#36843] opened 2017-10-24 18:19 UTC
- VSCode Version: 1.17.2 (normal), Code - Insiders 1.18.0-insider (aaec2980609a4bbe44d0cfe2d3f78c85cba1be83, 2017-10-24T04:19:43.883Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none

## Steps to Reproduce:

1. Updated to version 1.17.2 (also tried installing Insiders just now)
2. Start up VS Code, get the error
![extension_host_error](https://user-images.githubusercontent.com/2855641/31960484-eee7e2b6-b8c5-11e7-830c-b163ee94e40e.jpg)
3. Restart extension host a bunch of times, no change.

Reproduces without extensions: No, because it seems to be some problem with the extension system

**Comment by alexandrudima** [comment] 2017-10-25 10:59
@jdhines Do you have git installed on your machine ?

**Comment by jdhines** [comment] 2017-10-25 13:19
Yes, I do.

**Comment by alexandrudima** [comment] 2017-10-25 14:33
Ok, let's try to see if this is a problem with any of the built-in extensions.

Assuming you have installed VS Code Insiders at `C:\VSCode\`. Could you please rename the folder `C:\VSCode\resources\app\extensions` to `extensions.old` and create a new empty folder called `extensions`.

This will make it so we start an extension host process without any extensions.

**Comment by Dante-101** [comment] 2017-10-31 21:05
Is it possible to print out the name of the extension which crashed? Elimination by trial leads to a lot of wasted time.

**Comment by joaomoreno** [comment] 2017-11-01 08:45
ping @jdhines

**Comment by jdhines** [comment] 2017-11-01 15:03
@alexandrudima @joaomoreno So sorry for the absence, haven't needed to use VS Code on my PC for several days. I renamed the `extensions` folder and created a new one, and then Insiders opened without error. I then installed VSCode Icons and enabled it, which is working fine. 
I _don't_ understand why the new `extensions` folder is completely empty though, but I'm not sure enough about the inner workings to know if I should expect to see anything in there anyway.

**Comment by alexandrudima** [comment] 2017-11-01 15:16
@jdhines This implies that one of the built-in extensions is causing the crash. The following built-in extensions are activated on startup:
* `emmet`
* `git`
* `merge-conflict`

Can you please add these folders back in to the `extensions` folder one-by-one until we establish which one of the built-in extensions causes the crash ?

**Comment by jdhines** [comment] 2017-11-01 15:31
I added each one in turn, restarting VS Code Insiders each time, and the error did not pop up again. But there were a ton more extensions in the `extensions.old` folder, as you can see. Besides the VS Code Icons extension I just mentioned, I didn't install anything else, so this was all from a fresh install of Insiders.
 Given that, I fired up regular VS Code, and again, no error there either! So it doesn't make sense, but it seems like renaming and then switching back the extensions folder in Insiders fixed both versions, at least for the time being.

![vscode_extensions](https://user-images.githubusercontent.com/2855641/32282335-af9976e6-bef7-11e7-8282-579c10b36379.jpg)

**Comment by alexandrudima** [comment] 2017-11-01 15:55
@jdhines Most likely something else changed in the past week on your environment... now that the crash is not reproducible ...

**Comment by jdhines** [comment] 2017-11-01 15:58
I don't think so, because I fired up Insiders today before renaming the extensions folder as you suggested, and was still getting the error. Seems like renaming it "shook" things somehow to get it back in order.

**Comment by alexandrudima** [comment] 2017-11-01 16:03
> I don't think so, because I fired up Insiders today before renaming the extensions folder as you suggested, and was still getting the error. Seems like renaming it "shook" things somehow to get it back in order.

This is super-confusing for me. On each startup we do a `readdir` in the `extensions` folder to discover extensions. There is no state saved in between launches that would get changed, we don't cache anything and always read the extensions from this folder again, on each start-up. 

Also, VS Code and VS Code Insiders have different installation paths and different `extensions` folder, so changing something for the VS Code Insiders (renaming `extensions` to `extensions.old` and back) should have no effect on VS Code.

I am really puzzled as to what causes the crash now...

**Comment by joaomoreno** [comment] 2017-11-01 17:07
Wow. So you can't reproduce the issue in any way any more, @jdhines?

**Comment by jdhines** [comment] 2017-11-01 17:24
I just uninstalled Insiders and reinstalled the same version (since it was still in my Downloads folder): 1.81.0-insider, commit aaec298...

And the error is back. So I guess you could say it's reproducible.

**Comment by jdhines** [comment] 2017-11-01 17:29
Interestingly, even with a fresh install (and having removed the VS Code Insiders folder from `Program Files`), the VS Code Icons extensions is still active and working. According to the message in the dev tools, it's pulling from `C:\users\jdhines\.vscode-insiders\extensions\robertohuertoasm.vscode-icons-7.17.0...`

**Comment by joaomoreno** [comment] 2017-11-01 17:35
@jdhines Can you try something out for me? Edit `app/extensions/git/out/git.js` (within VS Code's installation folder) and comment out the following line. It should be around line 82.

```ts
        .then(void 0, () => findSpecificGit('git'));
```

Does the issue still reproduce with that commented out?

**Comment by jdhines** [comment] 2017-11-01 17:43
Commented out that line then started up Insiders; no error.
Un-commented the line and restarted Insiders; still no error. 

Makes it seem like making any changes to or within `extensions` is analogous to smacking the computer to get it to work, except that in this case it keeps working.

**Comment by joaomoreno** [comment] 2017-11-02 07:16
OK. How about [this build](https://az764295.vo.msecnd.net/insider/14bec536cd355008680893caa2c3f01c8a5c5ebf/VSCode-win32-x64-1.18.0-insider.zip)? Can you reproduce it at all with it? Work for a while, make some changes, wait a few minutes before giving up.

**Comment by joaomoreno** [comment] 2017-11-09 07:56
@jdhines

**Comment by joaomoreno** [comment] 2017-11-10 16:44
Closing as duplicate of #32739

**Closed by joaomoreno** 2017-11-10 16:44 UTC
Labels: extension-host, needs more info

**Comment by jdhines** [comment] 2017-11-17 18:11
Sorry, just been working hard on something else, haven't had time to get back to playing with this on my other computer, but I will update here if I found out anything.
