### ISSUE TITLE
option in task.json to load/reload a file in vscode editor

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#26160] opened 2017-05-07 14:04 UTC
I am looking for some option in task.json which shall load/reload a file in code editor after finishing a task

do we have something for that?

~SwK

**Comment by egamma** [comment] 2017-05-07 21:27
//fyi @dbaeumer

**Comment by dbaeumer** [comment] 2017-05-08 07:22
No, this is currently not available.

**Comment by 123swk123** [comment] 2017-05-08 13:10
would be great if we have some command option like below which shall trigger on success and failure of a task

"OnSuccess":{
"command": "blah blah",
"args":[]
},

"OnFailure":{
"command": "blah blah",
"args":[]
}

in that case I can code.exe as command and file path in args to open it.

also it becomes generic implementation for other use like flashing a software or launching debugger or post task operations.

**Comment by alexr00** [comment] 2018-12-21 10:13
Duplicate of #7090

**Closed** 2018-12-21 10:13 UTC
Labels: *duplicate, feature-request, tasks
