### ISSUE TITLE
Setting uninstalled extension...

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#132657] opened 2021-09-08 15:00 UTC
I noticed that I don't have `vscode-github-issue-notebooks` installed anymore and the log shows me that it got uninstalled this morning by settings sync. I am quite certain that I didn't do that and now it is time understand what happened

<img width="966" alt="Screen Shot 2021-09-08 at 16 59 02" src="https://user-images.githubusercontent.com/1794099/132534026-4886c64b-7393-42dc-b4ce-4d592ec515f7.png">

**Comment by sandy081** [comment] 2021-09-17 07:37
I am sorry that I got to it late because of too many things and did not notice it.

Above logs say that extension is not there in the remote and so it has removed it locally. Reason why it is not there on remote is that another instance would have uninstalled the extension locally and pushed the state to remote. 

You can find which instance has pushed it by checking the activity view:

- F1 > Settings Sync: Show Synced Data
- Focus on Sync Activity (Remote) view
- Type `Extensions` to filter the other resources

![image](https://user-images.githubusercontent.com/10746682/133743074-4633092b-c53c-4aa9-9f4b-9fba19907ea0.png)

- Please check the first entry that does not has your extension to find the instance that removed the extension.

If you think you have not removed the extension manually, please see if we can get the settings sync logs and shared process logs from that machine?

**Comment by jrieken** [comment] 2021-09-17 08:09
You mean something like this? Does that mean the web client uninstalled the extension?

<img width="1247" alt="Screen Shot 2021-09-17 at 10 08 59" src="https://user-images.githubusercontent.com/1794099/133748090-03ea8940-0f11-4161-a82f-708370f00d8e.png">

**Comment by jrieken** [comment] 2021-09-17 08:24
Safari seems to be `#8` and I see the same change but nothing in the log (btw I do see a bunch of other extensions that have been uninstalled without me recalling doing that)

<img width="1380" alt="Screen Shot 2021-09-17 at 10 20 09" src="https://user-images.githubusercontent.com/1794099/133750100-c8c4ba78-b0d3-4422-b47a-05e5ad114c79.png">

**Comment by sandy081** [comment] 2021-09-17 08:42
Yes, it seems one of the web clients has removed the extension from remote. I do not know why - may be extension does not exist and wrong state got pushed - just speculating. 

Since, settings sync runs on every browser tab, it could be one of those tabs. You will find all settings sync logs from all tabs here:

![image](https://user-images.githubusercontent.com/10746682/133751746-d53c4beb-60fc-4eca-9252-fa755919f7db.png)

Is it possible to get the logs from the day when it happened and may be previous ones. It would be helpful to find the log that pushed the state without the extension to remote. You will see in the logs that remote is updated and removed the extension. For eg: `[2021-09-17 10:39:44.666] [settingssync] [info] Extensions: Updated remote extensions. Removed: ["ms-vscode.vscode-github-issue-notebooks"].` Hopefully I can understand what would have happened by seeing that log.

**Comment by jrieken** [comment] 2021-09-17 08:48
this is what I am seeing in the log from the day

```
[2021-09-08 11:13:58.544] [userDataSync.log] [info] Snippets: No changes found during synchronizing snippets.
[2021-09-08 11:13:58.661] [userDataSync.log] [info] GlobalState: No changes found during synchronizing ui state.
[2021-09-08 11:13:59.524] [userDataSync.log] [info] Extensions: Uninstalled local extension. ms-vscode.vscode-github-issue-notebooks
[2021-09-08 11:13:59.556] [userDataSync.log] [info] Extensions: Updated last synchronized extensions. Skipped: ["dbaeumer.vscode-eslint","ms-vscode.vscode-selfhost-test-provider","chrisdias.vscode-opennewinstance","kisstkondoros.vscode-codemetrics","jrieken.references-plusplus","ipatalas.vscode-postfix-ts","jrieken.regex-notebook","jakearl.handydandy-notebook","jrieken.browser-links","eamodio.gitlens","ms-vscode-remote.remote-containers","ms-vscode-remote.remote-ssh-nightly","ms-vscode-remote.remote-ssh-edit-nightly","wayou.vscode-todo-highlight","kisstkondoros.vscode-gutter-preview"].
[2021-09-08 11:13:59.559] [userDataSync.log] [info] Sync done. Took 1034ms
[2021-09-08 11:18:59.561] [userDataSync.log] [info] Auto Sync: Triggered by Interval
```

**Comment by sandy081** [comment] 2021-09-17 09:06
This log also says that the remote does not have this extension. May I know if you have found any log with following entry?

```
[userDataSync.log] [info] Extensions: Updated remote extensions. Removed: ["ms-vscode.vscode-github-issue-notebooks"].
```

**Comment by jrieken** [comment] 2021-09-17 09:59
YEah, also found that in a later log

```
[2021-09-08 11:11:25.146] [userDataSync.log] [info] GlobalState: No changes found during synchronizing ui state.
[2021-09-08 11:11:44.548] [userDataSync.log] [info] Extensions: Updated remote extensions. Removed: ["ms-vscode.vscode-github-issue-notebooks"].
[2021-09-08 11:11:44.573] [userDataSync.log] [info] Extensions: Updated last synchronized extensions. Skipped: ["2gua.rainbow-brackets","jrieken.references-plusplus","jrieken.browser-links","chrisdias.vscode-opennewinstance","dbaeumer.vscode-eslint","eamodio.gitlens","jrieken.regex-notebook","ms-dotnettools.vscode-dotnet-sdk","ms-dotnettools.vscode-dotnet-runtime","wayou.vscode-todo-highlight","ipatalas.vscode-postfix-ts","ms-vscode.vscode-markdown-notebook","ms-vscode.vscode-selfhost-test-provider","kisstkondoros.vscode-codemetrics","kisstkondoros.vscode-gutter-preview","jakearl.handydandy-notebook","ms-vscode-remote.remote-ssh-nightly","ms-vscode-remote.remote-ssh-edit-nightly","ms-vscode-remote.remote-containers"].
[2021-09-08 11:11:44.576] [userDataSync.log] [info] Sync done. Took 19560ms
```

**Comment by sandy081** [comment] 2021-09-17 12:36
Thats it - this is exactly the one and it matches the timing too. Two minutes after this in the another tab, settings sync removed the extension. 

Wondering why this tab has removed the extension. This happens when remote sync state and local last sync state are same and locally extension was removed. I believe that you would not have removed it. So I am wondering why the locally installed extensions do not has this extension. 

In web, settings sync runs on every tab and therefore there can be chance that they run in parallel. So, I am suspicious that there can be a race condition causing this. I have to say I can't prove it though.

**Comment by sandy081** [comment] 2021-09-27 11:10
Moving this to under discussion as it is not clear how this would have happened other than some suspicions.

**Comment by sandy081** [comment] 2021-09-30 14:19
<img width="1004" alt="Screen Shot 2021-09-30 at 15 45 15" src="https://user-images.githubusercontent.com/1794099/135467144-04d9784e-5a99-4e3d-81c7-409b922cb7a6.png">

After investigating together, we found that it is because installed extensions on the web is excluding extensions if they cannot be resolved and Settings Sync thinks that as removal and removing the extension which is confirmed from above logs

**Closed** 2021-09-30 17:23 UTC
Labels: bug, settings-sync

**Comment by sandy081** [comment] 2021-09-30 17:53
Made a tactical fix:

- Settings Sync skips syncing extensions if there are errors while parsing installed extensions. Extensions get synchronized as soon as the errors are resolved.


I will do a better long term fix in next milestone that involves more changes - https://github.com/microsoft/vscode/issues/134224


To verify:

- Set up settings sync between desktop and web 
- In web, open installed extensions resource using command `Developer: Open Installed Web Extensions Resource`
- Change one of the extension's location to point to invalid URL. Eg: Change the `path` property in `location` of extension to a non existing extension 
- Refresh the page and make sure that extension is not removed in desktop. Check settings sync log that an error message is displayed while syncing.
- Fix the extension location and make sure sync works again.

**Comment by rchiodo** [comment] 2021-10-01 18:26
/verified

Invalid paths don't cause a sync.
