### ISSUE TITLE
Don't extend the last tab beyond its required size

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115134] opened 2021-01-26 19:33 UTC
Testing #114827

![image](https://user-images.githubusercontent.com/641685/105895223-3ec14300-5fe3-11eb-8759-5a78697937f2.png)

The close button is WAY too far away, and the huge underlying doesn't look good imo.

**Comment by yume-chan** [comment] 2021-01-27 00:01
Duplicate of #113801

**Closed** 2021-01-27 08:13 UTC
