### ISSUE TITLE
[js] syntax highlighting broken after bracket in the same line as 'if' or 'for'

### ISSUE THREAD

**Issue by EinEnton** [Microsoft/vscode#4245] opened 2016-03-15 11:58 UTC
- VSCode Version: 0.10.11
- OS Version: Win 7

Steps to Reproduce:

1. Write some code with an 'if' statement, and a variable compared with an smaller-as '<' operator (without separating space). 
2. Add a code block bracket on the same line.
3. Write more code in the block

Minimal example:
`var j;`
`if(j<2){`
`    var i=123;`
`}`

Result in the dark+ standard scheme:

![vscodejshighlightingproblem](https://cloud.githubusercontent.com/assets/6265026/13776959/50bb949e-eaad-11e5-8fd8-1530d15e7206.png)

btw. what should the color of the `j`be? It is different in the second example.

**Comment by jpalo** [comment] 2016-03-15 14:59
Also occurs with for loop, e.g.:

![image](https://cloud.githubusercontent.com/assets/6917905/13782309/4567099e-eacf-11e5-95ff-c075fac3786a.png)

**Comment by aeschli** [comment] 2016-03-15 15:06
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-03-15 15:06 UTC
