### ISSUE TITLE
undo(ctrl+z) like webstorm, locate last cursor

### ISSUE THREAD

**Issue by ricebna** [Microsoft/vscode#33843] opened 2017-09-05 13:13 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. webstorm在撤销回退ctrl+z(undo)时, 会先将光标定位在上次编辑的位置, 再次回退时, 才是真正的回退.  希望vs code 也加入这个功能.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment] 2017-09-11 03:18
Duplicate of #34093

**Closed** 2017-10-20 20:13 UTC
Labels: editor, editor-core
