### ISSUE TITLE
Shortcut "Ctrl+[KeyC]" is turned into "Ctrl + PageDown"

### ISSUE THREAD

**Issue by Septias** [microsoft/vscode#173436] opened 2023-02-04 17:02 UTC
Type: <b>Bug</b>

I have a custom keyboard layout installed (Neo 2.0) which uses letter `ä` for `[KeyC]`. Before version 1.75.0, it worked out just fined but after upgrading the combination (Ctrl + `[KeyC]`) doesn't work anylonger and is displayed as `Ctr + PageDown`.
Important to not as well is, that it is still shown as `Ctrl + [KeyC]` in the keys .json file.
Trying to use `Ctrl + ä` fails with something like "Your can't produce this combination on your keyboard" or something

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.19.17-2-MANJARO
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3641)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.34GB (9.48GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2688914e-7d7f-4852-879f-8ce70c8b65c3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982
vscup:30628656

```

</details>

**Comment by ulikunitz** [comment] 2023-02-04 22:15
I have a similar experience. When using the keyboard shortcut editor and trying to update Toggle Terminal and enter `Ctrl+´` it is displayed as `Ctrl+[Equal]` and pressing Enter, it  becomes `Ctrl-V`. So if I press `Ctrl+V` now I toggle the terminal instead of inserting the clipboard. Initially it confused me, because Ctrl+V stated without keyboard shortcut editing to toggle the terminal.

VS Code version: 1.75.0
Ubuntu 22.04.1 LTS
Keyboard: German (no dead keys)

I could use `Ctrl+´` for toggle terminal and it worked as expected.

**Comment by limwa** [comment] 2023-02-05 02:31
Having the same problem using Portuguese (Portugal) layout.
From what I've noticed, `CTRL+[Equal]` turns into `CTRL+V` and `CTRL+[Minus]` turns into `CTRL+U`. Furthermore, `CTRL+ALT+[Equal]` turns into `CTRL+ALT+«` (as expected) and `CTRL+ALT+[Minus]` turns into `CTRL+ALT+'` (as expected).

**Comment by alexdima** [comment] 2023-02-05 19:36
Duplicate of #173325

**Closed by alexdima** 2023-02-05 19:36 UTC
Labels: new release
