### ISSUE TITLE
Type aliases not respected when auto-implementing a TypeScript interface

### ISSUE THREAD

**Issue by robpaveza** [Microsoft/vscode#32791] opened 2017-08-18 16:18 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Create an interface such as:

```export type integer = number;
export interface IFoo {
    bar(baz: integer): Promise<integer>;
}
```

2. Go to a different file and write:

```
    import { integer, IFoo } from './location';
    export class Foo implements IFoo { }
```

3. Position the cursor over the `Foo` identifier to obtain the error and light bulb.  Click the light bulb and click `Implement interface 'IFoo'`.

Observed: The class is populated like so:

    export class Foo implements IFoo {
        bar(baz: number): Promise<number> {
            throw new Error('Not yet implemented');
        }
    }

Expected: Type aliases are honored:

    export class Foo implements IFoo {
        bar(baz: integer): Promise<integer> {
            throw new Error('Not yet implemented');
        }
    }

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-18 18:19
Thanks. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/15562

Closing as upstream

**Closed by mjbvz** 2017-08-18 18:19 UTC
Labels: typescript, upstream
