### ISSUE TITLE
vscode will be crashed when i copy json file(about 4500 lines) from sublime to vscode

### ISSUE THREAD

**Issue by RookieDay** [Microsoft/vscode#15885] opened 2016-11-22 13:50 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-html-css|ecmel|0.0.30|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|

---

Steps to Reproduce:

1.open sublime & vscode 
2.copy json file from sublime to vscode
3. then i can not create file or open another tabs then vscode will be crashed 
4. i can`t attached file here and you can find issue details from https://github.com/RookieDay/TempIssue

**Comment by jrieken** [comment] 2016-11-22 14:32
I cannot repo but it seems like tokenisation doesn't happen in that case

**Comment by RookieDay** [comment] 2016-11-22 15:55
vscode also crashed when i copy json file from a.json to b.json in vscode and then i can`t click any tabs or create files.

reproduce steps:
https://github.com/RookieDay/TempIssue/blob/master/vscode_issue.gif

**Comment by alexandrudima** [comment] 2016-11-30 11:28
@RookieDay Here I am trying the exact steps you have provided and I am unable to reproduce. Can you reproduce when disabling all extensions?

![15885](https://cloud.githubusercontent.com/assets/5047891/20750689/75811dfe-b6f8-11e6-8239-c375d5f6da47.gif)

**Comment by RookieDay** [comment] 2016-11-30 17:27
@alexandrudima 
when you copy json file from a.json to b.json in vscode, please **save** b.json file, and then you can`t click any tabs or create files.
![issue03](https://cloud.githubusercontent.com/assets/19630825/20763453/0c3583ea-b765-11e6-9ba4-1083d5f2caeb.gif)

**Comment by RookieDay** [comment] 2016-12-24 08:55
@alexandrudima 
hi alexandrudima,
I still have this issue now, if you can try to reproduce this issue as above comment i added ?

Thank you.

**Comment by King66** [comment] 2016-12-31 00:24
@RookieDay这个问题我看你提了三遍，这个帖子人家都问你关闭扩展的时候能否重现，你光重现，关扩展了吗？另外一个帖子人家都告诉你是哪个插件的问题了，尼玛到1.8版本又发个帖子。。
你是来练英语的？能不能动点脑子

**Comment by aeschli** [comment] 2016-12-31 01:16
@RookieDay Is this a duplicate of #17859? Does disabling Lonefy/vscode-JS-CSS-HTML-formatter fix the issue?

**Comment by aeschli** [comment] 2017-01-31 09:56
Closing due to lack of information.

**Closed by aeschli** 2017-01-31 09:56 UTC
Labels: needs more info
