### ISSUE TITLE
Match whole word dosn't work in Chinese

### ISSUE THREAD

**Issue by syj2010syj** [Microsoft/vscode#11955] opened 2016-09-13 13:16 UTC
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Ctrl+F
2.Match whole word(Alt+W dosn't work?)
3.Search

![qq 20160913205638](https://cloud.githubusercontent.com/assets/5213431/18475003/5a3fca56-79f7-11e6-9cb6-d41f2f57d9fc.png)

**Comment by ebugusey** [comment] 2016-09-29 11:13
Duplicate of this one #3623

**Closed** 2016-10-06 12:41 UTC
Labels: bug, duplicate
