### ISSUE TITLE
VSCode default language extensions override custom language extensions

### ISSUE THREAD

**Issue by robertohuertasm** [Microsoft/vscode#20074] opened 2017-02-06 19:38 UTC
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install [vscode-icons](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)
2. Install [Vue language extension](https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue)
3. Create a new file with the `.vue` extension.
4. Instead of the `Vue icon` the `html icon` is shown.

`vscode-icons` provides support for `Vue` files by leveraging the language id but it seems that the mechanism that it's used by the icon theme API is giving priority to the default language extensions provided by `VSCode`. 

This has an unexpected behavior as **the users are not able to see the expected icon**. 

In the case of `Vue`, you can see where it is associated to `html` in `VSCode`'s code in the [html extension](https://github.com/Microsoft/vscode/blob/master/extensions/html/package.json#L37) as @JimiC pointed out in  [vscode-icons #725](https://github.com/vscode-icons/vscode-icons/issues/725#issuecomment-277616047).

This is the only case where the file association has to be explicit, meaning that the [user has to explicitly change the file association](https://github.com/vscode-icons/vscode-icons/issues/725#issuecomment-277642688) so she can see the proper icon. That's not the case when the language id is not provided by default by `VSCode`.

This is clearly creating inconsistencies in the user experience thus confusing the users about what they are supposed to do. 

It would be nice if this could somehow be changed to prioritize custom language ids over default ones. This is at least what we were expecting from our side as icon theme builders until we've found out that this is not how it seems to be working.

**Comment by JimiC** [comment] 2017-02-14 21:38
@aeschli 
After a three hours debugging session, I figured out what's going wrong.

There are three factors that are causing this misbehavior.
1. `.vue` is also registered as an extension for the `html` language id in the internal support of `html` [syntax highlighting](https://github.com/Microsoft/vscode/blob/master/extensions/html/package.json#L37) as already mentioned.

2. Although `vscode` issues a [warning](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L59) about the extension getting overwriten, it doesn't get handled, in order for the internal association to get removed from the appropriate list (`nonUserRegisteredAssociations`).

3. While [iterating](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L146) through the association list (in this case the `nonUserRegisteredAssociations`), the [flow logic](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L166) prevents the correct `mime` to be assigned, as it gets assigned to `html` because the iteration finds the `html` first and   then prevents the flow to get through to `vue`.

My proposed solution is to handle the issue in the already coded [check section](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L53).

**Comment by aeschli** [comment] 2017-02-15 10:53
Thanks @JimiC for the investigation and the detailed write-up!

**Comment by JimiC** [comment] 2017-02-27 12:28
@alexandrudima Do we have any news on this? Is it OK if I provide a PR with my proposed solution?

**Comment by alexandrudima** [comment] 2017-03-02 13:51
Appears to be in `mime.ts`

**Comment by JimiC** [comment] 2017-03-02 14:48
Actually the flow starts from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/languagesRegistry.ts#L301 but the main logic is in `mime.ts`.

**Comment by bpasero** [comment] 2017-03-02 16:27
I cannot reproduce:
* installed vscode-icons
* installed vue extension
* opened a foo.vue file

=> icon shows up correctly
=> language in status bar reads Vue.js

![screen shot 2017-03-02 at 17 27 03](https://cloud.githubusercontent.com/assets/900690/23516429/79a1feea-ff6d-11e6-96e6-037f2d590c6c.png)

**Comment by JimiC** [comment] 2017-03-02 17:55
@bpasero I know, this is now invalid as you removed the `vue` filename extension from the `html` extension. But try this with the
[asp](https://marketplace.visualstudio.com/items?itemName=ilich8086.classic-asp) or [volt](https://marketplace.visualstudio.com/items?itemName=hunter-dev.volt) extension.

**Comment by bpasero** [comment] 2017-03-03 05:47
@JimiC it is not clear how to solve that though, there are 2 extensions that provide a language for an extension and the first one wins, but how do you argue that the second one should win? What are the rules?

**Comment by JimiC** [comment] 2017-03-03 09:11
As we have discussed this with @robertohuertasm internally a way to solve this is to introduce an extra level in the determination logic.
Currently, the logic is:
- filename
- filename extension
- language id

We propose it to become:
- filename
- filename extension
- language id (external extension)
- language id (internal extension)

This can be achieved by removing the internal `mime` association from the list if an external extension supports the same filename.

Now, I don't know the implications of this approach as I'm not familiar with the entire code base of `vscode`. I'm sure that there will be cases where the user may have installed more than one extension that support the same mime type. Or even cases where the external extension references the same `language id` as an internal one. Current examples are the [rails](https://github.com/bung87/vscode-rails/blob/master/package.json) and [Flow](https://github.com/flowtype/flow-for-vscode/blob/0.5.0/package.json).

**Comment by bpasero** [comment] 2017-03-03 09:13
@JimiC I am not a big fan of "internal" vs "external" extension, to me they are all the same and the fact that they behave differently is imho debt. And since the issue exists also when installing multiple external extensions, I think the real fix is some way of configuring this per extension.

**Comment by JimiC** [comment] 2017-03-03 09:18
Understandable but the issue here is that the user doesn't have a "clear" way to tell `vscode` to override the "internal" extension. there is a workaround those explained [here](https://github.com/vscode-icons/vscode-icons/issues/725#issuecomment-279845110).

**Comment by bpasero** [comment] 2017-03-03 09:20
This is the problem:
* user installs extension `foo`
* user installs extension `bar`
* foo registers support for `*.foo` and `*.bar`
* bar registers support for `*.bar`

=> as a user I want to control that extension foo only deals with `*.foo` and extension bar deals with `*.bar`

I see no other solution that does not add more confusion or complexity.

@aeschli @alexandrudima let me know what you think

**Comment by JimiC** [comment] 2017-03-03 09:30
Exactly what I'm saying. Currently, the logic determines that `*.bar` is handled by `foo` and stops there returning that `foo` is the `mime` type. What I'm proposing is that the logic keeps iterating and if it finds an extension that solely handles `*.bar` returns that as `mime` type. This also has its own complexity.

What if:
user installs extension `foo`
user installs extension `bar`
foo registers support for `*.foo` and `*.bar`
bar registers support for `*.bar` and `*.alcohol`
?

**Comment by bpasero** [comment] 2017-03-03 09:36
So now you are proposing that an extension that registers only for one extension is more important than one with more extensions? Not sure about that...

**Comment by JimiC** [comment] 2017-03-03 09:43
Just throwing ideas and questions here. I have already mentioned that I'm nor familiar with the entire code base and I don't know the implications my proposals can create.

I have to admit though that this is a "Lerna" and we definitely need a "Hercules" solution.

**Comment by bpasero** [comment] 2017-03-03 10:54
I think this is more of a UX question ("how should it behave") than a question of how it is implemented in the end 👍

**Comment by JimiC** [comment] 2017-03-06 09:17
@bpasero Thinking of it over the weekend I concluded that there are two possible behavior solutions:

1. Give the ability to the user to disable the `built-in` extension.
2. `installed` extension should always be preferred over the `built-in` as the `installed` ones can be disabled by the user.

In case two or more extensions support the same filename extension then it's up to the user to disable the one that creates an issue.

Appendix: 
- `installed` the extension/extensions that the user can install.
 - `built-in` the built-in extension/extensions supported by `vscode`.

**Comment by bpasero** [comment] 2017-03-06 09:20
@JimiC 👎  I would say that this should go on the level of the file extension and not entire extension. If the user is forced to disable an extension, then the user is loosing all functionality of this extension for all file extensions this extension configures. There may still be a very good reason why the extension should not be disabled.

Imagine HTML was an extension in the store: The user is now forced to disable the HTML extension so that the ASP extension works. But that means loosing all the functionality of the HTML extension for all other file types.

**Comment by JimiC** [comment] 2017-03-06 09:24
Then `2.` is the only option.

**Comment by bpasero** [comment] 2017-03-06 12:42
I disagree. Solution 3. imho is: Allow to control for any extension (either built in or installed) if a file association should be made from that extension or not.

**Comment by JimiC** [comment] 2017-03-06 12:47
I think this is already available by setting
```
"files.associations": {
    "*.foo": "foo"
}
```
Correct me if I'm wrong.

**Comment by bpasero** [comment] 2017-03-06 12:49
Yeah. maybe a little less obvious and hard to discover for users.

**Comment by JimiC** [comment] 2017-03-06 12:52
So, is this the officially proposed way to deal with those cases? Issue closed?

**Comment by bpasero** [comment] 2017-03-06 12:56
@JimiC no I think the official way of doing it would be from the extension itself, e.g. here:

![image](https://cloud.githubusercontent.com/assets/900690/23610849/9d81320e-0274-11e7-90b2-3ccba3feef0a.png)

I could maybe have a way to disable a specific association of a language with a file pattern.

**Comment by JimiC** [comment] 2017-03-06 13:07
And what about when it's a filename extension in a `built-in` extension?

**Comment by bpasero** [comment] 2017-03-06 13:11
@JimiC from a user point of view I see no reason why such configuration ability should not apply to any kind of extension (either built in or external). In the end I think all extensions should be treated equally.

**Comment by alexandrudima** [comment] 2017-03-06 14:06
In general extension contribution point collision is handled the following:

* built-in vscode extensions are processed in the `fs.readFile` order (which is AFAIK consistent alphabetical)
* user vscode extensions are processed in the `fs.readFile` order (also alphabetical AFAIK).
* vscode extension(s) under development

So assuming vscode extensions `Y` and `X` are built-in, `C` and `D` are user installed extension and `A` and `B` are extension(s) under development, the processing order of the extensions would be: `X`, `Y`, `C`, `D`, `A`, `B`.

In case of collisions, in extension points I write, I try to implement "overwrite semantics". e.g. if extension `X` contributes a TM grammar for `typescript`, then any of the extensions `Y`, `C`, `D`, `A` or `B` would **win** if they contributed a TM grammar for `typescript`. The same is true I think for most of the extension points. This plays out well as user installed extensions can "overwrite" contribution points of built-in extensions.

The mime detection is quite complicated, as there are so many different ways to associate a file with a language id, but, if possible, I would try to implement the "overwrite semantics": e.g. if a built-in extension associates ".html" => `html` and comes a user installed extension that associates ".html" => `someotherlanguage` I would let the user installed extension "win".

**Comment by bpasero** [comment] 2017-03-06 16:15
@alexandrudima isn't the consequence of this change is that if a user has an extension installed that happens to also register for `*.html`, suddenly all HTML support would change and the only solution is to uninstall the installed extension (that might provide something smart for another language the user is using). 

Are we sure we are willing to potentially break these users (if my assumption is right)?

**Comment by bpasero** [comment] 2017-03-08 16:16
After talking to @alexandrudima we decided to go forward with the model of letting a user installed extension override our built in extensions.

I have added a new property `userInstalled` to `ITextMimeAssociation` for the [`registerTextMime`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L42) method that is being used to register all languages. This property should be set to `true` for extensions that are originating from the extensions folder and not our installation directory. 

I did not find any property on ILanguageExtensionPoint that would tell me if the extension point is contributed from a built in or user installed extension.

@sandy081 is there any chance we could add this info to extension point handler [`here`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/mode/common/workbenchModeService.ts#L33)? I think that is the only piece missing.

**Comment by sandy081** [comment] 2017-03-08 16:34
Yeah that information is already there in extension description. You can get it as follows
```
extensions[i].description.isBuiltin
```

**Comment by bpasero** [comment] 2017-03-08 16:48
@JimiC please verify from tomorrows insider build

**Closed** 2017-03-08 16:48 UTC
Labels: bug, debt

**Comment by JimiC** [comment] 2017-03-09 09:52
@bpasero Confirming that behavior is as excepted in today's `insider` version. 👍

**Comment by bpasero** [comment] 2017-03-09 09:55
@JimiC awesome thanks.

**Comment by JimiC** [comment] 2017-03-14 12:28
@bpasero It has been [reported](https://github.com/vscode-icons/vscode-icons/issues/808) to us that due to this change there is an issue with the `scss` association. Using the [sass-intended](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented) extension the icon association for `scss` gets lost. This [line](https://github.com/Microsoft/vscode/blob/master/extensions/scss/package.json#L12) may cause the issue.

**Comment by bpasero** [comment] 2017-03-14 14:26
@JimiC can we extract this into a new issue?

**Comment by JimiC** [comment] 2017-03-14 14:54
@bpasero Sure.
