### ISSUE TITLE
Memory occupation has been increasing

### ISSUE THREAD

**Issue by onlyShadow** [Microsoft/vscode#40273] opened 2017-12-15 08:25 UTC
# Memory occupation has been increasing, causing my system to crash, my system is deepin Linux, is this my system problem?
![_ _20171215164833](https://user-images.githubusercontent.com/12453379/34034250-a2e3c170-e1b8-11e7-9907-fda6129adc46.png)
![_ _20171215164846](https://user-images.githubusercontent.com/12453379/34034252-a6b8606c-e1b8-11e7-9e66-41168fc6d8d2.png)

**Comment by jrieken** [comment] 2017-12-15 08:41
# Very hard to tell from just a title. How about adding more information by following this guide https://github.com/Microsoft/vscode/wiki/Performance-Issues?

**Comment by onlyShadow** [comment] 2017-12-15 08:52
![_ _20171215164833](https://user-images.githubusercontent.com/12453379/34034167-4a9d4da6-e1b8-11e7-86b4-747560f41cfe.png)
![_ _20171215164846](https://user-images.githubusercontent.com/12453379/34034169-4e7e0d70-e1b8-11e7-96dc-c538f5cd73c2.png)

**Comment by onlyShadow** [comment] 2017-12-15 08:57
# i I modified my problem description. Please take a look.

**Comment by jrieken** [comment] 2017-12-15 09:35
# Thanks 👍

**Comment by jrieken** [comment] 2017-12-15 09:36
@bpasero this seems to be the watcher service consuming crazy amounts of memory. Pretty sure have a dupe for that.

**Comment by bpasero** [comment] 2017-12-16 08:36
@onlyShadow do you see this with any folder you open?

**Comment by onlyShadow** [comment] 2017-12-18 00:59
@bpasero yes，I can see my folders。I suspect this is the problem caused by a plug-in

**Comment by onlyShadow** [comment] 2017-12-18 01:08
@bpasero I unloaded all the plug-ins, but the problem still exists. Is it the problem of the operating system?

**Comment by onlyShadow** [comment] 2017-12-18 01:20
![Uploading 深度录屏_code_20171218091850.gif…]()

**Comment by onlyShadow** [comment] 2017-12-18 01:20
![_code_20171218091850](https://user-images.githubusercontent.com/12453379/34086144-abadee7a-e3d4-11e7-9deb-6b94f68692bb.gif)

**Comment by bpasero** [comment] 2017-12-18 05:38
@onlyShadow does it reproduce when you set `"files.useExperimentalFileWatcher": true` ?

**Comment by onlyShadow** [comment] 2017-12-18 08:29
@bpasero 
![_ _20171218162912](https://user-images.githubusercontent.com/12453379/34096546-ab29c136-e410-11e7-8a22-8da0b3f7f954.png)
![_ _20171218162929](https://user-images.githubusercontent.com/12453379/34096547-ab5b8ff4-e410-11e7-8b71-887d5e8a5fef.png)

**Comment by bpasero** [comment] 2017-12-18 09:33
@onlyShadow what does "code --status" print when you run with that setting? Make sure to restart when changing this setting.

**Comment by onlyShadow** [comment] 2017-12-19 00:41
When I run code -status, the results are shown as shown
![_code_20171219083814](https://user-images.githubusercontent.com/12453379/34134888-5ca6bc70-e498-11e7-946d-e9fc6b8f1e66.png)

**Comment by onlyShadow** [comment] 2017-12-19 01:32
![_code_20171219093129](https://user-images.githubusercontent.com/12453379/34136135-76f17820-e49f-11e7-8c82-ff8b2de5f3b4.png)
I'm sure I've restarted it

**Comment by bpasero** [comment] 2017-12-19 05:37
@onlyShadow would it be possible that this folder contains a circular symlink? A cycle where at one point the file watcher just keeps on going traversing through a cycle of symlinks?

**Comment by onlyShadow** [comment] 2017-12-19 05:52
@bpasero Oh, I see, I deleted my workspace and its configuration file, memory possession is normal. Although the problem has been solved, I still don't understand why. Thanks
![_ _20171219135132](https://user-images.githubusercontent.com/12453379/34142715-bb80f5a0-e4c3-11e7-9fc4-fba855b80598.png)

**Comment by bpasero** [comment] 2017-12-19 06:05
Ok closing until we have more reproducible steps.

**Closed by bpasero** 2017-12-19 06:05 UTC
Labels: needs more info
