### ISSUE TITLE
Reload Required

### ISSUE THREAD

**Issue by jbrabant** [microsoft/vscode#144908] opened 2022-03-11 13:23 UTC
Issue Type: <b>Bug</b>

Reload Required is always shown on almost all extensions, even after reload of VSCode or clicking the button on the extension.

That behavior happened right after I have said yes to upgrade to latest PowerShell and doing so, I was ask to unshallow brew and install an update etc...

Restarted Mac, same issue.

VS Code version: Code - Insiders 1.66.0-insider (6b7453421201c888b81eae5c04ec822a6423608f, 2022-03-11T05:16:52.815Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.4
turbo-console-log|Cha|2.1.7
npm-intellisense|chr|1.4.1
bracket-pair-colorizer-2|Coe|0.2.2
quick-html-previewer|dai|1.0.1
jquerysnippets|don|0.0.1
gitlens|eam|12.0.4
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
vscode-ionic-snippets|fiv|2.2.2
Angular2|joh|13.0.0
vscode-peacock|joh|4.0.0
code-groovy|mar|0.1.2
Angular-BeastCode|Mik|10.0.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-edge-devtools|ms-|1.4.5
powershell|ms-|2021.12.0
vscode-typescript-next|ms-|4.7.20220310
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
angular2-inline|nat|0.0.17
nativescript|Nat|0.12.3
reload|nat|0.0.6
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.14.1
java|red|1.4.0
partial-diff|ryu|1.4.3
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.5.0
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
nativescript-ng2-snippets|www|2.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vscscmwlcmc:30428972
vscgsvid2:30433758
dockersurvey3cf:30438169
pynewfile477:30451556

```

</details>

**Comment by BenGinders** [comment] 2022-03-11 14:06
I am getting the exact same issue along with Jupyter running slow

**Comment by charkour** [comment] 2022-03-11 14:25
For a little more context, I've attached an image of what this looks like. Also, the extensions I have disabled are active despite the UI showing they are disabled.

<details>
<summary>Image of reload required extensions</summary>

![image](https://user-images.githubusercontent.com/33156025/157886133-afbdd2aa-3d7e-49d5-bbd8-565730936b75.png)


</details>

**Comment by charkour** [comment] 2022-03-11 14:27
This is a duplicate of https://github.com/microsoft/vscode/issues/144900

**Comment by misolori** [comment] 2022-03-11 15:46
Yea let's keep the conversation over in https://github.com/microsoft/vscode/issues/144900 and we'll keep you posted

**Closed by misolori** 2022-03-11 15:46 UTC
