### ISSUE TITLE
All Output window logging fails when the user name has non-ASCII characters on Windows

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#55900] opened 2018-08-06 18:58 UTC
- VSCode Version: 1.25.1
- OS Version: Windows.

Steps to Reproduce:

1. Create a user account such as Σπύρος .
2. From cmd, `runas /user:Σπύρος "C:\Program Files\Microsoft VS Code\Code.exe"`.
3. Try to view logs in the Output window.

Bug: All output logging fails and the error below appears. The messages are still being sent by the APIs, but the channel is closed.

Error: Failed opening file C:\Users\Σπύρος\AppData\Roaming\Code\logs\20180806T112412\exthost5.log for writing: No such file or directory
extensionHostProcess.js:408
    at RotatingLogger (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:408:29)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:453:241)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:808:950)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:816:31
    at <anonymous>

Does this issue occur when all extensions are disabled?: Yes

This was originally reported in https://github.com/Microsoft/vscode-cpptools/issues/2351 .

**Comment by sean-mcmanus** [comment] 2018-08-06 19:01
I haven't been able to locate a duplicate issue.

**Comment by sean-mcmanus** [comment] 2018-09-10 19:07
@mjbvz Yes, it still repros with 1.27.1. It should be pretty easy to repro (I've reproed it on 2 different Windows machines).

**Comment by sandy081** [comment] 2018-09-11 13:41
Duplicate of #47883

Please try new insiders where the issue has been fixed.

**Closed** 2018-09-11 13:41 UTC
Labels: *duplicate
