### ISSUE TITLE
Integrated Terminal shortcuts get mixed up with VSCODE shortcuts

### ISSUE THREAD

**Issue by hackerkid** [Microsoft/vscode#7335] opened 2016-06-07 15:53 UTC
- VSCode Version:1.2
- OS Version: Ubunu 14.04

Steps to Reproduce:

1. Open vscode
2. Open ctrl+`
3. Try pasting a copied word to terminal by ctrl+shift+v

I can give more examples in case.

**Comment by Tyriar** [comment] 2016-06-07 18:32
Closing as duplicate of https://github.com/Microsoft/vscode/issues/6451

The only shortcut added in 1.2 was toggling the terminal, more are coming in 1.3.

**Closed by Tyriar** 2016-06-07 18:32 UTC
