### ISSUE TITLE
Go To File very slow on large codebase when typing compared to pasting.

### ISSUE THREAD

**Issue by bpierce1** [microsoft/vscode#196160] opened 2023-10-21 11:00 UTC
Type: <b>Performance Issue</b>

I work on a relatively large code-base  ("rg" command I can see run that lists the files returns 85k results). I've extensively optimized the `files.exclude` and have that about as small as it can be. I use a remote ssh server. I have noticed that "go to file" has become quite slow recently. What is interesting is that for the same search string, it is < 0.5s if I paste in a string "e.g. src/Run.cpp", but if I type the string one letter at a time as fast as I can, the search is > 5s. This is repeatable - as long as I don't open a file, I can rerun the same search and it is continuously slow.

I am hoping to find a way to speed this up, since using "go to file" and typing a result is the main way I navigate my codebase.

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.6.0
Modes:
Connection to 'ssh-remote+cruise' could not be established
Remote OS version: Linux x64 5.15.0-1044-gcp
Connection to 'SSH: cruise' could not be established  Canceled
Connection to 'SSH: cruise' could not be established  Canceled
Connection to 'SSH: cruise' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|32.00GB (1.87GB free)|
|Process Argv|--crash-reporter-id c23c453f-0a6a-447d-ad6e-702bd42fc864|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+cruise' could not be established

|Item|Value|
|---|---|
|Remote|SSH: cruise|
|OS|Linux x64 5.15.0-1044-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.30GHz (32 x 2299)|
|Memory (System)|117.91GB (85.70GB free)|
|VM|0%|

Connection to 'SSH: cruise' could not be established  Canceled

Connection to 'SSH: cruise' could not be established  Canceled

Connection to 'SSH: cruise' could not be established  Canceled
</details><details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: cruise
Connection to 'SSH: cruise' could not be established  Canceled
Connection to 'SSH: cruise' could not be established  Canceled
Connection to 'SSH: cruise' could not be established  Canceled;
```

</details>

**Comment by andreamah** [comment] 2023-10-23 22:42
It looks like you're getting SSH errors in your description. What type of logs do you get from the `Extension Host (Remote)` output channel?

**Comment by bpierce1** [comment] 2023-10-24 01:20
sorry, i should've gotten rid of those errors. they were from long before i ran the search. those errors happen just from initial startup errors when i first log into the machine, but they are gone by the time i perform the search.

I set log level to `Trace`, and went to `Extension Host (Remote)` channel, and here's what it looks like as I perform the search:

```
 - Sibling clauses: {}
2023-10-24 01:19:03.561 [error] HttpError: Bad credentials
	at /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-24 01:19:03.561 [trace] forwarded error to extension? false {"extensionIdentifier":{"value":"StackBuild.bazel-stack-vscode","_lower":"stackbuild.bazel-stack-vscode"},"stack":"HttpError: Bad credentials\n\tat /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2023-10-24 01:19:04.534 [debug] ExtHostSearch /home/brian.pierce/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive --no-require-git -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/*.pyc' -g '!/.cache/**' -g '!/.mypy_cache/**' -g '!/build/**' -g '!/bazel-out/**' -g '!/.venv/**' -g '!/third_party/org_tensorflow/**' -g '!/third_party/boost/**' -g '!**/*.bag' -g '!**/*.bin' -g '!**/*.engine' -g '!**/*.jpg' -g '!**/*.manifest' -g '!**/*.mlir' -g '!**/*.out' -g '!**/*.par' -g '!**/*.parquet' -g '!**/*.pb' -g '!**/*.pkl' -g '!**/*.png' -g '!**/*.pt' -g '!**/*.rst' -g '!**/*.vec' -g '!**/*.whl' -g '!**/.cache/**' -g '!**/.mypy_cache/**' -g '!**/.venv/**' -g '!/cruise/mla/imagination/ncsdk/dependencies/**' -g '!/cruise/silicon/crmla/csim/**' -g '!/ros/src/controls_stack/controls_scenarios/**/*.yaml' -g '!/ros/src/drivers/**' -g '!/ros/src/localizer_scenarios/**/*.yaml' -g '!/ros/src/matrix/sim_driver/scenarios/**' -g '!/ros/src/perception_scenarios/**/*.yaml' -g '!/ros/src/planning_simulator_scenarios/**/*.yaml' -g '!/ros/src/semantic_database_pipeline/src/semantic_database_pipeline/semantic_map_asserts/**' -g '!/ros/src/simulator_scenarios/**/*.yaml' -g '!/third_party/**' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --no-config
 - cwd: /home/brian.pierce/workspaces/work1/src/github.robot.car/cruise/cruise
 - Sibling clauses: {}
2023-10-24 01:19:06.930 [error] HttpError: Bad credentials
	at /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-24 01:19:06.930 [trace] forwarded error to extension? false {"extensionIdentifier":{"value":"StackBuild.bazel-stack-vscode","_lower":"stackbuild.bazel-stack-vscode"},"stack":"HttpError: Bad credentials\n\tat /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2023-10-24 01:19:10.033 [error] HttpError: Bad credentials
	at /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-24 01:19:10.033 [trace] forwarded error to extension? false {"extensionIdentifier":{"value":"StackBuild.bazel-stack-vscode","_lower":"stackbuild.bazel-stack-vscode"},"stack":"HttpError: Bad credentials\n\tat /home/brian.pierce/.vscode-server/extensions/stackbuild.bazel-stack-vscode-1.9.8/node_modules/@octokit/request/dist-node/index.js:66:23\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
```

**Comment by andreamah** [comment] 2023-10-26 18:17
What happens if you try to run the rg executable that comes with vscode? The path should be in your logs as `/home/brian.pierce/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/@vscode/ripgrep/bin/rg`.

**Comment by bpierce1** [comment] 2023-10-30 15:24
I have run exactly the command that I saw above in a terminal. For example, I ran

```sh
$ time /home/brian.pierce/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive --no-require-git -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/*.pyc' -g '!/.cache/**' -g '!/.mypy_cache/**' -g '!/build/**' -g '!/bazel-out/**' -g '!/.venv/**' -g '!/third_party/org_tensorflow/**' -g '!/third_party/boost/**' -g '!**/*.bag' -g '!**/*.bin' -g '!**/*.engine' -g '!**/*.jpg' -g '!**/*.manifest' -g '!**/*.mlir' -g '!**/*.out' -g '!**/*.par' -g '!**/*.parquet' -g '!**/*.pb' -g '!**/*.pkl' -g '!**/*.png' -g '!**/*.pt' -g '!**/*.rst' -g '!**/*.vec' -g '!**/*.whl' -g '!**/.cache/**' -g '!**/.mypy_cache/**' -g '!**/.venv/**'  --no-ignore-parent --no-config > /dev/null
```
I added the `> /dev/null` to avoid the lag due to just printing all the files on my terminal.

I see timings like 
```sh
real    0m0.381s
user    0m2.772s
sys     0m1.814s
```

And it would be faster on subsequent runs.

To me, this shows that the slowdown is happening in vscode's processing of my search query against the file list, not the generation of the file list itself.

Another data point support that claim is the difference in timing between pasting the search string vs typing the search string. If i paste the string, searching is extremely fast. I can then immediately type the same string and the search is slow. Presumably the `rg` command shouldn't need to be run both times, and if it is, it would be faster the second time due to caching of the OS.

**Comment by andreamah** [comment] 2023-10-30 15:40
If you disable all extension except remote-ssh, do you still get slow performance?

**Comment by bpierce1** [comment] 2023-10-30 16:48
I just tried that using the `Disable All Extensions` command.  The performance seems unaffected, it's still very fast if I paste and very slow if I type.

**Comment by bpierce1** [comment] 2023-11-01 15:05
@andreamah please let me know if you need any more information from me to help debugging!

If it helps, I reproduced the problem using an open source repo: https://github.com/tensorflow/tensorflow
I cloned that to my desktop and took this video of the difference between typing vs pasting a search query. On my private repo the search time is even more exaggerated, but hopefully this gives a flavor of the issue.

https://github.com/microsoft/vscode/assets/2482596/8af75153-b48f-4e9e-a971-96b5d2635179

**Comment by bpierce1** [comment] 2023-11-08 15:36
I tried out the latest Insiders build, and it seems like all of the slow-down issues are gone. It's possible the difference is due to some change in my settings I didn't properly copy over, but I'm wondering if the latest insiders has some changes to go-to-file functionality that explains the difference.

**Comment by andreamah** [comment] 2023-11-17 19:01
Hmm, nothing on the performance side of Go To File should have changed. I can close this for now and we can re-open if something comes up again.

**Closed by andreamah** 2023-11-17 19:01 UTC
Labels: info-needed

**Comment by ChansonLeung** [comment] 2023-12-17 15:06
I got the same problem. It seems to be related to "search canceled" logic. It's easy to reproduce if I try to type a long word and I got this log. 
![image](https://github.com/microsoft/vscode/assets/24872993/d7faa255-3a75-4022-95f8-adc5505c6015)
VSCode version: 1.85.1
