### ISSUE TITLE
Give unsaved Markdown files a title, using the first header in the file

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46204] opened 2018-03-20 18:21 UTC
This feature exists in Sublime, and I think it would be useful in VSC as well. 

I'll often open several Markdown files without saving them, just to keep some temporary notes, and if they are all untitled, then it's hard to tell them apart. But this feature has been very useful in Sublime, since it's easy to identify them when they all have titles.

GIF:

![markdown](https://user-images.githubusercontent.com/343940/37674795-01aa49be-2c4a-11e8-8fac-ce3937081c56.gif)

**Comment by mjbvz** [comment] 2018-03-23 02:21
Duplicate of #37414

**Closed by mjbvz** 2018-03-23 02:21 UTC
Labels: markdown
