### ISSUE TITLE
Allow launch.json-less launching to spawn a compound/multiple debug sessions

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#50605] opened 2018-05-29 06:59 UTC
Currently it's possible to launch debug sessions without a `launch.json`, but if the user wants a compound debug session (for example wants to run their app on multiple devices as multiple debug sessions) they need to create a `launch.json` (or we need to create some custom way to start running).

It'd be great if there was some way for the user to hit `F5` and for an extension to start multiple debug sessions (for example returning an array of debug configs `resolveDebugConfiguration`).

**Comment by isidorn** [comment] 2018-05-29 08:36
This sounds like a feature request for the API for the resolveDebugConfiguration to return an array of configurations. Thus first forwarding to @weinand

**Comment by weinand** [comment] 2018-09-11 09:27
duplicate of #37193

**Closed by weinand** 2018-09-11 09:27 UTC
Labels: debug, feature-request
