### ISSUE TITLE
Feature Request: Mercurial Support

### ISSUE THREAD

**Issue by rapito** [Microsoft/vscode#205] opened 2015-11-19 12:38 UTC
# Add VCS Mercurial Support
- Simple file changes tracking as git.

**Comment by nchammas** [comment] 2015-12-19 20:05
+1

A large project that uses Mercurial is [CPython](https://hg.python.org/cpython/). It would be great if we could get VCS support while working on that and other Mercurial projects in VS Code.

**Comment by ounos** [comment] 2016-02-09 12:52
+1

I 'd really like to see that.

**Comment by neal-morgansolar** [comment] 2016-02-11 15:21
+1

**Comment by nsgundy** [comment] 2016-02-12 13:40
Same here, working with Mercurial a lot.

**Comment by micurs** [comment] 2016-02-19 01:14
+1
Same here. Mercurial support in vs code would be great.

**Comment by moigagoo** [comment] 2016-02-26 10:06
I believe there's no necessary API to implement it at the moment.

**Comment by Strate** [comment] 2016-02-26 16:30
+1

**Comment by armanx64** [comment] 2016-03-03 13:48
+OVER9000 
Where's HG support, guys?

**Comment by lilinfr** [comment] 2016-03-29 12:04
+1

**Comment by S8ER01Z** [comment] 2016-04-14 20:16
+1  Is there any chance of this happening?

**Comment by rottingcorpse** [comment] 2016-04-15 11:05
Looks like this feature-request is intentionally ignored.

**Comment by moigagoo** [comment] 2016-04-15 11:10
@rottingcorpse There're 13 hundred other issues in the tracker, and Mercurial support is obviously not the most critical one.

Nobody's ignoring this feature request intentionally, it's just a low-priority one, which is 100% understandable.

**Comment by ivodopiviz** [comment] 2016-05-18 00:29
:+1:

**Comment by phonicmouse** [comment] 2016-08-12 13:15
+1 I really want this...

**Comment by ChiggerChug** [comment] 2016-08-17 11:06
+1

**Comment by prembo** [comment] 2016-08-29 08:43
+1

**Comment by mrmlnc** [comment] 2016-08-29 08:53
@ivodopiviz, @phonicmouse, @ChiggerChug, @prembo, please use GitHub emotions.

![chrome_2016-08-29_11-50-52](https://cloud.githubusercontent.com/assets/7034281/18046101/e81fae10-6dde-11e6-9cde-7d90857865d4.png)

**Comment by LenzGr** [comment] 2016-09-07 20:56
FWIW, I too would like to see Mercurial support in addition to git.

**Comment by whyld4900** [comment] 2016-09-09 03:31
+1

**Comment by ferpaz** [comment] 2016-09-13 15:52
+1

**Comment by rajabiy** [comment] 2016-09-17 17:39
+1

**Comment by mrdixit** [comment] 2016-09-27 07:57
+1

**Comment by Strate** [comment] 2016-09-30 19:06
Maybe you could make extension point in vs code to achieve this?

**Comment by phonicmouse** [comment] 2016-10-03 17:17
@mrmlnc Already done.

**Comment by ChiggerChug** [comment] 2016-10-03 17:43
@phonicmouse isn't the extension for visual studio only, not code? Or am I misunderstanding something?

**Comment by maritzdev** [comment] 2016-10-03 17:45
@phonicmouse ?

**Comment by phonicmouse** [comment] 2016-10-04 12:58
@ChiggerChug we are requesting the vscode support for mercurial, not an extension for vscode or for visual studio.

**Comment by moigagoo** [comment] 2016-10-04 13:08
@phonicmouse Well if it's done with an extension, what's bad about that? The problem is, there's no such extension or a way to develop it since there's no API for custom version controls yet.

However, you claim there is an extension that provides Mercurial support in VSCode. If it's true, this is great news, and the issue should be closed. Could you please point that extension you're talking about?

**Comment by phonicmouse** [comment] 2016-10-05 16:44
@moigagoo I think that there is a misunderstanding...i'm not saying that there is an extension, i only want to find a way to use mercurial with vscode. Can you please tell me when i talked about an existing extension?

**Comment by ChiggerChug** [comment] 2016-10-05 16:54
@phonicmouse whoops thought you were replying to the guy above you. So when you said "Already done" I thought you meant that an extension had already been developed.

**Comment by phonicmouse** [comment] 2016-10-05 17:04
@ChiggerChug Yeah, that is.... 😂

**Comment by pcgeek86** [comment] 2016-10-29 17:21
While I love the Git integration with VSCode, it is a little short-sighted to integrate with only a single revision control system. From a usability standpoint, Mercurial is dramatically simpler to use than Git. It would be interesting if VSCode supported a generic interface for revision control, similar to how it exposes a Debug Adapter interface for external debuggers to implement.

**Comment by borisabramovich86** [comment] 2016-11-06 13:51
+1

**Comment by burnchar** [comment] 2016-11-16 18:29
My team can use VSCode for all multi-platform development once it supports Mercurial integration.
Push/pull/commit isn't terribly hard via CLI, but missing integration integration means switching back and forth between UIs, no at-a-glance visuals showing which files have been modified, etc., thus integration is on our requirements list.
Other than that, VSCode is great.

**Comment by catalinxyz** [comment] 2016-11-22 20:36
+1

Mercurial is my primary VCS it would be awesome to have support for it.

**Comment by qavaxb** [comment] 2017-01-08 11:31
I think this is also connected to #2824 SCM provider API
When API is available, it will be easier to support other SCMs than Git.

**Comment by seanmcbreen** [comment] 2017-03-22 20:15
Hello,

We are listening :) and have now added an API for VSCode to enable pluggable SCM Providers.  This is currently in the 'preview' state and only in the 'insiders' build.  Our plan is to move this into 'stable' in our next release (early April 17).   

This lays the foundation for SCM Extensions to be distributed through the marketplace.  These extensions will have access to all of the features our Git support leverages (this itself is now only using the public API).  

**Our ASK** If you are interested in helping create an SCM provider, we want to help you and have created a new repo with all of the required details including - timelines, instructions, sample implementations, ...   https://github.com/Microsoft/vscode-SCMBuilders

Head on over there if you want to help to get going or to monitor progress - with any luck in the coming months we should have a set of high quality SCM providers for VS Code.

Sean
VS Code Team Member

**Comment by mrcrowl** [comment] 2017-04-21 13:25
An integrated mercurial extension has just been published:
https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg

Or just search for Hg from the extensions tab.

**Comment by seanmcbreen** [comment] 2017-04-21 15:33
Amazing work thank you @mrcrowl .  I'll close this issue and I'm sure some people will jump in and try it out...

Sean
VS Code team member

**Closed by seanmcbreen** 2017-04-21 15:33 UTC
Labels: feature-request

**Comment by burnchar** [comment] 2017-04-21 16:35
Thank you for listening!
This _was_ the one major missing feature preventing my team's widespread use of VSC.
