### ISSUE TITLE
Unable to Install Extensions in Ubuntu

### ISSUE THREAD

**Issue by ooronning** [Microsoft/vscode#9107] opened 2016-07-12 00:37 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.19.0-64-generic (Ubuntu 14.04)

Steps to Reproduce:

1. Enter Ctrl+Shift+P, type `>install extensions`, and press Enter.
2. In the Extensions column, type `ReactSnippets`. Extension `Reactjs code snippets` should populate.
3. Click the green `Install` button, and there is no response. This behavior is the same for every extension attempted at this time. 

Maybe worth noting that this behavior only began after upgrading to 1.3.0. Extensions installed correctly before the upgrade. In addition, can confirm that extensions install properly on OS X after VSCode upgrade.

**Comment by f111fei** [comment] 2016-07-12 02:49
duplicate of #8859

**Comment by bpasero** [comment] 2016-07-12 05:09
Yup.

**Closed by bpasero** 2016-07-12 05:09 UTC
