### ISSUE TITLE
Multicursor with consecutive lines + moving of lines 

### ISSUE THREAD

**Issue by balazsu** [microsoft/vscode#199502] opened 2023-11-29 08:46 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.84.2
- OS Version: Windows 10 22H2

Steps to Reproduce:

1.  Set up multiple cursors that are on consecutive lines (any pair number of cursors will behave similarly)
2.  Move lines up (resp. down) with Alt + UpArrow (resp. DownArrow)

Result: When moving up (resp. down) the pair (resp. odd)  number of consecutive lines behave as expected, but the odd (resp. pair) ones' cursors disappear and stay in place.
It is still possible to select multiple lines and move them with Alt+Up/DownArrow though.

Thanks for the support!

**Comment by alexdima** [comment] 2023-12-08 11:16
Duplicate of https://github.com/microsoft/vscode/issues/11809

**Closed by alexdima** 2023-12-08 11:16 UTC
Labels: editor-multicursor
