### ISSUE TITLE
Update CSharp syntax highlighting

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#121124] opened 2021-04-12 17:19 UTC
This is valid CSharp,

```CSharp
enum Element { /* ... */ }
// ...
(Element?, Element) GetArchitectureElement(Element element) => (null, element);
```

However, this is literally what I see:

![image](https://user-images.githubusercontent.com/1824187/114434804-6d39cd80-9b91-11eb-9e82-43a708930809.png)

It is not important what `Element` fields are, but that it is an `enum`.

Also, the scope of this issue is not exhaustive, but covers one scenario that I happened to observe. Feel free to elaborate, specify the title accordingly, etc.

**Comment by alexr00** [comment] 2021-04-14 13:06
I'm not able to reproduce this behavior. What I see: 

![image](https://user-images.githubusercontent.com/38270282/114715068-fccab200-9d32-11eb-9f57-18950d224c3d.png)

Do you have any extension installed that may be causing this?

**Comment by mwpowellhtx** [comment] 2021-04-14 13:30
Possibly? Who knows... `Code` `1.54.3`:

![image](https://user-images.githubusercontent.com/1824187/114718212-c7f33680-9d03-11eb-9d1c-63f7c3918df7.png)

![image](https://user-images.githubusercontent.com/1824187/114718392-f1ac5d80-9d03-11eb-8c6c-0fe7697ca54a.png)

I ended up going a simpler way after all, but I thought it was interesting.

**Comment by alexr00** [comment] 2021-04-14 13:48
Given that you're not on the latest version and that you may have an extension causing this (there's a command "Extensions: Disable All Installed Extensions for testing things like this), I'm closing as not reproducible.

**Closed** 2021-04-14 13:49 UTC
Labels: *not-reproducible
