### ISSUE TITLE
Resize file explorer window horizontally doesn't work on windows 10 when terminal is visible

### ISSUE THREAD

**Issue by Hamund** [Microsoft/vscode#16985] opened 2016-12-09 14:28 UTC
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3511254/21053198/a6e72adc-be28-11e6-9637-b1a52c50a9cf.gif)
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.3.2|
|vscode-flow|rtorr|276.3.0|

---

Steps to Reproduce:

1.Drag separator between file Explorer and Editor to the right.
2.After a short distance it jumps back to original position and the whole Application redraws

**Comment by bpasero** [comment] 2016-12-09 14:37
@Hamund can you share a video how this behaves?

**Comment by Hamund** [comment] 2016-12-09 15:01
@bpasero Updated issue with animated gif now

**Comment by bpasero** [comment] 2016-12-09 17:21
Wow that looks super weird. I wonder if this is an issue with your mouse or OS version. I have never heard of this before.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-12-16 05:54
@Hamund does it reproduce when NOT having the terminal open?

**Comment by Hamund** [comment] 2016-12-16 08:18
@bpasero Sorry for going silent on this. No, it does not reproduce when terminal is not open. Must have something to do with the terminal.

**Comment by bpasero** [comment] 2016-12-16 08:41
I cannot reproduce on my Windows 10 though.

@Hamund did you configure the terminal in any way?

**Comment by bpasero** [comment] 2016-12-16 08:42
Also your terminal seems to have lots of output invisible, at least your cursor is somewhere in the middle. Does it reproduce with a fresh terminal?

**Comment by Hamund** [comment] 2016-12-16 08:46
No, I didn't configure the terminal and yes it reproduce with a fresh terminal.

**Comment by Tyriar** [comment] 2016-12-16 19:06
I can't repro either, some more questions:

- Are there any errors in the dev tools console (Help > Toggle Developer Tools)?
- Does it happening when you are *not* debugging?
- Does it happen when the output console or problem panels are open instead of the terminal?
- How did you get the terminal in that state (largely blank, cursor in the middle)?

**Comment by Tyriar** [comment] 2017-04-21 04:42
Closing as we don't have enough info and can't repro.

**Closed by Tyriar** 2017-04-21 04:42 UTC
Labels: bug, integrated-terminal, needs more info
