### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

### ISSUE THREAD

**Issue by jhernandez71** [microsoft/vscode#183645] opened 2023-05-27 23:07 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.1-rc

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
    at getDocumentRegistryEntry (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:133137:11)
    at Object.releaseDocumentWithKey (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:133234:19)
    at getOrCreateSourceFileByPath (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141912:30)
    at Object.getOrCreateSourceFile (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141896:14)
    at c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141828:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117906:24)
    at findSourceFileWorker (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120299:23)
    at findSourceFile (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120219:20)
    at c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120168:22
    at getSourceFileFromReferenceWorker (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120152:69)
    at processSourceFile (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120166:5)
    at processRootFile (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119963:5)
    at c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118718:41
    at forEach (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2325:22)
    at createProgram (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118718:5)
    at synchronizeHostData (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141852:15)
    at Object.getProgram (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141924:5)
    at InferredProject2.updateGraphWorker (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174484:41)
    at InferredProject2.updateGraph (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174336:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176726:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178344:12)
    at c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178574:64
    at flatMap (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178574:24)
    at updateOpen (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179754:29)
    at c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182326:69
    at IpcIOSession.executeWithRequestId (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182318:14)
    at IpcIOSession.executeCommand (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182326:29)
    at IpcIOSession.onMessage (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182368:51)
    at process.<anonymous> (c:\Users\Jonathan Hernandez\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183948:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (2dfb838f494f035099e999f0cd0eff5f1f488a30, 2023-05-26T05:22:45.569Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.59GB free)|
|Process Argv|--crash-reporter-id c30c70dd-09f6-4a6c-86bf-8b8dd1cafa76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot-chat|Git|0.1.2023052602
copilot-nightly|Git|1.86.118
remote-wsl|ms-|0.78.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
0bg3d529:30680467
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-30 20:25
Duplicate of https://github.com/microsoft/TypeScript/issues/54381

**Closed by mjbvz** 2023-05-30 20:25 UTC
