### ISSUE TITLE
Emmet 2.0:  auto-completion stops intermittently

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#30188] opened 2017-07-06 13:41 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (767eea03270f924b27d363a97dded3aff9f9e92a, 2017-07-05T18:51:17.228Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.26.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

One of  the most convenient things about Emmet was  the "fuzzy logic" for choosing the most likely abbreviation.  This seems to be not working.

1. In an scss file, inside a rule type `mb0`,  For example:

````
.myrule {
   padding: 0;
    mb10
}
````
2. This should expand to `margin-bottom: 10px`, but it does nothing.

As an aside, if I just type the `mb` part, I get intellisense for many things, apparently by searching for `m` and `b`.  The most common completion, `margin-bottom` is not at the top.

This has slowed down my coding, as I have grown used to the Emmet shortcuts for css like`mb10` or `m0-5-5`.

**Comment by ramya-rao-a** [comment] 2017-07-09 18:00
In the latest we have set the default value for "emmet.useNewEmmet" to false in preparation for the 1.14 release. Can you set it to true and try again?

**Comment by smlombardi** [comment] 2017-07-09 19:09
I have had `  "emmet.useNewEmmet":true,` in my settings json the whole time (including now).

**Comment by ramya-rao-a** [comment] 2017-07-09 20:55
Works for me...

<img width="798" alt="screen shot 2017-07-09 at 1 53 38 pm" src="https://user-images.githubusercontent.com/16890566/27997501-10b03b58-64ae-11e7-8dbe-cf11c7ddfe44.png">

Do none of the css abbreviations work? Eg: `m10`, `dp`, `db` ?

Can you share your settings?

**Comment by smlombardi** [comment] 2017-07-09 21:53
It's working again, in 2017-07-06T20

**Comment by ramya-rao-a** [comment] 2017-07-10 00:17
weird ....

But thanks for keeping an eye out

**Comment by smlombardi** [comment] 2017-07-12 14:22
@ramya-rao-a This has returned today in insiders 1.15  2017-07-12T05:03:23.744Z

![jul-12-2017 10-17-57](https://user-images.githubusercontent.com/835148/28122390-11db59be-66ec-11e7-9138-0433eb174a06.gif)

**Comment by ramya-rao-a** [comment] 2017-07-12 17:41
I am on the Insiders dated 12th July on Mac

<img width="752" alt="screen shot 2017-07-12 at 10 38 36 am" src="https://user-images.githubusercontent.com/16890566/28131294-4ee35a4e-66ee-11e7-9473-f9dad2483537.png">

Can you run code with all extensions disabled and see if you still have issues?

<img width="683" alt="screen shot 2017-07-12 at 10 41 26 am" src="https://user-images.githubusercontent.com/16890566/28131433-b2f173c2-66ee-11e7-83fc-fa2c2c00d603.png">

**Comment by smlombardi** [comment] 2017-07-12 20:24
Ugh.  It's working again.  No idea why it just conks out sometimes.

After posting the bug earlier, I set Emmet usenew to false and used Code for a while like that.

Then after reading your post, I set it back to true and it works.  Not sure if there's something in that process that "kicked it" into working again.

**Comment by ramya-rao-a** [comment] 2017-07-12 20:31
I don't like this ... don't like it at all.

Next time this happens, can you see if there are any errors in your console?

**Comment by smlombardi** [comment] 2017-07-17 14:47
@ramya-rao-a  Happened again.  Console shows this:

![screen shot 2017-07-17 at 10 46 23 am](https://user-images.githubusercontent.com/835148/28273812-470f2df0-6add-11e7-8bb3-119cb835c3e1.png)

**Comment by ramya-rao-a** [comment] 2017-07-17 16:00
Thanks @smlombardi

One more question, when you enter this state, does the `Emmet: Expand Abbreviation` command work as expected?
If yes, then the issue is with the way completions are triggered

**Comment by smlombardi** [comment] 2017-07-17 17:41
No, in this state nothing expands it.

Turning "off" new Emmet and back on, it works again.

**Comment by smlombardi** [comment] 2017-07-17 18:58
@ramya-rao-a Correction, my bad, the menu item DOES expand the abbreviation.

**Comment by ramya-rao-a** [comment] 2017-07-17 19:23
ok, so this narrows down the problem to just the auto-completion issue. 
I'll look into the call stack you provided and see if I can figure something out

**Comment by ramya-rao-a** [comment] 2017-07-17 21:39
@jrieken The error "TextEditor disposed" is coming from https://github.com/Microsoft/vscode/blob/f4ae12b20d7acd048c55262719d3d1c1536ada48/src/vs/workbench/api/electron-browser/mainThreadEditors.ts#L170

Any ideas of how this could happen?
Not sure if this and the auto-completion not working is related

**Comment by jrieken** [comment] 2017-07-18 07:08
re https://github.com/Microsoft/vscode/issues/30188#issuecomment-315893077: that might be the git merge extension (someone tries to set decorations on an disposed/hidden text editor)

**Comment by ramya-rao-a** [comment] 2017-07-18 15:37
@jrieken Any ideas on how to move forward here? Emmet auto-completions stop ever so often for @smlombardi. Since rest of the emmet features continue to work, my bet is on completion not being triggered or maybe the completion provider taking too long?

@smlombardi The next time you see this issue, can you see if other (non emmet) completions work as expected? Eg: if you are in an html file `<div><` should suggest `/div` from the html extension.
Or if you are in a css file `mar` should suggest `margin`

**Comment by jrieken** [comment] 2017-07-18 16:19
> @jrieken Any ideas on how to move forward here? Emmet auto-completions stop ever so often for

Are you saying it stops because of that?

**Comment by ramya-rao-a** [comment] 2017-07-18 16:26
@jrieken I thought so initially, but not anymore. It doesn't make sense that decorators and completions are related.

**Comment by smlombardi** [comment] 2017-07-18 19:06
@ramya-rao-a Regular completions, like the `<div><` one work fine even when Emmet suggestions are broken.

**Comment by ramya-rao-a** [comment] 2017-07-25 03:11
@smlombardi Have you see this lately?

**Comment by smlombardi** [comment] 2017-07-25 18:11
the `mb10` in a scss file still won't suggest/expand to `margin-bottom: 10px`.

this is in 2017-07-25T07:15:46.026Z

![jul-25-2017 14-10-04](https://user-images.githubusercontent.com/835148/28586878-2d836ca4-7143-11e7-9214-3889b2f61f81.gif)

**Comment by ramya-rao-a** [comment] 2017-07-25 20:03
Aha! Found it!

The case I can repro happens
- only in scss files not css or html
- specifically only on the line before a nested rule starts. So in @smlombardi's example the issue will occur in line 7 or 8 but not if you try in between line 5 and 6

Reason is that the [css parser](https://github.com/emmetio/css-parser) we are using treats the text from `mb10` down till the following `div` as the selector for the following nested rule
And I have a logic in place that will skip completions inside the rule selector. Because you know that doesnt make sense. You need css emmet completions for properties and property values and not rules.

Fixed with https://github.com/Microsoft/vscode/commit/4a4226e45385e06386c583c861f316405bbcc20b as it might take a while to fix the upstream issue.

Thanks for your patience @smlombardi !

**Closed by ramya-rao-a** 2017-07-25 20:03 UTC
Labels: emmet, insiders
