### ISSUE TITLE
Notebook opens as text/plain after reload + click

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99369] opened 2020-06-04 13:03 UTC
1. Open notebook
2. Reload
3. While it loads, click the notebook in the file explorer

🐛 Notebook opens as `text/plain`.

![recording (16)](https://user-images.githubusercontent.com/22350/83759780-5fafdf00-a674-11ea-9fb3-6a43badfba09.gif)

**Comment by rebornix** [comment] 2020-06-05 00:19
I can reproduce this issue with Image Editor too. The root cause is when we click the file from file explorer after reloading the workspace, the `editoroverrides` are not registered yet, which will then open the document in text editor.

**Comment by rebornix** [comment] 2020-06-26 00:57
Actually I was wrong, we registered `editoroverrides` very early on. The root cause is group view listeners are registered only when groups are all restored

https://github.com/microsoft/vscode/blob/f17030d3eb8d254be82940260912a5e05ffff1ef/src/vs/workbench/services/editor/browser/editorService.ts#L92

and only when the group view listeners are registered, editor overrides will be called

https://github.com/microsoft/vscode/blob/f17030d3eb8d254be82940260912a5e05ffff1ef/src/vs/workbench/services/editor/browser/editorService.ts#L164-L166

I'm wondering if we can register those event listeners a bit earlier, for example, register after the groups are created from `EditorPart#doCreateGridControl` https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorPart.ts#L929, instead of waiting for the groups fully resolved. @bpasero @isidorn any suggestions?

**Comment by bpasero** [comment] 2020-06-26 05:39
@rebornix yes looks like the overrides need to register early, but the problem is that the groups only restore as part of the startup, so you cannot register listeners without knowing which groups are there. 

I think again, this way of overrides is full of issues and https://github.com/microsoft/vscode/issues/100281 discusses an alternative where you register an override statically that will kick in very early in the `createInput` of things. If you have energy to drive this change and adopt it for notebooks, please go ahead.

**Comment by rebornix** [comment] 2020-06-26 19:59
Moving this out of June and the polish should happen with #100281. Discussions and proposals will continue there.

**Comment by mjbvz** [comment] 2021-05-06 01:27
I believe this has been fixed by @lramos15's recent work. Assigning to May for verification

**Closed by mjbvz** 2021-05-06 01:27 UTC
Labels: bug, custom-editors, notebook
