### ISSUE TITLE
Larger hit area for custom hover

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#224229] opened 2024-07-29 20:03 UTC
https://github.com/user-attachments/assets/f4dde175-0b5d-4f84-af0e-7035cfe9813b

I was trying to move the cursor into the hover so I can click on the buttons in the custom hover. Pressing alt can make the hover sticky but I think in general the hover should not be this easily dismissed.

**Comment by Tyriar** [comment] 2024-07-31 15:08
This is because the little button has a hover as well which immediately closes the hover. The hover is working as designed and this is more of a problem with the positioning of the "button" and the fact that the list item is an ancestor of the "button".

My recommendation would be to combine them into a single hover, including the remote information in the main hover.

**Comment by lszomoru** [comment] 2024-08-02 12:04
Thanks for the feedback! The remote information is already in the hover that is associated with the list item but I do agree that "the branch indicator" is confusing as it looks similar to a button but it not truly a button. I will be talking to @daviddossett this milestone to trying to clean this up which should hopefully address the issue with the hover.

**Comment by Tyriar** [comment] 2024-10-28 20:44
Since the badges don't have their own hovers anymore let's close this in favor of https://github.com/microsoft/vscode/issues/228121

**Closed by Tyriar** 2024-10-28 20:44 UTC
Labels: ux, scm
