### ISSUE TITLE
Extension host does not launch 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#133757] opened 2021-09-24 16:56 UTC
Does this issue occur when all extensions are disabled?: Yes — no issues found

- VS Code Version: 1.61.0-insider
- OS Version: macOS 11.5.2

Steps to Reproduce:

1. Open the [vscode webview sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample) and install deps
2. Hit F5 to launch the extension
3. Build task runs and VS Code enters debug state, but no extension host window appears.

Seems to work fine on stable for me. 

![CleanShot 2021-09-24 at 09 54 15@2x](https://user-images.githubusercontent.com/25163139/134712564-2fe2c1ed-324a-47e1-b080-1623c04c5d13.png)

**Comment by roblourens** [comment] 2021-09-28 02:39
The screenshot shows that the build is still running. Maybe the task isn't set up correctly?

**Comment by daviddossett** [comment] 2021-09-28 03:50
Here's what I have. Unchanged from when I created the extension. Wondering why it would work fine on stable?

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "watch",
      "problemMatcher": "$tsc-watch",
      "isBackground": true,
      "presentation": {
        "reveal": "never"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by roblourens** [comment] 2021-09-28 04:17
What's the output in the terminal?

**Comment by alexr00** [comment] 2021-09-28 08:43
It looks like your terminal width is a bit narrow, and with that I can reproduce the issue on Windows.

@Tyriar the lines I get from `onLineData` are as follows:
```
"[10:38:41 AM] Starting comp"
"ilation in watch mode..."
"[10:38:43 AM] Found 0 error"
"s. Watching for file change"
```

I think the lines used to come in like this:
```
"[10:38:41 AM] Starting comp"
"[10:38:41 AM] Starting compilation in watch mode..."
"[10:38:43 AM] Found 0 error"
"[10:38:43 AM] Found 0 errors. Watching for file change"
```

With the current behavior, tasks has no way to tell where a line actually ends so we can't track problems or task active/inactive at all.

**Comment by meganrogge** [comment] 2021-09-28 15:06
Fixed by reverting the xterm.js update f6da6010333c109a7786cfd0b5564557b707611d

**Comment by alexr00** [comment] 2021-09-29 07:45
I can still repro. I'll start a git bisect.

**Comment by alexr00** [comment] 2021-09-29 12:41
This isn't as urgent as I first thought. The issue started back in 1.57. This is the first bad build:

Version: 1.57.0-insider
Commit: 82767cc1d7bf8cdea0f2897276d5d15aee91f3d9
Date: 2021-05-17T05:15:14.544Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Tyriar** [comment] 2021-11-29 17:19
Think I saw this on Windows 11 using a terminal group with 3 watch tasks and unmaximizing the window.

**Closed** 2022-12-06 18:37 UTC
Labels: bug, terminal
