### ISSUE TITLE
Submenus should not select first item when triggered by mouse

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54733] opened 2018-07-20 15:12 UTC
Open a submenu via mouse, notice the first item is selected. This is not native behavior. It should only be selected if the menu is opened via keyboard

**Comment by isidorn** [comment] 2018-07-20 15:40
Actually this is true for context menus as well. I remember @Tyriar mentioned this in the UX meeting

**Comment by sbatten** [comment] 2018-07-20 17:07
closing this as a dupe of #52913 where you can see reasoning. I would wait for feedback from users. If you feel strongly, please re-open.

**Comment by sbatten** [comment] 2018-07-20 17:09
Just realized the initial issue was just for submenus which is an interesting point. I still think we can wait for feedback, but same deal, if you feel strongly, please re-open.

**Comment by isidorn** [comment] 2018-07-23 07:22
I feel strongly that our menu should look as much as the native one - reopening, adding under-discussion so we can see what other users think.

**Comment by Tyriar** [comment] 2018-07-23 18:12
I agree it should feel native via both mouse and via the menu button, especially since this looks like it will become the default and perhaps the only implementation in the future. @bpasero brought up a great point in https://github.com/Microsoft/vscode/issues/52913#issuecomment-405683555 that if this is not done we will get a continual trickle of issues until the end of time 😱

**Closed** 2018-07-26 00:19 UTC
Labels: bug, under-discussion, workbench-menu
