### ISSUE TITLE
Search working, similar search doesn't

### ISSUE THREAD

**Issue by paamonim** [microsoft/vscode#79499] opened 2019-08-20 10:34 UTC
Issue Type: <b>Bug</b>

I have a file named show.html.erb
The file is located at app/views/budgets

Tried to search for the file with CTRL+p.
When I write "budgets show", I get a list of files, and the first one is the above file.
But when I write "show budgets" I get no results.

It doesn't make sense

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment] 2019-08-20 12:00
@paamonim Quick open uses fuzzy match, that requires letters in query to appear in the same orders as in file path/name, but doesn't require them to be exact substrings.
In your case you can match same files by string `budg sho`, `vi/bu/sho` etc.

It function as expected, so it is not a bug (unless it worked in reverse order earlier) but a feature request.

**Comment by RMacfarlane** [comment] 2019-08-20 22:24
Duplicate of https://github.com/microsoft/vscode/issues/30404, please go thumbs up that issue and add any additional input there, thanks!

**Closed by RMacfarlane** 2019-08-20 22:24 UTC
