### ISSUE TITLE
Auto Attach for node js not working, Breakpoints not hit

### ISSUE THREAD

**Issue by jameswestbv** [microsoft/vscode#146932] opened 2022-04-06 17:29 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:   1.66.0
- OS Version:  Linux x64 5.13.0-37-generic (Ubuntu 20.04.3 LTS)

Steps to Reproduce:

1. Launch any node.js file from the terminal 
Debugger should auto attach (it does on Windows) and hit the break point - but it doesn't on Ubuntu

https://user-images.githubusercontent.com/6533453/162032923-11d42382-ba0c-4cdf-b801-13ea68ae9571.mp4

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-37-generic

------------------------------------------------------------------------------

Expected behaviour on Windows 11 - same version of VS Code

https://user-images.githubusercontent.com/6533453/162033007-b7d6f30b-1500-4693-9248-15d39e87c47a.mp4

Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by connor4312** [comment] 2022-04-06 20:58
Can you please run `echo $NODE_OPTIONS` in your terminal and let me know what/if anything is printed?

**Comment by jameswestbv** [comment] 2022-04-07 07:40
```
james@dev-api-101:~/test$ echo $NODE_OPTIONS
--require /home/james/.config/Code/User/workspaceStorage/83b135b3ec7cd3dbb3f565ff7bcfca1d/ms-vscode.js-debug/bootloader.js
```

**Comment by Platonn** [comment] 2022-10-13 19:05
Same for me. It doesn't attach automatically.
 VS Code 1.72.0. Mac OS Monterey v12.1. Macbook 2020 M1. Node v16.17.0

**Comment by Platonn** [comment] 2022-10-13 20:18
Now I figured out what was wrong. I had **some custom** `NODE_OPTIONS` exported in my `.bashrc`. When I removed it, the Auto Attach feature started to work:
```bash
export NODE_OPTIONS="--max-old-space-size=8192"
```

I discovered that by enabling AutoAttach in VSCode, the VSCode is setting NODE_OPTIONS and VSCODE_INSPECTOR_OPTIONS, e.g.:
```bash
NODE_OPTIONS=--require "/Users/<User>/Library/Application Support/Code/User/globalStorage/ms-vscode.js-debug/bootloader.js" --max-old-space-size=8192 ${env:NODE_OPTIONS}
VSCODE_INSPECTOR_OPTIONS=${env:VSCODE_INSPECTOR_OPTIONS}:::{"inspectorIpc":"/var/folders/8s/2dg05wjn62s42zzbvwm2by2w0000gn/T/node-cdp.10069-11.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"/Users/<User>/.nvm/versions/node/v16.17.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always"
```

So my `NODE_OPTIONS` from my `.bashrc` overwritten the value set by VSCode. And that's why Auto Attach feature didn't work.

--
Finally, instead of removing my custom `NODE_OPTIONS` from `.bashrc` I just concatenated my options with whatever was set before (in this case: by VSCode), by including variable `$NODE_OPTIONS` as part of the string value:
```bash
export NODE_OPTIONS="$NODE_OPTIONS --max-old-space-size=8192"
```

**Comment by WookashWackomy** [comment] 2022-10-18 16:31
@Platonn You've just saved an hour or two for me! I did not think that VSCode might make use of `NODE_OPTIONS` for debugging purposes...

**Comment by connor4312** [comment] 2022-10-18 16:40
@jameswestbv do you have capabilties set on your Node binary? You may be hitting https://github.com/nodejs/node/issues/37588

**Comment by jameswest368** [comment] 2022-10-19 12:11
@connor4312 Yep - that seems to be it.

Doesn't seem like anyone is in a hurry to fix it - probably one of those things that people think that setcap shouldn't really be used and things should run purely unprivileged... 🥱 

So either change your code to not need setcap or, in my case, or give it a bit of this 

`sudo sysctl -w net.ipv4.ip_unprivileged_port_start=0`

🙊

**Comment by connor4312** [comment] 2022-10-19 16:57
Thanks. Apologies for the slow response, I forgot about that issue at the time and this fell off my queue. Closing as a dupe of that one..

**Closed by connor4312** 2022-10-19 16:57 UTC
Labels: debug

**Comment by lifeiscontent** [comment] 2022-10-20 17:08
@connor4312 sorry, what is the fix for this? or is there one?

**Comment by lifeiscontent** [comment] 2022-10-20 17:19
@connor4312 sorry, what is the fix for this? or is there one?
