### ISSUE TITLE
Three column layout

### ISSUE THREAD

**Issue by jd-0001** [microsoft/vscode#136288] opened 2021-11-02 11:20 UTC
I use [bookmarks](https://marketplace.visualstudio.com/items?itemName=ExodiusStudios.comment-anchors) extension a lot to quickly navigate to the desired line/section.

The problem is I have to open that extensions view for navigating between different sections and have to open explorer for navigating between files.

I guess this is simillar to how we move terminal to sidebar (In this case i want to move it outside of sidebar, you can say reverse).

Regards.

**Comment by IllusionMH** [comment] 2021-11-02 11:55
Looks like duplicate of #132893
See comment there about experiments in Insiders builds.

**Closed** 2021-11-03 05:38 UTC
