### ISSUE TITLE
VSCode API: No way to reference open editor if file is image (window.activeTextEditor)

### ISSUE THREAD

**Issue by robole** [microsoft/vscode#122797] opened 2021-05-01 17:38 UTC
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-50-generic snap

Steps to Reproduce:

1. If you write an extension with code as below. 

```javascript
if (window.activeTextEditor !== undefined) {
     // do something with active editor
}
else{
   window.showInformationMessage("No editor is open");
}
```
If a PNG image is opened and that accompanying editor is active when this code is run, the information message is shown.

There does not appear any other way to reference this active editor. If its not considered a `TextEditor`, maybe another `window.activeXxx` property should be available instead?

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2021-05-04 07:05
/duplicate of https://github.com/microsoft/vscode/issues/15178

**Closed** 2021-05-04 07:06 UTC
Labels: *duplicate
