### ISSUE TITLE
When viewing images or pdf in VSC copy-and-paste in filenames is not working anymore

### ISSUE THREAD

**Issue by Pindar777** [microsoft/vscode#129509] opened 2021-07-27 11:38 UTC
Issue Type: <b>Bug</b>

Recently I noticed that after clicking an image or viewing an pdf it is marked as "written protected". Although changing the filename is possible, copy-and-paste inside the filename (in the VSC explorer) is not possible anymore. 
As a consequence I need to switch to Windows 10 explorer to rename if I need info from the clipboard.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.5.1
vscode-markdownlint|Dav|0.42.1
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.28.0
gc-excelviewer|Gra|3.0.42
r|Iku|2.1.0
path-autocomplete|ion|1.17.1
latex-workshop|Jam|8.19.2
svg|joc|1.4.9
language-julia|jul|1.2.8
vscode-language-pack-de|MS-|1.58.8
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
atom-keybindings|ms-|3.0.9
powershell|ms-|2021.6.2
vscode-bookdown|not|0.0.6
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
code-spell-checker-german|str|0.1.9
pdf|tom|1.1.0
vscode-ltex|val|10.5.0
vscodeintellicode|Vis|1.2.14
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2021-07-27 12:26
Duplicate of a known issue that is fixed by @mjbvz

**Closed** 2021-07-27 12:26 UTC
Labels: *duplicate
