### ISSUE TITLE
Sticky scroll - keep containers headers visible when scrolling

### ISSUE THREAD

**Issue by gulshan** [microsoft/vscode#26757] opened 2017-05-16 15:22 UTC
This is a feature request. Starting with an example. Suppose we have following c# file-
```csharp
using System;

namespace ExampleNamespace
{
    class ExampleClass
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        static void ExampleMethod1()
        {
            Console.WriteLine("ExampleMethod1");
        }

        static void ExampleMethod2()
        {
            var methodName = "ExampleMethod2";

            foreach(var c in methodName)
            {
                if(char.IsUpper(c))
                {
                    Console.WriteLine("Upper case");
                }
                else
                {
                    Console.WriteLine("Lower case");
                }
            }
        }
    }
}
```
If we are browsing the file at the end, it looks like this now-
![current](https://cloud.githubusercontent.com/assets/751732/26113648/f35eef8c-3a7c-11e7-8e9e-d52971278bb7.PNG)

And with this feature, I wish it to look something like this-
![requested](https://cloud.githubusercontent.com/assets/751732/26113706/176d1dc2-3a7d-11e7-99eb-2e2ac0176a0b.PNG)

It means the parent syntax nodes of the area being browsed is automatically freezed, so that the user can easily guess the context of the current code, regardless of how far the parent nodes are. Some points being-
- I think this should be a toggle keystroke to on/off feature, may or may not backed by a setting.
- The parent syntax nodes should smoothly stack up or goes out of stack while scrolling.
- This should be tied with the current viewport and not current cursor position in my opinion.
- It would be nice to have previous sibling nodes included in the stack for if-else chains and switch cases.
- By default, this can be solely based on indentation instead of actual syntax tree of the language, just like how folding currently works in vscode.
- There should be a minimum height of the viewport with actual code (without parent nodes). Or maximum height of parent node (header) lines. When that value will be reached (like for heavily nested code), furthest or top most parent nodes can be hidden in that order. The closes parent nodes will remain visible.

**Edit:**
Found a nice illustration for this feature [from this tweet](https://twitter.com/jckarter/status/1140131108564062213)-

![freeze_header](https://user-images.githubusercontent.com/751732/59565046-02d8a480-9070-11e9-9e4c-ad3b97962949.gif)

**Comment by aeschli** [comment] 2017-05-17 07:39
Interesting idea! @egamma @alexandrudima FYI.

**Comment by PEZO19** [comment] 2017-06-02 16:14
I really like the idea, I have something very similar. I believe code folding could be use many ways to make code easier to absorb.
I wonder is there any other editor which has similar code folding strategy?

**Comment by gulshan** [comment] 2017-06-05 06:27
I don't know any other editor with this kind of code folding feature.

**Comment by pr-yemibedu** [comment] 2017-08-01 14:08
Hello,
 This Peeking fold is nice. Some settings could be:
  -  folding.enablePeeking = true
  -  folding.peekingDepth = {0 = unlimited, 1 = one level in, 2 = two levels in, ... , n}
 
So what I would like to see is more (+) in the left border to indicate a way to collapse or expand. Also this can be a lot easier to get in vscode if there are not a lot of limits. The OP made six points ATTOW and so:
1) it could be a keyboard ready toggle, but being backed by a setting gives a user the choice to anchor the toggle direction.
2) ? the code tells the tale told by the programmer, no ?
3) agreed
4) special cases break expectations of ident based folding.
5) agreed
6) sounds like my second setting, but it maybe not poping into a fold based on anymore than matching the current level count

This is one of those so simple looking additions to the editor that it would be a crime to leave out. Thank you. Good day.

**Comment by gulshan** [comment] 2017-11-02 07:18
I thought user may not want to keep this settings on always. It will help more in code exploring situations. But may be someone will want to keep it on permanently. Then I have no objection to a permanent settings.

Regarding branching nodes like if, else-if, else, cases for switch or others, it's true that freezing previous sibling node headers violates indent based folding expectations and the feature will then require language awareness of some sort. So the first or baseline implementation can leave it. But I think it's still a nice to have enhancement and language servers should be able to contribute to this part.

**Comment by gulshan** [comment] 2018-01-10 14:26
One thing! When this feature is turned on, the usual code-folding has to be turned off. So enabling this can be part of `editor.folding` settings.

**Comment by gulshan** [comment] 2018-02-18 07:46
Another thing, the subsequent syntax tree headers can also be present below the focused code, orchestrating a cylindrical lens like effect.

**Comment by gulshan** [comment] 2019-06-16 13:50
This tweet has a nice illustration for this feature-
https://twitter.com/jckarter/status/1140131108564062213

![freeze_header](https://user-images.githubusercontent.com/751732/59565046-02d8a480-9070-11e9-9e4c-ad3b97962949.gif)

**Comment by wayou** [comment] 2019-06-17 17:31
Since the frozen part will take vertical space, it's better to limit the rows and collapse the middle rows with an explicit expand button.

Something like this:

```ts
class Foo{
...Expand 3+ hidden parent nodes...
	constructor(public name:string){
---------------------------------------
	// other codes...
	}
}
```

**Comment by jrieken** [comment] 2019-06-19 14:06
> This should be tied with the current viewport and not current cursor position in my opinion.

We could try that for breadcrumbs. I have created https://github.com/microsoft/vscode/issues/75776 to make breadcrumbs being driven by the viewport, not the selection

**Comment by pr-yemibedu** [comment] 2019-06-19 14:25
Hello,
 So those are two different ways (floating auto collapse and fixed key expandable collapse) for visualizing code information. But there becomes particulars that of the layout left up to opinion. One is whether the immediate and top parent are the most important to show or always the last two?
``` java
class Foo{
  class Bar{
...Expand 3+ hidden parent nodes...
	constructor(public name:string){
---------------------------------------
	// other codes...
	}
  }
}
```

OR

``` java
...Expand 3+ hidden parent nodes...
  class Bar {
	constructor(public name:string){
---------------------------------------
	// other codes...
	}
  }
}
```

Would it seem nice to always keep it all visually stacking? some languages nest better but it would look clumsy with this. Other languages are so thin in that you rarely nest but need to know scope. Thank you. Good day.

**Comment by gulshan** [comment] 2019-06-19 14:42
@jrieken That can be a nice thing. Thanks for consideration.
@pr-yemibedu I think immediate parents are more important for context.

**Comment by jrieken** [comment] 2019-10-04 13:49
Something very, very much like this can be seen here: https://searchfox.org/mozilla-central/source/layout/generic/nsTextFrame.cpp#1229

**Comment by vexx32** [comment] 2019-10-04 13:57
👀  `Semantic Scroll` is a good feature name.

**Comment by phil294** [comment] 2021-03-14 22:15
This is a great suggestion. Arguably the easiest, hackiest way to achieve this (perhaps as an extension?) would be set the `position` of all line divs from `absolute` to `sticky` (they already all have a set `top` property) and give them ascending z-indices. I did something very similar recently [here](https://produpedia.org/static/category-tree.html). But this doesn't seem to be feasible because said divs seem to be reused and only rendered as needed. If it is possible to deactivate the virtual scroller feature somehow (?), we could use some workaround like this in the meantime.

**Comment by gulshan** [comment] 2021-11-01 09:05
@jrieken We almost gathered 50 votes and some other issues have been linked to it. There is no hurry to implement this in the near future (~2 years). Can you please, just keep it open? Once closed, an issue gets lost.

**Comment by TylerEich** [comment] 2022-06-07 04:43
Looks like Xcode is supporting this now! Looks pretty slick. Maybe someday this can be revisited for VS Code. https://twitter.com/NathanBLawrence/status/1533898349761294336?s=20

**Comment by jrieken** [comment] 2022-06-07 14:06
Re-opening because this is cool but I don't have time to work on this right now...

**Comment by waleedrana777** [comment] 2022-06-08 22:46
@jrieken Please do add this amazing feature!

**Comment by tjx666** [comment] 2022-06-09 03:02
xcode 14 had supported it

**Comment by abhijitchikane** [comment] 2022-07-11 05:37
https://twitter.com/NathanBLawrence/status/1544751141363167232?s=20&t=XbLO4-JgAxRiO0VVNzkwSA
“Code structure while scrolling” feature will also bring in context from additional lines of your type or method declarations as you scroll them out of view.
This is soo cool!!!!

**Comment by BenBE** [comment] 2022-07-12 07:56
> One thing! When this feature is turned on, the usual code-folding has to be turned off. So enabling this can be part of `editor.folding` settings.

I don't think so. There's nothing that prevents you from having a collapsed function and when scrolling along just treat it as a single line. When the line is expanded you can see its contents, while when collapsed it's just like any other "single line statement" and you do no longer have to care about any of its child/nested contexts. Preferably you could even explicitly allow for folding the current contexts you are in, to allow for skipping to the next context.

**Comment by cj81499** [comment] 2022-08-04 20:28
For anyone who's watching this issue, sticky-scroll is available as an experimental feature in today's release!

https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll

**Comment by FezVrasta** [comment] 2022-08-07 09:25
Why it only works for TS files? Is that intended?

**Comment by jk** [comment] 2022-08-07 14:43
> Why it only works for TS files? Is that intended?

It doesn’t. I see it in Python files, too. I guess the language needs to expose a certain structure while it is in experimental state. Besides that here isn’t the right place to troubleshoot.

**Comment by gjsjohnmurray** [comment] 2022-08-07 16:16
> Why it only works for TS files?

@FezVrasta what language are you missing it in? Maybe the extension which adds that language to VS Code doesn't implement a DocumentSymbolProvider, or doesn't return the types of symbol that the new feature is driven off.

**Comment by FezVrasta** [comment] 2022-08-07 16:39
Babel

**Comment by BenBE** [comment] 2022-08-07 19:00
I'm properly seeing the semantic scroll work in C (haven't checked C++ yet), but with the headings only generated for the actual function I'm in, but not control structures within the function. Is this intentional? Or could there at least be a setting to enable this? With just the top-level header of the function this doesn't bring any advantages over the existing line above it:

![Image of some code from htop in ScreenManager.c scrolled half-way through the function](https://user-images.githubusercontent.com/111196/183306625-556faad9-3448-4cae-ac49-a2a5982d6b80.png)
I'd prefer if the `while (!quit)` from line 224, the `if (ch == KEY_MOUSE && this->settings->enableMouse) {` from line 239, the `if (ok == OK) {` from line 243 and `if (mevent.bstate & BUTTON1_RELEASED) {` from line 244 were all kept in view.

Also I noticed a minor strangeness in that trying to scroll up, the cursor seems to move into a line hidden by the sticky-scroll display.

Overall I like the feature and am looking forward to see these minor issues resolved in an upcoming version.

NB: Screenshot done against https://github.com/htop-dev/htop/commit/3e1908b80ab214b7b449b49183d1bd5d39c174e3 in case someone needs the exact source to reproduce. Feel free to ask for further details as needed.

**Comment by The-Compiler** [comment] 2022-08-11 13:07
From the blog post and also @BenBE's screenshot above, I can see a small shadow which makes it clear that some part of the source code isn't displayed. Unfortunately, with [Gruvbox Theme - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=jdinhlife.gruvbox), I don't see such a shadow at all:

![image](https://user-images.githubusercontent.com/625793/184139654-c41391bb-3ddd-491e-bc2b-6f024410ee5a.png)

which makes it very hard to notice that some lines aren't being shown. Any idea what's going on there, or what I would need to override in the theme to get those shadows?

I also think I'd prefer to be able to configure a separate color for the sticky lines entirely instead - quick mockup:

![image](https://user-images.githubusercontent.com/625793/184140195-75ba486d-a595-4c68-906b-715991207035.png)

**Comment by gjsjohnmurray** [comment] 2022-08-11 13:14
@The-Compiler please see https://github.com/microsoft/vscode/issues/157185#issuecomment-1207288806

**Comment by The-Compiler** [comment] 2022-08-11 13:17
Whoops, I missed that - thanks for the pointer and sorry for the noise! :+1:

**Comment by aiday-mar** [comment] 2022-08-12 08:05
Thank you for all your comments and interest. If you are interested to see the latest new behavior of sticky scroll you may install the VSCode Insiders release for testing (https://code.visualstudio.com/insiders/). Some of the recurring issues have been solved there. These changes will appear in next month's stable release.

**Comment by aiday-mar** [comment] 2022-08-22 13:13
To verify:

Open a file, scroll in it
Verify that the correct sticky headers are stuck to the top
Use simple click to jump to the line 
Use control click to jump to the definitions of the variable

**Closed** 2022-08-22 13:25 UTC
Labels: feature-request, verification-needed, editor-sticky-scroll
