### ISSUE TITLE
`acceptNextWord` should treat consecutive whitespaces as one part

### ISSUE THREAD

**Issue by bmuskalla** [microsoft/vscode#174329] opened 2023-02-14 10:44 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.76.0-insider (Universal)
Commit: 853b32bad26ed5ffe2d29b95be45adc7f753e35a

Steps to Reproduce:

1. Inline suggestion with multiple whitespaces (leading or in between)
2. Partially accept the whitespaces

Expected:
Suggestion is accepted up to the next non-whitespace character.

Actual:
Each whitespace will be accepted individually.

![Recording 2023-02-14 at 11 39 42](https://user-images.githubusercontent.com/316929/218712859-fbc84d0b-9110-47b2-9e13-76482aea13fa.gif)

cc @hediet

**Comment by piyush09-05** [comment] 2023-02-19 10:40
I would like to work on. Can you please assign this issue to me?

**Comment by MatteoPossamai** [comment] 2023-02-24 19:29
I would like to work on this issue if I can. Can you please describe better the issue because I did not understand what I should do

**Comment by Gardezi1** [comment] 2023-02-28 02:26
@hediet can you share the link to the v1.76.0-insider release version? I think it's specific to that version but I'm unable to find that release version

**Comment by monish-byte** [comment] 2023-03-31 17:32
hey @hediet  I'm a beginner in open source, I want to work on this issue can you please guide me on how I can get started?

**Comment by Brandodan5621** [comment] 2023-04-03 13:52
Can I work on this issue too?

**Comment by balaji-sivasakthi** [comment] 2023-04-04 03:33
Hey @bmuskalla, I've recently checked the issue and that's working fine. I think out that your issue caused by Github Copilot. Please make sure it.

![Screenshot (64)](https://user-images.githubusercontent.com/65065614/229679935-b8ee6113-e2cf-4237-bdad-f5ed7a81bbb7.png)

**Closed** 2023-04-17 10:24 UTC
Labels: help wanted, feature-request, good first issue, inline-completions
