### ISSUE TITLE
Can not read property panel of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37031] opened 2017-10-27 09:13 UTC
To repro, maybe open vscode extension with no panel open. Launch extension, panel gets opened and I see the exception

![screen shot 2017-10-27 at 11 12 10](https://user-images.githubusercontent.com/1926584/32096769-bd4ccc14-bb07-11e7-9b44-0b4bd28e7710.png)

**Comment by maxibanki** [comment] 2017-10-27 10:00
Duplicate of #37026

**Closed** 2017-10-27 11:36 UTC
Labels: bug, workbench
