### ISSUE TITLE
Can no longer press escape in terminal (or ctrl-f)

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#33283] opened 2017-08-28 18:59 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (d30825f323a7f77e17d25b212fef6440e73fdc14, 2017-08-28T05:16:41.243Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11

---

Steps to Reproduce:

1. Open vscode and open the terminal
1. Open file or create new file with `vi`
1. Hit  `i` to enter insert mode, hit `ESC` to attempt to exit insert mode

What happens:
* No effect, cursor stays in insert mode

Reproduces without extensions: Yes

**Comment by julianlam** [comment] 2017-08-28 19:00
Turns out this also happens without using tmux.

**Comment by julianlam** [comment] 2017-08-28 19:18
New regression (possibly related?): I can no longer invoke local file search by pressing `Ctrl-F`

**Comment by cleidigh** [comment] 2017-08-28 19:40
@julianlam 
Yes - I broke this with changes to the terminal simpleFind Widget... The bad merge has been reverted.
You can use the commands from the command pallet until the revert gets picked up by the next insiders build.

**Comment by Tyriar** [comment] 2017-08-28 19:57
Duplicate of https://github.com/Microsoft/vscode/issues/33240

**Closed by Tyriar** 2017-08-28 19:57 UTC
Labels: insiders, integrated-terminal
