### ISSUE TITLE
Git Branches menu should open near the current branch label

### ISSUE THREAD

**Issue by schicks** [Microsoft/vscode#47745] opened 2018-04-12 14:23 UTC
Issue Type: <b>Feature Request</b>

When you click on the branch label in the lower left corner, a menu opens at the middle top of the window. This is disorienting and disjointed. It would be nice if when that menu was opened by clicking on the branch label (rather than by navigating there with ctrl+shift+P) it would appear close to the branch label.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.14393

**Comment by bpasero** [comment] 2018-04-12 17:14
Duplicate of https://github.com/Microsoft/vscode/issues/29193

**Closed by bpasero** 2018-04-12 17:14 UTC
Labels: git
