### ISSUE TITLE
EMMET does not work inside already created tags

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#18473] opened 2017-01-12 21:01 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (ed5a9f269d2d1c9e866bc1f29dbd6a25abc02701, 2017-01-12T07:12:30.743Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-nsp|adambaldwin|1.0.1|
|vscode-color|anseki|0.2.2|
|vscode-node-readme|bengreenier|1.0.7|
|vscode-npm-source|dkundel|1.0.0|
|beautify|HookyQR|0.7.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|node-modules-resolve|naumovs|1.0.2|
|rcgenerator|ngSoftware|0.0.3|
|require-sort|Perkovec|0.0.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

open jsx/javascript react file
write some html in emmet
the first evaluation is done
for ex. div>p
mutates correctly to
`<div>
           <p></p>
       </div>`
also if you now add some more html before or after that div.

but when using emmet already inside a tag, does not work

**Comment by pungggi** [comment] 2017-01-12 21:09
#18445 

Same behaviour even when calling F1

**Comment by ramya-rao-a** [comment] 2017-01-12 23:14
The part about emmet expansions not working inside html in jsx files is duplicate of #18427


@pungggi I don't understand what you mean by the below, can you elaborate?
> Same behaviour even when calling F1

**Comment by pungggi** [comment] 2017-01-13 22:44
with F1 i mean running the command Emmet: Expand Abbreviation

**Comment by ramya-rao-a** [comment] 2017-01-14 20:43
Thanks @pungggi 

Closing this as duplicate of #18427

**Closed by ramya-rao-a** 2017-01-14 20:43 UTC
Labels: emmet
