### ISSUE TITLE
Code folding lost when switching files with back/forward

### ISSUE THREAD

**Issue by mjohnsonengr** [Microsoft/vscode#8202] opened 2016-06-27 15:13 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 10

Perhaps this is a bug or is by design -- please let me know.

I have noticed that I fold several sections of code so I see the two pieces I need most (which for me makes up for the lack of horizontal splitting).  However, if I navigate into another file for any reason, it seems when I come back my code is unfolded.

It would be great if VS Code could remember code folding at least for any of my current "working files"

**Comment by bpasero** [comment] 2016-06-28 05:15
I cannot reproduce, we persist folding information and restore it.

@mjohnsonengr do you have steps?

**Comment by alexandrudima** [comment] 2016-06-28 09:57
@bpasero Maybe this is due to us storing view settings per file and not per tab?

**Comment by bpasero** [comment] 2016-06-28 10:04
@alexandrudima this is in 1.2.1 where we did not have this

**Comment by aeschli** [comment] 2016-06-28 10:20
@mjohnsonengr In what editor do you see this? Is it with left hand side diff editors or with the default-settings editor?

**Comment by mjohnsonengr** [comment] 2016-06-29 18:12
It's in just a default editor I think? No split, and not a diff view.

When I came back to answer questions I realized this wasn't as reproducible as I originally thought and I haven't been able to narrow it down to any specifics.

I have had the most success reproducing this by navigating using Go to Definition (I'm using TypeScript), and then using Go Back to return to the file.  This occurs seemingly regardless to whether or not I've recently modified the file or have current pending changes in it.

If I return to the file using the Ctrl+Tab selector, the editor seems to remember what was folded.

I hope this is clear and concise enough. Let me know if you have more questions or need more info.

**Comment by alexandrudima** [comment] 2016-10-27 20:28
@bpasero Given this works for a single editor instance, I believe it is a problem with how the workbench stores / manages the view state. i.e. the fix (if any) is not in my reach.

**Comment by bpasero** [comment] 2016-10-28 05:20
@mjohnsonengr does it still reproduce with latest?

**Comment by mjohnsonengr** [comment] 2016-10-28 15:19
@bpasero I have 1.6.1 installed right now; it still happens.

**Comment by bpasero** [comment] 2016-10-28 15:28
@mjohnsonengr can you distill some steps to reproduce for us?

**Comment by mjohnsonengr** [comment] 2016-10-28 15:40
I have a folder open in VS Code and two working files open (I keep the tab bar hidden)

1. Press Ctrl + [ to fold some things (same result with Ctrl+k => 1, etc.)
2. Press Ctrl + Tab to switch to the other file
3. Press Alt + LeftArrow to go back to the first file
4. The previously folded code is no longer folded.

**Comment by bpasero** [comment] 2016-10-31 10:02
@alexandrudima fyi I had to tweak a little bit [codeEditorWidget](https://github.com/Microsoft/vscode/commit/7808d00d6ec9e206717ddf6b5661a36ba4e3dfaf#diff-2d7906c426c43683854e85e9c07b9881) so that I am able to restore only the `contributionsState`. Bottom line is that we often have code that opens an editor on a specific line/col and in those cases we never restored the view state of the editor that we stored, so we always lost the folding state actually. Now when you want to open an editor with line/col information, I always first make sure to restore the `contributionsState` view state to restore folding.

**Comment by alexandrudima** [comment] 2016-10-31 10:18
@bpasero Couldn't this be fixed by using `restoreViewState()` + `setSelection()` rather than editing the view state itself (i.e. I'm thinking there must be some other code somewhere that strips `cursorState` and `viewState`?) 

The change in my side is good, but it is unexpected that someone edits the view state object between `saveViewState()` / `restoreViewState()` calls.

**Comment by bpasero** [comment] 2016-10-31 12:05
@alexandrudima I can do that but does it have any bad UI flickering impact to first restore the original view state and then setting selection? will you first jump to the selection from the view state and then to the one from setSelection call?

**Comment by alexandrudima** [comment] 2016-10-31 13:34
@bpasero There should be no jumping if the calls are in the same execution stack (same how `setModel()` and `restoreViewState()` are in the same execution stack).

**Closed** 2016-10-31 14:01 UTC
Labels: bug, needs more info

**Comment by bpasero** [comment] 2016-10-31 14:02
@alexandrudima ok this makes for a much simpler fix. I have reverted my changes to editor and the only thing I am doing now is to first call restoreViewState (if I have any) and then do things like `setSelection` and `revealPositionInCenter`. This all happens from one callstack without timeout so I assume we do not end up in flicker as you say.

**Comment by alexandrudima** [comment] 2016-10-31 14:04
👍
