### ISSUE TITLE
User keyboard shortcut on different operational System should Sync

### ISSUE THREAD

**Issue by gaoljhy** [microsoft/vscode#83200] opened 2019-10-24 02:58 UTC
1. on different System ,user self shortcut need to Sync 
2. if not ,user need change many keybind .

that's terrible. 

> I know different system has many self OS key short cut ,but we need user high priority

1. maybe can export user setting to a file and then user can  import it on a different System

2. Or need a account like onedriver?

**Comment by alexr00** [comment] 2019-10-24 08:03
duplicate of https://github.com/microsoft/vscode/issues/78966

**Closed** 2019-10-24 08:03 UTC
Labels: *duplicate

**Comment by gaoljhy** [comment] 2019-10-25 10:20
oh my god , i just need a user key shortcut to share my different system computer.

you maybe don't understand my suggest
