### ISSUE TITLE
support show the outline when focus on md preview

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#136138] opened 2021-10-29 23:15 UTC
it is better to show the outline of md even in preview
![mdol](https://user-images.githubusercontent.com/1876302/139510576-31f232e2-9422-4491-89dc-c0ecc2648e3f.gif)

**Comment by mjbvz** [comment] 2021-11-01 15:41
Duplicate of #97095

**Closed by mjbvz** 2021-11-01 15:41 UTC
