### ISSUE TITLE
renderWhitespace: all rendering broken for words "all logs"

### ISSUE THREAD

**Issue by raggi** [microsoft/vscode#106793] opened 2020-09-15 18:49 UTC
Issue Type: <b>Bug</b>

Set `renderWhitespace: all` in settings.

Make a new file containing the words "all logs": observe bad rendering.

Set configuration of renderWhitespace to any other value: observe normal rendering.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (8.18GB free)|
|Process Argv|--crash-reporter-id 6d13fc8b-beaa-4250-a508-21863208c7fd|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by raggi** [comment] 2020-09-15 18:52
Bad:
![Screen Shot 2020-09-15 at 11 51 15 AM](https://user-images.githubusercontent.com/348/93251995-c8b1f300-f749-11ea-8c05-e5129dcba7ee.png)
Good:
![Screen Shot 2020-09-15 at 11 51 49 AM](https://user-images.githubusercontent.com/348/93252071-dcf5f000-f749-11ea-88b6-0e77af3c4b9f.png)

**Comment by raggi** [comment] 2020-09-15 18:55
Fonts being used:
```
'Source Code Pro', 'Inconsolata'
```

Setting to the default font partially resolves the issue, but potentially focuses the problem, see the spilling character:

![Screen Shot 2020-09-15 at 11 55 28 AM](https://user-images.githubusercontent.com/348/93252461-65749080-f74a-11ea-8d02-6a186c9b0eaf.png)

**Comment by alexdima** [comment] 2020-09-16 15:17
Duplicate of #106583

**Closed by alexdima** 2020-09-16 15:17 UTC
