### ISSUE TITLE
html loses auto-indent when using custom grammars

### ISSUE THREAD

**Issue by joshpeng** [Microsoft/vscode#28145] opened 2017-06-06 19:09 UTC
- VSCode Version: 1.12.2
- OS Version: Win 10

Steps to Reproduce:

1. Install any custom JavaScript grammar (e.g. Microsoft's own [Latest TypeScript and JavaScript](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar), Microsoft's [JavaScript Atom Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar), or any of the Babel grammars. [Babel ES6/ES7](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring), [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode))
2. Open a JavaScript file
3. Type ```div```
4. Press Tab for Emmet to auto convert that to ```<div></div>```
5. Press Enter --> it doesn't auto-indent the new line
![image](https://user-images.githubusercontent.com/22549127/26846989-52303ff0-4ab0-11e7-85fa-07af171051c1.png)

6. Uninstall any custom JavaScript grammar, restart VS Code
7. Repeat steps 3-5 --> the desired auto-indentation occurs
![image](https://user-images.githubusercontent.com/22549127/26847044-7fdeb274-4ab0-11e7-85e1-893733eadd94.png)

**Comment by akofke** [comment] 2017-06-20 03:32
I'd be very interested in a fix for this as well. It also happens for third-party HTML template languages such as Liquid or ERB. The built-in Handlebars plugin has the correct behavior however.

**Comment by joshpeng** [comment] 2017-06-20 06:33
@ramya-rao-a is there any other information I can provide to help out with this issue? Thanks.

**Comment by ramya-rao-a** [comment] 2017-06-20 18:23
@joshpeng I dont believe this is emmet related.

Type just `<div></div>`, keep cursor in between the 2 tags, press Enter
You will see the same issue.

**Comment by rebornix** [comment] 2017-06-20 18:52
Some thoughts

1. The indentation adjustment is onEnter rule defined by HTML
2. Writing HTML in JavaScript is likely JSX @mjbvz 
3. It's likely a common issue with embedded language. If you create an empty workspace, then create a javascript file, type HTML inside it will not load HTML language service. In this case the editor doesn't know about the indentation rules of HTML.

**Comment by joshpeng** [comment] 2017-06-20 19:01
@rebornix On your second and third points, somehow the built-in JavaScript grammar (JS and JSX) knows how to auto-indent it correctly though in that exact scenario. It is just whenever a custom grammar (including the MSFT latest JavaScript grammar) gets installed does it fail to work. It feels like something is probably not being wired up on the custom grammars?

**Comment by ramya-rao-a** [comment] 2017-06-20 19:26
@rebornix Note that the issue does not exists if there are no custom grammar. Like @joshpeng says, custom grammar might be interfering with the onEnter rule?

**Comment by aeschli** [comment] 2017-06-21 07:31
This has to do with the embedded languages definitions for Javascript:
![image](https://user-images.githubusercontent.com/6461412/27372080-9cc2227c-5663-11e7-962b-3107dfd42e45.png)

Extensions that replace the Javascript grammar also have to specify the embeddedLanguage section. When inside the scope, the auto-indent rules of the specified language are applied.
In the case of the built-in JavaScript we defined an artificial language 'jsx-tags' along with its own [language configuration rules](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/tags-language-configuration.json#L27).

**Comment by aeschli** [comment] 2017-06-21 07:32
So @joshpeng, the bug needs to be filed against the grammar extension that you installed.

**Comment by joshpeng** [comment] 2017-06-21 15:56
Hi @aeschli, at least for my grammar, I've already added those from a prior suggestion you made in another issue. The indentation issue still exists though even with the embedding of ```jsx-tags```.

**Comment by joshpeng** [comment] 2017-06-28 17:11
@aeschli just wanted to check-in again on this. If there is anything else I can provide, please feel free to let me know. Thanks.

**Comment by aeschli** [comment] 2017-06-29 01:28
@joshpeng https://github.com/joshpeng/Sublime-Babel-VSCode/blob/master/syntaxes/sublime-babel.json is your grammar, right? I think it would be `meta.tag.jsx` then
```
"embeddedLanguages": {
     "meta.tag.jsx": ...
```

**Comment by aeschli** [comment] 2017-08-15 07:49
Clsoing. The issue is in https://github.com/joshpeng/Sublime-Babel-VSCode.

**Closed by aeschli** 2017-08-15 07:49 UTC
Labels: editor-indentation, html
