### ISSUE TITLE
Unexpected graphical behavior of the window under small size

### ISSUE THREAD

**Issue by Northurland** [microsoft/vscode#73999] opened 2019-05-20 14:36 UTC
- VSCode Version:1.34.0
- OS Version: Windows 10, 17763.503

Steps to Reproduce:

1. Open VSCode
2. Resize the window to as small as possible
3. Click on maximize on the window's titlebar
4. 
![image](https://user-images.githubusercontent.com/40388212/58028345-1f56ef00-7b4d-11e9-8883-3a781b87006c.png) 
This happens instead of the expected maximize.

P.S.:
 - This doesn't happen every time and is less likely to happen when there is no file opened in the editor. Maybe you should repeat several times to see it.
 - This happens at different small sizes (for me it's 300 * 180 ~ about 320 * 210),  but not a certain size. Additional information: I use a 1920*1080 screen.
 - You can still interact with the window after it becomes something just like the picture in step 4. Another click on maximize will maximize, and another click on close will close. A manual resize will also restore the normal display.  However, you cannot move the window as long as it is in such abnormal state.
- The window becomes something like this when problem's reproduced without files opened but with a folder opened:
![image](https://user-images.githubusercontent.com/40388212/58029105-7c9f7000-7b4e-11e9-8aba-24535621b35d.png)
 - For me, there isn't yet any successful reproduction of the problem using a VSCode window with only file editor opened but no folder opened.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Northurland** [comment] 2019-05-21 13:56
Test update:
 - A reproduction of the problem with split editor opened
![image](https://user-images.githubusercontent.com/40388212/58101370-11b76d00-7c12-11e9-9aea-55c483f4eaf2.png)


In this time I did it with a slightly larger window.
<img width="161" alt="example" src="https://user-images.githubusercontent.com/40388212/58101745-bc2f9000-7c12-11e9-943d-584dc0663863.png">
(I blurred the editor content so you don't see what's in it)

**Comment by isidorn** [comment] 2019-05-23 11:58
I can not reproduce this but it sounds like an electron issue
Can you give more precise steps please? Also a video showing this might help?
Can you reproduce using just electron - checkout electron fiddle here https://github.com/electron/fiddle

fyi @bpasero

**Comment by Northurland** [comment] 2019-05-24 00:32
@isidorn 
I am not able to reproduce it with Fiddle but sure I get the (compressed) video here. 
[bug-reproduction-#73999.zip](https://github.com/microsoft/vscode/files/3214580/bug-reproduction-.73999.zip)
Don't mind the frame rate and the video quality. Those are only about capturing software setting.

**Comment by bpasero** [comment] 2019-05-24 04:40
@Northurland do you also see this when you configure `window.titleBarStyle: native` in settings?

**Comment by Northurland** [comment] 2019-05-24 04:46
> 
> 
> @Northurland do you also see this when you configure `window.titleBarStyle: native` in settings?

@bpasero Reproduction of the problem failed when I switched the setting to `native`. I think this might be an important point.

**Comment by sbatten** [comment] 2019-05-24 18:35
duplicate of https://github.com/microsoft/vscode/issues/73407

**Closed by sbatten** 2019-05-24 18:35 UTC
Labels: bug, workbench-title
