### ISSUE TITLE
Suggest is still slow (saw in selfhost)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2602] opened 2016-02-01 09:03 UTC
Created a new file rulers.ts:

If you add it, be sure to refresh given new files are not picked up properly by TS....
[CPU-20160201T100230.cpuprofile.txt](https://github.com/Microsoft/vscode/files/111910/CPU-20160201T100230.cpuprofile.txt)

See `// >>>>>>>>> TYPED BELOW LINE`

```typescript

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';

import 'vs/css!./rulers';

import {ViewPart} from 'vs/editor/browser/view/viewPart';
import EditorBrowser = require('vs/editor/browser/editorBrowser');
import EditorCommon = require('vs/editor/common/editorCommon');

export class Rulers extends ViewPart {

	public domNode: HTMLElement;
	private _rulers: number[];

	constructor(context:EditorBrowser.IViewContext) {
		super(context);
		this.domNode = document.createElement('div');
		this.domNode.className = 'view-rulers';
		this._rulers = [];
	}

	public dispose(): void {
		super.dispose();
	}

	// --- begin event handlers
	public onConfigurationChanged(e: EditorCommon.IConfigurationChangedEvent): boolean {
		if (e.rulers) {
			this._rulers = this._context.configuration.editor.rulers;
			return true;
		}
		return false;
	}
	public onLayoutChanged(layoutInfo: EditorCommon.IEditorLayoutInfo): boolean {
		return true;
		// if (this._width !== layoutInfo.width) {
		// 	this._width = layoutInfo.width;
		// 	return true;
		// }
		// return false;
	}
	// --- end event handlers

	// public onBeforeForcedLayout(): void {
	// }

	// public onReadAfterForcedLayout(ctx:EditorBrowser.IRenderingContext): void {
	// }

	_render(ctx: EditorBrowser.IRenderingContext): void {
		// console.log('rendering rulers');
		this._requestModificationFrame(() => {

			let existingRulers = this.domNode.children;
			let existingRulersLength = existingRulers.length;
			let max = Math.max(existingRulersLength, this._rulers.length);

			for (let i = 0; i < max; i++) {
// >>>>>>>>> TYPED BELOW LINE
				// if (i < existingRulersLength)
				// if (i < existingRulersLength)
			}

			// Update existing rulers
			let renderedRulers = this.domNode.children;
			for (let i = 0; i < renderedRulers.length && i < this._rulers.length; i++) {
				console.log('update @ ' + i);
			}

			// Insert new rulers

			// remove extra rulers


			// ruler
			console.log('rendering rulers');
			// DomUtils.StyleMutator.setWidth(this._domNode, this._width);
			// DomUtils.toggleClass(this._domNode, EditorBrowser.ClassNames.SCROLL_DECORATION, this._shouldShow);
		});
	}

}

```

**Comment by alexandrudima** [comment] 2016-02-01 09:04
![image](https://cloud.githubusercontent.com/assets/5047891/12712770/22321976-c8cb-11e5-92b4-8ee9eae85d1d.png)

**Comment by alexandrudima** [comment] 2016-02-01 09:05
Maybe its a problem only on Windows since I'm the only one seeing this?

**Comment by alexandrudima** [comment] 2016-02-01 09:13
![image](https://cloud.githubusercontent.com/assets/5047891/12712991/6dd57b60-c8cc-11e5-89c2-2d181dc33290.png)

**Comment by joaomoreno** [comment] 2016-02-01 09:17
Duplicate of #2490

**Comment by bpasero** [comment] 2016-03-01 19:46
Close = Done?

**Closed** 2016-03-02 11:07 UTC
Labels: freeze-slow-crash, important
