### ISSUE TITLE
Don't show "restart to update" on BigSur

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111803] opened 2020-12-03 10:31 UTC
There is a well-known issue that restart to update doesn't work on BigSur. While it's well-known to us, it likely won't be so popular for our users so I suggest to tweak the wording on BigSur or show an explicit dialog before shutting down. What do you think?

**Comment by joaomoreno** [comment] 2020-12-04 09:01
What does actually happen? What should we show on that dialog?

**Comment by joaomoreno** [comment] 2020-12-04 09:08
Related to https://github.com/microsoft/vscode/issues/109728

**Comment by deepak1556** [comment] 2020-12-04 18:45
Just to expand a bit, this is just an issue with squirrel version in Electron 9 and Big Sur. The issue is fixed in our exploration builds based on Electron 11 and will be fixed in our insiders next week. So its just about one more iteration until stable gets a fix too. So we should think if we need this change for the iterim.

**Comment by joaomoreno** [comment] 2020-12-07 09:22
https://github.com/microsoft/vscode/issues/109728

**Closed by joaomoreno** 2020-12-07 09:22 UTC
Labels: under-discussion
