### ISSUE TITLE
Broken markdown highlighting after 1.92.0 upgrade 

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#224627] opened 2024-08-02 19:03 UTC
Does this issue occur when all extensions are disabled?: I'm reporting a conflict with an extension, so I left that one enabled.

- VS Code Version: 1.92.0
- OS Version: macOS Sonoma 14.4.1

After upgrading to 1.92.0 syntax highlighting for qmd files (Quarto extension) started showing the same issues that were described some days ago wrt the builtin markdown support. That issue was marked as duplicate (it's not clear to me that it's a duplicate) and then closed by a bot as not planned. I don't know if this is a regression in VSCode or an issue that should be addressed by the extension, but it's clearly something going on that's related to a change in latest release.

---

- https://github.com/quarto-dev/quarto/issues/501
- https://github.com/microsoft/vscode/issues/220026

**Comment by mjbvz** [comment] 2024-08-02 20:16
Please Marking as caused by extension. Sounds like they may need to update their grammar based on changes to our markdown grammar

They can follow up here if there really a problem on the VS Code side

**Closed by mjbvz** 2024-08-02 20:16 UTC
Labels: new release

**Comment by memeplex** [comment] 2024-08-02 20:51
Ok @mjbvz thanks for the clarification.
