### ISSUE TITLE
Break on line decoration remained after debug session ended

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91094] opened 2020-02-20 15:51 UTC
I'm not sure how to repro this, but while prepping the demos today I noticed the paused indicator remained even after my debug session ended:

![image](https://user-images.githubusercontent.com/2230985/74952807-a293c280-53b5-11ea-968d-57c533232429.png)

When I started a debug session again, I could set breakpoints on that line, but the breakpoint decorations didn't appear. After I closed the second debug session, the state returned to normal.

**Comment by isidorn** [comment] 2020-02-20 16:15
Assigning to this milestone as it soundns like a regression so we investigte more.

**Comment by roblourens** [comment] 2020-02-20 17:01
I think this is what I saw while demoing in the call 😳

**Comment by isidorn** [comment] 2020-02-21 15:24
Please let me know if you still see this.
Since it might be fixed with the same fix for https://github.com/microsoft/vscode/issues/90940
I tried reproducing this and could not.

**Comment by isidorn** [comment] 2020-02-25 15:57
Optimistically closing and if you still see this please let me know and I will reopen

**Closed by isidorn** 2020-02-25 15:57 UTC
Labels: debug, needs more info, under-discussion
