### ISSUE TITLE
higlighting closing tags when open tag is clicked

### ISSUE THREAD

**Issue by thaboMoeketsi** [Microsoft/vscode#13683] opened 2016-10-13 14:29 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by aeschli** [comment] 2016-10-14 06:10
@thaboMoeketsi Which language? Please add a code snippet that shows what you expect.

**Comment by thaboMoeketsi** [comment] 2016-10-14 10:53
HTML 
![image](https://cloud.githubusercontent.com/assets/20064517/19385068/97ac18f4-91c1-11e6-8c8e-3d747b972ba2.png)

i want to see where the closing tag of div is when i click but it highlight all the div tags

**Comment by aeschli** [comment] 2016-10-16 21:48
duplicate of #2915

**Closed by aeschli** 2016-10-16 21:48 UTC
Labels: needs more info
