### ISSUE TITLE
Keyboard shortcut to fold all imports

### ISSUE THREAD

**Issue by nolancasimir** [microsoft/vscode#187050] opened 2023-07-05 13:06 UTC
There are currently keyboard shortcuts to fold all comments, and fold all regions. The third category of folding ranges, imports, has no keyboard shortcuts tied to it. For my org, I made an extension that overrides the default C folding ranges, and replaces them with more useful folds specific to our code, and tied them to keyboard shortcuts. We desire to add one more classification, but currently cannot map the fold to a shortcut.

**Comment by aeschli** [comment] 2023-08-18 14:03
You want a `Fold all import` command, correct?

Duplicate of https://github.com/microsoft/vscode/issues/130678

**Closed by aeschli** 2023-08-18 14:03 UTC

**Comment by nolancasimir** [comment] 2023-08-18 15:26
Correct. Thanks for looking into this!
