### ISSUE TITLE
Config different color theme per language

### ISSUE THREAD

**Issue by HaoyangFan** [Microsoft/vscode#55555] opened 2018-08-01 04:21 UTC
Is there a way for vscode to automatically alter the color theme according to the type of file that is currently opened in the workspace. I found a similar discussion #20652 but it doesn't give a exact answer for this question.

Ideally, I can set up the color themes for different languages in the user setting

```
"[javascript]": {
    "editor.colorTheme": "default dark"
}
```

I know this is probably hard to implement: since user could have different types of files mixed in a workspace and keep different file opened in the open editor. I would really appreciate if someone can purpose a way to achieve this effect

**Comment by aeschli** [comment] 2018-08-02 08:59
duplicate of #20652

See the discussions in the issue there. There's also an extension that gives it try:
https://github.com/jsaulou/vscode-theme-by-language

**Closed by aeschli** 2018-08-02 08:59 UTC
Labels: themes
