### ISSUE TITLE
Extensions not working, C# not recognized

### ISSUE THREAD

**Issue by danielpunct** [Microsoft/vscode#19816] opened 2017-02-03 09:41 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-earlytobed|PasqNet|0.0.4|
|theme-darktooth|Poorchop|0.0.2|
|unity-debug|Unity|1.1.0|
|python|donjayamanne|0.5.8|
|json-tools|eriklynd|1.0.2|
|Theme-Boron|gerane|0.0.4|
|Theme-Capo-Dark|gerane|0.0.2|
|Theme-CloudsMidnight|gerane|0.0.2|
|Theme-DarkRoomContrast|gerane|0.0.2|
|Theme-DarkRoomNormal|gerane|0.0.2|
|Theme-GrandsonOfObsidian|gerane|0.0.2|
|Theme-Harper|gerane|0.0.2|
|Theme-Jellybeams|gerane|0.0.2|
|Theme-Ocean-Dark-Soda|gerane|0.0.2|
|Theme-TomorrowNight|gerane|0.0.2|
|Theme-arstotzka|gerane|0.0.2|
|Theme-dimmed-monokai-no-contrast|gerane|0.0.2|
|theme-chromodynamics|lei|1.0.8|
|csharp|ms-vscode|1.6.2|
|theme-obsidian|rprouse|0.2.0|
|Align|steve8708|0.2.0|
|theme-arstotzka|none|0.0.1|
|theme-base16ocean dark (colorcoded)|none|0.0.1|

---

Hi,
I just updated VSCode and all the extensions keep remaining in the Reload state, and in my case C# is not recognised as a language.

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment] 2017-02-03 10:47
Duplicate of #19753

**Closed by sandy081** 2017-02-03 10:47 UTC
