### ISSUE TITLE
Sticky Scroll: Inlay Hints aren't updated when shown/hidden by keybinding

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#156786] opened 2022-08-01 09:57 UTC
Type: <b>Bug</b>

Testing #156175

1. Set `editor.inlayHints.enabled` to `onUnlessPressed` (same for `offUnlessPressed`)
2. Scroll down in JS/TS file so 
3. Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd> - inlay hints are hidden from code but still visible in function parameters

![image](https://user-images.githubusercontent.com/1312662/182123762-9d0b6942-c94c-4be0-a51e-ce94c5e7a9e9.png)

"Workaround"
4. Scroll a bit to "refresh" sticky line (not need to scroll up to function declaration, just few lines is enough) - inlay hints are hidden from both code and function parameters

VS Code version: Code - Insiders 1.70.0-insider (12b08be500f8a307f30e92cbc3ee39ba115eab69, 2022-07-29T10:47:14.408Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (15.72GB free)|
|Process Argv|--crash-reporter-id 19aedffb-5c29-4248-9110-b5b20040c42f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aiday-mar** [comment] 2023-07-13 13:50
Hi, thanks for filing the issue. An issue has been opened which aims to add all kinds of decorations to sticky scroll, such as diff background colors, highlights, code lens text, indentation guides. You may track and upvote the issue here: https://github.com/microsoft/vscode/issues/187834

**Comment by aiday-mar** [comment] 2023-12-05 11:37
Hi this issue is a duplicate of the issue https://github.com/microsoft/vscode/issues/187834. This issue will be closed in favor of the other issue. You may track progress there.

**Closed by aiday-mar** 2023-12-05 11:37 UTC
Labels: bug, inlay-hints, editor-sticky-scroll
