### ISSUE TITLE
Module import intellisense is not working

### ISSUE THREAD

**Issue by anjmao** [Microsoft/vscode#36759] opened 2017-10-23 15:06 UTC
- VSCode Version: 1.17.2
- OS Version: macOS Sierra

Steps to Reproduce:

1. `import 'angular'` intellisense is not working and it is not suggesting me angular
2. `import {} from 'angular'` now intellisense works

![image](https://user-images.githubusercontent.com/3028012/31896270-04d4c760-b81c-11e7-9210-04aa04da195d.png)

Note that I can still use control + space but if I have some longer imports I need to click it on every folder path.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-23 17:39
Duplicate of #35691

Should be fixed already in insiders builds

**Closed by mjbvz** 2017-10-23 17:39 UTC
Labels: javascript, new release
