### ISSUE TITLE
Search system failure

### ISSUE THREAD

**Issue by catchjack** [Microsoft/vscode#31618] opened 2017-07-28 02:20 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
vscode-simple-icons|Lau|1.4.2
vscode-todo|Mat|0.8.0
material-icon-theme|PKi|2.0.11
vscode-docker|Pet|0.0.16
html-css-class-completion|Zig|1.8.0
html-snippets|abu|0.1.0
project-manager|ale|0.18.1
vscode-color|ans|0.4.1
vscode-icontheme-nomo-dark|be5|1.3.2
code-react-instyle|boo|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
react-redux-snippets|dan|0.1.1
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
githistory|don|0.2.2
javadebugger|don|0.1.3
jquerysnippets|don|0.0.1
python|don|0.6.9
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.12
vscode-theme-seti-fania|fan|0.1.0
docthis|joe|0.4.7
MagicPython|mag|1.0.11
code-beautifier|mic|1.7.2
vscode-todo-parser|min|1.9.0
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.1
cpptools|ms-|0.12.1
js-atom-grammar|ms-|0.1.13
debugger-for-chrome|msj|3.1.6
color-highlight|nau|2.3.0
seti-icons|qin|0.1.3
java|red|0.7.0
vscode-icons|rob|7.11.0
sass-indented|rob|1.4.1
vue|sea|0.4.2
guides|spy|0.8.4
language-stylus|sys|1.7.3
ayu|tea|0.4.0
python|tht|0.2.3
vim|vsc|0.9.0
JavaScriptSnippets|xab|1.4.1

(8 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment] 2017-07-28 18:23
Since there is no detail and reproduce steps at all, close it first and reopen when we have more info.

**Closed by rebornix** 2017-07-28 18:23 UTC
Labels: new release
