### ISSUE TITLE
Slow startup.

### ISSUE THREAD

**Issue by MonsterZelek** [microsoft/vscode#137955] opened 2021-11-26 19:21 UTC
Slow startup for months, but just now I report. Its maybe even slower than my laptop in eco mode with i7 3630qm. Laptop without eco mode starts 3 times faster than on this PC in high mode...

## System Info

* Code: 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247)
* OS: win32(10.0.19042)
* CPUs: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz(12 x 3696)
* Memory(System): 15.95 GB(12.88GB free)
* Memory(Process): 176.79 MB working set(125.56MB private, 0.15MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 1037     | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 1        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 111      | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 991      | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 26       | [main]                    | initial startup: true, state: 0ms, widget: 24ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 193      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 2731     | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 683      | [renderer]                | cached data: NO, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 16       | [renderer]                | -                                                          |
| init workspace service                                          | 47       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 2768     | [renderer]                | -                                                          |
| restore viewlet                                                 | 18       | [renderer]                | workbench.view.explorer                                    |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 61       | [renderer]                | 0:                                                         |
| overall workbench load                                          | 281      | [renderer]                | -                                                          |
| workbench ready                                                 | 4985     | [main->renderer]          | -                                                          |
| renderer ready                                                  | 1032     | [renderer]                | -                                                          |
| shared process connection ready                                 | 2482     | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 7822     | [renderer]                | -                                                          |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 6         | 0             | 11              | *                                 | vscode.debug-auto-launch                |
| vscode.git                              | true  | 89        | 1             | 1200            | *                                 | vscode.github                           |
| vscode.github                           | true  | 8         | 0             | 0               | *                                 | vscode.github                           |
| christian-kohler.path-intellisense      | true  | 38        | 1             | 11              | *                                 | christian-kohler.path-intellisense      |
| Equinusocio.vsc-material-theme          | true  | 24        | 0             | 1173            | *                                 | Equinusocio.vsc-material-theme          |
| equinusocio.vsc-material-theme-icons    | true  | 24        | 3             | 8               | *                                 | equinusocio.vsc-material-theme-icons    |
| formulahendry.auto-rename-tag           | true  | 38        | 4             | 1167            | *                                 | formulahendry.auto-rename-tag           |
| HookyQR.beautify                        | true  | 55        | 0             | 4               | *                                 | HookyQR.beautify                        |
| naumovs.color-highlight                 | true  | 13        | 0             | 4               | *                                 | naumovs.color-highlight                 |
| xyz.local-history                       | true  | 44        | 1             | 3               | *                                 | xyz.local-history                       |
| vscode.configuration-editing            | false | 6         | 0             | 3               | onLanguage:jsonc                  | vscode.configuration-editing            |
| vscode.github-authentication            | false | 33        | 0             | 1               | onAuthenticationRequest:github    | vscode.github-authentication            |
| vscode.json-language-features           | false | 51        | 2             | 1               | onLanguage:jsonc                  | vscode.json-language-features           |
| vscode.merge-conflict                   | false | 3         | 1             | 28              | onStartupFinished                 | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 53        | 1             | 1118            | onAuthenticationRequest:microsoft | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 27        | 9             | 20              | onStartupFinished                 | ms-vscode-remote.remote-wsl-recommender |
| vscode.typescript-language-features     | false | 49        | 1             | 1               | onLanguage:jsonc                  | vscode.typescript-language-features     |
| CoenraadS.bracket-pair-colorizer-2      | false | 18        | 12            | 8               | onStartupFinished                 | CoenraadS.bracket-pair-colorizer-2      |
| esbenp.prettier-vscode                  | false | 552       | 7             | 1               | onStartupFinished                 | esbenp.prettier-vscode                  |
| PKief.material-icon-theme               | false | 16        | 0             | 8               | onStartupFinished                 | PKief.material-icon-theme               |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1637953156060	0	0
code/didStartMain	1637953156156	96	96
code/willStartCrashReporter	1637953156173	17	113
code/didStartCrashReporter	1637953157164	991	1104
code/mainAppReady	1637953157193	29	1133
code/willGenerateNls	1637953157195	2	1135
code/didGenerateNls	1637953157196	1	1136
code/willLoadMainBundle	1637953157196	0	1136
code/fork/willLoadCode	1637953157212	16	1152
code/registerFilesystem/file	1637953157303	91	1243
code/didLoadMainBundle	1637953157307	4	1247
code/willStartMainServer	1637953157316	9	1256
code/didStartMainServer	1637953157318	2	1258
code/willCreateCodeWindow	1637953157355	37	1295
code/willRestoreCodeWindowState	1637953157356	1	1296
code/didRestoreCodeWindowState	1637953157356	0	1296
code/willCreateCodeBrowserWindow	1637953157356	0	1296
code/didCreateCodeBrowserWindow	1637953157380	24	1320
code/didCreateCodeWindow	1637953157381	1	1321
code/willOpenNewWindow	1637953157386	5	1326
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1637953157387	0	0
code/didStartRenderer	1637953160109	2722	2722
code/willWaitForWindowConfig	1637953160110	1	2723
code/didWaitForWindowConfig	1637953160110	0	2723
code/willShowPartsSplash	1637953160110	0	2723
code/didShowPartsSplash	1637953160110	0	2723
code/willLoadWorkbenchMain	1637953160117	7	2730
code/didLoadWorkbenchMain	1637953160800	683	3413
code/registerFilesystem/file	1637953160805	5	3418
code/registerFilesystem/vscode-userdata	1637953160805	0	3418
code/willInitWorkspaceService	1637953160809	4	3422
code/willInitStorage	1637953160810	1	3423
code/didInitStorage	1637953160826	16	3439
code/willInitUserConfiguration	1637953160839	13	3452
code/didInitUserConfiguration	1637953160841	2	3454
code/willInitWorkspaceConfiguration	1637953160841	0	3454
code/didInitWorkspaceConfiguration	1637953160856	15	3469
code/didInitWorkspaceService	1637953160856	0	3469
code/willStartWorkbench	1637953160860	4	3473
code/LifecyclePhase/Ready	1637953160932	72	3545
code/registerFilesystem/trustedDomains	1637953160961	29	3574
code/willRestoreEditors	1637953161079	118	3692
code/willRestoreViewlet	1637953161082	3	3695
code/didRestoreViewlet	1637953161100	18	3713
code/willResolveExplorer	1637953161124	24	3737
code/didRestoreEditors	1637953161140	16	3753
code/LifecyclePhase/Restored	1637953161141	1	3754
code/didStartWorkbench	1637953161141	0	3754
code/didRemovePartsSplash	1637953161141	0	3754
code/willConnectSharedProcess	1637953161169	28	3782
code/willLoadExtensions	1637953161210	41	3823
code/didResolveExplorer	1637953163551	2341	6164
code/didConnectSharedProcess	1637953163651	100	6264
code/willHandleExtensionPoints	1637953163684	33	6297
code/didHandleExtensionPoints	1637953163972	288	6585
code/didLoadExtensions	1637953163978	6	6591
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1637953163468	0	0
code/fork/start	1637953163601	133	133
code/fork/willLoadCode	1637953163638	37	170
code/extHost/willConnectToRenderer	1637953164073	435	605
code/extHost/didConnectToRenderer	1637953164074	1	606
code/extHost/didWaitForInitData	1637953164219	145	751
code/extHost/didCreateServices	1637953164230	11	762
code/extHost/willWaitForConfig	1637953164233	3	765
code/extHost/didWaitForConfig	1637953164273	40	805
code/extHost/didInitAPI	1637953164304	31	836
code/extHost/didInitProxyResolver	1637953164308	4	840
code/extHost/ready	1637953164308	0	840
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1637953164320	12	852
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1637953164373	53	905
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1637953164373	0	905
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1637953164379	6	911
code/extHost/willLoadExtensionCode/vscode.git	1637953164379	0	911
code/extHost/didLoadExtensionCode/vscode.git	1637953164468	89	1000
code/extHost/willLoadExtensionCode/christian-kohler.path-intellisense	1637953164468	0	1000
code/extHost/didLoadExtensionCode/christian-kohler.path-intellisense	1637953164506	38	1038
code/extHost/willLoadExtensionCode/Equinusocio.vsc-material-theme	1637953164506	0	1038
code/extHost/didLoadExtensionCode/Equinusocio.vsc-material-theme	1637953164530	24	1062
code/extHost/willLoadExtensionCode/equinusocio.vsc-material-theme-icons	1637953164530	0	1062
code/extHost/didLoadExtensionCode/equinusocio.vsc-material-theme-icons	1637953164554	24	1086
code/extHost/willLoadExtensionCode/formulahendry.auto-rename-tag	1637953164554	0	1086
code/extHost/didLoadExtensionCode/formulahendry.auto-rename-tag	1637953164592	38	1124
code/extHost/willLoadExtensionCode/HookyQR.beautify	1637953164592	0	1124
code/extHost/didLoadExtensionCode/HookyQR.beautify	1637953164647	55	1179
code/extHost/willLoadExtensionCode/naumovs.color-highlight	1637953164647	0	1179
code/extHost/didLoadExtensionCode/naumovs.color-highlight	1637953164660	13	1192
code/extHost/willLoadExtensionCode/xyz.local-history	1637953164660	0	1192
code/extHost/didLoadExtensionCode/xyz.local-history	1637953164704	44	1236
code/extHost/willActivateExtension/vscode.microsoft-authentication	1637953164720	16	1252
code/extHost/willActivateExtension/vscode.debug-auto-launch	1637953164721	1	1253
code/extHost/willActivateExtension/vscode.git	1637953164721	0	1253
code/extHost/willActivateExtension/christian-kohler.path-intellisense	1637953164722	1	1254
code/extHost/willActivateExtension/Equinusocio.vsc-material-theme	1637953164723	1	1255
code/extHost/willActivateExtension/equinusocio.vsc-material-theme-icons	1637953164723	0	1255
code/extHost/willActivateExtension/formulahendry.auto-rename-tag	1637953164726	3	1258
code/extHost/willActivateExtension/HookyQR.beautify	1637953164730	4	1262
code/extHost/willActivateExtension/naumovs.color-highlight	1637953164730	0	1262
code/extHost/willActivateExtension/xyz.local-history	1637953164730	0	1262
code/extHost/didActivateExtension/vscode.debug-auto-launch	1637953164740	10	1272
code/extHost/didActivateExtension/christian-kohler.path-intellisense	1637953164740	0	1272
code/extHost/didActivateExtension/equinusocio.vsc-material-theme-icons	1637953164740	0	1272
code/extHost/didActivateExtension/HookyQR.beautify	1637953164740	0	1272
code/extHost/didActivateExtension/naumovs.color-highlight	1637953164740	0	1272
code/extHost/didActivateExtension/xyz.local-history	1637953164740	0	1272
code/extHost/didActivateExtension/vscode.microsoft-authentication	1637953165839	1099	2371
code/extHost/willLoadExtensionCode/vscode.github-authentication	1637953165863	24	2395
code/extHost/didLoadExtensionCode/vscode.github-authentication	1637953165896	33	2428
code/extHost/didActivateExtension/Equinusocio.vsc-material-theme	1637953165896	0	2428
code/extHost/didActivateExtension/formulahendry.auto-rename-tag	1637953165897	1	2429
code/extHost/willActivateExtension/vscode.github-authentication	1637953165898	1	2430
code/extHost/didActivateExtension/vscode.github-authentication	1637953165900	2	2432
code/extHost/didActivateExtension/vscode.git	1637953165922	22	2454
code/extHost/willLoadExtensionCode/vscode.github	1637953165924	2	2456
code/extHost/didLoadExtensionCode/vscode.github	1637953165932	8	2464
code/extHost/willActivateExtension/vscode.github	1637953165934	2	2466
code/extHost/didActivateExtension/vscode.github	1637953165934	0	2466
```

### cached data created (lazy, might need refreshes)

[prof-27d4.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/7610370/prof-27d4.renderer.cpuprofile.txt)
[prof-27d4.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/7610371/prof-27d4.extHost.cpuprofile.txt)
[prof-27d4.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/7610373/prof-27d4.main.cpuprofile.txt)

**Comment by jrieken** [comment] 2021-11-29 08:13
/duplicate of https://github.com/microsoft/vscode/issues/22087

**Closed** 2021-11-29 08:14 UTC
Labels: *duplicate, perf-startup
