### ISSUE TITLE
under line can not display in Rename Symbol Inputbox, when setting font=monospace and fontsize=14

### ISSUE THREAD

**Issue by rhdlilj** [microsoft/vscode#115577] opened 2021-02-02 04:00 UTC
Under line can not display in Rename Symbol Inputbox, when setting font=monospace and fontsize=14

VS Code version: Code 1.52.1
OS: Ubuntu 18.04

**Comment by rhdlilj** [comment] 2021-02-03 01:35
`Window: Zoom Level` is a condition too. `Editor: Font Family=monospace`,`Editor: Font Size=14`,`Window: Zoom Level=0`, the `_` dispaly as a `SPACE`.
![a](https://user-images.githubusercontent.com/55023294/106685313-1b118480-6603-11eb-8762-c8c357a16c2d.gif)

**Comment by jrieken** [comment] 2021-02-03 08:21
Thanks for clarifying. We have an item that is about replacing the simple input box with the text editor. That should also fix this https://github.com/microsoft/vscode/issues/53666. Leaving this item around but most likely it will be indirectly fixed when moving to the editor

**Comment by jrieken** [comment] 2021-09-27 13:57
closing this as dupe of https://github.com/microsoft/vscode/issues/53666

**Closed by jrieken** 2021-09-27 13:57 UTC
Labels: bug, rename
