### ISSUE TITLE
Tabs: Pointless insertion of ellipses for description

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#42032] opened 2018-01-23 11:16 UTC
* use tabs
* open a file with the uri `mem://füø/testz`
* arrange tabs/window so that there is limited width 
* 🐛 ellipses are being inserted but nothing is being removed

<img width="535" alt="screen shot 2018-01-23 at 12 05 48" src="https://user-images.githubusercontent.com/1794099/35272881-fe906734-0036-11e8-8f17-f4c54861d744.png">

**Comment by jrieken** [comment] 2018-01-23 11:17
this fs-provider is being used: https://github.com/Microsoft/vscode/issues/36946#issuecomment-358902019

**Comment by bpasero** [comment] 2018-01-23 11:23
Weird, but seems like a Chrome bug to me, we are just relying on CSS `text-overflow:ellipsis`.

**Comment by bpasero** [comment] 2018-01-23 11:24
@jrieken can you inspect the description element, is there really no text coming after the `füø/`?

**Comment by jrieken** [comment] 2018-01-23 11:27
This isn't about the trailing ellipses but about the one in the middle, between the first and second slash

<img width="535" alt="screen shot 2018-01-23 at 12 05 48" src="https://user-images.githubusercontent.com/1794099/35273397-ccf92fa6-0038-11e8-91cb-1f372dac7e0e.png">

**Comment by bpasero** [comment] 2018-01-23 11:38
@jrieken that one is on purpose because you happen to have 2 files of the same name and [our algorithm](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L145) will shorten the path enough to show the difference. 

Closing as designed, I actually very much like this behaviour (it came in through a PR from a contribution).

**Comment by bpasero** [comment] 2018-01-23 11:39
Ah but something is broken when computing that thing, probably because we are only fit for file URIs there.

**Comment by bpasero** [comment] 2018-01-23 11:40
@hun1ahpu please take a look

**Comment by bpasero** [comment] 2019-05-08 09:15
I cannot reproduce this

![image](https://user-images.githubusercontent.com/900690/57364015-928e5780-7182-11e9-913e-d13b9d8841fa.png)

I assume this is fixed meanwhile, otherwise please reopen with steps how to reproduce. I tried with the mem-fs extension creating 2 files of same name in different folders.

**Closed by bpasero** 2019-05-08 09:15 UTC
Labels: bug, workbench-tabs
