### ISSUE TITLE
lost settings.json

### ISSUE THREAD

**Issue by laoshaw** [Microsoft/vscode#69924] opened 2019-03-07 01:59 UTC
using the newest vscode after a 4 month pause, all of a sudden my hand crafted settings.json is gone, I have settings-sync installed and was told it's up to date, I however could not see the settings.json anymore with the vscode version 1.31.1.

lots of time spent on learning vscode over the past two years, I have no more motive to find out why my settings.json is gone anymore, plus all those plugins etc. I'm back to webstorm. So long and thanks for all the fish.

**Comment by joaomoreno** [comment] 2019-03-07 07:09
Could very well be settings sync, but checking with @sandy081 just to be sure.

**Comment by iashbringer** [comment] 2019-03-08 07:22
I lost my settings.json file after updating the version to latest version.
版本: 1.32.1 (user setup)
提交: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
日期: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment] 2019-03-11 10:40
@laoshaw Sorry for what happened. I am guessing this could be due to settings sync extension. 

@iashbringer Do you also have settings sync extension?

**Comment by iashbringer** [comment] 2019-03-11 12:35
@sandy081
No.

**Comment by sandy081** [comment] 2019-03-15 14:54
I cannot reproduce it.

Is it possible to provide any steps to repro here?

**Comment by iashbringer** [comment] 2019-03-18 02:31
Sorry,no more steps.
I only lost settings.json.
No thing else lost.(snippets,keybindings.json)

**Comment by sandy081** [comment] 2019-03-19 13:37
Not sure what can be done without steps to repro it. Closing it for now.

**Closed by sandy081** 2019-03-19 13:37 UTC
Labels: needs more info
