### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by Korokoukousei** [microsoft/vscode#146132] opened 2022-03-27 15:30 UTC
Issue Type: <b>Bug</b>

Just installed vs code on linux, i want to sign in with github to sync my settings and extentions from windows.
But when i click on the accounts symbol, nothing happens.
I tried reinstalling VS Code, both from the snap store and using the .deb file from the website.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-37-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (6.18GB free)|
|Process Argv|--no-sandbox --crash-reporter-id e909c289-0d27-42f2-b1bc-ad725ee74188|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
vscaac:30438847
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-03-27 15:50
/duplicate of https://github.com/microsoft/vscode/issues/145282

**Closed** 2022-03-27 15:50 UTC
Labels: *duplicate
