### ISSUE TITLE
Open an empty folder workspace and then turing it into a workspace with that folder open doesn't render the folder

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35377] opened 2017-09-29 13:42 UTC
![cast](https://user-images.githubusercontent.com/1931590/31018530-c8a92206-a52c-11e7-8ff6-ef1aad9a3cf9.gif)

**Comment by bpasero** [comment] 2017-09-29 13:57
Good catch, I think the problem is that there is no "workspace folder added" event because the same folder is already part  of the workspace. 

@isidorn moving to you, I think the explorer should still handle the workbench state change (from folder to workspace) properly.

**Comment by isidorn** [comment] 2017-10-04 09:49
Good catch, this is fixed via b597b6f55e

**Closed by isidorn** 2017-10-04 09:49 UTC
Labels: bug, multi-root, workbench
