### ISSUE TITLE
HTML comment

### ISSUE THREAD

**Issue by angelsix** [Microsoft/vscode#19380] opened 2017-01-25 17:08 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

```
<!------->
<div>something</div>
```

This is a valid start and end HTML comment, but the lines all below it show as commented
It only detects a space then --> as the end, not one that ends directly without a space. It only happens if there are an odd number of -'s

**Comment by aeschli** [comment] 2017-01-26 09:00
duplicate of #13778.

See the HTML spec, your comment is invalid:
> text must not ... contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-)

That's why the comment content is rendered red ('invalid')

**Closed by aeschli** 2017-01-26 09:00 UTC
Labels: html
