### ISSUE TITLE
Typing an import makes TS unresponsive for > 30s

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#20815] opened 2017-02-17 15:36 UTC
Type the following, one character at a time (i.e. no copy-paste tricks)

`import * as viewEvents from 'vs/editor/common/view/viewEvents';`

Observe how errors show up and the entire language service is unresponsive for >30s.

Saw it on Linux, but I don't think it is an OS specific issue

This is highly annoying and blocks me from being productive while selfhosting.

fyi @jrieken

**Comment by mjbvz** [comment] 2017-02-17 19:57
To investigate this, try collecting some logs from the TypeScript server when this occurs. Here's information on to do this using the TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging

From a command prompt, run:

```
$ export TSS_LOG="-level verbose -file /Users/USERNAME/.tslog"
$ code 
```

Reproduce the problem in VSCode and then share the `.tslog` file.

Let me know if you have any questions about this.

Thanks

**Comment by jrieken** [comment] 2017-02-20 15:58
I'd say this is the same as https://github.com/Microsoft/vscode/issues/18792. @mjbvz Are you [saying](https://github.com/Microsoft/vscode/issues/20815#issuecomment-280750815) you don't see that?

**Comment by alexandrudima** [comment] 2017-02-20 16:36
@mjbvz Here you go:
[tslog.txt.tar.gz](https://github.com/Microsoft/vscode/files/788025/tslog.txt.tar.gz)

Here is also a gif of me typing the import. The gif is not a loop, it eventually comes back ~50s later:
![ts-server-slow](https://cloud.githubusercontent.com/assets/5047891/23133828/cd3d62f2-f792-11e6-8d78-0c839dee9bfc.gif)

Please let me know if you encounter further difficulties in reproducing.

**Comment by alexandrudima** [comment] 2017-02-20 16:47
This is the TS version appearing in the status bar:

![image](https://cloud.githubusercontent.com/assets/5047891/23134222/4636bb58-f794-11e6-82fc-0a48695a6028.png)

And here is the time it takes for tsserver to become responsive when pasting the import:

![ts-server-paste](https://cloud.githubusercontent.com/assets/5047891/23134299/8fd055d0-f794-11e6-97b1-c6d6f62572a6.gif)

**Comment by alexandrudima** [comment] 2017-02-20 16:51
### Notice how fast VS Code 1.8.1 is:

![ts-server-1 8 1](https://cloud.githubusercontent.com/assets/5047891/23134467/3d7243ec-f795-11e6-8c70-44d8bd447035.gif)

**Comment by sandy081** [comment] 2017-02-21 15:36
I also saw this slowness today. Intellisense and Diagnostics are very slow. I had to reload to get back to normal state

**Comment by mjbvz** [comment] 2017-02-21 19:42
@mhegazy Can you please take a look here? I don't see anything explicitly going wrong on the VSCode side, but the request queue lengths do quickly build up which I believe causes this behavior.

The reason the queues get so long may be, `getCodeFixes` which starts out taking only a few ms but ends up taking 3.5 seconds plus in requests later on. I don't see any obvious causes in the TSS_LOGS for this

**Comment by mjbvz** [comment] 2017-02-21 22:27
Thanks everyone. @vladima took in a fix on the TS side  https://github.com/Microsoft/TypeScript/pull/14215 and I also checked in a workaround on our side 02006fe

**Closed** 2017-02-21 22:27 UTC
Labels: bug, needs more info, typescript

**Comment by alexandrudima** [comment] 2017-02-22 08:21
@mjbvz @vladima Thanks a lot for the fix, I really appreciate it 💯 🚀
