### ISSUE TITLE
Cannot delete file using delete

### ISSUE THREAD

**Issue by smallp** [microsoft/vscode#77042] opened 2019-07-10 03:17 UTC
Issue Type: <b>Bug</b>

Select a file and press delete, then delete has been caught by fitter. I have to delete a file by right click it and click del.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-54-generic/Ubuntu 18.04

Disable all extension does not fix it.

**Comment by usernamehw** [comment] 2019-07-10 07:05
/duplicate of #76514

Fixed in **1.36.1** version.

**Closed** 2019-07-10 07:05 UTC
Labels: *duplicate, editor-contrib
