### ISSUE TITLE
Middle-click Scrolling

### ISSUE THREAD

**Issue by jschraub** [Microsoft/vscode#16514] opened 2016-12-05 16:10 UTC
New feature suggestion: Middle mouse click scrolling

This is another feature that is supported by Visual Studio and Edge that would be useful in VSCode.

When the middle mouse click is pressed, it toggles the cursor to a quad-directional arrow.  Once that is toggled, moving the mouse in relation to where the mouse was when toggled, will scroll the page in the corresponding direction.

**Comment by jschraub** [comment] 2016-12-05 16:12
@DanJ210, I know you were talking about this as a new feature.  Please comment here to add any more details that you believe would be useful for this feature request.

**Comment by DanJ210** [comment] 2016-12-11 18:19
@jschraub Oh yea thanks. For right now this would be a cool feature to have upcoming. I'll post anymore that I can think of. I can't wait for some of the VScode insider features and changes to get released to the main branch. I'd use VScode insiders but I was having an issue or two and I need it working for school.

**Comment by nathanchase** [comment] 2017-05-01 02:58
Would love to see this implemented in VSCode. I use middle-mouse-button scrolling all the time in the browser. I miss it when I'm in the editor.

**Comment by CoenraadS** [comment] 2017-06-02 15:28
The funny thing is that middle click scrolling already works in the release notes, so hopefully it should be simple to get it working also in the text editors. This is also a dupe of: https://github.com/Microsoft/vscode/issues/6302

**Comment by Tyriar** [comment] 2018-01-02 14:20
Duplicate https://github.com/Microsoft/vscode/issues/6302

**Closed by Tyriar** 2018-01-02 14:20 UTC
Labels: editor, editor-core, feature-request, windows
