### ISSUE TITLE
Debian-Repository: Writing more data than expected (35578 > 35343)

### ISSUE THREAD

**Issue by Nols1000** [Microsoft/vscode#41100] opened 2018-01-03 15:06 UTC
When I try to follow the [Installation-Guide](https://code.visualstudio.com/docs/?dv=linux64_deb) and try to use the repository instead of the deb-file. I get this error message:

```bash
Get:6 https://packages.microsoft.com/repos/vscode stable InRelease [2,802 B]
Get:7 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages [35.3 kB]
Err:7 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  Writing more data than expected (35578 > 35343)
  Hashes of expected file:
   - Filesize:35343 [weak]
   - SHA512:c9496b6c369f633e2ae431bb758cf970671c191bd02264713ce864dc327475b9ca7cdddda7dee0a14a556dc65d6b59a8f79f16c47e178a6345c90878c99fa0c8
   - SHA256:fba8fa5d5d6d200e9b45febf5bb0e9fe0d9165202c2cbfe38c72d64a423cf4a3
   - SHA1:66776788449c7465ac8668f904c730310fd95e37 [weak]
   - MD5Sum:c87007bbbd77cb0d60fa69f5f83b6a7c [weak]
  Release file created at: Thu, 21 Dec 2017 18:21:42 +0000
```

- VSCode Version: not related
- OS Version: Debian 4.9.65-3+deb9u1

Steps to Reproduce:

1. execute 
```bash
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
```
2. execute `sudo apt-get update`

Reproduces without extensions: not related

**Comment by SeameX** [comment] 2018-01-03 15:10
duplicate of https://github.com/Microsoft/vscode/issues/41094

**Closed** 2018-01-03 16:08 UTC
Labels: *duplicate, install-update
