### ISSUE TITLE
VSCode crach when Drag and drop a gif image from an extension page to a new tab

### ISSUE THREAD

**Issue by kzelda** [Microsoft/vscode#21479] opened 2017-02-27 09:20 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-angular2-files|alexiv|1.3.8|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|angular2-snippets|danwahlin|1.0.12|
|vscode-instant-markdown|dbankier|0.1.0|
|githistory|donjayamanne|0.1.0|
|theme-dracula|dracula-theme|1.2.5|
|tslint|eg2|0.5.40|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|beautify|HookyQR|0.5.4|
|minify|HookyQR|0.2.5|
|Angular2|johnpapa|2.0.3|
|vscode-exec-node|miramac|0.1.8|
|atom-keybindings|ms-vscode|1.2.1|
|csharp|ms-vscode|1.5.1|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|sharecode|RolandGreim|0.3.1|
|vscode-open|sandcastle|0.0.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.  search "Angular Files"  extension
2.  click on "Angular Files" extension , then drag and drop the gif file to a new vscode tab

**Comment by bpasero** [comment] 2017-02-27 09:55
I cannot reproduce, can you somehow record a video how this reproduces?

**Comment by isidorn** [comment] 2017-03-03 10:40
Closing until more details are provided

**Closed by isidorn** 2017-03-03 10:40 UTC
Labels: needs more info
