### ISSUE TITLE
do i have a way to change native windows console ?

### ISSUE THREAD

**Issue by Trim21** [Microsoft/vscode#5421] opened 2016-04-17 19:43 UTC
- VSCode Version:1.0.0
- windows 10 home 

Steps to Reproduce:

when i use shortcuts `workbench.action.terminal.openNativeConsole` i can only  open a cmd but i can't open a powerhsell. is there a why to change the shell vsc open?

**Comment by joaomoreno** [comment] 2016-04-18 12:11
Duplicate of #3495

**Closed by joaomoreno** 2016-04-18 12:11 UTC
