### ISSUE TITLE
Debug: breakpoint doesn't work with `babel-register` and source maps

### ISSUE THREAD

**Issue by yanivefraim** [Microsoft/vscode#12255] opened 2016-09-19 09:12 UTC
- VSCode Version:
1.5.2 
- OS Version:
OS X El Capitan 10.11.6

Steps to Reproduce:
Use [this](https://github.com/yanivefraim/vscode-node-debug) example repo in order to reproduce the issue (clone + npm install + from vscode choose `launch`/`launch mocha` + F5)

When debugging node (index.js/mocha tests) using `babel-register` + source maps, breakpoint does not function (explicit `debugger` statement does work). 

See examples on those videos:
https://youtu.be/iNNb5Driawg
https://youtu.be/olBJ5HWT-Cw

**Comment by weinand** [comment] 2016-09-20 09:07
duplicate of #5728

**Closed by weinand** 2016-09-20 09:07 UTC
Labels: bug, debug
