### ISSUE TITLE
Settings UI rendering bug

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143824] opened 2022-02-23 22:48 UTC
Resizing the window causes a rendering bug, seems to happen when you are on a setting that shows code syntax text

https://user-images.githubusercontent.com/35271042/155422088-9476ee52-85d6-4c8a-a397-5db9d4a8eddb.mp4

**Comment by rzhao271** [comment] 2022-02-23 22:58
Duplicate of https://github.com/microsoft/vscode/issues/139805

**Closed by rzhao271** 2022-02-23 22:58 UTC
