### ISSUE TITLE
Change font size of markdown cells

### ISSUE THREAD

**Issue by LogicNg** [microsoft/vscode#130426] opened 2021-08-08 09:12 UTC
![image](https://user-images.githubusercontent.com/53685306/128627058-e3047061-463c-4859-96bc-40125a9be0e0.png)

The display size of the words in the markdown cell is barely readable, can you include a setting to change it in the next version?

**Comment by greazer** [comment] 2021-08-09 18:21
This is a dupe of #126294

**Comment by greazer** [comment] 2021-08-09 18:22
I'll let VS Code close.

**Closed** 2021-08-09 18:25 UTC
Labels: *duplicate, notebook-markdown
