### ISSUE TITLE
Rename Refactoring demo in interactive playground broken

### ISSUE THREAD

**Issue by mfurseroberts** [microsoft/vscode#82999] opened 2019-10-21 17:39 UTC
Issue Type: <b>Bug</b>

Open interactive playground.
Click, as instructed on instance of "Book", press F2, get long error.
Alternatively, right-click on "Book" > Refactor > get error "No refactorings available"

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.35GB free)|
|Process Argv|C:\Users\Mat\Desktop\Hotels-master\APIHotels\header-bg.jpg|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
gitlens|eam|10.1.1
php-debug|fel|1.13.0
rainbow-csv|mec|1.3.1
vscode-apache|mrm|1.2.0
vetur|oct|0.22.4

</details>

**Comment by mjbvz** [comment] 2019-10-21 18:15
Duplicate of #82419

**Closed by mjbvz** 2019-10-21 18:15 UTC
