### ISSUE TITLE
Request: Colourise text in Output Channel

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/vscode#1016] opened 2015-12-04 14:03 UTC
I am looking at building an extension that prints a lot of information from errors, debug & warnings so it would be nice to stylise the messages from the realtime logs of a website to help with debugging.

So can I make a feature request please to enable colorised text in Output Channel

**Comment by Thaina** [comment] 2015-12-08 06:52
Duplicated maybe?

https://github.com/Microsoft/vscode/issues/571

**Comment by egamma** [comment] 2015-12-08 11:26
Thanks, yes closing as a duplicate of #571

**Closed by egamma** 2015-12-08 11:26 UTC
Labels: feature request
