### ISSUE TITLE
"Convert to template string" context action for TypeScript and JavaScript

### ISSUE THREAD

**Issue by briman0094** [microsoft/vscode#84882] opened 2019-11-15 01:11 UTC
I find myself using the "To string interpolation" feature of ReSharper a lot when writing C#, and would love to see a similar context action added to Code for JS and TS files. If the cursor is inside a string, a lightbulb action could be made available to change the current string to a template string, automatically escaping any backticks (and maybe unescaping any escaped quotes?). ReSharper also offers this action when the cursor is on any string concatenation operators and it will convert as many consecutive concatenations as possible into one interpolated string.

**Comment by mjbvz** [comment] 2019-11-15 01:44
Duplicate of https://github.com/microsoft/TypeScript/issues/18267

**Closed by mjbvz** 2019-11-15 01:44 UTC
