### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by vurtskider** [microsoft/vscode#95755] opened 2020-04-21 09:30 UTC
Issue Type: <b>Bug</b>

Broken all search in project

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
vscode-whitespacer|dee|1.0.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
sass-lint|gle|1.0.6
beautify|Hoo|1.5.0
intellij-idea-keybindings|k--|0.2.38
require-cartridge-resolve|pik|1.8.0
material-icon-theme|PKi|4.0.1
prophet|Sqr|1.3.3
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.1.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-04-21 10:07
/needsMoreInfo

Please provide steps how to reproduce this issue.

**Comment by vurtskider** [comment] 2020-04-21 11:42
Hi @IllusionMH 
After my last update 'Find in files' doesn't work. (Seach works only with recently opened files)

My colleagues have the same problem.

**Comment by vurtskider** [comment] 2020-04-21 11:43
Just infinite loader and no results

**Comment by IllusionMH** [comment] 2020-04-21 11:47
Do you see any errors in DevTools (Help > Toggle Developer Tools)?

Is it happening in any folder (workspace) or concrete?

**Comment by damacisaac** [comment] 2020-04-22 13:18
Search is also broken for me as of a day or two ago. Not sure the cause yet, but I get the following in the Dev Tools:

```
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

IPC "Search" crashed with exit code null and signal SIGKILL
(anonymous) @ ipc.cp.ts:236
emit @ events.js:203
ChildProcess._handle.onexit @ internal/child_process.js:272
```

**Comment by roblourens** [comment] 2020-04-25 14:33
There was an issue in 1.44.1 which is fixed in 1.44.2. Please try that @vurtskider. @damacisaac if that doesn't help your case, please open a new issue.

**Comment by damacisaac** [comment] 2020-04-27 15:10
This is fixed for me now. Thank you for the quick fix!

**Comment by frankieali** [comment] 2020-07-27 18:48
I had this same problem today. Turns out I had a deprecated setting: `"search.usePCRE2": true,` Once removed search started working as expected.

**Closed** 2020-07-28 05:17 UTC
Labels: needs more info
