### ISSUE TITLE
Feature request: Show detected problems while a task is running, rather than at the end

### ISSUE THREAD

**Issue by oliveroxtoby** [Microsoft/vscode#41769] opened 2018-01-17 19:48 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.11-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.5

At present, when problems are detected by the problem matcher of a custom task, they appear in the problems panel only when the task has finished running. It would be tremendously useful if the problems could be added as they are encountered rather than at the end - e.g. for a make command where you want to get to work on the compile errors while it finishes running.

Many thanks!
Oliver

**Comment by dbaeumer** [comment] 2018-01-18 11:09
The task framework reports the errors when `files` switch between compilation. So when a error is detected for file A and the for file B the once for A are reported. If there is only errors in A then they are reported at the end. Error cleaning happens at the end as well.

**Comment by oliveroxtoby** [comment] 2018-01-18 12:38
OK, thanks. It would really be cool if the errors could be added to the problems panel as they are encountered. In my case gcc can be busy on one file (spewing out pages of errors) for many minutes.

**Comment by oliveroxtoby** [comment] 2018-01-19 09:57
That would be perfect. I suspect many people compiling complex projects in C++ are in the same situation - often, the first error will be output within a few seconds of starting the build, but this will trigger a cascade of compiler output which will go on for minutes. Usually, all you need to know about is that first error, so it would really improve the user experience to get faster feedback into the problems panel. Thank you!

**Comment by alexr00** [comment] 2018-12-21 14:17
Duplicate of #25875

**Closed** 2018-12-21 14:17 UTC
Labels: *duplicate, feature-request, tasks
