### ISSUE TITLE
The color of this area and the left and right sides are not coordinated. Please refer to VisualStudio2017 for improvement!

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#85516] opened 2019-11-25 04:03 UTC
![blue THeme](https://user-images.githubusercontent.com/27546390/69511548-8382c180-0f7b-11ea-884f-a5e28792e5a1.png)
Issue Type: <b>Bug</b>

The color of this area and the left and right sides are not coordinated. Please refer to VisualStudio2017 for improvement!

Extension version: 0.0.1
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (6.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by egamma** [comment] 2019-11-25 10:16
Duplicate of #85515

**Closed by egamma** 2019-11-25 10:16 UTC
