### ISSUE TITLE
Allow users to enable/disable extensions via .code-workspace files

### ISSUE THREAD

**Issue by Enteleform** [Microsoft/vscode#65081] opened 2018-12-14 12:23 UTC
## Issue

Currently, users can enable or disable extensions globally or per-workspace via a context menu command in the `Extensions` pane. This functionality is great, but it is currently not very efficient to configure workspaces that have multiple enabled/disabled extensions.

For example, I recently disabled all of my language-specific extensions. Doing so greatly improved the startup speed of VSCode, but in this case users will have to [`right click`, `click 'Enable (Workspace)'`] for each of the relevant extensions every time a new workspace is created. This approach creates unnecessary repetitive work for users, and is prone to user-error (*forgetting that some ambiguously named extension is required for a certain type of project, accidentally clicking an adjacent extension, etc.*).

## Proposal

Implement something along the lines of the following settings in `.code-workspace` files:

```json
{
  "settings": {
    "extensions.enable": [
      "some-extension",
    ],
    "extensions.disable": [
      "some-other-extension",
    ],
  }
}
```

This would allow users to set up their own templates that allow quick customization of workspaces for their common project-specific needs.

Several users already mentioned this in #15611, but @sandy081 mentioned that the enabled/disabled extensions are currently stored in a local storage cache when he resolved the primary issue, so I decided to create a separate issue for this alternative implementation.

**Comment by sandy081** [comment] 2018-12-16 19:44
Duplicate of #40239

**Closed** 2018-12-16 19:44 UTC
Labels: *duplicate, extensions
