### ISSUE TITLE
Fail to create terminal for task

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#70557] opened 2019-03-15 11:12 UTC
Issue Type: <b>Bug</b>

When running (launching) a task the error message "Fail to create terminal for task <task name>" is shown. Fixed by reloading the window. I'm not sure what starts this failure, but once started all tasks will fail until the window is reloaded.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (22.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|3.0.2
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.5.1
matlab|Gim|0.9.0
triggertaskonsave|Gru|0.2.7
vscode-dimmer|hoo|2.1.0
string-manipulation|mar|0.3.1
select-part-of-word|mle|1.0.1
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1326
indent-rainbow|ode|7.3.0
vscode-clearcase|Ope|2.1.0
vscode-icons|rob|8.2.0
vscode-header-source|ryz|1.3.0
code-settings-sync|Sha|3.2.7
indenticator|Sir|0.6.0
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
sensitive-replace|vil|0.1.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(3 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2019-03-18 09:16
Not sure what cuases this as it always goes away when I try to debug it. Should be fixed in insiders by 93c77d52866005c18751df58082b88aa09eacbb4

**Comment by roblourens** [comment] 2019-03-27 21:51
Maybe #71311 is a dupe of this?

**Closed** 2019-03-27 21:52 UTC
Labels: bug, tasks

**Comment by alexr00** [comment] 2019-03-28 10:43
Can't be verified until b5f5db3 is in a build.

**Comment by BillDenton** [comment] 2019-04-01 11:25
When will this get released? I'm getting this every few minutes as run tasks.

**Comment by alexr00** [comment] 2019-04-03 08:25
It will be part of the next release, which will likely happen this week.
