### ISSUE TITLE
Version Control: Git submodule tree view

### ISSUE THREAD

**Issue by Awbmilne** [microsoft/vscode#101859] opened 2020-07-07 15:36 UTC
I do a lot of work with repositories and submodules.
The biggest issue I come across is when using the same submodule in multiple repos of a multi-root workspace.

All the submodules show up in a plain list with just the name. This makes it hard to distinguish which repo each submodule belongs to:
```
Folder Structure:
├┬ Repo_A
│└─┬ Sub_A
│  └ Sub_B
├┬ Repo_B
│└─┬─ Sub_A
│  ├─ Sub_B
│  └┬ Sub_C
│   └─── Sub_Sub_A

Git Source Control Providers:
- Repo_A
- Sub_b
- Sub_b
- Sub_C
- Sub_A
- Repo_B
- Sub_Sub_A
- Sub_A
```

**It would be amazingly convenient if there was a tree view like the Explorer.**
**This would make working with nested and numerous submodules a breeze.**

_(Yes, I know I could do it with the command line, and for commits/merges I do. But the changes view is really nice for keeping track of whats going on)_

**Comment by ArturoDent** [comment] 2020-07-07 22:02
There is a tree view for scm view.  See https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_47.md#view--sort

**Comment by Awbmilne** [comment] 2020-07-08 14:31
@ArturoDent 
The [changes mention](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_47.md#view--sort) are for the changes section, not the actual repo list.

I have the changes setup in tree view, but the repos and submodules are still a plain list.

**Comment by Awbmilne** [comment] 2020-07-08 14:52
Another thing I have recently noticed:

When checking out submodules to specific versions (tags), some submodules show the tag name and some show the commit hash:
![image](https://user-images.githubusercontent.com/50780746/86933584-b04da880-c108-11ea-89f5-28c2ce866daa.png)

<b />

Im sure everyone has their preference, but it seems like showing the tag name when a repo is checked out with "HEAD detached" would be the most informative format. Falling back on the commit hash when there is no tag present at that commit.

**Comment by joaomoreno** [comment] 2020-07-12 14:45
The source control providers view is now gone, so this feature becomes harder to implement.

**Comment by NotWearingPants** [comment] 2020-07-17 20:35
Duplicate of #43951

**Closed** 2020-09-11 02:26 UTC
Labels: feature-request, scm
