### ISSUE TITLE
Intellisense inside JS template literal not showing automatically after typing ${

### ISSUE THREAD

**Issue by theGivingTree** [Microsoft/vscode#32954] opened 2017-08-22 12:07 UTC
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

While typing inside the string interpolation, e.g.`${foo}`, Intellisense popup for the variable is not shown.

Intellisense regarding the variable's property works perfectly though.
But, It's the variable name that popup doesn't open when typing.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-22 18:47
I think we just don't automatically trigger intellisense in this case. If you use the `editor.action.triggerSuggest` keybinding (ctrl+space on mac)  after the `{` do you see the proper intellisense?

**Comment by theGivingTree** [comment] 2017-08-23 10:28
Yes, I see.
You mean that's intended operation?

**Comment by mjbvz** [comment] 2017-08-23 17:30
Glad the workaround works.

This is a bug though. I'm going to change the title of this issue to make the root cause of problem more clear

**Comment by mjbvz** [comment] 2017-10-16 21:51
After thinking over this further, I don't believe we should automatically show suggestions when you type `${`. Instead my proposal is that we show suggestions once you start typing the next character, such as `${a`. This is how quick suggestions work normally in JS.

The reason for this is that the template substitution may contain any expression, and automatically showing suggestions on `${` will make it more annoying to enter expressions such as `${123}` or `${[a]}`.


Closing this as a duplicate of  https://github.com/Microsoft/vscode/issues/34857, which tracks showing quick suggestions on cases such as `${a`

**Closed by mjbvz** 2017-10-16 21:51 UTC
Labels: bug, duplicate, javascript
