### ISSUE TITLE
Debug console recognizes DateTime as URL

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#11560] opened 2016-09-06 03:39 UTC
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. Write a simple app in any language (I use C# with .NET Core) that writes current date time to console like `[9/6/16 11:33:45 AM]`
2. In Debug Console, part of the date time will be recognized as a URL.
3. Click the URL and it says `Unable to open '16 11': File not found (/6/16 11).`

This is not a big deal but can be nice to get fixed.

**Comment by isidorn** [comment] 2016-09-06 08:27
```
console.log('[9/6/16 11:33:45 AM]');
debugger;
```

Link detection fails.
@bpasero can we improve our link detection algorithm? Maybe some code pointers, do we have unit tests?

**Comment by bpasero** [comment] 2016-09-06 09:00
@isidorn see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputWorker.ts#L69 and yes there are tests in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/test/outputWorker.test.ts#L1

**Comment by isidorn** [comment] 2016-11-10 16:30
fyi @felixfbecker maybe your polished regex could also take care of this corner case :)

**Comment by willmurphyscode** [comment] 2017-03-21 13:19
<img width="270" alt="match_left_paren_dot" src="https://cloud.githubusercontent.com/assets/12529630/24148914/21547f84-0e17-11e7-8560-2c6ff4172644.png">

In the editor, it looks like `).` is matching the URL regex as well. It's not evident from the screenshot, but VS Code is offering to open this `).` as a link.  (I'm not sure whether this is the same regex or the same issue, but I didn't want to open a duplicate issue without checking here first.) 

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quick-open|leizongmin|1.0.0|
|Ruby|rebornix|0.10.4|
|cucumber|stevejpurves|0.9.6|;

**Comment by isidorn** [comment] 2017-04-13 09:00
Assigning to @michelkaporin to investigate

**Comment by michelkaporin** [comment] 2017-05-08 10:52
This should be fixed in #24451.

@willmurphyscode create a separate bug for it with the steps to reproduce (I couldn't reproduce you example), because the link handling in editor is different from the debug console.

**Closed by michelkaporin** 2017-05-08 10:52 UTC
Labels: debug, debug-console, feature-request
