### ISSUE TITLE
allow selection expansion at multi cursors

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#38224] opened 2017-11-13 13:52 UTC
when there are multicursors selection only expands on the first one:

![multi-cursor-selection-expansion](https://user-images.githubusercontent.com/937933/32728880-07f951ec-c850-11e7-9ac9-45a3b9047333.gif)

**Comment by roblourens** [comment] 2017-11-13 18:51
Duplicate of https://github.com/Microsoft/vscode/issues/4795

**Closed by roblourens** 2017-11-13 18:51 UTC
Labels: editor, editor-multicursor
