### ISSUE TITLE
'About Visual Studio Code' window can't be closed with ⌘W

### ISSUE THREAD

**Issue by NiklasBr** [Microsoft/vscode#26361] opened 2017-05-10 08:11 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-dash|deerawan|1.5.0|
|php-intellisense|felixfbecker|1.2.1|
|VS-code-drupal|marcostazi|0.0.12|;

---
This is a super-tiny issue, barely worth reporting… :)

Steps to Reproduce:

1. With the MacOS version of vscode, open the menu item "Code" and select "About Visual Studio Code" 
2. Try to close the window using ⌘W, you can't.

**Comment by wangweixuan** [comment] 2017-05-13 06:09
Is this a duplicate of #25907?

**Comment by NiklasBr** [comment] 2017-05-15 08:18
@wangweixuan I think it might be.

**Closed** 2017-05-20 06:06 UTC
Labels: help wanted, upstream
