### ISSUE TITLE
Git changes not showing in file editor

### ISSUE THREAD

**Issue by cquick01** [microsoft/vscode#212915] opened 2024-05-16 16:48 UTC
Type: <b>Bug</b>

Lines that have been modified according to Git are not showing up highlighted in the editor like normal. Usually there is a color near the line numbers showing lines that have changed (green added, red deleted, blue modified), along with similar colors near the scroll bar.

It happens with all of my repos, but also with creating an empty test repo. All extensions are disabled.

Usually we see something like this

![image](https://github.com/microsoft/vscode/assets/72400253/a82a9bc3-fb15-4a56-9273-7762c0651ec5)

1. Open new empty directory in VSCode
2. Initialize git repo, either with cli or through the Source Control panel
4. Create some empty file, add and commit with git
![Screenshot 2024-05-16 123938](https://github.com/microsoft/vscode/assets/72400253/8ed9be3e-7ce9-4902-91de-c36233e1981d)
6. Modify and save the file
![Screenshot 2024-05-16 124004](https://github.com/microsoft/vscode/assets/72400253/d431221b-fc57-4bfd-a72f-3053675bf3dc)
8. See that the file shows as modified in the file explorer, but there is no indication of modified lines in the editor, only in the actual diff explorer
![Screenshot 2024-05-16 124028](https://github.com/microsoft/vscode/assets/72400253/111e27b6-3ac9-478c-beb2-5965f401a4ec)

VS Code version: Code - Insiders 1.90.0-insider (0cd8d6ac480bc5b4e2a2d7f1eb87eaff9f7d47e1, 2024-05-16T05:49:53.998Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|11.68GB (10.23GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.88.2

</details>

**Comment by fai8146767** [comment] 2024-05-17 12:15
****

**Comment by ssalbdivad** [comment] 2024-05-18 17:09
I've been having the same issue on WSL for the last few days. Tried disabling all extensions etc. so it seems like a regression in VSCode?

@lszomoru Would be great to get some eyes on this. I'm constantly confused about why the files I'm working on don't look modified until I remember this.

**Comment by ovidiuc** [comment] 2024-05-22 13:53
Duplicates https://github.com/microsoft/vscode/issues/212857 , where you can see more people complaining about the problem.

**Comment by lszomoru** [comment] 2024-05-29 13:51
Closing as duplicate of https://github.com/microsoft/vscode/issues/212857

**Closed by lszomoru** 2024-05-29 13:51 UTC

**Comment by fai8146767** [comment] 2024-05-31 16:13
****
