### ISSUE TITLE
webpack command works in Terminal but doesn't work in task run.

### ISSUE THREAD

**Issue by rickyteng** [Microsoft/vscode#19012] opened 2017-01-23 03:06 UTC
webpack command works in Terminal but doesn't work in task run.

- VSCode Version:
- OS Version: windows server 2012

I run "node_modules\\.bin\\webpack.cmd" by task runner, I get the result:

```
running command> node_modules\.bin\webpack.cmd 
Hash: f0b84287dadbc64086ce
Version: webpack 1.14.0
Time: 90ms
           Asset       Size  Chunks             Chunk Names
         main.js    2.02 kB          [emitted]  
      index.html  495 bytes          [emitted]  
    package.json  456 bytes          [emitted]  
    lib/react.js     128 kB          [emitted]  
lib/react-dom.js     620 kB          [emitted]  
   [0] ./src/renderer.js 0 bytes [built] [failed]
WARNING in NODE_ENV environment variable is undefined.
ERROR in ./src/renderer.js
Module parse failed: c:\x\electron_project\electron-react-webpack-test\src\renderer.js Unexpected token (48:12)
```
I run "node_modules\\.bin\\webpack.cmd" by Terminal in vscode, 

```
C:\x\electron_project\electron-react-webpack-test>node_modules\\.bin\\webp
ack.cmd
Hash: de6c1c06fa2413d3a39d
Version: webpack 1.14.0

Time: 1327ms
           Asset       Size  Chunks             Chunk Names
     renderer.js     172 kB       0  [emitted]  renderer
    renderer.map     205 kB       0  [emitted]  renderer
         main.js    2.02 kB          [emitted]
      index.html  495 bytes          [emitted]
    package.json  456 bytes          [emitted]
    lib/react.js     128 kB          [emitted]
lib/react-dom.js     620 kB          [emitted]
    + 62 hidden modules

WARNING in NODE_ENV environment variable is undefined.
```

Steps to Reproduce:

I prepare my code and config in github, just clone it.

1. git clone https://github.com/rickyteng/electron-react-webpack-test.git
2. npm install
3. open vscode
4. press F1, select "Tasks : run task", then "node_modules\\.bin\\webpack.cmd"

note: all modules installed locally.

**Comment by dbaeumer** [comment] 2017-01-25 16:56
I can't reproduce this. See screen cast:

![cast](https://cloud.githubusercontent.com/assets/1931590/22300384/941fc34a-e327-11e6-9631-1b6b41b01ad4.gif)

Any additional steps / info you can provide.

**Comment by dbaeumer** [comment] 2017-02-09 11:47
Closing. Will reopen when additional information is available.

**Closed by dbaeumer** 2017-02-09 11:47 UTC
Labels: needs more info, tasks

**Comment by G-P-Git** [comment] 2017-02-27 18:00
Came here from Google.  It shows the error warning right at the bottom of your animation @dbaeumer .

**Comment by rickyteng** [comment] 2017-03-13 07:06
@dbaeumer Thanks your time. I updated to vscode 1.10.1. I have no this problem.
