### ISSUE TITLE
Intellisense for node modules and local imports appears to be broken in v1.11.1

### ISSUE THREAD

**Issue by leosco** [Microsoft/vscode#24121] opened 2017-04-06 18:34 UTC
On previous releases, typing `import assert from 'asse` would autocomplete to `assert`, and the same would apply to local imports such as `import myFunc from './myFunc'`.

Now, on v1.11.1 I've noticed that's stopped working.

**Comment by mjbvz** [comment] 2017-04-06 18:59
Duplicate of #23962

You still should be able to manually trigger the suggestions using the keyboard shortcut. Also see my explanation how to enable quick suggestions in strings to match the 1.10 behavior: https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416

**Closed by mjbvz** 2017-04-06 18:59 UTC
Labels: duplicate

**Comment by leosco** [comment] 2017-04-06 20:26
Thanks for the quick response! Sorry, I didn't notice the duplicate issue :)
