### ISSUE TITLE
What's up with Tabs being under review? seriously...

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#3503] opened 2016-02-26 15:30 UTC
It has like 5.4k votes on [uservoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752519-implement-tabs?tracking_code=421857240f4fcb6135eadecade77a4e2), it's unfortunate that an issue of _taste_ or style needs to be reviewed, it's like reviewing an issue about accessibility and debate whether it needs to be added to a modern program where the answer is definitely yes.

I _think_ that the majority of developers either like it or just too used to it and some don't, that's fine too so why wouldn't you consider adding this as an option? many people that really likes the editor shy away from using it because an editor shouldn't force you into anything you don't like and the working files isn't working for many people.

Now, I can certainly use other editors instead of VSCode and I do but when I'm working with TypeScript/JavaScript I really like to use VSCode and it really bothers me that it doesn't have tabs.

I'm working with different languages and use many editors/IDEs in my work and all of them have tabs, it fits my workflow best because I've been using Visual Studio and IntelliJ to develop software for a very long time and it's just a thing for me and I guess for many others too.

What's interesting is that Visual Studio Code carries the title Visual Studio that not only has tabs but it's part of the experience in the IDE so a developer that uses VSCode should expect no less but to have tabs as part of the same _editing_ experience.

Please, at least tell us what's going on with it, where it stands, etc... 

Thanks.

**Comment by gedw99** [comment] 2016-02-26 15:53
I have to admit, the default way with the 3 sheets limit and working files list (top left) was ok with me for about 2 months. But for larger projects, i need a better way.

Tabs is the standard paradigm to solve this problem. I cant think of a better way.

**Comment by 4tron** [comment] 2016-02-27 08:52
Excuse me for being objective to this idea, but i see no advantage of tabs. The reason they left it out was for a cleaner workspace. In the latest release they have gone so far as to remove the options bar by pressing "alt" . I understand this is a paradigm in most other editors, but it seems verbose . There are multiply ways in which to view working files. The obvious one is the "working files" in explorer , ctrl + tab, or just F1 and then type the file name you are looking for. There is also the idea of working with windows side by side which can be resized and activated to the larger size when in focus, like an accordion. add "ctrl + b" to remove explorer and you have a tidy workspace.

I see no benefit from tabs, i think is encourages newbies to use their mouse instead of the keyboard shortcuts to navigate around files. If the issue is with seeing the working files the "ctrl + tab" option is a lot cleaner with a view of more files and meta data of the files, which in larger projects is actually really helpful. as apposed to just a filename in the case of tabs.

**Comment by eyalsk** [comment] 2016-02-27 10:29
@4tron 

> Excuse me for being objective to this idea, but i see no advantage of tabs. The reason they left it out was for a cleaner workspace. In the latest release they have gone so far as to remove the top options bar by pressing alt . I understand this is a paradigm in most other editors, but it seems verbose . There are multiply ways in which to view working files. The obvious one is the "working files" in explorer , ctrl + tab, or just F1 and then type the file name you are looking for. There is also the idea of working with windows side by side which can be resized and activated to the larger size when in focus, like an accordion, this also allows for a ctrl + tab on each of the 3 windows with each window displaying a different list based on its history. Add ctrl + b to remove explorer and you have a tidy workspace.

Well, I disagree because the working files isn't mutually exclusive, meaning, it can coexists with tabs.

The reason they left it out doesn't matter so much because I don't think that a _cleaner_ workspace is more important than the style many developers were accustomed to for many years.

I completely respect your position and understand why would it seems verbose but _verbosity_ isn't a bad thing! certainly not in this case where for many developers it's part of their workflow.

> I see no benefit from tabs, i think is encourages newbies to use their mouse instead of the keyboard shortcuts to navigate around files. If the issue is with seeing the working files the ctrl + tab option is a lot cleaner with a view of more files and meta data of the files, which in larger projects is actually really helpful. as apposed to just a filename in the case of tabs. 

I'm a keyboard kinda guy and ctrl+tab or holding ctrl in Visual Studio allows me to jump between files quickly or even to move between windows inside the IDE.

I don't need an editor to educate me about productivity and newbies will use their mouse whether it's to jump between working files or click/select something in an editor or whatever, not everyone are keyboard oriented and if that makes some people happy! this should be acceptable workflow, even though I fully understand the mouse vs keyboard argument but again it shouldn't be the editor's job to tell you how to work and if anything it can prevent newbies from using it.

>  From the uservoice this option is under review, but i think personally, someone should build an extension if they want this. I think vscode is trying to be as light weight as possible with the user choosing his/her extensions to meet his/her coding style.

Unfortunately it's not really possible to make an extension for tabs, not everything is extensible within VSCode.

The lightweight argument is a bit silly because it won't bloat the editor but some people use it without even understanding what it means but whatever...

> applications will always be opinionated, every editor is. I think vscode is really trying to endorse a strong extension library with which it becomes the developers who choose where they want the editor to go.

Again, I don't know how much you read about the program's architecture but it's not possible to extend the UI without having the extensibility point to do it!

To really make it work you need to fork it and modify the UI because you can't really make an extension for it.

**Comment by 4tron** [comment] 2016-02-27 15:27
> Again, I don't know how much you read about the program's architecture but it's not possible to extend the UI because there's no extensibility point available to do it!  

. VScode is still in beta .. im pretty sure they are making plans for vast user extensibility.

> I'm a keyboard kinda guy and ctrl+tab or holding ctrl in Visual Studio allows me to jump between files quickly or even to move between windows inside the IDE.

So whats the main problem here? What exactly is the advantage of tabs in this so called workflow? You can have 9 tabs open that will show you their filename and maybe their state, or you can `ctrl + tab` and you have all that info there with meta data ? What is this "workflow" you speak of?

**Comment by TheColorRed** [comment] 2016-02-27 16:42
I don't see any advantage of having the tabs horizontally laid out instead of vertically laid out.

With the way it is set up, you have a little more vertical typing space anyway.

**Comment by eyalsk** [comment] 2016-02-27 16:46
> . VScode is still in beta .. im pretty sure they are making plans for vast user extensibility.

RTM is coming soon and I didn't see anything like this on their [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) so I really don't know where you get the idea that they are making _plans_ to extend their extensibility story.

> 
So whats the main problem here? What exactly is the advantage of tabs in this so called workflow? You can have 9 tabs open that will show you their filename and maybe their state, or you can ctrl + tab and you have all that info there with meta data ? What is this "workflow" you speak of?

Okay, so just to state the obvious here, tabs provide horizontal display over vertical display and many people find it more convenient because it simply exists everywhere, in almost every program.

Now, when you are used to look at information in one way and someone change it then you can't always adapt so you have two clear choices here drop the program or voice your opinion about it.

If you don't like tabs that's fine, that's how you like your cup of tea but it's not everyone's cup of tea.

**Comment by 4tron** [comment] 2016-02-28 07:49
I just dont understand , you get more information for your eyes (O.O) how is this not an advantageous step forward. As for it "simply exists everywhere " besides that being false, it does not mean its the best approach, and i like it when people think differently. Sometimes the best place to be is outside your comfort zone.

The extensibility might not be in the RTM but if visual studio is anything to go by we will probably be able to make our own isolated shells of the thing in future versions

**Comment by eyalsk** [comment] 2016-02-28 08:42
@4tron okay, listen, some people can adapt regardless to whether they are used to something but many people can't, just because you can do it, doesn't mean everyone can do it or even want to do it.

Anyhow, I'd argue that more information isn't necessarily an advantage over less information, with working files you have everything shown to you at once, sometimes you have to look through to remember what files you opened, with tabs you have limited horizontal space where you have to choose what files you want to be in that space and because the files are at the top, always in front of your eyes it allows some people to get this nice focus over files.

There's no right and wrong here! it's not like tabs are evil or bad it's just something people prefer it over working files and vice versa.

If the discussion was about people being lazy then I'd agree with you that sometimes the best place to be is outside your comfort zone but fortunately, this is a matter of style and it's not the case.

> The extensibility might not be in the RTM but if visual studio is anything to go by we will probably be able to make our own isolated shells of the thing in future versions

I don't know about that, I don't assume anything because I don't think they said anything about it, I mean I if only they gave us the ability to extend the UI I wouldn't be here writing this post, instead I'd probably wrote a plugin for it.

Isolated shells is nice and it can _definitely_ solve the problem but I'd argue that it's like killing a fly with a sledgehammer and it can have some weird consequences especially with things like themes.

**Comment by vilic** [comment] 2016-03-01 03:57
I used to use tabs when I use Visual Studio, but now I absolutely prefer code navigation with keyboard. `Ctrl+E` type the file name, `Ctrl+E` to select target file and go. I don't need to remember where the tab is any more.

While I support your voting for this feature, I strongly suggest you trying to adapt keyboard navigation that makes my life easier.

**Comment by joaomoreno** [comment] 2016-03-01 08:13
Closing as duplicate of #224. Please continue the discussion there.

My personal opinion: there is nothing more tabs provide me than what <kbd>Ctrl E</kbd> already does. Oh, besides the pain of having to look for *where the hell that tab is* once I have more than 6 open.

cc/ @chrisdias @waderyan @seanmcbreen

**Closed by joaomoreno** 2016-03-01 08:14 UTC
