### ISSUE TITLE
Breakpoints not hit when attaching to a language server

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#16143] opened 2016-11-28 12:00 UTC
This has worked in the past but no longer works.

Here are the steps to reproduce the setup:
- `git clone git@github.com:Microsoft/vscode-tslint.git`
- open a Code instance on both the folder `tslint` and `tslint-server` 
- run `npm install` in both the `tslint` and the `tslint-server` folder
- **new** in the `tslint-server` run `npm run compile`
- in  `tslint-server` open `src/server.ts` and set a breakpoint in `#doValidate`
- in `tslint` press F5 to start a debug session
- in the extension development host open the folder `vscode-tslint/tslint-test` and then the file `arrow-parens.ts` see the screenshot below for the setup.
- you will see a tslint warning/green squiggle on line 1. This shows that the tslint-server is running
- switch to the `tslint-server` window and press F5 to attach to the server. Attaching to the server is successful. 
- switch to the extension development host and make an edit in `arrow-parens.ts`. This should trigger `doValidate` in the server and hit the break point.

=> the break point is not hit.

When I replace the breakpoint with a `debugger;` statement and recompile the server, then the debugger stops as expected. This shows that attaching to the server process is successful.

So I suspect an issue with source maps or the way the launch is configured for the server.
This is the launch.json for the server:
```json
{
	"version": "0.1.0",
	// List of configurations. Add new configurations or edit existing ones.
	"configurations": [
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			// TCP/IP address. Default is "localhost".
			"address": "localhost",
			// Port to attach to.
			"port": 6004,
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/../tslint/server"
		}
	]
}
```

Notice that as part of the build process the *.js files and the source maps from the server folder are copied into the `vscode-tslint/tslint/server` folder. 

The path to the sources in the sourcemap `server.js.map` looks OK:
```json
{"version":3,"file":"server.js","sourceRoot":"","sources":["../../tslint-server/src/server.ts"],
```

// CC @dbaeumer 

## Test setup
![image](https://cloud.githubusercontent.com/assets/172399/20667303/d93e501e-b568-11e6-8421-a67cd9c5e0b2.png)

**Comment by weinand** [comment] 2016-11-29 11:06
@egamma starting tslint with F5 opens an extension host window but immediately results in this error message:
![2016-11-29_12-02-13](https://cloud.githubusercontent.com/assets/1898161/20707460/d1146e3c-b62b-11e6-9886-028b41d88f5b.png)

You said: 
> Notice that as part of the build process the *.js files and the source maps from the server folder are copied into the vscode-tslint/tslint/server folder.

I don't have a folder `vscode-tslint/tslint/server`:

![2016-11-29_12-05-24](https://cloud.githubusercontent.com/assets/1898161/20707544/2b6e323c-b62c-11e6-9b38-17a771173074.png)

**Comment by egamma** [comment] 2016-11-29 13:05
@weinand sorry I forgot a step. you have to run `npm run compile` in the server folder. This compiles the server and copies into the tslint/server folder. Sorry forgot this step.

**Comment by weinand** [comment] 2016-11-29 14:42
@egamma aha, I'd tried `npm run compile` but in the wrong directory...
Some 'prelaunchtask' for the launch config would have helped here (we do not have these setup issues  in debug adapters although they have a similar two process structure).

In addition I had to `npm install tslint` in the tslints-tests folder before everything started to work.

And I was hitting the breakpoint without problem.
But this is on macOS, so I will try the same on Windows....

**Comment by weinand** [comment] 2016-11-29 15:50
I can reproduce on Windows. Problem is a '..' in a path.

**Comment by siegebell** [comment] 2016-11-29 16:17
This has been a **huge** headache for me for the last month or two, but I haven't had the time to minimize the problem into a bug report :(
(Windows 8.1, vscode 1.6 - 1.7.2)

@weinand which languageserver version are you using? 3.0.0-alpha.*x* complains with *"Couldn't check launch.json file. Reading the file failed with: Path must be a string. Received undefined"* if you use "outFiles" instead of "outDir". So I've got both "outFiles" and "outDir" in launch.json :/

**Comment by weinand** [comment] 2016-11-29 16:29
@siegebell I don't quite understand your question about the languageserver version.
"outFiles" is a [new attribute](https://code.visualstudio.com/updates/v1_6#_glob-pattern-support-for-source-map-setup) of the VS Code builtin node-debugger. It was introduced in VS Code 1.6 (September). outFiles takes an array of glob patterns instead of a single directory path.
If you are using VS Code >= 1.6 just replace an outDir path by the corresponding outFiles array.

**Comment by siegebell** [comment] 2016-11-29 16:53
@weinand I asked what version you're using to see if vscode-languageserver is also reporting an error for you when you replace "outDir" with "outFiles" -- for version 3 (up to 3.0.1-alpha.3).

**Comment by weinand** [comment] 2016-11-29 17:07
@siegebell the "vscode-languageserver" cannot "report errors". VS Code might report errors for the project "vscode-languageserver" if it chokes on unknown attributes in the launch.json. This depends on the version of VS Code that you are using.

**Comment by siegebell** [comment] 2016-11-29 17:36
@weinand `installServerIntoExtension` is a component of vscode-languageserver, hence vscode-languageserver is reporting an error.

With "outDir", compilation is fine:
![no-error](https://cloud.githubusercontent.com/assets/16118166/20721062/887e13fe-b62f-11e6-853e-0c47c495fe33.png)

*Without* "outDir", an error is reported:
![error](https://cloud.githubusercontent.com/assets/16118166/20721084/9b70c2a4-b62f-11e6-9741-12596efbdd41.png)

If you can reproduce this behavior, then I'll go on over to https://github.com/Microsoft/vscode-languageserver-node/issues and report the issue. Until the issue is resolved, "outDir" is effectively not deprecated.

**Comment by weinand** [comment] 2016-11-29 18:01
@siegebell thanks for letting me know about this brittle and undocumented dependency.
I've filed an issue against the languageserver.

**Comment by weinand** [comment] 2016-11-30 11:36
fixed by https://github.com/Microsoft/vscode-node-debug/commit/3492983ce23b3c31d1671d5376a29ee24e085802

**Closed** 2016-11-30 11:36 UTC
Labels: bug, debug
