### ISSUE TITLE
Custom Editor Tab Becomes Unresponsive

### ISSUE THREAD

**Issue by jonnyhork** [microsoft/vscode#112100] opened 2020-12-08 17:15 UTC
Version: 1.52.0-insider
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:22:59.162Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Darwin x64 18.7.0

We are using the custom editor API for our extension and customers are reporting confusion when attempting to view a document with text editor and the visual custom editor at the same time. I am not sure if this is a bug or intended behavior but at the very least it is confusing to have two tabs open in one panel where one is unresponsive.

Steps to Reproduce:

1. Open a document with the custom editor
2. Use the right-click menu to reopen editor with the text editor
3. A new tab opens up with the text editor
4. Click on the first tab, the custom editor instance, then try to go back to the text editor.
5. The second tab becomes unresponsive

![Unable to go back to text editor](https://user-images.githubusercontent.com/25188632/101516775-2024c100-393d-11eb-98d6-9539c9e55a16.gif)

In this case, if you click on the newly opened text editor tab, first then the custom editor is displayed.
![Click on Text editor, get custom editor](https://user-images.githubusercontent.com/25188632/101517583-249da980-393e-11eb-9ed2-c812a39f4c44.gif)

Does this issue occur when all extensions are disabled?: The issue is with an extension API

**Comment by mjbvz** [comment] 2020-12-18 05:05
Duplicate of #111474

**Closed by mjbvz** 2020-12-18 05:05 UTC
