### ISSUE TITLE
Markdown Preview - HTML Anchor Tag Links don't scroll within document

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/vscode#215455] opened 2024-06-13 17:06 UTC
Type: <b>Bug</b>

If you create a link in Markdown like `[Important Changes](#changes)` and then add a header elsewhere in the document like so:

`## <a name="changes"></a> Important Changes`

Using the raw HTML anchor tag directly.

Then when clicking on that link in the Markdown Previewer, it won't scroll the document to that anchor tag as I would expect.

We use this header system for our blog staging before translating to WordPress, so it'd be nice to ensure we can test/see them working ahead of time as we stage in VS Code.

Related older issue: https://github.com/microsoft/vscode/issues/201634

However, the old issue was about a specific markdown extension syntax for anchor support. This is about just using HTML tags directly which is part of the standard Markdown spec: https://spec.commonmark.org/0.30/#html-block (though it excludes the anchor tag, I haven't seen any Markdown processor that requires that, and kind of seems contradicted by the spec in Example 344, though may be included under section 6.6 for Raw HTML).

Here's a CommonMark Playground Test which directly shows the desired behavior: https://spec.commonmark.org/dingus/?text=This%20is%20some%20text%2C%20%5Bclick%20here%5D(%23testanchor)%20to%20go%20below.%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0A%23%23%20%3Ca%20name%3D%22testanchor%22%3E%3C%2Fa%3E%20Header%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...%0A%0AFiller...

![image](https://github.com/microsoft/vscode/assets/24302614/2c3c37b8-376d-46b8-b174-f775fa9f2aed)

If you click on the 'click here' link, you'll see the view jump the Header to the top:

![image](https://github.com/microsoft/vscode/assets/24302614/fa3727c8-cf0c-4424-ae58-4806afd26c44)

In contrast in the VS Code Markdown Previewer, nothing happens if you click on the link:

![image](https://github.com/microsoft/vscode/assets/24302614/b169e435-a1a5-4b3c-8a13-f3c9dc7adc10)

I would expect the view to instead scroll to the start of the Header like so:

![image](https://github.com/microsoft/vscode/assets/24302614/47b3b23f-a438-4372-8902-22b99cad1437)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (39.60GB free)|
|Process Argv|--crash-reporter-id f3424e4a-3289-4d11-b089-58e06a3261d2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-diff|fab|2.1.2
git-graph|mhu|1.30.0
partial-diff|ryu|1.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by mjbvz** [comment] 2024-06-13 21:28
Duplicate of #139852

You should use the `id` attribute instead. AFAIK name is deprecated for this usage

**Closed by mjbvz** 2024-06-13 21:28 UTC
