### ISSUE TITLE
Debug toolbar draggable in the 4 edges of the VS Code screen.

### ISSUE THREAD

**Issue by FeliceGeracitano** [Microsoft/vscode#18399] opened 2017-01-11 12:07 UTC
Feature Request

The debug toolbar that appear when the a process is running, often (in my opinion) is in the wrong place and cover tabs/refresh buttons/console buttons. 
I'd like to drag this toolbar in a custom edge of the editor like in the bottom.

**Comment by mjbvz** [comment] 2017-01-11 19:21
This looks like a duplicate of #9093

Let me know if that is not the case

**Closed by mjbvz** 2017-01-11 19:21 UTC
Labels: debug, feature-request, ux

**Comment by FeliceGeracitano** [comment] 2017-01-12 11:04
@mjbvz it is. Thanks very much
