### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by Neohiro79** [Microsoft/vscode#50266] opened 2018-05-22 08:14 UTC
Issue Type: <b>Feature Request</b>

## Possibility of maybe having the option of PRINTING something from within VSC.

Just don't tell me that you have not thought of the possible option of having the need of PRINTING SOMETHING OUT (ie. Code, ie. .md-Files, whatever).

Just don't tell me that "similar problems" beeing listed while I was typing all this meantioned to be CLOSED - in fact ARE NOT CLOSED - since I cannot found the magic "print" button anywhere within the VSC interface at all. I might be looking at the wrong place, maybe it's hidden somewhere under **help > devtools > superprintingoption** or I need to type in some magic lines into the console?

Just don't tell me that the magical microsoft superior development team who really did an awesome great job while developing VSC at all - had NO INTENSION or NO THOUGHT AT ALL of any thinkable situation, in which someone might need the "printing" option anywhere within the VSC environment.

Just don't  tell me that a request like that is at all neccessary, at least not at version 1.23.

We are able to fly to the moon or elsewhere - but Microsoft is not able to put a fr* f* print-me option inside it's really superior VSC Editor ????

I cannot believe I need to even write those lines.

Awesome guys. Awesome. That's a code editor. Here we go ...

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment] 2018-05-22 08:59
duplicate of #5953

**Closed by weinand** 2018-05-22 08:59 UTC
Labels: editor, feature-request

**Comment by Neohiro79** [comment] 2018-05-22 09:16
Since #5953 is out there since 28 Apr 2016, and since at least my clock tells me 22 Mai 2018,
I pretty much assume, that this "closed" issue is far from beeing closed soon, since it seems 
not possible for microsoft to include this requested feature for about TWO YEARS now.

Is that correct ?

**Comment by weinand** [comment] 2018-05-22 09:53
Since this issue is closed now, please ask questions in #5953.
