### ISSUE TITLE
Editor: Add Git diff margin (Change Markers)

### ISSUE THREAD

**Issue by aspirisen** [Microsoft/vscode#17655] opened 2016-12-21 09:42 UTC
- VSCode Version: 1.8.1
- OS Version: Win 10

There is a good plugin for Visual Studio which is called [GitDiffMargin](https://github.com/laurentkempe/GitDiffMargin). It shows diff by lines in the editor and you can revert particular changes.

### This is how it works in Visual Studio:
This is original code
![image](https://cloud.githubusercontent.com/assets/3620639/21383991/75832bee-c779-11e6-9cfc-97f1d3b84e04.png)

I deleted some code and the red arrow is appeared on the right side of line numbers
![image](https://cloud.githubusercontent.com/assets/3620639/21384030/a3233f6c-c779-11e6-9c6a-9c3490387a88.png)

I can click on the arrow and I will see the deleted code.
![image](https://cloud.githubusercontent.com/assets/3620639/21384062/c89ff762-c779-11e6-809c-5334a28655d8.png)

If I click on `Rollback` button the deleted code will be restored
![image](https://cloud.githubusercontent.com/assets/3620639/21384144/37e6e842-c77a-11e6-9907-050925eb6fc8.png)

I think it is easier rather than copypaste lines in "Changes view"
![image](https://cloud.githubusercontent.com/assets/3620639/21384206/9f75755a-c77a-11e6-8c3e-cc505504ad0f.png)

**Comment by egamma** [comment] 2016-12-21 15:09
FYI @joaomoreno

**Comment by sideeffffect** [comment] 2016-12-23 13:40
IntelliJ IDEA already has something like this, even better, because it has syntax highlighting. They call it [Change Markers](https://www.jetbrains.com/help/idea/2016.3/change-markers.html):

![](https://www.jetbrains.com/help/img/idea/2016.3/changeMarkerToolbar.png)

![](https://www.jetbrains.com/help/img/idea/2016.3/highlight_change.png)

**Comment by tamlyn** [comment] 2017-02-23 16:47
Looks like a duplicate of #10782.

**Comment by joaomoreno** [comment] 2017-02-28 09:39
Yup, it is.

**Closed by joaomoreno** 2017-02-28 09:39 UTC
Labels: feature-request, git

**Comment by vedmant** [comment] 2017-10-01 15:10
Yeah, this is what I'm missing from PHPStorm.
