### ISSUE TITLE
VSCode on Mac cannot login to GitHub with 2FA on

### ISSUE THREAD

**Issue by shaipetel** [Microsoft/vscode#46964] opened 2018-03-29 19:47 UTC
- VSCode Version: 1.21
- OS Version: MacOS

Steps to Reproduce:

1. Open a Github account
2. Enable 2FA where it sends you an SMS to verify login
3. Open a repository on GitHub
4. Clone it locally, make some changes
5. Try to sync your changes - it will fail with wrong user name / password error after prompting you for user name and password.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Possible duplicate of: https://github.com/Microsoft/vscode/issues/490 but this one is for Mac OS. The other issue had workarounds for Windows PC.

**Comment by roblourens** [comment] 2018-04-01 04:20
I believe this is a duplicate of #490, (given that https://github.com/Microsoft/vscode/issues/43257 is))

**Comment by shaipetel** [comment] 2018-04-09 15:24
@roblourens No its not a duplicate. The issue is the same but like I said - this one is specifically for Mac OS.

Why is that significant? Because all the workarounds on the other 2 issues are for windows only.

Since they discuss and accept workarounds for windows, and these have nothing to do with Mac OS - I think there should be a separate issue for Mac OS.

So, you may want to link the issues together but I don't think this is a duplicate since the solution needed or workaround should be different.

**Comment by joaomoreno** [comment] 2018-04-10 14:08
Yeah you can use a personal access token or, even better, SSH keys for GitHub auth. That's what I do.

**Closed by joaomoreno** 2018-04-10 14:08 UTC

**Comment by shaipetel** [comment] 2018-04-10 15:50
Great, thanks. I wonder why this info wan't easy to find at first - ppl just saying its unusable in VSCode on a Mac.

got it though so no problem
