### ISSUE TITLE
[Request] Support for formatting when close bracket is injected by editor.autoClosingBrackets

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#105193] opened 2020-08-21 21:20 UTC
In the C/C++ extension, we now support formatting of a block when a user types `}`.  However, we do not receive a request to our `OnTypeFormattingEditProvider` when a `}` is inserted due to `editor.autoClosingBrackets`.

Perhaps there is a way to provide us with a formatting request in this scenario?

Although the block would be empty, we would use this trigger to format any `for` or `while` statement associated with the block.

**Comment by jrieken** [comment] 2020-08-24 08:23
Adding @alexdima to check how those characters are inserted and if they can trigger a type event

**Comment by alexdima** [comment] 2020-08-24 09:48
@jrieken I looked into it with the following change:
  ![image](https://user-images.githubusercontent.com/5047891/91030567-a96aee80-e5ff-11ea-815f-61fd67f1174b.png)

And I can see the two events fire when I type `}` in C++.

**Comment by jrieken** [comment] 2020-08-24 09:54
@alexdima my understanding of the issue is that the problem is with `}`s that get inserted automatically after typing `{`. The question is if there is some event that allows me observe that `}` got inserted automatically but due to auto-closing pairs.

**Comment by alexdima** [comment] 2020-08-24 10:08
Thanks for clarifying. So this is about typing `{`, which leads to `{|}` to be inserted.

@Colengms Would it then make sense to add `{` as an auto-format trigger character too? Since the user did not type `}`, but `{` ?

@jrieken I'm not sure what the contract of `OnTypeFormattingEditProvider` is around trigger characters. If by trigger characters we mean characters that were typed by the user via a keyboard or a Braille device, etc, then the current implementation is sensible. But if by trigger characters we mean that a certain character was inserted in the text, then the implementation of on type formatting needs to change to also work when pasting a `}`, or inserting a completion that inserts a `}` or when the `vim` extension decides to insert a `}`, etc. In this case, the `type` events are not useful since they would not fire.

**Comment by jrieken** [comment] 2020-08-24 12:57
> @jrieken I'm not sure what the contract of OnTypeFormattingEditProvider is around trigger characters.

There is no contract set in stone here but "yes" format on type should work with typing. Today, there two cases (1) typed or (2) everything else. Maybe there is something in between like "type triggered code change" or "user gesture triggered code change"

**Comment by jrieken** [comment] 2020-08-24 13:11
@alexdima is there a dedicated event or event property for when auto-closing has happened?

**Comment by alexdima** [comment] 2020-08-30 20:49
No, there isn't any special event when auto-closing occurs. I would wait with @Colengms to let us know if this could be addressed by simply adding `{` as a trigger character before exposing more editor internals.

**Comment by d-koppenhagen** [comment] 2020-12-02 19:25
Hey, I think it would be great if an extension would able to temporarily disable the `editor.autoClosingBrackets` settings. I am currently running into the same issue when contributing to the auto-completion functionality: 

https://github.com/asciidoctor/asciidoctor-vscode/pull/381

I opened also a thread on stackoverflow: https://stackoverflow.com/questions/65079743/prevent-autoclosingbrackets-when-inserting-content-as-result-of-registercompleti

**Comment by Colengms** [comment] 2021-10-15 18:47
Hi @alexdima .  I had investigated whether that would work, and ran into some complications.  I will update this issue as soon as I can.

**Closed** 2022-01-13 11:27 UTC
Labels: feature-request, needs more info, formatting, editor-autoclosing
