### ISSUE TITLE
Support starting VSCode in WSL in offline mode without new server

### ISSUE THREAD

**Issue by fpintos** [microsoft/vscode#158045] opened 2022-08-12 20:54 UTC
Type: <b>Feature Request</b>

I recently got into a situation where I wanted to use VSCode to edit files in WSL and I had no network connectivity.

If I recall correctly, I opened my WSL terminal and typed 'code'.

It deleted the current vscode server installation and tried to install a newer version, but at that point, without connection, it could not do that, and now I was stuck without vscode on that WSL instance.

I'll suggest that the script should try to download and install the new version without deleting the existing one, and if not connected, just use the old one.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by KyleRAnderson** [comment] 2022-08-20 02:45
I've experienced a few cases where I close VSCode with an update downloaded, the application upgrades when closed, and then upon reopning it later with no internet connectivity, I'm unable to use VSCode in WSL as it was tries to download the new server version and can't.

I know this might seem like an edge case but it's actually happened quite a few times to me at least.

**Comment by aeschli** [comment] 2022-12-07 15:17
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3839

**Closed by aeschli** 2022-12-07 15:17 UTC
