### ISSUE TITLE
Cannot run build after upgrade

### ISSUE THREAD

**Issue by elmt1** [Microsoft/vscode#24146] opened 2017-04-06 21:50 UTC
Hello, I don't yet know my way around VSCode but I was using it to try some things out and ran into a problem. I was working with a project and it would build fine. At some point, VSCode and it told me that an update was available. I decided to install the update. After that, I can no longer run build because of the following error: Cannot read property 'config' of undefined

I took my project down to its simplest form and even created a new empty project with one simple file. When I hit ctrl-shift-b I get the cannot read property config error. Everything else seems to work and I can open the console and compile/build from there. I have looked for some sort of logging and I see nothing. 

I have tried removing all keyboard and workspace customization but I still get the error. Any idea what I need to do to fix this?

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.2.4|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|1.0.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|;

---

Steps to Reproduce:

1. Create a new empty folder.
2. Add a simple .ts file.
3. Open the folder with vscode.
4. Press ctrl-shift-b

**Comment by chrmarti** [comment] 2017-04-06 23:12
Adding `"tasks": {}` to your settings should work around this issue.

**Comment by elmt1** [comment] 2017-04-06 23:17
That seems to work. Thank you!

**Comment by dbaeumer** [comment] 2017-04-07 08:10
Was able to reproduce. This is a regression and easy to fix.

**Comment by Slowlearneruk** [comment] 2017-04-07 08:24
Also seeing this error:
`Cannot read property 'tasks' of undefined`
With the following tasks.json:
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "grunt",
	"isShellCommand": true,
	"args": [],
	"showOutput": "always",
	"tasks": [
		{
			"taskName": "develop",
			"args": [],
			"isBuildCommand": true,
			"isBackground": false,
			"problemMatcher": [
				"$lessCompile",
				"$tsc",
				"$jshint"
			]
		}
	]
}
```

**Comment by dbaeumer** [comment] 2017-04-07 09:45
@Slowlearneruk thanks. Was able to reproduce as well. I fixed both in master and will prepare a fix for a recovery build.

**Comment by dbaeumer** [comment] 2017-04-07 09:46
Marking as important since this is a regression.

**Comment by jorgelbg** [comment] 2017-04-07 13:12
I have a the same issue using the go extension. `Cannot read property 'config' of undefined`

**Comment by sashaafm** [comment] 2017-04-09 10:34
Same here

**Comment by dbaeumer** [comment] 2017-04-10 07:44
Fixed for master and recovery build.

**Closed by dbaeumer** 2017-04-10 07:44 UTC
Labels: bug, important, tasks

**Comment by dbaeumer** [comment] 2017-04-12 08:17
@isidorn can you please verify.

**Comment by isidorn** [comment] 2017-04-12 10:08
Adding verified since I can not reproduce both issues with the latest stable candidate
