### ISSUE TITLE
Vim Extension Fails to Load on Extension Update

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#45604] opened 2018-03-12 16:59 UTC
Despite the fix here https://github.com/Microsoft/vscode/issues/40260. We are *still* getting reports of people unable to install an update to the extension.

- VSCode Version: 0.11.1 -> 0.11.2 of VSCodeVim
- OS Version: Various

Since the release the fix (https://github.com/Microsoft/vscode/issues/40260), we've had these issues filed:

* https://github.com/VSCodeVim/Vim/issues/2226
* https://github.com/VSCodeVim/Vim/issues/2415
* https://github.com/VSCodeVim/Vim/issues/2436

**Comment by jpoon** [comment] 2018-03-12 16:59
https://github.com/Microsoft/vscode/issues/40260 is locked so re-opening a new issue here.

**Comment by sandy081** [comment] 2018-03-13 07:28
Duplicate of #43813

**Closed** 2018-03-13 07:30 UTC
Labels: *duplicate, extensions
