### ISSUE TITLE
Link highlighting is applied inside codeblocks

### ISSUE THREAD

**Issue by HuskyNator** [microsoft/vscode#139770] opened 2021-12-26 14:21 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows_NT 10.0.19043

Steps to Reproduce:

1. Open a .md file (or manually select md highlighting)
2. Enter:
````
```
[](a)
```
````

**Comment by Pranshu258** [comment] 2022-01-06 00:02
![image](https://user-images.githubusercontent.com/7602984/148307080-3f5d3be5-cef4-48ce-98fa-f630c23e5bb8.png)
could not reproduce

**Comment by mjbvz** [comment] 2022-01-06 01:25
The `a` in the link is being underlined. This means it's a clickable link in the editor when it should not be

**Comment by Pranshu258** [comment] 2022-01-06 02:20
> The `a` in the link is being underlined. This means it's a clickable link in the editor when it should not be

@mjbvz I am trying to implement a fix for this, do you which file I should look at. I am not very familiar with the codebase. Thanks

**Comment by Pranshu258** [comment] 2022-01-06 02:28
I found another file which I think might be relevant for this - extensions/markdown-langauge-features/notebook/index.ts. Looking at the method "ActivationFunction".

**Comment by stampyzfanz** [comment] 2022-01-06 09:04
I personally don't think the grammar is at fault because of the results returned from the command `Developer: Inspect Editor Tokens and Scopes` on the following code.
````
```
[](first)
```
[](second)
````
- Second: classified as **link** under *textmate scopes* and should be **underlined**
- First: classified as  **code fence** under *textmate scopes* and does not have any associated style.

**Comment by mjbvz** [comment] 2022-01-06 21:02
@Pranshu258 The link in this case comes from the markdown link detector: 

https://github.com/microsoft/vscode/blob/a9bc0553f7d74586690221c878d3e8f14b14df30/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L105

This code likely doesn't properly check that we are inside a code block

**Comment by N00rAhmed** [comment] 2022-01-11 00:46
````

**Comment by iswarmondal** [comment] 2022-01-13 14:34
Hey @mjbvz, is this issue still open, can I contribute to this. I'm new to the opensource so I would be very glad to help.

**Comment by WaqasAliAbbasi** [comment] 2022-01-14 19:37
Hi would love to contribute as well. Here are a couple of approaches I looked into:
1. Expand the current regex -> checking we are outside indented/fenced/inline code might make the current regex too long/unreadable
2. Find the start/end of all indented/fenced/inline code sections using regex -> filter out links which overlap those sections -> Straightforward but less efficient than #1

Any thoughts @mjbvz?

**Comment by mjbvz** [comment] 2022-01-14 20:52
@WaqasAliAbbasi I think using regular expressions is going to be complicated and fragile. Instead, try using VS Code's [markdown engine](https://github.com/microsoft/vscode/blob/2a0d371ca3a7c216185eb8f4bc3831420b3c9d1c/extensions/markdown-language-features/src/markdownEngine.ts#L94) to parse the document  and the look for the code blocks within the parsed result 

The folding provide may be a good starting point for this: https://github.com/microsoft/vscode/blob/d3ceb35bece3f8ab658fb9006c9161e7a65d36c4/extensions/markdown-language-features/src/features/foldingProvider.ts#L37

**Comment by WaqasAliAbbasi** [comment] 2022-01-15 06:58
Thanks @mjbvzm that's helpful, i have started on the issue

**Closed** 2022-01-25 20:38 UTC
Labels: help wanted, markdown, good first issue
