### ISSUE TITLE
formatOnType: true breaks newline indentation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3393] opened 2016-02-24 10:30 UTC
* have `formatOnType: true`
* pressing enter on the end of the line does not indent the next line properly, it is not indented at all
* I can repro for both TS and JS

Simple snippet to repro. Pressing enter on end of first line I would expect to get indentation
```
function f() {
};
```

Works for our insider build so it seems like it is a regression -> important

fyi @alexandrudima @dbaeumer

**Comment by joaomoreno** [comment] 2016-02-25 14:20
Duplicate of #2907...

**Closed by joaomoreno** 2016-02-25 14:20 UTC
Labels: bug, important
