### ISSUE TITLE
switch branches switch working tabs

### ISSUE THREAD

**Issue by NikolaiRadoev** [microsoft/vscode#200848] opened 2023-12-14 13:23 UTC
Type: **Feature Request**

Hello VS Code
It might be a nice addition if there was an option when we switch branches to have a tab that shows you the branches you've worked on
For example, I have two branches: [branch-1: hello.js, branch-2: bye.js] and I'm working on branch-1 in the hello.js tab, when I switch to branch-2 it shows up in the bye.js tab
Thanks and stay healthy

**Comment by lszomoru** [comment] 2023-12-15 12:56
Closing as duplicate of https://github.com/microsoft/vscode/issues/35307

**Closed by lszomoru** 2023-12-15 12:56 UTC
