### ISSUE TITLE
Code will not start with locale='zh-cn' or locale='zh-tw'

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#4520] opened 2016-03-21 18:41 UTC
- VSCode Version: Insiders, ef2a1fcaa553d14d7731b284a5ac5e4a55c42936
- OS Version: OSX

Steps to Reproduce:

1. Edit `locale.json`
``` json
{
	"locale":"zh-cn"
}
```
2. Restart VS Code

Result: It does not start, I just have a "Code - Insiders" menu with a Quit action.

You have to manually edit `locale.json` to get the tool to start again

**Comment by dbaeumer** [comment] 2016-03-21 19:49
The problem here is that the FS for Mac is case insensitive however the amd loader we use is case sensitive. I need to see if I can find the correct casing of the file and then use that one as the locale independent of the case on the command line or locale.json file. 

We need to keep this case sensitive in terms of strings since the Linux file system is case sensitive.

**Comment by dbaeumer** [comment] 2016-03-21 20:11
See https://github.com/Microsoft/vscode/issues/4206 for the casing details.

**Comment by dbaeumer** [comment] 2016-03-21 20:27
The quick 'hack' fix for this is to uppercase the region (in this case cn) since we know the languages we ship. However in the mid/long term this might not work for other language since 'locale' identifiers can be more complex. (for example: zh-Hant-TW and de-CH-1901 is valid as well.). I didn't find any node API to get the casing of a file on disk. All we can do is to read the parent directory and compare. This shouldn't be too expensive since we read a directory with 18 items.

**Comment by dbaeumer** [comment] 2016-03-21 20:28
Reproduce on Windows as well since Windows FS is case insensitive as well. If we fix this we need to retest #4206 on Linux.

**Comment by chrisdias** [comment] 2016-03-21 20:34
For March, can we get comments and/or IntelliSense in the launch.json so that people don't accidentally get into this bad state?

**Comment by dbaeumer** [comment] 2016-03-21 20:44
Yes but might be work, code changes then fixing it. And we do have the --locale command line switch which is affected as well. I will see how open the team is and prepare different fixes so that we can discuss it in the team.

**Comment by dbaeumer** [comment] 2016-03-22 10:38
Fixing wise I came up with the following: locale tags are case insensitive. So we will always generate message bundles with lower case locale tags and will convert the locale specified by the user to lower case as well. This makes it work on all platforms even with a case sensitive loader.

**Comment by dbaeumer** [comment] 2016-03-22 11:51
@chrisdias please verify. Code complete or documentation for valid locale values should be handled in a different issue. I wanted to keep the code changes to fix this to a minimum.

**Closed** 2016-03-22 11:51 UTC
Labels: bug, important

**Comment by chrisdias** [comment] 2016-03-23 00:21
looks good, modulo #4589

**Comment by xgqfrms-GitHub** [comment] 2017-01-18 15:02
it should be like this!
```
"locale":"zh-CN"
```
