### ISSUE TITLE
Whitespace blocks have different background color than the default background color on dark themes

### ISSUE THREAD

**Issue by raduacosma** [microsoft/vscode#102288] opened 2020-07-12 11:33 UTC
Issue Type: <b>Bug</b>

1. Set the editor theme to a dark theme different than the default one (Nord, Material Theme Palenight, Night Owl tested).
2. Open a text file
3. Notice how the white space blocks (not between words, but empty blocks of whitespace, at the end of lines for example) have a different background color than the background of words. When selecting a line (thus making the line highlight appear), the line highlight intersects the different background color area and makes that block dissapear.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.4.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3559)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (7.39GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
code-runner|for|0.11.0
latex-workshop|Jam|8.11.1
csharp|ms-|1.22.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
wordcount|ms-|0.1.0
java|red|0.64.1
code-spell-checker|str|1.9.0
latex-utilities|tec|0.3.7
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
markdown-all-in-one|yzh|3.1.0

(2 theme extensions excluded)

</details>

![Screenshot from 2020-07-12 13-30-11](https://user-images.githubusercontent.com/49650267/87245205-d8f4db80-c443-11ea-9872-3de2854ce9a2.png)

![Screenshot from 2020-07-12 13-30-54](https://user-images.githubusercontent.com/49650267/87245215-edd16f00-c443-11ea-9f7c-2c6cdc48b0bc.png)

I could reproduce the issue on both the .tar.gz version and the .deb version, I do not seem to be able to reproduce it on the snap version. This has been persisting for a few months. The default dark theme does not seem to be affected, but that can also be because the background is simply dark and a difference is harder to see. Thanks for the great work and hope this gets resolved soon!

**Comment by IllusionMH** [comment] 2020-07-12 19:49
/duplicate of #93977 or #85452

See https://github.com/microsoft/vscode/issues/93977#issuecomment-614459402 or https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for current workarounds.

**Closed** 2020-07-12 19:49 UTC
Labels: *duplicate, new release
