### ISSUE TITLE
Running code from integrated terminal should always use same instance

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vscode#80055] opened 2019-08-29 15:12 UTC
Issue Type: <b>Bug</b>

I often run multiple vscode windows (mostly on windows but sometimes linux), and sometimes from the integrated terminal, when I run `code myfile.txt`, the file will be opened in one of the other vscode instances. I tried using `--reuse-window` but that did not matter.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (0.39GB free)|
|Process Argv|C:\Users\e27290\projects\squadx-new\squadx.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.5.0
project-manager|ale|10.7.0
clipboard-history|Anj|1.0.7
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.1
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.15
docs-preview|doc|0.3.28
docs-yaml|doc|0.2.3
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.9.3
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
matlab|Gim|1.2.0
vscode-peacock|joh|3.1.5
restructuredtext|lex|114.0.0
cmake-tools-helper|mad|0.2.1
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.25.0
powershell|ms-|2019.5.0
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.752
printcode|nob|3.0.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.9.0
vscode-yaml|red|0.5.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.2
vscode-table-formatter|shu|1.2.1
vscode-fileutils|sle|2.14.9
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
code-spell-checker|str|1.7.18
python|tht|0.2.3
cmake|twx|0.0.17
vscode-terminal-here|Tyr|0.2.4
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.3.0
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2019-08-29 15:51
Yeah good timing, I pushed a fix for that during the milestone, can you verify?

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by pwm1234** [comment] 2019-08-29 18:39
Yes, I just checked the latest insiders version, and at first it seemed to work, but then ...

I had two instances of code-insiders running. With each I opened a (different) folder. From one, call it A, I opened a file that was in the other's. B's, folder. And the file opened in A where I had executed the `code-insiders c:\B\foo.txt` in the integrated terminal of A. This is what I wanted and expected (and did not happen with 1.37.1. But then I tried to open c:\B\foo.txt from the B instance. And it opened it A, where it was already open. Not quite what I had wanted but still reasonable behavior since the file was already open in A. 

Even worse, however, I closed c:\B\foo.txt in instance A, and tried to open it from B's integrated terminal and the file still opened in A. Definitely not what I wanted.

**Comment by bpasero** [comment] 2019-08-30 05:45
@pwm1234 understood, it looks like my change (https://github.com/microsoft/vscode/commit/87f2b7682fba16cab3922308a42fcf1000c5a877) was not solving it in all cases. We still have logic in place that prefers to open a file in a window where the parent folder is opened in. 

@Tyriar can we solve this from the integrated terminal perspective maybe? Similar to what we do in the web, hijack the command to open a file and always prefer the current window IF executed from the integrated terminal?

**Comment by Tyriar** [comment] 2019-09-06 18:41
@bpasero sounds like this are acting as designed except `code-insiders -r c:\B\foo.txt` should force it to use the last active window?

**Comment by bpasero** [comment] 2019-09-10 05:13
@Tyriar we still have logic in place to prefer a window where the parent folder is opened of a file that is about to get opened from the terminal ([`findWindowOnFilePath`](https://github.com/microsoft/vscode/blob/55825e9/src/vs/code/node/windowsFinder.ts#L41)). My suggestion was to always reuse the window the integrated terminal was used from when opening files.

**Comment by Tyriar** [comment] 2019-09-13 18:15
@bpasero shouldn't we just take `openConfig.forceReuseWindow` into account when calling it here?

https://github.com/microsoft/vscode/blob/2226734db0722fa8a532af94c17c0f3e3e46fd8c/src/vs/code/electron-main/windows.ts#L561-L567

**Comment by bpasero** [comment] 2019-09-14 05:43
Yes we could do that.

**Closed** 2019-10-15 06:26 UTC
Labels: *out-of-scope, feature-request, integrated-terminal, workbench-cli
