### ISSUE TITLE
Formatting braces on new line causes editor to scroll so that the topmost line is at the opening brace

### ISSUE THREAD

**Issue by lachy874125** [microsoft/vscode#176108] opened 2023-03-04 03:12 UTC
Type: <b>Bug</b>

1. Set user `settings.json` to:
```
{
    "editor.formatOnType": true,
    "C_Cpp.formatting": "vcFormat",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.function": "newLine"
}
```
2. Create a new file with a `.cpp` extension.
3. Type `int main(){` and press enter.

The program puts the opening curly brace on a new line as expected but then it scrolls so that the topmost line is the one with the curly bracket. So I am not able to see `int main()`. I don't expect any scrolling to occur. The same behaviour occurs if I set the newLine setting for braces of blocks, namespaces, etc. I have tested this on two machines both with the same behaviour.

I originally raised a bug with the C++ tools extension linked here [https://github.com/microsoft/vscode-cpptools/issues/10626](url). They said the extension "sends VS Code the appropriate vscode.TextEdit[] and we're not doing any scroll change".

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.11GB free)|
|Process Argv|--crash-reporter-id 3531e1fd-b2e7-4bda-b416-aa65e7f0e5cb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.4.0
cpptools|ms-|1.14.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
vsctsb:30677850
funwalk2:30676043

```

</details>

**Comment by jrieken** [comment] 2023-12-04 15:40
Closing as duplicate of https://github.com/microsoft/vscode/issues/173540

**Closed by jrieken** 2023-12-04 15:40 UTC
Labels: formatting
