### ISSUE TITLE
VSCode freezes after a few minutes of work on a network folder

### ISSUE THREAD

**Issue by vinlos** [Microsoft/vscode#13428] opened 2016-10-10 14:24 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 7 64 bit

Steps to Reproduce:
1.  Open a folder located on the network (it can be a either a SMB folder or a WebDAV mounted drive)
2.  Open the same file in two editors side by side (it's a CSS file in my case)
3.  Work for a few minutes by making changes and saving several times
4.  VS Code freezes and it should be restarted (please look at the screenshot)

![vscode_crash](https://cloud.githubusercontent.com/assets/1380443/19239366/f9f5b25e-8f05-11e6-988c-4dd6a487afda.PNG)

**Comment by vinlos** [comment] 2016-10-11 08:27
same issue with VS Code 1.6.0

**Comment by bpasero** [comment] 2016-10-13 06:51
I suspect an issue with CSS tokenizer though. Does it reproduce with other files?

**Comment by aeschli** [comment] 2016-10-13 07:17
@vinlos Any chance you can share the css file that shows the problem? From the screenshot it looks at if this isn't pure css.

**Comment by aeschli** [comment] 2016-10-17 14:27
Also please try on a regular drive (not a network drive).

**Comment by aeschli** [comment] 2017-02-01 15:06
Closing as I'm not able to reproduce.

**Closed by aeschli** 2017-02-01 15:06 UTC
Labels: needs more info

**Comment by vinlos** [comment] 2017-02-01 16:15
I agree. Fortunately I'm not able to reproduce it anymore. Probably fixed in the latest releases
