### ISSUE TITLE
Git - Commit signing with SSH key

### ISSUE THREAD

**Issue by neo** [microsoft/vscode#159584] opened 2022-08-30 16:33 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS 12.3

Steps to Reproduce:

1. Set git config to default sign commits and sign with SSH
2. Verify being able to commit in the integrated terminal
3. Try to commit via the side panel GUI, and see this error some times:

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - --allow-empty
error: Enter passphrase: Load key "<path to key>": incorrect passphrase supplied to decrypt private key?

fatal: failed to write commit object
```

the other times (this only happened to when I used a FIDO2 physical security key based SSH key):

```
error: Signing file /var/folders/pv/xzhdszd900z95sz3ytth88g00000gn/T//.git_signing_buffer_tmpVytrZT
Couldn't sign message (signer): agent refused operation?
Signing /var/folders/pv/xzhdszd900z95sz3ytth88g00000gn/T//.git_signing_buffer_tmpVytrZT failed: agent refused operation?

fatal: failed to write commit object
```

- I can confirm the key is in the `ssh-add -l` results
- It only happens when it's from a security key **and** requires a passphrase (it works when it's security key but no passphrase)

**Comment by aaronjones** [comment] 2022-09-22 21:14
Is there a workaround for this?

**Comment by neo** [comment] 2022-09-22 21:22
my current workaround is to have change the password of the private key to not have a password 😂

**Comment by arrrgi** [comment] 2023-01-26 05:16
+1

My git config has

```
[user]
    name = Person
    signingkey = key::ssh-ed25519 <key cut for brevity>
[gpg]
    format = ssh
```

Trying to commit via the sidebar results in

`error: Couldn't load public key key::ssh-ed25519 <key cut for brevity>: No such file or directory?`

Committing via CLI with `git commit -S --message "my commit message"` works as @neo mentioned

I can see the same key when running `ssh-add -L`

**Comment by rohit-gohri** [comment] 2023-02-16 22:15
I setup a security key recently and set git config to sign with an ED25519-SK key. And committing worked in vscode until I restarted the system. I suspected it was related to ssh-agent. Adding this to my `.zshrc` fixed the issue for me (on macOS) :

```sh
export PATH=$(brew --prefix openssh)/bin:$PATH

eval "$(ssh-agent -s)"
```

**Comment by ishuar** [comment] 2023-02-17 00:40
Experiencing the same issue, I recently added my SSH  signing key to GitHub, but it does not work with VS code sidebar commit after configuring `"git.enableCommitSigning": true` in `settings.json`. 

- Key is available in `ssh-add -l`
- It Is working from the terminal with `git commit -S -m "message"`

**System Info:**   MAC OS `13.1` with M1  

**Command Outp1ut while committing from VS Code Sidebar.**
```bash
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - -S
error: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1
(()=>{"use strict";var e={4516:(e,s,r)=>{Object.defineProperty(s,"__esModule",{value:!0}),s.IPCClient=void 0;const t=r(8605);s.IPCClient=class{constructor(e){this.b=e;const s=process.env.VSCODE_GIT_IPC_HANDLE;if(!s)throw new Error("Missing VSCODE_GIT_IPC_HANDLE");this.a=s}call(e){const s={socketPath:this.a,path:`/${this.b}`,method:"POST"};return new Promise(((r,n)=>{const o=t.request(s,(e=>{if(200!==e.statusCode)return n(new Error(`Bad status code: ${e.statusCode}`));const s=[];e.on("data",(e=>s.push(e))),e.on("end",(()=>r(JSON.parse(Buffer.concat(s).toString("utf8")))))}));o.on("error",(e=>n(e))),o.write(JSON.stringify(e)),o.end()}))}}},5747:e=>{e.exports=require("fs")},8605:e=>{e.exports=require("http")}},s={};function r(t){var n=s[t];if(void 0!==n)return n.exports;var o=s[t]={exports:{}};return e[t](o,o.exports,r),o.exports}var t={};(()=>{var e=t;Object.defineProperty(e,"__esModule",{value:!0});const s=r(5747),n=r(4516);function o(e){console.error("Missing or invalid credentials."),console.error(e),process.exit(1)}!function(e){if(!process.env.VSCODE_GIT_ASKPASS_PIPE)return o("Missing pipe");if(!process.env.VSCODE_GIT_ASKPASS_TYPE)return o("Missing type");if("https"!==process.env.VSCODE_GIT_ASKPASS_TYPE&&"ssh"!==process.env.VSCODE_GIT_ASKPASS_TYPE)return o(`Invalid type: ${process.env.VSCODE_GIT_ASKPASS_TYPE}`);if("fetch"===process.env.VSCODE_GIT_COMMAND&&process.env.VSCODE_GIT_FETCH_SILENT)return o("Skip silent fetch commands");const r=process.env.VSCODE_GIT_ASKPASS_PIPE,t=process.env.VSCODE_GIT_ASKPASS_TYPE,i="https"===t?e[2]:e[3];let c,p,a;"https"===t&&(c=e[4].replace(/^["']+|["':]+$/g,"")),"ssh"===t&&(/passphrase/i.test(i)?p=e[6].replace(/^["']+|["':]+$/g,""):(c=e[6].replace(/^["']+|["':]+$/g,""),a=e[15])),new n.IPCClient("askpass").call({askpassType:t,request:i,host:c,file:p,fingerprint:a}).then((e=>{s.writeFileSync(r,e+"\n"),setTimeout((()=>process.exit(0)),0)})).catch((e=>o(e)))}(process.argv)})();var n=exports;for(var o in t)n[o]=t[o];t.__esModule&&Object.defineProperty(n,"__esModule",{value:!0})})();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: Cannot read properties of undefined (reading 'replace')
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:1665
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:1922
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:1938
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:2044)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/
fatal: failed to write commit object
```

**Comment by ishuar** [comment] 2023-02-20 09:23
> Experiencing the same issue, I recently added my SSH signing key to GitHub, but it does not work with VS code sidebar commit after configuring `"git.enableCommitSigning": true` in `settings.json`.
> 
> * Key is available in `ssh-add -l`
> * It Is working from the terminal with `git commit -S -m "message"`
> * SSH key has passphrase
> 
> **System Info:** MAC OS `13.1` with M1
> 

Able to sign commits using the VSCode Sidebar, most probably the issue was that I had multiple `ssh-agent`.  Because I had restarted my machine and did not verify it so it is my hunch.

Again added the SSH private key created for signing to the ssh-agent using 
```bash
ssh-add <path_to_private_key>
# ssh-add ~/.ssh/personal-github-signing-key ## example, it will ask your passphrase. ##
ssh-add -l ## verify if it is added.
```
### What worked for me

- Restart the machine 
- Add the key to ssh-agent again

**Comment by CJ42** [comment] 2023-03-08 10:39
> > Experiencing the same issue, I recently added my SSH signing key to GitHub, but it does not work with VS code sidebar commit after configuring `"git.enableCommitSigning": true` in `settings.json`.
> > 
> > * Key is available in `ssh-add -l`
> > * It Is working from the terminal with `git commit -S -m "message"`
> > * SSH key has passphrase
> > 
> > **System Info:** MAC OS `13.1` with M1
> 
> Able to sign commits using the VSCode Sidebar, most probably the issue was that I had multiple `ssh-agent`. Because I had restarted my machine and did not verify it so it is my hunch.
> 
> Again added the SSH private key created for signing to the ssh-agent using
> 
> ```shell
> ssh-add <path_to_private_key>
> # ssh-add ~/.ssh/personal-github-signing-key ## example, it will ask your passphrase. ##
> ssh-add -l ## verify if it is added.
> ```
> 
> ### What worked for me
> * Restart the machine
> * Add the key to ssh-agent again

This worked for me. Thanks @ishuar 🙏

**Comment by lszomoru** [comment] 2023-12-05 10:44
Closing this as duplicate of https://github.com/microsoft/vscode/issues/179517

**Closed by lszomoru** 2023-12-05 10:44 UTC
Labels: feature-request, git
