### ISSUE TITLE
tab as enter when working with emmet in visual studio cod

### ISSUE THREAD

**Issue by A-Y-B** [Microsoft/vscode#28420] opened 2017-06-10 13:29 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|theme-onedark|azemoh|0.4.3|
|htmltagwrap|bradgashler|0.0.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|file-icons|file-icons|1.0.3|
|autofilename|JerryHong|0.1.3|
|HTMLHint|mkaufman|0.3.3|
|sublime-keybindings|ms-vscode|2.0.1|
|stylelint|shinnn|0.24.8|
|guides|spywhere|0.7.1|
|open-in-browser|techer|1.0.0|;

---

Steps to Reproduce:

1.
2.

**Comment by Andrey-Belyaev** [comment] 2017-06-10 13:30
tab as enter when working with emmet in visual studio cod

**Comment by ramya-rao-a** [comment] 2017-06-12 18:05
Closing as duplicate of #28413

Please see https://github.com/Microsoft/vscode/issues/28413#issuecomment-307869976

**Closed by ramya-rao-a** 2017-06-12 18:05 UTC
Labels: new release
