### ISSUE TITLE
Format wrong again

### ISSUE THREAD

**Issue by hzmnet** [Microsoft/vscode#21634] opened 2017-03-01 15:50 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.copy below codes
2.format will tell what is wrong

```
<app-route path="/module" element="page-module" bindRouter onUrlChange="updateModel"></app-route>
<app-route path="/login" element="page-login" bindRouter onUrlChange="updateModel"></app-route>
<app-route path="/creator" element="page-creator" bindRouter onUrlChange="updateModel"></app-route>
<app-route path="*" redirect="/web"></app-route>


<script>
                                                                          Polymer({

                                                                          });

</script>
```

**Comment by aeschli** [comment] 2017-03-27 14:03
duplicate of #23063

**Closed by aeschli** 2017-03-27 14:03 UTC
