### ISSUE TITLE
Command with Dynamic enablement Is Buggy With Tree Items

### ISSUE THREAD

**Issue by dsanders11** [microsoft/vscode#110421] opened 2020-11-11 19:15 UTC
Issue Type: <b>Bug</b>

This was originally a comment on #102794, but it seemed unlikely it would be seen there.

The bug here is it doesn't work when a dynamic context value is used, unless something else causes the node to be re-rendered. It doesn't work if you use the global `editorIsOpen` context, but `view/title` does. It doesn't work if you use the `setContext` command but `view/title` does.

Here's an easy to reproduce example. Make a command with `editorIsOpen` as the `enablement`, and show the command as an `inline` in `view/item/context`, on a tree with children. If you expand a node with children while an editor is open, the icon won't be disabled (correct behavior). If you close the editor, the icons will stay enabled (not correct behavior, violates `enablement`). Collapse the node and re-expand it, and now the icons are disabled. Anything that causes them to re-render will change the disabled state of the icon. If you scroll up and down the list, any nodes which were previously not visible, or any that go out of view and come back in, will be updated, but others won't, leading to a list with some of the icons disabled and half not.

Here's a GIF showing the buggy behavior:

![bug](https://user-images.githubusercontent.com/5820654/98482305-690a1e00-21b5-11eb-96fe-789b740a06ac.gif)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexr00** [comment] 2022-03-24 09:15
Duplicate of the now fixed https://github.com/microsoft/vscode/issues/140010

**Closed by alexr00** 2022-03-24 09:15 UTC
Labels: bug, tree-views
