### ISSUE TITLE
`notebook.output.wordWrap` only updates after a reload

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#175051] opened 2023-02-22 01:07 UTC
Testing #174728

* run `print('asdf asfed asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf')`
* change setting
* go back to notebook and adjust window size

The setting change does not take affect.

**Comment by amunger** [comment] 2023-02-22 19:47
dupe of https://github.com/microsoft/vscode/issues/174908

**Closed by amunger** 2023-02-22 19:47 UTC
