### ISSUE TITLE
Select Kernel spins forever

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#186364] opened 2023-06-27 15:39 UTC
Testing #186238

1. On Windows, connect via SSH to 127.0.0.1.
2. Open a folder containing the file from https://github.com/microsoft/vscode/issues/186238#issuecomment-1609748984
3. Hit the Run button on the top cell
4. A "Select Kernel" quick pick shows and spins forever.

**Comment by ulugbekna** [comment] 2023-06-27 20:21
> A "Select Kernel" quick pick shows and spins forever.

A possibly related issue: https://github.com/microsoft/vscode/issues/183067

**Comment by martijnende** [comment] 2024-04-26 07:16
I'm having exactly the same issue as described here and in the linked issues. Is there any complementary information or workaround for this issue? Is there a way to e.g. set a default kernel to circumvent the kernel source selector?

**Comment by DonJayamanne** [comment] 2024-12-12 03:53
Duplicate of https://github.com/microsoft/vscode/issues/206007

**Closed by DonJayamanne** 2024-12-12 03:53 UTC
Labels: bug, notebook-kernel-picker
