### ISSUE TITLE
Insert does't toggle insert mode like most standard editoes do.

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#136565] opened 2021-11-06 07:43 UTC
Issue Type: <b>Bug</b>

1. Type the numbers 1-9.
2. Move cursor back to 1.
3. Type in the letters ABC.  Numbers move to right of letters.
4. Press insert once.
5. Type in the letters DEF.  Nothing changes on the status bar. Numbers still move to right of letters. 

This is very inconsistent compared with how most editors work.  This is actually quite annoying to hove to either keep deleting characters while inserting others, or having to copy paste/open file into another editor like Notepad++, edit, bring it back to vscode and continue working.  Very jarring to the workflow.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.38GB (1.56GB free)|
|Process Argv|--crash-reporter-id ff847a9c-5b94-44a0-b759-b62cfb7fa79c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
cortex-debug|mar|0.4.7
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
comment-wrap|nex|0.0.2
clang-tidy|not|0.5.1
code-spell-checker|str|2.0.12
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-06 08:21
/duplicate of #1012 and #86671

@alexdima any reason not to close the second of those as a duplicate of the first?

**Closed** 2021-11-06 08:22 UTC
Labels: *duplicate, new release

**Comment by Ma-XX-oN** [comment] 2021-11-11 18:28
Sorry.  I did try and look for this issue but I didn't find it. It got lost in the noise of the myriad of other bugs that came up.  Thanks.
