### ISSUE TITLE
can not output string with  color in debug console after update to 1.22.1

### ISSUE THREAD

**Issue by lerit** [Microsoft/vscode#47457] opened 2018-04-09 03:18 UTC
- VSCode Version:1.22.1
- OS Version:win10

Steps to Reproduce:

1.i use [colors ](https://github.com/Marak/colors.js)package to colorful my output 
console.log(colors.green('hello')+" world")
this will output string "hello world" that "hello" with color green(debug console,terminal)
this work fine in v1.21.1
2.after upgrade to v.1.22.1,it still work fine in terminal,but not work in debug console,
all the text color is green,not only 'hello'
terminal:
![image 5](https://user-images.githubusercontent.com/4743467/38477815-61c45694-3be7-11e8-9375-d773c33db66e.png)
debug console:
![image 6](https://user-images.githubusercontent.com/4743467/38477819-669da08a-3be7-11e8-9c7f-a3ac29d11de5.png)

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by ScriptKi77y** [comment] 2018-04-12 12:51
I also noticed this after the update.

![2018-04-12_07-37-38](https://user-images.githubusercontent.com/4461539/38677760-d52a3ed4-3e24-11e8-8e3d-758d60d89216.jpg)

**Comment by isidorn** [comment] 2018-04-23 14:27
@danielfrankcom this seems to have broke with your pr https://github.com/Microsoft/vscode/pull/45946

Would you be interested in fixing this issue?

**Comment by danielfrankcom** [comment] 2018-04-24 01:03
Yeah I definately can, but not for a little while. If someone else wants to take a crack at it in the mean time go right ahead!

**Comment by isidorn** [comment] 2018-04-24 07:59
@danielfrankcom great. Tackle it when you have time then, assigning this to May so we do not hurry.

**Comment by danielfrankcom** [comment] 2018-04-30 00:54
Hey @isidorn, I'm working on this issue now.

While I was looking at the code again, I've noticed discrepencies in the way that various ANSI codes are being handled. This, in combination with the issue that prompted my changes originally, have led to a rewrite of the whole ANSI handling function. It should be much more robust when I'm done, but I have a question regarding your preference for currently unsupported ANSI codes.

This code for example is currently unsupported by us:
![image](https://user-images.githubusercontent.com/15225573/39412657-c1371c68-4bd4-11e8-8666-a93155b895f3.png)

Would we like to print out `[K`, or hide the code on the debug console entirely? The actions taken currently vary substantially, so I'd like to define a specific way of handling situations like this. Certain codes such as `Esc[123456m` (which is completely invalid) are currently ignored, while the code mentioned above is printed to the console as `[K`.

**Comment by isidorn** [comment] 2018-04-30 09:02
@danielfrankcom first of all thanks for looking into this.
As for what to do in that specific scenario: my preference would be to not show it because that would be consistent with some other places where we [strip out ansi escape code](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L654)
However I could also be convinced to show it if you are leaning towards that.

**Comment by danielfrankcom** [comment] 2018-05-03 02:46
@isidorn Sound good.

Unless you think it really matters, I'm going to match all numbers from 0-107 as valid codes despite certain ranges not really being included as real ANSI codes. (https://en.wikipedia.org/wiki/ANSI_escape_code)

While I'm at it, I'm adding background colours as they're not currently supported. I'd like to add high-intensity colours too, but the colours all seem a bit off. I wanted to check, are there any sort of guidelines for maximum colour intensity? Certainly on the dark theme, yellow looks more like mud...

![image](https://user-images.githubusercontent.com/15225573/39558176-438a7a84-4e41-11e8-81d9-2d318a6bcfae.png)

**Comment by isidorn** [comment] 2018-05-03 07:51
@danielfrankcom great. Makes sense for ansi code ranges
If possible try to split it in two PRs, the second one that adds background colors.
As for the guidelines we do not really have them. If the color is exactly specified by ansi then there is not much we can do as we should not change it or make it lighter.
fyi our designer @misolori

**Comment by danielfrankcom** [comment] 2018-05-12 21:43
I haven't changed the actual colours at the moment, though I can if it's worth looking into.

As stated in #49764, the first commit in the pull request should be ignored, as it just provides the context of the other review.

**Comment by roblourens** [comment] 2018-05-30 22:46
Am I doing something wrong?

- Install `colors`
- Run code:

```ts
const colors = require('colors')
console.log(colors.green('hello') + ' world');
```

- No colored output:

![image](https://user-images.githubusercontent.com/323878/40751574-a24608a0-6420-11e8-9990-7188eb7cceef.png)

**Comment by isidorn** [comment] 2018-05-31 07:46
@roblourens I believe you are doing everything right. Though we stil plan to support some missing colors, but green should probably be supported
@danielfrankcom can comment more

**Comment by weinand** [comment] 2018-05-31 11:00
@isidorn this fails for me in Isiders but works fine when running out of source:

light theme:
![2018-05-31_12-57-13](https://user-images.githubusercontent.com/1898161/40778640-2994eafe-64d2-11e8-9c50-28690250b50c.png)

dark theme:
![2018-05-31_12-57-57](https://user-images.githubusercontent.com/1898161/40778659-434673dc-64d2-11e8-8460-b0ad26a77310.png)

**Comment by isidorn** [comment] 2018-05-31 11:59
@weinand I can try again once there is a new insiders

**Comment by weinand** [comment] 2018-05-31 12:15
@isidorn Probably the code relies on some source workspace detail that differs in the built and packaged product. Does it work for you if you build the packaged product locally?

**Comment by isidorn** [comment] 2018-05-31 12:37
Works fine out of source.
Does not work in insiders and when built locally.

The issue is that the output recieved from the adapter when run out of source nicely contains the anssi sequences. When using insiders the ansi characters are stripped.
Assigning to also @roblourens and @weinand to investiagte on the adapter side
Looking at this file it seems like the same extension version is used in both cases https://github.com/Microsoft/vscode/blame/master/build/builtInExtensions.json#L9
It might be somewhere between the adapter and the UI the ansi sequences get stripped

Out of source:
![screen shot 2018-05-31 at 14 32 15](https://user-images.githubusercontent.com/1926584/40782425-8818ee1a-64df-11e8-82dc-5a292e43decc.png)

Insiders:
![screen shot 2018-05-31 at 14 33 24](https://user-images.githubusercontent.com/1926584/40782440-989de70e-64df-11e8-9ac6-1620bd3b3acc.png)

**Comment by weinand** [comment] 2018-05-31 12:44
When running out of source the adapters are identical to the ones in Insiders (because they are loaded from the Marketplace).
So it cannot be something in the adapter.

**Comment by weinand** [comment] 2018-05-31 12:53
It is (again) the environment, stupid...

When running Insiders from the command line, the colors work fine.
And colors fail when running Insiders from the Finder.

**Comment by isidorn** [comment] 2018-05-31 13:01
@weinand great catch and good anlaysis. Thanks!
Should we close as duplicate then?

**Comment by weinand** [comment] 2018-05-31 13:04
No, #50340 has  the background info but would not fix this.
Leave it open until I understand the problem (and a workaround/fix).

**Comment by weinand** [comment] 2018-05-31 13:16
The npm module "colors" () relies on the environment to figure out whether colors are supported (https://github.com/Marak/colors.js/blob/a8ce90c51c929aa7759cca33bccb859027385709/lib/system/supports-colors.js#L40)

A workaround is to add a "FORCE_COLOR" variable to the environment:
```json

			"env": {
				"FORCE_COLOR": "10"
			},
```

**Closed** 2018-05-31 14:08 UTC
Labels: debug, debug-console, verification-needed
