### ISSUE TITLE
Integrated Terminal Links No More Clickable

### ISSUE THREAD

**Issue by mbugrahanc** [Microsoft/vscode#58232] opened 2018-09-08 00:07 UTC
- VSCode Version: 1.27.1
- OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Generate a path through a `grep -rn <seach_regex> <relative_path_to_workspace>` statement in VSCode Integrated Terminal
2. Cmd + Click to navigate to file
3. You will not be able to.

The issue should have been resolved back in 2017 as per https://github.com/Microsoft/vscode/issues/7321. I did not see any reverting of the feature in changelogs. I suspect there is a bug with the latest version `1.27.1`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-09-10 13:52
/duplicate of https://github.com/Microsoft/vscode/issues/58256

**Closed** 2018-09-10 13:52 UTC
Labels: *duplicate, new release
