### ISSUE TITLE
Hover signature detail is always getting truncated

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109267] opened 2020-10-23 21:12 UTC
![image](https://user-images.githubusercontent.com/2193314/97054455-b04baa00-1539-11eb-99e5-f948a7f5dd60.png)

Detail is showing very little information:

![image](https://user-images.githubusercontent.com/2193314/97054444-a88c0580-1539-11eb-8696-6b3a4fec841a.png)

**Comment by jrieken** [comment] 2020-10-26 07:50
/duplicate of https://github.com/microsoft/vscode/issues/108292

**Comment by Tyriar** [comment] 2020-10-26 15:12
@jrieken that issue seems unrelated?

**Comment by jrieken** [comment] 2020-10-26 15:22
Yeah, different duplicate

**Comment by Tyriar** [comment] 2020-10-26 19:24
Is it going to get fixed or is this by design with the new resizable widget as I much preferred wrapping vs truncating.

Before:

![image](https://user-images.githubusercontent.com/2193314/97218159-8dadd100-1785-11eb-98f1-b14a7b4cbca5.png)
![image](https://user-images.githubusercontent.com/2193314/97218169-93a3b200-1785-11eb-804c-51d6b4aad342.png)

After:

![image](https://user-images.githubusercontent.com/2193314/97218439-ed0be100-1785-11eb-9a10-eb43e52cecf0.png)
![image](https://user-images.githubusercontent.com/2193314/97218472-f85f0c80-1785-11eb-911f-c75cb19602f6.png)

**Comment by jrieken** [comment] 2020-10-27 07:31
Dude - I fixed it yesterday. Stop reopening issues and start trusting

**Closed by jrieken** 2020-10-27 07:31 UTC
Labels: *duplicate, suggest
