### ISSUE TITLE
"editor.suggestSelection": "recentlyUsed" frozen?

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#77254] opened 2019-07-11 23:40 UTC
- VSCode Version: 1.36.1 
- OS Version: macOS Mojave 10.14.4
- Does this issue occur when all extensions are disabled?: Yes

In certain files of a project, I'm apparently getting a recently used completion that I can't reset (I've tried all the clear commands).

But more importantly than being able to reset it, it seems like "recently used" could be improved on to take into account more factors (e.g. _context_ and _how recently_).

See the screenshot below, where a word suggestion continues to be selected regardless of how many times I autocomplete something else (i.e. `slice`).

<img width="1280" alt="example" src="https://user-images.githubusercontent.com/12591890/61092298-55a54200-a40b-11e9-8361-1d54d833e6f5.png">

**Comment by jrieken** [comment] 2019-07-12 05:42
Please provide repro steps

**Comment by jabacchetta** [comment] 2019-07-13 20:39
OK, took me some experimenting to figure out how to reproduce this, but think I figured it out.

1. Add the following settings:

```jsonc
{
  // // TODO: See if TypeScript has the same issue
  // "typescript.suggest.completeFunctionCalls": true,

  // `completeFunctionCalls` appears to be the problematic setting
  "javascript.suggest.completeFunctionCalls": true
}
```

2. Create a JavaScript file with the following code:

```javascript
const num = 1;
const str = 'foo';
```

3. Type `str.n` and then accept/autocomplete the word based, `num` suggestion.

4. Type `str.sl` and accept the `slice` suggestion.

5. Type in `str.` and notice that `num` is still being prioritized as the most recent autocompletion (when `slice` should be prioritized at this point).

6. Remove the `completeFunctionCalls` setting given above.

7. Repeat steps 3-5 above. But this time, notice that the `slice` suggestion is properly being prioritized.

**Comment by jrieken** [comment] 2019-07-23 15:31
This is an issue with TypeScript as it seems that the `insertText` differs, sometimes it's just `.slice` and sometimes it's `.slice($1)$0`. The LRU suggest memory selects recent item based on language, completion type, and insert text and if that differs an item isn't selected. 

<img width="945" alt="Screenshot 2019-07-23 at 17 28 56" src="https://user-images.githubusercontent.com/1794099/61725106-7193d680-ad6f-11e9-9df8-acb2520ea9a0.png">

**Comment by mjbvz** [comment] 2019-08-15 00:18
@jrieken Thanks for the investigation. Here's more detail on why this is happening:

1. In `provideCompletionItems`, we always return basic completion items with insert text such as `.slice`.
1. We only create the snippet based completions (such as `.slice($1)$0`) when the compeletion item is resolved
1. After accepting a completion, the suggestion memory stores the resolved completion item. When the next completion request comes in, it then tries matching the stored resolved completion item against unresolved completion items. This fails for `.slice($1)$0`

Do you think this is something we could fix in VS Code itself? Any potential workarounds? We can't eagerly resolve the insert text for JS/TS as that can be an expensive operation

**Comment by jrieken** [comment] 2019-08-15 07:39
> We only create the snippet based completions (such as .slice($1)$0) when the compeletion item is resolved

⬆️ That is the issue, actually the cause of multiple issues. The resolve-call should never change the insert behaviour of a completion. It was a mistake not to enforce that because it's the root of much evil. 

> We can't eagerly resolve the insert text for JS/TS as that can be an expensive operation

I honestly think we must do that. With https://github.com/microsoft/vscode/issues/73311 we already realised that items must be resolved asap and that we cannot wait once we show them. The only fix on our side I see is to forcefully call resolve before showing items - defeating the purpose of resolve...

**Comment by mjbvz** [comment] 2019-08-15 17:56
Ok, I will look to see what the cost of creating the insert text eagerly and if it is even possible to do with the existing TS api

**Comment by mjbvz** [comment] 2019-08-16 00:52
Ok, I investigated this and found we cannot fix this on the JS/TS side without dropping support for `completeFunctionCalls`.

The reason is that `completeFunctionCalls` generates the insert text using the `displayText` that typescript returns when resolving completion items. Doing this eagerly for all completion items would be expensive.

This request against TS may be relevant: https://github.com/microsoft/TypeScript/issues/25207

**Comment by mjbvz** [comment] 2020-10-15 01:02
Closing this due to lack of further user feedback over the past year. 

Long term, I feel that we should move `completeFunctionCalls` to TypeScript with microsoft/TypeScript#25207

**Closed by mjbvz** 2020-10-15 01:02 UTC
Labels: bug, javascript, suggest, typescript
