### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by jalchr** [microsoft/vscode#102576] opened 2020-07-15 07:17 UTC
We have written the needed data into your clipboard because it was too large to send. 
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99915:161)
    at resolveModuleNamesWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100282:19)
    at processImportedModules (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101695:35)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101438:17)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:60
    at Object.forEach (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:16)
    at synchronizeHostData (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138753:26)
    at Proxy.getProgram (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146608:44)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:97
    at Object.flatMap (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147790:46)
    at c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149544:28)
    at IOSession.Session.executeCommand (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:33)
    at IOSession.Session.onMessage (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149577:35)
    at Interface.<anonymous> (c:\Users\j.shaer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkit|alb|0.1.1
ng-template|Ang|0.1000.3
code-gnu-global|aus|0.2.2
azds|azu|2.0.220200611
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
supersharp|cra|0.1.4
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-deno|den|1.25.0
githistory|don|0.6.6
scala-lsp|dra|0.2.3
es7-react-js-snippets|dsz|2.8.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.12
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|5.1.3
flow-for-vscode|flo|1.5.0
auto-rename-tag|for|0.1.4
go|gol|0.15.1
beautify|Hoo|1.5.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
unity-code-snippets|kle|1.3.0
graphql-for-vscode|kum|1.15.3
csharpfixformat|Leo|0.0.84
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
vscode-aks-tools|ms-|0.0.6
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
atom-keybindings|ms-|3.0.8
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
mono-debug|ms-|0.15.8
node-debug2|ms-|1.42.5
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.16.1
resourcemonitor|mut|1.0.7
angular-console|nrw|12.0.0
vscode-yaml|red|0.8.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
vscode-fileutils|sle|3.0.1
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5
vscodeintellicode|Vis|1.2.9
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
unity-snippets|Ycl|0.1.2

(2 theme extensions excluded)

</details>
Please paste.

**Comment by mjbvz** [comment] 2020-07-15 22:16
Duplicate of https://github.com/denoland/vscode_deno/issues/89

Caused by the deno extension

**Closed by mjbvz** 2020-07-15 22:16 UTC
