### ISSUE TITLE
Definition. not found

### ISSUE THREAD

**Issue by imnurav** [microsoft/vscode#213524] opened 2024-05-27 06:03 UTC
Type: <b>Bug</b>

not to go to definition of code 

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id abeb1a8f-f884-40ca-85f2-848ad63c088c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
vscode-zipfs|arc|3.0.0
vscode-tailwindcss|bra|0.10.5
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.0.4
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-flutter-files|gor|4.8.1
headwind|hey|1.7.0
rest-client|hum|0.25.1
vscode-env|Iro|0.1.0
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.1
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.362.0
cpptools|ms-|1.20.5
java-prettier-formatter|mwp|0.1.6
gradle-language|nac|0.2.3
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.8.0
dart-syntax-highlighting-only|osc|1.0.1
material-icon-theme|PKi|5.3.0
vscode-thunder-client|ran|2.24.7
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.101.0
vscode-gradle|vsc|3.13.5
vscode-icons|vsc|12.7.0
vscode-nextjs-snippets|wil|0.3.0
material-theme|zhu|3.17.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-05-27 06:05
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by mjbvz** [comment] 2024-06-17 20:30
Closing as we can't investigate without proper steps to reproduce this

**Closed by mjbvz** 2024-06-17 20:30 UTC
