### ISSUE TITLE
Native IW forgets scroll position, jumps to top on return

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#131742] opened 2021-08-26 19:27 UTC
As mentioned in https://github.com/microsoft/vscode-jupyter/issues/6490#issuecomment-906536351, a small issue with the native IW is that switching between multiple windows, I'm often not at the scroll position where I left off when returning to the same window. Instead the IW has usually jumped to the top.

This is somewhat hard to reproduce in a minimal example but this seems to do the trick:

1. Create two files `a.py` and `b.py`.
2. Copy this code into both:
    ```py
    # %%
    import matplotlib.pyplot as plt


    for _ in range(10):
        plt.plot() # just some stuff to fill the window and get it scrolling
        plt.show()
    ```
3. Run both files in IWs.
4. Switch back and forth between both IW tabs.
5. For me `a.py` will be scrolled to the top every time I select it, even if I scrolled all the way down the last time.

**Comment by greazer** [comment] 2021-12-13 17:45
Resolving as dupe of #138557.

**Closed by greazer** 2021-12-13 17:45 UTC
Labels: bug, interactive-window
