### ISSUE TITLE
I hate this new logo

### ISSUE THREAD

**Issue by leeseean** [Microsoft/vscode#36009] opened 2017-10-11 02:07 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.I hate this new logo
2.I hate this new logo

Reproduces without extensions: Yes/No

**Comment by jindaxia** [comment] 2017-10-11 02:17
agree

**Comment by SethPoulsen** [comment] 2017-10-11 05:47
This is a duplicate of [#35683](https://github.com/Microsoft/vscode/issues/35683) and [#35783](https://github.com/Microsoft/vscode/issues/35783). Don't worry, you're not alone ;). Follow the links to see the hundreds of other complaints about it...

**Comment by BIGWarriorSoftware** [comment] 2017-10-11 06:38
If you hate this, you can change it in the application properties.

**Closed** 2017-10-11 09:54 UTC
Labels: duplicate

**Comment by coladou** [comment] 2017-10-14 15:04
Urgly LOGO!
