### ISSUE TITLE
maybe some input methods typing chinese in terminal tab don't work

### ISSUE THREAD

**Issue by ZhyMC** [microsoft/vscode#117024] opened 2021-02-19 10:04 UTC
- VS Code Version:1.53.2
- OS Version:Win10 10.0.18363

Steps to Reproduce:

1. switch the default input method to sogou ime(https://pinyin.sogou.com/)
2. typing chinese characters in terminal tab
3. nothing gonna happened , but english letters typing works
4. switch to microsoft's chinese input method "Microsoft PinYin"
5. typing chinese characters in terminal tab
6. everything works just fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2021-02-19 10:21
Duplicate of #115814

**Closed** 2021-02-19 11:12 UTC
