### ISSUE TITLE
Calling context.extension.exports throws

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#119596] opened 2021-03-23 13:25 UTC
Testing #119548

Uncaught TypeError: $e(...).getExtensionExports is not a function

**Comment by dbaeumer** [comment] 2021-03-23 13:28
Same for `context.extension.isActive`

**Comment by dbaeumer** [comment] 2021-03-23 13:32
Same for `context.extension.activate()`

**Comment by eamodio** [comment] 2021-03-23 17:05
Duplicate of #119636

**Closed by eamodio** 2021-03-23 17:05 UTC
Labels: *duplicate
