### ISSUE TITLE
Mixing code. Php, html, css, javascript. Intellisense

### ISSUE THREAD

**Issue by sunco007** [Microsoft/vscode#6616] opened 2016-05-21 20:17 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10 Insider 14342

If you mix code in the same file, it doesn't work well

For example, I create an empty Php file, and then add Html/Css/JavaScript code, it doesn't work

I mean, intellisense doesn't show <table or <div. It shows just Php stuff

However, you can collapse <head, <body and <script. Also you can collapse <div and <table

You can't add styles inside a div, for example <div style="display:none" (intellisense). The same with styles inside a <style

There is no way to make intellisense work on a <table for example for the width

Also would be nice jQuery support

Some simple code

![code](https://cloud.githubusercontent.com/assets/622200/15450677/5125d138-1f5f-11e6-9899-6be006db10a6.png)

**Comment by aeschli** [comment] 2016-05-23 07:32
duplicate of #670

**Closed by aeschli** 2016-05-23 07:32 UTC
