### ISSUE TITLE
Issue reporter did not clarify its actions in advance

### ISSUE THREAD

**Issue by yfdyh000** [microsoft/vscode#131349] opened 2021-08-22 09:25 UTC
Issue Type: <b>Feature Request</b>

Steps to reproduce:
1. Use 'Help: Start Extension Bisect', does to gets a result.
Issues:
1. This window only provides a cerate button, does not clarify it will create an issue to the resulting extension's Issue on Github.

Steps to reproduce:
2. Fill in the necessary information in the issue reporter window.
Issues:
2. It does not clarify which Github account will be used, as well as allow previews to review the issue report in advance, this may lead to unexpected information exposure to public.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by TylerLeonhardt** [comment] 2021-08-25 01:59
>  It does not clarify which Github account will be used

This could probably be more clear... but it uses the GitHub account that you're logged in with in VS Code. You can only be logged in to one GitHub account in VS Code.

At the end of the day, I think this is really a duplicate of https://github.com/microsoft/vscode/issues/117657

which, when we work on that, should make it more clear that it will create an issue.

**Closed by TylerLeonhardt** 2021-08-25 01:59 UTC
