### ISSUE TITLE
Problem messages not showing in the popover when hovering with the mouse

### ISSUE THREAD

**Issue by floatingpurr** [microsoft/vscode#136671] opened 2021-11-08 14:31 UTC
Does this issue occur when all extensions are disabled?: No (since it's a feature based on the VSCode language server)

- VS Code Version: 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a)
- OS Version: macOS BigSur 11.6

When I hover with the mouse on a problem, I can't see all the available error messages (e.g., flake8 messages are available just in the problem box at the bottom, but not in the popover). I used to see all of them also in the popover before the last VSCode update.

<img width="524" alt="a" src="https://user-images.githubusercontent.com/14820600/140758921-78698078-c589-4f3b-aaf7-56a244f1acb6.png">

Steps to Reproduce:

1. Install official Python extensions (Python + Pylance)
2. Install flake8 as a project linter
3. Create a faulty piece of code
4. You should see the problem in action in the popover when you put the mouse on the faulty piece of code.

**Comment by floatingpurr** [comment] 2021-11-08 14:53
Looks like a problem with Pylance rather than with VSCode. Gonna post to its repo. Sorry for the inconvenience.

**Comment by floatingpurr** [comment] 2021-11-08 15:05
FYI: https://github.com/microsoft/pylance-release/issues/2047

**Comment by floatingpurr** [comment] 2021-11-09 07:46
As pointed out in the [Pylance issue board](https://github.com/microsoft/pylance-release/issues/2047#issuecomment-963393138), the problem seem related to VSCode instead. I re-open this issue.

**Comment by sandy081** [comment] 2021-11-09 16:18
May I know if you see any errors in the developer tools console while trying to open the hover? Are you able to see hover in general, for eg hovering on valid code shows its doc ?

**Comment by floatingpurr** [comment] 2021-11-09 16:28
Hi @sandy081. No into the dev console there's nothing showing up upon opening the hover. I've found also this related issue in vscode-python: https://github.com/microsoft/vscode-python/issues/17882

**Comment by floatingpurr** [comment] 2021-11-09 17:06
Something has happened during the transition from 1.61.2 to 1.62.0. In version 1.61.2, the reported issue is not present.

**Comment by Redoubts** [comment] 2021-11-10 13:40
Maybe related: https://github.com/microsoft/vscode/issues/136711

**Comment by sandy081** [comment] 2021-11-11 13:17
Yeah seems to be related to hover - assigning to @alexdima to decide if it is a dup of #136711 or not.

**Comment by alexdima** [comment] 2021-11-11 13:28
:+1: Duplicate of #136711 . Collapsed error messages are rendered larger (expanded to 1ch), but hovering over them was very finicky. With the fix for #136711 we now expand the hit-box area for these collapsed errors.

**Closed by alexdima** 2021-11-11 13:28 UTC
