### ISSUE TITLE
Typescript service KO in VSCode

### ISSUE THREAD

**Issue by johanchouquet** [microsoft/vscode#103836] opened 2020-08-03 14:34 UTC
Issue Type: <b>Bug</b>

I upgrade VSCode to latest, and in my Angular Project (v10), I don't have anymore the ability to :
- Go To Definition: it always shows 'No definition found'
- The contextual menu is quite shorter than before: I can't for example 'Rename' a variable etc...
Don't know why it acts like that. Don't know how to check if this is local to my installation of VSCode, or a more important problem. Last week, I had message that Typescript Service is OFF after 5 trials to boot without success. Now, just no message, but i don't have anything yet.
So, can't point to reproduction steps neither, except this.

Hope it helps a bit.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.7
vscode-color|ans|0.4.5
vscode-mjml|att|1.6.0
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
svg|joc|1.3.8
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
vscode-docker|ms-|1.4.1
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|13.0.0
typescript-hero|rbb|3.0.0
vsfire|tob|1.4.1
vim|vsc|1.16.0
markdown-all-in-one|yzh|3.2.0

(3 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-08-03 15:11
Looks like this is behavior caused by Angular 10 new config approach when a non-imported files aren't part of the project.

See https://github.com/angular/angular-cli/issues/18040, https://github.com/angular/angular-cli/issues/18170 and related TS Issue https://github.com/microsoft/TypeScript/issues/39632 (has doc with possible change to include config option that should add all files to project)

**Comment by johanchouquet** [comment] 2020-08-03 15:20
Thanks @IllusionMH , I'll check those links, and hopefully find the right config...

**Comment by mjbvz** [comment] 2020-08-03 19:30
Thanks @IllusionMH. Closing as upstream issue on TypeScript: microsoft/TypeScript#39632

**Closed by mjbvz** 2020-08-03 19:30 UTC
