### ISSUE TITLE
Snippets appear in comments when typing dot

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#85761] opened 2019-11-28 10:12 UTC
I checked but this doesn't seem to be an error with the specific snippit extension I'm using (vue 2 snippets)

Steps to Reproduce:

1. Install Vue 2 Snippets (https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets)
2. Open a .js file
3. In comments, type some stuff, followed by "."
4. snippet suggestions appear and first is selected.

Obviously snippets are useful and you WANT the first to be selected and created when you press enter. In comments I sometimes use a full stop at the end of a scentence and then press enter. Doing so adds the snippet. This is non desireable.

Does this issue occur when all extensions are disabled?: No

This is because it is a snippet specific issue, and an extension adds a snippet that includes `.` in it's trigger.
![Screen Shot 2019-11-28 at 10 11 26](https://user-images.githubusercontent.com/731158/69797384-7e19b700-11c7-11ea-82cd-97a5934668d8.png)

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Comment by Relequestual** [comment] 2019-11-28 10:15
Not a duplicate

**Comment by gjsjohnmurray** [comment] 2019-11-28 12:41
Unless #58112 (or similar) gets implemented I don't think statically-added snippets can be prevented from appearing when you're typing inside what the language defines as comments.

If you're willing to set ```"editor.acceptSuggestionOnEnter": false``` then you won't get the issue but you'll have to retrain yourself to use <kbd>Tab</kbd> to accept suggestions.

**Comment by Relequestual** [comment] 2019-11-28 12:50
Hum. I had assumed that at least being able to differenciate between comments and code for snippets would be possible.

Thanks for pointing me towards turning off enter for accepting suggestions. I actually find `tab` more natrual anyway as I use a lot of CLI.

I guess leave this open looking for #58112 to be resolved first.

**Comment by jrieken** [comment] 2019-11-28 13:35
Closing as designed or dupe of the aforementioned issue because there will be no code change for this issue

**Closed** 2019-11-28 13:35 UTC
Labels: *as-designed

**Comment by Relequestual** [comment] 2019-11-28 13:48
@jrieken If the other issue was to be resolved, I would want to see a configuration option to disable suggestions in comments by default, which should be enabled by default.

The VSCode site defines snippets...

> Code snippets are templates that make it easier to enter repeating code patterns, such as loops or conditional-statements.

https://code.visualstudio.com/docs/editor/userdefinedsnippets

"Code snippets", and as such should not be in comments. Comments are not code.

Alternativly, I could further issue that this is a bug, and any API should enable the potential to add snippets for comments as a separate issue.

I believe the current situation is not the expected behaviour for most users.
