### ISSUE TITLE
shortcut in DVORAK Keyboard

### ISSUE THREAD

**Issue by sofianhw** [Microsoft/vscode#6020] opened 2016-04-30 16:38 UTC
- VSCode Version: 1.0.0 
- OS Version: OSX 10.11.4 (15E65)

Steps to Reproduce:

When I press "CMD"+"/" the result is "CMD"+"["
and others
Should I re-binding the shortcut

Thanks

**Comment by spywhere** [comment] 2016-05-04 02:37
Could you try it on different editor? Key mappings are different from each other. DVORAK, for example, has many varieties including DVORAK (command QWERTY) which I think is what you need.

If you want an alternative key mapping (not try to advertise though), I would suggest Karabiner which also supports most varieties of DVORAK.

**Comment by mathiasvr** [comment] 2016-06-28 00:19
I think this is a duplicate of #1492. My current work around is the suggestion in https://github.com/Microsoft/vscode/issues/1492#issuecomment-177733183.
VSCode is still the only editor that I have experienced this issue with.

**Comment by agektmr** [comment] 2016-08-27 04:23
Hi, I'm having the similar issue (merged issue #10986). As I noted there, the biggest problem is Karabiner not working on VSCode. It works without any problems on SublimeText or Atom.
Can you take a look? This is the only blocker for me to use VSCode.

**Comment by HookyQR** [comment] 2016-11-18 07:43
See https://github.com/Microsoft/vscode/issues/15624#issuecomment-261412779 and PR https://github.com/Microsoft/vscode/pull/15687

**Comment by alexandrudima** [comment] 2017-03-24 10:07
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24288943/8f2ce4dc-107f-11e7-8f48-162d2ea3a0aa.png)

---
### Analysis of default keybinding for `editor.action.commentLine`
* `editor.action.commentLine` is bound by default to the key code binding `` cmd+/ ``
* `` / `` can be produced through one scan code: ``[BracketLeft] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24289204/8d252324-1080-11e7-8673-117644913213.png)
* therefore, the action is bound by default to: ``Cmd+[BracketLeft] `` i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24289222/a2172bb0-1080-11e7-8d08-512fc7feefaa.png)

---
I have validated that pressing `` Cmd+[BracketLeft] `` does indeed toggle line comment.

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue.

**Closed by alexandrudima** 2017-03-24 10:07 UTC
Labels: keybindings, keyboard-layout, mac, question
