### ISSUE TITLE
Minimap: click and drag

### ISSUE THREAD

**Issue by Katarn** [Microsoft/vscode#59582] opened 2018-09-27 21:23 UTC
Similar to the behavior in Sublime Text. Click on any place of the minimap (inside or outside of current view zone) and, without releasing the left mouse button, move mouse the cursor up and down for the scroll.

In Sublime Text it setup with ``minimap_scroll_to_clicked_text`` option. See also https://stackoverflow.com/questions/20310107/sublime-text-3-minimap-click-and-drag

**Comment by rebornix** [comment] 2018-10-01 15:46
Duplicate of https://www.github.com/Microsoft/vscode/issues/24395

**Closed** 2018-10-01 15:46 UTC
Labels: *duplicate, editor, editor-minimap, feature-request
