### ISSUE TITLE
Git diff view uses custom editors

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#185929] opened 2023-06-22 23:36 UTC
When you are a custom editor author for types of files that renders them using a webview it also uses these by default when rendering in the git diff view.  This doesn't show the "diff" traditional view of underlying raw data in the case of non-binary information.

Is there a way to have a custom editor NOT be the default for the git diff view?

**Comment by mjbvz** [comment] 2023-06-23 00:25
Duplicate of #138525

**Closed by mjbvz** 2023-06-23 00:25 UTC
