### ISSUE TITLE
Provide an option to enable DirectWrite

### ISSUE THREAD

**Issue by luca-moser** [microsoft/vscode#1896] opened 2016-01-09 18:42 UTC
I am using VS Code on a 4k monitor (ASUS PB287Q 4K) and have set Windows 10's scaling on that monitor to 150%. VSCode fonts inside the editor are extremely blurry.

Look at this example (scaling in Windows 10: 150%, `editor.fontSize:`: 13, `window.zoomLevel`: 0):
<img width="491" alt="vc4k_blurry" src="https://cloud.githubusercontent.com/assets/1385611/12217686/62dd6400-b708-11e5-9faa-e93d617d6ee9.PNG">

The code in the background is very blurry (please open the image in a new tab to really see it), while the dialog in the foreground is not (just for comparison).

I tried to play around with the `edtior.fontSize`/`window.zoomLevel` options, but there isn't any way to get the font crisp. Using `--disable-direct-write` and `--force-device-scale-factor=1.0` to start VS Code also doesn't fix the issue.

**Comment by ricmed205** [comment] 2016-01-09 19:22
+1

**Comment by alexandrudima** [comment] 2016-01-12 09:58
cc @egamma 

@bpasero Looking at atom/electron#3349 looks like we still have a blurry font issue on windows until we adopt an Electron version with Chrome 47 -- the patch of Electron v0.34.4 only covers Linux.

**Comment by bpasero** [comment] 2016-01-12 10:14
@alexandrudima yup

**Comment by kanreisa** [comment] 2016-01-13 23:04
:+1:

**Comment by SeriousM** [comment] 2016-02-09 10:27
Any updates on that?
The blurriness is really annoying!

_(notice the blur-effect on two different documents)_
![image](https://cloud.githubusercontent.com/assets/462013/12913582/ea58154a-cf1f-11e5-9825-9c16337c14c2.png)

**Comment by bpasero** [comment] 2016-02-09 10:35
We can only solve this by updating Electron to a newer version but currently are blocked because of a native node crash.

**Comment by luca-moser** [comment] 2016-02-09 10:37
For reference, he is talking about https://github.com/atom/electron/issues/4299

**Comment by pprice** [comment] 2016-02-21 21:28
FWIW, this is also true on OSX (10.11.3) with 96 DPI monitors, but setting the zoom level to vscode to anything other than default (e.g. I have `"window.zoomLevel": 1`). 

It appears to be related to 'subpixel' scrolling of the editor text area. Might be different issue, however.

**Comment by iHuahua** [comment] 2016-03-03 07:20
i think the issue should be fixed by electron, Chrome has no problem.
 so, u can set the monitor's scaling to 100%, and font size 20+, it‘s very clear, just look like MAC retina.

**Comment by luca-moser** [comment] 2016-03-03 07:52
@iHuahua that is definitly **not** a workaround. Having a Windows 10 installation on a 4k monitor without scaling is absolutely tedious to say the least (I'd like to preserve my eyesight for the next years...).

**Comment by artsjedi** [comment] 2016-03-10 23:25
I just found the problem found a "translate3d" CSS transform that makes it blurry.
I disabled the CSS and it becomes SHARP!!! take a look

![blurry text](https://cloud.githubusercontent.com/assets/2263037/13688059/0b717b36-e6fe-11e5-843b-42f9b83195e0.png)

**Comment by bpasero** [comment] 2016-03-11 06:12
Interesting, so you say the explorer is always sharp but the editor is not for you?

**Comment by artsjedi** [comment] 2016-03-11 13:45
exactaly. and It realy seems to be a GPU rendering issue.
Removing the"translate3d" CSS transform (GPU Process) it becomes sharp.
Starting code with "--disable-gpu" too.

**Comment by alexandrudima** [comment] 2016-03-17 23:06
@artsjedi What settings are you using and what theme is that?

**Comment by artsjedi** [comment] 2016-03-17 23:19
@alexandrudima default dark theme. using windows 10, febury updated,  on surface pro 3. 2016-02 build.

**Comment by bpasero** [comment] 2016-04-21 06:34
We pushed a major update to the UI framework to our insiders release and would appreciate feedback if this issue got resolved. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!

**Comment by phraemer** [comment] 2016-04-21 08:26
Unfortunately not on Windows 10
150% text size on a 3840x2160 monitor.

![image](https://cloud.githubusercontent.com/assets/143631/14702518/34985598-07ab-11e6-9ed7-b91152109772.png)

**Comment by lediur** [comment] 2016-04-21 20:55
On a Surface Pro (150% scaling) attached to an external monitor (100% scaling), 1.0.1-insider still has blurry UI elements.

**External monitor (100%)**
<img width="420" alt="scaled-to-100" src="https://cloud.githubusercontent.com/assets/1077648/14723897/240986c6-07c8-11e6-9214-74e8fff81ec6.PNG">

**Surface Pro screen (150%)**
<img width="420" alt="scaled-to-150" src="https://cloud.githubusercontent.com/assets/1077648/14723948/5ce83a28-07c8-11e6-9cb5-f8f4ffd3dc55.PNG">

For comparison, on `1.0.0`:
**External monitor (100%)**
<img width="358" alt="1 0 0-100" src="https://cloud.githubusercontent.com/assets/1077648/14724002/a0d5cbe2-07c8-11e6-95bf-18166d5c192c.PNG">

**Surface Pro screen (150%)**
<img width="358" alt="1 0 0-150" src="https://cloud.githubusercontent.com/assets/1077648/14724026/bac0a220-07c8-11e6-891b-1dac5838fbdb.PNG">

**Comment by oncethyme** [comment] 2016-04-21 21:58
Here's a simple comparison of the still-reproing Insiders build with a regular build that uses the "--disable-gpu" workaround suggested by @artsjedi.
<img width="553" alt="comparison of blurry and clear" src="https://cloud.githubusercontent.com/assets/1475660/14725536/5572f4dc-07d1-11e6-8a22-24fd301c3388.PNG">

**Comment by jasonnian1978** [comment] 2016-04-21 22:02
- `[

- [ ] 1. 

](url)`

**Comment by lediur** [comment] 2016-04-22 02:42
`--disable-gpu` doesn't work for me - still exhibits the scaling bug:

![image](https://cloud.githubusercontent.com/assets/1077648/14730198/3b691a8a-07f9-11e6-88f3-c1fc3e7bc405.png)

**Comment by MannikJ** [comment] 2016-04-28 14:51
I am also facing the same problems. Running with `--disable-gpu` doesn't help it my case too. It is a really strange bug, as the blurryness only occurs in special situations and files. For example I just pasted something into a perfectly sharp looking editor tab which then turned blurry. Other editor tabs/files remained sharp. Closing and reopening the file as well as restarting VS Code didn't help. The blurryness is somehow file-related.
I also tried to start VS Code with the compatibility option 'Disable Display Scaling On High DPI Settings', because scaling is a known issue on Windows 10 with small screens and high resolutions, without any success.

**Comment by alexandrudima** [comment] 2016-04-28 16:09
@MannikJ Can you please try our insiders build https://code.visualstudio.com/download?insiders=true where we have already adopted Electron v0.37.6 which includes Chromium 49 and try if things improved.

**Comment by madispe** [comment] 2016-04-28 22:11
I was experiencing the same issue on Windows 7 with 150% scale.

In my case the fonts are now sharper with the latest insiders build when running with the `--enable-use-zoom-for-dsf` switch. I'm using the same switch (as a flag) on Chrome browser too, to fix the (probably) same issue ([crbug.com/485650](http://crbug.com/485650)).

If I add the `--disable-gpu` switch too, the code editor font is even sharper (subpixel antialiased!), but reverts back to grayscale antialiased when I scroll.

Also, there is an additional tiny blur that alternates on and off with each pixel scrolled (probably an unrelated round off error with translate transform).

Anyway, things are definitely better.

**Comment by MannikJ** [comment] 2016-04-29 15:08
Adding both flags madispe suggested also seem solve problems with the latest stable version. No need for the Insiders build as far as I see. But I didn't test it excessively. Maybe the problems will come back.

**Comment by luca-moser** [comment] 2016-04-29 16:01
Surface Pro 4, Windows 10, 4k Monitor with 150% scaling. Even with both flags enabled, it looks still a little bit blurry to me when I compare it with the "About" message box.

1.1.0-insider without any flags:

![image](https://cloud.githubusercontent.com/assets/1385611/14921724/e9726254-0e33-11e6-8c0c-addbde4a5f99.png)

1.1.0-insider with `--disable-gpu`:

![image](https://cloud.githubusercontent.com/assets/1385611/14921713/d52fc8a4-0e33-11e6-8986-b77c9e2d253a.png)


1.1.0-insider with `--disable-gpu` and `--enable-use-zoom-for-dsf`:

![image](https://cloud.githubusercontent.com/assets/1385611/14921705/c8db0dfc-0e33-11e6-914e-67c9ec734835.png)

**Comment by lediur** [comment] 2016-04-29 17:07
Okay, with `--enable-use-zoom-for-dsf`, it seems to be a different font rendering issue. It seems to be a character horizontal Anti-aliasing bug, rather than a blurry scaling bug. The font is clear on a Surface Pro 3 screen, but it could just be the higher DPI masking the issue.

With `--enable-use-zoom-for-dsf` at 100% scaling, external monitor (150% native):
![100-external](https://cloud.githubusercontent.com/assets/1077648/14923415/05ad51dc-0df2-11e6-957d-2acb7f3c4707.png)

With `--enable-use-zoom-for-dsf` at 150% scaling, Surface Pro 3 screen:
![150-sp3](https://cloud.githubusercontent.com/assets/1077648/14923426/114212a8-0df2-11e6-8de8-722d2c7ee645.png)

All pictures scaled 600% to reveal pixel detail.

**Comment by ppyupp** [comment] 2016-05-04 07:48
I have the same problem...

**Comment by lediur** [comment] 2016-05-14 19:46
I did discover a bug when using `--enable-use-zoom-for-dsf`: dragging items in the file explorer is dramatically shifted, like the event handlers are not scaled with the UI. This causes issues when trying to move things around, but it can be worked around.

**Comment by felixrieseberg** [comment] 2016-08-10 15:52
It's worth pointing out that Chromium M53 will [enable "use zoom for dsf" by default](https://codereview.chromium.org/2173243002/patch/1/10001), meaning that this change should eventually trickle down to VSCode via Electron.

**Comment by kyssproject** [comment] 2016-08-18 09:14
The same to me, 4K 27" LG display, where some files are blurry and some others are not (which I can switch in the same session, kind of weird).

I didn't enabled any flag, I am reading this thread now and here I have a 1080p display, but I am using the last 1.4.0 version (I assume the stable branch).

**Comment by MuhsinFatih** [comment] 2016-09-24 21:29
hasn't this been fixed yet? I am on a macbook pro retina bootcamp installed and in bootcamp it is exactly the same, blurry. version 1.5.3

**Comment by konistehrad** [comment] 2016-09-25 03:12
@MuhsinFatih AFAIK this is waiting on an Electron update to bring Chromium up to 53, such that `enable-use-zoom-for-dsf` is enabled by default for Windows and Linux (sampled above in https://github.com/Microsoft/vscode/issues/1896#issuecomment-215815482). Electron updates are, unfortunately, blocked on upstream https://github.com/electron/electron/issues/5715, but progress can be tracked in https://github.com/Microsoft/vscode/issues/12519.

**Comment by epicbugs** [comment] 2016-09-29 17:25
Had the same problem, Windows 10 Professional, Intel HD 520, and Dell U2715H, all with latest drivers. Fixed it with ` --disable-gpu --enable-use-zoom-for-dsf`. Thank you for sharing the workarounds. I was nearly prepared to have my monitor switched out.

**Comment by xt0rted** [comment] 2016-10-04 05:44
Had the same problem on Win10 Pro with a GTX 1080 and Dell P2715Q @ 150% scaling. Adding `--enable-use-zoom-for-dsf` to my shortcut fixed the blurriness.

This also fixed the blurriness I was getting in the Slack app, so if you're using any other Electron based apps this may carry over to those as well. I didn't notice a difference in the Azure Storage Explorer though.

**Comment by wkrueger** [comment] 2016-10-04 14:43
Font gets blurry when attepting to set a higher font weight.
OSX 1280x800
![captura de tela 2016-10-04 as 11 16 22](https://cloud.githubusercontent.com/assets/2209181/19077759/3424b682-8a24-11e6-86ac-fa6887a35872.png)
![captura de tela 2016-10-04 as 11 19 04](https://cloud.githubusercontent.com/assets/2209181/19077834/65e71386-8a24-11e6-8cb1-13074f606c7b.png)

**Comment by Matthias247** [comment] 2016-10-11 09:24
I tested yesterday evening if 1.6 with the Electron update improves the situation. Unfortunately it's still blurry for me.

Rendering is however perfect with adding `--disable-gpu --enable-use-zoom-for-dsf` to startup. Only adding `--enable-use-zoom-for-dsf` does not fully resolve the issue for me.

**Comment by madispe** [comment] 2016-10-11 16:26
Currently, `--enable-use-zoom-for-dsf` launch argument with `"window.zoomLevel": -0.001` setting seems to remove all issues for me. Perfect cleartype rendering on 150% OS scaling which doesn't disappear when scrolling (that's what the zoomLevel is for).
There is a slight blurry twitching on text when hovering over the gutter and the collapse / expand buttons appear.
With a negative value the twitching seems to be less visible.

**Comment by pdefreitas** [comment] 2016-10-26 10:54
Seems to be not just an windows issue, as per Issue #122.

**Comment by alexandrudima** [comment] 2016-10-26 12:13
I have tried briefly a few months ago some other Chromium flags (`--high-dpi-support=1 --force-device-scale-factor=1`) which seemed to help (i.e. disable Chromium automatic zoom)

**Comment by sevilayha** [comment] 2016-11-02 22:02
Running the new VS Code 1.7 and still got blurry text at 150% zoom on a 1920x1080 monitor on Win10.

`--disable-gpu and --enable-use-zoom-for-dsf` did the trick though.

**Comment by HipsterZipster** [comment] 2016-11-15 06:00
blurry text here as well, running inside Windows 10 anniversary on a macbook pro retina

**Comment by Ciantic** [comment] 2016-11-22 13:40
I'm quoting a @felixrieseberg from Atom's similar discussion:

> It's worth pointing out that Chromium M53 will enable "use zoom for dsf" by default, meaning that this change should eventually trickle down to Electron and fix a lot of the blurriness discussed here.

Electron version [1.4.7 seems to be at Chromium: 53.0.2785.143](http://electron.atom.io/), so only thing required by VSCode devs is to update the Electron?

**Comment by konistehrad** [comment] 2016-11-22 16:13
@Ciantic This appears to be happening. https://github.com/Microsoft/vscode/issues/15811 is the test plan.

**Comment by Ciantic** [comment] 2016-11-23 09:36
@konistehrad I tried with VSCode insiders, which is at 1.4.6. The DPI scaling does not work in it. I don't know on which version of Electron it is supposed to work. But 1.4.7 is at least Chrome M53.

**Comment by Ciantic** [comment] 2016-11-23 09:55
I did some more tests:

`"c:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" --high-dpi-support=1 --force-device-scale-factor=1.5`

This scales the window correctly, but then it uses Windows 150% factor on top of it, doubling it to blurry 150%.

It doesn't help if I disable the scaling for VSCode compatiblity settings, because then the above command line switches stops working.

Something is wrong with this electron version.

**Comment by Ciantic** [comment] 2016-11-23 10:53
Unfortunately I just figured out that 1.4.x is not going to solve this. I tried with 1.4.8 on my own Electron app and it didn't work.

I don't know does it make a difference but I tested with desktop scaling on a different desktop. This is a different issue apparently: https://github.com/Microsoft/vscode/issues/6196

Also I opened a electron bug:
https://github.com/electron/electron/issues/8062

I think this bug (and the other one) has nothing to do with VSCode basically. Adding to these threads will not make a difference.

**Comment by Matthias247** [comment] 2016-11-23 16:46
I also figured out that the severness of this bug also depends on how many monitors are connected. At home I got a single 4k screen @175% scaling. This is slightly blurry, but the blurness goes away with the often mentioned commandline params.

However at work I now also have an external 4k screen (@175% scaling), but addtionally on that PC also a normal screen with 100% scaling and the notebooks inbuilt screen (I think 125% scaling). In this constellation Code is extremely blurry on the 4k screen and the commandline params also don't help. If I boot with only a single screen it again behaves like my home setup (so this isn't related to graphic card drivers or similar issues).

**Comment by Tsmith18256** [comment] 2016-11-24 21:15
This happens if your 4K monitor is not your primary display. I just picked up a 4K monitor and have the following hooked up to my computer (Windows 10):

* 1080p 144hz monitor (which I had set as the primary)
* UHD/4K 60hz monitor @ 200% scaling

I had blur issues with a lot of programs that claimed they should work fine, such as Android Studio. VS Code was also blurry. I made the 4K monitor my primary and everything is super sharp now. Note that you need to log out and back in to Windows for this to take effect, but Windows should tell you that when you change primary monitors.

**Comment by fredrikaverpil** [comment] 2016-11-29 09:30
Thanks @madispe - setting `"window.zoomLevel": -0.001` in my user settings made the text sharp on my setup (Win 10, ASUS 4k dual monitors).

**Comment by LeoLozes** [comment] 2016-11-30 14:03
@Tsmith18256 did you manage to have VSCode being 100% sharp in both displays?

I have the same setup (1080p 22" external monitor, 4k 13" laptop (primary)), and while VS Code is super sharp in the 4K, the 1080p monitor is still a bit blurry . 

I think it has to do with the SetThreadDpiAwarenessContext API added in the [Windows 10 anniversary update](https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update), which is probably not implemented in Electron.

**Comment by Tsmith18256** [comment] 2016-11-30 18:14
@LeoLozes It looks pretty normal on the 1080p, maybe a bit blurry. I definitely don't think it's handling it properly though, it's just since I am using 200% scaling it can divide the pixels in half fairly clean when downsampling. At 150% it might be more noticeable.

I have pretty much concluded that it only works properly on the primary monitor though, which is common to most IDEs for the moment from what I've been seeing so far.

**Comment by Ciantic** [comment] 2016-11-30 20:19
Electron is at Chromium 53. Which is not DPI aware on multi-display setups, 54 version of Chromium is.

Read e.g. this thread: https://productforums.google.com/forum/#!topic/chrome/FLXs5lYQyBY 

> In Chrome 54, we've fixed many of these bugs and re-enabled support for 125% scale. As a result, Chrome's UI (i.e. icons, address bar, etc.) will appear larger than before when your system is set to 125% scale because it is now displaying properly.

If you've got Chrome 54 (stable) installed, it can be easily seen, even it's developer tools window scales nicely in multi-display setups, unlike in Chrome 53.

**Comment by Matthias247** [comment] 2016-12-15 16:57
New version, new report :)

By default it's still blurry :'(
The known `--disable-gpu --enable-use-zoom-for-dsf` commands improves it a little bit, but I have the feeling that is has less impact than on the last version. However setting `"window.zoomLevel"` as recommended here seems to have bigger positive impact for me than in the last version. So I will let this stay on. It's interesting how this setting actually impacts the font rendering. Fonts seem less tall but sharper. And from the screenshots I just made I guess that with the zoomLevel setting I get subpixel anti-aliasing, without it greyscale anti-aliasing.

**Comment by mizzao** [comment] 2016-12-21 19:14
According to this post (https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update/) Win 10 anniversary makes it easier for programs to rescale themselves in response to DPI changes (e.g. docking a Surface with a monitor, etc.)

The following image from that post captures the reason for most blurriness in my day-to-day:

![](https://msdnshared.blob.core.windows.net/media/2016/08/Picture111.png)

Is there a way to have VS code detect these DPI changes and render accordingly?

**Comment by Tsmith18256** [comment] 2016-12-24 01:05
As a followup to my comment before about it working if the scaled monitor is the primary, I am noticing an issue that either wasn't happening or I wasn't noticing before. I have a file that is displaying very sharp, but when I scroll down 1 notch it goes blurry. It's alternating between blurry and clear every time I move one notch on the scroll wheel.

It seems to be doing this at any font size.

**Comment by scotte** [comment] 2016-12-28 21:33
I'm not sure if it's exactly related, but text in vs code becomes blurry if I leave the window idle for a bit - moving the pointer or touching the keyboard sharpens text right back up. Curiously, text blur isn't consistent across the window - it tends to be sharp in the upper-left, and blurry nearer the bottom-right. Very weird.  --disable-gpu seems to resolve it.

**Comment by OfekA** [comment] 2017-02-07 22:34
@scotte I have the same exact issue. Also resolved using --disable-gpu.

**Comment by JohannesRudolph** [comment] 2017-02-10 09:17
What's the status of VSCode pushing this with the electron guys (as probably one of their largest downstream consumers)?

**Comment by keathmilligan** [comment] 2017-02-24 17:11
Just to add a little more characterization to this issue:

With an LG 4k attached as an external display on a Windows 10 laptop:
- if the external monitor _is not_ set to be the primary display, VSCode is blurry and none of the suggested command-line options or settings have any visible effect.
- if the external monitor _is_ set to be the primary display (you have to log out and back in for this to fully take effect), VSCode is nice and crisp.

This works at all scaling levels. With the external display set as main, I notice that other apps, like Outlook, Word, etc. are now slightly blurry on the laptop's built-in display even though it is set to 100% scaling.

**Comment by martinsuchan** [comment] 2017-02-27 08:59
As far as I know, this will be fixed once Electron update based on Chromium 54+ is released. Currently the latest release 1.4.15 is still based on Chromium 53, but Electron 1.5.0/1.6.0 based on Chromium 55/56 should be ready soon, see https://github.com/electron/electron/releases

**Comment by hosein71** [comment] 2017-03-02 13:59
And for more information, `--disable-gpu --enable-use-zoom-for-dsf` didn't help. 2K monitor.

**Comment by balupton** [comment] 2017-03-03 03:51
So I use the `Monoid-Retina` font, which is blurry. However, I found the following fixed it.

In Atom I had:

```
// make text look better
.platform-darwin .workspace  {
	-webkit-font-smoothing: none;
	-webkit-font-smoothing: antialiased;
	-webkit-font-smoothing: subpixel-antialiased;
	// -webkit-text-stroke: 0.015em;
	text-rendering: auto;
	text-rendering: optimizeSpeed;
	text-rendering: optimizeLegibility;
	text-rendering: geometricPrecision;
}
```

And turns out you can apply it to Visual Studio Code v1.10.1 by editing:

```
Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css
```

and inserting at the end:

```
.monaco-editor {
	-webkit-font-smoothing: none !important;
	-webkit-font-smoothing: antialiased !important;
	-webkit-font-smoothing: subpixel-antialiased !important;
	text-rendering: auto !important;
	text-rendering: optimizeSpeed !important;
	text-rendering: optimizeLegibility !important;
	text-rendering: geometricPrecision !important;
}
```

Here is the screenshot comparison.

Before:

![screen shot 2017-03-03 at 11 46 26 am](https://cloud.githubusercontent.com/assets/61148/23537505/975955d8-0007-11e7-9b67-e8ae04fec549.png)

After:

![screen shot 2017-03-03 at 11 46 54 am](https://cloud.githubusercontent.com/assets/61148/23537511/9ad24684-0007-11e7-8b84-c6eae9a8a8ca.png)


However, Visual Studio Code will then whine about a corruption issue, but you can just click "don't show again"

**Comment by essuraj** [comment] 2017-03-04 04:59
![clipboard image 4 march 2017](https://cloud.githubusercontent.com/assets/1737617/23576209/f6668574-00c4-11e7-85a6-4b5c7bfcfc4d.jpg)

this is on a 1080p screen, the blurryness goes away on focus and comes back slowly. feels like vscode is streaming video ;p .

does it have to do with multimonitor or 2 hybrid gpu ..

my laptop has an monitor attached.
its on an i7 4700 mq 
intel 4600
nvidia gt740m
seems im on hdmi and on intel driver by default.

**Comment by rfgamaral** [comment] 2017-03-07 14:17
The [above workaround[(https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289) does not work for me. I have a single 1080p monitor and I'm using Windows 10. All the fonts in the editor, tabs, statusbar, sidebar, etc are a bit blurry compared to something like Sublime Text.

This actually bothers me a bit and I haven't found a way to work around this. It seems that most CSS hacks don't work with the latest Chrome/Electron versions.

**Comparison screenshot:**
![vscode-sublime-font-comparison](https://cloud.githubusercontent.com/assets/96476/23660177/7cb2ee38-0340-11e7-8442-c2a782291f97.png)

It's not that big a difference but Sublime Text font rendering is slightly sharper. The same thing happened when Visual Studio IDE changed from a Windows Forms implementation to a WPF one (it was eventually fixed/improved).

Is this ever going to be fixed/improved?

**Comment by aleksey-bykov** [comment] 2017-03-10 18:22
my 3 cents i have 2 monitors: a laptop at 125% resolution and my desktop at 100%, so the very same window with VS Code:
- i see everything crisp on laptop 
- i see it blurry when i move it to the desktop (when moved slowly at some point it gets blurry, moving it back gets it crisp)

setting the desktop to 125% solved problem

**Comment by samirotiv** [comment] 2017-03-26 19:18
Wish this issue didn't exist. It's hard to pinpoint exactly when, but after scrolling, if I reach a certain position, fonts in the text editor are distinctly blurred compared to the fonts in the file explorer pane.

It happens when I'm in deep thoughts, so I'm too involved to take a screenshot. Will do so the next time it happens.

Is there an an ongoing effort to move VS Code to the newer version of Electron/Chromium? Does Atom use the latest version?

**Comment by bpasero** [comment] 2017-04-10 17:08
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by luca-moser** [comment] 2017-04-10 18:07
My second Screen attached through the Surface hub is blurry. The main screen isnt't.

No flags (ASUS PB287Q 4K - 150% Windows scaling):
![image](https://cloud.githubusercontent.com/assets/1385611/24875431/4d9b6960-1e28-11e7-9e9f-e85f952870b1.png)

--disable-direct-write (ASUS PB287Q 4K - 150% Windows scaling):
![image](https://cloud.githubusercontent.com/assets/1385611/24875512/926a4cf0-1e28-11e7-906c-a43310249bde.png)

--disable-gpu (ASUS PB287Q 4K - 150% Windows scaling):
![image](https://cloud.githubusercontent.com/assets/1385611/24875551/bdfea30c-1e28-11e7-8e38-a9798aac5780.png)

No flags main Screen (Surface pro 4 - 150% Windows scaling):
![image](https://cloud.githubusercontent.com/assets/1385611/24875633/08bcc69e-1e29-11e7-860c-de200778a562.png)

**Comment by brightghost** [comment] 2017-04-11 23:59
Wow. In my case, this issue is almost entirely resolved by changing the 'Primary display' per @keathmilligan 's suggestion  (https://github.com/Microsoft/vscode/issues/1896#issuecomment-282347176). My external display is not 4K, I think it's what they are calling 2K, and the laptop has a similar resolution but higher density. No scaling settings were able to get clear text in VS Code on the external display. My laptop was set as the primary display simply for taskbar location and window spawning purposes; I had no idea this setting has any bearing on the scaling algorithm, and have not seen this anywhere documented, but changing this little setting made a night and day difference. The text is now slightly less clear than I would like on the laptop display, but sharp as a tack on the larger one.

**Comment by seanzer** [comment] 2017-04-12 02:24
If it's only clear on your primary display, then it might be because the manifest does not specify per monitor dpi aware. Electron is gonna eventually fix it https://github.com/electron/electron/pull/8786

**Comment by essuraj** [comment] 2017-04-17 15:41
i used the vendor provided graphics driver(intel) and i dont have blurry text in my extended monitor setup

**Comment by balupton** [comment] 2017-05-05 06:23
seems v1.12.1 broke my fix at https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289

**Comment by syabro** [comment] 2017-07-14 20:44
A command to apply @balupton fix
```
echo ".monaco-editor {-webkit-font-smoothing: antialiased \!important;text-rendering: optimizeLegibility \!important;}" >> "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css"
```

**Comment by alexandrudima** [comment] 2017-11-24 14:37
From all these screenshots, it looks like every font is blurry in most cases: the menu, the explorer, and the editor => removing editor label.

**Comment by druellan** [comment] 2018-01-30 14:02
I've just noticed this, not sure if could be related, but could be an electron thing:
When I switch focus from the editor, fonts get "blurry" for a moment:

![code_change_alias](https://user-images.githubusercontent.com/6965667/35569955-7fbe36ae-05ac-11e8-9b3f-87ed91d675e9.gif)

I'm using:
Code: 1.20.0-insider
Windows 10.1709
Intel Display Driver: 20.19.15.4835
Display scaling: 125%

**Comment by essuraj** [comment] 2018-02-07 10:52
@druellan does this happen on a second monitor?

**Comment by druellan** [comment] 2018-02-08 13:08
No, but I think this can be something related to Win10 in general, since some dialogs also have this effect, so, disregard my comment for now. Thanks!

**Comment by DanTup** [comment] 2018-02-11 14:51
I'm not sure this is specific to Windows; here's screenshots of VS Code (1.20.0) from my MacBook (Mac OS High Sierra) connected to a monitor. Left is the MacBook (2017 12" MacBook) screen and right is the external screen (an LG 29" 1080p Ultrawide).

<img width="1176" alt="screen shot 2018-02-11 at 14 46 27" src="https://user-images.githubusercontent.com/1078012/36074612-8b12a494-0f3a-11e8-8047-717e76a082b0.png">

As mentioned above; it's not just the editor, all of the text including tabs and explorer are blurry on the external screen. Happens even if I launch Code on the second display, so I don't think it's related to dragged the window from one to the other.

**Comment by seppemarotta** [comment] 2018-02-13 14:21
I fixed my resolution enabling "Disable display scaling on high DPI settings" under the preference tab of Visual Studio Code Properties.
![fix](https://user-images.githubusercontent.com/3663789/36154360-353f9002-109f-11e8-81a7-a02dd99261b3.PNG)

**Comment by alien2003** [comment] 2018-03-27 08:49
The same thing on Manjaro

**Comment by anacondaqq** [comment] 2018-04-06 17:48
This is the very strange thing, that people trying different solutions related to GPU, and did not realize that the issues in some cases (I can confirm that) with Nvidia control panel and FXAA

Try to play with Antialiasing FXAA option if you have Nvidia graphics card, and the issue will be solved.
What about internal graphics cards on resolutions nonstandart and not native (not 1080p with any scaling) thanks to direct-write bugs you will have blurry text. I don't know if someone will be able to fix this blurry text in direct-write, and will be greatly grateful if someone shares it to me because it fills fix tons of issues with other apps based on the electron.

**Comment by anacondaqq** [comment] 2018-05-07 18:11
@alien2003 Sorry, I do not know.  But my comment is correct, and I can, again and again, confirm that.
On Windows 1804 the situation MUCH MUCH better with font rendering.

**Comment by jacob-arlington** [comment] 2018-05-13 12:13
I solved this with update my driver and set 

conservative morphological anti-aliasing  to off

https://goo.gl/JvW9Z5

**Comment by alien2003** [comment] 2018-05-14 11:35
@jacob-arlington how to do it on Manjaro Gnome?

**Comment by jacob-arlington** [comment] 2018-05-14 12:03
@alien2003 what is your graphic card?

**Comment by alien2003** [comment] 2018-05-14 13:43
@jacob-arlington Intel® HD Graphics 620 (Kaby Lake GT2)

**Comment by bpasero** [comment] 2018-09-10 16:31
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by anacondaqq** [comment] 2018-09-10 16:55
@bpasero the problem with DirectWrite on windows. If you have a way to return back DirectWrite flag (chrome://flags) like on CentBrowser to turn off DirectWrite and render all text via GDI+ the solution will solve the issue.

**Comment by unode** [comment] 2018-10-29 20:32
I'm experiencing a similar issue in Linux although in this case it seems to be due to a non-uniform aliasing effect across the screen.

The following are 2 screenshots taken on:
![screenshot_2018-10-29_21-08-48_875055699](https://user-images.githubusercontent.com/122319/47677232-df371b80-dbbe-11e8-87f8-a1a5cfd0912a.png)

The font used is [`Envy Code R`](https://www.fontsquirrel.com/fonts/envy-code-r) at 2 different sizes:
 
Size `13`:
![screenshot_2018-10-29_21-28-44_890043110](https://user-images.githubusercontent.com/122319/47678268-a8163980-dbc1-11e8-8d05-7e24c30ad05e.png)

Here you can see a rainbow-like effect across the screen. The pattern changes every `14` characters cycling 4 different color patterns. `green`, `orange`, `violet`, `blue`, `green`, ...
`m` was used as it makes the aliasing effect more noticeable.

Size `14`:
![screenshot_2018-10-29_21-03-33_971367519](https://user-images.githubusercontent.com/122319/47677097-836c9280-dbbe-11e8-9c7a-d8a2b9852c7a.png)
Similar situation but here the rendering cycles every character and contrary to the previous it alternates between 2 patterns only.

Using `--disable-gpu` has no effect.

In contrast the same font and size on `rxvt-unicode` displays no such artifacts:
![screenshot_2018-10-29_21-24-43_615369488](https://user-images.githubusercontent.com/122319/47678087-2cb48800-dbc1-11e8-88b6-b4b64bb183ea.png)

What is even more disturbing is that the font renders perfectly in the _embedded terminal_:
![screenshot_2018-10-29_21-27-01_512520030](https://user-images.githubusercontent.com/122319/47678225-8c129800-dbc1-11e8-8439-329a5f64e45f.png)
Even better than in `rxvt-unicode` (IMO).

**Comment by bpasero** [comment] 2019-10-09 18:35
Given https://github.com/microsoft/vscode/issues/15211#issuecomment-540048507 there will be a way to configure Chrome command line switches to be used on each startup. If there is a specific flag that makes the situation better for users, please let me know and we can think about supporting it there.

Otherwise I would like to close this issue as it seems not actionable from the VSCode side of things.

**Closed** 2019-10-15 06:36 UTC
Labels: electron, font-rendering, needs more info, upstream

**Comment by jeanabraham** [comment] 2019-11-27 14:35
> I'm not sure this is specific to Windows; here's screenshots of VS Code (1.20.0) from my MacBook (Mac OS High Sierra) connected to a monitor. Left is the MacBook (2017 12" MacBook) screen and right is the external screen (an LG 29" 1080p Ultrawide).
> 
> <img alt="screen shot 2018-02-11 at 14 46 27" width="1176" src="https://user-images.githubusercontent.com/1078012/36074612-8b12a494-0f3a-11e8-8047-717e76a082b0.png">
> 
> As mentioned above; it's not just the editor, all of the text including tabs and explorer are blurry on the external screen. Happens even if I launch Code on the second display, so I don't think it's related to dragged the window from one to the other.

@DanTup I'm noticing the same with my macbook vs ultrawide monitor. However, I find that the fonts of my Terminal window are extremely clear even on the ultrawide. Were you able to figure out how to make the text sharp on VScode by any chance? Thanks!

**Comment by DanTup** [comment] 2019-11-27 15:11
@jeanabraham I didn't figure it out - I tend to always use VS Code directly on the MacBook screen instead. My terminal is also fuzzy on the external screen - though I remember seeing some popup about terminal performance once offering to change renderer - I don't remember if I agreed or not, but maybe that's a reason for a difference.

**Comment by jeanabraham** [comment] 2019-11-29 13:32
@DanTup thanks! Ok. I decided I'll just trade in my ultrawide for 4k instead!

**Comment by DanTup** [comment] 2019-11-29 13:45
It's kinda funny that that might be the easiest fix 😄
