### ISSUE TITLE
Terminal windows turn black after resuming from hibernation on Ubuntu

### ISSUE THREAD

**Issue by bsdz** [microsoft/vscode#119554] opened 2021-03-23 07:17 UTC
Issue Type: <b>Bug</b>

After resuming from hibernation all vscode windows with open terminals show teminals as solid black blocks with no text visible. The cursor (a small white box remains). Clearing a terminal (CTRL + L) does not help. The only workaround currently is to close terminals and re-open. This often means restarting any running processes, reconnecting any container logging sessions, etc.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-66-generic snap
Remote OS version: Linux x64 5.4.0-66-generic
OS dist: Ubuntu 20.04.2 LTS

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2920X 12-Core Processor (24 x 2079)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|31.29GB (18.46GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 3189f488-8034-4bff-893e-03f7a494861b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Cron Server|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|AMD Ryzen Threadripper 2920X 12-Core Processor (24 x 2079)|
|Memory (System)|31.29GB (18.46GB free)|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943:30277001
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

# Screenshot before hibernation:

![image](https://user-images.githubusercontent.com/6608130/112108293-e99b4b00-8ba7-11eb-8c0b-cff35ce92280.png)

# Screenshot after resuming from hibernation:

![image](https://user-images.githubusercontent.com/6608130/112108305-ed2ed200-8ba7-11eb-9cc3-c0eaa032568e.png)

**Comment by meganrogge** [comment] 2021-03-29 15:18
Duplicate of #69665

**Closed** 2021-03-29 15:19 UTC
Labels: *duplicate, bug, integrated-terminal
