### ISSUE TITLE
Scrolling hover popup with keyboard

### ISSUE THREAD

**Issue by akshaal** [microsoft/vscode#69836] opened 2019-03-05 11:23 UTC
It's already possible to create a keyboard shortcut to trigger a hover popup window with keyboard.. But mouse is still required to scroll the windows.

**Comment by sandy081** [comment] 2019-03-06 08:54
Hmm interesting, I did not know that there is a shortcut to open hover :)

**Comment by sandy081** [comment] 2019-03-06 08:58
We never focus hover and any key press or mouse move will hide the hover. 

@alexandrudima Moving this to you, let me know if I have to do anything.

**Comment by akshaal** [comment] 2019-03-06 09:04
```
{
        "key": "alt+f1",
        "command": "editor.action.showHover",
        "when": "editorTextFocus"
},
```
Press alt+f1 and notice that the hover is focused.. or at least no key press hide it. But you still can't scroll the content inside.
VSCode 1.31.1

**Comment by alexandrudima** [comment] 2019-03-06 09:33
In 1.31, the action `editor.action.showHover` focuses the hover.
In (the upcoming) 1.32, the action will not focus the hover.

This change came in via #66827 which tackles #10643

**Comment by akshaal** [comment] 2019-03-06 09:44
Ok, I see.. How about a new "editor.action.showHoverFocused" or something like that? And if focused, make it scrollable with keyboard.

**Comment by alexdreptu** [comment] 2019-03-08 03:19
@alexandrudima in 1.32 `editor.action.showHover` doesn't automatically focus the hover but now it also doesn't close with `Esc` anymore. Is there currently any way to set a key bind for this to happen without using the mouse?

**Comment by rbenson** [comment] 2019-03-18 17:09
@alexdreptu the default has been `ctrl+k ctrl+i` since I have known about it, a year+. Focus has never been given to the pop-up.

**Comment by alexdreptu** [comment] 2019-03-19 02:12
@rbenson yes but you could close it using `Esc`, now there is no way to close it without using the mouse.

**Comment by dorian-marchal** [comment] 2019-04-04 09:17
Is their a workaround to scroll the hover tooltip without the mouse, currently?

**Comment by JUD210** [comment] 2019-07-04 10:18
I can't understand why this topic is abandoned.
Is it impossible? or not necessary?

**Comment by JUD210** [comment] 2019-07-04 10:21
As a Keyboard shortcut addictive user, If this feature is added, It would be really enjoyable.
Maybe later my skill goes up, I should contribute.

**Comment by arthurborisow** [comment] 2019-11-22 08:44
Is there any progress on this?

**Comment by stania** [comment] 2020-06-17 07:45
Is there any progress on this?

**Comment by anunezmartinez** [comment] 2020-06-27 07:22
Same problem here :(

**Comment by bheadwhite** [comment] 2020-07-06 19:29
@alexdima @akshaal @sandy081 ^^ any life or possibilities here?

**Comment by stemry83** [comment] 2020-07-18 07:35
It would be very nice (especially for vscodevim users) if vscode adds keyboard shortcut support API for scrolling up and down the content in the hover.

**Comment by papey** [comment] 2020-08-01 14:52
I also want this feature, tell me I can help on something. Thanks.

**Comment by stemry83** [comment] 2020-10-06 08:17
@papey 

Could you share how you did it? Is it specific to your particular brand of keyboard (ErgoDox)?

The popup window is relative to the cursor location (where your current cursor is). When the popup shows up and the current cursor isn't inside the popup window, triggering wheel scroll will target the Editor main area (instead of the popup window), so it'll scroll the editor instead of the popup content. How did you overcome this?

I'm fine with any solution (it's better than having none anyway). Thank you!

**Comment by papey** [comment] 2020-10-06 08:23
@stemry83, Yes, i saw that too. Since it's a programmable keyboard, I've added shortcuts to control the mouse from keyboard (just for fun). So I can `move` the mouse to the correct area and then press the mouse down keybinding. Was fun to test but clearly not usable :disappointed:.

**Comment by kres0345** [comment] 2020-10-10 12:34
I've never really understood the etiquette of '+1' on github issues, but anyway: +1 I would like this implemented as well

**Comment by zoshima** [comment] 2020-11-22 14:28
I guess we could make a PR for adding something like a "editor.action.showHoverFocused" action, but even if the popup opens up focused, is there any way to scroll inside of it using the keyboard?

**Comment by papey** [comment] 2020-11-22 14:53
Just for the sake of a somewhat acceptable alternative :

For now, the best thing I have is https://marketplace.visualstudio.com/items?itemName=bierner.docs-view, in my bottom panel with keyboard shortcuts to open/close it.

**Comment by haoadoresorange** [comment] 2021-04-18 21:52
> Just for the sake of a somewhat acceptable alternative :
> 
> For now, the best thing I have is https://marketplace.visualstudio.com/items?itemName=bierner.docs-view, in my bottom panel with keyboard shortcuts to open/close it.

@papey : nice, except that only works for docs and not errors (:

**Comment by papey** [comment] 2021-04-19 06:58
> @papey : nice, except that only works for docs and not errors (:

If you need to focus an errs/warnings, you may find `workbench.action.problems.focus` command usefull.

**Comment by JakubKoralewski** [comment] 2021-07-28 14:24
I think it could be useful to consider instead of adding specific 2 shortcuts to scroll inside the popup, to instead have one shortcut that moves the cursor into the popup. Then scrolling could be done how it is done usually with arrows, allowing VSCodeVIM users to use their keybindings and anyone else whatever they have set up, and would also allow to use the keyboard to select and copy text from inside the hover.  Then Escape could be used to exit out of the popup.

This would need a new issue, but then a neat feature would be to have hover popups inside hover popus, for example when the 1st level of hover popup documentation has example code inside, then you could get more hover info about some code inside the popup, etc. etc. I think pressing ESC should close each level separately and not all at once.

**Comment by KahnDepot** [comment] 2021-11-05 09:04
This is a very good proposal, for keyboard users they really need this feature.

vscode should not just sit back and watch!

Or at least propose some relatively feasible solutions!

**Comment by kchenzhi** [comment] 2021-11-07 03:53
I really hope this feature will be implemented soon, for my full keyboard controll life.

**Comment by Stolarskis** [comment] 2021-12-11 18:49
> It would be very nice (especially for `vscodevim` users) if `vscode` adds keyboard shortcut support API for scrolling up and down the content in the hover.

Can confirm when using vscodevim, trying to read the scroll through the popup doc only to have it vanish is frustrating. Mainly because 1/10 times my mouse just happens to be in the right spot and it works as expected. I'm trying to figure out the shortcut to just open the relevant docs page for the popup.

**Comment by kres0345** [comment] 2021-12-17 07:07
How is this proposal still open?! 2 years to implement this? How come

**Comment by Binly42** [comment] 2022-01-28 02:08
> I think it could be useful to consider instead of adding specific 2 shortcuts to scroll inside the popup, to instead have one shortcut that moves the cursor into the popup. Then scrolling could be done how it is done usually with arrows, allowing VSCodeVIM users to use their keybindings and anyone else whatever they have set up, and would also allow to use the keyboard to select and copy text from inside the hover. Then Escape could be used to exit out of the popup.

Agreed. 
And indeed, it is not always needed to scroll the hover popup~ So we can just focus it only when needed.

And one related idea is that add a new when clause to detect "whether it is showing a hover popup in active editor", based on which we can emit the new command to focus the popup.

---

> when the 1st level of hover popup documentation has example code inside, then you could get more hover info about some code inside the popup, etc. etc. I think pressing ESC should close each level separately and not all at once.

I am not sure whether this feature too complicated ? 
IMO too many hover popups may steal our people "focus" easier ... (even if the popups not overlay each other

**Comment by kres0345** [comment] 2022-01-28 05:24
Omg the bureaucracy, it's insane. It's two years ago it was proposed to add
shortcuts to scroll and I keep getting notifications, why not implement it
and get feedback that way instead of guessing an theorizing all the time...

fre. 28. jan. 2022 03.08 skrev Binly42 ***@***.***>:

**Comment by Binly42** [comment] 2022-01-28 07:14
> Omg the bureaucracy, it's insane. It's two years ago it was proposed to add
shortcuts to scroll and I keep getting notifications, why not implement it
and get feedback that way instead of guessing an theorizing all the time...

Emm... actually I have no enough time/skill to contribute what I want, so I guess the best thing I can do is just comment down my thinking and wait ...

**Comment by cz2415** [comment] 2022-02-28 06:59
I have an alternative with ahk

1. shortcuts:
{
  "key": "ctrl+alt+a",
  "command": "workbench.action.focusActiveEditorGroup"
}

2. setting
"editor.cursorBlinking": "solid"
"editor.hover.delay": 300

shift alt k: show hover
k/j:  up/down
esc: close hover

```ahk
#SingleInstance, force

#IfWinActive ahk_class Chrome_WidgetWin_1 

    global mode = 0

    +!k::
        PixelSearch, Px, Py, 0, 0, A_ScreenWidth, A_ScreenHeight, 0x0000FF, ,Fast
        Px +=2
        Py +=8
        mousemove %Px%, %Py%

        Sleep, 500

        x1 := Px - 8
        y1 := Py - 20
        x2 := Px + 8
        y2 := Py + 20

        PixelSearch, Px, Py, x1, y1, x2, y2, 0x524000, ,Fast
        mousemove %Px%, %Py%
        Click
        mode :=1
    Return

    ~Esc::
        If (mode == 1){
            Send, {CtrlDown}{AltDown}{a}{CtrlUp}{AltUp}
            mode := 0
        }
    Return

    ~j::
        If (mode == 1){
            Send, {WheelDown}
        }
    Return

    ~k::
        If (mode == 1){
            Send, {WheelUp}
        }
    Return

#IfWinActive
```

**Comment by haoadoresorange** [comment] 2022-02-28 14:22
> I have an alternative with ahk
> 
>     1. shortcuts:
>        {
>        "key": "ctrl+alt+a",
>        "command": "workbench.action.focusActiveEditorGroup"
>        }
> 
>     2. setting
>        "editor.cursorBlinking": "solid"
>        "editor.hover.delay": 300
> 
> 
> shift alt k: show hover k/j: up/down esc: close hover
> 
> ```ahk
> #SingleInstance, force
> 
> #IfWinActive ahk_class Chrome_WidgetWin_1 
> 
>     global mode = 0
> 
>     +!k::
>         PixelSearch, Px, Py, 0, 0, A_ScreenWidth, A_ScreenHeight, 0x0000FF, ,Fast
>         Px +=2
>         Py +=8
>         mousemove %Px%, %Py%
> 
>         Sleep, 500
> 
>         x1 := Px - 8
>         y1 := Py - 20
>         x2 := Px + 8
>         y2 := Py + 20
> 
>         PixelSearch, Px, Py, x1, y1, x2, y2, 0x524000, ,Fast
>         mousemove %Px%, %Py%
>         Click
>         mode :=1
>     Return
> 
>     ~Esc::
>         If (mode == 1){
>             Send, {CtrlDown}{AltDown}{a}{CtrlUp}{AltUp}
>             mode := 0
>         }
>     Return
> 
>     ~j::
>         If (mode == 1){
>             Send, {WheelDown}
>         }
>     Return
> 
>     ~k::
>         If (mode == 1){
>             Send, {WheelUp}
>         }
>     Return
> 
> #IfWinActive
> ```

Unfortunately I mostly use vscode on linux. Is there AHK alternative ?

**Comment by cz2415** [comment] 2022-03-01 02:19
> > I have an alternative with ahk
> > ```
> > 1. shortcuts:
> >    {
> >    "key": "ctrl+alt+a",
> >    "command": "workbench.action.focusActiveEditorGroup"
> >    }
> > 
> > 2. setting
> >    "editor.cursorBlinking": "solid"
> >    "editor.hover.delay": 300
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > shift alt k: show hover k/j: up/down esc: close hover
> > ```ahk
> > #SingleInstance, force
> > 
> > #IfWinActive ahk_class Chrome_WidgetWin_1 
> > 
> >     global mode = 0
> > 
> >     +!k::
> >         PixelSearch, Px, Py, 0, 0, A_ScreenWidth, A_ScreenHeight, 0x0000FF, ,Fast
> >         Px +=2
> >         Py +=8
> >         mousemove %Px%, %Py%
> > 
> >         Sleep, 500
> > 
> >         x1 := Px - 8
> >         y1 := Py - 20
> >         x2 := Px + 8
> >         y2 := Py + 20
> > 
> >         PixelSearch, Px, Py, x1, y1, x2, y2, 0x524000, ,Fast
> >         mousemove %Px%, %Py%
> >         Click
> >         mode :=1
> >     Return
> > 
> >     ~Esc::
> >         If (mode == 1){
> >             Send, {CtrlDown}{AltDown}{a}{CtrlUp}{AltUp}
> >             mode := 0
> >         }
> >     Return
> > 
> >     ~j::
> >         If (mode == 1){
> >             Send, {WheelDown}
> >         }
> >     Return
> > 
> >     ~k::
> >         If (mode == 1){
> >             Send, {WheelUp}
> >         }
> >     Return
> > 
> > #IfWinActive
> > ```
> 
> Unfortunately I mostly use vscode on linux. Is there AHK alternative ?

As far as I know, not yet. AHK is my biggest obstacle to use linux.

**Comment by milanglacier** [comment] 2022-04-18 07:04
Deadly need this feature to be full keyboard-esque

**Comment by axonasif** [comment] 2022-05-18 07:46
So it seems like we're all in the same boat here.
_Sinking together_ 😆

**Comment by matheusinfo** [comment] 2022-05-22 17:07
That's will be really useful to finally to be able to break my mouse

**Comment by RogerDurdn** [comment] 2022-05-28 04:07
Vim user here, this would be a game changer

**Comment by aibor-nongkynrih** [comment] 2022-05-28 13:45
I really need this feature

**Comment by kres0345** [comment] 2022-06-03 08:30
Oh no, I missed the third anniversary for this issue. Bureaucracy...

**Comment by repoerna** [comment] 2022-06-04 23:09
really want these feature..

my workaronud right now using

**Comment by bmarvinb** [comment] 2022-07-24 16:37
Any updates?

**Comment by ant1fact** [comment] 2022-08-06 20:25
Please implement, this is the last thing needed for a keyboard-only setup

**Comment by mezdelex** [comment] 2022-08-19 08:53
Just a reminder this feature is necessary to navigate vast documentations tooltips Rust provides (which is awesome).

**Comment by BIKA-C** [comment] 2022-08-27 08:38
It's been 3 years. Guys, it's hopeless. I bet this issue will remain open in its fifth  year

**Comment by mezdelex** [comment] 2022-08-28 14:58
Well, since I REALLY needed this feature I've been using a workaround that might be of interest for someone:

As they stated in previous responses, there's an extension in VSCode called Docs View which automatically tracks the element at the cursor position and shows related documentation in the "Documentation" section. By default this "Documentation" section can be found either at the left bar or at the bottom bar (and by those bars I mean the ones you toggle with ctrl+b and ctrl+j respectively).

Ok, dunno about you but I don't like the idea of having the docs in either of those places so I added this auxiliary bar toggle keybind in my keybindings.json (ctrl+shift+p and type Open Keyboard Shortcuts (JSON)):

// Auxiliary Bar Toggle
{
        "key": "ctrl+k ctrl+k",
        "command": "workbench.action.toggleAuxiliaryBar"
},

This keybinding toggles the auxiliary bar, which can be conveniently placed to the right of the editor and since it's a toggle, it can be shown and hidden with the same shortcut. I used ctrl+k ctrl+k because it makes sense being ctrl+k ctrl+i the actual tooltip shortcut. You only have to open the auxiliary bar, click and grab with the mouse the "Documentation" section located in any of the bars I mentioned before and put it in the auxiliary bar. 

Now, every time you would place the cursor on top of any significant element, you could either ctrl+k ctrl+i for inference, type, template or brief documentation check and whenever you would need to go more in depth, you could ctrl+k ctrl+k to open the auxiliary bar and navigate as you would normally do with PgUp, PgDn, Up, Down, Home, End since the focus is borrowed by the opened bar. Once you're done, toggle it off again and you're back to the editor.

![auxiliary_bar](https://user-images.githubusercontent.com/59997405/187079921-821b966b-9c8f-4ec2-8250-038d0b5986f5.png)

**Comment by benjamin-thomas** [comment] 2022-09-05 17:15
Excellent suggestion @mezdelex 

I too was looking for a keyboard driven solution. The reason being that I find myself regularly moving the mouse just enough to lose the window focus and I have to start all over again (generally wanting to grab the scrollbar of a long doc).

Pretty irritating when that happens, similar to some CSS navbars that collapse if you just moved a few pixels off.

@sandy081, could the vscode team have a look at this again? Looks like no one's assigned.

**Comment by Profpatsch** [comment] 2022-09-16 15:52
Thank’s @mezdelex this is a good intermediate solution. Though something like a `showAndFocusHover` command would really be appreciated anyway.

**Comment by ant1fact** [comment] 2022-10-11 08:43
That's exactly my use case as well

**Comment by Amonkipt** [comment] 2022-10-11 09:41
Severity Code Description Project File Line Suppression State
Error Could not copy "obj\Debug\sped.exe" to "bin\Debug\sped.exe". Exceeded
retry count of 10. Failed. The file is locked by: "sped (9156)" sped

**Comment by Amonkipt** [comment] 2022-10-11 09:42
Help with this please

**Comment by lukepighetti** [comment] 2022-10-12 21:58
@sandy081 did this issue miss the new backlog voting automation? Is there any way for this to get a fresh look and make sure it's been triaged properly?

As for the issue, I would like to be able to bind scroll up / down and page up / down to the hover.

**Comment by milanglacier** [comment] 2022-11-18 21:47
There are so many veterans from vim and emacs still hesitate on using vscode just because vscode leaves too many parts (UI components/widgets stuffs) that cannot be operated with keyboard.

**Comment by axonasif** [comment] 2022-11-19 02:52
Why bother, I've moved on to Neo(Vim), not even looking back. If you want the true Vim experience, use a real Vim editor but not emulation. VSCode works great in the browser otherwise.

**Comment by mezdelex** [comment] 2022-11-19 04:14
Welp, as much as I hate this issue (documentation scrolling) I have to say that there's no action/motion I could not perform or access other than this particular case with native shortcuts only. I've been trying Helix and Neovim lately, while I was committed to change from VSCode to any of them (I liked Helix more actually) and I couldn't find a single reason other than the 300MB~ vs 15Kb~ of memory that it allocates by default.  Once you understand how the relative positioning of the cursor to some tokens or the selection itself of some of those tokens affects the same action, you can fine tune every little motion to be performed as if there was a specific shortcut for that.

Back to the topic, please notice us 🥹

**Comment by Radrahil** [comment] 2022-11-22 15:40
Sure, in 5 years. If only neovim had more plugins...

**Comment by THOUSAND-SKY** [comment] 2022-11-23 02:51
Is this something that someone w/ zero knowledge of the vscode code base could fix in reasonable time?

Has anyone looked into the problem? Would definitely need some pointers before even attempting.

**Comment by Tantol** [comment] 2023-01-21 17:44
God help us

**Comment by SheryConcepts** [comment] 2023-02-21 16:59
I spent 1 hour trying to come with a solution but sadly. I still need to use mouse.

What functionality is used to scroll with mouse? If we can detect that, then we can map that to keybiindings

**Comment by SheryConcepts** [comment] 2023-02-21 17:01
There should be some api to jump in and out of  "hover widget" when we are in hover widget treat like a normal editor..?????

**Comment by milanglacier** [comment] 2023-02-21 21:39
I think there's no bindings for scrolling in the hover window.

The hover window is just a widget. VSCode is just a web broswer 
anyway...

So it just listens to mouse event and scrolls...

**Comment by aiday-mar** [comment] 2023-03-07 15:22
Hi all, thank-you all for your patience. A PR will soon be merged to solve this issue, which you may track here: https://github.com/microsoft/vscode/pull/176057. Thank you all for your participation.

**Closed** 2023-03-08 11:18 UTC
Labels: feature-request, editor-hover

**Comment by heartacker** [comment] 2023-03-10 14:52
can anybody tell me how to use this,
I tap <kbd>ctrl+k ctrl+i</kbd>, and nothing changed

**Comment by aiday-mar** [comment] 2023-03-10 16:32
Hi @heartacker, thanks for commenting. You may be experiencing this due to a regression that is fixed here: https://github.com/microsoft/vscode/pull/176740. Let me know when the new Insiders build of VS Code comes out if you are still experiencing issues.

**Comment by heartacker** [comment] 2023-03-10 23:03
@aiday-mar  thanks and the latest version work now

but there are some questions and suggestion
1.  <kbd>ctrl+k ctrl+i</kbd> to pin the hover context and tap again, we should unpin the hover. maybe that is great
2. when hover is pin, we tap <kbd>Esc</kbd> to exit the hover, but we lost the focus from that word.
3.  when editor.action.triggerParameterHints is showed， it doesn't work even we have pinned the hover
4. we could not scroll Horizontaly with <-  or  ->
5. 
![image](https://user-images.githubusercontent.com/1876302/224444052-617f24b0-5157-4871-bf2a-0cd216f2da60.png)

**Comment by heartacker** [comment] 2023-03-10 23:32
bother again, :D
1. maybe we could keep the hover pined unless we unpin them. now when we pin the hover and we use mouse to focus another word, the pined-hover disappeared, maybe we should keep the hover pined and easy to show hover-context of another word
2. and a pin/unpin icon to right corner is best. like this ↓
![image](https://user-images.githubusercontent.com/1876302/224445312-b4b7e239-b833-401d-97ed-54c17a6df1be.png)
3. when hover is pined, the only thing is we can scroll the context, and can we add the ability the copy the text?  :), when the hover pined, we could use <kbd>ctrl + ↑ ↓ ← →</kbd> to move the cursor and use  <kbd>shift + ↑ ↓ ← →</kbd> to select the text and the we could copy them. Of course, it would be nice if there was a better solution
> I want to copy that binary string
> ![image](https://user-images.githubusercontent.com/1876302/224447889-d496c29c-8520-4b89-8dfe-d288eafbaebb.png)

**Comment by benedictSchurwanz** [comment] 2023-03-11 04:13
There is a setting `Editor > Hover: Sticky`, "Controls whether the hover should remain visible when mouse is moved over it."

Turn that on, and you can move your mouse onto the tooltip, and scroll it.

**Comment by heartacker** [comment] 2023-03-11 12:43
> There is a setting `Editor > Hover: Sticky`, "Controls whether the hover should remain visible when mouse is moved over it."
> 
> Turn that on, and you can move your mouse onto the tooltip, and scroll it.

no ， that is not my meaning， the situation is that when the hover is pinned and when we use mouse to click other words, the hover still be show and DO be pinned

**Comment by aiday-mar** [comment] 2023-03-20 10:27
It is now possible to scroll the hover widget using the keyboard. Steps to test:

1. Do either of the following:
- Place the mouse so that a hover widget appears with a vertical scroll-bar. Click on the hover to focus it, or use the keybindings for showing the content hover in order to focus on it (Typically the keybindings are cmd+k, cmd+i). 
- Place cursor on a token where hover can appear, and use the keybindings for showing the content hover (typically cmd+k, cmd+i) in order to first show the hover, then focus on it.
2. Use the Up and Down arrow keys in order to scroll in the content hover. Use Page Up and Page Down in order to scroll up and down by the visible hover widget height.

Note: Note that as of now horizontal scrolling is not supported but will be added in the next iteration

**Comment by rami3l** [comment] 2023-03-31 05:12
Hi there! I'm glad to see this feature landing in the March 2023 update.

However, as I use the vim plugin, I actually use `normalModeKeyBindings*` in `settings.json` to control the hover, like so:

```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["K"],
      "commands": ["editor.action.showHover"]
    },
]
```

I'd expect hitting `K` twice will give me the ability to move up/down in the hover, however it seems to me that the hover is never focused...

I'm not sure if this is the right place to report, If needed, I can definitely open a new issue at https://github.com/VSCodeVim/Vim.

**Comment by Voronar** [comment] 2023-04-03 16:16
As @heartacker mentioned moving cursor around inside popup and selecting text with it would be very handy.
