### ISSUE TITLE
Automatically open files and replace the import path

### ISSUE THREAD

**Issue by PengWang0316** [Microsoft/vscode#55923] opened 2018-08-06 23:08 UTC
- VSCode Version: 1.25.1
- OS Version: WIndows 10

When I was editing the code for some files, the IDE sometimes opens bunch of files and randomly replace the import path to somewhere in my hard drive. For example, in some files, it replaced:
````
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
````
to
````
import PropTypes from '../../../../../Users/Kevin/AppData/Local/Microsoft/TypeScript/2.9/node_modules/@types/prop-types';
import { connect } from '../../../../../Users/Kevin/AppData/Local/Microsoft/TypeScript/2.9/node_modules/@types/react-redux';
````
I have other import statement in the same file. But they were not replaced.
Usually, when this happen, it will replace multiple files and just open them automatically.

**Comment by marano** [comment] 2018-08-07 09:16
I am facing the exact same issue here. This is very annoying because it opens dozens of files across my project and there is no way to close all without it prompting to discard changes for each file.

I use MacOS, and my project doesn't even uses typescript, it is a babel codebase.

**Comment by mjbvz** [comment] 2018-08-07 20:39
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-08-07 20:39 UTC
Labels: javascript
