### ISSUE TITLE
No push/pull list

### ISSUE THREAD

**Issue by werexa** [microsoft/vscode#205097] opened 2024-02-13 12:29 UTC
I cannot see the list of commits to push. I have many commits to push, and I didnt see in "source control" tab. I make a test to add a simple commit  and make fetch --all but nothing change. Can you help me to see again the list of push/pull in "source control" after "changes"

![obraz](https://github.com/microsoft/vscode/assets/54885526/d8fdb146-6784-4308-9c3f-5623b622fd4f)

**Comment by lszomoru** [comment] 2024-02-13 16:51
Duplicate of https://github.com/microsoft/vscode/issues/203863

**Closed by lszomoru** 2024-02-13 16:51 UTC
Labels: git
