### ISSUE TITLE
'typedef' have multi-color in difference C header files

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#71903] opened 2019-04-08 02:30 UTC
Issue Type: <b>Bug</b>

In some file, the typedef color is one color (like white), and some others file is other color.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.66GB (4.56GB free)|
|Process Argv|D:\Workspace\Projects\EB_QL_01\03_SoftwareDesign\Trunk\EB-QL-01-STM8|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
cpptools|ms-|0.20.1
psi-header|psi|1.6.6
vscode-icons|rob|8.1.0

(1 theme extensions excluded)

</details>

**Comment by JasonLeeCn** [comment] 2019-04-08 02:32
This issue has nothing to do with the color theme, it has this issue under any color theme.

**Comment by JasonLeeCn** [comment] 2019-04-08 05:50
This issue has nothing to do with the color theme, it has this issue under any color theme.
One color (original color) is same with previous version.
The new color type is "keywords" (scope: keyword).

**Comment by alexr00** [comment] 2019-04-09 09:55
Duplicate of #71823

**Closed** 2019-04-09 09:56 UTC
Labels: *duplicate, new release
