### ISSUE TITLE
Use remote ssh and modife the file in terminal, then the file was deleted when i quit

### ISSUE THREAD

**Issue by windmakeppcool** [microsoft/vscode#106844] opened 2020-09-16 09:02 UTC
- VSCode Version: August 2020 (version 1.49)
- OS Version: Window 10 educiton

Steps to Reproduce:
1. I use vscode remote ssh to connect to a remote docker and open a folder on win10，then i use vim to modife a file in the terminal and use "wq" to quit file. Then the file is deleted! 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment] 2020-09-16 12:56
Can you take a gif of this happening? https://gifcap.dev/

Reading the report it seems like vim if anything is the thing responsible, if VS Code didn't touch the file.

**Comment by windmakeppcool** [comment] 2020-09-17 02:43
![recording](https://user-images.githubusercontent.com/53427316/93413758-8831b100-f8d2-11ea-9621-9c577f447ebe.gif)
like this, when i modife the file and quit, file is deleted

**Comment by windmakeppcool** [comment] 2020-09-17 03:08
> Can you take a gif of this happening? https://gifcap.dev/
>  I add gif below
> Reading the report it seems like vim if anything is the thing responsible, if VS Code didn't touch the file.

**Comment by Tyriar** [comment] 2020-09-17 13:26
Strange, what extensions do you have installed? Pretty certain this is not related to the terminal, but any extension could be watching the file for changes and deleting it for some reason when a change is made.

**Comment by windmakeppcool** [comment] 2020-09-18 02:26
Extension list: 
Anaconda Extension Pack
Chinese(Simplified) lanaguage pack for vscode
code runner
Gitlens
path autocomplete
python
visual studio intellicode
Yaml

I uninstall all extension and try again, and it alse happened

**Comment by Tyriar** [comment] 2020-11-06 00:55
Unfortunately this isn't enough to go on and we haven't received any other reports on this so I'll close it out as the issue is unactionable. If anything I would guess that vim or some other program is causing the problem as you're only interfacing with the terminal component that doesn't have any code that edits files outside of vscode settings/data.

**Closed by Tyriar** 2020-11-06 00:55 UTC
Labels: needs more info
