### ISSUE TITLE
Hot exit on new file does not save language mode

### ISSUE THREAD

**Issue by Sephizor** [Microsoft/vscode#17724] opened 2016-12-22 11:15 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.9.0-040900-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|javadebugger|donjayamanne|0.0.2|
|task-master|ianhoney|0.1.38|
|Angular1|johnpapa|0.1.16|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.4.1|

---

Steps to Reproduce:

1. Open a new tab to get an untitled, unsaved file
2. Type in some JSON
3. Set the language mode to JSON
4. Exit the application without saving the file
5. Reopen the application

Expected Results:
Untitled file is still open with the language mode set to JSON

Actual Results:
Untitled file is still open but the language mode is set back to Plain Text

**Comment by mrmlnc** [comment] 2016-12-22 11:23
Please use serach before create a new issues.

Duplicate of #17115, #17681, #17319, #17402, #17520, #17702 & e.t.c.

**Comment by Sephizor** [comment] 2016-12-22 11:46
I literally searched for "hot exit language mode" and it returned 0 results. Sorry :-1:

**Comment by egamma** [comment] 2016-12-22 13:08
Thanks @mrmlnc 

duplicates #17115 (and is already fixed)

**Closed by egamma** 2016-12-22 13:08 UTC
Labels: duplicate
