### ISSUE TITLE
Cannot search in files

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#28329] opened 2017-06-09 10:06 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:06:23.044Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|cpptools|ms-vscode|0.11.4|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-versionlens|pflannery|0.18.1|
|vscode-open-in-github|sysoev|1.6.0|;

---

Steps to Reproduce:

* search for `IEditOperationBuilder`
* search in `./src/vs/`

* The search never completes and the progress spins indefinitely.
I see a bunch of NPEs in the console:

![screen shot 2017-06-09 at 12 05 35](https://user-images.githubusercontent.com/5047891/26971049-fbacda68-4d0b-11e7-944f-aeb60e641c06.png)

![28329](https://user-images.githubusercontent.com/5047891/26971175-7f8e6720-4d0c-11e7-8f6b-c21b46a42f61.gif)

**Comment by mjbvz** [comment] 2017-06-13 00:55
I believe this is a duplicate of #28293

**Closed by mjbvz** 2017-06-13 00:55 UTC
Labels: insiders
