### ISSUE TITLE
vsce should package closure without devDependencies

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode#2114] opened 2016-01-19 18:09 UTC
Using mainly the default generated files from `generator-code`, a significant number of devDependencies (mostly recursive) are pulled in - mainly because of Mocha. For development this is fine (I love Mocha). But why blindly package them all with `vsce package`? Perhaps create an output directory of everything `vsce ls` would find but _node_modules_, then run `npm install --production` and package that directory. Would certainly reduce the size of VSCode extensions. Mine - with only the addition of 1 small module (with no dependencies itself) is over 5MB.

**Comment by joaomoreno** [comment] 2016-01-19 20:24
Duplicate of Microsoft/vsce#52

**Closed by joaomoreno** 2016-01-19 20:24 UTC
