### ISSUE TITLE
ExtHost CodeLenses can register their command on an already disposed DisposableStore

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#75105] opened 2019-06-08 01:10 UTC
### Repo
1. Enable TypeScript reference code lenses
1. Open a large file in the VS Code code base
1. Wait for js/ts to init. Then make some code edits

### Bug
In dev tools console, see:

![Screen Shot 2019-06-07 at 6 01 53 PM](https://user-images.githubusercontent.com/12821956/59140205-6b78a080-894f-11e9-9951-f32b95ef2ead.png)

Also, try quickly clicking some of the code lenses after making an edit. This may result in:

```
notificationsAlerts.ts:38 Error: Running the contributed command: '_internal_command_delegation_1559955842654' failed.
```

**Comment by mjbvz** [comment] 2019-06-08 01:12
I believe that the root cause of this is:

1. `ExtHost.resolveCodeLens` is invoked
1. This calls `_provider.resolveCodeLens`
1. We `.then` on the result from `_provider.resolveCodeLens`
1. Before `.then` is resolved, we dispose of the code lens
1. Then in `.then`, we register a new command on a the disposable store

Looking into fix

**Comment by mjbvz** [comment] 2019-06-08 01:35
I pushed a partial fix with 1e9fae2 that prevents us from registering the command if we have already been disposed of. This does not fix two things:

* We can still end up invoking an invalid command if you quickly edit the file and then click on the codelens
* After applying 1e9fae2,  sometimes `no command` shows up in the code lens for a moment.

**Comment by jrieken** [comment] 2019-06-13 15:13
This is complicated! The problem is that we are still resolving "old" code lenses while making requests for new code lenses. I think that's actually fair because we wanna keep the UI stable so my idea is to dispose code lens results later, e.g. after lenses of subsequent models have been resolved and rendered. That should eliminate the `no command` and invalid command problem. "Should" tho, there is still something wrong and that need more work

**Comment by jrieken** [comment] 2019-06-20 10:38
Actually this is now good

**Closed by jrieken** 2019-06-20 10:38 UTC
Labels: bug, editor-code-lens
