### ISSUE TITLE
Background highlighting for code blocks in Markdown

### ISSUE THREAD

**Issue by neongreen** [microsoft/vscode#186065] opened 2023-06-24 10:46 UTC
I find it hard to notice code blocks in my .md documentation (eg. README.md with notes-to-self). I'd like an option to have a distinct background color for code blocks.

Note that this should work for all themes, not just "hardcode a specific color via TextMate rules in my user .json settings".

| Before | After |
|--------|--------|
| <img width="503" alt="image" src="https://github.com/microsoft/vscode/assets/1523306/9069db81-332f-4762-a4d7-6171d6608c02"> | <img width="508" alt="image" src="https://github.com/microsoft/vscode/assets/1523306/7db2acb0-10d6-4997-9a2a-c4dc9219234c"> |

**Comment by mjbvz** [comment] 2023-06-26 20:26
Duplicate of #3429

**Closed by mjbvz** 2023-06-26 20:26 UTC
