### ISSUE TITLE
Markdown Emphasis highlighting newline

### ISSUE THREAD

**Issue by TjeuKayim** [microsoft/vscode#81492] opened 2019-09-26 13:48 UTC
Markdown emphasises are interpeted differently in the editor and preview if there is a newline in between. For example in this case: https://spec.commonmark.org/0.29/#example-422.

- VSCode Version: 1.39.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create a file with Language Mode 'Markdown'
2. Insert this text:
```
*foo
foo*

*bar bar*
```
3. Open Preview and watch the difference: The first 'foo foo' is not highlighted as emphasis.

![image](https://user-images.githubusercontent.com/15987676/65693114-0b2f7b00-e074-11e9-8401-f39a964d477d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-09-26 17:49
Duplicate of https://github.com/microsoft/vscode-markdown-tm-grammar/issues/36

**Closed by mjbvz** 2019-09-26 17:49 UTC
