### ISSUE TITLE
GLIBC_2.32 not found during yarn watch

### ISSUE THREAD

**Issue by JengaMasterG** [microsoft/vscode#147478] opened 2022-04-14 20:36 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Pop!_OS 21.10 64-bit

Steps to Reproduce:

1. Download March 2022 Recovery 2
2. Unzip repository
3. Open terminal in directory
4. git init
5. git remote add origin https://github.com/microsoft/vscode
6. yarn
7. yarn watch

Error during `yarn watch` when trying to build web version:
```
[watch-extensions] [16:24:29] 'watch-extension-media' errored after 6.02 s
[watch-extensions] [16:24:29] Error: Command failed: /snap/node/5953/bin/node /media/giovanni/Dev-Any/Development/Project-VSCodeMobile/source/extensions/markdown-math/esbuild.js --watch
[watch-extensions] node:internal/modules/cjs/loader:1185
[watch-extensions]   return process.dlopen(module, path.toNamespacedPath(filename));
[watch-extensions]                  ^
[watch-extensions] 
[watch-extensions] Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /media/giovanni/Dev-Any/Development/Project-VSCodeMobile/source/extensions/node_modules/@parcel/watcher/build/Release/watcher.node)
[watch-extensions]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
[watch-extensions]     at Module.load (node:internal/modules/cjs/loader:981:32)
[watch-extensions]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[watch-extensions]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[watch-extensions]     at require (node:internal/modules/cjs/helpers:102:18)
[watch-extensions]     at load (/media/giovanni/Dev-Any/Development/Project-VSCodeMobile/source/extensions/node_modules/node-gyp-build/index.js:21:10)
[watch-extensions]     at Object.<anonymous> (/media/giovanni/Dev-Any/Development/Project-VSCodeMobile/source/extensions/node_modules/@parcel/watcher/index.js:1:42)
[watch-extensions]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[watch-extensions]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
[watch-extensions]     at Module.load (node:internal/modules/cjs/loader:981:32) {
[watch-extensions]   code: 'ERR_DLOPEN_FAILED'
[watch-extensions] }
[watch-extensions] 
[watch-extensions]     at ChildProcess.exithandler (node:child_process:399:12)
[watch-extensions]     at ChildProcess.emit (node:events:520:28)
[watch-extensions]     at ChildProcess.emit (node:domain:537:15)
[watch-extensions]     at maybeClose (node:internal/child_process:1092:16)
[watch-extensions]     at Socket.<anonymous> (node:internal/child_process:451:11)
[watch-extensions]     at Socket.emit (node:events:520:28)
[watch-extensions]     at Socket.emit (node:domain:537:15)
[watch-extensions]     at Pipe.<anonymous> (node:net:687:12)
[watch-extensions]     at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
[watch-extensions] error Command failed with exit code 1.
[watch-extensions] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "watch-extensions" exited with 1.
error Command failed with exit code 1.
```

**Comment by joaomoreno** [comment] 2022-05-02 07:28
Have you followed https://github.com/microsoft/vscode/wiki/How-to-Contribute ?

**Comment by deepak1556** [comment] 2022-05-02 07:39
`@parcel/watcher` watcher dependency for extensions will use a prebuilt version, in your case the snap version of node causes the watcher module to look for dependencies within the snap and it cannot find the necessary glibc support. You can either try using non snap version of node if your system glibc is newer otherwise you will have to build the watcher module from source. Closing as the issue is related to users' setup.

**Closed by deepak1556** 2022-05-02 07:39 UTC
Labels: needs more info
