### ISSUE TITLE
quiting terminal doens't end program and also the underscore not visible

### ISSUE THREAD

**Issue by Satish-Acharya** [microsoft/vscode#73329] opened 2019-05-06 09:08 UTC
Issue Type: <b>Bug</b>

try runing node server and quit the program by ctrl+c, it doesn't end the program.. The port will be still in use.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-47-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 1777)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.37GB (5.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32

</details>

**Comment by gjsjohnmurray** [comment] 2019-05-07 10:07
Underscore issue sounds like a duplicate of #35901

If it wasn't a duplicate I'd urge you to create a separate issue for it. "One issue per report" is part of the guidance at https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by Tyriar** [comment] 2019-05-10 19:57
If ctrl+c is causing the issue it must be node's fault, we simply tell the process (bash, node, w/e, we don't know what's on the other side) that ctrl+c was hit and it actions it.

**Closed by Tyriar** 2019-05-10 19:57 UTC
Labels: integrated-terminal
