### ISSUE TITLE
No icon shown for debugging

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#80606] opened 2019-09-10 01:59 UTC
![image](https://user-images.githubusercontent.com/4033249/64578305-e1681b80-d333-11e9-8207-579231c1d8be.png)

![image](https://user-images.githubusercontent.com/4033249/64578349-fb096300-d333-11e9-8b50-e44314b85d08.png)

Version: 1.39.0-insider
Commit: 0f1bd7721b793ed8b7805ba621061ce5a1f5c263
Date: 2019-09-09T05:26:48.181Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

**Comment by misolori** [comment] 2019-09-10 02:00
Duplicate of #80563

**Closed by misolori** 2019-09-10 02:00 UTC
