### ISSUE TITLE
IntelliSense should be more context aware

### ISSUE THREAD

**Issue by phest** [Microsoft/vscode#7273] opened 2016-06-06 22:35 UTC
See image below. `Foo` should be prominent in the list.

![intellisense](https://cloud.githubusercontent.com/assets/8858/15840004/b81d63da-2bfb-11e6-8b69-31fe372fe367.PNG)

**Comment by jrieken** [comment] 2016-06-07 07:34
@phest what language/extension are you using?

**Comment by phest** [comment] 2016-06-07 20:36
Apologies, I didn't realize this happened at the extension level.

The quick answer is 'Legacy C# Support' 0.3.3.

The longer answer is I checked after your question and I had 'C#' 0.3.something. I updated it to the latest (1.1.4), but Intellisense did not display symbols anymore. I work with Unity and this looks like a [known issue](http://code.visualstudio.com/docs/runtimes/unity). As recommended in the linked article, I uninstalled 'C#' and installed 'Legacy C# Support' 0.3.3, and I can now recreate the issue above.

Has this issue - Intellisense not context aware - been addressed in later versions of 'C#'?

**Comment by jrieken** [comment] 2016-06-08 06:28
Ok, so `Foo` is in the list but not sorted to the top. There are means to sorting but generally the sorting is lexical and we try to select the best match.

**Comment by phest** [comment] 2016-06-25 20:15
Correct, `Foo` is in the list but not sorted to the top, I should have elaborated.

In this case, enough irrelevant [1] symbols are displayed in the list to hide a field. Furthermore, if the user wrote `Fo`, irrelevant classes like `FocusType` or `FogMode` would still be on top. In this case the user couldn't tab to complete `Foo`, s/he would have to write `F` `o` `o`, or scroll down the list.

It would be helpful to have some sort of context aware sorting, so that the symbols most relevant to the cursor location would appear on top.

--
[1] Irrelevant as far as the context shows. Perhaps the user really would like a FixedJoint2D, but the nothing in the code besides the blanket `using UnityEngine` points at that.

**Comment by jrieken** [comment] 2016-08-17 15:40
@stevencl The issue here is that we sort all items and just pick the best matching (based on character matches). I know we did that for a reason you might remember. Also, the issue is more complex as there can be different sources of completions with competing individual sort orders

**Comment by daveredfern** [comment] 2016-09-04 10:05
I'd like this too. For example in CSS if I do `display:` it returns valid available options such as `block, inline-block, flex, inline`.

![image](https://cloud.githubusercontent.com/assets/183473/18230340/74916fd2-728f-11e6-9eb6-c7a546eb6e66.png)

Thanks!

**Comment by jrieken** [comment] 2016-09-05 07:52
@aeschli Is that our css language service returning so many suggestions for `display`?

**Comment by daveredfern** [comment] 2016-09-05 12:13
@jrieken Thanks for replying so quick <3

@jrieken @aeschli just to confirm it's on any css selector:

![image](https://cloud.githubusercontent.com/assets/183473/18247440/79740ad8-736a-11e6-837b-b874dd16d42b.png)

Thanks,

Dave.

**Comment by stevencl** [comment] 2016-09-05 12:52
@jrieken - I don't recall all the details about how and why we came up with this particular sort order. We looked at various ones, such as most recently used and I _think_ we ended up with the current approach because there were so many different sources of completions.

I have a vague memory that when we looked into it, we felt at the time that we couldn't come as close to a consistent experience as we wanted to, if we were to implement a smarter sort order. The worry from the UX point of view was that inconsistencies in how items are sorted would lead people to making incorrect assumptions about their code (such as, I must have made a mistake in how I declared that variable or that function as it is not showing up in intellisense now).

**Comment by aeschli** [comment] 2016-09-05 13:46
@jrieken The screenshot is with a SCSS file. The proposals look right. It's a mix of values for the display property as well as built-in SCSS functions. We could be smarter there as most of the functions return colors.

**Comment by daveredfern** [comment] 2016-09-06 07:59
@stevencl @aeschli thanks for replying. It's really nice to hear the though process behind it.

I quite like atoms to autocompletion. After I enter colon it provides me with the standard CSS options:

![image](https://cloud.githubusercontent.com/assets/183473/18265875/c4f820b6-740f-11e6-9174-934a6875fd33.png)

If I then start typing letters it initiates the autocomplete like vscode:

![image](https://cloud.githubusercontent.com/assets/183473/18265896/d7fd4560-740f-11e6-8c93-156050a2652f.png)

Maybe most used or most relevant could appear after entering colon and then return to current implementation as I type more?

Just brainstorming ideas 😄

**Comment by jrieken** [comment] 2017-04-21 08:13
Closing this because we have changed the sorting and selection logic. The new behaviour is that when no prefix is given (nothing left of the cursor) we sort alphabetically (we have to do this because there are multiple providers that all contribute completions and because they don't know each other they cannot define a global sort order). When a typing continues we re-sort and re-filter the completion list by how well they match the prefix string. The best match comes first, the second best match second and so on.

**Closed by jrieken** 2017-04-21 08:13 UTC
Labels: intellisense, ux
