### ISSUE TITLE
Auto forcus terminal at first time press CTRL + J (Windows)

### ISSUE THREAD

**Issue by pierreneter** [Microsoft/vscode#40509] opened 2017-12-19 11:06 UTC
- VSCode Version: 1.19.0
- OS Version: Microsoft Windows [Version 10.0.16299.125]

Steps to Reproduce:

1. Open VSCode
2. Press `CTRL + J`
3. The terminal isn't focused at the first time. (Work with ``CTRL + ` ``)

Reproduces without extensions: Yes

**Comment by usernamehw** [comment] 2017-12-19 12:28
A duplicate of https://github.com/Microsoft/vscode/issues/40416 ?

**Comment by pierreneter** [comment] 2017-12-19 12:49
@usernamehw Looks the same but not. I will send a gif.

**Comment by usernamehw** [comment] 2017-12-19 13:08
@pierreneter did it ever work before? I guess I've seen a similar issue before: https://github.com/Microsoft/vscode/issues/19400

**Comment by Tyriar** [comment] 2017-12-27 19:47
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/40416 to me, please provide more info

**Closed** 2018-01-03 20:05 UTC
Labels: integrated-terminal, needs more info
