### ISSUE TITLE
Custom compose key configuration does not work 

### ISSUE THREAD

**Issue by mlainz** [Microsoft/vscode#34277] opened 2017-09-13 08:19 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.9.0-3-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.2
spellright|ban|1.1.40
jupyter|don|1.1.3
unicode-latex|oij|1.0.2

I have configured some custom keybindings for entering unicode symbols using the compose key. They work on other programs but not on vscode.

For example, the default "compose" + "." + "." does type "…", as expected. 
However my custom "compose" + "g" + "a", which should type "α", as it does in other programs, does not work. 

A fix or a workarround would be welcomed.

Steps to Reproduce:

1. Create an .XCompose file in the home directory with the line 
`<Multi_key> <g> <a> : "α"`
2. Restart X.
3. "compose" + "g" + "a" types "α" in most programs.
4. "compose" + "g" + "a" doesn't do anything on vscode.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-09-13 09:47
@mlainz Is this a problem only with the editor or does this reproduce also when wanting to use this key combination in e.g. the find widget input or the search viewlet input boxes ?

Also, do these work in Chromium ?

**Comment by mlainz** [comment] 2017-09-13 10:37
The key combination doesn't work anywhere on vscode.

I tried on Chromium and exactly the same happens (standard key combination work, custom ones don't).

I guess it's a Chromium/electron problem, then.

**Comment by mlainz** [comment] 2017-09-13 10:45
Yes, the bug is referenced [here](https://bugs.chromium.org/p/chromium/issues/detail?id=506838).

**Comment by alexandrudima** [comment] 2017-11-24 14:58
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by alexandrudima** [comment] 2018-02-28 15:58
Reopened due to comment https://github.com/Microsoft/vscode/issues/43526#issue-296460914 from @timtro

The issue is identical to [this one](https://github.com/Microsoft/vscode/issues/34277), #34277. The issue was closed because Chrome displayed the same behaviour, indicating an upstream problem. However, I am currently able to use my custom compose combinations from `~/.XCompose` in Chrome. I'm wondering if this is something we can fix now.

**Comment by mattpalermo** [comment] 2018-05-21 22:12
I am having the same issue in the Atom text editor as well as vscode so perhaps this issue should be addressed upstream in the electron framework?

A thread of my issue: https://askubuntu.com/questions/1038657/how-can-custom-compose-key-combinations-be-defined-for-all-applications

**Comment by mattpalermo** [comment] 2018-05-23 00:29
Good news everyone! This bug is fixed in Atom 1.28 which means that upgrading to Electron 2.0 will (should) fix this problem. It looks like Electron 2.0 upgraded to Chrome 61 which must have been enough to fix the problem.

**Comment by mlainz** [comment] 2018-10-13 19:09
I think the bug is already fixed in the last update.

**Comment by mattpalermo** [comment] 2018-10-13 20:17
Did vscode upgrade to electron 2.0 or did something else happen?

**Comment by alexandrudima** [comment] 2018-10-16 13:51
Yes, the latest stable version of VSCode is on Electron 2.0.7

**Closed** 2018-10-16 13:51 UTC
Labels: upstream
