### ISSUE TITLE
JavaScript Finding all references does not work

### ISSUE THREAD

**Issue by kukoss** [Microsoft/vscode#27246] opened 2017-05-25 10:07 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|angular-material-snippets|4tron|0.3.1|
|angulardoc-vscode|AngularDoc|2.2.2|
|one-monokai|azemoh|0.2.4|
|path-intellisense|christian-kohler|1.4.2|
|unity3d-pack|dimasalmaz|0.7.0|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.4|
|EditorConfig|EditorConfig|0.9.3|
|eppz-code|eppz|1.2.22|
|beautify|HookyQR|1.0.2|
|csharpextensions|jchannon|1.3.0|
|Angular1|johnpapa|0.1.16|
|classic-asp-html|jtjoo|0.0.1|
|docomment|k--kato|0.0.15|
|format-php|Kasik96|1.1.2|
|angular1-code-snippets-johnpapastyle|lperdomo|0.1.0|
|ftp-sync|lukasz-wronski|0.3.3|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.7.0|
|shader|slevesque|0.2.3|
|python|tht13|0.2.3|
|unity-tools|Tobiah|0.1.9|
|python-extended-snippets|tushortz|0.0.1|
|unity-debug|Unity|1.2.0|
|vim|vscodevim|0.7.1|
|gitblame|waderyan|1.10.0|
|unity-snippets|YclepticStudios|0.1.2|
|Material-theme|zhuangtongfa|2.8.0|;

---

Hi I am having problems with Javascript within my project. I have 5 javascript files and I use module revealing pattern. For some reason actions like "Find All References" does not work. It works fine for the same project when I use WebStorm. I tried the same project on another computer with fresh VSC installation and got the same issue. Is this normal?

**Comment by roblourens** [comment] 2017-05-25 17:45
Can you share a code snippet?

**Comment by mjbvz** [comment] 2017-05-25 23:27
Also, do you have a `jsconfig.json` file in your workspace?

**Comment by kukoss** [comment] 2017-05-26 07:22
Hi, 

I created two simple JS files within one folder. file1.js uses function from file2.js. When I select "monthNameToNumber" in file1.js and hit F12 it does not find a function definition in the file file2.js

Here is screenshot of it
![vsc-find-definition](https://cloud.githubusercontent.com/assets/23157947/26484854/b96d6284-41f4-11e7-8820-55451b541e46.png)

And here are two files I just open in visual studio code through "Open folder"

[VSC-test.zip](https://github.com/Microsoft/vscode/files/1031106/VSC-test.zip)

I might be doing something wrong in the code, but it works in webstorm.

thank you

**Comment by kukoss** [comment] 2017-05-26 07:33
@mjbvz Hi, I don't. What should be the content of that file please?

**Comment by willwsharp** [comment] 2017-05-26 12:55
I have reproduced this same issue even with a jsconfig.json.  My directory and files are the same as @kukoss but with a jsconfig.json.

Here is my jsconfig.json

`{
    "include": [
        "file1.js",
        "file2.js"
    ]
}`

**Comment by mjbvz** [comment] 2017-05-26 19:11
Thanks for the additional examples

The issue boils down to: https://github.com/Microsoft/TypeScript/issues/10868 The pattern used to defined `PFTable.Tools.Calendar` is not something we understand even within a single file. You can check this by hovering over the namespaces such as `PFTable` and `Calendar`. All of these have an any type.

Closing as upstream duplicate

**Closed by mjbvz** 2017-05-26 19:11 UTC
Labels: duplicate, javascript, needs more info, upstream

**Comment by kukoss** [comment] 2017-05-26 20:19
@mjbvz what does it mean please? my code structure is bad, or is this not supported by VS code?

**Comment by mjbvz** [comment] 2017-05-26 20:34
@kukoss No, the code is not incorrect and the patterns you are using were quite common with pre-es6 JavaScript. However, we generally don't understand dynamic class/type definitions like you are using very well.

A simpler example of Microsoft/TypeScript#10868 is:

```js
var foo = {}
foo.bar = function() { ... }
```

It is easy for you or I to look at that code and understand that `foo` and a property `bar`, but it is very difficult for a tool to do the same thing in a way that supports all similar the patterns we may encounter in JavaScript. For example, what if we instead write

```js
var foo = {}
if (DEBUG) {
    foo.bar = function() { ... }
}
```

or

```js
var foo = {}
for (var i =0; i < 'bar'.length; ++i) {
    foo['bar'.slice(i)] = function() { ... }
}
```

or 

```js
var foo = {}
Object.defineProperty(foo, 'bar', { value: function() {}})
```

JavaScript's dynamic nature makes it very powerful but also difficult to correctly reason about.


We are able to handle classes and other more modern constructs much better because they provide well defined type information:

```js
class Foo {
    bar() { ... }
}
```

So if you want better editor support for your js, try changing your code to use static patterns like `class` and also defining dependencies between files using modules instead of globals
