### ISSUE TITLE
VScode adds random textto my file

### ISSUE THREAD

**Issue by kounelios13** [microsoft/vscode#64856] opened 2018-12-12 09:43 UTC
- VSCode Version: 1.29.1
- OS Version:
Ubuntu 16.04
Steps to Reproduce:

1.Open up vs code
2.Try to edit some file.After some time while typing a specific word it will add this word or phrase to various places inside my code and will break my code

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by SimpleSamples** [comment] 2018-12-12 13:04
Hopefully the information you provided is adequate for them to understand the problem and fix it. My guess is that they won't understand the problem. They will probably need more information than "_a specific word_". If you can provide specific instructions that re-creates the problem then they will be able to determine the cause of any errors in their code.

**Comment by kounelios13** [comment] 2018-12-12 14:12
Hey thanks for the problem.I really don't know hot to reproduce this.Let's say I select part of my file and press ctr+x to cut it.Some time this text will appear multiple times in random positions in the same file without me having pasted that

**Comment by kounelios13** [comment] 2018-12-12 14:16
Something that came in my mind right now.I was writing in a typescript file(can also happen in html files too) and  wanted to write the word name.After some time I noticed that in several places there was the word "Name" that was breaking my code something like this:

```

generatePhoneField(type) {
    if (type == 'representative') {
      this.phoneType = 'representative';
    } else {
      this.phoneType = 'user';
    }
    this.displayPhoneDialog = true;
  }Name
```

**Comment by mjbvz** [comment] 2018-12-12 19:48
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by kounelios13** [comment] 2018-12-13 11:14
I will try it today

**Comment by mjbvz** [comment] 2018-12-17 19:20
Did you have a chance to try this?

**Comment by mjbvz** [comment] 2018-12-17 19:56
Ok, closing this as not-reproducable. Let me know if you see this against in VS Code 1.31

**Comment by kounelios13** [comment] 2018-12-18 12:51
I reproduced that in the insiders version

**Comment by kounelios13** [comment] 2018-12-18 12:53
I was trying to import a primeng module in an angular project and after selecting then name of the module(ProgressBarModule) the word "Progress" appeared in a random position

**Comment by kounelios13** [comment] 2018-12-18 12:54
![vscode](https://user-images.githubusercontent.com/11466138/50155459-cac8f280-02d4-11e9-84cd-a47eb64deb02.png)

**Comment by mjbvz** [comment] 2018-12-18 19:55
Is the word `Progress` actually inserted in the file or is this just a visual glitch?

**Comment by kounelios13** [comment] 2018-12-19 08:11
The word is inserted in my file and breaking my code

**Comment by kounelios13** [comment] 2018-12-20 07:38
Problem is that it occurs randomly.Sometimes it might be an hour of typing without it occurring.I haven't found a specific keypress that triggers this behavior.

**Comment by kounelios13** [comment] 2018-12-20 07:41
Problem is that it occurs randomly.Sometimes it might be an hour of typing without it occurring.I haven't found a specific keypress that triggers this behavior.

**Comment by guyrish-waveinteractive** [comment] 2019-01-10 23:21
I can confirm that this has sporadically happened to me as well. I have never had it happen with small copy/paste operations - only with large ones (such as shuffling the order of large DIV sections). I have not yet gotten it to happen reliably, but I have encountered this on multiple occasions. It is not a visual affectation it is a corruption of the file.

**Comment by kounelios13** [comment] 2019-01-11 12:13
@guyrish-waveinteractive  that's whats happening most of the time to me

**Comment by guyrish-waveinteractive** [comment] 2019-01-12 03:14
(Fedora 29, vscode 1.30.2)

Cut and paste just "spammed" two files. I remembered to preserve one and take some snapshots. Unfortunately this is the least of them, The attachment of the word "name" on two different lines, overwriting text within the file it was barfed into. While this file was open, it was in a saved state and was _not_ one of the files being actively copied from nor pasted to. The other file (of the aforementioned two files), actually had more than two lines altered and was the source of the cut and paste. The destination of the cut and paste successful received the content without incident.
Most confounding: "name" is not a word that was found on _any_ line that was shuffling about. Nor, despite my previous statement, this was _not_ a large cut and paste operation, it was two lines that were consecutive (as opposed to two lines separated as seen in the snapshot (line 216 and 218 in the snap of the editor).
![cnpbug](https://user-images.githubusercontent.com/40361260/51068597-db277100-15e5-11e9-9c5c-59d6a9b6711e.gif)

**Comment by kounelios13** [comment] 2019-01-12 08:30
@guyrish-waveinteractive could you post some larger images?I cannot see the content of your file from these

**Comment by guyrish-waveinteractive** [comment] 2019-01-14 01:20
Additional content while copying and pasting from and into a single file.

![screenshot from 2019-01-13 19-16-18](https://user-images.githubusercontent.com/40361260/51093354-54e76800-1768-11e9-9f32-60bddbd6cfae.png)

**Comment by mjbvz** [comment] 2019-01-15 19:14
@guyrish-waveinteractive and @yannick1691 Can you try disabling all extensions as well to make sure one of them is not causing this issue

**Comment by guyrish-waveinteractive** [comment] 2019-01-15 19:22
@mjbvz I can... Are there any "blessed" plugins that we can leave enabled or at least slowly dial out? As this is intermittent and I'm essentially waiting for it happen while working, my ability to use the product is pretty inhibited if I turn off things like basic botnet / C# integration.

**Comment by mjbvz** [comment] 2019-01-15 22:20
When the problem happens, run the `Developer: show running extensions` command. This will list all active extensions that could have cause this issue.

It's probably easier though to disable all but your essential extensions and seeing the problems still happens. Can you also share the output of `code --list-extensions` so we know what extensions you have  installed

**Comment by smallSwed** [comment] 2019-03-12 09:20
Hi, I'm experiencing this problem (the appearing of words randomly in my code) in some time with and without enabled extensions.
**VSCode Version:** 1.31.1
**OS Version:** Ubuntu 18.04
**Extentions:** 
- alefragnani.project-manager
- eamodio.gitlens
- Gruntfuggly.todo-tree
- ms-python.python
- ms-vscode.cpptools
- streetsidesoftware.code-spell-checker

May I found the source of the problem: scrolling while the wheel mouse button is pushed down
It making multiple cursors like on Windows, but **on the event of mouse up insert the content of the clipboard**, so broke the code. (There is no pasting with middle mouse button on Windows)

**Comment by smallSwed** [comment] 2019-03-18 16:00
I don't now how can I be a contributor, but I forked and tried some fix:
https://github.com/smallSwed/vscode/commit/6df743599dc9bee3a83001467fdbe735d5d4a3ec

what I did: on scroll I prevented defaults of the mouseUp event

If you think it's good: feel free to use it or I can create a pull request (If I'm allowed)

**Comment by usmcamp0811** [comment] 2019-07-24 13:24
I'm having similar problems.. It seems that multiple cursors get spawned either randomly or in conjunction with some other common command and when I go to paste it pastes to all places the cursors are at. 

I am running VsCode 1.33.0 on CentOS 7

And I just read all of smallWed's post.. yep thats it.. gotta be.. good catch!

**Comment by alexandrudima** [comment] 2019-10-02 08:30
Ok, what I think is going on is:
- you create multiple cursors
- you type and what you type is typed at all the cursors

Multiple cursors is an editor feature that is quite popular. Multiple cursors can be introduced through many many gestures, like:
- alt+click or ctrl+click depending on (`editor.multiCursorModifier`)
- middle mouse button
- ctrl+D
- ctrl+shift+L
- ctrl+F2
- alt+enter while in the find widget

I am not sure what you would want the outcome of this issue to be? The fact that there are multiple cursors is presented in the status bar and all of the above are quite useful features once you get used to them...

**Comment by smallSwed** [comment] 2019-10-04 08:30
What actually going on:
- you create multiple cursors **by sensitive middle mouse button**
- you scroll and what saved to clipboard is typed at all the cursors
   - on **linux** if the **scroll wheel is pressed** it will place the content of the **clipboard** 

I would like to not paste the clipboard content while scrolling. So the code would not be broken.

see capture:
![clipboard_multi-cursor](https://user-images.githubusercontent.com/29921902/66192345-ed2bd100-e698-11e9-99e5-aac9603458c1.gif)

**Comment by alexandrudima** [comment] 2019-10-04 09:02
@smallSwed So I think you would need an option to disable that middle click adds cursors or otherwise you need a new mouse :).

**Comment by adabru** [comment] 2019-10-17 11:24
@smallSwed @kounelios13 does it solve your issue, if you disable "Selection Clipboard"? See https://github.com/Microsoft/vscode/issues/14610 and the screenshot:

![s](https://user-images.githubusercontent.com/6108978/67003852-3c352580-f0df-11e9-8b98-3fed0755844c.png)

I have the same issue with my trackpad and its configuration of doing a middle-click on three touchpoints. When scrolling with my two thumbs, the upper part of the thumb often causes a middle-click. The above mentioned option should probably solve my problem, but in my case https://github.com/microsoft/vscode/issues/80804 prevents me from using it.

**Comment by alexandrudima** [comment] 2019-10-17 14:26
@adabru Are you on macOS or on Linux? Have you tried our insiders build, I have recently pushed a fix where disabling selection clipboard was not actually working on Linux

**Comment by adabru** [comment] 2019-10-17 17:02
@alexandrudima I'm on Linux. Just tried the insiders version (1.40.0-insiders) and the setting works now, thanks a lot!

**Comment by smallSwed** [comment] 2019-10-18 06:20
I tried the insiders  version of vscode (1.40.0) and everything works as expected with that settings. Thank you @alexandrudima.

**Comment by alexandrudima** [comment] 2019-10-18 14:18
Unless there are other objectsion, I will close this issue for now...

**Closed by alexandrudima** 2019-10-18 14:18 UTC
Labels: editor-multicursor, needs more info

**Comment by AndBroPLAYipp** [comment] 2019-10-24 12:38
Updated to insider build;
The middle mouse button paste is disabled which is awesome.
BUT; If you move the mouse, while holding middle mouse, any were outside the document you will instantly paste were your line cursor is located.
This include; top document path and tabs, left tab panel, integrated terminal. and outside the document.

**Comment by alexandrudima** [comment] 2019-10-25 08:28
@AndBroPLAYipp Thank you for trying it out. I've extracted your comment into a separate issue at #83282
