### ISSUE TITLE
Tree view doesn't programatically expand after user collapses

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#44746] opened 2018-02-28 13:54 UTC
With my tree view, if I collapse all the nodes via the GUI and then try to expand them my extension, they stay collapsed.

Is this expected? 

I'm hoping that the new reveal function will remove the necessity to expand the nodes myself anyway.

**Comment by sandy081** [comment] 2018-02-28 14:52
@Gruntfuggly May I know how are you expanding the nodes from extension?

**Comment by Gruntfuggly** [comment] 2018-02-28 15:28
By changing the "state " value and triggering onDidChangeTreeData.

**Comment by sandy081** [comment] 2018-02-28 17:08
Setting `collapsibleState` property is for initial state and cannot override the user state. But if you want to programatically reveal an item, there is an api coming in here - https://github.com/Microsoft/vscode/issues/30288

If agreed, I can close this in favour of the other issue.

**Comment by Gruntfuggly** [comment] 2018-02-28 17:12
OK - that makes sense. Please close.

**Comment by sandy081** [comment] 2018-02-28 17:35
Duplicate of #30288

**Closed** 2018-02-28 17:35 UTC
Labels: *duplicate, explorer-custom, needs more info
