### ISSUE TITLE
Visual Studio Code Feature Request - Folder and files sort order

### ISSUE THREAD

**Issue by rodneyazev** [microsoft/vscode#145164] opened 2022-03-15 20:34 UTC
I would appreciate it if vscode could sort these files alphabetically, it would help me keep my codes organized, just like the sort order in Windows Explorer, same as Spring Boot

Could be possible? If you dont mind. Thanks in advance.

 - Unorganized 
![image](https://user-images.githubusercontent.com/40548312/158466711-8cbc7c03-284c-4d3e-9cb5-9e9f4b4946af.png)

Follows an example (sorted):

![image](https://user-images.githubusercontent.com/40548312/158467128-0f0186a5-40b9-47a5-94d7-1f98d971601b.png)

![image](https://user-images.githubusercontent.com/40548312/158467400-7c4e6cdd-c379-4f2f-8799-ff81755b5825.png)

![image](https://user-images.githubusercontent.com/40548312/158467436-91cb473e-3f85-4639-98e3-d6c5b7d53fab.png)

![image](https://user-images.githubusercontent.com/40548312/158467472-c96c1e56-4136-463c-99af-7483c2da4b52.png)

**Comment by brunovieira97** [comment] 2022-03-16 02:06
Hello @rodneyazev. The files are sorted alphabetically, actually.

The difference lies in Windows Explorer, that treats special characters such as hyphen to succeed letters in sorting, the opposite of what VS Code does. For Code, any special character will precede the letter "a", making such files appear first. You can observe in your screenshot that all files are correctly sorted, considering my explanation.

If you want to customize the sort order of files in the Explorer view, you can take a look at the following settings:
 - explorer.sortOrder
 - explorer.sortOrderLexicographicOptions

Note, however, that the character sorting that makes hyphens and other symbols precede letters can not be changed.

**Comment by rodneyazev** [comment] 2022-03-16 02:23
Hi @brunovieira97 , I tried use these sort methods, but none of them were able to do exactly as I would like to see to maintain my files organized making it easy to maintain as the project grows.

I think maybe they could consider the hyphen too as well as the number of character, as we can see in Windows Explorer, Spring Tools, and others IDE / Editors.

Image maintain thousands of kubernetes environments, files codes, etc. It would be very complicated to give a properly support.

This is something may they could implement in vscode. Lets see.

Grateful.

**Comment by yume-chan** [comment] 2022-03-16 03:22
Duplicate of #27759

Please read https://github.com/microsoft/vscode/issues/27759#issuecomment-680218592 and https://github.com/microsoft/vscode/issues/27759#issuecomment-1043424243

**Comment by Lemmingh** [comment] 2022-03-16 06:28
I guess what @rodneyazev essentially needs is not alternative sorting rules but [file nesting](https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting) (#6328).

**Closed** 2022-03-16 06:54 UTC

**Comment by rodneyazev** [comment] 2022-03-16 06:56
Thank you guys.

Closing this one as there is another one right here https://github.com/microsoft/vscode/issues/27759

Cheers
