### ISSUE TITLE
"Selection -> Add next occurrence" shortcut not working when file opened from command line or URL scheme

### ISSUE THREAD

**Issue by iliyang** [microsoft/vscode#73404] opened 2019-05-07 11:37 UTC
- VSCode Version: 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8)
- OS Version: macOS Mojave 10.14.4 (18E226)

Steps to Reproduce:

1. Open a file via `open vscode://file/path/to/file` or `code -g /path/to/file`
2. Navigate to a word using the keyboard and press `Cmd+D` shortcut

Does this issue occur when all extensions are disabled?: Yes

Additional notes:
The command works when activated via the menu "Selection -> Add next occurrence", but the shortcut `Cmd+D` doesn't work. I can re-enable the shortcut by changing the focus to another application and then back to VS Code, or by activating the search function (via `Cmd+F`) and deactivating it.

One may think this is not a big deal. However, when writing scientific papers with LaTeX (using the excellent LaTeX Workshop extension), activating VS Code via the URL scheme is a very common task. This is done when navigating to the LaTeX source by clicking on the generated PDF file in the Skim viewer.

**Comment by alexandrudima** [comment] 2019-05-07 15:09
Duplicate of #71553

**Closed by alexandrudima** 2019-05-07 15:09 UTC
Labels: editor-contrib
