### ISSUE TITLE
[Regression] - Multiple crashes a day since updating to v1.66

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#146451] opened 2022-03-31 17:01 UTC
- VS Code Version: 1.66
- OS Version:  MacOS 11.6.1

Does this issue occur when all extensions are disabled?: No 
(I will need to bisect what is causing it)

Since updating to v1.66 i keep having the extension host crash. It looks like an electron crash. I've saved the crash report here:
https://gist.github.com/jasonwilliams/30696dc5a0341dc59799dc2120c3d78a

I've also taken a screenshot of the developer tools panel here:
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/936006/161111916-efcd7fee-dde6-4010-ab78-22809fb0645e.png">

EDIT: it seems to be [PHPStan](https://marketplace.visualstudio.com/items?itemName=breezelin.phpstan) causing the issue according to Extension Bisect.  I've uninstalled it and the problem goes away. This only happened at the start of the updated version though so looks like some API is triggering a crash that some extensions are hitting.

**Comment by jasonwilliams** [comment] 2022-03-31 17:23
@vduggen for me it seems like PHPStan, are you using the same extension? I ran extension bisect might be worth you running the same

**Comment by vduggen** [comment] 2022-03-31 17:28
> @vduggen for me it seems like PHPStan, are you using the same extension? I ran extension bisect might be worth you running the same

no, I'm using Vetur and some other extensions gave the same message.

![image](https://user-images.githubusercontent.com/53385727/161114652-3dd2a841-df64-4a9b-8af1-a8216f065fcd.png)

**Comment by mjbvz** [comment] 2022-03-31 18:15
Closing this as caused by extension based on comments. Please try following up with them first and they can let us know if VS Code has broken anything

**Closed by mjbvz** 2022-03-31 18:15 UTC
Labels: triage-needed
