### ISSUE TITLE
Extension documentation view scrolls to top on focus

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#27926] opened 2017-06-02 13:42 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Click to open the documentation for an extension.
2. Scroll down a bit.
3. Click on some file.
4. Click back on the tab with the extension docs.
5. You have been scrolled back to the top.

This is especially annoying as I'm on an extension with a large amount of help text.

**Comment by sandy081** [comment] 2017-06-02 15:02
@mjbvz Assigning this to you, since I remember you own one such similar item.

**Comment by mjbvz** [comment] 2017-06-02 17:57
Thanks. Duplicate of #27498 which i'll look into for june

**Closed by mjbvz** 2017-06-02 17:57 UTC
Labels: duplicate, webview

**Comment by cfjedimaster** [comment] 2017-06-02 18:02
Thank you!

**Comment by cfjedimaster** [comment] 2017-06-02 18:03
Oh sorry to nit pick - is this the same? I had found that issue myself earlier, but noticed it was called the "Extension Editor" - is that the same thing as the documentation viewer?

**Comment by mjbvz** [comment] 2017-06-02 18:05
Yes, extension editor is just the name was use in the code for extension readme/documentation
