### ISSUE TITLE
[Accessibility]A11y_VSCode_CommandPalette_Keyboard:User can not get the list of "Command Palette" once any item is selected from the list.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52418] opened 2018-06-20 08:59 UTC
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Keyboard,MAS2.1.1

**Repro Steps:**
1.Navigate to Settings icon in Activity Bar->Press Enter->Select "Command Palette" from dropdown.
2.Enter ">" sign to reflect all list of expanded "Command Palette" option.
3.Select any item from expanded list such as "Change Language Mode".
4.Then it shows item list which comes under the "Change Language Mode".
5.If uer want to get list of item which shows on ">" sign again then user is not able to go back or user will not get the previous list which reflect on step2.

**Actual:**
Once user select any item of ">" result and again user want same result on ">" sign then user is not able to get same list of item.
 
**Expected:**
Once user get the data on ">" sign then same result should be display on each and every ">" sign.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User is not able to go back once sub item is selected from ">" sign becuase of this every time user have to go to on "command palette" option.

**MAS Reference:**
MAS2.1.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_CommandPalette_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2118568/Accessibility.A11y_VSCode_CommandPalette_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment] 2018-06-21 06:50
I recommend using the shortcut (`F1` or `Ctrl+Shift+P`) to open the command palette. That is faster than going through a menu. Marking as feature request because we don't have the notion of 'back' between these otherwise independent lists.

**Comment by isidorn** [comment] 2018-07-04 10:18
Closing this as designed. User can delete the > and reneter it

**Closed by isidorn** 2018-07-04 10:18 UTC
Labels: feature-request, quick-pick
