### ISSUE TITLE
VSCode corrupts 'registered sign' character

### ISSUE THREAD

**Issue by iSazonov** [Microsoft/vscode#15453] opened 2016-11-14 11:12 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|

---

Steps to Reproduce:

1. Open file containing 'registered sign' character `®` 
Ex.: `Microsoft® .NET Framework`
2. The character is replaced by `�` 
Ex.: `Microsoft� .NET Framework`

**Comment by ramya-rao-a** [comment] 2016-11-15 23:19
Closing as Duplicate of #15303

**Closed by ramya-rao-a** 2016-11-15 23:19 UTC
Labels: editor
