### ISSUE TITLE
File drag and drop does not open the Explorer pane.

### ISSUE THREAD

**Issue by panoschal** [microsoft/vscode#87596] opened 2019-12-23 10:07 UTC
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Minimize the "Explorer" view (e.g. with Ctrl+B)
2. Drag a file from the Windows Explorer
3. Try to drop it in the Explorer icon in vscode.
4. The explorer does not automatically open, which would be somewhat helpful, in order to be able to drop the file in the folder of your choice directly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2019-12-23 10:18
This is a fair feature request for the `compositeBar` that on dragOver the corresponding view would get open.
I think this feature reuqest makes sense in general, since in the future we might want to drag and drop views between containers, and then the corresponding container should expand.
Thus also assigning to @sbatten

**Comment by bpasero** [comment] 2019-12-27 08:24
@isidorn @sbatten this is a regression though. Testing 1.39 I can move a file from the desktop over the (collapsed) activity bar and views expand properly and focus depending on which view is hovered. This was very useful to drag images to `vscode-docs` for writing release notes. Can we bring it back?

**Comment by isidorn** [comment] 2019-12-27 09:02
Re-label it then, and assigned to Janaury so we try to fix it this milestone. @sbatten hope that makes sense.

**Comment by isidorn** [comment] 2020-01-06 15:35
Thanks a lot for the fix @jeanp413

**Closed** 2020-01-06 15:34 UTC
Labels: bug, layout, regression
