### ISSUE TITLE
Copying/Moving folded code does not work as expected

### ISSUE THREAD

**Issue by mika76** [microsoft/vscode#90427] opened 2020-02-11 07:57 UTC
Issue Type: <b>Bug</b>

When moving or copying folded code in Visual Studio (the IDE) it moves and copies as a block, but in VSCode it seems to cut it off in certain cases.

Example, if I fold a method, select the line by clicking on the line number, the click alt-up to move the whole method up, it first unfolds and then only moves the first line of the method.

Generally I would expect the folded to code act as if the whole block was selected and move/copy appropriately. Seems to work well in VS IDE.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.6.1
rest-client|hum|0.23.1
git-graph|mhu|1.21.0
vscode-docker|ms-|0.10.0
mssql|ms-|1.8.0
csharp|ms-|1.21.11
vetur|oct|0.23.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
vscode-status-bar-format-toggle|tom|2.0.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2

(4 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2020-02-11 08:33
Possibly related to #63972

**Comment by mika76** [comment] 2020-02-11 12:51
@usernamehw yes that definitely seems related. 

I've taken a couple of gifs to show what's happening and what is expected...

Currently.. (The first move only moves the first line in the fold - I then ctrl-Z, select the folded text including the blank lines above and below, and then it moves ok) 
![output2](https://user-images.githubusercontent.com/229311/74238027-2a524080-4cd5-11ea-993e-164e5082440a.gif)

This is how VS 2019 handles it...
![output](https://user-images.githubusercontent.com/229311/74238021-24f4f600-4cd5-11ea-8a05-7e13d3efebe9.gif)

**Comment by aeschli** [comment] 2020-02-17 14:10
Duplicate of https://github.com/microsoft/vscode/issues/72422

**Closed by aeschli** 2020-02-17 14:10 UTC
