### ISSUE TITLE
[Feature Request] - Disable and Enabling Extensions

### ISSUE THREAD

**Issue by bmodeprogrammer** [Microsoft/vscode#34828] opened 2017-09-22 11:46 UTC
Visual Studio Code x64
Version: 1.16.1

**What is happening:**
I notice that when we "Disable (Always)" an extension, when I want to enable it again I can't just enable for that workspace, I need to enable Always again. 

**What I want**
I can  "Disable (Always)"  for the default behavior, but Should let I "Enable (Workspace)". 

**Why?**
It's good to have some plugins that is disabled by default and I enable only when I need without the needing of enable it always.

**Thank you**

**Comment by sandy081** [comment] 2017-09-25 10:25
Duplicate of #15611

**Closed by sandy081** 2017-09-25 10:25 UTC
Labels: extensions
