### ISSUE TITLE
Improve TypeScript syntax highlighting

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#8084] opened 2016-06-24 05:17 UTC
Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Date 2016-06-14T13:00:22.146Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Windows 7 x64

Here's a side by side comparison of the (almost) same sample code from the TypeScript playground.

![image](https://cloud.githubusercontent.com/assets/412489/16328521/7735c9b6-39b1-11e6-8a86-cab3423d02be.png)

As you can see the TypeScript side doesn't highlight function/method calls in green as the JavaScript side does.

It's not easy to go through a big white-colored block like this. Specially for people new to TypeScript.
![image](https://cloud.githubusercontent.com/assets/412489/16331587/a79ec07e-39c7-11e6-81c8-4b890840712a.png)

**Comment by emzero** [comment] 2016-06-24 07:51
Adding further details to this. I believe Types should be colored too when being used and not only when declaring them.

Here's the same example in three different color themes.

![image](https://cloud.githubusercontent.com/assets/412489/16331176/c4c390c4-39c4-11e6-967e-c30b4742b58d.png)
![image](https://cloud.githubusercontent.com/assets/412489/16331204/0247232a-39c5-11e6-842c-f3929b3604ab.png)
![image](https://cloud.githubusercontent.com/assets/412489/16331299/a5cb98a0-39c5-11e6-8a79-2290ef2e9ac4.png)

I'd like Types to be colored equally when declaring, importing and using them.

Ideally, I'd like the monokai example to look like this:
![image](https://cloud.githubusercontent.com/assets/412489/16331438/dd761662-39c6-11e6-9291-21ed3d579f87.png)

**Comment by glen-84** [comment] 2016-06-25 14:15
Related to https://github.com/Microsoft/TypeScript-TmLanguage/issues/149 (?)

**Comment by aeschli** [comment] 2016-06-27 17:52
This is a duplicate of https://github.com/Microsoft/vscode/issues/3886 which asks for variable and function reference highlighting
But yes, to implement that we need https://github.com/Microsoft/TypeScript-TmLanguage

**Closed by aeschli** 2016-06-27 17:52 UTC
Labels: typescript
