### ISSUE TITLE
When viewing extension details: Error loading webview: Error: Could not register service workers

### ISSUE THREAD

**Issue by illgitthat** [microsoft/vscode#124791] opened 2021-05-27 22:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Launch VS Code
2. Search for an extension in the extension sidebar
3. Click on the extension
4. Error displayed:
```Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('vscode-webview://extensioneditor/') with script ('vscode-webview://extensioneditor/service-worker.js?platform=electron&id=extensionEditor&vscode-resource-origin=https%3A%2F%2FextensionEditor.vscode-webview-test.com'): ServiceWorker cannot be started.```

(Expected):
1. Launch VS Code
2. Search for an extension in the extension sidebar
3. Click on the extension
4. Extension details displayed

Screen capture:
![2021-05-27_18-04-55](https://user-images.githubusercontent.com/2256474/119903526-d2196f00-bf16-11eb-9b83-43d48d0d84df.gif)

**Comment by mjbvz** [comment] 2021-05-27 22:32
Duplicate of #122951

**Closed by mjbvz** 2021-05-27 22:32 UTC

**Comment by illgitthat** [comment] 2021-05-27 22:34
Thanks for the reference. Tried searching but didn't find that one. Following
