### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by 307025293** [microsoft/vscode#139487] opened 2021-12-20 03:22 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.0-dev.20211214

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:57056:22)
    at getPropertyOfType (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:57716:24)
    at resolveESModuleSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49830:54)
    at getTargetOfNamespaceImport (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49015:28)
    at getTargetOfAliasDeclaration (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49249:28)
    at resolveAlias (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49294:30)
    at getSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:47849:38)
    at resolveNameHelper (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:48142:34)
    at resolveName (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:48125:20)
    at resolveEntityName (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49466:42)
    at getTargetOfAliasLikeExpression (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49223:29)
    at getTargetOfExportAssignment (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49212:28)
    at getTargetOfAliasDeclaration (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49259:28)
    at resolveAlias (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49294:30)
    at resolveSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49284:67)
    at resolveExternalModuleSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49776:36)
    at getTargetOfNamespaceExportDeclaration (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49261:28)
    at resolveAlias (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49294:30)
    at resolveSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:49284:67)
    at mergeSymbol (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:47635:42)
    at c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:47750:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:47748:20)
    at initializeTypeChecker (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:85117:21)
    at Object.createTypeChecker (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:47406:9)
    at Object.getTypeChecker (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:114646:79)
    at synchronizeHostData (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:160331:21)
    at Proxy.getProgram (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:160452:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:165467:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:165396:42)
    at ConfiguredProject.updateGraph (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:166389:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:168113:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:169196:44)
    at c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:169536:97
    at Object.flatMap (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:502:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:169536:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:170694:46)
    at c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:172627:88
    at IOSession.Session.executeWithRequestId (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:172618:28)
    at IOSession.Session.executeCommand (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:172627:33)
    at IOSession.Session.onMessage (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:172653:35)
    at Interface.<anonymous> (c:\Users\30702\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20211214\node_modules\typescript\lib\tsserver.js:175258:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.64.0-insider (065b450db9f555f177161748e8f2911ebb5677f9, 2021-12-10T05:14:44.789Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.52GB free)|
|Process Argv|--crash-reporter-id b879da66-8ebc-46d1-86f9-7b25b0fa3aac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
typings-installer|ben|0.2.0
simple-react-snippets|bur|1.2.5
path-intellisense|chr|2.6.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
path-autocomplete|ion|1.18.0
autofilename|Jer|0.1.3
code-beautifier|mic|2.3.3
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-zh-hans|MS-|1.63.3
vscode-typescript-next|ms-|4.6.20211219
vscode-typescript-tslint-plugin|ms-|1.3.3
tsimporter|pmn|2.0.1
vs-code-prettier-eslint|rve|3.0.4
vscode-scss-formatter|sib|2.3.3
sass-indented|syl|1.8.18
language-stylus|sys|1.15.0
open-in-browser|tec|2.0.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscop804:30404766
vs360:30404995
vsclayoutctrc:30405799
py55gd98:30408621
azactmsal:30409287
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by IllusionMH** [comment] 2021-12-21 09:21
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

TS team needs a way to reproduce this issue. Please provide code that can help to reproduce this crash in issue linked above.

**Closed** 2021-12-21 09:22 UTC
Labels: *duplicate
