### ISSUE TITLE
Iframe - Clipboard issue  - Unable to read from the browser's clipboard.

### ISSUE THREAD

**Issue by faizansayyed** [microsoft/vscode#236582] opened 2024-12-19 12:04 UTC
When I am opening vs code server inside a iframe with a cross origin i am not able to paste anything from clipboard, whereas  if i open same origin in new tab it works fine

- code-server: v4.95.1
- Code: 1.95.1
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

Steps to Reproduce:
1. open terminal 
2. copy a text and try pasting something with 
Paste- COMMAND + V
OR
Paste - COMMAND + SHIFT + V

whenever I try to paste any text to terminal getting below issue 
"Unable to read from the browser's clipboard. Please make sure you have granted access for this website to read from the clipboard."

**I have tried all available solutions from community page**

Just for reference my code 
`   <iframe
              ref="iframe"
              src={iframeSrc}
              style={{
                width: "100vw"
              }}
              id="iframe"
              title={iframeTitle}
              allow={ `clipboard-read; clipboard-write self ${iframeSrc}` }
              onLoad={this.hideLoader}
            />`

**Comment by mjbvz** [comment] 2024-12-19 20:27
Duplicate of #180234

**Closed by mjbvz** 2024-12-19 20:27 UTC
