### ISSUE TITLE
Support (customizable) file type icons in the sidebar

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#427] opened 2015-11-21 21:45 UTC
Sublime Text and Atom supports displaying an icon indicates the type of files shown in the sidebar. These icons can be customized by "UI" themes. The current VSCode does not support any sidebar customization.
![image](https://cloud.githubusercontent.com/assets/240091/11320670/37ad911c-90dc-11e5-988f-e8ff9e0b0d16.png)

**Comment by jel-massih** [comment] 2015-11-21 22:43
Similar to #123 

Looks like its neither possible nor planned.

**Comment by bpasero** [comment] 2015-11-23 07:16
We might support this in the future as API so that extension writers can add decorations to the explorer.

**Comment by jstnlef** [comment] 2016-02-07 07:26
Wanted to bump this. It's the one thing I quite miss from sublime text.

**Comment by Tyriar** [comment] 2016-02-08 19:19
Should this be closed as a dupe of https://github.com/Microsoft/vscode/issues/211?

**Comment by bpasero** [comment] 2016-02-09 06:09
:+1:

**Closed by bpasero** 2016-02-09 06:09 UTC
Labels: feature-request, files
