### ISSUE TITLE
Incorrect file linking in output channel

### ISSUE THREAD

**Issue by sw** [microsoft/vscode#106847] opened 2020-09-16 09:58 UTC
Issue Type: <b>Bug</b>

The file links in the output channel seem to get confused ~~by a Windows short 8.3 path/filename~~. See attached screenshot ![image](https://user-images.githubusercontent.com/4478/93322560-bb613b00-f813-11ea-968b-7a80fce16d05.png)

After ctrl+clicking on link: 
![image](https://user-images.githubusercontent.com/4478/93322725-ecda0680-f813-11ea-9829-e672e37d63b4.png)

The file paths below the problematic line then are not linked. This may be related to #586

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.58GB free)|
|Process Argv|C:\work\hydra\hydra\main\hydra.code-workspace --crash-reporter-id a003d0f7-6204-45f4-a6c2-271f689952fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|2.12.4
cortex-debug|mar|0.3.7
python|ms-|2020.8.108011
cmake-tools|ms-|1.4.1
cpptools|ms-|1.0.0
devicetree|plo|0.1.1

</details>

**Comment by sw** [comment] 2020-09-16 11:11
Smaller example:

The following CMake code results in a wrong link:
```cmake
message(STATUS "aaaaaaaaaaaaaa xC:/work/hydra/hydra/main/prj.conf xC:/work/hydra/hydra/main/prj.conf xC:/work/hydra/hydra/main=C")
```
![image](https://user-images.githubusercontent.com/4478/93329840-1b5cdf00-f81e-11ea-8367-feacd7649e0f.png)

**Comment by isidorn** [comment] 2020-09-16 12:36
I think output is just using Editor link detection. However first forwarding to @sandy081

**Comment by sandy081** [comment] 2020-09-21 07:49
@isidorn Output has special link provider/computer. I am not familiar with this and not sure who wrote that. Do you know?

**Comment by isidorn** [comment] 2020-09-21 07:53
Aha I see there is the `outputLinkComputer`. Looking at the blame nobody wrote it in the last couple of years. It is old code. I did not write it. So it seems like it does not have an owner unfortunetly.

**Comment by sandy081** [comment] 2020-09-22 11:46
Unassigned myself. This is another module that nobody owns.

**Comment by Tyriar** [comment] 2020-09-23 17:31
I just looked into how this relates to the terminal's link detection. It seems to fill a similar role as the terminal's "validated local link provider":

https://github.com/microsoft/vscode/blob/162f9a871781abc6ab17806f5c6bd8ae8612ae05/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L36-L43

https://github.com/microsoft/vscode/blob/162f9a871781abc6ab17806f5c6bd8ae8612ae05/src/vs/workbench/contrib/output/common/outputLinkComputer.ts#L96-L112

These have the potential to have their detection logic merged now that the terminal is using xterm.js' new link provider API which puts the detection side of things in the hands of the embedder, rather than handing regexp's off to xterm.js.

The terminal already has [a link provider based on `LinkComputer`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/links/terminalProtocolLinkProvider.ts) which detects links with protocols in a similar way to `OutputLinkComputer`. The main issue being `OutputLinkComputer` seems to only support absolute paths (no relative, link validation, `a/` or `b/` removal from git diff, less patterns).

**Comment by Tyriar** [comment] 2020-09-23 17:36
History before the refactor:  https://github.com/microsoft/vscode/commits/b4964bcf35a223c976d3e1d1491ce37e4dd08857/src/vs/workbench/parts/output/common/outputLinkComputer.ts

**Comment by sw** [comment] 2020-09-24 18:39
Renaming again, the problem has nothing to do with 8.3 filenames, that was just a coincidence.

**Comment by bpasero** [comment] 2020-09-25 05:49
@sw can you provide steps how to reproduce or how a link looks like that does not work?

**Comment by bpasero** [comment] 2020-09-25 05:50
@sw seeing your example in https://github.com/microsoft/vscode/issues/106847#issuecomment-693337115 you seem to produce links like this one: `xC:/work/hydra/hydra/main/prj.conf` which then fail to open is that true? What do you expect to happen in this case?

**Comment by sw** [comment] 2020-09-26 19:28
In my example, it's the text at the beginning of the line: `[cmake] -- aaaaaaaaaaaaaa` that gets turned into an invalid link. I'm not at work right now so I can't say what exactly it links to.

I originally thought that this bug would prevent paths further down from being linked, which is why I opened the issue. I thought that's what's happening in the first screenshot. But apparently that's not the case, it's just that relative paths don't get linked.

So I guess this issue is just cosmetic.

That relative paths aren't linked is annoying, but that is tracked elsewhere (or a [shortcoming of ninja](https://gitlab.kitware.com/cmake/cmake/-/issues/13894), depending on how you look at it)

**Comment by bpasero** [comment] 2020-09-27 06:59
@sw I tried to reproduce and for me the links appear properly:

![image](https://user-images.githubusercontent.com/900690/94358231-c59af900-009f-11eb-9992-1fbac85f16e0.png)

If you can figure out some exact steps to reproduce, let me know.

**Comment by sw** [comment] 2020-09-30 10:57
@bpasero: the bug is sensitive to the length of the line:
```cmake
message(STATUS "aaaaaaaaaaaaaa xC:/work/hydra/hydra/main/prj.conf xC:/work/hydra/hydra/main/prj.conf xC:/work/hydra/hydra/main=C")
message(STATUS "aaaaaaaaaaaaaa xC:/work/hydra/hydra/main/test-ts/prj.conf xC:/work/hydra/hydra/main/test-ts/prj.conf xC:/work/hydra/hydra/main/test-ts=C")
message(STATUS "aaaaaaaaaaaaaaaaaaaaaa xC:/work/hydra/hydra/main/test-ts/prj.conf xC:/work/hydra/hydra/main/test-ts/prj.conf xC:/work/hydra/hydra/main/test-ts=C")
```
![image](https://user-images.githubusercontent.com/4478/94676957-6695e800-031c-11eb-9829-3be69ad6538d.png)

**Closed** 2020-10-01 06:07 UTC
Labels: bug, output
