### ISSUE TITLE
Fold/unfold

### ISSUE THREAD

**Issue by walaa-a** [microsoft/vscode#109252] opened 2020-10-23 17:20 UTC
Issue Type: <b>Bug</b>

The fold/unfold feature in VS code has been super buggy for me. Both the clicking on the arrow in the gutter and even the keyboard shortcuts, sometimes just won't do anything at all. The editor is not frozen and will respond to everything else I've tried doing, just not the fold/unfold. Eventually it will come to its senses without my restarting the software. Any ideas on what. the issue might be?

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.0.1

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-10-25 19:28
What's the language of the file you see this? Is it reproducible?

**Comment by walaa-a** [comment] 2020-10-25 20:05
It’s in C files. I’m not sure how to reproduce it but it repeatedly happens
to me, for no apparent reason.

Best,
Walaa

**Comment by rdinca1** [comment] 2020-10-30 15:33
Is there already implemented a function to fold/unfold comments in TS or HTML templates from Angular? I am using the latest VSC with no additional plugin installed for folding. I have tried "Fold comments command" but it doesn' work. Is there a 3rd plugin that can take care of "Comments" folding/unfolding?

**Comment by aeschli** [comment] 2020-11-05 14:06
@rdinca1 This seems to be unrelated to the description of this issue. There's a command to comment/uncomment all comments. If it doesn't work please file an issue with a code sample.

@walaa-a I need small samples and step that reproduce the problem.

Closing this issue, happy to reopen if more information is available.

**Closed by aeschli** 2020-11-05 14:06 UTC
