### ISSUE TITLE
Path Intellisense not working for scss file import

### ISSUE THREAD

**Issue by tklepzig** [Microsoft/vscode#54792] opened 2018-07-21 13:43 UTC
Issue Type: <b>Bug</b>

Create scss file with the following content:
```
@import "../"
```
Now place the caret after the slash and trigger the intellisense.

**Expected:** the intellisense list all available files and directories for `../`
**Actual:** the intellisense opens with the following content:

![image](https://user-images.githubusercontent.com/9308325/43036174-84aa2484-8cfc-11e8-953a-1157e09cb737.png)

### Remark

When importing a css using `@import url("")` the path intellisense is working as expected.

---

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:52.551Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1640)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|3.76GB (0.32GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aeschli** [comment] 2018-07-24 07:09
duplicate of #51331

**Closed by aeschli** 2018-07-24 07:09 UTC
