### ISSUE TITLE
Undo and Redo are missing from the Windows Keyboard Shortcuts Reference (PDF)

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90185] opened 2020-02-06 23:27 UTC
[Keyboard Shortcuts Reference](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference).

**Comment by chrisjj** [comment] 2020-02-07 00:15
@eamodio , duplicate of what?

**Comment by chrisjj** [comment] 2020-02-07 00:16
> Please also check if it is already covered by an existing one, like:
> 
> * [Undo and Redo are missing from docs' Key Bindings (#90172)]

I did before posting. And no, it is not.

**Comment by eamodio** [comment] 2020-02-07 00:21
How is it not a duplicate of #90172? You are reporting the same thing -- undo/redo missing from the same docs url. This seems to me to just be a more specific version, which is covered by the existing one. If you feel otherwise, please edit your other issue to include all the other instances of where it is missing rather than opening new issues.

**Comment by chrisjj** [comment] 2020-02-07 00:42
> How is it not a duplicate of #90172? 

This is "Undo and Redo are missing from the Windows Keyboard Shortcuts Reference"

That is "Undo and Redo are missing from docs' Key Bindings"

> You are reporting the same thing 

Different documents.

> This seems to me to just be a more specific version

Then it is worth another read.

> please edit your other issue to include all the other instances of where it is missing rather than opening new issues.

Thanks, but I'll stick with project policy. "File a single issue per problem" https://github.com/microsoft/vscode/blob/master/CONTRIBUTING.md

**Comment by eamodio** [comment] 2020-02-07 00:58
Ah, I see -- next time please be more clear in your description.

**Comment by chrisjj** [comment] 2020-02-07 01:15
> Ah, I see -- next time please be more clear in your description.

I'd thought explicitly identifying the document in question was sufficient. If not, please do let me know how I can be clearer in future. Thanks.

**Comment by gregvanl** [comment] 2020-02-09 21:51
VS Code uses the same keybindings as the default undo/redo for Windows, Linux, and macOS. Most users will discover this through their muscle memory so I don't think these need to be added to the subset of keyboard shortcuts displayed on the reference PDF.

**Closed by gregvanl** 2020-02-09 21:51 UTC

**Comment by chrisjj** [comment] 2020-02-09 22:01
> VS Code uses the same keybindings as the default undo/redo for Windows, Linux, and macOS. 

Just  as clipboard copy and cut. Yet those are listed whereas undo and redo are not.

> Most users will discover this through their muscle memory 

So not all, then.

> so I don't think these need to be added to the subset of keyboard shortcuts displayed on the reference PDF.

Are you sure it is supposed to be a subset? The page says

> This page lists out the default bindings (keyboard shortcuts) and describes how you can update them. ... We also have a printable version of these keyboard shortcuts.

and the PDF is headed "Visual Studio Code - Keyboard shortcuts for Windows".

Not "Visual Studio Code - a subset of Keyboard shortcuts for Windows".
