### ISSUE TITLE
top stack frame column heuristic should not look at stack frame column

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#25820] opened 2017-05-03 09:54 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

- start to debug this code `[1, 2, 3].map(x => x * 2).filter(x => x > 3);`
- set breakpoint in arrow function
- press continue three times

Observe: the breakpoint in the arrow function is only hit once.

I've verified that the DAP returns the proper column location in the top stackframe.

**Comment by isidorn** [comment] 2017-05-04 14:06
Works for me with the legacy node debugger, both with out of source and with the vscode insiders version.
@weinand Let me know what you are doing differently. Can you always reproduce this?
![cbp](https://cloud.githubusercontent.com/assets/1926584/25707365/97ceb5a0-30e3-11e7-9b4b-a662d88d33dd.gif)

**Comment by weinand** [comment] 2017-05-04 15:19
@isidorn in your screencast the column breakpoint in the first arrow function is actually never hit: there is no yellow arrow around/behind the red column breakpoint (so with "hit" I mean seeing the correct column location).
I was trying with a breakpoint in the second arrow function and there I am seeing the yellow column arrow once, but not three times (as expected).

**Comment by isidorn** [comment] 2017-05-05 09:51
@weinand still works for me. If you can consistently repro on your machine we can look together on Monday. 
As for the yellow column arrow not being shown that is due to our column showing heuristic (we only show the column if the previous stop location happen on the same line but on a different column on that line)

![screen shot 2017-05-04 at 22 03 01](https://cloud.githubusercontent.com/assets/1926584/25740956/04bfd1a8-3189-11e7-9925-3a76f12de04d.png)

**Comment by weinand** [comment] 2017-05-05 11:08
I'm talking only about the visual feedback. Yes, the breakpoint is hit correctly all the time, but I don't see it.
Why do we only show the column location if the column differs?

**Comment by isidorn** [comment] 2017-05-05 12:43
Becuase if we are not strict on the column than the heuristic is surfacing too much false positives (we had this live for one milestone and agreed it should be fixed somehow - and I fixed it by also looking at the column). 

Why this surfaces too much false positives is due to the fact that my decorations get updated on focus of a stack frame. So if you are stopped and stackframe A is focused, you click on B and then back on A -> I would see that the previous decoration on A was on the same line as now and the new one should draw a column which is false (since it is the same decoration, nothing changed).

If you are passionate about this issue I can look into restructuring this, otherwise I will push it to backlog.

**Comment by isidorn** [comment] 2017-11-13 18:34
Closing since I do not plan to fix this in the immediate future (more details in my comment above).

**Closed by isidorn** 2017-11-13 18:34 UTC
Labels: bug, debug
