### ISSUE TITLE
Manually restarting Typescript Server triggers a warning about a crashing TS Server process

### ISSUE THREAD

**Issue by maerten** [Microsoft/vscode#28724] opened 2017-06-14 14:03 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-es-beautifier|dai-shi|0.2.4|
|theme-spacemacs|dzannotti|0.0.8|
|Theme-Jellybeams|gerane|0.0.2|
|language-haskell|justusadam|2.2.1|
|vim|vscodevim|0.8.5|;

---

Steps to Reproduce:

1. Restart Typescript Server 5 times
2. Observe a crash notification about typescript server

**Comment by mjbvz** [comment] 2017-06-14 18:05
This is a duplicate of #27817

Please try out the latest [VSCode insiders build](https://code.visualstudio.com/insiders) which should fix this

**Closed by mjbvz** 2017-06-14 18:05 UTC
Labels: duplicate, typescript
