### ISSUE TITLE
InputBox.validation Message doesn't draw a red square anymore

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode#119094] opened 2021-03-16 15:42 UTC
- VS Code Version: insider
- OS Version: Windows

Steps to Reproduce:

1. execute demo with InputBox validation in https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample

2. the VSCode insider doesn't draw a red square anymore when there is a validation error:

![image](https://user-images.githubusercontent.com/1932211/111337226-33e76e00-8676-11eb-89d6-289355a77771.png)

although with vsocde 1.5.42 it's working:

![image](https://user-images.githubusercontent.com/1932211/111337092-14504580-8676-11eb-9245-e9fefe34e795.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by fbricon** [comment] 2021-03-16 15:47
Duplicate of #118945

**Closed** 2021-03-16 16:08 UTC
Labels: *duplicate
