### ISSUE TITLE
Allow snippets to start with other characters than alphabetical

### ISSUE THREAD

**Issue by vedmant** [Microsoft/vscode#35651] opened 2017-10-05 22:04 UTC
Currently when I write a snippet it only works when it starts with [a-zA-Z] characters, in my other IDE I have tons of snippets that start like /*=, *=, */,  and so on, this is not possible with VS Code unfortunately. Allowing this will really improve my experience as I'm really used to my sets of snippets.

**Comment by jrieken** [comment] 2017-10-06 07:02
Please share your snippet, the language in which you are trying this, the *exact* line contents, and how you are inserting a snippet (via IntelliSense, via the Insert Snippet command, or via tab completion). This is important because there are no restrictions about snippets prefixes in general.

**Comment by vedmant** [comment] 2017-10-06 08:30
For example I have following snippet:

	"Comment Section": {
		"prefix": "/*=",
		"body": [
			"/* ========================================================================= *\n * $1\n\\* ========================================================================= */\n",
			"$2"
		],
		"description": "Easily visible comment section"
	}

That generates a bold comment separator for a code, like this:

    /* ========================================================================= *\
     * Some other code
    \* ========================================================================= */

It doesn't work however, I tried several prefixes like "*=", "=*", working only those that start with alphabetical letters like "c*", "C=" and so on.

**Comment by jrieken** [comment] 2017-10-06 08:49
Thanks for clarifying. So, "yes" the snippets works but "no" the IntelliSense windows doesn't show when typing `/*=`. That is because we don't trigger 24x7 IntelliSense (the feature of popping up the completion window while you type) and *any* character but only those characters that define words... I see how this is annoying but there is no easy fix for this... 

Closing this as a duplicate of #32201

**Closed by jrieken** 2017-10-06 08:49 UTC
Labels: needs more info, snippets

**Comment by vedmant** [comment] 2017-10-06 08:57
So tab key works only when IntelliSense can read the prefix? Maybe there is a way to add a hook for tab key, for example with HTML VS Code has [Emmet](https://emmet.io/) functionality included, it works on tab key and I think is not connected to IntelliSense.

**Comment by jrieken** [comment] 2017-10-06 09:59
You must enable tab-completion for this by adding `"editor.tabCompletion": true`. That will only look at snippets and will insert the snippet that matches the current prefix (no matter what it is). It's very likely what you want

**Comment by vedmant** [comment] 2017-10-06 10:05
@jrieken That worked! Thanks!

**Comment by buz-zard** [comment] 2017-11-03 09:56
Adding `"editor.tabCompletion": true` did not help for my case. I have a snippet:
```json
"Create forEach": {
  "prefix": ".for",
  "body": [".forEach(item => $1)"]
},
```
![image](https://user-images.githubusercontent.com/3521740/32368207-ac3f9f60-c08d-11e7-903d-13b8545128a8.png)
And as you see, it did not suggest the snippet.

vscode - Version 1.17.2 (1.17.2)
OS - macOS 10.13
