### ISSUE TITLE
No-english language of sub menu in Selection do not switch,wrong language option lead vscode cannot restart.

### ISSUE THREAD

**Issue by lvhuat** [Microsoft/vscode#17465] opened 2016-12-17 16:27 UTC
- VSCode Version: 1.8.0
- OS Version: window 10

Steps to Reproduce:
switch into non-english language of menu `Selection` do not work well.

....and sorry for my itchy hand,
1. , then i edited with wrong language option ---  `zh` , restart vscode,but it donot show ui anymore!

![image](https://cloud.githubusercontent.com/assets/20853184/21288232/4eb661b6-c4b8-11e6-9311-d8856e866cd8.png)

SOS!!!i have install vscode again, but it still not working,where are the config files local at. can i edit manually

**Comment by kieferrm** [comment] 2016-12-17 18:53
@lvhuat #3884 describes our folder structure in detail. 

What exactly did you do to "editor the language option".

**Comment by lvhuat** [comment] 2016-12-18 03:01
BUG1:
![123](https://cloud.githubusercontent.com/assets/20853184/21291174/d3a3a6a6-c510-11e6-9671-dc5bbc175aa5.jpg)

BUG2:
Do this,you cannot restart your vscode anymore.
![456](https://cloud.githubusercontent.com/assets/20853184/21291192/54151be4-c511-11e6-9275-1a704323d518.jpg)

**Comment by kieferrm** [comment] 2016-12-19 06:04
Bug 1 is a dup of #17216.

I'm sure we are tracking the restart issue when you have an invalid locale but I can't find the issue. @bpasero?

**Comment by bpasero** [comment] 2016-12-19 06:17
For me I can start VS Code with wrong locale without problems on Windows. Moving to @dbaeumer for Windows.

**Comment by dbaeumer** [comment] 2016-12-19 11:21
Works for me without problems under Windows. @bpasero did you test under Linux / Mac ? Your last comment is a little confusing to me?

**Comment by bpasero** [comment] 2016-12-19 11:27
@dbaeumer updated my comment, cannot reproduce an issue on macOS nor Linux.

**Comment by dbaeumer** [comment] 2016-12-19 11:31
OK. The missing translation is partly expected due to the fact that translations always come in later.

**Comment by dbaeumer** [comment] 2016-12-19 11:34
Next 1.8.x build will have translations for the Selection menu:

![capture](https://cloud.githubusercontent.com/assets/1931590/21311450/846d47e0-c5e7-11e6-88e4-93886c50e151.png)

**Comment by dbaeumer** [comment] 2016-12-19 11:35
![capture](https://cloud.githubusercontent.com/assets/1931590/21311468/997216f2-c5e7-11e6-8145-997847dd53d6.png)

**Closed by dbaeumer** 2016-12-19 11:34 UTC
Labels: question
