### ISSUE TITLE
editor.autoIndent setting does not work for C++

### ISSUE THREAD

**Issue by iestynb** [Microsoft/vscode#35347] opened 2017-09-29 00:14 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.0
team|ms-|1.122.0

---

Steps to Reproduce:

1. Add this to your user settings file:   "editor.autoIndent": false,
2. Type code in your C++ source file (e.g newline, open parens, etc)
3. Auto-indent still occurs...
4. Restart VS Code... problem persists

Reproduces without extensions: Yes

**Comment by BillyONeal** [comment] 2017-10-01 04:20
Duplicate of #32746

**Closed** 2017-10-02 07:14 UTC
Labels: duplicate, editor
