### ISSUE TITLE
Call Hierarchy view toggle fails to update title bar and editor

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89557] opened 2020-01-28 20:12 UTC
- VSCode Version: 1.42 Insiders
- OS Version: Windows 10

Found while testing #89386 for TypeScript 3.8 Call Hierarchy view.

Peek > Peek Call Hierarchy

Toggle "Show Incoming Calls/Show Outgoing Calls" button on the right a few times. The first time toggling to "Show Incoming Calls", the entire UI changes to show 'Callers of'. The second round trip you try, the title bar and editor don't update but the right hierarchy view does.

**Comment by jrieken** [comment] 2020-01-29 13:19
Yeah, looks like the tree loses selection/focus...

**Comment by jrieken** [comment] 2020-01-29 13:30
Funky.... I am actually not able to consistently reproduce... I will post a best-guess fix based on the observations I made when I could reproduce this once. @gregvanl Do you still remember on what symbol you have tried this?

**Comment by gregvanl** [comment] 2020-01-29 15:36
@jrieken I have a very consistent repro with a baby TS program:

```ts
class Person {
    #name: string;
    
    constructor(name: string) {
        this.#name = name;
    }

    greet() {
        console.log(`Hello, my name is ${this.#name}!`);
    }
}
```
when I right-click on `greet` and toggle the incoming/outgoing view.

**Comment by jrieken** [comment] 2020-01-29 15:44
Just like that? Without a caller of greet? When showing callers you should see a message that are are none and that's it:

![Jan-29-2020 16-44-26](https://user-images.githubusercontent.com/1794099/73371883-ab154380-42b6-11ea-8517-4517ec71d085.gif)

**Comment by gregvanl** [comment] 2020-01-29 16:40
Oops, I left out:

```ts
let jeremy = new Person("Jeremy Bearimy");
jeremy.greet();
```

**Comment by jrieken** [comment] 2020-01-30 09:32
![Jan-30-2020 10-31-55](https://user-images.githubusercontent.com/1794099/73436981-cd0cd580-434b-11ea-8138-b2267a7667e0.gif)

Jeremy seems like latest insiders :-) Optimistically closing as fixed

**Closed by jrieken** 2020-01-30 09:32 UTC
Labels: bug, callhierarchy, needs more info
