### ISSUE TITLE
IntelliSense extremely slow, unusable

### ISSUE THREAD

**Issue by msallent** [microsoft/vscode#73321] opened 2019-05-06 04:44 UTC
Issue Type: <b>Performance Issue</b>

Tried disabling all extensions, doing a fresh install, and installing the Insider version. IntelliSense still takes more than 3 seconds to suggest anything, even taking more than 30 seconds to remove the red underline after changing some code quickly.

I have the same VS Code setup on my Windows machine (i7 7700K + 16GB RAM) and works perfectly, everything is instant as it should.

I don't think it's a hardware issue as this is a new MacBook Pro that I just bought, but I can't figure out how to solve this and it's driving me crazy.

I'm working on a Gatsby project and whenever I type anything, IntelliSense takes more than 3 seconds to suggest anything.

[Slow IntelliSense demonstration](https://i.imgur.com/5odywo4.gifv)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.49GB free)|
|Process Argv|-psn_0_254014|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   106	   696	code main
    0	    90	   699	   gpu-process
    0	    82	   730	   shared-process
    0	   262	   756	   window (Hero.js — nare-web)
    0	     0	   757	     /bin/bash -l
    0	    41	   760	     watcherService
    0	    98	   761	     extensionHost
    0	   524	   795	       electron_node tsserver.js 
    0	    74	   797	         electron_node typingsInstaller.js typesMap.js 
    0	    74	   799	   window (Issue Reporter)
    0	     0	   800	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Hero.js — nare-web)
|    Folder (nare-web): 567 files
|      File types: jpg(203) webp(135) json(124) js(78) png(14) DS_Store(3)
|                  md(1) prettierrc(1) gitignore(1) mp4(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
material-icon-theme|PKi|3.7.0

(1 theme extensions excluded)

</details>

**Comment by BjoernRave** [comment] 2019-05-06 08:17
@msallent yea, try using the 1.32.3 version, everything works fine there. I have no idea why it takes them soo long to fix this issue. It's already like this for me since two weeks

**Comment by RMacfarlane** [comment] 2019-05-06 17:16
This sounds like https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391. If you have `@types/styled-components` installed, please upgrade it to the latest version

**Comment by msallent** [comment] 2019-05-06 22:01
Hi @RMacfarlane, thanks for chiming in.

I don't have neither `@types/styled-components` installed nor `typescript`.

This is my list of installed dependencies:

`  "dependencies": {
    "babel-plugin-styled-components": "^1.10.0",
    "gatsby": "^2.3.25",
    "gatsby-image": "^2.0.39",
    "gatsby-plugin-manifest": "^2.0.29",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.0.35",
    "gatsby-plugin-styled-components": "^3.0.7",
    "gatsby-source-filesystem": "^2.0.29",
    "gatsby-source-instagram-all": "^2.0.5",
    "gatsby-transformer-sharp": "^2.1.18",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.0",
    "react-scroll": "^1.7.11",
    "react-slick": "^0.24.0",
    "slick-carousel": "^1.8.1",
    "styled-components": "^4.2.0"
  },
  "devDependencies": {
    "prettier": "^1.17.0"
  },`

I guess the issue is project related as I just tried opening a React Native project and IntelliSense worked as expected there.

**Comment by tkore** [comment] 2019-05-09 01:50
> @msallent yea, try using the 1.32.3 version, everything works fine there. I have no idea why it takes them soo long to fix this issue. It's already like this for me since two weeks and it's such an integral part of the software

Thank you for pointing this out. I have no idea why I haven't tried it myself. Works like a charm. :)

**Comment by vaunus** [comment] 2019-05-09 12:25
Can confirm I experienced the same issue with 1.33.1 and I disabled all extensions to eliminate those as the cause. Rolling back to 1.32.3 fixed the problem as suggested.

For me this was occurring in a React JavaScript ES6 project. If I for example added a new unused import it would take a good 4 seconds for IntelliSense to realise the imported variable was unused and to highlight it accordingly. After rolling back this is near instant.

**Comment by msallent** [comment] 2019-05-09 13:45
Can confirm as well, downgraded to version 1.32.3 and everything seems to be working fine.

Thank you for the suggestion @BjoernRave, hope this gets fixed in a future release.

**Comment by vaunus** [comment] 2019-05-09 15:29
@msallent do we need to keep this issue open so the VSCode team look into what the problem is? I see you've closed it but rolling back to a previous version isn't a resolution.

**Comment by msallent** [comment] 2019-05-09 21:17
Yeah, you're right @vaunus. I'll reopen the issue and hope someone from the team is able to help.

**Comment by dashdashzako** [comment] 2019-05-10 08:04
Isn't this issue the same as #72616? If it is, @msallent could you please confirm which version introduced the problem?
That would be great!

**Comment by tbredin** [comment] 2019-05-15 01:53
Experiencing this as well — I have just installed VSCode on a brand new MacBook Pro, and am editing SCSS blocks inside Vue components. The only extension I have installed so far is Vetur.

Typing `ml` and then hitting tab _should_ produce `margin-left: ;`, but I'm consistently getting `margin: ;` instead because its too slow to react to my keypress. 

Have checked my settings, and the delay on IntelliSense was set to `10`, but even changing this to `0` provides this very slow response. I am loving VSCode, but this feature is unusable for me at the moment, hope it gets fixed soon 👍

**Comment by sarneeh** [comment] 2019-05-15 12:02
I've also encountered this issue and started to dig around to find the cause of this. What I've found was that  the problem is mostly caused by the `ts-server` which for some reason parses all my `node_modules`. This is just a hypothesis as I didn't dig any further, but maybe it can be some kind of clue. My issue is right [here](https://github.com/microsoft/vscode/issues/73624).

**Comment by mjbvz** [comment] 2019-05-17 17:26
Please test this again with the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) (and make sure you are using typescript 3.5-insiders in your workspace)

There were a few upstream perf fixes, including https://github.com/microsoft/TypeScript/pull/31400, that may have addressed this

---

@bredin Please file your issue against the vetur extension

**Comment by vaunus** [comment] 2019-05-19 11:45
@mjbvz the issue I was having as described above appears to be fixed in the latest build, however I am using JavaScript ES6 not Typescript so would suggest waiting for @msallent and others to report back as well.

**Comment by msallent** [comment] 2019-05-19 15:46
@mjbvz latest insiders build works perfectly even though I'm not using typescript at all.

April update (1.34) seems to still have this issue so I'll keep using 1.32.3 until this is resolved.

**Comment by steabert** [comment] 2019-05-21 11:29
For me intellisense with typescript in 1.34.0 is unusably slow, in 1.35.0 it's normal again.

**Comment by mjbvz** [comment] 2019-05-21 17:50
Closing as fixed in 1.35 / insiders

**Closed by mjbvz** 2019-05-21 17:50 UTC
Labels: needs more info

**Comment by polishedwp** [comment] 2019-05-25 21:06
@mjbvz Not fixed here. VSC has been miserably slow since 1.32.

**Comment by chungweileong94** [comment] 2019-05-31 09:21
Not only that the IntelliSense is slow, the ts/js server often stop working for some reason, and I have to manually restart the ts server or reload the window, just to get it works again.

**Comment by polishedwp** [comment] 2019-05-31 15:12
For what it is worth, the [Code Insiders](https://code.visualstudio.com/insiders/) has gotten better over the last few days.

**Comment by BjoernRave** [comment] 2019-06-06 10:41
@polishedwp @chungweileong94 maybe check the developer tools of vscode, in `help` -> `Toggle Developer Tools`. I found out that  an extension called `Auto-Rename-Tag` was causing the problems

**Comment by polishedwp** [comment] 2019-06-06 12:01
@BjoernRave Thanks, didn't know about the Developer Tools but that is not the case for me. It started with the TS upgrade after 1.32.1 and I have turned off all extensions and added one by one with no discernable difference. It is getting better but still a long way to go.

**Comment by ProTip** [comment] 2019-06-28 22:22
For anyone still experiences issues with this **try disabling auto import suggestions**. In my testing just importing from the `aws-sdk` would then introduce a 2+ second delay on type suggestions to everything.
