### ISSUE TITLE
Web: Webview is stealing keybindings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82592] opened 2019-10-15 13:20 UTC
Linux, chrome

Open a markdown file preview
Press F1 > expect to get the quick open list, instead Chrome help gets opened 🐛
The issue it seems is that while the web view is opened it steals all keybindings from vscode. Even if chrome is in full screen.
Adding important since I think we should tackle this if possible, otherwise it would lead to a lot of unexpected ctrl + w closing whole vscode behavior.

@rebornix reply:

> It's a really good catch, even though we don't know the answer to it with current implementation. The iframe is running in another domain where keyboard.lock is not allowed at this moment WICG/keyboard-lock#40

**Comment by mjbvz** [comment] 2019-10-17 02:18
I have a local fix for the `f1` issue. Because I solved it by doing some major refactoring, I'm holding off on pushing it until I can test a bit more locally

I don't know what we can do about about the `ctrl + w` case though. If the webview iframe is focused, it never seems to gets a keyboard event for this at all. Should we raise the issue again with the standards folks?

**Comment by bpasero** [comment] 2019-10-18 05:58
@mjbvz yes I would bring it forward, maybe as a chrome bug actually.

**Comment by mjbvz** [comment] 2019-10-18 23:54
Reported upstream with minimal repo: https://bugs.chromium.org/p/chromium/issues/detail?id=1016034&can=2&q=keyboard%20lock%20iframe

I'm not sure exactly what the expected behavior would be in these cases. Letting an iframe be able to call `keyboard.lock()` as WICG/keyboard-lock#40 proposes would work, or maybe browser keyboard events (such as cmd+p or cmd+w) should always go to the top level window's context

**Comment by mjbvz** [comment] 2019-10-19 00:04
Raised issues upstream. @kieferrm It may be worth trying to get this issue prioritized as well

**Comment by mjbvz** [comment] 2019-10-21 18:59
Moving this out of October since we've done what we can on our side to fix this. Will continue following up upstream

**Comment by bpasero** [comment] 2021-03-19 07:18
This is making it very hard for me to operate cool extensions like draw IO, is there any idea how we can resolve this?

This is me trying to bring up command palette:

![recording](https://user-images.githubusercontent.com/900690/111744511-a67d6700-888b-11eb-9230-cd1569aaadd7.gif)

**Comment by mjbvz** [comment] 2021-05-06 00:52
@bpasero I believe DrawIO provides it's own print menu and incepts calls to `cmd+p`. Not a big fan of this but we also can't prevent it. I'll reopen #122596 to investigate more

**Comment by mjbvz** [comment] 2021-05-06 01:10
Unfortunately I don't think we'll be able to come up with a generic solution for this until there's a proper web API to support this use case. I brought this need up to the Edge team a few times but don't think there's been any progress 

I just fixed ctrl+p with #122596. Closing this but let's continue track  other common cases individually so they can be addressed

**Closed by mjbvz** 2021-05-06 01:10 UTC
Labels: bug, chromium, important, upstream-issue-linked, web, webview
