### ISSUE TITLE
Support user style sheet as mandated by CSS 2

### ISSUE THREAD

**Issue by mikkorantalainen** [microsoft/vscode#168856] opened 2022-12-12 10:50 UTC
I want support for [user style sheet](https://dbaron.org/css/user/) as specified [in the CSS spec](https://www.w3.org/TR/CSS22/conform.html#conformance)[*]. In practice, this could be implemented without any UI. The feature would be specified as follows:

- During VS Code startup, check if file `~/.config/Code/User/userstylesheet.css` exists (and the corresponding alternative for Windows users).
- If that file exists, inject it as `<link rel>` element using absolute `file:` URL into the DOM of `workscape.html`: `<link rel="stylesheet" href="..." />`
- Proceed as usual. None of any other VS Code implementation should even mind that user style sheet has been added. The user is taking full responsibility for all modifications done via user style sheet.

Document that this feature does exist and none of the class names, id selectors or DOM structure are part of permanent API, and those will be changed without a warning both during runtime and as part of software updates.

Explicit non-features:
- Ability to have multiple CSS files.
- Ability to specify different CSS files for different projects.
- Any kind of automatic reload of the CSS when the user stylesheet is modified.

In practice, the runtime performance cost would be one `stat()` syscall during the VS Code startup if this feature is not used and addition of one DOM element in case the `userstylesheet.css` does exist. Plus obviously any overhead that the users want to add with their custom styles, which is entirely on their own responsibility.

This feature is absolutely needed for accessibility alone. VS  Code users are already using ugly hacks such as https://github.com/be5invis/vscode-custom-css which cannot work in multiuser installations even in theory (e.g. VS Code installed via `apt` on Ubuntu Linux). The idea that *everything* that *anybody* could ever want to change change in the UI should be published as an official extension point doesn't hold water either. User style sheets were originally designed to be used for use cases where **one user** has some special need!

If I've understood correctly, this kind of feature (with more complex specification) has been denied previously because it supposedly cannot be understood (by software developers?!?) to not declare permanent API for DOM structures, or because implementing it would be so hard.

Would you accept this feature? If it's about resources needed to implement it, I'd be willing to create the missing patch for the spec I listed above, if that's what this takes.

If you do not want to allow this e.g. **for branding or political reasons instead of technical issues**, just say so and we know for real.

[*] The actual CSS spec says (emphasis mine):
> UAs **must allow** users to specify a file that contains the user style sheet. UAs that run on devices _without any means of writing or specifying files are exempted_ from this requirement.

**Comment by aeschli** [comment] 2022-12-12 15:03
Sorry, a user style sheet goes against a design philosophy of VS Code. A user style sheet would work against a DOM structure and class names that is not documented and we consider internal. To evolve, refactor or improve VS Code, we need the freedom to make changes to the UI. Each change would break user style sheets. This would result in frustration with user style sheet providers and a bad user experience: User style sheets that are half broken, resulting in potentially strange UI glitches that are hard to debug on our side.
Instead, we aim to a well-designed extension API. This one is documented, comes with tooling and samples, and is kept stable across all upcoming releases of VS Code.

Duplicate of https://github.com/microsoft/vscode/issues/459

**Closed by aeschli** 2022-12-12 15:03 UTC

**Comment by mikkorantalainen** [comment] 2022-12-12 15:47
> This would result in frustration with user style sheet provider

How about the amount of trustration when this feature is not working *at all* currently? If DOM was changed too much to apply the existing style sheet, **in worst case the situation would fall back to the current situation** because the user written selectors would no longer match anything.

This is no different from how user style sheets work in normal web use.

> user style sheet goes against a **design philosophy** of VS Code

I interpret that this is the real reason to not do this.

**Comment by aeschli** [comment] 2022-12-12 16:15
The worst case is half applied style sheets, causing UI glitches impacting the look and usability of VS Code resulting users to file issues (and blame) VS Code for it.

> This is no different from how user style sheets work in normal web use.

Do you have examples where the stylesheet of a Web page is user provided?

**Comment by aeschli** [comment] 2022-12-13 15:15
Sorry my ignorance about what user style sheets are and can include. If styling is limited to a well-defined set of properties, that's certainly in the spirit of VS Code: We want styling to happen in a controlled, well defined and documented way, that allows us to evolve the product without breaking any users. We already allow that through color and icons themes as well as various settings in the UI.
If there's anything missing that you would like to style, please file an issue.

You mentioned the vscode-custom-css extension that is about injecting a stylesheet that works against everything in the DOM: that's out of scope.

**Comment by ddnomad** [comment] 2022-12-15 17:42
> Sorry my ignorance about what user style sheets are and can include. If styling is limited to a well-defined set of properties, that's certainly in the spirit of VS Code: We want styling to happen in a controlled, well defined and documented way, that allows us to evolve the product without breaking any users. We already allow that through color and icons themes as well as various settings in the UI.
> 
> If there's anything missing that you would like to style, please file an issue.
> 
> 
> 
> You mentioned the vscode-custom-css extension that is about injecting a stylesheet that works against everything in the DOM: that's out of scope. 

In a light of https://github.com/iocave/customize-ui/issues/156, it seems like changes in VS Code already "break users", thus I believe that giving more freedom to people that want to customise VS Code is a lesser evil, even if those customisations break from time to time.

**Comment by danielwerg** [comment] 2022-12-15 18:03
Very odd to me that product made for _developers_ doesn't allow them to "hack" it.

**Comment by hellen-dorandt89** [comment] 2022-12-17 21:51
Why oh why did you break compatability with Iocave/customize-ui . I am not updating to 1.74, am staying on 1.73 until I find an alternative to VSCode. This much hand holding for programmers is insulting.

**Comment by mikkorantalainen** [comment] 2023-01-11 10:28
> If there's anything missing that you would like to style, please file an issue.

I have a lot of small things that *I* would want to tweak but I don't think that many other people feel the same. Do you really want me to file a new issue for every little thing simply to spam your issue tracker so that you can then mark it as "won't fix" because implementing official API point for every little thing makes zero sense?

Again, do you think that VS Code which is targeted to software developers has user base with lesser skills than Firefox that supports this out of box?

The only thing needed is ability to load a single CSS file from the user profile directory if one exists. Feel free to document that any CSS selectors one could use there will be changed without notice and before submitting bug reports, the issue must be repeated without user stylesheets.

Right now my customizations are in a CSS file which I copy paste to developer tools view every time after restarting VS Code. Do you think that's a good UX?
