### ISSUE TITLE
Auto import using @types or relative path rather than direct import

### ISSUE THREAD

**Issue by Orillion360** [Microsoft/vscode#54729] opened 2018-07-20 14:44 UTC
Issue Type: <b>Bug</b>

Where I'm using auto complete for an import when using typescript, visual studio code (or whatever manages this), prefers to include the relative path to a 'import <X> from "../node_modules/@types/package"' rather than the actual correct package. Which would just be 'import <X> from "package"'. This is problematic since during runtime this obviously won't work since the typings don't contain any code that can be executed.

The same problem sometimes occurs and it likes to prefer using a relative import to the node_modules. This is yet again not very desirable since there is no guarantee that the files in outDir has the same relative pathing to node_modules.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.1
tslint|eg2|1.0.34
vsc-material-theme|Equ|2.3.0
dotenv|mik|1.0.1
mssql|ms-|1.4.0
java|red|0.28.0
rust|rus|0.4.7
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2
vim|vsc|0.15.2

</details>

**Comment by mjbvz** [comment] 2018-07-20 18:30
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-20 18:30 UTC
