### ISSUE TITLE
Allow assiging keyboard shortcuts in tasks.json to trigger tasks per project

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode#78868] opened 2019-08-10 14:13 UTC
We have npm scripts running inside a docker-container running on a remote machine.
For quick access to fire these scripts we use tasks.json.
I'd like to add keystrokes to these scripts in tasks.json, but that currently isn't possible.
It seems like in VS Code we can only add custom keyboard shortcuts to the usersettings, which count for all projects. But every project has its own npm scripts and its own tasks.json, so we can't use these keystrokes as defined on a user level.

For this we would like to be able to add keystrokes for tasks directly in the tasks.json.

**Comment by alexr00** [comment] 2019-08-12 10:16
This would be solved by having project specific keyboard shortcuts. Duplicate of https://github.com/microsoft/vscode/issues/23757.

**Closed** 2019-08-12 10:16 UTC
Labels: *duplicate, tasks

**Comment by Friksel** [comment] 2019-08-12 17:18
> This would be solved by having project specific keyboard shortcuts. Duplicate of #23757.

Thanks and sorry for this duplicate. I was looking for keystrokes, tasks.json and all, but didn't find that issue.
