### ISSUE TITLE
alt+shift+f indent bug

### ISSUE THREAD

**Issue by pch18** [Microsoft/vscode#47981] opened 2018-04-16 16:32 UTC
![qq20180417-012746](https://user-images.githubusercontent.com/19822708/38822603-e9aa6150-41de-11e8-981a-87824c0209f9.gif)

**Comment by mjbvz** [comment] 2018-04-16 17:55
Same root cause as https://github.com/Microsoft/TypeScript/issues/19167 I believe 

Closing as upstream

**Closed by mjbvz** 2018-04-16 17:55 UTC
Labels: editor, editor-autoindent
