### ISSUE TITLE
typing closing brackets (or similar) doesn't ignore the input in some cases

### ISSUE THREAD

**Issue by vince1995** [microsoft/vscode#88134] opened 2020-01-06 13:00 UTC
In some cases VSCode doesn't ignore the input when I am typing a closing bracket, quote marks, or similar:

![brackets](https://user-images.githubusercontent.com/15120985/71819356-f65b7e00-308b-11ea-9bf3-5d67ebd69cbf.gif)

- VSCode Version: 1.4.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a bracket.
2. Go to another location with the cursor.
3. Go back to the opened brackets.
4. Write code in the brackets, close the brackets.
5. VSCode adds a bracket instead of skipping the input.

Does this issue occur when all extensions are disabled?: Yes

Note the gif: I am typing two times the closing bracket. At the first time, it seems to ignore the input and adds the bracket after the ignore a few milliseconds later. At the second time it's adding the bracket directly.

**Comment by alexdima** [comment] 2020-01-21 09:03
This is as designed. 

By default, VS Code types over a closing bracket only if it was automatically inserted and the cursor did not leave the area between the brackets since it was auto-inserted.

Please configure `"editor.autoClosingOvertype": "always"` to get the behavior of always over typing close brackets, even if they were not automatically inserted by the editor.

**Closed by alexdima** 2020-01-21 09:03 UTC
