### ISSUE TITLE
Canceled error popup

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#60488] opened 2018-10-10 09:26 UTC
Since updating to 1.28.0, every time I stop debugging with HashLink Debugger by either using Shift+F5 or closing the application window, it pops a `Canceled` error message with the following error in console:

```
TypeError: Cannot read property 'threads' of undefined
    at e.fetchThreads (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2969)
    at /C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2969
    at Object.g [as _notify] (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160)
    at Object.enter (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164)
    at n.Class.derive._creator._run (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at n.Class.derive._creator._error (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at n (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:163)
    at n.Class.define.cancel.then (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166)
    at Object.enter (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:163)
    at n.Class.derive._creator._run (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at n.Class.derive._creator._setCompleteValue (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at Object.m [as _notify] (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161)
    at Object.enter (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164)
    at n.Class.derive._oncancel._run (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at n.Class.derive._oncancel._error (/C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165)
    at /C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2605
    at /C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2609
    at Map.forEach (<anonymous>)
    at /C:/Users/Nico/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2609
```

I'm the HashLink debugger extension developer and I would like to know if there's something I can do to prevent this from happening.

**Comment by isidorn** [comment] 2018-10-10 09:28
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/60448#event-1894676452
which I plan to fix soon.
You can subscribe to that issue and try it out in vscode insiders and let us know if that fixes it for you

**Comment by AnanyaJha** [comment] 2018-10-24 18:45
@isidorn This issue seems to be the same as the one I referenced in [this post](https://github.com/Microsoft/vscode/issues/60448#issuecomment-432595933). Would like to reopen- when stopping the Apex Replay Debugger with Shift+F5 or stopping the debug session, there is a `canceled` error popup that appears. 
![image](https://user-images.githubusercontent.com/21326913/47453708-45b4d780-d782-11e8-9c20-fe74bb6252ba.png)

**Comment by AnanyaJha** [comment] 2018-10-25 17:28
Sounds good, please let me know if you need anymore information. There are no errors displayed at the time of this `Canceled` event. The only output at that point is: `notificationsAlerts.ts:40 Canceled t.onDidNotificationChange @ notificationsAlerts.ts:40 (anonymous) @ notificationsAlerts.ts:26 e.fire @ event.ts:145 t.notify @ notifications.ts:113 t.error @ notificationService.ts:48 (anonymous) @ debugSession.ts:590`

**Comment by AnanyaJha** [comment] 2018-10-31 18:36
Hi @isidorn I was wondering what the status was on this bug? Thanks.

**Comment by isidorn** [comment] 2018-10-31 20:29
@AnanyaJha this bug is assigned to november which means I will have some time in november to investigate into it.

**Comment by AnanyaJha** [comment] 2018-10-31 22:30
Ah, I see that now. Great, thank you!

**Comment by isidorn** [comment] 2018-11-09 12:01
@AnanyaJha some time next week the new insiders should arrive and it would be great if you could test out if this issue is fixed for you. Thank you

**Closed** 2018-11-09 12:02 UTC
Labels: debug, under-discussion

**Comment by isidorn** [comment] 2018-11-14 09:09
@AnanyaJha thanks for letting us know. Adding verified label.

**Comment by isidorn** [comment] 2018-11-19 14:52
You should wait for 1.30. Or even better try it with vscode insiders
