### ISSUE TITLE
Full screen overlap issue on multi-display setup

### ISSUE THREAD

**Issue by egorantonov** [microsoft/vscode#66906] opened 2019-01-22 09:49 UTC
- VSCode Version: 1.30.2 
- OS Version: Windows_NT x64 10.0.16299

**Steps to Reproduce:**

1. Have 2 monitors (1920x1200 twice)
2. Open Visual Studio Code (v1.30.2, all extensions are disabled)
3. Go to the full-screen mode (F11)
4. Return back by pressing F11 again 
5. Maximize the window
6. Make the window active

**Expected result**
Visual Studio Code window maximizes and fits one monitor resolution

**Actual result**
Visual Studio Code window maximizes and overlaps second display
(see attached photo)
![Photo:](https://user-images.githubusercontent.com/16327320/51525885-3eb16a00-1e42-11e9-8265-a16bc545de8b.jpg)

**Comment by bpasero** [comment] 2019-01-23 09:34
@egorantonov does it reproduce if you configure `"window.titleBarStyle": "native"`?

**Comment by egorantonov** [comment] 2019-01-23 12:02
nope, only with `"window.titleBarStyle": "custom"`

**Comment by MissingL-tter** [comment] 2019-01-24 16:20
I have had the same issue since I downloaded the "User" version.
I was going to measure the difference in width between `"window.titleBarStyle": "custom"` and `"window.titleBarStyle": "native" and report it here but toggling between the two seems to have gotten rid of it entirely for me.

To be clear I had several pixels of overlap on the secondary monitor with `"custom"` in fullscreen.
I switched to `"native"` and the overlap was gone.
I switched back to `"custom"` and the overlap remained gone.

**Comment by MissingL-tter** [comment] 2019-01-24 18:38
@sbatten Oh, I do not mean borderless fullscreen (f11), I mean a maximized window.

1. Downloaded "User" release of _Code_.
2. Open _Code_.
3. Click Maximize on the title bar.
    - Can visibly see several pixels of the window extend onto the second monitor (right) from the primary monitor (left). We'll call this "bleed".
5. Change `window.titleBarStyle` to `native`.
    - _Code_ window no longer bleeds onto second monitor. 
7. Change `window.titleBarStyle` back to `custom`.
    - _Code_ window still does not bleed over.

**Comment by AshleyFinneyEPS** [comment] 2019-09-05 11:30
Confirmed still active.

VSCode Version: 1.37.1
OS Version: Windows_NT x64 10.0.18362
Steps to Reproduce:

Have 2 monitors (1920x1200 twice)
Open Visual Studio Code
Maximise window
Note that VSCode window is fully filling and contained in one monitor
Go to the full-screen mode (F11)
Return back by pressing F11 again

Expected result
VSCode window should be fully filling and contained in one monitor

Actual result
VSCode window spills into 2nd monitor to the right (also spills to a monitor to the left and above)

**Comment by sbatten** [comment] 2019-09-05 23:56
@deepak1556 let's check this out in exploration builds

**Comment by deepak1556** [comment] 2019-09-06 02:46
@sbatten this is fixed with latest exploration.

**Comment by sbatten** [comment] 2019-10-09 16:57
@deepak1556 assigning to you as you track our electron upgrades

**Closed** 2019-10-10 19:26 UTC
Labels: electron, fixed-in-electron-6.0.x, upstream
