### ISSUE TITLE
Snippet Choice confirm choice should move to next placeholder

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#75594] opened 2019-06-16 16:19 UTC
When I confirm choice on a Snippet Choice options, it just stay at current placeholder and need to hit `Tab` to move to next placeholder. For a better developer experience, I think it should move to the next placeholder automatically. It because I already confirmed the choice, there is no reason stay at current placeholder.

**Comment by tanhakabir** [comment] 2022-04-27 15:45
When I insert the for loop snippet in TS, after I confirm my selection of using the for loop snippet I am automatically taken to renaming the first placeholder. I'm not sure if there are other behaviors I should be expecting?

**Comment by jrieken** [comment] 2022-04-27 16:00
To verify

* have a snippet with choice elements (see below)
* when accept a choice element (wer, wie, was) make sure that the next placeholder is selected

```
"2choice": {
		"prefix": "2choice",
		"body": "${1|wer,wie,was|}? ${2|wieso,weshalb,warum|} ist die ${3:Banane} krumm?"
	},
```

**Comment by jrieken** [comment] 2022-04-28 10:28
@amunger Works for me in TS files... Any special setting for TS for you?

https://user-images.githubusercontent.com/1794099/165733168-1b419aa6-af93-40fa-a393-533295ce0cae.mov

**Comment by jrieken** [comment] 2022-04-28 10:32
I can reproduce with `"editor.suggest.showValues": false`. @amunger Any change you are using that? I'll prepare a fix but I want to make sure there is nothing else going wrong

**Comment by jrieken** [comment] 2022-04-28 12:46
I have pushed a change to ignore filters in this setup. Optimistically close since

**Comment by amunger** [comment] 2022-04-28 17:55
That setting is true for me. I tested this further, and it looks like it only repros for me when the file is saved (looks like that's not the case for you since you're working with a saved file). I can select any language for an unsaved file and the choices come up, but as soon as I save the file, suggestions no longer populate. Same case with python, typescript, C#, markdown

![snippetChoices](https://user-images.githubusercontent.com/2019016/165816697-ba64e8da-f572-4636-8230-3fbba1997e31.gif)

**Comment by jrieken** [comment] 2022-04-29 07:01
Extracted #148406 and closing this

**Closed** 2022-04-29 07:01 UTC
Labels: feature-request, polish, verification-needed, snippets
