### ISSUE TITLE
Open Folder doesn't work when debugging extension

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#112148] opened 2020-12-09 11:35 UTC
* get https://github.com/microsoft/vscode-references-view/
* run `npm i`
* in the run viewlet select "Launch Extension"
* a window without folder or file opens
* select Open Folder from the explorer 
* :bug: nothing happens

[Screen Recording 2020-12-09 at 12.33.13.mov.zip](https://github.com/microsoft/vscode/files/5665573/Screen.Recording.2020-12-09.at.12.33.13.mov.zip)

**Comment by isidorn** [comment] 2020-12-09 11:53
This works for me. I am doing the same as you in your video.
@jrieken and Open Folder just works fine if you try vscode out of source, empty folder (so not while debugging)
Also assigning to @connor4312 and @weinand for extension debug flow and to let me know if we changed something here

@bpasero for open command not doing anything

![recording](https://user-images.githubusercontent.com/1926584/101626454-4b7edd00-3a1d-11eb-8712-192f426b13f5.gif)

**Comment by bpasero** [comment] 2020-12-09 12:47
Would be interesting if something is logged when the open dialog does not open. From time to time I get people complaining that "Open" is not doing anything, so would be very interesting to get at the root of this issue.

I wonder if the fact that you are on Big Sur + Apple SI plays a role here, but I think Isi is also Big Sur.

**Comment by jrieken** [comment] 2020-12-09 12:54
No Apple SI, but Big Sur. It now works, maybe because of the restart I did to get around the keytar issues

**Comment by bpasero** [comment] 2020-12-09 12:55
@jrieken anything in the previous session logs maybe that could shed some light?

**Comment by jrieken** [comment] 2020-12-09 12:58
nothing that I remember, tho I only checked the debug console. is open folder depending on IPC to main process. could that be dead and the same/similar cause the keytar issue?

**Comment by isidorn** [comment] 2020-12-09 13:00
@jrieken yeah I believe it flows through IPC between processes

**Comment by bpasero** [comment] 2020-12-09 13:02
@jrieken yes, it needs a IPC message to main to bring up the native dialog, unless you are using `"files.simpleDialog.enable": true`

**Comment by weinand** [comment] 2020-12-09 17:27
I wasn't able to reproduce this and I'm not aware of this issue in the context of extension debugging.

@bpasero I don't think that the non-functional "Open Folder" action is related to extension debugging. Is this a fair assumption? Or is there anything we (debug) can do?

**Comment by bpasero** [comment] 2020-12-10 07:12
Closing until we have steps or more info.

**Closed by bpasero** 2020-12-10 07:12 UTC
