### ISSUE TITLE
Documentation link broken in interactive editor playground

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#228013] opened 2024-09-09 17:46 UTC
- VS Code Version: 
Version: 1.93.0-insider (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:13:15.344Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26120
- OS Version: Windows 11 Insiders

Steps to Reproduce:

1. Run `Help: Interactive Editor Playground`
2. `documentation` in the first paragraph doesn't appear to be a link, which I was surprised about:

![Image](https://github.com/user-attachments/assets/eb6eb2c8-d7fe-4da7-88c1-f54528a01410)

3. When I hover over it, I see it's supposed to be a link, but clicking on it does nothing:

![Image](https://github.com/user-attachments/assets/24895072-c53b-414f-8a73-32789f11335b)

The other docs links at the bottom of the playground appear correctly as links and do open when I click on them:
![Image](https://github.com/user-attachments/assets/622c0ebc-915b-49ef-8e63-46e7ad092bcd)

**Comment by ntrogh** [comment] 2024-09-10 08:53
@mattbierner This seems related to the bookmark issue we had in the release notes. The other bookmark links in the interactive playground don't work either.

**Comment by mjbvz** [comment] 2024-09-10 21:51
Fixed the toc links. Need another fix for the documentation link too (which use command uris)

**Comment by ntrogh** [comment] 2024-09-13 09:42
@mjbvz The Editor Playground is not showing at all anymore in the latest insiders. When selecting the **Editor Playground** menu item, a black editor comes up.

**Comment by mjbvz** [comment] 2024-09-13 23:44
hm working from oss builds. Insiders, it seems like the error is:

```
vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/browser/editor/vs_code_editor_walkthrough.js net::ERR_FILE_NOT_FOUND
```

**Comment by mjbvz** [comment] 2024-09-13 23:46
Actually unrelated.  Seems like a duplicate of https://github.com/microsoft/vscode/issues/228063 and fixed by https://github.com/microsoft/vscode/pull/228534/files

**Closed by mjbvz** 2024-09-13 23:46 UTC
Labels: bug, interactive-playground
