### ISSUE TITLE
Preferences Sync notification returns after being explicitly turned off

### ISSUE THREAD

**Issue by GaryBoone** [microsoft/vscode#95129] opened 2020-04-13 15:44 UTC
Issue Type: <b>Bug</b>

Following the confusing notification for the Preferences Sync (https://github.com/microsoft/vscode/issues/94927), I figured out how to turn it off via cmd-shift-p: "Preferences Sync: Turn off."

However, the same notification returned again a few days later when I restarted vscode. It appears that this bug occurs whenever a new window is opened:

1) The new window has the Preferences Sync notification

2) The original window again has the Preferences Sync notification, even though it was just turned off in that window.

Turning off Preferences Sync and opening new windows repeats the flaw.

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T19:43:46.226Z)
OS version: Darwin x64 19.4.0

**Comment by RMacfarlane** [comment] 2020-04-13 15:54
Thanks for reporting, duplicate of https://github.com/microsoft/vscode/issues/94888. Should be fixed in today's insiders, which we're working on releasing

**Closed by RMacfarlane** 2020-04-13 15:54 UTC
