### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by dviljoen** [Microsoft/vscode#10844] opened 2016-08-23 14:54 UTC
- VSCode Version:1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open source directory
2. Click search charm (top left) and enter simple text
3. Progress bar indicates a search is in progress
4. No results.
5. I open a source file that I know has the text and search within the file and find multiple occurrences of the same text.

**Comment by bpasero** [comment] 2016-08-24 05:53
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sandy081** [comment] 2016-08-24 07:26
Can you also please check that if the file that has results is not excluded

- Exclusion list under search text box
- Exclusion list in settings `search.exclude`

**Comment by dbaeumer** [comment] 2016-09-05 07:16
Closing. Haven't received any response. @dviljoen please ping if the issue is still reproducible with steps that demo the problematic behavior.

**Closed by dbaeumer** 2016-09-05 07:16 UTC
Labels: needs more info
