### ISSUE TITLE
Word wrap should reset scroll to left

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#66254] opened 2019-01-09 02:36 UTC
When auto wrapping occurs, it does not scroll the editor view back to the left.

**Current behavior**

![vscode](https://user-images.githubusercontent.com/12591890/50872363-00697480-1385-11e9-8b6e-cf06122404fd.gif)

**Desired behavior**

![webstorm](https://user-images.githubusercontent.com/12591890/50872369-095a4600-1385-11e9-8ab1-8142bca0f05f.gif)

**Comment by RMacfarlane** [comment] 2019-01-09 18:13
Duplicate of https://github.com/Microsoft/vscode/issues/47108 and https://github.com/Microsoft/vscode/issues/2654

**Closed by RMacfarlane** 2019-01-09 18:13 UTC
Labels: *duplicate, editor-wrapping
