### ISSUE TITLE
File type incorrectly identified as C++ rather C depending on filename

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#31052] opened 2017-07-19 15:32 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|0.6.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
python|don|0.6.7
EditorConfig|Edi|0.9.4
matlab|Gim|0.5.0
triggertaskonsave|Gru|0.1.2
vscode-dimmer|hoo|2.1.0
docthis|joe|0.4.7
select-part-of-word|mle|1.0.1
cpptools|ms-|0.12.1
indent-rainbow|ode|0.6.1
vscode-clearcase|Ope|1.10.0
vscode-icons|rob|7.10.1
indenticator|Sir|0.4.2
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.0
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Load file called dl_srp_ce.c (and many others with similar names).
2. Shows as C++ at both top of tab and in file browser window and status bar.
3. Rename the file and reload and it correctly shows as C

Reproduces without extensions: Yes, still fails without extensions (as seen in status bar)

**Comment by bpasero** [comment] 2017-07-20 09:30
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/28410701-bfecabea-6d3e-11e7-8f56-3beaf72c2caa.png)

**Comment by BillDenton** [comment] 2017-07-20 09:31
Sorry I meant the filename was "dl_srp_ce.c".

**Comment by bpasero** [comment] 2017-07-20 09:40
@BillDenton also not reproducible, what icon theme are you using? I am using seti:

![image](https://user-images.githubusercontent.com/900690/28411142-3428e9b4-6d40-11e7-8812-155f3e947d6c.png)

**Comment by BillDenton** [comment] 2017-07-20 09:50
I'm using:
"workbench.iconTheme": "vscode-icons",
https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons
![image](https://user-images.githubusercontent.com/17859340/28411468-b92c1b2a-6d38-11e7-8a86-335fc31d1ca8.png)
Without extensions (code --disable-extensions) and no changes in settings:
![image](https://user-images.githubusercontent.com/17859340/28411545-f40b7e0c-6d38-11e7-9450-7c242c72eda6.png)
Without extenssions After changing settings:
"workbench.iconTheme": "vs-seti",
![image](https://user-images.githubusercontent.com/17859340/28411599-2ad76e00-6d39-11e7-9e7e-af9f5db04f5d.png)

**Comment by BillDenton** [comment] 2017-07-20 09:53
Tried again in a folder that doesn't have a .vscode directory and it is OK:
![image](https://user-images.githubusercontent.com/17859340/28411681-7dadfa22-6d39-11e7-8838-b5a56ef37ed8.png)
This is still without any extensions. The "settings.json" is in C:\Users\<my username>\AppData\Roaming\Code\User. So looks like another settings problem. I'll diff this settings.json with my workspace one.

**Comment by BillDenton** [comment] 2017-07-20 09:58
Found the problem. My workspace settings file has a lot of ""files.associations" including:
    "dl_srp_ce.c": "cpp",
I want to use the same settings for all workspaces, so I'll delete my workspace settings.json. It only contains file.associations. I've obviously got confused at some point in the past. Apologies for wasting your time.

**Comment by BillDenton** [comment] 2017-07-20 10:23
I'm not sure how this happened, but I think it may be due to the "Change Language Mode" keyboard shortcut, so I've disabled that. BTW: It would be useful to have a quick way of disabling keyboard mappings from the GUI. The "caused-by-extension" label should be removed, because it was caused by confusion between workspace and user settings.

**Comment by BillDenton** [comment] 2017-07-24 17:02
I'm still having the same problem. My workspace settings (settings.json in <folder>\.vscode) is slowly filling up ""files.associations". The list appears to start from the list in my user settings, but then includes an assortment of files that I have opened (just the filename, not path). Some of these have the correct language type, but others are wrong (e.g. cpp for a .c) file. Could be an extension. I haven't tried running for a significant time with extensions disabled.

**Comment by LegoChicken** [comment] 2017-08-03 10:58
This looks like https://github.com/Microsoft/vscode/issues/27404, as reported fixed in [C/C++ for Visual Studio Code Version 0.12.2](https://marketplace.visualstudio.com/items/ms-vscode.cpptools/changelog). After installing that update it looks like the problem report in my last comment has gone.

**Comment by BillDenton** [comment] 2017-08-04 07:32
This looks like https://github.com/Microsoft/vscode/issues/27404, as reported fixed in [C/C++ for Visual Studio Code Version 0.12.2](https://marketplace.visualstudio.com/items/ms-vscode.cpptools/changelog). ~~After installing that update it looks like the problem report in my last comment has gone.~~ No it hasn't after exiting and opening VS Code, I have in my workspace settings the contents of both my user settings plus "filename.c": "c" (same for "h") for some of the files I have opened.

**Comment by sean-mcmanus** [comment] 2018-01-17 23:28
@BillDenton If there's still a bug with our handling of files.associations can you file an issue at https://github.com/Microsoft/vscode-cpptools/issues ? We added a `C_Cpp.autoAddFileAssociations` setting you can use to disable the adding if it's buggy, but using a glob pattern to set all the system headers to the desired language is probably a better solution (we check those now and won't overwrite it).

**Comment by bpasero** [comment] 2018-01-28 07:13
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2018-01-28 07:13 UTC
Labels: bug, editor
