### ISSUE TITLE
Lag when minimize and maximize VS Code

### ISSUE THREAD

**Issue by Rightusername** [microsoft/vscode#84593] opened 2019-11-12 13:52 UTC
- VSCode Version: 1.40.0
- OS Version: windows 10\ windows 8.1

Steps to Reproduce:

1. Open VS Code in Fullscreen
2. Minimize VS Code window
3. Maximize VS Code window
4. You'll see lag - empty window for few seconds

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2019-11-12 14:51
/duplicate of #84343 

Please provide more details if you are sure that this is not a duplicate.

**Closed** 2019-11-12 14:51 UTC
Labels: *duplicate
