### ISSUE TITLE
cannot connect to marketplace

### ISSUE THREAD

**Issue by brokedevs** [microsoft/vscode#128926] opened 2021-07-17 23:29 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.58.0 | 2d23c42a936db1c7b3b06f918cde29561cc47cd6 | x64
- OS Version: 5.10.49-1-MANJARO

Receiving error message: We cannot connect to the Extension Marketplace at this time, please try again later!

**Comment by tamuratak** [comment] 2021-07-17 23:50
duplicate of #128583

**Closed** 2021-07-18 14:05 UTC
Labels: *duplicate
