### ISSUE TITLE
How to debug node project for specific script command?

### ISSUE THREAD

**Issue by zhouhao27** [Microsoft/vscode#4813] opened 2016-03-31 04:18 UTC
My package.json file:

```
{
  "scripts": {
    "forever": "forever start server.js",
    "db": "mongod --dbpath ./data",
    "nodemon": "nodemon server.js",
    "debug": "concurrently \"npm run db\" \"npm run nodemon\" \"parse-dashboard --config parse-dashboard-config.json --allowInsecureHTTP\"",
    "start": "concurrently \"npm run db\" \"npm run forever\" \"parse-dashboard --config parse-dashboard-config.json\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

Is it possible to use vscode to debug for "npm run debug" ? Thanks.

**Comment by egamma** [comment] 2016-03-31 17:45
// CC @weinand he has answered this question several time before.

**Comment by weinand** [comment] 2016-04-01 16:02
This is a duplicate of https://github.com/Microsoft/vscode/issues/2726.

I've just added an example project that shows how this can be done: https://github.com/Microsoft/vscode/issues/2726#issuecomment-204349900

**Closed by weinand** 2016-04-01 16:02 UTC
Labels: debug, question
