### ISSUE TITLE
Error: No such module: atom_browser_v8_util

### ISSUE THREAD

**Issue by taoabc** [Microsoft/vscode#41721] opened 2018-01-17 03:53 UTC
Match this issue exactly:

[https://github.com/Microsoft/vscode/issues/16321](https://github.com/Microsoft/vscode/issues/16321)

- VSCode Version: 1.19.2
- OS Version: Windows 10 16299.192

Steps to Reproduce:

1. Check follow breakpoints
![image](https://user-images.githubusercontent.com/274097/35024746-3ae9eab2-fb7c-11e7-95d7-ac6a5381bd24.png)
2. Debug electron project
3. If I uncheck those breakpoints, problem gone.
4. If I rename my project folder name, problem gone.

```
Error: No such module: atom_browser_v8_util
    at process.atomBinding (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\common\atom-binding-setup.js:4:14)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\api\browser-window.js:7:24)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\api\browser-window.js:203:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2018-01-18 09:16
- what version of node.js/Electron are you debugging?
- in what way are you renaming the project folder?

**Comment by taoabc** [comment] 2018-01-18 10:53
- what version of node.js/Electron are you debugging?

version 1.7.10

- in what way are you renaming the project folder, i.e. before/after?

my project path is: `C:\Users\taoab\Documents\sln\blackboard`, rename any of these word can fix this. i.e, `C:\Users\taoab\Documents\sln\blackboard-`

- you said that the problem does not occur if you disable extensions. Please try to determine which extension is the culprit.

Sorry, my mistake, I found when I disable all extensions, problem still exist.

![image](https://user-images.githubusercontent.com/274097/35094613-b8a0cf8e-fc80-11e7-8463-159c4f7c7b64.png)

**Comment by weinand** [comment] 2018-01-18 11:09
This might be a duplicate of #30105.
Please add the following to your launch config and see whether this makes a difference:
```json
"env": {
    "ELECTRON_NO_ASAR": null
}
```

**Comment by taoabc** [comment] 2018-01-18 11:38
```
{
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "args": ["${workspaceFolder}"],
      "cwd": "${workspaceFolder}",
      "env": {
        "ELECTRON_NO_ASAR": null
      }
    }
```
After add ELECTRON_NO_ASAR, I can still reproduce this issue

**Comment by taoabc** [comment] 2018-01-18 11:39
I was wonder whether vscode cache something about project path, and cache was broken.

**Comment by weinand** [comment] 2018-01-18 12:01
@roblourens any idea?

**Comment by roblourens** [comment] 2018-01-18 17:29
If you continue past that error, does the electron app run ok anyway? Sometimes electron throws caught exceptions on startup, and this sounds like another of those.

**Comment by taoabc** [comment] 2018-01-19 06:27
If I continue keep press `F5`, it will show plenty of other errors, such as:
```
Error: ENOENT: no such file or directory, stat 'c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\update.exe'
    at fs.existsSync (fs.js:268:13)
    at Object.fs.existsSync (ELECTRON_ASAR.js:379:16)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:84:10)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```
```
Error: Cannot find module 'c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\app\package.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:110:19)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
```
Error: Cannot find module 'c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\app.asar\package.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:110:19)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\electron\dist\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
```
Error
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\util.js:379:12)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\util.js:382:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\promise.js:14:12)
```
```
Error
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\async.js:3:12)
    at Object.<anonymous> (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\async.js:163:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (c:\Users\taoab\Documents\sln\blackboard\node_modules\bluebird\js\release\promise.js:31:13)
```
and so on

**Comment by roblourens** [comment] 2018-01-19 17:07
If it continues past all those errors, then they are just errors thrown and caught internally by different libraries. This is annoying but common. I recommend looking into the skipFiles or smartStep option - you can auto-skip these library files if you set it up correctly.

**Closed by roblourens** 2018-01-19 17:07 UTC
Labels: debug, needs more info
