### ISSUE TITLE
 exception while processing request (exception: Cannot read property 'index' of undefined)

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#655] opened 2015-11-25 19:18 UTC
Issue: <b>81559c42-419d-739b-a6b7-43927bc5d585<b/><br /><br />*Versions* <br />- 0.10.1-release<br />-  94cba4eb314f52fd18b47b72459954fda65302d0<br />-  a4bfcb890dc97f3e0801d8d824d0653e31ab3d44<br />*Stack* <br />[/vs/workbench/parts/debug/node/rawDebugSession.ts#L68:28 (RawDebugSession.send)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L68:28 (RawDebugSession.send))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1470:0 (onError)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1470:0 (onError))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1316:0 (_run)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1316:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L61:5 (V8Protocol.send)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L61:5 (V8Protocol.send))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L127:4 (V8Protocol.dispatch)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L127:4 (V8Protocol.dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L96:11 (V8Protocol.handleData)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L96:11 (V8Protocol.handleData))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L51:8 (V8Protocol.connect)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/node/v8Protocol.ts#L51:8 (V8Protocol.connect))<br />    at Socket.<anonymous> (out/vs/workbench/workbench.main.js:1593:24200)<br />    at emitOne (events.js:77:13)<br />

**Comment by weinand** [comment] 2015-12-01 09:51
duplicate of #30

**Closed by weinand** 2015-12-01 09:51 UTC
Labels: debug, error
