### ISSUE TITLE
[folding] show folding region in gutter with lines

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#25132] opened 2017-04-21 09:28 UTC
**Hi friends, thank for help.
I'm not very used to github. Sorry if my post is not compliant.**

I am looking for an option in visual studio code that would allow me to see the **first level embed**, of function with a line color.

There is a parameter that allows to do this, or a plugin?
I would love to have that opportunity.
It was available in _Notepad ++._

I make a screen shot to help understand.
Look at the red arrow.
I would like something similar.
Show a embed red line to all firsts levels functions. 
![vsc-show-level-fucntion-line](https://cloud.githubusercontent.com/assets/24865815/25257348/6be81528-2605-11e7-9d92-973615d9d313.jpg)

exists an extension, plugin or parameter in vcs to do this.?
Thank a lot guy for help me .

 Otherwise, it would be a great request. :)

**Comment by mjbvz** [comment] 2017-04-21 21:15
A few questions:

* What language are you targeted?
* Can you provide single page code example and screenshots of this behavior in notepad++
* By `first level embed`, do you mean class properties or something else?
* Are you asking for these elements to be a different color, or to actually have a marker showing them?

Does this atom question describe what you are asking for: https://forum.sublimetext.com/t/highlighted-indents-in-sublime-text-3-like-notepad/18661

Thanks

**Comment by elirnm** [comment] 2017-04-24 07:53
Here's some Notepad++ screenshots of what I suspect they mean.

![capture](https://cloud.githubusercontent.com/assets/19817004/25327110/c300cfc4-2887-11e7-8ae5-4813902d4428.PNG)

When you have focus on a line covered by the marker they change color.

![capture3png](https://cloud.githubusercontent.com/assets/19817004/25327149/e85921d6-2887-11e7-9271-d721189d6ecf.PNG)

They appear for any language with code folding (they're basically a visual representation of what would be folded).
![capture2](https://cloud.githubusercontent.com/assets/19817004/25327144/e1f429e4-2887-11e7-8087-ad28e758f057.PNG)

**Comment by aeschli** [comment] 2017-04-25 07:25
Also see #4096

**Comment by djmisterjon** [comment] 2017-04-26 08:29
This is exactly what I need target.
For now, i not find any plugin to help to do this.
i not find any parameter in VSC to allow this.
Can be with extra option, like add random color to help viewing, enable or disable SUB Folding Level

tank a lot guys

**Comment by djmisterjon** [comment] 2017-04-28 11:13
i find something similar 
**"editor.renderIndentGuides": true,**

this help a little , me this need more parametre

**Comment by saidbakr** [comment] 2017-11-11 15:23
This feature is very important to allow follow code blocks.

**Comment by aeschli** [comment] 2018-09-21 13:40
duplicate of #19690

**Closed by aeschli** 2018-09-21 13:40 UTC
Labels: editor-folding, feature-request
