### ISSUE TITLE
Exclude not applied

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226714] opened 2024-08-27 07:12 UTC
Testing #226671

I had this code:

```ts
const results = vscode.workspace.findTextInFilesNew(
{ pattern: 'test' }, 
{
	useExcludeSettings: vscode.ExcludeSettingOptions.FilesExclude,
	// include:['**/test/**', '**/*.ts'],
	exclude: ['**/test/**', '**lru**', '**/binaryMap**', 'test', 'test/**'],
});
```

But I still got results from a workspace `test` folder:

![Image](https://github.com/user-attachments/assets/05897d87-755e-403a-8702-893faeb9ab96)

Full Extension:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	console.log('Congratulations, your extension "search-ts" is now active!');

	const disposable = vscode.commands.registerCommand('search-ts.helloWorld', async () => {
		vscode.window.showInformationMessage('Hello World from search-ts!');

		const results = vscode.workspace.findTextInFilesNew(
			{ pattern: 'test' },
			{
				useExcludeSettings: vscode.ExcludeSettingOptions.FilesExclude,
				// include:['**/test/**', '**/*.ts'],
				exclude: ['**/test/**', '**lru**', '**/binaryMap**', 'test', 'test/**'],
			});

		const asyncIt = results.results;

		const output = vscode.window.createOutputChannel('searchresults');
		output.show();
		for await (const result of asyncIt) {
			if (result instanceof vscode.TextSearchMatchNew) {
				output.appendLine('Result: ' + result.previewText + ", " + result.uri.fsPath);
			} else {
				output.appendLine('Context: ' + result.text);
			}
		}
	});

	context.subscriptions.push(disposable);
}

export function deactivate() { }

```

**Comment by zheung** [comment] 2024-08-27 07:19
I happen to want to report the same problem

When there is only one item in the exclude string, the exclusion is correctly applied.  
When the exclude string contains more than one item, the exclusion is not applied.

![image](https://github.com/user-attachments/assets/5c63f2cb-c536-4063-82f5-159ff1d55be3)

**Comment by andreamah** [comment] 2024-08-28 17:23
@zheung I think that your issue is a duplicate of https://github.com/microsoft/vscode/issues/226830

**Comment by andreamah** [comment] 2024-08-28 20:32
Seems that this only happens when `includes` is not defined. Strange.

**Closed** 2024-08-28 22:03 UTC
Labels: bug, search, confirmed
