### ISSUE TITLE
Output and debug windows are hidding when user try to adjust window height.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5182] opened 2016-04-12 08:16 UTC
- VSCode Version: 1.0.0-alpha
- OS Version: windows10

Steps to Reproduce:
1. Launch app and perform build or debug operation to get output or debug window.
2. Try to adjust height of the window and verify application behavior.
3. Compare the same behavior in visual studio.

Actual: Output/debug window is completely hidden.
Expected: Window title should be visible when user try to adjust minimum height.
![outputwindowpositionissue](https://cloud.githubusercontent.com/assets/17735796/14453818/f09c637c-004b-11e6-817e-a60397248512.gif)

Visual Studio:

![outputwindowposition](https://cloud.githubusercontent.com/assets/17735796/14453942/9c80c0ac-004c-11e6-9ff3-a604c00302f3.png)

**Comment by egamma** [comment] 2016-04-12 13:30
This is consistent with how the side bar behaves and this should not be made inconsistently unless there is a good reason.

**Comment by bgashler1** [comment] 2016-04-12 18:24
@v-pavanp this is currently the intended behavior, but I want to make sure I understand your concern fully.  Is there a need for you to have the Output / Console at a smaller size than is presently allowed?

We try to be helpful in hiding it completely when a user drags it very close to the status bar, but if this is causing any trouble, please let me know more about how it's affecting your workflow so we can look into it.

**Comment by isidorn** [comment] 2017-11-16 13:42
This is consistent with the how the sidebar behaves and no user has complained about this ever. Closing as will not fix

**Closed by isidorn** 2017-11-16 13:42 UTC
Labels: ux, workbench-layout
