### ISSUE TITLE
contextual menu disappears while trying to copy

### ISSUE THREAD

**Issue by mmx64bits** [microsoft/vscode#130912] opened 2021-08-16 15:02 UTC
Issue Type: <b>Bug</b>

1. select a code block using the mouse (in my case, it is a multiline python string enclosed within """ """
2. click the right button to show the menu
     > the menu flashes and disappears.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.0-80-generic
Restricted Mode: No
Remote OS version: Linux arm 5.10.17-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2399)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.54GB (8.33GB free)|
|Process Argv|--unity-launch --crash-reporter-id d5d47ba1-7b35-4ddd-b6bd-72add89a5bb3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin-os-lite|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|zorin-os-lite|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux arm 5.10.17-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 1500)|
|Memory (System)|3.74GB (0.53GB free)|
|VM|0%|
</details>

**Comment by sbatten** [comment] 2021-08-16 16:46
dupe of https://github.com/microsoft/vscode/issues/113175

**Closed by sbatten** 2021-08-16 16:46 UTC
