### ISSUE TITLE
Program Crashes when "File" menu is opened

### ISSUE THREAD

**Issue by Mitchjkjkjk** [microsoft/vscode#231886] opened 2024-10-21 22:23 UTC
Type: <b>Performance Issue</b>

If I try to open the file menu (eg top left, next to edit), the VSCode crashes. Happens whether or not I have anything open.

VS Code version: Code - Insiders 1.95.0-insider (8d8f0cd9d4b25e89621ce897e82f2111eca6a278, 2024-10-15T05:04:26.261Z)
OS version: Linux x64 6.8.0-40-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 4025)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 1, 0|
|Memory (System)|62.21GB (58.52GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id a872703c-2358-40e7-87d2-6f3aa72b5533|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  8905	code-insiders main
    0	     0	  8907	   zygote
    0	     0	  8908	   zygote
    0	   255	  8974	window [1] (Welcome - Visual Studio Code - Insiders)
    0	    64	  8957	   utility-network-service
    0	    64	  9026	   gpu-process
    0	   127	  9062	shared-process
    0	     0	  9508	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  9509	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	  9063	fileWatcher [1]
    0	   319	  9100	extensionHost [1]
    0	    64	  9174	     electron-nodejs (languageserver.js )
    0	    64	  9195	     /snap/code-insiders/1768/usr/share/code-insiders/code-insiders /snap/code-insiders/1768/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9100
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
root-file-viewer|alb|1.3.4
copilot|Git|1.241.1169
copilot-chat|Git|0.22.2024101801
latex-workshop|Jam|10.5.4
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.13.2024101501
python|ms-|2024.17.2024102101
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.10.2024101501
jupyter-hub|ms-|2024.5.1002432242
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.2024101602
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.389.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.87.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
sqltools|mtx|0.28.3
biblatex-snippets|nik|1.0.5
quarto|qua|1.116.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vsc_aa:30263845
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-21 22:30
/duplicate of https://github.com/microsoft/vscode/issues/230604

**Closed** 2024-10-21 22:31 UTC
Labels: *duplicate
