### ISSUE TITLE
Hot Exit Can't undo change

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#17810] opened 2016-12-25 09:43 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

When I refuse the files, I can't refuse the change before exit

**Comment by Tyriar** [comment] 2016-12-25 12:35
What do you mean by refuse the files? Is this about not being able to undo after a restore occurs (#15135)?

**Comment by Jackie-Yang** [comment] 2016-12-26 14:36
@Tyriar Yes~

**Comment by Jackie-Yang** [comment] 2016-12-26 14:36
@Tyriar Sorry, I mean "recover".

**Comment by Tyriar** [comment] 2016-12-26 23:25
Closing as a duplicate of #15135 then, please provide some steps to reproduce the bug if I'm misunderstanding

**Closed by Tyriar** 2016-12-26 23:25 UTC
Labels: hot-exit, needs more info
