### ISSUE TITLE
installation of my extension hang

### ISSUE THREAD

**Issue by mattn** [Microsoft/vscode#9979] opened 2016-07-30 13:22 UTC
- VSCode Version:1.3.1
- OS Version:Windows10

Steps to Reproduce:

1. open extensions panel
2. type `lisp` and install Lisp

![](http://go-gyazo.appspot.com/e5656fa1a78970e8.png)

I can't get something why installation is hang with developer tools.

repository is here

https://github.com/mattn/vscode-lisp

**Comment by kieferrm** [comment] 2016-08-02 04:55
Duplicate of #9933.

**Comment by joaomoreno** [comment] 2016-08-02 07:30
@mattn Are you behind a proxy?

**Comment by mattn** [comment] 2016-08-02 08:17
@joaomoreno Yep now, but I could reproduce this without proxy.

**Comment by mattn** [comment] 2016-08-14 15:12
I figure out this issue. Maybe not duplicate of #9933

When I rename name attribute in package.json to "lisp" (lower case) from "Lisp", I could install my extension. But when rename to "Lisp" again, this issue occured.

**Comment by mattn** [comment] 2016-08-14 15:13
The error occured on https://github.com/Microsoft/vscode/blob/c9a246ad810b9a08f2e5deca95a1248cc03edc73/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L49

**Comment by mattn** [comment] 2016-08-14 15:25
I unpublish "mattn.lisp" at once, and publish "mattn.Lisp" agian. Problem solved.

**Comment by joaomoreno** [comment] 2016-08-15 09:31
Wow, thanks for your findings @mattn! Really cool that you dug it out. It is definitely a problem if the error happens there but never surfaces to the UI. Do you mind trying this out in our latest [insiders build](http://code.visualstudio.com/insiders) and see whether the error shows up in the UI?

**Closed** 2016-08-31 09:29 UTC
Labels: bug
