### ISSUE TITLE
Context menu command "Open in Integrated Terminal" does not use Default Profile

### ISSUE THREAD

**Issue by hotNipi** [microsoft/vscode#132718] opened 2021-09-09 05:57 UTC
Issue Type: <b>Bug</b>

Even if Default Profile is set to use Command Prompt, opening the terminal window with "Open in Integrated Terminal" uses Powershell.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (11.53GB free)|
|Process Argv|--crash-reporter-id f36e67e0-0564-41b9-964a-f1d68d1f289e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by albertosantini** [comment] 2021-09-09 06:22
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery release.

**Comment by IllusionMH** [comment] 2021-09-09 09:18
@albertosantini doesn't look like a duplicate - that issue is about starting VS Code with terminal panel open resulting in having PowerShell.

This one is about different action and reproducible in Insiders that has fix for #132150

Version: 1.61.0-insider (user setup)
Commit: aa93eefe550167de3ca29aaa3d06f721a47594a3
Date: 2021-09-09T05:15:19.597Z

**Comment by DerekZiemba** [comment] 2021-09-10 08:31
Can CONFIRM!  This annoys me to no end!  Just started after I updated vscode the other day.

![GAHHHHH](https://user-images.githubusercontent.com/7283693/132824249-35f3627d-fd55-4669-96a9-ed8dfa79edbe.gif)

Selecting "Select Default Profile" completely ignores what you you set. 

![GAHHHHHHHHHHH](https://user-images.githubusercontent.com/7283693/132824564-aa4e9fdf-23df-43e9-88fc-5c6e99f890e0.gif)

**Comment by aniketicloud** [comment] 2021-09-10 16:15
> Can CONFIRM! This annoys me to no end! Just started after I updated vscode the other day.
> 
> ![GAHHHHH](https://user-images.githubusercontent.com/7283693/132824249-35f3627d-fd55-4669-96a9-ed8dfa79edbe.gif)
> 
> Selecting "Select Default Profile" completely ignores what you you set.
> 
> ![GAHHHHHHHHHHH](https://user-images.githubusercontent.com/7283693/132824564-aa4e9fdf-23df-43e9-88fc-5c6e99f890e0.gif)

I am also annoyed by this

**Closed** 2021-09-10 16:48 UTC
Labels: bug, candidate, terminal, terminal-profiles

**Comment by DerekZiemba** [comment] 2021-09-18 20:17
@Tyriar 

When does the recovery August build release?  I hope it's not actually in August?

**Comment by IllusionMH** [comment] 2021-09-19 16:01
It was released earlier this week already. You need to update to 1.60.1.

No there is no switch, it's easy to have 2 installs as their configs folders and executables don't overlap.

**Comment by hotNipi** [comment] 2021-09-19 16:49
Works like sharm. Thank you all.
