### ISSUE TITLE
`TabsTitleControl.layout()` slows down editor resize

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#34745] opened 2017-09-21 10:22 UTC
* open a diff editor (side-by-side)
* resize via sash:
![kapture 2017-09-21 at 12 08 09](https://user-images.githubusercontent.com/5047891/30690770-8f64855c-9ec5-11e7-91d6-a323d2df7791.gif)

---

* now open two editors side-by-side
* resize via sash:
![kapture 2017-09-21 at 12 20 16](https://user-images.githubusercontent.com/5047891/30691193-40bb8d72-9ec7-11e7-8e4e-55423573e571.gif)

---

Most of the time is spent in two things:
* the find widget: filled #34744
* TabsTitleControl.layout:

![image](https://user-images.githubusercontent.com/5047891/30691250-7675c5b8-9ec7-11e7-8234-43da88e7e79b.png)

**Comment by alexandrudima** [comment] 2017-09-21 10:23
Note: the time TabsTitleControl.layout takes is significantly larger when using the steps in #34716

i.e. 3K+ code lenses.

**Comment by bpasero** [comment] 2017-09-22 06:42
@alexandrudima looks like most time is spend in this call:

![image](https://user-images.githubusercontent.com/900690/30732162-819d3fca-9f71-11e7-9d3a-85f7b8c18c58.png)

I am happy for advice how to avoid that. The tab title control is a `display:flex` container that lays out all tabs. I have seen performance issues before at this location and it seems worse the more tabs are opened. 

I need the `offsetWidth` to update the scrollbar properly that shows when tabs overflow.

Maybe one idea is to buffer the layout calls and not run them sync from the [mouse move listener](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/sash/sash.ts#L161) in the sash widget. 

/cc @joaomoreno

**Comment by alexandrudima** [comment] 2017-09-22 07:22
@bpasero I use various tricks to avoid sync forced layout:
* measuring unknown width/height things at creation time. i.e. if a new tab is added with a custom label, the tab width can be measured when the tab is created/added. If a tab is modified to have a different label, the width can be measured at the modification time.
* keeping track of known widths. If the workbench gets resized, the width of the tabs area can be saved in memory and the DOM would not need to be queried.

IMHO those two bullet points should cover the computation of `scrollWidth` (sum of all tabs width) and `width` (this is something the workbench knows)

**Comment by joaomoreno** [comment] 2017-09-22 10:11
> keeping track of known widths

Yeah, the width should actually only be measured at the top level of a `layout()` call chain. Every step down that chain should split that width up accordingly. The `TabsTitleControl.layout()` method should take a dimension as an argument.

**Comment by bpasero** [comment] 2017-09-29 10:41
The expensive part is indeed the call to `scrollWidth` where Chrome has to compute the size of each tab. Knowing the size of the container is not enough so it turns out to be a matter of caching the sizes for each tab when the tab changes.

**Comment by jrieken** [comment] 2017-11-02 16:10
This is really bad. When opening/reloading the workbench with just *one* tab, ~50ms are spend. That makes it the most expensive single call after code loading and garbage collection. 

<img width="996" alt="screen shot 2017-11-02 at 17 09 22" src="https://user-images.githubusercontent.com/1794099/32336824-a502c706-bff0-11e7-95ba-f9e4517f5e08.png">
[title.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1438478/title.cpuprofile.txt)

**Comment by bpasero** [comment] 2017-11-02 16:30
@jrieken interestingly as soon as I move that layout call into a setTimeout(0) the code is much faster. So just the fact that we force a layout in Chrome during window startup causes a performance of 50ms vs. 0.xms in the other case...

**Comment by jrieken** [comment] 2017-11-03 07:55
The timeline tool tells me that it's causing re-layouts. So with some setTimeout-tricks you might be lucky and get a layout-ed state but I believe the problem is some html-properties are accessed that cause the browser to relayout the whole page.

<img width="772" alt="screen shot 2017-11-03 at 08 53 58" src="https://user-images.githubusercontent.com/1794099/32364361-b6afe4e6-c074-11e7-83b3-e550039db186.png">

**Comment by jrieken** [comment] 2017-11-14 11:00
You we consider something like https://github.com/wilsonpage/fastdom?

**Comment by bpasero** [comment] 2017-11-14 11:27
@jrieken I think `fastdom` is the equivalent of our [`scheduleAtNextAnimationFrame`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/dom.ts#L321) where you can batch operations to run on the next animation frame.

**Comment by bpasero** [comment] 2017-11-15 10:50
Pushed 2 changes:
* for startup: scheduling the layout at next animation frame to avoid the critical path (https://github.com/Microsoft/vscode/commit/f54d16c464ee292a55de7f1f241e2e163830b08e)
* found an issue where within the layout method I would force 2 full layouts because the way code was ordered (https://github.com/Microsoft/vscode/commit/81427242c5be6557be601a3f216b9a5718f98cbb)

The fix of avoiding a second layout call brings some nice performance boost for resizing of editors. 

**Previously**
![image](https://user-images.githubusercontent.com/900690/32831980-517bec2a-c9fa-11e7-9732-44531a13c2a9.png)

**Now**
![image](https://user-images.githubusercontent.com/900690/32831991-5c7c506a-c9fa-11e7-91d0-2922e840635b.png)

The remaining performance issue with tabs is the fact that we access `offsetWidth` as well as scroll via `scrollLeft`. The only fix here is to:
* scroll via absolute positioning (negative `left`)
* remove flex and implement absolute pixel layout for the tabs
* implement custom auto-scrolling behaviour (e.g. when doing DND and reaching tabs that are scrolled away)

I am not a big fan of going away from flex, so I will stop here for now.

@jrieken I extracted the startup perf issue into https://github.com/Microsoft/vscode/issues/38404 so that we have something to close and verify for November. I will keep this issue open and restore it how it was before.

**Comment by jrieken** [comment] 2018-06-04 07:38
>  I will keep this issue open and restore it how it was before.

@bpasero Did we make further improvements to this or why is this closed?

**Comment by bpasero** [comment] 2018-06-04 07:59
Did not want to close this actually, the performance is pretty much the same as before grid land:

![image](https://user-images.githubusercontent.com/900690/40905363-f62648a2-67dd-11e8-84d7-3ee72e436ac8.png)

**Comment by liangya123** [comment] 2018-09-27 10:18
ss

**Comment by bpasero** [comment] 2022-12-06 11:13
Talked with Alex and he is 👍 to close this issue given the changes I have made so far.

**Comment by alexdima** [comment] 2022-12-06 11:13
Yes, the layout is a lot faster for me now:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/5047891/205896793-f17dad1c-970c-44c9-84d3-3bb246538afe.png">

**Closed by bpasero** 2022-12-06 11:13 UTC
Labels: bug, workbench-tabs, perf
