### ISSUE TITLE
file renaming is broken in the latest insiders update

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [Microsoft/vscode#70256] opened 2019-03-11 20:32 UTC
It is impossible to rename a file and get the imports fixed accordingly. Even worse the latest version actively prevents from fixing the imports by hands. So I got the file renamed and the imports are all broken, well I go to fix the imports and rewrite the modules but on saving the changes they return back to old values.

```
Visual Studio Code - Insiders
Version: 1.33.0-insider (system setup)
Commit: d77d8d561143cc021a82664efc056755c075d070
Date: 2019-03-11T08:47:23.627Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by mjbvz** [comment] 2019-03-11 20:53
Please provide a step by step description of how to trigger the issue

**Comment by feelextra** [comment] 2019-03-15 15:12
@mjbvz 
Looks like a duplicate of [#69305](https://github.com/Microsoft/vscode/issues/69305)

**Comment by aleksey-bykov** [comment] 2019-03-15 15:30
@feelextra no, in our case it has nothing to do with file extensions (we don't use them)

**Comment by mjbvz** [comment] 2019-04-29 18:42
Closing as there is not enough information to investigate this issue

**Closed by mjbvz** 2019-04-29 18:42 UTC
Labels: needs more info
