### ISSUE TITLE
how to debug npm scripts link the follow in vscode?

### ISSUE THREAD

**Issue by herrdu** [Microsoft/vscode#33783] opened 2017-09-04 09:31 UTC
- VSCode Version:1.15.1 (1.15.1)
- OS Version:10.12.6

My package.json:
```
{
  "name": "ued-react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts": "1.0.13"
  },
  "scripts": {
    "debug": "react-scripts start",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
My launch.json:
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug"
            ]
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

Steps to Reproduce:

1. Start Launch via NPM,
2.Produced error: "无法连接到运行中的进程，将在10000毫秒后超时 - （原因：无法连接到目标：connect ECONNREFUSED 127.0.0.1:27520）"

Terminal show :"Debugging with inspector protocol because a runtime executable is set.
npm --inspect=27520 --debug-brk run debug "

**Comment by jrieken** [comment] 2017-09-04 09:36
Please provide more information than a title

**Comment by herrdu** [comment] 2017-09-04 09:40
@jrieken  Your react is so fast. Thank you .

**Comment by isidorn** [comment] 2017-09-04 12:29
@herrdu can you please create / share a repository on GitHub which we can clone so we reproduce this issue.
Can you also translate the error message in step 2?

Assigning to @roblourens as this error seems to be coming from `node2`

**Comment by herrdu** [comment] 2017-09-05 08:43
@isidorn  Here is  the repository addr:https://github.com/herrdu/react-in-vscode
I just init a react Project. Then use vscode to debug " npm run start". 

When you cloned thie repository,type 'cd react-in-vscode && yarn install '. It will be fine ,if you type "npm run start " in console. 

But if I  use  launch.json to debug "npm run start ",it will shows the error. 

Am I in a wrong way?

**Comment by isidorn** [comment] 2017-09-05 09:14
@roblourens I can reproduce this, here is the full error in english

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:34624).`

And here is the launch.json I use
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "start"
            ]
        }
]
}
```

**Comment by roblourens** [comment] 2017-09-05 17:47
If you set `"runtimeExecutable": "npm",`, your npm script has to set the debug flag. See the examples here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools

**Comment by herrdu** [comment] 2017-09-06 02:22
@roblourens   I know the flag ?  Your example npm script:
```
  "scripts": {
    "debug": "node --nolazy --debug-brk=5858 myProgram.js"
  },
```
But  how to add the flag in npm script like  
```
 "scripts": {
    "debug": "react-scripts start",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

**Comment by roblourens** [comment] 2017-09-06 03:52
Actually if this is react, do you mean to debug the node side? Or do you want to debug the app in a browser? If so, you probably mean to be using the Chrome debug extension.

**Comment by herrdu** [comment] 2017-09-07 01:56
@roblourens  Of course , I  want to debug node side .  first know about define npm  scripts like that style . I want to know how does it operate. So I debug it in vscode . And I find vscode debugger can't work with this situation.   

Maybe I walk in a wrong way .

**Comment by roblourens** [comment] 2017-09-07 17:12
Well you can try adding the `--inspect-brk` flag to `react-scripts`. Hopefully it should be passed on to node, to start node in debug mode. If that doesn't work, then you'll have to ask the react-script maintainers.

**Closed** 2017-09-14 17:51 UTC
Labels: debug, needs more info
