### ISSUE TITLE
Ctrl+V for ipynb pastes code-portion twice

### ISSUE THREAD

**Issue by MMilczynski** [microsoft/vscode#102600] opened 2020-07-15 14:09 UTC
Issue Type: <b>Bug</b>

Ctrl+V within a ipynb pastes copied code-portion twice

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
plantuml|jeb|2.13.12
MagicPython|mag|1.1.0
vscode-exec-node|mir|0.5.3
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
code-spell-checker|str|1.9.0
material-theme|zhu|3.8.3

(4 theme extensions excluded)

</details>

**Comment by jbiz25** [comment] 2020-07-15 15:08
was just about to submit an issue on this....

**Comment by gjsjohnmurray** [comment] 2020-07-15 15:59
/duplicate of #101946 and due to be fixed in upcoming 1.47.2

**Closed** 2020-07-15 16:00 UTC
Labels: *duplicate, new release
