### ISSUE TITLE
TypeScript build tasks fail (likely new in version 1.64.0)

### ISSUE THREAD

**Issue by klylesatepic** [microsoft/vscode#142449] opened 2022-02-07 23:05 UTC
Issue Type: <b>Bug</b>

Attempt to run a build task (Ctrl+Shift+B) for a TypeScript project.  Both "tsc: build - tsconfig.json" and  "tsc: watch - tsconfig.json" show the issue for me.

I see the following output:
    > Executing task: 'c:\path\to\project\node_modules\.bin\tsc.cmd' -p 'c:\path\to\project\tsconfig.json' --watch <
    
    ParserError: 
    Line |
       1 |  … path\to\project\node_modules\.bin\tsc.cmd' -p 'c:\Epi …
         |                                               ~~
         | Unexpected token '-p' in expression or statement.
    
    The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command 'c:\path\to\project\node_modules\.bin\tsc.cmd' -p 'c:\path\to\project\tsconfig.json' --watch" terminated with exit code: 1.
    
    Terminal will be reused by tasks, press any key to close it.

I played around a little bit, and I suspect that adding a & before the tsc.cmd path would fix things.  I don't have a good way to confirm that, though.

I am reasonably certain that nothing about the project changed to cause this to break -- it was working before I updated to VS Code 1.64.0 and not working after.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (11.06GB free)|
|Process Argv|--crash-reporter-id de677aa9-41d3-4287-920a-b43d425bae91|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.2.0
csharp|ms-|1.24.0
remote-wsl|ms-|0.64.2
powershell|ms-|2021.12.0
vscode-jest|Ort|4.2.1
vim|vsc|1.22.0
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by mjbvz** [comment] 2022-02-09 00:26
Looks like a potential duplicate of #142196.Do you agree @alexr00?

**Comment by alexr00** [comment] 2022-02-09 09:45
Yes, it's a duplicate.

**Closed by alexr00** 2022-02-09 09:45 UTC

**Comment by klylesatepic** [comment] 2022-02-11 15:10
My use case works again as of version 1.64.2.  Thanks for the quick fix!
