### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3504] opened 2016-02-26 15:40 UTC
* Doing the vscode express smoke test I now get errors when I open any .js file that has a require
* e.g www/bin
* is there some setting I am missing

As for the node experience we seem to have worse support than before (what is described in the smoke test)

![screen shot 2016-02-26 at 16 38 18](https://cloud.githubusercontent.com/assets/1926584/13356786/71ebd2f0-dca7-11e5-8ad6-07320f45b6bf.png)

**Comment by joaomoreno** [comment] 2016-02-27 20:00
Duplicate of #3508

**Closed by joaomoreno** 2016-02-27 20:00 UTC
Labels: js
