### ISSUE TITLE
No support for tmTheme background colors

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#18542] opened 2017-01-14 08:06 UTC
- VSCode Version: All versions
- OS Version: macOS Sierra 

`.tmTheme` definitions can have background colors specified with `background` keys such:
```xml
<!-- Number -->
<dict>
    <key>scope</key>
    <string>constant.numeric</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#8fc2bbbb</string>
        <key>background</key>
        <string>#8fc2bb0f</string>
    </dict>
</dict>
```
and vscode provides on such support for this. A theme like NeonGlow that normally looks like this:

<img width="775" alt="screen shot 2017-01-14 at 11 33 46 am" src="https://cloud.githubusercontent.com/assets/2157285/21953470/9faaf08c-da4d-11e6-8e43-c6fcdf16b971.png">

In vscode looks like:

<img width="874" alt="screen shot 2017-01-14 at 11 33 02 am" src="https://cloud.githubusercontent.com/assets/2157285/21953474/ac2d6fd8-da4d-11e6-8e4c-a4a8e9262c05.png">

**Comment by aeschli** [comment] 2017-01-19 10:16
duplicate of #3429

**Closed by aeschli** 2017-01-19 10:16 UTC
Labels: themes

**Comment by pmkary** [comment] 2017-01-19 11:33
@aeschli nice...
