### ISSUE TITLE
organizeImports deletes modules in use

### ISSUE THREAD

**Issue by ozum** [Microsoft/vscode#49193] opened 2018-05-04 09:06 UTC
Issue Type: <b>Bug</b>

## Expected Result:
```js
import babel from "./babelrc";
export = { babel };
```

## Actual Result:
```js
export = { babel };
```

## Steps to reproduce

* Add below setting to VSCode
```
"editor.codeActionsOnSave": {
     "source.organizeImports": true
}
```

* Paste code below into editor
```js
import babel from "./babelrc";
export = { babel };
```

* Save file and see import dissapeared.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.4.0

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.47
vscode-generate-getter-setter|DSK|0.5.0
EditorConfig|Edi|0.12.1
material-icon-theme|PKi|3.3.0
code-settings-sync|Sha|2.9.2
pegjs-language|Sir|0.1.0
quokka-vscode|Wal|1.0.121
vscode-node-readme|ben|3.0.2
handlebars-preview|cha|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.8
vscode-dash|dee|1.10.0
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
vscode-great-icons|emm|2.1.31
prettier-vscode|esb|1.3.1
nearley|kar|1.0.2
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.6
debugger-for-chrome|msj|4.3.0
chai-snippets|nwh|0.1.0
vscode-code-outline|pat|0.1.1
LiveServer|rit|3.2.1
vscode-icons|rob|7.23.0
markdown-preview-enhanced|shd|0.3.5
autoimport|ste|1.5.3
open-in-browser|tec|1.1.0
code-navigation|vik|0.2.0
better-align|wwm|1.1.6

(4 theme extensions excluded)

</details>

**Comment by GankLanceman** [comment] 2018-05-04 15:02
This is the same issue I am experiencing. The setting does not seem to be respecting the ES6 object literal property value shorthand. 

If you need a temporary workaround you can define the object like so:
```
import babel from "./babelrc";
export = { babel: babel };
```
and then the organizeImports setting will function as expected.

**Comment by mjbvz** [comment] 2018-05-04 17:45
Duplicate of https://github.com/Microsoft/TypeScript/issues/23308

Should be fixed in insiders

**Closed by mjbvz** 2018-05-04 17:45 UTC
Labels: new release

**Comment by rebelliard** [comment] 2018-05-11 12:34
After today's update of VSCode, `organizeImports` worked on most of my `.jsx` files except for:

	import faPlay from '@fortawesome/fontawesome-free-solid/faPlay'
	import faPause from '@fortawesome/fontawesome-free-solid/faPause'
	import faStop from '@fortawesome/fontawesome-free-solid/faStop'
	import faStepForward from '@fortawesome/fontawesome-free-solid/faStepForward'
	import faStepBackward from '@fortawesome/fontawesome-free-solid/faStepBackward'
	import faEject from '@fortawesome/fontawesome-free-solid/faEject'
	import faExpandArrowsAlt from '@fortawesome/fontawesome-free-solid/faExpandArrowsAlt'
	
	/**
	 * @see https://github.com/FortAwesome/react-fontawesome#build-a-library-to-reference-icons-throughout-your-app-more-conveniently
	 */
	export {
	  faPlay as Play,
	  faPause as Pause,
	  faStop as Stop,
	  faStepBackward as StepBackward,
	  faStepForward as StepFoward,
	  faEject as Eject,
	  faExpandArrowsAlt as FullScreen,
	}
	

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2556)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.39GB (2.25GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.1
bracket-pair-colorizer|Coe|1.0.48
vscode-markdownlint|Dav|0.15.0
EditorConfig|Edi|0.12.1
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
vscode-custom-css|be5|2.7.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
mustache|daw|1.1.1
jshint|dba|0.10.18
githistory|don|0.4.0
eslint-disable-snippets|drK|1.1.4
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
debugger-for-chrome|msj|4.4.3
vscode-code-outline|pat|0.2.0
vscode-icons|rob|7.23.0
vscode-fileutils|sle|2.8.1
es6-mocha-snippets|spo|0.1.3
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.6.2
ReactSnippets|xab|2.1.0

(2 theme extensions excluded)

</details>
