### ISSUE TITLE
Potential breakpoint locations shown on every line in file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81986] opened 2019-10-05 00:17 UTC
Issue Type: <b>Bug</b>

**Repo**
Not sure of exact repo steps. Here's how I can reproduce the bug:

1. Start an oss build of VS Code
1. From insiders, attach to extension host and start debugging one of our built-in extensions
1. Hit a breakpoint in the extension.
1. Now delete some lines in the file (possible the one where the breakpoint was)
1. Detach and reattach the debugger

**Bug**
Potential break point locations are show on every line of the file

![Screen Shot 2019-10-04 at 4 50 57 PM](https://user-images.githubusercontent.com/12821956/66246672-a525a200-e6ca-11e9-9281-8ff1ebeb3824.png)

VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:23:20.797Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_3486547|
|Screen Reader|no|
|VM|18%|
</details>

**Comment by isidorn** [comment] 2019-10-07 07:52
I can not reproduce this following your exact steps. 
Though I see that on line deletion there are some left-over candidate locations. Though I can not get in the "extreme" case that you got here.
imho this is a corner case which we should fix on insiders not as a candidate

**Comment by isidorn** [comment] 2019-10-07 11:38
Chrome simply does not show any candidates if the file gets changes. We can do something similar.

**Comment by Clancey** [comment] 2019-10-15 00:02
This started happening to me after upgrading to Catalina. It happens on both 1.39 and  the 1.40 releases

```Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0```

**Comment by Clancey** [comment] 2019-10-15 00:04
When I set breakpoints without debugging enabled they set properly. When I start debugging no break points work until I reset them. When I set them a second time I get the behavior listed in this bug report.  In my debug output, I see:
```Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:96:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:96:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)```

**Comment by isidorn** [comment] 2019-10-15 08:44
@Clancey can you provide exact repo steps, with a potential repository?
@mjbvz more precise repro steps from you would also be appreciated. Thanks

**Comment by Clancey** [comment] 2019-10-15 22:12
It's not a public repo, however I think I narrowed it down. It has to do with WebPack.

**Comment by isidorn** [comment] 2019-10-16 08:31
If it is webpack related than it seems that the node debugger is returning strange candidates for a line. Thus also assigning to @roblourens

**Comment by roblourens** [comment] 2019-10-17 23:46
I think this stuff falls under https://github.com/microsoft/vscode-chrome-debug-core/issues/531 (the DA should be sure to only return breakpointLocations for the line that was requested) so I will close it as a dupe

**Closed by roblourens** 2019-10-17 23:46 UTC
Labels: bug, debug
