### ISSUE TITLE
VSCode hitting 70%+ CPU

### ISSUE THREAD

**Issue by jonmill** [microsoft/vscode#70989] opened 2019-03-22 23:14 UTC
Issue Type: <b>Performance Issue</b>

This happens after having one medium-sized .NET Core solution with one ReactJS project

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    73	  2744	code main
    1	    68	  1416	   window (Issue Reporter)
   27	   237	  5512	   window (Common.csproj - platform - Visual Studio Code)
    0	    10	 17448	     watcherService 
    0	     4	 15680	       console-window-host (Windows internal process)
   13	  1354	 17960	     extensionHost
    0	     2	 18544	       cmd /s /c "C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe -s c:\Users\JonathanMiller\Repositories\platform\src\platform.sln --hostPID 17960 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	     4	 18232	         console-window-host (Windows internal process)
    0	    71	 20988	         C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe  -s c:\Users\JonathanMiller\Repositories\platform\src\platform.sln --hostPID 17960 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    21	 18940	       C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\rzls.exe -lsp --logLevel None
    0	     4	 11316	         console-window-host (Windows internal process)
    0	    16	 19824	       electron_node server.js 
    0	    53	  5780	   shared-process
    1	   330	  6580	   gpu-process
   41	   382	 14580	   window (● VersionTrackerService.cs - ProductManagement - Visual Studio Code)
    0	    12	  2780	     watcherService 
    0	     4	  7440	       console-window-host (Windows internal process)
    0	     9	 14352	     electron-crash-reporter
    0	    35	 16556	     searchService
   14	  1554	 18304	     extensionHost
    0	    23	  5368	       C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\rzls.exe -lsp --logLevel None
    0	     4	  4264	         console-window-host (Windows internal process)
    0	    19	  8012	       electron_node tsserver.js 
    0	    19	 15584	         electron_node typingsInstaller.js typesMap.js 
    0	    31	 13512	       "C:\Users\JonathanMiller\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\JonathanMiller\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=18304
    0	    18	 18760	       electron_node server.js 
    0	     3	 20132	       cmd /s /c "C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe -s c:\Users\JonathanMiller\Repositories\ProductManagement\src\src.sln --hostPID 18304 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	   182	 12564	         C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe  -s c:\Users\JonathanMiller\Repositories\ProductManagement\src\src.sln --hostPID 18304 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\JonathanMiller\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	     5	 21368	         console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● VersionTrackerService.cs - ProductManagement - Visual Studio Code)
|  Window (Common.csproj - platform - Visual Studio Code)
|    Folder (ProductManagement): 304 files
|      File types: json(51) cs(46) dll(41) js(40) cache(30) map(14) pdb(9)
|                  css(7) html(6) ico(6)
|      Conf files: csproj(3) package.json(2) launch.json(1) tasks.json(1)
|                  sln(1)
|      Launch Configs: coreclr(2)
|    Folder (platform): 7999 files
|      File types: dll(5906) cs(560) cache(284) json(277) js(208) pdb(176)
|                  map(97) xml(70) txt(46) css(41)
|      Conf files: csproj(16) package.json(7) settings.json(3) launch.json(1)
|                  tasks.json(1) sln(1)
|      Launch Configs: coreclr(6);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.25.0
xml|Dot|2.4.0
prettier-vscode|esb|1.8.1
dotnet-test-explorer|for|0.6.5
vscode-pull-request-github|Git|0.5.1
graphql-for-vscode|kum|1.13.0
azure-pipelines|ms-|1.147.2
vscode-azureappservice|ms-|0.13.0
vscode-azurestorage|ms-|0.7.0
mssql|ms-|1.4.0
python|ms-|2019.2.5558
azure-account|ms-|0.8.0
azurecli|ms-|0.4.4
csharp|ms-|1.17.1
vscode-node-azure-pack|ms-|0.0.5
azurerm-vscode-tools|msa|0.5.0
vscode-coverage-gutters|rya|2.3.1
vscode-icons|vsc|8.3.0

</details>

**Comment by sallyamoore** [comment] 2019-03-23 00:17
I'm having a similar issue, but with my CPU hitting 102% on mac os 10.14.2 using Python

**Comment by isidorn** [comment] 2019-03-25 09:22
Follow this steps to file a good issue please. Thanks
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by jonmill** [comment] 2019-03-25 18:23
@isidorn - since this is a main window scenario, here is the attached javascript profile


[CPU-20190325T112243.zip](https://github.com/Microsoft/vscode/files/3004881/CPU-20190325T112243.zip)

**Comment by isidorn** [comment] 2019-03-26 08:53
@jonmill thanks for the profile. But can you reproduce with .NET core extension disabled?
If not, please file this issue with the profile to their extension repo

**Comment by jonmill** [comment] 2019-03-26 16:14
@isidorn - since @sallyamoore is having this issue while using Python, this appears to not be related to .NET Core

**Comment by sallyamoore** [comment] 2019-03-26 16:19
> Follow this steps to file a good issue please. Thanks
> https://github.com/Microsoft/vscode/wiki/Performance-Issues

Sorry about that, I'll provide full context the next time this happens. I restarted my machine immediately after replying and it hasn't happened since, but it has been an intermittent issue for a least the past few weeks. Will keep you updated.

**Comment by sallyamoore** [comment] 2019-03-26 16:26
> @jonmill does not really work that way. He might have an issue with the python extension.
> Please try reproducing withou the .NET core extension and with plain vscode insiders https://code.visualstudio.com/insiders/

I'm a she.

**Comment by isidorn** [comment] 2019-03-26 16:27
Apologies.

**Comment by jonmill** [comment] 2019-03-26 16:33
@isidorn - this is not an immediate repro, it takes time and isn't 100%. Moving my entire dev flow to not have intellisense and symbol lookup while waiting for this to repro isn't very reasonable and would definitely cause a loss for my company.

Could you please explain why it's necessary to jump through those hoops when we have provided two use cases using different extensions, a full profiling, and full information showing the problem in the main render window? This seems like it should be enough information to at least investigate on your end.

**Comment by isidorn** [comment] 2019-03-26 16:53
Looking at the cpu profile this seems to be coming from electron.asar. Internal crypto
Forwarding to @bpasero who would know more

![Screenshot 2019-03-26 at 17 52 59](https://user-images.githubusercontent.com/1926584/55016930-066c0a80-4ff0-11e9-99c9-05c821f0b129.png)

**Comment by jonmill** [comment] 2019-03-26 16:56
Thanks for the quick follow-up @isidorn!

**Comment by bpasero** [comment] 2019-03-26 17:08
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by Geekz45679** [comment] 2019-03-27 22:50
> We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
> * Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

@bpasero 
I'm also having this issue on the Insiders build (1.33.00-insider, MacOS Mojave 10.14.3), however I can't seem to reproduce it on the Exploration build, which is good. I can provide more information if needed.

**Comment by jonmill** [comment] 2019-04-01 02:47
Agreed; @bpasero - is there a general ETA for the move to electron 4.0.x to get to stable? Nothing concrete, but any general timeframe would be appreciated

**Comment by bpasero** [comment] 2019-07-01 06:23
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-07-01 06:23 UTC
Labels: electron, fixed-in-electron-4.0.x, upstream
