### ISSUE TITLE
Default settings file gives warnings

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2956] opened 2016-02-12 07:59 UTC
Complains on e.g. `"git.path": null,`. Pops up after I edit my user `settings.json` and save. I'm on Win7, VSCode 0.10.8.

> Incorrect type. Expected "String"
> \settings.json(154,14)

![image](https://cloud.githubusercontent.com/assets/1297882/13001459/691e095a-d166-11e5-80f2-b7bcc4410eff.png)

**Comment by aeschli** [comment] 2016-02-12 08:48
duplicate of https://github.com/Microsoft/vscode/issues/2856

**Closed by aeschli** 2016-02-12 08:48 UTC
