### ISSUE TITLE
If more than 300,000 line, "editor.wordWrap" doesn't work

### ISSUE THREAD

**Issue by LKHell** [Microsoft/vscode#32997] opened 2017-08-23 02:31 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

If file more than 300,000 line,  ("editor.wordWrap": "on" )  doesn't work.

OR It's my computer problem?

无意间打开了一个300,977的txt（utf-8）文档，发现自动换行失效，反复切割文档，得到300,000是自动换行的上限的结论

**Comment by yume-chan** [comment] 2017-08-23 03:40
Duplicate of #32992.

**Closed** 2017-08-23 09:07 UTC
Labels: editor, editor-core, new release
