### ISSUE TITLE
Open file (Ctrl+O) should use directory of currently edited file as starting point

### ISSUE THREAD

**Issue by bialix** [Microsoft/vscode#6532] opened 2016-05-19 12:32 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Open folder in the VSCode with many subdirectories
2. Navigate to some file in sub-sub directory and start to edit it
3. Press Ctrl+O to open other file from the same directory of currently edited file
4. But open file dialog starts with something really different directory, probably with directory I last used Ctrl+O with.
5. That's counter-intuitive and in usual Visual Studio it works the way I expect it to behave.

Should I enable some hidden config rule to get desired behaviour?

**Comment by Tyriar** [comment] 2016-05-19 18:11
Related: https://github.com/Microsoft/vscode/issues/3988

**Comment by bpasero** [comment] 2016-05-30 16:10
Duplicate of https://github.com/Microsoft/vscode/issues/1210

**Closed by bpasero** 2016-05-30 16:10 UTC
Labels: feature-request, files
