### ISSUE TITLE
Integrated terminal content is clipped on the left.

### ISSUE THREAD

**Issue by abhyankarsunil** [Microsoft/vscode#7354] opened 2016-06-07 20:30 UTC
- VSCode Version:1.2.0
- OS Version:Window 10 1511 Version: 10586.318

Steps to Reproduce:

1. Use your mouse scroll wheel to scroll up in the integrated terminal window
2. Content moves to the left and is clipped.
I am unable to move the cursor or use the mouse to bring the content back in view. Have to close the window and reopen it to see content normally.
![integrated terminal issue screenshot](https://cloud.githubusercontent.com/assets/4654937/15873513/ec4e42b0-2cb3-11e6-96cd-433b2c501ebb.PNG)
 See attached screenshot.

**Comment by Tyriar** [comment] 2016-06-07 22:24
Duplicate of https://github.com/Microsoft/vscode/issues/6738

**Closed by Tyriar** 2016-06-07 22:24 UTC
