### ISSUE TITLE
Missing button for deleting individual watches

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#25071] opened 2017-04-20 09:59 UTC
VSCode: 1.11.2

What has happened to the "X" button in watches?

Previously (I'm not sure exactly what versions, but at least v1.7), it was possible to click a cross button to the right of each individual watch expression to remove it. Now it seems the only way to delete an individual watch is to edit it to a blank string - this is a bit tedious.

Was this removed on purpose? If not, could you put them back please.

**Comment by isidorn** [comment] 2017-04-24 13:27
yes this was removed on purpose and we do not plan to put it back because there are already more than enough ways to remove a breakpoint (context menu, remove all bps action in title bar, clicking in the glyph margin, using the command palette)
Closing as designed

**Closed by isidorn** 2017-04-24 13:27 UTC
Labels: debug, ux

**Comment by adelphes** [comment] 2017-04-24 17:59
Breakpoints? This issue is about watches.

I can't find any command palette items for manipulating watches, you can't click in the glyph margin for watches and the description clearly states that this is about removing _individual_ watches (so the remove-all button is useless).

**Comment by isidorn** [comment] 2017-04-25 09:02
Sorry I misread your initial comment.
Yes, that is now only possible using the context menu and using the delete key when you focus the watch or `cmd + back` on mac
