### ISSUE TITLE
Server returned 503

### ISSUE THREAD

**Issue by nphara** [Microsoft/vscode#57881] opened 2018-09-04 15:18 UTC
Issue Type: <b>Bug</b>

"Server returned 503" on Check for Updates. It's not possible to Find Extensions on Store. Update-help doesn't work also.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.86GB (6.40GB free)|
|Process Argv|C:\Users\nayuki.hara\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
mdmath|goe|2.3.2
vscode-language-pack-pt-BR|MS-|1.24.3
cpptools|ms-|0.18.1
platformio-ide|pla|1.1.0
markdown-preview-enhanced|shd|0.3.5

</details>

**Comment by igorbb** [comment] 2018-09-04 16:03
https://blogs.msdn.microsoft.com/vsoservice/?p=17405

Also this seems to be a duplicate of :

#57851

**Comment by JuanMagos** [comment] 2018-09-04 16:28
![image](https://user-images.githubusercontent.com/35541642/45044393-a010a200-b035-11e8-8027-7ce741edaf5b.png)

**Closed** 2018-09-04 17:47 UTC
Labels: *duplicate
