### ISSUE TITLE
'Go back' do not go back to the original tab

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode#141525] opened 2022-01-26 05:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open file `a.c` on left editor group
2. Press 'Split Editor Right' button to open `a.c` on the right editor too
3. Move focus back to `a.c` on the left group by click it's tab
4. Jump from `a.c` on the left to another file `b.c` by `Cmd+Click` (Go to definition)
5. Go back to `a.c` on the left by `Ctrl + -`

Except: focus back to the `a.c` on the left group
Actual happened: focus move to the `a.c` on the right group

**Comment by yume-chan** [comment] 2022-01-26 06:27
Duplicate of #9526 (https://github.com/microsoft/vscode/issues/9526#issuecomment-629421111)

**Closed** 2022-01-26 06:46 UTC
Labels: *duplicate
