### ISSUE TITLE
Auto update import adds `.js` to `.json`

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#79563] opened 2019-08-21 09:29 UTC
- [x] Look for existing issues
- [x] Checked latest build

- VSCode Version: 1.37.1
- OS Version: MacOs 10.13.6

Steps to Reproduce:

1. Create a folder called v1.0.0
2. Create files a.json and b.json inside v1.0.0 folder
3. Create index.js file inside v1.0.0 folder and add `export.a = require('./a.json');` and for b.
4. Rename folder v1.0.0 to something else (like `v1.0`)
5. Code asks if you want to update imports. Click yes.
6. Code opens files and shows it cannot resolve new imports as the files do not exist. `require` now shows `require('./a.json.js')`

Does this issue occur when all extensions are disabled?: Yes

Additional info:

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

---

As an aside... wow this is actually really cool! Super job on adding this functionality in the first place!
Update notes where it's mentioned for reference: https://code.visualstudio.com/updates/v1_24#_update-import-paths-when-a-file-is-moved-or-renamed

**Comment by mjbvz** [comment] 2019-08-21 17:50
Thanks. I believe this issue has the same root cause as https://github.com/microsoft/TypeScript/issues/30550

Closing as upstream

**Closed by mjbvz** 2019-08-21 17:50 UTC
Labels: javascript
