### ISSUE TITLE
Repeat rendering in terminal panel after resizing and scrolling

### ISSUE THREAD

**Issue by Gu-Miao** [microsoft/vscode#232557] opened 2024-10-30 06:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

https://github.com/user-attachments/assets/1e2e32c7-4f83-4b43-8a44-e17350900d4e

1. Input something
2. Resize the terminal panel
3. Scroll
4. Repeat 2 and 3

**Comment by KasperZutterman** [comment] 2024-10-30 08:08
I have the same issue when opening & resizing vertical tabs:
![Recording](https://github.com/user-attachments/assets/67649bba-dfb1-4f3f-8e8a-032badc9feb5)

**Comment by meganrogge** [comment] 2024-10-30 19:38
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-10-30 19:38 UTC
Labels: new release
