### ISSUE TITLE
you can remove input fields when pasting in strange symbols like ⃞⃟

### ISSUE THREAD

**Issue by Mikey-y** [microsoft/vscode#176877] opened 2023-03-12 01:56 UTC
https://user-images.githubusercontent.com/102811601/224519916-a22ff432-07d7-4add-a86e-f9790453c30d.mp4

**Comment by iUnstable0** [comment] 2023-03-12 06:35
there's many other symbols that can achieve the same effect as that, I've seen it before. I forgot which though

**Comment by hediet** [comment] 2023-03-21 10:06
Already the browser default text area has this problem:

![chrome_ni7QCv95zw](https://user-images.githubusercontent.com/2931520/226574424-b5bab0f7-e15a-41f7-ae1d-a958d5b18357.gif)

I think this is a very specific edge case und the current behavior probably is even by design, thus closing this issue.

**Closed by hediet** 2023-03-21 10:06 UTC
