### ISSUE TITLE
Hangs while scrolling

### ISSUE THREAD

**Issue by piyushparkash** [Microsoft/vscode#22598] opened 2017-03-14 11:42 UTC
I am using Visual Studio Code v1.10.2. Scrolling is not smooth for the files. I have a PHP file of roughly 300 lines. If I scroll it will stop at the point where I started scrolling skip most the scroll and then almost reach the endpoint of the scroll and scroll till the endpoint. I hope you got me. I will try to get a video of this.

But If I have to update any extension, after updating the extension it will give me option to reload the window. If I reload the window, this problem will be gone and it will scroll smoothly even If I close the window and reopen it.

I hope I was clear. Let me know if I can help you with any more information.

- VSCode Version: 1.10.2
- OS Version:Microsoft Windows 10 Home Single Language

**Comment by weinand** [comment] 2017-03-14 11:56
This sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by piyushparkash** [comment] 2017-03-15 17:06
OK. Will try this and let you know the result.

**Comment by weinand** [comment] 2017-03-19 18:07
Any update on this?

**Comment by piyushparkash** [comment] 2017-03-21 02:13
I tried it. The problem is not happening very frequently now, but still happening.

**Comment by alexandrudima** [comment] 2017-03-28 12:19
@piyushparkash When you say you scroll, do you mean you scroll with the trackpad or with an external mouse scroll wheel?

**Comment by piyushparkash** [comment] 2017-03-28 13:32
Trackpad

**Comment by alexandrudima** [comment] 2017-03-28 14:33
Let's track in #12637 or #13612

It is an issue in the current Electron/Chromium version we're using. Workarounds include "restoring" the window and maximizing it back up (works for my Surface Book). The issue is already fixed in Chromium and with the next Electron update we should get the fix.

**Closed by alexandrudima** 2017-03-28 14:33 UTC
Labels: needs more info
