### ISSUE TITLE
npm command prompt not working 

### ISSUE THREAD

**Issue by chintan9** [Microsoft/vscode#7341] opened 2016-06-07 17:34 UTC
- VSCode Version:1.2.0
- OS Version:win10 10240

Steps to Reproduce:

1. open vscode and  change workspace setting 

`
    // The path of the shell that the terminal uses on Windows.
`
`
    "terminal.integrated.shell.windows": "C:\\windows\\system32\\cmd.exe",
`
to 
`
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe /k 'C:\\Program Files\\nodejs\\nodevars.bat'",
`

2.  use `ctrl+'`'`

**Comment by Tyriar** [comment] 2016-06-07 18:30
Closing as duplicate of https://github.com/Microsoft/vscode/issues/7266, you might be able to create a .bat file and set that are the shell, but not args as of yet.

**Closed by Tyriar** 2016-06-07 18:30 UTC

**Comment by chintan9** [comment] 2016-06-07 20:51
download file and put into nodejs folder ('C:\Program Files\nodejs\)


 open vscode and  change workspace setting 

`
    // The path of the shell that the terminal uses on Windows.
`
`
    "terminal.integrated.shell.windows": "C:\\windows\\system32\\cmd.exe",
`
to 
`
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe /k 'C:\\Program Files\\nodejs\\npm-cmd.bat'",

[https://github.com/chintan9/chintan9.github.io/commit/60919517e0ae66a30603ea4b27c3497e3712e2d2](url)

**Comment by chintan9** [comment] 2016-06-07 20:51
https://github.com/chintan9/chintan9.github.io/commit/60919517e0ae66a30603ea4b27c3497e3712e2d2
