### ISSUE TITLE
Outline in jupyter notebook explorer does not update

### ISSUE THREAD

**Issue by firezym** [microsoft/vscode#190715] opened 2023-08-18 02:12 UTC
Type: <b>Bug</b>

The issue happens in jupyter notebook file. When I add a new markdown cell and create more outline titles, e.g. `# test outline2`, the OUTLINE in the EXPLORER in on the left side window does not automaticly update until I click other icons on the left side bar (e.g. `search` or `source control`) then click back to `Explorer`. That is very unconvenient. It is ok on the previous insider version.

VS Code version: Code - Insiders 1.82.0-insider (ccb95fd921349023027a0df25ed291b0992b9a18, 2023-08-17T05:33:29.141Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.93GB (100.84GB free)|
|Process Argv|--crash-reporter-id 37912040-c721-4ea4-9cc9-539e301e87e2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3400)|
|Memory (System)|98.23GB (95.56GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.305.0
remote-wsl|ms-|0.81.0
vscode-highlight|fab|1.8.0
copilot|Git|1.104.343
copilot-chat|Git|0.7.2023081701
rainbow-csv|mec|3.7.0
vscode-docker|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.7.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
datawrangler|ms-|0.15.3
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
markdown-all-in-one|yzh|3.5.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by DonJayamanne** [comment] 2023-08-18 05:01
Duplicate of https://github.com/microsoft/vscode/issues/190631

**Closed by DonJayamanne** 2023-08-18 05:01 UTC
