### ISSUE TITLE
Not reporting tsc compile errors correctly in the problems view

### ISSUE THREAD

**Issue by httpdigest** [Microsoft/vscode#12390] opened 2016-09-21 15:49 UTC
- VSCode Version: 1.6.0-insider (commit: 90dda7af)
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create a project with Angular CLI
2. Observe, that the tsconfig.json is _not_ in the root directory of the project, but under src/
3. Add a _readonly_ class member field "readonly readOnlyProperty" to a class
4. Add a method to this class which assigns to `this.readOnlyProperty`
5. Observe that the editor does not flag this as an error
6. Add a typescript compilation task in Visual Studio Code with `"args": ["-p", "src"]`
7. Execute that task
8. Observe that there is no error output
9. Execute `tsc -p src` from the command line (using the same tsc version)
10. Observe that the "assignment to readonly field" error is shown

Also, it looks like other errors, such as real syntax errors, are only reported as warnings in the Visual Studio Code editor "problems" view, whereas the tsc command line compiler flags them as real errors.

It might have something to do with the tsconfig.json file _not_ residing under the root of the project, but inside the "src/" directory, as seems to be best-practice with Angular 2 projects. At least this is how Angular CLI creates the project.

**Comment by chrmarti** [comment] 2016-09-21 18:29
I've added this class to the main.ts of a new created Angular2 project:
```
class MyClass {
  public readonly foo = 2;
  public bar() {
    this.foo = 3;
  }
}
```
That correctly shows an error in the editor. I chose to use Typescript 2.0.2 when asked by VS Code if I wanted to use the version installed in the workspace. Which version of Typescript are you using?

**Comment by httpdigest** [comment] 2016-09-21 18:53
It happens with both 2.0.2 and the latest 2.1.0-dev.20160921.
I narrowed it down to the following case:
- add a folder app/ under /src/
- add a file with the exact file "app.component.ts"
- add your test class to it

The result for me is that once the file is called "app.component.ts" Visual Studio failes to compile it correctly. When I simply rename the file to "ap.component.ts" (notice the misspelling of "app") the compilation in the editor works again...

**Comment by httpdigest** [comment] 2016-09-21 18:55
When I rename the folder "app" to something else (such as "app2") and keep the file "app.component.ts" in it (with that exact name), everything also works correctly... :(
This looks like a really weird file path computation bug.

**Comment by chrmarti** [comment] 2016-09-21 19:22
Cannot reproduce. Have you tried pointing the settings at the workspace's typescript install:
```
"typescript.tsdk": "node_modules/typescript/lib"
```

**Comment by httpdigest** [comment] 2016-09-21 19:33
For me it is perfectly reproducible with creating a default angular-cli project:
- `npm install -g angular-cli@1.0.0-beta.15`
- `ng new test-project`
- open folder test-project in Visual Studio Code
- open the src/app/app.component.ts file
- make some changes that would produce a compile error

**Comment by httpdigest** [comment] 2016-09-21 19:59
I just tried that procedure on Ubuntu 16.04.1 with the latest Visual Studio Code Insiders download, and there the issue does not occur. Only on Windows 7 x64.

**Comment by chrmarti** [comment] 2016-09-21 20:55
Works for me with Windows 10. Could you open the Output panel and switch that to show the TypeScript output? Any hints there? That should at least tell you where it is running the tsserver from.

**Comment by httpdigest** [comment] 2016-09-21 21:02
Okay, that is a bit disappointing. The "Output" view shows:
```
[Info  - 22:59:41] Using tsserver from location: d:\projects\test-project\node_modules\typescript\lib\tsserver.js
```
after I execute the typescript compiler. But the thing is, that the hidden editor typescript auto-compilation also does not work. And once I manually execute the typescript compilation task it also does not recognize the error.

**Comment by chrmarti** [comment] 2016-09-21 21:19
Got it reproduced with the above steps you gave on Windows 8.1 (not sure if that makes a difference to Windows 10). It indeed only reproduces in src/app/app.component.ts with any compile error. It does not reproduce for me with the build task, that correctly reports the compile error.

Not sure if that has a chance of being on our side, @dbaeumer?

**Comment by httpdigest** [comment] 2016-09-21 21:27
Thanks for trying, I'm glad you could reproduce it. It's pretty strange. When I create a new empty folder and just add a src/app/app.component.ts, everything works fine. It seems to have to do with the "complexity" of the project (maybe number of node_modules).
But I have yet to figure out what exactly triggers the issue.
The first time I encoutered that issue was with an Angular 2 CLI-generated project.

**Comment by chrmarti** [comment] 2016-09-22 03:03
Figured we can take traces from the communication with the tsserver. This one shows me opening app.component.ts in a first editor and then app.module.ts in a second editor. Both have compile errors, but only those in app.module.ts are reported:
```
[Info  - 7:56:54 PM] Using tsserver from location: e:\vscode\helloangular2\node_modules\typescript\lib\tsserver.js
[Trace - 7:56:54 PM] Sending request: open (0). Response expected: no. Current queue length: 0
Arguments: {
    "file": "e:/vscode/helloangular2/src/app/app.component.ts",
    "fileContent": "import { Com ponent } from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  templateUrl: './app.component.html',\n  styleUrls: ['./app.component.css']\n})\nexport class AppComponent {\n  title = 'app works!';\n}\n"
}
[Trace - 7:56:54 PM] Sending request: geterr (1). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "e:/vscode/helloangular2/src/app/app.component.ts"
    ]
}
[Trace - 7:56:58 PM] Sending request: open (2). Response expected: no. Current queue length: 0
Arguments: {
    "file": "e:/vscode/helloangular2/src/app/app.module.ts",
    "fileContent": "import { Brows erModule } from '@angular/platform-browser';\nimport { NgModule } from '@angular/core';\nimport { FormsModule } from '@angular/forms';\nimport { HttpModule } from '@angular/http';\n\nimport { AppComponent } from './app.component';\n\n@NgModule({\n  declarations: [\n    AppComponent\n  ],\n  imports: [\n    BrowserModule,\n    FormsModule,\n    HttpModule\n  ],\n  providers: [],\n  bootstrap: [AppComponent]\n})\nexport class AppModule { }\n"
}
[Trace - 7:56:58 PM] Sending request: geterr (3). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "e:/vscode/helloangular2/src/app/app.module.ts",
        "e:/vscode/helloangular2/src/app/app.component.ts"
    ]
}
[Trace - 7:56:58 PM] Event received: syntaxDiag (0).
Data: {
    "file": "e:/vscode/helloangular2/src/app/app.module.ts",
    "diagnostics": [
        {
            "start": {
                "line": 1,
                "offset": 16
            },
            "end": {
                "line": 1,
                "offset": 24
            },
            "text": "',' expected."
        }
    ]
}
[Trace - 7:56:58 PM] Event received: semanticDiag (0).
Data: {
    "file": "e:/vscode/helloangular2/src/app/app.module.ts",
    "diagnostics": [
        {
            "start": {
                "line": 1,
                "offset": 10
            },
            "end": {
                "line": 1,
                "offset": 15
            },
            "text": "Module '\"E:/vscode/helloangular2/node_modules/@angular/platform-browser/index\"' has no exported member 'Brows'."
        },
        {
            "start": {
                "line": 1,
                "offset": 16
            },
            "end": {
                "line": 1,
                "offset": 24
            },
            "text": "Module '\"E:/vscode/helloangular2/node_modules/@angular/platform-browser/index\"' has no exported member 'erModule'."
        },
        {
            "start": {
                "line": 13,
                "offset": 5
            },
            "end": {
                "line": 13,
                "offset": 18
            },
            "text": "Cannot find name 'BrowserModule'."
        }
    ]
}
```

**Comment by dbaeumer** [comment] 2016-09-22 18:56
Moving to the TS team. There is little we can do if the tsserver doesn't report the problems.

**Comment by dbaeumer** [comment] 2016-09-22 18:57
This issue was moved to Microsoft/TypeScript#11066

**Comment by dbaeumer** [comment] 2016-09-22 18:58
@chrmarti thanks a lot for the investigation.

**Closed by dbaeumer** 2016-09-22 18:57 UTC
Labels: bug, typescript
