### ISSUE TITLE
Angular: unclear debug error message

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#24244] opened 2017-04-07 16:57 UTC
In the angular test tour:

After running `npm start` try to debug.
Go Debug and press the play button. 
You get an error message that does not make sense to the users. For example, it's unclear where the `serve` part comes from.

![azyhyt4v4r](https://cloud.githubusercontent.com/assets/4674940/24810803/7bcb7602-1b78-11e7-8136-e39b79da78bf.gif)

**Comment by weinand** [comment] 2017-04-07 22:49
duplicate of #24198

**Closed by weinand** 2017-04-07 22:49 UTC
