### ISSUE TITLE
"Look up & data detectors" feature not working on Mac OS with VS code

### ISSUE THREAD

**Issue by hust-whw** [microsoft/vscode#85632] opened 2019-11-26 21:46 UTC
After research some existing issues, I found the closest description of this issue is #31047, however there are some difference.
Instead of "behaving strangely", this feature now are not working at all.
Instead of macOS Sierra, this issue happened to me with MacOS Catalina.
I downloaded the insider version just now and still not working.

**Mac OS version**
macOS Catalina 10.15

**VS code version**
Version: 1.40.1
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Issue**
Look up feature still not working with both "Force click" and "3-fingers tab".
Tried to reinstaill, still not working.
![image](https://user-images.githubusercontent.com/8982712/69673960-80fe9580-1069-11ea-8ed7-9ee8ac933b9d.png)

Does this issue occur when all extensions are disabled?: Yes, even when it's brand new

**Comment by wizzard0** [comment] 2021-05-24 18:08
Still does not work w/1.56.2, Big Sur 11.3.1, vanilla vscode install.

**Comment by cheemunkong** [comment] 2021-09-27 06:50
Hope to have this fix too

**Comment by hileon** [comment] 2021-10-10 14:45
Hope this will be fixed too. It does not work in edit window, but works in preview window. 

VSCode info as following:
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:58.853Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by ushuz** [comment] 2022-07-31 01:04
Judging from https://github.com/microsoft/vscode/issues/31047#issuecomment-371747820, the "lookup popup" stopped showing up since version 1.21, so it may be a good starting point to look at the changes made between 1.20 and 1.21.

**Comment by pingren** [comment] 2022-07-31 14:23
I found out `user-select: none` is the root cause for this issue. I will make a PR for this.

**Closed** 2022-10-03 09:54 UTC
Labels: feature-request, macos, editor-input, workbench-os-integration
