### ISSUE TITLE
Implement tab indent guides

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#4278] opened 2016-03-15 21:03 UTC
Implement indent rulers similar to what's used in other editors ([see this screenshot](https://github.com/Microsoft/vscode/issues/3803#issuecomment-195682393)).

This should be a setting that is on by default but that can be disabled in settings.json.

Perhaps we can call it `"editor.indentGuides:" true`

Vertical tab rulers should show for each tab level in (also include position 0 within nested section of code, such as classes, functions, Html tag nesting etc...)

Addresses issue #3803.  Some users have trouble not knowing where the left edge of the code editor is.  This is partly because the code editor and the glyph margin is not visually separated. This is particularly a problem for users who use small tab sizes (such as 2 spaces).

**Comment by Tyriar** [comment] 2016-03-16 17:55
Duplicate of https://github.com/Microsoft/vscode/issues/2192

**Closed by Tyriar** 2016-03-16 17:55 UTC
Labels: editor
