### ISSUE TITLE
Jupyter notebook data viewer: dicts with keys, ability to navigate varaibles

### ISSUE THREAD

**Issue by eduardo-suela-DEq** [microsoft/vscode#209256] opened 2024-04-01 11:10 UTC
First of all. It is my first note in this forum.
If not the right place, I am sorry.

I am starting to use VS Code for Python development
Right now I executing a notebook and exploring the variables 
I am using the jupyter built in variable explorer.

I have two issues.
When you explore a dict, is there a way to get the keys beside the values?
Is it possible to explore substructures nested within the one opened, for example, a dict of dicts and enter each nested dict
For example something like spyder variable exlporer.

Maybe there is already an extension for that.
I tried data wrangler but it doesn't do what i want

Than you 

![image](https://github.com/microsoft/vscode/assets/144444009/d08a5ce5-bee8-4964-ba59-20b98430fa79)

**Comment by amunger** [comment] 2024-04-01 16:00
Try out the setting `"notebook.experimental.variablesView": true` - a tree view for the notebook variables should show up in the debug sideview. Let us know what you think!

dupe of https://github.com/microsoft/vscode-jupyter/issues/1148

**Closed by amunger** 2024-04-01 16:00 UTC
