### ISSUE TITLE
Terminal profile WSL 1 doesn't work (exit code 4294967295)

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#120464] opened 2021-04-03 12:20 UTC
Issue Type: <b>Bug</b>

The new terminal profiles (finally!) in 1.55 doesn't work with WSL 1.
Instead this error message will get displayed:
![grafik](https://user-images.githubusercontent.com/2277182/113478151-5277a280-9487-11eb-8092-fc58b8bd590f.png)

However launching `wslconfig` shows that there is indeed an installed and configured Ubuntu:
![grafik](https://user-images.githubusercontent.com/2277182/113478178-7b983300-9487-11eb-957b-d5a0346f9931.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.75GB free)|
|Process Argv|--crash-reporter-id 6ad73eb2-e24b-4305-a8ef-19341314fe6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
ifc-syntax|Ala|0.1.4
Bookmarks|ale|13.0.4
spellright|ban|3.0.56
change-color-format|bbu|1.0.0
gitignore|cod|0.6.0
aoe2-rms|del|0.3.3
rhinopython|des|0.1.11
dotfiles-syntax-highlighting|dot|0.1.0
vscode-gitignore-syntax|dun|0.1.2
EditorConfig|Edi|0.16.4
vscode-open-in-application|fab|1.0.6
auto-close-tag|for|0.5.10
gc-excelviewer|Gra|3.0.41
gdl|Gra|1.24.3
vscode-guid|hea|1.4.20
reg|ion|1.0.2
aoe2-aiscript|jvi|0.1.7
vscode-markdown-notes|kor|0.0.24
nim|kos|0.6.6
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
powershell|ms-|2021.2.2
sublime-keybindings|ms-|4.0.8
resourcemonitor|mut|1.0.7
printcode|nob|3.0.0
material-icon-theme|PKi|4.6.0
polacode|pnp|0.3.4
run-on-save|puc|1.4.0
gruvbox-material|sai|6.3.9
sonarlint-vscode|Son|1.21.0
language-stylus|sys|1.11.0
vscode-open-in-github|sys|1.15.0
markdown-links|tch|0.8.0
open-in-browser|tec|2.0.0
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.3.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Souzlipes** [comment] 2021-04-04 23:04
Are you demonstrating this error or are you trying to solve it?

**Comment by runxel** [comment] 2021-04-07 15:38
After fiddling with the command I've found that the correct invoking command has to be
```bash
wsl.exe -d Ubuntu
```
Note the absence of any quotes and also the `(Standard)` affix.

**Comment by meganrogge** [comment] 2021-04-08 03:32
Yep we're fixing this soon 
Duplicate of #120321

**Closed by meganrogge** 2021-04-08 03:32 UTC
