### ISSUE TITLE
'go to definition' no longer working

### ISSUE THREAD

**Issue by davidamey** [Microsoft/vscode#28324] opened 2017-06-09 09:48 UTC
This may be new configuration that I've missed, but cmd/ctrl+click no longer goes to definition. F12 also doesn't seem to work.

I've tested this in Dart and Java. A colleague has experienced the same thing on OSX but seems to work fine on Windows 10 (both when upgrading from 1.12 -> 1.13)

- VSCode Version: 1.13.0 (1.13.0)
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open project
2. Cmd/ctrl+click term or select term and press F12

**Comment by hemulin** [comment] 2017-06-09 11:14
Experiencing the same on Lubuntu 16.04

**Comment by davidamey** [comment] 2017-06-09 12:45
I've tried closing and opening vscode but still broken.

**Comment by curtisr7** [comment] 2017-06-09 13:25
I was having the same problem on OSX. To solve the problem I shutdown vscode and then removed `~/.vscode`. I'm not certain what all I lost when I removed that directory, but everything seems to be working now.

**Comment by Krizzu** [comment] 2017-06-09 18:15
Please note that when deleting `~/.vscode`, you're going to remove all installed extensions.

**Comment by curtisr7** [comment] 2017-06-09 18:25
> Please note that when deleting ~/.vscode, you're going to remove all installed extensions.

Ah yea, should have mentioned that.

**Comment by mjbvz** [comment] 2017-06-09 18:32
Yes deleting`~/.vscode` will remove all extensions, including the Java and dart ones that were providing `go to definition` in the first place.

@curtisr7 and @hemulin, what languages are you working in?

**Comment by curtisr7** [comment] 2017-06-09 18:36
> @curtisr7 and @hemulin, what languages are you working in?

go

I do recall seeing a message come up after a restart that mentioned something about a corrupt install?

**Comment by hemulin** [comment] 2017-06-09 18:40
@mjbvz, python at the time of this occurrence.

**Comment by mjbvz** [comment] 2017-06-09 19:44
I suspect this is related to the new `"editor.multiCursorModifier": "alt"` setting: https://code.visualstudio.com/updates/v1_13#_add-multiple-cursors-with-ctrl-cmd-click

Two things to try:

* If you run `go to definition` in the command palette, does that work?
* Can you please try setting `"editor.multiCursorModifier": "alt"` to see if cmd+click works for `go to definition` again?

**Comment by Krizzu** [comment] 2017-06-09 19:54
@mjbvz 
With `"editor.multiCursorModifier": "ctrlCmd"` I'm able to use `alt` key to use `go to definition` feature.
Although, with setting `"editor.multiCursorModifier": "alt"`,  I'm unable to `go to definition` nor add more cursor.

MacOSX

**Comment by hemulin** [comment] 2017-06-09 20:08
@mjbvz
**"editor.multiCursorModifier": "alt"** => 
1. Multi cursor doesn't work with alt key (known issue with ubuntu variants)
2. Pallete "go to" works
3. ctrl+click "go to" works
4. F12 "go to" works

**"editor.multiCursorModifier": "ctrlCmd"** => 
1. Multi cursor works with ctrl key
2. Pallete "go to" works
3. alt+click "go to" doesn't work. The term is being highlighted and underlined, intellisense window is opening with the right documentation, but the actual jumping to definition doesn't take place.
4. F12 "go to" works

Lubuntu 16.04

**Comment by mjbvz** [comment] 2017-06-09 20:19
@alexandrudima Can you please take a look? This issue does seem related to #27193

**Comment by alexandrudima** [comment] 2017-06-12 06:54
We didn't change anything out-of-the-box. 

But we have introduced a new setting, `editor.multiCursorModifier` which toggles between two states exactly as @hemulin notes:

### `editor.multiCursorModifier = alt` (Default)
* the <kbd>alt</kbd> modifier is used for adding/working with multiple cursors
* the <kbd>ctrl</kbd> (Windows & Linux) or <kbd>cmd</kbd> (Mac) are used for go to definition or opening links

### `editor.multiCursorModifier = ctrlCmd`
* the <kbd>ctrl</kbd> (Windows & Linux) or <kbd>cmd</kbd> (Mac) modifiers are used for adding/working with multiple cursors
* the <kbd>alt</kbd> modifier is used for go to definition or opening links

---

Now let's try to get to the bottom of this :)

---

@davidamey 
Can you please share your user settings? To rule out any issues with these extensions, can you please open a file and write a link in the file e.g. `https:///www.microsoft.com`. When hovering over the link, which modifier does the hover ask you to press to open the link? Does pressing the modifier and clicking work?

---

@hemulin 
Your problem stemmed I think from our multi-process architecture. When reloading a window, only the renderer process + extension host of that renderer process gets reload, while the main process survives. I think you've run into the case where the main process was running at version N and the renderer process was running at version N+1. That is something perhaps @bpasero or @joaomoreno would want to hear about such that we can quit or give a good error message instead of running in this inconsistent state. Perhaps you can file a new issue with precise steps.

---

@curtisr7 
I am not sure what effect deleting the extensions would have on the <kbd>alt</kbd> modifier would have, but if the issue is fixed for you and you're happily productive, then that's good 👍 

---

@Krizzu 
If I understand you correctly, you are reporting that `"editor.multiCursorModifier": "alt"` (which is the default) causes that go to definition / open link and add multiple cursors **all stop working**. I cannot reproduce this on my machine.

---

That being said, we **did change** a setting that impacts mouse operations. https://code.visualstudio.com/updates/v1_13#_changed-setting-defaults

![screen shot 2017-06-12 at 08 53 03](https://user-images.githubusercontent.com/5047891/27022088-9acdd862-4f4c-11e7-8577-1f95f32e4c5a.png)

This means that clicking on **an existing selection** will begin to drag it. Perhaps this setting interferes here ?

**Comment by davidamey** [comment] 2017-06-13 07:34
OK, so hovering over a link has the tooltip 'cmd + click to follow link' and doing this works.

I think it might be to do with the language extension(s) as I have no auto-complete for Dart either. I've just tried Go and that auto-completes and 'goes to definition'.

Going to uninstall and re-install the Dart and Java extensions.

**Comment by alexandrudima** [comment] 2017-06-13 08:03
@davidamey Thank you for following up on this. I'm not sure what might have went wrong with these extensions. If you find any reproducible steps, it is best to contact the extension authors directly in their issue trackers.

---

I think the only left thread in this issue in this case is with @Krizzu. @Krizzu do you have any additional steps that we can try to reproduce? Perhaps you can share your full settings where go to definition / open link and create cursor all stop working ?

**Comment by Krizzu** [comment] 2017-06-13 08:16
@alexandrudima 
Deleting `~/.vscode` fixed my problem. 

With `"editor.multiCursorModifier": "alt"` I can add more cursors holding `alt` key and use `go to definition` holding `CMD` key. 

Setting `multiCursorModifier` to `ctrlCmd` swaps functionality (`alt` for `go to definition`, `CMD` for adding cursors).

**Comment by alexandrudima** [comment] 2017-06-13 08:21
@Krizzu thanks for getting back to me. I am not sure what could have caused this. If you encounter this again and have some reproducible steps I'd love to investigate further.

---

I'll close this issue for now and please reopen if there are any additional findings.

**Closed by alexandrudima** 2017-06-13 08:21 UTC
Labels: needs more info, new release

**Comment by TheDeveloper** [comment] 2017-06-13 13:47
I'm seeing this too. cmd + click no longer works for going to definition. It has changed to alt + click. As far as I can see there is no setting for this. Aside from this, I have got `editor.multiCursorModifier` set to `ctrlCmd` for multiple selections with command key.

**Comment by alexandrudima** [comment] 2017-06-14 07:41
@TheDeveloper 

How would it be possible for `cmd+click` to both add a cursor and go to definition at the same time? When `editor.multiCursorModifier` is set to `ctrlCmd`, the go to definition modifier changes such that the two features do not collide.

<img width="500" alt="screen shot 2017-06-14 at 09 40 28" src="https://user-images.githubusercontent.com/5047891/27120896-8532d1d4-50e5-11e7-847f-ef41444b6cee.png">

**Comment by TheDeveloper** [comment] 2017-06-14 17:06
@alexandrudima you got me there!

The behaviour definitely makes sense, I just stopped being able to do what was built into muscle memory so I thought something was wrong. I should have thought about that when I changed the setting.
