### ISSUE TITLE
Function calls in ternary operators in preprocessor macro will make syntax highlighting malfunction (C/C++)

### ISSUE THREAD

**Issue by ngkaho1234** [Microsoft/vscode#16500] opened 2016-12-05 12:44 UTC
- VSCode Version: 1.7.2 (Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f)
- OS Version: ArchLinux

Steps to Reproduce:
1. Use function calls in ternary operators in preprocessor macro.

https://cloud.githubusercontent.com/assets/11871016/20885563/7a6e7856-bb2c-11e6-83e8-2a1e903b5677.png
https://cloud.githubusercontent.com/assets/11871016/20885562/7a68c654-bb2c-11e6-9110-102a88521187.png
https://cloud.githubusercontent.com/assets/11871016/20885565/7a6f4330-bb2c-11e6-9614-020754e4d03f.png
https://cloud.githubusercontent.com/assets/11871016/20885564/7a6f0a46-bb2c-11e6-86f3-c174ab033a24.png

**EDIT**:
1. Only when starting a newline within preprocessor macro will the bug be triggered
https://cloud.githubusercontent.com/assets/11871016/20885644/fd87447a-bb2c-11e6-8bd8-ef7eb4eec05c.png
2. Disable preview of screenshots

**Comment by aeschli** [comment] 2016-12-06 13:31
@ngkaho1234 Can you also paste the code snippets?

**Comment by ngkaho1234** [comment] 2016-12-07 05:40
@aeschli 
The one that gives correct syntax highlighting result: https://gist.github.com/ngkaho1234/b72c22accf2903b6b4157b1e02c11bca

This one gives incorrect syntax highlighting result:
https://gist.github.com/ngkaho1234/0defe261d983cfa10d9435050e5e7e36

**Comment by aeschli** [comment] 2016-12-07 08:26
Thanks a lot @ngkaho1234 . This looks like a duplicate of https://github.com/atom/language-c/issues/160

**Closed by aeschli** 2016-12-07 08:26 UTC
