### ISSUE TITLE
Auto import not working in JSX

### ISSUE THREAD

**Issue by sgcuber24** [microsoft/vscode#126781] opened 2021-06-20 13:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Try to type in any JSX element, whether pre-installed or custom made components.

![image](https://user-images.githubusercontent.com/35477291/122675230-20f4b480-d1f6-11eb-80e1-a486439031b2.png)
Auto import does not work for any of the JSX elements.

However, auto import works for functions such as useState. The issue is only with JSX elements.

**Comment by Bessonov** [comment] 2021-06-20 15:49
I'm not sure that I experience the same problem. After update from 1.56.2-1620838498 to 1.57.1-1623937013 vsc doesn't recognize ts/tsx exports from libraries. But I don't see any problem with own modules. Downgrade to 1.57.0-1623259737 doesn't help. Therefore I assume that this problem was introduced between 1.56.2 and 1.57.0.

**Comment by sgcuber24** [comment] 2021-06-20 16:00
I didn't have this problem in the previous version, 1.56.2. Auto imports from libraries such as Material UI and also custom components worked perfectly. 
Now neither of them works.

**Comment by iBhavesh** [comment] 2021-06-20 18:45
I am having the same issue tried both tsx and jsx auto import is not working for either  of them neither for custom component nor for other components from other module.s

**Comment by yuanworks** [comment] 2021-06-21 05:38
Also reproducible in MacOS Big Sur (11.0.1).

The only place autoi-mport is working for me is in the `includes` section:

<img width="679" alt="Screen Shot 2021-06-21 at 1 33 32 PM" src="https://user-images.githubusercontent.com/3508123/122711975-bbf09b80-d295-11eb-8a71-a1b6806c6bbd.png">

After pressing `tab`, the auto import works. However, it doesn't show the usual _auto import from ..._ popup.

**Comment by Torvaldi** [comment] 2021-06-21 07:36
Reproducible in Linux Ubuntu 20.04.2.

When I'm trying to auto-import something, I got this error on developer console : 
![image](https://user-images.githubusercontent.com/7703951/122724362-242e8580-d274-11eb-94f3-0ef2a474562c.png)

**Comment by igorconde** [comment] 2021-06-21 15:26
I'm having same issue, when dowgrade for version 1.56 work normally;

**Comment by agcty** [comment] 2021-06-21 15:47
I have the same issue, auto import just doesn't work anymore. I just spent 2 days trying to fix my eslint config but I am 100% sure that it has to be vscode now.

**Comment by weihuasubu** [comment] 2021-06-22 16:18
Confirmed on Big Sur 11.4. Not sure if my issue is similar to others, but for me, the auto import is working but not properly - I can only get some of my modules auto imported while the others would not even show up in the auto import popup.

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (5 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by pedrocarlos-ti** [comment] 2021-06-26 20:33
Same issue, downgrade to version 1.56 ( https://code.visualstudio.com/updates/v1_56 ) and works fine!

**Comment by mjbvz** [comment] 2021-06-29 21:57
Duplicate of https://github.com/microsoft/TypeScript/issues/44657

**Closed by mjbvz** 2021-06-29 21:57 UTC
