### ISSUE TITLE
Outline Window

### ISSUE THREAD

**Issue by filthyslider** [Microsoft/vscode#54748] opened 2018-07-20 16:33 UTC
I love the new Outline functionality in the Explorer Window, but I'd like to be able to separate it from the Explorer window and create another fixed window on the side where it's displayed.  So I could see both the Explorer window and the Outline View and they'd take up the entire vertical space.

**Comment by filthyslider** [comment] 2018-07-20 16:39
Duplicate of #49923

**Comment by alexandrudima** [comment] 2018-07-23 07:33
Duplicate of #49923

**Closed by alexandrudima** 2018-07-23 07:33 UTC
