### ISSUE TITLE
Wrong color of console.log token

### ISSUE THREAD

**Issue by igolskyi** [microsoft/vscode#91818] opened 2020-02-29 15:57 UTC
- VSCode Version: **1.43.0-insider**
Commit: 17c6d123d212f90300429ecad3fc96fcec6e338f
Date: 2020-02-28T12:48:39.706Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
- OS: Linux x64 5.3.0-40-generic
![consolelog](https://user-images.githubusercontent.com/22115961/75610747-a5f91d80-5b1c-11ea-941c-050bea3ea4e3.png)

Steps to Reproduce:

1. Fresh install of vscode-insider and run it
2. Open javascript file and write `console.log('smth')`
3. Use Dark+ (default dark) theme
3. The color will be correct ('#4EC9B0') for a short time, but it will not be correct ('#9CDCFE') in the next moment.

**P.S. this behavior also is in the stable version**:
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-02-29 22:07
/duplicate of #90379

As a workaround you could disable semantic highlighting.

**Closed by gjsjohnmurray** 2020-02-29 22:07 UTC
Labels: *duplicate

**Comment by igolskyi** [comment] 2020-03-03 16:04
Has disabled this option yet
```json  
"editor.semanticHighlighting.enabled": false
```
