### ISSUE TITLE
SCM validation message popover is not dismissed when switching views

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#211109] opened 2024-04-23 15:44 UTC
1. Go to vscode.dev, ensure SCM input validation messages aren't disabled
2. Place your cursor in the SCM input box 
3. Popover should show up 
4. Switch to another view e.g. GHPRI 
5. :bug: popover isn't dismissed 🧀 

![Image](https://github.com/microsoft/vscode/assets/30305945/6e81d702-74d4-4295-80eb-16f005578a32)

**Comment by lszomoru** [comment] 2024-04-23 19:31
Duplicate of https://github.com/microsoft/vscode/issues/211096.

**Closed by lszomoru** 2024-04-23 19:31 UTC
