### ISSUE TITLE
Notebook list screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93757] opened 2020-03-30 14:15 UTC
NOt sure how I got there but I have list screen cheese, this is printed onto the console

```
ERR ListError [NotebookCellList] Invalid index 4: Error: ListError [NotebookCellList] Invalid index 4
    at NotebookCellList.setFocus (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:1037:31)
    at MouseController.onPointer (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:472:23)
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:460:45)
    at file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:457:42)
    at HTMLDivElement.fn (file:///Users/jrieken/Code/vscode/out/vs/base/browser/event.js:10:35)

```
[Mar-30-2020 16-14-29.gif.zip](https://github.com/microsoft/vscode/files/4403360/Mar-30-2020.16-14-29.gif.zip)

<img width="1234" alt="Screenshot 2020-03-30 at 16 13 11" src="https://user-images.githubusercontent.com/1794099/77922474-62234080-72a1-11ea-876c-52492d56f479.png">

**Comment by rebornix** [comment] 2020-03-31 23:23
Pushed a few layout polish to master and now I can't reproduce this issue anymore. @jrieken let me know if you still see it.

**Comment by jrieken** [comment] 2020-04-01 09:46
[test.github-issues.zip](https://github.com/microsoft/vscode/files/4414238/test.github-issues.zip)

The attached notebook reproduces this pretty well. Whenever I open it it renders like this and only recovers when I type newlines in the editor

<img width="718" alt="Screenshot 2020-04-01 at 11 44 12" src="https://user-images.githubusercontent.com/1794099/78123316-44bfb500-740e-11ea-9422-232e99cd971d.png">

**Comment by rebornix** [comment] 2020-04-01 21:27
Fixed via https://github.com/microsoft/vscode/commit/28cfb4b1d61e6e223d8472c9ae4c20b870cf6182 . @jrieken did you run into this issue when switching between different notebooks?

**Closed by rebornix** 2020-04-01 21:27 UTC
Labels: bug, needs more info, notebook

**Comment by jrieken** [comment] 2020-04-02 06:59
No - I also saw this after reloads
