### ISSUE TITLE
Show (deleted) indicator in custom editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114545] opened 2021-01-18 20:01 UTC
Regular text files will show (deleted) in the tab when you delete a file:

![image](https://user-images.githubusercontent.com/2193314/104958383-c7593700-5984-11eb-8a5c-03e0dde9b94d.png)

This doesn't happen in custom editors:

![image](https://user-images.githubusercontent.com/2193314/104958408-d2ac6280-5984-11eb-99c3-248c104d8ffd.png)

Repro:

1. Open a custom editor file
2. `rm <file>` in terminal

**Comment by mjbvz** [comment] 2021-01-19 19:27
Duplicate of #99270

**Closed** 2021-01-19 19:27 UTC
Labels: *duplicate, custom-editors, polish
