### ISSUE TITLE
Gutter indicators not working after updating to 1.90.0-insiders

### ISSUE THREAD

**Issue by rary21** [microsoft/vscode#212857] opened 2024-05-16 03:37 UTC
Does this issue occur when all extensions are disabled?: Yes (but with WSL to open a repo in WSL)

- VS Code Version: Version: 1.90.0-insider (user setup)
Commit: 5e68ffd760038bb156894a87f896910be510accd
Date: 2024-05-15T08:29:12.858Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
- OS Version:  Windows 11 Enterprise
Version 22H2
OS Build	22621.3447
Windows Feature Experience Pack 1000.22688.1000.0

Steps to Reproduce:

1. Create a git repo with `git init`
2. Open the repo, add and modify files.
3. Open modified file in VSCode

I also tested with newly installed VSCode and it worked fine.

### 1.90.0-insider
![image](https://github.com/microsoft/vscode/assets/12541279/b603c39e-c5d6-422c-9165-fbd849c29f1e)

### 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621
![image](https://github.com/microsoft/vscode/assets/12541279/df0c7127-37e0-4d66-9706-079f780fba0f)

**Comment by ngollan** [comment] 2024-05-16 07:25
+1. For me, it so far only happens in a remote environment (a Ruby project in a devcontainer, Linux guest on a Windows host, using git for SCM). A local environment with a small C# project also using git is not affected.

**Comment by bmasias1** [comment] 2024-05-16 15:12
I have the same issue with version 1.90.0-insider. The gutters are not showing when working in a remote environment (WSL). I tested with both new and old repositories, and the problem persists.

**Comment by tcatherall** [comment] 2024-05-17 14:58
This is affecting my team when using Remote SSH connected to a remote container

**Comment by ssalbdivad** [comment] 2024-05-22 14:56
Yeah this has been the first regression that feels bad enough I've just been developing natively on Windows waiting for this to get fixed 😆

**Comment by deepeshmittal** [comment] 2024-05-22 20:29
I am also facing the same issue on `1.90.0-insider` version while working on remote container.

**Comment by BlankShrimp** [comment] 2024-05-27 02:25
It's been 2 weeks since I firstly encountered this issue. There is an average of 1 update every two days, yet none of them fixed it.

**Comment by ssalbdivad** [comment] 2024-05-28 12:50
@lszomoru Would it be possible to get an idea of the team's stance on this?

I very much appreciate how responsive the VSCode team usually is when addressing regressions. This feels like a very significant one to not have any feedback for two weeks.

**Comment by alexr00** [comment] 2024-05-28 13:27
`this` is defined. The issue is a timing problem, and I don't know why it has only surfaced now:

https://github.com/microsoft/vscode/blob/c6e45e96a6b0fe94e0dae5b13ab4167d69ec9788/extensions/git/src/repository.ts#L868-L871

1. On line 869, the source control is created. This looks sync, but actually async stuff happens. Specifically, in the renderer the repository is added to a map on line 480 here:

https://github.com/microsoft/vscode/blob/c6e45e96a6b0fe94e0dae5b13ab4167d69ec9788/src/vs/workbench/api/browser/mainThreadSCM.ts#L474-L480

2. Because this is async we don't have a guarantee that by the time you set the `quickDiffProvider` from the first snippet on line 871 the repository will have been added to that map, so instead of adding the quick diff provider we just return early here:

https://github.com/microsoft/vscode/blob/c6e45e96a6b0fe94e0dae5b13ab4167d69ec9788/src/vs/workbench/api/browser/mainThreadSCM.ts#L499-L504

@lszomoru while looking at this, I noticed that the `await` here was only recently added. That might be the culprit.

https://github.com/microsoft/vscode/blob/c6e45e96a6b0fe94e0dae5b13ab4167d69ec9788/src/vs/workbench/api/browser/mainThreadSCM.ts#L476-L477

**Comment by lszomoru** [comment] 2024-05-28 13:47
Thank you @alexr00. We have made a change to eagerly create the text model for the commit input in order to address a different paper-cut where in some cases the commit input would not get correctly focused. This clearly broke several things (quick diff being only one of them). I have a local repro and will be pushing a fix for this today/tomorrow.

**Closed** 2024-05-29 10:41 UTC
Labels: bug, scm

**Comment by IOLOII** [comment] 2024-06-11 03:19
If someone is like me, it is accidentally caused for couldn' t see the blue line I mean dirty diff line

It may also not be displayed due to other settings `dirty diff line`  #147352 

<img width="1389" alt="image" src="https://github.com/microsoft/vscode/assets/34856171/23a3e6e2-aeb5-4132-9664-6c6616715527">

When developing locally, if this is the case, you can check the settings.

<img width="1323" alt="image" src="https://github.com/microsoft/vscode/assets/34856171/864e7036-05b8-46b3-8cb9-a27ed44be94c">

Just annotate it.

**Comment by joynal-miah** [comment] 2024-06-20 15:45
This has stopped working again in the latest nightly, but only for .vue files.
We have tested gutters still work correctly for .php .js .ts .twig .json
