### ISSUE TITLE
Developer Tools pane overlapping main vscode UI

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#158518] opened 2022-08-18 17:50 UTC
Type: <b>Bug</b>

Repro:
- open vs code insiders
- show developer tools pane
- the three buttons `--/[]/X` in the upper right blend into the devtools UI blocking some of the elements in the upper right of devtools

Screenshot:
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/12552271/185461662-d66fabad-7973-40d7-80fc-1bb3977ea8ac.png">

VS Code version: Code - Insiders 1.71.0-insider (f5c96e2db885f43fe1adb4a6ebbdfecf095430a8, 2022-08-18T05:15:52.904Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.08GB free)|
|Process Argv|--crash-reporter-id 62122f1b-5534-43ca-aa21-fca29c482163|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.13.12301015
vscode-pylance|ms-|2022.8.31
jupyter|ms-|2022.8.1002321033
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52cf:30549188

```

</details>

**Comment by yume-chan** [comment] 2022-08-19 04:10
Duplicate of https://github.com/electron/electron/issues/34129

**Comment by deepak1556** [comment] 2022-08-19 07:29
Merging to https://github.com/microsoft/vscode/issues/150521

**Closed by deepak1556** 2022-08-19 07:29 UTC
