### ISSUE TITLE
Extra scrollbar in SCM Graph prevents smoothly moving the mouse to tooltip

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#232161] opened 2024-10-24 16:33 UTC
Latest Insiders.

Steps to Reproduce:

1. Hover over a branch pill in SCM Graph, try to move to the tooltip
2. 🐛 Easily fails and tooltip closes as I try to hover it

![Image](https://github.com/user-attachments/assets/ffd60664-79ba-4799-a5bb-6e303c8298e6)

Probably because of the tiny scrollbar that is added in the element

**Comment by lszomoru** [comment] 2024-10-24 17:36
Duplicate of https://github.com/microsoft/vscode/issues/228121

**Closed by lszomoru** 2024-10-24 17:36 UTC
