### ISSUE TITLE
Completion details should have syntax highlighting

### ISSUE THREAD

**Issue by jmagaram** [microsoft/vscode#50813] opened 2018-05-30 16:26 UTC
This is a big annoyance I've just come to accept in Visual Studio and VS Code and I suspect many other developers have too. The pop-up windows that explain function arguments and various other situations are very difficult to parse because they just wrap text wherever and no keywords are highlighted. In other words, the pop-up windows show code in a way that we would never accept in our source files. Here is an example showing what is [expected for javascript array reduce](https://1drv.ms/u/s!AjaZ-t3uLVN_zrsG0S24tGUA-UUIUA). From this pop-up it is extremely difficult to tell how many arguments the function takes and of what kind. I'd really like to see each argument on its own line. If an argument is a function, then show each of the arguments to that function indented on its own line. Maybe have some highlighting too. I'm not sure what the right solution is, but I do know the current behavior makes it really tough to figure out what is going on.

**Comment by octref** [comment] 2018-05-30 22:32
Here is the image

![vscodetooltip](https://user-images.githubusercontent.com/4033249/40751031-4ed77246-641e-11e8-8b94-82de43743f23.jpg)

I also found this a very lacking experience.

**Comment by octref** [comment] 2019-10-17 17:10
The issue is `detail` is just a string, meant for less-prominent info. We might allow `string | MarkupContent` in the future for `detail` to have code blocks.

**Comment by KamasamaK** [comment] 2019-10-17 18:38
Also see #34188

**Comment by octref** [comment] 2019-10-17 18:56
Closing as duplicate of #34188.

**Closed by octref** 2019-10-17 18:56 UTC
Labels: editor-parameter-hints, feature-request, ux
