### ISSUE TITLE
Removes trailing comma and adds to undo history

### ISSUE THREAD

**Issue by SalmanAlSaigal** [microsoft/vscode#137044] opened 2021-11-12 12:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: macOS 12.0.1 (21A559)

When I have a multiline import statement in Typescript that contains a trailing comma, saving the file causes VSCode to remove the trailing comma as well as add this to the undo history (when pressing Ctrl+z, it adds the comma back again, when pressing Ctrl+z a second time it undoes my actual edit).

Moreover, it does not seem to be a formatting step, since it doesn't happen when choosing "Format Document" from the command palette.

Steps to Reproduce:
1. Have a Typescript file with the following code
```ts
import {
  LongImportNumber1,
  LongImportNumber2,
  LongImportNumber3,
  LongImportNumber4,
} from "something";

console.log(LongImportNumber1, LongImportNumber2, LongImportNumber3, LongImportNumber4)
```
2. Make an edit and save
3. Press Ctrl+z (it removes the comma)
4. Press Ctrl+z (it undoes your edit)

![CleanShot 2021-11-12 at 15 55 37](https://user-images.githubusercontent.com/4637614/141470659-12e24533-944e-41a3-8c39-c8f2446ad97f.gif)

**Comment by mjbvz** [comment] 2021-11-12 15:37
Are you sure you’ve disabled all extensions and then restarted VS Code? This seems like something caused by one of the formatting extensions, such as prettier

**Comment by SalmanAlSaigal** [comment] 2021-11-12 17:03
This was my first thought as well, but if it was a prettier issue, it would do it when choosing the `Command Pallette > Format Document`, which doesn't happen.

And yes, I made sure I'm reloading with extensions disabled. Here is a GIF showing the problem persisting.

![CleanShot 2021-11-12 at 20 00 33](https://user-images.githubusercontent.com/4637614/141505665-68e0aaa9-910c-40cb-aa02-7e2069f222cb.gif)

**Comment by SalmanAlSaigal** [comment] 2021-12-11 12:43
This was driving me insane, so I have been doing some digging.
I found out the cause of this issue is the `source.organizeImports` action on save.
It's rewriting all the import section of the file and counting it as an undo step.

**Comment by mjbvz** [comment] 2022-03-23 22:30
Yes this seemed caused by setting:

```json
	"editor.codeActionsOnSave": {
		"source.organizeImports":true
	}
```

I just tested this though and confirmed the undo/redo behavior matches how other on save actions work (such as `files.trimTrailingWhitespace`). These also create an extra undo stop since they are also touching the file

Having a dedicated undo stop seems desirable too as it lets you clearly see what organize imports was doing (and revert this change if it was unexpected)

I'm closing this since I don't think it's a bug

**Closed by mjbvz** 2022-03-23 22:30 UTC
