### ISSUE TITLE
"Save workspace as" doesn't automatically add extension.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#83244] opened 2019-10-24 17:39 UTC
- VSCode Version:
```
1.40.0-insider
b53811e67e65c6a564a80e1c412ca2b13de02907
x64
```
- OS Version: `Linux 5.3.7-arch1-1-ARCH GNU/Linux`

Steps to Reproduce:

1. Create an empty folder.
2. Launch VSCode
3. File -> "Add Folder to Workspace" -> Select and open newly created folder.
4. File -> "Save Workspace As" -> Name the file something like, `foobar`
5. The file is saved as what you named it -- the extension `.code-workspace` is not automatically appended -- as in, `foobar` is saved as a file called `foobar` and not `foobar.code-workspace`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by afranko** [comment] 2019-11-19 13:04
In my case VSCode doesn't append extension automatically, and also does not fetch the content of the "workspace file" with or without extension (`.code-workspace`).

I usually set a ruler `"editor.rulers": [80]` in workspace file, but it doesn't appear now.

**Comment by alexr00** [comment] 2019-11-19 14:48
Duplicate of https://github.com/microsoft/vscode/issues/84818

**Closed** 2019-11-19 14:48 UTC
Labels: *duplicate
