### ISSUE TITLE
[typescript] rename fails with 'no result'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25571] opened 2017-04-27 19:54 UTC
- In the vscode reop, open src/vs/editor/browser/widget/diffEditorWidget.ts
- try to rename `diffInserted`. Dialog shows up: No result.

It seems that also no reference can be found

**Comment by mjbvz** [comment] 2017-04-28 21:19
The root cause of this is https://github.com/Microsoft/TypeScript/issues/15452

Closing as upstream

**Closed by mjbvz** 2017-04-28 21:19 UTC
Labels: bug, javascript, typescript, upstream
