### ISSUE TITLE
Cannot close terminal

### ISSUE THREAD

**Issue by idheepan** [microsoft/vscode#116134] opened 2021-02-08 17:17 UTC
Issue Type: <b>Bug</b>

Expected: When I click the trash can icon above terminal the terminal should close. 

Actual Result: Nothing happens when I click the icon

VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:13:57.826Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.49GB free)|
|Process Argv|--crash-reporter-id 3013ecef-bf69-4795-9992-51a65f62130e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-CommPrev|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|12.31GB (8.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-CommPrev|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|12.31GB (8.95GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.53.2
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.23.0
cmake-integration-vscode|go2|0.7.1
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
rust|rus|0.7.8
tabnine-vscode|Tab|3.2.6
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by lighht** [comment] 2021-02-08 17:24
![vscode_term_bug](https://user-images.githubusercontent.com/10219892/107257214-70d19c80-6a08-11eb-91b3-2790ba09a67c.gif)

The close button closes all terminal windows. In the older versions, I could keep one or two windows and close just one. 

Current workaround: I type exit manually to close them.

**Comment by meganrogge** [comment] 2021-02-08 19:54
Duplicate of #116095

**Closed** 2021-02-08 19:54 UTC
Labels: *duplicate
