### ISSUE TITLE
vscode.extensions.all misses disabled extensions

### ISSUE THREAD

**Issue by alexeychikk** [microsoft/vscode#98024] opened 2020-05-17 09:55 UTC
Issue Type: <b>Bug</b>

I've disabled all extentions for a workspace and then when I call `vscode.extensions.all()` the result contains only built-in extensions. Disabled extensions are missing in the list.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.58GB (8.26GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
color-info|bie|0.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
gc-excelviewer|Gra|2.1.34
intellij-idea-keybindings|k--|0.2.39
git-graph|mhu|1.22.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-jest|Ort|3.2.0
open-html-in-browser|pea|2.1.3
material-icon-theme|PKi|4.1.0
vscode-graphql|Pri|0.2.14
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.8.0
highlight-matching-tag|vin|0.9.9
change-case|wma|1.0.0
unsaved-files-vscode|wra|2.1.1
markdown-all-in-one|yzh|2.8.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-05-18 08:32
Possible duplicate of #14444

**Comment by sandy081** [comment] 2020-05-18 08:36
/duplicate

Yes.

**Closed** 2020-05-18 08:37 UTC
Labels: *duplicate, new release
