### ISSUE TITLE
Some plugins don't work on VSC 64-bit

### ISSUE THREAD

**Issue by pc-lover** [Microsoft/vscode#32733] opened 2017-08-17 17:28 UTC
- VSCode Version: 1.15.1 64-bit
- OS Version: Windows 10

Steps to Reproduce:

1. Install `Git History` or `Git Blame` extension.
2. The installed extensions could not be found on the commands list (Ctrl + Shift + P)

The extensions work well on VSC 32-bit version. I'm not sure if the problem belongs to VSC 64-bit version or the extensions, though.

Reproduces without extensions: No

**Comment by joaomoreno** [comment] 2017-08-18 09:28
Do you happen to have the [fsharp](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) extension installed? What other extensions do you have installed in these machines?

**Comment by pc-lover** [comment] 2017-08-18 10:04
@joaomoreno I have Ionide-fsharp and 33 other extensions installed.

- Align
- AutoFileName
- Babel ES6/ES7
- Babelrc
- Beautify
- Bookmarks
- C#
- Complete JSDoc Tags
- Debugger for Chrome
- Docker
- ESLint
- Git Blame
- Git History
- Git Lens
- Git Project Manager
- gitignore
- Ionide-FAKE
- Ionide-fsharp
- Ionide-Paket
- MagicPython
- Multiple clipboards for VSCode
- Nord
- npm
- npm Intellisense
- Paste and Indent
- Project Manager
- Python
- Python for VSCode
- REST Client
- Sort lines
- Studio Icons
- swagger-doc-viewer
- TSLint

**Comment by joaomoreno** [comment] 2017-08-18 10:20
Please update Ionide-fsharp to the latest version and the issue will fix itself up.

Duplicate of #32673

**Closed by joaomoreno** 2017-08-18 10:20 UTC
Labels: extensions, needs more info, new release
