### ISSUE TITLE
Dockable panels

### ISSUE THREAD

**Issue by lemalcs** [microsoft/vscode#88868] opened 2020-01-17 17:35 UTC
Issue Type: <b>Feature Request</b>

It would be great if activity bar would open dockable panels, moving in order to hidding them is not so confortable. The same applies for consoles.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment] 2020-01-18 04:42
/duplicate of #10121

See also the first bullet of the Workbench section in the 2020 roadmap at https://github.com/microsoft/vscode/wiki/Roadmap

**Closed** 2020-01-18 04:42 UTC
Labels: *duplicate
