### ISSUE TITLE
Multimedia buttons trigger highlights/filter in Explorer tree

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#78330] opened 2019-08-01 13:07 UTC
Issue Type: <b>Bug</b>

If you have keyboard with multimedia buttons using them in Explorer tree triggers highlights/filtering.

1. Bring focus to Explorer tree
2. Press Play/Pause media key
3. Notice that filter for `MediaPlayPause` was applied

![image](https://user-images.githubusercontent.com/1312662/62295416-abeb2b00-b475-11e9-8f90-5e8c2f877823.png)

This keyboard have only one multimedia key, but I expect that other might be affected too.

VS Code version: Code - Insiders 1.37.0-insider (92da68a71cfb60bd3b9b0d7fbfb2a7e1fff9dbaf, 2019-08-01T05:37:54.848Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by frobinsonj** [comment] 2019-10-22 15:48
I would like to have a go at this.

**Comment by frobinsonj** [comment] 2019-10-22 16:50
@IllusionMH Can you still reproduce this? Think it may have been fixed in commit aa75677a69cfdc29e18b2edbd44ca548ea82ed9a. I know I used to be able to reproduce this but I can't anymore.

**Comment by IllusionMH** [comment] 2019-10-22 17:01
@frobinsonj thanks for checking this issue.
Unfortunately I'm still able to reproduce this issue wits latest Insiders build.

![image](https://user-images.githubusercontent.com/1312662/67310561-ad714000-f506-11e9-8556-4988fe6297bf.png)

Version: 1.40.0-insider (user setup)
Commit: c58aaab8a1cc22a7139b761166a0d4f37d41e998
Date: 2019-10-22T05:27:32.053Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Reported key is (which looks like expected key code for this button)
![image](https://user-images.githubusercontent.com/1312662/67310474-7bf87480-f506-11e9-94f3-30a3b742f910.png)

**Comment by frobinsonj** [comment] 2019-10-22 18:52
Issue #80741 related.

@joaomoreno I am thinking that this key filtering (see below) could be simplified massively. Instead of blacklisting all of these edge cases, we could just check if `e.browserEvent.key` is a single character. I believe this should only allow key presses that we want. Then we can just add the exceptions such as `CTRL + Backspace`.

If we remove L660 and modify L664 to be:
```ts
.filter(e => (e.browserEvent.key.length === 1 && !e.altKey && !e.ctrlKey && !e.metaKey) || ((this.pattern.length > 0 || this.triggered) && ((e.keyCode === KeyCode.Escape || e.keyCode === KeyCode.Backspace) && !e.altKey && !e.ctrlKey && !e.metaKey) || (e.keyCode === KeyCode.Backspace && (isMacintosh ? (e.altKey && !e.metaKey) : e.ctrlKey) && !e.shiftKey)))
```

Key filtering:
https://github.com/microsoft/vscode/blob/5f045ec9e8ae012f7879cdf8c2e77fc4cad6b5d7/src/vs/base/browser/ui/tree/abstractTree.ts#L658-L666

**Comment by joaomoreno** [comment] 2019-10-24 09:19
> is a single character

I thought about this. But you're going to hit issues with unicode characters, in which one visible character actually has length > 1.

Let's just keep filtering out these cases one by one, it's fine.

**Closed** 2019-10-24 12:22 UTC
Labels: bug, help wanted, tree

**Comment by chrmarti** [comment] 2019-10-31 11:52
Cannot reproduce in 1.39. Could someone who can verify the fix in the latest Insiders?

**Comment by IllusionMH** [comment] 2019-10-31 12:03
Fix works as expected for me.

Version: 1.40.0-insider (user setup)
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T05:42:33.138Z
