### ISSUE TITLE
Content is invisible on getting start VS Code

### ISSUE THREAD

**Issue by mieszczans** [Microsoft/vscode#40308] opened 2017-12-15 16:21 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.0.0
mithril-emmet|Fal|0.6.1
php-intellisense|fel|2.1.0
beautify|Hoo|1.1.1
rest-client|hum|0.16.1
check-npm-updates|iak|1.3.0
path-autocomplete|ion|1.7.0
vs-color-picker|lih|0.7.0
sass-indented|rob|1.4.5
autoimport|ste|1.5.3
vscode-wakatime|Wak|1.1.22
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open editor
2. Disable extensions with cmd

Reproduces without extensions: No

I open VS Code and I can't see content. I updated Windows, uninstalled node and install new one, I unistall nodist, I also made disk clearup on C: . I reinstalled VS Code but it didn't help. I don't know what to do. When I hover at something there s a tooltip, but I can not see the content.

Here is my code --status:
![codestatus](https://user-images.githubusercontent.com/20318051/34050731-29f55ef0-e1bc-11e7-8c37-e2440c1ca88e.png)

And here is how it looks like:
![vscode](https://user-images.githubusercontent.com/20318051/34050767-5294d2fa-e1bc-11e7-8beb-a3a75db3fabb.png)

**Comment by ramya-rao-a** [comment] 2017-12-15 17:33
- In the menu, go to Help -> Toggle Developer Tools -> Console. Can you share any errors/callstacks from there if any? 
- Do you see the same when running `code --disable-gpu --disable-extensions`?
- Any errors when running `code --verbose`?

**Comment by mieszczans** [comment] 2017-12-15 17:44
The point is I cant. If I will click on Toggle Developer Tools it seems to open but I can't see it - there was visible for 1 sec white window but disappeared(so it works). No matter what I will click on menu. It seems like working but it is not visible. I tried with cmd but it is the same - no visible changes. When I hover on that black area, mouse pointer is changing so elements exist there.

**Comment by Tyriar** [comment] 2017-12-15 17:55
@mieszczans did you see this previously? I don't think we changed anything to do with Electron which would almost certainly be the cause for something like this (that affects devtools).

**Comment by mieszczans** [comment] 2017-12-15 18:07
No I didn't. I've never had any problems with VSC. I uninstalled some programs, I did clearup disc C: and update Windows/packages with npm - now I don't even now what affect. I worked with electron very long time ago, so it can't be the cause. Electron is not even installed.

**Comment by mieszczans** [comment] 2017-12-15 18:24
@Tyriar I had Atom and it is built with Electron. So what should I do? I uninstalled it before issue appeared.

**Comment by Tyriar** [comment] 2017-12-15 19:04
@mieszczans VS Code is bundled with Electron. The thing is we didn't change the version of Electron in 1.19.

**Comment by ramya-rao-a** [comment] 2017-12-15 19:15
>  I tried with cmd but it is the same

I am assuming you tried `code --disable-gpu --disable-extensions`.

Can you share the output in the terminal when running `code --verbose`?

Can you try our [Insiders](https://code.visualstudio.com/insiders) and see if you have the same issue?

**Comment by ramya-rao-a** [comment] 2017-12-15 19:31
Also try `code --extensions-dir <some-folder> --user-data-dir <some-other-folder>` to ensure none of the cached user data is causing this problem

**Comment by mese79** [comment] 2017-12-15 21:02
Seems like i have the same problem after update to 1.19.0 on linux.
here is my console log:
`index.js:5 [uncaught exception]: TypeError: Cannot read property 'comments' of null
onError @ index.js:5
index.js:5 TypeError: Cannot read property 'comments' of null
    at file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:2920:762
    at Array.forEach (native)
    at e.setCustomTokenColors (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:2920:735)
    at new e (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:2927:679)
    at t.create (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:90:103)
    at e._createInstance (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:1209:289)
    at e.createInstance (file:///home/me/resources/app/out/vs/workbench/workbench.main.js:1208:560)
    at e.initServiceCollection (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:4516:741)
    at e.createContents (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:4511:118)
    at e.open (file:///home/me/VSCode/resources/app/out/vs/workbench/workbench.main.js:4518:113)
onError @ index.js:5
`

**Comment by ramya-rao-a** [comment] 2017-12-15 21:29
`setCustomTokenColors` is coming when trying to set the theme. cc @aeschli 

@mese79 Are you using any custom themes?

**Comment by mieszczans** [comment] 2017-12-15 21:42
I reset windows to default options and it is working now.

**Comment by ramya-rao-a** [comment] 2017-12-15 21:59
@mieszczans What non default options was it set to?

**Comment by mieszczans** [comment] 2017-12-15 22:44
Sorry not default,  just restoring system to starting options (format).  :D

**Comment by bpasero** [comment] 2017-12-16 08:39
I am not sure both issues are related but we have https://github.com/Microsoft/vscode/issues/40329 for the theme issue. Closing since it seems to work for @mieszczans again.

**Comment by ramya-rao-a** [comment] 2017-12-17 03:26
@bpasero The 2 issues are related. See https://github.com/Microsoft/vscode/issues/40329#issuecomment-352228936

@mese79 Can you check if you have `editor.tokenColorCustomizations` set to `null` in your settings file (you can find it at ~/Library/Application Support/Code/User/settings.json). If yes, then set it to `{}` instead and then try opening VS Code.

**Comment by mese79** [comment] 2017-12-17 18:28
@ramya-rao-a Setting `editor.tokenColorCustomizations` from `null` to `{}` was a solution for me.
Thanks.

**Comment by ramya-rao-a** [comment] 2017-12-17 19:46
Thanks for confirming @mese79!

**Comment by ramya-rao-a** [comment] 2017-12-18 06:03
Closing this issue as the workaround in https://github.com/Microsoft/vscode/issues/40308#issuecomment-352229028 helps in getting around this issue.

The root cause is #40339 which is proposed as a candidate for the recovery release 1.19.1

**Closed by ramya-rao-a** 2017-12-18 06:03 UTC
Labels: freeze-slow-crash, themes
