### ISSUE TITLE
g++ build  fail for  no input file

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#76362] opened 2019-06-30 06:32 UTC
Issue Type: <b>Bug</b>

> Executing task: g++ -g c:\Users\heart\Desktop\vscode_cpp\main.cpp -o C:\Users\heart\Desktop\vscode_cpp\main.exe -std=c++11 <

g++.exe: error: c:UsersheartDesktopvscode_cppmain.cpp: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by heartacker** [comment] 2019-06-30 07:09
I change my default console from cmd.exe to git-bash.exe, that why it fail, but, Is there any that can fix this problem between diff platform about path.

**Comment by alexr00** [comment] 2019-07-04 08:09
There is currently no way around this. You can specify a specific shell for the task in your task though:
```
			"options": {
				"shell": {
					"executable": "cmd.exe"
				}
			},
```

Dupe of https://github.com/microsoft/vscode/issues/38381

**Closed** 2019-07-04 08:09 UTC
Labels: *duplicate
