### ISSUE TITLE
Cannot navigate to next item after triggering and exiting hover

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#143689] opened 2022-02-23 10:31 UTC
Testing #143547

![recording](https://user-images.githubusercontent.com/2931520/155302182-f0365259-f439-456b-90d1-163e8eccdb30.gif)

**Comment by alexr00** [comment] 2022-02-23 12:01
Duplicate of https://github.com/microsoft/vscode/issues/143698

**Closed by alexr00** 2022-02-23 12:01 UTC
