### ISSUE TITLE
Extension crash

### ISSUE THREAD

**Issue by regd25** [microsoft/vscode#177108] opened 2023-03-14 16:14 UTC
Type: <b>Bug</b>

In normal use, unexpectedly VSCode close few extensions.

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|13, 8, 7|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|--crash-reporter-id 25abffcc-7de5-4a1f-a85f-ad8b8c795b4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (91)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.15.16
tsl-problem-matcher|amo|0.6.2
jest-snippets|and|1.9.1
ruby-debug-env|arc|0.3.4
swagger-viewer|Arj|3.1.2
markdown-mermaid|bie|1.17.7
ruby-debug|cas|0.3.5
solargraph|cas|0.24.0
regex|chr|0.4.0
vscode-sql-beautify|cla|0.3.16
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
vscode-mocha|Com|0.1.1
vscode-mysql-client2|cwe|6.2.5
vscode-eslint|dba|2.4.0
python-extension-pack|don|1.7.0
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.10.4
url-encode|fle|1.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-google-translate|fun|1.4.13
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
ruby|gro|0.1.0
terraform|has|2.25.4
terraform-preview|has|2023.2.2216
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
ts-debug|kak|0.0.6
vsc-python-indent|Kev|1.18.0
sequelize-snippets|kvc|1.0.0
vs-color-picker|lih|1.0.0
auto-barrel|mik|1.10.0
dotenv|mik|1.0.1
ruby-rubocop|mis|0.8.6
vscode-filesize|mkx|3.1.0
mongodb-vscode|mon|0.10.0
vscode-docker|ms-|1.24.0
vscode-language-pack-es|MS-|1.76.2023030809
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cpptools|ms-|1.14.4
remote-explorer|ms-|0.2.0
test-adapter-converter|ms-|0.1.6
vscode-serial-monitor|ms-|0.8.0
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
serverless-vscode-snippets|raf|0.0.5
ruby|reb|0.28.1
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
mongo-snippets-for-node-js|roe|1.3.12
nunjucks|ron|0.3.1
synthwave-blues|sab|0.0.5
trailing-spaces|sha|0.4.1
vscode-spotify|shy|3.2.1
js-jsx-snippets|sky|11.0.1
bunker|sld|1.1.6
es6-mocha-snippets|spo|0.2.2
now-playing|spy|0.4.0
iconfont-preview|stx|0.0.4
pdf|tom|1.2.2
errorlens|use|3.7.0
gitflow|vec|1.2.1
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
mui-snippets|vsc|1.0.1
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.28.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
pythonb192cf:30669361
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-14 18:21
Perhaps being caused by Copilot extension.

**Comment by isidorn** [comment] 2023-03-15 11:07
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:07 UTC
Labels: freeze-slow-crash-leak, extension-host
