### ISSUE TITLE
Windows Explorer pop-up resolution does not update if screen resolution has changed

### ISSUE THREAD

**Issue by syedtaqi95** [microsoft/vscode#114840] opened 2021-01-23 15:10 UTC
Issue Type: <b>Bug</b>

Reproduced by doing the following:
1. Connect to an external monitor (with a different resolution to your laptop).
2. Open VSCode.
3. Disconnect the monitor so you're back to your laptop screen
4. Go to "File > Open Folder..."

Expected behaviour:
Pop-up uses the laptop screen's resolution

Actual behaviour:
Pop-up uses the previously connected external monitor's resolution.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.35GB free)|
|Process Argv|--crash-reporter-id 200646a4-6eb2-4f73-a2f5-94dd162a3bf2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
opencv-intellisense|did|0.0.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
gc-excelviewer|Gra|3.0.40
vscode-map-preview|jum|0.5.8
cortex-debug|mar|0.3.9
gnu-debugger|met|1.0.4
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
pdf|tom|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by yume-chan** [comment] 2021-02-08 07:59
Related: electron/electron#26622

**Comment by yume-chan** [comment] 2021-02-21 14:46
Duplicate of #85898, didn't find that last time.

**Comment by deepak1556** [comment] 2021-02-22 03:45
Merging to https://github.com/microsoft/vscode/issues/85898

**Closed by deepak1556** 2021-02-22 03:45 UTC
