### ISSUE TITLE
MacOS Catalina breaks update check due to permissions check

### ISSUE THREAD

**Issue by gramster** [microsoft/vscode#82435] opened 2019-10-12 16:34 UTC
- VSCode Version: 1.37.1
- OS Version: MacOS 10.15

Steps to Reproduce:

1. Check for updates

Result:

A popup:
 
    Could not create temporary directory: Permission denied
    Source: Update service

I thought I'd work around this by adding Code in the Full Disk Access permission set but it seems you can't add apps there; the "+" is grayed out. Presumably there is some metadata needed on Mac to request permissions.

**Comment by NetworkStudioRu** [comment] 2019-10-13 13:49
Can not setup on Catalina too.

**Comment by noelgonzalez** [comment] 2019-10-17 13:17
Having the same issue as above when installing a fresh download in macOS Catalina.

**Comment by hanivic505** [comment] 2019-10-17 21:16
can't  install fresh vscode on new MAC OS Catalina 
`“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.`

**Comment by ereichl** [comment] 2019-10-21 07:56
> can't install fresh vscode on new MAC OS Catalina
> `“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.`

I have the same issue with macOS Catalina 10.15 (19A602)

**Comment by joaomoreno** [comment] 2019-10-21 09:41
cc @bpasero @deepak1556

**Comment by bpasero** [comment] 2019-10-21 10:01
Isn't this a duplicate of https://github.com/microsoft/vscode/issues/74782 ?

**Comment by joaomoreno** [comment] 2019-10-21 10:06
It could be... but might also be a separate issue regarding update..

**Comment by bpasero** [comment] 2019-10-21 10:15
@MarshallOfSound heard this before? maybe Squirrel related.

**Comment by MarshallOfSound** [comment] 2019-10-21 18:22
@bpasero is vscode notarized? If not there is no guarantee anything works well on Catalina.  Notarization is a hard requirement.

**Comment by bpasero** [comment] 2019-10-22 05:55
Not yet: https://github.com/microsoft/vscode/issues/74782

**Comment by priscilacclr** [comment] 2019-10-23 08:34
Having the same security error on Catalina. Sad times.

**Comment by gregg-cbs** [comment] 2019-10-31 13:30
Live Share does not seem to authenticate / login. Collaboration does not seem to work. 

Making a note here for you.

**Comment by dsteadman** [comment] 2019-11-12 16:17
@gregg-cbs  having the same issue here. live share logs weren't helpful and i'm not seeing any popups about permissions. the hunt continues...

**Comment by cheles** [comment] 2019-11-17 13:00
Based on [this](https://stackoverflow.com/a/58458252/4258896) comment, I was able to run it on Catalina.
Per my understanding, that will -d (delete) the com.apple.quarantine extended attribute from VS Code app.

The com.apple.quarantine extended attributes can be added when:
- You download a file with a quarantine-aware application, like Safari, Chrome, or Transmission. For a few applications like Firefox, quarantine is forced to be enabled in /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist.
- You extract an archive with an application like Archive Utility or OS X's tar or zip.
- You create a file with an application that has LSFileQuarantineEnabled set to true in the Info.plist.

I'll treat this as temporary workaround.

**Comment by bpasero** [comment] 2019-12-05 08:45
Merging into https://github.com/microsoft/vscode/issues/74782

**Closed by bpasero** 2019-12-05 08:45 UTC
Labels: bug, help wanted, install-update, mac, macos-catalina, needs more info

**Comment by kiranjd** [comment] 2019-12-05 19:39
> > can't install fresh vscode on new MAC OS Catalina
> > `“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.`
> 
> I have the same issue with macOS Catalina 10.15 (19A602)

Try this:
https://stackoverflow.com/a/58458252/7822449
