### ISSUE TITLE
"Problems" panel is displaying TypeScript errors from /node_modules/ packages with typescript.tsserver.experimental.enableProjectDiagnostics enabled

### ISSUE THREAD

**Issue by hi2u** [microsoft/vscode#117732] opened 2020-07-29 07:23 UTC
# Summary

I'm using vscode insiders edition, and with the config option `"typescript.tsserver.experimental.enableProjectDiagnostics": true` to display TypeScript errors for my whole projects in the "Problems" panel along the bottom of the screen, i.e. the feature introduced in https://github.com/microsoft/vscode/issues/13953

I seem to have an inconsistent issue with the "Problems" panel randomly displaying errors from `/node_modules/` code (which I obviously can't control/fix):

![typescript_problems_from_node_modules](https://user-images.githubusercontent.com/9689599/88765956-a0326180-d1ba-11ea-871c-3588934ced57.png)

I can see that the error in the screenshot above refers to one of my project files (App.test.tsx) - but the error itself seems to be coming from the package `/node_modules/ts-invariant` (see example `tsconfig.json` files further down).  I've tried lots of fiddling with my `tsconfig.json` - but the thing is that other stuff that shows TypeScript errors never shows these `node_modules` errors, so as far as I'm aware, vscode should be the same?...

* ✔️ When I run `tsc` from the command line, I don't see these errors at all.  
* ✔️ My project is setup with create-react-app + typescript, which typically yells at me and refuses to even render when there's any TypeScript errors - but it never mentions theses node_modules related errors at all.
* ❌ The only place I ever see these errors is in the vscode "Problems" panel.

And many other people have reported the exact same issue in the comments in: https://github.com/microsoft/vscode/issues/13953 - so seems it's not just me / my project specifically.

# Random coming/going

* But it's seemingly random, I haven't been able to figure out a consistent way to reproduce it immediately.  
* Usually when I first start vscode, it won't show them for a while, but they typically pop up about 15+ minutes later 
    * ...note that before these `node_modules` errors show, my own project-wide TypeScript errors are already working, so it's not coming/going at the end same time that the rest of the project-wide TS errors are showing - it seems to have its own timing that is affected by something else
* Sometimes they just go away on their own for a while, without me doing anything
* Sometimes restarting the typescript service makes them go away for a while
* Restarting vscode entirely usually makes them it go away for a while too
* During these "comings and goings": I'm not making any changes to `tsconfig.json` or any vscode settings at all

# Steps to Reproduce:

1. My project was originally created using: `npx create-react-app my_project_name --template typescript` - but from memory, I think I've seen these issues with other non-react projects too.
2. It seems to be a regular this when using package: https://www.npmjs.com/package/ts-invariant - but again, I think I've also seen the issue with other packages in other projects too - but being hard to reproduce, I can't find them right now
3. Beyond that - I'm not sure how to easily reproduce it immediately, due to the seeming randomness of it coming/going

# VSCode Version:
```
Version: 1.48.0-insider (user setup)
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:39:18.007Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

# Example `tsconfig.json` file from one of my projects

```json5
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react",
        //"rootDir": "./src" // <--- I've tried both with and without this, no difference
    },
    "include": ["src"],
    "exclude": ["node_modules", "./node_modules/*"]
}

```

# Example `tsconfig.json` from `/node_modules/ts-invariant/tsconfig.json`

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./lib"
  }
}

```

# Does this issue occur when all extensions are disabled?: Yes

* Yes, I've tried running with: `"C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --disable-extensions` 
* ...and it's the same thing, problem doesn't occur immediately, comes and goes in the same way as when running vscode normally.

**Comment by mjbvz** [comment] 2021-02-26 02:46
As noted, this is caused by `typescript.tsserver.experimental.enableProjectDiagnostics `. Please disable this experimental setting if you are running into issues with it

**Comment by PinkaminaDianePie** [comment] 2021-02-26 08:45
@mjbvz nice way to fix the issue! Would you suggest stopping using VSCode in case anybody found any other bugs in it?

**Comment by JerryGreen** [comment] 2021-02-26 10:20
Oh, I’m actually glad it got into Milestone. Thanks @mjbvz !

**Comment by Whazor** [comment] 2021-03-08 13:55
Until then to avoid those problems I use `!**/node_modules**` in the search filter.

**Comment by JerryGreen** [comment] 2021-03-08 14:00
@Whazor but this doesn't hide those errors in "problems" panel, isn't it?

**Comment by Whazor** [comment] 2021-03-08 16:47
Adding the `!` before the node_modules, makes sure you do not see any irrelevant problems.

**Comment by JerryGreen** [comment] 2021-03-08 17:16
@Whazor, oh I actually didn’t even notice “problems” tabs has such a filter. I was confused first, but now I understand about what filter you’re talking about. Yes, this helps a lot, thanks

**Comment by JerryGreen** [comment] 2021-03-08 22:18
Earlier I thought I'm getting this bug only in projects where multiple `tsconfig.json` are present, but today I noticed I'm getting this bug even in a project with a single `tsconfig.json`. Still, it's hard to describe concrete steps to reproduce the bug: it happens randomly time to time. As much randomly those problems disappear after a while. Weird

**Comment by frank-weindel** [comment] 2021-04-23 16:44
I'm noticing this bug with node_modules folders of folders that I don't even have loaded in my workspace anymore. I even restarted VS Code to confirm. Not sure where this feature is getting it's list of folders to scan, but it's somehow picking up perhaps stale cached copies of it.

**Comment by olafur-palsson** [comment] 2021-08-13 14:24
What about having the `MarkerService` that populates the problems panel optionally filter out `.gitignore`d files? The performance of `enableProjectDiagonstics` will still be bad but the `node_module` errors can be removed.

**Comment by Ploppy3** [comment] 2021-09-18 15:39
@mjbvz What is the state of this issue ?

**Comment by mjbvz** [comment] 2021-10-04 23:12
Closing in favor of https://github.com/microsoft/TypeScript/issues/36664

This feature is currently implemented in rather suboptimal way (which is why the setting is marked experimental). If you're running into trouble using it, try setting up a [watch task](https://code.visualstudio.com/Docs/editor/tasks) instead, which should perform better overall, the obvious downside being that you have to setup the watch task in the first place

**Closed by mjbvz** 2021-10-04 23:12 UTC
Labels: help wanted, typescript
