### ISSUE TITLE
Terminal: recent command list should de-duplicate

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143695] opened 2022-02-23 10:43 UTC
Testing #143430
1. Do `ls` twice
2. F1 > run recent commands
3. Notice two entries 🐛 

![Screenshot 2022-02-23 at 11 42 22](https://user-images.githubusercontent.com/1926584/155303898-81077016-0367-429c-b7f9-e0b44876c4fe.png)

**Comment by Tyriar** [comment] 2022-02-23 16:05
This was by design, the thinking being to make it work like like `history`, up arrow or ctrl+r in most terminal shells where only adjacent duplicates are merged:

![image](https://user-images.githubusercontent.com/2193314/155357925-40af8f7b-1dfc-4721-8acd-f243cca5e2eb.png)

I guess deduplicating all of them makes more sense in this use case as well as the eventual autocomplete though.

**Closed** 2022-02-23 16:07 UTC
Labels: bug, terminal-shell-integration
