### ISSUE TITLE
feat(): Multiple Command Keybindings

### ISSUE THREAD

**Issue by wbhob** [Microsoft/vscode#31323] opened 2017-07-24 14:04 UTC
I would like to see VS Code have a feature for running commands in succession from a single keybinding. This is especially useful when formatting code, so we can run formatting commands in succession. For example: FORMAT, Sort Imports, Align, Align Comments.

- VSCode Version: 1.14.2
- OS Version: macOS 10.12.5

**Comment by mjbvz** [comment] 2017-07-24 17:43
Duplicate of #6617

**Closed by mjbvz** 2017-07-24 17:43 UTC
Labels: duplicate, new release

**Comment by wbhob** [comment] 2017-07-24 17:47
Oh you're right my bad
