### ISSUE TITLE
Offline Extension Installation fails

### ISSUE THREAD

**Issue by Outek** [Microsoft/vscode#39081] opened 2017-11-24 06:44 UTC
- VSCode Version: 1.18.1
- OS Version: Windows Server 2016 x64

Steps to Reproduce:

1.  code --install-extension C:\Temp\ms-vscode.PowerShell-1.5.1.vsix

Error: connect ETIMEDOUT 13.85.19.92:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

I can't install the Powershell Extension for vscode offline with a local vsix file. 
- Removed vscode / installed it, again no success with extensions
- Other extensions don't work as well

The Server has no Internet connection.

Similar to this problem:
https://stackoverflow.com/questions/47445070/why-am-i-getting-a-timeout-error-when-i-install-vs-code-extensions-from-vsix-fi

**Comment by sandy081** [comment] 2017-11-24 09:12
Duplicate of #37973

**Closed by sandy081** 2017-11-24 09:12 UTC
Labels: extensions
