### ISSUE TITLE
Markdown preview context menu cut/copy doesn't work.

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#156772] opened 2022-08-01 02:40 UTC
Issue Type: <b>Bug</b>

Markdown preview context menu cut/copy doesn't work.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
All-Autocomplete|Ati|0.0.23
gitlens|eam|12.1.2
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.215
nim|kos|0.6.6
mypy|mat|0.2.2
rainbow-csv|mec|2.4.0
vscode-docker|ms-|1.22.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
cpptools|ms-|1.11.4
hexeditor|ms-|1.9.8
shader|sle|1.1.5
io|tru|3.1.1
rainbow-tags|vol|0.4.1
php-debug|xde|1.27.0
php-intellisense|zob|1.0.11

</details>

**Comment by gjsjohnmurray** [comment] 2022-08-01 09:37
/duplicate of #141080

Workaround is to use Ctrl+C shortcut instead.

**Closed** 2022-08-01 09:38 UTC
Labels: *duplicate
