### ISSUE TITLE
Adjust the size of "Go to File" Popup Window

### ISSUE THREAD

**Issue by dineshsuthar786** [microsoft/vscode#121295] opened 2021-04-14 14:37 UTC
`Go to File` popup window _(which is opened using command + p for mac)_ has size fixed and I do not find any option to adjust the popup window size. Due to small popup window, sometimes complete file path is not getting displayed. 

There should be some option to adjust the size of `Go to File` popup window. Here is an attached screenshot for the same.

<img width="608" alt="Screenshot 2021-04-14 at 7 56 05 PM" src="https://user-images.githubusercontent.com/1614367/114727535-e7b64900-9d5b-11eb-8f4e-35caa7c96cda.png">

**Comment by TylerLeonhardt** [comment] 2021-04-15 17:52
Thanks! This is a duplicate of https://github.com/microsoft/vscode/issues/85374

**Closed by TylerLeonhardt** 2021-04-15 17:52 UTC
