### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by cdab-andreas** [microsoft/vscode#97518] opened 2020-05-11 15:30 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:112241:13)
    at Object.releaseDocument (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:112236:20)
    at /Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:135319:45
    at Object.forEach (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:167:30)
    at Proxy.dispose (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:135318:20)
    at InferredProject.Project.close (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:139542:38)
    at InferredProject.close (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:140420:40)
    at ProjectService.removeProject (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Users/andreasolsson/Code/cPlan/CDAB.cPlan/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.46.0-insider (2b472d1e4aaaecdda5ca96289869f90ae82de3a1, 2020-05-11T09:54:42.339Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (2.64GB free)|
|Process Argv|-psn_0_8304619|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
codesnap|adp|1.0.27
project-manager|ale|10.12.0
i18n-ally|ant|2.1.5
codestream|Cod|7.2.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.1.2
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
es7-react-js-snippets|dsz|2.7.1
git-cheatsheet|dzh|1.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.6.0
vscode-todo-plus|fab|4.17.1
file-icons|fil|1.0.24
docker-explorer|for|0.1.7
vscode-pull-request-github|Git|0.16.0
todo-tree|Gru|0.0.174
vscode-test-explorer|hbe|2.18.0
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.29
theme-karyfoundation-themes|kar|20.0.3
vscode-jest-test-adapter|kav|0.3.0
vscode-go-to-mdn|kby|1.1.1
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.15
azure-pipelines|ms-|1.165.1
vscode-docker|ms-|1.1.0
network-edge-devtools|ms-|1.0.0
vscode-edge-devtools|ms-|1.0.7
mssql|ms-|1.9.0
remote-containers|ms-|0.117.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
js-debug-companion|ms-|1.0.1
node-debug2|ms-|1.42.2
references-view|ms-|0.0.52
vsliveshare|ms-|1.0.2106
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
vscode-react-native|msj|0.15.0
sqltools|mtx|0.21.7
color-highlight|nau|2.3.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|0.27.0
material-icon-theme|PKi|4.1.0
code-spell-checker|str|1.8.0
code-spell-checker-swedish|str|0.1.3
ayu|tea|0.18.0
git-rebase-shortcuts|tre|1.0.5
errorlens|use|3.1.1
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
quokka-vscode|Wal|1.0.289
vscode-todo-highlight|way|1.0.4
vscode-webhint|web|1.5.5
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.5.0

(11 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-05-11 16:09
Does this reproduce with TS 3.9+?

**Comment by mjbvz** [comment] 2020-05-11 17:09
Duplicate of https://github.com/microsoft/TypeScript/issues/37500

**Closed by mjbvz** 2020-05-11 17:09 UTC
Labels: needs more info
