### ISSUE TITLE
graphical artifacts when opening some special C file (probably because of shadowed areas)

### ISSUE THREAD

**Issue by vvavrychuk** [Microsoft/vscode#56732] opened 2018-08-18 07:53 UTC
- VSCode Version: 1.26.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create special directory for test

        mkdir ~/temp/test

2. Put C file with some code under ifdefs in this directory. For example this one https://raw.githubusercontent.com/torvalds/linux/master/init/main.c
3. Open ~/temp/test directory in VS code:

        code ~/temp/test

4. Open C file by clicking on it in Explorer.
5. Scroll C file down to when CONFIG_KALLSYMS ifdefs starts.
6. Observe graphics artifacts on screen.

Screencast https://drive.google.com/open?id=1c_6gKcmA3BGhMP4yNn0gxzBaQ9xYzHBC

Does this issue occur when all extensions are disabled?: No

**Comment by vvavrychuk** [comment] 2018-08-20 16:12
I can reproduce with `--disable-gpu`.

This issue is not reproduced without ms-vscode.cpptools extension. You probably do not have this extension and therefore not reproduce.

This extension makes some areas near KALLSYMB shadowed because it thinks that they are disabled code. This shadowed areas kick off graphical artifacts.

**Comment by bpasero** [comment] 2018-08-21 11:11
@vvavrychuk does it reproduce when using a VSCode build with a newer Electron version (3.0.x in this case): https://az764295.vo.msecnd.net/exploration/fc217192b85f2aeb5fce410a33a66a8b9d9ce82b/code-exploration-1534831385.tar.gz

**Comment by vvavrychuk** [comment] 2018-08-21 16:15
I found other required item to reproduce this issue: it is my user data dir.

If I do `code --user-data-dir ~/temp/code/userdata .` issue is not reproduced.

I am not sure what can be so special in my user data dir that is causing this.

**Comment by vvavrychuk** [comment] 2018-08-21 16:43
I have found that missing element in user data to reproduce this issue was "editor.renderWhitespace=all". But even with it issue is not reproducible with Electron 3.0.x

**Comment by rizno** [comment] 2018-11-10 12:41
Hi, I have the exact same issue with vscode 1.28.2.
I'm using Ubuntu 18.04 64bits
With only one extension loaded: ms-vscode.cpptools-0.20.1
Using vscode 1.27-exploration proposed (https://github.com/Microsoft/vscode/issues/56732#issuecomment-414638428) the problem is not present anymore.

**Comment by carlushuang** [comment] 2018-11-11 03:19
same issue faced, ubuntu 16.04-64bit, with vscode 1.28.2. and the glitch thing occurs when there is #region that code is not compiled in. In my case, both the editor and the left side panel(Explorer/Search/...) have this kind ot effect.

![sss](https://user-images.githubusercontent.com/8322173/48308557-f0aafb00-e5a2-11e8-8684-ba25a93f0de0.png)

notice that there are characters unseen. When I scroll mouse, the unseen-characters may appear at different place.

And yes, when disable ms-vscode.cpptools, everything goes well. But I think it is because the editor may not recognize the code has been commented out by #region, and not display them in gray.

**Comment by fadeevab** [comment] 2018-11-12 05:36
> Hi, I have the exact same issue with vscode 1.28.2.
> I'm using Ubuntu 18.04 64bits

I have the same configuration and the same glithes on some .c/.h files. C/C++ extension is enabled. There are regions with "disabled" code by #ifdef. Issue is not reproduced when extension is disabled.

**Comment by bpasero** [comment] 2019-01-25 16:24
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:24 UTC
Labels: editor-rendering, electron, fixed-in-electron-3.0.x, linux, upstream
