### ISSUE TITLE
Background color highlighting drawn incorrectly

### ISSUE THREAD

**Issue by arthurlockman** [Microsoft/vscode#15126] opened 2016-11-07 21:30 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

![screen shot 2016-11-07 at 16 27 27](https://cloud.githubusercontent.com/assets/158981/20076608/1d6556f6-a507-11e6-9dd6-e1b5283c7afb.png)

---

Background color highlighting in the editor is broken in dark themes. There are chunks of the screen that are lighter than the background color set in the theme. This is also present in lighter themes (like the built-in Solarized light), but in light themes it is much less noticeable. Notice in the screenshot the highlight problems in the editor window, as well as the file selector sidebar. 

Steps to Reproduce:

1. Set VS code to use built-in solarized dark or dark+ theme.
2. Observe behavior.

**Comment by colebrew** [comment] 2016-11-08 00:43
To add to the repro steps: on my late 2013 MacBook Retina, these off-color background rectangles appear when vscode is displayed on an external monitor, but not on the native retina screen. Also, I found that this happens in certain size configurations -- resizing the panes can cause the rectangles to disappear. 

@arthurlockman can you comment on your display setup?

**Comment by arthurlockman** [comment] 2016-11-08 04:11
@colebrew Sure. I'm not using a retina display. I have 2 24" 1080P monitors hooked up to a Mac Pro. Resizing the panes doesn't make them go away for me, they're always there unless I set the theme to a theme that's all white.

**Comment by muratsu** [comment] 2016-11-08 11:53
I'm having the same issue on MBP (late 13). Mac OS version: 10.12.1 (16B2555). VS Code: 02611b40. I don't have any external displays setup. My color profiles: Color_LCD_D65.icc. Resolution is set to scaled (1920x1200).

![image](https://cloud.githubusercontent.com/assets/1308560/20097992/20986602-a5ba-11e6-81b0-08cfbb8b5ccd.png)

**Comment by mrmlnc** [comment] 2016-11-08 12:25
Please, use search before create new issue.

See official release notes: http://code.visualstudio.com/updates#_macos-sierra-support
See already created issues: #12473, #12474, #12523, #12571, #13175, #13192, #13959, #14233, #14540, #14692

**Comment by aeschli** [comment] 2016-11-08 14:24
thanks @mrmlnc ! Marking as duplicate of #12473.

**Closed by aeschli** 2016-11-08 14:24 UTC
