### ISSUE TITLE
Compile on save is not working

### ISSUE THREAD

**Issue by ishrathkkm** [microsoft/vscode#74405] opened 2019-05-27 12:43 UTC
Steps to Reproduce:

1. Angular 6 code is not auto compiling while saving the files

This is my tsconfig.json

{
    "compileOnSave": true,
    "compilerOptions": {
      "outDir": "./dist/out-tsc",
      "sourceMap": true,
      "declaration": false,
      "moduleResolution": "node",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "watch" : true,
      "target": "es5",
      "typeRoots": [
        "node_modules/@types"
      ],
      "lib": [
        "es2017",
        "dom"
      ]
    }
}
  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-05-28 17:00
Duplicate of #13953

**Closed by mjbvz** 2019-05-28 17:00 UTC
Labels: typescript
