### ISSUE TITLE
1.75.0 doesn't allow to remove some system keybindings (Zoom)

### ISSUE THREAD

**Issue by janjaali** [microsoft/vscode#173253] opened 2023-02-03 07:07 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.75.0
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open Keyboard Shortcuts UI or keybindings.json file
2. Try to remove 

```json
    {
        "key": "cmd+[BracketRight]",
        "command": "-workbench.action.zoomIn"
    },
```

**Comment by mojo2012** [comment] 2023-02-03 14:26
I had my keybindings configured in the way that `cmd+` and `cmd-` zooms the font. But this is not working any more for zoom in. The `cmd+` seems to be hardcoded to window view zoom in.
Please fix asap. This breaks my whole workflow :-(

**Comment by trkoch** [comment] 2023-02-03 16:00
1.75.0 also breaks disabling `cmd+[Period]` for me.

**Comment by janjaali** [comment] 2023-02-05 19:44
If it helps, using the same keybindings on my Windows machine with the latest release works like a charm. Guess this is somewhat related to MacOs.

**Comment by alexdima** [comment] 2023-02-05 21:02
Duplicate of #173325

**Closed by alexdima** 2023-02-05 21:02 UTC
Labels: new release
