### ISSUE TITLE
VSCode for linux only match first 2000 lines.

### ISSUE THREAD

**Issue by diigu** [Microsoft/vscode#35217] opened 2017-09-27 10:08 UTC
As you see, I selected "pid", but it only match first 2000 lines even I scroll to bottom.

![image](https://user-images.githubusercontent.com/5822468/30907913-a4205c44-a3ae-11e7-9d5d-edc8e70a7c76.png)

**Comment by alexandrudima** [comment] 2017-09-28 10:00
Duplicate of #1110

**Closed by alexandrudima** 2017-09-28 10:00 UTC
Labels: editor, editor-1000-limit
