### ISSUE TITLE
Integrated editor in webview

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#94983] opened 2020-04-11 09:58 UTC
**Summary**
Allow to create our own "Interactive Playgrounds" mixing HTML and integrated editors.

**Description**
VS Code has a nice interactive playground, which is a webview with integrated editors.

*Help > Interactive Playground*

![](https://user-images.githubusercontent.com/15984272/79040618-fb2f5100-7be9-11ea-828f-78783a113efe.png)

There editors embed all the features of a default text editor:
- syntax highlighting
- autocompletion
- extension contributions
- ...

I would like to create a webview containing editors like that.

Currently, we can only create webviews with an HTML textarea, [like this](https://user-images.githubusercontent.com/15984272/79040749-0fc01900-7beb-11ea-980d-8009611b8a84.png).

The content of the Interactive Playground is [here](https://github.com/microsoft/vscode/blob/72c700cf5419663c7bf833308233cc760709bcaf/src/vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough.ts#L132)
https://github.com/microsoft/vscode/blob/72c700cf5419663c7bf833308233cc760709bcaf/src/vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough.ts#L132-L143

Relates to #77131 even if this can apply to webviews that are not custom editors

**Comment by mjbvz** [comment] 2020-04-11 22:22
Duplicate of #93265

**Closed by mjbvz** 2020-04-11 22:22 UTC
