### ISSUE TITLE
TS server keeps crashing when is being initialized

### ISSUE THREAD

**Issue by danielbichuetti** [microsoft/vscode#181120] opened 2023-04-28 11:33 UTC
Type: <b>Bug</b>

After we installed @pulumi/azure-native module in a project, TS server doesn't work on it anymore. It keeps loading and crashs.

We tested both locally and remotely. After this module gets installed, VS Code starts with this behavior. Unsure why this started happening, as we used the same module on projects some months ago.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-69-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.63GB free)|
|Process Argv|--crash-reporter-id 26f46753-3828-4fb7-b316-c2484eeda75f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 139.144.187.121|
|OS|Linux x64 5.15.0-69-generic|
|CPUs|AMD EPYC 7F72 24-Core Processor (16 x 3199)|
|Memory (System)|62.80GB (56.42GB free)|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.5
remotehub|Git|0.54.0
jupyter-keymap|ms-|1.1.0
vscode-ai-remote|ms-|0.28.1
remote-containers|ms-|0.291.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.32.0
remote-server|ms-|1.1.0
env-cmd-file-syntax|Nix|0.3.0
vscode-icons|vsc|12.4.0
gitlens|eam|2023.4.2805
file-downloader|min|1.0.12
vscode-azurefunctions|ms-|1.10.5
vscode-azureresourcegroups|ms-|0.7.1
vscode-docker|ms-|1.25.0
vscode-aks-tools|ms-|1.3.11
vscode-kubernetes-tools|ms-|1.3.11
black-formatter|ms-|2023.3.10961008
gather|ms-|2022.3.2
isort|ms-|2023.9.11141005
pylint|ms-|2023.5.10901018
python|ms-|2023.7.11111009
vscode-pylance|ms-|2023.4.41
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-ai|ms-|0.31.2023042109
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.3
azurecli|ms-|0.5.0
vscode-yaml|red|1.12.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30725893

```

</details>

**Comment by mjbvz** [comment] 2023-05-01 18:23
Duplicate of https://github.com/microsoft/TypeScript/issues/50809#issuecomment-1261218807

This issue needs to be fixed by pulumi

**Closed by mjbvz** 2023-05-01 18:23 UTC
