### ISSUE TITLE
VSCode uses all the cpu and ram

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/vscode#56662] opened 2018-08-17 09:35 UTC
Since the last update, when I launch VSCode it eats all the esources of my PC. In this screenshot it is using 99% of the CPU and 34% ot the RAM, but sometimes it is even 70%.
This happens when I open a big project (Babel), but not with small projects.

![schermata da 2018-08-17 11-25-54](https://user-images.githubusercontent.com/7000710/44259218-3741c100-a211-11e8-9b47-a01c07686c29.png)

- VSCode Version: 1.26.0
- OS Version: Ubuntu 18.04.1

Does this issue occur when all extensions are disabled?: Yes.

**Comment by nicolo-ribaudo** [comment] 2018-08-17 12:33
I don't have this problem anymore with version 1.26.1.

People who :+1:ed, can you confirm?

**Comment by lmkz** [comment] 2018-08-21 23:38
Can confirm, permanently 100% CPU split across several Code.exe processes 1.26.1, no files open in editor (but "project" folder open in explorer). Have disabled all extensions. Tried both 32 and 64 bit versions.

**Comment by graph** [comment] 2018-08-26 07:46
I have same issue on Ubuntu with version 1.26.1. Code bootstrap is eating all my ram and causes my computer to thrash. It starts as soon as I open a specific project which the folder is 6GB in size. In the image bellow I didn't wait for my laptop to thrash, but the memory usage just keeps going up and doesn't stop.

![image](https://user-images.githubusercontent.com/1088059/44625978-5f50b480-a8e2-11e8-9e63-8e9256363063.png)

**Comment by bpasero** [comment] 2018-08-27 04:43
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by graph** [comment] 2018-08-31 00:28
@bpasero after disabling & enabling the extensions I can't reproduce the issue to the extent that I experienced RAM usage. Do you still want me to just click the report button?

**Comment by bpasero** [comment] 2018-08-31 05:02
@graph if you think this is caused by the C++ extension then I suggest to report this issue to them.

**Comment by graph** [comment] 2018-08-31 12:00
I'm just providing info. VS Code has been running fine all week for me. I guess reenabling the extensions reset something. It sounds like it's too hard to reproduce. I'm fine if you close this issue for difficulty of reproducing lol.

**Closed** 2018-09-05 16:42 UTC
Labels: needs more info
