### ISSUE TITLE
Typescript + Divide operator make syntax highlighting goes wrong...

### ISSUE THREAD

**Issue by nikitatchikita** [Microsoft/vscode#14941] opened 2016-11-03 22:04 UTC
I'm having an issue with my code with the new version **(1.7.1)**, divide operator isn't correctly highlighted and cause problems to the rest of the code.

**Screenshots:**

**With divide operator** `/`

http://image.prntscr.com/image/450c3ed8706d452b9872dea8379ef6e3.png

![With divide](http://image.prntscr.com/image/450c3ed8706d452b9872dea8379ef6e3.png)

**Without divide operator, replaced by**  `+`

http://image.prntscr.com/image/627da1a2cf7f46d292f66bbef4a64149.png

![Without divide](http://image.prntscr.com/image/627da1a2cf7f46d292f66bbef4a64149.png)

- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Use this code with Typescript in a class (or not, but mine is inside a class function) and you'll see by yourself: 

```
var process = Math.max(0, Math.min(1, (Time - User.LastMove) % (1000 / User.Speed) / (1000 / User.Speed)));

if(times > 100000 || times < 0) {
       times = 0;
}
```

Please fix this!

**EDIT**

Seems it's only occuring when the next operation is a divide
Check this:
![img](http://image.prntscr.com/image/e124cacfd1984d3f936f7d2a68d6d10d.png)

And

![img](http://image.prntscr.com/image/7290c796b4084a609a5ca65823874e25.png)

Also 
`/ /`
is considered as a JSON (I've seen the class with the devtools) and has the same color as the image before

**Comment by rebornix** [comment] 2016-11-03 22:17
This issue shares the same root cause as https://github.com/Microsoft/vscode/issues/14921#issuecomment-258237024 so I'd like to close this first and track the stuff there.

**Closed by rebornix** 2016-11-03 22:17 UTC

**Comment by nikitatchikita** [comment] 2016-11-03 22:31
@rebornix Okay, just if it can help you, this issue is concerning all the color schemes
