### ISSUE TITLE
SCM cursor jumps to bottom-most input box after clicking commit button in multiroot workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#124308] opened 2021-05-21 00:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-insider (user setup) 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. In a multiroot workspace with at least 2 git repositories, stage and commit a change using the SCM UI
2. After committing, the cursor automatically jumps to the bottom-most input box in the SCM UI 

![recording (2)](https://user-images.githubusercontent.com/30305945/119062694-476fc780-b98c-11eb-9011-3b622cf9dd47.gif)

(I can reliably reproduce this and I've noticed this happen for a few months now, so I don't think this is a recent change. It's somewhat frustrating when I've got a large number of changes in my working tree and am splitting them into multiple commits, since I'll start typing the next commit message while the current change is being committed and part of the message inevitably ends up in the wrong box.)

**Comment by lszomoru** [comment] 2021-11-05 14:08
Duplicate of #135143.

**Closed by lszomoru** 2021-11-05 14:08 UTC
Labels: bug, scm

**Comment by alexr00** [comment] 2021-11-08 09:02
Clearing milestone as there was not change.
