### ISSUE TITLE
Replace tslint with eslint

### ISSUE THREAD

**Issue by BO41** [microsoft/vscode#82891] opened 2019-10-19 12:47 UTC
[TSlint](https://github.com/palantir/tslint) is getting deprecated very soon (see [roadmap](https://github.com/palantir/tslint/issues/4534)).
This project, and connected projects, should consider switching to [Eslint](https://github.com/eslint/eslint).

Eslint already contains a lot of basic lints. For typescript specific there is this [plugin](https://github.com/typescript-eslint/typescript-eslint).
To smoothly switch, you can use [this script](https://github.com/typescript-eslint/tslint-to-eslint-config) to use tslint with eslint until all lints are ported.

cc #82053

**Comment by usernamehw** [comment] 2019-10-19 18:34
Might be a duplicate of #79230.

**Closed** 2019-10-20 18:49 UTC
