### ISSUE TITLE
Remember previous window size and position per workspace

### ISSUE THREAD

**Issue by raksa** [microsoft/vscode#61838] opened 2018-10-26 02:10 UTC
I use VSCode to develop many projects, require to open many folders in different window in same time.
Again and again after opened folder in window I need to resize VSCode window and prepare them to previous position.
If possible I want VSCode can remember previous state of each opened folder.

**Comment by weinand** [comment] 2018-10-26 08:55
Remember window size and position works for me (on macOS).
Make sure to have this setting:  `"window.restoreWindows": "all"`

**Comment by raksa** [comment] 2018-10-26 09:01
OS
==
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

VSCode
==
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by weinand** [comment] 2018-10-26 09:21
I tried the same on Ubuntu 18.04.1 LTS and it works fine.

**Comment by raksa** [comment] 2018-11-01 02:08
Each window will reopen in different position and size, they should remember and restore old state for each folder.
[Demo video](https://drive.google.com/file/d/1JUMjgb3r6-jkeR1BT4Tj39__yFIyJzJx/view)

**Comment by kieferrm** [comment] 2018-11-04 18:16
@raksa, I see only one window is restored. Does the same happen if you set the setting to 'all', quit VS Code through the 'File' menu, then restart, open multiple windows, and quit through the 'File' menu again?

**Comment by raksa** [comment] 2018-11-06 04:44
if exit via File's menu and reopen they're restored to same previous size and position.
![out1](https://user-images.githubusercontent.com/4116021/48043326-ac8db400-e1b8-11e8-8234-ec7bc4cc3c2a.gif)

but if close it one by one then open via **Open Recent** it will be restored with different size and position.
![out2](https://user-images.githubusercontent.com/4116021/48043373-f1194f80-e1b8-11e8-8967-6ab244e2c4dc.gif)

**Comment by msftrncs** [comment] 2019-02-07 07:11
I have set the option to 'all', but I am not getting the affect I am expecting.   I am expecting each window, as I am reopening them (folder or workspace) to remember where it last was, but, after the first window (that hot exited with files open), reopens, any additional windows open as a small window in the center of the screen.   The detail …  I am closing all windows, one at a time, and then reopening them one at a time.  I think this setting only applies to opening or closing them all at the same time (and possibly only after a 'restart' command?  The setting that seems to apply to this case is 'window.newWindowDimensions'. and it doesn't have any desirable values.

I think, if VS Code can remember what files were open in a given folder, it can also remember where on the screen the window was when it was last closed (providing that location of the screen is actually available/viewable).

**Comment by chrmarti** [comment] 2019-02-07 08:16
@raksa @msftrncs What you describe is the designed behavior. @bpasero to confirm.

**Comment by msftrncs** [comment] 2019-02-07 21:03
@chrmarti, @bpasero:  Is this really a 'design' or is it a limitation?   Can this instead be a feature request (that each folder or workspace window can remember its own window position and size)?  They already remember the files that were open and the editor layout.  I'd be more interested in size than position, if both were not possible.

**Comment by bpasero** [comment] 2019-02-08 06:20
@msftrncs if you configure `"window.restoreWindows": "all"` in settings, each window will restore its position and size upon a restart. Or do you want to preserve the size even after a window has been closed for that said workspace?

**Comment by msftrncs** [comment] 2019-02-10 04:40
"window.restoreWindows": "all" only works if I use EXIT in the file menu to close all the windows at once.  I would like to preserve the size of a workspace if it was closed and opened separately from the main window, or even in place of the main window.    I might have last closed down on one project and the next time I open it may be with a different project, and each will have different windows open, with different folders, different files open based on where I last left off, etc...

**Comment by bpasero** [comment] 2019-02-10 10:49
@msftrncs so to be specific, you want to preserve window size and location for each opened workspace individually?

**Comment by raksa** [comment] 2019-02-11 05:13
VSCode editor of folder can remember state inside (can remember opening editors, panel, explorer...)
wish it could remember outside state also e.g. window size and window position

**Comment by bpasero** [comment] 2019-02-11 07:16
?

**Comment by msftrncs** [comment] 2019-02-14 05:19
@bpasero, correct, if possible, both window size, and window position for each workspace, as @raksa stated, it already remembers the 'inside' state, of which files were open and how they were tiled.  From my point of view, each workspace is like a completely separate instance of VS Code and may be completely unrelated projects that I might just happen to have more than one of open at any time, and thus I don't want to have to open and close them all together in order to have the size and position remembered.

**Comment by demiro** [comment] 2019-07-25 08:13
OK, I know much of this is covered here:
https://github.com/microsoft/vscode/issues/10121

But, regarding remembering the window positions is becoming really, really frustrating on a laptop that connects to multiple monitors (which is very typical in a workplace).

So my regular setup (laptop + 2 monitors) I have 3 VSCode windows (3 different projects) ... they all have different layouts. (2 of the projects are full size on one monitor... the most important one is expanded over 2 monitors (not full width, 3/4 of the width  [with 3 columns]) . 

The problem is, when I close down the lid, or disconnect one of the monitors, or connect in a meeting room, or login again to the system, or connect to different monitor setup..... all the windows get rearranged again. This is probably not VSCode issue, I know... more windows issue, but...  each workspace could have a command to remember the layout (size, position) and to easy recall it. So when I set it up ... when I am happy with it... I save it... and when it's messed up, I run the command and the window get's re-positioned to the previous state... That would help me a looooads of headaches!

Cheers!

**Comment by tomByrer** [comment] 2020-03-04 14:46
Even a plugin would help here....?

**Comment by cole-paciano** [comment] 2020-04-02 18:56
Any forward motion with this request?  Keep hoping to see this has been done in each version release (really the only thing I've been hoping for) but it hasn't.  It would be great to not have to resize and reposition all my various project's windows every time I open/close them.

**Closed** 2020-11-06 07:00 UTC
Labels: *out-of-scope, feature-request, workbench-window

**Comment by jirimracek** [comment] 2020-11-07 15:14
Workaround on Debian Linux, Cinnamon desktop - not tested anywhere else

The way I work:  
1. I use 3 VS Code windows, on 3 different virtual desktops, one each for different projects  
2. I open an xterm (gnome-terminal), cd to a directory of the project and start VS Code by typing _code ._ (note the **dot** - start VS Code in current directory)  
3. My preferred desktop organization is to have an open xterm bordering the desktop on the right at its normal size and VS Code on the left, between the left desktop border and the xterm, sized such that I can see both

Issue: 
After I exit from all 3 VS Code windows, and start reopening next day, the first window normally opens at position & geometry of the last one from which I exited, the subsequent windows open at full screen and block the xterm from my view - pretty much the issue we have here.

The idea:
Use [xdotool](https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html) to find and position/resize windows

Script: 
pick the pieces you want (I place the script in the project directory and run it there)

```
#!/usr/bin/bash

# move xterm I am in to the right side of desktop - this is the easy part, ignore if you don't care
xdotool getactivewindow windowmove 2400 0

# start VS Code in current directory
/usr/bin/code .    

# setup loop, we need to give VS Code a little time to start, otherwise xdotool will not find it
let counter=0 
let vsid=0 

# start looking for it, sleep 1 second, try it 10 times before you give up 
while [[ ${counter} -lt 10 ]]; do
  ((counter++))
  sleep 1s

  # search for window with title '.*verblogic.*Visual Studio Code' - use what you see in your VS Code title bar
  vsid=$(xdotool search --name '.*verblogic.*Visual Studio Code')

  # if found (result of last command is 0), then
  if [[ ${?} -eq 0 ]]; then

    # activate the window, send it Alt+F5 - the "window unmaximize" kb shortcut - yours may be different
    # need to unmaximize first, size and move commands have no effect on maximized windows
    xdotool windowactivate --sync ${vsid} key Alt+F5

    # resize
    xdotool windowsize ${vsid} 2360 2090

    # move it to where you want
    xdotool windowmove ${vsid} 0 0

    # done, get out
    break;
  fi
done

```

Hope this helps to someone, happy coding
J.

**Comment by timtofan** [comment] 2020-11-14 12:22
One possible workaround is to keep "a buffer" of one or two extra vscode windows always open and positioned at the right location on the screen, and use "Git Project Manager" extension to switch between projects within same open window. It's not as good as a requested proper solution, but a bit better than manually positioning a new window on each open.

**Comment by mark-hahn** [comment] 2021-02-03 22:31
Can I position a window from a vscode command-line when opening a workspace?  If so I could write a script to open a specific workspace at a specific position.

BTW, I am yet another user that would kill for a feature to remember window positions by project.  I don't understand why this would be ignored.  Does no one else have many workspaces open at once.  My set up recently has six workspaces open all the time.

**Comment by robsonbucci** [comment] 2021-03-18 18:07
I have 2 monitors and the second one doesn't remember the last position.  what works for me was setting > Window > new window > new window dimensions = inherit.

**Comment by bendilley** [comment] 2021-06-14 12:31
Thanks @robsonbucci - that's not _exactly_ what I would have liked but it's a pretty decent compromise for my use cases, and very similar to how Sublime Text works (which is where I've come from).

**Comment by eengstrom** [comment] 2022-05-18 14:51
Since the core VSCode Developers have deemed this a non-issue, does anyone know of an extension that would do this "right"?  

Commentary:  I'm really surprised that someone decided that it's important enough to re-open the **first** window/workspace to the same size and position when it last closed, but all subsequent windows/workspaces are always tiny little windows in the center of the screen, ignoring the position and size of the workspace as last remembered.  Clearly the functionality is there, but only for the first workspace?  Why would that be a "feature".

For now, I'm suffering with the use of `Window: New Window Dimensions == offset`, but disliking it every time.

**Comment by demiro** [comment] 2022-05-18 15:54
I am so disappointed they closed this issue down! I am really surprised how they are implementing some nonsense functionality over this crucial and basic functionality that is annoying so many devs out there... beyond my comprehension

**Comment by mcswell** [comment] 2022-06-16 21:29
@demiro, same here.  EVERY TIME I re-open VSC on my Windows machine, I have to re-size it, and often have to re-size the individual panes after re-sizing the window.  Ridiculous.  

This used to work on Visual Slickedit and jEdit, not to mention virtually every other program I've ever used in Windows (Thunderbird, Vivaldi, Firefox, FreeCommander XE, PDF-XChange Editor...everything except certain Microsoft Office products that I won't mention here).  If all these programs can re-open with remembered size and position settings, why cant VSC?  It would make a big difference to how I work with VSC, whereas (as you allude to) not one of the new items of functionality that VSC has introduced in the last six months is anything I've found useful.

PLEASE, VSCode Developers, listen to your user base.  When you said (15 Jan 2020) that you'd put it in your backlog if it received 20 votes within 60 days, it got the required number of votes in less than half that time.  And then nine months later, you decided it wasn't worth your effort--in spite of the users asking for it.  Who do you prioritize, your users or yourself?

Sorry I'm so negative, it just seems like you're ignoring your users.

**Comment by vvolodin** [comment] 2022-07-30 14:33
Very disappointing that VS Code team ignores developers who work on multiple projects at the same time. Opening all windows each day takes considerable time, since only the first window I open seems to remember its previous size. All other windows require manual resizing every day. Every day I think about the people who decided this was a not an issue!

**Comment by mcswell** [comment] 2022-07-30 16:32
@vvolodin Agreed!!!  And I think also of all the things that have been done in the past couple years, few if any of which I found helpful--while this one, which would make a world of difference to me and to all the people that up-voted it, gets dropped for no good reason.

**Comment by mcswell** [comment] 2022-07-30 16:34
BTW, here's another one that is in need of up-votes: https://github.com/microsoft/vscode/issues/151857  (Disclaimer, I raised this issue; not sure how to encourage people to up-vote it, and maybe this is the wrong way to do it.  But every single editor I've ever used has this glob capability.  Except for VSC.)

**Comment by mark-hahn** [comment] 2022-07-30 17:13
I discovered a good solution for windows users.  Install powertoys and use the FancyZones. They are confusing at first but once you get the zones set up you can snap vscode windows to a zone and then later when you open a window it will go to it's zone.

**Comment by zikyfranky** [comment] 2023-06-18 09:25
5 years later, still nothing.
Just WOW!

**Comment by mcswell** [comment] 2023-06-18 13:02
@zikyfranky : agreed.  *Maybe* there have been tons of requests for the other things that have been added to VSC over the years, and this issue has few requests.  But somehow I doubt it.

**Comment by furopi** [comment] 2023-08-05 13:30
I'd love to see that feature... Is there no extension anywhere that does the same thing?

**Comment by Mivik** [comment] 2023-08-24 17:13
The only thing blocking me from completely switching from Sublime Text to VSC

**Comment by unikitty37** [comment] 2023-08-29 08:42
Nobody has ever answered an important question: why was this closed by a bot, with no reason given? At the very least, the reason for closing this should have been part of the closure message.

Don't send a bot to do a person's job.

**Comment by ThiefMaster** [comment] 2023-08-29 08:54
Come on, THAT's the best argument you have?  Right below the closure you find the reference to an issue where they explain this: https://github.com/microsoft/vscode/issues/110047#issuecomment-998997523

I also wish this issue wasn't closed, but I don't think nitpicking on "human vs bot closing it" is useful to anyone...

**Comment by unikitty37** [comment] 2023-08-29 13:26
Maybe point 3 means the ticket **needs to be all in bold text** 😁 

At the very least, the bot should say which of those rules is the one that applies here…

@ThiefMaster — I hadn't spotted the reference among all the other stuff, especially since I was focused on finding if there was a solution. Thanks for pointing that out!

As I'm using a Mac, I think I'll have to rig up some solution using Keyboard Maestro to save and restore window positions.

**Comment by furopi** [comment] 2023-09-05 15:15
**PLEASE REOPEN THÌS, DEAR BOT**
Is that bold enough?

**Comment by Jotunblood** [comment] 2023-09-27 14:33
Just stumbled upon this while researching this issue. 
I had luck with setting "Window: New Window Dimensions" to "inherit" and "Window: Restore Windows" to "preserve."
Hopefully that works for some people.

**Comment by mdesantis** [comment] 2026-04-24 15:24
Hello, 

Just to say that I can reproduce it on Ubuntu 26.04. VSCode just doesn't remember the previous position and spawns up where he likes to.
