### ISSUE TITLE
vscode account to save all settings and extensions

### ISSUE THREAD

**Issue by jmrodier** [Microsoft/vscode#26233] opened 2017-05-08 19:43 UTC
Feature Request: Would love to be able to create VS Code account to save all settings and extensions to. That way, we could just sign in on any machine where it is installed and all settings would be adjusted and extensions installed.

**Comment by amithegde** [comment] 2017-05-10 04:40
https://github.com/Microsoft/vscode/issues/24574

**Comment by yfdyh000** [comment] 2017-05-23 14:59
Duplicate of #7311, #25538.

**Comment by wangweixuan** [comment] 2017-05-27 23:46
Sync issue is also discussed in #7311 #9999 #10114 #18226 #22111 #24574 #25538 and a dozen closed ones.
@bpasero please close them if they are duplicates and track the issue at #2743 in the future.

**Comment by bpasero** [comment] 2017-06-03 07:37
https://github.com/Microsoft/vscode/issues/2743

**Closed by bpasero** 2017-06-03 07:37 UTC
Labels: feature-request, settings
