### ISSUE TITLE
Loss of the ability to collapse and uncollapse regions of code in javascript files

### ISSUE THREAD

**Issue by qdirks** [microsoft/vscode#114382] opened 2021-01-14 22:22 UTC
- VSCode Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
Step 1: create a file called "a.js" and paste in the following code:
```
/* a.js */
class a {
    // collapse/uncollapse me
}
a.prototype.a = 1;
```
Step 2: Keeping "a.js" open in a tab, create another file called "b.js" in the explorer panel. It opens automatically in another tab, automatically switching away from "a.js".
Step 3: Switch back to "a.js" tab. If the bug affects you, you have lost the ability to collapse/uncollapse the code in this tab.
Step 4: Regain the ability to collapse/uncollapse the code by typing anywhere in the file.
Step 5: Lose the ability again if you switch tabs and then switch back again.

Actual behavior:
Loss of the ability to collapse and uncollapse regions of code using the gui icon or keyboard shortcuts in the "a.js" file after switching tabs between "a.js" and "b.js". NOTE: The bug does not reveal itself when switching between "a.js" and the "welcome" tab. The bug is revealed when switching between "a.js" and "b.js".

Expected behavior:
The ability to collapse and uncollapse regions of code should be maintained when switching back to the "a.js" file.

Does this issue occur when all extensions are disabled?: Yes

System Information:

CPUs | AMD Ryzen 5 3600 6-Core Processor (12 x 3593)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.91GB (8.43GB free)
Process Argv | --disable-extensions . --crash-reporter-id 5b5f3c56-4a55-488e-8884-427be77ca91e
Screen Reader | no
VM | 0%

A/B experiment info:

vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30244300
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vstes627:30244334
pythonvspyt859:30241729

**Comment by yume-chan** [comment] 2021-01-15 02:23
Looks like duplicate of #112027

@mjbvz I couldn't repro this with the [JavaScript and TypeScript Nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), is this already been fixed?

**Comment by mjbvz** [comment] 2021-01-15 18:11
Thanks @yume-chan!

Yes this is a duplicate of https://github.com/microsoft/TypeScript/issues/35133

**Closed by mjbvz** 2021-01-15 18:11 UTC
