### ISSUE TITLE
Window freeze when receiving lots of output (extension host)

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6737] opened 2016-05-24 09:00 UTC
- VSCode Version: alpha
- OS Version: Windows 10 (Insider 14342)

Steps to Reproduce:

- New Workspace
- settings.json
```json
{
	"editor.formatOnType": true,
	"typescript.tsserver.trace": "verbose",
	"files.trimTrailingWhitespace": false,
	"editor.trimAutoWhitespace": false
}
```
- tsconfig.josn
```json
{
	"compilerOptions": {
		"module": "commonjs"
	}
}
```
- open output window
- test.js
```js
__foo;

<cursor>
```
- select TypeScript channel in output window
- open code assist
- select abstract
- type backspace very quickly. Don't hold the key down. You have to press it over and over again.

**Comment by bpasero** [comment] 2016-05-24 14:43
More insights:
* it does reproduce on Windows only for me
* it does reproduce in our shipped release already
* it seems to be related to the fact that we spam the output panel with lots of output (thousands) in short time

**Comment by bpasero** [comment] 2016-06-06 14:32
Moving to @isidorn for checking if our output spam protection kicks in. But I think it does.

**Comment by isidorn** [comment] 2016-07-25 14:46
@bpasero I can also repro it on win. I checked and the output spam protection kicks in, that is we will only append output to the channel every 300ms. However we will still execute [this code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputEditorInput.ts#L89) all the time. If I change that to be `this.bufferedOutput += 'a';` I can not get vscode to crash. 

I thought that creating all those 'large' string objects can cause vscode to freeze so I tried to be smarter in that code block to instead just of appending to strings just use an array but I still get a crash.

Also assigning to you for ideas.

**Comment by bpasero** [comment] 2016-08-05 14:54
@isidorn can you update the link, I think it is outdated now

**Comment by isidorn** [comment] 2016-08-08 20:38
@bpasero updated link

**Comment by bpasero** [comment] 2016-08-09 04:51
@isidorn that is weird, the code looks not like a performance issue to me, did you try with chrome profiling to see where it shows the bottle neck?

**Comment by bpasero** [comment] 2016-09-28 17:29
Let's continue in https://github.com/Microsoft/vscode/issues/12265

**Comment by bpasero** [comment] 2016-09-29 10:25
Ok, reopening this since this is about output from the extension host side. It might end up to be a duplicate in the end but maybe we need to also tweak the extension host side to buffer output.

**Comment by bpasero** [comment] 2016-09-29 10:55
I can not even profile when spamming output from the extension host, that's how much stuff happens between the 2 processes...

**Comment by jrieken** [comment] 2016-09-29 11:04
> I can not even profile when spamming output from the extension host, that's how much stuff happens between the 2 processes...

There is not much happening when you only send output for the output service. Before the incoming data results in a function call we parse the string to JSON using a custom reviver (for RegExp and URI). Looking at the previously taken perf-trace that account for 0.35% of the overall time being spend. 

<img width="691" alt="screen shot 2016-09-29 at 13 02 49" src="https://cloud.githubusercontent.com/assets/1794099/18951356/0f5db6f6-8645-11e6-8403-fcf9d8a389b9.png">

@bpasero I don't understand at what your are pointing here.

**Comment by bpasero** [comment] 2016-09-29 11:12
There is obviously something going wrong up to the point where the renderer becomes unresponsive and to proof that, notice the difference between running my extension sample with output printing enabled and disabled:

Enabled (after 3 seconds output is shown and you notice that my extension logging turns very slow and eventually everything is frozen):
![editors1](https://cloud.githubusercontent.com/assets/900690/18951556/1a46ec76-8646-11e6-8d6d-c935d964c5c8.gif)

Disabled: extension can happily send data over the wire
![editors](https://cloud.githubusercontent.com/assets/900690/18951557/1a49964c-8646-11e6-834e-e1df9a235f1e.gif)

So there is something going on as soon as the renderer is busy to process the messages received from the extension host, up to the point where everything is stuck.

Not pointing to anything, could as well be an issue with node.js, chrome or electron.

**Comment by jrieken** [comment] 2016-09-29 11:16
> Disabled: extension can happily send data over the wire

What does that mean? You send data but do anything with it? Can you profile the latter and latter?

**Comment by bpasero** [comment] 2016-09-29 11:19
@jrieken disabled means, the output gets sent over to the renderer and the renderer does some string magic with it but the output is never reaching the editor. Since in my profiling the majority of time is spend in the editor to render all the output, I do not end up in a freeze eventually.

**Comment by bpasero** [comment] 2016-09-29 11:21
Hm, just starting to profile makes it freeze for me too, even when not doing anything with the output. I believe profiling also puts quite some pressure on the renderer so maybe it causes a similar freeze as showing the output in the renderer.

**Comment by bpasero** [comment] 2016-09-29 11:26
Ok managed to get the profile, imho nothing obvious:

![image](https://cloud.githubusercontent.com/assets/900690/18951967/228b763e-8648-11e6-80e6-40db26634a5c.png)

On a related note: It seems saving profiles from Windows produce empty files :-((((

**Comment by jrieken** [comment] 2016-09-29 11:30
So, looking at the numbers: When I only receive the messages and stop forwarding them to the output service (comment line [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadOutputService.ts#L31)) `tickCallback` takes ~650ms, when I don't do that it takes ~5500ms. So, taking roughly half a second for reading 10000 messages isn't 🚀-fast but not the bottle neck here IMO. 

*only reading*
<img width="759" alt="screen shot 2016-09-29 at 13 27 50" src="https://cloud.githubusercontent.com/assets/1794099/18952115/ce5cf79e-8648-11e6-894d-17f6adbfc78c.png">

*reading & dispatching*
<img width="736" alt="screen shot 2016-09-29 at 13 28 11" src="https://cloud.githubusercontent.com/assets/1794099/18952119/d290a964-8648-11e6-9d49-193a779114cc.png">

**Comment by isidorn** [comment] 2016-09-29 14:17
This is not a regression -> moving to October
Also unassigning myself since this is to investigate on the extension host side

**Comment by jrieken** [comment] 2016-09-29 15:45
> Also unassigning myself since this is to investigate on the extension host side

There is not much to investigate on the extension host. An extension sends many messages which it can do via many paths: output, diagnostics, content provider events, calling API method, etc etc. 

closing as dup of #12265

**Comment by bpasero** [comment] 2016-09-30 05:25
I still want to continue looking into the total freeze of the entire application when data from the extension host travels to a busy renderer.

**Comment by bpasero** [comment] 2016-10-14 07:40
This seems to be https://github.com/Microsoft/vscode/issues/13667 and can possibly be improved by https://github.com/Microsoft/vscode/issues/13736

**Closed by bpasero** 2016-10-14 07:40 UTC
Labels: freeze-slow-crash, workbench
