### ISSUE TITLE
Pressing enter in the outline on a notebook doesn't navigate to the selected cell

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122595] opened 2021-04-28 23:08 UTC
- Open a notebook
- Open the outline
- Arrow down to some cell. As I navigate in the list, I get the yellow background color on the cell ✅ 
- Press enter
- I expect focus in the notebook list to move to that cell, but it stays where it was before i opened the outline

**Comment by jrieken** [comment] 2021-04-29 07:02
/duplicate of https://github.com/microsoft/vscode/issues/122480

**Closed** 2021-04-29 07:03 UTC
Labels: *duplicate, bug, notebook
