### ISSUE TITLE
Extension Host holds onto file locks causing builds to fail

### ISSUE THREAD

**Issue by moizgh** [Microsoft/vscode#68576] opened 2019-02-12 23:26 UTC
Issue Type: <b>Bug</b>

using the rush tool to build, Extension host keeps locks on files and rush build fails consistently.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1680 v4 @ 3.40GHz (16 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (55.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|9.5.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
git-tree-compare|let|1.5.0
code-spell-checker|str|1.6.10

</details>

**Comment by alexandrudima** [comment] 2019-02-13 07:28
@moizgh AFAIK, the extension host does not hold any locks by itself. Could you figure out which files are locked? (it would help us try to identify which extension holds locks)

**Comment by moizgh** [comment] 2019-02-13 15:24
This is an example of the issue we are hitting consistently.
``ERROR: EPERM: operation not permitted, lstat 'C:\Users\chrlo\office-shared-comments-ui\packages\canvas-simulator\node_modules'Often this is caused by a file lock from a process such as your text editor, command prompt, or "gulp serve"``

**Comment by alexandrudima** [comment] 2019-02-14 09:15
@moizgh When this happens, can you please use ProcessExplorer or similar software to identify the process id which is holding on to the file?

Once you have identified the process id, can you please include here the command line arguments for it (so we can find out which one of our processes it is)?

**Comment by moizgh** [comment] 2019-02-14 21:31
[cid:image001.jpg@01D4C482.A6E560F0]

**Comment by falsandtru** [comment] 2019-02-15 00:50
I've seen a similar problem since 1.29.x or 1.30.x.

```
Error: EPERM: operation not permitted, stat ...
```

This error is caused by even another standalone terminal when vscode launched by `code --disable-extensions` is running . And this will be resolved by closing vscode. So vscode has almost definitely affected permissions. I'm unable to reproduce this problem on ubuntu so probably this problem can be seen only on windows.

**Comment by falsandtru** [comment] 2019-02-15 01:00
Repro:

1. clone https://github.com/falsandtru/spica on Windows 10
1. run `npm i`
1. launch vscode
1. run `gulp dist`; this will be succeeded.
1. run `gulp dist` again; this will be failed by a permission error.
1. shutdown vscode
1. run `gulp dist`; this will be succeeded.

**Comment by alexandrudima** [comment] 2019-02-15 09:17
@moizgh Can you please use the github UI at https://github.com/Microsoft/vscode/issues/68576 . All your email messages look funny and attachments are not making it through.

---

@falsandtru Can you please use ProcessExplorer or similar software to identify the process id which is holding on to the file?

e.g. https://social.technet.microsoft.com/Forums/windowsserver/en-US/504017c7-1a92-415e-b12c-03d44145e1db/how-to-find-which-process-locked-the-log-file

Once you have identified the process id, can you please include here the command line arguments for it (so we can find out which one of our processes it is)?

**Comment by falsandtru** [comment] 2019-02-15 09:35
@alexandrudima I confirmed Code.exe is the only holder of the directory handler using ProcessExplorer. But I don't know what the command line arguments means.

**Comment by falsandtru** [comment] 2019-02-15 10:17
@alexandrudima Ah probably you mean this, right?

```
 ...\spica\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName ...\AppData\Local\Temp\vscode-typescript\tscancellation-98807ed02d080a987f69.tmp* --locale en --noGetErrOnBackgroundUpdate
```

**Comment by moizgh** [comment] 2019-02-15 12:02
![vscode bug-edit](https://user-images.githubusercontent.com/25937675/52855504-995f7e00-30ef-11e9-8fd1-812eaad6e306.jpg)

**Comment by alexandrudima** [comment] 2019-02-18 16:06
Thank you for following through, from the command line arguments, that looks to be the TypeScript server process that is locking up those files/folders.

**Comment by mjbvz** [comment] 2019-02-19 19:10
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/29856 and similar to https://github.com/Microsoft/TypeScript/issues/29407

**Closed by mjbvz** 2019-02-19 19:10 UTC
Labels: needs more info, typescript
