### ISSUE TITLE
Reduce number of tab stops for project-wide find widget

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#132828] opened 2021-09-10 03:46 UTC
/CC @isidorn 

Issue Type: <b>Bug</b>

When using the keyboard to navigate from the project-wide find widget (ctrl+shift+f) from the edit field to the tree view of search results, it takes 9 tab stops to do so. This is really painful for efficiency reasons, and gets worse the more controls are added.

VS Code version: Code - Insiders 1.61.0-insider (df115e761ae11cf87ca569ca1824b7257099553a, 2021-09-08T17:51:26.439Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.23GB (14.62GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/dickson/source/api-profile --remote=wsl+Ubuntu --crash-reporter-id 1304d64e-abdb-456c-beb6-72c33120f731|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1696)|
|Memory (System)|24.45GB (16.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1696)|
|Memory (System)|24.45GB (16.31GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-eslint|dba|2.1.25
dendron|den|0.58.1
dendron-markdown-links|den|0.6.20
dendron-markdown-preview-enhanced|den|0.10.57
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
dendron-snippet-maker|den|0.1.6
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
copilot|Git|1.4.2635

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30361752
pydsgst2:30361790

```

</details>

**Comment by ArturoDent** [comment] 2021-09-10 21:25
`Search: Focus List` which is unbound and then <kbd>downArrow</kbd> focuses the first search result.  Make it into a macro.

Also <kbd>Ctrl</kbd>+<kbd>downArrow</kbd> moves a little faster than tabbing.

**Comment by isidorn** [comment] 2021-09-15 14:28
@neurrone good points, however this is a duplicate of https://github.com/microsoft/vscode/issues/116450

Maybe we should add it to the plan in the future, or would be a good chance for someone to get introduced to the Find Widget. @rebornix what do you think?

**Closed by isidorn** 2021-09-15 14:28 UTC
