### ISSUE TITLE
TS Server fatal error:  Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by getalex** [microsoft/vscode#96739] opened 2020-04-30 22:08 UTC
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. browse through common js libraries
2. vscode reports typescript error even though js is not typescript file

**TS Server Error Stack**
```
TypeError: Cannot read property 'enable' of undefined
    at convertTypeAcquisition (tsserver.js:142208:37)
    at ProjectService.sendProjectTelemetry (tsserver.js:142189:38)
    at ConfiguredProject.updateGraph (tsserver.js:140657:37)
    at updateProjectIfDirty (tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143114:29)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-05-01 01:03
Duplicate of https://github.com/microsoft/TypeScript/issues/36834

**Closed by mjbvz** 2020-05-01 01:03 UTC
