### ISSUE TITLE
css3 has selector bug in html edit

### ISSUE THREAD

**Issue by nczsl** [microsoft/vscode#159934] opened 2022-09-02 17:20 UTC
example:
If you write code in an HTML file
```
.sidebar li:has（>label>input[type='checkbox']：checked）>ul{
display:none;
}
```
A red line error will be received, and the position starting from the bracket in the above code points to the > sign[](url)
![223](https://user-images.githubusercontent.com/5241693/188205765-b1a04d7f-fe1c-4388-8d43-e9535d13337c.jpg)

**Comment by aeschli** [comment] 2022-09-05 10:02
duplicate of https://github.com/microsoft/vscode/issues/147353

**Closed by aeschli** 2022-09-05 10:02 UTC
