### ISSUE TITLE
Add "Create new file" keyboard shortcut when the Explorer sidebar is active

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#94598] opened 2020-04-07 11:07 UTC
I'd love it if we could add this keybinding to the default VS Code configurations.
```
	// Cmd+n will create a new file in the explorer when the explorer sidebar is focused
	{
		"key": "cmd+n",
		"command": "explorer.newFile",
		"when": "explorerViewletFocus"
	}
```

This would allow us to Cmd+0 to focus the explorer window, navigate the folders and Cmd+n to create a new file without opening a separate dialog. It's a much more streamlined experience.

**Comment by ArturoDent** [comment] 2020-04-07 20:06
Your suggested keybinding works quite well.  It isn't clear what the issue is (other than having it built-in rather than a user-supplied keybinding.

**Comment by andrecasal** [comment] 2020-04-07 20:38
That's exactly my request Arturo: to add this keybinding to the defaults.

**Comment by isidorn** [comment] 2020-04-08 07:50
We will not add this keybinding to be built in, since that would break a flow that a lot of users are used to
Focus in the explorer, press cmd+n I get a new untitiled editor and focus is in it

For people who want to change that flow can use the keybinding which you propose, however we will not change the deafult expereince thus closing this. Thansk!

**Comment by andrecasal** [comment] 2020-04-08 11:07
Hey @isidorn, thanks for the reply. As I understand it cmd+n's behaviour happens regardless of the explorer sidebar being focused or not.

To put this in perspective, as is now:

1. `Cmd+n` to create new empty editor window
2. `Cmd+s` to open the operating system's save dialog, which by default is the last place we've saved a file to. Besides being a context switch (we're now outside of VS Code), this could also be outside and far from the repository we're working on. This is the step I have a problem with. The folder I want to save a file to is **right there** on the sidebar. Why do I have to go all the way to the operating system's save dialog and renavigate back to my repository from outside VS Code to save a file there?
3. Navigate to the folder to which we'd like to save the file.
4. Write file name
5. Enter to save the file
6. Optionally `Cmd+w` to close the empty editor window

With the proposed change:

1. `Cmd+0` to focus the explorer sidebar
2. `Arrow keys` to navigate to the repository folder you'd like to save the file to
3. `Cmd+n` to create a new file in the folder we're on
4. Write file name
5. Enter to save the file

I would expect that, if I have the explorer focused, the file be created on the folder I am selecting.

I understand you don't want to change the default behaviour, but please reconsider this change as this seems like a much better default than the one that's currently implemented.

Cheers!

**Comment by isidorn** [comment] 2020-04-08 11:10
I can reopen and leave this as a feature request so we gather more feedback.
However no plans to tackle for now.
Thanks

**Comment by andrecasal** [comment] 2020-04-08 11:13
Thanks, I appreciate it 👍

**Closed** 2020-06-29 13:59 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by User7711** [comment] 2021-07-09 07:16
This seems like a minor request. Why not just give it to us? There is a decent mouse option for this, so why not also a descent keyboard option? Using the mouse in a code editor is less immersive and/so the keyboard should always be the superior device!
