### ISSUE TITLE
VSCode won't launch

### ISSUE THREAD

**Issue by gustavoaca1997** [Microsoft/vscode#66872] opened 2019-01-21 23:01 UTC
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.04.1

Steps to Reproduce:

1. Try to launch VSCode

Does this issue occur when all extensions are disabled?: No.

#### Output of `code --verbose`:

```bash
[5462:0121/190014.573028:WARNING:browser_main_loop.cc(275)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
[5462:0121/190014.853060:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/entry.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[5462:0121/190014.854101:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[5462:0121/190014.854846:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button-toolbar.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[5462:0121/190014.857981:ERROR:gconf_listener.cc(116)] Error with gconf key '/apps/metacity/general': Failed to activate configuration server: The name org.gnome.GConf was not provided by any .service files
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[5496:0121/190015.055552:ERROR:gl_context_glx.cc(186)] Failed to create GL context with glXCreateContextAttribsARB.
[5496:0121/190015.055631:ERROR:gpu_info_collector.cc(51)] gl::init::CreateGLContext failed
[5496:0121/190015.055639:ERROR:gpu_info_collector.cc(119)] Could not create context for info collection.
[5496:0121/190015.055660:ERROR:gpu_init.cc(96)] gpu::CollectGraphicsInfo failed (fatal).
[5496:0121/190015.057188:ERROR:gpu_child_thread.cc(252)] Exiting GPU process due to errors during initialization
[5462:0121/190015.062206:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[90m[main 7:00:15 PM][0m Starting VS Code
[90m[main 7:00:15 PM][0m from: /snap/vscode/74/usr/share/code/resources/app
[90m[main 7:00:15 PM][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[90m[main 7:00:15 PM][0m Resolving machine identifier...
[90m[main 7:00:15 PM][0m Resolved machine identifier: 5b0a388a3c3c85c93ca4e831f7fba28a48531e33702d5b4f875f20c594a15eaf
[90m[main 7:00:15 PM][0m [storage :memory:] open()
[91m[main 7:00:15 PM][0m [uncaught exception in main]: Failed to watch /home/gus/.config/Code/User for changes (Error: watch /home/gus/.config/Code/User ENOSPC)
[90m[main 7:00:15 PM][0m telemetry/optInStatus { optIn: true }
[90m[main 7:00:15 PM][0m [storage :memory:] Trace (event): PRAGMA user_version = 1;
[90m[main 7:00:15 PM][0m [storage :memory:] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[90m[main 7:00:15 PM][0m [storage :memory:] getItems(): Map(0) {}
[90m[main 7:00:15 PM][0m update#setState idle
[91m[main 7:00:15 PM][0m Error: watch /snap/vscode ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (original-fs.js:1386:19)
    at Object.fs.watch (original-fs.js:1412:11)
    at t [as constructor] (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:349:333)
    at t.create (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:68:770)
    at t.e._createInstance (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:234:215)
    at t.e._createServiceInstance (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:236:234)
    at t._createServiceInstance (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:237:862)
    at t.e._createServiceInstanceWithOwner (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:235:982)
    at t.e._createAndCacheServiceInstance (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:235:652)
    at t.e._getOrCreateServiceInstance (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:234:795)
    at Object.get (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:233:112)
    at Ee.openFirstWindow (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:539:458)
    at /snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:535:808
    at t.e.invokeFunction (/snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:233:247)
    at /snap/vscode/74/usr/share/code/resources/app/out/vs/code/electron-main/main.js:535:772
    at <anonymous>
[90m[main 7:00:15 PM][0m Lifecycle#kill()
[90m[main 7:00:15 PM][0m [storage :memory:] Trace (event): SELECT * FROM ItemTable
```

**Comment by sandy081** [comment] 2019-01-22 09:09
Duplicate of #65879

**Closed by sandy081** 2019-01-22 09:09 UTC
