### ISSUE TITLE
Alt/Cmd+Click to see all header references?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148185] opened 2022-04-26 17:26 UTC
Testing #147731

In TS files I can Alt+Click on a declaration token and see a peek view of all references to that token. It would be nice to do the same in MD. (I use "editor.multiCursorModifier": "ctrlCmd", so alt does Go to Definition)

this also needs: 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/8586769/165357864-2c027212-4186-4869-a414-4d9018faeb22.png">

**Comment by mjbvz** [comment] 2022-04-30 21:20
I believe this is a duplicate of #146293 as we currently do not implement `go to definition` for markdown

**Closed by mjbvz** 2022-04-30 21:20 UTC
