### ISSUE TITLE
Git file is outside of repository when using 'stage change' button

### ISSUE THREAD

**Issue by alexsijm** [microsoft/vscode#100391] opened 2020-06-17 14:01 UTC
Issue Type: <b>Bug</b>

Since last friday whenever I use the + button to 'stage change' I get the following exception:

Git fatal: d:\(....): 'd:\(...)' is outside repository. 

If I use 'Git add (...)'  I can stage the same changes without any problem.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.0
sonarlint-vscode|Son|1.16.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-06-17 15:02
/duplicate of #99881 and others (search for 'outside repository')

People have reported resolving this by updating their local Git.

**Closed** 2020-06-17 15:03 UTC
Labels: *duplicate
