### ISSUE TITLE
IntelliSense to find matches in all open files including word suggestions

### ISSUE THREAD

**Issue by Vernando05** [Microsoft/vscode#12115] opened 2016-09-16 04:04 UTC
Feature Request:
Any vscode settings or extension that support  autocomplete to find matches in all open files?
like sublime one: https://github.com/alienhard/SublimeAllAutocomplete

**Comment by bpasero** [comment] 2016-09-16 14:07
@Vernando05 the symbol search in VS Code is accessible via Ctrl+T (or Cmd+T on Mac).

**Comment by Vernando05** [comment] 2016-09-21 05:17
Symbol search is just for specific context/code, it's nice to have a code completion based on word that exist across files, in my case re-typing font-family value again and again is little bit annoying.

**Comment by bpasero** [comment] 2016-09-21 05:52
Ah ok now I understand.

**Comment by abenhamdine** [comment] 2017-02-07 08:57
Users of SublimeText know that this feature is a killer-one.
It's not a 'smart' autocompletion : just a completion with allow words existing in all open files, but it turns out to be deadly efficient.
It's the thing I miss the most in VSCode comparing with ST.

**Comment by mrmlnc** [comment] 2017-02-07 09:11
Well, previously I created [vscode-less](https://github.com/mrmlnc/vscode-less) and [vscode-scss](https://github.com/mrmlnc/vscode-scss) to give users more autocomplete «Symbols» from all project files.

If you want this feature – I can create this plugin. This is very simple, but you want suggestions from all **open files** or from **all project files**?

**Comment by therealmarv** [comment] 2017-02-07 09:24
@mrmlnc wow that's nice! 😮

I suggest feature comparison with https://github.com/alienhard/SublimeAllAutocomplete which is 
the plugin. It's auto complete from all open files.

Would be nice to elaborate if auto complete from all project files is a) running fast enough to not slow down VSCode too much (or too much CPU?) b) if it is useful or too much (don't know, never had that feature in my editors) and c) make it maybe as option if you can? 😄

But auto complete on all open files would be first step 👍

**Comment by NKjoep** [comment] 2017-02-07 09:31
I agree, autocomplete on all open files it is more than enough. I think can be confusing to have suggestions from all the files in the project :)

Usually when working on a feature I keep those 5/6 files open so autocompleting words from those would be very helpful. 

And, as already said, It will be very helpful specially for css/html classes or other words in pseudo-code (templates, data files etcetc)

**Comment by abenhamdine** [comment] 2017-02-07 09:52
Agree with @NKjoep.
It's much better to complete with words in open files (as SublimeAllAutocomplete does), not with all project files, because it lets the user to decide the scope of autocompletion.

For exemple, with Sublime, I used to open a file with the model database definition, and an other one where I write my queries. So I can benefit from completion of db fields.

**Comment by bacalazin** [comment] 2017-03-15 14:52
+1
I'm trying VsCode coming from sublime.. It's really a blocker for me. I'm really used to https://github.com/alienhard/SublimeAllAutocomplete

**Comment by fish47** [comment] 2017-05-03 02:01
+1
This is a useful feature for those languages that lack auto-completion support, for example Lua.

**Comment by shahidmau** [comment] 2017-05-16 11:49
+1
I shifted from sublime to vscode, I am really missing this feature.
https://github.com/alienhard/SublimeAllAutocomplete

It should suggest all keywords from open files (but not from whole project)

**Comment by atishay** [comment] 2017-05-17 15:45
I just created: https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete.
Can you all please try this out and leave feedback.

**Comment by billychan** [comment] 2017-05-21 06:08
@atishay The plugin looks fantastic! For me it's just what I want. Thanks much!

**Comment by wangweixuan** [comment] 2017-05-29 10:47
Maybe a duplicate of #5312?

**Comment by ivanbanov** [comment] 2017-08-16 21:16
@atishay Thanks dude

**Comment by cntech** [comment] 2017-09-21 18:08
+1
Recently I switched from Atom to VSCode and it is one of 2 things I miss in VSCode.

**Comment by hemedani** [comment] 2017-09-22 11:14
in Atom autocomplete also support in string but vscode do not supported.
for Example :
```javascript
User.save()
   .then((userSaved) => {
        console.log('userSaved from userAuthentication', userSaved);
    })
```
atom suggest `userSaved` in both two places in log command but vscode only suggested after comma

**Comment by dorian-marchal** [comment] 2018-06-14 15:28
Any news, on this ?

**Comment by safield** [comment] 2018-10-05 14:49
+1 from me. I really miss this feature. It is the last blocker for me to pull the trigger on VSCode! Please!

I have tried the plugin All AutoComplete for VScode, and it is just straight up broken...

**Comment by paukul** [comment] 2018-10-08 14:45
👍

**Closed** 2019-05-01 22:51 UTC
Labels: *extension-candidate, feature-request
