### ISSUE TITLE
Window crash when using built-in view in custom views container

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#72453] opened 2019-04-17 00:31 UTC
Version: 1.33.1 (system setup)
OS: Windows_NT x64 10.0.17763

Referencing a built-in view such as `"outline"` in a custom view container of an extension causes a hard window crash when that view container is opened:

![](https://i.imgur.com/MMfTyi5.gif)

This originally came up in [this StackOverflow question](https://stackoverflow.com/questions/55716615/created-my-own-viewscontainer-can-i-include-views-from-other-viewscontainers/) where somebody was trying to use built-in views in custom containers (which might actually be a valid use case?).

____

To reproduce, create an extension with this in `package.json`:

```lang-json
"contributes": {
	"viewsContainers": {
		"activitybar": [
			{
				"id": "custom-activity",
				"title": "My Uber-activity",
				"icon": "resources/custom-activity.svg"
			}
		]
	},
	"views": {
		"custom-activity": [
			{
				"id": "outline",
				"name": "outline"
			}
		]
	}
}
```

**Comment by mike-lischke** [comment] 2019-04-17 07:26
I have an own view container for my file type and would like to embed the references outline there. So I'm interested in getting this solved.

**Comment by jrieken** [comment] 2019-04-17 07:34
> references outline 

Does that mean the references viewlet or the outline view? Anyways, I don't think that is supported by the container world

**Comment by bfitzpat** [comment] 2019-04-17 12:31
There doesn't seem to be a "views" declaration for the standard VS Code views (outline, resources, etc.), so that may be an issue for some of the core views in the Explorer activity. 

But even beyond that  I'm wondering if we can bring in views from other extensions if we know the ID? For example, the spring-boot-dashboard contributes the "spring-boot-dashboard" view -- can we reference that if it exists in the VS Code environment?

`        "views": {
            "explorer": [
                {
                    "id": "spring-boot-dashboard",
                    "name": "Spring-Boot Dashboard"
                }
            ]
},`

**Comment by sandy081** [comment] 2019-04-25 09:07
First I would like to investigate why there is a crash and fix it. Re supporting built in views in custom view containers, we do not support it.

**Comment by bfitzpat** [comment] 2019-04-25 12:50
> 
> 
> First I would like to investigate why there is a crash and fix it. Re supporting built in views in custom view containers, we do not support it.

Does that imply that supporting pulling in custom views may be supported then?

**Comment by sandy081** [comment] 2019-04-30 14:10
No.

**Comment by alexr00** [comment] 2019-10-07 13:03
Closing since I cannot reproduce the crash.

**Closed by alexr00** 2019-10-07 13:03 UTC
Labels: bug, explorer-custom, freeze-slow-crash
