### ISSUE TITLE
Sense the element change and respond with closing tag and viceversa

### ISSUE THREAD

**Issue by Georgekg** [Microsoft/vscode#27142] opened 2017-05-23 15:33 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Change the opening element tag to a different tag.
2. Wait to change the closing tag automatically.
3. Nothing happens.
4. Change the closing tag manually.
5. eg:-
`<div>Visual Studio Code</div>

 <p>Visual Studio Code</div>`

**Comment by aeschli** [comment] 2017-05-23 19:02
duplicate of #11153

**Closed** 2017-10-03 13:46 UTC
Labels: feature-request
