### ISSUE TITLE
Search: searching also in deleted files

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#50361] opened 2018-05-23 18:01 UTC
VSC: v1.23.0

Sometimes it happens that if you delete a file, and then perform a search query for which that file would be a match, that deleted file would show up in the search results.

Some issues with this:

- Obvious annoyance
- When performing a search & replace deleted files could actually get resurrected
- My trash bin is empty, and on the titlebar I see something something like `~/non/existent/path.ts (deleted from disk)`, where the hell does this file come from? There might be security implications in duplicating files somewhere else too

**Comment by fabiospampinato** [comment] 2018-05-23 21:59
I'm also seeing errors about this deleted file in the "Problems" pane.

**Comment by roblourens** [comment] 2018-05-23 23:20
The only way I think this would happen, is if you have unsaved changes in a file, and delete it from outside vscode (like from a terminal). In that case, the file stays open in the editor, and all open editors are searched. Could that be happening here?

In any other case, if you don't have changes in a file or delete it from inside vscode, the editor should be closed automatically.

**Comment by hvdklauw** [comment] 2018-05-24 06:41
I just ran into the same problem; steps to reproduce:

- Have a git project open in the editor.
- Use `git mv` to move a whole folder somewhere else in your code path.
- Use search to find something that is in one of the moved files.
- See the result show up twice in the result list (The old location and the new one).


P.S. I have NO open tabs in my editor.

**Comment by hvdklauw** [comment] 2018-05-24 07:01
hmm restarting VSC seems to have fixed it for now.

**Comment by fabiospampinato** [comment] 2018-05-24 10:39
@roblourens Unfortunately I don't have repro steps for you.

> The only way I think this would happen, is if you have unsaved changes in a file, and delete it from outside vscode (like from a terminal). In that case, the file stays open in the editor, and all open editors are searched. Could that be happening here?

I don't remember if I had that file opened in a tab when I deleted it, but later even with 0 files open it kept popping up in the search results.

**Comment by roblourens** [comment] 2018-05-24 17:29
I can't repro that @hvdklauw. Both of you, which OS?

Even if the file wasn't open in a tab when you did the search, did you see duplicates in a file that **had** previously been open in a tab?

I guess there are two things that could cause this:

- The file was really still on disk and was returned from the disk search
- The file still had an editor model because it had been open, and the model wasn't cleaned up somehow. @sandy081 do you know how that would be possible?

**Comment by fabiospampinato** [comment] 2018-05-24 17:35
> Both of you, which OS?

macOS v10.13.

> Even if the file wasn't open in a tab when you did the search, did you see duplicates in a file that had previously been open in a tab?

Yes, I think I opened the deleted file at least once before deleting it.

> The file was really still on disk and was returned from the disk search

It wasn't.

**Comment by hvdklauw** [comment] 2018-05-24 18:45
Same here, not currently open in a tab, file no longer on disc (and because it was python I also checked it's cache).

Did close and open the laptop a couple of times since starting it up, and did some reloads when a plugin updated too.

Could it be a plugin? Maybe gitlens?

**Comment by sandy081** [comment] 2018-05-25 12:54
@roblourens The file still had an editor model because it had been open, and the model wasn't cleaned up somehow. @sandy081 do you know how that would be possible?

When a file is open in the editor and is deleted in the disk, we still show the file in the editor by updating the title with deleted label.

![image](https://user-images.githubusercontent.com/10746682/40545268-8d42edf4-602b-11e8-9a65-ed2ca451c12a.png)

**Comment by roblourens** [comment] 2018-05-25 15:39
Yeah but at the time they did the search, they say they had no tabs open.

**Comment by roblourens** [comment] 2018-05-25 15:56
It is true that if you do a search/replace with a "deleted from disk" file open, it restores the file. We can fix that at least.

**Comment by hvdklauw** [comment] 2018-05-25 18:05
I had it again this morning, all I did inbetween yesterday (where it didn't happen after a restart) and today was close my laptop last night and open it again this morning with vscode open.

Moved some more code (`git mv` in the terminal) and then did a search and replace for the imports that needed to change, and presto, one of the moved files showed up in the search and replace both in it's old and it's new location without having any tabs open.

**Comment by hvdklauw** [comment] 2018-05-25 18:31
> Anything special about that one file that showed results? Were you editing it before moving it?
I might have edited it yesterday, but those changed where commited.
> Was the file open when you moved it, and then you closed it before searching, or was it closed when you moved it?
It was closed when moving it and when search/replacing

I'm as baffled as you are :)

**Comment by waynebloss** [comment] 2018-07-23 15:42
I am getting this problem on Windows 10 Pro v1803 with VSCode 1.25.1 (x64).

I duplicated an existing file, renamed the duplicate, then deleted it. Then I did a search and results from the deleted file where showing up.

**Comment by roblourens** [comment] 2018-07-23 15:55
Did you delete it through vscode or externally?

Did you click the results in the deleted file? If so what happened?

**Comment by waynebloss** [comment] 2018-07-23 16:22
I deleted the file through VSCode.

I clicked the result and the file opened with a tab title containing "deleted from disk".

**Comment by roblourens** [comment] 2018-07-23 16:47
And the deleted file isn't open in a tab when you do this right?

**Comment by waynebloss** [comment] 2018-07-24 03:36
That is correct. I am able to reproduce this on a work machine and a home machine.

However, it just occurred to me to mention that I am also asking VSCode to use `typescript@next` via the `typescript.tsdk` setting, in order to solve a different issue with JSDoc types.

**Comment by waynebloss** [comment] 2018-07-24 03:38
The version of typescript I'm on is `3.0.0-dev.20180712`

**Comment by waynebloss** [comment] 2018-07-24 03:43
OK, just tested again removing the `typescript.tsdk` setting (commenting it out) and the issue still presents itself.

If you tell me some diagnostics you want me to run, please let me know. Thanks.

**Comment by roblourens** [comment] 2018-09-13 19:55
Is this still an issue? I haven't seen it and don't know anything new.

I wonder if it's possible for an extension to keep a model alive for a file after it's deleted.

**Comment by hvdklauw** [comment] 2018-09-14 06:32
I haven't encountered the issue again, but then I haven't been doing a lot of moving/search and replace work either the last few weeks.

I'd say close the issue and let's reopen it if it happens again.

**Closed** 2018-09-14 15:45 UTC
Labels: bug, search
