### ISSUE TITLE
Buttons for vscode

### ISSUE THREAD

**Issue by laoshaw** [Microsoft/vscode#40404] opened 2017-12-18 02:24 UTC
can vscode support quick-buttons? like most of other editors, that I can click on a button and it will do something(e.g. save, open, wrap text with a pair of tags in html,etc). so far I only see a "split window" button.

many of us actually spend more time reviewing code instead of writing, those button can work with mouse without the need of reaching keyboard. Besides, most  editors support the quick action buttons long time ago.

thanks for the consideration.

**Comment by laoshaw** [comment] 2017-12-18 02:25
even the little github edit window has all those great buttons, please support them in vscode, and make them customizable too.

**Comment by xianghongai** [comment] 2017-12-18 02:54
![2017-12-18_10-43-23](https://user-images.githubusercontent.com/2075006/34087779-4fe692e8-e3e0-11e7-9c93-fdc3d079af13.png)

no! 

when coding, 80% ++ keyboard, 20% -- mouse !

1920*1080+ resolution, the cursor in the (x offset:1000, y offset:800)+ coordinates, first of all, to find out which button icon, and then use the mouse to move to the coordinates of (x offset:100, y offset:80), so a waste of time, if using shortcuts, less than 1 second.

This is a modern compiler, not an old antiques.

**Comment by laoshaw** [comment] 2017-12-18 03:00
they're not mutual exclusive, not everyone code all the time, studying /reviewing code also occupies lots of time where keyboard is rarely needed and mouse click helps, again, they shall co-exist just fine, you do not need pick just one. In fact, nearly all other editors did that long time ago and keep doing that now, there must be a good reason.

yes i use keymap too, but also miss those buttons when reviewing code.

**Comment by bpasero** [comment] 2017-12-18 05:40
Marking as /duplicate of https://github.com/Microsoft/vscode/issues/9378

**Closed** 2017-12-18 05:40 UTC
Labels: workbench, workbench-tabs
