### ISSUE TITLE
Ligatures stopped working

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#87276] opened 2019-12-18 20:11 UTC
Issue Type: <b>Bug</b>

Up until today's insider, ligatures (e.g. "=>") worked perfectly in Fira Code, Cascadia Code, and other fonts with ligatures.  Today, none of them work.

Ligatures work for the same fonts in other ligature-aware apps.

VS Code version: Code - Insiders 1.42.0-insider (26f5dfcd76c9a02f116a706844611aeb09ae8c0b, 2019-12-18T10:32:01.697Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
ng-template|Ang|0.900.2
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.6
es7-react-js-snippets|dsz|2.4.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.16.1
svg|joc|1.0.6
vscode-phpfmt|kok|1.0.30
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
vscode-scss|mrm|0.8.1
angular2-inline|nat|0.0.17
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.1
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|9.6.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.6.1

(4 theme extensions excluded)

</details>

**Comment by smlombardi** [comment] 2019-12-18 20:35
Despite what vscodebot says, this is _not_ about the integrated terminal, but the editor.

**Comment by smlombardi** [comment] 2019-12-19 00:02
I had to remove the contextual alternates from each language:
`"editor.fontLigatures": "'ss01', 'ss05', 'ss20'"`

Then the default ligatures (like arrow functions) started working again

**Comment by alexdima** [comment] 2020-01-16 07:47
@smlombardi When using the string format (the expert format), then all desired font features must be turned on manually, including `calt` for ligatures in general:

e.g. `"editor.fontLigatures":"'ss01', 'ss05', 'ss20', 'calt'",`

**Comment by alexdima** [comment] 2020-01-16 07:47
Duplicate of #85457

**Closed by alexdima** 2020-01-16 07:47 UTC
