### ISSUE TITLE
Can't format HTML code

### ISSUE THREAD

**Issue by edotassi** [Microsoft/vscode#1333] opened 2015-12-15 13:57 UTC
VsCode 0.10.4

When I click on "Format Code" in the context menu, i get the following error:

```
Main Thread sent to worker the following message:e._onError @ workbench.main.js:16e._onmessage @ workbench.main.js:16e._onSerializedMessage @ workbench.main.js:16(anonymous function) @ workbench.main.js:16worker.onmessage @ workbench.main.js:19
workbench.main.js:16 Object {type: "threadService", payload: Array[3]}payload: Array[3]type: "threadService"__proto__: Object
workbench.main.js:16 And the worker replied with an error:e._onError @ workbench.main.js:16e._onmessage @ workbench.main.js:16e._onSerializedMessage @ workbench.main.js:16(anonymous function) @ workbench.main.js:16worker.onmessage @ workbench.main.js:19
workbench.main.js:16 Object {stack: "TypeError: Cannot read property 'startLineNumber' …tor/common/worker/editorWorkerServer.js:14:31951)", message: "TypeError: Cannot read property 'startLineNumber' of null"}message: "TypeError: Cannot read property 'startLineNumber' of null"stack: "TypeError: Cannot read property 'startLineNumber' of null↵    at Function.e.startPosition (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:4:24655)↵    at n.format (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/htmlWorker.js:8:13906)↵    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10265↵    at t.Class.define.then (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/base/common/worker/workerServer.js:4:25244)↵    at e.t._worker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:16843)↵    at e.formatDocument (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10236)↵    at t.OneWorker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:15:490)↵    at e.(anonymous function) [as formatDocument] (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:12479)↵    at t._handleRequest (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31878)↵    at t.dispatch (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31951)"__proto__: Object
workbench.main.js:90 TypeError: Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at Function.e.startPosition (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:4:24655)
    at n.format (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/htmlWorker.js:8:13906)
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10265
    at t.Class.define.then (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/base/common/worker/workerServer.js:4:25244)
    at e.t._worker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:16843)
    at e.formatDocument (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10236)
    at t.OneWorker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:15:490)
    at e.(anonymous function) [as formatDocument] (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:12479)
    at t._handleRequest (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31878)
    at t.dispatch (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31951)e.onUnexpectedError @ workbench.main.js:90(anonymous function) @ workbench.main.js:90e.onUnexpectedError @ workbench.main.js:10u @ workbench.main.js:9e._onmessage @ workbench.main.js:16e._onSerializedMessage @ workbench.main.js:16(anonymous function) @ workbench.main.js:16worker.onmessage @ workbench.main.js:19
workbench.main.js:63 TypeError: Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at Function.e.startPosition (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:4:24655)
    at n.format (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/htmlWorker.js:8:13906)
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10265
    at t.Class.define.then (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/base/common/worker/workerServer.js:4:25244)
    at e.t._worker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:16843)
    at e.formatDocument (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/languages/html/common/html.js:4:10236)
    at t.OneWorker (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:15:490)
    at e.(anonymous function) [as formatDocument] (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:13:12479)
    at t._handleRequest (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31878)
    at t.dispatch (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/worker/editorWorkerServer.js:14:31951)
```

**Comment by jrieken** [comment] 2015-12-15 14:24
Got fixed today for 0.10.5. Duplicate of #1321

**Closed by jrieken** 2015-12-15 14:24 UTC
Labels: bug
