### ISSUE TITLE
Add some margins around the notification toolbar to separate better from message

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50937] opened 2018-06-01 10:35 UTC
- run code with `code-insiders --locale=pt-br`
dialog shows

![image](https://user-images.githubusercontent.com/6461412/40836708-02740826-6598-11e8-9a79-09d8fb877b99.png)

To me it looks like the gear image is part of the text. Some margins would be good.

**Comment by bpasero** [comment] 2018-06-01 12:08
That very much depends on the wrapping, e.g. looks fine in this case:

![image](https://user-images.githubusercontent.com/900690/40840033-486baae8-65a5-11e8-963e-124f01acd752.png)

**Comment by octref** [comment] 2018-06-04 04:37
@bpasero Does this need ux discussion or should I assign this to you?

**Comment by ramya-rao-a** [comment] 2018-06-13 20:39
This gets worse for single line messages

![image](https://user-images.githubusercontent.com/16890566/41376815-350168c6-6f0f-11e8-8bfb-7c0769151833.png)

Lets learn `m.` :)

**Comment by ramya-rao-a** [comment] 2018-06-13 20:43
The initial notification that @aeschli shared above does look better now

![image](https://user-images.githubusercontent.com/16890566/41377048-be6d99c2-6f0f-11e8-867d-3d4088caf438.png)

**Comment by bpasero** [comment] 2018-09-11 15:43
@ramya-rao-a your case sounds like a bug to me, can you file it if it reproduces?

**Closed** 2018-09-11 15:43 UTC
Labels: *out-of-scope, feature-request, ux, workbench-notifications

**Comment by ramya-rao-a** [comment] 2018-09-11 18:55
Now it occurs only on hover.

Did we change something to make the gear and the close icons appear only on hover?

![image](https://user-images.githubusercontent.com/16890566/45381185-7b7a7400-b5b9-11e8-8a57-e6020377dc7e.png)

**Comment by bpasero** [comment] 2018-09-12 03:53
@ramya-rao-a that should have been there since the beginning
