### ISSUE TITLE
Native Real-Time Preview in the code editor

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode#75078] opened 2019-06-07 14:09 UTC
I propose that Visual Studio Code include the same feature of Brackets, which can preview in real time the changes that are executed in an HTML or PHP document, without having to save the document or refresh the browser.
With the additional feature that allows this within the code editor and in the user's browser.

To explain myself better:

What I want Visual Studio Code to do is that it has a built-in previewer for websites in any language to create websites like HTML, PHP, PUG, etc. and that supports dynamic changes in CSS, SASS, Javascript, etc. I would also like to see all the changes made in the document in real time without having to reload or save the document to be able to observe the changes in real time, either in a PHP or HTML document that has linked CSS or JavaScript files and also that this previewer can be used within the same editor of Visual Studio Code by dividing the screen in two, either vertically or horizontally and that all these features that I said are also possible in the browser, so that you can preview all changes in the HTML or PHP document without having to reload or save changes to display them directly in the browser. As well as including an examiner of the body of the document that when clicking on a part of this we will take directly to the label in question that we click; For example: if I am now looking at the header of a page and I click it from the preview of the document, I would like it to take me directly to that line of code that has the search in the document.

What I propose is to integrate the same Brackets functionality to preview webs, without any additional extension for visual studio code; I want this to be included, because I have tried many preview extensions and ninugna complies with all these features mentioned above.

Please Microsoft, this is the dream of all the web programmers.

**Comment by egamma** [comment] 2019-06-07 16:55
Does this extension cover your needs https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

**Comment by COD3BREAK3R** [comment] 2019-06-10 12:54
https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

This extension does not meet my requirements, does not automatically reload the page, does not show PHP files, does not even have a preview that refreshes the page automatically when saving. I have tried many extensions of this type and none meet my requirements, brackets is one step ahead in this regard with respect to visual studio code because there is no other extension that has a preview as the brackets

**Comment by COD3BREAK3R** [comment] 2019-06-10 12:55
> Does this extension cover your needs https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

This extension does not meet my requirements, does not automatically reload the page, does not show PHP files, does not even have a preview that refreshes the page automatically when saving. I have tried many extensions of this type and none meet my requirements, brackets is one step ahead in this regard with respect to visual studio code because there is no other extension that has a preview as the brackets

 @COD3BREAK3R

**Comment by egamma** [comment] 2019-06-11 06:40
//fyi @auchenberg

**Comment by egamma** [comment] 2019-06-11 06:41
Duplicate of #12080

**Closed by egamma** 2019-06-11 06:41 UTC
Labels: editor-contrib, feature-request

**Comment by auchenberg** [comment] 2019-06-11 08:02
Hi @COD3BREAK3R  👋

You can combine the popular [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension that gives you live reloading functionality with [Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview), which gives you that inline browser inside VS Code. Think of the extension as modular lego-bricks you can combine to the experience you want.

Brackets still have element highlighting and PHP support, which isn't supported by LiveServer+Browser Preview, but you could run your own php dev server from the integrated terminal.
