### ISSUE TITLE
Dark Transparent Overlay over windows

### ISSUE THREAD

**Issue by ChrisWestermann** [microsoft/vscode#103641] opened 2020-07-30 16:40 UTC
Issue Type: <b>Bug</b>

There is a dark transparent overlay over every Visual Studio Code and Visual Studio Installer windows.  I can still use and interact with the UI, however everything is now darker then before and changing theme colors does not do anything.  In some cases white boxes will appear over parts of the text editor windows.  This seemed to appear after the last round of updates.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.10GB free)|
|Process Argv|--wait G:/Development/Work/Bedrock/.git/COMMIT_EDITMSG --waitMarkerFilePath C:\Users\chris\AppData\Local\Temp\kqhpgi|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ChrisWestermann** [comment] 2020-07-30 16:42
Oddly, when I attempt to take a screen shot the windows appear correctly after pasting the image.

**Comment by ChrisWestermann** [comment] 2020-07-30 16:46
Attached picture of screen.  Visual Studio 2019 window is behind the VS Code and VS Installer windows to show that I should normally see bright white backgrounds in editor windows.

![IMG_20200730_124408](https://user-images.githubusercontent.com/7303357/88950370-8e0bfe00-d262-11ea-9249-4585cc915c4f.jpg)

**Comment by IllusionMH** [comment] 2020-07-30 17:28
Looks more like duplicate of #88491 and not overlay.

Can you check if workaround https://github.com/microsoft/vscode/issues/88491#issuecomment-589527628 works?

You can also try Insiders build as mentioned in the end of the thread.

**Comment by ChrisWestermann** [comment] 2020-07-30 19:15
HDR mode was the issue.  Didn't think of that. Thank you.

**Comment by IllusionMH** [comment] 2020-07-30 19:19
/duplicate of #88491

Glad that it works.
Should be fixed in July 2020 build (early August if there will be no clockers for Electron 9 upgrade)

**Closed** 2020-07-30 19:20 UTC
Labels: *duplicate
