### ISSUE TITLE
Make the app available on the OS X App Store?

### ISSUE THREAD

**Issue by yvan-sraka** [Microsoft/vscode#41935] opened 2018-01-21 19:07 UTC
Hello,

I do not see any issue related to this in this repository after a quick search.

It could be really nice to let the application available in the OS X App Store! I do not know if there is a restriction or a good reason why the app is not already available now?

Thank you for those who could give me an answer.

**Comment by tluanga34** [comment] 2018-01-22 09:29
Microsoft would need to pay some fees to submit the app in the app store. This project is completely open source so, it is likely not to happen.

**Comment by mjbvz** [comment] 2018-01-22 16:36
Duplicate of #19544

**Closed by mjbvz** 2018-01-22 16:36 UTC
