### ISSUE TITLE
"Go To Symbol in Workspace" command provides inconvenient UX in some cases.

### ISSUE THREAD

**Issue by kkovalevskiy** [microsoft/vscode#17022] opened 2016-12-10 15:24 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.12.2|
|path-intellisense|christian-kohler|1.1.0|
|githistory|donjayamanne|0.1.2|
|vscode-generate-getter-setter|DSKWRK|0.4.1|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|RelativePath|jakob101|0.11.0|
|docthis|joelday|0.3.5|
|Angular2|johnpapa|1.0.2|
|refactorix|krizzdewizz|0.3.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|typescript-hero|rbbit|0.11.0|
|vscode-icons|robertohuertasm|4.0.5|
|vscode-terminal-here|Tyriar|0.0.5|
|gitblame|waderyan|1.3.0|

---

"Go To Symbol in Workspace" command (CTRL+T) is one of the most useful commands used for navigation in workspace, but in some cases it can be not so useful as it could be. Here is a couple of examples (usually I use VS code for typescript projects):

1. When I run vs code and there are no opened files, CTRL+T doesn't provide any result. For new users of VS code it's a bit unobvious fact, that you should open some file before perform some navigation.
2. If I have several tsconfig.json files in my workspace (atleast two), it performs search only within nearest one relative to an editing file. So, I can't see any classes and interfaces from the first project if I'm editing a file from the second project.

I suppose that this a bit strange behaviour origins from Typescript Language Service (tsserver), but can these issues be resolved on VS Code side? Most of users expect that "Go To Symbol in Workspace" performs search through whole workspace folder and through all projects in this workspace.

Thanks for awesome editor, it's really great!

**Comment by jrieken** [comment] 2016-12-12 08:57
That a problem specific to TypeScripts `WorkspaceSymbolProvider` and how tsserver works

**Comment by deadbeef84** [comment] 2017-03-23 14:59
> When I run vs code and there are no opened files, CTRL+T doesn't provide any result. For new users of VS code it's a bit unobvious fact, that you should open some file before perform some navigation.

This also confused me. I have a habit of closing all open files every now and then, but then CTRL+T wont work, so now I mostly use **Go to file... (CTRL+P)** to avoid this confusion all together.

I don't know how tsserver works, but wouldn't it be possible to use the project root folder as the tsserver root? Especially considering I have a `tsconfig.json` there.

**Comment by brunetton** [comment] 2017-10-04 11:34
> When I run vs code and there are no opened files, CTRL+T doesn't provide any result. For new users of VS code it's a bit unobvious fact, that you should open some file before perform some navigation.

Indeed. All my dev team just tried the new VSCode version to check out if this *broken* feature has been *repaired*; but we was quite disappointed seeing that "Goto symbol in workspace" still doesn't return any result.

If I understand well, "Goto symbol in workspace" is only looking in **opened files** ? Maybe should it be renamed to "Goto symbol in opened files" instead ?

**Comment by rajinder-yadav** [comment] 2018-04-03 04:55
I would love to be able to search from any symbol from the project and have them appear first, before other NPM modules or external imports.

**Comment by imsedim** [comment] 2018-04-25 08:25
[Years](https://github.com/Microsoft/vscode/issues/8081) [since](https://github.com/Microsoft/vscode/issues/11026) [first](https://github.com/Microsoft/vscode/issues/17393) [reported](https://github.com/Microsoft/vscode/issues/23584)? 
Still no commits?
How come, VScode Team?

**Comment by CaoLiSheng** [comment] 2018-05-09 09:27
I run into the same problem. cmd+t can only search in opened files and maybe some related files.

**Comment by smelukov** [comment] 2018-06-11 11:48
The same confusing... I expect that `Go To Symbol in Workspace` is not depend on opened files

**Comment by leidegre** [comment] 2018-10-11 06:29
@jrieken this is incredibly annoying but easy enough to work around. How do we fix this? What specifically is it that the tsserver does that is preventing this feature from working as if I had all my TS file opened in the first place? For the most time it does find stuff but whenever you switch workspace or restart VS code it's back to nothing.

**Comment by rajinder-yadav** [comment] 2018-11-01 02:02
Anyone looking into fixing this?

**Comment by rmariuzzo** [comment] 2018-11-30 15:09
I would be happy to help if someone can point to the cause in the source.

**Comment by gennaro-tedesco** [comment] 2019-10-25 15:17
has this been looked into, ever since?

**Comment by bhagatparwinder** [comment] 2020-01-08 22:43
This has been open for a while! Why can't I search for symbol when no file is open in workspace?

**Comment by mjbvz** [comment] 2020-04-24 07:51
Not searching all projects is a duplicate of #11026 (fixed with TS 3.9)

Search requiring a file is a duplicate of #11173

**Closed by mjbvz** 2020-04-24 07:51 UTC
Labels: bug, javascript, typescript

**Comment by syabro** [comment] 2020-04-24 08:06
@mjbvz does it work only with TS?
What's about python/es6 classes for example?

**Comment by mjbvz** [comment] 2020-04-24 08:23
This issue (and the linked ones) are about JS/TS

If you see this same issue but for Python, please file an issue against the python extension
