### ISSUE TITLE
代码补全会把后面的代码覆盖

### ISSUE THREAD

**Issue by SomnusTan** [microsoft/vscode#82463] opened 2019-10-13 15:35 UTC
Issue Type: <b>Bug</b>

ts代码补全时，会把后面的代码覆盖
比如代码public getAvatarData(resName) {这样
我要给参数加上类型resName:string
则输入 :st 时，弹出补全选择，我选中string时，代码会变成
public getAvatarData(resName:string
原来后面的 ) { 都不见了

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:44:05.506Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
vscode-eslint|dba|1.9.1
vscode-language-pack-zh-hans|MS-|1.39.3
python|ms-|2019.10.41019
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
EgretCode|zc|0.0.3

</details>

**Comment by byyxx128** [comment] 2019-10-13 18:23
1. In English please.
2. With detailed steps to reproduce. You can record a gif to show this issue.

**Comment by varadero** [comment] 2019-10-14 05:39
Looks like a duplicate of #82468 , #82466 , #82444

**Closed** 2019-10-14 07:22 UTC
Labels: *english-please
