### ISSUE TITLE
Search editor can show invalid values for context lines

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#193611] opened 2023-09-20 19:36 UTC
See several duplicate lines below:

![Image](https://github.com/microsoft/vscode/assets/2193314/2d56e685-047b-4330-8c1b-cc174ba88f3d)

It might have something to do with having the file opened?

**Comment by jaminthorns** [comment] 2023-09-21 15:11
I've recently noticed this too, and I can confirm that it corresponds with having the file open.

You can test by closing any of the files that you notice duplicate lines for and refreshing the search editor. The duplicate lines will disappear. Reopen the file, refresh the search, and the duplicate lines with reappear.

If you increase the number of context lines, the behavior of exactly what's duplicated becomes clearer. The duplicated lines are always:

- The line above the match
- The last line of the match "chunk"

If either or both of those don't exist (because the matched line is the first/last in the file), then you won't get the corresponding duplicates. Duplicates never occur when the context lines are disabled/set to 0.

**Closed** 2023-09-25 15:24 UTC
