### ISSUE TITLE
False statement in warning

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#21615] opened 2017-03-01 10:29 UTC
Hi,

I just saw this warning in the built-in CSS linter (VSC is up to date):

```
[css] Property is ignored due to the display. With 'display: inline-block', float properties have no effect.
```

This is untrue: the only "display" value that would override a float statement is "none". Any other case is the opposite: the display property has no effect on float elements.

Here’s a test: https://jsfiddle.net/wr5pgn1c/1/ 

Thanks!

**Comment by aeschli** [comment] 2017-03-01 15:43
duplicate of #16548

**Closed by aeschli** 2017-03-01 15:43 UTC
