### ISSUE TITLE
Valid JSON flagged as invalid

### ISSUE THREAD

**Issue by TastesLikeTurkey** [Microsoft/vscode#36066] opened 2017-10-11 12:46 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
xml|Dot|1.9.2
tslint|eg2|1.0.10
vscode-npm-script|eg2|0.2.1
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-styled-components|jpo|0.0.8
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
vscode-statusbar-json-path|ric|1.0.7
sample-ext|Rol|0.0.2
nativescript|Tel|0.7.2
markdown-all-in-one|yzh|0.10.3

(1 theme extensions excluded)

---

Steps to Reproduce:

Enter this code into a JSON file:

```
{
  "name": "MyExtension",
  "author": "Somebody",
  "description": "An extension",
  "version": "1.0",
  "manifest_version": 1,
  "content_scripts": [
    {
      "js": [ "./src/scrip.js" ],
      "matches": [ "*://*" ]
    }
  ]
}

```

It shows an error after the content script object, saying "Value expected".

Reproduces without extensions: Yes/No

**Comment by TastesLikeTurkey** [comment] 2017-10-11 12:49
This appears to be specific to a certain file I have open. It's not refreshing it or something.

**Comment by egamma** [comment] 2017-10-11 14:13
@TastesLikeTurkey 
I cannot reproduce it using the same contents (see below). Can you reproduce this when you have the extensions disabled?

![image](https://user-images.githubusercontent.com/172399/31445762-0b00fb58-ae9f-11e7-8958-8b44a8de136f.png)

**Comment by egamma** [comment] 2017-10-16 06:49
closing, please reopen with more information for how to reproduce the problem.

**Closed by egamma** 2017-10-16 06:49 UTC
Labels: needs more info
