### ISSUE TITLE
Auto Format pasted/moved code

### ISSUE THREAD

**Issue by moyascii** [Microsoft/vscode#15301] opened 2016-11-10 14:55 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. When you move a line, sort the code

**Comment by aeschli** [comment] 2016-11-11 21:08
Can you add a small code sample and the steps to reproduce.
Please also describe what you expect to see.

**Comment by wprater** [comment] 2016-11-12 06:04
I think he may be referring to when you move lines in Atom it will ident the code as you're moving the text.  It's quite nice, actually.

**Comment by ramya-rao-a** [comment] 2016-11-16 19:18
@jrieken Feature Request or extension candidate?

**Comment by jrieken** [comment] 2017-01-03 16:17
actually a dupe of https://github.com/Microsoft/vscode/issues/13945

**Closed by jrieken** 2017-01-03 16:17 UTC
Labels: feature-request, format
