### ISSUE TITLE
JS Debug not updating

### ISSUE THREAD

**Issue by amtagrwl** [Microsoft/vscode#27880] opened 2017-06-01 19:25 UTC
- VSCode Version: 1.12.2
- OS Version: Win 7 64

Steps to Reproduce:

1. Run "Launch chrome against localhost" 
2. Error 

I am working on a small project with JS in VS Code. I am using the Chrome Debugger to test some JS code. Even when the code is edited, the debugger doesn't update the version of the code it runs. I have commented out a line from my .js file but the code is still erroring out at that line. Not too sure what's happening. I have restarted the application in an attempt to make it work, but that doesn't help. I have attached a screenshot. 

Thanks!
![capture](https://cloud.githubusercontent.com/assets/5302320/26696941/52a42b7a-46c5-11e7-915f-9942b15b37c5.PNG)

**Comment by isidorn** [comment] 2017-06-02 09:29
Thanks for reporting but this is a duplicate of https://github.com/Microsoft/vscode/issues/26844
It is fixed in https://code.visualstudio.com/insiders and will be available in the next stable release in about a week

**Closed by isidorn** 2017-06-02 09:29 UTC
