### ISSUE TITLE
ZDOTDIR not getting reset properly

### ISSUE THREAD

**Issue by QBos07** [microsoft/vscode#213099] opened 2024-05-20 21:03 UTC
Type: <b>Bug</b>

after injection of the terminal shell integration ZDOTDIR is not reset (i.e. undefined) to the correct value but instead left to what the injection was using. This for some reason I don't understand why this only affect history restored ones but not the inital (EDIT: Probably because there is no injection on first open happening; Maybe another propblem using remote tunnels).

How to reproduce:
0. enable terminal history restore
1. `echo "echo hi" >>{ZDOTDIR:-$HOME}/.zshrc`
2. open a zsh terminal
- `hi` should be printed
3. `echo $ZDOTDIR`
4. close & re-open vscode
- after terminal initialized prompt should be defaulting and there is no `hi` being printed
5. `echo $ZDOTDIR` again
- output differs

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux arm64 6.5.0-1019-oracle

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (21.52GB free)|
|Process Argv|--crash-reporter-id a3a542d8-bb78-4ebc-b2d0-f92c2f5f577a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|instance-20230202-18|
|OS|Linux arm64 6.5.0-1019-oracle|
|CPUs|Neoverse-N1 (2 x 0)|
|Memory (System)|11.65GB (6.99GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.62.0
vsc-python-indent|Kev|1.18.0
kconfig|luv|1.0.3
autoconf|mae|0.2.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
vscode-speech-language-pack-de-de|ms-|0.4.0
pdf|tom|1.2.2
copilot|Git|1.194.0
copilot-chat|Git|0.15.2
vscode-clangd|llv|0.1.28
bash-ide-vscode|mad|1.41.0
vscode-docker|ms-|1.29.1
vscode-language-pack-de|MS-|1.89.2024050109
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
bash-beautify|sha|0.1.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31049070
fchga941:31046352
dvdeprecation:31052039
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by meganrogge** [comment] 2024-12-18 20:37
I get the same, correct (custom), `$ZDOTDIR` after reloading with shell integration. Closing as I cannot reproduce

**Closed by meganrogge** 2024-12-18 20:37 UTC

**Comment by QBos07** [comment] 2024-12-20 18:49
can repilicate on newest version at time of writing: ![Image](https://github.com/user-attachments/assets/b5e26cef-59ec-4d57-83b2-0eee3e5296d6)
the diffrenece to my reprocude steps is that is noticed i use `.zshenv` instead of `.zshrc` like one should.
