### ISSUE TITLE
Background color changes in "blocks" in editor

### ISSUE THREAD

**Issue by ohkaiby** [Microsoft/vscode#17209] opened 2016-12-14 23:14 UTC
- VSCode Version: 1.8.0
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open an editor window.
2. You should be able to see that the background color of the editor window is not consistent. This happens for all themes.

![image](https://cloud.githubusercontent.com/assets/1090861/21205237/b77c47f0-c220-11e6-848c-40bdb0327607.png)

**Comment by kieferrm** [comment] 2016-12-15 01:01
This is an issue with how chrome uses your GPU. Please start code with the following option `--disable-gpu`.

**Comment by kieferrm** [comment] 2016-12-15 01:02
Duplicate of #12473.

**Closed by kieferrm** 2016-12-15 01:02 UTC
Labels: upstream
