### ISSUE TITLE
Markdown only syntax highlights code when at start of line

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#40999] opened 2018-01-01 00:19 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24

![image](https://user-images.githubusercontent.com/3335181/34464809-4a7a0bb2-ee46-11e7-9a9d-18d8ff4dc9e0.png)

---

Like #38523, but with language-specified code syntax instead of quotes.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2018-01-02 18:30
Duplicate of #10082

**Closed by mjbvz** 2018-01-02 18:30 UTC
Labels: markdown
