### ISSUE TITLE
TypeScript language region/endregion autocomplete superfluous slashes

### ISSUE THREAD

**Issue by reviewher** [microsoft/vscode#94580] opened 2020-04-07 01:47 UTC
- VSCode Version: 1.43
- OS Version: OSX 10.5.3

Steps to Reproduce:

1. New file and set language to "TypeScript"
2. Type `//#` and select "#region"

Expected result `//#region`, VSC actually makes it `////#region`

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-04-08 09:01
duplicate of https://github.com/microsoft/vscode/issues/92051

**Closed by aeschli** 2020-04-08 09:01 UTC
Labels: editor-folding, typescript
