### ISSUE TITLE
Extension development shouldn't check for engines.vscode being *

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#31574] opened 2017-07-27 13:38 UTC
Testing #31448

We often have to change `engines.vscode` to `*` in order to get the latest `vscode.d.ts` while developing an extension. If you F5 that extension you'll get an error that the vscode version isn't valid. This is always such a pain to go through every time one needs to test an extension using a new API.

IMO in extension development mode, the extension should still be loaded. This error shouldn't be there.

**Comment by bpasero** [comment] 2017-08-11 09:42
Yeah agree.

@sandy081 moving to you since it seems the API check is done in [`extensionValidator`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensions/node/extensionValidator.ts#L225). 

I wonder if we should just always allow a version to be "*" given that we allow this when you run `npm install` in the extension?

Otherwise, the simplest way of knowing that you are running inside the extension development host is via `IEnvironmentService.isExtensionDevelopment`

**Comment by sandy081** [comment] 2017-08-21 10:45
What does it mean if an extension has `engines.vscode` value `*` in a production version? This extension is compatible with any vscode? Not sure about complete impact.

Better improvement would be to allow it only during extension development.

**Comment by moshfeu** [comment] 2018-09-25 21:08
I faced this pain when I tried to understand which engine I should specify to get the typings for [`createTerminal`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#2120).
The solution can be either specify  in the docs, from which version it can be used (just like [jQuery](https://api.jquery.com/add/#add-selector)). Or specify the version in the _vscode.d.ts_.

**Comment by sandy081** [comment] 2019-03-25 15:39
Ignoring `*` while development might confuses the author that why it works while development and not in production (after published). 

@joaomoreno What is the validation in vsce? Does it allow `*` ?

@alexandrudima FYI

**Comment by joaomoreno** [comment] 2019-03-26 08:04
Though I think it does not apply, since one uses VSCE when ready to publish, at which point the engine should not be `*`... but VSCE does accept `*`: https://github.com/Microsoft/vscode-vsce/blob/master/src/validation.ts#L40

**Comment by sandy081** [comment] 2019-03-26 09:52
Since we do not support `*` in production, we can have a guard in VSCE to prevent this?

Given that VSCE will guard it, I think it is ok to allow `*` while testing an extension in development

**Comment by alexandrudima** [comment] 2019-03-27 19:17
I disagree with changing the engine check logic.

**Comment by sandy081** [comment] 2019-03-27 19:54
@alexandrudima Can you please state your reasons.

**Comment by alexandrudima** [comment] 2019-03-27 20:30
The engine check logic should be 100% the same when a developer tries out their extension and when the extension is installed on a user machine. In other words, it is very important to have reproducibility, especially around something that can brick your extension. 

And what is the use-case? What percentage of extension authors need to use `*` to use the `vscode.d.ts` on `master`? Moreover, is this even the case anymore with @octref 's work? I think the `vscode.d.ts` is now coming in from `@types`, and no longer downloaded based on the `engines` version, so the whole issue is IMHO artificial and outdated and dangerous as it would lead to a bad change.

**Comment by octref** [comment] 2019-03-27 20:48
I have this item in #71048 (will do it in May):

> Provide a module vscode-dts, so we can run `npx vscode-dts dev` or `npx vscode-dts 1.30` etc for testing.

The logic for `npx vscode-dts dev` would be:

- Download latest `vscode.d.ts` from master branch
- Replace the `vscode.d.ts` in either `vscode` or `@types/vscode`
- `npx vscode-dts restore` would restore correct version of `vscode.d.ts`
    - For `vscode`, restore according to `engines.vscode`
    - For `@types/vscode`, restore according to `node_modules/@types/vscode/package.json`

Also plan to have a **hidden** command `npx vscode-dts proposed` which does all above + downloading a copy of `vscode.proposed.d.ts` + `enableProposedAPI: true`. Hidden because we don't want too much attention on using proposed APIs.

**Comment by sandy081** [comment] 2019-03-28 08:58
If we are going away from using `vscode.engine` to download `vscode.d.ts`, then we should make `*` as invalidate everywhere.

**Comment by alexandrudima** [comment] 2019-03-28 10:02
> If we are going away from using `vscode.engine` to download `vscode.d.ts`, then we should make `*` as invalidate everywhere. 

It is already invalid everywhere, that's why I kindly ask to not touch the logic.

**Comment by sandy081** [comment] 2019-03-28 13:21
I mean also while installing extensions, where we check this to get the compatible extension to install.

**Comment by alexandrudima** [comment] 2019-03-28 21:39
@sandy081 Do you mean there are today extensions published in the marketplace with the engine `*`? How is that possible? They would never load in VS Code. We only allow built-in extensions to use `*`.

**Comment by sandy081** [comment] 2019-04-01 07:37
@alexandrudima Yes, there can be extensions published with `*` as VSCE does not restrict it, see [comment](https://github.com/Microsoft/vscode/issues/31574#issuecomment-476515372). Also while looking for a compatible extension to install, we take `*` as valid value. There is some gap and inconsistency here.

I am sure there are no such extensions because as you said we do not load them in ext host.

**Comment by octref** [comment] 2019-06-28 22:00
> We often have to change engines.vscode to * in order to get the latest vscode.d.ts while developing an extension.

That is no longer the case. `vscode-dts` will download and remove the duplicate `vscode.d.ts` from either `node_modules/vscode` or `node_modules/@types/vscode` upon your confirmation.

![dev](https://user-images.githubusercontent.com/4033249/60373521-4c50ba00-99b5-11e9-8ffa-ea4a899dd162.gif)

Can we close this issue then? I also agree we should keep the `engines.vscode` working as it is now.

**Closed** 2019-06-30 18:37 UTC
Labels: extension-host, verification-needed
