### ISSUE TITLE
Anonymous function argument names are being autocompleted

### ISSUE THREAD

**Issue by distinctdan** [Microsoft/vscode#54443] opened 2018-07-17 03:35 UTC
Issue Type: <b>Bug</b>

Yet another annoying issue. In typescript, when typing the signature of my anonymous function, VS Code autocomplete my argument names, which is totally wrong.

For example, if I'm trying to type this code:

    myArray.sort((a, b) => {

When I've typed this much `myArray.sort((a` and then type the comma, VS autocompletes `a` to `this.activate`, which is a method on the class. Autocomplete should be off for anonymous function arguments, and autocompleting on comma seems like a bad idea anyways. The editor should stay out of your way unless you tell it to, following the Rule of Least Surprise in UX design. VS Code has so much autocomplete junk and focus-grabbing popups that come up when you type, it feels like I'm fighting the editor more than I'm writing code.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.6

</details>

**Comment by jrieken** [comment] 2018-07-18 07:54
Please provide more information so that we can reproduce this. Thanks

![jul-18-2018 09-53-54](https://user-images.githubusercontent.com/1794099/42867658-8946493e-8a70-11e8-8a25-6abd885b3283.gif)

**Comment by mjbvz** [comment] 2018-07-18 21:51
Duplicate of #54386

**Closed by mjbvz** 2018-07-18 21:51 UTC
Labels: needs more info, suggest, typescript

**Comment by distinctdan** [comment] 2018-07-19 19:33
Here's a simplified version of the class. The above example isn't doing it because it's missing a class method that starts with `a`.

    module Foo {
        'use strict';

        export class MyClass {
            public activate() {}

            public foo() {
                var myArray = [1, 2, 3];
                myArray.sort((a
            }
        }
    }

I'll take a look at the other thread.
