### ISSUE TITLE
Disable intellisense when typing <?php

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2744] opened 2016-02-05 20:02 UTC
Whenever I type `<?php` and press enter, intellisense autocompletes the item and turns it into this:

```php
<?php_ini_loaded_file
```

What should happen, is that it should create a new line instead.

**Comment by mattacosta** [comment] 2016-02-06 09:48
Duplicate of #663, #1380.

**Closed** 2016-02-06 14:06 UTC
