### ISSUE TITLE
Questions about undo/redo API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96485] opened 2020-04-28 21:19 UTC
On the `onDidChangeCustomDocument` Event, it's interesting that it fires an object with an 'undo' method. As an implementor it makes me a little uncomfortable because there is no typed guarantee that these undo functions will be called in the order I expect. 

```ts
this._onDidChange.fire({
	label: 'Stroke',
	undo: async () => {
		this._edits.pop();
		this._onDidChangeDocument.fire();
	},
	redo: async () => {
		this._edits.push(edit);
		this._onDidChangeDocument.fire();
	}
```

I have to make a lot of assumptions,

- 'undo' for an edit will only be called on this edit after 'undo' has been called on all subsequent edits
- undo and redo will only be called once
- redo only called after undo

and so on. And I know it's safe to assume those, but did you consider an API where VS Code would just call undo/redo on the provider without specifying a particular edit, so the extension can maintain those assumptions itself? 

And I'm probably stepping into something with a lot of history, so if you've already beat this to death then just tell me it's settled 😁

**Comment by mjbvz** [comment] 2020-04-28 23:40
Thanks for the feedback. 

We landed on the current design in part because it matches our [internal undo/redo service](https://github.com/microsoft/vscode/blob/8ad94ef2ac4d5f2921f6ed081b3c492f30a48413/src/vs/platform/undoRedo/common/undoRedo.ts#L16). It is also a compromise between not having structured edits at all and having VS Code fully define the what edits look like and how they are used. Previous iterations of the API 

When implementing these methods, your extension should generally only need to think about how it would undo or redo the single edit that has been made. The example custom editor extension however needs to maintain a stack of edits since it far easier to to redraw all drawn lines up to the current edit point rather than trying to actually undo a draw operation.

@roblourens Once you started using the API, did the behavior make more sense? Any suggestions on what would help you understand what your extension is supposed to do for these methods? Improved documentation for example?

/cc @jrieken  @bpasero

**Comment by roblourens** [comment] 2020-04-29 00:07
> When implementing these methods, your extension should generally only need to think about how it would undo or redo the single edit that has been made

But I usually can't undo an edit without the editor/document being in the same state that it was when the edit was made. When I implement undo, I am either assuming that's the case (and if I'm wrong, I'll probably corrupt the document) or I am keeping a stack of edits and writing 'undo' to actually undo the _last_ edit, not the _specified_ edit which is what the sample editor does.

Edits are piled on top of other edits, and I typically can't undo one from the middle unless I have first undone all the later edits. Now that I think of it, in this case of the simple image editor, you could actually undo an edit from the middle of the stack and the right thing would happen. I doubt VS Code would ever want to do that, but if I am implementing this I have doubts since the API does enable it.

**Comment by roblourens** [comment] 2020-04-29 00:10
I think that it would help if you just write out those assumptions in the docs. Most people probably wouldn't be bothered by it. But the sort of people who turn on all the strict TS options might like some reassurance about when this function that they fired out will be called.

**Closed** 2020-04-29 21:55 UTC
Labels: custom-editors

**Comment by mjbvz** [comment] 2020-04-29 22:00
@roblourens Take a look at the updated docs I just pushed. I've tried to summarize what implementors of `undo` and `redo `are support to do. The new docs still do not go into details about edit stack since I felt that made the intended behavior more difficult to understand 

Let me know if you have any further ideas on how this could be made clearer.

**Comment by jrieken** [comment] 2020-04-30 07:35
> undo and redo will only be called once

Should we also clarify that this ⬆️ actually isn't true? If a user does undo, redo, undo, redo, undo, redo then the "same" undo and redo function are called over and over again

**Comment by roblourens** [comment] 2020-04-30 14:24
Yeah "once unless the opposite method is called" is what I had in mind
