### ISSUE TITLE
paste twice

### ISSUE THREAD

**Issue by gemini-mouse** [microsoft/vscode#102185] opened 2020-07-11 01:52 UTC
upgrade to 1.47.0
everything paste twice, so annoying..

error - 
#rso > div:nth-child(1) > div > div.r > a > h3#rso > div:nth-child(1) > div > div.r > a > h3

shall be -
#rso > div:nth-child(1) > div > div.r > a > h3

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

**Comment by blackwharf** [comment] 2020-07-11 02:00
got the same problem!
everything also copies mutiple times with crtl+y

**Comment by injcristianrojas** [comment] 2020-07-11 02:30
Same over here. Pastes twice.

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.7-200.fc32.x86_64

**Comment by mjbvz** [comment] 2020-07-11 04:51
Duplicate of #101946

**Closed by mjbvz** 2020-07-11 04:51 UTC
Labels: new release
