### ISSUE TITLE
Code intelligent didn't display as markdown content for param comment. 

### ISSUE THREAD

**Issue by vothanhdat** [Microsoft/vscode#27832] opened 2017-06-01 10:26 UTC
Code intelligent doesn't display as markdown content for param comment. 

- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

![screenshot from 2017-06-01 17-16-28](https://cloud.githubusercontent.com/assets/8221386/26675642/f11eacfc-46ee-11e7-8a17-a96ec40844ee.png)
![screenshot from 2017-06-01 17-16-55](https://cloud.githubusercontent.com/assets/8221386/26675643/f1526a60-46ee-11e7-920c-066014110080.png)

**Comment by jrieken** [comment] 2017-06-02 06:38
dupe of #11877

**Closed by jrieken** 2017-06-02 06:38 UTC
