### ISSUE TITLE
Introducing '.js' file causes errors with TypeScript code

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#1157] opened 2015-12-10 01:46 UTC
From https://www.reddit.com/r/programming/comments/3ux8fs/announcing_typescript_17/cxo5ldn?context=3.

> I just updated VSCode to the latest version (0.10.3) and reduced this problem to a small case, and I'm really confused:

> 1. A simple internal module, a simple .d.ts referencing it. Everything works fine: http://i.imgur.com/O8uIQFT.png

![](http://i.imgur.com/O8uIQFT.png)
2. I create a plain .js file. Even without writing to it or saving it again, I get Schrodinger's interface: http://i.imgur.com/siOf1AV.png

![](http://i.imgur.com/siOf1AV.png)

> At this point, the errors about the interface file won't go away. After I close the .js file in the editor, close the folder, and reopen the folder, things go back to normal. But as soon as I open a plain .js file, they come back just like before. After the errors get triggered, I can close the .js file and they stay in the status bar. If I then add both the module and the .d.ts to the "working files" list, then remove .d.ts from it, the errors vanish again.

We're not sure what sort of interaction might be going on with the TypeScript language service, so we felt it would be better filed here.

**Comment by dbaeumer** [comment] 2015-12-15 14:29
These errors are produced by the JS language service. The owner is javascript/semantic. Since the view.d.ts file is a declare file it is loaded into the JS language service and that doesn't know anything about the all.ts file which defines the mystery namespace.

**Comment by dbaeumer** [comment] 2015-12-15 14:29
Moving to @jrieken

**Comment by egamma** [comment] 2015-12-15 14:31
The issue is understood, removing the important label.

**Comment by jrieken** [comment] 2015-12-15 15:52
This is how the current JS implementation works. It only considers `.js` and `.d.ts` files, but no `.ts` files. We won't fix that for the current JS language service but it might go away once we use project Salsa.

**Closed by jrieken** 2015-12-15 15:52 UTC
Labels: bug, js
