### ISSUE TITLE
 Capabilities for imagePreview.previewEditor already set

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97446] opened 2020-05-11 06:02 UTC
Issue Id: <b>313b7387-2f9b-19d3-4eae-e942e4f9586b</b><br /><br />*Versions* <br />- 1.45.0<br />*Stack* <br />Error: Capabilities for imagePreview.previewEditor already set<br />[/vs/workbench/contrib/customEditor/browser/customEditors.ts#277:9 (registerCustomEditorCapabilities)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L277:9 (registerCustomEditorCapabilities))<br />[/vs/workbench/api/browser/mainThreadWebview.ts#328:28 (registerEditorProvider)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadWebview.ts#L328:28 (registerEditorProvider))<br />[/vs/workbench/api/browser/mainThreadWebview.ts#313:7 (apply)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/api/browser/mainThreadWebview.ts#L313:7 (apply))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#402:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L402:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#387:31 (_invokeHandler)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L387:31 (_invokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#303:18 (_receiveRequest)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L303:18 (_receiveRequest))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#230:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L230:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#105:41 (call)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L105:41 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#453:18 (fire)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/parts/ipc/common/ipc.net.ts#L453:18 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#733:20 (_receiveMessage)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/parts/ipc/common/ipc.net.ts#L733:20 (_receiveMessage))<br />[/vs/base/parts/ipc/common/ipc.net.ts#592:72](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/parts/ipc/common/ipc.net.ts#L592:72)<br />    at e.fire (out/<br />

**Comment by bpasero** [comment] 2020-05-11 06:02
Similar:

```
Error: Capabilities for vscode.markdown.preview.editor already set
/vs/workbench/contrib/customEditor/browser/customEditors.ts#277:9 (registerCustomEditorCapabilities)
/vs/workbench/api/browser/mainThreadWebview.ts#328:28 (registerEditorProvider)
/vs/workbench/api/browser/mainThreadWebview.ts#309:7 (apply)
/vs/workbench/services/extensions/common/rpcProtocol.ts#402:16 (_doInvokeHandler)
/vs/workbench/services/extensions/common/rpcProtocol.ts#387:31 (_invokeHandler)
/vs/workbench/services/extensions/common/rpcProtocol.ts#303:18 (_receiveRequest)
/vs/workbench/services/extensions/common/rpcProtocol.ts#230:9 (_receiveOneMessage)
/vs/workbench/services/extensions/common/rpcProtocol.ts#105:41 (call)
/vs/base/common/event.ts#587:15 (fire)
/vs/base/parts/ipc/common/ipc.net.ts#453:18 (fire)
/vs/base/parts/ipc/common/ipc.net.ts#733:20 (_receiveMessage)
/vs/base/parts/ipc/common/ipc.net.ts#592:72
at e.fire (ou
```

**Comment by mjbvz** [comment] 2020-05-11 17:37
Duplicate of #97060

**Closed by mjbvz** 2020-05-11 17:37 UTC
Labels: error-telemetry
