### ISSUE TITLE
Intellisense is working incorrectly for Vue and React projects in 1.41.1

### ISSUE THREAD

**Issue by sborenko** [microsoft/vscode#88161] opened 2020-01-06 19:01 UTC
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create new Vue project: _**vue create enterprise**_
2. Change current directory to _**enterprise**_
3. Open VS Code: _**code .**_
4. Open main.js file. Type _**imp**_ to add _**import**_ command. No prompts appear, intellisense is not working.
![image](https://user-images.githubusercontent.com/43484798/71839768-9c2adf00-30c4-11ea-8aa7-aacaead3c5b9.png)
Note, if we open App.vue and type _**me**_ to add _**methods**_ property, intellisense works fine:
![image](https://user-images.githubusercontent.com/43484798/71839708-73a2e500-30c4-11ea-9e34-91c94a4b860e.png)
5. Let's reopen project, but this time open _**Enterprise**_'s parent directory _**Vue**_:
6. Open main.js again and again type _**imp**_ to add _**import**_ command. This time intellisense is working: 
![image](https://user-images.githubusercontent.com/43484798/71840132-5f131c80-30c5-11ea-816b-63c3f68ab546.png)
7. But, unfortunately, this time prompts are not correctly working for App.vue:
![image](https://user-images.githubusercontent.com/43484798/71840354-d8ab0a80-30c5-11ea-8108-730ab7a684f4.png)
8. Similar problems happen to _**React projects**_.
9. I have downgraded to version _**1.40.2**_. Everything looks working right:
![image](https://user-images.githubusercontent.com/43484798/71840966-1197af00-30c7-11ea-80ba-353097caf678.png)
![image](https://user-images.githubusercontent.com/43484798/71841058-3724b880-30c7-11ea-9839-51cb26587ffa.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment] 2020-01-08 09:52
I can't reproduce this.

![image](https://user-images.githubusercontent.com/4033249/71968260-d3080e80-3204-11ea-8047-826a61c51262.png)

Were you seeing a long "Initializing JS/TS language features" message in the bottom? During the initialization phase no intellisense will be shown.

![image](https://user-images.githubusercontent.com/4033249/71968289-e5824800-3204-11ea-8cf3-3095d2676b02.png)

**Comment by sborenko** [comment] 2020-01-11 21:16
Yes, I do:

![image](https://user-images.githubusercontent.com/43484798/72210673-9f104000-34c7-11ea-86ea-b695dbc31ad4.png)

Also, when I'm trying to force intellisense to display the prompts by pressing Ctrl + Spacebar, I get "Loading ..." message that never finish:

![image](https://user-images.githubusercontent.com/43484798/72210669-8b64d980-34c7-11ea-8ed5-dff48563fe5f.png)

Incorrect version is still 1.41.1.
Version 1.40.2 still works fine.

**Comment by sborenko** [comment] 2020-01-11 21:29
I looked through the list of more recent issues and found one more similar issue:

**_#88264: when i try to write code intellisense not showing any suggestions
it continuously shows "Loading...." ._**

Probably, that's the same case, as soon as I had the same error not only in Vue, but in React applications as well.

**Comment by octref** [comment] 2020-01-13 10:11
Then this is a issue with TypeScript language server, not Vetur.

**Comment by sborenko** [comment] 2020-01-13 14:36
Great! But this doesn't happen in VSCode version 1.40.2 and earlier.
Must be a new feature.

**Comment by sborenko** [comment] 2020-01-13 15:25
Great! But this doesn't happen in VSCode version 1.40.2 and earlier.

**Comment by mjbvz** [comment] 2020-01-13 21:43
@sborenko  Where is your code stored? Somewhere besides the `c:` drive?

**Comment by sborenko** [comment] 2020-01-13 21:49
On hard disk d:

**Comment by mjbvz** [comment] 2020-01-13 22:02
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-13 22:02 UTC
Labels: javascript, needs more info

**Comment by sborenko** [comment] 2020-01-13 22:03
Okey, thanks. I'll try.
