### ISSUE TITLE
vscode.workspace.getConfiguration('') does not return defaults

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#14500] opened 2016-10-26 00:16 UTC
- VSCode Version: Version 1.7.0-insider (1.7.0-insider) (`2016-10-25T06:03:02.884Z`)
- OS Version: OS X El Capitan

_**vscode.workspace.getConfiguration('') does not return default values for configuration items defined in `package.json` of an extension.**_

Steps to Reproduce:
1. Invoking `vscode.workspace.getConfiguration('python');`, only returns the values found in workspace `settings.json`
2. However this same code running on VS Code (`1.6`) returns from `settings.json` merged with the default configuration values defined in `package.json`

This is the value returned in VS Code Insiders:

``` json
{
    "pythonPath":"${workspaceRoot}/p27/bin/python"
}
```

This is the value returned in VS Code 1.6:

``` json
{
    "pythonPath": "${workspaceRoot}/p27/bin/python",
    "sortImports": {
        "args": [
            "-sp",
            "${workspaceRoot}/issues/sorts"
        ]
    },
    "linting": {
        "enabled": true,
        "prospectorEnabled": false,
        "pylintEnabled": true,
        "pep8Enabled": false,
        "flake8Enabled": false,
        "pydocstyleEnabled": false,
        "mypyEnabled": false,
        "lintOnTextChange": true,
        "lintOnSave": true,
        "maxNumberOfProblems": 100,
        "pylintCategorySeverity": {
            "convention": "Information",
            "refactor": "Hint",
            "warning": "Warning",
            "error": "Error",
            "fatal": "Error"
        },
        "prospectorPath": "prospector",
        "pylintPath": "pylint",
        "pep8Path": "pep8",
        "flake8Path": "flake8",
        "pydocStylePath": "pydocstyle",
        "mypyPath": "mypy",
        "prospectorArgs": [],
        "pylintArgs": [],
        "pep8Args": [],
        "flake8Args": [],
        "pydocStyleArgs": [],
        "mypyArgs": [],
        "outputWindow": "Python"
    },
    "formatting": {
        "provider": "autopep8",
        "autopep8Path": "autopep8",
        "yapfPath": "yapf",
        "autopep8Args": [],
        "yapfArgs": [],
        "formatOnSave": false,
        "outputWindow": "Python"
    },
    "autoComplete": {
        "extraPaths": []
    },
    "unitTest": {
        "nosetestsEnabled": false,
        "nosetestPath": "nosetests",
        "pyTestEnabled": true,
        "pyTestPath": "py.test",
        "nosetestArgs": [],
        "pyTestArgs": [],
        "unittestEnabled": false,
        "unittestArgs": [
            "-s=./tests",
            "-p=test_*.py"
        ],
        "outputWindow": "Python Test Log"
    },
    "terminal": {
        "executeInFileDir": false,
        "launchArgs": []
    },
    "jupyter": {
        "appendResults": true,
        "defaultKernel": "",
        "startupCode": [
            "%matplotlib inline"
        ]
    }
}
```

**Comment by bpasero** [comment] 2016-10-26 09:55
Might be me.

**Comment by bpasero** [comment] 2016-10-26 10:17
@DonJayamanne I cannot reproduce, but this could be a regression from https://github.com/Microsoft/vscode/commit/1dbf76bfb301ff9bf45059d9dfadbc96b84ecb8a

Can you try if this reproduces with that change reverted?

If so, we need to understand how you manage to call `getConfiguration()` early enough that you do not see these values. For that I need a reproducible extension code 👍

**Comment by jrieken** [comment] 2016-10-26 10:47
I know that many extension load settings very early during code loading (*before* activate is being called) so changes to the timing might be risky. There is an underlying problem that we have no extension host lifecycle that says *ready, load extensions now*. Esp [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostConfiguration.ts#L30) is what needs to happen very, very early

**Comment by jrieken** [comment] 2016-10-26 10:48
fyi @alexandrudima - we have talked about this

**Comment by bpasero** [comment] 2016-10-26 11:28
What also could have an impact is that we do extension reading now from the renderer side. Though I have to check if configuration registry is also being configured now from the renderer side.

**Comment by alexandrudima** [comment] 2016-10-26 12:09
yes, in the old way there was an implicit synchronization waiting when the extension host was sending the extension info (package.json) to the main process. Given the new way of reading extensions in the main thread the order should be (roughly):

 *  a. discover and parse `package.json` files
 *  b. **then** trigger extension point listeners
 *  c. **then** begin creating the extension host and use as initData also the initial configuration

I believe b is happening after c today.

**Comment by sandy081** [comment] 2016-10-26 12:25
The refactoring only changed where the extensions are read. **Before**, extensions are scanned in extensionHostMain and **now** they are read in the Renderer. There is no change in the lifecycle other than this. Registering of extensions (=> triggering extension point listeners) still is done in extension host process.

**Comment by alexandrudima** [comment] 2016-10-26 12:30
@sandy081 Extension point listeners were and are still triggered in the main process. e.g. the debug viewlet would not know debuggers if it was done in the extension host process.

**Comment by alexandrudima** [comment] 2016-10-26 12:31
I can take this issue and review the change with this occasion.

**Comment by sandy081** [comment] 2016-10-26 12:52
@alexandrudima You are right. What I meant was extension host process sends the signal to main process to register extensions which is triggering extension point listeners.

Please let me know if you need any information about the changes I have done or any help from me, I would be happy to do.

Thanks

**Comment by bpasero** [comment] 2016-10-26 14:11
Thanks, let me know if we need to do something about the `RunOnceScheduler` for the event.

**Comment by jrieken** [comment] 2016-10-28 10:12
Verified with the following snippet/config and made sure it always prints the same config

```ts

import * as vscode from 'vscode';
console.log('ON LOAD', vscode.workspace.getConfiguration('typescript'));

setTimeout(() => console.log('AFTER 10ms', vscode.workspace.getConfiguration('typescript'), 10));

```

```json
"typescript.format.enable": false,
"typescript.format.insertSpaceAfterSemicolonInForStatements": false
```

<img width="497" alt="screen shot 2016-10-28 at 12 09 14" src="https://cloud.githubusercontent.com/assets/1794099/19803131/60b3262a-9d07-11e6-8bda-d1cc59d05d26.png">

**Comment by octref** [comment] 2016-10-28 23:03
@jrieken 

`vscode.workspace.getConfiguration('python')` returns empty object, even if Python has configuration contributions.

**Comment by bpasero** [comment] 2016-10-31 09:40
Fixed via https://github.com/Microsoft/vscode/commit/1730383e85c56a0788a86cf5f9e0f7ab9af427b3

**Closed by bpasero** 2016-10-31 09:40 UTC
Labels: bug, candidate, important

**Comment by bpasero** [comment] 2016-11-02 10:22
@alexandrudima could you verify please?

**Comment by bpasero** [comment] 2016-11-02 10:38
Actually I just verified:
* installed Python extension into insider build
* wrote an extension that activates on star
* in the very first line called `console.log(vscode.workspace.getConfiguration("python"))`
* output I am seeing:

![image](https://cloud.githubusercontent.com/assets/900690/19925560/cef492d0-a0f0-11e6-95c0-112edb80f950.png)
