### ISSUE TITLE
Typescript Linter & Intellisense unexpected behaviour

### ISSUE THREAD

**Issue by sharadcodes** [Microsoft/vscode#11429] opened 2016-09-02 07:20 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.4.0-36-generic

Steps to Reproduce:

1. Start the `vscode`.
2. Does not have linting support for files just opened.
3. Restart the app to have it support again.
4. If any new files are opened, goto step 2.

I have to restart again and again just to have intellisense for the file.

**Comment by dbaeumer** [comment] 2016-09-02 07:22
@sharadcodes do you have a TypeScript linter installed ? If so which one?

**Comment by sharadcodes** [comment] 2016-09-02 11:51
@dbaeumer No, I have none installed. It is the default one.

**Comment by egamma** [comment] 2016-09-03 15:52
@sharadcodes which version of TypeScript do you have installed, are you using the typescript.tsdk setting to point to a new version of TypeScript than 1.8.1 that is currently used in VS Code.

@dbaeumer since there is no linter involved I assume that @sharadcodes refers to diagnostics from the language server. So I'm assigning this issue back to you.

**Comment by sharadcodes** [comment] 2016-09-04 13:02
@egamma TypeScript Version 1.8.10 and `"typescript.tsdk": null`

**Comment by dbaeumer** [comment] 2016-09-05 09:36
@sharadcodes can you provide an example to reproduce this. I believe this is more a setup problem than a bug in the tsserver.

**Comment by sharadcodes** [comment] 2016-09-06 11:34
I have my code within `src/` and `node_modules/`. `typings.json` & `tsconfig.json` in root. Is it, somehow, not able to look back to `typings/` folder?

**Comment by dbaeumer** [comment] 2016-09-06 18:24
@sharadcodes can you share your code?

**Comment by waderyan** [comment] 2016-09-29 18:00
Closing until more information is given.

**Closed by waderyan** 2016-09-29 18:00 UTC
Labels: needs more info, typescript
