### ISSUE TITLE
Unable to open a file within an egg/zip file in the editor

### ISSUE THREAD

**Issue by asierralozano** [microsoft/vscode#83779] opened 2019-10-31 18:42 UTC
- VSCode Version: 1.39.2
- OS Version: CentOS 7

Steps to Reproduce:
Hello!

I've was redirected from the Python Language Server Repo (Here you have the issue that I've created in there:  https://github.com/microsoft/python-language-server/issues/1731)

I just copy and pasted what I've just wrote there:

> If I use the Go To Definition function with a module that it is inside an egg/zip file, I'm getting the following error:
> Unable to open 'test.py': Unable to read file (Unknown (FileSystemError): Error: ENOTDIR: not a directory, stat '/home/users/alberto/testEnv/testPackage-py2.7.egg/myProject/foo/test.py').
> 
> I can import that file without problems within a Python Terminal by:
> from myProject.foo import test
> 
> If you need more info, please, let me know! :)
> 
> Thanks!

Apparently, the problem is that CentOS is not treating the zips files as folder (like Microsoft Windows does), so if I try to use the any of the Intellisense feature (like Go To Definition) in a file that is pointing to another file inside a zip (or egg) file, VSCode gave the error that I typed above.

I'm wondering if there is any way to handle this.

Thanks!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-10-31 21:23
Duplicate of #75559

**Closed by mjbvz** 2019-10-31 21:23 UTC
