### ISSUE TITLE
Shorten the diff editor tab title

### ISSUE THREAD

**Issue by Otiel** [Microsoft/vscode#44916] opened 2018-03-02 10:51 UTC
Could we have an option to choose the format of the file names displayed on the tab of a diff editor ?

![image](https://user-images.githubusercontent.com/3851902/36894996-8e5790ba-1e0d-11e8-83a1-b25c5606e122.png)

This tab is taking too much space and I can't even see the filename of the right file.

Maybe something similar to `workbench.editor.labelFormat`?
```
// Controls the format of the label for an editor. Changing this setting can for example make it easier to understand the location of a file:
// - short:   'parent'
// - medium:  'workspace/src/parent'
// - long:    '/home/user/workspace/src/parent'
// - default: '.../parent', when another tab shares the same title, or the relative workspace path if tabs are disabled
"workbench.editor.labelFormat": "default",
```

**Comment by bpasero** [comment] 2018-03-02 12:53
I think we can treat #43806 as duplicate of this one.

**Comment by bpasero** [comment] 2018-03-02 12:53
@Otiel as a workaround you could also play around with setting `"workbench.editor.tabSizing": "shrink"`

**Closed by bpasero** 2018-03-02 12:53 UTC

**Comment by Otiel** [comment] 2018-03-02 13:18
@bpasero Thanks. I'm already using `"workbench.editor.tabSizing": "shrink"`, but as you can see on the screenshot it doesn't help with the diff editor.

I think #43806 asks to cover a broader spectrum as I am simply asking to apply `workbench.editor.labelFormat` to the diff editors.

**Comment by Otiel** [comment] 2018-03-08 13:28
Voting to reopen this.
