### ISSUE TITLE
Launch configuration is changed when debugging is started

### ISSUE THREAD

**Issue by quadfin** [Microsoft/vscode#32912] opened 2017-08-21 23:29 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
EditorConfig|Edi|0.9.4
vscode-nuget-package-manager|jmr|1.1.4
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.8
debugger-for-edge|msj|0.4.1
marko|pca|0.2.2
vim|vsc|0.9.0
---

A compound configuration may reference multiple launch configurations.
When such a compound configuration is selected for launch, (debug toolbar, DEBUG list) and the debugging session is started (F5) the selected configuration is changed to the last referenced launch configuration.

Subsequently, to restart the compound configuration one must first manually select the compound configuration in the DEBUG dropdown list.

The expected behavior is to retain the selected compound configuration after debugging is terminated.

Steps to Reproduce:

1. Create a node launch configuration - "Launch Program"
2. Create a chrome launch configuration - "Launch Chrome"
3. Create a compound configuration consisting of the above - "Launch & Debug"
4. Select the compound - "Launch & Debug"
5. Start debugging - F5
6. Stop debugging - Shift-F5, Shift-F5

The selected configuration is now "Launch Program"
The expected behavior is for the selected configuration to be "Launch & Debug"

launch.json:
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}\\app.js",
      "protocol": "inspector"
    },
    {
        "name": "Launch Chrome",
        "type": "chrome",
        "runtimeArgs": [
          "--incognito"
        ],
        "request": "launch",
        "port": 9222,
        "url": "http://localhost:3000/",
        "sourceMaps": true,
        "webRoot": "${workspaceRoot}"
    }
  ],
  "compounds": [
      {
          "name": "Launch & Debug",
          "configurations": [ "Launch Program", "Launch Chrome" ]
      }
  ]
}

Reproduces without extensions: No (not applicable)

**Comment by weinand** [comment] 2017-08-22 08:46
duplicate of https://github.com/Microsoft/vscode/issues/32318

This is already fixed in the Insiders build.

**Closed by weinand** 2017-08-22 08:46 UTC
Labels: debug, new release
