### ISSUE TITLE
Please make code folding for c languages take up only 1 line

### ISSUE THREAD

**Issue by Shadowblitz16** [Microsoft/vscode#47371] opened 2018-04-07 01:26 UTC
please make code folding only take up 1 line when folding with c languages
so something like this..
`if (condition)
{
    stuff
}`

looks like this when folded
`if (condition) {...}`

**Comment by roblourens** [comment] 2018-04-07 22:45
It does fold to a single line, right? Which language are you trying?

**Comment by Shadowblitz16** [comment] 2018-04-10 22:01
action/angel script but it uses c style {} code blocks

**Comment by roblourens** [comment] 2018-04-10 22:13
Can you post a code example? Are you using an extension for that language?

**Comment by Shadowblitz16** [comment] 2018-04-11 02:43
no its just c syntax, just a sec
this is what it looks like..
`
if (condition)
{...

}
`

**Comment by aeschli** [comment] 2018-04-11 07:29
duplicate of #3352

**Closed by aeschli** 2018-04-11 07:29 UTC
Labels: editor, editor-core, needs more info
