### ISSUE TITLE
Accessibility: Manage_Settings_DeveloperTool: The Clear search input button is wrapped in a <ul> which is given a role toolbar.

### ISSUE THREAD

**Issue by nasc17** [microsoft/vscode#139589] opened 2021-12-21 18:32 UTC
"Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier."
Environment Details:
Version: 1.35.0-insider (user setup)
Commit: 443257e699bfa1d7402ee7e41f36cf3db1ac383f
Date: 2021-12-21T06:32:12.431Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

**Repro Steps:**
Launch the application-Azure Data Studio
Tab till settings button and press enter.
Tab till search field.
Tab till clear search input button and inspect using Developer tool.
**Actual:**
The Clear search input button is wrapped in a `<ul>` which is given a role toolbar.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/69922333/146980764-cc1c52f9-e2fd-46e8-b883-85461603b072.png">

**Expected:**
The clear search input button should be given a role as presentation.
**User Impact:**
Screenreader users will get confused if the role is not correctly defined.

MAS Reference:
MAS 4.1.2 – Name, Role, Value

**Comment by Raghu-addepalli** [comment] 2021-12-22 09:20
GitHub Tags:#A11yMAS;WCAG4.1.2;A11ySev2;#A11yTCS;#VisualStudioCode-Win32-Apr2021;#Visual Studio Code Client;

**Comment by rzhao271** [comment] 2021-12-27 23:31
Usually, the toolbar designation makes sense because it indicates to the user that they are focused within an action bar, and that they must use the left and right arrows to navigate the buttons. An example of that case is in the keyboard shortcuts editor (accessible via `Ctrl+K Ctrl+S`).
For this issue, there is only one item in the action bar/toolbar. Therefore, the options I can think of are:
1. For consistency, we continue using the toolbar role on the `ul` element even when there is only one button in the toolbar, or
2. We only add the toolbar role onto the `ul` element when there is more than one action item.

Do you have any recommendation on which would be better to implement?

Also pinging @isidorn.

**Comment by isidorn** [comment] 2022-01-03 14:07
@rzhao271 I think that only option 1 makes sense. 
We heard no user negative feedback regarding this, thus I suggest to not change anything here until we do. A one element toolbar is perfectly fine and it should not be treated as a special case.

Thus closing as designed

**Closed by isidorn** 2022-01-03 14:07 UTC
Labels: bug, needs more info, accessibility, settings-editor
