### ISSUE TITLE
view latex pdf file doesn't work

### ISSUE THREAD

**Issue by tingroger** [microsoft/vscode#111442] opened 2020-11-28 14:58 UTC
after build Latex project，pdf file is created.

but when i click 'view latex pdf file' button，there is  empty.

![test tex - mywork  SSH_ 192 168 32 139  - Visual Studio Code 2020_11_28 22_56_44](https://user-images.githubusercontent.com/31399956/100518544-27293200-31cd-11eb-8b3b-d436ce9bf703.png)

**Comment by tingroger** [comment] 2020-11-28 15:02
system info:

CPUs | AMD Ryzen 7 2700X Eight-Core Processor (16 x 3693)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.93GB (5.96GB free)
Process Argv | --crash-reporter-id d9a2354e-2cc7-4ff6-a7e0-66af58cba938
Screen Reader | no
VM | 50%

extensions info;

Extension	Author (truncated)	Version
arm	dan	1.4.0
remote-containers	ms-	0.148.1
remote-ssh	ms-	0.56.0
remote-wsl	ms-	0.51.4
vscode-remote-extensionpack	ms-	0.20.0
vim	vsc	1.17.1
code-gnu-global	aus	0.2.2
vscode-markdownlint	Dav	0.37.2
code-runner	for	0.11.1
latex-workshop	Jam	8.14.0
plantuml	jeb	2.13.16
cpptools	ms-	1.1.2
markdown-preview-enhanced	shd	0.5.13

**Comment by tamuratak** [comment] 2020-11-28 23:04
Duplicate of James-Yu/LaTeX-Workshop/issues/2206

**Closed** 2020-11-29 00:40 UTC
Labels: *caused-by-extension
