### ISSUE TITLE
Code lens rendering issues are back

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110354] opened 2020-11-10 22:34 UTC
![image](https://user-images.githubusercontent.com/641685/98741565-e206a280-237a-11eb-8e15-a22430c1cb1e.png)

Switching away from the file and back again fixed it.

And did we change the font or font-size (or something) about the code lens? They look different to me.

**Comment by misolori** [comment] 2020-11-10 23:42
I think this is a duplicate of https://github.com/microsoft/vscode/issues/110332

**Closed** 2020-11-11 03:46 UTC
Labels: *duplicate
