### ISSUE TITLE
Variables are not displayed when debugging two sessions and one ends

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#113742] opened 2021-01-04 10:09 UTC
Hi,
First of all, Happy new Year! 
I submit here an issue regarding to `Variables` in Debug View.

- VSCode Version: Latest (1.52.1)
- OS Version: Win10 x64

Steps to Reproduce:

1. Launch a Debug Configuration 1 (my case is from a custom DebugAdapter, this problem occurs as well with C/C++ Extension)
2. Launch a second Debug Configuration (it can be a different type from previous one)
3. End a session (Stop or Step)
4. Second session has now focus but variables are not revealed. 

Variables are correctly displayed when switching one session to another, but they are not displayed after a session ended.
Regards.

EDIT: If you try the same steps with 3 sessions:
1. First, you will see that your current session does not display variables.
2. If you switch to the 3rd session, it will display variables associated.
3. If you switch again, it will show you variables associated.

Does this issue occur when all extensions are disabled?: N/A : Need at least one extension to debug.

EDIT2: This ""problem"" is due to `stackFrame` lost focus, which happens when debuggee stops. It can be an expected behaviour. If so, I can close this issue.

**Comment by isidorn** [comment] 2021-01-05 15:14
Happy New Year,

Yes I can reproduce this with js-debug adapter which has child sessions. The issue is that when a debug session is stopped we do not focus the stack frame, but only the session. What this means is that the variables does not display anything since a stack frame is not focused.
I acknowledge that this is a bug. And I think @connor4312 might have hit something similiar in the past

**Comment by isidorn** [comment] 2021-08-04 18:43
@yannickowow just to check if you can still reproduce this with latest vscode insiders? Since we have improved automatic switching of focus of sessions?

**Comment by yannickowow** [comment] 2021-08-04 19:41
Using
`
Version: 1.59.0-insider
Commit: 8f58c1f457bd2ddf6cf81120c450c783b6e8c01b
Date: 2021-08-04T08:40:59.207Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 4.19.0-14-amd64
`
I can still reproduce this issue. 
When a session is closed, no current session is focused. It does not show variables nor the arrow in the glyph margin.

**Comment by isidorn** [comment] 2021-08-11 10:43
@yannickowow this works just fine for me with js-debug and latest Insiders. Here's a gif where I am doing the same thing as you.
In case you can still reproduce this, can you please F1 > developer tools > sources and place a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugService.ts#L666) and let me know what you see? Since that code should handle this case exactly.

![recording (2)](https://user-images.githubusercontent.com/1926584/129012811-2ddf6b23-b89e-478a-bf84-28682c4d810e.gif)

**Comment by yannickowow** [comment] 2021-08-14 18:39
I used latest version of Insiders (and Code OSS) and it is not working.
Sadly, it reveals a new bug when I do stepping using multi session :(

For the current bug, I hope it is still the line you asked.
This breakpoint is only triggered when I close the second session and not the first one.
![image](https://user-images.githubusercontent.com/45362067/129457033-90375466-0621-45e3-9470-6c526d2bf3e3.png)

**Comment by isidorn** [comment] 2021-08-16 14:05
Now I pushed the fix for the new issue you found. It would be great if you can re-try tomorrow with vscode insiders and try to investigate more. The actual line is this one https://github.com/microsoft/vscode/blob/51c39d0df3e5f9dcb853495227a7c2f06f95b345/src/vs/workbench/contrib/debug/browser/debugService.ts#L659

This is a permalink, so the line should be definite. Just try to figure out how the focus behaves, and if the focus is properly passed to the remaining `session`. Thanks

**Comment by yannickowow** [comment] 2021-08-17 12:32
I did some testing, here is my understanding.
It looks like informations gathered from this line is correct.  However, we are setting a focus on a `session` which is not able to focus to a given stackFrame / thread couple.
I tried by getting all the objects returned by ` getStackFrameThreadAndSessionToFocus` and it behaves as we want here.

Before:
```ts
const { session } = getStackFrameThreadAndSessionToFocus(this.model, undefined, undefined, undefined, focusedSession);
this.viewModel.setFocus(undefined, undefined, session, false);

```

After:
```ts
const { session, thread, stackFrame } = getStackFrameThreadAndSessionToFocus(this.model, undefined, undefined, undefined, focusedSession);
this.viewModel.setFocus(stackFrame, thread, session, false);
```

With further testing, to display these variables we only need to focus a `stackFrame`. Focusing a `thread` is a plus.

**Comment by isidorn** [comment] 2021-08-17 13:17
@yannickowow that looks like a reasonable change. Would you like to create a PR with that change, or would you like me to push it?
Thanks a lot for a great investigation 👏

**Comment by yannickowow** [comment] 2021-08-17 16:36
I opened a PR about this change

**Comment by isidorn** [comment] 2021-08-17 18:10
Awesome. I merged it. Should be in insiders tomorrow. Let me know how it goes once you try it out with the built vs code.

**Closed** 2021-08-17 18:10 UTC
Labels: bug, needs more info, debug

**Comment by yannickowow** [comment] 2021-08-19 08:51
👍

**Comment by isidorn** [comment] 2021-08-19 08:52
Great, adding verified label.
