### ISSUE TITLE
When the `name` in the VariablesResponse is a 0-length string, this variable cannot be seen in the vscode GUI.

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#49355] opened 2018-05-07 09:26 UTC
Issue Type: <b>Bug</b>

Watch panel, variables panel and debug console can reproduce this problem.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by isidorn** [comment] 2018-05-07 16:27
Yes this is correct, currently we use the name to compute the Variable id [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L288)
Thus we filter out any varialbe without a name [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L195)

In theory we could support one variable without a name per parent however I am reluctant to make that change.

What is the actual use case of this? Since none of the users complained about this.

fyi @weinand

**Comment by actboy168** [comment] 2018-05-07 16:49
I'm sending a 0-length string, not null, so it's not without a name. I think 0-length strings are the same as other strings.

**Comment by weinand** [comment] 2018-05-07 16:52
@isidorn if chrome dev tools support this, we should too (even if it doesn‘t make a lot of sense).

**Comment by isidorn** [comment] 2018-05-08 14:03
Thanks for the feedback.
Chrome dev tools also support this.

I have pushed a fix for this.
@actboy168 it would be great if you could try this out tomorrow and let us know if the issue is fixed for you

**Closed** 2018-05-08 14:03 UTC
Labels: bug, debug

**Comment by actboy168** [comment] 2018-05-09 12:32
I try today's vscode, 0 length string variable can already be seen. But it missing a colon.
![2](https://user-images.githubusercontent.com/1836844/39814635-b0a757a0-53c7-11e8-8f1e-b3d3a88cadec.png)

The first line is a variable of 0 length string, the second line is a variable of 1 space, and the third line is a normal variable.

**Comment by isidorn** [comment] 2018-05-09 12:54
@actboy168 thanks for the quick response I have fixed this issue with c986442064 and should be in tomorrow's insiders.
