### ISSUE TITLE
Filtering the document tree

### ISSUE THREAD

**Issue by sarojmhj** [microsoft/vscode#158177] opened 2022-08-15 14:41 UTC
Type: <b>Bug</b>

Filtering the document tree not working

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.18.6-051806-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3872)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (1.06GB free)|
|Process Argv|--unity-launch --crash-reporter-id f4468a62-41b5-4d55-af24-6b7601afe675|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
copilot|Git|1.40.6471
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.22.1
material-icon-theme|PKi|4.19.0
LiveServer|rit|5.7.5
material-theme|zhu|3.15.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-08-15 14:51
Please explain "not working". Paste screenshots if necessary.

 Are you aware that until a tree folder has been expanded once its contents are not available for filtering?

**Comment by gjsjohnmurray** [comment] 2022-08-15 14:52
Also, did you see https://code.visualstudio.com/updates/v1_70#_tree-find-control from the 1.70 release notes?

**Comment by 2bit-waterkamp** [comment] 2022-08-16 08:21
Does the new feature 'Tree find control' not work recursive? It doesn't look like :-/

**Comment by Richhoef** [comment] 2022-08-16 15:12
This is a duplicate of #157986

**Closed** 2022-08-17 08:52 UTC
Labels: *duplicate
