### ISSUE TITLE
Provide method to accept a Typescript Type inlay hint

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#195287] opened 2023-10-10 18:32 UTC
It would be a tremendous timesaver to be able to convert a given typescript type inlay hint such as `:string` to actual text instead of the hint, essentially "accepting" the hint and making it part of the code.

I realize I can (and do) type over the hint, but just providing a click or hover menu would be faster and less error-prone. I seem to remember this being mentioned as a coming feature but can't find anything more about it.

**Comment by jrieken** [comment] 2023-10-11 06:33
Inlay hints support this via `InlayHint#textEdits` but TS/JS needs to adopt this

**Comment by mjbvz** [comment] 2023-11-15 23:04
Duplicate of https://github.com/microsoft/TypeScript/issues/50235

**Closed by mjbvz** 2023-11-15 23:04 UTC
