### ISSUE TITLE
Tabs and coding windows become invisible when splitting an extension info tab

### ISSUE THREAD

**Issue by xuqihang** [microsoft/vscode#76796] opened 2019-07-07 10:26 UTC
**The current possible "solution" is to reload the window.**

- VSCode Version: 1.36.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a file and get it editable
2. Search for an extension and open its info tab
3. Drag the extension info tab and split it

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-07-08 15:28
Duplicate of #76822

**Closed by mjbvz** 2019-07-08 15:28 UTC
Labels: webview
