### ISSUE TITLE
ES6 import not highlihted

### ISSUE THREAD

**Issue by John0x** [Microsoft/vscode#2838] opened 2016-02-09 12:17 UTC
Hey, there seems to be some kind of a problem with my setup and the ES6 highlighting.
I've got my jsconfig.json as the following:
`{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ]
}`

But that config file changes nothing. Whethere it's there or not, the syntax highlighting stays the same.
It looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/5455173/12916004/5f7fcade-cf2f-11e5-9c37-a41075d2ce6a.PNG)

My file structure:
![unbenannt](https://cloud.githubusercontent.com/assets/5455173/12916013/7604b15c-cf2f-11e5-97ae-f780061e3bc7.PNG)

**Comment by aeschli** [comment] 2016-02-09 13:51
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/32

**Closed by aeschli** 2016-02-09 13:51 UTC
