### ISSUE TITLE
please improve touchpad  performance on windows10

### ISSUE THREAD

**Issue by Powerful24HS** [Microsoft/vscode#38758] opened 2017-11-20 08:16 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299

In Windows 10，the touchpad has no “precision touch”，and very choppy。

**Comment by alexandrudima** [comment] 2017-11-23 16:17
Duplicate of #35191

TL;DR: It is an upstream issue and there exists a funny workaround, to resize and maximize the window.

**Closed by alexandrudima** 2017-11-23 16:18 UTC
