### ISSUE TITLE
Integrated Terminal does not work

### ISSUE THREAD

**Issue by UndiedGamer** [microsoft/vscode#133504] opened 2021-09-21 07:16 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest insiders build
- OS Version: WSL 2 Ubuntu 20.04

Steps to Reproduce:

1. Open vscode
2. Open terminal

Expected Output: terminal opens
Ouput Recieved: terminal opens but blank, takes no input neither gives any output

**Comment by gjsjohnmurray** [comment] 2021-09-21 07:44
Maybe a duplicate of #133442

**Closed** 2021-09-21 08:22 UTC
