### ISSUE TITLE
 Organize imports: exclude files via settings

### ISSUE THREAD

**Issue by no-stack-dub-sack** [Microsoft/vscode#52087] opened 2018-06-16 03:44 UTC
## Suggestion
 It would be excellent if we had the ability to disable organize imports on a per-file basis as part of the feature's settings, e.g. : 

```json
"editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.organizeImports.exclude": [
        "**/index.ts",
        "src/components/MyComponent.ts"
    ]
},
```
## Use Cases
Organize imports on save is an excellent time-saving feature, however in some rare cases, imports may need to be in a specific order for a specific file. For example, loading 3rd party CSS assets which conflict with one another in the right order in the root component of an angular or react app (which is one of my particular use-cases).

Currently, since I'm trying to maintain consistent standards throughout my project, I am keeping organize imports on, however, every time I modify a couple of particular files, I need to go to settings, turn it off, save, then turn it back on. It seems like this may be an edge use-case, since I don't see any one else suggesting this (searched open and closed issues, sorry if I missed something), but I'm sure others could also find it useful.

Thanks for considering my comments!

## Examples
This:
```js
import 'this-should-come-first.css';
import 'this-needs-to-be-loaded-last.css';
```
Sorts to this, even though the former condition needs to be true to preserve the correct styles:
```js
import 'this-needs-to-be-loaded-last.css';
import 'this-should-come-first.css';
```

**Comment by mjbvz** [comment] 2018-06-18 15:10
duplicate of #35350

(or rather of #50888 which was marked as a dup of that)

**Closed by mjbvz** 2018-06-18 15:10 UTC
Labels: javascript
