### ISSUE TITLE
Review README.md could remember position have be read

### ISSUE THREAD

**Issue by superbiger** [Microsoft/vscode#73130] opened 2019-05-01 13:55 UTC
Review README.md could remember position have be read

**Comment by gjsjohnmurray** [comment] 2019-05-01 14:19
Probably a duplicate of #27498

**Comment by RMacfarlane** [comment] 2019-05-01 16:17
Thanks @gjsjohnmurray! This does look like a duplicate of https://github.com/Microsoft/vscode/issues/27498

**Closed by RMacfarlane** 2019-05-01 16:17 UTC
