### ISSUE TITLE
Space dots display in goups

### ISSUE THREAD

**Issue by huchenme** [microsoft/vscode#90457] opened 2020-02-11 15:31 UTC
Recently my space dots are displayed in groups

![image](https://user-images.githubusercontent.com/2078389/74251008-72e61a00-4d26-11ea-82ff-cd94245b8962.png)

are there any settings I need to change to get the dots to display correctly?

**Comment by jonathanphz** [comment] 2020-02-11 15:33
I have a similar problem but also the dots are now squares. Opened VScode yesterday and saw these.

**Comment by IllusionMH** [comment] 2020-02-11 16:23
Looks like duplicate of existing issues with whitespace character renders and recent fix is for #90197

Can you reproducible it in Insiders build? https://code.visualstudio.com/insiders/

**Comment by alexdima** [comment] 2020-02-11 20:43
Yes, please check insiders, where we now render the character that is closest in width to a space and then we enforce its width.

**Closed** 2020-02-18 21:38 UTC
Labels: needs more info

**Comment by huchenme** [comment] 2020-02-25 06:18
I noticed that it only happens when using `Dank Mono` font, could the whitespace ignore the font I am using and could you help reopen the issue?

**Comment by IllusionMH** [comment] 2020-02-25 10:38
Is it still reproducible in Insiders using Dank Mono font?

**Comment by jonathanphz** [comment] 2020-02-25 13:43
I had to change the font I usually use which is M+1m.

**Comment by huchenme** [comment] 2020-02-25 13:46
Interestingly I have changed a Mac with exact same settings (using settings sync extension) and another Mac does not have this issue (not insider)
