### ISSUE TITLE
Error when new file is set to Typescript language

### ISSUE THREAD

**Issue by Macil** [microsoft/vscode#91919] opened 2020-03-02 23:49 UTC
Issue Type: <b>Bug</b>

In some or all of the Typescript projects I work on, if I create a new unsaved file and then set its language to Typescript, then "Initializing JS/TS language features" turns on and off a few times in the status bar, and then I get this error in a notification:

>The TypeScript language service died 5 times right after it got started. The service will not be restarted.

I'm not able to recreate this in an empty directory, or even a directory with a tsconfig.json and typescript npm-installed into it. I can reproduce it with these steps though:

    git clone https://github.com/StreakYC/react-draggable-list.git
    cd react-draggable-list
    yarn
    code .
    # press cmd-N to make a new file
    # set its language to TypeScript

I'm not sure what it is about the repo that triggers the error.
Maybe related to https://github.com/microsoft/vscode/issues/85547 since that issue was also about this error showing up when a new file was set to Typescript.
The Typescript features work fine for me on .ts/.tsx files as long as I don't have any file-less tabs set to Typescript.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|316, 211, 164|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.5.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
flow-for-vscode|flo|1.5.0
Go|ms-|0.13.1
vsliveshare|ms-|1.0.1653
ActiveFileInStatusBar|Ros|1.0.3

</details>

**Comment by mjbvz** [comment] 2020-03-03 01:23
Duplicate of https://github.com/microsoft/TypeScript/issues/36200

Should be fixed in VS code 1.43 (current insiders build)

**Closed by mjbvz** 2020-03-03 01:23 UTC
