### ISSUE TITLE
ALT+(key) doesn't open corresponding menu

### ISSUE THREAD

**Issue by hayleyanthony** [Microsoft/vscode#45312] opened 2018-03-08 16:05 UTC
Issue Type: <b>Bug</b>

Expected: Hold ALT and press 'F' key and the file menu pops open. ALT-E for Edit, ALT-S for Selection, etc.
Actual: Hold ALT and press 'F', nothing happens. Ditto with the rest of the menus. 

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.89GB (2.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
Go|luk|0.6.77
python|ms-|2018.1.0
cpptools|ms-|0.15.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces without extensions

**Comment by kieferrm** [comment] 2018-03-09 02:30
Thanks for reporting. 

/duplicate of #5556

**Closed** 2018-03-09 02:30 UTC
Labels: *duplicate, new release
