### ISSUE TITLE
 After splitting the editor, the copied content is incorrect 

### ISSUE THREAD

**Issue by DeepChirp** [microsoft/vscode#198587] opened 2023-11-18 11:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Windows 11 23H2 (22631.2715)

Steps to Reproduce:

1. Split editor
2. Copy text on one side
3. Paste text
![2023-11-18 191117](https://github.com/microsoft/vscode/assets/66902050/fff9499c-b7d2-4b12-9489-cfa50b4a7244)

**Comment by mjbvz** [comment] 2023-12-04 23:54
Seems like a duplicate of #194421

**Closed by mjbvz** 2023-12-04 23:54 UTC
