### ISSUE TITLE
A little weird - Horizontal scroll bar

### ISSUE THREAD

**Issue by irwan8910** [microsoft/vscode#95464] opened 2020-04-16 16:32 UTC
Issue Type: <b>Bug</b>

i dont know what to say, but horizontal scroll bar a little hard to access when i need for hurry, because of fade in and out.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.95GB (4.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
python|ms-|2020.3.71659

</details>

**Comment by ArturoDent** [comment] 2020-04-17 01:01
Duplicate of https://github.com/microsoft/vscode/issues/35454, I don't know that the suggested unofficial "fix" works anymore though.

**Closed** 2020-04-17 07:11 UTC
Labels: *duplicate
