### ISSUE TITLE
Markdown snippets constantly appearing after every space

### ISSUE THREAD

**Issue by stefanuddenberg** [Microsoft/vscode#69283] opened 2019-02-23 19:13 UTC
Every time I place a space after a word in a markdown file, an autocomplete pop-up appears reminding me of the basics of Markdown (e.g., bold, italics, etc.). Disabling `editor.quickSuggestions` for Markdown does not help with this. This is extremely distracting.

![image](https://user-images.githubusercontent.com/32106244/53290644-11bfe200-3775-11e9-88ec-7f0463ed6bd9.png)

**Comment by mjbvz** [comment] 2019-02-25 23:53
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment] 2019-02-25 23:54
Also, did you set:

```json
[markdown]": {
		"editor.quickSuggestions": true
}
```

That would enable the suggestions you are seeing

**Comment by stefanuddenberg** [comment] 2019-03-01 03:28
Currently I've explicitly set quickSuggestions to false. I have not tried the new Insiders build; I'm on version 1.31.1. Will try the insiders build.

**Comment by mjbvz** [comment] 2019-03-02 00:37
Please make sure you set the [language specific](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings) markdown setting that I shared above as well

**Comment by stefanuddenberg** [comment] 2019-03-02 01:39
Yes, as noted in the original post I tried disabling `quickSuggestions` specifically for `[markdown]`, using the syntax you also referenced (but setting it to `false`), as below:

```json
  "[markdown]": {
    "editor.quickSuggestions": false
  }
```

A clean installation of the Insider's edition works fine; disabling all of my currently installed extensions on the standard installation of VS Code also makes the problem go away. I'm trying to go through the list and disabling each extension one at a time to see what the offending extension is...

**Comment by mjbvz** [comment] 2019-03-02 02:05
Ok, closing as it sounds like this is caused by an extension

**Closed by mjbvz** 2019-03-02 02:05 UTC
Labels: markdown, needs more info

**Comment by stefanuddenberg** [comment] 2019-03-02 17:15
Problem was resolved by disabling [IntelliSense for CSS class names in HTML](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion#review-details) by [Zignd](https://marketplace.visualstudio.com/publishers/Zignd).
