### ISSUE TITLE
 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20104] opened 2017-02-07 07:32 UTC
Issue Id: <b>472cb8c2-9336-3e3b-034a-baf84dd05b24</b><br /><br />*Versions* <br />- 1.9.0<br />-  3af0e9d6b79145011a7be3970c1d4b83d69b0443<br />-  fcac9b686abe4292e69a774f61c8c4ce17768bf5<br />*Stack* <br />TypeError: Cannot read property 'length' of undefined<br />[/vs/workbench/api/node/extHostDocuments.ts#L423:33 (length)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/extHostDocuments.ts#L423:33 (length))<br />[/vs/workbench/api/node/extHostDocuments.ts#L399:19 (validatePosition)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/extHostDocuments.ts#L399:19 (validatePosition))<br />[/vs/workbench/api/node/extHostDocuments.ts#L311:19 (validateRange)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/extHostDocuments.ts#L311:19 (validateRange))<br />[/vs/workbench/api/node/extHostDocuments.ts#L289:42 (_getTextInRange)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/extHostDocuments.ts#L289:42 (_getTextInRange))<br />[/colorDecorators.ts#L80:27](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/colorDecorators.ts#L80:27)<br />    at Array.map (native)<br />[/colorDecorators.ts#L79:55](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/colorDecorators.ts#L79:55)<br />[/colorDecorators.ts#L75:18](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/colorDecorators.ts#L75:18)<br />    at process._tickCallback (internal/process/next_tick.js:103:7) <no sourcemaps><br />

**Comment by aeschli** [comment] 2017-02-21 15:01
Similar to #18293, but now I changed my the color decorator to iterate over the list of visibleTextEditors and get the document from there.

It looks like an editor holds on to a disposed document.

**Comment by aeschli** [comment] 2017-02-21 15:11
duplicate of #20867

**Closed by aeschli** 2017-02-21 15:11 UTC
Labels: error-telemetry
