### ISSUE TITLE
Boolean attributes in JSX wrapped by curly braces wrongly

### ISSUE THREAD

**Issue by jasonlimantoro** [Microsoft/vscode#47517] opened 2018-04-09 18:59 UTC
- VSCode Version: 1.22.1
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. In a react app (in a js or jsx file), type an attribute with **boolean** datatype in a JSX element
2. When the suggestions appear, press tab (just like a normal autocompletion)
3. The attribute will be automatically wrapped in a curly braces

**Expected Result**
```javascript
<Nav bsStyle="tabs" justified>
...
</Nav>
```

**Actual Result**
```javascript
<Nav bsStyle="tabs" {justified}>
...
</Nav>
```

**Animation**
![out](https://user-images.githubusercontent.com/31163334/38516923-ed7b94f8-3c6a-11e8-816c-04dbe175457b.gif)

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by mjbvz** [comment] 2018-04-09 19:56
Duplicate of #47112 / https://github.com/Microsoft/TypeScript/issues/23099

**Closed by mjbvz** 2018-04-09 19:56 UTC
Labels: *duplicate, javascript
