### ISSUE TITLE
VSCode only refactoring the first file when multiple files are moved simultaneously (typescript)

### ISSUE THREAD

**Issue by sidgo28** [microsoft/vscode#117130] opened 2021-02-20 12:57 UTC
- VS Code Version:1.53.1
- OS Version:Darwin x64 19.6.0

Steps to Reproduce:

Sample file structure:
Folder-A
Folder-A/Folder-B
Folder-A/index.ts
Folder-A/f1.ts
Folder-A/f2.ts

index.ts contents:
export * from './f1'
export * from './f2'

1. Select multiple typescript files (e.g. f1.ts and f2.ts)
2. Drag to a folder (e.g. to Folder-B)
3. The bug occurs: 
- In index.ts file, only the reference to f1.ts file is updated (reference to f2 file is unchanged)
- Relative imports inside f1.ts file are updated (e.g. additional ../ are added) but not in f2.ts file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2021-02-22 22:30
Duplicate of #105110

**Closed by mjbvz** 2021-02-22 22:30 UTC
