### ISSUE TITLE
vscode render error

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#28227] opened 2017-06-08 07:22 UTC
- VSCode Version:1.12.2
- OS Version:win32 

Steps to Reproduce:

1.openDevtool 
2.press F5 refresh vscode。

![fqyw kd1md8ylgz 77 8 fv](https://user-images.githubusercontent.com/3353702/26916777-33132146-4c5e-11e7-8c8d-9e24364d34ed.png)

**Comment by ydcoming** [comment] 2017-06-08 08:42
The reason of this bug is  that vscode creates BrowserWindow  。
webPreferences:{
backgroundThrottling: !1,
disableBlinkFeatures: "Auxclick"
}。
backgroundThrottling does not work well 。I delete it。 it works well

**Comment by bpasero** [comment] 2017-06-08 14:27
@ydcoming to be clear: the bug you see is the dropdowns are empty? do they stay empty when you open them multiple times?

**Comment by ydcoming** [comment] 2017-06-09 02:46
multiple times opened does not work well。 only first time。

**Comment by bpasero** [comment] 2017-06-09 09:18
@ydcoming how did you actually find out that `backgroundThrottling` is causing this, very good find!

Marking as duplicate of https://github.com/Microsoft/vscode/issues/25700

**Closed by bpasero** 2017-06-09 09:18 UTC
Labels: bug, needs more info
