### ISSUE TITLE
"Reveal in Sidebar" to wrong place/nothing when not refreshed

### ISSUE THREAD

**Issue by Onfealive** [Microsoft/vscode#34617] opened 2017-09-19 07:45 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.12.1
---
Steps to Reproduce:
1. Must use Git. Create new file outside VS Code (in that git).
2. Go to "Source Control" in Activity Bar, then click any created file.
3. In "Editor Group", right-click in the filename, choose "Reveal in Sidebar".
-- In Sidebar, it scroll to wrong place (may be to nothing).
4. Refresh in "Explorer" then repeat Step 3. It works normally.

Reproduces without extensions: No

**Comment by isidorn** [comment] 2017-09-21 08:47
I am following your exact steps and it works for me. I can not reproduce with latest insiders
Can you also see this issue with https://code.visualstudio.com/insiders
If yes then please describe what you are doing differently than me

![git](https://user-images.githubusercontent.com/1926584/30687000-4477f368-9eba-11e7-9951-f0b7c7faa774.gif)

**Comment by Onfealive** [comment] 2017-09-22 04:30
It looks like this

![bug](https://user-images.githubusercontent.com/18258131/30729361-29bcb840-9f89-11e7-9dae-37a76e887f87.gif)

**Comment by isidorn** [comment] 2017-09-22 09:13
I could not reproduce with latest insiders also on windows.
Closing as will not fix as I can not repro and it is not an important issue imho

**Closed by isidorn** 2017-09-22 09:13 UTC
Labels: explorer-files, needs more info
