### ISSUE TITLE
Double-clicking on icon doesn't close window

### ISSUE THREAD

**Issue by erik-schmitt** [Microsoft/vscode#61087] opened 2018-10-16 21:42 UTC
Issue Type: <b>Bug</b>

Double-click on the VS Code icon in upper left corner. The window resizes.

The expected behavior is that the window should close.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.96GB (6.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
crane|Hvy|0.3.8

</details>

**Comment by Tyriar** [comment] 2018-10-16 22:57
I can repro, looks like this must have regressed recently as it definitely worked in the initial version I tested.

**Comment by AlexBillon07** [comment] 2018-10-17 11:56
Double click on the system menu active the default action of the menu. I think this changed in the 1.27 or 1.28

The defaut action has been changed and as far as I can see, it is not possible to configure it in the settings.

![SystemMenu1.28.1](https://user-images.githubusercontent.com/33461310/47084632-57dbc680-d214-11e8-9957-f826aea32d17.png)


VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-edifact|DAX|0.4.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
reg|ion|0.0.2
mssql|ms-|1.4.0
PowerShell|ms-|1.9.0
vsc-jsonsnippets|wmo|0.1.4

</details>

**Comment by sbatten** [comment] 2018-10-18 17:11
this is a duplicate of #58199

**Closed by sbatten** 2018-10-18 17:11 UTC
Labels: bug, workbench-title

**Comment by ltrzesniewski** [comment] 2018-10-18 22:55
@sbatten may I honestly ask how much more duplicate issues you need before you realize that *this is a bug*?

There is nothing "modern" in breaking user expectations, or so I hope.
