### ISSUE TITLE
Implement multiLinePasteWarning in VSCode terminal, similar to Windows Terminal behavior

### ISSUE THREAD

**Issue by cruscio** [microsoft/vscode#122683] opened 2021-04-29 18:13 UTC
Please implement a [multiLinePasteWarning](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#warn-when-the-text-to-paste-contains-multiple-lines) for the VSCode integrated terminal, similar to Windows Terminal.

![image](https://user-images.githubusercontent.com/30699280/116595961-e0fa0b00-a8f1-11eb-883b-14bb45a8343c.png)

More times than I care to admit, I've accidentally pasted bad text into a VSCode integrated terminal session - often due to either the wrong panel being in focus, or fat fingering an unintended right-mouse-click at a bad place/time.

VSCode workspaces have replaced 99% of my standalone terminal usage these days. Having that safety net is _by far_ the top of my missing-features wish list.

(... and I was surprised to come up empty handed when searching for an existing setting or open issue.)

**Comment by Tyriar** [comment] 2021-06-30 12:27
I think it would be good to have an opt-in setting for this as I've accidentally pasted the wrong thing as well which could be destructive. Opening up to PRs

**Comment by slidoooor** [comment] 2022-01-24 12:29
hi, can I work on this issue? 

> 我认为最好有一个选择加入设置，因为我不小心粘贴了错误的东西，这可能是破坏性的。向 PR 开放

**Comment by cruscio** [comment] 2022-01-24 14:49
Hey @slidoooor - I haven't done any work on this yet. If you're interested, please do!

**Comment by slidoooor** [comment] 2022-01-27 03:03
> Hey @slidoooor - I haven't done any work on this yet. If you're interested, please do!

okay，I will try to solve this problem :)

**Comment by slidoooor** [comment] 2022-01-27 15:21
![image](https://user-images.githubusercontent.com/17105034/151388196-8779fb54-6883-4b4c-b664-6e7d358ce6c6.png)

@cruscio @Tyriar  How do you all feel? I think the text is a bit crowded and if we want to display the clipboard it will be even more crowded

**Comment by slidoooor** [comment] 2022-01-27 15:25
![image](https://user-images.githubusercontent.com/17105034/151389326-35eb1760-a9c5-4020-bcfc-fb21fbac963c.png)

@cruscio  @Tyriar  How do you all feel? I think the text is a bit crowded and if we want to display the clipboard it will be even more crowded

**Comment by Tyriar** [comment] 2022-01-27 15:32
@misolori any opinions here for how to present this warning when pasting multiple lines into the terminal? It'll probably be opt-in and ideally I think it would have a preview of the first 2 lines.

**Comment by slidoooor** [comment] 2022-01-27 16:49
Currently I am handling this situation by making a judgment before we execute paste:
https://github.com/microsoft/vscode/blob/913639f42aaf268f6b2acc6cbe5701eee3720d7b/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L2031
But it's not easy to get to the clipboard here

We can also handle it here and can easily get the clipboard:
https://github.com/microsoft/vscode/blob/913639f42aaf268f6b2acc6cbe5701eee3720d7b/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L964
But this means that all pastes in the terminal will be detected (e.g right click behavior paste)

**Comment by Tyriar** [comment] 2022-01-27 16:56
> But this means that all pastes in the terminal will be detected (e.g right click behavior paste)

Not sure what the right behavior is here, does Windows Terminal show it on right click as well?

**Comment by slidoooor** [comment] 2022-01-27 17:02
> > But this means that all pastes in the terminal will be detected (e.g right click behavior paste)
> 
> Not sure what the right behavior is here, does Windows Terminal show it on right click as well?

I tried it and it does prompt

**Comment by slidoooor** [comment] 2022-01-27 17:03
Perhaps we could have three options, prompt for a brief message, prompt for the first two lines, and not prompt at all

**Comment by misolori** [comment] 2022-01-27 17:32
Not sure what the right text should be, here's another example from iTerm:

<img width="300" alt="CleanShot 2022-01-27 at 08 56 21@2x" src="https://user-images.githubusercontent.com/35271042/151406342-3cb0adfb-ae0e-4de6-827a-8de9be838e4e.png">

I do like how simple the "confirm on delete" dialog looks with the preview:

<img width="316" alt="CleanShot 2022-01-27 at 09 12 03@2x" src="https://user-images.githubusercontent.com/35271042/151409169-b41bffd5-dc56-493d-aff4-83c025ce815b.png">

<hr>

How about something like:

> **Are you sure you want to paste the following xx lines to the terminal?**
> `line one`
> `line two`...
> This may result in the unexpected execution of commands
> [Paste] [Cancel]

**Comment by Tyriar** [comment] 2022-01-27 18:00
> **Are you sure you want to paste the following xx lines to the terminal?**
> `line one`
> `line two`...
> This may result in the unexpected execution of commands
> [Paste] [Cancel]

Looks great 👍, @slidoooor let's go with that. We could enable it by default with the don't ask me again checkbox to change the setting for you.

**Comment by slidoooor** [comment] 2022-01-30 08:17
![image](https://user-images.githubusercontent.com/17105034/151691964-b145cb23-d89a-465b-81e3-1a888684e0c4.png)

@Tyriar @misolori  Hi!, I committed the latest changes and it currently looks like this.
I've only done it in the 'paste', not deal wit 'pasteSelection', which I assume has the expected behavior in general? Do we need to process both?

Another small problem is that I am handling the lines by separator, and if the user's pasteboard has only two lines, but each line is very long, there will also be a lot of content displayed, e.g:

![image](https://user-images.githubusercontent.com/17105034/151692103-38570189-8fbc-48d0-8d90-8717af704b2d.png)

**Closed** 2022-02-01 15:03 UTC
Labels: help wanted, feature-request, terminal

**Comment by yume-chan** [comment] 2022-02-08 09:14
In my test it doesn't care about the current [Paste Bracketing](https://cirw.in/blog/bracketed-paste) state. It should be fine (no warning) if current program can handle multi-line paste.

**Comment by Tyriar** [comment] 2022-02-08 15:52
@yume-chan 👍 created https://github.com/microsoft/vscode/issues/142525
