### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Abhay123png** [microsoft/vscode#94868] opened 2020-04-10 05:56 UTC
Issue Type: <b>Bug</b>

Yesterday I opended vs code and got this error + command code-runner.run could not found , so I cannot run codes . These both errors on the same time 
Howto fix it?

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:30:48.287Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B980 @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|1.88GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment] 2020-04-10 06:09
See #94829 and your #94807. For the latter please respond to my questions at https://github.com/microsoft/vscode/issues/94807#issuecomment-611861903

**Comment by RMacfarlane** [comment] 2020-04-10 19:20
Duplicate of https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765, see https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

**Closed by RMacfarlane** 2020-04-10 19:20 UTC
Labels: needs more info, new release
