### ISSUE TITLE
iPadOS: Korean input isn't combined properly

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode#114602] opened 2021-01-19 23:59 UTC
OS Version: iPadOS 14.3
Version: 1.53.0-insider
Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
Date: 2021-01-19T06:08:51.817Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

Originally reported in code-server: https://github.com/cdr/code-server/issues/1314

## Reproduce
1. Add Korean keyboard under General > Keyboard > Keyboards > Add New Keyboard > Korean
2. Open code-server 
3. Open file (e.g. markdown file)
4. Switch to Korean keyboard  
5. Start typing: ㄱㅏ 

## Expected
가

It works properly on VSCode + macOS.

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

## Actual
ㄱ가

But not on Codespaces/code-server + macOS

https://user-images.githubusercontent.com/3806031/105103759-58f0a380-5a6e-11eb-892c-ccf84e63b6c1.MP4

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2021-01-22 19:22
I could not reproduce on Safari:


https://user-images.githubusercontent.com/5047891/105535686-76807000-5cef-11eb-9df6-cc8a68ba9fa8.mp4

**Comment by jsjoeio** [comment] 2021-01-22 21:08
@alexdima I was using Chrome (shouldn't matter though, right?)

Is there anything more I can do to help.

**Comment by bummoblizard** [comment] 2021-06-17 18:06
I am having the same problem when using mobile Safari.

**Comment by dhguswns23** [comment] 2021-07-20 13:07
Same with me. Any progress here?

**Comment by alexdima** [comment] 2021-11-29 22:39
I am fairly confident that this was caused by us writing to the textarea (changing its value) during the `compositionstart` event. In other words, I think the fix for #138095 will also fix this issue. I would be very thankful if you could verify that the issue no longer reproduces using tomorrow's [Insiders](https://code.visualstudio.com/insiders/) that should be released in 9-10 hrs.

**Closed by alexdima** 2021-11-29 22:39 UTC
Labels: bug, macos, editor-input-IME, ios-ipados

**Comment by jsjoeio** [comment] 2021-11-30 21:28
> I would be very thankful if you could verify that the issue no longer reproduces using tomorrow's Insiders that should be released in 9-10 hrs.

Just confirmed, it is working as expected on https://insiders.vscode.dev

## Video

https://user-images.githubusercontent.com/3806031/144130880-08b55b11-3c85-4c3d-8f95-740ebbf83ed9.MP4

Thanks for fixing this!

**Comment by alexdima** [comment] 2021-12-01 10:00
Thank you very much for verifying!
