### ISSUE TITLE
VS Code delays file save operation

### ISSUE THREAD

**Issue by engina** [Microsoft/vscode#11338] opened 2016-08-31 19:20 UTC
- VSCode Version: 1.4.0
- OS Version:  Mac 10.11.6

## Steps to Reproduce:

1. Create file watcher via (gaze, chokidar) on a source file that is open in VS Code and run it.
2. Let the document be idle in VS Code for a few minutes. Important.
3. Save the document.

## Expected:
File watcher to notice the file change immediately.

## Actual:
File changes are noticed a few seconds later (up to 10 seconds). But if you make subsequent changes, they are noticed almost immediately.

At first I thought it was gaze's fault, then I tried chokidar, then I tried chokidar in polling mode, they all behaved the same way. But when I `touch`ed the files they are always immediately noticed.

Which means...

The problem seems to be VS Code delaying the save operation. I've looked through whole code path and couldn't find the culprit myself unfortunately.

## Why is it important?
Because when you are trying to see the result of automated tests and they are delayed, it is really annoying.

**Comment by bpasero** [comment] 2016-09-01 04:32
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-09-06 05:38
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-09-06 05:38 UTC
Labels: needs more info, workbench

**Comment by Flame2057** [comment] 2017-05-14 21:32
Same
