### ISSUE TITLE
Do not change touchbar buttons when stepping

### ISSUE THREAD

**Issue by weimarcoro** [microsoft/vscode#54084] opened 2018-07-11 17:03 UTC
Issue Type: <b>Feature Request</b>

Whe you are debuggin code and you are trying to step over many times (and more or less fast) like you are pressing the normal F10 key in a normal keyboard, the status of the touch bar display sometimes changes the possitions of the debug options which in many times caused me to stop and restart the application accidentally (because the options changed positions. Restart option instead of Step Over in this case).
It would be awesome to provide a fixed debugging display for the touch bar when performing a debug so you are safe to step over fast and many times without restarting the app by accident. if not, a way to configure the touch bar behavior to do just that, fix the debug options. 
I guess the touch bar options change because of the context and since the debug context changes a lot, it make sense to change the options but keep in mind that in a normal keyboard, we have all the options as FX options and we are safe to step over many times pressing F10 for example. I just would like the same freedom in my Touch Bar since I don't have FX buttons.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

**Comment by isidorn** [comment] 2018-07-17 15:14
So the issue is that the order of the action in the mac touch bar changes. We could fix this by showing the invalid actions as disabled (instead of not showing them).
[Code pointer](https://github.com/Microsoft/vscode/blob/4e975a1bebd8e346a511339c8d177d8bf35a945a/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L244)
We would use the `precondition` instead of the `when` clause.

Not sure what other apps are doing and what is standrad behavior. Let's leave this open for now to gather more feedback

fyi @bpasero @weinand

**Comment by bpasero** [comment] 2018-07-18 04:58
@isidorn @weimarcoro I cannot reproduce this behaviour, but I am also not having a macbook with native touch bar (I am using the touchbar simulator). Is this while debugging TypeScript?

**Comment by weimarcoro** [comment] 2018-07-18 13:03
Hi @bpasero I can easily reproduce this behavior by debugging c# code. For example, if you have a function that takes 2 or more seconds to return data (EF long query could be) you can see the buttons at the touch bar changing while waiting for the data to return. Step over and other buttons disappear and Restart button appears at the position of the other buttons which leads me to "Restart" accidentally the application.

**Comment by weimarcoro** [comment] 2018-07-18 13:18
![afterlongrunning](https://user-images.githubusercontent.com/12765172/42884071-5d761546-8a6b-11e8-8d6b-67e8176789ac.jpg)
![whilelongrunning](https://user-images.githubusercontent.com/12765172/42884073-5dbc9ea8-8a6b-11e8-8ae8-cb6420fe2f66.jpg)
![beforelongrunning](https://user-images.githubusercontent.com/12765172/42884072-5d9a61bc-8a6b-11e8-9d20-90f38dc2c87b.jpg)

**Comment by isidorn** [comment] 2018-07-25 08:11
@billba thanks, yeah lets close that one, this one I prefer the description

**Comment by bpasero** [comment] 2018-08-06 13:39
I am using a bunch of debug provided context keys, so maybe I need different keys to support this scenario better. The code starts from here:

https://github.com/Microsoft/vscode/blob/eec79d70207c5cf052b2ead3c055c14e788d8642/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L456

**Comment by isidorn** [comment] 2018-08-13 13:43
A PR that fixes this is more than welcome.
Someone with a mac touch bar could help here.
@bpasero already provided a code pointer

**Comment by chamons** [comment] 2019-05-15 19:18
@isidorn This is the issue I showed you in person.

**Comment by isidorn** [comment] 2019-05-15 19:51
@chamons thanks. Let me assign to May to investigate if we can fix this.

**Comment by isidorn** [comment] 2019-06-25 14:54
Verifier:
Use a macbook with a new touch bar, or use a [touchbar simulator](https://sindresorhus.com/touch-bar-simulator/) - the simulator works great!
Start debugging, verify that the location of the step buttons on the touch bar does not change as you are stepping through code. And that you can click on the step over button like crazy.

**Comment by RMacfarlane** [comment] 2019-06-25 19:01
For some reason, I'm now seeing the actions printed as text instead of icons on VS Code insiders:
![20190625_115644](https://user-images.githubusercontent.com/3672607/60125494-c1678980-9740-11e9-9e7e-f522dcdbb090.jpg)
I've looked through my settings to try to find what would be causing this and haven't found anything, they appear as icons on stable.

**Comment by isidorn** [comment] 2019-06-26 12:15
@RMacfarlane  Great catch. This happened due to the move from `electron-browser` to `browser` and we forgot to update the import path.

**Closed** 2019-06-26 12:16 UTC
Labels: debug, feature-request, help wanted, verification-found, verification-needed, workbench-touchbar

**Comment by weinand** [comment] 2019-06-27 10:38
Icons are now showing up again!
