### ISSUE TITLE
Terminal text shifts to the left when scrolling up

### ISSUE THREAD

**Issue by NickolasAcosta** [Microsoft/vscode#7564] opened 2016-06-11 20:52 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 10 Pro Insider Preview build 14352.rs1_Release.160522-1930

[I am using angular-cli's ng--help function for this case.](https://github.com/angular/angular-cli)

Steps to Reproduce:

1. Launch VS Code
2. Open Terminal
3. ls
4. dir
5. ng --help
6. Scroll up

Result:  All the text in the terminal shifts to the left, and the terminal becomes stuck that way.  In my gif, i somehow got it back, but once i scrolled up it broke again.

![gif](http://g.recordit.co/5A76COPv4B.gif)

Here is my dev tools console at startup.  It does not change when this error occurs.
```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] Spell and Grammar checker active...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] .NET Core Debugger tools already installed
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] rejected promise not handled with 1 second
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:118 Unexpected token /: SyntaxError: Unexpected token /
    at Object.parse (native)
    at C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\out\assets.js:35:42
    at tryCatcher (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\NickA\.vscode\extensions\ms-vscode.csharp-1.0.11\node_modules\bluebird\js\main\async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by Tyriar** [comment] 2016-06-11 22:02
Duplicate of https://github.com/Microsoft/vscode/issues/6738

**Closed by Tyriar** 2016-06-11 22:02 UTC
