### ISSUE TITLE
Problem matcher does not work well with text wrapping in integrated terminal

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#109367] opened 2020-10-26 11:06 UTC
When using a task to build c++ code and using a problem matcher to parse the output, the line wrapping messes up the captured output.

Example:
```
c:\some\long\path\to\a\file\src\unittest.cpp(436,3): error C2065: 'asdf': undeclared identifier [c:\project\some_project.vcxproj]
```

Normally the problem matcher should capture `'asdf': undeclared identifier [c:\project\some_project.vcxproj]`.

But if the text wraps after `'asdf': undeclared identifier [c:\proje` then it will only capture that part.

If I remember correctly this was not an issue a few releases ago.

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment] 2020-10-26 15:43
Looks like a duplicate of https://github.com/microsoft/vscode/issues/85839

**Closed by alexr00** 2020-10-26 15:43 UTC
