### ISSUE TITLE
The width of the terminal can overflow out of the panel for proportional fonts

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#51945] opened 2018-06-15 00:20 UTC
Issue Type: <b>Bug</b>

there will be more out of the right side of the panel;
Like the place marked with an arrow in the screenshot below.
The situation still appears when i disable all extensions.

![5](https://user-images.githubusercontent.com/13393959/41444195-1ec5aec6-7074-11e8-89b9-ffde13c8c478.png)

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:17:21.496Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.69GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
dart-code|Dar|2.14.0
flutter|Dar|2.14.0
docs-markdown|doc|0.0.3
gitlens|eam|8.3.5
code-runner|for|0.9.3
Kotlin|mat|1.6.0
vscode-cosmosdb|ms-|0.7.2
vscode-language-pack-zh-hans|MS-|1.24.3
python|ms-|2018.5.0
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.82
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.42
vetur|oct|0.12.5
java|red|0.26.0
vscode-yaml|red|0.0.13
rust|rus|0.4.5
vscode-arduino|vsc|0.2.16
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-react-native|vsm|0.6.11
debug|web|0.22.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment] 2018-06-15 13:54
Duplicate https://github.com/Microsoft/vscode/issues/51479

**Comment by yume-chan** [comment] 2018-06-19 08:21
@Tyriar I want this one to be reopened because I believe this one is quite different from others.

1. It's using canvas renderer, while others mainly happen to dom renderer.
2. There is no characters being hidden or clipped or overflowed like others, the canvas itself is too wild for the container.

I also encountered this issue today and I believe it's relevant with language or font rendering, because I forgot to installing the font for my synced settings.

**Comment by Tyriar** [comment] 2018-06-19 20:07
@yume-chan oh really 😕? Can you show me a screenshot of the DOM structure inside the terminal element?

**Comment by yume-chan** [comment] 2018-06-20 01:57
![image](https://user-images.githubusercontent.com/1330321/41632952-f0bb2282-746e-11e8-8bb3-9c2c412b94a8.png)

@Tyriar To reproduce:

1. Put `"terminal.integrated.fontFamily": "Some Random Font"` into settings
2. Create a new terminal.

It might be my bad because when I do this intentionally, Code warns me to use a monospace font. But Code only does it after settings has been modified, so in my previous comment, I use OneDrive to sync my settings, and I forget to install the font, and Code didn't say anything. 

So I think there are two issues:

1. In any circumstances Code should correctly calculate the width of terminal.
2. Code should warn about non-monospace font every time (and allow a user to "Don't ask again", currently it not).

**Comment by Tyriar** [comment] 2018-06-20 08:06
Hmm, well it shouldn't happen still for non-monospace fonts as you can see the `i` is being sized to the `W`'s size. Better warning is captured in https://github.com/Microsoft/vscode/issues/45226

**Comment by JackDeMeyers** [comment] 2018-06-21 02:04
Just wanted to say that this started happening to me in VS Code Insiders a few days ago both on a few PCs. I haven't modified any settings involving fonts.

**Comment by Aculeo** [comment] 2018-07-09 07:50
I am seeing this issue since last update (V1.25) - no setting changes either.

![grafik](https://user-images.githubusercontent.com/3977620/42437445-6d115822-835d-11e8-8bd9-46fbe1df3956.png)

**Comment by Tyriar** [comment] 2018-07-09 12:50
Could you check the latest insiders to see if it's still happening? I think this is a duplicate of https://github.com/Microsoft/vscode/issues/51479

**Comment by czfadmin** [comment] 2018-07-09 13:19
This problem  no longer occurs in the latest insiders  。👍@Tyriar

**Closed** 2018-07-09 16:39 UTC
Labels: bug, help wanted, integrated-terminal, needs more info
