### ISSUE TITLE
Editor scroll bar has its bottom aligned to mouse the first time the mouse is moved on long files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25872] opened 2017-05-04 04:50 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T15:02:36.792Z)
- OS Version: Linux x64 4.10.0-20-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

![out](https://cloud.githubusercontent.com/assets/2193314/25690872/6d0c0cda-304a-11e7-87cb-6b0b7635b7e9.gif)

The file opened is 2378 lines long: https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js

**Comment by alexandrudima** [comment] 2017-06-06 10:47
Duplicate of #6710

**Closed by alexandrudima** 2017-06-06 10:47 UTC
Labels: bug
