### ISSUE TITLE
Slow startup / crashes - unusable

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#335] opened 2015-11-20 10:36 UTC
Hello,

since the release of VS Code v0.10.1 I cannot use it anymore - yes, I already tried to reinstall it.
It takes minutes to start and all I'm getting is the following:
![unbenannt](https://cloud.githubusercontent.com/assets/7961978/11297744/c5accec8-8f7a-11e5-8bc3-632a0873b1f2.PNG)

I am using Windows 10 Pro on my Microsoft Surface Pro 3.

**Comment by tominon** [comment] 2015-11-20 10:55
Duplicate of #160

**Comment by Morgy93** [comment] 2015-11-20 11:02
@tominon I already went through that issue, but it's not that much of a duplicate. Everyone is having issues related to php and stuff, while I just try to open up the Editor via the code.exe / desktop icon.

**Comment by bpasero** [comment] 2015-11-20 20:46
@Morgy93 can you run code.exe from the program files directory with the "--verbose" flag and attach the output you are seeing?

**Comment by Morgy93** [comment] 2015-11-20 21:17
@bpasero I hope I didn't get it wrong. This is what I put into the "Target:" property of the icon, but there is no extra output on startup.
![unbenannt](https://cloud.githubusercontent.com/assets/7961978/11312024/b514d070-8fd3-11e5-82e0-48b8a183bb24.PNG)
Even if I go for View -> Toggle Output there's just "Output for 'Git'" with lots of empty space.

**Comment by bpasero** [comment] 2015-11-20 21:18
@Morgy93 sry, I meant to say that you try from the windows command prompt.

**Comment by Morgy93** [comment] 2015-11-20 22:20
@bpasero Alright, here we go:
```
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code\resources\app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined }
Lifecycle#unload() 1
```
Here it just takes forever for Code to start .. then the "crash" happens:
```
[VS Code]: detected unresponsive
```
![unbenannt](https://cloud.githubusercontent.com/assets/7961978/11313335/6b0a13d8-8fdc-11e5-9899-6c3c183d3e9f.PNG)
And if I go for "Keep Waiting" or just do nothing, this gets added:
```
IPC#vscode-workbenchLoaded
```

And Code is ready for use now it seems .. after like two to three minutes of waiting.

For the easiness, full log:
```
C:\Users\Thomas>"C:\Program Files (x86)\Microsoft VS Code\code.exe" --verbose

C:\Users\Thomas>
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code\resources\app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined }
Lifecycle#unload() 1
[VS Code]: detected unresponsive
IPC#vscode-workbenchLoaded
```

**Comment by bpasero** [comment] 2015-11-21 07:33
@Morgy93 can you try starting code.exe -n (will open an empty workbench without folder) to see if it changes anything?

**Comment by Morgy93** [comment] 2015-11-21 12:09
@bpasero Well, it still took minutes to show up while using around 30% of my CPU, but at least I didn't got the "crash" message and were able to use it right away.

**Comment by bpasero** [comment] 2015-11-21 13:45
@Morgy93 any extensions installed? Otherwise I am totally clueless...

**Comment by Morgy93** [comment] 2015-11-21 15:36
@bpasero Nope, I just made the automatic update from my previous version to the v0.10.1 which immediately caused this issue. Like I said I already reinstalled it, but nothing changed. I also don't know what else to do. Anything else I could provide to resolve this issue?

**Comment by bpasero** [comment] 2015-11-23 14:26
@Morgy93 maybe use process explorer to analyze which process within code.exe actually causes the slowness, we start with more then one process and it would be interesting if one of them is spiking and consuming most startup time.

**Comment by bpasero** [comment] 2015-11-23 14:31
Also can you try running "code.exe --disable-gpu" from a command prompt from the installation folder of code to see if it makes any difference?

**Comment by Morgy93** [comment] 2015-11-23 14:54
@bpasero Sadly --disable-gpu doesn't help.
Maybe here's something that helps? (Phew, a lot of parameters..)
![vscode](https://cloud.githubusercontent.com/assets/7961978/11339524/3019958a-91fa-11e5-9969-93a65860f60d.PNG)

I'll have a look at this process explorer thing in the meanwhile..

**Comment by bpasero** [comment] 2015-11-23 15:38
@Morgy93 yes please, there are processes within the one that is selected in your screen shot that could cause that one to take so long.

**Comment by Morgy93** [comment] 2015-11-23 16:38
@bpasero I took this one: https://technet.microsoft.com/de-de/sysinternals/processexplorer.aspx
But the output is most likely the same:

![vscode2](https://cloud.githubusercontent.com/assets/7961978/11342492/fad06c06-9207-11e5-87af-3d47384bcb5b.PNG)

```
"C:\Program Files (x86)\Microsoft VS Code\code.exe" --type=renderer --no-sandbox --lang=de --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --enable-pinch --device-scale-factor=1 --enable-delegated-renderer --num-raster-threads=2 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --channel="11656.1.1109162074\190479848" /prefetch:673131151
```

![vscode3](https://cloud.githubusercontent.com/assets/7961978/11342649/b6d45da4-9208-11e5-8d7e-68a06cdc4385.PNG)

Don't really know what's important for you within this tool, so please be a bit more precise. :)

**Comment by bpasero** [comment] 2015-11-23 16:49
@Morgy93 I am using process explorer and it allows to group processes hierarchically and then I can expand the renderer process of code.exe to see spawned children within:

![image](https://cloud.githubusercontent.com/assets/900690/11343051/904405f2-920a-11e5-84f3-9578a1cb9941.png)

Can you use the same tool and then see if any of the processes within the renderer is busy or actually really the renderer?

**Comment by Morgy93** [comment] 2015-11-23 20:43
@bpasero Actually that's just what I did, but there is no other process before the editor is fully loaded.
Have a look at the comparison:

I am starting VS Code and wait for the UI to load a bit (nothing changed till here):
![screenshot- 21](https://cloud.githubusercontent.com/assets/7961978/11349000/0a568594-922a-11e5-8add-0aae1ddefae7.jpg)

Then suddenly I get the no response error message and still nothing changed:
![screenshot- 22](https://cloud.githubusercontent.com/assets/7961978/11349011/25026020-922a-11e5-953e-4c16cf307d41.jpg)

Just after waiting for a little longer, the editor is fully loaded and two new processes spawned within the one which was consuming the cpu power.
![screenshot- 23](https://cloud.githubusercontent.com/assets/7961978/11349050/667ec1f6-922a-11e5-87d5-d9002bed0396.jpg)

That's pretty much everything that happens.
Maybe I provide Teamviewer access or something similar to you and you play around with it for yourself? I don't mind struggling around with it like that, but maybe that boosts the process of solving the problem. :)

**Comment by Morgy93** [comment] 2015-11-23 21:15
Just to let you know:
I just installed version 0.9.2 from this source https://az764295.vo.msecnd.net/public/0.9.2/VSCodeSetup.exe over my existing installation and VS Code started up fast again.
Now I installed the latest release from the official website over the 0.9.2 installation and .. see.. it's slow again.
So I assume that there are code changes between 0.9.2 and 0.10.1 which cause this issue.

**Comment by bpasero** [comment] 2015-11-24 04:54
@Morgy93 good insights, thanks. Especially good to know that 0.9.2 loads fast for you. There are two things that changed for the 0.10.x release: Lots of code changes on our end but also an update to the cross platform framework (Electron). 

First of all we need to understand if this is caused by code changes or by Electron. The easiest to start with is to set you up to run Code from its sources so that we can tweak changes and rapidly see if it helps.

Can you follow https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source and when you launch code see if you see the same issue of slow startup?

**Comment by bpasero** [comment] 2015-11-26 06:18
@Morgy93 another thought I had was if - once VS Code is up and running - you could see if reloading the application is also slow. For that you can just trigger View | Command Palette | Reload Window.

If that action turns out to be as slow, we have a chance to run a profiler to see where the time is spent. For that - before reloading - run Help | Toggle Developer Tools, click Profiles, then press the Start button and run the reload action. After that, press the Stop button. You should get a list of function calls and their timings. You can export this report from the little "Save" button next to "Profile 1" on the left.

![image](https://cloud.githubusercontent.com/assets/900690/11416436/d997ae5c-940d-11e5-976b-8c449472eb22.png)

**Comment by Morgy93** [comment] 2015-11-26 09:22
By the way I just updated to version 0.10.2 but the issue remains. But from now on I will most likely rely on that version, if no other instructions are given.

@bpasero I'll try the build and run from source at the weekend. (If needed)
The Reload Window option is also slow, cpu consuming and causes the "does not respond" error message.
Here's the Profile dump:
[CPU-20151126T100506.txt](https://github.com/Microsoft/vscode/files/44764/CPU-20151126T100506.txt) (Original filetype was .cpuprofile)
[code.txt] (https://github.com/Microsoft/vscode/files/44784/code.txt)(Original filetype was .dmp)

And some picture: 
![vscode4](https://cloud.githubusercontent.com/assets/7961978/11419137/aec7c230-9425-11e5-97b1-8f441068d6b7.PNG)

**Closed** 2015-11-26 10:09 UTC
Labels: bug

**Comment by bpasero** [comment] 2015-11-26 11:53
@Morgy93 thanks a lot for the profile, this helped identify the issue and in fact many more users are hit. This likely qualifies for an update that we will push out to all users but we need some verification first. So I have a couple of asks for you:

1.) can you download the following build of VS Code (standalone zip, no installer) and open Code.exe to see if performance is better. I uploaded the zip to my onedrive: http://1drv.ms/1NQvCOu

2.) if performance is better: close the instance and open `\resources\app\out\vs\workbench\electron-browser\index.html` in that zip and make the following console.log additions after this line:

```javascript
process.env['VSCODE_SHARED_IPC_HOOK'] = configuration.sharedIPCHandle;

console.log('URL length: ' + window.document.URL.length);
console.log(JSON.stringify(configuration, null, '\t'));
```

Then save the file and run Code again from the zip and hit Help | Toggle Developer Tools. You should then see potentially lots of output from the log statements. I would need the entire log, since it may contain user data it should probably be not attached to this issue but you can send it via mail (benjpas@microsoft.com).

**Comment by Morgy93** [comment] 2015-11-26 12:40
@bpasero Performance is good again - log sent via mail.

**Comment by bpasero** [comment] 2015-11-26 17:40
To people hitting this issue: We might not be able to release a new version until next week. **But there is a workaround**: 

If you can start Code eventually:
* select File | Open Recent | Clear Items
* restart and things should be fast again

If you cannot start Code:
* close Code
* locate storage.json (see https://code.visualstudio.com/Docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates for how to find it)
* delete the file or rename it
* start Code

Sorry for the trouble :heart:

**Comment by slayerxj** [comment] 2015-12-02 04:43
Hi, I can still reproduce the issue in version 0.10.3.
When I open a JSON file which size is about 4M, the VS code stops responding. It used to be OK before 0.10.1.

**Comment by bpasero** [comment] 2015-12-02 06:38
@slayerxj that seems like a different issue that should get filed, please do that!

**Comment by slayerxj** [comment] 2015-12-04 04:19
@bpasero Sorry, I thought they were same because the first time I met this issue, that JSON file was supposed to be shown at startup. So I did experience slow startup / crashes :) And now after reading the discussions I realized they're different.
