### ISSUE TITLE
Custom Default Terminal doesn't work

### ISSUE THREAD

**Issue by wormple12** [microsoft/vscode#132975] opened 2021-09-13 09:27 UTC
Issue Type: <b>Bug</b>

Since a recent update (not sure which one), my default terminal for VSC has reset to Powershell. I have returned the setting for default terminal to Git Bash instead, but it only seems to be in effect in a few parts of the application, while it still uses Powershell in others:

- Whenever the application opens, the terminal opens in Powershell no matter what, ignoring both my default terminal setting as well as what terminal I left open when I exited the application last.

- Right-clicking a project and selecting "Open in Integrated Terminal" always opens in Powershell, while opening a terminal with Terminal --> New Terminal opens correctly with Bash.

- Closing the terminal and reopening it with “Ctrl+`” opens correctly with Bash, but I have to do this every time I run VSC.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.59GB free)|
|Process Argv|--crash-reporter-id b599e879-8764-4151-8300-247b977d195a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.4
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.15
vscode-scss-formatter|sib|2.2.4
rewrap|stk|1.14.0
unity-snippets|Ycl|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by IllusionMH** [comment] 2021-09-13 09:34
/duplicate of #132150 and other for open in internal terminal

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-13 09:35 UTC
Labels: *duplicate

**Comment by fritzmg** [comment] 2021-09-13 12:31
> It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

Is there any ETA on this?

**Comment by IllusionMH** [comment] 2021-09-13 12:32
See linked issue for details. Most likely today

**Comment by fritzmg** [comment] 2021-09-13 12:36
Ah yes 👍 . For anyone else looking for this info (since the linked issue is pretty huge at this point): https://github.com/microsoft/vscode/issues/132150#issuecomment-917023548
