### ISSUE TITLE
Cursor invisible on long lines when scrolled horizontally

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#8828] opened 2016-07-07 09:04 UTC
- VSCode Version: 1.3.0-Insider e724f269ded347b49fcf1657fc576399354e6703
- OS Version: MacOSX 10.11.5

Steps to Reproduce:

1. Open document with long lines (longer then screen width
2. Scroll to the right and move the cursor to accordingly -> Cursor is invisible

**Comment by joaomoreno** [comment] 2016-07-07 09:18
Unless I'm misunderstanding the issue, this is expected behaviour.

How would you expect the editor to behave? This happens on every editor.

If you'd like your long line to **wrap**, you can control that by setting the configuration `"editor.wrappingColumn"` to `0`.

**Comment by marvinhagemeister** [comment] 2016-07-07 09:36
No, this has nothing to do with wrapping long lines. My cursor is literally invisible:
![vscode-bug](https://cloud.githubusercontent.com/assets/1062408/16649007/f7b21a06-4436-11e6-8a5e-22f9e2249067.png)

**Comment by joaomoreno** [comment] 2016-07-07 09:40
Interesting, but I still can't reproduce... Can you provide a screencast or similar? 👍

**Comment by alexandrudima** [comment] 2016-07-07 09:41
@marvinhagemeister Where is your focus? The cursor blinks/is rendered only when the editor is focused

**Comment by marvinhagemeister** [comment] 2016-07-07 09:55
I tried reproducing it with new files, but I'm unable to. This happens with a few xsl files at work. I'll try to see if I can get a 100% reproducible file.

@alexandrudima The focus is in the active editor. I'm only moving the cursor to the right.

Screencast:

![vscode-bug](https://cloud.githubusercontent.com/assets/1062408/16649475/6526c620-4439-11e6-9a4a-3ad5a5687c6e.gif)

**Comment by alexandrudima** [comment] 2016-07-07 12:51
@marvinhagemeister Thank you for the gif! I've never seen that before.

Do you see any errors in the console (`Help > Toggle Developer Tools`) ?

I've quickly tried with a file with these contents but could not reproduce:
```
<?xml version="1.0" ?>

<xsl:variable name="content" select="ancestor::div[has-class('contentSection')][1]/following-sibling::div"
```

Other things that might be relevant: does this reproduce when running code without extensions (close it completely and launch with `code --disable-extensions`), did you customize the font and/or picked a different theme?

**Comment by marvinhagemeister** [comment] 2016-07-07 14:50
I found a way to reliably reproduce this issue. The missing piece was, that it only happens when you have split the main editor. I can't reproduce it with just one editor visible. Launching with `code --disable-extensions` doesn't help. I did try with the default user settings and theme as well, but without success.

I managed to nail it down to the following steps to reproduce this issue:
1. Open vscode
2. Open random file (doesn't matter)
3. Split the editor with `cmd + #` (this is important)
4. Paste random code/text with long lines in one of the 2 editor panels

**Comment by marvinhagemeister** [comment] 2016-07-07 20:44
@alexandrudima Forgot to mention: unfortunately there are no errors in the devtools console.

**Comment by SeijiSuenaga** [comment] 2016-07-08 18:18
I can corroborate this issue.

- VSCode 1.3.0 commit e724f26
- Windows 10.0.10586 Build 10586

**Comment by bpasero** [comment] 2016-07-12 07:29
@marvinhagemeister @SeijiSuenaga can you try my solution in https://github.com/Microsoft/vscode/issues/9029#issuecomment-231825432 ?

**Comment by bpasero** [comment] 2016-07-12 13:13
To verify:
* be on windows
* have 2 groups open at least
* have enough tabs open to cause scrolling
* activate a tab that is at the end of the tab list in group one
* find a long line and arrow right 
* verify the cursor is not lost

**Closed** 2016-07-12 13:13 UTC
Labels: important

**Comment by bpasero** [comment] 2016-07-12 13:58
@alexandrudima can I ask you to verify this on Windows using this 1.3.1 stable build: https://az764295.vo.msecnd.net/stable/e6b4afa53e9c0f54edef1673de9001e9f0f547ae/VSCode-win32-stable.zip

Thanks!

**Comment by joaomoreno** [comment] 2016-07-12 14:28
@alexandrudima I verified this.
