### ISSUE TITLE
Getting TypeScript errors in JavaScript files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#230] opened 2015-11-19 14:25 UTC
`getTSConfig` might return a string or an object. I get a red squiggly saying that there is no common type between all return values.

<img width="686" alt="screen shot 2015-11-19 at 15 23 35" src="https://cloud.githubusercontent.com/assets/22350/11273073/94ae51b0-8ed1-11e5-8085-24104973799c.png">

**Comment by simonvizzini** [comment] 2015-11-20 15:21
Your "red squiggly" doesn't look as bad as mine :smile: 

![image](https://cloud.githubusercontent.com/assets/10862380/11303199/eb33a4b0-8fa1-11e5-8481-f72570832a19.png)

Aside from the TS error, is it really intended behavior to underline every single line on errors? Or is this maybe another issue? I'm using 0.10.1 btw

**Comment by joaomoreno** [comment] 2015-11-20 15:23
The error range is given by TypeScript, so that you can definitely file in their repo. :+1:

**Comment by simonvizzini** [comment] 2015-11-20 15:25
Alright, will do! I also just noticed that this only happens for methods inside a `class`, but not for plain, standalone functions.

**Comment by sveisvei** [comment] 2015-12-22 08:52
`() => {}` vs `function() {}` gives different red/error-highlighting, but both get the error.

**Comment by rbiggs** [comment] 2016-01-07 22:17
I having the same issue with my JavaScript in VSCode. I use a common pattern where a function does something and returns an object with a method/property. Its an object factory. I use this pattern a lot, but once in a while I get the same error and red squigglies for No best common types exists among return expressions. Even though the TypeScript declaration file and the function graph are identical to other uses of this pattern.

**Comment by janaagaard75** [comment] 2016-02-05 15:13
Is it possible to filter out this error with a comment?

I have a function that does indeed return different types, because the data returned is used to populate a drop down via Backbone Stickit. Depending on the drop having options groups or not, the data format will be a bit different.

I like that VS Code warns me about this, but in this particular this is actually expected.

**Comment by egamma** [comment] 2016-02-06 17:59
We are migrating to a new version of the JS infrastructure called Salsa, please give it a try. The issue above should is addressed by Salsa. To try out Salsa:
Install the insiders build: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
Enable Salsa: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#javascript---salsa-preview

Closing - if there are still JS problems pls file them against https://github.com/Microsoft/TypeScript/issues and mention that you are using Salsa.

**Closed by egamma** 2016-02-06 17:59 UTC
Labels: bug, js

**Comment by janaagaard75** [comment] 2016-02-08 08:51
Just confirming that using VS Code 0.10.7-insider, TypeScript 1.9.0-dev.20160208 and Salsa did indeed fix my issue. Thanks.

**Comment by egamma** [comment] 2016-02-08 09:13
@janaagaard75 thanks for the confirmation.

**Comment by patrickheeney** [comment] 2016-02-18 17:50
@janaagaard75 Are you running Version 0.10.9 by chance? I seem to be running into this on the latest vscode, not using any typescript. Curious if you updated something else independently?

**Comment by janaagaard75** [comment] 2016-02-19 09:41
I don't have the issue in 0.10.9 either. I stil think you need to install the typescript@next npm package in order to use the Salsa engine to analyze the JavaScript - maybe that's your issue?
