### ISSUE TITLE
show file path suggest besides .js files when working in .js file

### ISSUE THREAD

**Issue by littlee** [microsoft/vscode#106000] opened 2020-09-03 05:00 UTC
Issue Type: <b>Feature Request</b>

when working on a webpack based project, one may want to import .css files or .png files, but vs code doesn't  show those file path suggest

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

**Comment by mjbvz** [comment] 2020-09-03 21:23
Duplicate of https://github.com/microsoft/TypeScript/issues/19018

**Closed by mjbvz** 2020-09-03 21:23 UTC
