### ISSUE TITLE
Webview editor doesn't seem to work right in remote

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81769] opened 2019-10-01 16:34 UTC
#81698

SSH: Windows -> Ubuntu

I have all the same source as the built-in image-preview but I get this error when trying to open:

```
h: Unable to read file (Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"))
    at v.readFileStream (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1539:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Seems to be complaining about the /media/main.js path specifically.

**Comment by mjbvz** [comment] 2019-10-08 23:38
Duplicate of #1489 I believe. Let me know if you still see this

**Closed by mjbvz** 2019-10-08 23:38 UTC

**Comment by benc-uk** [comment] 2019-10-10 15:10
The linked issue seems to be completely unrelated
Why is this closed? @mjbvz

**Comment by mjbvz** [comment] 2019-10-10 18:46
Fixed reference
