### ISSUE TITLE
Request: mouse wheel scroll sensitivity setting for the explorer

### ISSUE THREAD

**Issue by Otrebus** [Microsoft/vscode#47230] opened 2018-04-05 09:12 UTC
Issue Type: <b>Feature Request</b>

The existing editor.mouseWheelScrollSensitivity setting doesn't affect the mouse wheel scrolling speed for the explorer, so a separate setting like explorer.mouseWheelScrollSensitivity would be nice.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment] 2018-04-05 17:19
Duplicate of #37727

**Closed by roblourens** 2018-04-05 17:19 UTC
Labels: editor, editor-core
