### ISSUE TITLE
File icons are not showing

### ISSUE THREAD

**Issue by paulmjfeng** [microsoft/vscode#94638] opened 2020-04-08 00:27 UTC
Issue Type: <b>Bug</b>

When I change file icon theme to another (Minimal or any other third party theme like VSCode Icons) from the default Seti theme, all icons are gone.

File -> Preferences -> File Icon Theme -> Click 'Minimal (Visual Studio Code)'

Expected:
File icons should change and show up

Actual:
File icons are disappeared.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
es7-react-js-snippets|dsz|2.7.1
remote-wsl|ms-|0.42.4
vscode-icons|vsc|10.0.0

</details>

**Comment by RMacfarlane** [comment] 2020-04-08 20:38
Duplicate of https://github.com/microsoft/vscode/issues/92695

**Closed** 2020-04-08 20:39 UTC
Labels: *duplicate
