### ISSUE TITLE
Save Proxy Authentication

### ISSUE THREAD

**Issue by prateekrajgautam** [Microsoft/vscode#56439] opened 2018-08-15 05:53 UTC
Issue Type: <b>Bug</b>

Please add option to save proxy authentication

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.88GB (0.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|8.0.0
vscode-color|ans|0.4.5
markdown-preview-github-styles|bie|0.1.2
excel-to-markdown-table|csh|0.3.1
c-cpp-compile-run|dan|0.0.6
matlab-runner|eam|0.3.0
vscode-install-vsix|fab|1.1.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
terminal|for|0.0.10
matlab|Gim|0.9.0
python|ms-|2018.6.0
cpptools|ms-|0.17.7
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.25.0
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by sandy081** [comment] 2018-08-15 09:08
Duplicate of #44041

**Closed** 2018-08-15 09:08 UTC
Labels: *duplicate, new release
