### ISSUE TITLE
Interface griefing itself

### ISSUE THREAD

**Issue by Cesare439** [microsoft/vscode#122740] opened 2021-04-30 16:22 UTC
- VS Code Version: 1.55.2
- OS Version: Windos 10 20H2

Hello Github, I'm having this issue with the entire interface of vs code. Did someone have a similiar or even the same issue?
It's not that it doesn't works but it's just so annoying....
I tried disabling the only extension I have, live server, and it still does this....

![Immagine 2021-04-30 151710](https://user-images.githubusercontent.com/57791969/116721520-aec5d780-a9dd-11eb-8a34-62c2bf5a697c.png)

**Comment by IllusionMH** [comment] 2021-04-30 19:21
/duplicate of #92379 which is some upstream issue

Should work with `--disable-gpu` flag or more permanent disable https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration 

Also check https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 look like Nvidia drivers may also affect rendering of Electron apps.

**Closed** 2021-04-30 19:22 UTC
Labels: *duplicate
