### ISSUE TITLE
vscode random crush

### ISSUE THREAD

**Issue by VictorIancu** [Microsoft/vscode#562] opened 2015-11-24 20:01 UTC
I'm working at a .php file and vs code crush at random, freeze is a more accurate description, wen i'm typing,   open files, all i can say it's a behavior witch appeared after the last update. And i've noticed that intellisense remain opened long after i've finished typing the function. Yes i have the warning: "Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'".  
Didn't try with other type of files to see if this issue appear.
My version of SO: Microsoft Windows [Version 10.0.10586]
VSCode version:
![vscodever](https://cloud.githubusercontent.com/assets/5724331/11379022/cf16ec3a-92f6-11e5-8c4e-d69cf57b3fc9.png)

![vscodecrush](https://cloud.githubusercontent.com/assets/5724331/11378856/f2b813cc-92f5-11e5-931e-b66a0860692b.png)

**Comment by h2u** [comment] 2015-11-24 20:27
Hi, you have to read #160 :)

**Comment by aeschli** [comment] 2015-11-27 14:11
duplicate of #160

**Closed by aeschli** 2015-11-27 14:11 UTC
