### ISSUE TITLE
Output from external device stopped showing in OUTPUT Window

### ISSUE THREAD

**Issue by n-is** [Microsoft/vscode#58266] opened 2018-09-08 18:57 UTC
Output from external device stopped showing in OUTPUT Window after updating to latest release of insiders. It still works on the non-insider version.

**Comment by sandy081** [comment] 2018-09-11 11:02
Please check latest insiders. It should be fixed

Duplicate of https://github.com/Microsoft/vscode/issues/58127

**Closed** 2018-09-11 11:02 UTC
Labels: *duplicate

**Comment by n-is** [comment] 2018-09-11 17:15
Thank you
