### ISSUE TITLE
Error "A system error occurred (EINVAL: invalid argument, stat 'c:\Users\carlos.fonseca\OneDrive\Documentos')" saving file

### ISSUE THREAD

**Issue by Carloslx** [Microsoft/vscode#33029] opened 2017-08-23 12:41 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
json-tools|eri|1.0.2
vscode-clang|mit|0.2.2
prettify-json|moh|0.0.3
mssql|ms-|1.1.0
cpptools|ms-|0.12.3
json-schema-validator|tbe|0.1.0

---

Steps to Reproduce:

1. Create a file
2. Attempt to save it

Reproduces without extensions: Yes/No

**Comment by Carloslx** [comment] 2017-08-23 12:47
Hmmm... Saving on a folder *not* being synced by OneDrive (build 17.3.6963.0807 from Windows 10 Insider Build 16257) works.

**Comment by Tyriar** [comment] 2017-08-23 15:19
Duplicate of https://github.com/Microsoft/vscode/issues/27285

**Closed by Tyriar** 2017-08-23 15:19 UTC
Labels: json, new release
