### ISSUE TITLE
Trying to modify settings, unable to write user settings

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#61423] opened 2018-10-21 03:41 UTC
Issue Type: <b>Bug</b>

When I try to change the settings using the methods in the GIF diagram below, I always get <b>'Unable to write user settings. Please open user settings and clear errors or warnings and try again'</b>, and I can't complete the changes. Disabling all extensions will still happen like this.

Only when it is overwritten directly in the <code> "setting.json" </code>file, the changes are valid, and the situation in the gif does not occur at this time.

![suggest_error](https://user-images.githubusercontent.com/13393959/47262832-5288bf80-d525-11e8-9307-31694cec433a.gif)

VS Code version: Code - Insiders 1.29.0-insider (45d5d153bbebed743b77e426615aade34971eb46, 2018-10-19T06:58:45.940Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
angular2-snippets|dan|1.0.20
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
jquerysnippets|don|0.0.1
jupyter|don|1.1.4
code-runner|for|0.9.4
Angular2|joh|6.3.0
Kotlin|mat|1.6.0
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|7.0.4
vscode-cosmosdb|ms-|0.8.0
vscode-language-pack-zh-hans|MS-|1.28.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.1
azure-account|ms-|0.4.3
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.93
js-atom-grammar|ms-|0.1.14
mono-debug|ms-|0.15.8
PowerShell|ms-|1.9.0
typescript-javascript-grammar|ms-|0.0.46
debugger-for-chrome|msj|4.10.2
debugger-for-edge|msj|1.0.6
vetur|oct|0.13.0
platformio-ide|pla|1.4.1
java|red|0.32.0
vscode-yaml|red|0.0.17
rust|rus|0.4.10
vscode-arduino|vsc|0.2.22
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
JavaScriptSnippets|xab|1.7.1

(2 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2018-10-21 19:48
Duplicate of #61341

**Comment by sandy081** [comment] 2018-10-22 15:19
@czfadmin This is expected, if there are any errors in the file action is not completed until the errors are fixed.

You have to fix your file before performing the action.

**Closed by sandy081** 2018-10-22 15:19 UTC
Labels: insiders

**Comment by czfadmin** [comment] 2018-10-23 01:56
@sandy081 
 I have fixed all the problems in <code>"settings.json" </code>before, but I still have such a prompt.

**Comment by sandy081** [comment] 2018-10-23 08:09
@czfadmin Did you save the file before trying? Can you please provide steps you followed? A video/gif would be nice.

**Comment by czfadmin** [comment] 2018-10-23 11:09
@sandy081 , thank you, I deleted all the settings in <code>"settings.json"</code>, and then used a quick way to modify some settings, but this problem did not appear (disable all extensions did not appear this problem). So it should be the original configuration There is an error in the file, but vscode does not check it out. So this problem will occur.

**Comment by sandy081** [comment] 2018-10-23 15:49
> So it should be the original configuration There is an error in the file, but vscode does not check it out. So this problem will occur.

@czfadmin You mean that VS Code did not show this error? Did you see in Problems view?

**Comment by czfadmin** [comment] 2018-10-23 23:38
@sandy081 Right, and I didn’t see some problems in the Problems view.
When I first encountered this problem, I fixed all the problems according to the prompt method, but there was a phenomenon like gif. There is no problem in the problem view at this time. It may also be an update yesterday that solved the problem.So in the latest version, this issue has not been encountered for the time being.
