### ISSUE TITLE
Linux: Updates are applied while Code is still running

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#45569] opened 2018-03-12 09:49 UTC
From #45547

This needs to be addressed for both DEB and RPM packages.

**Comment by Tyriar** [comment] 2018-03-12 18:11
@joaomoreno this is less than ideal but is as designed since we I believe it's bad practice to block apt if code is running. Right now users typically get an ENOENT pretty quickly which forces them to restart (a more specific message would be better though.

This will be much better with the snap package which is the future direction https://github.com/Microsoft/vscode/issues/5458

**Comment by joaomoreno** [comment] 2018-03-14 08:16
@Tyriar We should still fix it since we're getting bogus error telemetry errors which show processes from different versions interacting with one another.

In Windows, we prevent it using a system-wide app mutex. Can we do the same in Linux?

**Comment by alexandrudima** [comment] 2018-03-26 20:33
@Tyriar steps:
1. launch a vscode window with the terminal hidden
2. update vscode
3. toggle terminal

Can we at least send a signal or something such that we at least disable error telemetry... Or perhaps show the user a message that everything is broken...

**Comment by Tyriar** [comment] 2018-03-27 15:47
@bpasero what do you think about watching `process.argv[0]` with `fs.watchFile` on the main process and if there's a change notify all renderers to show a message and disable telemetry?

**Comment by bpasero** [comment] 2018-03-27 16:27
@Tyriar and the intent is to send a command over from another process to VS Code? If so, that should be done by running just code with a command line argument, no?

**Comment by Tyriar** [comment] 2018-03-27 17:31
@bpasero I was thinking leave this completely up to the running version to handle. Relying on a CLI arg could potentially going wrong, for example `code --notify-update` on any old version would *launch* the old version.

**Comment by bpasero** [comment] 2018-03-28 04:42
@Tyriar I am just worried that something generic as watching `process.argv[0]` could be triggered by other things than us.

**Comment by Tyriar** [comment] 2018-03-28 16:40
@bpasero we could check for something like [stats.mtime](https://nodejs.org/api/fs.html#fs_stats_mtime) && [size](https://nodejs.org/api/fs.html#fs_stats_size) to narrow it to the case we're interested in.

**Comment by bpasero** [comment] 2018-03-28 16:42
@Tyriar from my experience of using these flags for preventing dirty writes / reads you cannot rely on that information...

**Comment by Tyriar** [comment] 2018-03-28 17:30
Ok, I guess the option is then inside the deb/rpm post install scripts to check if vscode is running (`ps axco command | grep code`?), check the version inside package.json is compatible and then run something like `code --notify-update` to inform the windows.

**Comment by bpasero** [comment] 2018-03-28 17:49
@Tyriar as far as I know we use a mutex on windows to signal that Code is running, can't you do something like that for Linux too?

**Comment by Tyriar** [comment] 2018-03-29 17:44
@bpasero I think blocking install without closing VS Code would not be ideal for Linux. This would cause `apt`/`dnf` to fail updating half way through, which may not only be updating VS Code (eg. `sudo apt-get upgrade`).

**Comment by bpasero** [comment] 2018-03-30 05:57
@Tyriar we could add a new shell script that you would call that would pass some specific argument to the running Code instance. For older installations it would fail silently because this shell script would not exist. With that we could do it all through a new command line argument.

**Comment by Tyriar** [comment] 2018-03-30 14:55
@bpasero version checking using `code --version` should be pretty easy and we could leverage the same CLI then?

**Comment by bpasero** [comment] 2018-03-30 15:50
@Tyriar yeah true that would work as well. After you see that the version is fit for the command, just invoke it again with another CLI argument that you add only for this purpose.

**Comment by Tyriar** [comment] 2018-03-30 16:46
I'll see if I can get to this in April

**Comment by Tyriar** [comment] 2018-09-12 21:36
Duplicate https://github.com/Microsoft/vscode/issues/5908

**Closed by Tyriar** 2018-09-12 21:36 UTC
Labels: bug, install-update, linux
