### ISSUE TITLE
HTML Formatter adding extra new lines between <textarea>

### ISSUE THREAD

**Issue by samshareski** [Microsoft/vscode#58435] opened 2018-09-11 13:42 UTC
Issue Type: <b>Bug</b>

If you have a textarea tag and the closing tag is on a separate line, each time you run the formatter (I have format on save enabled) it will add extra new lines between the opening and closing tags.

The number of new lines doubles each time the formatter is run.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.4.0-134-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 0, 0|
|Memory (System)|10.86GB (1.98GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by aeschli** [comment] 2018-09-12 07:13
I'm not able to reproduce with this sample
```html
<html>

<body>
	<textarea name="" id="" cols="30" rows="10">
		sdfsdf
	</textarea>
</body>

</html>
```

@samshareski  Can you provide a small sample where the problem shows?

**Comment by samshareski** [comment] 2018-09-12 13:30
@aeschli 

Your example doesn't reproduce on my machine either. It seems to only happen if the textarea closing tag is on a new line and there's no text in between the opening and closing tags like so

```html
<html>

<body>
	<textarea name="" id="" cols="30" rows="10">
	</textarea>
</body>

</html>
```

But the bug occurs for any number of new line characters between the tags.

**Comment by aeschli** [comment] 2018-09-18 12:58
Fixed in the latest jsbeautify.

**Closed by aeschli** 2018-09-18 12:58 UTC
Labels: html, needs more info
