### ISSUE TITLE
Titlebar display issue

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#88531] opened 2020-01-13 09:34 UTC
Version: 1.42.0-insider
Commit: 960cddb992cc96d47f56b633b361909f1b5b3353
Date: 2020-01-10T05:35:27.119Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

---

This start to happen since last week. Might be due to Electron or some other changes, I'm not sure.

From what I can observer:

- `Untitled-1` is not offset to the right postion
- When statusbar is loaded, this is fixed
- However, even if I hide statusbar, this is not fixed

![bug](https://user-images.githubusercontent.com/4033249/72244836-666b8600-35ef-11ea-86c3-0a82a910a41b.gif)

I only have Auto Attach enabled for my statusbar:

![image](https://user-images.githubusercontent.com/4033249/72244754-3de38c00-35ef-11ea-9280-7cbb3d8bba80.png)

**Comment by sbatten** [comment] 2020-01-17 15:21
@octref are you still reproducing this?

**Comment by octref** [comment] 2020-01-17 19:26
Yes on

Version: 1.42.0-insider
Commit: fd13e449f5f2fe300f187129d6065ed1cfad74d3
Date: 2020-01-17T16:30:38.851Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by sbatten** [comment] 2020-01-17 20:00
are there any special conditions?

I cannot repro with these steps:

1) open empty workspace
2) open new untitled file
3) reload window

**Comment by octref** [comment] 2020-01-24 20:13
I set all extensions disabled.

This is still reproducible for me when setting `"window.titleBarStyle": "custom"`.

![image](https://user-images.githubusercontent.com/4033249/73100699-607a7c80-3eee-11ea-8633-d0ce110f6602.png)

**Comment by sbatten** [comment] 2020-02-08 03:54
now rob is seeing this, i'll need to try to repro again on monday

**Comment by octref** [comment] 2020-02-15 06:27
This still happens.

**Comment by octref** [comment] 2020-03-02 18:09
This isn't happening in latest insiders now. If it happens again I'll reopen.

**Comment by roblourens** [comment] 2020-12-01 20:45
I still see this.

![image](https://user-images.githubusercontent.com/323878/100794635-b2274980-33d2-11eb-9cd8-160cd65a3035.png)

- Open a new empty vscode window
- cmd+O, open some file

also

- Connect to a remote
- While connecting, the title is offset. When it finishes connecting, it gets fixed.
- Sometimes if it fails to connect, it gets stuck like this

So, something about having a folder open in the window? 

If I resize the window, it gets fixed.

**Comment by sbatten** [comment] 2020-12-07 19:47
Closing this as duplicate of https://github.com/microsoft/vscode/issues/106001

**Closed by sbatten** 2020-12-07 19:47 UTC
Labels: needs more info
