### ISSUE TITLE
Emmet + selection gives weird behavior

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53182] opened 2018-06-27 21:58 UTC
From #51180

I don't know if this is expected or not

```html
<html>
	<body>
		<div />
	</body>
</html>
```

- Select `<div`
- Run "Split/Join Tag"
- It actually operates on <body> and produces `<body />`

And this seems related:

- Start with the same html and selection
- Run "Remove Tag"
- body is deleted, you are left with `<div />` which is weird, it deleted the opposite of the selection
- "undo"
- Now body has an extra close tag

```html
<html>
	<body></body>
		<div />
	</body>
</html>
```

**Comment by ramya-rao-a** [comment] 2018-06-28 00:21
@JacksonKearl Passing `true` for `includeNodeBoundary` in `getHtmlNode` will fix this. But before doing that, lets review all the usages of `getHtmlNode` and check where else inlcuding the boundary makes sense

**Comment by JacksonKearl** [comment] 2018-06-28 00:40
`includeNodeBoundary` is currently an optional parameter that defaults to false. It is left as that defualt value in:

- updateTag
- splitJoinTag
- selectPrev/Next item
- removeTag
- balance (out only)

Of these, it is only important that selectPrev/Next item stays false and balance out stays false. The others could go either way.

**Comment by JacksonKearl** [comment] 2018-06-28 00:48
I put up a PR that explicitly passes `includeNodeBoundries: false` for selectPrev/Next item and balance out. We can now flip the default param to true if we decide that's better and everything should still work

**Comment by FerozCerebro13** [comment] 2018-06-28 00:50
Flipped back to normal standards.

**Comment by JacksonKearl** [comment] 2018-06-28 00:58
As for the issue with tag auto-completion I believe we don't have direct access to the fact that the edit operation was an undo inside the extension, but we might be able to decide not to insert the closing tag if the edit operation inserted a closing tag itself? Relevant lines: https://github.com/Microsoft/vscode/blob/56fb08bd529544ac1eb9d89abd7a4af53bf508de/extensions/html-language-features/client/src/tagClosing.ts#L47

**Comment by ramya-rao-a** [comment] 2018-06-28 04:15
The issue of remove tag followed by undo was tracked in #39545 and the root cause was tracked in #34484

**Comment by ramya-rao-a** [comment] 2018-06-28 04:51
> I put up a PR that explicitly passes includeNodeBoundries: false for selectPrev/Next item and balance out. We can now flip the default param to true if we decide that's better and everything should still work

@JacksonKearl Can you do a similar analysis to the use of `getNode` which has the same boundary related input parameter?

**Comment by JacksonKearl** [comment] 2018-06-28 17:49
@ramya-rao-a  Put up a new commit that explicitly sets the getNode parameter where required (only one place I could find) I also flipped the default to `true`, as that seems like it makes more sense given emmet commands like "select prev/next item" put the selection at the boundaries of the node

**Closed** 2018-06-29 20:41 UTC
Labels: bug, emmet
