### ISSUE TITLE
Extremely laggy typing in Integrated Terminal

### ISSUE THREAD

**Issue by Tinyik** [microsoft/vscode#111074] opened 2020-11-21 02:10 UTC
- VSCode Version: 1.51.0
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Open an Integrated Terminal
2. Start typing with normal speed (e.g. `git commit -m "commit message"`)
3. At mid-sentence, Terminal freezes for 3-4 seconds on screen before becoming responsive again. (The terminal still takes input when frozen)

This is not related to the shell I'm using. Reproduces 100% with multiple shells, and both on my MacBook and iMac. macOS Terminal and iTerm2 do not have the same issue.

The lag improves quite a bit when extensions are disabled, but still freezes at some point with shorter interval. (sub-seconds).

**Comment by the-kenny** [comment] 2020-11-21 10:33
I can reproduce this as well. Also on Big Sur and 1.51.1.

It's pretty easy to capture in the JS Profiler:

<img width="1036" alt="Screenshot 2020-11-21 at 11 29 28" src="https://user-images.githubusercontent.com/31167/99875049-d4f47980-2bec-11eb-92e3-885cb20e6a9a.png">

Attached are two profiles both showing this firing timer at the instant the terminal freezes for 1-2 seconds.


[Profile-20201121T113142.txt](https://github.com/microsoft/vscode/files/5577419/Profile-20201121T113142.txt)
[Profile-20201121T113127.txt](https://github.com/microsoft/vscode/files/5577420/Profile-20201121T113127.txt)

**Comment by the-kenny** [comment] 2020-11-21 10:43
It boils down to the following `exec` returning extremely slow:

```javascript
 d.exec("lsof -OPl -p " + this._ptyProcess.pid + " | grep cwd", cb)
```

(found in `ProcessManager.getCwd`).

**Comment by the-kenny** [comment] 2020-11-21 10:50
...it's actually already being tracked in https://github.com/microsoft/vscode/issues/105446

**Comment by meganrogge** [comment] 2020-11-22 02:32
thanks for your patience while we look into Big Sur related issues. Closing this as a dupe of #105446

**Closed** 2020-11-22 02:32 UTC
Labels: *duplicate, bug, integrated-terminal, macos-big-sur
