### ISSUE TITLE
I reopened issue but it is not notifiable

### ISSUE THREAD

**Issue by YVEF** [microsoft/vscode#113961] opened 2021-01-07 06:50 UTC
Hi
I reopened the issue https://github.com/microsoft/vscode/issues/111460
but I can see that the activity is not resumed. If the maintainer does not have time - not a problem, I understand :) but I suspect that just the reopening is not subject to notification. The new one issue can be closed anyway, because it is just a friendly reminder.
Thank you a lot!

**Comment by rzhao271** [comment] 2021-01-07 19:50
Thanks for the reminder! Closing this issue.
Duplicate of #111460

**Closed by rzhao271** 2021-01-07 19:50 UTC
Labels: *duplicate
