### ISSUE TITLE
Code Helper will burn 30%+ CPU always!

### ISSUE THREAD

**Issue by futurist** [Microsoft/vscode#24874] opened 2017-04-17 02:29 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-dictionary|Compulim|0.0.5|
|beautify|HookyQR|1.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-terminal-here|Tyriar|0.0.5|
|vscode-select-line|andreaskian|0.0.3|
|vscode-standard-format|chenxsan|0.0.12|
|open-html-in-browser|coderfee|0.0.6|
|githistory|donjayamanne|0.2.0|
|shell-format|foxundermoon|0.1.3|
|bracketselection|guosong|1.0.3|
|goto-last-edit-location|krizzdewizz|0.2.1|
|vscode-exec-node|miramac|0.2.8|
|debugger-for-chrome|msjsdiag|2.6.0|
|gotolastedit|plrenaudin|0.2.1|
|expand-selection-to-scope|vittorioromeo|0.1.0|;

---

Steps to Reproduce:

1. Just use it normally for a while

And now the `Code Helper` has 100% CPU usage!

**Comment by landonepps** [comment] 2017-04-17 04:33
I also seem to have this issue. The process running at 100% is this one:
```
landon$ ps aux | grep 4287
landon           4287 100.0  0.1  3272012  10148   ??  R    Fri11PM  96:23.89 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost

```
It also did not terminate after I closed VSCode, I had to kill it manually.

I don't know how to print my installed extensions nicely like futurist, but these are the results from the command line:

```
landon$ code --list-extensions
2gua.rainbow-brackets
EditorConfig.EditorConfig
IBM.output-colorizer
PKief.material-icon-theme
Shan.code-settings-sync
WakaTime.vscode-wakatime
alefragnani.project-manager
azemoh.one-monokai
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
dzannotti.vscode-babel-coloring
eg2.tslint
formulahendry.auto-rename-tag
ms-vscode.cpptools
msjsdiag.debugger-for-chrome
naumovs.color-highlight
nepaul.editorconfiggenerator
spywhere.guides
wmaurer.vscode-jumpy
xabikos.JavaScriptSnippets
```

**Comment by jrieken** [comment] 2017-04-18 07:37
Please try again with `--disable-extensions` which will only run with the build in extensions

**Comment by mjbvz** [comment] 2017-05-01 19:48
Closing as we need more information to investigate this.

Please try running code with extensions disabled to see if one of these is the root cause of the issue

**Closed by mjbvz** 2017-05-01 19:48 UTC
Labels: needs more info
