### ISSUE TITLE
Freeze when opening JS file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#38308] opened 2017-11-14 09:34 UTC
Open attached JS file.

[workbench.main.zip](https://github.com/Microsoft/vscode/files/1487872/workbench.main.zip)

**Comment by tsalinger** [comment] 2017-11-21 14:59
I reduced the file to this one line that causes the freeze.

[causesCrash.txt](https://github.com/Microsoft/vscode/files/1491791/causesCrash.txt)

**Comment by aeschli** [comment] 2018-01-29 11:29
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/567

**Closed by aeschli** 2018-01-29 11:29 UTC
Labels: bug, editor, freeze-slow-crash
