### ISSUE TITLE
Next version release notes don't show from update banner

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#21652] opened 2017-03-01 21:38 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open 1.9.1 and wait for update banner to appear.
2. Click on "Release Notes".

Get error message:
"Unable to open 'Release Notes: 1.10.0': Cannot read property 'replace' of null

1.10 release notes display fine after installing 1.10 VS Code.

**Comment by grantwinney** [comment] 2017-03-01 21:40
Nothing to add really, except I happened to snag a screenshot.

![unable to open release notes](https://cloud.githubusercontent.com/assets/1354059/23482605/ae970940-fe9d-11e6-96e0-9b69df2370a2.png)

**Comment by unional** [comment] 2017-03-01 22:07
> The "Release Notes" open without error if you go through the Help / Release Notes menu item, even without restarting VS Code first.

I saw still the 1.9.1 release note by doing that, instead of 1.10.0

**Comment by gregvanl** [comment] 2017-03-01 22:29
Callstack:
messageService.ts:126 Unable to open 'Release Notes: 1.10.0': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: 1.10.0': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:1119)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:725
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18548)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:480)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:131:30589
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19172)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:131:30561)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:131:29827)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:22073)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:21503)

**Comment by grantwinney** [comment] 2017-03-01 22:39
I double-checked and the menu pulls up the 1.9.1 release notes for me too @unional.

**Comment by fabiorocha** [comment] 2017-03-02 03:23
Also reproes for me.

![image](https://cloud.githubusercontent.com/assets/1686833/23491662/70e8e688-feb4-11e6-8baa-cce67b577d30.png)

**Comment by joaomoreno** [comment] 2017-03-02 08:52
The fix for this was pushed in f9c78602c1fc4f55bf6be239fd74f0f4b28faa68, so it's only available in 1.10.

**Comment by tomahawkzx** [comment] 2017-03-03 18:07
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-toolbox-snippets|alechp|0.12.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|dark-plus-plus-theme|DryWolf|0.0.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vsc-material-theme|Equinusocio|0.0.3|
|icons-fania|fania|0.4.0|
|file-icons|file-icons|1.0.0|
|vscode-flatland-icon-theme|gebilaoxiong|0.0.6|
|easy-icons|jamesmaj|0.3.1|
|vsclassic-icon-theme|jez9999|1.0.3|
|ionic2-vscode|jgw9617|1.0.0|
|Angular2|johnpapa|0.5.7|
|vscode-icon-theme|jtlowe|1.4.0|
|theme-dark-plus-contrast|k3a|0.1.101|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|indent-rainbow|oderwat|0.4.1|
|material-icon-theme|PKief|1.3.2|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.2.0|
|indenticator|SirTori|0.2.1|
|react-beautify|taichi|0.3.0|
|ayu|teabyii|0.2.1|
|ionic2|Thavarajan|2.1.3|
|react-redux-es6-snippets|timothymclane|2.0.2|
|jsx|TwentyChung|0.0.1|
|ionic2-snippets|uqutub|0.0.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|;


---

Steps to Reproduce:

1. Open 1.10.1 and wait for update banner to appear.
2. Click on "Release Notes".

**Comment by fabiorocha** [comment] 2017-03-03 18:15
@joaomoreno My comment above also referred to 1.10.1.

**Comment by joaomoreno** [comment] 2017-03-06 08:59
@tomahawkzx @fabiorocha 

Wait... but if you are on 1.10.1... how are you getting an update notification. There's no later version, after that one. Are you sure about being on 1.10.1?

Can you show me a screenshot of the update notification?

If you open the Dev Tools, and set a breakpoint on `vs/workbench/parts/update/electron-browser/update.ts`, line 51, before you get the update notification... it should get hit once that update notification comes in... what is the value of the `version` variable?

![image](https://cloud.githubusercontent.com/assets/22350/23602999/643c1278-0253-11e7-952d-673514f62fd7.png)

**Comment by tomahawkzx** [comment] 2017-03-06 12:21
@joaomoreno that is where this became weird. Although I already have 1.10.1, the update bar still randomly pops through the day. (sorry to not mention that before, I was in a hurry)

When I select Download Now, nothing happens. Pressing "Release Notes" leads to the second message "Error: Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null".

![image](https://cloud.githubusercontent.com/assets/18285859/23609405/a0885ed2-024c-11e7-9bc5-c7bc9bb787f0.png)

![image](https://cloud.githubusercontent.com/assets/18285859/23609451/d0c37ffa-024c-11e7-8c74-ce6bed6966e8.png)



I don't know if this behavior is related to this issue (nor the actual label for this), but the button Help > "Check for updates" keeps disabled on "Checking for updates..." state.

![image](https://cloud.githubusercontent.com/assets/18285859/23609549/51201424-024d-11e7-939a-bcdbbe2d6cd0.png)

While I'm figuring how to find _update.ts_ in the Developer Tools, here follows the errors logged at the console:
```

Overwriting extension <<.jsx>> to now point to mime <<text/x-jsx>>
2/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31 Overwriting extension <<.jsx>> to now point to mime <<text/javascript>>
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: ejst.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: lattet.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tplt.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tst.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: hamlt.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117 [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: erbt.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: ejsd.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: latted.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tpld.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tsd.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: hamld.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] [C:/Users/leonardobag/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: erbd.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] vscode-icons is active!
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103 Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:1119)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:725
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16796)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:480)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30715
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30687)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:29953)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:10371)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:9801)e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:101 [File Watcher] Warning: Watcher is busy catching up wit 27232 file changes in 60 seconds. Latest path is 'c:\Projetos\AtlasV2\dev\Atlas\Atlas.WebApp\node_modules\.staging\material-design-icons-0f65fbca\hardware\2x_web'
27/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:101 [File Watcher] System.IO.InternalBufferOverflowException: Too many changes at once in directory:c:\Projetos\AtlasV2\dev\Atlas\Atlas.WebApp.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103 Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:1119)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:725
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16796)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:480)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30715
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30687)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:29953)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:10371)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:9801)e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103
3/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:71 Cannot execute type because no code editor is focused.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103 Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:1119)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:725
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16796)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:480)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30715
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30687)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:29953)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:10371)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:9801)e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Cannot set property 'column' of undefined: TypeError: Cannot set property 'column' of undefined
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:21278
    at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:10581)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:14159)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15987)
    at _completed (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15428)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:1700
    at g.e.dispatch (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:3056)
    at g.e.handleData (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:2564)
    at Socket.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:1565)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7) (2 errors in total)e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32 WARNING: Promise with no error callback:737
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32 Object
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] ApplicationInsights:Sender Array[1]
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 getaddrinfo ENOENT vscode-update.azurewebsites.net:443

Error: getaddrinfo ENOENT vscode-update.azurewebsites.net:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26): Error: getaddrinfo ENOENT vscode-update.azurewebsites.net:443

Error: getaddrinfo ENOENT vscode-update.azurewebsites.net:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:1308)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:103 Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: {0}': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:1119)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:725
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16796)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:480)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30715
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:30687)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:29953)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:10371)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:122:9801)

```

**Comment by tomahawkzx** [comment] 2017-03-06 12:30
After restart VSCode, the Help>"Check for updates..." button became available, and now it seems to work properly. 

![image](https://cloud.githubusercontent.com/assets/18285859/23609855/d6ba3d70-024e-11e7-99b6-863aa4f17329.png)

I'll wait to see if this update request pops randomly along the day. The breakpoint is ready at the file you suggested.

**Comment by joaomoreno** [comment] 2017-03-06 14:31
Awesome, remember to keep the Developer Tools window open, otherwise the breakpoint won't be hit.

**Comment by martellaj** [comment] 2017-03-27 15:39
![image](https://cloud.githubusercontent.com/assets/1019478/24364842/e4a32976-12c8-11e7-91f8-d41d5ee0685d.png)

Now reproing in PROD.

**Comment by joaomoreno** [comment] 2017-03-27 15:45
@martellaj Can you use a network inspector like Charles proxy, and inspect the requests done between Code and the update server?

**Comment by martellaj** [comment] 2017-03-27 16:04
@joaomoreno Hm, I clicked `Check For Updates...` to try to get the banner to pop again, but now it's telling me there are no updates. I didn't update this morning.

**Comment by martellaj** [comment] 2017-03-27 18:02
@joaomoreno The banner popped up again. I tried using Fiddler to capture any requests made when I clicked to view release notes, but none were made. I assume the call happens before the banner is displayed, but I didn't have Fiddler running then.

**Comment by joaomoreno** [comment] 2017-03-28 06:50
Yeah, I'd be interested in capturing the request which fires up the update notification.

**Comment by joaomoreno** [comment] 2017-04-26 09:51
Closing this as dupe of #18714

**Closed by joaomoreno** 2017-04-26 09:51 UTC
Labels: bug
