### ISSUE TITLE
Wrong text type recognition behind specific regexp in powershell function

### ISSUE THREAD

**Issue by ztrhgf** [Microsoft/vscode#29982] opened 2017-07-01 05:19 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|code-runner|formulahendry|0.6.24|
|format-php|Kasik96|1.1.2|
|perl-debug|mortenhenriksen|0.2.3|
|PowerShell|ms-vscode|1.4.1|
|easy-snippet-maker|tariky|0.0.5|
|plsql-language|xyz|1.0.4|;

---

Steps to Reproduce:

1.
type this to VS Code editor as powershell function and see wrong coloring
```powershell
function aaa {
    param(
        [Parameter()]
        [ValidateScript( {$_ -match '^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$'})]
        [string] $ReplyTo = "admins@fi.muni.cz", # everything after end of previous line is brown, but it shouldnt be
        [string] $hascolorasitistext    
    )
}
```

2. everything after match is brown, as it is common text
3. but if i use this shorter regexp everything is back to normal
```powershell
function aaa {
    param(
        [Parameter()]
        [ValidateScript( {$_ -match '^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-'})]
        [string] $ReplyTo = "admins@fi.muni.cz",
        [string] $hascolorasitistext    
    )
}
```

**Comment by aeschli** [comment] 2018-02-09 10:16
duplicate of https://github.com/Microsoft/vscode/issues/36991

**Closed by aeschli** 2018-02-09 10:16 UTC
