### ISSUE TITLE
VS Code window doesn't preserve maximized state after restart in Gnome 44.1

### ISSUE THREAD

**Issue by tandrejo** [microsoft/vscode#184311] opened 2023-06-05 10:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Manjaro Linux with Gnome 44.1 Wayland session, with all latest updates.

Steps to Reproduce:

1. Start VS Code, maximize window then exit the application.
2. Start VS Code again - VS Code window is not maximized. VS Code expected  to be maximized as before exiting.

Started facing the issue after upgrading to Gnome 44.1 from 43.5.

**Comment by anvltu** [comment] 2023-07-10 11:33
With the latest system update the problem seems gone.

**Comment by duanebv** [comment] 2023-11-22 18:23
I have also been facing this issue, but only in Gnome and while using Xorg.  It does not occur when using Wayland.  This was tested using both XOrg and Wayland while running in Fedora 39 KDE spin, and both worked properly.  I am currently running Fedora 39 with Gnome 45.1.  If I maximize the VSCode window and close the application, it is no longer maximized when the application is relaunched. I am running kernel 6.5.12 and have also confirmed that his occurs regardless of how many monitors are in use.

**Comment by deepak1556** [comment] 2023-12-05 15:59
Closing based on https://github.com/microsoft/vscode/issues/184311#issuecomment-1628784340

**Closed by deepak1556** 2023-12-05 15:59 UTC

**Comment by duanebv** [comment] 2023-12-17 19:39
My comment declaring the issue present was posted 4 months after tandrejo's comment.  tandrejo addressed the issue was resolved by updates when running using Wayland.  It is still very much not resolved when running with Xorg.  I updated VS Code to 1.85.1 today and am on the latest updates for Fedora 39 and the issue is still present.
