### ISSUE TITLE
Add a setting to stop grouping the errors by file

### ISSUE THREAD

**Issue by bbalp** [Microsoft/vscode#23887] opened 2017-04-04 14:16 UTC
I failed at finding such a setting, but it would be quite nice to have.

Explanation: When building a c++ program, (real) template errors may cause a huge amount of (false) errors. In this context, we need to have the errors listed in the order they appear in the build output, to start by fixing the first one.

I would be pleased to have your opinion.

**Comment by jeremieca** [comment] 2017-04-26 15:59
+1

**Comment by sandy081** [comment] 2017-11-27 13:41
Duplicate of #18685

**Closed** 2017-11-27 13:41 UTC
Labels: *duplicate, error-list, feature-request
