### ISSUE TITLE
Open in merge editor didnt work

### ISSUE THREAD

**Issue by bish0768** [microsoft/vscode#213058] opened 2024-05-20 10:52 UTC
When I tried to open the merge changes via 'open in merge editor', it shows as loading but didn't show the content in 'Incoming' and 'current' files.
![New Error](https://github.com/microsoft/vscode/assets/170322018/e0e267a3-240b-4a1d-b39a-438b6ee05fae)

**Comment by hediet** [comment] 2024-12-16 16:12
/duplicate of merge editor diffing is slow

**Closed by hediet** 2024-12-16 16:12 UTC
