### ISSUE TITLE
Fixes icon is overlapping the content/code in windows

### ISSUE THREAD

**Issue by jeybin** [Microsoft/vscode#36564] opened 2017-10-19 14:06 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vscode-great-icons|emm|2.1.16
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.1
code-runner|for|0.7.3
beautify|Hoo|1.1.1
rest-client|hum|0.15.3
angular2-switcher|inf|0.1.4
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.9.0
vscode-extension-auto-import|mop|1.3.3
vscode-scss|mrm|0.6.2
typescript-hero|rbb|1.6.0
vscode-icons|rob|7.15.0
stylelint|shi|0.30.0
autoimport|ste|1.2.2
Angular2|UVB|0.4.1
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.11.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jeybin** [comment] 2017-10-19 14:07
![icon is overlaping](https://user-images.githubusercontent.com/32933024/31774956-da9b2260-b504-11e7-9a8f-5a89ec748d54.JPG)

**Comment by ramya-rao-a** [comment] 2017-10-19 17:33
@jeybin What is the file type of the file where you see this?

**Comment by jeybin** [comment] 2017-10-19 17:52
@ramya-rao-a

**Comment by jeybin** [comment] 2017-10-19 17:52
@ramya-rao-a  its a typescript file .ts

**Comment by mjbvz** [comment] 2017-10-20 03:25
Duplicate of #33895

**Closed** 2017-10-23 07:40 UTC
Labels: duplicate, typescript
