### ISSUE TITLE
Can't hover on small error squiggly

### ISSUE THREAD

**Issue by ahmafi** [microsoft/vscode#138372] opened 2021-12-02 21:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Linux Mint 20.2

Steps to Reproduce:

You can produce this issue in any language. I give an example for javascript and eslint.
1. Install and configure eslint extension.
2. Create a .js file and type `if abcd`. (Or any other code that creates single letter squiggly)
3. A squiggly error should show up in the editor.

When you hover your mouse on the squiggly the expected behavior is to get descriptions about the error, but the squiggly is too small that you can't hover over it and you won't get any descriptions.

![vscode-bug](https://user-images.githubusercontent.com/12560109/144508127-91d0e185-5007-4620-9fa7-47dda9be2660.gif)

It works if the error is at the end of the line:

![vscode-bug-2](https://user-images.githubusercontent.com/12560109/144508812-36d34637-ed38-4cec-a4c1-2d453e2a4b74.gif)

**Comment by sandy081** [comment] 2021-12-07 07:27
Assigning to @alexdima as it is related to hover. Please assign it back if something can be done from my side.

**Comment by alexdima** [comment] 2021-12-07 08:07
Duplicate of https://github.com/microsoft/vscode/issues/136711

**Closed by alexdima** 2021-12-07 08:07 UTC
