### ISSUE TITLE
User Defined Snippets Issue

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#12487] opened 2016-09-22 20:52 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

I have the following user defined snippet:

`"MyInput": {
        "prefix": "MyInput",
        "body": [
            "<input type=${Type} name=${Name} id=${Name} value=${Value}>"
        ],
        "description": "Enters a full input tag into code."
    }`

The first time I try to use the snippet by typing "MyInput" and hitting `TAB` I experience an issue once I start to type in the "type" of input it is.  The same thing happens for any user defined snippet that I have created so I'm thinking that either my snippets are coded incorrectly or there is some type of glitch.  Instead of getting "text" when I hit the `TAB` key I get `<text></text>`.  If I undo my typing and then type `myinp` all over again and tab through the process, I get the desired result.

Language for demonstration purposes is basic HTML.

Please watch the video inserted below:

![2016-09-22_15-42-23](https://cloud.githubusercontent.com/assets/6462859/18765619/1f8efc9c-80dc-11e6-860c-e2fe009323d5.gif)

**Comment by chrmarti** [comment] 2016-09-22 21:06
Looks like Intellisense jumps in.

**Comment by aeschli** [comment] 2016-09-26 17:26
It's emmet used while in a snippet template mode

**Comment by alexandrudima** [comment] 2016-09-27 20:49
Out of the box keybindings for tab:
```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "insertSnippet",
                                     "when": "config.editor.tabCompletion && editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "jumpToNextSnippetPlaceholder",
                                     "when": "editorTextFocus && inSnippetMode" },
{ "key": "tab",                   "command": "acceptQuickFixSuggestion",
                                     "when": "editorFocus && quickFixWidgetVisible" },
{ "key": "tab",                   "command": "acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible" },
```

From looking at the gif, I believe it is safe to eliminate a few (which are obviously not active or which don't cause such funny edits) which brings us down to:
```
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "insertSnippet",
                                     "when": "config.editor.tabCompletion && editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus" }
```

@egamma (`editor.emmet.action.expandAbbreviation`) @jrieken (`insertSnippet`) - can you please investigate

**Comment by jrieken** [comment] 2016-10-08 10:11
I have added `!inSnippetMode` to block tab completion when filling in a snippet

**Comment by alexandrudima** [comment] 2016-10-31 12:03
@BrandonRice Can you please share with us your `keybindings.json` file. Out of the box this works for me, so I'm thinking you have perhaps defined some different keybindings around tab?

**Comment by BrandonRice** [comment] 2016-10-31 13:48
@alexandrudima I actually haven't set up any user defined keybindings.  I have attached the code below:

`
// Place your key bindings in this file to overwrite the defaults
[
]
`

**Comment by alexandrudima** [comment] 2016-10-31 14:01
I think this might be a duplicate of #5751 

I don't know why I cannot reproduce on my machine, but I can reproduce #5751, the issue being:
* if the editor is already in snippet mode
* and a snippet is inserted
* in the end, the editor leaves snippet mode entirely, instead of remaining in the second snippet

I'm thinking for you somehow after the first `td|` is expanded into `<td>|</td>`, the editor is in snippet mode. Then, the `MyInput` introduces a new snippet and the editor is **not** (bug here) in snippet mode. Since it is not in snippet mode, pressing `Tab` will not jump to the next snippet, but fall through and execute the next command (emmet expand abbreviation in this case).

**Comment by alexandrudima** [comment] 2017-03-02 10:08
Let's track in #5751

**Closed by alexandrudima** 2017-03-02 10:08 UTC
Labels: bug, needs more info, snippets, suggest
