### ISSUE TITLE
Why does Vs code cannot prompt me when import node-modules after the upgrade?

### ISSUE THREAD

**Issue by denghejun** [Microsoft/vscode#26126] opened 2017-05-06 17:19 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.5|;

---

Steps to Reproduce:

1.create a new JavaScript file named: service.js
2.write code: "import React from 're'"

What I want to say is why the import not auto completed after the VS code has been upgraded?

I mean when I am typing the "import React from 're'", it should prompt me like "import React from 'react'".

It works good before I upgrade to the latest version.

**Comment by mjbvz** [comment] 2017-05-08 16:31
This sounds like a duplicate of #23962

Try triggering the suggestions using the keybinding, or set:

```json
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```

to restore the previous behavior

**Closed by mjbvz** 2017-05-08 16:31 UTC
