### ISSUE TITLE
VSCode detecting wrong / key

### ISSUE THREAD

**Issue by VIMGAS** [microsoft/vscode#111223] opened 2020-11-24 10:17 UTC
- VSCode Version:
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open VSCode
2. Try to use Toggle Line Comment shortcut
3. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

Some extra input:

I noticed that when I try to create e new keybinding, VSCode understands `/` as `;` and understands `;` as `[Semicolon]`, just like the screenshot below:
![Peek 2020-11-24 07-13](https://user-images.githubusercontent.com/20145874/100080663-ddcf9000-2e24-11eb-9652-9b66ba1f693e.gif)

I use the english keyboard layout for coding, but I am brazillian and use Portuguese(Brazil) as my primary input configuration. It makes no sense to me, since I always open VSCode with the english input configured, but in my primary layout the `/` key position is, indeed, `;`, not sure if that is causing the bug.

Below are my installed keyboard layouts:
![image](https://user-images.githubusercontent.com/20145874/100081083-60584f80-2e25-11eb-9b01-ea8e11426b95.png)

Tried to change keyboard layouts order to put English first but the bug persists.

**Comment by VIMGAS** [comment] 2020-11-24 10:24
> Tried to change keyboard layouts order to put English first but the bug persists.

Actually, after changing the order and restarting VSCode the bug went away. What is causing is the bug is that VsCode is reading inputs from the first keyboard layout configured and not the active one! Not sure if that is a VSCode or Electron bug.

**Comment by alexdima** [comment] 2020-11-25 15:43
Yes, I'm sorry about that. Duplicate of https://github.com/microsoft/vscode/issues/24166

**Closed by alexdima** 2020-11-25 15:43 UTC
Labels: linux
