### ISSUE TITLE
Add ability to exclude files using files.exclude ignoring case

### ISSUE THREAD

**Issue by anton-gorbikov** [Microsoft/vscode#20263] opened 2017-02-09 09:09 UTC
- VSCode Version: 1.10 Insider
- OS Version: Windows 7

Steps to Reproduce:

1. Create a folder, for example: someCamelCaseTestFolder;
2. Add files.exlude rule: "somecamelcasetestfolder": true;

Actual result: Folder is still visible in the VS Code Explorer.
Expected result: Folder should be hidden, ignoring the case (like in .gitignore for example).

As far as in Windows there is no ability to create two different folders "AAA" and "aaa" in the same parent folder I don't see any reason to make exclude pattern case sensitive.

![files exclude](https://cloud.githubusercontent.com/assets/5469718/22776382/7d295d50-eec0-11e6-93a2-39e08798d634.png)

**Comment by roblourens** [comment] 2017-09-04 05:07
duplicate of https://github.com/Microsoft/vscode/issues/10633

**Closed by roblourens** 2017-09-04 05:07 UTC
Labels: feature-request, search
