### ISSUE TITLE
@angulr/core flagged as module not found by tslint

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#34960] opened 2017-09-25 13:19 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
gitlens|eam|5.2.0
tslint|eg2|1.0.9
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.29.1
Align|ste|0.2.0
ayu|tea|0.8.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Files that I've been using for weeks without any errors showing are now flagging my components with an error in lines like

`import { Component, OnInit } from '@angular/core';`

<img width="548" alt="screen shot 2017-09-25 at 9 16 20 am" src="https://user-images.githubusercontent.com/835148/30810246-7076d072-a1d2-11e7-9423-f954d2ba8d9e.png">

2. not sure what's different.  Same project, using Code's version of TS.

Could be user error, but I have no idea why and haven't changed anything, other than updating each Insiders build.

**Comment by sandy081** [comment] 2017-09-25 13:53
@smlombardi Is the error coming from TSLint extension?

**Comment by smlombardi** [comment] 2017-09-25 15:09
I believe so.  It looks like this:

<img width="554" alt="screen shot 2017-09-25 at 11 08 58 am" src="https://user-images.githubusercontent.com/835148/30815739-0a408a04-a1e2-11e7-9b8f-ad45d5b36664.png">

<img width="1279" alt="screen shot 2017-09-25 at 11 09 22 am" src="https://user-images.githubusercontent.com/835148/30815742-0c656bf6-a1e2-11e7-8465-26aece5252df.png">

**Comment by smlombardi** [comment] 2017-09-25 19:43
I found this issue: https://github.com/Microsoft/vscode/issues/34681

However, I do not have the ability to switch versions of Typescript

<img width="581" alt="screen shot 2017-09-25 at 3 43 20 pm" src="https://user-images.githubusercontent.com/835148/30827489-46b03e96-a208-11e7-9e2c-7a3ba21bf162.png">

**Comment by mjbvz** [comment] 2017-09-25 19:48
I think this error is from the normal TS extension. This is a duplicate of #34681. Let me know if you have any trouble with Andy's instructions on that issue for switching TS versions. You can also just install typescript to your current workspace and then switch to that version

**Closed by mjbvz** 2017-09-25 19:48 UTC
Labels: insiders, needs more info
