### ISSUE TITLE
Unable to use shortcuts in integrated terminal

### ISSUE THREAD

**Issue by baydet** [microsoft/vscode#116164] opened 2021-02-09 05:22 UTC
Issue Type: <b>Bug</b>

At some point they just stopped working. App reloading didn't help.

VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:23:20.010Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|--crash-reporter-id 5eb15274-2b6f-401e-90d4-e4d02f907449|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
subword-select|all|0.0.1
clipboard-history|Anj|1.0.7
quitcontrol-vscode|art|3.1.3
pgformatter|bra|1.16.0
gitignore|cod|0.6.0
jshint|dba|0.11.0
githistory|don|0.6.14
prettier-vscode|esb|5.9.1
gitlab-workflow|Git|3.11.2
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
rest-client|hum|0.24.4
vscode-edit-csv|jan|0.5.4
a08-test-highlighter|jim|0.0.2
recent-files|jun|1.1.10
dotenv|mik|1.0.1
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.2.531887795-dev
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
node-debug2|ms-|1.42.5
vsliveshare|ms-|1.0.3629
debugger-for-chrome|msj|4.12.12
vscode-subword-navigation|ow|1.2.0
gitpatch|par|0.2.1
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
python|tht|0.2.3
gitblame|wad|6.0.2
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by baydet** [comment] 2021-02-09 05:30
The same reason as here #116163

Also `Kill the active Terminal instance button` (and shortcut) is not working anymore. Now it is just clearing terminal

**Comment by meganrogge** [comment] 2021-02-09 15:49
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

Duplicate of #116163

**Closed** 2021-02-09 15:50 UTC
Labels: *duplicate

**Comment by baydet** [comment] 2021-02-10 06:27
That was fast! Thanks!
