### ISSUE TITLE
terminal cut zsh PROMPT to two lines and not show fully

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#8894] opened 2016-07-08 05:29 UTC
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.2
- shell: zsh(oh-my-zsh with theme robbyrussell)

Steps to Reproduce:

1. open a project
2. CTRL + ` open terminal

actual behavior
PROMPT was cut to two lines and not show fully
![2016-07-08 1 23 43](https://cloud.githubusercontent.com/assets/2631733/16678214/859c4f0c-450f-11e6-9605-5adfddf935e0.png)

expected(iTerm2 example)
![2016-07-08 1 23 51](https://cloud.githubusercontent.com/assets/2631733/16678218/8ff0c050-450f-11e6-9874-0d6573834f6a.png)

**Comment by Tyriar** [comment] 2016-07-08 16:56
Duplicate of https://github.com/Microsoft/vscode/issues/8219

**Closed by Tyriar** 2016-07-08 16:56 UTC
