### ISSUE TITLE
vscode 1.0 editor.fontSize not work for tip or autocomplete

### ISSUE THREAD

**Issue by sswangifly** [Microsoft/vscode#5302] opened 2016-04-15 06:05 UTC
- VSCode Version:1.0
- OS Version:windows 10

Steps to Reproduce:

1. change the editor.fontSize in the settings.json
2. the editor font size has success changed,but not the tip and autocomplete

**Comment by joaomoreno** [comment] 2016-04-28 12:39
Autocomplete: #2465

What do you mean by *tip*?

**Comment by sswangifly** [comment] 2016-05-23 06:05
yes IntelliSense.

**Comment by joaomoreno** [comment] 2016-05-24 07:53
Closing as duplicate of #2465

**Closed by joaomoreno** 2016-05-24 07:53 UTC
Labels: needs more info
