### ISSUE TITLE
sh: 1: /scripts/wslServer.sh: not found

### ISSUE THREAD

**Issue by frank1russo** [microsoft/vscode#198298] opened 2023-11-15 13:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.84.2
- OS Version: Windows 11

Steps to Reproduce:

1. From wsl command line, run "code ."
2. VSCode opens with error message: "VS Code Server for WSL closed unexpectedly. Check WSL terminal for more details."
3. The WSL terminal shows the following:
> [2023-11-15 13:05:28.337] Extension version: 0.81.8
> [2023-11-15 13:05:28.338] L10N bundle: undefined
> [2023-11-15 13:05:28.345] authorityHierarchy: wsl+Ubuntu
> [2023-11-15 13:05:28.345] WSL extension activating for a local WSL instance
> [2023-11-15 13:05:28.359] Resolving wsl+Ubuntu, resolveAttempt: 1
> [2023-11-15 13:05:28.359] NodeExecServer run: C:\Windows\System32\wsl.exe --status
> [2023-11-15 13:05:28.982] WSL feature installed: true (wsl --status)
> [2023-11-15 13:05:28.982] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose
> [2023-11-15 13:05:29.560] 1 distros found
> [2023-11-15 13:05:29.561] Starting VS Code Server inside WSL (wsl2)
> [2023-11-15 13:05:29.561] Windows build: 22621. Multi distro support: available. WSL path support: enabled
> [2023-11-15 13:05:29.561] Scriptless setup: false
> [2023-11-15 13:05:29.655] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu -e sh -c [ -f '/tmp/vscode-distro-env.otd4J2' ] && cat '/tmp/vscode-distro-env.otd4J2' || echo ''
> [2023-11-15 13:05:29.772] WSL daemon log file: 
> [2023-11-15 13:05:29.772] Probing if server is already installed: if [ -d ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
> [2023-11-15 13:05:29.772] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu -e sh -c if [ -d ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
> [2023-11-15 13:05:30.328] Using shell environment from invoking shell: /tmp/vscode-distro-env.otd4J2
> [2023-11-15 13:05:30.432] Probing result: install-found x86_64
> [2023-11-15 13:05:30.432] Server install found in WSL
> [2023-11-15 13:05:30.433] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=649067668-209844331-2511855524-2873055476 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: CreateProcessParseCommon:708: Failed to translate C:\Program Files\Microsoft VS Code
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate c:\Users\frruss\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\PowerShell\7
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Python311\Scripts\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Python311\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\system32
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\Wbem
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\OpenSSH\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Microsoft VS Code\bin
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\dev\alerts\allure-2.22.1\bin
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Git\cmd
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\dotnet\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\PowerShell\7\
> [2023-11-15 13:05:31.145] <3>WSL (405) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
> [2023-11-15 13:05:31.145] sh: 1: /scripts/wslServer.sh: not found
> [2023-11-15 13:05:31.194] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
> [2023-11-15 13:06:44.012] Download in background is enabled

4. The section where my previous files are open shows the message: 
> The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'vscode-remote://wsl%2Bubuntu/home/frruss/src/detection-commons/src/components/EnhancedAGGrid/__stories__/EnhancedAGGrid.story.tsx'

**Comment by moweiser** [comment] 2023-11-15 14:49
+ same

**Comment by frank1russo** [comment] 2023-11-15 16:24
I'm not sure why this matters or why it just started today, but I started up Powershell as a windows administrator, and now everything works. It's not really convenient for me because I have to request permission each time I run something as an admin, so a solution where I don't need that would be ideal.

**Comment by moweiser** [comment] 2023-11-16 08:55
I also didn't have any problems today, started all normally. Welp!

**Comment by daltonv** [comment] 2023-11-16 09:37
This seems related to this issue https://github.com/microsoft/vscode/issues/198285

**Comment by HecGonOra** [comment] 2023-11-16 10:49
Same here after patch 2023-11 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (**KB5032190**)

**Comment by aeschli** [comment] 2023-11-29 17:13
duplicate of https://github.com/microsoft/vscode/issues/198285

**Closed by aeschli** 2023-11-29 17:13 UTC
