### ISSUE TITLE
Scrollable area's width does not reduce when long lines are removed/reduced

### ISSUE THREAD

**Issue by realh** [Microsoft/vscode#64241] opened 2018-12-03 17:41 UTC
Issue Type: <b>Feature Request</b>

If any lines are too long to fit the width of the viewport it becomes horizontally scrollable. The trouble is that removing or reducing the length of those lines doesn't reduce the width of the view so that the scrollbar can be removed. I have to close the tab and reopen the file.

I try to avoid long lines, but sometimes it's difficult to avoid temporarily creating one before reformatting. The horizontal scrolling is a bit of a nuisance when trying to scroll vertically with a touchpad.

I realise it's much harder to keep track of line lengths to achieve auto-shrinking than it is to implement auto-growing, but I hope you can do it.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

**Comment by usernamehw** [comment] 2018-12-07 18:58
duplicate of #13516 or not?

**Comment by realh** [comment] 2018-12-07 19:49
Yes, I think it's a duplicate. Sorry I didn't find the old report, but I did try to search for existing issues.

**Closed** 2018-12-10 08:36 UTC
Labels: editor-rendering, feature-request
