### ISSUE TITLE
CTRL+F2 Multiple Occurrence Edition fails at LineWrap-End

### ISSUE THREAD

**Issue by ksowada** [microsoft/vscode#69723] opened 2019-03-03 02:53 UTC
Hi Thanks for the Great Software,
just reporting a serious issue when using CTRL+F2
when 1 Occurence is exactly wrapping at end of line, 
the used algorithm makes serious errors, 
editing at a one or more chars wrong position on the wrapped Occurence,
did supply a video, 
[VSCODE_F2_ERR.zip](https://github.com/Microsoft/vscode/files/2922705/VSCODE_F2_ERR.zip)

**Comment by alexdima** [comment] 2020-01-10 10:15
Duplicate of #65815

**Closed by alexdima** 2020-01-10 10:15 UTC
Labels: bug, editor-find, editor-wrapping
