### ISSUE TITLE
Menu: window buttons should never be hidden

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52918] opened 2018-06-26 10:25 UTC
Refs: #52854

It looks like currently the menu pushes the window buttons out when the size is small. I think the buttons should always be visible:

![image](https://user-images.githubusercontent.com/900690/41905570-e7e76edc-793b-11e8-950b-9091fd31552e.png)

**Comment by bpasero** [comment] 2018-06-26 10:30
It also looks like the application icon is moving when I resize the window just a bit.

**Comment by sbatten** [comment] 2018-07-03 22:16
resolving as dupe of #52920

**Closed by sbatten** 2018-07-03 22:16 UTC
Labels: bug, workbench-menu
