### ISSUE TITLE
Script defined in package.json not working on clicking 'run script' shown on hover

### ISSUE THREAD

**Issue by trishalanaman** [microsoft/vscode#160279] opened 2022-09-07 10:30 UTC
In package.json, hover on any scripts defined.
It will show 2 options- run script | debug script
Clicking on the run script usually opens a new terminal and runs that script, but after I updated the VS Code today on 07-09-2021, nothing is happening on clicking the run script.

https://user-images.githubusercontent.com/47503078/188856672-ddd8a631-550b-48e8-b56b-8f75ca31d8a3.mp4

**Comment by connor4312** [comment] 2022-09-07 15:47
Duplicate of https://github.com/microsoft/vscode/issues/159881

**Closed by connor4312** 2022-09-07 15:47 UTC
Labels: debug
