### ISSUE TITLE
Intellisense Not Working on Mac

### ISSUE THREAD

**Issue by rhrahul** [microsoft/vscode#84830] opened 2019-11-14 14:31 UTC
Version: 1.40.1
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

It's working fine in Windows, It automatically suggest before I finish writing code, but not anymore  in Mac. Please Help.

Thanks & Regards

**Comment by rebornix** [comment] 2019-11-14 22:44
@rhrahul could you please provide more information, like what language are you using, are you working on the same project, do you see the same issue if you disable all extensions by `code --disable-extension`?

**Comment by rhrahul** [comment] 2019-11-15 07:14
Hey @rebornix , THANKS FOR REPLY.
I am using JavaScript.
And I also tried with disabling all extensions, but still not working.

**Comment by oliviayizhang** [comment] 2019-11-16 14:26
Intellisense stopped working for me unless hot-reloading, but then stops working shortly after, very frustrated! 
I am also working in Javascript, disabling all extensions didn't help.
<img width="393" alt="Screen Shot 2019-11-16 at 9 25 12 AM" src="https://user-images.githubusercontent.com/28352311/68994641-3607a580-0853-11ea-88e0-bcb2508783cc.png">

**Comment by mals14** [comment] 2019-11-17 00:03
Intellinsense in javascript stopped working for me also. I do not exactly when it stopped working as I tinkered with a js file after quite a while. I did use vscode using ```code --disable-extension``` also and still no IntelliSense.

Not sure if this is useful, but I see this in output.

[Info  - 7:01:29 PM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 7:01:29 PM] <syntax> Forking...
[Info  - 7:01:29 PM] <syntax> Starting...
[Info  - 7:01:29 PM] <semantic> Forking...
[Info  - 7:01:29 PM] <semantic> Starting...

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mals14** [comment] 2019-11-17 00:14
I downloaded the Insider version, and it appears that it is fixed in that version. But the insider version does not have any of my extensions installed. :(

I wonder if I can go to the previous month version. Will look into how to do that.

**Comment by mals14** [comment] 2019-11-17 00:17
I installed 1.39.2 but that does not work either :(

**Comment by mals14** [comment] 2019-11-17 15:40
So the problem is on of my installed extensions. I disabled all extensions with cmd-shift-P, and then restarted, and IntelliSense started working. IT did not work with ```code --disable-extension```,and now I am enabling extensions one by one and checking. Painful way to do it.

It there any other way to figure out which extension might be interfering with javascript IntelliSense? Thanks.

**Comment by mals14** [comment] 2019-11-17 16:01
Kite extension is what was causing this it seems. Hope this helps.
I disabled Kite extension in the javascript workspace. 

Wish there was a way to figure out which extension is interfering with Intellisense...

**Comment by mjbvz** [comment] 2019-11-18 19:38
@rhrahul Are you still seeing this problem? If so, please provide the information from our [issue reporting guidelines](https://aka.ms/vscodeissuereporting)

**Comment by rhrahul** [comment] 2019-11-19 08:11
Hey @mjbvz , I am still facing this issue.

Version: 1.40.1
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0


Language I am using : JavaScript

And I also tried by disabling all extensions, but still not working.

What more information you'll need?

**Comment by mjbvz** [comment] 2019-11-19 23:46
Please share steps to reproduce the issue

**Comment by mjbvz** [comment] 2019-11-20 18:23
What do you see? Does this happen for all files and all projects you open?

We can't investigate this without more information about what is going wrong

**Closed** 2019-11-27 19:14 UTC
Labels: needs more info
