### ISSUE TITLE
[Javascript]Wrong Syntax Highlighter

### ISSUE THREAD

**Issue by longque** [Microsoft/vscode#4060] opened 2016-03-12 06:18 UTC
When the name of a variable begins with "var",VSC will make "var" as a kind of color and make the end of its name as a different kind of color.
However,if the name of a variable is "*var*",it will make its name as a kind color.
![-1](https://cloud.githubusercontent.com/assets/8530043/13721271/95c81ab6-e85b-11e5-9c10-f021ec277584.png)
* VERSION:0.10.10
* THEME:Light+
* NODEJS(My Project):v4.2.3(I used ES6)
* PLATFORM:Windows 10

**Comment by felixfbecker** [comment] 2016-03-12 10:36
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/112

**Closed** 2016-03-12 16:30 UTC
