### ISSUE TITLE
Metadata is not getting reverted

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#226708] opened 2024-08-27 06:47 UTC
Testing #226665

- Before reverting metadata

![Image](https://github.com/user-attachments/assets/ce087b62-9924-4ae9-98f8-56a5525efec3)

- After reverting

![Image](https://github.com/user-attachments/assets/a99c6b99-df00-427a-b262-fe89754997dd)

🐛 language remains `python`. If I try to revert, nothing happens.

**Comment by rebornix** [comment] 2024-08-29 21:45
I was expecting the revert will revert the content to the version on the left side if the diff editor is opened from the timeline view, but it seems reverting to something different.

https://github.com/user-attachments/assets/8b23bc2f-77c0-48ee-910b-f167b1eef0b1

**Comment by rebornix** [comment] 2024-08-29 21:46
I think this can be fixed next month.

**Comment by DonJayamanne** [comment] 2024-08-29 22:03
Thats a duplicate of https://github.com/microsoft/vscode/issues/225204
Marking as `verified` as metadta gets reverted

**Closed by DonJayamanne** 2024-08-29 22:03 UTC
Labels: bug, verification-found, notebook, notebook-diff

**Comment by DonJayamanne** [comment] 2024-08-29 22:05
@rebornix Yes, the plan is to fix next month, I have a PR, but do not want to merge it just yet
Its a slightly convoluted issue,
