### ISSUE TITLE
Different `wrappingColumn` settings based on language mode.

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#1073] opened 2015-12-07 13:32 UTC
For example, `0` for markdown, large enough for code.

**Comment by Krzysztof-Cieslak** [comment] 2016-01-05 19:13
It would be nice to extend it for giving genral per language configuration. It was also suggested in F# support repo (as tabs in F# are not allowed by default)

**Comment by mjbvz** [comment] 2016-11-11 23:02
Closing this as a duplicate of #2253 (I know this issue was opened first, but the other issue has more comments on it)

**Closed by mjbvz** 2016-11-11 23:02 UTC
Labels: duplicate, feature-request
