### ISSUE TITLE
Comment buttons/actions too far away on a wide screen

### ISSUE THREAD

**Issue by evangrayk** [microsoft/vscode#80276] opened 2019-09-03 18:01 UTC
Thread-/comment-level commands and context buttons appear on the far right side of the comment. On a wide screen, this puts the buttons very far away from the context, making it difficult to use / inaccessible. Some kind of max-width or being resizable would be nice.

<img width="1878" alt="comment_api_too_wide" src="https://user-images.githubusercontent.com/1762690/64196814-81f0a400-ce39-11e9-9712-a955b6650efe.png">
Notice that "Reply" and "Unresolve" are very far to the right. This is from a laptop, but the effect can be much worse depending on your monitor.

**Comment by alexr00** [comment] 2022-12-05 10:05
Even though this issue is older, marking as a duplicate of https://github.com/microsoft/vscode/issues/150824 since that's where the discussion is occurring.

**Closed by alexr00** 2022-12-05 10:05 UTC
Labels: feature-request, ux, comments
