### ISSUE TITLE
Settings UI resets when it regains focus.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/vscode#46372] opened 2018-03-22 22:50 UTC
### Issue Type
Bug

### Description

Every time I open my settings, switch to another tab, and then switch back, the settings UI collapses any setting groups  I had open, as well as scrolling back to the top.  Effectively this loses my place; I have to scroll back down and re-open the settings group.  If I'm flipping back and forth while tweaking some settings then this can quickly get *really* annoying.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-116-generic

Reproduces without extensions

**Comment by sandy081** [comment] 2018-03-26 08:55
Duplicate of ##28394

**Closed** 2018-03-26 08:55 UTC
Labels: *duplicate, settings-editor
