### ISSUE TITLE
String DocumentFilter should only match scheme 'file' and 'untitled'

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#21886] opened 2017-03-03 12:01 UTC
- VSCode Version: 1.10.x

Document filters that are only string based should only match scheme file and untitled. So if an extension registers a feature provider for 'bat' for example the provider should only be invoked for 'file' and 'untitled' scheme and not for example for 'git' scheme.

**Comment by dbaeumer** [comment] 2017-03-03 12:01
@egamma FYI.

**Comment by jrieken** [comment] 2017-03-07 16:33
@dbaeumer Pushed this to master, please verify with the language servers.

@aeschli You might need to adjust some selectors for html, json, etc that work off the virtual state

**Comment by dbaeumer** [comment] 2017-03-07 20:02
@jrieken will do. Thanks!

**Comment by chrmarti** [comment] 2017-03-27 21:21
@jrieken This breaks the interactive playground. Adding `walkThroughSnippet` to the `_defaultSchemes` in languageSelector.ts appears to fix it. Please advise.

**Comment by jrieken** [comment] 2017-03-28 07:01
Please share more details about your problem? Are you registering your document as `walkThroughSnippet` and what extension do you expect to work with that? The consequence of our change is that those extensions must not opt in and adjust their language selector

**Comment by chrmarti** [comment] 2017-03-28 13:57
The embedded editors use models with `walkThroughSnippet` as their URL scheme. These URLs no longer match the registered languages, they did before. As a consequence editorModelConext.ts deactivates all contexts and actions like Format and Rename are no longer available in the embedded editors, that's a regression.

**Comment by jrieken** [comment] 2017-03-28 14:12
Yes, that is the new design. It's not enough for the languages to just register with `'langId` anymore but they must spell out all schemes they should support (`file`, `untitled`, `walkThroughSnippet `).

**Comment by jrieken** [comment] 2017-03-28 14:13
fyi @dbaeumer

**Comment by dbaeumer** [comment] 2017-03-28 15:09
The consequences of the old design was that the `walkThroughSnippet`s were honored by a lot of extensions although they can't actually do something meaningful with them. With the new design extension by default participate in file and untitled (what most extensions thought happens anyways) and you must explicitly opt in into more schemes. This is breaking by design.

**Comment by chrmarti** [comment] 2017-03-28 15:55
Chatted with @jrieken, he suggests to add `scheme: *` to the languages participating in the playground, effectively reversing the effect of this change. It would be easier and avoid matching all schemes to handle `walkThroughSnippet` like `untitled`. The original change meant to address issues with `git` and similar, not `walkThroughSnippet`, if I understand correctly.

**Comment by jrieken** [comment] 2017-03-29 10:10
We will revert the changes for March to give us more time for this

**Comment by jrieken** [comment] 2017-03-29 12:35
Moving to April for further discussion

**Comment by chrmarti** [comment] 2017-03-31 16:13
Another way to look at it is that the Playground document is at odds with the layering, because it comes with languages that are not in the core, but in extensions. Longer term we could move the document out of the core, while keeping the Playground URI scheme and editor as language-agnostic support for playgrounds in the core. That would allow for special-casing the Playground scheme in the core similarly to `untitled`. /cc @kieferrm

**Comment by dbaeumer** [comment] 2017-04-03 09:19
IMO we should not have any playground specific URI knowledge in the core. A Playground should be contributable by an extension without it being necessary to modify the core. 

I know that due to limitation we need to, but we should push hard to improve our system to not require thus.

**Comment by jrieken** [comment] 2017-04-03 09:40
> IMO we should not have any playground specific URI knowledge in the core.

Agree

>  A Playground should be contributable by an extension without it being necessary to modify the core.

Disagree. The extension API is there to enrich the core development cycle not these scenarios. IMO the playground should use the standalone editor *with* its language service implementation. It's problematic that playground samples bleed into the extension host and causing all kinds issues, like markers we don't really want.

**Comment by jrieken** [comment] 2018-04-12 15:49
Idea is to educate because it's hard to make the right (breaking) decision for every extension. As a first step, I have added an info-message that gets logged once for extensions that are under development and that use a lax-selector. Next step is a page with more documentation/information that we can link to.

**Comment by jrieken** [comment] 2018-04-18 13:01
@gregvanl Can you please review the text here: https://go.microsoft.com/fwlink/?linkid=872305. We also find a place in the docs for this. 

/cc @egamma

**Closed** 2018-04-20 09:05 UTC
Labels: api, feature-request, under-discussion
