### ISSUE TITLE
Tasks: Echo: false has no effect

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29567] opened 2017-06-27 10:32 UTC
Refs: #29442

Have `"echo": false` in yout tasks.json, notice the tasks still gets outputed in the panel, so it is crpytic to me what does this attribute do in the end.
Here's my tasks.json if needed

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "gulp",
            "task": "build",
            "presentation": {
                "echo": false,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "problemMatcher": [
                "$gulp-tsc"
            ]
        }
    ]
}
```

**Comment by michelkaporin** [comment] 2017-06-27 10:42
Works well for me.

It does not echo the command that is run by task if you set it to `false`:
`> Executing task: node_modules\.bin\gulp.cmd build <`

**Comment by isidorn** [comment] 2017-06-27 10:45
Does not work on my mac.

**Comment by Lixire** [comment] 2017-06-27 22:43
Works on Linux. Maybe the description could be more clear on what is/is not being echoed, though.

**Comment by dbaeumer** [comment] 2017-06-29 07:27
Need to find out why this is not working on the Mac. Not critical for June since this doesn't cause any big harm.

**Comment by dbaeumer** [comment] 2017-08-28 09:54
Worked for me on Windows. @isidorn lets check on your machine to see why this is not working under Mac. If echo is false I simply don't pass the string to the terminal so I don't see how this couldn't work on Mac.

https://github.com/Microsoft/vscode/blob/master\src\vs\workbench\parts\tasks\electron-browser\terminalTaskSystem.ts#L490

**Comment by isidorn** [comment] 2017-08-28 14:50
@dbaeumer sure, drop by any time to my machine and we can check it out

**Comment by dbaeumer** [comment] 2017-11-08 11:31
@isidorn can you still reproduce this. If yes I will drop by and have a look.

**Comment by isidorn** [comment] 2017-11-08 14:18
@dbaeumer I still get this.

**Comment by dbaeumer** [comment] 2017-11-08 15:43
Thanks. Lets look then in November.

**Comment by dbaeumer** [comment] 2017-12-04 10:56
@isidorn are you in tomorrow. Then I would drop by to investigate.

**Comment by isidorn** [comment] 2017-12-04 11:21
@dbaeumer no, I am wfh this week, we can do screen sharing if you would like

**Comment by dbaeumer** [comment] 2017-12-05 14:27
Using
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "dir",
            "command": "ls",
            "presentation": {
                "echo": false,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            }
        }
    ]
}
```

does not echo anything on the latest Insider. 

I will close the issue since I can't reproduce (anymore).

**Comment by dbaeumer** [comment] 2017-12-05 14:28
Note that gulp file sometimes echo the task they execute. My be this is what has been seen.

**Closed by dbaeumer** 2017-12-05 14:27 UTC
Labels: *not-reproducible, bug, mac, tasks
