### ISSUE TITLE
File dialog uses slash when backslash should be used in this case

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#195938] opened 2023-10-18 20:12 UTC
- Connect with a Mac to a Windows tunnel.
- Use `Open Folder` to open a folder on the tunnel machine.
- Notice that the `Open Folder` UI starts on the wrong folder (looks like Linux, e.g., `/home/chrmarti`) and interferes in folder navigation.
- Pick a folder, window reloads.
- `vscode.workspace.workspaceFolders` has a URI missing the drive letter. (e.g., `vscode-remote://tunnel%2Bdevbox-dev1/Users/chrmarti/devel/smktst`)

This then triggers errors in Dev Containers. Maybe the root cause is with the folder picker?

from @chrmarti in https://github.com/microsoft/vscode-remote-tunnels/issues/694

**Comment by connor4312** [comment] 2023-10-18 20:16
I see this as well in insiders.vscode.dev. Debugging minified code, somehow `getLastActiveFile()` returns a file from a different workspace, on a different remote authority than the one I'm connected to. I'm not sure how it got there, since I see the history's storage scope is workspace. I'm also having trouble getting it to repro in OSS.

If this is something that's expected that could happen, thought is to add an authority filter to the history service, as in https://github.com/microsoft/vscode/commit/51bdd25867302463083d8687d782f92627d2c413 (untested). What do you think @bpasero?

**Comment by bpasero** [comment] 2023-10-19 04:23
@connor4312 as for your change, we can have it, maybe introduce a filter interface and have scheme and authority in there to make it a bit nicer. Then have one method in the history service to check if a URI is filtered or not.

As for the issue here: would still be interesting how you got there. The history is a mix of previously opened editors (from workspace storage) and currently opened editors. What authority mismatch did you see?

**Comment by connor4312** [comment] 2023-10-23 18:29
The mismatch was `vscode-remote://tunneling%2Bmbp/Users/connor/Downloads/sept-items` (a macOS remote) being in history for `getLastActiveFile()` when I was on the `remote://tunneling%2Bhelios` remote (a Windows remote). That caused the `AbstractFileDialogService.defaultFolderPath()` to use that path as the default in `pickFolderAndOpen`.

The picker acts rather badly at that point:

<img width="651" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/fdc4d288-4677-4b4c-96b0-297187d4297f">

I'm not sure how exactly that path made it into the history for another remote. Also, for me the drive letter does appear in the path, so maybe it's a slightly different issue that Christof's?

**Comment by chrmarti** [comment] 2023-10-23 20:14
I see similar behavior and it works when I add `c:` manually, but not otherwise. It uses `/` as the path separator:


https://github.com/microsoft/vscode/assets/9205389/c3e52f76-42f9-4694-8168-0c6e9f03cf26

**Comment by connor4312** [comment] 2023-10-23 21:22
ah, okay, so we do have the same issue 👍

**Comment by bpasero** [comment] 2023-10-24 04:07
@connor4312 @chrmarti can you file an issue to the simple file dialog component that @alexr00 maintains with a description how to reproduce that state? Is that the source of this issue or just a separate issue?

If you have steps for this the issue of getting a bad last active file into the history, let me know.

**Comment by chrmarti** [comment] 2023-10-24 06:37
@alexr00 Please see the issue's description for detailed steps. My basic setup is: The folder picker starts at a Linux-like path when I'm connected from a Mac to a Windows remote tunnel.

**Comment by bpasero** [comment] 2023-10-26 04:45
I cannot reproduce: my Windows in Parallels ran `code-insiders tunnel` and my macOS connects to it:

<img width="1219" alt="image" src="https://github.com/microsoft/vscode/assets/900690/e075d6f4-a942-44fa-934c-a06858b9c731">

The picker seems to put the right path in with a drive letter.

**Comment by chrmarti** [comment] 2023-10-26 11:26
@bpasero Wouldn't you expect backslashes though?

**Comment by alexr00** [comment] 2023-10-26 13:16
Will fix for November.

**Comment by alexr00** [comment] 2023-11-01 16:08
@connor4312, the simple file picker gets the separator from the label service. In this case, it picks the Remote Tunnels label formatter, which appears to always set the separator to `/`.

**Comment by connor4312** [comment] 2023-11-01 16:43
Ah, hood find, that's been in there since the inception of tunnels 🙈 

I think there's still the (now much smaller) bug of reusing the directory from the wrong remote, but I hope that with the label formatter fixed the misbehaviors will be fixed. Will re-open this issue if not.

**Comment by connor4312** [comment] 2023-11-01 18:43
Okay, that fixes the separation issue. But the issue in [my video](https://github.com/microsoft/vscode/issues/195938#issuecomment-1775777408) where the "Downloads" segment keeps getting appended to the end, and where the bad path is reused, is still present.

**Comment by alexr00** [comment] 2023-11-02 14:43
@bpasero I think @connor4312 authority filter change in https://github.com/microsoft/vscode/commit/51bdd25867302463083d8687d782f92627d2c413 is good. If we are trying to open a file and we don't find something in the history that matches the authority then that's ok. We then fall back to the user's home folder.

**Comment by bpasero** [comment] 2023-11-02 15:14
Lets continue to discuss that change in a PR, or is that merged already?

**Comment by connor4312** [comment] 2023-11-02 15:17
I hadn't make a PR yet since I didn't know if that was the right approach at all. There's now one here: https://github.com/microsoft/vscode/pull/197237

**Closed** 2023-11-02 18:24 UTC
Labels: bug, remote, confirmed

**Comment by connor4312** [comment] 2023-11-03 16:17
That seems to have fixed it for me -- @chrmarti can you verify?

**Comment by chrmarti** [comment] 2023-11-06 10:35
The main issue is fixed, the picker works as expected now. It still uses forward slashes, it might make sense to fix this too:
![Image](https://github.com/microsoft/vscode/assets/9205389/0a0c1a4e-f4ea-42f3-949e-796e5d0929ee)

**Comment by alexr00** [comment] 2023-11-06 12:50
@chrmarti do you have the latest Remote Tunnels pre-release installed? @connor4312 made the fix for the slashes there.
