### ISSUE TITLE
SCM actions should be disabled without changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#232007] opened 2024-10-23 06:39 UTC
I think all of these only work with changes:

![Image](https://github.com/user-attachments/assets/a69a7ba2-17e1-49c4-90fa-99c692504642)

**Comment by lszomoru** [comment] 2024-12-10 20:19
Duplicate of [132108](https://github.com/microsoft/vscode/issues/132108)

**Closed by lszomoru** 2024-12-10 20:19 UTC
Labels: bug, scm
