### ISSUE TITLE
Always reopens window regardless of reopenWindows setting

### ISSUE THREAD

**Issue by fdncred** [microsoft/vscode#92852] opened 2020-03-17 14:30 UTC
Issue Type: <b>Bug</b>

Log ago I had a folder open in `C:\Temp\SomeFolder`. After recently upgrading to the latest version, whenever I start VSCode, my previous session opens as expected, but now that session opens another VSCode with the `C:\Temp\SomeFolde`r open. So, a single click is opening two vscode sessions. One of them I want, the other I don't.

So, my next step was to change the reopenWindows setting to none. I did that and now my last session doesn't open (as expected) but it's still opening my old `C:\Temp\SomeFolder` session.

How do I fix this?

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
search-crates-io|bel|1.2.1
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.0
json-tools|eri|1.0.2
vscode-test-explorer|hbe|2.17.0
rust-test-lens|hde|1.0.0
beautify|Hoo|1.5.0
reg|ion|1.0.1
vscode-edit-csv|jan|0.2.6
vscode-peacock|joh|3.6.0
roslynator|jos|2.9.0
csharpfixformat|Leo|0.0.84
rainbow-csv|mec|1.6.0
prettify-json|moh|0.0.3
csharp|ms-|1.21.14
mssql|ms-|1.9.0
python|ms-|2020.2.64397
cpptools|ms-|0.27.0-insiders2
powershell|ms-|2020.3.0
vscode-json-transform|oct|0.1.2
cargo|pan|0.2.3
rust|rus|0.7.0
crates|ser|0.4.9
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.7.2
vscode-rust-test-adapter|Swe|0.11.0
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
vscode-lldb|vad|1.5.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-03-17 14:58
/duplicate of #92318, which is scheduled to be fixed by the upcoming 1.43.1 recovery release.

**Closed** 2020-03-17 14:58 UTC
Labels: *duplicate
