### ISSUE TITLE
Scroll position not retained when switching back to a file that was opened from the source control diff section

### ISSUE THREAD

**Issue by 01abhishekjain** [Microsoft/vscode#28956] opened 2017-06-18 08:49 UTC
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: macOS Sierra 10.12.4

**Steps to Reproduce:**
1. open the diff view for any file from the Source Control panel
2. click the Open File button at the top-right corner of vscode
3. scroll to a different position in the file (doesn't matter if the cursor is also at the new position or the old position)
4. switch to a different file then back.

**What I saw:** the scroll position is back to where it was when the file was originally opened from the diff view.
**Expected:** the new scroll position should have been preserved; just like it does if the file was opened from the Explorer (or CMD+P)

Reproducible when vscode is started with extensions disabled.

**GIF of the bug:**
The cursor is moved from the initial line no.1577 to line no.1495. After switching back to this file, we are back to line no. 1577.
![issue](https://user-images.githubusercontent.com/11534188/27259414-9985f6f4-5430-11e7-8291-721910dc9a0d.gif)

**Comment by 01abhishekjain** [comment] 2017-06-18 08:53
Might be helpful to know that the issue isn't there if only the file is opened manually via CMD+P, like so:

Cursor is dropped to line no.1577 from the initial line no.1660. After switching back to this file, it's still at no.1577.
![non issue](https://user-images.githubusercontent.com/11534188/27259456-4fb0330e-5431-11e7-8b94-1163dd9be1df.gif)

**Comment by antcodd** [comment] 2017-08-23 07:03
May be a duplicate of #10663? This bug is really irritating and long standing.

**Comment by isidorn** [comment] 2017-11-17 10:35
Duplicate

**Closed by isidorn** 2017-11-17 10:35 UTC
Labels: diff-editor
