### ISSUE TITLE
Unexpected behaviour on quote wrapping

### ISSUE THREAD

**Issue by lerran80** [Microsoft/vscode#21767] opened 2017-03-02 13:33 UTC
- VSCode Version: 1.10.1
- OS Version: Mac OS X El Capitain

Steps to Reproduce:

1. Write foo, unquoted.
2. Select foo
3. Type "
    (It will become "foo")
4. Type [arrow right] to move the cursor away from the selection 
   (it will become "fo"")

Coming from atom, I expected it to just be "foo". It quickly becomes an annoyance as I have to always get back and correct it.

Also:

1. Type " 
    ("" will show, with the cursor in the between the quotes)
2. Type a 
   (it will become ä", which I believe is not the desired result in any circumstance. It should be just ä or "a" - for me at least, the second option would be the most useful)

**Comment by lerran80** [comment] 2017-03-03 12:09
I forgot to mention. Backtiks have a similar bug. They have the same behaviour as my first example and:

1. Write foo, unquoted.
2. Select foo
3. Type `
    (It will become `foo`)
4. Type {
    (It will become `fo`{`, that I believe is not the desired result in any circumstance)

In atom, it becomes `{foo}`. Speeding up javascript coding, when you are trying to include a variable in a string.

**Comment by alexandrudima** [comment] 2017-03-08 11:17
@lerran80 I cannot reproduce this behaviour. Is it possible you have a keyboard layout where `"` or `` ` `` have some special function (i.e. accents)?

This is what I get when:
* I select foo
* I type `"`
* I press right arrow
![21767](https://cloud.githubusercontent.com/assets/5047891/23701888/1874e7dc-03f9-11e7-89ac-d3c1901f2d35.gif)
arrow

**Comment by lerran80** [comment] 2017-03-08 18:44
Hi, my keyboard layout is "U.S.International - PC".

Really, changing to "US" makes the issue go away. Which is unfortunately not a solution for me as I need to be able to write stuff in both English and Portuguese.

**Comment by panitaxx** [comment] 2017-03-22 13:39
This happens on my mac too under  U.S.International - PC. Usually when in this keyboard language quote characters behave like a dead key so if you type " + U that gives you ü or ' + a =á. If you want just the quotes you can type space or right arrow.  When is confusing is when quote wrapping. VS Code wraps in quotes and replaces the last character with another quote. It is annoying especially with JSON.   Atom has the correct behavior when quote wrapping that is: you select text, type ", then space or right arrow, the text gets surrounding quotes.

**Comment by alexandrudima** [comment] 2017-03-24 16:19
Since `'` and `"` are used for input building (composition) under the US Intl kb layout, we cannot distinguish the user intent after pressing a single `"`. e.g.:
* when wanting to insert `ä` one would type <kbd>"</kbd> and <kbd>a</kbd>
* when wanting to insert `"` one could type <kbd>"</kbd> and <kbd>"</kbd> (press it twice for example).

We receive the `"` typed immediately after the first keypress. This is needed in order to support other composition cases such as CJK languages.

With the fix for #15825, we now no longer do any smartness of surrounding character pairs, auto closing characters, etc. when inside a composition.

So when <kbd>"</kbd> is typed, the selected text will be overtyped. This allows for example overtyping a selection with ä (by replacing the selected text with ä).

**Closed by alexandrudima** 2017-03-24 16:19 UTC
Labels: bug, editor-input, keyboard-layout, mac

**Comment by panitaxx** [comment] 2017-04-13 22:12
@alexandrudima can it be like the Atom behavior, no overtyping but quote wrapping.  Example:
On us-international key layout
type foo
select
type "
press right arrow
result: "foo"

**Comment by lerran80** [comment] 2017-04-14 02:51
Also, in Atom, us-international works identically to us-english layout, with all the smartness. If you type quotes, it just inserts a pair and positions the caret in between them.

I think it is safe to assume there will be no variable names starting letters like "ä" or "é". Most times, maybe every single time, these letters will appear inside quotes. So, if you type " when not inside quotes, you get a pair. If you type " from inside pair of quotes it waits for the next type before deciding what to do.

Could you guys do it as well?

At least for me, this issue is a productivity killer, as I usually forget the "smartness" is not there and end up making typos all the time.


The current behaviour is less buggy. But still buggy. Example:
- write "foo"
- press shift + command + left arrow
You end up with ""foo"

**Comment by dandeveloper** [comment] 2017-09-03 12:30
I would like it works like Atom's behaviour in En-international keyboard layout.
I think it is the best behaviour to work using this layout.
