### ISSUE TITLE
Long Text longer than 10000 letters wrapped with [...]

### ISSUE THREAD

**Issue by Serpentsoft** [Microsoft/vscode#27380] opened 2017-05-27 21:42 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.2|
|php-pack|felixfbecker|1.0.1|
|mssql|ms-mssql|1.0.0|
|wordpress-snippet|tungvn|1.1.2|;

---

Steps to Reproduce:

1. I try to paste a very long text (Base64Encoded) I noticed that the text wrapped and ends with [...]
2. It stops in Col (10,000).

**Comment by cnshenj** [comment] 2017-07-06 17:57
Also, "END" (go to line end) key no long works when this happens. "HOME" works fine.

**Comment by alexandrudima** [comment] 2017-11-27 12:59
Duplicate of #7772

**Closed by alexandrudima** 2017-11-27 12:59 UTC
Labels: bug, editor-rendering
