### ISSUE TITLE
opening slow

### ISSUE THREAD

**Issue by nikhilsingh884** [microsoft/vscode#181895] opened 2023-05-09 14:03 UTC
Type: <b>Performance Issue</b>

It was good until I started learning react after installing node modules a couple of times. After that I think it is taking 20 to 25 seconds to open which previously was about a couple of seconds.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.02GB free)|
|Process Argv|--crash-reporter-id 00ce20df-3204-454a-90d9-81f963d3e34a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	  2236	code main
    0	   157	 10696	extensionHost [1]
    0	    78	  1128	     electron-nodejs ("C:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=10696)
    0	    75	 16644	     electron-nodejs ("C:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\NIKHIL\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=10696)
    0	    81	 18084	     electron-nodejs ("C:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10696)
    0	   167	 10720	window [1] (styles.css - react-project-1 - Visual Studio Code)
    0	   100	 13860	shared-process
    0	    87	 14072	     ptyHost
    0	    61	   240	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\NIKHIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 14064	       console-window-host (Windows internal process)
    1	   185	 14360	   gpu-process
    0	    81	 15348	fileWatcher [1]
    0	    27	 18448	   crashpad-handler
    0	    48	 20976	   utility-network-service
    0	    87	 22864	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (styles.css - react-project-1 - Visual Studio Code)
|    Folder (react-project-1): 18 files
|      File types: jsx(5) json(2) js(2) html(1) md(1) jpg(1) png(1) css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
prettier-vscode|esb|9.12.0
auto-rename-tag|for|0.1.10
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051

```

</details>

**Comment by mjbvz** [comment] 2023-05-09 15:36
Duplicate of #178962

**Closed by mjbvz** 2023-05-09 15:36 UTC
