### ISSUE TITLE
Pipe output to editor under WSL

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#40447] opened 2017-12-18 16:55 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (bcc46316b497d1a316dd47ae86481df3ca5784ee, 2017-12-18T11:57:54.810Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.0
apiconnecttools|IBM|0.0.5
coldfusion|ili|0.0.11
wordcount|ms-|0.1.0
htmlescape-vscode-extension|ray|0.0.4
code-settings-sync|Sha|2.8.7
spellchecker|swy|1.2.13

---

Steps to Reproduce:

1. I'm using Insiders and trying to pipe output from the terminal running Unbuntu to the editor.
2. I tried a simple: cat .bashrc | code-insiders

Nothing happens. I thought perhaps it was an issue with Windows not having access to the file under WSL so I also tried something under /mnt/c and had the same response. Note, I can "which code-insiders" in Ubuntu and it correctly sees the proper path to my install.

Reproduces without extensions: I'll be honest and say I didn't check.

**Comment by leonadler** [comment] 2017-12-18 17:08
`cat .bashrc | code-insiders -`

https://github.com/Microsoft/vscode/issues/40351#issuecomment-352432867

**Comment by cfjedimaster** [comment] 2017-12-18 17:10
That opens a new file titled "-". The contents are empty.

**Comment by leonadler** [comment] 2017-12-18 17:14
Whoops, my bad - it should work in the next release then; the comment above is only 3 hours old

**Comment by cfjedimaster** [comment] 2017-12-18 17:15
No worries. Is the "-" at the end a Unix thing I should have known?

**Comment by bpasero** [comment] 2017-12-19 05:42
Related/duplicate of https://github.com/Microsoft/vscode/issues/39892

**Closed** 2017-12-28 23:51 UTC
Labels: *duplicate, insiders, WSL

**Comment by leonadler** [comment] 2017-12-29 21:49
@cfjedimaster late follow up: yes, `-` means "standard input" in unix for most programs:
```
echo 'Files in home directory:' > header.txt
date '+(generated on %d.%m at %H:%M)' > footer.txt
ls -Al ~ | cat header.txt - footer.txt > files-in-home.txt
# concatenates header.txt, standard input (standard output of ls) and footer.txt to a single file
```
