### ISSUE TITLE
Intellisense doesn't load automatically and stops loading when using control + click

### ISSUE THREAD

**Issue by RavePlnt** [Microsoft/vscode#71818] opened 2019-04-05 18:11 UTC
Issue Type: <b>Bug</b>

1.) Intellisense doesn't load automatically and stops loading when using control + click. For example, when typing in a link for an image in html there are no suggestions at all.

2.) Can't collapse html code blocks anymore. There is no + sign.

3.) Caching CSS Classes fequently hangs up and stops.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
auto-rename-tag|for|0.0.15
LiveServer|rit|5.5.1
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
lorem-ipsum|Tyr|1.2.0
html-snippets|wge|0.1.5
html-css-class-completion|Zig|1.18.0

(10 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-04-05 19:04
One problem per github issue please

**Comment by bsdahl** [comment] 2019-04-05 20:55
I am also having issues with 1.33. Initellisense seems to be broken. Rolling back to 1.32.3 resolves the issues.

**Comment by geebounce** [comment] 2019-04-05 21:46
Same here.
Intellisense not working after 1.33 update when project's file structure is complex.
Settings reset and fresh install didn't seem to help either.
Apparently the watcher is busy trying to analyze node_modules even though it's set up as an exception, because this is not happening in small project folders.

**Comment by Aleksion** [comment] 2019-04-05 22:33
Same here. CPU usage spikes to 100% and everything stops working. 1.32 works without any issues. 
I've tried with all extensions disabled and on simpler projects as well.

**Comment by aeschli** [comment] 2019-04-06 10:38
As all commenters referred on the first issue, renaming the issue.
@RavePlnt Please file separate issue for the remaining issues. Re. 2.) Check whether you have accessibility mode turned on. Folding indicators are hidden then.

**Comment by harry-sm** [comment] 2019-04-07 17:26
I had this same issue. I switched from typescript@3.4.1 to my workspace typescript@3.3.4  and everything works fine.

**Comment by mupkoo** [comment] 2019-04-08 08:43
I am having problems with the autocomplete as well. It is just loading and nothing happens. I notice that there is a VSCode process that is running ot 100% as well.

@harry-sm how do you switch typescript version for VSCode

**Comment by RavePlnt** [comment] 2019-04-08 12:58
Thanks but how do you roll back?

**Comment by mupkoo** [comment] 2019-04-08 13:01
@RavePlnt disable your automatic updates and just download an older version (https://code.visualstudio.com/updates/v1_32)

**Comment by mjbvz** [comment] 2019-04-08 21:50
Duplicate of #71751

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

**Closed** 2019-04-08 21:50 UTC
Labels: *duplicate, new release

**Comment by harry-sm** [comment] 2019-04-09 08:05
@mupkoo 

![image](https://user-images.githubusercontent.com/15040197/55783426-61840f80-5a7c-11e9-8066-f55832fa68da.png)
If you have typescript installed for your project. Just click on the typescript version in vs code and you will get a pop up which will give you the option to switch.
