### ISSUE TITLE
Visual studio Code restart

### ISSUE THREAD

**Issue by maxteebabs** [Microsoft/vscode#58491] opened 2018-09-12 08:07 UTC
Upon restarting Visual studio code, my workspace does not load. Unlike sublime, that stores your workspace, vsc does not open the last workspace that was opened.

**Comment by bpasero** [comment] 2018-09-13 07:48
@maxteebabs does this happen all the time? E.g. try this:
* start VSCode
* open a folder
* select File > Quit
* start VSCode

=> is the folder opened again?

**Comment by bpasero** [comment] 2018-09-13 13:05
Duplicate of https://github.com/Microsoft/vscode/issues/12058

**Closed by bpasero** 2018-09-13 13:05 UTC
Labels: editor, needs more info, workbench-state
