### ISSUE TITLE
Buttons read out title on hover and on click

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51999] opened 2018-06-15 09:26 UTC
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],MAS1.3.1

**Repro Steps:**
1. Launch VS Code while NVDA is ON.
2.Navigate to "Activity Bar" at left side of the screen after login.
3.Observed that, NVDA is reading the "Activity Bar" menu items name twice.
 
**Actual:**
NVDA is reading "Explorer" button name of "Activity Bar" twice .
eg:Explorer(ctrl+shift+E) button Explorer(ctrl+shift+E)

**Expected:**
NVDA should reads all the button name only once such as "Explorer button","Search button" etc

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
If screenreader reads it twice then user will get confused that, control have two name or two control are having same name.

**MAS Reference:**
MAS1.3.1- [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
1.
![accessibility a11y_vscode_activitybar_screenreader_speechviewer](https://user-images.githubusercontent.com/39204909/41460876-a76cb9b8-70ab-11e8-99d2-d8287db64c44.png)
2.
[[Accessibility]A11y_VSCode_ActivityBar_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2105532/Accessibility.A11y_VSCode_ActivityBar_Screenreader.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-07-03 16:10
IMHO this is desired behavior, since the first read is the hover, and the second read is only once you click. Are you sure this is unexpected? Since we have this behavior for all our buttons and none of the users complained

**Comment by AccessibilityTestingTeam-TCS** [comment] 2018-07-11 11:08
As per C+E accessibility testing reading twice it makes user confused.Hence it should reads only once.For more details please check the attached screenshots

**Comment by isidorn** [comment] 2018-07-17 15:41
I actually can not reproduce this with the latest vscode insiders and latest nvda -> closing

**Closed by isidorn** 2018-07-17 15:41 UTC
Labels: accessibility, needs more info
