### ISSUE TITLE
LanguageClient does not handle IntelliSense correctly for PowerShell static class methods

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3153] opened 2016-02-19 07:48 UTC
_From @daviwil on February 18, 2016 18:53_

We're seeing an issue in the PowerShell extension where our trigger for static .NET class methods is not resulting in the right IntelliSense in VS Code.  To reproduce the issue, try typing this in a PowerShell script file after installing the PowerShell extension on a Windows machine:

```powershell
[DateTime]::
```

After the second `:` we would expect an IntelliSense pane to appear.  Our language server sends the `:` character back as a triggerCharacter in our completionProvider section of the serverCapabilities object in the Initialize response.  Could there be an issue with the double-colon?

Another interesting problem here is that using `Ctrl+Space` after the double-colon results in an empty IntelliSense list even though our server gets the request correctly and returns a list of IntelliSense results.  Can you think of a reason why the results wouldn't be applied in this case?

We're tracking the issue on our side here: https://github.com/PowerShell/PowerShellEditorServices/issues/163

Let me know if it's more appropriate to file this on the Microsoft/vscode repo.

Thanks!

cc @rkeithhill @dfinke

_Copied from original issue: Microsoft/vscode-languageserver-node#26_

**Comment by dbaeumer** [comment] 2016-02-19 07:48
I checked that the language server correctly returns the :: and initialized code complete with the value. However to my knowledge VSCode only support trigger characters not trigger strings. Moving to VSCode for commenting

**Comment by dbaeumer** [comment] 2016-02-19 07:49
Starting with Joh. Unclear if this is an extension host problem or a general design thing.

**Comment by daviwil** [comment] 2016-02-19 15:40
To be clear, our specified trigger character is `:`, not the double-colon `::`.  I wonder if the two instances of the same trigger character is causing some issue there.

**Comment by rkeithhill** [comment] 2016-02-19 17:09
Yup, in the debugger I see the first colon initiate a completion request and we return an empty list.  Then I see the second colon initiate another completion request and we return all the static members.

**Comment by jrieken** [comment] 2016-03-07 10:42
@daviwil You do anything fancy with [CompletionItem#textEdit](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2028) or filter test? The suggest widget does refer to the word definition in some cases and uses that for some filtering.

**Comment by daviwil** [comment] 2016-03-07 15:52
I'd have to check to see what the textEdit is for that suggestion since the PowerShell engine sometimes will replace more of the source text than just what comes after the cursor.  What should I be looking out for?

**Comment by rkeithhill** [comment] 2016-03-09 03:36
Here's a related bug (I think) that isn't using two colons:
![vscodecolonbug](https://cloud.githubusercontent.com/assets/5177512/13624527/44da76b8-e56c-11e5-8ef0-f2f305dd00e9.gif)
Notice how I'm getting a completion list until I type in the colon - then bumpkis.

**Comment by jrieken** [comment] 2016-03-10 12:56
I will investigate

**Comment by jrieken** [comment] 2016-03-11 10:25
I cannot reproduce this with a simple extension. I assume you have `:` registered as completion trigger character. Any chance the subsequent request isn't getting a valid result?

**Comment by rkeithhill** [comment] 2016-03-11 16:39
Yes, we do have `:` registered as a completion character. However, upon receiving the `:` in the `$env:` example above we do return a completion list to VSCode that has all the variables in it. Here's a snippet from our editor services log file which shows that the extension returns a non-empty completion list when the `:` is typed:

```
    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "method": "textDocument/**didChange**",
      "params": {
        "uri": "file:///c%3A/Users/Keith/.vscode/extensions/ms-vscode.PowerShell-0.5.0/examples/DebugTest.ps1",
        "contentChanges": [
          {
            "range": {
              "start": {
                "line": 0,
                "character": 4
              },
              "end": {
                "line": 0,
                "character": 4
              }
            },
            "rangeLength": 0,
            "text": ":" <----
          }
        ]
      }
    }

3/11/2016 9:32:39 AM [VERBOSE] - Method "ResolveFilePath" at line 248 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: c:\Users\Keith\.vscode\extensions\ms-vscode.PowerShell-0.5.0\examples\DebugTest.ps1

3/11/2016 9:32:39 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 8, <----
      "method": "textDocument/completion",
      "params": {
        "uri": "file:///c%3A/Users/Keith/.vscode/extensions/ms-vscode.PowerShell-0.5.0/examples/DebugTest.ps1",
        "position": {
          "line": 0,
          "character": 5
        }
      }
    }

3/11/2016 9:32:39 AM [VERBOSE] - Method "ResolveFilePath" at line 248 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: c:\Users\Keith\.vscode\extensions\ms-vscode.PowerShell-0.5.0\examples\DebugTest.ps1

3/11/2016 9:32:39 AM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": "8",  <------
      "result": [
        {
          "label": "$ALLUSERSPROFILE",
          "kind": 6,
          "detail": null,
          "documentation": null,
          "sortText": null,
          "filterText": null,
          "insertText": "$env:ALLUSERSPROFILE",
          "textEdit": {
            "range": {
              "start": {
                "line": 0,
                "character": 0
              },
              "end": {
                "line": 0,
                "character": 5
              }
            },
            "newText": "$env:ALLUSERSPROFILE"
          },
          "data": null
        },
        {
          "label": "$AMD_ENTRYPOINT",
          "kind": 6,
          "detail": null,
          "documentation": null,
          "sortText": null,
          "filterText": null,
          "insertText": "$env:AMD_ENTRYPOINT",
          "textEdit": {
            "range": {
              "start": {
                "line": 0,
                "character": 0
              },
              "end": {
                "line": 0,
                "character": 5
              }
            },
            "newText": "$env:AMD_ENTRYPOINT"
          },
          "data": null
        },
        ...
```

**Comment by jrieken** [comment] 2016-03-16 13:46
maybe related to #4269

**Comment by rkeithhill** [comment] 2016-03-20 23:34
@jrieken I tried today's alpha build and the problem still exists. :-(

**Comment by pcgeek86** [comment] 2016-03-31 06:37
FYI I'm using the Insider build, and it's still broken.

![2016-03-31 00_38_00-visual studio code - insiders](https://cloud.githubusercontent.com/assets/466713/14167470/ceac4ca4-f6d8-11e5-95b7-5210208ff5b4.png)

**Comment by jrieken** [comment] 2016-03-31 08:25
Yes, we have not found time to tackle this in March.

**Comment by jrieken** [comment] 2016-04-01 08:21
The problem is that the suggest model computes `::` as being the current word. It will use that to filter the suggestions and end up with nothing left

![screen shot 2016-04-01 at 10 13 17](https://cloud.githubusercontent.com/assets/1794099/14201649/7f4ba3aa-f7f3-11e5-8a18-f0874b66f3a7.png)

**Comment by jrieken** [comment] 2016-04-01 08:25
@joaomoreno It's time to finally get rid of that current word notion. My proposal is to not use the word definition anymore but use the `overrideBefore` and `overrideAfter` (which corresponds to the `TextEdit` the api surfaces)

**Comment by jrieken** [comment] 2016-04-01 09:59
@rkeithhill We have understood the problem and are working on a fix. What you can try to get unblocked faster is tweaking the word definition for Powershell. Today, it seems to match for `:` and disabling that should get you going until we get our fix out

**Comment by jrieken** [comment] 2016-04-01 15:17
With that PR in the goings we will use a smarter way of selecting what text from the current line to filter you completion items against. When providing a `TextEdit` like above we will use the range that it defines (in the same `0,0,0,5` and use that for filtering) otherwise (only `label` is present) we will fall-back to the word range until the position. 

There is still an issue because we filter the proposals by `label` or `filterText` against the selected text. In above sample that will is `ALLUSERSPROFILE ` and `$AMD_ENTRYPOINT ` against `$env:`. Unsure if we should also use `insertText` when present...

**Comment by daviwil** [comment] 2016-04-01 17:42
Thanks a lot for working on this!  I believe `insertText` should also be inspected since the real completion text for PowerShell will come from there.  The `label` and `filterText` are used for different purposes and don't necessarily reflect the text that will be inserted.

How are you currently filtering the proposals against the text that is being completed?  What's the goal for filtering, just to discard any completions that don't seem the follow from the previous text?

**Comment by jrieken** [comment] 2016-04-04 07:54
> How are you currently filtering the proposals against the text that is being completed? What's the goal for filtering, just to discard any completions that don't seem the follow from the previous text?

Yes, it's about discarding completions that don't match the previous text. The actual filtering is an [OR](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/modesFilters.ts#L35) of(prefix, substring, camel case) and at a later step the best matching result is picked from the remaining items.

**Comment by jrieken** [comment] 2016-04-04 10:08
The improved filtering changes are now on master. The rules are that the range of the text edit defines that text that will be used for filtering and that filtering will happen against _label_, _insertText_, and _filterText_. Having said that the PowerShell extension still needs tweaking (wrt the sample above). 

Given the editor content `$env:` and a suggestion like `range: 0,0,0,5, insertText:'$env:ALLUSERS', label:$ALLUSERS` might be misleading because the user sees _$ALLUSERS_ after _$env:_ and when adding another _$_ the list is empty (comparing '$env:$' to '$ALLUSERS' and '$env:ALLUSERS') I believe its easier to make the text edit an insert like `range: 0,5,0,5, insertText:'AllUSERS' ...`

**Closed by jrieken** 2016-04-04 10:08 UTC
Labels: bug, important

**Comment by pcgeek86** [comment] 2016-04-04 13:36
@jrieken Thank you for your work, sir!

**Comment by jrieken** [comment] 2016-04-04 14:35
no worries, thanks for your patience.

**Comment by daviwil** [comment] 2016-04-05 17:12
@jrieken Hmm, we shouldn't be adding a `$` to the `$env:` suggestions anyway.  I'll see if I can figure out why that's happening, could be a bug on our side.  If the suggestion in that case is `AllUsers` instead of `$AllUsers`, would we be OK without changing the insertText range?

**Comment by daviwil** [comment] 2016-04-05 17:12
And thanks a lot for making this change, by the way!  Will be a great benefit to PowerShell developers.

**Comment by jrieken** [comment] 2016-04-06 07:07
Happy to help. Yeah, I don't thing it needed to put the `$` in from of the suggest label when `$env:` is already written. Generally, things are easy when completion describe an insert operation at the current position. Tho, when having typed just `$`, it might make sense to propose `$ALLUSER, $MORE_VARS` and then insert `$env:ALLUSER` etc

**Comment by rkeithhill** [comment] 2016-04-07 02:13
I have verified that static member completion now works with the alpha channel build 2016-04-06.  And yeah, we have some work to do on the `$env:` case.
