### ISSUE TITLE
Hangs when writing optional param with default value in JavaScript comment

### ISSUE THREAD

**Issue by Catlinz** [Microsoft/vscode#35384] opened 2017-09-29 15:41 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.3.0
code-runner|for|0.7.2
Lua|key|0.0.9
cpptools|ms-|0.13.0
typescript-javascript-grammar|ms-|0.0.24
material-icon-theme|PKi|2.2.1
java|red|0.10.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Write a JavaScript JsDoc comment on a class member function with a parameter.
2. Edit the documentation of the param to make it optional with a default value.  When typing the equals sign, without having typed the closing brace first, vs code will often hang and need to be restarted.

E.x.
```
class Test {
    /**
     * Some test documentation
     * @async
     * 
     * @param {string} [configFile= - The absolute path of the module's configuration file.
     * @returns {Promise}
     */
    parseModuleConfig(config) {
        return config + 1;
    }
}
```

When typing the **=** in the above comment, vs code hangs.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-29 17:45
Thanks. This is a duplicate of Microsoft/TypeScript-TmLanguage#515

Should be fixed in the next VScode insiders build

**Closed by mjbvz** 2017-09-29 17:45 UTC
Labels: duplicate, grammar, javascript
