### ISSUE TITLE
Error: Failed to execute git

### ISSUE THREAD

**Issue by linanwx** [Microsoft/vscode#23074] opened 2017-03-23 06:37 UTC
- VSCode Version: 1.10.2
- OS Version: deepin 15.3

Steps to Reproduce:

1. Open a directory with no "git init" or any other git operating.
2. See bug.

Even if I clicked off, it will still remind me.
If the directory has .git subdirectory, it will not show.

Steps to fix:
**Change the system language to English.**

![20170323143030](https://cloud.githubusercontent.com/assets/16589958/24234990/059e6cda-0fd6-11e7-926f-b4189d19f199.png)

**Comment by joaomoreno** [comment] 2017-03-27 08:29
Should be duplicate of #22355

Can you please try out our [latest insider release](https://code.visualstudio.com/insiders)?

**Closed by joaomoreno** 2017-03-27 08:29 UTC
