### ISSUE TITLE
Build failed: Egress is over the account limit

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#170070] opened 2022-12-27 07:53 UTC
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197880
Changes: https://github.com/Microsoft/vscode/compare/27a911a...0d7a4f6

No idea which account, maybe that limit can be increased? Looks like it happened before any specific tests could start.

```
[14:35:08] 'vscode-linux-x64-min-ci' errored after 9.55 s
[14:35:08] HTTPError: Response code 503 (Egress is over the account limit.)
    at EventEmitter.<anonymous> (/__w/1/s/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:552:15)
    at module.exports (/__w/1/s/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/__w/1/s/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:552:15)
    at ClientRequest.origin.emit (/__w/1/s/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:674:27)
error Command failed with exit code 1.
```

**Comment by lszomoru** [comment] 2023-01-02 12:29
Duplicate of #160766. Also not sure why this is assigned to me as I do not own this gulp task.

**Closed by lszomoru** 2023-01-02 12:29 UTC
Labels: unit-test-failure
