### ISSUE TITLE
File opened with lowercase path when following --declarationMap

### ISSUE THREAD

**Issue by dylanscott** [Microsoft/vscode#51242] opened 2018-06-06 17:21 UTC
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.5

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open a TypeScript project that uses the (new in TS 2.9) `--declarationMap` flag (and have VS Code use that compiler, rather than the bundled version which is currently 2.8)
2. Use the Go-to-Definition feature from a `.d.ts` file so that it will follow the declaration map and open the relevant source file

Expected: The source file will be opened normally.
Actual: The source file is opened, but the path is lowercased.

This presumably only affects case-insensitive file systems. Here are screenshots of the path bar in VS Code, first when I open the source file normally, and then when I open it via Go-to-Definition:

![screen shot 2018-06-06 at 10 19 01 am](https://user-images.githubusercontent.com/491393/41054416-25304404-6973-11e8-94df-a4b6f264a9ad.png)

![screen shot 2018-06-06 at 10 19 11 am](https://user-images.githubusercontent.com/491393/41054423-282023dc-6973-11e8-81f8-3bf49df093bb.png)

Related: #12448

**Comment by goloveychuk** [comment] 2018-08-23 20:33
other problem because of this - vscode can't match this path with tree panel on the right. So after "go to definition" you have no idea where are you, which makes UX very complicated

**Comment by mjbvz** [comment] 2019-01-29 00:57
Duplicate of #55827

I believe this was an upstream TypeScript issue. I just tested this with TS 3.3-rc and VS Code insiders and it seems to be working properly. If you still see this issue when using TS 3.3+, please share a small example project and I'll take a a look

**Closed by mjbvz** 2019-01-29 00:57 UTC
Labels: bug
