### ISSUE TITLE
the settings sync show "undefined" account after sign in ms account

### ISSUE THREAD

**Issue by guotuofeng** [microsoft/vscode#105699] opened 2020-08-31 02:34 UTC
Only one of my machines have that issues.
1. sign-in use my MS alias
2. sometimes, my alias will changed to "undefined (undefined)" name
3. at this moment, VSCode will complains should sign again to Turn on the settings syncs even if I previous enabled it already after successfully signed in.

![image](https://user-images.githubusercontent.com/817030/91677501-7aabc580-eb75-11ea-8802-1e91b2193d3b.png)

**Comment by RMacfarlane** [comment] 2020-09-01 15:52
Closing as a duplicate of https://github.com/microsoft/vscode/issues/105503

**Closed by RMacfarlane** 2020-09-01 15:52 UTC
