### ISSUE TITLE
The window terminated unexpectedly (reason: 'clean-exit', code: '1')

### ISSUE THREAD

**Issue by SunnySun1027** [microsoft/vscode#185544] opened 2023-06-19 08:53 UTC
- VS Code Version: 1.79.2
- Node.js: 16.17.1
- OS Version: macos 10.14.2

Steps to Reproduce:

1.  Run node process, like ng s -c dev
2.  Click kill Terminal button or Keyboard Shortcuts to kill the terminal

Reuslts:
Vscode crashed

<img width="446" alt="image" src="https://github.com/microsoft/vscode/assets/11438367/5d6bdce7-6b06-4295-9c2f-ecf9ff67cd84">

**Comment by 3344567** [comment] 2023-06-20 07:17
VS Code Version: 1.79.2
Node.js: 16.20.0
OS Version: macos 10.13.6
same problem

**Comment by visionXIT** [comment] 2023-06-21 07:24
Really, any solution?

**Comment by foreground-voice** [comment] 2023-06-21 10:42
all VSC windows crashing after closing Terminal. Reproducing on 
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (1 wk ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0

**Comment by deepak1556** [comment] 2023-06-21 11:35
Please provide the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by foreground-voice** [comment] 2023-06-22 10:54
[dump.zip](https://github.com/microsoft/vscode/files/11833095/dump.zip)

**Comment by gary-menzel** [comment] 2023-07-06 11:09
I am having the same problem with the same VSCode version.  If I run these applications in a native terminal everything behaves properly.  If I issue a CTRL-C to a nodejs application of any case, the SIGINT is not even trigger and the application continues to run.  But in a native terminal it gets the SIGINT and exits properly.  If I just open a terminal and then close it - that is fine.  It seems to be how VSCode is interacting (or not) with the launched application.  I also run a WebPack instance in another integrated terminal - that has the same problem.  Both never respond to a CTRL-C in the integrated terminal and issuing the KILL completely closes VSCode without warning.  Yet, both work fine in a native terminal.

NOTE: if I open a terminal in VSCode and launch `htop` it works but then kills all of VSCode if I kill that `htop` terminal.  So it is not just `nodejs` related. Exiting `htop` normally seems to work - just not issuing a KILL.  As mentioned, `nodejs` does not appear to be getting the SIGINT with `CTRL-C`.


From the About screen:

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 17.7.0

**Comment by gary-menzel** [comment] 2023-07-06 12:51
I have just dug into this even further.  Each time VSCode exists it leaves detached processes running. During development this causes all sorts of problems with server ports that are left open even if you restart VSCode.  I went through and removed all the child processes that were not shut down.  But, for now, I won't be using the integrated terminal to run my development processes (e.g. builds and hot reloads, etc).

**Comment by yulingjia** [comment] 2023-07-12 11:42
How can I do the same

**Comment by yulingjia** [comment] 2023-07-12 11:44
How to solve this problem

**Comment by cjp-luany** [comment] 2023-07-25 05:30
My solution : go back 1.78.2 , is ok and not crash anymore.

https://code.visualstudio.com/updates/v1_78

The download line select mac universal

**Comment by raval1234** [comment] 2023-11-07 07:56
![Screenshot at Nov 07 13-25-15](https://github.com/microsoft/vscode/assets/143083844/fa91df79-1c63-4258-aadb-0567e96d45ca)


solve problem

**Comment by deepak1556** [comment] 2023-12-05 16:40
Closing as macOS 10.13 and 10.14 have reached EOL https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-old-macos-versions. Can reopen if the issue is present with supported OS versions.

**Closed by deepak1556** 2023-12-05 16:40 UTC
