### ISSUE TITLE
Bug in VScode: CPU usage at 100% and RAM gradually fills up to 100%

### ISSUE THREAD

**Issue by vasuprint** [microsoft/vscode#210644] opened 2024-04-18 11:29 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1  x64
- OS Version: Ubuntu 22.04.4 LTS 64 bits
- nvidia driver : 545.29.06
-  Cuda version 11.8

When I use VScode with conda env and I clone the repository on Github (large file picture + Video>=1TB, python file is more 50 files) . The issue occurs when opening VScode, which uses about 3 GB of RAM, but when opening a folder with a cloned project, the RAM gradually increases until it reaches 100% (with 32 GB of RAM) and the CPU operates at 100%. Subsequently, Pylance (v.2024.4.101) crashes as illustrated, and the RAM then drops to around 4 GB. I attempted to solve the problem by downgrading Pylance to version 2023.12.1, but the issue persisted with RAM and CPU usage still reaching 100%. I tried disabling all extensions, but the problem remained unresolved. Ps. When i use code --status it normal but htop is abnormal .
![Screenshot from 2024-04-18 18-11-19](https://github.com/microsoft/vscode/assets/90551743/ddc44361-9c6d-4d9a-b9ce-93b3c85bcd1d)
![Screenshot from 2024-04-18 18-02-07](https://github.com/microsoft/vscode/assets/90551743/7187655c-02f4-4b3f-b746-8fcb23709672)
![Screenshot from 2024-04-18 17-55-38](https://github.com/microsoft/vscode/assets/90551743/5db0ffc2-3a45-465e-a650-d7d0c9a6f669)

**Comment by DonJayamanne** [comment] 2024-04-18 19:44
@vasuprint does this issue repro when you disable the `Pylance` extension?

**Comment by DonJayamanne** [comment] 2024-04-18 19:53
> I tried disabling all extensions, but the problem remained unresolved

Thanks, however based on the error message `Pylance has crashed....`, it seems very likely this is caused by Pylance extension.
I understand you have mentioned you have tried this, but I'd like a confirmation, hence please do bear with me as we've had similar issues in the past with the Pylance extension.
Please can you try disabling the `Pylance` extension and trying again.

>  (large file picture + Video>=1TB, python file is more 50 files) . The issue occurs when opening VScode, which uses about 3 GB of RAM, but when opening a folder with a cloned project, the RAM gradually increases until it reaches 100% (with 32 GB of RAM) and the CPU operates at 100%.

* Please ensure you disable all exetnsions.
* Close all files in the workspace folder
* Open just the simple and small `setup.py` file
* Reload VS Code
* Does this issue occur when you do not open the `mmaction...ipynb` file. instead just open the `setup.py` file in the directory.
I.e. do not open notebooks, just open a smaller python file and see if you run into the same issue.


>  (large file picture + Video>=1TB, python file is more 50 files) . The issue occurs when opening VScode, which uses about 3 GB of RAM, but when opening a folder with a cloned project, the RAM gradually increases until it reaches 100% (with 32 GB of RAM) and the CPU operates at 100%.

* Does the notebook contain a video?
* Is this a public repository?
* Does this issue repro, when you open another folder in VS Code?

**Comment by vasuprint** [comment] 2024-04-18 22:40
Thank you for your help,
--------
 <b>No problem at all if my information can make it easier for you to solve the problem.</b>

> please do bear with me as we've had similar issues in the past with the Pylance extension.

- [x] Please ensure you disable all extensions ( I will attach a picture for you)
- [x] Close all files in the workspace folder
- [x] Reload VS Code
- [x] Open just the simple and small `setup.py` file

In that case, I will start the experiment by disabling all extensions and closing all files. I will attach a picture for you.
Conclusion:  I found that even if I don't open any files and disable all extensions, there is still a CPU core operating at 100%, and memory usage gradually increases, constantly rising over time from about 3.2 GB to 11.8 GB (I captured a picture even though there was no increase, but I think it's abnormal for opening VScode without doing anything and with no extensions to use 11 GB of RAM and have periods where 1 CPU core is working at 100%.), taking approximately 15-30 minutes. If I open a setup.py or small .ipynb, .py file, the RAM reaches 32 GB in less than 10 minutes (Depend on complexity file). I have attached the operations using the monitor command through `htop`.

>Does the notebook contain a video?

No, I just Text file and basic code to test program (Code open video on path directory it only just 1 video to test)


> Is this a public repository?

Yes, MMaction2 is public repository and many people use its.

> Does this issue repro, when you open another folder in VS Code?

Yes, no matter which repository I open, I always encounter the problem. T...T Regardless of whether it's a small or large repo, the issue persists. The problem doesn't only occur on my computer; even when I use Remote (SSH), I still face the same issues mentioned.


Fig1. Start Vscode 
![start](https://github.com/microsoft/vscode/assets/90551743/0b32ed43-beb5-4018-b54a-49dc142961de)

P.S. From my observations, when VScode uses a significant amount of RAM and CPU, it often results from my monitoring through `htop`. I usually find that VScode repeatedly performs certain actions multiple times or replace process all time, which consumes RAM and CPU usage.


Fig2. Open it and wait around 15 min
![end](https://github.com/microsoft/vscode/assets/90551743/0b72ec2e-86fd-4180-8b79-872d09d48a75)

**Comment by vasuprint** [comment] 2024-04-18 22:47
Fig3. I open `setup.py` with no extension you can see memmory(RAM) around 10.12 gb 
![Openpython_noextension](https://github.com/microsoft/vscode/assets/90551743/df8b4b78-0dad-42c8-a030-794650c4e974)



Fig4. I open `setup.py`   You can see memory increase very high and fast, CPU same increased too. 
![setupwithpythonextension](https://github.com/microsoft/vscode/assets/90551743/74c510e3-c4f4-4e2f-8860-d59a07c14e29)

**Comment by DonJayamanne** [comment] 2024-04-19 00:40
@vasuprint 
When looking at the screenshots here https://github.com/microsoft/vscode/issues/210644#issuecomment-2065447762
You still have extensions installed and enabled.
Perhaps you were trying to highlight the fact that it was bad with and without, not entirely sure.

For now, lets disable/uninstall all extensions and open an empty workspace folder with perhaps just one plain text file.
Please can you share the CPU logs for this.
Please have a look at the instructions here https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by DonJayamanne** [comment] 2024-04-19 00:49
@deepak1556 /cc in case you might have seen this before.

**Comment by vasuprint** [comment] 2024-04-20 04:07
Yes, I want to show you a comparison to see what it's like with and without extensions in the https://github.com/microsoft/vscode/issues/210644#issuecomment-2065447762. The first image will show the gradual increase in RAM when all extensions are disabled, but if extensions are enabled, even just using the Python extension, there's a significant RAM leak. I find this very strange

**Comment by vasuprint** [comment] 2024-04-20 04:28
I followed your advice by sharing the CPU log, and I have attached the file for you.
I have attached the file in both `.json` format and the `original file.`
[CPU-20240420T040502.819Z.cpuprofile.json](https://github.com/microsoft/vscode/files/15046849/CPU-20240420T040502.819Z.cpuprofile.json)
[CPU-20240420T040502.819Z.cpuprofile](https://github.com/microsoft/vscode/files/15046850/CPU-20240420T040502.819Z.cpuprofile)

My CPU log file looklike 
![CAPTURELOGCPU](https://github.com/microsoft/vscode/assets/90551743/92feac11-f9e0-40cc-8431-f774a4ea9196)

 When I monitored using the `htop` command, I found that my RAM usage was as high as 9.88 GB, CPU was high  too. Following your advice, I uninstalled every extension, but the CPU and RAM still behaved abnormally and operated at excessively high levels.
![htopmonitor](https://github.com/microsoft/vscode/assets/90551743/f89edd72-2046-4a67-870f-489b91e81887)

**Comment by DonJayamanne** [comment] 2024-04-20 04:30
@karthiknadig Given there's an increase in usage when Python ext is active (based on user feedback), assigning this to you.

**Comment by vasuprint** [comment] 2024-04-20 04:33
However, even though I'm not using any extensions or have uninstalled all extensions, the operation is still abnormal. T...T

**Comment by deepak1556** [comment] 2024-04-23 02:09
@vasuprint can you share the full command line of the process with high cpu `cat /proc/<PID>/cmdline`

**Closed** 2024-05-03 11:24 UTC
Labels: info-needed, perf
