### ISSUE TITLE
High CPU Usage when typing (typescript project)

### ISSUE THREAD

**Issue by JohannesRudolph** [Microsoft/vscode#9592] opened 2016-07-21 17:44 UTC
- VSCode Version: 1.3.1  (no extensions, no user settings)
- OS Version: OS X El Capitan

Steps to Reproduce:
1. `git clone https://github.com/AngularClass/angular2-webpack-starter` (will likely work with any other TS project too)
2. open the project folder in VS Code, pick any file (e.g. app.component.ts) and start typing (e.g. repeat keys `asd` anywhere in the file
3. Observe high CPU usage by 2 Electron-Helper Processes

I know VS Code may occasionally want to perform expensive operations (type checking, syntax highlighting) but these should either be throttled or made more efficient. The current CPU usage is just insane and makes using VSCode unattractive in any mobile scenario (or in a summerly warm office with fans spinning all the time!).

**Comment by kieferrm** [comment] 2016-07-22 15:10
@JohannesRudolph what is the numbers you are seeing?  How long is the CPU spike (assuming its a spike)?

**Comment by JohannesRudolph** [comment] 2016-07-22 15:20
It's between 15-25%cpu on an 8 core (4 physical) machine. So 1-2 cores are
fully loaded. The spike starts when typing and lasts for a few seconds
after stopping.

Am 22.07.2016 17:10 schrieb "Kai Maetzel" <notifications@github.com>:

**Comment by kieferrm** [comment] 2016-07-22 17:49
@JohannesRudolph The numbers the Activity Monitor shows are somewhat counter intuitive. When it shows 25%, then this means 25% of one CPU core.  I.e if you have 8 cores,  1/32 of your overall CPU capacity is currently being used rather than 1/4.

**Comment by JohannesRudolph** [comment] 2016-07-22 20:18
I didnt mean the per-process score, but total system cpu usage (scaled from
0 to 100%). Can provide a screen capture if you need it.

Am Freitag, 22. Juli 2016 schrieb Kai Maetzel :

**Comment by dbaeumer** [comment] 2016-08-04 13:21
We do throttle this already. We only ask for revalidation/typ checking after a 100ms delay. 

The tsserver which is a node/electron app can only consume one core. To better understand what is going on could you provide the command line args of the code executable which consumes lot of memory.

An which version of TS do you use. Normally angular2-webpack-starter using 2.0-alpha/beta which on my machine produces a higher CPU load as well.

**Comment by dbaeumer** [comment] 2016-11-15 19:23
Closing since no additional information has been provided and I am not able to reproduce the issue.

**Closed** 2016-11-15 19:24 UTC
Labels: needs more info, not-reproducible, typescript
