### ISSUE TITLE
Focus integrated terminal on first startup

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40416] opened 2017-12-18 06:23 UTC
1. Have tab other than `terminal` active in panel
2. Reload the editor
3. Activate `terminal` tab
4. After the shell is loaded focus is not set

![terminal_focus](https://user-images.githubusercontent.com/9638156/34092446-844f3442-e3d4-11e7-8b99-e3ec39d68eba.gif)

**Comment by Tyriar** [comment] 2017-12-18 14:22
I can reproduce on mac

**Comment by bpceee** [comment] 2017-12-20 06:10
Hi @Tyriar , I will create a PR to fix this.

**Comment by Tyriar** [comment] 2018-01-22 18:59
A proper fix for this is a little tough, the reason is because we need to make sure that the panel is not focused when it shouldn't be (when launching VS Code, when showing but not focusing via the API). Also the reason the focus isn't happening is because of the async terminal initialization. It's also possible that this will go away once https://github.com/xtermjs/xterm.js/issues/955 is fixed.

**Comment by bialix** [comment] 2018-03-09 16:03
"A proper fix for this is a little tough" - sorry but it worked well in older versions of VS code, but now is broken. Can you just revert those changes that introduces such bug?

**Comment by letmaik** [comment] 2018-03-19 21:25
I can confirm that this worked before the terminal got replaced and it is the number one annoying thing now for me in VS Code.

**Comment by Tyriar** [comment] 2018-03-22 20:51
@usernamehw fixed the toggle terminal case, the only remaining issue is clicking the terminal label on the panel (when no terminals are open).

**Comment by johnpapa** [comment] 2018-03-30 11:12
thanks for the progress update @Tyriar

**Closed** 2018-06-11 16:49 UTC
Labels: bug, help wanted, integrated-terminal
