### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by hannibal-code** [microsoft/vscode#130701] opened 2021-08-12 18:24 UTC
Hello. I work with vscode about 4 years but I really sad because there is no changing background feature. please please add it.

**Comment by heynan0** [comment] 2021-08-12 18:38
Change the background of what part of VSCode? Could you provide a specific example?

**Comment by hannibal-code** [comment] 2021-08-12 18:44
> 
> 
> Change the background of what part of VSCode? Could you provide a specific example?

Thanks for your answer! background image for code editor. I mean hole editor. looks like any other IDEs that you can set background image.

**Comment by heynan0** [comment] 2021-08-12 18:46
Do you have a screenshot example?

**Comment by hannibal-code** [comment] 2021-08-12 18:47
![image](https://user-images.githubusercontent.com/47059632/129251759-7fb7fcca-9894-4a99-a164-b237f9a067b0.png)
Hole this black parts!!!

**Comment by heynan0** [comment] 2021-08-12 19:00
@hannibal-code if you do a web search, it seems you can find tutorials on how to achieve that. One way seems to be via an extension. Have you tried this particular one?

https://marketplace.visualstudio.com/items?itemName=shalldie.background

**Comment by hannibal-code** [comment] 2021-08-12 19:04
> 
> 
> @hannibal-code if you do a web search, it seems you can find tutorials on how to achieve that. One way seems to be via an extension. Have you tried this particular one?
> 
> https://marketplace.visualstudio.com/items?itemName=shalldie.background
> 
> Also, I would like to tag this issue as duplicate of
> 
>     * [Custom background image #84120](https://github.com/microsoft/vscode/issues/84120)

I search it many time. every time about 2 hours. after that i write this issue!
this extension and 5 others dos not work for me. in 3 laptops!

**Comment by hannibal-code** [comment] 2021-08-12 19:13
> 
> 
> @hannibal-code if you do a web search, it seems you can find tutorials on how to achieve that. One way seems to be via an extension. Have you tried this particular one?
> 
> https://marketplace.visualstudio.com/items?itemName=shalldie.background
> 
> Also, I would like to tag this issue as duplicate of
> 
>     * [Custom background image #84120](https://github.com/microsoft/vscode/issues/84120)

![image](https://user-images.githubusercontent.com/47059632/129255090-11a76123-bf6f-4d3c-bba7-22e34b7ab667.png)

**Comment by rzhao271** [comment] 2021-08-13 20:21
Duplicate of #84120

**Closed** 2021-08-13 20:35 UTC
Labels: *duplicate
