### ISSUE TITLE
Slow performance starting VS Code, same with --disable-extensions

### ISSUE THREAD

**Issue by PlanePlusPilot** [Microsoft/vscode#21293] opened 2017-02-23 15:41 UTC
- VSCode Version: <code>Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz (12 x 3192)</code>
- Memory (System): <code>31.96GB (22.81GB free)</code>
- Memory (Process): <code>123.33MB working set (124.09MB peak, 97.51MB private, 34.02MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>67%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|26|
|main|app.isReady => window.loadUrl()|1472|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|338|
|renderer|require(workbench.main.js)|884|
|renderer|-> of which require() node_modules|166|
|renderer|create extension host => extensions onReady()|2602|
|renderer|restore viewlet|0|
|renderer|restore editor view state|405|
|renderer|overall workbench load|2583|
|main + renderer|start => extensions ready|5476|
|main + renderer|start => workbench ready|5327|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by bpasero** [comment] 2017-02-23 18:36
@PlanePlusPilot running inside a VM?

**Comment by PlanePlusPilot** [comment] 2017-02-23 18:39
No, running on a physical desktop - DELL Precision T5810, Xeon E5-1650 CPU, 3.2 Ghz, 32GB RAM, SSD HDD.

**Comment by bpasero** [comment] 2017-02-23 18:40
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by PlanePlusPilot** [comment] 2017-02-23 18:42
Good thought, I thought the same - I tried it and it resulted in pretty much the same numbers to my surprise (I even mentioned it in the issue subject)

**Comment by bpasero** [comment] 2017-02-23 18:45
@PlanePlusPilot what about trying our insiders release to compare the numbers:  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by PlanePlusPilot** [comment] 2017-02-24 15:52
Performance is better but still seems high to me - 4395ms with -p --disable-extesions startup options.

**Comment by jrieken** [comment] 2017-02-24 16:18
This is interesting data. Most performance tickers from above show above average results, except for (2) and (6). 

|Component|Task|Time (ms)|
|---|---|---|
|main|app.isReady => window.loadUrl()|1472 🐌 |
|renderer|create extension host => extensions onReady()|2602 🐌 |

**Comment by jrieken** [comment] 2017-03-02 10:14
@PlanePlusPilot With latest [Insiders](https://code.visualstudio.com/insiders) you can now start with like so: `code --prof-start`. That will produce two cpu profiles which we would like you to share with us. Thanks

**Comment by PlanePlusPilot** [comment] 2017-03-04 11:10
@jrieken I'm sorry but I no longer have access to the PC in question (switched jobs).

**Comment by jrieken** [comment] 2017-03-06 11:51
bummer... closing this as need-info. We have added a lot perf tracing and folks report issues with cpu profiles. I am confident we will capture this issue with that as well.

**Closed by jrieken** 2017-03-06 11:51 UTC
Labels: needs more info, perf
