### ISSUE TITLE
Exception widget text wrapping not perfect

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23373] opened 2017-03-28 09:53 UTC
Refs #23013

1. Start debugging some program with an exception
2. Exception widget opens -> decrease the size of the screen bit by bit so you get word wrapping
3. Notice how the wrapping is not perfect -> in my screenshot you can see that there is an empty line which should not be the case, it should contain the text which is not visible on the previous line

![screen shot 2017-03-28 at 11 51 29](https://cloud.githubusercontent.com/assets/1926584/24399437/0eae8406-13ad-11e7-997c-0136bef6c63c.png)

**Comment by michelkaporin** [comment] 2017-03-29 12:51
Cannot reproduce it, would be good to see it in person when you have time @isidorn.

**Comment by michelkaporin** [comment] 2017-03-29 13:34
After talk to @isidorn it seems that it is OS-specific (Windows is fine, Mac OS gives the result above), being a small edge case. Closing it for now as I am not doing any fancy calculations there apart from setting `white-space: pre-wrap;` in CSS.

https://github.com/Microsoft/vscode/blob/8b24b77b5cf320cf0c58154bfa2b5e6d652af0fc/src/vs/workbench/parts/debug/browser/media/exceptionWidget.css#L8

**Closed by michelkaporin** 2017-03-29 13:34 UTC
Labels: debug
