### ISSUE TITLE
VSCE Error

### ISSUE THREAD

**Issue by timaiv** [Microsoft/vscode#43888] opened 2018-02-17 14:54 UTC
When i want to create vsix file (vsce package) in ts exstension i always have this problem(on 2 computers):

Error: Cannot find module 'vso-node-api/HttpClient'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Yaroslav\AppData\Roaming\npm\node_modules\vsce\out\publicgalleryapi.js:3:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

When i try install HttpClient via npm i had :host key verification failed.

- VSCode Version: 1.20
- OS Version:win7

**Comment by jlchmura** [comment] 2018-02-17 20:38
+1   
I just installed vice package for the first time today and ran in to this same problem.
Happening on both MacOS and Win10 box

**Comment by timaiv** [comment] 2018-02-17 20:56
jlchmura, I change publicgalleryapi and now i fixed it for me.

> I just installed vsce package for the first time today and ran in to this same problem.
> Happening on both MacOS and Win10 box

**Comment by petertirrell** [comment] 2018-02-17 22:32
Same here - was working on a new VSCode extension and went to install vsce to work toward publishing it.  Got this same error, Win10, VSCode 1.20.1

**Comment by florinpatrascu** [comment] 2018-02-17 22:38
Same here - and also while I was trying to publish a new VSCode extension. Got this same error:

```
$ vsce publish -p 77e.......
module.js:557
    throw err;
    ^

Error: Cannot find module 'vso-node-api/HttpClient'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/out/publicgalleryapi.js:3:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

OSX, VSCode Version 1.20.1

**Comment by jlchmura** [comment] 2018-02-17 22:56
@timaiv Can you share the change that you made?

**Comment by timaiv** [comment] 2018-02-17 23:47
> Can you share the change that you made?

Comment 3 , 11, 14 lines in publicgalleryapi. And all works!

**Comment by florinpatrascu** [comment] 2018-02-18 18:56
doesn't work for me, commenting 3, 11, 14. I am getting `Error: api.getExtension is not a function`, w/ and w/o the lines referred above. Is there a good version I could go back to, to publish my extension update??

**Comment by florinpatrascu** [comment] 2018-02-18 19:39
fwiw, I rolled back to `vsce` version `1.15.1`, and was able to publish my extension. I am getting the expected warning: `The latest version of vsce is 1.36.2 and you have 1.15.1`, of course, but this is so much better than fiddling at the broken version. HTH

**Comment by itowlson** [comment] 2018-02-18 20:59
Same error, and this is breaking CI because that pulls down vsce latest.

**Comment by joaomoreno** [comment] 2018-02-21 08:47
Duplicate of https://github.com/Microsoft/vscode-vsce/issues/238

Please update to the latest vsce to get the fix: `npm i -g vsce`

**Closed by joaomoreno** 2018-02-21 08:47 UTC
