### ISSUE TITLE
Maximize windows button

### ISSUE THREAD

**Issue by Ahtuz** [microsoft/vscode#85307] opened 2019-11-21 15:13 UTC
please close this issue, i'm sorry, i just found out that this issue is duplicate.

**Comment by IllusionMH** [comment] 2019-11-21 15:17
/needsMoreInfo

Most likely duplicate of #81102

**Closed** 2019-11-21 15:17 UTC

**Comment by IllusionMH** [comment] 2019-11-21 15:25
Sorry. Sent somment 15 seconds after issue was closed and before UI was updated :(

Also you can check recent Insiders build https://code.visualstudio.com/insiders/ - I think that fix is already merged and released.

**Comment by Ahtuz** [comment] 2019-11-22 05:16
Well, it's not your fault, sir. It's my fault that I didn't clearly check other issues similar to this one. By the way, thank you for letting me know about the Insiders build. I didn't found this problem there. I'll be using the Insiders build from now on.
Cheers! :)
