### ISSUE TITLE
No such file errors after update

### ISSUE THREAD

**Issue by mbinette** [microsoft/vscode#122325] opened 2021-04-27 12:43 UTC
Issue Type: <b>Bug</b>

Install SFTP 1.12.9 SFTP/FTP sync Extension by liximomo, https://github.com/liximomo/vscode-sftp.

An update to VS Code Insiders after Friday 4/23/2021 cause this extension to fail. Every time you save a file the extension SFTPs it to a remote server. I didn't try over the weekend but come Monday, it began to fail on every update with a notification "No such file", "Source: SFTP (Extension)". The detail output is:

```
[04-27 08:17:32] [info] [file-save] d:\dev\fas-dev\web\src\verification\fas-document-select-card.js
[04-27 08:17:33] [error] Error: No such file
	at SFTPStream._transform (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote d:\dev\fas-dev\web\src\verification\fas-document-select-card.js
```

VS Code version: Code - Insiders 1.56.0-insider (9a4d524f909e09079fec7abb82f2efde2172da7c, 2021-04-27T06:15:26.914Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.62GB (6.14GB free)|
|Process Argv|--crash-reporter-id 45e19e72-f964-447a-91b9-2b35016194eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.0.3
es6-string-css|bas|0.1.0
pgformatter|bra|1.17.0
better-toml|bun|0.3.2
markdown-table-prettify|dar|3.4.0
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
prettier-vscode|esb|6.3.2
php-intellisense|fel|2.3.14
go|gol|0.24.2
vscode-drawio|hed|1.4.0
php-cs-fixer|jun|0.1.158
vscode-phpfmt|kok|1.0.30
sftp|lix|1.12.9
camelcasenavigation|map|1.1.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.12.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
es6-string-html|Tob|2.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820cf:30276953
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by alexdima** [comment] 2021-04-27 19:33
@sandy081 I think this extension might be doing something with virtual workspaces. I think you made some changes in this area recently, so giving to you to investigate.

**Comment by sandy081** [comment] 2021-04-28 15:18
I have just changed the enablement of extensions in virtual workspaces. Can you please help me in understanding what is the issue here and how does enablement impacts this?

**Comment by alexdima** [comment] 2021-04-28 15:45
@sandy081 Please forward the issue to someone else. As inbox tracker, I thought there was a chance that one of the recent changes related to virtual workspaces could have caused this.

**Comment by sandy081** [comment] 2021-04-28 15:53
@mbinette I am sorry that above info is not helpful to diagnose the issue. I would recommend to file the issue against the extension first so that extension can analyze and diagnose from its side and see if there is an issue in the extension or if it finds some feature is not working as expected in VS Code then they can file an extension against VS Code providing proper steps to reproduce.

**Comment by alexdima** [comment] 2021-04-28 15:57
FYI @jrieken @bpasero if you changed something recently in this area. This extension hasn't been update in 2 years and stopped working on Monday's insiders.

**Comment by sandy081** [comment] 2021-04-28 15:58
Just got to know that (thanks @alexdima) the extension has not been updated from last 2 years. So it could be a change in VSC that caused this. Hence reopening and asking others to jump on and provide some insights.

Meanwhile @mbinette can you please provide steps to reproduce so that we can diagnose it easily?

**Comment by mbinette** [comment] 2021-04-28 16:05
The steps to reproduce are simple but does require you to have a remote SSH or SFTP service setup. I have a local Windows 10 workstation that syncs files over SSH to a Google virtual server. Follow the directions for the extension to setup the Host, Username, Password or Key, and the local and remote directories to sync. Then use the extension to sync files and you will get the error every time. Some files are correctly synced but others will have its contents removed  or truncated (file still exists).

I've installed the non-insiders edition of VS Code and the extension still works. Has Electron or Node been updated in Insiders Edition since last Friday? The errors are coming from Node but couldn't figure out if it had actually changed and when.

**Comment by alexdima** [comment] 2021-04-28 16:09
@mbinette That [stack](https://github.com/mscdex/ssh2/issues/724) appears multiple times in issues in that npm module repository and it looks like it is caused by any server-side error.

**Comment by deepak1556** [comment] 2021-04-28 20:24
Yes insiders has bumped node from `12.18.3` to `14.16.1`, so very likely some behavior change is in play here. Can you provide the debug logs from the extension https://github.com/liximomo/vscode-sftp#debug

**Comment by mbinette** [comment] 2021-04-29 18:33
Here is the debug log. Doesn't look very helpful.
`[04-29 14:32:19] [info] [file-save] d:\dev\fas-dev\build\k8s\tmpl\api-web.yaml
[04-29 14:32:19] [trace] handle upload file for d:\dev\fas-dev\build\k8s\tmpl\api-web.yaml
[04-29 14:32:19] [debug] Outgoing: Writing MKDIR
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing LSTAT
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing OPEN
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing FSTAT
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing FSETSTAT
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing WRITE
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing CLOSE
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing FSETSTAT
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [debug] Outgoing: Writing CLOSE
[04-29 14:32:19] [debug] Outgoing: Writing CHANNEL_DATA (0)
[04-29 14:32:19] [error] Error: No such file
	at SFTPStream._transform (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:412:27)
	at SFTPStream.Transform._read (internal/streams/transform.js:205:10)
	at SFTPStream._read (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
	at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SFTPStream.Writable.write (internal/streams/writable.js:303:10)
	at Channel.ondata (internal/streams/readable.js:719:22)
	at Channel.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Channel.Readable.push (internal/streams/readable.js:223:10)
	at SSH2Stream.<anonymous> (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\Channel.js:167:15)
	at SSH2Stream.emit (events.js:315:20)
	at parsePacket (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:3288:10)
	at SSH2Stream._transform (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:694:13)
	at SSH2Stream.Transform._read (internal/streams/transform.js:205:10)
	at SSH2Stream._read (c:\Users\mbine\.vscode-insiders\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\ssh.js:253:15)
	at SSH2Stream.Transform._write (internal/streams/transform.js:193:12)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at SSH2Stream.Writable.write (internal/streams/writable.js:303:10)
	at Socket.ondata (internal/streams/readable.js:719:22)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote d:\dev\fas-dev\build\k8s\tmpl\api-web.yaml
[04-29 14:32:24] [debug] Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
`

**Comment by deepak1556** [comment] 2021-05-05 11:27
Thanks for the log, the error seems to be thrown from the server after `FSETSTAT` operation when syncing the file `when local ➞ remote d:\dev\fas-dev\build\k8s\tmpl\api-web.yaml`. I am not sure what causes this, one thing to check if the directory and file are present in the server. It is best if this issue is debugged by the extension author, closing as such.

Side note: noticed that https://github.com/liximomo/vscode-sftp is not using the latest version of `ssh2` module, so maybe it has fixes for node 14 compatibility.

**Closed by deepak1556** 2021-05-05 11:27 UTC
Labels: needs more info

**Comment by WraithKenny** [comment] 2021-05-14 16:06
Hi all, wasn't having a problem until I just now upgraded vscode to 1.56.2. 

Now the error is
[05-14 11:29:14] [warn] Can't set modified time to the file because Invalid handle
[05-14 11:29:14] [error] Error: Invalid handle

"Caused by extension" lmao, you just broke 845K installs.
