### ISSUE TITLE
package.json files for private packages should not warn about missing name and version properties

### ISSUE THREAD

**Issue by nicolasmccurdy** [Microsoft/vscode#6103] opened 2016-05-04 17:26 UTC
- VSCode Version: 1.0.0
- OS Version: Mac OS 10.11.4

## Steps to Reproduce

1. Create the following `package.json` file and open it in Code: ```{ "private": true }```
2. View the linter warnings (hover over the green squiggles)

## Expected

No warnings, because `npm install` no longer warns about missing names and versions in private packages.

## Actual

Code produces the following warnings:

- Missing property "name"
- Missing property "version"

**Comment by aeschli** [comment] 2016-05-06 19:33
duplicate of #5398

**Closed by aeschli** 2016-05-06 19:33 UTC
Labels: bug
