### ISSUE TITLE
Inconsistent handling of CRLF -> LF between TextEdit and TextEditorEdit

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#15385] opened 2016-11-11 21:58 UTC
- VSCode Version: 1.7.1
- OS Version: MacOS Sierra (10.12.1)

- Easiest to demonstrate with HookyQR.beautify installed

Steps to Reproduce:

1. Open a project folder.
2. Add a `.jsonbeautifyrc` file with
```javascript
{"eol": "\r\n"}
```
3. Create a json file, with content, that includes several lines. eg:
```javascript
{
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json"
            ]
        }
    }
}
```
4. Set the document line end to **LF**
5. Format with the beautify command (`F1->Beautify file`) -> No extra lines are produced.
6. Format with "Format Document" -> ***An extra line will be produced for every existing new line***.

You can repeat step six over and over to add extra lines to the new extra lines.

This is caused by inconsistent handling of new lines in document edits between `TextEditor.edit` (returning a `TextEditorEdit`) and `TextEdit.replace` (and its siblings, I'm assuming - returning a `TextEdit`).

The beautify command calls `activeTextEditor.edit` to provide the changes. This works correctly, changing CRLF to LF when required.

Format Document (and Format Selection) call `TextEdit.replace` (as the callback requires an array of `TextEdit`s to be returned) and changes CRLF to LFLF, generating extra lines.

*Also, as a side note:* it would be helpful if `FormattingOptions` included an `eol` property.

**Comment by aeschli** [comment] 2016-11-14 09:50
I was thinking the code that applies the edits would make sure that consistent new lines separators are inserted.
Otherwise either the `FormattingOptions` or the `TextDocument` should have a `eol` property.

**Comment by jrieken** [comment] 2016-11-14 13:10
Yes - the editor normalises whitespace according to its `eol`-configuration. When a formatter inserts more newlines (without replacing existing) you duplicate them.

@HookyQR Can you confirm that you get new newline-characters even when you select the existing newline character?

**Comment by HookyQR** [comment] 2016-11-14 19:29
This happens on a full document format (as well). Nothing is selected, the whole file content is formatted.

When using Format Selection, yes, if a new line is selected, two new lines replace it.

Here's what i think is happening, for the record - using a simple JSON example, with the settings above.

#### Formatting: `{"a":1}` *(a single line)*
* I provide a TextEdit replace of `{\r\n\t"a": 1\r\n}`.
* Since there is only one line, this single replacement is used, and the `\r\n` is normalised to `\n`.

#### Formatting: `{\n\t"a":1\n}`
* I provide a TextEdit replace of `{\r\n\t"a": 1\r\n}`.
* Which VS Code matches by line to three replacements of:
  * `{` => `{\r`
  * `\t"a":1` => `\t"a": 1\r`
  * `}` => no change
* VS Code then normalises each of these replacements, converting the trailing `\r` to an **extra** new line.

### Why do I think this:

#### Formatting: `{\n\t"a":1,"b":2\n}`
* I provide a TextEdit replace of `{\r\n\t"a": 1\r\n"b": 2\r\n}`.
* Which VS Code matches by line to three replacements of:
  * `{` => `{\r`
  * `\t"a":1,"b":2` => `\t"a": 1\r\n\t"b": 2\r` 

        _^^ the CRLF between **a** and **b** is normalised to one LF. (The correct operation)_
  * `}` => no change
* VS Code then normalises each of these replacements, converting the trailing `\r` to an **extra** new line.


All that has to change is the normalisation step be moved to the point where the original edit is provided.


@aeschli: Knowing what to provide in the way of line endings is difficult as the file can be open in multiple editor views, but those views could have different line ending options set. Also, the editor's `eol` setting can differ from the workspace and the global `eol` setting. The view which triggered the format operation should either providing the `eol` setting to the formatter, or _correctly_ handle normalisation of the response. `eol` should be a property on the FormattingOptions, not on the text document because of the various ways it can be set (independent of the document).

**Comment by jrieken** [comment] 2016-11-14 20:41
I can reproduce with below extension snippet and the sample doc above. I believe our logic to minify edits is responsible for this.

```ts
    vscode.languages.registerDocumentFormattingEditProvider('abc', {
        provideDocumentFormattingEdits(doc) {
            let range = new vscode.Range(doc.lineAt(0).range.start, doc.lineAt(doc.lineCount - 1).range.end);
            return [vscode.TextEdit.replace(range, '{\r\n\t"a":1\r\n}')];
        }
    })
```

**Comment by jrieken** [comment] 2016-11-15 13:52
> Knowing what to provide in the way of line endings is difficult as the file can be open in multiple editor views, but those views could have different line ending options set. Also, the editor's eol setting can differ from the workspace and the global eol setting. 

That isn't correct. The EOL-property is kept in the document, not in the editor view. When a document is being opened its EOL-sequence is derived from the contents (whatever occurs most often is picked). It can be changed via the status bar UI or via the [`TextEditorEdit`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1058). We should probably also allow that via [`TextEdits`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1910). I'll create a separate item for this.

**Comment by jrieken** [comment] 2016-11-15 13:55
issue about EOL-sequence in the `TextDocument`: #15385

**Comment by jrieken** [comment] 2016-11-15 13:55
Closing because I have pushed changes that make sure we don't duplicate newlines anymore

**Closed by jrieken** 2016-11-15 13:55 UTC
Labels: bug, format, important

**Comment by HookyQR** [comment] 2016-11-15 19:39
@jrieken, there is no `eol` parameter on the document, (technically, or the editor):

(active is the currently active editor)
```
active.document.eol: undefined
active.document._eol: undefined
active.eol: undefined
active._eol: undefined
active._documentData._eol: '\n'
```

So when the document is passed to the formatter, there is no `eol` parameter available.

**Comment by jrieken** [comment] 2016-11-15 19:55
@HookyQR Yes - that's why I have created #15385

**Comment by jrieken** [comment] 2016-11-15 19:55
Well, stupid me... I meant #15510

**Comment by HookyQR** [comment] 2016-11-15 19:56
I thought I was going in a loop... :)

**Comment by HookyQR** [comment] 2016-11-18 19:36
@jrieken small problem, the formatter is being called twice when triggered from `onWillSaveTextDocument`. With no code changes, I've tested under `1.7.1` and **Insiders**. `1.7.1` only triggers the format once. **Insiders** triggers it twice. Everywhere else is fine.

**Comment by jrieken** [comment] 2016-11-21 08:30
@HookyQR Is that because you have format on save enabled *and* implement an onWillSave-handler?

**Comment by HookyQR** [comment] 2016-11-21 17:49
Yep, seems that was it. So effectively I can drop the `onWillSave` handler completely right?

**Comment by jrieken** [comment] 2016-11-22 08:30
yeah - for formatter that shouldn't be required anymore

**Comment by roblourens** [comment] 2016-12-12 22:53
Actually I was able to see the difference with the repro, verified.
