### ISSUE TITLE
Detect File Encode Wrong

### ISSUE THREAD

**Issue by getvictorh** [microsoft/vscode#79675] opened 2019-08-23 03:04 UTC
Issue Type: <b>Bug</b>

Opening files on Windows-1252 detects ISO 8859-2. 
When you try to save it to another encode, such as UTF-8 does not save it. 
In many cases, it incorrectly detects files in the format tis620 when they are actually in UTF-8.
VSCode is an excellent editor and works great, but it is not usable with these bugs. Please fix these bugs.
Thanks a lot

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
apacheconf-snippets|eim|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
uikit-3-snippets|Ken|1.4.2
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.2.0

</details>

**Comment by byyxx128** [comment] 2019-08-23 04:55
Duplicate of #33720

**Comment by getvictorh** [comment] 2019-08-26 02:01
Thank you very much for answering @byyxx128.
To try to be clearer, I tell my experience:
When the "Auto Guess Encoding" option is enabled, Viusal Studio Code is not able to correctly detect the encoding of the files. Usually if they are saved in UTF-8, it works fine, except for some cases where it detects tis620, but if it is saved in Windows-1252, it almost always works badly. It can detect ISO-8859-2.
When you open a file in which another encode is detected by mistake, if you click on the bottom bar and then click on save with another encode, it does not work, leave it in the original encode.
This was tested on Mac OSX 10.13.4, Windows 10 and Linux (Ubuntu 19.04, Debian 10 and Deepin 15.11.
If these same files are opened with Sublime Text 3, Notepad ++, Brackets, Gedit and other editors, they work without problems.

**Comment by bpasero** [comment] 2019-08-26 14:17
@getvictorh so the steps would be:
* auto guess encoding enabled (and you have no workspace encoding configured)
* you open a file that is wrongly detected to be cp1252
* from the status bar you select to save with a specific encoding

=> 🐛 still the auto guessed encoding is taken?

Can you attach that file?

**Comment by bpasero** [comment] 2019-08-27 09:24
@getvictorh I cannot reproduce, here is what I tried:
* configure `"files.autoGuessEncoding": true`
* open an empty file
* type in "öäü" and save normally
* close the file
* open the file
* it will be detected as `cp1252`
* remove the garbled characters and type "öäü" again
* from the status bar pick to save with encoding `utf8`
* reload app

=> the editor opens in UTF-8 and the characters typed are preserved properly

**Closed** 2019-09-03 09:52 UTC
Labels: file-encoding, needs more info
