### ISSUE TITLE
Can not be removed code

### ISSUE THREAD

**Issue by sj19101019** [Microsoft/vscode#38176] opened 2017-11-13 02:45 UTC
- VSCode Version: 1.18
- OS Version: windows 7 x64

Steps to Reproduce:

When I wanted to remove the code, it has be to a crash.
1.
![issuse](https://user-images.githubusercontent.com/19618640/32707423-ad5bf866-c85e-11e7-854a-bd769d0f6520.png)

2.
![issuse2](https://user-images.githubusercontent.com/19618640/32707447-da745f78-c85e-11e7-9d29-876ee754564a.png)

**Comment by bpasero** [comment] 2017-11-13 05:49
@alexandrudima @isidorn this is not the first time I am seeing users having a file full of breakpoints and as a result that leads to a crash...

**Comment by isidorn** [comment] 2017-11-13 10:03
Potentially a duplicate of https://github.com/Microsoft/vscode/issues/37880
@sj19101019 can you please try reproducing with latest vscode inisders from here https://code.visualstudio.com/insiders/ because that versoin contains a fix for the potential duplicate

@bpasero can you ping me on other issues like this one that you saw

**Comment by olivierchatry** [comment] 2017-11-14 07:47
@isidorn insiders fix this bug for me. Any plan on updating the current version ? It is a super annoying bug :/

**Closed** 2017-11-14 08:53 UTC
Labels: freeze-slow-crash, needs more info, new release

**Comment by isidorn** [comment] 2017-11-14 11:09
Yes, we will update the  current version in a couple of days. The update will contain this fix.
