### ISSUE TITLE
When opening the terminal for the first time after startup, it doesn't get focus

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#43652] opened 2018-02-14 11:51 UTC
- VSCode Version:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:10:15.949Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open VS Code
2. open the terminal
3. **focus is still on the editor**
4. close terminal
5. open it again
6. focus is now on the terminal as it should be

Does this issue occur when all extensions are disabled?: Yes

Might be related to https://github.com/Microsoft/vscode/issues/40416.

**Comment by Tyriar** [comment] 2018-02-14 15:43
Yep this is a duplicate of #40416

**Closed by Tyriar** 2018-02-14 15:43 UTC
Labels: integrated-terminal
