### ISSUE TITLE
[powershell] collapsible regions

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#10900] opened 2016-08-24 15:50 UTC
- VSCode Version: 1.4.0
- OS Version: OSX

Code collapsing works well in PowerShell for most things but it doesn't work for the region tags.
# region
## Stuff here
# endregion

**Comment by sandy081** [comment] 2016-08-25 11:38
Currently folding is supported only through indentation

**Comment by adbertram** [comment] 2016-08-25 13:39
Correct thus the feature request.

**Comment by aeschli** [comment] 2016-08-29 06:02
blocked by #3422

**Comment by kendalf1** [comment] 2016-12-13 14:43
Collapsable is misspelled in the title - it should be collapsible.  This may help with search.

**Comment by aeschli** [comment] 2016-12-13 14:44
Thanks @kendalf1, I fixed the title

**Comment by aeschli** [comment] 2017-08-09 14:54
duplicate of #12146

**Closed by aeschli** 2017-08-09 14:54 UTC
Labels: feature-request
