### ISSUE TITLE
[Extension Authoring] TreeDataProvider update doesn't cause update of collapsibleState of TreeItems

### ISSUE THREAD

**Issue by rugpanov** [microsoft/vscode#54192] opened 2018-07-12 16:33 UTC
- VSCode Version: 1.25.0
- OS Version: Win10

Steps to Reproduce:
1. Create `TreeDataProvider`
2. Put a `TreeItemCollapsibleState.Collapsed` TreeItem there and save a ref to it
3. Fire `TreeDataProvider#onDidChangeTreeData` 
`Note:` *as expected now there is a **collapsed** `TreeItem` in the `TreeDataProvider`*
4. Change collapsibleState of the `TreeItem` to the `TreeItemCollapsibleState.Expanded` via the stored ref
5. Fire `TreeDataProvider#onDidChangeTreeData` 

`Expected result:` There is an **expanded** `TreeItem` in the `TreeDataProvider`
`Actual result:`   There is a **collapsed** `TreeItem` in the `TreeDataProvider`

`Note 1:` It worked correctly in VSCode 1.24.0 but not in 1.25.0 for me
`Note 2:` changing collapsibleState in the UI still works.
`Note 3:` changing collapsibleState from TreeItemCollapsibleState.Expanded/Collapsed to TreeItemCollapsibleState.None works fine.

**Comment by sandy081** [comment] 2018-07-13 08:35
Duplicate of #30918

**Comment by rugpanov** [comment] 2018-07-13 08:39
@sandy081, are you sure this is the same issue? 
One I reported is appeared after update from 1.24.0 to 1.25.0
And it has another description

**Comment by sandy081** [comment] 2018-07-13 13:59
@rugpanov There was a similar issue before which is a dup of #30918. 

Since you are mentioning it is working in previous release, I will check it.

**Comment by fabiospampinato** [comment] 2018-08-06 14:12
I'm also having this problem.

I want to add a collapse/expand button to the navigation bar, but the only ways that I've found for actually collapsing/expanding the tree are:

1. Clearing it first, then rebuilding it collapsed
2. Change the labels by appending a random number of whitespace characters to them

The obvious solution is just setting `TreeItem.collapsibleState` to something, which doesn't work.

**Comment by sandy081** [comment] 2018-08-29 15:15
This is another issue related to `shouldAutoexpand` api from the tree which shares the same root cause of #30918.

**Comment by sandy081** [comment] 2018-08-29 15:18
If you want a node to be expanded or collapsed programatically, may be the right approach is to have an API to expand or collapse instead of causing a data change?

**Comment by fabiospampinato** [comment] 2018-08-29 15:27
@sandy081 Why not both an API and listening for a mutation of the `collapsibleState` property? The "problem" with the API is that we would have to keep references to the `TreeItem`s around.

**Comment by rugpanov** [comment] 2018-08-30 08:30
It used to work with `collapsibleState` property and some extension authors used it. So from this perspective it would be better to return this way. In any case - with separate API or with previous approach, now it doesn't work and for me this is a problem. Please could you provide a possibility to expand/collapse a collapsible tree item in the nearest release.

**Comment by sandy081** [comment] 2018-08-30 15:03
@rugpanov It only works consistently if you give the state for the first time and was not working completely. See #30918

**Comment by rugpanov** [comment] 2018-08-30 15:46
@sandy081 Now I see. So are there any plans about adding such a functionality? It would be really useful for an extension authoring.

**Comment by sandy081** [comment] 2018-08-31 08:06
There are plans to add an API to expand/collapse - https://github.com/Microsoft/vscode/issues/55879

**Comment by johnspurlock** [comment] 2019-02-18 01:24
`.collapse` was never added on the view, so it's currently impossible to collapse a single item!  `.reveal({expand:false})` does not work either.

For example, try to implement toggle-expansion-on-select behavior to mimic the built-in explorer.  Can track the real state using `onDid(Expand|Collapse)Element`, but can only set a new state of expanded, using `.reveal({expand:true})` - impossible to set collapsed.  Any workarounds appreciated. : )

As mentioned earlier in this bug, updating an existing TreeItem's `collapsibleState` has no effect.

Current stable (1.31) and insiders (1.32).

Thanks!

**Comment by alexr00** [comment] 2020-11-06 14:03
duplicate of https://github.com/microsoft/vscode/issues/78970

**Closed by alexr00** 2020-11-06 14:03 UTC
Labels: bug, explorer-custom
