### ISSUE TITLE
Font super bold after latest update

### ISSUE THREAD

**Issue by pozdena** [microsoft/vscode#214511] opened 2024-06-06 19:55 UTC
Type: <b>Bug</b>

I'm using Operator Mono 16 pt and never had a problem but now it's bold

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:48.028Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (11.94GB free)|
|Process Argv|--crash-reporter-id 7b1f2bec-4679-4e86-a12b-f35a8df5e6be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
html-preview-vscode|geo|0.2.5
vscode-graphql|Gra|0.11.0
vscode-graphql-execution|Gra|0.2.6
vscode-graphql-syntax|Gra|1.3.6
dummytextgenerator|gur|1.0.1
vscode-colorize|kam|0.11.1
auto-dark-mode|Lin|0.1.7
prisma|Pri|5.15.0
svg-preview|Sim|2.8.3
highlight-matching-tag|vin|0.11.0
gitblame|wad|11.0.1
propertylist|zho|0.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31067618
26j00206:31048877

```

</details>

**Comment by pozdena** [comment] 2024-06-06 19:56
<img width="441" alt="image" src="https://github.com/microsoft/vscode/assets/3536798/1a9b97f1-b35b-4365-ba9b-3f25253413b3">

**Comment by pozdena** [comment] 2024-06-06 19:56
<img width="286" alt="CleanShot 2024-06-06 at 15 56 41@2x" src="https://github.com/microsoft/vscode/assets/3536798/f2cec337-fd3a-4085-b6ec-dcc1794aa042">
 
 Font weight is already `normal`

**Comment by damons** [comment] 2024-06-06 20:43
Same issue for me.  After upgrading from 1.83 to 1.90, it seems to ignore all font weight details.  

I'm using "IBM Plex Mono UltraLight" and no matter what, it uses the heavyweight version of the font.  

Downgrading immediately fixes the issue.

**Comment by victordidenko** [comment] 2024-06-06 20:45
Same font (Operator Mono), same operating system (macOS), same issue for me.
Font rendering become drastically worse :(
And `editor.fontWeight` doesn't fix an issue with any value, with values less that 350 font become too thin.

**Comment by damons** [comment] 2024-06-06 20:46
Likely same issue as https://github.com/microsoft/vscode/issues/214461

**Comment by victordidenko** [comment] 2024-06-06 20:55
And this one #214390

**Comment by rzhao271** [comment] 2024-06-06 21:35
Duplicate of https://github.com/microsoft/vscode/issues/214390

**Closed by rzhao271** 2024-06-06 21:35 UTC
Labels: new release
