### ISSUE TITLE
 locale.json config can't take effect after updating.

### ISSUE THREAD

**Issue by akq** [Microsoft/vscode#5295] opened 2016-04-15 02:54 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 8.1 Simplified Chinese.

Steps to Reproduce:
1. the ui in last version is in English.
2. After updating, the ui becomes Chinese, I checked locale.json, the config is still 'en-US'. but it seems no effect on the UI.
3. Change the property to zh-CN and restart, then change it back to en-US and restart, it then get worked.

**Comment by hungys** [comment] 2016-04-15 03:42
+1.

But one restart can solve the issue, you don't need to change to zh-CN and back.

**Comment by akq** [comment] 2016-04-15 06:43
I have tried restart. but if you don't modify the locale.json, simply restartting can't resolve this issue.

**Comment by mizunashi-mana** [comment] 2016-04-16 01:24
+1

OS Version: Windows 10

**Comment by dbaeumer** [comment] 2016-04-18 09:03
I can't reproduce this. What is the case is that changing the value requires a restart. This is stated in the file. Please be aware that you really need to close VSCode and restart it. Reloading the Window is not enough.

@akq can you please attach a video showing what you are seeing.

**Comment by akq** [comment] 2016-04-18 17:21
@dbaeumer Thanks for your quick response.
I can reproduce this bug, and I know the cause after reading the source code. But I haven't set up the debugging environment yet, so hopefully you can easily resolve it.

1. My previous version is 0.10.11, its UI is English by default. In this version, there is no `Configure Language ` command, and no locale.json as well. To reproduce this issue, **remove your locale.json file**.

![no-config](https://cloud.githubusercontent.com/assets/1907927/14612792/ac5f011c-05cb-11e6-8bd6-5a263d0766b6.jpg)

2. When updating, the seed url will depend on the `${ env.getPlatformIdentifier() }` at the line 224 of [update-manager.ts](https://github.com/Microsoft/vscode/blob/84abe71111ac14dd58e14565a74a55af0ae6b797/src/vs/workbench/electron-main/update-manager.ts). My platform is simplified Chinese version, so this update media will be in Chinese version as well. (It's another bug, I use the English, why the server forces me to install Chinese version?)

![updated install](https://cloud.githubusercontent.com/assets/1907927/14612717/473ffc8c-05cb-11e6-8021-54dcb226aa38.JPG)

3. After updating, the UI becomes Chinese. If I don't use the command '配置语言' (`Configure Language` in Chinese translation) , the locale.json will not be generated. and the variable `locale` (at line 66 of [main.js](https://github.com/Microsoft/vscode/blob/c82ac047c4f43f738d212c3d6e600180475543d0/src/main.js)) will be the value of `app.getLocale()`, in my case, it's `zh-CN`, so I get Chinese UI.

![config_cn](https://cloud.githubusercontent.com/assets/1907927/14612716/473e8c26-05cb-11e6-962d-bb1f62861796.jpg)

4. The default content of locale.json is defined at [configureLocale.ts](https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/src/vs/workbench/browser/actions/configureLocale.ts), but the locale value is fixed to `en-US`, that's why I get confused when I opened the new generated locale.json with the Chinese command `Configure Language`. @hungys, you are right, after the locale.json is generated, restarting will resolve the issue, and the English UI will come back.

![locale json](https://cloud.githubusercontent.com/assets/1907927/14612718/4741a816-05cb-11e6-8be7-a33397e3dc84.jpg)


So my suggestion is 
1. the seed url for updating media should be the same language as the client's current locale setting.
2. if there is no locale.json file, just use en-US by default, the command localization is not a smart choice for a developer. (see the Chinese command above, it's ineffective.)
3. if there is an language selection option during the installation, that's would be better.

**Comment by dbaeumer** [comment] 2016-04-19 14:58
@akq thanks a lot for the detailed response. We discussed a solution for this back and force and we landed on the following improvements: 

- when possible we honor OS locale. So the installer and VSCode will start by default in the locale of your OS
- for commands we will allow typing them in English and the picked UI language. So although VSCode might show Chinese you can still type git pull to execute git pull
- we will add menu contributions to switch the UI Language
- when the default locale.json is generate we will take the current UI language to avoid confusion.

**Comment by dbaeumer** [comment] 2016-04-19 19:19
See https://github.com/Microsoft/vscode/issues/5512

**Comment by iamCristYe** [comment] 2017-05-08 03:24
@dbaeumer
Should this issue be closed?

**Comment by dbaeumer** [comment] 2017-05-08 07:19
@iamCristYe Yes. Thanks for pinging.

**Closed by dbaeumer** 2017-05-08 07:19 UTC
Labels: bug, i18n, needs more info
