### ISSUE TITLE
Search everywhere

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#52773] opened 2018-06-24 22:01 UTC
Coming from WebStorm, the one feature I find myself missing in VS Code is ["search everywhere"](https://www.jetbrains.com/help/webstorm/searching-everywhere.html).

At the moment, this can be partially implemented by using `Quick Open` with the following setting: `"search.quickOpen.includeSymbols": true`. However, even with this setting, not all symbols are actually shown (e.g. methods and properties).

And, there are still missing pieces:

1. `shift shift` support (an [existing feature request](https://github.com/Microsoft/vscode/issues/5280)).

2. Showing ALL symbols including methods and properties (which is not currently the case with the `Quick Open` setting.

3. Show commands, files, classes, etc.

4. Organize results under separate headings (files/symbols/commands) along with tabs. Example shown below.

<img width="1440" alt="screen shot 2019-01-07 at 11 11 10 am" src="https://user-images.githubusercontent.com/12591890/50782344-5ea33400-126d-11e9-82ad-8f8105d24cd6.png">

**Comment by aimergenge** [comment] 2019-03-28 02:37
any plan for this?

**Comment by bpasero** [comment] 2020-03-19 10:22
I added a new setting to stop filtering symbols from the quick open results when `search.quickOpen.includeSymbols` is enabled:

`search.quickOpen.workspaceSymbolsFilter`: Controls the filter to apply for the workspace symbols search in quick open. Depending on the setting, some symbols like local variables will be excluded to reduce the total number of results
* `default`: All symbols including local variables are included in the specific workspace symbols picker but excluded from the files picker when `search.quickOpen.includeSymbols` is enabled.
* `reduced`: Some symbols like local variables are excluded in all pickers
* `all`: All symbols including local variables are included in all pickers

To include all symbols in the default quick open, just configure:
* `search.quickOpen.workspaceSymbolsFilter: all`
* `search.quickOpen.includeSymbols: true`

**Comment by bpasero** [comment] 2020-03-20 12:53
Re-opening given the discussion in https://github.com/microsoft/vscode/issues/86761

**Comment by bpasero** [comment] 2020-03-20 12:54
Marking as duplicate of https://github.com/microsoft/vscode/issues/86761

**Closed** 2020-03-20 12:54 UTC
Labels: *duplicate, feature-request, quick-pick, workspace-symbols
