### ISSUE TITLE
Code navigation gets very slow

### ISSUE THREAD

**Issue by vyemialyanchyk** [Microsoft/vscode#54316] opened 2018-07-14 17:15 UTC
Issue Type: <b>Bug</b>

Ctrl+LMouse stops work smooth after update to lates version...

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.3.9600

**Comment by Tyriar** [comment] 2018-07-16 14:24
What language?

**Comment by vyemialyanchyk** [comment] 2018-07-17 09:08
JavaScript/TypeScript

**Comment by mjbvz** [comment] 2018-07-18 21:52
Please provide proper repo steps and example code

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by vyemialyanchyk** [comment] 2018-07-26 20:49
Practically I use VS Code without extentions, or couple were installed before and all was smooth.
The problem gets visible and anoing in 1.25.1 only.
With the version for insiders it is practically invisible. Start VS, open some ts file, wait couple of seconds, and able to navigate to File interface for example. Much better, but I can't state smooth, cause before 1.25.1 I even pay no attantion for that, now I calculate feeling is frustration or not )))

**Comment by mjbvz** [comment] 2018-07-26 22:19
Closing since it sounds like it is fixed in insiders builds. Let me know if you start notice it on insiders

**Closed by mjbvz** 2018-07-26 22:19 UTC
Labels: typescript
