### ISSUE TITLE
Please let me print

### ISSUE THREAD

**Issue by clandrew** [microsoft/vscode#73693] opened 2019-05-13 20:30 UTC
Issue Type: <b>Feature Request</b>

I would like to print out something- the preview of a Markdown file

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment] 2019-05-13 20:47
I haven't personally tried it, but the extension at https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print looks like it might help you.

**Comment by clandrew** [comment] 2019-05-13 20:53
hm, ok
I would still like to see this as a built-in feature since most Windows programs that can edit text can also print the text
maybe I can look into it sometime as a workaround the next time I hit this.

**Comment by mjbvz** [comment] 2019-05-13 22:31
Duplicate of #5953

**Closed by mjbvz** 2019-05-13 22:31 UTC
Labels: markdown
