### ISSUE TITLE
VS Code Remote with WSL "Install from VSIX..." prepends "C:" to the path.

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/vscode#79243] opened 2019-08-15 19:35 UTC
- VSCode Version: 1.37.0
- OS Version: Windows Build 18962

Steps to Reproduce:

1. Launch VS Code Remote from Linux command line with `code .`
2. Use the command palette to run `Extensions: Install from VSIX...`
3. Select a VSIX extension in the Linux file system
4. Receive error: `ENOENT: no such file or directory, open 'C:\home\bob\projects\test\test.vsix'`
5. The error seems to be in the fact that a `C:\` is being prepended to the Linux file location.

Does this issue occur when all extensions are disabled?: Yes

This was originally posted to the WSL github page. https://github.com/microsoft/WSL/issues/4410

All credit to @rdubner for finding this one! :)

**Comment by aeschli** [comment] 2019-08-20 10:09
duplicate of https://github.com/microsoft/vscode-remote-release/issues/1027

**Closed by aeschli** 2019-08-20 10:09 UTC
