### ISSUE TITLE
Double clicking on a lazy variable name to edit edits the preview instead of the value

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#143786] opened 2022-02-23 18:22 UTC
Testing #143572

1. Have a lazy variable with a `value` preview. In js-debug the preview is just the stringified function
2. Double click on the _name_ of the variable to try to edit it
3. Get in this state where the getter is still collapsed and the value is being edited

![image](https://user-images.githubusercontent.com/2230985/155382878-732ddee1-87a0-41bc-9475-edf72a990c5f.png)

Instead the variable should automatically expand and its value should be edited

**Comment by JacksonKearl** [comment] 2022-02-23 18:56
In mock-debug this is surfaced as `lazy var` appearing on click and staying there after focus leaves

**Comment by roblourens** [comment] 2022-02-24 00:29
Dupe of #143751

**Closed by roblourens** 2022-02-24 00:29 UTC
Labels: debug
