### ISSUE TITLE
Revert Push menu item back to primary menu. Poor UX

### ISSUE THREAD

**Issue by andrewhawkes** [microsoft/vscode#104912] opened 2020-08-18 09:29 UTC
Originally, it was one menu click to "Push", it is now buried under a secondary menu which has introduced another level of tedium.

![image](https://user-images.githubusercontent.com/4975742/90496184-6b705500-e13d-11ea-95f1-638cf8433dcb.png)

Is there any reasoning for this and can it be reverted via options or by default?

**Comment by gjsjohnmurray** [comment] 2020-08-18 09:35
/duplicate of #104762, and as a workaround you may be interested in https://github.com/microsoft/vscode/issues/104762#issuecomment-674902220

**Closed** 2020-08-18 09:35 UTC
Labels: *duplicate

**Comment by andrewhawkes** [comment] 2020-08-18 10:30
@gjsjohnmurray thanks! I did search but I didn't find anything. I'll look harder next time :)
