### ISSUE TITLE
Make indent guides extend through sticky scroll

### ISSUE THREAD

**Issue by jibbers42** [microsoft/vscode#159809] opened 2022-09-01 21:23 UTC
I'd like for the indent guide lines to extend through the sticky scroll region. In the screenshot, it would be nice for the yellow line to be drawn all the way to the word `class`. This begins to be useful at two lines and would become more useful as the sticky scroll region increases in line count.

![image](https://user-images.githubusercontent.com/797824/188014386-4344a929-67a7-4c8c-8cd3-4ad31f7fdf65.png)

**Comment by aiday-mar** [comment] 2023-07-13 13:40
Hi, thanks for filing the issue. An issue has been opened which aims to add all kinds of decorations to sticky scroll, such as diff background colors, highlights, code lens text, indentation guides. You may track and upvote the issue here: https://github.com/microsoft/vscode/issues/187834

**Comment by aiday-mar** [comment] 2023-12-05 11:32
Hi. This issue is a duplicate of this issue https://github.com/microsoft/vscode/issues/159809. It will be closed in favor of the other issue. You can track progress on this issue there.

**Closed by aiday-mar** 2023-12-05 11:32 UTC
Labels: feature-request, editor-sticky-scroll, editor-sticky-scroll-decorations
