### ISSUE TITLE
How to make VSCode to replace the word when accepting autocomplete hint?

### ISSUE THREAD

**Issue by MichalMichalak** [Microsoft/vscode#22499] opened 2017-03-13 01:16 UTC
When I tried to open an issue here, I got below hint.

> Do you have a question? Please ask it on http://stackoverflow.com/questions/tagged/vscode

So I did, and opened a question on SO[1], hoping that someone from VSCode team would answer, but seems like no one is tracking these questions. Let me repeat the question here.

JetBrains IDE platform have very useful feature, which I am using a lot and I find it a performance booster. When I have a word in editor, and I want to change or update that word, I do the following.

- Place cursor in front of the word (or in middle, ex. when I want to change only last part.)
- Start typing until I got autocomplete I want to use.
- Press TAB or ENTER.
  - On TAB - Old word is completely replaced by new word. This is especially useful when I update some names, in which beginning of word is the same, but ending is different. For example, change getTimeInSeconds() to getTimeInMinutes() - I put cursor after getTimeIn, get autocomplete, and press TAB. Nothing left to delete, everything is replaced.
  - On ENTER - New word is replaced from the start of old word, but right part from the cursor stays on screen.

By default VSCode supports only "ENTER" use case. Does it support "TAB" use case? If so, how to enable it?

---

[1] http://stackoverflow.com/questions/41948329/how-to-make-vscode-to-replace-the-word-when-accepting-autocomplete-hint

**Comment by jrieken** [comment] 2017-03-13 12:51
this is a dupe of #10266

**Closed by jrieken** 2017-03-13 12:51 UTC
