### ISSUE TITLE
Unable to Remove Binding for Workbench ZoomIn and ZoomOut

### ISSUE THREAD

**Issue by objectuser** [Microsoft/vscode#14720] opened 2016-10-30 20:54 UTC
- VSCode Version: 1.6.1
- OS Version: OSX 10.12.1

Per [these](https://code.visualstudio.com/docs/customization/keybindings#_removing-a-specific-key-binding-rule) instructions, I attempted to remove the zoom in and zoom out behavior of the workbench in order to let the OS use the binding.

Steps to Reproduce:
1. Unbind the keys:

```
  { "key": "cmd+=",                 "command": "-workbench.action.zoomIn" },
  { "key": "cmd+-",                 "command": "-workbench.action.zoomOut" }
```
1. Then use `cmd+=` and `cmd+-` and the workbench still zooms in and out.

**Comment by alexandrudima** [comment] 2016-10-31 08:52
@objectuser This works for me after closing and restarting VS Code. The reason is that these actions are displayed in the View menu and there we don't update the keybindings until we restart. 

So any keybindings removals for actions we render in the top level menu don't really take effect until VS Code is restarted.

fyi @bpasero I was able to reproduce also on Windows (I thought Electron dispatches keybindings through the menu bar only on macOS, but looks like it does it now also on Windows).

**Comment by bpasero** [comment] 2016-10-31 08:55
Yup, needs a restart. There is another feature request opened to update the menu live when changing keybindings.json.

**Closed by bpasero** 2016-10-31 08:55 UTC

**Comment by alexandrudima** [comment] 2016-10-31 08:58
Just a note: at least on Windows, this is a regression from recent versions of Electron. The restart was not required on Windows in the past.

**Comment by objectuser** [comment] 2016-10-31 12:36
Thanks very much!

Should this trigger an new issue in Microsoft/vscode-docs?
