### ISSUE TITLE
Window won't render/restore

### ISSUE THREAD

**Issue by Camios** [microsoft/vscode#207668] opened 2024-03-14 05:00 UTC
Type: <b>Bug</b>

A couple of times in the last week I've been running multiple VS Code windows simultaneously and found that one of them won't show its window any more. The other works fine.

I've tried using windows 11 app/monitor docking shortcuts but it doesn't work. The faulty window shows on the task bar and in the list of apps to alt-tab through. Tried restarting explorer.exe (in case it was the problem), but that didn't help either.

The faulty window was maximised and it was performing a long-running debugpy (python) debug session.
I access this computer via remote desktop and in the latest instance I had been logged-out (inactivity) before logging back in again to find one of the windows wouldn't display any more.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.72GB (83.01GB free)|
|Process Argv|E:\\dev\\<snip>\\.vscode\\fbcli.code-workspace --crash-reporter-id f7ab30df-e6d5-46d4-8630-294e93f9777b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
debugpy-old|ata|2023.1.12492010
githistory|don|0.6.20
python-environment-manager|don|1.2.4
xml|Dot|2.5.1
gitlens|eam|14.9.0
communicationhubtools|Ele|1.1.0
json-tools|eri|1.0.2
nsis|idl|4.2.4
vscode-graphviz|joa|0.0.9
vscode-azurefunctions|ms-|1.13.4
vscode-azureresourcegroups|ms-|0.8.4
vscode-bicep|ms-|0.26.54
vscode-cosmosdb|ms-|0.20.1
csdevkit|ms-|1.4.29
csharp|ms-|2.22.3
vscode-dotnet-runtime|ms-|2.0.2
vscodeintellicode-csharp|ms-|0.1.26
autopep8|ms-|2023.8.0
debugpy|ms-|2024.3.10731008
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.86.0
azure-account|ms-|0.11.6
azurecli|ms-|0.6.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.7
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.0.0
azurerm-vscode-tools|msa|0.15.11
cosmosdbsqlapi|Sav|0.0.60
markdown-preview-enhanced|shd|0.8.12
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by aiday-mar** [comment] 2024-03-14 08:26
Seems to be connected to remote connections, not sure if I correctly assigned, feel free to reassign

**Comment by bpasero** [comment] 2024-06-13 05:53
Was this involving floating windows?

**Comment by Camios** [comment] 2024-06-16 23:15
I had multiple VS Code sessions open. It was their main windows.

**Comment by bpasero** [comment] 2024-06-17 05:27
Do you have steps to reproduce for me?

**Comment by Camios** [comment] 2024-06-18 06:30
No, sorry.  I'd say it was an intermittent problem. My current work doesn't have me using VS Code as much and I haven't seen it in the last couple of weeks.

**Closed** 2024-06-19 04:27 UTC
Labels: info-needed
