### ISSUE TITLE
The top toolbar is hidden ! 

### ISSUE THREAD

**Issue by OmarSAlGhamdi** [microsoft/vscode#159902] opened 2022-09-02 13:18 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

The app doesn't appear very well when the language of the computer is Arabic. The top left toolbar is hidden under the exit and minimize bar!

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.91GB (11.18GB free)|
|Process Argv|--crash-reporter-id 07ce8423-a1fa-4765-9ea9-68b627e1547f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
askia-qexml-generator-extension|Ask|1.0.1
vscode-intelephense-client|bme|1.8.2
doxdocgen|csc|1.4.0
dart-code|Dar|3.48.0
rust-syntax|dus|0.6.1
vscode-html-css|ecm|1.13.1
batch-rename-extension|Jan|0.0.5
better-cpp-syntax|jef|1.15.19
rust-doc-viewer|JSc|3.0.3
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.0
onedrive-browser|ms-|0.0.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
vscode-lldb|vad|1.7.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

![لقطة الشاشة 2022-09-02 161738](https://user-images.githubusercontent.com/31236422/188154354-265595ab-3e94-4d55-801c-9678358b4556.png)

**Comment by gjsjohnmurray** [comment] 2022-09-02 13:32
/duplicate of https://github.com/microsoft/vscode/issues/159813 where you can also find a setting to toggle that will work around this.

**Closed** 2022-09-02 13:33 UTC
Labels: *duplicate, new release
