### ISSUE TITLE
Visual Studio Code Icons and Text looks blurry

### ISSUE THREAD

**Issue by echonox** [Microsoft/vscode#1334] opened 2015-12-15 14:11 UTC
![screenshot 20](https://cloud.githubusercontent.com/assets/9529847/11812730/d9e426da-a33d-11e5-94bf-d5aa826942c2.png)

First time installing on fresh Windows 10 and this is how it looks, it doesn't stay like this, but it moves like some ripple effect or something how can I fix this?

**Comment by bpasero** [comment] 2015-12-15 19:58
Wow that looks bad, never saw something like that. If you install Atom, does it look the same?

**Comment by jack-dev** [comment] 2016-01-10 09:29
@bpasero I can confirm same issue on Atom and Light Table, on Brackets on the other hand its ok, could you please explain why its this the case, its clearly rendering issue but why?!

**Comment by bpasero** [comment] 2016-01-11 06:17
@jack-dev no I cannot explain it, if you file the same bug against Atom, it will get the attention of the Electron guys (underlying UI framework) which maybe helps us find the actual issue here.

**Comment by sangohan** [comment] 2016-04-14 21:55
The issue is very likely chrome's use of directwrite to draw the UI. The same problem appears in chrome for me (chrome 41 and above?).

**Comment by Tyriar** [comment] 2016-04-14 22:10
@sangohan I opened https://github.com/electron/electron/issues/5165 to expose the flag in electron.

**Comment by Tyriar** [comment] 2016-04-15 18:03
Apparently the flag works, but not documented in https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by bpasero** [comment] 2016-04-21 06:34
We pushed a major update to the UI framework to our insiders release and would appreciate feedback if this issue got resolved. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!

**Comment by bpasero** [comment] 2016-06-06 17:08
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-06-06 17:08 UTC
Labels: bug, upstream

**Comment by echonox** [comment] 2016-06-07 07:24
@bpasero First of all please accept my apologize for not responding so soon, I am afraid I can't provide you with a feedback because the issue were my AMD Radeon Graphics Drivers, after an Update was released the issue was gone. Thanks for your hard work!
