### ISSUE TITLE
Live Preview

### ISSUE THREAD

**Issue by amfunteam** [microsoft/vscode#118107] opened 2021-03-04 10:56 UTC
A lot of people want a live preview inside vs code because it is annoying to switch tabs. Also, it uses a lot of memory. So it will be better if you guys add live HTML, CSS, and js preview inside vs code. Make it an extension or built-in. That will be very good.

**Comment by mjbvz** [comment] 2021-03-04 21:13
Duplicate of #12080

**Closed by mjbvz** 2021-03-04 21:13 UTC
Labels: *duplicate
