### ISSUE TITLE
Multiple Workspaces in the same window

### ISSUE THREAD

**Issue by LemonBoiDotExe** [Microsoft/vscode#43866] opened 2018-02-17 00:22 UTC
Workspaces are the only solution I have to fixing my debugging problem.. and I cant even have them all in the same window and that drives me absolutely insane.. and I really need to see all my folders in the side with every workspace holding the files for the language its for (Thats how I organize it personally) but the workspace tab already acts like a folder with the opening and closing to hide or show the contents so why cant we have multiple in the same tab? please add it so I can continue Loving this amazing editor..

**Comment by bpasero** [comment] 2018-02-17 08:17
@LemonBoiDotExe to be clear, you want to open multiple folders in the same window?

**Comment by LemonBoiDotExe** [comment] 2018-02-17 17:50
Okay so basically to break it down I have a workspace for every language I program in. But Im only able to have one of them in a window. If I try to add more it will open a seperate window for it and wont put it in the same window as the first. I already have multiple files set up but I want there to be a way I can switch between my workspaces without having to reopen the editor.

**Comment by bpasero** [comment] 2018-02-18 06:45
Ok, then I think duplicate of https://github.com/Microsoft/vscode/issues/43188

**Closed by bpasero** 2018-02-18 06:45 UTC
Labels: multi-root, needs more info
