### ISSUE TITLE
 Uncaught Error: Unable to display threads: "Cannot find Delve debugger at dlv. Ensure it is in your "GOPATH/bin" or "PATH"."

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20079] opened 2017-02-06 21:05 UTC
Issue Id: <b>e3405c18-0b08-b2d7-8907-412956bac4cc</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />Error: Unable to display threads: "Cannot find Delve debugger at dlv. Ensure it is in your "GOPATH/bin" or "PATH"."<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L176:30](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L176:30)<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1041:0 (_run)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1041:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData))<br />    at emitOne (events.js:96:13)<br />

**Comment by ramya-rao-a** [comment] 2017-02-06 21:10
Duplicate of #18329

**Closed by ramya-rao-a** 2017-02-06 21:10 UTC
