### ISSUE TITLE
Cmd + P searching for a file doesn't work

### ISSUE THREAD

**Issue by zxcware** [Microsoft/vscode#11994] opened 2016-09-14 01:01 UTC
- VSCode Version: 1.5.2
- OS Version: OS X EI Capitan 10.11.6

Steps to Reproduce:

1.  Open a relative large code base
2. Cmd + P, search for a file doesn't work!

**Comment by octref** [comment] 2016-09-14 01:31
Can you be a bit more specific about what didn't work?
Would be great if you can take a screenshot with `Cmd + Shift + 3` and put it here.

**Comment by chrmarti** [comment] 2016-09-14 05:35
@octref Could you run `time (find -L . -type f | wc -c); echo $?` and `time (find -L . -type f | wc -l); echo $?` in your project folder and paste the output here?

**Comment by markusm7** [comment] 2016-09-14 07:17
I've got a similar problem on Ubuntu 14.04.4 LTS with 1.5.2.
The search for the file doesn't end
Only recently opened files are listed. In addition, the search in the side bar doesnt work neither.
Im not sure when it started because i was programming on that machine pre 1.5

The output of the two time commands:
220824946

real	2m10.356s
user	0m0.928s
sys	0m22.060s
0

2143148

real	1m26.622s
user	0m0.912s
sys	0m21.208s
0

**Comment by chrmarti** [comment] 2016-09-14 15:10
@markusm7 You're guess is right, I'm using the 'find' command line tool to get the full list of files. I'm working on applying folder exclusions with find's -prune switch to recover the performance lost in cases with large excluded folders.

Thanks for the feedback. Closing as a duplicate of #11874.

**Closed by chrmarti** 2016-09-14 15:10 UTC
Labels: duplicate, needs more info
