### ISSUE TITLE
`Create: New Jupyter Notebook` command is not localized

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172247] opened 2023-01-24 18:51 UTC
![Screenshot 2023-01-24 at 12 43 59 PM (1)](https://user-images.githubusercontent.com/29464607/214382348-f1c07eda-d4d9-4354-9a11-b4b8e922268c.png)

**Comment by DonJayamanne** [comment] 2023-01-24 20:27
Duplicate of https://github.com/microsoft/vscode/issues/172246

**Closed by DonJayamanne** 2023-01-24 20:27 UTC
