### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by qiqingfu** [microsoft/vscode#74734] opened 2019-06-02 04:47 UTC
I tried to download the Mac version of the vscode editor on the official website, but jumped directly to the not foundation page. I wonder why?

**Comment by hrgupta** [comment] 2019-06-02 04:51
I am also getting the same error.

Link: https://update.code.visualstudio.com/latest/darwin/stable

Response: Not Found

**Comment by readuo** [comment] 2019-06-02 04:53
Same error. I tried to download older versions in different browsers. nothing works

**Comment by hrgupta** [comment] 2019-06-02 04:53
I just saw an issue for it has already been open. It's affecting multiple download links.

**Comment by GitHub-User22** [comment] 2019-06-02 05:10
I have the same problem.  The link for download redirects me to a page that says: "Not Found."

**Comment by GitHub-User22** [comment] 2019-06-02 05:12
![image](https://user-images.githubusercontent.com/51281492/58757096-641e4680-84ba-11e9-8ea1-9f8e39f08111.png)

**Comment by hiraqdev** [comment] 2019-06-02 05:26
This issue also affecting `Remote WSL` extension today 

![wslerror](https://user-images.githubusercontent.com/39719575/58757157-37594600-8531-11e9-9255-9e87400e2f55.PNG)

I just uninstalling Insider and still not working, every time editor opened, it try to download the update and got `500 internal server error`.  I'm also disable auto update, but i think it's too late now, need help for this issue, i'm using `Code - Insider` & `Remote WSL` for my daily works

**Comment by CarlJi** [comment] 2019-06-02 05:28
404 error occurred for URL: https://update.code.visualstudio.com/latest/darwin/stable
`➜  ~ curl -v "https://update.code.visualstudio.com/latest/darwin/stable"
*   Trying 104.42.78.153...
* TCP_NODELAY set
* Connected to update.code.visualstudio.com (104.42.78.153) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: update.code.visualstudio.com
* Server certificate: Microsoft IT TLS CA 5
* Server certificate: Baltimore CyberTrust Root
> GET /latest/darwin/stable HTTP/1.1
> Host: update.code.visualstudio.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
< request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
< X-Powered-By: Express
< Strict-Transport-Security: max-age=31536000
< X-Source-Commit: 9076449f9a910cfadcc0279a751f352280cec989
< Set-Cookie: ARRAffinity=06c134b3c9389fbb156c738e838d14a64c82219bd42d1857a4c800679837e9d9;Path=/;HttpOnly;Domain=update.code.visualstudio.com
< Date: Sun, 02 Jun 2019 05:27:39 GMT
<
* Connection #0 to host update.code.visualstudio.com left intact
Not Found%                                                                                                                                                            ➜  ~`

**Comment by MAETEX** [comment] 2019-06-02 05:35
The same problem. Downloading program for Windowsn10 and getting ,,Not Found" mesage

**Comment by CarlJi** [comment] 2019-06-02 05:38
Duplicate of #74732

**Comment by qiqingfu** [comment] 2019-06-02 10:55
Now you can download it properly

**Closed** 2019-06-03 07:17 UTC
Labels: *duplicate
