### ISSUE TITLE
Hovers show extension and unnecesery extension reason

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86080] opened 2019-12-03 14:04 UTC
Refs: #85933

Setup eslint as specified in #85933
Hover over an extra semicolon. Notice that the hover says `eslint` which makes sense such that the user is aware from what extension the error message is coming. However I do not understand why we also say `(no-extra-semi)`. Why would a user care about this? It just feels to me like clutter since the message from the extension should be explanatory enough

Creating in VS Code since I do no think this is an ES Lint issue, but on the VS Code side.

![Screenshot 2019-12-03 at 15 01 23](https://user-images.githubusercontent.com/1926584/70057833-1eb01280-15de-11ea-97d9-30879ed5c89e.png)

**Comment by dbaeumer** [comment] 2019-12-03 14:11
This is actually as designed since a lot of users using eslint ask for embedding the code to know which setting to use to enable / disable the rule.

The extension actually sets the code of a diagnostic. If we want to change this VS code should have a setting to not show the code.

@sandy081 please speak up if you think such a setting makes sense.

I will close the issue as designed since it is actually something I added based on user feedback.

**Closed by dbaeumer** 2019-12-03 14:11 UTC

**Comment by isidorn** [comment] 2019-12-03 14:15
Ok, this makes sense to make it easier for the rules to be discovered.
I was not seeing any value in showing it, thus I complained, but I was wrong.
I do not think this shuold be configurable unless more users complain.
