### ISSUE TITLE
Does commands.executeCommands('editor.action.format') work properly?

### ISSUE THREAD

**Issue by Agetorp** [Microsoft/vscode#967] opened 2015-12-03 14:28 UTC
In an extension, I tried to register an event listener for onDidSaveTextDocument() which would activate the format function, and save the file afterwards.
Using the code:
``` typescript
commands.executeCommands('editor.action.format').then(() => {
 commands.executeCommands('workbench.action.files.save');
});
```

The problem is that the file gets saved, then formatted, but not saved afterwards. Using a timer for a 500ms delay after the format, before the next save, gives the wanted result. 

The function inside of ".then((){   }" should not be called before the file is actually formatted, unless there is something else I don't understand.

**Comment by jrieken** [comment] 2015-12-03 14:43
yeah, we had an issue that made the command promise resolve too early. Closing as duplicate of #617

**Comment by jrieken** [comment] 2015-12-03 14:43
And maybe you want `onWillSaveTextDocument` and a way to add some changes before the actual save happens...

**Closed by jrieken** 2015-12-03 14:43 UTC

**Comment by Agetorp** [comment] 2015-12-03 14:45
Thank you, kind sir!
