### ISSUE TITLE
Typescript editor contents out-of-sync with language service?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10306] opened 2016-08-08 14:31 UTC
I'm afraid this is going to be a terrible bug report because I'm sure I won't be able to reproduce it...

I switched file with Ctrl+Tab, double-clicked on a method name (where it says `trackFile` used to say `updatePriorityFiles`) and re-typed it (I didn't get intellisense so typed manually) then ended up getting weird errors that didn't seem to reflect the code.

![Typescript errors](https://cloud.githubusercontent.com/assets/1078012/17483145/d2419562-5d7c-11e6-85a5-24efca055d45.png)

In this state, everything is broken; errors are all wrong. Pressing Save doesn't fix the issue, nor does closing and re-opening the file. However the "Reload Window" command did fix it.

I don't know if you'll be able to track down the cause from this; but it might be worth considering re-sending the file when re-opening (or even saving) as they're likely the first things a user will try upon seeing this behaviour.

**Comment by dbaeumer** [comment] 2016-08-09 08:06
@DanTup we do have measure to avoid these cases by doing the following:

- if you close the file in the editor its content is reread from disk
- if you open a file we always send the content even if it has been opened/closed before.

So it looks like something else has happened in the language server.

I will keep the issue around to have a place to add additional information.

**Comment by dbaeumer** [comment] 2016-11-15 19:21
I am closing the issue. As commented we do have measure to prevent that. I wasn't able to reproduce and I have no steps.

**Closed by dbaeumer** 2016-11-15 19:21 UTC
Labels: bug, typescript

**Comment by DanTup** [comment] 2016-11-15 20:02
@dbaeumer apologies, I meant to come back to this. I've seen it a few times since (not many, maybe two or three). I think it's always after I change git branch in GitHub Desktop but I've always been in the middle of something so not gone back and retried. I'll do some more testing on Friday and post back if I can get a reliable repro.

**Comment by dbaeumer** [comment] 2016-11-15 21:32
@DanTup Thanks.

**Comment by DanTup** [comment] 2016-11-18 15:52
@dbaeumer I've tried, but I don't seem to be able to repro this doing what I thought I was doing.

I'll keep my eyes open and if it happens again I'll try and do some more debugging and post back.

**Comment by dbaeumer** [comment] 2016-11-18 18:05
Thanks!

**Comment by dbaeumer** [comment] 2016-12-08 15:52
@DanTup I found a problem in the LSP node client implementation that might have caused this (especially when running refactoring like rename). I fixed it in the latest version which is 3.0.1-alpha.12 available under the latest tag. I plan to deliver the new version end of next week to latest.

**Comment by DanTup** [comment] 2016-12-08 17:57
Thanks for the info! I will ofcourse try and do some debugging and post back if I do encounter it again.
