### ISSUE TITLE
add setting import and export feature

### ISSUE THREAD

**Issue by wzengguang** [Microsoft/vscode#33260] opened 2017-08-28 13:56 UTC
hello:
     Can vsCode add a feature than let me export vsCode Settings and extensions, that when I use another computer , I can import settings from original export.
     Or can vsCode support account login, save settings and extensions in account . When I use another computer , I can login my account , sync setting from clound.
thanks.

**Comment by Tyriar** [comment] 2017-08-28 14:52
Duplicate of https://github.com/Microsoft/vscode/issues/2743

In the meantime there is this extension https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Closed by Tyriar** 2017-08-28 14:52 UTC
Labels: workbench
