### ISSUE TITLE
Fatal Error in TS Server: Debug Failure - Script Kind Mismatch: Expected ScriptKind 4, but found ScriptKind 3 in sourceFile.scriptKind. Entry Point Flag: false

### ISSUE THREAD

**Issue by jurnalanas** [microsoft/vscode#182708] opened 2023-05-17 03:41 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230509

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:4 and sourceFile.scriptKind: 3, !entry: false
    at getDocumentRegistryEntry (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133014:11)
    at Object.releaseDocumentWithKey (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133111:19)
    at getOrCreateSourceFileByPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141789:30)
    at Object.getOrCreateSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141773:14)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141705:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117879:24)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120247:23)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120167:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120116:22
    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120100:69)
    at processSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120114:5)
    at processRootFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119911:5)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:41
    at forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:5)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141729:15)
    at Object.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141801:5)
    at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174359:41)
    at InferredProject2.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174211:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176601:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178219:12)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:64
    at flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:24)
    at updateOpen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179629:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182193:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182243:51)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (9084e081d4e89ed8ab67fce340d573c4e1378939, 2023-05-15T05:24:19.845Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 33d368d1-8bcb-40c7-9e6d-9ea7faa66061|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (112)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-devdocs|akf|1.0.3
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
vscode-sqlite|ale|0.14.1
jest-snippets|and|1.9.1
vscode-color|ans|0.4.5
html-end-tag-labels|ant|0.11.0
slidev|ant|0.4.2
emojisense|bie|0.9.1
markdown-emoji|bie|0.3.0
vscode-multi-line-tricks|big|0.0.3
vscode-styled-jsx|bla|2.1.1
vscode-tailwindcss|bra|0.9.11
better-toml|bun|0.3.2
vs-code-can-do-that|bur|0.0.7
turbo-console-log|Cha|2.9.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.5.1
indent4to2|Com|0.1.2
postcss|css|1.0.9
vscode-eslint|dba|2.4.0
dendron-markdown-shortcuts|den|0.12.1
vscode-new-file|dku|4.0.2
quicktype-refresh|dog|1.0.2
xml|Dot|2.5.1
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
copy-relative-path|eno|0.1.1
prettier-vscode|esb|9.12.0
vscode-jest-runner|fir|0.4.60
vscode-monorepo-workspace|fol|1.3.1
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot-chat|Git|0.1.2023051601
copilot-nightly|Git|1.86.92
vscode-pull-request-github|Git|0.64.0
go|gol|0.38.0
gc-excelviewer|Gra|4.2.57
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
svgeditor|hen|2.9.0
vscode-settings-cycler|hoo|1.0.1
vscode-react-typescript|inf|1.3.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
snipped|jef|1.3.0
vscode-insertdatestring|jsy|2.3.1
better-line-select|kai|1.1.1
comment|kar|23.0.0
auto-comment-blocks|kev|1.0.1
inline-parameters|lia|0.2.1
regexp-preview|Lou|0.1.5
tailwind-sass-syntax|mac|1.3.0
json-to-ts|Mar|1.7.5
file-ops|meh|2.0.1
vscode-language-babel|mgm|0.0.39
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-azureresourcegroups|ms-|0.7.3
vscode-docker|ms-|1.25.1
playwright|ms-|1.0.11
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.1
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.293.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
azure-account|ms-|0.11.5
live-server|ms-|0.4.8
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
vscode-print|pdc|0.11.3
vscode-versionlens|pfl|1.5.0
markdown-checkbox|PKi|1.9.0
material-icon-theme|PKi|4.27.0
polacode|pnp|0.3.4
prisma|Pri|4.14.0
quicktype|qui|12.0.46
ruby|reb|0.28.1
vscode-yaml|red|1.12.2
bulma-css-class-completion|rel|0.3.2
vscode-open|san|0.1.0
vscode-javascript-booster|sbu|14.0.1
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.10.1
stately-vscode|sta|1.14.3
vscode-stylelint|sty|1.2.4
language-stylus|sys|1.16.0
vscode-markdown-paste-image|tel|1.0.0
vscode-status-bar-format-toggle|tom|3.1.1
lorem-ipsum|Tyr|1.3.1
altitude-script-language|uca|0.0.3
vscode-mdx|uni|1.3.0
errorlens|use|3.11.0
highlight-matching-tag|vin|0.11.0
vim|vsc|1.25.2
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.5.1

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
f08j5886:30680471
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-17 22:03
Duplicate of #182526

**Closed by mjbvz** 2023-05-17 22:03 UTC
