### ISSUE TITLE
showInputBox should allow to change contents based on input

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3579] opened 2016-03-01 11:42 UTC
`vscode.window.showInputBox()` lets me accept user input through the command palette, but it is a two step process.  I have to first execute a command and then i have to show the input box.  Ideally, I should be able to prompt and accept input in one command, much in the way the git branch prompt does:
 
![image](https://cloud.githubusercontent.com/assets/1487073/13425898/37f9eae0-dfaa-11e5-920f-07caf0807a4d.png)

here i'm prompted with "git checkout", if i have a set of branches they are shown in the list, and I can free form type in any text in order to create a new branch.  

As an extension author I would love to be able to have a similar model. For example, let's say I want to have a list of tasks and each task can take a parameter.  

myextension create thing1
myextension create thing2

in this case i don't want to select "myextension create thing1" and then have an input box.  What i want is to be able to say "myextension thing1 thing1's description".  This is also similar to the extension install experience where i can say `ext install myextension` where `myextension` is free form text.

**Comment by jrieken** [comment] 2016-04-29 10:38
duplicate of #426

**Closed by jrieken** 2016-04-29 10:38 UTC
Labels: api, feature-request
