### ISSUE TITLE
Fix menu position while right click on folder with subfolder

### ISSUE THREAD

**Issue by volovodenko** [microsoft/vscode#117964] opened 2021-03-02 11:07 UTC
When I do right click on folder with subfolder, menu appears in wrong place, and random menu position accidentally click. To avoid this i need to press and hold right button. Please fix it.

https://user-images.githubusercontent.com/29176940/109639679-2602fa80-7b58-11eb-9559-e3665c63533c.mp4

**Comment by IllusionMH** [comment] 2021-03-02 11:25
/needsMoreInfo

Please provide info required by template which includes OS and VSCode versions.

Also please check if it's still reproducible in VS Code Insiders builds https://code.visualstudio.com/insiders/
Insiders (but on Windows) opens to side, not under the cursor for me.

**Comment by volovodenko** [comment] 2021-03-02 11:39
Operating System: Linux Mint 20.1
Kernel: Linux 5.4.0-66-generic
Architecture: x86-64

VSCode version: 
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-66-generic


It doesn'e reproducible in VS Code Insiders.

**Comment by volovodenko** [comment] 2021-03-02 11:43
O...excuse me....I've just seen that it's also reproducible in VS Code Insiders.

**Comment by isidorn** [comment] 2021-03-02 11:45
Looks like custom menus + trees thus moving to @sbatten 
fyi @joaomoreno

**Comment by volovodenko** [comment] 2021-03-02 11:47
https://user-images.githubusercontent.com/29176940/109644156-cb6c9d00-7b5d-11eb-9c6d-d4c023513272.mp4

**Comment by sbatten** [comment] 2021-03-02 16:52
duplicate https://github.com/microsoft/vscode/issues/113175

**Closed by sbatten** 2021-03-02 16:52 UTC
Labels: needs more info
