### ISSUE TITLE
[Feature Request] Access Syntax Tree From Extensions

### ISSUE THREAD

**Issue by yo1dog** [Microsoft/vscode#43147] opened 2018-02-07 23:34 UTC
It would be very powerful if we could access information about the syntax tree from within an extension. For example, the extension could identify variables, strings, operators, references, function calls, etc.

Here's an extension that could toggle the currently hovered string's quote type in JavaScript:

```javascript
const textEditor = vscode.window.activeTextEditor;

if (textEditor.syntaxTree.language !== 'JavaScript') {
  return;
}

const syntaxNode = textEditor.syntaxTree.getNodeAtPosition(textEditor.selection.start);
if (syntaxNode instanceof StringSyntaxNode) {
  const stringSyntaxNode = syntaxNode;
  
  const curQuoteChar = syntaxNode.quoteChar;
  const newQuoteChar = curQuoteChar === `'`? `"` : `'`; // very dumb example
  
  textEditor.edit(textEditorEdit => {
    textEditorEdit.replace(stringSyntaxNode.start, newQuoteChar);
    textEditorEdit.replace(stringSyntaxNode.end, newQuoteChar);
  });
}
```

There are existing extensions to toggle quote type, but they do not work well as they attempt to parse JavaScript syntax to find the string quotes.

**Comment by usernamehw** [comment] 2018-02-07 23:41
Duplicate of https://github.com/Microsoft/vscode/issues/580 ?

**Comment by mjbvz** [comment] 2018-02-08 00:07
Yes, #580 tracks this.

**Closed by mjbvz** 2018-02-08 00:07 UTC
Labels: javascript
