### ISSUE TITLE
Task Runner: Define multiple commands

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4756] opened 2016-03-29 16:22 UTC
- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

I would like to be able to specify multiple commands in a Task Runner. Right now, only one command is supported. Is the best way to do this with a shell script?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Tyriar** [comment] 2016-03-29 16:29
Duplicate of https://github.com/Microsoft/vscode/issues/981

**Closed by Tyriar** 2016-03-29 16:29 UTC
