### ISSUE TITLE
move to new file creates 'export export' at the bottom instead of an import

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode#53976] opened 2018-07-10 16:59 UTC
- VSCode Version: 1.25.0
- OS Version: fedora 28

Steps to Reproduce:

1. select the following javascript code (in my file, here is the whole file https://paste.fedoraproject.org/paste/WjAQLbQw507ngo7gVroYjw) and select  'move to a new file':
```
function keyHandler(event) {
  switch (event.code) {
    case 'ArrowUp':
      if (event.type === 'keydown') {
        frog.move(0, -1);
      }
      break;
    case 'ArrowDown':
      if (event.type === 'keydown') {
        frog.move(0, 1);
      }
      break;
    case 'ArrowLeft':
      event.preventDefault();
      if (event.type === 'keydown') {
        frog.move(-1, 0);
      }
      break;
    case 'ArrowRight':
      event.preventDefault();
      if (event.type === 'keydown') {
        frog.move(1, 0);
      }
      break;
    // no default
  }
}

addEventListener('keydown', keyHandler);
addEventListener('keyup', keyHandler);
```
2. a new file is created, but instead of an import being created at the top, at the bottom of the file we get:

`export export `

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-07-12 00:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/24643

Should be fixed in VS Code insiders

**Closed by mjbvz** 2018-07-12 00:58 UTC
