### ISSUE TITLE
Format forces html span on new line creating an extra space

### ISSUE THREAD

**Issue by KyleStay** [Microsoft/vscode#45825] opened 2018-03-15 04:46 UTC
Issue Type: <b>Bug</b>

Pressing alt+shift+f on an HTML type document with a span next to a single quote forces the span onto a new line.

1. Create a new document
2. Paste in Example text:
```html
<p>Test stuff '<span class="quoted-test-span"></span>'.
</p>
```

3. In lower right, select HTML for the language mode
4. Press alt+shift+f on your keyboard
5. See that span was forced to a new line
6. Notice when the html rendard this creates an extra space between the quotes

Desired solution:
allow spans to not be formatted in this way

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_930019|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by aeschli** [comment] 2018-03-15 10:10
duplicate of #43520

It's a problem with jsbeautify which we use as the underlying formatter.

**Closed by aeschli** 2018-03-15 10:10 UTC
Labels: editor, editor-autoindent

**Comment by KyleStay** [comment] 2018-03-15 12:28
I recommend this user setting as a work around in the mean time: 
```json
{
    "html.format.unformatted": "wbr,span"
}
```
