### ISSUE TITLE
Custom UI for Views Container

### ISSUE THREAD

**Issue by jbaptistegrenouille** [microsoft/vscode#98208] opened 2020-05-19 21:37 UTC
Currently views container only allows to create tree views. It would be good that some other UI elements can be added such as button, text inputs, [dropdown](https://stackoverflow.com/questions/56789726/dropdowns-in-custom-vscode-view-container), among others.

This all can be done in web-views, however some times we don't need full power from web-view but instead it would be highly beneficial to leverage the views container to have all extra inputs.

Some extension follow a hacky approach for buttons which is treating elements from the tree views as buttons. This is some times unintuitive and undesired. Also it doesn't allows to create text boxes.

**Comment by mjbvz** [comment] 2020-05-20 22:55
Duplicate of #46585

**Closed by mjbvz** 2020-05-20 22:55 UTC
