### ISSUE TITLE
TypeScript server crashes on newly created unsaved documents

### ISSUE THREAD

**Issue by fox1t** [microsoft/vscode#92089] opened 2020-03-05 15:19 UTC
Issue Type: <b>Bug</b>

1. Open new document (cmd+n)
2. select TypeScript as language from the language selection selector 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1620916/75995155-4d4ec980-5efc-11ea-81a3-dd48f687dc38.png">
3. it will start to initialize the TS server
<img width="223" alt="image" src="https://user-images.githubusercontent.com/1620916/75995225-68b9d480-5efc-11ea-99de-9b68644f0e55.png">
 
4. after a while it will popup this message: "The TypeScript language service died 5 times right after it got started. The service will no be restarted."
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1620916/75995269-766f5a00-5efc-11ea-9096-87443b6007ed.png">

Clicking on mange extension it brings to "TypeScript and JavaScript Language Features".

Note: if I create a new file save it and then start coding in TS/JS, it works as expected and the server doesn't crash at all.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.0.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
githistory|don|0.6.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.20.0
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.1.0
python|ms-|2020.2.64397
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
sublime-keybindings|ms-|4.0.6
vscode-typescript-tslint-plugin|ms-|1.2.3
color-highlight|nau|2.3.0
advanced-new-file|pat|1.2.0
vscode-yaml|red|0.7.2
rust|rus|0.7.0
final-newline|sam|0.3.2
todotasks|san|0.5.0
crates|ser|0.4.7
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
sort-lines|Tyr|1.9.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-03-05 20:18
duplicate of #85547

**Closed by mjbvz** 2020-03-05 20:18 UTC
