### ISSUE TITLE
Remove white background of the icon

### ISSUE THREAD

**Issue by YLiLarry** [Microsoft/vscode#21509] opened 2017-02-27 17:30 UTC
I sincerely think the icon would look so much better (on osx at least) if the white background is transparent, like this:

![screen shot 2017-02-27 at 12 27 36 pm](https://cloud.githubusercontent.com/assets/8177295/23372155/750cb30c-fce8-11e6-80b9-72128cc86c8f.png)

Currently the two inner triangles are opaque.

**Comment by YLiLarry** [comment] 2017-03-24 18:51
This is the one as the image.
[Code.icns.zip](https://github.com/Microsoft/vscode/files/868886/Code.icns.zip)
Note that for icon smaller than 64x64 (or 32x32) it looks better if the white border is removed completely.

**Comment by hoovercj** [comment] 2017-04-05 15:15
Duplicate of #11274

**Comment by chrisdias** [comment] 2017-07-07 03:54
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607

**Closed by chrisdias** 2017-07-07 03:54 UTC
