### ISSUE TITLE
Broken EH debugging on Windows after window reloads 

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55916] opened 2018-08-06 22:12 UTC
https://github.com/Microsoft/vscode/issues/55911 is for node2 shouldn't support `terminate` on windows. This is for broken EH debugging.

- VSCode Version: Insiders 1.26 dated 6th August, 2018
- OS Version: Windows 10

Steps to Reproduce:

1. Have an extension that opens a folder on command
```
vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse('C:/some-local-path'));
    })
```
2. Debug the extension, run the above command.
3. Close the debugging session, start again

At this point, a new window for extension host is not launched. Clicking the stop button doesnt stop the process either and throws the below error in the debug console

![image](https://user-images.githubusercontent.com/16890566/43739897-75b9723e-997e-11e8-9a52-67d400e684d3.png)

- EH debugging still doesn't work, until I start with a fresh `--user-data-dir`. What could be stored that impacts this?
- Debugging, I see that vscode sends the 'launch' but never sends the 'attach' command which is supposed to come after, I don't know why

**Comment by weinand** [comment] 2018-08-06 23:42
But the „terminate“ request error should no longer happen with your fix for supportTerminateRequest, right?
And this is still a duplicate of 
https://github.com/Microsoft/vscode/issues/55025?

**Comment by roblourens** [comment] 2018-08-06 23:57
The error will go away, but this doesn't just impact the session, like #55025. We can't debug the EH **at all** after this.

**Comment by ramya-rao-a** [comment] 2018-08-08 02:01
On further investigations, Rob and I found that the reason why further EH were not launching new windows was due to https://github.com/Microsoft/vscode/blob/6f3f9edcfa917530562d83bc4744fcdbe9159404/src/vs/code/electron-main/windows.ts#L974

Supporting stack trace:

[main 4:59:47 PM] [ 'TypeError: Cannot read property \'scheme\' of null',
 '    at Object.s [as hasToIgnoreCase] (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:49:835)',
 '    at C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:334:774',
 '    at Array.filter (<anonymous>)',
 '    at Object.t.findWindowOnWorkspaceOrFolderUri (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:334:600)',
 '    at C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:496:683',
 '    at Array.some (<anonymous>)',
 '    at e.openExtensionDevelopmentHostWindow (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:496:656)',
 '    at e.startOpenWindow (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:330:714)',
 '    at e.start (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:330:535)',
 '    at e.call (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:329:72)',
 '    at e.onPromise (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:159:654)',
 '    at e.onMessage (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:159:409)',
 '    at C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:159:201',
 '    at e.fire (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:104:992)',
 '    at a (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:168:685)',
 '    at Socket._socketDataListener (C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\code\\electron-main\\main.js:168:904)',
 '    at emitOne (events.js:116:13)',
 '    at Socket.emit (events.js:211:7)',
 '    at addChunk (_stream_readable.js:263:12)',
 '    at readableAddChunk (_stream_readable.js:250:11)',
 '    at Socket.Readable.push (_stream_readable.js:208:10)',
 '    at Pipe.onread (net.js:594:20)' ]

**Comment by weinand** [comment] 2018-08-08 07:53
@bpasero @jrieken @aeschli any ideas?

**Comment by bpasero** [comment] 2018-08-08 12:49
@roblourens @ramya-rao-a you seem to be using the URI class wrongly, if you have a file path, make sure to use `vscode.Uri.file('C:/some-local-path')`. I cannot reproduce the exception in https://github.com/Microsoft/vscode/issues/55916#issuecomment-411259108 and the opening of the folder works just fine for me.

**Comment by roblourens** [comment] 2018-08-08 14:52
Extensions are apparently doing this because it used to work, see https://github.com/Microsoft/vscode/issues/55891. This is closely related to that issue. No amount of wrong code should break launching the extension dev host entirely.

**Comment by bpasero** [comment] 2018-08-08 14:58
@roblourens I never saw the exception even with the bad usage of URI. Are you saying the window does not open at all, what is the visible impact?

**Comment by kieferrm** [comment] 2018-08-08 16:11
@bpasero 

The steps are as described. 
- be on windows
- have a workspace with an extension open that uses openFolder with URI.parse(filePath)
- debug the extension
- make sure the openFolder code is executed 
- stop debugging
- relaunch 
-> at this moment EH debugging is broken and you can only get to a workable state by patching or changing the user-data-dir

The question is why we need to check the command line args for URI compliance when we launch an EH in development mode? If this code is removed (but the normal CLI check for URI compliance remains) we avoid the problem. See @ramya-rao-a comment: 
https://github.com/Microsoft/vscode/issues/55916#issuecomment-411259108

**Closed** 2018-08-08 16:37 UTC
Labels: bug, candidate, debug, insiders

**Comment by roblourens** [comment] 2018-08-08 16:46
If we just fix the npe, does this work correctly if a window is already open on that folder?

We weren't clear why this check exists or if this is doing the right thing in this case: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L973

**Comment by aeschli** [comment] 2018-08-08 18:52
I pushed one more improvement to #55891. Now also the sample with the windows path works (again).
I verified that @kieferrm [steps](https://github.com/Microsoft/vscode/issues/55916#issuecomment-411462752) work now.
