### ISSUE TITLE
Unclear how to handle errors from `makeChatRequest`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205803] opened 2024-02-21 01:53 UTC
Testing #205568

Make a chat request with a million tokens

**Bug**
I see an internal error from the extension host

<img width="998" alt="Screenshot 2024-02-20 at 5 52 24 PM" src="https://github.com/microsoft/vscode/assets/12821956/977a3cf4-c503-4d72-a035-076f1b27702f">

However neither `request.stream` or `request.value` throw errors

In `request.stream`, I actually get back a nonsense response:

<img width="286" alt="Screenshot 2024-02-20 at 5 53 11 PM" src="https://github.com/microsoft/vscode/assets/12821956/4991140f-0df5-491d-baea-dffc03e1e09b">

**Comment by jrieken** [comment] 2024-02-21 10:33
/duplicate of https://github.com/microsoft/vscode/pull/205849

**Closed** 2024-02-21 10:34 UTC
Labels: lm-access
