### ISSUE TITLE
Build Task detection failure in multi-root workspace

### ISSUE THREAD

**Issue by Borvik** [Microsoft/vscode#60315] opened 2018-10-09 13:05 UTC
- VSCode Version: 1.28.0 and prior
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1.  Add TypeScript Project with defined tasks.json to multi-root workspace
```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "noEmitOnError": true,
    "outDir": "./dist",
    "declaration": true
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*.ts"
  ]
}
```
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "problemMatcher": [
        "$tsc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```
2.  When "Run Build Task" is run the following is seen in the Tasks output window:
```
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "type": "typescript",
    "tsconfig": "tsconfig.json",
    "problemMatcher": [
        "$tsc"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.
```

The same project, when the folder is opened (not in a workspace) - just immediately runs the build task.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Borvik** [comment] 2018-10-09 13:17
Here is a sample project as well.
[SampleTaskBug.zip](https://github.com/Microsoft/vscode/files/2460544/SampleTaskBug.zip)

**Comment by dbaeumer** [comment] 2018-10-16 09:43
Interestingly it works if the project has one workspace folder.

The problem is that the TypeScript extensions scopes the contributed task to the workspace folder and add the workspace folder name to the path of the `tsconfig.json` file. 

@mjbvz since the task is already scoped you shouldn't add the project folder name to the `tsconfig` property value.

The UI also shows the task in the right folder (see ProjectC postfix):

![capture](https://user-images.githubusercontent.com/1931590/47007454-8d12e680-d138-11e8-8106-de8f0df9f7e2.png)

Please assign back when you have done the change that I can validate that everything works as expected. I checked my code paths and they all seem to handle this correctly.

**Comment by mjbvz** [comment] 2018-10-30 00:43
@dbaeumer I have a fix in a branch under cd74cd275ea7b5f11d133edb4a3f124a1a1b65af

However this fix breaks the case where you have two folders with the same name (but different paths) that both contribute tasks in a workspace. I only see one of the folder's tasks showing up.

**Comment by dbaeumer** [comment] 2018-10-30 08:37
I would say that this is a bug in the task land then. We scope them per workspace folder but may be for the naming we only consider the last segment. Let me look into this in November.

**Comment by mjbvz** [comment] 2018-11-12 23:01
I've cherry-picked cd74cd275ea7b5f11d133edb4a3f124a1a1b65af to master 

@dbaeumer Please look into the same name issue

**Comment by dbaeumer** [comment] 2018-11-13 09:43
Will do but has to wait until next week.

@alexr00 do you want to give this a try. Will expose you to multi root workspace and all the fun with tasks in that setup :-)

**Comment by dbaeumer** [comment] 2018-12-05 16:52
I retested this and both tasks show up although with the same name. Executing one always executes the right one

![capture](https://user-images.githubusercontent.com/1931590/49529039-804b7d00-f8b5-11e8-842c-4df2bd7a2d85.png)

The debug drop down has the same problem. 

![capture](https://user-images.githubusercontent.com/1931590/49529223-da4c4280-f8b5-11e8-8ce1-c0cd49addf7e.png)

Even the workspace fails:

![capture](https://user-images.githubusercontent.com/1931590/49529361-21d2ce80-f8b6-11e8-97af-ab4a9206ed79.png)

So I will close the issue. If we think that we should be better with these names sense we need an effort in the workspace (@bpasero)

**Closed by dbaeumer** 2018-12-05 16:52 UTC
Labels: bug, tasks, typescript

**Comment by dbaeumer** [comment] 2018-12-05 16:55
Assigning back to TS since nothing got fixed in Task land for this.
