### ISSUE TITLE
Integrated terminal converts tab characters to spaces

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29523] opened 2017-06-27 05:42 UTC
Integrated terminal - spaces:

```
$ node -e "console.log('foo\tbar')"
foo     bar
```

iTerm2 - tab:

```
$ node -e "console.log('foo\tbar')"
foo	bar
```

**Comment by Tyriar** [comment] 2017-06-27 17:30
Tabs like this also work in gnome-terminal and Terminal.app.

**Comment by Tyriar** [comment] 2017-06-27 17:33
Upstream issue: https://github.com/sourcelair/xterm.js/issues/734

**Comment by Tyriar** [comment] 2017-12-23 00:48
I'm going to close this off as designed because tab is not a printable character in a terminal but rather repositions in the cursor, see https://github.com/xtermjs/xterm.js/issues/734#issuecomment-347506518

**Closed by Tyriar** 2017-12-23 00:48 UTC
Labels: feature-request, integrated-terminal, upstream

**Comment by abimelex** [comment] 2018-01-09 10:21
Is there any workaround for this? For me it's sometimes essential to copy/paste terminal output to numbers. I would like to avoid to the detour over csv files...

**Comment by Tyriar** [comment] 2018-01-09 14:26
@abimelex no workaround, the only fix is to proceed with https://github.com/xtermjs/xterm.js/issues/734. I doubt I'll have time to work on it any time soon though.
