### ISSUE TITLE
Markdown preview doesn't fill editor 

### ISSUE THREAD

**Issue by SidIcarus** [Microsoft/vscode#19745] opened 2017-02-02 20:58 UTC
- VSCode Version: 1.9.0
- OS Version: MacOS Sierra 10.12.1
  - 15.4" (2880x1800)

Steps to Reproduce:
1. Open Markdown Preview (or Release Notes/Extension)

Notes: 
- Relative amount of space it doesn't fill in
- Unaffected by anything other state of the app (other files open, split editor, panel open, resolution of monitor, etc.)
- Noticed in previous two versions of vscode
- The `<object></object>` fills in completely but its embedded content does not.

When I read over the release notes I noticed the gif of the markdown synch had the preview fill entire screen and realized it's been not completely filled on mine since I started using it. whoops ¯\_(ツ)_/¯ 

![screen shot 2017-02-02 at 03 49 56 pm 3](https://cloud.githubusercontent.com/assets/3842798/22567793/578c7354-e95f-11e6-8966-f67358424fd4.png)
![screen shot 2017-02-02 at 03 49 56 pm 2](https://cloud.githubusercontent.com/assets/3842798/22567794/57983518-e95f-11e6-89a0-5a4512b3d57e.png)

**Comment by mjbvz** [comment] 2017-02-02 22:25
I believe the exception is caused by a bad link reference in the markdown file.  #19417 may have fixed this by upgrading markdown it, and #19411 also added some error handling for exceptions in markdown it. Both of those changes are in the next vscode insiders build

As for the content sizing issue, I believe this is a duplicate of #5745. I've looked into the issue in the past, but was not able to find a solution. I'll try revisiting this sometime since this bug is a continual source of annoyance.

**Closed by mjbvz** 2017-02-02 22:25 UTC
Labels: bug, duplicate, markdown

**Comment by SidIcarus** [comment] 2017-02-03 15:14
I downloaded the insider preview and the content sizing issue is fixed in that. 👍 
The bad link exception currently occurs for opening the 1.10 insider release notes but as you've linked, that is for another issue.
