### ISSUE TITLE
can not open vscode in the background when using vscode in WSL2

### ISSUE THREAD

**Issue by IsaacLiuu** [microsoft/vscode#193321] opened 2023-09-18 01:00 UTC
Does this issue occur when all extensions are disabled?: Yes/No
unknown, I need extensions such as ssh to open vscode in windows.

- VS Code Version: code 1.82.2
- OS Version:
-  WSL Version： 1.2.5.0
Core Version： 5.15.90.1
WSLg Version： 1.0.51
MSRDC Version： 1.2.3770
Direct3D Version： 1.608.2-61064218
DXCore Version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version： 10.0.22621.2283

Steps to Reproduce:

1. type "code ." in wsl terminal and press enter
2. you will find vscode is open but there is no new line in terminal
![vscode](https://github.com/microsoft/vscode/assets/134244468/c26836a3-a139-491f-870a-b88d4f24351f)

**Comment by yishiashia** [comment] 2023-09-18 02:26
Facing same issue with WSL2 + VS Code version 1.82.2

**Comment by yongzhang** [comment] 2023-09-18 07:25
Having the same issue today.

**Comment by wtfzambo** [comment] 2023-09-20 14:35
Same issue here. Version 1.82.1 works fine.

**Comment by aeschli** [comment] 2023-09-21 21:08
Duplicate of #193453

**Closed by aeschli** 2023-09-21 21:08 UTC
Labels: triage-needed
