### ISSUE TITLE
Add support to display images in the code editor

### ISSUE THREAD

**Issue by ikzk** [Microsoft/vscode#28083] opened 2017-06-06 04:08 UTC
It is very good to have this feature. It is a must to implement things like:

![](https://cloud.githubusercontent.com/assets/12573621/17191378/062d4a38-544a-11e6-8b17-b5bf92b8c78f.png)

![](https://cloud.githubusercontent.com/assets/163428/21752878/a87c13ba-d5e0-11e6-8a3b-1fb60a06fa4d.png)

![](https://cdn-business.discourse.org/uploads/github_atom/original/3X/7/5/75463ae9d1ef0c6e93e3a61118e1266236192374.png)

#3220 can be another way to achieve similar effects, but it seems that there is no update for that?

**Comment by jrieken** [comment] 2017-06-06 08:55
dupe of #3220

**Closed by jrieken** 2017-06-06 08:55 UTC
Labels: feature-request
