### ISSUE TITLE
debugging extension stuck on building

### ISSUE THREAD

**Issue by Itsamirmasoud** [microsoft/vscode#112534] opened 2020-12-15 08:43 UTC
- VSCode Version: 1.52.0
- OS Version: Windows 10 Pro Build 2004

Steps to Reproduce:

1. follow the steps of creating your first extension [here](https://code.visualstudio.com/api/get-started/your-first-extension)
2. hit F5
3. "Building..." appear in the status bar and never stops...never finishes and nothing happens.

Does this issue occur when all extensions are disabled?: Yes

there is only two line outputted in the terminal :  
Starting compilation in watch mode...
Found 0 errors. Watching for file changes.

**Comment by weinand** [comment] 2020-12-15 09:19
What options did you select when running "yo code"?
E.g. npm, yarn, webpack?

**Comment by isidorn** [comment] 2020-12-15 09:39
@Itsamirmasoud I just tried this and it works just fine for me. If you could answer @weinand questions it would be great
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
I suppose you are using a Typescript extension?

**Comment by Itsamirmasoud** [comment] 2020-12-15 10:25
@weinand @isidorn 
thanks for helping and yes i am using Typescript template with npm and no webpack. almost everything was set to default

**Comment by isidorn** [comment] 2020-12-15 11:10
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by Itsamirmasoud** [comment] 2020-12-15 11:53
> Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> also fyi @alexr00 for ideas since it sounds like the `preLaunchTask` is forever spinning

I tried running the same project with the insider version and faced the same issue. so i created a whole new project in insider and the problem still existed. with following config : 

 What's the identifier of your extension? helloworld
 What's the description of your extension? BLANK
 Initialize a git repository? No
 Bundle the source code with webpack? No
 Which package manager to use? npm

**Comment by alexr00** [comment] 2020-12-15 12:13
All I can think of is that the problem matcher isn't being used.
@Itsamirmasoud did you disable the built in typescript extension (or any other built in extensions)?

**Comment by Itsamirmasoud** [comment] 2020-12-15 12:18
> All I can think of is that the problem matcher isn't being used.
> @Itsamirmasoud did you disable the built in typescript extension (or any other built in extensions)?

nope, none of the built in extensions are disabled.

**Comment by Rolodo** [comment] 2020-12-19 04:52
I'm having the same issue I formated my computer and tryed again still stuck in "Building..."

Same Settings
What's the identifier of your extension? helloworld
What's the description of your extension? BLANK
Initialize a git repository? No
Bundle the source code with webpack? No
Which package manager to use? npm

**Comment by MalcolmMielle** [comment] 2020-12-23 11:32
I have the smae problem with an extension that builds fine on windows but not on linux Fedora33

**Comment by isidorn** [comment] 2021-01-04 11:29
Also assigning to @weinand due to the `inheritEnv` which I know he looked into

**Comment by weinand** [comment] 2021-01-04 11:58
For extension debugging, the debuggee (another instance of VS Code) runs in the debug console and not run in an integrated terminal. So the only integrated terminal being involved here is the one for the build/watch task.

Assigning to @alexr00 because she might know how the "inheritEnv" setting affects the build task.

**Comment by alexr00** [comment] 2021-01-05 09:58
@Itsamirmasoud do you have `terminal.integrated.inheritEnv` set?

That setting can affect tasks because tasks often expect to be able to find things on the path (like `npm`) and that setting will often break that.

**Closed** 2021-01-12 11:55 UTC
Labels: debug, needs more info
