### ISSUE TITLE
Retain terminal splits during window reload

### ISSUE THREAD

**Issue by mke-xena** [microsoft/vscode#111872] opened 2020-12-04 08:49 UTC
I often have multiple Terminal splits going at the same time: One for a server, one for a client, one for general messing around, laid out side-by-side:

![image](https://user-images.githubusercontent.com/70580121/101142436-e0e13200-3615-11eb-9a89-44a1d7502519.png)

It works well for my purposes, but whenever I have to reload the window (e.g. loss of SSH to remote system when using the Remote features, or due to an extension updating) then my terminal layout is lost. I still have the Server, Client and General terminals, but they're no longer in a split view. And as far as I can tell there's no way to re-introduce the splits with the existing terminals.

![image](https://user-images.githubusercontent.com/70580121/101142507-fbb3a680-3615-11eb-86a5-3977a114ea0f.png)

My request: Maintain the splits during window reload.

**Comment by meganrogge** [comment] 2020-12-04 18:21
@mke-xena this is a goal for our next iteration, so coming soon! /duplicate 
Duplicate of #109244

**Closed** 2020-12-04 18:22 UTC
Labels: feature-request, integrated-terminal
