### ISSUE TITLE
explorer.autoReveal can produce a pointless stat call

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#79047] opened 2019-08-13 14:55 UTC
Issue Type: <b>Bug</b>

Assume `explorer.autoReveal: true`

If a FileSystemProvider extension implements more than one scheme, and if a file is opened using a scheme that is not used by the root folder(s) of the workspace, then when focus is switched to that file a `stat()` call is issued on a folder resource that cannot possibly contain the file resource (because the scheme is different).

In some scenarios a stat() call on a root folder can be costly, meaning it is important not to do it unnecessarily.

This is not a new 1.37 issue.

I will add information about how to demonstrate the issue using a variant of fsprovider-sample, and I am also willing to supply a PR to fix it.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment] 2019-08-13 15:38
Steps to reproduce:

Use 1.38.0-insider, or a 1.37 build that contains the fix for #78961 

1. Download branch at https://github.com/gjsjohnmurray/vscode-extension-samples/tree/autoReveal-and-stat
2. Open fsprovider-sample in VS Code
3. Add a logpoint in the stat() method of src/fileSystemProvider.ts (line 58) with the following message:

`stat of {uri.toString()}`

4. Check that `explorer.autoReveal: true`
5. Run the 'Launch Extension' debug configuration.
6. When the Extension Development Host window appears, run the following commands in it:

- MemFS: Setup Workspace
- MemFS: Add Second Root
- MemFS: Create Files

7. Go to Explorer view.
8. Doubleclick on file2.txt under the second root (MemFS2 - Different Scheme)
9. Under the first root doubleclick on at least two files.
10. On the Debug Console of your initial VS Code instance, observe the stat messages as you switch between file tabs on the EDH, e.g.
```
stat of memfs:/file.html
stat of memfs:/file.py
stat of memfs2:/file2.txt
stat of memfs:/file.html
```
11. Use context menu of second root (MemFS2) to Remove Folder from Workspace.
12. Click between tabs of the files and observe how when you click on the file2.txt opened from memfs2 there is an additional stat of the first root (memfs)
```
stat of memfs:/file.html
stat of memfs:/file.py
stat of memfs2:/file2.txt
stat of memfs:/
```

**Comment by isidorn** [comment] 2019-08-14 14:41
Fixed via https://github.com/microsoft/vscode/pull/79052
@gjsjohnmurray can you just let us know tomorrow once the new insiders is out if the issue is indeed fixed for you. Thank you

**Closed** 2019-08-14 14:41 UTC
Labels: bug, file-explorer

**Comment by gjsjohnmurray** [comment] 2019-08-15 09:36
@isidorn confirmed good in today's Insider. Thanks!

**Comment by isidorn** [comment] 2019-08-15 09:38
Thanks, adding verified label.
