### ISSUE TITLE
Endless TypeScript language extension crash

### ISSUE THREAD

**Issue by Paril** [microsoft/vscode#173644] opened 2023-02-07 04:55 UTC
Type: <b>Bug</b>

Just by opening any JS/TS file.

VS Code version: Code - Insiders 1.76.0-insider (c9e3ef865539061b5602c6b9ac6030332aa1ce70, 2023-02-06T05:24:33.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.91GB (32.59GB free)|
|Process Argv|--crash-reporter-id be941164-3c0c-4773-b7d4-a6d544f0a97c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.0
vscode-wasm|dts|1.4.0
phpcs|ika|1.0.5
latte|Kas|0.18.0
vscode-less|mrm|0.6.3
csharp|ms-|1.25.4
cpptools|ms-|1.14.1
powershell-preview|ms-|2023.2.0
phpstan|par|1.4.5
better-less|rad|0.5.0
shader|sle|1.1.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
php-debug|xde|1.31.0
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
hidelangstatbar:30657380

```

</details>

**Comment by mjbvz** [comment] 2023-02-07 19:24
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Paril** [comment] 2023-02-08 01:14
Disabling the TypeScript/JS Language extension resolves it; it seems to be limited to that. There doesn't appear to be any information in the Output < TypeScript extension host window, just that it keeps initializing every second and then exiting.

**Comment by mjbvz** [comment] 2023-02-08 01:22
I notice `vsintellicode/typescript-intellicode-plugin`  in the logs. Does this still happen if you disable the VS Code IntelliCode extension and restart VS Code?

**Comment by Paril** [comment] 2023-02-08 01:51
I can't find that extension in my Extensions List; I only see VisualStudioExptTeam.vscodeintellicode and VisualStudioExptTeam.intellicode-api-usage-examples.

If I disable "IntelliCode", the error changes slightly:

![](https://i.imgur.com/3b1Mfuw.png)

```
[Trace - 01:50:49.9] <semantic> Sending request: compilerOptionsForInferredProjects (1). Response expected: no. Current queue length: 0
Arguments: {
    "options": {
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "ES2020",
        "jsx": "react",
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "sourceMap": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "resolveJsonModule": true
    }
}
[Error - 01:50:49.269] TSServer exited. Code: 1. Signal: null
[Info - 01:50:49.269] Starting TS Server
[Info - 01:50:49.269] Using tsserver from: c:\Users\Paril\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info - 01:50:49.269] <syntax> Trace directory: file:///c%3A/Users/Paril/AppData/Roaming/Code%20-%20Insiders/logs/20230207T205042/window1/exthost/vscode.typescript-language-features/tsserver-log-XhXiZZ
[Info - 01:50:49.269] <syntax> Forking...
[Info - 01:50:49.275] <syntax> Starting...
[Info - 01:50:49.276] <semantic> Trace directory: file:///c%3A/Users/Paril/AppData/Roaming/Code%20-%20Insiders/logs/20230207T205042/window1/exthost/vscode.typescript-language-features/tsserver-log-2MbY3q
[Info - 01:50:49.276] <semantic> Forking...
[Info - 01:50:49.282] <semantic> Starting...
[Trace - 01:50:49.282] <syntax> Sending request: configure (0). Response expected: no. Current queue length: 0
Arguments: {
    "hostInfo": "vscode",
    "preferences": {
        "providePrefixAndSuffixTextForRename": true,
        "allowRenameOfImportPath": true,
        "includePackageJsonAutoImports": "auto"
    },
    "watchOptions": {}
}
[Trace - 01:50:49.282] <semantic> Sending request: configure (0). Response expected: no. Current queue length: 0
Arguments: {
    "hostInfo": "vscode",
    "preferences": {
        "providePrefixAndSuffixTextForRename": true,
        "allowRenameOfImportPath": true,
        "includePackageJsonAutoImports": "auto"
    },
    "watchOptions": {}
}
[Trace - 01:50:49.282] <semantic> Sending request: compilerOptionsForInferredProjects (1). Response expected: no. Current queue length: 0
Arguments: {
    "options": {
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "ES2020",
        "jsx": "react",
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "sourceMap": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "resolveJsonModule": true
    }
}
[Error - 01:50:49.498] TSServer exited. Code: 1. Signal: null
[Info - 01:50:49.499] Starting TS Server
[Info - 01:50:49.499] Using tsserver from: c:\Users\Paril\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info - 01:50:49.499] <syntax> Trace directory: file:///c%3A/Users/Paril/AppData/Roaming/Code%20-%20Insiders/logs/20230207T205042/window1/exthost/vscode.typescript-language-features/tsserver-log-RVhSol
[Info - 01:50:49.499] <syntax> Forking...
[Info - 01:50:49.506] <syntax> Starting...
[Info - 01:50:49.506] <semantic> Trace directory: file:///c%3A/Users/Paril/AppData/Roaming/Code%20-%20Insiders/logs/20230207T205042/window1/exthost/vscode.typescript-language-features/tsserver-log-IPf6Ql
[Info - 01:50:49.506] <semantic> Forking...
[Info - 01:50:49.514] <semantic> Starting...
[Trace - 01:50:49.515] <syntax> Sending request: configure (0). Response expected: no. Current queue length: 0
Arguments: {
    "hostInfo": "vscode",
    "preferences": {
        "providePrefixAndSuffixTextForRename": true,
        "allowRenameOfImportPath": true,
        "includePackageJsonAutoImports": "auto"
    },
    "watchOptions": {}
}
[Trace - 01:50:49.515] <semantic> Sending request: configure (0). Response expected: no. Current queue length: 0
Arguments: {
    "hostInfo": "vscode",
    "preferences": {
        "providePrefixAndSuffixTextForRename": true,
        "allowRenameOfImportPath": true,
        "includePackageJsonAutoImports": "auto"
    },
    "watchOptions": {}
}
[Trace - 01:50:49.515] <semantic> Sending request: compilerOptionsForInferredProjects (1). Response expected: no. Current queue length: 0
Arguments: {
    "options": {
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "ES2020",
        "jsx": "react",
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "sourceMap": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "resolveJsonModule": true
    }
}
[Error - 01:50:49.736] TSServer exited. Code: 1. Signal: null
[Info - 01:50:49.736] Starting TS Server```

**Comment by mjbvz** [comment] 2023-02-08 18:36
Thanks. Based on the logs this looks like a known issue on windows. Workaround is to disable `typescript.tsserver.enableTracing`  (there's no real reason to keep it on unless you are investigating performance issues with the TypeScript server)

Duplicate of https://github.com/microsoft/vscode/issues/173854

**Closed by mjbvz** 2023-02-08 18:36 UTC
Labels: info-needed
