### ISSUE TITLE
Process explorer hovered item loses visual feedback periodically

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115227] opened 2021-01-27 14:16 UTC
This is https://github.com/microsoft/vscode/issues/104013 again, just not as bad because at least scroll is stable now.

![recording (53)](https://user-images.githubusercontent.com/2193314/106003370-ff3c3a80-6066-11eb-8b55-f0929ce40729.gif)

**Comment by joyceerhl** [comment] 2022-12-13 16:38
I'm unable to reproduce this in current Insiders so closing as not reproducible.

**Closed by joyceerhl** 2022-12-13 16:38 UTC
Labels: bug, workbench-diagnostics
