### ISSUE TITLE
One of the lines is missing after the formatter is applied on save

### ISSUE THREAD

**Issue by chandu2chandu1** [microsoft/vscode#92827] opened 2020-03-17 07:11 UTC
Just wrote the find function on typescript and the vs code formatted my code automatically and split into multiple lines.  The bold line is not displayed in VS Code and that line number was also not shown.  

VS Code shown as, 
               x =>
                  x.id ==
                  **My Missing Code**
              ),
This line gets shown only after closing and opening the file.  After I save this line goes missing again, but it is not deleted.

**Comment by gjsjohnmurray** [comment] 2020-03-17 07:20
Does this reproduce if you reload with all extensions disabled? There is a command for doing that.

If yes, please post simplest exact code to paste into an untitled document (what language?) that will be corrupted after save.

**Comment by chandu2chandu1** [comment] 2020-03-19 06:01
Hello John,

This issue is not reproduced when I disabled all the extensions.  The code
is not really corrupted, instead it just removed a line displayed as I
noticed. I can see a missing line number in VS Code editor.  This happened
on with typescript code.

Thanks & Regards,
Chandra Sekhar S

**Comment by gjsjohnmurray** [comment] 2020-03-19 06:09
@chandu2chandu1 I suggest you disable extensions methodically (e.g. bisecting) until you discover which one is causing the issue. Then log it on the repo of that extension.

**Comment by aeschli** [comment] 2020-03-22 14:10
Closing the issue as it is caused by an extension.
If you find the problematic extension, please file an issue against the extension's issue tracking system.

**Closed by aeschli** 2020-03-22 14:10 UTC
Labels: needs more info
