### ISSUE TITLE
CSS code in <style> tag is not working

### ISSUE THREAD

**Issue by khunglongxanh9999** [microsoft/vscode#84900] opened 2019-11-15 08:37 UTC
Issue Type: <b>Bug</b>

https://prnt.sc/px9mga
Hi there
Please check this out because I believe that there's some issues with the latest version of VS
Thank you

VS Code version: Code - Insiders 1.41.0-insider (eccf417b72fc0a632ec2cbd7855a681cdb8c81fa, 2019-11-14T09:50:04.822Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.94GB (0.53GB free)|
|Process Argv|C:\Users\Viet Anh\Desktop\Hdashboard.html|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
LiveServer|rit|5.6.1

</details>

**Comment by alexandrudima** [comment] 2019-11-20 11:53
Duplicate of #84401

**Closed by alexandrudima** 2019-11-20 11:53 UTC
Labels: tokenization
