### ISSUE TITLE
terminal bug

### ISSUE THREAD

**Issue by qctxzwq** [microsoft/vscode#117531] opened 2021-02-24 02:12 UTC
Chinese symbol sticky keyboard
![image](https://user-images.githubusercontent.com/46992318/108935420-a02f0d00-7688-11eb-80d3-c896f8967fbb.png)

**Comment by qctxzwq** [comment] 2021-02-24 02:13
Chinese symbol sticky keyboard

**Comment by rzhao271** [comment] 2021-02-24 17:52
Not sure if duplicate of #115814, assigning to @Tyriar

**Comment by Tyriar** [comment] 2021-02-24 19:13
Closing as dupe, if it's not there isn't enough information in the report to know.

**Closed by Tyriar** 2021-02-24 19:13 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
