### ISSUE TITLE
When `Experimental Edit Context Enabled` is enabled and Copilot Chat has been opened, closed and opened again then it's impossible to paste text to some fields

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#231931] opened 2024-10-22 11:18 UTC
Does this issue occur when all extensions are disabled?: I'm not sure, but seems to be related to Copilot Chat extension

- VS Code Version: 1.95.0-insider
```
Version: 1.95.0-insider (user setup)
Commit: defe52dc43e6f5d861f55600ff01f7553fac7eaf
Date: 2024-10-22T05:04:01.628Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Windows_NT x64 10.0.26100
```
- OS Version: Windows 11

Steps to Reproduce:

1. Install GitHub Copilot extension
2. In Visual Studio Code enable `Editor: Experimental Edit Context Enabled`
`editor.experimentalEditContextEnabled`
3. Restart VS Code or use `Reload Window` command
4. Open new file, type something like `test` and copy it
5. Open Copilot Chat (click on the icon on the sidebar)
6. Close chat (click on the icon on the sidebar)
7. Open Copilot Chat again (click on the icon on the sidebar)
8. Now in the text are, use search (<kbd>Ctrl</kbd>+<kbd>F</kbd>)
9. Try to paste copied text to search field (by using <kbd>Ctrl</kbd>+<kbd>V</kbd>)
10. Nothing happens

The same problem with other shortcuts <kbd>Ctrl</kbd>+<kbd>C</kbd>, <kbd>Ctrl</kbd>+<kbd>A</kbd>.

https://github.com/user-attachments/assets/cb630fe1-03d4-4b45-81aa-668df0376b3c

**Comment by aiday-mar** [comment] 2024-10-29 11:44
Hi thanks for filing this issue. This is a duplicate of the issue https://github.com/microsoft/vscode/issues/231082 and should be fixed with https://github.com/microsoft/vscode/pull/232479

**Closed by aiday-mar** 2024-10-29 11:44 UTC
Labels: bug, editor-edit-context
