### ISSUE TITLE
some files cannot be opened from pending changes

### ISSUE THREAD

**Issue by artin-phares** [Microsoft/vscode#36556] opened 2017-10-19 12:59 UTC
- VSCode Version: 1.17.1
- OS Version: window 7

Steps to Reproduce:

1. Upload some files to `git`
2. Change them and try to see those changes from `Source Control - pending changes` tab

Some files cannot be opened, just ignored to open with left click or right click `Open Changes`.  

- can't say exactly what blocks them from opening. see no correlation in extension/previous contents/change/etc. Some files just cannot be opened. Have feeling it happens with 'index.js' files only, but not sure. [update: nope, experiencing same issue with other '.js' files too]

- issue gets fixed after vs code reload.

demo:  

![gif](https://user-images.githubusercontent.com/671082/31771834-327f4246-b4e6-11e7-938b-6fdd502c0f71.gif)

**Comment by rnemec** [comment] 2017-10-20 14:40
This is really unpleasant. Any known workarounds?

**Comment by artin-phares** [comment] 2017-10-21 10:07
@rnemec I'm restarting vs code as workaround

**Comment by rnemec** [comment] 2017-10-21 14:56
Good old command-line resurrected: `git difftool -d` 😉

**Comment by joaomoreno** [comment] 2017-11-02 09:25
This seems very hard for me to reproduce. It's very possible that https://github.com/Microsoft/vscode/commit/9e9f809fc0d43f4b5079eaeb37cd8a986cce14e4 fixed it. But not sure...

I'l close it for now. Please give Insiders or the November stable (coming out next week) a try and let me know if you still see the issue.

**Closed by joaomoreno** 2017-11-02 09:25 UTC
Labels: bug, scm

**Comment by artin-phares** [comment] 2017-12-03 11:46
still reproducible in `v1.18.1`  
still cannot narrow repro, happens randomly :cry:

**Comment by rnemec** [comment] 2017-12-03 16:48
@joaomoreno - I can also confirm in 1.18.1. Please, consider re-opening this one. If there is anything we can do to help you collect some more info, let us know. Since it is not always reproducible, it must be something that we can have configured/turned on for longer time without making the env unusable.

**Comment by joaomoreno** [comment] 2017-12-04 08:02
@artin-phares @rnemec This was fixed in https://github.com/Microsoft/vscode/issues/35724#issuecomment-345265884

**Comment by artin-phares** [comment] 2017-12-04 09:55
@joaomoreno great! waiting for next stable `v1.19.0`

**Comment by rnemec** [comment] 2017-12-04 12:50
Thank you, @joaomoreno !
