### ISSUE TITLE
Filter folders for formatOnSave  

### ISSUE THREAD

**Issue by philipp-spiess** [Microsoft/vscode#25824] opened 2017-05-03 12:32 UTC
We run a bigger project where we've recently added prettier and are using the `formatOnSave` option. However, we don't want to run the formatting process on files that are not part of a few directories.

Is it possible to add another option so I can configure a regex that will be tested against the filename before `formatOnSave` will be triggered? A glob would work as well.

**Comment by sandy081** [comment] 2017-11-20 09:00
To generalise, this is to have file type specific settings. 

Duplicate of #35350

**Closed** 2017-11-20 09:00 UTC
Labels: *duplicate, config, feature-request
