### ISSUE TITLE
js代码无提示，sass变量无提示

### ISSUE THREAD

**Issue by hemocy** [Microsoft/vscode#66643] opened 2019-01-17 03:40 UTC
in my scss，i definde some variables,then i import this scss to another,in that scss ,i can't get variable hinting.
and in my html ,i imported a  file of js with tag script,in tag body i create a tag script to wirte some code;i also can't get code hinting in my javascript;
by the way ,my computer system is win10;
![image](https://user-images.githubusercontent.com/29173748/51294096-6a9cac00-1a4c-11e9-876b-24585d15a0be.png)
in the image,my i definded a variable $fontColor in "var.scss",there is no hinting about it!

**Comment by octref** [comment] 2019-01-17 04:30
Duplicate of #6734

**Closed by octref** 2019-01-17 04:30 UTC
