### ISSUE TITLE
Pressing up/down arrow in SCM input loses any typed content

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109434] opened 2020-10-27 04:10 UTC
Testing #109428

There are a few issues here.

### Issue 1 steps:

1. Enter some text in the SCM input
1. Press the down arrow
1. :bug: any entered text will be lost and replaced by nothing -- and there is no way to get the original text back

In this case, I don't even expect anything to happen, since this is the "most recent" message -- so the down arrow should have no effect.

### Issue 2 steps:

1. Enter some text in the SCM input
1. Press the up arrow
1. :bug: any entered text will be lost and replaced by a previous commit message -- and there is no way to get the original text back

In this case, I should be able to press the down arrow to get my message back. Also, I would expect the up arrow would first move the cursor position to 0,0 before triggering the history. Search behaves this way today -- although only if the search text is multiline (imo it should always be the behavior). 

I was able to get into other states of unexpected behavior, but I think they are just variants of case 1 or 2 above not working correctly and causing other down stream issues.

**Comment by joaomoreno** [comment] 2020-10-27 16:13
@eamodio 

Issue #1 is https://github.com/microsoft/vscode/issues/109443

Issue #2 I can't reproduce, can you try this again?

**Comment by meganrogge** [comment] 2020-10-27 21:04
Duplicate of #109443

**Closed by meganrogge** 2020-10-27 21:04 UTC
Labels: needs more info
