### ISSUE TITLE
Please add the button close Folder and add the Symbol outline 

### ISSUE THREAD

**Issue by quan-tran-niteco** [Microsoft/vscode#34421] opened 2017-09-15 04:16 UTC
1. Please add the button close Folder on the Explorer.
2. Please add the symbol outline beside document map, currently I can see the symbol list by press shortcut key Ctrl + T, but its better if VS Code have the symbol list outline panel always visible as the document map.

**Comment by isidorn** [comment] 2017-09-15 07:50
1. Close folder is coming once we release multi root workspaces, until then it is not possible to close or open folder. You can read more about it in our release notes
2. is duplicate of #5605

**Closed by isidorn** 2017-09-15 07:50 UTC
Labels: workbench
