### ISSUE TITLE
macOS: allow to specify Visual Studio Code as default "open with" application in finder

### ISSUE THREAD

**Issue by eguerin-ucsf** [microsoft/vscode#99473] opened 2020-06-05 17:35 UTC
- VSCode Version:  1.45.1
- OS Version: Mac OS X 10.14.6

Steps to Reproduce:

1.   From the Mac Finder application, choose a file and Get Info on it, such as a .php, or other file type.
2.  From the Get Info window, select Visual Studio Code as the Open With option.  
3.  Choose Change All to make this the default application for all files of type X ( in this case PHP).
4) Right click on the file and confirm the default open with option -  XCode is now selected.  
5) Try another application such as BBEdit, BBEdit will show as the Default.   

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2020-06-06 06:01
I do not have sufficient knowledge to know what is needed for an app to be the default application to "Open with", maybe @deepak1556 or @joaomoreno have an idea.

**Comment by deepak1556** [comment] 2020-06-08 22:26
I am unable to repro this issue on Catalina, we set the `CFBundleTypeExtensions` property on the app to respect the `open with..` context menu https://github.com/microsoft/vscode/blob/master/build/lib/electron.ts#L44-L73 and I see php is already there, so not sure what the issue is here.

**Comment by deepak1556** [comment] 2020-06-09 01:53
Oops, just wanted to tag it, not close the issue.

**Comment by bpasero** [comment] 2020-06-09 06:47
@eguerin-ucsf 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2020-06-16 11:23 UTC
Labels: *not-reproducible, feature-request, mac, needs more info, workbench-os-integration
