### ISSUE TITLE
Broken syntax highlighting for template strings

### ISSUE THREAD

**Issue by eseliger** [Microsoft/vscode#15433] opened 2016-11-13 19:41 UTC
- VSCode Version: 1.7.1

Syntax highlighting is currently broken in template strings in javascript/typescript for Constants and the color for dots (`.`) between `product` and `id`.
![image](https://cloud.githubusercontent.com/assets/19534377/20248305/6875f298-a9e1-11e6-8ab2-e9186d24a5a3.png)

`${API_URL}/somewhat/got/${any.thing}/todo`

**Comment by aeschli** [comment] 2016-11-14 08:14
duplicate of #13166

**Closed by aeschli** 2016-11-14 08:14 UTC
