### ISSUE TITLE
context menu redundant separator

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#17900] opened 2016-12-29 13:12 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  I remember this iusse has fixed ,but now it appears！
2. 
![2016-12-29_211059](https://cloud.githubusercontent.com/assets/8591065/21544597/632fb67c-ce0b-11e6-85f0-faaa493e6f5f.png)

**Comment by rebornix** [comment] 2016-12-29 17:41
@ZCShou can you tell us which version of Code you are using and what platform you are on?

**Comment by ZCShou** [comment] 2016-12-30 00:10
@rebornix 
- VSCode Version: Code - Insiders 1.9.0-insider (58ab5ecdd9e54643e3ae9ae188021844329c0854, 2016-12-28T07:12:03.061Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

---

**Comment by jrieken** [comment] 2016-12-30 09:16
@ZCShou I also need to know if this happens without extensions enabled and in what file type this happens. Thanks

**Comment by ZCShou** [comment] 2017-01-02 10:57
@jrieken I have no extensions
![2017-01-02_185417](https://cloud.githubusercontent.com/assets/8591065/21588007/2bed5542-d11d-11e6-8ff0-6bf9538ecbfe.png)

**Comment by jaseonline** [comment] 2017-01-03 08:57
I can't reproduce this.

**Comment by jrieken** [comment] 2017-01-03 08:57
@ZCShou That's not how you show installed extensions. Erase everything from the input field and see what extensions are listed as installed.

**Comment by ZCShou** [comment] 2017-01-04 01:05
![2017-01-04_090113](https://cloud.githubusercontent.com/assets/8591065/21628711/6921df24-d25c-11e6-914e-ee6026dfc6ee.png)

How do I determine if I have disabled all extensions?

**Comment by jrieken** [comment] 2017-01-04 08:35
There is an action in the `...`-menu. But it seems you have no extensions installed which is strange that you see that extra separator. I have the same setup and don't see that. ![screen shot 2017-01-04 at 09 34 24](https://cloud.githubusercontent.com/assets/1794099/21635985/ff48ab28-d260-11e6-979a-6467ee810218.png)

**Comment by ZCShou** [comment] 2017-01-04 08:48
@jrieken  I update to the latest version, It's OK!  Thanks for your help!

**Comment by jrieken** [comment] 2017-01-04 08:56
Ok. Thanks for getting back. Closing in that case

**Closed by jrieken** 2017-01-04 08:56 UTC
Labels: needs more info
