### ISSUE TITLE
Render math at comment prompts

### ISSUE THREAD

**Issue by Banyc** [microsoft/vscode#153907] opened 2022-07-01 11:50 UTC
# Background

VSCode markdown preview has already supported math syntax. However, math notations are not rendered at comment prompts.

# Context

The demonstration and context are in the following issue:

https://github.com/rust-lang/rust-analyzer/issues/12666

**Comment by mjbvz** [comment] 2022-07-05 15:36
Duplicate of #124784

**Closed by mjbvz** 2022-07-05 15:36 UTC
