### ISSUE TITLE
Remote SSH into MacOS 12.3: python command not found

### ISSUE THREAD

**Issue by u9520107** [microsoft/vscode#146063] opened 2022-03-25 15:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Win11 21H2 (22000.556), remote host: MacOS 12.3 on M1

Steps to Reproduce:

1. Simply try to use remote ssh into MacOS 12.3

Remote Server Log:
[08:20:09.157] > Server did not start successfully. Full server log at /Users/jack.huang/.vscode-
> -server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log >>>
> /Users/jack.huang/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bi
> in/code-server: line 10: python: command not found
> usage: dirname string [...]
> usage: dirname string [...]
> /Users/jack.huang/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bi
> in/code-server: line 13: /node: No such file or directory
> <<< End of server log
> 325b0e84c307: start
> exitCode==32==
> listeningOn====

It seems that MacOS 12.3 no longer come bundled with python 2.7. I will try to install python 2.7. I'll try to install python2.7 on my own, but want to see if there will be an official solution to this.

**Comment by roblourens** [comment] 2022-03-25 17:08
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6442

**Closed by roblourens** 2022-03-25 17:08 UTC
