### ISSUE TITLE
Terminal is always launching externally when ConPTY is turned on

### ISSUE THREAD

**Issue by GollyJer** [microsoft/vscode#73790] opened 2019-05-15 20:14 UTC
I can't get the terminal to launch integrated. It always launches externally.
More details in [this StackOverflow question](https://stackoverflow.com/questions/56154957/how-do-i-get-visual-studio-code-to-use-the-integrated-terminal).

System Info
![image](https://user-images.githubusercontent.com/689204/57806034-20ce8480-7713-11e9-8deb-90b16e937970.png)

I'm not sure if this is a bug or user error.
Steps to Reproduce:
1. Open vscode.
2. Pres `ctrl` + `~`.

Does this issue occur when all extensions are disabled?: **Yes**

Thanks for any help! 👍

**Comment by comniemeer** [comment] 2019-05-16 15:33
Are you on Windows 10 Update 1903? I have the same problem on this build.

**Comment by GollyJer** [comment] 2019-05-16 16:29
> 
> 
> Are you on Windows 10 Update 1903? I have the same problem on this build.

Yes

**Comment by chnldw** [comment] 2019-05-17 01:13
Same issue here. I'm on 1903 as well. vscode 1.34.0

**Comment by Tyriar** [comment] 2019-05-20 19:32
Can you share your settings.json file?

**Comment by GollyJer** [comment] 2019-05-20 21:28
Fresh install. 🙂

![image](https://user-images.githubusercontent.com/689204/58053121-76d46b00-7b0b-11e9-96cc-fe1a40ecff30.png)

**Comment by Tyriar** [comment] 2019-05-20 22:26
@GollyJer can you try with the Insiders build tomorrow? I made some changes just today around this area. https://code.visualstudio.com/insiders

**Comment by GollyJer** [comment] 2019-05-20 22:39
@Tyriar Sure... I'll keep you posted. Thanks! 👍

**Comment by GollyJer** [comment] 2019-05-21 14:11
No change. Sorry.

![image](https://user-images.githubusercontent.com/689204/58103353-adf05e00-7b97-11e9-9826-670c0c98aca0.png)

**Comment by Tyriar** [comment] 2019-05-22 18:13
Weird, I don't suppose you have anything in your keybindings.json either?

Does disabling the Windows Enable Conpty setting affect it? Also what is the comspec environment variable set to?

**Comment by comniemeer** [comment] 2019-05-22 18:23
Yes, disabling Windows Enable Conpty works, the terminal launches in VS Code. Even in the stable build.

**Comment by GollyJer** [comment] 2019-05-23 01:53
keybindings
===
```json
[
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  },
  {
    "key": "alt+f",
    "command": "-gitlens.showCommitSearch",
    "when": "gitlens:enabled"
  },
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.quickOpenNavigateNextInEditorPicker",
    "when": "inEditorsPicker && inQuickOpen"
  },
  {
    "key": "ctrl+s",
    "command": "workbench.action.files.saveAll"
  },
  {
    "key": "ctrl+k s",
    "command": "-workbench.action.files.saveAll"
  },
  {
    "key": "ctrl+k s",
    "command": "workbench.action.files.save"
  },
  {
    "key": "ctrl+s",
    "command": "-workbench.action.files.save"
  },
  {
    "key": "ctrl+k ctrl+c",
    "command": "workbench.action.toggleCenteredLayout"
  },
  {
    "key": "ctrl+`",
    "command": "workbench.action.terminal.focus"
  },
  {
    "key": "ctrl+shift+x",
    "command": "multiCommand.reRun",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+,",
    "command": "workbench.action.openSettingsJson"
  },
  {
    "key": "ctrl+.",
    "command": "-settings.action.editFocusedSetting",
    "when": "inSettingsSearch"
  },
  {
    "key": "shift+alt+s",
    "command": "python.sortImports"
  }
]
```

comspec
===
![image](https://user-images.githubusercontent.com/689204/58220143-8ea21f80-7cc2-11e9-86d2-7ce3866c28a1.png)

**Comment by GollyJer** [comment] 2019-05-23 02:03
Answer... for now. 😀
https://stackoverflow.com/questions/56154957/how-do-i-get-visual-studio-code-to-use-the-integrated-terminal

**Comment by luchoespejo** [comment] 2019-05-24 13:40
the solution for mee.
1 - Go to https://code.visualstudio.com/insiders/ and install Version: 1.35.0-insider 
2 - Go to File/Preferences/Settings
3 - Search conPTY and disable --> Terminal › Integrated: Windows Enable Conpty

![image](https://user-images.githubusercontent.com/2988847/58331779-4133c880-7e10-11e9-9fa5-1ac3ee86692d.png)

![image](https://user-images.githubusercontent.com/2988847/58331800-4abd3080-7e10-11e9-9e41-355eef1b8759.png)

**Comment by comniemeer** [comment] 2019-05-24 17:02
@luchoespejo See a few answers before, it already has been pointed out.

**Comment by Tyriar** [comment] 2019-05-31 02:35
@zadjii-msft any ideas? ConPTY is launching an external conhost, turning on winpty works.

**Comment by zadjii-msft** [comment] 2019-05-31 13:22
... No, I haven't the faintest clue why this isn't working. 

Does the integrated terminal window display anything, or is it just blank?

Does the conhost window that appears have a scrollbar?

If the VS Code terminal is displaying something, then maybe the conhost that's getting launched to host conpty is not in headless mode (somehow).

If it's totally blank, then I'd imagine that somehow the conhost doesn't think that it's getting activated in conpty mode. Conhost will think it's in conpty mode as long as it has one of the pipes (in/out/signal), and if it's being activated via the API, it should definitely have at least the signal pipe.

**Comment by Tyriar** [comment] 2019-05-31 14:41
@zadjii-msft looks like the integrated terminal is blank based on https://stackoverflow.com/q/56154957/1156119

**Comment by zadjii-msft** [comment] 2019-05-31 14:49
Huh. That's kinda what I imagined, though I'm not sure it really helps psychic debug it. I can't get this to repro locally, so I'm not sure how to be able to debug this further. Maybe it has something to do with OS architecture vs VS Code architecture?

@GollyJer do you have WSL installed? If you do, could you try running cmd.exe from within a wsl prompt? That should activate another conpty, and hopefully help narrow down where this is originating from.

**Comment by Tyriar** [comment] 2019-05-31 16:46
I haven't repro'd it either, but it has been reported a few times. The code responsible for using conpty is at https://github.com/microsoft/node-pty/blob/master/src/win/conpty.cc if that helps.

**Comment by GollyJer** [comment] 2019-05-31 17:10
@zadjii-msft This is strange. I just reenabled `Conpty` in vscode settings and integrated terminal **is working**.

To answer your question... yes. I have WSL enabled and Ubuntu installed. Running `cmd` in bash activated an inline command prompt.

The major change I've made to my system is uninstalling Docker Desktop and disabling HyperV. I had to use VMWare Workstation which doesn't work in conjunction with HyperV.

I don't have time to turn on HyperV and reinstall Docker Desktop today, but I can at some point if necessary.

Do other's in this thread have Docker installed?

**Comment by adrianinfinitum** [comment] 2019-07-10 18:27
Ran into this same problem and the conpty workaround that @GollyJer posted worked for me.

I'm on Windows 10 Pro (Build 1903) and running Docker for Windows Desktop.

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:58:59.274Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT ia32 10.0.18362

**Comment by Tyriar** [comment] 2019-07-13 15:46
@zadjii-msft I've gotten quite a few reports for this, still can't repro myself though and I don't know what I can do or ask to help.

**Comment by yth2012** [comment] 2019-07-15 10:00
encountered the same problem. besides the method provided above I also found that by unchecking the "use legacy console" option in cmd/powershell it is able to run in vscode integrated console as before (at least for me)

**Comment by zadjii-msft** [comment] 2019-07-17 13:51
>  unchecking the "use legacy console" option

Oh my god that's 100% it. Just this week we figured out that if you're using the v1 console, that _also_ affects conpty, and launches the v1 console instead of conpty. We actually just made some changes to the OS this week to force conpty to use the v2 console, so hopefully this will be fixed in Insiders soon<sup>tm</sup>

**Comment by Tyriar** [comment] 2019-07-17 14:11
@zadjii-msft is there a microsoft/terminal issue tracking this?

**Comment by zadjii-msft** [comment] 2019-07-17 14:27
Yep! There's https://github.com/microsoft/terminal/issues/1838 and https://github.com/microsoft/terminal/pull/1935

**Comment by Scorpibear** [comment] 2019-08-30 07:02
Reproduced at Windows 10 Enterprise build 18362, VS Code v1.37.1. With ConPTY setting turn on, all tried terminals (PS 1.0, PS 6.0, bash) are run in external window. With turning off the setting, it is immediately fixes the issue.

**Comment by gorban** [comment] 2019-09-04 18:12
I encountered this same issue and disabling ConPTY for the integrated terminal fixed it for me (no more external Powershell windows are popping up and it works integrated in VS Code). This only started happening when installed Windows 1903.

**Comment by Tyriar** [comment] 2019-09-05 23:55
@Scorpibear @gorban do not turn conpty off, turn off "use legacy console" in your conhost settings: https://github.com/microsoft/vscode/issues/73790#issuecomment-511342381

**Comment by StdGit** [comment] 2019-09-30 16:52
@Tyriar What if I have windows 7 enterprise.
I have the same issue.

**Comment by Tyriar** [comment] 2019-09-30 17:42
@StdGit that's using a different system (winpty) that we are no longer improving upon, I'm not sure how you would fix that.

Closing since this is fixed in a future version of Windows 10 https://github.com/microsoft/terminal/issues/1838 and nothing more to action.

**Closed by Tyriar** 2019-09-30 17:42 UTC
Labels: bug, integrated-terminal, integrated-terminal-conpty, upstream, windows
