### ISSUE TITLE
Emacs usage in VSCode terminal is broken

### ISSUE THREAD

**Issue by j00bar** [microsoft/vscode#142754] opened 2022-02-10 18:48 UTC
Issue Type: <b>Bug</b>

Since the latest update, when I try to run emacs in the VSCode terminal, Weird Stuff™ happens.

First, the editor doesn't show up right away. I get a blank terminal and have to hit a keystroke to have it redraw.

More importantly, when opening emacs with a file as the argument (or, for example, when using emacs as the git commit message editor) the editor opens to `*scratch*`.

This did not happen in previous versions. Emacs works fine in the system terminal, just not VSCode's.

I've had a colleague successfully reproduce this behavior on their copy of 1.64.1 as well.

VS Code version: Code 1.64.1 (Universal) (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:26:08.977Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 8e391140-90fd-402a-914a-809486f4e509|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
vscode-pull-request-github|Git|0.36.1
vscode-emacs|hir|0.1.1
plantuml|jeb|2.17.2
vscode-position|jtr|1.1.2
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.2
vscode-thunder-client|ran|1.11.1
rewrap|stk|1.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstartedc:30433508
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by fherwig** [comment] 2022-02-13 14:51
I have a similar issue. No delay in starting up emacs, but emacs will open into *scratch* instead of the file argument. This happens both on a local Mac OS instance as well as on a remote Linux based instance. emacs will open file correctly when manually loaded from inside emacs once started. 

Version: 1.65.0-insider
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:16:57.139Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Darwin x64 20.6.0

**Comment by tstackhouse** [comment] 2022-02-14 21:55
Also seeing this behaviour following the update that pushed the new side panel.

```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic snap
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-28-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2029)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|30.78GB (7.09GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id dd44f64f-61ef-4c79-9c0a-8288003c84d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
ng-template|Ang|13.2.3
better-toml|bun|0.3.2
solargraph|cas|0.23.0
coddx-alpha|cod|0.3.1
gitignore|cod|0.7.0
yaml-key-viewer|cyb|0.2.2
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
graphviz-preview|EFa|1.5.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.2.0
php-intellisense|fel|2.3.14
vscode-jest-runner|fir|0.4.47
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.14
terminal|for|0.0.10
shell-format|fox|7.2.2
sass-lint|gle|1.0.7
todo-tree|Gru|0.0.215
terraform|has|2.19.0
rest-client|hum|0.24.6
latex-workshop|Jam|8.23.0
vscode-codeowners|jas|1.1.1
docthis|joe|0.7.1
Angular2|joh|12.0.0
json-escaper|jos|1.1.2
vscode-insertdatestring|jsy|2.3.1
auto-comment-blocks|kev|1.0.1
dotenv|mik|1.0.1
mlxprs|mlx|3.5.1
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.217.4
atom-keybindings|ms-|3.0.9
azure-account|ms-|0.9.11
powershell|ms-|2021.12.0
angular-console|nrw|17.14.1
vscode-jscpd|pau|0.3.4
material-icon-theme|PKi|4.13.0
ruby|reb|0.28.1
vscode-yaml|red|1.4.0
code-settings-sync|Sha|3.4.3
guides|spy|0.9.3
dot|Ste|0.0.1
move-ts|str|1.12.0
vscode-ruby|win|0.28.0
php-debug|xde|1.23.0
material-theme|zhu|3.13.19
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by meganrogge** [comment] 2022-02-15 16:18
cc @sbatten

**Comment by meganrogge** [comment] 2022-02-16 17:28
can you try to repro this in insider's and also attach a gif? I cannot reproduce the issue

![Recording 2022-02-16 at 11 27 30 (1)](https://user-images.githubusercontent.com/29464607/154321754-565978aa-9b69-48a7-a69e-9334a2fdbb3e.gif)

**Comment by meganrogge** [comment] 2022-02-16 17:46
In stable, running:

`emacs package.json` results in:
![Screen Shot 2022-02-16 at 11 45 27 AM](https://user-images.githubusercontent.com/29464607/154324671-313db550-2187-4a25-8eae-52292a097a69.png)

In insider's, running the same results in:

![Screen Shot 2022-02-16 at 11 45 49 AM](https://user-images.githubusercontent.com/29464607/154324718-5e12335c-0e63-4582-8176-20f8cb156b6f.png)

with this warning:

```
 WARN Error deserializing stored test result bc81d10d-2f6e-40b9-b6bb-69762396883b Error: Unable to read file '/Users/meganrogge/Library/Application Support/Code - Insiders/User/workspaceStorage/5cacf96d56b064c73732a980ab163340/testResults/bc81d10d-2f6e-40b9-b6bb-69762396883b.json' (Error: Unable to resolve nonexistent file '/Users/meganrogge/Library/Application Support/Code - Insiders/User/workspaceStorage/5cacf96d56b064c73732a980ab163340/testResults/bc81d10d-2f6e-40b9-b6bb-69762396883b.json')
    at p.doReadFileStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:605)
    at async p.doReadFile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:605)
    at async l.readForResultId (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1233)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1233
    at async Promise.all (index 15)
    at async l.read (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:123
```

**Comment by meganrogge** [comment] 2022-02-16 18:50
@deepak1556 we think this is a permissions related problem. it happens in 1.64 on linux/mac (before electron update) and we haven't touched node-pty recently. Do you know of any packaging changes that could've caused this?

**Comment by fherwig** [comment] 2022-02-16 20:58
Here is code-insider running on Mac in a remote connection to a linux server, left bottom command issued, right resulting emacs editor opening in scratch.
<img width="821" alt="image" src="https://user-images.githubusercontent.com/10589734/154354816-28d4a7e4-910e-41e3-9078-cffa566037f9.png">

And here the same in a local (zsh) instance, same behaviour.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/10589734/154355292-7cedf4d6-1618-49b3-a08b-4d761210eb44.png">

For me VS code shows the same behaviour, except when I want to exit emacs the entire VS Code window will exit as if I had done Cmd-q. Before the recent update of VS code I did the content would show in emacs, but still when trying to save, the whole VS Code window closes.

**VS Code insider**
Version: 1.65.0-insider
Commit: 52e65499654de7525e30df3a8228b69320796bf5
Date: 2022-02-16T05:16:06.667Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Darwin x64 20.6.0

**VS Code**
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by ivucica** [comment] 2022-02-16 22:21
https://xkcd.com/1172/

**Comment by deepak1556** [comment] 2022-02-24 17:12
@meganrogge there we no package related changes for macOS/linux with `1.64`. Also command of the launched sub process looks fine and `--debug-init` does not throw any error, so I don't think this was an issue at the process spawn level. Can you check if something changed with terminal rendering ?

```
$ ps -p 45826
  PID TTY           TIME CMD
45826 ttys001    0:00.49 /Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_14 ./package.json -nw
```

**Comment by Tyriar** [comment] 2022-02-25 00:59
I don't think this can be a rendering only issue as it's not opening the file?

We did have a rendering change in this area that @meganrogge pointed out: https://github.com/xtermjs/xterm.js/commit/a63890e6270749ae353db0d0b294d57448c82a72#diff-2c55cc3213368a05daba3b895bbb127ef81fa0dfa90f658ace9d89f12e963577R69 - @meganrogge can you see if reverting that fixes it?

**Comment by meganrogge** [comment] 2022-02-25 01:02
Reverting that did not fix it @Tyriar

**Comment by joelhock** [comment] 2022-03-02 19:48
Ok, i have a clue.  If you notice in the screenshots posted to this issue, they have `Quit` displayed in the status bar.  Adding `(setq debug-on-quit t)` to `.emacs` results in the following backtrace immediately on emacs startup in the vscode integrated terminal:
```
Debugger entered--Lisp error: (quit)
  xterm--version-handler()
  xterm--query("\033[>0c" (("\033[?" . xterm--version-handler) ("\033[>" . xterm--version-handler)))
  terminal-init-xterm()
  tty-run-terminal-initialization(#<frame F1 0xc927b0> nil t)
  command-line()
  normal-top-level()
```
adding `(setq xterm-extra-capabilities nil)` to `.emacs` solves the issue.  I believe the commands emacs issues are detailed in https://github.com/emacs-mirror/emacs/blob/master/lisp/term/xterm.el, but I haven't investigated further.

**Comment by giromide** [comment] 2022-03-04 04:19
I wonder if there's an equivalent to this in `vim` that explains the rendering problem that demands I `clear` the terminal just prior to running it.

**Comment by Zitrax** [comment] 2022-03-09 13:40
Noticed that if I press a key while emacs is loading with a file argument it works, if no key is pressed it opens *scratch*.

**Comment by danielsue** [comment] 2022-03-21 21:55
> 
adding (setq xterm-extra-capabilities nil) to ~/.emacs
This works for me too. Thanks.

**Comment by meganrogge** [comment] 2022-03-23 23:23
Fixed with the linked PR upstream

**Closed by meganrogge** 2022-03-23 23:23 UTC
Labels: bug, upstream, confirmed, upstream-issue-linked, upstream-issue-fixed

**Comment by meganrogge** [comment] 2022-03-28 14:59
to verify, run `emacs __file-name___` . it should open the file and display its contents, not showing `scratch` at the bottom
