### ISSUE TITLE
Shortcut Ctrl+Shift+e renders as unknown instead of navigating to explorer window

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode#121266] opened 2021-04-14 08:29 UTC
- VS Code Version: 1.55.2
- OS Version: Ubuntu 20.10

Steps to Reproduce:

1.Open Keyboard shortcuts, Ctrl k + Ctrl s. Then, press "Record keys" (Alt k). Press Ctrl_Shift_e. It renders as "ctrl+shift+unknown"
2. When a saved file is open in the editor window, hitting Ctrl_Shift_e does NOT navigate to explorer windows on the side. Instead the file becomes unsaved with an "underscore e" entered into the file.

Does this issue occur when all extensions are disabled?: Yes

Attaching two gif images of the same below.

https://i.stack.imgur.com/oaZOH.gif
(above, you will see that Ctrl_shift_w renders properly, but Ctrl_shift_e does not)

https://i.stack.imgur.com/1C6sr.gif

**Comment by connor4312** [comment] 2021-04-15 03:47
Please check out https://github.com/microsoft/vscode/wiki/Keybinding-Issues. If you're still having trouble, share the troubleshooting log

**Comment by TryerGit** [comment] 2021-04-15 17:30
I ran the Developer : Toggle Keyboard Shortcuts Troubleshooting

Then, on hitting Ctrl_shift_e, when the run and debug panel is open on the left, with the hope that the explorer window would open, the following log is obtained:

```
[2021-04-15 22:52:40.706] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlRight, keyCode: 17, key: Control
[2021-04-15 22:52:40.707] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlRight, keyCode: 5 ('Ctrl')
[2021-04-15 22:52:40.708] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-04-15 22:52:40.708] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftRight, keyCode: 16, key: Shift
[2021-04-15 22:52:40.709] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftRight, keyCode: 4 ('Shift')
[2021-04-15 22:52:40.710] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.

```

Again, after the above, the e gets printed in whatever file is open in the editor view as an "underscore e".

**Comment by alexdima** [comment] 2021-06-04 20:08
Duplicate of https://github.com/microsoft/vscode/issues/117966

**Closed by alexdima** 2021-06-04 20:08 UTC
