### ISSUE TITLE
VS Code parser problems.

### ISSUE THREAD

**Issue by varanthir** [Microsoft/vscode#6868] opened 2016-05-25 10:54 UTC
- VSCode Version: 1.1.1
- OS Version: Win 10 Home

VS Code can't parse code properly, script is ok - works.

![code_parser_bug](https://cloud.githubusercontent.com/assets/17810474/15537571/8d619626-2277-11e6-921d-f41be1da733c.png)

**Comment by aeschli** [comment] 2016-05-25 13:19
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by aeschli** 2016-05-25 13:19 UTC
