### ISSUE TITLE
Please do not change the tab order in the source control panel

### ISSUE THREAD

**Issue by djfarly** [microsoft/vscode#198134] opened 2023-11-13 16:30 UTC
Type: <b>Bug</b>

To create a commit I write the commit message, press tab and hit enter to commit.
The new AI icon should not be before the commit button in this order.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:57.054Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.93GB free)|
|Process Argv|--crash-reporter-id 17e0a57f-0612-4756-93e9-f08010f3a041|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
bundle-size|amb|1.5.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.20.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.10.3
multi-cursor-case-preserve|Car|1.0.5
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
auto-rename-tag|for|0.1.10
vscode-glsl|GeF|0.3.0
copilot|Git|1.135.0
copilot-chat|Git|0.10.1
vscode-env|Iro|0.1.0
smart-react-component-extractor|klo|0.1.0
twig-language-2|mbl|0.9.4
template-string-converter|meg|0.6.1
dotenv|mik|1.0.1
sort-selection-concentrically|min|1.0.4
vscode-duplicate|mrm|1.2.1
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
live-server|ms-|0.4.11
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.31.0
polacode|pnp|0.3.4
excalidraw-editor|pom|3.6.1
bevy-snippets-rendaoer|ren|0.10.0
rust-analyzer|rus|0.4.1729
vscode-sanity|san|0.1.4
crates|ser|0.6.3
vscode-rustfmt|sta|0.1.2
vscode-styled-components|sty|1.7.8
svelte-vscode|sve|107.13.0
even-better-toml|tam|0.19.2
es6-string-html|Tob|2.12.1
alphabetical-sorter|ue|2.0.1
pretty-ts-errors|yoa|0.5.2
markdown-all-in-one|yzh|3.5.1
file-size|zh9|1.0.0

(2 theme extensions excluded)

</details>

**Comment by djfarly** [comment] 2023-11-13 16:32
to be clear: With the AI commit message thing it goes: "add xyz" > tab > enter > add xyz is changed to something else, which is not what i normally want.

**Comment by djfarly** [comment] 2023-11-13 16:33
(The button also has no focus state, which makes this extra annoying)

**Comment by lszomoru** [comment] 2023-12-05 11:19
Adding @isidorn, @meganrogge to confirm that the recommended accessor for the source control input action button is pressing Tab while the input box is focused. Assuming that pressing Tab should indeed focus the action button you have couple of options: 
1. Disable the action button by toggling the `scm.showInputActionButton`
2. Use Ctrl/Cmd + ENTER to commit after you entered the commit message
3. In case you have invoked the action button to generate a commit message that overrides the commit message that you have typed, you should be able to use the keybinding for "Undo" to undo the change and restore the original commit message

The focus indicator for the input button is fixed in the latest Insiders release and will be released to Stable later this week.

**Comment by isidorn** [comment] 2023-12-05 11:36
Yes. For accessibility - tab focus should move from left to right, from top to bottom. So the "Generate Commit Message" button should be focused when pressing the first `tab`.

What I find weird is that blue Commit button only gets focus after the toolbar in the Changes view gets focus. Ideally the Commit button would gets focus right after the "Generate Commit Message".

**Comment by lszomoru** [comment] 2024-01-24 15:30
@isidorn, are you still able to reproduce this? When I focus the SCM input field and press `tab` twice, I end up with the focus on the Commit action button. I have spent quite some time toggling various settings that affect the layout of the Source Control view but I am not able to reproduce the issue.

**Comment by isidorn** [comment] 2024-01-24 15:44
This works well now. Thank you!

**Comment by lszomoru** [comment] 2024-01-24 15:49
Thanks! I will go ahead and close this issue as "by design".

**Closed by lszomoru** 2024-01-24 15:49 UTC
Labels: git
