### ISSUE TITLE
No autocomplete for native JavaScript props and methods

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#12186] opened 2016-09-17 10:16 UTC
- VSCode Version: 1.5.1
- OS Version: OS X El Capitan

Autocomplete for native methods and properties in JavaScript doesn't work inside IIFE (Immediately-Invoked Function Expression).

Steps to Reproduce:

1) Type `document.get` at the top of JS file - you will get 'getElementById` autocomplete suggestion.

![2016-09-17-0dyeh](https://cloud.githubusercontent.com/assets/1612675/18607761/e32f6238-7cde-11e6-9fff-e22aab4e8398.png)

2) Type `document.get` inside IIFE construction - you'll get no autocomplete suggestion for `getElementById`.

```javascript
(function (window, document) {
  document.get| // no autocomplete
})(window, document)
```

![2016-09-17-gtm7q](https://cloud.githubusercontent.com/assets/1612675/18607762/ed55e5a2-7cde-11e6-96bb-d15638ff2d42.png)

This looks like an issue, I hope this will be fixed in the next release.

**Comment by rozzzly** [comment] 2016-09-17 15:03
Offtopic.. but what theme is that lol looks nice.

**Comment by waderyan** [comment] 2016-09-20 17:17
@fronteed thanks for opening this issue. Moving to TypeScript language service (powers JavaScript auto complete).

**Comment by waderyan** [comment] 2016-09-20 17:18
This issue was moved to Microsoft/TypeScript#11012

**Closed by waderyan** 2016-09-20 17:18 UTC

**Comment by naxsooley** [comment] 2016-10-03 12:45
I'm using v1.5.3, current issue still exists and doesn't fixed at all.

**Comment by waderyan** [comment] 2016-10-03 21:43
@naxsooley thank you for your comment. The issue is on the TypeScript and we will get it fixed there.
