### ISSUE TITLE
Theming: allow list.focusForeground

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#26467] opened 2017-05-11 15:22 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (5057c95e6b5a43ddecee0d6f663764b7c80f6c95, 2017-05-11T06:05:28.620Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.7.0|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.16.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.4|
|tslint|eg2|0.14.0|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.4.1|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. When creating a workbench theme, I can them all the colors I need except the foreground color of the active menu item:

![screen shot 2017-05-11 at 11 19 05 am](https://cloud.githubusercontent.com/assets/835148/25957262/e42c5d32-363b-11e7-9251-8b4f50de8a3c.png)

2. All I can find is the overall "editor.foreground" but I like the color of that, but I'd rather use a lighter gray or white for the text in the active menu item.  I can (and did) theme the _background_ but there doesn't seem to be a corresponding foreground.

**Comment by pahen** [comment] 2017-05-12 08:58
Duplicate of https://github.com/Microsoft/vscode/issues/26277

**Comment by bpasero** [comment] 2017-05-12 17:09
https://github.com/Microsoft/vscode/issues/26277

**Closed by bpasero** 2017-05-12 17:09 UTC
Labels: feature-request, themes
