### ISSUE TITLE
[Feature request] Apply rename refactoring to all ES6 imports

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#21075] opened 2017-02-22 09:56 UTC
There a popular but unanswered question on stackoverflow: [Visual Studio Code - apply rename file refactoring in all ES6 imports](http://stackoverflow.com/questions/37747938/visual-studio-code-apply-rename-file-refactoring-in-all-es6-imports/42387739#42387739)

> I've typescript application build with ES6 modules.
> 
> How do I rename ts or js file representing a module without breaking ES6 import that referenced the renamed file?
> 
> e.g: rename MyModule.ts to RenamedModule.ts -> change import * from './MyModule' to import * from  './RenamedModule' in all files;
> 
> Is there an VSCode extension or typescript service that would rename module path in all ES6 imports when renaming file?

I believe the VS Code users would appreciate this feature and that it belongs to VSCode

**Comment by mjbvz** [comment] 2017-02-24 00:59
I believe this is a duplicate of #19439. This is something we are looking into for the future

**Closed by mjbvz** 2017-02-24 00:59 UTC
Labels: duplicate
