### ISSUE TITLE
I'm 100% sure that this is a github-actions bug.

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode#137944] opened 2021-11-26 14:11 UTC
Why github-actions closes that issue? I don't know why. Now, that issue has 0% possibility to be solved! (╯‵□′)╯︵┻━┻
![IMG_20211126_220314](https://user-images.githubusercontent.com/62426149/143593503-875c5c89-a603-47ed-b267-25b73e7e0f18.jpg)

**Comment by IllusionMH** [comment] 2021-11-26 14:36
Doesn't look like a bug it correctly marked missing initial content - more like lack of delay and check if content was updated in e.g. 10 minutes.

![image](https://user-images.githubusercontent.com/1312662/143596474-8a876280-179a-4e39-a73e-86e097409afd.png)
But this one is funny ╰（‵□′）╯

**Comment by CodeCrazy-ywt** [comment] 2021-11-26 15:15
Haha, I didn't look at the editing history 😂
But why vscode-triage-bot mark my issue as “Not in English”??? I wonder which language github-actions would think my issue is in.

**Comment by IllusionMH** [comment] 2021-11-26 16:03
> I wonder which language github-actions would think my issue is in.

Answer will be ~table~ jaw dropping... I'll see myself out :D

On serious note now I'm also curious because Bing detects message as English and I would expect it will be same in Cognitive Services API
![image](https://user-images.githubusercontent.com/1312662/143606958-67293a96-b5a5-41e5-899b-5d06910fb461.png)

**Comment by egamma** [comment] 2021-11-27 08:19
@CodeCrazy-ywt I've looked at the original issue #137860 and I observe that it contains no actionable text that describes how to reproduce the issue. This is the contents:

>I am inside my git project which has .git folder in it, but it's not showing anything ( branch, commits)

So the Bot was correct that the issue not helpful and triaged it same as issues that forgot to paste issue details from the clipboard. I've filed a separate issue https://github.com/microsoft/vscode/issues/137970 against the Bot infrastructure on this.

@CodeCrazy-ywt the best way to avoid this, is to file issues with details steps so that the development team can act on them. Therefore please file a new issue with your git problem with details for how to reproduce the problem, e.g., describe your setup, does it only happen in this folder, does it happen for other folders etc. I'll close this issue and invite you to file a detailed new issue about your problem.

**Closed by egamma** 2021-11-27 08:19 UTC

**Comment by CodeCrazy-ywt** [comment] 2021-11-27 09:19
> I observe that it contains no actionable text that describes how to reproduce the issue.

@egamma Haha, I have to explain that the content of that issue was originally “We have written the needed data blablabla”, and maybe the user edited that issue **after** github-actions closed that issue.

However, I think it will be better if github-actions can:

1. Not close an issue if a user **adds a comment containing the clipboard data** to a “please paste”-only issue.

2. Reopen when user **edits the content of issue by changing the “please paste” prompt to the clipboard data** or **adds a comment containing the clipboard data to an already closed “please paste”-only issue**.
