### ISSUE TITLE
Tasks that use repeated script value are incorrectly removed

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/vscode#142329] opened 2022-02-06 15:23 UTC
Issue Type: <b>Bug</b>

If multiple tasks share the same npm script, all but the last one will appear, disregarding the different label names or script options (eg: environment).

Bad:

```json
{
  "version": "2.0.0",
  "tasks": [{
      "label": "debug app1",
      "type": "npm",
      "script": "debug",
      "options": {
        "env": {
          "app": "app1",
          "port": "3000"
        }
      },
      "isBackground": true
    },
    {
      "label": "debug app2",
      "type": "npm",
      "script": "debug",
      "options": {
        "env": {
          "app": "app2",
          "port": "3001"
        }
      },
      "isBackground": true
    },
    {
      "label": "debug app3",
      "type": "npm",
      "script": "debug",
      "options": {
        "env": {
          "app": "app3",
          "port": "3002"
        }
      },
      "isBackground": true
    }
  ]
}
````

Only `debug app3` will appear.

If you change the script to `"script": "debug"`, `"script": "debug "`, `"script": "debug  "`, then it'll list all three.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (4.62GB free)|
|Process Argv|--crash-reporter-id 60cbaf76-22af-4ba9-96f5-323a3ef36b66|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics (16 x 3293)|
|Memory (System)|7.47GB (4.88GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
javascript-ejs-support|Dig|1.3.1
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
eta-vscode|sha|1.0.0
webvtt-language|spa|0.0.4
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710cf:30416617

```

</details>

This is has been a issue for a weeks or months, but I just found the workaround now.

**Comment by joyceerhl** [comment] 2022-02-06 16:08
Duplicate of https://github.com/microsoft/vscode/issues/93001?

**Comment by alexr00** [comment] 2022-02-07 10:05
Yes, it's a duplicate.

**Closed by alexr00** 2022-02-07 10:05 UTC
Labels: new release
