### ISSUE TITLE
Enable Emmet support for js, html and css in .liquid files.

### ISSUE THREAD

**Issue by jack-fdrv** [microsoft/vscode#163118] opened 2022-10-09 13:43 UTC
I would like to use Emmet Autocomplete for JS, CSS and HTML in .liquid files.
We cant make it like this:
```
"emmet.includeLanguages": {
        "liquid": "html, css, js"
},
```
or
```
"emmet.includeLanguages": {
        "liquid": "[html, css, js]"
},
```
So how?

**Comment by rzhao271** [comment] 2022-10-10 18:07
Duplicate of https://github.com/microsoft/vscode/issues/62910

**Closed by rzhao271** 2022-10-10 18:07 UTC
