### ISSUE TITLE
VS Code TypeScript built in extension stops and restarts every time a file is saved

### ISSUE THREAD

**Issue by hdngr** [microsoft/vscode#112696] opened 2020-12-17 01:37 UTC
- VSCode Version: 1.52.1
- OS Version: Mac OS 11.0.1

Steps to Reproduce:

1. Open any typescript file
2. Save File (even with no changes)
2. TS/JS Features initalizes and EVENTUALLY starts, but intellisense does not work until it does
![image](https://user-images.githubusercontent.com/1875033/102426996-48f42880-3fc5-11eb-81a8-6b6aae428418.png) 

Is there a setting to prevent TS Server from starting/stop every time a file is saved?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-12-17 22:23
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2020-12-17 22:24
Also check the developer logs to make sure the server is not crashing:

1. In VS Code
2. Run `Developer: Toggle Developer tools` in the command palette
3. Look in the developer console for errors related to TypeScript

**Comment by hdngr** [comment] 2020-12-18 00:13
Behavior cannot be replicated in `VS-Insiders`!

Here is what happens in `VS-Code`:
`[Extension Host] File /Users/someproject/node_modules/api/src/utils/isAdmin.ts has been changed. Restarting TS Server.`

Just realizing that what is going on here has to do with mono-repo architecture...  Yarn is reinstalling "api" in the top level `node_modules` folder when I save a file in `/Users/someproject/apps/api/...`.

Is the intended behavior for vs-code TS to watch all files in node_modules, and if they change, to restart the server?

For future visitors, is there a better config for vs-code?  Seems as though this is the intended behavior and I need to research my `yarn workspaces` settings.

Thanks!

**Comment by mjbvz** [comment] 2021-01-16 01:30
Thanks for the information. I am closing this since it does not happen insiders.

However I suspect it's not actually related to insiders at all, rather it seems that an extension or setting could be the root cause. As far as I can tell, the string `Restarting TS Server'  does not appear anywhere in our codebase, so my guess is that an extension is triggering the server restart

**Closed by mjbvz** 2021-01-16 01:30 UTC
Labels: needs more info
