### ISSUE TITLE
Multiline strings are truncated in the terminal

### ISSUE THREAD

**Issue by neidantaslopez** [microsoft/vscode#138589] opened 2021-12-07 11:57 UTC
Multiline strings ([Template literals (Template strings) from Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)) are truncated in the terminal when the area relative to the terminal is resized to make it smaller and then larger.

1. Run the following .js file in the Visual Code terminal (pwsh):

```
let html = 
`<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olá Mundo</title>
    <script>
        function helloWorld() {
            alert("Hello world!")
        }
    </script>
</head>
<body onload="helloWorld()">
    <p>Hellow world in JavaScript</p>
</body>
</html>`;

console.log(html);
```

2. Resize the terminal area so it's really small and then resize it so it's big again;

3. Note that the string text is truncated and can no longer be viewed completely.

**Comment by AlbertoFabbri93** [comment] 2021-12-11 10:53
The same happens to me with a Java program when printing multiple consecutive lines on the terminal. If I resize the terminal some lines gets deleted and there is no way to recover them.

**Comment by Tyriar** [comment] 2021-12-16 14:26
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/label terminal terminal-conpty windows

**Closed by Tyriar** 2021-12-16 14:26 UTC

**Comment by AlbertoFabbri93** [comment] 2021-12-17 22:23
Ok, I can not reproduce the error in Windows Terminal.
