### ISSUE TITLE
Broken keyboard shortcuts with multiplu layouts

### ISSUE THREAD

**Issue by henrique** [microsoft/vscode#89184] opened 2020-01-23 16:56 UTC
Issue Type: <b>Bug</b>

Ubuntu 18.04, standard VS install from  Ubuntu Software application

I have two keyboard layouts: german QWERTZ for my laptop, and an USB en-us QWERTY keyboard.
Both layouts are configured on Ubuntu, but German is the first (default).
Using the USB US keyboard, I can type normally on the editor but the shortcuts seem to be using the german layout. E.g.  Ctrl+z Redo instead of Undoing (Y and Z are switched over), and Ctrl+/ zooms out the editor instead of commenting the code line (- is on the place of / in a german layout)...  
It becomes quite impossible to use the editor

Note: I have not changed the layout while VS was already opened like in https://github.com/Microsoft/vscode/issues/42153

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-26-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.22GB (12.58GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.58038

</details>

**Comment by rebornix** [comment] 2020-01-27 22:47
Looks like duplicate of https://github.com/microsoft/vscode/issues/23690 as when you are switching keyboards, there is no keyboard layout event triggered on Linux.

**Comment by alexdima** [comment] 2020-01-28 10:47
@henrique Have you seen our troubleshooting wiki -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings


![image](https://user-images.githubusercontent.com/5047891/73257363-ec78f680-41c3-11ea-8604-155cd0d3b53a.png)

**Closed** 2020-02-14 01:36 UTC
Labels: keyboard-layout, linux, needs more info
