### ISSUE TITLE
Quick pick should prioritize contiguous matches

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123681] opened 2021-05-12 13:39 UTC
This has annoyed me for years. I'm just happy we have a new champion to fix it! 💪

![image](https://user-images.githubusercontent.com/22350/117984442-b4c88c00-b2ec-11eb-8611-81001afbfdd7.png)

cc @bpasero

**Comment by bpasero** [comment] 2021-05-12 13:50
There is not just one quick-pick and there is not just one filter/matcher. From the screenshot this seems to be the list of recently opened, which is leveraging the quick pick widget (not quick open). 

Probably a duplicate of https://github.com/microsoft/vscode/issues/34088

See also https://github.com/Microsoft/vscode/issues/27317 for a somewhat full list of issues in the area of quick pick and quick open regarding results and sorting.

**Comment by TylerLeonhardt** [comment] 2021-10-04 19:03
I think we have plenty of coverage in issues for this particular problem. So I'm closing this as a dupe.

**Closed by TylerLeonhardt** 2021-10-04 19:03 UTC
Labels: quick-pick
