### ISSUE TITLE
Behavior of Shift + End changed

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#17087] opened 2016-12-12 17:52 UTC
- VSCode Version: 1.8.0-insiders

Steps to Reproduce:

1. Select one line up with <kbd>Shift</kbd>+<kbd>↑</kbd>
2. Try to only select till the line end with <kbd>Shift</kbd>+<kbd>End</kbd>

Expected:
The cursor jumps to the end of the line where the cursor currently is (like in stable)
![stable](https://cloud.githubusercontent.com/assets/10532611/21110045/f8191c2e-c09b-11e6-999b-0e7048cdb228.gif)

Actual:
The cursor jumps to the end of the line where the selection ends
![insiders](https://cloud.githubusercontent.com/assets/10532611/21110059/0d4877f2-c09c-11e6-93cb-16c3a2075136.gif)

**Comment by felixfbecker** [comment] 2016-12-12 18:20
Same problem with <kbd>Pos1</kbd>

**Comment by kieferrm** [comment] 2016-12-13 05:37
Duplicate of #17011.

**Closed by kieferrm** 2016-12-13 05:37 UTC
Labels: duplicate
