### ISSUE TITLE
Visual Studio Code is not responding 

### ISSUE THREAD

**Issue by MuhammadRashed** [Microsoft/vscode#4734] opened 2016-03-29 09:54 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 - 64 bit
  Commit f291f4ad600767626b24a4b15816b04bee9a3049
  Date 2016-03-11T17:10:35.304Z
  Shell 0.35.6
  Renderer 45.0.2454.85
  Node 4.1.1

Steps to Reproduce:
it is produced in many ways one of them:
1. open JavaScript file 
2. type function 
3. press tab
4. the program instance freezes

Please note that I have several instances one of them freezes not all of them together, 
I do not have problem with memory or processing

**Comment by dbaeumer** [comment] 2016-03-29 19:20
@MuhammadRashed I can't reproduce this using VSCode 0.10.11. Which JS file did you open? 

It looks like you had the vscode workspace open. The workspace itself is configured for TS and not JS and if you opened a file in the out folder it could happen that too many files get loaded into the JS language server. We fixed this for 0.11.13.

Can you provide more details about a file that reveals the behavior.

**Comment by dbaeumer** [comment] 2016-03-29 19:20
@jrieken @egamma FYI.

**Comment by mjbvz** [comment] 2016-11-29 22:42
Closing since we haven't seen recent reports of this.

@MuhammadRashed please try out a more recent VSCode release and let us know if you still see this.

**Closed by mjbvz** 2016-11-29 22:42 UTC
Labels: bug, freeze-slow-crash, javascript, needs more info

**Comment by ramya-rao-a** [comment] 2016-12-07 22:43
Removing the "bug" label so that this stops coming in our list of verifiable closed bugs
