### ISSUE TITLE
Typescript not overwriting color customization

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40706] opened 2017-12-22 08:39 UTC
- VSCode Version: 1.20.0-insider f9115349ef09cfef2bed669680d10ac58b490dce
- OS Version: Win10

It was working fine in 1.19

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "function call",
            "scope": [
                "meta.function-call support.function",
                "meta.function-call entity.name.function",
            ],
            "settings": {
                "foreground": "#40b18c"
            }
        },
    ],
}
```
![typescritpt_f_call](https://user-images.githubusercontent.com/9638156/34291054-8bb81f98-e70b-11e7-92ff-c435c62a19f3.png)

It does work with more specific selector `meta.function-call entity.name.function.ts`. 

(javascript is working in 1.20 with the same code and selector `meta.function-call entity.name.function`).

---
Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-01-08 10:43
I have tried with both `Light` and `Light+` default themes, but I cannot reproduce. 

The Inspect TM Scopes widget computes the explanation for the color (the row where the selector is presented) with a different algorithm than that used regularly. 

The reason is that the one that is used regularly uses a trie data structure and the source rule is discarded while building the trie. 

I am quite curious to investigate deeper, @usernamehw can you still reproduce? Are you perhaps using a different base theme than `Light` or `Light+` ?

**Comment by usernamehw** [comment] 2018-01-08 19:29
@alexandrudima, it's my fault. I just didn't expect for `fontStyle` to clash with `foreground`.

I have this bunch of selectors to remove pesky italic:
```json
{
    "scope": [
        "comment",
        "comment.block",
        "comment.block.documentation",
        "comment.line",
        "constant",
        "constant.character",
        "constant.character.escape",
        "constant.numeric",
        "constant.numeric.integer",
        "constant.numeric.float",
        "constant.numeric.hex",
        "constant.numeric.octal",
        "constant.other",
        "constant.regexp",
        "constant.rgb-value",
        "emphasis",
        "entity",
        "entity.name",
        "entity.name.class",
        "entity.name.function",
        "entity.name.method",
        "entity.name.section",
        "entity.name.selector",
        "entity.name.tag",
        "entity.name.type",
        "entity.other",
        "entity.other.inherited-class",
        "invalid",
        "invalid.deprecated",
        "invalid.illegal",
        "keyword.operator",
        "keyword.operator.new",
        "keyword.operator.assignment",
        "keyword.operator.arithmetic",
        "keyword.operator.logical",
        "keyword.other",
        "markup",
        "markup.bold",
        "markup.changed",
        "markup.deleted",
        "markup.heading",
        "markup.inline.raw",
        "markup.inserted",
        "markup.italic",
        "markup.list",
        "markup.list.numbered",
        "markup.list.unnumbered",
        "markup.other",
        "markup.quote",
        "markup.raw",
        "markup.underline",
        "markup.underline.link",
        "meta",
        "meta.block",
        "meta.cast",
        "meta.class",
        "meta.function",
        "meta.function-call",
        "meta.preprocessor",
        "meta.return-type",
        "meta.selector",
        "meta.tag",
        "meta.type.annotation",
        "meta.type",
        "punctuation.definition.string.begin",
        "punctuation.definition.string.end",
        "punctuation.separator",
        "punctuation.separator.continuation",
        "punctuation.terminator",
        "storage",
        "storage.modifier",
        "storage.type",
        "string",
        "string.interpolated",
        "string.other",
        "string.quoted",
        "string.quoted.double",
        "string.quoted.other",
        "string.quoted.single",
        "string.quoted.triple",
        "string.regexp",
        "string.unquoted",
        "strong",
        "support",
        "support.class",
        "support.constant",
        "support.function",
        "support.other",
        "support.type",
        "support.type.property-name",
        "support.variable",
        "variable",
        "variable.language",
        "variable.name",
        "variable.other",
        "variable.other.readwrite",
        "variable.parameter",
        "meta.import.ts meta.block.ts variable.other.readwrite.alias.ts",
        "meta.import.tsx meta.block.tsx variable.other.readwrite.alias.tsx",
        "meta.import.js variable.other",
        "entity.name.function.ts",
        "entity.name.function.tsx",
        "support.type.primitive",
        "entity.name.tag.yaml",
        "meta.tag.sgml.doctype.html",
        "entity.name.tag.doctype",
        "meta.tag.sgml.doctype",
        "entity.other.attribute-name",
        "entity.name.tag.custom",
        "source.js.jsx keyword.control.flow.js",
        "support.type.property.css",
        "variable.assignment.coffee",
        "support.function.basic_functions",
        "keyword.operator.expression.typeof",
        "keyword.operator.type.annotation",
        "assignment.coffee",
        "entity.name.type.ts",
        "support.constant.math",
        "meta.object-literal.key",
        "meta.var.expr storage.type",
        "text.html.markdown",
        "parameter",
        "keyword",
        "language",
        "type .function",
        "type.function",
        "storage.type.class",
        "type.var",
        "meta.parameter",
        "meta.parameters",
        "keyword.control",
        "modifier",
        "this",
        "italic",
        "quote",
    ],
    "settings": {
        "fontStyle": ""
    }
}
```
And it's preventing setting `foreground` in 1.19.1 & 1.20 for `meta.function-call entity.name.function` because of `entity.name.function.ts`.

**Comment by usernamehw** [comment] 2018-01-13 17:45
Should it be closed or is it a bug?

**Comment by alexandrudima** [comment] 2018-01-23 08:11
Changing `fontStyle` should be independent of a different selector changing `foreground`.

**Comment by alexandrudima** [comment] 2018-02-05 11:44
Ok, I have just double checked in code at https://github.com/Microsoft/vscode-textmate/blob/df3539f87667c32fafd30d27208070fd931813f9/src/grammar.ts#L1045

and it turns out `fontStyle` and `foreground` are not as separated as I believed.

With the following simplest repro:

```
{
	name: "base theme",
	scope: ["entity.name.function"],
	settings: { fontStyle: "italic", foreground: "#DCDCAA" }
}, {
	name: "no italics",
	scope: ["entity.name.function.ts"],
	settings: { fontStyle: "" }
},
{
	name: "function call",
	scope: ["meta.function-call entity.name.function"],
	settings: { foreground: "#40b18c" }
},
```

As part of building a trie, the rules get "completed" in the following way:

```
{
	name: "base theme",
	scope: ["entity.name.function"],
	settings: { fontStyle: "italic", foreground: "#DCDCAA" }
}, {
	name: "no italics",
	scope: ["entity.name.function.ts"],
	settings: { fontStyle: "", foreground: "#DCDCAA" }
},
{
	name: "function call",
	scope: ["meta.function-call entity.name.function"],
	settings: { foreground: "#40b18c" }
},
```

In this case, the second rule (no italics) will inherit the color from the first rule (base theme). And it is the one that wins.

The discrepancy in the inspect tool comes from it being implemented using a different algorithm.

**Comment by alexandrudima** [comment] 2018-02-05 11:57
To verify:
* Dark theme
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "no italics",
                "scope": [
                    "entity.name.function.ts",
                    "entity.name.function.tsx",
                ],
                "settings":{
                    "fontStyle": ""
                }
            },
            {
                "name": "function call",
                "scope": [
                    "meta.function-call support.function",
                    "meta.function-call entity.name.function",
                ],
                "settings": {
                    "foreground": "#40b18c"
                }
            },
        ],
    }
```
![image](https://user-images.githubusercontent.com/5047891/35803423-1148430a-0a74-11e8-8846-d3a01c975aff.png)

**Closed** 2018-02-05 11:58 UTC
Labels: bug, grammar
