### ISSUE TITLE
useIgnoreFilesByDefault is a bad setting name

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37210] opened 2017-10-31 07:50 UTC
Refs #37179

`"search.useIgnoreFilesByDefault": true` sounds ugly, why should the word default be part of this setting name. I propose the following name:
`"search.respectIgnoreFiles"`

**Comment by joaomoreno** [comment] 2017-10-31 14:02
Agreed. What does `byDefault` even mean in this case?

**Comment by chrmarti** [comment] 2017-10-31 15:12
Agree, I was using the existing setting for text search, but that might not be a good fit here. (Also: #37291)

**Comment by roblourens** [comment] 2017-10-31 23:18
`useIgnoreFilesByDefault` isn't the right setting to use for quickopen here. It determines whether the 'use ignore files' button in the search viewlet is selected by default in a new workspace.

https://github.com/Microsoft/vscode/issues/32035

Let's talk about it tomorrow @chrmarti

**Comment by chrmarti** [comment] 2017-11-01 21:28
Fixing with #37291. Marking as duplicate of #37291.

**Closed by chrmarti** 2017-11-01 21:28 UTC
Labels: polish
