### ISSUE TITLE
VS Code automatically closes when I try to open it

### ISSUE THREAD

**Issue by Sh0g0-1758** [microsoft/vscode#214492] opened 2024-06-06 18:04 UTC
Does this issue occur when all extensions are disabled?: Don't know, can't really open it to disable the extensions. 

- VS Code Version: 1.90.0
- OS Version: Ubuntu 24.04 LTS

Steps to Reproduce:

1. Open terminal in any directory
2. open vs code by ``` code .``` or by simply clicking on its icon.

**Comment by erickduran-stx** [comment] 2024-06-06 18:26
Same as @Sh0g0-1758 . VS Code automatically closes

**Comment by simonqueric** [comment] 2024-06-06 21:51
> For now I have reverted the commit that caused the bug. I am back to commit `dc96b837` now. It works fine then.



> For now I have reverted the commit that caused the bug. I am back to commit `dc96b837` now. It works fine then.

Hello, could you please provide steps / tutorial to come back to commit `dc96b837` ?

**Comment by GuySartorelli** [comment] 2024-06-06 22:56
Duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by deepak1556** [comment] 2024-06-07 02:33
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Closed by deepak1556** 2024-06-07 02:33 UTC
Labels: triage-needed, new release
