### ISSUE TITLE
The font size is too small on Release notes page.

### ISSUE THREAD

**Issue by chanchancl** [Microsoft/vscode#19896] opened 2017-02-04 02:29 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

I want to have same font size in new release notes page as my settings.

**Comment by joaomoreno** [comment] 2017-02-06 09:47
Can you show us a screenshot?

**Comment by chanchancl** [comment] 2017-02-13 05:16
@joaomoreno of course
![image](https://cloud.githubusercontent.com/assets/11457297/22871691/401949d0-f1ee-11e6-892e-e592b1148ce4.png)

and my resolution is 1920*1080

**Comment by joaomoreno** [comment] 2017-02-13 07:36
It looks as big as menu items.

**Comment by joaomoreno** [comment] 2017-02-13 07:36
Closing as duplicate of #5745, since you can't zoom in.

**Closed by joaomoreno** 2017-02-13 07:36 UTC
Labels: needs more info
