### ISSUE TITLE
VS Code messes with Linux places paths. VS Code is opened instead of system path.

### ISSUE THREAD

**Issue by jonagoldman** [Microsoft/vscode#41037] opened 2018-01-02 16:43 UTC
The "Places" extension is a really popular extension that adds a menu for quickly navigating places in the system. It is activated by default on most Linux Gnome distributions.

After installing VS Code, anything opened using the "Places" extension opens VS Code instead of the default folder / path.

- VSCode Version: 1.19.1-1 (official binary version)
- OS Version: Antergos Linux 17.12

Steps to Reproduce:

0. Install VS Code
1. Make sure you have the "Places" extension activated
2. Using the places menu in the top bar, open any location (Home, Documents, etc...) 

![screenshot from 2018-01-02 13-30-38](https://user-images.githubusercontent.com/1297559/34491408-11002d1c-efc2-11e7-86a3-cfeb7b6fd978.jpg)

Actual result:
VS Code opens.

Expected result:
System path/folder/place is opened.

**Comment by bpasero** [comment] 2018-01-03 08:25
@Tyriar any clues?

**Comment by Tyriar** [comment] 2018-01-03 14:30
This happens because we register vscode as an opener of folders in the desktop file. If anyone knows a way to deprioritize or something we can do that but it would be too big of a regression to remove this feature from other, AFAICT behaving distros.

This is the "problem" line:

https://github.com/Microsoft/vscode/blob/fd08d32b40c8a9ff56777265bce3c385008c3cb1/resources/linux/code.desktop#L11

**Comment by Tyriar** [comment] 2018-01-03 14:30
As a workaround for our problem, you can open up the installed desktop file and remove `inode/directory` (every time VS Code updates).

**Comment by DerTieran** [comment] 2018-02-27 22:52
Just wanted to follow up on this issue because I get the same behavior.
It also happens when using `xdg-open` to open a directory (e.g. `xdg-open ~`).

I also set nautilus as the default for `inode/directory`
```sh
➜ xdg-mime default nautilus.desktop inode/directory

➜ xdg-mime query default inode/directory           
nautilus.desktop
```
but it still doesn't work.

Then I looked for the distribution-provided defaults for `inode/directory`
```sh
➜ cat /usr/share/applications/mimeinfo.cache | grep inode/directory
inode/directory=visual-studio-code.desktop;org.gnome.Nautilus.desktop;
```
and it seems the order here does matter, changing it to
```sh
inode/directory=org.gnome.Nautilus.desktop;visual-studio-code.desktop;
```
fixes the issue.

Sadly I'm not an expert in this field so I can't tell you if you can influence this or if this needs to be done after every update (I hope not because vs code is still registered).

It might be even a issue with `gio` (used [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/blob/f9ae518c9d19ad79e163ecc0791ae41ecbcfb3c0/extensions/places-menu/placeDisplay.js#L87)) and opening directories.
Because it works for `text/plain` as expected
```sh
➜ xdg-mime query default text/plain                
gedit.desktop
 
➜ cat /usr/share/applications/mimeinfo.cache | grep text/plain     
text/plain=visual-studio-code.desktop;org.gnome.gedit.desktop;

➜ xdg-open ~/some.txt
```

**Comment by Tyriar** [comment] 2018-02-28 16:22
Copying over my response from https://github.com/Microsoft/vscode/issues/44344

> This is happening due to this line in the .desktop file:
> 
> https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop
> 
> Which tells the system (and nautilus) that VS Code knows how to open folders.
> 
> If anyone knows how to do this in such a way that it is marked as low priority I'd love to hear it, I'm not sure how to "fix" this without removing VS Code's integration for opening folders right now.

**Comment by Tyriar** [comment] 2018-02-28 16:23
Copying over my response from https://github.com/Microsoft/vscode/issues/44344

> This is happening due to this line in the .desktop file:
> 
> https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop
> 
> Which tells the system (and nautilus) that VS Code knows how to open folders.
> 
> If anyone knows how to do this in such a way that it is marked as low priority I'd love to hear it, I'm not sure how to "fix" this without removing VS Code's integration for opening folders right now.

**Comment by DerTieran** [comment] 2018-02-28 18:42
I'm answering here instead of #44344.

@Tyriar I don't think it is really an issue with VS Code.
You are registering VS Code to for both `text/plain` and `inode/directory`
https://github.com/Microsoft/vscode/blob/fd08d32b40c8a9ff56777265bce3c385008c3cb1/resources/linux/code.desktop#L11

And as I [mentioned before](https://github.com/Microsoft/vscode/issues/41037#issuecomment-369056292) `text/plain` works as expected even though it is registered the same way.

I think this is a bug with `inode/directory` not using the default application but the first one registered for it.

I'm not sure where this should be reported instead, but I don't think you can do something about it (except for not registering `inode/directory`).

**Comment by DerTieran** [comment] 2018-03-01 20:28
Just verified this by installing another file manager ([`vifm`](https://www.archlinux.org/packages/community/x86_64/vifm/)).
Same problem, opening a directory with `xdg-open` or places uses the first entry for `inode/directory` instead of the default:
```sh
➜ xdg-mime query default inode/directory                           
nautilus.desktop

~ 
➜ cat /usr/share/applications/mimeinfo.cache | grep inode/directory
inode/directory=vifm.desktop;visual-studio-code.desktop;org.gnome.Nautilus.desktop;

~ 
➜ xdg-open ~/Documents
```

**Comment by Tyriar** [comment] 2018-03-01 20:50
Thanks for looking into it @DerTieran, I'll close this off as you suggest since it looks like something in the OS is misbehaving

**Closed by Tyriar** 2018-03-01 20:50 UTC
Labels: bug, help wanted, linux

**Comment by goodmami** [comment] 2018-03-15 18:49
I know the issue is closed but the problem still affects me and I want to add some info here in case someone else stumbles upon this issue.

Note: I'm also using Gnome-shell (3.26.2) on Antergos, like the OP, and I don't recall having the problem on Ubuntu, so the problem is likely to affect Antergos and maybe Arch Linux.

The [standard for default applications](https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s04.html) is to look for the first entry in one of several mimeapps.list files; if the first entry isn't available (uninstalled, etc.), the next is tried. Order does matter. On my machine, I have a `~/.config/mimeapps.list` file, but it does not contain any entries for `inode/directory`, and there are no other `mimeapps.list` files that are checked. There are, however, `mimeapps.cache` files, which are generated automatically from the `.desktop` files, meaning the default depends on the order they are automatically added (maybe by the timestamp of the `.desktop` file?). See the Arch wiki article about [Default_applications#Desktop_entries](https://wiki.archlinux.org/index.php/Default_applications#Desktop_entries) for an explanation about the `mimeapps.cache` files.

Changing the `mimeapps.cache` file is only a temporary solution, since it gets regenerated. Instead, add an entry into the `.config/mimeapps.list` file (as described in [this](https://forum.antergos.com/topic/9261/folders-opening-with-microsoft-code-instead-of-deepin-file-manager) Antergos forum post), creating the file if necessary:

```
[Default Applications]
inode/directory = org.gnome.Nautilus.desktop
```

(or just the second line if there is already a `[Default Applications]` section; and change the `.desktop` file if you prefer a different default)

I think this is indeed a problem with the distribution and not VSCode

**Comment by goodmami** [comment] 2018-03-18 18:58
Should be fixed in Antergos (see https://github.com/Antergos/antergos-packages/issues/299)

Update your packages and test (but see here if you have trouble: https://forum.antergos.com/topic/9464/antergos-gnome-defaults-list)

**Comment by Tyriar** [comment] 2018-03-19 18:20
Thanks @goodmami!
