### ISSUE TITLE
Extension host crashing repeatedly 

### ISSUE THREAD

**Issue by TheSolly** [microsoft/vscode#176950] opened 2023-03-13 10:44 UTC
Type: <b>Bug</b>

Manipulating a jsconfig.json file, causing the extension host to crash after saving and formatting the file.

VS Code version: Code - Insiders 1.77.0-insider (95ee78fd9ada5361edb97a51122cb84e8b46c243, 2023-03-13T05:23:39.248Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 8, 7|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id fb13af6d-bf4b-497c-acdc-212ac5023b58|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|1.0.8
vscode-icontheme-nomo-dark|be5|1.3.6
emojisense|bie|0.9.1
vscode-tailwindcss|bra|0.9.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vscode-great-icons|emm|2.1.91
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
code-runner|for|0.12.0
copilot|Git|1.77.9225
todo-tree|Gru|0.0.224
styled-components-snippets|jon|0.10.0
vscode-styled-components|jpo|1.6.6
react-native-snippet|jun|0.5.6
vscode-simple-icons|Lau|1.16.0
codeacejumper|luc|3.3.2
string-manipulation|mar|0.5.7
ts-error-translator|mat|0.8.0
vscode-language-babel|mgm|0.0.37
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.2.0
color-highlight|nau|2.5.0
convert-css-in-js|pau|1.1.3
seti-icons|qin|0.1.3
subtle-brackets|raf|3.0.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
vscode-fileutils|sle|3.10.0
code-spell-checker|str|2.19.0
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|3.1.1
errorlens|use|3.7.0
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.2.0
vscode-todo-highlight|way|1.0.5

(19 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192cf:30661257
funwalk2cf:30682975
pythonms35:30671666
0bg3d529:30680467

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-13 11:30
Does this still happen after you disable the Copilot extension? If yes, please re-enable it and use the `Start Extension Bisect` command to investigate other causes.

**Comment by TheSolly** [comment] 2023-03-14 10:22
Yes, could confirm Copilot is the culprit.

**Comment by isidorn** [comment] 2023-03-15 11:15
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:15 UTC
Labels: freeze-slow-crash-leak, extension-host, triage-needed
