### ISSUE TITLE
Feature request: remember Mac Spaces location

### ISSUE THREAD

**Issue by jvu84** [microsoft/vscode#144853] opened 2022-03-10 18:22 UTC
Issue Type: <b>Feature Request</b>

Love your IDE.

I have a lot of monitors and in each monitor, i have several Spaces open on each.  It would be nice for VSCode to remember which space it was in when I restart my computer.

Thanks.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

**Comment by yume-chan** [comment] 2022-03-11 01:51
Duplicate of #123517

**Closed** 2022-03-11 05:46 UTC
Labels: *duplicate, triage-needed
