### ISSUE TITLE
Zooming editor view causes rendering issues with code annotations

### ISSUE THREAD

**Issue by stofte** [Microsoft/vscode#15828] opened 2016-11-21 18:22 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open any C# project
2. Wait for intellisense/annotations to appear (ie, "references" annotation on class fields, methods, etc) 
3. Zoom editor view (Ctrl++)

Result:
Annotations appear off to the left in the margin, instead of at the proper locations. They're still clickable out there, so it's functional.
See picture http://i.imgur.com/pUsklJd.png

I couldn't figure out if this was new, or not (there seems to be a variety of zoom issues already) so apologies in advance  if this is a dupe.

**Comment by ramya-rao-a** [comment] 2016-11-21 22:31
Closing as duplicate of #15389. The fix is already in the insiders build. You can use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-21 22:31 UTC
