### ISSUE TITLE
Chat view empty after restart

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#190581] opened 2023-08-16 11:59 UTC
* I have the chat view dragged into the alternative side bar into its own view
* I reload
* 🐛 the view is empty (despite the extension being active and running)

Switching the view back and forth, e.g from outline back to chat renders the view. It seems some view-activation/restoration is missing here

<img width="1578" alt="Screenshot 2023-08-16 at 13 58 01" src="https://github.com/microsoft/vscode/assets/1794099/fcd0330d-3da9-448a-beb8-0fbe8e3a3aaf">

**Comment by roblourens** [comment] 2023-08-18 00:05
Whoa

**Comment by roblourens** [comment] 2023-08-18 17:20
I can't repro in OSS. Any suggestions @sbatten?

**Comment by roblourens** [comment] 2023-08-18 18:21
It happens when there is also another view in the secondary sidebar, so I can repro in OSS with the Outline view also in the secondary sidebar

**Comment by sbatten** [comment] 2023-08-29 00:56
duplicate of https://github.com/microsoft/vscode/issues/185179

**Closed by sbatten** 2023-08-29 00:56 UTC
Labels: bug, panel-chat
