### ISSUE TITLE
Mac OS: Allow to save files that need user elevation

### ISSUE THREAD

**Issue by jreljac** [Microsoft/vscode#13404] opened 2016-10-09 22:50 UTC
- VSCode Version: 1.5.3
- OS Version: macOS 10.12

Steps to Reproduce:
1. Install Code into command path using the Command pallet option **Shell command: Install 'code' command in PATH**
2. Open terminal then open a protected file using `code` Example: `$ code /etc/php.ini`
3. Edit file then `cmd + S` to save
4. VSCode responds with `Error Failed to save 'php.ini': File is write protected.  Select 'Overwrite' to remove protection.`
- Clicking **Overwrite** produces the same message
- Clicking **Cancel** produces the same message
- Clicking Esc key or **Discard** dismisses the message

Typical behavior would be to prompt the user for administrator credentials to allow the protected file to be saved.

**Comment by fuggfuggfugg** [comment] 2016-10-11 18:22
After updating VSCode, It saves the files couple of times initially and then abruptly stops saving code. I've to close the app and re-open VSCode.

**Comment by bpasero** [comment] 2017-12-03 15:54
/duplicate of https://github.com/Microsoft/vscode/issues/1614

**Closed by bpasero** 2017-12-03 15:54 UTC
Labels: *duplicate, feature-request, run-as-admin
