### ISSUE TITLE
Submenu contribution documentation

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#128603] opened 2021-07-14 03:20 UTC
@joaomoreno was doing [great work](https://github.com/microsoft/vscode/pull/102784) on this. Has it been released yet? If so then the [documentation for the contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) needs to be updated. 

The closest I can find is [this comment](https://github.com/microsoft/vscode/issues/100172#issuecomment-645203070).

**Comment by usernamehw** [comment] 2021-07-14 06:22
/duplicate of https://github.com/microsoft/vscode-docs/issues/4643

**Closed** 2021-07-14 06:22 UTC
Labels: *duplicate
