### ISSUE TITLE
It's impossible to create a folder or file via new folder/file buttons when project has only folders in the root level 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#1152] opened 2015-12-09 23:27 UTC
If my project structure is like this:

```
.
├── bar
├── baz
└── foo
```

And I've selected a folder in the sidebar, the new folder/file button will create a folder/file inside the selected folder and there is no way (that I know of) to select the root folder and make a folder in root level.

![screen shot 2015-12-09 at 3 27 08 pm](https://cloud.githubusercontent.com/assets/543633/11702164/54b4471e-9e89-11e5-8c75-5d6d21e160e7.png)

**Comment by egamma** [comment] 2015-12-10 07:43
Closing as a duplicate of #1043

**Closed by egamma** 2015-12-10 07:43 UTC
