### ISSUE TITLE
Wrong "open recent" order

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53458] opened 2018-07-02 18:45 UTC
- Open folder A
- Invoke "Open Recent", ctrl+r, open folder B
- Invoke "Open Recent"
- Folder A should be the second item in the list because it was used most recently, but it isn't

This isn't happening 100% of the time but if I open 3 windows and switch between them in a different order a few times, then it gets screwed up.

I use this really often so this is probably new within the last couple days.

**Comment by bpasero** [comment] 2018-07-03 04:57
@roblourens the logic lives in `historyMainService` and [there has not been a relevant change for a long time ](https://github.com/Microsoft/vscode/commits/74fcd9ae313957df6ed910966616225d67831a24/src/vs/platform/history/electron-main/historyMainService.ts). I can also not reproduce. If you have more specific steps that reliably reproduce, let me know. Also maybe try on another machine of another user.

**Comment by roblourens** [comment] 2018-07-03 05:01
I'll debug it tomorrow, it repro'd very consistently today.

**Comment by roblourens** [comment] 2018-07-03 05:59
I think this is what's happening

- I switch windows and so 'recently opened' windows are updated. menubarPart.ts in every window listens to that and calls getRecentlyOpened to sync recent entries: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/menubar/menubarPart.ts#L270 (sorry @sbatten) 
- That would be fine, but getRecentlyOpened has the side effect of adding the calling window to the top of list. https://github.com/Microsoft/vscode/blob/master/src/vs/platform/history/electron-main/historyMainService.ts#L189
- And it looks like that mutates the array that the stateService has.

Check my work on this, if it's true that using open recent can shuffle your recent entries, we might take it for June.

**Comment by roblourens** [comment] 2018-07-03 06:02
Yeah with a dumb fix like `storedRecents = objects.deepClone(storedRecents);` in getRecentlyOpened, I can't reproduce it anymore

**Comment by bpasero** [comment] 2018-07-03 08:50
Thanks for the investigation, so it seems related to using a custom menu on Windows/Linux (I am on macOS). Moving to July, I think this needs fixing.

**Comment by roblourens** [comment] 2018-07-03 14:53
I'm also on MacOS

**Comment by sbatten** [comment] 2018-07-17 18:13
@bpasero I need to sync to get the recent entries, so fixing the getRecentlyOpened operation seems like the correct solution

**Comment by sbatten** [comment] 2018-08-26 19:45
doesn't seem to repro since we moved back to the old menus, we will need to re-visit when the dynamic menus come back.

**Comment by sbatten** [comment] 2018-09-21 18:40
As discussed, we will start validation of the dynamic menus in debt week of October

**Comment by sbatten** [comment] 2018-10-29 18:13
will be addressed when moving the open recent logic out of main

**Comment by sbatten** [comment] 2018-12-03 15:23
the branch that @roblourens  verified this is fixed this will be merged in December Debt week

**Comment by sbatten** [comment] 2018-12-12 23:19
it has been merged #64092

**Closed by sbatten** 2018-12-12 23:19 UTC
Labels: bug, workbench-menu
