### ISSUE TITLE
JSDoc renders wrong when it includes a code snippit with an @ symbol

### ISSUE THREAD

**Issue by bschlenk** [microsoft/vscode#105534] opened 2020-08-27 21:38 UTC
- VSCode Version: 1.48.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Write some jsdoc for a function, that includes a js code example that includes an `@` symbol
2. Hover the function and look at the code rendered in the popup

Does this issue occur when all extensions are disabled?: (Yes)/No

Here's the code:

![Screen Shot 2020-08-27 at 5 31 54 PM](https://user-images.githubusercontent.com/1390303/91497406-f95de580-e88b-11ea-84b7-e3d93c65d2ba.png)

And here's how it renders:

![Screen Shot 2020-08-27 at 5 32 05 PM](https://user-images.githubusercontent.com/1390303/91497423-0084f380-e88c-11ea-9b72-939ead29f443.png)

**Comment by mjbvz** [comment] 2020-08-27 22:29
Duplicate of https://github.com/microsoft/TypeScript/issues/39371

**Closed by mjbvz** 2020-08-27 22:29 UTC
Labels: new release
