### ISSUE TITLE
All the extension icons in the activity bar are gone after last update 

### ISSUE THREAD

**Issue by dlucazeau** [microsoft/vscode#92323] opened 2020-03-10 08:32 UTC
Issue Type: <b>Bug</b>

Since the last update, this bug is now in VSCode not only in Insiders (@see https://github.com/microsoft/vscode/issues/88814#issuecomment-586848250).
This bug affects also the explorer when using extensions theme icons like (Material Icon Theme)

See also https://github.com/microsoft/vscode/issues/92322#issue-578407406

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.90GB (9.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
vscode-sqlite|ale|0.8.1
ng-template|Ang|0.900.15
color-info|bie|0.5.1
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.4.2
file-templates|brp|1.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
docs-markdown|doc|0.2.58
xml|Dot|2.5.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-reveal|evi|4.0.3
vscode-commands|fab|1.3.0
vscode-terminals|fab|1.12.9
vscode-firefox-debug|fir|2.7.0
vscode-jest-runner|fir|0.4.15
dotnet-test-explorer|for|0.7.1
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|2.1.34
todo-tree|Gru|0.0.169
vscode-test-explorer|hbe|2.17.0
vscode-guid|hea|1.4.19
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
plantuml|jeb|2.13.6
svg|joc|1.1.3
Angular2|joh|9.1.2
vscode-peacock|joh|3.6.0
vscode-regexp-preivew|le0|0.0.3
csharpfixformat|Leo|0.0.84
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
git-graph|mhu|1.21.0
vscode-checkpoints|mic|1.3.0
ecdc|mit|1.3.0
vscode-kanban|mkl|1.27.1
vscode-cosmosdb|ms-|0.12.1
vscode-docker|ms-|1.0.0
vscode-language-pack-fr|MS-|1.43.2
csharp|ms-|1.21.13
mssql|ms-|1.9.0
remote-wsl|ms-|0.42.3
azure-account|ms-|0.8.8
typescript-javascript-grammar|ms-|0.0.53
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1711
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
vscode-paste-image|mus|1.0.4
vscode-json-editor|nic|0.2.3
syncing|non|3.0.13
angular-console|nrw|11.1.3
vscode-jest|Ort|3.1.1
vscode-versionlens|pfl|0.25.0
markdown-checkbox|PKi|1.6.0
material-icon-theme|PKi|4.0.1
psi-header|psi|1.9.1
java|red|0.58.0
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
code-eol|soh|0.3.3
sonarlint-vscode|Son|1.15.0
guides|spy|0.9.3
vscode-odata|sta|0.1.0
shell-launcher|Tyr|0.4.1
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.6
vscode-svg-previewer|vit|0.5.1
vscode-java-debug|vsc|0.25.1
change-case|wma|1.0.0
poor-sql-formatter|WSR|0.1.0
local-history|xyz|1.8.1
vscode-surround|yat|1.0.2

</details>

**Comment by dlucazeau** [comment] 2020-03-10 10:34
It is the same bug reappeared in VSCode Insiders but new in VSCode

**Comment by babakks** [comment] 2020-03-10 11:41
I'm seeing such strange things, too. When I open VS Code Insiders or even open a new window, the line in `settings.json` where it set the icons theme, just disappears and file icons reset to default. The only new thing I tried today, was enabling the brand new auto sync feature. Now, even if I disable it, the problem still exists.

**Comment by wilson-weets** [comment] 2020-03-11 07:35
Hi, I have the same problem. Hope it will be fixed soon.

**Comment by sandy081** [comment] 2020-03-11 16:28
@babakks Your issue seems unrelated, please file a separate one.

**Comment by sandy081** [comment] 2020-03-11 16:32
Can you please try by disabling all installed extensions and only have one extension that contributes to activity bar?

**Comment by wilson-weets** [comment] 2020-03-20 12:46
Here's a screenshot of my problem. I have uninstalled all other icon extensions. There's only one left.

![image](https://user-images.githubusercontent.com/26062231/77164714-258d6300-6ab1-11ea-8b44-bda3176965fc.png)

**Comment by sandy081** [comment] 2020-03-27 06:50
@wilson-weets Which is that one extension and looks like you are not seeing that icon too?

**Comment by sandy081** [comment] 2020-03-27 06:52
- Does it reproduce if you reload the window?
- Can you please try using fresh user data dir. Start code from command line as follows
`code --user-data-dir <path to a temp user data dir>`
- Open Developer tools (Developer: Toggle Developer Tools). Go to elements tab and inspect the element. Let me know where the icons are located. See eg:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/10746682/77729242-772c7500-6ffe-11ea-8fb3-3c9205e65062.png">

**Comment by wilson-weets** [comment] 2020-03-27 07:53
Hi. Thanks a lot for taking care of this with me.

- A reload didn't do anything.
- Creating a temp user folder worked. So I imagine the problem comes from my user-data folder. Is there a way I can use the new one without losing all my user data?
- I looked and the icons are there :
![image](https://user-images.githubusercontent.com/26062231/77734155-76004580-7008-11ea-97b9-364eba747511.png)


Thanks again.

**Comment by sandy081** [comment] 2020-03-27 09:18
These are file icons.  Assigning to @aeschli

**Comment by aeschli** [comment] 2020-03-27 13:56
@wilson-weets Can you open the dev tools network tab, reload and see if the icons are loaded?

**Comment by wilson-weets** [comment] 2020-03-27 14:46
Here you go :

![image](https://user-images.githubusercontent.com/26062231/77767705-bf20bb80-7041-11ea-9dcf-6aee135dfbac.png)

It seems to be my user-data dir that contains something bad. Maybe I could export my config and extensions, delete this directory, and import back my settings. 

A side effect of these icons not display is the icons of the git interface are broken too : 
![image](https://user-images.githubusercontent.com/26062231/77767931-1161dc80-7042-11ea-977e-4e64e850891b.png)

**Comment by aeschli** [comment] 2020-03-27 15:26
I wonder whether the browser really tries to get the image or just serves it from a corrupt cache. Any information on the 'Headers' and 'Response' tab in the Network tab?

**Comment by wilson-weets** [comment] 2020-03-27 15:30
Seems to be nothing in the headers :
![image](https://user-images.githubusercontent.com/26062231/77772298-2fcad680-7048-11ea-81f2-ff00a4e551f1.png)

And no data in the response :
![image](https://user-images.githubusercontent.com/26062231/77772343-42451000-7048-11ea-9076-4720539d2c30.png)

Here's the console, just in case :
![image](https://user-images.githubusercontent.com/26062231/77772377-5426b300-7048-11ea-8bbf-6cbcdf2abea5.png)

**Comment by sandy081** [comment] 2020-03-31 19:10
@deepak1556 is there a way to remove or reset the browser cache so that we can validate if this is browser caching issue or not?

**Comment by deepak1556** [comment] 2020-03-31 20:56
@sandy081 the image caches is located under `<user-data-dir>/Cache` you can remove that directory to start from a clean state. But if you know which specific asset to reset for then use this tool https://github.com/felixrieseberg/chrome-cachetool#usage-node-module

**Comment by sandy081** [comment] 2020-04-01 08:01
@wilson-weets Can you please try above suggestion?

**Comment by dlucazeau** [comment] 2020-04-01 08:43
Where is user-data-dir on win10 ? Is this directory shared between two versions of VSCode ? Because: 
_VSCode Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363_
works fine and not the latest.

**Comment by sandy081** [comment] 2020-04-01 08:55
> Where is user-data-dir

user settings.json file is located in `<user-data-dir>/User`. You can find this by opening user settings.json file.

**Comment by dlucazeau** [comment] 2020-04-01 15:57
So this is the directory between versions. Why old version are working fine and not the latest ?

**Comment by sandy081** [comment] 2020-04-01 16:20
No idea that is what we are trying to figure out. Could be due to any change.

**Comment by dlucazeau** [comment] 2020-04-02 06:54
This bug has already been fixed in Insiders #88814, and it returned both in Insiders and in the standard version. VSCode becomes absolutely unusable on Windows.

**Comment by sandy081** [comment] 2020-04-02 11:39
@dlucazeau I don't think they are same. They are multiple issues being discussed here. 

- One is activity bar icons
- Second is file icons

If you are seeing missing activity bar icons please provide following information as requested earlier, it is difficult to understand the root cause without getting info

- Open Developer tools (Developer: Toggle Developer Tools). Go to elements tab and inspect the element. Let me know where the icons are located. See eg:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/10746682/77729242-772c7500-6ffe-11ea-8fb3-3c9205e65062.png">

I want to know where the missing icon is located and see if that missing activity bar icon exists in the location or not

**Comment by dlucazeau** [comment] 2020-04-02 12:19
In the bug @88814 you can see that icons are not visible on file explorer and on activity bar.
Here is a screenshot of VSCode Insiders. For my work I need to use VSCode 1.42.
![image](https://user-images.githubusercontent.com/4538922/78248382-d30a6880-74ec-11ea-8bdc-187fca4f7610.png)
If I open the SVG file in a viewer, the icon is well drawn

**Comment by sandy081** [comment] 2020-04-02 14:43
> In the bug @88814 you can see that icons are not visible on file explorer and on activity bar.

I saw #88814 again and it is only for activity bar icons. At that time there was a change that broke this and I fixed it immediately. That bug was never rolled out to stable. So, this is not same as the that.

Can you please check that if the icon at this location exists or not?

<img width="539" alt="image" src="https://user-images.githubusercontent.com/10746682/78262505-f212f580-7500-11ea-8d6b-5516172ece58.png">

If so, I would suspect this is a chrome caching issue and try what @deepak1556 suggested [here](https://github.com/microsoft/vscode/issues/92323#issuecomment-606870520)

**Comment by dlucazeau** [comment] 2020-04-02 15:10
I have deleted the Cache for VSCode insiders and I don't have icons shown for extensions

**Comment by sandy081** [comment] 2020-04-06 09:41
@dlucazeau Did you check this?

> Can you please check that if the icon at this location exists or not?

**Comment by dlucazeau** [comment] 2020-04-06 09:54
I don't know how can I say that the icon exists, I have told you "If I open the SVG file in a viewer, the icon is well drawn" https://github.com/microsoft/vscode/issues/92323#issuecomment-607811531

**Comment by sandy081** [comment] 2020-04-06 10:19
Thanks for confirmation.

Can you please open network tab and check what is being returned for this svg file?

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10746682/78548278-d3fb0d00-7800-11ea-848d-1c6497529420.png">

**Comment by dlucazeau** [comment] 2020-04-06 11:56
All GitLens icons have a bad content-header:
![image](https://user-images.githubusercontent.com/4538922/78555926-54743a80-780e-11ea-8dd1-ed360d7dd54c.png)
![image](https://user-images.githubusercontent.com/4538922/78555947-5a6a1b80-780e-11ea-8503-939bd619043c.png)

**Comment by sandy081** [comment] 2020-04-06 15:49
Looks that is the cause of the issue.

@deepak1556 @bpasero  any insights?

**Comment by deepak1556** [comment] 2020-04-06 21:24
Mime type of `.svg` is deduced in a way, if the OS has a preferred custom type for the file extension then it will be used before trying the default type from the browser. The custom type in this case seems to be coming from the OS.

@dlucazeau can you try loading the `.svg` file in question from chrome browser on your OS ? If it fails to load then you will have to check the windows registry if the mime type is overriden and fix that.

**Comment by bpasero** [comment] 2020-04-07 07:03
@deepak1556 @sandy081 just fyi we seem to be doing some SVG blocking in the main process, not sure that is relevant here:

https://github.com/microsoft/vscode/blob/f24a7ba4c732565316d5b3b07ef62242a5ec9f81/src/vs/code/electron-main/window.ts#L389-L410

//cc @joaomoreno

**Comment by deepak1556** [comment] 2020-04-07 07:12
@bpasero thats interesting, would be good to know why we do it.

But if the request is block according to the handler then the response wouldn't be `200` , per https://github.com/microsoft/vscode/issues/92323#issuecomment-609748898 they are served with invalid mime type, hence I doubt its coming from the OS.

**Comment by dlucazeau** [comment] 2020-04-07 07:21
Yes it fails. The file is downloaded. Why do I have to change the mime type of .svg files ? I use The Gimp.

**Comment by deepak1556** [comment] 2020-04-07 07:28
> Why do I have to change the mime type of .svg files ? I use The Gimp.

I am not sure which application on your system changed it, best bet would be check the windows registry `HKEY_CLASSES_ROOT\.svg`

**Comment by dlucazeau** [comment] 2020-04-07 07:39
I deleted the entry .svg which referenced ConceptDraw and everything went back to normal. ConceptDraw was tested and uninstalled at least a year ago. The icons were perfectly visible with an earlier version of VSCode before the removal of this registry
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14: 45: 59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
and not visible with the most recent version.

Upgrading the registry works around a problem in VSCode.

**Comment by deepak1556** [comment] 2020-04-07 07:59
> The icons were perfectly visible with an earlier version of VSCode before the removal of this registry

Can you `Disable Cache` under `Network` tab in developer tools and reload the window in this older version. Does the icon still appear when system registry has the `ConceptDraw` entry ?

**Comment by dlucazeau** [comment] 2020-04-07 08:23
Sorry, I have deleted the registry entry and I am no able to recreate it, I have quickly (re-)installed the latest version of VSCode. The cache is already disabled and I hadn't change anything in dev tools. So I think the cache was disabled.

**Comment by sandy081** [comment] 2020-04-08 15:24
Thanks @deepak1556 

To summarise, this issue is happening because of the windows registry overriding the svg mime type.

@deepak1556 Do you think is there something to be done on our side or its an user side bug?

**Comment by dlucazeau** [comment] 2020-04-08 15:32
@sandy081 I believe since it depends on the version of VSCode.

**Comment by blindrood** [comment] 2020-04-08 16:04
I had entries at `HKEY_CLASSES_ROOT\.svg` that were leftovers from ConceptDraw installation. Deleting these and reloading vscode resolved my issues with missing icons

**Comment by deepak1556** [comment] 2020-04-08 16:06
> Do you think is there something to be done on our side or its an user side bug?

@sandy081 nope , this bug does not require intervention from our end, can be closed.

**Closed by deepak1556** 2020-04-08 16:06 UTC
Labels: needs more info, windows

**Comment by wilson-weets** [comment] 2020-04-10 06:36
> I had entries at `HKEY_CLASSES_ROOT\.svg` that were leftovers from ConceptDraw installation. Deleting these and reloading vscode resolved my issues with missing icons

This is the solution. I had exactly the same problem. Thanks a lot.
