### ISSUE TITLE
Failed to create terminal for task when running automatic tasks

### ISSUE THREAD

**Issue by nerdo** [Microsoft/vscode#70904] opened 2019-03-21 14:40 UTC
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

Automatic tasks seem to interfere with extensions that need to run tasks.

I use a PHPUnit extension (https://github.com/elonmallin/vscode-phpunit) and I find that whenever I launch a workspace that runs automatic tasks, the phpunit commands fail with an error message saying `Failed to create terminal for task phpunit: run`.

Turning off the automatic tasks seems to fix the issue.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by alexr00** [comment] 2019-03-21 17:31
This is duplicate of #70557. It should be fixed in insiders, and the fix should be available in the next release.

**Closed** 2019-03-21 17:31 UTC
Labels: *duplicate, tasks
