### ISSUE TITLE
代码智能提示自动导入功能出错！

### ISSUE THREAD

**Issue by ivedk123** [Microsoft/vscode#60234] opened 2018-10-09 04:16 UTC
Issue Type: <b>Bug</b>

更新前功能正常，更新后现象为：
输入代码后自动提示“从XXX自动导入XXX”，敲击回车后没有自动导入，反而将语句嵌入到了当前代码区域！
![image](https://user-images.githubusercontent.com/32889947/46646506-1d8f7b00-cbbd-11e8-9f64-0a92b0eb4a22.png)
![image](https://user-images.githubusercontent.com/32889947/46646513-284a1000-cbbd-11e8-9d61-d5b77baaada1.png)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2

</details>

**Comment by mjbvz** [comment] 2018-10-09 05:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/27317

**Closed by mjbvz** 2018-10-09 05:13 UTC
Labels: new release
