### ISSUE TITLE
Backslash in file path on mac

### ISSUE THREAD

**Issue by jakobhu** [Microsoft/vscode#70123] opened 2019-03-09 15:19 UTC
Issue Type: <b>Bug</b>

When trying to configure tasks (Terminal > Configure Tasks...) i get this message on MacOS:

Unable to open '.vscode\tasks.json': File not found (file:///Users/jakob/NMS/.vscode\tasks.json).
It looks like a microsoft style dir-separator - the file is there (at file:///Users/jakob/NMS/.vscode/tasks.json)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 17.7.0

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.3.0
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
csharp|ms-|1.17.1

**Comment by shiftgeist** [comment] 2019-03-09 15:59
The only difference is the ´\´, is this caused by vscode or did you enter the path `.vscode\tasks.json` somewhere?

**Comment by jakobhu** [comment] 2019-03-09 16:27
Where could i enter such path? FWIW - none of the files i have in .vscode contain a backslash

**Comment by jakobhu** [comment] 2019-03-09 17:22
I have two test projects, and "Configure Tasks..." used to work w/o said error prior to upgrading to 1.32.1 - but after upgrading VS code it stopped working (with no changes to my configurations). I'm guessing here that VS code recently modified how path joins work

**Comment by RaphaelMaschinsen** [comment] 2019-03-10 11:42
I have exactly the same issue, also on MacOs:

Unable to open '.vscode\tasks.json': File not found (file:///Users/raphael/Code/jajaja/.vscode\tasks.json).

Everything else works just fine. I just can't configure tasks.

Vscode: Version 1.32.1 (1.32.1)
MacOs: 10.13.6

**Comment by alexr00** [comment] 2019-03-11 11:09
Git bisect revealed this as the first bad commit https://github.com/Microsoft/vscode/commit/cb7261fc9cb6d60d4139e83a17f31770418ae070

**Comment by alexr00** [comment] 2019-03-11 14:15
Fixed in insiders by https://github.com/Microsoft/vscode/commit/b91ffcf44a87bf109b9b4a479818444b0894d5a8

**Closed** 2019-03-11 14:53 UTC
Labels: bug, candidate, new release, tasks
