### ISSUE TITLE
Set a default task for all files with given extension

### ISSUE THREAD

**Issue by desk7** [Microsoft/vscode#65891] opened 2019-01-01 23:32 UTC
As far as I know,  you have to add a task.json file in every project (for example in c++). I think that, especially for beginners or to build and run a single file, it will be very useful to set a default task.json for all files with a given extension - I mean - build and run task for .cpp files, another for .c files and so on. There is that feature in Geany, for example. In this way, after the first set-up, VSCode automatically could build the file you are working on and run the executable in the terminal. Without the necessity for project. But if you have specific need, you could set a specific task.

**Comment by alexr00** [comment] 2019-01-03 11:51
Duplicate of #1435

**Closed** 2019-01-03 11:52 UTC
Labels: *duplicate, tasks
