### ISSUE TITLE
Debug sessions can't be monitored across extension hosts

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#233184] opened 2024-11-06 10:52 UTC
Does this issue occur when all extensions are disabled?: No, but this removes all debuggers :)

- VS Code Version: 1.95.1
- OS Version: Windows

It seems that some debug session functionality can be implemented across extension hosts and some cannot.
e.g. `vscode.debug.onDidChangeActiveDebugSession` is successfully fired between hosts, however `vscode.debug.registerDebugAdapterTrackerFactory` does not work.

Steps to Reproduce:

1. Use a setup with a remote workspace (e.g. WSL on Windows)
2. Deploy a debugger extension into the workspace host
3. Deploy an extension in the ui/local host which listens to debug events

Observe that `debugAdapterTrackerFactory` does not work and I would expect to be able to listen to debug events.

This scenario has come about because we have a [browser-based debugger](https://marketplace.visualstudio.com/items?itemName=Arm.embedded-debug) which must run in the UI extension host and we have also developed a generic debug memory viewer to interact with different debuggers no matter where they are running (see https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/150).

If this isolation of debug events is by design, are there any patterns which could be employed to specify the memory extension is installed in the same host as the debugger bearing in mind the debugger could be in any host? I don't believe `extensionKind` is enough because this decision needs to be made at runtime.

**Comment by roblourens** [comment] 2024-11-06 23:55
Yeah, debug adapter trackers currently have to be in the same EH as the DA. https://github.com/microsoft/vscode/issues/196009 essentially covers this.

> generic debug memory viewer to interact with different debuggers no matter where they are running 

So it could work with debuggers in either EH? I don't think there's really a good solution for you right now. 

Just with the way debug adapters and debugging works, it wouldn't be straightforward to fix this, needs big changes to how debug adapters work in the EH.

Maybe a workaround would be to actually publish it as two extensions, one "ui" and one "workspace"? A bit weird but something like that might be a way out.

Closing as dupe of #196009

**Closed by roblourens** 2024-11-06 23:55 UTC

**Comment by thegecko** [comment] 2024-11-07 00:08
Ok, thanks.

Contrary to #196009, however, debug trackers do work in the UI EH (we use them) you just need your debugger there too!

**Comment by roblourens** [comment] 2024-11-07 00:27
Yeah, that's not called out in the OP but Connor's comment calls it out and I think that's behind the original issue
