### ISSUE TITLE
Inconsistent shortcut key translations in menu vs workbench

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4771] opened 2016-03-29 20:22 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10 / Ubuntu 15.10

Steps to Reproduce:
1. Change to another language, I used Spanish.
2. Hover over the Explorer/Search/Git/Debug icons on the left

Actual:
It is translating the shortcut word Shift. Elsewhere, such as the file menu, it is not translated.
![shortcuttranslation](https://cloud.githubusercontent.com/assets/12900364/14122547/14d6417c-f5b1-11e5-977f-6be5f05a23c5.png)

**Comment by dbaeumer** [comment] 2016-04-01 09:36
@johnliu2016 can you please forward to the translation team.

**Comment by johnliu2016** [comment] 2016-04-01 09:52
@dbaeumer forwarded to loc team

**Comment by dbaeumer** [comment] 2016-04-01 12:38
Thanks!

**Comment by johnliu2016** [comment] 2016-04-05 06:01
loc team says all instances of "Shift" are localized well, after all if we still see unlocalized "Shift", this probably implies localizability issue.
@vsccarl can you attach a s/s of the untranslated "Shift" of the file menu.

**Comment by vsccarl** [comment] 2016-04-06 19:09
@johnliu2016 
![untranslatedshift](https://cloud.githubusercontent.com/assets/12900364/14329410/14004c62-fbf0-11e5-8eb3-7c713f856444.JPG)

![untranslatedshift2](https://cloud.githubusercontent.com/assets/12900364/14329463/4e5d7ad8-fbf0-11e5-8cb2-2e7d6967f2f3.JPG)

![untranslatedshift3](https://cloud.githubusercontent.com/assets/12900364/14329469/548aaf16-fbf0-11e5-8cff-91daf62e0c9b.JPG)

![untranslatedshift4](https://cloud.githubusercontent.com/assets/12900364/14329473/581d4652-fbf0-11e5-8c26-142075167fa7.JPG)

**Comment by johnliu2016** [comment] 2016-04-07 06:24
@dbaeumer can you help understand the shortcut accelerator of key combination display on such main menu, we found no single matching case in loc files

**Comment by dbaeumer** [comment] 2016-04-07 08:16
@bpasero @alexandrudima  I looked at the code and it looks like the resolving of a key binding to a user presentable string is done in keytCodes.ts and none of the code there is externalized (ElectronAcceleratorLabelProvider). Is this in oversight ?

**Comment by bpasero** [comment] 2016-04-07 09:27
I do not think we control how Electron presents the key bindings in the menus.

**Comment by alexandrudima** [comment] 2016-04-07 10:53
ElectronAcceleratorLabelProvider correctly does not use nls localize because these strings are passed to electron which then parses them:

https://github.com/electron/electron/blob/e05804848f98959d63337aacd9047cd579c5b23f/atom/common/keyboard_util.cc#L86

```c++
// Return key code represented by |str|.
ui::KeyboardCode KeyboardCodeFromKeyIdentifier(const std::string& s,
                                               bool* shifted) {
  std::string str = base::ToLowerASCII(s);
  if (str == "ctrl" || str == "control") {
    return ui::VKEY_CONTROL;
  } else if (str == "super" || str == "cmd" || str == "command" ||
             str == "meta") {
    return ui::VKEY_COMMAND;
  } else if (str == "commandorcontrol" || str == "cmdorctrl") {
#if defined(OS_MACOSX)
    return ui::VKEY_COMMAND;
#else
    return ui::VKEY_CONTROL;
#endif
  } else if (str == "alt" || str == "option") {
    return ui::VKEY_MENU;
  } else if (str == "shift") {
    return ui::VKEY_SHIFT;
  }
```

it is then Electron that renders them in the top level menu without any control from our side.

**Comment by bpasero** [comment] 2016-04-07 11:47
I think we have to distinguish between Electron menu and hover: In the hover imho we can provide translated labels, for Electron we should follow up with them. I found https://github.com/electron/electron/issues/1632 though I cannot remember we talked to them about this?

**Comment by bpasero** [comment] 2016-04-08 05:20
I reopened https://github.com/electron/electron/issues/1632. I can reproduce the issue on Windows, but interestingly not on Linux.

**Comment by bpasero** [comment] 2018-08-17 05:43
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.

**Closed by bpasero** 2018-08-17 05:43 UTC
Labels: electron, i18n, upstream, workbench-menu
