### ISSUE TITLE
js/ts workspace symbol search only works if you have loaded a js/ts file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#11173] opened 2016-08-30 08:50 UTC
Testing #11106
Steps to Reproduce:

Set up:

```
"workbench.settings.openDefaultSettings": false,
"search.quickOpen.includeSymbols": true
```
1. Open a File say **editorStyles.ts** from VS Code dev
2. <kbd>cmd</kbd>+<kbd>p</kbd> search for **EditorStyleSettings**
3. Quick open shows the requested Symbol - Good
4. Open settings - <kbd>cmd</kbd>+<kbd>,</kbd>
5. **editorStyles.ts** and **Settings** are in two tabs in the same editor group. **Settings** is active
6. Reload the window
7. **editorStyles.ts** and **Settings** are in two tabs in the same editor group. **Settings** is active
8. Repeat Step 2 

Observed: No results for Symbol **EditorStyleSettings**

**Comment by bpasero** [comment] 2016-08-30 09:07
This is likely a TS issue where the TS file needs to be opened in order for the symbol search to work.

**Comment by sandy081** [comment] 2016-08-30 09:21
@bpasero TS file is open after reload but not active. Updated the steps to be more clear.

**Comment by bpasero** [comment] 2016-08-30 09:40
Yeah if the file is not loaded, the TS language service is likely not loaded either. Also adding @aeschli as owner of the "Open Symbol" provider that I am using.

**Comment by dbaeumer** [comment] 2016-08-30 10:49
Let me take the issue first and see if it is a TS issue. 

@sandy081 did you have another TS file open. The underlying problem is that TS wants to have a file for global symbols to determine the project. I take the active editor if a TS file. Otherwise I look at the open documents and take the first TS file which could be a simple test file.

**Comment by sandy081** [comment] 2016-08-30 12:44
@dbaeumer I have two files open

1. Settings file in an active tab
2. A TS file in another tab

**Comment by dbaeumer** [comment] 2016-09-01 12:48
The reason is that when the workbench reloads the TS file isn't actually loaded hence the TS extension isn't activated hence now workspace symbols can be computed.

@bpasero I think it makes perfect sense to not load the content of the TS file in the setup on startup. But may be we have to restore all files when global actions alike workspace symbols are executed to make sure that the extensions can participate in them. The user has the visual impression that the TS file is there since he sees the tab.

**Comment by bpasero** [comment] 2016-09-01 13:22
@dbaeumer I disagree with your proposal. If I am inside a TS project and I want to open symbols, I expect this to work also when no file is open. Why would I need to first open files to make this work? What if I am typically start my coding session with all editors closed? Is it not bad to ask a user to first open a file to get symbol search?

Besides, when I look at the code how we resolve symbols, we seem to have some kind of symbol provider registry (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/common/search.ts#L65) and I think TypeScript should participate if it detects that the workspace I am in uses TypeScript (@aeschli could maybe comment on that).

I am not sure if VS Code is the right owner of this issue or it should be moved to TypeScript. Thereby passing back to you to decide how to proceed.

**Comment by sandy081** [comment] 2016-09-01 13:55
Updated the description to be more clear that two tabs are in the same group. It means the ts file is not visible but only file name is.

**Comment by aeschli** [comment] 2016-09-01 15:03
Its been a while since I was involved. I think at the time we were eagerly activated everyone that could have any result
@jrieken Rewrote that using provider and might have spend more thoughts on this.

**Comment by dbaeumer** [comment] 2016-09-01 15:26
@bpasero agree and disagree. I think we should still do our best to load the TS extension as late as possible. So I thought about two alternatives on two be activated but both aren't very good. One "onCommand:workbench.action.showAllSymbols" and the other "workspaceContains:tsconfig.json". Both not very good and both might result in too eager loading. So I believe something is missing here in the workbench and the best thought I had were the open tabs. But agree not good either. 

Note: that this is totally independent of the fact that the tsserver needs a ts file to compute workspace symbols. In @sandy081 case the TS extension doesn't even get activated.

@alexandrudima do you have an idea how this could be described by an extension. May be we need something 'fast main' that gets loaded on start up and makes some of the decisions.

**Comment by alexandrudima** [comment] 2016-09-01 15:51
@dbaeumer It is uncool, but you could activate on `*` and do nothing except spy for when you need to **really** activate. But even that won't help you in this case? As there's no API to list the editor background not-loaded tabs?

**Comment by bpasero** [comment] 2016-09-02 05:33
> I think we should still do our best to load the TS extension as late as possible

If that is our principle, then we should not activate all language services from files that are opened in background tabs. Since people might have a large number of tabs open in the background (maybe without even noticing because tabs are disabled), it would cause a lot of activation right on startup. Whereas if we activate from "Open Symbols", we can move this activation out of the critical startup path.

I think what is missing in our APIs is some concept of a project setting where you can configure what kind of project you are working in. If you are working in a TypeScript project, the TS language should get activated when searching for symbols.

**Comment by jrieken** [comment] 2016-09-02 06:49
> I think what is missing in our APIs is some concept of a project setting where you can configure what kind of project you are working in. 

An instance of such a project file would then be `tsconfig` and (improved) activation event ala `workspaceContains:**/{tsconfig.json,jsconfig.json}`

**Comment by dbaeumer** [comment] 2016-09-02 07:35
My idea was not to load all files in tabs. Only if the users requests 'workspace wide' actions. 

>I think what is missing in our APIs is some concept of a project setting where you can configure what kind of project you are working in. If you are working in a TypeScript project, the TS language should get activated when searching for symbols.

Fully Agree and @alexandrudima and I discussed something similar yesterday.

**Comment by bpasero** [comment] 2016-09-02 07:55
I would start with `workspaceContains` activation for now even though it only supports top level files and then once file search is fast we can think about glob pattern support in `workspaceContains`.

**Comment by dbaeumer** [comment] 2016-11-15 21:31
@waderyan when you plan to fix this, please ping me. This will not be trivial since it requires quite some code changes.

**Comment by eamodio** [comment] 2018-03-26 03:14
Can this be fixed now that `workspaceContains` support glob patterns?

**Comment by mjbvz** [comment] 2020-04-24 07:58
#11026 Improved this. You no longer need to have a JS/TS file open for workspace symbol search to work and we can now search across all JS/TS projects you know about.

However we still require you open at least one JS/TS file for the search to work

**Comment by mjbvz** [comment] 2020-06-23 00:53
I thought more about the case where you have not opened any js/ts files yet

Loading a JS/TS project can be expensive and take time. if we try to activate the JS/TS extension whenever the user triggers a workspace symbol search, we could delay the results and cause extra load on the user's system

So for now, I think it's better to wait for the user to signal to us that they may be interested in viewing JS/TS workspace results. Opening any JS/TS file seems like a good signal

**Closed by mjbvz** 2020-06-23 00:53 UTC
Labels: feature-request, typescript

**Comment by eamodio** [comment] 2020-06-24 16:32
@mjbvz why isn't triggering a workspace symbol search not enough of a signal that I want to search across the workspace? To me, even if I have to wait, I will, because I want to find something across the workspace

**Comment by mjbvz** [comment] 2020-06-25 03:15
@eamodio Today cmd+T already only searches through opened TS projects. It does not aggressively open new projects. 

This is by design. Imagine I open the VS Code codebase and immediately hit cmd+T. In an ideal world, this would search through all TypeScript files. However implementing this would currently require loading like 20 TypeScript projects (core + all the extensions) which is going to take a long time and temporarily turn my computer into a space heater. It's not going to be a good experience. 

By closing this issue, what I'm is that right now we don't want to special case  "no TS files opened" and try to infer which projects to load. If we ever add a setting that forces workspace symbol search really search through all TS projects in your workspace, then we should revisit this
