### ISSUE TITLE
Regression: Emmet is broken

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#63010] opened 2018-11-13 09:51 UTC
Issue Type: <b>Bug</b>

I have just upgraded to the latest VS Code Insiders, and Emmet doesn't work anymore at all. 

VS Code version: Code - Insiders 1.30.0-insider (c72cb129f2a0b8117c9b01f3767026041d7d1d31, 2018-11-13T06:19:28.504Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (13.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
project-manager|ale|9.1.0
bracket-pair-colorizer|Coe|1.0.60
disableligatures|Coe|0.0.8
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
beautify|Hoo|1.4.7
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.11.0
stylelint|shi|0.46.1
vvs-theme-seti|Vla|1.0.0
vscode-todo-highlight|way|1.0.4
vscode-jumpy|wma|0.3.1

(2 theme extensions excluded)

</details>

**Comment by vvs** [comment] 2018-11-13 09:52
Here's what I see in the log:

```
log.ts:169   ERR Cannot find module 'vscode-emmet-helper': Error: Cannot find module 'vscode-emmet-helper'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:744:970)
	at Function.t.getExtensionPathIndex.then.o._load (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:447)
	at Function.t.getExtensionPathIndex.then.r._load (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:774)
	at Module.require (module.js:586:17)
	at n (x:\Soft\VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.defineProperty.value (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:51955)
	at n (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:313)
	at Object.t.getEmmetHelper (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:2682)
	at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:45851)
	at t.DefaultCompletionItemProvider.provideCompletionItems (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:45076)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:791
	at t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:93)
	at new Promise (<anonymous>)
	at Object.t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:61)
	at e.provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:750)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:911
	at e._withAdapter (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:549:554)
	at e.$provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:873)
	at t._doInvokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:963)
	at t._invokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:635)
	at t._receiveRequest (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:196)
	at t._receiveOneMessage (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:126)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:10
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:126:16
	at e.fire (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:127:466)
	at a (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:179:853)
	at Socket.n._socketDataListener (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:180:50)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
log.ts:169   ERR a.updateExtensionsPath is not a function: TypeError: a.updateExtensionsPath is not a function
	at c (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:2552)
	at Object.t.getEmmetHelper (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:2689)
	at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:45851)
	at t.DefaultCompletionItemProvider.provideCompletionItems (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:45076)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:791
	at t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:93)
	at new Promise (<anonymous>)
	at Object.t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:61)
	at e.provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:750)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:911
	at e._withAdapter (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:549:554)
	at e.$provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:873)
	at t._doInvokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:963)
	at t._invokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:635)
	at t._receiveRequest (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:196)
	at t._receiveOneMessage (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:126)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:10
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:126:16
	at e.fire (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:127:466)
	at a (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:179:853)
	at Socket.n._socketDataListener (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:180:50)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
log.ts:169   ERR f.extractAbbreviation is not a function: TypeError: f.extractAbbreviation is not a function
	at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:46280)
	at t.DefaultCompletionItemProvider.provideCompletionItems (x:\Soft\VS Code\resources\app\extensions\emmet\dist\extension.js:1:45076)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:791
	at t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:93)
	at new Promise (<anonymous>)
	at Object.t.asThenable (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:61)
	at e.provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:750)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:911
	at e._withAdapter (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:549:554)
	at e.$provideCompletionItems (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:873)
	at t._doInvokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:963)
	at t._invokeHandler (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:635)
	at t._receiveRequest (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:196)
	at t._receiveOneMessage (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:126)
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:10
	at x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:126:16
	at e.fire (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:127:466)
	at a (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:179:853)
	at Socket.n._socketDataListener (x:\Soft\VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:180:50)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by vvs** [comment] 2018-11-13 14:06
I've downloaded the latest VS Code installer and reinstalled just in case if the previous installation was broken. The same result, Emmet is non-functional.

**Comment by ramya-rao-a** [comment] 2018-11-14 02:58
/duplicate of #63033

I see this only in the latest Insiders, but not when running the code from the master branch.
So, lets wait and see if tomorrow's Insiders fixes this.

**Closed** 2018-11-14 02:58 UTC
Labels: *duplicate, insiders
