### ISSUE TITLE
Cannot write code in editor on new empty files

### ISSUE THREAD

**Issue by jacobi85** [Microsoft/vscode#26803] opened 2017-05-17 07:59 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (9843623452cbb9eea0c57e2ccc371b4d2c3c2d37, 2017-05-17T06:05:58.874Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|jsx|TwentyChung|0.0.1|
|file-templates|brpaz|1.1.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.15.0|
|auto-close-tag|formulahendry|0.4.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. Create a new file
2. Try to write code in editor on an empty file

**Comment by bpasero** [comment] 2017-05-17 08:55
@jacobi85 what happens if you try? can you share a video?

**Comment by alexandrudima** [comment] 2017-05-18 05:58
@jacobi85 Are you using a `window.zoomLevel` value that is <= 0 ?

This could be a duplicate of #26575

**Comment by alexandrudima** [comment] 2017-05-18 06:06
Let's track in #26575

**Closed by alexandrudima** 2017-05-18 06:06 UTC
Labels: editor-input, mac, needs more info
