### ISSUE TITLE
Scrolling extremely slow using precision touchpad 

### ISSUE THREAD

**Issue by jlouros** [Microsoft/vscode#30159] opened 2017-07-05 22:35 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.4|
|cake-vscode|cake-build|0.6.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|xml|DotJoshJohnson|1.9.2|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.16.0|
|vscode-npm-script|eg2|0.2.0|
|beautify|HookyQR|1.1.1|
|Angular2|johnpapa|2.3.3|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|3.1.6|
|vscode-docker|PeterJausovec|0.0.16|
|autoimport|steoates|1.2.2|
|cucumber|stevejpurves|0.9.6|;

---

Steps to Reproduce:

1. Use two finger gesture to scroll a document
2. Take 1-3 seconds to actually scroll

However, if I use a mouse (exactly on the same document) I can scroll without any issues.
Not sure if it's worth mentioning, but I'm using a Dell XPS 15 with a 4K display.

**Comment by warpdesign** [comment] 2017-07-10 19:32
I am having the same problem, on a Surface Book with latest Windows 10 (Creators Update).

It seems to lag from time to time: you perform a swipe up using two fingers, and sometimes there is a lag of 1-2 seconds before it actually scrolls.

There is no such problem on other apps: Edge, Chrome, etc.. all scroll fine with no lag at all.

This lag makes VSCode unusable on a Surface Book if you do not use an external mouse :(

**Comment by ivomachado** [comment] 2017-07-11 02:24
I'm having this issue too, in a Dell Inspiron 7348. I tried other Electron apps and the scroll was just fine.

**Comment by ivomachado** [comment] 2017-07-11 02:39
I opened VS Code with the flag `--disable-gpu` and the scroll was ok.

**Comment by mbiebusch** [comment] 2017-07-12 06:27
Happens on other devices, too. You might want to try WIN + UP and WIN + DOWN as well to "fix" the issue.

**Comment by EthanRutherford** [comment] 2017-07-17 19:59
Having the same issue. Resizing the window does temporarily alleviate the issue.

**Comment by GuusBaggen** [comment] 2017-08-07 10:33
Same issue here, same "work-around" here too. Also on Dell XPS 15 FHD.

**Comment by alexandrudima** [comment] 2017-08-08 14:12
Duplicate of #13612

And indeed, here is a confirmed workaround: https://github.com/Microsoft/vscode/wiki/Known-issues#-confirmed-workaround-reported-by-alexpaluzzi

**Closed by alexandrudima** 2017-08-08 14:12 UTC
