### ISSUE TITLE
Changes not showing after pulling from remote origin in source control

### ISSUE THREAD

**Issue by pinkido** [microsoft/vscode#112697] opened 2020-12-17 02:51 UTC
Issue Type: <b>Bug</b>

I try to pull from another branch of my remote repo and found out that it needs merging.Oddly there is a number of change files on the source control icon,but no changes are showing in the source control panel.Error logs show in console of developer tool.
![image](https://user-images.githubusercontent.com/21196140/102437662-e008c100-4055-11eb-8175-177f02d6ae91.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (6.19GB free)|
|Process Argv|--crash-reporter-id 62065dbc-b3bf-4b81-ba96-3988c78683fc|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icontheme-nomo-dark|be5|1.3.6
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.5.4
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
vscode-html-css|ecm|1.1.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
vscode-pull-request-github|Git|0.22.0
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.52.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-ssh-explorer|ms-|0.56.0
cpptools|ms-|1.1.3
debugger-for-chrome|msj|4.12.11
vsc-netease-music|non|0.0.40
vetur|oct|0.31.3
material-icon-theme|PKi|4.4.0
view-in-browser|qin|0.0.5
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.13
html5-boilerplate|sid|1.1.1
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt600cf:30237611
vsjup459:30237187

```

</details>

**Comment by pinkido** [comment] 2020-12-17 03:21
**error logs:**

  ERR Should never happen: Error: Should never happen
    at D.getRightResource (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:72819)
    at D.getResources (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:72101)
    at C.get resources (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:64113)
    at C.<anonymous> (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:23851)
    at C.get leftUri [as leftUri] (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:63944)
    at D.resolveChangeCommand (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:71651)
    at D.resolveDefaultCommand (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:71447)
    at C.get command [as command] (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:64040)
    at c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:479
    at Array.map (<anonymous>)
    at c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:261
    at Array.map (<anonymous>)
    at w._takeResourceStateSnapshot (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:234)
    at c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:611
    at Set.forEach (<anonymous>)
    at y.eventuallyUpdateResourceStates (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:589)
    at Timeout._onTimeout (c:\Users\36065\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:8:779)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by infinnie** [comment] 2020-12-22 03:47
Temporary solution here:
https://github.com/microsoft/vscode/issues/112717#issuecomment-749321371

Corresponding Git blame:
https://github.com/microsoft/vscode/blame/0c947cb4ee4a35f04aa6c5117a9727be35b3c828/extensions/git/src/repository.ts#L586

**Comment by eamodio** [comment] 2021-01-05 06:10
Duplicate of #112537 (which will be fixed in tomorrow's insiders)

**Closed by eamodio** 2021-01-05 06:10 UTC
