### ISSUE TITLE
Ignore changes confirmation  panel

### ISSUE THREAD

**Issue by akash-potdar7** [Microsoft/vscode#67556] opened 2019-01-30 15:36 UTC
Issue Type: <b>Bug</b>

I see the ignore changes and revert file changes panel confirm box opening twice.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-docker|Zim|0.34.0
vscode-eclipse-keybindings|alp|0.10.0
vue-peek|dar|1.0.2
dart-code|Dar|2.22.2
flutter|Dar|2.22.2
emulate|Die|0.0.7
githistory|don|0.4.4
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
docker-explorer|for|0.1.6
sass-lint|gle|1.0.4
vue-snippets|hol|0.1.11
python|ms-|2019.1.0
vetur|oct|0.14.5
vscode-docker|Pet|0.5.1
java|red|0.37.0
vscode-nginx|sha|0.6.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1

</details>

**Comment by joaomoreno** [comment] 2019-01-31 07:59
Possibly duplicate of https://github.com/Microsoft/vscode/issues/65959

Can you reproduce with out our [insider release](https://code.visualstudio.com/insiders)?

**Closed** 2019-02-07 12:29 UTC
Labels: needs more info
