### ISSUE TITLE
terminal.integrated.inheritEnv breaks integrated terminal

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode#76542] opened 2019-07-03 21:08 UTC
Issue Type: <b>Bug</b>

1. Add `"terminal.integrated.inheritEnv": false` to settings.json
2. Try to open terminal
3. Terminal blinks and can't do anything

![Screen record from 2019-07-03 14 44 16](https://user-images.githubusercontent.com/7832163/60623901-2191a780-9da1-11e9-9071-be3390f4183c.gif)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: elementary OS 5.0 Juno (Ubuntu 18.04.2 LTS), Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz (4 x 3454)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.28GB (4.55GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by teohhanhui** [comment] 2019-07-04 16:10
Same problem. I see this in output of `Log (Window)`:

> [2019-07-04 18:06:11.943] [renderer1] [error] A system error occurred (EACCES: permission denied, open '/proc/2194/environ'): Error: EACCES: permission denied, open '/proc/2194/environ'

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.8-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.45GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
latte|Kas|0.1.1
vscode-paste-and-indent|Rub|0.0.8
cucumberautocomplete|ale|2.14.0
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|29.2.0
vsc-material-theme-icons|equ|1.0.6
varnish-vcl|flo|0.1.3
vscode-pull-request-github|Git|0.8.0
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
restructuredtext|lex|110.0.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
vscode-yaml|red|0.4.1
vscode-qt-for-python|sea|0.3.0
gitconfig|sid|2.0.0
shellcheck|tim|0.6.0
twig|wha|1.0.2


</details>

**Comment by teohhanhui** [comment] 2019-07-04 16:34
Investigating further, could it be related to this? https://superuser.com/questions/842155/what-is-the-policy-for-permissions-on-proc-pid-environ

    $ cat /proc/sys/fs/suid_dumpable
    0

**Comment by gandroz** [comment] 2019-10-10 19:18
On Ubuntu 18.04, I installed VSCode with snap. When I launch VSC inside a terminal with 
```> /snap/bin/code```
I am able to work in the VSC terminal whatever the `terminal.integrated.inheritEnv` settings, but when I launch it with the `.desktop` link, if the settings is at `false` I got the issue of a blank terminal.

**Comment by teohhanhui** [comment] 2019-10-11 14:24
For whatever reason, I'm no longer able to reproduce this bug.

`"terminal.integrated.inheritEnv": false` seems to work perfectly for me now.

**Comment by gandroz** [comment] 2019-10-11 14:30
> For whatever reason, I'm no longer able to reproduce this bug.
> 
> `"terminal.integrated.inheritEnv": false` seems to work perfectly for me now.

not for me (even with the 1.39.1 version)

**Comment by GammaGames** [comment] 2019-10-11 14:34
I also still get the issue, though I'm using the deb

**Comment by astrowonk** [comment] 2019-10-11 18:10
"terminal.integrated.inheritEnv": false 

produced the blank terminal window that the above mention for me on RHEL, VS Code 1.39.1. Log Window shows the same error as mentioned earlier:

```A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'
```

**Comment by creeper121386** [comment] 2019-11-06 09:45
I got this problem after once running `sudo code --user-data-dir`
and after that I always get this bug when I launch vscode in normal way (without `sudo`)...

**Comment by tufei** [comment] 2019-11-14 17:34
Same here with the latest 1.40.1 on amd64 Ubuntu 16.04.

I used '--user-data-dir'. Only adding '--verbose' make the integrated terminal work.

"terminal.integrated.inheritEnv": false

**Comment by teichert** [comment] 2020-01-01 22:32
Several issues have been marked as duplicates of this, so I'm adding a comment here rather than opening a new issue.  I am using vscode 1.41.1 on Ubuntu 18.4 (gnome).

I had the same symptoms and log error message as described here and elsewhere (although in my case and other linked issues, the cursor was not blinking in my terminal). Specifically: non-working integrated terminal despite attempting to set the default shell or open additional terminals.
In addition, attempting to run the debugger on a python file resulted in a popup window saying simply "timeout".

However, since I wasn't using "inheritEnv" in my settings.json, the recommended workarounds didn't apply. (and so maybe I should have opened a separate issue)

In attempting to check the log messages, I ran code from a bash terminal "code --log trace", but no longer had the bad symptoms.  I discovered the bad symptoms for me only happen when I run code using a custom keyboard shortcut I made for gnome (I was able to log the error messages, by changing the command associated with the shortcut).

So, for me, the failed debugging and failed integrated terminal were fixed by opening vscode from the command-line rather than via a gnome keyboard shortcut.

**Comment by norru** [comment] 2020-01-22 11:01
Reproduced in Ubuntu 18.04, .deb Version: 1.9.1-1486597190

**Comment by martinlbrook** [comment] 2020-01-23 15:27
As others have mentioned, this issue doesn't seem to happen if you run code from the terminal. Therefore I found a simple workaround in modifying my menu entry (via menulibre) to enable the "run in terminal" option.

(Also FWIW #83100 seems like another duplicate of this - just mentioning it here so that this issue gets linked there).

**Comment by norru** [comment] 2020-01-23 15:30
@martinlbrook I am running from the terminal and the problem occurs anyway.

**Comment by dre2004** [comment] 2020-02-02 12:59
`Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic`

I also run it from the terminal, usually doing a `code .` in a project directory.

It started happening to me today, I ticked this option and it started working
![image](https://user-images.githubusercontent.com/29732449/73608497-c9ad6e80-4617-11ea-9ae0-88f78f3bda33.png)

**Comment by cyogian** [comment] 2020-02-21 18:08
A system error occurred (EACCES: permission denied, open '/proc/1598/environ'): Error: EACCES: permission denied, open '/proc/1598/environ'

In fedora:
 1. Just go to settings > user
 2. Search  terminal.integrated.inheritEnv
 3. Check it to enable it.  

For some reason it is not enabled by default and that is preventing the Terminal from running.

**Comment by vhquang** [comment] 2020-04-27 04:13
The reason Inherit Env isn't enable by default is probably this:
https://github.com/microsoft/vscode-python/issues/7607
(ie: to make it more compatible with conda)
I can confirm it happens for version 1.44.2, with both gnome-shortcut and terminal. Temporary fix for me is enable it, since my particular project does not care about it. But that is just a workaround.

**Comment by brando90** [comment] 2020-04-27 18:39
Slightly noob question (but it will make this gitissue more self contained).

How does one change the `terminal.integrated.inheritEnv` value? What is the name of the json file for it?

I tried typing that in the command palette with no success. Help?

**Comment by rickstaa** [comment] 2020-09-29 10:56
I also experience this issue when my `settings.json` contains the `terminal.integrated.inheritEnv: False` flag. Like @martinlbrook mentioned this only happens if you use the desktop shortcut.

**Comment by danchaseCTS** [comment] 2020-10-23 18:58
For Windows, I tried to use this answer, as I had environment variables not being included, and that question was closed as a dup to this one. So I went to the setting in vscode, and it says "Terminal>Integrated:Inherit Env" is checked, but it says "This is not supported on Windows". 

So which is it? I know the variable list looks completely different than if I just launched CMD and typed "set". 

My use case is: "set NODE_OPTIONS=--max_old_space_size=8192" because in Angular I get an out-of-memory error when trying to build prod, and setting an environment variable tells Node to use a larger VM. This is supposed to be better in my situation than other proposed solutions, but I think I've fallen down a rabbit hole!

**Comment by jmp75** [comment] 2020-11-23 00:17
This issue (re)-appeared after an upgrade on a Debian Testing of VSCode to Version: 1.52.0-insider

Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
Date: 2020-11-20T07:26:12.345Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.0-2-amd64

Setting to 'true' appears to resolve it.

```json
"terminal.integrated.inheritEnv": true
```

**Comment by DanRunfola** [comment] 2020-12-01 12:33
Confirming this issue is still live on Ubuntu 18.04.

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-53-generic snap

**Comment by Tyriar** [comment] 2021-05-04 14:12
We are removing inheritEnv in v1.57 as we will behave like regular terminals now wrt the base environment

**Closed by Tyriar** 2021-05-04 14:12 UTC
Labels: bug, integrated-terminal, linux

**Comment by Tyriar** [comment] 2021-05-14 13:35
It's actually coming back, but it's using a new way of getting the environment that should not have this issue.
