### ISSUE TITLE
Expansion should not include space before paren

### ISSUE THREAD

**Issue by DanS** [microsoft/vscode#138213] opened 2021-11-30 21:27 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: macOS Big Sur version 11.6.1

Steps to Reproduce:
1. Inside .html file, inside <style> tag, type "gtc" and hit TAB
2. Observe it expands to: grid-template-columns: repeat ( );
Better if it expands to:     grid-template-columns: repeat( );
Because the repeat does not work correctly if the space is allowed to remain there.

**Comment by rzhao271** [comment] 2021-11-30 22:14
Duplicate of https://github.com/microsoft/vscode/issues/117648
There's already an upstream PR for it, but it's not merged yet.
https://github.com/emmetio/emmet/issues/647

**Closed by rzhao271** 2021-11-30 22:14 UTC
