### ISSUE TITLE
Sync Settings and Plugins To The Cloud

### ISSUE THREAD

**Issue by timkofu** [microsoft/vscode#83431] opened 2019-10-28 13:23 UTC
First of all, thank you for creating such a great code editor and making it available freely.

Would it be possible to add a feature that allows sync of settings and plugins to Google Drive or Dropbox? It would automatically sync, and on a fresh install, a login to the cloud storage would pull down the settings and install all plugins.

Thank you.

**Comment by IllusionMH** [comment] 2019-10-28 15:57
/duplicate of #2743

In the meantime you can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

As for custom storage - it should be checked if already requested and in tracked issue. However it feels like custom storages are candidate for an extension.

**Closed** 2019-10-28 15:57 UTC
Labels: *duplicate

**Comment by timkofu** [comment] 2019-10-28 17:22
@IllusionMH Thanks.
