### ISSUE TITLE
"Go To Next Error" steals focus until esc is pressed

### ISSUE THREAD

**Issue by hesher** [Microsoft/vscode#25373] opened 2017-04-26 06:20 UTC
- VSCode Version: 1.12.0
- OS Version: MacOS

Steps to Reproduce:

1. Click F8 (Or whichever shortcut) to "Go To Next Error"
2. You would ideally be able to click shortcut for "quick fix" or type in to fix but you have to press ESC first to return focus to editor. That's an annoyance.

**Comment by jrieken** [comment] 2017-04-26 09:26
dupe of #18366

**Closed by jrieken** 2017-04-26 09:26 UTC
