### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Anuj-786** [microsoft/vscode#139506] opened 2021-12-20 10:15 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Proxy.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2339)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 3, 2|
|Memory (System)|7.69GB (0.22GB free)|
|Process Argv|--unity-launch --crash-reporter-id fd66da5f-3f55-4bbe-bbef-783d975ab6ea|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.9
atlascode|atl|2.10.1
vscode-multi-line-tricks|big|0.0.3
htmltagwrap|bra|0.0.7
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
pug-formatter|duc|0.6.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
vscode-peacock|joh|4.0.0
duplicateselection|kka|1.0.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.11.0
vscode-react-refactor|pla|1.1.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
code-spell-checker|str|2.0.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by IllusionMH** [comment] 2021-12-21 09:21
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

TS team needs a way to reproduce this issue. Please provide code that can help to reproduce this crash in issue linked above.

**Closed** 2021-12-21 09:21 UTC
Labels: *duplicate
