### ISSUE TITLE
editor.action.changeAll limited to only 999 selections

### ISSUE THREAD

**Issue by email2vimalraj** [Microsoft/vscode#36816] opened 2017-10-24 11:34 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 15.6.0

---

**Steps to Reproduce**:
1. Open a new file and add the same word 1000 times (may be you can use Emmet extension to do this quickly, for ex: div*1000 and tab, will produce <div></div> 1000 times)
2. Select the 1st word and press ⌘F2 or execute `editor.action.changeAll`

**Expected Result**:
All the 1000 matching words should be selected

**Actual Result**: 
Only 999 matching words are selected

**Reproduces without extensions**: Yes

**Comment by email2vimalraj** [comment] 2017-10-24 11:39
It look like there is already one issue #5887 opened and closed. Not clear whether the issue got fixed or not. Seems this issue exists from `1.0.0.1

**Comment by alexandrudima** [comment] 2017-10-25 10:53
Duplicate of #5887

The fix is available on the Insiders Release Channel and will be shipped with 1.18 on the Stable Release Channel.

**Closed by alexandrudima** 2017-10-25 10:53 UTC
Labels: editor

**Comment by email2vimalraj** [comment] 2017-10-25 11:01
Thanks for confirming.
