### ISSUE TITLE
Show TS/JS File and Folder Suggestions using Trigger Characters

### ISSUE THREAD

**Issue by ndkcha** [Microsoft/vscode#21543] opened 2017-02-28 07:12 UTC
- VSCode Version: 1.9.1
- OS Version: macOS Sierra (10.12.3)

Steps to Reproduce:

1. Open folder (containing the angular2 app)
2. Write import statement and refer to path. It should suggest the path based on directory structure.

Image:

<img width="1280" alt="screen shot 2017-02-28 at 12 33 40 pm" src="https://cloud.githubusercontent.com/assets/8328240/23395103/e11fb024-fdb2-11e6-9037-06e23a39e05f.png">

**Comment by mjbvz** [comment] 2017-02-28 19:01
This should work. Can you please share your tsconfig.json and a small example project that demonstrates this issue

**Comment by ndkcha** [comment] 2017-03-01 06:39
I have created a repository containing a code where i encountered with the issue. You can find the [repository here](https://github.com/ndkcha/vscode-issue/tree/issue-21543). 
My [tsconfig.json](https://github.com/ndkcha/vscode-issue/blob/issue-21543/tsconfig.json) file.
I have commented on a specific file to elaborate the issue. You can it [here](https://github.com/ndkcha/vscode-issue/blob/issue-21543/src/app/user/user.component.ts).

I hope this helps.

**Comment by mjbvz** [comment] 2017-03-04 00:10
Thanks. So to be clear, the issue is not that directory/files suggestions are never shown, but that they are not shown when you type `/` in the import path? 

As a workaround, you can trigger quick suggestions manually with <kbd>ctrl</kbd><kbd>space</kbd>

**Comment by ndkcha** [comment] 2017-03-04 03:35
yes.
okay. thanks! 👍

**Comment by Aetherall** [comment] 2017-09-19 07:16
Is it possible to show first the files in which the variable exported matches the one imported?

something like

   import { AwesomeClass } from ' 
/_____________________________________________________\\
| => - "../../fileExportingAwesomeClass.js"                                            
| => - "../../../anotherFileExportingAwesomeClass.js"                            
| => - "packagenameFromNodeModulesExportingAwesomeClass"     
| [... rest]

**Comment by mjbvz** [comment] 2017-09-22 22:36
Fixed by 5ec101edadf162169b5cbd79a3a3b1d5aacc777a

**Closed by mjbvz** 2017-09-22 22:36 UTC
Labels: bug, feature-request, javascript, plan-item, suggest, typescript
