### ISSUE TITLE
Can't search in file for a new line using '\n'

### ISSUE THREAD

**Issue by robsonrosa** [Microsoft/vscode#49287] opened 2018-05-06 00:36 UTC
- VSCode Version: 1.23.0
- OS Version: Microsoft Windows 10 Enterprise

Steps to Reproduce:

1. Open "SEARCH" (find in files) 
2. Activate the regular expression search
3. Type anything with "\n"
4. An error will be shown: "Literal '\n' not allowed."

I can search in files using regular expression and a new line search. But the same search works fine when I use "Find" in the current file.

![image](https://user-images.githubusercontent.com/2868031/39668721-53b82b78-50ac-11e8-80f4-1bf6aeaea0c3.png)

**Comment by rebornix** [comment] 2018-05-07 02:47
Duplicate of https://github.com/Microsoft/vscode/issues/43212

**Closed by rebornix** 2018-05-07 02:47 UTC
Labels: new release
