### ISSUE TITLE
Autocomplete on HTML element selector adds double colon

### ISSUE THREAD

**Issue by adamhammes** [Microsoft/vscode#16132] opened 2016-11-28 06:41 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro (version 1607, OS build 14393.447)

Steps to Reproduce:

1. Start typing "a:hov"
2. Autocomplete for "a:hover" will show up
3. Press enter to accept
4. The resulting text is now "a::hover" (should be "a:hover")

**Comment by adamhammes** [comment] 2016-11-28 06:42
Screenshot: http://recordit.co/vh31kIkfNE

**Comment by aeschli** [comment] 2016-11-28 16:07
duplicate of #14161

**Closed by aeschli** 2016-11-28 16:07 UTC
