### ISSUE TITLE
Autoformat sometimes breaks javascript code in html files

### ISSUE THREAD

**Issue by Tim86** [Microsoft/vscode#20124] opened 2017-02-07 15:06 UTC
- VSCode Version: 1.9.0
![image](https://cloud.githubusercontent.com/assets/724211/22696398/200a9a94-ed4e-11e6-87b8-db64623ac144.png)

- OS Version: 6.3.9600
![image](https://cloud.githubusercontent.com/assets/724211/22696557/b83031e4-ed4e-11e6-90d1-21bcc554fc17.png)

Steps to Reproduce:

1. Open a **html** file which contains a ```<style></style>``` block
1. Use the autoformat (```Shift + Alt + F```) 
1. The javascript code gets wrongly formatted or even breaks sometimes
#### Before autoformat 
![image](https://cloud.githubusercontent.com/assets/724211/22696644/16f6ea10-ed4f-11e6-89c6-079e85ec6232.png)
#### After autoformat
![image](https://cloud.githubusercontent.com/assets/724211/22696441/4b4d31f8-ed4e-11e6-9405-631c6cb9b7be.png)

**Comment by Tim86** [comment] 2017-02-07 15:12
Seems to be the style block that messes things up, updated the issue.

**Comment by mjbvz** [comment] 2017-02-07 19:03
I believe this is a duplicate of  #19813

@aeschli Has a fix checked in to master and we plan on releasing a 1.9 recovery build with the fix as well

**Closed by mjbvz** 2017-02-07 19:03 UTC
Labels: duplicate
