### ISSUE TITLE
Interface Implementation (Stubbing Functionality)

### ISSUE THREAD

**Issue by napalm684** [Microsoft/vscode#17418] opened 2016-12-16 21:10 UTC
- VSCode Version: Any
- OS Version: Any

Feature Request:
Add the ability in TypeScript and other Object-Oriented languages to implement (stub out) an inherited interface automatically.

**Comment by mjbvz** [comment] 2016-12-16 22:26
Closing as duplicate of #7073

**Closed by mjbvz** 2016-12-16 22:26 UTC
Labels: duplicate, feature-request, typescript

**Comment by napalm684** [comment] 2016-12-17 02:31
Sorry for the dupe missed #7073
