### ISSUE TITLE
Git Diff not showing the diff

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#23906] opened 2017-04-05 00:30 UTC
- VSCode Version:Version 1.11.0-insider (1.11.0-insider) ce0277bf8e30329fddcba1b67f8ba7314c10c97e
- OS Version: 10.10

Steps to Reproduce:
Click the SCM icon, view list of changed files. Pick one. Then wait forever while watching the blue line move across the top over and over again. Never see the actual diff. This behavior began about a week ago. 

This is from the output screen:
Using git 2.5.4 (Apple Git-61) from /usr/bin/git
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git config --get commit.template
git status -z -u
git fetch

git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...gitlab/master
git for-each-ref --format %(refname) %(objectname)
git remote --verbose

**Comment by joaomoreno** [comment] 2017-04-06 09:35
Are you editing files in a network share?

**Comment by rhires** [comment] 2017-04-06 13:13
I am not. I'm not doing anything different than I've ever done. That's part of why this is a mystery. Not sure what else I could do to diagnose the issue or what other logging or information I could produce or look at to figure out what's going on.

**Comment by joaomoreno** [comment] 2017-04-07 13:11
Duplicate of #23977

**Closed by joaomoreno** 2017-04-07 13:11 UTC
Labels: needs more info
