### ISSUE TITLE
Sub-word navigation doesn't work as expected in all-caps words or word parts

### ISSUE THREAD

**Issue by Xjs** [Microsoft/vscode#53680] opened 2018-07-06 09:03 UTC
Issue Type: <b>Bug</b>

Navigate an all-caps word or a word with all-caps component.

Examples: `REMOTE_PREFIX` or `GetWebhookURL`. 

I would expect navigation to stop here:

```
REMOTE_PREFIX
^------^-----^

GetWebhookURL
^--^------^--^
```

Instead, the cursor stops between each of the capitalised letters when using the `cursorWordPartRight`/`cursorWordPartLeft` shortcuts.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v6 @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.2.0
bazel-code|Dev|0.1.9
gitlens|eam|8.4.1
python|ms-|2018.6.0
Go|ms-|0.6.84
angular2-inline|nat|0.0.17
vetur|oct|0.12.5
vscode-code-outline|pat|0.2.1
java|red|0.28.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
markdown-all-in-one|yzh|1.5.1
vscode-proto3|zxh|0.2.1

</details>

**Comment by dsanz006** [comment] 2018-07-06 09:07
Agree, in my opinion it should only stop on changes from lowercase to uppercase.

**Comment by LegoChicken** [comment] 2018-07-06 09:46
My defect #53685 is a duplicate of this

**Comment by Xjs** [comment] 2018-07-06 11:20
Forgot to mention: I'm a huge fan of the feature itself, too.

**Comment by V-ed** [comment] 2018-07-06 13:23
Duplicate of https://github.com/Microsoft/vscode/issues/53645

Although I find the formatting of this issue better than the one I linked haha

**Comment by dsanz006** [comment] 2018-07-10 14:02
Moreover, I just realised that sub-word navigation doesn't work on the search and replace text fields. I think it should, as "Ctrl+left" or "Ctrl+right" work perfectly.

**Comment by rbolsius** [comment] 2018-07-11 22:40
Also, the cursorWordPart and deleteWordPart commands should skip over multiple spaces instead of moving one space at a time.

**Comment by davidcoleman007** [comment] 2018-07-22 00:31
agreed.  +1 for the feature, but it really needs to properly follow `ALL_CAPS_SNAKE_CASE`.

**Comment by davidcoleman007** [comment] 2018-07-25 19:35
+1 for subword in other parts of IDE too!

especially for search! and also for filenames in the explorer pane!

**Comment by V-ed** [comment] 2018-07-25 19:41
@davidcoleman007 #53498

**Comment by alexandrudima** [comment] 2018-07-30 21:07
Duplicate of #53645

**Closed by alexandrudima** 2018-07-30 21:07 UTC
Labels: editor-subword
