### ISSUE TITLE
*Microsoft* CSS Extensions

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#144880] opened 2022-03-11 05:44 UTC
Hello @microsoft, Please Create a **CSS Extension** for :-

---

1. **Formatting**
1. **Intellisense** for Class's & ID's (Present in .html)
1. Some Most used **Snippets** like 

```
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box
}
etc.
```
4. Latest CSS **Features** Guide on Hover

**Comment by yume-chan** [comment] 2022-03-11 06:45
1. On iteration plan #144519, no tracking issue
2. Duplicate of #47331
3. Everyone needs different snippets, you can add your own
4. Can't understand

Always use one issue for each feature request.

**Comment by aeschli** [comment] 2022-03-11 08:14
CSS Formatter: https://github.com/microsoft/vscode/issues/19166

**Closed by aeschli** 2022-03-11 08:14 UTC
