### ISSUE TITLE
Terminal Suggest: Just prints a bunch of stuff to the console

### ISSUE THREAD

**Issue by lishaduck** [microsoft/vscode#224537] opened 2024-08-02 00:36 UTC
Type: <b>Bug</b>

Steps to Reproduce:

1. Enable `terminal.integrated.suggest.enabled`
2. The terminal spits out the following:

    ```pwsh
    PS C:\Users\elish> c'C:\\Program Files\\Android\\Android Studio\\jbr\\bin\\klist.exe'",2,"C:\\Program Files\\Android\\Android Studio\\jbr\\bin\\klist.exe"],["Boxstarter.Chocolatey\\Log-BoxstarterMessage",2,"\r\nLog-BoxstarterMessage \r\n"],["Boxstarter.Common\\Log-BoxstarterMessage",2,"\r\nLog-BoxstarterMessage \r\n"],["Boxstarter.HyperV\\Log-BoxstarterMessage",2,"\r\nLog-BoxstarterMessage \r\n"],["Boxstarter.WinConfig\\Log-BoxstarterMessage",2,"\r\nLog-BoxstarterMessage \r\n"],["CimCmdlets\\ncim",2],["CimCmdlets\\ncms",2],["CimCmdlets\\ncso",2],["Boxstarter.HyperV\\New-BoxstarterPackage",2,"\r\nNew-BoxstarterPackage \r\n"],["Boxstarter.HyperV\\New-PackageFromScript",2,"\r\nNew-PackageFromScript \r\n"],["PowerShellGet\\New-ScriptFileInfo",2,"\r\nNew-ScriptFileInfo \r\n"],["C:\\WINDOWS\\notepad.exe",2],["Boxstarter.Chocolatey\\Out-BoxstarterLog",2,"\r\nOut-BoxstarterLog \r\n"],["Boxstarter.Common\\Out-BoxstarterLog",2,"\r\nOut-BoxstarterLog \r\n"],["Boxstarter.HyperV\\Out-BoxstarterLog",2,"\r\nOut-BoxstarterLog \r\n"],["Boxstarter.WinConfig\\Out-BoxstarterLog",2,"\r\nOut-BoxstarterLog \r\n"],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pip.exe",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pip3.10.exe",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pip3.exe",2],["PSReadLine\\PSConsoleHostReadLine",2,"\r\nPSConsoleHostReadLine \r\n"],["PowerShellGet\\Publish-Module",2,"\r\nPublish-Module \r\n"],["PowerShellGet\\Publish-Script",2,"\r\nPublish-Script \r\n"],["PowerShellGet\\pumo",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Launcher\\py.exe",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Python311\\python.exe",2],["C:\\Users\\elish\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Python311\\pythonw.exe",2],["C:\\Users\\elish\\AppData\\Local\\Programs\\Python\\Launcher\\pyw.exe",2],["C:\\tools\\ruby31\\bin\\racc.bat",2],["C:\\tools\\ruby31\\bin\\rake.bat",2],["C:\\tools\\ruby31\\bin\\rbs.bat",2],["CimCmdlets\\rcie",2],["CimCmdlets\\rcim",2],["CimCmdlets\\rcms",2],["C:\\tools\\ruby31\\bin\\rdoc.bat",2],["Boxstarter.HyperV\\Register-ChocolateyInterception",2,"\r\nRegister-ChocolateyInterception \r\n"],["PowerShellGet\\Register-PSRepository",2,"\r\nRegister-PSRepository \r\n"],["Boxstarter.Chocolatey\\Remove-BoxstarterError",2,"\r\nRemove-BoxstarterError \r\n"],["Boxstarter.Common\\Remove-BoxstarterError",2,"\r\nRemove-BoxstarterError \r\n"],["Boxstarter.HyperV\\Remove-BoxstarterError",2,"\r\nRemove-BoxstarterError \r\n"],["Boxstarter.WinConfig\\Remove-BoxstarterError",2,"\r\nRemove-BoxstarterError \r\n"],["Boxstarter.Chocolatey\\Remove-BoxstarterTask",2,"\r\nRemove-BoxstarterTask \r\n"],["Boxstarter.Common\\Remove-BoxstarterTask",2,"\r\nRemove-BoxstarterTask \r\n"],["Boxstarter.HyperV\\Remove-BoxstarterTask",2,"\r\nRemove-BoxstarterTask \r\n"],["Boxstarter.WinConfig\\Remove-BoxstarterTask",2,"\r\nRemove-BoxstarterTask \r\n"],["Defender\\Remove-MpPreference",2,"\r\nRemove-MpPreference \r\n"],["Defender\\Remove-MpThreat",2,"\r\nRemove-MpThreat \r\n"],["Boxstarter.HyperV\\Resolve-VMPlugin",2,"\r\nResolve-VMPlugin \r\n"],["C:\\tools\\ruby31\\bin\\ri.bat",2],["C:\\tools\\ruby31\\bin\\ridk.cmd",2],["C:\\tools\\ruby31\\bin\\ruby.exe",2],["C:\\tools\\ruby31\\bin\\rubyw.exe",2],["PowerShellGet\\Save-Module",2,"\r\nSave-Module \r\n"],["PowerShellGet\\Save-Script",2,"\r\nSave-Script \r\n"],["CimCmdlets\\scim",2],["Boxstarter.HyperV\\Set-BoxstarterConfig",2,"\r\nSet-BoxstarterConfig \r\n"],["Boxstarter.HyperV\\Set-BoxstarterShare",2,"\r\nSet-BoxstarterShare \r\n"],["oh-my-posh\\Set-CursorForRightBlockWrite",2,"\r\nSet-CursorForRightBlockWrite \r\n"],["oh-my-posh\\Set-CursorForRightBlockWrite",2,"\r\nSet-CursorForRightBlockWrite \r\n"],["oh-my-posh\\Set-CursorForRightBlockWrite",2,"\r\nSet-CursorForRightBlockWrite \r\n"],["oh-my-posh\\Set-CursorUp",2,"\r\nSet-CursorUp \r\n"],["oh-my-posh\\Set-CursorUp",2,"\r\nSet-CursorUp \r\n"],["oh-my-posh\\Set-CursorUp",2,"\r\nSet-CursorUp \r\n"],["PSDiagnostics\\Set-LogProperties",2,"\r\nSet-LogProperties \r\n"],["Defender\\Set-MpPreference",2,"\r\nSet-MpPreference \r\n"],["oh-my-posh\\Set-Newline",2,"\r\nSet-Newline \r\n"],["oh-my-posh\\Set-Newline",2,"\r\nSet-Newline \r\n"],["oh-my-posh\\Set-Newline",2,"\r\nSet-Newline \r\n"],["oh-my-posh\\Set-Prompt",2,"\r\nSet-Prompt \r\n"],["oh-my-posh\\Set-Prompt",2,"\r\nSet-Prompt \r\n"],["oh-my-posh\\Set-Prompt",2,"\r\nSet-Prompt \r\n"],["PowerShellGet\\Set-PSRepository",2,"\r\nSet-PSRepository \r\n"],["oh-my-posh\\Set-Theme",2,"\r\nSet-Theme \r\n"],["oh-my-posh\\Set-Theme",2,"\r\nSet-Theme \r\n"],["oh-my-posh\\Set-Theme",2,"\r\nSet-Theme \r\n"],["C:\\tools\\ruby31\\bin\\setrbvars.cmd",2],["oh-my-posh\\Show-Colors",2,"\r\nShow-Colors \r\n"],["oh-my-posh\\Show-Colors",2,"\r\nShow-Colors \r\n"],["oh-my-posh\\Show-Colors",2,"\r\nShow-Colors \r\n"],["oh-my-posh\\Show-ThemeColors",2,"\r\nShow-ThemeColors \r\n"],["oh-my-posh\\Show-ThemeColors",2,"\r\nShow-ThemeColors \r\n"],["oh-my-posh\\Show-ThemeColors",2,"\r\nShow-ThemeColors \r\n"],["oh-my-posh\\Show-ThemeSymbols",2,"\r\nShow-ThemeSymbols \r\n"],["oh-my-posh\\Show-ThemeSymbols",2,"\r\nShow-ThemeSymbols \r\n"],["oh-my-posh\\Show-ThemeSymbols",2,"\r\nShow-ThemeSymbols \r\n"],["SqlServer\\SQLSERVER:",2,"\r\nSQLSERVER: \r\n"],["SqlServer\\SQLSERVER:",2,"\r\nSQLSERVER: \r\n"],["Defender\\Start-MpScan",2,"\r\nStart-MpScan \r\n"],["Defender\\Start-MpWDOScan",2,"\r\nStart-MpWDOScan \r\n"],["Boxstarter.Chocolatey\\Start-TimedSection",2,"\r\nStart-TimedSection \r\n"],["Boxstarter.Common\\Start-TimedSection",2,"\r\nStart-TimedSection \r\n"],["Boxstarter.HyperV\\Start-TimedSection",2,"\r\nStart-TimedSection \r\n"],["Boxstarter.WinConfig\\Start-TimedSection",2,"\r\nStart-TimedSection \r\n"],["PSDiagnostics\\Start-Trace",2,"\r\nStart-Trace \r\n"],["Boxstarter.Chocolatey\\Stop-TimedSection",2,"\r\nStop-TimedSection \r\n"],["Boxstarter.Common\\Stop-TimedSection",2,"\r\nStop-TimedSection \r\n"],["Boxstarter.HyperV\\Stop-TimedSection",2,"\r\nStop-TimedSection \r\n"],["Boxstarter.WinConfig\\Stop-TimedSection",2,"\r\nStop-TimedSection \r\n"],["PSDiagnostics\\Stop-Trace",2,"\r\nStop-Trace \r\n"],["Boxstarter.Chocolatey\\Test-Admin",2,"\r\nTest-Admin \r\n"],["Boxstarter.Common\\Test-Admin",2,"\r\nTest-Admin \r\n"],["Boxstarter.HyperV\\Test-Admin",2,"\r\nTest-Admin \r\n"],["Boxstarter.WinConfig\\Test-Admin",2,"\r\nTest-Admin \r\n"],["oh-my-posh\\Test-Administrator",2,"\r\nTest-Administrator \r\n"],["oh-my-posh\\Test-Administrator",2,"\r\nTest-Administrator \r\n"],["oh-my-posh\\Test-Administrator",2,"\r\nTest-Administrator \r\n"],["oh-my-posh\\Test-NotDefaultUser",2,"\r\nTest-NotDefaultUser \r\n"],["oh-my-posh\\Test-NotDefaultUser",2,"\r\nTest-NotDefaultUser \r\n"],["oh-my-posh\\Test-NotDefaultUser",2,"\r\nTest-NotDefaultUser \r\n"],["PowerShellGet\\Test-ScriptFileInfo",2,"\r\nTest-ScriptFileInfo \r\n"],["oh-my-posh\\Test-VirtualEnv",2,"\r\nTest-VirtualEnv \r\n"],["oh-my-posh\\Test-VirtualEnv",2,"\r\nTest-VirtualEnv \r\n"],["oh-my-posh\\Test-VirtualEnv",2,"\r\nTest-VirtualEnv \r\n"],["C:\\tools\\ruby31\\bin\\typeprof.bat",2],["PowerShellGet\\Uninstall-Module",2,"\r\nUninstall-Module \r\n"],["PowerShellGet\\Uninstall-Script",2,"\r\nUninstall-Script \r\n"],["PowerShellGet\\Unregister-PSRepository",2,"\r\nUnregister-PSRepository \r\n"],["PowerShellGet\\Update-Module",2,"\r\nUpdate-Module \r\n"],["PowerShellGet\\Update-ModuleManifest",2,"\r\nUpdate-ModuleManifest \r\n"],["Defender\\Update-MpSignature",2,"\r\nUpdate-MpSignature \r\n"],["PowerShellGet\\Update-Script",2,"\r\nUpdate-Script \r\n"],["PowerShellGet\\Update-ScriptFileInfo",2,"\r\nUpdate-ScriptFileInfo \r\n"],["PowerShellGet\\upmo",2],["Boxstarter.Chocolatey\\Write-BoxstarterLogo",2,"\r\nWrite-BoxstarterLogo \r\n"],["Boxstarter.Common\\Write-BoxstarterLogo",2,"\r\nWrite-BoxstarterLogo \r\n"],["Boxstarter.HyperV\\Write-BoxstarterLogo",2,"\r\nWrite-BoxstarterLogo \r\n"],["Boxstarter.WinConfig\\Write-BoxstarterLogo",2,"\r\nWrite-BoxstarterLogo \r\n"],["Boxstarter.Chocolatey\\Write-BoxstarterMessage",2,"\r\nWrite-BoxstarterMessage \r\n"],["Boxstarter.Common\\Write-BoxstarterMessage",2,"\r\nWrite-BoxstarterMessage \r\n"],["Boxstarter.HyperV\\Write-BoxstarterMessage",2,"\r\nWrite-BoxstarterMessage \r\n"],["Boxstarter.WinConfig\\Write-BoxstarterMessage",2,"\r\nWrite-BoxstarterMessage \r\n"],["oh-my-posh\\Write-ColorPreview",2,"\r\nWrite-ColorPreview \r\n"],["oh-my-posh\\Write-ColorPreview",2,"\r\nWrite-ColorPreview \r\n"],["oh-my-posh\\Write-ColorPreview",2,"\r\nWrite-ColorPreview \r\n"],["Boxstarter.HyperV\\Write-HostOverride",2,"\r\nWrite-HostOverride \r\n"],["C:\\WINDOWS\\write.exe",2],["C:\\Users\\elish\\AppData\\Local\\Microsoft\\WindowsApps\\wsl.exe",2],["C:\\Users\\elish\\AppData\\Local\\Microsoft\\WindowsApps\\wslconfig.exe",2],["'C:\\Program Files (x86)\\Yarn\\bin\\yarn.cmd'",2,"C:\\Program Files (x86)\\Yarn\\bin\\yarn.cmd"],["'C:\\Program Files (x86)\\Yarn\\bin\\yarnpkg.cmd'",2,"C:\\Program Files (x86)\\Yarn\\bin\\yarnpkg.cmd"]cd .\AppData\Local\Programs\
    ```

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.04GB free)|
|Process Argv|--crash-reporter-id 46890a02-a7c4-4220-ada8-77aa2a7dde23|
|Screen Reader|no|
|VM|0%|
</details>

Reproduces without extensions ( `code --disable-extensions .`)

<details><summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplt:31103426
pythonrstrctxt:31103193

```

</details>

**Comment by Tyriar** [comment] 2024-08-02 19:10
This is probably because you're on a relatively old version of Windows. Chance are https://github.com/microsoft/vscode/issues/224488 will fix the problem

**Comment by lishaduck** [comment] 2024-08-02 23:52
> This is probably because you're on a relatively old version of Windows.

Is 10 considered old nowadays?

> Chance are #224488 will fix the problem

Thanks for all your hard work making VS Code the best editor around!

**Comment by ArrushC** [comment] 2024-08-10 09:31
I'm also encountering this issue, where the suggestion widget doesn't appear and some junk is printed to the console instead:
![image](https://github.com/user-attachments/assets/3c11ae2a-59a5-40a0-bf1b-11101fb98013)

This is occurring when running Visual Studio Code v1.92.1 (User Setup) and trying to type "cd" to invoke the suggestion widget.

**Comment by Tyriar** [comment] 2024-08-10 14:15
@lishaduck @ArrushC yes 10 is old, however if you're on insiders we just shipped a new experimental setting which may fix this problem for you `"terminal.integrated.experimental.windowsUseConptyDll": true`.

**Comment by ArrushC** [comment] 2024-08-10 20:51
@Tyriar just checked this experimental setting on my machine with insiders and it works perfectly! Hopefully this will be included in the next patch update. Thank you for your help 😃

**Comment by ArrushC** [comment] 2024-08-11 16:31
@Tyriar Just noticed a different issue that I would like to share:

On Windows 10, If you open a new PS session and from your cwd you use cd command to change to the root directory of the C drive, then typing `cd .` gives the following error:
![image](https://github.com/user-attachments/assets/8ac96d75-29e2-4ab3-8031-f6d4a6551dd9)

After hitting the enter key, this issue becomes non-reproducible.

**Comment by Tyriar** [comment] 2024-12-09 22:22
We're pivoting to a different extension-based approach for completions so what caused this will eventually go away.

**Closed by Tyriar** 2024-12-09 22:22 UTC
Labels: bug, windows, terminal-suggest
