### ISSUE TITLE
Uri provided to editor/title commands is always the Uri of the right side of a diff view, even if the left side is focused

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#59188] opened 2018-09-23 18:13 UTC
- VSCode Version: 1.28.0-insider
- OS Version: Windows 10 x64

Uri provided to editor/title commands is always the Uri of the right side of a diff view, even if the left side is focused

Steps to Reproduce:

1. Create an extension with a `editor/title` command registered with `commands.registerCommand`
1. Open a diff view (comparing 2 files, comparing git changes, etc) and move focus to the left side
2. Click on the `editor/title` command and observe that the `Uri` provided to the callback is from right side and not the left.

Originally reported here:
https://github.com/Microsoft/vscode/issues/22403#issuecomment-423747609

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment] 2018-09-24 09:09
I think this is actually working as intended. In a diff editor most commands target only the right hand side. We never update the editor actions when you switch focus between left or right hand side. Closing.

**Closed by bpasero** 2018-09-24 09:09 UTC
Labels: insiders
