### ISSUE TITLE
Copy All command is missing once toggle search view position

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#49637] opened 2018-05-10 18:20 UTC
- VSCode Version: Insiders
- OS Version: macOS and Ubuntu

Steps to Reproduce:

1. Search
2. Right Click on any result, Copy All command is there
3. Toggle Search View Position
4. Right Click, Copy All command is missing

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-05-30 04:37
This depends on #44491

**Comment by roblourens** [comment] 2018-09-13 18:16
Debugged a little more, I'm calling it a dupe of  #44491

**Closed by roblourens** 2018-09-13 18:16 UTC
Labels: bug, search
