### ISSUE TITLE
Allow to disable Windows fs.truncate() upon save through a setting

### ISSUE THREAD

**Issue by ianoel230982** [microsoft/vscode#73393] opened 2019-05-07 09:26 UTC
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:09.080Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 6.3.9600

I have recently updated VS code to the above version, from version 1.20.1. 
I have this strange problem that when i save javascript files and reload my web page the page has a javascript error, for example 'unexpected end of input', this then gives the line and file of the error in Chrome dev tools.
When i use Chrome dev tools to inspect the file with the error i can see that a small snippet from the end of my javascript appears to have been duplicated and popped in randomly afterwards.

I've pasted example code below.
This can happen in multiple files and it always appears that it is the last part of my javascript that is duplicated and stuck in at the end of the file.

If i close down VS Code and reopen it i can see the duplicate code in the .js file. If i remove this from the file and save, the web page still has the error. Re-opening VS Code again still shows the code in the file, despite me removing it.

I have tried disabling all the extensions i use and the issue still occurs.
If i roll back to version 1.20.1 the issue goes away.

I'm not entirely sure what the problem is.

If any further info is needed please let me know.

Thanks,
Ian.

```
function loadData(){

	var listName = "ListName";

	var call = $.ajax({
		url:   api endpoint goes here",        
		type: "GET",
		dataType: "json",
		headers: {
			Accept: "application/json;odata=verbose"
		}
	});
	
	call.done(function (data,textStatus, jqXHR){		


        console.log(data);
        
		var table = $('#elementID').dataTable({
			"bDestroy": true,
            "bProcessing": true,
			"responsive": true,            
			"aaData": data.d.results,
			"aoColumns": [			
            { "mData": "Name",
                "mRender": function (data, type, full){ 				
				   return some data here;
                },
            },

        ],
			"lengthMenu":[[10, 25, 50, -1], [10, 25, 50, "All"]],
			"order":['1', 'asc'],
			"columnDefs": [
                {              
                    "width": "10%", "targets": 2,
                }
            ],	

		});

	});
	call.fail(function (jqXHR,textStatus,errorThrown){
		alert("Error retrieving data: " + jqXHR.responseText);
	});
	
	
}
//START OF DUPLICATED CODE
 jqXHR.responseText);
	});
	
	
}
//END OF DUPLICATED CODE
```

**Comment by mjbvz** [comment] 2019-05-07 18:51
Are you sure this still happens you disabled all extensions? Also, can you please record this happening so that we can better see what exactly is going wrong

**Comment by mr-layco** [comment] 2019-05-07 19:08
Hi. From command prompt I ran code --disable-extensions and confirmed none were running. If you feel this may be a likely cause I'll certainly try it again.
When you say record this happening, do you mean capture a video of what is happening? If so, I'll try, as my company are super strict with downloading and installing software on our machines. Getting VSCode was hard enough 😊

**Comment by mjbvz** [comment] 2019-05-07 22:48
Thanks for checking.

It's difficult for me to understand exactly what is happening with the code from your description. If you cant record a video, can you take a screenshots of each step so that I can see what is going wrong more clearly.

**Comment by ianoel230982** [comment] 2019-05-08 08:56
Hi,

I've spent a few hours trying to figure out an exact cause of this issue but i cannot get it to repeat every single time, if it doesn't repeat, what happens instead is that the file looks like it has saved my changes, however when i go to the web browser the removed code is still there. I reload vs code and open the same js file and the code i'd previously removed is still there.

I'll also give you a little more info about my setup before i talk about the attached screen shots showing the issue directly.

I have vs code installed on my work laptop, this is connected to a company network. The files i am working with are stored on a SharePoint 2013 on premises environment within the company infrastructure. I access these files through File > Open Folder and navigating to the SharePoint site using a network path e.g. \\server name\site\site name. This then opens my folder tree and i can access my files through here.

So, i have attached 4 screen shots, all showing no extensions installed in VSCode.

1. Shows VSCode and google chrome dev tools open at the sources tab so you can see the code from the file being pulled from the server. The example shows a console.log on the bottom line of my js file in vscode. This is mirrored in the chrome dev tools. 

2. VSCode showing that i have removed the console.log and saved the file.

3. As mentioned previously, it took me a few attempts to reproduce the error (whilst battling with the issue of the file not updating mentioned above). Before getting it reproduced i had changed the text in my console.log
Note in line 955 of both VSCode and Chrome i have added a line of jQuery appending some text in the body.  The end of the file in VSCode shows the end of a js function, but Chrome Devtools has some extra code, which is the reminents of the removed console.log

4. Reloaded VSCode js file showing the reminents of the console.log actually in the file at line 1001 (same place as what chrome showed in screen shot 3).

I hope this helps a little bit in understanding what is happening. I'll also note that i previously tried VSCode version 1.30 and this had the same problem. I can go back to using version 1.20.1 for now as this works fine. So i'm presuming something has happened between those versions that is conflicting with how i am working.

Sorry for the essay, thanks for reading :-)
![Capture1](https://user-images.githubusercontent.com/37065485/57362782-6f11df80-7177-11e9-895b-77403a91ed80.JPG)
![Capture 2JPG](https://user-images.githubusercontent.com/37065485/57362802-75a05700-7177-11e9-9213-952f2bd1dd41.JPG)
![Capture3](https://user-images.githubusercontent.com/37065485/57362808-7a650b00-7177-11e9-82eb-8d41a9941e18.JPG)
![Capture4](https://user-images.githubusercontent.com/37065485/57362812-7df89200-7177-11e9-85c3-3eb60aea77cc.JPG)

**Comment by mjbvz** [comment] 2019-05-08 18:36
Thanks for the investigation. The network drive sounds like it could be related. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? We've made a few a few fixes related to network drives but I'm not sure if these are related to your problem.

Also do you also see this happen for any other file types, such an html file or even plain text files?

**Comment by mr-layco** [comment] 2019-05-08 18:39
I'll take a look at the insiders build and let you know as soon as I can get my hands on it, may be a couple days. Not noticed it with HTML or plain text but I'll carry out some more investigation and let you know. 😊

**Comment by mr-layco** [comment] 2019-05-13 20:00
Hi, I tried the insiders build, same problem i'm afraid. I've also tried html, aspx and plain text files, they don't have the same problem as the javascript files. 
Any thoughts?

**Comment by mjbvz** [comment] 2019-05-18 01:26
Adding @rebornix and @alexandrudima since I do not see how the TypeScript extension could be causing this and am suspicious of the network drive.

@mr-layco Please let us know if you see this for local files too or for those from the network drive

**Comment by ianoel230982** [comment] 2019-05-18 22:55
Hi, further update. I've downloaded newly released v1.34, 32 bit to give that a try. Here are my findings..
If i work locally i do not appear to have the same issue as i do when working from a network drive. 
I have also tried working with my files from the network drive with v1.34 and at first i thought it was all ok, but after a few saves the issue returned. 
I also noticed something else which i didn't see when working locally. That being, in the bottom left of the vs code window i started to see a message intermittently flashing saying 'initializing js/ts language features'. This only appeared when working on network files (it also appeared in v1.33 as well and if it did appear when working with local files it wasn't noticeable). However, i do not see this same message when working from the network drive in version 1.20 (which i've previously mentioned is working ok for me).

If you need anything else from me please let me know :-)

**Comment by ianoel230982** [comment] 2019-05-22 18:52
Hi, any update on this? :-)

**Comment by mr-layco** [comment] 2019-05-28 19:10
Anyone?

**Comment by ianoel230982** [comment] 2019-05-28 19:15
Hey, anyone still looking at this?

**Comment by ianoel230982** [comment] 2019-07-19 20:16
Hi, this is still an issue, any update please?

**Comment by rebornix** [comment] 2019-07-29 17:26
> If i work locally i do not appear to have the same issue as i do when working from a network drive.
I have also tried working with my files from the network drive with v1.34 and at first i thought it was all ok, but after a few saves the issue returned.

@mjbvz do you ever see similar issue before with network drive?

**Comment by mr-layco** [comment] 2019-08-05 18:27
This should not have been closed. It is unresolved and needs to be investigated further by the developers.

**Comment by bpasero** [comment] 2019-08-06 08:04
@ianoel230982 to clarify: you are editing a JS file in VSCode and after a few attempts you suddenly see some garbage at the end of the file?

**Comment by mr-layco** [comment] 2019-08-06 08:20
Hi,
Almost got it. It's not so much garbage, but a copy of the last few lines of the JavaScript file. The screen shots I provided above should give you an idea. It doesn't happen in Vs code version 1.20.1 but when I upgraded to version 1.34.0 the issue started. So somewhere between those versions something must have changed that introduces the issue.

**Comment by bpasero** [comment] 2019-08-06 08:28
> So somewhere between those versions something must have changed that introduces the issue.

That is a time frame of 14 months 😱 

This never reproduces in other file types but JavaScript? Even if you take the same content to another file with other extension and try there?

**Comment by ianoel230982** [comment] 2019-08-06 08:41
I tried using some aspx files and html files and couldn't get it to reproduce in those. If i work locally in version 1.34.0 then i don't have the problem, it only occurs when i'm using a network drive ( which in my particular instance is a MS SharePoint server opening the sharepoint site as a folder like 
\\web-application-name\sites\site-url  and/or saving the folder as a workspace and opening that way)

**Comment by bpasero** [comment] 2019-08-06 11:54
> I tried using some aspx files and html files and couldn't get it to reproduce in those.

And it reproduces without extensions running? Is there any external tool involved maybe that could hijack the file?

**Comment by ianoel230982** [comment] 2019-08-06 12:01
Yes reproduced without extensions running as well. There's no other external tool that i can think would be causing it. I used v1.34 exactly the same way that i use v1.20.1 now. There's literally no difference in the way i use it apart from it being a different version.
Could you recommend any other fault finding things to try? I could potentially try and figure out which version it starts breaking at by installing every version since 1.20.1 and trying it out if that would help?

**Comment by bpasero** [comment] 2019-08-06 12:23
@ianoel230982 yeah, let's start with 1.30: https://az764295.vo.msecnd.net/stable/61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8/VSCode-win32-x64-1.30.2.zip

**Comment by ianoel230982** [comment] 2019-08-06 12:30
Sure thing, before i do so, am i ok just to install 1.30 in a different folder on my hard drive or do i need a fully uninstall and clean install of the new version? If so, is there an easy way to fully uninstall vs code as i know there are a number of different folders various settings/extensions are stored.

**Comment by bpasero** [comment] 2019-08-06 14:20
Yeah good point, this is how you can ensure a fresh data directory so that you need no uninstall:

Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by ianoel230982** [comment] 2019-08-06 18:13
hi, this is most likely me not understanding fully, however the link you sent me didn't appear to be an install file, just the files for the program where i can double click code.exe however when i run code --disable-extensions --user-data-dir vscodetest in command prompt, it still opens version 1.20.1. I then downloaded the install file for 1.30.2 and installed it into a different folder on my C: drive, then did code --disable-extensions --user-data-dir vscodetest again, it still opens up 1.20.1. I'm sure i'm doing something wrong.

**Comment by bpasero** [comment] 2019-08-07 05:23
@ianoel230982 ah yes, you need to run the EXE directly, sorry for that.

**Comment by ianoel230982** [comment] 2019-08-07 08:40
Thanks for that. Manage to open it up as you described now. I have tested a couple of javascript files and had some mixed results. One file i tried and edited many times i couldn't reproduce the error. However, on another javascript file i could reproduce the error after a few edits. So the issue still exists in version 1.30.2. Long shot, are there any logs for vs code that i could look at that may log out what is happening if there is something behind the scenes not working? Or should i move on to another previous version and try again?

**Comment by bpasero** [comment] 2019-08-07 08:51
I fear there is not much logging to enable to get this kind of information. 

Let's continue to try more versions, e.g. 1.28.0: https://az764295.vo.msecnd.net/stable/3f23ae9e5d3190dd80e1703fa6e02497438457b4/VSCode-win32-x64-1.28.0.zip

Can you send me a screenshot of the extensions viewlet when you open it?

**Comment by ianoel230982** [comment] 2019-08-07 11:38
Hi, issue still persists on v.128. 
Just an extra bit of info. The issue seems to start when i remove some lines of code from the javascript file. This isn't every time i remove code, but once the issue starts, the file will let me undo my changes that started the error, maybe add some more code, but again if i remove some code, the file errors.
Also, if have the 'Initialising JS/TS language features' constantly flashing in the bottom left of my window, this isn't something. i get in v 1.20
Attached is the screen shot you requested
![code128](https://user-images.githubusercontent.com/37065485/62620097-492fde80-b910-11e9-974c-63a4a2ae1f3d.jpg)

**Comment by bpasero** [comment] 2019-08-07 12:02
@ianoel230982 that is quite interesting, the fact you see the statusbar flash. How about disabling this extension too?

![image](https://user-images.githubusercontent.com/900690/62621403-0a078a80-b91c-11e9-9ff3-9bec18c1fee3.png)

**Comment by ianoel230982** [comment] 2019-08-07 13:53
Still having the problem even with the type/javascript feature disabled. Should i try another version?

**Comment by bpasero** [comment] 2019-08-07 14:44
@ianoel230982 ok, here is 1.25: https://az764295.vo.msecnd.net/stable/1dfc5e557209371715f655691b1235b6b26a06be/VSCode-win32-x64-1.25.1.zip

**Comment by ianoel230982** [comment] 2019-08-07 15:44
Ok, i couldn't get v 1.25 to open properly using the command line as i had been doing with all the others, it kept opening version 1.20 that is installed on my system. However, i opened the code.exe file from directly within the folder of 1.25.1, so obviously this loaded with my extensions etc, and I have done some testing in the same js file i have been checking all the other versions in and i _cannot_ reproduce the error in 1.25. Two things i notice between this version and the last one i tried, I don't have the flashing text in the status bar that is relating to typescript/javascript features (i have checked the builtin extensions and it is enabled in 1.25) and the options menus at the top of the window (File, Edit, Selection, View etc) has a lighter background colour, as opposed to the later versions that are darker in colour (i'm sure that is not related though). So maybe something between 1.25 and 1.28 changed that is causing my issue?

**Comment by bpasero** [comment] 2019-08-07 16:07
Ok good, so here are the versions in between:
* 1.26: https://az764295.vo.msecnd.net/stable/4e9361845dc28659923a300945f84731393e210d/VSCode-win32-x64-1.26.0.zip
* 1.27: https://az764295.vo.msecnd.net/stable/7b9afc4196bda60b0facdf62cfc02815509b23d6/VSCode-win32-x64-1.27.0.zip

**Comment by ianoel230982** [comment] 2019-08-08 07:28
Ok, i've now checked both 1.27 and 1.26.
The issue does not exist on 1.26 but it DOES exist on 1.27. So perhaps the issue lies within that version somewhere?

**Comment by bpasero** [comment] 2019-08-08 09:07
@ianoel230982 at this point it would be good if you could try to run VSCode locally from its sources so that we can start to make some changes and see if they have any impact. 

Would you be willing to do that? It needs a bit of setup as explained here: https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by ianoel230982** [comment] 2019-08-08 09:47
I'm certainly happy to try and do what i can to help identify the issue. I have a few concerns though. If i do follow the instructions outlined in the link you provided i will need to install a few bits of software on my machine. The machine is on a local government network behind a corporate proxy that is quite restricted, so i may potentially have some access issues along the way.
Do i just follow the instructions on the 'How To Contribute Page' or is there more to it?

I've read through #6363 and the associated issue, it's a bit above my knowledge level, but if you're willing to answer lots of questions when they arise i'm certainly happy to do anything i can.

I won't get chance to begin the process for a few days as i have my day job i need to do as well :-)

**Comment by bpasero** [comment] 2019-08-08 09:52
@ianoel230982 yeah I realised that it may not be easy to do this. Any chance you can reproduce this issue from your personal machine as well? I guess this is hard because the issue only reproduces on the network drive?

**Comment by ianoel230982** [comment] 2019-08-08 09:58
I have tried in the past to get it to reproduce locally on my machine and it didn't, but i can certainly try again.

I'm not sure what a 'hook' is (sorry) where should i look or who would be the best person within an IT dept to ask?

**Comment by bpasero** [comment] 2019-08-08 10:08
My theory is that maybe something is checking any JS file that is being saved to the network drive and potentially alters the content in some way?

**Comment by bpasero** [comment] 2019-08-08 12:29
@ianoel230982 I just had a brief look over the changes that went into 1.27 and think there might be a related change in our file service implementation that could have an impact. I am now building a custom version of VSCode with this change reverted so that we can try it out. Will ping you once I have it.

**Comment by ianoel230982** [comment] 2019-08-08 12:35
ok, great thanks :-)

**Comment by bpasero** [comment] 2019-08-08 13:06
@ianoel230982 here you go: https://az764295.vo.msecnd.net/insider/2621bd8693ef46fcc465cee60bfcc009f9ef21f4/VSCode-win32-x64-1.38.0-insider.zip

**Comment by mr-layco** [comment] 2019-08-08 16:56
Thanks, will give it a go this evening and report back.

**Comment by ianoel230982** [comment] 2019-08-09 07:29
@bpasero i feel like this may be working. I did some testing on the same file in the same workspace whilst i was at home connected to my works network through wi-fi and vpn and i couldn't replicate the issue. I have done a little bit more testing connected directly to the network this morning in the office (just in case it was related) and it still seems to be working ok.
The constant flashing of the typescript/javascript features i had in the status bar isn't there anymore, although it does appear regularly but only for a split second before it disappears (again just in case that was related).
I'm going to continue using this version now properly with my normal daily duties and see if it ever happens again.
Has your change fixed the issue do you think?

**Comment by bpasero** [comment] 2019-08-09 08:33
@ianoel230982 yeah continue to use it for a while and maybe report back how it goes.

Unfortunately I cannot simply release this change as it will break another issue it was fixing. Best I can think of doing is providing some kind of setting.

**Comment by ianoel230982** [comment] 2019-08-09 08:44
@bpasero ok i will do, i'll give it a week or so and report back in the interim if there are any issues. I really appreciate your help with this, you've been great :-)

**Comment by ianoel230982** [comment] 2019-08-16 07:23
@bpasero hi, been using this version for a week now and not had any issues so i'm pretty sure whatever you did worked, so thanks again. What is the likelihood of your fix making it into the live version?

**Comment by bpasero** [comment] 2019-08-16 08:27
I cannot make any promises currently, sorry. It might be a bit before this gets revisited.

**Comment by ianoel230982** [comment] 2019-08-16 09:42
That's ok. As long as i can still use the version you gave me i'm happy for now.
I just hope it doesn't fall off the radar :-)

**Comment by ianoel230982** [comment] 2020-01-03 13:08
Hi @bpasero 
Just wondered if this fix is on the roadmap for anytime soon? If not, is there any possibility of me updating the version of vscode you created for me to the newest version (with this fix still in place)? There is an extension ([SPGo](https://marketplace.visualstudio.com/items?itemName=SiteGo.spgo)) i haven't been able to use since it was updated recently as it isn't compatible with the version you kindly created for me.

**Comment by bpasero** [comment] 2020-01-05 07:45
@ianoel230982 I created a build from our 1.41 release that you can get here: [Download](https://az764295.vo.msecnd.net/insider/03daa06eefbfdbef9096250ac019c51a85cd6cdd/VSCodeUserSetup-x64-1.41.1-insider.exe)

**Comment by bpasero** [comment] 2020-01-05 07:46
I am closing this issue as I find it unlikely to provide this option just for this one particular case.

**Closed by bpasero** 2020-01-05 07:46 UTC
Labels: debt, file-io

**Comment by ianoel230982** [comment] 2020-01-06 09:37
@bpasero Well thanks for your help, appreciate it. I'd be interested to know if you could explain to me (in lehmans terms) why this is causing our team an issue and no one else would be having this issue.

**Comment by bpasero** [comment] 2020-01-06 09:42
Such a setting seems like a band-aid for behavior that seems to originate from something outside of VSCode that you seem to be the only user hitting (as far as I can tell from issues at least). I feel this does not justify for a user facing setting, which - if turned on - btw will cause a lot of other issues to arise. The truncate is there for a reason to fix certain issues on Windows.

**Comment by ianoel230982** [comment] 2020-01-06 09:49
@bpasero i agree that it doesn't make sense for you to do a fix for just one person. Is it likely to be related to a setting on the company network i'm on or that i'm accessing the files via a network drive as opposed to locally on my machine?

**Comment by bpasero** [comment] 2020-01-06 10:20
Yeah I would think it is related to accessing the files via network share, but I cannot tell exactly what would trigger it. I am sure we have many more users accessing files from VSCode though a network attached share.
