### ISSUE TITLE
8/5000  An error occurred during software account synchronization. Procedure

### ISSUE THREAD

**Issue by nyhxiaoning** [microsoft/vscode#144883] opened 2022-03-11 06:36 UTC
I changed my Microsoft email account, and the result is that vscode always prompts the following every time I open it
You have been deregistered because stored authentication information could not be read.

**Comment by mjbvz** [comment] 2022-03-11 06:54
Duplicate of #144884

**Closed by mjbvz** 2022-03-11 06:54 UTC
