### ISSUE TITLE
Color Picker - Edits Wrong Property Value

### ISSUE THREAD

**Issue by bitm0de** [microsoft/vscode#136193] opened 2021-10-31 16:53 UTC
Issue Type: <b>Bug</b>

The color picker within VS Code shows the correct JSON property in the popup window but when you change the value of the RGB color control it edits the wrong JSON value.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.50GB free)|
|Process Argv|--crash-reporter-id 81da2d01-b71f-4fa6-9e73-ecf5aaae49e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
chalice-icon-theme|art|1.2.15
githistory|don|0.6.19
eppz-code|epp|1.2.52
prettier-vscode|esb|9.0.0
remotehub|Git|0.17.0
solidity|Jua|0.0.134
fluent-icons|mig|0.0.14
ecdc|mit|1.4.0
theme-monokai-pro-vscode|mon|1.1.19
csharp|ms-|1.23.16
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.4
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
vetur|oct|0.35.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
crestron-splus|sen|0.5.0
trailing-spaces|sha|0.3.1
vim|vsc|1.21.10
quokka-vscode|Wal|1.0.410

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by bitm0de** [comment] 2021-10-31 16:56
![Bug](https://user-images.githubusercontent.com/14263968/139594066-8769a2b6-7213-443e-ba8f-bbf7582d1ad9.gif)

**Comment by yume-chan** [comment] 2021-11-01 08:14
Duplicate of #121897. It has been fixed in insiders version.

**Closed** 2021-11-02 19:21 UTC
Labels: *duplicate
