### ISSUE TITLE
Move to file and Move to a new file not works

### ISSUE THREAD

**Issue by lsbbd** [microsoft/vscode#221539] opened 2024-07-12 08:16 UTC
Type: <b>Bug</b>

1. Select a React component in a tsx file
2. Select Move to a new file

-------------

and here is some errors in the VS Code developer Tools

<img width="1677" alt="image" src="https://github.com/user-attachments/assets/57b9836e-0ff3-45ee-8b51-5e9a1b82409b">

<details>
    <summary>errors</summary>

```
    2workbench.desktop.main.js:sourcemap:660   ERR Unhandled method getIdAtPosition: Error: Unhandled method getIdAtPosition
    at /Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398068
    at re (/Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398362)
    at /Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393146
    at Immediate.<anonymous> (/Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393166)
    at process.processImmediate (node:internal/timers:478:21)
  workbench.desktop.main.js:sourcemap:660   ERR <semantic> TypeScript Server Error (5.5.2)
  Debug Failure.
  Error: Debug Failure.
      at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154158:32)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144203:19
      at Map.forEach (<anonymous>)
      at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144197:17)
      at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143427:3)
      at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144403:3)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144392:77
      at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174213:5)
      at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144392:60)
      at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142518:31)
      at Object.getEditsForRefactor2 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149854:32)
      at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:190993:49)
      at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189211:43)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191397:69
      at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191389:14)
      at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191397:29)
      at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191439:51)
      at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
      at process.emit (node:events:514:28)
      at emit (node:internal/child_process:951:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.2)
  Debug Failure.
  Error: Debug Failure.
      at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154158:32)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144203:19
      at Map.forEach (<anonymous>)
      at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144197:17)
      at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143427:3)
      at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144403:3)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144392:77
      at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174213:5)
      at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144392:60)
      at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142518:31)
      at Object.getEditsForRefactor2 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149854:32)
      at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:190993:49)
      at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189211:43)
      at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191397:69
      at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191389:14)
      at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191397:29)
      at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191439:51)
      at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
      at process.emit (node:events:514:28)
      at emit (node:internal/child_process:951:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at n.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:474351)
    at v.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:468321)
    at v.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:467165)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466658)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
  workbench.desktop.main.js:sourcemap:660   ERR Unhandled method getIdAtPosition: Error: Unhandled method getIdAtPosition
    at /Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398068
    at re (/Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398362)
    at /Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393146
    at Immediate.<anonymous> (/Users/lsbbd/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393166)
    at process.processImmediate (node:internal/timers:478:21)
```
</details>

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin x64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (3.52GB free)|
|Process Argv|--crash-reporter-id d3faba32-b823-4f56-8236-d1dcd1268c58|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-sql-formatter|adp|1.4.4
vscode-sqlite|ale|0.14.1
toml|be5|0.6.0
vscode-tailwindcss|bra|0.12.5
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
rust-syntax|dus|0.6.1
gitlens|eam|15.2.0
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
prettier-vscode|esb|10.4.0
nasc-touchbar|fel|1.12.0
auto-close-tag|for|0.5.15
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.92.0
vscode-leetcode|Lee|0.18.2
nodejs-repl|los|0.5.15
regionfolder|map|1.0.22
rainbow-csv|mec|3.12.0
snapcode|moy|1.1.0
graphql|mqu|0.1.2
vscode-language-pack-zh-hans|MS-|1.91.2024071009
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
atom-keybindings|ms-|3.3.0
live-server|ms-|0.4.14
remote-explorer|ms-|0.5.2024070409
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5932
docthis|oou|0.8.2
vscode-twoslash-queries|Ort|1.2.2
prisma|Pri|5.16.1
quicktype|qui|23.0.170
vscode-xml|red|0.27.1
vscode-sort-json|ric|1.20.0
rust-analyzer|rus|0.3.2029
crates|ser|0.6.7
swift-lang|ssw|1.10.4
comment-divider|sta|0.4.0
addDocComments|ste|0.0.8
code-spell-checker|str|3.0.1
markdowntable|Tak|0.12.0
vscode-mdx|uni|1.8.9
vscode-lldb|vad|1.10.0
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-apple-swift-format|vkn|1.4.3
vim|vsc|1.27.3
change-case|wma|1.0.0
luahelper|yin|0.2.28
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31094926
refactort:31093865

```

</details>

**Comment by mjbvz** [comment] 2024-07-12 16:40
Please share an example project and steps to reproduce the issue

**Comment by lifeiscontent** [comment] 2024-07-15 21:38
@mjbvz this is likely a duplicate of https://github.com/microsoft/TypeScript/issues/58897

**Comment by divmgl** [comment] 2024-07-22 16:39
Looks like it's a TypeScript issue. Also really annoying that the `Move to file` and `Move to new file` has been swapped. I've been using `Move to new file` for years, why swap it?

**Comment by aconrad** [comment] 2024-07-26 16:08
This workaround fixed it for me: https://github.com/microsoft/TypeScript/issues/58897#issuecomment-2220808697

**Closed** 2024-10-15 11:48 UTC
Labels: info-needed
