### ISSUE TITLE
Application window is stuck on top of other apps on Ubuntu 16 + VirtualBox(3D Accelerated)

### ISSUE THREAD

**Issue by soichih** [Microsoft/vscode#6203] opened 2016-05-09 01:35 UTC
- VSCode Version: 1.0.0
- OS Version: Ubuntu16 (Running on VirtualBox 5.0.20 + 3D acceleration)

On Ubuntu16, vscode window will be stuck on top of all other windows - even above it's own menu, dialog, etc.. When I minimize the app, the main window will be left open but I can not interact with it. 

I've also noticed that the vscode app window's refresh rate is super slow; when I move the window around the desktop by grabbing the title bar, the main window sluggishly follows the title bar which is refreshed more responsively. 

I am not seeing any issue with Ubuntu 14, however.

_update_
If I disable 3D acceleration on the VirtualBox, the issue goes away. Also, google-chrome and chromium browser also has a similar issue. I believe this issue has to do with Chrome browser and VirtualBox-3D acceleration.

**Comment by bpasero** [comment] 2016-05-09 05:22
Maybe this is fixed in our latest insider build?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by soichih** [comment] 2016-05-09 20:56
I just updated my original post. This issue only occurs if I enable 3D acceleration on the VirtualBox. It has to do with the latest version of Chrome (50?)

**Comment by kalinkrustev** [comment] 2016-05-10 05:33
Seems related to this too: https://www.virtualbox.org/ticket/15375

**Comment by bpasero** [comment] 2016-09-18 07:20
@soichih @kalinkrustev  could you try our latest insider release to see if this issue still reproduces? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by kalinkrustev** [comment] 2016-09-23 07:19
I tried with:

> Version 1.6.0-insider
> Commit d81ee41c51cae93a5cac967e42a28660a3a7e005
> Date 2016-09-23T05:58:22.484Z
> Shell 1.3.5
> Renderer 52.0.2743.82
> Node 6.3.0

Still needs --disable-gpu to run properly. I must note that the issue I see is that window content is black or sometimes shows flickering rectangles. It is not stuck on top.

Also Chromium 52.0.2743.116 works fine on the same VM. An older chromium (<52) had similar issues as VSCode.

**Comment by bpasero** [comment] 2017-11-14 17:22
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.

**Closed by bpasero** 2017-11-14 17:22 UTC
Labels: electron, upstream
