### ISSUE TITLE
Pinned Diff Editor Does Not Retain Scroll Position After You Switch Back to it

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#7370] opened 2016-06-07 23:38 UTC
- VSCode Version: commit a3c38e902fc6dbe06d80f43d5cf527b066499f51
- OS Version: Mac OS X

Steps to Reproduce:

1. Open a diff editor
2. Pin the editor to stay by double clicking it in Open Editors
3. Scroll somewhere you will remember in this editor
4. Now open some other file from the explorer
5. Switch back to the diff editor and note that it does not retain the scroll position as other editors normally do when switching back.

![jun-07-2016 16-20-23](https://cloud.githubusercontent.com/assets/11839736/15878229/2f3df006-2cce-11e6-9c4b-c0f09b8065cb.gif)

**Comment by bpasero** [comment] 2016-06-08 04:46
Has always been like that. I think we just always focus the first diff in the editor.

**Comment by bpasero** [comment] 2016-06-08 04:48
Closing as designed because I think it is fair that the diff editor always jumps to its first diff. You might have edited the file meanwhile and going back to the diff could jump to the line with the diff that previously was not there.

**Closed by bpasero** 2016-06-08 04:48 UTC
Labels: bug
