### ISSUE TITLE
Clicking build error or warning opens up new instance of same file

### ISSUE THREAD

**Issue by BaronZemo** [Microsoft/vscode#61512] opened 2018-10-22 16:40 UTC
- VSCode Version: 1.28.2
- OS Version: Windows 7 64-bit

Steps to Reproduce:

1. Open a C file in the editor that is part of the workspace or open folder via Quick Open.
2. Force a build error by putting junk in the file.
3. Build project.
4. Click on build error or warning in the Output Pane. A new instance of file opens, this time with the absolute path instead of a relative path.
5. Launch Quick Open again. This time two versions of same file will appear. One with absolute path, one with relative path.

This seems like a minor thing, but by having two versions of same file opened, it's easy to get the "The content on disk is newer. Please compare your version with the one on disk."

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-10-22 19:16
@BaronZemo can you mouse over each of the tabs and tell us what the paths say?

**Comment by bpasero** [comment] 2018-10-23 05:51
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-10-23 05:51 UTC
Labels: needs more info
