### ISSUE TITLE
why port 9229 had been used!

### ISSUE THREAD

**Issue by CHANCCCZQ** [microsoft/vscode#85431] opened 2019-11-23 02:45 UTC
- VSCode Version:1.40.1

- OS Version: Darwin x64 18.6.0

Steps to Reproduce:

1.i don't use port 9229
2. it just can't run my service

![image](https://user-images.githubusercontent.com/22274839/69471788-5816a000-0dde-11ea-8ac0-b07f8a3369e7.png)

![image](https://user-images.githubusercontent.com/22274839/69471792-61a00800-0dde-11ea-8d7a-b9dd4a9be559.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment] 2019-11-23 15:29
Duplicate of #85328

**Closed by egamma** 2019-11-23 15:29 UTC

**Comment by ahmadx87** [comment] 2019-11-25 09:16
I'm having the same issue. Everything was working perfectly. I have a basic node project that I'm not able to debug anymore. I think it all happened after the last update. Already wasted a few hours of my time and yet haven't found a solution.
