### ISSUE TITLE
Please add the ability to choose different themes for colors and tokenColors

### ISSUE THREAD

**Issue by dzhukovsky** [microsoft/vscode#188311] opened 2023-07-19 18:43 UTC
VS Code has beautiful build-in theme like "Default Dark Modern", but it doesn't contain `tokenColors` for editor (e.g. C# for me). But I have another one theme that not as pretty as the first one but has a rich `tokenColors` customization, e.g. "Visual Studio 2019 Dark".

Please, add ability to select one theme for VS Code shell, and another for 'tokenColors'.

![image](https://github.com/microsoft/vscode/assets/136100876/d2fb2057-8b3a-4d7a-a2af-4b547ec2c255)
![image](https://github.com/microsoft/vscode/assets/136100876/ab828b9b-88dc-49be-81b2-60372a4d56eb)

**Comment by aeschli** [comment] 2023-08-18 08:54
duplicate of https://github.com/microsoft/vscode/issues/25986

We don't plan to add this. There are various possibilities for you:
- customize the Dark Modern theme in your settings: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
- create a new theme and publish it

**Closed by aeschli** 2023-08-18 08:54 UTC
