### ISSUE TITLE
Feature Request: Extension API - Notification for Debugger Events and Current Stack Frame

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#49785] opened 2018-05-13 14:32 UTC
I have a very cool extension in mind, but for that I need to know whenever the state of the debugger changes (running/halting) and what the current selected stackframe in vs code is.

According to the docs, this does not seem to be possible yet. Are there any plans to make parts of the debugger api available to extensions?

**Comment by weinand** [comment] 2019-10-14 15:42
this is a duplicate of #30810 and #63943

**Closed** 2019-10-14 15:42 UTC
Labels: *duplicate, api, debug, feature-request
