### ISSUE TITLE
Merge conflict not displaying changed files in version control

### ISSUE THREAD

**Issue by hanzlahabib** [microsoft/vscode#115286] opened 2021-01-28 07:00 UTC
Issue Type: <b>Bug</b>

1. Take pull from xyz branch
2. It stops because of merge conflict
3. No changed / conflict files are displaying in git version control panel

![image](https://user-images.githubusercontent.com/41893448/106101888-6558b880-6160-11eb-83cc-d21531577040.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.14GB free)|
|Process Argv|. --crash-reporter-id 902149e6-dc36-4a75-b96e-7af00f47a6b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.5
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.3
vsc-material-theme-icons|equ|1.2.2
vscode-docker|ms-|1.9.1
remote-wsl|ms-|0.52.0
vscode-yaml|red|0.14.0
vs-code-prettier-eslint|rve|0.4.1
tabnine-vscode|Tab|3.2.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30250195
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by eamodio** [comment] 2021-02-08 20:54
Duplicate of #114397

**Closed by eamodio** 2021-02-08 20:54 UTC
