### ISSUE TITLE
Highlight / Validate code in template string

### ISSUE THREAD

**Issue by rogerpadilla** [Microsoft/vscode#27269] opened 2017-05-25 13:20 UTC
- VSCode Version: 1.12.2
- OS Version: Win 10

Steps to Reproduce:

1. Having a template string containing HTML code, VsCode should be able to highlight such language in that context (independently from the global file).

I.e. You can be inside a .ts file, but if you are in a variable wich value is a template string containing HTML code, the IDE should understand it in some way (maybe using some annotation or comment?).

I'm aware we can switch (CTRL + k, m) the language of the file, but I'm asking about do the same but for some parts of the file.

**Comment by aeschli** [comment] 2017-05-25 21:18
duplicate of #1751

**Closed by aeschli** 2017-05-25 21:18 UTC
