### ISSUE TITLE
Vs code android

### ISSUE THREAD

**Issue by Ninjacoderhsi** [microsoft/vscode#140507] opened 2022-01-11 17:06 UTC
![Screenshot_۲۰۲۲۰۱۱۱-۲۰۰۷۰۲_vs code mobile](https://user-images.githubusercontent.com/89408667/148988367-8ee29c45-2689-4484-b6dd-ec7583929324.jpg)
![Screenshot_۲۰۲۲۰۱۱۱-۱۵۵۹۱۷_vs code mobile](https://user-images.githubusercontent.com/89408667/148988375-b94164c2-c1d2-48da-ba0a-238934bbab4f.jpg)

Hello, I am an Android developer and I want to publish the vs code program for Android. Do you grant the necessary permissions?

**Comment by luisdavim** [comment] 2022-02-16 07:27
I think an official android version of vscode on the play store would be awesome, especially with tablets and Samsung  Dex becoming more powerful and popular.

**Comment by chrisdias** [comment] 2022-02-22 20:39
dupe of #126147

**Closed by chrisdias** 2022-02-22 20:39 UTC

**Comment by Ninjacoderhsi** [comment] 2022-03-05 10:18
> 

Yes, I created a version but it is not very powerful. I am updating this program. I update about 5 times a month.
