### ISSUE TITLE
Target size of "Copy collaboration link" and "Stop collaboration session" button is less than 24x24px: A11y_Visual Studio Code_"Session Details ", "Help" sections_Target Size

### ISSUE THREAD

**Issue by kapilvaishna** [microsoft/vscode#216783] opened 2024-06-21 06:16 UTC
**Please do not close this bug. This bug should only be closed by Trusted Tester after verification.**
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."
## Environment Details:
Application Name: Visual Studio Code
Edition Windows 11 Enterprise
Version 23H2
OS build 22631.3737
Visual Studio code
Version 1.89.1
## GitHub Tags:
#A11yTCS; #A11ySev2; #WCAG2.5.8; #DesktopApp; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Jan2024; #FTP; #Win32; #A11yMAS; #A11yWCAG2.2; #TargetSize;
## Repro Steps:

1. Open visual studio code application.
2. Install "Live share" extension.
3. TAB till "Share read/write" control and hit ENTER.
4. TAB till "Session Details" in left navigation.
5. TAB till "Copy collaboration link" and "Stop collaboration session" button.
6. Observe that target size of "Copy collaboration link" and "Stop collaboration session" button is less than 24x24px

## Actual Result:
Target size of "Copy collaboration link" and "Stop collaboration session" button is less than 24x24px.
## Expected Result:
Target size of "Copy collaboration link", and "Stop collaboration session" button should be minimum 24x24pixel. If the controls have spaced in-between, then those spaces should not intersect each other and target size with spacing should be 24x24 pixel for each one.
## User Impact:
Users with dexterity limitations and those who have difficulty with fine motor movement find it difficult to accurately activate small targets when there are other targets that are too close. Providing sufficient size, or sufficient spacing between targets, will reduce the likelihood of accidentally activating the wrong control.
### Attachment

https://github.com/microsoft/vscode/assets/124254981/8d7c0a63-9c6f-4fdc-a527-edc5dcfba872

![216783_Stop collaboration session](https://github.com/microsoft/vscode/assets/124254981/d740a2ce-9762-4439-83d6-59e5fba9669d)
![216783_Copy collabration link](https://github.com/microsoft/vscode/assets/124254981/845851c7-ef1c-47d8-a1a5-ae52c05144ca)

**Comment by kapilvaishna** [comment] 2024-06-21 06:27
Logged to track this bug https://github.com/microsoft/vscode/issues/209934

**Comment by alexr00** [comment] 2024-06-21 09:31
Closing a duplicate of the previous bug https://github.com/microsoft/vscode/issues/209934

Please reach to Isidor on Teams.

**Closed by alexr00** 2024-06-21 09:31 UTC

**Comment by kapilvaishna** [comment] 2024-07-18 17:25
Verify the issue with ruler scale and for both control logical size is 20*20 px and 4 px space is there between the control so closing the bug.
Attachment:

https://github.com/user-attachments/assets/4a03db5c-0e22-4e7b-a512-b16bde9b2aaf
