### ISSUE TITLE
Hindi characters are not being rendered properly

### ISSUE THREAD

**Issue by amitguptagwl** [Microsoft/vscode#42700] opened 2018-02-01 05:13 UTC
I noticed that Hindi characters are not being render properly in markdown file. It happens only with list.

- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Copy the following code in markdown file in ordered list "वो ऐसा क्या है जो हमारे अंदर भी है और बाहर भी है। जिसकी वजह से हम सब हैं। जिसने इस सृष्टि की रचना की है।"

![webp net-gifmaker](https://user-images.githubusercontent.com/7692328/35662134-80424282-073c-11e8-8782-af195ee93014.gif)

Does this issue occur when all extensions are disabled?: Yes

Impact: minimum as selection, search, final view, and copy paste to other files are ok.

**Comment by mjbvz** [comment] 2018-02-02 07:06
Ok, here's what I see in the current insiders build after pasting in the text:

<img width="711" alt="screen shot 2018-02-01 at 11 04 57 pm" src="https://user-images.githubusercontent.com/12821956/35720859-56421436-07a4-11e8-83b5-7b93af2aad5d.png">

I can sometimes trigger the invalid glyph while editing the text itself. It also shows up in the editor.

Do you see this problem after pasting in the text or only while editing the text? Can you please test this on VS Code insiders

**Comment by amitguptagwl** [comment] 2018-02-02 07:21
![screenshot from 2018-02-02 12-45-57](https://user-images.githubusercontent.com/7692328/35721247-1aea222a-0817-11e8-9e8c-2579d3db434f.png)
I have noticed that the issue is not with list but with number of spaces in starting. In above picture, I left 3 spaces before 1st line, 6 spaces before 2nd line, and 11 spaces before 3rd line. One more observation, it is not related to MD files only, I have found it on text, and file with no extension. However I didn't find the issue on  HTML, JS, JSON etc. files .

**Comment by KTSamy** [comment] 2018-03-30 14:03
This issue like looks the same as the one with Tamil (https://github.com/Microsoft/vscode/issues/22352). It seems that all Indic languages are having this issue.

**Comment by alexandrudima** [comment] 2018-04-04 09:40
We are breaking up the text into multiple `<span>` elements approx. every 50 characters. We probably shouldn't do it in this case.

**Comment by alexandrudima** [comment] 2018-04-04 09:45
Duplicate of #22352

**Closed by alexandrudima** 2018-04-04 09:45 UTC
Labels: bug, editor-rendering
