### ISSUE TITLE
some times vscode save js file document confusion

### ISSUE THREAD

**Issue by zhoutianwu** [Microsoft/vscode#15102] opened 2016-11-07 15:02 UTC
- VSCode Version: 1.6.1
- OS Version: Windows7 x64

Steps to Reproduce:

1.  Open more js file in vscode ,and some js files is in edit dirty state, when i click save all button, the current open unsaved file(the current editor show in tab) will confusion,its content can be anthor opened js file content or  anthor opened  js file part content. Then the confusion js file be saved with wrong content!
2. i found this error some times (3-4 times a month) under vscode version 1.6.0 and 1.6.1 and 1.7.1

**Comment by bpasero** [comment] 2016-11-07 16:02
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-11-08 18:32
@zhoutianwu ping

**Comment by bpasero** [comment] 2016-11-16 18:08
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-11-16 18:08 UTC
Labels: bug, needs more info
