### ISSUE TITLE
2 TS quick fixes that do the same thing to implement abstract class

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78048] opened 2019-07-27 20:22 UTC
Bit confusing having the second one considering there is only 1 class that needs the fix.

<img width="450" alt="Screen Shot 2019-07-27 at 1 20 10 PM" src="https://user-images.githubusercontent.com/2193314/61999228-51b32a00-b071-11e9-8756-f19d7b7dfd40.png">

**Comment by mjbvz** [comment] 2019-08-11 09:59
Please share example code?

**Comment by Tyriar** [comment] 2019-08-11 15:47
Does not reproduce:

```ts
abstract class A {
	abstract b(): void;
}
class B extends A {
}
```

Does reproduce:

```ts
abstract class A {
	abstract b(): void;
	abstract c(): void;
}
class B extends A {
}
```

**Comment by mjbvz** [comment] 2019-08-12 18:51
Thanks

The root cause is that there are two errors reported at the exact same location:

<img width="855" alt="Screen Shot 2019-08-12 at 11 46 54 AM" src="https://user-images.githubusercontent.com/12821956/62889941-37c34980-bcf7-11e9-8815-d656749261b2.png">

This is the only case that I know of where we have multiple errors at the same location with a single quick fix that fixes both errors

One fix would be to have a single error that says something like: `B does not implement all members of abstract class A`, with related diagnostics for the specific missing properties. This is what we do for interfaces:

```ts
interface A {
	b(): void;
    c(): void;
    
    
}

class B implements A {
}
```

Marking as august for investigation

**Comment by mjbvz** [comment] 2019-08-13 21:24
After thinking about this more, I think the correct fix would be to have TS use related spans: https://github.com/microsoft/TypeScript/issues/32848

I don't think adding special logic to handle this specific case is worth it in VS Code. Using related spans would also make the error more clear and let us link to specific abstract methods that not implemented

**Closed by mjbvz** 2019-08-13 21:24 UTC
