### ISSUE TITLE
Delete files on explorer with press key Delete

### ISSUE THREAD

**Issue by MarcelloVSilva** [microsoft/vscode#76991] opened 2019-07-09 14:08 UTC
- VSCode Version: 1.36.0
- OS Version: Deepin 15.9.3

Steps to Reproduce:

1. Select any file at explorer and press `delete` key, for delete file or files
2. Result: vscode start a find folders and files with `delete` match.
![Captura de Tela_selecionar área_20190709110303](https://user-images.githubusercontent.com/6786382/60894784-bb41d480-a239-11e9-9dd0-061dd82d89e8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2019-07-09 14:27
/duplicate of #76514 and fixed in the upcoming recovery release.

**Closed** 2019-07-10 07:33 UTC
Labels: *duplicate
