### ISSUE TITLE
Output window treats characters 'xA' as a new line.

### ISSUE THREAD

**Issue by meancoot** [Microsoft/vscode#12108] opened 2016-09-15 23:27 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10

When a string containing the character sequence 'xA' is written to the output window VSCode replaces it with a new line.

![example](https://cloud.githubusercontent.com/assets/2244868/18570711/5cb540de-7b7a-11e6-8f5c-98a6bbc10dc7.png)

**Comment by bpasero** [comment] 2016-09-16 03:53
Not sure if this is an editor issue or output issue.

**Comment by isidorn** [comment] 2016-09-19 13:38
@bpasero this is coming from [removeAnsiEscapeCodes](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L543)
It seems like the xA is the ansi escape code for new line.

**Comment by bpasero** [comment] 2016-09-19 13:43
@isidorn got it. I think we cannot change this because it could mean that the output for other programs suddenly end up on a single line.

**Comment by isidorn** [comment] 2016-09-19 13:53
Thus closing this as designed

**Closed by isidorn** 2016-09-19 13:53 UTC

**Comment by rmunn** [comment] 2016-09-27 02:31
For reference, this is not actually working as designed. Rather, this has been buggy since VS Code's first commit, but the bug is only just now being reported. See #12608 for all the details.
