### ISSUE TITLE
Open Recent Uses Current Window

### ISSUE THREAD

**Issue by zcdunn** [microsoft/vscode#76874] opened 2019-07-08 12:26 UTC
Issue Type: <b>Bug</b>

**Description:** When I have a project open and try to open another, it uses the current window.

**Steps to Reproduce:**
1. Open a project in VSCode
2. Click File->Open Recent->/Select a different project

**Expected Result:** My current window remains and a new window is opened with the second project.

**Actual Result:** The new project is opened in the current window.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (24.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
vim|vsc|1.8.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by gjsjohnmurray** [comment] 2019-07-08 12:43
/duplicate of #76823

Hold the Shift key down when you click on the recent workspace in the list.

**Closed** 2019-07-08 15:00 UTC
