### ISSUE TITLE
"{}" input will automatically pop up when the console, write JS when in the HTML file

### ISSUE THREAD

**Issue by 343830384** [Microsoft/vscode#45863] opened 2018-03-15 13:40 UTC
Issue Type: <b>Bug</b>

"{}" input will automatically pop up when the console, 
write JS when in the HTML file

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|7.90GB (2.59GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-simple-icons|Lau|1.8.2
debugger-for-chrome|msj|4.2.0
view-in-browser|qin|0.0.5

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment] 2018-03-15 14:27
You mention that this only occurs when extensions are installed. Can you identify the extension that is causing this behavior by disabling all extensions and then turning on one after the other?

**Comment by 343830384** [comment] 2018-03-16 05:38
The problem remains
![bug](https://user-images.githubusercontent.com/16252756/37505329-460fea60-291f-11e8-9613-58c21c6bb1a5.png)

**Comment by 343830384** [comment] 2018-03-16 05:44
I disabled all plugins but the problem persists
![bug](https://user-images.githubusercontent.com/16252756/37505506-287ee95a-2920-11e8-815c-7060742ab788.png)

**Comment by 343830384** [comment] 2018-03-16 05:47
I disabled all plugins but the problem persists
![bug](https://user-images.githubusercontent.com/16252756/37505557-86d55b74-2920-11e8-88a2-800ad6d57c02.png)

**Comment by tsalinger** [comment] 2018-03-16 05:49
Interesting, how exactly can you trigger this error?
Please provide reproducable steps.

**Comment by 343830384** [comment] 2018-03-16 05:56
When you write javascript in an html file, such as var a={}.
This time the console will automatically jump out.
I don't care about this error, but the console always jumps out

**Comment by aeschli** [comment] 2018-03-16 08:53
duplicate of https://github.com/Microsoft/vscode/issues/45529

**Closed by aeschli** 2018-03-16 08:53 UTC
Labels: needs more info

**Comment by 343830384** [comment] 2018-03-16 09:02
I don't really understand what you mean , 
 I'm new to the installation and I haven't done what you said  .  
 So can you tell me where to close this?    
 Thank you very much

2018-03-16 

KS3438 



发件人：Martin Aeschlimann <notifications@github.com>
发送时间：2018-03-16 16:54
主题：Re: [Microsoft/vscode] "{}" input will automatically pop up when the console, write JS when in the HTML file (#45863)
收件人："Microsoft/vscode"<vscode@noreply.github.com>
抄送："KS"<343830384@163.com>,"Author"<author@noreply.github.com>

Closed #45863.

**Comment by aeschli** [comment] 2018-03-16 09:13
Your bug is the same as bug #45529 which is tracked in https://github.com/Microsoft/TypeScript/issues/22618

There is currently nothing you can do than to wait for https://github.com/Microsoft/TypeScript/issues/22618 to be fixed and the fix to be integrated into VSCode.
