### ISSUE TITLE
Color picker immediately closes on click (not allowing cycling through presentations or changing opacity) when a presentation has additionalTextEdits

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#136965] opened 2021-11-11 14:48 UTC
When a `ColorProvider` provides multiple ColorPresentations, they can be cycled by clicking on the text in the color picker because dragging the color selector around does not close the color picker:

![color_good](https://user-images.githubusercontent.com/1078012/141317459-68c1db00-443d-4351-8aa6-93a10d1613ed.gif)

However, if the `ColorPresentation` contains `additionaTextEdits`, the color picker closes immediately upon clicking anywhere, making it impossible to select any other presentation. Clicking where you'd normally cycle through the presentations also immediately closes the picker.

![color_bad](https://user-images.githubusercontent.com/1078012/141317673-a8ca75bf-769d-43f4-84a5-27fe22499760.gif)

Here's an example. Paste this into a newly created VS Code extension, change `activationEvents` to `*` and then open a file with at least a few lines.

```ts
const colorRange = new vscode.Range(new vscode.Position(5, 0), new vscode.Position(5, 1));
const otherEditRange = new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0));
context.subscriptions.push(vscode.languages.registerColorProvider({ scheme: 'file' }, {
	provideDocumentColors(document: vscode.TextDocument, token: vscode.CancellationToken): vscode.ProviderResult<vscode.ColorInformation[]> {
		return [
			new vscode.ColorInformation(
				colorRange,
				new vscode.Color(1, 0, 0, 1),
			),
		];
	},

	provideColorPresentations(color: vscode.Color, context: { document: vscode.TextDocument, range: vscode.Range }, token: vscode.CancellationToken): vscode.ProviderResult<vscode.ColorPresentation[]> {
		const one = new vscode.ColorPresentation('one');
		one.textEdit = new vscode.TextEdit(colorRange, one.label);
		one.additionalTextEdits = [
			new vscode.TextEdit(otherEditRange, 'IMPORT')
		];
		const two = new vscode.ColorPresentation('two');
		two.textEdit = new vscode.TextEdit(colorRange, two.label);
		two.additionalTextEdits = [
			new vscode.TextEdit(otherEditRange, 'IMPORT')
		];
		return [
			one,
			two,
		];
	}
}));
```

**Comment by rajhlinux** [comment] 2022-06-23 00:28
I have this same problem, its super annoying.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/61344181/175182267-7492f5ca-b670-4b3a-bf77-1971d7010c7c.gif)

Whenever I put my mouse on the tiny color box, the color palette opens and when I hover the mouse to select a color, the entire color palette disappears.

I need to keep on repeating the above steps until the color palette does not close anymore.

Whats the fix to this issue? How can I use a color picker from an extension plugin?

Thanks.

**Comment by gonzalologorg** [comment] 2023-11-21 04:38
Can confirm in vscode insiders it has been fixed

**Comment by aiday-mar** [comment] 2023-11-21 08:02
Thanks for picking up on it @gonzalologorg, this issue will be closed

**Comment by DanTup** [comment] 2023-11-21 10:20
This doesn't seem fixed in Insiders to me. Using the same code provided in my OP above. If anything, it seems to close more aggressively (sometimes just clicking on the colour block toggles it open and closed very quickly):


https://github.com/microsoft/vscode/assets/1078012/115e4fca-6042-4f41-a0d0-a1799a057854

```
Version: 1.85.0-insider (user setup)
Commit: 05cd2640ec8a106a4ee99cb38e6ee34fbec04f11
Date: 2023-11-21T05:35:09.651Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by aiday-mar** [comment] 2023-11-21 12:12
I see, apologies, I will reopen the issue

**Comment by pooYAYooq** [comment] 2023-12-06 06:48
So frustrating, I have the same issue with my vs code.

**Comment by screenspaceio** [comment] 2023-12-06 10:49
Same here. Started closing on click about a month ago.

**Comment by DarkPromo** [comment] 2023-12-06 20:43
same here it is very annoyng. has any1 found a way to fix it<

**Comment by peachtrees13** [comment] 2023-12-07 07:46
Facing the same issue

**Comment by spikethea** [comment] 2023-12-07 14:06
Got the same problem

**Comment by starball5** [comment] 2023-12-07 20:33
@aiday-mar thanks! what's the release milestone for the fix?

**Comment by aiday-mar** [comment] 2023-12-08 16:42
Hey @starball5 this fix will go into Insiders soon, and then it will land in stable only end of January, which is when our next stable release is.

**Closed** 2023-12-08 16:42 UTC
Labels: bug, editor-color-picker

**Comment by DanTup** [comment] 2023-12-11 15:00
@aiday-mar the colour picker stays open now, but it's not updating the range correctly, it's just inserting on every click.

Let me know if I should file a new issue about this (it's not really the same bug, but I suspect it might occur as a result of this fix):

https://github.com/microsoft/vscode/assets/1078012/0eed2879-fca2-463f-af1b-240d26db3bf3

I'm using the same code I posted above to repro.

**Comment by aiday-mar** [comment] 2023-12-11 16:35
Hi @DanTup thank you for posting about this and apologies, it looks like the fix has caused a regression. Yes if you could please open an issue that would be great.

**Comment by DanTup** [comment] 2023-12-11 17:23
I've opened https://github.com/microsoft/vscode/issues/200569
