### ISSUE TITLE
Windows: Pressing stop does not close extension development window in some cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4131] opened 2016-03-14 12:22 UTC
I notice that pressing the stop button in debug no longer seems to close the extension host window, at least sometimes. Did something change here in the protocol?

I only see it sporadically so I wonder if this is some timing issue.

Also @weinand fyi

**Comment by weinand** [comment] 2016-03-14 13:12
@bpasero I tried 20 times but I cannot reproduce this. Or does this problem occur less often?

**Comment by bpasero** [comment] 2016-03-14 13:27
In my case I had a simple extension (Hello World) that would create a output channel and append output to it when the command is invoked. Not sure if it makes any difference but I had the window with the extension on top of the debugger and clicked right onto the stop button even though the extension host window had focus. It should not make a difference though...

**Comment by weinand** [comment] 2016-03-14 13:33
@bpasero On OS X if you have the EH window on top of the debugger and press the stop button, the first click does not stop the EH because it only brings the window to front. Only the second click kills the EH. Could that be the effect that you are seeing?

**Comment by bpasero** [comment] 2016-03-14 15:15
This is on Windows.

**Comment by isidorn** [comment] 2016-06-17 15:11
Not sure if this is still an issue, forwaring to @weinand to decide

**Comment by weinand** [comment] 2016-07-06 13:30
duplicate of Microsoft/vscode#6572

**Closed by weinand** 2016-07-06 13:30 UTC
Labels: bug, debug
