### ISSUE TITLE
TypeScript Organize Imports removes aliased imported types that are in use

### ISSUE THREAD

**Issue by AustonZ** [Microsoft/vscode#47706] opened 2018-04-12 02:05 UTC
Issue Type: <b>Bug</b>

1.  Create a new TS project that uses an NPM package, such as "typescript"
2.  Create a TS file that imports a type from that package, aliasing it to a different name.  Use that aliased type in the code.  E.g.:
```typescript
import { BaseType as Foo } from "typescript";
const x: Foo = null;
```
3.  SHIFT+ALT+O  (or CTRL+SHIFT+P, TypeScript: Organize Imports)

Expect:
No changes

Actual:
The import line is removed, and the code no longer compiles.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|15.84GB (8.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment] 2018-04-12 15:43
Duplicate of https://github.com/Microsoft/TypeScript/issues/22743

Should already be fixed in vscode insiders

**Closed by mjbvz** 2018-04-12 15:43 UTC
Labels: typescript
