### ISSUE TITLE
Markdown Preview cache

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#146014] opened 2022-03-25 00:16 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.65.2
- OS Version:win10

Steps to Reproduce:

1.open folder with .md file, open the file, open it's Preview .
2.switch to the file, edit and save it .
3. switch to the Preview .
4. repeat 2. and 3. .
5. switch to the file, switch to the Preview . the Preview will show the state which was at the opening .

**Comment by mjbvz** [comment] 2022-03-25 01:50
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by irvnriir** [comment] 2022-03-25 02:29
i also copied all settings and extensions . no, the issue seems currently solved in 1.66 .

**Comment by mjbvz** [comment] 2022-03-25 20:14
Ok, closing since it is already fixed in insiders then

**Closed** 2022-03-25 20:15 UTC
Labels: markdown, *not-reproducible
