### ISSUE TITLE
Git - Merge on pull that results in no changes after resolving conflicts won't commit

### ISSUE THREAD

**Issue by vinitshahdeo** [microsoft/vscode#203875] opened 2024-01-31 10:17 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.85.2 (Universal)
- OS Version: Darwin arm64 23.2.0

**Steps to Reproduce**:

- Change something locally in branch A and commit to the remote.
- Another person changes the same line (with slight differences) and pushes to another remote branch B.
- Pull the latest changes from branch B and attempt to merge into branch A.
- Open the conflicted file, and choose **`Accept Current`** for the conflict resolution.
- Save the file and click **`Stage Changes`** on the conflicted file, resulting in no apparent change.
- Attempt to commit, but it indicates that there are no changes to commit.
- Despite this, Git still thinks you're in a merge operation and gives the error "a `MERGE_HEAD` exists."

**Comment by lszomoru** [comment] 2024-12-13 13:05
Duplicate of https://github.com/microsoft/vscode/issues/129598

**Closed by lszomoru** 2024-12-13 13:05 UTC
Labels: bug, git
