### ISSUE TITLE
Using vscode://vscode-remote/ssh-remote with an SSH username can break (WebView) resources

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#128309] opened 2021-07-09 12:13 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Windows 10, Remote SSH into Linux

Steps to Reproduce:

It's not easy to reproduce. It happens with Remote SSH, opening a remote `.workspace` file. Reproduces in first step of extension bisect, so should not be related to extensions. Does not reproduce when connecting to the same Linux server via Remote SSH (without opening the workspace). Does not reproduce locally on Windows.

![image](https://user-images.githubusercontent.com/12128514/125075305-b3ce9380-e0be-11eb-8037-da268a9bc5d6.png)

I also see this:
```
[2021-07-09 13:58:43.164] [renderer5] [error] Could not find pty with id "74": Error: Could not find pty with id "74"
    at y._throwIfNoPty (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:12:49364)
    at y.updateIcon (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:12:46464)
    at Object.call (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:11:8338)
    at y.onPromise (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:10:49795)
    at y.onRawMessage (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:10:49154)
    at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:10:48407
    at T.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:8:1726)
    at process.U (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/platform/terminal/node/ptyHostMain.js:6:31321)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2021-07-09 13:58:45.572] [renderer5] [error] Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at _.deserializeWebviewPanel (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/extensions/markdown-language-features/dist/extension.js:1:108631)
	at s.$deserializeWebviewPanel (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:85:79150)
	at u._doInvokeHandler (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:12743)
	at u._invokeHandler (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:12435)
	at u._receiveRequest (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:11097)
	at u._receiveOneMessage (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:9900)
	at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:8004
	at d.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at h.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:15777)
	at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:29793
	at d.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at h.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:15777)
	at r._receiveMessage (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:21035)
	at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:17921
	at d.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at c.acceptChunk (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:13138)
	at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:12486
	at d.fire (/data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at /data2/bers/opt/vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:19018
	at afterWrite (internal/streams/writable.js:466:5)
	at onwrite (internal/streams/writable.js:446:7)
	at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
	at Zlib.processCallback (zlib.js:586:8)
```

Does not happen with this version SSH-remoting into the same workspace (settings and extensions synced):
```
Version: 1.59.0-insider (user setup)
Commit: 87d692b7bf1eb5a663b3e62620a6e7e436e1838c
Date: 2021-07-09T05:13:26.890Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```
So either it has been fixed already, or my stable installation is broken somehow.

**Comment by mjbvz** [comment] 2021-07-14 02:50
Closing since this is not reproducible on insiders. If you start seeing it again with VS Code 1.59+ please let us know

**Comment by bersbersbers** [comment] 2021-07-26 08:54
I can reproduce this in Insiders now, see https://github.com/microsoft/vscode-remote-release/issues/5282#issuecomment-886506235

Basically, having Remote SSH installed, open
```
vscode-insiders://vscode-remote/ssh-remote+user@host/home/user
```
and try to view a PNG file. That won't work due to resource requests having "user@" being blocked. I am not sure this is an issue with VS Code or VS Code Remote (SSH), though, so I am posting this in both issues.

**Comment by bersbersbers** [comment] 2021-07-27 08:07
@mjbvz do you want to reopen and rename this issue? Or should I file the above as a new one?

**Comment by bersbersbers** [comment] 2021-07-28 08:16
I should maybe add that while the `user@` is not documented anywhere (I can find), it is certainly considered when opening the SSH connection. To show that, I changed the username in my SSH config to an incorrect one (`ber`).

Then, while
```
vscode://vscode-remote/ssh-remote+host/home/bers
```
fails to connect,
```
vscode://vscode-remote/ssh-remote+bers@host/home/bers
```
still connects fine.

**Comment by mjbvz** [comment] 2021-08-12 19:04
Possibly a duplicate of #123494

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by bersbersbers** [comment] 2021-08-16 06:43
Interesting - the issue does reproduce in

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

but not in

Version: 1.60.0-insider (user setup)
Commit: 58454f7bec838f79fe2422ab5914419147d82e40
Date: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

I can test this again once 1.60 has been released.

**Comment by mjbvz** [comment] 2021-08-16 21:38
Ok, closing this since it is fixed in insiders

**Closed by mjbvz** 2021-08-16 21:38 UTC
Labels: needs more info, markdown, webview

**Comment by bersbersbers** [comment] 2021-09-07 16:23
Verified - thanks!
