### ISSUE TITLE
Imports are not updated when moving JS/TS files.

### ISSUE THREAD

**Issue by sbmelvin** [microsoft/vscode#139858] opened 2021-12-28 21:17 UTC
Issue Type: <b>Bug</b>

When moving multiple JS/TS files, only the imports of the first file are updated. 

Does this issue occur when all extensions are disabled?: Yes 
(tested using `open /Applications/Visual\ Studio\ Code.app --args --disable-extensions` on macOS)

Steps to Reproduce:
1. Select multiple js/ts source files in the explorer.
2. Drag the files to another folder.
3. Inspect the moved files and notice that the imports in only one file have been updated.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|--crash-reporter-id b8692c04-ae0a-4a94-8da3-2ee9d270c051|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.6
gitblame|wad|8.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
py55gd98cf:30411515
vscexrecpromp3t1:30407762

```

</details>

**Comment by mjbvz** [comment] 2022-01-03 21:08
Duplicate of #105110

**Closed by mjbvz** 2022-01-03 21:08 UTC
