### ISSUE TITLE
Terminal windows missing chars after using Remote Desktop

### ISSUE THREAD

**Issue by paulelong** [microsoft/vscode#83892] opened 2019-11-03 14:12 UTC
Issue Type: <b>Bug</b>

Sometimes after I have a remote desktop session and use VSCode, then log back into the main console, the characters in the terminal window are mostly missing.  It's as if something randomly removed %90 of the characters.  Look at attached picture.

The text in question is output from ESP32 IDF log output, which is presented with different colors.  For whatever reason, text in yellow is not affected.  But white and green are.  
![vscodebug_ts2](https://user-images.githubusercontent.com/10391057/68086422-f637cb80-fe19-11e9-95ee-ba1e3fa27f9d.png)

I have to close and reopen the window to fix it.

The video card is GTX 1050 TI Version 441.08

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.17GB free)|
|Process Argv|--folder-uri file:///e%3A/Users/Paul/Documents/src/OLEDGraphics|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.4.4
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|2.1.32
live-html-previewer|hdg|0.3.0
r|Iku|1.1.7
vscode-supercollider|jat|0.0.2
python|ms-|2019.10.44104
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.1
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
r-lsp|REd|0.1.4
vscode-taskexplorer|spm|1.20.1
code-spell-checker|str|1.7.18
vscode-arduino|vsc|0.2.27
debug|web|0.23.1

</details>

![vscodebug_ts](https://user-images.githubusercontent.com/10391057/68086376-62fe9600-fe19-11e9-8a63-55be9ef7f31c.png)

**Comment by Tyriar** [comment] 2019-11-04 15:36
Looks like another case of GPU dropping textures like https://github.com/Microsoft/vscode/issues/69665

Does ctrl++, ctrl+- help work around the problem?

**Comment by alfeg** [comment] 2019-11-06 04:24
@Tyriar Yes it helps! Thanks, I were struggling with this issue for several month and restarted Code everytime.

**Comment by Tyriar** [comment] 2019-11-07 16:32
Good to hear the workaround works, closing as duplicate of #69665

**Closed by Tyriar** 2019-11-07 16:32 UTC
Labels: needs more info
