### ISSUE TITLE
Feature Request: Limit search to modified files

### ISSUE THREAD

**Issue by literalpie** [Microsoft/vscode#38965] opened 2017-11-22 15:09 UTC
When doing a search, it would be useful to have an option to limit the search to files that have been modified since the last commit.

A toggle could be added to the 'files to include' field - similar to the 'use ignore files' and 'use exclude settings' toggles in the 'files to exclude' field.

It may also be helpful to limit the search to files that are currently open. 

![image](https://user-images.githubusercontent.com/20398475/33134225-269203f0-cf6d-11e7-8fc9-b2d66560900b.png)

**Comment by roblourens** [comment] 2017-11-23 01:08
/duplicate of https://github.com/Microsoft/vscode/issues/20530

**Closed** 2017-11-23 01:08 UTC
Labels: *duplicate, search
