### ISSUE TITLE
Menus don't work correctly when narrator is running

### ISSUE THREAD

**Issue by jaduff** [microsoft/vscode#116842] opened 2021-02-17 10:26 UTC
With Narrator running, I press Alt+F to bring up the file menu. When I try to navigate down the File menu with the down arrow, it does not work. Navigating to adjacent menus with the left and right arrows also does not work. If I quit Narrator and try again, it works as expected.

**Comment by isidorn** [comment] 2021-02-17 12:20
@jaduff thanks for letting us know. However we recommend using NVDA with VS Code since we test this out regularly.
For now I can leave this issue open, even though it sounds like a problem on the Narrator side.

**Comment by isidorn** [comment] 2021-02-17 12:21
I actually prefer to close this as duplicate of https://github.com/microsoft/vscode/issues/10729
And move this issue into that one. Hope that makes sense.

**Closed by isidorn** 2021-02-17 12:21 UTC
Labels: accessibility, under-discussion

**Comment by jaduff** [comment] 2021-02-17 12:23
Thanks Isidor,

Will try NVDA.

**Comment by rbenson** [comment] 2021-02-19 19:50
@jaduff - using narrator, try the right/left arrows vs up/down.

**Comment by isidorn** [comment] 2021-02-24 12:32
Workaround for this is to turn off scan mode manually
