### ISSUE TITLE
Folder icons do not respect theme

### ISSUE THREAD

**Issue by rafakwolf** [Microsoft/vscode#12443] opened 2016-09-22 11:30 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (25b370a3ebe800ac1fedc551a47b7689aa2a5c5b, 2016-09-22T06:10:29.536Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.Install any icon theme
2.Icons to folder are always the same

**Comment by chrmarti** [comment] 2016-09-22 17:16
These appear to be independent settings currently.

**Comment by bpasero** [comment] 2016-09-22 17:39
@rafakwolf can you clarify what you mean?

**Comment by rafakwolf** [comment] 2016-09-22 17:55
@bpasero  
the "file-icon theme", menu **File -> Preferences -> File Icon Theme** changes the folder icons on file explorer  , but now no more, the icons are the same, even when the theme is changed.

sorry for my english.

**Comment by bpasero** [comment] 2016-09-22 17:59
@rafakwolf icon theme and color theme are independent from each other!

**Comment by rafakwolf** [comment] 2016-09-22 18:05
@bpasero i now that, but, **file** icons and **folder** icons are part of icon theme, right?

**Comment by bpasero** [comment] 2016-09-22 18:08
@rafakwolf yes they are, changing the icon theme should change the icons 👍

**Comment by rafakwolf** [comment] 2016-09-22 18:30
i do not like this
![capturar](https://cloud.githubusercontent.com/assets/2060578/18760878/377a5638-80d9-11e6-986d-0e6c4b0db48e.PNG)

i like this
![screenshot_folders](https://cloud.githubusercontent.com/assets/2060578/18760940/6e86dd86-80d9-11e6-9787-6bf0045a3677.png)

**Comment by robertohuertasm** [comment] 2016-09-22 23:19
@rafakwolf I guess you're using vscode-icons. If you're using the old custom functionality (you have executed the command `icons enabled` at some point) and provided that you're using the insiders version I will recommend you to do the following:

1. Execute this comand `icons disable`. Restart VSCode as per shown instructions.
2. Go to File > Preferences > File Icon Theme > VSCode Icons

This should make it work again by no using any hack at all. Close the issue if that solved your problem.

**Comment by bpasero** [comment] 2016-09-23 05:10
💣 💣 💣 💣 💣 💣 💣 💣 💣 💣

**Comment by robertohuertasm** [comment] 2016-09-23 23:40
@bpasero I'm working on next releases of the icon theme and I can confirm you that this is an issue with the Insiders version. Check this screen capture by using another file icon theme (not vscode-icons):
![bug](https://cloud.githubusercontent.com/assets/696981/18804173/ccf29620-81f7-11e6-840e-562e15f8a408.PNG)

I think this should be reopened.

**Comment by robertohuertasm** [comment] 2016-09-24 00:29
I've found an inconsistency in the code. Either `themeService.ts` is wrong or `label.ts` is. One of these files should be modified.

**themeService.ts**
![bug4](https://cloud.githubusercontent.com/assets/696981/18804645/0ed135a0-81fe-11e6-8e17-32bbd1c52054.PNG)

As you can see the injected css is creating selectors with `-name-folder.icon.folder-icon...`  but the problem is that the css classes used by folders are not honoring these selectors as they're being set as `-name-file folder-icon`, as you can see below:

**labels.ts**
![bug5](https://cloud.githubusercontent.com/assets/696981/18804673/733f628c-81fe-11e6-8803-2cd1bbd2218f.PNG)

I would change it myself but I'm not sure of what's the way you've planned to change this as you have two different options here.

**Comment by bpasero** [comment] 2016-09-24 05:58
Confirmed regression.

**Closed** 2016-09-26 08:05 UTC
Labels: bug, themes
