### ISSUE TITLE
First call to activeDebugConsole.appendLine() while debugging JavaScript doesn't appear in the debug console

### ISSUE THREAD

**Issue by MaxAbernethy** [microsoft/vscode#116043] opened 2021-02-07 16:44 UTC
Issue Type: <b>Bug</b>

1. Make an extension with a command that does:
		vscode.debug.activeDebugConsole.appendLine('foo');
		vscode.debug.activeDebugConsole.appendLine('bar');
2. Debug the extension
3. Debug a Node program in the extension host
4. Run the command twice
5. Find output in the debug console with the first 'foo' missing:
	bar
	foo
	bar

this does not repro while debugging a C++ program.
it does repro with all extensions disabled except the one making the appendLine() calls.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz (32 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.80GB (40.19GB free)|
|Process Argv|--crash-reporter-id d108af95-e6be-45c0-9fd1-f67e5197a02b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.4
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
vscode-powertools|ego|0.63.0
scriptpoints|Max|0.0.2
vectorcalculator|Max|0.0.8
vscode-azureappservice|ms-|0.20.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.5
cpptools|ms-|1.2.0
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment] 2021-02-09 15:07
@MaxAbernethy thanks for great steps I can reproduce this

The issue is that in the Debug Console we started using the `diffIdentityProvider` to only re-render the elements that changed.

@connor4312 @joaomoreno my understanding was that if I return a different diff identity for the same object that it will be re-rendered when updating children. However that is not happening, what I see is that my element does not get re-rendered even though I return a new diff id.
If I do not use the `diffIdentityProvider` this bug does not repro.
In more detail: when new text is appended to the debug console I simply update the value of the last element, I do not add new values to the tree and thus I need that last element re-rendered. I was initially using a bad `diffIdentityProvider` but I just "fixed" it and the issue still remains.

Is there some limitation with the `diffIdentityProvider` that I am unaware of? Or am I using it wrongly?

**Comment by connor4312** [comment] 2021-02-09 16:28
Something I notice in the REPL is that you call `setChildren(undefined)` to do a generic refresh of the whole tree. With the diff identity provider, if there is an existing child of the same ID it will not recurse unless `diffDepth` is specified. Are you sure that the returned ID actually changes? What you describe sounds consistent with this not happening.

**Comment by isidorn** [comment] 2021-02-09 16:35
@connor4312 thanks. I just tried specifying `diffDepth: Infinity` and that does not fix the issue.
I am sure the returned ID actually changes.

**Comment by connor4312** [comment] 2021-02-09 16:37
Okay, thanks. I'll investigate this issue myself. Do you think this is candidate worthy? I can prioritize if so.

**Comment by isidorn** [comment] 2021-02-09 16:42
@connor4312 might be a candidate. Since this might mean that output gets lost and that is ugly.
Though I am surprised only 1 user found it...

We can always do the easy fix for the recovery and I just stop using the `diffIdentityProvider` in the debug console.

**Comment by connor4312** [comment] 2021-02-09 16:46
Yea that's likely the easy fix. I'll take a look at this today and put in a candidate PR to either apply a fix if it's simple or drop the diffIdentityProvider if not.

**Comment by isidorn** [comment] 2021-02-09 16:48
Sounds good, thanks!

**Comment by connor4312** [comment] 2021-02-10 00:50
The issue was that echoing when there wasn't previously a new line appended the text to the last element in the REPL. Although this changed the ID of that element, the element also already existed in the REPL, so when a diff was done and we called getID on the existing element in the collection, the updated ID is returned.

That's the case when starting a JS debug session, since js-debug doesn't add a new line after showing the pseudo-command; the resulting ID/message is:

```
"topReplElement:23C:\Program Files\nodejs\node.exe .\main.jsfoo↵"
```

It is hard to fix this in the tree, since we don't require the diff identity provider to be given in every child mutation: there's not necessarily a point where we can cache the old ID. So I modified the repl to create a new element instead of modifying the existing one.

**Comment by connor4312** [comment] 2021-02-10 01:00
Also, does this change mean that `element.toString()` doesn't need to be part of the diff identity? Small optimization if soo.

**Comment by isidorn** [comment] 2021-02-10 11:29
@connor4312 awesome, thanks for looking into it. Yes, I was also suspecting that is in fact the issue. 
I like your fix, and I have merged in the PR. I see that you also pushed it to master - great.
I have removed the `toString()` part from the diff identity computation

**Closed by isidorn** 2021-02-10 11:29 UTC
Labels: bug, candidate, debug
