### ISSUE TITLE
cmd x also copies the code when only intending to cut the line 

### ISSUE THREAD

**Issue by Guy-Ronen** [microsoft/vscode#184135] opened 2023-06-02 08:13 UTC
Cmd X is instrumental in cutting unnecessary lines in vs code quickly - however, a side effect is that it also sets the last "copied line" to the latest line I cut. This creates an annoying impact where for example, If I want to abstract some function knowledge to a separate file and quickly cut the function from the original file - If I used cmd x, it would override the function I cmd c - which later results in multiple cmd z to revert and then copying/deleting with the mouse. 

It would be handy in cmd x would ONLY cut the line without saving it in the "last line copied" memory :)

**Comment by mjbvz** [comment] 2023-06-13 04:55
Can you please share a code example that explains the issue and what your desired behavior would look like?

**Comment by Tyriar** [comment] 2023-06-13 14:52
To cut content explicitly means put it in the clipboard. Is this [custom keybinding](https://code.visualstudio.com/docs/getstarted/keybindings) what you're after?

```json
{
  "key": "cmd+x",
  "command": "editor.action.deleteLines",
  "when": "textInputFocus && !editorReadonly"
}
```

**Comment by mjbvz** [comment] 2023-06-19 21:48
Closing as we need more info about what the issue is and expected behavior

**Closed by mjbvz** 2023-06-19 21:48 UTC
Labels: triage-needed
