### ISSUE TITLE
PHP one-line functions syntax highlighting

### ISSUE THREAD

**Issue by BenjaVR** [Microsoft/vscode#11476] opened 2016-09-02 22:15 UTC
If I use one-line functions in my PHP files, they don't get highlighted. If I use new lines, the highlighting works as espected. Is it possible to fix this?

![screenshot](https://i.imgur.com/keW7JJj.png)

**Comment by aeschli** [comment] 2016-09-05 06:02
duplicate of #8739

**Closed by aeschli** 2016-09-05 06:02 UTC
Labels: languages basic
