### ISSUE TITLE
Website for Visual Studio Code states "Free. Open Source." which is extremely misleading given the download button below is leading to EULA licensed proprietary software. Please don't mislead users intentionally

### ISSUE THREAD

**Issue by JonasT** [microsoft/vscode#17996] opened 2017-01-01 20:07 UTC
The main landing page https://code.visualstudio.com for Visual Studio Code currently does the following:

1. it states the offered version is "Free. Open Source." which suggests free software to anyone who knows what the difference of "free" and "open-source" in the common word use is

2. Below it immediately offers download buttons  for something licensed under https://code.visualstudio.com/License/ which is **absolutely not free software in any modern definition of the word**.

Therefore, the website's main page is right now *incorrect  and extremely misleading*, since the advertised version on the main page is not "Free." at all as stated prominently.

I am aware the actual licensing page clears this up in a small remark at the top, but anyone just browsing to the main page and thinking about downloading it is almost guaranteed to be misled, and they might even think they got something under a free software license without realizing by downloading they just agreed to a classic non-free EULA which doesn't respect many basic user rights like disassembling and analyzing the software, or providing the software to others as a hosted solution and other non-free restrictions.

Please fix the labeling on the main page and clearly advertise the non-free version on the website as what it is, and stop misleading users.

---
Also, this has been brought up before and you have refused to do so, but I implore you to simply abandon this model entirely. All this confusion and naming mess is just because you insist on twisting a free software into some weird proprietary branded spin-off that doesn't add much except a logo. As you can see, all it leads to is confusion, misleading remarks and even borderline false advertising, which is absolutely not worthy of a company that is clearly trying to embrace open-source and free software and getting rid of their old image from the past.

Please note it is possible to write binding trademark / branding guidelines to allow protected use of a name like "Visual Studio" in a free software product by the community, so you wouldn't need to do this just to be able to brand Visual Studio Code nicely.

Edit:  the full source of that version isn't available either, is it? It is altered from the GitHub variant after all - so the main download is probably not even "Open Source." in a strict definition of the expression, as strongly suggested by the landing page...

**Comment by mac-pro** [comment] 2017-01-20 07:21
[FAQ page][FAQ] has one item about this issue, which points to [this answer][issues-60/comment-161792005]. I'm sorry that I don't understand clearly about the whole issue, but my opinion is, it's fair for Microsoft to do so.

I comment this in hope that that answer could help you.

[FAQ]: https://code.visualstudio.com/docs/supporting/faq
[issues-60/comment-161792005]: https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

**Comment by JonasT** [comment] 2017-01-20 07:30
@mac-pro the problem is that the main page is *very* misleading. I am aware the download page and other pages have notes about this, but the main page very openly suggests you're about to download software under a free software license, while the big fat download button actually makes you agree to some corporate EULA.

Of course Microsoft is free to do this, but is it so weird to ask that they do it in a less misleading way?

As I have suggested on #17994 Oracle has many branded proprietary versions of open-source products. However, unlike VS Code, they are clearly named ("Virtualbox" vs "Virtualbox OSE", instead of "VS Code" and "Code - OSS Dev" (???)) and the download page makes it obvious when you're downloading the corporate EULA'd version.

**Comment by JonasT** [comment] 2017-01-29 14:17
I just updated the text to make it more clear that this ticket is first and foremost about the labeling and the main page being misleading, and not so much about the release model chosen (which has apparently been discussed already on this issue tracker).

**Comment by slodki** [comment] 2017-06-14 14:30
> [MICROSOFT SOFTWARE LICENSE TERMS](https://code.visualstudio.com/License)
> MICROSOFT VISUAL STUDIO CODE
> 
> These license terms are an agreement between Microsoft Corporation [...] They apply to the software **named above**. 
> [...]
> The software contains **third party components** licensed under **open source** licenses with source code availability obligations
> [...]
> You **may not** [...] reverse engineer, decompile or disassemble the software, or otherwise **attempt to derive the source code** for the software 

> [Visual Studio Code - Open Source](https://github.com/Microsoft/vscode)
> [...]
> Licensed under the MIT License.

1. **Microsoft Visual Studio Code** distributed free of charge from code.visualstudio.com is a proprietary closed source product, licensed from Microsoft under EULA, build with open-source components
2. There is a wrong statement at code.visualstudio.com saying "Free.  Open source." while users are not allowed to attempt to derive the source code. This should be changed.
3. **Visual Studio Code - Open Source** is different product, distributed on GitHub (not from code.visualstudio.com), licensed from Microsoft under MIT open source license, distributed as binaries by third parties with limited functionality compared to [1].
4. There are wrong links in [README.md](https://github.com/Microsoft/vscode/blob/master/README.md) pointing to different product website and binaries. This references to different closed-source product should be removed OR moved to "Similar product" section in README.md with differences detailed description (licensing, functionality, customisation etc.)

There are two bugs (one on code.visualstudio.com, second on GitHub) to be removed.

**Comment by slodki** [comment] 2017-06-16 17:54
Next place where wrong information is pesentedat Microsoft side and must be fixed: https://code.visualstudio.com/docs/supporting/faq#_is-vs-code-free

**Comment by clarkis117** [comment] 2017-07-13 23:53
I’ve been struggling to find a straight answer on whether Visual Studio Code is free for Commercial use… anyone know?

**Comment by JonasT** [comment] 2017-07-14 22:44
@clarkis117 you should probably ask this in a separate ticket or in a forum. Also it might depend on what you mean by commercial use (resell visual studio itself, or sell a program made with it, ..) and which edition you use (the open-source self-built one or the proprietary build from the website).

**Comment by sam0x17** [comment] 2018-06-19 14:04
Yeah, frankly Microsoft should MIT license this. That is if they want developers not to hate them.

**Comment by mcdan** [comment] 2018-06-19 14:07
@sam0x17 is it not MIT licensed since ~Jan 2017?

https://github.com/Microsoft/vscode/pull/17684

**Comment by superamadeus** [comment] 2018-06-19 14:19
> absolutely not free software in any modern definition of the word

![image](https://user-images.githubusercontent.com/8728882/41603004-0d48c514-73aa-11e8-8c29-eb711c2c7a7f.png)

It's pretty clear, and significant, that they are saying "free" as in "you don't have to pay for this".

**Comment by akatechis** [comment] 2018-06-19 14:41
Here's some more definitions, @superamadeus, from the very same page you snipped:

![free](https://user-images.githubusercontent.com/1058931/41604427-3dd89922-73ad-11e8-971b-91c7d6901a5f.PNG)

**Comment by superamadeus** [comment] 2018-06-19 14:53
@akatechis right, I’m just saying that free-as-in-cost is a modern definition of the word, and significant when talking about a product. So I don’t think it’s misleading, especially not intentionally.

**Comment by luongvo209** [comment] 2018-06-19 15:00
@superamadeus  don't forget that they are still licensing VSCode MIT : https://github.com/Microsoft/vscode/blob/master/LICENSE.txt 

With or without that word, it doesn't matter. Confusion still exists.

**Comment by sam0x17** [comment] 2018-06-19 15:06
The confusion isn't even the worst of it. The ONLY motivation Microsoft would have to run a different license on the binaries would be because they are including some sketchy telemetry/spyware code in the binary distribution that is not included in the MIT-licensed source code. They obviously aren't going to include the source code for the spyware in their repo, so this is the result.

So keep up the pressure guys. With any luck (there is already substantial coverage on hacker news and a slashdot article on the way), Microsoft will have no choice but to actually publish binaries that match the code in this repo. This is the GVFS situation 2.0.

**Comment by superamadeus** [comment] 2018-06-19 15:12
@luongvo209 @sam0x17 Ok, I understand the confusion now. I was being pedantic because I thought the post just being pedantic about the use of the word "free". The actual disconnect is where users assume they're downloading a build of the code in this repo, where in reality they're getting a version bundled with something else we don't see.

**Comment by bfattori** [comment] 2018-06-19 17:45
@sam0x17 You state:

> The ONLY motivation Microsoft would have to run a different license on the binaries would be because they are including some sketchy telemetry/spyware code in the binary distribution that is not included in the MIT-licensed source code.

Making a claim like this is just inflammatory. You have no idea why they would release it under a different license than the code. For example, it could be under a proprietary license due to the inclusion of patented processes that Microsoft doesn't intend to release openly. While the source is open, the particular pre-built version that Microsoft provides is not. That is Microsoft's choice under the MIT license.

Binaries are typically not something that is governed by an open source license. Most will mention that you must include the copyright with the distribution of the binary, but that is the only requirement. The confusion is real, but clearly within the defined parameters of the law.

**Comment by JonasT** [comment] 2018-06-19 18:06
> Binaries are typically not something that is governed by an open source license. 

Can you give a source for that claim? I think you are wrong.

> Most will mention that you must include the copyright with the distribution of the binary, but that is the only requirement.

Yes, usually because they *are* governed by an open source license that requires it. (E.g. MIT does require that.)

> clearly within the defined parameters of the law.

Of course. This whole discussion is because it's sketchy, unnecessarily confusing and misleading, and just plain annoying. Nobody here claims they *can't* do it, but it's certainly unusual and has no obvious benefit for anyone - unless they put in differently licensed, hidden things as @sam0x17 points out.

If there is no problematic telemetry/spyware, give it to us with an open license. You can give patented technology under an open license no problem, just needs to come with a separate patent agreement. (Google does it all the time.)

**Comment by sam0x17** [comment] 2018-06-19 18:55
> You have no idea why they would release it under a different license than the code. For example, it could be under a proprietary license due to the inclusion of patented processes that Microsoft doesn't intend to release openly. While the source is open, the particular pre-built version that Microsoft provides is not.

We know enough to know that it's either 100% arbitrary or the binaries include extra/additional code that isn'tin this repo. If it's because of patents or processes they want to protect, then either those are also included in the repo which is MIT licensed and already in the open, or this is an admission that the source code is different between the binary release and the repo, which would be super shady and outcry-inducing. So no matter what the reason, the license for the binaries should change to MIT as well, unless MS has something to hide.

**Comment by JonasT** [comment] 2018-06-19 19:04
The main page still says "Free. Open Source." followed by a big green button that makes you agree to some nasty proprietary EULA. If at all, please fix at least that if you're sticking to the licensing @ Microsoft. At this point after so much time it becomes hard to believe this misleading site design isn't intentional.

**Comment by sam0x17** [comment] 2018-06-19 19:06
> Binaries are typically not something that is governed by an open source license. Most will mention that you must include the copyright with the distribution of the binary, but that is the only requirement. The confusion is real, but clearly within the defined parameters of the law.

Whether or not what they are within the defined parameters of the law is completely irrelevant. As a vocal developer community we don't have to settle for "shady but legal". We can point out shady and complain all we want, and we are improving the community and the average quality of software out there by doing that. Why would you not aspire to improving what's out there?

**Comment by bfattori** [comment] 2018-06-19 22:44
@JonasT An example of such a case would be the MIT license, itself. It makes no specific mention of binaries anywhere in the license text. Because there is no clear definition of what "the Software" is, beyond "...a copy of this software and associated documentation files (the "Software")", it is impossible to imply source or binary form. Since open source licenses are associated with the source and not the binary, that would only imply (in this situation) the source code. If it were the BSD, GPL, or CDDL, for example, that explicitly state "binary" in some form, then it would most certainly apply to the binary.

**I don't disagree with you**, but asking a large corporation to change its licensing practices isn't something that happens overnight. The license that they have is quite permissive, suggesting that they could select another open source license to cover it. However, using another open source license, such as the Apache 2.0, with a patent grant would only serve to invalidate a number of patents that Microsoft might deem important enough to protect. They would forego their right to prosecute any patent claims against, say, Apache (creator of Apache Server, competitor to IIS) because if any of their patented processes read on the code that included an Apache license in it - then they have to give an express patent grant. This is very unfavorable to corporations that need to protect other IP.

Now, IANAL, but I've spent a fair amount of time the past 11 months getting very familiar with everything I could lay my hands on when it came to open source licensing. Again, I'm not picking any bones with you... I'm just pointing out why they might hesitate to do something about it.

**Comment by bfattori** [comment] 2018-06-19 23:05
> Why would you not aspire to improving what's out there?
@sam0x17, I do aspire to improving what is out there and I seek to do it every day. But this is a non-issue. This version, on Github, is VS Community, not vscode. Would it make everyone happy if they renamed the repo vscommunity?

**Comment by JonasT** [comment] 2018-06-20 01:05
This is really off-topic, but your statements are dangerous:

> since open source licenses are associated with the source and not the binary

I'm pretty sure there's just no legal basis for this assumption, at all. And I'm not alone reading MIT/BSD/... like that, so don't take my word for it. Ask your lawyer! (I'm not one.)

As for the other things you listed, most sound like excuses. Clearly, the main software can easily be released MIT (as evidenced by this repo), and clearly, the website is still super misleading. So whatever amount of work it might be, Microsoft should just get its stuff in order.

**Comment by luongvo209** [comment] 2018-06-20 03:00
I don't see any reasons for this discussion to go on. It's boring that we have to choose our side here - whether to accept with Microsoft in-house license or build own our binary. I really hate this. The situation like now looks like:
- Microsoft opened a restaurant and told everyone that they got free food
- In fact they offered free materials and if you want 'real' food, you have to eat what they cooked (and of course sign a bunch of agreements), which is shady by design.
- ALSO, It's obvious that everyone can see how professional chefs cook their food. But what is bullshit is that the restaurant hides the very last step where foods are being prepared on the disk and served to you. Good luck trusting that waiter. Oh wait, you signed a bunch of agreements beforehand, remembered? 
- Someone noticed the process and informed the community. And now look where we are. Arguing about priorities for choosing a shady thing? Redefine what "free" means? Bashing a conventional license like MIT, which just works anywhere else except this restaurant?  
  
To be honest, we could all choose to support another restaurant from the beginning. Plus, I have a feeling like we are being treated like beggars.

**Comment by bfattori** [comment] 2018-06-20 13:44
@JonasT You're right that the MIT is a questioned license in its simplicity. There is a faction  that believes that the MIT has patent protection _implied_ as well. That is the problem with short licenses that don't go into detail. People will _assume_ how it's interpreted, legally or not, and manipulate it to mean whatever they desire. Regardless, Microsoft is protecting IP plain and simple. Whether it's a trade secret or a patent doesn't make a difference. Microsoft is taking VS Community and adding functionality that they want to protect, but still offer for no cost, and calling it VS Code. Sure it seems shady, but they are correct in saying that Jetbrains and other orgs do this as well. So, it seems more like a "Micro$oft is Evil!" argument rather than an argument for the benefits of open source as a whole.

Finally, from the OSI FAQ:

> Think of it this way: Open Source licenses are always applied to the source code — so if you're not distributing the source, then you're not distributing the thing to which an Open Source license applies. You might or might not distribute binaries; that's a separate question. But while some Open Source licenses allow you to distribute binary code without distributing the corresponding source, _it is only the source code that can be "open source"._

So, is it really that dangerous if it's defined at the OSI in such a way?

**Comment by JonasT** [comment] 2018-06-20 19:08
> So, is it really that dangerous if it's defined at the OSI in such a way?

That question makes no sense. Why would the OSI be legally relevant? Is it referenced from the license?

But this is all highly off-topic, and we both have no definite idea, so why are we discussing this? To everyone reading, just be *be extremely careful who you trust with license advice* - again, ask your lawyer.

**Comment by luongvo209** [comment] 2018-06-21 05:15
Let me remind you guys something and put an end to the discussion here : 
1. Github has its own "release" tab, which this project can use to release binary for different platform. Look at how Atom is doing it : https://github.com/atom/atom/releases. I don't support conspiracy but if this basic functionality is not utilized, then sorry but your arguments to protect Microsoft is clueless and we all have the right to be cynical about what Microsoft is doing. 
2. MIT license is simple because it needs to be straightforward and readable. No one give free things and attach with it a lengthy license. That would be meaningless. Also, no one ever would ever choose a simple, free license like MIT, IF THEY AREN'T REALLY WILLING TO GIVE SOMETHING FOR FREE. I don't understand how someone could try to defend Microsoft by distorting a free license and attacking its choice of vocabulary. By the way, you can't say that because a regulation doesn't mention something, you are allowed to do it. If you are human, have some basic common sense. Don't act like you can bring a Katana on a plane because they just mention knife in the regulation.
3. We don't ask anyone or any organisations to change anything. BUT WE WANT THEM TO BE RELEVANT, TRANSPARENT AND FULLY COMMITED TO WHAT THEY PROMISED. 

To the OP @JonasT , I don't see anyone with good and worthy arguments here in this issue section. Instead of supporting what is right, they are putting you in the place where everyone is questioning what is right. Seriously, ignore this. You should not waste your time here, unless someone who is directly involved in this project reply. Bring this link to reddit or HNews if you really seek support or further discussion. Abandon VSCode distributed on MS's site if you are not satisfied with it.

**Comment by sam0x17** [comment] 2018-06-21 15:09
There is nothing patent-able in VSCode, period. so that entire line of reasoning is moot. Microsoft should change the binaries to MIT.

**Comment by so-rose** [comment] 2018-06-22 23:32
My two cents:

I'm not sure why this is such an involved discussion. To me, the problem is **very, very simple**:

The text, **"Free. Open source. Runs everywhere."** is _directly above_ a **strictly proprietary binary download**.

This isn't just misleading, or protective. It's **a straight lie**, and a contextually dangerous one for what should be obvious reasons.

It may be a mistake or oversight; if so, it's a **simple thing to fix**. They could distribute an MIT licensed binary, or just remove the line claiming it's open source. We, the community, have certainly done our part to notify them that a mistake has been made through proper channels. But it would seem that these efforts go unnoticed.

Please don't misunderstand me; Microsoft has every _right_ to do this, just like I have the right to compile an open source vscode myself (as I happily do).

Yet, the apprehension felt by myself and many, many other developers about using Microsoft products is only fanned by continuing ignorance of this issue.

**Comment by akatechis** [comment] 2018-06-23 16:53
I find it interesting to contrast this situation with the controversy around Facebook, and React's (initially) modified license. At the time, I recall, the arguments were the same: "FB has every right to do this, if you don't like it, don't use it, what about company Y, etc". However, to show they were "good citizens" of the open source community, they decided to change their license.

And to preempt the responses I'm sure I'm going to get: Yes, I know it's not the same situation, yes, FB has it's own image issues with regards to data privacy, etc. I think if MS wants to repair its image in the open source community, the least it can do is be honest, and dispel any confusion about the distinction between the open source code base and their closed source binaries, especially as it's been just a couple of weeks since they announce their purchase of Github.

**Comment by rosepac** [comment] 2018-06-24 10:35
The cloud is the greatest deception that has ever existed. VC It is a deception. And the news versions much more, the next versions in the cloud. they just want us to be less owners of nothing. First we get used to using a free service (we stop using the music files, text files, programs) then they make us pay for them, in the cloud. When it is impossible to run the programs on the operating system, we will be forced to use them in the cloud. It is the new monopoly. In the software. The music. The documents. With all. The control of the data and the web is the future of your money.

Sorry for my english. I hope you understand my idea. It is all planned. -

**Comment by FiGOBLAC** [comment] 2018-07-08 03:36
"VS Code the product has a different license than the code in the repository."
[https://github.com/Microsoft/vscode/issues/60](url)

**Comment by njwest** [comment] 2018-07-27 01:39
[this meme === related](https://twitter.com/gweilo_fi/status/1022657329274138624)

**Comment by rzr** [comment] 2018-12-21 11:12
Relate-to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898259

**Comment by snow8gaia** [comment] 2019-02-22 11:10
This (https://github.com/Microsoft/vscode-docs/pull/2431) seemed like a similar problem that straight up avoids the licensing differences. So I made a really rough PR. Please add plenty of suggestions for improvement.

This should help a lot of users make an informed decision when it gets merged.

**Comment by sam0x17** [comment] 2019-02-22 16:21
While we wait for all this to be addressed forever, vscodium is a completely viable, open source licensed, tracking free version of vscode with regular binary releases on major package managers https://github.com/VSCodium/vscodium

**Comment by jonkri** [comment] 2019-05-23 14:01
I created issue #63875 about the Visual Studio Code patents, and the fact that the MIT license does not contain an explicit patent grant.

**Comment by chrisdias** [comment] 2019-05-24 16:27
The [website](https://code.visualstudio.com) was updated a few weeks back, it now says "Build on open source".

**Closed by chrisdias** 2019-05-24 16:27 UTC
Labels: license
