### ISSUE TITLE
workspace search (`search.exclude`) glob not correctly matching all .txt files

### ISSUE THREAD

**Issue by j9108c** [microsoft/vscode#137855] opened 2021-11-25 08:43 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: 
![image](https://user-images.githubusercontent.com/31039318/143408608-9f58d695-161f-4f9d-ab4c-f4cc11490412.png)

Steps to Reproduce:

1. `"search.exclude": {"**/*.txt": true}`
2. workspace search does not exclude txt files starting with "# " (e.g., "# filename.txt")

edit: it seems this only happens if the excluded file is also open somewhere in the editor. not sure if this is expected behavior, but i think it would be better to have an option to adhere to the `search.exclude` settings regardless of whether an excluded file is open or not.

**Comment by gjsjohnmurray** [comment] 2021-11-25 09:35
> edit: it seems this only happens if the excluded file is also open somewhere in the editor

/duplicate of #31819 and is mentioned at https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results

**Closed** 2021-11-25 09:36 UTC
Labels: *duplicate
