### ISSUE TITLE
[regression] Member completion introduces compilation errors in TypeScript

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#58597] opened 2018-09-13 11:09 UTC
Issue Type: <b>Bug</b>

* Good version where this is working: I have tried 1.4.0 (July 2016) which can be downloaded [here](https://code.visualstudio.com/updates/July_2016).
* There exists a feature request that is similar in spirit, #10266, but since this is a regression (i.e. a bug), IMHO it cannot be a duplicate of a feature request.

Open a folder with a single TypeScript file:
```ts
class A {
    private editor: number;

    constructor() {
        this.editor = 0;
    }
}
```

Place the cursor here: `edi|tor` and trigger ctrl+space.
Accept the completion.

---

#### working version (completion is a no-op)
![completion-bug](https://user-images.githubusercontent.com/5047891/45484872-f2e50a80-b755-11e8-987f-0cc5bd0e2a14.gif)

---

#### broken version (accepting a completion leads to compiler errors)
![completion-bug-now](https://user-images.githubusercontent.com/5047891/45484934-1f008b80-b756-11e8-9432-03c12788054a.gif)

---

VS Code version: Code - Insiders 1.28.0-insider (42ffc0e721a7d8c7d11f5d927e1810e8c17064d9, 2018-09-13T05:18:42.456Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (8.54GB free)|
|Process Argv|C:\Alex\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by mjbvz** [comment] 2018-09-18 21:15
To be fair, this has been the behavior since like VS Code 1.9 or something so not exactly a new regression... Will take a quick look to see what other editors and languages do here.

**Comment by mjbvz** [comment] 2019-01-05 02:14
I've checked in a fix for this and also have been adding pinning tests for the TS completions since they are growing quite complicated.

This is a change in a core behavior that has existed for a while so we'll need to see what the user feedback is like on it (and I'm not in favor of adding a setting to enable/disable this behavior)

**Comment by mjbvz** [comment] 2019-01-28 22:12
Reopening since we had to revert this change due to #66187

**Comment by mjbvz** [comment] 2019-05-17 23:54
I'm closing this in favor #10266  which proposes  a language agnostic setting to control this behavior. @jrieken and I also briefly discussed this when he was in Redmond over the winter, and agreed that a language agnostic setting would be better than changing the existing js/ts behavior (and then getting issues to change it back to the old way)

**Closed by mjbvz** 2019-05-17 23:54 UTC
Labels: feature-request, javascript, suggest, typescript
