### ISSUE TITLE
TypeScript auto import opens up same file in new tab, with lower cased filename.

### ISSUE THREAD

**Issue by olvrb** [microsoft/vscode#73738] opened 2019-05-14 18:16 UTC
- VSCode Version: 1.33.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open a file `Index.ts`.
2. Start writing the name of a method which would need to be imported, such as `join` from the `path` module.
3. Hit ctrl+enter to bring up the autofill menu/dropdown, then hit enter on the correct result.
4. Now, another tab will be opened, titled `index.ts` (lowercase i, as opposed to the original uppercase). `index.ts` will now have the correctly imported method, while the original `Index.ts` will remain the same. 

See video: https://i.olivrb.xyz/7ZIcDym.mp4

Does this issue occur when all extensions are disabled?: Yes.

**Comment by mjbvz** [comment] 2019-05-17 21:27
Duplicate of #55655

**Closed by mjbvz** 2019-05-17 21:27 UTC
Labels: typescript
