### ISSUE TITLE
Moving JS files only updates import path of first file moved

### ISSUE THREAD

**Issue by indignant** [microsoft/vscode#138208] opened 2021-11-30 20:09 UTC
Yes

- VS Code Version: 1.62.3
- OS Version: Catalina

Steps to Reproduce:

1. Select 2+ files in explorer
2. Drag those two files into a new folder
3. A pop up asks if you'd like to move the files (they're all listed)
4. Confirm
5. VS Code opens the first file with the relative import paths updated (needs to be saved)
6. VS Code does not update the other files or any file importing the moved files

It would be nice if it updated all of the files, preferably without the need to save each one, and also update the files importing the moved files.

**Comment by JacksonKearl** [comment] 2021-11-30 23:41
@mjbvz I see this in TS projects, is this known?

**Comment by JacksonKearl** [comment] 2021-12-01 22:13
Also cc @jrieken as I see you own workspace edits

**Comment by jrieken** [comment] 2021-12-02 08:15
Can you set log level to debug (F1 > Log Level > Debug) and find messages starting with `_performXYZEdit`? That will explain if the correct edits have been created or not

**Comment by sbmelvin** [comment] 2021-12-14 20:42
@jrieken I am also having this problem. 
VSCode: 1.63.1 
OS: MacOS Monterey


```
[2021-12-14 15: 36: 44.881] [renderer1] [debug] 
  _performFileEdits [
  {
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes",
      "scheme": "file"
    },
    "options": {
      "folder": true
    }
  }
]

[2021-12-14 15: 36: 52.297] [renderer1] [debug] 
  _performFileEdits [
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.by.id.get.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.by.id.get.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.by.id.get.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.condition.patch.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.condition.patch.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.condition.patch.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.condition.patch.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.get.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.get.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.get.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.get.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.patch.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.patch.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.patch.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.patch.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.post.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.post.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.post.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.post.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.patch.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.patch.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.patch.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.products.patch.js",
      "scheme": "file"
    }
  },
  {
    "oldResource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.roles.patch.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.roles.patch.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/accounts.products.roles.patch.js",
      "scheme": "file"
    },
    "newResource": {
      "$mid": 1,
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.products.roles.patch.js",
      "scheme": "file"
    }
  }
]

[2021-12-14 15: 36: 57.139] [renderer1] [debug] 
_performTextEdits [
  {
    "resource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "scheme": "file"
    },
    "textEdit": {
      "text": "../account.respository",
      "range": {
        "startLineNumber": 11,
        "startColumn": 42,
        "endLineNumber": 11,
        "endColumn": 63
      }
    },
    "versionId": 3
  },
  {
    "resource": {
      "$mid": 1,
      "fsPath": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "external": "file:///Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "path": "/Users/stephen/Development/dtn/auth-services/dtn-node-account-management-service/src/routes/accounts.by.id.get.js",
      "scheme": "file"
    },
    "textEdit": {
      "text": "../logger",
      "range": {
        "startLineNumber": 12,
        "startColumn": 29,
        "endLineNumber": 12,
        "endColumn": 37
      }
    },
    "versionId": 3
  }
]
```

**Comment by sbmelvin** [comment] 2021-12-28 21:13
This bug is still present in 1.63.2.

**Comment by mjbvz** [comment] 2022-01-03 22:45
Duplicate of #105110

**Closed by mjbvz** 2022-01-03 22:45 UTC
