### ISSUE TITLE
High CPU usage when typing in editor

### ISSUE THREAD

**Issue by NuNn-DaDdY** [Microsoft/vscode#61260] opened 2018-10-18 18:31 UTC
When typing in the editor, the CPU usage spikes to over 50% from 2-3 VS Code processes. Insiders build appeared to suffer the same issue. OS/Version information below; using virtual desktop infrastructure (VDI) with a persistent desktop.

Steps to Reproduce:
1. Open Visual Studio Code
2. Start typing in editor

Does this issue occur when all extensions are disabled?: Yes

![code_2018-10-18_14-20-43](https://user-images.githubusercontent.com/3686401/47175587-7d82d180-d2e1-11e8-930f-aec3bd167e8b.png)

λ code --status

```
[15932:1018/135859.795:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

Version:          Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS Version:       Windows_NT x64 6.1.7601
CPUs:             Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (2 x 2494)
Memory (System):  32.00GB (21.78GB free)
VM:               100%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    unavailable_software
                  checker_imaging:              disabled_off
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      disabled_off
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled_readback
                  webgl2:                       unavailable_off

CPU %   Mem MB     PID  Process
    4      104   16140  code main
    2       87   19560     window (Process Explorer)
   45      231   22556     window (ΓùÅ employer-resolver.service.ts - ClientApp - Visual Studio Code [Administrator])
    0        5    6428       winpty-process
    0        7   22036         C:\WINDOWS\System32\cmd.exe /K C:\source\cmder\vscode.bat
    0       33   13372           electron_node cli.js
    0       50   15932             "C:\Users\Corey\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    0       10   19204       electron-crash-reporter
    1       73   20332       extensionHost
    0       36   11752         "C:\Users\Corey\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Corey\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20332
   23      177   22240         electron_node tsserver.js
    0       31   17672           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       11   25260       watcherService
    0       62   26132     shared-process
Workspace Stats:
|  Window (ΓùÅ employer-resolver.service.ts - ClientApp - Visual Studio Code [Administrator])
|    Folder (ClientApp): 348 files
|      File types: js(119) map(117) ts(73) html(16) json(10) scss(4) ico(1)
|                  gitignore(1) log(1) lock(1)
|      Conf files: tslint.json(2) package.json(1) tsconfig.json(1)
```

**Comment by NuNn-DaDdY** [comment] 2018-10-18 19:00
CPU Profile of issue
[CPU-20181018T145749.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2493241/CPU-20181018T145749.cpuprofile.txt)

**Comment by mjbvz** [comment] 2018-10-26 22:45
Thanks for the logs. Looks like a duplicate of #60754

**Closed by mjbvz** 2018-10-26 22:45 UTC
Labels: javascript, typescript
