### ISSUE TITLE
Multiple prompt to grant access to login keychain after always allow

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#109978] opened 2020-11-04 20:05 UTC
- VSCode Version: 1.51-Insiders
- OS Version: macOS

Originally reported in #108342 which was then re-purposed. 

@deepak1556 and me investigated but didn't find anything special from the logs `log show --start "2020-10-07 15:27:48" --end "2020-10-07 16:27:48" --predicate 'eventMessage CONTAINS[c] "Keychain"' --info --debug` and keychain info. One suspicion is maybe I'm using GitHub intensively, my setup:

* Settings Sync is using GitHub account
* GitHub PRI is using GitHub account
* GitHub Issue Notebook is also using GitHub account

On Oct 6th, I ran into SSO bad credential issue with GitHub Issue Notebook so I signed out of my GitHub account. Then I login again and grant access to all three extensions/services. I got a prompt for login keychain access once, I clicked "always allow"

On Oct 7th afternoon, I saw the prompt again.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment] 2020-11-05 00:41
@rebornix Can you copy the text of the prompt you keep seeing? Which key is it trying to access in the keychain? I'm wondering if there is anything we write that is not prefixed by the product scheme, so that switching between stable and insiders would cause the prompt to be shown again. Or are you seeing multiple prompts in a row within the same session?

**Comment by rebornix** [comment] 2020-11-06 05:08
@RMacfarlane sure I'll take screenshot when I see it again, I'm currently seeing it once a day or every other day but every time I only saw the prompt once.

**Comment by rebornix** [comment] 2020-11-09 03:48
<img width="546" alt="image" src="https://user-images.githubusercontent.com/876920/98498310-47338a00-21fb-11eb-91f8-5b7d4c58528d.png">

This is the prompt I always see when running into this issue.

**Comment by RMacfarlane** [comment] 2020-11-09 17:56
Awesome, thanks! This is actually from the Live Share extension, not anything we write in VS Code. I can reproduce this when I have it installed in both Insider's and OSS, I sign in on Insider's, run OSS and see the prompt and allow it, then restart Insider's and see the prompt again. The key isn't prefixed with anything about the current product scheme, so switching between products causes the prompt. I'm not sure why Mac doesn't just allow both, but the behavior is that it prompts again when a new process accesses it.

Closing since this is caused by the Live Share extension.

**Closed by RMacfarlane** 2020-11-09 17:56 UTC
Labels: authentication, bug

**Comment by rebornix** [comment] 2020-11-10 17:25
The "VS Code Account" made me think it's controlled by us, and yes I have Live Share installed in both OSS and Insiders. Thanks a huge ton for the investigation, you made my day!

I wonder if there is no prefix for the key, Live Share can access this info from both Insiders and Stable, right? If so users who are using both Stable and Insiders may run into it as well, should we file an issue against Live Share? cc @lostintangent

**Comment by rebornix** [comment] 2020-11-10 17:36
Thought about it again why I didn't figure out the problem myself, it's majorly because

* The prompt is controlled by macOS and we can't change the wording. By reading the prompt, I thought it was VS Code account management trying to read my account info. 
* Then I open the account management view but can only find GitHub Issue Notebook, PRI, and Settings Sync using my GitHub account info.
  * Thus I thought it was these extensions are reading the info

Is it in the long term plan that every extension moves to use the authentication api instead of reading keychains themselves?

**Comment by dpkirchner** [comment] 2020-11-23 23:07
Given the permissions dialog doesn't or can't show useful context, could you add an indicator to the Code window indicating the specific extension or feature that caused the prompt to appear? Alternatively, could you add a way to log these permissions requests including service and account, basically whatever's passed to keytar, and the extension or feature that triggered the request?
