### ISSUE TITLE
JSDoc @example tag breaks syntax highlighting

### ISSUE THREAD

**Issue by Antonius-S** [Microsoft/vscode#67916] opened 2019-02-05 11:09 UTC
- VSCode Version: 1.30.2
- OS Version: Win7 x64

Steps to Reproduce:

The following code
```js
/**
 @example
 */
'use strict';
console.log();
```
disables syntax highlight for lines after JSDoc comment. Adding `*` before `@example` solves the problem but these asterisks are optional. One-line comment `/** @example */` breaks highlight as well.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by myfonj** [comment] 2019-02-05 13:50
NB `@example` without following content in the JSDoc comment is quite useless or even invalid.  Docs state that 
> "The text that follows this tag will be displayed as highlighted code."
-- http://usejsdoc.org/tags-example.html

Meaning that starting line following the `[*] @example [<caption></caption>]` up to next `[*] @tag` occurance in the JSDoc commentis considered example body

Not that it is a good thing that it breaks highlight, but it seems to be instance of "syntactic error in nested language breaks highlight in the host", described in #20488 and its dupes.

**Comment by Antonius-S** [comment] 2019-02-05 14:09
@myfonj tag content was empty just for shortness, the same bug happens when there is something
```js
/**
  @example
  foo bar
 */
'use strict';
console.log();
```
Interesting that adding any tag after the example removes error:
```js
/**
  @example
  foo bar
  @author foo
 */
'use strict';
console.log();
```
Currently I'll use it as workaround

**Comment by myfonj** [comment] 2019-02-05 15:06
Ah, you are right, it is wonky even with content present, and even indentation makes difference: apparently NOT indenting (preceding with space) the closing `*/` makes it work differently in certain scenarios, but after all it probably makes sense, because without some "indentation contract" parser could not tell what falls into example body and what is comment terminator.

Anyway, have you tried it with those leading stars?  From docs it seems that it is not possible (?) to use bare `[start of line and indent]@tag`, only `[start of line and indent] * @tag` is shown everywhere.

<details>

![image](https://user-images.githubusercontent.com/1761395/52281996-95996200-295f-11e9-9fa7-c22f77a4a893.png)

</details>

**Comment by Antonius-S** [comment] 2019-02-05 15:21
> Anyway, have you tried it with those leading stars? From docs it seems that it is not possible (?) to use bare `[start of line and indent]@tag`, only `[start of line and indent] * @tag` is shown everywhere.
Yeah, with leading *'s seems working. But any other comment works fine without leading *'s; I previously developed in a simpler textpad so adding a * before every line manually was a pain in the ass. I tried without them and JSDoc consumed it.

**Comment by mjbvz** [comment] 2019-02-05 19:22
Duplicate of #66247

Should be fixed in insiders

**Closed by mjbvz** 2019-02-05 19:22 UTC
Labels: javascript
