### ISSUE TITLE
Menu short-cut keys will no active if current language is not English

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#41240] opened 2018-01-07 11:12 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.5
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1. Switch keyboard to ather language expect EN like Microsoft Pinyin for Chinese input.
2. Call Menu, then press any key (eg. Press Alt + F, N), it will input a N in edit and the keyboard will show, but the menu no active(not create a new file).

Reproduces without extensions: Yes/No

**Comment by ywaby** [comment] 2018-01-07 12:09
it same at linux. 
only Reproduces when you are in input mode before  Press Alt + F, N. i think reason is chromium  not change input state to disable when menu active. 
it's chromium problem, you can Reproduces it in chromium. you can create an issue at https://bugs.chromium.org/p/chromium/issues/list or find one already existing there and add a link to it here.

**Comment by bpasero** [comment] 2018-08-17 06:17
Duplicate of #52935

**Closed by bpasero** 2018-08-17 06:17 UTC
Labels: bug, electron, upstream, workbench-menu
