### ISSUE TITLE
openFilesInNewWindow is off, but always without effect

### ISSUE THREAD

**Issue by wanzhende** [Microsoft/vscode#19790] opened 2017-02-03 06:32 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:21:13.228Z)
- OS Version: Linux x64 4.9.0-deepin1-amd64
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

setup openFilesInNewWindow: "off";

**Comment by bpasero** [comment] 2017-02-03 08:35
@wanzhende can you share more details what is not working as expected in your setup?

**Comment by chris48s** [comment] 2017-02-04 17:03
I have the same issue on Ubuntu MATE 16.04 since the 1.9.0 update. Setting `"window.openFilesInNewWindow": "off"` or `"window.openFoldersInNewWindow": "default"` results in files being opened in new window instance.

**Comment by bpasero** [comment] 2017-02-05 08:04
@chris48s can you share some steps for me to reproduce and/or maybe a video that demonstrates the problem?

**Comment by chris48s** [comment] 2017-02-05 12:11
Sure - hopefully this helps:

![gifrecord_2017-02-05_120417](https://cloud.githubusercontent.com/assets/6025893/22626032/c9357062-eb9b-11e6-9182-07dbc23d1af0.gif)

its all a bit squashed as an embedded image, but if you open in a new tab, you can actually read all the text :)

**Comment by bpasero** [comment] 2017-02-05 15:45
@chris48s thanks, I can reproduce now.

**Comment by bpasero** [comment] 2017-02-06 06:29
@chris48s for some reason I can not reproduce with our insider release which contains more fixes after the release. Could you give it a try?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by chris48s** [comment] 2017-02-06 09:31
I tried the insider build and that doesn't fix it for me. I still see the same behaviour described above.

**Comment by bpasero** [comment] 2017-02-06 09:40
@chris48s can you try to open a file from the command line instead of using the desktop menu? e.g.
* open VS Code once to have a window open
* from the command line run "code <file>"

=> does it open a new window or existing?

**Comment by chris48s** [comment] 2017-02-06 19:10
Opening a file with `code myfile.txt` on the command line opens the file in a new tab in the same window (the desired behaviour) but from the right-click menu it still opens in a new instance.
What does that mean?

**Comment by bpasero** [comment] 2017-02-07 06:10
@Tyriar any idea? could this be some behaviour on Linux when using the native explorer to open a file that causes this?

**Comment by Tyriar** [comment] 2017-02-09 17:26
Actually I expect this to be fixed in 1.9.1, can you test on latest stable @chris48s?

**Comment by chris48s** [comment] 2017-02-09 18:56
Yes. Upgrading to 1.9.1 fixes this - thanks

**Comment by Tyriar** [comment] 2017-02-09 18:59
Great, this is a duplicate of https://github.com/Microsoft/vscode/issues/19775 then

**Closed by Tyriar** 2017-02-09 18:59 UTC
Labels: bug, needs more info
