### ISSUE TITLE
Opening terminal gives "Cannot set property 'innerHTML' of undefined"

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#7313] opened 2016-06-07 10:16 UTC
- VSCode Version: 1.2.0-insider (24e811)
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Open integrated terminal
2. Type e.g. 'dir' and press enter
3. Toggle/close integrated terminal
4. Toggle/open integrated terminal

Expected: Terminal opens
Actual: Error: Cannot set property 'innerHTML' of undefined

Problem exists both with cmd.exe as terminal, and with `"terminal.integrated.shell.windows": "\\Program Files\\Git\\Bin\\bash.exe"`

**Comment by tht13** [comment] 2016-06-08 11:01
Error occurs on this [line](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-
[vs-code-terminal-error.txt](https://github.com/Microsoft/vscode/files/304581/vs-code-terminal-error.txt)
[vs-code-terminal-error.txt](https://github.com/Microsoft/vscode/files/304582/vs-code-terminal-error.txt)

browser/terminalInstance.ts#L139)
See chrome debug log attached

**Comment by Tyriar** [comment] 2016-06-09 02:54
Duplicate of https://github.com/Microsoft/vscode/issues/7357, already fixed for June :+1:

**Closed by Tyriar** 2016-06-09 02:54 UTC
Labels: bug, integrated-terminal, windows
