### ISSUE TITLE
TS error stays around

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12798] opened 2016-09-27 17:38 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

Testing #12633 

Steps to Reproduce:

1. Rename file referenced by other file
2. Other file shows error
3. Rename first file back
4. Unexpected: Error stays

![ts-compile-error-stays-around](https://cloud.githubusercontent.com/assets/9205389/18884964/8888ec9c-849e-11e6-8c46-b3587d0ce933.gif)

[Info  - 10:32:20 AM] Using tsserver from location: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/server/typescript/lib/tsserver.js
[Trace - 10:32:20 AM] Sending request: open (0). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "fileContent": "import * as bar from './bar';\n\nbar.boo();\n"
}
[Trace - 10:32:20 AM] Sending request: open (1). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "fileContent": "export function boo() {\n    console.log('boo');\n}\n"
}
[Trace - 10:32:20 AM] Sending request: geterr (2). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/Users/chrmarti/Development/repos/ts203/app.ts",
        "/Users/chrmarti/Development/repos/ts203/bar.ts"
    ]
}
[Trace - 10:32:21 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": []
}
[Trace - 10:32:21 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": []
}
[Trace - 10:32:21 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "diagnostics": []
}
[Trace - 10:32:21 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "diagnostics": []
}
[Trace - 10:33:42 AM] Sending request: open (3). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts",
    "fileContent": "export function boo() {\n    console.log('boo');\n}\n"
}
[Trace - 10:33:42 AM] Sending request: close (4). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts"
}
[Trace - 10:33:42 AM] Sending request: geterr (5). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/Users/chrmarti/Development/repos/ts203/boo.ts",
        "/Users/chrmarti/Development/repos/ts203/app.ts"
    ]
}
[Trace - 10:33:42 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts",
    "diagnostics": []
}
[Trace - 10:33:42 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts",
    "diagnostics": []
}
[Trace - 10:33:42 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": []
}
[Trace - 10:33:42 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": [
        {
            "start": {
                "line": 1,
                "offset": 22
            },
            "end": {
                "line": 1,
                "offset": 29
            },
            "text": "File '/Users/chrmarti/Development/repos/ts203/bar.ts' is not a module."
        }
    ]
}
[Trace - 10:33:43 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts",
    "diagnostics": []
}
[Trace - 10:33:43 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts",
    "diagnostics": []
}
[Trace - 10:33:48 AM] Sending request: open (6). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "fileContent": "export function boo() {\n    console.log('boo');\n}\n"
}
[Trace - 10:33:48 AM] Sending request: close (7). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/Users/chrmarti/Development/repos/ts203/boo.ts"
}
[Trace - 10:33:48 AM] Sending request: geterr (8). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/Users/chrmarti/Development/repos/ts203/bar.ts",
        "/Users/chrmarti/Development/repos/ts203/app.ts"
    ]
}
[Trace - 10:33:48 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "diagnostics": []
}
[Trace - 10:33:48 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/bar.ts",
    "diagnostics": []
}
[Trace - 10:33:48 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": []
}
[Trace - 10:33:48 AM] Event received: semanticDiag (0).
Data: {
    "file": "/Users/chrmarti/Development/repos/ts203/app.ts",
    "diagnostics": [
        {
            "start": {
                "line": 1,
                "offset": 22
            },
            "end": {
                "line": 1,
                "offset": 29
            },
            "text": "Cannot find module './bar'."
        }
    ]
}

**Comment by dbaeumer** [comment] 2016-09-28 07:32
I will investigate, but the trace shows that an error is still reported by the tsserver. There is little we can do if this is the case.

**Comment by dbaeumer** [comment] 2016-09-28 11:43
OK. The problem was that I still called realpath however the workbench and other parts didn't. After fixing this renaming back and forth works.

**Comment by dbaeumer** [comment] 2016-09-28 12:17
Reopening the issue. Even with the fix I can still reproduce this under Mac. TS bug to track: https://github.com/Microsoft/TypeScript/issues/11206

**Comment by dbaeumer** [comment] 2016-09-28 12:51
However Windows looks good.

**Comment by dbaeumer** [comment] 2016-09-28 12:54
This is getting more wired. Now I can reproduce this on Windows as well.

**Comment by dbaeumer** [comment] 2016-09-29 10:37
Moving to October. There is nothing I can do today. More fixing requires a TS update.

**Comment by dbaeumer** [comment] 2016-10-26 07:54
This got fixed with the latest upgrade to TS 2.0.6 were we now use one inferred project.

**Closed by dbaeumer** 2016-10-26 07:54 UTC
Labels: bug, needs more info, typescript
