### ISSUE TITLE
The code is unclear when I use VSCode, but Atom not.

### ISSUE THREAD

**Issue by mikisama** [Microsoft/vscode#56733] opened 2018-08-18 08:48 UTC
- VSCode Version: 1.26.1
- OS Version: MacOS Mojave Beta

Steps to Reproduce:

1. Just open some code with VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by kounelios13** [comment] 2018-08-18 12:17
what do you mean unclear?

**Comment by jeroenvisser101** [comment] 2018-08-21 15:04
Possible dupe of #51132

**Comment by sandy081** [comment] 2018-08-21 17:27
@mikisama Please provide proper summary, description and steps to reproduce the issue

**Comment by mikisama** [comment] 2018-08-22 01:03
This issue is on the whole the same as #51132. I‘m sorry for the lack of description. Thank you for all help!

**Closed** 2018-08-22 01:04 UTC
Labels: needs more info
