### ISSUE TITLE
Node: Prelaunchtask errors on "restart debugging" in 1.49.3

### ISSUE THREAD

**Issue by robbie-mac** [microsoft/vscode#108134] opened 2020-10-05 18:00 UTC
- VSCode Version: 1.49.3
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. Use this launch config:

```
        {
            "name": "Launch Debug Server",
            "program": "${workspaceFolder}/build/debug/server.js",
            "cwd": "${workspaceFolder}/build/debug/",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "preLaunchTask": "Build Debug"
        }
```

2. With this task configuration

```
"tasks": [
    {
      "label": "debug",
      "type": "shell",
      "command": "${workspaceFolder}/util/server.buildDebug.sh",
      "group": "build",
      "presentation": {
        "reveal": "silent",
        "panel": "shared"
      },
      "problemMatcher": []
    },
    {
      "label": "clean",
      "type": "shell",
      "command": "${workspaceFolder}/util/server.clean.sh",
      "group": "build",
      "presentation": {
        "reveal": "silent",
        "panel": "shared"
      },
      "problemMatcher": []
    },
    {
      "label": "Build Debug",
      "dependsOn":["clean","debug"],
      "dependsOrder": "sequence"
  },
  ]
```

3. Using this script for server.clean.sh

```
rm -rf build/debug
```

4. start debug session, and click restart

Node isn't stopped, therefore it doesn't release the resources, resulting in this error:
rm: cannot remove 'build/debug': Device or resource busy
Preventing the script to clean and then rebuild the component.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment] 2020-10-05 21:21
I'm not able to reproduce this. Node doesn't lock directories while running in general, e.g. you can delete a script while it's running. Please provide more reproduction information.

**Comment by robbie-mac** [comment] 2020-10-05 23:00
I was able to narrow down the cause of the issue. vscode was keeping the terminal window for the scripts open,  because of an error in my script. That terminal window was preventing removal of the folder… this can be closed.

What threw me off was that ProcessExplorer was showing that the instances (2) of Node that vscode was opening held the handle to the folder. Not the conhost.exe

**Comment by connor4312** [comment] 2020-10-05 23:30
Okay, thanks for the info. ProcessExplorer was probably showing that since the terminal is a child process of the VS Code (node) instance.

It sounds like there's no action from VS Code for this, so I will close it.

**Closed by connor4312** 2020-10-05 23:30 UTC
Labels: needs more info, new release
