### ISSUE TITLE
Sorting/ranking of code actions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33756] opened 2017-09-03 17:20 UTC
If available, it will probably be the most useful.

<img width="621" alt="screen shot 2017-09-03 at 10 18 39 am" src="https://user-images.githubusercontent.com/2193314/30005172-58854b3a-9091-11e7-81f0-fab83adc0a64.png">

**Comment by mjbvz** [comment] 2017-09-04 19:37
@jrieken Adding you since I believe this would require an API change to code actions to add a sort order or similar

**Comment by jrieken** [comment] 2017-09-05 07:01
>  add a sort order or similar

And how do you do that given there is multiple providers that only have a *local* view of the world?

**Comment by mjbvz** [comment] 2017-09-05 22:28
I'm not sure we can create a general solution. A few ideas on how some sort of ordering could be introduced though:

- Sort of error severity. If code actions had additional metadata about which error they fixed, sort so that fixes for errors are shown before fixes for warnings. We could also use the error info to group fixes by error or show error information like [VS does](https://docs.microsoft.com/en-us/visualstudio/ide/quick-actions) in its quick fix menu

- Sort by fixed error range. One idea would be to show errors that span larger ranges first. Not sure if this would be useful

- Create types of quick fixes, similar to [intellij](https://www.jetbrains.com/help/idea/intention-actions.html). Show quick fixes before other actions like refactorings

- Show actions that fix the problem higher than actions that suppress the problem. This also would require some additional metadata on the code action, similar to quick fix types.

**Comment by jrieken** [comment] 2017-09-06 08:29
Yes, it all requires enhanced API, I like the code-action-diagnostics-association, tho things need to be thought out carefully as there are also other requests in this area, like expressing a code action as text edit(s) and not just as command

**Comment by jrieken** [comment] 2017-12-11 11:46
Closing this as a dupe of #38623 and #34664 which makes code actions know the errors they fix. We will use that as sorting/grouping hint

**Closed by jrieken** 2017-12-11 11:46 UTC
Labels: api, editor-code-actions, under-discussion
