### ISSUE TITLE
"Initializing JS/TS language features" happens frequently

### ISSUE THREAD

**Issue by drayfar** [Microsoft/vscode#69988] opened 2019-03-07 21:27 UTC
Issue Type: <b>Bug</b>

I am consistently seeing "Initializing JS/TS language features" after working in VSCode for a while. It will slowly initialize after launch, then, within a few hours, goes back into the "Initializing" state and won't come back without a restart of VSCode.

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.18348

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (15.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
gitlens|eam|9.5.1
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-icons|rob|8.2.0

</details>

**Comment by drayfar** [comment] 2019-03-07 21:31
Thanks vscodebot, but the issue is not already covered by either of those two. The feature does correctly load at first, the problem is that it stops working after some time.

**Comment by gazzaf** [comment] 2019-03-11 13:14
I have this problem too. I only have 4 extensions and just 1 in common with the OP. That's the wonderful **Bookmarks** extension. Ah. Now if I disable Bookmarks and reload the problem seems to go away.
@drayfar - Can you do the same please and confirm if this resolves the issue? If so we need to contact the author of Bookmarks.

**Comment by mjbvz** [comment] 2019-03-11 18:05
Duplicate of #68896

**Closed by mjbvz** 2019-03-11 18:05 UTC
