### ISSUE TITLE
Snippet failing to function consecutively

### ISSUE THREAD

**Issue by dburles** [Microsoft/vscode#20716] opened 2017-02-16 10:23 UTC
Edit: I believe I have found the problem, typically one will realise it immediately after posting a bug report. It seems to be conflicting with an autocompletion that takes precedence:

![screen shot 2017-02-16 at 9 25 09 pm](https://cloud.githubusercontent.com/assets/319567/23017483/89c8068c-f48e-11e6-87b5-d331e155f5f6.png)

What's the workaround for that? Should the snippet be prioritised?

---

Possibly related to #11742

Behaviour:

![feb-16-2017 21-21-14](https://cloud.githubusercontent.com/assets/319567/23017355/0600c1c2-f48e-11e6-91b6-53cbd707dca4.gif)

I'm interested if anyone else can reproduce this as easily as I can, I haven't had time to dig into it any further but it's been a problem for quite a while.

This is the snippet:

```
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log($1);"
		],
		"description": "Log output to console"
	},
```

**Comment by ramya-rao-a** [comment] 2017-02-17 05:37
#1952 tracks the same problem for emmet snippets.

**Comment by jrieken** [comment] 2017-02-21 15:05
I actually cannot reproduce. @dburles Do you use tab completion to accept the suggestion? So type `log` and press <kbd>Tab</kbd> to insert or is this a selection from the suggestion widget?

**Comment by jrieken** [comment] 2017-02-21 15:08
Like, do you have these settings?

```
"editor.tabCompletion": true,
"editor.quickSuggestions": false,
```

**Comment by jrieken** [comment] 2017-03-10 15:13
Closing because a certain number of days have passed with a reply

**Comment by dburles** [comment] 2017-03-10 22:03
Sorry @jrieken not sure how I missed the notifications for the previous messages. My settings are the inverse of what you mentioned.

**Comment by jrieken** [comment] 2017-04-05 14:41
So this is what happens (assuming I correctly guessed this is JavaScript)

1. file is empty or at least doesn't use `console.log` yet
2. typing starts 24x7 IntelliSense (`quickSuggestions: true`) and further typing the word `log` selects the snippet with that prefix. Enter expands the snippet to `console.log`
3. Now the JavaScript language service sees `log` being used and adds it to the global symbol completion table which is appended to each and every set of completions (notice the icon)
4. now typing starts again, again with `log`. This time there is still the `log`-snippet but also the `log` symbol from the global table. 
5. because snippet completions are scored lower than other completions the _"new log completion"_ wins


Get around around this you can add this configuration `"editor.snippetSuggestions": "top"` which makes sure snippets always come on top on things

![screen shot 2017-04-05 at 16 33 34](https://cloud.githubusercontent.com/assets/1794099/24710805/7abd0b32-1a1e-11e7-8509-c33ba00a841d.png)

**Closed** 2017-04-05 14:41 UTC
Labels: snippets

**Comment by dburles** [comment] 2017-04-12 09:33
Thanks @jrieken, works like a charm!
