### ISSUE TITLE
Folding in Python - Hides newlines between functions

### ISSUE THREAD

**Issue by flemingtech** [Microsoft/vscode#4968] opened 2016-04-05 15:48 UTC
- VSCode Version: 0.10.11
- OS Version: Win7Sp1

Steps to Reproduce:

Before collapsing; Doesn't matter how many newlines I use.
![image](https://cloud.githubusercontent.com/assets/7074286/14288334/37286502-fb24-11e5-8780-d8c642bb2200.png)

After collapsing; I really don't think it should collapse all the newlines, it looks horrible.
![image](https://cloud.githubusercontent.com/assets/7074286/14288344/3ecdc2de-fb24-11e5-98f1-8b84833e61b7.png)

**Comment by Tyriar** [comment] 2016-04-07 02:21
Duplicate of https://github.com/Microsoft/vscode/issues/3353

**Closed by Tyriar** 2016-04-07 02:21 UTC

**Comment by inergy** [comment] 2016-06-23 18:37
@Tyriar is this truly a duplicate?  I feel that this is more of a bug with code that is already folded as well.  For example, when I have folded code and create a new line under it, my newline disappears and becomes part of the folded code above.

**Comment by Tyriar** [comment] 2016-06-24 02:56
@inergy I agree that it's a bug personally, I originally created it as such. I'll point out the fact that adding a new line immediately folds it.
