### ISSUE TITLE
Files have other files text.

### ISSUE THREAD

**Issue by stmaus** [Microsoft/vscode#21305] opened 2017-02-23 19:02 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|0.8.7|
|ionic2|Thavarajan|2.3.5|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|angular2-snippets|danwahlin|1.0.12|
|vscode-simpler-icons|davidbabel|1.3.0|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|code-runner|formulahendry|0.6.11|
|vscode-javac|georgewfraser|0.0.23|
|live-html-previewer|hdg|0.0.1|
|rest-client|humao|0.12.3|
|icon-fonts|idleberg|1.6.1|
|docthis|joelday|0.4.0|
|net-core-project-manager|ksubedi|0.3.6|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|font-awesome-codes-css|medzhidov|0.1.1|
|font-awesome-codes-html|medzhidov|0.0.4|
|code-beautifier|michelemelluso|1.6.2|
|HTMLHint|mkaufman|0.3.3|
|vs-rest-api|mkloubert|1.18.0|
|csharp|ms-vscode|1.7.0|
|ionic2-snippets|oudZy|1.0.0|
|diff|rafaelmaiolla|0.0.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.10|
|yo|samverschueren|0.9.3|
|stylelint|shinnn|0.23.0|
|react-beautify|taichi|0.3.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|cordova-tools|vsmobile|1.2.6|
|vscode-react-native|vsmobile|0.3.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. When attempting to paste large amounts of text files get corrupted with the text from another loaded file. Hard to reproduce but happens very frequently.
2.

**Comment by mjbvz** [comment] 2017-02-23 22:37
Does this still happen if you disable all extensions by launching code with `--disable-extensions`?

**Comment by mjbvz** [comment] 2017-02-27 22:38
Closing as we need more info to investigate this. I suspect an extension is the root cause

@stmaus Please try disabling all extensions and let me know if you still see this problem

Thanks

**Closed by mjbvz** 2017-02-27 22:38 UTC
Labels: needs more info

**Comment by stmaus** [comment] 2017-02-28 21:58
I believe the problem is all the beautify extensions. I closed all of them and haven't seen another occurrence. I don't know if they were conflicting or only one was the culprit.
