### ISSUE TITLE
References in C# extension most of the time not shown correctly on wide monitor

### ISSUE THREAD

**Issue by JRBonnema** [Microsoft/vscode#15700] opened 2016-11-18 07:53 UTC
![2016-11-18 1](https://cloud.githubusercontent.com/assets/23283340/20422609/b9fd64b0-ad6b-11e6-86c2-a6611a1b8e4e.png)
![2016-11-18 2](https://cloud.githubusercontent.com/assets/23283340/20422610/ba012578-ad6b-11e6-80d1-355a1dca3ca6.png)
![2016-11-18](https://cloud.githubusercontent.com/assets/23283340/20422608/b9fcf3b8-ad6b-11e6-9d6a-b002f4f33fcf.png)

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.2|

---

Steps to Reproduce:

1.    I use a wide monitor 1920-1080. 
2.   References are only shown correctly on one size of font (change with CTRL +, CTRL -). See three screenprints that are included

**Comment by ramya-rao-a** [comment] 2016-11-18 18:07
Closing as duplicate of #15389. The fix is already in the insiders build. You can use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-18 18:07 UTC
