### ISSUE TITLE
Could not install typings files for JavaScript language features.

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#27596] opened 2017-05-30 16:27 UTC
@rebornix

- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T09:59:32.734Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|angular2-snippets|danwahlin|1.0.15|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-script|eg2|0.1.9|
|cpptools|ms-vscode|0.11.2|;

---

Steps to Reproduce:

1. 安装最新版本的vscode
2. 提示（如图）：Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH
Warning: Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH (occurred again)
Tweet us your feedback.
How was your experience?
Other ways to contact us
Submit a bug
Request a missing feature
Tell us why?(130 characters left)

![image](https://cloud.githubusercontent.com/assets/13050025/26594271/944cc460-4599-11e7-8e17-9517905432f8.png)

**Comment by mjbvz** [comment] 2017-05-31 03:17
This is a duplicate of #24961

See [this comment](https://github.com/Microsoft/vscode/issues/24961#issuecomment-305040579) for the workaround we have planned for VSCode 1.13. In the next insiders build, you should be able to set `"typescript.npm"` to point to where you have npm installed to fix this issue

**Closed by mjbvz** 2017-05-31 03:17 UTC
Labels: duplicate
