### ISSUE TITLE
 Cannot read property 'getModeId' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#61355] opened 2018-10-19 22:23 UTC
Issue Id: <b>9ecc35fa-e063-d4bd-f935-515383ca6ca4</b><br /><br />*Versions* <br />- 1.29.0-insider (10/17/2018 5:16:50 AM)<br />*Stack* <br />TypeError: Cannot read property 'getModeId' of null<br />[/vs/workbench/parts/comments/electron-browser/commentsPanel.ts#230:47](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/workbench/parts/comments/electron-browser/commentsPanel.ts#L230:47)<br />    at Array.forEach (<anonymous>)<br />[/vs/workbench/parts/comments/electron-browser/commentsPanel.ts#214:26 (call)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/workbench/parts/comments/electron-browser/commentsPanel.ts#L214:26 (call))<br />[/vs/base/common/event.ts#145:15 (_onDidCloseEditor)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/event.ts#L145:15 (_onDidCloseEditor))<br />[/vs/workbench/services/editor/browser/editorService.ts#47:9 (call)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/workbench/services/editor/browser/editorService.ts#L47:9 (call))<br />[/vs/base/common/event.ts#145:15](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/event.ts#L145:15)<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#594:2 (onComplete)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L594:2 (onComplete))<br />[/vs/base/common/winjs.base.js#1191:0 (_notify)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L1191:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1057:0 (complete)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L1057:0 (complete))<br />[/vs/base/common/winjs.base.js#1834:0 (argDone)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L1834:0 (argDone))<br />[/vs/base/common/winjs.base.js#1859:0](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/winjs.base.js#L1859:0)<br />    at <anonymous><br />    at process._tickCallback (aaaaaaaaaaaaaaaaaaaaaaaaaaaaa:188:7)<br />

**Comment by RMacfarlane** [comment] 2018-10-23 22:06
Duplicate of https://github.com/Microsoft/vscode/issues/61027

**Closed by RMacfarlane** 2018-10-23 22:06 UTC
