### ISSUE TITLE
Missing recommended extentions

### ISSUE THREAD

**Issue by MrGurto** [microsoft/vscode#65654] opened 2018-12-24 22:54 UTC
Issue Type: <b>Bug</b>

when I click recommended extentions it dont show anything

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
csharpextensions|jch|1.3.0
vscode-clang|mit|0.2.3
python|ms-|2018.12.1
csharp|ms-|1.17.1

</details>

**Comment by usernamehw** [comment] 2018-12-25 22:40
Possible duplicate of #65615

**Comment by sandy081** [comment] 2019-01-03 14:11
@MrGurto Can you please check if there are no issues connecting to Marketplace? You can check it opening Developer tools.

**Comment by francoism90** [comment] 2019-01-03 17:25
@sandy081 

This is my debug:
```
extensionHost.ts:329 [Extension Host] debugger listening on port 22084
extensionHost.ts:235 Extension Host
extensionHost.ts:236 Debugger listening on ws://127.0.0.1:22084/bbe9ff59-5a4c-4cc9-98b1-c88af255f590
For help see https://nodejs.org/en/docs/inspector

log.ts:157  INFO no standard startup: not just one text editor
console.ts:134 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
t.log @ console.ts:134
console.ts:134 [Extension Host] Sync : File Change Detected On : /home/user/.config/Code - OSS/User/workspaceStorage/../state.vscdb-journal
requestService.ts:70 XHR finished loading: GET "https://streetsidesoftware.gallerycdn.vsassets.io/extensions/streetsidesoftware/code-spell-checker/1.6.10/1525284241417/Microsoft.VisualStudio.Services.Content.Details".
```

**Comment by sandy081** [comment] 2019-10-02 14:20
I have missed this notification. Can you please try to reproduce this on latest bits and let us know if it is still the issue?

**Comment by francoism90** [comment] 2019-10-03 07:36
@sandy081 This seems to be fixed a few releases ago, working atm. :)

**Comment by sandy081** [comment] 2019-10-03 08:39
Thanks

**Closed by sandy081** 2019-10-03 08:39 UTC
Labels: needs more info
