### ISSUE TITLE
Provide a way to copy the file_path->class->method 

### ISSUE THREAD

**Issue by preethamraj27** [microsoft/vscode#129028] opened 2021-07-20 07:27 UTC
![Screenshot 2021-07-20 at 12 51 08 PM](https://user-images.githubusercontent.com/49123461/126279320-f560273c-b7d6-4bfc-89fe-232467e360e4.png)

I would like to request for a feature , that enables the copy of the path right down till the method. 
Such as file_path(relative) -> class-> method 
vscode seems to display this already, One of the suggestions is to have copy option in the right click context menu. 

Thank you so much for look at this. 
@arunvkumr

**Comment by jrieken** [comment] 2021-07-21 12:16
/duplicate of https://github.com/microsoft/vscode/issues/58678

**Closed** 2021-07-21 12:17 UTC
Labels: *duplicate, breadcrumbs
