### ISSUE TITLE
Feature Request: Ability to synchronize settings between multiple machines/operating systems via Microsoft account.

### ISSUE THREAD

**Issue by chevex** [Microsoft/vscode#22111] opened 2017-03-06 22:44 UTC
I use VSCode on my MacBook and my Windows 10 machine. I often change settings on one machine and then forget to make the same changes on the other machine. Semi-regularly I have to copy the settings file from one machine to the other to keep them in sync. This is made a little more difficult if I've made changes on both machines.

I know I can work around this with a git repository or other external solutions but it would be cool if we were able to sign into our Microsoft account from within VSCode and choose to sync editor settings to the cloud.

**Comment by ramya-rao-a** [comment] 2017-03-06 23:19
Have you tried this: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
It uses your Github account

There is no login story from within VS Code itself

**Comment by chevex** [comment] 2017-03-07 02:11
Oh sweet! Kind of what I was going to do manually but built into an extension. Not sure why I didn't think of looking there first. Thanks!

Still think this would be a cool feature in VSC itself though using your MS account :)

**Comment by ramya-rao-a** [comment] 2017-03-07 02:46
As far as I know there is no login story planned for VS Code.
@seanmcbreen @chrisdias should be able to speak more to this.

Closing the issue as your original issue has been addressed.

**Comment by chevex** [comment] 2017-03-07 02:47
Hence feature *request*

**Comment by seanmcbreen** [comment] 2017-03-07 22:34
We will log this as such for now no immediate plans for log-in support but lets add this to the list.

**Comment by jsynowiec** [comment] 2017-04-06 18:26
Isn't this one being tracked in #2743?

**Comment by yfdyh000** [comment] 2017-05-23 15:00
Duplicate of #7311.

**Comment by shanalikhan** [comment] 2017-05-23 15:23
What i suggest, to ask user if they want to sync then code should install my settings sync extension 😄 
I am planning to import export the settings - if user selects onedrive it will be sync with one drive and dropbox also - without asking user its credentails - just placing the files in user onedrive / dropbox folder and retrive from them.

**Comment by bpasero** [comment] 2017-06-03 07:37
https://github.com/Microsoft/vscode/issues/2743

**Closed by bpasero** 2017-06-03 07:37 UTC
Labels: feature-request
