### ISSUE TITLE
"Edit in settings.json" should add the key and default value

### ISSUE THREAD

**Issue by sfreed141** [Microsoft/vscode#73259] opened 2019-05-03 23:01 UTC
Issue Type: <b>Feature Request</b>

When in the settings ui some options only have an "Edit in settings.json" button. Clicking on it just brings you to settings.json, without any context or help. It would be great if it could at least add a default `"key": value` entry.

Or, even better, just have a free form text box to edit the key's value directly in the settings ui (like how the C/C++ extension settings ui works).

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment] 2019-05-03 23:39
Duplicate of https://github.com/Microsoft/vscode/issues/67908. Thanks!

**Closed by RMacfarlane** 2019-05-03 23:39 UTC
