### ISSUE TITLE
Sometimes VSCode is crazy

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode#44980] opened 2018-03-03 17:27 UTC
Hi. Always VSCode freezes my machine!
I'm just open one file to edit or directory and wait about 3-5 minutes.
VSCode make many-many child thread and eaten all available free resources (about 3GB RAM + 1GB Swap) + CPU load 12-80%.
![screenshot at 2018-03-03 20-06-49](https://user-images.githubusercontent.com/15020827/36937198-c0fec79a-1f20-11e8-88dc-6b302f5dcfb3.png)

Reproduce: right click on any file/directory -> Open with VSCode, wait 3-5 minutes

OS: Linux Mint 18.3 x64
VSCode: 1.20.1

What I'm doing wrong?

**Comment by Tyriar** [comment] 2018-03-03 18:13
@r3d9u11 could you run `code --status` and share the output?

**Comment by tweakimp** [comment] 2018-03-03 19:04
What extensions are you using?

**Comment by r3d9u11** [comment] 2018-03-03 20:52
@Tyriar 
[code_status.log](https://github.com/Microsoft/vscode/files/1777883/code_status.log)

**Comment by r3d9u11** [comment] 2018-03-03 20:52
@tweakimp 
![screenshot at 2018-03-03 23-50-12](https://user-images.githubusercontent.com/15020827/36939187-fd8a3ec0-1f3d-11e8-8047-7e8ef346ead7.png)

**Comment by r3d9u11** [comment] 2018-03-03 21:24
Well, I disabled all extensions and system not freezes now, but really slowdown with vscode (I'm tried to edit one and two files).

Here is several logs of vscode --status:
[code_status_1.log](https://github.com/Microsoft/vscode/files/1777906/code_status_1.log)
[code_status_2.log](https://github.com/Microsoft/vscode/files/1777907/code_status_2.log)
[code_status_3.log](https://github.com/Microsoft/vscode/files/1777908/code_status_3.log)
[code_status_4.log](https://github.com/Microsoft/vscode/files/1777909/code_status_4.log)
[code_status_5.log](https://github.com/Microsoft/vscode/files/1777910/code_status_5.log)
[code_status_6.log](https://github.com/Microsoft/vscode/files/1777911/code_status_6.log)
[code_status_7.log](https://github.com/Microsoft/vscode/files/1777912/code_status_7.log)
[code_status_8.log](https://github.com/Microsoft/vscode/files/1777913/code_status_8.log)
[code_status_9.log](https://github.com/Microsoft/vscode/files/1777914/code_status_9.log)

Here is screenshots of resource usage with VSCode (and two opened files):
![screenshot at 2018-03-04 00-17-10](https://user-images.githubusercontent.com/15020827/36939442-30c5c648-1f42-11e8-8163-005ce53580e2.png)
![screenshot at 2018-03-04 00-18-18](https://user-images.githubusercontent.com/15020827/36939443-30e9cb6a-1f42-11e8-94da-1eaca32119f5.png)

Here is screenshot of resource usage after VSCode closed:
![memory_after_vscode_closed](https://user-images.githubusercontent.com/15020827/36939448-519e0434-1f42-11e8-92a2-57de9178cb8d.png)

**Comment by bpasero** [comment] 2018-03-04 06:08
This sounds like https://github.com/Microsoft/vscode/issues/3998

@r3d9u11 does it change if you configure: `"files.useExperimentalFileWatcher": true`

**Comment by r3d9u11** [comment] 2018-03-04 08:02
@bpasero yes, with this option my system doesn't slow down and freezes. also RAM consumption on VSCode startup decreased (from 500MB to 300-330), thanks!

but I'll close this issue little bit later, after more several tests

**Comment by Tyriar** [comment] 2018-03-04 20:31
It could also be https://github.com/Microsoft/vscode/issues/36307

**Comment by bpasero** [comment] 2018-03-05 05:39
@r3d9u11 do you have any circular symlinks in that folder you open with VS Code?

**Comment by r3d9u11** [comment] 2018-03-05 06:13
@bpasero no, folder without any symlinks

**Comment by bpasero** [comment] 2018-03-05 06:35
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by r3d9u11** [comment] 2018-03-05 07:18
@bpasero I found strange behavior of explorer:
I have two separated logical disks: 
* sdb.EXT4 (SSD) - contains my own home directory
* sda.EXT4 (HDD) - contains data directory

when I tried to open file `/home/r3d9u11/source.nim:`
![1](https://user-images.githubusercontent.com/15020827/36961887-4f62eeb0-205e-11e8-8cea-14d785ca9c49.png)

and when I tried to open file `/media/data/home/user/source.nim`:
![2](https://user-images.githubusercontent.com/15020827/36961911-698cc11c-205e-11e8-8d59-628d21db0b0f.png)

the explorer expands full FS tree. maybe problem have a roots somewhere here.

**Comment by bpasero** [comment] 2018-03-05 08:50
@r3d9u11 are you saying the performance issue only shows up in the second case where many more files are opened?

We have a heuristic to look for a parent folder with a `settings.json` in a `.vscode` folder to see if any parent was ever a VS Code workspace. Is there such a `.vscode` folder in your home directory?

**Comment by r3d9u11** [comment] 2018-03-05 08:58
@bpasero yes, problem shows up only when I try to open path `/media/data/home/user/source.nim`
yes, I have hidden .vscode folder in my home directory (it contains subfolder `extensions`).

**Comment by bpasero** [comment] 2018-03-05 09:32
@r3d9u11 if you delete that one, it should be fine. what are the exact contents, can you share them?

**Comment by r3d9u11** [comment] 2018-03-05 12:14
contents of ~/.vscode?
here is:
```
$ ls -a ~/.vscode
.
..
extensions
$ ls -a ~/.vscode/extensions
.
..
msjsdiag.debugger-for-chrome-4.1.0
openfl.lime-vscode-extension-1.0.8
webfreak.debug-0.21.2
ms-vscode.cpptools-0.15.0
vadimcn.vscode-lldb-0.8.0
davidmart.theme-jsfiddle-like-syntax-vscode-0.0.6
nadako.vshaxe-1.9.3 
vscode-hxcpp-debug
kosz78.nim-0.5.29
oderwat.indent-rainbow-0.7.2
vscode-kha
```
ok, I'll try to remove this directory and do another tests

**Comment by bpasero** [comment] 2018-03-05 13:30
I pushed a fix to no longer open a folder of a file if it simply contains a .vscode folder. We now require a settings.json file in there. To verify:
* shutdown VS Code
* from the command line open VS Code pointing to a file where the parent contains a ".vscode" folder
* verify we do not open the parent folder
* now try again but this time have a settings.json in there and it should open that folder instead

**Comment by roblourens** [comment] 2018-03-28 22:55
Now it never opens the whole folder, even when a .vscode/settings.json file is present...

**Comment by bpasero** [comment] 2018-03-29 05:58
@roblourens yes we took this entirely out. If the users intent is to open a file, we do exactly that.

**Closed by bpasero** 2018-03-29 05:58 UTC
Labels: bug, verification-found
