### ISSUE TITLE
VSCode doesn't highlight user-defined types for c++

### ISSUE THREAD

**Issue by onecalled3bkr** [Microsoft/vscode#72785] opened 2019-04-24 05:45 UTC
We have written the needed data into your clipboar
Issue Type: <b>Bug</b>

Write any class and proceed to declare an instant of it, the class name isn't highlighted. I have read before that this has something to do with the parser and that this is related to https://github.com/atom/language-c/issues/266

If adding the tree-sitter parser fixes the problem I only ask to know how to do it. I'm fairly new to programming and my knowledge is limited. Thank you for your time.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (11.79GB free)|
|Process Argv|D:\College\First Year\Second Semester\DS\Labs\Lab6_UPDATED_Recursion_Binary_Search_Trees_S2019_std\DS_Lab5\Binary_Search_Tree|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sync|jac|1.0.4
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
subtitles-editor|pep|1.0.2

(2 theme extensions excluded)

</details>
d because it was too large to send. Please paste.

**Comment by alexr00** [comment] 2019-04-26 15:21
Duplicate of https://github.com/Microsoft/vscode/issues/50140

**Closed** 2019-04-26 15:21 UTC
Labels: *duplicate

**Comment by EvgeniyPeshkov** [comment] 2019-05-22 13:42
Hello everyone. I've developed and published syntax highlighting extension based on Tree-Sitter. It provides universal syntax coloring engine for almost any programming language (currently, C and C++ are supported OOTB). Constructing entire syntax tree, Tree-sitter efficiently overcomes all limitations of built-in TextMate grammars. Being context-aware, it's able to parse complex language structures providing complete coverage of source code. So all custom types are properly highlighted. I've been using it by myself for a month, so I suppose it's ready for public use.

[You can install it from VSCode Marketplace.](https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter)
[Or download .vsix package from GitHub page and install it manually.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
[**Please note**, that extension published in VS Code Marketplace will only work in Windows-x64](https://github.com/EvgeniyPeshkov/syntax-highlighter#distribution).
[For other operating systems, please download pre-compiled .vsix package.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
This will be fixed in the near future with one of the next updates.
Alternatively, you can [build extension from sources](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md).

@onecalled3bkr, you may give it a try, feedback is welcome.

**Comment by onecalled3bkr** [comment] 2019-05-22 14:17
Thank you so much for this extension, the syntax highlighting works so far
so good, a great solution to all my problems.
I was wondering if you can perhaps add an easy way to use Visual Studio's
syntax highlighting colors.

**Comment by EvgeniyPeshkov** [comment] 2019-05-23 18:35
Hello @onecalled3bkr . I was investigating this feature during development.
Unfortunately, VSCode API [doesn't provide access to token colors](https://github.com/Microsoft/vscode/issues/32813).
I will be glad to add such synchronization when VSCode teem resolves this issue.
