### ISSUE TITLE
Quick Fix Not working

### ISSUE THREAD

**Issue by yashp98** [microsoft/vscode#77567] opened 2019-07-18 10:01 UTC
when i update my vs code to new version .after that quick fix give suggestion but when i click on suggestion nothing happened

**Comment by afisher88** [comment] 2019-07-18 21:10
I am also having this issue. 

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134


Here are some repro steps:

1. https://github.com/afisher88/typescript-lint-test
2. `npm install`
3. `npm run dev`

Extensions required:
- ESLint
- Prettier

VSCode Settings:
`{
  "window.zoomLevel": 0,
  "workbench.iconTheme": "material-icon-theme",
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false
  },
  "eslint.autoFixOnSave": true,
  "prettier.disableLanguages": ["javascript", "javascriptreact"],
  "editor.tabSize": 2,
  "editor.autoIndent": true,
  "files.insertFinalNewline": true,
  "emmet.triggerExpansionOnTab": true,
  "git.enableSmartCommit": true,
  "git.autofetch": true,
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.colorTheme": "Night Owl",
  "git.confirmSync": false
}
`

I have created a change that throws an ESLint error in `src/pages/page1.jsx` by declaring a variable which is not used. This is highlighted as a fixable error and hovering over this displays the dialogue as expected:

![quick-fix1](https://user-images.githubusercontent.com/5710575/61492107-98858d80-a9a8-11e9-9c06-2ad2780b8826.jpg)

However, if you try clicking on one of the actions, then nothing happens:

![quick-fix2](https://user-images.githubusercontent.com/5710575/61492135-a63b1300-a9a8-11e9-93ef-b3534e182363.jpg)

**Comment by mjbvz** [comment] 2019-07-18 21:35
Duplicate of #77018

**Closed by mjbvz** 2019-07-18 21:35 UTC
Labels: editor-code-actions
