### ISSUE TITLE
OpenDialogOptions: 'openFiles = false' lets me open files

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35139] opened 2017-09-26 16:00 UTC
Testing #34821, Linux

- Use yo code to create a sample extension and set extension.ts to
```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.window.showOpenDialog({
            openFiles: false,
            filters: {}
        }).then(r => console.log(r));
    });
    context.subscriptions.push(disposable);
}
```
- run the 'sayHello' command
- select a file and press ok

**Comment by jrieken** [comment] 2017-09-27 07:39
@aeschli What would you expect? That is opens folder? The logic that if both are false, it will fallback to open files

**Comment by jrieken** [comment] 2017-09-27 10:40
closing this as duplicate of #35141

**Closed by jrieken** 2017-09-27 10:40 UTC
Labels: api
