### ISSUE TITLE
Settings Sync doesn't memory my account

### ISSUE THREAD

**Issue by jeiea** [microsoft/vscode#105017] opened 2020-08-19 18:03 UTC
- VSCode Version: 1.48.0
- OS Version: Windows 10.0.19041.450

Steps to Reproduce:

1. Make default browser open links in incognito mode.
2. Enable settings sync with microsoft account.

Does this issue occur when all extensions are disabled?: Yes

First login is successful, but it requires new login consistently.

**Comment by ghvanderweg** [comment] 2020-08-21 07:29
I have this same issue, I'm prompted to login at least once a day.
FWIW, I'm using my workplace's Azure AD account to login.

**Comment by PeterBrain** [comment] 2020-08-29 12:29
I do experience this issue as well and figured out why it is happening on my machine.
The sign-in token gets cached for 1 hour, then sometimes fail to refresh depending whether I have an internet connection or not.

Steps to reproduce:
- Open vscode with internet connection & log in to settings sync with Microsoft Authentication (verify log in)
- Now close vscode and disconnect from the internet
- Open vscode again, look at the log (View -> Open View -> Microsoft Authentication) and you can see it logs out of the session for settings sync.
- So next time you have internet (just enable your internet connection again) you have to sign in to settings sync again.

I guess this is already known to the developers, as it is not that hard to figure out what is going on and considering this feature is in preview (mentioned here at the top: [https://code.visualstudio.com/docs/editor/settings-sync](https://code.visualstudio.com/docs/editor/settings-sync)) we can't really blame them. If not, here you go, these are my findings.

Here are my log entries from View -> Open View -> Microsoft Authentication:
[Info  - 13:02:03.922] Token available from cache, expires in 3598997 milliseconds
[Info  - 08:23:47.10] Refreshing token...
[Error  - 08:23:47.27] Refreshing token failed
[Info  - 08:23:47.27] Logging out of session 'f8cdef31-...-590be7261c5e'
[Info  - 11:50:27.77] Logging in...
[Info  - 11:50:33.944] Exchanging login code for token
[Info  - 11:50:34.693] Exchanging login code for token success
[Info  - 11:50:34.697] Login successful
[Info  - 11:50:34.697] Token available from cache, expires in 3598999 milliseconds

Same issue #105121

**Comment by RMacfarlane** [comment] 2020-09-01 15:55
Closing as a duplicate of https://github.com/microsoft/vscode/issues/105503

**Closed by RMacfarlane** 2020-09-01 15:55 UTC
