### ISSUE TITLE
npm explorer: update when package.json is modified

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50789] opened 2018-05-30 13:42 UTC
Testing #50568

When adding a new script to the `package.json`, the npm scripts explorer requires a refresh.

Would be nice if the explorer tracks document and resource modifications and updates the tree automatically.

**Comment by egamma** [comment] 2018-05-30 21:07
Duplicate of #48544

**Closed by egamma** 2018-05-30 21:07 UTC
