### ISSUE TITLE
rename folder fails

### ISSUE THREAD

**Issue by Skatterbrainz** [microsoft/vscode#117523] opened 2021-02-24 01:31 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Trying to rename a folder in the explorer panel tries for about 1-2 minutes and fails.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.29GB free)|
|Process Argv|--crash-reporter-id 674d6b76-76b3-450b-8d66-3b73411ae794|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.39.0
vscode-html-css|ecm|1.10.2
rainbow-csv|mec|1.8.1
powershell|ms-|2020.6.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|11.1.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by isidorn** [comment] 2021-02-24 08:34
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Skatterbrainz** [comment] 2021-03-01 05:12
It doesn't seem to happen while using the insider build

**Comment by isidorn** [comment] 2021-03-01 07:54
Then it seems to be fixed in latest, thus closing this.
In your stable maybe some extension is also to blame, so think about that.

**Closed by isidorn** 2021-03-01 07:54 UTC
Labels: file-explorer, needs more info
