### ISSUE TITLE
Title: Unexpected Application Shutdown

### ISSUE THREAD

**Issue by markjpT** [microsoft/vscode#195398] opened 2023-10-11 19:07 UTC
Type: <b>Feature Request</b>

Steps to Reproduce:

Open the application.
Navigate to the ‘Settings’ menu.
Click on the ‘Update’ button.
Actual Result: The application shuts down unexpectedly with an error message “Application has stopped working”.

Expected Result: The application should start the update process without any errors.

Additional Information: This issue occurs on both Windows and macOS versions of the application. It seems to be more frequent when the system is under heavy load.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by legomushroom** [comment] 2024-12-19 20:56
Hi @markjpT its really hard to assist you without more information on the issue you are experiencing. Related logs/error messages/stack traces can help us to identify the root cause and help you effectively, anything you can share?
Please remember that this is a public repo, so strip out any sensitive information in the data before sharing 🔒

Few options on how to get the logs:

1. Get basic info from the `EventViewer`:
  - open the `EventViewer` (`eventvwr.msc`) and navigate to `Windows Logs` > `Application`
  - look for entries marked as "Error" that correspond to the crash timestamp
  - identify the `Faulting Module Name` and `Exception Code`, look for any relevant information that we can use to debug this
2. Enable error reporting and logging:
  - Windows Error Reporting (WER)
    - navigate to `Control Panel > System > Advanced system settings > Startup and Recovery > Settings`
    - enable `Write debugging information` and choose `Small memory dump (256 KB)` or a complete dump
    - reproduce the issue and send the memory dumps to us to analyse
3. Send us the logs generated by `VSCode` components:
  - open `Command palette`(`ctrl+shift+p` by default) and type `Developer: Open Logs Folder`, then press `Enter` to run the command
  - the logs folder will popup, try to see if the logs file contain any errors/warnings that were reported around the time of the crash and send us that information
4. Try disabling all extensions and repeating the steps that lead to the crash to validate that no faulty extension cause this.

Once you have this information please reopen this issue or create a new one 🤗
Closing this one because it is very old and not very actionable without more data.

**Closed by legomushroom** 2024-12-19 20:56 UTC
