### ISSUE TITLE
compressed diff view like git diff, Github, etc

### ISSUE THREAD

**Issue by Die4Ever** [microsoft/vscode#169941] opened 2022-12-23 17:45 UTC
viewing the diff inside VSCode is very convenient. However it'd be great if there was an option to change to the condensed diff view, like what shows up when you run `git diff` or when you view a commit on Github. This would be especially helpful for long files. Even if it didn't support the bars to click to expand context it would still be useful.

**Comment by Die4Ever** [comment] 2022-12-23 17:47
example 
![image](https://user-images.githubusercontent.com/30947252/209381668-d3299884-cd5c-4fef-a0f9-a96b733fd05f.png)

**Comment by IllusionMH** [comment] 2022-12-23 20:20
Looks like duplicate of #3562

**Closed** 2024-06-14 12:21 UTC
