### ISSUE TITLE
Arguments color in function body

### ISSUE THREAD

**Issue by donifer** [Microsoft/vscode#41885] opened 2018-01-19 21:19 UTC
Feat request:

To my understanding there is no way to get coloring of arguments inside a function's body like you can with WebStorm.

Eg: Current functionality
![image](https://user-images.githubusercontent.com/32689666/35172106-eff7d2b0-fd2b-11e7-9b96-3686e542f537.png)

Eg: Desired Functionality (taken from WebStorm)
![image](https://user-images.githubusercontent.com/32689666/35172120-0068d2a2-fd2c-11e7-9734-ff75193b704f.png)

**Comment by mjbvz** [comment] 2018-01-19 22:05
Duplicate of #585

**Closed by mjbvz** 2018-01-19 22:05 UTC
Labels: javascript
