### ISSUE TITLE
minimap jump to area

### ISSUE THREAD

**Issue by kh0m** [Microsoft/vscode#29328] opened 2017-06-23 14:05 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.3.1|
|Ruby|rebornix|0.12.1|
|vscode-icons|robertohuertasm|7.9.0|
|vim|vscodevim|0.8.7|;

---

Steps to Reproduce:

1. open any source file that requires scrolling
2. with minimap enabled, click an area of the map that is not under the shadow, and hold the click
3. while still holding the click, try to drag the shadow to a desired area

The expected behavior is to be able to drag the shadow up and down, as you are able to do with the regular scroll bar. However when following the above steps, the shadow is not automatically selected after the scroll position jumps to the area that you initially click in step 2. Instead you have to release and reclick to have the shadow be selected.

**Comment by alexandrudima** [comment] 2017-06-27 07:40
Duplicate of #21708

See https://github.com/Microsoft/vscode/issues/21708#issuecomment-283600344 for an explanation

**Closed by alexandrudima** 2017-06-27 07:40 UTC
Labels: editor
