### ISSUE TITLE
Artifacts on dark themes

### ISSUE THREAD

**Issue by worldadmin** [microsoft/vscode#101755] opened 2020-07-05 13:40 UTC
Version: 1.47.0-insider
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:15:57.898Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.7-arch1-1

![изображение](https://user-images.githubusercontent.com/66319058/86534051-fc101000-bec4-11ea-83f3-61792cca837d.png)

**Comment by worldadmin** [comment] 2020-07-05 13:59
![изображение](https://user-images.githubusercontent.com/66319058/86534407-c6b8f180-bec7-11ea-8a82-4523997fa698.png)

**Comment by worldadmin** [comment] 2020-07-05 14:05
![изображение](https://user-images.githubusercontent.com/66319058/86534524-a3427680-bec8-11ea-8623-1759394a68b8.png)

**Comment by IllusionMH** [comment] 2020-07-06 09:46
/duplicate of #85452
See https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for better approach to disable HW Acceleration without constantly passing flag.

**Closed** 2020-07-06 09:47 UTC
Labels: *duplicate
