### ISSUE TITLE
Manage font for rendered markdown code in Native Notebooks?

### ISSUE THREAD

**Issue by nickeubank** [microsoft/vscode#128164] opened 2021-07-07 19:31 UTC
Maybe there's a way to control this I don't see, but don't love the default slightly greyed, san serif and relatively small font markdown cells render into. Is that adjustable, and if not, would that be possible?

**Comment by joyceerhl** [comment] 2021-07-07 21:28
Possible duplicate of https://github.com/microsoft/vscode/issues/126294

**Closed** 2021-07-08 02:15 UTC
Labels: *duplicate
