### ISSUE TITLE
Any code prompt is "loading"

### ISSUE THREAD

**Issue by WWongs** [microsoft/vscode#88588] opened 2020-01-14 06:55 UTC
- VSCode Version:
版本: 1.41.1 (user setup)
提交: 26076a4de974ead31f97692a0d32f90d735645c0
日期: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version:
windows 10

Steps to Reproduce:
1. Open the project and the code will prompt.
2. Any new code is entered and the prompt becomes loading.
![image](https://user-images.githubusercontent.com/31298228/72320973-ae68d680-36dd-11ea-96e5-aee947f4ba42.png)
3. You can't even format the code shift+ Alt +f.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-01-14 20:36
Where is your code stored? Somewhere besides the `c:` drive?

**Comment by WWongs** [comment] 2020-01-15 01:43
> 您的代码存储在哪里？除了`c:`驱动器之外的其他地方？

Yes, I store the code on D disk.But some of the other items on disk D have smart prompts.

**Comment by mjbvz** [comment] 2020-01-15 02:14
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-15 02:14 UTC
Labels: needs more info
