### ISSUE TITLE
Type intellisense in javascript is missing in 1.14.0

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#30580] opened 2017-07-13 06:48 UTC
- VSCode Version: Code 1.14.0 
- OS Version: Ubuntu 17.04
- Extensions: I had try disabled all extensions for verifying this problem is not caused by extension

---

Before upgraded VS Code to 1.14.0 . I usually write javascript codes with jsDoc (such as "@type" "@param" "@returns" and more) for getting better intellisense in javascript file.

But I found the type intellisense in **1.14.0** is missing, like follow screenshot:

![2017-07-13 14-38-04](https://user-images.githubusercontent.com/4303130/28153622-ef253532-67d8-11e7-963c-4aa3bc7c6304.png)

I mark this variable `a` type as `GameController`(I declare this type in `src/main/index.d.ts`). But I could not get any intellisense when I type `GameController`.

--- 

But same code in VS Code **1.13.1**. I could get intellisense around `GameController`, like this:

![2017-07-13 14-41-43](https://user-images.githubusercontent.com/4303130/28153685-6bb61030-67d9-11e7-848d-4fcb4bbcaf6f.png)

(P.s. This type intellisense missing is occurred for all type included basic type (number, string, Function ...)

Are you removed this intellisense in 1.14.0? Or it is a bug?   
I could only downgrade version to 1.13.1 to obtain this intellisense now.

Thanks for reading.

**Comment by Juanjofp** [comment] 2017-07-13 07:02
Same on MacOS Sierra 10.12.5 with VC 1.14.0

**Comment by istarkov** [comment] 2017-07-13 07:22
I found that even empty `{}` jsconfig.json in folder root breaks all things like cmd click, intellisense and type showing on mouse hover.
VC 1.14.0 MacOs
Without it all works but I see no possibility to provide `baseUrl` and `include` options

**Comment by SeanChenU** [comment] 2017-07-13 07:55
Seems like downgrading is the only possible solution currently
https://code.visualstudio.com/updates/v1_13

**Comment by dperfetto** [comment] 2017-07-13 16:28
Same problem here on windows 10 and VSCode v1.14.0.
 Downgrading to v1.13 solve the problem.

**Comment by fossage** [comment] 2017-07-14 06:43
Same issue here on mac v.10.11.6 and VSCode v1.14.0.  I've noticed that the intellisense works when I first open the editor, but after I've hovered on something once, it looks like the typescript server crashes and I get the following output:

```bash
[Error  - 11:41:12 PM] 'quickinfo' request failed with error.
Error processing request. Project '/Users/new/Desktop/webdev/Volt/client_react_native/jsconfig.json' does not contain document '/users/new/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
Error: Project '/Users/new/Desktop/webdev/Volt/client_react_native/jsconfig.json' does not contain document '/users/new/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:75718:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77238:42)
    at ConfiguredProject.Project.getScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77243:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76551:51)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:84
    at Object.map (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1483:29)
    at ModuleBuilder.getReferencedFileInfos (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:31)
    at ModuleBuilder.updateFileReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76708:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76693:30)
    at ModuleBuilder.onProjectUpdateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76684:22)
```

**Comment by mjbvz** [comment] 2017-07-14 18:02
@fossage That looks like a duplicate of Microsoft/TypeScript#17131 

This could also be https://github.com/Microsoft/TypeScript/issues/16610 . @hangxingliu  can you please check the Typescript section of the output panel to see if there are any errors reported?

**Comment by pmaroncelli** [comment] 2017-07-14 18:55
Same problem here. Intellisense in my typescript project stopped working since upgrading to 1.14. Downgrading to 1.13 solved the problem.

**Comment by kingdaro** [comment] 2017-07-14 19:32
If it helps, I'll add that the intellisense seems to be missing in TS when typing in function parameters as well, but works fine in other places.

![](http://i.imgur.com/lR5oOn2.gif)

**Comment by mjbvz** [comment] 2017-07-14 20:30
@kingdaro Can you please check the `TypeScript` output panel to see if any errors are printed?

**Comment by kingdaro** [comment] 2017-07-14 20:41
Ah, looks like the issue you pointed out hit the nail on the head.
```
[Error  - 4:41:07 PM] 'completions' request failed with error.
Error processing request. Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at symbolsToArray (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:27963:20)
    at Object.getExportsOfModuleAsArray [as getExportsOfModule] (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:24316:20)
    at symbolCanbeReferencedAtTypeLocation (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62889:55)
    at d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62853:36
    at Object.filter (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:1439:25)
    at filterGlobalCompletion (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62839:27)
    at tryGetGlobalSymbols (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62835:27)
    at getCompletionData (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62727:22)
    at Object.getCompletionsAtPosition (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:62347:34)
    at Object.getCompletionsAtPosition (d:\Projects\falling-box\node_modules\typescript\lib\tsserver.js:74367:35)
```

**Comment by jasperjn** [comment] 2017-07-17 03:03
Works for me, downgrade VSCode Typescript 2.4.1 to workspace version 2.3.4 solved this issue.  Don't need to fall back to VSCode 1.13

**Comment by raulk** [comment] 2017-07-17 13:57
I kept Typescript 2.4.1 and downgraded VS Code to 1.13.1, and still encountered the same issue :-(

**Comment by mjbvz** [comment] 2017-07-17 16:33
I'm working with the TypeScript team to try to get this resolved. There does not appear to be anything we can do on the VSCode side to workaround this. We're looking into whether we can take a new TypeScript build into a potential VSCode 1.14.2 build

Until then, please try downgrading to TypeScript 2.3.2 by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed** 2017-07-19 21:50 UTC
Labels: bug, javascript, new release, upstream
