### ISSUE TITLE
Terminal can't use Nerd Font

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#119364] opened 2021-03-19 22:29 UTC
Issue Type: <b>Bug</b>

VSCode doesn't allow the use of Nerd Font Iosevka.
This is a screenshot from VSCode and Terminal, both using the same font (which is an adapted version of Iosevka, made by Nerd Fonts)

![image](https://user-images.githubusercontent.com/379339/111848232-5b923c80-88e9-11eb-8019-cce6ab676dca.png)

VS Code version: Code 1.54.3 (Universal) (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (15.05GB free)|
|Process Argv|--crash-reporter-id 7bb35bdf-5f60-46ac-8de0-7ce213087b0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
separators|ale|2.0.0
flutterpubopen|And|0.0.1
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
gitlens|eam|11.3.0
vscode-google-translate|fun|1.4.12
todo-tree|Gru|0.0.207
output-colorizer|IBM|0.1.2
pubspec-assist|jer|2.2.1
svg|joc|1.4.5
bracket-peek|jom|1.4.2
vscode-gutter-preview|kis|0.27.1
dart-import|lua|0.3.1
csharp|ms-|1.23.9
awesome-flutter-snippets|Nas|2.0.4
vscode-xml|red|0.15.0
multi-command|ryu|1.5.0
swdc-vscode|sof|2.5.3
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.9.0
errorlens|use|3.2.5
vscode-icons|vsc|11.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by meganrogge** [comment] 2021-03-29 17:03
Duplicate of #73879

**Closed** 2021-03-29 17:03 UTC
Labels: *duplicate, integrated-terminal
