### ISSUE TITLE
Unable to install extensions via proxy, even --ignore-certificate-errors no longer works

### ISSUE THREAD

**Issue by cggac** [microsoft/vscode#93595] opened 2020-03-27 18:00 UTC
- VSCode Version: 1.40.1-1573664190
- OS Version: Debian 9.4

Steps to Reproduce:

1. Launch code while behind a proxy which decrypts all traffic
2. Attempt to search for an extension

Does this issue occur when all extensions are disabled?: Yes

I can see in the network developer tools that this is a certificate issue, the output is:
marketplace.visualst…ry/extensionquery:1 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID

![error1](https://user-images.githubusercontent.com/62764806/77785811-9e159600-7054-11ea-9e7e-279e42786c21.png)

More precisely, this looks like an issue caused by strict transport security being enforced and/or a 3rd party certificate mechanism and I can't see a way of disabling or working around.
If someone can tell me the relevant place for vscode to use the proxy's certificate or somehow disable this, I (and the developers who use these systems) would be very grateful.  It doesn't seem to be using the system certs in /etc/ssl/certs that are added after running update-ca-certificates

I was working around this problem on a previous release by launching using:
code --ignore-certificate-errors
However, at some point a new release causes the message:
Option 'ignore-certificate-errors' is unknown. Ignoring.

setting http_proxy and https_proxy system environment variables and setting "http.proxy" within vscode makes no difference, neither does "http.proxyStrictSSL": false,

I have added the root certificate CA which allows wget to grab extensions but this isn't a solution on multiple shared systems where extensions are being updated regularly.

user@host:/home/user/> wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.3.69010/vspackage
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/user/.wget-hsts'. HSTS will be disabled.
--2020-03-27 17:36:40--  https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.3.69010/vspackage
Connecting to 185.46.212.32:9443... connected.
Proxy request sent, awaiting response... 200 OK
Length: 28090788 (27M) [application/vsix]
Saving to: 'vspackage'

vspackage                                                                100%[=================================================================================================================================================================================>]  26.79M  9.15MB/s    in 2.9s    

2020-03-27 17:36:47 (9.15 MB/s) - 'vspackage' saved [28090788/28090788]

**Comment by gjsjohnmurray** [comment] 2020-03-27 23:54
It may not make a difference, but are you able to upgrade from 1.40.1 to the current release (1.43.2)?

**Comment by chrmarti** [comment] 2020-03-30 11:33
@deepak1556 Is `--ignore-certificate-errors` still a supported option? (@aeschli You might need to add that to the allow-list of CLI options.)

@cggac Please update to the latest version of VS Code to make sure you have all the latest fixes. Adding the proxy's CA certificate to the OS should make this work. Where did you add the CA certificate? Why is that not the right approach (if I understand you correctly)?

**Comment by deepak1556** [comment] 2020-03-30 19:19
@chrmarti yeah `--ignore-certificate-errors` option is still supported by electron but we need to allow it in our cli as you suggested.

**Comment by cggac** [comment] 2020-03-30 19:49
@chrmarti I meant downloading via wget a installing/updating manually is what I’m looking to avoid.
I added the CA certificates by copying them to /usr/local/share/ca-certificates and running update-ca-certificates where you can see output confirming the additions; this step enables the wget downloads.
I’m hoping to have time tomorrow to test the latest release, also hoping it’s possible to install that release on Debian 9.

**Comment by chrmarti** [comment] 2020-03-31 05:24
It was listed missing the final `s`. Fixing that.

@deepak1556 Does Electron pick up CA certs from `/etc/ssl/certs/ca-certificates.crt`? Is there documentation on this?

**Comment by deepak1556** [comment] 2020-03-31 06:26
@chrmarti electron doesn't handle certificate management, it is delegated to chromium and chromium uses NSS Shared DB on linux , for managing certificates in this case you can follow https://chromium.googlesource.com/chromium/src/+/lkgr/docs/linux/cert_management.md , updating certificates in the system store wouldn't have an effect.

**Comment by cggac** [comment] 2020-03-31 09:44
I can confirm the same behaviour in code_1.43.2-1585036376_amd64 as originally reported.  I'll see what can be done in our environment with the chromium certificate management (we don't use Chrome on these nodes).

**Comment by deepak1556** [comment] 2020-03-31 20:28
> we don't use Chrome on these nodes

@cggac chrome is not required, can you try adding the certificate following https://chromium.googlesource.com/chromium/src/+/lkgr/docs/linux/cert_management.md#add-a-certificate , vs code should pick it up

**Comment by cggac** [comment] 2020-04-03 09:55
@chrmarti Apologies for the stupid question but could you let me know which release the commit to fix the --ignore-certificate-errors will be/was applied to?

**Comment by cggac** [comment] 2020-04-09 13:36
Just a follow-up on using certutil / nss, I've added the necessary root certificates using
`certutil -d sql:/home/myusername/.pki/nssdb -A -t ",," -n RootCAnickname -i /usr/share/ca-certificates/RootCAfile.crt`
Which does change the behaviour, however, it's not clear how this is failing now
![Error2](https://user-images.githubusercontent.com/62764806/78899881-90eda380-7a65-11ea-9c55-36505eadc7e3.png)

**Comment by chrmarti** [comment] 2020-04-09 18:50
It doesn't seem to get any response. Is that the same for the other extensionquery requests? What does the timing tab of the request show?

**Comment by cggac** [comment] 2020-04-15 07:57
Hi @chrmarti I'm not a user of this application, I'm just testing the installation of extensions on behalf of developers. If there's a particular function you'd like me to attempt I can show you the results.  Here's a selection of some failed timing tabs

![Error3](https://user-images.githubusercontent.com/62764806/79312426-66c93500-7eee-11ea-9d35-1ce9cce2dc64.png)
![Error4](https://user-images.githubusercontent.com/62764806/79312438-69c42580-7eee-11ea-910a-f77ec6225357.png)
![Error5](https://user-images.githubusercontent.com/62764806/79312441-6c267f80-7eee-11ea-849c-4ffcd947c360.png)
![Error6](https://user-images.githubusercontent.com/62764806/79312453-70529d00-7eee-11ea-8561-9f48d9bf2ac1.png)

**Comment by deepak1556** [comment] 2020-04-15 08:02
@cggac can you launch code with `--log-net-log=netlog.json` and attach the log after making some extension searches that triggers the above request. Thanks!

**Comment by cggac** [comment] 2020-04-15 08:24
I have done this, I received the message:
Option 'log-net-log' is unknown. Ignoring.
However, logs were taken and are attached (renamed with .txt to upload here)
[netlog.json.txt](https://github.com/microsoft/vscode/files/4479945/netlog.json.txt)

**Comment by deepak1556** [comment] 2020-04-15 08:48
If you load the log in https://netlog-viewer.appspot.com/#import , we can see all the network connections are timed out.

@chrmarti is there a mock request payload to try for @cggac from the chromium browser on his system to narrow down whether the issue is in the system.

**Comment by chrmarti** [comment] 2020-04-15 09:38
Does this show that we are running without proxy configured?
![image](https://user-images.githubusercontent.com/9205389/79321928-5de75c00-7f0c-11ea-8f1a-4744c535ad0b.png)

@cggac Could you retry including `--log-net-log=netlog.json` and `--proxy-server=<your proxy>:<proxy port>` and attach the netlog.json again?

You could open the same URL in Chromium: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery. If it works the reply would inform you of 'GET' not being supported.

**Comment by cggac** [comment] 2020-04-15 10:23
@chrmarti Well, I had the proxy declared as a http_proxy and https_proxy variable and within the application and it didn't work; however, with the flag --proxy-server=<your proxy>:<proxy port> it works! extensions install!
Here's the log:
[netlog2.json.txt](https://github.com/microsoft/vscode/files/4480574/netlog2.json.txt)

**Comment by deepak1556** [comment] 2020-04-15 10:48
@cggac can you try with our https://code.visualstudio.com/insiders/ , @chrmarti made a recent change that should pick up proxy settings from `http(s)_proxy` variables.

**Comment by chrmarti** [comment] 2020-04-16 05:36
@deepak1556 My change only picks up the `http.proxy` setting - not the environment variables. We could add that. (And add `--log-net-log` to the list of valid command line options.)

**Comment by chrmarti** [comment] 2020-04-16 06:50
Added these changes. For extensions we currently read the certificates from `/etc/ssl/certs`, I wonder if we should change that to also read the NSS DB for consistency. Currently the user would have to add any custom certificate in both places to get consistent behavior.

**Comment by deepak1556** [comment] 2020-04-16 09:12
@chrmarti if the extensions are using any web request api then chromium would pick up the certificates from the NSS DB, I don't see any advantage in us reading the certificates. And if the extensions are just using node apis then NSS DB wouldn't come into play.

**Comment by chrmarti** [comment] 2020-04-16 12:46
@deepak1556 I'm currently adding the `/etc/ssl/certs` certificates through the `tls` module, so extensions benefit from it. Extensions cannot use the web request API.

**Comment by deepak1556** [comment] 2020-04-17 03:30
> Currently the user would have to add any custom certificate in both places to get consistent behavior.

Its bit difficult to solve this, since node doesn't care about NSS db we will write our own native module which would essentially be a wrapper around https://source.chromium.org/chromium/chromium/src/+/master:net/cert/nss_cert_database.h to allow importing client certificates to the shared NSS db.

I think we can just document this behavior for now and let users know how to import ceritificates to the NSS db when some requests fail ?

**Comment by cggac** [comment] 2020-04-17 15:54
@deepak1556 The fix on the insiders build does correctly pull in the proxy setting in preferences.  I should also note that the insiders build also locked up when clicking a few checkboxes in the online services preferences.

Apologies for the delay; it was all working, I then tried to see the minimum required steps to get this up and running for a user.  Having started with a clean home directory, nothing was working, I only just figured out the command I listed above wasn't what I'd originally used, this works though:
`certutil -d sql:/home/myusername/.pki/nssdb -A -t "C,," -n RootCAnickname -i /usr/share/ca-certificates/RootCAfile.crt`

With regards to how you implement changes to where certificates are pulled from, `/etc/ssl/certs` would be so much better for multi-user systems such as ours, rather than making changes in many home directories which would need ongoing management.

**Comment by chrmarti** [comment] 2020-04-27 11:46
@cggac Unifying the two would make sense. It seems unlikely that Chromium would switch to using `/etc/ssl/certs`, so we're probably stuck with NSS db.

@deepak1556 Extracted #96247 for the suggested improvement.

Closing this issue as the discussed problems are fixed.

**Closed by chrmarti** 2020-04-27 11:46 UTC
Labels: bug, proxy
