### ISSUE TITLE
Can't be opened because Apple cannot check it…

### ISSUE THREAD

**Issue by ROOKSDesign** [microsoft/vscode#87610] opened 2019-12-23 17:55 UTC
Trying to install Visual Studio code and I get this message...

<img width="435" alt="Screenshot 2019-12-23 at 17 46 58" src="https://user-images.githubusercontent.com/43404437/71372648-dbc5d700-25ac-11ea-90cb-74bc9ec64c8e.png">

Any suggestions?

I'm running macOS Catalina 10.15.2

**Comment by IllusionMH** [comment] 2019-12-23 19:13
/duplicate of #74782

Please see steps in https://github.com/microsoft/vscode/issues/74782#issuecomment-541420688 for current workaround.

**Closed** 2019-12-23 19:13 UTC
Labels: *duplicate
