### ISSUE TITLE
resolve merge conflicts toolbar disappear

### ISSUE THREAD

**Issue by Archsx** [microsoft/vscode#157325] opened 2022-08-05 20:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.70.0 (user setup)
- Date: 2022-08-04T04:38:16.462Z
- Electron: 18.3.5
- Chromium: 100.0.4896.160
- Node.js: 16.13.2
- V8: 10.0.139.17-electron.0
- OS: Windows_NT x64 10.0.19044

this is what I want:
![resolve_merge_conflicts](https://user-images.githubusercontent.com/21698481/183154999-a8fb4419-ec37-4780-9182-e974b7044aec.gif)

and some days ago it works as expected, but today I found the toolbar just disappear.

but I get :

![actual](https://user-images.githubusercontent.com/21698481/183155990-db3773f4-46b5-4f24-827a-0f67e2b20251.gif)

I've searched the question in Stackoverflow, and I got a similar question(https://stackoverflow.com/questions/47241098/accept-incoming-change-not-appearing-in-vs-code), and I've tried set `editor.codeLens: true` and `diffEditor.codeLens: true`, but it still not work.

Steps to Reproduce:
1. init a git repo and do some branch merge operation

and here is my global git config if needed:
```
[core]
	autocrlf = false
	editor = code --wait --new-window
[remote "origin"]
	proxy = 
[credential]
	helper = manager-core
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
[merge]
	tool = vscode
[mergetool "vscode"]
	cmd = code --wait --merge $REMOTE $LOCAL $BASE $MERGED
[diff]
	tool = vscode
[difftool "vscode"]
	cmd = code --wait --diff $LOCAL $REMOTE

```

**Comment by 256hz** [comment] 2022-08-05 20:42
This just happened to me too, the solution for me was to open settings (command+comma), search for `merge`, and disable `Git: Merge Editor`.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/46080343/183159595-5dd2f760-3d26-4a14-89ce-5e4738e63a7d.png">

**Comment by dashed** [comment] 2022-08-05 21:10
@256hz thanks! That helped resolve this.

**Comment by Archsx** [comment] 2022-08-05 21:25
> This just happened to me too, the solution for me was to open settings (command+comma), search for `merge`, and disable `Git: Merge Editor`. <img alt="image" width="455" src="https://user-images.githubusercontent.com/46080343/183159595-5dd2f760-3d26-4a14-89ce-5e4738e63a7d.png">

yes it works !!!!!!!!, but I don't know it is the proper way . I don't know what side effect it will cause .

and I installed github desktop and find I needn't it so uninstall it , so is there any chance that the github desktop is the culprit or it is just a vscode bug?

**Comment by gjsjohnmurray** [comment] 2022-08-05 21:41
It's not a bug. As mentioned in the 1.70 release notes, the new merge editor has become the default. If you don't want to use it, clear that checkbox.

**Comment by dashed** [comment] 2022-08-05 21:58
@gjsjohnmurray Was it this section? https://code.visualstudio.com/updates/v1_70#_3way-merge-editor-improvements

It might've been helpful to provide information on reverting using the checkbox option that @256hz mentioned earlier.

**Comment by Archsx** [comment] 2022-08-05 22:02
@gjsjohnmurray  yes it is mentioned in the release notes, but it says "The merge editor can be opened by clicking on a conflicting file in the Source Control view.", so I have to manually click the panel ? is there any way that it will jump to the editor automatically you type some merge operation in bash ?

**Comment by gjsjohnmurray** [comment] 2022-08-05 22:07
> It might've been helpful to provide information on reverting

Agreed. Anyway, here's a link to the info.

https://github.com/microsoft/vscode/issues/157268#issuecomment-1206670413

**Comment by gjsjohnmurray** [comment] 2022-08-05 22:08
> is there any way that it will jump to the editor automatically you type some merge operation in bash ?

Pinging @lszomoru about this.

**Comment by Archsx** [comment] 2022-08-05 22:19
thank you all and I hope release notes more image to demonstrate the differences .

**Comment by heartacker** [comment] 2022-08-05 23:16
Please don't close this issue.
I think this is a bug that we should fix

**Comment by Archsx** [comment] 2022-08-05 23:18
> Please don't close this issue. I think this is a bug that we should fix

ok, reopend.

**Comment by a4lg** [comment] 2022-08-06 04:52
New merge tool itself is cool but the editor view without clear indication of the conflict is *never* I wanted.

I would like to have both. Is there any good reason to be them mutually exclusive?

**Comment by magnetikonline** [comment] 2022-08-08 04:41
Happy I found this issue - I've had to re-enable `"git.mergeEditor": false` - no matter what I do I can't seem to trigger/open the new merge editor when clicking on a file that is currently in conflict.

Would like to be able to try this - but from the file explorer or source control views - just can't get it to fire.

**Comment by sixclones** [comment] 2022-08-08 13:40
Being able to have both would be really neat! I love both ways of resolving conflicts, depending on the situation. Being able to have this configuration would be awesome!

```json
"diffEditor.codeLens": true,
"git.mergeEditor": true,
```

**Comment by lszomoru** [comment] 2022-08-09 07:58
@hediet, @jrieken could you please take a look? Thank you!

**Closed** 2022-08-09 11:54 UTC
Labels: merge-editor

**Comment by smflorentino** [comment] 2022-08-13 15:21
I never would have figured out how to fix this if not for this issue (I assumed it was a bug and "Merge Editor" was the pre-1.70 thing I actually wanted to keep, so I was puttering around in "Merge Conflict" settings). I don't always read release notes since they're so lengthy (and judging by this thread, suspect I'm not the only one).

Honestly, what would *really* help is a "new since 1.70 (August 2022)" badge next to the setting. Then it would be immediately obvious. Bonus points for making such "new" settings searchable so I can quickly navigate through new settings.

Here's my cruel attempt with MS Paint:
![image](https://user-images.githubusercontent.com/3495150/184500454-a1144ced-f72c-4e55-a177-aacee9a886e4.png)

Thoughts?

**Comment by fabiomilheiro** [comment] 2022-08-16 15:53
I don't like the new merge tool. If you want to try it out, there's no need to break functionality that devs are already used to. It's not even obvious "untick 'open the merge editor'" could be replaced with a checkbox ticked by default called "resolve conflicts inline".

**Comment by xiuxiumomo** [comment] 2022-08-18 00:50
> > This just happened to me too, the solution for me was to open settings (command+comma), search for `merge`, and disable `Git: Merge Editor`. <img alt="image" width="455" src="https://user-images.githubusercontent.com/46080343/183159595-5dd2f760-3d26-4a14-89ce-5e4738e63a7d.png">
> 
> yes it works !!!!!!!!, but I don't know it is the proper way and what side effect it has .
> 
> Today I installed github desktop and find I needn't it then uninstall it , so is there any chance that the github desktop is the culprit or it is just a vscode bug?

i  set it but, still  doesn't work

**Comment by jamiemccarville** [comment] 2022-08-31 18:26
> This just happened to me too, the solution for me was to open settings (command+comma), search for `merge`, and disable `Git: Merge Editor`. <img alt="image" width="455" src="https://user-images.githubusercontent.com/46080343/183159595-5dd2f760-3d26-4a14-89ce-5e4738e63a7d.png">

This worked for me as well. Thanks!
