### ISSUE TITLE
Unable to clear the contents of the query

### ISSUE THREAD

**Issue by shizengzhou** [microsoft/vscode#45211] opened 2018-03-07 14:39 UTC
### Issue Type
Bug

### Description

- Ctrl+F, search 'error'
- Delete error, quit the search
- Highlight all 'e' in the current file
- Press 'Esc', the cursor jumps to the position of the first 'e'
![search](https://user-images.githubusercontent.com/24318019/37097998-bcdd8a22-2257-11e8-9813-72dce2293438.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (1.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by rebornix** [comment] 2018-09-07 22:55
Re https://github.com/Microsoft/vscode/issues/17563#issuecomment-296622212 . The find widget is incremental, which means it will try to search for the keyword in the find widget once it's changed and move the selection to the nearest match, that's why when we delete characters from the find input box, the selection will finally shrink to one character. However once the find widget is empty, we don't try to set the selection to an empty one. This behaves the same as Visual Studio's find widget.

**Comment by rebornix** [comment] 2019-10-23 22:09
/duplicate of https://github.com/microsoft/vscode/issues/17563#issuecomment-296622212

**Closed** 2019-10-23 22:09 UTC
Labels: *duplicate, editor-find, under-discussion, ux
