### ISSUE TITLE
Extensions Query behind proxy is broken

### ISSUE THREAD

**Issue by akcorp2003** [Microsoft/vscode#17574] opened 2016-12-20 01:47 UTC
- VSCode Version: 1.8.1
- OS Version: OSX El Capitan 10.11.6
- Chrome:  55.0.2883.95

After the update to 1.8.1, the extensions side bar cannot search for extensions in the gallery when using VS Code behind a proxy. Updating existing extensions is still functional.

The error message is ERR_TUNNEL_CONNECTION_FAILED

The debug log:

    workbench.main.js:94An unknown error occurred. Please consult the log for more details.
    e.doShow @ workbench.main.js:94

    POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery 
    net::ERR_TUNNEL_CONNECTION_FAILED
    (anonymous function)	@	workbench.main.js:132
    n.Class.derive._oncancel	@	workbench.main.js:32
    t.xhrRequest	@	workbench.main.js:132
    e.request	@	workbench.main.js:132
    n.request	@	workbench.main.js:132
    (anonymous function)	@	workbench.main.js:132
    then	@	workbench.main.js:32
    e.queryGallery	@	workbench.main.js:132
    e.query	@	workbench.main.js:132
    e.queryGallery	@	workbench.main.js:91
    t.query	@	workbench.main.js:129
    t.doSearch	@	workbench.main.js:128
    (anonymous function)	@	workbench.main.js:128
    e.queue	@	workbench.main.js:32
    (anonymous function)	@	workbench.main.js:32
    (anonymous function)	@	workbench.main.js:32
    g	@	workbench.main.js:32
    enter	@	workbench.main.js:32
    _run	@	workbench.main.js:32
    _completed	@	workbench.main.js:32
    (anonymous function)	@	workbench.main.js:32

    workbench.main.js:94 An unknown error occurred. Please consult the log for more details.
    e.doShow @ workbench.main.js:94
    e.show @ workbench.main.js:94
    t.onError @ workbench.main.js:129
    (anonymous function) @ workbench.main.js:128
    done @ workbench.main.js:32
    v @ workbench.main.js:32
    enter @ workbench.main.js:32
    _run @ workbench.main.js:32
    _chainedError @ workbench.main.js:32
     n @ workbench.main.js:32
     v @ workbench.main.js:32
     enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _error @ workbench.main.js:32
     (anonymous function) @ workbench.main.js:32
     done @ workbench.main.js:32
     v @ workbench.main.js:32
     enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _error @ workbench.main.js:32
     (anonymous function) @ workbench.main.js:32
     done @ workbench.main.js:32
     v @ workbench.main.js:32
     enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _chainedError @ workbench.main.js:32
     n @ workbench.main.js:32
     then @ workbench.main.js:32
     enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _setCompleteValue @ workbench.main.js:32
     v @ workbench.main.js:32
     enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _chainedError @ workbench.main.js:32
     n @ workbench.main.js:32
     v @ workbench.main.js:32
    enter @ workbench.main.js:32
     _run @ workbench.main.js:32
     _error @ workbench.main.js:32

Steps to Reproduce:

1.  Initialize the proxy settings (Code -> Preferences -> User Settings) by including "http.proxy": 
and "http.proxyStrictSSL":
2.  Open Extensions bar and search for an extension.

**Comment by egamma** [comment] 2016-12-20 10:16
@akcorp2003 

>After the update to 1.8.1, the extensions side bar cannot search for extensions in the gallery when using VS Code behind a proxy. Updating existing extensions is still functional.

Can you confirm that this has worked in version 1.8.0?

**Comment by ruslanch** [comment] 2016-12-20 12:32
In version 1.8.0 it did not work too.

**Comment by akcorp2003** [comment] 2016-12-21 02:32
I couldn't (and not sure if I did it correctly) build the version 1.8.0 from source. How can I get  a compiled version of 1.8.0 without building from source?

**Comment by bruceauyeung** [comment] 2016-12-21 08:38
updating existing extensions and searching for extensions both dont work here behind a proxy. 
vscode: 1.8.1
os: kubuntu 16.04

**Comment by raphabi** [comment] 2016-12-21 16:31
Hi, same problem here,
I've tried on the same machine (and same user settings file) : it works on 1.7.1 but not on 1.8.1
(win 7 x64)
Thank you

**Comment by eric-brunel** [comment] 2016-12-22 16:05
I switched from 1.2.1 to 1.8.1 and marketplace extensions lookup did not work anymore with following error in console log: 
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
When checking ajax request, proxy data are not provided.

**Comment by fazouane-marouane** [comment] 2016-12-22 21:38
Hi,

This is a duplicate of #17397 
It's seems that it's due to electron update. Electron brought some good features regarding proxy-friendliness. So vscode should now act like any chrome instance and use the default proxy configuration on your computer. However, extensions installs still use the old node netfworking stack which requires defining "http_proxy".
I tried to debug this locally. I followed https://github.com/Microsoft/vscode/wiki/How-to-Contribute However I couldn't debug extensions installation process because vscode-oss didn't even look for extensions. So either I did something wrong or only the guys from Microsoft have access to the corresponding code...

**Comment by akcorp2003** [comment] 2016-12-23 18:52
@fazouane-marouane How do I get to product.json file in the UI?

**Comment by fazouane-marouane** [comment] 2016-12-23 23:22
@akcorp2003 Actually this was to be able to debug the process of installing extensions and to be able to understand the rootcause of the problem. It's unfortunately not a fix 😞

**Comment by akcorp2003** [comment] 2016-12-25 05:41
@fazouane-marouane Aww... it looks like then, that it's a good place to start the fix!

**Comment by joaomoreno** [comment] 2017-01-03 09:38
This is definitely **not** a duplicate of #17397. @akcorp2003 complains that searching is broken, while updating is not. Extension querying uses Chrome's network stack. That's what has changed.

@akcorp2003 Does Chrome itself work without any problems on macOS?

**Comment by akcorp2003** [comment] 2017-01-03 15:43
@joaomoreno Chrome is working perfectly fine. Browsing wise, I'm not seeing any issues nor downloading things.

**Comment by akcorp2003** [comment] 2017-01-03 15:46
@joaomoreno I just noticed that my C# extension version is 1.5.3 but the version on VS Gallery is 1.6.2 and there's no option to update...so perhaps updating is not working?? (I did see an update button appear the day I opened this issue.)

**Comment by bigwhite** [comment] 2017-01-06 09:06
same problems:

enviroment:

```
vscode 1.8.1
ubuntu 16.04  4.4.0-57-generic
```

**Comment by leonibr** [comment] 2017-01-09 19:17
same here:
vscode 1.8.1
windows 8.1
backing to 1.7.2 version

**Comment by fazouane-marouane** [comment] 2017-01-09 19:37
Hi @leonibr
Please take a look at https://github.com/Microsoft/vscode/issues/18103

**Comment by ununseptium** [comment] 2017-01-19 09:11
Yeah same for me here. 
vscode `1.8.1`
windows 7

**Comment by FloMaetschke** [comment] 2017-01-25 09:29
Same problem, please fix:

- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:12:18.506Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

**Comment by Guitarbum722** [comment] 2017-02-24 03:20
Same issue here.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

I installed Insiders 1.8.0-insider (287a5deb91f7025ee8d737cde856e608f57da5e5, 2016-11-21T16:14:00.480Z) just to try it out.  I used the same exact user settings behind my corporate proxy and everything worked perfectly.

**Comment by joaomoreno** [comment] 2017-07-03 12:40
The whole network stack has changed recently. Closing due to inactivity. Documentation comes with #27838

**Closed by joaomoreno** 2017-07-03 12:40 UTC
Labels: bug, proxy
