### ISSUE TITLE
Cannot open folder / empty explorer pane.

### ISSUE THREAD

**Issue by parasit** [microsoft/vscode#91002] opened 2020-02-19 16:34 UTC
When try open folder with code, got message on explorers pane "You have not yet opened a folder" and button "Open folder". But it's not working. Any try, by button, by menu "File-> Open folder" or shortcut just not work. Explorer pane remains empty with the same message and button. 
 

- VSCode Version: 1.42.1
- OS Version: Kubuntu 19.10

Steps to Reproduce:

1. Open code folder eg. `code ./folder_with_sources`
2. Explorer pane remains empty/closed

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2020-02-19 16:41
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by parasit** [comment] 2020-02-19 16:47
> Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

After installing this version (same version number?) everything looks ok...
```Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic```

**Comment by isidorn** [comment] 2020-02-19 16:57
Ok, so closing.
If you can reproduce with vscode insiders please let us know. Thank you

**Closed by isidorn** 2020-02-19 16:57 UTC
Labels: file-explorer, needs more info

**Comment by markuscraig** [comment] 2020-03-16 16:13
fyi, I'm seeing the same behavior with `1.43.0` on OSX (10.14.6).

The latest insiders build works for me though (`1.44.0-insiders`).
