### ISSUE TITLE
'${fileDirname}' Can not be resolved.

### ISSUE THREAD

**Issue by azenapow** [microsoft/vscode#100556] opened 2020-06-19 06:27 UTC
Version: 1.47.0-insider (user setup)
Commit: 84f52fe1c0124307046ac0f5443493cda946e60f
Date: 2020-06-17T06:43:38.511Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. VSCode Insider upgrade.
2. Open exists workspace.
3. Run Start Debugging

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "miDebuggerPath": "/usr/bin/gdb",
            "preLaunchTask": "g++ build active file"
        }
    ]
}

```

It works on previous version of VSCode insder.

> [Window Title]
> Visual Studio Code - Insiders
> 
> [Content]
> '${fileDirname}' can not be resolved. Please open an editor.
> 
> [Open launch.json] [Cancel]
> 

![cannotresolve](https://user-images.githubusercontent.com/16533954/85103307-5f513f80-b241-11ea-9493-0f34f9668cda.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Unknown. (C/C++ extension must require)

**Comment by qarawlus** [comment] 2020-06-19 15:51
I have the same issue.

**Comment by alexr00** [comment] 2020-06-22 15:10
Looks like a duplicate of https://github.com/microsoft/vscode/issues/95423

**Closed by alexr00** 2020-06-22 15:10 UTC
