### ISSUE TITLE
Uncomment a multline comment in CPP without completely selecting the commented text

### ISSUE THREAD

**Issue by ajay9022** [microsoft/vscode#81663] opened 2019-09-30 17:37 UTC
Sublime text provides the feature that you don't need to select the required piece of text for uncommenting. 

for eg : 
`
/*
int x = 5;
float b = 5.6;
*/
`
For uncommenting the above part, I need to first select the snippet inside the the block of comment and then do `Shift+cmd+/` (MacOS)for toggling/removing the comment.

Whereas in Sublime Text, you just need to keep the text cursor anywhere inside the `/* */` block and then do `Shift+cmd+/` to remove the comment.

**Comment by ajay9022** [comment] 2019-09-30 17:40
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Uncomment block when caret at any position in that block [feature request] (#29004)](https://www.github.com/microsoft/vscode/issues/29004)

I think nothing has been done to tackle it.

**Comment by alexandrudima** [comment] 2019-10-02 09:59
Duplicate of #29004

**Closed by alexandrudima** 2019-10-02 09:59 UTC

**Comment by ajay9022** [comment] 2019-10-02 17:20
> Duplicate of #29004

I don't think that it's been answered in the original question too. Is it?
