### ISSUE TITLE
unable to fully close/collapse object or switch statement case.

### ISSUE THREAD

**Issue by pcdependency** [microsoft/vscode#130281] opened 2021-08-06 18:54 UTC
Issue Type: <b>Bug</b>

Bug: unable to fully close/collapse object or switch statement case. This wasnt an issue before the last update. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (24.62GB free)|
|Process Argv|--crash-reporter-id 667bf135-8aa9-424a-ba4d-2acd551da5ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jsx-html-tags|ang|1.0.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
highlight|deb|0.1.0
es7-react-js-snippets|dsz|3.1.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|8.1.0
search-node-modules|jas|1.3.0
vs-color-picker|lih|1.0.0
theme-monokai-pro-vscode|mon|1.1.19
vscode-react-native|msj|1.6.0
color-highlight|nau|2.4.0
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.6.0
codesandbox|yes|0.0.8

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472
bridge0723:30346310

```

</details>

**Comment by pcdependency** [comment] 2021-08-06 18:57
![Capture](https://user-images.githubusercontent.com/64095310/128558916-10f4fc36-996b-4a7d-b8d0-32064b1fb665.JPG)

**Comment by IllusionMH** [comment] 2021-08-06 20:01
/needsMoreInfo

Please provide reduced code sample that worked in previous version but stopped now?

```js
switch (key) {
    case value1: {
        //code
    }
    case value1:
        {
            //code
        }
    case value1:
        return {
            a: {
                b:1
            }}        

    default:
        break;
}
```
Has same issue in 1.58.2 and 1.57.1.

I think this is duplicate of #3352

**Closed** 2021-08-17 11:25 UTC
Labels: needs more info
