### ISSUE TITLE
Disconnection isn't permanent after the remote agent goes down

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#114002] opened 2021-01-07 18:13 UTC
This is with the stable version of the SSH extension that doesn't yet have any of the recent changes.

- Connect to an SSH host
- Run "Kill VS Code Server on Host", pick the current host
- Reconnection starts
- On stable, the resolver runs, then vscode realizes that its EH is gone, and shows an error
- On insiders, it keeps trying to reconnect forever

Stable
![image](https://user-images.githubusercontent.com/323878/103928161-4a020c80-50d0-11eb-9c5b-e3c86840226e.png)

Insiders
![image](https://user-images.githubusercontent.com/323878/103928216-600fcd00-50d0-11eb-82b2-b237b93dcbe0.png)

Insiders logs
![image](https://user-images.githubusercontent.com/323878/103928434-afee9400-50d0-11eb-9a2f-a7e6ea809541.png)

**Comment by alexdima** [comment] 2021-01-07 21:03
This sounds like something that would be caused by moving to Chromium's `WebSocket` on Insiders vs the usage of node's TCP/IP on Stable.

**Comment by alexdima** [comment] 2021-01-07 21:11
Yes, it looks like `WebSocket`s tend to never result in an error:

![image](https://user-images.githubusercontent.com/5047891/103945294-481e6480-5135-11eb-9eec-1221bb9c0b65.png)

**Closed** 2021-01-07 21:38 UTC
Labels: bug, remote
