### ISSUE TITLE
Organize Imports adding semicolons despite semi:false

### ISSUE THREAD

**Issue by bj97301** [Microsoft/vscode#57312] opened 2018-08-28 02:22 UTC
This is not a good solution when you add eslinting to the mix.  I end up with semicolons in my imports. 
https://github.com/Microsoft/vscode/issues/49223#issuecomment-387146776

**Comment by mjbvz** [comment] 2018-09-04 20:00
Duplicate of https://github.com/Microsoft/TypeScript/issues/19882

**Closed by mjbvz** 2018-09-04 20:00 UTC
Labels: javascript
