### ISSUE TITLE
Jupyter Notebook: Can't close without saving

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode#138700] opened 2021-12-09 05:37 UTC
Issue Type: <b>Bug</b>

1. Work on an .ipynb file
2. Try closing it when there are pending changes

Result:
The message box asks whether to close without saving. Click "Close without saving"

The file re-opens.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (47.31GB free)|
|Process Argv|--folder-uri file:///c%3A/git/fetch/theia-models --crash-reporter-id 28592bab-0cbd-42c4-b35d-ec0a4bb99be1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
markdown-toc|Ala|1.5.6
aws-toolkit-vscode|ama|1.34.0
atlascode|atl|2.10.0
cmake-format|che|0.6.11
doxdocgen|csc|1.3.2
vscode-fsharp-refactor|dan|0.6.2
gitlens|eam|11.7.0
env-switcher|Eck|0.3.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
vs-code-xml-format|fab|0.1.5
azure-virtual-machine-explorer|for|0.0.2
matlab|Gim|2.2.1
vscode-pull-request-github|Git|0.32.0
vscode-test-explorer|hbe|2.21.1
yaml-plus-json|hil|1.9.2
Untabify|ili|0.0.2
Ionide-fsharp|Ion|5.10.2
latex-workshop|Jam|8.22.0
better-cpp-syntax|jef|1.15.10
vscode-graphviz|joa|0.0.6
vscode-gutter-preview|kis|0.29.0
vscode-cudacpp|kri|0.1.1
vscode-catch2-test-adapter|mat|4.0.11
rainbow-csv|mec|1.10.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
azure-video-analyzer|ms-|0.2.3
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-docker|ms-|1.18.0
vscode-asa|ms-|1.1.2
csharp|ms-|1.23.17
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-ssh-edit-nightly|ms-|2021.12.9540
remote-ssh-nightly|ms-|2021.12.9540
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
test-adapter-converter|ms-|0.1.4
vsliveshare|ms-|1.0.5196
vsliveshare-audio|ms-|0.1.91
vscode-paste-image|mus|1.0.4
proto|pet|0.0.2
view-in-browser|qin|0.0.5
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.2
scala|sca|0.5.5
git-merger|sha|0.4.1
shader|sle|1.1.5
urdf|smi|0.1.0
ros-snippets|swe|0.1.0
spellchecker|swy|1.3.0
html-preview-vscode|tht|0.2.5
hlsltools|Tim|1.1.303
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
azure-iot-edge|vsc|1.25.3
azure-iot-toolkit|vsc|2.16.6
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0
clang-format|xav|1.9.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
vscode-proto3|zxh|0.5.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932cf:30408637
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by rebornix** [comment] 2021-12-16 00:22
@fierval did it happen all the time?

**Comment by fierval** [comment] 2021-12-16 01:34
Yes

Ср, 15 дек. 2021 г. в 16:23, Peng Lyu ***@***.***>:

**Comment by rebornix** [comment] 2022-03-28 18:52
/duplicate of https://github.com/microsoft/vscode/issues/140667

**Closed** 2022-03-28 18:52 UTC
Labels: bug, *duplicate, notebook-serialization
