### ISSUE TITLE
Can't uncollapse collapsed code

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#25018] opened 2017-04-19 15:12 UTC
- VSCode Version: 1.12.0-Insider
- OS Version: Windows 10 Enterprise v1703

Steps to Reproduce:

1. Paste this code:
```ts
class A {

    a;

}

class B {

    b;

}
```
2. Ctrl-K, Ctrl-0 to collapse all.
3. Click the `+` next to `class B`. Nothing happens.
4. If you click the `+` next to `class A` first, then `class B` can be uncollapsed.

**Comment by mjbvz** [comment] 2017-04-19 20:59
Possible duplicate of #25013

**Comment by aeschli** [comment] 2017-04-20 07:58
closing as duplicate of #25013

**Closed by aeschli** 2017-04-20 07:58 UTC
Labels: editor-folding
