### ISSUE TITLE
JSON file destroyed on save

### ISSUE THREAD

**Issue by Nemesarial** [Microsoft/vscode#12330] opened 2016-09-20 16:25 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce: difficult -- seems sporadic -- doesn't always do this with the same json content:

create a json file with the following content:

```
{
  "vertical": "apps",
  "device": "responsive",
  "head": {
    "css": [
      "../../../global/apps/css/apps.css",
      "../../../global/responsive/css/owl.carousel.css",
      "../../../global/responsive/css/cms.css" 
    ],
    "js": []
  },
  "footer": {
    "js": [
      "../../../global/responsive/js/vendors/owl.carousel.js",
      "../../../global/responsive/js/vendors/owl.carousel.js",
      "../../../global/responsive/js/vendors/owl.carousel.js"
    ]
  }
}
```

When I save it, my content gets converted to:

```
{
  "vertical": "apps",
  "device": "responsive",
  "head": {
    ,: [];
  }

  "footer": {
    ,: ;
  }
}
```

**Comment by bpasero** [comment] 2016-09-20 18:01
@Nemesarial 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by aeschli** [comment] 2016-12-05 15:02
The built-in JSON support does not make changes on save. Also when I test format with the given file all seems fine. Closing.

**Closed by aeschli** 2016-12-05 15:02 UTC
Labels: bug, json
