### ISSUE TITLE
Debug: If debugging steps, stops, or restarts after a stopping event but before obtaining locals have finished, Loading graphic in the locals cannot be dismissed.

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#4378] opened 2016-03-17 17:18 UTC
- VSCode Version: 0.10.11
- OS Version: Win10

![image](https://cloud.githubusercontent.com/assets/6598594/13854579/66b230b4-ec29-11e5-9c06-cdb889913a5a.png)

Steps to Reproduce: I was able to reproduce this using the C# debugger from the [C# Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp), but I believe it is a UI issue and should repro with any debugadapter.

1. Run code that will hit a breakpoint
2. After the UI begins to stop, but before locals are populated, stop debugging (or restart debugging or step).

Expected: debugging stops, debugging UI is cleared of debug mode information

Actual: Locals loading graphic continues to be displayed. Locals are broken for subsequent debug session and code must be restarted to fix this.

**Comment by isidorn** [comment] 2016-03-18 07:47
Setting to March to investigate

**Comment by isidorn** [comment] 2016-03-18 08:25
This is not a regression, but a dupe of #3666. Setting that one to April to fix it for the April release

**Closed by isidorn** 2016-03-18 08:25 UTC
Labels: debug
