### ISSUE TITLE
Autocomplete illogical work when the word is completed

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode#15702] opened 2016-11-18 08:06 UTC
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. We begin and complete typing a word.
2. Autocomplete tells it exactly the same words, that it is not longer than the entered word.
3. But autocomplete still expects pressing enter.

I think it would be logical if autocomplete was showing suggestions only if it has a longer word.

**Comment by ramya-rao-a** [comment] 2016-11-18 18:09
Something like this?

![image](https://cloud.githubusercontent.com/assets/16890566/20440928/16ee9936-ad77-11e6-85e1-44d0f8483c4f.png)

**Comment by KostyaTretyak** [comment] 2016-11-18 21:18
Yes, it is.

**Comment by jrieken** [comment] 2017-04-03 12:48
@KostyaTretyak What is your preference on this once. Not showing the completion when its insert text is already there or making Enter insert a new line? I'd favour the second because it still gives my some information, e.g type and doc etc without making me hit Enter twice

**Comment by jrieken** [comment] 2017-04-03 12:49
closing this as dupe of #11944

**Closed by jrieken** 2017-04-03 12:49 UTC
Labels: suggest
