### ISSUE TITLE
Ruler: depending on the size of the file tree, the ruler can be 1px or 2px wide

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#29530] opened 2017-06-27 07:30 UTC
- VSCode Version: 1.13.1
- OS Version: MacOS Sierra 10.12.5

Steps to Reproduce:

1. Resize the editor/file browser on the left
2. The ruler changes width randomly

This is a mild annoyance but depending on the size of the editor/file tree, the ruler's width will change from 1px to 2px, making it more noticeable than it needs to be on some occasions.

Screenshots to compare:

![screen shot 2017-06-27 at 09 25 16](https://user-images.githubusercontent.com/1923346/27575767-113a8714-5b1b-11e7-8cb9-d9835e29ea16.JPG)

![screen shot 2017-06-27 at 09 25 32](https://user-images.githubusercontent.com/1923346/27575768-113b34ca-5b1b-11e7-8a54-b349264caeca.JPG)

**Comment by alexandrudima** [comment] 2017-06-27 07:35
Duplicate of #28542. For pixel perfect rendering, do not use `window.zoomLevel` or set it to 0.

**Closed by alexandrudima** 2017-06-27 07:35 UTC
Labels: editor
