### ISSUE TITLE
Typescript beautification - operator combination turns following code green

### ISSUE THREAD

**Issue by eltimmo** [Microsoft/vscode#37077] opened 2017-10-28 11:48 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.3.0
terraform|mau|0.0.18
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0

---

Steps to Reproduce:

1. Example code below when beautification  takes place, all code after ```++ <``` becomes green. Issue seems to be around this operator combination, if I change this to ```++ <=``` beautification  works as expected. If I remove the ```++``` this also solves the problem.

Thanks,

```typescript
var greenCode
if (greenCode++ < 10) 
{
    var itsAllGreen 
    var Here
}
```

Reproduces without extensions: Yes

![vscode_01](https://user-images.githubusercontent.com/27624232/32134016-15c2a808-bbdc-11e7-8551-47937acf0532.JPG)

![vscode_02](https://user-images.githubusercontent.com/27624232/32134020-25c87f48-bbdc-11e7-924e-c232da01c49a.JPG)

**Comment by mjbvz** [comment] 2017-10-30 17:02
Duplicate of #35768

Already fixed in vscode insiders builds

**Closed by mjbvz** 2017-10-30 17:02 UTC
Labels: grammar, javascript, typescript
