### ISSUE TITLE
Syntax highlight of C/C++ code blocks in Markdown incomplete

### ISSUE THREAD

**Issue by arttet** [microsoft/vscode#107071] opened 2020-09-19 17:07 UTC
The keywords `final`, `override` are not highlighted.
https://en.cppreference.com/w/cpp/keyword

- Version: 1.49.1 (user setup)
- Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
- Date: 2020-09-16T23:27:51.792Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

```cpp
class Book final
{
public:
  std::string const& contents();
private:
  std::string contents_;
}
```

Does this issue occur when all extensions are disabled?: Yes
![2020-09-19_19-58-21](https://user-images.githubusercontent.com/51746822/93672388-24b2a980-fab3-11ea-965a-9773b13a8864.png)

**Comment by gjsjohnmurray** [comment] 2020-09-19 17:46
The Markdown preview uses highlight.js for code highlighting. Please file an issue upstream.

**Comment by mjbvz** [comment] 2020-09-28 19:02
Duplicate of #34525

**Closed by mjbvz** 2020-09-28 19:02 UTC

**Comment by arttet** [comment] 2020-09-28 19:32
Why did you close this issue?
