### ISSUE TITLE
White flash when reloading window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#66373] opened 2019-01-11 03:15 UTC
- Reload the window
- See brief white flash

Is there an issue for this already? From the electron update, I think.

**Comment by bpasero** [comment] 2019-01-11 09:44
@roblourens windows?

**Comment by roblourens** [comment] 2019-01-14 17:48
macOS

**Comment by roblourens** [comment] 2019-01-14 17:52
I also see it when switching open folders. I tried to record a gif but the flash was so quick it didn't appear...

**Comment by roblourens** [comment] 2019-01-14 17:53
High framerate version:

![jan-14-2019 09-53-06](https://user-images.githubusercontent.com/323878/51130604-38881180-17e2-11e9-8081-1fa294824c5e.gif)

I am pressing the keyboard shortcut for Reload Window

**Comment by bpasero** [comment] 2019-01-15 08:59
@roblourens does it reproduce with an empty user data dir and no theme changes?

**Comment by bpasero** [comment] 2019-01-15 09:15
Nevermind I can reproduce. Have to figure out if this is Electron 3 related.

**Comment by bpasero** [comment] 2019-01-15 09:38
@roblourens I can reproduce right from the point where we updated to Electron 3, however I cannot reproduce with our exploration builds that use Electron 4, can you give them a try too?

We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by roblourens** [comment] 2019-01-15 18:30
Yeah, I'm not seeing it in Electron 4 👍

**Comment by bpasero** [comment] 2019-07-01 06:27
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-07-01 06:27 UTC
Labels: electron, electron-3.0.x-update, fixed-in-electron-4.0.x, upstream
