### ISSUE TITLE
Process explorer rendering issues

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114040] opened 2021-01-08 15:38 UTC
See below gif which is scrolling up and down with the mouse wheel:

- Not sure what the black line is
- Scrolling/scroll bar is acting strangely
- There is a big gap at the bottom of the window

![recording (21)](https://user-images.githubusercontent.com/2193314/104033325-37e1a600-5184-11eb-8c83-115283b2a39b.gif)

**Comment by depascalis** [comment] 2021-03-04 10:06
**Line**
`.monaco-list-row:first-of-type` is responsible for the black line. But since all row items are positioned absolutely and switch order every ~second, and the order in the DOM does not reflect the data-index, the line (border) is jumping around.

Expand the following node to see it in action
```javascript
document.querySelector("#process-list > div > div > div.monaco-list-rows")
```
**Scrolling**
The scrolling acting weird is because there are two vertical scrollbars in action. One solution is to set `overflow: hidden` on the `<body>`. Hover the right side of the window to reveal the custom scrollbar. Notice that there is more weirdness going on though, I believe the custom scrollbar is not getting the correct height.

**Codeicon**
Tree view is missing expander icons since the codeicon classes are out of scope. Add this in `<head>` to quickly see the intended result.
```html
<style type="text/css" media="screen" id="codiconStyles">.codicon-tree-item-expanded:before { content: '\eab4'; }</style>
```

There are more rendering issues in the Process Explorer, but this is what I tracked down for now. Many issues are caused by missing CSS class definitions since they are out of scope or not imported. They are available under `<style>` tags in the main VSCode window.

**Comment by rebornix** [comment] 2022-08-08 20:51
This should be fixed now via https://github.com/microsoft/vscode/issues/157301.

**Closed by rebornix** 2022-08-08 20:51 UTC
Labels: bug, workbench-diagnostics
