### ISSUE TITLE
Pin editor keyboard shortcut sometimes doesn't work

### ISSUE THREAD

**Issue by Dustin-Digitar** [microsoft/vscode#200305] opened 2023-12-08 04:36 UTC
Type: <b>Bug</b>

This started happening since the latest patch.

One way I was able to reproduce:
There is more than one editor open.
At least one editor is pinned.
There is only one editor that is not pinned.

For that one editor that is unpinned, the keyboard shortcut will not pin it.
If another pinned editor becomes unpinned, then, with two editors unpinned, any editor can be pinned as normal.

The cause seems to be the calculated state for the 'pinned' status of an editor.
My keyboard shortcuts check those to determine wheter a keyboard shortcut should pin or unpin the editor.
When I use the VSCode state inspection tool, I see that a pinned editor has a state of 'unpinned'.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5825U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|38.83GB (25.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
copilot|Git|1.140.0
copilot-chat|Git|0.11.0
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.76.1
vscode-graphql-syntax|Gra|1.2.2
vscode-env|Iro|0.1.0
rainbow-csv|mec|3.9.0
remote-wsl|ms-|0.81.8
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5897
language-plan|und|0.0.1
excalidraw-editor|pom|3.7.1
quicktype|qui|12.0.46
vscode-yaml|red|1.14.0
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.4.3
multi-command|ryu|1.6.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
gitblame|wad|10.5.1
copy-hover-type|You|0.0.7

</details>

**Comment by swajj** [comment] 2023-12-10 00:54
<img width="1052" alt="image" src="https://github.com/microsoft/vscode/assets/133168946/486ee17a-c749-4d5e-8a35-847114fb4e95">
Same issue here. Have one key assigned to both pin/unpin with the logic to pick based on `activeEditorIsPinned` as shown. This "When Expression" is the default one suggested by VSCode. (these are the only shortcuts these keys are assigned to, and there are no other keys assigned to these actions anymore- I removed the System assignments)

As long as I have 2+ unpinned text editors, both shortcuts work- C+S+A+P toggles the pinned state of the active editor. BUT, if only the active edito tab is currently unpinned e.g. as shown, it doesn't work at all. Note that right-click on the tab to select "Pin" DOES still work.
<img width="988" alt="image" src="https://github.com/microsoft/vscode/assets/133168946/61ff1473-fff2-489e-a6df-ce2231390c71">

**Comment by Dustin-Digitar** [comment] 2023-12-11 03:53
> @Dustin-Digitar I am not able to reproduce this behaviour. Have you changed the key binding `workbench.action.pinEditor` ? If so, it could possibly be conflicting with a different key binding in some cases. Are you using any non-default editor tab settings?

My keybindings are the same as swajj. 

>Have one key assigned to both pin/unpin with the logic to pick based on `activeEditorIsPinned` as shown.

**Comment by Dustin-Digitar** [comment] 2023-12-11 03:55
Here is the internal state of the editor, showing that the pinned state is incorrect, and thus causing the keyboard shortcut to not work.  Note that it says the active editor is `pinned` when in fact it is not.
![pinned issue](https://github.com/microsoft/vscode/assets/113573618/2c1c62b6-352b-420f-b392-c580d799fded)

**Comment by swajj** [comment] 2023-12-11 04:51
I'll note that today I was having the "opposite" problem- the keys refused to unpin a pinned editor, with several pinned and several unpinned editors. So I'm not sure the bug is as simple as "have exactly one unpinned editor"- but `activeEditorIsPinned` is definitely buggy right now.

**Comment by iappwebdev** [comment] 2023-12-12 07:09
I observed the same behaviour since the last update. Some tabs that are not pinned cannot be pinned and vice verca. There are not other key binding defined, I also tried different key bindings.

**Comment by bpasero** [comment] 2023-12-12 07:23
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by benibenj** [comment] 2023-12-12 08:11
I'm able to reproduce the bug. Running the command from the command palette does not trigger the bug, only when I use the key binding. I ran the bisect and it seems the it is most probable that the bug was caused from the change to allow editor actions in the titlebar. Looking into it...

**Comment by Dustin-Digitar** [comment] 2023-12-12 08:49
If I had to guess, doing a simple 'find' on the commit range you provided turned up this block of code that was removed:
![image](https://github.com/microsoft/vscode/assets/113573618/09511bd5-e726-4dd4-8b3a-a776d0b5475b)

**Comment by iappwebdev** [comment] 2023-12-12 10:30
What I just observed that I can always reproduce this behavior when using the extension [angular2-switcher
](https://marketplace.visualstudio.com/items?itemName=infinity1207.angular2-switcher). 

Steps to reprocude:
1. open a `*.component.ts` file
2. pin tab via `alt+p` pins the editor
3. use `alt+o` to open the `*component.html` file
4. pin tab via `alt+p` does not anything

When using the context menu to pin the `*component.html` file it works again. As soon as I switch between template and component, the file that I switched to cannot be pinned via key binding.

**Comment by benibenj** [comment] 2023-12-12 11:22
I've found the issue and fixed it. The issue was caused by a refactoring of the editor context keys we did last month.

**Closed** 2023-12-12 11:34 UTC
Labels: bug, workbench-tabs

**Comment by alexkubica** [comment] 2024-01-04 16:02
Hi @benibenj sorry if this isn't the proper place to ask
I'm still having this issue in the latest version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2

I saw the patch was released to the insiders version, when does it get released to the public?

**Comment by benibenj** [comment] 2024-01-04 17:31
@alexkubica Because we did not have a December release last year (December 2023) this will be part of the January release which should be shipped in the first week of February.

In the mean time pinning / unpinning editors should be possible from the command palette

**Comment by alexkubica** [comment] 2024-01-04 18:28
> @alexkubica Because we did not have a December release last year (December 2023) this will be part of the January release which should be shipped in the first week of February.
> 
> 
> 
> In the mean time pinning / unpinning editors should be possible from the command palette

Alright thanks for the quick reply 🙏🏼

**Comment by benibenj** [comment] 2024-01-23 16:00
Verification Steps For Insiders:
1. Open 2 editors/files
2. Use keyboard shortcut to pin first file (default: ctrl + k, shift + enter)
3. Use keyboard shortcut to pin second file (default: ctrl + k, shift + enter)
4. Both editors should be pinned now

**Comment by rzhao271** [comment] 2024-01-24 17:07
Thanks for the verification steps!
