### ISSUE TITLE
Find Box creates padding at the top of documents

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#56370] opened 2018-08-14 14:38 UTC
Issue Type: Bug Report 

Find dialog just creates unnecessary padding. I can understand if this was a design decision to stop it blocking users' code, but with all this space, you could make it a full width thing with bigger font/possibly boxes, or make it part of the tabs on the bottom panel. It just looks really odd right now. Could do with UI rework.

- VSCode Version: 1.27.0-insiders
- OS Version: Windows 10 1803 v17134.191

Steps to Reproduce:

1. Press Ctrl+F/Cmd+F to open Find Dialog
2. Scroll to top of document to find unnecessary padding

Does this issue occur when all extensions are disabled?: Yes

**Comment by Radivarig** [comment] 2018-08-30 11:08
Also, when scrolled up and the dialogue gets closed, the whole document snaps back since the padding is removed.

It would be great to have an option to display the find bar in panel on bottom where no text is blocked. Same place where search&replace is shown when using the option `"search.location": "panel"`.

Something like `"editor.find.location": "panel"`

**Comment by rebornix** [comment] 2018-09-04 23:32
Duplicate of https://github.com/Microsoft/vscode/issues/28390, let's track it there.

**Closed** 2018-09-04 23:32 UTC
Labels: *duplicate, editor, editor-find
