### ISSUE TITLE
VSCode does not respond on CentOS7

### ISSUE THREAD

**Issue by sdevita7** [microsoft/vscode#120918] opened 2021-04-09 10:21 UTC
When I open the software it freezes and stops responding
- VSCode version:
1.55.1
08a217c4d27a02a5bcde898fd7981bda5b49391b
x64

- OS version:
CentOS Linux 7
Kernel: Linux 3.10.0-1062.4.1.el7.x86_64
Architecture: x86-64

**Comment by IllusionMH** [comment] 2021-04-09 11:00
/duplicate of #115784

New Electron versions don't support CentOS 7. See linked issue for details and probable workarounds

**Closed** 2021-04-09 11:00 UTC
Labels: *duplicate
