### ISSUE TITLE
Format Document does not correctly format the closing tag in the js files (React) 

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#77093] opened 2019-07-10 11:34 UTC
- VSCode Version: 1.36.1
- OS Version: macOS Mojave

Steps to Reproduce:

1. Use React component in js file
2. Tab few times on closing tag
3. Try to `Format Document`

<img width="466" alt="Screenshot 2019-07-10 at 13 28 59" src="https://user-images.githubusercontent.com/3521624/60965851-257c7700-a317-11e9-8a19-caafe24555df.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-07-10 16:40
Duplicate of https://github.com/microsoft/TypeScript/issues/20766

**Closed by mjbvz** 2019-07-10 16:40 UTC
Labels: new release
