### ISSUE TITLE
Option to override globally disabled extension in workspace settings

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#26728] opened 2017-05-16 08:11 UTC
VScode currently has the option to disable an extension for certain workspaces.
However, there are extensions such as Arduino and the likes which are _very_ workspace specific and negatively impact the overall experience if enabled outside that environment.

Instead of having to manually disable those extensions for every workspace, I suggest making it possible to enable an extension for a workspace even if it is globally disabled.

The current behaviour does not allow you to enable the extension for a workspace if it is disabled globally:
![image](https://cloud.githubusercontent.com/assets/2827047/26096008/0971f7fe-3a20-11e7-8592-c0f76d329119.png)

**Comment by DTasev** [comment] 2017-06-03 12:22
:+1: This could potentially speed up startup of vscode, by not starting _all_ extensions by default (I am not sure how to time if it actually would make a significant difference). 

Usage wise, I currently find myself to be disabling extensions depending on which are not used in the workspace. It would be nice to disable any language extensions globally, and only enable them if they're used in the current workspace.

**Comment by unional** [comment] 2017-08-29 22:11
Duplicate of https://github.com/Microsoft/vscode/issues/15611

**Closed** 2017-11-22 10:37 UTC
Labels: *duplicate, extensions, feature-request
