### ISSUE TITLE
Underscore is not visible in the Terminal

### ISSUE THREAD

**Issue by sklrsn** [Microsoft/vscode#39018] opened 2017-11-23 09:46 UTC
- VSCode Version:1.18.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1.type A_B in the terminal
2. you will see A B

Reproduces without extensions: Yes/No
![image](https://user-images.githubusercontent.com/13186099/33166703-dbd55920-d043-11e7-8201-0d81ca97e27e.png)

**Comment by bochen2014** [comment] 2017-11-23 10:45
got the same issue here

**Comment by mpoeter** [comment] 2017-11-23 11:56
Same here since I updated to v1.18 - v1.17 did not show this behavior.

**Comment by maxibanki** [comment] 2017-11-23 12:26
Duplicate of #38133

**Closed** 2017-11-24 19:02 UTC
Labels: *duplicate, integrated-terminal

**Comment by bochen2014** [comment] 2017-11-26 03:57
ok. I'll just past the answer here for ppl's convenience
```json
"window.zoomLevel": -0.001
```
by @suonto [here](https://github.com/Microsoft/vscode/issues/38133#issuecomment-346372521)
