### ISSUE TITLE
Weird characters in the menu in the terminal panel

### ISSUE THREAD

**Issue by mehdibo** [microsoft/vscode#81178] opened 2019-09-19 15:22 UTC
- VSCode Version: 1.36.1
- OS Version: Mac OS 10.12.6.1337

Steps to Reproduce:

1. Open an integrated terminal
2. Run one of the following commands:
`cat file.txt | less`
`echo "hello" | less`
`cat file.txt | vim`
`echo "hello" | vim`
3. Weird characters start appearing quickly and changing randomly like this:
<img width="158" alt="Screen Shot 2019-09-19 at 4 05 57 PM" src="https://user-images.githubusercontent.com/5004111/65257374-065d4b00-daf9-11e9-892e-c6bdc0232af5.png">
<img width="159" alt="Screen Shot 2019-09-19 at 4 06 00 PM" src="https://user-images.githubusercontent.com/5004111/65257377-065d4b00-daf9-11e9-9d12-e87a2bb8bd84.png">
<img width="88" alt="Screen Shot 2019-09-19 at 4 06 03 PM" src="https://user-images.githubusercontent.com/5004111/65257378-06f5e180-daf9-11e9-892c-e1bd40cc0fe7.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2019-09-19 15:24
/duplicate of #78539

Please provide more info if you are sure that is was marked as duplicate incorrectly.

**Closed** 2019-09-19 15:24 UTC
Labels: *duplicate
