### ISSUE TITLE
Notebook: Reverting a notebook change doesn't refresh the notebook

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105904] opened 2020-09-02 03:06 UTC
Testing #105769

Add a Markdown cell (## Hello World) to a notebook in vscode repo, for example verification.github-issues.
The change is reflected in the Source Control view. 
Revert the change in the Source Control view.

The new Markdown cell is still visible in the Notebook, even if you close and reopen the Notebook file. 

If you try to make another edit to the Notebook, you get a notification that the content of the file is newer.

![image](https://user-images.githubusercontent.com/12818376/91927526-9951af80-ec8e-11ea-8afb-5942a45bb45e.png)

**Comment by gregvanl** [comment] 2020-09-02 03:16
The notification text is also confusing. I think it is saying that the Notebook file on disk has been updated. Saying "newer" is confusing because my changes to the file were "newer" than the source control reverted version.

How about: "The contents of the file has changed on disk. Would you like to open the updated version or overwrite the file with your changes?"

**Comment by rebornix** [comment] 2020-09-02 22:58
The bug mentioned in the issue description is a duplicate of https://github.com/microsoft/vscode/issues/105917 and fixed via 088f8fec17e71a2f69628be5821a3539d019f515

The notification text update is fixed via  4fb1c9a

**Closed** 2020-09-02 22:58 UTC
