### ISSUE TITLE
Issue Reporter doesn't actually work after filling it out

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode#44938] opened 2018-03-02 18:04 UTC
I fill out the form:

![image](https://user-images.githubusercontent.com/3548/36914105-f78a7f96-1e00-11e8-9969-6c0e724d8328.png)

When I click Preview On GitHub, all I ever see is a blank tab on Edge:

![image](https://user-images.githubusercontent.com/3548/36914113-fee89f48-1e00-11e8-992a-7f4843b1f91d.png)

![image](https://user-images.githubusercontent.com/3548/36914128-190e8522-1e01-11e8-893a-d68635eabcf1.png)

**Comment by RMacfarlane** [comment] 2018-03-02 18:18
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/44245.

This is fixed in the latest insider's, now if the url the reporter is trying to open is too long the data will be copied to clipboard and the issue preview will open with text prompting you to paste.

**Closed by RMacfarlane** 2018-03-02 18:18 UTC
