### ISSUE TITLE
Onclick div it will show outer div boundary instead of current div

### ISSUE THREAD

**Issue by potenzatk** [Microsoft/vscode#70316] opened 2019-03-12 13:37 UTC
Hello,

When we click on any div vs codes showing outer div start and ending white line ( boundary  ) between div.
But we think it should show current div start and ending line ( boundary), not outer div please check below link.
we can easily identify with notpad++ but not with vs code. there are any solutions like we can show notepad ++

![image](https://user-images.githubusercontent.com/6461412/54276848-9b055000-458e-11e9-89b4-7e499db5fb32.png)

![image](https://user-images.githubusercontent.com/6461412/54276808-84f78f80-458e-11e9-9e98-1a3c8484eeee.png)

let us know if you want more details.
Thanks

**Comment by aeschli** [comment] 2019-03-13 11:51
You are talking about the indent guides. You want the indent guide highlighted that has the same indent as the cursor selection.

**Comment by alexandrudima** [comment] 2019-03-27 15:13
Duplicate of #49342

**Closed by alexandrudima** 2019-03-27 15:13 UTC
