### ISSUE TITLE
New explorer: clicking on a file first shows blue focus outline

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69437] opened 2019-02-26 08:40 UTC
I feel like this is different behavior from before:
* close all editors
* click on a file in the explorer

=> :bug: first you see the focus outline in the tree and then the element is selected
=> I do not recall ever seeing the focus outline before when just clicking into an item

Not sure if this is a general tree/list issue or specific to the explorer.

//cc @joaomoreno

**Comment by isidorn** [comment] 2019-02-26 10:26
I can reproduce this with fresh user data dir vscode.
I can reproduce for all trees (also watch).
So it seems like the tree takes focus for a moment and only then forwards to focus to the element. Forwarding to @joaomoreno since it feels like a tree issue

**Comment by joaomoreno** [comment] 2019-02-26 20:09
This is definitely new. The tree gets DOM focus on mouse down. The tree element gets selected on mouse up.

I don't find this terrible, so I propose to just close this.

**Comment by bpasero** [comment] 2019-02-27 07:13
It looks ugly, so I propose to fix it by restoring how it used to be.

**Comment by joaomoreno** [comment] 2019-03-25 13:20
Let's close this and roll with the current setup for a while.

**Closed by joaomoreno** 2019-03-25 13:20 UTC
Labels: bug, list, tree
