### ISSUE TITLE
Inspector loaded scripts: Hide <eval> for scripts from the debug adapter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#31537] opened 2017-07-27 09:27 UTC
Refs: #31327

1. Debug a node app (for instance our smoke test repo)
2. Open the loaded scripts view
3. Notice the <eval> folder

Those scripts always seem useless to me and do not provide any real value.
Is it common practice to also show these scripts or should we hide them?

Since it is a tree, the user can always just collapse them so maybe showing them is a better choice then implicitly hidding. Though still creating this as a question.

**Comment by weinand** [comment] 2017-07-27 09:32
"legacy" shows eval scripts under "<node_internals>", "protocol" has introduced another top level node.
If you are using eval in your code it is very useful to have the scripts available while debugging because you can step through the scripts and even set breakpoints.

**Comment by roblourens** [comment] 2017-07-27 14:53
User eval scripts would be very useful. However the debug adapter creates some eval scripts too, which wouldn't be useful to the user. It's not straightforward to tell which ones came from the debug adapter, but I could use `//@sourceUrl` to give them a unique name, then filter them out from that view. We did that in F12.

**Comment by movedoa** [comment] 2018-08-28 16:19
Any news on this? This gets really annoying when working with third party libraries that use eval :/

**Comment by cdaringe** [comment] 2018-10-23 18:50
consider the following `launch.json` block for, say, an `Attach` launch config:

```
      "skipFiles": [
        "<node_internals>/**/*.js",
        "<node_internals>/**/*",
        "*VM*"
      ]
```

unfortunately, this still allows debug sessions inside of `VM*` "files" (node 10.12.0).  this creates a particularly difficult situation as i have a code block like this:

```js
const boot = require('some-module')
boot(initValues)
```

and when i use VSCode's step-in feature on the `boot(initValues)` line, it enters directly into a VM script, now with a giant stack (likely because of my `skipFiles`).  stepping out a few times then steps up just far enough where the program ultimately resumes, and i have no downstream breakpoints set.  

it's a bummer, because i step in @ `boot` specifically to add deeper breakpoints and explore the code of interest, but ultimately, i cannot even step-in, per the intent of the feature.

**Comment by roblourens** [comment] 2018-10-23 18:56
@cdaringe please open a new feature request, this is about hiding those scripts from the loaded scripts view.

**Comment by cdaringe** [comment] 2018-10-23 19:20
@roblourens, you closed #49142 already, pointing it to this issue.  i can make a dupe of #49192 with a bit more context perhaps?

**Comment by roblourens** [comment] 2018-10-23 21:38
Oops 😬 I guess the two go together, I'll say this issue covers both skipFiles for eval scripts, and hiding certain eval scripts from loaded scripts.

**Comment by mzhukovs** [comment] 2019-01-05 03:18
Hope this makes it in soon. My skipFiles keeps growing, smartStep doesn't seem to do anything for me, not sure if it's just my webpack setup or what. Instead of skipFiles - is there some basic way to just say ok, only step into .ts files for debugging? Basically the opposite of skipFiles, only debug files in the project...

**Comment by luisorbaiceta** [comment] 2021-09-09 17:31
Any news on this?

**Comment by roblourens** [comment] 2021-09-09 19:14
I think this would be on the debug adapter side to filter these scripts out.

**Comment by connor4312** [comment] 2021-09-09 20:04
We do filter out internally-evaluated scripts. However we don't want to just generically ignore all eval'd scripts, since then we cannot break in them, reference them in stacktraces, and so on.

**Closed** 2021-09-09 20:06 UTC
Labels: feature-request, debug, *as-designed
