### ISSUE TITLE
Not active extension in dev container

### ISSUE THREAD

**Issue by daras94** [microsoft/vscode#175841] opened 2023-03-02 07:22 UTC
Type: <b>Bug</b>

Not active extension in dev container for de last update in vscode

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.19.0-35-generic

<details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|3.0.2
language-gas-x86|bas|0.0.2
Doxygen|bbe|1.0.0
Nix|bbe|1.0.1
django-html|bib|1.3.0
django|big|1.0.2
mermaid-markdown-syntax-highlighting|bpr|1.5.1
gcc-arm-linux|chi|1.0.1
elixir-syntax-vscode|dev|0.1.2
prototxt|dmi|0.0.6
dotfiles-syntax-highlighting|dot|0.1.0
rust-syntax|dus|0.6.1
LogFileHighlighter|emi|2.16.0
vscode-firefox-debug|fir|2.9.8
remotehub|Git|0.52.0
vscode-ptx-syntax|gka|1.0.0
language-cython|guy|0.0.7
mysql-syntax|jak|1.3.1
better-c-syntax|jef|1.13.2
better-cpp-syntax|jef|1.17.2
better-dockerfile-syntax|jef|1.0.2
better-go-syntax|jef|1.1.0
better-js-syntax|jef|0.0.2
better-objc-syntax|jef|0.2.0
better-objcpp-syntax|jef|0.2.0
better-perl-syntax|jef|1.0.14
better-shellscript-syntax|jef|1.4.2
lua-plus|jep|1.1.1
io|ken|0.0.3
vsc-python-indent|Kev|1.18.0
vscode-cudacpp|kri|0.1.1
ignore-files|lde|0.1.0
auto-build|mar|2.1.45
Lisp|mat|0.1.12
ninja-syntax|mel|1.0.0
vscode-language-pack-es|MS-|1.76.2023030109
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.28.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.30.0
remote-server|ms-|1.0.0
cpu12|nic|1.0.5
mdl|Ome|0.0.1
dart-syntax-highlighting-only|osc|1.0.1
material-icon-theme|PKi|4.24.0
better-less|rad|0.5.0
prolog|reb|0.0.4
scala|sca|0.5.6
gitconfig|sid|2.0.1
octave|toa|0.0.3
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
vscode-ruby|win|0.28.0
material-theme|zhu|3.15.6

(16 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsctsb:30662444
pythonb192cf:30669361
funwalk2cf:30676044

```

</details>

**Comment by sandy081** [comment] 2023-03-02 08:16
> Not active extension in dev container for de last update in vscode

Can you please elaborate more on this? If possible provide a gif/video of the issue you are seeing.

**Comment by twanwv** [comment] 2023-03-02 15:32
Think this is a duplicate of #175705 

To elaborate a bit more, on 1.75.1 opening a remote dev container the extensions referenced in the `.devcontainer/devcontainer.json` in the `customizations: { vscode: { extensions` array are automatically installed.
After upgrading to 1.76.0 those extensions are not automatically installed inside the dev container, resulting in manual actions to install the extensions inside the dev container.

**Comment by sandy081** [comment] 2023-03-08 18:43
I am not sure if it is a duplicate. Is the remote window is on default or custom profile - https://code.visualstudio.com/updates/v1_76#_profiles-in-remote-workspaces

**Comment by twanwv** [comment] 2023-03-08 19:21
Initially it was on a custom profile for me, I removed my profiles and tried again but still run into the same issue.
What I see is that some extensions do get installed in the container, some don't. I haven't found a consistent pattern yet.

I can setup a very simple repository to reproduce this scenario if that helps you @sandy081

**Comment by twanwv** [comment] 2023-03-08 20:00
Decided to make a reproduction repository: https://github.com/twanwv/extension-issue-in-dev-containers

**Comment by twanwv** [comment] 2023-03-10 11:16
On VSCode - Insiders

Version: 1.77.0-insider
Commit: b60db78000bfa99d1b290194ed4651c4ceef02cc
Date: 2023-03-10T05:24:46.841Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

It all works for me, will use it for the time being

**Comment by sandy081** [comment] 2023-03-10 11:39
Ok. Closing it since it works with insiders. Please reopen it if you still see the issue.

**Closed by sandy081** 2023-03-10 11:39 UTC
Labels: info-needed
