### ISSUE TITLE
No horizontal scrolling

### ISSUE THREAD

**Issue by Dec-35** [microsoft/vscode#164330] opened 2022-10-22 12:45 UTC
Type: <b>Bug</b>

When using a Mx Master mouse, the htumb scroll is very usefull as a horizontal scroll but it doesn't work in VSCode.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (7.48GB free)|
|Process Argv|--crash-reporter-id 64709317-4f9c-4ffc-a162-166c184bf159|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jquerysnippets|don|0.0.1
vscode-language-pack-fr|MS-|1.72.10120953
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5739
java|red|1.11.0
LiveServer|rit|5.7.9
ayu|tea|1.0.5
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
php-debug|xde|1.29.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by alexdima** [comment] 2022-10-22 17:08
Duplicate of #84136

**Closed by alexdima** 2022-10-22 17:08 UTC
