### ISSUE TITLE
Highlight for shell script fails after a heredoc end tag with leading spaces

### ISSUE THREAD

**Issue by mchencb** [Microsoft/vscode#61192] opened 2018-10-18 02:50 UTC
- VSCode Version: 1.28.0
- OS Version: Mac OS X High Sierra

Steps to Reproduce:

1. Create a new file `test.sh` with the following content.
    ```bash
    #!/bin/bash

    function test() {
      echo << "  EOS"
        some text
      EOS
    # highlight fails for the rest of the script (same for vscode and github)
    }

    test
    ```
2. While this is a valid bash script, hightlight does not work after a heredoc end tag with leading spaces.
![image](https://user-images.githubusercontent.com/9190517/47128235-fde60a00-d2c2-11e8-8fbc-c21c92db431f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2018-10-23 10:14
duplicate of https://github.com/atom/language-shellscript/issues/122

**Closed by aeschli** 2018-10-23 10:14 UTC
