### ISSUE TITLE
Powershell integrated terminal is always opened when I open folder with vscode.

### ISSUE THREAD

**Issue by bluetifulc** [microsoft/vscode#132533] opened 2021-09-07 10:38 UTC
Issue Type: <b>Bug</b>

1. my setting for integrated terminal
 ```
 "terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "terminal.integrated.cursorStyle": "line"
```
2. When I open folder, powershell is opened ignoring defaultProfile setting.
3. But if I open new terminal (crtl + shift + `), git bash is opened as setting.

This problem appeared after last update of vscode.
After some tries, I found out the folders that I open first time after update don't have problem.
But if i opened folders more than twice, the problem started.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.48GB free)|
|Process Argv|--crash-reporter-id 91b792bb-ff3c-48a4-8b8f-8b9844c2ce61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
file-icons|fil|1.0.29
code-runner|for|0.11.5
python|ms-|2021.8.1105858891
jupyter|ms-|2021.8.1236758218
cpptools|ms-|1.6.0
material-icon-theme|PKi|4.9.0
LiveServer|rit|5.6.1
vscode-wakatime|Wak|15.0.1
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-07 10:50
/duplicate of #132150 and will be fixed in upcoming 1.60.1 recovery release

**Closed** 2021-09-07 10:50 UTC
Labels: *duplicate
