### ISSUE TITLE
Editor not scrolling to centre when cursor out of view

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#107214] opened 2020-09-22 09:49 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open a fairly long file
2. Place the cursor somewhere in the middle
3. Keeping the cursor active on the editor, scroll with mouse wheel up to another part of the code so the cursor is out of sight
4. Press <kbd>→</kbd> to move the cursor
5. Observe that the cursor comes back into view but stays at the very bottom of the editor window
6. Now scroll down so the cursor is out of view again
7. Press <kbd>→</kbd> to move the cursor
8. Observe that the cursor comes back into view but now stays at the very top of the editor window 

Expected behaviour:

For the cursor to come back to the middle/centre of the editor, much like when you press <kbd>CMD + G</kbd> (find next) and you browse through the search results, it also centres the search item in the centre of the editor, which is helpful to quickly locate the cursor/active item.

Now I often find myself losing the cursor and not seeing where it is, because it's all the way at the top or bottom of the screen.

I believe this used to be centered in the previous version of Code, as I only started noticing this behaviour after I updated to this version.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (0.97GB free)|
|Process Argv|-psn_0_1749419|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
file-icons|fil|1.0.26
gc-excelviewer|Gra|3.0.40
name-that-color|gui|0.1.2
json2csv|kha|0.0.1
l13-diff|L13|0.28.1
prettify-json|moh|0.0.3
vetur|oct|0.27.3
multi-command|ryu|1.4.0
vscode-fileutils|sle|3.0.1
control-snippets|svi|1.9.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alexdima** [comment] 2020-09-22 10:57
This was always the behaviour. Cursor revealing when moving the cursor left / right was always configured to be the minimal amount of scrolling necessary to reveal the cursor.

**Comment by adamreisnz** [comment] 2020-09-22 20:13
So why is this the opposite of how search term revealing works, which shifts to the centre?
Seems to me like these two cases should be consistent, or at least configurable to allow us to make them consistent.

**Comment by adamreisnz** [comment] 2021-12-13 06:23
@alexdima can we please get a 2nd pair of eyes on this issue, as I don't believe this is a feature request but a bug as the behaviour is quite inconsistent at the moment.

**Comment by alexdima** [comment] 2021-12-13 09:11
@adamreisnz This is the behavior of the editor since its inception. You can verify this by downloading an old VS Code version (e.g. from 2017 - https://code.visualstudio.com/updates/v1_10 ) and checking it there. This behavior (to do minimal revealing when pressing arrow left or arrow right) is consistent with other code editors. I have just tried XCode and SublimeText. This is not a bug.

**Comment by adamreisnz** [comment] 2021-12-13 09:32
I'll just repeat my question then:

> So why is this the opposite of how search term revealing works, which shifts to the centre?
> Seems to me like these two cases should be consistent, or at least configurable to allow us to make them consistent.

**Comment by alexdima** [comment] 2021-12-13 10:01
> So why is this the opposite of how search term revealing works, which shifts to the centre?

Because pressing arrow left/arrow right is really not the same as clicking on a search result. Yes, they both cause scrolling in the editor to reveal a position, but the use-cases are different:
* when clicking on a search result, it is very likely that the user didn't look at the code before (or maybe since a while). Also, it is not clear what other code around the search result is relevant. It could be some code above, it could be some code below. The safest bet is to reveal the position in the center vertically, rendering both some code above and some code below. In other words, this is the method which most likely minimizes post-reveal scrolling.
* when pressing arrow left/arrow right, the user has intentionally scrolled away from a position which they were looking at. They were looking at that position and then chose to intentionally scroll in a certain direction, let's say up. This is because it is very likely there was something up that they needed to look at in order to continue working at the current position. So when they press arrow left/arrow right we want to do the minimal amount of scrolling to reveal the position, as that might leave the code they were looking at still in the viewport. In other words, this is the method which most likely minimizes post-reveal scrolling.

> Seems to me like these two cases should be consistent, or at least configurable to allow us to make them consistent.

Our goal is to minimize post-reveal scrolling and not to reveal in the same way in all scenarios. This issue has been left open and marked as a feature request to track the feature request to add a configuration option to be able to tweak how revealing works when pressing arrow left/arrow right.

**Closed** 2021-12-22 02:31 UTC
Labels: feature-request, editor-rendering
