### ISSUE TITLE
minimap disappear when peek definition

### ISSUE THREAD

**Issue by tammyrobinson03** [Microsoft/vscode#28478] opened 2017-06-12 02:02 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|base16-themes|AndrsDC|1.3.0|
|vs-code-css-comments|ashhitch|1.0.3|
|arm|dan-c-underwood|0.1.2|
|EditorConfig|EditorConfig|0.9.3|
|csharpextensions|jchannon|1.3.0|
|MagicPython|magicstack|1.0.10|
|cpp-symbols|mirkoh|0.0.1|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.1|
|vscode-icons|robertohuertasm|7.9.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.7|;

---

Steps to Reproduce:

1.
2.

**Comment by wsmelton** [comment] 2017-06-12 03:16
:+1: 

Steps to reproduce:

1. Enable minimap if you have it disabled.
2. Go into a script (I'm using PowerShell).
3. Peek definition on variable (or even CodeLens reference)
4. Minimap will stay until you close the peek window.
5. Close the peek window and the minimap goes away.
6. Does not come back for the current file or any additional file I open. HOWEVER, it is open if I go into user settings.

**Comment by ramya-rao-a** [comment] 2017-06-12 18:37
Thanks for the steps @wsmelton, I can repro too.

Found that this is a duplicate of #28093

The fix is available in the Insiders.

cc @alexandrudima @rebornix

**Closed by ramya-rao-a** 2017-06-12 18:37 UTC
Labels: new release
