### ISSUE TITLE
Aux window: cant interact with juypter notebook when switching from floating window 

### ISSUE THREAD

**Issue by msukkari** [microsoft/vscode#198795] opened 2023-11-21 18:40 UTC
Type: <b>Bug</b>

Steps to repro:

- open a vscode window and open a jupyter notebook (*.ipynb)
- open a floating window and focus on it
- attempt to switch to the jupter notebook using focus shortcut (ex. ctrl + 1)
- observe that you cannot use keyboard shortcuts to interact with the notebook (ex. pressing enter or the arrow keys does nothing)

Current workaround is to have another editor group in the main window that isn't a notebook, and then navigate to that group first and then navigate to the notebook. I have the vim extension enabled but I've tested with it disabled and I'm still able to repro

VS Code version: Code - Insiders 1.85.0-insider (da5ab29656a9f0bef63602fbce10968a7f4db2b5, 2023-11-20T18:53:26.158Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1026-aws

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vim|vsc|1.27.0
copilot|Git|1.138.0
copilot-chat|Git|0.11.2023112102
autopep8|ms-|2023.9.13201008
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.11.1003211000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment] 2023-11-21 19:16
@msukkari can you try with latest insiders that has the fix for https://github.com/microsoft/vscode/issues/198607 in?

**Comment by msukkari** [comment] 2023-11-22 00:05
I believe I am using the latest insiders (`1.85.0-insider`) since the issue [#198607](https://github.com/microsoft/vscode/issues/198607) is resolved. I can switch between the windows (even the first group) just fine, it's only when I'm switching to a notebook that this new issue arises. This issue happens even when the notebook is in the second editor group on the main window

**Comment by bpasero** [comment] 2023-11-22 04:47
![Recording 2023-11-22 at 05 46 50](https://github.com/microsoft/vscode/assets/900690/6ef8a421-c132-4d9b-a1bd-1206bfbc054a)

I am not able to reproduce directly with another notebook type: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks

Can you try if its specific to Juypter?

**Comment by msukkari** [comment] 2023-11-22 16:46
Thanks for trying to repro. Looks like it's possible to switch back to the notebook and navigate within the cell, but I am unable to navigate across cells from the keyboard. I'm navigating across cells within the notebook by pressing esc to unfocus a specific cell, and then using the arrow keys to navigate up and down different cells. If the notebook is not focused on a specific cell, after I navigate to it from a floating window I am unable to navigate between cells with the keyboard 

Tried with the github issue notebook type and it seems to happen as well

**Comment by bpasero** [comment] 2023-12-02 05:55
I believe the issue for navigating between cells is a duplicate of https://github.com/microsoft/vscode/issues/199729: I think the notebook is backed by a list widget and the symptoms are the same. I will see to push a fix for that next week and then we can see if this issue is addressed as well.

**Closed** 2023-12-04 10:03 UTC
Labels: bug, notebook-commands, workbench-auxwindow
