### ISSUE TITLE
C++ multilne comment render error

### ISSUE THREAD

**Issue by th1nk3r-ing** [microsoft/vscode#195012] opened 2023-10-06 16:13 UTC
Type: <b>Bug</b>

The line begin with `timestamps` will be Identify as code.

```c++
#define AVFMT_TS_NEGATIVE  0x40000 /**< Format allows muxing negative
                                        timestamps. If not set the timestamp
                                        will be shifted in av_write_frame and
                                        av_interleaved_write_frame so they
                                        start from 0.
                                        The user or muxer can override this through
                                        AVFormatContext.avoid_negative_ts
                                        */
```

- U can new a cpp file & input the test code above.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.64GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/th1nk3r/work/FFmpeg --remote=wsl+Ubuntu-22.04|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 3799)|
|Memory (System)|15.59GB (14.24GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3801)|
|Memory (System)|31.93GB (18.64GB free)|
|VM|31%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
CppSnippets|har|0.0.15
vscode-drawio|hed|1.6.6
vscode-auto-open-markdown-preview|hnw|0.0.4
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.315.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.7
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vscode-icons|vsc|12.5.0
vscode-todo-highlight|way|1.0.5
vscode-markdownlint|Dav|0.52.0
vscode-clangd|llv|0.1.24
vscode-language-pack-zh-hans|MS-|1.83.2023100409
cpptools|ms-|1.17.5
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details>

**Comment by justschen** [comment] 2023-10-10 18:39
@th1nk3r-ing was there a different expected behavior in 1.82?

**Comment by th1nk3r-ing** [comment] 2023-10-11 02:18
> @th1nk3r-ing was there a different expected behavior in 1.82?

NO, the same as `v1.83`.    
It's been an issue for a while.

**Comment by th1nk3r-ing** [comment] 2023-10-11 02:20
I was able to replicate this bug on macos as well. 
<img width="715" alt="image" src="https://github.com/microsoft/vscode/assets/25501591/870bc50f-a481-4a22-901c-4b7b0901b365">

**Comment by alexr00** [comment] 2023-11-16 14:25
Duplicate of upstream issue: https://github.com/jeff-hykin/better-cpp-syntax/issues/646

**Closed by alexr00** 2023-11-16 14:25 UTC
