### ISSUE TITLE
Add ability to change from opt+click to cmd+click on explorer view to open file in second pane

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#61213] opened 2018-10-18 07:52 UTC
Currently I have to opt + click on the file name in Explore view to open it in second pane. I wish I could just use cmd + click as it's much nicer placed on the keyboard.

I found https://github.com/Microsoft/vscode/issues/43067 but it seems this behavior can't be changed.

**Comment by isidorn** [comment] 2018-10-18 07:54
Cmd + click works for me on the mac.
Are you on windows? If you are you can use both ctrl + click, and alt + click

Sorry but we will not support cmd + click on windows -> closing as out of scope

**Closed** 2018-10-18 07:55 UTC
Labels: *out-of-scope

**Comment by nikitavoloboev** [comment] 2018-10-18 08:00
> Cmd + click works for me on the mac.

It worked for me before too. But now cmd + click does nothing. Perhaps there is a [setting I changed in VS Code](https://github.com/nikitavoloboev/dotfiles/blob/master/vscode/settings.json). I am not sure what caused it to not work for me.

**Comment by isidorn** [comment] 2018-10-18 08:03
@nikitavoloboev can you reproduce with latest vscode insiders? https://code.visualstudio.com/insiders/

**Comment by nikitavoloboev** [comment] 2018-10-18 08:13
> can you reproduce with latest vscode insiders

Just downloaded Insiders. Yes I can reproduce it there. cmd + click simply highlights the file but doesn't open it on the side.

![2018-10-18 at 10 13](https://user-images.githubusercontent.com/6391776/47140417-75656a80-d2be-11e8-9b8a-93678e035a33.png)
