### ISSUE TITLE
TypeScript language server keeps dying

### ISSUE THREAD

**Issue by will-wow** [microsoft/vscode#149782] opened 2022-05-18 00:18 UTC
Issue Type: <b>Bug</b>

The typescript language server dies a few times a day for me. I'm working on a TypeScript React Chraka-UI monorepo (with Lerna), with a few servers running, but nothing totally insane. On Window WSL 2

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (0.67GB free)|
|Process Argv|--crash-reporter-id ae9c0c57-77ab-43c6-8882-a2c3e72168f2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics (16 x 3293)|
|Memory (System)|7.47GB (1.57GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.5.0
javascript-ejs-support|Dig|1.3.1
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.66.3
vscode-autohotkey|sle|0.2.2
vim|vsc|1.22.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.5.0
copilot|Git|1.20.5902
vscode-pull-request-github|Git|0.42.0
vscode-styled-components|jpo|1.6.6
vscode-insertdatestring|jsy|2.3.1
solidity|Jua|0.0.139
vscode-github|Kni|0.30.7
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
vscode-xml|red|0.20.0
LiveServer|rit|5.7.5
code-spell-checker|str|2.2.0
vsfire|tob|1.4.1
language-pde|Tob|1.4.6
vscode-pets|ton|1.10.0
gitblame|wad|8.2.0
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment] 2022-05-18 01:52
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides wsl)?

**Comment by edgerunner** [comment] 2022-05-18 13:36
Just figured out that the same problem for me was somehow caused by the [Imba] [extension].

[Imba]: https://imba.io
[extension]: https://marketplace.visualstudio.com/items?itemName=scrimba.vsimba

```
stack trace: Error: <syntax> TypeScript Server Error (4.6.4)Cannot read properties of undefined (reading 'Symbol(#readFile)')
TypeError: Cannot read properties of undefined (reading 'Symbol(#readFile)')    
at readFile (/Users/mert/.vscode/extensions/scrimba.vsimba-3.1.14/node_modules/typescript-imba-plugin/dist/index.js:13046:7233)
```

**Comment by mjbvz** [comment] 2022-06-15 00:05
Closing as more info needed from the original poster

**Closed by mjbvz** 2022-06-15 00:05 UTC
Labels: needs more info
