### ISSUE TITLE
bug with context menus

### ISSUE THREAD

**Issue by artmih24** [microsoft/vscode#178745] opened 2023-03-31 00:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0-insider
- OS Version: Windows 11
![image](https://user-images.githubusercontent.com/83209415/228991338-0d0a6711-0530-4224-91ea-d23de57b367e.png)

Steps to Reproduce:

1. launch VSCode-insiders
2. click on menu on menubar

**Comment by Kathund** [comment] 2023-03-31 00:53
Just wanting to point out that it also dose this when clicking on the account or the settings button in the bottom left

**Comment by starball5** [comment] 2023-03-31 01:10
Note: I don't get this on 1.77 on Ubuntu

**Comment by starball5** [comment] 2023-03-31 01:11
Duplicate of #178730 ?

**Comment by Kathund** [comment] 2023-03-31 01:55
> Duplicate of #178730 ?

assume so by looking at it

**Comment by Kathund** [comment] 2023-03-31 02:54
@artmih24 Currently if your turn on **Reduce Motion** it will fix it.
![Code_-_Insiders_FtUQHG6BFs](https://user-images.githubusercontent.com/55346310/229011163-11b8c0b0-2b7a-47b0-91f9-7a5e4f37e05a.png)

Theres already an open issue about it (#178730) so can you please cloes this issue

**Comment by Kathund** [comment] 2023-03-31 03:51
This can be closed as it has been fixed with #178731 just restart and it should download the update and the fix

**Closed** 2023-03-31 07:59 UTC

**Comment by FallingObject** [comment] 2023-03-31 16:18
I think it has something to do with windows 11 new update, because it was working fine last night, then I let it update without closing code-insiders and now the issue popped up.

**Comment by Kathund** [comment] 2023-03-31 21:53
> I think it has something to do with windows 11 new update, because it was working fine last night, then I let it update without closing code-insiders and now the issue popped up.

this issue is the devs pushed an update to fix it. i dont run windows 11 and i had it anyway o it cant be
