### ISSUE TITLE
Not able to see one of the sym link of three in folder(file explorer)

### ISSUE THREAD

**Issue by Sreevenkateshn** [microsoft/vscode#165340] opened 2022-11-03 11:04 UTC
Type: <b>Bug</b>

Hi there,

    I was not able to see the symlink in a folder. there are three symlinks and i was able to see two, one symlink is not visible in file explorer.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.73GB (16.32GB free)|
|Process Argv|--crash-reporter-id 88388880-c064-4131-bda6-5e4bdd4a68cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
vscode-svgviewer|css|2.0.0
gobystrok|GoB|0.0.1
backbone-js-snippets|ioa|0.0.1
hungry-delete|jas|1.7.0
backbone-language|log|0.0.2
csslint|ray|0.0.11
LiveServer|rit|5.7.9
vscode-icons|vsc|12.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
iaj6b796:30602301

```

</details>

**Comment by lramos15** [comment] 2022-12-06 18:29
Likely duplicate of https://github.com/microsoft/vscode/issues/167146

**Closed by lramos15** 2022-12-06 18:29 UTC
