### ISSUE TITLE
Code Insiders Angular imports 

### ISSUE THREAD

**Issue by Dovernh** [Microsoft/vscode#34765] opened 2017-09-21 15:59 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.2.3
gitlens|eam|5.1.0
tslint|eg2|1.0.8
prettier-vscode|esb|0.23.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
angular2-switcher|inf|0.1.4
csharpextensions|jch|1.3.0
Angular2|joh|2.7.0
csharp|ms-|1.12.1
material-icon-theme|PKi|2.2.1
better-merge|ppr|0.7.0
typescript-hero|rbb|1.5.0
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:
![captureimports](https://user-images.githubusercontent.com/1800249/30705742-4e766426-9ec4-11e7-9da2-18fdc5a75823.PNG)

1. Open angular project with code-insiders
2. Any imports with '@angular/core' as an example have a red squiggly and hovering over says [ts] says cannot find module .... No problem with imports with custom code
3. Uninstall code-insiders and install code
4. Open angular project with code, no issues 
5. Launch with code-insiders --disable-extensions still shows same issue listed in #2

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-09-21 17:13
Duplicate of #34681

**Closed by mjbvz** 2017-09-21 17:13 UTC
Labels: duplicate, insiders, javascript
