### ISSUE TITLE
Save All not working if more than one source to be saved

### ISSUE THREAD

**Issue by andguestofall** [microsoft/vscode#128106] opened 2021-07-07 08:03 UTC
Issue Type: <b>Bug</b>

Simply amend multiple files...go to the File menu and 'Save All' is disabled

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.0.0-32-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2875)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (7.53GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id a08f0376-d3ed-4bc8-bfe3-06058f5d5b5c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by gjsjohnmurray** [comment] 2021-07-07 10:10
/duplicate of #126133 and fixed in upcoming 1.58, scheduled for release this week.

**Closed** 2021-07-07 10:11 UTC
Labels: *duplicate

**Comment by bperreault** [comment] 2021-07-09 15:25
Thank You for Fixing This Issue.
