### ISSUE TITLE
Pause gif playback button in Release notes

### ISSUE THREAD

**Issue by gewoonwoutje** [microsoft/vscode#102030] opened 2020-07-09 21:28 UTC
In the release notes, there are often gifs that explain a feature. Very helpful, but it can be a bit distracting when reading the file. I'd like to be able to pause the animation of the gif in the release notes view.

It's not an uncommon feature, for instance MS Teams has this capability.

**Comment by mjbvz** [comment] 2020-07-13 18:48
Duplicate of #92493

**Closed by mjbvz** 2020-07-13 18:48 UTC
