### ISSUE TITLE
F12 definition not found

### ISSUE THREAD

**Issue by olegdunkan** [microsoft/vscode#90449] opened 2020-02-11 13:24 UTC
After compiling project with new angular Ivy support I can't go to definition to all @angular declarations (for example, FormGroup, OnInit ...)via F12.
Visual code writes: No definition found for '...' .
I have disabled all extensions, reinstalled all node_modules.
But for my declarations within project all works as expected and for other libs like  'rxjs', 'lodash' and etc as expected.  

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment] 2020-02-11 17:24
Duplicate of https://github.com/microsoft/TypeScript/issues/36335

**Closed by mjbvz** 2020-02-11 17:24 UTC
