### ISSUE TITLE
Can't rename a folder

### ISSUE THREAD

**Issue by wallybh** [Microsoft/vscode#5172] opened 2016-04-11 20:35 UTC
- VSCode Version:0.10.11
- OS Version:Windows 10

Steps to Reproduce:

1. Open powershell and cd to a existing project folder
2. run "code ."
3. Try to rename an existing folder

VSCode return an error "Operation not permtited".

![image](https://cloud.githubusercontent.com/assets/593137/14441479/53d1b80c-000b-11e6-8ec2-7a1f8161381e.png)

**Comment by bpasero** [comment] 2016-04-12 05:12
Closing as duplicate of #4578

**Closed by bpasero** 2016-04-12 05:12 UTC
