### ISSUE TITLE
Git: Submodules keep appearing

### ISSUE THREAD

**Issue by vogler** [microsoft/vscode#103235] opened 2020-07-24 09:23 UTC
Issue Type: <b>Bug</b>

I found issue #40947, deactivated `git.detectSubmodules` in my workspace settings, closed all submodules, but vscode still reopens them (after it gets focus?).

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
haskero|Van|1.3.1
Bookmarks|ale|11.3.1
vscode-sqlite|ale|0.8.2
svelte-intellisense|ard|0.7.1
spellright|ban|3.0.50
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
graphviz-preview|EFa|1.3.3
vscode-npm-script|eg2|0.3.12
vscode-great-icons|emm|2.1.47
macros|ged|1.2.1
vscode-pull-request-github|Git|0.18.0
gc-excelviewer|Gra|3.0.39
latex-workshop|Jam|8.11.1
svelte-vscode|Jam|0.9.3
hoogle-vscode|jca|0.0.7
dune|mae|0.0.5
package-json-dependencies-navigation|mam|0.1.8
Lisp|mat|0.1.10
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
cpptools|ms-|0.29.0
hexeditor|ms-|1.1.0
ocaml-platform|oca|0.8.0
vscode-code-outline|pat|0.2.1
vscode-data-preview|Ran|2.0.0
gi|rub|0.2.11
vscode-gtm|s3r|0.2.0
linter-xo|sam|2.3.3
code-settings-sync|Sha|3.4.3
vscoq|sie|0.2.7
latex-utilities|tec|0.3.7
vsfire|tob|1.4.1
stylish-haskell|vig|0.0.10
vscode-arduino|vsc|0.3.1
vscode-icons|vsc|10.2.0
vim|vsc|1.16.0
vscode-wakatime|Wak|4.0.0
quokka-vscode|Wal|1.0.310
better-align|wwm|1.1.6
material-theme|zhu|3.8.5

(3 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment] 2020-07-24 12:10
Do the submodules still appear if you restart VS Code?

**Comment by vogler** [comment] 2020-07-24 12:58
Thanks, that fixed it. So, 'requiring a restart/not showing a message about it' is still a bug?

**Comment by vogler** [comment] 2020-07-24 14:41
Ok, I don't know what triggered it, but now they're open again.

**Comment by joaomoreno** [comment] 2020-08-05 14:21
@vogler Can you still repro this? Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by vogler** [comment] 2020-08-05 14:47
No, now it doesn't do it on refresh anymore but still does it on restart:
![recording](https://user-images.githubusercontent.com/493741/89427150-36c2cd80-d73b-11ea-9ac4-a5d7c7425286.gif)

**Comment by joaomoreno** [comment] 2020-08-05 16:17
Thanks for the screen recording. Does it also repro if you close all editor tabs?

**Comment by vogler** [comment] 2020-08-05 20:34
Yes

**Comment by AlCalzone** [comment] 2021-02-05 20:33
Same happens here. I have a git submodule in a directory, close the repo in the git sidebar, do something else and the submodule comes back.

**Comment by abirke** [comment] 2021-07-01 15:53
I am facing the same problem. Both options `git.detectSubmodules = false` and `git.ignoreSubmodules = true` don't seem to fix it. Unfortunately, I am not an expert on this field. Is there any way I can collect some helpful logs or try to debug into it?

Thanks and best regards
André

**Comment by wilhelmer** [comment] 2021-07-22 09:16
Same here, would be great to see this fixed.

**Comment by duskmoon314** [comment] 2021-08-18 03:22
Same here

```
1.59.0 (user setup)
379476f0e13988d90fab105c5c19e7abc8b1dea8
2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by wilhelmer** [comment] 2021-09-16 12:22
Just found out that you can add the submodules to `git.ignoredRepositories`. It works now, they're gone!

**Comment by lszomoru** [comment] 2022-12-09 15:41
Closing as duplicate of https://github.com/microsoft/vscode/issues/107398

**Closed by lszomoru** 2022-12-09 15:41 UTC
Labels: bug, help wanted, git
