### ISSUE TITLE
errors & strange traces in linux build

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#142572] opened 2022-02-09 00:12 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154859&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=6b00722f-1101-5770-9e0c-f427af83d823

```
[main 2022-02-08T23:49:08.484Z] Starting extension host with pid 6536 (fork() took 22 ms).
[main 2022-02-08T23:49:08.485Z] ExtensionHostStarterWorker.start() took 436 ms.
IExtensionHostStarter.start() took 839 ms.
Finished waiting on IWorkspaceTrustManagementService.workspaceResolved.
Invoking resolveAuthority(test)
Gtk-Message: 23:49:08.773: GtkDialog mapped without a transient parent. This is discouraged.
[6428:0208/234909.278634:INFO:CONSOLE(29)] "%c INFO color: #33f Starting worker process with pid 6587 (type: fileWatcher, window: 1).", source: vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[6428:0208/234937.291470:INFO:CONSOLE(3035)] "The customer named _initialize has been holding on to the lock for 30s. This might be a problem.", source: vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js (3035
```

```
[0208/234908.357692:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0208/234908.358712:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0208/234908.358751:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[6428:0208/234908.482186:ERROR:bus.cc(393)] Failed to connect to the bus: /usr/bin/dbus-launch terminated abnormally with the following error: Crashing due to FD ownership violation:
#0 0x555b116c2463 <unknown>
#1 0x555b1176938c <unknown>
#2 0x555b11769351 <unknown>
#3 0x7ff89eb22395 <unknown>
#4 0x7fffeeb07330 <unknown>
#5 0x555b1243f5c6 <unknown>
#6 0x555b1243fc2b <unknown>
#7 0x555b0f0b7eee <unknown>
#8 0x555b0f0a9c13 <unknown>
#9 0x555b0ef6d460 <unknown>
#10 0x555b106e1735 <unknown>
#11 0x3f2400080eb8 <unknown>
#12 0x3f240000c761 <unknown>
#13 0x3f240009eb8d <unknown>
#14 0x3f240000c761 <unknown>
#15 0x3f240000c761 <unknown>
#16 0x3f240000c761 <unknown>
#17 0x3f24002d012f <unknown>
#18 0x3f24002e2c0e <unknown>
#19 0x3f240000a75c <unknown>
#20 0x3f240000a487 <unknown>
#21 0x555b1079eb28 <unknown>
#22 0x555b1079df8a <unknown>
#23 0x555b10696a2e <unknown>
#24 0x555b14cf1192 <unknown>
#25 0x555b0ef37bfd <unknown>
#26 0x555b0ef3ac8f <unknown>
#27 0x555b0f07b643 <unknown>
#28 0x555b11713425 <unknown>
#29 0x555b117294a6 <unknown>
#30 0x555b1172a63f <unknown>
#31 0x555b116dedcf <unknown>
#32 0x7ff89ff59537 <unknown>
#33 0x005400084fc0 <unknown>
#34 0x555b116dea9b <unknown>
#35 0x555b1172aaa4 <unknown>
#36 0x555b116fcb82 <unknown>
#37 0x555b0ffb8d13 <unknown>
#38 0x555b0ffba902 <unknown>
#39 0x555b0ffb6588 <unknown>
#40 0x555b0fe74ff4 <unknown>
#41 0x555b0fe74a1f <unknown>
#42 0x555b0fe7250f <unknown>
#43 0x555b0fe72ef9 <unknown>
#44 0x555b0ef4ba2c <unknown>
#45 0x7ff89b381bf7 <unknown>
```

**Comment by EricTulowetzke** [comment] 2022-02-09 07:53
Same here and just when I updated too.

```
$ code-insiders -v                                      
1.65.0-insider
d09aeab62c1f93acf4a89b93e9a8a82419d6249a
x64

 $ code-insiders --verbose                               
[main 2022-02-09T07:45:35.039Z] [File Watcher (node.js)] Request to start watching: /home/eric/.config/Code - Insiders/User (excludes: <none>),/home/eric/.config/Code - Insiders/User/settings.json (excludes: <none>)
[main 2022-02-09T07:45:35.055Z] Starting VS Code
[main 2022-02-09T07:45:35.055Z] from: /opt/visual-studio-code-insiders/resources/app
[main 2022-02-09T07:45:35.056Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '31a941db-3731-4359-a541-722bd65d04fd',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/eric/.config/Code - Insiders/logs/20220209T014535'
}
[main 2022-02-09T07:45:35.057Z] Resolving machine identifier...
[main 2022-02-09T07:45:35.057Z] Resolved machine identifier: 9eedff6eb979a71df2a51997cfbe4ead6809ab249520fa36fb35e44ff4a7419d
[main 2022-02-09T07:45:35.058Z] Main->SharedProcess#connect
[main 2022-02-09T07:45:35.061Z] [File Watcher (node.js)] Started watching: '/home/eric/.config/Code - Insiders/User'
[main 2022-02-09T07:45:35.064Z] [File Watcher (node.js)] Started watching: '/home/eric/.config/Code - Insiders/User/settings.json'
[main 2022-02-09T07:45:35.108Z] StorageMainService: creating global storage
[main 2022-02-09T07:45:35.114Z] lifecycle (main): phase changed (value: 2)
[main 2022-02-09T07:45:35.115Z] windowsManager#open
[main 2022-02-09T07:45:35.116Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '454e9c443d002e52d9c1d4a0659921d8', uri: [h] },
    type: 2,
    exists: true
  }
]
[main 2022-02-09T07:45:35.116Z] windowsManager#doOpenFolderOrWorkspace {
  folderOrWorkspace: {
    workspace: { id: '454e9c443d002e52d9c1d4a0659921d8', uri: [h] },
    type: 2,
    exists: true
  },
  filesToOpen: undefined
}
[main 2022-02-09T07:45:35.117Z] IPC Object URL: Registered new channel vscode:339374b8-39b0-4c5c-8d55-e78b2f9314d2.
[main 2022-02-09T07:45:35.117Z] window#validateWindowState: validating window state on 2 display(s) { mode: 0, x: 1792, y: 96, width: 1024, height: 768 }
[main 2022-02-09T07:45:35.117Z] window#validateWindowState: multi-monitor working area { x: 1536, y: 32, width: 1536, height: 832 }
[main 2022-02-09T07:45:35.117Z] window#ctor: using window state { mode: 0, x: 1792, y: 96, width: 1024, height: 768 }
[main 2022-02-09T07:45:35.155Z] window#load: attempt to load window (id: 1)
[main 2022-02-09T07:45:35.159Z] StorageMainService: creating workspace storage (454e9c443d002e52d9c1d4a0659921d8)
[main 2022-02-09T07:45:35.160Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2022-02-09T07:45:35.160Z] lifecycle (main): phase changed (value: 3)
[main 2022-02-09T07:45:35.161Z] update#setState idle
[main 2022-02-09T07:45:35.161Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[0209/014535.177532:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

will need to look into rolling back version if this isn't fixed by morning 

please let me know if I can help in any way

**Comment by deepak1556** [comment] 2022-02-10 15:49
@EricTulowetzke the issue you are facing should be fixed with latest insiders, please give it a try. Thanks!

**Comment by JacksonKearl** [comment] 2022-02-14 17:59
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155814&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=a5663145-e9fb-5b6a-6210-7b66b21662a2

**Comment by bpasero** [comment] 2022-02-15 07:26
@deepak1556 please see https://github.com/microsoft/vscode/commit/7dbd7367dc96690ae1cae12f9d74191b3f21b6fe for a change to disable crash reporting in Linux CI.

**Comment by bpasero** [comment] 2022-02-15 07:46
Oh and also in smoke tests: https://github.com/microsoft/vscode/commit/5faea719c597992e5186bd4954bbe5d95a5d215c

**Comment by deepak1556** [comment] 2022-02-15 12:11
thanks @bpasero

**Comment by deepak1556** [comment] 2022-02-15 15:24
dbus errors continues with the crash reporter disabled, one of the recent runs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=156012 after the above commits. I will continue to investigate this via the Electron 17 branch, the errors are harmless and looks like we will need the crash reporter back on in the azure CI to capture a recent regression in the native-keymap module https://vscodeteam.slack.com/archives/C1Y427SES/p1644923219041849?thread_ts=1644922937.657609&cid=C1Y427SES

@bpasero can we revert your above commits ?

**Comment by bpasero** [comment] 2022-02-15 15:28
@deepak1556 ok I have pushed 2 reverts, however one thing to keep in mind is that on Linux at least I see dozens of crash dumps being attached as artefacts and I wonder if that slows down the CI sufficient enough that we end up in our timeouts. Have we figured out what these crash dumps actually are? I am referring to https://github.com/microsoft/vscode/issues/143000

**Comment by deepak1556** [comment] 2022-02-15 15:45
Just looked into them, they are related to this issue. All of them have crash when attempting to connect with dbus,

```
Crash reason:  SIGTRAP
Crash address: 0x0
Process uptime: 0 seconds

Thread 0 (crashed)
 0  code-insiders!close + 0x75
    rax = 0xc0391b5eb08c8b00   rdx = 0x0000000000000001
    rcx = 0x00007f497a0513a7   rbx = 0x00007ffe5e9a3b00
    rsi = 0x000055fe775d8bba   rdi = 0x0000000000000000
    rbp = 0x00007ffe5e9a42e0   rsp = 0x00007ffe5e9a3b00
     r8 = 0x0000000000000000    r9 = 0x00007ffe5e9a3590
    r10 = 0x00000000000116e8   r11 = 0x0000000000000000
    r12 = 0x00001c6600e8c000   r13 = 0x00007ffe5e9a4300
    r14 = 0x00007ffe5e9a4460   r15 = 0x0000000000000000
    rip = 0x000055fe7aad9395
    Found by: given as instruction pointer in context
 1  code-insiders!close + 0x31
    rbp = 0x00007ffe5e9a42f0   rsp = 0x00007ffe5e9a42f0
    rip = 0x000055fe7aad9351
    Found by: previous frame's frame pointer
 2  libdbus-1.so.3!_dbus_close_all [dbus-sysdeps-unix.c : 4422 + 0x7]
    rsp = 0x00007ffe5e9a4300   rip = 0x00007f49782de395
    Found by: stack scanning
 3  libdbus-1.so.3!_dbus_get_autolaunch_address [dbus-sysdeps-unix.c : 3879 + 0xb4]
    rbx = 0x00007ffe5e9a45c0   rbp = 0x00007ffe5e9a4550
    rsp = 0x00007ffe5e9a4340   r12 = 0x00007ffe5e9a4360
    r13 = 0xffffffffffffffff   rip = 0x00007f49782de927
    Found by: call frame info
 4  libdbus-1.so.3!_dbus_transport_open_autolaunch [dbus-transport.c : 297 + 0xe]
    rbx = 0x0000000000000000   rbp = 0x00007ffe5e9a45c0
    rsp = 0x00007ffe5e9a4530   r12 = 0x00007ffe5e9a45b8
    r13 = 0x0000000000000000   r14 = 0x00007ffe5e9a4550
    r15 = 0x0000000000000010   rip = 0x00007f49782d30d5
    Found by: call frame info
 5  libdbus-1.so.3!_dbus_transport_open [dbus-transport.c : 396 + 0xb]
    rbx = 0x00001c6601509770   rbp = 0x00007ffe5e9a45c0
    rsp = 0x00007ffe5e9a45a0   r12 = 0x00007ffe5e9a45b8
    r13 = 0x0000000000000000   r14 = 0x00007f49784f59d0
    r15 = 0x0000000000000010   rip = 0x00007f49782d2f70
    Found by: call frame info
 6  libdbus-1.so.3!_dbus_connection_open_internal [dbus-connection.c : 1887 + 0xb]
    rbx = 0x0000000000000000   rbp = 0x0000000000000000
    rsp = 0x00007ffe5e9a4630   r12 = 0x00007ffe5e9a4680
    r13 = 0x00007ffe5e9a4660   r14 = 0x0000000000000000
    r15 = 0x00001c6601509770   rip = 0x00007f49782bd195
    Found by: call frame info
 7  libdbus-1.so.3!internal_bus_get [dbus-bus.c : 474 + 0x8]
    rbx = 0x0000000000000000   rbp = 0x00007ffe5e9a4790
    rsp = 0x00007ffe5e9a46f0   r12 = 0x00007ffe5e9a4b50
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x00007ffe5e9a47b0   rip = 0x00007f49782b8af4
```

I will push up this issue to be tackled this iteration as it does make our builds flaky, will look into why the connection failes.

**Closed** 2022-02-16 17:08 UTC
Labels: important, linux, engineering, integration-test-failure, electron-16-update
