### ISSUE TITLE
Undo redo cursor moves to the top of the file

### ISSUE THREAD

**Issue by muqsith** [Microsoft/vscode#46057] opened 2018-03-18 12:57 UTC
Issue Type: <b>Bug</b>

Write something in the file and save it.
Again change something in the same file then save it again, 
and then do undo  (Ctrl + Z) and save and then redo (Ctrl + Shift + Z) then the cursor moves to the top of the file.

Current Behavior: Cursor moves to the top of the file.

Expected Behavior: Cursor to remain at the chnaged text location.

This is very unpleasant if the number of lines in the file are many and scrolling is enabled.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Load (avg)|5, 4, 3|
|Memory (System)|31.30GB (17.08GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
ejs-language-support|Qas|0.0.1
vscode-svgviewer|css|1.4.3
gitlens|eam|8.1.1
debugger-for-chrome|msj|4.2.1

</details>
Reproduces without extensions

**Comment by singhravi1** [comment] 2018-03-19 12:20
+1

**Comment by julien-HAM** [comment] 2018-03-19 12:49
+1

**Comment by alexandrudima** [comment] 2018-03-28 20:39
fyi @bpasero The root cause is the same as #45538

The symptom (undo going back to [1,1]) is fixed via #46208.

**Closed by alexandrudima** 2018-03-28 20:39 UTC
Labels: editor, editor-core
