### ISSUE TITLE
Support i18n in extension contributions page

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#69209] opened 2019-02-22 13:02 UTC
Issue Type: <b>Feature Request</b>

here is the screenshot

![2019-02-22 21 01 34](https://user-images.githubusercontent.com/9758711/53244189-15a42380-36e5-11e9-90e9-f1aa40ee5bdf.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment] 2019-02-22 14:35
Duplicate of #54111

**Closed by sandy081** 2019-02-22 14:35 UTC
Labels: extensions
