### ISSUE TITLE
Disable editor replacing double L with a joint character

### ISSUE THREAD

**Issue by jansensan** [microsoft/vscode#111385] opened 2020-11-26 22:07 UTC
**VSCode Version**
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**OS Version**
macos 10.15.7 (19H15)

**Steps to Reproduce:**

1. Open a file in VScode
2. Type either a double L (e.g. `elle`) or even an L with a space in between (e.g. `el le`)
3. VScode replaces the double l with a character that is a merge of `l·l`

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1410355/100393983-88080d00-3009-11eb-9c7e-fcb526546a6d.png">

**Additional Notes**

- No, this is not part of the text replacements I have set up in mac os
- If you copy that part of text and paste it elsewhere, the character is not copied
- Navigating one character at a time takes this as a single character
- Adding two spaces between the character removes that ligature

Does this issue occur when all extensions are disabled?: **Yes**

**Expected**
No ligature should occur, characters should not be replaced and remain independent.

**Comment by ArturoDent** [comment] 2020-11-26 22:31
What font are you using?  Does this happen if you use a different font?

**Comment by IllusionMH** [comment] 2020-11-26 22:54
In addition to the question about font above - is it reproducible if you set `editor.renderWhitespace` to `"none"`?

**Comment by alexdima** [comment] 2020-11-27 07:40
Duplicate of #106583. Workaround is to use `"editor.fontLigatures": "'ccmp' off"`

**Closed by alexdima** 2020-11-27 07:40 UTC
Labels: needs more info
