### ISSUE TITLE
Up arrow in a read only editor sometimes moves you outside the editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27765] opened 2017-05-31 17:49 UTC
Extracted from @Neurrone 's comment in https://github.com/Microsoft/vscode/issues/26730#issuecomment-303906193

I've installed the add-on and the global plugin that bumps the wait time up to 200ms.

...

Also when in the editor for files in readonly mode, pressing up arrow when on the first line unexpectedly moves you outside the editor. Down arrows will also sometimes move you outside the editor as well.

**Comment by alexandrudima** [comment] 2017-06-12 12:54
I could not reproduce this issue in the diff left-hand-side read-only editor. I can, however, reproduce in the default settings editor, where arrow up after the first line moves focus out of the editor to a section toggle. 

The initial comment from @Neurrone mentions being in the default settings.

**Comment by Neurrone** [comment] 2017-06-12 12:57
@alexandrudima looks like a problem specific to that control

**Comment by rebornix** [comment] 2017-07-12 22:49
IMHO, moving up cursor on the first line of a section moves focus the section header is a feature. Once the focus is on the section header, you can use arrow keys to expand/collapse the section and even navigate through different sections fastly. @sandy081 can confirm this.

@Neurrone is this the only case that you run into this problem?

**Comment by Neurrone** [comment] 2017-07-15 09:48
@rebornix I personally find it more confusing than helpful, since the expectation of users in edit boxes is that the arrow keys will never cause you to leave the edit box if you're already inside. That instance is the only one which I've found so far, but I'm waiting till more issues are fixed to use it more intensively.

**Comment by sandy081** [comment] 2017-07-17 06:52
@rebornix Yes I confirm. Default settings editor is a special editor. It is in a state in between editor and UI widget. 

>>since the expectation of users in edit boxes is that the arrow keys will never cause you to leave the edit box if you're already inside

Agreed. But this Default Settings is a special read only editor with some widgets incorporated. IMO, I feel I should move away from using Editor for rendering Default Settings which will makes lot of things simple and intuitive. But then, users might loose the functionality of copying the contents of default settings like in editor. Its a trade off we have to make.

**Comment by sandy081** [comment] 2017-08-25 15:23
Closing this based on above comment.

**Comment by alexandrudima** [comment] 2017-09-01 10:20
@sandy081 Doing nothing does not seem to me to be the best outcome here.

How about we add some code that alerts when arrow up is "stolen" by the Default Settings special keybinding. i.e. `alert("Focused on Commonly Used group")` or something along those lines that allow for some understanding for someone using us with a Screen Reader ?

**Comment by sandy081** [comment] 2017-09-01 11:08
I wonder if this is already the case that when the group is focused, screen reader shouts the title/aria-label of the group. Can confirm.

**Comment by sandy081** [comment] 2017-09-01 11:12
Confirmed that on focusing on the group, nothing is mentioned. 

@alexandrudima Not sure why the aria-label is not read by the screen reader? 

Reopening

**Comment by alexandrudima** [comment] 2017-09-01 13:35
@sandy081 I don't know why the aria label is not read by the screen reader. Perhaps the screen reader expects that focus remains in the editor when pressing arrow up ?

**Comment by sandy081** [comment] 2018-09-18 13:20
Closing this in favour of new settings editor.

**Closed by sandy081** 2018-09-18 13:20 UTC
Labels: accessibility, bug, settings-editor
