### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by jovialp** [microsoft/vscode#135266] opened 2021-10-18 05:50 UTC
Issue Type: <b>Bug</b>

1. Open VS Code
2. Start node server using "npm start" or "yarn start"
3. After few minutes, able to see the notification banner at the right bottom VS Code with the warning text "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:15:35.620Z)
OS version: Linux x64 5.11.0-37-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2275)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|9, 5, 3|
|Memory (System)|15.56GB (4.96GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e52708ce-d051-4dad-98b9-ec81cc9f2249|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.19
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by mrantivirus** [comment] 2021-10-20 01:09
I just updated to v1.61.2 and the issue seems to be fixed. @jovialp do you still get this bug after upgrading?

**Comment by tecnologia-magno** [comment] 2021-11-04 18:45
Do the settings below:
` "typescript.tsserver.useSyntaxServer": "never"`
works?

**Comment by mjbvz** [comment] 2021-11-10 00:23
Closing as it sounds like this is no longer reproducible

**Closed by mjbvz** 2021-11-10 00:23 UTC
Labels: needs more info
