### ISSUE TITLE
The selection of Russian characters happens by itself

### ISSUE THREAD

**Issue by NazarBog123** [microsoft/vscode#139317] opened 2021-12-16 18:28 UTC
Issue Type: <b>Bug</b>

Different letters in Ukrainian and Russian are highlighted with a yellow square (MacOS)

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 3a60d137-cf43-44f3-a3c6-efda9f21317c --crash-reporter-id 3a60d137-cf43-44f3-a3c6-efda9f21317c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.62
auto-rename-tag|for|0.1.9
vscode-gutter-preview|kis|0.29.0
vscode-scss|mrm|0.10.0
vscode-language-pack-ru|MS-|1.63.3
vetur|oct|0.35.0
vscode-css-navigation|puc|1.11.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
material-theme|zhu|3.13.6

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by IllusionMH** [comment] 2021-12-16 19:56
/duplicate of #138869 > #138767

Also see https://code.visualstudio.com/updates/v1_63#_unicode-highlighting

**Closed** 2021-12-16 19:57 UTC
Labels: *duplicate, new release, triage-needed
