### ISSUE TITLE
typescript 中的 模板字符串 中第一个表达式总是无法获取到变量提示 

### ISSUE THREAD

**Issue by shynome** [Microsoft/vscode#26984] opened 2017-05-20 08:00 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1.输入 es6 模板字符串 ``
2.在其中插入变量 ${ x } , 在 x 区域获取不到提示

**Comment by mjbvz** [comment] 2017-05-21 19:10
Can you manually trigger suggestions in the string using `ctrl` + `space`?

**Comment by shynome** [comment] 2017-05-22 02:59
@mjbvz Thanks , it's hulepful . 
Before  the 1.1 version, I just type is enough , I want to know how can I do to be like before .

**Comment by mjbvz** [comment] 2017-05-22 15:31
This is a duplicate of #23962 To replicate the old behavior, try:

```json
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```

**Closed by mjbvz** 2017-05-22 15:31 UTC
Labels: duplicate, typescript
