### ISSUE TITLE
Multiple folders at the same time

### ISSUE THREAD

**Issue by Rajsharma9593** [Microsoft/vscode#20656] opened 2017-02-15 14:03 UTC
- VSCode Version:
- OS Version:

Like you know we can open multiples files at the same time or pin it to status bar so , I think it is needed sometimes to open a multiple  folders which is not allowed in it. So please provide us with a ability to open multiples folders through side bar like that of files.
Thank you.

**Comment by jofravelo** [comment] 2017-02-15 16:07
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/396

**Comment by mjbvz** [comment] 2017-02-15 21:29
Thanks @jofravelo. Yes this is a duplicate of #396

**Closed by mjbvz** 2017-02-15 21:29 UTC
Labels: duplicate
