### ISSUE TITLE
Launch configs: resolve replacement patterns in object keys, in addition to values

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#38455] opened 2017-11-15 23:05 UTC
From https://github.com/Microsoft/vscode-chrome-debug/issues/226

A chrome-debug config can have

```
            "sourceMapPathOverrides": {
                "webpack:///C:/Depot/Impakt/DNA/DNACore/*": "${webRoot}/*" // SUCCEEDS
                //"webpack:///${workspaceRoot}/*": "${webRoot}/*" // FAILS
                //"webpack:///${webRoot}/*": "${webRoot}/*"  // FAILS
            },   
```

vscode replaces `${workspaceRoot}` in values, and the adapter replaces `${webRoot}` in values, and now after https://github.com/Microsoft/vscode-chrome-debug/pull/543, in keys as well. It would be great if vscode would replace `${workspaceRoot}` in keys.

One issue is that you can have collisions where two keys are the same after applying these replacements. In chrome-debug now, the last one wins where "last" is technically undefined.

**Comment by weinand** [comment] 2017-11-15 23:26
duplicate of #34059.
I've just raised the priority of this to "On Deck".

**Closed by weinand** 2017-11-15 23:26 UTC
Labels: debug, feature-request
