### ISSUE TITLE
Open a folder with VS Code but VSCode also opens both this folder and recent folder

### ISSUE THREAD

**Issue by hoangitk** [Microsoft/vscode#37198] opened 2017-10-31 03:06 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.22.0
tslint|eg2|1.0.14
scriptcsRunner|fil|0.1.0
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
csharp|ms-|1.12.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vscode-docker|Pet|0.0.20
quokka-vscode|Wal|1.0.72

---

Steps to Reproduce:

0. There is no opened VS Code.
1. Right click in a folder project => Open with Code
2. VS Code will open both choose folder and recent folder of other project (2 VS Code instances)

Or
1. Use open by command line: code .

Reproduces without extensions: Yes

It happens both Menu Context and from command line (code .)
Screen capture:
![vscode_issue](https://user-images.githubusercontent.com/342078/32205946-d705bd9e-be24-11e7-9d6c-e081899e2992.gif)

**Comment by bpasero** [comment] 2017-10-31 08:55
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by hoangitk** [comment] 2017-11-01 13:19
Hi @bpasero,

I think I found out the issue with Steps to Reproduce:
1. Open Folder A with VS Code. Edit a file without save. Close VS Code.
2. Open Folder B with VS Code. It will auto open both Folder A and Folder B.

Sometime VS Code asks to Save file before closing, sometime not.

Below is my captured screen with VSCode Insider:
![vscode_issue_2](https://user-images.githubusercontent.com/342078/32276202-c3ff464e-bf40-11e7-9bd5-288042aee9d4.gif)

**Comment by bpasero** [comment] 2017-11-01 13:23
@hoangitk this works as designed, we reopen any window that had a dirty file. assigning to @Tyriar since this is about hot-exit.

**Comment by Tyriar** [comment] 2017-11-01 19:33
Yes this is as designed, you can look into using this setting to not reopen the window with unsaved files:

```js
"files.hotExit": "onExitAndWindowClose"
```

Be careful as you could lose track of unsaved changes under this setting though.

**Closed by Tyriar** 2017-11-01 19:33 UTC
Labels: hot-exit, workbench
