### ISSUE TITLE
vscode update to 1.11 removes mostly all default keybindings

### ISSUE THREAD

**Issue by NoSuchProcess** [Microsoft/vscode#24535] opened 2017-04-11 16:04 UTC
- VSCode Version: 1.11.1
- OS Version: Fedora 25 x86_64, XFCE desktop, LANG=ru_RU.UTF-8

Steps to Reproduce:

1. install 1.11 or update from 1.10 to 1.11
2. press Ctrl+N, Ctrl+S - no result, also drop-down menu shows no keybindings for frequently used (i'd say - standart)  actions.

![bug](https://cloud.githubusercontent.com/assets/3430181/24918609/68e98bf2-1efa-11e7-95a0-c418ed92a455.png)

[layout.ru_pc105.txt](https://github.com/Microsoft/vscode/files/913929/layout.ru_pc105.txt)

update: vscode on Ubuntu-14 x86_64 LANG=ru_RU.UTF-8 isn't affected by this issue

**Comment by NoSuchProcess** [comment] 2017-04-11 16:20
[layout.ru_pc105.txt](https://github.com/Microsoft/vscode/files/913919/layout.ru_pc105.txt)

**Comment by alexandrudima** [comment] 2017-04-12 08:15
Duplicate of #24057. A fix is available in the latest Insiders Release.

**Closed by alexandrudima** 2017-04-12 08:15 UTC
