### ISSUE TITLE
Cannot Read "/extensions/csharp-o/packages.json"

### ISSUE THREAD

**Issue by rabel001** [Microsoft/vscode#1901] opened 2016-01-10 02:36 UTC
I get this error each time I open Visual Code.

[c:/Program Files/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files/Microsoft VS Code/resources/app/extensions/csharp-o/package.json: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\extensions\csharp-o\package.json'

**Comment by joaomoreno** [comment] 2016-01-11 08:37
Duplicate of #1605

**Workaround:** delete the `csharp-o` folder.

**Closed by joaomoreno** 2016-01-11 08:37 UTC
