### ISSUE TITLE
Reopen with GB2312 encoding is very slow

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#43248] opened 2018-02-08 20:45 UTC
- VSCode Version: 1.20.0
- OS Version: Windows 10.0.16299.192 x64

Steps to Reproduce:

1. Open a 9MB file that is encoded in GB2312 (or GBK or GB18030)
2. Use command palette to choose "Change File Encoding", then "Reopen with Encoding", then "GB 2312".

I takes several minutes for the operation to complete. And it prompts "Application Not Responding" several times during the operations. Need to select "Keep Waiting" for the operation to complete.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by AnaDron** [comment] 2018-02-26 10:07
The same problem with Windows 1251 encoding.

**Comment by rebornix** [comment] 2018-02-27 21:35
It would be great if you can share the data to help troubleshoot.

**Comment by AnaDron** [comment] 2018-02-28 07:17
[test.log](https://github.com/Microsoft/vscode/files/1765931/test.log)
This is a small 1Mb file. When i reopen in win1251 - it takes 2-3 seconds.
Real log file size over 10Mb - reopen them around 1-2 minutes.

**Comment by cnshenj** [comment] 2018-02-28 07:30
[test.txt](https://github.com/Microsoft/vscode/files/1765991/test.txt)
You can easily make a test file by copying/pasting same block of text several times. The file content doesn't matter.

**Comment by rebornix** [comment] 2018-03-05 19:47
Shared the same root cause as https://github.com/Microsoft/vscode/issues/41184 and it's fixed in master.

**Closed by rebornix** 2018-03-05 19:47 UTC
Labels: file-encoding, needs more info
