### ISSUE TITLE
Multiroot: Automatic Generation of launch.json for node has wrong paths

### ISSUE THREAD

**Issue by grork** [microsoft/vscode#60536] opened 2018-10-10 16:55 UTC
- VSCode Version: 1.28.1
- OS Version: 10.0.17763.55

Steps to Reproduce:

1. Clone https://github.com/Microsoft/vscode-smoketest-express
2. Open VS Code
3. Add `public`, `routes`, and `views` to a _workspace_ (Don't open the root folder)
4. Open `index.js` from the `routes` root.
5. Press F5
6. Select Node in the debugger quick pick when it's shown
7. Message: Attribute 'program' does not exist ('F:\temp\smoke-test-repo\routes/routes\index.js').
8. Select open launch.json, and select node again to see the generated file

Does this issue occur when all extensions are disabled?: Yes

Expected behaviour:
`launch.json` is generated, with the `program` attribute as follows: `"program": "${workspaceFolder}\\index.js"`

Actual Behaviour:
`launch.json` is generated, with the `program` attribute as follows: `"program": "${workspaceFolder}/routes\\index.js"`

**Comment by isidorn** [comment] 2018-10-11 14:53
I can reproduce this.
This is coming from a debug adapter, forwarding to @weinand 
Corner case since it is only happening for multi root workspaces on win

**Comment by connor4312** [comment] 2020-11-06 00:25
This appears fixed in the new debugger.

**Closed** 2020-11-06 00:26 UTC
Labels: *not-reproducible, bug, debug
