### ISSUE TITLE
Move the find in selection button into a filters dropdown

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158598] opened 2022-08-19 15:00 UTC
Current:

![image](https://user-images.githubusercontent.com/2193314/185647240-acfbbaa5-c5e8-4174-bfab-0ee8172ad217.png)

Proposed:

![image](https://user-images.githubusercontent.com/2193314/185647283-ed77a2f3-2511-4b81-b08e-a9d49d2061be.png)

When a filter is non-default:

![image](https://user-images.githubusercontent.com/2193314/185647310-75076080-99db-4526-bf50-b9684a8f8b09.png)

Find in selection behaves a little strangely currently as it's enabled when there is no selection, we could disable the dropdown entry in this case.

We can also expand this filter to include find in commands/strings/brackets in the future so it's not just a single entry. @hediet is there a feature request for this you could link?

**Comment by hediet** [comment] 2022-08-22 07:31
No known feature request for this.

**Comment by misolori** [comment] 2022-08-29 04:10
I believe we had previously discussed this in https://github.com/microsoft/vscode/issues/14836#issuecomment-926959562

**Comment by amunger** [comment] 2022-12-14 22:16
duplicate of https://github.com/microsoft/vscode/issues/144851

**Closed by amunger** 2022-12-14 22:16 UTC
Labels: debt, editor-find
