### ISSUE TITLE
Terminals are reactivated...

### ISSUE THREAD

**Issue by SunrunnerK** [microsoft/vscode#231550] opened 2024-10-17 00:34 UTC
Type: <b>Bug</b>

Hello, I can't execute codes. There is no error message, only the bottom status bar says "Terminals are being reactivated...". A circle spins next to it. This problem is persistent and cannot be solved even by reinstalling VS Code. What can I do? Unfortunately my internet searches didn't come up with anything. 

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900K (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.18GB free)|
|Process Argv|--crash-reporter-id 47df230f-bab5-463a-beb2-382ed11451db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
guiscript|Dam|0.0.1
pygame-snips|Dha|0.0.4
vscode-language-pack-de|MS-|1.94.2024101609
vscode-edge-devtools|ms-|2.1.6
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
java|red|1.35.1
pip-manager|sli|1.1.4
pygame-snippets|tus|0.0.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.9.0
five-server|yan|0.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31160513
icondisabled:31158250

```

</details>

**Comment by albertosantini** [comment] 2024-10-17 06:12
Anything related with python?

Did you see

https://github.com/microsoft/vscode-python/issues/23922
https://github.com/microsoft/vscode-python/issues/23963

Hope that helps.

**Comment by karthiknadig** [comment] 2024-10-17 17:21
See here for possible workarounds: https://github.com/microsoft/vscode-python/issues/23922#issuecomment-2293911979

duplicate of https://github.com/microsoft/vscode-python/issues/23922

**Closed by karthiknadig** 2024-10-17 17:21 UTC
