### ISSUE TITLE
Icons in WATCH view missing in latest VSC insiders

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#90177] opened 2020-02-06 22:03 UTC
Version: 1.42.0-insider (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-05T20:04:22.920Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

The highlighted icons to add and remove variables (while debugging) in the WATCH view are missing in latest VS Code insiders. The following screenshot is from the stable version

![image](https://user-images.githubusercontent.com/13199757/73982500-3b700b80-48e9-11ea-94b3-1e3f9332ccbc.png)

Does this issue occur when all extensions are disabled?: No

**Comment by eamodio** [comment] 2020-02-06 22:26
I can't reproduce this on either `1.42` or the latest `1.42-insiders` -- Can you provide more details?

**Comment by karrtikr** [comment] 2020-02-06 22:42
I just noticed it's only happening when Python extension is activated

### Steps to reproduce

- Install the python extension
- Open a workspace folder containing python file
- Open python file to activate the extension

It's working fine in the previous versions of VSC

**Comment by karrtikr** [comment] 2020-02-06 22:55
I just noticed it's only happening when Python extension is installed

### Steps to reproduce

- Install the python extension
- Open a workspace folder containing `.vscode/launch.json` and a python file
- Open the python file

It's working fine in the previous versions of VSC

**Comment by isidorn** [comment] 2020-02-07 12:44
This works for me. Please note the picture.
We did not do any changes in this area. Thus it is my reason to believe that something changed in the python extension.
I suggest that you simply F1 > develoepr tools > investigate that area where the icons are missing and see if the HTML elements are present, is the css for icon applied and so on.

![Screenshot 2020-02-07 at 13 42 40](https://user-images.githubusercontent.com/1926584/74030598-bac81280-49af-11ea-8d3a-36067dcf9ce0.png)

**Comment by karrtikr** [comment] 2020-02-12 00:37
@isidorn It happens with me irrespective of which extension is installed. Updated the steps to repro:

- Disable all the installed extensions from the Command palette
- Open a workspace containing `launch.json`.
_Observe that the WATCH window is fine_
- Enable any one of the extensions
_Have a look at the WATCH window again. The icons disappear_

My other co-worker also sees this issue even in VS Code stable. Please try reproducing it again, thanks for the patience.

If you're still not able to repro, I will check the CSS and get back to you.

**Comment by isidorn** [comment] 2020-02-12 10:55
@karrtikr thank you for the steps. I can also reproduce.

I think the issue here is that we moved to the new View and container infrastructure. When all extensions get disabled - we probably re-add the views to the view container and some bad timing seems to happen.
I checked and I set the correct actions from the Watch view [here](https://github.com/microsoft/vscode/blob/ddf6ed326c7ffed826b91fb67e6e936fa79cf17e/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L102) however the view container probably later overwrites this.
Due to that assigning to @sbatten . To repro just:
1) Open debug viewlet, hover over watch actions -> they are there
2) Disable all extensions, hover over watch actions -> they are not there. The action bar is not aware of them, even though I see that they are nicely added to the toolbar on startup, but probably they get cleared away. Can you please investigate?

Even though this happens in stable this is not a candidate since it is a corner case, and there are alternative command palette actions to these. Thus assigning to february.

fyi @sandy081

**Comment by isidorn** [comment] 2020-02-12 15:18
After consulting with @sandy081 he came to the good idea that we should drop the pattern of setting the actions directly on the toolbar, but we should instead always have the `getActions()`. Thus I have updated my views and now the issue no longer seems to happen.
@karrtikr thanks for reporting this!

**Closed** 2020-02-12 15:18 UTC
Labels: bug

**Comment by karrtikr** [comment] 2020-02-12 21:11
Happy to. Thanks for the quick fix!
