### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes infinite loop

### ISSUE THREAD

**Issue by bbouski** [Microsoft/vscode#19994] opened 2017-02-06 00:38 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|sp-tools|Mike|0.3.0|

---

Steps to Reproduce:

1. Mount SharePoint Online Site Asset Library as Network Drive
2. Open drive as folder in VSC
2. Try and work with any JavaScript file.

**Comment by rmunn** [comment] 2017-02-06 10:19
#20009 seems to be a duplicate of this one. Caused by https://github.com/Microsoft/TypeScript/issues/13874

**Comment by mjbvz** [comment] 2017-02-06 18:46
Thanks @rmunn. Yes, this looks like a duplicate of Microsoft/TypeScript#13874. Closing as upstream

We're coordinating with the TypeScript team to try to fix this

**Closed by mjbvz** 2017-02-06 18:46 UTC
Labels: bug, javascript, typescript, upstream
