### ISSUE TITLE
@vscode please help me I am facing issue in my mac m2 in running c++ code  I am sharing the compiler issue  below and I have all the requires compiler 

### ISSUE THREAD

**Issue by Pavan8104** [microsoft/vscode#209045] opened 2024-03-28 18:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by mjbvz** [comment] 2024-03-28 19:50
Duplicate of #209047

**Closed by mjbvz** 2024-03-28 19:50 UTC
