### ISSUE TITLE
Split terminal splits to the left

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123127] opened 2021-05-06 13:14 UTC
![recording](https://user-images.githubusercontent.com/22350/117304177-4db16000-ae32-11eb-8fd4-c510afe202a1.gif)

**Comment by joaomoreno** [comment] 2021-05-06 13:21
Also, and maybe even worse: focus is put on the right editor. 😢

**Comment by meganrogge** [comment] 2021-05-06 14:26
Duplicate of #123117

**Closed by meganrogge** 2021-05-06 14:26 UTC
Labels: *duplicate, bug, integrated-terminal, integrated-terminal-tabs
