### ISSUE TITLE
File nesting in selfhost `build/lib` folder appears broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#147772] opened 2022-04-20 14:25 UTC
In our repo, all `build/lib/**/*.ts` files appear as if they have nested files. But those files are ignored from the explorer anyway, so the whole thing appears very messy:

![image](https://user-images.githubusercontent.com/22350/164252985-769755f4-c9db-43bf-ac51-cd28817227af.png)

**Comment by JacksonKearl** [comment] 2022-04-20 19:32
Duplicate of #141430. I'm considering either ignoring `file.excludes` when in a nested context (as nesting is an alternative solution to the some of same problems `file.excludes` solves), or just excluding them entirely and rendering the file as usual when nesting is enabled. 

An intermediary approach could be to collapse the nests by default when they only contain hidden files, but still show the files if the nest is manually expanded. 

What do you think?

**Comment by joaomoreno** [comment] 2022-04-21 12:03
> excluding them entirely and rendering the file as a usual, un-nested file, when nesting is enabled but all of its children are hidden

This is my expected behavior.

**Comment by JacksonKearl** [comment] 2022-04-26 17:01
Fixed with https://github.com/microsoft/vscode/issues/141430.

**Closed by JacksonKearl** 2022-04-26 17:01 UTC
