### ISSUE TITLE
Bug with maximizing window when "Automatically hide the taskbar in desktop mode" is "on" on Windows10

### ISSUE THREAD

**Issue by alengYuan** [microsoft/vscode#84759] opened 2019-11-14 02:59 UTC
- VSCode Version: 1.40.1 (system setup) [8795a9889db74563ddd43eb0a897a2384129a619]
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Update your VSCode to 1.40.0.
2. Switch "Automatically hide the taskbar in desktop mode" to "on" on your Windows10.
3. Make sure that "Window: Title Bar Style" of your VSCode is "custom".
4. Maximize the window of your VSCode.
5. Then, you may reproduce the bug like ones in following gifs.

![issue1](https://user-images.githubusercontent.com/25302878/68822106-0037b500-06cb-11ea-8383-1d63a0061376.gif)

- Can't call taskbar by sliding the mouse to the edge of the screen, until you press the "Windows" key on keyboard.

![issue2](https://user-images.githubusercontent.com/25302878/68822127-0fb6fe00-06cb-11ea-9d40-3fc2e02f7a89.gif)

- Bad "maximize" button, but the window would work normally when double click on title bar.

Does this issue occur when all extensions are disabled?: Yes

P.s. In fact the first bug also could be reproduced on some of other softwares which based on electron.js, but before I updated to 1.40.0, VSCode didn't have this problem, may be you could fix it. 😊

**Comment by yume-chan** [comment] 2019-11-14 04:51
duplicate of #81102

Please always search before posting new issues.

**Comment by alengYuan** [comment] 2019-11-14 07:50
> 
> 
> duplicate of #81102
> 
> Please always search before posting new issues.

Yep, I have got it, vscodebot has told me that and I would do as you told me in the future (I really have searched related issues, but I am not familiar to the usage of issue search and I used keyword which is not suitable, so... I am sorry 😓).

But this issue is more like with #84342 than #81102.

**Comment by yume-chan** [comment] 2019-11-14 08:27
> But this issue is more like with #84342 than #81102.

Yes, you are right, sorry I didn't read your issue carefully.

**Comment by alengYuan** [comment] 2019-11-14 08:49
> 
> Yes, you are right, sorry I didn't read your issue carefully.

That's all right. And thanks for your contributions. 😀

**Comment by deepak1556** [comment] 2019-11-14 23:27
The root cause is same for all these issues, I am merging them together. Thanks for the report!

/duplicate https://github.com/microsoft/vscode/issues/81102

**Closed** 2019-11-14 23:27 UTC
Labels: *duplicate, new release
