### ISSUE TITLE
Option to Selectively Disable Toast Notifications for Extensions

### ISSUE THREAD

**Issue by michaelbrazell** [microsoft/vscode#94923] opened 2020-04-10 15:40 UTC
It would be great if users could disable notifications from extensions for specific extensions or globally for all extensions.  

In the last few months more and more extensions have started using the notifications area to show what amount to be ads, and some extensions do not respect the "Dismiss" button, or the notification will come back after dismissing it a short time later.

The example that prompted me to make the request is the "Highlight Matching Tag," extension which is a great extension, except it's basically pedalling ads for a VSCode Power Users course (See Screenshot):

<img width="558" alt="Screen Shot 2020-04-10 at 11 29 01 AM" src="https://user-images.githubusercontent.com/1779475/79002888-711ab600-7b1f-11ea-91ee-1b2c16a04ab6.png">

While this is one of the more egregious abuses of the notification area (the button opens a paid course which does not look to be affiliated or sponsored by VSCode / Microsoft and I suspect the extension developer is getting a referral bonus for advertising), there are other extensions which also seem to flood the area with toast notifications that really aren't helpful ("Updated VS Code Icons -- See what's changed!" eh, some people may find value in a changelog for an icon pack but I don't).

Thanks!

**Comment by Saf3ty1nnumb3rs** [comment] 2020-04-10 21:15
@michaelbrazell is spot on. This has brought advertising into the development space and is distracting. Despite  "Highlight Matching Tag" being useful, I may need to let it go as it is detracting from the value of the development space overall.
Having to remove a toast every time I need to view some sort of terminal or reporting on the bottom right takes from workflow and ultimately has a non-trivial impact on the overall productivity and experience.

**Comment by RMacfarlane** [comment] 2020-04-10 21:36
Duplicate of https://github.com/microsoft/vscode/issues/41767

**Closed by RMacfarlane** 2020-04-10 21:36 UTC
