### ISSUE TITLE
I hope vscode can open files by mutiple windows such as sublime text

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#6424] opened 2016-05-17 12:53 UTC
I hope vscode can open files by mutiple windows such as sublime text

**Comment by Tyriar** [comment] 2016-05-17 17:50
Duplicate of https://github.com/Microsoft/vscode/issues/48

**Closed by Tyriar** 2016-05-17 17:50 UTC

**Comment by biij5698** [comment] 2016-05-18 13:17
What time is it can support ?

**Comment by biij5698** [comment] 2016-05-18 13:17
@Tyriar  What time is it can support ?

**Comment by Tyriar** [comment] 2016-05-18 18:27
@biij5698 follow #48 to track the issue.
