### ISSUE TITLE
Custom PROMPT_COMMAND always executed with $? of 1 when shell integration is enabled

### ISSUE THREAD

**Issue by luxaritas** [microsoft/vscode#157294] opened 2022-08-05 16:57 UTC
Type: <b>Bug</b>

According to https://github.com/microsoft/vscode/issues/150243 this was supposed to have been resolved, but I was able to reproduce it on 1.70 and the latest insiders build. Running `trap` does not produce any output, so I assume this is not related to https://github.com/microsoft/vscode/issues/150241. Let me know if there's any additional debugging I can do or info I can provide, but I think the context should be identical to the previous issue - aside from the exit code always being `1` instead of `0`.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:48.541Z)
OS version: Linux x64 5.18.14-1-MANJARO snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3896)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|15.28GB (0.46GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 92f9d4a3-8422-4e6d-ba6a-5a6a7a7c1f55|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
reabank-syntax-highlighting|ada|1.1.0
toggle-hidden|adr|1.0.2
vscode-prisma-raw-query-sql|Aku|0.0.1
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
gitignore|cod|0.9.0
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
yash|dao|0.2.9
vscode-eslint|dba|2.2.6
javascript-ejs-support|Dig|1.3.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.8
vscode-jest-runner|fir|0.4.48
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
go|gol|0.35.1
todo-tree|Gru|0.0.215
beautify|Hoo|1.5.0
dynamic-inputs|igr|0.0.15
latex-workshop|Jam|8.28.0
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
mips|kda|0.0.9
vscode-gutter-preview|kis|0.30.0
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.8
sqltools|mtx|0.23.0
gremlins|nho|0.26.0
angular-console|nrw|17.19.1
vetur|oct|0.35.0
explorer-exclude|Pet|1.3.1
polacode|pnp|0.3.4
prisma|Pri|4.1.0
fabric8-analytics|red|0.3.6
java|red|1.9.0
vscode-commons|red|0.0.6
rust|rus|0.7.8
scala|sca|0.5.6
metals|sca|1.18.0
markdown-preview-enhanced|shd|0.6.3
code-spell-checker|str|2.3.4
svelte-vscode|sve|105.20.0
sass-indented|syl|1.8.22
language-stylus|sys|1.16.0
pdf|tom|1.2.0
cmake|twx|0.0.17
lorem-ipsum|Tyr|1.3.1
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
volar|Vue|0.39.4
quokka-vscode|Wal|1.0.496
vscode-todo-highlight|way|1.0.5
vscode-nginx|wil|0.7.2
local-history|xyz|1.8.1
vscode-caddyfile-syntax|zam|1.0.4
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by benblank** [comment] 2022-08-05 17:41
This occurs for me as well, using Bash 5.1.16 on Ubuntu 22.04 under WSL2 in Windows 10 21H2. To reproduce:

1. Launch VS Code
2. Create new WSL window.
3. Open integrated terminal.
4. Run `__vsc_original_prompt_command='echo $?'` to overwrite the stored prompt command.
5. Run `true`; observe that "1" is printed, indicating that `$?` was not correctly available to the prompt command.

**Comment by benblank** [comment] 2022-08-05 18:00
After playing around with the shell integration script a bit, I was able to find a fix/workaround: setting `$?` back to `$__vsc_status` immediately before evaluating the prompt command. (Tested with both string and array variants of PROMPT_COMMAND.)

In other words, after launching an integrated terminal, run:

```sh
__vsc_prompt_cmd_original() {
  __vsc_status="$?"
  # Evaluate the original PROMPT_COMMAND similarly to how bash would normally
  # See https://unix.stackexchange.com/a/672843 for technique
  if [[ ${#__vsc_original_prompt_command[@]} -gt 1 ]]; then
    for cmd in "${__vsc_original_prompt_command[@]}"; do
      __vsc_status="$?"
      (exit $__vsc_status)
      eval "${cmd:-}"
    done
  else
    (exit $__vsc_status)
    eval "${__vsc_original_prompt_command:-}"
  fi
  __vsc_precmd
}
```

(Alternatively, `cp "$(code --locate-shell-integration-path bash)" …`, edit the corresponding function definition in the copy, and include that in your `.bashrc`.)

**Comment by friedbrice** [comment] 2022-08-06 00:35
I'm seeing the same problem on my machine, ever since I upgraded VS Code a few days ago.

```
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

## Control Group: my other virtual terminal
<img width="650" alt="Screen Shot 2022-08-05 at 5 12 03 PM" src="https://user-images.githubusercontent.com/3302003/183226274-33e373c9-31b5-45c7-962d-84095717395e.png">
Notice the `$` prompt is determined by the exit status of the previous command.

## Experimental Group: VS Code's integrated terminal
<img width="598" alt="Screen Shot 2022-08-05 at 5 12 26 PM" src="https://user-images.githubusercontent.com/3302003/183226304-f183dfb6-48f1-448c-8816-d0f97f1eb300.png">
Notice the `$` prompt is always red.

## My .bashrc

Here is the relevant fragment of my `.bashrc`.

```bash
function set_bash_prompt {
  # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
  # return value of the last command.
  set_prompt_symbol $?

  PS1="${LIGHT_GREEN}\u${WHITE}@${YELLOW}\h${WHITE}:${LIGHT_BLUE}\w${COLOR_NONE}\n${DARK_GRAY}[\D{%H:%M:%S}] ${PROMPT_SYMBOL} "
}

PROMPT_COMMAND='set_bash_prompt'
```

**Comment by Tyriar** [comment] 2022-08-10 13:09
Fixed by https://github.com/microsoft/vscode/pull/157631

/closedWith d6fbc86

**Closed by Tyriar** 2022-08-10 13:09 UTC
Labels: bug, terminal-shell-integration, terminal-shell-bash
