### ISSUE TITLE
A logical problem with Line Number Active Foreground

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#51765] opened 2018-06-13 13:22 UTC
- VSCode Version: 1.24.0
- OS Version: Mac 10.13.4 (17E202)

As always, thanks a lot for the great stuff you bring to vscode.

Since the new version of Visual Studio Code added this beautiful __Line Number Active Foreground Coloring__ feature for the themes I noticed a little problem in the logic:

![vscode-active-line-line-number-foreground](https://user-images.githubusercontent.com/2157285/41353513-abff39f4-6f31-11e8-8e1b-c553c4f5b29b.gif)

See, I guess `4` must remain active when the cursor is on the wrapped portions of the line, shouldn't it?

**Comment by usernamehw** [comment] 2018-06-13 21:09
Duplicate of #45365

**Closed** 2018-06-14 12:13 UTC
Labels: editor-colors
