### ISSUE TITLE
Git - "Stage Selected Ranges" creates a "Staged Changes" file of type UTF-8 when the orginal file is ANSI (Windows 1252)

### ISSUE THREAD

**Issue by jekitf** [microsoft/vscode#111915] opened 2020-12-04 22:12 UTC
Issue Type: <b>Bug</b>

1. Create a file of type ANSI (Windows 1252). In Notepoad++ (Encoding-ANSI, Encoding-Character sets-Western  European-Windows 1252).
2. Add the scandinavian letters: ØÆÅ to the file. (hex D8 C6 C5)
3. Add the file to a git repo
--
4. Edit the file and add "\r\n-" (hex 0D 0A 2D)
5. Git source control: "Stage Selected Ranges"  for the one line containing "-" (hex 2D)
6. Commit the file from "Staged Changes"
7. Delete the file on disk
8. Git source control:  Select the file and "Discard changes" (to restore the file from git)
--
The file have the content: C3 98 C3 86 C3 85 0D 0A 2D
Expected content: D8 C6 C5  0D 0A 2D

The file have been changed from ANSI to UTF-8 in git.

In C++ using "Use Multi-Byte Character Set" this is a fatal bug

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3602)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (4.12GB free)|
|Process Argv|--crash-reporter-id 48361099-29ee-4112-bdbe-983a488188b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gc-excelviewer|Gra|3.0.40
csharp|ms-|1.23.6
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
powershell|ms-|2020.6.0
vetur|oct|0.30.3
vscode-zipexplorer|sle|0.3.1
pdf|tom|1.1.0

</details>

**Comment by jekitf** [comment] 2020-12-04 23:02
Is this the problem?


\extensions\git\src\git.ts

![image](https://user-images.githubusercontent.com/10177867/101223679-dca42b80-368c-11eb-8b3e-51847f082a1f.png)

Value if specified in settings should be used


![image](https://user-images.githubusercontent.com/10177867/101223482-70292c80-368c-11eb-8eb2-60bec8148f2a.png)

**Comment by eamodio** [comment] 2021-01-06 23:47
@jekitf I think that utf8 is ok, but the one 2 lines above it might be the issue. But not sure. I won't really be able to look at this this iteration at least, so any testing/PR that you can provide would be greatly appreciated.

**Comment by MadsAdrian** [comment] 2021-03-19 09:16
Facing a similar issue. Related to #36219?

**Comment by hkcomori** [comment] 2021-03-23 02:12
This problem also occurs with Shift-JIS files.

- VSCode Version 1.54.3
- Windows 10 Pro x64 Version 1909

Steps to Reproduce:

1. Setup user settings according to this:
```json
{
    "files.encoding": "shiftjis"
}
```

2. Initialize a git repository
3. Create a file which is encoded by Shift-JIS
4. Open the diff of the created file
5. Select some lines and run "Stage Selected Ranges"

**Comment by Dub1shu** [comment] 2021-04-06 15:18
I'm facing the same problem with Shift-JIS.  
Therefore, I tried to verify it.  
As eamodio says, this line seems to be the cause of the bug.
```
child.stdin!.end(data, 'utf8');
```
### Verification Code
\extensions\git\src\git.ts
![verification](https://user-images.githubusercontent.com/81973731/113728239-e029eb00-9730-11eb-9b53-cb7f849101fb.png)

### Verification Process
1. Create a non-UTF-8 file (Shift-JIS in this case), add some text and commit it.
2. Set the workspace encoding setting to Shift-JIS.
3. Add new line.
4. In source control view, select the new line and execute "Stage Selected Ranges".

**Current Stable**  
The Shift-JIS file is converted to UTF-8 by "Stage Selected Ranges".  
![Before](https://user-images.githubusercontent.com/81973731/113732916-f33eba00-9734-11eb-9e5f-9faeb27cff54.png)

**Verification code result**  
Shift-JIS files are staged as is.
![After](https://user-images.githubusercontent.com/81973731/113732936-f9349b00-9734-11eb-9865-8f6e24a78c5a.png)

This verification code is an ad hoc fix and I'm not sure if it's the right way to fix the bug.

**Comment by ankostis** [comment] 2021-12-03 10:14
Isn't this one supposed to have already been fixed by #84130 (as reported on #55110 --> #36219)?
Maybe that fix is the root cause?

**Comment by lszomoru** [comment] 2022-03-23 15:58
https://github.com/microsoft/vscode/pull/84130 has addressed the problem related to encoding when files are being shown in the diff editor. Unfortunately it did not address the encoding related issue when it comes to the "Stage Selected Ranges" command. Fixing the "Stage Selected Ranges" command is currently blocked on https://github.com/microsoft/vscode/issues/824 as at the moment extensions do not have access to the encoding of the text document.

**Comment by gdh1995** [comment] 2022-04-06 11:01
I also run into this today. Why does this issue exist yet?

**Comment by ankostis** [comment] 2022-04-06 15:47
The viciousness of this bug is that the corrupted files manifest themselves very late in git history, when eg bisecting old commits and discovering differences in irrelevant  but huge ranges of text due to EOLs.
I've been bitten by this bug, and discovered it roughly after a year!

**Comment by ams-tschoening** [comment] 2022-05-08 19:31
Is `working-tree-encoding` of `.gitattributes` are workaround? Using that GIT is expected to store UTF-8 internally, while converting to some different encoding locally. In that case it might be OK if VSCode forwards UTF-8 at some point.

```
*			text=auto
*.bat		text eol=crlf	working-tree-encoding=cp850
*.c			text eol=crlf	working-tree-encoding=windows-1252
```

**Comment by Kiuchi** [comment] 2022-10-25 11:35
I tried to create an extension to add a "Stage Selected Range (ANSI)" command for ANSI to work around this problem, but it was not possible because the `registerDiffInformationCommand` is still in the proposed stage. (#84899)
We hope this will be corrected as soon as possible.

**Comment by Dub1shu** [comment] 2022-10-30 02:03
This issue requires an API for encoding, but the issue of adding this API(#824) has remained open for 6 years. Also, adding such a core API would be difficult for the average contributor.
Until the API is added, how about getting the encoding from the config and staging based on that encoding instead of the actual encoding?

**Comment by h8nor** [comment] 2023-07-28 15:05
It is true that GIT always stores files in UTF-8 encoding on a remote server.
With the setting in comments given a year ago the Github Desktop works fine. But the vscode doesn't use the setting when comparing commits. The solution was not very obvious.
https://code.visualstudio.com/updates/v1_48#_browser-support
https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/understanding-file-encoding#configuring-vs-code

**Comment by ams-tschoening** [comment] 2023-07-28 20:03
> It is true that GIT always stores files in UTF-8 encoding on a remote server.

Don't be misleading, that's not the case "always", but depends on settings in `.gitattributes`. Git itself is fine to store files in arbitrary encoding as-is, depends on various different settings of the client. Remember that it's able to store binary files as well.

**Comment by ErikSteiner** [comment] 2023-11-09 10:59
Is there an update to this issue? I also opened an issue on VSCodium's GitHub: https://github.com/VSCodium/vscodium/issues/1418

I have reproduced and documented the current problem in two examples. The difference between the two use cases is the use of a .gitattributes. The post has become a little longer than planned.

# Case 1

1. `mkdir .\test-repo`
2. `cd test-repo`
3. `git init`
4. `git config --local --list`
```
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
```
5. Create script.vbs with content
```
# Test file
Msg "Hello"
```
6. commit script.vbs in VSCode with Stage Changes
7. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "Änderungen"
```
8. commit script.vbs in VSCode with Stage Changes
9. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "Überlegung"
Msg "Änderungen"
```
10. commit script.vbs in VSCode with Stage Changes
11. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "ÄÖ first commit"
Msg "Überlegung"
Msg "ÜÖ later commit"
Msg "Änderungen"
```
10. in VSCode under Source Control highlight the row with `Msg "ÄÖ first commit"` and select "Stage selected Ranges".
11. Commit the Staged Change
12. After that:
- Source Control shows the following state:
![grafik](https://github.com/microsoft/vscode/assets/2684018/8fe1dd29-f061-492a-90ba-80482fddd38b)
- The explorer shows the following state (just ignore the file name). Note the lines marked in blue.:
![grafik](https://github.com/microsoft/vscode/assets/2684018/04ec546e-8d7d-4db1-9d3b-ca2e1c00ccdb)

# Case 2

1. `mkdir .\test-repo2`
2. `cd test-repo2`
3. `git init`
4. `git config --local --list`
```
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
```
5. Create script.vbs with content
```
# Test file
Msg "Hello"
```
6. Create .gitattributes with content
```
*			text=auto
*.vbs		text eol=crlf	working-tree-encoding=windows-1252
```
7. commit  .gitattributes in VSCode with Stage Changes
8. commit script.vbs in VSCode with Stage Changes
9. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "Änderungen"
```
10. commit script.vbs in VSCode with Stage Changes
11. from now on, the explorer shows a change in line three, even if Source Control shows no changes:
![grafik](https://github.com/microsoft/vscode/assets/2684018/ca6aad6f-9a2a-4b7d-96ff-091409ed15dc)

13. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "Überlegung"
Msg "Änderungen"
```
14. commit script.vbs in VSCode with Stage Changes
15. the explorer shows a change in line three, even if Source Control shows no changes. Interestingly the text shows "1 of 1 change":
![grafik](https://github.com/microsoft/vscode/assets/2684018/09f6600b-90b4-4ab5-b423-944568c04f61)
17. edit the script.vbs and add some umlauts
```
# Test file
Msg "Hello"
Msg "ÄÖ first commit"
Msg "Überlegung"
Msg "ÜÖ later commit"
Msg "Änderungen"
```
10. in VSCode under Source Control highlight the row with `Msg "ÄÖ first commit"` and select "Stage selected Ranges".
11. Commit the Staged Change
18. After that:
- Source Control shows the following state:
![grafik](https://github.com/microsoft/vscode/assets/2684018/3c4b5644-89f0-4c19-a0b2-0a086f2af971)
- The explorer shows the following state (just ignore the file name). Note the lines marked in blue.:
![grafik](https://github.com/microsoft/vscode/assets/2684018/9b053267-ab71-4430-9d31-870744900a28)

# Summary


settings.json
```
"files.autoGuessEncoding": false,
"[vbs]": {
        "files.encoding": "windows1252"
    }
```

**Comment by rasmussehlin** [comment] 2024-01-09 20:56
I had this problem today. Running version 1.85.1. Thought I'd make a comment to give this issue a kick, since this issue is three years old. :)

**Comment by michaelmesser** [comment] 2024-08-29 22:16
Can this bug be prioritized higher? Silently changing files is a significant bug. Many users are likely running into this bug without realizing it. If it breaks something later, they might not find the original cause.

**Comment by michaelmesser** [comment] 2024-12-07 22:52
Is there any update on this? I think it is very important for a text editor to not silently make unwanted changes to files.

**Closed** 2024-12-19 14:46 UTC
Labels: bug, help wanted, git

**Comment by lszomoru** [comment] 2024-12-19 14:54
Apologies for not getting back to you on this until now. Thanks @jekitf, and @Dub1shu for tracking down the root cause of this issue and for proposing a fix. I have pushed a changes for this issue today and it should be available in tomorrow's VS Code Insiders release. I would really appreciate if you could download that and verify that the fix is working as expected. Thanks!

**Comment by heartacker** [comment] 2024-12-19 22:24
really thanks

**Comment by ErikSteiner** [comment] 2024-12-20 05:56
Wuhuu, finally!

**Comment by JuanRaVa** [comment] 2025-01-21 13:26
Hi @lszomoru 

I'm testing today to see if the issue was solved but I face with the problem. Look at picture below some characters on my file are change. This happens only if you use "Stage Selected Range". 

Version use: 
- Vsc 1.96.4

Encoding use: Windows 1252

![Image](https://github.com/user-attachments/assets/8bf7a50a-942a-4716-a140-a2ad9f7fe1b6)

**Comment by emonnot** [comment] 2025-01-21 13:36
Tested with version 1.97.0-insider, the issue seems to be resolved. Thanks, @lszomoru !

**Comment by lszomoru** [comment] 2025-01-21 15:05
@JuanRaVa, please test using `1.97.0-insider` as that is the only one that currently contains the fix.

**Comment by JuanRaVa** [comment] 2025-01-27 22:54
@lszomoru thank you for clarifying it, I was tested in this insider version and works well. Thank you so much
