### ISSUE TITLE
Clear Terminal while using PowerShell 7 doesn't move cursor

### ISSUE THREAD

**Issue by jonvanausdeln** [microsoft/vscode#202630] opened 2024-01-17 01:55 UTC
Type: <b>Bug</b>

Repro Steps:
1. Start Terminal, Powershell 7.4
2. Type some commands, e.g. echo "test"
3. Select "Clear Terminal"
4. Type a command

Expected:
Command to be typed at top of screen where prompt shows

Actual Result:
Command is shown on the screen where the cursor was before "Clear Terminal"

<img width="276" alt="image" src="https://github.com/microsoft/vscode/assets/6433789/45263f0b-f164-43e2-810d-785a73ec5455">

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.45GB free)|
|Process Argv|--crash-reporter-id aa465fa2-0b05-4474-9e09-d12877c65f1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-pull-request-github|Git|0.78.1
vscode-docker|ms-|1.28.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
java|red|1.26.0
vscodeintellicode|Vis|1.2.30
vscode-maven|vsc|0.43.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
vsjup518:30340749
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2cf:30926736
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t:30925682

```

</details>

**Comment by meganrogge** [comment] 2024-01-17 03:43
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-01-17 03:43 UTC
