### ISSUE TITLE
No textDocument/references LSP message is sent to extensions when references-view.find is not used on an identifier

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#77617] opened 2019-07-19 03:13 UTC
- VSCode Version: 1.36.1
- OS Version: Windows (others)

Bug: Our C/C++ extension needs to do vscode.commands.executeCommand("references-view.find") in order to re-send reference results after we have already sent our "preview" references from the initial textDocument/references, but VS Code is early aborting the references-view.find if the cursor is not on an identifier (otherwise it works). This breaks out ability to stream/preview references results back to users, which is bad because the final result could take many minutes, but the preview results may be usable and sufficient.

However, I believe we can workaround this via repeatedly trying the command until the users move their cursor on an identifier and updating our progress message to tell users they need to move their cursor to an identifier get the final references results -- it's just a strange thing to have to inform users about.

UPDATE: I got it working – the experience seems acceptable – in the somewhat unusual case where the user moves their cursor to an invalid Find All References location (i.e. not an identifier) then the progress message appends “Move your cursor to any identifier to get results”.

**Comment by bobbrow** [comment] 2019-07-19 16:20
Ideally, we could use [this](https://github.com/microsoft/language-server-protocol/issues/786) for Find all References so we can get partial results streaming without this hack.

(Adding @dbaeumer to the discussion)

**Comment by dbaeumer** [comment] 2019-08-05 13:26
@jrieken assigning to you since this is not under the LSP control. We only send a server request if the reference provider is called in the VS Code extension API.

**Comment by jrieken** [comment] 2019-08-05 13:33
/duplicate of https://github.com/microsoft/vscode/issues/20010

**Closed** 2019-08-05 13:33 UTC
Labels: *duplicate

**Comment by sean-mcmanus** [comment] 2019-08-06 21:57
Yeah, this won't be an issue any more after proper streaming is enabled, but I still think this is a VS Code bug with "references-view.find" -- it doesn't repro with Peek References, i.e. editor.action.referenceSearch.trigger.

**Comment by jrieken** [comment] 2019-08-07 07:55
> but I still think this is a VS Code bug with "references-view.find" 

Disagree - I think its fair not to try search for references when the cursor is on whitespace. Anyways, while we are the land of hacks and workaround. Why aren't you using the `references-view.refresh`-command to update/refetch the result list?

**Comment by sean-mcmanus** [comment] 2019-08-07 19:05
Thanks a lot -- that fixed the issue. I thought I had already tried that and it didn't work, but I was mistaken.

**Comment by sean-mcmanus** [comment] 2019-08-08 01:43
Is there a way to refresh with Peek (editor.action.referenceSearch.trigger) or should I file a feature request for that? When we do that without moving the cursor it causes the Peek UI to disappear if it's visible, so we can't reliably refresh it (and the position moves) -- our workaround is to disable the "preview" ability for Peek References.

**Comment by jrieken** [comment] 2019-08-08 07:25
> Is there a way to refresh with Peek (editor.action.referenceSearch.trigger) or should I file a feature request for that? 

No and please don't invest energy in workarounds when #20010 is what you need.

**Comment by bobbrow** [comment] 2019-08-08 15:55
It looks like #20010 is closed.  Is there another issue we should be tracking?

**Comment by jrieken** [comment] 2019-08-08 17:01
We closed this last year as 'out-of-scope' because it was on our 6-12 months roadmap. The issue can be commented on, and if we agree that's what we need can be re-opened.
