### ISSUE TITLE
version `GLIBC_2.25' not found in centos 7 for vscode server

### ISSUE THREAD

**Issue by GMHDBJD** [microsoft/vscode#155474] opened 2022-07-18 09:34 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: centos7

Steps to Reproduce:

1. install vscode-server https://code.visualstudio.com/docs/remote/vscode-server#_quick-start
2. run code-server
```
/usr/local/bin/code-server: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/code-server)
/usr/local/bin/code-server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/code-server)
```

**Comment by GMHDBJD** [comment] 2022-07-18 16:25
```
[root@test ~]# node --version
v16.16.0
```

**Comment by GMHDBJD** [comment] 2022-07-19 06:06
Maybe related to https://github.com/microsoft/vscode/issues/146390

**Comment by Suliang1027** [comment] 2022-08-02 07:09
same problem. CentOS 7, node version 16.13.2

**Comment by rzhao271** [comment] 2022-12-09 18:48
The UX changed recently, and now there's a [code cli](https://code.visualstudio.com/docs/remote/vscode-server#_getting-started) instead. Does this issue still occur with the new program?

**Comment by deepak1556** [comment] 2022-12-10 02:37
@rzhao271 the underlying server executable has not changed, we should test the steps from https://github.com/microsoft/vscode/issues/155474#issue-1307662878 on CentOS 7

**Comment by rzhao271** [comment] 2022-12-13 20:57
I confirmed that one can still get to the server executable by running `./code tunnel`.
I'm still unable to repro the issue, though.

**Comment by tfcace** [comment] 2023-01-18 15:47
I'm also getting this on Debian 11

**Comment by rzhao271** [comment] 2023-01-18 18:05
@tfcace could you share repro steps? For example, did you just run `./code tunnel` with Code CLI, or were there other steps involved?

**Comment by tfcace** [comment] 2023-01-18 19:57
yes. I'm using Debian 11.6 installed on a VM.
VSCode was installed through the snap package.

This is the input of my terminal session:
```bash
code tunnel
/snap/code/117/usr/share/code/bin/code-tunnel: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /snap/code/117/usr/share/code/bin/code-tunnel)
/snap/code/117/usr/share/code/bin/code-tunnel: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /snap/code/117/usr/share/code/bin/code-tunnel)
```

When running `code --version`, this is the output:
```
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64
```

If there's anything else I can provide, let me know.

**Comment by deepak1556** [comment] 2023-01-18 23:34
@tfcace the issue you are facing is tracked in https://github.com/microsoft/vscode/issues/168427, please follow that issue for updates tl:dr; code-tunnel from the snap package will not work due to our build version. Please use the cli from deb package, thanks!

**Comment by tfcace** [comment] 2023-01-19 11:32
thank you!

**Comment by deepak1556** [comment] 2023-12-15 16:55
Closing as server requirements will be bumped to `GLIBC >= 2.28` in upcoming releases following https://github.com/microsoft/vscode/pull/192513

**Closed by deepak1556** 2023-12-15 16:55 UTC
Labels: bug, linux, confirmation-pending
