### ISSUE TITLE
Extension-development-host is not terminating when closing debug session from main process.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6445] opened 2016-05-17 22:21 UTC
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
 1. Launch an app.
 2. Follow the instructions to create and debug extension.
https://code.visualstudio.com/docs/extensions/example-word-count
3. Start debugging with F5 and verify new instance of VSCode launched or not.
4. From the main window (where debug options are available) perform search from action-bar and click on close debug button from debug-actions widget.

**Actual**: When user terminate the debug session after search operation then child window (Extension-development-host) is not closing.

**Expected**: Whenever user close the debug session then all the child processes and threads associated with that should be terminated.
I tried to perform below operations without search action and Child process is terminating properly.
1. Close debug session from main process and verify app behavior (new instance of VSCode closed when ending debug session).
2. Try to perform in either way, Close newly launched VSCode instance and verify app behavior (Debug session terminated)

![extensiondev-hostclosingissue](https://cloud.githubusercontent.com/assets/17735796/15341272/8d28186e-1c42-11e6-8d96-1620819d4fc1.gif)

**Comment by weinand** [comment] 2016-07-06 13:29
duplicate of Microsoft/vscode#6572

**Closed by weinand** 2016-07-06 13:29 UTC
Labels: bug, debug, v-test
