### ISSUE TITLE
Code Helper thread burning CPU

### ISSUE THREAD

**Issue by sinadino** [microsoft/vscode#98660] opened 2020-05-27 15:37 UTC
Issue Type: <b>Bug</b>

Hi, I know this is a long shot but I am having an issue with VS Code and the latest Catalina. I noticed my mac has been overheating lately so I went looking at my Activity Monitor and spotted two potential causes. One was Chrome (resolved) and the other was VisualStudio Code, they both were burning CPU. I already tried disabling and uninstalling VS Code and plug ins but I can’t get Code Helper to stop burning CPU. Thanks in advance. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

![image](https://user-images.githubusercontent.com/4544708/83041364-3f897b80-9ff5-11ea-8b1f-25afc50d1fea.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by egamma** [comment] 2020-05-27 20:24
/needsMoreInfo please follow this guide to help us narrow down performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by namaggarwal** [comment] 2020-05-28 15:30
It happened with my flatmates laptop today. 

This issue has been reported so many times and every time its closed without any resolution. Its hard to reproduce because it doesn't happen very often.

Can we not start by looking why "Code Helper" process is still running even after closing VSCode.

**Comment by egamma** [comment] 2020-06-09 19:11
@namaggarwal the CodeHelper process runs VS Code extensions and most of the time the slowness is caused by an extension, this is not an issue with the CodeHelper process. To narrow such issues down we have created this guide https://github.com/microsoft/vscode/wiki/Performance-Issues.

**Comment by namaggarwal** [comment] 2020-06-10 03:45
Thanks @egamma. I understand. I will got through the link and try to figure out the root cause.

**Comment by egamma** [comment] 2020-06-17 18:50
@namaggarwal thank you looking forward for the additional info.

**Closed** 2020-06-25 11:23 UTC
Labels: needs more info
