### ISSUE TITLE
option to amend a commit in the scm commit button.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#187239] opened 2023-07-07 06:58 UTC
Type: <b>Feature Request</b>

it would be nice to have the `amend` option in the `commit` button/dropdown in the scm view instead of the source control pane.

![image](https://github.com/microsoft/vscode/assets/9264813/4be2b342-598b-4e9e-b819-ea3d6c267bb9)

VS Code version: Code - Insiders 1.81.0-insider (79ec05cb73486ad2d57a57a5f138b094d21c8644, 2023-07-06T23:18:22.645Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by lszomoru** [comment] 2023-07-11 12:10
Closing as duplicate of https://github.com/microsoft/vscode/issues/180419

**Closed by lszomoru** 2023-07-11 12:10 UTC
