### ISSUE TITLE
consider adding possibility to check/uncheck or labelizing files

### ISSUE THREAD

**Issue by AimSai59** [microsoft/vscode#115488] opened 2021-01-31 06:12 UTC
When we have a large amount of files to review or correct, it is extremely difficult to find our way into the sidebar.
It would be interesting to be able to simply check a box or apply a color (a label) to the name of the file whose proofreading or correction is finished. 
A label seems more flexible to adapt to the majority of cases. Something like this.
![Capture d’écran 2021-01-31 à 07 10 39](https://user-images.githubusercontent.com/57364580/106376223-7a695d80-6393-11eb-80ca-8d7ee9b58ec5.png)

**Comment by gjsjohnmurray** [comment] 2021-01-31 07:23
Sounds like something an extension could do using  [FileDecorationProvider](https://code.visualstudio.com/api/references/vscode-api#FileDecorationProvider) API that arrived in 1.52

**Comment by isidorn** [comment] 2021-02-01 10:34
Also there are other issues that ask for coloring of items in the Explorer. Thus closing as extension-candidate and duplicate of those issues

**Closed by isidorn** 2021-02-01 10:34 UTC
Labels: *extension-candidate
