### ISSUE TITLE
Can't select an arabic text in the editor

### ISSUE THREAD

**Issue by Nabeel20** [microsoft/vscode#92758] opened 2020-03-16 06:33 UTC
Issue Type: <b>Bug</b>

When I tried to select an Arabic text I can't. 
this happened after the last update.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-4300M APU with Radeon(tm) HD Graphics    (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.45GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-close-tag|for|0.5.6
vetur|oct|0.24.0
LiveServer|rit|5.6.1
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-03-16 15:45
Duplicate of #92373

**Closed by alexdima** 2020-03-16 15:45 UTC
