### ISSUE TITLE
VS code keeps using older version of typescript

### ISSUE THREAD

**Issue by Bokac30** [Microsoft/vscode#9623] opened 2016-07-22 12:40 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

I have changed the PATH to use 1.8 but no luck.

Steps to Reproduce:
1. this is my tasks.json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-v"],
    "showOutput": "always",
    "problemMatcher": "$tsc"
}
2. Run build ctrl+shift +b
output is:
Version 1.0.3.0

**Comment by dbaeumer** [comment] 2016-08-04 13:23
I think you once installed tsc in VS which installs a executable different than the npm module. You can verify with a cmd prompt and where tsc.

**Comment by dbaeumer** [comment] 2016-11-15 19:23
Closing since no additional information has been provided and I am not able to reproduce the issue.

**Closed by dbaeumer** 2016-11-15 19:23 UTC
Labels: needs more info, not-reproducible, tasks, typescript
