### ISSUE TITLE
VsCode Snap crashing on Manjaro 20.1 XFCE when you try to save or open some native menu!

### ISSUE THREAD

**Issue by spirulin** [microsoft/vscode#106797] opened 2020-09-15 20:05 UTC
- VSCode Version: Latest on date 15.09.2020 (Sorry now on Windows because I need a working editor!)
 - OS Version: Manjaro XFCE 20.1

Steps to Reproduce:

1. Open VScode
2. New file - Save as - CRASH!

Does this issue occur when all extensions are disabled?: Yes

Extra info:

This fixed it for me:

sudo mkdir /usr/lib/x86_64-linux-gnu/
sudo ln -s /usr/lib/gdk-pixbuf-2.0 /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0

What the Snap team at MS is doing? This thing has been a problem since forever. Would be nice if someone finally fixes it.

**Comment by IllusionMH** [comment] 2020-09-15 22:13
/duplicate of #100940 (but you already commented there)

That issue is in September milestone so hopefully fixed soon.

**Closed** 2020-09-15 22:14 UTC
Labels: *duplicate
