### ISSUE TITLE
Fonts appear too thin (Windows) 

### ISSUE THREAD

**Issue by Mikhail22** [microsoft/vscode#108487] opened 2020-10-11 14:39 UTC
- VSCode Version: 1.50.0
- OS Version: Windows_NT x64 10.0.18363

Issue description:

Fonts appear too thin in VSCode. This creates a major problem because 
of poor reading experience. Please pay attention to this issue, because 
font rendering is the key element of the editor.

For example let's compare with the Times New Roman font (16pt).

VSCode:  

![times_vscode](https://user-images.githubusercontent.com/12515548/95681177-199cf600-0be7-11eb-8054-a1b37604f055.png)

Windows native cleartype rendering (Notepad++):  

![times_cleartype](https://user-images.githubusercontent.com/12515548/95681184-26b9e500-0be7-11eb-9d94-7676082086b7.png)

Arial font, 15pt:
VSCode:

![arial_vscode](https://user-images.githubusercontent.com/12515548/95720207-9b3d6400-0c79-11eb-8de6-4ef433cf7b2f.png)

Notepad++:

![arial_cleartype](https://user-images.githubusercontent.com/12515548/95720233-a55f6280-0c79-11eb-8d79-398544505011.png)

Currently I can't find any solution for this. The only workaround is to use bolder 
fonts, but this is not really a solution to the problem. Fonts need to be rendered 
precisely as they are designed for best contrast and readability, and ideally this 
should be configurable. Software that uses Cleartype has contrast setup possibilty, 
but VSCode does not have any option to configure the contrast or anything 
related to this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by thunder-coding** [comment] 2020-10-12 05:29
You can change the font weight in Settings

- Open settings by pressing Ctrl + ,
- Search for Font Weight
- Get the font weight you need.

Hope this helps, if so, please close this issue

**Comment by Mikhail22** [comment] 2020-10-12 06:53
> 
> 
> You can change the font weight in Settings
> 
>     * Open settings by pressing Ctrl + ,
> 
>     * Search for Font Weight
> 
>     * Get the font weight you need.
> 

This setting merely relates to variable fonts, otherwise it just picks bold, semibold, etc. if it's present in the system so your advise does not even relate to the issue I describe. And Times New Roman (on the screenshot) is not a variable font.

**Comment by deepak1556** [comment] 2020-10-12 19:27
Can you update to latest stable `1.50` and check if the issue is still present.

**Comment by Mikhail22** [comment] 2020-10-13 00:46
> Can you update to latest stable `1.50` and check if the issue is still present.

Updated to 1.50.0, the issue still present.

**Comment by deepak1556** [comment] 2020-10-13 01:55
can you check if launching code with `--force-device-scale-factor=1` is better ?

**Comment by Mikhail22** [comment] 2020-10-13 02:30
> can you check if launching code with `--force-device-scale-factor=1` is better ?

Tried, and no, this did not not change the font appearance at all.

**Comment by thunder-coding** [comment] 2020-10-13 02:54
Try using other font

Must be of variable type

**Closed** 2021-01-08 11:50 UTC
Labels: font-rendering, needs more info, windows
