### ISSUE TITLE
[html] wrong autocomplete HTML end tag

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#24322] opened 2017-04-08 17:33 UTC
- VSCode Version: 1.11.1
- OS Version: ALL

Steps to Reproduce:

[Video](https://www.youtube.com/watch?v=Xfmt26UQJB8&ab_channel=GabrielMlocik)

**Comment by aeschli** [comment] 2017-04-10 08:50
Thanks @Mlocik97. If you can paste your html sample that shows the problem that would be great!

**Comment by Mlocik97** [comment] 2017-04-10 13:01
every html file... when <tag> text </tag> text2 is in one line, and </tag> write later than text2 so - write only `<` and press tab. It complete as `<tag> text </text2> text2`


[Untitled-1.zip](https://github.com/Microsoft/vscode/files/910095/Untitled-1.zip)

**Comment by aeschli** [comment] 2017-04-12 08:37
duplicate of #22028

**Closed by aeschli** 2017-04-12 08:37 UTC
Labels: bug, html
