### ISSUE TITLE
Add a command line option to start vscode with the integrated terminal open

### ISSUE THREAD

**Issue by maeriens** [microsoft/vscode#93826] opened 2020-03-31 06:30 UTC
Currently, I am able to start VSCode from the terminal by running `code <path>`, and I know if I want to reuse the same window I have open, I can also add the `-r` flag. 

My issue is that, when I do this from the integrated terminal, it closes and I have to reopen it manually. And same thing when I access from the OS's terminal; I usually have the server running in an external terminal but have the integrated one open for tests and other checks.

 Having a flag like `-t`, which would automatically open the terminal, would be a small improvement that would help a lot.

**Comment by Tyriar** [comment] 2020-04-05 04:42
Currently we try to avoid workbench-related features in the CLI. If we chose to make the terminal launchable by itself then it would probably gets this so closing a duplicate of https://github.com/microsoft/vscode/issues/34442

**Closed by Tyriar** 2020-04-05 04:42 UTC
