### ISSUE TITLE
Select Default Profile do not actually open gitbash. After relaunch, on startup, it just keeps open PowerShell

### ISSUE THREAD

**Issue by elgerus** [microsoft/vscode#133066] opened 2021-09-14 08:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

Issue Type: Bug

OS: Windows 10
1. Download/Install VScode
2. Open integrated terminal (PowerShell) - ctrl+`
3. Add new Terminal: Git Bash
4. Select Git Bash Terminal
5. Select Default Profile: Git Bash
6. Go back to powershell - kill/destroy it.
7. Let terminal (git bash) open
8. (do not close terminal) close VS code
9. Relaunch VS code
It should launch with gitbash terminal. Instead it opens PowerShell. If we add new terminal then it opens gitbash

Version: 1.60.0 
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment] 2021-09-14 08:07
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-14 08:08 UTC
Labels: *duplicate
