### ISSUE TITLE
Integrated terminal doesn't draw properly on open

### ISSUE THREAD

**Issue by eparizzi** [microsoft/vscode#75123] opened 2019-06-08 10:57 UTC
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open a new integrated terminal (cmd). This is how it looks:
![image](https://user-images.githubusercontent.com/412489/59145992-ccee4d00-89eb-11e9-900e-2430129be218.png)
2. Type `cd` in it. It now looks like this. Can't see the current directory. I have to enter a command in order for it to appear. 
![image](https://user-images.githubusercontent.com/412489/59146000-e68f9480-89eb-11e9-838a-994e88837b45.png)

Now the same thing with Powershell.
1. New terminal, It seems to autoscroll to the bottom.
![image](https://user-images.githubusercontent.com/412489/59146035-733a5280-89ec-11e9-8d21-420feceb34b3.png)
2. Scroll the terminal to the top. I can see the init message, but again, no current working directory (until I send a command and now I see the current directory).
![image](https://user-images.githubusercontent.com/412489/59146039-7af9f700-89ec-11e9-9e71-daf767a0e00c.png)

This seems to happen when the integrated terminal area is not tall enough. See what happen when I open a new one with enough height. It looks like as expected.
![image](https://user-images.githubusercontent.com/412489/59146193-d4fabc80-89ec-11e9-9ecb-af84588c4ad7.png)
![image](https://user-images.githubusercontent.com/412489/59146242-e04de800-89ec-11e9-9ea7-0dad8e742311.png)

Git Bash doesn't seem to be affected by this issue:
![image](https://user-images.githubusercontent.com/412489/59146355-60744d80-89ed-11e9-8166-5e1a8456c92c.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes and with default settings.

**Comment by usernamehw** [comment] 2019-06-08 11:08
Duplicate of #57803. The only fix is to update Windows to 1903, which should be available now.

**Closed** 2019-06-08 17:44 UTC
Labels: integrated-terminal
