### ISSUE TITLE
Support searching through the extensions contributions

### ISSUE THREAD

**Issue by HardikModha** [Microsoft/vscode#65803] opened 2018-12-29 08:00 UTC
Currently, I cannot perform a text search on the extension ~detail~ contributions tab content. Pressing CMD+F (On Mac) doesn't work. (Tested with all extensions disabled) (👇 contributions tab screenshot)

![screen shot 2018-12-29 at 2 36 44 pm](https://user-images.githubusercontent.com/22439276/50536133-3d5c8c80-0b77-11e9-956d-6e41acc318a4.png)

IMO, This should be supported. This searching is very useful if I want to search for a particular configuration or any specific detail quickly. Right now, I have to go to the extension GitHub repo or npmjs to search through the docs.

**Comment by roblourens** [comment] 2018-12-30 19:57
You can search the settings in the settings editor, but I agree that this page could be more powerful.

**Comment by sandy081** [comment] 2019-01-03 14:41
Duplicate of https://github.com/Microsoft/vscode/issues/56163

**Closed** 2019-01-03 14:41 UTC
Labels: *duplicate, extensions
