### ISSUE TITLE
Improve File Association feature (status bar)

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#4532] opened 2016-03-22 00:08 UTC
I like this new feature... I have some suggested improvements. Open to discussion of course :) 

Let's take a simple use case. I have a file `.babelrc`. This file is a JSON file. VS Code detects it as Plain Text. I click in the bottom right to change it to `JSON`. I see that there are two options "Auto Detect" and "Configure file association for .babelrc". 

I try "Auto Detect". The file is still Plain Text. (1) I would expect Auto Detect to intelligently figure out I am using JSON. 

I try "Configure file association for .babelrc." I am taken to settings.json. A popup explains that I may need to restart. I don't see any instructions nor do I know where to look. (2) I am not sure how to proceed. 

I try setting `.babelrc` to JSON. This works as expected. I close the file and come back to it. Its back to Plain Text. (3) I would have expected it to stay JSON. 

Couple of ideas. For (1) can we intelligently figure out what the file is? We could start with a JSON file or other common configuration files. Also, what is "Auto Detect" supposed to do? It seems like we're already auto detecting every single file. We could consider dropping it. 

(2) We should provide some prompt for settings. Even a navigation and highlighting of the settings command that needs to be configured would be helpful. This could be similar to what @alexandrudima did for keybindings. As it stands, I need to know to trigger suggest to know what to type. This isn't obvious, especially for new users. 

(3) What if VS Code saved a file's association automatically. For example if I set .babelrc to JSON, I would expect there to be an association and never have to do it again (at least for the workspace I am in). 

Just some thoughts.

// @chrisdias

**Comment by bpasero** [comment] 2016-03-22 06:01
(1) auto detect is just doing what the editor does by checking for the file extension and taking whatever is configured. since this is in no way a smart feature I am fine to remove it

(2) I think (3) would solve this

(3) we are currently not able to write to the settings file because the file is user edited and may contain comments, but I agree this would be nice

**Comment by bpasero** [comment] 2016-09-17 05:55
Lets make this a duplicate of https://github.com/Microsoft/vscode/issues/11974

If you have more feedback on https://github.com/Microsoft/vscode/issues/11974, add it there 👍

**Closed by bpasero** 2016-09-17 05:55 UTC
Labels: explorer-files, feature-request

**Comment by waderyan** [comment] 2016-09-20 17:09
Cool thanks @bpasero
