### ISSUE TITLE
feature-request: Sync my extensions between to systems (Mac <--> Windows)

### ISSUE THREAD

**Issue by rish7** [Microsoft/vscode#33194] opened 2017-08-26 17:47 UTC
Hi,

I am using Mac and Windows at Work/Home. I have VS code in both. 
If we have a feature to sync all extensions between both systems. That will be very good. 

Something like Visual Studio theme sync. 

And give the option to install button in the Web site to push extensions to all systems, the user logged in. (Like Android/WP store)

Thank you,
Naga Harish.

**Comment by vnbrs** [comment] 2017-08-26 18:33
That'd be great.

Maybe if we could log in inside VS Code with a MS account, just like it's done in VS, keeping all the stuff synchronized.

**Comment by Tyriar** [comment] 2017-08-27 15:28
Duplicate of https://github.com/Microsoft/vscode/issues/2743

In the meantime, this extension is the typical way of doing this https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Closed by Tyriar** 2017-08-27 15:28 UTC
Labels: extensions
