### ISSUE TITLE
Debug Console not updating. Error thrown in Developer Tools

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#115798] opened 2021-02-04 21:53 UTC
Issue Type: <b>Bug</b>

1. Startup .Net Core Web App
2. Startup Chrome 
3. Open Integrated Terminal and Tab to Debug Console 
4. Observe old output and unable to clear

Open Developer Toos
1. Observe errors
Error: TreeError [DebugRepl] Tree element not found: [object Object] 

<details>
<summary>Stack error from Developer Tools Console
</summary>
ERR TreeError [CallStackView] Data tree node not found: [object Object]: Error: TreeError [CallStackView] Data tree node not found: [object Object]
    at G.getDataNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:19676)
    at G.rerender (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:17325)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1929:21339
    at u.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at O.setName (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1891:40468)
    at C.$setDebugSessionName (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1558:7618)
    at h._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:9678)
    at h._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:9370)
    at h._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:8040)
    at h._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:6842)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:4970
    at u.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at o.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21379)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18273
    at u.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at Socket.I (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2653:112473)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
</details>

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.17GB free)|
|Process Argv|--crash-reporter-id 161e5da9-f592-4143-baa2-0a9d01a1bfab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
quick-html-previewer|dai|1.0.1
vscode-dotnet-auto-attach|Den|1.1.1
githistory|don|0.6.14
redis|Dun|0.8.4
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|5.9.0
vscode-firefox-debug|fir|2.9.1
text-transform|flo|0.1.0
code-runner|for|0.11.2
docker-explorer|for|0.1.7
openssl-configuration-file|gee|0.0.1
beautify|Hoo|1.5.0
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.5
intellij-idea-keybindings|k--|1.3.0
dotnet-core-essentials|Kis|0.0.8
vscode-github|Kni|0.30.4
csharpfixformat|Leo|0.0.84
git-graph|mhu|1.28.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
mssql|ms-|1.10.1
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.2.0
js-debug-nightly|ms-|2021.2.117
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vetur|oct|0.32.0
vsnotes|pat|0.7.1
material-icon-theme|PKi|4.5.0
toggle|reb|0.0.1
java|red|0.74.0
vscode-yaml|red|0.14.0
vs-code-prettier-eslint|rve|0.4.1
preview-vscode|sea|2.2.5
msbuild-project-tools|tin|0.3.11
vscode-workspace-explorer|tom|1.5.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
gitblame|wad|6.0.2
material-theme|zhu|3.9.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by dfdumaresq** [comment] 2021-02-04 21:57
Urgent as I'm unable to work with this. 
I believe this is a result of the VSCode update today. How to rollback to previous version?

**Comment by jpike88** [comment] 2021-02-05 06:44
Same problem, HELP!!!!

**Comment by NormandoHall** [comment] 2021-02-05 07:01
Same here but for two extension not run anymore. How to rollback?

**Comment by isidorn** [comment] 2021-02-05 08:28
Thanks for filling this issue. I can not reproduce this.
The error which you pasted is not related to the Debug Console, so that is not the root cause.

Can somebody here provide exect reproduable steps?
Does somebody see this with a simple JavaScript app or everybody sees this only with .net core apps?

Thanks!

**Comment by dfdumaresq** [comment] 2021-02-05 16:41
@NormandoHall, to rollback: 
https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode
Then prevent VSCode from updating on restart:
- open Settings and set Update:Mode to none

**Comment by Skuriles** [comment] 2021-02-09 07:26
I have the same issue with an angular 8 app. 
Start npm task, press F5 to run app in chrome.  Thank it runs for a few minutes, then it stops working.
Last entry is always: "Uncaught null". 
Console is not reacting anymore. No updates, no clear functionality.
I will try to reproduce it.

**Comment by Skuriles** [comment] 2021-02-09 07:49
So - I found it, or at least I could reproduce it and can add a console log of the VS Code dev tools. Console is frozen, but I couldn't specify a special process/action to cause the crash. Sometimes it works for 30 minutes, sometimes only 1. 

Dev log:

` ERR TreeError [DebugRepl] Tree element not found: [object Object]: Error: TreeError [DebugRepl] Tree element not found: [object Object]
    at D.getElementLocation (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:56:58107)
    at D.isCollapsed (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:56:57244)
    at b.isCollapsed (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:676)
    at q.setChildren (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:21534)
    at q.doRefreshNode (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20666)
    at async q.doRefreshSubTree (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20229)
    at async Promise.all (index 0)
    at async q.doRefreshSubTree (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:20272)
    at async q.refreshAndRenderNode (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:19781)
    at async q._updateChildren (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:17022)
    at async q.updateChildren (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:163:16688)
    at async I.runner (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1950:3217)`

**Comment by isidorn** [comment] 2021-02-09 17:29
Maybe a duplicate of https://github.com/microsoft/vscode/issues/116043
But I doubt it
fyi @connor4312

**Comment by connor4312** [comment] 2021-02-09 17:30
Doesn't look like it's calling through the "smart slice" method. I've also seen this _sometimes_ before but never had a repro and I didn't see(/notice) freezes

**Comment by isidorn** [comment] 2021-02-12 17:48
Assigning to backlog. Would be good to get some repro steps from the community since I can not reproduce this.

**Comment by dfdumaresq** [comment] 2021-03-02 18:20
This is still happening for me in 1.53.2.
Steps to reproduce might include 
- Start debugging a CS, ReactJS application with Typescript
- Put break point in the client code and run with Chrome.
- Hit the break point and restarted the client from the Debug UI in VSCode
![image](https://user-images.githubusercontent.com/20051/109695117-68204200-7b40-11eb-90cb-510f2a6fb544.png)
- Observe breakpoint becomes disabled
![image](https://user-images.githubusercontent.com/20051/109695256-88500100-7b40-11eb-98f8-fc8260e21084.png)
- Observe the debug console has frozen and cannot be cleared
![image](https://user-images.githubusercontent.com/20051/109695356-a74e9300-7b40-11eb-91e3-687b73943e2c.png)
- Open Developer Tools and observe 'potential listener leak' and TreeError.
![Uploading image.png…]()

**Comment by dfdumaresq** [comment] 2021-03-02 18:40
Reporting two other Developer Tools errors that may be related
![image](https://user-images.githubusercontent.com/20051/109697845-95222400-7b43-11eb-8966-b5bbf512dd64.png)

**Comment by dfdumaresq** [comment] 2021-03-02 18:43
Also noticing js-debug-nightly errors related to breakpoints on startup - after crashes above.
![image](https://user-images.githubusercontent.com/20051/109698242-111c6c00-7b44-11eb-9ea0-ac8a0243329f.png)

**Comment by dfdumaresq** [comment] 2021-03-02 18:53
Note: I'm not having this issue with Firefox.

**Comment by dfdumaresq** [comment] 2021-03-03 20:59
I can't get the same functionality with breakpoints that I can with Chrome, so I'm having to revert VSCode to November/2020 Release (1.52.2).

**Comment by fnicastri** [comment] 2021-04-28 16:25
having the same issue with react-native since months.
Any news?

**Comment by connor4312** [comment] 2021-04-29 15:54
@fnicastri please open an issue on https://github.com/microsoft/vscode-react-native. I do not maintain the RN tools.

**Comment by fnicastri** [comment] 2021-04-30 06:04
> @fnicastri please open an issue on https://github.com/microsoft/vscode-react-native. I do not maintain the RN tools.

I'll do. Thanks.
But I think it's related to Code, switching to an old version (1.50.1) ended every issue.
Debugger is running since yesterday without a single problem.

**Closed** 2021-05-04 18:15 UTC
Labels: *out-of-scope, debug, needs more info

**Comment by dfdumaresq** [comment] 2021-05-06 18:58
@fnicastri, I've forgotten exactly what I did to get myself out of this hell. I believe I cleared the preview debugger in settings. I'm now back to using Chrome in the latest vscode release. Good luck!
