### ISSUE TITLE
Method tooltips truncated on really long signatures

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2728] opened 2016-02-05 04:18 UTC
Using 0.10.7-insider on Windows 8.1

Hovering over methods that have really long signatures seems to produce a truncated tooltip (see attached image)

![vscode_truncated_tooltip](https://cloud.githubusercontent.com/assets/563860/12837925/7c1dfa92-cc1b-11e5-9d5a-bfe9d16fdac9.png)

Not sure if problem is language specific, but if required the screenshot is from some TypeScript code.

**Comment by egamma** [comment] 2016-02-05 07:37
duplicate of #2673

**Closed by egamma** 2016-02-05 07:37 UTC
