### ISSUE TITLE
Unable to use Unicode category regex to match non-Western digits

### ISSUE THREAD

**Issue by msoutopico** [microsoft/vscode#74400] opened 2019-05-27 10:47 UTC
- Version: 1.34.0 (user setup)
- Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
- Date: 2019-05-15T21:59:37.030Z
- Electron: 3.1.8
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

### Description

Unable to use Unicode category regex to match non-Western digits, in particular \pN

### Steps to reproduce

1. Type some Western and non-Western digits in a new file, e,g. 9598١٢٣٤٥٦
2. Search for \d
3. Search for \pN or \p{N} to find any number

### Expected behavior

Step 2 matches Western numbers but not for non-Western numbers.
Step 3 matches any number 

### Actual behavior

Step 2 matches Western numbers but not for non-Western numbers.
Step 3 matches nothing

### Observations

When searching in all open files in the VSCode window (Ctrl+Shift+F), \pN seems to match Western digits. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2019-07-02 18:55
This is technically a duplicate of https://github.com/microsoft/vscode/issues/61746

**Closed by roblourens** 2019-07-02 18:55 UTC
Labels: feature-request, search
