### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

### ISSUE THREAD

**Issue by nlarusstone** [microsoft/vscode#183143] opened 2023-05-22 18:24 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230502

**Steps to reproduce crash**

Not sure, was just editing code in a `tsx` file when this crashed.

**TS Server Log**

❗️ Server logging disabled.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
    at getDocumentRegistryEntry (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:132962:11)
    at Object.releaseDocumentWithKey (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133059:19)
    at getOrCreateSourceFileByPath (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141737:30)
    at Object.getOrCreateSourceFile (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141721:14)
    at /private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141653:42
    at Object.getSourceFileWithCache [as getSourceFile] (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117827:24)
    at findSourceFileWorker (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120195:23)
    at findSourceFile (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at /private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120064:22
    at getSourceFileFromReferenceWorker (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120048:69)
    at processSourceFile (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120062:5)
    at processRootFile (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119859:5)
    at /private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118638:41
    at forEach (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118638:5)
    at synchronizeHostData (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141677:15)
    at Object.getProgram (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141749:5)
    at InferredProject2.updateGraphWorker (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174307:41)
    at InferredProject2.updateGraph (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174159:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176549:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178167:12)
    at /private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178397:64
    at flatMap (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178397:24)
    at updateOpen (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179577:29)
    at /private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182149:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182141:14)
    at IpcIOSession.executeCommand (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182149:29)
    at IpcIOSession.onMessage (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182191:51)
    at process.<anonymous> (/private/var/folders/vy/cb58vztd6ldb8lmvkrzxxfy80000gp/T/AppTranslocation/3525491D-B171-4442-935D-F6AFD8DC7532/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183771:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (a7133ae9e21e01ed204b02e17e8fc3e91dcadae7, 2023-05-09T10:00:34.036Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id d96d0bd7-dd69-4348-811d-b1bdffacfed6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2023.16.0
gitlens|eam|13.6.0
copilot-chat|Git|0.1.2023051803
copilot-nightly|Git|1.86.105
black-formatter|ms-|2023.3.11241004
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
vim|vsc|1.25.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
cai9j608:30680470
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-24 23:59
Duplicate of https://github.com/microsoft/TypeScript/issues/54381

**Closed by mjbvz** 2023-05-24 23:59 UTC
