### ISSUE TITLE
V1_36 Tasks

### ISSUE THREAD

**Issue by nimishagarwal76** [microsoft/vscode#77517] opened 2019-07-17 10:55 UTC
I had certain tasks for compile and run C++ files which worked fine, untill I installed latest update. It stopped working. I had to switch back to previous version to get it running.

Ctrl + Shift + B used to run Compile and Run task in V1_35 not in v_1.36

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "debug",
            "type": "shell",
            "command": "",
            "args": [
                "g++",
                "-g",
                "${relativeFile}",
                "-o",
                "a.exe"
            ],
            "group": "build"
        },
        {
            "label": "Compile and run",
            "type": "shell",
            "command": "",
            "args": [
                "g++",
                "-g",
                "${relativeFile}",
                "-o",
                "${fileBasenameNoExtension}.out",
                "&&",
                "clear",
                "&&",
                "./${fileBasenameNoExtension}.out"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}
```

**Comment by alexr00** [comment] 2019-07-29 12:14
Thank you for including you tasks! This looks like a duplicate of https://github.com/microsoft/vscode/issues/77059, which is fixed in insiders already.

**Closed by alexr00** 2019-07-29 12:14 UTC
Labels: tasks
