### ISSUE TITLE
Add update button to left panel

### ISSUE THREAD

**Issue by GaryBoone** [microsoft/vscode#107816] opened 2020-09-30 15:49 UTC
Issue Type: <b>Bug</b>

VSCode frequently needs to restart to update when the default Update: Mode is active. The result is a daily blue icon on the settings gear in the lower left of the window. That then requires 1) selecting the gear icon, 2) dragging down to the bottom of the menu, 3) holding while the menu scrolls up because the update item is off-screen, 4) selecting "Restart to update".
Note that 3 happens because the gear icon is on the lowest part of the left panel, so if the window bottom is near the bottom of the screen as it normally would be, then the menu doesn't have room to render fully and doesn't shift up. It draws partially and the user has to scroll.

This is a tedious experience for something so trivial and common. The Extensions pages, for example, have simple buttons. Just click to restart after installing an extension.

The solution is simple: Just add a button in the left panel that appears when restarts are needed.

The bugs here are:
1) There isn't a one-click "restart to update" button prominently in the left panel.
2) The daily restart due to automatic updates is tedious due to its multiple UI steps.
3) The gear menu on the bottom left doesn't shift up to render fully but instead draws partially and requires scrolling.

...where 2 is solved by 1. 3 could be a separate bug because it affects the whole menu, not just the "Restart to update" menu item.

VS Code version: Code - Insiders 1.50.0-insider (0c50e1db17168a738235bd7e5c02b9f05ea5df59, 2020-09-30T06:45:45.996Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.7.10-1rodete2-amd64

**Comment by joaomoreno** [comment] 2020-10-01 14:06
> There isn't a one-click "restart to update" button prominently in the left panel.

This is not a bug. I bet a lot of different people would like a lot of different buttons in the left panel.

> The daily restart due to automatic updates is tedious due to its multiple UI steps.

True. Code will also update simply by quitting it, by the way.

> The gear menu on the bottom left doesn't shift up to render fully but instead draws partially and requires scrolling.

This is an issue in Electron on macOS. It's actually super smooth on other platforms:

![recording (6)](https://user-images.githubusercontent.com/22350/94819783-f2cd0b80-03ff-11eb-92e1-e2d3810272fd.gif)

Finally, feel free to assign a keybinding to the `update.restart` command, if you want to optimize for reducing the tedium and the multiple steps.

Sorry but I'll close this as designed.

**Closed by joaomoreno** 2020-10-01 14:06 UTC
