### ISSUE TITLE
Autofix on save not working for TS

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67482] opened 2019-01-29 20:16 UTC
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67295.

1) Install the TS Lint Plugin extension
-> Both TS Lint and TS Lint Plugin are installed now
2) Add 
```
    "[typescript]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
            "source.fixAll": true
        }
    }
```
to your user settings.
3) remove a couple of `;` from a `*.ts` file
-> Note that in the code action menu there are duplicate entries
4) Save
-> semicolons added
5) Uninstall TS Lint extension and reload window
6) remove a couple of `;` from a `*.ts` file
-> Note that there are no duplicate entries in the code actions menu anymore
7) Save
-> no semicolons added

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
solargraph|cas|0.19.2
ssh|chr|0.0.4
vscode-svgviewer|css|1.4.7
gitlens|eam|9.4.1
vsc-material-theme|Equ|2.6.3
vscode-pull-request-github-insiders|Git|1.29.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.5.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
Go|ms-|0.8.0
vscode-typescript-tslint-plugin|ms-|0.4.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
material-icon-theme|PKi|3.6.2
ruby|reb|0.21.0
vscode-xml|red|0.3.0
bash-debug|rog|0.3.3
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-01-29 20:54
I may be reading this issue incorrectly but auto fix is only enabled for TSLint and requires the TS Lint extension be installed. We don't ship any auto fix all as part of our normal TS extension

**Comment by kieferrm** [comment] 2019-01-29 21:40
Fix All on Save works when the TS Lint Plugin and the old TS Lint extension are installed.
FIx All on Save does not work when only the TS Lint Plugin extension is installed.

**Comment by mjbvz** [comment] 2019-01-29 21:49
Sorry but I can't repo this:

![jan-29-2019 13-47-05](https://user-images.githubusercontent.com/12821956/51942648-7a14e100-23cc-11e9-9acc-0e9ffdd12dc9.gif)

This is with:

```json
	"editor.codeActionsOnSave": {
		"source.fixAll": true
	}
```

* Only the TSLint plugin-based extension installed
* Using VS Code's version of TypeScript

**Comment by kieferrm** [comment] 2019-01-29 23:03
This is the extension host log:
```
[2019-01-29 15:00:32.506] [exthost] [error] Error: TypeScript Server Error (3.3.0-rc)
Error processing request. Cannot read property 'pos' of undefined
TypeError: Cannot read property 'pos' of undefined
    at Object.rangeContainsRange (tsserver.js:93561:41)
    at _loop_6 (tsserver.js:104471:36)
    at getContainingArgumentInfo (tsserver.js:104478:31)
    at Object.getSignatureHelpItems (tsserver.js:104093:32)
    at Proxy.getSignatureHelpItems (tsserver.js:118414:37)
    at IOSession.Session.getSignatureHelpItems (tsserver.js:126470:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125424:61)
    at tsserver.js:126891:88
    at IOSession.Session.executeWithRequestId (tsserver.js:126882:28)
    at IOSession.Session.executeCommand (tsserver.js:126891:33)
    at IOSession.Session.onMessage (tsserver.js:126913:35)
    at Interface.<anonymous> (tsserver.js:128174:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at v.dispatchResponse (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:163851)
	at v.dispatchMessage (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:162605)
	at constructor._reader.onData.e (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:161961)
	at e.fire (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
	at t.Reader.onLengthData (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:168034)
	at Socket.t.Reader.constructor.e.on.e (/Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:167682)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by kieferrm** [comment] 2019-01-30 00:14
@mjbvz When I change my settings file to only run `fixAll` on save then it works but not when I use the settings entry I posted above.

**Comment by mjbvz** [comment] 2019-01-30 00:38
Ok, this is a limitation of how the tslint plugin implements fix all. If you change the setting order, it does generally work:

```json
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": true
    }
```

The problem is the following:

1. Code actions on save are requested sequentially. For the setting:
    ```
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
        "source.fixAll": true,
    }
    ```

    We first request the organize imports actions and then the fix all actions

1. The tslint plugin computes its fix all action by: 

    * Get all diagnostics in the file
    * For each diagnostic, try to find the tslint fix all code action associated with that diagnostic

1. When organize imports is run first, it edits the document. This invalidates the diagnostics, which means no code actions are returned when the next `fix-all` code action check for them

Fixes would be:

- Get a proper TS api for computing fix all - https://github.com/Microsoft/TypeScript/issues/29452
- Somehow have TS lint 'fix-all' provider check if diagnostics are pending before we request code actions on them


Moving to tslint plugin extension because this is a tslint specific problem

**Comment by kieferrm** [comment] 2019-01-30 00:59
@mjbvz I could argue that it makes sense that fixAll is always the first source action to run since that allows all other source actions to operate on "better" code. So, why don't we resort fixAll to the beginning of the array while keeping all others in the same spot?

**Closed** 2019-01-30 19:33 UTC
Labels: bug
