### ISSUE TITLE
Notebook suggest icons missing colors again

### ISSUE THREAD

**Issue by znorman-harris** [microsoft/vscode#189377] opened 2023-08-01 02:15 UTC
Does this issue occur when all extensions are disabled?: Yes/No (Yes)

- VS Code Version: 1.80.2
- OS Version: Windows 11 and Mac

This issue seems to be happening again: #128798

![completion-bug](https://github.com/microsoft/vscode/assets/31664668/906985da-f0ba-43db-810d-c743bce52627)

**Comment by quangtienli** [comment] 2023-11-18 05:22
Any discussion on this? I have no idea how to bring the colors back to where it was.

<img width="779" alt="image" src="https://github.com/microsoft/vscode/assets/106639841/33ef9696-0ce2-4695-b88f-00fbf7a337db">

**Comment by znorman-harris** [comment] 2023-11-27 17:50
Still an issue for me as well

**Comment by rebornix** [comment] 2023-12-13 19:13
/duplicate of https://github.com/microsoft/vscode/issues/186905 , let's track it there.

**Closed by rebornix** 2023-12-13 19:13 UTC
Labels: bug, notebook, notebook-layout
