### ISSUE TITLE
cant copy text from integrated terminal

### ISSUE THREAD

**Issue by ravinsinghd** [Microsoft/vscode#7375] opened 2016-06-08 00:40 UTC
- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:

1. selected text from terminal
2. tried right click. no context menu open

**Comment by Tyriar** [comment] 2016-06-08 00:49
Duplicate of https://github.com/Microsoft/vscode/issues/6451

**Closed by Tyriar** 2016-06-08 00:49 UTC
