### ISSUE TITLE
Cannot debug anymore with VSCode in my typescript Angular application

### ISSUE THREAD

**Issue by stherrienaspnet** [microsoft/vscode#232934] opened 2024-11-04 02:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.1
- OS Version: Windows 11

Steps to Reproduce:

1. Debug any typescript project or Angular project
2.

**Comment by SPKorhonen** [comment] 2024-11-04 10:04
Possible duplicate of #210717

**Closed** 2024-11-04 19:27 UTC
Labels: *duplicate, new release
