### ISSUE TITLE
Copy paste bug on js files

### ISSUE THREAD

**Issue by vendra95** [microsoft/vscode#144464] opened 2022-03-05 13:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: 10.0.19043

Steps to Reproduce:

1. create a .js file
2. write `function testFunction() {
    $('.test-hello').show();
}`
3. copy a string text (ex. hello2)
4. overwrite (paste) `hello`
5. the string between '' disappears

This behavior has never occurred in previous versions.

**Comment by mjbvz** [comment] 2022-03-08 01:06
I can't repro this

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2022-03-08 19:41
Likely a duplicate of https://github.com/microsoft/TypeScript/issues/48006 actually

**Closed by mjbvz** 2022-03-08 19:41 UTC
Labels: needs more info
