### ISSUE TITLE
Shell script syntax highlighting stops after several one line function declarations

### ISSUE THREAD

**Issue by Alexendoo** [Microsoft/vscode#10521] opened 2016-08-14 15:54 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 8.1

Moving the final bracket down one line seems to fix it, moving the first bracket seems to change the effect by one. It doesn't seem that the depth of the declaration has any effect.

Jumping to the matching bracket still seems to function as expected

![image](https://cloud.githubusercontent.com/assets/1830331/17650171/deaa7a14-623e-11e6-8f87-bc502a4fa4f3.png)

**Comment by aeschli** [comment] 2016-08-15 09:07
The problem is that the grammar begins the "meta.scope.group.shell" rule, but doesn't leave it.
The rule that consumes 'echo ":(" also matches the closing bracket.

**Comment by aeschli** [comment] 2016-08-15 09:07
This issue was moved to textmate/shellscript.tmbundle#31

**Closed by aeschli** 2016-08-15 09:07 UTC

**Comment by Alexendoo** [comment] 2016-08-15 13:59
Ah if it's bash only then fair enough, the bundle is correct there, I was seeing the issue because vscode uses the it for highlighting zsh files also (where it is valid)
