### ISSUE TITLE
Collapse/expand regions does not work

### ISSUE THREAD

**Issue by phamquocduy** [Microsoft/vscode#47308] opened 2018-04-06 11:06 UTC
- VSCode Version: 1.22.1
- OS Version:

Steps to Reproduce:
1. Have //#region and //#endregion
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-04-06 18:11
In which language? Can you give a full code example?

**Comment by PierrickI3** [comment] 2018-04-07 12:26
I just noticed the same thing after updating to 1.22.1. I can no longer fold regions.
See a node.js example in the screenshot below:

<img width="518" alt="screen shot 2018-04-07 at 14 24 28" src="https://user-images.githubusercontent.com/7140338/38454875-a135cd36-3a6f-11e8-8afc-cce66c3df8f6.png">

**Comment by mpgr04** [comment] 2018-04-07 18:06
I have the same problem too

**Comment by mpgr04** [comment] 2018-04-07 18:06
For me it happens in JavaScript and PHP

**Comment by aeschli** [comment] 2018-04-08 14:36
Please file a separate issue for PHP, the folding providers are not related (actually nothing has changed for PHP)

**Comment by AlCalzone** [comment] 2018-04-08 16:51
Happens in TypeScript too since 1.22:
![unbenannt](https://user-images.githubusercontent.com/17641229/38470032-b97b622c-3b5d-11e8-8cae-9722948431ba.PNG)
Note the difference between regions with description (don't work) and regions without (they work)

**Comment by mjbvz** [comment] 2018-04-09 18:50
Root caused by https://github.com/Microsoft/TypeScript/issues/23270

Will be fixed in stable by #47473

**Closed by mjbvz** 2018-04-09 18:50 UTC
Labels: editor
