### ISSUE TITLE
Allow walkthrough to re-open after opening a folder from a step

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#137544] opened 2021-11-19 20:42 UTC
We've heard from extensions that they'd like to a step in their getting started to either open a folder or create a project. The downside with the walkthroughs right now is that opening a folder does not re-open the walkthrough where the user last left off. It would be great to have a flag to allow the walkthrough to re-open. A few examples of other extensions doing something similar:

<img width="958" alt="CleanShot 2021-11-19 at 12 40 08@2x" src="https://user-images.githubusercontent.com/35271042/142688918-aa30ecc2-1d5a-43ec-ad1e-0777640d1aaa.png">

<img width="937" alt="CleanShot 2021-11-19 at 12 40 41@2x" src="https://user-images.githubusercontent.com/35271042/142688977-de30e3f0-ff59-45f9-a476-77ef96077af3.png">

**Comment by alexweininger** [comment] 2021-11-19 20:51
This would be a huge value add for us over on the Azure extensions (specifically Static Web Apps). https://github.com/microsoft/vscode-azurestaticwebapps/issues/397

**Comment by misolori** [comment] 2021-11-19 21:47
Here's a demo of how this could become a streamlined experience:

https://user-images.githubusercontent.com/35271042/142695638-b4e646c8-c6f2-4089-8b52-b9e2cd94ea24.mov

**Comment by digitarald** [comment] 2021-11-19 23:44
This seems to have worked before as it landed and was verified in #123525.

**Comment by Eskibear** [comment] 2021-12-02 04:38
@digitarald  It's slightly different from #123525 .  In this issue, when you open a folder (e.g. which is not opened in vscode before) from walkthrough, the walkthrough will not open automatically, so users cannot resume and follow rest steps.

Demo in https://github.com/microsoft/vscode/issues/137544#issuecomment-974494107 is exactly the experience we want. 
Technically, what I can imagine now include:
- Option A. provide a command like `workbench.action.files.openFolder` accepting args like id of walkthrough to open.
- Option B. For command `workbench.action.files.openFolder`, if it's triggered from a walkthrough step (but not the last step), it auto opens current walkthrough after opening the folder.
- ...

**Comment by nickzhums** [comment] 2021-12-13 08:13
Hello folks, any update for this issue ? We are currently optimizing our walkthrough and this issue is a blocker in our overall walkthrough flow - Would be great if we can have an ETA of some sort :) 

thanks!

**Comment by jaeyonglee8687** [comment] 2021-12-20 08:42
@digitarald so is this issue targeting to be resolved by the January milestone? 
TeamsFx team is also having the same trouble and would like to leverage this in GA scope if possible.

**Comment by digitarald** [comment] 2022-01-03 17:54
Checking with @JacksonKearl if it's on his radar. Afaik this is a regression as it worked before, so the scope shouldn't be a concern.

**Closed** 2022-01-05 00:36 UTC
Labels: feature-request, getting-started

**Comment by JacksonKearl** [comment] 2022-01-05 00:39
Added new API for telling vscode that after running a given command via getting started, a provided folder URI should be opened. VSCode core will handle opening the URI with the current walkthrough&step selected. Please LMK if this works for your use cases. 

Sample: https://github.com/microsoft/vscode-extension-samples/blob/main/getting-started-sample/src/extension.ts#L28-L30

**Comment by JacksonKearl** [comment] 2022-01-25 04:00
@alexweininger, @jaeyonglee8687, @nickzhums, etc. if possible it'd be helpful if you could text this new functionality in Insiders and verify that it suits your indented use cases.

**Comment by nickzhums** [comment] 2022-01-25 04:23
@Eskibear would you mind doing a test of this?

**Comment by Eskibear** [comment] 2022-01-25 04:27
I just tested the example provided in https://github.com/microsoft/vscode/issues/137544#issuecomment-1005282329 , and it works. However it simply hardcoded the target folder to open. 

Our user case is to let users specify their Java project folder to open. But hopefully we can implement some logic with "open dialog" to let user specify the folder to open.

**Comment by Eskibear** [comment] 2022-01-25 04:43
I simply tried below sample code, the API works well, and the walkthrough page is opened automatically.

But there's a small problem for us to tweak. From the demo you can find that, there is a re-rendering of walkthrough after we grant workspace trust. That's because some java extensions are activated, changing some context value, leading to the update of the steps.

```ts
  context.subscriptions.push(vscode.commands.registerCommand('java.pack.openFolder', async () => {
    const target = await vscode.window.showOpenDialog({
      canSelectFolders: true,
      canSelectFiles: false,
      canSelectMany: false,
    })
    return target && { openFolder: target[0] };
  }));
```

Demo:

https://user-images.githubusercontent.com/2351748/150911647-2dccbbf8-8e48-40f9-acb4-c8151f32a1b5.mp4

**Comment by JacksonKearl** [comment] 2022-01-25 04:48
We need to reload the window upon granting trust, so there's no avoiding the re-render. I'm not exactly sure what you mean regarding the context keys, is the final displayed walkthough incorrect?

**Comment by Eskibear** [comment] 2022-01-25 05:03
See 0:08 ~ 0:10 in my demo. There's no problem after granting trust, re-rendering of walkthrough. And the active step is still "explore your projects" at that moment.

For "explore your projects" step, we actually provide two different steps, depending on whether there's a valid Java project recognized by Java LS. So you'll see 1s after granting trust, the walkthrough refreshed and it changed to focus on the first step.

I guess that's as expected behavior. It just makes the workflow less smooth, but is not a blocking problem.

**Comment by Eskibear** [comment] 2022-01-25 05:06
Before granting trust, it was focusing on `java.showProjectExplorer.inactive`. And after, the step is replaced by a different step `java.showProjectExplorer` (though same title), and I guess that's the reason why it's not focused.

```
{
            "id": "java.showProjectExplorer",
            "title": "Explore your projects",
            "description": "%walkthrough.java.projects%",
            "media": {
              "svg": "walkthrough/projects.svg",
              "altText": "Project Explorer"
            },
            "when": "java:projectManagerActivated && workspaceFolderCount > 0"
          },
          {
            "id": "java.showProjectExplorer.inactive",
            "title": "Explore your project",
            "description": "%walkthrough.java.projects.inactive%",
            "media": {
              "svg": "walkthrough/projects.svg",
              "altText": "Project Explorer"
            },
            "when": "!java:projectManagerActivated || workspaceFolderCount == 0"
          },
```

**Comment by 1openwindow** [comment] 2022-02-11 06:05
@JacksonKearl , I know this issue was closed, but I still got one question when I try to implement this cool feature. Can you help to address it. 
In your shared example: https://github.com/microsoft/vscode-extension-samples/blob/4e9b69f212d4544f8ad933b473c84db87b34c78f/getting-started-sample/src/extension.ts#L28-L30
	context.subscriptions.push(vscode.commands.registerCommand('getting-started-sample.viewSources', () => {
		return { openFolder: vscode.Uri.joinPath(context.extensionUri, 'src') }; 
	}));

it will open folder in same windows, is there any way to open folder in a new windows? Such as: 
`return { openFolder: vscode.Uri.joinPath(context.extensionUri, 'src'), forceNewWindow: true }; `
