### ISSUE TITLE
Navigation arrows on the keyboard don't work (Debian package)

### ISSUE THREAD

**Issue by dmitsh** [Microsoft/vscode#24529] opened 2017-04-11 15:56 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.52|;

---

Steps to Reproduce:

1. Open a file in VSCode (on Linux)
2. Use navigation arrows (left, right, up, down) to navigate on the text. It doesn't work!

**Comment by Sgtpanda** [comment] 2017-04-11 17:32
Also getting this issue, it appears to be related to the new way of checking KeyBoardEvent.code, worse still it's not just navigating the text that doesn't work, using the arrow keys on code completion suggestions doesn't work properly either, the 'Delete' key also seems not to work.

I'm on X11 over SHH, not sure if that could be part of the problem.
As a workaround setting "keyboard.dispatch": "keyCode" reverts to the old behaviour and fixes it.

**Comment by initiumSrc** [comment] 2017-04-11 18:09
Similar issue here, ESC and CAPS is swapped in my X11 config. After updating to version 1.11.1 the ESC and CAPS are not swapped in the editor but swapped on my system.

The workaround submitted by @Sgtpanda fixes this, but the behaviour is unexpected and confusing.

**Comment by alexandrudima** [comment] 2017-04-12 08:14
@dmitsh @Sgtpanda Duplicate of #24107 -- the latest insiders release contains a fix, would you mind validating?
@initiumSrc Duplicate of #23991 - the only workaround for now is to use `"keyboard.dispatch": "keyCode"`.

**Closed by alexandrudima** 2017-04-12 08:14 UTC
