### ISSUE TITLE
Attempting to delete node_modules dir in VSCode workspace fails EPERM: operation not permitted, unlink ...

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#86421] opened 2019-12-05 18:59 UTC
- VSCode Version: 1.40.2
- OS Version: Windows 10 1909

Steps to Reproduce:

1.  Open a workspace that has npm projects in it and populated node_modules dirs
2.  After a while, attempt a build that does a rimraf of your node_modules dirs

Does this issue occur when all extensions are disabled?: Yes

I've read several closed issues just like this that point the finger at TypeScript but from what I can see it is `code.exe` that has the dirs locked (using SysInternals handle.exe):
```
Code.exe           pid: 5472   type: File           418: C:\Users\hillr\Git\KLM\src\KalManagement\dist\kal-management\node_modules
Code.exe           pid: 5472   type: File           41C: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 5472   type: File           420: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 5472   type: File           430: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 5472   type: File           434: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 5472   type: File           43C: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 5472   type: File           448: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 5472   type: File           460: C:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules
Code.exe           pid: 5472   type: File           46C: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\dist\kal-management-app-services\node_modules
Code.exe           pid: 5472   type: File           494: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 5472   type: File           4B4: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\dist\kal-management-app-services\node_modules
Code.exe           pid: 5472   type: File           4D4: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
```
I also tried restarting the TS server.  handle.exe shows all these folders are still locked.

Our whole dev team is really getting tired of having to exit VSCode for every freaking build.

**Comment by mjbvz** [comment] 2019-12-05 19:19
Seems like a duplicate of https://github.com/microsoft/TypeScript/issues/32113

To help move that issue along, please try opening a new issue upstream with repo steps so that the TS team can investigate

**Comment by mjbvz** [comment] 2019-12-05 19:21
Actually before you do that, please share the full process info (such as the command line arguments) for the process holding the lock

**Comment by rkeithhill** [comment] 2019-12-05 19:22
Does TS run inside code.exe?  I thought that would run in a separate exe.  I'll grab that extra info in a bit.

**Comment by rkeithhill** [comment] 2019-12-05 19:36
Here ya go:
```
Code.exe           pid: 23548  type: File           508: C:\Users\hillr\Git\KLM\src\KalManagement\dist\kal-management\node_modules
Code.exe           pid: 23548  type: File           50C: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\dist\kal-management-app-services\node_modules
Code.exe           pid: 23548  type: File           510: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
C:\Users\hillr
12-05 12:32:25 2> get-ntprocess 23548 | % CommandLine
"C:\Program Files\Microsoft VS Code\Code.exe" --max-old-space-size=3072 "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\hillr\AppData\Local\Temp\vscode-typescript\a046e5a7634361593230\tscancellation-2191af9d140a955dee64.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```
So does look to be TS Server related.  But I've run the Restart TS Server command and while the build gets a little further, it still fails.  And now that I look at this with handle.exe, I can see that the TS server restart, killed the old process and started a new one. It has fewer of my node_modules folders open but it still has some open (3 out of 6).

**Comment by mjbvz** [comment] 2019-12-05 19:40
Thanks. Just to confirm, after the restart, you don't see old processes still hanging onto the lock, just a new `tsserver` process?

**Comment by rkeithhill** [comment] 2019-12-05 19:47
Correct but the new process pretty quickly starts locking folders. For example, a few secs after the TS restart is complete, I see the new process has these folders locked:
```
Code.exe           pid: 6304   type: File           408: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 6304   type: File           40C: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 6304   type: File           414: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 6304   type: File           420: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 6304   type: File           424: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 6304   type: File           428: C:\Users\hillr\Git\KLM\src\KalManagement\dist\kal-management\node_modules
Code.exe           pid: 6304   type: File           42C: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 6304   type: File           444: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 6304   type: File           448: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 6304   type: File           450: C:\Users\hillr\Git\KLM\src\KalManagementAppServices\node_modules
Code.exe           pid: 6304   type: File           454: C:\Users\hillr\Git\KLM\src\KalClientServices\dist\kal-client-services\node_modules
Code.exe           pid: 6304   type: File           468: C:\Users\hillr\Git\KLM\src\KalClientServices\dist\kal-client-services\node_modules
Code.exe           pid: 6304   type: File           46C: C:\Users\hillr\Git\KLM\src\KalClientServices\node_modules
Code.exe           pid: 6304   type: File           480: C:\Users\hillr\Git\KLM\src\KalManagement\node_modules
Code.exe           pid: 6304   type: File           494: C:\Users\hillr\Git\KLM\src\KalClientServices\dist\kal-client-services\node_modules
Code.exe           pid: 6304   type: File           498: C:\Users\hillr\Git\KLM\src\KalManagement\dist\kal-management\node_modules
```

**Comment by mjbvz** [comment] 2019-12-05 19:56
Thanks for confirming. This has the same symptoms of microsoft/TypeScript#32113 so I suggest that you follow up upstream on the TypeScript repo

I've prioritized microsoft/TypeScript#32113 but I know the TS team has had trouble reproducing the issue to investigate it

**Closed by mjbvz** 2019-12-05 19:56 UTC
Labels: git
