### ISSUE TITLE
Programs / executables / libraries are not signed

### ISSUE THREAD

**Issue by twpol** [Microsoft/vscode#11571] opened 2016-09-06 08:59 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Download and install VSCode
2. Open VSCode
3. Open Process Explorer
4. In Process Explorer, enable Verify Image Signatures from Options menu

Expected Results:

Verified Signer column says "(Verified) Microsoft Corporation"

Actual Results:

Verified Signer column says "(No signature was present in the subject) Microsoft Corporation"

More Details:

There are two particular processes running on my machine:

- C:\Program Files (x86)\Microsoft VS Code\Code.exe
- c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\files\node\watcher\win32\CodeHelper.exe

However, I'd expect all executable components to be signed, including libraries (currently only the MSVC runtime libraries are signed).

**Comment by ramya-rao-a** [comment] 2016-09-06 21:59
@joaomoreno Duplicate of #10763 ?

**Comment by joaomoreno** [comment] 2016-09-07 08:13
Absolutely, thanks!

**Closed by joaomoreno** 2016-09-07 08:13 UTC
