### ISSUE TITLE
After modifying a file, the "change" flag cannot be displayed. （SVN）

### ISSUE THREAD

**Issue by QuentinHsu** [microsoft/vscode#104750] opened 2020-08-16 10:56 UTC
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

When using the [SVN](https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm)(v 2.12.3) plug-in, after modifying a file, the "change" flag cannot be displayed.
This worked with VS Code v1.47.3, but not with VS Code upgrade to v1.48.
As shown in the screenshot, this is what is shown in the working state.

I reported back to the author of the plugin, but he was told that it was a VS Code issue。[link](https://github.com/JohnstonCode/svn-scm/issues/1042#issuecomment-674000407)

I have tried using the insiders version but found that the problem is not fixed.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

Screenshots
![image](https://user-images.githubusercontent.com/21162238/90332669-5dadb900-dff1-11ea-9b6c-27b58c944548.png)

**Comment by gjsjohnmurray** [comment] 2020-08-16 18:04
/duplicate of #104640, already raised by extension author.

**Closed** 2020-08-16 18:05 UTC
Labels: *duplicate, new release
