### ISSUE TITLE
Support path links that contain spaces in the integrated terminal 

### ISSUE THREAD

**Issue by nielsvaneck** [microsoft/vscode#97941] opened 2020-05-15 18:51 UTC
- VSCode Version: 1.45.1
- OS Version: MacOS 10.15.4

Steps to Reproduce:

1. create a vscode python project in a directory with a space that contains some code that produces a failing test or stacktrace
2. hover over the paths in the stacktrace and notice that those with a space in a directory name are not rendered as links.  those without spaces are.

I have created a tiny repo that reproduces the bug: https://github.com/nielsvaneck/vscode_space_path_bug

Does this issue occur when all extensions are disabled?: *Yes*

**Comment by Tyriar** [comment] 2020-06-11 12:01
For the case that you linked I don't think it's expected that it would be linkified on Linux and macOS when the `\` before the space is not present, what tools are outputting this? (it's a little more nuanced on Windows)

**Comment by nielsvaneck** [comment] 2020-06-12 15:25
> For the case that you linked I don't think it's expected that it would be linkified on Linux and macOS when the `\` before the space is not present, what tools are outputting this? (it's a little more nuanced on Windows)

just the error output generated by the python interpreter

**Comment by smcoll** [comment] 2020-09-01 15:48
Am i having the same issue, or is this different?

In the terminal, paths in the Python traceback are not linked/clickable if there is a space in the path, even though the path is quoted.  For example: 

```
File "/home/me/some space/myproject/mypapp/models.py", line 360, in foo
    for obj in qs.distinct()
```

That seems to be the issue referenced by https://github.com/microsoft/vscode-python/issues/7491 (closed and conversation locked) which was moved to https://github.com/microsoft/vscode/issues/81190 (closed and conversation locked) which is marked as a duplicate of https://github.com/microsoft/vscode/issues/21125 which is supposedly fixed (closed and conversation locked).

Same problem for traceback inlined in the code editor while debugging (i'm not sure what this UI component is called, or where to find out).

**Comment by Tyriar** [comment] 2020-09-02 15:53
This is the same issue yes.

As of 1.49.0 we have stabilized the link provider API which would allow Python to add better support to Python-specific link formats like this one. The problem we face is the output could be literally everything, so our list of detection continues to grow and get slower and slower. While we could provide better support for spaces in names (that's what this issue is about), Python could improve the support by making this link do something with `foo` if that's useful

> File "/home/me/some space/myproject/mypapp/models.py", line 360, in foo

And maybe even give this line a link to do something useful:

> for obj in qs.distinct()

FYI @luabud

**Comment by smcoll** [comment] 2020-09-18 06:29
@Tyriar is the line considered Python-specific because it's a format used in Python tracebacks?  And are you saying that Python support could choose to link right to that line in the file, for example?

i opened https://github.com/microsoft/vscode-python/issues/7491 hoping that the original issue for the Python extension can be re-opened.

**Comment by Tyriar** [comment] 2020-09-18 14:20
@smcoll I commented on https://github.com/microsoft/vscode-python/issues/13989

**Comment by jackHedaya** [comment] 2021-02-10 19:17
I don't think this is python specific –– I'm encountering the same bug in Node.js

**Comment by BenjaminGalliot** [comment] 2021-03-27 13:33
Same here with Julia.

**Comment by MichaelUray** [comment] 2021-03-28 19:55
Same problem with Python in Windows 10 using Visual Studio Code (Version: 1.54.3)
It does not allow to click hyperlinks in error messages if there is a space in the path.
![2021-03-28_21-52-29_thermalCamVideo py_-_thermalCamVideo_-_Visual_Stud](https://user-images.githubusercontent.com/25169478/112765998-0f917700-9010-11eb-99e3-eb58bbb2af99.png)

**Comment by GeorgeLyon** [comment] 2021-06-18 19:12
This issue also exists with Swift on macOS:  
<img width="401" alt="Screen Shot 2021-06-18 at 12 11 41 PM" src="https://user-images.githubusercontent.com/989903/122606831-6d8d9380-d02e-11eb-9a9c-9c421a13c5fc.png">

**Comment by ItaiPendler** [comment] 2021-08-01 06:24
Hey this still happens to me, any updates?

**Comment by mcurrycl** [comment] 2021-10-10 23:28
I am also having this issue with Typescript and any other languages I have tried. It makes VSCode unusable for debugging in this sense, I have to manually find the line of code or reinstall Windows to make sure there are no spaces in my linked network and local paths. Please fix.

**Comment by shiraze** [comment] 2021-11-01 16:13
Same issue here with any error that get shown in Terminal. Example lint issue, with a path that contains a space ("IS Transfer"), and clicking the link should open up folder location, but attempts to open up "C:\IS" or "Transfer\Source\...."
![image](https://user-images.githubusercontent.com/9248719/139704037-c87da5dc-1de0-485c-84f5-cb774f238d6f.png)

**Comment by AgainPsychoX** [comment] 2021-11-02 10:14
_I am on it, will try my best._

**Comment by Tyriar** [comment] 2021-11-02 12:54
@AgainPsychoX this is probably not the best candidate for a contribution as it's not yet known what an efficient solution would look like.

**Comment by AgainPsychoX** [comment] 2021-11-02 13:16
I was looking in the related code some time already and I have few ideas. Current solution does not seem to be efficient at all, in few places I can see Regex recompiled and executed even for the very same link.

Key things I would want to do are:
* [ ] Make `TerminalLink` class abstract, then move tooltip and activation callbacks from `LinkManager` to `TerminalLink` specializations (refactor to separate shared code). 
* [ ] Make link providers parse the found paths/links instead just matching them - one regex to catch path with line and column numbers.
* [ ] Better path detection, I already have interesting piece of more efficient Regexes to detect all current stuff plus spaces (with conditions like, spaces are allowed only inside parenthesis by quotes, brackets, etc. 
* [ ] Use more general `ITerminalInstance` in `TerminalLink`s/providers (instead just `Terminal` from xterm), as there are places the code need stuff from the general version (like widget manager; it will avoid listening to changes to update `LinkManager` I think).
* [ ] Add custom providers for detecting paths without parenthesis but with spaces, like in `shiraze` post above. Specialized provider could look not at certain line, but whole feed (stateful to detect path that are connected to multiple following links of line/number.

**Comment by Tyriar** [comment] 2021-11-02 13:34
@AgainPsychoX thanks for looking into it, in general this sounds good 👍 I'd recommend small focused PRs to make them easier and less risky to review/merge

>  I can see Regex recompiled and executed even for the very same link.

I think we can just add `@memoize` to `TerminalValidatedLocalLinkProvider._localLinkRegex` for example to get caching happening.

> Make TerminalLink class abstract, then move tooltip and activation callbacks from LinkManager to TerminalLink specializations (refactor to separate shared code).

I can't remember the reason for this, just make sure you don't introduce a circular dependency when doing this.

> Better path detection, I already have interesting piece of more efficient Regexes to detect all current stuff plus spaces

I worry about trying to use regex for path with space detection as well as it's often not clear why a regex is slow and it seems like adding spaces to the regex will make it much more difficult to optimize.

> Use more general ITerminalInstance in TerminalLinks/providers (instead just Terminal from xterm), as there are places the code need stuff from the general version (like widget manager; it will avoid listening to changes to update LinkManager I think).

This would add a circular dependency (TerminalInstance -> TerminalLinkManager -> ... -> TerminalLink -> TerminalInstance) which we should avoid as it will make unit testing more cumbersome.

**Comment by tjx666** [comment] 2021-11-18 10:45
eslint same here.

![image](https://user-images.githubusercontent.com/41773861/142400974-87669735-c8a1-4215-bc9b-f4e2d4344e0c.png)

**Comment by surajmandalcell** [comment] 2022-05-11 08:53
Any update on this?

**Comment by GoodiesHQ** [comment] 2022-05-11 09:14
For real, you'd think more people would complain since Windows' default account style has a space in the name... any of my documents have a space in the full path.

**Comment by bromelio** [comment] 2022-08-25 09:10
Same issue. Is there a workaround to make paths with spaces in them clickable in VSC while we wait?

**Comment by Tyriar** [comment] 2022-08-25 13:27
@bromelio no updates other than what is posted. A workaround is to select the link (double click + drag makes this easy), copy, then ctrl+p and paste

**Comment by bromelio** [comment] 2022-08-25 18:11
@Tyriar Thanks for the workaround, very attentive of you! I was hoping for something like _replace space with \x20 and it'll work_, though 😉. But I guess that's simply not possible then? 😞

Anyway, please have this fixed. It's an annoying bug and I think you personally already found a solution (regex)? If your colleagues don't like regex barring any better idea then please simply tell them that customers like bugs even less and push it through regardless. Less important things are constantly being implemented while we've already been patient for over two years here. Maybe we have to get a little more cheeky to be heard, too?

**Comment by Pullusb** [comment] 2022-10-10 19:29
Hi everyhone,

Same here when developing add-on for blender in VScode.
The installation of Blender folder sadly have a space in name... "Blender Foundation"

Print something like this on error:

```
    from . import error_handle
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\myAddon\handle.py", line 176       
    .filename
    ^
```

I always want to click on that path :rage2:  , it even has the line number hint included so it should be able to get there.

+1 for clickable path with space.

For now @Tyriar's workaround save the day (+ we can quickly add line number after path with `:258`)
But still manual where it should be a one click jump to line.
Does any VScode user here have found a plug-in that parse the console and that could do that ?

Happy coding all

**Comment by Tyriar** [comment] 2022-12-21 23:46
I put this together in https://github.com/microsoft/vscode/pull/169786, here are the detected formats when it gets merged:

- Python style links: `From "<path>", line <line>`
- Lines that only contain a path: `<path>`
- Independently styled file paths: `foo<underlined_path>bar`

I think that should cover the main cases called out in the issue, let me know if your case isn't covered by this.

**Closed** 2022-12-22 05:03 UTC
Labels: feature-request, terminal-links
