### ISSUE TITLE
Can't type Vietnamese

### ISSUE THREAD

**Issue by EmYeuCoGiao** [Microsoft/vscode#1412] opened 2015-12-17 10:10 UTC
I can't type vietnamese with Unikey software, also with Visual Studio everthing worked perfectly

**Comment by takumif** [comment] 2015-12-18 02:40
I believe this is a duplicate of #1168.

**Comment by EmYeuCoGiao** [comment] 2015-12-18 03:17
Ok. I will follow #1168
Thanks you!

**Closed** 2015-12-18 13:39 UTC
Labels: bug, editor
