### ISSUE TITLE
ability to put integrated terminal panel on top

### ISSUE THREAD

**Issue by JestDotty** [microsoft/vscode#167810] opened 2022-12-01 08:17 UTC
ability to put integrated terminal panel on top

you're allowed bottom, left, right, but not top. My original editor was Atom but was discontinued, VSCode was suggested to me but I'm frustrated that the panels/tabs can't be drag and dropped easily/consistently like they were in Atom. My screens are elevated and the terminal is less important, so it would be nice to make the text files in the best focus area for my case (not to say my case is important, but I think layout customization in IDEs makes sense as a design principle, since it falls under stuff like usability). Thanks.

**Comment by sbatten** [comment] 2022-12-01 19:12
dupe of https://github.com/microsoft/vscode/issues/50984

**Closed by sbatten** 2022-12-01 19:12 UTC
