### ISSUE TITLE
Diff is not encoding aware

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#38879] opened 2017-11-21 14:45 UTC
- VSCode Version: 1.18.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Create repo with file in CP1251 encoding (windows 1251)
2. Save it and commit to repo.
3. Open in vs code, lines with cyrillic symbols will have blue diff stripe. 

![image](https://user-images.githubusercontent.com/7345761/33078394-9a0c7070-cee3-11e7-9573-0dc5e920a856.png)

Reproduces without extensions: Yes

Some cyrillic text:
```
hello world.
привет мир.
```

Probably relates to #21146
See also https://github.com/JohnstonCode/svn-scm/issues/35#issuecomment-346043458

**Comment by joaomoreno** [comment] 2017-11-21 15:33
Duplicate of #21146

**Closed** 2017-11-21 15:34 UTC
Labels: *duplicate, git, new release
