### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#96627] opened 2020-04-29 17:49 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T05:54:24.582Z)
OS version: Linux x64 5.6.7-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-firefox-debug|fir|2.7.2
graphql-for-vscode|kum|1.15.3
atom-keybindings|ms-|3.0.6
magic-beans|sel|0.22.1
niketa|sel|3.2.2
tabnine-vscode|Tab|2.8.1
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
wallaby-vscode|Wal|1.0.196

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-04-29 20:02
Duplicate of https://github.com/microsoft/TypeScript/issues/37500

To upgrade your workspace to use `typescript@3.9`, install [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-04-29 20:02 UTC
