### ISSUE TITLE
Extreme laggy when .... your are not ready for this guys!

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#113553] opened 2020-12-29 21:02 UTC
After several years of frustrating random laggy code sessions requiring to restarts vscode , disable and test all plugins one by one and sometime reboot machine!

I have just discovered that some window applications can affect permanently vscode and give a permanant lag !!!
Big wtf here !
Am happy because now i will get no more lag in vscode and no more reboot or restart.
But I also feel anxious to realize that opening an app can affect vscode!

i think this need a video to capture this weird behavior for ever, and hope this can also help to find why you get LAGGS on a nextgen machine !!

**Never open `MicrosoftVirtualKeyboard` in your current Window sessions.**
https://youtu.be/14AKtLqlbtE

So if you find vscode slow, think about testing your applications in the background which could affect this one without understanding why.
@+

**Comment by rzhao271** [comment] 2021-01-06 17:36
Duplicate of https://github.com/microsoft/vscode/issues/107016

**Closed** 2021-01-06 17:37 UTC
Labels: *duplicate, bug, perf, windows
