### ISSUE TITLE
Using ALT to focus menu bar breaks ALT multiple cursors/selection

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#54065] opened 2018-07-11 14:56 UTC
- VSCode Version: 1.26.0-Insider
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Enable the new experimental title bar
2. Hold alt and click multiple places in the document to insert multiple cursors
3. Release alt. The new menu is focused, causing all cursors and selections to disappear

**Comment by iansan5653** [comment] 2018-07-11 14:57
This issue is caused by #53924.

**Comment by iansan5653** [comment] 2018-07-12 17:34
I'm not able to reproduce this anymore since updating today and switching to the User version. I'm not sure what changed to fix it since I don't see any new PRs related to this though, so I hesitate to mark it closed.

**Comment by sbatten** [comment] 2018-07-12 17:37
same root cause as #54047, now fixed

**Closed by sbatten** 2018-07-12 17:37 UTC
Labels: important, workbench-menu
