### ISSUE TITLE
Extension Host is Shutting Down

### ISSUE THREAD

**Issue by AritraLahiri** [microsoft/vscode#94789] opened 2020-04-09 13:37 UTC
Issue Type: <b>Bug</b>

After the recent March update the extension host is constantly shutting down . 

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G620 @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (4.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.2
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|2.7.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
code-runner|for|0.9.17
vscode-simple-icons|Lau|1.13.2
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.0.1
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-04-09 16:06
Please try disabling your LiveServer extension. If that doesn't solve the problem, disable other extensions until you discover which one is crashing the Extension Host (EH) process.

**Comment by RMacfarlane** [comment] 2020-04-09 16:09
Duplicate of https://github.com/microsoft/vscode/issues/94807

**Closed by RMacfarlane** 2020-04-09 16:09 UTC
Labels: new release
