### ISSUE TITLE
JavaScript syntax highlighting

### ISSUE THREAD

**Issue by chmln** [Microsoft/vscode#5361] opened 2016-04-15 20:18 UTC
- VSCode Version: 1.0.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open any js file with abundant variables and functions
2. Compare with any other popular editor e.g. sublime, atom, brackets, etc

VS Code is a fantastic editor. However, for an editor that accentuates support for JavaScript, the syntax highlighting is less than sub-par. 

To illustrate, here's VS Code and Sublime using the same color scheme:
![vsc_](https://cloud.githubusercontent.com/assets/11352152/14573672/6ef0d336-0324-11e6-8b8a-6953b87cb469.PNG)
![subl3](https://cloud.githubusercontent.com/assets/11352152/14573673/6ef1c106-0324-11e6-8a62-d2f3fdc460f4.PNG)

The color scheme isn't at fault since the default (dark+) theme is not much better
![vsc](https://cloud.githubusercontent.com/assets/11352152/14573691/88886d72-0324-11e6-9eaa-23a3acde6431.PNG)

Here's the code in screenshot:
```javascript
init = function () {

        navigationCurrentMonth.className = 'flatpickr-current-month';
        calendarContainer.className = 'flatpickr-calendar';
        calendar.className = "flatpickr-days";
        
        instanceConfig = instanceConfig || {};

        self.config = {};
        self.element = element;

        for (var config in self.defaultConfig)
            self.config[config] =
                instanceConfig[config] ||
                self.element.dataset&&self.element.dataset[config.toLowerCase()] ||
                self.element.getAttribute("data-"+config)||
                self.defaultConfig[config];

        
        self.input = (self.config.wrap) ? element.querySelector("[data-input]") : element;    

        if(self.config.defaultDate){
            self.config.defaultDate = uDate(self.config.defaultDate);
        }

        if ( self.input.value || self.config.defaultDate )
            self.selectedDateObj = uDate(self.config.defaultDate||self.input.value);

       self.config.minDate =
            uDate(self.config.minDate === "today" ? new Date() : self.config.minDate, true);

       self.config.maxDate = uDate(self.config.maxDate, true);

        self.jumpToDate(self.selectedDateObj||self.config.minDate||currentDate);

        wrap();        
        buildCalendar();
        bind();

        if (!self.config.noCalendar)
            updateValue();
    };
```

Significant and *absolutely necessary* enhancements can be brought in by highlighting:
* Variables
* Function names
* Methods

**Comment by aeschli** [comment] 2016-04-20 20:54
The build-in default themes do - by design- not highlight variable, method and function references.
The dark/light theme colorize however declarations.

@chmln Which custom theme to you use?

**Comment by chmln** [comment] 2016-04-20 21:12
> Which custom theme to you use?

*One Dark*

I have tried all the popular color themes, and not a single one has colored variables, methods, etc. 

Logically, that can be explained by two scenarios:
* It is impossible to color variables, methods, and function references
* All the color scheme authors are closet notepad fans

**Comment by chmln** [comment] 2016-04-20 21:12
![1](https://cloud.githubusercontent.com/assets/11352152/14690555/9bd18810-071a-11e6-92de-57084534303b.png)
![2](https://cloud.githubusercontent.com/assets/11352152/14690552/9bb22dd0-071a-11e6-85a3-60bd9c475373.png)
![3](https://cloud.githubusercontent.com/assets/11352152/14690551/9bb1f89c-071a-11e6-8b70-76169bf985fb.png)
![5](https://cloud.githubusercontent.com/assets/11352152/14690553/9bb3ea26-071a-11e6-8a9f-e93c5a48df2e.png)
![4](https://cloud.githubusercontent.com/assets/11352152/14690554/9bb4de22-071a-11e6-9b59-e58d6d7fc229.png)

**Comment by Tyriar** [comment] 2016-04-20 21:51
The root issue here is that https://github.com/Microsoft/TypeScript-TmLanguage does not scope variables and method calls.

**Comment by chmln** [comment] 2016-04-20 22:02
That explains it.
I see issues like https://github.com/Microsoft/TypeScript-TmLanguage/issues/72 so I surely can't be the first one to notice those shortcomings.

**Comment by aeschli** [comment] 2016-04-21 06:44
Looking at Atom JS grammar it seems they use the `support.function` scope for function references.
For variable references it's `variables.other.object`.
We would still need a scope that stands for just the variable declaration.
Moving this to the TM/JS grammar team for consideration. I personally think we should stick to what we have.

**Comment by aeschli** [comment] 2016-04-21 06:44
This issue was moved to Microsoft/TypeScript-TmLanguage#149

**Closed** 2016-04-21 07:33 UTC
Labels: feature-request, js
