### ISSUE TITLE
Users are reporting my extension is re-enabling itself when I publish updates

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#73484] opened 2019-05-08 18:24 UTC
In the last few days I've had two reports of the same thing - my extension was disabled for a workspace and it re-enabled itself:

- https://github.com/Dart-Code/Dart-Code/issues/1695
- https://github.com/Dart-Code/Dart-Code/issues/1690

As far as I can see, there's no way my extension could be causing this (if it's disabled, it's not running any code)?

Strangely, it's apparently only happening for the Dart extension, not the Flutter extension. Both are always published at the same time (note: Flutter has a dependency on Dart - I don't know if that's related).

I think this has to be a VS Code bug, but if you can think of anything I could be doing that could result in this, please let me know!

**Comment by sandy081** [comment] 2019-05-09 08:48
/duplicate of https://github.com/microsoft/vscode/issues/71752

**Closed** 2019-05-09 08:48 UTC
Labels: *duplicate, extensions

**Comment by DanTup** [comment] 2019-05-09 09:09
Whoops, thanks! I did search but didn't turn anything up (though there are a lot of pages of results searching for these words).
