### ISSUE TITLE
Quick Outline/Goto Symbol does not work on the Default Keyboard Shortcuts

### ISSUE THREAD

**Issue by djhojd** [Microsoft/vscode#17376] opened 2016-12-16 07:39 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: None

---

The first Q&A from [Common Questions](https://code.visualstudio.com/docs/customization/keybindings#_common-questions) does not work.

Steps to Reproduce:

1. Open `Keyboard Shortcuts` (Ctrl+k Ctrl+S)
2. Click to focus on the `Default Shortcuts`, by default the focus is on the `User Shortcuts` panel
3. Open `Quick Outline/Goto Symbol` (Ctrl+Shift+O)
4. You see the results from the `User Shortcuts` and not the `Default` ones
5. If you hit `ESC` you can see the focus is on the `User Shortcuts` from the right panel

**Comment by kieferrm** [comment] 2016-12-16 19:29
Same is true for the settings editor.

**Comment by bpasero** [comment] 2016-12-18 07:45
I think this is OK behaviour because we want to move away from the left hand side of preferences and keybindings to work like a normal editor but rather something that we control the searching and filtering on using more explicit widgets (like the big search box). 

However, for keybindings we did not yet adopt any new UI to allow for searching, so it is a bit unfortunate that quick outline does not work there anymore. 

I do not understand why we treat this as candidate though, imho this should move to January.

**Comment by kieferrm** [comment] 2016-12-19 06:18
@bpasero when we made the changes we overlooked the Quick Outline style of navigating in keyboard shortcuts and settings. I.e. we broke established and efficient workflows without appropriate consideration. That makes this a regression.

**Comment by bpasero** [comment] 2016-12-19 10:07
Suggestion: go back to 2 editors for keybindings.

**Comment by sandy081** [comment] 2016-12-19 10:43
Agreed that disabling outline for Keybindings was not expected and was a side effect of moving to side by side editor. I will revert it to old behaviour of showing 2 editors for key bindings.

Disabling Quick outline/Go to Symbol/Go to line/Find was intentional in Default Settings. This was done in favour of new rich functionality in Default Settings.
- Advanced Search and filtering
- Rich Grouping

**Closed** 2016-12-19 10:44 UTC
Labels: bug, candidate
