### ISSUE TITLE
If you load a font with SVG data in the terminal, all language syntax will not work.

### ISSUE THREAD

**Issue by twinxx** [microsoft/vscode#139221] opened 2021-12-15 16:40 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.1
- OS Version:Darwin arm64 21.1.0

Steps to Reproduce:

If you load a font with SVG data in the terminal, all language syntax will not work.
Is this my problem?

**Comment by IllusionMH** [comment] 2021-12-15 17:07
Not sure what you mean under "load a font with SVG data in the terminal"

However sounds like duplicate of #100840 which is external issue (see https://github.com/microsoft/vscode/issues/100840#issuecomment-651365807)

Using font without SVG glyphs is best way to go.

**Comment by twinxx** [comment] 2021-12-15 17:22
코멘트 처럼 저는 이미 일부 SVG 를 변환해서 그문제를 해결했습니다만
그래도 그런문제가 발생할 필요가 없는 것처럼 보입니다
그 설정은 이것입니다.
Terminal › Integrated: Font Family
Editor: Font Family

**Comment by IllusionMH** [comment] 2021-12-15 17:27
/duplicate of #100840

VS Code built with Electron, which in turn uses chromium which incorrectly renders fonts on MacOS.
It won't be necessary when upstream issue fixed.

**Closed** 2021-12-15 17:27 UTC
Labels: *duplicate

**Comment by twinxx** [comment] 2021-12-15 17:33
/중복 #100840  OK
doesn't it change
Then I can change
