### ISSUE TITLE
Custom Windows menu bars introduces a grey window border when double click to maximize

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#54618] opened 2018-07-18 22:36 UTC
Custom Windows menu bars introduces a grey window border when double click to maximize. Spotted at OSCON

**Steps:**
Double click on custom menubar to maximize
Windows maximizes
Repeat
Grey border/bar appears

See video: https://photos.app.goo.gl/mqGX8289LUgZt5867

**Comment by sbatten** [comment] 2018-07-18 22:50
I believe this is a dupe of #52265, but please re-open with more info if I'm mistaken.

**Closed by sbatten** 2018-07-18 22:50 UTC
