### ISSUE TITLE
Wrongly accepting suggestions when entering Spread syntax

### ISSUE THREAD

**Issue by z-jeffry** [microsoft/vscode#130896] opened 2021-08-16 10:41 UTC
Hello!
When writing React code, I found that I would incorrectly accept the first suggestion when using Spread syntax。

Steps to Reproduce:
1. The language mode is react. Enter the first decimal point, a suggestion appears：

![Spread syntax in react](https://user-images.githubusercontent.com/45141759/129549705-cd486039-2ee5-4048-ba05-21a254f1f8c6.png)

2. Continue to enter the second decimal point. The first suggestion is automatically selected:

![image](https://user-images.githubusercontent.com/45141759/129549955-eea570a0-46ce-469d-a595-67f4dfe9bdc1.png)

I found that by closing the option `Accept Suggestion On Commit Character`, the problem disappeared

- VS Code Version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
- OS Version:Windows_NT x64 10.0.18363

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.89GB free)|
|Process Argv|--crash-reporter-id 1f623d58-d324-4797-9427-723926bb98c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-nginx-conf|ahm|0.1.3
Bookmarks|ale|13.1.0
project-manager|ale|12.3.0
gitee-code-settings-sync|Ale|0.1.20
vscode-color|ans|0.4.5
npm-intellisense|chr|1.4.0
cssrem|cip|2.4.3
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-drawio|hed|1.6.1
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
latex-workshop|Jam|8.20.2
svn-scm|joh|2.13.6
intellij-idea-keybindings|k--|1.4.5
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.15.0
vscode-language-pack-zh-hans|MS-|1.59.3
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.4.0
korofileheader|OBK|4.8.16
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.22
open-in-browser|tec|2.0.0
react-redux-es6-snippets|tim|2.1.0
luna-paint|Tyr|0.8.1
vscode-icons|vsc|11.6.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
project-tree|zhu|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747

```

**Comment by IllusionMH** [comment] 2021-08-16 11:05
/duplicate of #130096 which is candidate for July 2021 Recovery release

**Closed** 2021-08-16 11:06 UTC
Labels: *duplicate
