### ISSUE TITLE
Quick open doesn't respect "Enable Preview From Quick Open"

### ISSUE THREAD

**Issue by stephenpassero** [microsoft/vscode#129244] opened 2021-07-23 13:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: MacOS Big Sur v. 11.4

Steps to Reproduce: See attached .gif

Recently, I started noticing that quick open was opening tabs as a preview, instead of making them permanent. Togging the "Enable Preview From Quick Open" setting doesn't seem to have any affect, however.

If I disable preview completely, then tabs are made permanent, but that isn't what I want (I like preview in general, just not from quick open).

See this gif for an example of the problem:
![quickopen](https://user-images.githubusercontent.com/12648039/126791795-427e302b-f4e4-4bc2-9765-036dacadc7c8.gif)

Thanks!

**Comment by TylerLeonhardt** [comment] 2021-07-23 15:12
This is already fixed in the latest insiders. Please give insiders a go.

duplicate of #128755

**Closed by TylerLeonhardt** 2021-07-23 15:12 UTC
