### ISSUE TITLE
All Chinese characters entered in terminal are the same as those entered for the first time

### ISSUE THREAD

**Issue by amtoaer** [microsoft/vscode#112349] opened 2020-12-12 05:30 UTC
- VSCode Version:1.52.0
- OS Version:Arch Linux

Steps to Reproduce:

1.enter some characters

![2020-12-12_13-21](https://user-images.githubusercontent.com/32017007/101976151-6d769a80-3c7d-11eb-83f4-865ad13ae5d9.png)

2.enter other characters

![2020-12-12_13-22](https://user-images.githubusercontent.com/32017007/101976203-dc53f380-3c7d-11eb-8969-2ae961474651.png)

3.the characters entered for the second time are the same as those for the first time

![2020-12-12_13-22_1](https://user-images.githubusercontent.com/32017007/101976156-78312f80-3c7d-11eb-9b7a-dcbcbb1a370d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-12-14 16:56
Duplicate of #112060

**Closed by meganrogge** 2020-12-14 16:56 UTC
Labels: new release
