### ISSUE TITLE
Vscode seems to have problems with folder names with uppercase characters

### ISSUE THREAD

**Issue by TitaneBoy** [microsoft/vscode#74291] opened 2019-05-24 16:31 UTC
Version : 1.34.0 (user setup)
Validation : a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date : 2019-05-15T21:59:37.030Z
Électron : 3.1.8
Chrome : 66.0.3359.181
Node.js : 10.2.0
V8 : 6.6.346.32
OS : Windows_NT x64 6.1.7601

Hello people..I'm facing a particular issue... I have in my project a folder (named zeroMQ) with files inside, and sometimes, when editing some of these files, it seems to create kind of shadow files...I don't know how to explain..but here is a screenshot of what I can see sometimes

![image](https://user-images.githubusercontent.com/15614466/58338367-b5249f80-7e15-11e9-9410-8d19503fc932.png)

As you can see, in the file "client_base.ts" I was trying to edit, I've just added the getter "isConnect()" but it showed me there was 1 reference ..I didn't understand why vscode tells me there is 1 reference of this function since I've JUST created this function. By clicking on it, I could see what you can see on the screenshot... The only difference is in the "path" value, where in the up side, "zeroMQ" is writted with M and Q capitalized. But on the bellow side, "zeromq" has no uppercase characters. I think there might be an issue about this in vscode. I'm not sure that vscode manage correctly folder (or maybe files too) with uppercase characters.

And sometimes, in the file explorer of vscode, I can see the folder "zeroMQ" but not the files and folders inside it. It's really hard to reproduce manually...But it only happens with this folder (zeroMQ)

The structure of my project:

![image](https://user-images.githubusercontent.com/15614466/58338577-f9b03b00-7e15-11e9-9006-e9262fb9f84e.png)

**Comment by mjbvz** [comment] 2019-08-15 00:22
Duplicate of #71735

**Closed by mjbvz** 2019-08-15 00:22 UTC
