### ISSUE TITLE
Vs code using emmet syntax, when many times will be vscode automatically prompt interference, how to do

### ISSUE THREAD

**Issue by humuye** [Microsoft/vscode#25170] opened 2017-04-22 00:09 UTC
- VSCode Version: 1.11.2
- OS Version: window10

Steps to Reproduce:

Vs code using emmet syntax, when many times will be vscode automatically prompt interference, how to do?
When I press the tab key：
![rkoid](https://cloud.githubusercontent.com/assets/22143654/25299562/f3052522-2732-11e7-90bd-a1136537507a.gif)

**Comment by humuye** [comment] 2017-04-22 00:38
I want the same as ATOM
![atom](https://cloud.githubusercontent.com/assets/22143654/25299893/00d00a4c-2737-11e7-892c-3881896cd037.gif)

**Comment by ramya-rao-a** [comment] 2017-04-23 01:19
Duplicate of #24596

What is happening in your case is that snippet from the suggestion list gets expanded instead of the emmet abbreviation.

You have a couple of options for working around this.
See https://github.com/Microsoft/vscode/issues/1952#issuecomment-257811974 and https://github.com/Microsoft/vscode/issues/1952#issuecomment-293770991

We are also working on a way to get the emmet abbreviation expansion in the suggestion list itself.
That work is being tracked in #21943

**Closed by ramya-rao-a** 2017-04-23 01:19 UTC
Labels: emmet

**Comment by humuye** [comment] 2017-04-23 13:49
Thank you, have solved my problem

**Comment by ramya-rao-a** [comment] 2017-06-01 05:28
@humuye 

See https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464 for updates on this issue. You can now get emmet abbreviation expansion in the suggestion list without giving up on quick suggestions
