### ISSUE TITLE
GIT extension not working

### ISSUE THREAD

**Issue by janispinkis** [microsoft/vscode#116126] opened 2021-02-08 16:07 UTC
After upgrading to 1.53.0 on folders with git repository Source Control tab displays  "The folder currently open doesn't have a git repository". 
Expected behavior, Source Control tab shows status of the git repository (updated files, allows to commit and push etc)

Another issue with version 1.53.0. The Issue Reporter does not work. When selecting menu item HELP->Report Issue the Issue Reporting window is not opened.

My operating system is RedHat 7.9. 

After downgrading to Code 1.52.1 it works as expected.

**Comment by meganrogge** [comment] 2021-02-08 16:22
I'm not able to reproduce your Issue Reporter problem in Insider's. Can you try Insider's?

**Comment by RMacfarlane** [comment] 2021-02-08 16:24
@janispinkis Can you press F12 when you open the issue reporter and check if there is anything in the console there?

**Comment by gjsjohnmurray** [comment] 2021-02-08 16:36
@RMacfarlane see https://github.com/microsoft/vscode/issues/115784#issuecomment-775273645 in case @janispinkis is suffering from the same underlying issue, or if it's even RedHat7 related at all.

**Comment by janispinkis** [comment] 2021-02-08 16:37
> @janispinkis Can you press F12 when you open the issue reporter and check if there is anything in the console there?

F12 isn't working at all. When opening the terminal I'm getting the error mentioned by gjsjohnmurray

**Comment by gjsjohnmurray** [comment] 2021-02-08 18:32
Confirmation at https://github.com/microsoft/vscode/issues/115784#issuecomment-775307222 that the Report Issue problem is caused by the RedHat7 incompatibility problem. Maybe the git problem is too.

**Comment by michaellumley1** [comment] 2021-02-13 22:24
How can we provide more information to you? On RHEL 7.8 both v1.53.0 and v1.53.1, the git repositories are not recognised as janispinkis describes above. We've downgraded all our people to v1.52.

**Comment by RMacfarlane** [comment] 2021-05-07 16:14
Closing as a duplicate of https://github.com/microsoft/vscode/issues/115784

**Closed by RMacfarlane** 2021-05-07 16:14 UTC
Labels: needs more info
