### ISSUE TITLE
TS: move to file changes formatting

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74050] opened 2019-05-21 10:12 UTC
* have some TypeScript code
* select and trigger 'move to new file' code action
* :bug: the formatting is now completely off

**Comment by jrieken** [comment] 2019-05-21 10:12
this is a paper-cut-issue

**Comment by mjbvz** [comment] 2019-05-21 17:31
Duplicate of https://github.com/microsoft/TypeScript/issues/27294

**Closed by mjbvz** 2019-05-21 17:31 UTC
