### ISSUE TITLE
Comment line in HTML <script> should only use JS-style if cursor is within the tags

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18420] opened 2017-01-11 21:53 UTC
![image](https://cloud.githubusercontent.com/assets/2193314/21867911/2cbcab46-d805-11e6-9e31-49acd8ec861e.png)

ctrl+/

![image](https://cloud.githubusercontent.com/assets/2193314/21867923/3bb9b300-d805-11e6-97d3-bbd019475043.png)

**Comment by aeschli** [comment] 2017-01-12 00:28
duplicate of #18416

**Closed by aeschli** 2017-01-12 00:28 UTC
Labels: bug
