### ISSUE TITLE
Apply Extension to All Profiles keeps coming back

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#188788] opened 2023-07-25 14:06 UTC
Testing #188614

An extension I have installed for testing keeps getting the "Apply Extension to All Profiles" checked when I install it. I then uncheck it, uninstall the extension, reinstall the extension and it has this option checked again.

**Comment by chrmarti** [comment] 2023-07-25 14:08
Just noted that restarting VS Code between uninstalling and reinstalling the extension did not bring the checkmark back.

**Comment by sandy081** [comment] 2023-07-26 09:48
I cannot reproduce this. It works even without restarting. Can you please provide the steps?

**Comment by chrmarti** [comment] 2023-07-26 10:07
Cannot reproduce anymore. 🤷‍♂️

**Comment by sandy081** [comment] 2023-07-26 10:35
Ok, lets keep an eye and see if this can be reproduced. Closing this until then.

**Closed by sandy081** 2023-07-26 10:35 UTC
Labels: info-needed
