### ISSUE TITLE
Renaming file in Explorer leaves old name

### ISSUE THREAD

**Issue by benblank** [Microsoft/vscode#68732] opened 2019-02-14 20:04 UTC
Issue Type: <b>Bug</b>

I renamed a file using Explorer (clicking on the file, pressing Enter, and typing a new name).  The file renamed successfully on disk and on the editor tab, but only the old name shows in Explorer.

Clicking on the old name in Explorer pops up the message:

    Unable to open 'fsfacade-test.js': File not found (file:///Users/bblank/working/change-tracking/fs-tree-diff/tests/fs-tree/fsfacade-test.js).

…with a button to create the file.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|-psn_0_3121914|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
vscode-ember|emb|0.2.0
json-tools|eri|1.0.2
vsc-ember-cli|fel|0.3.3
language-haskell|jus|2.5.0
dotenv|mik|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
rust|rus|0.5.3
code-settings-sync|Sha|3.2.4
haskelly|UCL|0.5.5
vscodeintellicode|Vis|1.1.3

</details>

**Comment by fwcd** [comment] 2019-02-16 12:39
This might be a duplicate of #68316.

**Comment by isidorn** [comment] 2019-02-18 11:59
Dup of https://github.com/Microsoft/vscode/issues/68316

**Closed by isidorn** 2019-02-18 11:59 UTC
