### ISSUE TITLE
git sumbit input box crash when auto fetch

### ISSUE THREAD

**Issue by wingkung** [microsoft/vscode#113741] opened 2021-01-04 10:06 UTC
git sumbit input box crash when chinese input method actived，git auto fetch, can't focus

**Comment by RMacfarlane** [comment] 2021-01-04 18:32
Please include some more details, what version of VSCode are you using? Does this only happen when git auto fetch is on?

**Comment by wingkung** [comment] 2021-01-05 02:47
version 1.52.1, every time

**Comment by eamodio** [comment] 2021-01-05 06:16
Duplicate of #112621

**Closed by eamodio** 2021-01-05 06:16 UTC
