### ISSUE TITLE
HTML Formatting Breaks when ul tag has style attribute

### ISSUE THREAD

**Issue by g5codyswartz** [Microsoft/vscode#19617] opened 2017-01-31 09:37 UTC
- VSCode Version: 1.8.1
- OS Version: Mac OSX 10.11.6

Steps to Reproduce:

1. Create an HTML file, or a new blank file and choose HTML from the bottom right
2. Pase the following markup in:
```
<ul class="testing" style="color: black;">
<li></li>
<li></li>
<li></li>
</ul>
```
3. Run format document
4. **Expected**: the `li` tags should indent
5. Remove the `style` attribute from the `ul` tag
6. Run format document
7. Now it's working w/o the `style` attribute, the `li` tags will indent.

**Comment by aeschli** [comment] 2017-01-31 15:01
duplicate of #17849

**Closed by aeschli** 2017-01-31 15:01 UTC
