### ISSUE TITLE
Korea characters displayed overlapped in a teminal window.

### ISSUE THREAD

**Issue by leedonhyun** [Microsoft/vscode#7373] opened 2016-06-08 00:13 UTC
- VSCode Version: 1.2.0-insider 
   Commit 24e811aaa256f9d45c10fbe2491a5938f57482c0
   Date 2016-06-07T07:55:32.262Z
   Shell 0.37.6
   Renderer 49.0.2623.75
   Node 5.10.0
 
- OS Version: Windows 10

Steps to Reproduce:

1. 
![image](https://cloud.githubusercontent.com/assets/8449892/15878824/1e11457c-2d59-11e6-8457-db73927d8392.png)

2.

**Comment by Tyriar** [comment] 2016-06-08 00:21
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-08 00:21 UTC
