### ISSUE TITLE
Copy Paste Not Working

### ISSUE THREAD

**Issue by Vermasiddhant89** [microsoft/vscode#55303] opened 2018-07-28 15:31 UTC
Unable to copy and paste the on the same file, I am using Window 10 and 1.25.1 version of visual studio.

**Comment by blunatic** [comment] 2018-08-03 16:09
Also experiencing this all of a sudden. On Version 1.21.1 of VSCode using Mac OS High Sierra 10.13.6. Only started happening within the last few days.

A full close of VSCode doesn't seem to fix it either, and I've tried disabling all related copy and paste extensions (I use Clipboard History and Paste with Indent).

I've also been experiencing some issues with saving files immediately. I'll do cmd+s to save a file, and it seems to hang for a second or two before saving whereas prior the file would save immediately.

**Comment by ecbrodie** [comment] 2018-08-09 03:28
I am also experiencing this issue too. This time, it is more like I cannot copy ANYTHING from VS Code into my system clipboard. I am using VSCode 1.25.1 and MacOS 10.13.6. It also looks like an intermittent issue. Closing and reopening VSCode was enough for the issue to go away.

I was testing the reproduction by trying to copy text from VSCode and paste it into the address bar in Chrome.

**Comment by dpurge** [comment] 2018-08-27 09:27
I am on VSCode 1.26.1 on Win x64, upgraded a few minutes ago.
I have noticed that long command lines cannot be pasted because they are broken in the middle of the command by new line.

Example:

```
 Write-Host "11111 22222 33333 44444 55555 66666 77777 88888 99999 00000 11111 22222 33333 44444 55555 66666 77777 88888 99999 00000 11111 22222 33333 44444 55555 66666 7777
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 3000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()
```

For comparison, in the same window, shorter commands do work:

```
PS D:\src\prod\xxx> Write-Host "11111 22222 33333 44444 55555 66666 77777 88888 99999 00000"
11111 22222 33333 44444 55555 66666 77777 88888 99999 00000
PS D:\src\prod\xxx> Write-Host "11111 22222 33333 44444 55555 66666 77777 88888 99999 00000 11111 22222 33333 44444 55555 66666 77777 88888 99999 00000"
11111 22222 33333 44444 55555 66666 77777 88888 99999 00000 11111 22222 33333 44444 55555 66666 77777 88888 99999 00000
```

**Comment by andyg303** [comment] 2018-08-30 10:27
I had the same issue by the sounds of things. I could not copy / paste into or out of VS Code. (C&P internally was OK though).

For some reason doing the following fixed it on Mac:

- Go to /Users/YOUR_USER_NAME/Library/Application Support/Code/CachedData
- Delete all files, then restart VS Code.

Hope that helps others fix and/or helps root out the underlying cause.

**Comment by Vermasiddhant89** [comment] 2018-09-03 18:56
Hi There,

I have uninstall the VS code and restart the machine and again install the
updated version 1.26.1 ,

Now it is working fine on copy/paste the code.

You can also clear the cache before uninstalling .

Below are manual method to clear the cache from the machine.

Windows: C:\Users\<userid>\AppData\Roaming\Code\Local Storage

Linux: /home/<userid>/.config/Code/Local Storage

macOS: /Users/<userid>/Library/Application Support/Code/Local Storage

Thanks and Regards

Siddhant

**Comment by koliyo** [comment] 2018-11-27 09:56
I have the same problem in 1.29.1, on Mac

I have deleted all the vs code settings
- `~/.vscode`
- `~/Library/Application Support/Code`

And restarted VS Code.

But still can not access the global Mac clipboard.

I have not had this problem before.

**Comment by zheeeng** [comment] 2018-12-15 19:59
I encountered this issue just then and restarting my machine(mac os 10.11.6) resolved it

**Comment by bejota** [comment] 2019-01-09 17:24
On Linux (CentOS 7.2), deleting the contents of '/home/<userid>/.config/Code/Local Storage' worked the first time. Next occurrence, I had to delete the contents then reboot. 
It's happened again and the cause seems to be my attempt to paste from a PuTTY terminal into VS Code. VS Code hangs then a popup dialog asks to wait or kill. I am connecting remotely to the Linux server via PuTTY from Windows.

**Comment by moahammadalt** [comment] 2019-01-31 07:14
the same issue with windows 10, it was great when I stated using it but after this ugly bug I just disabled it, we need a major fix here.

**Comment by jdmr** [comment] 2019-02-08 15:06
Unfortunately I have the same problem. Upgraded to 1.31.0 and the paste on the explorer stopped working. I've restarted, removed the cache, even uninstalled/installed vscode and still can't get it to work. 

I've got macos mojave 10.14.2... Hopefully I can get this fixed before I have to reinstall my computer (VS Code is that important! Thanks for all the hard work)

**Comment by leopoldkristjansson** [comment] 2019-02-11 11:04
Had a copy paste problem now for months/maybe a year on my Windows machine. Restarting VS Code fixes it but it keeps popping up.

**Comment by kushalj** [comment] 2019-02-15 16:25
CMD-v paste was dying once a week but now dying every hour after Version 1.31.1 update. Quit and restart fixes it. But it's really a fix. How is this still a problem. It's been an issue on and off for well over a year.

**Comment by Xmetalfanx** [comment] 2019-02-23 21:47
I was just here troubleshooting a paste related issue and i found something that may be affecting others ... hoping a dev see's this as it may be related to an addon and not something (or maybe it is in vscode by default ... who knows) 

anyway, I looked through my extensions and searched for "paste" ... I disabled _paste JSON as code_ (100% added by me)  and _indent on paste_ (that is the one I am not sure if say _awesome-vscode_ added that one or if intend on paste is there in a default install ... anyway I did not remove that one i just disabled it .. paste is working again ... don't think i have any "paste" items in preferences changed from default settings ... 

Hoping this may help others and devs, when people ask about a similar "paste, is not working" issue

**Comment by Xmetalfanx** [comment] 2019-02-23 21:49
_awesome-vscode_

> CMD-v paste was dying once a week but now dying every hour after Version 1.31.1 update. Quit and restart fixes it. But it's really a fix. How is this still a problem. It's been an issue on and off for well over a year.

i just commented that I (not sure if its installed by default or not) disabled an extention "indent on paste" and paste seems to be working for me again ... I have different Linux distros installed and I think I was on another one when this happened before ... but it may be a simple ext. or ext that another one adds as a "dependency" that is causing the issue.

**Comment by Xmetalfanx** [comment] 2019-02-23 21:52
not 100% sure but i think this is the one i mean .. dont see why it wouldn't be (aka two ext. with the same name and there is another one) https://marketplace.visualstudio.com/items?itemName=gazugafan.vscode-indent-on-paste

**Comment by Xmetalfanx** [comment] 2019-02-23 21:53
sorry for "post spamming" but i saw https://github.com/gazugafan/vscode-indent-on-paste/issues/3 ... the dev is aware it seems

**Comment by kevmon** [comment] 2019-02-24 05:28
This has been an issue for me also, for well over a year.  I've tried everything from restarting VSC, testing extensions one-by-one, reformatting my Mac.

It typically happens a few times a day and I have to restart the workspace, but not the full app.  I can leave other projects open and only re-open the current one. 

I've noticed that it specifically happens after copying something in an HTML file, usually a class for some reason.  

When this happens, tab, paste, and all intellisense stops working.

**Comment by bug-z** [comment] 2019-03-05 08:06
> sorry for "post spamming" but i saw [gazugafan/vscode-indent-on-paste#3](https://github.com/gazugafan/vscode-indent-on-paste/issues/3) ... the dev is aware it seems

I tried to use it, but to no success - paste stops working the same with or without this app

**Comment by gongjiaji** [comment] 2019-03-15 04:15
well, I am pretty sure the problem is some "copy-paste" extensions on my MacBook. The function works as expected right after I shut the extension down. 
对于中文用户并且使用了欧陆词典自动取词功能的, 他这个功能的本质是复制粘贴, 最好把软件关掉再做尝试.

**Comment by bejota** [comment] 2019-03-20 21:30
Building on previous [comment](https://github.com/Microsoft/vscode/issues/55303#issuecomment-452779417), I'm using x2go to open a terminal on the remote linux box. 
Observations:
- I noticed that pasting into the x2go terminal was failing also. Restarting x2go & VS Code recovered paste functionality to both programs.
- Selecting any text in VS Code, then attempting to paste elsewhere in the editor always caused it to hang.

Potential solution (not sure if all, one or combination):
- I've disabled the following settings: Selection Clipboard, Drag And Drop, Copy On Selection

Still a bit quirky but clipboard and copy/paste are working as expected.

**Comment by MariuszDabrowski** [comment] 2019-03-25 15:52
Same issue here, looks like VSCode is not reading values from the system clipboard.

High Sierra 10.13.5
VSCode 1.32.3

**Comment by tim-rohrer** [comment] 2019-04-08 16:14
Mojave 10.14
VSCode 1.33.0

I disabled all extensions, deleted cache and restarted the computer. Logged back in and did a copy & paster in Notes. No problem. Pasted the same contents into a VSCode document. Worked.

Then tried copying something from the VSCode document, and pasting it. No go. 

Interestingly, `ctrl-click`, then copy does work. Only the shortcut `cmd-c` seems to be affected. I tried reassigning the shortcut (which is also used by seven other commands according to VSCode, but that didn't seem to help.

**Comment by p0fi** [comment] 2019-04-08 18:21
I have the same problem since a couple of days,… what the heck? 
Does anybody have a solution? No copy / past makes vscode basically unusable 😱

**Comment by bug-z** [comment] 2019-04-09 08:30
> I have the same problem since a couple of days,… what the heck?
> Does anybody have a solution? No copy / past makes vscode basically unusable scream

You've also disabled all extensions? I had just the same issue and disabled all extensions and it started working again... Though couldn't definitely find the extension causing the issue... Seems it is some roaming error.

**Comment by p0fi** [comment] 2019-04-09 11:03
I found the Issue!
For whatever reason I had a key chord defined where `cmd+c` was the starter. I noticed this after I saw in the status bar that it said: `cmd+c was pressed. Waiting for second key of chord` I could not find this chord in the Keyboard Shortcuts section of vscode when I searched for `cmd+c` since this search does not include chords containing the search query. I needed to look in the `keybinding.json` and found it there via `cmd+f` (find).

I removed this keybinding and now everything works again! 🎉 

After all I have no idea how I might have set this binding 🤷‍♂️

**Comment by WillLuce** [comment] 2019-04-22 03:05
> I found the Issue!
> For whatever reason I had a key chord defined where `cmd+c` was the starter. I noticed this after I saw in the status bar that it said: `cmd+c was pressed. Waiting for second key of chord` I could not find this chord in the Keyboard Shortcuts section of vscode when I searched for `cmd+c` since this search does not include chords containing the search query. I needed to look in the `keybinding.json` and found it there via `cmd+f` (find).
> 
> I removed this keybinding and now everything works again! 🎉
> 
> After all I have no idea how I might have set this binding 🤷‍♂️

This worked for me as well. I removed this setting in my `keybindings.json`
```
	{
		"key": "cmd+c cmd+a",
		"command": "search.action.collapseSearchResults"
	}
```

**Comment by caseyjconger** [comment] 2019-05-03 15:05
Bless your soul @p0fi

**Comment by gcacars** [comment] 2019-05-11 20:13
For me too. But the problem is not the keybinds, by context menu command I have the same problem.

**Comment by MelMacaluso** [comment] 2019-07-21 21:01
> I had the same issue by the sounds of things. I could not copy / paste into or out of VS Code. (C&P internally was OK though).
> 
> For some reason doing the following fixed it on Mac:
> 
> * Go to /Users/YOUR_USER_NAME/Library/Application Support/Code/CachedData
> * Delete all files, then restart VS Code.
> 
> Hope that helps others fix and/or helps root out the underlying cause.

This fixed it, cheers

**Comment by Xmetalfanx** [comment] 2019-07-25 19:48
It's been a while for me and I use vscode on different distro bases (not Windows) of Linux ... Arch, Fedora, OpenSuse, and Ubuntu bases ... with  the past few versions and no fixes (if i posted that above) needed ... I have NOT run into this issue, myself

**Comment by jreljac** [comment] 2019-10-16 00:31
This is happening to me as well

My setup

macOS 10.14.6
VSCode 1.39.2
[Alfred](https://www.alfredapp.com/) 4.0.5 (with clipboard history turned on)

I'll be fine then randomly `cmd+v` stops pasting after `cmd+c`

If I `cmd+v` and it breaks I look at my Alfred paste history what I was pasting over is listed first and what I had previously copied was listed second.  Seems like VS Code is now treating `cmd+v` as `cmd+c`.

Turning off Alfred does nothing.
Restarting VSCode tends to help.

My installed and active extensions are:
- alefragnani.project-manager
- be5invis.vscode-icontheme-nomo-dark
- bmewburn.vscode-intelephense-client
- formulahendry.auto-close-tag
- johnpapa.vscode-peacock
- oderwat.indent-rainbow
- Shan.code-settings-sync
- streetsidesoftware.code-spell-checker
- JasonReljac.theme-coda

**Comment by RhetTbull** [comment] 2020-03-14 15:31
I have this problem as well: 
VS Code Version: 1.42.1

MacOS 10.15.1

Installed extensions:
- Cameron.vscode-pytest
- DotJoshJohnson.xml
- Gruntfuggly.todo-tree
- ms-python.python
- tommorris.mako
- Tyriar.sort-lines
- vscodevim.vim

I've cleared the cache ( /Users/YOUR_USER_NAME/Library/Application Support/Code/CachedData) and restarted VS Code as others have suggested but that doesn't solve the problem.  Cmd-C works in every other app.

**Comment by xinzweb** [comment] 2020-04-15 16:59
Similar issue:

VS Code Version: 1.44.1

MacOS 10.15.4

Installed Extensions:
- C/C++ 0.27.0
- GitLens 10.2.1
- Go 0.13.1
- Live Share 1.0.1947
- Python 2020.3.71659
- Vim 1.13.1 (I used it to work around the issue within the editor)
- YAML 0.7.2

**Comment by domingowensnsoft** [comment] 2020-04-17 06:54
in the version 1.44.0 of VSCode IDE, when I use copy and paste, multiple repeats it. the VSCode will break it down and popup let me reopen. pls refix it. thanks

**Comment by adnanhz** [comment] 2020-04-24 09:56
I'm having the same problem on Windows 10.
Copying works fine.
Pasting works fine until it stops working suddenly.
Then I copy from VSCode and have notepad++ open for the sole purpose of pasting.

**Comment by xinzweb** [comment] 2020-04-24 16:39
> Similar issue:
> 
> VS Code Version: 1.44.1
> 
> MacOS 10.15.4
> 
> Installed Extensions:
> 
> * C/C++ 0.27.0
> * GitLens 10.2.1
> * Go 0.13.1
> * Live Share 1.0.1947
> * Python 2020.3.71659
> * Vim 1.13.1 (I used it to work around the issue within the editor)
> * YAML 0.7.2

Well, update on my end. I only experience this issue with `brew cask` install. After I removed the `brew cask` install, and then just use the download from the visual studio code (suppose to be the same thing, but maybe different way of installation), then I don't have copy-paste issue anymore.

I don't know what exactly caused the copy-paste issue for the `brew cask` install then.

**Comment by sageetheba** [comment] 2020-04-30 10:41
I have same issue but if we use "Ctrl"+"Shift"+V  ...it will work in visual studio code

**Comment by CocoBeezy** [comment] 2020-05-05 21:24
> I have same issue but if we use "Ctrl"+"Shift"+V ...it will work in visual studio code
> 
> if You installed "VIM" extension in Your VS Code then UnInstalled it .
> its work for me.

Yup yup. This is the same issue I have had and how I had to resolve it. It only happens on Windows for me. In order to use copy + paste, I have to be in vim's insert mode.

**Comment by mitchdubdub** [comment] 2020-05-14 22:01
looks like this issue https://github.com/VSCodeVim/Vim/issues/4149  was re-introduced into the current

**Comment by tobiashochguertel** [comment] 2020-05-15 13:11
It looks fot me that VSCode does not share the same clipboard like mac Os. because I can copy and paste inside of VSCode, but I can't paste content which copied from outside of VSCode (Opera Touch, Sublime Text and so on..).

**Comment by cnjdk** [comment] 2020-05-18 20:26
After fighting VSCODE 1.45.1 on Windows 10 with PHP code with Unix LF and UTF8 encoding for days, I was able to replicate this problem in Notepad++ with VSCode closed. Seems that it has to do with encoding of white space when you copy-paste into another editor and then back.  I was using UTF8 but when I changed the code to ANSI, weird white space characters showed up. After I deleted them everything worked fine.

**Comment by totszwai** [comment] 2020-07-23 14:14
Happening with the latest. Cannot copy paste from the explorer panel. Was working before. It just greyed out.
![image](https://user-images.githubusercontent.com/4440365/88296939-51be2800-cccd-11ea-8add-eb2d6c7fa17a.png)


Version: 1.48.0-insider (user setup)
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:50:56.947Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by rochelryu** [comment] 2020-07-27 11:18
**SAVE ALL PROBLEMS WITH GOD INSTRUCTIONS (god:save, god:...paste, god:....cut, god:...copy)**
1 - cmd + Shift + P
2 - search this : >God: Create .editorconfig
3 - Select this.

GOD INSTRUCTIONS is ready........

**Closed** 2020-10-22 11:30 UTC
Labels: editor-clipboard, needs more info
