### ISSUE TITLE
Cannot open/save Jupyter notebook on Linux (chrome-os Debian)

### ISSUE THREAD

**Issue by hennievn** [microsoft/vscode#130585] opened 2021-08-11 00:47 UTC
Open code-insiders.  Ctrl-Shift-P - New Jupyter Notebook.  Try to save this new notebook; any filename.  This will produce a Failed to save error message.

Alternatively open any existing notebook.  This will open the file and show the JSON? source as a text file instead of opening the Notebook with the Jupyter extension.

I suppose Chromebooks and their built-in linux environments are still a bit of an edge case, below is my system info:
Linux penguin 5.4.131-16014-ge3ef2add98ca microsoft/vscode-jupyter#1 SMP PREEMPT Sat Jul 31 20:32:18 PDT 2021 x86_64 GNU/Linux

**Comment by roblourens** [comment] 2021-08-11 19:44
@hennievn are there any other error details in the devtools console? (Help > Toggle developer tools). And when you open the notebook and get the text editor, does it show an error?

**Comment by hennievn** [comment] 2021-08-12 00:33
@roblourens the screenshot below shows the console messages from Code clean startup, creating a new notebook and attempting to save twice.  On Code startup there is already two "Devtools failed to load source map" errors. I'm not sure what the failure to locate pip indicates, my conda environment includes pip.

When you create a new notebook you do not get any error messages in the editor and you can execute code fine.

![Screenshot 2021-08-11 7 25 09 PM](https://user-images.githubusercontent.com/3038425/129120211-f4489027-d4bf-47c8-94b8-4803e29b58ec.png)

**Comment by Li-fAngyU** [comment] 2021-08-12 05:41
@roblourens It is ok run in chromebook.
the loading issue appears when i am ssh my server and run .ipynb file on that server. this issue has not happened before. 
but today it seems ok. i don't know what cause the loading issue. and i can sure the program does not fall into an endless loop or read a large amount of data or calculate.

by the way the save issue it still have.
![QQ图片20210812134118](https://user-images.githubusercontent.com/56572498/129144048-b9deb2b8-ebeb-4690-85a7-dc43c211abc4.png)

**Comment by roblourens** [comment] 2021-08-20 17:59
Duplicate of https://github.com/microsoft/vscode/issues/130428

**Closed by roblourens** 2021-08-20 17:59 UTC
Labels: bug, important, notebook
