### ISSUE TITLE
Ctrl+s 

### ISSUE THREAD

**Issue by nearxu** [Microsoft/vscode#30772] opened 2017-07-15 18:19 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|1.0.1
beautify|Hoo|1.1.1
docthis|joe|0.4.7
vscode-react-templates|kko|0.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-icons|rob|7.10.1
react-beautify|tai|0.3.0
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1

  <
            div className = "bank-item-r"
            style = {
                { borderBottom: "0px" }
            } >
            <
            div className = "bank-name" >
            <
            span > { this.cBankInfo.bk_nm } { Reg.bankCardHide2(this.cBankInfo.cc || "") } < /span> <
            em > { this.cBankInfo.bk_tp == 1 ? "储蓄卡" : "信用卡" } { this.cBankInfo.op_bk ? "快捷" : "" } < /em> < /
            div > <
            span className = "small-btn-orange"
            onTouchTap = { this.recharge.bind(this) } > 充值 < /span> < /
            div > <
            /div>

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by nearxu** [comment] 2017-07-15 18:21
我的设置不知道改了什么，导致了 ctrl+s 不是保存，变成html标签换行了，急急急。卸载重装还是这样

**Comment by nearxu** [comment] 2017-07-15 18:26
现在是只要保存文件就出现

for example

 render() {
        return ( <
            div className = "yc-abus" >
            <
            section className = "bank-header" >
            <
            PageHeader url = "#/setting"
            title = "关于我们" / >
            <
            div className = "ab-des" >
            <
            div className = "logo-img" > < img src = { require("../../../img/connact_logo.png") }
            /></div >
            <
            div >

**Comment by nearxu** [comment] 2017-07-15 18:33
已经解决了，是由于 JS-CSS-HTML Formatte插件引起的，建议直接封掉，浪费了一个小时

**Comment by mjbvz** [comment] 2017-07-17 19:56
Closing as caused by the `vscode-JS-CSS-HTML-formatter` extension

**Closed by mjbvz** 2017-07-17 19:56 UTC
Labels: caused-by-extension, javascript, new release
