### ISSUE TITLE
Keywords are not getting highlighted with 0.10.10 release

### ISSUE THREAD

**Issue by mistyharsh** [Microsoft/vscode#3946] opened 2016-03-10 04:15 UTC
Just updated my Visual Studio Code to 0.10.10. It not longer highlights JavaScript keywords  like function, let, const, yield, etc.

Details:
OS: Linux Mint 17.3 64 bit
Code: 0.10.10 64 bit

**Comment by mistyharsh** [comment] 2016-03-10 09:24
Checked on Windows 7 as well. I can see the same issue.
![error](https://cloud.githubusercontent.com/assets/4905303/13664950/03573ffe-e6d0-11e5-9b8d-08ac431013e2.jpeg)

**Comment by aeschli** [comment] 2016-03-10 09:34
duplicate of https://github.com/Microsoft/vscode/issues/3903

**Closed by aeschli** 2016-03-10 09:34 UTC

**Comment by aeschli** [comment] 2016-03-10 09:57
Workaround is to switch to the Light+/Dark+ theme...

**Comment by mistyharsh** [comment] 2016-03-10 12:30
Thanks, dark+ and other themes works.
