### ISSUE TITLE
Language server hanging and CodeHelper process going zombie

### ISSUE THREAD

**Issue by duro** [Microsoft/vscode#40225] opened 2017-12-14 19:14 UTC
- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Launch VSCode
2. Run into some kind of Linter error, or other language server error

Reproduces without extensions: No

For the last several days, I have been getting frequent hangups where the language server stops responding, and causes VSCode to go pretty dumb. No new linter errors come back, the built in JS validation starts returning incorrect results, intellisense stops working, my CPU spikes, and I have to restart VSCode to get any of those things to work again. After I close VSCode, I can see CodeHelper still running and 100% CPU, and have to force quit the process. It has been happening more and more frequently.

New to debugging an issue like this, so if there is more info you need, let me know.

**Comment by dbaeumer** [comment] 2017-12-15 09:45
@bpasero assigning to you. The CodeHelper process under Mac is the file watcher. If not please assign back.

**Comment by bpasero** [comment] 2017-12-16 08:34
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Closed** 2017-12-23 09:05 UTC
Labels: freeze-slow-crash, needs more info
