### ISSUE TITLE
Top menu not showing properly in OS Dark Theme after update

### ISSUE THREAD

**Issue by manueltorrez** [Microsoft/vscode#63212] opened 2018-11-15 12:48 UTC
Issue Type: <b>Bug</b>

The top menu (where "Files", "Edit", "Selection", etc. go) is not showing properly under OS Dark Theme. 
I'm currently using Vertex Maia in XFCE and it was displaying right before the update. Now it's showing the words in black.

![screenshot_2018-11-15_06-51-01](https://user-images.githubusercontent.com/22844772/48553864-64e6e680-e8a2-11e8-9bd8-e4f5cdda344b.png)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.17.19-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E2-7110 APU with AMD Radeon R2 Graphics (4 x 1623)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 1|
|Memory (System)|3.33GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
material-icon-theme|PKi|3.6.0
LiveServer|rit|5.1.1

(2 theme extensions excluded)

</details>

**Comment by eyal0803** [comment] 2018-11-15 13:31
I also have this after the v1.29 update. I'm running Arch Linux and GNOME with Arc-Darker GTK theme.

**Comment by stormprograms** [comment] 2018-11-15 14:23
I'm also having this issue on Ubuntu 18.10

**Comment by sbatten** [comment] 2018-11-15 22:20
duplicate of https://github.com/Microsoft/vscode/issues/62593

Please see https://code.visualstudio.com/docs/setup/linux#_low-contrast-menu-bar for info and fix for this issue.

**Closed by sbatten** 2018-11-15 22:20 UTC
Labels: new release
