### ISSUE TITLE
Add setting to disable copy with syntax highlighting

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#21820] opened 2017-03-02 19:24 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 10

There doesn't seem to be a way to turn off the default behavior of copy/pasting with syntax highlighting.  Some users may have a workflow where they want to paste text into an external rich edit text box (like a web form) without the extra formatting but there doesn't seem to be a way to turn this off right now.

/cc @rebornix @RamblingCookieMonster

**Comment by yfdyh000** [comment] 2017-05-24 14:26
Duplicate of #21071.

**Comment by jamesfancy** [comment] 2017-09-03 04:06
There are two actions in VSCode:

* `editor.action.clipboardCopyAction`
* `edtior.action.clipboardCopyWithSyntaxHighlightingAction`

We can bind one of them to <kbd>Ctrl+C</kbd>. So that if `clipbordCopyAction` does copy without formatting, everything would be okay.

**Comment by melipharo** [comment] 2017-11-15 10:58
It seems that this does not works on 1.18.0. I've set those variables in "keybindings.json":
`
{
    "key": "ctrl+shift+alt+c",
    "command": "editor.action.clipboardCopyWithSyntaxHighlightingAction"
},
{
    "key": "ctrl+c",
    "command": "editor.action.clipboardCopyAction"
}
`
but when I'm hitting `Ctrl+C` and pasting the clipboard in the rich edit (such as web form or a word/excel), I've got the highlighted text instead of just the text only. The `ctrl+shift+alt+c` does the same thing as the `Ctrl+C`.

**Comment by tatoosh** [comment] 2018-01-25 11:49
How to get it working to copy without format?

**Comment by AlGantori** [comment] 2018-04-01 17:32
How to get it working to copy without format?

**Comment by ioma8** [comment] 2018-04-10 14:12
Hello, please how do I set copy to not pick up formatting???

**Comment by xan1000** [comment] 2018-05-16 06:38
In case anyone else comes here - I still haven't found an answer to this outside work arounds, e.g., pasting the clipboard into a plain-text file and copying it again. I made an extension called "CopyPlainText" as a less annoying work around which adds a command palette for this.

**Comment by tatoosh** [comment] 2018-05-16 08:49
Thx @xan1000 - ur extension is working well for me

**Comment by ioma8** [comment] 2018-05-16 08:53
Thx for creating extension for this @xan1000 , I will check it.

**Comment by melipharo** [comment] 2018-05-21 03:36
@xan1000 wow thx a lot! It just works.

**Comment by rsyring** [comment] 2018-08-22 01:27
I'd just like to point out that I really think this is a bug with respect to the default behavior of VS Code.  Right now, we have two commands:

1. Copy: editor.action.clipboardCopyAction (CTRL + C default binding)
2. Copy with Syntax Highlighting: edtior.action.clipboardCopyWithSyntaxHighlightingAction

To me, that would imply that the plain "Copy" is copy without syntax highlighting.   But that doesn't seem to be the case.

**Comment by ioma8** [comment] 2018-08-22 08:07
Yes this is bug and needs attention!

**Comment by linhtto** [comment] 2018-08-29 00:18
This shouldn't be hard to fix, so I hope it'll happen soon!

**Comment by ioma8** [comment] 2018-08-29 07:10
I would help us all. We want to be happy users of Visual Studio code. How
should we help to make it solve?

st 29. 8. 2018 v 2:19 odesílatel linhtto <notifications@github.com> napsal:

**Comment by rebornix** [comment] 2018-09-05 21:27
With this great PR https://github.com/Microsoft/vscode/pull/54155, we can now disable the copy with syntax highlighting behavior by setting `editor.copyWithSyntaxHighlighting` to `false` from tomorrow's Insiders and next Stable. Command "Copy With Syntax Highlighting" would always work not matter of the value of this setting, so you can bind another specific keybinding for this command.

Lastly thanks for all your patience, feedback and great contribution to this issue. Happy Coding!

**Closed by rebornix** 2018-09-05 21:27 UTC
Labels: editor-clipboard, feature-request

**Comment by ioma8** [comment] 2018-09-06 07:18
Thanks a lot guys for fixing this!! Rly appreciate this.

**Comment by danvoyce** [comment] 2018-09-15 10:45
Not working for me in 1.27.2

**Comment by rebornix** [comment] 2018-09-16 19:54
@danvoyce it will work with next Stable version 1.28. For now you need to use Insiders version.
