### ISSUE TITLE
Regex Search Query Causes Crash

### ISSUE THREAD

**Issue by bordrboy** [microsoft/vscode#184343] opened 2023-06-05 16:06 UTC
Type: <b>Bug</b>

Reproducible steps (1... 2... 3...) that cause the issue:
1. Create a file with the following single line:
```
const test = { thing: "hello" }
```
2. Do a find in that file, with 'Use Regular Expression' selected: `(.*)+x`

UI freezes up and user gets the following message over and over indefinitely
![image](https://github.com/microsoft/vscode/assets/7196249/65c4e8fb-d6f8-44e7-96b4-9ff66abce74e)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.68GB free)|
|Process Argv|C:\\Users\\mwalter6\\Documents\\Projects\\ALQ213Trainer\\git_alq213trainer\\alq-213-trainer --crash-reporter-id 70c4b227-dd68-48df-ba61-bff724432f08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.0
gitlens|eam|13.6.0
prettier-vscode|esb|9.13.0
regexp-preview|Lou|0.1.5
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.1
csharp|ms-|1.25.8
powershell|ms-|2023.5.0
code-spell-checker|str|2.20.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30739705
pythonnosm12tcf:30757130

```

</details>

**Comment by andreamah** [comment] 2023-06-05 18:19
should be /duplicate of https://github.com/microsoft/vscode/issues/30874

**Closed by andreamah** 2023-06-05 18:19 UTC
