### ISSUE TITLE
split project settings from local settings in settings.json

### ISSUE THREAD

**Issue by chrisroat** [microsoft/vscode#101767] opened 2020-07-05 21:43 UTC
The `.vscode/settings.json` file seems to contain project settings that I might want to share with other developers (e.g., `python.testing.pytestEnabled`) and settings specific to my machine (e.g., `python.pythonPath`).  Can these be separated, so that project settings are more easily committed to a source code repo?

**Comment by roblourens** [comment] 2020-07-06 02:51
The settings that are specific to your machine can go in your User settings.json. Does that work for you?

**Comment by yume-chan** [comment] 2020-07-06 02:53
Duplicate of #40233

**Closed** 2020-09-24 13:43 UTC
Labels: needs more info

**Comment by chrisroat** [comment] 2020-09-25 02:22
@roblourens No problem closing this is favor the duplicate.

However, we should distinguish "user" settings, "project" settings, and "user-project" settings, for lack of better words.  You are correct that I should place my user settings in my User settings.json.

However, things like pythonPath are a "user-project" type of setting.  It depends on my machine, belongs in the project folder, but is not a global "user" setting.

**Comment by roblourens** [comment] 2020-09-25 15:58
The easiest way to get "user-project" settings are to use a workspace with those settings: https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by chrisroat** [comment] 2020-09-25 16:02
I do use multi-root workspaces.  Each root gets its own pythonPath (it may have different virtualenv because of different package dependencies), which is something I'd prefer not to check-in to a repo.  On the other hand, other settings I do want to have checked in for each root.  

Having all these settings in one file is the rub, as far as version control is concerned.

**Comment by roblourens** [comment] 2020-09-25 16:05
I understand the pain, I think this is basically a known issue but FYI @sandy081 in case you have anything to add
