### ISSUE TITLE
Support format for handlebars file

### ISSUE THREAD

**Issue by sulhome** [Microsoft/vscode#1735] opened 2016-01-01 21:53 UTC
although VS Code recognize that the markup is indeed handlebars, it is unable to format it. 
So format code option does nothing

**Comment by bpasero** [comment] 2016-01-03 12:01
It is currently just not implemented.

**Comment by sulhome** [comment] 2016-01-03 13:19
@bpasero thank you

**Comment by gpluta** [comment] 2016-01-16 21:29
@bpasero is it on the roadmap though?

**Comment by egamma** [comment] 2016-01-16 22:14
@gpluta not on the immediate roadmap and it depends on contributions from the community.

**Comment by gpluta** [comment] 2016-01-16 22:15
@egamma Thanks for clarifying!

**Comment by v3ss0n** [comment] 2017-04-08 18:03
Ember Handlebar templates are having very bad format in VSCode , that is only one thing i am going back to atom.
All the existing extensions can't do it well too. Would be very nice vscode look into it. Over a year now.

**Comment by mjbvz** [comment] 2017-11-08 23:30
Duplicate of #7011 / #32916 (I know this issue is older, but those two issue seem to have more relevant information on them)

**Closed by mjbvz** 2017-11-08 23:30 UTC
Labels: feature-request
