### ISSUE TITLE
UNTITLED (WORKSPACE) being shown as workspace title on opening two projects in version 1.18.0

### ISSUE THREAD

**Issue by saurabhpati** [Microsoft/vscode#37876] opened 2017-11-09 05:21 UTC
- VSCode Version:1.18.0
- OS Version:Windows 7

Steps to Reproduce:

1. Open Visual studio code and open any project.
2. Drag and drop another project.

Expected: The workspace title should not be UNTITLED (WORKSPACE)
Actual: The workspace title is UNTITLED (WORKSPACE)
Suggestion: 
1. Ask the user for a workspace title which will remain constant till the user closes the editor.
OR
2. Change the title of workspace the depending on the current active project the user is working on.
(as soon as he switches to another project, change the title of workspace to reflect the change.)

Personal Suggestion as a VS Code Fan: If the suggestion number 2 interferes with the editor's light weight features, don't do it. Really like the new features.

Cheers.
 

Reproduces without extensions: Yes

Screen shot for reference:
![issue](https://user-images.githubusercontent.com/20544414/32589681-f773a78a-c53b-11e7-808d-897ad391374c.jpg)

**Comment by unional** [comment] 2017-11-09 05:49
One solution is to name it "new workspace" or "unsaved workspace"

**Comment by isidorn** [comment] 2017-11-09 10:24
Personally not a big fan of either of those ideas. Option 1 makes the whole operation more heavy than it should be. Option 2 would give the notion of the master folder which we try to avoid in the explorer.

As for @unional suggestion I prefer our current solution since it alligns well with out Untitiled file semantic.

Assigning to @bpasero and @sandy081 to make a decision here but I feel we should close this as designed.

**Comment by sandy081** [comment] 2017-11-09 17:21
Yes, We chose `Untitled` to be consistent with what we have currently. I would close this as designed

**Closed by sandy081** 2017-11-09 17:21 UTC
Labels: workbench

**Comment by bpasero** [comment] 2017-11-10 05:57
@saurabhpati use File > Save Workspace to give the workspace a name and location.

**Comment by saurabhpati** [comment] 2017-11-25 14:09
@bpasero Got it, Thank You!.
