### ISSUE TITLE
runtimeVersion error only mentions nvm-windows

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#44632] opened 2018-02-27 19:02 UTC
Issue Type: <b>Bug</b>

Testing #44452

**Steps to reproduce**
1.  Install NVS
1. Don't use NVS
1. Try launching:

    ```json
    {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch test",
                "runtimeVersion": "9.6.1",
                "program": "${workspaceFolder}/index.js"
            }
        ]
    }
    ```

**bug**
Error message says:

```
Attribute 'runtimeVersion' requires Node.js version manager 'nvm-windows' (no environment variable 'NVM_HOME').
```

It does not mention that nvs is also supported. 

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (17.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces only with extensions

**Comment by weinand** [comment] 2018-02-27 19:05
duplicate of https://github.com/Microsoft/vscode/issues/44605

**Closed** 2018-02-27 19:06 UTC
Labels: *duplicate, debug, insiders
