### ISSUE TITLE
Debug toolbar contributed action visibility not updated on context key change

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#69398] opened 2019-02-25 19:13 UTC
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69196

When setting a `when` clause on the command, it seems to be evaluated when the toolbar is shown, but then not revaluated when the underlying context key updates.

```
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		],
		"menus": {
			"debug/toolbar": [
				{
					"command": "extension.helloWorld",
					"group": "navigation",
					"when": "inZenMode"
				}
			]
		}
```

For this snippet, if starting debugging while in zen mode the command is shown, but toggling zen mode after that does not remove the command.

VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.2.0

</details>

**Comment by isidorn** [comment] 2019-02-26 10:37
Yes, this is by design.
We only update the toolbar when a step event occurred.
Leaving this open for now as a feature request and we see if more people request it.

**Comment by DanTup** [comment] 2019-04-09 12:37
I've just discovered this too :(

This is quite annoying - we can't tell whether an app supports Hot Reload until it starts up and the debugger registers its services. Is there any workaround we can use to force an update?

**Comment by DanTup** [comment] 2019-04-09 12:38
Also - touchBar has the same issue - should I open a new issue, or would fixing this fix them both?

**Comment by isidorn** [comment] 2019-04-11 14:12
No there is currently no workaround.
This is the limitation of the design of the debug toolbar and the touchBar. We only update actions on debug state change.
No need to open another issue.

**Comment by DanTup** [comment] 2019-07-18 14:42
@sandy081 I saw elsewhere that there was some support for enabling/disabling items? Would that help here (eg. be able to disable the buttons without removing them)?

**Comment by sandy081** [comment] 2019-07-19 09:21
Do you mean hiding activity/status bar actions? Same thing can be done but this will cause inconsistency as then I would expect I can hide actions everywhere.

**Comment by DanTup** [comment] 2019-07-23 08:39
I meant I remember seeing some info on being able to enable/disable commands (https://github.com/microsoft/vscode/issues/21131?).. I wondered whether the debug toolbar supported this (I'm still looking for a way to either disable or hide a button from my debug toolbar after the debug session launches).

**Comment by sandy081** [comment] 2019-07-23 10:43
If it is a menu item then the enablement/disablement should be supported OOB.

**Comment by DanTup** [comment] 2019-07-23 10:55
It's a debug toolbar item (which lives inside the `menu` section - was shown in the JSON at the top here). Above you said:

> We only update actions on debug state change

So I wasn't sure whether that also applied to enabled/disabled state too? Eg. if we add something like `"precondition": "myContext == 42"` to a command that is added to the debug toolbar, should it update automatically when the context changes?

**Comment by sandy081** [comment] 2019-07-24 08:56
I do not know how debug tool bar actions are implemented. I would wait for @isiorn as he is on vacation and will be back soon.

**Comment by DanTup** [comment] 2019-07-24 13:16
Will do, thanks!

**Comment by DanTup** [comment] 2019-08-20 08:46
@isidorn do you know the answer to the above? If we can't toggle visibility of debug toolbar actions with contexts, are we able to toggle their enabled state?

**Comment by isidorn** [comment] 2019-08-20 08:48
Toggling their enablment state is also not supported I think. You can try it out and let me know if it works.

**Comment by DanTup** [comment] 2019-08-20 09:03
I put `"enablement": "false"` on one of my commands, but it still works on the debug toolbar, so I guess enablement isn't supported at all (not just that it can't be toggled once the bar is visible). Is that a bug?

**Comment by isidorn** [comment] 2019-08-20 09:13
It is not supported, we never wrote code to support that so it is a feature request. Thought this one would first have to be tackled.

**Comment by DanTup** [comment] 2019-08-20 09:29
Out of the two, I'd much rather have this one supported. Currently it's not possible to dynamically show/hide debug actions based on capabilities of the app being debugged (assuming you can't tell the capabilities until the app is launched). I don't use enablement - I just wondered if it might've been a somewhat workaround for this.

**Comment by isidorn** [comment] 2020-07-30 15:38
Somebody smart fixed this. I think @connor4312 
Thus closing

**Closed by isidorn** 2020-07-30 15:38 UTC
Labels: debug, feature-request

**Comment by DanTup** [comment] 2020-07-30 15:53
Awesome, thanks!

(the PR was https://github.com/microsoft/vscode/pull/93531)
