### ISSUE TITLE
Editor Foreground Faded Yellow

### ISSUE THREAD

**Issue by spolat** [Microsoft/vscode#32373] opened 2017-08-12 12:30 UTC
Hi everyone I'm using Vs code on ubuntu an os x. At os x everything is normal but at ubuntu when I'm opening vs code foreground color is faded yellow could you please help me how can ı increase color vividness 

Here how is my editor looks like

![image](https://user-images.githubusercontent.com/25878632/29240694-1342961a-7f73-11e7-8873-7cae82b849be.png)

**Comment by aeschli** [comment] 2017-08-14 08:23
IMO it has to do with the font used, which is different on every platform.

**Comment by aeschli** [comment] 2017-08-14 08:24
@bpasero We can't change the workbench font, right?

@spolat You might want to also try out some of the other themes.

**Comment by spolat** [comment] 2017-08-14 11:01
@aeschli I already tried other themes.  Nothing changed.  I thought it might be a problem from my monitor, but in other editors everything is normal

**Comment by bpasero** [comment] 2017-08-15 06:11
@spolat does it change anything if you run "code --disable-gpu"?

**Comment by spolat** [comment] 2017-08-18 19:26
@bpasero sorry for late reply. I tried your command. Nothing changed.

**Comment by spolat** [comment] 2017-08-18 20:50
@bpasero can you help about how can I change foreground color?

**Comment by bpasero** [comment] 2017-08-21 09:57
@spolat I am out of ideas why you see this on Linux. Maybe someone else has ideas. We have no way of changing the overall color in VS Code other than https://code.visualstudio.com/docs/getstarted/theme-color-reference

/cc @Tyriar

**Comment by Tyriar** [comment] 2017-08-21 18:27
Duplicate of https://github.com/Microsoft/vscode/issues/5742

**Closed by Tyriar** 2017-08-21 18:27 UTC
Labels: needs more info
