### ISSUE TITLE
Allow to write to a file without permission after authentication

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [Microsoft/vscode#1779] opened 2016-01-04 23:53 UTC
VS code on my Mac cannot save modified files suddenly. I tried restarting VS Code and MAC itself, but none brought saving back. It keeps popping this dialog when I cmd + S to save a file.

More information:
VS version: 0.10.6
<img width="891" alt="vscode unable to save files 3" src="https://cloud.githubusercontent.com/assets/10081208/12103906/3f34763a-b2fb-11e5-8198-90c9ee1a83ab.png">
<img width="921" alt="dev information 3" src="https://cloud.githubusercontent.com/assets/10081208/12104351/849b4ab0-b2ff-11e5-883e-51a54b641cb3.png">

**Comment by bpasero** [comment] 2016-01-05 12:01
@HuanhuanSunMSFT did something change with your permissions? can you save with another editor?

**Comment by HuanhuanSunMSFT** [comment] 2016-01-05 18:14
@bpasero I can save with Sublime 3. But I guess something permissions related did happen because when I save with Sublime 3, I need to input my password. However, I checked the file properties, it's **not** read only.

**Comment by bpasero** [comment] 2016-01-05 18:27
@HuanhuanSunMSFT this indicates that you are not the owner of the file and currently we do not support entering password during write.

**Comment by HuanhuanSunMSFT** [comment] 2016-01-05 18:30
@bpasero that's interesting. How come I'm not the owner of this file? Though it may not be related to VS Code, how could I get into this state and get out of it?

**Comment by bpasero** [comment] 2016-01-05 18:34
I have no clue but this does not sound like something to discuss in the VSCode issue tracker.

**Comment by bpasero** [comment] 2016-01-05 18:34
rather StackOverflow :+1:

**Comment by lukewhitehouse** [comment] 2017-07-10 10:19
@bpasero Hey, just picking up on this one too. Is the idea of password prompts for saving files you don't have permission for on the roadmap for vscode? This was super useful when I used Sublime Text and I was editing `/etc/hosts` files, etc.

**Comment by isidorn** [comment] 2017-11-17 09:59
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by lukewhitehouse** [comment] 2017-11-17 11:19
@isidorn That's a shame but understand there are bigger fishes to fry. Is there anyway you can keep this tracked though, just closing the issue and pretending it doesn't exist just disregards those of us who are looking to have this fixed?

**Comment by isidorn** [comment] 2017-11-17 11:25
Sure, we can reopen and put to backlog to keep track

**Comment by lukewhitehouse** [comment] 2017-11-17 11:31
@isidorn Very much appreciated, thanks!

**Comment by bpasero** [comment] 2017-12-03 15:54
/duplicate of https://github.com/Microsoft/vscode/issues/1614

**Closed by bpasero** 2017-12-03 15:54 UTC
Labels: *duplicate, feature-request, run-as-admin
