### ISSUE TITLE
Associating a custom icon to my language extension 

### ISSUE THREAD

**Issue by NavnathKumbhar** [Microsoft/vscode#70393] opened 2019-03-13 12:18 UTC
🚨 The issue tracker is not for questions 🚨

Hello,
I have created a language extension.  It supports files with ".br" and ".ots" extensions. Now I want to associate a custom icon to .br anr .ots files. 
How can I achieve this?

I am using Visual Studio Code 1.31.1

Thank you in advance!

**Comment by Gama11** [comment] 2019-03-13 12:33
Duplicate of #14662.

**Closed** 2019-03-13 16:57 UTC
Labels: extensions

**Comment by NavnathKumbhar** [comment] 2019-03-14 07:20
So as per the suggestions provided by you in #14662, I want to contribute to VSCode to add my custom icon definitions in Seti icon theme. From where should I start?

**Comment by NavnathKumbhar** [comment] 2019-03-15 07:17
I cloned the vscode repository which I forked. To add a new icon for my language extension, It seems that I have to modify sett.woff font file. Perhaps, I have to add a new glyph for my custom icon.

Is it acceptable change in vscode? 

Thank you in advance.
