### ISSUE TITLE
Focus on next error/warning starts from beginning after editing a file

### ISSUE THREAD

**Issue by JohnPoison** [Microsoft/vscode#22781] opened 2017-03-17 08:01 UTC
- VSCode Version: 1.10.2
- OS Version: OS X 10.11.6

When I hit F8 to go through problems vscode always focuses on the first problem. This makes hard to fix multiple problems in file.

Steps to Reproduce:

1. Hit F8 several times and focus on problem
2. Hit Cmd+1 and focus editor area. Edit file and fix problem. (message about problem still exist, meaning that vscode is focused on current problem)
3. Hit F8 again to focus on next problem.
4. Notice that vscode focused the first problem again.

> Suggestion: F8 should search closest problem next to current position of cursor.

**Comment by plievone** [comment] 2017-03-17 09:51
This is a regression between v1.7 and v1.8, see #17191. Hopefully it will be fixed soon!

**Comment by jrieken** [comment] 2017-04-24 09:22
dupe of  #17191

**Closed by jrieken** 2017-04-24 09:22 UTC
Labels: bug, code-actions
