### ISSUE TITLE
The rotating icon of initializing typescript language server is not centered.

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#76805] opened 2019-07-07 15:39 UTC
- VSCode Version: 1.36.0
- OS Version: macOS 10.14.5

![Screen Recording 2019-06-13 at 12 41 24 PM](https://user-images.githubusercontent.com/2157285/60770651-adce0280-a0f2-11e9-80e9-fc04ed934191.gif)

If you look at the gif above the two arrow icons that rotate around the center aren't actually set around the center.

**Comment by misolori** [comment] 2019-07-08 15:12
Duplicate of #75446

**Closed by misolori** 2019-07-08 15:12 UTC
