### ISSUE TITLE
VS Code forgets previous shortcut filters

### ISSUE THREAD

**Issue by leonardoanalista** [Microsoft/vscode#29846] opened 2017-06-29 11:26 UTC
- VSCode Version: any
- OS Version: mac os

Steps to Reproduce:

1. Select menu code/preferences/shortcuts
2. enter something to filter shortcuts. Example: duplicate lnes
3. change tabs
4. VS code forgets previous filters

Reproduces without extensions: Yes

Expected: keep previous data and filter entered by the user.

**Comment by sandy081** [comment] 2017-08-25 14:34
Duplicate of ##23543

**Closed by sandy081** 2017-08-25 14:34 UTC
