### ISSUE TITLE
Scroll jog on secondary screen

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#107577] opened 2020-09-28 10:49 UTC
Issue Type: <b>Bug</b>

Middleclicking on a file in the explorer pane *only* on my secondary screen, produces a scroll jog. On my primary screen, it closes the file when using on an open file. Same when middleclicking on the file header/tab.

The scroll jog is the incorrect behaviour, because middleclicking is meant to close an open file. On top of that, a scroll jog on a file header/tab is not useful, because you can't scroll there.

When I say scroll jog, I mean a circle with four little arrows. When this jog is visible, you can move the mouse away from it, and the view will scroll in the direction you move from it. I think it's a Windows thing, for those who aren't familiar. It can't be screenshotted, unfortunately.

A scroll jog can be quite useful, but not when you don't expect it, and certainly not when the circumstance by which it is triggered, is inconsistent. But mind you, I have no other applications on my pc that do this, so even if it were useful, I'm not used to it. I literally can't middleclick *anywhere* else to get that scroll jog.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (18.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
overtype|ada|0.2.0
codesnap|adp|1.2.0
Bookmarks|ale|11.3.1
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.56
vscode-firefox-debug|fir|2.9.1
duplicate|gee|1.0.1
docthis|joe|0.7.1
rainbow-csv|mec|1.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.6.0
remote-wsl|ms-|0.44.5
powershell|ms-|2020.6.0
vscode-template-literal-editor|pli|0.9.0
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
vscode-svg-previewer|vit|0.6.0

</details>

**Comment by isidorn** [comment] 2020-09-28 11:38
I have no clue why the mouse middle click would behave different on a secondary screen. Sounds like an electron issue, thus first forwarding to @deepak1556 
fyi @bpasero for ideas.

**Comment by thany** [comment] 2020-10-01 08:37
@isidorn 
> @thany is this something new, or vs code always behaved like this?

I'm sorry I can't say with confidence. Normally I use VScode on my primary screen where this doesn't happen.

**Comment by deepak1556** [comment] 2020-10-09 00:17
I don't have the required setup to verify this, @isidorn can you reassign to someone who can verify this. I would recommend verifying this with https://vscode-web-test-playground.azurewebsites.net/?enter=true on either chrome/edge, chromium manages the device inputs and not electron.

**Comment by JacksonKearl** [comment] 2020-10-10 00:28
@thany are you able to reproduce this in other electron based applications? Or even chromium itself?

**Comment by thany** [comment] 2020-10-14 08:01
@JacksonKearl I think Slack is Electron-based. On middle-click onto something scrollable but not clickable, it provides a scroll jog on *both* screens. The same goes for Chrome itself.

Could it be that VScode is doing something custom that cancels the scroll jog, that only happens to work on the primary screen?

**Comment by JacksonKearl** [comment] 2020-10-20 21:58
Yes we have code in a variety of places to override middle click behavior... 

```
src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts:
  104  	private onTitleAuxClick(e: MouseEvent): void {
  105: 		if (e.button === 1 /* Middle Button */ && this.group.activeEditor) {
  106  			EventHelper.stop(e, true /* for https://github.com/microsoft/vscode/issues/56715 */);

src/vs/workbench/browser/parts/editor/editorGroupView.ts:
  284  		this._register(addDisposableListener(this.element, EventType.AUXCLICK, e => {
  285: 			if (this.isEmpty && e.button === 1 /* Middle Button */) {
  286  				EventHelper.stop(e, true);

src/vs/workbench/browser/parts/editor/tabsTitleControl.ts:
  244  		this._register(addDisposableListener(tabsContainer, EventType.MOUSE_DOWN, (e: MouseEvent) => {
  245: 			if (e.button === 1) {
  246  				e.preventDefault();

  619  			if (e instanceof MouseEvent && e.button !== 0) {
  620: 				if (e.button === 1) {
  621  					e.preventDefault(); // required to prevent auto-scrolling (https://github.com/microsoft/vscode/issues/16690)

  666  		disposables.add(addDisposableListener(tab, EventType.AUXCLICK, (e: MouseEvent) => {
  667: 			if (e.button === 1 /* Middle Button*/) {
  668  				EventHelper.stop(e, true /* for https://github.com/microsoft/vscode/issues/56715 */);
```

Going to pass this off to @bpasero as you've authored most of these, though it does seem the issue is upstream.

**Comment by bpasero** [comment] 2020-10-21 06:02
@thany to clarify you see this with Slack and Chrome too, not just VSCode?

**Closed** 2020-10-28 11:32 UTC
Labels: needs more info, trackpad/scroll

**Comment by thany** [comment] 2020-10-30 10:58
> @thany to clarify you see this with Slack and Chrome too, not just VSCode?

No. I see a scroll jog on BOTH screens in Slack and Chrome, so it's consistent. In VScode I'm only getting a scroll jog on the secondary screen, making it inconsistent.
