### ISSUE TITLE
Same document open twice via search, both with modifications

### ISSUE THREAD

**Issue by Mehuge** [microsoft/vscode#51554] opened 2018-06-10 15:33 UTC
Issue Type: <b>Bug</b>

I have a sub-folder of my workspace, added to my workspace for the convenience of accessing a deeply nested folder.

If I do a search, the same term is found in the same file twice, once within the workspace and once within the added folder.  This in itself is an issue.

If I don't notice this has happened, I can click the search result and edit it.  If I do this for both search hits, I end up with the same file, opened twice in the editor, both with separate edits.

I save one, and I find I have another that still needs saving.  This can be confusing if I don't twig what is going on.

Opening the same file from search results should not open separate tabs in the editor, the editor should use the physical path of the file for handling tab uniqueness not the path of the file within the workspace.

myworkspace/game/hud/src/component/mycomponent.tsx
hud/src/component/mycomponent.tsx

are the same file! as hud is myworkspace/game/hud added as a folder to the workspace.

Whilst I am at it, it would be great if could right click a folder in a workspace, and say add folder to the workspace, instead of having to go through the file menu.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (1.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
path-intellisense|chr|1.4.2
routeros-syntax|cpe|1.0.0
vscode-fileheader|mik|0.0.2
indent-rainbow|ode|7.2.2
final-newline|sam|0.3.2
vim|vsc|0.12.0

</details>

**Comment by bpasero** [comment] 2018-06-11 16:14
Marking as duplicate of https://github.com/Microsoft/vscode/issues/12448

The one folder is likely using different path casing compared to the other.

**Comment by Mehuge** [comment] 2018-06-15 16:31
I don't think your analysis is correct.  The paths are not using a different case.  It's because whatever is checking if a tab is open is using the path within the workspace reference rather than the physical path.

![image](https://user-images.githubusercontent.com/99895/41479075-dbd9e728-70c1-11e8-8177-553388bb414a.png)

**Comment by bpasero** [comment] 2018-06-15 16:47
@Mehuge so what are the paths of both files then when opened?

**Comment by Mehuge** [comment] 2018-06-15 19:18
You know, you are right

![image](https://user-images.githubusercontent.com/99895/41485609-2d68f126-70d9-11e8-8323-297a959b6171.png)

But my workspace config is as below, so why is search using different case root paths?

```{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "library"
    },
    {
      "path": "game\\hud"
    }
  ],
  "settings": {}
}```

But search is finding files in each path, but using different root folder casing

**Comment by bpasero** [comment] 2018-06-16 05:39
@Mehuge is it using symbolic links?

**Comment by Mehuge** [comment] 2018-06-16 13:58
No.  `D:\DEV\CU\Mehuge\Camelot Unchained` is just a regular folder, there are no junctions or symbolic links.  There isn't a D:\dev 

Though a new clone and workspace, with the above workspace file copied into it, when I do a search, it doesn't find multiple different results.  Don't know what's going on, but I now can't replicate the image above with the separate case roots.

Ok, I have a reproducible case, and its to do with launching code from `cygwin`.

1. open cygwin bash
2. cd /d/dev/cu/mehuge/Cam*
3. code .
4. add folder to workspace
5. browse to D:\DEV\CU\Mehuge\Camelot Unchained
6. pick a folder and add it.

If I then search for something, it will find it twice.

![image](https://user-images.githubusercontent.com/99895/41499299-a62c62ea-7175-11e8-881a-1c6a0508837c.png)

On windows, when comparing paths, perhaps the comparison should be case insensitive.

**Comment by bpasero** [comment] 2018-06-16 16:13
Moving to search land, I think if the paths are the same but the case differs we should maybe be smarter.

**Comment by jvgomez** [comment] 2019-02-12 10:51
@bpasero what would be the issue with symlinks? I am experiencing a similar issue but I do have symlinks.

**Comment by roblourens** [comment] 2019-10-09 18:39
Sorry I don't understand the problem. You did open one folder with the wrong case, but "Camelot-Unchained" and "widgets" are different folders! One is inside the other. So of course you see the results twice. I don't really understand what you were trying to do. Sorry that this is so old. Will close it unless I get a response.

**Closed by roblourens** 2019-10-09 18:39 UTC
Labels: bug, search

**Comment by Mehuge** [comment] 2019-10-09 22:10
Look at the tail end of the paths not the roots. They are the same folder.

Camelot-Unchained (the main project) is pointing at: `d:\dev\cu\mehuge\Camelot Unchained` because I did `code .` while sat in cygwin after doing `cd /cygdrive/d/cu/mehuge/Came*`

`Camelot Unchained\widgets` is the same physical folder as `widgets` but separate in the project tree because `widgets` was added to the project using **Add Folder to Workspace...**. 
<blockquote>
not very sensible example given widgets is a folder in Camelot Unchained anyway, but it is only to demonstrate the issue - the real case was a folder deep within the folder structure
</blockquote>

When doing a search that finds something within widgets, in the search results we have:

```widgets\cu-character-creation\src\...\FactionSelect.tsx```
and
```cu-character-creation\src\...\FactionSelect.tsx```

They are the same physical file. The paths are the same, differ only in case. The actual DOS path being:

```D:\DEV\CU\Mehuge\Camelot Unchained\widgets\cu-character-creation\src\...\FactionSelect.tsx```

As WINDOWS is case-insensitive when it comes to path names, then I think they should be treated as the same file and not searched twice or displayed twice.

**Comment by roblourens** [comment] 2019-10-09 22:21
Ok now I understand, thanks. I didn't realize that the results do get duduped typically because they are held in a big map at some point and not case-normalized.

I'm going to leave it closed - it's covered by https://github.com/microsoft/vscode/issues/12448, search won't really do any search-specific file path case normalizing. Also, I would recommend not having workspace folders that are inside other workspace folders, I think you will have an inconsistent and confusing experience.

**Comment by Mehuge** [comment] 2019-10-10 08:48
Ok, thank you, that makes complete sense.
