### ISSUE TITLE
Dubugging mode not work properly(show automatically lots of break point )

### ISSUE THREAD

**Issue by neha-exzeo** [Microsoft/vscode#38585] opened 2017-11-17 05:57 UTC
recently I updated my visual studio code in which debugging
![breakpoint]
 does not work properly its show automatically breakpoint. which are also not remove by removing. please check this issue its create problem on working in visual studio code

**Comment by neha-exzeo** [comment] 2017-11-17 05:59
![breakpoint](https://user-images.githubusercontent.com/20860884/32931505-98e8fab2-cb8a-11e7-81ea-e830db2e3ef1.PNG)

**Comment by sean-mcmanus** [comment] 2017-11-17 06:15
I've hit this a few times in the past few days too. I was using the C++ extension to debug, but I don't think that extension is the cause. I used 1.18 on Windows. I have to clear all my breakpoints to fix it. Seems to happen randomly or something.

**Comment by neha-exzeo** [comment] 2017-11-17 06:35
I also used 1.18 on windows and I was using C# extension same thing is happening to me when I set few breakpoint. then breakpoints appear in every line and this breakpoint not remove also.

**Comment by weinand** [comment] 2017-11-17 07:48
Duplicate of #37880. Fixed in VS Code 1.18.1.

**Closed by weinand** 2017-11-17 07:48 UTC
Labels: debug
