### ISSUE TITLE
"Running the contributed command" error while using 

### ISSUE THREAD

**Issue by gustawx** [microsoft/vscode#118098] opened 2021-03-04 07:23 UTC
- VS Code Version: 
- OS Version:
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
I use shortcut shift+alt+O to remove unused imports
1. In TypeScript file press keys: **shift+alt+O**
error:
**Running the contributed command: '_vscode_delegate_cmd_klujbaaa' failed.**

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by gjsjohnmurray** [comment] 2021-03-04 07:33
/needsMoreInfo please use the Extension Bisect command to investigate whether the problem is being caused by one of your extensions

**Comment by gustawx** [comment] 2021-03-04 07:37
I thought it is reproducible after disabling all extensions, do I still need to do it (simply very busy at work...)

**Comment by gjsjohnmurray** [comment] 2021-03-04 08:17
In that case, no. Extension Bisect would run that test first anyway.

Please review https://github.com/microsoft/vscode/wiki/Keybinding-Issues steps.

**Comment by mjbvz** [comment] 2021-03-05 02:40
Does not reproduce for me with VS Code insiders

**Comment by gustawx** [comment] 2021-03-05 07:08
Yesterday I reinstalled the VS Code, restarted windows and still reproduced the issue. Today it works fine... strange problem

**Comment by gjsjohnmurray** [comment] 2021-03-05 07:31
1.54 released yesterday, followed quickly by 1.54.1

I guess it's possible your reinstall happened before one or both of those releases, and that your VS Code has updated itself since then.

Please close the issue.

**Comment by gustawx** [comment] 2021-03-05 10:13
I found the problem, actually two:
1. Error from this issue description occurs If we have code like that (mind at /** at the end of first line):

```
import * as something from "path";/** 
 * some comment here
 * and there
 */
import * as somethingElse from "anotherpath";
```

2. Another issue is when we have the following code:
```
import * as something from "path";
/** 
 * some comment here 
 * and there
 */
import * as somethingElse from "anotherpath";
```

and we click shift+alt+O then whole comment section is being deleted as well as unused imports

**Comment by mjbvz** [comment] 2021-03-05 21:27
Thanks. Opened https://github.com/microsoft/TypeScript/issues/43107 to track upstream root cause

**Closed by mjbvz** 2021-03-05 21:27 UTC
Labels: needs more info
