### ISSUE TITLE
Document formatting is removing characters!

### ISSUE THREAD

**Issue by AlQuraian** [Microsoft/vscode#19871] opened 2017-02-03 20:03 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. code the following code and place it in an html file then format the file.
```html
<script>
      tag = document.createElement('script');
        src = "https://www.youtube.com/iframe_api";
        firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  </script>
```

After the formatting it would look like:
```html
<script>
    document.createElement('script');
        "https://www.youtube.com/iframe_api";
        criptTag = document.getElementsByTagName('script')[0];
        criptTag.parentNode.insertBefore(tag, firstScriptTag);
</script>
```

I uninstalled VS Code, removed the 'code' folder in 'AppData\Roaming' and removed all extensions. The issue still occurs!

**Comment by aeschli** [comment] 2017-02-06 11:55
duplicate of #19813

**Closed by aeschli** 2017-02-06 11:55 UTC
