### ISSUE TITLE
JavaScript : bring old CodeLens behavior back

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#86846] opened 2019-12-12 21:01 UTC
I really really don't need a new `x references` line for every inline function or object I make, old behavior was nearly perfect, it just needed references for functions returned object properties

Here is a bunch of unwanted references

![Code_2019-12-12_20-53-42](https://user-images.githubusercontent.com/30108880/70746747-b8866680-1d26-11ea-99b1-2f9bdda1e451.png)
![Code_2019-12-12_21-00-01](https://user-images.githubusercontent.com/30108880/70746748-b8866680-1d26-11ea-807a-711e37cc1cec.png)
![Code_2019-12-12_21-12-46](https://user-images.githubusercontent.com/30108880/70746750-b91efd00-1d26-11ea-9625-4d44c133c8c8.png)
![Code_2019-12-12_21-21-53](https://user-images.githubusercontent.com/30108880/70746752-b91efd00-1d26-11ea-8c67-7f1f5e0bb0e3.png)
![Code_2019-12-12_21-27-34](https://user-images.githubusercontent.com/30108880/70746753-b9b79380-1d26-11ea-89b4-79674047885b.png)

I should thicken my argumentation but my extension free vscode goes on a cpu binge and loses all of its features whenever I declare a variable anyway so I'm just not going to deal with any of it and go back to 1.40
I should mention that this version brought noticeable improvements and it's the first time I ever encounter such an issue, you guys are doing a fantastic job

**Comment by mjbvz** [comment] 2019-12-12 21:04
Duplicate of #86495 I believe

Should be fixed in VS Code 1.42 insiders builds

**Closed by mjbvz** 2019-12-12 21:04 UTC
Labels: javascript
