### ISSUE TITLE
VScode Disabling preview SVG badges with Some content has been disabled in this document

### ISSUE THREAD

**Issue by ssewilliam** [Microsoft/vscode#68309] opened 2019-02-09 11:42 UTC
- VSCode Version: Version 1.31.0 (1.31.0)
- OS Version: macOS Mojave v 10.14.1

Steps to Reproduce:

1. Copy badge markdown from Continous Integration Platform and Paste it in a README.md. file
2. Press `CMD+ SHIFT+ V` to preview build badge.
3. Actual experience is an error message with `Some content has been disabled in this document`

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by mjbvz** [comment] 2019-02-11 16:23
Duplicate of #68033

**Closed by mjbvz** 2019-02-11 16:23 UTC
Labels: webview

**Comment by ssewilliam** [comment] 2019-02-11 16:56
@mjbvz I had the feeling that you would mark the issue as a duplicate but it does not help when the *duplicates of* also do not have solutions.
Please know that some issues are closed without solutions.
