### ISSUE TITLE
Is there are some APIs or some methods to get the opend files.

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#90887] opened 2020-02-18 14:06 UTC
![image](https://user-images.githubusercontent.com/12140508/74739029-040f4080-5293-11ea-8bcb-fa8b5641271f.png)
I have noticed that the `Close All ` function was implemented and when open the vscode , it can restore last time's opened files. I wonder if there are some APIs or some methods where i can get the opened files in vscode .  I found the similar question in https://github.com/microsoft/vscode/issues/15178 , but an API may be more reasonable and elegant. Is there any other reasons that can't give such an API?  Hope your answer . Thanks a lot.

**Comment by isidorn** [comment] 2020-02-18 16:06
Closing as duplicate of that issue.
You can continue the discussino there. Thanks

**Closed by isidorn** 2020-02-18 16:06 UTC

**Comment by Abbyyan** [comment] 2020-02-19 09:18
> You can continue the discussino there.
I 've finish reading the disscusion but i wonder if there are some progress for this problem. Thanks a lot .
