### ISSUE TITLE
Ctrl-M doesn't scroll the page and take you to the matching braces.

### ISSUE THREAD

**Issue by aarumug** [Microsoft/vscode#32664] opened 2017-08-16 20:17 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (728b2f9ad74bbec1dcde55dc42e5ea028661447d, 2017-08-16T05:16:50.783Z)
- OS Version: Windows_NT x64 10.0.16267
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
python|don|0.7.0
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
beautify|Hoo|1.1.1
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
sublime-keybindings|ms-|2.9.1
typescript-javascript-grammar|ms-|0.0.23
debugger-for-chrome|msj|3.1.8
debugger-for-edge|msj|0.4.1
view-in-browser|qin|0.0.5
vscode-react-native|vsm|0.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open any c++ code and go to an open brace in a function or loop
2. Press Ctrl-M (which is the shortcut key combo) to get to the matching braces. Notice the page doesn't scroll and show you the matching brace. Instead the cursor just jumps to the matching brace.

Reproduces without extensions: No. Requires (sublime keymap extension)

**Comment by hoangnamitc** [comment] 2017-09-12 01:46
this is my problem too ! :(

**Comment by alexandrudima** [comment] 2017-10-26 08:12
Duplicate of #32597 . The fix is out since 1.17

**Closed by alexandrudima** 2017-10-26 08:12 UTC
Labels: editor, editor-core
