### ISSUE TITLE
Merge editor starts showing merge markers after closing file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151033] opened 2022-06-01 21:38 UTC
Testing #150389

1. Open merge editor
2. In another editor group, open the file being merged3. 

![Screen Shot 2022-06-01 at 2 36 16 PM](https://user-images.githubusercontent.com/12821956/171506144-91439d3b-e7e1-402f-b23c-2f76472ca76c.png)

3. Now close the file being merged (`main.ts` in my case)

**Bug**
The bottom part of the merge editor scrolls all the way to the bottom of the editor. When I scroll it back up, I see merge markers:

![Screen Shot 2022-06-01 at 2 36 25 PM](https://user-images.githubusercontent.com/12821956/171506240-970e08ee-f8a1-490e-bf99-a540136e43db.png)

**Comment by mjbvz** [comment] 2022-06-01 21:41
I also don't understand what the filled circles that replace the checkmarks mean

**Comment by hediet** [comment] 2022-06-02 12:30
I think the bug is caused by how we integrate the merge editor into the workbench.
Hopefully this gets resolved after @jrieken, @bpasero and me meet next week.

> I also don't understand what the filled circles that replace the checkmarks mean

This means that the user has changed the result in this area, but has not accepted either input 1 or input 2.

**Comment by bpasero** [comment] 2022-06-02 13:20
I cannot really reproduce the issue:
![Recording 2022-06-02 at 15 19 54](https://user-images.githubusercontent.com/900690/171638445-4867705f-1ecf-424c-9fd2-24e70b15bbeb.gif)

Anyway: the "Result" of merge editor should be identical to the file on disk, meaning that edits in the one are reflected in the other editor, same as we do for diff editors.

**Comment by bpasero** [comment] 2022-06-02 16:56
I agree that opening an editor should not make it dirty right from the beginning, so I suggest to:
* always have the result be the actual file on disk
* never change the file when you open the editor
* find a clever way how to hide the merge markers so that resolving the merge conflict is still nice

I am not sure whether this is possible or not?

**Comment by hediet** [comment] 2022-06-02 17:03
I like this! Let's try to collapse merge markers, so they take only a single line.

**Comment by bpasero** [comment] 2022-06-03 07:05
One thing I am not entirely sure: even when we remove merge markers, the file would still contain both conflicting changes one above the other. Maybe the merge editor initially should reflect this by showing both checkboxes checked in that case and then as a user, only when I click a checkbox, the editor becomes dirty and changes are removed?

**Comment by jrieken** [comment] 2022-06-07 09:19
> One thing I am not entirely sure: even when we remove merge markers, the file would still contain both conflicting changes one above the other. 

Yeah, that's the issue. The merge markers and the inlined versions should be understood as a "poor man's" merge editor. IMO keeping that in a "UI-driven" merge editor adds more confusion than help. It's also entirely unclear who tells us what part of a file is "merge marker noise". 

I do understand the confusion about the editor opening as dirty. We could not make any changes during open, just be a different display-mode for how the file is on disk (e.g the results pane wouldn't show the file as on disk). Once the user accepts changes make the file dirt, maybe have a user-setting to auto-apply non-conflicting changes (which means dirty on open again)

**Comment by bpasero** [comment] 2022-06-07 12:12
Btw I believe in VS case, the file is actually in some temp dir, so you may not be editing the actual file, but some copy.

**Comment by jrieken** [comment] 2022-06-07 12:41
Yeah, that's something we have thought about and maybe not discussed enough yet. The downside of a temp/virtual file is that language services likely won't handle them as good as files on disk

**Comment by bpasero** [comment] 2022-06-07 13:04
Yeah wasn't suggesting to go down that path, I think all advantages when the real file on disk is edited 👍

**Comment by jrieken** [comment] 2022-06-24 13:33
I believe this issue will go away when we implement https://github.com/microsoft/vscode/issues/151024. The plan for that is to show a modal message when you are closing the merge editor while still having unresolved conflicts

**Comment by jrieken** [comment] 2022-06-27 11:59
Closing since we now have the explicit warning about unhandled conflicts on close (#151024)

**Closed by jrieken** 2022-06-27 11:59 UTC
Labels: bug, merge-editor, merge-editor-workbench
