### ISSUE TITLE
Typing in File Tree causes all files to appear disabled

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#69549] opened 2019-02-27 16:31 UTC
Issue Type: <b>Bug</b>

When the file explorer tree is selected, typing a partial file name then hitting enter causes all of the files/folders to appear "disabled". The only way (I found) to restore it is to do a Refresh Window command.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/13488/53506002-10e3c480-3a83-11e9-8e32-c92bba2eb066.png">

Start typing:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/13488/53506027-1f31e080-3a83-11e9-913f-8628bbd92e48.png">

Hit Enter:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/13488/53506049-2ce76600-3a83-11e9-99e5-03f3d5a85c37.png">

Erase typing:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/13488/53506078-3a045500-3a83-11e9-86b6-9dc71a0a33ee.png">

VS Code version: Code - Insiders 1.32.0-insider (ce073b0076ac2f69faf2c609af72f9b81506c791, 2019-02-27T06:15:35.767Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.62GB free)|
|Process Argv|-psn_0_14548447|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.27
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
auto-rename-tag|for|0.0.15
csharpextensions|jch|1.3.0
Angular2|joh|7.0.1
azure-account|ms-|0.8.0
csharp|ms-|1.18.0-beta7
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.2
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
quicktype|qui|12.0.46
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.3

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment] 2019-02-27 18:06
Encountered watching a Twitch stream: https://clips.twitch.tv/FantasticSavageEggnogSSSsss

**Comment by usernamehw** [comment] 2019-02-28 00:42
Possible duplicate of #69468

**Closed** 2019-03-01 13:23 UTC
Labels: *duplicate
