### ISSUE TITLE
macOS Mojave: font rendering is blurry or has changed

### ISSUE THREAD

**Issue by 0xdeafcafe** [microsoft/vscode#51132] opened 2018-06-05 09:09 UTC
**Solution:**
If you have updated to macOS 10.14 (Mojave) you might have noticed that fonts in VSCode are looking blurry if you are not using a high-DPI monitor. A workaround for this is to run

```
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
```

from the terminal followed by a restart to get back the previous behaviour. Note that this change is global for every application and not specific to VSCode.

-----

- VSCode Version: Version 1.23.1 (1.23.1) - `d0182c3417d225529c6d5ad24b7572815d0de9ac `
- OS Version: macOS Version 10.14 Beta

Steps to Reproduce:

1. Open VSCode
2. Open a file
3. View said file

Does this issue occur when all extensions are disabled?: Yes

This is how the fonts look:
![screenshot 2018-06-05 at 10 06 27](https://user-images.githubusercontent.com/2768524/40966370-3c5b96a4-68a8-11e8-8ac8-b5000890e95d.png)

I don't expect this is a VSCode issue, but just incase wanted to bring it up earlier rather than later.

**Comment by birkir** [comment] 2018-06-05 17:07
Can confirm, but only on non-retina displays.

Tried change LCD Font Smoothing in Mac OS Settings, no luck.
Tried `workbench.fontAliasing` without any luck.

**Comment by BanjoCam** [comment] 2018-06-05 19:35
I'm on a retina display. Fonts are still completely usable but appear far thinner(?) than they did prior to the update. Anecdotal of course, but the change was obvious as soon as I fired up post upgrade.

**Comment by celento** [comment] 2018-06-05 19:47
Yep, the fonts are thinner on all Webkit based apps even on Chrome. I think macOS Mujave is setting the font-aliasing in by default to “antialiasing” instead of “subpixel-antialiasing”.

**Comment by BanjoCam** [comment] 2018-06-05 22:09
@celento That is sad and I hope not a permanent change... one of my favourite things about MacOS is the font rendering!

**Comment by bpasero** [comment] 2018-06-06 06:10
Does it make a difference if you configure our `workbench.fontAliasing` setting to `none` or `antialiased`? Also, can people reproduce this with our builds that leverage Electron 2.0.x: https://az764295.vo.msecnd.net/exploration/4ba0c0e008bf983ab61a3bd577df370582fec9fb/VSCode-darwin-exploration.zip

**Comment by digicase** [comment] 2018-06-10 16:29
This is a good relevant thread about the text rendering changes in macOS Mojave

https://twitter.com/siracusa/status/1004143205078597633

**Comment by Rykuno** [comment] 2018-06-11 02:57
Seems not to just be VSCode either for me. Opened up a few applications after trying out Mojave and most non-Apple applications look similar to this...

![screen shot 2018-06-10 at 9 54 25 pm](https://user-images.githubusercontent.com/10355852/41210737-0d90be08-6cf9-11e8-9830-1a76a6c6cd1f.png)

**Comment by vinkla** [comment] 2018-06-19 20:18
This is also reported in Atom: https://github.com/Microsoft/vscode/issues/51132 and could be related.

**Comment by Toxblh** [comment] 2018-06-19 20:22
Link on issue in atom https://github.com/atom/atom/issues/17486

**Comment by gravicle** [comment] 2018-06-28 17:29
Is there a workaround for the issue? Can reproduce on Mohave running VSCode 1.24.1

**Comment by glixlur** [comment] 2018-06-29 07:08
Relevant issue on Chrome bug reporter: https://bugs.chromium.org/p/chromium/issues/detail?id=858861

**Comment by bpasero** [comment] 2018-07-07 14:08
And: https://news.ycombinator.com/item?id=17476873

**Comment by jmikrut** [comment] 2018-07-16 12:29
I just .... got around this problem by setting `editor.fontWeight` to `bold`.  It looks basically like it used to before Mojave.  Maybe a bit bolder but I can live with it compared to what it was set to `normal`.

**Comment by birkir** [comment] 2018-07-17 03:32
That totally depends on which font family you use, and it will also look different on an Retina/Non-retina display.

Only solution is to have Chromium have its own font raster engine I guess

**Comment by vinkla** [comment] 2018-07-17 10:07
It seems Apple released [further updates to UI font smoothing](https://twitter.com/jnadeau/status/1018966229183184897) in Mojave Beta 4. The fonts now looks bolder and are easier to read.

**Comment by quentez** [comment] 2018-07-30 20:26
I'm using Beta 5 and still seeing significantly thinner font in VSCode.

**Comment by vinkla** [comment] 2018-07-31 07:57
> I'm using Beta 5 and still seeing significantly thinner font in VSCode.

Yes, sadly this seems the case in Beta 5.

**Comment by glixlur** [comment] 2018-07-31 22:46
Can anyone with Beta 5 upload a screenshot of VSCode?

**Comment by 0xdeafcafe** [comment] 2018-08-01 09:17
Beta 5 non-retina:
![screenshot 2018-08-01 at 10 16 25](https://user-images.githubusercontent.com/2768524/43512858-2046965a-9574-11e8-991d-7b296132b22f.png)

Beta 5 retina:
<img width="1552" alt="screenshot 2018-08-01 at 10 16 40" src="https://user-images.githubusercontent.com/2768524/43512867-235b62a8-9574-11e8-9d8f-9d38b42c12d3.png">

**Comment by BanjoCam** [comment] 2018-08-01 14:19
For comparison, I reverted back to Beta 4 because I find the fonts too hard to read. I have a retina display - here is the Beta 4 screen shot:

![image](https://user-images.githubusercontent.com/3679608/43527309-4dc23350-9574-11e8-9e30-34c05296db19.png)

**Comment by ryanwarsaw** [comment] 2018-08-02 05:59
I have a Dell UltraSharp U2715H 27-Inch Screen LED-Lit monitor, just upgraded to the public beta, I assume that's #4 if I'm not mistaken. Font rendering looks pretty much normal on a good portion of my applications, looks really bad on others - especially VS Code. 

It's really weird, the best way to describe it is that it looks exactly like @0xdeafcafe's screenshots, would be great if we could figure out what is happening here 😄

**Comment by glixlur** [comment] 2018-09-04 20:06
Public beta 10 has been released. Can anyone still reproduce this problem?

**Comment by ryanwarsaw** [comment] 2018-09-04 20:14
Since I've been doing the beta over the past month, I've noticed that pretty much all of my applications are fine, it's only a select few like VS Code, and Atom. Other IDEs like IntelliJ look crisp and just like they should, and other electron-based apps also for the most part look unchanged. This has been consistent behavior across each beta update I've done.

**Comment by celento** [comment] 2018-09-04 21:37
In that case do you have any idea about why only certain electron based
applications are affected ?

**Comment by glixlur** [comment] 2018-09-04 22:27
@ryanmcnamara What about Chrome? If Chrome works fine, Electron just needs to update their upstream.

**Comment by ryanmcnamara** [comment] 2018-09-05 00:09
@glixlur wrong ryan?

**Comment by Rykuno** [comment] 2018-09-05 02:10
@glixlur I'm having the same problems for quite a few applications I use. Strangely enough all the applications I'm currently having problems with are either Electron or QT applications also.

**Comment by ryanwarsaw** [comment] 2018-09-05 02:48
### VS Code (default font settings, Version 1.26.1, 493869ee8e8a846b0855873886fc79d480d342de)
![vs code](https://user-images.githubusercontent.com/6530909/45068109-97e35180-b08b-11e8-8113-69ade7f578fa.png)

### Android Studio (default font settings, 3.1.4, stable)
![android studio](https://user-images.githubusercontent.com/6530909/45068175-d547df00-b08b-11e8-9a50-4b7ed0e85778.png)

### Chrome (default font settings, Version 68.0.3440.106, release build) 
![thimble](https://user-images.githubusercontent.com/6530909/45068200-f3adda80-b08b-11e8-9216-9c743baf678e.png)

@celento @glixlur I attached some pictures, but I haven't had much of an issue w/Chrome.

**Comment by celento** [comment] 2018-09-05 03:10
The last Beta I used was Beta 5 and it had even thinner fonts for Google search results using Chrome.

**Comment by carlca** [comment] 2018-09-09 11:55
I can confirm that the problem still exists in Beta 10, but that @jmikrut 's suggestion of setting the font weight to bold works. Thanks @jmikrut!

**Comment by zlliang** [comment] 2018-09-14 12:37
I'm at Beta 10, and the problem exists in Chromium 70... 😓

**Comment by simeonpashley** [comment] 2018-09-17 10:02
This improved things for me, _almost_ back to normal
` defaults -currentHost write -globalDomain AppleFontSmoothing -int 2`

**Comment by MikeMcQuaid** [comment] 2018-09-17 14:51
> got around this problem by setting `editor.fontWeight` to `bold`

I tried this and didn't like how it looked. `"editor.fontWeight": "500"` looks like the good old days, though.

**Comment by pdgago** [comment] 2018-09-18 17:47
Agree, It looks horrible on non-retina displays and I don't think vscode can do anything about this.

Really bad move from apple, It's way too soon to remove the subpixel rendering, most people doesn't have external retina displays! I am getting tired of this behaviour...

After trying every font possible, I agree that setting the font-weight to 500 doesn't look that bad, but most fonts doesn't support this weight... 😣

**Comment by FateLight** [comment] 2018-09-20 18:39
@samelhusseini What is the resolution of your display?

**Comment by mario-grgic** [comment] 2018-09-24 20:57
> > got around this problem by setting `editor.fontWeight` to `bold`
> 
> I tried this and didn't like how it looked. `"editor.fontWeight": "500"` looks like the good old days, though.

This has no effect for me (macOS Mojave release version on 2017 27'' iMac).

**Comment by angristan** [comment] 2018-09-24 21:04
So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔

**Comment by alexanderyakusik** [comment] 2018-09-24 21:30
> So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔

I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

**Comment by noobtiger** [comment] 2018-09-24 21:37
> > So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔
> 
> I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

This worked me, thank you @alexanderyakusik

**Comment by JonnyKong** [comment] 2018-09-24 21:45
> > So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔
> 
> I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

Also worked for me. Thank you very much!

**Comment by slavapavlutin** [comment] 2018-09-24 21:46
Saved me from downgrading to High Sierra, @alexanderyakusik. You're a saint.

**Comment by colevanh** [comment] 2018-09-24 21:48
> > So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔
> 
> I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

Thank you! This worked.

**Comment by alexknipfer** [comment] 2018-09-24 21:49
> defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

Thanks! Worked perfectly!

**Comment by steelbrain** [comment] 2018-09-24 21:51
A request to please not spam the thread with confirmation comments, please do a thumbs up reaction on the comment instead. Thank you

**Comment by angristan** [comment] 2018-09-24 21:54
@alexanderyakusik Thank you so, so much much!

For anyone viewing this: make sure you have font smoothing enabled, too.

This feels exactly like High Sierra!

<img width="780" alt="screenshot 2018-09-24 at 23 52 20" src="https://user-images.githubusercontent.com/11699655/45981361-0301c180-c055-11e8-8bf9-8bcc0c9273ee.png">

**Comment by Lachlantula** [comment] 2018-09-25 06:46
@angristan I have this enabled by default, but my fonts still look a little off in all my apps. Anyone else got any ideas?

![image](https://user-images.githubusercontent.com/12870244/45997321-87e6ec80-c0e2-11e8-93e9-67cd999ec2a2.png)

Font is Operator Mono Book.

**Comment by matwming** [comment] 2018-09-25 07:15
> I just .... got around this problem by setting `editor.fontWeight` to `bold`. It looks basically like it used to before Mojave. Maybe a bit bolder but I can live with it compared to what it was set to `normal`.

thanks this works very well

**Comment by Greenmzc** [comment] 2018-09-25 09:46
> > So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔
> 
> I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

Thanks! It's worked.

**Comment by frzi** [comment] 2018-09-25 10:55
> > So... Mojave is out. The font rendering looks awful on both 1x displays and Retina displays. I'm really disappointed. I don't think the VS Code team can do anything about it though 😔
> 
> I just found the possible solution. Try executing this command in the terminal: defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

Can confirm this works for me as well! All my Electron apps are beautiful again.

**Comment by Lachlantula** [comment] 2018-09-25 10:57
Would definitely recommend trying the `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO` solution first (before updating font weights). Much more natural solution. Don't forget to log out then log back in to see changes.

**Comment by bpasero** [comment] 2018-09-25 11:03
Since we seem to have found a solution, I think we can lock this issue (if someone disagrees, just open a new issue and ping me).

**Solution:**
If you have updated to macOS 10.14 (Mojave) you might have noticed that fonts in VSCode are looking blurry if you are not using a high-DPI monitor. A workaround for this is to run

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

from the terminal followed by a restart to get back the previous behaviour. Note that this change is global for every application and not specific to VSCode.

**Comment by deepak1556** [comment] 2019-10-11 19:52
This should be fixed in latest insiders, can anyone confirm. Thanks!

**Comment by deepak1556** [comment] 2019-10-15 19:00
The fixes from chromium team made for both retina and non-retina displays https://bugs.chromium.org/p/chromium/issues/detail?id=901611 ,  https://bugs.chromium.org/p/chromium/issues/detail?id=858861 are available in the latest insiders. If the bug is still visible, I would suggest to compare the font rendering with chrome and report in upstream if the bug is repro'd in chrome. I am keeping this issue open to avoid possible duplicate issues in the repo and also to track any further chromium side improvements.

**Comment by deepak1556** [comment] 2019-11-15 18:16
No further action can be taken on this one from VSCode end, closing as such.

**Closed by deepak1556** 2019-11-15 18:16 UTC
Labels: electron, fixed-in-electron-6.x, font-rendering, mac, mojave, needs more info, upstream
