### ISSUE TITLE
Add selection command concatenates selections when selected terms are next to each other

### ISSUE THREAD

**Issue by durad** [Microsoft/vscode#24561] opened 2017-04-12 01:32 UTC
- VSCode Version: 1.11.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Click on File -> New File
2. Type the following text: `cat dog cat cat dog`
3. Select first occurrence of cat with space immediately after it (first four characters)
4. Press ctrl+d three times

Second and third occurrence of word cat will become one selection. Three occurrences of a word cat (plus space) will become only two selections. If only cat was selected initially (without space after it) then everything would work as expected resulting with three selections.

**Comment by alexandrudima** [comment] 2017-04-12 12:54
Duplicate of #6661

**Closed by alexandrudima** 2017-04-12 12:54 UTC
