### ISSUE TITLE
node launch: wrong runtimeExecutable used

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#50032] opened 2018-05-17 08:24 UTC
- Open the vscode selfhost workspace on linux
- In the debug viewlet launch the 'Unit Tests' launch
- Error:
Attribute 'runtimeExecutable' does not exist ('/home/aeschli/workspaces/vscode-remote/.build/electron/Code - OSS.app/Contents/MacOS/Electron').

Looks like the default `runtimeExecutable` is used, and the linux override is ignored.
```
"runtimeExecutable": "${workspaceFolder}/.build/electron/Code - OSS.app/Contents/MacOS/Electron",
"linux": {
	"runtimeExecutable": "${workspaceFolder}/.build/electron/code-oss"
},
```

**Comment by isidorn** [comment] 2018-05-17 08:25
Sounds like a duplicate of #50006
Thanks for fillling, looking into the fix right now

**Closed by isidorn** 2018-05-17 08:25 UTC
