### ISSUE TITLE
Notebook controller should be auto selected when there is only one option 

### ISSUE THREAD

**Issue by setaskin** [microsoft/vscode#167887] opened 2022-12-01 22:26 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0 insider 
- OS Version: Windows 11 

This issue is found while working on a notebook bug on Live Share. When Live Share host runs a cell, output doesn't reflect on the guest side and "notebook controller is not associated with this notebook" error shows up on console.  After discussion with VS Code team, I figured notebook controller needs to be selected by user to be able to execute cells. However, in Live Share guest's case there is only one controller.  So, we believe if there is only one controller available it should be selected by default.  I found there is previous discussion started here but the issue is closed due to inactivity. https://github.com/microsoft/vscode/issues/126534

apart from that,  the UI is confusing for the user in terms of whether controller is selected or not.  
Controller button on the right top doesn't reflect whether it is selected or not . There is no difference in the button before or after it is selected.  Right now, it brings one of the available controller's names randomly if there is more than one controller.  If there is only one controller it shows the available controller's name, but it is not selected, so it is very confusing for the user. 

So to summarize we request 2 improvements 

1. If there is only one notebook controller available to user, it should be selected by default. 
2. Notebook controller button should show up as "select controller" if none is selected. Right now, it brings one of the available controllers' names randomly if there is more than one controller.  For the case when there is only one controller available, it is even more confusing because it shows the controllers name and user would think it is selected but it is not. 

controller is not selected: 
![image](https://user-images.githubusercontent.com/37163639/205170575-7152712a-eef5-47e6-93e3-62a4a0f30e61.png)

controller is selected:
![image](https://user-images.githubusercontent.com/37163639/205170723-734fa675-71ae-47f8-b158-25e7dbbd3b9c.png)

![controller](https://user-images.githubusercontent.com/37163639/205171532-5ab49d7a-d2ac-46a2-901a-5a020261ccc0.gif)

**Comment by setaskin** [comment] 2022-12-01 22:28
cc: @minsa110

**Comment by minsa110** [comment] 2022-12-01 22:44
Also adding @rebornix @DonJayamanne @roblourens

**Comment by setaskin** [comment] 2023-01-12 21:12
Hi, is there any time estimate for the fix of this issue ?

**Comment by rebornix** [comment] 2023-01-19 21:01
> So, we believe if there is only one controller available it should be selected by default

I didn't follow the real problem occurred in Live Share but here is what happens under the hood

* `Selected` is a state where users have used that controller in the notebook before (or current session). "Used" means users run a cell.
* If users never use the notebook, they would either see
  * `Select Kernel` if there are multiple kernels, and none of them is preferred.
  * Kernel name if there is one preferred kernel.
  * Kernel name if there is only one kernel.
 
For the later two cases, the kernel is not selected yet, but more or less "suggested". That's why when users open kernel picker, there is no "currently selected" description next to its name.

@setaskin I'd like to know in detail how is this behavior leading to the problem you raised.

**Comment by setaskin** [comment] 2023-01-25 01:11
Hi @rebornix , when Live Share Guest joins the session. There is no indication of kernel selection needs to be made and if guest doesn't understand they need to select a controller and doesn't take any action,  as a result guest doesn't recognize when host runs the cell or output is being produced ect .  I can give you detailed quick demo to show the user experience in terms of Liev Share.  Feel free to ping me via Teams.

**Comment by DonJayamanne** [comment] 2024-12-12 03:15
Duplicate of https://github.com/microsoft/vscode/issues/175272

**Closed by DonJayamanne** 2024-12-12 03:15 UTC
Labels: bug, notebook-kernel-picker
