### ISSUE TITLE
Allow dragging images from web browser into VSCode explorer

### ISSUE THREAD

**Issue by bduffany** [microsoft/vscode#93782] opened 2020-03-30 18:32 UTC
Currently it's possible to drag and drop files from Windows explorer into the VSCode Explorer. It's also possible to drag and drop files from a Web browser (Chrome) into Windows Explorer.

It'd be nice to also be able to drag and drop files directly from the Web browser into VSCode, instead of having to first drag it into Explorer and then VSCode.

**Comment by isidorn** [comment] 2020-03-31 07:29
Somewhat duplicate of https://github.com/microsoft/vscode/issues/91132

**Comment by bduffany** [comment] 2020-03-31 18:43
That issue seems to be describing an issue of dragging from VS Code --> Other apps, where this issue is talking about Other apps --> VS Code. Are you sure that it's the same issue?

**Comment by isidorn** [comment] 2020-04-01 07:30
We can reopen this one if you prefer. Point being if we start looking into improving the DnD behavior we will look it at both directions

**Comment by bduffany** [comment] 2020-04-01 14:00
IMO, it makes more sense to keep this one open, to avoid falling off the radar completely. Wouldn't want someone to later pick up that issue who doesn't have any context for this issue, and then not realize that the problem is in both directions.

**Closed** 2020-06-29 13:57 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by HazemE1** [comment] 2023-08-17 20:33
Hey, 

there were never any updates here is this going to implemented anytime soon ?
