### ISSUE TITLE
Markdown Preview Window Shrink on Zoom

### ISSUE THREAD

**Issue by darrenparkinson** [Microsoft/vscode#20146] opened 2017-02-07 21:53 UTC
- VSCode Version: 1.9.0
- OS Version: MacOS 10.12.1

Steps to Reproduce:

1. Open Markdown file
2. Open Preview to side
3. Press Cmd + to zoom in
4. Available text space on preview is crammed into smaller window with scroll bars

Also happens on Windows.

Thanks.

![image](https://cloud.githubusercontent.com/assets/4262917/22713258/a1e741ee-ed7f-11e6-9187-84c8478762ef.png)

**Comment by mjbvz** [comment] 2017-02-07 21:56
Thanks. This is a duplicate of #5745

**Closed by mjbvz** 2017-02-07 21:56 UTC
Labels: duplicate, markdown, webview
