### ISSUE TITLE
Add "show diff" when user closes not saved file

### ISSUE THREAD

**Issue by Specyk** [microsoft/vscode#124238] opened 2021-05-20 09:50 UTC
When user closes not saved file there are 3 options in saving dialog:
- don't save
- cancel
- save

I think there is missing an extra option "Show diff" which shows the difference between last saved file and current version. Alternatively the difference could be displayed always when saving file dialog appears.

**Comment by MurzNN** [comment] 2021-07-13 13:45
Similar issue https://github.com/microsoft/vscode/issues/62378 is marked as duplicate of #26339 but I think this is wrong, current feature is more precise and much easier to implement.
_P.S. Here also my duplicate of this issue: https://github.com/microsoft/vscode/issues/128539_

**Closed** 2021-07-20 02:32 UTC
Labels: feature-request, workbench-editors
