### ISSUE TITLE
Zooming in messes up rendering of reference count adornments in C# files 

### ISSUE THREAD

**Issue by danroth27** [Microsoft/vscode#15503] opened 2016-11-15 08:10 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|

---

Steps to Reproduce:

1. Open a new .NET Core project in VS Code
2. Zoom in 

![image](https://cloud.githubusercontent.com/assets/1874516/20297892/3e715fea-ab13-11e6-8c6e-4815db9c7c6f.png)

**Comment by kisstkondoros** [comment] 2016-11-15 18:24
Duplicate of #15389

**Comment by ramya-rao-a** [comment] 2016-11-15 22:24
Closing as duplicate. Please use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-15 22:24 UTC
