### ISSUE TITLE
Regex search and replace hangs when trying to enter \n

### ISSUE THREAD

**Issue by geniosity** [Microsoft/vscode#39929] opened 2017-12-08 15:36 UTC
I have a 17MB file and when I search for tab (\t) and replace with another character, the app FLIES!!! Totally surprised.

But, if I try and search for a new line character (\n), it hangs as I press the "n" character. So I get the backslash character in, but I don't actually see the letter "n", the app hangs before it's "drawn" to screen.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
xml|Dot|1.9.2
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.5
Angular2|joh|2.11.2
qub-xml-vscode|qub|1.2.8
java|red|0.15.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by leocb** [comment] 2018-02-13 12:49
I can confirm this is also happening on
Ubuntu 17.10 4.13.0-32-generic #35-Ubuntu
VScode Version 1.20.0

**Comment by pascallaprade-beslogic** [comment] 2018-03-23 15:49
Although I was able to search and replace a `\n` regex easily (to remove every empty line of a file, specific regex was `^\n`, I also have a problem with a `\n`-related regex search: `/\*(.*\n?)*\*/`.

- Pasting the regex immediately hangs VS Code, and a window appears after a few seconds, suggesting to reopen the window.
- Typing the regex manually will hang when typing the fourth `*` character specifically (I reproduced it many times to make sure it was this specific character hanging), so: `/\*(.*\n?)*\` works, then as you type the `*` right after that, it hangs.

This is on VS Code 1.21.1, on Windows 10, both x64.

**Comment by jgrammen-agilitypr** [comment] 2018-06-19 12:41
I am having a similar problem when using search and replace.
my search regex is as follows:
```
^  <%- if (.*\n.*){2,5} <%- end -%>$
```
which consistenly hangs vscode. The file I am searching within is 26 lines long (very small file). 
basic regex with `\n` work fine, but anything slightly complex results in crashes

**Comment by rebornix** [comment] 2018-09-11 17:47
When we have backtracking in the regex, or a normal regex when the file content is really large, VSCode will freeze as we run the search in the main thread. Duplicate of https://github.com/Microsoft/vscode/issues/30874, let's track it there. We should probably search async in a worker if the model is available in the worker.

**Closed** 2018-09-11 17:47 UTC
Labels: *duplicate, bug, editor-find
