### ISSUE TITLE
Seems word wrap don't work

### ISSUE THREAD

**Issue by kenny-reyes** [Microsoft/vscode#20121] opened 2017-02-07 12:49 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|json-tools|eriklynd|1.0.2|
|csharp|ms-vscode|1.6.2|

---

Steps to Reproduce:

1. Try to toggle word wrap
2. Nothing happens

**Comment by mjbvz** [comment] 2017-02-07 21:08
Closing as a duplicate of #19842

@alexandrudima's [comment](https://github.com/Microsoft/vscode/issues/19842#issuecomment-278032572) explains the new behavior here

**Closed by mjbvz** 2017-02-07 21:08 UTC
Labels: duplicate
