### ISSUE TITLE
Sign in stuck in "Loading..." after each new launch of vscode

### ISSUE THREAD

**Issue by skuffe** [microsoft/vscode#123675] opened 2021-05-12 12:15 UTC
- VS Code Version: 1.56.1
- OS Version: Windows 10 10.0.19043

Steps to Reproduce:

1. Sign in to a microsoft or github account, for live share or settings sync
2. Launch new vscode window

The issue seem to be the same or similar to the one mentioned in the now closed issue #95061 on an insider build, which seems to have now exist in the 1.56.1 release as well.

After a minute or two, the "Loading..." disappears and the sign in succeeds, presumable after some sort of timeout has occurred.

![image](https://user-images.githubusercontent.com/1579080/117973286-7c48a280-b32c-11eb-9b06-f040b0b0e938.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by trexx** [comment] 2021-05-12 12:18
I too am effected by this same bug.

Version: 1.57.0-insider (user setup)
Commit: 988902e0bc37c7acba82e2ddde49592d8cb11666
Date: 2021-05-11T13:54:54.372Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by RMacfarlane** [comment] 2021-05-13 19:21
If the sign out information is still retained, then I think this behavior is ok. The accounts are loaded after extensions are activated, and these need to read previous auth information and potentially refresh it on startup, which takes time. If there's no functional impact beyond the menu taking a while to load, I'm going to go ahead and lose this.

**Comment by skuffe** [comment] 2021-05-13 20:21
There's definitely a functional impact, the account is not actually signed in, joining a collaborative session takes 4-5 minutes due to this bug!

**Comment by RMacfarlane** [comment] 2021-05-13 20:26
Ok, can you please open the Output panel and copy what's in the "Microsoft Authentication" channel there? (Or GitHub if you're using that)

**Comment by trexx** [comment] 2021-05-14 08:04
[Error  - 07:59:51.359] Getting token failed: Error: Unable to transform input.

**Comment by trexx** [comment] 2021-05-18 07:32
Further to my comment above.
This timeout occurs when the same account is used to login to both LiveShare and Settings Sync.

Logging in to one or the other, doesn't cause the issue.

**Comment by RMacfarlane** [comment] 2021-05-19 15:06
Thanks for the further details, that's really useful. This looks like a duplicate of https://github.com/microsoft/vscode/issues/117362.

@skuffe Can you confirm that you're seeing the same thing in the output channel/that you're actually being signed out? It sounds like the login information is still there for you, just taking a really long time to load, is that right?

**Comment by skuffe** [comment] 2021-05-20 07:24
Yup, can confirm, similar output here. After the "Loading..." times out, The following is logged in the MS Auth Output channel
```
[Error  - 07:19:48.288] Getting token failed: Error: Unable to transform input.
```

And subsequently login is possible again.
```
[Info  - 07:20:23.903] Logging in...
[Info  - 07:20:27.443] Exchanging login code for token
[Info  - 07:20:28.62] Exchanging login code for token success
[Error  - 07:20:28.63] Unexpected token � in JSON at position 0
[Info  - 07:20:28.63] Failed to fetch token claims from access_token. Attempting to parse id_token instead
[Info  - 07:20:28.63] Login successful
```

**Comment by skuffe** [comment] 2021-05-20 07:25
Version info:
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by RMacfarlane** [comment] 2021-05-20 15:26
Ok, I'm going to go ahead and close this as a duplicate of https://github.com/microsoft/vscode/issues/117362, please subscribe to that issue. Thanks!

**Closed by RMacfarlane** 2021-05-20 15:26 UTC
Labels: authentication, bug
