### ISSUE TITLE
Add feature to resize the IntelliSense window

### ISSUE THREAD

**Issue by Oneliey** [microsoft/vscode#96173] opened 2020-04-26 09:08 UTC
![image](https://user-images.githubusercontent.com/30212642/80302985-f5d42800-87df-11ea-8c59-bce84543a454.png)
Sometime the IntelliSense window is too small to read all information, so I am looking forward to resize the window using mouse, thx~

**Comment by octref** [comment] 2020-04-27 18:18
Duplicate of #29126.

**Closed by octref** 2020-04-27 18:18 UTC
