### ISSUE TITLE
In Built Spell Check

### ISSUE THREAD

**Issue by kingeke** [Microsoft/vscode#43609] opened 2018-02-13 18:56 UTC
### Issue Type
Feature Request

### Description

Can we pleaseeeeeeeeeeeeeeeeeeeeeeeee have an inbuilt spell checker

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

**Comment by usernamehw** [comment] 2018-02-13 19:44
Duplicate of #20266

**Closed** 2018-02-13 20:57 UTC
Labels: *duplicate
