### ISSUE TITLE
Shortcut key for adding semicolon to line end quickly

### ISSUE THREAD

**Issue by monkingame** [Microsoft/vscode#56419] opened 2018-08-15 00:41 UTC
I write javascript with vsc.
Frequently I add semicolon to the end of line.
But sometimes it is not fast. 
e.g. I need move mouse or tap end key or tap arrow key more times.
If a shortcut key(e.g. win [Ctrl+;]  or mac [Command+;] ) help users to add semicolon at the end of line immediately, it will improve efficiency.

**Comment by sandy081** [comment] 2018-08-15 09:25
Duplicate of #24862

**Closed** 2018-08-15 09:25 UTC
Labels: *duplicate, editor
