### ISSUE TITLE
Total amount is not correct

### ISSUE THREAD

**Issue by Canon0223** [Microsoft/vscode#46400] opened 2018-03-23 08:39 UTC
Issue Type: <b>Bug</b>

When I use Ctrl+F  to search a word in a file,the total amount of the word is not correct.
E.g I used this word in 3 places ,but the "total amount" show me 4 or more.And I can't jump to the first places, I can only jump to the opsition 2-4.

VS Code version: Code - Insiders 1.22.0-insider (9160e85b1ab0333dfe697032f90da494f1f81fd4, 2018-03-16T06:17:01.376Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.88GB (10.73GB free)|
|Process Argv|F:\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
vscode-lua|gcc|0.1.2
vscode-power-mode|hoo|2.1.0
Lua|key|0.0.9
vscode-lua|tri|0.9.0
lua-for-vscode|xxx|0.0.23

</details>
Reproduces only with extensions

**Comment by yume-chan** [comment] 2018-03-23 13:56
Duplicate of #45770.

Your Insiders version is too old. In fact it's just the next day's version that fixed this problem.

**Comment by rebornix** [comment] 2018-03-23 18:19
thanks @yume-chan , it's already fixed in following Insiders.

**Closed by rebornix** 2018-03-23 18:19 UTC
