### ISSUE TITLE
Support variables in snippets

### ISSUE THREAD

**Issue by secato** [Microsoft/vscode#13047] opened 2016-09-29 21:41 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 10

Is there anyway to get the filename from a snippet? Something like

```
"Test snippet": {
    "prefix": "test",
    "body": [
        "this is a test snippet",
        "file: $FILENAME"
    ],
    "description": "Test snippet"
}
```

**Comment by alexandrudima** [comment] 2016-10-06 13:46
fyi @jrieken

**Comment by jrieken** [comment] 2016-10-07 08:40
related or dupe of #3210

**Comment by jrieken** [comment] 2016-11-03 15:16
Ideas/requests for variables:  *file name* and *time*

**Comment by jrieken** [comment] 2016-11-03 15:24
Actually, also a dupe of #4956

**Closed by jrieken** 2016-11-03 15:24 UTC
Labels: feature-request, snippets
