### ISSUE TITLE
Quick-Navigation with mouse broken since last update!

### ISSUE THREAD

**Issue by SirHodlington** [microsoft/vscode#77369] opened 2019-07-14 19:07 UTC
Hi,

It used to be possible to use the side-buttons of the mouse to go back/forward between positions in code. This has not worked since the last update. 
I need this feature!!!!

**Comment by mjbvz** [comment] 2019-07-14 19:48
Duplicate of #71318

**Closed by mjbvz** 2019-07-14 19:48 UTC
Labels: editor-contrib
