### ISSUE TITLE
VSCode and Webpack module casing issue

### ISSUE THREAD

**Issue by asadsahi** [Microsoft/vscode#11515] opened 2016-09-04 11:02 UTC
- VSCode Version:
1.4.0
- OS Version:
Windows 10
Node: 6.3.1

Steps to Reproduce:

1. Open VScode
2. Open terminal 

![image](https://cloud.githubusercontent.com/assets/3470892/18230541/a2ef75a2-7296-11e6-80bf-564cf948e786.png)

Running webpack command with drive letter as lowercase c, causing warning on javascript modules:

![image](https://cloud.githubusercontent.com/assets/3470892/18230564/016974de-7297-11e6-8c09-db966a853bce.png)

Same is the case when opening terminal using Ctrl + Shift + C opens command prompt with drive letter as lowercase and running webpack command. 

However when running command prompt from windows programs, which opens it with uppercase driver letter "**C**" when webpack doesn't show any warning. 

So, is there a way to force VScode to open terminal with uppercase C drive which will fix the webpack warnings?

**Comment by Tyriar** [comment] 2016-09-05 01:55
Duplicate of #9448

**Closed** 2016-09-05 01:56 UTC
Labels: debug, integrated-terminal
