### ISSUE TITLE
sub-word navigation doesn't work for upper case snakes

### ISSUE THREAD

**Issue by LegoChicken** [Microsoft/vscode#53685] opened 2018-07-06 09:45 UTC
Issue Type: <b>Bug</b>

The new sub-word navigation doesn't work for "UPPER_CASE_DOES_NOT_WORK", but does for "lower_case_does_work". To reproduce put those strings in an empty file. For upper case it moves character by character. Lower case it moves between words.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|31.89GB (23.58GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|0.19.1
read-only-indicator|ale|0.7.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
matlab|Gim|0.9.0
triggertaskonsave|Gru|0.1.6
vscode-dimmer|hoo|2.1.0
mediawiki|jak|2.1.0
string-manipulation|mar|0.2.0
python|ms-|2018.6.0
cpptools|ms-|0.17.6
PowerShell|ms-|1.7.0
indent-rainbow|ode|7.2.2
vscode-clearcase|Ope|1.12.1
vscode-icons|rob|7.24.0
vscode-hexdump|sle|1.6.0
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
sensitive-replace|vil|0.1.1
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-07-30 21:08
Duplicate of #53645

**Closed by alexandrudima** 2018-07-30 21:08 UTC
Labels: editor-subword
