### ISSUE TITLE
"Select all occurrences of find match" doesn't work when Find window is opened with some text in it

### ISSUE THREAD

**Issue by litera** [microsoft/vscode#91879] opened 2020-03-02 08:14 UTC
Issue Type: <b>Bug</b>

1. Open a file
1. Open Find window (Ctrl+F)
1. Type some text in Find textbox
1. Select text in the document that is different to the text in the Find tool textbox
1. Click Ctrl+Shift+L (or run command "Select all occurrences of find match")

**Expected result:**
Find window should replace its text to the one being selected and all occurrences of the text should be selected.

**Actual result:**
Other occurrences of selected text are not being selected, but rather the text being in the Find window textbox. Find text value doesn't change to the text being selected.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ArturoDent** [comment] 2020-03-04 04:36
I can't reproduce.  Do you see anything I am doing differently:

![findMatches](https://user-images.githubusercontent.com/31813701/75845584-c9c79800-5d96-11ea-9871-ad595fd75f9c.gif)

Version: 1.43.0-insider (user setup)  [same result in standard build]
Commit: 3943d614597f9f7c384846613d417e97ea6d5ab4
Date: 2020-03-03T21:20:08.233Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19569

**Comment by rebornix** [comment] 2020-07-22 18:45
Closing as no update from comment https://github.com/microsoft/vscode/issues/91879#issuecomment-594322069

**Closed by rebornix** 2020-07-22 18:45 UTC
