### ISSUE TITLE
Theme contrast slider/tweaker

### ISSUE THREAD

**Issue by C0D3O** [microsoft/vscode#200480] opened 2023-12-10 14:47 UTC
It would be really nice to have a tweaker that tweaks the contrast of overall theme color, or contrast between background and fonts etc. For example I made my own color tokens, picked the colors and it looks good, but it would become perfect if the contrast of the colors would be a bit higher. So the only way to do it ( and really not obvious, not visual one ) is to go through all my custom color and change the brightness a bit, which will take a lot time and effort. Instead this little slider thing, a floating little window with a slider for example that changes contrast of all color would make it a lot easier and visual and perfect and good and great.

**Comment by aeschli** [comment] 2023-12-11 14:00
duplicate of https://github.com/microsoft/vscode/issues/200451

**Closed by aeschli** 2023-12-11 14:00 UTC
