### ISSUE TITLE
terminal errado toda vez

### ISSUE THREAD

**Issue by gumiranda** [microsoft/vscode#132680] opened 2021-09-08 18:00 UTC
Issue Type: <b>Bug</b>

DEFINI COMO TERMINAL PADRÃO O BASH MAS TODA HORA ABRE ESSE POWERSHELL

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.98GB free)|
|Process Argv|C:\\Users\\gustavoaguiar\\Documents\\web-react-1 --crash-reporter-id fce09fae-2d44-423d-a373-45a738255948|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-expo|byC|0.7.3
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
copilot|Git|1.4.2628
vscode-styled-components|jpo|1.6.6
vscode-docker|ms-|1.16.1
vscode-language-pack-pt-BR|MS-|1.60.3
remote-containers|ms-|0.194.0
vscode-typescript-next|ms-|4.5.20210907
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.6.1
color-highlight|nau|2.4.0
sonarlint-vscode|Son|2.1.2
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.398
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.2.2

(1 theme extensions excluded)

</details>

**Comment by UrszulaCzerwinska** [comment] 2021-09-08 18:21
I have the same problem!

**Comment by IllusionMH** [comment] 2021-09-08 18:28
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-08 18:29 UTC
Labels: *duplicate
