### ISSUE TITLE
Code ignores setting of workbench.list.openMode

### ISSUE THREAD

**Issue by nebenjamin** [Microsoft/vscode#67074] opened 2019-01-24 17:09 UTC
- VSCode Version: Code - Insiders 1.31.0-insider (50854c0a705745bbf50982fab3c30fd6bd1f7b19, 2019-01-24T09:15:00.061Z)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Set the setting of workbench.list.openMode to "doubleClick".
2. Single-click on a file in the explorer list.
3. The file opens in a preview tab (if preview tabs are enabled, in a new tab if they aren't).

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment] 2019-01-24 20:12
Nope, this is definitely a regression.

**Comment by joaomoreno** [comment] 2019-01-24 20:12
@isidorn Another reason to simply listen on the `open` event... I'll fix it.

**Comment by joaomoreno** [comment] 2019-01-25 09:59
Dupe of #65252

**Closed** 2019-01-25 10:07 UTC
Labels: *duplicate, file-explorer, list
