### ISSUE TITLE
Select all inside webview inputs is not working

### ISSUE THREAD

**Issue by arjun27** [Microsoft/vscode#53416] opened 2018-07-02 05:04 UTC
Issue Type: <b>Bug</b>

The keyboard action cmd+A does not trigger text selection inside an input field of a webview. From my debugging, the keyboard event gets intercepted by vscode, and is never received by the webview. These closed issues seem to be related:

- https://github.com/Microsoft/vscode/issues/50735
- https://github.com/Microsoft/vscode/pull/38387

This is affecting my extension ([Slack Chat](https://github.com/karigari/vscode-chat/issues): https://github.com/karigari/vscode-chat/issues/22) and I would be happy to send in a PR once the team can confirm it is required.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 4|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.1
prettier-vscode|esb|1.5.0
chat|kar|0.3.2
python|ms-|2018.6.0
vsliveshare|ms-|0.3.335
java|red|0.27.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-07-02 07:06
Duplicate of #8794

**Closed by mjbvz** 2018-07-02 07:06 UTC
