### ISSUE TITLE
The editor highlights errors, despite the fact that the code runs fine

### ISSUE THREAD

**Issue by cawa-93** [Microsoft/vscode#20976] opened 2017-02-21 07:21 UTC
* **VSCode Info**:
Версия 1.9.1
Фиксация f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Дата 2017-02-08T23:44:55.542Z
Оболочка 1.4.6
Обработчик 53.0.2785.143
Node 6.5.0
- **OS Version**: Ubuntu 16.04

The editor highlights errors, despite the fact that the code runs fine

![image](https://cloud.githubusercontent.com/assets/1662812/23154525/ee4ad4d2-f816-11e6-94b1-76291ea7b080.png)

**Comment by jrieken** [comment] 2017-02-21 09:32
In what language does that happens? What extensions do you have installed?

**Comment by cawa-93** [comment] 2017-02-21 09:38
@jrieken 
* Code in `javascript`
* File `*.vue`
* VSCode read this file as `html`
* Installed onle one extension: [Vue 2 Snippets](https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets)

**Comment by mjbvz** [comment] 2017-02-21 19:45
@aeschli Vue files were previously being handled by the html extension, correct? If so, this may be a duplicate of #19629

**Closed by mjbvz** 2017-02-21 19:45 UTC

**Comment by cawa-93** [comment] 2017-02-22 14:26
@mjbvz If you disable the extension result is the same
