### ISSUE TITLE
Allow to focus on definition peek/preview

### ISSUE THREAD

**Issue by khoitd1997** [microsoft/vscode#72317] opened 2019-04-15 07:12 UTC
Hi, when I'm peeking/previewing the code definition, it usually takes a click to focus and allow the peek window to register any key, this makes it necessary to use a mouse to work with peeks.I understand that focusing by default makes it not possible to use the enter key to jump to the file but there should be an option to select.

**Comment by jrieken** [comment] 2019-05-28 12:11
closing in favour of, as duplicate of #64530

**Closed** 2019-05-28 12:11 UTC
Labels: *duplicate, editor-contrib, editor-symbols, feature-request
