### ISSUE TITLE
Escape doesn't close the peek view

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67010] opened 2019-01-23 19:20 UTC
- Do find all refs in peek view
- Press escape
- Nothing happens

Keybinding issue? Doesn't seem that any other command is being executed so I assume the event is being intercepted somewhere else. But it works for other things like the find widget.

**Comment by usernamehw** [comment] 2019-01-23 19:48
If peek widget uses new tree then duplicate of #66926

**Closed** 2019-01-23 19:50 UTC
Labels: *duplicate
