### ISSUE TITLE
Restore notebooks after reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93000] opened 2020-03-19 10:35 UTC
There is this https://github.com/microsoft/vscode/blob/d1354bb26be8d41ea713a837d70d16e5a93f5475/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L79-L82 

In theory it should enable notebooks to be restored after reload but often the webview doesn't make it...

**Comment by jrieken** [comment] 2020-03-26 09:51
@rebornix I have pushed a change to restore notebook inputs after reload. This works OK but the webview isn't happy when reloading 2 or more notebooks after start...

**Comment by rebornix** [comment] 2020-03-26 18:53
I think the issue you see is a duplicate of https://github.com/microsoft/vscode/issues/92128 , let's track it there.

**Comment by rebornix** [comment] 2020-03-26 18:59
If I have two editor groups opening the same notebook, after reloading the window, one of the editor group never finished opening. Will investigate.

<img width="1976" alt="image" src="https://user-images.githubusercontent.com/876920/77685775-32023780-6f59-11ea-9a95-2baac610dd70.png">

**Closed** 2020-03-26 22:12 UTC
Labels: notebook

**Comment by rebornix** [comment] 2020-03-26 22:14
Fixed.

<img width="2168" alt="image" src="https://user-images.githubusercontent.com/876920/77701874-73541080-6f74-11ea-95f8-d8c37b7bee3f.png">
