### ISSUE TITLE
VS Code HTML Class Intellisense stopped working

### ISSUE THREAD

**Issue by MainaWycliffe** [Microsoft/vscode#24377] opened 2017-04-09 19:27 UTC
I have a new issue regarding HTML css class intellisense, it was working brilliantly until recently, when i type class, no suggestions are offered. I just uninstalled a couple extensions (Not those extensions that offered CSS class intellisense). The interesting thing in a new line, if i start typing the names of a class like fa-* or btn*, i get a suggestion of all classes i have but inside a class. PHP, Other html intellisense like Angular ng* works perfectly only classes

- VSCode Version: 1.11.1
- OS Version: Windows 10 (Anniversary Update)

**Comment by aeschli** [comment] 2017-04-10 14:42
duplicate of https://github.com/Zignd/HTML-CSS-Class-Completion/issues/43

**Closed by aeschli** 2017-04-10 14:42 UTC
