### ISSUE TITLE
Deleted code after update

### ISSUE THREAD

**Issue by Diggsey** [Microsoft/vscode#61995] opened 2018-10-28 20:20 UTC
I'd been using VSCode for a while when I noticed it had become sluggish (seemed like GC pauses every few seconds, VSCode was showing high CPU usage in task manager). I decided to restart the editor to see if it would fix the problem.

I saved, and then hit close. The editor closed normally without displaying any kind of dialog, and then an "update" dialog flashed up briefly with a progress bar. I re-opened the editor, and it showed me the "what's new" page. I switched back to the file I was editing and it was completely empty. I checked the file on disk, and that too was showing zero bytes. I checked the recycle bin, and there were no recent items added.

I use version control for my projects, but in this case it was a new file, and I'd written several hundred new lines of code since last commit. I don't expect my editor to truncate files already saved to disk with no warning!

- VSCode Version: 1.28.2 (after update)
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Probably

**Comment by Diggsey** [comment] 2018-10-28 22:29
Visual Studio did not stop responding, it simply became sluggish: I was still able to save the file, and the operation appeared to complete successfully. I did not change any settings around saving files during the event or before - it is using default settings.

Note: I am not unhappy about it losing unsaved changes: that would be more acceptable. I am unhappy about it completely truncating the file, which had been saved many times before. It shows that there is a bug in either the update, or the saving process, as it appears to be non-atomic, such that an error during saving can result in the pre-existing file being lost.

**Comment by Dob6458** [comment] 2018-10-28 22:35
Try to reinstall Visual Studio code or reinstall Windows with reset if it is work.

**Comment by Diggsey** [comment] 2018-10-28 22:58
@Dob6458 thanks for your helpful advice... Somehow I doubt reinstalling windows is going to restore the lost file.

**Comment by Dob6458** [comment] 2018-10-28 23:06
@Diggsey You're welcome :)

**Comment by joaomoreno** [comment] 2018-10-30 11:13
@bpasero User had his files truncated.

**Comment by Dob6458** [comment] 2018-10-30 12:19
Hi @Diggsey,
For example, If you want to save automatically your files, copy this code in `settings.json`.
```json
  "files.autoSave": "afterDelay"
```

**Comment by bpasero** [comment] 2018-10-30 13:31
@Diggsey if the file was not dirty, I recently pushed a fix where there was a chance that we first truncate the file and then writing the contents failed for some reason. We now retry to write the contents into the file after a short timeout. 

If the file was dirty and the save failed for some other reason, it would have been restored after the next startup. So my guess would be that the file was not dirty.

I assume you cannot reproduce this anymore?

**Comment by Diggsey** [comment] 2018-10-30 13:38
That sounds likely. Is that fix included in my current version? (1.28.2)

**Comment by bpasero** [comment] 2018-10-30 13:45
@Diggsey no, only in our insiders version (1.29) which should be released to stable next week.

**Comment by Diggsey** [comment] 2018-10-30 14:08
Happy to close this when the fix is released.

**Comment by bpasero** [comment] 2018-10-30 14:18
Oke, lets close it and you report back if it ever happens again with our stable 1.29 next week,

**Closed by bpasero** 2018-10-30 14:18 UTC
Labels: needs more info
