### ISSUE TITLE
Contents missing when cut folded text

### ISSUE THREAD

**Issue by YuanshengZhao** [microsoft/vscode#50510] opened 2018-05-26 17:43 UTC
- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. type "x[\n][space]y", and fold it.
![image](https://user-images.githubusercontent.com/37881856/40578868-9252496c-610b-11e8-9ef9-d99ece4ae686.png)
![image](https://user-images.githubusercontent.com/37881856/40578873-a2689dce-610b-11e8-9f0f-e8a4f5848bba.png)
2. CTRL-A and CTRL-X, the "x" and "y" disappeared altogether.
![image](https://user-images.githubusercontent.com/37881856/40578889-dc2c9a06-610b-11e8-94a3-9c64a97a02b3.png)
3. CTRL-V, only the "x" reappeared, and the "y" is lost.
![image](https://user-images.githubusercontent.com/37881856/40578898-0a8e54ca-610c-11e8-9217-0557cd66e96a.png)

However, if I select all the text manually and cut, only "x" will get cut, but "y" will not.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment] 2018-05-28 12:40
Likely a problem of the cut action

**Comment by rebornix** [comment] 2018-06-06 22:33
This happens when we run copy on Folding ranges as well. The root cause is the `textAreaHandler` tracks `ViewCursor` instead of the model state of cursors. For example

```
a {
 }
```

If we run Fold All and Select All, the code now looks like

```
a {...
```

The view state of the selection is `{startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 4}` while the actual selection on model is `{startLineNumber: 1, startColumn: 1, endLineNumber: 2, endColumn: 3}`. The Copy/Cut works properly on text model but we save the wrong content into clipboard. 

@alexandrudima do you think we can put cursor's model info (I don't know if it has a better name) into `ViewCursorStateChangedEvent`?

**Comment by alexandrudima** [comment] 2018-06-11 10:42
@rebornix We could enhance `ViewCursorStateChangedEvent` and then store the original model selection in `textAreaHandler`.

We could pass the model range in `getPlainTextToCopy` and in `getHTMLToCopy`, but care must be taken that those methods are adapted to take in model ranges instead of view ranges.

**Comment by alexdima** [comment] 2020-02-04 20:55
Also fixed by ee9e25effcc736ad03fc5eeedf1cf49169d500a9

**Closed by alexdima** 2020-02-04 20:55 UTC
Labels: bug, editor-core
