### ISSUE TITLE
Processes stress CPU

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#40294] opened 2017-12-15 12:53 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T06:08:07.643Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
vscode-jira|Kni|0.5.2
material-icon-theme|PKi|3.1.0
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.7
vscode-file-peek|abi|1.0.1
yaml|ada|0.0.9
Bookmarks|ale|0.18.0
numbered-bookmarks|ale|0.11.0
vscode-processes|and|0.0.4
vscode-intelephense-client|bme|0.8.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.4.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.0.0
php-debug|fel|1.12.1
sass-lint|gle|1.0.1
vscode-dimmer|hoo|2.1.0
smarty|imp|0.2.0
docthis|joe|0.6.0
vscode-scss|mrm|0.6.2
color-highlight|nau|2.3.0
vsnotes|pat|0.4.3
vscode-code-outline|pat|0.0.12
sass-indented|rob|1.4.5
vim|vsc|0.10.6
twig|wha|1.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Go into insert mode.
2. Try to enter text.

Reproduces without extensions: No
![image](https://user-images.githubusercontent.com/30625381/34042959-3c6f8e60-e19f-11e7-9203-13dccd785322.png)

**Comment by jrieken** [comment] 2017-12-15 13:04
Can you check with F1 > Show Running Extensions?

**Comment by bm-stschneider** [comment] 2017-12-15 14:17
And then? nothing out of the ordinary as I can see.

**Comment by jrieken** [comment] 2017-12-15 14:29
Sorry, forget some of the instruction... In that view you'll find a button to create a CPU profile of the extension host process. Please profile for a few seconds (while it sits at100%) and find the extension consuming most CPU cycles (it will sorted atop and there will be little chart next to each of them)

**Comment by bm-stschneider** [comment] 2017-12-15 14:33
Ah okay, that helped 
![image](https://user-images.githubusercontent.com/30625381/34046428-579cfb7e-e1ad-11e7-9b7e-32efc33f5efa.png)

**Comment by KnisterPeter** [comment] 2017-12-15 14:42
@bm-stschneider Probably you can have a look at that. Right now I have litte time to care about the jira extension.

**Comment by jrieken** [comment] 2017-12-15 14:55
Good find, I'll close this as caused by extension and leave it up to you two. Btw, from the same menu you can save the CPU-profile to disk, share it, and then open it in Chrome-devtools.

**Closed** 2017-12-15 14:55 UTC
Labels: *caused-by-extension, insiders, needs more info
