### ISSUE TITLE
Tasks are not detected

### ISSUE THREAD

**Issue by oliversturm** [Microsoft/vscode#35734] opened 2017-10-06 15:30 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.8.0-59-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
indenticator|Sir|0.4.2
prettier-vscode|esb|0.24.0
hungry-delete|jas|1.3.3
graphql-for-vscode|kum|1.6.2
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
embrace|myc|1.0.0
yo|sam|0.9.3
visualclojure|sti|0.0.2
ayu|tea|0.8.0

(4 theme extensions excluded)

---

My package.json contains scripts:

```
  "scripts": {
    "start": "gulp watch",
    "build": "gulp build",
    "debug": "node --inspect-brk dist/index.js",
    "serve": "forever -a -v -m 20 --minUptime 20000 --spinSleepTime 20000 --no-colors  dist/index.js"
  },
```

According to [this](https://code.visualstudio.com/docs/editor/tasks), these should be auto-detected. However, I see "no tasks found" when I enter `task` in the command window.

I also have `gulpfile.js` in the project, with tasks `build` and `lint` defined. According to the same URL, I was expecting these to be auto-detected as well - they are not.

So I create my own task. After quite a bit of fixing the standard templates (they have `taskName`, for instance), I ended up with this:

```
{
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "label": "build",
      "type": "npm",
      "script": "build"
    }
```

However, this task is still not being detected. If I *Run Build Task* from the menu, the message says "No build task to run found".

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment] 2017-10-06 15:43
This works for me.

![capture](https://user-images.githubusercontent.com/1931590/31286222-cc64c350-aabd-11e7-93c8-c4a528336ed4.png)

@egamma assigning to you to follow up since it is npm auto detection.

**Comment by oliversturm** [comment] 2017-10-06 15:57
Good to know :) Doesn't work for me at all though!

![image](https://user-images.githubusercontent.com/4730969/31286857-61b58662-aab7-11e7-99ce-64efcb396bdb.png)

**Comment by oliversturm** [comment] 2017-10-06 15:58
I see your *needs more info* and raise you by a *ask me anything*.

**Comment by egamma** [comment] 2017-10-08 21:48
@oliversturm do you already have a `tasks.json` in the .vscode folder? If yes can you pls attach it. Can you try whether it works when you temporarily remove the file.

Can you try whether task detection works for you for our smoke test repository:
- git clone https://github.com/Microsoft/vscode-smoketest-express.git
- cd vscode-smoketest-express
- code .
- execute  "Run Task..."

**Comment by oliversturm** [comment] 2017-10-09 08:56
@egamma I guess I've found what the problem is. The smoke test repo works fine - I think I have a structural issue. My "project folder" is set up like this:

* TOP LEVEL
  * .vscode
    * tasks.json
  * SUB PROJECT 1
    * package.json
    * ...
  * SUB PROJECT 2
    * package.json
    * ...

I could imagine task detection to work "on the fly", checking the relevant package.json for a given source file I'm currently editing - not sure whether that would be totally intuitive to everybody, and I guess it just doesn't work that way.

In a similar way, I could imagine a task being executed magically in the "correct" sub-folder, again depending on current editor status. Again, I guess it doesn't work that way. Meanwhile, I don't understand why the content of my tasks.json is ignored completely. Is it the absence of package.json relative to (i.e. one level above) tasks.json? If so, an error message would be nice!

How can I work with tasks in vscode given this project structure? I'm not using lerna at the moment, but I could - would that make a difference?

**Comment by egamma** [comment] 2017-10-09 19:44
@oliversturm there is a feature request open to also scan package.json in subfolders.

>How can I work with tasks in vscode given this project structure?

The insider version supports what we call Multi Root workspaces. With this support you can create a workspace with the roots subproject 1, subproject 2.

>Meanwhile, I don't understand why the content of my tasks.json is ignored completely.

Can you add your task.json? I speculate you are using a tasks.json with a version < 2.0?

**Comment by oliversturm** [comment] 2017-10-10 09:29
@egamma Thanks, I'll check out the insider version.

I hadn't posted the tasks.json because it really only contains the snippet I showed earlier. It's version 2.0:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "label": "build",
      "type": "npm",
      "script": "build"
    }
  ]
}
```

**Comment by egamma** [comment] 2017-10-12 13:40
@oliversturm I can reproduce the behaviour. 

The issue is that you have a customization for a build task, but this task cannot be found since you have no package.json at this level.

What you can do is to define a shell task that invokes npm

        {
            "taskName": "hello",
            "type": "shell",
            "command": "cd yourfolder; npm build"
        }

@dbaeumer do you have other ideas? I also suggest to improve the error message when a configured task cannot be found, that is no task is detected, but there is a customization for a task defined in the task.json.

**Comment by oliversturm** [comment] 2017-10-12 13:45
@egamma That sounds plausible. However, I only created the task initially because I saw the auto-detection not working - before that I didn't have any tasks, and none were detected either.

I can't help but think that the current behavior is trying to be overly clever... I would have found out what the problem was long ago if I had been able to see and run the task and it would have then failed with a message saying that package.json couldn't be found. Instead the task is being hidden without any message, which prompted this whole investigation.

Thanks for the hint about the shell task, I'll try that.

**Comment by dbaeumer** [comment] 2017-10-13 06:48
@oliversturm there should have been a message in the task output panel indicating that the task to run couldn't be found. Did that show up?

**Comment by dbaeumer** [comment] 2017-10-13 06:50
@oliversturm I tested it and there is actually no message. Will look into why.

**Comment by dbaeumer** [comment] 2017-10-13 09:38
No issuing an error for tasks configured in the tasks.json for which no task got contributed. The message looks like this:
```
Error: No task has been contributed for the following task configuration:
{
    "type": "npm",
    "script": "build",
    "label": "npm: build"
}
The task configuration will be ignored.
```

**Comment by oliversturm** [comment] 2017-10-13 10:13
@dbaeumer I find the expression "no task has been contributed" a bit abstract. I guess it means that for some reason, the parameters configured in the task definition can't be used to successfully run a task. Shouldn't there be an error available from some lower level module that would be more descriptive? For instance, for npm I would expect that some kind of module somewhere knows whether the error was due to a missing package.json, or rather due to the script item missing.

Better this message than none at all - but there's room for improvement.

**Comment by dbaeumer** [comment] 2017-10-13 10:30
@oliversturm in your case there is no lower level module that could have caught that. the npm task detection got invoked correctly but it didn't return any tasks since it by current implementation doesn't look into folders. 

But I agree that contributed is misleading here. I will change this to auto detected  and add a sentence that the npm subsystem didn't return a task.

**Comment by oliversturm** [comment] 2017-10-13 10:35
@dbaeumer I apologize if I'm not using the correct terminology! :)

What I mean is that the "npm task detection" must know that it wasn't able to return a task because package.json couldn't be found. So an error message could include "Couldn't find package.json in <folder>." Right?

**Comment by dbaeumer** [comment] 2017-10-13 10:46
@oliversturm you didn't use the wrong terminology. The flow is different. We ask the npm task detection for all task and then merge them with what we see in the tasks.json using the task type. We do have an item to resolve tasks to limit the task list instead of always showing all tasks but that is not implemented yet.

However I tweak the message to make it more clear from where the problem comes:

```
Error: The npm task detection didn't contribute a task for the following configuration:
{
    "type": "npm",
    "script": "build",
    "label": "npm: build"
}
The task  will be ignored.
```

**Comment by oliversturm** [comment] 2017-10-13 10:49
@dbaeumer Ah yes, I see what you mean. I like the improved message better than the first one.

**Comment by dbaeumer** [comment] 2017-10-18 08:05
@egamma assigning back to you. The original request of looking into sub folders is still fair.

**Comment by egamma** [comment] 2017-10-18 13:44
> The original request of looking into sub folders is still fair.

@dbaeumer agreed and there is already a feature request for this. Closing as a duplicate of #31217

**Closed by egamma** 2017-10-18 13:44 UTC
Labels: tasks
