### ISSUE TITLE
Label in problems panel is slightly clipped when using horizontal scrolling

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67498] opened 2019-01-29 21:56 UTC
Testing #67275

- Enable horizontal scrolling
- Get a long error in the problems pane
- Scroll horizontally to see the end of the problem label
- Even when scrolled all the way to the right, it's slightly clipped  

![image](https://user-images.githubusercontent.com/323878/51943143-9d8c5b80-23cd-11e9-8273-4b0aaf93c30e.png)

**Comment by joaomoreno** [comment] 2019-01-30 06:32
@sandy081 This happens because you may have decorations coming up after the row was first rendered. If so, you should notify the tree that the row's width could have possibly changed, through the `updateWidth(element`) API.

**Comment by gregvanl** [comment] 2019-02-26 22:14
Still see clipping as can't scroll far enough.

![image](https://user-images.githubusercontent.com/12818376/53450330-ca359200-39d0-11e9-89fc-b05494cfcffd.png)

**Comment by sandy081** [comment] 2019-02-27 08:10
@gregvanl Is it when you enable horizontal scrolling?

**Comment by sandy081** [comment] 2019-02-27 08:33
Ignore my previous comment, I can repro it.

**Comment by sandy081** [comment] 2019-02-27 08:33
Moving to march as this is not a regression.

**Comment by sandy081** [comment] 2019-03-20 17:56
@joaomoreno There are no decorations in the message row other than highlights. So not sure when I have to call `updateWidth`?

**Comment by joaomoreno** [comment] 2019-03-21 08:21
Make sure the width measured [here](https://github.com/Microsoft/vscode/blob/50d5be49fdf6b354a974929257421e714a956aef/src/vs/base/browser/ui/list/listView.ts#L622) makes sense.

**Closed** 2019-03-26 15:14 UTC
Labels: bug, error-list
