### ISSUE TITLE
[Terminal] Selection is a few characters off

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#34475] opened 2017-09-15 16:02 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (b0c0634339c6f64a5c7f08b56fe732fb9154d3c4, 2017-09-15T05:24:23.107Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|5.0.0
tslint|eg2|1.0.7
vscode-icons|rob|7.12.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Have text in the integrated terminal.
2. Select text.

![vs code selection](https://user-images.githubusercontent.com/1019478/30492216-999c6f7e-99f4-11e7-8a5d-41f17c525744.gif)

**Comment by roblourens** [comment] 2017-09-19 15:44
Probably a duplicate of https://github.com/Microsoft/vscode/issues/34184

**Closed by roblourens** 2017-09-19 15:44 UTC
Labels: insiders, integrated-terminal
