### ISSUE TITLE
Sync Changes button doesn't go

### ISSUE THREAD

**Issue by udayasindhu** [microsoft/vscode#154493] opened 2022-07-08 11:15 UTC
Issue Type: <b>Bug</b>

Sync Changes button always there, even after i take the latest and synced with latest changes.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|2.6.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-07-08 11:45
Related to #154478

**Comment by lszomoru** [comment] 2022-07-08 12:43
Closing this as duplicate of https://github.com/microsoft/vscode/issues/154478.

**Closed by lszomoru** 2022-07-08 12:43 UTC
Labels: git, new release
