### ISSUE TITLE
SourceControl view breaks after non deterministic amount of commits (SVN repository)

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#102586] opened 2020-07-15 10:45 UTC
Issue Type: <b>Bug</b>

Hi,
after the update of VScode from 1.46 to 1.47 I'm running into issues with SourceControl view.
Premise: I work with SVN repository with TortoiseSVN extension and it worked until the recent VSCode update.

I can't help you to determine the exact steps to replay the bug, however, I can tell that after some commits made to SVN repository and changing files' contents afterwards, the sourceControl panel seems to break and doesn't show any files I've just modified.
I'll append screenshots of both graphical issue and error logged in devTools
I have to restart VSCode to make it visible again.

![IssueVSCodeVCSPanel](https://user-images.githubusercontent.com/43338672/87536153-ed7de180-c698-11ea-9d6c-43682d3b1323.jpg)
![IssueVSCodeVCSPanelDevToolsMessage](https://user-images.githubusercontent.com/43338672/87536154-ee167800-c698-11ea-94b4-4b9813c5544f.jpg)

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.7
githistory|don|0.6.6
gitlens|eam|10.2.2
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.8
beautify|Hoo|1.5.0
svn-scm|joh|2.11.5
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
eml|lei|0.4.0
HTMLHint|mka|0.8.0
vscode-filesize|mkx|2.1.4
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.7
color-highlight|nau|2.3.0
vetur|oct|0.24.0
vscode-yaml|red|0.8.0
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
vscode-sql-beautify|sen|0.0.4
open-in-browser|tec|2.0.0
vscode-icons|vsc|10.2.0
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-07-15 13:29
Maybe related to #102358, for which a fix is due in 1.47.2 and is probably already in Insiders. Are you able to try Insiders? It can coexist with Stable.

**Comment by IperStan** [comment] 2020-07-15 13:51
I'm can't switch to the insiders version right now, but reading the related issue it's basically identical.
If for any reason you want to connect my issue report to the aforementioned you are welcome!

**Comment by gjsjohnmurray** [comment] 2020-07-15 15:54
I suggest we leave this open until 1.47.2 is out and you've been able to verify it's resolved.

**Comment by joaomoreno** [comment] 2020-07-16 08:00
I'm pretty sure this is a duplicate of https://github.com/microsoft/vscode/issues/102358, so I'll close it for now, but you can always comment in case you still reproduce the issue once 1.47.2 is out and you can still reproduce.

**Closed by joaomoreno** 2020-07-16 08:00 UTC
Labels: new release
