### ISSUE TITLE
every time vim in the bash edits file  always trigger the p-key which automately copy the trash into the file. This is shit !

### ISSUE THREAD

**Issue by liangtb** [Microsoft/vscode#34583] opened 2017-09-18 19:01 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
python|don|0.7.0
cpptools|ms-|0.12.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment] 2017-09-18 21:45
Can you clarify a few things?
- You are using vim, but where? In the editor? In the integrated terminal? Which bash are you using in the terminal?
- Can you share repro steps? Screenshots or videos/gifs can be helpful

**Comment by liangtb** [comment] 2017-09-19 01:36
vim 8.0.10 in the integrated bash or zsh, both this situation happened, but in the MACOS system bash or zsh is ok for vim, this situation only happened in the  integrated editor both bash and zsh.
My steps is simple, install VScode whatever which version, then type vim in the integrated terminal bash or zsh, and type temple in the vim, then key-yy, and :wq in the vim, type the vim repeatedly. In the next entry to the vim, you will see vim key-p the paste board content for information without your consent, but never happen in the MACOS system bash or zsh.
This is the biggest bug in the VScode!!!

**Comment by liangtb** [comment] 2017-09-19 02:19
vim 8.0.10 in the integrated bash or zsh, both this situation happened, but in the MACOS system bash or zsh is ok for vim, this situation only happened in the  integrated editor both bash and zsh.
My steps is simple, install VScode whatever which version, then type vim in the integrated terminal bash or zsh, and type temple in the vim, then key-yy, and :wq in the vim, type the vim repeatedly. In the next entry to the vim, you will see vim key-p the paste board content for information without your consent, but never happen in the MACOS system bash or zsh.
This is the biggest bug in the VScode!!!

**Comment by liangtb** [comment] 2017-09-19 02:43
I didn't install any plugin in this situation which vim repeatedly called the key-p to paste anything but in the paste board. Microsoft making a shit.

**Comment by liangtb** [comment] 2017-09-19 03:05
I figure out that this problem come from the specific vim version which from the source fo brew, using the macos default vim is ok.
please contact brew make compatible this vim with VScode.

**Comment by ramya-rao-a** [comment] 2017-09-19 06:10
So you are saying that this problem occurs when you build vim from source using brew?

**Comment by liangtb** [comment] 2017-09-19 06:16
yes, the vim from the root@apple.com is ok.

**Comment by liangtb** [comment] 2017-09-19 06:35
This version of VScode is seriously incompatible with SpaceVim and has many problems with integrated terminal which installed SpaceVim.

**Comment by oleblaesing** [comment] 2017-09-19 10:48
Yup, can confirm. However it seems to be a problem with the integrated terminal running zsh. If you type any command into zsh, does the command get printed out in a new line?

**Comment by liangtb** [comment] 2017-09-19 10:50
yes, This happened to me.

**Comment by Tyriar** [comment] 2017-09-28 15:16
Does anyone have reliable/precise repro steps for this? I just tried to:

```
brew install vim
/usr/local/Cellar/vim/8.0.1150/bin/vim
```

It seems to work just fine.

**Comment by oleblaesing** [comment] 2017-09-28 22:00
Do you use zsh? I only can reproduce this behaviour with zsh. bash works fine for me, too.

**Comment by Tyriar** [comment] 2017-09-29 00:39
I tried with both zsh and bash.

There was a similar issue to this before but there was also no repro. I suspect this is something about the environment triggering this behavior, just not sure what it could be as it only seems to affect vscode's terminal.

**Comment by Tyriar** [comment] 2017-09-29 09:20
I found the other issues, let's close this in favor of https://github.com/Microsoft/vscode/issues/34145

**Closed by Tyriar** 2017-09-29 09:20 UTC
Labels: integrated-terminal, needs more info
