### ISSUE TITLE
Make it easier to change default paste method

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188942] opened 2023-07-26 16:39 UTC
When pasting a plain text URL I see this:

![image](https://github.com/microsoft/vscode/assets/2193314/a9fc1c60-0f00-4682-976f-8c0a61882809)

Personally I don't think this should be the default when pasting plain text, but I'm fine with it if it's easier to change the default. Instead of digging through settings we should have a separator and then a way to change the default paste behavior in the dropdown (Set default paste [for mime type]?)

![image](https://github.com/microsoft/vscode/assets/2193314/c5c4b251-bd9c-4d87-a6d4-a88234a3cc67)

I only just noticed this now because I had `"editor.pasteAs.enabled": false` set

**Comment by mjbvz** [comment] 2023-07-26 17:13
Duplicate of https://github.com/microsoft/vscode/issues/188871 

Currently we're also discussing:

- Only enable this feature if you have a selection: https://github.com/microsoft/vscode/issues/188871
- Disabling this feature in other cases, such as when your cursor is inside of a word
- If this feature is ready to by enabled by default this iteration

**Closed by mjbvz** 2023-07-26 17:13 UTC

**Comment by Tyriar** [comment] 2023-07-26 17:21
Oh it's still only Insiders? Sounds good 👍
