### ISSUE TITLE
Viewport tokenization heuristic doesn't work well for PHP files

### ISSUE THREAD

**Issue by gsfarm** [microsoft/vscode#138822] opened 2021-12-10 07:25 UTC
- VS Code Version: 1.63
- OS Version: Ubuntu 21.10, Windows 11

In the latest version of VS Code with the new function "Preview themes before installing" - themes are applied very slowly. In files with 1000+ lines of code, you have to wait 5, 10, 20 seconds or more. The animation of the file coloring is also visible in small modules.

I checked it in PHP, JS, TS, checked it in Windows 11, Ubuntu 21.10. On machines with SSD, M.2 disks, with 16 and 32 gigabytes of memory, with powerful processors. I also installed the VS Code Insiders 1.64 version, the new slowly-themes-engine is saved there. I also tested syntax highlighting without any extensions.

It became hard to work, because the main power of the VS Code is in its speed, in how you can move between files, travel freely between thousands of files of large projects, with search and quick views. And now "twitching" interferes everywhere.

Steps to Reproduce:

1. Open any file
2. Watch the animation of coloring code

Demo video: https://drive.google.com/file/d/1DB3ADuJRW_pvhbkqCDcAI_2w3HRMnDNt/view

https://user-images.githubusercontent.com/5047891/145640407-b265079d-40bc-496d-a116-486957bdcf04.mp4

**Comment by aeschli** [comment] 2021-12-10 15:05
The new feature `Preview themes before installing` does not impact the way that the colorization works. But are you maybe now using a new theme that is more complex?
Do you see it with all themes?

**Comment by gsfarm** [comment] 2021-12-10 17:41
@aeschli I don't think this problem is related to the new theme preview feature. I tested in different environments (Linux, Windows, WSL2), with different themes.

What do you mean, "a more complex theme"? I think the syntax highlighting on the one same principle anyway.

The preview-video shows how slowly the color scheme appears. In files with 1000 and more lines, it takes several seconds (I can't show it with an example of working code). It started right after the update to 1.63. After that I tried a lot of settings, installations, environments.

**Comment by alexdima** [comment] 2022-01-28 10:11
This is not a 1.63 regression, but rather it is a problem we have always had with viewport tokenization & PHP.

When opening a file at a certain scroll position, we do something called viewport tokenization. We take the code in the viewport and (with some heuristics based on indentation) some lines above, outside the viewport and tokenize that. This is imperfect, as tokenization really needs to run through all lines one-by-one to be correct. For example, on line 1000 there could be a block comment start `/*` that is never closed and unless that line is tokenized it will be missed.

In the case of PHP, viewport tokenization almost always results in a flash because we miss the `<?php` line unless all code is indented by one tab. By missing the `<?php` line, we end up tokenizing the viewport using the root state, which in this case is HTML-like, and only later the background tokenization catches up and corrects things. I'm not really sure how to tackle this, it seems that for PHP viewport tokenization should always include `<?php` but it is not clear to me how the text model (which is language agnostic) should be able to pull that off.

Here's proof that it was a problem even with 1.62:

https://user-images.githubusercontent.com/5047891/151527977-1ded367e-aac1-41bb-bc33-00e04d83c969.mp4

**Comment by gsfarm** [comment] 2022-01-28 12:44
> it is a problem we have always had with viewport tokenization & PHP

This is strange. I have been working with PHP in Visual Studio Code for many years, the last year with huge projects, with files of 10000+ lines of code. I didn't notice it before. However, in the latest versions, the problem has almost disappeared. There are issues here where they write about the problem for many languages.

**Comment by alexdima** [comment] 2022-01-28 13:25
@gsfarm Indeed, #138887 was a problem only for 1.63.0 and 1.63.1, but was fixed in 1.63.2. #138887 would make background tokenization a lot slower, which exacerbates the viewport tokenization problem PHP has.

**Comment by gsfarm** [comment] 2022-01-28 13:30
@alexdima ok, thanks. This issue can be closed, real problem for this thread in #138887

**Closed** 2022-01-28 13:33 UTC
Labels: feature-request, tokenization
