### ISSUE TITLE
Auto Update Not Functional

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode#144700] opened 2022-03-08 18:26 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.0 (system setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Have VS Code installed.
2. Ensure you have auto updates enabled:
3. "update.enableWindowsBackgroundUpdates": true
4. "update.mode": "default"
5. Wait for new VS Code release. Instead of it being installed, notice that it only notifies you of updates.
6. 
![image](https://user-images.githubusercontent.com/16603906/157301462-e00d6b2b-f583-44a5-a55c-2a975e5e17c0.png)

Possible cause: Settings were brought over from a different machine, so maybe, by having the setting turned on from there, it's messed up somehow? All I can say is turning setting on an off has no impact either.
When I click install I get a UAC prompt, so maybe the automated update stream is failing because of that hurdle?

**Comment by IllusionMH** [comment] 2022-03-09 08:20
Could you please describe exact concern and expected behavior?

Updates will be installed if you restart or close app on Windows (prompt will be displayed to notify user), it won't just randomly stop in the middle of work process to install update.
![image](https://user-images.githubusercontent.com/1312662/157400914-6b0d9de6-3e4e-47e9-a5df-a79224c24cb4.png)

If there is problem with UAC - you should uninstall System installer and install using User installer instead.

**Comment by mjmatthiesen** [comment] 2022-03-09 18:29
Sorry, I thought it was clear.

On my previous machine it would simply download and install the update as I was using vs code, then notify me that I can restart to update.

On this machine, it only notifies. It never installs the updates. Not in the background while vs code is running, nor when vs code is closed. I always have to trigger the install from the notification.

**Comment by hmt** [comment] 2022-03-10 07:31
same here. I'm notified to restart to update but clicking it will just stop vs code and not restart. Reopening vs code manually will show the restart to update again. No update seems to ever be installed

**Comment by joaomoreno** [comment] 2022-03-10 13:40
The `update.enableWindowsBackgroundUpdates` can affect either system or user install. But on system install you always have no be notified because of the UAC prompt. If you want a straighforward and nice update flow, I suggest using the user setup and leaving the setting as true.

**Closed by joaomoreno** 2022-03-10 13:40 UTC
Labels: needs more info

**Comment by mjmatthiesen** [comment] 2022-03-10 16:05
> The `update.enableWindowsBackgroundUpdates` can affect either system or user install. But on system install you always have no be notified because of the UAC prompt. If you want a straighforward and nice update flow, I suggest using the user setup and leaving the setting as true.

So it doesn't work on system installs. Got it.
