### ISSUE TITLE
VScode freeze when openning a directory

### ISSUE THREAD

**Issue by ryuran** [Microsoft/vscode#54241] opened 2018-07-13 08:43 UTC
- VSCode Version: 1.25.1
- OS Version: MacOS 10.13.5 

VSCode seems to try to check each files of the directory and sub-directories…
It's slow and VSCode freeze most of times.

Steps to Reproduce:
1. Open a huge directory project with `code .` command
2. try to work on a file (impossible to scroll, vscode freeze)

<img width="513" alt="capture d ecran 2018-07-13 a 11 20 24" src="https://user-images.githubusercontent.com/1309340/42683991-2df96cee-868f-11e8-9902-6b6d6ee4944c.png">

![capture d ecran 2018-07-13 a 11 21 05](https://user-images.githubusercontent.com/1309340/42684113-71354014-868f-11e8-9264-e1eb316563a5.png)

Does this issue occur when all extensions are disabled? No

**Comment by bpasero** [comment] 2018-07-16 15:19
Duplicate of https://github.com/Microsoft/vscode/issues/3998

**Closed by bpasero** 2018-07-16 15:19 UTC
Labels: freeze-slow-crash, new release
