### ISSUE TITLE
Audio cues not working

### ISSUE THREAD

**Issue by steverep** [microsoft/vscode#157648] opened 2022-08-09 14:23 UTC
Type: <b>Bug</b>

I am not getting any audio cues to work on the latest insiders build.

VS Code version: Code - Insiders 1.71.0-insider (fe946068ba8ed2c4db200483dbec89210fea1332, 2022-08-09T09:39:20.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.33GB free)|
|Process Argv|--crash-reporter-id 2264703e-acb2-4e8f-b637-a3dc1f5bd270|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Home Assistant Frontend|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (2 x 3400)|
|Memory (System)|3.83GB (0.91GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.8
remotehub|Git|0.40.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.244.0
remote-ssh|ms-|0.84.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
remote-repositories|ms-|0.18.0
vscode-ruby|win|0.28.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.48.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
lit-plugin|run|1.2.4
vscodeintellicode|Vis|1.2.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by steverep** [comment] 2022-08-09 14:24
cc: @isidorn

**Comment by isidorn** [comment] 2022-08-09 20:29
@steverep thanks for filling, this is a regression from the electron update. We are investigating. Closing as a duplicate of https://github.com/microsoft/vscode/issues/157403

**Closed by isidorn** 2022-08-09 20:29 UTC
