### ISSUE TITLE
Cursor dissapear after move between parameters

### ISSUE THREAD

**Issue by brunocasado** [Microsoft/vscode#9029] opened 2016-07-10 14:58 UTC
- VSCode Version:  1.3.0
- OS Version: Ubuntu 16.04

Cursor dissappear on functions parameters

Steps to Reproduce:

1. Move cursor between functions parameters

**Comment by alexandrudima** [comment] 2016-07-11 10:14
@brunocasado Are you on the insiders or the stable stream? Do you use any extensions with VS Code, do you have any old stuck processes? (we have a very bad post-upgrade issue https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408 )

@Tyriar Have you ever seen this while selfhosting on Linux?

**Comment by brunocasado** [comment] 2016-07-11 13:43
@alexandrudima stable stream. 

My extensions:

EditorConfig
Color Picker
ESLint
Stylesheet Formatter
add jsdoc comments
git blame

About process, none stuck process after exit.

**Comment by brunocasado** [comment] 2016-07-11 13:54
@alexandrudima disabled tabs. I think "solved"  the problem.

**Comment by alexandrudima** [comment] 2016-07-11 16:10
fyi @bpasero

**Comment by bpasero** [comment] 2016-07-11 16:13
To reproduce I opened a *.js file on Ubuntu 15 and pressed + hold the arrow left or right key. I could not reproduce. 

Are those the steps @brunocasado ?

**Comment by Tyriar** [comment] 2016-07-11 16:54
I haven't seen this, at least not anytime recently (I recall a similar bug before v1.0).

**Comment by brunocasado** [comment] 2016-07-11 17:14
I only used arrow left or right.....

**Comment by bpasero** [comment] 2016-07-11 17:22
@brunocasado can you make 100% sure that disabling tabs fixes this issue for you?

**Comment by brunocasado** [comment] 2016-07-11 17:26
@bpasero so far so good.

In the end of day i can say with 100% sure.

**Comment by bpasero** [comment] 2016-07-11 17:30
@brunocasado can you:
* enable tabs again
* open dev tools (from help menu)
* click on console
* type: `setInterval(function() { console.log(document.activeElement); }, 1000);`
* hit enter
* use arrow left/right until cursor is gone

=> see what the output is printed once the cursor is gone?

**Comment by brunocasado** [comment] 2016-07-11 17:35
@bpasero 
oh, sorry

tabs on top. new feature.

**Comment by brunocasado** [comment] 2016-07-11 17:40
<textarea data-keybinding-context="54" class="inputarea" wrap="off" autocorrect="off" autocapitalize="off" spellcheck="false" aria-label="process.js. Text file editor." role="textbox" aria-multiline="true" aria-haspopup="false" aria-autocomplete="both" style="top: 0px; left: 0px; font-family: 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'; font-size: 14px; line-height: 19px;"></textarea>

after enabled editor tabs top the problem is back

**Comment by bpasero** [comment] 2016-07-11 17:42
@brunocasado thanks a lot. does this happen also if you just have 1 editor tab open and no other thing?

**Comment by brunocasado** [comment] 2016-07-11 17:42
@bpasero look the image. I have edited :)

**Comment by bpasero** [comment] 2016-07-11 17:51
@brunocasado thanks, did you try to run without extensions to see if that makes any difference (`code --disable-extensions`)

Below is a video how I tried to reproduce it and failed on my Ubuntu 16:

![editors](https://cloud.githubusercontent.com/assets/900690/16740752/c883418e-47a0-11e6-9a33-95920e910bda.gif)

Could you also try what I do there to see if it reproduces?

**Comment by bpasero** [comment] 2016-07-11 18:39
I think I might have found the reason: when tabs are enabled we use a CSS property `mix-blend-mode `that seems to cause the cursor from hiding (which seems like a Chrome bug to me).

Can people hitting this issue when it happens:
* open dev tools on the elements tab
* find the title container on top where the tabs are contained
* remove the `mix-blend-mode` rule by clicking the checkbox
* move the cursor to see if it is now fine

Screenshot: 

![image](https://cloud.githubusercontent.com/assets/900690/16742327/7d8f22fe-47a7-11e6-8868-7771448d5831.png)

@brunocasado fyi

**Comment by brunocasado** [comment] 2016-07-11 18:42
I tried some times again but without bug.... i think this bug is unstable hehe.

I not sure exactly when this occours.

I need finish some work, ASAP i'll try ok?

**Comment by bpasero** [comment] 2016-07-12 13:11
Duplicate of https://github.com/Microsoft/vscode/issues/8828

**Closed by bpasero** 2016-07-12 13:11 UTC
Labels: important

**Comment by qlaire** [comment] 2016-07-12 15:30
removing the mix-blend-mode rule fixes the issue for me.
