### ISSUE TITLE
onDidChangeViewState event not fired

### ISSUE THREAD

**Issue by mikecyj** [Microsoft/vscode#71339] opened 2019-03-28 04:11 UTC
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open one webview.
2. Open another webview right after the first step.
3. Switch to first webview by making it visible.

When doing step#3, the onDidChangeViewState event only fired when one webview's state changed from visible to invisible, but it is not fired for another webview whose state changed from invisible to visible. This only happened the first time switching the webview. Later this event will be working correctly for both active and inactive webviews.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-04-03 23:01
Duplicate of #70859 I believe. Please test in the 1.34 vscode insiders builds that should be coming out later this week

**Closed by mjbvz** 2019-04-03 23:01 UTC
