### ISSUE TITLE
vscode 1.7.1 html tag completion is not working in .jsx file

### ISSUE THREAD

**Issue by manastunga787** [Microsoft/vscode#15278] opened 2016-11-10 05:12 UTC
- VSCode Version 1.7.1:
- OS Version: windows 8.1

i upgraded to vscode 1.7.1 and i noticed the html tag completion in .jsx file is not working.
when ever i type div and hit tab key it is no longer producing ```<div></div> ``` in .jsx file.

but this works fine in .html file

**Comment by wUFr** [comment] 2016-11-10 10:16
related to https://github.com/Microsoft/vscode/issues/15285

+ have same issue when editing file as other than HTML (Smarty template)

**Comment by Shayac** [comment] 2016-11-14 15:56
I've got the same issue. It's not an extension or setting as I don't have any extensions or settings installed.
However, I built the latest version from source and when running that it works fine.

**Comment by Shayac** [comment] 2016-11-15 16:28
It's also working fine in the insider edition

**Comment by egamma** [comment] 2016-12-12 15:55
Closing as a duplicate of #14962, which got fixed in 1.7.2.

**Closed by egamma** 2016-12-12 15:55 UTC
