### ISSUE TITLE
IntelliSense descriptions cutoff in Visual Studio Code for Mac

### ISSUE THREAD

**Issue by cknightdevelopment** [Microsoft/vscode#429] opened 2015-11-22 00:28 UTC
I am using Visual Studio Code `v0.10.1` on Mac. When I was utilizing IntelliSense in a `tsconfig.json` file that have for a `TypeScript` project, I noticed that the descriptions for some of the properties was being cutoff. See screenshot below:

![visual studio code](https://cloud.githubusercontent.com/assets/7575912/11321263/6e6bc068-906c-11e5-9ff7-07f5a27cbd85.png)

I would expect the IntelliSense window to expand to show the full description, or for the description to flow onto a new line. Not sure if this is specific to `tsconfig.json` files or if it is more widespread but I just wanted to flag it as an issue. Thank you.

**Comment by codepic** [comment] 2015-11-22 01:22
Applies to windows also.

![capture](https://cloud.githubusercontent.com/assets/3933589/11321441/2c0370f2-90c8-11e5-807c-caf74afb4ad9.PNG)

**Comment by jel-massih** [comment] 2015-11-22 03:45
Dupe of #369

**Closed** 2015-11-23 09:50 UTC
