### ISSUE TITLE
Issue with formatting HTML when angular components are present

### ISSUE THREAD

**Issue by nkryp** [Microsoft/vscode#17318] opened 2016-12-15 16:24 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular1-code-snippets|alexandersage|0.0.3|
|path-intellisense|christian-kohler|1.2.0|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|debugger-for-edge|msjsdiag|0.4.1|
|vscode-icons|robertohuertasm|4.1.0|

---

Steps to Reproduce:

1. Create HTML file
2. Write code with custom components e.g <customTag>123</customTag>
3. Format code
ALL code is aligned to left

**Comment by vthibeault** [comment] 2016-12-15 17:44
i can confirm i have the same problem using aurelia.

**Comment by jwerts** [comment] 2016-12-16 14:50
same issue here w/ 1.8.0 (angular 2):

![image](https://cloud.githubusercontent.com/assets/674057/21266579/e60df33e-c374-11e6-905f-5aeec1b9b33b.png)

**Comment by AlQuraian** [comment] 2016-12-17 13:17
I too started having this issue when I updated to 1.8.0.

**Comment by aeschli** [comment] 2016-12-31 02:40
duplicate of #17849

**Closed by aeschli** 2016-12-31 02:40 UTC
