### ISSUE TITLE
Cannot read property "isWrapped" of undefined in [Extension Host] when launching VSCode extension for debug

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#59572] opened 2018-09-27 18:32 UTC
- VSCode Version: 1.28.0-insider
- OS Version: Microsoft Windows 10.0.18247

Steps to Reproduce:

1. Clone https://github.com/PowerShell/vscode-powershell/
2. Clone https://github.com/PowerShell/PowerShellEditorServices/ into a sibling directory
3. `cd` into `vscode-powershell`
4. Open `.` in VSCode
5. Execute the **Launch Extension** task

Does this issue occur when all extensions are disabled?: Yes

Here's the task in question:
```json
{
    "name": "Launch Extension",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": [ "--extensionDevelopmentPath=${workspaceRoot}" ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": ["${workspaceRoot}/out/src/**/*.js"],
    "preLaunchTask": "BuildAll"
}
```

You can see our full task configuration [here](https://github.com/PowerShell/vscode-powershell/blob/master/.vscode/tasks.json).

Here's a screen shot of the prompt that appears when the task is run:
![task-error](https://user-images.githubusercontent.com/7009879/46166603-73246900-c248-11e8-944d-8ecaf3badb65.png)

If I click on **Debug Anyway**, I get this:
![vscode-debug](https://user-images.githubusercontent.com/7009879/46166619-7fa8c180-c248-11e8-8a98-48583a05435c.png)

This currently all works in VSCode 1.27.2. I usually use Insiders, so I can report that launching tasks has all worked perfectly up until this point. But I've downgraded to 1.27.2 in light of this issue.

I had a brief look through:

- https://github.com/Microsoft/vscode/issues/37997
- https://github.com/Microsoft/vscode/issues/35340
- https://github.com/Microsoft/vscode/issues/24595

But they don't quite seem to relate -- although perhaps I didn't read closely enough.

Is there something I should change in our task configuration maybe?

Sorry I haven't provided a simpler repro, but happy to work with people to get to the bottom of the problem.

**Comment by dbaeumer** [comment] 2018-09-28 07:31
I tried to reproduce this but failed since Invoke-Build can't be found (I cloned the vscode-powershell repository)

Any additional steps
<img width="965" alt="capture" src="https://user-images.githubusercontent.com/1931590/46194287-44b69480-c301-11e8-8612-5c0424280270.png">

**Comment by isidorn** [comment] 2018-09-28 09:10
I followed your steps and when I start debugging I get the following
```
> Executing task: Invoke-Build BuildAll <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1
```

If I click Debug Anyway - I get no errors you are seeing.
fyi I am on the mac.

1. Can you reproduce this if you disable all other extensions? I see you have C# and others
2. What happens if you simple F1 > execute task > BuildAll

And yes a minimalstic repro steps would help.

You get that error only after 10 second timeout, correct?

**Comment by rjmholt** [comment] 2018-09-28 15:04
`Invoke-Build` you get with `Install-Module InvokeBuild`.

The `execvp(3) failed: No such file or directory` is probably because the task refers to `pwsh` and you only have `pwsh-preview` installed. The error message isn't terribly helpful there. Is there a way to (1) allow someone to easily switch to `pwsh-preview` for the executable there and/or (2) throw a more informative error about what failed where and why? (I'd be happy to do the work and open a PR if you can point me to the relevant code).

Rather than you [go down the path of building the PowerShell extension](https://github.com/PowerShell/vscode-powershell/blob/master/docs/development.md), which involves the above plus cloning the [PowerShell language server](https://github.com/PowerShell/PowerShellEditorServices) in a sibling directory, can you give me some extra hints toward what other information I can record/provide that would help narrow it down toward a minimal repro?

**Comment by isidorn** [comment] 2018-09-28 15:12
@rjmholt regarding questions please read my comment from above

1. Can you reproduce this if you disable all other extensions? I see you have C# and others
2. What happens if you simple F1 > execute task > BuildAll - do you see the task completing?

And yes a minimalstic repro steps would help.
is BuildAll a background watching task? If yes then it has to have the isBackground: true
You get that error only after 10 second timeout, correct?

**Comment by rjmholt** [comment] 2018-09-28 15:56
Just tried the **Launch Extension** task from `code-insiders --disable-extensions`, but the new window it opens still has extensions in it (from the same Chrome error window I see). Is there a way to stop the Extension Host from loading extensions?

**Comment by rjmholt** [comment] 2018-09-28 15:57
Also saw our launch.json version was set to 0.1.0 and no `isBackground` was set.

I tried with the version set to 2.0.0 and `"isBackground": true` in the **Launch Extension** task and same result unfortunately. The JSON schema checker informed me that `Property isBackground is not allowed`.

**Comment by rjmholt** [comment] 2018-09-28 15:59
<kbd>F1</kbd> -> **Run Task** -> `BuildAll` works perfectly :)

**Comment by rjmholt** [comment] 2018-09-28 16:01
The error that Chrome console is showing me is:
```
TypeError: Cannot read property 'isWrapped' of undefined
    at Buffer.getWrappedRangeForLine (c:\Users\roholt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:205:50)
    at BufferStringIterator.next (c:\Users\roholt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:305:34)
    at Linkifier._linkifyRows (c:\Users\roholt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:65:37)
    at c:\Users\roholt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:53:69
```

**Comment by rjmholt** [comment] 2018-09-28 16:05
Just timed the task execution and that popup does show at the 10 second mark.

After reading the [Background Tasks](https://code.visualstudio.com/Docs/editor/tasks#_background-watching-tasks) page, I don't think we're running a background task; we're not doing any file watching, just calling the build.

**Comment by rjmholt** [comment] 2018-09-28 16:08
Just saw that `"isBackground": true` is intended for `tasks.json`. Tried adding it there to the `BuildAll` task, and the same popup occurs.

**Comment by rjmholt** [comment] 2018-09-28 16:29
Getting the "specified task cannot be tracked" popup in VSCode 1.27.2 now, but it seems pretty harmless.

The real problem in insiders seems to be the `isWrapped` property.

**Comment by corbob** [comment] 2018-09-29 23:02
FWIW: The isWrapped started appearing for me on insiders around September 19th. It may have been occurring sooner, but that's when I launched the vscode-powershell extension to test my PRs.

I've done a test with vscode-terraform which I have on my computer, and it comes up with the specified task cannot be tracked message, but doesn't seem to do the isWrapped thing. 

The isWrapped thing is happening in insider only, but it only seems to pop up in the extension host. Otherwise if you toggle the developer tools you'll see the errors. The errors stop if you terminate the integrate console, and they return if you relaunch it.

**Comment by rjmholt** [comment] 2018-09-29 23:53
Perhaps it's our bug on that one then. I'll take a look on Monday

**Comment by corbob** [comment] 2018-09-30 00:59
I took a look at the codebase, and can't find isWrapped anywhere in either vscode-powershell or PSES. I'm wondering if it's both a vscode and a vscode-powershell thing since it doesn't occur in vscode 1.27.2...

**Comment by isidorn** [comment] 2018-10-01 12:50
`isWrapped` error seems to be coming from vscode-xterm
fyi @Tyriar @dbaeumer

**Comment by Tyriar** [comment] 2018-10-01 17:15
https://github.com/Microsoft/vscode/issues/59114

**Comment by isidorn** [comment] 2018-10-02 08:04
@rjmholt `isWrapped` issues is fixedi n latest vscode insiders. Please let me know if now everything works fine.

**Comment by rjmholt** [comment] 2018-10-02 16:10
Thanks @isidorn!

**Comment by isidorn** [comment] 2018-10-03 08:02
I'll take tha as everything works. Closing this.
If something is still not working please create a new one, since this one becase confusing at least for me.

**Closed by isidorn** 2018-10-03 08:02 UTC
Labels: *duplicate, debug, insiders, needs more info
