### ISSUE TITLE
Debugging TypeScript: Step over/into inside async functions

### ISSUE THREAD

**Issue by insprintorob** [Microsoft/vscode#26579] opened 2017-05-13 00:34 UTC
I have a node app written in TypeScript, launched with node.

I've set up Debugging as per the docs, and it works perfectly for non-async functions. I can step over, step into, step out etc.

However, this changes when I go into an async function. "Step over" takes me to the compiled javascript. To work around this I have to set multiple breakpoints to run my code line by line.

- VSCode Version: 1.12.1
- OS Version: Linux

Steps to Reproduce:

1. Set up debugging for a node TypeScript project
2. Create an async function and set a breakpoint.
3. Step over. Also try Stepping into function calls.

test code (test.ts):
```
class Test { 
     test(): any {
         //debugging, step over/step into will work fine in this method
         let a = 'b';
         let b = 'c';
         this.testa();
     }
     async testa(): any {
         let a = 'b';
         let b = 'c';
         await this.testb(); //Try step into/step over here
         let c = 'd';

        return new Promise<void>(function(resolve) {
            
        });
     }
     async testb(): Promise<any> {
           let a = 'b';
           let b = 'c'; 

        return new Promise<void>(function(resolve) {
            
        });
     }
}

let test = new Test();
test.test();
```

**Comment by polkovnikov-ph** [comment] 2017-06-02 12:59
@weinand This is not a question, this is a third duplicate of the same bug #19973, #11645.

**Comment by weinand** [comment] 2017-06-02 13:31
dup of https://github.com/Microsoft/vscode/issues/11645

**Closed by weinand** 2017-06-02 13:31 UTC
Labels: debug, question
