### ISSUE TITLE
Source control menu menu auto-click

### ISSUE THREAD

**Issue by XanManZA** [Microsoft/vscode#54923] opened 2018-07-24 08:24 UTC
Issue Type: <b>Bug</b>

On Windows and VS Code 
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

1) Open source control panel
2) Click on any provider
3) Click on menu ("...") on right side of collapsible
The click immediately propogates and chooses "Pull". Meaning I cannot choose any other options on the menu.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (4.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
auto-close-tag|for|0.5.6
php-namespace-resolver|Meh|1.1.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
python|ms-|2018.7.0
vsliveshare|ms-|0.3.423
vetur|oct|0.12.5
laravel-blade|one|1.18.0
vscode-docker|Pet|0.0.27
vscode-wakatime|Wak|1.2.3

</details>

**Comment by XanManZA** [comment] 2018-07-25 13:07
I'm pretty sure I run the native one.
That would appear as an extension right?

**Comment by kieferrm** [comment] 2018-07-26 01:36
@XanManZA you control the window titlebar through user settings. But since you don't know, it's likely you didn't change it 😄.

**Comment by sbatten** [comment] 2018-07-26 17:11
duplicate of #52803

**Closed by sbatten** 2018-07-26 17:11 UTC
Labels: workbench-menu

**Comment by formulahendry** [comment] 2018-07-27 02:42
@kieferrm @sbatten I see several issues about this. Do we have an ETA of this issue? As I mentioned in https://github.com/Microsoft/vscode/issues/52803#issuecomment-406139023 , we really want this could be fixed.  Thanks a lot!
