### ISSUE TITLE
Screen cheese in suggest window

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3464] opened 2016-02-25 17:33 UTC
- open folding.ts, line 343
- after the dot of `model.getLineMaxColumn` do code assist
- scroll down the list of proposals 
![image](https://cloud.githubusercontent.com/assets/6461412/13328323/49decb3c-dbee-11e5-83d3-49f805332de5.png)

**Comment by joaomoreno** [comment] 2016-02-25 18:37
@aeschli I can't reproduce, make sure you have a recent version.

**Comment by aeschli** [comment] 2016-02-25 19:18
I'm on Linux.
Version 0.10.10-alpha
Commit cecdf875d510948053fb815e9cfc48bb1e31eec7
Date 2016-02-25T08:07:21.481Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

That's pretty new, right?

**Comment by joaomoreno** [comment] 2016-02-25 22:03
Is there nothing else you can give me here? From the screenshot, scrolling down wasn't the only thing you did, since `findPreviousMatch` is focused. Show me tomorrow morning?

**Comment by aeschli** [comment] 2016-02-25 22:11
I just tried to reproduce again, but wasn't able, all looks fine now. Same version, same file content. Nasty!

**Comment by joaomoreno** [comment] 2016-02-26 08:02
Let's keep an eye out then.

**Comment by aeschli** [comment] 2016-03-01 15:15
There seems to be an extra DOM done in the list container. The list model seems sane.

**Comment by joaomoreno** [comment] 2016-03-17 07:53
Moving to April since it reproduces very rarely.

**Comment by joaomoreno** [comment] 2016-05-24 09:15
More info in #6274

**Closed** 2016-05-25 16:18 UTC
Labels: bug

**Comment by joaomoreno** [comment] 2016-05-25 16:20
Thanks for the help in this @aeschli. I was able to simplify the render and splice methods much more; from 319 loc to 272! Feels much better to reason about too. Also ended up dropping the diff algorithm and just unrender and render everything, like you suggested.

**Comment by aeschli** [comment] 2016-05-27 09:10
@joaomoreno Can you list the steps that reproduced the issue for you?

**Comment by joaomoreno** [comment] 2016-05-27 09:37
Sorry!

- Open User Settings, get the cursor into a position for a new setting
- Trigger suggestions
- Press <kbd>Up</kbd> to select the last suggestion
- Press <kbd>PageUp</kbd> several times

This would break it.
