### ISSUE TITLE
Problems to delete file or folder in Visual Studio Code

### ISSUE THREAD

**Issue by HiddenBehindTheKeyBoard** [microsoft/vscode#98547] opened 2020-05-26 02:22 UTC
if you delete file or folder with visual studio code, seconds later the file or folder is restored.

**Comment by Wieschie** [comment] 2020-05-29 16:13
I can provide more info here:

This occurs when another process has a lock on some file in the folder.  VS Code does not properly detect / display the deletion error.

Simple reproduction:

1. Create a new folder
2. Open a new terminal in that folder (can be the VS Code builtin or an external session)
3. Delete that folder through the VS Code Explorer view

Expected behavior: Code displays an error similar to Windows Explorer "The folder cannot be deleted because it is open in another program"

Actual behavior: Code removes the folder from the listing on the right and issues no errors.  Refreshing immediately re-displays the folder.

**Comment by bpasero** [comment] 2020-05-30 06:38
@Wieschie this is Windows right, not any other OS?

**Comment by Wieschie** [comment] 2020-05-30 11:54
@bpasero that's correct. I'm on W10 1909.

**Comment by bpasero** [comment] 2020-05-30 12:14
@Wieschie as far as I know, Windows will not let you delete any file or folder that is in use by another program, I am not sure how VSCode can solve that?

**Comment by Wieschie** [comment] 2020-05-30 12:28
In my opinion, code should display an error upon trying to delete a locked folder, instead of silently failing and pretending it has done so.

At the very least, it should not remove the folder from the explorer list if the delete failed.

**Comment by bpasero** [comment] 2020-05-30 12:33
Right, if that is the issue, then moving to Isi and file explorer.

**Comment by isidorn** [comment] 2020-06-02 16:42
Will not fix this week, moving out to June to investigate into a fix then. Thanks

**Comment by HiddenBehindTheKeyBoard** [comment] 2020-06-02 18:55
**Don't worry until then, my team and I use sublime-text or Windows notepad, thanks for willingly collaborating.**

**Closed** 2020-07-31 15:34 UTC
Labels: bug, file-explorer, wont-fix
