### ISSUE TITLE
Can't scroll past column 10000

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#137138] opened 2021-11-13 20:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Win10 X64 2004 build 19041.1348

Steps to Reproduce:

1. Load a stupidly big file that doesn't have newlines for some reason.
2. Scrollbar won't go past column 10000 even though the cursor will.

Placing the cursor as far as the scrollbar will go:

> ![image](https://user-images.githubusercontent.com/177243/141658213-9c9a06ee-9f74-4374-977a-6396bcade987.png)

Placing the cursor at the end of that (stupidly long) line:

> ![image](https://user-images.githubusercontent.com/177243/141658223-d97d0821-8874-4f20-b2db-94a4f8fb0aa3.png)

**Comment by IllusionMH** [comment] 2021-11-13 22:02
/duplicate of #7772

This is expected behavior and done for performance reasons.
You can use formatter that would format it to more readable multiline presentation.
Or
See https://github.com/microsoft/vscode/issues/7772#issuecomment-347174463 for "hidden" way to extend limit (beware of performance implication for very long lines)

**Closed** 2021-11-13 22:02 UTC
Labels: *duplicate, new release

**Comment by Pomax** [comment] 2021-11-14 00:19
how unfortunate. I'd have hoped vs code would not interfer with me seeing my entire file, even if it'd impact performance. Just pop up a dialog going "This file has very long lines, scroll be capped at 10,000 unless you're very sure you don't want that" with two buttons, like a million other things VSCode already ask you to confirm on a per-case basis.

**Comment by IllusionMH** [comment] 2021-11-14 00:47
Just use setting mentioned in the comment and enjoy your large files (although rarely useful as it's hard to read single line nested JSONs).

Also you can always submit PR that shows confirmation dialog, as I (not a team member) suppose that it's not frequent request and with existing workaround isn't high in team's priority list.
