### ISSUE TITLE
[folding] Option for single line collapse like in visual studio

### ISSUE THREAD

**Issue by RasHas** [Microsoft/vscode#25768] opened 2017-05-02 09:11 UTC
![demonstration](https://cloud.githubusercontent.com/assets/5573972/25610860/8894f75a-2f2d-11e7-8be8-f3ce5721f41a.PNG)
Left VSCode right Visual Studios editor.

Could we get an option for collapsing code to single line instead of 2 lines? I understand the benefits of 2 line collapse (ex. correctly shown line numbers), but in many cases 1 line collapse is far more useful.

**Comment by aeschli** [comment] 2017-05-03 15:04
basically a duplicate of #24515

**Closed by aeschli** 2017-05-03 15:04 UTC
Labels: editor-folding, feature-request
