### ISSUE TITLE
Support for live preview and/or "open in browser" shortcut and Format support for PHP

### ISSUE THREAD

**Issue by D4YN3X** [Microsoft/vscode#22370] opened 2017-03-10 10:00 UTC
There is no "easy" way to open files your are working on right now, you know just to make sure everything is okay. Whether it is PHP, HTML or something else there's no all around extension that makes this work flawlessly. Additional you could make a live preview for these file types as well (maybe not for PHP idk). Windows already have a nice way to add the windows to the sides for multitasking, with live preview it would work great!

Also PHP format in HTML files and HTML format in PHP files would be greatly appreciated too!

**Comment by ramya-rao-a** [comment] 2017-03-10 22:21
cc @waderyan for thoughts on live preview

cc @aeschli for thoughts on php formatting in html and vice versa

**Comment by D4YN3X** [comment] 2017-03-11 10:28
I see, but there should be more "native" support for these things as some of the extension aren't well made or/and doesn't give give correct or enough infomation in how to install or even use them. 
+ when you try to find a

**Comment by D4YN3X** [comment] 2017-03-11 10:37
(my phone screwed up) as I was saying
+ when you try to find an extension you almost everytime get more than you actually need. Like shen you try to get a good formatting extension, you can choose the combi extension or just get the exact formatting extension you need. But the combi may have some good formatting for some code you write, but terrible formatting in aome other you eventually can't find anywhere else. While the single formatting got good formatting, but nothing more, now you may have two extensions for the same thing...

**Comment by aeschli** [comment] 2017-03-11 15:59
duplicate of #12080

**Closed by aeschli** 2017-03-11 15:59 UTC
Labels: html, php

**Comment by ramya-rao-a** [comment] 2017-03-11 23:56
@aeschli #12080 covers live preview

Thoughts on the last part of the OP's query?

> Also PHP format in HTML files and HTML format in PHP files would be greatly appreciated too!
