### ISSUE TITLE
Menu: keyboard selected item should go away when mouse moves

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52933] opened 2018-06-26 10:49 UTC
Refs: #52854

Steps:
* expand a menu
* arrow down 
* move the mouse

=> native menus at this point clear the keyboard selected entry

This also avoids the issue that hovering with the mouse over a keyboard selected entry takes the selection away.

**Comment by octref** [comment] 2018-06-26 23:08
I think maybe separate the keyboard highlight indicator from the mouse highlight? For example in Edge:

![image](https://user-images.githubusercontent.com/4033249/41944069-f4fb8404-795a-11e8-8500-ef6dae0b4820.png)

The expected behavior for pressing an enter, even if the mouse moves and hovers on other item, should be executing the action selected by the keyboard focus indicator.

**Comment by sbatten** [comment] 2018-07-03 21:05
I think what native does is actually move keyboard focus to the mouse location. There is no difference between the two. Removing the keyboard focus would violate #52385

**Comment by sbatten** [comment] 2018-07-03 21:06
Also @octref, This is pretty much what happens today already. It looks weird when using a mouse, but not in Edge, because they violate #52385

**Comment by sbatten** [comment] 2018-07-17 17:39
fixed via #54428

**Closed by sbatten** 2018-07-17 17:39 UTC
Labels: bug, workbench-menu
