### ISSUE TITLE
Can editors be closed by an extension?

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#21617] opened 2017-03-01 10:44 UTC
I would really like a feature to close any editors which are not modified in git. I would be happy to implement this as an extension, but I can't find anything in the API or in any examples that show how to close an open editor. Is this even possible?

**Comment by jrieken** [comment] 2017-03-01 15:07
well, we do have a *deprecated* `TextEditor#hide` method. It is deprecated because the editor will likely be disposed after hiding it and subsequent interactions will fail (like show et al). The current recommended workaround, which stinks, is to execute the `'workbench.action.closeActiveEditor'` command. 

Also, what you what seems to be a model of the 'tabs'. For the API an editor always one which is active and visible in the UI. Editors that are not showing and reveal only when selecting their tab don't really exist because it's always the same editor to which we set different documents. In the API tho, an editor is the combination of an text editor widget *and* a document.  

I am closing this as a duplicate of #15178 which is about exposing our tab-model.

**Closed by jrieken** 2017-03-01 15:07 UTC
Labels: api
