### ISSUE TITLE
New CLI option to call an extension command with args in a terminal

### ISSUE THREAD

**Issue by L13** [microsoft/vscode#174082] opened 2023-02-10 17:33 UTC
A developer suggested the idea to call my extension from the command line with arguments, but this is right now only possible with a bad workaround.

The idea is to open VS Code with the CLI and start an extension immediatley with arguments. For example:

`code --command "l13Diff.action.panel.openAndCompare" --args "/path/to/folder-a" "/path/to/folder-b"`

For security reasons I suggest to add the commands to the activation events list with:

`onCLI:l13Diff.action.panel.openAndCompare`

This should prevent other commands to be called from the command line.

What do you think?

**Comment by aeschli** [comment] 2023-02-22 13:15
Duplicate of https://github.com/microsoft/vscode/issues/105487

**Closed by aeschli** 2023-02-22 13:15 UTC
