### ISSUE TITLE
 Cannot read property 'value' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#49542] opened 2018-05-09 14:10 UTC
Issue Id: <b>88806823-f681-238e-d25b-c9b5dfcab727</b><br /><br />*Versions* <br />- 1.23.0<br />-  a656d397e424173c86f32703e0c0293bd8084da0<br />-  b8475d1dc68bfee70c3fbe3e7fc39f6e0003803b<br />-  e6076fad9a41821f8647b60375ad21535f424498<br />-  5a397a1f9e2123088f13e1ff9134723f181bf373<br />*Stack* <br />TypeError: Cannot read property 'value' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#236:16 (onComplete)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L236:16 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#916:0 (enter)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L916:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1046:0 (_chainedError)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1046:0 (_chainedError))<br />[/vs/base/common/winjs.base.js#751:0 (onError)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L751:0 (onError))<br />[/vs/base/common/winjs.base.js#1224:0 (_notify)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1224:0 (_notify))<br />[/vs/base/common/winjs.base.js#916:0 (enter)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L916:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1056:0 (reject)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/common/winjs.base.js#L1056:0 (reject))<br />[/vs/workbench/services/extensions/electron-browser/extensionHost.ts#331:5](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L331:5)<br />

**Comment by alexandrudima** [comment] 2018-05-15 10:37
Duplicate of #43477

**Closed by alexandrudima** 2018-05-15 10:37 UTC
