### ISSUE TITLE
CLI on macOS with `-w` does not exit when running multiple times

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#134030] opened 2021-09-28 16:14 UTC
Testing #133771

Steps to repro:
* Open terminal in directory x
* run `code-insiders -w`
* Open another terminal in the same directory x
* run `code-insiders -w`
* Quit VS Code
* Only the first call to `code-insiders -w` runs to completion (i.e. the second terminal is still waiting for `code-insiders -w` to complete)

**Comment by deepak1556** [comment] 2021-09-28 20:54
@rzhao271 I can confirm the terminal related to the second instance does not run to completion in either cases you have listed on latest Big Sur. 
[Screen Recording 2021-09-29 at 5.52.24.zip](https://github.com/microsoft/vscode/files/7247224/Screen.Recording.2021-09-29.at.5.52.24.zip)

**Comment by DonJayamanne** [comment] 2021-09-28 21:15
I'm on Big Sur (11.6)

**Comment by rzhao271** [comment] 2021-09-29 01:11
I confirmed the bug. It seems to occur when one doesn't specify the location. Repeating the original steps with `code-insiders -w .` instead works.
@bpasero should there be a difference between starting code-insiders with a directory provided and without?

**Comment by bpasero** [comment] 2021-09-29 04:48
That is really bizarre, I would not expect that to make any difference but moving to September to get to the bottom of this, please investigate.

**Comment by bpasero** [comment] 2021-09-29 07:58
Actually something in my area 👍

**Comment by lramos15** [comment] 2021-09-30 15:46
Still seeing this.

**Comment by rzhao271** [comment] 2021-09-30 18:19
Thanks, Logan.
I can also still see the issue. The difference between `code-insiders -w .` and `code-insiders -w` seems to be at https://github.com/microsoft/vscode/blob/8eac5e624dc025a80672ede544e3d49a46c260c3/src/vs/platform/windows/electron-main/windowsMainService.ts#L689

Previously, we would exit when the child process (code-insiders) closed. On the new code path, the child process (opens) exits immediately, so we must wait for the wait marker file to be deleted instead. Also, when no path is passed in, the behaviour isn't exactly the same as passing in the current directory. 

Therefore, I wonder whether it has to do with `handleWaitMarkerFile` https://github.com/microsoft/vscode/blob/8eac5e624dc025a80672ede544e3d49a46c260c3/src/vs/platform/windows/electron-main/windowsMainService.ts#L394

**Comment by bpasero** [comment] 2021-10-01 06:37
I actually forgot part of my fix. Somehow I could still verify locally though running out of sources.

**Closed** 2021-10-01 06:37 UTC
Labels: bug, verification-found, macos, workbench-cli, confirmed
