### ISSUE TITLE
Apply font to the whole app

### ISSUE THREAD

**Issue by piscopancer** [microsoft/vscode#207194] opened 2024-03-08 19:51 UTC
There's an extension called `fonted` and it does the work. Can we have this functionality native?

**Comment by rzhao271** [comment] 2024-03-08 20:57
Duplicate of https://github.com/microsoft/vscode/issues/519
In particular, see https://github.com/microsoft/vscode/issues/519#issuecomment-414583479

**Closed by rzhao271** 2024-03-08 20:57 UTC
