### ISSUE TITLE
Program hangs after update

### ISSUE THREAD

**Issue by markkilonzi** [Microsoft/vscode#372] opened 2015-11-20 19:11 UTC

**Comment by bpasero** [comment] 2015-11-20 20:56
@markkilonzi more infos please. are you maybe editing PHP? So it could be #160

**Comment by markkilonzi** [comment] 2015-11-20 21:07
yeah its php- i've checked out #160 ... found out its the one.... thanks man.

**Comment by bpasero** [comment] 2015-11-20 21:14
Closing as dupe of #160

**Closed by bpasero** 2015-11-20 21:14 UTC
