### ISSUE TITLE
Paper cut: NotebookDocumentMetadata object usage

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125150] opened 2021-06-01 18:37 UTC
Testing #124992

So I had the following code in my deserialize:

```ts
const meta = new vscode.NotebookCellMetadata();
meta.with({
    foo: "asdf"
});

return new vscode.NotebookData(cells, meta);
```

I was surprised when I was going to serialize that:

```ts
data.metadata.foo
```
was undefined. It wasn't until I realized that `.with` actually returned a _new metadata object_... so my code should actually be:

```ts
const meta = new vscode.NotebookCellMetadata();
return new vscode.NotebookData(cells, meta.with({
    foo: "asdf"
}));
```

It's a little silly that I need this instance of `NotebookCellMetadata` that's useless to me except to make the actual cell metadata I care about.

2 suggestions:

1. A static `with` method so I only need to create a single `NotebookCellMetadata` object:
```ts
vscode.NotebookCellMetadata.with({ foo: 'bar' })
```

2. Go back to when it was `{ [key: string]: any }` which just feels more natural for TS/JS

**Comment by jrieken** [comment] 2021-06-02 06:48
> Go back to when it was { [key: string]: any } which just feels more natural for TS/JS

We actually did that yesterday. No more specific types for metadata but just object literal. However, the `with`-function is a thing, see Uri, Position, Range, and it should be though of as a modifier-function, read "object foo _with_ these changes"

**Comment by TylerLeonhardt** [comment] 2021-06-02 12:43
But examples you gave all have constructors/static methods that let you specify everything you need.

`Uri` - I can use the parse static function
`Position` & `Range` - give you the ability to specify everything you would want to set in their ctor

This is not the case for `Notebook*Metadata` because I have no way to specify any object in the ctor and there's no static ctor to do so.

I don't have a problem with `with`, I just wish there was a way for me to create a single instance of the `Notebook*Metadata` with everything I need in it already.

**Comment by jrieken** [comment] 2021-06-02 12:46
> This is not the case for Notebook*Metadata because I have no way to specify any object in the ctor and there's no static function to do so.

Yeah, that's why we removed it in the end. It is an opened ended bag of stuff that we don't know.

Closing since the root cause is gone

**Closed by jrieken** 2021-06-02 12:46 UTC
