### ISSUE TITLE
Loading Intellisense Infinitely

### ISSUE THREAD

**Issue by Nsj94** [microsoft/vscode#206316] opened 2024-02-27 04:51 UTC
Type: <b>Bug</b>

TYpescript intellisense is loading infinitely and code helper plugin in mac isgoing cpu 125% or above

VS Code version: Code - Insiders 1.87.0-insider (Universal) (e73419bef379f7956f024557cbf40bd3755a0645, 2024-02-26T14:33:08.796Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 7, 5|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
vscaat:30438846
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:30968133
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfcontrol:30963551
8082a590:30961435
edj9j583:30969294
fegfb526:30952798
e3gdj431:30946825
ccp1r3:30958150
pythonait:30973460

```

</details>

**Comment by trry-github** [comment] 2024-02-27 06:03
I also felt stuck in 1.86.2

**Comment by Nsj94** [comment] 2024-02-27 17:14
@mjbvz  any solution?

**Comment by fwsGonzo** [comment] 2024-03-02 16:35
I'm also experiencing this

**Comment by sKopheK** [comment] 2024-03-03 17:04
a wild "Loading IntelliSense status" label appeared all of sudden in my poor project and I'm stuck with that ever since. tried restart, clean install, but nothing helped. in other projects it's fine
![imagen](https://github.com/microsoft/vscode/assets/5802917/d89facd9-9262-4955-834b-82ae9397259c)

**Comment by mjbvz** [comment] 2024-03-04 21:32
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by sKopheK** [comment] 2024-03-04 23:04
funny enough, i can't reproduce the issue anymore even with the same ts version and (i believe) same files
i've checked `tsserver.log` before (with default "terse" settings tho) but could not find anything particular, it mostly just looked stuck

**Comment by Nsj94** [comment] 2024-03-05 03:32
Mee too can't reproduce this error , it comes and goes away after few days

**Comment by mjbvz** [comment] 2024-03-13 22:17
If you can reproduce it, please try collecting the logs. Closing for now since we can't investigate any further without these

**Closed by mjbvz** 2024-03-13 22:17 UTC
Labels: info-needed
