### ISSUE TITLE
single and double aren't auto-closing inside html tags

### ISSUE THREAD

**Issue by ashklempton** [Microsoft/vscode#44118] opened 2018-02-21 12:52 UTC
### Issue Type
Bug

### Description

Well i Don't know why but due to some reason , single and double quotes aren't auto-closing inside of html tags.

Quotes do auto-close when called outside of an html tag.

![peek 2018-02-21 18-19](https://user-images.githubusercontent.com/36561828/36480905-0b046984-1734-11e8-866d-e10b263a3054.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.4.0-92-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 x 3300)|
|Load (avg)|0, 0, 0|
|Memory (System)|3.79GB (0.20GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.6.1
vscode-github|Kni|0.26.0
materialize-snippets|len|1.2.2
emmet-uxcore|rba|0.0.1
bootstrap4-vscode|the|4.0.0

(1 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by aeschli** [comment] 2018-02-23 14:58
duplicate of https://github.com/Microsoft/vscode/issues/42956

**Closed by aeschli** 2018-02-23 14:58 UTC
Labels: html
