### ISSUE TITLE
When replacing folders, offer an option to merge the files

### ISSUE THREAD

**Issue by flleeppyy** [microsoft/vscode#232714] opened 2024-10-31 09:16 UTC
Duplicate of discarded issue #1391

I lost a crap ton of work because I moved a folder and clicked replace. Please make this a thing.

**Comment by gjsjohnmurray** [comment] 2024-10-31 10:26
@lramos15  this is a duplicate of https://github.com/microsoft/vscode/issues/165706, for which you have a long-open PR.

**Comment by lramos15** [comment] 2024-10-31 15:28
Yes it is a duplicate. I just need to freshen up some of the various confirmations in that PR and it should be good to go. If someone else wants to take a crack at updating my PR that's also cool!

**Closed by lramos15** 2024-10-31 15:28 UTC
