### ISSUE TITLE
no exit confirmation when VS window close button pressed

### ISSUE THREAD

**Issue by gsmpager** [microsoft/vscode#119402] opened 2021-03-21 06:23 UTC
Issue Type: <b>Feature Request</b>

Hello,
It would be nice to ask the user if she or he really wants to exit the VS, when the close button is pressed on the application frame. It could be pressed accidentally also.
Thank You , Andras

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 6.1.7601

**Comment by gjsjohnmurray** [comment] 2021-03-21 10:29
/duplicate of #14710

In particular see https://github.com/microsoft/vscode/issues/14710#issuecomment-316562950 for a suggestion.

**Closed** 2021-03-21 10:29 UTC
Labels: *duplicate
