### ISSUE TITLE
2-finger scroll on touchpad stops working randomly

### ISSUE THREAD

**Issue by nicholasengleman** [Microsoft/vscode#36164] opened 2017-10-12 19:24 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

1. Can't pinpoint what causes 2-finger scrolling to stop working in VS Code. 2-finger scrolling continues to work in other applications. Even a reboot of machine does not fix the scrolling. Problem continues with extensions disabled. 

I am using a windows precision touchpad. 

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-13 07:26
Duplicate of #13612

**Closed by egamma** 2017-10-13 07:26 UTC
Labels: extensions, new release
