### ISSUE TITLE
Cannot open menus on second window

### ISSUE THREAD

**Issue by danwdart** [microsoft/vscode#166574] opened 2022-11-17 11:24 UTC
Type: <b>Bug</b>

1. Open new window
2. Click on a top menu e.g. File
3. No popdown happens.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 6.0.7
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3139)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 0|
|Memory (System)|31.11GB (13.92GB free)|
|Process Argv|--crash-reporter-id f285cc09-1b3e-49ed-8982-24919fc276a1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/nix/store/p5gqhfi76ychm9gybvx1ykfz11h7h2fd-desktops/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
nixpkgs-fmt|B4d|0.0.1
vscode-direnv|Rub|0.0.2
nix-env-selector|arr|1.0.7
Nix|bbe|1.0.1
nixfmt-vscode|bre|0.0.1
vscode-ghc-simple|dra|0.2.3
x86-64-assembly-pro|Ehl|0.0.1
x8664assembly|fre|0.1.0
haskell|has|2.2.0
haskell-linter|hoo|0.0.6
nix-ide|jno|0.1.12
svg|joc|1.4.19
haskell-pointfree|Jos|0.0.1
language-haskell|jus|3.6.0
nasm|Luc|1.2.1
nasmcustom|Luc|1.1.0
hlint|lun|0.5.1
nix|mar|0.0.1
remote-ssh|ms-|0.85.2022071315
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.13.2
haskell-ghcid|ndm|0.3.1
phoityne-vscode|pho|0.0.27
haskell-formatter-vscode-extension|ser|0.0.2
stylish-haskell|vig|0.0.10
x86|whi|0.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by rzhao271** [comment] 2022-12-05 23:25
Duplicate of #159852

**Closed by rzhao271** 2022-12-05 23:25 UTC
Labels: menus
