### ISSUE TITLE
Editor split function is abnormal

### ISSUE THREAD

**Issue by LiuyangRY** [microsoft/vscode#76760] opened 2019-07-06 05:44 UTC
Issue Type: <b>Bug</b>

When you execute an Sql query in VS Code, the editor is automatically split into two parts, with a preview provided by the Markdown extension on the right.If you use the mouse to drag and drop the editor in this case, you will not be able to adjust the layout smoothly.In other cases, the layout can be adjusted normally.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.6
unity-code-snippets|kle|1.3.0
vscode-language-pack-zh-hans|MS-|1.36.2
mssql|ms-|1.6.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
csharp|ms-|1.20.0
Go|ms-|0.11.2
vetur|oct|0.21.1
markdown-preview-enhanced|shd|0.4.2
vscode-leetcode|she|0.15.1

</details>

**Comment by dbaeumer** [comment] 2019-07-06 11:23
Not sure where to start. @mjbvz starting with you since the left side is markdown and it otrherwise works

**Comment by mjbvz** [comment] 2019-07-08 18:55
I believe this is a duplicate of #76866

**Closed by mjbvz** 2019-07-08 18:55 UTC
