### ISSUE TITLE
IDE closes all my network files when i lose connection to the network during a power blackout.

### ISSUE THREAD

**Issue by nicolasvahidzein** [microsoft/vscode#136673] opened 2021-11-08 14:50 UTC
When i lose power VScode removes all my files located on the network from the folder view and closes all my files i am working on, this is a huge problem and needs to be corrected please.

**Comment by sbatten** [comment] 2021-11-08 18:16
I assume this because the filewatcher sees those events as removed... @bpasero

**Comment by nicolasvahidzein** [comment] 2021-11-08 21:34
Version: 1.62.0 (user setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.10586

**Comment by nicolasvahidzein** [comment] 2021-11-08 21:35
@sbatten is it possible to change that behavior?

**Comment by bpasero** [comment] 2021-11-09 06:11
If this is file events, running with `-verbose` would reveal this.

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by nicolasvahidzein** [comment] 2021-11-09 17:33
As you requested, here is the file. It seems to be the watcher indeed.

![001](https://user-images.githubusercontent.com/29876108/140975022-d8ce9d02-f38e-4157-8841-8fd859b6013c.JPG)

**Comment by bpasero** [comment] 2021-11-10 05:42
Hm, no, doesn't look like it. The watcher fails to watch, but that will not result in editors closing. Can you add a breakpoint into `FileEditorInput#dispose` and share the stack when the editors close to see what is triggering the close?

**Comment by nicolasvahidzein** [comment] 2021-11-10 06:26
Id love to but i don't know where to go to do that. Do you have a tutorial i can watch? Thanks.

**Comment by bpasero** [comment] 2021-11-10 06:53
* open developer tools
* open "Sources"
* Ctrl+O and `fileEditorInput`
* scroll to `dispose`
* add a breakpoint into the first line
* reproduce the condition that closes editors
* share a screenshot of the call stack

**Comment by nicolasvahidzein** [comment] 2021-11-10 08:00
Will do. Thank you so much.

**Comment by bpasero** [comment] 2021-11-10 08:14
Thanks

**Comment by nicolasvahidzein** [comment] 2021-11-10 08:31
I can't get it to close the files like before. It's strange. Now it just crosses out the file in red and when the network drive is available it returns back to normal. I can't explain it.

**Comment by bpasero** [comment] 2021-11-10 08:39
This is driven by a setting: `workbench.editor.closeOnFileDelete`

**Comment by nicolasvahidzein** [comment] 2021-11-11 08:27
> This is driven by a setting: `workbench.editor.closeOnFileDelete`

It happened again. This is so annoying. That setting is off btw. I will try it again and see what changes in the disconnection that it closes those files.

**Comment by nicolasvahidzein** [comment] 2021-11-11 08:56
I have log files to share, how do i get those to you privately? Thanks. I had to shut my whole apartment down to test it and it was worth it. Cutting the network adapter made it act differently. Your breakpoint worked. 90% of the files were closed and ihave the command prompt log, the vscode log and the captures as well from the console (redundant since we have the vscode log).

**Comment by bpasero** [comment] 2021-11-11 12:13
Great, you can share it via my mail to me. You can find that here: https://github.com/bpasero

**Comment by nicolasvahidzein** [comment] 2021-11-11 13:01
Done. Thanks @bpasero.

**Comment by bpasero** [comment] 2021-11-11 14:03
@nicolasvahidzein yeah so it really seems like there is an error occurring when watching and we emit a file change event as if the root was deleted to notify upstream components:

https://github.com/microsoft/vscode/blob/80c789277f1a0f3e88d292d09030eaba5cbe4b67/src/vs/platform/files/node/watcher/parcel/parcelWatcherService.ts#L479-L482

When I simulate such an event I can reproduce that opened editors begin to close because we assume the files are deleted from disk. However, the default setting of `workbench.editor.closeOnFileDelete` prevents this from happening for me. 

Are you sure you have not configured `workbench.editor.closeOnFileDelete` anywhere? Maybe as workspace setting?

**Comment by nicolasvahidzein** [comment] 2021-11-11 15:15
Nope, not set anywhere. You can have access to my system if you wish.

**Comment by nicolasvahidzein** [comment] 2021-11-11 15:16
Does it matter if those files are opened and not edited and do not contain any changes? Most of my files are files I might use but for the most part are unchanged. Does that matter?

**Comment by bpasero** [comment] 2021-11-11 15:46
Yeah somewhat. Dirty files would never close automatically since they obviously have data that was not yet written to disk. 

I am actually wondering if my change to send out a `deleted` event for the root workspace folder is clever. We have not been sending out such an event before and now it may cause other issues I am not aware of. So one idea would be to go back to the previous behaviour and not emit this `deleted` event for the root path.

Can you actually experiment with this and disable the file watcher to make sure it is the one triggering this close of editors? To do so you would have to configure `files.watcherExclude: "**"`.

**Comment by nicolasvahidzein** [comment] 2021-11-11 16:34
Ok i will do this tomorrow as i have to cut power to the apartment again. Thank you Ben.

**Comment by nicolasvahidzein** [comment] 2021-11-11 18:24
Where do i configure this btw? In my own json preferences?

**Comment by sbatten** [comment] 2021-11-11 22:57
@nicolasvahidzein yes that's right

**Comment by bpasero** [comment] 2021-11-12 07:31
Yeah normally in settings.

**Comment by nicolasvahidzein** [comment] 2021-11-12 07:44
Ok its done. Ill simulate a disconnection today.

**Comment by nicolasvahidzein** [comment] 2021-11-12 13:38
nope still not working. Half the files still get removed, Pain in the neck.

       "files.watcherExclude": {
		"**": true
	},

this is in my JSON prefs set from the main preferences toggle.

There doesn't even seem to be any logic as to how the files are closed. All were saved, none were unsaved, and half of them were closed.

**Comment by bpasero** [comment] 2021-11-12 16:26
Yeah I wonder why half of them close and not all. Nevertheless I have pushed a [change](https://github.com/microsoft/vscode/commit/81cf536582dcfd31371b48d610613917a875a804) to not emit a `deleted` event for the root of the workspace anymore to align more with how we used to behave. If you want to try this out, our latest insiders build has that change (https://code.visualstudio.com/insiders/).

When you added that breakpoint and it was hit, can you share the screenshot or stack trace so that I get to know what method is causing the editors to close?

**Comment by nicolasvahidzein** [comment] 2021-11-12 16:31
Ok i will try it thank you so much Ben. I was not home when the blackout happened unfortunately. I will see later how it behaves.

**Comment by bpasero** [comment] 2021-11-12 16:32
I am sorry that the steps to reproduce are so involved for you, I hope there is no physical harm to any technical devices :)

**Comment by nicolasvahidzein** [comment] 2021-11-12 16:40
No it's the nature of the beast, everything is so complex these days. I have to say, i love your work on this IDE, it's wonderful. Do you also suggest improvements and the likes?

**Comment by nicolasvahidzein** [comment] 2021-11-12 16:57
BTW i copied over my settings, i hope this won't cause issues:

{
    
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.visible": true,
    "editor.fontSize": 18,
    "editor.trimAutoWhitespace": false,
    "editor.detectIndentation": false,
    "editor.insertSpaces": false,
    "editor.tabSize": 4,
	"editor.autoIndent": "full",
	"editor.comments.insertSpace": false, //don't add a space after a comment like so: // <-- dddd
	// "editor.renderWhitespace": "all",
	"workbench.editor.closeOnFileDelete": false,
	"git.autoRepositoryDetection": "subFolders",
	
    //status bar modifications
    "workbench.colorCustomizations": {
        "statusBar.background" : "#1a0352",
        "statusBar.noFolderBackground" : "#4d0be7",
        "statusBar.debuggingBackground": "#465502"
    },
	
	//PHP section
	//"php.validate.executablePath": null
	
    //dart section
    
    "[dart]":  {
        "editor.tabSize": 2,
        "editor.insertSpaces": false,
        "editor.detectIndentation": false,
		"editor.trimAutoWhitespace": false,
		"editor.autoIndent": "full",
		// "editor.renderWhitespace": "all",
    },
    
	"dart.closingLabels": true,
	
	"liveshare.shareExternalFiles": true,
	
	"dart.flutterHotRestartOnSave": true,
	"dart.openDevTools": "flutter",
	"peacock.favoriteColors": [
		{
			"name": "Angular Red",
			"value": "#b52e31"
		},
		{
			"name": "Auth0 Orange",
			"value": "#eb5424"
		},
		{
			"name": "Azure Blue",
			"value": "#007fff"
		},
		{
			"name": "C# Purple",
			"value": "#68217A"
		},
		{
			"name": "Gatsby Purple",
			"value": "#639"
		},
		{
			"name": "Go Cyan",
			"value": "#5dc9e2"
		},
		{
			"name": "Java Blue-Gray",
			"value": "#557c9b"
		},
		{
			"name": "JavaScript Yellow",
			"value": "#f9e64f"
		},
		{
			"name": "Mandalorian Blue",
			"value": "#1857a4"
		},
		{
			"name": "Node Green",
			"value": "#215732"
		},
		{
			"name": "React Blue",
			"value": "#00b3e6"
		},
		{
			"name": "Something Different",
			"value": "#832561"
		},
		{
			"name": "Vue Green",
			"value": "#42b883"
		}
	],
	"php.validate.run": "onType",
	"editor.wordWrap": "on",
	"dart.debugExternalLibraries": false,
	"dart.debugSdkLibraries": false,
	"explorer.confirmDragAndDrop": false,
	"diffEditor.ignoreTrimWhitespace": false,
	"editor.minimap.enabled": true,
	"breadcrumbs.enabled": true,
	"liveshare.allowGuestDebugControl": true,
	"liveshare.allowGuestTaskControl": true,
	"liveshare.languages.allowGuestCommandControl": true,
	"intelephense.stubs": [
		"apache",
		"bcmath",
		"bz2",
		"calendar",
		"com_dotnet",
		"Core",
		"ctype",
		"curl",
		"date",
		"dba",
		"dom",
		"enchant",
		"exif",
		"FFI",
		"fileinfo",
		"filter",
		"fpm",
		"ftp",
		"gd",
		"gettext",
		"gmp",
		"hash",
		"iconv",
		"imap",
		"intl",
		"json",
		"ldap",
		"libxml",
		"mbstring",
		"meta",
		"mysqli",
		"oci8",
		"odbc",
		"openssl",
		"pcntl",
		"pcre",
		"PDO",
		"pdo_ibm",
		"pdo_mysql",
		"pdo_pgsql",
		"pdo_sqlite",
		"pgsql",
		"Phar",
		"posix",
		"pspell",
		"readline",
		"Reflection",
		"session",
		"shmop",
		"SimpleXML",
		"snmp",
		"soap",
		"sockets",
		"sodium",
		"SPL",
		"sqlite3",
		"standard",
		"superglobals",
		"sysvmsg",
		"sysvsem",
		"sysvshm",
		"tidy",
		"tokenizer",
		"xml",
		"xmlreader",
		"xmlrpc",
		"xmlwriter",
		"xsl",
		"Zend OPcache",
		"zip",
		"zlib",
		"mongodb"
	],
	"dart.previewFlutterUiGuides": true,
	"dart.previewFlutterUiGuidesCustomTracking": true,
	"eslint.codeAction.disableRuleComment": {
		
	
	},
	"eslint.alwaysShowStatus": true,
	"eslint.format.enable": true,
	"vetur.format.options.tabSize": 4,
	"vetur.format.options.useTabs": true,
	"[html]": {
		"editor.defaultFormatter": "vscode.html-language-features"
	},
	"security.workspace.trust.untrustedFiles": "open",
	"workbench.editorAssociations": {
		"*.ipynb": "jupyter.notebook.ipynb"
	},
	"diffEditor.maxComputationTime": 0,
	"files.watcherExclude": {
		"**": true
	},
	"git.confirmSync": false,
	
}

**Comment by nicolasvahidzein** [comment] 2021-11-12 17:01
I cannot find fileEditorInput in the new build

**Comment by bpasero** [comment] 2021-11-13 07:02
It should be there but it needs internet connectivity to download/access some source maps. I have recorded the steps:


![recording](https://user-images.githubusercontent.com/900690/141609437-f8109da0-bead-46de-99e2-1fe737bddfe2.gif)

**Comment by nicolasvahidzein** [comment] 2021-11-13 16:08
Indeed it is here now. Thank you Ben.

**Comment by nicolasvahidzein** [comment] 2021-11-15 06:24
Btw turning the watcher off is not good as nothing is detected in git. Ill try vscode insider today to see how it behaves.

**Comment by bpasero** [comment] 2021-11-15 06:27
Sounds good.

**Comment by nicolasvahidzein** [comment] 2021-11-16 14:57
Hello Ben,

so i was able to catch one of those strange events for you:
![001](https://user-images.githubusercontent.com/29876108/142008945-473933fc-0f2e-466e-a579-8d016f10b83c.JPG)

**Comment by bpasero** [comment] 2021-11-16 18:24
@nicolasvahidzein thanks, that is indeed hinting to a file event from our watching library. Does latest insider version change anything?

**Comment by nicolasvahidzein** [comment] 2021-11-16 18:37
Will test that tonight. Thanks Ben.

**Comment by bpasero** [comment] 2021-11-16 18:41
Cool

**Comment by nicolasvahidzein** [comment] 2021-11-16 23:47
No such behavior on the insider version. Just asks to try accessing the file again. That is good news.

**Closed** 2021-11-17 05:58 UTC
Labels: needs more info, file-watcher

**Comment by nicolasvahidzein** [comment] 2021-11-20 10:27
Hello @bpasero Ben. Quick question, how will I know when to download the new version of vscode that includes this fix? Thanks for all your help in pinpointing this issue btw.

**Comment by bpasero** [comment] 2021-11-20 10:59
We release stable versions in the first week of a new month, so you would have to wait until first week of December or just stay on insiders for the time being.

**Comment by nicolasvahidzein** [comment] 2021-11-20 11:31
Ok thank you Ben.
