### ISSUE TITLE
Problems with resuming after breakpoint or pause

### ISSUE THREAD

**Issue by noizex** [microsoft/vscode#62468] opened 2018-10-28 14:32 UTC
Hello, I'm having problems telling the UI that execution has been resumed after hitting breakpoint or pausing. I seem to be missing some step, but I checked examples, other debug adapters and can't even find that part there. My current flow is this:

1. Set breakpoint (this works fine, breakpoint is sent to my runtime)
2. Breakpoint is hit, my runtime sends back info and trggers `new StoppedEvent('breakpoint', Const.THREAD_ID)` (this is single thread thing)
3. I haven't yet implemented stack capabilities in runtime so I just return some predefined list of stack trace lines to show them in UI. 
4. In debug UI the icon || (Pause) changes to |> (Continue) and other options become available (step etc.)

And here is where I'm encountering problems - I added Continue support:
```
protected continueRequest(response: DebugProtocol.ContinueResponse, args: DebugProtocol.ContinueArguments): void {
		this._remoteProcess.continue();
		this.sendResponse(response);
	} 
```
which sends command to runtime to resume execution. This works but the UI still shows |> icon and looks like if it was in stopped state. I tried sending `ContinuedEvent` but no luck here. I'm out of ideas what is responsible for telling UI that the execution continues and reflect that by showing back Pause buttons and greying out step functions. 

It's even worse with Pausing, because while breakpoint stop allows me to continue, after pausing the flow it'll still stay in || (Pause) mode for UI, so I can't resume from here. I think I miss information on what it is that decides what UI is displayed. I followed examples, but maybe something simple is missing here... 
Also, many times Pause just won't work - I click it but there is no `pauseRequest` being sent, which gives me some hint that maybe VS is not in a state where it expects pause? This is output from the logger:
```
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"angelscript","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsEvaluateForHovers":true,"supportsStepBack":true,"supportsRestartFrame":false}}
From client: attach({"type":"angelscript","request":"attach","name":"Run remote debugger","remoteHost":"127.0.0.1","remotePort":55557,"debugServer":55381,"__sessionId":"a6ec6b05-5d2f-43fb-a5d9-d1d1f04a03ab"})
To client: {"seq":0,"type":"event","event":"initialized"}
From client: setFunctionBreakpoints({"breakpoints":[]})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setFunctionBreakpoints","success":true}
From client: setExceptionBreakpoints({"filters":[]})
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":true}
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":6,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Thread 1"}]}}
```
and at this point clicking "Pause" does not send any request.

Not sure if this has any useful meaning but I'm only implementing "Attach" behaviour, because my runtime is not possible to be launched (it's remotely running process).

**Comment by paulo-fernando-silva** [comment] 2018-11-10 11:59
On vsc v1.28.2 I believe I'm getting a similar behavior on my own debug adaptor.

It works normally and I can stop no problems, but sometimes I send back the event:
`this.sendEvent(new StoppedEvent('breakpoint', OctaveDebugSession.THREAD_ID));`
Then UI does stop, requests all the data, and marks the line where it stopped, but the debug menubar is still showing only pause || as clickable.

The debugger is still working, and if I send commands via the console or if I use the evaluateExpression on mouse over some expression everything works. I the overlay is displayed correctly and the stack and variables view are also updated on step via console.
The UI is just stuck.

I confirmed that the StoppedEvent is still being sent back. But neither the breakpoint line nor the toolbar on the UI are updated anymore.

Is this supposed to be possible? To have a breakpoint active, but at the same time the menu bar is in a state of "program executing"? (see attached screenshot)

I have the log  in case that helps. In this particular case it locked at instruction 35 of the loop being debugged. Since the loop only has 8 instructions the same instruction was executed several times before. Which is strange as amount of data doesn't change during the iterations, and it worked fine in the previous iterations.

Stepping faster doesn't seem to make the reproduction rate any different. I tried a couple more times, and even though it eventually locks, once it did so after 4 steps, and another time it did so after 100+ times. 

Doing so I also noticed that if I press next and don't let go it'll send a:
`From client: disconnect({"restart":false})`
Not sure if vsc is supposed to work like that.

<img width="1392" alt="screen shot 2018-11-10 at 20 24 46" src="https://user-images.githubusercontent.com/6506378/48300810-db908680-e526-11e8-9199-07b10db03d9a.png">

**Comment by paulo-fernando-silva** [comment] 2018-11-10 16:20
I believe I found my issue. I was sending a response to the stepRequest after receiving a stackRequest. I guess vsc just kept on waiting for the stack response but that came out of order.
Sending the response to the step even before the step has finished executing seems to work.
But maybe the issue is still the same. Request/Response might be out of order.

**Comment by weinand** [comment] 2020-11-11 18:27
Since this report is rather old, and we have not received any other reports that VS Code is not working properly in this area, I'm closing the issue. If you still see the problem in the latest version of VS Code, please create a new issue.

**Closed by weinand** 2020-11-11 18:27 UTC
Labels: bug, debug
