### ISSUE TITLE
Better support for JSDoc @example tag.

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#56223] opened 2018-08-12 15:43 UTC
- VSCode Version:1.25.1 (1.25.1)
- OS Version: 10.14 Beta (18A353d)

Steps to Reproduce:

1. Create JSDoc comment in JavaScript with @example tag. 
2. Add spaces for indentation of example (see following code example).

```javascript
/**
 * Component can be instantiated with the new keyword, or extended to create a custom version of the Component.
 * @class Class to create a component.
 * @example New instance of Component class:
 * const title = new Component({
 *   container: 'header',
 *   state: 'World',
 *   render: message => <h1>Hello, {message}!</h1>
 * })
 * @example Extending Component class:
 * class UserList extends Component {
 *   constructor(props) {
 *     super(props)
 *     this.state = users
 *     this.container = 'section'
 *   }
 *   render(users) {
 *     return (
 *      <ul class='user-list'>
 *        {
 *          users.map(user => <li>{user.name}</li>)
 *        }
 *      </ul>
 *     )
 *   }
 * }
 */
```

When hovering over the class, VSCode shows the call signature complete with the above JSDoc content. The `@example` tags have proper colored highlighting, but all the whitespace for indentation is stripped. For very simple examples this is not so bad. But when you have an example with several layers of indentation, especially with braces, the result is unreadable.

Example image:

<img width="630" alt="screen shot 2018-08-12 at 7 59 58 am" src="https://user-images.githubusercontent.com/249218/44003651-1c8d82d6-9e0b-11e8-817e-60274715ff90.png">

I am aware that the `@example` tag is not listed in the supported tags at https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript. However, VSCode does recognize the tag and highlight its content correctly. Is adding whitespace support for the `@example` tag impossible? Seems like it would allow much richer and better looking intellisense.

**Comment by mjbvz** [comment] 2018-08-20 13:54
Duplicate of https://github.com/Microsoft/TypeScript/issues/15749

**Closed by mjbvz** 2018-08-20 13:54 UTC
Labels: javascript
