### ISSUE TITLE
cmd+down doesn't work when "workbench.list.openMode": "doubleClick" is set

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#68469] opened 2019-02-11 23:25 UTC
Found in https://github.com/Microsoft/vscode/issues/68018

**Comment by Tyriar** [comment] 2019-02-25 21:34
@roblourens maybe I'm doing something wrong but I removed all my settings and keybindings, searched something and now pressing cmd+down and cmd+return when focus is on a search result and it's doing nothing. Am I thinking right in that this should do the same thing as cmd+1? (since a preview editor will be opened)

This happens when both doubleClick and singleClick are set.

**Comment by roblourens** [comment] 2019-02-25 22:18
@joaomoreno this is from https://github.com/Microsoft/vscode/commit/3946e3233baba153802680044654d605a03ce926

It sounds right to not trigger onDidChangeSelection when the selection did not actually change, but we can select a selected element to make different things happen.

Similar, select an element in the file explorer then alt+click. It should open to the side (on mac) now it does nothing.

**Comment by roblourens** [comment] 2019-02-25 22:24
Maybe the same, "go to definition" on something with multiple definitions (like the `onDidChangeSelection` event) and the first item in the peek tree is selected but it no longer navigates to that item.

**Comment by isidorn** [comment] 2019-02-26 11:06
Feels like a duplicate of https://github.com/Microsoft/vscode/issues/69284
Leaving up to @joaomoreno to decide if to close as dupe.

**Comment by joaomoreno** [comment] 2019-02-26 15:26
It was hard to understand what is the issue here, since I didn't know what <kbd>Enter</kbd> should do in that case. After testing stable, I verified that <kbd>Enter</kbd> should open and focus the editor. I've pushed a fix for that.

> This happens when both doubleClick and singleClick are set.

@Tyriar Correct. Even in stable. My fix should cover that as well.

> Maybe the same, "go to definition" on something with multiple definitions (like the `onDidChangeSelection` event) and the first item in the peek tree is selected but it no longer navigates to that item right away.

Can't repro that any more, maybe got fixed today with my other changes.

**Closed** 2019-02-26 15:28 UTC
Labels: bug, tree
