### ISSUE TITLE
All debuggers don't start if any of them has problem while loading

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#68739] opened 2019-02-14 21:23 UTC
Issue Type: <b>Bug</b>

I have installed official C# extension, which includes debugger support. For some reason it crashes on my arch linux (see log 1).

After it crashes I **can't start any debugger** (python, haskell etc.). Nothing literally happens. See screencast:
![peek 2019-02-15 00-21](https://user-images.githubusercontent.com/7345761/52818409-c132ef80-30b7-11e9-8ac2-a70bc0bfd11c.gif)

log 1:
```
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha2-20181112.3
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

[Info  - 0:16:37] Connection to server got closed. Server will restart.
[Info  - 0:16:38] Connection to server got closed. Server will restart.
[Info  - 0:16:39] Connection to server got closed. Server will restart.
[Info  - 0:16:40] Connection to server got closed. Server will restart.
[Error - 0:16:41] Connection to server got closed. Server will not be restarted.

```
PS I don't care about C# debugging at all, this extension breaks debug support.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.20.7-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 1730)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-hie-server|ala|0.0.24
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
vscode-dash|dee|2.0.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
file-icons|fil|1.0.16
code-runner|for|0.9.7
kotlin|fwc|0.1.13
godot-tools|gee|0.3.7
todo-tree|Gru|0.0.118
live-html-previewer|hdg|0.3.0
hoogle-vscode|jca|0.0.7
svn-scm|joh|1.47.1
language-haskell|jus|2.5.0
favorites|kdc|2.4.5
Lisp|mat|0.1.8
vscode-todo-parser|min|1.9.1
vscode-language-pack-ru|MS-|1.31.4
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
vsliveshare|ms-|0.3.1182
debugger-for-chrome|msj|4.11.2
gradle-language|nac|0.2.3
vscode-subword-navigation|ow|1.2.0
phoityne-vscode|pho|0.0.21
java|red|0.38.0
vscode-yaml|red|0.2.1
rust|rus|0.5.3
vscode-hexdump|sle|1.7.2
emmylua|tan|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.3
vscode-svg-previewer|vit|0.3.1
vscode-java-debug|vsc|0.16.0
debug|web|0.22.0
jinja|who|0.0.8
clang-format|xav|1.9.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by weinand** [comment] 2019-02-15 10:29
Does restarting VS Code helps if you are in the situation that debugging no longer works?

You have a ton of extensions. This has the potential that some of them are interacting in a way that results in the problem you are seeing.
Could you please disable all extensions with the exception of C# and Python. 
Does C# still crashes in that smaller setup?
If yes, is it still not possible to start Python debugging in that situation?

**Comment by Yanpas** [comment] 2019-02-15 10:43
> Does restarting VS Code helps if you are in the situation that debugging no longer works?

Yes but only if I disable C# extension. Actucally that's what I do to workaround: disable it and run "Reload window" command.

I'll test it today later, currently have no access to my arch machine

**Comment by bmewburn** [comment] 2019-02-15 11:17
I came across this too trying to start the typescript debugger. It's a bug in Razor.VSCode https://github.com/aspnet/Razor.VSCode/issues/223

**Comment by Yanpas** [comment] 2019-02-15 21:15
I have created new folder where locally disabled all extensions except c# and python ones. c# extension continues to crash, I can't even create launch.json from gui, see screenshot. And of course debugger still doesn't launch.

I think you need to create basic debugger extension which throws exceptions everywhere it can to reproduce, I don't know

![image](https://user-images.githubusercontent.com/7345761/52884625-85635d00-317f-11e9-89ed-221b7b8c6418.png)

I also believe that this issue is not related to new release, I use arch seldom.

**Comment by weinand** [comment] 2019-02-15 23:42
Please file this issue against C# extension.

**Comment by Yanpas** [comment] 2019-02-15 23:51
There is definitely an issue with extension, but vscode has an issue too. It stops working properly with buggy extension. Why close?

**Comment by weinand** [comment] 2019-03-17 23:25
@isidorn let's investigate why VS Code debugging stops working after the C# issue.

**Comment by isidorn** [comment] 2019-03-18 10:18
@weinand ok, I can investigate.

**Comment by isidorn** [comment] 2019-03-20 10:56
I wrote a debug adapter extension that throws on start and I can not reproduce this exact issue.
However I could reproduce a similar issue which might cause this and I fixed this.
@Yanpas @bmewburn So please try vscode insiders tomorrow and let me know if you can still reproduce https://code.visualstudio.com/insiders/

Also can you reproduce this if you uninstall or disable the live share extension?

**Comment by Yanpas** [comment] 2019-03-20 11:41
Can you upload your extension to github? I'll try to experiment with throw in different methods or/and add sleeps.

Will test soon.

**Comment by isidorn** [comment] 2019-03-20 11:47
@Yanpas I just modified the mock debug extension, you can find it here and try to throw in multiple places https://github.com/Microsoft/vscode-mock-debug
Though just using C# on arch linux should do it for you. Also please note my live share comment.

**Comment by Yanpas** [comment] 2019-03-21 21:05
Nope, that didn't help, still python debugger doesn't start with C# extension:
```
Version: 1.33.0-insider
Commit: edd2c737f9b6f08cd0e30050b441cd262eb7f0d8
Date: 2019-03-21T06:14:07.104Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-arch1-1-ARCH
```

**Comment by Yanpas** [comment] 2019-03-21 21:44
![image](https://user-images.githubusercontent.com/7345761/54785722-01960800-4c38-11e9-802a-ec856846fb13.png)
![image](https://user-images.githubusercontent.com/7345761/54787050-a403ba80-4c3b-11e9-827c-26b80cf41544.png)

Seems like error happens in startDebugging (debugService.ts), after startInitializingState. I catch error in different places

**Comment by Yanpas** [comment] 2019-03-21 21:50
You may try to run manjaro vbox image to reproduce since this distro is very close to arch
https://www.osboxes.org/manjaro/

**Comment by isidorn** [comment] 2019-03-22 11:11
@yanpas thanks for providing more details. But I could still not repro.
Can you try to find the most specific place where the error is thrown?
Also when you start debugging Python which does not start can you put a breakpoint [here](https://github.com/Microsoft/vscode/blob/a94502f9dfc5aa2aeb819be3457c0a61ba5171f6/src/vs/workbench/contrib/debug/electron-browser/debugService.ts#L257) and step and try to figure out why debugging is not started.
We can also do a debugging session together if you have time.

Setting up a archlinux machine I could look into doing some time in the future since I unfortunetly do not have time now.

**Comment by Yanpas** [comment] 2019-03-22 21:49
Funny way to break C# extension is `cp /usr/bin/echo ~/.vscode-oss-dev/extensions/ms-vscode.csharp-1.17.1/.razor/rzls`

While trying to debug vscode noticed that likely Promise returned in `this.extensionService.activateByEvent` line 259 never gets resolved:

```diff
diff --git a/src/vs/workbench/contrib/debug/electron-browser/debugService.ts b/src/vs/workbench/contrib/debug/electron-browser/debugService.ts
index 8c0d6605cf..fe8bf8b8e3 100644
--- a/src/vs/workbench/contrib/debug/electron-browser/debugService.ts
+++ b/src/vs/workbench/contrib/debug/electron-browser/debugService.ts
@@ -71,6 +71,26 @@ const enum TaskRunResult {
        Success
 }
 
+function promiseTimeout<T>(ms: number, promise:Promise<T>){
+       return new Promise<T>(function(resolve, reject){
+
+               // create a timeout to reject promise if not resolved
+               let timer = setTimeout(function(){
+                       reject(new Error("promise timeout"));
+               }, ms);
+
+               promise
+                       .then(function(res){
+                               clearTimeout(timer);
+                               resolve(res);
+                       })
+                       .catch(function(err){
+                               clearTimeout(timer);
+                               reject(err);
+                       });
+       });
+}
+
 export class DebugService implements IDebugService {
        _serviceBrand: any;
 
@@ -256,7 +276,7 @@ export class DebugService implements IDebugService {
 
                this.startInitializingState();
                // make sure to save all files and that the configuration is up to date
-               return this.extensionService.activateByEvent('onDebug').then(() => {
+               let p = this.extensionService.activateByEvent('onDebug').then(() => {
                        return this.textFileService.saveAll().then(() => this.configurationService.reloadConfiguration(launch ? launch.workspace : undefined).then(() => {
                                return this.extensionService.whenInstalledExtensionsRegistered().then(() => {
 
@@ -336,6 +356,7 @@ export class DebugService implements IDebugService {
                        this.endInitializingState();
                        return Promise.reject(err);
                });
+               return promiseTimeout(1000, p);
        }
 
        /**
```

**Comment by isidorn** [comment] 2019-03-26 09:34
Thanks for providing more details, reopening to investigate more

**Comment by isidorn** [comment] 2019-03-27 16:39
Should be fixed  via https://github.com/Microsoft/vscode/commit/d9a72bc222b550398ebaf553c02e8f21f292f034

**Comment by Yanpas** [comment] 2019-03-27 21:54
Were you able to reproduce this bug with modification of rzls executable on any linux and c# extension v 1.17.1?

I've pulled master now, ran `yarn install; yarn watch` and launched nodejs debugger inside code-oss-dev and nothing happens:
![Peek 2019-03-28 00-52](https://user-images.githubusercontent.com/7345761/55114762-e0c82980-50f3-11e9-88c7-30e6f4e7e7b3.gif)

**Comment by isidorn** [comment] 2019-03-28 10:39
@Yanpas no, I did not change the rzis executable.
Let's reopen and assign to next milestone to investigate then.

**Comment by isidorn** [comment] 2019-07-03 14:16
@Yanpas Sorry for not responding on this sooner. I can not reproduce following your steps @Yanpas with the latest out of source on my os x.
I have modified the `rzis` file and the C# basically crashes on start of since it is not supported with vscode out of source. I would expect you also see something similar.
After the crash I can normally run my node debugger. If I use vscode-insiders I can debug C# even if I delete the whole `.rzis` file

Is it possible to get a different reproducable case? Best one would be modifying a fork of Mock debugger from [here](https://github.com/microsoft/vscode-mock-debug).
Or is it possible that we do a live debuggin session on your machine?
For example just F1 > developer tools > put a brekapoint [here](https://github.com/Microsoft/vscode/blob/989e1fa995a7973a0b802c9ce7db786f416b1229/src/vs/workbench/contrib/debug/browser/debugService.ts#L255) when you launch debugging after a failure and try to figure out why it just hangse?

![failure](https://user-images.githubusercontent.com/1926584/60598040-4fc8b480-9dac-11e9-8140-a556249835c7.gif)

**Comment by Yanpas** [comment] 2019-07-03 14:59
I cannot reproduce with insiders and manually instaleed 1.17.1. I even tried `find -executable | xargs rm -f` from extension folder. May be closed I think, thank you!

**Comment by isidorn** [comment] 2019-07-03 15:04
@Yanpas  Thank you for looking into it. Closing.
If someone else can reproduce please provide more steps with regards to my last comment from above.

**Closed by isidorn** 2019-07-03 15:04 UTC
Labels: bug, debug, needs more info

**Comment by misolori** [comment] 2019-07-31 22:44
@isidorn assuming this doesn't need to be verified? It was never removed from the July milestone.
