### ISSUE TITLE
Highlight file on active editor change shouldn't scroll explorer to the file (only highlight it)

### ISSUE THREAD

**Issue by gregid** [microsoft/vscode#84365] opened 2019-11-09 11:15 UTC
With the 1.40.0 release, change of the active file in the editor also highlights the active file in the explorer. This is a nice feature unfortunately at the moment it doesn't work well with split editor.
If you have 2 (or more) split editors and are opening a new file it will open file in the active split editor. 

Say you found the file in the explorer you want to open but you want to change where the file should be opened, so you click in the right split editor first - activating it. But with a recent change this will automatically scroll to the file in just activated split editor. And now you need to browse for the file you just wanted to open... again. With projects with many files and more complex folder structure this is a problem.

Proposed change:
1. Add setting:
    `Explorer: Scroll To Active File on Editor Change`
    - if `true` the behaviour will stay as it is right now + see no. 2
    - if `false` it will only highlight file + see no. 2.
   - default: `false`
2. Highlighted file in explorer should be marked in an explorer scroll bar - similar to how selected line is marked in editor window - with horizontal bar.

**Comment by isidorn** [comment] 2019-11-14 10:23
Duplicate of these issues https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3Aisidorn+explorer+highlight

**Closed by isidorn** 2019-11-14 10:23 UTC

**Comment by gregid** [comment] 2019-11-14 10:36
I looked through these issues but couldn't find any where I could disable current behaviour. What's the consensus as I understand there are many people that may have different take on it.
