### ISSUE TITLE
Side bar part is not shown in Splash screen in empty window

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#55019] opened 2018-07-25 09:31 UTC
Testing #54937

- Open a new empty window
- Open explorer
- Reload window

Splash screen does not show side bar part

**Comment by jrieken** [comment] 2018-07-25 11:03
Yeah, we have done that on purpose because usually no sidebar shows in the empty window case

**Comment by jrieken** [comment] 2018-09-12 13:13
closing as designed.

**Closed by jrieken** 2018-09-12 13:13 UTC
Labels: as-designed, under-discussion, workbench-rapid-render
