### ISSUE TITLE
Feature Suggestion: Go to implementation

### ISSUE THREAD

**Issue by RoarkeRandall** [Microsoft/vscode#10806] opened 2016-08-22 19:32 UTC
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:
1.  Press f12 on a function that is an interface type. 
2.  Editor will go to declaration of the function on the interface, rather than the implementation (as expected). 

In Visual Studio (with resharper) this is a nice feature.

**Comment by dvlsg** [comment] 2016-08-24 16:56
Side note, this is actually available in [Visual Studio 2015 Update 1](https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx) without resharper. I believe a default shortcut of Ctrl+F12 was added in Update 2.

**Comment by Tyriar** [comment] 2016-10-17 16:00
This would be really handy to navigate vscode's source faster, currently I have to use view references and navigate to the implementation in the peek view.

**Comment by kkovalevskiy** [comment] 2016-12-15 05:29
As I can see, tsserver has added support of this feature on their side (https://github.com/Microsoft/TypeScript/pull/10482), so why we still don't have it in vs code?

**Comment by Tyriar** [comment] 2016-12-15 07:59
Thanks for pointing this out @kkovalevskiy! I've reassigned this and am very excited about the possibility of being able to use it soon 😉

**Comment by jrieken** [comment] 2016-12-20 08:47
@Tyriar Taking this back because it shouldn't be a TypeScript only solution but implemented in the spirit of other language features, like go to definition, find referenced etc

**Comment by jrieken** [comment] 2017-01-13 09:37
![screen shot 2017-01-13 at 10 35 41](https://cloud.githubusercontent.com/assets/1794099/21925101/30e339a6-d97c-11e6-9ce8-f8b4acde1098.png)

@mjbvz I have reopened this because it takes aways the Find References keyboard shortcut

**Comment by jrieken** [comment] 2017-01-13 11:22
Sorry, actually none-sense. I was confused with another extension I have

**Closed** 2017-01-13 11:22 UTC
Labels: api, feature-request

**Comment by unional** [comment] 2017-03-24 18:25
Just tested and it is not working. It still routed to the declaration file.

**Comment by FredrikFolkesson** [comment] 2017-04-12 11:27
I also have problems here, going to declaration on another package works and I get to the d.ts file, but going to implementation I only get "No implementation found"

**Comment by mjbvz** [comment] 2017-04-12 21:07
@FredrikFolkesson Please open new issues for any problems related to `go to implementation`. Include a small project and a list of  repo steps so that we can investigate

Thanks

**Comment by Wenzil** [comment] 2017-05-09 16:41
Has a new issue been opened yet? The issue is still occurring

**Comment by 3x1010** [comment] 2017-08-25 08:46
Sorry if I post here but I'm getting mad about this topic.
I can't stand the fact that visual studio code is not able to jump to the definition in a case like this:

foo = funtion(){
  this.init();
}

foo.prototype.init = function(){
  // code
}

if I press F12, Alt F12, Ctrl F12, Shift F12, Ctrl F12 or whatever on "this.init()" Visual Studio Code is not able to jump to the foo.prototype.init method.

Where am I wrong? In Visual Studio 2015 this works, also it works on sublime.
Thanks in advance

**Comment by Tyriar** [comment] 2017-08-30 15:54
@mjbvz is this just a limitation of tsserver that it doesn't check the prototype? Does VS2015 use some other system?

```js
// this.init() go to def doesn't works
var foo = function() {
	this.init();
};
foo.prototype.init = function() {
	// code
};

// this.init() go to def works
class Foo {
	constructor() {
		this.init();
	}

	init() {
	}
}
```

**Comment by mjbvz** [comment] 2017-08-30 23:07
VS2015 used a different JavaScript analysis engine, not one the from typescript that we use and that VS2017 uses. That engine could handle some cases better than we can, but also had some performance issue and to my knowledge was not being actively maintained. 

However the case that @3x1010 provided looks like bug in TS.  For the code:

```js
function foo() {
	this.init();
}

foo.prototype.init = function () { /*...*/}

const a = new foo();
a.init()
```

Go to definition does work on `a.init` but not on this.init. I've opened https://github.com/Microsoft/TypeScript/issues/18171 to track this
