### ISSUE TITLE
Git: Close Repository reopens right after

### ISSUE THREAD

**Issue by andronat** [microsoft/vscode#107398] opened 2020-09-25 01:15 UTC
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (8 hrs ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
Steps to Reproduce:
```
`Help > Report` didn't work 😕 

Steps to Reproduce:

1. I'm connecting to a Remote-SSH vagrant host
2. I'm closing a repository from `Source Control` -> `Close Repository`

![vscode-bug](https://user-images.githubusercontent.com/793408/94215555-e3683280-fed4-11ea-8c3c-cab7bf2751d6.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment] 2020-09-30 11:34
Yeah I've even seen this locally, but failed to repro reliably.

**Comment by andronat** [comment] 2020-09-30 14:34
I reproduce it consistently in Remote-SSH 😕

**Comment by AlopexXx** [comment] 2020-10-21 10:48
I have the same Problem

**Comment by gustavo-reyes** [comment] 2020-10-21 19:26
I noticed this also while looking at another issue. I think either one or both of the following conditions needs to be true in order to reproduce the issue:

1. There needs to be some pending/uncommitted changes in the repo that you are trying to close.
2. A file in the repo that you are trying to close needs to be open in the editor.

In the video above, condition 1 appears to be true.

**Comment by sunithapatel** [comment] 2021-07-15 16:01
I would like to work on this issue if it is still available to work on.

**Comment by sunithapatel** [comment] 2021-07-15 16:03
I have some questions around the expected behavior here. Once you click 'Close Repository', should it always stay closed if you open any files from the folder for that repository, or if you close and re-open the workspace containing that folder, or the folder itself in VS Code?

**Comment by sunithapatel** [comment] 2021-07-15 21:29
@philipjmurphy It looks like the scenario you described is working as expected since you are editing a file that is within that closed repository. So it would reopen that repository because of that.
It seems like the original issue is the repository shows up even after closing but no files are open on the left. So slightly different from what you reported.
Potentially it may be an issue related to Remote-SSH.

**Comment by eamodio** [comment] 2021-07-15 21:30
I think this should only be "persisted" for the current session (so all in memory), so if you reload the window, or open a different workspace the "close list" is forgotten/cleared.

**Comment by sunithapatel** [comment] 2021-07-15 23:30
@eamodio Thank you for replying! I made a pull request to store a list of closed repositories for the session. I mentioned in the PR about some testing that I did, but there may be more scenarios that I am missing. 
Please let me know if there are more things that I can do with testing, or if there are unit tests that I need to do. Thank you in advance for the help!

**Comment by rs333** [comment] 2021-11-07 14:29
I'm late to this discussion but it seems like desired behavior that if  you close a repository, then later open/edit a file from the closed repository, you would want that repository to show up again.  Especially since there does not appear to be a way for you to reopen the repository other than reloading the window which takes noticeably more time than just opening a file.  

Note that in v1.62.0 using remote-ssh, it works how I would expect with one exception.  Specifically, if you close the repository, it should stay closed until either
1) You open a file from the closed repository that you were not previously editing/have open.
2) You modify a file from the closed repository that was previously open.
3) You close and reopen the workspace that contains the closed repository.
4) You reload the window.
* Note:  Current behavior matches items 1,3, and 4 but not 2.  Instead of 2, the repo will be opened again if you navigate away from a previously open file and return to it.  If you simply change the file without navigating away from it and then save it, the repo does not open.

If the desire is to not reopen the repository for items 1 and 2, recommend adding an option to reopen the closed repository so that reloading the window is not necessary.

**Comment by Xunnamius** [comment] 2022-03-29 02:15
Running into this problem in 2022. Was this fixed? I noticed there's an unmerged PR.

**Comment by Spenhouet** [comment] 2022-04-11 07:37
Can confirm, still having this issue with VS code 1.66.0.

**Comment by RichardJeon** [comment] 2022-07-01 07:34
Delete the hidden folder called 'git'.  That's how I solved it and I don't know what kind of other problem might be.

**Comment by waynegemmell** [comment] 2022-08-18 07:54
I'm also frustrated by this. I have about 10 repositories that I don't want to work on but they keep showing up on restarting VSCode. This cluttered workspace is not ideal..

**Comment by plague006** [comment] 2022-12-13 20:16
git.ignoredRepositories can be used to keep unwanted git repos closed/out of sight.

(This was mentioned in other tickets, but I'm copying it here since the others are closed.)

**Comment by lszomoru** [comment] 2023-06-15 10:37
The following changes have been implemented and are available in the latest Insiders release:
* Add welcome view if all repositories have been closed
* Do not reopen repositories that were manually closed
* Remember closed repositories per workspace
* New command command to reopen closed repositories if there are any that are closed

**Closed by lszomoru** 2023-06-15 10:37 UTC
Labels: bug, help wanted, git, good first issue
