### ISSUE TITLE
Breadcrumbs: twisties not aligned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57349] opened 2018-08-28 09:16 UTC
Refs: https://github.com/Microsoft/vscode/issues/57280

OS: Windows 10 (no zooming)

Labels and twisties are not centered to each other:

![image](https://user-images.githubusercontent.com/900690/44713557-ae017880-aab3-11e8-87a5-6e32d64298a9.png)

**Comment by bpasero** [comment] 2018-08-28 09:43
Here is how the explorer shows twistie:

![image](https://user-images.githubusercontent.com/900690/44715197-71378080-aab7-11e8-9732-8c01db517f8d.png)

Compared to breadcrumb:

![image](https://user-images.githubusercontent.com/900690/44715221-7f859c80-aab7-11e8-9aa1-0866a21beccb.png)

I am running this on a native windows box (not a VM).

**Comment by bpasero** [comment] 2018-08-28 09:44
Somehow the alignment seems to be off in the explorer too, but its not so visible because there is always just one twistie.

**Comment by jrieken** [comment] 2018-08-28 09:49
VM or not shouldn't make a difference... Please digg into the CSS rules that cause this funky baseline

**Comment by bpasero** [comment] 2018-08-28 10:39
Explorer:
![capture](https://user-images.githubusercontent.com/900690/44718110-4f41fc00-aabf-11e8-90fb-3799fa6f8b56.PNG)

Breadcrumb:
![cap2](https://user-images.githubusercontent.com/900690/44718112-4f41fc00-aabf-11e8-8982-f3f0358dd81f.PNG)

one difference is that the explorer one has a height of 22px, which is good to set because the line-height typically is 22px. Now why the breadcrumb twistie is not centered is something I have not figured out yet.

**Comment by jrieken** [comment] 2018-08-28 10:45
Still, doesn't explain why this happens your but not my machine...

**Comment by bpasero** [comment] 2018-08-28 10:53
One thing that improves it for me is if the breadcrumb items have 22px height, looks like this was not true for the labels:

![image](https://user-images.githubusercontent.com/900690/44718733-4d793800-aac1-11e8-80ff-0bc6e31648cc.png)

**Comment by jrieken** [comment] 2018-08-29 10:16
@bpasero I have pushed some height tweak that appear to make sense but my problem is that I am not able to reproduce this. Can you check from master?

**Comment by bpasero** [comment] 2018-08-29 10:34
@jrieken yeah looks better:

![image](https://user-images.githubusercontent.com/900690/44782558-e07ca580-ab87-11e8-9f21-420a63ef10d2.png)

Now it seems though that the icon (TS) is a bit too high.

**Comment by jrieken** [comment] 2018-08-29 10:51
Closing as the icon is too hight in all places.

**Closed** 2018-08-29 10:51 UTC
Labels: breadcrumbs, bug, needs more info
