### ISSUE TITLE
Electron: Enable renderer process reuse

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#120431] opened 2021-04-02 15:41 UTC
We currently have process reuse disabled in `main.js`, but considering how the native modules we use are now context-aware, we can start looking more into enabling process reuse.

There are other processes to look into, but for now, I would like to concentrate just on the **extensionHost** and **watcherService**. For those, I'm wondering 

1. Are the processes killed + restarted during a reload?
2. Are the processes killed + restarted when a user opens a new folder or workspace? I'm currently trying to see if such actions are equivalent to a reload right now, but haven't yet found the code.
3. If yes to 1 and/or 2, can they be set up in a way using IPC such that the main process can send a reset signal during reloads? This way, we can continue using the same child process, and it's just the state of the child process that gets reset.

**Comment by rzhao271** [comment] 2021-04-02 15:41
CC @deepak1556

**Comment by bpasero** [comment] 2021-04-03 09:36
@rzhao271 anytime a window either gets reloaded, closed or workspace changed within the window, the same code gets triggered to handle this because anyone in the window can participate on this event to either veto it from happening or doing some task (even long running). The events are `ILifecycleService.onBeforeShutdown` and `ILifecycleService.onWillShutdown`. The latter is triggered from here:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.ts#L86

I think we can easily use these events to kill processes when the `onWillShutdown` is fired. 

The watcher is actually a [IPC Client](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/base/parts/ipc/node/ipc.cp.ts#L86) and it looks like the dispose method will kill the process. 

I think the extension host already has code to participate in the shutdown so that extensions can properly get deactivated: 

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L130

A couple of things we have to make sure:
- are there other child processes that the renderer spawns (e.g. search is also a process!)
- are we sure all native modules are either context aware or no longer being used from the renderer (e.g.,only recently I found that the shared process -which is also a renderer process - was still not ready, see https://github.com/microsoft/vscode/issues/120159)
- are there any other implications for process renderer reuse that we need to be thinking about

Would you be interested in providing a PR for this work to help out on this task?

**Comment by bpasero** [comment] 2021-04-03 14:49
It looks like `[windows-process-tree](https://github.com/microsoft/vscode-windows-process-tree)` is a dependency that we still drag into the shared process which has not been adopted set to be context aware iirc. A requirement would be to first make that module context aware unless we can control the process reuse per renderer.

**Comment by rzhao271** [comment] 2021-04-05 17:27
> are there other child processes that the renderer spawns (e.g. search is also a process!)

Deepak mentioned that I can look for places that call `bootstrap-fork`, and so I have the following list:
- watcherService
- customEndpointTelemetryService
- ptyHostService
- localProcessExtensionHost
- searchService

The following places use `loadURL` to open a new window:
- issueMainService
- sharedProcess
- window in `windows/electron-main`

> are we sure all native modules are either context aware or no longer being used from the renderer (e.g.,only recently I found that the shared process -which is also a renderer process - was still not ready, see #120159)

Before doing any optimizations (this issue), we should double-check that all the native modules we use are context-aware. I'll create a separate issue for `windows-process-tree`.

> are there any other implications for process renderer reuse that we need to be thinking about

Deepak provided two scenarios to consider, which are reloading a window, and switching the current workspace. Are there any other cases that could involve a process being reused?

If we implement a reset signal so that instead of killing + relaunching the window, the window state is simply reset, a part we would have to be careful about would be ensuring the old state doesn't leak into the new one.

**Comment by deepak1556** [comment] 2021-04-05 18:27
@bpasero in what situations does the shared process get reloaded ?

**Comment by bpasero** [comment] 2021-04-06 06:01
> Deepak mentioned that I can look for places that call bootstrap-fork

Yes, that is a good way to find out what child processes we spawn from a renderer.

> The following places use loadURL to open a new window

Fyi that `issueMainService` has 2 different windows: the process explorer and the issue reporter

> Before doing any optimizations (this issue), we should double-check that all the native modules we use are context-aware

Yes, I would suggest to do a pass over our `dependencies` of `package.json` including the `optionalDependencies` which list specific native modules for Windows only and find the ones which are still being used in renderers.

When I did that last time, I only found the `windows-process-tree`, while the others where only accessed from either a child process (like file watchers) or the main process.

> Deepak provided two scenarios to consider, which are reloading a window, and switching the current workspace

At least for VSCode workbench windows, these 2 are the same. They both go through the same code and will trigger `loadURL` eventually.

> If we implement a reset signal so that instead of killing + relaunching the window, the window state is simply reset, a part we would have to be careful about would be ensuring the old state doesn't leak into the new one.

I do not think that keeping the script context alive is an option currently, simply because we currently have no means of cleaning up all the state on shutdown. So far we get a free cleanup because the context changes everytime we call `loadURL`. My understanding is that we continue to call `loadURL`, even when process reuse is enabled, or not?

@deepak1556 

> in what situations does the shared process get reloaded

Never. We have no support to reconnect to the shared process currently.

**Comment by deepak1556** [comment] 2021-04-06 06:37
>  So far we get a free cleanup because the context changes everytime we call loadURL. My understanding is that we continue to call loadURL, even when process reuse is enabled, or not?

That is correct and there will be a context change on reload. Based on the lifecycle hooks you have mentioned in https://github.com/microsoft/vscode/issues/120431#issuecomment-812841013 , they are sufficient to have child processes restart in the process reuse model as well, we don't have to treat the process reuse mode as a different state.

**Comment by rzhao271** [comment] 2021-04-06 20:21
> #35109 is related where we discussed the concept of doing a workspace change without a loadURL call, but there is lots of work involved currently.

@bpasero So this issue is essentially reviving #35109? I would also like to confirm what is meant by there being "lots of work involved currently", because I currently only see two blockers:

1. Verify the native modules are context-aware (shouldn't take too long)
2. Merging Electron 12 into Insiders and turning on process reuse (this one's riskier and we will likely have regressions to work on first)

**Comment by deepak1556** [comment] 2021-04-06 20:33
We should keep the workspace reuse idea tracked separately, this issue I would like to track only the work required to enable

```
app.allowRendererProcessReuse = true;
```

For that the blockers:

1) Verify the native modules loaded in workbench and shared process are context aware, ignore modules loaded in other processes as they are not affected

2) Turn on the flag in master and identify regressions. This need not depend on Electron 12 adoption

3) Ensure child processes spawned from workbench are restarted on reload.

**Comment by bpasero** [comment] 2021-04-07 05:20
Agree on https://github.com/microsoft/vscode/issues/120431#issuecomment-814420518. Some comments:

> Turn on the flag in master and identify regressions. This need not depend on Electron 12 adoption

To clarify: are you suggesting to push this to insiders/stable even before Electron 12 and even before we moved away from `webview`?

> Ensure child processes spawned from workbench are restarted on reload

I think they automatically get restarted because we always spawn them from the workbench when it starts. So the task at hand would be to ensure that the processes a renderer spawns properly terminate as part of the workbench shutdown (which is an event that happens anytime a window is closed, reloaded or when the workspace changes).

**Comment by deepak1556** [comment] 2021-04-07 08:18
> To clarify: are you suggesting to push this to insiders/stable even before Electron 12 and even before we moved away from webview?

yup that is correct, since electron 11 already supports process reuse. I think this should be experimented on current main branch.

**Comment by bpasero** [comment] 2021-04-07 08:21
@deepak1556 oh sorry, nevermind. I confused myself here with the idea to enable `contextIsolation` :). Too many things...

**Comment by rzhao271** [comment] 2021-04-07 23:07
Some notes based on offline discussions:

> Verify the native modules loaded in workbench and shared process are context aware, ignore modules loaded in other processes as they are not affected

1. The shared process is not being killed and restarted during reloads. Therefore, we don't need native modules under the shared process to be context-aware right now. Even if we did, the only native modules I see are `node-pty` and `vscode-windows-process-tree`. I'm making the latter context-aware in https://github.com/microsoft/vscode-windows-process-tree/pull/30 and I'm not sure about the former yet. 
2. The workbench is being killed and restarted during reloads. The native modules that are used or might be used under the workbench are `native-is-elevated`, `vscode-windows-ca-certs`, `native-watchdog`, `nsfw`, `fsevents`, and `spdlog`. @deepak1556 has confirmed these modules are context aware (and I also took a look at some of them).

> Turn on the flag in master and identify regressions. This need not depend on Electron 12 adoption
> Ensure child processes spawned from workbench are restarted on reload.

Currently, the largest regression _is_ the fact that child processes spawned from the workbench are not restarting on reloads. Right now with the process reuse flag enabled, we have the following:

1. The child processes of the workbench are killed.
2. `workbench.html` under `electron-browser` is loaded along with all the scripts.
3. The child processes of the workbench are _not_ restarted.

**Comment by deepak1556** [comment] 2021-04-08 02:39
> The workbench is being killed and restarted during reloads

Are you saying there is a process swap on reloads ?

> The native modules that are used or might be used under the workbench are native-is-elevated, vscode-windows-ca-certs, native-watchdog, nsfw, fsevents, and spdlog

native-watchdog is not context-aware, the module has global states that will conflict when used from multiple contexts.

spdlog should not be used in renderer after https://github.com/microsoft/vscode/issues/120159, how did you confirm spdlog usage ?

**Comment by bpasero** [comment] 2021-04-08 05:49
> The shared process is not being killed and restarted during reloads

Isn't `node-pty` only used in child processes from the shared process? My understanding is that there is one child process per terminal tab and only in there we use `node-pty`?

> The native modules that are used or might be used under the workbench are `native-is-elevated`, `vscode-windows-ca-certs`, `native-watchdog`, `nsfw`, `fsevents`, and `spdlog`

Can you clarify how you found these dependencies, from my memory:
* `native-is-elevated` is provided only from `electron-main` [here](https://github.com/microsoft/vscode/blob/9c2b05377852217453d3f7b0151bf60a327989a6/src/vs/platform/native/electron-main/nativeHostMainService.ts#L386-L386)
* `vscode-windows-ca-certs` is not a direct dependency anymore, but possibly a dependency of a module we depend on now (discussion in https://github.com/microsoft/vscode/issues/120546
* `native-watchdog` seems to be used only in the extension host process which is a child process of the renderer
* `nsfw`, `fsevents` are used in file watcher processes that are child processes of the renderer
* `spdlog` should only be used from `electron-main` given recent changes

> Currently, the largest regression is the fact that child processes spawned from the workbench are not restarting on reloads

That is something to follow up and is unexpected. After all, when the workbench starts we always spawn new processes for file watcher and extension host because we do not support to reconnect to existing processes.

**Comment by rzhao271** [comment] 2021-04-08 18:18
> Are you saying there is a process swap on reloads ?

When `app.allowRendererProcessReuse` is `false`, the workbench process and all of its children are restarted with new process IDs.
When `app.allowRendererProcessReuse` is `true`, the workbench process continues to have the same process ID. All of its children are killed, but are currently not being restarted.

> Isn't `node-pty` only used in child processes from the shared process? My understanding is that there is one child process per terminal tab and only in there we use `node-pty`?

I'm still not sure how exactly the `.node` files correspond to the imports, and will look into it more today.

> After all, when the workbench starts we always spawn new processes for file watcher and extension host because we do not support to reconnect to existing processes.

I'm looking through the code right now to see what is happening. With the extension host, I can see some areas that might need to be changed to read `app.allowRendererProcessReuse` to determine whether or not to restart. For example, the signature for `_startExtensionHosts` in `src\vs\workbench\services\extensions\common\abstractExtensionService.ts` is `_startExtensionHosts(isInitialStart: boolean, initialActivationEvents: string[]): void`

**Comment by rzhao271** [comment] 2021-04-08 19:45
> Can you clarify how you found these dependencies, from my memory:
> 
> native-is-elevated is provided only from electron-main here
> vscode-windows-ca-certs is not a direct dependency anymore, but possibly a dependency of a module we depend on now (discussion in #120546)
> native-watchdog seems to be used only in the extension host process which is a child process of the renderer
> nsfw, fsevents are used in file watcher processes that are child processes of the renderer
> spdlog should only be used from electron-main given recent changes

Yep, some updated info and clarifications:

- As per the offline discussion, we can disregard `native-is-elevated` because it is loaded in `electron-main`. There's code that calls it indirectly from `electron-sandbox`, but `electron-sandbox` code has no node support, so we don't need to look further into this module.
- I confirmed `watchdog.node` is loaded only in the extension host process, not the workbench.
- `spdlog.node` is loaded in the extension host process still. Searching through imports, I'm not sure why that is the case. I'll look through https://github.com/microsoft/vscode/commit/291cc7c9d557c6053e18670cf8c802683b780c94.
- `windows_process_tree.node` and `conpty.node` are loaded in the ptyHost. All is well there.

Everything else agrees with your comment.

My current VS Code:
Version : 1.56.0-insider (user setup)
Commit : bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a
Date : 2021-04-07T12:30:14.880Z
Electron : 11.4.1
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

**Comment by deepak1556** [comment] 2021-04-08 21:34
Thanks for sharing the list, it is better. Can you update the above list with modules loaded in `electron-main`, also `nsfw` and `fsevents` are in `watcherService`.

Specifically the following modules are missing in the list

```
vscode-windows-registry
windows-foreground-love
windows-mutex
vscode-sqlite3
native-is-elevated
keytar
native-keymap
vscode-encrypt
```

**Comment by rzhao271** [comment] 2021-04-09 01:11
**Current progress**

It turns out the child processes are reloaded when turning on process reuse in the Electron 12 branch!
In other words, the PIDs of the shared process, ptyHost, and workbench stay the same, but the extension host and watcher service receive new PIDs (i.e. they are now new processes).

On the main branch, I was doing some tracing and it seemed that an `fs.readFile` call was not calling a callback. @deepak1556 points out that it is probably due to https://github.com/electron/electron/issues/22119.

**Looking over the checklist**
From https://github.com/microsoft/vscode/issues/120431#issuecomment-814420518

> Verify the native modules loaded in workbench and shared process are context aware, ignore modules loaded in other processes as they are not affected

We still have some context-aware modules such as `native-watchdog`. Does it matter anymore for this issue?

> Turn on the flag in master and identify regressions. This need not depend on Electron 12 adoption

On the main branch, reloads and workspace changes aren't working anymore. On the Electron 12 branch, reloads and workspace changes are working fine, though there might be unrelated regressions from the Electron 11->12 version bump.

> Ensure child processes spawned from workbench are restarted on reload.

See above.

**Question:** Does this issue now depend on Electron 12 being merged into Insiders?

**Comment by deepak1556** [comment] 2021-04-09 02:23
Minor correction the reason for failure on `main` branch is because https://github.com/electron/electron/pull/28175 has not been backported. 

> Does this issue now depend on Electron 12 being merged into Insiders?

Yeah given the above fix, we should experiment this with Electron 12.

Next steps,

1) Add a runtime argument `enable-process-reuse`
2) Set it to `true` with `electron-12.x.y` changes
3) Get feedback from insiders

**Comment by bpasero** [comment] 2021-04-09 06:10
The fact that issues such as https://github.com/electron/electron/issues/22119 exist actually make me worry that this flag is not tested/used in other apps. That is probably mainly because the flag is still not enabled by default so there is little to zero coverage.

> spdlog.node is loaded in the extension host process still

@rzhao271 Can you elaborate how that is an issue for renderer process reuse. Are we not only concerned about the renderer process but not child processes in general?

**Comment by rzhao271** [comment] 2021-04-09 15:33
> Are we not only concerned about the renderer process but not child processes in general?

I don't think it matters in this case, considering how the child process is being restarted anyway. I must have thought that we wanted `spdlog` to be in the main process only, independent of this issue.

Yesterday, I set up the vscode repo on my Mac and enabled process reuse from the main branch. It was still using Electron 11, but reloads seemed to work fine.

We already have E12 in, though, so we most likely don't have to add in OS-specific checks like "if windows, enable by default" now.

> Next steps after Electron 12 is merged to main, thoughts ?

Those steps look good to me. I'll add in the argument.

**Comment by bpasero** [comment] 2021-04-09 15:38
It looks like Electron has been running with renderer process reuse by default since Electron 9, so there is probably some coverage: https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-90

**Comment by bpasero** [comment] 2021-11-18 12:05
This seems to trigger https://github.com/electron/electron/issues/30153 in selfhost where suddenly colorization and any node.js IPC communication stops to work.

**Comment by bpasero** [comment] 2022-01-19 08:43
Closing this in favour of the general work item to update to Electron 16 where this will be the default.

**Closed** 2022-03-10 15:51 UTC
Labels: feature-request, on-testplan, workbench-electron, sandbox, electron-16-update

**Comment by rzhao271** [comment] 2022-03-21 18:45
I'm wondering where the testplan item for this issue is, and/or whether we need a new one? @bpasero

**Comment by bpasero** [comment] 2022-03-22 06:16
I think @deepak1556 covered that as part of the E16 and E17 test plan items previously.

**Comment by deepak1556** [comment] 2022-03-22 08:50
Yup its covered in previous milestone testing https://github.com/microsoft/vscode/issues/141268. This feature has already gotten plenty of coverage, does not require additional testing.
