### ISSUE TITLE
Allow to disable incremental search

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#65286] opened 2018-12-18 12:17 UTC
Like Atom, it'd be great if we could disable incremental search for buffer search (Find `Ctrl+F`). Right now, when you want to e.g. simply check number of matches within a file, without losing cursor position, it's not possible.

The **current behavior** is to automatically scroll to first match. **Desired behavior** is to postpone scroll-to-match until you hit `enter`/`find-next` for the first time, explicitly.

Couldn't find any related issue nor an existing option to disable this behavior.

EDIT: potentially duplicate/related issue https://github.com/Microsoft/vscode/issues/17563

**Comment by regexus** [comment] 2019-01-19 13:49
It would be really cool to have an option to leave the cursor where it is and change its position only on enter press during Find (Ctrl+F) operation. 

Imagine, we have a function **foo_function** at line 1 and some really huge function **bar_function** at line 1056. Let's also assume that **bar_function** contains no **foo**, but we don't know it yet and want to figure it out. So we press Ctrl+F and the nice highlighting system of VS Code would actually give us a hint, that no **foo** is there, but the cursor jumps back to the line 1. 

Here is a screenshot to illustrate the situation:
![search_cursor_position](https://user-images.githubusercontent.com/25210091/51427488-d3288c00-1bf8-11e9-876c-b38dbf5179b4.jpg)

Hope it helps other people to understand the issue faster and give it more votes.

**Comment by rebornix** [comment] 2019-08-07 18:22
/duplicate of https://github.com/microsoft/vscode/issues/60977

**Closed** 2019-08-07 18:22 UTC
Labels: *duplicate, editor-find, feature-request
