### ISSUE TITLE
[html] find/peek references to CSS 

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#10727] opened 2016-08-19 23:05 UTC
- VSCode Version: 1.5.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Add functionality similar to QuickEdit the Adobe Brackets for quick edits CSS file, or when I have a `style` tag in my HTML.

![2](https://cloud.githubusercontent.com/assets/19866231/17826492/a9938ed0-6647-11e6-80f3-049e449d974a.jpeg)

Simple explanation how it works: https://www.granneman.com/webdev/editors/brackets/quick-edit/

Add the functionality of this [extension](https://github.com/angular-ui/AngularJS-brackets) is the same as the QuickEdit but for directives, controllers and services on AngularJS in my JS or when one has a `script` tag in my HTML.

![1](https://cloud.githubusercontent.com/assets/19866231/17826462/71414e0a-6647-11e6-85fe-5f7ae90afac4.gif)

That would be a similar function with the [Peek](http://code.visualstudio.com/docs/editor/editingevolved#_peek) VSCode and [File Peek](https://marketplace.visualstudio.com/items?itemName=abierbaum.vscode-file-peek) extension, but for HTML.

**Comment by Learn-Digital-Audio** [comment] 2016-08-21 20:28
QuickEdit like in Brackets would be awesome!

**Comment by Tekbr** [comment] 2016-08-30 13:04
@aeschli not only css, javascript also. the first image is an example for CSS, and gif (second image) and an example of a for js directives. Also add "label js", please.

**Comment by Tekbr** [comment] 2017-12-01 12:30
-- Sorry for the English, I used Google Translator --

@aeschli Even if it is few votes .. the idea is to do this function tando for CSS when for AngularJS (javascript).

The old gif on AngularJS does not seem to be loading correctly, so I'm putting a new one showing.

![angularjs](https://user-images.githubusercontent.com/19866231/33482868-3bc7499e-d682-11e7-9668-b2eba81ab93e.gif)


Create a new one to then track the AngularJS (javascript). But I believe the process can be the same or even similar.

Or can we change the title one more time?

**Comment by aeschli** [comment] 2017-12-03 08:53
@Tekbr Let's keep this issue to enable finding a css rule from a HTML element. That enables opening a peek view, which is similar to what your screenshot shows. That fits in with our current features. 

For improved angular tooling, please file this against one of the Angular extensions. We don't plan to add Angular specific tooling to the HTML built-in support.

**Comment by aeschli** [comment] 2017-12-15 07:37
I mark this as duplicate of #27892 as that one has more votes.

**Closed by aeschli** 2017-12-15 07:37 UTC
Labels: css-less-sass, feature-request, html
