### ISSUE TITLE
Emmet css abbreviation not expanded in style attribute in html tag

### ISSUE THREAD

**Issue by meltifa** [Microsoft/vscode#29583] opened 2017-06-27 12:02 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|path-intellisense|christian-kohler|1.4.2|
|vscode-wxml|coderfee|0.1.9|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.7|
|EditorConfig|EditorConfig|0.9.3|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.14|
|vscode-scss|mrmlnc|0.6.2|
|vscode-stylefmt|mrmlnc|2.4.1|
|vetur|octref|0.8.6|
|vuehelper|oysun|0.1.0|
|vscode-html-scss|P-de-Jong|0.0.42|
|vscode-icons|robertohuertasm|7.10.1|
|stylelint|shinnn|0.25.0|;

---

Steps to Reproduce:

when i type `<div style="d:b` and press tab, Emmet does not expanded

**Comment by ramya-rao-a** [comment] 2017-06-29 22:28
Duplicate of #29066

Related to #29113

**Closed by ramya-rao-a** 2017-06-29 22:28 UTC
Labels: emmet, html
