### ISSUE TITLE
Installing extension behind a firewall

### ISSUE THREAD

**Issue by horst-naujoks** [Microsoft/vscode#215] opened 2015-11-19 13:30 UTC
I tried to install an extension. As I'm currently behind a corp firewall I wasn't successful after a first try with **ext install**. After configuring **"http.proxy": "http://xxx.yyy.zzz:1234/"** within my global **settings.json** I was successful in loading the list of extensions. But installing one fails with the error **connect ECONNREFUSED 191.238.172.191:443**. Yes, I also configured **https.proxy** correspondingly, but it seems that this value doesn't get honored.

**Comment by mponton** [comment] 2015-11-19 13:54
+1 Same here. I can check for updates but cannot "ext install" being proxy. I tried setting up the corresponding http_proxy and https_proxy environment variables too just in case, but no luck.

**Comment by Spinarooni** [comment] 2015-11-19 14:55
+1 Same here.  Also using Cntlm.

**Comment by joaomoreno** [comment] 2015-11-19 15:37
Duplicate of #69

**Closed by joaomoreno** 2015-11-19 15:37 UTC

**Comment by Tavriets** [comment] 2015-11-25 02:20
Seems like a certificate issue. If I try accessing the Extension gallery directly by its IP address as it is shown in VSCode (i.e. [https://191.238.172.191](https://191.238.172.191)), I'm getting the error: 
> *The security certificate presented by this site was issued fora different website's address.*

**Comment by bgolla** [comment] 2017-03-29 15:41
This worked for me.
Add proxy to File->Preferences->User settings
"http.proxy": "<your proxy>"
