### ISSUE TITLE
Salsa shows same symbol twice in outline

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2428] opened 2016-01-27 10:41 UTC
Testing #2218 

- no `jsconfig.json`

```javascript
exports.something = function() {
    return true;
}

function test() {
    
}
```

![salsa-duplicate-outline](https://cloud.githubusercontent.com/assets/5047891/12610977/cef3df08-c4ea-11e5-9337-a7d59190b1f2.gif)

**Comment by egamma** [comment] 2016-01-27 18:32
Duplicate of Microsoft/TypeScript#6566

**Closed by egamma** 2016-01-27 18:32 UTC
