### ISSUE TITLE
Wrong text pasted with multiple cursors

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#181913] opened 2023-05-09 16:42 UTC
In the following recording I copy `\ntwo`, select the first `\none`, hit <kbd>Cmd+D</kbd> to add another selection on the following `\none` and then hit <kbd>Cmd+V</kbd> to paste. I expected both `\none` selections to be replaced by two `\ntwo` snippets, but only the second one got replaced:

https://github.com/microsoft/vscode/assets/22350/e14b35aa-09ae-4b5a-82d8-e0966ab4fca8

**Comment by mjbvz** [comment] 2023-05-11 16:25
Reopening as the case with new lines is not a duplicate of #181486 and doesn't require `editor.pasteAs.enabled`. It actually appears to have been broken for a while

**Comment by joaomoreno** [comment] 2023-05-11 16:26
Repros at least all the way back to 1.75.1. Didn't test beyond that. Possibly not a regression at all.

**Comment by mjbvz** [comment] 2023-05-11 16:29
This bug appears to be in `_distributePasteToCursors`

https://github.com/microsoft/vscode/blob/3059063b805ed0ac10a6d9539e213386bfcfb852/src/vs/editor/common/cursor/cursorTypeOperations.ts#L125

If the copied text has the exact same number of lines as the number of cursors being pasted to, then the copied text is incorrectly treated as coming from multiple cursors instead of being duplicated for each cursor

I suspect this bug has been around for a while

**Comment by fellerts** [comment] 2024-05-30 15:10
I hit this today and believed it to be a bug, but as @mjbvz pointed out, it's a feature.

Set `"editor.multiCursorPaste": "full"` to make multi-cursor paste behave sanely. The default is `spread` which pastes a single line per cursor if the number of copied lines matches the cursor count.

**Comment by hediet** [comment] 2024-05-30 15:31
Closing, as there is a setting for this.
Let's create a new issue for a discussion which value should be the default, if someone wants to change it!

**Closed by hediet** 2024-05-30 15:31 UTC
Labels: bug, editor-core
