### ISSUE TITLE
Feature request: allow extension developers to add items to menu

### ISSUE THREAD

**Issue by iDev0urer** [Microsoft/vscode#4762] opened 2016-03-29 17:19 UTC
I'd be surprised if this hasn't come up before, but if it has I haven't been able to find it. It would be extremely nice if extensions had the ability to create menus, both on the top of the screen as well as adding items to the context menu. This could be controlled through a separate .json file or by adding a section to the `contributes` section of `package.json`.

**Comment by joaomoreno** [comment] 2016-04-01 07:08
cc @jrieken

**Comment by jrieken** [comment] 2016-04-01 07:25
Yes, menu bar and action bar contributions we shall have

**Comment by Thaina** [comment] 2016-04-18 08:00
+1

**Comment by Thaina** [comment] 2016-04-18 08:01
Should we merge #3192 into this issue? It should be done at the same time both menu and context menu

**Comment by jrieken** [comment] 2016-04-18 12:21
makes sense. Closing as dupe of #3192

**Closed** 2016-04-29 10:14 UTC
Labels: api, duplicate, extensions, feature-request
