### ISSUE TITLE
C and C++ syntax highlight grammar doesn't support multiline comment and asterisk

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#68784] opened 2019-02-15 14:11 UTC
- VSCode Version: 1.31.1
- OS Version: linux

Steps to Reproduce:

1. Insert:
```c
bool aaaa(const char */* comment */) { return true; }
```
Result:
![image](https://user-images.githubusercontent.com/7345761/52861792-a0fd4200-3144-11e9-98f9-8462ac6f8d10.png)

No matter if you have any c/c++ extensions installed

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment] 2019-02-18 09:28
We're going to try moving to a new C grammar soon. Once the move is done I'll see if this still reproduces.

**Comment by alexr00** [comment] 2019-03-04 10:20
Looks like this one is still occuring moving to jeff-hykin/cpp-textmate-grammar.

**Comment by alexr00** [comment] 2019-03-04 10:21
This issue was moved to jeff-hykin/cpp-textmate-grammar#11

**Closed by alexr00** 2019-03-04 10:21 UTC
Labels: grammar

**Comment by sean-mcmanus** [comment] 2019-03-15 00:39
@alexr00 What's the schedule for pulling in the latest fixes into Insiders?

**Comment by alexr00** [comment] 2019-04-26 15:18
I updated again from  jeff-hykin/cpp-textmate-grammar this week! You can see all the changes in Insiders.
