### ISSUE TITLE
Integrated Terminal only available sporadically

### ISSUE THREAD

**Issue by ThomasLBonner** [Microsoft/vscode#43992] opened 2018-02-19 22:52 UTC
### Issue Type
Bug

### Description

The integrated terminal becomes unresposnive and nothing can be edited. All text disappears and new text cannot be added. Closing the editor and reopeninbg sometimes fixes the problem, other times the problem persists. 

I have seen reports of similar behavior on Windows systems, but this is occuring on a Mac running OS 12.6.

This is extremely frustrating.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3520  @ 2.67GHz (8 x 2660)|
|Load (avg)|3, 5, 6|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Users/Ironsides/Downloads/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
Angular1|joh|0.2.0
vscode-language-babel|mgm|0.0.12
prettier-standard-vscode|num|0.3.0
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by Tyriar** [comment] 2018-02-20 17:57
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/42999.

**Closed by Tyriar** 2018-02-20 17:57 UTC
Labels: integrated-terminal
