### ISSUE TITLE
Internal terminal can not show "under-line( _ )" on screen

### ISSUE THREAD

**Issue by hcnhcn012** [Microsoft/vscode#38640] opened 2017-11-17 16:23 UTC
- VSCode Version: 1.18.1
- OS Version: Fedora 27 and Fedora 26

Steps to Reproduce:

![screenshot from 2017-11-18 00-22-37](https://user-images.githubusercontent.com/19546977/32957431-a53551dc-cbf6-11e7-8972-248e2ce2c676.png)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-17 17:58
Duplicate of #35901

Use `terminal.integrated.fontSize": 13` as a workaround

**Comment by hcnhcn012** [comment] 2017-11-18 06:29
@maxibanki Thanks! It has worked

**Closed** 2017-11-18 06:29 UTC
Labels: integrated-terminal, new release
