### ISSUE TITLE
Markdown preview: don't show editor if (1) it's hidden (2) user clicks a link to another local markdown file

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#38100] opened 2017-11-11 03:31 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.11-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
contextualduplicate|laf|0.2.0
MDTools|sea|1.0.1

---

Steps to Reproduce:

1. Open a markdown file. Open preview and close editor.
2. Click a link which points to a local markdown file.
3. VSCode opens new preview _plus_ editor for that file.

Reproduces without extensions: Yes

Would you please add handlers to check that for a markdown file:

- If preview is open but editor is closed.
- And the user clicks a link pointing to a local markdown file.

Then VSCode only opens new preview of that file, and not editor?

Additional features:

- Click: open in same tab (replace current file).
- Ctrl+Click: open in new tab.

Thank you,

**Comment by mjbvz** [comment] 2017-11-13 21:23
Duplicate of #19339

**Closed by mjbvz** 2017-11-13 21:23 UTC
Labels: duplicate, markdown
