### ISSUE TITLE
Bug when processing the afterthought of a for loop in a macro

### ISSUE THREAD

**Issue by targetnull** [Microsoft/vscode#21621] opened 2017-03-01 11:51 UTC
- VSCode Version: 1.9.1
- OS Version: windows 10 and ubuntu 16.04.2

Steps to Reproduce:

1. open a C file, e.g. `test.c`
2. paste the following code
```
#define problem(aa) \
    for(aa; aa; \
    add(aa))

int cc(int dd)
{
    //whatever down the macro is colored blue
}
```
As you can see, whatever down that macro is colored blue because they are incorrectly recognized as part of the macro.

3. if I replace the afterthough `add(a)` with `i += 2` or `++i`, it could be recognized normally. I think it is because of the rules you use to mark the end of a for loop.

I tried to see if I could fix it myself and send a pull request, but you'are using node.js which I'm not familiar, and the code base seems to be a little huge. It is beyond my ability, so all I can do is to report it here.

**Comment by aeschli** [comment] 2017-03-01 16:06
duplicate of https://github.com/atom/language-c/issues/160

**Closed by aeschli** 2017-03-01 16:06 UTC
