### ISSUE TITLE
Markdown unordered list and word wrap

### ISSUE THREAD

**Issue by nomad101** [microsoft/vscode#102999] opened 2020-07-21 08:43 UTC
When text wraps on an unordered list in the Editor, the second line of wrapped text is not aligned with the indented word on the first line of the list. (In preview view it is aligned). 

The readability of list items in the Editor could be improved with this enhancement. More writers are using vscode markdown, therefore more readable lists would be beneficial. 

Thanks.

**Comment by mjbvz** [comment] 2020-07-21 16:00
Please share example markdown (as text)

/needsMoreInfo

**Comment by nomad101** [comment] 2020-07-22 13:43
At the moment, if you have a list in markdown and the text wraps, the words on the next line don't left align. For example, ideally in editor view, the new line words ('particular', 'if', 'full') would align with the word 'Civility' (as you would see in preview view).

![image](https://user-images.githubusercontent.com/27806124/88183522-782a8780-cc29-11ea-84b0-af0537eca6fd.png)

It would be great if this was possible in the editor view. It will make reading lists easier on the eye (and especially for long lists).

**Comment by mjbvz** [comment] 2020-07-22 23:19
Thanks. Duplicate of https://github.com/microsoft/vscode/issues/94674 which we don't plan on addressing in the short term

**Closed by mjbvz** 2020-07-22 23:19 UTC
Labels: needs more info
