### ISSUE TITLE
Migrate extension samples to eslint

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#97476] opened 2020-05-11 08:43 UTC
The following examples are still using tslint and should be migrated to use eslint. 

This is the guide https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

- [ ] i18n-sample
- [ ] helloworld-sample
- [ ] fsconsumer-sample
- [ ] webpack-sample
- [ ] lsp-embedded-language-service
- [ ] lsp-embedded-request-forwarding
- [ ] basic-multi-root-sample
- [ ] lsp-log-streaming-sample
- [ ] semantic-tokens-sample
- [ ] configuration-sample
- [ ] nodefs-provider-sample
- [ ] extension-terminal-sample
- [ ] webview-sample
- [ ] comment-sample
- [ ] decorator-sample
- [ ] proposed-api-sample
- [ ] tree-view-sample
- [ ] progress-sample
- [ ] quickinput-sample
- [ ] call-hierarchy-sample
- [ ] custom-editor-sample
- [ ] .base-sample
- [ ] completions-sample
- [ ] helloworld-test-sample
- [ ] code-actions-sample
- [ ] document-editing-sample
- [ ] diagnostic-related-information-sample
- [ ] task-provider-sample
- [ ] fsprovider-sample
- [ ] source-control-sample
- [ ] terminal-sample
- [ ] lsp-multi-server-sample
- [ ] vim-sample
- [ ] contentprovider-sample

**Comment by jrieken** [comment] 2020-05-26 12:30
related, duplicate of https://github.com/microsoft/vscode-extension-samples/issues/266

**Comment by jrieken** [comment] 2020-06-04 12:10
This is done. Thanks @mjbvz

**Closed by jrieken** 2020-06-04 12:10 UTC
Labels: plan-item
