### ISSUE TITLE
Pressing `esc` with a selection, should clear the selection but keep the selected item

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119663] opened 2021-03-23 17:57 UTC
Testing #119118

Currently, pressing `esc` with a selection, clear it (👍) but it also resets the selected item so it looks like there is no selected item

**Comment by rebornix** [comment] 2021-03-24 01:01
Duplicate of https://github.com/microsoft/vscode/issues/118835 , which @joaomoreno already puts in April milestone.

**Closed by rebornix** 2021-03-24 01:01 UTC
