### ISSUE TITLE
Allow QuickPick list items be formatted with HTML

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10886] opened 2016-08-24 11:39 UTC
Just as proposal:
Allow Extension QuickPick list items be formatted with HTML, this would allow extension creators:
1) Have some additional "hidden" information using tags
2) Style selection options to make it more convenient for user

So just need to treat quickPick list items as HTML, not raw text.

**Comment by jrieken** [comment] 2016-08-25 12:48
closing as dupe of #1833

**Closed by jrieken** 2016-08-25 12:48 UTC
Labels: duplicate
