### ISSUE TITLE
Save Proxy Credentials

### ISSUE THREAD

**Issue by akcorp2003** [microsoft/vscode#32566] opened 2017-08-15 15:09 UTC
- VSCode Version: 1.15
- OS Version: MacOS Sierra 10.12.6

It would be nice if Code could save my proxy credentials for a certain proxy address. It is a bit intrusive having to enter my credentials every time I hop onto my corporate proxy.

**Comment by naprelsky** [comment] 2017-11-10 07:11
How about this issue? I was tired of proxy authentication popup after every restart. Perhaps there is a solution?

**Comment by jackpot1136** [comment] 2017-11-10 07:14
They are going after our storage pull the keys

**Comment by benjaminfontaine** [comment] 2017-11-29 08:34
I concur with the previous comments, it's quite bothersome to reenter the credentials everytime I'm launching my IDE.

**Comment by CHQ-synaix** [comment] 2018-02-13 07:39
Is there anything new about this topic? I love vscode, but this popup hurts every morning :(

**Comment by vrbsky** [comment] 2018-02-16 12:12
Same here! I would love not having to do a manual login every time vscode starts up.

**Comment by albertotn** [comment] 2018-05-09 07:36
Same for me, please add save crendials ! I've found there are other issues, like #44041

**Comment by 7654098** [comment] 2018-12-07 12:07
+1

**Comment by mayes21** [comment] 2018-12-20 14:56
same problem for me !

**Comment by rossan518** [comment] 2019-01-12 09:42
Same for me. I hope this problem will be solved soon.

**Comment by ruchern** [comment] 2019-02-20 09:26
Any updates on this?

**Comment by Koushikphy** [comment] 2019-03-06 14:28
It's shocking to see, this issue was opened nearly one and half an year ago, and still no fix, while vs code is launching new and complicated feature every month. 
Its really annoying to put the credential several times, every day and sometimes extensions (like wakatime) doesn't work properly for this.

**Comment by miicah** [comment] 2019-03-06 23:52
Just started using VSCode at work and it's really annoying having to type creds in each time. Even a "save credentials" tickbox would reduce some of the annoyance.

**Comment by zicklag** [comment] 2019-03-11 01:54
This is the largest UX pain point for me in a nearly perfect and constantly improving tool.

**Comment by FerhatAkgun** [comment] 2019-03-20 10:28
This is very annoying.

Additional info:
In my case the window shows up twice. Any idea why this happens?
I am pretty sure that I enter the credentials correctly both times.

**Comment by Koushikphy** [comment] 2019-03-20 10:32
@FerhatAkgun this is because of the extensions.

**Comment by willemavjc** [comment] 2019-04-04 12:52
Nearly 2 years ago for a (simple?) useful feature. *dying*

**Comment by cytar** [comment] 2019-04-08 05:49
Hi,
i got the same problem. I disabled all extensions: same problem.
In my case, it was due to the fact that their is 2 proxy settings: 1st is user specific, the other one is workspace specific. And i haven't fill the second one.
In my case, this solved the problem when i filled up both proxy settings with the user/password syntax: http://user:password@proxy:proxy_port

![image](https://user-images.githubusercontent.com/29857786/55701180-7906be00-59d2-11e9-9834-deb6d35acb76.png)
![image](https://user-images.githubusercontent.com/29857786/55701149-570d3b80-59d2-11e9-9995-02ab79310767.png)

**Comment by Koushikphy** [comment] 2019-04-08 12:59
I tried that but the proxy box is still popping up

**Comment by Benj1907** [comment] 2019-05-12 08:11
+1

**Comment by Shinigami92** [comment] 2019-05-12 08:20
I do not need this change any more because I've changed my employer and they use a transparent proxy ... lol

I have been following this ticket for a year now...

**Comment by solarjoe** [comment] 2019-05-15 06:18
Same issue for me, the pop-up appers twice (once for the Extensions I guess).

Windows 10, 64-bit
VS Code 1.33.1 (user setup)

I tried lots of things in the GUI settings and settings.json for User Settings and Workspace Settings, also both as mentioned in https://github.com/microsoft/vscode/issues/32566#issuecomment-480692463

```
    "http.proxy": "http://user:password@proxy-ip:port" (with password, without, username only, ...)
    "http.proxyStrictSSL": false or true
    "http.proxySupport": "on (override, off, ...)
```

The environment variables are set (lowercase) and work fine for other programs

```
https_proxy=http://user:password@proxy-ip:port
http_proxy=http://user:password@proxy-ip:port
```

- What is the expected behaviour? Is VS Code always supposed to ask for the password even if it is stored in the URL in the settings or the environment variables?
- Could there be a "store password" in this pop-up which puts it to the settings.json if authentication works?

**Comment by howar31** [comment] 2019-06-26 03:32
I have a different issue that my popup never show up even I'm behind a proxy which need authentication.  This makes my VSCode not connected to network and I don't know how to fix this :/

**Comment by tady159** [comment] 2019-07-18 14:16
I have this issue too. It's really annoying to type in my proxy credentials every time I open VSCode.

**Comment by tixuoty** [comment] 2019-09-10 10:51
I am living the pain also.....starting to think about switching back to Atom.

**Comment by solarjoe** [comment] 2019-09-11 08:31
I found this issue https://github.com/Microsoft/vscode/issues/38888 

They mention that supplying the proxy parameters on the command line works, even if setting it in VS Code doesn't. And this works for me. Still not beautiful, as the password is clear text, but for the other options (environment variables, settings.json) this would also be the case.

So I added this to my desktop shortcut and the two popups are gone:

`"C:\Path\To\Code.exe" --proxy-server=http://user:password@123.123.123.123:8080`

**Comment by koutheir** [comment] 2019-09-11 08:52
Supplying `--proxy-server=` gives the following errors:
- Menu `Help/Check for Updates...`: `net::ERR_NO_SUPPORTED_PROXIES`.
- Check for extension updates: `An unknown error occurred. Please consult the log for more details.`.
So, the pop up window is no more there, but the setting just doesn't work.

**Comment by koutheir** [comment] 2019-09-11 09:13
Specifying `--proxy-server=` makes the pop up disappear, but the IDE cannot actually connect to the Internet. Trying to check for updates for the IDE or the extensions fails either with time out, or with `net::ERR_NO_SUPPORTED_PROXIES`.

**Comment by solarjoe** [comment] 2019-09-11 16:26
Yes, that's correct. Argh, it can't be that difficult.

Is there a way to see which proxy settings are being used when VCS is connecting somewhere? I checked the developer tools but they only state the errors.

**Comment by solarjoe** [comment] 2019-09-19 13:46
@zicklag, I tried your Gist and it works like charm! Thanks!

**Comment by amir-alic** [comment] 2019-09-19 14:36
I tried the Gist (on Windows 10, starting manually "node index.js") and unfortunately does not work for me => still getting the annoying VSCode Proxy dialog.

**Comment by zicklag** [comment] 2019-09-19 17:17
@amir-alic Did you set your proxy settings in VSCode to `http://localhost:3128`. That will make VSCode use the local proxy that you started when you ran `node index.js`, which won't ask for authentication.

**Comment by solarjoe** [comment] 2019-09-19 17:34
You can enter the settings in VSCode, or if you have problems with other software you can also set the user environment variables `http_proxy` and `https_proxy` both to `http://localhost:3128` or `https://localhost:3128` which VSCode will find and use.

**Comment by zicklag** [comment] 2019-10-02 00:32
I just found a **much** easier "proxy proxy" to use instead of the NodeJS one from my Gist above. You can use [glider](https://github.com/nadoo/glider). Just run it like this:

```
glider -listen http://localhost:3128 -forward http://user:pass@123.456.789.1:1234
```

That is way nicer than using Node and writing a script and it also fixes a problem with my previous suggestion that I noticed recently: the NodeJS proxy will listen on all IP addresses which means that anybody on your local network that knows the port you are hosting the server on will be able to connect to your computer on that port to make proxied requests with your credentials. Probably not good.

Glider also doesn't require installing NodeJS or using npm to install dependencies. It is just a single downloadable binary.

**Comment by rahmaevao** [comment] 2020-08-26 12:02
> Actually, you could probably easily make a VSCode plugin that implements that workaround without having to modify VSCode core.

Brother, write this extension yourself.
I think you can handle it.

**Comment by quyleanh** [comment] 2020-09-18 07:48
If we cannot save proxy credential, could we have a better UI for the proxy dialog?
A better UI likes something has unify/sync theme/style with the rest UI.
If we have this, the pain of typing credential every morning will much reduce.

**Comment by bpasero** [comment] 2020-10-27 07:10
With https://github.com/microsoft/vscode/issues/106489 landing in October there is a new setting `"window.enableExperimentalProxyLoginDialog": true` to enable a new login experience that will show a dialog in the active window:

![image](https://user-images.githubusercontent.com/900690/97268202-c56f5400-182b-11eb-998c-e657f5589770.png)

This experience allows to remember the credentials and thus not ask again.

I would appreciate if people could try this from our insider build today and give some feedback how it goes. We would like to make this experience the new default beginning with our release end of the year if it works fine.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by zicklag** [comment] 2020-10-27 14:52
Just tested it and it works as advertised!

Thank you for putting effort into this. As an issue with 51 :+1:  and tons of other users who probably never bothered to jump on GitHub and search for an issue, I think this will really help our a bunch of people!

**Comment by bpasero** [comment] 2020-10-27 15:25
Closing, as this shipped and is being tested during the week via https://github.com/microsoft/vscode/issues/109377. Will address issues as we see them.

**Closed by bpasero** 2020-10-27 15:25 UTC
Labels: feature-request, on-testplan, proxy

**Comment by guilhermetod** [comment] 2020-11-06 12:49
Just as a feedback, I just testes the released version and everything seems to be working pretty fine. Thanks to everyone involved in this!
