### ISSUE TITLE
Incorrect icons rendering

### ISSUE THREAD

**Issue by mykolarubets-tomtom** [microsoft/vscode#209801] opened 2024-04-08 06:56 UTC
Type: <b>Bug</b>

On Ubuntu 22.04 with environment variable FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0" sidebar icons are incorrect rendered:
![vscode_icorrect_icon_rendering](https://github.com/microsoft/vscode/assets/132565323/ea65956d-a3be-47b7-a796-c4011b0ddd08)

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 6.5.0-26-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2799)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|8, 8, 6|
|Memory (System)|31.03GB (19.43GB free)|
|Process Argv|--no-sandbox develop/tmp --crash-reporter-id 62a7d3c4-c0ac-4093-b554-5765e2a2a50b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-mdx-checker|awx|0.1.3
thrift|cdu|0.0.1
vscode-eslint|dba|2.4.4
FreeMarker|dco|0.0.9
githistory|don|0.6.20
gitlens|eam|14.9.0
json-tools|eri|1.0.2
copilot|Git|1.178.0
copilot-chat|Git|0.14.0
better-cpp-syntax|jef|1.17.2
vscode-clangd|llv|0.1.28
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.4.0
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
remote-explorer|ms-|0.4.3
vs-keybindings|ms-|0.2.1
vscode-xml|red|0.26.1
code-spell-checker|str|3.0.1
cmantic|tde|0.9.0
cmake|twx|0.0.17
vscode-mdx|uni|1.8.3
vscode-lldb|vad|1.10.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by bpasero** [comment] 2024-04-08 15:24
You could see if it reproduces in Chrome on https://insiders.vscode.dev/

**Comment by mykolarubets-tomtom** [comment] 2024-04-09 11:10
> You could see if it reproduces in Chrome on https://insiders.vscode.dev/

Yes, there is a problem. Most likely, this is due to the fact that the icons are also text, and not vector graphics or images, since I see similar problems throughout the whole system.
The main idea was to finally make fonts in Ubuntu more readable https://www.reddit.com/r/linux_gaming/comments/16lwgnj/is_it_possible_to_improve_font_rendering_on_linux/?rdt=34042

**Comment by deepak1556** [comment] 2024-12-17 11:33
Closing per above comment given the issue is not isolated to the desktop application.

**Closed by deepak1556** 2024-12-17 11:33 UTC
