### ISSUE TITLE
Only Render Whitespace on Selection

### ISSUE THREAD

**Issue by tills13** [Microsoft/vscode#7825] opened 2016-06-17 16:29 UTC
- VSCode Version: any
- OS Version: any

In Sublime, there's an option to only show whitespace when text is highlighted. 

<img width="363" alt="screenshot 2016-06-17 09 19 42" src="https://cloud.githubusercontent.com/assets/1269421/16157344/fb07502e-346c-11e6-990a-c7ffa44d511f.png">

In my opinion, this helps with code readability, while still allowing you to see whitespace if you need to. Code currently only supports whitespace on/whitespace off.

It might also help to tone down the weight of the whitespace indicator. 

![screenshot 2016-06-17 09 30 03](https://cloud.githubusercontent.com/assets/1269421/16157609/1a5d3f00-346e-11e6-960c-041317d26fa4.png)

**Comment by glen-84** [comment] 2016-06-18 14:28
Duplicate of #1477.

**Comment by alexandrudima** [comment] 2016-06-29 14:21
Let's track in #1477

**Closed by alexandrudima** 2016-06-29 14:21 UTC
Labels: editor, feature-request
