### ISSUE TITLE
Add a default keybooard shortcut for toggling the integrated terminal

### ISSUE THREAD

**Issue by giefferre** [Microsoft/vscode#24086] opened 2017-04-06 15:45 UTC
The keyboard shortcut for the integrated terminal is disabled by default, and now users need to manually re-enable it creating a key binding.

- VSCode Version: 1.11.0 (1.11.0) 2017-04-05T20:49:18.310Z
- OS Version: macOS 10.12.4 (16E195)

Steps to Reproduce:

1. Open VSCode
2. Press `^` + `\` (or correspective keys according to [the macOS keyboard shortcuts map](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf))

**Comment by railto** [comment] 2017-04-06 16:20
It appears that the cause is actually VSCode reading the kaymapping wrong.  When I went to remap the function it was showing as ctrl + ` which is what it always has been, however when I attempted to update this and used that key combo it showed up as ctrl + § instead. 

I've confirmed the mapping on my mac is correct for the keyboard that I'm using.

**Comment by giefferre** [comment] 2017-04-06 16:22
In my case the binding were not present at all (anymore) and I eventually had to manually set it again.

**Comment by chrmarti** [comment] 2017-04-06 18:26
Which keyboard layout are you using?

**Comment by railto** [comment] 2017-04-06 18:51
The irish layout for apple keyboard on macOS 10.12.4

**Comment by alexandrudima** [comment] 2017-04-06 20:54
@railto What do you mean VS Code reads the keymapping wrong? Here is an in-depth explanation of what we are doing -- https://github.com/Microsoft/vscode/wiki/Keybindings
We do not ship with keyboard layout specific default keybindings, e.g. we don't ship with keybindings optimized for the Irish keyboard layout. It is therefore possible that we lack some default keybindings or that they are unfortunate/badly placed. This can be upvoted in #1240

@giefferre That PDF is valid for a US standard English layout. For your current keyboard layout, the best way to find out default/your current keyboard shortcuts is to use the `F1` list or Preferences > Keyboard Shortcuts.

Please let me know if you suspect there's anything else going wrong.

**Comment by jsynowiec** [comment] 2017-04-07 05:47
Related to #23896 

For me upgrading to 1.11.1 disables the <kbd>⌃</kbd>+<kbd>`</kbd> shortcut that should be assigned to **Toggle Terminal** command. Executing this command from the Command Palette works as supposed.

<img width="615" alt="screenshot 2017-04-07 07 45 51" src="https://cloud.githubusercontent.com/assets/1029142/24787067/538a369a-1b66-11e7-8ad5-3c317f13ae4c.png">

**Comment by giefferre** [comment] 2017-04-07 08:05
@alexandrudima this is what appears to be the default keybindings for the integrated terminal.

<img width="899" alt="schermata 2017-04-07 alle 09 59 12" src="https://cloud.githubusercontent.com/assets/1171932/24791164/65c531f8-1b79-11e7-83ab-a9734b9f5775.png">

As @jsynowiec points out, *it worked* in 1.10.2 but stopped working in version 1.11.1.
Of course, when I run the 'toggle terminal' command from the Command Palette it works as expected.

<img width="617" alt="schermata 2017-04-07 alle 10 02 33" src="https://cloud.githubusercontent.com/assets/1171932/24791208/959ea404-1b79-11e7-95cb-f1d9812e2fd8.png">

As you can see I use the italian layout.

**Comment by jsynowiec** [comment] 2017-04-07 09:00
In #24186 @lordchancellor pointed out that <kbd>`</kbd> is switched with <kbd>§</kbd> on Mac so this might indicate a problem with keymapping?

**Comment by jkzing** [comment] 2017-04-07 10:10
Same issue happen to me. I tried to set `Toggle Integrated Terminal` keymap shortcut to
<kbd>ctrl</kbd> + <kbd>`</kbd> 

<kbd>shift</kbd> + <kbd>`</kbd> 

<kbd>alt</kbd> + <kbd>`</kbd> .

 And all of them are worked as expect only excepted <kbd>cmd</kbd> + <kbd>`</kbd>.

Is it because of that <kbd>cmd</kbd> + <kbd>`</kbd> is a reserved keybinding under MacOS? It  is used to toggle opened windows of an App.

**Comment by intellix** [comment] 2017-04-08 12:27
Also found that this broke in the latest update. I was using: <kbd>ctrl</kbd> + <kbd>`</kbd> with Apple British Keyboard layout and it stopped working.

It has the <kbd>`</kbd> and <kbd>§</kbd> keys mixed up as I see when re-binding that shortcut.

![](http://kb.parallels.com/Attachments/19485/Images/wireless-british.jpg)

**Comment by railto** [comment] 2017-04-08 15:16
@alexandrudima, the reply from @intellix explains exactly the issue I was trying to explain.

**Comment by alexandrudima** [comment] 2017-04-10 16:09
Thank you all!

It is difficult to juggle so many different keyboard layouts in a single issue, here is what I suggest we do:

@giefferre OP
You appear to be using an Italian keyboard layout. From https://support.apple.com/en-ca/HT201794 I will assume it looks like this:
![image](https://cloud.githubusercontent.com/assets/5047891/24870834/e8cdf12a-1e17-11e7-832c-36527feda6a1.png)

From the picture it appears that there is no way to produce `` ` `` on an Italian keyboard layout. That's why the terminal is not bound out of the box under the Italian keyboard layout. You can upvote that we ship with keyboard layout specific default keybindings in #1240

---

@jsynowiec @intellix @railto It appears you are using the British keyboard layout and we have some issue with `[Backslash]` and `[IntlBackslash]` where they are somehow swapped from a label point of view. Let's track in #24153 which clearly states it is about the British keyboard layout.

---

@jkzing It appears you cannot bind ``cmd + ` `` due to the OS eating up that keypress. I am sorry, if the keypress doesn't reach us, there is nothing we can do.

**Closed by alexandrudima** 2017-04-10 16:09 UTC
Labels: keybindings, keyboard-layout, mac, needs more info

**Comment by giefferre** [comment] 2017-04-10 16:12
Thanks @alexandrudima for your feedback.

The keyboard layout you posted is the right one, I used to toggle the integrated terminal using the `CTRL`+`> <` keys.

Upvoted the bug you linked.
