### ISSUE TITLE
Allow keybindings for moving through symbols in a file

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#126927] opened 2021-06-22 17:21 UTC
VSCode's code navigation would really help with being able to move between symbols. Other IDE's have this built in, Sublime, Vim, IntelliJ etc.
Keyboard users need to do some tough manoeuvring to get to a function below or a class (either GoToLine which is a few steps, or opening up symbols table). Having the ability to cycle through all symbols in a file would really help.

## Risks
The main risk is adding bloat, which I understand. However in this case we're not adding a new feature. You can already cycle through symbols using Cmd+Shift+O (MacOS), this feature request is just allowing users to have this as a keybinding.

## Implementations
https://marketplace.visualstudio.com/items?itemName=mishkinf.goto-next-previous-member exists although its no longer maintained. There is the argument it could be an extension but a feature this low level I'd expect to be baked in (as it is in other IDEs). Also there shouldn't be much extra work here, as you can already do this in the UI (as mentioned above).

I've set the above to ctrl+shift+{up, down} (as these seems to be free)

## Similar issues
This is a continuation of https://github.com/microsoft/vscode/issues/46153 which was abandoned because the approach was not suitable.

**Comment by jrieken** [comment] 2021-06-23 06:42
/duplicate of https://github.com/microsoft/vscode/issues/46153#issuecomment-866181200

**Closed** 2021-06-23 06:43 UTC
Labels: *duplicate
