### ISSUE TITLE
how to modify workbench font family

### ISSUE THREAD

**Issue by scott8013** [microsoft/vscode#139665] opened 2021-12-23 03:24 UTC
Issue Type: <b>Feature Request</b>

how to modify workbench font family

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

**Comment by septsea** [comment] 2021-12-23 03:37
**Workbench** font family? Consider the extension `Customize UI`:

https://github.com/iocave/customize-ui

May it helps you.

**Comment by IllusionMH** [comment] 2021-12-23 05:27
/duplicate of #519

See that thread for suggestions, but it's mostly about extension recommended by @septsea above.

**Closed** 2021-12-23 05:28 UTC
Labels: *duplicate, triage-needed
