### ISSUE TITLE
Flickering in terminal following a switch to a new Macbook Pro

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#52378] opened 2018-06-20 03:08 UTC
Issue Type: <b>Performance Issue</b>

I recently upgraded from an old  macbook pro to a new macbook pro.  I am now noticing flickering in the ui for the first time (particularly around the terminal, and animations in the release notes).

The new Macbook has a higher resolution screen -- one cause that I considered (without evidence) is that it might be related to scaling in some web content.

If needed, I can get the old computer to also provide system info regarding the old host.

Please let me know how I can help debug.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (test.sh (Working Tree) — clarifai)
|    Folder (clarifai): more than 21104 files
|      File types: go(9059) py(2359) jsonnet(1143) txt(878) golden(736)
|                  sh(521) md(497) a(432) proto(402) json(334)
|      Conf files: makefile(192) settings.json(2) gulp.js(2) package.json(2)
|                  launch.json(1) tasks.json(1) sln(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.27
ActiveFileInStatusBar|Ros|1.0.3
better-toml|bun|0.3.2
solargraph|cas|0.17.4
gitignore|cod|0.5.0
githistory|don|0.4.1
gitlens|eam|8.4.1
jsonnet|hep|0.1.0
git-tree-compare|let|1.2.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.83
Ruby|reb|0.18.0
java|red|0.27.0
vscode-open-in-github|sys|1.7.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
vscode-proto3|zxh|0.2.1

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment] 2018-06-20 07:50
I notice that GPU acceleration is disabled, what version of macOS are you on?

**Comment by josh-tepper** [comment] 2018-06-20 15:27
Version 10.13.4

![screen shot 2018-06-20 at 11 27 20 am](https://user-images.githubusercontent.com/20231989/41668263-f2f47ac2-747c-11e8-98ee-b931ee97415d.png)

**Comment by Tyriar** [comment] 2018-06-20 19:56
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/48043

**Closed by Tyriar** 2018-06-20 19:56 UTC
Labels: needs more info

**Comment by josh-tepper** [comment] 2018-06-20 20:19
Three questions if you have a chance -- if you happen to know offhand:
1. Is the gpu blacklist is maintained by electron? 
2. When vscode moves to electron 2, is it possible that this be resolved?
3. Will that depend on Mac OS addressing the issue first?

**Comment by josh-tepper** [comment] 2018-06-20 20:28
Actually -- I tried to again generate a bug report and it gives me different values from what I see in the command line.  Copied and pasted from the bug report (which did not actually submit):
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

**Comment by Tyriar** [comment] 2018-06-20 20:59
@RMacfarlane any ideas on why this would be reporting different values?

> Is that because the gpu is only sometimes disabled

@josh-tepper I would expect the values to always be the same, especially in a single session (the "main" process defines this, cmd+q will fully close the main process).

**Comment by josh-tepper** [comment] 2018-06-20 21:29
Just reproduced after typing cmd+q and restarting

**Comment by RMacfarlane** [comment] 2018-06-20 21:50
Hmm, they both make a call to `app.getGPUFeatureStatus()`. My only thought for why they would be different is that in the `code --status` case when another process is launched, I might be making the call in the process that just launched instead of the original code instance. But even then, I'm not sure what would cause them to be different across instances

**Comment by josh-tepper** [comment] 2018-06-20 22:48
Just to be clear -- since I'm not sure if I'm invoking this correctly:

Starting from no running instances of VSCode, I execute
```
$ code <dir>
```
VSCode starts; then, in a separate invocation:
```
$ code --status
```
Then in the (only) vscode window, I click on the smiley face in the status bar to generate the bug report.

**Comment by RMacfarlane** [comment] 2018-06-20 23:06
@josh-tepper Yeah, that's correct, thanks for the additional details!

I just created another issue to track this: https://github.com/Microsoft/vscode/issues/52520
