### ISSUE TITLE
Copy line no longer pastes correctly on Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#181550] opened 2023-05-04 17:00 UTC
Have a document with your cursor placed at `|`

```
hello w|orld
```

Ctrl+c and ctrl+v. I would expect to get two lines of `hello world`, but instead I get

```
hello whello world
orld
```

**Comment by mjbvz** [comment] 2023-05-04 17:17
Duplicate of #181489

**Closed by mjbvz** 2023-05-04 17:17 UTC
