### ISSUE TITLE
Command Palette should return focus to terminal pane

### ISSUE THREAD

**Issue by jheiv** [microsoft/vscode#92076] opened 2020-03-05 11:31 UTC
- VSCode Version: 1.43.0-insider
- OS Version: Win 10 (10.0.18362 Build 18362)

Steps to Reproduce:

1. Open an integerated terminal (and give it focus)
2. Open the Command Palette with your keyboard shortcut
3. Select something (e.g. Clear Terminal) or even hit escape to close the Command Palette
4. Notice how your focus (and cursor) are now in the editor pane (previously, the terminal had both)

![vscode-issue-gif](https://user-images.githubusercontent.com/1411138/75977502-8a8a6b80-5eaa-11ea-9335-3e2d2c051bc3.gif)

Similar to the closed issue #46961, but for a different command palette command.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2020-03-21 11:06
Duplicate of https://github.com/microsoft/vscode/issues/93055 ?

**Closed** 2020-03-24 16:05 UTC
Labels: *duplicate, bug, quick-pick
