### ISSUE TITLE
增加设置class后光标位置自动位于最后方

### ISSUE THREAD

**Issue by zzskyweb** [Microsoft/vscode#11884] opened 2016-09-12 14:06 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.输入<xmp><div></div></xmp>
2.在div中增加class:<xmp><div class=""></xmp>
此时光标自动跳转到<xmp></div></xmp>后面，而不是位于class=“”引号中间

**Comment by thinkadd** [comment] 2016-09-12 14:32
For those who don't read Chinese, I'm trying to give some translation:
===========Translation of original post===========
Summary: Cursor jumps to line end after adding "class" in tag.

Steps:
1. Type in "<div></div>" (without quotation marks)
2. Add "class" in <div> tag --> <div class=""></div>, then the cursor jumps to the line end, after </div>, instead of staying between the quotation marks.
========================================

I have personally verified this issue(in version 1.5.1) with language mode HTML, the cursor didn't jump to line end, instead, it jumps into the closing tag, between 'd' and 'i', like </d|iv>.

**Comment by Mlocik97** [comment] 2016-09-12 14:53
Duplicate of #11719, #11763 and #11742.

**Closed** 2016-09-13 10:39 UTC
