### ISSUE TITLE
Shared workspace settings vs personal workspace settings

### ISSUE THREAD

**Issue by jamiekyle-eb** [Microsoft/vscode#68007] opened 2019-02-06 20:35 UTC
## Background

Right now it's only possible to have a single `/.vscode/settings.json` file which you may want to use for two different things:

1. Shared VSCode workspace settings across teams for things like `files.exclude`
2. Personal VSCode workspace settings for _whatever_

Most people would want to commit shared settings and `.gitignore` personal ones. But with a single file, this is currently not possible.

It would be great if you could have multiple `settings*.json` files which you can `.gitignore` or commit as you wish. 

## Feature Request

I would suggest that VSCode supports an additional file location for Workspace settings: `./.vscode/settings.shared.json`

```
/.vscode/
  settings.shared.json
  settings.json
```

Then in your `.gitignore` file you could do the following:

```
/.vscode/*
!/.vscode/settings.shared.json
```

## Alternatives

You could also reverse the relationship add a config option to `./.vscode/settings.json` that allows an additional file:

```json
{
	"settingsFilesWhateverConfig": {
    "Personal Workspace Settings": "./.vscode/settings.personal.json"
  }
}
```

**Comment by sandy081** [comment] 2019-02-12 11:57
Duplicate of #40233

**Closed** 2019-02-12 11:57 UTC
Labels: *duplicate, config
