### ISSUE TITLE
[Feature request] Take into account location information in paths when following them in the terminal

### ISSUE THREAD

**Issue by Zoxc** [Microsoft/vscode#25880] opened 2017-05-04 08:33 UTC
rustc produces error messages with paths formatted like `src\librustc\ty\instance.rs:61:31`. Currently I can Ctrl+Click to go to the file. It would be nice if it could also go to line 61, column 31.

**Comment by Zoxc** [comment] 2017-05-04 11:25
Backtraces due to panics in Rust has the form `.\src\librustc\infer\mod.rs:532`. That should also go to line 532.

**Comment by kieferrm** [comment] 2017-05-04 18:00
Support for this will be in 1.12. Duplicate of #21472. Fixed in #24832.

**Closed by kieferrm** 2017-05-04 18:00 UTC
