### ISSUE TITLE
Color file and folder names in explorer view according to their git status

### ISSUE THREAD

**Issue by sunheat** [Microsoft/vscode#21030] opened 2017-02-22 00:36 UTC
- VSCode Version: latest Insider
- OS Version: Windows 7 Enterprise

It would be nice if in the file explorer view the file and folder names can be colored according to their git status (changed, not indexed, newly added, deleted, etc.). #

**Comment by mjbvz** [comment] 2017-02-22 00:48
Duplicate of #178

**Closed by mjbvz** 2017-02-22 00:48 UTC
Labels: duplicate
