### ISSUE TITLE
Extension host is continously crashing

### ISSUE THREAD

**Issue by tdsone** [microsoft/vscode#177098] opened 2023-03-14 14:50 UTC
Type: <b>Bug</b>

1. Start VS Code

After 2-3 minutes of coding the extension host has crashed multiple times and extensions are no longer available.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 19, 17|
|Memory (System)|16.00GB (2.50GB free)|
|Process Argv|--crash-reporter-id 70cd2248-491d-4269-856c-a0dd19d979cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
preview-pdf|ana|1.0.0
protein-viewer|Ari|0.1.0
vscode-tailwindcss|bra|0.9.8
pgformatter|bra|1.20.0
doxdocgen|csc|1.4.0
postcss|css|1.0.9
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
xtend-lang|Gra|0.2.3
xtext-lang|gra|0.4.0
todo-tree|Gru|0.0.224
terraform|has|2.25.4
headwind|hey|1.7.0
xtext-vscode-example|ite|0.0.31
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-docker|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
microsoft-office-add-in-debugger|mso|0.3.0
autodocstring|njp|0.6.1
java|red|1.15.0
rust-analyzer|rus|0.3.1435
preview-vscode|sea|2.2.5
markdown-preview-enhanced|shd|0.6.8
snakemake-lang|sna|0.1.8
visualize-control-flow|tea|0.2.0
simple-rst|tro|1.5.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-icons|vsc|12.2.0
vim|vsc|1.25.2
markdown-all-in-one|yzh|3.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
funwalk2:30682974
pythonms35cf:30680985

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-14 18:40
A lot of similar recent issues have been traced to the Copilot extension.

**Comment by K2adir** [comment] 2023-03-15 01:19
same issue, started to happen after the latest update, 
Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z (6 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes

**Comment by isidorn** [comment] 2023-03-15 11:08
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:08 UTC
Labels: freeze-slow-crash-leak, extension-host
