### ISSUE TITLE
Can't open files in WSL: The editor could not be opened due to an unexpected error

### ISSUE THREAD

**Issue by fc-amiggi** [microsoft/vscode#172107] opened 2023-01-24 03:34 UTC
Type: <b>Bug</b>

I can no longer open any files inside of WSL. In the status bar in the lower left, I see "Disconnected from WSL" and while I see the directory I opened VSCode from in the tree (with no open/close widget and nothing under it), when I click on the dir name I get a pop-up saying "Unable to open <directory name>" unable to resolve resource vscode-remote://<the full path to the dir inside wsl>

VS Code version: Code - Insiders 1.75.0-insider (f1b09237cd400d92987cf7a9681995e8011ef54c, 2023-01-23T11:53:59.088Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted
Sandboxed: Yes
Connection to 'WSL: Debian' could not be established  No remote extension installed to resolve wsl.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.85GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/home/forrcaho/Amiggi/MetroNet/account-management-api --remote=wsl+Debian --crash-reporter-id 3d6bfcde-d3d0-4831-bc4c-120c572626da|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Debian' could not be established  No remote extension installed to resolve wsl.
</details>Extensions: none

**Comment by fc-amiggi** [comment] 2023-01-24 03:35
Fortunately, this is only a problem with Insiders.

**Comment by tomaxsas** [comment] 2023-01-24 06:12
here is issue: https://github.com/microsoft/vscode-remote-release/issues/7891

**Comment by aeschli** [comment] 2023-01-24 09:05
duplicate of https://github.com/microsoft/vscode-remote-release/issues/7891, fix is out

**Closed by aeschli** 2023-01-24 09:05 UTC
