### ISSUE TITLE
Filesystem-related variables report wrong-cased file name if filename case was changed sometimes on 

### ISSUE THREAD

**Issue by vimmerru** [microsoft/vscode#123664] opened 2021-05-12 11:01 UTC
- VS Code Version: Version: 1.56.1
- OS Version: Darwin x64 20.4.0

Steps to Reproduce:

0. Use preserve case filesystem. For example, default on MacOS
1. Create file (ex. sample.txt)
2. Rename it by changing case (ex. Sample.txt)
3. Create any task that uses file name variable
4. Launch task. Filename is reported in a wrong case.

It breaks some basic flows with gnu make and git.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2021-05-12 13:54
@vimmerru did this work with an earlier version of VS Code?

I'm testing on Ubuntu, and I'm not able to reproduce the issue:
1. Added this task
```
        {
            "label": "My Task",
            "type": "shell",
            "command": "echo ${fileBasename}",
            "problemMatcher": []
        }
```
2. In VS Code's file explorer I added a new file sample.txt
3. Open sample.txt in VS Code
4. In VS Code's file explorer right click to rename sample.txt to Sample.txt.
5. Run the above task.

**Comment by vimmerru** [comment] 2021-05-12 14:51
@alexr00 What file system are you using? 'preserve case' filesystem is important here. Something like ntfs or APFS.

**Comment by vimmerru** [comment] 2021-05-12 15:02
Here is the video https://share.icloud.com/photos/0HO11TqoYlMQhBtJVvTT38mkQ Behaviour looks more complex than i expected. Sometimes it returns good value, sometimes not. Sometimes file reopening helps, sometimes not, but problem is obvious.

**Comment by bpasero** [comment] 2021-05-13 09:44
@alexr00 if tasks have a variable that resembles the active editor resource, please make sure to use this helper to get the right resource: `EditorResourceAccessor.getOriginalUri`, and not `editor.resource`.

**Comment by jp06** [comment] 2021-05-14 03:08
Hi @alexr00, I want to bring this [issue regarding Handlebars highlighting](https://github.com/microsoft/vscode/issues/121478) into attention again. I wanted to open a new one but I don't want to open a duplicate, maybe this one can be reopened? My bad because I wasn't able to respond earlier.

**Comment by alexr00** [comment] 2021-05-14 08:13
@bpasero there is a place where I can change from `editor.resource` to `EditorResourceAccessor.getOriginalUri`, so I will make that change. But, some of this is in the extension host where I am using `ExtHostDocumentsAndEditors.activeEditor`. Will that have the correct resource?

**Comment by bpasero** [comment] 2021-05-14 08:40
@alexr00 I defer to @jrieken for answering that, but when I e.g. look at this line here:

https://github.com/microsoft/vscode/blob/f41b6e6d81339cc75252aba5579855010686f616/src/vs/workbench/api/common/extHostDebugService.ts#L940-L940

It seems to return the documents URI which is likely the underlying model URI which will be canonical [1] and not the original one.

[1] In order to address https://github.com/microsoft/vscode/issues/12448 we introduced the concept of canonical URIs. On platforms that are case insensitive (macOS, Windows), we want to avoid issues like having the same file opened in different editors when the path of the files are the same but with different casing. As such, canonical URIs are there to map any path casing to one form on these platforms. Basically the first one to create a canonical URI will be the one defining the path casing for the duration of the session (and sometimes beyond, e.g. when editors persist and restore). As such:
* when an editor opens, the casing of the file of the editor will become the canonical form of that URI
* no matter how many other different forms are used to open that file, the `editor.resource` and `model.uri` will always be that canonical form
* to show the right label to the user though, the `EditorResourceAccessor` was added to get at the original resource
* as far as I know, we currently do not expose any API to extensions to get at that original URI (except maybe for that new editor tab API which still seems proposed only)

**Comment by connor4312** [comment] 2021-06-04 22:33
This still seems to happen on Windows: https://memes.peet.io/img/21-06-444ad62e-2244-43f4-ae94-ab7933252a8b.mp4

**Comment by alexr00** [comment] 2021-06-07 09:05
@jrieken the incorrectly cased URI is coming from here:

https://github.com/microsoft/vscode/blob/a60beb9d7a8ade758f62dd12fa3e4461955554eb/src/vs/workbench/api/common/extHostDocumentsAndEditors.ts#L187-L197

Is that something you think should be fixed?

**Comment by jrieken** [comment] 2021-06-07 09:13
> Is that something you think should be fixed?

We have no plans for that. Internally, we know the true and canonical uri but that's nothing we expose to extensions

**Comment by bpasero** [comment] 2021-06-07 09:19
Well, at least with the new proposed `window.openEditors` we do put the original resource in:

https://github.com/microsoft/vscode/blob/f207b3830717f2c354ea12ead37baff21f33a680/src/vs/vscode.proposed.d.ts#L2660-L2660

from

https://github.com/microsoft/vscode/blob/2f500f0ce560eac073c3065b90d8f21757edcc04/src/vs/workbench/api/browser/mainThreadEditorTabs.ts#L75-L75

**Comment by jrieken** [comment] 2021-06-07 09:23
> Well, at least with the new proposed window.openEditors we do put the original resource in:

Which is maybe an oversight. IMO the extension host should know a certain resource only under one identify, not multiple. I see that this change came in as fix for this but it should probably changed back. 

@alexr00 I am afraid that you cannot use the extension API (or internals) if you depend on the true/original uri

**Comment by bpasero** [comment] 2021-06-07 09:26
Yeah, that proposed API should distinguish between the `resource` property (which should be of the canonical form) and the `displayResource` (or whatever name we end up taking) which should be used for display purposes or when used in user facing things such as variable replacement.

**Comment by alexr00** [comment] 2021-06-14 13:00
@bpasero is there a extension host service that you think it makes sense to add a `getOriginalUri` method to? It seems very unlikely that variable resolving is the only place this is needed, so I would prefer not to make my own service just for this.

**Comment by bpasero** [comment] 2021-06-15 06:23
I think I indicated what should be used (https://github.com/microsoft/vscode/issues/123664#issuecomment-855762484) but Jo seems to disagree, so maybe this needs to be an API discussion?

**Comment by jrieken** [comment] 2021-06-15 10:11
> but Jo seems to disagree, so maybe this needs to be an API discussion?

I disagree that this is an API discussion. Resolving variables in task and debug configs is something that the core provides. All information and services for that is in the renderer and I want to start by asking why are duplicating this in  the extension host now.

**Comment by alexr00** [comment] 2021-06-15 11:28
Many variables are only correct in the extension host (environment variables) and/or require node (install folder, exec folder), so the extension host seems like the logical place to resolve variables.

**Comment by alexr00** [comment] 2021-08-18 13:55
I have a fix ready in which during variable resolving in the extension host we go to the renderer to get the correct URI. However, there are several reasons why I'm not 100% happy with this change:
- Variable resolving can result in extra round trips to the renderer. (slower)
- Lots of sync code duplicated as async code. (also slower)

These two things are not great for everyone. @vimmerru it seems that renaming a file as suggested in the repro probably doesn't happen that often. I am disinclined to merge this fix as a result. If you disagree that renaming a file like this happens often, please feel free to reply and we can continue to discuss.

**Comment by vimmerru** [comment] 2021-08-18 14:22
>  @vimmerru it seems that renaming a file as suggested in the repro probably doesn't happen that often.

I don't think it is frequent case, but when it happens result is quite confusing. So decision is up to you.

**Comment by alexr00** [comment] 2021-08-18 14:57
Since the fix will result in additional slowness for all users, I will not make the fix.

**Closed by alexr00** 2021-08-18 14:57 UTC
Labels: bug, verification-found, variable-resolving, wont-fix
