### ISSUE TITLE
VSCode unresponsive for 1-2 seconds when switching between windows

### ISSUE THREAD

**Issue by artemudovyk** [microsoft/vscode#203442] opened 2024-01-25 12:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2, x64.
- OS Version: Fedora Linux 39 (Workstation Edition), Wayland, AMD GPU.

Steps to Reproduce:

1. Open 2 VSCode windows (maximized).
2. Open the first one, then switch to the second one. It will be unresponsive for 1-2 seconds.

Demo video:

https://github.com/microsoft/vscode/assets/58283675/35b992dd-edf1-4916-8d9c-d5f14684c9f4

Happens only with 2+ VSCode (or 2+ VSCode Insiders) windows. If I'd open a VSCode + VSCode Insiders - it's fine. Switching between different apps (VSCode + Firefox, for example) is also fine.

If I don't maximize windows and keep them in window mode, it's fine:

https://github.com/microsoft/vscode/assets/58283675/31e13b13-e98a-45f1-a774-a8f29ca0efab

What I tried and it didn't help:
- Install VSCode Insiders. The same happens with 2 windows of VSCode Insiders, but not if one is VSCode and the other is VSCode Insiders. But it's not optimal because something will still lag with 3+ projects opened.
- Disable hardware acceleration.
- Disable all extensions.

**Comment by bpasero** [comment] 2024-01-25 13:40
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2024-01-25 14:56
Thanks for the video, this looks like a window manager or upstream issue to me.

**Comment by artemudovyk** [comment] 2024-01-30 17:12
The latest build of VSCode Insider suffers from the same problem.

Version: 1.86.0-insider
Commit: 9c5eabb378c9d18a0f712d1f22fe63df3f933ade
Date: 2024-01-30T03:55:53.004Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.6.13-200.fc39.x86_64

https://github.com/microsoft/vscode/assets/58283675/a66ba124-30f2-4476-be4b-ace0911e14ff

**Comment by artemudovyk** [comment] 2024-04-20 20:32
Didn't find one. I've tried KDE instead of GNOME DE, and the problem didn't occur there. But I tested it very briefly, so not 100% sure.
For now, I'm waiting for a Fedora 40 to be stable with a new version of GNOME, and I hope it will resolve the problem with a VS Code.

**Comment by artemudovyk** [comment] 2024-04-25 10:12
I've upgraded to Fedora 40 (GNOME 46). The issue persists.

Tinkered with it a bit, and found out that VSCode launches in XWayland instead of Wayland. When launching VSCode or VSCode insiders with flags to launch in Wayland (something like `code --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations`), lags when switching between windows doesn't appear anymore. But there's no way to lock these options when launching from the terminal (in ArchLinux there is a `~/.config/code-flags.conf` file), only to edit the `.desktop` file.

Another issue is that I can't pin the app in the Dash to Panel when the VSCode launches with the options I've mentioned above, as it treats it as a different application. So the experience is not optional on that front.

Is there any other way to force VSCode to launch in Wayland instead of XWayland consistently from the terminal and desktop launch?

**Comment by artemudovyk** [comment] 2024-09-23 08:16
Switched to KDE Plasma 6 (Fedora) instead of GNOME and the issue is gone out of the box.

**Comment by deepak1556** [comment] 2024-12-17 17:58
closing per above comment

**Closed by deepak1556** 2024-12-17 17:58 UTC
Labels: freeze-slow-crash-leak
