### ISSUE TITLE
CTRL+F2 highlights occurrences on scrollbar only downwards

### ISSUE THREAD

**Issue by turboborsuk** [Microsoft/vscode#38088] opened 2017-11-10 19:52 UTC
When using CTRL+F2 to select all occurrences of a string all of them are selected within the file but the scrollbar feedback is limited to only those starting from current selection and downward.

- VSCode Version: 1.18.0
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Open a reasonably long file with multiple occurrences of a specific string
2. Select a string occurrence somewhere in the middle
3. Observe tickmarks on scrollbar missing until current selection.

**Comment by alexandrudima** [comment] 2017-11-13 11:38
Duplicate of #1110

**Comment by turboborsuk** [comment] 2017-11-13 14:01
It's a completely different scenario than #1110.
It's an issue with checkmarks feedback on scrollbar, not actual code highlights.
You can try it with as little as 3 occurrences of a string in a file.

Please reopen and evaluate for duplicates more diligently.

**Comment by alexandrudima** [comment] 2017-11-13 14:05
@turboborsuk I cannot reproduce. I could not reproduce 2 hours ago, so I thought you just ran into #1110:

![38088](https://user-images.githubusercontent.com/5047891/32729431-0b83324a-c884-11e7-8c40-a7d0f74c4cc7.gif)

Can you perhaps add more precise information to help me reproduce ?

**Comment by turboborsuk** [comment] 2017-11-13 14:20
You can see this behavior below - when highlighting the first occurrence of the word "two" and hitting CTRL+F2 you get two checkmarks on the scrollbar. When doing the same after selecting the second one you get only one checkmark but the first occurrence is also highlighted for editing.

It can get annoying if you use the scrollbar feedback to know what parts of the file will be edited.

![test](https://user-images.githubusercontent.com/22117434/32729828-5daff21e-c885-11e7-89a0-26df1869c5d7.gif)

**Comment by alexandrudima** [comment] 2017-11-13 14:28
@turboborsuk thank you. I can reproduce now.

**Closed** 2017-11-13 14:33 UTC
Labels: bug, editor, new release
