### ISSUE TITLE
[Debug] Cannot launch multiple programs in integrated terminal

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#40814] opened 2017-12-26 02:21 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 10

**Steps to Reproduce**:
1. Install [java-debug extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)
2. Use vscode to open java project, add two launch configurations on `launch.json`, and both configurations' console setting is `integratedTerminal`.
3. Launch the first one, and you see `Java Debug Console` channel added to integrated terminal.
4. Try to launch the second one, timeout. No new terminal channel is created. 

See the gif below. The two launchInTerminal commands are sent to the same shell terminal, but the first debug session is still running so that the second one is pending. You see if i stop the first one, the second the runInTerminal commands shows up immediately at the same terminal.

![cannotlaunchinterminal](https://user-images.githubusercontent.com/14052197/34344968-4165e5f6-ea26-11e7-932c-c5df693aecb7.gif)

**Expected behavior**:

- Users should be able to launch multiple programs in integrated terminal
- Each program should have its own terminal created

**Comment by isidorn** [comment] 2017-12-27 08:53
@testforstephen Here's a code pointer in case you are interested in providing a PR that solves this issue
`https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L21`

Forwarding to @weinand feel free to bounce back to me if you would like me to investigate

**Comment by weinand** [comment] 2017-12-27 09:32
duplicate of #37589

**Closed by weinand** 2017-12-27 09:32 UTC
Labels: debug
