### ISSUE TITLE
Slow performance after 1.77 update

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#181434] opened 2023-05-03 17:55 UTC
@mjbvz 
It happened for me in all code repos I tried, including public ones such as https://github.com/microsoft/vscode/. For now I can't point to specific location in code and editing action where this problem reproduces 100%.

I can only confirm that disabling error handler telemetry (e.g. with https://github.com/sergei-dyshel/vscode/commit/122c48b6bf76fe52a1959fc5932fb1a07d8686a3) eliminates the issue. 

When I have some more time I'll try to investigate it a bit more.

_Originally posted by @sergei-dyshel in https://github.com/microsoft/vscode/issues/178799#issuecomment-1532829589_

**Comment by mjbvz** [comment] 2023-05-03 17:57
@jrieken Can you investigate this. The reporter suggests it may be related to extension host exception handling

**Comment by DPRIYATHAM** [comment] 2023-05-03 21:33
I do have the same issue, before I checked this issues section, I thought some issue with my laptop and reinstalled vs code, still issue hadn't resolved, then I realized it is 1.77v problem after viewing this issue, thanks for making this issue, else I would be sitting the whole night to debug the issue. 💀

**Comment by jrieken** [comment] 2023-05-04 07:52
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#startup-timer. Thanks.

**Comment by sergei-dyshel** [comment] 2023-05-04 22:22
@jrieken 
May I ask how is startup time is related here? The slowness happens during using language features, not on start.

Instead, can you provide information/link to guide on how to debug extension host itself? Particularly I'm interested:
1. Putting breakpoints in exthost code - I can put breakpoint in error handler to see when `prepareStackTrace`.
2. Adding debugging logs to exthost.
3. Existing `PerformanceObserver/Histogram` infrastracture that I can use to add error handler histograms by plugin.

**Comment by hasokeric** [comment] 2023-06-03 18:50
I am facing the same issue I am on the latest build Insiders.

**Comment by maccman** [comment] 2023-06-04 18:24
Same here

**Comment by hasokeric** [comment] 2023-06-04 21:33
@maccman I just downgraded to 1.76 and the problems are all gone!

https://github.com/sergei-dyshel/vscode/commit/122c48b6bf76fe52a1959fc5932fb1a07d8686a3
https://vscode.blob.core.windows.net/insider/c9e3ef865539061b5602c6b9ac6030332aa1ce70/VSCodeSetup-x64-1.76.0-insider.exe

**Comment by maccman** [comment] 2023-06-06 21:41
@hasokeric  Me too - downgrade worked for me.

For any core-team members reading this, this seems like a real problem.

**Comment by DavidAmunga** [comment] 2023-06-10 06:18
Thanks @hasokeric , Downgrade worked for me well. Hopefully this is resolved soon by the core team.

**Comment by maccman** [comment] 2023-06-10 20:58
@jrieken bump :)

**Comment by maccman** [comment] 2023-06-13 18:34
Managed to capture a profile

[25fb790dc5e0.json.zip](https://github.com/microsoft/vscode/files/11738041/25fb790dc5e0.json.zip)

**Comment by jrieken** [comment] 2023-06-14 06:49
Still needs actionable information. Please use this guide to provide more information: [https://github.com/Microsoft/vscode/wiki/Performance-Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and/or "F1 > Start Extension Bisect" to provide more information

**Comment by hasokeric** [comment] 2023-06-15 17:04
Is this the related issue, finally someone caught it? We should be able to see if it solves it in the next minor releases, perhaps insiders... https://github.com/microsoft/vscode/issues/184926

**Comment by jrieken** [comment] 2023-06-23 10:07
closing that either dupe of #184926 or not actionable as no further information has been delivered

**Closed by jrieken** 2023-06-23 10:07 UTC
Labels: info-needed
