### ISSUE TITLE
Regular replacement

### ISSUE THREAD

**Issue by azbo** [Microsoft/vscode#48877] opened 2018-04-28 06:46 UTC
- VSCode Version:1.22.2
- OS Version:windows10

Steps to Reproduce:

1.Regular replacement
setResourceId;
setResourceType;
![image](https://user-images.githubusercontent.com/5110699/39393035-d01c51ae-4af2-11e8-83a2-61f7f326165f.png)

\w+.\w+;\s+

“\s+” The newline character cannot be identified normally

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tommai78101** [comment] 2018-04-29 04:04
No, that is correct:

https://regex101.com/r/8oGY0E/1

**Comment by alexandrudima** [comment] 2018-04-30 07:27
@azbo I'm guessing you expect `\s` to also match the EOL sequence, `\n` or `\r\n`, depending on the file.

The reason is because we don't switch on the multi-line flag for the regular expression in this case. The workaround is to use `\w+.\w+;[\s\n]+` (manually write `\n` in there). This gives us a hint to enable the multi-line flag for the regex.

Duplicate of #9051

**Closed by alexandrudima** 2018-04-30 07:27 UTC
Labels: editor, editor-core
