### ISSUE TITLE
Debug Console: Closing parenthesis stops completion

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87123] opened 2019-12-16 23:59 UTC
Version: 1.42.0-insider
Commit: 2d2ac8f75b539d505443ac0733b196851c0b218d
Date: 2019-12-16T12:08:26.094Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

Repro:

- Have a file `test.js` with following content, breakpoint on the second line:

```js
const a = 5
const b = 10
```

- Type `a.` to complete in debug console, this works:

![image](https://user-images.githubusercontent.com/4033249/70953018-e288a300-201c-11ea-93f8-06ddfcf55dcb.png)

- Type a dot after `a` in `(a)`, this doesn't work, even with hitting Ctrl+Space manually

![image](https://user-images.githubusercontent.com/4033249/70953064-0c41ca00-201d-11ea-8315-bc1963f3b164.png)

- Although in editor it works fine

![image](https://user-images.githubusercontent.com/4033249/70953051-03e98f00-201d-11ea-8324-2faa153ded41.png)

**Comment by isidorn** [comment] 2019-12-17 11:44
Yes, there is an issue here.
The problem is how we set the completion item properties [here](https://github.com/Microsoft/vscode/blob/a6e81fb6863470e7b35f598cab1670ff6c080f15/src/vs/workbench/contrib/debug/browser/repl.ts#L148) `word`, `overwriteBefore` and `text`. We need to somehow set thos properties differently such that vscode does not filter out the completions.
All those properties are documented [here](https://github.com/Microsoft/vscode/blob/a6e81fb6863470e7b35f598cab1670ff6c080f15/src/vs/editor/common/modes.ts#L393)

I am open for a PR that fixes this.
fyi @connor4312

**Comment by petevdp** [comment] 2019-12-18 19:07
@isidorn I took a look at this and it seems like the only significant difference from variables you listed is `text`.
When which is then sent to the debugger via [RawDebugSession.send](https://github.com/microsoft/vscode/blob/b9f0336dc36e9231a3325bd246fbd3d38e820297/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L326).
[response.body.targets defined here](https://github.com/microsoft/vscode/blob/af864aed2f167376f9b950f7415786e59cf25d5d/src/vs/workbench/contrib/debug/browser/debugSession.ts#L573) is then given as an an empty list.

some additional test cases which also fail to show completions: 
```
(a.
[a.
{a.
{a: a.
;a.
```
Note that just a closing parens or equivalent for some of the other examples works fine, and it seems that only the opening parens matters for this issue.

**Comment by connor4312** [comment] 2019-12-18 20:57
I seem to have (accidentally?) avoided this issue when reworking PWA's completions

![image](https://user-images.githubusercontent.com/2230985/71122496-957c0c80-2195-11ea-8153-4cad2bb50666.png)

**Comment by isidorn** [comment] 2019-12-19 09:32
@connor4312 great! Assigning this issue to you as well, since that is a proof that the issue might lye on the extension side. And you can close it once we start using pwa debugger as the default.
@petevdp thanks for investigating, however I can not get anything concise from your comment that would help us with this issue. It seems like the issue can be solved on the extesnion side, thus removing help-wanted.

**Closed** 2019-12-19 19:52 UTC
Labels: bug, debug, debug-console
