### ISSUE TITLE
Unable to see the execution in vs code. 

### ISSUE THREAD

**Issue by PradeepHebbar** [Microsoft/vscode#26193] opened 2017-05-08 09:01 UTC
the test cases are shown as passed but i cant see the execution. 
I can see that browser is launched but no Url is loaded.

But when i run the same project in command promt i can see the URL getting loaded and the execution of the test case as well.

**I am pasting my launch.json and config file below::**

{
   
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
            "args": ["${workspaceRoot}/config.js"]
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "address": "localhost",
            "port": 5858
        }
    ]
}

**config.js**

var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
var jasmineReporters = require('jasmine-reporters');
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['spec/Calculator.js'],
    capabilities: {
        'browserName': 'chrome'
    },
    jasmineNodeOpts: {
        showColors: true
    },
	
    onPrepare: function() {
		console.log("inside config");
        jasmine.getEnv().addReporter(
            new Jasmine2HtmlReporter({
                savePath: 'target/screenshots'
            })
        );
    }
};

**These are the logs printed in vscode console window:::**

node --debug-brk=48235 --nolazy node_modules\protractor\bin\protractor c:\Users\dipika.gusain1\Desktop\Jasmine/config.js 
Debugger listening on [::]:48235
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
inside config
3.
Finished in 0.13 seconds
3 tests, 3 assertions, 0 failures
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed

**Comment by egamma** [comment] 2017-05-08 09:12
@pradeep-kumar-JP please provide more context, what are you trying to do when the problem occurrs?  What is your setup. Do you want to debug a protractor test case?

**Comment by pradeep-kumar-JP** [comment] 2017-05-08 09:21
@egamma 
Its a protractor-jasmine framework. I am just trying to run my test cases in the vscode.

When i run my test cases in command promt, i face no issue i.e.
1.   I can see the URL getting loaded each time my test cases are run.
2.   I can see the execution on the browser.


But when i run the same test cases in vs code,  i can't see any of those 2 happening . Also i dont understand how the test cases are reporting to be passed in console window.


i have shared my launch.json , config,js,  and reports on the console in the previous comment box.

**Comment by egamma** [comment] 2017-05-08 09:29
@pradeep-kumar-JP thanks for the additional information, but the launch.json is not sufficient for us to reproduce the problem, can create or point to a setup (e.g. github repository) that we can use to reproduce the problem.

**Comment by weinand** [comment] 2017-05-08 09:37
@pradeep-kumar-JP are you following the (VS Code) steps listed here: https://github.com/angular/protractor/blob/master/docs/debugging.md ?

**Comment by pradeep-kumar-JP** [comment] 2017-05-08 10:09
Do you mean  I should push my project folder in github repository ?

**Comment by pradeep-kumar-JP** [comment] 2017-05-08 10:15
@weinand 
I am not debugging. I am simply trying to run my test cases in vs code

**Comment by weinand** [comment] 2017-05-08 13:16
@pradeep-kumar-JP configuring a launch.json is typically used for debugging, but of course, using it for running tests should work too.

Could you please try to run your tests from the command line but inside VS Code. For this open the integrated terminal and use the same command that you would use when running the tests ouside of VS Code.

Does this work?

**Comment by pradeep-kumar-JP** [comment] 2017-05-09 05:27
@weinand  
Thank you for the solution. I am able to run the test cases from the integrated terminal.
Could u please suggest a way to debug .?

**Comment by weinand** [comment] 2018-03-02 16:15
@PradeepHebbar  is this still a problem in recent versions of VS Code and Node.js?

**Comment by aj-r** [comment] 2018-03-02 18:11
@PradeepHebbar @weinand I was having a similar issue trying to debug tests with plain jasmine (no protractor). The issue was that Jasmine's default reporter writes to `stdout`, not necessarily to the console. Adding `"console": "integratedTerminal"` to my launch config fixed the problem.

**Comment by pavelstudeny** [comment] 2018-03-27 07:07
@weinand, yes. Redirecting the output to the terminal as suggested above didn't look that great, but
`"outputCapture": "std"` works for me so far.

**Comment by weinand** [comment] 2018-03-27 07:59
So there seem to be enough ways to get this to work. Closing.

**Closed by weinand** 2018-03-27 07:59 UTC
Labels: debug, needs more info
