### ISSUE TITLE
Support websockets port forwarding

### ISSUE THREAD

**Issue by jylin** [microsoft/vscode#138159] opened 2021-11-30 14:06 UTC
Related to: https://github.com/microsoft/vscode/issues/74085
It seems the fix in that issue did not work, but is there any way to support also forwarding websocket ports?

The main reason for requesting this is that for apps built with create-react-app or similar tools: hot module reloading does not work if you forward for example port 3000 to develop an app. Is there any way to support also websocket forwarding so that things like hot reload work?

**Comment by mjbvz** [comment] 2021-12-06 19:46
Duplicate of #84819

**Closed by mjbvz** 2021-12-06 19:46 UTC
