### ISSUE TITLE
Integrated terminal does not refresh anymore in v1.80 => background color not applied

### ISSUE THREAD

**Issue by ybrock** [microsoft/vscode#187582] opened 2023-07-11 13:24 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0
- OS Version: Windows 11 Enterprise 22h2 (OS Build 22621.1848)

Steps to Reproduce:

1.  use escape sequences in your bash prompt to change background dynamically, for example (in your .bashrc) :
```
prompt_command() {
    bgcolor='0e2832'
    fgcolor='ffffff'
    promptstring="\e]11;#${bgcolor}\007\e]10;#${fgcolor}\007"
    echo -ne "$promptstring"
}
PROMPT_COMMAND="prompt_command ;history -a; history -c; history -r"
```
Terminal background changes to `$bgcolor`
2. Open two (or more) tabs
3.  When switching from one tab to the other one, the background is not redrawn in the choosen color.

This was working previously, with WSL, Cygwin bash, SSH Remote + bash, SSH Remote + ZSH

Now it is not working anymore, or randomly.
You have to press Enter once to have the prompt refresh your background.

**Comment by Tyriar** [comment] 2023-07-28 13:46
Might be a duplicate of https://github.com/microsoft/vscode/issues/187803

**Comment by Tyriar** [comment] 2024-12-10 17:15
`PROMPT_COMMAND` isn't re-run when you switch tabs normally, you would need to press enter/ctrl+c to get the new colors by design in bash. Maybe I'm misunderstanding but this should never have worked.

**Closed by Tyriar** 2024-12-10 17:15 UTC
Labels: confirmation-pending, terminal-rendering

**Comment by ybrock** [comment] 2024-12-11 06:41
It was working in the past with prior versions of vscode, and it is working with almost any other terminal emulator like konsole, cygwin mintty or gnome-terminal for example.

When vsocde loose focus on a window, it draws it with default theme colors now, like black and the background colors set with PROMPT_COMMAND and Escape sequences are lost.

**Comment by Tyriar** [comment] 2024-12-11 09:12
I just added this to my `.bashrc`:

```
PROMPT_COMMAND='echo -n "$(date +"%T") "'
```

Focus/unfocus of the terminal does not reprint the prompt:

![Image](https://github.com/user-attachments/assets/bd0d821d-b967-4311-8e37-1882f641d748)

This is the same in VS Code and Windows Terminal

Is that what you mean?

**Comment by ybrock** [comment] 2024-12-11 15:32
You have to open many terminal in full window, and then if you switch from one terminal tab, to another tab (either terminal tab or file tab) and back, the terminal is not redrawn and stays black (probably depending on the theme applied).

If you keep the terminal in the lower part of vscode, the issue is not produced. It's when the terminal is on full size (as an editor tab).
