### ISSUE TITLE
[Fedora Linux] Custom titlebar dissapearing after changin the profile

### ISSUE THREAD

**Issue by proninyaroslav** [microsoft/vscode#189725] opened 2023-08-05 18:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: Fedora Linux 38 (GNOME/Wayland)

**Steps to Reproduce:**

1. Switch to `custom` titlebar in the `window.titleBarStyle` settings
2. Create some profile and setup checkboxes like this (select only extensions):

![image](https://github.com/microsoft/vscode/assets/7840559/8ca07205-09dd-4f05-97ca-a0cf7235b8c5)

4. Switch to the new profile

**Expected behavior:**

Titlebar should not disappear after profile change.

**Actual behavior:**

After changing the profile, the titlebar disappears. This happens if, when setting up a profile, I uncheck the `Settings` checkbox, that is, if I want to use the default profile settings. This doesn't happen if I check the checkbox, in which case everything works fine.

I also recorded a video to make it a bit clearer:

[2023-08-05-21-34-34.webm](https://github.com/microsoft/vscode/assets/7840559/e929f79c-24e0-485b-9c6b-27948b28acdb)

**Comment by sbatten** [comment] 2023-08-29 00:29
I believe duplicate of linked issue

**Closed by sbatten** 2023-08-29 00:29 UTC
