### ISSUE TITLE
[1210/111511.666:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#112216] opened 2020-12-10 11:17 UTC
![image](https://user-images.githubusercontent.com/55927613/101765412-2cde1c00-3ad9-11eb-857f-fd8e269f9432.png)

![image](https://user-images.githubusercontent.com/55927613/101765321-120ba780-3ad9-11eb-97f0-b68d8d97823a.png)

The folder  opened without a problem. But in the terminal it was displayed this weird message.

Steps to Reproduce:

I just opened another directory using ``code .` and it displayed that message. It was the first time it happened.  No ideia how to reproduce it.

Does this issue occur when all extensions are disabled?: N/A

**Comment by bpasero** [comment] 2020-12-10 16:49
Also saw this error in https://github.com/microsoft/vscode/issues/112202

//cc @deepak1556

**Comment by deepak1556** [comment] 2020-12-10 17:00
This is dupe of https://github.com/microsoft/vscode/issues/109782 and https://github.com/microsoft/vscode/issues/107496

The log itself is completely harmless, I don't plan to fix this anytime soon but will keep this issue open to avoid more duplicates.

**Comment by wsmelton** [comment] 2020-12-22 17:26
This file gets created anytime the second instance of VS Code is opened for me. I work with repositories that do not support the use of a `.gitignore` file (Github Wikis) so it is not like I can just ignore it. 

The file is locked by the VS Code process so there is no way to delete it when it gets created without restarting VS Code **every time**. This causes user workflow to break when we are using the control pallet for quick commits because that file will end up being included in PRs.

**Comment by SleeplessByte** [comment] 2020-12-27 19:55
Seems to be a regression of https://github.com/microsoft/vscode/issues/105191.

**Comment by baruchiro** [comment] 2020-12-28 15:12
> Seems to be a regression of #105191.

I agree. The wired thing is this issue closes with empty commit?? #107366

Anyway, reproduced for me with:
```
Version: 1.53.0-insider (system setup)
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:33:38.481Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.20270
```

And the `debug.log` file is everywhere!

**Comment by SleeplessByte** [comment] 2020-12-28 16:00
Workaround to run as Administrator still works. (Same vscode version as @baruchiro).

**Comment by albannurkollari** [comment] 2021-02-05 10:20
The issue is back again in 1.53.0!

**Comment by viceice** [comment] 2021-02-05 12:54
Seeing this in `Docker Language Server` logs.

`[0205/134634.781:ERROR:registration_protocol_win.cc(102)] CreateFile: Das System kann die angegebene Datei nicht finden. (0x2)`

On this repo: https://github.com/renovatebot/docker-renovate

**Comment by sarrahtrembl** [comment] 2021-02-05 13:13
Hey, je suis désolé à l'avance pour mon choix de langue mais pourquoi pas faire different? Ou même un mélange des deux? Sometime i will talk in english but i love french. ..


Pour répondre à ton commentaire, tu as raison que le site n'est pas dévouer à ca, par contre, je ne vois pas ce qu'il y a de mal à faire le pas à un rythme différent ?

**Comment by baruchiro** [comment] 2021-02-05 13:47
@sarrahtrembl I think you need to write in English

**Comment by AllanOricil** [comment] 2021-02-05 15:15
> @sarrahtrembl I think you need to write in English

@baruchiro report it. It is a bot. the more people that report it, the quicker it gets deleted.

**Comment by joanofdart** [comment] 2021-02-05 21:28
![image](https://user-images.githubusercontent.com/43426084/107091019-59749280-6801-11eb-89f3-84f822bace42.png)

I was just creating a new app using `npx create-next-app app` and when I wanted to open code from the cmd, that log appeared.

**Comment by Baystef** [comment] 2021-02-06 14:55
> ![image](https://user-images.githubusercontent.com/43426084/107091019-59749280-6801-11eb-89f3-84f822bace42.png)
> 
> I was just creating a new app using `npx create-next-app app` and when I wanted to open code from the cmd, that log appeared.

Same issue with me too

**Closed** 2021-02-10 07:39 UTC
Labels: electron, upstream

**Comment by geirivarjerstad** [comment] 2021-02-11 09:43
Find out which extension that is using the "**debug.log**" file by using tooling such as [https://lockhunter.com/](https://lockhunter.com/), then uninstall those extentions. In my case it was the yaml "https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml"
