### ISSUE TITLE
Unable to update from 1.18.0-insider on Windows_NT x64 10.0.17046

### ISSUE THREAD

**Issue by apwestgarth** [Microsoft/vscode#39280] opened 2017-11-28 19:25 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 10.0.17046
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
AzureFunctionsSnippets|ahm|0.1.0
vscode-azurefunctions|ahm|0.0.1
azuretoolsforvscode|bra|1.3.0
vscode-markdownlint|Dav|0.12.0
azure-functions-tools|joh|0.3.1
gauntletStaging|Mic|1.5.0
PowerShell|ms-|1.5.1
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
vscode-docker|Pet|0.0.22
code-spell-checker|str|1.5.1
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1.Restart to update
2. Check about information - still reports 1.18

Reproduces without extensions: Yes

**Comment by cleidigh** [comment] 2017-11-28 20:28
@apwestgarth 
Can you give more information.
- Did an update dialogue start and show downloading new code?
- Did code restart at all?
- any errors?
- did you try uninstalling and reinstalling?

**Comment by apwestgarth** [comment] 2017-11-28 23:35
I get a UAC prompt and then nothing further;
Code shutdown.
I don't see any errors reported.
I will try uninstalling and reinstalling.

**Comment by apwestgarth** [comment] 2017-11-28 23:38
When I view Task Manager I saw a number of CodeSetup-Insider exe and tmp processes running,  I've killed the original list and opened code and closed to update.  Now I see the following:

![image](https://user-images.githubusercontent.com/1146895/33350149-33656de4-d452-11e7-8af9-f3d9fc476712.png)

**Comment by Joelism** [comment] 2017-11-29 07:41
It seems to be a bug in 17046. I'm not able to run any installer of any program unless doing a reboot.

**Comment by kieferrm** [comment] 2017-11-30 00:18
On 17040 I can't reproduce the issue.  See the same on 17046.

**Comment by apwestgarth** [comment] 2017-11-30 17:55
It's not localised to 17046, I have another machine on that build with no issues.

On this machine I now cannot install either having uninstalled.

**Comment by kieferrm** [comment] 2017-12-06 19:47
@apwestgarth can you clarify your last sentence?

**Comment by joaomoreno** [comment] 2018-09-19 15:37
Seems lost in history. Closing.

**Closed by joaomoreno** 2018-09-19 15:37 UTC
Labels: bug, install-update, upstream
