### ISSUE TITLE
syncing with remote git repos

### ISSUE THREAD

**Issue by Muha0644** [microsoft/vscode#135208] opened 2021-10-16 11:43 UTC
Issue Type: <b>Bug</b>

Everything worked fine before so a recent change is most likely causing this issue.
When I make a commit locally and press sync, it pops up a git error about divergent branches. Now, using `git push` manually in the terminal works fine so i'm guessing it's a VSC problem.

My guess is it tries to do `git pull` first, and that might be causing an issue because the local repo is ahead of the remote when it tries to pull.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:15:35.620Z)
OS version: Linux x64 5.14.12-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|15.56GB (0.16GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6cfe3661-03aa-473d-8bde-601111505e7a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>

**Comment by vbrozik** [comment] 2021-10-30 09:57
This does not seem to be a duplicate of #135186 which is related to the `pull.ff = only` option.

Before upgrading git from 2.25.1 (default in Ubuntu 20.04) to 2.33.1 I did not need any of these settings:
```
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
```
... and the "Synchronize changes" function in VS Code was working well to push changes to the remote repository. Now I have to use just "Push" explicitly. Did not VS Code lose compatibility with the latest Git versions?

**Comment by ahkohd** [comment] 2021-11-02 09:02
Does anyone have a fix?? it's really annoying or do I downgrade git for now??

**Comment by lukashass** [comment] 2021-11-02 09:15
@ahkohd 

> Turns out setting `pull.rebase` to either value fixes this issue.

So `git config --global pull.rebase false` is most likely what you want to do.

**Comment by ahkohd** [comment] 2021-11-02 09:31
@lukashass thanks

> @ahkohd
> 
> > Turns out setting `pull.rebase` to either value fixes this issue.
> 
> So `git config --global pull.rebase false` is most likely what you want to do.

Thanks, it works!

**Comment by vbrozik** [comment] 2021-11-02 13:39
@ahkohd Another option is to use push only instead of synchronize changes.

**Source control tab > Source control > the repository > ... > Push**
or
**F1 > Git: Push**

If one of the `pull.rebase` options corresponds to the original behavior it would be good to know which one it is.

**Comment by fnkr** [comment] 2021-12-08 09:10
On GitHub Codespaces you can enable the "Rebase When Sync" option in VSCode settings to fix this. Setting `pull.rebase` in the [configured dotfiles repo](https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-codespaces-for-your-account#dotfiles) doesn't really work because GitHub removes git config files when cloning the repo (so you would have to set it manually for every new Codespace).

**Comment by lszomoru** [comment] 2022-01-05 14:45
The issue related to `pull.ff = only` has been [fixed](https://github.com/git/git/blob/dcc0cd074f0c639a0df20461a301af6d45bd582e/Documentation/RelNotes/2.34.0.txt#L206) in git 2.34. Can you please upgrade to the latest version. Thank you!

**Comment by josielewis** [comment] 2022-01-19 15:10
Updating my git version solved this issue.

**Comment by lszomoru** [comment] 2022-01-20 16:17
Thanks for the update. I will close the issue.

**Closed by lszomoru** 2022-01-20 16:17 UTC
Labels: bug, git, upstream-issue-fixed
