### ISSUE TITLE
Sometimes cursor drawn does not match the cursorStyle that is set

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#17472] opened 2016-12-17 19:39 UTC
After the 1.8.0 release, the VSCodeVim extension is not always rendering the correct cursor.

I am using: console.log(vscode.window.activeTextEditor.options.cursorStyle); to verify cursor style

In some cases, it prints vscode.TextEditorCursorStyle.Block (which is what I want), but what is rendered looks to be vscode.TextEditorCursorStyle.Line.

So there is a mismatch between vscode.window.activeTextEditor.options.cursorStyle, I set it to exactly what I want, I query the value of vscode.window.activeTextEditor.options.cursorStyle and it is what I set it to, however what is drawn is NOT what I set it to.

It is easiest to reproduce in settings.json currently, however we are seeing it sporadically in other files as well..

**Comment by xconverge** [comment] 2016-12-19 04:52
Related #17513

**Comment by xconverge** [comment] 2017-03-22 21:13
Was this fixed? It seems to be different/fixed on insiders

**Comment by rebornix** [comment] 2017-03-22 22:05
@xconverge Even though right now it looks reasonable in Insider, I'll say let's keep an eye on it. Basically right now we are saving a lot of stuff to settings file and whenever the settings file change, the options cache on active text editor will get flushed. The racing of our Vim's internal cursor update and Code's internal cursor style update might be the root cause.

**Comment by alexandrudima** [comment] 2017-03-27 20:04
Possibly 67924dec07b503fafbe6e7128333ae15202e3ef9 improved things a lot

**Comment by alexandrudima** [comment] 2018-04-17 10:03
Duplicate of #17513

**Closed by alexandrudima** 2018-04-17 10:03 UTC
Labels: bug
