### ISSUE TITLE
为什么代码没写完就跳到当前行的末尾了

### ISSUE THREAD

**Issue by venlee1993** [Microsoft/vscode#26112] opened 2017-05-06 10:11 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.7|
|vscode-icontheme-nomo-dark|be5invis|1.2.6|
|open-html-in-browser|coderfee|0.0.9|
|vscode-html-css|ecmel|0.1.2|
|live-html-previewer|hdg|0.0.1|
|html-tag-wrapper|hwencc|0.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|;

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment] 2017-05-07 00:57
Can you provide more details or repro steps or even better a gif to help troubleshoot?

**Comment by Leedehai** [comment] 2017-05-07 03:20
**Translation of the issue's title**: the cursor jumps to the end of the current line before finishing coding.

Comment: honestly I don't understand this issue, either.

**Comment by King66** [comment] 2017-05-07 04:34
@Leedehai 没必要翻译，人家看得懂的😅

**Comment by egamma** [comment] 2017-05-07 22:05
I suspect this is caused by an extension, can you please try to reproduce with all extension disabled.

See [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment] 2017-05-09 07:17
Closing the issue for now, pls reopen with additional information.

**Closed by egamma** 2017-05-09 07:17 UTC
Labels: needs more info
