### ISSUE TITLE
Allow notebook cells that are grouped to be moved together

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#99882] opened 2020-06-11 15:16 UTC
This came up in our user study of the GitHub Issues Notebook where multiple users expected that moving a header cell, with grouped cells underneath, would move all cells. Users also attempted to collapse the header and then try moving that but it only moved the single header

1. Create a notebook with two headings and nested code cells
  ![image](https://user-images.githubusercontent.com/35271042/84403698-d68c3100-abba-11ea-9ec4-5ca727460ed5.png)
2. Collapse one heading and attempt to move
  ![image](https://user-images.githubusercontent.com/35271042/84403904-1226fb00-abbb-11ea-994f-40106655163f.png)
3. :bug: Only a single cell is moved
  ![image](https://user-images.githubusercontent.com/35271042/84404466-b0b35c00-abbb-11ea-8bd2-0c3dfaca5c86.png)

A few ideas that @kieferrm I discussed was to allow moving grouped cells when they are collapsed (Colab does this), and also provide a keyboard shortcut for moving cells when they are expanded. If we move grouped cells by default we run into issues where easily moving a single markdown cell may not be possible.

**Comment by rebornix** [comment] 2020-06-11 20:47
> allow moving grouped cells when they are collapsed
> provide a keyboard shortcut for moving cells when they are expanded

Are these two items the same? Dragging a collapsed markdown cell moves the all cells inside the folding region, dragging an expanded cell will only move the cell itself. Or we want to have two set of commands to move individual cells or grouped cells no matter if they are collapsed or not.

**Comment by misolori** [comment] 2020-06-11 21:00
They are different. I think in the latter part you want to provide a quick and easy way to move nested cells without having to collapse the items (because that would be extra clicks - collapse, move, expand vs click + keyboard shortcut). Sort of like dragging a cell and holding down option duplicates the cell. But we still want to be able allow users to move a single cell.

**Comment by rebornix** [comment] 2020-07-22 22:09
Fixed in master.

**Comment by connor4312** [comment] 2020-08-05 21:42
This doesn't work for me, example: https://memes.peet.io/img/20-08-7c21caf6-80a6-4369-95d6-66ace31a2edd.webm

**Comment by rebornix** [comment] 2020-08-05 23:45
Verifiers, please test both drag cells upwards and downwards.

**Comment by JacksonKearl** [comment] 2020-08-06 18:09
Seeing the cells get reversed somehow...
![recording (4)](https://user-images.githubusercontent.com/8586769/89566601-4858b380-d7d5-11ea-9609-52bac66b93e0.gif)

**Comment by rebornix** [comment] 2020-08-06 18:19
![Kapture 2020-08-06 at 11 18 05](https://user-images.githubusercontent.com/876920/89567482-96ba8200-d7d6-11ea-81b2-31f17c6157d5.gif)

doesn't seem to reproduce in latest Insiders

**Closed** 2020-08-06 18:34 UTC
Labels: feature-request, notebook, verification-found, verification-needed

**Comment by rebornix** [comment] 2020-08-06 18:39
Fixing it the third time. cc @roblourens , apparently I didn't handle the drag direction/point well.

There are four scenarios, say we have 7 cells:

```
code 0
markdown header 1
code 1
markdown header 2
code 2
markdown header 3
code 3
```

**Scenario 1**
1. Fold Header 1
2. Drag Header 1 
3. Drop it below Code cell 2, but make sure the cursor is on the bottom half of Code cell 2

![dnd-1](https://user-images.githubusercontent.com/876920/89569069-0b8ebb80-d7d9-11ea-9428-ff0edda20f0f.gif)

**Scenario 2**
1. Fold Header 1
2. Drag Header 1 
3. Drop it above Markdown Header 3, but make sure the cursor is not on Code cell 2

![dnd-2](https://user-images.githubusercontent.com/876920/89569215-3bd65a00-d7d9-11ea-862b-7d6445782303.gif)

**Scenario 3**
1. Fold Header 2
2. Drag Header 2 
3. Drop it above Markdown Header 1, but make sure the cursor is not on Code cell 0

![dnd-3](https://user-images.githubusercontent.com/876920/89569291-5ad4ec00-d7d9-11ea-913e-e273dbe0e964.gif)

**Scenario 3**
1. Fold Header 2
2. Drag Header 2 
3. Drop it below Code cell 0, but make sure the cursor is on the bottom half of Code cell 0

![dnd-4](https://user-images.githubusercontent.com/876920/89569373-78a25100-d7d9-11ea-948c-c5279ab74a44.gif)

**Comment by rebornix** [comment] 2020-08-06 18:41
Since DND is complicated, request @roblourens for verification.
