### ISSUE TITLE
Git Remotes list truncated at spaces in the URL

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#116577] opened 2021-02-12 18:48 UTC
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Place a GIT remote on a UNC or Windows Drive file path that contains spaces.
2. Connect/Clone from that remote.
3. Attempt a Pull From or Push To GIT command via the Source Control panel.

GitLens shows the remote as:
![image](https://user-images.githubusercontent.com/26179051/107809003-1437ef80-6d30-11eb-9339-5d4966fc2c8a.png)
 
The pull from dialog shows:
![image](https://user-images.githubusercontent.com/26179051/107809092-2f0a6400-6d30-11eb-9042-37be7c45f22d.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by lszomoru** [comment] 2022-12-21 12:57
@msftrncs, apologies for not getting back to you on this until now. Since this issue has been filed we have refactored the code that determines the list of remotes. I tried to reproduce the issue with the latest Insiders release (1.75) but I was not able to do so. I will optimistically close this issue as resolved but in case I have missed something and you are still able to reproduce it please feel free to reopen it. Thanks!

**Closed by lszomoru** 2022-12-21 12:57 UTC
Labels: bug, git
