### ISSUE TITLE
md file scroll bug 

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#60541] opened 2018-10-10 18:20 UTC
When scroll up it return automatically down again
![capture](https://user-images.githubusercontent.com/17777237/46757214-cf1bd280-ccc9-11e8-94e4-1f44a8a24260.gif)

**Comment by mjbvz** [comment] 2018-10-10 18:37
What version of VS Code?

**Comment by pixieaka** [comment] 2018-10-10 19:05
@mjbvz
VS Code version: Code - Exploration 1.29.0-exploration (878fda8c5e688a5f01fe16c586ba51c28da325a4, 2018-10-10T05:47:41.620Z)
OS version: Windows_NT x64 10.0.17763

**Comment by charlottetan** [comment] 2018-10-21 19:58
Tried to repro in dev build but didn't manage to, not sure how to get the exploration version?

Version: 1.29.0
Commit: Unknown
Date: Unknown
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by mjbvz** [comment] 2018-10-26 18:52
Duplicate of #61816 + #61815

**Closed by mjbvz** 2018-10-26 18:52 UTC
Labels: bug, markdown
