### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by LiteCat0905** [microsoft/vscode#202274] opened 2024-01-11 19:08 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.3.3

**Steps to reproduce crash**
1.
2.
3.

**Global TS Server Plugins**

- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-bundle`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at InferredProject2.updateGraphWorker (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:177372:11)
    at InferredProject2.updateGraph (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:177231:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:179723:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:181345:12)
    at d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:181575:64
    at flatMap (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:2597:17)
    at _ProjectService.applyChangesInOpenFiles (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:181575:24)
    at updateOpen (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:182773:29)
    at d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:185375:69
    at IpcIOSession.executeWithRequestId (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:185367:14)
    at IpcIOSession.executeCommand (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:185375:29)
    at IpcIOSession.onMessage (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:185417:51)
    at process.<anonymous> (d:\Code\Prudoce\SMusic\node_modules\typescript\lib\tsserver.js:186999:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.60GB free)|
|Process Argv|D:\\Code\\Prudoce\\SMusic --crash-reporter-id 018a2922-3679-4ebe-8fa0-842f4246d1b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
expressjs|ama|2.0.0
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.10.5
EnglishChineseDictionary|Cod|1.1.0
codeium|Cod|1.6.22
fastapi-snippets|dam|0.0.2
vscode-eslint|dba|2.4.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.6
prettier-vscode|esb|10.1.0
go|gol|0.39.1
vscode-django-support|jun|1.0.26
vsc-python-indent|Kev|1.18.0
kether-snippet|Lit|1.0.5
vscode-language-pack-zh-hans|MS-|1.73.11020948
python|ms-|2022.18.2
vscode-pylance|ms-|2023.1.10
cpptools|ms-|1.18.5
sftp|Nat|1.16.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.33.0
platformio-ide|pla|3.3.2
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
naiveui-vscode-snippets|vid|0.0.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
volar|Vue|1.8.17
vscode-typescript-vue-plugin|Vue|1.8.27
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
cloudmusic|YXL|9.19.2
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by mjbvz** [comment] 2024-02-08 01:20
Closing as this is an old VS Code and TS version running a bunch of plugins. It's very likely the issue has already been fixed or is caused by one of those plugins

**Closed by mjbvz** 2024-02-08 01:20 UTC
