### ISSUE TITLE
Vertical margins around lists in jsdoc comments are too large

### ISSUE THREAD

**Issue by weswigham** [Microsoft/vscode#9727] opened 2016-07-26 02:56 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

- Open vscode.
- Paste this into a new buffer:
```ts
interface TypeChecker {
        /**
         * Two types are considered identical when
         *  - they are both the `any` type,
         *  - they are the same primitive type,
         *  - they are the same type parameter,
         *  - they are union types with identical sets of constituent types, or
         *  - they are intersection types with identical sets of constituent types, or
         *  - they are object types with identical sets of members.
         *
         * This relationship is bidirectional.
         * See [here](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.2) for more information.
         */
        isIdenticalTo(a: any, b: any): boolean;
}
```
- Save the file as `example.ts`.
- Mouse over `isIdenticalTo` and see the documentation popup.
- Observe large vertical margins around and within the list.

**Comment by DanielRosenwasser** [comment] 2016-07-26 06:24
Ran into this as well when I started a JSDoc comment with a hyphen and got way too much padding around the text.

**Comment by jrieken** [comment] 2016-08-05 15:34
I know @joaomoreno wanted to or did make that fix already

**Comment by joaomoreno** [comment] 2016-08-08 09:31
Duplicate of #2330

**Closed by joaomoreno** 2016-08-08 09:31 UTC
Labels: polish
