### ISSUE TITLE
drag duplicates text

### ISSUE THREAD

**Issue by Swazimodo** [Microsoft/vscode#63139] opened 2018-11-14 15:19 UTC
Issue Type: <b>Bug</b>

1 - Make a selection
2 - ctrl + h to bring up find and replace
3 - esc to close find and replace
4 - drag text

I expected the selection to move but it was copied instead. I know that this bug has been brought up multiple times but I found new steps to still create it.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (18.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
node-module-in

**Comment by rebornix** [comment] 2018-12-03 17:11
/duplicate of https://github.com/Microsoft/vscode/issues/61867

**Closed** 2018-12-03 17:11 UTC
Labels: *duplicate
