### ISSUE TITLE
Suddenly the text in terminal gets invisible

### ISSUE THREAD

**Issue by alexandis** [microsoft/vscode#112010] opened 2020-12-07 11:28 UTC
Issue Type: <b>Bug</b>

It's a random bug, but I got it several times occasionally. The VS code window gets refreshed, after this whole text in Terminal window gets invisible.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (17.67GB free)|
|Process Argv|--crash-reporter-id 42e80882-db2f-4b0d-8b7e-28ae3df25103|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.2
prettier-vscode|esb|5.8.0
remote-wsl|ms-|0.51.4
vscode-typescript-tslint-plugin|ms-|1.2.3
vscodeintellicode|Vis|1.2.10

</details>

![image](https://user-images.githubusercontent.com/6149843/101345656-0bd6ba80-3890-11eb-9152-83c48ea448a9.png)

**Comment by Devansh2005** [comment] 2020-12-07 11:35
Using the same version of this but not facing such an issue.

**Comment by meganrogge** [comment] 2020-12-07 17:03
Duplicate of #110832

**Closed** 2020-12-07 17:04 UTC
Labels: *duplicate
