### ISSUE TITLE
0.10.10 Dark theme for js is not highlight var and function

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#3810] opened 2016-03-08 07:02 UTC
I think it is not expect behaviour. Other keyword like `if` `else` `return` `while` even `true` `false` `null` is highlighted but `function` and `var` is not

Is it a bug or you have any reason to?

Also `require` should be highlighted too

**Comment by robertftw** [comment] 2016-03-08 08:00
Yep got the same problem!

**Comment by arminas** [comment] 2016-03-08 09:45
This happens only on OSx. On windows 10 highlighter works fine.

**Comment by ndonohoe-bjss** [comment] 2016-03-08 09:57
const, let, class are also not highlighted.

This is happening for me on Windows 7

**Comment by aeschli** [comment] 2016-03-09 09:42
Duplicate of https://github.com/Microsoft/vscode/issues/3903

**Closed by aeschli** 2016-03-09 09:42 UTC
