### ISSUE TITLE
In Explorer, the alphabetical order messed up

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#108242] opened 2020-10-07 10:21 UTC
- VSCode Version: **_1.48.2 zip 64 bit_**
- OS Version: _**Windows 10 Enterprise**_

Steps to Reproduce:

1. In VSCode the **Explorer Sort Order** setting is `default`, so **files** & **folders** should be sorted by their names in alphabetical order.
![image](https://user-images.githubusercontent.com/19678455/95317863-3c32c480-08f2-11eb-9111-bfbc7acac843.png)

2. But in one of my workplaces, it shows a messed order as below. `Digital.Sales` & `Digital.Shared` are placed above `Digital.BusinessType.Api`, the rest are in the right order.
![image](https://user-images.githubusercontent.com/19678455/95318623-4b664200-08f3-11eb-88f7-fc7e9d431ed7.png)

Does this issue occur when all extensions are disabled?: _**Yes**_

**Comment by yume-chan** [comment] 2020-10-14 15:03
Duplicate of #99955

Please update to a newer version.

**Closed** 2020-10-19 10:55 UTC
Labels: *duplicate
