### ISSUE TITLE
Install Helper Tool Install Dialogue Burns CPU/Fans

### ISSUE THREAD

**Issue by ambroselittle** [microsoft/vscode#95534] opened 2020-04-17 14:49 UTC
Issue Type: <b>Bug</b>

1. Leave VS Code open indefinitely (until an update is published).
2. Wait until the dialogue shows that says "VS Code Needs to Install a Helper Tool".
3. Just leave it alone for a bit.

Actual: CPU spikes indefinitely, fans start burning, until you put your password into that dialog.

Expected: Would really prefer it doesn't do this, as sometimes this happens overnight, and it's just killing trees all night long. ;) 

I try to remember to close Code when I go away, but I don't always, and I don't think we should have to. 

BTW, this has happened for a loong time. I just finally got motivated to report. I was kinda surprised not to find it as an open issue, but maybe my search fu is off.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.78GB free)|
|Process Argv|-psn_0_241723|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-icalendar|af4|1.0.1
markdown-toc|Ala|1.5.6
markdown-preview-github-styles|bie|0.1.6
regex|chr|0.2.0
mustache|daw|1.1.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
docthis|joe|0.7.1
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
mssql|ms-|1.9.0
python|ms-|2020.3.71659
azure-account|ms-|0.8.9
vsliveshare|ms-|1.0.2000
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vscode-open-project|sve|0.0.9
tabnine-vscode|Tab|2.6.4
vscode-icons|vsc|10.1.1
wallaby-vscode|Wal|1.0.195
glean|wix|4.21.1
propertylist|zho|0.0.2

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment] 2020-04-20 12:50
> VS Code Needs to Install a Helper Tool

Does this appear if you run with `code --disable-extensions`?

**Comment by ambroselittle** [comment] 2020-04-20 15:13
This only happens when Code is running and finds that it needs an update. Then it shows the dialog for the VS Code Install Helper Tool, and it's that dialog, if left open, that seems to cause the spike. This is not during normal usage. It's part of the update process.

I just loaded with no extensions, but unless I wait until an update is released like that, it won't verify the behavior. Since this is about the updater for Code itself, it seems strange that it would be related to extensions.

**Comment by joaomoreno** [comment] 2020-04-23 09:49
@deepak1556 Since this is macOS, is related to the Squirrel framework shipped with Electron. Have you see this before?

**Comment by ambroselittle** [comment] 2020-04-23 20:38
I have seen this consistently with VS Code, but maybe only because I use it more than other electron-based apps. Not really sure, TBH. 

Are you suggesting I file this issue with them?

**Comment by joaomoreno** [comment] 2020-04-27 14:42
> I have seen this consistently with VS Code, but maybe only because I use it more than other electron-based apps. Not really sure, TBH.
> 
> Are you suggesting I file this issue with them?

It wouldn't hurt!

**Comment by anaisbetts** [comment] 2020-04-27 17:43
You're seeing this dialog in the first place because VS Code has broken permissions, if you fix them you won't ever see it again! ✨   Make sure that VS Code.app is owned by your user and not `root` or some other user account

**Comment by ambroselittle** [comment] 2020-04-27 17:53
@anaisbetts, thanks for the suggestion. Just tried chowning. Will see if I never see it again. :D Or at least not at the next update.

**Comment by deepak1556** [comment] 2020-04-27 18:06
@ambroselittle here is an insiders version from few days ago https://az764295.vo.msecnd.net/insider/a250df703de955a38aed427a917bce8278ab3331/VSCode-darwin-insider.zip which will trigger an update once you launch it. You can test if the issue is mitigated with correct user permissions for the app.

**Comment by ambroselittle** [comment] 2020-04-27 19:08
@deepak1556, I'm gonna ask a dumb question. That gives me a new insiders copy of the app, from what I can tell. How will it test that my mainline copy is now configured correctly?

**Comment by deepak1556** [comment] 2020-04-27 20:07
Sorry I wasn't clear, I would like you to install the app as another user that would trigger the install helper tool and see the cpu usage increases.

Reinstall the app again as above, but before opening the app change permissions like you did for the mainline copy, open the app and see if the update no longer causes an issue.

This would verify what you did for your mainline copy. Also double-check permissions match for 

```
/Applications/Visual\ Studio\ Code.app
/Applications/Visual\ Studio\ Code\ -\ Insiders.app

~/Library/Caches/com.microsoft.VSCode.ShipIt
~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt
```

**Comment by ambroselittle** [comment] 2020-04-28 14:06
OK. I put that in /Applications and chowned it as root. 

I opened. Clicked Open (security dialog). Waited.

In a short bit, the dialog showed:
![install-helper-prompt](https://user-images.githubusercontent.com/2660021/80496901-cafce780-8937-11ea-861f-0b2e777046a4.jpg)

And accordingly, CPU usage spiked, and fans kicked in as usual.
![install-helper-burning](https://user-images.githubusercontent.com/2660021/80496968-d6e8a980-8937-11ea-838d-3e0db09facb2.jpg)

I will try as myself and see how it goes.

**Comment by ambroselittle** [comment] 2020-04-28 14:13
I quit the Insiders copy. Then I chowned it back to my user. 

Ran again. After a few seconds, it showed the little history icon over the gear icon, then showed a 1 badge (for update).

I clicked and chose restart to update. And it's OK. No dialog. No burning CPU. So I guess that's definitely the source of the issue. I wonder if there's a way to proactively let people know about this, like check the owner of the app and show a dialog? (Not sure offhand if that's doable. just throwing it out there.)

Anyhow, I'll assume for now that this is fixed until the next mainline update re-confirms. If it does it again, I'll let you know. Thanks for the help.

**Comment by ambroselittle** [comment] 2020-04-28 14:16
Just for anyone else who comes across this and may not be up to speed on the commands.. in Terminal (or similar):
```bash
cd /Applications
sudo chown -R [your username here] Visual\ Studio\ Code.app
```
That's assuming your copy is in /Applications, of course. HTH.

**Comment by ambroselittle** [comment] 2020-05-06 14:21
I noticed the same thing happened on MS Teams. So I looked, and yup, it was root, as well. chowned that baby as well. Thanks again for the workaround @anaisbetts.

**Comment by dannystaple** [comment] 2021-04-01 08:13
I noticed in my case it was all owned by user "root". I've chmodded, but with the additional change of group. I have 2 primary users on this mac, with a shared "brew" user (due to homebrew ownership issues), so putting this as brew owned should help. I also need to ensure the group as the same permissions as the user. At least rw for all files.

**Comment by deepak1556** [comment] 2021-06-21 04:00
Upstream issue https://github.com/electron/electron/issues/29119

**Comment by joel-g** [comment] 2021-06-28 20:14
> @deepak1556 Since this is macOS, is related to the Squirrel framework shipped with Electron. Have you see this before?

I'm experiencing this issue on macOS with VS Code _and_ Signal

**Comment by deepak1556** [comment] 2021-07-28 23:23
This should now be addressed in latest insiders and upcoming stable release `1.59`

**Closed by deepak1556** 2021-07-28 23:23 UTC
Labels: fixed-in-electron-13, install-update, macos, upstream, upstream-issue-fixed
