### ISSUE TITLE
environment variables are empty when executing tasks

### ISSUE THREAD

**Issue by dominikschreiber** [Microsoft/vscode#71786] opened 2019-04-05 10:28 UTC
Issue Type: <b>Bug</b>

After updating to VSCode March 2019 (stable, tested on macOS and on Windows), environment variables used in task definitions are no longer resolved, they are emptystring instead.

Consider the following tasks.json:

```json
{
  "version": "2.0.0",
  "tasks": [{
    "label": "echo",
    "type": "shell",
    "command": "echo $HOME == ${env:HOME}",
    "problemMatcher": []
  }]
}
```

*expected:* `/Users/me == /Users/me`
*actual:* `/Users/me ==`

This renders all tasks unuseable that in any way rely on environment variables directly (e.g. starting a tomcat via `${env:CATALINA_HOME}/bin/startup.sh`).

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (17.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.2
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
vsc-material-theme|Equ|2.8.2
nasc-touchbar|fel|1.12.0
beautify|Hoo|1.4.11
java-properties|ith|0.0.2
vscode-jsp|pth|0.0.2
rust|rus|0.6.1
perforce|sle|3.1.0

(2 theme extensions excluded)

</details>

**Comment by sleutho** [comment] 2019-04-05 14:32
Same on Windows 10. Breaks all my tasks (C++/make related tasks) and cripples VSCode as an IDE for me.

Version: 1.33.0 (user setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by sleutho** [comment] 2019-04-05 14:37
Duplicate of 71740

**Closed** 2019-04-06 01:49 UTC
Labels: *duplicate, new release
