### ISSUE TITLE
Setting sync: turn off syncing on all machine and clear cloud 404

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#104007] opened 2020-08-04 22:48 UTC
Testing #103604

Get `Server returned 404` error when trying to turn off syncing on all machine without any actionable suggestion.

**Comment by sandy081** [comment] 2020-08-05 07:57
@rebornix I am not able to reproduce this. Are there any specific steps I have to follow or may be you have a special set up?
If you can repro it can you please try it again by setting log level to trace and provide me the Settings Sync log from output channel?

**Comment by 9at8** [comment] 2020-08-05 14:25
I was seeing this as well, couldn't reproduce it deterministically :cry:

**Comment by sandy081** [comment] 2020-08-05 15:55
I am not able to speculate when this can happen.

@Tyriar any guess when server return's 404?

@rebornix @9at8 May I know when you are seeing this error? Are you performing any action?

**Comment by rebornix** [comment] 2020-08-05 16:20
@sandy081 I was testing the sign out feature a couple of times, but at the beginning I didn't check off the "turn off syncing on all machine". After testing the other features, I did that once, but then I got 404, and then everything went well.

**Comment by 9at8** [comment] 2020-08-05 16:20
Ah, I can repro now.

0. Turn on sync
1. "Show synced data"
2. Click on the '...' menu -> "Clear data in cloud"
3. Once the data is cleared, activity doesn't go away
4. Click on activities
5. Get 404

**Comment by sandy081** [comment] 2020-08-05 16:34
Seems duplicate of 103985

**Closed** 2020-08-05 16:35 UTC
Labels: *duplicate
