### ISSUE TITLE
Updating to vscode alpha breaks my command line shrotcut

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2314] opened 2016-01-26 11:55 UTC
I guess this is as designed, but should we somehow improve this experience?
Windows.

![image](https://cloud.githubusercontent.com/assets/1926584/12579941/f0de0b08-c42b-11e5-9609-16f45e790013.png)

**Comment by joaomoreno** [comment] 2016-01-26 13:45
Duplicate of #2127

**Closed by joaomoreno** 2016-01-26 13:45 UTC
