### ISSUE TITLE
JSON language server spawns zombie processes on large files

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#55182] opened 2018-07-26 19:02 UTC
- VSCode Version: 1.26-insiders

Steps to Reproduce:

1. Open a large json file (extensions/markdown-basics/syntaxes/markdown.tmLanguage.json for instance)
2. Outline view wont populate, Folding markers wont show up, if you try to naviage to another json file those markers wont show up either

If you try just changing the extension to `.ts`, everything is more or less instant. 

Edit: mentioned below, but bringing up for visibility... when this happens, the server also spawns a process which does not terminate when Code is closed, and will use up all of the available compute. Each time a you open and close Code a seperate new process is formed

**Comment by aeschli** [comment] 2018-07-30 20:16
I tried to reproduce with `extensions/markdown-basics/syntaxes/markdown.tmLanguage.json` but I don't see any slowness:
![json-folding](https://user-images.githubusercontent.com/6461412/43421179-3aebc22a-9446-11e8-90c3-bc8ea58e4f4d.gif)

**Comment by JacksonKearl** [comment] 2018-07-30 20:46
Doesnt always repro for me but here's a demo of what happens when it does.
![slowjson](https://user-images.githubusercontent.com/8586769/43422486-b22b3692-93fe-11e8-9650-017ed1562f47.gif)

Notice the outline view never loads. I've also seen the outline view say that there is no editor that can provide an outline when opening this json file. And when I repeatedly open and close Code with this file, there is a process that never terminates, so after a few rounds I was able to get up to 8 different processes in my task manager, combined using all of my CPU, even when I had closed out of all code windows

**Comment by aeschli** [comment] 2018-07-31 09:57
Cab you set `"json.trace.server": "verbose"' and open the output view for the JSON language server to see what's going on?

**Comment by JacksonKearl** [comment] 2018-08-10 18:19
[dfasdf.txt](https://github.com/Microsoft/vscode/files/2279034/dfasdf.txt)
![image](https://user-images.githubusercontent.com/8586769/43974352-25481bfc-9c8f-11e8-81e3-b7fc7dc462b0.png)
It doesn't seem out of the ordinary. I notice the folding range computation says it took a few ms, but in the outline view I saw it loading for several seconds

**Comment by aeschli** [comment] 2018-09-14 08:10
Closing, I'm not able to reproduce. If you still see this then it would be great if you can take a profile.

**Closed by aeschli** 2018-09-14 08:10 UTC
Labels: editor-folding, json
