### ISSUE TITLE
Suggestion: configurationDefaults should be indicated in each language section

### ISSUE THREAD

**Issue by soulchainer** [Microsoft/vscode#21902] opened 2017-03-03 15:41 UTC
There's a recent section in the `settings.json` file for overwrite `editor` defaults for specific languages.
An specific and isolated section just for that.

```json
  "[go]": {
    "editor.insertSpaces": false
  },

  "[makefile]": {
    "editor.insertSpaces": false
  },

  "[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  },

  "[yaml]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2
  },
```

I think this is a bit counterintuitive.
If you want to change something specifically related to Markdown, the logic will make you to check the markdown section. Because you want to change some behaviour related to that kind of files. The same applies to the rest of languages. That was my case. I didn't knew about this specific overwritting and I went a little crazy when I updated my default editor config `editor.wordWrap` and it was working in all files... but markdown ones. So I quick checked the issues here and, eventually, I found in the code that there is an specific override for markdown files... in a section apart.

Even if you know about this section, it seems like a problem. Now, even if there isn't any overwritting at all for your specific language, you will need to check also that isolated section «just in case» there is something new overwritting anything that you aren't aware of.

Don't you think that having all the settings about a language in the language section is a better approach? As example, something like this, for the Markdown section:

```json
  "markdown.styles": [],
  "markdown.previewFrontMatter": "hide",
  "markdown.preview.fontFamily": "'Segoe WPC', 'Segoe UI', 'SFUIText-Light', 'HelveticaNeue-Light', sans-serif",
  "markdown.preview.fontSize": 14,
  "markdown.preview.lineHeight": 1.6,
  "markdown.preview.scrollPreviewWithEditorSelection": true,
  "markdown.preview.markEditorSelection": true,
  "markdown.preview.scrollEditorWithPreview": true,
  "markdown.preview.doubleClickToSwitchToEditor": true,
  ...
  "[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  },
```

**Note**: comments omitted for the sake of brevity.

**Comment by sandy081** [comment] 2017-03-06 09:05
@soulchainer I take your feedback and agreed that there is not a good way to know what settings are being applied to the editor. You see this issue through language settings but this issue exists at other places too.

- Workspace settings
- Extensions like Editor config
- In memory configurations (toggle word wrap functionality)

Showing language specific settings in the language section might not solve all. Still user not aware of this concept (lang spec settings) will be still clueless what are the sources of a particular setting. So, IMO I think we need a concept of Editor settings preview showing the settings applied to current editor and what are their sources? This will help user understanding about where settings are coming from and able to update/configure them. What do you think?

Thanks

**Comment by soulchainer** [comment] 2017-03-06 11:17
Well, I put it that way because I stumbled on it when I was editing markdown files, but yes, of course: I think you're right.
As long as we have an obvious place were we can see all the settings applied to the current editor in a practical fashion, it'll be great :D.

**Comment by sandy081** [comment] 2017-03-09 09:01
Created a separate issue for Editor settings preview. I would take your suggestion here to show lang specific settings to show close to the lang section.

**Comment by sandy081** [comment] 2017-11-15 14:34
Root cause of this issue is #22283 and left this to handle ordering of the settings. Current grouping of settings is good enough and changing it is not often requested. Hence closing this feature request.

**Closed by sandy081** 2017-11-15 14:34 UTC
Labels: editor, feature-request, settings, workbench
