### ISSUE TITLE
Previewing an MD file with a .gif image in it crashes the window

### ISSUE THREAD

**Issue by alexhx5** [microsoft/vscode#66495] opened 2019-01-14 16:22 UTC
- VSCode Version: 1.30.2
- OS Version: Win10

Steps to Reproduce:

1. Create an `.md` file
2. Put in a link to an existing `.gif` image. For example: `![](./test.gif)`
3. Open preview `ctrl + shift + v`

Does this issue occur when all extensions are disabled?: Yes

## UPDATE:
Crash happens when you try to display big images. The limit is somewhere in range between 100mb and 250mb (100mb images do not crash the window)

**Comment by mjbvz** [comment] 2019-01-14 16:23
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by AlexSHoffman** [comment] 2019-01-14 16:36
@mjbvz yes, just checked, it does reproduce in `1.31.0 insider x64 win10` build

**Comment by mjbvz** [comment] 2019-01-14 16:39
Do all gifs cause this problem or just one gif in particular?

**Comment by AlexSHoffman** [comment] 2019-01-14 16:41
@mjbvz initially I got a crash with a gif of 250mb in size. I just rechecked it with a smaller (100kb) gif it works fine. So it looks like there's a limit. Is that intentional?

**Comment by AlexSHoffman** [comment] 2019-01-14 16:43
@mjbvz initially I got a crash with a gif of 250mb in size. I just rechecked it with a smaller (100kb) gif it works fine. So it looks like there's a limit somewhere in the region <250mb.

Is that intentional? It worked before in the older VScode builds

**Comment by mjbvz** [comment] 2019-01-14 19:12
That's a large gif but we should never crash.

Can you please try collecting some information about the crash by following these instructions: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows

**Comment by bpasero** [comment] 2019-01-15 09:16
Possibly just an out of memory crash?

**Comment by AlexSHoffman** [comment] 2019-01-15 11:19
@mjbvz @bpasero right after you open the preview  VSCode quickly takes up several GB of RAM and crashes a few seconds later.

Here's an `.md` file and large `.gif` so you guys can see what I'm seeing:

https://drive.google.com/open?id=1OcKI3EMj776fE9JEQ9XjndA4pra_lE2D

**Comment by bpasero** [comment] 2019-01-15 13:46
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by AlexSHoffman** [comment] 2019-01-15 13:50
@bpasero I did, as I mentioned above, nothing changes

**Comment by bpasero** [comment] 2019-01-15 14:54
I have seen before that loading media resources within the renderer consumes crazy amount of memory, even for smaller images. That is why I added a size limitation (e.g. you cannot open images > 1 MB). Of course this limitation does not exist for webviews, and I do not think we could easily add it.

**Comment by AlexSHoffman** [comment] 2019-01-15 16:19
@bpasero what does it do during that "preview" generation process that requires it to take up so much memory? Why doesn't it just display the images on the page using an `<img>` tag?

**Comment by AlexSHoffman** [comment] 2019-01-15 16:33
@bpasero hmm, I don't get it, I've never seen this behavior. I'm building an Electron app that also has a main and a renderer processes and it displays tens of images (of any size: 30mb, 100mb, 250mb what have you) on the page just like a normal browser does.

**Comment by bpasero** [comment] 2019-01-15 16:48
@AlexSHoffman can you try to reproduce it with a bare Electron app and a webview?

**Comment by AlexSHoffman** [comment] 2019-01-15 17:23
@bpasero Bare in mind I'm not a professional developer, I'm, probably doing something wrong. But:

I just created a new `electron-quick-start` project and displayed a large gif:
```HTML
<img src="C:\test.gif" alt="" style="width:100%">

<webview id="foo" src="C:\test.gif" style="width:100%"></webview> 
```
Image `test.gif` is `240mb` in size. I don't know what I'm doing wrong but it takes up 1:1 amount of RAM:

![1](https://user-images.githubusercontent.com/13764106/51197571-fdc9ca80-1902-11e9-801b-f7bfe0450146.jpg)

**Comment by bpasero** [comment] 2019-01-16 08:41
@AlexSHoffman thanks. It is possible that the way we hookup the webview makes a difference. I leave it up to @mjbvz to comment on that.

I can easily reproduce the crash with your sample on macOS btw, thanks for providing the files.

**Comment by mjbvz** [comment] 2019-10-10 22:59
@deepak1556 Related to this: we probably should use streams for loading content inside of webviews. This is currently blocked by https://github.com/electron/electron/issues/17059

**Comment by deepak1556** [comment] 2021-03-12 02:00
@mjbvz the upstream issue has been closed as the scenario is no longer valid, protocol subscriptions now happen in the main process so hopefully this issue is unblocked.

**Comment by mjbvz** [comment] 2021-05-22 00:04
I just tested this using the linked gif and it seems to work fine now:

![Screen Shot 2021-05-21 at 5 01 52 PM](https://user-images.githubusercontent.com/12821956/119208273-460ad180-ba56-11eb-9972-730f5489fc43.png)

The gif is 250MB so there's still memory usage, but I don't see it ballooning to multiple GB for a simple case and don't see a crash

**Closed by mjbvz** 2021-05-22 00:04 UTC
Labels: confirmed, electron, freeze-slow-crash-leak, upstream, webview
