### ISSUE TITLE
macOS: Unable to quit when all windows are closed

### ISSUE THREAD

**Issue by jungaretti** [microsoft/vscode#172967] opened 2023-01-31 21:25 UTC
Type: <b>Bug</b>

VS Code has trouble quitting with the `cmd+Q` shortcut on macOS. When I use `cmd+Q` quickly after `cmd+shift+W`, VS Code hangs and remains open. I can tell that VS Code is open by the indicator dot under its icon in the dock.

Steps to reproduce:
1. Open VS Code on macOS
2. Use `cmd+shift+W` to close all windows
3. Quickly use `cmd+Q` to quit VS Code
4. Notice that the "Code" title in the macOS menubar flashes
5. Notice the dot under VS Code's icon in the dock and that VS Code remains open

I've seen this bug in both VS Code stable and insiders.

Here's a screen recording of this bug:

https://user-images.githubusercontent.com/19893438/215887767-4a78d24c-8c30-4344-b56a-f0061edbbad7.mp4

Notice how the "Code" title in the menubar flashes as the windows close. It seems like VS Code is receivng the quit event, but it's getting stuck somewhere.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (36.59GB free)|
|Process Argv|--crash-reporter-id 3488aeac-bc57-46d3-ac1a-73d78d4582d6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30647091
89544117:30613380
2i9eh265:30646982

```

</details>

**Comment by jungaretti** [comment] 2023-01-31 21:35
https://github.com/microsoft/vscode/issues/172846 may be related to this bug.

**Comment by VincentDondain** [comment] 2023-01-31 22:04
Something similar happens to me when I update my VSCode insider, the editor restart after the update and I do not have the close buttons anymore in the UI, nor can I quit the program with cmd + Q, I need to force quit it.

**Comment by bpasero** [comment] 2023-02-01 05:12
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jungaretti** [comment] 2023-02-01 05:56
Here's a repro with insider:

https://user-images.githubusercontent.com/19893438/215963196-21e101c9-aec7-48b6-9a2e-18fce8de9639.mp4

Version: 1.75.0-insider (Universal)
Commit: 0615c4f98b07b51d3be6a357e22afec119490c5a
Date: 2023-01-31T00:09:14.434Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by bpasero** [comment] 2023-02-01 06:18
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by jungaretti** [comment] 2023-02-01 06:27
I see the same behavior with `code-insiders --disable-extensions --user-data-dir <directory>`

https://user-images.githubusercontent.com/19893438/215967918-1ecf1138-1a94-4ce6-b762-4f4caf83b826.mp4

**Comment by bpasero** [comment] 2023-02-01 06:39
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by jungaretti** [comment] 2023-02-01 06:56
Here's the complete output of `code-insiders --disable-extensions --user-data-dir /var/folders/2g/cjbxg4p94_925xh94s396hth0000gn/T/tmp.kxnJXdZL --verbose &> quit-failed-log.txt`

[quit-failed-log.txt](https://github.com/microsoft/vscode/files/10554036/quit-failed-log.txt)

I see `CommandService#executeCommand workbench.action.closeWindow"` on line 472 and `CommandService#executeCommand workbench.action.quit"` on line 483. It looks like VS Code is hearing both `cmd+shift+W` and `cmd+Q`. I think the problem must come from the `workbench.action.quit` command.

**Comment by bpasero** [comment] 2023-02-01 07:09
Yeah so if `workbench.action.closeWindow` command runs, then you are basically left with a VS Code app that still runs but has no windows opened. But that should not be a command that runs by default, unless you have keyboard shortcuts defined that are any different from the defaults?

**Comment by jungaretti** [comment] 2023-02-01 07:16
All of my screen recordings show `cmd+shift+W` followed by `cmd+Q`. That's my daily flow and I encounter this bug most when following it. Sorry if that wasn't clear.

`cmd+Q` alone feels more reliable than `cmd+shift+W` followed by `cmd+Q`. Here are the logs from using just `cmd+Q` where VS Code quits properly:

[quit-success.txt](https://github.com/microsoft/vscode/files/10554182/quit-success.txt)

These logs look different than the failure logs. I don't see `closed application storage` in the logs where VS Code didn't quit properly.

**Comment by jungaretti** [comment] 2023-02-01 07:18
Maybe there's a race condition between `workbench.action.closeWindow` and `workbench.action.quit` when closing the folder/workspace? I don't see `Request to stop watching` or `stopping file watcher` in the failure logs.

**Comment by bpasero** [comment] 2023-02-01 07:39
Oh, what? You press `Cmd+Shift+W` and then `Cmd+Q`? Would have really helped to indicate this in the beginning.

How fast do you press the one after the other?

**Comment by jungaretti** [comment] 2023-02-01 08:03
> Oh, what? You press `Cmd+Shift+W` and then `Cmd+Q`? Would have really helped to indicate this in the beginning.

My steps to reproduce include the `cmd+shift+W` step, but my description wasn't accurate. I just edited the issue for clarity.

**Comment by jungaretti** [comment] 2023-02-01 08:06
> How fast do you press the one after the other?

I use `cmd+Q` less than 1 second after `cmd+shift+W`. I can still repro this bug with a ~2 second delay. Please check the logs for more detailed timestamps.

**Comment by jungaretti** [comment] 2023-02-01 08:10
Here are logs from a case where quitting failed, but I didn't have a specific folder/workspace open:

[empty-folder-failure.txt](https://github.com/microsoft/vscode/files/10554713/empty-folder-failure.txt)

**Comment by klaussner** [comment] 2023-02-01 18:07
Here's another screen recording in case it helps.
- The time between closing the window and quitting the application doesn't seem to matter.
- After quitting, you can click on the app icon to open another window, but the menu is missing several items.
- Closing the new window immediately quits the application.

https://user-images.githubusercontent.com/1312807/216125156-8a5991b7-65cc-4aa9-809b-971a5d5b1bac.mp4

**Comment by jungaretti** [comment] 2023-02-01 18:32
Nice catch! It seems like closing all of the windows before quitting plays a role, but you don't need to use `cmd+shift+W` or quit immediately after closing them.

**Comment by jungaretti** [comment] 2023-02-01 18:38
I'm able to repro with the steps from @klaussner's recording. Here's another recording an its logs:

https://user-images.githubusercontent.com/19893438/216132775-7b0e71fc-b825-45c9-b162-194ebf7b6f91.mp4

[vscode-not-quitting-clicks.txt](https://github.com/microsoft/vscode/files/10560396/vscode-not-quitting-clicks.txt)

**Comment by bpasero** [comment] 2023-02-02 05:06
I cannot reproduce that flow. What is your macOS versions?

**Comment by bpasero** [comment] 2023-02-02 05:08
![Recording 2023-02-02 at 06 07 59](https://user-images.githubusercontent.com/900690/216236729-3c08c754-3489-40a3-82d7-49cbb98babcc.gif)

You possibly have some 3rd party tool installed that triggers this, can you check.

**Comment by bpasero** [comment] 2023-02-02 05:12
I wonder if waiting longer (20 seconds) eventually terminates VS Code after you selected "Quit" or will it never?

**Comment by klaussner** [comment] 2023-02-02 06:37
> I cannot reproduce that flow. What is your macOS versions?

13.1 (22C65), running on M1 and M2.

> I wonder if waiting longer (20 seconds) eventually terminates VS Code after you selected "Quit" or will it never?

I waited for a few minutes, but the app didn't terminate. I also tried to focus/open other apps after quitting VS Code but that didn't have any effect.

**Comment by bpasero** [comment] 2023-02-02 06:42
I am on 12.x but I think @jungaretti is as well, so this does not look like a macOS Ventura regression. Can you confirm?

**Comment by jungaretti** [comment] 2023-02-03 06:34
Yep, I'm on 12.6.3.

**Comment by jungaretti** [comment] 2023-02-03 06:38
> I waited for a few minutes, but the app didn't terminate. I also tried to focus/open other apps after quitting VS Code but that didn't have any effect.

Same here. I've seen it remain in limbo for an entire afternoon (>3 hours).

**Comment by bpasero** [comment] 2023-02-03 06:47
Wondering if other apps exhibit the same behaviour: Chrome?

**Comment by klaussner** [comment] 2023-02-04 12:44
I found out a few more things:
- It looks like the app terminates if a second VS Code window is opened before quitting (shown in the video below).
- I haven't been able to reproduce the issue with a custom build of the latest OSS version (also shown in the video).
- If a new window is opened after a failed attempt to quit VS Code, the following errors appear in the console:

```
ERR [uncaught exception in main]: Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at h (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:5995:17)
    at E.connect (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:35860:45)
    at async E.t (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:35688:23)
ERR Error received from starting extension host (kind: LocalProcess)
ERR Canceled: Canceled
    at w (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:989:19)
    at Pt.createExtensionHost (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:32864:46)
    at Object.call (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:15531:26)
    at u.s (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:15078:20)
    at u.q (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:15032:22)
    at /Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14983:53
    at p.invoke (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9048:25)
    at m.deliver (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9160:26)
    at a.fire (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9133:48)
    at /Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:8710:45
    at p.invoke (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9048:25)
    at m.deliver (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9160:26)
    at a.fire (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9133:48)
    at /Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:8731:54
    at p.invoke (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9048:25)
    at m.deliver (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9160:26)
    at a.fire (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:9133:48)
    at j (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:8886:35)
    at IpcMainImpl.g (/Users/christian/Desktop/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:7200:29)
    at IpcMainImpl.emit (node:events:526:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:169:11430)
    at EventEmitter.emit (node:events:526:28)
```

The first error references this line, where `this.window` is `undefined`:

https://github.com/microsoft/vscode/blob/7606e812a6f8d437e4cf51eca2cbb7950c3c21b9/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L293

I commented out the body of the `connect` function in the Insiders build to see if the error is related to the issue and it looks like the app always terminates if the error isn't thrown.

https://user-images.githubusercontent.com/1312807/216768205-9e56533d-352a-4a86-88a1-878eb2337888.mp4

**Comment by bpasero** [comment] 2023-02-04 15:00
When the quit sequence starts, we bring down critical pieces needed to run VS Code, including the shared process. So I am not that surprised that there are errors popping up after the quit sequence has started when then a new window is attempted to open.

We still have to figure out the reason why VS Code would not just terminate when quitting with no windows. I wonder which processes are still running then, can people do an htop?

**Comment by jungaretti** [comment] 2023-02-07 19:28
Here's the output of `ps -e` (and logs) that I captured while `code-insiders` was in limbo:

[ps.txt](https://github.com/microsoft/vscode/files/10678714/ps.txt)
[ps-quit-failed.txt](https://github.com/microsoft/vscode/files/10678713/ps-quit-failed.txt)

**Comment by bpasero** [comment] 2023-02-08 16:31
Thanks, there is a strange log at the end:

```
[90m[main 2023-02-07T19:26:03.812Z][0m StorageMainService: closed workspace storage (1675797962181)
[90m[main 2023-02-07T19:26:03.813Z][0m StorageMainService: closed application storage
[90m[main 2023-02-07T19:26:03.828Z][0m Lifecycle#app.on(will-quit)
[7104:0207/112603.811084:INFO:CONSOLE(37)] "%cTRACE color: #888 Lifecycle#onWillShutdown.fire()", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (37)
[90m[main 2023-02-07T19:26:31.271Z][0m update#checkForUpdates, state =  idle
```

Basically, we want to quit (`will-quit`), but something holds this so that even an update check can run after.

https://github.com/microsoft/vscode/pull/173833 adds more logging to identify which component may block the quit from happening, but it requires another insiders so we wait until tomorrow and then I ping you back to try.

I think by now it is evident that only very few users are impacted, so it must be a setup/configuration issue that we have not understood yet.

**Comment by bpasero** [comment] 2023-02-09 09:04
@jungaretti can you try again to send me logs from todays insider? The version is `853b32bad26ed5ffe2d29b95be45adc7f753e35a`

**Comment by jungaretti** [comment] 2023-02-09 18:02
[853b32bad26ed5ffe2d29b95be45adc7f753e35a-failure.txt](https://github.com/microsoft/vscode/files/10700197/853b32bad26ed5ffe2d29b95be45adc7f753e35a-failure.txt)

https://user-images.githubusercontent.com/19893438/217898932-bc35e364-c295-43a2-aa84-679f6e038491.mp4

```
Version: 1.76.0-insider (Universal)
Commit: 853b32bad26ed5ffe2d29b95be45adc7f753e35a
Date: 2023-02-09T05:23:48.935Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by bpasero** [comment] 2023-02-10 06:57
@jungaretti thanks, so we actually do end up calling `app.quit` here:

https://github.com/microsoft/vscode/blob/9f0d458c211ed2da1b1e180545c8640a856dfb05/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L313

Not clear to me though why that would be prevented, because at that time no window is opened other than the hidden "shared process" window. I wonder if that possibly prevents the shutdown.

In the scenario where VS Code refuses to quit can you run this:

```
ps aux | grep vscode-window-kind=shared-process
```

And see if there is a process returned? If so, that would indeed indicate that the hidden shared process window prevents the shutdown.

**Comment by jungaretti** [comment] 2023-02-10 18:00
Done. Here are my logs and `ps aux` output. `ps aux` does return a process.

[hidden-shared-process-ps-aux.txt](https://github.com/microsoft/vscode/files/10710004/hidden-shared-process-ps-aux.txt)
[hidden-shared-process-logs.txt](https://github.com/microsoft/vscode/files/10710003/hidden-shared-process-logs.txt)

**Comment by bpasero** [comment] 2023-02-10 19:10
Ok thanks, the shared process does not seem to be running anymore, as expected.

Just to clarify: in all the examples and reproduces above, you tried with right-click "Quit" from the dock icon when no window was opened?

Btw I am somewhat able to reproduce the original issue when quickly closing all windows and then quitting. So I may be able to fix that, but I feel in the end we have 2 separate issues here actually.

**Comment by jungaretti** [comment] 2023-02-14 20:32
> Just to clarify: in all the examples and reproduces above, you tried with right-click "Quit" from the dock icon when no window was opened?

I usually use `cmd`+`shift`+`W` to close all of the windows and `cmd`+`Q` to quit VS Code. @klaussner's first recording shows right clicking "Quit" from the dock.

It seems like speed is an important piece of this puzzle: the more quickly you quit VS Code after closing all windows, the more likely you are to see the bug. That's why I see it so often when using the keyboard shortcuts.

Why do you think there are 2 separate issues?

**Comment by bpasero** [comment] 2023-02-15 05:49
Because if timing is involved for the keybindings and using the dock works consistently then I was wondering if the keybinding thing is a race condition in our code and the other an issue maybe even deeper in Electron.

Btw I am no longer able to reproduce the issue with keybindings I had seen before.

Sorry, I am at the end of knowledge how to proceed here.

@deepak1556 would it help to do a Chrome trace to diagnose what happens after we call `app.quit()` and if so, what filters would we need?

**Comment by klaussner** [comment] 2023-02-15 22:36
After looking into it further, I'm pretty sure that this issue is related to telemetry (which would explain why I couldn't reproduce it with the OSS build). If telemetry is disabled with `"telemetry.telemetryLevel": "off"`, VS Code always quits as expected.

To track down where the problem was introduced, I binary searched through Insiders builds released between January 2022 (where I found a working version) and today. This is the result:

- Last good build (July 6, 2022): [Download](https://vscode.blob.core.windows.net/insider/9c5408c04a614e641d7a69680686cb9346e0d7a8/VSCode-darwin-arm64.zip) | [Commit](https://github.com/microsoft/vscode/commit/9c5408c04a614e641d7a69680686cb9346e0d7a8)
- First bad build (July 7, 2022): [Download](https://vscode.blob.core.windows.net/insider/bc0bdc5d0969030f114d5931b18e134059da00c1/VSCode-darwin-arm64.zip) | [Commit](https://github.com/microsoft/vscode/commit/bc0bdc5d0969030f114d5931b18e134059da00c1)

The [changes between these two versions](https://github.com/microsoft/vscode/compare/9c5408c04a614e641d7a69680686cb9346e0d7a8..bc0bdc5d0969030f114d5931b18e134059da00c1) include a few changes to telemetry, but I'm not familiar enough with VS Code internals to find out what exactly causes the problem.

**Comment by bpasero** [comment] 2023-02-16 04:30
I would be a bit surprised that having an impact, but @jungaretti maybe you can test with telemetry turned off.

**Comment by jungaretti** [comment] 2023-02-17 01:03
Disabling telemetry with `"telemetry.telemetryLevel": "off"` fully resolved the issue for me. I tried 120 times in a row and didn't see the bug at all. Nice find @klaussner, you're a legend!

**Comment by jungaretti** [comment] 2023-02-17 01:13
You two may ask yourselves, "How did he try it 120 times in a row?"

**Good news, I figured out a way to consistently repro this bug!** I wrote a script that opens VS Code, sends the `cmd`+`shift`+`W` shortcut to close all windows, sends a quit event, and checks if VS Code is still running. Check it out:

https://user-images.githubusercontent.com/19893438/219523168-ab6d789c-f5e7-4cf7-bcae-6fa545b4a9b4.mp4

Here are the results for our two telemetry cases:
- [results-with-telemetry.txt](https://github.com/microsoft/vscode/files/10762269/results-with-telemetry.txt)
- [results-disabled-telemetry.txt](https://github.com/microsoft/vscode/files/10762266/results-disabled-telemetry.txt)

Disabling telemetry fully eliminates the bug.

GitHub won't let me share the `.scpt` file, but you can use `Script Editor` on macOS to run it: [measure-code.txt](https://github.com/microsoft/vscode/files/10762279/measure-code.txt)

1. Download [measure-code.txt](https://github.com/microsoft/vscode/files/10762279/measure-code.txt)
2. Open `Script Editor`
3. Copy and paste the script into the editor
4. Show the log view
5. Switch to the `Messages` tab
6. Run the script

If you run into a permissions issue regarding accessibility and sending keystrokes, then you need to follow the prompt and open `System Preferences` to give `Script Editor` accessibility permissions.

<img width="321" alt="Messages tab in log view" src="https://user-images.githubusercontent.com/19893438/219524051-4e9a400d-c497-49ec-aa8f-9bd499e228f7.png">

**Comment by bpasero** [comment] 2023-02-17 08:03
This is bizarre, but nice we are getting to the bottom of this. 

@lramos15 the gist here is that some people cannot quit VS Code on macOS only when telemetry is enabled. I think at one point we swapped the library for telemetry to a new library and maybe that had an effect. How does telemetry work on shutdown, are we prolonging the shutdown somehow?

**Comment by lramos15** [comment] 2023-02-17 15:32
> And is this all running from the shared process or the main process?

Should all be running in the shared process. We use IPC to pass events from the renderer to the shared process.

As for how it works on shutdown we call https://github.com/microsoft/vscode/blob/ce978df63f369a062a075a4b86dd4fb6aa69b5bf/src/vs/platform/telemetry/common/1dsAppender.ts#L137-L149 on disposal.

The only place I see we specifically await this call is in your window admin crash handler here
https://github.com/microsoft/vscode/blob/ce978df63f369a062a075a4b86dd4fb6aa69b5bf/src/vs/platform/windows/electron-main/windowImpl.ts#L791-L846

Otherwise it's just disposed of like so
https://github.com/microsoft/vscode/blob/ce978df63f369a062a075a4b86dd4fb6aa69b5bf/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L322-L323

**Comment by klaussner** [comment] 2023-02-17 16:00
Great idea to use a script for reproduction, @jungaretti! After tweaking a few values (`warmupDelay = 1.5` and `minQuitDelay = 0.5`) and adding `tell application code to quit` at the beginning of `testCode` (to close the app in case quitting failed during the last call), I could confirm that the problem was introduced in the Insiders build for commit bc0bdc5d0969030f114d5931b18e134059da00c1 from July 7, 2022:

https://user-images.githubusercontent.com/1312807/219703186-e485a72a-5a63-4dd8-bed9-0bf28c94bef8.mp4

**Comment by bpasero** [comment] 2023-02-17 18:36
@lramos15 good catch but that only applies to Windows and users here report it on macOS.

Do people that see this have any special firewall enabled or network monitor?

**Comment by jungaretti** [comment] 2023-02-17 18:44
> Do people that see this have any special firewall enabled or network monitor?

I don't think so. I use a VPN at home and work, but I can repro the bug when that is turned off.

**Comment by bpasero** [comment] 2023-02-17 18:49
@lramos15 do we know what happens on `flush()` exactly? Is it a native module in the end or doing some XHR request?

**Comment by bpasero** [comment] 2023-02-17 19:13
Well we could, but there are questions:
* why is this only impacting very few users and not all
* why does this only happen when VS Code runs without a window open (macOS only) and you try to quit from the dock
* how can a possible pending XHR request block `app.quit` in Electron 🤔 

//cc @deepak1556

**Comment by bpasero** [comment] 2023-02-18 07:26
@jungaretti curious if it reproduces with our exploration build too, with a much newer Electron version: https://az764295.vo.msecnd.net/exploration/0cfb22d96de802eab1fbc7404f2d5822d9c672bb/VSCode-darwin-universal.zip

**Comment by jungaretti** [comment] 2023-02-21 21:47
Yes, I can repro with the exploration build you shared. I see the same symptoms as stable and insiders. Disabling telemetry with `"telemetry.telemetryLevel": "off"` still fixes the problem

[exploration-telemetry.txt](https://github.com/microsoft/vscode/files/10798038/exploration-telemetry.txt)
[exploration-no-telemetry.txt](https://github.com/microsoft/vscode/files/10798037/exploration-no-telemetry.txt)

**Comment by bpasero** [comment] 2023-02-22 05:05
@VincentDondain for you any special network settings involved? VPN? Proxy?

**Comment by bpasero** [comment] 2023-02-22 06:06
@jungaretti out of curiosity because we just made some fundamental changes to the shared process, can you:
* use VS Code insiders
* make sure telemetry is enabled again as usual to reproduce the issue
* set `window.experimental.sharedProcessUseUtilityProcess` in settings to enabled
* restart
* try to reproduce the issue

**Comment by deepak1556** [comment] 2023-02-22 07:37
> how can a possible pending XHR request block app.quit in Electron

This seems to point an issue with the net module in the main process blocking the event loop on pending requests.

@jungaretti @klaussner can you try the following settings to confirm if the issue persists, thanks!

```
"developer.sharedProcess.redirectRequestsToMain": false
"window.experimental.sharedProcessUseUtilityProcess": false
"telemetry.telemetryLevel": "all"
```

**Comment by bpasero** [comment] 2023-02-22 07:40
👍 worth mentioning though, that in stable we have neither enabled the utility process for shared process nor `developer.sharedProcess.redirectRequestsToMain` by default, but its worth a try, maybe one of the users changed the settings.

**Comment by klaussner** [comment] 2023-02-22 20:03
> Do people that see this have any special firewall enabled or network monitor?

I tested it on two different devices in two locations/networks (without a VPN or firewall) and couldn't see a difference.

> Can you try the following settings to confirm if the issue persists, thanks!

The issue persists with these settings. 🙁

---

I don't know if it helps, but if you monitor the requests sent to the telemetry endpoint with `mitmproxy`, you can see that the final requests are handled differently, depending on the timing:
- If the app doesn't quit, requests are sent (and responses are received) after <kbd>⌘</kbd>+<kbd>Q</kbd> (first part of the video).
- If the app quits, the final request is aborted immediately (second part of the video).


https://user-images.githubusercontent.com/1312807/220744568-ab558843-d068-4b5b-a6ad-bc7ee1f62160.mp4

**Comment by jungaretti** [comment] 2023-03-01 23:23
> @jungaretti @klaussner can you try the following settings to confirm if the issue persists, thanks!

Yes, the issue persists with these settings.

**Comment by deepak1556** [comment] 2023-05-15 13:25
@jungaretti @klaussner can you start the application with the following arguments `--trace --trace-category-filter="browser,io,ipc,net,mojom,renderer_host,shutdown,disabled-by-default-lifecycles,disabled-by-default-network"`,  perform the steps below,

1) Close all open windows `Ctrl + Shift.+ W`
2) Quit the application `Cmd + Q`
3) As per the bug, application should still hang around in the dock
4) Open a new window from this running instance
5) Open command paletter `Cmd + Shift + P` and run `Developer: Stop Tracing`
6) Attach the generated trace in this issue thread.

**Comment by jungaretti** [comment] 2023-05-16 18:24
I'm struggling to repro the bug with `code-insiders`, and to fix it in `code` I simply disabled telemetry. I'll share the trace as soon as I can.

**Comment by klaussner** [comment] 2023-05-17 10:23
Same here. I can't reproduce the issue with the latest Insiders build.

**Closed** 2023-05-17 10:37 UTC
Labels: info-needed, freeze-slow-crash-leak, macos, telemetry
