### ISSUE TITLE
Close tags as you open them

### ISSUE THREAD

**Issue by okezieokpara** [Microsoft/vscode#11388] opened 2016-09-01 12:40 UTC
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

1. HTML tags should be automatically closed as I open them. This used to be available before, don't know what happened since I updated.
2. Also I should get snippets based on the CSS and JS files linked to the document. For example I included bootstrap.css in my html, I should get suggestion for all the style classes included in that css file.

**Comment by aeschli** [comment] 2016-09-07 18:53
duplicate of #3000

**Closed by aeschli** 2016-09-07 18:53 UTC
Labels: html
