### ISSUE TITLE
not working closing html closing tags

### ISSUE THREAD

**Issue by isorbitos** [microsoft/vscode#132722] opened 2021-09-09 06:56 UTC
Issue Type: <b>Bug</b>

next time fix bugs before updates!!! now on *.js file when pressing > not creating selfclosing tag, when working with react files!!!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by IllusionMH** [comment] 2021-09-09 09:00
/needsMoreInfo

You forgot to provide steps to reproduce so this problem can be narrowed and fixed. Please provide them.

Most likely duplicate of #132492 (which was created properly)

**Closed** 2021-09-24 11:25 UTC
Labels: needs more info
