### ISSUE TITLE
OnEnter keybinding condition must honour additional text, command, and snippet type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25998] opened 2017-05-05 07:17 UTC
From #25959 

**Repo**
- Create a completion item provider that returns a completion item with the insert text `abc` and a command that edits the document at the completion position
- Trigger the completion item by typing `abc` in a document

**Bug**
Even though the insert text will not change the document, the command will. Because VSCode thinks the item will not change the current document, we do not capture `enter` which results in an extra new line being inserted into the document

**Fix**
Treat any completion item with a command as `MakesTextEdit`

**Comment by jrieken** [comment] 2017-05-05 07:29
@mjbvz Isn't this just a dupe of https://github.com/Microsoft/vscode/issues/25959?

**Comment by mjbvz** [comment] 2017-05-05 07:34
Thanks for the fix. Yes, same root cause for both issues but I created this one to track the root problem on its own

Fixed by 	f8ede24

**Comment by jrieken** [comment] 2017-05-05 07:37
Great. Stupid me, it took two commits to fix this properly: https://github.com/Microsoft/vscode/commit/d1768a78bce98a5ce06373a67631fab49d326955 and https://github.com/Microsoft/vscode/commit/f8ede24fd90af759ee23de89f2baf8b4c5032011. Let's not forget to cherry-pick both if we decide to rebuild

**Comment by jrieken** [comment] 2017-05-05 13:02
I re-open this to be more prominent on our radar

**Comment by jrieken** [comment] 2017-05-08 13:11
pushed changed to `release/1.12`

**Closed** 2017-05-08 13:11 UTC
Labels: api, candidate

**Comment by aeschli** [comment] 2017-05-12 08:25
Verified with a sample extension:
```typescript
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.window.showInformationMessage('Hello World!');
    }));

    context.subscriptions.push(vscode.languages.registerCompletionItemProvider('java', {
        provideCompletionItems: (doc, pos) => {
            let item = new vscode.CompletionItem('abc');
            item.command = { title: 'hello', command: 'extension.sayHello' };
            return [ item ];
        }
    }));
}
```
