### ISSUE TITLE
virtual machine crashes after right clicking too many times in visual studio code

### ISSUE THREAD

**Issue by T-Younce** [microsoft/vscode#89581] opened 2020-01-29 03:28 UTC
I run code in a virtual machine and when I right click too many times, it crashes the entire vm. 

- VSCode Version: 1.14.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open a file in code.
2. Right click several times.

I also would add that before it crashes, it shows a completely black box with no options when I right click or click on file, edit, selection, etc..

Does this issue occur when all extensions are disabled?: Yes
The top image is the output that code is giving me when it crashes(Top; In Ubuntu), and the bottom is the windows crash message (Bottom; In Windows).
![image](https://user-images.githubusercontent.com/56093800/73325433-c1b29080-420b-11ea-87a9-753b2261af2a.png)
![Untitled](https://user-images.githubusercontent.com/56093800/73325548-28d04500-420c-11ea-8b89-fe3263d64229.png)

**Comment by nzupan** [comment] 2020-02-19 13:11
I am experiencing the same problem.
VSCode Version: 1.42.1
OS Version: Ubuntu 18.04

**Comment by deepak1556** [comment] 2020-02-20 03:52
Can you try disabling hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if it still crashes. Possible duplicate of https://github.com/microsoft/vscode/issues/84745

**Closed** 2020-02-27 04:38 UTC
Labels: freeze-slow-crash, linux, menus, needs more info

**Comment by dandymon** [comment] 2020-03-05 14:59
Shouldn't have been closed, happens for me too
Doesn't crash despite repeated clicking in OS or any other application, just in VS code in a virtualbox running Centos (for me).

Appears OS independent, VS code is probably accessing some memory not allowed by the VM?

**Comment by dr-woo** [comment] 2020-03-16 23:01
Also seeing the same behavior as dandymon.

**Comment by dandymon** [comment] 2020-03-17 09:52
> Also seeing the same behavior as dandymon.

Solved by stopping hardware acceleration. I also got the same problem on chrome in my VM so I turned off graphics acceleration in that too and it's been stable for weeks. Hasn't changed the visual performance at all

https://github.com/microsoft/vscode/issues/84745

**Comment by deepak1556** [comment] 2020-03-17 22:26
Thanks for confirming the fix @dandymon , @dr-woo please follow the workaround mentioned here https://github.com/microsoft/vscode/issues/89581#issuecomment-588596303 . This is something that needs fix from chromium.

**Comment by nzupan** [comment] 2020-03-18 07:19
I am still experiencing the same problems even after following the workaround mentioned in #89581 comment.

**Comment by deepak1556** [comment] 2020-03-20 23:05
@nzupan are you seeing the crash in VirtualBox or VS Code ?

Can you provide me the output of `ps -aux | grep code`. Thanks!

**Comment by dr-woo** [comment] 2020-03-20 23:54
So far it looks like disabling hardware acceleration ("disable-hardware-acceleration": true), along with using the command 'code --disable-gpu -a' (although I think this does the same thing as above) has solved my problem.  I'm using VituralBox and I also turned off 'Enable 3D Acceleration' via those settings as well.  I'll report back if it comes up again, thanks all.

**Comment by nzupan** [comment] 2020-03-23 08:01
@deepak1556 VirtualBox crashes. Therefore I can't send ps -aux output. I had hardware acceleration disabled for VS Code, but not for the VM in the VirtualBox. I have disabled it there as well and lets see if the problem goeas away as it did for dr-woo.

**Comment by KocsisV** [comment] 2020-04-07 16:11
I'm experiencing the same.
Windows 10 host, Ubuntu 16.04 guest, VirtualBox 6.1.4 r136177.
Disabling the 3D acceleration is not a solution for me, as I need hw accelerated graphics in the VM.
