### ISSUE TITLE
auto-save’s problem

### ISSUE THREAD

**Issue by zeng662313** [microsoft/vscode#125614] opened 2021-06-06 07:55 UTC
Issue Type: <b>Feature Request</b>

vscode is very convenient, I like it very much. Thank you very much for developing such a convenient tool.
In the process of using it, I found a problem. When saving automatically, if the attribute name of the program has one more ". Like this "<div id="low" class="low"">", the system will not detect errors, but will automatically make the code regular During the process, an extra space is added after each attribute name, which causes the attribute name of the html code to be inconsistent with the attribute name of js.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment] 2021-06-07 14:13
Sorry, I'm not able to reproduce.
- have a file `foo.html`
```
<div id="low" class="low"">
```
- run format from the context menu. Nothing happens
or
- have `"editor.formatOnSave": true` in your settings
save. nothing happens

Can you provide me exact steps?

Please check that the issue is not caused be a formatter that you installed. For that make sue the problem reproduces with all extensions disabled.

**Comment by zeng662313** [comment] 2021-06-07 14:43
I use the latest version of vscode.  when i save my html codes. I maked a mistake. the mistake just like this.  <div class=&quot;first&quot;&quot;&gt;</div&gt;   I save the code,but it will not warning me the problem,instead,it The class of all the tags below will add a space.  from <div id=&quot;doapp&quot;&gt; to <div id=&quot;doapp &quot;&gt;------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月7日(星期一) 晚上10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] auto-save’s problem (#125614)

**Comment by aeschli** [comment] 2021-06-07 16:02
duplicate of #124540

In order to help, I really need detailed steps, as shown in https://github.com/microsoft/vscode/issues/125614#issuecomment-855965602

**Closed by aeschli** 2021-06-07 16:02 UTC
Labels: needs more info
