### ISSUE TITLE
Add option to set debug side-panel font family

### ISSUE THREAD

**Issue by infinitepr0** [microsoft/vscode#116656] opened 2021-02-14 18:13 UTC
The default font used for the variables in the debug panel is totally ugly. Changing `debug.console.fontFamily` and `editor.fontFamily` doesn't change it. Please add a new option, or apply `editor.fontFamily` to the variables too.

![image](https://user-images.githubusercontent.com/45997896/107885108-68a0c200-6f1e-11eb-9ae2-59d16a952f96.png)

**Comment by isidorn** [comment] 2021-02-15 08:55
We will not add an option only for debug. The debug view should be consistent with the rest of the workbench, thus closing this as duplicate of https://github.com/microsoft/vscode/issues/519

**Closed by isidorn** 2021-02-15 08:55 UTC
Labels: debug
