### ISSUE TITLE
Intellisense: set always open downwards???

### ISSUE THREAD

**Issue by dev-chr** [microsoft/vscode#90095] opened 2020-02-05 19:01 UTC
Is it possible to make the code hinting on functions and classes, etc, to not cover above written code? 

![image](https://user-images.githubusercontent.com/10053700/73873634-ef0cc900-481f-11ea-84f5-3da91072b298.png)

**Comment by yume-chan** [comment] 2020-02-06 03:20
Duplicate of #33752

**Closed** 2020-02-06 05:13 UTC
Labels: *duplicate
