### ISSUE TITLE
File explorer not working at all

### ISSUE THREAD

**Issue by G89Angel** [Microsoft/vscode#37592] opened 2017-11-03 08:49 UTC
It happens only with a specific project. File explorer is simply not visible. 

Already tried uninstalling vscode and installing it back again. Also tested without any extension.

Root directory contains the next files:
```
-rw-r--r--   1 users     147 May 15 08:52 .babelrc
-rw-r--r--   1 users       8 May 11 07:59 .closure-config
-rw-r--r--   1 users     661 May 11 07:59 .eslintrc.js
drwxr-xr-x   8 users    4096 Nov  3 09:46 .git
-rw-r--r--   1 users       0 May 11 07:59 .gitattributes
-rwxr-xr-x   1 users    1634 Nov  2 13:17 .gitignore
drwxr-xr-x   8 users    4096 Nov  3 07:47 .idea
-rw-r--r--   1 users    3691 Nov  2 14:22 .php_cs.cache
-rw-r--r--   1 users    2234 May 15 08:52 Gulpfile.js
-rw-r--r--   1 users      71 May 11 07:59 README.md
drwxr-xr-x   6 users    4096 May 11 07:59 ansible
drwxr-xr-x   8 users    4096 Oct 23 14:14 app
drwxr-xr-x   2 users    4096 Nov  2 13:27 bin
-rw-r--r--   1 users    5079 Aug  9 15:00 command.txt
-rw-r--r--   1 users    4564 Nov  2 13:26 composer.json
-rw-r--r--   1 users  200076 Nov  2 13:27 composer.lock
-rw-r--r--   1 users 1840920 May  3  2017 composer.phar
drwxr-xr-x 664 users   28672 Sep 19 08:23 node_modules
-rw-r--r--   1 users    2619 Jul 21 08:42 package-lock.json
-rw-r--r--   1 users    1251 Sep 19 08:23 package.json
-rw-r--r--   1 users     995 May  3  2017 phpunit.xml.dist
-rw-r--r--   1 users     161 May 11 07:59 postcss.json
drwxr-xr-x   3 users    4096 May  3  2017 src
drwxr-xr-x   3 users    4096 May  3  2017 tests
drwxr-xr-x   3 users    4096 Nov  2 13:27 var
drwxr-xr-x  45 users    4096 Nov  2 13:27 vendor
-rw-r--r--   1 users    3790 May 15 08:52 watchers.xml
drwxr-xr-x   9 users    4096 Nov  2 13:27 web
-rw-r--r--   1 users  176205 Sep 19 10:21 yarn.lock
```

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.10-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
quokka-vscode|Wal|1.0.74
html-css-class-completion|Zig|1.12.0
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
vscode-eslint|dba|1.4.2
vscode-npm-script|eg2|0.3.2
php-intellisense|fel|1.5.4
phpcs|ika|0.7.0
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1. Open Code
2. Open project folder

Reproduces without extensions: Yes

**Comment by octref** [comment] 2017-11-03 18:49
By "Tree Explorer" do you mean "File Explorer"? Can you include a screenshot?

**Comment by G89Angel** [comment] 2017-11-03 22:11
![yqsrq](https://user-images.githubusercontent.com/6549094/32397886-459be520-c0ec-11e7-8ee2-d14ec78ef94d.png)

**Comment by octref** [comment] 2017-11-03 22:46
Can you post the SO link?
Also, does this only happen to that particular project? If so, can you open Help -> Toggle Developer Tools and let me know any errors there?

**Comment by G89Angel** [comment] 2017-11-03 23:24
This is the SO link: https://stackoverflow.com/questions/45851552/vs-code-explorer-is-not-showing-any-project-directory-or-files

Someone suggest to delete certain files on Mac, but I'm on Linux. The problem only happens with one particular project.

I wont be in the office till monday, I'll try the developer tools then.

**Comment by G89Angel** [comment] 2017-11-06 06:51
![captura de pantalla de 2017-11-06 07-48-51](https://user-images.githubusercontent.com/6549094/32428646-12d1f3dc-c2c7-11e7-8289-064f02dec2b6.png)

There is my screenshot. Couldn't find anything on Developer tools, no errors on console, just some logs.

**Comment by sandy081** [comment] 2017-11-06 10:54
We stopped allowing hiding File explorer from last couple of milestones. 

To confirm, @G89Angel Can you right click on the header and check what views are enabled and disabled. 

![image](https://user-images.githubusercontent.com/10746682/32437981-4445eadc-c2e9-11e7-8209-f4462c8a818d.png)

**Comment by sandy081** [comment] 2017-11-06 11:29
Suspecting this a duplicate of #37693

**Comment by G89Angel** [comment] 2017-11-06 11:34
![captura de pantalla de 2017-11-06 12-31-15](https://user-images.githubusercontent.com/6549094/32439351-8e161f88-c2ee-11e7-9589-b97383a82cc6.png)
Agree, It looks like a duplicate. So, nothing till 1.18?

**Comment by sandy081** [comment] 2017-11-06 11:57
There are two workarounds:

1. I will be fixing it in insiders and you can move to insiders when it is available.
2. Please follow the [comment](https://github.com/Microsoft/vscode/issues/37693#issuecomment-342124397) for immediate workaround

**Comment by sandy081** [comment] 2017-11-06 11:57
Duplicates #37693

**Closed by sandy081** 2017-11-06 11:57 UTC
Labels: explorer-files, needs more info
