### ISSUE TITLE
Windows: using `edge` as `workbench.externalBrowser` opens default browser too

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#230636] opened 2024-10-06 12:11 UTC
Type: <b>Bug</b>

My default browser is Firefox.
I have `workbench.externalBrowser` set to `edge`
After running `npm run dev` on any web project and clicking the localhost link to open the website I would expect vscode to open the website in Edge only.
What actually happens is that VsCode open the website in both Firefox _and_ Edge

It does this will all extensions disabled.
It's very annoying.

It's a Vite React project I'm using, and in addition to opening browser tabs in both Edge and Firefox, VsCode is only actually establishing a browser link to the Firefox tab. So any compilation errors from Vite go to the Firefox console but not the Edge console. So despite having set `workbench.externalBrowser` to `edge`, the Edge browser tab that gets opened isn't even usable.

I see the same behaviour whether I run `npm run dev` in either the embedded cmd or Powershell terminals.

I also created a new create-react-app using the instructions from [here](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial), and then manually added an Edge launch profile as described in that guide. This also had no effect and clicking the localhost link in the enbedded terminal just ignored the `workbench.externalBrowser` setting and opened the website in Firefox.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (17.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment] 2024-10-06 13:36
I can reproduce, and it seems due to launching `edge` writing to std-error here, which makes us fallback to the default browser:

https://github.com/microsoft/vscode/blob/dc265add0b37d88dcf955ef83c8d483e35af242c/src/vs/platform/native/electron-main/nativeHostMainService.ts#L543-L546

The error logged is:
```
[main 2024-10-06T13:28:29.919Z] Error openening external URL 'https://github.com/microsoft/vscode/issues' using browser 'edge': #< CLIXML
```

We are using a 3rd party library for opening: https://github.com/sindresorhus/open

If someone has ideas, marking for help wanted.

**Comment by gy2649263674** [comment] 2024-10-07 03:50
Device: Microsoft Windows 11 
Vscode version:1.94.0
I find an odd phenomenon: when I set workbench.externalBrowser in my setting.json file with any value like 'chrome' or 'edge' my vscode can't open any external url anymore and when i  leave it with space then it can open url correctly using my default brower. Why does this happen?

**Comment by Parasaran-Python** [comment] 2024-10-07 18:18
Grabbed the system command thats executed by the "open" library to open the external browser and ran the same in a cmd instance, the stack is clean and I dont see any error, stderr doesnt seem to be expected here.

[https://github.com/sindresorhus/open/issues/348](url)

opened an issue in their repo.

**Comment by peterdanwan** [comment] 2024-10-07 23:00
I think I have a similar issue, but not exactly the same.

## Version Information
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

## Behaviour _without_ `"workbench.externalBrowser": "chrome"`

![Code_RWl85qghR3](https://github.com/user-attachments/assets/a9c45abf-fe60-4930-94a2-1d0e510b89b5)

## Behaviour _with_ `"workbench.externalBrowser": "chrome"`

![chrome_oaIcjvkdmR](https://github.com/user-attachments/assets/18df3bca-24b3-446c-8cfc-a42326b606c4)

**Comment by bpasero** [comment] 2024-10-08 07:24
That document should get you setup running VS Code out of sources and test your changes.

**Comment by peterdanwan** [comment] 2024-10-10 01:53
Hello @bpasero! I just wanted to follow-up with you - I have made a [PR](https://github.com/microsoft/vscode/pull/230987) with some changes that seem to work on my end. 

If you have the opportunity, can you check to see if these changes are valid?

Thank you!

**Comment by bpasero** [comment] 2024-10-11 10:08
Sorry, I did not yet get back to your PR, while investigating what happens.

The full message output from PowerShell.exe is:

```
#< CLIXML

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="Sour
ceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```

Maybe a low risk fix is to just detect this case 🤔

**Comment by ihsanalikapahi01** [comment] 2024-10-11 10:35
dear sir, thank you very much for so much concern. Actually, there is a lot to tell you people the team of Microsoft Google One especially get up and Apple that I had been in pain since the last 45 years that my billions of crypto is in risk I was working with petroleum starting from 2007 to 2013 then I move to group of countries here in Pakistan in 2019. My wife is a doctor and she just started her carrier and she got Covid in 2019 I was in out of my town actually is like 45 Hours Dr. from my village, which is my hometown. The thing is by bike after spending like 1516 years at very top level with two marketing companies in Pakistan I decided that I should go back to my home because my my wife was in a very critical position then I took my three kids and my wife and I came back and I quit my job I belong to a very royal family. I did my bachelors from university of Cambridge Singapore. Then I did my masters in business information technology from Lahore Pakistan one of the top institutions thing is to tell you that when I move from Covid Faisalabad to my hometown, there was no Internet facility at that time and buy two laptops my personal laptops then my my computer my my devices my iPhone X I was out of Internet. They just got paid for almost one year. It was a very difficult scenario for me. That was a very difficult period for me after my wife got Covid then my cricket got Covid. Then I felt failed in Covid for longer time when I was absent from GitUp, Microsoft, Apple, Google, and everybody because I was having no Internet then you people got stuck where is this guy is I don’t know what happened. I couldn’t even go to ATM to take my cash for longer time and then the statement of Pakistan and then my bank account for free without any reason I think there was a information floated by you, people Microsoft, and whatever that I was holding a lot of stocks in your stock change and actually with Microsoft office, I was holding my personal office in that I was having billions of dollars at that time then when I started taking prescription subscription of the app from Microsoft store Microsoft store and then I move to Apple technology before that I was holding technology. A lot of things got mixed and what I think is that Microsoft was thinking that I am the owner of the company actually you people were thinking that I am the owner of and I am the owner of LaGuardia because I was my Internet for totally safe and things were totally safe and I was working at the very top position but at the same time I was I was I was holding my private Microsoft OneDrive since long. It’s been almost 16 years that I am I am owning almost more than 100 apps subscription app. You can check my record, but the thing is when you contacted me. I decided that you people offered me somebody. Nobody was in front of me actually I think the guys from Google I am or Apple Microsoft contacting me that your stock where are you? Are you dead? I felt into Covid since then they asked me that you are holding a lot of money. What are your plans? I asked that I am thinking that I will bring a huge amount of money and Pakistan it rest for me. I am planning will either take it to UAE Singapore or whatever I was planning but at the same time somebody offered me that why don’t you take the crypto I was actually almost 0 knowledge of having crypto knowledge but actually I am masters MBN tech technology. I just studied 23 days. Please give me my money wallet you transferred my money interest wallet the billions of dollars so I took three days almost and I was having at the time iPhone X of storage 512 GB the thing is that I was already having 2 to 300 GB of storage in my iPhone and then when the transaction started my phone just stuck by the Apple logo after three days and it was a shock that it was happening. It was happening very first time with me that I thought that this huge amount of money is gone when I have repaired my phone through local market because Pakistan at that time there not a lot of facilities then when I got repaired my phone since that day took a lot almost 4 1/2 years that that bloody trust and financing nobody is just giving the test to my pain my family pain that I am requesting you all where is my money? I am holding. I gave you a lot of proof every document saying to people that this bloody acid belongs to me. A lot of emails and a lot of portfolios have been created at the thing is that my data passes went to 3000 GB I don’t have any device with which is of 3000 GB. I am holding a lot of subscription subscription like I am holding 2000 GB from Apple 2000 GB from the dropbox and 2000 GB from TeraBox. Everybody is packed. Everybody is packed that you people almost broke my devices for 1010 times I couldn’t evengive you my message properly. Nobody is listening where the bloody that stock is where is my money? why don’t you give my money back please the thing is I’m giving you the proves for the reason that that money belongs to me. Please give it to me that’s it. 


Sent from Yahoo Mail for iPhone


On Friday, October 11, 2024, 3:19 PM, Benjamin Pasero ***@***.***> wrote:




Sorry, I did not yet get back to your PR, while investigating what happens.

The full message output from PowerShell.exe is:
#< CLIXML

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="Sour
ceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>

Maybe a low risk fix is to just detect this case 🤔

**Comment by bpasero** [comment] 2024-10-11 11:08
Pushing https://github.com/microsoft/vscode/commit/bb19ce3f00302e797376767188a3933a95666170 as a quick workaround for Windows.

**Comment by bpasero** [comment] 2024-10-12 07:27
I am leaving this with my workaround for now as it fixes the reported issue. The only downside is that now when you mis-configure this setting, we have no fallback. I am willing to revisit this if more people report this as being annoying.

**Closed by bpasero** 2024-10-12 07:27 UTC
Labels: bug, help wanted, good first issue, workbench-os-integration, confirmed
