### ISSUE TITLE
Missing basic code snippets: ctor, prop after upgrade

### ISSUE THREAD

**Issue by kradwan** [Microsoft/vscode#26111] opened 2017-05-06 09:56 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.16.0|
|aurelia|AureliaEffect|0.3.3|
|Aurelia|behzad88|1.2.1|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.12.0|
|beautify|HookyQR|1.0.2|
|cs-syntax-visualizer|itn3000|0.0.2|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.2|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|docomment|k--kato|0.0.14|
|csharpfixformat|Leopotam|0.0.23|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|resharper9-keybindings|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|color-highlight|naumovs|2.1.3|
|view-in-browser|qinjia|0.0.5|
|view-in-default-application|seesharprun|3.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1.Open editor, create class, inside class start typing "ctor" or "prop", "struct", these basic snippets disappeared somehow?
2. Even adding User code snippets I can't use them inside VSCode anywhere

User stub for "ctor" snippet which is not recognized inside VSCode as below:
"constructor": {

		"prefix": "ctor",
		"body": [
			"${1:public} ${2:ClassName}(${3:Parameters})",
			"{",
			"	${0}",
			"}"
		],
		"description": "constructor"
	}

**Comment by andrebaltieri** [comment] 2017-05-06 22:25
I`m facing the same issue here! Tested on MacOs and Ubuntu... same on both!

**Comment by jrieken** [comment] 2017-05-08 17:24
dupe of https://github.com/Microsoft/vscode/issues/26182

**Closed by jrieken** 2017-05-08 17:24 UTC
