### ISSUE TITLE
Switching Custom Editor causes broken tab

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#114288] opened 2021-01-13 16:39 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open a custom editor either text or binary.
2. Trigger reopen with -> Text Editor
3. Click back to the custom editor tab
4. 🐛 You can't click back onto the text editor tab it's broken
![Bug Demo](https://user-images.githubusercontent.com/4544166/104481436-ca72b280-5593-11eb-839a-27ab1256cbd3.gif)

VS Code version: Code - Insiders 1.53.0-insider (e17aea136d32fdb06d9b32184b04ccd36bb51e9c, 2021-01-12T08:23:24.929Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.63GB free)|
|Process Argv|C:\\Users\\lramo\\Documents\\Microsoft Work\\custom-editor-sample --crash-reporter-id 0e841b0e-68ef-4be7-9633-d77305150fd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.22.0
python|ms-|2021.1.436859988-dev
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
js-debug-nightly|ms-|2021.1.817
debugger-for-chrome|msj|4.12.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30244316
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt875:30241730
core-portspanelcf:30233468

```

</details>

**Comment by mjbvz** [comment] 2021-01-13 18:50
Duplicate of #112848

**Closed by mjbvz** 2021-01-13 18:50 UTC
Labels: bug, custom-editors
