### ISSUE TITLE
Context menu item is immediately selected when the menu is brought up

### ISSUE THREAD

**Issue by dragongears** [microsoft/vscode#119138] opened 2021-03-16 23:02 UTC
When clicking the right mouse button to bring up the context menu in the editor, the menu item that happens to be under the cursor is selected immediately when the menu appears. It seems to be more likely when the cursor is closer to the bottom of the screen. Reading other similar issues, it also seems to be zoom related. If I choose a zoom level of 0 it doesn't seem to happen. It does happen at all other zoom levels. It is also a recently introduced issue.

Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-7642-generic

**Comment by yume-chan** [comment] 2021-03-17 02:37
Duplicate of #113175

**Closed** 2021-03-18 22:06 UTC
Labels: *duplicate
