### ISSUE TITLE
TS Server fatal error:  No Project.

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode#100121] opened 2020-06-14 14:08 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**

I just opened my workspace.

**TS Server Error Stack**
```
Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141496:23)
    at ScriptInfo.getDefaultProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142266:46)
    at ProjectService.telemetryOnOpenFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146828:42)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146910:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146910:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.47.0-insider (7e4cc2c435927e5a2845897961a2af10ee7f784d, 2020-06-12T05:59:19.397Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (17.19GB free)|
|Process Argv|-psn_0_17076296|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-coverage-highlighter|bra|1.0.3
better-toml|bun|0.3.2
vscode-zonefile|Com|0.0.4
vscode-eslint|dba|2.1.5
chmod|dle|1.1.1
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.0.0
vscode-firefox-debug|fir|2.8.0
backticks|fra|1.6.0
vscode-sshfs|Kel|1.17.0
vscode-webidl|keq|0.0.1
restructuredtext|lex|128.0.0
vscode-clangd|llv|0.1.6
rust-analyzer|mat|0.2.199
vscode-docker|ms-|1.2.1
python|ms-|2020.5.86806
remote-containers|ms-|0.122.1
remote-ssh-edit-nightly|ms-|2020.6.3953
remote-ssh-nightly|ms-|2020.6.3953
idl|myt|0.3.1
autotrim|Nat|1.0.6
material-icon-theme|PKi|4.1.0
django-intellisense|sha|0.0.2
vscode-hexdump|sle|1.7.2
vscode-taskexplorer|spm|1.26.3
vscode-lldb|vad|1.5.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-06-15 18:39
Does this happen in other workspaces?

Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Mossop** [comment] 2020-06-16 14:28
I cannot reproduce this issue.

**Comment by patrickhulce** [comment] 2020-06-18 22:05
I stumbled upon this after updating Insiders and Intellisense was broken with a similar log. Restarting VS Code fixed the issue, but does seem to happen randomly 🤷 

If it helps, it happened when VS Code was started automatically after a kernel panic crash OS restart.

**Comment by mjbvz** [comment] 2020-09-08 20:38
Closing since the original reporter cannot reproduce it

Let me know if you can reliably hit this in VS Code 1.49+

**Closed by mjbvz** 2020-09-08 20:38 UTC
Labels: needs more info
