### ISSUE TITLE
Error code of zero in markers get removed

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode#31275] opened 2017-07-23 11:32 UTC
markerService.ts tries to [sanitize](https://github.com/Microsoft/vscode/blob/caa0ef4e3a0128a73bfe51a32c1833dea4f63c35/src/vs/platform/markers/common/markerService.ts#L190) the marker data by checking the marker's `code` property. Unfortunately, if `code === 0` then it'll become `null`. This means that later attempts to access the created marker will not match "reality" because the `code` property is now `null`.

**Comment by jrieken** [comment] 2017-07-24 07:55
Good catch. Thanks for reporting!

**Comment by jrieken** [comment] 2017-07-24 08:04
Wait... @rcjsuen How do you feed in the that marker with `code = 0`?

**Comment by rcjsuen** [comment] 2017-07-24 08:30
@jrieken Hi, thank you for following up so quickly!

I'm using [some code](https://github.com/TypeFox/monaco-languageclient/blob/8fad2e2bc7e34e687cd010680cef4fc99cead3a2/src/converter.ts#L518) that transforms a [language server protocol's Diagnostic](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/protocol.md) object into an `IMarkerData`. Unfortunately, the transpiled JavaScript doesn't actually convert the `number` into a `string` because the `as string` casting is simply removed and nothing happens to the actual `diagnostic.code`.
```JavaScript
ProtocolToMonacoConverter.prototype.asMarker = function (diagnostic) {
    return {
        code: diagnostic.code,
        severity: this.asSeverity(diagnostic.severity),
        message: diagnostic.message,
        source: diagnostic.source,
        startLineNumber: diagnostic.range.start.line + 1,
        startColumn: diagnostic.range.start.character + 1,
        endLineNumber: diagnostic.range.end.line + 1,
        endColumn: diagnostic.range.end.character + 1
    };
};
```
I think the TypeScript code should be modified to actually convert the `number` into a `string` but I think VS Code should also guard against this. Do you agree?

**Comment by jrieken** [comment] 2017-07-24 09:19
Yes, this is a bug with LSP converter because it fails to create a valid marker.

**Comment by rcjsuen** [comment] 2017-07-24 09:37
> Yes, this is a bug with LSP converter because it fails to create a valid marker.

Actually, that code is in the [Typefox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) project. I've opened Typefox/monaco-languageclient#14 to ask them to fix this.

However, I still think that VS Code should guard against this in markerService.ts.

**Comment by dbaeumer** [comment] 2017-08-02 13:56
@jrieken the LSP is not involved here. It is some specific code to integrate the LSP into the Monaco editor from Typefox. The LSP code to convert is as follows

```
	function asDiagnostic(diagnostic: ls.Diagnostic): code.Diagnostic {
		let result = new code.Diagnostic(asRange(diagnostic.range), diagnostic.message, asDiagnosticSeverity(diagnostic.severity));
		if (is.number(diagnostic.code) || is.string(diagnostic.code)) { result.code = diagnostic.code; }
		if (diagnostic.source) { result.source = diagnostic.source; }
		return result;
	}
```

Moving to @jrieken to comment on the request to protect the marker service.

**Comment by jrieken** [comment] 2017-08-14 10:11
Closing as caused by extension. Internally this is a string which won't be falsy when set to '0'

**Closed by jrieken** 2017-08-14 10:11 UTC
Labels: bug
