### ISSUE TITLE
typescript '....' is declared but its value is never read fails

### ISSUE THREAD

**Issue by chrisj-skinner** [Microsoft/vscode#54152] opened 2018-07-12 10:03 UTC
Issue Type: <b>Bug</b>

Using typescript and angular and the  " '....' is declared but its value is never read" is a great idea but fails when using the '....' within a component.html file.  It greys it out but I actually still need it. Make sure the rule searches template url files.
Eg. import { foo }  from '....';

<p foo>Foo could be a pipe for example</p>

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
FreeMarker|dco|0.0.9
prettier-vscode|esb|1.5.0
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|6.1.1
angular2-inline|nat|0.0.17
vetur|oct|0.12.5
vscode-icons|rob|7.24.0
wallaby-vscode|Wal|1.0.91
JasmineSnippets|xab|1.0.1

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-07-12 15:32
Sounds like a duplicate of https://github.com/Microsoft/TypeScript/issues/24790. Can you please provide a code example of the problem

**Comment by chrisj-skinner** [comment] 2018-07-13 08:29
app.component.ts

import * as fromHelpers from '../../../shared/helpers';

@Component({
  ...
  templateUrl: './app.component.html',
})

`constructor(
    ...
    private fFhelper: fromHelpers.FormFieldHelper, <---- fFhelper greyed out 
  ) {}`

app.component.html

`<form novalidate (ngSubmit)="fFhelper.onSubmit(form)" .....>

**Comment by mjbvz** [comment] 2018-07-16 18:20
This seems to be the same question asked here: https://github.com/Microsoft/TypeScript/issues/24790

I do not think you should use private variables in your template: https://stackoverflow.com/questions/34574167/angular2-should-private-variables-be-accessible-in-the-template

**Closed by mjbvz** 2018-07-16 18:20 UTC
Labels: needs more info, typescript
