### ISSUE TITLE
Bug Sur icons glitched on non-hidpi screens

### ISSUE THREAD

**Issue by shaonianruntu** [microsoft/vscode#120305] opened 2021-04-01 05:11 UTC
OS: macOS 11.2.3 (20D91)
Device: Mac mini (M1, 2020)
Desktop: Benq 24' inch 1080P 

New Icon (v1.55) garbled under Big Sur M1 Mac both for apple scallion version and universal version.

**But interestingly, there's no problem with my 13-inch M1 Macbook air, and it's this problem under the M1 Mac mini on my 24-inch external display.**

The following example of icon garbled comes from Mac mini:

This is the installation package downloaded from the official website, you can see that after unziping its little icon is garbled:
![iShot2021-04-01 12 47 30](https://user-images.githubusercontent.com/16336682/113245917-82d60a00-92ea-11eb-9538-5d8dba08459b.png)

This is the introduction to this unzipping installation package, you can see that the small icon is in disarray but the large icon is correct:
![iShot2021-04-01 12 47 41](https://user-images.githubusercontent.com/16336682/113246132-f0823600-92ea-11eb-9933-7840b98996b1.png)

This is the display of the launch desk page, the same small icon is wrong but the big icon is correct:
![iShot2021-04-01 12 47 13](https://user-images.githubusercontent.com/16336682/113246379-828a3e80-92eb-11eb-82d9-67ddc691a498.png)
![iShot2021-04-01 12 47 17](https://user-images.githubusercontent.com/16336682/113246518-bb2a1800-92eb-11eb-95d1-1f2aabd9ff3e.png)

**Comment by shaonianruntu** [comment] 2021-04-01 05:13
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:07:58.402Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id aebaf2e0-6548-4ea1-8ed8-5823f58efc9c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: g1080|
|OS|Linux x64 4.15.0-20-generic|
|CPUs|Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz (20 x 3803)|
|Memory (System)|125.82GB (63.43GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
svg-preview|Sim|2.8.3
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
code-runner|for|0.11.3
todo-tree|Gru|0.0.209
rainbow-csv|mec|1.8.1
vscode-filesize|mkx|3.1.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2
korofileheader|OBK|4.8.5
indent-rainbow|ode|7.5.0
svg-preview|Sim|2.8.3
tabnine-vscode|Tab|3.2.16
vscode-wakatime|Wak|5.0.1
markdown-all-in-one|yzh|3.4.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontbcf:30265426
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by shaonianruntu** [comment] 2021-04-01 05:16
And dragging the '/Applications/Visual Studio Code.app/Contents/Resources/Code.icns' file in the package file to the small icon in the upper left corner of the software's introduction page still doesn't solve the problem.

**Comment by robjwells** [comment] 2021-04-01 05:51
Same on Catalina (10.15.7), on an Intel MacBook Air. Dock icon fine, but smaller icon garbled.

![Screenshot 2021-04-01 at 06 49 28](https://user-images.githubusercontent.com/1935268/113249358-71730a80-92b6-11eb-83ab-5947d79c37a2.png

```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by yume-chan** [comment] 2021-04-01 05:59
Duplicate of #118754, #106429

**Comment by sataset** [comment] 2021-04-01 06:03
macOS Big Sur 11.2.3 (20D91)

- normal in dock
- distorted in Finder toolbar

![Screenshot at Apr 01 10-59-44](https://user-images.githubusercontent.com/28687456/113250142-3e357900-92c0-11eb-910d-24a6277beb01.png)

<details>
  <summary>vscode info</summary>

    Version: 1.55.0
    Commit: c185983a683d14c396952dd432459097bc7f757f
    Date: 2021-03-30T16:01:05.981Z (1 day ago)
    Electron: 11.3.0
    Chrome: 87.0.4280.141
    Node.js: 12.18.3
    V8: 8.7.220.31-electron.0
    OS: Darwin x64 20.3.0
</details>

**Comment by robjwells** [comment] 2021-04-01 06:05
> Duplicate of #118754, #106429

Not sure it’s a duplicate of #106429 as it is just the icon affected for me.

**Comment by yume-chan** [comment] 2021-04-01 06:08
@robjwells I agree with you and that's why I included #118754. Which had been marked as a duplicate of #106429

**Comment by bpasero** [comment] 2021-04-01 07:13
I can see the garbled icon too (macOS ARM).

**Comment by bpasero** [comment] 2021-04-01 07:38
@misolori this is just the icon, nothing else for me. And only in the menu such as here:

![image](https://user-images.githubusercontent.com/900690/113259994-0d5c4080-92ce-11eb-9c2e-1997d1206e17.png)

**Comment by estruyf** [comment] 2021-04-01 12:41
Same for me, got it on my Macbook (Catalina) and Mac Mini (Big Sur). Noticed it when I used the "open with".

![Screenshot 2021-04-01 at 14 37 22](https://user-images.githubusercontent.com/2900833/113295310-57f2b280-92f8-11eb-9bd6-a4a169a1a822.png)

**Comment by gjdass** [comment] 2021-04-01 18:46
Same here. Fresh install or not.
MaxBook Air M1.

**Comment by aryadaroui** [comment] 2021-04-01 19:53
Same issue here. Intel mac on Big Sur.
Seems only to be the smaller icons that are distorted.

**Comment by deepak1556** [comment] 2021-04-02 02:59
@misolori this not an issue on the users' device but on the icn files we have shipped.

```
* Download https://github.com/microsoft/vscode-distro/raw/distro/quality/stable/resources/darwin/code.icns
* iconutil -c iconset -o /tmp/vscode.iconset ~/Downloads/code.icns
* 16x16, 32x32 and 48x48 are not correct however their 2x counterparts (hiDPI templates) are fine, that is why only certain set of users are seeing this issue.
```

**Comment by misolori** [comment] 2021-04-02 03:17
@deepak1556 thanks for investigating this, marking as a candidate and will work on a fix for this.

**Comment by butuzov** [comment] 2021-04-02 06:18
same on mojave

**Comment by widersky** [comment] 2021-04-02 13:46
The same issue here on macOS 11.2.3

**Comment by supriyo-biswas** [comment] 2021-04-03 13:17
I see the same issue on macOS 10.14.6 within Spotlight:

![vscode-icon-spotlight](https://user-images.githubusercontent.com/27079933/113479487-08a1b300-94ad-11eb-8f66-f3714d0d20ba.png)

**Comment by ventulus95** [comment] 2021-04-03 13:45
same issue on macOS 10.15.7 
![스크린샷 2021-04-03 오후 10 44 52](https://user-images.githubusercontent.com/17822723/113480215-3519f700-94ce-11eb-80e3-5eb326f8b008.png)

**Comment by misolori** [comment] 2021-04-04 21:49
I've got updated icon files, can someone who's encountering this issue verify that these work? 

**Steps**
1. [Download and extract this zip file](https://github.com/microsoft/vscode/files/6255404/code-icon.zip)
2. Right-click on VS Code from finder > Get Info
3. Drag the new `code.icns` file into the top left of the Get Info window
4. Restart the dock by running ` killall Dock` from the terminal


![CleanShot 2021-04-04 at 14 47 02](https://user-images.githubusercontent.com/35271042/113522372-c8960b00-9554-11eb-9777-55c41ea26a2e.gif)

**Comment by David-NS** [comment] 2021-04-04 22:16
> I've got updated icon files, can someone who's encountering this issue verify that these work?
> 
> **Steps**
> 
> 1. Close VS Code
> 2. [Download and extract this zip file](https://github.com/microsoft/vscode/files/6255404/code-icon.zip)
> 3. Right-click on VS Code from finder > Get Info
> 4. Drag the new `code.icns` file into the top left of the Get Info window
> 5. Restart the dock by running ` killall Dock` from the terminal
> 6. Open VS Code
> 
> ![CleanShot 2021-04-04 at 14 47 02](https://user-images.githubusercontent.com/35271042/113522372-c8960b00-9554-11eb-9777-55c41ea26a2e.gif)

It is working fine now, I'm on Big Sur 11.2.3

![Captura de pantalla 2021-04-05 a las 0 14 46](https://user-images.githubusercontent.com/50212780/113522841-1f770100-95a4-11eb-9df3-ea7e68c9534d.png)
![Captura de pantalla 2021-04-05 a las 0 15 00](https://user-images.githubusercontent.com/50212780/113522845-2271f180-95a4-11eb-8e8d-0cf4782b0d89.png)
![Captura de pantalla 2021-04-05 a las 0 15 36](https://user-images.githubusercontent.com/50212780/113522847-24d44b80-95a4-11eb-8006-66464c2da223.png)

**Comment by shaonianruntu** [comment] 2021-04-05 04:50
> I've got updated icon files, can someone who's encountering this issue verify that these work?
> 
> **Steps**
> 
> 1. Close VS Code
> 2. [Download and extract this zip file](https://github.com/microsoft/vscode/files/6255404/code-icon.zip)
> 3. Right-click on VS Code from finder > Get Info
> 4. Drag the new `code.icns` file into the top left of the Get Info window
> 5. Restart the dock by running ` killall Dock` from the terminal
> 6. Open VS Code
> 
> ![CleanShot 2021-04-04 at 14 47 02](https://user-images.githubusercontent.com/35271042/113522372-c8960b00-9554-11eb-9777-55c41ea26a2e.gif)

It works for me! Thank You !

**Comment by DeveloperWOW64** [comment] 2021-04-05 07:47
I once had the same issue with a drive icon.

**Comment by DeveloperWOW64** [comment] 2021-04-05 07:54
> I've got updated icon files, can someone who's encountering this issue verify that these work?
> 
> **Steps**
> 
> 1. Close VS Code
> 2. [Download and extract this zip file](https://github.com/microsoft/vscode/files/6255404/code-icon.zip)
> 3. Right-click on VS Code from finder > Get Info
> 4. Drag the new `code.icns` file into the top left of the Get Info window
> 5. Restart the dock by running ` killall Dock` from the terminal
> 6. Open VS Code
> 
> ![CleanShot 2021-04-04 at 14 47 02](https://user-images.githubusercontent.com/35271042/113522372-c8960b00-9554-11eb-9777-55c41ea26a2e.gif)

Yes, does work, if you use [this link](https://github.com/microsoft/vscode/issues/120410#issuecomment-812988039) you can pick which icons you like

**Comment by heismauri** [comment] 2021-04-05 17:23
I tried @DeveloperWOW64's solution and it only fixed the program but not the files that are able to be opened with VSCode.
![Screen Shot 2021-04-05 at 1 21 54 PM](https://user-images.githubusercontent.com/47569205/113603500-086ef800-9612-11eb-9afe-050398445afc.png)

**Comment by misolori** [comment] 2021-04-05 17:26
@DeveloperWOW64 @heismauri let's please keep this issue focused on the official VS Code icons.

**Comment by DeveloperWOW64** [comment] 2021-04-05 17:26
> I tried @DeveloperWOW64's solution and it only fixed the program but not the files that are able to be opened with VSCode.
> ![Screen Shot 2021-04-05 at 1 21 54 PM](https://user-images.githubusercontent.com/47569205/113603500-086ef800-9612-11eb-9afe-050398445afc.png)
> 
> This is a MacBook Air (13-inch, 2017) running MacOS Catalina 10.15.7

There is a way to solve the file icons, I think

**Comment by DeveloperWOW64** [comment] 2021-04-05 17:29
in the /Applications/Visual Studio Code.app/Contents/Resources/ are there any corrupted icns files that look similar to the him-ultimate.py icon?

**Comment by misolori** [comment] 2021-04-05 17:32
Since a few people have already confirmed that the new fix works, going to lock this issue to reduce the noise. Thanks everyone in reporting this, will close this issue once the PR has been merged.

**Comment by misolori** [comment] 2021-04-05 20:41
For verification:

1. cd into the directory that has the icns files
2. run `iconutil -c iconset -o ~/Desktop/code-temp.iconset Code.icns` to deconstruct icns file (this will create a folder on your desktop)
3. Open folder and verify that all icons appear normally without any glitches
  <img width="300" src="https://user-images.githubusercontent.com/35271042/113624448-83d1a900-9614-11eb-804c-76115bd1f53b.png">

**Comment by misolori** [comment] 2021-04-05 20:52
Merged https://github.com/microsoft/vscode/commit/91fa7f030d2da54f381be16cd1855798a091727d

**Closed by misolori** 2021-04-05 20:52 UTC
Labels: bug, candidate, confirmed, icons-product, mac
