### ISSUE TITLE
Should not open save prompt when closing a tab when autosave is enabled (via files.autoSave to onFocusChange)

### ISSUE THREAD

**Issue by musiKk** [Microsoft/vscode#35234] opened 2017-09-27 15:37 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.8.0-59-generic
- Extensions: don't matter at all

---
Setting `files.autoSave` to `onFocusChange` seems to replicate IntelliJ's save as close as possible. To me this signifies that I don't want to manually save at all. However, when closing a tab that is currently dirty, VSCode displays a save prompt with "Cancel", "Don't Save" and "Save" buttons. I would expect it to automatically save as well.

Steps to Reproduce:

1. Set `files.AutoSave` to `onFocusChange`.
2. Open any file.
3. Make any edit.
4. Close tab with the shortcut, e.g., for me this is Ctrl+w (don't open command palette, this already counts as a focus change)

Outcome:
* Save prompt opens.

Expected outcome:
* File is saved and editor is closed.

I guess this could be solved by either changing the behavior of `onFocusChange` or introducing a new value like `onFocusChangeOrClose`.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-11-17 14:47
i am not 100% sure changing this is right because strictly speaking you have not lost editor focus yet. and maybe people actually like the fact that they can still close the editor without saving in that case. Closing as designed for now until more people complain.

**Closed by bpasero** 2017-11-17 14:47 UTC
Labels: feature-request, file-io

**Comment by musiKk** [comment] 2017-11-20 15:29
I get it in the sense that it works as it sounds. I just don't think it's a particularly useful. If the setting is enabled as described, even something as innocent as clicking into the side bar will save the file. This is about as close to "real time saving" as you can get were it not for the issue I mentioned when closing the tab.

I guess there is nothing I can do to convince anyone that this would be a good feature... 😕
