### ISSUE TITLE
Update extension button invisible when new version number too big

### ISSUE THREAD

**Issue by mmakarios** [Microsoft/vscode#33910] opened 2017-09-06 20:50 UTC
If the number is too big and the side bar too small, the button to upgrade vanishes from view (but still covers the author's name).

In this example, the button is gone only when I'm using a theme with borders around the side bar, like the High Contrast or Dracula. With a theme without borders, the space is just right to fit the example "0.29.0", both using minimal side bar width.

![image](https://user-images.githubusercontent.com/9814055/30133791-7af78d12-932b-11e7-9ac2-af2747075b4e.png)

![image](https://user-images.githubusercontent.com/9814055/30133526-9b0c4fe4-932a-11e7-8e9a-54bb86827a24.png)

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0

**Comment by sandy081** [comment] 2017-11-24 09:04
@mmakarios Not able to reproduce this with Dracula and High Contrast themes. Can you please try again and let us know if it happens to you still. If so, please provide more information to reproduce.

![image](https://user-images.githubusercontent.com/10746682/33202961-b8bf685c-d0fe-11e7-83ca-16c07321f002.png)

![image](https://user-images.githubusercontent.com/10746682/33202992-d8ef8ae4-d0fe-11e7-8f46-d9ebb485f940.png)

**Comment by mmakarios** [comment] 2017-11-24 18:16
I can't test again with the same extension "stylelint" since I uninstalled it, but I'm able to do with other extensions requesting updates on my Insiders build.

The issue happens with the extensions "Bracket Pair Colorizer" (Update to 0.10.14) and "Prettier - Code formatter" (Update to 0.26.0), but it doesn't happen with the extension "Project Manager" (Update to 0.23.0). Which is odd, since Prettier and Project Manager have practically the same numbers in the update button. Maybe something to do with the name and description too?

![image](https://user-images.githubusercontent.com/9814055/33220677-4fd02d26-d131-11e7-8e1d-513ff915ce41.png)

I found something that might be another issue on its own, but I'm not sure.

When I click and drag to shrink the side bar, sometimes it "locks" before reaching the minimum width, although my cursor is past the threshold (in between the minimum width and hiding the side bar). I think this is related to the refresh rate of the editor, because if I hide and reopen the side bar, the "actual" minimum width is displayed, and the Update button is invisible again.

**Comment by sandy081** [comment] 2017-11-27 09:12
@mmakarios Thanks for providing more info. I can reproduce the issue now. After digging history of this, I see this is expected behaviour. Initially we were wrapping and showing the buttons partially. But later, we decided not to show them partially, instead hide them. Ref #7995. 

But, one of the problems I see with this approach is that, if users have small side bar width, then update button will be never visible.

@joaomoreno FYI

**Comment by sandy081** [comment] 2018-09-17 14:20
Closing this as wrapping is expected from #7995. Since it is a very corner case and did not see any other complaints, closing this as as designed.

**Closed** 2018-09-17 14:20 UTC
Labels: as-designed, extensions
