### ISSUE TITLE
Crash unexpectedly

### ISSUE THREAD

**Issue by kentng201** [microsoft/vscode#97587] opened 2020-05-12 08:30 UTC
Issue Type: <b>Bug</b>

The visual studio code always auto close with unknown issue, can help me to find out the problem?
It comes about 3 months, in these time the vscode always up-to-date to that time latest version.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexdima** [comment] 2020-05-12 09:02
Duplicate of #97586

**Closed by alexdima** 2020-05-12 09:02 UTC
Labels: new release
