### ISSUE TITLE
When carat is at beginning of line in editor and then ctrl-f is used to search for text, ctrl-f is automatically is "search selection mode"

### ISSUE THREAD

**Issue by Fozzy0007** [Microsoft/vscode#13695] opened 2016-10-13 18:32 UTC
This regressed recently in one of the daily updates.  looks like it selects the two lines from where the carat is.  I must manually turn off "search selection" in the find dialog so that I can actually search the file

- VSCode Version: Code - Insiders 1.7.0-insider (5dd716eaedc5a239379013863568c7f7dea708a5, 2016-10-13T08:02:00.080Z)
- OS Version: Windows_NT ia32 10.0.14943
- Extensions: ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2

Steps to Reproduce:

1. click beginning of line
2. ctrl-f
3. type in a string that should be later in the file

expected: find string
result: searches line where carat is only

**Comment by roblourens** [comment] 2016-10-13 20:58
Dupe of #13621

**Closed by roblourens** 2016-10-13 20:58 UTC
