### ISSUE TITLE
Completely back square "window" appears and is unresponsive.

### ISSUE THREAD

**Issue by Elsewhere42** [microsoft/vscode#117780] opened 2021-02-26 17:43 UTC
Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1.  Execute code.exe
2.  Completely back square "window" appears and is unresponsive.
3. The only way to open VS Code is with "code --disable-gpu"

Is there any way to change a setting in VS Code so the gpu is always disabled?

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/27238937/109335403-98f23580-7827-11eb-957c-6e9212abf60d.png)

**Comment by avenmore** [comment] 2021-02-26 17:57
Duplicate of #114459?

**Comment by deepak1556** [comment] 2021-02-26 18:30
/Duplicate https://github.com/microsoft/vscode/issues/114459

This will be fixed with next release `1.54`

**Closed by deepak1556** 2021-02-26 18:30 UTC
