### ISSUE TITLE
When python.pythonPath includes ${workspaceFolder}, tasks that use ${config:python.pythonPath} fail to start

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#57551] opened 2018-08-30 00:05 UTC
_From @segevfiner on August 28, 2018 22:39_

## Environment data

- VS Code version: 1.26.1
- Extension version (available under the Extensions sidebar): 2018.7.1
- OS and version: Windows 10.0.17134.228 x64
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7.0 x64
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

## Actual behavior

When `python.pythonPath` includes `${workspaceFolder}`, tasks that use `${config:python.pythonPath}` fail to start:

```
> Executing task: ${workspaceFolder}\venv\Scripts\python.exe setup.py build_ext --inplace <

The system cannot find the path specified.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

## Expected  behavior

The tasks should start correctly. It's quite useful to use `${config:python.pythonPath}` in your tasks so as to use the Python version used by vscode-python to run the tasks.

## Steps to reproduce:
1. Create a virtualenv under your workspace: `virtualenv venv`
2. Select it as the Python interpreter of VS Code using the status bar. (`python.pythonPath` should be set to a path using `${workspaceFolder}`).
3. Create a task that uses `${config:python.pythonPath}` to run anything you want, and try to run it.

## Logs
Nothing relevant under default log level.

_Copied from original issue: Microsoft/vscode-python#2459_

**Comment by brettcannon** [comment] 2018-08-30 00:05
_From @bhrutledge on August 29, 2018 13:47_

I stumbled upon this issue by way of #1664.

My workspace settings (set automatically, I think):

```json
{
    "python.pythonPath": "${workspaceFolder}/venv/bin/python"
}
```

What I tried:

```json
{
    "label": "runserver",
    "type": "shell",
    "command": "${config:python.pythonPath} manage.py runserver",
    "problemMatcher": [],
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
```

Output:

```
> Executing task: ${workspaceFolder}/venv/bin/python manage.py runserver <

/usr/local/bin/bash: /venv/bin/python: No such file or directory
The terminal process terminated with exit code: 127
```

Changing `command` to `${workspaceFolder}/venv/bin/python manage.py runserver` works. Just using `manage.py runserver` doesn't work because the virtualenv isn't activated. Of course, if I were using pipenv, I'm guessing `pipenv run manage.py runserver` would do the job.

Aside: this makes me wonder if VS Code has a facility for defining a new task `type`, that would handle the virtualenv automatically.

**Comment by dbaeumer** [comment] 2018-08-30 09:05
This is actually not task related. What the user does is configuring a  like this `"python.pythonPath": "${workspaceFolder}/venv/bin/python"` but to my knowledge settings can't contain variables.

WE can do two things:

@sandy081 allow variables in settings in the first place
@isidorn improve the configuration resolver so that it looks at the value of a setting and if a variable is in there replaces it as well

Opinions?

**Comment by isidorn** [comment] 2018-08-30 09:13
@dbaeumer we do not support variables in settings - adding it would be a big door which I am not sure I would like to open.
Option 2 does not really make sense since we do not support variables in settings, so I am not sure why we should resolve again.

For now I suggest no action, and if more users ask for this we can look in Option 2 (which feels a bit ugly).

fyi @weinand

**Comment by dbaeumer** [comment] 2018-08-30 09:16
OK. Will keep as a feature request then.

**Comment by segevfiner** [comment] 2018-08-30 14:38
The `python.pythonPath` variable was generated by the extension after selecting an interpreter, and it was generated including `${workspaceFolder}`, rather than being directly specified by the user.

Being able to create tasks that use the workspace interpreter is needed to get development tasks that use packages installed in a virtualenv working correctly, without hardcoding an absolute path to Python which cannot be shared. You often install development tools for the project in a virtualenv rather than globally, and you likely want to define `setup.py` tasks too.

This use case is even mentioned in the documentation: [Tasks in Visual Studio Code - Variable Substitution](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution)! Which is where I got the idea from, and than got suprised when it didn't work.

It's also possible to support this using a custom task type (Should it be like shell or like process... That distinction is kinda annoying for task types like this), a task type can even activate the virtualenv, so you will be able to use it to run shell scripts that use Python too (If you make sure it can launch arbitary commands and not only Python scripts).

Another option is a custom variable expansion like `${pythonPath}`, instead of the generic `${config:*}`, but I don't think there is an extension API for that.

Yet another option is to implement something like `${configExpanded:*}`, that's not exactly pretty though...

**Comment by dbaeumer** [comment] 2018-08-30 19:33
The problem is that you can either resolve a variable or a setting. But settings themselves don't have variable support right now. 

Using a custom task makes sense here since you then have full control over what is called. The difference between `shell` and `process` is comparable to the node API difference between `child_process.exec(command[, options][, callback])` which runs a command in a shell and `child_process.spawn(command[, args][, options])` with `options.shell: false`.

**Comment by segevfiner** [comment] 2018-08-30 19:39
> The difference between shell and process is comparable to the node API difference between child_process.exec(command[, options][, callback]) which runs a command in a shell and child_process.spawn(command[, args][, options]) with options.shell: false.

Of course, but should a "python" task type be like "shell" or like "process". :wink:

**Comment by segevfiner** [comment] 2018-08-31 13:26
> It depends on. If the pyhton tasks wants to execute a shell script it should be a shell task. If it is a executable you should use a process task to have full control over the args since there will be no shell interpretation. If you want shell interpretation for the args (e.g. wild card expanding under bash for example) then even if it is a binary executable use a shell task.

Yeah I know about this but of logic. I was talking about if you implement a custom "python" task in the extension, should it act like the "shell" task type or the "process" task type. Since the distinction is made based on the task type and not a separate `"shell": true/false` flag.

**Comment by brettcannon** [comment] 2018-08-31 21:58
FYI I've re-purposed the original issue on the Python extension's side to stop inserting `${workspaceFolder}` into `settings.json`. Sorry about the mix-up.

**Comment by alexr00** [comment] 2019-10-08 13:12
Since the issue is that settings do not support variables, and the python extension was adding a variable to settings, I'm going to close this issue.

It also seems that the python extension has fixed the bug of adding a variable to settings. Please feel free to ping this issue if the problem still hasn't been addressed.

**Closed by alexr00** 2019-10-08 13:12 UTC
Labels: feature-request, tasks
