### ISSUE TITLE
Two separate panels

### ISSUE THREAD

**Issue by simonknittel** [microsoft/vscode#104172] opened 2020-08-06 11:37 UTC
I would like to able to have two separate panels open (in addition to the sidebar), one at the bottom and one at the right side.

Why would I need this? I would move the integrated terminal to the bottom since sometimes it outputs long text lines which get a lot of line breaks when it's on the side since then panel is too narrow. Expanding the panel all the time is a bit annoying. If I could move the terminal to the bottom, it gets the space to get much wider and less line breaks are required. In addition to that I would like to keep open a few other panes which then I could put into the second panel at the right.

**Comment by IllusionMH** [comment] 2020-08-06 15:55
Looks like duplicate of #26777

**Comment by simonknittel** [comment] 2020-08-06 16:01
Ah, you are right. Didn't find it before. While the initial request in that issue is kinda already possible by having the sidebar and the panel, the later suggestion especially https://github.com/microsoft/vscode/issues/26777#issuecomment-576998706 is what I'm looking for. Three places to attach stuff to (left, right and bottom).

**Closed** 2020-08-06 16:09 UTC
