### ISSUE TITLE
Codelens fails with 'Actual command not found' when searching for references on TS file

### ISSUE THREAD

**Issue by khaosdoctor** [microsoft/vscode#220046] opened 2024-07-05 09:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91
- OS Version: MacOS Sonoma 14.5

version dump:
```
Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

# Description

I'm getting a weird error in every file I edit, every time I click the codelens hint for the references on top of any function:
![image](https://github.com/microsoft/vscode/assets/3200560/64facac9-cbe1-4ff9-86df-ed516e7fe692)

I get these errors:
![image](https://github.com/microsoft/vscode/assets/3200560/4b710ac6-d73d-447e-beb2-8497ea791643)
![image](https://github.com/microsoft/vscode/assets/3200560/86f4c62d-97b8-4d89-9608-0c411ca8f2ac)

The caveat is that, when I open code, it works for a brief moment, even with extensions disabled, then it stops working, the only option is to right-click and then click "show references" which seems to work.

This was also mentioned in this issue https://github.com/microsoft/vscode/issues/84153

Steps to Reproduce:
1. Open any TS project with Code
2. Click the inlay hint for references in code lens
3. The notification should open with the error

**Comment by gjsjohnmurray** [comment] 2024-07-05 11:06
Please use the Start Extension Bisect command to investigate.

**Comment by gjsjohnmurray** [comment] 2024-07-05 11:07
Another idea is to run `Profiles: Create a Temporary Profile` from Command Palette and see if it still occurs.

**Comment by khaosdoctor** [comment] 2024-07-05 12:15
> Please use the Start Extension Bisect command to investigate.

But the issue is still happening even with all the extensions disabled

**Comment by khaosdoctor** [comment] 2024-07-05 20:23
> Then I was confused by your first screenshot showing a complexity codelens, which I think comes from an extension.

Oh I'm sorry, yes that comes from an extension, but it's just because I took the screenshot from the normal profile, the error happens when I click on the "xx references", with or without any extension.

The weird though is that if I completely restart code, and click on it asap, the reference hint works for about 1s then it breaks. Also tested this with and without extensions

**Comment by mjbvz** [comment] 2024-09-23 22:08
@jrieken Adding you as it looks like the lifecycle for these code lens commands may have a bug

**Comment by jjaychen1e** [comment] 2024-12-10 08:20
Same issue here whe clicking references / implementations

**Comment by jrieken** [comment] 2024-12-16 09:41
closing as duplicate of https://github.com/microsoft/vscode/issues/226936

**Closed by jrieken** 2024-12-16 09:41 UTC
Labels: bug, code-lens
