### ISSUE TITLE
Terminal problem

### ISSUE THREAD

**Issue by OhYee** [Microsoft/vscode#7524] opened 2016-06-10 10:37 UTC
- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:

1. Input some Chinese characters in terminal
2. You will find the characters overlapped

![](http://images.cnblogs.com/cnblogs_com/ohyee/720846/t_QQ%E6%88%AA%E5%9B%BE20160610183401.png)

----

终端里中文字符会重叠

**Comment by Tyriar** [comment] 2016-06-10 19:38
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-10 19:38 UTC
