### ISSUE TITLE
Opening a file with drag and drop into VSCode shows a "+ Copy" tooltip

### ISSUE THREAD

**Issue by kiewic** [microsoft/vscode#101444] opened 2020-06-30 19:28 UTC
Issue Type: <b>Bug</b>

Dragging a file over VSCode shows a confusing `+ Copy` tooltip, which gives the impression the file will be somehow copied at the file system level. However, if the file is dropped over VSCode, it is simply being opened as expected.

![VsCode-Drag-Drop](https://user-images.githubusercontent.com/874134/86168362-faada480-bacc-11ea-8e20-87a6b7b7d1f4.gif)

For comparison, on macOS, this tooltip is not displayed when realizing the same operation.

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:00:22.588Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment] 2020-07-01 06:34
I think I decided to pick "Copy" because the alternative suggests that the file is being moved:

![move](https://user-images.githubusercontent.com/900690/86210809-8975fc00-bb75-11ea-9b29-09b8bb98b10e.gif)

The file is not moved though, so copy seemed safer. If you have ideas how to improve this, let me know, otherwise closing as designed.

**Comment by kiewic** [comment] 2020-07-07 17:37
Can the tooltip say *open*? An alternative could be to be consistent with macOS, where the action only shows a plus sign. For example:

![drag-and-drop-on-macos](https://user-images.githubusercontent.com/874134/86820157-84192580-c03d-11ea-9d3f-7f78c1044602.gif)

**Comment by bpasero** [comment] 2020-07-08 05:57
We do not have any control about the native drag and drop feedback afaik.

**Comment by kiewic** [comment] 2020-07-08 07:31
Oh, I thought that tooltip was part of VSCode UI. Thanks for the clarification.

**Closed** 2020-07-08 07:51 UTC
Labels: needs more info
