### ISSUE TITLE
Git - Reverting uncommited lines duplicates other lines

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#114068] opened 2021-01-09 04:07 UTC
Issue Type: <b>Bug</b>

I've encountered some very strange behavior where when I revert some simple uncommited changes on some lines in my code using the built in git tools then some other lines further down or up the code (that are also uncommited changes) will duplicate. I can't even begin to wrap my head around what could be causing this. See the linked video that I recorded of the issue since I don't know how to describe this properly.

[Recording of the problem](https://youtu.be/rIxpmZKAYi0)

What other information should I provide to help better diagnose this issue?

Thanks.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (8)</summary>
Recording of the problem
Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|1.1.2
phpserver|bra|3.0.1
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt600cf:30241728
vsjup459cf:30237188

```

</details>

**Comment by ArthurYdalgo** [comment] 2021-02-16 02:55
I thought I was going crazy when I saw a bunch of duplicated lines. They were most often lines that wouldn't compromise the algorithm (besides doing the same thing multiple times), but when } are duplicated it's hell on earth.

For now I'm simply not using this feature because it's essentially a russian roulette and I never know when/where it happens

**Comment by rob151515** [comment] 2021-03-12 03:16
I also thought I was going mad there until I started comparing code before & after the 'Revert Change'. Also glad someone else has opened this issues as I also wasn't quite sure what was going on other than 'Revert Change' is causing me problems.

**Comment by samuelphy** [comment] 2022-05-18 12:33
I have now also experienced this issue running VScode 1.67.0. Reverted a change on row 79 and got a new set of curly brackets inserted 100 lines below.

**Comment by ASSmirnov** [comment] 2023-03-07 13:27
The issue is still with us, VScode 1.76.0

**Comment by robbitt07** [comment] 2023-03-07 14:18
Same, now having the issue with VScode 1.76.0

**Comment by leog** [comment] 2023-03-07 14:46
This issue is becoming increasingly annoying!

**Comment by 21febbraio** [comment] 2023-03-08 00:57
Same problem here

**Comment by JacobTheEldest** [comment] 2023-03-08 17:59
I have this problem as well. I've used this feature before with no problems, so I thought an extension might be causing it. I ruled that out by disabling all extensions, and I still see the same issue.

**Comment by it-is-michal** [comment] 2023-03-08 21:20
Confirm as well. When I revert a change it will not only multiply the chunk that I wanted to revert but also do the same thing to other changes in this particular file.

I'm not seeing anything standing out in developer tools or a few of the checked outputs. Please let me know if and how can I enhance this report.

Attaching some information about my setup.

---

CPUs | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1800)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 1, 1, 2
Memory (System) | 31.09GB (14.34GB free)
Process Argv | --unity-launch --crash-reporter-id 81bb4573-223b-41e7-b365-1f4680e3b522
Screen Reader | no
VM | 0%

---

Remote | Dev Container: py3.11:Ubuntu-jammy:dind
-- | --
OS | Linux x64 5.14.0-1049-oem
CPUs | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1800)
Memory (System) | 31.09GB (14.35GB free)
VM | 0%

---

Remote | Dev Container: py3.7:Ubuntu-jammy:dind
-- | --
OS | Linux x64 5.14.0-1049-oem
CPUs | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1800)
Memory (System) | 31.09GB (14.34GB free)
VM | 0%

---

Extension | Author (truncated) | Version
-- | -- | --
emojisense | bie | 0.9.1
remotehub | Git | 0.52.0
vscode-peacock | joh | 4.2.2
dotenv | mik | 1.0.1
jupyter-keymap | ms- | 1.1.0
remote-containers | ms- | 0.282.0
remote-ssh | ms- | 0.98.0
remote-wsl | ms- | 0.76.1
vscode-remote-extensionpack | ms- | 0.24.0
azure-repos | ms- | 0.28.0
remote-explorer | ms- | 0.2.0
remote-repositories | ms- | 0.30.0
remote-server | ms- | 1.0.0
rewrap | stk | 1.16.3
pdf | tom | 1.2.2
better-toml | bun | 0.3.2
gitlens | eam | 13.3.2
vscode-pull-request-github | Git | 0.60.0
vscode-stashek | it- | 0.0.2
vscode-docker | ms- | 1.24.0
python | ms- | 2023.4.0
vscode-pylance | ms- | 2023.3.10
jupyter | ms- | 2023.2.1000592019
jupyter-keymap | ms- | 1.1.0
jupyter-renderers | ms- | 1.0.15
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5

(2 theme extensions excluded)</div></div><br class="Apple-interchange-newline">

**Comment by FranciscoCaldeira** [comment] 2023-03-08 21:27
I have this problem on 1.76.0 too and a workaround is to open command palette(ctrl+shift+p) and choose  >Developer: reload window

**Comment by it-is-michal** [comment] 2023-03-08 21:48
It didn't work for me :disappointed:

**Comment by prOOrc** [comment] 2023-03-08 21:58
I have this problem on 1.76.0 too. Downgrade to version 1.75.1 have helped me.

**Comment by aegwyng** [comment] 2023-03-08 22:45
Same problem here 

```
Version: 1.76.0 (Universal)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
```

**Comment by francesconazzaro** [comment] 2023-03-09 11:18
Same problem here
```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

**Comment by odeialba** [comment] 2023-03-09 14:49
Same problem here
```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

**Comment by 21febbraio** [comment] 2023-03-09 15:44
> I have this problem on 1.76.0 too. Downgrade to version 1.75.1 have helped me.

worked for me

**Comment by dejandujmovic** [comment] 2023-03-10 07:05
Seems like it is resolved in 1.76.1.
I assume this was the one: https://github.com/microsoft/vscode/issues/176051

**Comment by it-is-michal** [comment] 2023-03-10 08:57
Yes! :tada: 
I can confirm that.

**Comment by lszomoru** [comment] 2023-12-12 21:16
Reopening the issue, as I have finally been able to reproduce this issue.

**Comment by lszomoru** [comment] 2023-12-13 13:44
Create a new text document, and commit it to source control.

```txt
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
```

Open the file and:
  * delete the line that has "4"
  * add a space on line that has "5"
  * delete line that has "6"
  * delete the line that has "17"
  * add a space on line that has "18"
  * delete the line that has "19"

At this point you should have the following state. Notice the "touching" delete/modified decorations:
<img width="67" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/7ba9fd78-9350-4e3e-82b4-6073da8f6958">

Click on the decorator on line 15, and revert the change. Notice the result:
<img width="78" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/edba25be-0fcc-4532-b624-f85a05987806">

**Comment by lszomoru** [comment] 2024-12-19 20:01
Apologies for not getting back to you on this until now. In recent days I have pushed some changes that address some of the issues with the "stage/unstage/revert selected ranges" commands. I would really appreciate if you could try the latest [VS Code Insiders release](https://code.visualstudio.com/insiders/) (version information below) and would let me know if that resolves the problem. In case you are still able to reproduce the issues I would really appreciate if you could:
1. See if you are able to reproduce in a simple repository which you could share
2. Share a recording (https://gifcap.dev) assuming that you are able to consistently reproduce the issue
3. Let me know if you are invoking the command from a text editor or a diff editor
4. If you are using a diff editor see if you can reproduce the problem when using the "Revert Selection" command available in the editor gutter. 

```
Version: 1.97.0-insider
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```

**Closed by lszomoru** 2024-12-19 20:01 UTC
Labels: bug, git
