### ISSUE TITLE
ambigous html code highlighting

### ISSUE THREAD

**Issue by noontz** [microsoft/vscode#150679] opened 2022-05-30 06:15 UTC
Issue Type: <b>Bug</b>

1.Add a button in a html document
2.Add an onclick listener inline
3. repeat 1. 2. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.05GB free)|
|Process Argv|--crash-reporter-id 1e6d5089-6165-45ec-844d-5f2ea6a18690|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
vscode-eslint|dba|2.2.2
svg|joc|1.4.18
vetur|oct|0.35.0
LiveServer|rit|5.7.5
comment-ts|sal|1.0.21
shader|sle|1.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

![vs_code_bug](https://user-images.githubusercontent.com/7408674/170928633-7b18d2f5-94d5-44c5-bf6e-1d2a69976c0c.png)

**Comment by aeschli** [comment] 2022-05-30 14:06
Can you paste the code snippet to reproduce?
I was not able to do so with the following (similar) snippet:
```
<div>
	<button onclick="goBack()">Back</button>
	<button onclick="openUsers()">Users</button>
	<span</span>
	<button onclick="logOut()">LogOut</button>
	<button onclick="logOut()">LogOut</button>
</div>
```

**Comment by noontz** [comment] 2022-06-02 08:00
Hi sorry for not replying.. I'm on vacation. But I assume you might need a reference in the html to the js file containing the window.logout definition.

**Comment by aeschli** [comment] 2022-06-02 09:28
Ah, now I see the problem, the second `onClick` attribute uses a upper case `C`.

This is a bug in the HTML grammar and the issue is: https://github.com/textmate/html.tmbundle/issues/104

Closing as duplicate

**Closed by aeschli** 2022-06-02 09:28 UTC
Labels: needs more info
