### ISSUE TITLE
Edit sessions are not same

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161936] opened 2022-09-27 09:55 UTC
Testing #161860

- I have opened VS Code repo in VS Code Desktop and insiders.vscode.dev
- Stored some edit sessions
🐛 Second edit session (from insiders.vscode.dev) is not showing the changes in Desktop

<img width="491" alt="image" src="https://user-images.githubusercontent.com/10746682/192495515-74cb142a-9b7c-4dc4-8d41-f2cc15b5d6b8.png">

**Comment by joyceerhl** [comment] 2022-09-28 18:50
Likely also duplicate of https://github.com/microsoft/vscode/issues/161939

**Closed by joyceerhl** 2022-09-28 18:50 UTC
