### ISSUE TITLE
`code-insiders --locate-shell-integration-path fish` returning a non-existent path

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#232537] opened 2024-10-29 22:13 UTC
Type: <b>Bug</b>

`code-insiders --locate-shell-integration-path fish` is returning for me `/home/brett/.vscode-server-insiders/bin/workbench/contrib/terminal/browser/media/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish`, but unfortunately `/home/brett/.vscode-server-insiders/bin/workbench/` does not exist.

VS Code version: Code - Insiders 1.95.0-insider (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:14:20.189Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.66GB (44.58GB free)|
|Process Argv|--crash-reporter-id 8c2d3e93-0526-420f-a934-b71e879abff1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 0)|
|Memory (System)|31.18GB (28.23GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 0)|
|Memory (System)|31.18GB (28.23GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-todo-highlight|jgc|2.0.8
remote-wsl|ms-|0.88.4
ruff|cha|2024.54.0
copilot|Git|1.243.0
copilot-chat|Git|0.22.2024102902
vscode-pull-request-github|Git|0.101.2024102916
debugpy|ms-|2024.13.2024101501
python|ms-|2024.17.2024102201
vscode-pylance|ms-|2024.10.103
even-better-toml|tam|0.19.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
962ge761:30841072
9b8hh234:30694863
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by brettcannon** [comment] 2024-10-29 22:14
![Image](https://github.com/user-attachments/assets/a6e421ac-a127-4e7c-8bf6-f1ed30ce20cc)

**Comment by DiabloRex** [comment] 2024-10-30 02:54
Same problem here on zsh.
no such file or directory: ~/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh

However, the file location is "~/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/server/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh"

So, the problem solved by creating the folder and copy the file to the created folder, and this works for me.
mkdir -p ~/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/workbench/contrib/terminal/browser/media
cp ~/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/server/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh ~/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh

**Comment by bpasero** [comment] 2024-10-30 08:22
Should be fixed by https://github.com/microsoft/vscode/commit/1330eb738986802e906df1beda0e3a2334fca820

Please check with latest insiders today: Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2024-10-30 08:22 UTC
Labels: bug

**Comment by brettcannon** [comment] 2024-10-30 18:14
It worked for me!
