### ISSUE TITLE
extensions host terminated 

### ISSUE THREAD

**Issue by CuongCoder** [Microsoft/vscode#60121] opened 2018-10-08 06:17 UTC
Issue Type: <b>Bug</b>

extensions host terminated 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.17.13-041713-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2799)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 3, 4|
|Memory (System)|7.68GB (1.09GB free)|
|Process Argv|/snap/vscode/59/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
es7-react-js-snippets|dsz|1.8.6
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
react-native-react-redux|EQu|1.9.1
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
beautify|Hoo|1.4.4
useful-react-snippets|igo|1.4.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
color-highlight|nau|2.3.0
vetur|oct|0.13.0
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.0
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
sass-indented|rob|1.4.9
indenticator|Sir|0.6.0
code-spell-checker|str|1.6.10
language-stylus|sys|1.10.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by studioljw** [comment] 2018-10-09 00:42
Since the 1.20 update this evening, I have been having the same issue. The error comes back as "Extension Host has unexpectedly crashed".

**Comment by carlocardella** [comment] 2018-10-09 16:32
My Extension Host was crashing due on an out of memory exception (console log attached), since I was seeing some other weird behaviors with other extensions I have deleted my local extension folder (C:\Users\carlo\\.vscode) and restored my config using shan.code-settings-sync, and the crash seems to be gone

[-1539099125320.log](https://github.com/Microsoft/vscode/files/2461317/-1539099125320.log)

**Comment by alexandrudima** [comment] 2018-10-16 08:04
@CuongCoder Does the crash reproduce when disabling all extensions? What does the Extension Host log show? (`F1 > Developer: Show Logs ... > Extension Host`)

@carlocardella The log shows that execution was in this extension -- `fabiospampinato.vscode-highlight-1.2.9` -- right before the OOM crash. Can you please reach out directly to @fabiospampinato and perhaps attempt to distill reproducible steps...

**Comment by fabiospampinato** [comment] 2018-10-16 22:30
@alexandrudima there was an bug in vscode-highlight@1.2.10 where non-global regexes caused the extension to loop endlessly, causing the extension host to eventually crash.

If you want to reproduce it exactly install the attached extension and add the following to your settings:

```
  "highlight.regexes": {
    "(foo)": {
      "regexFlags": "i",
      "decorations": [{}]
    }
```

[vscode-highlight-1.2.10.vsix.zip](https://github.com/Microsoft/vscode/files/2485157/vscode-highlight-1.2.10.vsix.zip)

It looks like there's another issue probably caused by regexes that are too broad (like `(.)`), maybe too many decorations get created or something, I'm working on a fix for this one too.

@carlocardella were you doing any of those things maybe?

**Comment by carlocardella** [comment] 2018-10-16 23:17
@fabiospampinato not that I can remember but in those days I was also troubleshooting the performance startup problem with Todo+, I was messing around with settings and extensions...

**Comment by alexandrudima** [comment] 2018-10-17 06:55
@fabiospampinato @carlocardella Thank you for following up.

Let's continue using this issue for @CuongCoder 

@CuongCoder Does the crash reproduce when disabling all extensions? What does the Extension Host log show? (`F1 > Developer: Show Logs ... > Extension Host`)

**Closed** 2018-10-24 07:12 UTC
Labels: needs more info
