### ISSUE TITLE
Highlighting wrong in code blocks in markdown file.

### ISSUE THREAD

**Issue by shivanshu-semwal** [microsoft/vscode#136039] opened 2021-10-28 14:28 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04.3 LTS x86_64

Steps to Reproduce:

1. Crete a new markdown file
2. Put this in the file in the file.

```c
void bubble_sort(int *arr, int n){
  for(int i=0;i<n;i++){
    printf("Hello world");
  }
}
```

![image](https://user-images.githubusercontent.com/53912074/139276323-77a39613-a6fc-4fbc-be58-00be728735bc.png)

My guess is that `<` is causing the problem. Here is the same thing with `<` replaced with `=`

![image](https://user-images.githubusercontent.com/53912074/139276663-cb582626-3eb6-49d1-b2b1-c013dad06fb9.png)

**Comment by mjbvz** [comment] 2021-11-10 00:21
Duplicate of #118300

Out of scope for VS Code itself since this is a problem with the c/C++ grammar we are picking up

**Closed by mjbvz** 2021-11-10 00:21 UTC
Labels: markdown, grammar
