### ISSUE TITLE
auto complete clobbering existing text

### ISSUE THREAD

**Issue by ace510** [microsoft/vscode#82404] opened 2019-10-12 00:53 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

whenever I start to type more text into an existing string and intellisense completes a variable name, instead of inserting the text and moving what's after it out, the variable overwrites the rest, for example

print(f+bazz)

completes to
print(fooooazz)

when I would prefer
print(foooo+bazz)

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:44:05.506Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.2
python|ms-|2019.11.41569-dev
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0-insiders2
Go|ms-|0.11.7
java|red|0.50.0
vscode-xml|red|0.9.0
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|1.1.30
code-spell-checker|str|1.7.18
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
jinja|who|0.0.8

</details>

**Comment by usernamehw** [comment] 2019-10-12 07:30
duplicate of #82324 ?

**Closed** 2019-10-14 07:05 UTC
Labels: *duplicate
