### ISSUE TITLE
Incorrect syntax highlighting for Javascript raw strings

### ISSUE THREAD

**Issue by parkertomatoes** [microsoft/vscode#110011] opened 2020-11-05 11:02 UTC
- VSCode Version: 1.50.1
- OS Version: Windows 10 Version 1809

Steps to Reproduce:

1. Open a javascript file
2. Type `String.raw"Hello\nworld"`
3. Observe that the `\n` is highlighted as an escape character
![image](https://user-images.githubusercontent.com/6298931/98232730-06522180-1f2c-11eb-9d1b-ec48a5935c28.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-11-05 19:43
1. This example is invalid, you need to use a template string:

```js
String.raw`Hello\nworld`
```

2. The `\n` highlighting still happens in that case too but I'm closing this as out of scope since it's not worth it to try conditionally disabling the highlighting based on what a function does with a string

**Closed by mjbvz** 2020-11-05 19:43 UTC

**Comment by felixhao28** [comment] 2020-12-07 04:16
> 1. it's not worth it to try conditionally disabling the highlighting based on what a function does with a string

Maybe we should treat `String.raw` as an exception because it is built-in?

**Comment by wyckster** [comment] 2020-12-29 04:11
I personally don't like it when things get closed as being _out-of-scope_ without a satisfactory explanation (no offense @mjbvz but the explanation was a little brief), so let me offer some sympathy and a longer explanation.  I've thought a lot about this and I'd like to offer my opinions about both sides of this issue.

Consider the example code at [mozilla.org's documentation for String.raw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw )

That example code is:
```js
const filePath = String.raw`C:\Development\profile\aboutme.html`;
```

That **exemplary** code is highlighted in vscode as shown below. 

![image](https://user-images.githubusercontent.com/6098274/103254385-177b4580-4953-11eb-9848-a8130f0d480a.png)

Firstly, I'd like to sympathize with @parkertomatoes that this indeed causes false-alarm panic that perhaps a critical filename string may have been incorrectly escaped.  Something admittedly feels wrong with this experience.

---

On the other hand, I'd like to call attention to the fact that both the cooked and raw template strings are in fact generated and available at run-time, even to the `String.raw` function, and either could be used at run-time regardless of the tag function expression.

Consider [this example](https://exploringjs.com/impatient-js/ch_template-literals.html#cooked-vs.-raw-template-strings-advanced) (excerpted below) which makes use of both the raw and cooked literals.  It shows clearly how the first argument to the tag function is a collection of templateStrings

```js
function cookedRaw(templateStrings, ...substitutions) {
  return {
    cooked: [...templateStrings], // copy just the Array elements
    raw: templateStrings.raw,
    substitutions,
  };
}
```

Also, [this website](https://dev.to/joelhassan/js-tagged-template-literals-26ff) gives an implementation of manual substitution as follows:

```js
function someTag(literals, ...substitutions) {
  let returnString = literals.reduce((stringsJoined, currentString, i) => {
    return stringsJoined + currentString + (substitutions[i] || "")
  }, "")
  return returnString
}
```

And one could easily replace `literals.reduce` with `literals.raw.reduce` in the above code and then you'd have a manually crafted version of `String.raw`. Then one could wantonly redefine `String.raw = someTag`, (or any other tag function) so it would be impossible to determine during syntax highlighting what the interpretation of the string escapes will be during processing of the tag function.

To push this further, the [grammar of a tagged template literal](https://tc39.es/ecma262/#sec-tagged-templates-runtime-semantics-evaluation) allows for it to be preceded by a _MemberExpression_ or _CallExpression_.  So again, as a matter of ***syntax*** one could legally write a tag function that returned another tag function and indeed chain the templates together without error, further complicating the static analysis required to produce correct highlighting. 

```
let mytag = () => String.raw
let result = mytag`what\now``hello\world`
```

This would be _challenging_ for the syntax highlighter to statically analyze, to say the least!

My overall point is that the syntax of the escape sequences is that they're still syntactically special even when passed to `String.raw`.  So it's still logical to highlight the escape sequences, even if it is occasionally undesirable, depending on the context.

---

Of perhaps peripheral relevance at this point is the [treatment of Unicode escape sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates_and_escape_sequences).

According to this [Template Literal Revision], this would be legal:

```
let illegal = `\unicode`; // This untagged template Unicode escape sequence is illegal 
let legal = String.raw`\unicode`; // This tagged template sequence *is* legal
```
![image](https://user-images.githubusercontent.com/6098274/103257199-3e8b4480-495e-11eb-80ee-ecbc3acf18fb.png)

The reason I mention this is that there must be a cooked version of even illegal escape sequences.  (Indeed they become `undefined`)  And in terms of highlighting and calling attention to errors, it's still worth cautioning that the illegal escape sequence is being used in the template -- even if the implementation of `String.raw` is correctly disregarding the cooked version being passed to it.

---

I think the highlighting is correct as is (not a bug).  But the experience could definitely benefit from not raising false alarms. Attempts to reduce panic and stop highlighting the escape sequences when the highlighting engine is confident the tag function is indeed `String.raw` would have to make context-sensitive assumptions about what the value of `String.raw` is at run-time.  I have no idea how vscode developers may eventually figure out how to do it.  I think it will be **very** challenging to get acceptable behaviour, and I believe that is the ultimate reason that this is closed as being _out-of_scope_.

For now, we can rest assured that there *is* meaning to the escape sequences in any tagged template litera (even raw), and as a matter of purely ***syntax***, the highlighting is logical.  This highlighting gives the most correct understanding of what is happening at during parsing and also what is happening at run-time.

As far as I know, the language does not offer a way to specify a string literal where the escape sequences are taken verbatim while the code is being compiled in a way that is unambiguous to the syntax highlighter.  It is a philosophical discussion to have with language experts to see if it's worth it to add syntax for a verbatim string literal that one could be confident couldn't be sabotaged at run-time.

---

And finally, as a workaround, users are welcome to customize the highlighting to be of even less contrast or even no contrast at all.

But I feel ya, @parkertomatoes !
