### ISSUE TITLE
Hover in JSON files has quiete some white space

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2356] opened 2016-01-26 14:35 UTC
See screen shot

![capture](https://cloud.githubusercontent.com/assets/1931590/12582929/521171a8-c440-11e5-8f05-70694154de9f.png)

The hover looks more compact for TS files for example.

**Comment by jrieken** [comment] 2016-01-27 08:28
duplicate of #2344

**Closed by jrieken** 2016-01-27 08:28 UTC
Labels: bug, json
