### ISSUE TITLE
Make relative cwd values relative to the workspace root

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3100] opened 2016-02-18 00:30 UTC
Since the january release, when I open VS Code from the start menu and (last opened project opens) and hit Ctrl+Shift+B, I get

```
Failed to launch external program gulp .
spawn C:\Windows\system32\cmd.exe ENOENT
```

I can of course asure you that C:\Windows\system32\cmd.exe does exist and gulp is installed globally and in PATH. I can restart Code as many times as I want, it only works when opening Code though right click on folder > open with Code.

**Comment by dbaeumer** [comment] 2016-02-18 16:13
I wasn't able to reproduce using Windows 10.

@felixfbecker can you provide your tasks.json ? And which version of Windows are you on. 

This is strange since I don't do anything special when launched from the start menu. Does it work when you use code . from the cmd shell?

**Comment by felixfbecker** [comment] 2016-02-21 10:12
@dbaeumer I can only reproduce it in one of my projects, where the project structure looks like this:
```
|--.vscode
|  |--launch.json
|  |--settings.json
|  \--tasks.json
|--client
|  |--build
|  |--node_modules
|  |--src
|  |--.eslintrc.json
|  |--gulpfile.js
|  |--package.json
|  \--README.md
|--server
|  |--public
|  |--src
|  |--vendor
|  |--composer.json
|  |--composer.lock
|  |--config.ini
|  \--example_config.ini
|--.editorconfig
\--.gitignore
```
Gulp is installed both locally (in client/node_modules) and globally. 
Here is my tasks.json:
```json
{
  "version": "0.1.0",
  "command": "gulp",
  "isShellCommand": true,
  "showOutput": "silent",
  "options": {
    "cwd": "client",
    "env": {
      "NODE_ENV": "development"
    }
  },
  "tasks": [
    {
      "taskName": "build",
      "isBuildCommand": true
    },
    {
      "taskName": "watch",
      "isWatching": true
    }
  ]
}
```
As you can see, I set the cwd to client since I only have Gulp tasks for my client.
Here is the error again:
```
Failed to launch external program gulp .
spawn C:\WINDOWS\system32\cmd.exe ENOENT
```
The bug occurs only when starting from the start menu, starting with explorer context menu and starting from command line works aswell.

The shortcut's target is `"C:\Program Files (x86)\Microsoft VS Code\Code.exe"`, and the cwd of the shortcut is set to `"C:\Program Files (x86)\Microsoft VS Code"`. This is the default shortcut created on installation.

Any other project works too. I assume it has something to do with setting the cwd.

I am on Windows 10 Pro, newest updates and VS Code January.

**Comment by felixfbecker** [comment] 2016-02-21 10:14
I found a fix, setting `cwd` to `${workspaceRoot}/client` fixed it. But it is still weird that this occurs only when running Code from the start menu.

**Comment by dbaeumer** [comment] 2016-02-29 19:47
@felixfbecker thanks for the additional info. I suspect that the working directory of the process is different when started from the start menu which makes client then relative to that directory. I change the title since the right fix would be to either forbid relative values or make the predictable (e.g relative to the workspace root).

**Comment by alexr00** [comment] 2018-12-20 14:44
There have been a lot of changes around cwd in the last couple months, let alone the last couple years 😊 Closing until there's a report of this happening recently.

**Closed by alexr00** 2018-12-20 14:44 UTC
Labels: feature-request, tasks
