### ISSUE TITLE
Peek definition scrolls the files

### ISSUE THREAD

**Issue by FcTD4mN** [Microsoft/vscode#36360] opened 2017-10-16 13:52 UTC
- VSCode Version: Code - Insiders 1.18.0-insider  de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T05:22:08.224Z  
- OS Version: Linux x64 4.13.4-200.fc26.x86_64 
- Extensions:  cpptools|ms-|0.13.1
- Steps to Reproduce: Peek a definition on the bottom part of the screen in a C++ file, then close the peek view using shortcut (esc)

I don't know if it is intentional or not, but since the last update, when i peek a definition, it scrolls the file so the function within the peek editor gets on top of the screen.
Not sure if i like this behaviour all that much, as it forces you to scroll back up to see the close button.
The real problem then comes when i close the peek view using a shortcut (esc by default), it doesn't scroll back down, so i lose the line i was working on :

![peekexample](https://user-images.githubusercontent.com/29691930/31615363-9c554d00-b289-11e7-9f79-a0afd01087fd.gif)

**Comment by jrieken** [comment] 2017-10-17 07:20
duplicate of https://github.com/Microsoft/vscode/issues/36340

**Closed by jrieken** 2017-10-17 07:20 UTC
Labels: editor, editor-contrib
