### ISSUE TITLE
Overall perf. issue with TypeScript(JS)

### ISSUE THREAD

**Issue by berkaey** [microsoft/vscode#72362] opened 2019-04-15 19:02 UTC
Issue Type: <b>Performance Issue</b>

- When did this performance issue happen? 
After updating to 1.33 (everything is still fine at 1.32) 
- Does it occur on startup or after a specific series of actions? 
It happens when you need to use TypeScript Intellisense.

PS: I didn't experience this in a TypeScript Project, My Project is a ES6 JS Project.

It really got messy when you try to cmd/ctrl+click to anything.

PS2: removing TypeScript cache helps a bit but after an hour it became slow again

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	    90	 44270	code main
    6	    49	 44271	   gpu-process
    5	   262	 44272	   window (glocalzone (Workspace))
    0	   156	 44421	     extensionHost
    0	   492	 44427	       electron_node tsserver.js 
    0	    74	 44437	         electron_node typingsInstaller.js typesMap.js 
    0	   467	 44428	       electron_node language-server-stdio.js 
    0	    57	 44430	       electron_node server.js 
    0	    98	 44431	       electron_node eslintServer.js 
    0	    33	 44438	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=44421
    1	    49	 44460	       electron_node server.js 
    0	   147	 44511	       extensionHost
    0	   123	 44521	       extensionHost
    0	   139	 44523	       extensionHost
    0	    25	 44422	     watcherService
    0	    41	 44426	     searchService
    0	    74	 44423	   shared-process
    0	    74	 44546	   window (Issue Reporter)
    0	     0	 44551	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (glocalzone (Workspace))
|    Folder (gz-api): 98 files
|      File types: js(66) graphql(11) json(9) DS_Store(4) yml(1) graphqlrc(1)
|                  babelrc(1) sh(1) gitignore(1) lock(1)
|      Conf files: package.json(1) webpack.config.js(1)
|    Folder (gz-app): more than 24620 files
|      File types: hpp(7604) flat(2181) h(1749) pcm(835) timestamp(790)
|                  png(611) jar(579) hmap(240) xml(202) m(194)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-cmd-shift-d|and|1.2.2
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
path-autocomplete|ion|1.13.2
styled-components-snippets|jon|0.1.7
vscode-styled-components|jpo|0.0.26
vscode-wrap-console-log|mid|1.7.2
vscode-versionlens|pfl|0.22.0
macos-dark-mode-theme|phi|0.2.7
vscode-graphql|Pri|0.1.7
subtle-brackets|raf|3.0.0
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
mdx|sil|0.1.0
indenticator|Sir|0.6.0
ignore-gitignore|stu|1.0.1
selectline-statusbar|tom|0.0.2
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-04-15 21:54
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by xserber** [comment] 2019-04-16 01:09
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Yes, on the insider assembly, in my TypeScript project (TSX) this is repeated.

**Comment by berkaey** [comment] 2019-04-16 07:21
I forgot to mention this but beside the slowness, intellisense got not so intelligence :) (go to wrong root definitions or just stuck at same definition)

**Comment by mjbvz** [comment] 2019-04-22 18:50
@berkaey Did you test on insiders? Also, do you have `@types/styled-components` in your `node_modules`?

**Comment by berkaey** [comment] 2019-04-23 06:47
No I didn't. and No both workspace folders doesn't have `@types/styled-components` in node_modules.

**Comment by berkaey** [comment] 2019-04-23 06:48
btw, @mjbvz, you mean insiders version? if it so, how can i download it ?

**Comment by mjbvz** [comment] 2019-04-23 18:50
https://code.visualstudio.com/insiders/. Test with all extensions disabled

**Comment by berkaey** [comment] 2019-04-24 06:50
Hey @mjbvz, I tested for 10 mins without any extensions, I guess it is much better than 1.33 but I think still has slower navigation on some case and sometimes it goes to import definition first sometimes it  just goes to file itself.

**Comment by berkaey** [comment] 2019-04-24 14:18
@mjbvz, after a full-day test on insider(with extensions) issue still stands. A bit more fast than 1.33 but lags behind 1.32

**Comment by mjbvz** [comment] 2019-04-24 17:31
@berkaey So this didn't happen when you disabled all extensions? 

Also, can you share your project?

**Comment by berkaey** [comment] 2019-04-24 18:27
I tested without extensions only 10-20 min. 'cause I'm much slower without extensions :). Do you mean workspace file?

**Comment by codepunkt** [comment] 2019-04-26 08:56
@mjbvz We're using @types/styled-components. What's the deal with them?

**Comment by mjbvz** [comment] 2019-04-26 17:33
@berkaey If this only happens when extensions are enabled, then one of your extensions is causing this.

If you can share your project (as a github repo) then we can investigate this better

**Comment by berkaey** [comment] 2019-04-27 06:14
@mjbvz it is happening without extensions also, (but bit better from 1.33) I'm using same extensions on 1.32 and works flawlessly. (I'm actually had to use 1.32 otherwise all of my MacBook Pro fans just hit the ceil :) too much cpu I guess)

**Comment by swashata** [comment] 2019-05-02 15:11
I do have `styled-components` and it happens with me also. Here's a list of possibly heavy libraries I am using

1. React/React DOM
2. Apollo Client with `react-apollo`.
3. Styled components.
4. Ant design.

I am using the following version of vscode

```
$ code --version
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
```

I think it is slow mostly on `tsx` files.

**Comment by mjbvz** [comment] 2019-05-02 16:43
@berkaey Can you try  changing your workspace to use `typescript@3.3`  by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions). If using the older typescript works in current VS Code builds, then try switching to the current nightly build of typescript by installing `typescript@next` to see if the issue has been resolved

**Comment by berkaey** [comment] 2019-05-02 17:02
@mjbvz  I'm not using typescript, no tax files in my workspace (but as you now most of the node_modules libs are typed like styled-components etc.)

**Comment by mjbvz** [comment] 2019-05-02 17:09
Typescript powers our javascript intellisense. Try those steps

**Comment by swashata** [comment] 2019-05-03 03:08
@mjbvz Do you think it is happening because of [this issue](https://github.com/Microsoft/TypeScript/issues/30663) in typescript itself?

I investigated because it was not only vscode which was slow, rather `fork-ts-checker-webpack-plugin` results too. So I did some benchmarking and

For typescript version `3.4.5` with `@types/styled-components@4.1.14`
 
```
yarn typecheck  11.16s user 0.56s system 154% cpu 7.611 total
```

For typescript version `3.5.0-dev.20190502` with `@types/styled-components@4.1.14`

```
yarn typecheck  8.66s user 0.53s system 168% cpu 5.452 total
```

Overall vscode ts intellisense is much faster now. Also `fork-ts-checker` plugin performs better.

**Comment by natew** [comment] 2019-05-03 03:17
I'm also getting this, not using `styled-components`. At one point I had narrowed it down to `react-spring@8.x`, but upgrading to their new types in the 9 beta and it's still slow.

**Comment by swashata** [comment] 2019-05-03 03:23
Also for typescript `3.3.4000` with `@types/styled-components@4.1.14`

```
yarn typecheck  6.79s user 0.39s system 171% cpu 4.180 total
```

So think switching to typescript `3.3.4000` until the problem [in upstream](https://github.com/Microsoft/TypeScript/issues/30819) is solved is a viable solution for now?

**Comment by mjbvz** [comment] 2019-05-14 01:14
Sounds like this could be https://github.com/microsoft/TypeScript/issues/31341

To check this, can you please try upgrading your workspace to use the next `typescript@next` that is published (3.5.0-dev.20190513+) by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

**Comment by swashata** [comment] 2019-05-20 14:09
I tried with `typescript@rc` and the performance improvement is significant and things are back to normal. So with the release of `typescript@3.5.0` it should be resolved.

Here are more details https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/

**Comment by mjbvz** [comment] 2019-05-21 17:55
@berkaey Can you please confirm by testing using the latest VS Code insiders build, which includes TS 3.5-rc

**Comment by natew** [comment] 2019-05-21 18:35
One weird thing I still see is the compiler is slow to output the success
message when you fix the last error. So if you have an error, and you fix
it, it sits at “compiling...” for 6 seconds or so. In reality, it actually
outputs the file before that, but it seems the message just gets held up
for a while.

**Comment by johnkahn** [comment] 2019-05-23 03:14
@mjbvz I was also experiencing slowness in `1.34.0` and I just tried `1.35-insider` with all 50ish extensions and it's much faster 🔥 Thanks!

**Comment by berkaey** [comment] 2019-05-23 09:05
@mjbvz let me check the 1.35-insider

**Comment by berkaey** [comment] 2019-05-23 09:16
After a quick test, I would say it is more responsive but still lags when I first open a file and cmd+click on an import, (I'm not sure but) when I open `insider` fans immediately kicks in for a period of time (this could be reason for first issue). After the fans got cooled, smooth as `1.32`. 👍

**Comment by mjbvz** [comment] 2019-05-23 17:52
Closing. A spike in cpu usage is expected on first open

**Closed by mjbvz** 2019-05-23 17:52 UTC
Labels: needs more info
