### ISSUE TITLE
json schema with $ref not working

### ISSUE THREAD

**Issue by mejuhi** [microsoft/vscode#130165] opened 2021-08-05 08:06 UTC
- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Json schema tried

```

{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "company_name#",
    "title": "title here",
    "description": "Desc ...",
    "type": "object",
    "required": [
        "Response"
    ],
    "properties": {
        "Response": {"$ref": "#ResponseMessageType"}
    },
    "definitions": {
        "ResponseMessageType": {
            "$id": "#ResponseMessageType",
            "additionalProperties": false,
            "type": "object",
            "properties": {
                "SuccessResponse": {"$ref": "#SuccessResponseType"}
            },
            "oneOf" : [{
            "required" : ["SuccessResponse"]
        }
    ]
        },
        "SuccessResponseType": {
            "$id": "#SuccessResponseType",
            "additionalProperties": false,
            "type": "object",
            "required": [
                "Code"
            ],
            "properties": {
                "Name": {
                    "$ref": "#NameType",
                    "description": "This attribute ..."
                },
                "Reference": {
                    "$ref": "#ReferenceType",
                    "description": "Unique ..."
                },
                "Code": {
                    "$ref": "#CodeType",
                    "description": "Code ..."
                }
            }
        },
        "NameType": {
            "$id": "#NameType",
            "type": "string",
            "minLength": 1,
            "maxLength": 100,
            "examples": ["Naame"]
        },
        "ReferenceType": {
            "$id": "#ReferenceType",
            "type": "string",
            "minLength": 1,
            "maxLength": 36,
            "examples": ["000"]
        },
        "CodeType": {
            "$id": "#CodeType",
            "type": "string",
            "minLength": 1,
            "maxLength": 4,
            "examples": ["0000"]
        }

    }
}
```

**Comment by mejuhi** [comment] 2021-08-10 08:28
@aeschli just checking if you have any updates/info for this issue I can look into?

**Comment by aeschli** [comment] 2021-08-18 12:00
We currently don't support references to $id

Duplicate of https://github.com/microsoft/vscode-json-languageservice/issues/55

**Closed by aeschli** 2021-08-18 12:00 UTC
