### ISSUE TITLE
Turkish [Iı] and [İi] characters search problem

### ISSUE THREAD

**Issue by iBener** [microsoft/vscode#155930] opened 2022-07-22 08:30 UTC
Issue Type: <b>Bug</b>

In English, upper [I] and lower [i] represent same character but in Turkish they are different. Actually there are plain "Iı" and also dotted "İi" chars in Turkish. For example "ASIL" and "asil" are different words and have different pronunciations and meanings. VS Code doesn't seem to be aware of this distinction when search without "Match Case".

Consider the following words:
(UPPERCASE, lowercase)
ISPARTA, ısparta
ISPANAK, ıspanak
İSPANYA, ispanya
İSPAT, ispat

[Match case off]
If I write "isp" in search box it should find:
    İSPANYA, ispanya
    İSPAT, ispat 
words and should mark "İSP" and "isp" parts. 
But VS Code cannot find "İSPANYA" and "İSPAT" and also finds "ISPARTA" and "ISPANAK", which it shouldn't find:
![image](https://user-images.githubusercontent.com/5037744/180402928-05a8e87b-8e7f-4517-8ba4-cea3ae361c4c.png)

If I write "ısp" in search box it should find only:
    ISPARTA, ısparta
    ISPANAK, ıspanak
words and should mark "ISP" and "ısp" parts.
But VS Code only find "ısparta" and "ıspanak" words and cannot find "ISPARTA" and "ISPANAK":
![image](https://user-images.githubusercontent.com/5037744/180403858-c9da6d29-62b9-43a3-b4d5-d7936b34d10a.png)

[Match case on]
Searching with match case works fine.

### EDIT
As a developer I think the current behavior is more acceptable than above suggestion. If it's to be fixed it should be like this; whichever of the [Iıİi] characters you type should find any of the [Iıİi]. Because no matter how Turkish you are, you often use English names when writing code. For example, you have a method and its name is "IsVerified". As a habit, you would type "isveri" in the search box, not "ısveri". So you won't find what you're looking for, and that would be frustrating. I think the best solution for us Turkish developers would be to find them all, no matter which [Iı] or [İi] you type.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.30GB free)|
|Process Argv|--crash-reporter-id 48dff169-f90b-4445-9cd0-3b3a807ba49e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
xml|Dot|2.5.1
gitpod-desktop|git|0.0.44
vscode-docker|ms-|1.22.1
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.2.2
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.1
sql-database-projects-vscode|ms-|0.17.2
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
powershell|ms-|2022.6.3
sqlite-viewer|qwt|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
841h4636:30532337

```

</details>

**Comment by IllusionMH** [comment] 2022-07-22 09:01
Effectively duplicate of #63643

**Comment by iBener** [comment] 2022-07-22 10:02
Actually, on rethinking (if it's changed) I have to point out that this fix would be very frustrating for Turkish developers. Because no matter how Turkish you are, you often use English names when writing code. For example, you have a method and its name is "IsVerified". As a habit, you will type "isveri" in the search box, not "ısveri". So you won't find what you're looking for, and that would be frustrating. I think the best solution for us Turkish developers would be to find them all, no matter which [Iı] or [İi] we type.

**Comment by TylerLeonhardt** [comment] 2022-07-24 18:12
I think the edit is sound. It would be non-trivial and in some folks opinion wrong to make such a change. I'm gonna close this as by design.

**Closed by TylerLeonhardt** 2022-07-24 18:12 UTC
