### ISSUE TITLE
Zen Mode permanently Hiding Activity bar and showing enabled(or Visible symbol)

### ISSUE THREAD

**Issue by SpeedyG3** [microsoft/vscode#148585] opened 2022-05-02 19:50 UTC
Issue Type: <b>Bug</b>

When I turn ON Zen mode and exit out of it, it permanently hides the Activity Bar. I checked whether Activity Bar was enabled or not, it show visible but does show the activity bar on the screen. Nothing works, have to close and open for it to work normally once again.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.11GB free)|
|Process Argv|--crash-reporter-id 4f454a71-d46f-44a8-b117-4e5dc3477dc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

<!-- generated by issue reporter --
![Screenshot (6)](https://user-images.githubusercontent.com/100776745/166315609-2438477a-9677-4c4e-a21d-885212472e13.png)
>

**Comment by JacksonKearl** [comment] 2022-05-03 16:34
Duplicate of #148022

**Closed by JacksonKearl** 2022-05-03 16:34 UTC
