### ISSUE TITLE
Symbols after collapsed markdown item

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162408] opened 2022-09-29 23:43 UTC
When I collapse title here, I get some strange symbols after it:

[![Image from Gyazo](https://i.gyazo.com/71f98308cb84af931a2c7b5f0487088a.gif)](https://gyazo.com/71f98308cb84af931a2c7b5f0487088a)

**Comment by mjbvz** [comment] 2022-09-30 02:46
@aeschli Assigning you since I think this is an issue with VS Code's folding implementation and not with the markdown folding provider

**Comment by aeschli** [comment] 2022-12-06 15:34
duplicate of https://github.com/microsoft/vscode/issues/145897

**Closed by aeschli** 2022-12-06 15:34 UTC
Labels: markdown
