### ISSUE TITLE
Editor.renameOnType: true

### ISSUE THREAD

**Issue by FatTonyy** [microsoft/vscode#96301] opened 2020-04-27 21:13 UTC
This works only on html but not on jsx, I dunno about vue though since I never used it.

- VSCode Version: 1.44
- OS Version: windows

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2020-04-28 00:11
/duplicate of https://github.com/microsoft/vscode/issues/94316

It's implemented only for HTML at this point.

JSX requires additional work as described in linked issue. Vue extension would need to implement support when API is finalized.

**Closed** 2020-04-28 00:12 UTC
Labels: *duplicate
