### ISSUE TITLE
更新完报错  “扩展宿主无法加载”

### ISSUE THREAD

**Issue by lxsunbin** [Microsoft/vscode#56307] opened 2018-08-14 07:06 UTC
Issue Type: <b>Bug</b>

怎么办？函数都不能跳转了

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|8.00GB (2.87GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_61455|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
golang-tdd|joa|0.0.9
vscode-language-pack-zh-hans|MS-|1.26.3
Go|ms-|0.6.86
vetur|oct|0.12.6
gitpatch|par|0.2.1
tsimporter|pmn|1.2.14
view-in-browser|qin|0.0.5
vscode-icons|rob|7.25.0
sass-indented|rob|1.4.9
background|sha|1.1.19
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by sandy081** [comment] 2018-08-14 08:08
Can you please provide summary and description in English.

**Comment by yume-chan** [comment] 2018-08-14 09:49
> # Can not load Extension Host after updating
> So can't jump to function definitions.

I suspect a native addon cannot be loaded after Electron upgrading.

**Comment by sandy081** [comment] 2018-08-15 14:41
Duplicate of #56301

**Closed** 2018-08-15 14:41 UTC
Labels: *duplicate, needs more info, new release
