### ISSUE TITLE
Custom HTML tag tooltips in project settings

### ISSUE THREAD

**Issue by samterainsights** [Microsoft/vscode#61069] opened 2018-10-16 17:58 UTC
VS Code currently shows nice little descriptions of standard HTML tags when you hover over them, in tooltips. What would be a killer feature for any web-app project would be the ability to add custom tooltips for custom HTML tags.

The frontend I work on is AngularJS and will be moved to Angular in the future (but this also applies to any other web component framework), and given the sheer number of components we have, it is easy to forget the exact bindings and usage rules for a particular one.

Being able to **register tag tooltips in a project settings file for each of our components** and then just hover over a `<my-component ...>` tag to see usage instructions would save a lot of time versus going to the component class, even though our component classes follow a strict naming scheme: `<HTML tag name>.comp.ts`. And for people who have to take care of unorganized projects, it would be even better.

I do not know how difficult this would be to implement, but even text-only tooltips for the tags would be totally workable. VS Code is fantastic as-is, and I feel this would make it even better. Thanks for considering my issue and have a great day.

**Comment by aeschli** [comment] 2018-10-17 07:18
Extensions can already do that. It basically means adding another hover provider for the `html` language mode. The only problem is that this needs to be done in code and that that code will have to parse the HTML again. But we have the HTML parser available in the `vscode-html-languageservice` node module.

The alternative is would be a extension point to the html language service so that the html parser can be reused: That's https://github.com/Microsoft/vscode/issues/2784.

Marking as duplicate of https://github.com/Microsoft/vscode/issues/2784

**Closed by aeschli** 2018-10-17 07:18 UTC
Labels: html
