### ISSUE TITLE
extension changelog page overlap

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#108908] opened 2020-10-19 02:01 UTC
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

![Snipaste_2020-10-19_09-53-37](https://user-images.githubusercontent.com/41773861/96393539-00e99d00-11f2-11eb-89bd-7f472d91e6d8.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by mjbvz** [comment] 2020-10-19 20:35
Duplicate of #107104

**Closed by mjbvz** 2020-10-19 20:35 UTC
