### ISSUE TITLE
JSDoc Intellisense not working as shown in release notes (10.10)

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [Microsoft/vscode#3842] opened 2016-03-08 13:03 UTC
My intellisense is not showing the same behavior as what's shown in the v10.10 release notes. 
Note here how the `@constructor` directive is visible at the end of the description, suggesting that perhaps it wasn't parsed.
![image](https://cloud.githubusercontent.com/assets/2729807/13602144/e08dde2a-e502-11e5-8c73-2380e406cf61.png)

The `name` parameter does not show the description, but the type is displayed correctly.
![image](https://cloud.githubusercontent.com/assets/2729807/13602227/59cb9a3e-e503-11e5-9e5b-36fa14196c00.png)

There is no intellisense for the greet function
![image](https://cloud.githubusercontent.com/assets/2729807/13602191/24c6dcfe-e503-11e5-9d43-a1bdeab1a6a2.png)

Do I need to do something to explicitly enable the functionality showcased in the release notes? I tried executing "Reload Javascript Project" both with and without a jsconfig.json file present already.

**Comment by LittleBrainz** [comment] 2016-03-09 18:06
I have come across a similar issue.

Intellisense will work as described (in the release notes) with a function declaration:

```js
/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
function upper1(value) {
	return value.toUpperCase();
}
```

But will be limited (see previous comment be @egamma) with a function expression:

```js
/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
var upper2 = function(value) {
	return value.toUpperCase();
};
```

Similarly, my preferred ES2015 style behaves the same:

```js
/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
const upper3 = (value) => {
	return value.toUpperCase();
};
```

Also, it looks to me that `@returns` is not being parsed, or perhaps it's just being poorly presented.

**Comment by egamma** [comment] 2016-03-16 14:24
@AdamAndersonFalafelSoftware 

My setup is a folder with a single .js file, no jsconfig.json

>The name parameter does not show the description, but the type is displayed correctly.

works for me:

![image](https://cloud.githubusercontent.com/assets/172399/13815130/a5d4f1aa-eb89-11e5-8f69-1ca294cb4f34.png)

>There is no intellisense for the greet function

works for me:

![image](https://cloud.githubusercontent.com/assets/172399/13815187/de1a7a76-eb89-11e5-8486-96a17889a7c4.png)

This is the full source

```js
/**
 * Represents a person
 * @constructor
 * @param {string} name The name of the person
 */
function Person(name) {
    this.name = name;
}

/**
 * Greets the person
 * @param {string} greeting The greeting
 */
Person.prototype.greet = function greet(greeting) {
    return greeting + ' ' + this.name;
}

var p = new Person('joe');
```

**Comment by egamma** [comment] 2016-03-16 14:28
@LittleBrainz 

I've tried the following source

```js
/**
 * To upper case
 * @param {string} value The string to be transformed
 */
function upper(value) {
    return value
}

/**
 * To upper case
 * @param {string} value The string to be transformed
 */
var upper2 = function(value) {
    return value
}

/**
 * To upper case
 * @param {string} value The string to be transformed
 */
var upper3 = (value) => {
    return value
}
```

And I get proper IntelliSense, parameter hints, hovering. What am I missing?

**Comment by AdamAndersonFalafelSoftware** [comment] 2016-03-16 14:35
@egamma I can effortlessly reproduce my results in a single .js file all alone in a folder with no jsconfig.json. Is there anything I can do to help you reproduce my results? Are there any configuration options I need to check in my environment? Perhaps this is an artifact of upgrading from an earlier version of VSCode. Is it possible that somehow I'm not even using Salsa even though it's supposed to be the default now?

**Comment by AdamAndersonFalafelSoftware** [comment] 2016-03-16 14:48
@egamma Perhaps this has something to do with it? I just noticed all these errors after opening my user settings. Pretty sure they didn't appear before then.

![image](https://cloud.githubusercontent.com/assets/2729807/13816381/886417b0-eb64-11e5-86bd-794c4fa352de.png)

**Comment by egamma** [comment] 2016-03-16 14:52
@AdamAndersonFalafelSoftware The screenshot from you above shows that you are using Salsa. Did you anything with the `typescript.tsdk` setting? It could be that the tsdk points to an older version of Salsa/TypeScript.

I've also tested on 0.10.11 and I cannot reproduce it.

The screenshot above looks like a duplicate of #3766 and I don't think it is related.

**Comment by AdamAndersonFalafelSoftware** [comment] 2016-03-16 15:07
@egamma I wonder if my TypeScript config is correct. Here are my default settings. Is the tsdk supposed to be null?

![image](https://cloud.githubusercontent.com/assets/2729807/13816610/6c5e2a28-eb65-11e5-9051-07f2e80fd6ef.png)

I just re-tested a few things and got some of the results you did, but not all.

Intellisense for Person appends the @constructor directive to the description:
![image](https://cloud.githubusercontent.com/assets/2729807/13817016/eaf3a81c-eb66-11e5-860f-e34e903ebed7.png)

I *do* see intellisense for the name parameter of the constructor:
![image](https://cloud.githubusercontent.com/assets/2729807/13817032/015b0262-eb67-11e5-8ffb-2e434aa564c0.png)

I *do* see the description for Person.prototype.greet:
![image](https://cloud.githubusercontent.com/assets/2729807/13817053/19e2561e-eb67-11e5-82d0-28bf388c5fbe.png)

,,.but I do **not** see intellisense for the greeting parameter of Person.prototype.greet:
![image](https://cloud.githubusercontent.com/assets/2729807/13817075/31164390-eb67-11e5-88e5-5404e9ead1c3.png)

**Comment by LittleBrainz** [comment] 2016-03-16 18:51
@egamma 

```js
/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
function upper1(value) {
    return value.toUpperCase();
}


/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
var upper2 = function(value) {
    return value.toUpperCase();
};


/**
 * Transform a string to upper-case.
 * @param {string} value The string to be transformed.
 * @returns {string} The upper-cased string.
 */
const upper3 = (value) => {
    return value.toUpperCase();
};


var v1 = upper1('hey');

var v2 = upper2('ho');

var v3 = upper3('lets go');
```

Intellisense with a function declaration (upper1)...
![fd completion](https://cloud.githubusercontent.com/assets/5047398/13824703/193ed274-eba7-11e5-9280-4025f6200803.PNG)
And hover...
![fd hover](https://cloud.githubusercontent.com/assets/5047398/13824714/21e2a75c-eba7-11e5-9057-7bcaa24a2b15.PNG)

Intellisense with a function expression (upper2 & upper3)...
![fe completion](https://cloud.githubusercontent.com/assets/5047398/13824735/32638c18-eba7-11e5-8c56-7d4a6e50f6d1.PNG)
And hover...
![fe hover](https://cloud.githubusercontent.com/assets/5047398/13824737/35c07cae-eba7-11e5-82b8-d6cc972c5623.PNG)

This is VS Code 0.10.11 with a jsconfig.json.

**Comment by egamma** [comment] 2016-03-18 08:52
@AdamAndersonFalafelSoftware 

>I wonder if my TypeScript config is correct. Here are my default settings. Is the tsdk supposed to be null?

This is the default value that gets inserted, it is treated as the setting is not defined. So I would just delete it.

We have updated to a new version of salsa/typescript 1.8.9 which has additional fixes.  We will make this available on the insider channel next Monday.

I suggest to retest there again.

**Comment by egamma** [comment] 2016-03-18 08:54
@LittleBrainz same here I suggest to retest on the latest with TypeScript 1.8.9.

**Comment by AdamAndersonFalafelSoftware** [comment] 2016-03-18 11:29
@egamma I am not on the insider channel. How do I join?

**Comment by LittleBrainz** [comment] 2016-03-18 16:41
@egamma - TypeScript 1.8.9 is giving the same results as 1.8.2.
![typescript version](https://cloud.githubusercontent.com/assets/5047398/13884975/3c90480c-ed28-11e5-9490-84a567fab506.PNG)

**Comment by egamma** [comment] 2016-03-18 16:48
@AdamAndersonFalafelSoftware here is how to get the insiders build https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build, but this one doesn't have 1.8.9 yet. To try out 1.8.9 you have to do the same as @LittleBrainz and use the tsdk option to use 1.8.9.

@LittleBrainz in this case I don't see how VS Code could be the culprit. Can you extract the good steps from https://github.com/Microsoft/vscode/issues/3842#issuecomment-197484962 and file an issue against TypeScript.

**Comment by LittleBrainz** [comment] 2016-03-18 16:56
@AdamAndersonFalafelSoftware - TypeScript 1.8.9 is the current default on NPM.

- Install TypeScript 1.8.9 globally with:
```sh
npm install --global typescript
```

- On the File menu / Preferences / User Settings, edit the `settings.json` file to set `typescript.tsdk` to the folder path containing the tsserver and lib*.d.ts files to use. On my system I have:
```json
"typescript.tsdk": "C:/Users/Stephen/AppData/Roaming/npm/node_modules/typescript/lib"
```

That should do it. But, be warned, the next version of VS Code may have a more up-to-date TypeScript, so you will have to comment out the line in User Settings when you upgrade next.

**Comment by egamma** [comment] 2016-04-17 16:55
Closing this issue since it is now tracked in the TypeScript repository.

**Closed by egamma** 2016-04-17 16:55 UTC
