### ISSUE TITLE
Support ligatures in inputs (Debug input, Breakpoint input, etc)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#26640] opened 2017-05-15 07:18 UTC
- VSCode Version: Code - Insiders 1.13.0-insider **[Unsupported]** (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.16193
---

Currently font ligatures seem to only work in a document editor or the terminal (if enabled).

**Comment by isidorn** [comment] 2017-05-15 08:47
This is basically a duplicate of the https://github.com/Microsoft/vscode/issues/11462
I have updated that issue to also contain this feature request

**Closed by isidorn** 2017-05-15 08:47 UTC
