### ISSUE TITLE
Formatting issue when adding a debug configuration

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#44096] opened 2018-02-21 09:16 UTC
pls see https://youtu.be/2oFKNL7vYV8?t=184

The identation of the text is not correct

![image](https://user-images.githubusercontent.com/172399/36471713-c6325dfa-16ef-11e8-92a3-56d732d117c4.png)

**Comment by isidorn** [comment] 2018-02-21 09:26
This is as expected since @auchenberg had a badly formated file before the action.
Notice that he is adding the "Attach by Process ID" configuration which is nicely indented. The issue is that he already has a badly idented "Launch Program".
When a suggestion is accepted it is idented based on the previous line and that is done correctly in this case.
Closing as designed

**Comment by auchenberg** [comment] 2018-02-21 15:37
@isidorn Isn't it the other way around? The `launch.json` is created with the last configuration that is nicely indented, which the "attach by process id" is inserted into? With a bad indent?

**Comment by isidorn** [comment] 2018-02-21 16:12
@auchenberg you are correct, my mistake.
I can not reproduce though following your steps, that is why I though the issue was the original launch.json.

@auchenberg Do you see this issue all the time in the vscode insiders? If yes, are you doing something differnetly than me?
Thanks

![kenneth](https://user-images.githubusercontent.com/1926584/36491154-64d5f4fa-172a-11e8-93a4-e5b6149dc4f1.gif)

**Comment by auchenberg** [comment] 2018-02-21 16:59
Yeah, I can't reproduce it in Insiders either. I think Rob fixed an issue related to this earlier. Let's close for now. I'll re-open if I see it again.

**Closed by auchenberg** 2018-02-21 16:59 UTC
Labels: needs more info
