### ISSUE TITLE
Set breakpoint by selection

### ISSUE THREAD

**Issue by jgcook935** [microsoft/vscode#77946] opened 2019-07-25 17:40 UTC
I'd like the ability to set break points by a selection of text. Quite often I'll add breakpoints to a block of code one by one by clicking the sidebar or using f9 and it can be a bit cumbersome. It'd be great if there was a shortcut to set breakpoints on all lines of code highlighted in the editor.

**Comment by isidorn** [comment] 2019-07-30 09:41
Would it work for you if Toggle Breakpoint action would respect multiple cursors.
That way you could have 10 cursors set wherever you want and doing Toggle Breakpoint would set 10 breakpoints?
That's the only way this could nicely work imho

**Comment by isidorn** [comment] 2019-07-30 12:19
Aactually duplicate of https://github.com/microsoft/vscode/issues/77879

**Closed by isidorn** 2019-07-30 12:19 UTC
Labels: debug, feature-request

**Comment by jgcook935** [comment] 2019-07-30 15:03
This sounds good to me. I'll follow #77879 instead.
