### ISSUE TITLE
Minimap(enhanced scrollbar) became a black

### ISSUE THREAD

**Issue by jeffguorg** [Microsoft/vscode#38030] opened 2017-11-10 06:31 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)(from ppa: ```deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main```)

- OS Version: Ubuntu 16.04.03 x64 (Linux x64 4.4.0-98-generic)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.21
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-auto-open-markdown-preview|hnw|0.0.4
Go|luk|0.6.67
VS-code-vagrantfile|mar|0.0.7
hg|mrc|1.2.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
team|ms-|1.122.0
vetur|oct|0.11.0
vscode-code-outline|pat|0.0.12
Ruby|reb|0.15.0
java|red|0.14.0
bash-debug|rog|0.1.0
bash-beautify|sha|0.1.1
vim|vsc|0.10.2
jinja|who|0.0.8
markdown-all-in-one|yzh|0.11.1

---

Steps to Reproduce:

1. open vscode

2. suspend your laptop

3. boom! minimap becomes blank like this

4. resizing the window will make it normal again

![2017-11-10 14-18-04](https://user-images.githubusercontent.com/7763702/32645418-1af6441a-c622-11e7-95e7-0f1e697ae17e.png)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-11-13 11:57
Duplicate of #30292

**Closed by alexandrudima** 2017-11-13 11:57 UTC
Labels: editor, new release
