### ISSUE TITLE
Merge editor and base

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160247] opened 2022-09-07 05:22 UTC
I cannot understand this merge conflict without spending a lot of time comparing the sides:
* `git co main`
* `git revert dffbdebac52a09539eb720d059d5a21f86fb7524`

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/900690/188794552-b0ca209e-a7c3-40e1-8cd4-d2c975fe26ca.png">

**Observations:**
* I can show a "base" editor but it does not reveal the area of the conflict when you make "base" visible
* I would have expected to see some red/green decorations for changes added or removed similar to diff, now I have to compare base with left and right side to find the changes, can we not visualise this better?

//cc @daviddossett

**Comment by hediet** [comment] 2022-09-07 09:15
Can you share with the merge dev command copy state to JSON?

**Comment by bpasero** [comment] 2022-09-07 09:17
[json.zip](https://github.com/microsoft/vscode/files/9504648/json.zip)

**Comment by hediet** [comment] 2022-09-07 09:39
I also notice that there are no decorations, which was caused by the bug I discussed in yesterdays standup.

This is how it should look like:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/2931520/188845558-8e11dc37-fa00-475a-9cb2-76b134941422.png">

I created
* #160276
to track the highlighting issue of the deletion view-zone.

What else do you find confusing?

**Comment by bpasero** [comment] 2022-09-07 09:43
Ok I am happy to re-test after the fix. I still think "base" should automatically reveal the conflict I am at, as soon as I make it visible.

To clarify what I meant with understanding the merge conflict: once base is visible, can we not show a diff like as if I would compare one side to base? Maybe take the active focussed side and update diff markers?

here is what I see today in diff:

![image](https://user-images.githubusercontent.com/900690/188847167-6fc831d8-2d33-46bb-82ba-4656c378b9cf.png)

**Comment by hediet** [comment] 2022-09-07 12:44
>  I still think "base" should automatically reveal the conflict I am at, as soon as I make it visible.

That should be the case with today's insider, no?

> Maybe take the active focussed side and update diff markers?

I like that idea!

**Comment by hediet** [comment] 2022-09-07 14:08
@jrieken maybe when "Show Base" and "mixed" is enabled, we can show an option "Show Base At Top"?

<img width="167" alt="image" src="https://user-images.githubusercontent.com/2931520/188899299-364a416a-959b-4f2c-871f-328a35fce83a.png">

**Comment by hediet** [comment] 2022-09-07 14:11
Can we close this in favor of the new issues?

**Closed** 2022-09-07 14:19 UTC
Labels: info-needed, merge-editor
