### ISSUE TITLE
[TypeScript] Snippets in String Literals

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/vscode#19879] opened 2017-02-03 21:54 UTC
- VSCode Version: 1.9.0, commit 27240e71
- OS Version: Win10

Snippet completions occur in string literals, where it doesn't make sense to apply them.

![import_snippet](https://cloud.githubusercontent.com/assets/3226984/22609973/2719a502-ea18-11e6-8293-0fdf4e68f64c.png)

Steps to Reproduce:

1. Create a ts file with the following contents:
``` ts
import x =  require('cl')
```
2. Place the caret after the `l`
3. Trigger completions (Ctrl+Space)
4. Observe that the `class` snippet is a completion option.

## Expected

No snippet completions occur in string literals

## Observed

They do.

**Comment by mjbvz** [comment] 2017-02-03 22:12
Closing as duplicate of #1304

**Closed by mjbvz** 2017-02-03 22:12 UTC
Labels: duplicate, javascript, snippets, typescript
