### ISSUE TITLE
High CPU usage in mac

### ISSUE THREAD

**Issue by FourEyebrowXiake** [Microsoft/vscode#58671] opened 2018-09-14 07:42 UTC
Issue Type: <b>Performance Issue</b>

when I opened vscode, the vscode will use a lot of CPU after a while
![image](https://user-images.githubusercontent.com/18180417/45536818-2054b580-b835-11e8-8f79-c37e84d2f1ce.png)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	    90	 87444	code main
    0	    66	 87468	   gpu-process
    0	   115	 87469	   window (newintentpage.js — frontend)
    0	     0	 87473	     /bin/zsh -l
    0	    33	 87482	     extensionHost
    0	    57	 87562	       electron_node tsserver.js 
    0	    25	 87581	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    25	 87563	       electron_node eslintServer.js 
    0	    25	 87564	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=87482
    0	    25	 87484	     watcherService
    0	    25	 87571	     searchService
    0	    49	 87491	   shared-process
    0	    82	 88265	   window (Issue Reporter)
    0	     0	 88269	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (newintentpage.js — frontend)
|    Folder (frontend): 151 files
|      File types: js(74) scss(42) png(9) map(8) json(5) gif(5) css(2) html(2)
|                  eslintignore(1) ejs(1)
|      Conf files: jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.0
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.27.2
python|ms-|2018.8.0
vscode-docker|Pet|0.2.0
markdown-preview-enhanced|shd|0.3.5
ReactSnippets|xab|2.2.0

</details>

**Comment by joaomoreno** [comment] 2018-09-17 06:52
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by ghost-of-turek** [comment] 2018-09-18 13:49
I can confirm this issue also occurs on Arch Linux @ Dell XPS 13 since the upgrade to `1.27`. The issue is intermittent and usually lasts only a few seconds. I will try to run the test suite mentioned above soon and report back the results.

**Comment by jacobweber** [comment] 2018-09-24 21:56
I've seen a bunch of similar issues reported and closed because they couldn't be reproduced. I hope the VSCode team is still looking into it, since it seems like a widespread issue. In my case, I've been seeing it since 1.24.x, but I haven't been able to consistently reproduce it, so it's hard to get most of the items on the checklist above.

**Comment by joaomoreno** [comment] 2018-09-25 09:04
@ghost-of-turek @jacobweber Do not jump on other people's issues. Instead, please file a separate issue with as much information as you can.

@FourEyebrowXiake Waiting for your reply.

**Comment by serkanyersen** [comment] 2018-09-25 21:43
I have the same issue. Just tested your list and it doesn't happen when extensions are disabled.

With extensions enabled, this is what I see (idle)

<img width="1237" alt="screen shot 2018-09-25 at 14 41 01" src="https://user-images.githubusercontent.com/30582/46044989-341fd780-c0d1-11e8-932a-9fac8f60e033.png">


After a few hours of usage, it goes crazy, spins up all fans and CPU usage shows 600%. I wasn't able to check Process explorer when that happens

**Comment by serkanyersen** [comment] 2018-09-25 21:55
@FourEyebrowXiake do you have `code-spell-checker` installed? I think that might be the issue with big files.

It could also be the "Settings Sync" plugin with the combination of `Auto upload when saved` feature and the new Settings GUI.

When I make changes to settings all CPUs fire up.
<img width="1280" alt="screen shot 2018-09-25 at 14 51 38" src="https://user-images.githubusercontent.com/30582/46045518-cbd1f580-c0d2-11e8-94a1-f894eff3a748.png">

@joaomoreno None of these were an issue before the last update though. Is there anyway I can gather more information for you?

**Comment by serkanyersen** [comment] 2018-09-25 21:58
Sorry forgot to mention, when I kill vscode, `Code Helper` process sticks around. it doesn't die. lingers there with 100% usage.

**Comment by joaomoreno** [comment] 2018-09-26 07:09
@serkanyersen Do not jump on other people's issues. Instead, please file a separate issue with as much information as you can.

@FourEyebrowXiake Waiting for your reply.

**Comment by serkanyersen** [comment] 2018-09-26 07:33
@joaomoreno can you clarify, do you want duplicate issues?

**Comment by joaomoreno** [comment] 2018-09-26 09:03
@serkanyersen It is not clear that your issue is a duplicate of @FourEyebrowXiake's. When you come into his issue and start providing more details about yours, it makes the discussion about his issue much harder. Create a new issue; if they are indeed duplicates, we'll figure it out eventually and join forces.

**Closed** 2018-10-03 09:12 UTC
Labels: needs more info
