### ISSUE TITLE
Writing login information to the keychain failed with error 'Error during CryptAcquireContext.'.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#108362] opened 2020-10-09 07:15 UTC
I see this everytime I open Insider

<img width="358" alt="capture" src="https://user-images.githubusercontent.com/1931590/95554094-e2282100-0a0f-11eb-9fbc-cefb20c378a6.png">

**Comment by ThiefMaster** [comment] 2020-10-09 09:20
I get this after updating to the latest insiders version:

> Writing login information to the keychain failed with error 'The stub received bad data.'

**Comment by fdncred** [comment] 2020-10-09 14:16
Same here with this version
```
Version: 1.51.0-insider (user setup)
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:54.647Z (8 hrs ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by plwalsh** [comment] 2020-10-09 16:31
Same message as @ThiefMaster after updating to the same version as @fdncred.

**Comment by Chuxel** [comment] 2020-10-09 21:24
Yeah this is also happening for the Codespaces extension in insiders.  On macOS, you don't see this error, but VS Code gets "amnesia" and forgets its signed in so the remote explorer keeps showing "Sign in..." on first start.

**Comment by RMacfarlane** [comment] 2020-10-09 23:47
They are likely both related to the same set of changes to add an additional layer of encryption on top of the OS credential store, but I think the root cause is different between them, so I will keep that one open separately

**Comment by cmendible** [comment] 2020-10-10 08:02
Same here. Can't logging to Sync settings and Codepsaces

**Comment by joamag** [comment] 2020-10-11 21:18
I'm also getting this error when using the latest insiders version and trying to sync settings.

**Comment by TechStacker** [comment] 2020-10-12 08:20
Same problem here, after updating to Mojave 10.14.6 :(

**Comment by joaomoreno** [comment] 2020-10-12 09:11
This breaks both Settings Sync and Git authentication for me (pull, push).

**Comment by RMacfarlane** [comment] 2020-10-12 23:36
I've checked in a fix for the "stub received bad data" error, this is tracked in #108411

I made some slight changes that might fix this in c0d465ce1c2c1992b30bb4219ed17d88529c87f2 or give a better error message. If you are seeing the "Error during CryptAcquireContext" issue, can you try out tomorrow's insiders and see if this has any impact?

**Comment by joaomoreno** [comment] 2020-10-13 07:41
Fixed for me today, thanks!

**Comment by baboon-king** [comment] 2020-10-13 08:00
> Fixed for me today, thanks!

I also encountered this problem, can you give me your method, thank you

**Comment by cmendible** [comment] 2020-10-14 06:40
Fixed after updating today!

Version: 1.51.0-insider (user setup)
Commit: bc20f53838c75c0ec473b2a1afa7423cc5bcf7ab
Date: 2020-10-13T17:29:58.109Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by baboon-king** [comment] 2020-10-14 07:02
The problem was fixed after the update

Version: 1.51.0-insider (system setup)
Commit: bc20f53838c75c0ec473b2a1afa7423cc5bcf7ab
Date: 2020-10-13T17:29:58.109Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by RMacfarlane** [comment] 2020-10-14 18:05
Thanks for the confirmation!

**Closed by RMacfarlane** 2020-10-14 18:05 UTC
Labels: authentication, bug, important

**Comment by dbaeumer** [comment] 2020-10-29 13:25
I haven't noticed it either. Marking as verified.
