### ISSUE TITLE
When webview get focus, can't open color theme interface

### ISSUE THREAD

**Issue by forwardhuan** [microsoft/vscode#85170] opened 2019-11-20 03:34 UTC
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362 

Steps to Reproduce:

1. Use a  webview page and click it.
2. Open Setting  --> Color Theme, can't show select color theme interface

**Comment by forwardhuan** [comment] 2019-11-20 03:39
I made an attempt.  When the mouse removed the WebView, I called “reveal(undefine, true)”, and I  want to make the WebView lose focus, but it didn't work

**Comment by gjsjohnmurray** [comment] 2019-12-13 04:50
Probably a duplicate of #75209

**Comment by mjbvz** [comment] 2020-04-15 22:36
Duplicate of #75209

**Closed by mjbvz** 2020-04-15 22:36 UTC
