### ISSUE TITLE
Repeated Reload Window commands results in blank window

### ISSUE THREAD

**Issue by bobrocke** [Microsoft/vscode#24724] opened 2017-04-13 22:53 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-solarized|Braver|0.0.3|
|EditorConfig|EditorConfig|0.9.3|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|sort-lines|Tyriar|1.2.0|
|html-snippets|abusaidm|0.1.0|
|vscode-twig-pack|bajdzis|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.5|
|file-icons|file-icons|1.0.3|
|phpcs|ikappas|0.7.0|
|HTMLHint|mkaufman|0.3.3|
|color-highlight|naumovs|2.0.1|
|vscode-solar|RJR|0.0.3|
|scope-info|siegebell|0.2.0|
|code-spell-checker|streetsidesoftware|1.0.2|
|twig|whatwedo|1.0.2|;

---

Steps to Reproduce:

1. Reload the window a couple of times

After a few times, the window reloads but remains blank. Quitting and restarting fixes it.

**Comment by bpasero** [comment] 2017-04-17 16:41
@bobrocke I cannot reproduce by pressing Cmd+R in the window a couple of times. When this happens next, can you see if there is something printed to the developer console?

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bobrocke** [comment] 2017-04-17 17:26
OK, I got the blank screen again after a few reloads while editing the active theme .tmtheme file. Here are the diagnostics:

```
→ code --verbose
[main 1:24:14 PM] Starting VS Code in verbose mode
[main 1:24:14 PM] from: /Applications/Development/Visual Studio Code.app/Contents/Resources/app
[main 1:24:14 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 1:24:15 PM] IPC#vscode-machineId
[7481:0417/132415:INFO:CONSOLE(28)] "Overwriting extension <<.html>> to now point to mime <<text/x-html>>", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132415:INFO:CONSOLE(28)] "Overwriting extension <<.twig>> to now point to mime <<text/x-twig>>", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132415:INFO:CONSOLE(28)] "Conflict detected, command `editor.debug.action.toggleBreakpoint` cannot be triggered due to sortLines.sortLines", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[main 1:24:16 PM] IPC#vscode-workbenchLoaded
[7481:0417/132416:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[7481:0417/132416:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[7481:0417/132416:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[7481:0417/132416:INFO:CONSOLE(28)] "Activating extension `bajdzis.vscode-twig-pack` failed: ENOENT: no such file or directory, open '/Users/bob/.vscode/extensions/bajdzis.vscode-twig-pack-1.0.0\snippets\filters.json'.", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132416:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132417:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[7481:0417/132417:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Development/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
```

![console](https://cloud.githubusercontent.com/assets/2962426/25097180/6eff8de0-2371-11e7-8ae9-4361df3b8049.jpeg)

**Comment by bpasero** [comment] 2017-05-14 08:06
@bobrocke does this reproduce with our 1.12 release?

**Comment by bobrocke** [comment] 2017-05-14 12:49
Hmm. I can't find the Reload Window menu item and ⌘-R (for Mac) does nothing!

Using Reload Window from the command palette does reload the window, but no longer reopens files.

It's all seeming very odd. Where have I gone so far wrong?

**Comment by bpasero** [comment] 2017-05-14 13:06
It looks like this particular issue was fixed in Electron then. Please file a new issue with steps how you loose opened files after a window reload (but keep in mind that for windows that have no folder opened we never restore the opened files).

**Closed by bpasero** 2017-05-14 13:06 UTC
Labels: needs more info, upstream
