### ISSUE TITLE
Bug in Minimap after pc suspend

### ISSUE THREAD

**Issue by HakimMliki** [Microsoft/vscode#49439] opened 2018-05-08 07:57 UTC
Issue Type: <b>Bug</b>

after i suspend my pc (linux mint) with vscode open i get this in the minimap 

![selection_002](https://user-images.githubusercontent.com/16654549/39745203-7e520720-529e-11e8-9592-a6806eb9e844.png)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2319)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.51GB (4.03GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26

</details>

**Comment by alexandrudima** [comment] 2018-05-09 07:41
Duplicate of #30292

**Closed by alexandrudima** 2018-05-09 07:41 UTC
Labels: linux
