### ISSUE TITLE
Code Helper high CPU usage on MacBook Pro 13

### ISSUE THREAD

**Issue by LingYanSi** [Microsoft/vscode#28687] opened 2017-06-14 05:29 UTC
- VSCode Version: 1.13.0 (1.13.0) 376c52b955428d205459bea6619fc161fc8faacf 2017-06-08T16:31:58.321Z
- OS Version:  macOS Sierra 10.12.5

![image](https://user-images.githubusercontent.com/8621814/27115377-c4da279e-50fc-11e7-957d-f07b539a014a.png)

I have disable all extensions
![image](https://user-images.githubusercontent.com/8621814/27115374-beb61e04-50fc-11e7-94a0-96f267a88fa2.png)
￼
```bash
$ ps aux | grep 57102
wangyong         57102 100.0  1.3  3251200 105020   ??  R    12:06下午   9:04.40 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/wangyong/Library/Caches/typescript --enableTelemetry
wangyong         57858   0.0  0.0  2442020    796 s003  S+   12:15下午   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 57102
```

my jsconfig:
```json
{
    "compilerOptions": {
        "jsx": "react",
        "target": "es6",
        "module": "commonjs",
        "baseUrl": "./react/",
        "experimentalDecorators": true
    },  
    "exclude": [
        "node_modules",
        "static",
        "static1"
    ]
}
```

When I set  ``` ”typescript.disableAutomaticTypeAcquisition": true ```，cpu is ok , but the node intellisense is not working.

**Comment by mjbvz** [comment] 2017-06-14 18:13
This seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/15301 . It looks like under some circumstances that the Typing installer can go into a loop. It is not clear what the cause of this issue is but we plan on adding additional logging to hopefully track down what may be going wrong: https://github.com/Microsoft/TypeScript/issues/16203

Closing as upstream

**Closed by mjbvz** 2017-06-14 18:13 UTC
Labels: typescript, upstream

**Comment by zaatas** [comment] 2017-06-29 05:48
Arg... I'm having the exact same problem !!!
