### ISSUE TITLE
Invalid tabbing!

### ISSUE THREAD

**Issue by VitalySenko** [Microsoft/vscode#15463] opened 2016-11-14 13:52 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typings-installer|benjaminromano|0.2.0|
|npm-intellisense|christian-kohler|0.1.4|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.1.0|
|vscode-npm|fknop|3.3.0|
|path-autocomplete|ionutvmi|1.1.0|
|typings-autoinstaller|jvitor83|1.2.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|vscode-icons|robertohuertasm|4.0.1|

---

Steps to Reproduce:

1. My user settings:
```
{
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.renderWhitespace": true,
  "editor.formatOnType": true,
  "extensions.autoUpdate": true,
  "window.reopenFolders": "none",
  "html.format.extraLiners": "",
  "html.format.indentInnerHtml": true,
  "html.format.unformatted": "",
  "editor.formatOnSave": true
}
```
2. Sometimes VS Code misthinking and make all tabs in file = 4 (edit on save).

**Comment by jedfonner** [comment] 2016-11-15 03:19
I get this constantly.  Despite having specified in my user settings that I only want 2 spaces for tab, Visual Studio Code constantly reformats my js files to have 4 spaces when I save.

**Comment by dylanparry** [comment] 2016-11-15 17:09
Appears to be a duplicate of #15316

**Comment by ramya-rao-a** [comment] 2016-11-15 22:46
Closing as duplicate of #15316

**Closed by ramya-rao-a** 2016-11-15 22:46 UTC
