### ISSUE TITLE
Add option to hide the new "details feature" in npm script explorer

### ISSUE THREAD

**Issue by stijn7621** [microsoft/vscode#139095] opened 2021-12-14 14:35 UTC
Add option to hide details in npm script explorer. I don't care about the details directly. It already pops up when I hover over it.

**Comment by gjsjohnmurray** [comment] 2021-12-14 14:39
/duplicate of #138694 which needs 16 more upvotes on the issue description in order to progress beyond Backlog Candidate.

**Closed** 2021-12-14 14:39 UTC
Labels: *duplicate
