### ISSUE TITLE
Vscode grays out completely, becomes unusable

### ISSUE THREAD

**Issue by MJimitater** [microsoft/vscode#123671] opened 2021-05-12 12:00 UTC
- VS Code Version: 1.56.1 (user setup); commit: e713fe9b05fc24facbec8f34fb1017133858842b
- OS Version: Windows 10, 10.0.18363 Build 18363

Steps to Reproduce:

1. Run jupyter notebook program for long time
2. All of a sudden vscode screen turns gray. Program seems to still be running in the background, at least fans are still working. However there is no other way to operate than to restart vscode.

Perhaps related to #120725 or #105996 in some way?!

Does this issue occur when all extensions are disabled?:  Not certain, haven't tested yet. Jupyter, Python and Pylance Extension are used.
![Vscode_grey_blank](https://user-images.githubusercontent.com/26901261/117971388-23780a80-b32a-11eb-8942-0f232a58ff54.PNG)

**Comment by deepak1556** [comment] 2021-05-19 10:17
Root issue is very likely duplicate of https://github.com/microsoft/vscode/issues/123257

Can you check if the issue happens in insiders https://code.visualstudio.com/insiders/ ? Also you can confirm if the issue happens in stable by launching with `code --disable-features=CalculateNativeWinOcclusion`

**Comment by MJimitater** [comment] 2021-05-19 11:10
@deepak1556 thanks for getting back to this issue, thanks for the tips!
This only ever happend once to me, and since then not again, so its rather difficult for me to pinpoint and to repeat the issue.
But I'll keep my eyes open, and I'll report back here if it happens again.
Feel free to close this issue for so long, as long as we can reopen it if necessary.

**Comment by deepak1556** [comment] 2021-05-19 11:41
Closing for now, can reopen if the issue persists.

**Closed by deepak1556** 2021-05-19 11:41 UTC
Labels: needs more info, windows
