### ISSUE TITLE
[Bug] Hover placement problem

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#188243] opened 2023-07-19 06:03 UTC
* open `src/vs/platform/actions/browser/menuEntryActionViewItem.ts`
* scroll such that the viewport starts at line 131
* hover over the `MenuItemAction`
* (good) observe that the hover renders above the symbol because it fits
* hold cmd and slightly move mouse
* (bug) observe that the hover renders on top of the symbol. It should render below since it doesn't fit above.

https://github.com/microsoft/vscode/assets/5047891/7b9fef2c-189b-48b8-b468-b2b7be21c9b7

```
Version: 1.81.0-insider
Commit: 4390ebc406732e5b4eed22a1d7aa4fc0ef4a9460
Date: 2023-07-18T05:52:27.219Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by alexdima** [comment] 2023-07-19 06:14
An easier reproducible example. Simply hover over `doSomething`:

```ts
function doSomething(
	accessor: string,
	something: boolean,
	name: string,
	data: { p1: { [key: string]: string }; p2: { [key: string]: number } }
): void {
}
```


https://github.com/microsoft/vscode/assets/5047891/8c1a95b2-a831-48c7-b795-5404607cd9f6

**Comment by aiday-mar** [comment] 2023-07-20 14:38
I have reproduced this bug, I will be looking into it.

**Comment by aiday-mar** [comment] 2023-07-20 15:24
The bug is caused because the hover placement is not updated when the content changes. A PR with a fix has been made.

**Closed** 2023-07-21 07:36 UTC
Labels: bug, editor-hover
