### ISSUE TITLE
Relative image paths don't work in markdown in hovers

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#95947] opened 2020-04-23 07:35 UTC
Given the following TypeScript:

```ts
/**
 * This is my class
 *
 * # Example!
 *
 * ![foo](../images/foo.jpg)
 * */
class Foo { }
```

And an image at `../images/foo.jpg`, the image won't render:

<img width="297" alt="Screenshot 2020-04-23 at 08 31 41" src="https://user-images.githubusercontent.com/1078012/80071632-e08b9f00-853c-11ea-8bb7-1de2fe6c81c2.png">

The path is being resolved from the application folder:

file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/images/foo.png

This would be useful to support (without requiring each language to parse the markdown to find images and rewrite the paths). For example in Flutter we show images with previews of colors - these work because they're generated by us, but users may wish to do the same for their own classes:

<img width="498" alt="Screenshot 2020-04-23 at 08 35 03" src="https://user-images.githubusercontent.com/1078012/80071949-6d365d00-853d-11ea-843e-1b39269a6ed1.png">

**Comment by mjbvz** [comment] 2020-04-23 19:21
Duplicate of #86564 I believe

**Closed by mjbvz** 2020-04-23 19:21 UTC

**Comment by DanTup** [comment] 2020-04-23 20:35
Ah thanks - I did search but failed to find!
