### ISSUE TITLE
 Cannot read property 'other' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102353] opened 2020-07-13 05:58 UTC
Issue Id: <b>1d92da4d-ee80-28d1-a2d2-025fc5a9cfbb</b><br /><br />*Versions* <br />- 1.47.0<br />-  376d9d9d785ccca128fdbb16f001446d0ad64d32<br />-  e95f9e63380a139cb1cbe54bacfc6703b96e30b9<br />*Stack* <br />TypeError: Cannot read property 'other' of null<br />[/vs/editor/common/config/commonEditorConfig.ts#373:27 (_subsetEquals)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L373:27 (_subsetEquals))<br />[/vs/editor/common/config/commonEditorConfig.ts#385:15 (_subsetEquals)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L385:15 (_subsetEquals))<br />[/vs/editor/common/config/commonEditorConfig.ts#402:32 (updateOptions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/common/config/commonEditorConfig.ts#L402:32 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#363:22 (updateOptions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/browser/widget/codeEditorWidget.ts#L363:22 (updateOptions))<br />[/vs/workbench/browser/parts/editor/textEditor.ts#311:22 (updateEditorConfiguration)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/textEditor.ts#L311:22 (updateEditorConfiguration))<br />[/vs/workbench/browser/parts/editor/textEditor.ts#150:57 (call)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/textEditor.ts#L150:57 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#437:25 (setModel)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/browser/widget/codeEditorWidget.ts#L437:25 (setModel))<br />[/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#120:14](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L120:14)<br />[/vs/workbench/browser/parts/editor/editorControl.ts#180:3 (editorChanged)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/editorControl.ts#L180:3 (editorChanged))<br />[/vs/workbench/browser/parts/editor/editorControl.ts#67:23 (pos)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/browser/parts/editor/editorControl.ts#L67:23 (pos))<br />    at async out/vs/workbench/workbench.desktop.main.js:6290:577<br />[/vs/base/common/json.ts#244:16](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/json.ts#L244:16)<br />

**Comment by alexdima** [comment] 2020-07-21 09:42
Duplicate of #102920

**Closed by alexdima** 2020-07-21 09:42 UTC
Labels: error-telemetry
