### ISSUE TITLE
Git: Support nested git repositories

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [microsoft/vscode#37947] opened 2017-11-09 13:49 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

We use some command line tools from ARM to organise our project. This tools rely on special lib files to establish dependencies between modules. Each module should be an independent repository (git repositories in our case). So once all the references are deployed (the tools will "git clone" the indicated repositories in the lib files) the folder structure would look like this (folders in bold):

> - **project_folder** (git repo)
>     - module1.lib
>     - module2.lib
>     - **module1** (git repo)
>          - module3.lib
>          - **module3** (git repo)
>    - **module2** (git repo)

If we add **project_folder** as the root folder, the source control tab will only track the changes done in **project_folder**. 

If we use the new multi-root project feature and also add **module1**, **module2**, and **module3** to the workspace; we still find that only the changes in **project_folder** are tracked.

Nevertheless, if we add the folder in an strict reverse nesting order in the following manner:
1. With an empty project open **module3** as root folder
2. Add folder to workspace... **module2** 
3. Add folder to workspace... **module1**
4. Add folder to workspace... **project_folder**

Then we see that the source control view displays the several source control providers correctly.

Reproduces without extensions: Yes

**Comment by r44083** [comment] 2018-08-17 08:03
Is there any updates about this bug?

**Comment by sveinse** [comment] 2018-09-20 09:10
Thank you @javier-moreno-tridonic-com for the procedure in how to circumvent this issue by adding the projects to the workspace in inner->outer order. That helps a lot until this issue is fixed.

**Comment by AjawadMahmoud** [comment] 2018-10-02 05:33
The reverse order works, but screws up intillisense. My python modules from the child folder won't be able to access parent folder package causing all my child package modules to report errors of undefined module.
I'd suggest adding settings value to the workspace file where it would automatically populate at generation time all the auto-detected git repos. Then, we can manually set the additional paths for the nested git repos we are using.

**Comment by zurkoxxx** [comment] 2018-10-11 09:50
Had the same problem. 
Fixed it by adding nested repository as a submodule (https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by AjawadMahmoud** [comment] 2018-10-11 10:36
Some use cases defy the use of submodules.

**Comment by rhymu8354** [comment] 2018-10-12 03:56
In all my work, I have nested git repositories that are specifically _not_ submodules, and for this reason: I want the top-level repository to track each sub-level repository via branch, not commit.  I made a Python tool, [mugit](https://pypi.org/project/mugit/), which uses a manifest file to maintain the relative repository structure, similar to how Google organizes the Android multi-repository structure using their tool, [repo](https://source.android.com/setup/develop/repo).

Android Studio is notable for handling nested, non-submodule, multi-git repository structures quite nicely.  It would be great if VSCode could do the same.  In the mean time, I've been using the GitLens extension for most things, but still for making commits I'm pretty much forced to use another tool completely (e.g. git, git-gui, GitHub Desktop, SourceTree, etc.) to stage commits.

I'll be watching this issue with interest.  I was disappointed to see there were at least two previous issues filed for this exact same subject, but were closed in the belief that multi-repository support was somehow either already done in some "insider" build ([36250](https://github.com/Microsoft/vscode/issues/36250)) or would somehow ride on the coattails of the multi-folder workspace support ([12564](https://github.com/Microsoft/vscode/issues/12564)).

**Comment by rahman** [comment] 2018-11-14 23:55
+1 for nested git repo support

**Comment by RobertoSnap** [comment] 2019-01-07 08:22
Is this still only possible with submodules? @rhymu8354

In that case
+1 for nested git repo support

**Comment by p3t3r5** [comment] 2019-02-04 17:38
could be a workaround for you... i create .gitmodules in the root of main repo with content:
[submodule "your_module_name"]
	path = relative/path/to/module
	url = git/url/to/module

Its not realy configurated submodule, but VSCode can handle this. Its works recursively to.

VS Code v1.30.2
Git 2.16.2

**Comment by benlindsay** [comment] 2019-03-04 19:16
@p3t3r5 Thanks for this info! This feel like kind of a hack, but it's a good interim solution until repos in subdirectories are supported.

For anyone using this .gitmodules hack with no intention of using submodules, also note that the `url = ` line, while necessary for this hack to work, does not require a real URL. Based on some quick testing on my macbook, it looks like any non-whitespace string will work. (I currently have it working with `url = dummy_string_to_satisfy_vscode`)

**Comment by Morgy93** [comment] 2019-06-28 12:13
Any news on this? 🙏 
I'd love to have one of these options, maybe one is easy to implement:

```
main_repo/* <- Git1
main_repo/vendor/module1 <- Git2
main_repo/vendor/module2 <- Git3
```
(Pretty common for like php composer stuff)

A) Get the current path from terminal
The git integration checks the current path upon refresh.
So it uses Git1, but if I'm `cd main_repo/vendor/module1` then it shows me Git2 instead
- Probably not easy because of different shells and stuff

B) Use the current selection from the explorer
The git integration uses the current selected path upon refresh 
So as long as my selection is somewhere inside of Git3 this will be used for git integration:
![image](https://user-images.githubusercontent.com/7961978/60340612-5c17d080-99ac-11e9-89fb-73e3cb9e855c.png)

C) Set the current git path
Slightly different from B) if the "use current selection" is difficult:
Just right click and "set this as git path" so that this folder/path is used for the git integration.

For me it seems that the git integration does just like `git status` and this is of course always from the root of the opened folder.
If you could set a git path manually (via right click and select [C] or just use selection [B]) you could simply "add a prefix" do thinks like: `cd PATH && git status` (there are probably better ways but it would work)

I hope at least one is able to understand this mess 😁 
Not being able to simply/quickly select/use a nested repo sadly is a deal breaker for me.

**Comment by benlindsay** [comment] 2019-06-28 12:30
Did you try the solution above where you make a .gitmodules file as though you were going to use submodules but don't actually check it in? It's not ideal but at least it's a one time setup that allows integration of all your git repos

**Comment by Morgy93** [comment] 2019-06-28 13:00
@benlindsay 
I work on like 20 of those "main repos" and all of them have like 20 sub git repos which also have dependencies and my co-workers use those main repos as well, so I cannot track what sub repos are added.
I'd love to use a workaround, but this one is sadly not maintainable for me.

**Comment by benlindsay** [comment] 2019-06-28 13:08
Ah yeah I can see that wouldn't work for your use case.

**Comment by TheHackmeister** [comment] 2019-07-20 19:05
@Morgy93 I had a similar use case. My workaround was to create a script that would generate the .gitmodules. Still have to kick it off manually, but WAY easier than by hand. It works by searching for all the folders it needs to include, and then appends them to the .gitmodules. I just needed to loop over all the subfolders in a specific folder. I doubt you're that lucky. Maybe you could adapt this to use find and search for .git folders? 

https://github.com/SciFiFarms/TechnoCore/blob/8db3a1cb76f1be6cc4fb1449dc7245532bdbedeb/bin/generate_gitmodules#L1-L17

**Comment by JDDoesDev** [comment] 2019-07-24 17:56
I was able to get this working with the submodule hack as well, however there is an issue with order of submodules.

Here's my scenario:
I have a local dev environment, Docksal.  I want to be able to customize it so it's a repo.
I have a Drupal 8 codebase that I use for contribution and development.  This lives at `/docksal/docroot`.  This is a repo so I can patch and test.
I have a custom module that I've contributed back to d.o.  This lives at `/docksal/docroot/modules/custom/my_module` and is also a repo.

If I have the `.gitmodules` file list `docroot` before `my_module`, SCM doesn't pick up on `my_module`.
If I have the `.gitmodules` file list `docroot` after `my_module`, SCM finds them both.

A bit of a gotcha, but it's worth noting if anyone else finds their way to this thread.

**Comment by lid3rs** [comment] 2019-07-29 07:32
Any updates?

**Comment by michaelmcandrew** [comment] 2019-09-26 10:10
Elephant in the room: you can get around this without using (fake) git submodules if you use VScode workspaces as outlined by the OP.

**Comment by JojoS62** [comment] 2019-12-09 19:33
I ran into the same problem. I have a project root and some subdirs with own .git. These are shown properly when VSCode starts in the project root. 
I run the command 'Git: Initialize Repository' and it still works, the root git is added to the repo list.
Then I close and repoen VSCode and now only the git for the root is shown.
This looks like a problem with the enumeration of the git repos, when there is one found the enumeration for the subdirs is aborted.

**Comment by jasomimo** [comment] 2019-12-11 08:19
It would be great to have nested Git repositories support. I am having same issue, where we have main repo, which contains widgets, where each widget is separate Git repository.

**Comment by arterrey** [comment] 2019-12-21 03:00
+1 that is a very needed feature. It is quite common for build tools to checkout other repos, it would be nice to be able to edit and commit to dependent repos using the UI

**Comment by eine** [comment] 2020-01-16 00:55
I believe that #76904, which is now a candidate for `Backlog` would provide a solution to this issue. Hence, I would like to ask users that upvoted this issue to react to #76904 too.

**Comment by eine** [comment] 2020-01-16 02:11
> @eine I did look at #76904 however that is not for _nested_ repo's so would not be any different than having multiple folders in the workspace. So unfortunately not a solution to this issue.

It is for nested repo's, as long as each folder defined in the workspace file is expected to be an isolated domain. Precisely, that's the nuclear feature of #76904. Currently, it is possible to add subfolders (either submodules or nested repos) as additional folders in the workspace, but things are screwed up. #76904 makes it explicit that content in say `module1` needs to be tracked independently from the parent.

**Comment by joshbmarshall** [comment] 2020-01-16 03:07
> It is for nested repo's, as long as each folder defined in the workspace file is expected to be an isolated domain.

Unfortunately you're saying that for it to work with nested repos we would have to list them all in the workspace.
There are projects that have many repos that change often and can be cumbersome to add / remove manually.
There is a workaround for the nested git repositories at the moment - a dummy .gitmodules file. #76904 would just be another workaround for this issue.
Autodetection of nested git repos is the best option. I have added some notes at https://github.com/microsoft/vscode/issues/87888#issuecomment-574949683 on the current behaviour and what behaviour changes we require to get this resolved.

**Comment by eine** [comment] 2020-01-16 03:17
@joshbmarshall, that's correct. I did not claim #76904 to be the solution to this issue, nor that it should be superseeded. I just said that it can provide a solution, and asked other users for help to avoid having it closed.

**Comment by nandorojo** [comment] 2020-03-17 20:19
This bug still persists. Wondering if there are any plans to support nested git repos. Thanks!

**Comment by sveinse** [comment] 2020-04-28 15:19
Are there any plans on fixing this issue?

Due to the presence of the git top repo, the `git.scanRepositories` and `git.detectSubmodules` settings are completely ignored. This implies that either `.gitmodules` or adding folders inner>outer must be done to use them recursively VSCode. This issue is described in #96372

**Comment by Jibbajabbafic** [comment] 2020-05-21 11:22
+1 I would also like to see this issue fixed without needing to use hacky workarounds.

**Comment by aarograh** [comment] 2020-09-18 19:28
I'd also like to see this work as well, but I think I did find another workaround that's pretty clean (at least for those on unix-based systems):
1. Do not clone the nested repositories inside the parent repository; clone them next to the parent repository
2. Create a symbolic link to the nested repository at the location in the parent where you would normally clone the nested repository

I stumbled upon this in my project because I cloned 8 sub-repositories and sym-linked to a ninth, then noticed the sym-linked one was showing up in VS Code.  So I moved all the others and linked to them, and now they show up as well!  Just wanted to post that here in case it might be of help to someone else.

**Comment by ramyhhh** [comment] 2021-02-07 19:59
Well, +1 
I think nesting git repos is good to still be able to use monorepo at the same time make it modular and avoid sharing every app with all the teams

**Comment by stefanospetrakis** [comment] 2021-02-23 18:13
+1, missing this feature terribly in Composer-managed PHP projects.

**Comment by kusogaki77** [comment] 2021-03-12 14:21
Interesting that the very first project I try to maintain using VSCode makes use of a nested repo. 
Why does it take a few years to add automatic nested repo detection?

**Comment by jeremy-farrance** [comment] 2021-03-16 14:05
Still hoping this is upcoming. Really, really needed and "lightbulb" useful to many situations.

**Comment by Morgy93** [comment] 2021-03-16 14:20
Since the recent activity here, I want to highly recommend using workspaces, which solved the issue in my case.

So if you have a project like
Project root git: `/var/www/html/`
Sub git 1: `/var/www/html/vendor/foo/bar/`
Sub git 2: `/var/www/html/vendor/foo/baz/`

Just create a workspace file like `/var/www/html/my-project.code-workspace` which contains something like:
```
{
    "folders": [
        {
            "path": "vendor/foo/bar"
        },
        {
            "path": "vendor/foo/baz"
        },
        {
            "path": "."
        }
    ],
    "settings": {}
}
```

Open this workspace and you have all your nested git repos under source control:

![image](https://user-images.githubusercontent.com/7961978/111323528-422f8d00-866a-11eb-8598-c7d8e5636191.png)
(Yes, the names differ here, because I used a real workspace of mine instead of creating the demo workspace provided before 😜 )

Plus you have really quick access to all sub repos via explorer:

![image](https://user-images.githubusercontent.com/7961978/111324179-d39eff00-866a-11eb-91e2-e2b1c8138877.png)

I hope this helps one or another.

**Comment by JojoS62** [comment] 2021-03-22 19:06
@Morgy93 I've tried this, but it didn't work although I'm using workspaces already and the structure looks similar to your example.

Then I found the difference: when I use VSCode to add the workspace folders, they are added after the main project with { "path": "."}. In this case, the behaviour is like before: VSCode stops scanning for subfolders.
But when main project is the one in the workspaces list like in your example, then it works and the additional repos are shown.
When gitlens extension is installed, the repos must be activated in the 'view and sort' context menu in 'source control'.

**Comment by pshvechikov** [comment] 2021-06-14 08:23
Is there any plans to fix the issue? 
I find it VERY frustrating, especially because of the inconsistent behavior, the description of which follows.

Suppose a structure `main_git_repo/folder/another_git_repo_not_a_submodule`.
If I add the folder `main_git_repo` in a workspace I see only **one** git repository in the git sidebar tab (the main one). 
If I add two dummy folders `A/B`, move the `main_git_repo` inside the `B`, so that structure becomes `A/B/main_git_repo/folder/another_git_repo_not_a_submodule`, and then add a folder `A` in the workspace, I can see **two** git repositories in the git sidebar tab.

**Comment by Morgy93** [comment] 2021-06-14 08:37
@pshvechikov 
> Is there any plans to fix the issue?
> I find it VERY frustrating, especially because of the inconsistent behavior, the description of which follows.
> 
> Suppose a structure `main_git_repo/folder/another_git_repo_not_a_submodule`.
> If I add the folder `main_git_repo` in a workspace I see only **one** git repository in the git sidebar tab (the main one).
> If I add two dummy folders `A/B`, move the `main_git_repo` inside the `B`, so that structure becomes `A/B/main_git_repo/folder/another_git_repo_not_a_submodule`, and then add a folder `A` in the workspace, I can see **two** git repositories in the git sidebar tab.

Please have a look at my reply here: https://github.com/microsoft/vscode/issues/37947#issuecomment-800300385

Your `main_git_repo/my-awesome-project.code-workspace` would look something like:
```
{
    "folders": [
        {
            "path": "folder/another_git_repo_not_a_submodule"
        },
        {
            "path": "."
        }
    ],
    "settings": {}
}
```

If you open the workspace, you have the `another_git_repo_not_a_submodule` and `main_git_repo` available for editor and source control.

Hope it helps!

**Comment by JojoS62** [comment] 2021-06-14 08:45
the order of the workspaces is important, the root must be the last entry, then it works.

**Comment by IllusionSquid** [comment] 2021-12-15 14:12
> @Morgy93 I've tried this, but it didn't work although I'm using workspaces already and the structure looks similar to your example.
> 
> Then I found the difference: when I use VSCode to add the workspace folders, they are added after the main project with { "path": "."}. In this case, the behaviour is like before: VSCode stops scanning for subfolders. But when main project is the one in the workspaces list like in your example, then it works and the additional repos are shown. When gitlens extension is installed, the repos must be activated in the 'view and sort' context menu in 'source control'.

So I experienced this issue as well. By default vsc orders the .code-workspace as follows:
```
"folders": [
	{
		"path": "."
	},
	{
		"path": "very\\nice\\sub-folder"
	}
]
```
After reading that comment I tried placing the root path underneath:
```
"folders": [
	{
		"path": "very\\nice\\sub-folder"
	},
	{
		"path": "."
	}
]
```

This gave me both source controls. like @JojoS62 said, it seems that VSC stops scanning for folders after it got the one in the root folder.

Hope this helps somebody who is running into this issue.

**Comment by skupjoe** [comment] 2022-02-10 04:08
How come when I add just this to my workspace:
```
  {
    "name": "scripts",
    "path": "../../../scripts"
  },
```

it doesn't detect my projects under `../../../scripts/python/subfolder`....

But when I add this:
```
  {
    "name": "scripts",
    "path": "../../../scripts"
  },
  {
    "name": "python",
    "path": "../../../scripts/python"
  },
```
it detects my lower-level project directories (subfolders with `.git/` in them) just fine?

**Comment by gogobd** [comment] 2022-04-08 13:39
Any news on this? I just tried the workaroud posted by @skupjoe and that worked in my project. It would be great if nested git repos would be supported.

**Comment by jeremy-farrance** [comment] 2022-04-08 14:46
> Any news on this? I just tried the workaroud posted by @skupjoe and that worked in my project. It would be great if nested git repos would be supported.

@gogobd, its worth reading through this whole thread, in particular, the [detailed comment above](https://github.com/microsoft/vscode/issues/37947#issuecomment-800300385) by @Morgy93 has solved this for us (and others?). We have multiple projects where VS Code workspaces and `.gitmodules` do everything we need.
 
If it helps, here is an example of my .gitmodules file. So two child projects under a parent project.

```
# Nested projects
[submodule "Shared Tools"]
path = app/portal/c/content/shared
url = https://github.com/Org/ProjTools.git

[submodule "App_Code shared classes/constants"]
path = app/App_Code
url = https://github.com/Org/ProjAppCode.git

### Hack
### it is CRITICAL this .gitmodules file (in the parent) is .gitignore'd
### in English; tell local Git about the sub-modules, but NOT GitHub
### https://github.com/microsoft/vscode/issues/37947#issuecomment-460340426
# Docs; https://git-scm.com/docs/gitmodules

## optional keys (see docs)
# update # checkout, rebase, merge, none
# branch # defaults to HEAD
# ignore # all, dirty, untracked, none
```
And here is what it looks like in VS Code Files, 1 is the root/parent proj, 2 and 3 are the submodules (above)
![image](https://user-images.githubusercontent.com/653301/162461969-87cf2f20-164a-4f9e-bb8c-36bb959d42a2.png)

**Comment by gogobd** [comment] 2022-04-08 15:25
Hi!
Thanks for pointing this out. I was using a workspace file and that "solves" the issue for me/us but unfortunately it's not dynamic and doesn't pick up newly added repositories.
The project I'm currently working on doesn't use submodules and it's not planned to change this.

That's why I was interested if vscode would ever add modules that are located in a directory that's listed in "Git: Scan Repositories" even when they are nested.

**Comment by jeremy-farrance** [comment] 2022-04-08 15:55
Oh, I see. I agree that VS Code needs to be more aware of and automatically handle this. I find the setup (that works for us) to be awkward and fragile.

**Comment by gogobd** [comment] 2022-04-08 16:15
Note: There's a related issue here: (https://github.com/microsoft/vscode/issues/87888)

**Comment by plwalsh** [comment] 2022-04-08 16:39
I know you've got the workspaces workaround in place, but just a note for others who come across this page:

> The project I'm currently working on doesn't use submodules and it's not planned to change this.

You don't actually need to set up submodules for your project in order to use this workaround. It's just a local hack where you create a "fake" `.gitmodules` file that gets picked up by vscode for its repo sidebar; it never gets committed or anything.

**Comment by jeremy-farrance** [comment] 2022-04-08 16:54
Rephrase, because its key to the hack - tell your local Git instance about the submodules via .gitmodules, but make sure that file is .gitignored so GitHub (or your real Git repo/server) doesn't find out about it. :)

**Comment by jan-hudec** [comment] 2022-04-08 21:43
I don't think ignoring the `.gitmodules` file is what makes any difference. What makes the difference is never calling the git command to init the submodules or record their versions.

**Comment by gogobd** [comment] 2022-04-09 18:56
The submodules hack works; however if I'd `init` there's a fair chance that I break something.

What I don't understand is that vscode doesn't pick up repositories even when they are specified explicitly via `Git: Scan Repositories` - it feels strange to use any sort of "hack" to get there.

**Comment by plwalsh** [comment] 2022-04-09 19:48
It's more of a "fake out" than a hack. And the whole point is that you *don't* `init` anything. You just create a single file, and that's it. Nothing more. You don't init it, you don't commit it. Just the simple existence of the file is all you need.

But yes, it would be nice if vscode found these nested repos on its own.

**Comment by orlandoaleman** [comment] 2022-05-11 20:34
Please!

**Comment by slitcch** [comment] 2022-05-23 14:14
I just want to be able to search within and ctrl+p to files in nested repos...

**Comment by orlandoaleman** [comment] 2022-05-24 18:04
> I just want to be able to search within and ctrl+p to files in nested repos...

I made a detour for this by creating a symbolic link (macos, linux) from an external location (eg a sibling of root) to the child folder. Then I have combined both in a workspace.

**Comment by wesleybl** [comment] 2022-05-25 03:41
@lszomoru any news on this? I'm +1 for this feature. And there are a lot of people who need it too.

**Comment by ms2pony** [comment] 2022-07-11 08:14
all my bro want this feature，so please!

**Comment by gogobd** [comment] 2022-07-21 08:31
Any news?

**Comment by nteymory** [comment] 2022-08-09 18:03
I already mentioned this in https://github.com/microsoft/vscode/issues/157347, but

If you temporarily move the .git folder from your workspace root, then open the workspace, then put the .git folder back, vscode detects all the repositories correctly. Note, this _does not work_ if you do it while the workspace is currently open. 

It seems to me there is a check that happens when a workspace is opened: 

- Is there a repository in the root of the workspace?
- If yes, then for the rest of this session don't scan subdirectories for additional repositories
- If no, then scan all subdirectories for repositories

Assuming such a check is actually happening, I think all we need is a configuration option to disable it.

**Comment by nteymory** [comment] 2022-08-09 23:24
Ok, this bothered me enough that I decided to spend the afternoon debugging it and I've figured it out. The problem lies within the function `Model.getOpenRepository` inside `model.ts`

The problematic part is this for loop

```
for (const liveRepository of this.openRepositories.sort((a, b) => b.repository.root.length - a.repository.root.length)) {
	if (!isDescendant(liveRepository.repository.root, resourcePath)) {
		continue;
	}

	for (const submodule of liveRepository.repository.submodules) {
		const submoduleRoot = path.join(liveRepository.repository.root, submodule.path);

		if (isDescendant(submoduleRoot, resourcePath)) {
			continue outer;
		}
	}

	return liveRepository;
}
```

What is happening here is that the `resourcePath` (the current potential directory that _could be_ a git repository) is being checked to see if it's a subdirectory (`isDescendent`)  of some already discovered repository. If it is, the for loop checks if it corresponds to a submodule of the parent and if so, will not consider it part of this repo. Otherwise, it assumes that the path being tested is part of the parent repository. This sort of makes sense.. 

This explains why the submodule "hack" above works, why if you load repositories in reverse order it works, and also why my workaround of removing the parent .git folder and readding afterwards works as well -- as long as you haven't discovered the parent repro before you add the child repro everything works.

Now, I'm not exactly sure what the right way to fix this is, but I propose the following change: check if `resourcePath` contains a .git folder, if it does, it should be considered it's own repo. That's it. There is probably a "more correct" way to do this, but this is what I did in my local build and it fixed the problem for me:

```
for (const liveRepository of this.openRepositories.sort((a, b) => b.repository.root.length - a.repository.root.length)) {
	if (!isDescendant(liveRepository.repository.root, resourcePath)) {
		continue;
	}

	for (const submodule of liveRepository.repository.submodules) {
		const submoduleRoot = path.join(liveRepository.repository.root, submodule.path);

		if (isDescendant(submoduleRoot, resourcePath)) {
			continue outer;
		}
	}

        // NEW CODE
	// We are a descendant, and we are not a submodule
	// If we also are not the exact path for the repository being tested
	if (!pathEquals(liveRepository.repository.root, resourcePath)) {
		// Then check if we have our own .git folder
		// If we do, this implies we are our own repository
		// and therefore and not just a subfolder of this outer repository
		if (fs.existsSync(path.join(resourcePath, ".git"))) {
			continue;
		}
	}
        // ~NEW CODE

	return liveRepository;
}
```

I'm willing to make a pull request if this solution is not considered horrible @lszomoru. Otherwise, I'm happy to leave it to you to fix "properly".

If anyone doesn't want to wait for the fix, you can patch this into your build right away. Here is how to do it:

Locate your vscode install and navigate to `resources\app\extensions\git\dist\main.js`. For example for me it was located here
```
C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js
```
This file is optimized so it's a bit tricky to edit. Make sure you are using a decent editor. Look for this bit of code `(0,s.isDescendant)(e.repository.root,t)`. You can manually expand the braces to see the logic above:

```
			e: for(const e of this.openRepositories.sort(((e,t)=>t.repository.root.length-e.repository.root.length)))
			{
				if((0,s.isDescendant)(e.repository.root,t))
				{
					for(const r of e.repository.submodules)
					{
						const i=c.join(e.repository.root,r.path);
						if((0,s.isDescendant)(i,t))
						{
							continue e
						}
					}
					return e
				}
			}
```
Patch it by adding this bit into the for loop
```
			e: for(const e of this.openRepositories.sort(((e,t)=>t.repository.root.length-e.repository.root.length)))
			{
				if((0,s.isDescendant)(e.repository.root,t))
				{
					for(const r of e.repository.submodules)
					{
						const i=c.join(e.repository.root,r.path);
						if((0,s.isDescendant)(i,t))
						{
							continue e
						}
					}
					
                                        // NEW CODE
					if (!s.pathEquals(e.repository.root, t)) {
						if (l.existsSync(c.join(t, ".git"))) {
							continue e
						}
					}
                                        // ~NEW CODE

					return e
				}
			}
```
Reload your workspace and it should now work the way you expect

There is one more thing to consider here, there is a setting that you may always want to double check. By default, vscode will only search 1 folder deep for additional repos. If your repos are deeper, this alone won't fix it, update this setting as well:

```
git.repositoryScanMaxDepth
```

**Comment by JanJakes** [comment] 2022-08-10 10:25
@nteymory Awesome! The patch seems to work for me. I think a pull request would move any further discussion to the code and could help move this forward; what do you think?

**Comment by lszomoru** [comment] 2022-08-10 10:32
@nteymory, thank you very much for the investigation. Since the issue has been labeled with `help wanted`, I would suggest that you create a PR so that we can move the conversation there. Adjusting the repository discovery code is a great start but we will have to see if there are other areas in the `git` extension that need to be tweaked to fully support nested repositories.

**Comment by nteymory** [comment] 2022-08-10 16:45
Sure, PR created: https://github.com/microsoft/vscode/pull/157812

**Comment by BrockHallenbeck** [comment] 2022-09-03 18:53
@nteymory is this a git specific solution? I am observing identical behavior using subversion and am hopeful this effort will benefit SVN users as well.

**Comment by nteymory** [comment] 2022-09-04 19:25
> @nteymory is this a git specific solution? I am observing identical behavior using subversion and am hopeful this effort will benefit SVN users as well.

Unfortunately, yes, it is

**Comment by lszomoru** [comment] 2022-09-08 09:27
I know that it has been a long time coming, but today's Insiders release (2022-09-08) contains changes to the repository discovery code that detects nested git repositories. Depending on how deep the nested repositories are, one might have to tweak the `git.repositoryScanMaxDepth` setting.

At the moment we have only tweaked the repository discovery code, but I do expect some additional paper-cuts on the way so I would like to ask you to update to the latest Insiders release, try out this new capability and let us know if you are running into any issues. Thank you very much!

**Comment by wesleybl** [comment] 2022-09-10 02:58
@lszomoru 

I tested with the following version:

```
Version: 1.72.0-insider
Commit: 5cecbf4746a7b95dedaf9fc4534b9786b9a30ace
Date: 2022-09-09T16:25:41.046Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 4.15.0-176-generic
Sandboxed: Yes
```

It worked for me! I had to be setting `git.repositoryScanMaxDepth` to 2 to work for me. My root folder is a git repository, and inside it is a folder that has two git repositories. Changes in 3 repositories are detected.

After changing `git.repositoryScanMaxDepth`, it only started working after restarting VSCode. This is expected, correct?

Thanks for the fix!

**Comment by lszomoru** [comment] 2022-09-12 09:34
@wesleybl, thanks for testing out the changes.  

> After changing git.repositoryScanMaxDepth, it only started working after restarting VSCode. This is expected, correct?

That is currently expected behaviour.

**Comment by hemmingsv** [comment] 2022-09-14 11:00
@lszomoru installing code-insiders with latest snap on ubuntu 22.04 => works perfectly, all git subfolders detected, inline git diffs show up as expected. Fantastic!

**Comment by lszomoru** [comment] 2022-09-14 15:47
@hemmingsv, thank you very much for trying out and validating the new functionality.

**Comment by lszomoru** [comment] 2022-09-16 13:57
With the changes to the repository discovery code checked into main, and slated to be included in the next Stable release, I will got ahead and close this issue. Any other issues that are being discovered with nested git repositories should be handled in separate issues. Thank you all for your help, and for your patience.

**Closed** 2022-09-16 13:57 UTC
Labels: feature-request, git

**Comment by abhijitchikane** [comment] 2022-09-22 15:40
I just tried the nested git repo Initially it did show me the git subfolders but after I reload the vscode it is no more working
anything I am missing or any setting that I may have changed?

**Comment by lszomoru** [comment] 2022-09-23 05:42
@abhijitchikane, could you please create a separate issue so that we continue the investigation? Thanks!
