### ISSUE TITLE
when I commit code to gitlab,vscode can't edit commit message

### ISSUE THREAD

**Issue by djytwy** [microsoft/vscode#113527] opened 2020-12-29 07:39 UTC
- VSCode Version: November 2020 (version 1.52)
- OS Version:  Mac OS 10.15.6

Steps to Reproduce:
1.
When I update the version of the editor, sometimes I cannot edit commit message.
like this:
![image](https://user-images.githubusercontent.com/30172796/103266867-7be9e380-49eb-11eb-9f6b-2d9442e467f8.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment] 2021-01-04 21:01
Is there anything more you can tell us about when this happens? If you unfocus and re-focus the input, does it fix it?

/cc @zinwalin

**Comment by eamodio** [comment] 2021-01-05 06:13
Duplicate of #112621

**Closed by eamodio** 2021-01-05 06:13 UTC
Labels: git, needs more info
