### ISSUE TITLE
Can‘t install extension without internet access anymore

### ISSUE THREAD

**Issue by skrysmanski** [Microsoft/vscode#38616] opened 2017-11-17 12:14 UTC
- VSCode Version: 1.18.1
- OS Version: Windows 7

Steps to Reproduce:

1. Have no internet connection
2. Try to install an extension via command line (with `—install-extension`)

When you do this, you get an error like this:

```
code --install-extension vscode-icons.vsix
Error: getaddrinfo EAI_AGAIN marketplace.visualstudio.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

Extension doesn‘t seem to matter. I‘ve also verified that the extension doesn‘t get installed anyways.

Unfortunately, in my situation I do not have any internet connection.

This used to work with version 1.17.2.

**Comment by sandy081** [comment] 2017-11-20 09:19
Duplicate of #37973

**Closed** 2017-11-20 09:19 UTC
Labels: *duplicate, extensions, new release
