### ISSUE TITLE
Generate Commit Message hides characters behind it

### ISSUE THREAD

**Issue by blakegearin** [microsoft/vscode#197202] opened 2023-11-02 04:55 UTC
Does this issue occur when all extensions are disabled?: No, but I'm not sure that's relevant because "Generate Commit Message" is not present despite being a native, non-extension feature (based on other bug reports)

- VS Code Version: 1.84.0
- OS Version: macOS 13.5.2

Steps to Reproduce:

1. Go to Source Control
1. Type a longer commit message into the textbox
1. Resize and see characters disappear behind the "Generate Commit Message" button

![generate commit message bug](https://github.com/microsoft/vscode/assets/17950836/a16a0592-eaa3-4e94-9e0c-37f69321a20f)

**Comment by gjsjohnmurray** [comment] 2023-11-02 07:20
See also #195773

**Comment by lszomoru** [comment] 2023-11-02 15:31
Closing as duplicate of #195773.

**Closed by lszomoru** 2023-11-02 15:31 UTC
Labels: bug, scm, new release
