### ISSUE TITLE
 Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#65699] opened 2018-12-26 18:09 UTC
Issue Id: <b>00ce83dc-9ed1-ed9f-5811-4db18c25755e</b><br /><br />*Versions* <br />- 1.31.0-insider (12/21/2018 6:20:22 AM)<br />-  c6b23294522f5ceebe57ec591d522ab2cbe46ecd<br />*Stack* <br />Error: Tree element not found: [object Object]<br />    at e.getElementLocation (out/vs/workbench/workbench.main.js:98:730)<br />    at e.isCollapsed (out/vs/workbench/workbench.main.js:98:85)<br />    at n.e.isCollapsed (out/vs/workbench/workbench.main.js:951:336)<br />    at t.revealMarkersForCurrentActiveEditor (out/vs/workbench/workbench.main.js:4725:499)<br />    at t.autoReveal (out/vs/workbench/workbench.main.js:4725:318)<br />    at t.onActiveEditorChanged (out/vs/workbench/workbench.main.js:4722:434)<br />    at e.fire (out/vs/workbench/workbench.main.js:81:875)<br />    at t.doEmitActiveEditorChangeEvent (out/vs/workbench/workbench.main.js:4736:568)<br />    at t.handleActiveEditorChange (out/vs/workbench/workbench.main.js:4736:344)<br />    at out/vs/workbench/workbench.main.js:4736:692<br />    at e.fire (out/vs/workbench/workbench.main.js:81:855)<br />    at out/vs/workbench/workbench.main.js:5188:868<br />

**Comment by Tyriar** [comment] 2018-12-26 18:13
Some other stack traces:

```
Error: Tree element not found: [object Object]
at e.getElementLocation (out/vs/workbench/workbench.main.js:98:730) 
at e.isCollapsed (out/vs/workbench/workbench.main.js:98:85) 
at n.e.isCollapsed (out/vs/workbench/workbench.main.js:951:336) 
at t.revealMarkersForCurrentActiveEditor (out/vs/workbench/workbench.main.js:4725:499) 
at t.autoReveal (out/vs/workbench/workbench.main.js:4725:318) 
at t.onActiveEditorChanged (out/vs/workbench/workbench.main.js:4722:434) 
at e.fire (out/vs/workbench/workbench.main.js:81:875) 
at t.doEmitActiveEditorChangeEvent (out/vs/workbench/workbench.main.js:4736:568) 
at t.handleActiveEditorChange (out/vs/workbench/workbench.main.js:4736:344) 
at out/vs/workbench/workbench.main.js:4735:795 
at e.fire (out/vs/workbench/workbench.main.js:81:855) 
at t.doSetGroupActive (out/vs/workbench/workbench.main.js:5208:609) 
at t.activateGroup (out/vs/workbench/workbench.main.js:5205:623) 
at t.doOpenEditor (out/vs/workbench/workbench.main.js:5188:50 
```

```
Error: Tree element not found: [object Object]
at e.getElementLocation (out/vs/workbench/workbench.main.js:98:730) 
at e.setChildren (out/vs/workbench/workbench.main.js:96:654) 
at t.setChildren (out/vs/workbench/workbench.main.js:956:826) 
at n.e.setChildren (out/vs/workbench/workbench.main.js:969:50) 
at out/vs/workbench/workbench.main.js:967:744 
```

**Comment by sandy081** [comment] 2019-01-25 09:22
Duplicate of #66325

**Closed** 2019-01-25 09:22 UTC
Labels: *duplicate, error-list, error-telemetry
