### ISSUE TITLE
Slow Saving due to "Quick Fixes"

### ISSUE THREAD

**Issue by lumyx2** [microsoft/vscode#90376] opened 2020-02-10 15:55 UTC
Saving Javascript files is very slow. The extension reported is "Quick Fixes". I do not have any extension with that name so I don't know if it an extensio of VS Code.  See image below.

![image](https://user-images.githubusercontent.com/8171323/74165905-b143e200-4c1d-11ea-9756-b9f08b0b68d1.png)

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.37GB free)|
|Process Argv|--folder-uri file:///f%3A/Eng_Cambridge/PhD/Project_Workspace/d3_exp_IMS_apps|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
githistory|don|0.5.0
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.11
todo-tree|Gru|0.0.167
asciidecorator|hel|0.2.0
beautify|Hoo|1.5.0
theme-by-language|jsa|1.1.1
vscode-map-preview|jum|0.5.1
vscode-github|Kni|0.30.3
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
remote-wsl|ms-|0.42.3
vscode-json-editor|nic|0.2.3
indent-rainbow|ode|7.4.0
fix-json|oli|0.1.2
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.9.3
vscode-yaml|red|0.6.1
highlight-words|rsb|0.1.4
indenticator|Sir|0.6.0
selectline-statusbar|tom|0.0.2
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-02-10 17:14
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by lumyx2** [comment] 2020-02-10 17:19
Yes, I just tried. See image below.

[image: image.png]

**Comment by lumyx2** [comment] 2020-02-10 17:26
Hi Matt,

Actually, it looks like it's an extension that didn't get disabled!
The one called "Bracket Pair Colorizer 2". People reported high CPU usage
with that one.
Any suggestion on one that shows different colours for brackets?

Thanks,
M

**Comment by mjbvz** [comment] 2020-02-10 22:15
So if you disable it, you can't repo this issue?

**Comment by muuvmuuv** [comment] 2020-02-11 07:55
I'm experiencing the same but haven't tried without extensions because it appears to be not reproduce able everytime. I guess my "quick fix" formatter is prettier in this case. 

MacOS: 10.15.3
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

<details>
<summary>Screenshot</summary>

![Bildschirmfoto 2020-02-11 um 08 49 07](https://user-images.githubusercontent.com/11534760/74218962-ac2d7400-4cab-11ea-9f35-421752f32d6f.png)

</details>

If it happens another time I'll copy the process explorer and try to debug it more. Just appeared a few seconds but goes up to 4000% CPU load.

**Comment by lumyx2** [comment] 2020-02-11 11:20
Hi Marvin,

I get lots of spikes actually, but I normally ignore them as I have quite a
few different extensions.
In all honesty, unless it totally breaks I have pretty much given up. Every
time something gets fixed in VS Code
something else breaks it. I really wish a lot of the functionality would
get implemented into the core of the editor
instead of having 200+ extensions that offer a bit of functionality that
another one missed. It makes it really hard to
troubleshoot.

**Comment by eyalhakim** [comment] 2020-02-18 11:02
Having the same issue

**Comment by simkessy** [comment] 2020-02-23 16:55
Been having same issue same last updates, it's making working on js unbearable

**Comment by iobond** [comment] 2020-03-14 17:04
same issue, after upgrade vs-code, it happens

**Comment by lumyx2** [comment] 2020-07-07 11:58
Unfortunately, I can't. I simply stopped using it as it was not reliable
enough to work with.
I am working on other stuff now so I haven't used VS-Code in 4 months.

**Comment by mjbvz** [comment] 2020-07-07 19:51
I'm closing this because we don't have clear steps to reproduce. It sounds like it was caused by an extension so if you can figure out which one, please file an issue against them

**Closed by mjbvz** 2020-07-07 19:51 UTC
Labels: needs more info
