### ISSUE TITLE
TSServer consume constant CPU load (~10% or even more) also I am not typing or doing anything in VS Code

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#51139] opened 2018-06-05 10:35 UTC
See attached screen shot.

This is with having the VS Code workspace open
![cast](https://user-images.githubusercontent.com/1931590/40971148-f5077e2a-68bc-11e8-94e5-2bdf1f3a9f66.gif)

**Comment by dbaeumer** [comment] 2018-06-05 10:36
Version 1.24.0-insider
Commit f67e6397855fb25becbdf33df185f96da7fdd108
Date 2018-06-04T20:56:48.515Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by dbaeumer** [comment] 2018-06-05 13:29
Some more testing:

- After I start the CPU load after some initial computation goes down to 0%
- I don't know exactly when but after some time the tsserver never goes beyond 10% CPU consumption for a longer period of time (> 5 seconds) even if I have VS Code in the background
- I do start `scripts\code` if that makes a difference and I have `npm run gulp watch` running

**Comment by dbaeumer** [comment] 2018-06-05 18:37
Same happens with

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by dbaeumer** [comment] 2018-06-05 18:43
I could now reproduce this by simply starting code opening `task.contribution.ts` and then let it sit for a while.

**Comment by dbaeumer** [comment] 2018-06-05 18:56
I tried again and this time it didn't reproduce. So it is not consistent but if it happens then the impact it quite noticeable on the CPU. Anything you want me to do to help tracking this down?

**Comment by mjbvz** [comment] 2018-06-06 00:02
I haven't been able to repo this using those steps. Let me try on windows too though.

Can you  please check the tsserver log to if it says that anything is happening during the periods of cpu usage

**Comment by dbaeumer** [comment] 2018-06-06 08:11
Will do.

**Comment by dbaeumer** [comment] 2018-06-06 11:42
Here is the server.log. I noticed high CPU load at the end of the session (around 13:34). The interesting thing is that the tsserver watches for file changes that are totally unrelated to any project info.

[tsserver.log](https://github.com/Microsoft/vscode/files/2075959/tsserver.log)
[ti-16276.log](https://github.com/Microsoft/vscode/files/2075960/ti-16276.log)

**Comment by sheetalkamat** [comment] 2018-06-07 17:45
I think the root cause for this is #24471 where in we aren't ignoring writes in some cases. This would repro only for classic module resolution. Working on fixing this.

**Comment by mjbvz** [comment] 2018-06-07 18:51
@dbaeumer Can you please test this with TypeScript@next as well?

**Comment by sheetalkamat** [comment] 2018-06-07 20:17
@mjbvz @dbaeumer The issue here is location of vscode folder in "c:/users/username/Projects" folder. We ignore "/users/username/Projects" and "c:/users/Projects" kind of pattern but not that one. I am working on the fix. Thanks.

**Comment by mhegazy** [comment] 2018-06-07 22:40
@dbaeumer can you give `typescript@3.0.0-dev.20180608` tonight a try and see if that addresses your issue?

**Comment by dbaeumer** [comment] 2018-06-08 09:11
I installed it and so far I can't reproduce the CPU consumption.

**Comment by dbaeumer** [comment] 2018-06-08 10:13
Have to take it back. I do CPU consumption again, however it is a little lower than before. The tsserver consumes between 5 and 10 percent having VS Code open.

**Comment by dbaeumer** [comment] 2018-06-08 13:30
Here is another screen cast using the latest nightly. The interesting think is that the CPU activity occurs even though nothing is written to the log. I check the file after I stop capturing and it still had the same content.

![cast](https://user-images.githubusercontent.com/1931590/41160715-d74bd586-6b30-11e8-8c3b-5972cb7679de.gif)

**Comment by sheetalkamat** [comment] 2018-06-14 20:13
@dbaeumer I have fix for it in Microsoft/TypeScript#24933 which i just merged. We are currently experiencing typescript drop publishing issues, but once its resolved, there will be new drop in typescript@next. Can you give that a try. Alternatively you can always build from master branch. Thanks.

**Comment by mhegazy** [comment] 2018-06-14 20:53
A note about nightly releases, We are having problems with our build and publish, so it is possible that we do not have `typescript@next` published tonight. I think we should have that fixed by Friday.

**Comment by dbaeumer** [comment] 2018-06-15 07:15
Checked this morning and there is no recent nightly build. Will look again Monday.

**Comment by mjbvz** [comment] 2018-06-20 21:00
@dbaeumer Nightly ts builds should have resumed. Can you please test this again on the latest typescript@next

**Comment by dbaeumer** [comment] 2018-06-21 08:57
Will do

**Comment by dbaeumer** [comment] 2018-07-03 09:58
I retested this and it is still very bad. A nice reproducible test case is as follows:

- clone vscode
- set it up for development (see https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source)
- open VS Code 
- open some TS files under src
- open a terminal
- in the terminal run npm run gulp vscode-win32-x64

Although the out folders are listed in the tsconfig.json as excludes the TS server reacts to file events in the out folder buring up to 20% of my CPU. I have attached a trace as well.

[tsserver.log](https://github.com/Microsoft/vscode/files/2158716/tsserver.log)

@mhegazy @sheetalkamat can you please have a look.

**Comment by dbaeumer** [comment] 2018-07-03 10:09
Even closing all TS files when this happens doesn't help to cool down the tsserver. I tested it with typescript@next.

**Comment by sheetalkamat** [comment] 2018-07-03 18:53
Looking at the log it seems like you have multiple projects open based on files open. Also noticed that most of the directory watcher callback were for the inferred project but none of them schedule project update (ignoring the file/directory that its invoked on) The compiler options for that inferred project would be:
```
{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}
```
And current directory for that project would be projectRoot from open request ("c:\\Users\\dirkb\\Projects\\mseng\\VSCode\\vscode")
```
 {"seq":24,"type":"request","command":"open","arguments":{"file":"c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/bootstrap-amd.js","fileContent":"<<CONTENT>>","scriptKindName":"JS","projectRootPath":"c:\\Users\\dirkb\\Projects\\mseng\\VSCode\\vscode"}}
```
which results in watching that directory for any failed module resolution locations. (eg instead of watching ```["c:/github/vscode/src/vs/loader.ts","c:/github/vscode/src/vs/loader.tsx","c:/github/vscode/src/vs/loader.d.ts","c:/github/vscode/src/vs/loader/package.json","c:/github/vscode/src/vs/loader/index.ts","c:/github/vscode/src/vs/loader/index.tsx","c:/github/vscode/src/vs/loader/index.d.ts"]``` it watches the root directory as an optimization.

```
Info 2275 [11:37:44.736] Project '/dev/null/inferredProject1*' (Inferred) 2
Info 2275 [11:37:44.736] 	Files (26)
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es5.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2016.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.dom.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.dom.iterable.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.scripthost.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.core.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.collection.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.generator.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.promise.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	C:/Users/dirkb/Projects/mseng/node_modules/typescript/lib/lib.es2016.full.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/vs/loader.js
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/bootstrap-amd.js
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/keytar/index.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/minimist/index.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/mocha/index.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/node/index.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/semver/index.d.ts
	c:/Users/dirkb/Projects/mseng/VSCode/vscode/node_modules/@types/sinon/index.d.ts
Info 2275 [11:37:44.736] Open files: 
Info 2275 [11:37:44.736] 	FileName: c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/vs/nls.d.ts ProjectRootPath: c:/Users/dirkb/Projects/mseng/VSCode/vscode
Info 2275 [11:37:44.736] 		Projects: c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/tsconfig.json
Info 2275 [11:37:44.736] 	FileName: c:/Users/dirkb/Projects/mseng/VSCode/vscode/src/bootstrap-amd.js ProjectRootPath: c:/Users/dirkb/Projects/mseng/VSCode/vscode
Info 2275 [11:37:44.736] 		Projects: /dev/null/inferredProject1*
Info 2275 [11:37:44.736] 	FileName: c:/Users/dirkb/Projects/mseng/VSCode/vscode/build/gulpfile.vscode.js ProjectRootPath: c:/Users/dirkb/Projects/mseng/VSCode/vscode
Info 2275 [11:37:44.736] 		Projects: c:/Users/dirkb/Projects/mseng/VSCode/vscode/build/tsconfig.json
```

Note that just closing files is not enough since we keep the projects alive even after close because most of the users tend to reopen same project and we want to speedup that. (the orphan projects/infos are removed on next file open if they are still orphan)

**Comment by dbaeumer** [comment] 2018-07-04 08:42
@sheetalkamat thanks for looking into this. Is there anything that I can do to avoid this. Is this because I use the tsserver from `C:/Users/dirkb/Projects/mseng/node_modules/typescript`. I only do that because you ask me to verify the bug on latest typescript. 

All I see is ~20% CPU load of the tsserver when compile VS Code using `npm run gulp vscode-win32-x64` with me not even using VS Code.

**Comment by sheetalkamat** [comment] 2018-07-05 17:44
@dbaeumer I am still thinking about what we can do for better experience here. The issue isnt about using tsserver location, it is more to do with your js file, its locations and  trying to resolve modules and having failed lookup locations being watched.

**Comment by sheetalkamat** [comment] 2018-07-05 23:10
@dbaeumer I have a prototype on https://github.com/Microsoft/TypeScript/tree/optimizeFailedLookupWatchOverCorrectness Can you please build and use that tsserver to see if it helps.
In that prototype, the failed lookup locations are not watched if module resolution ends up in any of the typescript file or allowJs is true and js file. So only really failed resolutions are watched so its not ideal but can be a good compromise.

**Comment by sheetalkamat** [comment] 2018-07-09 19:09
@dbaeumer The exclude property only helps with the initial list of files to be included in the project. Module resolution can add files on those excluded folder to your program if thats where file for resolution is. In short suppose you said exlude to contain node_modules and file a.ts references module b from node_modules/b/index.d.ts then  that file is added to the program.

**Comment by dbaeumer** [comment] 2018-07-10 16:39
@sheetalkamat OK I see. But for our example we know for sure that the TS server shouldn't resolve modules from the out folder. May be it would make sense to let us specify this in the `tsconfig.json` with something like:

```
{
    "folder": "../out",
    "moduleResolution: true
}
```

to exclude it from module resolution (e.g. have this literal instead of a string in the exclude array.

**Comment by sheetalkamat** [comment] 2018-07-10 17:48
I am not sure if thats going to help with your scenario. When we watch a directory there is no way to exclude it for certain folders.. (unless we create our own watch implementation for it.) In your scenario you arent watching directory for files in out folder, so any watcher invoked because of that will ignore it and not invalidate your project.

**Comment by dbaeumer** [comment] 2018-07-10 18:40
May be I don't understand then what is causing the CPU load. I thought it can't be the simple watching that causes 20% CPU load on a Surface Book 2. I was under the impression that the tsserver does something which could be ignore with the above information.

**Comment by sheetalkamat** [comment] 2018-07-11 18:12
It isnt the actual watch (since thats the file system based watch) but it being triggered often as you compile the code that makes it take cpu. It ignores those directories after the watch is invoked but we cant make it not invoke the watch.

**Comment by dbaeumer** [comment] 2018-07-12 15:46
I tested your branch and even then I see spikes in CPU between 10% and 15%. I have to say I am still not understanding what I can do to make this go away. Or are you saying the tsserver needs 10% - 15% CPU load to decide to do nothing.

**Comment by sheetalkamat** [comment] 2018-07-12 23:59
I looked into this further, and i dont seem to see high cpu with branch noFailedLookupWatchForResolvedModules which is just rebase of the old prototype to master. 
I have been looking into the logs you sent and the logs i am getting when i try to repro this as per your steps + logs, and there seem to be log of "reloadProjects" sent to the server. Any idea why ? That would reload complete project structure and that command seems to be too frequent and would need to re-read project structure from disk and update the projects. Those commands are followed by getErr as well. 

Can you use the branch noFailedLookupWatchForResolvedModules  and get me the tsserver and ti log both. And if possible approximate time stamp when you notice the high cpu usage. (so far i have been following your commands only open and quickinfo/navigatrion kinds from what your log says)

**Comment by sheetalkamat** [comment] 2018-07-19 23:42
@dbaeumer can you please check drop from #25811 to see if that improves your scenario. I believe this is better solution and should help in your case. In logs, i dont see much activity from the build any more but verifying on your end would be helpful. Thanks.

**Comment by dbaeumer** [comment] 2018-07-20 07:09
Self hosting now on that branch. Will let you know how it goes. Thanks for looking into this.

**Comment by sheetalkamat** [comment] 2018-07-23 23:00
@dbaeumer was wondering if you tried the drop from  #25811 and was it helpful.

**Comment by dbaeumer** [comment] 2018-07-24 08:31
I was using it for 4 days now and it does look better. It is OK for me to close the issue. If I see new problem I will open a new one.

**Closed** 2018-07-24 18:24 UTC
Labels: bug, typescript, upstream
