### ISSUE TITLE
markdown preview - layout breaks on font zoom

### ISSUE THREAD

**Issue by sinclairzx81** [Microsoft/vscode#17235] opened 2016-12-15 05:38 UTC
- VSCode Version: 1.8 release
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open markdown (*.md) document in editor.
2. View markdown in preview mode.
3. Press Ctrl + "+" to zoom.

When previewing markdown documents in vscode, zooming the font causes the markdown window to shrink. The window gets visibly smaller with each zoom level.

![issue](https://cloud.githubusercontent.com/assets/3048342/21212887/7cecc42c-c2f5-11e6-8d68-be76ec1ec4df.png)

Many Thanks

**Comment by kieferrm** [comment] 2016-12-16 01:19
Duplicate of #5745.

**Closed by kieferrm** 2016-12-16 01:19 UTC
