### ISSUE TITLE
Window snaps to top left corner when trying to maximize

### ISSUE THREAD

**Issue by wbradney** [Microsoft/vscode#359] opened 2015-11-20 15:54 UTC
It just docks top left and goes back to its original size...

**Comment by bpasero** [comment] 2015-11-20 20:50
@wbradney what OS? can you attach a screenshot

**Comment by wbradney** [comment] 2015-11-20 23:11
Windows 7. I'll try and grab a screenshot when I get back to that machine. This is new behaviour after I updated vscode today. I can manually resize the window, and minimize it, but the maximize/restore button always shows as maximized regardless of the window size/position. When I click maximize, the window briefly fills the screen, the goes back to original size (and sticks top left).

Sent from my Windows Phone
________________________________

**Comment by bpasero** [comment] 2015-12-22 11:05
Please reopen if still reproduces.

**Comment by wbradney** [comment] 2015-12-22 14:17
I've actually moved to Windows 10, where this does not reproduce, so I'm happy to leave this closed.

**Comment by nhymxu** [comment] 2016-05-28 06:25
I'm using Windows 10, and I get same error.

How to fix this?

**Comment by bpasero** [comment] 2016-05-28 06:32
@nhymxu which version of code?

**Comment by nhymxu** [comment] 2016-05-28 08:58
@bpasero v1.1.1
Lastest version download from homepage.

**Comment by bpasero** [comment] 2016-05-28 10:55
@nhymxu can you attach a video how this looks like? is this standard windows 10 or insiders?

**Comment by nhymxu** [comment] 2016-05-28 11:30
@bpasero 
After double click to window title. VS Code change to full screen size, and auto resize to normal size, move window to top left.

I'm using standard Windows 10 v1511 build 10586.218
Not install KB3156421 because auto rollback this update.

[Demo Video](https://www.youtube.com/watch?v=U1r-pUHR1F4)

**Comment by bpasero** [comment] 2016-05-28 12:46
Thanks, I would think this is rather an issue with Electron (our UI framework) than Code.

**Comment by nhymxu** [comment] 2016-05-28 12:49
same error from Atom https://github.com/atom/atom/issues/10720

**Comment by bpasero** [comment] 2016-05-28 12:50
![editors](https://cloud.githubusercontent.com/assets/900690/15627410/6545b0aa-24e3-11e6-9c5d-f248c43e65c4.gif)

Since this works fine for me on Windows 10 and seems to work fine for most Windows 10 users, I am asking for more info on your system what this could be and if maybe other apps show the same issue.

**Comment by bpasero** [comment] 2016-05-28 12:50
Ok, so it is an upstream issue then.

**Comment by nhymxu** [comment] 2016-05-28 12:51
I try install Atom and get same error. 
I think my computer error with electron.

**Comment by nhymxu** [comment] 2016-05-28 13:10
temporary fix with create shortcut and config with maximize state.

**Comment by nhymxu** [comment] 2016-05-28 13:26
After try run VS code with "Run as admin".
Everything is fine!

**Comment by bpasero** [comment] 2016-09-18 06:59
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Closed by bpasero** 2016-09-18 06:59 UTC
Labels: bug, needs more info, upstream
