### ISSUE TITLE
Repainting in Editor and Preview Pane

### ISSUE THREAD

**Issue by rfuehrer** [microsoft/vscode#105156] opened 2020-08-21 14:52 UTC
Issue Type: <b>Bug</b>

Repainting in Editor and Preview pane

File affected: 
https://github.com/generaliinformatik/fah-red-lions/blob/master/README.md

Demonstration of behaviour: 
https://imgur.com/a/vSig9ut

When entering text in the Editor window, the display of the Editor and the Preview is redrawn each time text is entered and the visible area in both windows is moved. Please go to any position in the document and start typing any text. the view changes with every keystroke

Provoke the behavior:

The problem is caused by the line 

> img src="https://github.com/generaliinformatik/fah-red-lions/blob/master/images/dashboard.png?raw=true" alt="dashboard" width="100%"/>

If you change text below this line, the behavior will happen. Ideally, the displayed image in the preview is outside the visible area, so that the behavior occurs and the repainting is performed.

If you remove the above line, the display will appear without the described behavior when the text is changed.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|24.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|3.4.3

</details>

**Comment by mjbvz** [comment] 2020-08-24 15:26
Duplicate of #89930

**Closed by mjbvz** 2020-08-24 15:26 UTC
Labels: markdown, new release
