### ISSUE TITLE
`editor.formatOnSaveMode` does not appear to function

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#105800] opened 2020-09-01 08:53 UTC
Testing #105733

* Create a file `file.ts`
* Paste the following contents:
```
class A {
private foo(): number {
return 5;
}
}
```
* Close the file and reopen vscode
* Configure `"editor.formatOnSaveMode": "modifications"`
* Configure `"editor.formatOnSave": true`
* Paste the following contents in the file:
```
class B {
private foo(): number {
return 5;
}
}
```
* Save file via cmd+s to get the format on save running
* Observe that `class A` has been formatted:

![Kapture 2020-09-01 at 10 52 28](https://user-images.githubusercontent.com/5047891/91829097-4b628a80-ec41-11ea-9880-276be64a23a5.gif)

**Comment by jrieken** [comment] 2020-09-01 08:55
@alexdima modifications are based on SCM diff information. Your file appears as untracked and no quick diff markers show. Do you really have only those lines "SCM modified"?

**Comment by misolori** [comment] 2020-09-01 21:46
I can also repo, I have the same settings from above (`"editor.formatOnSaveMode": "modifications",` and `"editor.formatOnSave": true`) and I expect only to have line 10 formatted but then other lines get formatted.

![Kapture 2020-09-01 at 14 45 01](https://user-images.githubusercontent.com/35271042/91909273-bfad2600-ec61-11ea-870d-681c7c8aa4ea.gif)

**Comment by jrieken** [comment] 2020-09-02 07:45
@misolori you are on the right path. Modifications are being formatted but my assumption is that I pass  the range 10,1-11,1 to the html formatter and that it then over-eagerly formats the whole statement of line 11.

@alexdima ping for clarification

**Comment by alexdima** [comment] 2020-09-02 07:51
@jrieken I see, I misunderstood the feature. Maybe the setting could make it more clear that this is only about SCM diff ranges. I thought that the file is read from disk just before saving and a diff is computed with the state on disk. It was not clear to me that the diff is computed with the state of the index.

**Comment by jrieken** [comment] 2020-09-02 08:00
The setting says "requires source control"... I actually like your assumption of how it should/could work and that's maybe something for the future. So, maybe we find an alternative for "modified" that expresses it's "source control modified" and then, in the future, we have another option that says "modified in session". Ideas?

<img width="423" alt="Screenshot 2020-09-02 at 09 58 47" src="https://user-images.githubusercontent.com/1794099/91955034-e66f6900-ed02-11ea-808d-abfca131420a.png">

**Comment by alexdima** [comment] 2020-09-02 08:54
:+1: Sorry about my confusion. I didn't use the settings ui and this was my experience:

![image](https://user-images.githubusercontent.com/5047891/91960847-af04ba80-ed0a-11ea-801f-9e0f5b25874a.png)

**Comment by jrieken** [comment] 2020-09-02 09:43
Yeah, the suggestion details widget would show this... Still open for suggestion for a better name and maybe give this a short test run after all

@misolori can you share the file and what formatter your are using? I wasn't able to reproduce what you see.

**Comment by misolori** [comment] 2020-09-02 15:16
So it looks like that may have been an issue with my formatter (Prettier). Disabled that and used the default one and got it working for JS files. 

However, I'm not seeing this work reliably with JSON files. Some format commands don't work (`Format Selection` and `Format Modified Lines`) but `Format Document` does work 🤷‍♂️:

![Kapture 2020-09-02 at 08 13 16](https://user-images.githubusercontent.com/35271042/92001999-398def80-ecf4-11ea-8b11-3d5d6d603292.gif)

**Comment by jrieken** [comment] 2020-09-02 15:21
Yeah, the secret of "format modified" is that it does "format selection" where the selection isn't visible and consists of the modified ranges. Adding @aeschli who did the JSON formatter - it might be fit for arbitrary range formattings

**Comment by misolori** [comment] 2020-09-02 15:27
Seeing similar things with the HTML formatter. This works fine in other JS/TS files though. Hopefully these bugs can get fixed and are not by design.

**Comment by jrieken** [comment] 2020-09-03 09:03
I have created https://github.com/microsoft/vscode/issues/105998 to track selection formatting issues. Closing this as the @alexdima's confusion has been cleared

**Closed by jrieken** 2020-09-03 09:03 UTC
Labels: formatting, needs more info
