### ISSUE TITLE
Keyboard layout ignored

### ISSUE THREAD

**Issue by leesdolphin** [Microsoft/vscode#48336] opened 2018-04-22 05:11 UTC
Issue Type: <b>Bug</b>

I have a dual-keyboard layout set up where I use Dvorak at work and QWERTY at home; When VS Code starts up it always picks Dvorak despite QWERTY being the currently selected layout. This makes VS Code impossible to use as there is no feedback and it completely ruins the experience.

Additionally the documentation is not very useful, and is to be honest quite dense.

Oh well, at least I don't cut code that often; because that'd drive me mad.

VS Code version: Code - OSS 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-13T19:17:59Z)
OS version: Linux x64 4.15.17-64.current

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2646)|
|Load (avg)|2, 2, 1|
|Memory (System)|15.44GB (0.97GB free)|
|Process Argv|/usr/share/vscode/code-oss|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-rust|kal|0.4.2
atom-keybindings|ms-|3.0.4

</details>

**Comment by alexandrudima** [comment] 2018-04-23 07:46
Please see https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings 

![image](https://user-images.githubusercontent.com/5047891/39113190-1b580d28-46db-11e8-8822-ef31b6db2caa.png)

Duplicate of #24166

**Closed by alexandrudima** 2018-04-23 07:46 UTC
Labels: keyboard-layout, linux
