### ISSUE TITLE
Unused decoration drawing issue

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52585] opened 2018-06-21 10:32 UTC
Issue Type: <b>Bug</b>

`import *` is shown as `import **` after pressing space after the `*`. It disappears when the line is fully typed.

![unused-drawing-issue](https://user-images.githubusercontent.com/9205389/41713952-05a196e6-754f-11e8-9901-8b8500ed4470.gif)

VS Code version: code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|/Users/chrmarti/Development/repos/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-processes|and|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.0
Go|ms-|0.6.83
vscode-docker|Pet|0.0.27

</details>

**Comment by alexandrudima** [comment] 2018-06-21 10:34
Duplicate of #52196

**Closed by alexandrudima** 2018-06-21 10:34 UTC
