### ISSUE TITLE
TS Server fatal error:  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by michel-grenier** [microsoft/vscode#97829] opened 2020-05-14 17:20 UTC
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. Simply open a docker having the latest Docker Desktop for Windows (2.3.0.2) installed

**TS Server Error Stack**
```
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:19148:110)
    at Object.parseJsonText (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:18972:26)
    at Object.parseJsonText (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:18793:23)
    at ProjectService.loadConfiguredProject (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:142258:33)
    at ProjectService.createAndLoadConfiguredProject (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:142240:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:142245:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:143101:44)
    at /home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/home/dev/.vscode-server/bin/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by michel-grenier** [comment] 2020-05-14 17:30
Restarting Docker is a potential workaround.  I'm now able to open the dockers I've used for a long time now and were working correctly with the previous versions of Docker.

**Comment by mjbvz** [comment] 2020-05-14 18:46
Duplicate of microsoft/TypeScript#30005

**Closed by mjbvz** 2020-05-14 18:46 UTC
