### ISSUE TITLE
Extension Host Crashing when launching from macOS GUI (Catalina 10.15.6 (19G73))

### ISSUE THREAD

**Issue by foorenxiang** [microsoft/vscode#103057] opened 2020-07-22 00:31 UTC
Issue Type: <b>Bug</b>

Extension Hosts crashing on start if launching Code by macOS GUI. This occurs even after performing a complete uninstall and clean installation again, with no extensions installed.

Upon adding Code to path, launching Code by macOS Terminal doesn't result in Extension Host crashing, even after extensions are installed.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-use-strict|cri|1.0.1
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.18.0
q|lws|0.0.4
vscode-docker|ms-|1.3.1
python|ms-|2020.7.94776
vscode-ai|ms-|0.6.13
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
azure-account|ms-|0.8.11
sublime-keybindings|ms-|4.0.7
vsonline|ms-|1.0.2527
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-07-22 07:33
@foorenxiang Do you by any chance have `DYLD_LIBRARY_PATH` configured in your `~/.zshrc`?

what does `otool -L /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib` print ?

**Comment by foorenxiang** [comment] 2020-07-22 07:37
Hi, apparently I don't have a ~/.zshrc.

Running `cat  ~/.zshrc` returns `cat: /Users/foorx/.zshrc: No such file or directory`

Running `otool -L /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib` returns `/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib:
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf-lite.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer (compatibility version 1.0.0, current version 274.24.9)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libTelephonyUtilDynamic.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)`

**Comment by alexdima** [comment] 2020-07-22 08:13
@deepak1556 I see again that `libprotobuf` is in there. Do you think this is a duplicate of #100118?

**Comment by deepak1556** [comment] 2020-07-22 09:02
I think this might be a different issue considering the crash only happens when launching from the finder/dock.

@foorenxiang does the devtools print ay error when the extension host is terminated ? 

Can you also follow the instructions at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports to get a symbolicated trace. Thanks!

**Comment by foorenxiang** [comment] 2020-07-22 10:32
When launching from finder/dock, the devtools indicate the following errors
<img width="1114" alt="Screenshot 2020-07-22 at 6 28 21 PM" src="https://user-images.githubusercontent.com/7560259/88166217-8092ba80-cc49-11ea-9122-4510dc6ab9ff.png">

I can't seem to generate the dmp file with the symbolicated trace steps, as Code doesn't crash extension host when executed from Terminal...

I do suspect it's related to  #100118, as it may have occurred after running `brew upgrade yarn`

**Comment by deepak1556** [comment] 2020-07-23 04:45
@foorenxiang is that the complete output from the devtools ? if not, can you paste the full output from the devtools.

**Comment by foorenxiang** [comment] 2020-07-23 04:49
@deepak1556 

just restarted VS code from GUI, this is the complete output:

`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4275 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
_onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4275
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Extension host terminated unexpectedly.
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4616 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4616 dyld: Symbol not found: __cg_jpeg_resync_to_restart  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO  Expected in: /usr/local/lib/libJPEG.dylib in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Error: [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4279 [tht13.python]: 'configuration.jsonValidation.url' must be an absolute URL or start with './'  to reference schemas located in the extension.
_logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4279
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Cannot read property 'start' of null: TypeError: Cannot read property 'start' of null
    at V._startLocalExtensionHost (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5004:712)
    at V._scanAndHandleExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5003:686)
    at async V._initialize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4273:805)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/foorx/.vscode/extensions/tht13.python-0.2.3/syntaxes/python.tmLanguage
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140 Overwriting grammar scope name to file mapping for scope source.regexp.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicRegExp.tmLanguage.json.
New grammar file: file:///Users/foorx/.vscode/extensions/tht13.python-0.2.3/syntaxes/Regular%20Expressions%20%28Python%29.tmLanguage
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Error: [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Error: [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
configuration.ts:112 [Violation] 'setTimeout' handler took 58ms
[Violation] Forced reflow while executing JavaScript took 55ms
`

**Comment by deepak1556** [comment] 2020-07-23 04:54
Interesting error

```
dyld: Symbol not found: __cg_jpeg_resync_to_restart Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO Expected in: /usr/local/lib/libJPEG.dylib in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

can you try to remove `/usr/local/lib/libJPEG.dylib` from `DYLD_LIBRARY_PATH`

**Comment by foorenxiang** [comment] 2020-07-23 12:22
@deepak1556 I've moved /usr/local/lib/libJPEG.dylib out of the DYLD_LIBRARY_PATH, extension host still crashes when launched from GUI.

Here's the updated full output from devtools:

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4279 [tht13.python]: 'configuration.jsonValidation.url' must be an absolute URL or start with './'  to reference schemas located in the extension.
_logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4279
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4275 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
_onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4275
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Extension host terminated unexpectedly.
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4616 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4616 dyld: Symbol not found: __cg_TIFFClientOpen  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO  Expected in: /usr/local/lib/libTIFF.dylib in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/foorx/.vscode/extensions/tht13.python-0.2.3/syntaxes/python.tmLanguage
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140 Overwriting grammar scope name to file mapping for scope source.regexp.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicRegExp.tmLanguage.json.
New grammar file: file:///Users/foorx/.vscode/extensions/tht13.python-0.2.3/syntaxes/Regular%20Expressions%20%28Python%29.tmLanguage
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5140
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Error: [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151 IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1151
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR Error: [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
workbench.contribution.ts:13 [Violation] 'requestIdleCallback' handler took 53ms
configuration.ts:112 [Violation] 'setTimeout' handler took 69ms

**Comment by deepak1556** [comment] 2020-07-23 20:54
There is a new one

```
dyld: Symbol not found: __cg_TIFFClientOpen Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO Expected in: /usr/local/lib/libTIFF.dylib in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

can you make sure the `DYLD_LIBRARY_PATH` changes don't leak into vscode launch.

**Comment by foorenxiang** [comment] 2020-07-24 02:01
@deepak1556 Nice, moving out both `/usr/local/lib/libTIFF.dylib` and `/usr/local/lib/libJPEG.dylib` fixed the issue. Extension Host no longer crashes when launching from GUI. 

I'm not sure if other applications/services on my mac will be using those 2 files though, not comfortable with moving them out for now :/ . But I guess that will have to be the workaround for now. Thanks!

**Comment by deepak1556** [comment] 2020-07-24 03:35
Thanks! closing this issue.

**Closed by deepak1556** 2020-07-24 03:35 UTC
Labels: extension-host, freeze-slow-crash-leak, mac

**Comment by po5i** [comment] 2020-08-20 22:12
For the record, I also faced this same issue with:
```
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib
```

removing that line from my .zshrc file solved this issue.
