### ISSUE TITLE
Terminal Ctrl+Click for node object containing url adds ', to urls which contain ?

### ISSUE THREAD

**Issue by akulmehta** [microsoft/vscode#94572] opened 2020-04-06 21:27 UTC
- VSCode Version: 1.43.2
- OS Version: Windows 10 (10.0.17763)
- Node.js: 12.8.1

Steps to Reproduce:

1. Console.log with node an object which contains a url with `?` using Windows PowerShell
for e.g.
`
console.log(
  {
  linkText: 'DuckDuck Go: my query',
  href: 'https://duckduckgo.com/?q=myquery&t=h_&ia=web',
  parentCell: 3
  },
  {
    linkText: 'DuckDuck Go',
    href: 'https://duckduckgo.com/',
    parentCell: 3
    }
);
`
2. The console will show the href, over which if the mouse hovers it will allow you to ctrl+click.
3. For the link `'https://duckduckgo.com/?q=myquery&t=h_&ia=web',` the url copied and opened in the browser will also contain `',`.
While in the case of duckduckgo this is not a problem, for other urls it can produce 404 errors.
4. This seems to happen only with urls containing `?` in the url.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2020-04-06 21:58
Looks like duplicate of #21125 however pick more symbols than usual.

**Closed** 2020-04-06 23:28 UTC
Labels: *duplicate
