### ISSUE TITLE
Issue #7198 is closed but Im stillexperiencing the issue

### ISSUE THREAD

**Issue by siran** [Microsoft/vscode#47037] opened 2018-03-31 18:58 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Described in #7198

Does this issue occur when all extensions are disabled?: Yes

**Comment by siran** [comment] 2018-03-31 19:42
This is not a duplicate

**Comment by bpasero** [comment] 2018-04-01 06:39
Duplicate of https://github.com/Microsoft/vscode/issues/20876 https://github.com/Microsoft/vscode/issues/14298 https://github.com/Microsoft/vscode/issues/23107

**Closed by bpasero** 2018-04-01 06:39 UTC
Labels: extensions
