### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by yuguuk** [Microsoft/vscode#27985] opened 2017-06-03 22:57 UTC
- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)</code>
- Memory (System): <code>2.99GB (0.28GB free)</code>
- Memory (Process): <code>159.67MB working set (214.04MB peak, 132.84MB private, 36.66MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|2545|
|main|app.isReady => window.loadUrl()|565|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2559|
|renderer|require(workbench.main.js)|15235|
|renderer|create extension host => extensions onReady()|4681|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|25852|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make 
[cf8e_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1049999/cf8e_main.cpuprofile.txt)
sure to **attach** these files: :warn
[cf8e_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1050000/cf8e_renderer.cpuprofile.txt)
ing:
-`C:\Users\yuguu\cf8e_main.cpuprofile.txt`
-`C:\Users\yuguu\cf8e_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-06-09 10:50
Thanks, we could see that is because of a delayed app ready event. Closing as dupe of #22087

**Closed by jrieken** 2017-06-09 10:50 UTC
Labels: insiders, perf-profile
