### ISSUE TITLE
Switch theme base on file type

### ISSUE THREAD

**Issue by Vxider** [Microsoft/vscode#45939] opened 2018-03-16 03:16 UTC
Can vscode automatically switch `workbench.colorTheme` based on file type?  I am using `monokai-chacoral(HC)` when I am coding,  but `monokai-chacoral(HC)` is not support `markdown`, so I need to switch to another theme.

**Comment by aeschli** [comment] 2018-03-16 08:55
duplicate of #20652

**Closed by aeschli** 2018-03-16 08:55 UTC
Labels: themes
