### ISSUE TITLE
Touchpad Gesture

### ISSUE THREAD

**Issue by biku1998** [Microsoft/vscode#48112] opened 2018-04-18 09:10 UTC
Issue Type: <b>Bug</b>

**TouchPad not working properly , gesture problem in scrolling.**

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|11.91GB (7.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.5.1
vscode-eslint|dba|1.4.8
vscode-babel-coloring|dza|0.0.4
code-runner|for|0.9.3
java|red|0.23.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by bpasero** [comment] 2018-04-18 16:54
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-04-18 16:54 UTC
Labels: trackpad/scroll
