### ISSUE TITLE
Tasks execution adds a '<' in the line's end, renders it useless. 

### ISSUE THREAD

**Issue by nukegold** [Microsoft/vscode#30634] opened 2017-07-13 16:40 UTC
Note: I'm using Bash as my default terminal
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.wordWrap": "off",
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 5000,
    "editor.formatOnSave": true,
    "window.zoomLevel": 0
}

---

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-angular2-component-generator|dba|0.0.3
githistory|don|0.2.1
vscode-generate-getter-setter|DSK|0.4.2
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
Angular2|joh|2.3.3
node-module-intellisense|lei|1.3.0
dotenv|mik|1.0.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.6
vscode-docker|Pet|0.0.16
higlight-matching-tag|vin|0.1.1

---

Steps to Reproduce:

1.Run any Task, e.g. npm: run start
2.In the terminal see:
> Executing task: npm run start <

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Nuke\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@4.2.0 C:\Users\Nuke\AppData\Roaming\npm\node_modules\npm

Terminal will be reused by tasks, press any key to close it.

Reproduces without extensions: Yes/No

**Comment by ciwchris** [comment] 2017-07-14 21:26
I experience the same behavior when trying to build .Net Core. Zsh is my default shell and I'm on Arch Linux.

> 4.11.9-1-ARCH

VS Code version info:

> Version 1.14.1
> Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
> Date 2017-07-13T19:12:01.887Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

Terminal output:

> \> Executing task: dotnet <
> 
> Usage: dotnet [options]
> Usage: dotnet [path-to-application]
> 
> Options:
>   -h|--help            Display help.
>   --version         Display version.
> 
> path-to-application:
>   The path to an application .dll file to execute.
> The terminal process terminated with exit code: 129
> 
> Terminal will be reused by tasks, press any key to close it.
> 

Task.json

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "dotnet",
            "type": "shell",
            "group": "build",
            "presentation": {
                "reveal": "always"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by yrtimiD** [comment] 2017-07-25 17:48
@nukegold, for me all started working when I stopped using bash.
terminal still shows: > Executing task: blablabla <
so, probably, final "<" isn't actually added to the command.

**Comment by dbaeumer** [comment] 2017-08-02 08:46
The message like `> Executing task: ... <` is a pure output message to let the user know which task is executed. It is not sent that way to the underlying terminal. So there must be another issue when executing this in a git bash environment.

**Comment by scorchpt** [comment] 2017-08-02 08:56
I have the same issue on Windows 10, using powershell. It seems executing the same command manually works, though.

**Comment by dbaeumer** [comment] 2017-08-02 10:31
@scorchpt this is really strange. Can you provide some steps to reproduce ?

**Comment by scorchpt** [comment] 2017-08-02 12:09
Sure. It happens in every project I've tried, and there's nothing special, honestly. My **tsconfig.json**:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "sourceMap": true,
        "outDir": "lib/"
    },
    "include": [
        "./src/**/*"
    ]
}
```

And my **tasks.json** (generated automatically):
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Running `Ctrl+Shift+B` yields:
> error TS5042: Option 'project' cannot be mixed with source files on a command line.

Running the command between the `> tsc ... <` compiles just fine.

**Comment by dbaeumer** [comment] 2017-08-03 11:04
@scorchpt I can't reproduce this using Windows, PowerShell and your described setup. Can you provide me with a repository that I can clone that shows the behavior ?

![cast](https://user-images.githubusercontent.com/1931590/28919064-21b6e7b0-784c-11e7-8515-a479f69f6d59.gif)

**Comment by nukegold** [comment] 2017-08-03 11:24
If it helps, I use GIT Bash. In my settings:
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

**Comment by dbaeumer** [comment] 2017-08-03 11:43
The problem with git bash and Linux Subsystem Bash is a dup of https://github.com/Microsoft/vscode/issues/28036.

**Comment by dbaeumer** [comment] 2017-08-03 11:44
Moving to August since the bash problem is covered by https://github.com/Microsoft/vscode/issues/28036 and the PowerShell issue can't be reproduce.

**Comment by dbaeumer** [comment] 2017-08-03 11:45
The problem with git bash is that the args are not passed correctly hence it looks like executing the command fails.

**Comment by dbaeumer** [comment] 2017-08-28 13:25
I fixed the problem with bash (both Git and WSL). Since I can't reproduce this in PowerShell I close as dup if #28036. Please ping if you still see this on other shells than bash under Windows.

**Closed by dbaeumer** 2017-08-28 13:25 UTC
Labels: bug, tasks
