### ISSUE TITLE
[Debugger] VS Code no longer rebinds breakpoints on save file

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#21383] opened 2017-02-24 18:04 UTC
- VSCode Version:
```
Version 1.10.0-insider
Commit 25c55638340197fc9c8767aba9d32a0c29ccf68a
Date 2017-02-21T07:10:22.174Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version: Windows 10

Steps to Reproduce:

1. Begin debugging (I am using the C# debugger against a .NET Core application)
2. Stop at a breakpoint
3. While stopped, alter the file (such as add a line break) and save the file

Expected: In the past, Code would send SetBreakpoints command when the file was saved.

Actual: Code no longer sends SetBreakpoints on file saved.

The C# debugger supports matching source to the debugged binary exactly using checksums. If the file on disk is saved we expect to rebind breakpoints so that we can send failure messages. This used to be the behavior in code but in no longer does this.

**Comment by chuckries** [comment] 2017-02-24 18:05
@weinand @isidorn

**Comment by isidorn** [comment] 2017-02-27 10:49
@chuckries VSCode does not send breakpoints while a file is dirty, once a file gets saved vscode will send breakpoints to the adapter if there are some new breakpoints(or some got removed) in that file. If the breakpoints did not change in a file and a file gets saved VS Code will not send anything. It is up to the adapter to track that.

This has not changed in the last couple of VSCode releases. VSCode was always behaving like this AFAIK.
However if this does not work for debug adapter then we can revisit this, thus assigning to march for discussion

**Comment by isidorn** [comment] 2017-02-28 15:25
@chuckries @weinand let me know how you think VS Code should behave with regards to this. I explained the current behavior in my comment above

**Comment by chuckries** [comment] 2017-03-01 05:48
We had thought that VS Code would rebind breakpoints on file save, so we prefer that behavior. If that's not what you want than we can adjust.

**Comment by isidorn** [comment] 2017-03-10 14:32
Since I did not recieve any strong feedback on this I propose that VSCode still behaves like it is and that you handle this on your adapter side.
Thus closing as designed

**Closed by isidorn** 2017-03-10 14:32 UTC
Labels: debug, needs more info
