### ISSUE TITLE
VS Code 1.64.0 broke support for moving the Panel to the right side

### ISSUE THREAD

**Issue by adam-arold** [microsoft/vscode#142120] opened 2022-02-03 21:40 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Windows 10

Steps to Reproduce:

1. Upgrade VS Code to 1.64.0
2. You're done

The problem is that with the latest update there is no longer an option when I right-click on the "Panel" to move it to the right. There is a side panel instead, but the side panel has no maximize feature so I can no longer have my terminal on the right-hand side and toggle between hidden, visible, and maximized. 

**This update broke this functionality**.

If I look for the command from the menu I get the 

```
Moving the panel with this command has been deprecated in favor of the "Move Views From Panel To Side Panel" and "Move Views From Side Panel To Panel" commands.
```

message and it moves **all my views** the side panel instead.

Why are you deprecating things **before adding support for things that they were able to do**??

**Comment by gjsjohnmurray** [comment] 2022-02-03 22:01
See also #142075

**Comment by adam-arold** [comment] 2022-02-03 22:15
@gjsjohnmurray who approves these breaking changes? I gotta know.

**Comment by sbatten** [comment] 2022-02-04 00:26
dupe of #142075 #141569

**Closed by sbatten** 2022-02-04 00:26 UTC
Labels: new release
