### ISSUE TITLE
mini-map highlight show only when hover, it should visible all the time

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#21914] opened 2017-03-03 17:50 UTC
@alexandrudima
-------------------
![1](https://cloud.githubusercontent.com/assets/17777237/23562400/f0f10c7e-004a-11e7-9a3a-baf81b6e2e98.JPG)
![2](https://cloud.githubusercontent.com/assets/17777237/23562404/f2a87bc4-004a-11e7-8c3e-bbd1608a6a68.JPG)

**Comment by Tekbr** [comment] 2017-03-04 00:16
Duplicate of #21823 , no?

**Closed** 2017-03-05 18:37 UTC
