### ISSUE TITLE
VS Code does not warn/report when file behind loaded buffer is changed on disk

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#7198] opened 2016-06-03 19:01 UTC
- VSCode Version: 1.1.1 (1.1.1)
- OS Version: OSX 10.11.5 (15F34)

Steps to Reproduce:

1. Edit file in VS code
2. Open file in a different editor
3. Edit and save in different editor
4. Go back to code in VS file

### Expected
VS Code prompts me with "File has been changed on disk, do you wish to reload the file?"

### Actual
VS Code does not give any indication that the file on disk is different than whats in the editor.

**Comment by bpasero** [comment] 2016-06-04 06:10
@Sequoia VS Code should update the file in place when it changes on disk, we do not prompt however. Does this happen with a file opened from a workspace (folder) or a file outside of the workspace? Is it reproducible always?

**Comment by bpasero** [comment] 2016-06-13 05:13
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-06-13 05:13 UTC
Labels: needs more info

**Comment by HCKgit** [comment] 2016-11-09 19:13
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393 (IMac running Parallels 11 & Win10)
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.0|
|vscode-great-icons|emmanuelbeziat|1.1.22|
|Theme-Twilight|gerane|0.0.2|
|henkes-theme|henriiik|0.3.0|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|createGUID|nwallace|0.0.2|
|Spell|seanmcbreen|0.8.6|
|harbour|ekon|0.0.1|

---

Steps to Reproduce:
1. Open file in VSCode & Notepad++ and load the same file.
2. Edit the file in Notepad++
3. Switch focus to VSCode and note that file is not changed if it is in focus. 

In VSCode, switch focus to another file (tab) and than back again and notice change has registered.

Basically, the refresh only happens if the file does not have focus in the editor.   This means, the file could change on disk somehow, and if the file is open and has focus in VSCode, the view will be stale, and not reflect the latest.  

If you try to re-save the file, it will not do anything as the file in the editor has not changed. The file on disk will remain the same, and will still be newer than the stale VSCode editor view of the file.  

If you do then edit the stale file, and try and save it, thankfully there will be a nice message and buttons; a warning with a compare option allowing user to revert or force the save. This is very nice.  

The only issue is that you may be looking at a stale file if you do not refocus or revert if the disk changes.  It could lead to paranoid ritual of refocusing the view every-time you switch to use VSCode.  

If there is no change in VSCode and the file changes on disk, VSCode should just update the view to the latest without switching tabs / focus.

BIG POINT:
If there is a disk change to a file being edited in VSCode, then there should be a VSCode warning that the file changed, like notepad++, warning that you are in a possible conflict , would you like to revert.

Always problems with feet and bullets.  Git is a background fix for most of this trouble. :)  That is, if your team actually wants to use it ;)

**Comment by bpasero** [comment] 2016-11-10 05:44
That behaviour is definitely not intended, we do update a file if it changes on disk even when it is not focussed. The issue you describe rather implies that our file watcher somehow is missing file events in your case.

**Comment by ajbogh** [comment] 2017-03-06 20:31
I believe I'm seeing this issue as well on Ubuntu 16.04. Reproduction steps are to change a file in a git repository, save it, issue a `git reset --hard HEAD` command. Notice the file in VSCode doesn't change. The workaround is to close and reopen the file. Opening the VSCode Settings file and closing it also refreshed the file.

**Comment by ajbogh** [comment] 2017-03-11 09:31
Works with the build you provided using a different computer using Ubuntu 16.10. Will try with the previous computer again.

```
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

**Comment by lowiebenoot** [comment] 2017-10-26 11:57
I have the same issue.
I change some things to a file in VSCode. When I undo these things by using `git checkout` (so I actually do changes to the file externally), it's never reloaded in VSCode. When I close the file and reopen it, the changes are there.

**Comment by PhilRB** [comment] 2017-11-01 18:01
I have this issue too. It is kind of frustrating because changes won't appear in VS code and I continue working, when I try to save then it prompts me that the file on disk changed and I have to use the clunky VSCode merge tool.

Same steps as the original poster:

1. Open a file in VS code (in workspace, with no local changes made)
2. Make a change to the file in any other editor and save
3. Go back to VSCode

ACTUAL:
File has not reloaded automatically and there is no prompt.
If I switch to another tab and then back to the original file, the change HAS appeared, but only if I didn't make any edits on the local copy first.

EXPECTED: 
File reloads automatically, or prompts me to reload.

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:48.528Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
