### ISSUE TITLE
Snippets are not always on top of the context menu

### ISSUE THREAD

**Issue by valkanov** [Microsoft/vscode#8571] opened 2016-06-30 12:15 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. open JS file
2. type "for" to trigger the for loop snippet or "if" or just "fun" for function

The snippet is not on top and when the "tab" button is pressed, nothing happens.

![if](https://cloud.githubusercontent.com/assets/5782506/16487776/86a09dd0-3ed5-11e6-8ca6-c916521db2d3.PNG)
![function](https://cloud.githubusercontent.com/assets/5782506/16487777/86a2c5e2-3ed5-11e6-9098-a75edfbbe33c.PNG)
![for](https://cloud.githubusercontent.com/assets/5782506/16487778/86a650f4-3ed5-11e6-8083-79d8c3f443e6.PNG)

**Comment by joaomoreno** [comment] 2016-07-04 15:40
@aeschli What to do here? cc @jrieken

**Comment by jrieken** [comment] 2016-07-04 16:08
Add a setting - there is people that don't like snippets, there is people that want snippets more than anything.

**Comment by jrieken** [comment] 2016-07-04 16:09
Also see #2343

**Comment by emzero** [comment] 2016-07-09 03:38
Related issue: https://github.com/Microsoft/vscode/issues/6667

We already know there are people that want snippets on top of everything and other people that want them at the bottom. As I suggested in the related issue, I'm pretty sure the snippets lovers would we just fine if the snippets are shown on top only if the cursor is on a empty line and outside function parenthesis and object literal brackets.

**Comment by aeschli** [comment] 2016-07-14 20:58
duplicate of #9286

**Closed by aeschli** 2016-07-14 20:58 UTC
Labels: bug
