### ISSUE TITLE
[macOs] Key bindings not working anymore with non US layout

### ISSUE THREAD

**Issue by jremen** [microsoft/vscode#173267] opened 2023-02-03 09:13 UTC
Type: <b>Bug</b>

Change keyboard layout to other language (not US)
Try ie. Outdent/Indent lines (cmd-] and cmd-[) or Cmd+W to close tab

It doesn't work properly with latest update, key bindings are ignored

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|24.00GB (0.52GB free)|
|Process Argv|--crash-reporter-id 2d8bbc97-be1b-4299-a0e1-b2b76bf9d02d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|3.0.0
klipper-config|aer|0.1.6
increment-selection|alb|0.2.0
Bookmarks|ale|13.3.1
to|ami|0.0.11
vscode-json|and|1.5.2
change-color-format|bbu|1.2.0
unique-lines|bib|1.0.0
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
html-entities|chr|1.1.2
jsonpath-extract|dav|1.2.3
vscode-eslint|dba|2.2.6
vscode-notes|dio|1.1.0
es7-react-js-snippets|dsz|4.4.3
filter-lines|ear|1.0.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-diff|fab|1.4.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
selected-lines-count|gur|1.4.0
google-translate|han|1.2.7
beautify|Hoo|1.5.0
charactercount|j4n|0.1.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
vscode-gutter-preview|kis|0.30.0
wrapSelection|kon|0.10.0
ecdc|mit|1.8.0
vscode-filesize|mkx|3.1.0
nc-gcode|ML2|0.14.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
sublime-keybindings|ms-|4.0.10
vscode-react-native|msj|1.10.0
vetur|oct|0.36.1
material-icon-theme|PKi|4.23.1
vscode-statusbar-json-path|ric|2.0.0
LiveServer|rit|5.7.9
partial-diff|ryu|1.4.3
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
autoimport|ste|1.5.4
vscode-stylelint|sty|1.2.3
open-in-browser|tec|2.0.0
wordpress-toolbox|wor|1.3.15
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983

```

</details>

**Comment by niccolomineo** [comment] 2023-02-03 09:56
I can't change key bindings any more via the UI.

**Comment by alexdima** [comment] 2023-02-05 21:01
Duplicate of #173325

**Closed by alexdima** 2023-02-05 21:01 UTC
Labels: new release
