### ISSUE TITLE
copy pasted text breaks unnaturally

### ISSUE THREAD

**Issue by kenhan** [microsoft/vscode#82844] opened 2019-10-18 13:48 UTC
Issue Type: <b>Bug</b>

Hi,

I have markdown text file. When I copy either a portion or all of it, and then paste it to Pages / TextEdit / Notes / Mail in MacOS, the words break happen mid word, but not in an expected way. Is there a way to attach screen shot?

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (4.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.31.0
code-runner|for|0.9.14
python|ms-|2019.10.41019

</details>

**Comment by roblourens** [comment] 2019-10-18 15:48
Yeah if you take a screenshot you can drag or paste it into github to attach it to the issue. I think a screenshot would help.

**Comment by kenhan** [comment] 2019-10-18 18:06
<img width="622" alt="Screen Shot 2019-10-18 at 6 48 57 AM" src="https://user-images.githubusercontent.com/47984/67117279-24b97380-f197-11e9-8e47-f90bd1580d83.png">

See how the word breaks unnaturally in several places. First line "is" is broken up in the middle, third line "making" is broken up after "m", fourth line "infant" broken up after "inf" and etc.

**Comment by roblourens** [comment] 2019-10-19 01:05
And this is all one line in the actual vscode editor?

Are you sure that this isn't the destination app adding line breaks? It just looks like it's trying to wrap it to some column width.

Do you see it if you paste into another vscode document? Do you see it if you start with `--disable-extensions`?

**Comment by peterneely** [comment] 2019-10-22 17:37
I had this problem too. The "language support for java" extension was causing it. When I disabled it, no more drunken copy/paste. https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by kenhan** [comment] 2019-10-22 18:26
Thanks for the tip Peter. But I don't have any java extension installed. So I wonder what's going on.

**Comment by kenhan** [comment] 2019-10-22 18:29
In fact, I don't have any extensions installed. And I still have this problem.

**Comment by roblourens** [comment] 2019-10-24 02:30
And this is all one line in the actual vscode editor?

Are you sure that this isn't the destination app adding line breaks? It just looks like it's trying to wrap it to some column width. What if you paste it into another vscode editor?

**Comment by kenhan** [comment] 2019-10-24 12:59
Yes, all one line in viscode editor. When pasted into another viscode editor, the content displays as expected.
When pasted into MacOS Pages, Notes, TextEdit, Mellel, even in Vim running, the problem shown in the screen capture above shows up.
I really like viscode and want to keep using it, but if I can't resolve this soon, I will have to unfortunately move on. This is costing me too much time.

**Comment by kenhan** [comment] 2019-10-24 13:01
By the way, simple paste always shows the problem. But in some cases paste and match styles in the destination app **sometimes** clears it up, which leads me to think something other than a sequence of strings is being copied from vscode which some apps can strip while other apps can't. Mellel can fix it. So can Notes, sometimes. But not Pages, ever.

**Comment by roblourens** [comment] 2019-10-26 01:35
Can you try disabling this setting? `editor.copyWithSyntaxHighlighting`

**Comment by kenhan** [comment] 2019-10-26 14:00
> Can you try disabling this setting? `editor.copyWithSyntaxHighlighting`

That's it! With it turned off copy-paste now works as expected with no weird word break. With it on, the problem returns. With it off, problem gone again. Thanks for tracking this down for me!

**Comment by DanielRosenwasser** [comment] 2020-04-20 18:19
Is this related to #88178?

**Comment by rebornix** [comment] 2020-11-03 16:55
yes, it's a duplicate of https://github.com/microsoft/vscode/issues/88178. We went back and forth on breaking/non-breaking space but didn't seem to have a good solution for all. Let's discuss in that issue.

**Closed by rebornix** 2020-11-03 16:55 UTC
Labels: editor-clipboard, polish
