### ISSUE TITLE
Non-existent config variables do not resolve to empty strings

### ISSUE THREAD

**Issue by Jake-Carter** [microsoft/vscode#204889] opened 2024-02-10 03:13 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Ubuntu 22.04

## Issue

Attempting to resolve a configuration variable with `"${config:xxx}"` does not resolve to an empty string if the variable does not exist.  Instead, it returns the literal `"${config:xxx}"` string itself.

## Expected Behavior

A non-existent variable should resolve to an empty string.

## Context

This causes a major issue for projects that rely on a user-set config variable to set up a project's PATH/toolchain.  For example...

```json
{
    "terminal.integrated.env.linux": {
        "PATH":"${config:TOOLCHAIN_PATH}:${env:PATH}"
    },
}
```

... will completely break the terminal if `TOOLCHAIN_PATH` is not set.  (i.e. the PATH is completely broken, core utilities like `ls`, `mkdir`, `grep`, etc. are inaccessible)

## Steps to Reproduce:

1. `settings.json`:
```json
{
    "TEST_VARIABLE":"Hello!",

    "terminal.integrated.env.linux": {
        "TEST_ENV_VAR":"${config:TEST_VARIABLE}"
    }
}
```

2. Launch a terminal and `echo $TEST_ENV_VAR`

![image](https://github.com/microsoft/vscode/assets/38844790/3067837e-2d2d-4293-a982-b9f0fdf9b6d2)

3. Remove variable

```json
{
    // "TEST_VARIABLE":"Hello!",

    "terminal.integrated.env.linux": {
        "TEST_ENV_VAR":"${config:TEST_VARIABLE}"
    }
}
```

4. Re-launch a fresh terminal and `echo $TEST_ENV_VAR`

![image](https://github.com/microsoft/vscode/assets/38844790/66ad49fb-fdf0-4010-be97-9a8bf2bf879e)

**Comment by Jake-Carter** [comment] 2024-03-04 22:38
@Tyriar any opinion on this behavior?

**Comment by Tyriar** [comment] 2024-12-18 16:40
@alexr00 is this by design for the variable resolver? Is there an option to resolve non-existent variables to the empty string?

**Comment by alexr00** [comment] 2024-12-18 17:06
It is by design as it simply isn't recognized as something that should be replaced. There's been a request for fallback values for `env` variables before. Could be a dupe of that https://github.com/microsoft/vscode/issues/92854.

**Closed** 2024-12-19 19:15 UTC
Labels: bug, *duplicate, confirmation-pending, terminal-process
