### ISSUE TITLE
Hotkeys do not work

### ISSUE THREAD

**Issue by yalokin** [Microsoft/vscode#24579] opened 2017-04-12 07:53 UTC
If I start with the Russian language, hotkeys do not work
- VSCode Version: 1.11.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. To switch language in system to Russian
2. Start VS Code
3. To try hotkeys, for example ctrl+n
4. To switch language in system to English
5. To try hotkeys, for example ctrl+n

**Comment by alexandrudima** [comment] 2017-04-12 08:19
Duplicate of #24057. The latest insiders release already contains a fix.

**Closed by alexandrudima** 2017-04-12 08:19 UTC
