### ISSUE TITLE
Markdown internal links not render correctly

### ISSUE THREAD

**Issue by AndresOchoaS** [Microsoft/vscode#16887] opened 2016-12-08 02:51 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|azuretoolsforvscode|bradygaster|0.0.11|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|azure-iot-toolkit|formulahendry|0.0.6|
|mssql|ms-mssql|0.1.5|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|vscode-azureextensionpack|ms-vscode|0.0.3|
|azurerm-vscode-tools|msazurermtools|0.3.2|
|debugger-for-chrome|msjsdiag|2.3.2|
|debugger-for-edge|msjsdiag|0.4.1|
|vscode-docker|PeterJausovec|0.0.9|
|usql-vscode-ext|usqlextpublisher|0.1.9|
|vscode-react-native|vsmobile|0.2.3|

---

Steps to Reproduce:

1. Open a Markdown file with internal links.
2. When you open a internal link, vscode render this:
![2016-12-07 4](https://cloud.githubusercontent.com/assets/18619074/20995775/427f3e5c-bcc7-11e6-952b-11369f723216.png)
![2016-12-07 5](https://cloud.githubusercontent.com/assets/18619074/20995774/427b080a-bcc7-11e6-815e-0b84cec4e207.png)

**Comment by mjbvz** [comment] 2016-12-08 23:26
Closing as duplicate of #16337

The fix is already in insiders builds and will go out with VSCode 1.8.

Thanks

**Closed by mjbvz** 2016-12-08 23:26 UTC
Labels: duplicate
