### ISSUE TITLE
Using shebangs in TypeScript are generating errors.

### ISSUE THREAD

**Issue by Kurtz1993** [Microsoft/vscode#899] opened 2015-12-02 04:57 UTC
I'm working on a Node script using TypeScript and the editor is generating this annoying erros.
TS compiler is working fine, it compiles my script without problems :)

Here's a screenshot of the error.

Shebang is present at the top of the file:

#! /usr/bin/env node
![untitled](https://cloud.githubusercontent.com/assets/5412470/11522626/c20e1756-987e-11e5-84a7-4d70084d77df.png)

**Comment by alexandrudima** [comment] 2015-12-02 08:15
@Kurtz1993 What language appears in the bottom right corner?

I think the `#! /usr/bin/env node` first line drives VSCode to detect the file as a JavaScript file.

@bpasero I think this is a case where the first line match getting the highest priority is back-firing.

**Comment by bpasero** [comment] 2015-12-02 08:31
:frowning:

**Comment by Kurtz1993** [comment] 2015-12-02 13:17
@alexandrudima in fact, it's detecting the file as Javascript :worried:

Here's the full screenshot.
![capture](https://cloud.githubusercontent.com/assets/5412470/11531744/ac36fe66-98c4-11e5-81d7-0ef0677b7063.PNG)

**Comment by Kurtz1993** [comment] 2015-12-02 13:28
I tried just to put a new line at the top of the file and the editor is now detecting the file as TypeScript.
![screenshot 1](https://cloud.githubusercontent.com/assets/5412470/11531944/1f812fbc-98c6-11e5-85c6-45adaf55dd69.png)


But it's causing the compiler to complain.
![capture](https://cloud.githubusercontent.com/assets/5412470/11531958/30959af4-98c6-11e5-945d-9151d72c26fc.PNG)

**Comment by dbaeumer** [comment] 2015-12-02 15:09
@Kurtz1993  See https://github.com/Microsoft/TypeScript/issues/2749. shebang is only supported on the first line.

**Comment by dbaeumer** [comment] 2015-12-02 15:09
Assigning issue to @bpasero since the wrong detection has to be fixed in the workbench.

**Comment by Kurtz1993** [comment] 2015-12-02 15:13
Thank you for the aclaration @dbaeumer
So, it's just the shebang in the frist line causing the editor to treat the file as Javascript instead of TypeScript.

**Comment by bpasero** [comment] 2015-12-02 15:19
@Kurtz1993 yes, the workaround is to not use shebangs.

**Comment by bpasero** [comment] 2015-12-02 20:27
@alexandrudima I am open for ideas how to fix this. I don't have a straight forward idea in mind. What we actually want is that the TS contribution overrides the JS contribution but only in this specific case. It almost seems we have to introduce a weight property when contributing patterns for a language?

**Comment by vilic** [comment] 2016-03-02 02:58
Why is this bug still in backlog?

**Comment by bpasero** [comment] 2016-03-02 06:09
dupe of #2883

**Closed by bpasero** 2016-03-02 06:09 UTC
Labels: bug
