### ISSUE TITLE
Notebook diff gets corrupted after switching profiles

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#167642] opened 2022-11-29 22:38 UTC
Testing #167161

1. Open a diff of an `.github-issues` notebook
2. With the diff editor open, create a new blank profile (or switch to a profile that doesn't have the GitHub issues notebook extension installed)

**Bug**
The notebook diff view ends up Looking very strange and this error is printed in the developer tools:

```
ERR Missing viewType for 'git:/Users/matb/projects/vscode/.vscode/notebooks/my-endgame.github-issues?%7B%22path%22%3A%22%2FUsers%2Fmatb%2Fprojects%2Fvscode%2F.vscode%2Fnotebooks%2Fmy-endgame.github-issues%22%2C%22ref%22%3A%22~%22%7D': Error: Missing viewType for 'git:/Users/matb/projects/vscode/.vscode/notebooks/my-endgame.github-issues?%7B%22path%22%3A%22%2FUsers%2Fmatb%2Fprojects%2Fvscode%2F.vscode%2Fnotebooks%2Fmy-endgame.github-issues%22%2C%22ref%22%3A%22~%22%7D'
    at h.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2491:68033)
    at async De.provideTextContent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2491:71953)
    at async d.q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2480:63837)
    at async d.m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2480:62827)
    at async r.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:19:32028)
    at async g.createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2480:64463)
    at async U.lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2245:43956)
```

**Comment by sandy081** [comment] 2022-11-30 08:13
@rebornix When switching profile, I take down ext host and restart so that it starts with new set of extensions. Not sure if notebooks might be depending on something or not disposing stuff. Can you please investigate first from your side and let me know if there is anything that can be done from my side?

**Comment by rebornix** [comment] 2022-12-05 23:30
/duplicate of https://github.com/microsoft/vscode/issues/167644

**Closed by rebornix** 2022-12-05 23:30 UTC
Labels: bug
