### ISSUE TITLE
Outline View does not reflect edits when displaying notebook cells  in outline view

### ISSUE THREAD

**Issue by jj-github-jj** [microsoft/vscode#189643] opened 2023-08-04 13:52 UTC
Type: <b>Bug</b>

Turn on notebook cells in outline view
you should see all cells in outline view not just markdown now
Python cells show first line of cell in outline view
next change the first line of cell  and save notebook
the outline view does not reflect changes 
reload vs code window using ctrl shift p > reload window
Now the modified python cell will show correctly in outline view

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.22GB free)|
|Process Argv|--crash-reporter-id 19bc74b9-096c-402c-b95a-9eddc06322a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-select|chu|2.0.2
vscode-quick-select|dba|0.2.9
codespaces|Git|1.14.14
copilot|Git|1.100.306
copilot-chat|Git|0.6.0
restructuredtext|lex|189.3.0
playwright|ms-|1.0.15
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.15.12151010
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.6.0
vscode-react-native|msj|1.11.2
es7-react-js-snippets|rod|1.9.3
search|use|0.0.1
vscode-python-poetry|zes|0.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by rebornix** [comment] 2023-08-22 20:40
/duplicate of https://github.com/microsoft/vscode/issues/190631

**Closed by rebornix** 2023-08-22 20:40 UTC
