### ISSUE TITLE
Release notes appear on every window

### ISSUE THREAD

**Issue by brandondrew** [microsoft/vscode#90632] opened 2020-02-13 20:45 UTC
I would like to see the release notes when there's an update, because there are always useful additions that I want to know about, but currently VS Code:

1. regularly re-opens release notes that I have already read, 
2. opens release notes in EVERY SINGLE WINDOW.

![image](https://user-images.githubusercontent.com/9854/74476387-3a098a80-4e77-11ea-89aa-9de19b1cce08.png)

These have been happening for years.  Please fix them before I jump off a bridge! 😱 

There should never be any reason to automatically open them more than ONE time.  Perhaps consider using the OS notification system to send ONE notification.  If you can't do that, please open ONE window with the release notes, instead of one tab in every window.

**Comment by gjsjohnmurray** [comment] 2020-02-13 23:29
/needsMoreInfo does this reproduce if you run with all extensions disabled?

**Comment by brandondrew** [comment] 2020-02-14 01:21
Since some of the conditions to reproduce it (a new release) are outside of my control, and outside of my knowledge until I see the release notes, that's _very_ hard to answer.  

Are you trying to tell me that you do not have the release notes appear in _every single window_ when you reopen Visual Studio Code and there's a new release?  And that you never have them appear again after you've already read them?  Since I've seen this happen SO many times, I guessed it happened quite widely.

**Comment by bpasero** [comment] 2020-02-14 07:01
This seems to be triggered from update, moving to Joao.

**Comment by joaomoreno** [comment] 2020-02-14 09:03
@brandondrew Yes there is a known issue: when opening release notes, every window opens them. It's pretty dramatic in your case since you seem to have ~20 windows open.

But release notes should not appear twice, unless there's been a recovery update. There was one yesterday... so that might explain it?

**Comment by joaomoreno** [comment] 2020-02-14 09:53
I could swear this issue had been fixed in the past... and I was right.

@bpasero  This got broken by https://github.com/microsoft/vscode/commit/f0b99530c857c74bd0cfba6d0f835afc7a56a40f#diff-10b67ccbd65ac0e04fe13cd734b466f4L128.

**Closed** 2020-02-14 10:10 UTC
Labels: bug, install-update, release-notes

**Comment by brandondrew** [comment] 2020-02-14 15:45
Muito obrigado João!  👏🏻👏🏻👏🏻

**Comment by joaomoreno** [comment] 2020-02-15 09:04
De nada! Make sure you let us know when stuff annoys you. Sometimes it seems obvious that an issue would annoy everyone but sometimes it just doesn't. :+1:

**Comment by alexr00** [comment] 2020-02-27 16:53
@joaomoreno is there a good way to verify this? If not, I have already verified by code review.

**Comment by joaomoreno** [comment] 2020-02-28 07:34
Code review should be 🆗
