### ISSUE TITLE
Can't search extensions

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#57902] opened 2018-09-04 21:15 UTC
I tried to search extensions but always got `No extensions found`. Is there anything wrong with my vs code?

![image](https://user-images.githubusercontent.com/3355579/45058252-70b47080-b0db-11e8-8a18-ece9c8d4982e.png)

VS Code version:

![image](https://user-images.githubusercontent.com/3355579/45058239-5d090a00-b0db-11e8-9654-88636c5ab375.png)

OS version:

![image](https://user-images.githubusercontent.com/3355579/45058231-55e1fc00-b0db-11e8-973a-5d6fbae3c6b5.png)

**Comment by mjbvz** [comment] 2018-09-04 21:27
Duplicate of #57851

**Closed by mjbvz** 2018-09-04 21:27 UTC
Labels: extensions
