### ISSUE TITLE
Folding not working properly.

### ISSUE THREAD

**Issue by fskorzec** [Microsoft/vscode#25074] opened 2017-04-20 11:15 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (d8fe52b1789a398a7319346b8923d330f7ab1016, 2017-04-19T07:19:29.296Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. With this sample of code
```typescript
function testFolding() {
  const test: string = "";

  switch(test) {
    case "A":
      /** */
    break;
    case "B":
      /** */
    break;
    case "C":
      /** */
    break;
  }
}
```
2. When I try to Fold case "A", it's working, but I cannot Fold case B nor C.
3. If I fold case "B" I cannot do it with C but I can with A, and in that case I cannot unfold case B
3. If I fold case C I can fold then B and then A but cannot unfold B and C anymore

**Comment by mjbvz** [comment] 2017-04-20 19:59
This sounds like a duplicate of #25013

Please try out the latest insiders built and let me know if you still see this issue

**Closed by mjbvz** 2017-04-20 19:59 UTC
Labels: duplicate, editor-folding

**Comment by fskorzec** [comment] 2017-04-20 21:17
You're right, working on the latest insiders :-)
