### ISSUE TITLE
Cannot auto-complete path in Save As panel

### ISSUE THREAD

**Issue by mcrampon** [microsoft/vscode#231835] opened 2024-10-21 13:40 UTC
Type: <b>Bug</b>

Create a new file, press `CTRL+S`, try to save in a deeply nested file structure.

## Expected

I can type and auto complete the name of the directories as I progress down the tree

## Actual

Everytime I add a directory to the path I want to save to, the temporary file name gets appended, making the auto-completion not work anymore.

## Video demonstrating the issue

https://github.com/user-attachments/assets/f53fd934-45d9-4a55-bdca-0cf6a68624d4

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (38.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 0)|
|Memory (System)|31.31GB (20.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 0)|
|Memory (System)|31.31GB (20.80GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
auto-close-tag|for|0.5.15
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.4
multi-command|ryu|1.6.0
scala|sca|0.5.8
slim|sia|0.1.2
svg-preview|Sim|2.8.3
haml|vay|1.0.1
json-tools|eri|1.0.2
copilot|Git|1.241.0
copilot-chat|Git|0.21.2
selected-lines-count|gur|1.4.0
terraform|has|2.33.0
rails-rspec-file-toggle|mal|0.0.3
vscode-yaml-sort|Pas|6.5.17
sass-indented|syl|1.8.31
simple-ruby-erb|vor|0.2.1
volar|Vue|2.1.6
gitblame|wad|11.1.1
change-case|wma|1.0.0

</details>

**Comment by alexr00** [comment] 2024-10-22 14:25
Duplicate of https://github.com/microsoft/vscode/issues/89751

**Closed** 2024-10-22 14:24 UTC
Labels: *as-designed
