### ISSUE TITLE
Unoptimized file diff in jupyter notebooks

### ISSUE THREAD

**Issue by bleamer** [microsoft/vscode#144578] opened 2022-03-07 12:01 UTC
Issue Type: <b>Bug</b>

File comparison between version on VSCode for Jupyter notebook can be improved. 
Steps to reproduce:

- Modify a cell in Jupyter notebook
- Add 2-3 non-empty new cells below the modified cell
- Observe the diff does not align the earlier modified cell correctly and tried to compare with newly added cell.

IN contrast nbdiff-web is able to catch this difference.

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
gitlens|eam|12.0.1
gitkraken-authentication|git|1.0.3
python-resource-monitor|kai|0.1.9
json-table-viewer|len|0.0.4
rainbow-csv|mec|2.0.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-progressive-increment|nar|1.0.3

</details>

**Comment by rebornix** [comment] 2022-12-28 22:01
/duplicate of https://github.com/microsoft/vscode/issues/133645

**Closed by rebornix** 2022-12-28 22:01 UTC
Labels: bug, notebook-diff, notebook-polish
