### ISSUE TITLE
VS Code caches old file name that does not exist anymore

### ISSUE THREAD

**Issue by Loreno10** [microsoft/vscode#88103] opened 2020-01-05 12:53 UTC
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.2

Steps to Reproduce:
1. Create a file homePage.tsx
2. Rename to HomePage.tsx

Use CMD+P to search for "homepage". List shows you both the old file and the current one:
![image](https://user-images.githubusercontent.com/10273406/71780444-a9f83b80-2fc2-11ea-8a65-ae8097c3aa84.png)

Does this issue occur when all extensions are disabled?: Didn't check

**Comment by bpasero** [comment] 2020-01-06 10:31
@Loreno10 do you rename inside or outside of VSCode? How exactly?

**Comment by Loreno10** [comment] 2020-01-06 11:10
> @Loreno10 do you rename inside or outside of VSCode? How exactly?

Inside VS Code

**Comment by bpasero** [comment] 2020-01-06 11:18
Hm, I cannot reproduce this. Does it reliably reproduce? Is the file opened or closed when you rename?

When the file is opened I can see it updating in the recently opened list. When the editor is not opened, the file is removed from the recently opened for me.

**Comment by methodbox** [comment] 2020-01-14 16:10
This seems to be related to what appears to be a regression ( due to previous issues opened for the same problem which have then been "fixed" in preview builds) exa. https://github.com/microsoft/vscode/issues/72637.

I'm not sure I should open a separate issue, since this one exists, but I will if needed. 

Currently, if you rename a file in terminal, for example, it isn't reflected inside VS Code. It should be watching for these changes, instead it looks like (as per this issue) it's caching the file names. File name changes are actual file changes and should be reflected in Git; not sure how that is working correctly if the file name is cached.

The end result is that changing the name of a file doesn't reflect in the sidebar correctly, even if you *don't have the file open*, then open it, it *still* shows the old name in the tab.

Using "Reveal in Finder" will take you to the *correctly named* file, i.e. obviously VS Code is referencing the correct file, but it doesn't update itself to show that.

I have had this result in the wrong file name being committed to Git (this is bizarre) to the point I had to rename the file in the repo, then pull from remote to get the right file reflected inside VS Code.

This all seems to have started in the last few months.

**Comment by bpasero** [comment] 2020-01-14 16:16
@methodbox that sounds like a separate issue to me because here the user is using the file explorer within VSCode to rename which means we can detect the operation much better compared to renaming anywhere else.

**Comment by methodbox** [comment] 2020-01-14 20:26
> @methodbox that sounds like a separate issue to me because here the user is using the file explorer within VSCode to rename which means we can detect the operation much better compared to renaming anywhere else.

Ok will open a separate issue.

**Closed** 2020-02-11 06:13 UTC
Labels: *not-reproducible, needs more info
