### ISSUE TITLE
Problems Panel Sticky Errors From Closed Files

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#61241] opened 2018-10-18 14:33 UTC
I'm not sure why this occurs sometimes and doesn't other times. The problem I have is the following:
1. Open any file which has warnings/errors showing up in Problems panel.
2. Notice warnings/errors show up just fine.
3. Close the file and/or open another file.
4. Notice the errors from the previous file are still persistent in the Problems panel.

I don't want to see the warnings/errors from the previously closed files. Is this a bug or is there a setting for this that I've been unable to find? 

@mjbvz

**Comment by Astrantia** [comment] 2018-10-20 02:33
@mjvbz can you clarify is this is the expected behavior or a bug? 
it has been like this since I started using visual studio code, so im not sure

**Comment by Astrantia** [comment] 2018-10-22 13:03
@bpasero mjbvz doesn't want to answer so can you clarify if this the intended behavior or not? Persistent errors/warnings are bugging me very much, perhaps there's a configuration I overlooked to disable them?

**Comment by mjbvz** [comment] 2018-10-22 19:55
Duplicate of #59363

Will follow up there

**Comment by Astrantia** [comment] 2018-10-22 20:06
@mjbvz The issue you linked to me is specific to typescript, but I'm seeing the same problematic behavior with .json:
![image](https://user-images.githubusercontent.com/32885386/47316162-77a82b80-d614-11e8-825d-d03911f754eb.png)

^ With having Settings closed.

**Comment by mjbvz** [comment] 2018-10-22 21:02
Oh, I thought you pinged me because you were writing js/ts. Is this for any file type? What if you disable all extensions?

**Comment by sandy081** [comment] 2018-10-23 07:58
@Astrantia Is it happening only for settings file or all files? For settings file what are the steps to reproduce... I am asking because I am not able to repro with settings file

**Comment by Astrantia** [comment] 2018-10-23 14:30
@sandy081 This has been happening to me for all files, but I don't know how to reproduce it yet. It just happens spontaneously after a long usage of vscode.

**Comment by sandy081** [comment] 2018-10-23 15:52
@Astrantia It is hard to fix without able to repro. When it happens next time please check if there are any errors in the console (Use command `Toggle Developer Tools`).

Closing this as it can't be repro.

**Closed by sandy081** 2018-10-23 15:52 UTC
Labels: needs more info
