### ISSUE TITLE
php: Emmet abbreviations with class operator dont show up in suggestions unless php.suggest.basic is disabled

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32423] opened 2017-08-13 17:45 UTC
In a php file, below abbreviations that have the class operator dont show up in suggestions unless `php.suggest.basic` is disabled

- .hello
- ul.hello

**Comment by jens1o** [comment] 2017-08-13 18:15
Well, most of the time the users have disabled this option, because there are extensions which provide better language support

**Comment by ramya-rao-a** [comment] 2017-08-13 20:06
@jens1o That's good to know, but I'd still like to get to the root cause of this issue.

**Comment by roblourens** [comment] 2017-08-28 18:53
@jrieken We debugged a little and this looks like an issue with suggestions in general -

There are two suggestion providers registered, PHP and Emmet. Both are triggered on `.`. When `.` is pressed, Emmet returns nothing, and PHP returns a complete list. When more characters are typed, the completion providers aren't called again, because the completion model is only looking at existing completion items to determine whether the full list is complete. Emmet returned an incomplete result, but since the list was empty, that isn't taken into account by CompletionModel._createCachedState.

**Comment by jrieken** [comment] 2017-08-29 07:37
Yeah, I'd say this is a dupe of #13735. I am not decided one what to do because an empty, but incomplete result set sound wrong to me. With that an extension can hijack the whole completion logic...

**Comment by jrieken** [comment] 2017-09-01 16:05
closing as dupe of #13735. @ramya-rao-a let me know if you need this for September

**Closed by jrieken** 2017-09-01 16:05 UTC
Labels: emmet, php

**Comment by ramya-rao-a** [comment] 2017-10-03 18:08
@jrieken Can we do something about this for the October release?
