### ISSUE TITLE
Opened editors view: weird behaviour when deleting a file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22513] opened 2017-03-13 09:05 UTC
Steps to Reproduce:

1. configure `"workbench.editor.closeOnFileDelete": false`
2. open a file
3. delete it on disk

=> you should see the file tab getting a "(file deleted on disk)" annotation
=> somehow the opened editors view still shows the entry but you cannot click it and it also does not update until you open another file

**Comment by isidorn** [comment] 2017-03-13 16:50
Previously I was creating an OpenEditor from an event so the tree could know which object to refesh - I do not have a map from editor + group to OpenEditor already created.
I simplified this and am now just refreshing the whole group. This seems to work nicely and hopefully does not break anything specified in https://github.com/microsoft/vscode/issues/6670

**Comment by isidorn** [comment] 2017-11-13 18:23
Closing as will not fix due to no user complained, and the fix is not trivial. Also I do not think the issue is mayor.

**Closed by isidorn** 2017-11-13 18:23 UTC
Labels: bug, file-explorer
