### ISSUE TITLE
Extensions SecretStorage issue: Input is not valid base64-encoded data.

### ISSUE THREAD

**Issue by Borvik** [microsoft/vscode#147515] opened 2022-04-15 15:51 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.1, 1.66.2
- OS Version: Ubuntu 20.04.4

So the issue I'm having is as an extension developer (ckolkman.vscode-postgres).

I've had users report an issue that I have tracked back down to vscode - I can confirm the issue on the above versions, but don't know the full extent on other os versions. (https://github.com/Borvik/vscode-postgres/issues/196)

The error being received is: "Input is not valid base64-encoded data."

I've tracked this down to getting the secret from secret storage (https://code.visualstudio.com/api/references/vscode-api#SecretStorage).

I use the SecretStorage api to securely store credentials used by my extension.  The api docs don't seem to indicate a change - but something appears to have changed (whether by design and the docs need to change, or by introducing a bug).

The issue does not appear to affect vscode 1.66.0 - reverting to that version allows it to work.

I do not know whether it affects whether it affects `storing` secrets - but can confirm on `getting` secrets.

Steps to Reproduce (with referenced extension - so far):

1.  In vscode 1.66.0 - with extension, create a db connection with pwd to store creds (without pwd won't use store creds so it won't use the SecretStorage)
2.  Upgrade vscode
3. Try to view the connection explorer and it will error when attempting to pull the secret from storage.

**Comment by dbaeumer** [comment] 2022-04-19 06:41
@jrieken can you help me triage this. Not sure who owns it.

**Comment by deepak1556** [comment] 2022-04-20 00:02
@Borvik was the above steps tested with snap build or Debian build ?

**Comment by Borvik** [comment] 2022-04-20 00:04
Snap

**Comment by deepak1556** [comment] 2022-04-20 01:10
The problem is that encryptionService was not working with snaps before `1.66.1` as seen in https://github.com/microsoft/vscode/issues/116690, with `1.66.1` we made some changes to our native dependency https://github.com/microsoft/vscode/issues/146390 that now enabled the encryption service for snaps as well. So previously unencrypted data are thrown as error.

Migration:

1) At the encryption service layer, encrypt before decrypting for snaps
2) At the extension level, store the secrets again with `1.66.1` before retrieving it (not sure if this is possible unless the extension could retrieve the stored data outside the service)

**Comment by Borvik** [comment] 2022-04-20 01:58
Ok, that may explain the issue, and I can confirm this is not broken on Windows.

Is there a way in the extension to detect installs via snap?

**Comment by TylerLeonhardt** [comment] 2022-04-20 17:37
I have a fix^^ out for this. It will be included in 1.67 which should be released early next month. If you want to workaround this, first catch the SecretStorage Error and do one of two things:

* Ask the user for the thing you stored in SecretStorage again. Easiest to implement... inconvenient for the user.
* Temporarily (just for 1.66) include [node-keytar](https://github.com/atom/node-keytar) in your project and read the secret directly using `getPassword(...)` the service will be: `vscodeckolkman.vscode-postgres` (exactly) and then the account is whatever your key is. Once you get that secret value, store it back using the `SecretStorage` API to prevent future errors. Very inconvenient for you, but the user doesn't have to do anything.

**Comment by TylerLeonhardt** [comment] 2022-04-25 21:35
Verification (on Linux):
* Grab latest stable Snap: 1.66.2
* Log in to GitHub for settings sync or extension
* Close vscode

Install this snap which is a "stable" build of VS Code that includes the fix: https://az764295.vo.msecnd.net/stable/3033c068ec4aa07413cb715316c6a02a1d98ea9c/code-stable-x64-1650429998.snap

When you launch VS Code, you should still be logged in to GitHub

**Comment by Borvik** [comment] 2022-04-26 21:04
```
❯ sudo snap install ./code-stable-x64-1650429998.snap
error: cannot find signatures with metadata for snap "./code-stable-x64-1650429998.snap"
```

**Comment by connor4312** [comment] 2022-04-29 20:50
@TylerLeonhardt those steps didn't work for me, I was signed after installing that snap

<img width="979" alt="image" src="https://user-images.githubusercontent.com/2230985/166067389-bcd01d1c-aef0-4a2d-be01-d3757cbde076.png">

**Comment by TylerLeonhardt** [comment] 2022-04-29 21:31
@connor4312 updated to a newer stable build liked above.

Can you share whats in GitHub Authentication Output pane?

**Comment by TylerLeonhardt** [comment] 2022-05-04 22:36
doesn't seem to work for @connor4312. Will need to investigate further but don't think this needs to be a candidate.

**Comment by Borvik** [comment] 2022-05-06 12:24
Maybe this revealed other issue - but I can confirm with 1.67.0, my extension appears to be working again.

**Comment by Borvik** [comment] 2022-05-11 20:19
and now I am seeing (in 1.67.1) a new error "Cannot get password"

**Comment by deepak1556** [comment] 2022-05-13 05:02
Can confirm the issue from https://github.com/microsoft/vscode/issues/147515#issuecomment-1113715811

Github Authentication log fails with the error `Cannot get password` https://github.com/microsoft/vscode/blob/113287ccc3be52dc3409d451a9b3416d133dca1a/src/vs/workbench/api/browser/mainThreadSecretState.ts#L70

**Closed** 2022-06-03 16:31 UTC
Labels: bug, linux, snap, confirmed

**Comment by TylerLeonhardt** [comment] 2022-06-03 17:17
Ok I have a fix for this. Unfortunately due to the nature of this fix, I was unable to migrate secrets from older versions forward... but at least going forward, we shouldn't see any issues where secrets can't be decrypted after an update.

**Comment by TylerLeonhardt** [comment] 2022-06-03 18:27
Verification is weird but here it is:

* On Linux remove all VS Code stables snaps or debs
* Now install the latest unreleased main stable candidate snap (Like 3cfcfa942c on the builds page) - `snap install --dangerous --classic ./path/to/code.snap`
* Open it, log in to anything (GH/MSFT for settings sync for example)
* Close vscode
* Now install the 3c318d335c stable build that is built on my branch (`tyler/rev-version-for-fun`) (all this branch does is revs the version to 1.69)
* Open it, and verify that your login persisted across versions

**Comment by Borvik** [comment] 2022-06-09 19:16
Ok, just got the update to 1.68 - this is still an issue.

I'm not familiar with your merge process, but it looks like the PR that was linked here for excluding from the snap package was closed without merging.  Is this still coming?

It's almost been 2 months since my extension has been working properly for Snap users.

**Comment by TylerLeonhardt** [comment] 2022-06-09 20:08
@Borvik maybe my message:

> Ok I have a fix for this. Unfortunately due to the nature of this fix, I was unable to migrate secrets from older versions forward... but at least going forward, we shouldn't see any issues where secrets can't be decrypted after an update.

wasn't clear. You will see this issue in the 1.68 update. However, going forward, you shouldn't see it. 1.69 should not have this problem.

**Comment by Borvik** [comment] 2022-06-09 20:52
Thanks, so right now the password hasn't gotten migrated, and right now we are getting the `Cannot get password`, if I understand correctly in 1.69, this issue should disappear - will it still attempt to decrypt the password and then error, or will it just starting working.

If it's going to error, what should I tell the users of my extension?  I would assume that the password would have to be re-entered and then it would get stored in the new way and start working.

**Comment by TylerLeonhardt** [comment] 2022-06-09 22:11
> will it still attempt to decrypt the password and then error, or will it just starting working.

Ah that's a good point... I did not clear the password after the fact. I should do this. That password is essentially dead at this point so it should be cleaned up.

> I would assume that the password would have to be re-entered and then it would get stored in the new way and start working.

Yes that's correct. If you overwrite the password using the SecretStorage API you should be good to go. I think this is generally a good practice to handle when SecretStorage doesn't return an expected result because there are a lot of layers all the way down to the OS that need to work.
