### ISSUE TITLE
broken icons in exploration build

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74526] opened 2019-05-29 10:02 UTC
* use exploration build
* open error peek
* :bug: icons are bust

<img width="1052" alt="Screenshot 2019-05-29 at 12 01 20" src="https://user-images.githubusercontent.com/1794099/58548395-850c4080-8209-11e9-8b48-35fa38cf198d.png">

**Comment by bpasero** [comment] 2019-05-29 10:04
I cannot reproduce when changing the icon theme to our built in ones, so I suspect an issue with the exploration icon theme.

**Comment by misolori** [comment] 2019-05-29 12:55
Thanks for catching that, I think I know why. Will push a fix for it today.

**Comment by misolori** [comment] 2019-05-31 16:02
This is now fixed in the exploration build:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/35271042/58718612-be1bf080-8382-11e9-9564-36b57b46eb23.png">

**Closed by misolori** 2019-05-31 16:02 UTC
Labels: ux
