### ISSUE TITLE
Menus not accessible

### ISSUE THREAD

**Issue by winmike** [Microsoft/vscode#21115] opened 2017-02-22 11:29 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.10|
|beautify|HookyQR|0.8.7|
|rest-client|humao|0.12.2|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|

---

Steps to Reproduce:

1. Open VS Code
2. Try to click on any menu and/or to open ctx menu on any of folder or files in the list pane.
3. No reactions

**Comment by pidov** [comment] 2017-02-22 22:52
* VS Code Version: Unknown (Latest available at the website at the moment)
* OS Version: Windows 10 x64 Insider Preview build 15025.
* Extensions: N/A

I'm experiencing the same!

My system is freshly installed (literally 15 minutes old). I just downloaded Visual Studio Code and tried to use it. Couldn't open any of the menus. They seem to blink on the first few clicks and then stop responding completely. Unfortunately I don't know the VS Code version because it's hidden in an inaccessible menu.

**Comment by bpasero** [comment] 2017-02-23 05:56
This sounds like a bug in the Windows insiders version you guys are using.

**Comment by winmike** [comment] 2017-02-23 08:21
Sounds prudential, can we collect any information to escalate it towards Windows PG, Ben?

**Comment by bpasero** [comment] 2017-02-23 08:39
I suggest to use the official channels of Windows 10 feedback.

**Comment by winmike** [comment] 2017-02-23 08:50
Agree, but the question was: which information should be collected from your point of view to enable colleagues for better investigation

**Comment by bpasero** [comment] 2017-02-23 08:57
@winmike same information you post here :)?

**Comment by darwinkim** [comment] 2017-02-23 23:44
I am running the Windows Insider Preview build 15031. It does seem like an issue only present on recent Insider builds, but I haven't found any other programs that would reproduce this issue.

Compatibility mode to Windows 7 and 8 fixes the issue, but creates other issues such as errors when opening the integrated terminal.

Resizing the window to a small enough size shows that the menus are rendered and is completely functional but are rendered behind the window. Keyboard and mouse controls can be used to select menu items, including the parts hidden behind the window.

**Comment by darwinkim** [comment] 2017-02-24 04:39
I've just posted a Windows Insider feedback for this issue: [https://aka.ms/P274ut](https://aka.ms/P274ut)

If the short link does not work, [click here](feedback-hub:?contextid=443&feedbackid=cc32f47f-05ad-4525-a778-94e1a80c392c&form=1&src=1).

**Comment by darwinkim** [comment] 2017-02-24 04:46
Visual Studio Code was built using GitHub Atom's [Electron API](http://electron.atom.io/). All projects using Electron seems to be having the same issue.

The following programs use the Electron API:

- 1Clipboard
- Atom
- Beaker Browser
- Brave Browser
- Caret
- Collectie
- Flow
- Ghost
- GitKraken
- Hyper
- Insomnia
- JIBO
- Kap
- Kitematic
- Marp
- Now
- Nylas N1
- Ramme
- Simplenote
- Slack
- Svgsus
- Visual Studio Code
- WebTorrent
- WordPress.com

I've tested VS Code, Atom, and WordPress. They are all affected by the same bug.

**Comment by darwinkim** [comment] 2017-02-24 04:57
It's confirmed; Electron has [an issue tracker](https://github.com/electron/electron/issues/8562) for the bug

Rhywden's comment
> Okay, I found the source of the issue - it's the DPI scaling. If it's set to 200% or above (which is the default for a Surface Book with its 3000 by 2000 resolution) then I don't see the menus. If I set the scaling to anything below 200% (i.e. 175% to 100%) then it works normally again.

This may have been because of the new DPI scaling behavior on Windows Insider builds. The compatibility options for DPI scaling override does not have any effect.

**Comment by darwinkim** [comment] 2017-02-25 18:18
The issue seems to be fixed on build 15042! Tested on VS Code and Electron API demos.

**Closed** 2017-02-25 19:25 UTC
Labels: bug, upstream
