### ISSUE TITLE
Problems: light bulb missing in icon even though quick fix present

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#55022] opened 2018-07-25 09:46 UTC
Refs: #54861

1. Open `debug.ts` remove TPromise import from start of file
2. Notice a bunch of errors
3. Notice how the first error does not have a light bulb even though it has a context menu quick fix 

![screen shot 2018-07-25 at 11 46 02](https://user-images.githubusercontent.com/1926584/43193460-5d2e176a-9000-11e8-9242-a350d837d16b.png)

**Comment by sandy081** [comment] 2018-07-25 11:04
@mjbvz Looks like above two quick fixes does not include all diagnostics

![image](https://user-images.githubusercontent.com/10746682/43197306-1206b282-900b-11e8-9dc9-dcb41b7cbe8f.png)

These two quick fixes only includes diagnostic `Cannot find name 'TPromise'.` at `99:17` but not `Return type of method from exported interface has or is using private name 'TPromise'.`

**Comment by mjbvz** [comment] 2018-07-25 18:32
@sandy081 Hard. The quick fix we return is specifically to address the `Cannot find name 'TPromise'` error. It just happens to fix the other one as well

I think the bug is that the quick fix menu is shown on the first marker even though the TS extension has not said if it will be addressed by any quick fix. Looks like we only use the range for computing the actions currently? Should it check the diagnostic code too?

**Comment by sandy081** [comment] 2018-07-25 22:35
@mjbvz There are some quick fix (code action) providers who are not providing diagnostics for their quick fixes. If I check for the diagnostics always, then the quick fixes will not be shown for them.

**Comment by sandy081** [comment] 2018-07-25 22:37
If the quick fix is not meant for that diagnostic, then it makes sense not to show the light bulb indicator. Showing in the context menu is fine in this case I suppose.

**Comment by mjbvz** [comment] 2018-07-25 22:40
Ok, that makes sense. Does that mean though that we will only show the lightbulb in the problems view if there is a code action that includes that diagnostics?  Having the icon and context menu out of sync may be confusing

**Comment by sandy081** [comment] 2018-07-25 22:55
You are right, but this was done for performance reasons. Instead of getting code actions for each diagnostic, I get for the complete file and match them with the diagnostics and show light bulb. 

I would request all linters and language servers to support this for getting this behaviour.

**Comment by mjbvz** [comment] 2019-08-22 00:49
This issue also has the same root cause as https://github.com/microsoft/TypeScript/issues/32901

**Comment by sandy081** [comment] 2019-11-08 13:07
Closing as this is not reported by users and there are no plans to fix

**Closed by sandy081** 2019-11-08 13:07 UTC
Labels: error-list, under-discussion
