### ISSUE TITLE
region navigator

### ISSUE THREAD

**Issue by hansyulian** [microsoft/vscode#51738] opened 2018-06-13 03:29 UTC
So now that we have the #region and #endregion support, can we have a navigator for region? when we click this, then we will right away navigate to one of the region defined in the code. My suggestion of the location of region navigator is either floating on top, right, or bottom of the code editor, or on top of the open editors in explorer as follow:
![image](https://user-images.githubusercontent.com/10959546/41328880-fbe85e26-6efc-11e8-8995-3c6bc977c706.png)

of course included in F1 command also

**Comment by hansyulian** [comment] 2018-06-13 06:29
this one is not duplicated right? i did check before that this one should be very different from all related to region

**Comment by mjbvz** [comment] 2019-10-08 00:52
Duplicate of #58658 I believe

**Closed by mjbvz** 2019-10-08 00:52 UTC
Labels: editor-contrib, feature-request
