### ISSUE TITLE
F# "//#region" not working (1.76.1)

### ISSUE THREAD

**Issue by YkTru** [microsoft/vscode#177051] opened 2023-03-14 07:46 UTC
Type: <b>Bug</b>

All details are here:

https://stackoverflow.com/questions/75729573/vscode-f-how-to-make-region-act-like-c-sharp-region

It's strange since when I used Bisect, it worked for a moment disabling C# Omnisharp (Bisect recommandation). I then tried to create a new //#region, but same issue again (no folding icon)

I hope the issue is on my side since region folding is a real must to manage cognitive overload

Thank you

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.76GB (36.40GB free)|
|Process Argv|--crash-reporter-id e3c9ed49-4bda-4ecd-b627-226a52b5433b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
namespace|adr|1.1.2
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
auto-using|Fud|0.7.15
copilot|Git|1.77.9225
Ionide-fsharp|Ion|7.5.1
vscode-nuget-package-manager|jmr|1.1.6
regionfolder|map|1.0.21
prettify-json|moh|0.0.3
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4152020
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
fantomas-fmt|pao|0.3.0
vscode-nuget-gallery|pat|0.0.24
vscode-xml-complete|rog|0.3.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
vscodedisable:30660115
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by aeschli** [comment] 2023-03-14 08:32
This works for me with no extensions installed.
![image](https://user-images.githubusercontent.com/6461412/224941069-80270237-6aed-46ae-bd97-5f0b609e898a.png)


Very likly, the problem is that you have an extension installed that adds a language aware folding provider that does not support `//#region. You have to file a feature request against that extension.
Alternativly you can decide to not use the language aware folding provider, but indent based provider:
```
	"[fsharp]": {
		"editor.foldingStrategy": "indentation"
	}
```

**Comment by YkTru** [comment] 2023-03-14 17:36
Also, it doesn't work in Visual Studio

**Comment by YkTru** [comment] 2023-03-15 07:30
@aeschli  Any idea? Is Omnisharp and Ionide the problem? What can VSCode team can do about it if it is? Thank you.

**Comment by aeschli** [comment] 2023-03-15 15:52
You are using bisect to find out which extension causes the issue. While doing that bisect turns on and off various extensions and you must answer the questions. So around 30 seconds it must have enabled the csharp extension, that's why the range is gone again.
Once bisect has finished it told you which extension causes the issue.

Later at around 1:28, you are adding a new `//#region`. There are now more start regions than end regions. The top start region has no matching end region and therefore cannot be folded

Looking at the video all looks fine to me.

If you think you have found a bug, please paste a small code sample here.

**Comment by YkTru** [comment] 2023-03-16 06:02
Yes I understand the bisect process, but my point is that if I have to disable csharp ext not only do I loose interop, but Ionide wont work because it depends on it so that's not great at all!

So as you suggests I filed an issue against the extension, but could you please try with Omnisharp and Ionide in VSCode to double-check?  Otherwise if you don't have time I understand thank you very much for your time.

**Comment by aeschli** [comment] 2023-05-01 13:51
Closing as this is caused by an extesnion

**Closed by aeschli** 2023-05-01 13:51 UTC
