### ISSUE TITLE
Sort Files by File Name Length in File Explorer

### ISSUE THREAD

**Issue by BeltonMenete** [microsoft/vscode#224880] opened 2024-08-05 18:29 UTC
Currently, VS Code does not offer the ability to sort files based on their **file name length** within the File Explorer. This feature would enhance user efficiency and flexibility when managing files that require organization or identification by name length.

 **Proposed Feature:**

->  Introduce a new sorting option in the File Explorer context menu or settings.(**_filename length_**)
->  Enable users to sort files in ascending or descending order according to their file name length.(**_filename length asc /desc_**)

![ScreenShot](https://github.com/user-attachments/assets/1c7adf40-252b-4ef6-b1e2-8b51f9d1a656)
By implementing this feature, VS Code would provide a valuable tool for users who rely on file name length for various tasks and organizational purposes.

**Comment by rzhao271** [comment] 2024-12-16 21:58
@lramos15 is this a good first issue considering there is the `explorer.sortOrder` setting?
@BeltonMenete how should folders be sorted relative to the files?

**Comment by lramos15** [comment] 2024-12-19 15:35
Closing as duplicate of https://github.com/microsoft/vscode/issues/27286 

We need to find an extensible way to sort the explorer as there are just too many feature requests for various ways people wish to do this.

**Closed by lramos15** 2024-12-19 15:35 UTC
Labels: file-explorer, under-discussion
