### ISSUE TITLE
VSCode issue with the version 1.94 Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by adamsipo** [microsoft/vscode#230796] opened 2024-10-08 11:45 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.94
- OS Version: Ubuntu 24.04 LTS

Steps to Reproduce:

1. Install VSCode using either the DEB package or from the Snap Store; either method is fine.
2. After opening VSCode, when I click "Open Folder," the application shuts down by itself. This occurred on my Ubuntu 24.04 LTS.

**Comment by gjsjohnmurray** [comment] 2024-10-08 12:12
/duplicate of pinned issue https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-08 12:13 UTC
Labels: *duplicate
