### ISSUE TITLE
Visual Studio issue with Network drive

### ISSUE THREAD

**Issue by grupodesarrolloinnovacion** [Microsoft/vscode#70143] opened 2019-03-10 03:45 UTC
Issue Type: <b>Bug</b>

I have a project in a Network drive that I connect to vsCode through VPN.
In the vscode version 1.28.2 everything was fine, but I upgrade to the last version, and vsCode wasn't work fine.  The editor is too slow and freeze. The editor takes a long time to open the projects  and files.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.80GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.1.1
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-phpfmt|kok|1.0.30
php-namespace-resolver|Meh|1.1.5
dotenv|mik|1.0.1
vsliveshare|ms-|0.3.1284
php-docblocker|nei|1.7.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|3.6.3
vscode-icons|rob|8.2.0
vscode-react-native|vsm|0.8.0
twig|wha|1.0.2

(2 theme extensions excluded)

</details>

**Comment by ingcarlosperez** [comment] 2019-03-10 13:42
I have the same problem.

**Comment by bpasero** [comment] 2019-03-11 10:43
@grupodesarrolloinnovacion @ingcarlosperez when you open VSCode is it the editor that is slow to open files or the file explorer to the left?

**Comment by psilonmarko** [comment] 2019-03-11 12:00
Same problem here (VS Code 1.32, Debian 9)
When I open mounted folder (over VPN), file explorer populates the list quickly, but the editor just loads... and loads... and loads.... after that VSCode is so no longer responsive and I have to kill it. However if I wait for some time (couple of minutes) it becomes responsive again and it works - but slower than 1.28. If I close it and reopen the same folder, it starts reindexing (?) the folders again. 
I added some folders in files.watcherExclude but it doesn't help.
Mounted folders from local network don't cause problems.

For now I'm downgrading to 1.28

**Comment by nogenem** [comment] 2019-03-11 13:24
Same problem here (VS Code 1.32, Win 10)

**Comment by bpasero** [comment] 2019-03-11 14:13
Duplicate of https://github.com/Microsoft/vscode/issues/70045

Let's continue the discussion in there.

**Closed** 2019-03-11 14:14 UTC
Labels: needs more info, new release
