### ISSUE TITLE
TypeScript syntax highlighting error in for-loop

### ISSUE THREAD

**Issue by Groschenroman** [Microsoft/vscode#5096] opened 2016-04-08 14:16 UTC
- VSCode Version: 0.10.11
- OS Version: Mac OS X Yosemite (10.10.5)
- Default syntax highlighting
- Issue persists when running VSCode with `--disable-extensions`

Syntax highlighting gets confused within for loop. Strings don't get recognized. Elements that follow a string are considered to be strings instead (as it seems to me).
After the for-loop there are still syntax highlighting errors but line 74 in screenshot looks fine again.

Steps to Reproduce:

1. Open new TypeScript file within Angular 2 project (aka create new component)
2. Create for loop (see Screenshot)
![screen shot 2016-04-08 at 16 00 39](https://cloud.githubusercontent.com/assets/7312890/14386505/78de89da-fda5-11e5-8b20-6fc7947b08af.jpg)

**Comment by contreras-jorgev** [comment] 2016-04-08 15:06
I also noticed related issue.

In the following simple code (file named "test.js"):
    var l = 5;
     for( var i=0; i<l; i++ ) {
         var in_loop; /* coloring stops working */
     }

After the opening brace '{' in the for loop line, any var declared inside is not colored correctly.

If the color theme being used is "Dark+ (default dark)" most of the color inside the loop is 'green'

**Comment by bgse** [comment] 2016-04-08 21:25
Does it persist when you add spacing like this in the loop?

`for(var i = 0; i < I; i++)`

If that resolves the issue, it is probably https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Comment by ericmartinezr** [comment] 2016-04-08 22:01
I reported a similar issue over here https://github.com/Microsoft/vscode/issues/4841 and I think the problem is the `:` and other few things that I found. I've updated my original issue with some screenshots that may be useful.

**Comment by Groschenroman** [comment] 2016-04-11 09:37
@bgse: You're right. Adding spaces fixed the highlighting. Feels like a kind of workaround though.

@ericmartinezr: Thx!

**Comment by aeschli** [comment] 2016-04-11 14:26
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-04-11 14:26 UTC
