### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by jsupa** [microsoft/vscode#170578] opened 2023-01-04 19:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0-insider Commit: 4acf2d9b46b75748ae687cf3b2952a0799679873
- OS Version: Darwin arm64 22.2.0

Steps to Reproduce: 

1. Open Keyboard Shortcuts
2. Change View: Toggle Terminal
3. press CMD+BracketRight 

Actual result: Shortcut save as CMD+X

![image](https://user-images.githubusercontent.com/74856856/210635439-7ae8e43d-bd90-4678-ab12-414c7d814f46.png)
![image](https://user-images.githubusercontent.com/74856856/210635645-98726088-645a-46f7-9631-97c074c07541.png)

I didn't make any changes and it was still working for me recently.

**Comment by jsupa** [comment] 2023-01-04 19:44
![image](https://user-images.githubusercontent.com/74856856/210636530-06350021-9e56-453f-8fa9-4d2735c07eeb.png)

**Comment by ulugbekna** [comment] 2023-12-07 16:04
Hi @jsupa, I think this is duplicate of https://github.com/microsoft/vscode/issues/173325. Please, let us know if you can still reproduce.

**Closed by ulugbekna** 2023-12-07 16:04 UTC
