### ISSUE TITLE
Terminal tab is blank on Windows 10

### ISSUE THREAD

**Issue by stevenbdf** [microsoft/vscode#138169] opened 2021-11-30 15:23 UTC
Issue Type: <b>Bug</b>

The terminal of my VSCode suddenly stopped working. Now is blank and I can't do anything on it. I'm using Windows 10 and this hasn't happened to me before. 

I use the Git Bash as a default bash profile. I event tried uninstalling, deleting all the setting/extensions files and installing it again, but still doesn't work.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon 3000G with Radeon Vega Graphics      (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.55GB free)|
|Process Argv|--crash-reporter-id 11b925f1-12ac-4c5e-8be8-ef55afb4f735|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptt2:30404948
vscop804:30404766
vs360:30404995

```

</details>

**Comment by stevenbdf** [comment] 2021-11-30 16:23
I looked into the developer tools and I saw these errors.
![image](https://user-images.githubusercontent.com/35903969/144086334-81dd5d1d-2ad5-4aef-938f-24b44b7ea84d.png)

I went to that directory and exactly there isn't a node_modules directory. (I already have enabled the Explorer feature to see hidden files/directories)

![image](https://user-images.githubusercontent.com/35903969/144086489-554be130-a9f1-4cbe-aeb6-23e0772c9466.png)

**Comment by Tyriar** [comment] 2021-11-30 16:46
This looks suspicious and conflicts with the extension list you posted:

![image](https://user-images.githubusercontent.com/2193314/144090350-c412726a-55d4-432e-9c14-fe3d64dc4538.png)

Does it happen when you close all windows and run `code --disable-extensions`?

**Comment by stevenbdf** [comment] 2021-11-30 17:11
Yes, I just reloaded it in that way and I got the same problem. 
![image](https://user-images.githubusercontent.com/35903969/144094640-1c308526-4f20-4558-ad13-923b48ba199c.png)

**Comment by steffchep** [comment] 2021-12-01 07:46
I've got the same issue!

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

First noticed yesterday. At some point it suddenly worked again, no idea why. This morning, gone again.

Terminal section is blank, trying to open a fresh terminal via the plus, the keyboard shortcut or the menu does nothing (also no further error messages in the dev tool console).

I made no changes to the configuration for weeks, if not months, and I noticed this problem first yesterday, and only on one of my machines.

![vscode-terminal-broken](https://user-images.githubusercontent.com/10571670/144192498-cb29fe32-ce90-46b8-ba11-7b6ec8a824be.jpg)

**Comment by steffchep** [comment] 2021-12-02 09:06
Update: It seems an erratic thing, did not work at all yesterday, today I started VScode, no terminal. Had it running in the background for a while and looked at it again - terminal is there.

**Comment by stevenbdf** [comment] 2021-12-04 01:38
Some times it works and some times it doesn't.

**Comment by xbfld** [comment] 2021-12-04 06:55
I have same issue after update vscode, so I tried reinstall older version.
July 2021 (v1.59) was OK and problem reproduced on August 2021 (v 1.60).

until someone fix this issue, just using v1.59 is one of option i think...

**Comment by Tyriar** [comment] 2021-12-20 19:16
Can anyone confirm whether this happens after closing all windows and running `code --disable-extensions`? I can't reproduce.

**Comment by steffchep** [comment] 2021-12-20 19:37
I'm on 1.63.2 now and it has not happened for some time.

**Closed** 2022-03-19 11:26 UTC
Labels: needs more info
