### ISSUE TITLE
Git extension should not wrap `console` methods

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#139896] opened 2021-12-29 20:29 UTC
**Describe the bug**

When developing or testing extensions, it's common for developers to log data from their extensions. However, because the git extension wraps console methods, the lines reported to the developer are incorrect.

**To Reproduce**
1. Create a hello world extension https://code.visualstudio.com/api/get-started/your-first-extension
2. In the launch.json, add the following lines (this will be unnecessary in the next release):
 	```
	"skipFiles": [
		"<node_internals>/**",
		"**/bootstrap-fork.js"
	],
	```
3. Add a `console.log("hello")` to the command in `src/extension.ts`
4. F5, and run the hello world command

Note: you may need to disable codespaces, the github auth, Github PR, and Microsoft auth plugins to see this, because they do the same thing https://github.com/github/codespaces/issues/5622 https://github.com/microsoft/vscode/issues/139895 https://github.com/microsoft/vscode/issues/139894 https://github.com/microsoft/vscode-pull-request-github/issues/3213

**Expected behavior**

The line in the console points to the source line in the user's code where the log message appeared.

**Actual behavior**

It's the git extension where it wraps the global console methods. It should _not_ wrap these methods.

**Screenshots**

See the source in the lower right corner points to a place where the extension wraps the global console methods.

![image](https://user-images.githubusercontent.com/2230985/147700882-e3812ff5-3ba1-4b0a-b419-b172b4b01267.png)

**Comment by alexr00** [comment] 2022-01-03 13:05
Maybe caused by https://github.com/microsoft/vscode-extension-telemetry/issues/88

**Comment by lszomoru** [comment] 2023-01-02 15:57
Closing as I do not believe this was an issue with the git extension.

**Closed by lszomoru** 2023-01-02 15:57 UTC
Labels: debt, git
