### ISSUE TITLE
Crashes when opening whatever folder or checking for updates

### ISSUE THREAD

**Issue by step135** [microsoft/vscode#108531] opened 2020-10-12 14:36 UTC
- VSCode Version: latest from snap today
- OS Version: Fedora 32

Steps to Reproduce:

1. click on option open folder or Help -> Check for updates

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by JacksonKearl** [comment] 2020-10-12 18:53
Is this the latest insiders or stable version?

**Comment by step135** [comment] 2020-10-18 22:39
As I wrote, it is the actual version on snap.

**Comment by JacksonKearl** [comment] 2020-10-20 18:58
duplicate of https://github.com/microsoft/vscode/issues/100940

**Closed by JacksonKearl** 2020-10-20 18:58 UTC
Labels: needs more info
