### ISSUE TITLE
VSC will only create an initial terminal of the PowerShell type

### ISSUE THREAD

**Issue by RasmusVedsted** [microsoft/vscode#132622] opened 2021-09-08 07:36 UTC
Issue Type: <b>Bug</b>

I usually have a live terminal when I close VSC. In my experience, this ensures that VSC will create a new terminal upon reopening.

When I reopen VSC, it used to create my default terminal, but now it creates a PowerShell terminal despite my default terminal being Command Prompt. I first noticed this yesterday, and I don't remember making any update recently.

When I make a new terminal, it becomes a Command Prompt terminal, as expected, but the one created on startup is not.

Several times, I've set my default terminal to Command Prompt, killed the terminal, and restarted VSC. This has not solved the problem: After this, it doesn't create any terminal when reopened, but it will proceed to only ever create a PowerShell terminal on a reopen.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.87GB (10.98GB free)|
|Process Argv|--crash-reporter-id 80c8e3a2-4f5c-4fa8-ae4a-225dabe81c3f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by clarkjoey** [comment] 2021-09-08 07:41
Also having the same experience after updating!

**Comment by lebron112** [comment] 2021-09-08 07:58
我也有同样的问题，之前是设置默认启动用gitbash，现在设置不了了

**Comment by IllusionMH** [comment] 2021-09-08 08:40
/duplicate of #132150 - should be in recovery release

**Closed** 2021-09-08 08:40 UTC
Labels: *duplicate
