### ISSUE TITLE
Do not follow circular symlinks when auto expanding folders

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11461] opened 2016-09-02 15:16 UTC
- VSCode Version: 1.5 Insider
- OS Version: Window 10

Steps to Reproduce:
1.  Workspace folder
2.  Set up a cylic link between folders using mklink /D (only available in the cmd.exe under Administrator)
3. Open the workspace folder

You get:

![capture](https://cloud.githubusercontent.com/assets/1931590/18208768/0b8bda86-7131-11e6-8769-5d6cdd158ef9.png)

**Comment by dbaeumer** [comment] 2016-09-02 15:23
Same when using junction command.

**Comment by bpasero** [comment] 2016-09-02 16:15
@dbaeumer what is the bug actually? we do the same as the native windows explorer. we typically try to show the real situation as it is on disk and not hide something from the user.

Closing as designed unless you found an actual issue in the explorer doing so.

**Comment by dbaeumer** [comment] 2016-09-05 07:09
@bpasero the explorer to my knowledge doesn't render a tree. I would have expected some visual indication that there is s cycle. 

What I found very strange as well is the fact then when I opened VS Code on that folder the tree expanded exactly to the state shown in the screen shot. Why into that state. What makes you break the cycle here.

**Comment by bpasero** [comment] 2016-09-05 07:46
@dbaeumer can you share a screenshot how the native windows explorer presents you this circular structure?

There is a couple of things going on in your example which are a bit special:
* the explorer automatically expands folders that have only 1 child so that for cases with many single-child folders (e.g. think of Java projects) you quickly end up in the folder that actually has files
* since you have a cyclic dependency, the explorer ends up automatically expanding the folder on and on (debatable if this should be treated as bug or not)
* once you hit a path length of 255 characters, windows stops following a link (as far as I know). so in your case we just reached the max path length

If the native windows explorer handles this case in a clever way, then I agree we should change our handling too.

**Comment by dbaeumer** [comment] 2016-09-05 07:59
Here is what the native Windows Explorer shows:

![capture](https://cloud.githubusercontent.com/assets/1931590/18241039/50c7295a-734f-11e6-8000-cf5913aca107.png)

Note it didn't expand automatically (I wasn't aware of your one child case). And it has this nice link overlay telling me that it is a linked folder.

**Comment by bpasero** [comment] 2016-09-05 08:04
@dbaeumer ok so the explorer is also going on and on even though this is a circular link. The only difference I see is that a linked folder gets a nice decoration over the folder. Is that what you are missing?

**Comment by dbaeumer** [comment] 2016-09-05 09:33
I would change two thinks:

- render the link 
- and don't auto expand cycles. 

I was more confused by the auto expand behavior.

**Comment by bpasero** [comment] 2016-09-05 11:47
@dbaeumer I extracted the rendering of links to https://github.com/Microsoft/vscode/issues/11539. imho this should happen from the icon theme because if you do not show icons, we cannot really render symlinks.

As for not following symlinks when auto expanding, lets keep this one.

**Comment by bpasero** [comment] 2016-09-06 05:55
Actually this is not due to the explorer following empty directories, but due to `autoExpandSingleChildren` option for the tree. I do not have any control over when to expand a tree and when not. I think this option was added later to the tree and originally the explorer was expanding by itself. We might have to go back to that solution or have a way in the tree to stop expanding under certain conditions.

/cc @joaomoreno

**Comment by joaomoreno** [comment] 2016-09-06 09:31
IMO that option shouldn't even exist in the tree. That logic should be implemented outside of it. I suggest you do that. Once done, I'd remove that option from the tree.

**Comment by bpasero** [comment] 2016-09-06 09:40
@joaomoreno it used to be outside of the tree and I do not know why or who added it into the tree

**Closed** 2018-07-05 10:20 UTC
Labels: *out-of-scope, bug, file-explorer, file-io
