### ISSUE TITLE
css property 'cursor' style is different

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#43681] opened 2018-02-14 16:49 UTC
css property 'cursor' style is different, though I'm not completely sure it's an issue.
![css-cursor](https://user-images.githubusercontent.com/1499188/36216534-62723640-11af-11e8-84be-c085bdff7aa1.JPG)

**Comment by usernamehw** [comment] 2018-02-14 17:17
If it's not `CSS`, but `SCSS` then it's a duplicate of https://github.com/atom/language-sass/issues/226

**Comment by aeschli** [comment] 2018-02-15 16:46
This works for me in the latest:
![image](https://user-images.githubusercontent.com/6461412/36268931-24af7cd6-1278-11e8-903e-5dc4a63f42f9.png)

**Closed by aeschli** 2018-02-15 16:46 UTC
Labels: css-less-sass
