### ISSUE TITLE
Automatic extension update fails with UnknownError: Signature: UnknownError

### ISSUE THREAD

**Issue by Spanfile** [microsoft/vscode#167408] opened 2022-11-28 14:26 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.0-insider
Commit: ac084d723b7405591d2110fe374648345ecb8ce6
Date: 2022-11-28T05:23:46.430Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.10-native_intel-xanmod1-1
Sandboxed: Yes
- OS Version: Arch Linux (VS Code installed with the AUR package `visual-studio-code-insiders-bin`)

Steps to Reproduce:

1. Attempt to update any extension with a pending update
2. The update fails with "Error while updating 'Remote - SSH' extension. Please check the [log](command:workbench.action.showWindowLog) for more details."
Window log:
```
2022-11-28 16:16:50.292 [info] Electron sandbox mode is enabled!
2022-11-28 16:16:50.842 [warning] Skipping extension /home/user/.vscode-insiders/extensions/ms-vscode.js-debug-1.72.1 in favour of the builtin extension /opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug.
2022-11-28 16:16:50.843 [error] Extension 'ms-vscode.js-debug' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): portsAttributes, findTextInFiles, workspaceTrust, resolvers, tunnels
product.json (WINS): portsAttributes, findTextInFiles, workspaceTrust, tunnels
2022-11-28 16:16:53.408 [info] [perf] Render performance baseline is 21ms
2022-11-28 16:16:55.200 [error] UnknownError: Signature: UnknownError
    at pt.download (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92674)
    at async Y.h (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167628)
2022-11-28 16:17:02.338 [error] Signature: UnknownError
    at pt.download (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92674)
    at async Y.h (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167628)
2022-11-28 16:17:02.367 [error] UnknownError: Signature: UnknownError
    at pt.download (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92674)
    at async Y.h (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167628)
```

It happens with at least the extensions Remote - SSH, Python and rust-analyzer. Manually downloading the extensions and installing via the command line does work.

**Comment by sandy081** [comment] 2022-11-29 16:00
CC @isidorn

**Comment by furai** [comment] 2022-11-30 08:15
Still present in:
```Version: 1.74.0-insider
Commit: 9908b3d5ae12691da5adc2f18e21a100ee8eeb58
Date: 2022-11-30T05:33:53.125Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.10-arch2-1
Sandboxed: Yes```

**Comment by isidorn** [comment] 2022-12-01 10:00
Thanks a lot for filling these issues. We are looking into a fix.
In the meantime here's a workaround:
Set `extensions.verifySignature` to `false` in your `settings.json`

**Comment by furai** [comment] 2022-12-02 10:10
![image](https://user-images.githubusercontent.com/2674689/205268761-abba5a68-46ce-4591-aa13-6c9391e762f8.png)
I don't see such option. And when I just put it in it does not work. Maybe it's something available only in development version of VSCode?

**Comment by furai** [comment] 2022-12-08 08:13
Any news on this issue?

**Comment by sandy081** [comment] 2022-12-08 08:31
Please continue using this setting `"extensions.verifySignature" = false` until this is fixed

**Comment by wrenparismoe** [comment] 2022-12-09 04:03
I have had an identical error for nearly a month now. I can't install or update any extensions.

**Comment by isidorn** [comment] 2022-12-09 08:56
@wrenparismoe what OS are you using? If you set `"extensions.verifySignature" = false` in your settings does that fix the problem?
We are investigating this issue and hope to have a fix soon. Thank you for your patience.

**Comment by sandy081** [comment] 2023-01-23 21:52
@isidorn/@dtivel Any updates on this?

**Comment by dtivel** [comment] 2023-01-23 23:56
This should be resolved with latest Insiders via https://github.com/microsoft/vscode/pull/169777.  If it isn't, please let us know with your version info.

**Comment by isidorn** [comment] 2023-01-24 09:55
Closing as fixed

**Comment by furai** [comment] 2023-01-24 10:29
Seems to be working here. Thanks for fixing.

**Comment by isidorn** [comment] 2023-01-24 11:51
Correct. We have follow up work that is investigating the underlying problem.

**Comment by TylerLeonhardt** [comment] 2023-01-25 23:45
Only marking verification found because there's no issue linked about the the follow up work. @isidorn if there is one, can you link it here?

Once that's linked this can be marked verified since @furai confirmed it's fixed by handling the error.

**Comment by isidorn** [comment] 2023-01-26 14:44
Thanks @TylerLeonhardt 
Some follow up work is here https://github.com/microsoft/vscode/issues/168525
More details and work in our private planning repo to which I can not link from here unfortunately.

**Closed by isidorn** 2023-01-26 14:44 UTC
Labels: bug, verification-found, extensions
