### ISSUE TITLE
Rendering error on macOS

### ISSUE THREAD

**Issue by romshark** [Microsoft/vscode#20472] opened 2017-02-11 11:48 UTC
There is an annoying rendering error on macOS Sierra that you can see on these screenshots, colors go crazy in the editor as well as on the panels and the footer. The color theme doesn't matter, experience the same bug on any available color theme (except the "High Contrast" one). When in the editor a line is selected this "box" on the right goes aways, but only in selected regions.

<img width="1440" alt="bildschirmfoto 2017-02-11 um 12 10 36" src="https://cloud.githubusercontent.com/assets/9574743/22853468/75f9b0d2-f057-11e6-8112-bae0d7de65db.png">
<img width="1440" alt="bildschirmfoto 2017-02-11 um 12 30 22" src="https://cloud.githubusercontent.com/assets/9574743/22853470/7dcdacfa-f057-11e6-93c1-c3b21635ccf7.png">
<img width="1440" alt="bildschirmfoto 2017-02-11 um 12 32 25" src="https://cloud.githubusercontent.com/assets/9574743/22853475/823ff04a-f057-11e6-8adc-10e255a99f9a.png">

- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1a. Just open VSC and you'll see it on the panels
1b. Open any document in VSC on any color theme

**Comment by FromZeus** [comment] 2017-02-12 18:21
+1

**Comment by mrmlnc** [comment] 2017-02-12 19:03
Duplicate of #12473.

Sorry, but, please, use search before create a new issue.

See official release notes: http://code.visualstudio.com/updates/v1_6#_macos-sierra-support

**Comment by joaomoreno** [comment] 2017-02-14 13:59
Thanks, @mrmlnc

**Closed by joaomoreno** 2017-02-14 13:59 UTC
