### ISSUE TITLE
When the window is not in focus, it takes two clicks to open a folder or file in File Explorer.

### ISSUE THREAD

**Issue by zhanxiaoge** [microsoft/vscode#206585] opened 2024-03-01 02:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows 10

Steps to Reproduce:

1. Make vscode lose focus.
2. Click on folders or files in File Explorer.

If clicking on an already opened file in File Explorer, it opens normally without the need for a double-click.

**Comment by myakura** [comment] 2024-03-03 05:23
It happens to me as well with the latest update

Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

maybe a dupe of https://github.com/microsoft/vscode/issues/166118, but this hasn't happed to me until the last couple of days.

**Comment by artturimatias** [comment] 2024-03-06 11:18
Same problem here. I think that it appeared on latest update.

Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:16.599Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.10.0-28-amd64

**Comment by huynamboz** [comment] 2024-03-08 13:44
Same issue

**Comment by Mistale** [comment] 2024-03-14 07:30
Same for me, it didn't happen until a few weeks ago. It's very annoying since the hover state works as expected, but clicking the hovered file doesn't do anything (the first time).

**Comment by xt0rted** [comment] 2024-03-23 18:52
I updated to 1.87.2 yesterday, I don't recall which version I was on prior to that, and I'm experiencing this behavior now too. It's really annoying because I keep thinking I selected a file only to realize it's not actually open and I have to click on it again.

**Comment by lramos15** [comment] 2024-03-25 13:43
I'm still working on reproducing this on my Mac. Maybe I cannot due to lack of dual monitors on this screen.

If anyone feels like doing some investigation you can bisect versions of VS Code to find when the regression occurred using https://github.com/microsoft/vscode-bisect

**Comment by uiii** [comment] 2024-03-26 10:21
I have the same problem.

Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by xt0rted** [comment] 2024-03-26 19:39
I ran `vscode-bisect` and that ended with the following:

```text
Run the following commands to continue bisecting via git in a folder where VS Code is checked out to:

git bisect start && git bisect bad cfa5001723394bbe633c8fa14d539334a1111be7 && git bisect good 9db1b0571e119289a2264971bdac75793965e063
```

Commits https://github.com/microsoft/vscode/compare/9db1b0571e119289a2264971bdac75793965e063...cfa5001723394bbe633c8fa14d539334a1111be7

I tried running `git bisect` but I keep running into issue after issue getting the code to build and finally just gave up. Hopefully that's enough information to point someone else in the right direction.

**Comment by lramos15** [comment] 2024-03-26 19:49
Thanks @xt0rted. @joaomoreno since were you able to repro would you be able to bisect this? I see one list commit in that range https://github.com/microsoft/vscode/commit/23c84573fbfa9858b67721dd619e4de3ef0b15de and that's the only possible culprit I see just by glancing at commit names

**Closed** 2024-03-28 16:38 UTC
Labels: bug, file-explorer, regression, confirmation-pending

**Comment by zhanxiaoge** [comment] 2024-04-07 02:23
> Thanks @xt0rted. @joaomoreno since were you able to repro would you be able to bisect this? I see one list commit in that range [23c8457](https://github.com/microsoft/vscode/commit/23c84573fbfa9858b67721dd619e4de3ef0b15de) and that's the only possible culprit I see just by glancing at commit names

Thank you very much, but the issue hasn't been fixed. I have submitted a demonstration video.https://github.com/microsoft/vscode/issues/209741

**Comment by lramos15** [comment] 2024-04-08 14:06
@zhanxiaoge Confirms it is fixed here https://github.com/microsoft/vscode/issues/209741#issuecomment-2041800374

Just in case someone doesn't read the other thread
