### ISSUE TITLE
Allow configuration for location of integrated terminal

### ISSUE THREAD

**Issue by haasDev** [Microsoft/vscode#31332] opened 2017-07-24 15:43 UTC
I usually prefer to work with my terminal to the right of the editor. It would be nice to have an option to set where the terminal shows. Thanks for all your great work!

**Comment by Tyriar** [comment] 2017-07-24 17:09
Duplicate of https://github.com/Microsoft/vscode/issues/2806

**Closed by Tyriar** 2017-07-24 17:09 UTC
Labels: integrated-terminal
