### ISSUE TITLE
Report issue feature do not include extension information

### ISSUE THREAD

**Issue by themnd** [microsoft/vscode#83093] opened 2019-10-22 19:09 UTC
Issue Type: <b>Bug</b>

Issue https://github.com/microsoft/vscode/issues/83074 was automatically created by the "Report issue" feature of visual studio code.
In the "File on" field I've selected "An extension" and in the "Extension" field which appears I've selected "Prettify JSON", it was the first time I used this "report" feature and I was puzzled by the fact that the extension I've selected was nowhere to be seen in the issue being created.

Issue #83074 was closed because not relevant to vscode (since it is caused by an extension) but probably the "Report issue" feature should have prevented me from creating that issue or should have warned me that the issue must be created elsewhere.
Probably the best would be to open the extension github issues (since you should already have the extension github link).

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
create-jsconfig|Tom|0.2.0
jsx|Twe|0.0.1
Bookmarks|ale|10.5.0
Handlebars|and|0.4.1
swagger-viewer|Arj|2.2.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.5.1
jenkins-runner|dav|1.2.2
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
javadebugger|don|0.1.5
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
php-intellisense|fel|2.3.13
vscode-mysql|for|0.4.0
fs-flutter-snippets|fra|0.1.3
vscode-javac|geo|0.2.27
ansible|haa|0.2.8
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
Scala|itr|0.1.7
jenkinsfile-support|ivo|0.4.4
swift|Kas|0.1.0
dart|kev|0.1.0
restructuredtext|lex|114.0.0
ecdc|mit|1.3.0
prettify-json|moh|0.0.3
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
azure-account|ms-|0.8.6
Go|ms-|0.11.7
node-debug2|ms-|1.39.1
vsliveshare|ms-|1.0.1056
cordova-tools|msj|1.9.0
debugger-for-chrome|msj|4.12.0
debugger-for-ios-web|msj|0.1.2
vscode-react-native|msj|0.12.1
vetur|oct|0.22.5
vscode-spring-boot|Piv|1.11.0
swaggitor|qns|0.1.1
ruby|reb|0.25.3
java|red|0.51.0
vscode-quarkus|red|1.1.0
vscode-yaml|red|0.5.3
nunjucks|ron|0.2.3
vscode-nginx|sha|0.6.0
velocity|sod|0.2.0
vcl|tho|0.1.2
python-extended-snippets|tus|0.0.1
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
ReactSnippets|xab|2.3.0

</details>

**Comment by RMacfarlane** [comment] 2019-10-23 16:39
Duplicate of https://github.com/microsoft/vscode/issues/73515

**Closed by RMacfarlane** 2019-10-23 16:39 UTC
