### ISSUE TITLE
vscode failed to load image

### ISSUE THREAD

**Issue by Tracker647** [microsoft/vscode#124488] opened 2021-05-24 08:31 UTC
issue type: bug
my vscode info:
![image](https://user-images.githubusercontent.com/54085641/119319748-697b8980-bcad-11eb-8faf-8c1e5681217c.png)

error message:
`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

![image](https://user-images.githubusercontent.com/54085641/119319858-844dfe00-bcad-11eb-8533-cb337794f96c.png)

**Comment by Tracker647** [comment] 2021-05-24 08:32
my extension list:
```
abierbaum.vscode-file-peek@1.0.1
abusaidm.html-snippets@0.2.1
bierner.markdown-preview-github-styles@0.2.0
bmewburn.vscode-intelephense-client@1.7.1
CoenraadS.bracket-pair-colorizer-2@0.2.0
danielpinto8zz6.c-cpp-project-generator@1.2.4
dbaeumer.vscode-eslint@2.1.20
ecmel.vscode-html-css@1.10.2
esbenp.prettier-vscode@6.4.0
felixfbecker.php-debug@1.15.1
formulahendry.auto-rename-tag@0.1.6
formulahendry.code-runner@0.11.4
gamunu.vscode-yarn@1.7.1
hediet.debug-visualizer@2.0.6
hollowtree.vue-snippets@1.0.4
ionutvmi.path-autocomplete@1.17.1
jakebathman.mysql-syntax@1.3.1
michelemelluso.code-beautifier@2.3.3
mkaufman.HTMLHint@0.10.0
mrmlnc.vscode-less@0.6.3
mrmlnc.vscode-scss@0.10.0
ms-python.python@2021.5.842923320
ms-python.vscode-pylance@2021.5.3
ms-toolsai.jupyter@2021.6.832593372
ms-vscode.cmake-tools@1.7.3
ms-vscode.cpptools@1.3.1
octref.vetur@0.33.1
pranaygp.vscode-css-peek@4.2.0
ProEagle.px2xx@0.0.2
redhat.java@0.79.2
ritwickdey.LiveServer@5.6.1
techer.open-in-browser@2.0.0
tht13.html-preview-vscode@0.2.5
twxs.cmake@0.0.17
VisualStudioExptTeam.vscodeintellicode@1.2.14
vscjava.vscode-java-debug@0.33.1
vscjava.vscode-java-dependency@0.18.3
vscjava.vscode-java-pack@0.15.0
vscjava.vscode-java-test@0.29.0
vscjava.vscode-maven@0.30.1
xsro.masm-tasm@0.8.5
yzhang.markdown-all-in-one@3.4.0
Zignd.html-css-class-completion@1.20.0
```

**Comment by mjbvz** [comment] 2021-05-24 18:49
Duplicate of #122951

**Closed by mjbvz** 2021-05-24 18:49 UTC

**Comment by Tracker647** [comment] 2021-05-24 23:45
Problem solved, I re-installed it.
