### ISSUE TITLE
Perf: xterm is being loaded right on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40146] opened 2017-12-13 07:03 UTC
Even though there is code to load xterm async (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L257) I see it showing up and taking the most part of node module loading right on startup (when running `code -p`):

![image](https://user-images.githubusercontent.com/900690/33925865-19ac6f66-dfdc-11e7-8c89-bed6bb562959.png)

It looks like we manage to require `xterm` before already and should try to avoid that if possible.

**Comment by jrieken** [comment] 2017-12-13 08:34
this is a dupe of https://github.com/Microsoft/vscode/pull/31216 and https://github.com/Microsoft/vscode/pull/40122

**Closed by jrieken** 2017-12-13 08:34 UTC
Labels: perf, perf-startup
