### ISSUE TITLE
VSCODE Icon is not the correct one

### ISSUE THREAD

**Issue by fskorzec** [Microsoft/vscode#36731] opened 2017-10-23 07:57 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (c1be82537d9fda852a258851f48ea78b7fc8a7a3, 2017-10-23T04:18:13.902Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
code-runner|for|0.7.4
mediawiki|jak|2.1.0
web-browser|mas|0.0.1
vscode-antlr4|mik|1.1.10
azure-account|ms-|0.1.3
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
material-icon-theme|PKi|2.2.3
vscode-hexdump|sle|1.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Run VsCode
2. Look at the Icon on the Title Bar... It-s not VsCode Icon.

**Comment by maxibanki** [comment] 2017-10-23 08:03
When the icon is the electron icon:
![image](https://user-images.githubusercontent.com/17984549/31878156-64e798fa-b7d9-11e7-8834-4c7aafd5b00c.png)

Then it is a duplicate of #36665

**Comment by warpdesign** [comment] 2017-10-23 08:49
@maxibanki I confirm the problem and it's this icon indeed.

**Comment by mjbvz** [comment] 2017-10-23 22:17
Duplicate of #36665

**Closed by mjbvz** 2017-10-23 22:17 UTC
Labels: workbench
