### ISSUE TITLE
Bugs in GUI (code-insiders)

### ISSUE THREAD

**Issue by RinatValiullov** [Microsoft/vscode#58285] opened 2018-09-09 10:23 UTC
Issue Type: Bug

1. There are bugs in GUI of menu items (all). See examples' screenshots below.

- VSCode Version: 1.28.0 - insider (system setup) (https://github.com/Microsoft/vscode/commit/a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4 2018-09-09T15:20:39)
- OS Version: Windows 7 Ultimate 6.1.7601 Service Pack 1 rev 7601

Does this issue occur when all extensions are disabled?:  Yes

Screenshots:

![help](https://user-images.githubusercontent.com/9755333/45263406-5f07fb80-b442-11e8-8154-faa4528ddb31.png)

![edit](https://user-images.githubusercontent.com/9755333/45263407-629b8280-b442-11e8-9152-1f2b0a806b1f.png)

**Comment by usernamehw** [comment] 2018-09-09 12:31
Duplicate of #58156

**Closed** 2018-09-10 06:02 UTC
Labels: insiders
