### ISSUE TITLE
markdown preview zoom

### ISSUE THREAD

**Issue by GlacierStudioQ** [Microsoft/vscode#21677] opened 2017-03-02 02:31 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Spell|seanmcbreen|0.8.6|;

---

Steps to Reproduce:

1. open markdown preview
2. "ctrl" + "+" zoom the editor
3. editor will narrow and blank show on the right（编辑框会缩小，右边会出现空白，并且编辑框越来越小，空白越来越大）.

**Comment by mjbvz** [comment] 2017-03-02 02:32
Thanks. This is a duplicate of #5745 Hopefully we'll be able to get around to this with a new electron version

**Closed by mjbvz** 2017-03-02 02:32 UTC
Labels: duplicate, markdown, webview
