### ISSUE TITLE
Icon for run/debug code missing in Insiders

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode#98816] opened 2020-05-29 15:26 UTC
Issue Type: <b>Bug</b>

In the latest version of the Insiders build the icon for run/debug code button is missing.

![image](https://user-images.githubusercontent.com/48929623/83276735-10167280-a19f-11ea-9ed7-33e91a4d71f4.png)

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:45:32.560Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 5.3.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_2073082|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: brain|
|OS|Linux x64 5.3.0-51-generic|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 800)|
|Memory (System)|62.78GB (1.77GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-docker|ms-|1.2.1
remote-containers|ms-|0.118.1
remote-ssh-edit-nightly|ms-|2020.5.19620
remote-ssh-nightly|ms-|2020.5.19620
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.1.0
code-settings-sync|Sha|3.4.3
gitlens|eam|10.2.1
rainbow-csv|mec|1.7.0
python|ms-|2020.5.80290
autodocstring|njp|0.5.2
vscodeintellicode|Vis|1.2.7

</details>

**Comment by IllusionMH** [comment] 2020-05-29 18:04
/duplicate of #98704

Already fixed in latest Insiders build

**Closed** 2020-05-29 18:05 UTC
Labels: *duplicate
