### ISSUE TITLE
"editor.wordWrap": true is not working in VScode 1.9.0

### ISSUE THREAD

**Issue by heyyoyo** [Microsoft/vscode#20114] opened 2017-02-07 10:43 UTC
- VSCode Version: 1.9.0
- OS Version: Windows 7

Steps to Reproduce:
1- ALT+Z to toggle Word wrapping
2- I could see the property "editor.wordWrap" in my user settings
3- But not effect at all

It was working in previous version of VS code

**Comment by swemaniac** [comment] 2017-02-07 11:17
Yup! Me too. I'm using `"editor.wrappingColumn": -1` at the moment to disable word wrapping. It's squiggly and it's not telling me why, but it works.

**Comment by mjbvz** [comment] 2017-02-07 21:08
Closing as a duplicate of #19842

@alexandrudima's [comment](https://github.com/Microsoft/vscode/issues/19842#issuecomment-278032572) explains the new behavior

**Closed by mjbvz** 2017-02-07 21:08 UTC
Labels: duplicate

**Comment by Olanrewaju** [comment] 2017-03-05 12:34
As at VSCode 1.10.1 
To turn on wordwrap use 
"editor.wordWrap": "on", 

Full options:
/ Controls how lines should wrap. Can be:
  //  - 'off' (disable wrapping),
  //  - 'on' (viewport wrapping),
  //  - 'wordWrapColumn' (wrap at `editor.wordWrapColumn`) or
  //  - 'bounded' (wrap at minimum of viewport and `editor.wordWrapColumn`).
  "editor.wordWrap": "off",

**Comment by eric-leitzel** [comment] 2017-03-27 12:18
Thanks for your comment @Olanrewaju. I can see there is a lot action between the community and the developers on this issue.

I'm on VSCode 1.10.2 and I cannot turn off word wrap now. I can make it toggle for a short period of time then it seems to get stuck. Right now I have "editor.wordWrap": "off" but it is wrapping at the viewport.

Toggle Word Wrap (Alt+Z) was working for a few minutes. After going back and forth from file to file I noticed it would be turned on after I set it toggled it off. That is when I noticed the toggle no longer works. The setting for editor.wordWrap acting as if it were on, but it is set to off.

Any ideas?

**Comment by alexandrudima** [comment] 2017-03-27 19:05
@eric-leitzel You might be running into #21801 -- for files of odd shapes (where more than half of the text in a file is on lines longer than 1k chars). The Insiders Channel Build contains a workaround.
