### ISSUE TITLE
Need outline view like atom ide

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#34253] opened 2017-09-12 22:19 UTC
https://ide.atom.io
atom ide add features

Improved language integration

Get smarter context-aware auto-completion, code navigation features such as an outline view, go to definition and find all references. As well as hover-to-reveal information, diagnostics (errors and warnings) and document formatting.

**Comment by crper** [comment] 2017-09-13 03:06
Yes , this is great feature....expect...

**Comment by alexandrudima** [comment] 2017-09-13 09:49
Possible dup of #5605

**Comment by jrieken** [comment] 2017-09-13 09:55
Yes, duplicate of #5605

**Closed by jrieken** 2017-09-13 09:55 UTC
Labels: duplicate
