### ISSUE TITLE
Automatic curly brace closure with f-strings in python

### ISSUE THREAD

**Issue by amjass12** [microsoft/vscode#125481] opened 2021-06-04 08:16 UTC

**Comment by aeschli** [comment] 2021-06-07 13:58
Please add more details, e.g. a code sample.

**Comment by amjass12** [comment] 2021-06-13 09:58
apologies - I actually had but for some reason the main body of text wasn't posted. please see a below a code example below thank you. 

`print(f'the answer is: {')`

This is the current way in which the curly brace is interpreted in an f string. As you can see when you enter the opening curly brace, the closing one is not automatically inserted and i have to enter it manually.. it would be incredibly useful if the closing brace was automatically added  (in the same way automatic closing of brackets and braces is achieved outside of the print statement in the editor) to achieve something like:

`print(f'the answer is {}')`

having said this - this is a trivial feature request, but i find myself using this a lot

**Comment by aeschli** [comment] 2021-06-14 07:57
`{` is defined as bracket pair, also for when in strings, so I believe it should work.

**Comment by amjass12** [comment] 2021-06-14 09:23
> `{` is defined as bracket pair, also for when in strings, so I believe it should work.

Thank you for the reply! 

Hmm this doesn't for me unfortunately, is there a setting that needs to be activated?

**Comment by alexdima** [comment] 2021-06-14 12:16
`{` does autoclose in strings in general e.g.

https://user-images.githubusercontent.com/5047891/121890531-be457980-cd1a-11eb-9644-e9ac2a5b592d.mp4

But not at the position before the closing `'` e.g.

https://user-images.githubusercontent.com/5047891/121890649-dd440b80-cd1a-11eb-8c62-eae6bf27fd43.mp4

Relevant code: https://github.com/microsoft/vscode/blob/8a9ac9a8519d2b698432b58b1f1d11f339532a12/src/vs/editor/common/controller/cursorTypeOperations.ts#L585-L593

**Comment by amjass12** [comment] 2021-06-14 13:03
ha! thank you, this is really interesting - i can confirm that it works when entering before the closing `'` - funny because i have only ever really required the the braces before the closing comma (because this then creates a whitespace between the statement and the answer which is intended for visual purposes

will this be treated as a bug to fix? again this obviously isn't critical.  happy to close. 

thanks

**Comment by thebinarysearchtree** [comment] 2021-09-20 03:22
The problem is, Python uses the f character instead of a particular quote style for interpolated strings. If you add autoCloseBefore ' and ", it means that when a user types a = '{ it will auto-close to a = '{} and they may not want it to do that. With languages like JavaScript, you can have different behaviour for different quote characters. So the question is, do people want it to auto-close in that situation as well, or not?

**Comment by thebinarysearchtree** [comment] 2021-09-20 10:47
This cannot be fixed at the moment. The behaviour is controlled by the autoCloseBefore property in the language configuration file, but quotes are not appropriate for that property.

**Closed** 2022-12-11 20:36 UTC
Labels: bug, editor-autoclosing
