### ISSUE TITLE
"Cannot find a program to debug" when autoAttachChildProcesses = True

### ISSUE THREAD

**Issue by arudov** [Microsoft/vscode#45046] opened 2018-03-05 10:50 UTC
- VSCode Version: 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002)
- OS Version: Mac OS 10.13.3 (17D47)

Steps to Reproduce:

1. Use NodeJS code that forks a new process
2. set autoAttachChildProcesses to True in the Launch configuration
3. "Cannot find a program to debug" is shown

If I run another custom Launch configuration w/o autoAttachChildProcesses setting(for example I run my "Unit Tests" configuration) and then run "Launch" again everything is working correctly and the debugger is connected to a child process.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2018-03-05 11:12
How does you launch config look like?

**Comment by arudov** [comment] 2018-03-05 12:14
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/test/debug.js",
            "stopOnEntry": false,
            "args": ["run", "--appdata", "${workspaceRoot}/var"],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy",
                "--max_old_space_size=8192"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "integratedTerminal",
            "sourceMaps": true,
            "autoAttachChildProcesses": true
        },
        {
            "name": "Unit Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/test/test",
            "stopOnEntry": false,
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "integratedTerminal",
            "sourceMaps": true
        },
       // other configurations here
    ]
}
```

**Comment by weinand** [comment] 2018-03-05 12:24
Does the problem still occur if you set "autoAttachChildProcesses" to false in your "Launch" configuration?

**Comment by arudov** [comment] 2018-03-05 12:33
The problem does not occur if autoAttachChildProcesses is false.

BTW when I set "autoAttachChildProcesses:false" and then reverted it back to "autoAttachChildProcesses: true" the dialog "Select environment" with options "Node JS" and "Python" appeared. I selected "NodeJS"  and the error "Cannot find a program to debug" appeared again.

**Comment by weinand** [comment] 2018-03-05 13:02
Where does you launch.json live?

**Comment by arudov** [comment] 2018-03-05 13:05
```[project dir]/.vscode/launch.json```

**Comment by weinand** [comment] 2018-03-06 16:40
I cannot reproduce this.
Could you share the project with us (or create a simple debug.js that repros the issue)?

**Comment by jsantos98** [comment] 2018-03-06 23:25
I confirm this problem as well.

To me it happens when I'm debugging a child process created with cluster.fork().
The yellow dot on the "open lauch.json" button appears immediately after the child debugging starts.

Hope this helps
Rergards

**Comment by weinand** [comment] 2018-03-06 23:30
@jsantos98 could please you post a screenshot showing this situation?
What version of node are you using?
What OS?

@isidorn can you explain the "yellow dot on the "open lauch.json" button appears immediately after the child debugging starts" ?

**Comment by jsantos98** [comment] 2018-03-06 23:33
Sure!
Before start debug:
![image](https://user-images.githubusercontent.com/4644017/37064882-a06a26fa-2196-11e8-9a60-b1f490396828.png)

After the fork:
![image](https://user-images.githubusercontent.com/4644017/37064909-b88031f8-2196-11e8-8d72-544fec811f6f.png)

OS: Windows 10 x64
Node 8.9.4 LTS

**Comment by jsantos98** [comment] 2018-03-06 23:50
I've recorded a gif (my first one, so have that in mind :) )
![visualstudio_clusterdebugproblem](https://user-images.githubusercontent.com/4644017/37065492-029a8534-2199-11e8-8950-a09e117afbb6.gif)

**Comment by weinand** [comment] 2018-03-07 07:40
@jsantos98 how does your launch config look like?

**Comment by arudov** [comment] 2018-03-07 07:40
@jsantos98 exactly the same happens in my case.

@weinand, unfortunately, I could not share my private project but looks like @jsantos98 already provided the working code. 

A friend of mine was able to reproduce the issue using my project on Ubuntu 16.04.4 LTS and VSCode 1.20.1(f88bbf9137d24d36d968ea6b2911786bfe103002)

**Comment by isidorn** [comment] 2018-03-07 10:21
@weinand yellow dot on the "open launch.json" appears when no launch configuratino is selected (this usualy indicates launch.json should be fixed). However in this case it seems to be a bug - but should not affect the main issue here.

**Comment by weinand** [comment] 2018-03-07 10:37
@isidorn and if no launch configuration is selected, you pass an empty launch config to the resolveDebugConfiguration method, right? This would explain the "Cannot find a program to debug" error message.

What I don't understand:
why is "having no launch configuration selected" an issue at all? The user could successfully launch the initial launch config "Launch". Then the "autoAttach" feature kicks in: it just calls `startDebugging`with an in-memory launch configuration. It does not depend on the launch.json in any way.

**Comment by jsantos98** [comment] 2018-03-07 11:00
@weinand, the config looked (already removed the sample project) like this:

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
	"type": "node",
	"request": "launch",
	"name": "Cluster",
	"program": "${workspaceRoot}/src/test/test.js",
	"autoAttachChildProcesses": true
      },
   ]
}
```

**Comment by weinand** [comment] 2018-03-07 12:55
Can anyone reproduce this in the latest Insiders?

**Comment by arudov** [comment] 2018-03-07 13:09
@weinand the issue is not reproduced in the latest Insiders build on my Mac! looks like it is fixed! Thanks u!

**Comment by weinand** [comment] 2018-03-07 13:12
Thanks for verifying.
Let's see whether @jsantos98 sees this too...

**Comment by jsantos98** [comment] 2018-03-07 14:43
@weinand the issue no longer happens on the latest insiders build for Windows x64.
Thanks!

**Comment by weinand** [comment] 2018-03-07 14:45
Ok, let's close this then.

**Closed by weinand** 2018-03-07 14:45 UTC
Labels: bug, debug
