### ISSUE TITLE
VSCode sets VSCODE_LOGS on spawned 3rd party processes

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#64897] opened 2018-12-12 16:40 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 10 RS5 x64

Steps to Reproduce:

1.Clone VSCode
2.Setup to build VSCode
3. Build VSCode
4. Launch VSCode to under debugger

Results -> Logging exceptions occur (such as)

```
Error: Failed opening file C:\Users\emclemen\AppData\Roaming\Code\logs\20181209T201113\cli.log for writing: Permission denied
    at new RotatingLogger (C:\Users\emclemen\AppData\Local\Programs\Microsoft VS Code\_\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (C:\Users\emclemen\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\code\node\cliProcessMain.js:70:564)
    at Object.t.main (C:\Users\emclemen\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\code\node\cliProcessMain.js:177:299)
    at C:\Users\emclemen\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\code\node\cli.js:123:343
```

Does this issue occur when all extensions are disabled?: Yes

The log-file service (src\vs\platform\environment\node\environmentService.ts) is setting the log-file directory path into the process environment block.

```
    constructor(private _args: ParsedArgs, private _execPath: string) {
        if (!process.env['VSCODE_LOGS']) {
            const key = toLocalISOString(new Date()).replace(/-|:|\.\d+Z$/g, '');
            process.env['VSCODE_LOGS'] = path.join(this.userDataPath, 'logs', key);
        }

        this.logsPath = process.env['VSCODE_LOGS']!;
    }
```

As a result, if VSCode ever gets reloaded (which only really reloads a portion of VSCode), or launches a process (in the case of debugging), then the logging tries to open up a file that is already in use. The permission denied you are getting is not really an accurate error from the spdlog. What it is really getting is an sharing violation.

I believe the fix for this is quite simple which is to store a static inside the class rather than trying to use the environment block.

```
    private static processLogFilePath : string | undefined;

    constructor(private _args: ParsedArgs, private _execPath: string) {
        if (!EnvironmentService.processLogFilePath) {
            const key = toLocalISOString(new Date()).replace(/-|:|\.\d+Z$/g, '');
            EnvironmentService.processLogFilePath = path.join(this.userDataPath, 'logs', key);
        }

        this.logsPath = EnvironmentService.processLogFilePath;
    }
}
```

**Comment by GabeDeBacker** [comment] 2018-12-13 15:35
This should also cover that it also affects instances of where VSCode launches itself (or an extension launches VSCode) since the newly launched instances cannot create log files in the same path.

**Comment by sandy081** [comment] 2018-12-13 15:46
@GabeDeBacker What does this step mean

`Launch VSCode to under debugger` ?

**Comment by GabeDeBacker** [comment] 2018-12-13 16:42
Typo. That was supposed to say "When debugging VSCode from VSCode". This occurs during development of VSCode as well is what this was supposed to capture.

**Comment by joaomoreno** [comment] 2018-12-14 10:03
@GabeDeBacker The fact that child processes inherit the parent's environment is not a coincidental one. It's actually a pretty decent way of controlling a specific environment for a process tree.

The problem occurs when external processes are spawned from that tree: the environment needs to get back to the state that it was at the tree's root. This is what @Tyriar does in the terminal, for example.

> What is happening is that any processes launched from VSCode (even other VSCode proceses in the case of debugging say an extension) end up trying to use the same logging path.

Is debugging the only execution path that makes you hit this issue?

**Comment by sandy081** [comment] 2018-12-20 10:36
@GabeDeBacker I tried to launch VS Code from VS Code dev set up using the launch `Launch VS Code` and I do not see any errors you described. Am I missing any steps here?

**Comment by sandy081** [comment] 2019-01-10 15:08
Ok, now I understand the inheritance of these environment variables to the child process.

**Comment by GabeDeBacker** [comment] 2019-01-26 22:02
@sandy081 - So are there plans to address this?

**Comment by Tyriar** [comment] 2019-01-27 15:38
FYI I fixed this once and for all for the terminal:

https://github.com/Microsoft/vscode/blob/9301aefe0f5b8c2505421ee57721e5bcfde2e117/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L54-L70

**Comment by joaomoreno** [comment] 2019-01-28 08:50
I am tempted to just do that for all places where we spawn processes, instead of bigger change of letting go environment variables at all.

@Tyriar Could you organize with @weinand and @alexr00 to have a single place where this code would live and Terminal, Debug and Tasks would all utilize it?

**Comment by Tyriar** [comment] 2019-01-28 15:44
@alexr00 @weinand I moved the function to `sanitizeProcessEnvironment` in processes.ts, please pick it up when you can.

**Comment by GabeDeBacker** [comment] 2019-02-01 16:40
As a note, you should be launching processes using a fresh user environment block. VSCode could inherit all kinds of badness in the environment block as it does not know the process chain that led up to its launching.

Typically looking for and removing "what you don't like" is not the correct approach. You should start with what you know you like.

**Comment by GabeDeBacker** [comment] 2019-02-01 16:46
To be very clear by a "clean user environment block" we do this for our build environment for Windows (this is C# pinvoke - error handling removed). This removes ALL traces of previous processes environment variables.

            IntPtr envBlock = IntPtr.Zero;
            IntPtr processToken = IntPtr.Zero;

                // Open the process token for "query, duplicate and impersonate" so that it can be used by
                // CreateEnvironmentBlock to obtain the user's security ID (sid) and construct things like the
                // USERNAME, USERDOMAIN, etc. environment variables.
                if (!OpenProcessToken(GetCurrentProcess(), TokenFlags.TOKEN_DUPLICATE | TokenFlags.TOKEN_QUERY | TokenFlags.TOKEN_IMPERSONATE, ref processToken))
                {
                    throw new Win32Exception(Marshal.GetLastWin32Error());
                }

                if (!CreateEnvironmentBlock(out envBlock, processToken, bInherit: false))
                {
                    throw new Win32Exception(Marshal.GetLastWin32Error());
                }

**Comment by Tyriar** [comment] 2019-02-01 17:22
Maybe we should be doing that on Windows, it's a pretty big change and I'm not sure what it would break though. For example extensions may rely on the fact that the window's environment is inherited?

**Comment by GabeDeBacker** [comment] 2019-02-07 17:42
@Tyriar - Relying on the Windows environment can actually wreak havoc on applications. In general we advise folks to not use environment variables as an IPC mechanism. However, yes, some environment variables are required hence why we create an environment block based on what the user has set. (which is the best we can do)

**Comment by GabeDeBacker** [comment] 2019-07-15 21:37
@Tyriar 
This still happens for me every time I debug the extension. You can see this in the console logs of the developers tools while debugging the extension.

We are also seeing it reported in our telemetry as well.

**Comment by Tyriar** [comment] 2019-08-19 23:03
Duplicate of https://github.com/microsoft/vscode/issues/38428?

**Comment by connor4312** [comment] 2020-11-11 22:32
Found this grooming issues. We've had cases where this happened before; right now in js-debug we're unsetting ELECTRON_RUN_AS_NODE and the app insights environment variable, but in the linked commit I adopt the more thorough sanitization that Daniel added to VS Code which should fix the debugging case, which looks like the only remaining problem here.

**Closed** 2020-11-11 22:42 UTC
Labels: bug, tasks
