### ISSUE TITLE
feature request: allow skipping VM* files in a debug session

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#61648] opened 2018-10-23 19:35 UTC
related: #31537 #49142

# problem

- `VMXXX`/`VM*` eval scripts cannot be ignored in a debug session, leading to disruptive and difficult-to-navigate debug sessions

# solution

- permit `skipFiles` to ignore `VM*`/`eval`'d scripts

# discussion

- [here's a minimal, reproducible example project](https://github.com/cdaringe/vscode-skip-vm-files)

consider the following `launch.json` block for, say, an Attach launch config:

```jsonc
      "skipFiles": [
        "<node_internals>/**/*.js",
        "<node_internals>/**/*",
        "*VM*"
      ]
```

unfortunately, this still allows debug sessions inside of VM* "files" (node 10.12.0).  if any code, like old skool `lodash`'s `createIterator`, evals anything, your step forces you into the VM* files eval context, not your desired, non-evaly next piece of code.  `--nolazy` mode with node launches help for anything that is run immediately on import, but that doesn't get anyone too far

**Comment by weinand** [comment] 2018-10-24 11:05
My proposal is to list the VM* scripts under "<node_internals>" so that they are covered by the "<node_internals>" glob patterns. This is what I do in node-debug legacy.

If we want to go with another pseudo root "<eval>" then node-debug2 needs to support "<eval>" in its glob patterns (and node-debug legacy needs to adapt this for consistency).

**Comment by roblourens** [comment] 2018-10-24 16:10
I think they should have their own name, since they aren't node internals. This is a duplicate of https://github.com/Microsoft/vscode/issues/31537. Maybe I should do it for November

**Closed by roblourens** 2018-10-24 16:10 UTC
Labels: debug, feature-request, under-discussion
