### ISSUE TITLE
Debug Console Flickering

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [microsoft/vscode#108677] opened 2020-10-14 19:04 UTC
After the September 2020 update, the debug console is flickering.

**Comment by szmcdull** [comment] 2020-10-16 08:58
I encounter this very annoying issue, even with version 1.50.1.
Whenever there is something output to the debug console, it auto scrolls to somewhere exceeds the bottom. The position is not constant. So it is flickering with random blank area.
I'm debugging Golang codes. Not tested against other languages yet.

**Comment by raohag** [comment] 2020-10-20 13:02
This happens with Java as well

**Comment by isidorn** [comment] 2020-10-22 15:24
Duplicate of https://github.com/microsoft/vscode/issues/107704
If you have exact reproducable steps without Dart, just pure JS or Python would be great so I repro on my machine. Thank you

**Closed by isidorn** 2020-10-22 15:24 UTC
Labels: debug
