### ISSUE TITLE
VSCode doesn't refresh file tree after updating FileSystemProvider (regression in 1.33 insiders)

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#71423] opened 2019-03-29 00:25 UTC
- VSCode Version: 1.33.0 Insiders

*Steps to Reproduce:*

In Live Share collaboration session, the following scenario is broken in Insiders and works in stable VSCode
1. Host starts a read-only collaboration session
2. Guest joins that session

*Expected:*
The guest gets the file tree in the Explorer after joining.

*Actual:*
The guest doesn't get the file tree in the Explorer after joining.

This is what happens with the `FileSystemProvider` on the guest side in this scenario:
1. Live Share registers file system provider for vsls: scheme as read-write
1. Guest joins the collaboration session
1. VSCode calls stat on these URIs. These calls await till the join is complete and do not complete.
    * stat vsls:/
    * stat vsls:/.git/config
    * stat vsls:/.git/config
    * stat vsls:/node_modules
    * stat vsls:/
    * stat vsls:/
    * stat vsls:/
    * stat vsls:/.vscode
1. Guest finds out that the session is read-only. It disposes the file system provider registration for vsls: and registers a new provider for vsls: with `isReadonly: true`.
1. The previous calls to stat resolve with this result:
  ```
 <vscode.FileStat>{
            type: vscode.FileType.Directory,
            mtime: 0,
            ctime: 0,
            size: 0
        }
 ```
After that VSCode works with the new (read-only) file system provider reads some file with it, but it never calls stat on / again, and it doesn't read the root directory either. The user then sees empty tree in the Explorer.

In the stable version, VSCode does read the root directory again after we register another provider for vsls: scheme.

**Comment by IlyaBiryukov** [comment] 2019-03-29 00:26
cc @bpasero

**Comment by bpasero** [comment] 2019-03-29 07:38
@IlyaBiryukov I just tried to reproduce this but cannot. Here is my setup (macOS):
* have LiveShare installed and setup in VSCode insiders
* have LiveShare installed and setup running (VSCode) "out of sources"
* start a LiveShare session in insiders
* join from the other one that is running "out of sources"
* => it works
* do the same with a readonly session
* => it works

Can you give me more exact steps how to reproduce? And are you able to reproduce this with a setup where you have insiders sharing and running out of sources joining? Because then I would like to ask you to try a change to see if it makes a difference.

**Comment by isidorn** [comment] 2019-03-29 08:17
We did change behavior which might effect this in Explorer. More details can be found here https://github.com/Microsoft/vscode/issues/71163

Here's my comment from that issue 
"We refresh the explorer in this case since the file system provider might unregister and register itself to make itself readonly. This requires that all the file stats are refreshed.
To optimaze that I changed that I only refresh the explorer if the file system provider got re-registered. I know that by rembering the schemes of the register providers thus far."

However this should not break your case since you are re-registering.
@IlyaBiryukov can you please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/292e59f3678ef0b9a6c7d920cd00abf9c26c8ccc/src/vs/workbench/contrib/files/common/explorerService.ts#L103) and check if the `fileSystemProviderSchemes` has your vsls scheme the second time you register.

I will now try to reproduce like @bpasero

**Comment by isidorn** [comment] 2019-03-29 10:08
I just tried reproducing using @bpasero steps and could not reproduce.
Since we are last day of endgame and LiveShare is GA soon I have decided to revert my fix.
However I still want to apply that fix for the next release. So please provide more details @IlyaBiryukov 
Thus moving this issue to april. And pushing a revert for https://github.com/Microsoft/vscode/commit/bb35a1d223c04425c73bfa7bd4ef865018f8fe4c

**Comment by IlyaBiryukov** [comment] 2019-03-29 20:40
@bpasero Here is the original bug, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/826969/

VSCode Build: 1.33.0-insider
VSCode Extension Build: 0.3.1426
Affected Project Type: All
Repro Rate: 80%

Repro on current published extension 0.3.1326:  Yes

Operation System Information: Win10, LTS for Ubuntu 16.04.4, Mac Mojave version 10.14.3

MoreInfo:
This issue can be reproduced when guest joins the read-only session for the first time.

Repro Steps:
1. Host: Share a read-only session from VSCode/VS
2. Guest: Join collaboration session with shared link by VSCode
3. Guest: Observe the file tree

Expected: 
The file tree can be showed on the workspace after guest joins the session. 

Actual:
No file tree shows on the workspace after guest joins read-only session, if guest leaves the session and join the session again, this issue cannot be reproduced.

**Comment by IlyaBiryukov** [comment] 2019-03-29 22:01
@isidorn I put a breakpoint where you asked, and reproduced the issue. I hit the breakpoint 3 times. I assume these were: 
1. Provider registartion where it was not read-only. 
1. Unregistration
1. Provider registration where it is read-only

Here are the values for `e`, `fileSystemProviderSchemes` and the call stacks for these three hits:
```
e = Object {added: true, scheme: "vsls", provider: RemoteFileSystemProvider}
this.fileSystemProviderSchemes = Set(0) {}

disposables.push.fileService.onDidChangeFileSystemProviderRegistrations.e (c:\src\vscode\src\vs\workbench\contrib\files\common\explorerService.ts:103)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
registerProvider (c:\src\vscode\src\vs\workbench\services\files2\common\fileService2.ts:76)
RemoteFileSystemProvider (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:82)
$registerFileSystemProvider (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:35)
_doInvokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:399)
_invokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:384)
_receiveRequest (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:304)
_receiveOneMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:226)
RPCProtocol._protocol.onMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:101)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
deliverMessages (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:392)
source (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:399)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
_receiveMessage (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:678)
PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:549)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
acceptChunk (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:212)
ProtocolReader._register._socket.onData.data (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:173)
listener (c:\src\vscode\src\vs\base\parts\ipc\node\ipc.net.ts:24)
```

```
e = Object {added: false, scheme: "vsls", provider: RemoteFileSystemProvider}
this.fileSystemProviderSchemes = Set(1) {"vsls"}

disposables.push.fileService.onDidChangeFileSystemProviderRegistrations.e (c:\src\vscode\src\vs\workbench\contrib\files\common\explorerService.ts:103)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
lifecycle_1.combinedDisposable.lifecycle_1.toDisposable (c:\src\vscode\src\vs\workbench\services\files2\common\fileService2.ts:83)
dispose (c:\src\vscode\src\vs\base\common\lifecycle.ts:42)
first.forEach.d (c:\src\vscode\src\vs\base\common\lifecycle.ts:22)
dispose (c:\src\vscode\src\vs\base\common\lifecycle.ts:22)
dispose (c:\src\vscode\src\vs\base\common\lifecycle.ts:38)
dispose (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:86)
dispose (c:\src\vscode\src\vs\base\common\lifecycle.ts:26)
$unregisterProvider (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:39)
_doInvokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:399)
_invokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:384)
_receiveRequest (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:304)
_receiveOneMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:226)
RPCProtocol._protocol.onMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:101)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
deliverMessages (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:392)
source (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:399)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
_receiveMessage (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:678)
```

```
e = Object {added: true, scheme: "vsls", provider: RemoteFileSystemProvider}
this.fileSystemProviderSchemes = Set(1) {"vsls"}

disposables.push.fileService.onDidChangeFileSystemProviderRegistrations.e (c:\src\vscode\src\vs\workbench\contrib\files\common\explorerService.ts:103)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
registerProvider (c:\src\vscode\src\vs\workbench\services\files2\common\fileService2.ts:76)
RemoteFileSystemProvider (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:82)
$registerFileSystemProvider (c:\src\vscode\src\vs\workbench\api\browser\mainThreadFileSystem.ts:35)
_doInvokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:399)
_invokeHandler (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:384)
_receiveRequest (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:304)
_receiveOneMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:226)
RPCProtocol._protocol.onMessage (c:\src\vscode\src\vs\workbench\services\extensions\node\rpcProtocol.ts:101)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
deliverMessages (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:392)
source (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:399)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
_receiveMessage (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:678)
PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:549)
fire (c:\src\vscode\src\vs\base\common\event.ts:584)
acceptChunk (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:212)
ProtocolReader._register._socket.onData.data (c:\src\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:173)
listener (c:\src\vscode\src\vs\base\parts\ipc\node\ipc.net.ts:24)
```

**Comment by IlyaBiryukov** [comment] 2019-03-29 22:32
One possible explanation of the bug may be that Explorer tree just waits for the first stat() to finish, and Live Share changing the file system provider underneath doesn't invalidate the first call to stat(), neither does it make Explorer tree issue another call after the first returns with empty results.

**Comment by IlyaBiryukov** [comment] 2019-03-29 23:17
As a workaround, Live Share may issue a command to refresh Explorer some time after it switched the providers and original stat() has finished.

**Comment by isidorn** [comment] 2019-04-01 12:10
@IlyaBiryukov thanks for providing more details and for investigating.
Becuase there were no other changes on the explorer side I am pretty sure this is due to the File System refactoring. Thus forwarding to @bpasero 
After discussing this with @dbaeumer it might be a duplicate of https://github.com/Microsoft/vscode/issues/71302

As @bpasero commented there

"please do not make any assumptions about which stat call comes first or second. The IFileService is a service that is now being used in lots of places, e.g. to load the configuration very early on (which probably is the call you see for the .vscode folder). The explorer is coming only a lot later to resolve itself and even other services might use the file service to resolve things (like output channels)."

@IlyaBiryukov also when and where do you register your file system provider

As for the workaround to refresh the explorer, you can always do that as a temporary fix.

**Comment by bpasero** [comment] 2019-04-01 13:40
Sorry without being able to reproduce, I am not sure how I can be of help. @IlyaBiryukov let me know if you need further assistance otherwise I will go ahead and close this issue.

**Comment by bpasero** [comment] 2019-04-01 13:43
@IlyaBiryukov are you maybe on a different OS than mac? I only tried macOS so far.

**Closed** 2019-04-16 17:13 UTC
Labels: needs more info
