### ISSUE TITLE
Go to definition, Find references, Go to symbol do not work anymore in v1.27.0-insider

### ISSUE THREAD

**Issue by nahttran** [Microsoft/vscode#56804] opened 2018-08-20 08:39 UTC
- VSCode Version:1.27.0-insider
- OS Version: Windows 10
- Commit: 00649474f2e43a84c61ddbbbc356060257328372

Steps to Reproduce:

1.  Navigate to a variable and press shortcut F12 or Alt+F12 => no definition found ???
2.  Navigate to a file and press shortcut Ctrl+Shift+o (go to symbol) => the symbol list is shown but empty.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-08-20 11:55
Duplicate of #56792. Should be fixed in next insiders

**Closed by mjbvz** 2018-08-20 11:55 UTC
Labels: editor, editor-contrib
