### ISSUE TITLE
Opens on wrong Desktop after restart

### ISSUE THREAD

**Issue by mloepfe** [microsoft/vscode#138319] opened 2021-12-02 07:44 UTC
Issue Type: <b>Bug</b>

Hi

I have multiple Vcode windows open, each on a different virtual desktop, on a Mac. 

When I restart the tool (for the frequent updates), the window open all on the current desktop instead of the one they where open before.

Thanks for fixing this

VS Code version: Code - Insiders 1.63.0-insider (0cc0904c565399781defa830facf43141db8b6f3, 2021-12-01T05:13:35.988Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 90619be2-ec31-4fdb-b6a5-38d26b6660e4|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment] 2021-12-03 06:33
Same as https://github.com/microsoft/vscode/issues/62920. Electron needs to address this by giving an API to figure out in which space a window was opened and by giving an API to open a window in a space.

**Comment by yume-chan** [comment] 2022-03-11 01:52
Duplicate of #123517

**Comment by deepak1556** [comment] 2022-12-13 10:56
Merging to https://github.com/microsoft/vscode/issues/123517

**Closed by deepak1556** 2022-12-13 10:56 UTC
Labels: upstream, electron
