### ISSUE TITLE
Auto import should omit default exports

### ISSUE THREAD

**Issue by bali182** [Microsoft/vscode#39564] opened 2017-12-04 16:25 UTC
- VSCode Version: **1.18.1**
- OS Version: **Windows 10** (most likely platform independent)

Steps to Reproduce:

When requesting autocomplete the new auto import shows `default` exports for the `default` keyword.

1. Have a workspace where you have at least 1 `default` export
2. Start typing `default` in any context
![export-default](https://user-images.githubusercontent.com/3879181/33563283-67b0df4a-d90f-11e7-879d-208b134c6897.gif)

The feature is really nice but in this context it would be better to omit these suggestions since it produces syntax errors, and is not particularly useful when you only want to save a few keystrokes on typing out `default`

Reproduces without extensions: **Yes**

**Comment by mjbvz** [comment] 2017-12-04 18:55
/duplicate of https://github.com/Microsoft/TypeScript/issues/19877

Should already be fixed in insiders

**Closed by mjbvz** 2017-12-04 18:55 UTC
Labels: javascript
