### ISSUE TITLE
the "selected" reference always goes back to the begnning when searching globally and make some changes

### ISSUE THREAD

**Issue by sy19890515** [microsoft/vscode#224113] opened 2024-07-28 07:34 UTC
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

Issue:
When I opened more than one files and search for some keyword globally, and if it returns some results, I may use the shortcut for "Go to Next Reference" (in my case, it's F4) to locate the first reference.
Sometimes, I would want to change the text at that location, sometimes I want to keep looking for the later references and see if those need to be changed.
Let's say that I searched for some keyword, and I see that the first reference is correct, and the second is wrong, so I would press F4 twice to go to the second reference and change it. Then I want to keep looking for the rest of the references and see if there are more mistakes. In some versions back (I remember in 1.85.* or before, not 100% sure), even though I changed the text at the second reference, the "selected" reference would remain there, so if I press F4 again, it would go to the "previously third, now second" reference. However, in newer versions (maybe since 1.86.* or 1.87.* or 1.88.*), it's like the "selected" reference would go back to the beginning, then every time I make a change, I cannot continue from where I am, I have to start all over from the beginning.
![image](https://github.com/user-attachments/assets/2ff30eb2-8c93-48ae-97a0-0259aacd3135)
![image](https://github.com/user-attachments/assets/0bf2c30d-d2c2-4c40-b815-c02cfb5d21dc)
![image](https://github.com/user-attachments/assets/31cec0a6-ae73-4535-bcc0-7cc35658356b)
You may see in the above screenshots:
1. I searched for the quotation marks in some subtitle files
2. I deleted the third occurrence
3. the "selected" reference highlight disappeared
4. I pressed F4 again, the first reference was selected, instead of the "previously fourth, now third" reference
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.22GB free)|
|Process Argv|--crash-reporter-id 2e325794-7e8f-42ba-b875-ae38281e1ddd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-subtitles|ast|0.4.0
vscode-sql-beautify|cla|0.3.23
gitlens|eam|15.2.3
shell-format|fox|7.2.5
vdf|GEE|0.0.7
remotehub|Git|0.62.0
githd|hui|2.3.5
openvpn|idl|0.3.5
autopep8|ms-|2024.0.0
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.14
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
sonarlint-vscode|Son|4.7.0
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31101459
ccpltc:31103427
pythonrstrctxt:31103193
hdi1a554:31097393
wkspc-onlycs-c:31102393

```

</details>

**Comment by andreamah** [comment] 2024-09-03 18:32
I believe that this is a duplicate of https://github.com/microsoft/vscode/issues/206511
/duplicate https://github.com/microsoft/vscode/issues/206511

**Closed** 2024-09-03 18:33 UTC
Labels: *duplicate
