### ISSUE TITLE
[loc][Query] Typo in source text for "Allow debugging and profiling of extensions. Check the developer tools for the connection uri."

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#48139] opened 2018-04-18 15:13 UTC
For string below community member asked to fix incorrect source text. Can you please confirm and fix? Thanks!

**Original comment**
"uri" should be "URI"by  mjcheetham

**Context**
src/vs/platform/environment/node/argv:English (en):plaintext:inspect-extensions

**Resource**
vs_platform

**String Hash**
562d2db7822f0c319e4846de58b4dc34

**String text**
Allow debugging and profiling of extensions. Check the developer tools for the connection uri.

**Comment by bpasero** [comment] 2018-04-19 08:30
Duplicate of https://github.com/Microsoft/vscode/issues/48140

**Closed by bpasero** 2018-04-19 08:30 UTC
Labels: i18n
