### ISSUE TITLE
Can't type attributes in HTML

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#165913] opened 2022-11-09 12:51 UTC
* type ` type="module`
* expected: ` type="module` or ` type="module"` with auto-closing pairs
* 🐛 actual: ` type=""module`

https://user-images.githubusercontent.com/5047891/200834747-ff9d2dee-4d6d-4db8-9160-8bab47538a29.mp4

**Comment by aeschli** [comment] 2022-11-28 13:42
Duplicate of https://github.com/microsoft/vscode/issues/140698
After typing `=` the quotes are auto-inserted and adding the additional `"` brings you outside the quotes.

**Closed by aeschli** 2022-11-28 13:42 UTC
