### ISSUE TITLE
HTML indentation bug when using inline styles

### ISSUE THREAD

**Issue by battmanz** [Microsoft/vscode#19106] opened 2017-01-24 04:33 UTC
Any tags that follow a tag using inline styles will not have the property indentation -- they will be to the far left.

- VSCode Version: 1.8.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. The following html was formatted using the keyboard shortcut. Notice that all elements have the appropriate indentation.
<img width="383" alt="screen shot 2017-01-23 at 9 26 31 pm" src="https://cloud.githubusercontent.com/assets/1054833/22234110/b6f7526e-e1b2-11e6-95e7-1f65382955b3.png">

2. Now, I'll just make one change: on the third `div` with a class of `foo`, I'll add an inline style. Afterward, I'll format again using the keyboard shortcut. Notice that the proper indentation is not preserved on tags (including closing tags) that follow the inline style.
<img width="527" alt="screen shot 2017-01-23 at 9 32 09 pm" src="https://cloud.githubusercontent.com/assets/1054833/22234208/85346d06-e1b3-11e6-98c4-b721a9f6d090.png">

**Comment by aeschli** [comment] 2017-01-24 10:59
duplicate of #17849

**Closed by aeschli** 2017-01-24 10:59 UTC
