### ISSUE TITLE
Configure tasks "other" does not allow selection of installed languages

### ISSUE THREAD

**Issue by leemke** [microsoft/vscode#96415] opened 2020-04-28 13:55 UTC
Issue Type: <b>Feature Request</b>

New to VScode.  Created a folder; saved as a workspace. Then selected
"configure tasks". Did not see C++ or Arduino, or other environments (i.e.) Python. Selected more. Expected a list of other existing environments.

Just received a "echo; shell; echo Hello" configuration.  Not very helpful. 
Would like to see a dropdown list of other environments and/or extenstion available. 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

**Comment by alexr00** [comment] 2020-04-28 16:25
Duplicate of https://github.com/microsoft/vscode/issues/66308

**Closed** 2020-04-28 16:26 UTC
Labels: *duplicate, tasks
