### ISSUE TITLE
References issue

### ISSUE THREAD

**Issue by smarzic** [microsoft/vscode#87167] opened 2019-12-17 11:58 UTC
I have set `"javascript.referencesCodeLens.enabled"` to `true` to display refrences for functions. Since the last update (unwanted) references are displayed for object properties. 

In example below line comments (`//`) are positions of all references that appear. Before the update only the first two references would appear.

```javascript
import React, { Component } from "react";
//
export default class Example extends Component {
    //
    constructor() {
        this.state = {
            //
            one: "1",
            //
            two: "2",
            //
            three: "3"
        }
    }
}
```

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.6
gitlens|eam|10.2.0
prettier-vscode|esb|3.14.0
Clarion|Fus|1.0.18

</details>

**Comment by mjbvz** [comment] 2019-12-18 19:26
Duplicate of #86495

**Closed by mjbvz** 2019-12-18 19:26 UTC
Labels: typescript
