### ISSUE TITLE
vscode doesn't replace problems in problems view after they are fixed

### ISSUE THREAD

**Issue by josiahbgrace** [Microsoft/vscode#17953] opened 2016-12-31 00:05 UTC
- VSCode Version: 1.8.0
- OS Version: Mac OS El Capitan

Steps to Reproduce:

1. Write a custom problem matcher
2. Run problem matcher, it produces some errors
3. Fix those errors
4. Run problem matcher again
5. The old errors are still there, they only reset on full quit/reinstall.

**Comment by sandy081** [comment] 2017-01-03 09:33
@josiahbgrace May I know if the problem matcher is generating the problems again?

**Comment by josiahbgrace** [comment] 2017-01-03 18:19
It is not generating problems again. The same minimal example above is reproducible.

```
function x() {
    return 5;<trailing_space>
}
```

```
Trailing spaces not allowed. (no-trailing-spaces)
```

Fix problem. Rerun the task.

```
Trailing spaces not allowed. (no-trailing-spaces)
```

**Comment by sandy081** [comment] 2017-01-04 09:07
I guess existing problems are not removed. @jrieken @dbaeumer FYI

**Comment by dbaeumer** [comment] 2017-01-09 10:09
@josiahbgrace I can't reproduce this. The task framework clears the problems per [owner, resource] when the task is run again. Can you please share a workspace exposing the behavior.

![cast](https://cloud.githubusercontent.com/assets/1931590/21763036/1e9646a8-d65c-11e6-89a4-99747c3b315b.gif)

**Comment by fearthecowboy** [comment] 2017-03-19 01:27
I'm seeing this kind of behavior too from time to time.  

The only solution seems to be exiting vscode and restarting.

I can't seem to get a repro that's consistent.

**Comment by dbaeumer** [comment] 2017-04-26 14:04
I still can't reproduce this. Without a test case that demonstrates the problem this is hard to track down and to fix. I will close the issue. Please ping if steps are available on how to reproduce this.

**Closed by dbaeumer** 2017-04-26 14:04 UTC
Labels: needs more info, tasks
