### ISSUE TITLE
Unable to type

### ISSUE THREAD

**Issue by Cdixon855** [Microsoft/vscode#65887] opened 2019-01-01 17:36 UTC
Issue Type: <b>Bug</b>

Opening files I created on my macbook in workspace, none are allowing me to edit. I made a new file independent of the others, and it seems to work fine. How do I make the others work? I am only using scss and html files. They were working prior, and now they do not.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
vscode-markdownlint|Dav|0.22.0
python-preview|don|0.0.4
githistory|don|0.4.4
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
gitlens|eam|9.2.4
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
sublime-keybindings|ms-|4.0.0
team|ms-|1.144.1
vscode-yaml|red|0.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.3.1
sass-indented|rob|1.5.1
python|tht|0.2.3
vscodeintellicode|Vis|1.1.2
vim|vsc|0.17.3
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by egamma** [comment] 2019-01-02 11:20
@Cdixon855 I'm unable to reproduce this given the information above. 

What exactly do you mean by 
>none are allowing me to edit

I've used the following steps from a console/terminal:

- touch test.html
- code test.html

The file can be edited without any problems.

**Comment by rogeramitchell** [comment] 2019-01-03 17:21
This has happened to me with 2 separate projects today. Keyboard shortcuts work as expected, although any files in the project do not accept keyboard inputs where the cursor is.

Following @egamma's steps did not work if that project was open (and `code test.html` opens in that window), however closing VS Code and executing `code test.html` again allows for editing that file.

Closing VS Code again, dragging the project directory onto the VS Code in macOS dock, and opening that file does not allow for editing. However, if VS Code is closed with that file as an open tab, and then the project is opened again, it allows for editing the file.

[Here's a screen recording of the issue occurring.](http://recordit.co/QOApQ8Mzk7)

VS Code version: Version 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T17:58:06.754Z)
OS version: macOS Mojave 10.14.2 (18C54)

Extensions

- DavidHelmer.mavensmate
- esbenp.prettier-vscode
- ms-vscode.sublime-keybindings
- salesforce.salesforcedx-vscode
- salesforce.salesforcedx-vscode-apex
- salesforce.salesforcedx-vscode-apex-debugger
- salesforce.salesforcedx-vscode-apex-replay-debugger
- salesforce.salesforcedx-vscode-core
- salesforce.salesforcedx-vscode-lightning
- salesforce.salesforcedx-vscode-visualforce
- wesbos.theme-cobalt2

**Comment by alexandrudima** [comment] 2019-01-07 14:39
@rogeramitchell I can see in the screen recording that in some cases you cannot type but unfortunately I cannot reproduce using a clean installation of VS Code with the steps you have provided.

![kapture 2019-01-07 at 15 38 10](https://user-images.githubusercontent.com/5047891/50773866-4abdf900-1292-11e9-8fcb-396b7c0b3779.gif)

Does this reproduce for you when disabling all extensions?

**Comment by rogeramitchell** [comment] 2019-01-08 13:46
@alexandrudima disabling all extensions, I am unable to reproduce. I re-enabled all extensions, and was able to reproduce. I disabled only this extension `salesforce.salesforcedx-vscode-lightning`, and was unable to reproduce. I'll open an issue with Salesforce as they are the maintainer of that extension. Also, I'll try disabling all extensions in the future to see if the issue persists. Thanks for your help, and such an amazing code editor.

**Comment by alexandrudima** [comment] 2019-01-08 13:49
:+1: Thank you for following up @rogeramitchell

**Closed by alexandrudima** 2019-01-08 13:49 UTC
Labels: needs more info
