### ISSUE TITLE
Clicking the multi-diff icon opens a new editor on each click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199288] opened 2023-11-28 10:04 UTC
Testing #199155

I think the same editor should reveal when opening it, otherwise I get the same editor opened multiple times:

![image](https://github.com/microsoft/vscode/assets/900690/a5e9f8a4-bcde-4b01-beff-51a7eb4daf98)

**Comment by hediet** [comment] 2023-11-28 10:09
Currently, this is by design, because an editor does not have a chance to refresh its file list (the `input` has a static file list, computed at the time when the command to open a new multi diff editor is invoked).
Closing in favor of #199291

**Closed by hediet** 2023-11-28 10:09 UTC
