### ISSUE TITLE
Error info tooltip window on hover  disappears immediately  when the code is scrolled to the right,  and is unreadable in general

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#61936] opened 2018-10-27 10:51 UTC
Issue Type: <b>Bug and Suggestions</b>

Having a long line with an error in it (in my case Typescript) and hovering the red curvy line brings up a tooltip window with error information. If the editor is scrolled far enough to the right due to the length of the line, this window disappears immediately after appearing (merely blinks in and out of existence). I reckon this has to do with mouse move coordinates not being relative to the scroll position. See video. 

By the way, when you're at it - the font in the tooltip window is the same monospaced font as the code, making long texts (in TypeScript type errors can span dozens of lines) unreadable (hard to distinguish from the underlying code and no optimal use of space). This could be improved (also the automatic wrapping of text in that tooltip window should be suppressed in case the text contains line feeds, since compiler errors come with their own hierarchical formatting, which is impossible to read otherwise). 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

![vsc-tooltip-issue](https://user-images.githubusercontent.com/5341447/47603054-d68bed00-d9e6-11e8-8f67-4ea6a8500f26.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (18.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-icons|rob|7.27.0

</details>

**Comment by weinand** [comment] 2018-10-27 14:49
similar to #57088

**Comment by hamxabaig** [comment] 2019-05-04 12:44
This is still a problem in latest version `v1.33.1 (1.33.1)` (I disabled all extensions and its still occurring). Its very annoying and occurs very randomly. However i found a way to reproduce this. If you scroll the swiggly error line to the very top and then hover over it. This opens and closes the error tooltip (giving flickering effect).

Here is a screencast of it reproduced.
https://www.dropbox.com/s/1xq1p0ju4tp4442/Screen%20Recording%202019-05-04%20at%205.17.55%20PM.mov?dl=0

**Comment by tamuratak** [comment] 2019-05-05 01:10
Duplicate of #71493, #51794.

**Closed** 2019-07-22 08:33 UTC
Labels: bug, editor-hover
