### ISSUE TITLE
Can't snap or split view with JSON files

### ISSUE THREAD

**Issue by scooby359** [microsoft/vscode#102920] opened 2020-07-20 07:23 UTC
Open a file containing JSON text. Try and drag the tab to the right to split view, or right click on the tab and select split tab from the menu. The file closes and an error pops up with "Unable to open 'emailTemplates.json': Cannot read property 'strings' of null."

**Comment by IllusionMH** [comment] 2020-07-20 09:46
/needsMoreInfo

Please provide other info required by template (VS Code version, OS version, if reproduced without extension etc.).

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Looks similar to #102348 . Do you see same stack if you open **Help** > **Toggle developer Tools**?

**Comment by bpasero** [comment] 2020-07-20 16:33
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by scooby359** [comment] 2020-07-20 16:56
First error occurs when setting language to JSON, second error occurs when trying to split / snap screen

```
  ERR Cannot read property 'strings' of null: TypeError: Cannot read property 'strings' of null
    at Function._subsetEquals (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1771:726)
    at Function._subsetEquals (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1771:875)
    at g.updateOptions (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1772:4)
    at e.updateOptions (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2286:606)
    at e.updateEditorConfiguration (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3636:749)
    at file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3634:633
    at c.fire (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:146
    at c.fire (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at F.setMode (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1436:124)
    at k.setLanguage (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2661:907)
    at e.setMode (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2669:587)
    at e.setMode (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2999:79)
    at e.setMode (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6049:31)
    at e.setMode (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5628:254)
    at le.run (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5650:418)
    at async Object.triggerAndDisposeAction (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:424)
    at async file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:149
    at async Object.accept (file:///C:/Users/chrisw/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:899)


  | onDidChangeNotification | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:587
  | addNotification | @ | notifications.ts:207
  | notify | @ | notificationService.ts:106
  | doHandleOpenEditorError | @ | editorGroupView.ts:1062
  | (anonymous) | @ | editorGroupView.ts:990
  | async function (async) |   |  
  | (anonymous) | @ | editorGroupView.ts:979
  | doShowEditor | @ | editorGroupView.ts:977
  | doOpenEditor | @ | editorGroupView.ts:960
  | openEditor | @ | editorGroupView.ts:888
  | doMoveOrCopyEditorAcrossGroups | @ | editorGroupView.ts:1181
  | copyEditor | @ | editorGroupView.ts:1203
  | E | @ | editorCommands.ts:458
  | (anonymous) | @ | editorCommands.ts:473
  | invokeFunction | @ | instantiationService.ts:61
  | _tryExecuteCommand | @ | commandService.ts:84
  | (anonymous) | @ | commandService.ts:73
  | Promise.then (async) |   |  
  | executeCommand | @ | commandService.ts:73
  | run | @ | actions.ts:294
  | run | @ | actions.ts:361
  | runAction | @ | actions.ts:198
  | run | @ | actions.ts:190
  | onClick | @ | actionbar.ts:183
  | (anonymous) | @ | actionbar.ts:161


```

**Comment by bpasero** [comment] 2020-07-21 05:32
This seems to be editor options:

https://github.com/microsoft/vscode/blob/7725bf1bcc0fcc3c96286ab1dcf2c66491eaefdc/src/vs/editor/common/config/commonEditorConfig.ts#L369

Moving to @alexdima

**Comment by alexdima** [comment] 2020-07-21 08:27
@scooby359 Do you have any `null`s in your user `settings.json` ?

**Comment by scooby359** [comment] 2020-07-21 08:32
Yes, found a couple:
```   
"gitlens.menus": null,
"editor.quickSuggestions": null,
```

**Closed** 2020-07-21 08:46 UTC
Labels: editor, needs more info
