### ISSUE TITLE
User tasks

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#65180] opened 2018-12-17 01:01 UTC
Please consider adding the option of User tasks, so that these user tasks are saved in C:\Users\JMatos\AppData\Roaming\Code\User and not in the .vscode folder.
This would be helpful to create the option of syncing user tasks between several devices (from the same user). I use it to launch Python Help for example.

**Comment by cedric05** [comment] 2018-12-17 15:33
can i work on it ? 
@alexr00

**Comment by cedric05** [comment] 2018-12-19 16:20
i started working on this issue.

**Comment by alexr00** [comment] 2018-12-20 10:35
Duplicate of #1435
This is a big change, and will require a significant amount of re-arranging of how tasks are currently grouped. See #1435 for all the history here.

**Closed** 2018-12-20 10:35 UTC
Labels: *duplicate, feature-request, tasks
