### ISSUE TITLE
select-all then copy, does not work in debug console

### ISSUE THREAD

**Issue by stevedekorte** [microsoft/vscode#86322] opened 2019-12-04 20:51 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. open debug console and click in it
2. hit command-a to select all text (it highlights everything)
3. hit command-c to copy all selected text
4. click in another app (such as a text editor) and hit command-p to paste
5. notice that the pasted text was not the highlighted text when command-c was hit

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|64.00GB (44.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
debugger-for-chrome|msj|4.12.2

</details>

**Comment by stevedekorte** [comment] 2019-12-04 21:12
This is particularly frustrating as find doesn't appear to work in the debug console, so there's no way to find things without doing a (slow and tedious) scrolling selection then copy (vs select-all-copy), then copy and paste to another app, then find.

**Comment by isidorn** [comment] 2019-12-05 07:17
Duplicate of can not select all text in the debug console since we use the virtualised tree.

**Closed** 2019-12-05 07:16 UTC
Labels: *duplicate
