### ISSUE TITLE
"size limit" link in warning does not open setting in Settings GUI

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#151364] opened 2022-06-02 22:35 UTC
While verifying https://github.com/microsoft/vscode-jupyter/issues/10345 I noticed that if I click on the `Output exceeds the size limit. Open the full output data in a text editor` warning I'm not taken to the size limit setting which I would've expected to be taken to.

![Recording 2022-06-02 at 15 30 36](https://user-images.githubusercontent.com/12758612/171749113-aa221f73-9dad-4ee0-a6a8-d5433556f352.gif)

## Environment data

Version: 1.68.0-insider (Universal)
Commit: 15253f1528573fc8f84e956b21af4bad57f38c07
Date: 2022-06-02T05:16:30.515Z
Electron: 17.4.6
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001552309
Python Extension version (available under the Extensions sidebar): v2022.7.11521008

**Comment by greazer** [comment] 2022-06-06 20:10
This link is specified in core code.

**Comment by rzhao271** [comment] 2022-10-20 23:38
The issue is now fixed for me in the latest Insiders, at least on Windows 11.

**Closed by rzhao271** 2022-10-20 23:38 UTC
Labels: bug
