### ISSUE TITLE
Horizontal scrolling with word wrap on

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#47108] opened 2018-04-02 21:56 UTC
Have noticed this for awhile, but usually don't have word wrap on. Recently it was extremely annoying while writing lots of markdown. Sometimes in this case, after the wrap happens, it scrolls back to the left. But sometimes in doesn't.

It seems like it shouldn't scroll horizontally at all when word wrap is turned on, the word should wrap as soon as it would need to scroll.

![apr-02-2018 14-54-27](https://user-images.githubusercontent.com/323878/38218188-c9f62394-3685-11e8-9268-e98d22009f8b.gif)

**Comment by janvaniperen** [comment] 2018-05-16 19:47
Same here. Word Wrap is on and still limited horizontal scroll, making about 1.5 character to fall off.

**Comment by alexandrudima** [comment] 2018-09-18 20:27
@roblourens Word wrapping works entirely only for monospace fonts. From your screenshot, I believe you are using Fira Code and possibly using ligatures. i.e. duplicate of #2654

**Closed by alexandrudima** 2018-09-18 20:27 UTC
Labels: bug, editor-wrapping
