### ISSUE TITLE
Regression: Debugger frequently not going to main instance on breakpoint hit when debugging extensions

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#109415] opened 2020-10-26 20:14 UTC
Issue Type: <b>Bug</b>

Is this a known problem?  It started a few days ago.  If not, I can try to provide a repro.

VS Code version: Code - Insiders 1.51.0-insider (7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9, 2020-10-23T07:32:22.213Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 13, 13|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.186
vscode-azurefunctions|ms-|1.0.0
vscode-azurestorage|ms-|0.10.1
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.7.0
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.9.114305
vscode-ai|ms-|0.6.16
azure-account|ms-|0.9.3
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.13.0
vscode-todo-highlight|way|1.0.4

(8 theme extensions excluded)

</details>

**Comment by connor4312** [comment] 2020-10-26 21:17
What do you mean by "main instance"? Can you [record what you're seeing](https://gifcap.dev/)?

**Comment by weinand** [comment] 2020-10-26 21:17
What do you mean by "not going to main instance on breakpoint hit"?

**Comment by StephenWeatherford** [comment] 2020-10-26 22:06
This is what should happen - when the breakpoint is hit, the main instance should come to the forefront:
## As expected
![howitshouldwork](https://user-images.githubusercontent.com/6913354/97233696-9bbb1c00-179c-11eb-829c-e0da9ef019de.gif)
## Actual
Right now, of course, I can't repro it (it's been inconsistent but happening frequently).  

I've also sometimes see breakpoint not getting hit at all.  But again, it's inconsistent.

**Comment by isidorn** [comment] 2020-10-27 08:57
Ok, it seems like Electron API does not bring main window to front and feels like a duplicate of https://github.com/microsoft/vscode/issues/105913 which should be fixed.
I use the [`hostService`](https://github.com/microsoft/vscode/blob/0b1cd268f1a2753ba02ab1a0754f7d4a0528b7b3/src/vs/workbench/contrib/debug/browser/debugSession.ts#L820) for this

@StephenWeatherford you do not have `debug.focusWindowOnBreak` setting disabled, correct?

fyi @deepak1556 and @bpasero for electron smartness

**Comment by bpasero** [comment] 2020-10-27 09:06
As long as this line is hit:

https://github.com/microsoft/vscode/blob/ca4dd67abe11321dc977f8396616ff5e5714dfee/src/vs/code/electron-main/window.ts#L346-L346

It should work.

**Closed** 2020-11-04 11:22 UTC
Labels: debug, needs more info

**Comment by StephenWeatherford** [comment] 2020-11-04 20:31
This bug was not waiting for information from me, as far as I can tell.  Although I will say I haven't noticed it recently.

**Comment by isidorn** [comment] 2020-11-05 09:16
If you did not hit it recently then let's leave it closed since nobody else complained and we can not reproduce.
