### ISSUE TITLE
Prevent scrolling to last edited line when re-opening file

### ISSUE THREAD

**Issue by aviddiviner** [Microsoft/vscode#57650] opened 2018-08-31 00:23 UTC
Hi. I've had a fairly good look around and I don't believe this is possible currently. I'd like to add a config setting that would prevent VS Code from scrolling automatically to the last line that I had selected when I open a previously edited file.

I'm happy to implement this myself and submit a PR if you can offer me some pointers in the right direction. Here's what I've found so far (correct me if I'm wrong):

The magic seems to happen in src/vs/editor/browser/widget/codeEditorWidget.ts, around line 800: restoreViewState. I think I understand that part. Now I can add a new editor option and make use of it from src/vs/editor/common/config/editorOptions.ts. I need to figure out where that gets set.

Does this sound reasonable? Am I missing anything? Thanks for your time.

**Comment by alexandrudima** [comment] 2018-08-31 07:56
fyi @bpasero

**Comment by bpasero** [comment] 2018-08-31 09:00
Duplicate of https://github.com/Microsoft/vscode/issues/24394

**Closed by bpasero** 2018-08-31 09:00 UTC
Labels: feature-request, workbench-editors, workbench-state
