### ISSUE TITLE
Error installing vscode.d.ts: Error: Request returned status code: 500

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#74733] opened 2019-06-02 04:05 UTC
Just like #36627 and #69656, getting this error again trying to npm install in an extension.

```
> vimsavehang@0.0.1 postinstall C:\Users\thadh\Documents\GitHub\thadhouse\vimcrashdemo\vimsavehang
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.29.1
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vimsavehang@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vimsavehang@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jgfoster** [comment] 2019-06-02 04:07
Duplicate of #74732 (submitted a few minutes earlier).

**Closed** 2019-06-03 07:10 UTC
Labels: *duplicate
