### ISSUE TITLE
Errors not clearing after typing / building.

### ISSUE THREAD

**Issue by RichieAHB** [Microsoft/vscode#9945] opened 2016-07-29 13:13 UTC
- VSCode Version: 1.3.1
- OS Version: Mac OSX 10.11.5

Error not disappearing after save or typing. Initially I had a method `get` on the side.  I just left the options object as public and changed it.  I tried to clear the error by typing but it seems random parts of separate buffers are getting updated out of sync?

![screen shot 2016-07-29 at 14 08 03](https://cloud.githubusercontent.com/assets/1652187/17249069/15aab8cc-5596-11e6-90d8-3de4ea90b5d8.png)

**Comment by dbaeumer** [comment] 2016-08-03 14:03
I was not able to reproduce this is a simple example. Are you able to share your code so that I can have a look.

**Comment by dbaeumer** [comment] 2016-11-15 19:22
Closing since no additional information has been provided and I am not able to reproduce the issue.

**Closed by dbaeumer** 2016-11-15 19:22 UTC
Labels: needs more info, typescript
