### ISSUE TITLE
Trust: extensions that require a reload should trigger a modal reload dialog?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125050] opened 2021-06-01 09:31 UTC
Testing #124984

If I stop trusting a workspace, extensions get deactivated, but some seem to require a reload. If so, should we not ask the user to reload the window after trust has removed from the workspace?

![image](https://user-images.githubusercontent.com/900690/120301243-f2597d00-c2cc-11eb-868f-ebf3bb290904.png)

**Comment by lszomoru** [comment] 2021-06-05 19:02
Duplicate of #125526

**Closed by lszomoru** 2021-06-05 19:02 UTC
Labels: bug, workspace-trust

**Comment by meganrogge** [comment] 2021-06-07 16:23
I wasn't prompted to reload (even though I had some of the same extensions as above). None of the extensions had the requires reload button though. Not sure how to reproduce this.

**Comment by sbatten** [comment] 2021-06-07 17:03
@meganrogge the behavior you see is correct, the extension host is reloaded behind the scenes, so you shouldn't be prompted and you shouldn't see the requirement of a reload.
