### ISSUE TITLE
stack on search

### ISSUE THREAD

**Issue by JackJek** [microsoft/vscode#106239] opened 2020-09-07 14:24 UTC
Start global search by regexp interface(.+\n.+)*@cfg on ts files
If it have match VSCode fatal stack

**Comment by IllusionMH** [comment] 2020-09-07 14:55
/needsMoreInfo

Is it reproducible if you close all tabs and perform search? Most likely duplicate of #30874

Please provide VS Code/OS version and other info required by issue template.

**Closed** 2020-09-15 11:23 UTC
Labels: needs more info
