### ISSUE TITLE
Keyboard Shortcuts are different among Linux,Windows and Mac OS.

### ISSUE THREAD

**Issue by JiangCN** [Microsoft/vscode#55211] opened 2018-07-27 05:56 UTC
Keyboard Shortcuts are different among Linux,Windows and Mac OS.

Please get the Keyboard Shortcuts as same.

**Comment by V-ed** [comment] 2018-07-27 12:34
Duplicate of #17550 (closed)

**Closed** 2018-07-27 21:57 UTC
Labels: *duplicate
