### ISSUE TITLE
Make IntelliSense select the first suggested text by pressing Enter within a snippet without pressing the Up / Down key first

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#174836] opened 2023-02-20 12:21 UTC
I would like to select the first suggested text by IntelliSense by pressing Enter within a snippet without pressing the Up / Down key first.

Currently, neither Tab nor Enter selects the first suggested text within a JavaScript console.log snippet. If I press Tab, the cursor moves to the next field in the snippet, and if I press Enter, a new line appears. To select a variable name, I have to first select the text by pressing the Up/Down key and then pressing Tab or Enter. And if IntelliSense only suggests one option, I can't select the text because the Up/Down key takes me out of the snippet.

Version: 1.76.0-insider (system setup)
Commit: 4e3219683563939873497516a235691aa2731274
Date: 2023-02-20T05:23:01.179Z
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by gjsjohnmurray** [comment] 2023-02-20 12:31
Have you changed the `editor.suggest.selectionMode` setting from its default?

**Comment by gjsjohnmurray** [comment] 2023-02-20 12:39
I think this is a duplicate of #173387

**Closed** 2023-02-20 13:19 UTC
Labels: *duplicate
