### ISSUE TITLE
"Search files by name" with ":<line-number>" doesn't jump to line

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#129151] opened 2021-07-22 05:56 UTC
to repro:
- copy some text: `<filename>:<line-number>`
- ctrl-p
- paste in copied text
- `<enter>`

results:
the file is opened, but if it's the first time since vscode was started, then it doesn't jump to the line number. if you repeat the steps, then it works as expected.

this is really annoying - i use this feature _all the time_.

this just started happening since an upgrade. worked fine before.

**Comment by IllusionMH** [comment] 2021-07-22 10:31
/duplicate of #128518

Already fixed in Insiders builds https://code.visualstudio.com/insiders/

**Closed** 2021-07-22 10:32 UTC
Labels: *duplicate
