### ISSUE TITLE
JS/TS service seems to be cash looping

### ISSUE THREAD

**Issue by frozenbubble** [microsoft/vscode#182862] opened 2023-05-18 11:52 UTC
Type: <b>Bug</b>

I'm on macos 13.3.1 (a) on an M1 macbook pro, JS/TS runtime keeps initializing until I get an error notification that it has restarted a bunch of times in the last 5 minutes. Code helper process in the activity monitor seems to be occupying the CPU in the meanwhile and the computer noticably heats up.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 6b77ca2b-c55a-4c58-9566-d2aa067527c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
namespace|adr|1.1.2
primer-light|and|0.0.6
systemd-unit-file|coo|1.0.6
tsimportsorter|doz|7.6.3
gitlens|eam|13.6.0
prettier-vscode|esb|9.12.0
vscode-diff|fab|1.4.2
copilot|Git|1.86.82
vscode-pull-request-github|Git|0.64.0
go|gol|0.38.0
vscode-codemetrics|kis|1.26.1
labeled-bookmarks|koa|1.1.11
vscode-docker|ms-|1.25.1
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.5
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vsliveshare|ms-|1.0.5864
unity-toolbox|pix|3.0.0
ayu|tea|1.0.5
change-case|wma|1.0.0
material-theme|zhu|3.15.13

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by mjbvz** [comment] 2023-05-18 18:02
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2023-05-23 20:08
Thanks for testing. Closing since it sounds like the issue may have already been fixed in insiders

**Closed by mjbvz** 2023-05-23 20:08 UTC
Labels: info-needed
