### ISSUE TITLE
More than 100000 values in an array on debugging mode

### ISSUE THREAD

**Issue by amiralisalimi** [microsoft/vscode#76798] opened 2019-07-07 13:38 UTC
On VS Code debugging mode, when I have an array / vector / map or etc, with more than 100000 values, and then click on it on debugging panel, VS Code tries to load all the values, obviously is unable to, so, infinitely loads. I am supposed to restart VS Code, temporary decrease the maximum value to 1000, and restart debugging mode.

But a better solution may be this: 
If the number of values is more than 1000, just load the first 1000 values! There can be a button on the debugging panel to increase the number of loaded values.

**Comment by weinand** [comment] 2019-07-07 13:41
What debugger is this?

**Comment by amiralisalimi** [comment] 2019-07-07 13:43
Microsoft C++ extension
On Linux (GDB)

**Comment by weinand** [comment] 2019-07-07 13:56
@amiralisalimi in theory, VS Code should not walk the whole array because it shows only chunks of the data like this:

<img width="770" alt="2019-07-07_15-47-26" src="https://user-images.githubusercontent.com/1898161/60769376-2a4eea00-a0cf-11e9-87ab-d20f30612254.png">

But I think we have regressed in that area and VS Code does walk the whole data.

@isidorn please investigate why VS Code can no longer deal with large arrays. This could be related to the new tree work.

Here is my test sample:
```js
var a = new Array(1000000);

for (let i = 0; i < a.length; i++) {
	a[i] = i;
}

debugger;

console.log(a[99]);
```

and here the launch.json:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/test.js"
		}
	]
}
```

**Comment by amiralisalimi** [comment] 2019-07-07 14:09
As my debugger doesn't break the data to chunks, and also there is no problem when using gdb debugger on terminal, this maybe related to [c++ extension](https://github.com/Microsoft/vscode-cpptools.git).

**Comment by amiralisalimi** [comment] 2019-07-07 14:24
Here is a sample:
```
#include <iostream>

int main()
{
    const int maxn = 1e5;
    int a[maxn];

    for (int i = 0; i < maxn; i++)
        a[i] = i;

    return 0;
}
```

My `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/bin/gdb"
        }
    ]
}
```

Try adding break point on line 10 of the sample code and click on `a` on the debugger panel. For me, it infinitely loads.

**Comment by weinand** [comment] 2019-07-07 14:32
The C++ debugger seems to show only the first 1000 elements of an array (without breaking it into chunks). This is a problem of the C++ extension that should be reported against the extension.

My JavaScript sample from above does use chunks but VS Code basically hangs on loading the data. This indicates that it is more a frontend (VS Code) problem.

**Comment by isidorn** [comment] 2019-07-08 08:46
I can reproduce this with the JavaScript sample and I am looking into it.

**Comment by isidorn** [comment] 2019-07-08 08:47
I can reproduce this with the JavaScript sample and I am looking into it.

**Comment by isidorn** [comment] 2019-07-08 09:00
I have investigated and vscode behaves the following for the long arrays:
* It first fetches the `named` variables, and only after that it starts fetching the `indexed` variables once the user clicks on the chunks.
* Fetching of the `named` variables is actually slow as node2 does not respond for a long time. VS Code is fetching `named` variables since the `namedVariables` has value 2 in this case returned from the adapter. [Code pointer](https://github.com/Microsoft/vscode/blob/8434efe71f2f382b313ec16bd7212b4c15b20989/src/vs/workbench/contrib/debug/common/debugModel.ts#L137) on the vscode logic

So it seems that the `variables` request with the filter `named` got slow. Also VS Code did not change the variable fetching logic for over a year and the new tree does not change this.
Assigning to @roblourens to investigate

<img width="317" alt="Screenshot 2019-07-08 at 10 58 26" src="https://user-images.githubusercontent.com/1926584/60797332-5d48ba80-a16f-11e9-986a-5dc11a1e36fe.png">

**Comment by roblourens** [comment] 2019-07-10 18:32
This has been broken for many months :(

**Comment by amiralisalimi** [comment] 2019-10-11 08:24
I found a new fact. When I use vector container in c++ (which is an array with dynamic size), even when I set it's size to something more than 100000, there is no problem viewing it's elements on the debugging panel. It actually only shows the first 1000 elements.
(code version 1.39.1)

**Comment by ncduy0303** [comment] 2020-06-03 16:07
Has there been any solutions for this problem? The GDB debugger keeps loading the entire array which is very slow.

**Comment by weinand** [comment] 2020-06-03 16:10
@ncduy0303 Please file your issue against the GDB debugger.

**Comment by connor4312** [comment] 2021-02-04 19:23
js-debug behaves properly here using array chunks. V8 still takes some time to report stackframe variables if I have an array with 10 million entries, although it still just sends a small summary which we can show an deal with correctly.

**Closed by connor4312** 2021-02-04 19:23 UTC
Labels: bug, debug
