### ISSUE TITLE
All entered characters are removed when some characters are removed before conversion by Japanese IME.

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode#89860] opened 2020-02-02 11:34 UTC
- VSCode Version: 1.41.1
- OS Version: Windows 10 (1909, build 18363.592)
From VSCode version info
```
バージョン: 1.41.1 (system setup)
コミット: 26076a4de974ead31f97692a0d32f90d735645c0
日付: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Enable Japanese IME
1. Input any characters
1. Press arrow key before conversion
1. Press delete or backspace key to remove one character
1. Press enter key

Expected result:
Some characters, except removed one at step 4, remains

Actual result:
All characters are removed.
![vscode_ime](https://user-images.githubusercontent.com/4566555/73607583-5138b480-45fb-11ea-9fdc-70e78a68c653.gif)

https://twitter.com/hori__hiro/status/1223081019084902400
https://twitter.com/hori__hiro/status/1223081543062581253

Does this issue occur when all extensions are disabled?: Yes

**Comment by Nikumo** [comment] 2020-02-07 02:39
This is a bug with certain versions of chromium.
It has been fixed in google chrome 77 or later, so it seems to be fixed if the version of electron is increased.

**Comment by rebornix** [comment] 2020-02-10 17:42
We will verify this issue once we adopt Electron 7 which ships with Chromium 78.

**Comment by rebornix** [comment] 2020-04-02 17:07
I can confirm it's already fixed in Insiders.

**Closed by rebornix** 2020-04-02 17:08 UTC
Labels: editor-input-IME, electron, verification-needed, windows
