### ISSUE TITLE
Problem-matcher displays only one line of multiple errors.

### ISSUE THREAD

**Issue by hirooih** [microsoft/vscode#111134] opened 2020-11-22 15:50 UTC
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Add a sample task on `tasks.json` and `gcc.out`.

```
    "tasks": [
        {
            "label": "problem-watcher-test",
            "type": "shell",
            "command": "cat gcc.out",
            "problemMatcher": {
                "owner": "external",
                "fileLocation": ["autoDetect", "${workspaceFolder}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
        },
    ]
```

The problem matcher can be replaced by `"problemMatcher": "$gcc",`.  (See #105159)

gcc.out

```
foo.txt:3:3: warning: one
foo.txt:5:3: warning: two
foo.txt:5:3: warning: three
```

2. Run the task above.

Only `one` and `three` are shown, but  `two` is not shown in PROBLEM window.

![image](https://user-images.githubusercontent.com/24754036/99908155-4be05e00-2d24-11eb-8482-cd89725e9a90.png)

I thought there must be a configuration option, but I cannot find.  But I think all error should be shown by default.

https://stackoverflow.com/questions/64069836/visual-code-problemmatcher-only-report-one-issue-per-line-of-code
is similar to this issue but no response.

And #105159 is also similar, but it is for multi-line problem.  I reported on it but it has been in "needs more info" state.
So I decided to open this issue.

Thank you.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-11-23 11:21
duplicate of #105159

**Closed by alexr00** 2020-11-23 11:21 UTC

**Comment by hirooih** [comment] 2020-11-23 12:44
Thank you for your response.

You closed this ticket  as duplicate of #105159.
And you closed #105159 as duplicate of "Terminal doesn't flush all line data before firing onExit" #92868.

But obviously this ticket is not a duplicate of #92868.  The example above shows the last line.

Here is better example.
gcc.out

```
foo.txt:1:1: warning: line 1: 1/3
foo.txt:1:1: warning: line 1: 2/3
foo.txt:1:1: warning: line 1: 3/3
foo.txt:2:1: warning: line 2: 1/2
foo.txt:2:1: warning: line 2: 2/2
foo.txt:3:1: warning: line 3: 1/1
```

The problem window shows;

![image](https://user-images.githubusercontent.com/24754036/99962978-696d0080-2dd4-11eb-8bce-05e06779178b.png)

Please reopen this issue ticket.

I've changed the title from

> Problem-matcher displays only one line of multiple errors.

to

> Problem-matcher displays only the first line of multiple errors.

Thanks!

**Comment by alexr00** [comment] 2020-11-23 12:49
As explained in https://github.com/microsoft/vscode/issues/105159#issuecomment-732093981, I found two problems while debugging. This is a result of the second problem, which I improved (fixed for non-Windows, we still need that heuristic on Windows) with the change I pushed for #105159.

**Comment by hirooih** [comment] 2020-11-23 12:59
I've been having this issue on Linux, too.  Sorry I should wrote about it.

I read #77475.  It is a windows specific issue.
So this is not duplicate of them.

**Comment by hirooih** [comment] 2020-11-23 13:36
@alexr00 

Additional info.

gcc.out

```
foo.txt:1:1: warning: line 1: 1/3
foo.txt:1:10: warning: line 1: 2/3, column 10
foo.txt:1:1: warning: line 1: 3/3
foo.txt:2:1: warning: line 2: 1/2
foo.txt:2:1: warning: line 2: 2/2
foo.txt:3:1: warning: line 3: 1/1
```
If I change the column number, it shows up.

![image](https://user-images.githubusercontent.com/24754036/99967141-c5d31e80-2dda-11eb-93b9-9c5a86cf2150.png)

@alexr00 
Problem matcher shows only one of lines whose line number and column number are same.
This cannot be OS dependent behavior.

I looked for the source code.  I'm suspecting that the following files are related to this issue.

```
workbench/contrib/tasks/common/problemCollectors.ts
workbench/contrib/tasks/common/problemMatcher.ts
```

but I could not find out where the filtering is done.
If you know where it is, please share with me.

Thanks!

**Comment by alexr00** [comment] 2020-11-23 14:08
See https://github.com/microsoft/vscode/issues/105159#issuecomment-732093981 which explains this. And please try out the next insiders build.

**Comment by hirooih** [comment] 2020-11-23 23:45
@alexr00

As I wrote above this is not the issue about the file IO flush.  The last line is shown.

Please try the above test with the insiders build.

**Comment by TheQuill** [comment] 2020-11-25 09:52
I'm leaving a comment here because i also don't see the other ticket solving this issue.

For my problem matcher:
`"problemMatcher": {
        "owner": "vhd",
        "fileLocation": [
          "relative",
          "${workspaceFolder}/modelsim/${command:extension.commandvariable.file.fileDirBasename}"
        ],
        "pattern": {
          "regexp": "^#\\s..\\s(\\w+):\\s([a-zA-Z./_]+)[(](\\d+)[)]: (.+)$",
          "file": 2,
          "line": 3,
          "severity": 1,
          "message": 4
        }
      }`

The input:
`# eval vcom  -quiet -suppress 1346,1236,1090 -2008 -work lib_front_panel_led  ../../hdl/lib_front_panel_led/front_panel_led_avalon.vhd
# ** Error: ../../hdl/lib_front_panel_led/front_panel_led_avalon.vhd(41): (vcom-1136) Unknown identifier "AVALON_DATA_WITH".
# ** Error: ../../hdl/lib_front_panel_led/front_panel_led_avalon.vhd(41): Type error resolving infix expression ">=" as type std.STANDARD.BOOLEAN.
# ** Error: ../../hdl/lib_front_panel_led/front_panel_led_avalon.vhd(84): VHDL Compiler exiting`

Leads to only the second error on line 41 being displayed while the first is much more valuable:
![image](https://user-images.githubusercontent.com/32319801/100210910-cb7c5180-2f0b-11eb-8dfc-d16ef436204b.png)

The steps to reproduce my setup are lengthy so my comment is just to support this issue being looked at. I tried this with the latest insiders build and this also has this issue.

**Comment by hirooih** [comment] 2020-11-25 23:34
@alexr00 

> I tried this with the latest insiders build and this also has this issue.

Please reopen this issue.

@TheQuill 

Thank you for your info.  I also found this issue on output from EDA tools.

> ... while the first is much more valuable:

This is the real problem.  VS-code might hide important messages.
