### ISSUE TITLE
NPM SCRIPTS :  No Scripts found

### ISSUE THREAD

**Issue by LittleTheFu** [microsoft/vscode#88895] opened 2020-01-18 09:00 UTC
- VSCode Version:1.41.1
- OS Version:mac os Catalina version 10.15.2

Steps to Reproduce:

1.cannot find any npm scripts in any project, even a simple create-react-app project.
2.it still not work when I click the refresh button in "NPM SCRIPTS" bar.
3.the screen-shot is a simple create-react-app project.
![Screen Shot 2020-01-18 at 4 54 41 PM](https://user-images.githubusercontent.com/15071167/72661352-d45ee580-3a13-11ea-82ec-bbfa728206ab.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by fjcalzado** [comment] 2020-01-21 09:22
Same thing happened to me a couple of weeks ago since a popup showed up warning about bad performance of this built-in extension. Any progress on this issue? I tried reinstalling with no success.

**Comment by LittleTheFu** [comment] 2020-01-21 10:24
> couple

You remind me, I also came up with something like a popup warning dialog before this bug appears.

**Comment by dalkegama** [comment] 2020-01-21 15:22
+1

**Comment by andoni90** [comment] 2020-01-21 19:17
Had the same problem. This fixed it for me:
Settings -> Features ->Task -> Auto Detect - "on"

**Comment by LittleTheFu** [comment] 2020-01-22 07:30
> Had the same problem. This fixed it for me:
> Settings -> Features ->Task -> Auto Detect - "on"

thank you， it works for me.

**Comment by egamma** [comment] 2020-02-04 08:49
I cannot reproduce this using a create-react-app project

![image](https://user-images.githubusercontent.com/172399/73727938-b4793280-4732-11ea-8344-e1ea2c04d2b4.png)

> I also came up with something like a popup warning dialog before this bug appears.

Can you share this popup dialog. I suspect it is the warning that a task detection took too long and timed out? 

Can you share more information about your workspace by running `code --status` when code is running and include the the 'Workspace Stats' section. For example, this is what I'm getting from the create-react-app:

```
Workspace Stats:
|  Window (package.json — my-app)
|    Folder (my-app): 15 files
|      File types: js(3) css(2) gitignore(1) json(1) md(1) lock(1) svg(1)
|                  html(1) ico(1)
|      Conf files: package.json(1)
```

**Comment by egamma** [comment] 2020-02-04 16:22
**Update** after discussing with @alexr00 I now understand what is going on.
- in some workspaces there was a slow task detection
- a notification shows up with the option 'Disable All' task detection

This setting is global and therefore no more task detection takes place.
To recover from the setting change from above does this:
>Settings -> Features ->Task -> Auto Detect - "on"

We will improve this behaviour.

**Comment by alexr00** [comment] 2020-02-05 11:31
Since the setting is behaving as expected, I'm going to close this issue. Improving the case where we currently show the notification with the dangerous 'Disable All' button is tracked by https://github.com/microsoft/vscode/issues/90015.

**Closed by alexr00** 2020-02-05 11:31 UTC
