### ISSUE TITLE
Emmet wrap with abbreviation inserts extra spaces before content when abbr is inline element

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29898] opened 2017-06-29 23:26 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:07:31.424Z)
- OS Version: Darwin x64 16.6.0
---

Steps to Reproduce:

1. for the html file
```html
text
```
2. Put cursor after `text` and run `emmet: wrap with abbreviation`
3. Enter `ul>li>a` as the abbreviation

**Expected**
```html
<ul>
	<li><a href="">text </a></li>
</ul>
```
**Actual**
Extra spaces are inserted before and after text:

```html
<ul>
	<li><a href=""> 	text </a></li>
</ul>
```

Also tested on current master

**Comment by ramya-rao-a** [comment] 2017-06-30 01:47
This happens when the abbreviation in the end is for an inline element like <a> or <span>

The extra tab is added for indentation purposes. But it fails to identify cases like the above where the tab is not needed.

No easy way to fix this at the moment other than expecting the emmet module to return the content with right indents.

**Comment by ta-riq** [comment] 2017-06-30 06:22
Can we please keep the default emmet environment ?

**Comment by ramya-rao-a** [comment] 2017-06-30 06:33
@ta-riq Can you elaborate on what you mean by the default emmet environment?

We won't be switching to the new model until all the major issues (including this one) are fixed.
The stable build will have the setting `emmet.useNewSetting` with value `false` by default.
The Insiders build has this setting set to `true` by default as we need it to be tested and improved.
You can always set the `emmet.useNewSetting` to `false` to go back to the old model.

**Comment by ramya-rao-a** [comment] 2017-07-21 16:06
From @vvs in #31212

Steps to Reproduce:

1. Open the following HTML file:
```
<html>
<body>
  <ul>
	  <li></li>
	  <li></li>
	  <li></li>
	  <li></li>
	  <li></li>
  </ul>
</body>
</html>
```
2. Select all lines between the `ul` tags.
3. Invoke "Emmet: Wrap with Abbreviation", and then type `span` in the command palette.
4. The end result is horrific:
```
<html>
<body>
  <span> 	<ul> 	 <li></li> 	 <li></li> 	 <li></li> 	 <li></li> 	 <li></li> 	</ul> </span>
</body>
</html>
```

**Comment by ramya-rao-a** [comment] 2017-07-21 16:06
This happens for all elements that have `display: inline` by default.

Emmet thinks that "oh this is an inline element, so I should place everything in a single line"

Solution would be to fix it upstream by not doing this single line treatment if the text being wrapped is multi line to begin with.

**Comment by ramya-rao-a** [comment] 2017-07-23 01:22
Turns out there is a setting that will treat inline elements as block
Fixed with https://github.com/Microsoft/vscode/commit/dac7e15aba0564bdca99aea2270503d94b369706

Note to verifier:

Test below scenarios:

- single line text
- multi line text
- single line html
- multi line html (with indentation)

**Comment by vvs** [comment] 2017-07-23 06:26
@ramya-rao-a many, many thanks for your work, it makes my experience with VS Code **A LOT** better :) ☺️

One note regarding the latest changes. So, now, even for a single line, when I wrap it with, say, `span`, I end up with the multi-line output like this:

```
<span>
   single-line-text
</span>
```
Which doesn't feel right. Ideally, I'd prefer the inline-tags to be, well, inline and not create extra lines when we deal with the single line.

For multi-line cases the current behavior is perfect already though. :)

**Comment by vvs** [comment] 2017-07-23 06:31
Here's the fix I meant in mind, to handle single-line better:
```
diff --git a/extensions/emmet/src/abbreviationActions.ts b/extensions/emmet/src/abbreviationActions.ts
index 7cad2eb959..7bd44dcb14 100644
--- a/extensions/emmet/src/abbreviationActions.ts
+++ b/extensions/emmet/src/abbreviationActions.ts
@@ -218,7 +218,7 @@ function expandAbbreviationInRange(editor: vscode.TextEditor, expandAbbrList: Ex
 function expandAbbr(input: ExpandAbbreviationInput, newLine: string): string {
 	const emmetConfig = vscode.workspace.getConfiguration('emmet');
 	const expandOptions = getExpandOptions(emmetConfig['syntaxProfiles'], emmetConfig['variables'], input.syntax, input.textToWrap);
-	if (input.textToWrap) {
+	if (input.textToWrap && !input.rangeToReplace.isSingleLine) {
 		// Below fixes https://github.com/Microsoft/vscode/issues/29898
 		// With below, Emmet formats inline elements as block elements 
 		// ensuring the wrapped text does not get merged to a single line
```

**Comment by ramya-rao-a** [comment] 2017-07-23 19:31
Done!

@vvs Thanks for all your feedback as well, I couldn't have found half the corner cases around emmet if not for you, @jens1o and @smlombardi

If I could ask one more favor of you all, can you also test rest of the Emmet commands (run `Show Emmet Commands` to see the list) with `emmet.useNewEmmet` set to `true`?

Currently `emmet.useNewEmmet` is `false` by default in the stable build,  I want to turn that to `true` by default for the next update (1.15).

Extra eyes on the rest of the Emmet commands will help a great deal

**Comment by jens1o** [comment] 2017-07-23 19:55
I'm going to do that, don't mention it. ;)

**Comment by ramya-rao-a** [comment] 2017-08-01 23:12
Repeating note to verifier:

Test below scenarios:

- single line text
- multi line text
- single line html
- multi line html (with indentation)

with the below type of abbreviation

- single block element like `div`
- single inline element like `span`
- single element snippet like `a`
- abbreviation that would expand to multi line ending in a block element like  `ul>li`
- abbreviation that would expand to multi line ending in a inline element like  `ul>li>span`

Verify that when single lines are wrapped with inline element you get a single line at the end

**Comment by roblourens** [comment] 2017-08-04 00:17
I still repro the original issue

**Comment by ta-riq** [comment] 2017-08-26 03:54
Is There any way that emmet will foloow the default rules ?

**Comment by ramya-rao-a** [comment] 2017-08-26 20:10
@ta-riq What are the default rules?

**Comment by ramya-rao-a** [comment] 2018-02-15 01:09
The original fix is fixed with https://github.com/Microsoft/vscode/pull/43345

Note to verifier: Please see https://github.com/Microsoft/vscode/issues/29898#issuecomment-319522557

**Closed by ramya-rao-a** 2018-02-15 01:09 UTC
Labels: bug, emmet, help wanted
