### ISSUE TITLE
Session state is not persisted if VS Code does not cleanly exit

### ISSUE THREAD

**Issue by flotwig** [Microsoft/vscode#66633] opened 2019-01-16 23:10 UTC
Issue Type: <b>Bug</b>

The normal behavior when you cleanly quit VS Code (not by crashing the app or powering off your PC) and re-open it is that it will re-open with all the same tabs and workspace configuration as before. This behavior was added in response to #101, and it works well.

If VS Code crashes, or if the PC is shut down, VS Code will not reopen with your previous session intact. You lose all of your unsaved work and context if VS Code does not exit cleanly.

I'm assuming that this behavior occurs because session state is only persisted to disk when VS Code receives a command to exit, which will not happen if it crashes.

I think this behavior is a **bug** because it greatly exacerbates the effects of other bugs on your work. Normally, crashes in applications are no big deal; but in VS Code's case, it can cause you to completely lose track of what you're working on. Is this side-effect of losing work intended? Could it be fixed by regularly persisting session state to disk every few minutes?

Note: I'm currently on Ubuntu Linux; however, I've experienced this issue on Windows 10 as well.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2516)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.55GB (2.60GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
php-intellisense|fel|2.3.10
python|ms-|2018.12.1
Go|ms-|0.8.0
vetur|oct|0.14.5
vscode-docker|Pet|0.5.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0
markdown-html|zhy|0.1.8

</details>

**Comment by usernamehw** [comment] 2019-01-16 23:13
Possible duplicate of #12058

**Comment by flotwig** [comment] 2019-01-16 23:16
Oops, didn't see that one. The only thing I'm adding to the conversation here is that this is not a Windows-only issue.

**Comment by usernamehw** [comment] 2019-01-16 23:19
/duplicate #12058 

There is no `windows` label on that issue so it's probably implied as cross-platform.

**Closed** 2019-01-16 23:19 UTC
Labels: *duplicate
