### ISSUE TITLE
xml syntax collapse exception

### ISSUE THREAD

**Issue by nblog** [microsoft/vscode#88735] opened 2020-01-16 05:45 UTC
版本: 1.41.1 (user setup)
提交: 26076a4de974ead31f97692a0d32f90d735645c0
日期: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

with [#88657](https://github.com/microsoft/vscode/issues/88657)

I uninstalled all plug-ins (including language packs)
there is still an abnormal phenomenon of folding display.
so I don't think it's plug-ins.
I will provide the documents for the sample, It's more helpful to reproduce the problem.

example file (use unzip):[api.zip](https://github.com/microsoft/vscode/files/4063104/api.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-01-16 11:43
/duplicate of #88657 

With no extensions enabled, code folding for XML will be purely indent-based. See [docs](https://code.visualstudio.com/docs/editor/codebasics#_folding).

The redhat.vscode-xml extension claims to offer document folding. Maybe try it yourself, and if it gets something wrong report the issue at its repo.

**Closed** 2020-01-16 11:43 UTC
Labels: *duplicate
