### ISSUE TITLE
More Robust Markdown Preview

### ISSUE THREAD

**Issue by JaimeStill** [Microsoft/vscode#59483] opened 2018-09-26 19:08 UTC
I like to view the markdown preview as I'm typing to keep track of how it looks. Below are some changes that would be great:

* Style preview code snippets to match the editor theme (or be overridden if desired).
* Apply font family to snippets (Fira Code with ligatures). The overall preview font can be set, why not these? I know that you can point to an external style sheet, but I shouldn't have to do this for a common, persistent configuration.
* Native HTML conversion without the need for an extension. Conversion should keep styling consistent with the preview.

I know this may be a bit nit-picky, but it's really jarring when the editor and preview don't match:

![image](https://user-images.githubusercontent.com/14102723/46103094-f2a92e00-c19d-11e8-89d1-74bd88f99b51.png)

**Comment by mjbvz** [comment] 2018-10-04 18:21
Please split this up into separate feature request issues. 

1 and 2 require #56356

3 is a duplicate of #49157

**Closed by mjbvz** 2018-10-04 18:21 UTC
Labels: feature-request, markdown
