### ISSUE TITLE
workbench.colorCustomizations & editor.tokenColorCustomizations: match all light or dark themes

### ISSUE THREAD

**Issue by bluebear94** [microsoft/vscode#194555] opened 2023-10-01 06:22 UTC
Currently, you can match themes in `workbench.colorCustomizations` and in `editor.tokenColorCustomizations` by name or override values for all themes. I’d like to be able to additionally override colors for either all light themes or all dark themes.

I have the latter option set to change the color of comments to `#7ce9fc`, which is more visible than the default comment color for most themes, but I’d need a different value for light themes.

**Comment by gjsjohnmurray** [comment] 2023-10-01 07:25
Previously requested in  #101418 but failed to progress beyond Backlog Candidate.

**Comment by aeschli** [comment] 2023-10-02 09:35
Marking as duplicate of #101418.
As you know, we already have support for theme specific settings, by name and even with pattern: See https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting

**Closed by aeschli** 2023-10-02 09:35 UTC
