### ISSUE TITLE
New Key Bindings are not loaded automatically

### ISSUE THREAD

**Issue by kvrmd** [Microsoft/vscode#48861] opened 2018-04-27 22:26 UTC
Issue Type: <b>Bug</b>

I don't know how this happened, but every time I change keybindings.json I have to reload VSCode to apply the new settings.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|7, 4, 4|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment] 2018-05-02 08:54
@kvrmd I see you are editing the `keybindings.json` file directly. 
- Can you open keybindings editor and check if the changed keybinding was updated?
- Can you try updating it from Keybindings editor and see if it works?

**Comment by alexandrudima** [comment] 2018-05-02 09:01
@kvrmd I cannot reproduce. When I edit the file `keybindings.json` and **save** it, the changes are picked up immediately.

**Comment by kvrmd** [comment] 2018-05-03 15:53
@sandy081 
Both places did not update key bindings until reloading vscode.

I'm sorry I cannot describe how I got into that state. I managed to get away from this issue by doing a fresh install.

I deleted vscode from my applications and deleted the settings folder and vscode folder:
```
rm -rf $HOME/Library/Application Support/Code/User/settings.json
rm -rf $HOME/.vscode
```
When I installed back vscode, this issue is gone.

**Comment by alexandrudima** [comment] 2018-05-03 16:03
@kvrmd 

I will close this issue for now, as there is nothing actionable at this point.

Please let us know if you ever manage to distill some steps so we can investigate...

**Closed by alexandrudima** 2018-05-03 16:03 UTC
Labels: needs more info
