### ISSUE TITLE
Hover getting disabled automatically

### ISSUE THREAD

**Issue by brunochirelli** [microsoft/vscode#165988] opened 2022-11-10 08:15 UTC
Type: <b>Bug</b>

This is driving me nuts.

From time to time (minutes) the hover option got disabled and I ended by turning it on manually.

I don't know how it's supposed to happen, but even when I set the option on settings.json, it disabled too.

I don't know if my extensions are making this behavior or something related to setting sync. But I disabled all unnecessary extensions and even turned setting sync off and the problem persists.

I expect to keep the setting that I choose (always on) and don't disable it automatically.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.87GB (8.04GB free)|
|Process Argv|--crash-reporter-id 442e3911-4623-4ebe-9313-10b256932ade|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2903)|
|Memory (System)|11.62GB (7.92GB free)|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
Bookmarks|ale|13.3.1
vscode-browser-preview|auc|0.7.2
codesandbox-projects|Cod|0.2.55
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.46.0
vscode-graphql-syntax|Gra|1.0.4
vscode-drawio|hed|1.6.4
raml|jep|1.0.1
dotenv|mik|1.0.1
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-repositories|ms-|0.24.0
material-icon-theme|PKi|4.22.0
rewrap|stk|1.16.3
vscode-icons|vsc|12.0.1
ReactSnippets|xab|2.4.0
vscode-openapi|42C|4.15.9
aws-toolkit-vscode|ama|1.53.0
ng-template|Ang|14.2.0
vscode-tailwindcss|bra|0.9.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
copilot|Git|1.58.7236
todo-tree|Gru|0.0.220
openapi-lint|mer|1.2.0
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.0.10
prisma|Pri|4.6.0
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
code-spell-checker|str|2.11.0
code-spell-checker-portuguese-brazilian|str|2.0.9
quokka-vscode|Wal|1.0.509
wallaby-vscode|Wal|1.0.348

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-11-10 08:31
Exactly which value in your `settings.json` file is getting changed by something?

**Comment by brunochirelli** [comment] 2022-11-10 09:05
Exactly this one: `"editor.hover.enabled": true`
From time to time even this turned false automatically

**Comment by aproli90** [comment] 2022-11-23 09:51
I'm facing the same problem. Even asked the same on [stackoverflow](https://stackoverflow.com/questions/74301862/hover-getting-automatically-disabled-in-vscode). Any progress in debugging/resolving the issue?

**Comment by alexdima** [comment] 2022-11-25 22:44
I don't think there is any code in our source tree which would update `editor.hover.enabled` specifically in user settings. I am using settings sync and never witnessed settings changing without my doing so, therefore my best guess is that this is caused by one of your installed extensions.

All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by alexdima** [comment] 2022-11-25 22:44
@sandy081 Maybe you know, is there some log that could be enabled to see if our configuration service flips a setting and the reason it would do so?

**Comment by aproli90** [comment] 2022-11-28 11:55
> I don't think there is any code in our source tree which would update `editor.hover.enabled` specifically in user settings. I am using settings sync and never witnessed settings changing without my doing so, therefore my best guess is that this is caused by one of your installed extensions.
> 
> All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
> 
>     * run `F1 > Help: Start Extension Bisect`
> 
>     * (this will restart VS Code with half of your extensions disabled)
> 
>     * try to do the steps which reproduce the problem
> 
>     * if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
> 
>     * if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
> 
>     * these steps will repeat until the problematic extension is found
> 
> 
> initial 	step 	final
> ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) 	![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) 	![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png)

Since it's an intermittent issue, it's very difficult to debug it using this method. I can't afford to let extensions get disabled randomly since it would block my development

**Comment by KTibow** [comment] 2022-11-28 14:40
Doing a code search, this appears to be AWS Tookit. Can everyone else confirm that they also have this extension?

**Closed** 2022-11-28 16:16 UTC
Labels: info-needed

**Comment by aproli90** [comment] 2022-11-28 16:28
@alexdima Thanks for suggesting the way to rootcause the problem. I could see `hover.enabled` in many extensions, but AWS Toolkit was definitely one of them. The code pointer you shared is very valuable. Let me cut a ticket for them

**Comment by aproli90** [comment] 2022-11-29 10:05
https://github.com/aws/aws-toolkit-vscode/issues/3014

They have acknowledge the issue and working it

**Comment by BrianHHough** [comment] 2022-12-11 06:24
So strange this is the root cause of the Editor › Hover: Enabled being toggled off. I thought I was just going crazy... Thank you for looking into this and looking forward to a fix! 🙌

**Comment by justinmk3** [comment] 2022-12-13 20:57
Sharing an update on this AWS Toolkit issue (see also https://github.com/aws/aws-toolkit-vscode/issues/3014 ):

AWS Toolkit provides suggestions from [CodeWhisperer](https://aws.amazon.com/codewhisperer/). To do so, we implement [vscode.InlineCompletionItemProvider](https://github.com/aws/aws-toolkit-vscode/blob/c146b6e8edb92396d21746efdd03351c2c47475c/src/codewhisperer/service/inlineCompletionService.ts#L142). We also [override "editor.action.inlinesuggest.shownext"](https://github.com/aws/aws-toolkit-vscode/blob/c146b6e8edb92396d21746efdd03351c2c47475c/src/codewhisperer/service/inlineCompletionService.ts#L179-L191)  and related commands _when CodeWhisperer is providing suggestions_ so that the inline suggestion popup `Next` and `Previous` buttons provide CodeWhisperer suggestions.

@alexdima @hediet is there a better way for vscode extensions to provide inline suggestions without conflicting with other inline suggestions extensions?

Note also that a key problem is that GitHub Copilot overrides the hover popup _even when it is not providing suggestions_. In this screenshot, CodeWhisperer is providing suggestions but GitHub Copilot adds a button to the inline suggestions hover:

![image](https://user-images.githubusercontent.com/55561878/207440901-e2e5df04-b617-41f2-b237-0f488b37849e.png)

As a short-term solution, we've removed the workaround in AWS Toolkit v1.59 (not released yet) that temporarily disabled the hover popup. But now if user mouse-hovers, they see the `Open GitHub Copilot` button above (while CodeWhisperer is providing suggestions), which is very confusing.

**Comment by hediet** [comment] 2022-12-14 09:59
@justinmk3 can you file a new feature request for this, describing the problem and potential solutions?

**Comment by justinmk3** [comment] 2022-12-15 22:55
> can you file a new feature request for this, describing the problem and potential solutions?

https://github.com/microsoft/vscode/issues/169336
