### ISSUE TITLE
Intellisense not working, stops working after a couple of seconds

### ISSUE THREAD

**Issue by nonameolsson** [Microsoft/vscode#31056] opened 2017-07-19 16:19 UTC
- VSCode Version: 1.14.1
- OS Version: macOS Sierra 0.12.5 (16F73)

Steps to Reproduce:

1. Uninstall all VSCode instances and all extensions
2. Install VS Code stable
3. Open a new .js-file
4. Intellisense doesn't work. Developer tools throws errors.

Reproduces without extensions: No

This looks like being the error message:
```
activating extension `vscode.typescript` failed: [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

Error normal start:
![normalstart](https://user-images.githubusercontent.com/1493018/28377893-ec5920ee-6c73-11e7-8801-30584e81df2c.png)

Error `code --disable-extensions`
![noextensions](https://user-images.githubusercontent.com/1493018/28377894-ed5d0906-6c73-11e7-8a93-679a9693b6d0.png)

**Comment by mjbvz** [comment] 2017-07-19 20:23
Duplicate of #30716

Should be fixed in vscode insiders builds already

**Closed by mjbvz** 2017-07-19 20:23 UTC
Labels: duplicate, new release

**Comment by nonameolsson** [comment] 2017-07-19 21:04
@mjbvz Thanks for a fast reply!

But the problem was that I was running the latest Insiders build, and I got the problem. So I uninstalled it and tried with the stable one. And the issue was the same.

That is why I wrote the stable version in my issue. I just installed the latest Insiders build and I can't still use Intellisense.

**Comment by mjbvz** [comment] 2017-07-19 21:16
Do you see the same error on the latest insiders? There are few other issues that have similar symptoms to this

**Comment by nonameolsson** [comment] 2017-07-19 21:17
@mjbvz Hm, I'm not sure. Now I just tried with Insiders again, and it seems like there is another error. I'll upload a video.

**Comment by nonameolsson** [comment] 2017-07-19 21:21
@mjbvz https://youtu.be/7njKLa2zv5k This is the error I'm having with Insiders build.

**Comment by mjbvz** [comment] 2017-07-19 21:24
Thanks. That issue is a duplicate of #30425  / https://github.com/Microsoft/TypeScript/issues/17131 upstream. I'm working with the TS team to get a fix out soon

**Comment by nonameolsson** [comment] 2017-07-19 21:30
Oh, great!! Thanks for your help! 

Would the solution be to downgrade to v1.13.1 meanwhile?

**Comment by mjbvz** [comment] 2017-07-19 21:33
You don't need to downgrade all of VSCode, just the ts version. See this comment: https://github.com/Microsoft/vscode/issues/30425#issuecomment-314574428

You can also try disabling type acquisition as described in this comment: https://github.com/Microsoft/vscode/issues/30425#issuecomment-315660909
