### ISSUE TITLE
[Feature Request] Support for low-latency remote development

### ISSUE THREAD

**Issue by vandop** [Microsoft/vscode#24068] opened 2017-04-06 14:21 UTC
Hi,

Common scenario is to have my workstation in my office, but when travelling or working from home, I would like to have a low latency editing experience. Today I do it through RDP what is quite slow...

Facebook engineers seem to be pretty happy with Nuclide approach:
https://nuclide.io/docs/features/remote/

Thanks

**Comment by pwwang** [comment] 2017-06-05 18:08
+1

**Comment by rr32btg** [comment] 2017-07-18 00:18
+1

**Comment by mjbvz** [comment] 2017-11-09 01:28
Duplicate of #29194

**Closed by mjbvz** 2017-11-09 01:28 UTC
Labels: duplicate, feature-request, workbench
