### ISSUE TITLE
Text that pasted at .ipynb file is always double in two

### ISSUE THREAD

**Issue by raffizulvian** [microsoft/vscode#102135] opened 2020-07-10 16:11 UTC
Issue Type: <b>Bug</b>

Whenever I copy and paste some text in Jupyter Notebook files, the text that pasted is always double in two.

This should be normal, only pasted the text that already been copied before.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350
LiveServer|rit|5.6.1

</details>

**Comment by mjbvz** [comment] 2020-07-10 20:14
Duplicate of #101946

**Closed by mjbvz** 2020-07-10 20:14 UTC
Labels: new release
