### ISSUE TITLE
Code generation on copilot extension on vscode after prompt to reply in markdown bug

### ISSUE THREAD

**Issue by RicardoGEsteves** [microsoft/vscode#203571] opened 2024-01-26 20:25 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. After being prompt to generate code in markdown it fails to render all the code in markdown after the first block of 
```bash
code
``` 

2. 
![vscode-copilot](https://github.com/microsoft/vscode/assets/30535937/ca37c44e-3a12-4617-a534-279c60230ddc)

**Comment by mjbvz** [comment] 2024-02-08 00:17
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/760

**Closed by mjbvz** 2024-02-08 00:17 UTC
