### ISSUE TITLE
Font Editor Option Improvement

### ISSUE THREAD

**Issue by SrStick** [microsoft/vscode#125699] opened 2021-06-07 21:32 UTC
Could have a font selector in the editor's font edit option.
Something like a *\<select>* tag in which one would select among the fonts available in the system. Because the current way makes it very easy for the user to misspell the font name, or something like that.

**Comment by IllusionMH** [comment] 2021-06-07 22:44
/duplicate of #22917

Please upvote that issue

**Closed** 2021-06-07 22:44 UTC
Labels: *duplicate
