### ISSUE TITLE
Inconsistent CSS/SCSS highlighting after latest update

### ISSUE THREAD

**Issue by FridaNyvall** [Microsoft/vscode#39134] opened 2017-11-25 17:07 UTC
- VSCode Version: 1.18
- OS Version: Windows 10

Steps to Reproduce:

1.
![vscode2](https://user-images.githubusercontent.com/25387271/33232540-68aaf1d2-d208-11e7-9f97-4d2af2618452.png)

Line 16, 17, and 28 in the image. Different colors on the same type of selector pattern. With this seemingly random coloring it gets more difficult to spot errors.
Try writing some CSS and see how the colors on the same type of selectors differ.

2. Line 9 in the image: Also noticed that any "normal" selectors like p, h etc., have become white even if the Monokai theme usually styles them pink. I tried with different Monokai themes from the VS Marketplace, but all with the same white result.

Reproduces without extensions: Yes
I changed from Monokai to Visual Studion Dark, and the same inconsistency remained:
![vscode3](https://user-images.githubusercontent.com/25387271/33232567-bff87112-d208-11e7-89d2-a187de3e7edb.png)

**Comment by aeschli** [comment] 2017-11-27 09:36
duplicate of #38398, fixed in 1.19

**Closed by aeschli** 2017-11-27 09:36 UTC
