### ISSUE TITLE
In Breakpoints, cursor indicates click-ability where not actually clickable

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#10913] opened 2016-08-24 20:18 UTC
- VSCode Version: All (up to 1.4.0)
- OS Version: Windows 10

Steps to Reproduce:

1. Run debug task
2. Click on an any options in the "Breakpoints" but *not* on the checkbox.

The cursor is changed to a "pointer" (to use the CSS term) for the entire line in the breakpoints, but the only thing that is actually clickable is the checkbox. This is extremely annoying! Please make the entire line clickable or at least only show the pointer where is actually **is** clickable. But the former is preferable.

**Comment by isidorn** [comment] 2016-09-06 20:39
Well actually the whole line is clickable since clicking on a breakpoint will open the editor on that line in a file where a breakpoint is set.
This also conforms with our other trees (e.g explorer) - where we also show the pointer for the whole line.

If clicking on the entire line would enable / disable that breakpoint it would not be possible to just click on a breakpoint and be taken to that file.

The only place where clicking on a brekapoint does not make much sense are the All Exceptions / Uncaught Exceptions. However we also need to make them selectable to the checkboxes can be reached via keyboard for accessibility reasons.

Due to this I am closing this as designed. Feel free to propose other ideas on how to improve this.

**Closed by isidorn** 2016-09-06 20:39 UTC
Labels: debug
