### ISSUE TITLE
Editor line highlight only gets applied to line number

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16024] opened 2016-11-24 13:45 UTC
After some time the editor line highlight only gets applied to the line number, not the whole line

As seen in the picture for the quite light theme. This can also be easily spotted in the diff editor.
Sorry for not exact steps but regularly happens for me on OS X insider.

![screen shot 2016-11-24 at 14 43 35](https://cloud.githubusercontent.com/assets/1926584/20600562/8b1ea62a-b254-11e6-8fcc-fd1b0b24de37.png)

**Comment by rebornix** [comment] 2016-11-27 23:14
@isidorn Previously our highlight logic of current line was highlighting the line where the cursor is on. If there is any selection, do not highlight that line.

Right now after supporting to highlight the gutter of current line, we didn't make any change to above logic, what we added right now is, whether there is any selection or not, highlight the gutter of the line where the cursor is on.

In summary, the `repro steps` is selecting several chars :) But I'll say it's not a regression and has been there for quite a while. I'd like to close it first, if you think this behavior needs to be polished, feel free to reopen it.

**Comment by alexandrudima** [comment] 2017-11-23 11:24
Since its first implementation (>5 years) the line highlight is not rendered in the editor text area if there is selected text. I copied this behavior from Visual Studio.

**Closed by alexandrudima** 2017-11-23 11:24 UTC
Labels: as-designed, editor, feature-request
