### ISSUE TITLE
notebook.output.textLineLimit does not apply immediately

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177842] opened 2023-03-21 17:09 UTC
Testing #177719

Repro:

1. Create a notebook
2. Run something with 29 lines, there should not be a scrollbar
3. Set `notebook.output.textLineLimit` to 25, 🐛 there should be a scrollbar in the notebook but isn't

**Comment by Tyriar** [comment] 2023-03-21 17:14
Also consider changing the name of the setting to be more descriptive, something like scrollable line threshold?

**Comment by amunger** [comment] 2023-03-22 17:03
duplicate of https://github.com/microsoft/vscode/issues/177803

**Closed by amunger** 2023-03-22 17:03 UTC
