### ISSUE TITLE
Request a Feature

### ISSUE THREAD

**Issue by EklavyaJain-dot** [microsoft/vscode#112556] opened 2020-12-15 12:26 UTC
Issue Type: <b>Feature Request</b>

There should be a bug finder in the program for HTML and CSS

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.10240

**Comment by aeschli** [comment] 2020-12-16 08:53
You mean we should add validation. We don't have plans for that. There are extension that can do it, e.g. HTML Hint
Closing as duplicate of #23199

**Closed by aeschli** 2020-12-16 08:53 UTC
