### ISSUE TITLE
[terminal] (⌘K) was pressed. Waiting for second key of chord...

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#7240] opened 2016-06-06 08:08 UTC
- VSCode Version: 1.2.0-insider
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Press ⌘K to clear the integrated terminal.
2. The terminal gets cleared.
3. \**VS Code is still waiting for the second key of the ⌘K chord.*\*

⌘K is a recognised shortcut for clearing out the terminal on the Mac, but here it also conflicts with Code's other key bindings.

**Comment by Tyriar** [comment] 2016-06-07 02:10
I don't think ⌘K would be a good default because it would conflict with the chord keybindings. I'm going to close this off as a duplicate of https://github.com/Microsoft/vscode/issues/6603 which will allow you to set your own keybinding for clearing the terminal.

**Comment by Merott** [comment] 2016-06-07 09:24
@Tyriar I'm so used to the `⌘K` shortcut to clear the terminal on Mac, that I do it automatically without thinking. And I do it a lot.

The `⌘K` combination is even recognised in the Chrome DevTools Console for clearing the output - yet another reason that I'm so used to it.

I realise I may not be alone in this, so I have a suggestion:

- As per your suggestion, set the default "Clear Terminal" shortcut to something that won't conflict with another shortcut, especially the chord keybindings.
- If the user decides to override the default shortcut with `⌘K`, make sure that VSCode does not consider that as initiation of a chord keybinding.

This way, there won't be a conflict by default, but the user can opt to lose chord keybindings when in the context of the terminal, in favour of using the well-recognised shortcut.

Would you mind to reopen the issue to make it easier to find, and to continue the discussion?

**Comment by prashaantt** [comment] 2016-06-07 09:50
Thanks @Merott for chiming in. I use ⌘K very heavily too.

I wanted to take this discussion to a point where it might be possible to detach the default bindings whenever the terminal is in focus (except perhaps one shortcut to focus back on the workbench) and only retain the platform-level shortcuts that deal specifically with the terminal. I'm not sure if that's possible, but I suppose that would be most ideal.

**Comment by Tyriar** [comment] 2016-06-07 10:06
I can definitely sympathize, I'm not going to be happy unless I copy and paste in the terminal using <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>c</kbd> and <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>v</kbd> for example.

I'm not sure how the chord keybindings work exactly and what can override them, but there are conditions you can attach to keybindings, for example:

```
{ "key": "escape",                "command": "cancelSelection",
                                     "when": "editorHasSelection && editorTextFocus" },
```

A `terminalFocus` value seems like an ideal usage of the `when` property.

You can also [unbind keybindings as of v1.2.0](https://code.visualstudio.com/updates/May_2016#_workbench) which is another possible remedy.

So it's not possible right now to bind anything to ⌘K?

**Comment by Merott** [comment] 2016-06-07 10:29
@prashaantt - I came to Github the log this issue myself, but I found this one 👍  - It shouldn't be necessary to disable all keybindings in terminal. In fact, I wouldn't want that.

This can really be simplified to changing the behaviour of the `⌘K` shortcut, to not initiate chord keybindings if it gets used as a normal shortcut. Then, the user can do this:

```js
{
    "key": "cmd+k",
    "command": "terminal.action.clear",  // does not exist today
    "when": "terminalFocus"              // does not exist today
  }
```

With the updated `⌘K` behaviour, the above would work just as you'd expect, and only in the context of the terminal. If you leave out the `when` property, your `⌘K` chord bindings will stop altogether. It's not wise, but it's a choice.

Thanks @Tyriar for reopening the issue. And to answer your question, it seems that as of right now, `⌘K` can't be used as a keyboard shortcut, so the above would not be possible.

**Comment by Tyriar** [comment] 2016-07-05 17:57
Upstream issue: https://github.com/sourcelair/xterm.js/issues/118

**Comment by jensvdh** [comment] 2016-07-08 19:24
Any of idea of what it would take to implement a "terminalFocus" when condition? Would love to contribute to get this issue solved. I hit cmd+k quite a lot out of habit!

**Comment by Tyriar** [comment] 2016-07-08 20:03
@jensvdh https://github.com/sourcelair/xterm.js/issues/118 will probably fix the issue without requiring a terminalFocus event, I'm hoping to get this done for July.

**Comment by Tyriar** [comment] 2016-09-06 22:39
Closing in favor of #6603

**Closed by Tyriar** 2016-09-06 22:39 UTC
Labels: feature-request, integrated-terminal, mac, upstream
