### ISSUE TITLE
Ability to display only one side bar view at a time

### ISSUE THREAD

**Issue by jerryturcios08** [Microsoft/vscode#53762] opened 2018-07-06 23:51 UTC
Hello, I was wondering if a setting can be implemented where only one side bar view is displayed at a time. For example, let's say I only have the file explorer and the outline views in the side bar [open editors options is set to 0 in settings.json]. The file explorer view is fully expanded by default and the outline view is closed. However, when I click to fully expand the outline view, the file explorer view closes automatically. The same can be done vice versa and with more than two views in the side bar. I would love to hear from others about this idea, as I would personally find this useful. If such a feature exists through an extension, do let me know. Thanks!

**Comment by sandy081** [comment] 2018-07-09 08:02
Duplicate of #34136

**Closed** 2018-07-09 08:02 UTC
Labels: *duplicate, explorer-custom
