### ISSUE TITLE
runInTerminalRequest@debugAdapter problem when non-ascii characters in path

### ISSUE THREAD

**Issue by rogalmic** [microsoft/vscode#71917] opened 2019-04-08 08:52 UTC
Some non-ascii characters are not working as well in runInTerminalRequest args:
```
JSON.stringify(termArgs)
"{"kind":"integrated","title":"Bash Debug Console","cwd":".","args":["wsl.exe","bash","-c","cd \"/mnt/c/Users/Michał/Documents/src/bash-debugger/testing\"; while [[ ! -p \"/tmp/vscode-bash-debug-fifo-15640\" ]]; do sleep 0.25; done; \"bash\" \"/mnt/c/Users/Michał/Documents/src/bash-debugger/vscode-bash-debug/bashdb_dir/bashdb\" --quiet --tty \"/tmp/vscode-bash-debug-fifo-15640\" --tty_in \"/tmp/vscode-bash-debug-fifo-15640_in\" --library \"/mnt/c/Users/Michał/Documents/src/bash-debugger/vscode-bash-debug/bashdb_dir\" -- \"/mnt/c/Users/Michał/Documents/src/bash-debugger/testing/test.2.sh\" \"aaaa   \""]}"

```

results in following text executed in actual integrated terminal window/pan:
```
PS C:\Users\Michał\Documents\src\bash-debugger\testing> cd '.'; & 'wsl.exe' 'bash' '-c' 'cd "/mnt/c/Users/Micha/Documents/src/bash-debugger/testing"; while [[ ! -p "/tmp/vscode-bash-debug-fifo-15640" ]]; do sleep 0.25; done; "bash" "/mnt/c/Users/Micha/Documents/src/bash-debugger/vscode-bash-debug/bashdb_dir/bashdb" --quiet --tty "/tmp/vscode-bash-debug-fifo-15640" --tty_in "/tmp/vscode-bash-debug-fifo-15640_in" --library "/mnt/c/Users/Micha/Documents/src/bash-debugger/vscode-bash-debug/bashdb_dir" -- "/mnt/c/Users/Micha/Documents/src/bash-debugger/testing/test.2.sh" "aaaa   "'
: wiersz 0: cd: /mnt/c/Users/Micha/Documents/src/bash-debugger/testing: Nie ma takiego pliku ani katalogu 
bash: /mnt/c/Users/Micha/Documents/src/bash-debugger/vscode-bash-debug/bashdb_dir/bashdb: Nie ma takiego pliku ani katalogu
PS C:\Users\Michał\Documents\src\bash-debugger\testing>
```
"Nie ma takiego pliku ani katalogu" == No such directory because "ł" letter disappeared from "/mnt/c/Users/Micha/Docu....".

**Comment by Eskibear** [comment] 2019-08-07 08:47
Same problem with non-ascii chars. 
Java Debugger passes args like below, e.g.
```
path-to-java-binary -cp <classpaths> MainClass
```
<classpaths> might contain non-ascii chars, causing failure. 

See: https://github.com/microsoft/vscode-java-debug/issues/622

**Comment by connor4312** [comment] 2020-11-12 23:50
I'm not able to reproduce this. Running powershell, sending this

```
{
  "seq": 10,
  "type": "request",
  "command": "runInTerminal",
  "arguments": {
    "kind": "integrated",
    "title": "Node Debug Console",
    "cwd": "C:\\Test",
    "args": [
      "C:\\Program Files\\nodejs\\node.exe",
      "main.js",
      "test Michał"
    ],
  }
}
```

Gets the `"test Michał"` string over to the program without issue. Please let us know if you still run into it in recent versions of VS Code, and if so please share a repro case if possible. Thanks!

**Comment by Eskibear** [comment] 2020-11-13 09:20
@connor4312  Thank you for following up this issue. 

In 1.51.1, the "non-ascii char in command" mentioned in https://github.com/microsoft/vscode/issues/71917#issuecomment-519004276 seems to be fixed.

![image](https://user-images.githubusercontent.com/2351748/99050735-28563e80-25d3-11eb-8698-78653df298f5.png)

But you still can see, CMD wrongly decoded messages from stdout.  `你好` in utf-8 was wrongly decoded (with cp936) as `浣犲ソ`. I'm not sure if it's a problem that vscode can solve. In macOS everything works fine, but in windows, shells respect `chcp`. see https://ss64.com/nt/chcp.html FYI.

**Comment by connor4312** [comment] 2020-11-13 17:38
I'm not sure. @TylerLeonhardt do you have any ideas on that last comment?

**Comment by TylerLeonhardt** [comment] 2020-11-13 20:36
@Eskibear can you share what your `$OutputEncoding` is? And test if your code works after doing this:

```pwsh
$OutputEncoding = [System.Text.Encoding]::UTF8
```

**Comment by TylerLeonhardt** [comment] 2020-11-13 20:42
Also, if you wanna go above and beyond, and install the newest version of PowerShell (which is a side-by-side installation with the PowerShell that comes in the box... the exe is `pwsh.exe` instead of `powershell.exe`), you can get that:
* via the [Microsoft Store](https://www.microsoft.com/en-us/p/powershell/9mz1snwt0n5d?activetab=pivot:overviewtab)
* through whatever package manager on Windows you like
* [through these steps that help you install the MSI](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)

**Comment by Eskibear** [comment] 2020-11-14 03:09
I download latest `pwsh` MSI from Github, below is the output.

BTW `$OutputEncoding = [System.Text.Encoding]::UTF8` didn't change anything including `[Console]::OutputEncoding`. So later I tried `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`, and it was working. 

```
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\zy199\Desktop\中文目录> [Console]::OutputEncoding

EncodingName      : Chinese Simplified (GB2312)
WebName           : gb2312
HeaderName        : gb2312
BodyName          : gb2312
Preamble          :
WindowsCodePage   :
IsBrowserDisplay  :
IsBrowserSave     :
IsMailNewsDisplay :
IsMailNewsSave    :
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : False
CodePage          : 936


PS C:\Users\zy199\Desktop\中文目录> java Hello
浣犲ソ
PS C:\Users\zy199\Desktop\中文目录> [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
PS C:\Users\zy199\Desktop\中文目录> [Console]::OutputEncoding

Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001


PS C:\Users\zy199\Desktop\中文目录> java Hello
你好
PS C:\Users\zy199\Desktop\中文目录> 
```



BTW, for powershell.exe and cmd.exe, I can get it work by execute `chcp 65001` first. But it's not working for `pwsh.exe`, value of `[Console]::OutputEncoding` remain unchanged.

**Comment by connor4312** [comment] 2020-11-16 17:39
Thanks for the update. It sounds like the remaining problem was a matter of changing your shell configuration. You can run this every time you start powershell by adding it to [your profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1).

Closing this since it seems like the original issue was fixed in the interim.

**Closed by connor4312** 2020-11-16 17:39 UTC
Labels: bug, debug, needs more info
