### ISSUE TITLE
False positive - "Parsing error: Illegal import declaration (undefined)"

### ISSUE THREAD

**Issue by Jaans** [Microsoft/vscode#3532] opened 2016-02-28 04:09 UTC
I have ta simple ES6 module export and VS Code is seeing it as an error:

> Parsing error: Illegal import declaration (undefined)

Yet that is valid, and works just fine. 
Below is the entirety of the module:

```
export class ErrorEvent {
    constructor(structuredError) {
        this.structuredError = structuredError;
    }
}
```

The "export" keyword get's a red squiggly line and an error is added to VS Error error list for it.

Can this please be fixed?

**Comment by joaomoreno** [comment] 2016-03-01 08:18
cc @egamma

**Comment by dbaeumer** [comment] 2016-03-01 13:42
This is fixed in the upcoming Release.

![capture](https://cloud.githubusercontent.com/assets/1931590/13428599/d0adb170-dfbb-11e5-9488-a29627e0ef99.png)

**Comment by Jaans** [comment] 2016-03-01 13:50
Excellent! Thanks for that!

Does the upcoming release by any chance also include a fix for ES7 Class properties being seen as a "Duplicate identifier". Refer the following snippet, where the red squiggly is for `someProperty = false;` and the hover tooltip gives the duplicate identifier message :

```
export class SomeClass {
    
    someProperty = false;

    someMethod() {
        this.someProperty = true;
    }
}
```

**Comment by egamma** [comment] 2016-03-03 11:48
Regarding:
> "Parsing error: Illegal import declaration (undefined)"

This looks like an error message from ESLint and it shows up when you do not have `sourcetype modules` configured in your `eslintrc` configuration file (see below). The latest version of the ESLint extension now prefixes such errors from ESLint with `[eslint]`. 
```json
{
    "parserOptions": {
        "sourceType": "module"
    },
}
```

@Jaans Can you please update your vscode-eslint extension to verify whether my theory is correct.

**Comment by egamma** [comment] 2016-03-03 11:49
>a fix for ES7 Class properties being seen as a "Duplicate identifier"

This looks like a duplicate of Microsoft/TypeScript#6997

**Comment by Jaans** [comment] 2016-03-03 12:04
Thanks for the feedback. I actually don't have the ESLint extension installed.
Are you saying I should install it to fix the issue?

![image](https://cloud.githubusercontent.com/assets/3510981/13493713/62516074-e18b-11e5-87d9-063ec1e0bc09.png)


FYI: Running VSCode 0.10.8
And I can confirm the original issue from the ticket `Parsing error: Illegal import declaration (undefined)` has been fixed.

**Comment by unional** [comment] 2016-03-08 06:27
This error shows up on `.ts` files just now after VSCode update to 0.10.10

**Comment by dbaeumer** [comment] 2016-03-09 11:52
This doesn't happen in TS files.

**Comment by dbaeumer** [comment] 2016-03-09 11:54
In JS you now get which is IMO the correct behavior:

![capture](https://cloud.githubusercontent.com/assets/1931590/13634452/ff2b10fc-e5f5-11e5-91d7-9e2eb41325ab.png)

**Closed by dbaeumer** 2016-03-09 11:54 UTC
Labels: bug, js

**Comment by unional** [comment] 2016-03-09 12:00
For the project I have problem with, it is because the file is detected as JavaScript due to the shebang

**Comment by dbaeumer** [comment] 2016-03-09 14:25
The shebang issue is known and worked on.

**Comment by Andrew1431** [comment] 2017-01-29 15:02
I am having this issue in my project. And these solutions are not fixing the problem. Any ideas?
