### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by izzaldin2001** [Microsoft/vscode#34158] opened 2017-09-11 17:24 UTC
- VSCode Version: VSCode 1.16.0
- OS Version: Windows 10 64x 1703

The problem:
No support for HTML Entities. I just need to add HTML Entities like &copy; ( & copy ; ) and others to the HTML support in VS Code please.

**Comment by aeschli** [comment] 2017-09-12 08:16
duplicate of #17928

**Closed by aeschli** 2017-09-12 08:16 UTC
Labels: new release
