### ISSUE TITLE
Lag when editing code while WebGL is open in Chrome

### ISSUE THREAD

**Issue by Anheurystics** [Microsoft/vscode#26610] opened 2017-05-14 01:37 UTC
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a tab rendering rather heavy WebGL, keep it as the focused tab
2. Go to VSCode, try to edit (scroll around, type) a file

I'm not sure if this is a bug, as I'm not sure why Chrome's performance should affect VSCode's. I'm using the latest version, but I noticed this as well on older versions.

**Comment by Anheurystics** [comment] 2017-05-14 02:09
Sorry, I didn't see the two other previous issues on this ( #26125 and #22132)

**Comment by egamma** [comment] 2017-05-14 06:56
@Anheurystics thanks for duplicate searching, closing as a duplicate of #26125 and #22132

**Closed by egamma** 2017-05-14 06:56 UTC
Labels: duplicate
