### ISSUE TITLE
Breadcrumbs picker can't toggle normally in Custom Editor on macOS

### ISSUE THREAD

**Issue by fangbinwei** [microsoft/vscode#101181] opened 2020-06-27 10:55 UTC
- VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
- OS version: Darwin x64 19.5.0

Steps to Reproduce:

1. open custom editor (e.g. `preview image` by builtin extension) or use this [official custom editor sample](https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample)
2. toggle the breadcrumbs picker, it's difficult to expand the list view.

![image](https://user-images.githubusercontent.com/13298807/85920526-0ae43a80-b8a7-11ea-97c1-26de2ac5b245.png)

It seems this problem only happened when using custom editor. BTW, my os is darwin.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2020-07-01 07:01
This the webview and its [async focus behaviour](https://github.com/microsoft/vscode/blob/94eb764129a532bcd8098d302fbdc4b3af71d17e/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L302)

The following sequence of events is happening

1. user selects breadcrumbs item and (thereby moves to breadcrumbs)
1. breadcrumbs move focus back to editor pane
1. breadcrumbs opens picker (which closes on blur)
1. webview takes focus and thereby closes the picker

@mjbvz This seems to be a known issue on your side for which you have already deployed some quick pick workaround: https://github.com/microsoft/vscode/blob/94eb764129a532bcd8098d302fbdc4b3af71d17e/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L306

**Comment by mjbvz** [comment] 2020-07-01 22:02
Thanks for the investigation @jrieken. Not a regression as far as I can tell so moving to July

**Comment by mjbvz** [comment] 2020-10-20 03:45
Duplicate of #108596 (newer issue I know, but I already linked the commit to that one)

**Closed by mjbvz** 2020-10-20 03:45 UTC
Labels: breadcrumbs, bug, webview
