### ISSUE TITLE
Inlay hints make everything jumpy and nervous

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#130580] opened 2021-08-11 14:50 UTC
Overall I think injected text hints are a cool and useful feature. My biggest dislike while self hosting is that it makes everything jumpy and nervous while I am typing.
As a simple improvement maybe consider to debounce aggressively while a user is typing so that there would be no jumping then.

In the example below I am typing on this [line](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugSession.ts#L907)

![recording (3)](https://user-images.githubusercontent.com/1926584/129051583-0591f516-b60b-4299-b198-c70f6305f3e6.gif)

**Comment by hediet** [comment] 2021-08-11 14:57
See #129637. @mattbierner seems like the update of TS did not fix it?
@isidorn which version of TS are you using?

**Comment by isidorn** [comment] 2021-08-11 16:08
4.4.0-dev.20210802

**Comment by mjbvz** [comment] 2021-08-11 17:36
Duplicate of #129637 

Please make sure you are using the new workspace version of TS. It should be 4.5-dev.20210810

**Closed by mjbvz** 2021-08-11 17:36 UTC
