### ISSUE TITLE
The selection display is invisible

### ISSUE THREAD

**Issue by wen-gg** [microsoft/vscode#123618] opened 2021-05-12 01:39 UTC
For example，This background color
![image](https://user-images.githubusercontent.com/17865026/117905511-e13cd200-b305-11eb-8e9e-05c4a2178167.png)

**Comment by egamma** [comment] 2021-05-12 05:40
@wen-gg what theme are you using?

**Comment by wen-gg** [comment] 2021-05-12 07:18
@egamma Monokai

**Comment by Yqnn** [comment] 2021-05-12 07:39
I'm facing the same issue, only with Monokai theme.
(on macOS)

The search fields are also impacted:
![image](https://user-images.githubusercontent.com/588624/117937076-e0a43b80-b305-11eb-96b8-a566284df3ca.png)

**Comment by gjsjohnmurray** [comment] 2021-05-12 18:36
/duplicate of #123044

The fix should land in 1.56.2

**Closed** 2021-05-12 18:37 UTC
Labels: *duplicate, needs more info
