### ISSUE TITLE
Emmet doesnt respect inline elements

### ISSUE THREAD

**Issue by babobski** [microsoft/vscode#129829] opened 2021-07-30 09:23 UTC
Issue Type: <b>Bug</b>

I recently switched to vscode, only the biggest frustation I have is that Emmet always insert a div when completing a class. I'm used that Emmet looks at the parents elements and if it's a block element it uses a div elelement. But when the autocompletion is inside a inline elelement it autocompletes a span element. In vscode it always inserst a div wich is causing invalid html.

```html
<a href="">
    .test
</a>

<!-- It should expand to: -->
<a href="">
    <span class="test">|</span>
</a>

<!-- currently it expands to: -->
<a href="">
    <div class="test">|</div>
</a>
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.18GB free)|
|Process Argv|--crash-reporter-id c30c5460-fb42-48d6-a3d8-41454c79982a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.1.0
aspect-ratio|Bab|0.0.2
bootstrap-5-snippets|bab|0.0.2
svg-data-uri|Bab|0.0.3
tatu-diff|Bab|0.1.6
vertaaltags|bab|0.0.1
vscode-intelephense-client|bme|1.7.1
vscode-path-tools|cg-|0.0.4
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
php-debug|fel|1.17.0
php-pack|fel|1.0.2
triggertaskonsave|Gru|0.2.17
vscode-wordpress-hooks|joh|0.5.4
sftp|lix|1.12.9
lucidocean-plurge|Luc|0.0.5
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
html-css-class-completion|nat|1.20.1
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.8.0
format-html-in-php|rif|1.7.0
open-in-browser|tec|2.0.0
vscode-wakatime|Wak|14.0.2
searchwpdocs|yog|2.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by rzhao271** [comment] 2021-10-06 18:29
Duplicate of https://github.com/microsoft/vscode/issues/128038

**Closed** 2021-10-06 18:29 UTC
Labels: bug, *duplicate, emmet
