### ISSUE TITLE
No OOTB `ipynb` file support in Codespaces 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129504] opened 2021-07-27 09:39 UTC
Testing #129463 on "web":

I did not see any `ipynb` file support out of the box in a Codespace

Steps:
- open `https://github.com/odewahn/ipynb-examples` in MS Edge on macOS
- from the github's "Code" menu I selected the "Cloud" tab and created a Codespace on the current branch
- in the file explorer select `Cell Magics.ipynb`
- Observe:
  <img width="1092" alt="2021-07-27_11-12-04" src="https://user-images.githubusercontent.com/1898161/127131313-feefa421-0ad4-41ad-8b01-7d278301bdeb.png">
  is this the "native notebooks UI"? 
- pressing the "Install" button installed the "Jupyter" extension
- nothing changed for the opened notebook file `Cell Magics.ipynb`
- reselecting the file in the browser showed this:
  <img width="1443" alt="2021-07-27_11-15-04" src="https://user-images.githubusercontent.com/1898161/127131731-9d7d0a74-cedc-441f-822e-8fe723c3ed47.png">
- this happens for all files

The "About" box of the web UI shows this:

<img width="586" alt="2021-07-27_11-38-00" src="https://user-images.githubusercontent.com/1898161/127132463-40d837ab-ac06-4bce-b6b0-b36ac63515cd.png">

**Comment by roblourens** [comment] 2021-07-28 00:46
This is stable, you will have to switch to Insiders

**Comment by joyceerhl** [comment] 2021-07-28 22:57
Duplicate of https://github.com/microsoft/vscode/issues/129502?

**Closed** 2021-07-29 04:46 UTC
Labels: needs more info
