### ISSUE TITLE
Content of editor window jumps up and down when markdown side-by-side preview is open

### ISSUE THREAD

**Issue by urmilparikh** [Microsoft/vscode#25687] opened 2017-04-30 07:37 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open a markdown file to editing
2. Open side-by-side preview.
3. Edit file in the left (editor) pane.

As the preview updates in right pane, content of left pane keeps jumping up and down, making it very difficult to edit.

**Comment by mjbvz** [comment] 2017-05-02 00:52
Thanks for the report. This sounds like a duplicate of #25125. Hopefully I'll be able to look into this for the next release

**Closed by mjbvz** 2017-05-02 00:52 UTC
Labels: bug, duplicate, markdown
