### ISSUE TITLE
Scroll bar and minimap arrive at the start / end before reaching the first or last line

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#22759] opened 2017-03-16 20:56 UTC
- VSCode Version: 1.11.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

Settings "editor.wordWrap": "on"

1.Take a file with many lines. This example was using angular.js 1.6.3
2.Scroll down the page using the minimap or the scroll bar to the end.
3.Note that the minimap or scrollbar has come to an end, but we still have more rows.
4.Go back to the beginning using the minimap or the scroll bar to start.
5.See that the minimap or the scroll bar has reached the beginning but we still have more lines.

Atom works properly.

Note: I know that VSCode has an empty space at the end in the files (this is cool), I believe this has no influence.

![scroll1](https://cloud.githubusercontent.com/assets/19866231/24041757/9c10cd68-0aed-11e7-983e-30eb2ae25fbc.gif)

**Comment by alexandrudima** [comment] 2017-04-26 10:21
For very large files we artificially inflate the height of the slider such that it is easy to grab via the mouse. 

This is implemented in a quite crude way, where the slider height is inflated in both vertical directions (up and down). This might lead to the slider appearing to be all the way to the bottom, even if this is not the case.

**Comment by alexandrudima** [comment] 2017-06-06 14:00
Duplicate of #6710

**Closed by alexandrudima** 2017-06-06 14:00 UTC
Labels: bug

**Comment by Tekbr** [comment] 2017-06-09 19:55
Thank you so much @alexandrudima . 👏 👏 😄
