### ISSUE TITLE
Typescript language service does not autocomplete types from referenced projects

### ISSUE THREAD

**Issue by sunniejai** [microsoft/vscode#78728] opened 2019-08-08 20:42 UTC
VSCode Version: 1.37.0 (user setup)
OS: Windows 10.0.17763
Typescript Version: 3.5.2

Currently if you setup a monorepo with two typescript projects 
/foo
   index.ts
/bar
   index.ts

and bar references foo. using the references feature in typescript 3.

Here's a sample tsconfig.json
```{
  "compilerOptions": {
       "target": "es2016",
       "module": "commonjs",
       "moduleResolution": "node",
       "declaration": true,
       "declarationMap": true,
       "sourceMap": true,
       "composite": true
  },
  "references": [
    { "path": "../foo" }
  ]
}
```

If in /foo/index.ts you export a function/const named `blah`, intellisense will not provide auto complete in /bar/index.ts to auto import that symbol. This happens even if you've already compiled /foo so that all the declaration files are already there.

It would be nice if VS code can show autocomplete for those symbols exported in the referenced projects, and auto import them as well. 

This might help with giving a workaround to this issue as well because you may be able set it up to work locally on different packages without using symlinks and instead using the `paths` config in tsconfig.json instead? https://github.com/Microsoft/vscode/issues/25312

It could also be nicer if the references config had a name field along with path to setup the alias (you could probably just do it with paths) though

**Comment by mjbvz** [comment] 2019-08-13 16:17
Duplicate of https://github.com/microsoft/TypeScript/issues/26913

Please share any feedback upstream on TypeScript

**Closed by mjbvz** 2019-08-13 16:17 UTC
