### ISSUE TITLE
Markdown Preview screen does not respond to keyboard shortcuts

### ISSUE THREAD

**Issue by typoon** [microsoft/vscode#111381] opened 2020-11-26 18:49 UTC
- VSCode Version: 1.51.1
- OS Version: Linux x64 5.4.0

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

Steps to Reproduce:

1. Open a file with Markdown in it
2. Open the Markdown preview pane to the right side of your Markdown file
3. Click the Markdown preview pane to focus it
4. Press ctrl+shift+p to open the `Show All Commands` bar
5. Execute the command `View: Navigate to the View on the Left`
6. Notice that nothing happens 

Does this issue occur when all extensions are disabled?: Yes

Expectation: The commands from the `Show All Commands` bar should work in the `Markdown Preview` window (and also the keyboard shortcuts of those commands).

**Comment by gjsjohnmurray** [comment] 2020-11-26 19:26
/confirm also in 1.52.0-insider

You might have more success with the commands named `View: Focus Right Editor Group` and `View: Focus Left Editor Group`. However the default keybindings for these use a chord, i.e. they both begin with `Ctrl+K`. It seems that the Markdown Preview doesn't handle chords properly. Watch the status bar for the message reporting about waiting for the second key of the chord. When on Markdown Preview this message disappears prematurely, leaving no opportunity for me to press the second key. In contrast, entering the Ctrl+K, Ctrl+RightArrow chord when on the raw markdown editor in the left group works correctly.

**Comment by susiwen8** [comment] 2020-12-25 12:43
I'm working on this issue

**Comment by mjbvz** [comment] 2021-10-21 01:02
I am no longer able to reproduce this with VS Code insiders on MacOS and windows . I think it is potentially a duplicate of #119076

**Closed by mjbvz** 2021-10-21 01:02 UTC
Labels: bug, help wanted, webview, confirmed
