### ISSUE TITLE
Allow custom "paste as"

### ISSUE THREAD

**Issue by mbaas2** [microsoft/vscode#184704] opened 2023-06-09 09:58 UTC
I like the idea of the new "Paste As". Unfortunately it doesn't seem to cover my most common use case for it (or maybe I misunderstood the doc): when pasting a file[name], I'd like options to

- make absolute filename[s] relative to the edited file's location
- replace `\` with `/`

And related: when pasting a URL into .md, wouldn't it be nice if VC checked if we're pasting into `()` and if not, would provide an option to do (perhaps even asking for the title of the link)?

**Comment by mjbvz** [comment] 2023-06-12 18:06
Duplicate of #30066

**Closed by mjbvz** 2023-06-12 18:06 UTC
