### ISSUE TITLE
Debug unsaved files

### ISSUE THREAD

**Issue by xieranmaya** [Microsoft/vscode#46046] opened 2018-03-18 08:25 UTC
- VSCode Version: any
- OS Version: any

Steps to Reproduce:

1.as to issue #21681, existing files which didn't saved can also debug
2.but new files which never saved can not debug 

Does this issue occur when all extensions are disabled?: Yes/No
not important, it's core functionality

related issues: 

https://github.com/Microsoft/vscode/issues/285
https://github.com/Microsoft/vscode/issues/21681

**Comment by isidorn** [comment] 2018-03-19 10:01
This seems like a duplicate of https://github.com/Microsoft/vscode/issues/19415
Closing as we will not support this in the forseable future

**Closed by isidorn** 2018-03-19 10:01 UTC
