### ISSUE TITLE
Application status stuck on  "initializing JS/TS language features"

### ISSUE THREAD

**Issue by stevenyoung** [Microsoft/vscode#68160] opened 2019-02-07 19:49 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open the app.
2. Look for app developers to resort to standard bureaucratic responses instead of helpful diagnostics.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-03-11 18:05
Duplicate of #68896

**Closed by mjbvz** 2019-03-11 18:05 UTC
Labels: extensions, needs more info
