### ISSUE TITLE
comments hang around

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#178147] opened 2023-03-23 16:05 UTC
Note: I don't think this is a regression, I've seen this for awhile

I have no pull requests checked out (main is my branch) and yet comments are hanging around

![Screenshot 2023-03-23 at 9 04 37 AM](https://user-images.githubusercontent.com/29464607/227264236-0a29ffb5-4b86-4bfc-a073-84b3b46185e2.png)

in the output channel:

```
2023-03-23 09:03:36.432 [info] TemporaryState> Error in initialization: Unable to delete nonexistent file 'vscode-userdata:/Applications/code-insiders-portable-data/user-data/User/globalStorage/github.vscode-pull-request-github/temp'
2023-03-23 09:03:36.482 [info] Looking for git repository
2023-03-23 09:03:36.482 [info] Found 0 repositories during activation
2023-03-23 09:03:36.482 [info] Git repository found, initializing review manager and pr tree view.
2023-03-23 09:03:36.501 [info] Registering git provider
2023-03-23 09:03:36.501 [info] Review> Validate state in progress
2023-03-23 09:03:36.501 [info] Review> Validating state...
2023-03-23 09:03:36.501 [info] Cannot updates repositories as git is uninitialized
2023-03-23 09:03:39.578 [info] Repo state for file:///Users/meganrogge/Repos/vscode changed.
2023-03-23 09:03:39.578 [info] Repo file:///Users/meganrogge/Repos/vscode has already been setup.
2023-03-23 09:03:39.578 [info] Review> no matching pull request metadata found for current branch merogge/active
2023-03-23 09:03:39.579 [info] Review> No matching pull request metadata found on GitHub for current branch merogge/active
2023-03-23 09:04:01.923 [info] Git initialization state changed: state=initialized
2023-03-23 09:04:01.923 [info] Review> Validate state in progress
2023-03-23 09:04:01.923 [info] Review> Validating state...
2023-03-23 09:04:05.145 [info] Found GitHub remote for folder /Users/meganrogge/Repos/vscode
2023-03-23 09:04:06.683 [info] Review> Queuing additional validate state
2023-03-23 09:04:06.685 [info] Review> no matching pull request metadata found for current branch merogge/active
2023-03-23 09:04:09.423 [info] Review> No matching pull request metadata found on GitHub for current branch merogge/active
2023-03-23 09:04:09.443 [info] Review> Validating state...
2023-03-23 09:04:09.453 [info] Found GitHub remote for folder /Users/meganrogge/Repos/vscode
2023-03-23 09:04:10.080 [info] Review> current branch main is associated with pull request #176054
2023-03-23 09:04:10.080 [info] Review> Resolving pull request
2023-03-23 09:04:10.674 [info] Review> no matching pull request metadata found for current branch main
2023-03-23 09:04:11.653 [info] Review> Fetching pull request data
2023-03-23 09:04:11.653 [info] PullRequestTree> Adding PR #176054 to tree
2023-03-23 09:04:11.669 [info] Review> Register comments provider
2023-03-23 09:04:11.671 [info] Review> Display pull request status bar indicator and refresh pull request tree view.
2023-03-23 09:04:11.671 [info] Review> Using focus mode = true.
2023-03-23 09:04:11.671 [info] Review> State validation silent = true.
2023-03-23 09:04:11.671 [info] Review> PR show should show = false.
2023-03-23 09:04:13.656 [info] GitContentFileSystemProvider> Getting change model (file:///Users/meganrogge/Repos/vscode) content for commit 2aaf9c14ad534786ef737456db5704621eadb748 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/media/xterm.css
2023-03-23 09:04:13.659 [info] GitContentFileSystemProvider> Getting repository (file:///Users/meganrogge/Repos/vscode) content for commit 2aaf9c14ad534786ef737456db5704621eadb748 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/media/xterm.css
2023-03-23 09:04:13.660 [info] GitContentFileSystemProvider> Getting change model (file:///Users/meganrogge/Repos/vscode) content for commit df40683e5038f21997761b3ac422999d49f86b13 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/media/terminal.css
2023-03-23 09:04:13.662 [info] GitContentFileSystemProvider> Getting repository (file:///Users/meganrogge/Repos/vscode) content for commit df40683e5038f21997761b3ac422999d49f86b13 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/media/terminal.css
2023-03-23 09:04:13.665 [info] GitContentFileSystemProvider> Getting change model (file:///Users/meganrogge/Repos/vscode) content for commit df40683e5038f21997761b3ac422999d49f86b13 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts
2023-03-23 09:04:13.668 [info] GitContentFileSystemProvider> Getting repository (file:///Users/meganrogge/Repos/vscode) content for commit df40683e5038f21997761b3ac422999d49f86b13 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts
2023-03-23 09:04:13.669 [info] GitContentFileSystemProvider> Getting change model (file:///Users/meganrogge/Repos/vscode) content for commit 3dd87832d82f074c76931af221a1dc871d619af7 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts
2023-03-23 09:04:13.673 [info] GitContentFileSystemProvider> Getting repository (file:///Users/meganrogge/Repos/vscode) content for commit 3dd87832d82f074c76931af221a1dc871d619af7 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts
2023-03-23 09:04:13.674 [info] GitContentFileSystemProvider> Getting change model (file:///Users/meganrogge/Repos/vscode) content for commit f7c106bd0205cd60d845c7a3f0e2fcd30a33ad25 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts
2023-03-23 09:04:13.677 [info] GitContentFileSystemProvider> Getting repository (file:///Users/meganrogge/Repos/vscode) content for commit f7c106bd0205cd60d845c7a3f0e2fcd30a33ad25 and path /Users/meganrogge/Repos/vscode/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts
2023-03-23 09:04:27.765 [info] RateLimit> Unexpectedly low rate limit: 30
2023-03-23 09:04:27.765 [warning] RateLimit> REST Rate limit remaining: 29, /search/issues
2023-03-23 09:04:27.836 [info] RateLimit> Unexpectedly low rate limit: 30
2023-03-23 09:04:27.836 [warning] RateLimit> REST Rate limit remaining: 28, /search/issues
2023-03-23 09:04:28.133 [info] RateLimit> Unexpectedly low rate limit: 30
2023-03-23 09:04:28.133 [warning] RateLimit> REST Rate limit remaining: 27, /search/issues
```

**Comment by alexr00** [comment] 2023-03-23 17:04
Thanks for the logs! The logs show this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4508

**Closed by alexr00** 2023-03-23 17:04 UTC
