### ISSUE TITLE
Debuggers not enabled under current context keys should not provide debug configurations

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#134141] opened 2021-09-29 16:46 UTC
Testing https://github.com/microsoft/vscode/issues/133146

1. Have a debugger disabled via its `when` clause
2. In a folder without a launch.json, run "create a launch.json file"
3. The disabled debugger can still provide configurations

While there might be some edge use cases for this, I think it should be disabled.

**Comment by isidorn** [comment] 2021-09-29 16:58
I think duplicate of https://github.com/microsoft/vscode/issues/133957

**Closed** 2021-09-29 23:50 UTC
