### ISSUE TITLE
Highlight is persistent after deleting a code block

### ISSUE THREAD

**Issue by evansom** [Microsoft/vscode#9858] opened 2016-07-27 16:46 UTC
- VSCode Version: 1.3
- OS Version: Mac OS

Steps to Reproduce:
1. Highlight a block of code for deletion
2. Delete the code block
3. The highlight is persistent and now highlights some lines of code that replaces the deleted code block
4. This leads to unintentional deletion of newly highlighted line (say, if you press 'backspace' twice when trying to delete some whitespace before the initially highlighted code block)

**Comment by kieferrm** [comment] 2016-08-02 01:38
@evansom  I was unable to reproduce that. With what file types do you see this? Do you see the same behavior when you launch vscode with the `--disable-extensions` command line argument?

**Comment by evansom** [comment] 2016-08-03 08:52
@kieferrm I have tried launching vscode with extensions disabled and I still see the same issue. However I must add that this does not occur all the time (may be 30 % of the time). I see this when working with HTML and Js.

See images below; 
- Step 1: Code block highlighted
- Step 2: After deletion

Hope they help.
<img width="1463" alt="step 1" src="https://cloud.githubusercontent.com/assets/8733674/17359750/ad4991f2-5970-11e6-93f3-64045240f2d4.png">
<img width="1462" alt="step 2" src="https://cloud.githubusercontent.com/assets/8733674/17359749/ad49323e-5970-11e6-960b-d03df7706499.png">

**Comment by alexandrudima** [comment] 2016-08-12 09:48
@evansom Is it possible you still have the mouse button pressed when pressing `Delete` ?

**Comment by alexandrudima** [comment] 2017-05-10 19:42
Duplicate of #6478.

**Closed by alexandrudima** 2017-05-10 19:42 UTC
Labels: editor, needs more info
