### ISSUE TITLE
[snippets] Support for regular expressions with Snippet Variables

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#17821] opened 2016-12-25 21:40 UTC
It'd be nice if regular expression support is added to the new snippet syntax (great work btw!! 👍). With variables such as "TM_FILENAME", the *extension* of the file is also added when the snippet is expanded, and when using snippets in code (eg. React), it's rarely the case that I'd need the extension of the file, thus I feel the need to have functionality to remove it from the replaced string.

I think this might be related closely to https://github.com/Microsoft/vscode/issues/6920?
Ref: https://manual.macromates.com/en/snippets Section 7.2

**Comment by jrieken** [comment] 2016-12-27 09:13
Yes - closing this as duplicate of #6920.

**Closed by jrieken** 2016-12-27 09:13 UTC
