### ISSUE TITLE
TS Server fatal error:  Cannot read properties of undefined (reading 'charCount')

### ISSUE THREAD

**Issue by tiam-at** [microsoft/vscode#231093] opened 2024-10-11 07:33 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.1 (Universal) (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id 008499fa-1952-477b-beb7-cca352e80d4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
flutter-snippets|ale|3.0.0
vscode-intelephense-client|bme|1.12.6
turbo-console-log|Cha|2.10.4
ccs-flutter-color|cir|2.0.0
dart-code|Dar|3.98.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
html-preview-vscode|geo|0.2.5
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
vscode-power-mode|hoo|3.0.2
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.25.0
background-cover|man|2.5.5
flutter-tree|mar|1.0.0
template-string-converter|meg|0.6.1
vscode-language-pack-ja|MS-|1.94.2024100909
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
live-server|ms-|0.4.15
awesome-flutter-snippets|Nas|4.0.1
indent-rainbow|ode|8.3.1
tsimporter|pmn|2.0.1
vscode-css-navigation|puc|1.15.0
LiveServer|rit|5.7.9
trailing-spaces|sha|0.4.1
code-spell-checker|str|3.0.1
vscode-pets|ton|1.27.0
vscode-icons|vsc|12.9.0
quokka-vscode|Wal|1.0.653
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
cc771715:31146322

```

</details>

**Comment by mjbvz** [comment] 2024-10-29 20:37
Duplicate of https://github.com/microsoft/typescript/issues/60118

**Closed by mjbvz** 2024-10-29 20:37 UTC
