### ISSUE TITLE
Suggest widget stalls typing

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2027] opened 2016-01-14 16:58 UTC
* open viewLine.ts
* after the first interface in the file type as fast as you can
* `class HorizontalRange implements EditorBrowser.IHorizontalRange `

Please observe the 153ms stall due to `onDidSuggest` > `refresh`

![image](https://cloud.githubusercontent.com/assets/5047891/12331073/46dddcce-bae8-11e5-8ad5-d174b972478f.png)

**Comment by joaomoreno** [comment] 2016-01-14 19:47
Duplicate of #1923. For some reason, something changed here.

**Closed by joaomoreno** 2016-01-14 19:47 UTC
Labels: bug, important
