### ISSUE TITLE
Open Workspace Floating Button

### ISSUE THREAD

**Issue by Eventyret** [Microsoft/vscode#68216] opened 2019-02-08 09:18 UTC
Issue Type: <b>Bug</b>

After latest update (1.32.0-insider) 1c50a8756 you have a floating "Open Workspace" button bottom right (see screenshot)
![Screenshot](https://i.imgur.com/oZakA30.png)
This is after opening a folder, and you can't click on it or remove it.

VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:16:17.233Z)
OS version: Windows_NT x64 10.0.18329

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (49.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
emojisense|bie|0.4.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
typescript-angular-plugin|cyr|1.2.0
dart-code|Dar|2.22.3
githistory|don|0.4.6
jquerysnippets|don|0.0.1
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
bootstrap-4-cdn-snippet|eve|1.1.5
json2ts|Gre|0.0.6
rest-client|hum|0.21.1
dotenv|mik|1.0.1
vscode-autoprefixer|mrm|2.2.0
csharp|ms-|1.17.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
comment-ts|sal|0.9.11
code-settings-sync|Sha|3.2.4
gitflow|vec|1.2.1
vscode-wakatime|Wak|1.2.5
vscode-import-cost|wix|2.12.0
JasmineSnippets|xab|1.0.1
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by Eventyret** [comment] 2019-02-08 09:35
Just to note it sits on "top" of the integrated terminal

**Comment by ddotlic** [comment] 2019-02-08 09:46
Just wanted to say that this is not Windows specific, am running latest macOS and see exactly the same thing. IMHO it's not terminal related, just sitting close to it in the editor.

What's _really_ annoying is that even after opening developer tools and removing this from the DOM, switching the editor will make it show up again 😠 

Could someone issue a quick fix please? If not, for situations like this - since I'm only running insider and not "regular" version, is there a way to temporarily downgrade (maybe we should add a facility for this)?

**Comment by Eventyret** [comment] 2019-02-08 09:58
@Tyriar seems we can confirm it's not an integrated terminal issue.

**Comment by ddotlic** [comment] 2019-02-08 10:28
@Eventyret  This is really, really weird: the buttons have just disappeared from my editor, yet I don't recall doing anything for this to happen (definitely have _not_ restared VS Code, nor have I reloaded the workspace). 🤔

**Comment by dalDevelo** [comment] 2019-02-08 11:36
Another voice to the choir here, I'm using macOS and I'm seeing this button in both the insiders and exploration latest updates.

**Comment by Eventyret** [comment] 2019-02-08 14:16
@ddotlic same here it disappeared after a while. but still should not be displayed there.

**Comment by Ash258** [comment] 2019-02-08 14:20
This should be fixed with 92eedf890c66994783e785b00321189d70e55228

**Comment by Eventyret** [comment] 2019-02-08 17:13
Thanks @Ash258  @aeschli 👍 Presume we can close this then

**Comment by dalDevelo** [comment] 2019-02-08 17:28
Confirmed fixed in latest insiders build. Exploration build still awaiting fix.

**Comment by ddzy** [comment] 2019-02-09 01:43
It doesn't seem to be fixed.

**Comment by aeschli** [comment] 2019-02-09 12:41
dup of #68231, insiders has the fix, I merged and retriggered exploraration

**Closed** 2019-02-09 12:41 UTC
Labels: integrated-terminal
