### ISSUE TITLE
Drag and drop file to terminal uses incorrect path separator

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#139853] opened 2021-12-28 17:09 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 11 + WSL2 Ubuntu 20.04

Steps to Reproduce:

https://user-images.githubusercontent.com/29582865/147590182-cd47bf14-16e1-4fb6-9252-79060738976b.mp4

Seems to be happening on any Remote target (SSH, Codespaces, WSL, Containers).

Same as https://github.com/microsoft/vscode/issues/131844

**Comment by felipecrs** [comment] 2021-12-28 17:12
Also happens in today's VS Code - Insiders.

**Comment by felipecrs** [comment] 2021-12-28 17:14
Answering

Does the `explorer.copyRelativePathSeparator` setting help here at all?

_Originally posted by @JacksonKearl in https://github.com/microsoft/vscode/issues/131844#issuecomment-914855313_

No:

https://user-images.githubusercontent.com/29582865/147590517-2c5b9af9-a931-4578-b537-500520da08ef.mp4

And even if it did, it would be nice if we didn't require to set this manually.

**Comment by Licenser** [comment] 2022-01-20 16:18
for refference, I'm having the same error :)

**Comment by felipecrs** [comment] 2022-02-14 16:47
Reading through https://github.com/microsoft/vscode/issues/131844 it seems that the issue was once solved in the past. If anyone could provide any hint about the implementation, I could give a try to fix it by myself. I tried to look into but I could not find anything useful.

**Comment by JacksonKearl** [comment] 2022-04-07 16:18
duplicate of #120270

**Closed by JacksonKearl** 2022-04-07 16:18 UTC
Labels: bug, file-explorer, label-provider
