### ISSUE TITLE
 Illegal value 31 for `line`

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5481] opened 2016-04-19 08:08 UTC
Issue Id: <b>9d49987e-1058-1c47-d977-23b53a6f81d2</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8<br />*Stack* <br />Error: Illegal value 31 for `line`<br />    at t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:29390) <no sourcemaps><br />    at Object.t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:28204) <no sourcemaps><br />    at TrailingSpaces.matchTrailingSpaces (\shardulm94.trailing-spaces-0.2.8\out\src\trailing-spaces\trailing-spaces.js:150:95) <no sourcemaps><br />    at \shardulm94.trailing-spaces-0.2.8\out\src\trailing-spaces\trailing-spaces.js:59:23 <no sourcemaps><br />    at e.invoke (\out\vs\workbench\node\pluginHostProcess.js:7:14035) <no sourcemaps><br />    at e.fire (\out\vs\workbench\node\pluginHostProcess.js:7:15488) <no sourcemaps><br />    at e._acceptSelectionsChanged (\out\vs\workbench\node\pluginHostProcess.js:19:7900) <no sourcemaps><br />    at t.e.handle (\out\vs\workbench\node\pluginHostProcess.js:15:12835) <no sourcemaps><br />    at c (\out\vs\workbench\node\pluginHostProcess.js:11:16222) <no sourcemaps><br />    at h (\out\vs\workbench\node\pluginHostProcess.js:11:16882) <no sourcemaps><br />

**Comment by jrieken** [comment] 2016-04-19 09:32
duplicate of  #5494

**Closed by jrieken** 2016-04-19 09:32 UTC
Labels: bug, error-telemetry
