### ISSUE TITLE
Markdown preview is laggy and distracting

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15851] opened 2016-11-22 02:06 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Notice that as i update the header below, the badge icons distractingly flash and take a while to render
![2016-11-21_18-03-20](https://cloud.githubusercontent.com/assets/762848/20508229/f19ba566-b014-11e6-869c-82f258e6477b.gif)

Repro: This is using the acorn README (npm install acorn, then open up in node_modules dir)

**Comment by mjbvz** [comment] 2016-11-22 20:01
The flashing badge is expected because that status image is explicitly not cached and must be retrieved from the server every time.

A normal image does not show this behavior:

![nov-22-2016 11-59-39](https://cloud.githubusercontent.com/assets/12821956/20539769/19d498a8-b0ab-11e6-8399-5f12b6912d74.gif)

There's no good solution to this.

Closing as by design.

**Closed by mjbvz** 2016-11-22 20:01 UTC
Labels: as-designed, markdown
