### ISSUE TITLE
Updating (Insiders) fails, cannot find "Code OSS"?

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#98146] opened 2020-05-19 08:15 UTC
Issue Type: <b>Bug</b>

I got a notification about 1.46.0 being available for Code Insiders and I ran the update as usually. It failed, telling me to look into a log file in the temp folder.

This log file contains:

```
May 19 09:38:42.275 INFO Starting: C:\Program Files\Microsoft Code OSS\Code - OSS.exe, true
May 19 09:38:42.278 ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft Code OSS\Code - OSS.exe
```

It is the first time I heard about the path `C:\Program Files\Microsoft Code OSS` (I expect the editor to live in `C:\Program Files\Microsoft VS Code Insiders`), and it exists but only contains a `tools` directory and an uninstaller. However, registry entries like `CodeOSSSourceFile` pointing to nonexisting paths there were created. I was worried that the installation got messed up somehow and downloaded a fresh installer for VS Code Insiders, but it seemed it was also trying to install "Code OSS" instead, which doesn't make sense. I googled what it is, and it seems it's to VS Code what Chromium is to Chrome, but that's not what I wanted - I wanted the VS Code Insiders version as before, not a non-Microsoft version with less functionality, so I'm not sure why a wrong installer is being linked [here](https://code.visualstudio.com/insiders/).

Can you help me solve the mystery?

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (2.63GB free)|
|VM|0%|
</details>

**Comment by IllusionMH** [comment] 2020-05-19 10:52
/duplicate of #98142

Fix is in progress. Also see https://github.com/microsoft/vscode/issues/98142#issuecomment-630706455

**Closed** 2020-05-19 10:52 UTC
Labels: *duplicate
