### ISSUE TITLE
VS Code Initially Opens Wrong Terminal

### ISSUE THREAD

**Issue by ashblox** [microsoft/vscode#132151] opened 2021-09-02 18:29 UTC
Issue Type: <b>Bug</b>

I had my default profile set to Git Bash for the last 2 years. Today, set a global gitconfig value (autocorrect 20) and all of a sudden new VS Code instances are spawning a PowerShell terminal instead of a bash one. (I set it on the command line instead of manually updating the file.)

I've confirmed that Git Bash is still my default profile. If I hit the plus icon, it will open a bash shell. I've also made sure to close the PowerShell terminal each time before opening the project again (in case it's saved as part of my workspace settings or something).

I've tried other projects as well. 

My user-settings.json are as follows: 
``` json
{
    "workbench.iconTheme": "vscode-icons",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "cucumberautocomplete.steps": [
        "features/step_definitions/*.rb",
    ],
    "cucumberautocomplete.syncfeatures": "features/tests/*feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "editor.renderWhitespace": "all",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "diffEditor.ignoreTrimWhitespace": false,
    "extensions.ignoreRecommendations": false,
    "json.maxItemsComputed": 10000,
    "security.workspace.trust.untrustedFiles": "open",
    "files.autoSave": "afterDelay",
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "debug.javascript.terminalOptions": {
    
    },
    "terminal.integrated.profiles.windows": {
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe (migrated)": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": []
        }
    },
    "terminal.integrated.defaultProfile.linux": ""
}
```

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (22.58GB free)|
|Process Argv|C:\\Repos\\RateManager\\credit-exposure-app --crash-reporter-id dd7f4885-0a2b-40dd-a0cd-c96c5c8d9c08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
csharp-to-typescript|adr|1.12.1
specflow-tools|ami|1.1.3
ng-template|Ang|12.2.0
npm-intellisense|chr|1.4.0
vscode-markdownlint|Dav|0.43.2
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
beautify|Hoo|1.5.0
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
ruby|reb|0.28.1
trailing-spaces|sha|0.3.1
gherkin-autocomplete|sil|1.3.3
vscode-icons|vsc|11.6.0
HCL|who|0.0.5
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
vsdyn420:30356812
vscus224cf:30358040

```

</details>

**Comment by jsta** [comment] 2021-09-02 19:56
A downgrade to v1.59.1 restored operations for me. 

I set `"update.mode": "none"` for good measure.

**Comment by TylerLeonhardt** [comment] 2021-09-02 20:30
duplicate of https://github.com/microsoft/vscode/issues/132149

cc @Tyriar @meganrogge

**Closed by TylerLeonhardt** 2021-09-02 20:30 UTC
Labels: new release

**Comment by ashblox** [comment] 2021-09-02 20:42
Thanks - downgrading worked!

**Comment by PhakornKiong** [comment] 2021-09-06 12:27
Downgrading to 1.59.1 works for me.
