### ISSUE TITLE
Allow extensions to add custom widgets / custom rendering to sidebar

### ISSUE THREAD

**Issue by th317erd** [Microsoft/vscode#68266] opened 2019-02-08 17:30 UTC
I love the extension GitLens, and would use it completely (instead of paying for GitKraken) if it only had a commit/merge graph. The author of GitLens says this isn't possible because VSCode currently doesn't allow custom rendering in the extension sidebar.

This feature request is to allow extensions to custom render HTML in the extension's sidebar (or elsewhere as well).

Please see the current open issue for this in the GitLens issue tracker for a better understanding (with a screenshot).

I think this would be an amazing extension feature for all extensions.

https://github.com/eamodio/vscode-gitlens/issues/472

**Comment by usernamehw** [comment] 2019-02-08 18:27
duplicate of #46585 ?

**Closed** 2019-02-11 00:25 UTC
Labels: *duplicate, extensions

**Comment by th317erd** [comment] 2019-02-11 00:33
Ah thanks! I search liked crazy before I created this issue and found nothing. :+1:
