### ISSUE TITLE
I can't type anything when cmd+n new file

### ISSUE THREAD

**Issue by pertrai1** [Microsoft/vscode#26404] opened 2017-05-10 19:26 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (c615b43be67170e166779c9020a249442c4f36fc, 2017-05-09T06:05:27.476Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-closetag|Compulim|1.1.0|
|EditorConfig|EditorConfig|0.9.3|
|beautify|HookyQR|1.0.2|
|html-css-class-completion|Zignd|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|tslint|eg2|0.14.0|
|auto-close-tag|formulahendry|0.3.12|
|theme-onedark-sublime|joshpeng|0.3.6|
|vscode-less|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|color-highlight|naumovs|2.1.3|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.7.0|
|vim|vscodevim|0.7.1|
|Material-theme|zhuangtongfa|2.7.3|;

---

Steps to Reproduce:

1. Use `cmd+n` for a new file to open
2. Try to type. I am not able to do any typing of a character at all

**Comment by pertrai1** [comment] 2017-05-10 19:45
Note that this does not happen in version 1.12.1 (1.12.1)

**Comment by alexandrudima** [comment] 2017-05-10 20:53
Duplicate of #26279

Workaround until the next insiders build: use `window.zoomLevel > 0`

**Closed by alexandrudima** 2017-05-10 20:53 UTC
