### ISSUE TITLE
Variable transformation doesn't work if undefined variables are used in the same snippet

### ISSUE THREAD

**Issue by Chingyat** [Microsoft/vscode#51769] opened 2018-06-13 14:12 UTC
Issue Type: <b>Bug</b>

Consider the following snippet:
```json
{
  "Class": {
    "prefix": "myclass",
    "body": [
      "class ${TM_FILENAME_BASE/(^|_)([a-zA-Z0-9])/${2:/upcase}/g} : public ${BaseClass} {\n",
      "\t$0",
      "};\n"
    ]
  }
}
```
The transformation `${TM_FILENAME_BASE/(^|_)([a-zA-Z0-9])/${2:/upcase}/g}` would normally remove the underscores and capitalize the filename, but in the snippet above, the file name is directly inserted without any transformation. However, after replacing `${BaseClass}` with `${1:BaseClass}`,
the snippet works as expected.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.16.14-300.fc28.x86_64

**Comment by jrieken** [comment] 2018-06-22 10:59
@Chingyat I actually cannot reproduce anymore... Can you give it a try with latest insiders please https://code.visualstudio.com/insiders/. We did make some changes in the variables world and this might have been fixed by that.

**Comment by Chingyat** [comment] 2018-06-23 05:01
I tried the snippet above with insiders in file `my_class.cpp`.
It should inserts:
```cpp
class MyClass : public BaseClass {

    
};
```
But it actually inserts:
```cpp
class My_class : public BaseClass {

    
};
```

**Comment by jrieken** [comment] 2018-06-25 07:48
Yeah, it looks like the `/g`-flag is getting lost

**Closed** 2018-06-25 08:06 UTC
Labels: bug, snippets
