### ISSUE TITLE
SSH not working - could not establish connection

### ISSUE THREAD

**Issue by ayush-j** [microsoft/vscode#115066] opened 2021-01-26 15:46 UTC
Version: 1.53.0-insider (user setup)
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:13:59.356Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Remote-SSH: Connect to SSH host
2. Select host

I have a SSH host added to my VS code install which had been working fine till yesterday. Today, I'm unable to connect. I can still remote into my machine using RDP and connect to it using console using "ssh <host>"

```
[21:06:43.760] Log Level: 2
[21:06:43.767] remote-ssh@0.63.0
[21:06:43.768] win32 x64
[21:06:43.768] SSH Resolver called for "ssh-remote+<ssh-host-name-removed>", attempt 1
[21:06:43.768] "remote.SSH.useLocalServer": false
[21:06:43.769] "remote.SSH.showLoginTerminal": false
[21:06:43.769] "remote.SSH.remotePlatform": {"<ssh-host-name-removed>":"windows","<ssh-host-name-removed>":"windows"}
[21:06:43.769] "remote.SSH.sshPath": undefined
[21:06:43.769] "remote.SSH.sshConfigurationFile": undefined
[21:06:43.769] "remote.SSH.useFlock": true
[21:06:43.769] "remote.SSH.lockfilesInTmp": false
[21:06:43.769] "remote.SSH.localServerDownload": auto
[21:06:43.769] "remote.SSH.remoteServerListenOnSocket": false
[21:06:43.769] "remote.SSH.showLoginTerminal": false
[21:06:43.770] SSH Resolver called for host: <ssh-host-name-removed>
[21:06:43.770] Setting up SSH remote "<ssh-host-name-removed>"
[21:06:43.787] Using commit id "1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3" and quality "insider" for server
[21:06:43.790] Install and start server if needed
[21:06:43.794] Checking ssh with "ssh -V"
[21:06:43.862] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[21:06:43.866] Remote command length: 8104/8192 characters
[21:06:43.868] Running script with connection command: ssh -T -D 53367 "<ssh-host-name-removed>" powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('<long base 64 text removed>')))))"  # RemoteSSHConfigurationScript
[21:06:43.868] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:06:43.962] > The command line is too long.
> ]0;C:\WINDOWS\System32\cmd.exe
[21:06:43.962] Got some output, clearing connection timeout
[21:06:44.335] "install" terminal command done
[21:06:44.336] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[21:06:44.336] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[21:06:44.337] Stopped parsing output early. Remaining text: ]0;C:\WINDOWS\System32\cmd.exe
[21:06:44.337] Failed to parse remote port from server output
[21:06:44.343] Resolver error: Error: 
	at Function.Create (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
```

**Comment by hyx52077** [comment] 2021-01-28 07:44
The command line is too long  .  I don't know how to solve this limitation

**Comment by ayush-j** [comment] 2021-01-28 08:39
Still happening.

```
Version: 1.53.0-insider (user setup)
Commit: 7b0cfdd04ad530a9c8d782c618afd79290be3d64
Date: 2021-01-27T08:59:32.031Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

@roblourens Could you take a look? My system config/setup hasn't changed but SSH has stopped working since Tuesday. This seems like a regression.

**Comment by ayush-j** [comment] 2021-01-29 08:55
microsoft/vscode-remote-release#4354

**Comment by jethas-bennettjones** [comment] 2021-01-29 15:51
> Still happening.
> 
> ```
> Version: 1.53.0-insider (user setup)
> Commit: 7b0cfdd04ad530a9c8d782c618afd79290be3d64
> Date: 2021-01-27T08:59:32.031Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042
> ```
> 
> @roblourens Could you take a look? My system config/setup hasn't changed but SSH has stopped working since Tuesday. This seems like a regression. If you need more info, let me know.

I downgraded to 0.62 and that resolved the issue. I'm pretty sure Rob knows about the issue but downgrading is a temporary workaround that has worked for me.

**Comment by roblourens** [comment] 2021-02-05 02:39
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/4354

**Closed by roblourens** 2021-02-05 02:39 UTC
