### ISSUE TITLE
Unable to save a file

### ISSUE THREAD

**Issue by neodisk17** [Microsoft/vscode#52228] opened 2018-06-18 19:21 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by neodisk17** [comment] 2018-06-19 18:33
After updating vs code to the latest version
Whenever i am making any changes in the file and try to save it
Its giving me an error that the content on the disk is newer and you might
want to compare it
But its contain the old changes

So i am unable to save the current file
I need to close the file and open it again to add my new changes to it.

I am mostly working on php files
So i dont know about other file types,

Its very frustrating to use VS Code in such conditions.

**Comment by chrmarti** [comment] 2018-06-20 07:19
Maybe you have a background task that touches the file? Which OS are you on?

**Comment by bpasero** [comment] 2018-06-20 08:08
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by neodisk17** [comment] 2018-06-20 19:45
I tried disabling the vs code extension but still i am getting the same
issue

I tried using this
 code --disable-extensions

but it doesn't causing any effect
as I am getting some unexpected error from php intellisense
Which are not correct, Its giving me an error on a perfect syntax statement

And after some time i realise that if i changed the language from php to
html
I am not getting this type of error

**Comment by bpasero** [comment] 2018-06-25 04:58
@neodisk17 are you using a remote file system maybe or is this a local disk?

**Comment by neodisk17** [comment] 2018-06-25 16:52
No ,I am using local disk.
The file is saved in my local system
And I am not using any remote connection

**Comment by bpasero** [comment] 2018-06-25 18:18
@neodisk17 but you already verified that this only happens for some file types but not all?

**Comment by neodisk17** [comment] 2018-06-25 18:42
Yes, Its happenng only for PHP files.
My work is on html,css,js and php

But my majority of work is on PHP
And it always showing me the message to compare the files.

Please help me how can i solve this problem.

**Comment by bpasero** [comment] 2018-06-25 18:45
@neodisk17 do you have any tool running outside of VSCode that could touch/write the PHP files?

**Comment by neodisk17** [comment] 2018-06-25 19:13
Only my git bash is running in the backgroung.

**Comment by bpasero** [comment] 2018-06-26 04:44
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by neodisk17** [comment] 2018-06-26 19:54
ok

I will try using it.

**Comment by neodisk17** [comment] 2018-06-29 19:19
I had tried the insider builds,it was great, I am not getting any file saving issues  while using it.

**Comment by bpasero** [comment] 2018-06-30 07:53
@neodisk17 what if you configure the exact same settings and install the exact same extensions you have in the stable version for that insiders version, does it still work?

**Comment by neodisk17** [comment] 2018-06-30 18:09
Nope I haven't install all the extension.

I had only installed which were important for me at that time.

I will try to install all the extension and let you know

**Comment by neodisk17** [comment] 2018-07-06 18:08
I had use the same configuration and install the same extensions as of the
stable version,

But it seems that there are no problems while saving files that arise in
stable version

I just wanted to know that when will be the insiders preview  will be
merged in the stable version?

**Comment by chrmarti** [comment] 2018-07-09 08:53
Insiders from when you reported it working has been released as the new stable version last Wednesday. Let us know when you see this again. Thanks.

**Closed by chrmarti** 2018-07-09 08:54 UTC
Labels: needs more info
