### ISSUE TITLE
Cursor and Keystrokes are acting strange

### ISSUE THREAD

**Issue by dedicatedcloud** [microsoft/vscode#165887] opened 2022-11-09 04:58 UTC
Hi When even I used the browser based VS Code, my cursor starts acting up and won't delete the characters in the correct order, it jumps and seems to have whitespace in front of it, can you advise on what to do ?
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by alexdima** [comment] 2022-11-25 22:36
Could you please share some steps to reproduce?

**Comment by dedicatedcloud** [comment] 2022-11-26 01:02
Hi

Wll it basically is just when ever I open the code editor by pressing period/full stop on any of my repos the cursor seems to be out of place on the two screenshots you can see it's actually on a character stays there after I delete. On other occasions it sometimes deletes 2 or 3 characters before the last character, what it should delete, I will attach two screentshots
![Screenshot 2022-11-26 00 30 22](https://user-images.githubusercontent.com/98156514/204066608-6494a474-25ea-4043-ace9-dd6bff0cb959.png)
![Screenshot 2022-11-26 00 31 06](https://user-images.githubusercontent.com/98156514/204066626-e7a89650-6285-4749-9b50-158a4c71994c.png)

**Comment by alexdima** [comment] 2022-11-28 10:06
Thank you for clarifying. This looks like a duplicate of https://github.com/microsoft/vscode/issues/160702

**Closed by alexdima** 2022-11-28 10:06 UTC
Labels: info-needed
