### ISSUE TITLE
Debug hover doesn't show 'Generator'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5808] opened 2016-04-26 09:49 UTC
from testing test item #4949 

```javascript
 function*fibonacci() {
    var pre = 0, cur = 1;
    for (;;) {
      var temp = pre;
      pre = cur;
      cur += temp;
      yield cur;
    }
  }
var it = fibonacci();
for (var n of it) {
  // truncate the sequence at 1000
  if (n > 1000)
    break;
  console.log(n);
}
```
- set a breakpoint on the console log
- run program and when stopped hover of `it`
-> The variables view, watch and debug console all render it as 'Generator'. Hover just shows 'proto'

**Comment by isidorn** [comment] 2016-05-02 14:39
This is as designed, our hover just shows the list of children of an object.
In this case that can be confusing since there is only one child and you thought that the child is the actual value.

Chrome solves this issue by showing in the first line the value of the object, and then the list of children. If you think that is the way to go let me know and I will create a new feature request.
Closing this as designed

**Closed by isidorn** 2016-05-02 14:39 UTC
Labels: debug
