### ISSUE TITLE
Installing an extension never completes

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6947] opened 2016-05-26 23:19 UTC
- VSCode Version:1.1.0-alpha
- OS Version:Windows 10

Steps to Reproduce:

1. Try to install Markdown Lint or Sean's Spell checker
2. The installation never completes and the icon stays in the wavy animation.
If you stop VS Code and restart the extensions are not installed.

This doesn't seem to be an issue with Theme or snippet extensions.

**Comment by alexandrudima** [comment] 2016-05-27 13:20
I can reproduce, funny I went happy through the smoke test, as the 1337 theme gets installed OK. Maybe we can update the smoke test to cover more heavy-weight extensions.

**Comment by joaomoreno** [comment] 2016-05-27 13:25
Great find.

**Comment by isidorn** [comment] 2016-05-27 15:08
Loser.

**Comment by gregvanl** [comment] 2016-05-27 15:18
Not sure I understand why the issue was reopened or Isi's comment but I verified that the issue appears to be fixed.  I can install extensions like Sean's spell checker and MarkdownLint.

**Comment by joaomoreno** [comment] 2016-05-27 15:27
@gregvanl Isi mentioned myself. 👍  We tackled the issue at his desk and just reopened since we saw some issues.

Ended up being related to #6959, so we'll track it there. Closing this one.

**Closed by joaomoreno** 2016-05-27 15:27 UTC
Labels: bug, important

**Comment by isidorn** [comment] 2016-05-27 15:29
@gregvanl sorry about all that, it was just @joaomoreno talking to himself on my keyboard :)
