### ISSUE TITLE
Customize peek

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#17072] opened 2016-12-12 12:05 UTC
It's more of a feature request. I am referring to the peek display zone (the one on blue background).
It's quite a great thing, but it's annoying that uses all the horizontal space. 
In my case I like to use the right side where there is a lot of empty space (no code) to display something. And keep the code from the current file visible and unchanged (when peek is used it shifts the code a few lines lower.  
It would be great if we could change its size and even position anywhere. That way we can see both the peek version and the current file however we like.

**Comment by dfroze** [comment] 2016-12-12 12:10
If this is ok and approved. I would like to work on this feature if possible (i am guessing it's an easy one and I would like to use this opportunity to help :D)

**Comment by jrieken** [comment] 2016-12-12 13:11
closing as duplicate of #3220

**Closed by jrieken** 2016-12-12 13:11 UTC
