### ISSUE TITLE
Format on Save and Format produce different results

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12827] opened 2016-09-27 22:03 UTC
Testing #12639.

Version 1.6 insiders
MacOS

Below is a case in which the result of auto-format and the result of an explicit format differ. 

![wubg3io1fr](https://cloud.githubusercontent.com/assets/4674940/18893589/692f9876-84c3-11e6-9de7-5c6c8d753936.gif)

**Comment by jrieken** [comment] 2016-09-28 08:06
@kieferrm This is a JS or a TS file?

**Comment by kieferrm** [comment] 2016-09-28 15:52
@jrieken this is a JS file.

**Comment by jrieken** [comment] 2016-10-04 11:06
@kieferrm I cannot reproduce with similar code. Please point me to your code location or paste it here

**Comment by jrieken** [comment] 2016-10-11 14:05
@kieferrm ping

**Comment by jrieken** [comment] 2016-10-25 15:29
Closing until steps allowing to reproduce this are supplied

**Closed by jrieken** 2016-10-25 15:29 UTC
Labels: bug, format, needs more info
