### ISSUE TITLE
Markdown underscores prevent word highlighting

### ISSUE THREAD

**Issue by jbrower2** [microsoft/vscode#119959] opened 2021-03-26 15:15 UTC
- VS Code Version: 1.54.3
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open an editor with the Markdown Language Mode
2. Enter the following:

  ```markdown
  When you click on _this_ word
  this will highlight
  but _this_ will not
  ```

3. Click on the first instance of the word "this"
4. The second instance of "this" is highlighted, but the first and third are not
5. If you remove all the underscores, all three instances will highlight as expected
6. The same applies for double underscores i.e. bold text

Does this issue occur when all extensions are disabled?: Yes

---
*Edit by @hediet*

![image](https://user-images.githubusercontent.com/2931520/137911327-2e42b77a-d6a6-4197-85a5-962542609d76.png)

**Comment by mjbvz** [comment] 2021-10-21 00:38
Duplicate of #86332

**Closed by mjbvz** 2021-10-21 00:38 UTC
Labels: bug, languages-basic, markdown
