### ISSUE TITLE
Ability to integrate a textbox into a treeview

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117139] opened 2021-02-20 17:22 UTC
As an extension developer, I'd love to be able to integrate a textbox into a treeview node so I can compose more elaborate user interfaces

**Comment by alexr00** [comment] 2021-02-22 12:42
Duplicate of https://github.com/microsoft/vscode/issues/97190

**Closed by alexr00** 2021-02-22 12:42 UTC

**Comment by gplumb** [comment] 2021-02-22 14:08
The duplicate issue you linked to is closed. This is still a valid ask, can
you re-open the linked ticket before shutting this one down?

**Comment by alexr00** [comment] 2021-02-22 14:29
@gplumb the duplicate is an open issue.

**Comment by gplumb** [comment] 2021-02-22 14:36
My apologies, this looked closed when I checked!

Thanks!
