### ISSUE TITLE
Enabling word wrapping is not working

### ISSUE THREAD

**Issue by ferrecromain** [microsoft/vscode#93267] opened 2020-03-23 20:45 UTC
- VSCode Version: 1.43.1
- OS Version: 10.0.18363.720

Steps to Reproduce:

1. in settings : Editor: wordWrap = "wordWrapColumn" and Editor: Word wrap column = 80
2. From menu View > Enable toggle word wrap
3. Create a new .md file
4. Writing text on one line and more than 80 chars is possible

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-03-23 20:54
Duplicate of #72559

#74195 Would make this more discoverable

**Closed by mjbvz** 2020-03-23 20:54 UTC

**Comment by ferrecromain** [comment] 2020-03-23 21:04
Yes, thanks you @mjbvz, so as it seems that these settings are applied for languages that do not have default word wrapping rules (unlike markdown). We have to override them.
