### ISSUE TITLE
Keybindings input not remembered

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35077] opened 2017-09-26 10:52 UTC
1. Preferences > keyboard shortucts > type something
2. Open some other editor, go back to keyboard shortucts -> input is cleared
3. This does not align with our general UX story where we try to preserve as much UX state as possible

**Comment by sandy081** [comment] 2017-09-28 12:38
Duplicate of #23543

**Closed by sandy081** 2017-09-28 12:38 UTC
Labels: keybindings, ux
