### ISSUE TITLE
Detaching from a parent debugging session leaves a zombie child session

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#108351] opened 2020-10-08 23:51 UTC
Issue Type: <b>Bug</b>

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

1. Attach to or launch a debugger that spawns a child process and attaches to the child as a nested debugger session
1. Detach from the parent session
1. The child session stays attached and the debugger toolbar stays active, but the child session disappears from the call stack pane.

I am using [vscode-byebug](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-byebug) and [byebug-dap](https://rubygems.org/gems/byebug-dap). I've attached my test ruby file and launch configurations. For attaching, I am running `bundle exec byebug-dap -f --wait --unix debug.socket main.rb`.

- [example.zip](https://github.com/microsoft/vscode/files/5351775/example.zip)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/879055/95524498-29be9680-0997-11eb-936c-ed88e8f96335.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id b66d31ed-6df8-483a-9367-cc739cc188f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
Bookmarks|ale|11.3.1
quitcontrol-vscode|art|3.1.3
rails|bun|0.16.7
vscode-gemfile|bun|0.4.0
better-toml|bun|0.3.2
vscode-test-explorer-status-bar|con|1.1.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
permute-lines|ear|1.1.0
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vscode-byebug|eth|0.1.0
vscode-go-test-adapter|eth|0.1.3
vscode-firefox-debug|fir|2.9.1
gitlab-workflow|Git|3.3.0
go|gol|0.17.2
vscode-graphql|Gra|0.3.10
vscode-test-explorer|hbe|2.19.1
docomment|k--|0.1.18
cpptools|ms-|1.0.1
hexeditor|ms-|1.3.0
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.3.0
ruby|reb|0.27.0
slim|sia|0.1.2
rewrap|stk|1.13.0
code-spell-checker|str|1.9.2
haml|vay|1.0.1
vscode-ruby|win|0.27.0

</details>

**Comment by connor4312** [comment] 2020-10-09 00:11
It's expected that the child session will send a `terminated` even when it exits. If this is not the case then I believe VS Code will be in the state that you show. Are you able to determine whether this is what you're running into?

**Comment by firelizzard18** [comment] 2020-10-09 03:25
In this case, a long-running process with worker process children is running. When VSCode attaches to the main process, the debug adapter informs the extension of the children (via a custom event), and VSCode attaches to the children, as child debug sessions. When VSCode disconnects from a given session, the process/debug adapter (intentionally) does not exit.

This appears to be a side-effect of the fact that VSCode leaves the Call Stack view empty if there is only a single debug session, which is single threaded. If I start a second thread in the child, the two threads appear in the Call Stack view. I still find this behavior confusing, but I guess it's not a bug. I might open a feature request: "VSCode should show *something* in the Call Stack view for a single, single-threaded debug session."

**Comment by connor4312** [comment] 2020-10-09 19:33
Ah, yea. The call stack is empty when not paused and with a single session. That's as designed at the moment, but is now different than what the js debugger does for instance (since the js debugger uses a logical parent session). Forwarding to Isi for thoughts.

**Closed** 2020-10-20 10:06 UTC
Labels: debug

**Comment by isidorn** [comment] 2020-10-20 10:07
Correct this is designed. Call Stack is empty when not paused and with a single session.
However I agree it is confusing so I have pushed a commit to improve this. Namely we will show a RUNNING label in the CALL STACK header area when there is a single session running. Try it out with VS Code insiders from tomorrow and let us know what you think.

Alternative is to show the session in this case, however then the UI might be jumping too much when a breakpoint gets hit (where did my session go).
