### ISSUE TITLE
Viewlet views sizes not preserved across sessions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39020] opened 2017-11-23 10:18 UTC
1. Extensions viewlet, notice 2 panes in the split view, make them equal size
2. Reload vscode -> sizes are not preserved, they are back to their original size

This can also be reproduced for debug views and I am sure this worked 2 months ago.
You can also notice the broken behavior in the current stable.
Assigning to November since I find this behavior quite bad. If you are not sure what broke this you can assign back to me.

**Comment by sandy081** [comment] 2017-11-23 11:56
Duplicate of #37189

**Comment by sandy081** [comment] 2017-12-08 16:26
This is not duplicate of #37189. This is about view sizes are not retained in all side bar views which is a pretty bad regression. Marked it as a duplicate of other by mistake.

Hence reopening it and planning to for November.

**Comment by sandy081** [comment] 2017-12-08 16:30
Fixed by fc312d75b3575bda8e0cfb7114c2f88a1b88fdb3 and d1c11162fad6992bf40936ab94aaafbd75b55e6f

**Closed by sandy081** 2017-12-08 16:30 UTC
Labels: bug, important, workbench
