### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined" when debugging

### ISSUE THREAD

**Issue by AlanRosenthal** [Microsoft/vscode#27640] opened 2017-05-30 20:50 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|gitlens|eamodio|3.5.1|
|cpptools|ms-vscode|0.11.2|;

---

Steps to Reproduce:

1. Sometimes when you try and debug the error "Cannot read property 'toLowerCase' of undefined" pops up.  You have to restart VSCode to debug again.

**Comment by AlanRosenthal** [comment] 2017-05-30 20:56
`messageService.ts:125 Cannot read property 'toLowerCase' of undefined: TypeError: Cannot read property 'toLowerCase' of undefined
    at t.updateStateAndEmit (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:536578)
    at t.doCreateProcess (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:542397)
    at textFileService.saveAll.then.t.configurationManager.resloveConfiguration.then.t.runPreLaunchTask.then.t.messageService.show.message (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:541363)
    at n.Class.define.cancel.then (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:75132)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:541197
    at n.Class.define.cancel.then (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:75132)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:540857
    at n.Class.derive._creator.then (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:75132)
    at t.createProcess (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:540787)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:540604`

**Comment by isidorn** [comment] 2017-05-31 09:21
Please try this with latest vscode stable (1.13) it should be fixed.
Let me know if you still see the issue with latest vscode and I will reopen
Thanks

**Closed by isidorn** 2017-05-31 09:21 UTC

**Comment by Starkiller4011** [comment] 2017-05-31 13:02
Running VS Code on Mint and regardless of language I am working with every time I go to debug I get this message and sometimes I also get "Debug adapter process has terminated unexpectedly". I'm not entirely sure if it's something I am doing or not, my launch.json is all default minus the following line 
`"program": "${workspaceRoot}/statman.cpp",`

**Comment by AlanRosenthal** [comment] 2017-06-01 20:31
In VSCode 1.13 (insider) the C/C++ extension is updated to 0.11.3 and this bug is happening:
https://github.com/Microsoft/vscode-cpptools/issues/792

**Comment by pieandcakes** [comment] 2017-06-02 03:01
@isidorn I tried latest Insiders with latest 0.11.3 cpptools and I can't duplicate this. Can you help shed some light as to what was fixed and what is happening?

**Comment by isidorn** [comment] 2017-06-02 09:27
I have added an additional null guard to prevent this from happening, you can try it out in tomorrow's insiders.

Now what seemed to be happening is that a timining issue is making the debug state be undefined, which should never be the case. The current fix does not fix the underlying problem but only handlles the problem more gracefully.
Since this only seems to be happening with the C++ adapter it might be that some unique event timing is triggering this on the vscode side. To investgiate the root cause further I would need exact repro steps.

For now the null guard should improve this experience
