### ISSUE TITLE
[Settings Sync / Stable] Invalid "Microsoft Sign In" redirect when enabling settings sync + connected to WSL2 (Remote - WSL extension)

### ISSUE THREAD

**Issue by d0cz** [microsoft/vscode#104674] opened 2020-08-14 17:27 UTC
- VSCode Version: 1.48.0 (stable)
- OS Version: Windows 10 2004 (OS Build 19041.450)

Steps to Reproduce:

1. Go to the Account icon (above the Manage cog, bottom left area)
2. Sign in
3. Select "Sign in with Microsoft"
4. Browser opens with invalid URL: http://127.0.0.1:50711/signin?nonce... (there's a token after this but I don't think it's relevant here, also the port is not always the same)

obs: GitHub works fine

Does this issue occur when all extensions are disabled?: No

Launching VSCode with --disable-extensions the browser opens with the valid URL: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize....

EDIT:

I was just checking for the extension that could be causing this and turns out it's because I was connected to my WSL2.

Disconnecting or opening a new window (out of WSL) works fine, so it seems that the "Remote - WSL extension" is doing something for that sign in option (again, github worked fine while connected to wsl/active extension)

**Comment by d0cz** [comment] 2020-08-14 17:31
I was just checking for the extension that could be causing this but turns it's because I was connected to my WSL2.

Disconnecting or opening a new window (out of WSL) works fine, so it's not really an extension issue.

**Comment by IainVM** [comment] 2020-11-16 14:53
This also occurs with the Remote-SSH extension, though seems to happen because you get sent to `localhost:58041` but when the Remote - SSH extension tries to forward the extension so you can connect doesn't ensure it's the same port number. So you have `58040 -> localhost:58041` in the extension. 

Changing the URL in the browser to point at the correct port brings up the correct Microsoft login page. 

Either the extension needs to ensure it maps the same ports both sides, or the web url needs to use the host port number that gets forwarded.

**Comment by RMacfarlane** [comment] 2020-11-17 23:09
Closing as a duplicate of https://github.com/microsoft/vscode/issues/104628

**Closed by RMacfarlane** 2020-11-17 23:09 UTC
Labels: authentication, bug
