### ISSUE TITLE
[xterm] `CTRL+C` not work in Terminal

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#30742] opened 2017-07-15 01:27 UTC
- VSCode Version: 1.14 (no issue in 1.13)
- OS Version: Windows 10

Steps to Reproduce:

1. Install [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) (It is just for repro, the issue should not be related to this extension)
2. In 'Docker Images' tree explorer, Select one Docker image (e.g. jekyll/jekyll:pages) and click 'Run'
3. When it is running, try to use `CTRL+C` to stop it

Actual:
There is error as below:
![image](https://user-images.githubusercontent.com/1050213/28234520-018a28d0-6933-11e7-8b12-7ffd8cbe76f5.png)

Reproduces without extensions: Disable all other extensions, except 'Docker Explorer', just for repro

**Comment by Tyriar** [comment] 2017-07-15 06:59
@formulahendry can you expand the uncaught exception at the top?

**Comment by formulahendry** [comment] 2017-07-16 05:47
This error happens when I put cursor to the terminal, before triggering `Ctrl+C`:
![image](https://user-images.githubusercontent.com/1050213/28244960-ec9709ca-6a2c-11e7-9bc8-dfdc87f1bf7f.png)

After triggering `Ctrl+C`:
![image](https://user-images.githubusercontent.com/1050213/28244962-213f4566-6a2d-11e7-9a14-7c8bb27bc149.png)

**Comment by Tyriar** [comment] 2017-07-17 16:45
Duplicate of https://github.com/Microsoft/vscode/issues/20505

**Closed by Tyriar** 2017-07-17 16:45 UTC
Labels: integrated-terminal, needs more info, new release
