### ISSUE TITLE
Opening Vscode with `code` cli causes terminal to hang. Ubuntu on WSL

### ISSUE THREAD

**Issue by ryanhockstad** [microsoft/vscode#193417] opened 2023-09-19 00:06 UTC
Type: <b>Bug</b>

Opening a file or specific folder in the terminal (for example by typing `code .`) will cause the terminal to hang.  This is a minor issue, because `ctrl c` will free the terminal and Vscode will remain open.

This issue happens on my instance of Ubuntu 22.04 in the most up to date version of WSL2. 

I tried a fresh install of Ubuntu and ran into the same issue. Rolling back to Vscode 1.81 fixes  the problem.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.89GB (43.24GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/plurn/learning/unix/apue --remote=wsl+Ubuntu --crash-reporter-id a505ba86-9749-43c4-bbf8-63f20f9a5c13|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|Memory (System)|31.29GB (29.99GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.81.3
go|gol|0.39.1
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by ryanhockstad** [comment] 2023-09-19 13:12
```
+ COMMIT=abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\ryanh\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.3
+ [ -n c:\Users\ryanh\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.3 ]
+ wslpath -u c:\Users\ryanh\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.3
+ WSL_CODE=/mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts/wslCode.sh
+ /mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts/wslCode.sh abd2f3db4bdb28f9e95536dfa84d8479f1eb312d stable /mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/plurn/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts/wslCode.sh
+ /mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts/wslDownload.sh abd2f3db4bdb28f9e95536dfa84d8479f1eb312d stable /home/plurn/.vscode-server/bin
+ [ ! -d /home/plurn/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.Y1tEZl
+ env
+ dirname /mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/ryanh/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/ryanh/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.3/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.Y1tEZl VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID /home/plurn/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/bin/remote-cli/code 
.

```

**Comment by aeschli** [comment] 2023-09-19 19:15
Oh, I see what you mean: Duplicate of https://github.com/microsoft/vscode/issues/193453

**Closed by aeschli** 2023-09-19 19:14 UTC
Labels: info-needed, WSL
