### ISSUE TITLE
Support Link Titles with single quotes in Welcome Views

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91442] opened 2020-02-25 18:50 UTC
Testing #91269

> Content supports Markdown style links (including title, href and tooltip) and new lines with \n

It doesn't appear that using like titles like `[link](url 'title goes here')` is supported:

![image](https://user-images.githubusercontent.com/35271042/75277155-5d5c0000-57bc-11ea-8abc-4f8f9994587c.png)

But it does work in our markdown preview:

![image](https://user-images.githubusercontent.com/35271042/75277327-a318c880-57bc-11ea-8be4-456f2a97cd84.png)

**Comment by joaomoreno** [comment] 2020-02-26 20:05
These do work, but with double quotes. We can make it work with single quotes as well. cc @bpasero

**Comment by joaomoreno** [comment] 2020-02-26 20:06
@bpasero Since I'm quite busy this week and out for the next 4 weeks.... and you're the regex master here, wanna take this?

**Comment by bpasero** [comment] 2020-02-27 06:20
Open for grab.

**Comment by bpasero** [comment] 2020-02-27 06:20
Oh, maybe this is just a bug because you say it works with double quotes...

**Comment by connor4312** [comment] 2020-02-28 18:50
The title attribute is now applied, but the tmLanguage doesn't recognize it

![image](https://user-images.githubusercontent.com/2230985/75578139-300b8e00-5a18-11ea-9fb0-26ce7055b35d.png)

**Comment by bpasero** [comment] 2020-02-29 06:34
@connor4312 may I ask how this is a "verification found" if the issue is unrelated to the original one? My understanding is that you found a colorization issue, can you report it as new issue then?

**Comment by connor4312** [comment] 2020-02-29 06:46
Sure, I marked it as 'found' as what looked like incomplete support for the new the single-quote syntax in markdown. I'll open a new issue for the coloring. Works otherwise 🙂

**Comment by bpasero** [comment] 2020-02-29 06:53
@connor4312 thanks, this issue is not about markdown at all, it is about rendering the title for an attribute when you use markdown for the new welcome extension point for empty views.

**Closed** 2020-02-29 06:53 UTC
Labels: bug, verified, workbench-welcome
