### ISSUE TITLE
Support multiple searches at the same time

### ISSUE THREAD

**Issue by shantai** [Microsoft/vscode#45585] opened 2018-03-12 12:23 UTC
很多时候我们希望对多个关键字进行搜索，并针对结果进行分析，但目前的搜索功能同时只支持一个关键字搜索。
如果想同时看到两个以上的关键字搜索就很麻烦，不得不舍弃当前的搜索结果。

**Comment by tsalinger** [comment] 2018-03-12 14:00
Google Translate:
> Many times we want to search for multiple keywords and analyze the results, but the current search function only supports one keyword search at the same time.
If you want to see more than two keyword searches at the same time, it's a hassle and you have to discard the current search results.

**Comment by roblourens** [comment] 2018-03-13 15:28
/duplicate of https://github.com/Microsoft/vscode/issues/16488

**Closed by roblourens** 2018-03-13 15:28 UTC
Labels: feature-request
