### ISSUE TITLE
Synchronise UI state and settings across machines

### ISSUE THREAD

**Issue by gerardam** [Microsoft/vscode#30720] opened 2017-07-14 15:26 UTC
- VSCode Version: 1.14.1
- OS Version: Windows 10

It would be nice to be able to start session in visual studio code to be able to save the customized characteristics and once it is installed again in another computer that adds the characteristics once the session begins.

**Comment by mjbvz** [comment] 2019-05-01 23:33
Duplicate of #2743

**Closed by mjbvz** 2019-05-01 23:33 UTC
Labels: config, feature-request, workbench-state
