### ISSUE TITLE
`--unity-launch` option removal causes VSCode to ignore input file

### ISSUE THREAD

**Issue by Ved-s** [microsoft/vscode#214137] opened 2024-06-03 12:40 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1 dc96b837cf6bb4af9cd736aa3af08cf8279f7685 x64
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. run VSCode with `code --unity-launch some-file`
2. it prints `Warning: 'unity-launch' is not in the list of known options, but still passed to Electron/Chromium.`
3. file doesn't open in VSCode as it's being treated as an argument to the unknown `--unity-launch` option

.desktop file for VSCode uses this option. It either wasn't updated when this option was removed or it may still install VSCode with this option in its .desktop file.

Also sorry if it's a duplicate, couldn't make github search by option's name

**Comment by rzhao271** [comment] 2024-06-06 23:25
I looked through the codebase and didn't find any mentions of `--unity-launch`.
I'm wondering whether the `.desktop` file just didn't update along with the rest of the program.
Could you update to 1.90.0 and check the file again?

**Comment by Ved-s** [comment] 2024-06-07 06:03
I tested with code-insiders when i created the issue and i checked now, its desktop file is normal, without unity-launch. I will update code to 1.90.0 and look if its desktop file changes.

**Comment by Ved-s** [comment] 2024-06-07 06:08
No, apt didn't update the desktop file while unpacking, but it probably will on clean reinstall

**Comment by rzhao271** [comment] 2024-09-13 21:17
Duplicate of #212125

**Closed by rzhao271** 2024-09-13 21:17 UTC
Labels: bug, debt, linux, deb
