### ISSUE TITLE
Panel view container location jumping

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96383] opened 2020-04-28 12:00 UTC
Testing https://github.com/microsoft/vscode/issues/96318

![locationJump](https://user-images.githubusercontent.com/38270282/80484762-8c2b5980-8958-11ea-9686-3715c1e3913f.gif)

**Comment by sbatten** [comment] 2020-04-28 17:01
ahh, this again. i had one report of this from @mjbvz but I closed it as I could never reproduce. it repros 100% for you?

**Comment by alexr00** [comment] 2020-04-29 09:36
Yes.

**Comment by sbatten** [comment] 2020-04-29 14:09
I've performed the actions in the gif 20 different times in different ways, but I am unable to repro. With the repro at 100%, can you check which of those panels is in their default container? Right click each panel and see if it has `Reset View Location`. If it does, that means its in a generated container. Additionally can I know if the output container is in a generated container at the start and at the end?

**Comment by alexr00** [comment] 2020-04-29 14:30
In the panel, only Output has a `Reset View Location`.

**Comment by sbatten** [comment] 2020-04-30 22:18
resolving this as a duplicate of the other since i've had the same luck with both reproing... :(

**Closed by sbatten** 2020-04-30 22:18 UTC
Labels: bug, needs more info
