### ISSUE TITLE
Extension editor: scroll position is not restored.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#27498] opened 2017-05-30 08:47 UTC
Testing: #27350 

- VSCode Version: 1.13 insider
- OS Version: Linux Fedora

Steps to Reproduce:

1. open extension editor
1. scroll the content
1. switch to another editor in the same group
1. switch back to extension editor

Observe: scroll position is not restored

**Comment by dbaeumer** [comment] 2017-05-30 08:47
Not sure who owns this :-)

**Comment by sandy081** [comment] 2017-05-30 10:02
Extension editor uses Web view. Could be that, this was not adopted by the feature #22995 If it is scoped to all web views. @mjbvz FYI

**Comment by isidorn** [comment] 2017-05-30 10:16
I am also seeing this

**Comment by mjbvz** [comment] 2017-05-30 23:01
Yes, the scroll preserving change only targeted htmlPreview and the release notes page this month. I'll port it to the extensionviews as well in June

**Comment by RafaelKr** [comment] 2018-08-14 07:49
@mjbvz hey you said you implemented this for the Release Notes tab for one month. Would it be possible to implement this for every release notes page?
I want to test the new features while reading about them and it's really annoying that the release notes tab always reloads when switching back to it - without a restored scroll position.

**Comment by moshfeu** [comment] 2019-08-08 11:47
Nothing? :(

**Comment by crystalfp** [comment] 2019-11-08 05:33
The problem is still present in Release Notes reader with 1.40.0 on Windows.

**Comment by davicoradini** [comment] 2019-11-26 13:54
Still...

**Comment by PaulPCIO** [comment] 2019-12-02 07:29
still present, in Extentions & Release Notes

https://github.com/microsoft/vscode/issues/24122
https://github.com/microsoft/vscode/issues/58007

**Comment by moshfeu** [comment] 2019-12-02 08:57
@mjbvz  [`retainContextWhenHidden`](https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden) can solve that.

**Comment by gjsjohnmurray** [comment] 2019-12-02 11:13
@moshfeu I wish it was that easy. I just tried adding ```retainContextWhenHidden: true``` at https://github.com/microsoft/vscode/blob/c26146d7c5a7b9b4b01e7b5d758fae087dea834a/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L580-L582

But it didn't fix the problem. I also tried ```tryRestoreScrollPosition: true``` as the option name looked to be relevant. Didn't help either.

To prove I was changing the right place I temporarily switched ```enableFindWidget``` to ```false``` and verified that Ctrl+F no longer brought up the Find widget.

My guess is the ExtensionEditor gets completely reinitialized when I switch back to the tab after switching away.

**Comment by okikio** [comment] 2020-10-10 19:00
This is not a scroll position issue, VS code actively reloads WebViews when not in focus.

**Comment by PaulPCIO** [comment] 2020-10-10 19:17
> still present, in Extentions & Release Notes
> 
> #24122
> #58007

![image](https://user-images.githubusercontent.com/39598117/95663235-ce7ad880-0b3d-11eb-9a27-8e6daea14697.png)

Why would this comment be marked as spam? 🤔  on the contrary it avoids spammy issues by linking similar issues?  anyhow....

@okikio this is a scroll position issue though? it may be caused by WebView reloading, but the issue still remains that once you refocus, the scroll position should be maintained, so technically it falls within a "scroll position issue"...

**Comment by okikio** [comment] 2020-10-10 20:03
> > ![image](https://user-images.githubusercontent.com/39598117/95663235-ce7ad880-0b3d-11eb-9a27-8e6daea14697.png)
> > still present, in extensions & release notes
> > #24122
> > #58007
> 
> Why would this comment be marked as spam? 🤔 on the contrary it avoids spammy issues by linking similar issues? anyhow....
> 
> > This is not a scroll position issue, VS code actively reloads WebViews when not in focus.
> 
> @okikio this is a scroll position issue though? it may be caused by WebView reloading, but the issue still remains that once you refocus, the scroll position should be maintained, so technically it falls within a "scroll position issue"...

Fair enough.

**Comment by gjsjohnmurray** [comment] 2020-12-11 14:08
@mjbvz now that 1.52 has shipped please can this PR make progress?

**Closed** 2020-12-18 21:56 UTC
Labels: extensions, feature-request, help wanted, webview
