### ISSUE TITLE
count-badge's content is not centered

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#100685] opened 2020-06-21 09:24 UTC
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Steps to Reproduce:

1. Go to settings
2. Search something (`editor.find.loop` for example)

![Screen Shot 2020-06-21 at 12 21 41](https://user-images.githubusercontent.com/3723951/85221147-2d171d80-b3ba-11ea-984b-56e782adc008.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2020-06-23 13:54
Maybe same as https://github.com/microsoft/vscode/issues/97960

**Comment by misolori** [comment] 2020-06-23 15:03
Yea, closing as a duplicate of #97960

**Closed by misolori** 2020-06-23 15:03 UTC

**Comment by moshfeu** [comment] 2020-06-23 15:21
Thanks
