### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by jcitarello** [Microsoft/vscode#35233] opened 2017-09-27 14:50 UTC
- VSCode Version: 1.6
- OS Version: Ubuntu 16,04

Steps to Reproduce:

1.  Open VS Code
2. Attempt to load and install any extenstions.

Reproduces without extensions: Yes

I am unable to see any extensions when opening the Extensions dialog and seeing "Error XHR failed" message when typing in any search.  Please advise, thanks.

**Comment by banyudu** [comment] 2017-09-29 14:38
Same issue
VSCode version 1.16.1
OS Version: Ubuntu 17.04

**Comment by banyudu** [comment] 2017-09-29 14:53
Possible duplicate of https://github.com/Microsoft/vscode/issues/34385

Besides, in my case, the system proxy causes this error.

**Comment by sandy081** [comment] 2017-10-02 09:34
Duplicate of #34385

**Closed by sandy081** 2017-10-02 09:34 UTC
Labels: extensions
