### ISSUE TITLE
Debug Typescript Not Stopping on Break Points - Electron

### ISSUE THREAD

**Issue by JamesBewley** [Microsoft/vscode#29749] opened 2017-06-28 12:28 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro
- Node7.4.0

I am attempting to debug an electron app written in Typescript and compiled to JS/sourcemaps with gulp and debugged with VSCode.  The electron instance is launched, the debugger is attached and it appears to be able to resolve the typescript source using the source maps but the debugger never stops.  It doesn't even stop if I put a `debugger;` statement in the Typesrcipt.

I can supply more information if required, here are a few bits that seem relevant but don't mean much to me.  Any help much appreciated.

Here are the relevant bits of the launch file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/source/server/main.ts",
            "outFiles": [
                "${workspaceRoot}/dist/server/src/main.js",
                "${workspaceRoot}/dist/server/**/*.js"
            ],
            "cwd": "${workspaceRoot}",
            "trace": "all",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
                ".",
                "--enable-logging"
            ],
            "sourceMaps": true
        }
    ]
}
```

Here is the output from the debug console:
```
23708: _findSourceMapUrl: source map url found at end of generated file 'c:/code/GIT/project/test_harness_gui/dist/server/src/main.js'
23708: _findSourceMapUrl: source map url found at end of generated file 'c:/code/GIT/project/test_harness_gui/dist/server/src/harnessLauncher.js'
23708: _findSourceMapUrl: source map url found at end of generated file 'c:/code/GIT/project/test_harness_gui/dist/server/src/harnessInstance.js'
23708: _findSourceMapUrl: source map url found at end of generated file 'c:/code/GIT/project/test_harness_gui/dist/server/src/harnessServer.js'
23708: _registerSourceMap: c:/code/git/project/test_harness_gui/source/server/harnesslauncher.ts -> c:/code/git/project/test_harness_gui/dist/server/src/harnesslauncher.js
23708: _registerSourceMap: c:/code/git/project/test_harness_gui/source/server/main.ts -> c:/code/git/project/test_harness_gui/dist/server/src/main.js
23708: _registerSourceMap: c:/code/git/project/test_harness_gui/source/server/harnessinstance.ts -> c:/code/git/project/test_harness_gui/dist/server/src/harnessinstance.js
23708: _registerSourceMap: c:/code/git/project/test_harness_gui/source/server/harnessserver.ts -> c:/code/git/project/test_harness_gui/dist/server/src/harnessserver.js
23708: launchRequest: program 'c:\code\GIT\project\test_harness_gui\source\server\main.ts' seems to be the source; launch the generated file 'c:\code\GIT\project\test_harness_gui\dist\server\src\main.js' instead
c:\code\GIT\project\test_harness_gui/node_modules/.bin/electron.cmd --debug-brk=42194 . --enable-logging dist\server\src\main.js 
23708: _attach: address: 127.0.0.1 port: 42194

23708: _attach: connected
23708: __initialize: got process id 2696 from node
23708: _initialize: target node version: v7.4.0
23708: _injectDebuggerExtensions: code injection successful
23708: _startInitialize: stopped: true
23708: _startInitialize: no entry event after 10 retries; giving up
23708: NodeV8Protocol hook: ref cache size: 10
23708: _startInitialize2: fire initialized event
23708: _startInitialize2: remember to do a 'Continue' later
23708: setBreakPointsRequest: {"path":"c:\\code\\GIT\\project\\test_harness_gui\\source\\server\\main.ts","name":"main.ts"} [{"line":15}]
23708: setBreakPointsRequest: {"path":"c:\\code\\GIT\\project\\test_harness_gui\\source\\server\\harnessLauncher.ts","name":"harnessLauncher.ts"} [{"line":35}]
23708: _mapSourceAndUpdateBreakpoints: src: 'c:\code\GIT\project\test_harness_gui\source\server\main.ts' 14:0 -> gen: 'c:\code\GIT\project\test_harness_gui\dist\server\src\main.js' 8:4
23708: _mapSourceAndUpdateBreakpoints: src: 'c:\code\GIT\project\test_harness_gui\source\server\harnessLauncher.ts' 34:0 -> gen: 'c:\code\GIT\project\test_harness_gui\dist\server\src\harnessLauncher.js' 17:8
23708: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\code\\\\GIT\\\\project\\\\test_harness_gui\\\\dist\\\\server\\\\src\\\\main\\.js$","line":8,"column":4}
23708: _updateBreakpoints: result [{"verified":true,"line":15,"column":1}]
23708: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\code\\\\GIT\\\\project\\\\test_harness_gui\\\\dist\\\\server\\\\src\\\\harnessLauncher\\.js$","line":17,"column":8}
23708: _updateBreakpoints: result [{"verified":true,"line":35,"column":1}]
23708: setFunctionBreakPointsRequest: result []
23708: setExceptionBreakPointsRequest: ["uncaught"]
23708: configurationDoneRequest: do a 'Continue'
```

**Comment by JamesBewley** [comment] 2017-06-28 14:52
Ok, I managed to get it to hit a `debugger;` statement in the main.ts file and can see it complaining about case in the file paths.

Here is some more output that might be relevant:

```
Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.
...
28624: _createStackFrameFromSourceMap: gen: 'c:\code\GIT\project\test_harness_gui\source\server\harnessLauncher.js' 32:8 -> couldn't be mapped to source -> use generated file
28624: __readFile: c:\code\GIT\project\test_harness_gui\source\server\harnessLauncher.js
28624: scopesRequest: scope 0
28624: NodeV8Protocol hook: ref cache size: 11
28624: _resolveToCache: vscode_lookup 1 handles
28624: NodeV8Protocol hook: ref cache size: 38
28624: _resolveToCache: vscode_lookup 3 handles
28624: _resolveToCache: vscode_lookup 1 handles
28624: NodeV8Protocol hook: ref cache size: 46
28624: _resolveToCache: vscode_lookup 1 handles
28624: NodeV8Protocol hook: ref cache size: 51
28624: stackTraceRequest: backtrace 1 20
28624: NodeV8Protocol hook: ref cache size: 73
28624: _createStackFrameFromSourceMap: gen: 'c:\code\GIT\project\test_harness_gui\source\server\main.ts' 26:20 -> couldn't be mapped to source -> use generated file
28624: _createStackFrameFromSourceMap: gen: 'c:\code\GIT\project\test_harness_gui\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js' 246:36 -> couldn't be mapped to source -> use generated file
```

**Comment by SlickNutter** [comment] 2017-07-05 12:34
@JamesBewley 
https://github.com/colinskow/angular-electron-dream-starter/issues/1#issuecomment-312957104

That thread helped me, although it would be important to know whether you are trying to debug the main or the renderer.

**Comment by JamesBewley** [comment] 2017-07-05 12:36
Trying (and failing) to debug the main.  I'll take a look through that thread.  Thanks

**Comment by JamesBewley** [comment] 2017-07-05 12:46
@SlickNutter I don't see any resolution in that thread apart from using a `debugger;` statement in the main.ts file (which I mention above).  Although once the debugger statement is hit you can only step through the javascript code not the typescript because of the source mapping issue.

Maybe the two issue are related and the warning about case sensitivity might be the root cause.

Need one of the developers familiar with this to review it really.

**Comment by greg9504** [comment] 2017-07-06 12:48
@JamesBewley 
How are you starting VS Code?  The case issue with file paths is covered in the docs:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_javascript-source-map-tips

> Have you opened the folder in VS Code with the incorrect case? It's possible to open folder foo/ from the command line like code FOO in which case source maps may not be resolved correctly.

Try right clicking on the project folder in Windows explorer and opening the project in VS Code.

**Comment by JamesBewley** [comment] 2017-07-06 12:51
As far as I'm aware the project is correctly setup, the above traces show VScode finding the sourcemaps and the typescript file but there is a problem when it comes to setting breakpoints.

**Comment by weinand** [comment] 2017-07-06 13:02
If using a `debugger` statement works, then the next logical thing to try is setting a breakpoint in the generated JavaScript. For this disable source maps by setting the `sourceMaps` attribute to false.

**Comment by JamesBewley** [comment] 2017-07-10 13:22
@weinand putting a `debugger; `statement in the typescript or the generated javascript causes the VSCode debugger to stop and allow debugging.  

Any thoughts on why breakpoints are not being hit?

**Comment by weinand** [comment] 2017-07-10 13:50
Did you try setting breakpoints in the generated JavaScript and turning off source maps?

**Comment by JamesBewley** [comment] 2017-07-10 14:41
@weinand Yes the generated javascript can be debugged directly.

**Comment by weinand** [comment] 2017-07-10 14:50
Aha, then the problem is in the source maps. 

Make sure to have read this section: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_javascript-source-map-tips

The most important sentence from that doc is this:

> Are the `sourceRoot` and `sources` properties in your source map correct? Can they be combined to get the correct path to the .ts file?

Please verify this.

And if the combined path from above is still relative, combine it with the directory where the source map file lives.

**Comment by JamesBewley** [comment] 2017-07-10 14:54
@weinand The sourcemaps are found and the paths to the TS files are correct (see trace in initial post).

**Comment by JamesBewley** [comment] 2017-07-12 14:05
I've updated to version 1.14.0 and this is all working fine now.  Also made lots of changes to launch file and gulp so difficult to pin down what the cause was exactly.

Please close.

**Comment by weinand** [comment] 2017-07-12 15:10
@JamesBewley Thanks a lot for resolving this.

**Closed by weinand** 2017-07-12 15:10 UTC
Labels: debug
