### ISSUE TITLE
extension host issue

### ISSUE THREAD

**Issue by pradeept95** [microsoft/vscode#176900] opened 2023-03-12 16:40 UTC
Type: <b>Bug</b>

I am frequently getting popup asking to restart because of extension host issue.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.70GB free)|
|Process Argv|--crash-reporter-id 1f82fb5e-855c-4f86-b6e4-c610b6b8b0e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.7
codex-build|Cod|0.5.7
xstviz|dks|1.0.4
es7-react-js-snippets|dsz|4.4.3
expando-vscode|Fan|0.1.5
copilot|Git|1.77.9225
emoji|Per|1.0.1
LiveServer|rit|5.7.9
stately-vscode|sta|1.13.0
rdoc-readme|vau|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
funwalk2:30682974
pythonms35cf:30680985

```

</details>

**Comment by phoenixeliot** [comment] 2023-03-12 17:02
Same. Likely related, my git addition/removal/modifications aren't being noticed and updated in the gutter or source control section, very frequently, requiring an app restart.

**Comment by gjsjohnmurray** [comment] 2023-03-12 19:00
Diff markers issue is #176749

For extension host issue please use the Start Extension Bisect command to investigate.

**Comment by isidorn** [comment] 2023-03-15 11:16
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:16 UTC
Labels: freeze-slow-crash-leak, extension-host
