### ISSUE TITLE
Cannot find module after switching branch

### ISSUE THREAD

**Issue by Conner05** [microsoft/vscode#78508] opened 2019-08-05 14:31 UTC
Issue Type: <b>Bug</b>

1. Be on branch B
2. rename a folder with components in it
3. Commit
4. Checkout branch A
5. rebase from master `git pull --rebase origin master`
6. push branch up `git push --force`
7. Checkout master `git checkout master`
8. get latest `git pull`
9. Checkout new branch `git checkout -b C`

Now I see red squigglies under some of the references (`import`s) to the files I had in the folder I renamed on branch B. Only some, though. One file is actually referenced ok. The path is correct, too, for all of them. I just see red squigglies that say "Cannot find module". Closing and re-opening VS Code resolves this.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.0
gitlens|eam|9.9.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
gc-excelviewer|Gra|2.1.32
csharpextensions|jch|1.3.0
vscode-peacock|joh|3.0.1
csharpfixformat|Leo|0.0.83
rainbow-csv|mec|1.2.0
Angular-BeastCode|Mik|8.0.10
dotenv|mik|1.0.1
vscode-docker|ms-|0.7.0
csharp|ms-|1.21.0
debugger-for-chrome|msj|4.11.7
vscode-jest|Ort|3.0.2

</details>

**Comment by IllusionMH** [comment] 2019-08-05 15:35
/needsMoreInfo

Are you seeing this error for JS/TS or other language?

You can just use `>TypeScript: Restart TS server` if you are editing JS/TS in meantime. Its a bit faster than close/re-open.

**Comment by Conner05** [comment] 2019-08-05 16:03
> /needsMoreInfo
> 
> Are you seeing this error for JS/TS or other language?
> 
> You can just use `>TypeScript: Restart TS server` if you are editing JS/TS in meantime. Its a bit faster than close/re-open.

I am using TS. I had forgotten about the `Restart` cmd. Thanks!

**Comment by mjbvz** [comment] 2019-08-12 21:15
Duplicate of #7790

**Closed by mjbvz** 2019-08-12 21:15 UTC
