### ISSUE TITLE
Warning message loops popup while opening js file

### ISSUE THREAD

**Issue by Jacksing** [Microsoft/vscode#20376] opened 2017-02-10 06:18 UTC
The following two message loop popup while opening a js file.
1)  The path path/to/typescript/lib doesn't point to a valid tsserver install. Falling back to bundled TypeScri...
2)  The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|django-html|bibhasdn|1.2.0|
|django-snippets|bibhasdn|1.1.0|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.6|
|tslint|eg2|0.8.1|
|Theme-Monokai-Midnight|gerane|0.0.2|
|output-colorizer|IBM|0.0.9|
|MagicPython|magicstack|1.0.3|
|vscode-icons|robertohuertasm|7.0.1|
|python|tht13|0.2.3|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. open js project(in my case it is a react project) with vscode
2. click a js file in the explorer windows
3. the warning message loops popup on the top of edit window.

**Comment by mjbvz** [comment] 2017-02-10 19:05
Please check the path mentioned in the error message. We've seen many reports of an antivirus program deleting the javascript files under that path which causes TypeScript to stop working

**Comment by mjbvz** [comment] 2017-02-13 22:36
Closing as likely duplicate of #20552 

Please provide more information on this issue if you feel this is not the case

**Closed by mjbvz** 2017-02-13 22:36 UTC
Labels: duplicate, External, javascript, needs more info

**Comment by Jacksing** [comment] 2017-03-02 04:20
Thanks a lot for the comments.

I solved it by adding `typescript.tsdk` in my settings which pointed to my typescript/lib. And now every thing goes OK after I update vscode to a newer edition even if I remove the `typescript.tsdk` setting.

Maybe there was some thing wrong in my envioriment with vscode worked with the default `typescript.tsdk`  in its older editon.
