### ISSUE TITLE
problem occurs wile importing file swith ES6 import command

### ISSUE THREAD

**Issue by qiufengiii** [Microsoft/vscode#71974] opened 2019-04-09 03:22 UTC
Issue Type: <b>Bug</b>

When importing files with ES6 import command, the editor stops functioning if tslint prompts that there is a problem with the path

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (10.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.6.0
auto-rename-tag|for|0.0.15
code-beautifier|mic|2.2.1
vscode-language-pack-zh-hans|MS-|1.33.2
material-icon-theme|PKi|3.7.0
view-in-browser|qin|0.0.5

</details>

**Comment by qiufengiii** [comment] 2019-04-10 01:52
when i'm inputting this import { connect } from 'react-redux' or something like that, my vs code just stop functioning, and i just found that

**Comment by qiufengiii** [comment] 2019-04-10 02:07
Once I input 'import { connect } from 'react-redux', or something like this, the problem shows up, And this morning I just found that the outline view will be stuck after I input the code above, how can I fix it?

**Comment by qiufengiii** [comment] 2019-04-10 02:12
How can I disable the outline view?

**Comment by mjbvz** [comment] 2019-04-10 21:37
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by qiufengiii** [comment] 2019-04-11 01:11
yes

**Comment by mjbvz** [comment] 2019-04-17 18:13
I still don't understand what the steps to reproduce the issue are or what the problem is. Please describe:

1. List of steps to reproduce the issue in an empty workspace
1. The exact error that is showing up

**Comment by mjbvz** [comment] 2019-04-22 18:53
Closing as needs-more info

**Closed by mjbvz** 2019-04-22 18:53 UTC
Labels: needs more info
