### ISSUE TITLE
[folding][general] New option for Code Folding Indicator [+]/[-]

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#19020] opened 2017-01-23 10:11 UTC
Is it already possible to make the Folding Indicators stay visual and not only show them on hovering over the Space next to the Number or not?

If it is please tell me how/where.

If not why not i think this was requested multiple times.
I think this could be done with setting:

"editor.folding" 

just make it a triple select [false, hover, always] instead of just [true, false]

**Comment by mousetraps** [comment] 2017-01-24 00:44
Hey @konqui, love the idea - thanks for the feedback! Unfortunately, we haven't gotten around to that feature yet. See here: https://github.com/Microsoft/vscode/issues/6563

As far as *why* we haven't done it yet... the honest answer is we're a small team with a huge backlog, and we're working through it as fast as we can, but we haven't quite gotten to this one. We ❤️ PRs, though. Just sayin'! :wink:

closing as a duplicate of https://github.com/Microsoft/vscode/issues/6563 - feel free to chime in there with any additional comments you have

**Closed by mousetraps** 2017-01-24 00:44 UTC
