### ISSUE TITLE
quoting selection freezes app

### ISSUE THREAD

**Issue by davidjdixon** [Microsoft/vscode#56408] opened 2018-08-14 21:54 UTC
Issue Type: <b>Bug</b>

during some routine pasting of code into the editor (pasting a yaml structure into a python file), I was attempting to reformat the data to a python object... during which I do the normal "select key, press quote key" to wrap the keys in quotes.

After updating vscode to the latest release, and performing this change, the editor suddenly froze/crashed. I forced quit, tried the same thing... freeze/crash.

I tried this a few more times doing slight variations in approach to see if it was something else (and even disabled a recently installed extension to see if it could have caused it)... no difference. the editor freezes out, unable to use editor view, yet menus open/close file (although actions from the menus were not being performed while the app was frozen).

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.2
aws-cloudformation-yaml|Dan|0.2.2
output-colorizer|IBM|0.1.2
vscode-paste-and-indent|Rub|0.0.8
vsc-material-theme-italicize|Ser|0.0.14
sort-lines|Tyr|1.7.0
scope-bar|amo|0.1.0
better-toml|bun|0.3.2
solargraph|cas|0.17.6
vaulty|cod|0.2.0
gitignore|cod|0.5.0
cform|dav|0.0.10
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
ansible-vault|dho|0.1.3
chmod|dle|1.0.0
githistory|don|0.4.2
vscode-great-icons|emm|2.1.41
vsc-material-theme|Equ|2.3.0
json-tools|eri|1.0.2
php-debug|fel|1.12.3
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
phpcs|ika|1.0.5
vscode-flake8|jay|0.0.4
snippetica-json|jos|0.6.0
vscode-gutter-preview|kis|0.13.1
vscode-github|Kni|0.30.0
restructuredtext|lex|66.0.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
python|ms-|2018.7.1
vscode-open-iterm2|mus|0.0.4
makefiles-support-for-vscode|nae|0.0.3
live-server-preview|neg|0.1.2
autodocstring|njp|0.2.3
fix-json|oli|0.1.2
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.2
cf-templates|pra|0.1.1
qub-xml-vscode|qub|1.2.8
logstash|Ran|0.0.3
ruby|reb|0.20.0
vscode-sort-json|ric|1.13.0
edit-with-shell|ryu|1.0.0
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.0.0
gitconfig|sid|1.0.1
ghosttext|tok|1.1.0
json2yaml|tux|0.2.0
vscode-ansible|vsc|0.3.1
HCL|who|0.0.5
jinja|who|0.0.8
change-case|wma|1.0.0
markdown-all-in-one|yzh|1.6.0

(3 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-08-15 14:09
@davidjdixon can you please share with us a python file or a similar one that reproduces the freeze ?

**Comment by aeschli** [comment] 2018-08-15 16:01
duplicate of #56377

**Closed by aeschli** 2018-08-15 16:01 UTC
Labels: candidate, freeze-slow-crash, new release
