### ISSUE TITLE
ResourcesManagement miss in  left side bar  

### ISSUE THREAD

**Issue by Liu-Liang** [microsoft/vscode#142801] opened 2022-02-11 03:44 UTC
Issue Type: <b>Bug</b>

change tab to search panel

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 11, 8|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id a3780115-2c33-4d95-a8e8-e4dff856afbe|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Liu-Liang** [comment] 2022-02-11 07:00
![Recording 2022-02-11 at 14 58 25](https://user-images.githubusercontent.com/23443019/153549430-c64c1ab9-2a21-413e-a1fb-4edc7c2ad25f.gif)

**Comment by Liu-Liang** [comment] 2022-02-11 07:01
@gjsjohnmurray

**Comment by sbatten** [comment] 2022-02-11 17:53
@Liu-Liang please do the following:
1. right click on any icon in the activity bar (for example the search icon).
2. Click on "Explorer" / "Resource Management" (if that is the correct translation for you)

**Comment by Liu-Liang** [comment] 2022-02-14 03:30
OK.It's useful.(Whether this default change is good?)

**Comment by sbatten** [comment] 2022-02-14 16:49
I am going to close this as I believe the issue is resolved.

**Closed by sbatten** 2022-02-14 16:49 UTC
Labels: needs more info, new release
