### ISSUE TITLE
Local commands for editors need to be visible with Tabs enabled

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#8779] opened 2016-07-06 01:04 UTC
We need to better show local commands for commonly used things like "View next change" "View previous change" and for "Preview markdown."

These used to be quite easy to access with tabs disabled.  Although we can't include local commands with global commands, as it could be confusing, we need to find a spot to put these that will be easy to use in one click and highly discoverable.  Right-clicking the active tab is not very discoverable.

**Comment by bpasero** [comment] 2016-07-06 09:44
Duplicate of https://github.com/Microsoft/vscode/issues/8779 ?

**Comment by bgashler1** [comment] 2016-07-06 16:41
@bpasero I think you posted the same issue number by accident.  Feel free to reference the existing issue and close this one :)

**Comment by bpasero** [comment] 2016-07-06 16:44
@bgashler1 oh sorry, I meant: https://github.com/Microsoft/vscode/issues/7666

**Closed** 2016-07-06 17:26 UTC
Labels: tabs, ux
