### ISSUE TITLE
Undo stack lost at random times.

### ISSUE THREAD

**Issue by tacho87** [Microsoft/vscode#3443] opened 2016-02-25 06:05 UTC
After 0.10.9 vscode does not preserve the undo/redo stack. Sometimes it preserves for 5 to 10 items. It was not behaving like this before upgrading.

**Comment by joaomoreno** [comment] 2016-02-25 08:27
@tacho87 Are you using OS X? Seems to be a duplicate of #3071. Related to #2829.

**Comment by alexandrudima** [comment] 2016-02-25 08:44
@tacho87 Can you please share some reproducible steps?

**Comment by tacho87** [comment] 2016-03-03 01:43
Yes I am using OSX, vscode Version 0.10.9 (0.10.9).
I tried to reproduce it. It seems to happen when I change from vscode to the browser and go back on JSX files mostly. Unfortunately , I do not have any steps or scenarios to reproduce it. 

It just feels like it is refreshing the redo/undo stack when something happens internally when using JSX files.

**Comment by alexandrudima** [comment] 2016-03-03 08:16
@tacho87 Is it possible that the files are changed on disk outside of VSCode? When a file changes on disk, we reload the file and drop the undo stack.

**Comment by tacho87** [comment] 2016-03-03 19:37
I usually work on a share drive for backup purposes with git on it. Could that be the issue? I also experienced it today on a plain html/js file on my desktop. Seems to happen specially when I debug the js on chrome.

**Comment by alexandrudima** [comment] 2016-03-17 12:33
@tacho87 We drop the undo stack when the file is edited on disk outside of VSCode. If a file is merely touched (but has the same content), we don't drop the undo stack. Are you editing the files through the Chrome debugger?

**Comment by joaomoreno** [comment] 2016-06-10 13:50
@alexandrudima This could be a duplicate of #2908, if that question is answered positively.

**Comment by alexandrudima** [comment] 2016-07-07 12:33
Most likely it is #2908

**Closed by alexandrudima** 2016-07-07 12:33 UTC
Labels: needs more info

**Comment by warmhug** [comment] 2016-07-29 12:27
On Mac,  vs code's version of 1.3.1 also reproduce it

**Comment by bpasero** [comment] 2016-08-26 10:49
This is https://github.com/Microsoft/vscode/issues/10932

**Comment by stefanpatatu** [comment] 2016-09-13 11:15
I can confirm the bug still exists as of v1.4.0. The bug mostly manifests after I save a file (work on file, CTRL+S, webpack rebuilds, check browser, see everything is broken, realize I have a typo or something, ALT+TAB, then CTRL+Z no longer works). It also manifests randomly sometimes, but especially after CTRL+S-ing.

**Comment by bpasero** [comment] 2016-09-13 12:05
@stefanpatatu what about Code 1.5 where we landed a fix?
