### ISSUE TITLE
vs code hangs for while when pressing the tab key for the first time

### ISSUE THREAD

**Issue by M-Zuber** [Microsoft/vscode#6816] opened 2016-05-24 16:07 UTC
- VSCode Version: 1.1.1
- OS Version: Win 10 home 

Steps to Reproduce:
1. Open vs code
2. Press the tab key
3. Wait a second or two
4. Get control back
5. Go crazy as it won't happen again until a new instance is opened or an indeterminate amount of time has passed

**Comment by scottste** [comment] 2016-05-24 16:28
I've noticed this as well even after doing `code-insiders --disable-extensions`.

- VSCode Version 1.1.1-insider
- OS Version: OS X 10.11.5

**Comment by aeschli** [comment] 2016-05-25 07:06
@M-Zuber Which view has the focus when you press tab? If it is in an editor, what type of file is it (JavaScript, HTML...)?

**Comment by M-Zuber** [comment] 2016-05-25 07:08
On a clean open of Code, blank file with focus on the file. 
But it happens with almost any extension - js, ts, html, cs

**Comment by M-Zuber** [comment] 2016-05-26 05:04
Just to reiterate, it happens to me on any type of file - usually only for the first time I press tab after opening vscode (but sometimes also in the middle of working)

**Comment by egamma** [comment] 2016-05-26 13:47
When it is the tab key and happens on first time, then this is the loading of the emmet node module.

>or an indeterminate amount of time has passed
however this doesn't explain this, since the emmet module is loaded only once into the renderer process.

@alexandrudima any other ideas what could go on?

**Comment by alexandrudima** [comment] 2016-05-26 13:53
> usually only for the first time I press tab after opening vscode

Yes this is caused by emmet loading the first time it is invoked. 

@M-Zuber once the May release comes out you can use the following rule in your `keybindings.json` to remove that `Tab` loads and executes emmet:
```
{ "key": "tab", "command": "-editor.emmet.action.expandAbbreviation" }
```

Here I am loading emmet (typing tab for the first time in a html file) on my quite powerful desktop at home: 488ms to load.


![image](https://cloud.githubusercontent.com/assets/5047891/15576786/da6d8cf8-2359-11e6-9322-b6828d8c0e6d.png)

I think the way forward here is to move emmet to an extension, thus the 500ms loading hit will be taken by the extension host.

**Comment by M-Zuber** [comment] 2016-05-29 09:28
Thank you for the help.
As I use emmet snippet expansion quite heavily (More than once I've built a 30+ char snippet :)), I'll deal with the one time hit.
> or an indeterminate amount of time has passed

I played around a bit, and it would seem that it only happens either on first use in a new instance of `code`, or after leaving an open instance run idle for a while (I leave my machine on overnight most nights). @egamma are the modules cached in any way?

**Comment by alexandrudima** [comment] 2017-03-02 10:41
emmet loading...

**Comment by ramya-rao-a** [comment] 2017-04-06 17:55
#21943 looks into having emmet features come from an extension rather than the tightly coupled in built way it is integrated today.

Closing this issue as the work done in #21943 will have a better user experience.

If #21943 doesn't pan out, then we will get back to see if there is something we can do to improve the first time experience.

**Closed by ramya-rao-a** 2017-04-06 17:55 UTC
Labels: emmet
