### ISSUE TITLE
[css] @supports at-rule unknown

### ISSUE THREAD

**Issue by Hidden50** [Microsoft/vscode#34273] opened 2017-09-13 07:36 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601

---

Steps to Reproduce:

1. Place in a CSS file:
```
@supports (-moz-appearance: none) {
	select { -moz-appearance:    none }
}
```
2. Press Ctrl Shift M to view Problems
3. VS Code reports the following error:
> severity: 'Error'
> message: 'at-rule unknown'

---

``@supports`` is documented at https://developer.mozilla.org/en/docs/Web/CSS/@supports and is supported by most browsers.

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-09-13 14:04
duplicate of #1505 (Fixed for September)

**Closed by aeschli** 2017-09-13 14:04 UTC
Labels: css-less-sass, new release
