### ISSUE TITLE
When save auto delete the start brace of function

### ISSUE THREAD

**Issue by JaydenWooDotCom** [microsoft/vscode#146492] opened 2022-04-01 04:09 UTC
Issue Type: <b>Bug</b>

Today when I save my go file, VSCode auto delete the start brace of function, this is really an odd bug! Is it April Fools ' Day today?

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by JaydenWooDotCom** [comment] 2022-04-01 04:15
Sometime it auto delete a letter of my go code at random position.

**Comment by gjsjohnmurray** [comment] 2022-04-01 04:42
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by mjbvz** [comment] 2022-04-14 23:55
Closing this as the most likely cause is a misbehaving extension. If this happens with all extensions disabled, please share steps to reproduce the issue so we can investigate

**Closed by mjbvz** 2022-04-14 23:55 UTC
Labels: needs more info, triage-needed
