### ISSUE TITLE
Reactivating Terminals

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#233097] opened 2024-11-05 15:02 UTC
Type: <b>Bug</b>

At the left bottom of my VS code, there is a message like "Reactivating Terminals" which has been showing whenever I open vs code. i am able to excute code even when it appear. Please help to resolve this issue.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.03GB free)|
|Process Argv|--crash-reporter-id f9b50e15-68ee-468d-80f0-85cb7577419a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.60
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
better-cpp-syntax|jef|1.27.1
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
jupyter|ms-|2024.11.2024102401
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
LiveServer|rit|5.7.9
vscode-devto|sne|0.0.14
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by karthiknadig** [comment] 2024-11-08 17:01
Duplicate of https://github.com/Microsoft/vscode-python/issues/23922

Add this to your **user settings** and reload VS Code:
```
"python.experiments.optOutFrom": ["pythonTerminalEnvVarActivation"],
```

**Closed** 2024-11-08 17:01 UTC
