### ISSUE TITLE
ext install <extension name> doesn't install extension

### ISSUE THREAD

**Issue by stereokai** [Microsoft/vscode#26389] opened 2017-05-10 13:52 UTC
- VSCode Version: v1.12.1
- OS Version: Win 10 Pro

Steps to Reproduce:

1. Go to [VS Code extension marketplace](https://marketplace.visualstudio.com/vscode)
2. Click on any extension to view it's homepage
3. At the top of the page you will see this example, which appears on *every extension's page*:
![image](https://cloud.githubusercontent.com/assets/2685357/25901135/734e34fc-359e-11e7-8a0b-a4ee9171ef4c.png)
4. Go to VSCode
5. Follow the instructions:
6. Hit `ctrl+p`
7. Type: `ext install cpptools` (for example)
8. Hit Enter.
9. Only extension bar opens, but the extension does not install.
10. To reach install button using keyboard only, use `ctrl+m` (change tab moves focus) and hit Tab key 11 times. Then hit Enter. Again. Or:
11. Use the slowly mouse & despair.

I am using the direct command, why can't VSCode just install the extension? If the VSCode team agrees this is a broken feature, I wouldn't mind working on a PR :)

**Comment by egamma** [comment] 2017-05-10 15:47
@stereokai this is as designed. Is the complaint that you want to perform the same operation without the mouse?

You can also install extensions from the command line using --install-extension, which doesn't require any mouse interaction.

**Comment by stereokai** [comment] 2017-05-10 19:21
@egamma 
>  Is the complaint that you want to perform the same operation without the mouse?

Exactly. And thanks for taking me seriously. IMO, it's a weird choice forcing users to reach to the mouse in a keyboard-centric environment (I mean, in principle, why bother with all the work around the custom keymappings etc.? You could argue there are edge cases, but I don't think this is one)

> You can also install extensions from the command line using --install-extension, which doesn't require any mouse interaction.

I don't think this is a good solution, because this is a context switch. In the same sense that I don't change other settings via the command line. And in the same breath then, why bother with the command palette at all? Just have everyone hacking VS Code commands into their terminals.

By the way, it used to be possible to install with keyboard only (also not very long ago) before the install buttons were added to the extensions sidebar. So far, I still haven't understood this limiting design change.

**Comment by sandy081** [comment] 2017-05-12 07:56
@joaomoreno I kinda agree with @stereokai on copy-pasting `ext install <extension-identifer` is supposed to install the extension. Any reason why we changed this behaviour and show the viewlet?

**Comment by joaomoreno** [comment] 2017-05-12 08:01
Yes, `cpptools` doesn't identify any extension. Only `ms-vscode.cpptools` does, since it has the publisher in the name. We never adopted it, since it would break old versions (now currently really old versions).

If we want to bring that functionality back, we need the Marketplace to change those instructions to use the full ID.

At the same time, we are ready for having a single-click-install experience, which should completely replace this mechanism. We are also waiting on the Marketplace for that to happen.

cc @waderyan

**Comment by sandy081** [comment] 2017-05-12 13:36
True @joaomoreno I did not see that publisher name is not there in the identifier. 
So this single-click-install experience will take away this command `ext install <extension_id>` or we will still support it?

**Comment by joaomoreno** [comment] 2017-05-16 07:08
It will still be there for those that can't use the one-click.

**Comment by dajbd** [comment] 2017-06-19 09:12
`ext install vetur`
then  extension does not install.
maybe my network speed not well? 

when I search the extension, click install,
some time late, 
I can install vetur success.

bug?

**Comment by waderyan** [comment] 2017-06-19 15:42
@dajbd `ext install vetur` will search for the extension. You'll need to then click install. 

stay tuned for a better experience from the Marketplace website.

**Comment by dajbd** [comment] 2017-06-20 09:06
@waderyan I know, I did it like you said. click install button , but can not install it.
I tried it many times, also can not install.


another way,
I search the extension, click install button,
some time late,
I can install vetur success.

**Comment by wagnereliakim** [comment] 2017-07-11 02:39
@dajbd I have the same problem.
VsCode 1.13.1

**Comment by christianbueno1** [comment] 2017-07-25 19:25
OS: fedora26, x86_64
code: 1.14.2
well then, new users would find that confuse, because they would think that process is for install the extension in fact I thought that, it doesn't show us the suggested extension instead it search and show us more extensions. Anyway is good to know that here.

**Comment by sandy081** [comment] 2017-11-22 10:34
@joaomoreno Is this got fixed by #37033?

**Comment by joaomoreno** [comment] 2017-11-22 13:18
Yes

**Closed by joaomoreno** 2017-11-22 13:18 UTC
Labels: bug, extensions
