### ISSUE TITLE
Integration test (Windows, browser, chromium) failure git smoke test rename/delete conflict

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228486] opened 2024-09-13 13:47 UTC
![Image](https://github.com/user-attachments/assets/08269244-acc9-4795-88c1-e8cbf4366fc9)

https://dev.azure.com/vscode/VSCode/_build/results?buildId=131573&view=logs&j=e5ed5edc-5ec6-5bfb-d1cb-ed7e8a6cb5eb&t=b97d797e-cacf-547d-e55a-b0d6a53644f4&l=992

**Comment by lszomoru** [comment] 2024-09-13 22:36
Duplicate of https://github.com/microsoft/vscode/issues/228307

**Closed by lszomoru** 2024-09-13 22:36 UTC
