### ISSUE TITLE
Emmet 'Go to matching pair' doesn't work inside script tags

### ISSUE THREAD

**Issue by Dagge1** [Microsoft/vscode#36905] opened 2017-10-25 14:28 UTC
I updated to VS Code 1.17.2 and now Emmet 'Go to matching pair' command doesn't work at all (before this update it worked). Today is Oct 25 2017

**Comment by ramya-rao-a** [comment] 2017-10-27 17:45
Just checked in VS Code 1.17.2 in Windows
The command works just fine.
There has been no changes to this part of the code in over 4 months.

Did it work as expected in 1.16, 1.17.0, 1.17.1 ?
Are you trying it on an HTML file or any other file type?
Any errors pop up?
Can you try on a simple/small HTML file?

Share your sample code where you see the issue

**Comment by GammaGames** [comment] 2017-10-30 15:30
I'm having a similar issue, I'm not sure if it's a misunderstanding on my part of the command or unexpected behavior.

I attached a file that the issue is present for me. I can use the command just fine on regular html, but if I'm working on a template the command doesn't do anything. Replacing the "script" tags with "body" makes it work fine, so it might just be something with how Emmet sees tags.

[test.zip](https://github.com/Microsoft/vscode/files/1427704/test.zip)

**Comment by ramya-rao-a** [comment] 2017-10-30 17:54
@GammaGames thanks for the sample code. I get a repro. The issue seems to occur inside `script` tags only.

@Dagge1 @Bushrut can you confirm that you see the issue inside script tags as well? Or do you see it in any other tags?

The root cause seems to be that the Emmet parser I am using ignores the contents of `script` and `style` tags assuming the contents arent html.
I have logged an upstream issue for this: https://github.com/emmetio/html-matcher/issues/2

@GammaGames A suggestion: The sample code you share was just a few lines, could you please just paste the code in the comments instead of zipping it next time? Saves us (and am sure you as well) some time :)

**Comment by Dagge1** [comment] 2017-10-30 20:26
@ramya-rao-a I restarted PC and now it works inside .html file, I do not reason why it didn't work before. But it doesn't work inside <script> tags. I also tried @GammaGames sample code and it doesn't work inside <script> on my PC

Thanks

**Comment by ramya-rao-a** [comment] 2017-10-30 22:00
@Dagge1 Thanks for confirming that the issue is indeed inside the script tags

By php tag you mean `<?php`? Then the answer is no.

**Comment by electriccode** [comment] 2018-01-03 14:27
@GammaGames Wouldn't it be much better to use HTML template tags which are meant for the purpose? I am sorry, I am diverting this whole thread off but the only valid values for `type` attribute is `module` or a valid [Javascript MIME Type](https://html.spec.whatwg.org/#javascript-mime-type). [Source](https://html.spec.whatwg.org/#attr-script-type).

**Comment by GammaGames** [comment] 2018-01-04 16:53
@electriccode I use underscore for templating and tried to use the template tag with `type="text/javascript"` but that breaks the templating. Someone else had the idea a while ago, but [didn't have any luck](https://stackoverflow.com/questions/27175852/jquery-and-html5s-template-tag).
But that is actually interesting to know, I didn't know about the valid types! Thank you!

**Comment by bwasilewski** [comment] 2018-05-04 14:27
Has there been any activity around this lately? I experience the same issue inside of script tags.

**Comment by ramya-rao-a** [comment] 2018-05-06 19:26
@bwasilewski I don't see the upstream issue getting fixed anytime soon, but we can definitely attempt to fix this from our end by re-parsing the contents of the `script` tag.

PRs are very much welcome.

- Location where we should determine whether or not re-parsing is needed is [here](https://github.com/Microsoft/vscode/blob/release/1.23/extensions/emmet/src/matchTag.ts#L40) based on the current node
- Example of how we re-parse an already parsed node is [here](https://github.com/Microsoft/vscode/blob/release/1.23/extensions/emmet/src/toggleComment.ts#L76)
- Whitelist of types that a script tag should have to be considered as html content is [here](https://github.com/Microsoft/vscode/blob/release/1.23/extensions/emmet/src/abbreviationActions.ts#L12)

**Comment by ramya-rao-a** [comment] 2018-06-04 23:43
cc @JacksonKearl https://docs.emmet.io/actions/go-to-pair/ describes the feature being discussed in this issue.

The bug is described in https://github.com/Microsoft/vscode/issues/36905#issuecomment-340481398

And pointers for the bug fix are in https://github.com/Microsoft/vscode/issues/36905#issuecomment-386906618

**Closed** 2018-06-06 00:00 UTC
Labels: emmet, feature-request
