### ISSUE TITLE
Broken code commenting in 1.6

### ISSUE THREAD

**Issue by dasurid** [Microsoft/vscode#13457] opened 2016-10-11 01:30 UTC
- VSCode Version: 1.6 September update
- OS Version: OSX Mavericks

Previously, while editing JS code in an .html file, it was possible to use the CMD /  keyboard shortcut to comment a line or block of JS code.  Now, it is broken and it inserts HTML comments instead of JS comments.

This is a problem working with Polymer components, because JS and HTML are heavily intermixed in the same .html file.

**Comment by isidorn** [comment] 2016-10-11 08:37
Adding important since it seems like a regression and 3 users reported already

**Comment by mrmlnc** [comment] 2016-10-11 09:32
@isidorn, related to https://github.com/Microsoft/vscode/issues/12969 and "Updated HTML/Razor/Handlebar Support" section in https://code.visualstudio.com/updates/v1_6

![image](https://cloud.githubusercontent.com/assets/7034281/19265654/a31d43bc-8fae-11e6-9b6d-55fb71ade7af.png)

**Comment by isidorn** [comment] 2016-10-11 09:37
@mrmlnc thanks a lot! I guess I should read our release notes :) Removing important, adding to October

**Comment by aeschli** [comment] 2016-10-11 14:05
duplicate of #11081

**Closed by aeschli** 2016-10-11 14:05 UTC
