### ISSUE TITLE
When double clicking a file that has vsc as the default app to open with the file does not open

### ISSUE THREAD

**Issue by ofirgeller** [Microsoft/vscode#20014] opened 2017-02-06 08:37 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600 (I have windows 8.1)
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|scriptcsRunner|filipw|0.1.0|
|live-html-previewer|hdg|0.0.1|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|2.22.1|
|Ionide-Paket|Ionide|1.6.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|vshaxe|nadako|1.3.0|
|html5-boilerplate|sidthesloth|1.0.1|
|svg-snippets|sidthesloth|1.0.0|
|code-spell-checker|streetsidesoftware|0.14.8|

---

Steps to Reproduce:

1. Create a file called tsconfig.json
2. Define that the default program for opening it is visual studio code
3. double click the file
4. vsc will open, a new file called Untitled-1 will be created and opened, the json file you clicked will not appear.

**Comment by bpasero** [comment] 2017-02-06 09:07
@ofirgeller does it reproduce when you completely uninstall and then reinstall Code? 

I suspect an issue with the registry entry, hence assigning to @joaomoreno (I cannot reproduce with a fresh install).

**Comment by ofirgeller** [comment] 2017-02-06 13:00
Gave that a try after seeing your response, did not help.

**Comment by joaomoreno** [comment] 2017-02-06 17:00
When defining the default program, are there more instances of VS Code in there? How do you pick VS Code? Can you show a screenshot of that?

**Comment by ofirgeller** [comment] 2017-02-06 17:05
@joaomoreno That was it. if I set the default program again with the windows context menu the icon changes from a big vsc icon to a small vsc icon. and double clicking the file works as expected. 
I guess an older version of vsc was still effecting it?

**Comment by joaomoreno** [comment] 2017-02-06 17:14
That was it!

**Closed by joaomoreno** 2017-02-06 17:14 UTC
Labels: needs more info
