### ISSUE TITLE
Notebook and Interactive Window outputs aren't shown, commonly seen as "Failed to fetch dynamically imported module"

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#139609] opened 2021-12-21 22:00 UTC
## Environment data

Version: 1.64.0-insider
Commit: e8a26d3ebf5095d4324ad4bf794787540ed3b33e
Date: 2021-12-21T05:15:08.855Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.157-17178-ge2a77dd180f6 snap

-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001605991
-   Python Extension version (available under the Extensions sidebar): v2022.0.1589021501-dev
-   Python and/or Anaconda version: python 3.8
-   Jupyter server running: Remote

## Actual behaviour
I don't know how to reproduce this. I can't see the error sometimes (this also happens with matplotlib figures).

![image](https://user-images.githubusercontent.com/44866753/147000606-2c06f31e-1964-4615-af6d-d441cdcb8c39.png)

If I change the representation to build in, I can see the error.
![image](https://user-images.githubusercontent.com/44866753/147001066-ac0efb99-bed4-4c9a-89fc-f40fa22ef489.png)

And sometimes, I only see this
![image](https://user-images.githubusercontent.com/44866753/147002761-edc1d28f-211c-4451-b508-afada8f822d7.png)

In this situation the "More actions" (three dots) button is not clickable.

**Comment by DonJayamanne** [comment] 2021-12-22 00:40
Looks like the renderers aren't getting fetched in remote.

**Comment by fuxxnori** [comment] 2021-12-22 09:00
I had same issue.
How can I solve that??

**Comment by richardroberts-slamcore** [comment] 2021-12-24 04:53
Same issue, this happens every time I try to use `%matplotlib widget`.  Let me know if there's anything I can do to help track down the cause.  Here's my exact error:

`Error loading preloads:
Failed to fetch dynamically imported module: https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f63656461722d63616c6962726174696f6e222c2273657474696e6773223a7b22636f6e74657874223a22726963686172642d736c616d636f7265227d7d.vscode-resource.vscode-webview.net/home/richard/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.1.1001614873/out/datascience-ui/ipywidgetsRenderer/ipywidgetsRenderer.js`

**Comment by pedroangelini** [comment] 2021-12-26 00:28
got the same here... started happening around a week ago...

**Comment by danaiz** [comment] 2021-12-26 16:53
same here.
started a couple of days ago and it also appears instead of errors:
![image](https://user-images.githubusercontent.com/52538833/147414985-e15639aa-504e-4cf7-9fd5-dfa53eb4f8aa.png)

**Comment by pedroangelini** [comment] 2021-12-26 21:11
I've finally updated all my packages in that venv, and everything started working again. Not sure which package did the trick, but I had ipython, jupyter, pywin32 and setuptools updated, and I suspect any of those could have been the one that worked.

**Comment by DonJayamanne** [comment] 2021-12-26 22:56
@pedroangelini your are running into a different issues, issue with widgets, not with the rendering of errors in the output (which happens to be what others in this issue are running into)
Glad you got it working.

**Comment by avarayr** [comment] 2021-12-28 03:39
Please see [this comment](https://github.com/microsoft/vscode/issues/139200#issuecomment-999805684) for a temporary solution

**Comment by greazer** [comment] 2022-01-03 21:57
This appears to be the same problem that's causing me to be unable to use plotly at all in the latest insiders.

**Comment by gampx** [comment] 2022-01-04 13:10
@greazer I get this error most likely when I close and then open my laptop. May be it is connected with ssh session restart or something.

**Comment by greazer** [comment] 2022-01-05 01:46
Yep, I've verified a similar discovery. If I reload VS Code it seems (more) likely to happen. If I restart the kernel all seems to go swimmingly.  Here's a set of transitions with an IW session I just did:

---
Open VS Code and run an IW Script with graphs. Note there's neither an output plot nor any error indicated:
![image](https://user-images.githubusercontent.com/11685408/148147376-a9d0247e-711a-4ae5-8723-6b57555a35dd.png)

---
Then I scrolled up and down through the IW (at least that's all I think I did) and suddenly the same errors magically appeared for the same cells:
![image](https://user-images.githubusercontent.com/11685408/148147464-d16d0646-d4e9-4c85-b3f8-61f037e81474.png)

---
Finally, after restarting the kernel and running from the top, all seems to be going well: 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/11685408/148147315-bc44b681-a44e-4cb3-a8f3-6404b1666ad0.png">

**Comment by avarayr** [comment] 2022-01-05 03:41
I updated the Jupyter renderer extension to 1.0.4 which was supposedly the culprit, however, I cannot reproduce this issue anymore. There has to be some specific condition that's causing this.

**Comment by kuelumbus** [comment] 2022-01-05 14:46
I see this error regardless of having the Jupyter renderer extension installed at 1.0.4 or 1.0.3. Closing and reopening the notebook fixes this error for me temporarily. And then it "magically" reappears after a while.

**Comment by kuelumbus** [comment] 2022-01-05 17:32
My console output looks like this if I see the error. 

![image](https://user-images.githubusercontent.com/44866753/148261983-aade749a-c980-4fb5-9db4-9a8bbf18cd4f.png)

**Comment by greazer** [comment] 2022-01-05 18:38
Based on my experimentation and conversation with @rebornix , this appears to be a race condition regarding rendering registration because it's just very inconsistent for when it happens. We're investigating, thanks for all the input!

**Comment by mjbvz** [comment] 2022-01-06 01:35
@kuelumbus Are you on the latest VS Code insiders?

**Comment by kuelumbus** [comment] 2022-01-06 04:37
I think so 

Commit: 990ad4044032b05c0ebf0f67f800c5845baad4c7
Date: 2022-01-04T05:16:47.911Z

**Comment by SimiPixel** [comment] 2022-01-06 13:02
I am having exactly the same issue, it started when i used _SSH: Connect to remote_ to a server and at the same time i played around with the matplotlib-backends in order to get the notebook to display figures (when connected to remote).
Opening & closing and _str+shift+p -> Reload Window_ solves it temporarily (for roughly 5 minutes).

**Comment by kuelumbus** [comment] 2022-01-06 14:32
@mjbvz I just updated VS Code Insiders but I am still seeing these problems. 

Commit: 9afbea7caab9dd06592ddd98aa4161b43b126d3f
Date: 2022-01-06T05:15:46.948Z

**Comment by greazer** [comment] 2022-01-06 22:02
Thanks @kuelumbus, we are still investigating. This is turning into a tough issue to address as it's a race condition that's not readily showing up while using diagnostic or debugging tools. :( We will figure it out though. :)

**Comment by greazer** [comment] 2022-01-07 18:14
Still investigating.

**Comment by joaoponceleao** [comment] 2022-01-08 19:36
Just a heads up.
Had to downgrade to VS Code 1.6.1 with Jupyter extension v2021.9.1001312534 to resolve the issues.
Beyond not being able to see errors in the output (the choose representation render does not always show up), it was also preventing the enter/return key from being recognised in cells: shift-enter would work to run the cell, but enter would not create a new line (all other keys worked to edit - impressive how important new lines are...).

It also made large notebooks unbearable to run.

**Comment by avarayr** [comment] 2022-01-08 19:44
> Just a heads up. Had to downgrade to VS Code 1.6.1 with Jupyter extension v2021.9.1001312534 to resolve the issues. Beyond not being able to see errors in the output (the choose representation render does not always show up), it was also preventing the enter/return key from being recognised in cells: shift-enter would work to run the cell, but enter would not create a new line (all other keys worked to edit - impressive how important new lines are...).
> 
> It also made large notebooks unbearable to run.

The enter key not being recognized is most likely unrelated 
to this issue since it was working fine for me when this issue was occurring. 

Also, can you confirm this error is not occurring at all in VSCode 1.6.1?

**Comment by joaoponceleao** [comment] 2022-01-08 19:46
> Also, can you confirm this error is not present at all in VSCode 1.6.1?

I can confirm.

The reason I mention the enter issue, is because it would only show up when the other issues showed up (bad performance, no error outputs, etc).

**Comment by greazer** [comment] 2022-01-11 19:18
Thanks for everybody's patience! This was a tough bug to figure out. As of today's insiders it should be addressed. Personally, I was able to repro this quite regularly and with today's build I no longer can. If you can, please take a look to confirm from your end too.

**Comment by matrix303** [comment] 2022-01-11 19:33
> Just a heads up. Had to downgrade to VS Code 1.6.1 with Jupyter extension v2021.9.1001312534 to resolve the issues. Beyond not being able to see errors in the output (the choose representation render does not always show up), it was also preventing the enter/return key from being recognised in cells: shift-enter would work to run the cell, but enter would not create a new line (all other keys worked to edit - impressive how important new lines are...).
> 
> It also made large notebooks unbearable to run.

can confirm that the pressing enter issue also started to occur around the same time as rendering issue. (couple weeks ago). Mainly notice it in large notebooks. Happens on remote, WSL2 and local instances.

**Comment by matrix303** [comment] 2022-01-11 19:33
> Thanks for everybody's patience! This was a tough bug to figure out. As of today's insiders it should be addressed. Personally, I was able to repro this quite regularly and with today's build I no longer can. If you can, please take a look to confirm from your end too.

Should we use notebook render 1.0.4?

**Comment by avarayr** [comment] 2022-01-11 19:34
> Thanks for everybody's patience! This was a tough bug to figure out. As of today's insiders it should be addressed. Personally, I was able to repro this quite regularly and with today's build I no longer can. If you can, please take a look to confirm from your end too.

Thank you ! Do you mind sharing your steps to reproduce this? I will test on my end and report back.

**Comment by rchiodo** [comment] 2022-01-11 19:40
> Should we use notebook render 1.0.4?

Notebook renderer has no effect on the error, so yes please upgrade.

> Thank you ! Do you mind sharing your steps to reproduce this? I will test on my end and report back.

Repro steps would be:

1. Open python file
2. Write code like 
```
# %%
raise Exception("TEST")
```
3. Run the cell
4. Error trace should show in the interactive window.

**Comment by matrix303** [comment] 2022-01-11 19:40
Just restarted VScode to install insider update. This notebook was already opened and reopened in this state.

Python: v2022.0.1668608660-dev
Jupyter-renderer: v1.0.4 - prerelease
Jupyter: v2022.1.1001681627 - prerelease

vscode: 1.64.0 - insider

<img width="496" alt="Screenshot 2022-01-11 143506" src="https://user-images.githubusercontent.com/10987493/149010091-7f1b2b0d-84f0-461a-a575-0d2fe826fa41.png">

**Comment by rchiodo** [comment] 2022-01-11 19:42
Thanks @matrix303, I entered a new issue for that. Not related to the renderers not loading AFAIK.

**Comment by avarayr** [comment] 2022-01-11 20:38
Confirming fix works on my end! Thank you @greazer and @rchiodo 🥳

Version: 1.64.0-insider (Universal)
Commit: a06afb22ce06dbd4f01d3bb5bf946e08bff55180
Date: 2022-01-10T05:14:47.227Z

![image](https://user-images.githubusercontent.com/7735415/149017443-7bb67710-ae35-407c-86e7-9d4034931a58.png)

Version: 1.64.0-insider (Universal)
Commit: 00f1ca47ada2fda8ee1437e17b27af5b4002cecb
Date: 2022-01-11T09:14:08.981Z 

![image](https://user-images.githubusercontent.com/7735415/149017709-d4e4277b-7253-43ad-bd64-4e2e41ccaf6e.png)

**Comment by mjbvz** [comment] 2022-01-11 20:53
Fixed by #140351

**Closed by mjbvz** 2022-01-11 20:53 UTC
Labels: bug, important, notebook-output, nb-golden, iw-golden

**Comment by mjbvz** [comment] 2022-01-29 00:36
Marking as verified based on @greazer's early testing
