### ISSUE TITLE
[i18n] Some suggestions in command palette lack original English label in 1.10.1

### ISSUE THREAD

**Issue by lefb766** [Microsoft/vscode#21776] opened 2017-03-02 14:06 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 10 1607
- Lang: Japanese

![24](https://cloud.githubusercontent.com/assets/1574928/23509796/6536e0b0-ff9a-11e6-82b2-c27d0fcd816e.png)

Upon recent update (1.10.0 or 1.10.1), English label in some commands have gotten rid of.
This also disables suggestions in English for such commands.

**Comment by bpasero** [comment] 2017-03-02 15:35
@lefb766 could it be that these commands are coming from extensions?

It should work for all built in commands but there is a known issue that extension commands are not supported yet.

![image](https://cloud.githubusercontent.com/assets/900690/23514004/402cb8c8-ff66-11e6-88f5-bdcb81d5dae1.png)

**Comment by bpasero** [comment] 2017-03-02 15:37
@dbaeumer  @michelkaporin   is there any way I could get access to the command name in english locale? Something like nls.lookup(id, language: english)? That would save us a lot of trouble with these aliases and also make command registration much simpler.

**Comment by michelkaporin** [comment] 2017-03-02 16:13
@bpasero As far as I am aware, localised strings are loaded at the VSCode startup and immutable after it has been loaded, so there is no way to change them on the fly during instance of a tool running. 

Not sure whether there is a special flag to provide to start it in a specific locale. Neither aware of any command to access command name in particular locale programatically. 

If you know which part of the tool source (.ts file) contains the command name, you can drill down to the /i18n/ folder with the .json file storing the localisation under the same folder path as ts.file.
E.g. actionbar.ts file stored under:
~\vscode\src\vs\base\browser\ui\actionbar\actionbar.ts
translation is under:
~\vscode\i18n\deu\src\vs\base\browser\ui\actionbar

Hope this helps, @dbaeumer might know more.

**Comment by bpasero** [comment] 2017-03-02 16:14
@michelkaporin yes, that is what I thought, it is too late to get access. It would be very useful though for this case where we need to show the english translation so that people can do command search in english even though the locale is different.

**Comment by dbaeumer** [comment] 2017-03-02 16:24
The problem here is that the commands come from extensions defined in package.json files. To support this we would need to extend the command reading from package.json files to also read the English strings and then add both to the command stored in the command registry. Currently we only consider the translated string. 

The work needs to happen when parsing the package.json file when reading contributions.

**Comment by lefb766** [comment] 2017-03-02 16:26
@bpasero @dbaeumer They are built-in ones, definitely.

![26](https://cloud.githubusercontent.com/assets/1574928/23516139/b2584ae0-ffaf-11e6-8bb1-3d59bac439ed.png)

I can see commands with prefix "JavaScript: " and "TypeScript: " also lack English.

**Comment by bpasero** [comment] 2017-03-02 16:31
@lefb766 those are not built in ones but from extensions actually.

**Comment by bpasero** [comment] 2017-03-02 16:32
This is a duplicate of https://github.com/Microsoft/vscode/issues/17549

**Closed by bpasero** 2017-03-02 16:32 UTC
Labels: needs more info
