### ISSUE TITLE
Support mac/linux/windows subkeys in keybindings.json the same as extensions.contributes.keybindings...

### ISSUE THREAD

**Issue by joerohde** [Microsoft/vscode#45679] opened 2018-03-13 17:03 UTC
Issue Type: <b>Feature Request</b>

For users running on multiple machines/platforms, it is common to sync the vs settings.  Without support for the default 'key' and override-platform-specific 'windows/mac/linux' subkeys, there's no good way to share keybindings.json.

Keeping multiple copies is a pain to keep in sync; and with the commonality of 'cmd' on Mac in particular, it's hard to have a true common config that works across platforms.

I may be underestimating the work, but it looks like the most tedious/difficult part would be extending the localization of the schema in keybindingservice.ts. :)

There does not seem to be a write model that would need to preserve the original values. 
 (writeKeybindingItem looked like it might be it, but it's generating very specific formatting for the Default Keybindings window.  I guess it could be used by something more general and OS specific bindings would be lost?)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

**Comment by joerohde** [comment] 2018-03-16 18:49
The attached PR https://github.com/Microsoft/vscode/pull/45995 has an implementation; and tests.  I've attempted to make sure there are no downstream effects; but not being fluent in non-extension code, I won't claim it's ship ready.

**Comment by bpasero** [comment] 2018-08-07 05:24
Duplicate of https://github.com/Microsoft/vscode/issues/8962

**Closed by bpasero** 2018-08-07 05:24 UTC
Labels: feature-request, keybindings
