### ISSUE TITLE
Cannot import "Event" from quick fix

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116417] opened 2021-02-11 06:51 UTC
Steps to Reproduce:

1. when I type `Event` I see import suggestions
2. when I use quick fix I do not get them

![image](https://user-images.githubusercontent.com/900690/107609013-f4c09a00-6c3d-11eb-9a1c-92d77c109b77.png)

![image](https://user-images.githubusercontent.com/900690/107609020-fa1de480-6c3d-11eb-8815-a42a66105dcc.png)

**Comment by mjbvz** [comment] 2021-02-17 19:50
This seems like a duplicate of https://github.com/microsoft/TypeScript/issues/42752

Also, here's where we previously discussed `Event` in our codebase:  https://github.com/microsoft/TypeScript/issues/28739

**Closed by mjbvz** 2021-02-17 19:50 UTC
Labels: papercut :drop_of_blood:, typescript
