### ISSUE TITLE
Markdown - Preview synchronization after save

### ISSUE THREAD

**Issue by Camatius** [Microsoft/vscode#9625] opened 2016-07-22 15:33 UTC
- VSCode Version: 1.3.1
- OS Version: Win10 

Steps to Reproduce:
1. Start with new Markdown file (unsaved)
2. Open live preview
3. Create some content and save file

After saving the live preview of Markdown file is still connected to (now) nonexisting "unsaved" file. You have to close preview and open new one to see changes again...

Similar situation with **"Save as..."**

**Comment by mjbvz** [comment] 2017-01-25 07:23
Duplicate of #12033

**Closed by mjbvz** 2017-01-25 07:23 UTC
Labels: duplicate, markdown
