### ISSUE TITLE
Bug: Markdown > Preview: Open Markdown Links setting not respected

### ISSUE THREAD

**Issue by tarheels100** [microsoft/vscode#81320] opened 2019-09-23 15:03 UTC
- VSCode Version: 1.37.1
- OS Version: Windows 10, build 18362.356

### Description:
VS Code does not appear to respect the `Markdown > Preview: Open Markdown Links` setting.  The expected behavior for this setting is described [here](https://code.visualstudio.com/updates/v1_28#_markdown-preview-now-opens-links-to-local-files-in-the-preview).  In my case, both options (`inPreview` and `inEditor`) yield the same behavior, described below.  

A MWE is attached: [LinkTest.zip](https://github.com/microsoft/vscode/files/3642759/LinkTest.zip)

### Steps to Reproduce:

1. Open markdown file.
2. Open preview to the side.
3. Click link in preview of markdown file.
4. Result:
    - New editor tab with the linked file opens in the same group/panel as the preview tab.

### Additional tests:

- [x] Tested using the latest insiders build: same result
- [x] Tested without any extensions: same result

**Comment by mjbvz** [comment] 2019-09-24 01:34
That's an old VS Code version. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by tarheels100** [comment] 2019-09-24 01:53
@mjbvz 

> That's an old VS Code version. 

I just updated to the newest version and I get the same behavior.

> Can you check if the reproduce in the latest VS Code insiders build with all extensions disabled?

Yeah, I mentioned in the initial post that I reproduced the issue in the latest insiders build.  I did this with no extensions installed.

**Comment by mjbvz** [comment] 2019-09-26 23:57
Does not repo for me on insiders on windows:

![Sep-26-2019 16-56-31](https://user-images.githubusercontent.com/12821956/65732400-9e6dae00-e07e-11e9-8aa0-5324595c371f.gif)

Please provide more detailed repo steps

**Comment by tarheels100** [comment] 2019-09-30 19:50
@mjbvz 

Ok, I've done a ton more testing because it has been really difficult to come up with a consistent picture of what is happening.  Luckily, I think I've narrowed it down to the key problem.

It appears to arise in one specific circumstance: having spaces in the **absolute file path** of the file to which the markdown link refers.  And let me emphasize that this includes, but is not restricted to, markdown links that have spaces in the relative path specified in the markdown file.  That means that even if your current folder (and all subfolders) in VS Code are space-free, if it is stored on a path that contains spaces, preview links will not open properly.  (As an aside, I am aware that spaces in markdown links must be URL encoded [i.e., replaced with `%20`] to work at all and I have encoded them as such in all my tests.)

Here is a new test case to illustrate this:
[LinkTest.zip](https://github.com/microsoft/vscode/files/3672929/LinkTest.zip)

And here is an example of how this looks for me:
![vscode2](https://user-images.githubusercontent.com/29213686/65910886-388c6980-e391-11e9-89ac-9a79486f8617.gif)

**Comment by mjbvz** [comment] 2019-10-08 23:51
Thanks for the investigation. Can you please test this once VS Code 1.40 insiders is available later this week. I believe the issue may have been fixed by 36aa903d5a98ba5cf1d46b84c0a8fb3c2106bd8a as I can't reproduce the problem with VS Code 1.40 but can with VS Code 1.39

**Comment by tarheels100** [comment] 2019-10-11 15:15
@mjbvz 

I just tested with Insiders build 1.40, and I also no longer observe the issue with links containing spaces.  What is the typical timeframe for fixes in the Insiders build making their way into the mainline build?

**Comment by mjbvz** [comment] 2019-10-13 03:07
1.40 should be out in the first or second week of November, see #82194

**Closed** 2019-10-13 03:06 UTC
Labels: bug, markdown
