### ISSUE TITLE
Indenting exports overwrites them and then undo doesn't work

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#2884] opened 2016-02-10 10:52 UTC
I'm using the latest version of VS Code on OS X (Version 0.10.8 (0.10.8), db71ac615ddf9f33b133ff2536f5d33a77d4774e).

Replication steps:
Paste the following into a new whatever.ts file.
```
function foo() { }
function bar() { }
function baz() { }

export {
foo,
bar,
baz
};
```

Now highlight the properties of the export (the 3 lines saying foo, bar, baz) and press tab to indent them and it outputs the following and can't be undone using the undo command:
```
function foo() { }
function bar() { }
function baz() { }

export {
	az
};
```

The indenting seems to happen but where did my exports go?! :open_mouth:

**Comment by solidgoldpig** [comment] 2016-02-10 11:17
I can replicate this (VS Code 0.10.8 (0.10.8), OSX 10.10.5)

Before updating I checked in 0.10.6, and the indentation resulted in the correct outcome.

**Comment by SamVerschueren** [comment] 2016-02-10 15:12
duplicate https://github.com/Microsoft/vscode/issues/2829

**Comment by egamma** [comment] 2016-02-10 15:17
closing as a duplicate of #2829. Thanks @SamVerschueren

**Closed by egamma** 2016-02-10 15:17 UTC
