### ISSUE TITLE
main and context menu background flash when open

### ISSUE THREAD

**Issue by MaximS** [microsoft/vscode#102512] opened 2020-07-14 16:48 UTC
Issue Type: <b>Bug</b>
(not very severe)

Main menu and context menus show a white background for a fraction of a second before showing menu itself.
I have a dark Mint theme and dark VS Code theme. The white flash is clearly visible.
Not sure about the cause. On Linux Mint 19.3 I haven't seen this issue. May be it's Linux Mint 20 (recent upgrade), may be this version of VS Code.
If it were Windows I would think about not cancelled WM_ERASE_BACKGROUND without double-buffering. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-40-generic (Linux Mint 20)
GTX-750ti with 440 version of proprietary NVidia driver

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3459)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.60GB (11.30GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
pascal|ale|9.0.0
pascal-formatter|ale|2.2.0
bracket-pair-colorizer|Coe|1.0.61
tslint|eg2|1.0.44
todo-tree|Gru|0.0.178
githd|hui|2.2.4
rest-client|hum|0.24.1
r|Iku|1.4.2
dotnet-core-essentials|Kis|0.0.8
regionfolder|map|1.0.11
Angular-BeastCode|Mik|8.1.2
csharp|ms-|1.22.1
sqltools|mtx|0.22.10
sqltools-driver-sqlite|mtx|0.1.0
angular-console|nrw|12.0.0
vscode-graphql|Pri|0.2.14
partial-diff|ryu|1.4.1
code-spell-checker|str|1.9.0
code-spell-checker-russian|str|0.2.4

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-07-19 03:24
/duplicate of #80798 which gives a workaround as well as a link to the upstream issue

**Closed** 2020-07-19 03:25 UTC
Labels: *duplicate
