### ISSUE TITLE
JavaScript Debug Terminal Doesn't Launch From Run And Debug Dropdown

### ISSUE THREAD

**Issue by adamtMastery** [microsoft/vscode#166396] opened 2022-11-15 20:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1 (Universal)
- OS Version: OSX Monterey 12.6.1 

Steps to Reproduce:

1. Click "Run and Debug"

![Screen Shot 2022-11-15 at 2 27 08 PM](https://user-images.githubusercontent.com/103965368/202018658-fdd4c3f1-c9f0-4542-95ab-8538b0f52ac5.png)

2. Select "JavaScript Debug Terminal" from dropdown
![Screen Shot 2022-11-15 at 2 27 23 PM](https://user-images.githubusercontent.com/103965368/202018706-4b0c0610-9da2-44a5-8dd7-3a657dcb44cb.png)

3. Click Green Start Arrow

![Screen Shot 2022-11-15 at 2 29 43 PM](https://user-images.githubusercontent.com/103965368/202019084-4de6782c-0a5d-441c-9e1d-37c5eabebfb6.png)

The debugger indicates an attached terminal, as the debugger toolbar appears:
![Screen Shot 2022-11-15 at 2 28 19 PM](https://user-images.githubusercontent.com/103965368/202018865-1a536b22-3ebf-4683-afef-b2c7bd60843e.png)

Likewise, the Status Bar indicates a terminal is active:
![Screen Shot 2022-11-15 at 2 28 51 PM](https://user-images.githubusercontent.com/103965368/202018954-186d5afb-b259-4b31-8b82-eab9a10af8a0.png)

However, no JavaScript Debug Terminal actually launches in the IDE:
![Screen Shot 2022-11-15 at 2 27 55 PM](https://user-images.githubusercontent.com/103965368/202018789-74fc8e04-f2b3-4ad6-b300-fb3025fe4d88.png)

**Comment by roblourens** [comment] 2022-11-17 15:52
If you open the terminal view, is there a debug terminal there?

**Comment by adamtMastery** [comment] 2022-11-17 15:56
@roblourens It is not. It's a normal shell terminal (**zsh** in my case), and it doesn't attach to the debugger even after running a node process (`yarn start`) with **Auto-Attach** active.

**Comment by connor4312** [comment] 2022-11-17 16:25
The ID of the process being debugged in shown in the name in the Call Stack view. What is that process?

**Comment by adamtMastery** [comment] 2022-11-17 16:46
12594
![Screen Shot 2022-11-17 at 10 45 47 AM](https://user-images.githubusercontent.com/103965368/202506604-ad1ded90-ede2-4155-b909-ad70dce0cde8.png)

**Comment by gianveloxbr** [comment] 2022-11-17 17:26
same thing here, cannot start debugging a nest.js application, all the output says is /usr/local/bin/node
![image](https://user-images.githubusercontent.com/31005220/202515457-cfef1d75-dddc-47f8-b6cd-f27541a2720e.png)

**Comment by gianveloxbr** [comment] 2022-11-17 17:32
The only solution i've found was to install the latest vscode insiders version, it's the second time this problem happens this year (at least with me) on the base version of vs code.

**Comment by adamtMastery** [comment] 2022-11-17 18:13
@gianveloxbr Yes, this is the third time it's happened for me this year. The first two times, it seems to have eventually sorted itself out, but it's been over a week now and still no luck with this breakdown.

The workaround I've found is to set **Auto-Attach** to `always`  from the **Command Palette** (*Cmd+Shift+P* on **OSX**), then launch a **JavaScript Debug Terminal**  from the **Command Palette** and run a node command such as `yarn start` from there.

This does correctly attach the JavaScript Terminal for debugging!

**Comment by connor4312** [comment] 2022-11-17 19:02
> 12594

I was looking for what that process is actually executing. You can run a command like `ps -eo pid,ppid,%mem,%cpu,args -r | grep <process id here>` to check

**Comment by adamtMastery** [comment] 2022-11-17 20:53
@connor4312 My mistake!

Here's the output from my terminal, with the headless JavaScript Debug Terminal running:

```
68975  1374  0.0   0.7 grep 68837
68951 68837  0.1   0.0 /Users/<MY_NAME>/.asdf/installs/nodejs/16.17.1/bin/node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/watchdog.bundle.js
68837 67905  0.1   0.0 /Users/<MY_NAME>/.asdf/installs/nodejs/16.17.1/bin/node
```

**Comment by connor4312** [comment] 2022-11-17 20:56
Thanks. Unfortunately this looks like a regression that happened partially because I was not around last month to publish a stable release of js-debug. The good news is this should already be fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of js-debug. If you install that, you should be good to go.

This _will_ be fixed in the next release of VS Code in a couple weeks which will bundle the next stable revision of js-debug.

**Closed by connor4312** 2022-11-17 20:56 UTC
Labels: bug, info-needed, debug

**Comment by adamtMastery** [comment] 2022-11-17 21:15
@connor4312 Amazing, thank you!!!
