### ISSUE TITLE
JavaScript files opened via FileSystemProvider extension do not display Outline

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#74611] opened 2019-05-30 11:03 UTC
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Also tested with latest Insiders.

Steps to Reproduce:

1. Install the [Remote FS](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs) extension, which implements `FileSystemProvider`
2. Connect to a remote source (I used an FTP server)
3. Open a .js file

Outline panel reports "The active editor cannot provide outline information".

Breadcrumb shows nothing deeper than the filename.

I assume the builtin vscode.javascript extension isn't providing the information. Perhaps its `DocumentSymbolProvider` implementation doesn't handle a resource that isn't on the local filesystem?

Of course, I may be wrong. Perhaps the `FileSystemProvider` implementation is missing a crucial feature. I have an extension of my own that is derived from Remote FS and exhibits the same lack of outline (and breadcrumb) info. So if my extension needs to implement something extra I'll give that a go. I just need a pointer about what.

**Comment by gjsjohnmurray** [comment] 2019-05-30 11:13
Interestingly, .css and .htm files fetched remotely in the same way **do** display Outline and Breadcrumb info.

**Comment by gjsjohnmurray** [comment] 2019-05-30 13:26
A bit more digging and the finger is pointing to the [TypeScript and JavaScript Language Features](https://github.com/microsoft/vscode/tree/master/extensions/typescript-language-features) builtin extension. [Looks like](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/utils/fileSchemes.ts) it only supports file:// uris plus a couple of extra ones.

@mjbvz am I right that this builtin extension won't handle files sourced by a `FileSystemProvider`? If so, any prospect of this changing?

**Comment by mjbvz** [comment] 2019-05-30 17:24
Duplicate of #59650

**Closed by mjbvz** 2019-05-30 17:24 UTC
Labels: extensions
