### ISSUE TITLE
ExternalTerminal.windowsExec requires tool directory to be on path variable

### ISSUE THREAD

**Issue by richardspence** [Microsoft/vscode#7156] opened 2016-06-02 20:25 UTC
- VSCode Version: 1.1.1
- OS Version: Win 10 enterprise preview 14355.rs1_release.160525-1714

Steps to Reproduce:

1. Install Git-Bash
2. Change setting to "externalTerminal.windowsExec" : "C:\Program Files\Git\git-bash.exe"
3. Use the context menu 'open in cmd prompt'

Expected behavior:
Git bash opens:

Actual behavior:
Command prompt opens with "C:\Program Files\Git\git-bash.exe" in the title.

Workaround: Change the setting to "git-bash" and adjust the user/system PATH variable to include the program files\git location.

**Comment by Tyriar** [comment] 2016-06-02 20:29
This is because we pass "" as the title and I guess it defaults to the full path since `git-bash` isn't a thing if it's not on the `PATH`. Not sure it's worth changing this.

**Comment by richardspence** [comment] 2016-06-02 20:34
Well it's weird behavior since if you put in "foo" as your external tool, it will actually complain that "foo" isn't recognized.  It appears that the title is being passed if the external tool contains a space in the path.  Adding quotes around the path doesn't work either as it looks like it only uses everything after the last space

**Comment by Tyriar** [comment] 2016-07-05 17:53
Closing as designed

**Closed by Tyriar** 2016-07-05 17:53 UTC
