### ISSUE TITLE
[Fedora 25] Release notes window doesn't cover entire page

### ISSUE THREAD

**Issue by luca76** [Microsoft/vscode#17675] opened 2016-12-21 13:50 UTC
- VSCode Version: 1.7, 1.8
- OS Version: Fedora 25

Steps to Reproduce:

1. Check for new version
2. See the release notes page

The release notes doesn't cover entire window, but only a quarter. See the picture.

![schermata del 2016-12-21 14-50-25](https://cloud.githubusercontent.com/assets/5095918/21391650/d8a641e4-c78c-11e6-82e0-946edf4636ac.png)

**Comment by luca76** [comment] 2016-12-21 13:51
Note: this bug happened in 1.7, too.

**Comment by mjbvz** [comment] 2016-12-29 00:46
Since the release notes are shown using a webview, I believe this issue is a duplicate of #5745

**Closed by mjbvz** 2016-12-29 00:46 UTC
Labels: duplicate
