### ISSUE TITLE
Multiple Source Control Extensions no longer working

### ISSUE THREAD

**Issue by bluemonkmn** [microsoft/vscode#146423] opened 2022-03-31 11:45 UTC
Issue Type: <b>Bug</b>

Before applying the latest Visual Studio Code update, it was possible to have multiple source control extensions active simultaneously. After updating to the following version, only one source control extension is visible even if multiple are loaded:
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (13.32GB free)|
|Process Argv|--crash-reporter-id 05c7e705-f248-40ae-97dd-20a6852170e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
infor-landmark-support|Bel|1.1.0
lpl-debugger|Bel|1.0.0
lpl-icons|Bel|1.0.0
lpl-language-support|Bel|1.1.0
lpl-snippets|Bel|1.0.6
accurev|blu|0.1.1
lpl-outline|blu|0.1.8
gitlens|eam|12.0.5
gitlab-workflow|Git|3.41.2
xtend-lang|Gra|0.2.3
indentation-level-movement|kai|1.3.0
rainbow-csv|mec|2.2.0
git-graph|mhu|1.30.0
csharp|ms-|1.24.1
hexeditor|ms-|1.9.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
vscodeintellicode|Vis|1.2.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30463512

```

</details>

**Comment by bluemonkmn** [comment] 2022-03-31 11:53
This might be related to / duplicate of https://github.com/microsoft/vscode/issues/146396

**Comment by lszomoru** [comment] 2022-03-31 12:36
Closing as duplicate of https://github.com/microsoft/vscode/issues/146396

**Closed by lszomoru** 2022-03-31 12:36 UTC
Labels: new release
