### ISSUE TITLE
Typescript formatter inserts to many spaces for multiple objects in a function call

### ISSUE THREAD

**Issue by cnsdato** [microsoft/vscode#74038] opened 2019-05-21 06:16 UTC
Also in Insiders

- VSCode Version: 1.34.0
- OS Version: Windows 10.0.17763

Steps to Reproduce:
1. Create a TS file like this:
```typescript
function foo(a, b): void {

}

foo({
  a: 1,
  b: 2
}, {
  c: 3,
  d: 4
});

const arr = [{
  a: 1,
  b: 2
}, {
  c: 3,
  d: 4
}];
```
2. Format document
3. Formating is weird in lines 9-11
![kRRcxoMsVn](https://user-images.githubusercontent.com/1501909/58072497-29eea400-7ba0-11e9-8bb4-d4dac593b4c6.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment] 2019-05-21 18:20
Duplicate of https://github.com/microsoft/TypeScript/issues/14589

**Closed by mjbvz** 2019-05-21 18:20 UTC
Labels: typescript
