### ISSUE TITLE
HTML - p tag inside a p tag

### ISSUE THREAD

**Issue by samirdadashzade** [Microsoft/vscode#29136] opened 2017-06-20 20:59 UTC
Hi.
I'm using Visual Code daily, so I would want one issue to be handled. When writing an HTML code in some online text editors when I put a &lt;p&gt; tag inside another &lt;p&gt; tag, I get a reasonable syntax error indicating that it is not right, because we can't give any CSS properties (just can't style) that inner &lt;p&gt; tag. But maybe for some reasons it doesn't give any kind of snytax error when I type in Visual Code. So I think that it would be great if this issue was taken into account by Visual Code Developers. Hopefully, this will make You curious as it made me :)

Thanks.
Best regards.

**Comment by ramya-rao-a** [comment] 2017-06-20 21:02
Can you give sample code? May be a screen shot of the syntax error you are expecting?

**Comment by samirdadashzade** [comment] 2017-06-22 05:43
Well, I attach images from "w3schools.com" and "jsfiddle.net" online code editors. Please, see the below images:
1) When we write a <p> tag inside a <div> (w3schools):
![capture1](https://user-images.githubusercontent.com/19173164/27418784-7703b85e-572e-11e7-8cea-80afa5ec7e59.PNG)
2) When we write a <p> tag inside another <p> (w3schools):
![capture2](https://user-images.githubusercontent.com/19173164/27418788-7a28aa6c-572e-11e7-9624-9a8f7bd10d0b.PNG)
3) When we write a <p> tag inside another <p> (jsfiddle):
![capture3](https://user-images.githubusercontent.com/19173164/27418790-7c86c276-572e-11e7-9199-e4b419567a47.PNG)

As You see, when we write a <p> tag inside another <p>, both of the code editors highlight the closing outer <p> tag with red in addition to highlighting the closing <body> and <html> tags.

Thanks.
Best regards.

**Comment by aeschli** [comment] 2017-06-22 07:54
Thanks for the explanation. This is a duplicate of #23199

**Closed by aeschli** 2017-06-22 07:54 UTC

**Comment by samirdadashzade** [comment] 2017-06-22 08:09
Well, Martin.
I don't think that my question is a duplicate of "Should show an error if html end or start tag is missing". I guess my issue is specific to &lt;p&gt; tag that we just can not create nested &lt;p&gt; tags inside each other. It is not about end tag or start tag. It relates only to &lt;p&gt; tags.

Thanks.
Best regards.
