### ISSUE TITLE
Blue line in the left of explorer icon in activity bar when mouse down.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#122003] opened 2021-04-23 09:20 UTC
- VS Code Version: 1.56.0 insider - commit: 0310f02
- OS Version: Windows 10 20h2

Steps to Reproduce:

@sandy081 I have noticed this blue line in the left when mouse down only in file icon and this doesn't shows in the other icons. (0310f02) - Ref: https://github.com/microsoft/vscode/issues/118077#issuecomment-825471885

![image](https://user-images.githubusercontent.com/17777237/115838239-bf90af00-a419-11eb-870f-da481c71db6a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment] 2021-04-23 13:23
Yes, this is the focus state for the activity bar. If you tab into the activity bar you'll see this as well so this is by design.

**Comment by pixieaka** [comment] 2021-04-23 18:05
@misolori But it's only in first icon ( explorer icon )! The other icons doesn't have focus state.

**Comment by misolori** [comment] 2021-04-24 22:41
@pixieaka this happens on all icons:

https://user-images.githubusercontent.com/35271042/115974717-72910380-a513-11eb-8b37-48ae14d11b14.mp4

**Comment by pixieaka** [comment] 2021-04-24 23:48
@misolori This not working with me in all icons !

![Animation](https://user-images.githubusercontent.com/17777237/115975789-2f14b480-a568-11eb-82db-a0a85b0b1bbe.gif)

![image](https://user-images.githubusercontent.com/17777237/115975800-3d62d080-a568-11eb-88f1-88aa8b5dcdf4.png)

**Comment by misolori** [comment] 2021-04-26 16:05
@sandy081 assigning to you since it seems the active state does not appear until after you've had keyboard access, so looks like a bug in the activity bar:


https://user-images.githubusercontent.com/35271042/116114809-8f8e1980-a66e-11eb-8e08-02a111c6c4d1.mov

**Comment by pixieaka** [comment] 2021-04-26 19:28
@sandy081 After latest update all icons works fine, But `Timeline` still doesn't work.

![image](https://user-images.githubusercontent.com/17777237/116139265-1f1ae300-a6d6-11eb-9a9c-bfd367236249.png)

**Comment by misolori** [comment] 2021-04-26 19:44
It seems like the behavior is inconsistent overall. Sometimes it show and other times it doesn't.

**Comment by sandy081** [comment] 2021-07-28 13:47
Blue line is showed when the item is focused and I am not sure why the item is not set to focused on click. More strangely it only works for the first item.

**Comment by hi-ogawa** [comment] 2021-08-22 11:54
Hi everyone, I made a PR to address this issue.
I explained it in the PR comment, but what I found is that `tabindex` attribute is only enabled for the first activity bar item, which is the "file explorer" tab. Note that "tabindex" is necessary for `li` tag (which is used for activity bar item) to have the ability of `:focus` selector to match and correct styling.
Please let me know if the PR properly solves the issue (and, importantly, doesn't make a new bug).

**Closed** 2024-12-12 10:37 UTC
Labels: bug, help wanted, workbench-views, wont-fix
