### ISSUE TITLE
Allow bottom panel to be maximised when using "justified" display mode

### ISSUE THREAD

**Issue by andrewmcdonald-oxb** [microsoft/vscode#143294] opened 2022-02-17 16:55 UTC
I noticed that when the bottom panel is set to the new "justified" setting (which occupies the full width of the host window, so it also sits below the side panels) then the "maximise" button disappears. You have to manually drag the divider to achieve the same effect.

This is important to me, as I use a rotated widescreen monitor. The setup is very narrow, so I want the bottom panel in "justified" mode to maximise its width. I also frequently want to maximise it to see more stuff vertically too.

**Comment by IllusionMH** [comment] 2022-02-17 18:00
Looks like duplicate of #141094
Please upvote that issue.

**Comment by andrewmcdonald-oxb** [comment] 2022-02-17 18:02
Aha, thanks. I did search, but on terms like "justified" which didn't yield that result!

**Closed** 2022-02-17 18:33 UTC
Labels: triage-needed
