### ISSUE TITLE
"A system error occurred" when opening web in desktop

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91495] opened 2020-02-25 23:27 UTC
ref #91225 on ubuntu

![image](https://user-images.githubusercontent.com/8586769/75296888-4b418800-57e3-11ea-8397-5bbe3639b1e5.png)

**Comment by bpasero** [comment] 2020-02-26 06:31
This seems unrelated to opening a link to me.

**Comment by joaomoreno** [comment] 2020-02-26 13:22
Caused by https://github.com/microsoft/vscode/pull/89199, will be fixed with https://github.com/microsoft/vscode/issues/89593

@bpasero Is it critical for February?

**Closed by joaomoreno** 2020-02-26 13:22 UTC
Labels: install-update, snap

**Comment by bpasero** [comment] 2020-02-26 13:33
If you ask for the "Open in Desktop" support, I think this is not critical for February. But I am not sure how this triggers the issue. It would probably happen for any protocol link invocation then.
