### ISSUE TITLE
Feature requests about the workspace explorer tree branches

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43044] opened 2018-02-06 15:55 UTC
- VSCode Version: 1.20.0-ins
- OS Version: win7x64

I don't know how is it hard for devs to implement, but I'm gonna propose it anyway...

So, when I take a glance at workspace explorer tree, for me it always hard to figure out - what file belongs to what folder... so, branches would make it much more easier:

![workspace tree1](https://user-images.githubusercontent.com/24613274/35867515-98a3b534-0b62-11e8-895e-6dbdc1a267cc.png) ---> ![workspace tree](https://user-images.githubusercontent.com/24613274/35867351-32fdedc6-0b62-11e8-9c5f-bcb0e8aafce2.png)

Don't you think?..

And here is one more idea about hover effect: make highlighting of each file in different folder group - different. Not for width 100% for any file. Also it would be great - to highlight specific branch (from root of tree to hovered file) with more brightness or somehow. 

And maybe highlight all folders, which concerned with a file we hovered, and go up to very root.

example:
![workspace tree3](https://user-images.githubusercontent.com/24613274/35868649-c98d5896-0b65-11e8-9d1f-99b4a9a730a7.png)

Maybe a little `border-radius` for highlighted rectangles, a little `transition`... and it would be great.

**Comment by bpasero** [comment] 2018-02-06 16:27
Duplicate of https://github.com/Microsoft/vscode/issues/17777

**Closed** 2018-02-06 16:27 UTC
Labels: file-explorer
