### ISSUE TITLE
Scroll lag with 4k monitors

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#91643] opened 2020-02-27 01:31 UTC
I got a new amazing monitor and it's nice when I scroll in firefox. In vscode scrolling is fast but laggy in comparison. 60 fps scrolling feels very nice. I don't think I even get 30fps when scrolling. definitely faster than 15 fps. Make it smooth too, scrolling is jittery. For perspective when I scroll in firefox or watch a video I notice a difference in smoothness when I go back to vscode. But coding in vscode for a while my brain just forgets about the smoothness & jitteryness as it's already pretty smooth. I have noticed this issue before, but with my new high refresh rate monitor it's more noticeable. You guys are already doing amazing job with smoothness. I like that 60 fps scrolling feeling :grinning: I want more of it.

**Comment by rebornix** [comment] 2020-02-27 17:54
Thanks for the feedback, it's a duplicate of https://github.com/microsoft/vscode/issues/9432 and currently we don't have a sound solution for it considering we are on top of Electron.

**Comment by deepak1556** [comment] 2020-03-11 06:44
@graph just to confirm is this on windows ?

**Comment by graph** [comment] 2020-03-11 17:38
I got a new monitor at home using Ubuntu 20 Beta, but it's clear all platforms don't do 30fps. I don't do full screen, but when I tried to expand my window I noticed issue #9432 does apply and scrolling FPS does drop. I have smooth scrolling enabled on all platforms. Interesting on Mac it's the smoothest. It also depends on projects, larger projects have clearly slower scrolling performance. I feel c++ code has worst fps, but that could just be cause I have c++ addons installed for vsscode, and my code base is significantly larger for c++. Electron on mac says ~50fps but it doesn't feel that smooth. Firefox feels very smooth for scrolling web pages. Maybe scrolling needs more tweening?

**Comment by deepak1556** [comment] 2020-10-14 01:30
@graph is this still an issue with latest stable `1.50` ?

**Closed** 2020-10-21 11:29 UTC
Labels: needs more info, trackpad/scroll, upstream

**Comment by graph** [comment] 2020-11-13 00:43
it's definitely smoother. But firefox does feel smoother.

**Comment by deepak1556** [comment] 2020-11-13 20:51
Does running with `--disable-renderer-accessibility` help improve the perf ?

**Comment by graph** [comment] 2020-11-25 00:56
Sorry but, I have ulimits set on my machine that can support the high framerates, and vscode won't start with ulimits and I'm unable to test this without inconveniencing myself and reverting the ulimit rules. I was hoping I would do so, but it's been 11 days and it doesn't look like I will revert the necessary changes temporarily to be able to start vscode, and there doesn't appear to be a way to change global ulimits without a reboot. Because of the ulimits issue I'm unable to use vscode, and I do miss it.
