### ISSUE TITLE
Why is the extra dialog needed at all when clicking a link?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122324] opened 2021-04-27 12:41 UTC
Testing #121763

It's not clear why this is needed, for debugging it makes sense since the click/keyboard event happens a while ago so the browser no longer treats it as a "user event". But for clicking a link in the editor, that's already a user event, so why would the browser block it if we handle the click event properly?

Related: https://github.com/microsoft/vscode/issues/122323

**Comment by isidorn** [comment] 2021-04-27 12:45
We only show the dialog if the browser blocked the open.
I am not 100% sure why safari blocked the link opening. My best guess would be because it is handled async.
Maybe @bpasero has a better answer.

**Comment by Tyriar** [comment] 2021-04-27 12:49
For cases like this, we should track down why it's async and make sure it really needs to be. If async work is required we could do it before the show the popup is shown so the button click can be handled synchronously.

**Comment by bpasero** [comment] 2021-04-27 12:50
I think @mjbvz explained this here: https://github.com/github/codespaces/issues/2213#issuecomment-782544411

**Comment by isidorn** [comment] 2021-04-27 12:53
Ok, so let's close as a dupe of that issue.
@mjbvz let me know if you would prefer to also have an issue in this repo and I can reopen this. Thanks

**Closed by isidorn** 2021-04-27 12:53 UTC
