### ISSUE TITLE
Close to tray

### ISSUE THREAD

**Issue by Adiqq** [Microsoft/vscode#33263] opened 2017-08-28 14:34 UTC
Hi, 

Visual Studio Code can take some time to open (especially visible on laptops or slow HDD).
I'm not aware if this feature already exists (integrated or provided by some extension), but it would nice if it started at boot, minimized to tray and close button would also minimize it to tray.

**Comment by devcompl** [comment] 2017-09-15 11:09
Duplicate of #11723

**Closed** 2017-11-16 17:42 UTC
Labels: feature-request, perf, workbench
