### ISSUE TITLE
Marketplace search for file extensions doesn't give good enough results

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#41781] opened 2018-01-18 01:33 UTC
- VSCode Version: 1.19.2
- OS Version: Any

Steps to Reproduce:

1. Create a file `test.stylus`.
2. The mode is `Plain Text`. Click on it and then select `Select Marketplace Extensions for .stylus...`
3. The result is a single extension 

<img width="419" alt="screen shot 2018-01-17 at 5 29 18 pm" src="https://user-images.githubusercontent.com/16890566/35076215-0b65e5f4-fbac-11e7-9657-13a3e4430dc2.png">

4. Now search for "stylus" in the extensions viewlet. The search results has many more extensions with the top one having higher install count and rating than the one in the previous step

<img width="419" alt="screen shot 2018-01-17 at 5 29 32 pm" src="https://user-images.githubusercontent.com/16890566/35076230-26e19d50-fbac-11e7-8f4c-826a567d3a8f.png">

**Comment by ramya-rao-a** [comment] 2018-01-19 19:37
@sandy081 behind the scenes the the search text being formed is `tag:"__ext_stylus"`. If `stylus` was one of the supported mimetypes, then the request would have been `tag:"__ext_stylus" tag:stylus` which yields better results, but the order would not yet desirable

![image](https://user-images.githubusercontent.com/16890566/35168257-1bd46746-fd0d-11e7-859e-d76469c6eb60.png)

**Comment by sandy081** [comment] 2018-01-22 10:12
@ramya-rao-a First of all, While generating the VSIX, we generate internal tags in the format `__ext_<ext>`. `<ext>` is read from `extensions` section under language contributions. So if an extension contribute a language with associated file extensions say `.stylus` then we generate tag `__ext_.stylus`. 

**Note** that all extensions contributions under languages section will have `.` in the beginning.

Looks like we have a bug in our VS Code that we are not adding `.` while generating the query for extension. For eg., our query is always `__ext_stylus` and hence it is not finding some extensions with `.stylus` lang extension contributions. Added a fix for this.

After fixing here are the results when I do `Select Marketplace Extensions for .stylus...`

![image](https://user-images.githubusercontent.com/10746682/35215315-2b9afa06-ff64-11e7-914e-ea870c6cf592.png)

`stylus` extension is at the bottom because, it is not properly tagged. When I looked into its `vsixmanifest` file, it does not have our internal tags for extensions. Hence it is at the bottom. This can be confirmed by using the query `tag:__ext_.stylus`. I guess that extension was not packaged properly, hence did not have appropriate tags. May not be maintained too as it was last updated two years back.

I assume, after my fix extensions are returned in proper order. Check it out.

**Comment by sandy081** [comment] 2018-01-22 14:48
@ramya-rao-a I think part of my assumption is partially wrong in the above comment. VSCE was generating the tags from file extensions with `.` character. But there was a fix couple of months ago to remove non-word characters. 

So, this resulted in two kinds of tags for file extensions for a language extension, one with `.` (__ext_.stylus) and other without (__ext_stylus). 

Update the fix to support both kinds of tags.

**Comment by ramya-rao-a** [comment] 2018-01-22 18:17
@sandy081 Though the current fix does fix the issue for extensions with tags starting from `.`, it doesnt address my initial concern as described in https://github.com/Microsoft/vscode/issues/41781#issuecomment-359067901

When you have an extension installed to support stylus and then do the search, you get the results similar to https://github.com/Microsoft/vscode/issues/41781#issuecomment-359379170

But, do the same search after disabling/uninstalling the extension that supports stylus, then you end up with only 2 results

![image](https://user-images.githubusercontent.com/16890566/35236551-98b53b2c-ff5c-11e7-99c7-057e3821fdd6.png)

The root cause is that for languages with known mimetypes, `tag:languageName` gets added here: https://github.com/Microsoft/vscode/blob/de220368be1cf08ece9d5a9bd8bb858f1e921994/src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts#L231-L237

And for languages with unknown mimetypes, this additional tag is missing in the search.

I suggest to change ```const languageTag = languageName ? ` tag:"${languageName}"` : '';```
to ```const languageTag = ` tag:"${languageName || ext}"``` ;

**Comment by sandy081** [comment] 2018-01-25 17:44
@ramya-rao-a file extension and language id cannot be same always. So calling that a language tag might not be right. Instead we can append the extension tag to the query. 

```
`tag:"__ext_${ext}" tag:"__ext_.${ext}" tag: ${ext} ${keywords.map(tag => `tag:"${tag}"`).join(' ')}${languageTag}`; 
```

I think it makes sense to also get extensions tagged by file extension.

**Closed** 2018-01-25 17:47 UTC
Labels: bug, extensions

**Comment by ramya-rao-a** [comment] 2018-01-25 18:47
Works well for stylus now, but there is noise for other file types, mostly due to bad tagging, will dig deeper
