### ISSUE TITLE
This pane is too large 

### ISSUE THREAD

**Issue by HeroSuperGaming** [Microsoft/vscode#41178] opened 2018-01-05 08:51 UTC
![bug](https://user-images.githubusercontent.com/28282044/34601775-1b2c0770-f206-11e7-9c78-e3deb232cf23.jpg)

- VSCode Version:1.20 
- OS Version:Windows 10 

Steps to Reproduce:

1.Open VS Code 
2.Select the VIEW Pane 

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by HeroSuperGaming** [comment] 2018-02-08 13:12
Still effects 1.21.0 insiders build

**Comment by bpasero** [comment] 2018-06-28 09:34
Duplicate of https://github.com/Microsoft/vscode/issues/16826

**Closed by bpasero** 2018-06-28 09:34 UTC
Labels: electron, upstream, workbench-menu
