### ISSUE TITLE
 AbstractMirrorModel.getPositionFromOffset: Model is disposed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1809] opened 2016-01-06 04:58 UTC
Issue Id: <b>7cdf41c7-6071-4fe6-0ad7-ebedc86c54c9</b><br /><br />*Versions* <br />- 0.10.5<br />-  a80232bbcfe8a5cdad1ebc98638673d9dcb02458<br />*Stack* <br />Error: AbstractMirrorModel.getPositionFromOffset: Model is disposed<br />[/vs/editor/common/model/mirrorModel.ts#L130:9 (AbstractMirrorModel.getPositionFromOffset)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/common/model/mirrorModel.ts#L130:9 (AbstractMirrorModel.getPositionFromOffset))<br />[/vs/languages/json/common/jsonWorker.ts#L174:37 (JSONWorker.doValidate)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/languages/json/common/jsonWorker.ts#L174:37 (JSONWorker.doValidate))<br />    at Array.forEach (native)<br />[/vs/languages/json/common/jsonWorker.ts#L169:41 (JSONWorker.doValidate)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/languages/json/common/jsonWorker.ts#L169:41 (JSONWorker.doValidate))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1023:0 (then)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1023:0 (then))<br />

**Comment by aeschli** [comment] 2016-01-27 14:04
duplicate of #2234

**Closed by aeschli** 2016-01-27 14:04 UTC
Labels: error-telemetry
