### ISSUE TITLE
Suggest widget fails to add import

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116765] opened 2021-02-16 11:18 UTC
I hit this soooo often, and for soooo long, I am surprised no one else sees it:

1. In a TS file, type a symbol from another file
2. At the end, press <kbd>Ctrl Space</kbd> and select it with <kbd>Enter</kbd> to add it to the imports

🐛 TypeScript doesn't add any import statement.

I have a very hard time reproducing this, unfortunately. As I tried to repro for a recording I completely failed. @mjbvz Can you review the code here and see if there are any holes in the logic which might cause this?

cc @jrieken

**Comment by joaomoreno** [comment] 2021-02-16 15:00
Yup

![recording (14)](https://user-images.githubusercontent.com/22350/108080366-a25bf080-7024-11eb-9870-a8b237f386ff.gif)

**Comment by mjbvz** [comment] 2021-02-16 20:35
Is this in the latest insiders?

**Comment by joaomoreno** [comment] 2021-02-17 08:54
Yeah, tho I hit this for at least 2+ months.

**Comment by mjbvz** [comment] 2021-02-17 16:34
I should have mostly fixed this this iteration, which is likely why you are having trouble reproducing it

Can you share a specific repo where you still see it?

**Comment by joaomoreno** [comment] 2021-02-17 16:47
I only ever saw this in microsoft/vscode. I can never repro on demand unfortunately...

**Comment by mjbvz** [comment] 2021-02-17 17:18
Ok, I'm going to close this as a duplicate of #109439 then

If you find a specific case where this doesn't work, please let me know

**Closed by mjbvz** 2021-02-17 17:18 UTC
