### ISSUE TITLE
Color picker does not show on color affordance

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42720] opened 2018-02-01 10:46 UTC
Steps to Reproduce:

1. open settings
2. define a setting that shows a color decoration (like `workbench.colorCustomizations`)
3. hover over color decoration

The color picker does not show up (works fine in stable)

![image](https://user-images.githubusercontent.com/900690/35674617-7e781bda-0745-11e8-8c98-8fe313480020.png)

**Comment by aeschli** [comment] 2018-02-01 10:48
It shows up on the text (`#ff0000`) so the language server provides the ranges.

**Comment by eamodio** [comment] 2018-02-16 20:23
Not sure if this is related or not, but I've found it tricky to get the color picker to show up in css/scss files.

![hovers](https://user-images.githubusercontent.com/641685/36327614-106580bc-132d-11e8-8d29-4d3ae885d927.gif)

You can see in the gif that if you start over the color text it does show, but if you hover over anything before the color itself it won't switch to the color picker when you move. And if you hover on the color swatch itself it won't show (which is what I always try).

**Comment by hibyguy** [comment] 2018-02-18 01:49
Hey, guys first post ever on a github public repo! From bisecting the repo I was able to find the first place to look. Unfortunately, it landed on merge 1287a5dd31956b2. I'm relatively new to the vs code repo so I can't really provide more details. I hope this helps!

**Comment by BernardoMB** [comment] 2018-03-01 03:18
You have to hover the text, not the colored box

**Comment by MrChriZ** [comment] 2018-04-03 12:39
It seems strange to me that hovering over the colored box doesn't work.  It's instinctively the place where I go to - as other applications tend to work this way.

**Comment by aeschli** [comment] 2018-04-03 13:36
@rebornix This is a regression, would be good to plan it...

**Comment by pelx** [comment] 2018-08-23 10:40
I switched from brackets to VSC and was frustrated with this issue. Still cant make it work. It only works if CP opens above the color...

**Comment by tiagossa1** [comment] 2018-09-12 17:07
@eamodio You deserved my login just comment + like your post! This is the best workaround for this!!
Like others, I'm having trouble trying to get color picker to appear.

**Comment by rebornix** [comment] 2018-09-20 21:10
This issue shares the same root cause as https://github.com/Microsoft/vscode/issues/40634 so let's track it there.

**Closed** 2018-09-20 21:10 UTC
Labels: *duplicate, bug, editor-color-picker
