### ISSUE TITLE
Panel can be almost completely squashed by resizing window, despite room available in viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37377] opened 2017-11-01 03:49 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.4
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
vscode-rust|kal|0.4.2
vscode-scss|mrm|0.6.2
cpptools|ms-|0.14.0
seti-icons|qin|0.1.3

(3 theme extensions excluded)

---

#36906 

Repro:

1. Size the viewlet large
2. Reduce the window width significantly, but not inside the viewlet:

![image](https://user-images.githubusercontent.com/2193314/32259310-c6019452-be7c-11e7-9325-9e95e5efb5aa.png)

Resizing down again will give what I expect:

![image](https://user-images.githubusercontent.com/2193314/32259334-fbaf2a10-be7c-11e7-89bf-7836e9ada585.png)

**Comment by isidorn** [comment] 2017-11-01 07:17
This should be fixed in latest insiders. Closing as duplicate of some issues than Ben filed.
Please let me know if you still see this and I will reopen

**Closed by isidorn** 2017-11-01 07:17 UTC
Labels: bug, workbench
