### ISSUE TITLE
Tabs & Spaces before braces in control flow statements?

### ISSUE THREAD

**Issue by azarus** [Microsoft/vscode#31272] opened 2017-07-23 02:40 UTC
Enter after typing a control flow statement puts spaces or tab.

![Fucked up control flow](https://i.imgur.com/D9lomEa.png "Fucked up control flow")

Typing  an if statement
causes code to look like this:

```javascript
if(true)
    {
// Why is there a tab?
    }
```

Note the tabs before the braces?

It should work like this
```javascript
if(true)
{
 // No tab before the braces!
}
```
I have no idea if this is an option or not, but if this is an option i'd recommend to remove it immidiately because that is just "jesus what the hell is that?". I have no idea what happened it started to act this weird after updating to the latest version.

More here:

![Fucked up braces]( https://i.imgur.com/60d0GUL.png "Fucked up braces")

**Comment by azarus** [comment] 2017-07-23 02:54
Downgrading to the 2017 may version and disabling the bullshit garbage updates fixed the issue.  Thanks a lot for driving me crazy with the awesome updates.

**Comment by mjbvz** [comment] 2017-07-24 20:56
Duplicate of #30933

Please do not add unnecessary side snark when reporting issues: https://opensource.microsoft.com/codeofconduct/

**Closed by mjbvz** 2017-07-24 20:56 UTC
Labels: duplicate, javascript

**Comment by simonl65** [comment] 2017-07-31 12:45
@mjbvz There's a large number of issues raised for this and many seem to be getting closed with reference to others. **This needs to be fixed**

**Comment by davidstlyoui** [comment] 2017-07-31 13:08
Ok so we have a big problem here... Javascript is impossible to use right now with 1.14 because of this bug. There are like 5 tickets on this, and they are all closed without a fix. All marked as duplicate with each other. Where is the REAL ticket? This is a blocker!
#30933 is closed, with only "yo just used previous version".

**Comment by mjbvz** [comment] 2017-07-31 15:44
As already noted, this is tracked by #30933
