### ISSUE TITLE
Reveal in Side Bar not working

### ISSUE THREAD

**Issue by vedmant** [microsoft/vscode#84631] opened 2019-11-12 23:20 UTC
Issue Type: <b>Bug</b>

I opened index.d.ts file from my node_modules folder with command + click on the imported object, then when I try to right click on the editor tab title and select "Reveal in Side Bar" nothing happens, side bar doesn't respond on this.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-routes|aki|0.3.1
svelte-intellisense|ard|0.7.1
vscode-mjml|att|1.6.0
rails|bun|0.13.1
vscode-gemfile|bun|0.0.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
activitusbar|Gru|0.0.21
svelte-vscode|Jam|0.9.3
auto-comment-blocks|kev|1.0.1
sftp|lix|1.12.9
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
python|ms-|2019.10.44104
vscode-react-native|msj|0.13.1
vetur|oct|0.22.6
ruby|reb|0.25.3
slim|sia|0.1.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by isidorn** [comment] 2019-11-14 16:34
Works for me. What are you doing differnetly than me?
Can you repro with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you share a repository for which you can always reproduce?
Also do you see some error if you open F1 > developer tools > debug conosle?

![sidebar](https://user-images.githubusercontent.com/1926584/68876566-f632a800-0704-11ea-8fbc-bfa683b06e90.gif)

**Comment by vedmant** [comment] 2019-11-14 16:44
@isidorn Try to open file from node_modules folder, I checked debug conosle, no errors. Here is small video: https://screencast.com/t/9054kgKXy8

**Comment by isidorn** [comment] 2019-11-14 16:51
Also works fro mnode_modules.
Please answer my other questions. Thanks

**Comment by vedmant** [comment] 2019-11-14 17:00
It's the same in insiders, it also works only with index.d.ts file from node_modules, here is video from vscode insiders: https://screencast.com/t/4ALaicCVUUQ here is that repo I work with https://github.com/vedmant/running-time-react

**Comment by isidorn** [comment] 2019-11-15 14:47
I have just cloned your repo. Can you just write the exact steps you do when you open that repo?
I do not have flash player and do not see your videos. So please provide steps, thanks

**Comment by vedmant** [comment] 2019-11-15 22:07
Open `screens/Entries/EditEntryScreen.js`, click on `import { StyleSheet, View } from 'react-native'` View with command button pressed. It will open `/Users/vedmant/Library/Caches/typescript/3.6/node_modules/@types/react-native/index.d.ts` this is where Reveal in Side Bar not working. 

Here I made mp4 video https://a.uguu.se/7VmCKk1MAvm2_Nov-16-201900-02-32.mp4

**Comment by isidorn** [comment] 2019-11-19 15:29
That file is outside of your workspace, thus the reveal in side bar does not work. It is not in the sidebar, it is not part of your workspace.
Reveal in Finder for example nicely revelas it in the Finder.

The issue is that Typescript cmd + click, navigates to the index.d.ts that is outside of the workspace, and not inside node_modules. 
The issue for this is that you do not have react-native types in your node_modules. So please setup the dependencies in your project proprely.

Closing since this is designed behavior

**Closed by isidorn** 2019-11-19 15:29 UTC
Labels: file-explorer, needs more info

**Comment by vedmant** [comment] 2019-11-19 15:34
Yeah, I understand that, I didn't expect it will open anything outside of the project. It also was not clear why it didn't work cause there were no any message, it just silently didn't work. I think it might be a good idea to notify user why file can't be revealed in the sidebar with some message.

**Comment by isidorn** [comment] 2019-11-19 15:49
Yes, the sidebar could notify the user why it does not work.
However I am not a fan of notifications and too much spam and will only add it if more users encounter the same issue. Hope that makes sense.
