### ISSUE TITLE
CSS imports path autocomplete not working within css/sass/scss/less

### ISSUE THREAD

**Issue by saurabh-sharma** [Microsoft/vscode#53932] opened 2018-07-10 07:14 UTC
- VSCode Version: Version 1.25.0 (1.25.0)
- OS Version: macOS 10.13.3 (17D102) High Sierra

Steps to Reproduce:

1. Open any css file
2. write `@import '<-path goes here->'
3. You will notice there's no path suggestion as it used to be earlier.

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/3684584/42494797-e8d61ef2-843e-11e8-89eb-4171bc009187.png)

**Comment by octref** [comment] 2018-07-11 23:07
Duplicate of #51331.

**Closed by octref** 2018-07-11 23:07 UTC
