### ISSUE TITLE
[regression] Highlights no longer rendered for match case whole word

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23540] opened 2017-03-29 09:40 UTC
* close the find widget
* press alt+c

stable:
![image](https://cloud.githubusercontent.com/assets/5047891/24448385/49f50946-1474-11e7-9467-5342027c31bb.png)

insiders:
![image](https://cloud.githubusercontent.com/assets/5047891/24448411/61d6ea48-1474-11e7-96d5-664c0db7e5c5.png)

**Comment by aeschli** [comment] 2017-03-29 09:41
duplicate of #23441

**Comment by alexandrudima** [comment] 2017-04-11 16:32
This has not been fixed with the fix for #23441 :|

**Comment by aeschli** [comment] 2017-04-12 06:59
Ah, now I understand how to get the small filter selection widget. :-)

**Closed** 2017-04-12 08:53 UTC
Labels: important, themes
