### ISSUE TITLE
Cannot open Jupyter notebook files, .ipynb

### ISSUE THREAD

**Issue by daniel347x** [microsoft/vscode#130586] opened 2021-08-11 04:36 UTC
Issue Type: <b>Bug</b>

I have disabled all extensions and reloaded VSCode, leaving only the Python extension, the Pylance extension, and the Jupyter extension enabled. I have also set the Jupyter server as I always do and have for years. No matter what I do, my Jupyter notebooks do not open. They just show up as text files. This is a very recent problem.

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.65GB (225.71GB free)|
|Process Argv|--crash-reporter-id d848feff-4ee7-4665-988c-0bf5e3a4a18a|
|Screen Reader|no|
|VM|22%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by rebornix** [comment] 2021-08-18 17:22
This is a duplicate of https://github.com/microsoft/vscode/issues/131040 and we are going to have a fix it soon in recovery build. thanks for the info.

**Closed** 2021-08-18 17:22 UTC
Labels: *duplicate, notebook
