### ISSUE TITLE
Hidden spaces inserted when using Sogou Chinese input method

### ISSUE THREAD

**Issue by legendtang** [Microsoft/vscode#39295] opened 2017-11-29 09:08 UTC
- VSCode Version: <= 1.18.1
- OS Version: macOS 10.13.1
- Input Method: Sogou 4.4.0

Steps to Reproduce:
![](https://i.imgur.com/sbEm1cR.gif?noredirect)

1. Input a sentence
2. Switch to Chinese mode accidentally and want to switch back to English mode, press "Delete" twice then save first.
3. Then you found a hidden space which is not UTF-8 character. That means you can delete twice between two characters (in the video, hidden space occurs between 'i' and 'n').

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-11-30 10:15
I believe this is a duplicate of #38897. Has to do with showing a webview (a preview of LaTeX or markdown)

**Closed by alexandrudima** 2017-11-30 10:15 UTC
Labels: bug, editor, editor-ime
