### ISSUE TITLE
Failure to recognise OS / save to default keyring - Pi5 bookworm debian / raspberry pi OS

### ISSUE THREAD

**Issue by tyeth** [microsoft/vscode#196961] opened 2023-10-30 09:48 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest insiders on bookworm
- OS Version: latest 64bit full desktop raspberry pi OS

Steps to Reproduce:

1. Install an extension that uses github
2. Follow the github signin request notification and sign in to github - returning to code-insiders
3. Notice popup suggesting only weak encryption available.
4. install `seahorse` and verify if keychain exists (no).
5. add a password keychain.
6. set as default and ensure unlocked
7. restart code-insiders and repeat steps 2+3
8. same problem

Output of `code --verbose --vmodule="*/components/os_crypt/*=1"`
```
[8359:1030/094109.755219:INFO:CONSOLE(645)] "%cTRACE color: #888 [mainThreadSecretState] Getting password for vscode.github-authentication extension:  github.auth", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (645)
[8359:1030/094109.755771:VERBOSE1:key_storage_util_linux.cc(54)] Password storage detected desktop environment: (unknown)
[8359:1030/094109.755812:VERBOSE1:key_storage_linux.cc(128)] Selected backend for OSCrypt: BASIC_TEXT
[8359:1030/094109.755883:VERBOSE1:key_storage_linux.cc(148)] OSCrypt did not initialize a backend.
```

I'm aware that I can specify the security storage backend manually, due to the really informative help link (kudos), but that's not the issue. I don't care about encryption on these machines so basic / weak encryption will suffice until code-insiders works properly out the box. I also disagree with directing the user to a website for deb updates, please just push updates to official OS package repositories as quickly as possible so users get what they expect when installing via OS tools rather than old sauce. Surely the comfort / value of automated security updates would be motivation enough to reduce the release lag to package repositories as much as possible.

**Comment by TylerLeonhardt** [comment] 2023-10-30 16:26
@tyeth since you except the risk of basic encryption, the steps to enable it can be found here:
https://code.visualstudio.com/docs/editor/settings-sync#_not-recommended-configure-basic-text-encryption

we don't do this by default because we don't want the user to be automatically opted into an experience they potentially don't want.

**Comment by tyeth** [comment] 2023-10-30 17:06
Thanks, as mentioned I already read that, it's the link from the error popup. It's very informative, although maybe not for less technical users.
 The issue is the OS should be detected. Also if a keyring is created and set as default and unlocked that should also work.

**Comment by TylerLeonhardt** [comment] 2023-10-30 17:33
Your OS not being detected is a duplicate of https://github.com/microsoft/vscode/issues/187338 where we have other users on various linux distros that don't get picked up. A change needs to come from Electron/Chromium.

**Closed by TylerLeonhardt** 2023-10-30 17:33 UTC

**Comment by TylerLeonhardt** [comment] 2023-10-30 19:26
You're right. This is more of a duplicate of https://github.com/microsoft/vscode/issues/185212 though I would imagine that both would be solved with a similar fix.

I do want to push more for the fix for that issue.
