### ISSUE TITLE
Typescript: module resolution for directories not using index.ts

### ISSUE THREAD

**Issue by kyleferguson** [Microsoft/vscode#63440] opened 2018-11-19 15:54 UTC
Using a module alias (with paths setup in tsconfig) doesn't work when importing a directory that has an `index.ts` file. 

![image](https://user-images.githubusercontent.com/4224075/48718161-d4cdd780-ebe8-11e8-87fe-e9824131e396.png)

Adding index works
![image](https://user-images.githubusercontent.com/4224075/48718185-e44d2080-ebe8-11e8-9a1f-875814c29895.png)

Path is setup in tsconfig.json in the root of the project (no other tsconfig files exist)
![image](https://user-images.githubusercontent.com/4224075/48718326-26766200-ebe9-11e8-8adb-937e97228145.png)

- VSCode Version: 1.29.1
- OS Version: OSX Mojave

Steps to Reproduce:

1. Setup custom module paths in tsconfig.json
2. Create a module directory in that path with an index.ts file
3. Import custom module using directory name

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-11-19 19:12
Duplicate of https://github.com/Microsoft/TypeScript/issues/26859

**Closed by mjbvz** 2018-11-19 19:12 UTC
Labels: new release
