### ISSUE TITLE
Cannot enable inline diff view for unstaged changes

### ISSUE THREAD

**Issue by JesseTG** [Microsoft/vscode#65016] opened 2018-12-13 18:54 UTC
Issue Type: <b>Bug</b>

Open a project, specifically a file in a Git repository with unstaged changes.  Enable "Toggle Side By Side View" to enable inline diffs; nothing happens.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 3250)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (1.45GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.7.0
swagger-viewer|Arj|2.1.0
vagrant|bbe|0.5.0
better-toml|bun|0.3.2
ssh|chr|0.0.4
gitignore|cod|0.6.0
jupyter|don|1.1.4
EditorConfig|Edi|0.12.5
vsc-travis-ci-status|fel|1.1.0
forestry|for|0.3.2
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.0
vscode-nginx-conf-hint|han|0.1.0
vscode-git-tags|how|1.3.1
latex-workshop|Jam|5.18.0
nbpreviewer|jit|1.1.0
jq-syntax-highlighting|jq-|0.0.2
vscode-github|Kni|0.30.1
restructuredtext|lex|88.0.0
AWK|lug|0.0.2
openapi-lint|mer|0.3.3
python|ms-|2018.11.0
cpptools|ms-|0.20.1
vscode-docker|Pet|0.4.0
vscode-yaml|red|0.1.0
rust|rus|0.5.3
explorer-excluded-files|sad|1.0.0
gitconfig|sid|2.0.0
shader|sle|1.1.4
cmake|twx|0.0.17

</details>

**Comment by joaomoreno** [comment] 2018-12-14 10:08
Can you share a screen recording?

**Comment by JesseTG** [comment] 2018-12-14 23:38
Here you go.

![2018-12-14 18 37 15 175](https://user-images.githubusercontent.com/1175189/50035318-715c7d00-ffcf-11e8-84ef-7e1c884bd9b0.gif)

**Comment by joaomoreno** [comment] 2018-12-17 08:32
Can you run `Developer: Toggle Developer Tools` and see if an error comes up in the Console when you run that action?

**Comment by devinrhode2** [comment] 2018-12-17 14:32
FTR this is fixed in insiders build

**Comment by JesseTG** [comment] 2018-12-17 14:46
@joaomoreno No errors.  In fact, no relevant output at all.

@devinrhode2 Fixed before I opened this issue, or after?

**Comment by devinrhode2** [comment] 2018-12-17 15:57
In the referenced build number...

**Comment by joaomoreno** [comment] 2018-12-19 08:02
@JesseTG Can you reproduce with `--disable-extensions`?

**Comment by devinrhode2** [comment] 2018-12-19 12:42
When I was creating my duplicate issue, I found it did occur with
extensions disabled.

Just for sanitys sake, the issue was still occuring for me yesterday

**Comment by JesseTG** [comment] 2018-12-19 14:49
@joaomoreno No, but that's because the issue suddenly went away for some reason.  I have not updated VS Code or installed new extensions since originally filing this issue.

**Comment by devinrhode2** [comment] 2018-12-21 01:08
I will say the issue persists for me.  I assume this will be fixed when the next version comes out? (Since it's already fixed/not present in the insiders build)

**Comment by joaomoreno** [comment] 2019-01-03 15:17
@devinrhode2 Can you reproduce on our [insider release](https://code.visualstudio.com/insiders)?

**Comment by joaomoreno** [comment] 2019-01-03 16:11
Oh! Completely missed that :man_facepalming: sorry.

Closing this then, it will be closed next Stable.

**Closed by joaomoreno** 2019-01-03 16:11 UTC
Labels: needs more info

**Comment by devinrhode2** [comment] 2019-02-01 17:24
Ok, I just found out that this issue was being caused by a setting I forgot about long time ago,   `"diffEditor.renderSideBySide": false,`

To anyone finding this on google, open terminal in vscode, then go to problems tab, open vscode settings, view json, and look at problems for duplicate keys, etc

**Comment by JesseTG** [comment] 2019-02-01 17:51
Thank you for not being this guy:

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
