### ISSUE TITLE
Sticky scroll comes in delayed when I switch editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192523] opened 2023-09-08 07:23 UTC
Is it supposed to kick in only later? I find that a bit hectic:

![Image](https://github.com/microsoft/vscode/assets/900690/ca710232-0911-4f30-923f-52748fe5b7ed)

**Comment by aiday-mar** [comment] 2023-09-08 07:47
Hi @bpasero, thanks for filing the bug. There is a performance issue. I have to look at how to improve the speed of sticky lines calculation/rendering.

**Comment by aiday-mar** [comment] 2023-09-08 09:44
When the following PR is merged: https://github.com/microsoft/vscode/pull/191464, this should help improve the performance because it will minimize the rebuild of sticky scroll.

**Comment by aiday-mar** [comment] 2023-12-05 10:30
Hi @bpasero, do you still see this performance issue?

**Comment by Tyriar** [comment] 2024-06-19 14:27
This takes so long because it initializes after first render which is <= 50ms after the text model is attached, which is fine:

https://github.com/microsoft/vscode/blob/3cb3a37238888e5546e1c406d8bb6a99ea955098/src/vs/editor/contrib/stickyScroll/browser/stickyScrollController.ts#L537

But more importantly it depends upon `IFoldingController.getFoldingModel()`:

https://github.com/microsoft/vscode/blob/3cb3a37238888e5546e1c406d8bb6a99ea955098/src/vs/editor/contrib/stickyScroll/browser/stickyScrollController.ts#L537

Which looks like it's debounced here:

https://github.com/microsoft/vscode/blob/3cb3a37238888e5546e1c406d8bb6a99ea955098/src/vs/editor/contrib/folding/browser/folding.ts#L243

The red line here is awaiting for FoldingController:

![image](https://github.com/user-attachments/assets/c7b8ea2b-eaef-49c8-bb3e-1e926979342c)

I don't know enough about folding to determine whether we should fix this or not. It's important that we don't delay the initial editor opening and tokenization.

**Comment by aiday-mar** [comment] 2024-12-13 16:26
duplicate of https://github.com/microsoft/vscode/issues/191973

**Closed by aiday-mar** 2024-12-13 16:26 UTC
Labels: bug, editor-sticky-scroll, performance
