### ISSUE TITLE
Emmet - "remove tag" + "Ctrl+Z" are making an unnecessary closing tag

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39545] opened 2017-12-04 11:45 UTC
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

If there is a div, that written in one line, and we will try to remove it (Ctrl+L) and then return back (Ctrl+Z) - everything is fine.
But if the div (or any other tag) is expanded, returning it back by pressing Ctrl+Z, will return one more unnecessary closing tag.

![emmet - remove tag](https://user-images.githubusercontent.com/24613274/33551067-d7870f0e-d8f8-11e7-9a04-f322eb513d05.gif)

**Comment by huguinho27** [comment] 2017-12-04 12:05
I'll try to fix this, if possible. May I?

**Comment by ramya-rao-a** [comment] 2017-12-04 19:48
This is happening due to the auto-close feature kicking in.

@aeschli Repro steps are
- Have this in an html file
```
<div>

</div>
```
- Keep the cursor in between the opening and closing tag
- Run the command `Emmet: Remove Tag`. This uses the [TextEditorEdit](https://github.com/Microsoft/vscode/blob/5ecc577420b7ad266966861803e160d2ea33a889/src/vs/vscode.d.ts#L1132) to remove the tag.
- Ctrl+Z

Now the auto close feature kicks in adds the extra `</div>`

**Comment by aeschli** [comment] 2017-12-05 07:06
dup of #34484

**Closed by aeschli** 2017-12-05 07:06 UTC
Labels: html

**Comment by JacksonKearl** [comment] 2018-06-28 18:02
We can address this incarnation of the issue by just testing if the edit also inserted the closing tag, but that doesn't help with the root cause. Not sure if the "remove tag/undo" operation happens enough for this to be worthwhile
