### ISSUE TITLE
Wrong SCSS syntax coloring 

### ISSUE THREAD

**Issue by dariuspranskus** [Microsoft/vscode#39361] opened 2017-11-30 09:04 UTC
Hello

I have discovered a wrong SCSS syntax coloring. Please see the picture below. & sign should be blue in &:visited (1) and color property should be cyan (2).

![image](https://user-images.githubusercontent.com/15170614/33422276-4670e798-d609-11e7-8cb1-f4c1e10b860f.png)

- VSCode Version: 1.18.1
- OS Version: Windows 10 Home (OS Build 15063.726)

Steps to Reproduce:

1. Create a new .scss file
2. Enter a text like 

```
.link-class {
    &:link,
    &:visited {
        color: red;
        font-size: 2rem;
    }
}

```
Reproduces without extensions: **Yes**

Thanks

**Comment by aeschli** [comment] 2017-12-04 13:17
duplicate of #38001, fixed in 1.19

**Closed by aeschli** 2017-12-04 13:17 UTC
Labels: css-less-sass
