### ISSUE TITLE
NotSupportedError upon opening github.dev for the first time

### ISSUE THREAD

**Issue by nikilp** [microsoft/vscode#165600] opened 2022-11-05 13:48 UTC
I'm opening github.dev for the first time. I am logged in on github.com. As the page loads I receive error notification in the lower right corner:

```
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://199jkee4m8n804to12udkvh49hpmc1pkc6o6scsmqlpti5oka2br.vscode-cdn.net/stable/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://199jkee4m8n804to12udkvh49hpmc1pkc6o6scsmqlpti5oka2br.vscode-cdn.net/stable/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): The user denied permission to use Service Worker..
```

ADD ISSUE DESCRIPTION HERE

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by lszomoru** [comment] 2022-11-16 14:29
@nikilp, are you still able to reproduce this issue or was it a transient error condition? Thanks!

**Comment by MasterInQuestion** [comment] 2022-11-18 22:19
Pretty much identical error message but occurred upon previewing Markdown.

    Probably related: [https://github<i>.</i>com/microsoft/vscode/issues/165361](https://github.com/microsoft/vscode/issues/165361)

**Comment by nikilp** [comment] 2022-11-20 16:15
It's is still occurring:
![here](https://user-images.githubusercontent.com/11346664/202913085-8c68a924-1361-417d-a62f-7dc1d90fd8eb.gif)

**Comment by lszomoru** [comment] 2022-11-22 14:10
@nikilp, does this occur only the first time when you open https://gitHub.dev, or every time you open https://github.dev?

**Comment by nikilp** [comment] 2022-11-22 14:12
Every time. I cannot get past this.

**Comment by mjbvz** [comment] 2022-12-05 19:16
Closing as this seems like a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1320796 / #142813

Unfortunately I don't think we can work around this on the VS Code side

**Closed by mjbvz** 2022-12-05 19:16 UTC
Labels: info-needed

**Comment by MasterInQuestion** [comment] 2022-12-09 20:58
Reproducible in Chromium.
