### ISSUE TITLE
Editor not repainted when resizing the window while a deletion confirmation dialog is opened

### ISSUE THREAD

**Issue by greengiraffe** [Microsoft/vscode#9262] opened 2016-07-14 08:53 UTC
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.3

**Description:**

When a confirmation dialog is open and the editor window is resized, the window doesn't repaint itself to fit the new window dimensions. 

**Steps to Reproduce:**
1. Open a file that is visible in the explorer. 
2. Delete the file (a confirmation dialog opens).
3. Resize the editor window.

**Screencast:**

![vsc-bug-report-screencast](https://cloud.githubusercontent.com/assets/9062294/16833752/e75f0fa4-49b0-11e6-80c1-93faf5cecbdf.gif)

**Comment by bpasero** [comment] 2016-07-14 11:43
A problem that should probably be reported to Electron (same happens in Atom).

**Comment by bpasero** [comment] 2017-12-03 15:28
Cannot reproduce anymore.

**Comment by mjbvz** [comment] 2017-12-05 22:45
@bpasero I still see this in both the current insiders and a build from master:

![screen shot 2017-12-05 at 2 44 44 pm](https://user-images.githubusercontent.com/12821956/33634950-e0939de2-d9ca-11e7-911c-224f8500ed3a.png)

**Comment by bpasero** [comment] 2017-12-06 06:32
@mjbvz ah yeah, that is a blocking dialog from the SCM viewlet. It no longer happens for the async delete dialog from the file explorer. 

Related to https://github.com/Microsoft/vscode/issues/39536

**Comment by bpasero** [comment] 2017-12-14 11:17
fixed via https://github.com/Microsoft/vscode/pull/40211

**Closed by bpasero** 2017-12-14 11:17 UTC
Labels: bug, workbench-layout
