### ISSUE TITLE
Electron 9: cannot do performance profile

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101350] opened 2020-06-30 08:42 UTC
Steps to Reproduce:

1. run out of sources on Linux with E9
2. start performance profile
3. reload window
4. stop performance profile

```
Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
[115.728] ng_service_impl.cc:1188 Timeout while waiting for ACKs for tracing session 1
```

**Comment by bpasero** [comment] 2020-08-26 07:00
I just tried this again and now it seems to actually crash following my steps:


```
Thread 0 (crashed)
 0  libsystem_platform.dylib!_platform_memmove$VARIANT$Haswell + 0x4d
    rax = 0x00007fab8e8b4ef0   rdx = 0x0000000000000011
    rcx = 0x0000000000000000   rbx = 0x00007fab8e8c6230
    rsi = 0x0000000000000288   rdi = 0x00007fab8e8b4ef0
    rbp = 0x00007ffee6a5ab80   rsp = 0x00007ffee6a5ab80
     r8 = 0x000000000000b0e8    r9 = 0x000000000000b0e9
    r10 = 0x00000000fffffeff   r11 = 0x00007fab8e8b4c68
    r12 = 0x000000000000000b   r13 = 0x0000000000000012
    r14 = 0x00007fab8e8b4ef0   r15 = 0x0000000000000011
    rip = 0x00007fff6976494d
    Found by: given as instruction pointer in context
 1  Electron Framework + 0x1292416
    rbp = 0x00007ffee6a5ac20   rsp = 0x00007ffee6a5ab90
    rip = 0x000000010a479416
    Found by: previous frame's frame pointer
 2  Electron Framework + 0xf4a1a3
    rbp = 0x00007ffee6a5ac80   rsp = 0x00007ffee6a5ac30
    rip = 0x000000010a1311a3
    Found by: previous frame's frame pointer
 3  Electron Framework + 0x1410c6f
    rbp = 0x00007ffee6a5ad10   rsp = 0x00007ffee6a5ac90
    rip = 0x000000010a5f7c6f
    Found by: previous frame's frame pointer
 4  Electron Framework + 0x142601c
    rbp = 0x00007ffee6a5ad60   rsp = 0x00007ffee6a5ad20
    rip = 0x000000010a60d01c
    Found by: previous frame's frame pointer
 5  Electron Framework + 0xf58355
    rbp = 0x00007ffee6a5adf0   rsp = 0x00007ffee6a5ad70
    rip = 0x000000010a13f355
    Found by: previous frame's frame pointer
 6  Electron Framework + 0x12ef564
    rbp = 0x00007ffee6a5ae60   rsp = 0x00007ffee6a5ae00
    rip = 0x000000010a4d6564
    Found by: previous frame's frame pointer
 7  Electron Framework + 0x18a5d38
    rbp = 0x00007ffee6a5ae88   rsp = 0x00007ffee6a5ae70
    rip = 0x000000010aa8cd38
    Found by: previous frame's frame pointer
 8  Electron Framework + 0x1839b39
    rbp = 0x00007ffee6a5af18   rsp = 0x00007ffee6a5ae98
    rip = 0x000000010aa20b39
    Found by: previous frame's frame pointer
 9  Electron Framework + 0x1839ab5
    rbp = 0x00007ffee6a5af60   rsp = 0x00007ffee6a5af28
    rip = 0x000000010aa20ab5
    Found by: previous frame's frame pointer
10  Electron Framework + 0x18334ff
    rbp = 0x00007ffee6a5afa0   rsp = 0x00007ffee6a5af70
    rip = 0x000000010aa1a4ff
    Found by: previous frame's frame pointer
11  Electron Framework + 0x1839ab5
    rbp = 0x00007ffee6a5aff0   rsp = 0x00007ffee6a5afb0
    rip = 0x000000010aa20ab5
    Found by: previous frame's frame pointer
12  Electron Framework + 0x18334ff
    rbp = 0x00007ffee6a5b028   rsp = 0x00007ffee6a5b000
    rip = 0x000000010aa1a4ff
    Found by: previous frame's frame pointer
13  Electron Framework + 0x18375fa
    rbp = 0x00007ffee6a5b058   rsp = 0x00007ffee6a5b038
    rip = 0x000000010aa1e5fa
    Found by: previous frame's frame pointer
14  Electron Framework + 0x18373d8
    rbp = 0x00007ffee6a5b0c0   rsp = 0x00007ffee6a5b068
    rip = 0x000000010aa1e3d8
    Found by: previous frame's frame pointer
15  Electron Framework + 0xf308fc
    rbp = 0x00007ffee6a5b210   rsp = 0x00007ffee6a5b0d0
    rip = 0x000000010a1178fc
    Found by: previous frame's frame pointer
16  Electron Framework + 0xf2fd46
    rbp = 0x00007ffee6a5b290   rsp = 0x00007ffee6a5b220
    rip = 0x000000010a116d46
    Found by: previous frame's frame pointer
17  Electron Framework + 0xe21108
    rbp = 0x00007ffee6a5b3b0   rsp = 0x00007ffee6a5b2a0
    rip = 0x000000010a008108
    Found by: previous frame's frame pointer
18  Electron Framework + 0x40d1c06
    rbp = 0x00007ffee6a5b4c0   rsp = 0x00007ffee6a5b3c0
    rip = 0x000000010d2b8c06
    Found by: previous frame's frame pointer
19  Electron Framework + 0x416375a
    rbp = 0x00007ffee6a5b560   rsp = 0x00007ffee6a5b4d0
    rip = 0x000000010d34a75a
    Found by: previous frame's frame pointer
20  Electron Framework + 0x416386e
    rbp = 0x00007ffee6a5b5d0   rsp = 0x00007ffee6a5b570
    rip = 0x000000010d34a86e
    Found by: previous frame's frame pointer
21  Electron Framework + 0x48b16e3
    rbp = 0x00007ffee6a5b6e0   rsp = 0x00007ffee6a5b5e0
    rip = 0x000000010da986e3
    Found by: previous frame's frame pointer
22  Electron Framework + 0x48b0fd1
    rbp = 0x00007ffee6a5b720   rsp = 0x00007ffee6a5b6f0
    rip = 0x000000010da97fd1
    Found by: previous frame's frame pointer
23  Electron Framework + 0x48b2aa8
    rbp = 0x00007ffee6a5b750   rsp = 0x00007ffee6a5b730
    rip = 0x000000010da99aa8
    Found by: previous frame's frame pointer
24  Electron Framework + 0x1a033e4
    rbp = 0x00007ffee6a5b770   rsp = 0x00007ffee6a5b760
    rip = 0x000000010abea3e4
    Found by: previous frame's frame pointer
25  Electron Framework + 0x1a062e6
    rbp = 0x00007ffee6a5b790   rsp = 0x00007ffee6a5b780
    rip = 0x000000010abed2e6
    Found by: previous frame's frame pointer
26  Electron Framework + 0x19e1ace
    rbp = 0x00007ffee6a5b810   rsp = 0x00007ffee6a5b7a0
    rip = 0x000000010abc8ace
    Found by: previous frame's frame pointer
27  Electron Framework + 0x19e2060
    rbp = 0x00007ffee6a5b850   rsp = 0x00007ffee6a5b820
    rip = 0x000000010abc9060
    Found by: previous frame's frame pointer
28  Electron Framework + 0x285b61f
    rbp = 0x00007ffee6a5b900   rsp = 0x00007ffee6a5b860
    rip = 0x000000010ba4261f
    Found by: previous frame's frame pointer
29  Electron Framework + 0x286b7fa
    rbp = 0x00007ffee6a5b9d0   rsp = 0x00007ffee6a5b910
    rip = 0x000000010ba527fa
    Found by: previous frame's frame pointer
30  Electron Framework + 0x286b589
    rbp = 0x00007ffee6a5ba20   rsp = 0x00007ffee6a5b9e0
    rip = 0x000000010ba52589
    Found by: previous frame's frame pointer
31  Electron Framework + 0x28bc141
    rbp = 0x00007ffee6a5ba40   rsp = 0x00007ffee6a5ba30
    rip = 0x000000010baa3141
    Found by: previous frame's frame pointer
32  Electron Framework + 0x28b78da
    rbp = 0x00007ffee6a5ba50   rsp = 0x00007ffee6a5ba50
    rip = 0x000000010ba9e8da
    Found by: previous frame's frame pointer
33  Electron Framework + 0x28bba0f
    rbp = 0x00007ffee6a5ba90   rsp = 0x00007ffee6a5ba60
    rip = 0x000000010baa2a0f
    Found by: previous frame's frame pointer
34  CoreFoundation!__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 0x11
    rbp = 0x00007ffee6a5baa0   rsp = 0x00007ffee6a5baa0
    rip = 0x00007fff2f69cd52
    Found by: previous frame's frame pointer
35  CoreFoundation!__CFRunLoopDoSource0 + 0x67
    rbp = 0x00007ffee6a5bad0   rsp = 0x00007ffee6a5bab0
    rip = 0x00007fff2f69ccf1
    Found by: previous frame's frame pointer
36  CoreFoundation!__CFRunLoopDoSources0 + 0xd1
    rbp = 0x00007ffee6a5bb40   rsp = 0x00007ffee6a5bae0
    rip = 0x00007fff2f69cb0b
    Found by: previous frame's frame pointer
37  CoreFoundation!__CFRunLoopRun + 0x39f
    rbp = 0x00007ffee6a5c850   rsp = 0x00007ffee6a5bb50
    rip = 0x00007fff2f69b83a
    Found by: previous frame's frame pointer
38  CoreFoundation!CFRunLoopRunSpecific + 0x1ce
    rbp = 0x00007ffee6a5c8e0   rsp = 0x00007ffee6a5c860
    rip = 0x00007fff2f69ae3e
    Found by: previous frame's frame pointer
39  Foundation!-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 0xd4
    rbp = 0x00007ffee6a5c920   rsp = 0x00007ffee6a5c8f0
    rip = 0x00007fff31d361c8
    Found by: previous frame's frame pointer
40  Electron Framework + 0x28bc661
    rbp = 0x00007ffee6a5c960   rsp = 0x00007ffee6a5c930
    rip = 0x000000010baa3661
    Found by: previous frame's frame pointer
41  Electron Framework + 0x28bb3c2
    rbp = 0x00007ffee6a5c9a0   rsp = 0x00007ffee6a5c970
    rip = 0x000000010baa23c2
    Found by: previous frame's frame pointer
42  Electron Framework + 0x286bd83
    rbp = 0x00007ffee6a5c9d0   rsp = 0x00007ffee6a5c9b0
    rip = 0x000000010ba52d83
    Found by: previous frame's frame pointer
43  Electron Framework + 0x2843193
    rbp = 0x00007ffee6a5ca60   rsp = 0x00007ffee6a5c9e0
    rip = 0x000000010ba2a193
    Found by: previous frame's frame pointer
44  Electron Framework + 0x5dbf179
    rbp = 0x00007ffee6a5cb20   rsp = 0x00007ffee6a5ca70
    rip = 0x000000010efa6179
    Found by: previous frame's frame pointer
45  Electron Framework + 0x1ab3289
    rbp = 0x00007ffee6a5cb90   rsp = 0x00007ffee6a5cb30
    rip = 0x000000010ac9a289
    Found by: previous frame's frame pointer
46  Electron Framework + 0x4038308
    rbp = 0x00007ffee6a5cee0   rsp = 0x00007ffee6a5cba0
    rip = 0x000000010d21f308
    Found by: previous frame's frame pointer
47  Electron Framework + 0xd33564
    rbp = 0x00007ffee6a5cf70   rsp = 0x00007ffee6a5cef0
    rip = 0x0000000109f1a564
    Found by: previous frame's frame pointer
48  Electron Framework + 0x2bd4
    rbp = 0x00007ffee6a5d000   rsp = 0x00007ffee6a5cf80
    rip = 0x00000001091e9bd4
    Found by: previous frame's frame pointer
49  Code - OSS Helper (Renderer) + 0x18a5
    rbp = 0x00007ffee6a5d0d0   rsp = 0x00007ffee6a5d010
    rip = 0x00000001091a38a5
    Found by: previous frame's frame pointer
50  libdyld.dylib!start + 0x1
    rbp = 0x00007ffee6a5d0e8   rsp = 0x00007ffee6a5d0e0
    rip = 0x00007fff6956ecc9
    Found by: previous frame's frame pointer
51  libdyld.dylib!start + 0x1
    rbp = 0x00007ffee6a5d0e8   rsp = 0x00007ffee6a5d0e8
    rip = 0x00007fff6956ecc9
    Found by: stack scanning
```

[fc9f478c-4491-4ce3-a857-67c10e0a0062.dmp.zip](https://github.com/microsoft/vscode/files/5128114/fc9f478c-4491-4ce3-a857-67c10e0a0062.dmp.zip)

**Comment by deepak1556** [comment] 2020-08-26 07:57
Can repro, symbolicated trace

```
Symbolicating...
Operating system: Mac OS X
                  10.15.6 19G73
CPU: amd64
     family 6 model 158 stepping 10
     12 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x289
Process uptime: 3 seconds

Thread 0 (crashed)
 0  libsystem_platform.dylib!_platform_memmove$VARIANT$Haswell + 0x4d
    rax = 0x00007fd580a60750   rdx = 0x0000000000000011
    rcx = 0x0000000000000000   rbx = 0x00007fd580a651f0
    rsi = 0x0000000000000288   rdi = 0x00007fd580a60750
    rbp = 0x00007ffeecb6f840   rsp = 0x00007ffeecb6f840
     r8 = 0x0000000000005c6e    r9 = 0x0000000000005c6f
    r10 = 0x00000000ffffbfff   r11 = 0x00007fd580a604c8
    r12 = 0x000000000000000b   r13 = 0x0000000000000012
    r14 = 0x00007fd580a60750   r15 = 0x0000000000000011
    rip = 0x00007fff6c77f94d
    Found by: given as instruction pointer in context
 1  Electron Framework!v8::internal::ProfilerListener::CodeCreateEvent(v8::internal::CodeEventListener::LogEventsAndTags, v8::internal::wasm::WasmCode const*, v8::internal::Vector<char const>) [algorithm : 1717 + 0xf]
    rbp = 0x00007ffeecb6f8e0   rsp = 0x00007ffeecb6f850
    rip = 0x0000000105379416
    Found by: previous frame's frame pointer
 2  Electron Framework!v8::internal::CodeEventDispatcher::CodeCreateEvent(v8::internal::CodeEventListener::LogEventsAndTags, v8::internal::wasm::WasmCode const*, v8::internal::Vector<char const>) [functional : 2203 + 0x5]
    rbp = 0x00007ffeecb6f940   rsp = 0x00007ffeecb6f8f0
    rip = 0x00000001050311a3
    Found by: previous frame's frame pointer
 3  Electron Framework!v8::internal::wasm::WasmCode::LogCode(v8::internal::Isolate*) const [wasm-code-manager.cc : 237 + 0x14]
    rbp = 0x00007ffeecb6f9d0   rsp = 0x00007ffeecb6f950
    rip = 0x00000001054f7c6f
    Found by: previous frame's frame pointer
 4  Electron Framework!v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(v8::internal::Isolate*) [wasm-engine.cc : 849 + 0x5]
    rbp = 0x00007ffeecb6fa20   rsp = 0x00007ffeecb6f9e0
    rip = 0x000000010550d01c
    Found by: previous frame's frame pointer
 5  Electron Framework!v8::internal::StackGuard::HandleInterrupts() [stack-guard.cc : 301 + 0x5]
    rbp = 0x00007ffeecb6fab0   rsp = 0x00007ffeecb6fa30
    rip = 0x000000010503f355
    Found by: previous frame's frame pointer
 6  Electron Framework!v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [runtime-internal.cc : 293 + 0x8]
    rbp = 0x00007ffeecb6fb20   rsp = 0x00007ffeecb6fac0
    rip = 0x00000001053d6564
    Found by: previous frame's frame pointer
 7  Electron Framework!Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit + 0x38
    rbp = 0x00007ffeecb6fb48   rsp = 0x00007ffeecb6fb30
    rip = 0x000000010598cd38
    Found by: previous frame's frame pointer
 8  Electron Framework!Builtins_InterpreterEntryTrampoline + 0x159
    rbp = 0x00007ffeecb6fba0   rsp = 0x00007ffeecb6fb58
    rip = 0x0000000105920b39
    Found by: previous frame's frame pointer
 9  Electron Framework!Builtins_JSEntryTrampoline + 0x5a
    rbp = 0x00007ffeecb6fbd8   rsp = 0x00007ffeecb6fbb0
    rip = 0x000000010591e5fa
    Found by: previous frame's frame pointer
10  Electron Framework!Builtins_JSEntry + 0x78
    rbp = 0x00007ffeecb6fc40   rsp = 0x00007ffeecb6fbe8
    rip = 0x000000010591e3d8
    Found by: previous frame's frame pointer
11  Electron Framework!v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [simulator.h : 142 + 0x8]
    rbp = 0x00007ffeecb6fd90   rsp = 0x00007ffeecb6fc50
    rip = 0x00000001050178fc
    Found by: previous frame's frame pointer
12  Electron Framework!v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [execution.cc : 461 + 0x8]
    rbp = 0x00007ffeecb6fe10   rsp = 0x00007ffeecb6fda0
    rip = 0x0000000105016d46
    Found by: previous frame's frame pointer
13  Electron Framework!v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [api.cc : 4995 + 0x15]
    rbp = 0x00007ffeecb6ff30   rsp = 0x00007ffeecb6fe20
    rip = 0x0000000104f08108
    Found by: previous frame's frame pointer
14  Electron Framework!node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [callback.cc : 156 + 0xe]
    rbp = 0x00007ffeecb6fff0   rsp = 0x00007ffeecb6ff40
    rip = 0x000000010a04cd4c
    Found by: previous frame's frame pointer
15  Electron Framework!node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [async_wrap.cc : 739 + 0x11]
    rbp = 0x00007ffeecb70040   rsp = 0x00007ffeecb70000
    rip = 0x000000010a05b381
    Found by: previous frame's frame pointer
16  Electron Framework!node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [async_wrap-inl.h : 95 + 0xe]
    rbp = 0x00007ffeecb70090   rsp = 0x00007ffeecb70050
    rip = 0x000000010a0d3e48
    Found by: previous frame's frame pointer
17  Electron Framework!node::fs::AfterInteger(uv_fs_s*) [node_file.cc : 538 + 0xd]
    rbp = 0x00007ffeecb700f0   rsp = 0x00007ffeecb700a0
    rip = 0x000000010a0d4418
    Found by: previous frame's frame pointer
18  Electron Framework!uv__work_done [threadpool.c : 313 + 0x3]
    rbp = 0x00007ffeecb70130   rsp = 0x00007ffeecb70100
    rip = 0x000000010a1bdfe8
    Found by: previous frame's frame pointer
19  Electron Framework!uv__async_io [async.c : 147 + 0x2]
    rbp = 0x00007ffeecb70580   rsp = 0x00007ffeecb70140
    rip = 0x000000010a1c1f84
    Found by: previous frame's frame pointer
20  Electron Framework!uv__io_poll [kqueue.c : 343 + 0x8]
    rbp = 0x00007ffeecb78640   rsp = 0x00007ffeecb70590
    rip = 0x000000010a1d3250
    Found by: previous frame's frame pointer
21  Electron Framework!uv_run [core.c : 375 + 0x8]
    rbp = 0x00007ffeecb786b0   rsp = 0x00007ffeecb78650
    rip = 0x000000010a1c2431
    Found by: previous frame's frame pointer
22  Electron Framework!electron::NodeBindings::UvRunOnce() [node_bindings.cc : 424 + 0xa]
    rbp = 0x00007ffeecb78740   rsp = 0x00007ffeecb786c0
    rip = 0x000000010425521e
    Found by: previous frame's frame pointer
23  Electron Framework!base::TaskAnnotator::RunTask(char const*, base::PendingTask*) [callback.h : 98 + 0x3]
    rbp = 0x00007ffeecb787f0   rsp = 0x00007ffeecb78750
    rip = 0x000000010694261f
    Found by: previous frame's frame pointer
24  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) [thread_controller_with_message_pump_impl.cc : 324 + 0xf]
    rbp = 0x00007ffeecb788c0   rsp = 0x00007ffeecb78800
    rip = 0x00000001069527fa
    Found by: previous frame's frame pointer
25  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [thread_controller_with_message_pump_impl.cc : 248 + 0xb]
    rbp = 0x00007ffeecb78910   rsp = 0x00007ffeecb788d0
    rip = 0x0000000106952589
    Found by: previous frame's frame pointer
26  Electron Framework!invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) [message_pump_mac.mm : 499 + 0x6]
    rbp = 0x00007ffeecb78930   rsp = 0x00007ffeecb78920
    rip = 0x00000001069a3141
    Found by: previous frame's frame pointer
27  Electron Framework!base::mac::CallWithEHFrame(void () block_pointer) + 0xa
    rbp = 0x00007ffeecb78940   rsp = 0x00007ffeecb78940
    rip = 0x000000010699e8da
    Found by: previous frame's frame pointer
28  Electron Framework!base::MessagePumpCFRunLoopBase::RunWorkSource(void*) [message_pump_mac.mm : 475 + 0x5]
    rbp = 0x00007ffeecb78980   rsp = 0x00007ffeecb78950
    rip = 0x00000001069a2a0f
    Found by: previous frame's frame pointer
29  CoreFoundation!__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 0x11
    rbp = 0x00007ffeecb78990   rsp = 0x00007ffeecb78990
    rip = 0x00007fff3251ed52
    Found by: previous frame's frame pointer
30  CoreFoundation!__CFRunLoopDoSource0 + 0x67
    rbp = 0x00007ffeecb789c0   rsp = 0x00007ffeecb789a0
    rip = 0x00007fff3251ecf1
    Found by: previous frame's frame pointer
31  CoreFoundation!__CFRunLoopDoSources0 + 0xd1
    rbp = 0x00007ffeecb78a30   rsp = 0x00007ffeecb789d0
    rip = 0x00007fff3251eb0b
    Found by: previous frame's frame pointer
32  CoreFoundation!__CFRunLoopRun + 0x39f
    rbp = 0x00007ffeecb79740   rsp = 0x00007ffeecb78a40
    rip = 0x00007fff3251d83a
    Found by: previous frame's frame pointer
33  CoreFoundation!CFRunLoopRunSpecific + 0x1ce
    rbp = 0x00007ffeecb797d0   rsp = 0x00007ffeecb79750
    rip = 0x00007fff3251ce3e
    Found by: previous frame's frame pointer
34  Foundation!-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 0xd4
    rbp = 0x00007ffeecb79810   rsp = 0x00007ffeecb797e0
    rip = 0x00007fff34bb81c8
    Found by: previous frame's frame pointer
35  Electron Framework!base::MessagePumpNSRunLoop::DoRun(base::MessagePump::Delegate*) [message_pump_mac.mm : 745 + 0x10]
    rbp = 0x00007ffeecb79850   rsp = 0x00007ffeecb79820
    rip = 0x00000001069a3661
    Found by: previous frame's frame pointer
36  Electron Framework!base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) [message_pump_mac.mm : 190 + 0xc]
    rbp = 0x00007ffeecb79890   rsp = 0x00007ffeecb79860
    rip = 0x00000001069a23c2
    Found by: previous frame's frame pointer
37  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [thread_controller_with_message_pump_impl.cc : 429 + 0x6]
    rbp = 0x00007ffeecb798c0   rsp = 0x00007ffeecb798a0
    rip = 0x0000000106952d83
    Found by: previous frame's frame pointer
38  Electron Framework!base::RunLoop::Run() [run_loop.cc : 124 + 0x13]
    rbp = 0x00007ffeecb79950   rsp = 0x00007ffeecb798d0
    rip = 0x000000010692a193
    Found by: previous frame's frame pointer
39  Electron Framework!content::RendererMain(content::MainFunctionParams const&) [renderer_main.cc : 226 + 0x5]
    rbp = 0x00007ffeecb79a10   rsp = 0x00007ffeecb79960
    rip = 0x0000000109ea6179
    Found by: previous frame's frame pointer
40  Electron Framework!content::ContentMainRunnerImpl::Run(bool) [content_main_runner_impl.cc : 882 + 0x5]
    rbp = 0x00007ffeecb79a80   rsp = 0x00007ffeecb79a20
    rip = 0x0000000105b9a289
    Found by: previous frame's frame pointer
41  Electron Framework!service_manager::Main(service_manager::MainParams const&) [main.cc : 454 + 0x9]
    rbp = 0x00007ffeecb79dd0   rsp = 0x00007ffeecb79a90
    rip = 0x000000010811f308
    Found by: previous frame's frame pointer
42  Electron Framework!content::ContentMain(content::ContentMainParams const&) [content_main.cc : 19 + 0x8]
    rbp = 0x00007ffeecb79e60   rsp = 0x00007ffeecb79de0
    rip = 0x0000000104e1a564
    Found by: previous frame's frame pointer
43  Electron Framework!ElectronMain [electron_library_main.mm : 23 + 0x5]
    rbp = 0x00007ffeecb79ef0   rsp = 0x00007ffeecb79e70
    rip = 0x00000001040e9bd4
    Found by: previous frame's frame pointer
44  Code - OSS Helper (Renderer)!main [electron_main.cc : 274 + 0xb]
    rbp = 0x00007ffeecb79fc0   rsp = 0x00007ffeecb79f00
    rip = 0x00000001030868a5
    Found by: previous frame's frame pointer
45  libdyld.dylib!start + 0x1
    rbp = 0x00007ffeecb79fd0   rsp = 0x00007ffeecb79fd0
    rip = 0x00007fff6c589cc9
    Found by: previous frame's frame pointer
```

**Comment by deepak1556** [comment] 2020-08-26 08:07
I was not able to repro with base electron, considering the stack contains wasm path, it must require a particular wasm call to trigger this issue. This is definitely a chromium issue, will check if I can get a minimal repro with vscode-oniguruma.

**Comment by deepak1556** [comment] 2020-08-26 08:13
okay most likely fixed by https://chromium-review.googlesource.com/c/v8/v8/+/1948704, checking now.

**Comment by bpasero** [comment] 2020-08-26 08:17
@deepak1556 I followed the instructions at https://github.com/nornagon/electron-minidump/blob/master/README.md to get the symbolified stacktrace and looks like that did not work. I wonder, isn't that readme missing to ask for the Electron version? Maybe that is what I did wrong, by not specifying it?

**Comment by deepak1556** [comment] 2020-08-26 08:22
It is not required to specify the version, the module will download correct symbols based on the `.dmp` file. The problem is that our executables are renamed from `Electron Helper (Renderer)` -> `Code - OSS Helper (Renderer)`, right now I update the downloaded symbols with correct name manually.

**Comment by bpasero** [comment] 2020-08-26 08:54
@deepak1556 Oh ok, thanks. Should this maybe be added to https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports then?

**Comment by deepak1556** [comment] 2020-08-26 09:02
Yup I will update them tomorrow.

**Comment by deepak1556** [comment] 2020-08-26 23:33
Fixed by https://chromium-review.googlesource.com/c/v8/v8/+/2230536

**Comment by deepak1556** [comment] 2020-08-31 08:52
Will be fixed in tomorrow's insider.

**Closed by deepak1556** 2020-08-31 08:52 UTC
Labels: chromium, electron, electron-9-update, upstream, upstream-issue-fixed

**Comment by bpasero** [comment] 2020-09-01 08:35
Seems to work fine today!
