### ISSUE TITLE
It may be better if I could switch extension group

### ISSUE THREAD

**Issue by NanaseRuri** [microsoft/vscode#79652] opened 2019-08-22 15:59 UTC
It may be better if I could switch extension groups by tabs.
As I select different tabs I could get different groups of extension to prevent bugs caused by the conflicts of different extension.

Hope that I express myself clearly.

**Comment by RMacfarlane** [comment] 2019-08-22 22:48
Thanks @NanaseRuri! I think this is a duplicate of https://github.com/microsoft/vscode/issues/20599, please go add a "thumbs up" to that issue

**Closed by RMacfarlane** 2019-08-22 22:48 UTC
