### ISSUE TITLE
save all modifies incorrectly formed .json file

### ISSUE THREAD

**Issue by jeffwlandry** [microsoft/vscode#77869] opened 2019-07-24 11:25 UTC
Issue Type: <b>Bug</b>

It seems that using save all on an imperfectly formed json object, does not save the incorrect element of the object definition.

It may seem correct to not save incorrect elements, however there is no alerting of the user that the file as currently exists will be modified.  First, this caused me much grief and wasted time until I realized what was going on.  Second, this is inconsistent with what I have observed of all other save operations.  I have observed no other instance in which the file as seen by the user is modified on save.

Put a correctly formed json object definition in assets folder.
save all
close file
open file
file is correct
place extra comma (or create any other imperfection) in the definition
save all
close file
open file
incorrect element of file has been deleted from definition

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18941

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
shortcut-menu-bar|jer|1.1.0
debugger-for-chrome|msj|4.11.6

</details>

**Comment by MachineMitch21** [comment] 2019-07-24 14:17
I cannot reproduce this behavior.  I have tried several times using various methods, keyboard shortcuts, the File menu, manually closing the file, etc,  I am using the same version of vscode and am also on Windows 10.

**Comment by jeffwlandry** [comment] 2019-07-24 14:28
Concur.

I knew I should have tried recording this but wimped out because it seemed so consistent.  Was failing as described this morning, but now I can’t recreate it.

I appologize for not providing the recording and thus wasting your time.

Jeff



________________________________

**Comment by rebornix** [comment] 2019-07-24 19:34
Close it for now but we can reopen once we have a reproduce step.

**Closed by rebornix** 2019-07-24 19:34 UTC
