### ISSUE TITLE
Injecting and opening multiply file for unknown reason

### ISSUE THREAD

**Issue by Akumzy** [Microsoft/vscode#52795] opened 2018-06-25 12:30 UTC
I was just coding the next time I noticed is multiply opened tabs
An injection unnecessary code messing up my code base.
It did same thing a day or two ago with over 200 files opened 

![screenshot from 2018-06-25 13-13-03](https://user-images.githubusercontent.com/25849232/41849938-b6714d58-787a-11e8-91b6-ecb51863f639.png)
![screenshot from 2018-06-25 11-49-45](https://user-images.githubusercontent.com/25849232/41849940-b77c24fc-787a-11e8-8020-d027d8638347.png)

Issue Type: <b>Bug</b>

Install a Visual Studio Code insiders
The start coding with it...

VS Code version: Code - Insiders 1.25.0-insider (d5ad3572c4782f34d3ea3a5e4c8e2384222f9467, 2018-06-25T05:18:17.418Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 x 1041)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (0.12GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.4
vsc-material-theme|Equ|2.1.0
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.8
vue|liu|0.1.5
dotenv|mik|1.0.1
vscode-extension-auto-import|mop|1.3.3
Go|ms-|0.6.83
js-atom-grammar|ms-|0.1.14
sublime-keybindings|ms-|4.0.0
vuejs-extension-pack|mub|1.1.2
vetur|oct|0.12.5
LiveServer|rit|5.1.1
vue-vscode-snippets|sdr|1.3.0
autoimport|ste|1.5.3
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment] 2018-06-25 12:51
What did you do at the time this happened? Could it be that you ran a refactoring (like renaming a type) on one of the Vue.js types?

**Comment by octref** [comment] 2018-06-25 13:45
@Akumzy Yeah, please describe what you are doing. Like what keys do you press exactly.
Mostly it's probably you run F12 jump to definition on one of the Vue API, so it goes to the type definition files.

**Comment by Akumzy** [comment] 2018-06-25 18:50
I can't remember pressing F12 button (fn + F12) 
Cause I don't know exact time it happened.

My system was hanging for few seconds the next time I noticed was some random imported modules and multiple files that was opened.

I later noticed it was consuming about 3gb worth of ram space with two different windows opened

**Comment by octref** [comment] 2018-06-25 18:58
> 3gb worth of ram space

That's TypeScript's problem. @mjbvz Any ideas?

F12 jumps to definition, so this is really working as expected.

**Comment by mjbvz** [comment] 2018-06-25 19:01
@Akumzy Can you run `code-insiders --status` to see which process is using the resources

**Comment by Akumzy** [comment] 2018-06-25 20:15
Sorry I've to uninstall it and switch back to normal code.
insiders almost ruined my entire day.
Thank you Guys for the wonderful editor.

**Comment by polco** [comment] 2018-06-26 07:51
this happens to me every time i rename a typescript file. I'm using vscode stable on macos. It opens a bunch of typescript declaration files and update them. i disabled all my extension and the problem is still here.
After disabling the 'auto update import' feature in the settings, renaming files does not trigger this error anymore. So it's definitely a problem with that feature.

**Comment by Nimelrian** [comment] 2018-06-26 08:36
Can confirm, this has been happening to me since yesterday. When I move a ts file with `typescript.updateImportsOnFileMove.enabled = "always"` VS Code suddenly opens up more than 800 files from my node_modules/@types directory and starts changing imports in there (from what I could tell, it was simply normalizing import paths), leading the VS Code window to crash. The only way to fix this is trying to hit the "close all editors" button in the explorer view and telling VS Code not to save the changes. VS Code also spawns hundreds of new processes during the whole ordeal.

**Comment by octref** [comment] 2018-06-26 15:39
@mjbvz FYI, I also encountered the problem after setting `updateImportsOnFileMove`. I can try to get you a repro.

**Comment by Nimelrian** [comment] 2018-06-26 16:34
Maybe this is a regression of Typescript? I can't remember having this issue while still running TS 2.9.1, even when `updateImportsOnFileMove` was set to `"always"`

**Comment by octref** [comment] 2018-06-26 18:54
This is easily reproducible:

- `mkdir repro`
- `yarn add lodash @types/lodash`
- Make sure `"typescript.updateImportsOnFileMove.enabled": "always"` is set
- Write a `index.ts` file like so:

  ```ts
  import * as _ from 'lodash'

  _.add(1, 2)
  ```
- In VS Code, do a rename to `foo.ts`
- Boom, you have all dts files from lodash open.
- This only repros for the first time you run the rename.

**Comment by mjbvz** [comment] 2018-06-26 20:33
Duplicate of #52977

**Closed by mjbvz** 2018-06-26 20:33 UTC
Labels: needs more info
