### ISSUE TITLE
Only generic icon displayed for medium icon size

### ISSUE THREAD

**Issue by dileepd11** [Microsoft/vscode#61658] opened 2018-10-23 23:32 UTC
Issue Type: <b>Bug</b>

As per release notes file type icons should display in Medium or larger icon sizes. File type icons do not display in Medium size on my windows 10 laptop. i see only the generic VS Code icon. i see file type icons only when i get to Large icon sizes which are impractical. Please include separate 
 file icons for medium and lower sizes also as i hate not knowing what kind of file i am looking at.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (6.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.1
tslint|eg2|1.0.40
angular-bootstrap|her|4.0.9
Angular1|joh|0.2.0
mssql|ms-|1.4.0
csharp|ms-|1.16.2
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.9.0
typescript-javascript-grammar|ms-|0.0.46
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.10.2
qub-xml-vscode|qub|1.2.8
vscode-icons|rob|7.27.0
Angular2|UVB|0.4.1

(3 theme extensions excluded)

</details>

**Comment by misolori** [comment] 2018-10-24 14:41
Duplicate of #60200

**Closed by misolori** 2018-10-24 14:41 UTC
