### ISSUE TITLE
Enable SemanticHighlighting if provider uses predefined tokens or maps tokens to superType's or TextMate scopes

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#99499] opened 2020-06-06 01:50 UTC
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Our DocumentSemanticTokensProvider provides some predefined tokens as well as tokens that are derived from existing token types (using "superType").  These tokens are mapped to fallback TextMate scopes.

Even if `semanticTokenColorCustomizations` is not enabled in settings or `semanticHighlighting` is not enabled by the current theme, these tokens should still be colored based on their fallback TextMate scopes.  However, in this scenario, our provider is not used at all.  Tokens that could be colored based on fallback scopes do not get colored as they are never requested.

Fixing this would seem to involve automatically enabling semantic highlighting whenever a provider supports predefined tokens or tokens associated with superType's or fallback TextMate scopes.

**Comment by aeschli** [comment] 2020-06-09 11:14
When neither `semanticTokenColorCustomizations` in the settings nor `semanticHighlighting` in the theme is set, the we don't even make requests to the semantic highlight provider and so there are no semantic tokens to color.
The settings are there for users who want to stick with theming based on TextMate grammars only.
So turning them automatically seems to defeat the purpose of the setting.

**Comment by Colengms** [comment] 2020-06-09 18:31
@aeschli Yes, there are semantic tokens to color, despite not being enabled in either of the ways you indicated.  There are those that are associated with existing types (superType) and TextMate scopes that could be colored.

For example, these are a couple of the fallback TextMate scopes from: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

Semantic Token Selector | Fallback TextMate Scope
-- | --
namespace | entity.name.namespace
type | entity.name.type

This is a token from my contribution point:

      {
        "id": "templateType",
        "superType": "type",
        "description": "A template type."
      },

This should fall back to using the color associated with 'entity.name.type', however does not get an opportunity to be colored at all if you don't request semantic tokens from my provider.

**Comment by Colengms** [comment] 2020-06-09 20:40
A practical example:
For C++, TextMate syntactic/lexical/regex parsing can identify and color a class when followed by the keyword "class":

```
class CLASS
{
};
```

However, in the following case, it's unable to identify and color CLASS:

```
void foo()
{
    CLASS c;
}
```

Our semantic tokens providers would allow CLASS to be colored in the second example, using the color associated with the existing TextMate scope associated with 'class'.  It doesn't make sense for whether this is enabled or not to be tired to whether the theme has opted in to semantic highlighting, as a lot can be colored without special support from the theme.

**Comment by aeschli** [comment] 2020-06-10 09:56
I think I understand what you mean. The problem is that we have semantic highlighting disabled by default for custom themes, while some languages very much depend on semantic highlighting as their TextMate grammar are limited due to the language's syntax.

I originally also hoped we could just enable semantic highlighting for all, but it's very hard to do that in an existing system where users got used to and now expect a certain way coloring, regardless if semantic color is more logical. 
We had a big storm of complaints when we originally turned semantic highlighting on for all.
That's why the default is off now and are working with theme authors to opt in.
I've filed issues against the top theme to do so.
And then I hope there will be use pressure on themes to turn semantic highlighting on.

E.g. in the C++ CLASS case, user hopefully will complain to their favorite theme that it looks bland for C++.

If you want we can discuss this deeper in a call.

**Comment by aeschli** [comment] 2020-06-22 13:46
I like the idea to to use the language specific setting of `"editor.semanticHighlighting.enabled": true` as an the default for `semanticHighlighting` for themes should be.
But themes can still explicitly state `semanticHighlighting: false`

**Comment by Colengms** [comment] 2020-06-23 20:50
@aeschli Yes, that would work for us.

We have code ready to go to switch from our own semantic colorization implementation to use of Semantic Tokens API.  We're just waiting for this, and https://github.com/microsoft/vscode/issues/97177

**Comment by aeschli** [comment] 2020-06-24 07:41
Isn't #97177 is a clean up that should happen after you switched, correct?

**Comment by Colengms** [comment] 2020-06-24 18:55
If we switch first, colorization regresses for our users who use default themes, until #97177 is done and released.  So, we've been waiting for #97177.  Ideally, new tokens could be added first, then old tokens removed in a subsequent VS Code release.  If both changes are made in the same VS Code release, we could quickly post an update and advise people to upgrade if they report an issue.

**Comment by aeschli** [comment] 2020-06-29 18:46
fixed by  #101292

**Closed** 2020-07-28 18:53 UTC
