### ISSUE TITLE
[html] add css intellisense for styles

### ISSUE THREAD

**Issue by areijngoudt** [Microsoft/vscode#1005] opened 2015-12-04 08:37 UTC
The style links are set in my MVC masterpage _Layouts:

<base href="@Url.Content("~")" />
<link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />

VSCode does not 'see' any styles.

Is there a way around this?

**Comment by alexandrudima** [comment] 2015-12-04 14:25
@areijngoudt Did you intend to provide a screenshot? Can you please provide the code snippet that has issues?

**Comment by areijngoudt** [comment] 2015-12-04 16:45
Oh, I don't have access to the code right now. It's something like:

link href='~/Content/bootstrap.css' type=...

Etc

**Comment by aeschli** [comment] 2015-12-07 09:52
Note that we don't have any intellisense for href completion in HTML, so it's doesn't depend on whether the string starts with '~/'

**Comment by areijngoudt** [comment] 2015-12-07 16:27
Hi Martin,

Ok, I understand. But my point is that css intellesense does not work.
So my question is how to solve this.

Kind regards, Ad.

Op 7 dec. 2015 om 10:52 heeft Martin Aeschlimann <notifications@github.com>
het volgende geschreven:

Note that we don't have any intellisense for href completion in HTML, so
it's doesn't depend on whether the string starts with '~/'

—
Reply to this email directly or view it on GitHub
<https://github.com/Microsoft/vscode/issues/1005#issuecomment-162466875>.

**Comment by aeschli** [comment] 2015-12-08 08:28
@areijngoudt Maybe I misunderstood what you meant with 'css intellisense'. Is it about completing the href in a link tag, or is it about completing css rules inside html. Can you give a more compete example code and write what completions you expect? A screenshot would be great.

**Comment by areijngoudt** [comment] 2015-12-08 17:45
Hi Martin,

Sorry, have no screenshot available right now.

What I mean is that when in an .html file I type class='btn btn-' I don't
get auto complete suggestions. And when I press Ctrl+.  a popup appears
saying something like No symbols found.

Best regards, Ad.

Op 8 dec. 2015 om 09:28 heeft Martin Aeschlimann <notifications@github.com>
het volgende geschreven:

@areijngoudt <https://github.com/areijngoudt> Maybe I misunderstood what
you meant with 'css intellisense'. Is it about completing the href in a
link tag, or is it about completing css rules inside html. Can you give a
more compete example code and write what completions you expect? A
screenshot would be great.

—
Reply to this email directly or view it on GitHub
<https://github.com/Microsoft/vscode/issues/1005#issuecomment-162812112>.

**Comment by aeschli** [comment] 2015-12-09 08:50
Thanks @areijngoudt, I updated the issue title

**Comment by Natas0007** [comment] 2016-01-20 23:15
I'm actually having this exact same issue and I'll be glad to supply a screenshot.  This is about the simplest example I can create.  index.html has both a reference to app.css which only contains the teststyle class and the inlineTest class is declared directly in the html file.  Neither of these classes are shown in intellisense when typing in a class attribute of a html element.  The screenshot shows "No suggestions" which is what comes up with Ctrl+Space.  Also, Find All References is greyed on when right clicking on either of the css classes.  I'm sure these 2 issues are related.

![vscode no css intellisense](https://cloud.githubusercontent.com/assets/5757764/12466231/91b09958-bf98-11e5-81e7-437e3e4dfa34.png)

**Comment by sifeij** [comment] 2016-08-11 17:34
I would like to have intellisense when using bootstrap classes. Is there any plan on when this feature can be completed? Thank you.

**Comment by chumtoadafuq** [comment] 2016-10-02 17:03
this feature is a gap in what is otherwise the best code editor out there... any plans to address this anytime soon?

**Comment by aeschli** [comment] 2016-10-11 16:14
duplicate of #2037

**Closed by aeschli** 2016-10-11 16:14 UTC
Labels: feature-request, html
