### ISSUE TITLE
I can not add any new file or folder

### ISSUE THREAD

**Issue by PVerberkmoes** [microsoft/vscode#112808] opened 2020-12-18 12:27 UTC
When i right click on a folder and try to make a new file/folder it closes automatically.
I can not enter the name for the file/folder. 
This is on version 1.52.1

<details>
<summary>System info</summary>

- CPUs | Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)
- GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
- Load (avg) | 2, 2, 2
- Memory (System) | 8.00GB (0.25GB free)
- Process Argv | --crash-reporter-id fff2484a-efc6-4c4b-93ba-405cc165bedc
- Screen Reader | no
- VM | 0%

</details>

<details>
<summary>Vscode extension</summary>
Extension | Author (truncated) | Version

- better-comments | aar | 2.1.0
- silverstripe | adr | 0.0.3
- vscode-css-formatter | aes | 1.0.1
- vscode-intelephense-client | bme | 1.5.4
- cloudformation-yaml-validator | cha | 0.3.15
- vscode-svgviewer | css | 2.0.0
- gitlens | eam | 11.0.6
- vscode-npm-script | eg2 | 0.3.13
- php-debug | fel | 1.13.0
- auto-rename-tag | for | 0.1.5
- rest-client | hum | 0.24.4
- vscode-gutter-preview | kis | 0.26.2
- vscode-phpfmt | kok | 1.0.30
- git-graph | mhu | 1.28.0
- vscode-scss | mrm | 0.9.0
- vetur | oct | 0.31.3
- subtle-brackets | raf | 3.0.0
- vscode-yaml | red | 0.13.0
- format-html-in-php | rif | 1.7.0
- vscode-spotify | shy | 3.2.1
- vscode-scss-formatter | sib | 2.0.5
- json-script-tag | sis | 0.3.2
- php-namespace-snippet | Tra | 0.0.4
- highlight-matching-tag | vin | 0.10.0
- vscode-import-cost | wix | 2.13.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-12-18 12:36
Please use the new extension bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by isidorn** [comment] 2020-12-18 14:06
This is fixed in latest vscode insiders
Dup of https://github.com/microsoft/vscode/issues/111652

**Closed by isidorn** 2020-12-18 14:06 UTC
