### ISSUE TITLE
line display will be truncated if its length exceeds 10000

### ISSUE THREAD

**Issue by FremdSprach** [microsoft/vscode#97331] opened 2020-05-09 07:10 UTC
Issue Type: <b>Bug</b>

Just type more than 10000 charactors, say 10009, in one line in the editor's view, drag the horizonal bar to the right most side, the last 9 charactors cannot be seen.

In other words, is the line view display limited to 10000 characters?

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (124)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
increment-selection|alb|0.2.0
numbered-bookmarks|ale|7.0.0
project-manager|ale|10.12.0
vscode-sequence-diagrams|Ale|0.4.0
auto-add-brackets|ali|0.11.0
html-class-suggestions|And|1.0.7
previewseqdiag-vscode|ari|0.2.4
insertnumbers|Asu|0.9.1
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.5.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.1.1
vscode-clock|Com|0.0.1
vscode-ipaddress|Com|1.0.0
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.35.1
jshint|dba|0.10.21
vscode-quick-select|dba|0.2.8
empty-indent|Dmi|0.2.0
docs-markdown|doc|0.2.68
python-preview|don|0.0.4
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
EditorConfig|Edi|0.14.5
graphviz-preview|EFa|1.4.0
LogFileHighlighter|emi|2.8.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.6.0
vscode-relative-line-numbers|ext|0.0.5
markdown-table-formatter|fcr|2.0.4
file-icons|fil|1.0.24
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
code-runner|for|0.10.0
terminal|for|0.0.10
duplicate|gee|1.0.1
graphviz-markdown-preview|gee|0.0.8
mdmath|goe|2.4.0
beautify|Hoo|1.5.0
vscode-settings-cycler|hoo|1.0.1
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
compareit|in4|0.0.2
path-autocomplete|ion|1.13.6
vscode-essentials|jab|1.5.0
open-file-from-path|jac|1.3.3
fontawesome-autocomplete|Jan|1.0.0
hungry-delete|jas|1.6.0
markdown-extended|jeb|1.0.17
plantuml|jeb|2.13.8
vscode-text-pastry|jkj|1.2.0
vscode-graphviz|joa|0.0.6
svg|joc|1.1.8
vscode-peacock|joh|3.7.0
indentation-level-movement|kai|1.2.1
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.8.1
vscode-gutter-preview|kis|0.26.1
markdown-math|koe|0.1.0
graphql-for-vscode|kum|1.15.3
vscode-simple-icons|Lau|1.13.2
vscode-smart-column-indenter|lmc|0.0.13
MagicPython|mag|1.1.0
markdown-converter|man|3.0.2
string-manipulation|mar|0.3.2
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.7.0
python-path|mge|0.0.11
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.4
theme-monokai-pro-vscode|mon|1.1.15
python|ms-|2020.4.76186
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.1
vscode-mscgen|msc|1.2.0
reload|nat|0.0.6
gremlins|nho|0.15.1
deepdark-material|Nim|3.2.1
incrementor|nms|0.1.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.14
text-power-tools|qcz|1.11.1
subtle-brackets|raf|3.0.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
synthwave-vscode|Rob|0.1.4
partial-diff|ryu|1.4.1
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.3
auto-rename-tag|Sim|0.1.4
indenticator|Sir|0.6.0
shader|sle|1.1.4
swdc-vscode|sof|2.2.5
dot|Ste|0.0.1
vscode-graphql|stp|0.2.3
code-spell-checker|str|1.8.0
tabnine-vscode|Tab|2.8.2
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
graphviz-interactive-preview|tin|0.0.8
vscode-input-sequence|tom|0.2.0
python-extended-snippets|tus|0.0.1
sort-lines|Tyr|1.9.0
vscode-counter|uct|1.3.5
alphabetical-sorter|ue|2.0.1
remove-empty-lines|use|0.0.6
rainbow-tags|vol|0.3.1
vscode-icons|vsc|10.1.1
vim|vsc|1.14.1
JavaScriptSnippets|xab|1.8.0
linecount|yyc|0.1.7
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.4.0

(22 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-05-09 19:05
/duplicate of #7772
See that issue for details

**Closed** 2020-05-09 19:05 UTC
Labels: *duplicate
