### ISSUE TITLE
Can't clone/update private GitHub repos in VS Code 1.62.2

### ISSUE THREAD

**Issue by rgoubet** [microsoft/vscode#137258] opened 2021-11-15 21:14 UTC
Since this week-end, I'm unable to clone or update private repos in VS Code, either from Windows or Linux. My latest attempt in Windows was to completely sign out of GitHub from VS Code, quit and restart, then try to sync again.

I have no problem with my *public* repo. For my private ones, I also tried by removing the local copy and clone again. Still no luck.

```
Validating found git in: C:\Program Files\Git\cmd\git.exe
Validating found git in: C:\Program Files (x86)\Git\cmd\git.exe
Validating found git in: C:\Program Files\Git\cmd\git.exe
Validating found git in: C:\Users\user\AppData\Local\Programs\Git\cmd\git.exe
Validating found git in: C:\Users\user\Programs\git\bin\git.exe
Using git 2.29.2.windows.2 from C:\Users\user\Programs\git\bin\git.exe
> git rev-parse --git-dir
Open repository: c:\Users\user\GitHub\ivql
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --local branch.main.github-pr-owner-number
> git config --get commit.template
> git check-ignore -v -z --stdin
> git rev-parse --git-dir
> git status -z -u
Open repository: c:\Users\user\GitHub\private_repo1
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git config --local branch.main.github-pr-owner-number
> git config --get commit.template
> git config --local branch.main.github-pr-owner-number
> git config --local branch.main.github-pr-owner-number
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/mrgou/private_repo1.git/'
> git clone https://github.com/user/private_repo2.git c:\Users\user\GitHub\private_repo2 --progress
Cloning into 'c:\Users\user\GitHub\private_repo2'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/user/private_repo2.git/'
```

On Linux, I tried all tips I could find on the subject, including signing out from VS Code, or authenticating again with a personal access token with `git remote set-url origin https://<TOKEN>@github.com/<user_name>/<repo_name>.git`. 

If I make the repo public, I can clone it in VS Code, but once I make it private again, sync fails (`authentication failed`).

Finally, downgrading to 1.62.1 solves the issue.

**Comment by gjsjohnmurray** [comment] 2021-11-16 05:56
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 05:57 UTC
Labels: *duplicate
