### ISSUE TITLE
git changes not showing after branch merge

### ISSUE THREAD

**Issue by zeralight** [microsoft/vscode#112717] opened 2020-12-17 09:36 UTC
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a git repository
2. Make a merge branch

The issue is only specific to this git project, I tried to delete it and run git clone, didn't fix it

Does this issue occur when all extensions are disabled?: Yes

git output:

> Looking for git in: C:\Program Files\Git\cmd\git.exe
> Using git 2.29.2.windows.3 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --git-dir
> Open repository: c:\myproject
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> Warning: Failed to watch ref 'c:\myproject\.git\refs\remotes\origin\develop', is most likely packed.
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> Warning: Failed to watch ref 'myproject\.git\refs\remotes\origin\develop', is most likely packed.

Screenshot:
![image](https://user-images.githubusercontent.com/10931192/102469853-899a8300-4053-11eb-8d9a-f7df777a5d57.png)
![image](https://user-images.githubusercontent.com/10931192/102470374-2d842e80-4054-11eb-97b2-57b5e6b63185.png)

**Comment by viraxslot** [comment] 2020-12-17 19:07
Same for me (not always).
MacOs 10.15.7, VsCode Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 day ago)

![image](https://user-images.githubusercontent.com/20737672/102531640-ad8db100-40b3-11eb-93b0-b5bc65298aee.png)

Extentions
```
coenraads.bracket-pair-colorizer-2-0.2.0        ms-azuretools.vscode-docker-1.9.0               spoonscen.es6-mocha-snippets-0.2.2
eamodio.gitlens-11.0.6                          ms-python.python-2020.12.424452561              tomoki1207.pdf-1.1.0
esbenp.prettier-vscode-5.8.0                    ms-toolsai.jupyter-2020.12.414227025            wilson-godoi.wg-getters-and-setters-2.0.0
gruntfuggly.todo-tree-0.0.192                   ms-vscode.powershell-2020.6.0                   yzhang.markdown-all-in-one-3.4.0
mohsen1.prettify-json-0.0.3                     pkief.material-icon-theme-4.4.0                 zainchen.json-2.0.2
```

**Comment by nguyenngochoang** [comment] 2020-12-18 04:36
I have the same issue here. any fixes ??

![image](https://user-images.githubusercontent.com/26711150/102575234-51637500-4125-11eb-9033-976788340a12.png)

**Comment by viraxslot** [comment] 2020-12-18 08:00
> I have the same issue here. any fixes ??
Hey, I downgraded to the previous version temporary, it's 100% fix :)

**Comment by nguyenngochoang** [comment] 2020-12-18 08:12
> > I have the same issue here. any fixes ??
> 
> Hey, I downgraded to the previous version temporary, it's 100% fix :)

you're right, thanks.

**Comment by infinnie** [comment] 2020-12-22 01:58
Same here.

When upgraded to version 1.52 (as well as 1.52.1), I noticed that changes are not shown when performing certain merges, which is really confusing.

**Comment by infinnie** [comment] 2020-12-22 02:24
#112713
#112697

**Comment by infinnie** [comment] 2020-12-22 02:54
![image](https://user-images.githubusercontent.com/8168391/102843348-fb077680-4443-11eb-98d4-0a5f29a45e28.png)
Seems that rename/delete conflicts are mistakenly treated as a file.

**Comment by infinnie** [comment] 2020-12-22 03:44
The temporary solution is turn off the `git.openDiffOnClick` command.

![image](https://user-images.githubusercontent.com/8168391/102846419-e5e21600-444a-11eb-8f0e-47d4f92f97ed.png)

When this option is turned off, corresponding conflicts are correctly displayed.

**Comment by infinnie** [comment] 2020-12-22 03:46
Corresponding Git blame:
https://github.com/microsoft/vscode/blame/0c947cb4ee4a35f04aa6c5117a9727be35b3c828/extensions/git/src/repository.ts#L586

**Comment by eamodio** [comment] 2021-01-05 06:10
Duplicate of #112537 (which will be fixed in tomorrow's insiders)

**Closed by eamodio** 2021-01-05 06:10 UTC
