### ISSUE TITLE
regression in v1.51.0 for multi-line JSDoc 

### ISSUE THREAD

**Issue by k-yle** [microsoft/vscode#110122] opened 2020-11-07 03:28 UTC
Issue Type: <b>Bug</b>

Syntax highlighting for multi line JSDoc comments is broken in v1.51.0, if the `@type` or `@param` is on the same line as the `/**`. The whole comment is rendered in grey, instead of three separate colours for `@type`, `{{ ... }}`, and the rest of the comment

Example:

```ts
/** @type {{
  a: 1;
  b: import("y").SomeType;
}} */
const myObj = {};
```

<table>
<tr>
	<td>
pre v1.51.0
	<td>
<img src="https://user-images.githubusercontent.com/16009897/98431038-eb8fd080-2116-11eb-81ae-184f5531d94f.png">

different colours

<tr>
	<td>
v1.51.0
	<td>
<img src="https://user-images.githubusercontent.com/16009897/98430858-9901e480-2115-11eb-9ac1-39da197c1a15.png">

all grey
</table>

An observation: In the above example, clicking <kbd>F12</kbd> (go to definition) with the cursor over `SomeType` still works, suggesting that it might just be an issue with the colour highlighting?

---

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.20221

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.76GB free)|
|Process Argv|--crash-reporter-id 8fdee845-6edc-437d-ba67-5331318fb644|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
i18n-ally|ant|2.4.3
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
prettier-vscode|esb|5.7.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.4.0
errorlens|use|3.2.3
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-11-07 22:57
The previous highlighting was incorrect. Here's 1.50:

<img width="421" alt="Screen Shot 2020-11-07 at 2 53 29 PM" src="https://user-images.githubusercontent.com/12821956/98452977-2428ad80-2109-11eb-9674-32008d72bfc3.png">

Note how the leading `*` is treated as part of the type.

With 1.51, this case is now handled properly:

<img width="587" alt="Screen Shot 2020-11-07 at 2 55 09 PM" src="https://user-images.githubusercontent.com/12821956/98452988-3c98c800-2109-11eb-8aca-c2ae6d0bacf6.png">

One side effect of the fix that you need to use a leading `*` to get highlighting and that the `@type` cannot appear on the same line as the opening `/*`.

Closing this as by design since the fixed cases are more important than the ones that were regressed

**Closed by mjbvz** 2020-11-07 22:57 UTC
Labels: new release

**Comment by k-yle** [comment] 2020-11-08 01:39
@mjbvz there is a flaw with requiring people to have a `*` at the start of every line in the comment - You can't have blank lines for readability anymore.

e.g.
```js
/**
 * @type {{
 *  a: 1;

 *  b: import("y").SomeType;
 * }}
 */
const myObj = {};
```

In v1.51.0, the blank line causes the lower half of the comment to have no syntax highlighting

![image](https://user-images.githubusercontent.com/16009897/98453483-71b32200-21be-11eb-9a9c-c6ddd7f9c40a.png)


To fix this, you can put in a `*` on the blank line but then TS interprets the `*` as part of the TS code and therefore it's a syntax error

![image](https://user-images.githubusercontent.com/16009897/98453510-c787ca00-21be-11eb-9b5a-02171f9bd906.png)

**Comment by k-yle** [comment] 2020-11-08 01:47
oh, and another issue with requiring people to have a `*` at the start of every line in the comment :

You can't put inline comments above properties within JSDoc anymore:

**This is valid:**

```js
/** @type {{
  // comment
  a: 1;
}} */
const myObj = {};
```

But now we have to put `*`s, so **this is invalid** because TS sees the `*` and raises a syntax error

```js
/** 
 * @type {{
 *   // comment
 *   a: 1;
 * }} 
 */
const myObj = {};
```
