### ISSUE TITLE
Many Interactive Playground features not working correctly, "Initializing JS/TS language features" message spinning continuously at bottom right

### ISSUE THREAD

**Issue by SarmBoJim** [microsoft/vscode#83268] opened 2019-10-25 02:12 UTC
Issue Type: <b>Bug</b>

Installed VS Code, launched it, selected "Interactive playground" from the Welcome tab. A message "Initializing JS/TS language features" appears at the bottom right of the window and stays there, the circle icon beside it continuously spinning.
Items such as the squiggly lines for errors and warnings do not appear and pressing F2 on the Book  symbol causes the message to appear displayed in the image below:
![image](https://user-images.githubusercontent.com/53518185/67537832-90708300-f739-11e9-8561-949a21a0b072.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 955 Processor (4 x 3214)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (4.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment] 2019-10-25 08:31
/duplicate of #81059

Looks like initial issue was fixed in Insiders builds.
Could you check if it works for you there https://code.visualstudio.com/insiders/ ?

**Closed** 2019-10-25 08:31 UTC
Labels: *duplicate

**Comment by SarmBoJim** [comment] 2019-10-25 10:59
Hi Andrii,
Thanks, I'm just learning to use Github and VS code now, didn't realize
it'd been fixed in the Insiders.
I tried the Insiders out as you asked and it has fixed that issue.
However I noticed one item is still not working for me even on the Insiders
I downloaded.
The Errors and Warnings part of the Playground page does not show any
squiggles and pressing F8 with the cursor in that section did not appear to
do anything.
Here is a screenshot just in case you need:
[image: image.png]

I'm not sure if the correct thing to do is to file another bug for this or
if replying to your email is OK.

Thanks,
Rowan

**Comment by IllusionMH** [comment] 2019-10-25 11:06
Looks like Errors and warnings section already tacked in #83025 with two other issues #83024, #83026

**Comment by SarmBoJim** [comment] 2019-10-25 15:09
OK thanks! :)
