### ISSUE TITLE
Middle Click (or Scroll Wheel Click or Shift + Click) should open new window.

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#7203] opened 2016-06-04 01:06 UTC
On Windows (and Ubuntu with Unity Desktop Manager), clicking on a taskbar item with the scroll wheel button, middle mouse button, or shift + click causes a new window to be opened instead of an existing instance. VS Code does not do this.

Repro: 
1. Open VS Code and open a folder.
2. Click the VS Code icon using the scroll wheel click.

Expected: A new VS Code window will open

Actual: The existing VS Code window is shown.

**Comment by Tyriar** [comment] 2016-06-04 08:52
Duplicate of https://github.com/Microsoft/vscode/issues/48

**Closed by Tyriar** 2016-06-04 08:52 UTC
