### ISSUE TITLE
Color of JS Code

### ISSUE THREAD

**Issue by pawz107** [microsoft/vscode#105567] opened 2020-08-28 08:39 UTC
Issue Type: <b>Bug</b>

Hi,
I was in the middle of coding a JS file when I was prompted to update VSC.
However, after the update, I found that the "console" word in the "console.log" and many others are no longer been shown in a different color, but in the default white color.

Just wanted to inform to make sure this is not a bug or a feature that has been turned off by me unknowingly.

I have been using the Oceanic Next Theme with a dimmed bg option

Regards.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.5.0

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-08-28 09:10
duplicate of https://github.com/microsoft/vscode/issues/104616

**Closed by aeschli** 2020-08-28 09:10 UTC
Labels: new release
