### ISSUE TITLE
References view does not open

### ISSUE THREAD

**Issue by AlexanderAmelkin** [Microsoft/vscode#66614] opened 2019-01-16 17:47 UTC
Issue Type: <b>Bug</b>

Menu: `View` -> `Open View...` -> `view References`
Result: Nothing happens.
Expected: References view appears on the sidebar

Mouse: Right-click on a variable
Result: A context menu pops up, but there is no "Find all references" item
Expected: There must be a "Find all references" item in the pop-up menu

My project is C++.  C/C++ extension version 0.20.1 is installed.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|15.59GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.6
vscode-clang|mit|0.2.3
cpptools|ms-|0.20.1
html-preview-vscode|tht|0.2.5

</details>

**Comment by sandy081** [comment] 2019-03-11 15:35
Fixed the first part (`View` -> `Open View...` -> `view References`).

Assigning @jrieken for the second part.

**Comment by jrieken** [comment] 2019-03-11 15:49
> A context menu pops up, but there is no "Find all references" item

That depends on the extension, it must register a reference provider. @AlexanderAmelkin please try with a TypeScript file and check if you see the action in the context menu

**Comment by jrieken** [comment] 2019-03-22 08:16
Closing because no information was provided

**Closed by jrieken** 2019-03-22 08:16 UTC
Labels: bug, needs more info, workbench-views

**Comment by AlexanderAmelkin** [comment] 2019-03-25 12:02
I'm sorry for the delay with info regarding TypeScript (I don't use it), but isn't it wrong to close an issue regarding C++ because I haven't conducted the requested TypeScript experiment?

I've checked now and yes, it turns out that it indeed does work with TypeScript.
Does that excuse that it doesn't work with C/C++? I don't think so.

**Comment by AlexanderAmelkin** [comment] 2019-03-25 12:02
@jrieken, please re-open. The issue isn't resolved.

**Comment by jrieken** [comment] 2019-03-25 13:35
> Does that excuse that it doesn't work with C/C++? I don't think so.

That means this issue is caused by the c/c++ extension and should be filed there

**Comment by AlexanderAmelkin** [comment] 2019-03-29 11:03
@jrieken, ok thank you.
I found that it is a long (very-very-long actually) existing issue: Microsoft/vscode-cpptools#15
I see that Microsoft has been working on it for THREE YEARS now without any progress. :(
IMO, there is no slightest chance that this feature will ever get implemented.
I'll go switch back to vim+cscope.
Thanks.

**Comment by XobSod** [comment] 2019-04-01 06:25
@AlexanderAmelkin 
Have you tried using clangd with its extension. I have "configured" it few days ago and it works quite well, of course you have to disable this microsoft addon, and allow [clangd](https://clang.llvm.org/extra/clangd/) do the stuff ;)
