### ISSUE TITLE
Add support for `vscode.executeFoldingRangeProvider`

### ISSUE THREAD

**Issue by allisonchou** [microsoft/vscode#158973] opened 2022-08-23 19:53 UTC
Folding ranges is part of the VS Code API: https://code.visualstudio.com/api/language-extensions/programmatic-language-features

yet is not exposed as a command:
https://github.com/microsoft/vscode/blob/c84655d123e115dc7b38fdea27c7449c0773f60c/src/vs/workbench/api/common/extHostApiCommands.ts

Razor needs the command to retrieve C#/HTML folding range results.

**Comment by aeschli** [comment] 2022-08-26 15:13
Duplicate of https://github.com/microsoft/vscode/issues/36638

**Closed by aeschli** 2022-08-26 15:13 UTC
