### ISSUE TITLE
fatal: ""repository folder""/README.md' is outside repository

### ISSUE THREAD

**Issue by best4him** [microsoft/vscode#100171] opened 2020-06-15 07:54 UTC
When I am trying to add a file, it fails! I get the following error: fatal: ""repository folder""/README.md' is outside repository. It happens after the last update. It looks like I am not the only one: https://stackoverflow.com/questions/47508212/vscode-git-fatal-error-file-is-outside-directory/62345271#62345271?newreg=2a4134dd0a0448ddb2f67d353b7fe235. 

If a add it from terminal, it works! Also, on some projects I am able to add the untracked files.

**Comment by gjsjohnmurray** [comment] 2020-06-15 09:11
/duplicate of #99881 and others (search for 'outside repository')

People have reported resolving this by updating their local Git.

**Closed** 2020-06-15 09:11 UTC
Labels: *duplicate
