### ISSUE TITLE
'find' function  can not work

### ISSUE THREAD

**Issue by microchang** [microsoft/vscode#69819] opened 2019-03-05 03:54 UTC
Issue Type: <b>Bug</b>

double click a word ,commond + f ,then I can see the find function block at right top area,but it says "No Results". sometimes I search a word,find funciton says only one in this page,but there are many same word actually.(I dont choosed any buttons such as 'Aa' or 'Ab|')

at first I doubt  if there is some extensions break my vscode, so I disabled someone,then find funciton works.but a few minutes later, find function break again.so I disabled all my extensions,but find function  can not work either . 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
<img width="710" alt="wx20190305-115353 2x" src="https://user-images.githubusercontent.com/5638390/53780003-60bc0300-3f3d-11e9-9143-fa841a9545a3.png">

</details>Extensions: none

<img width="710" alt="wx20190305-115353 2x" src="https://user-images.githubusercontent.com/5638390/53780019-72050f80-3f3d-11e9-8242-c4e74e2948d7.png">

**Comment by Rycochet** [comment] 2019-03-05 10:14
Just been hit with the same bug - haven't tracked down a cause for it, but if you select-all first, then choose to search selection, it allows it to work. Not a pleasant work-around, but at least it only slows things down now.

**Comment by atiris** [comment] 2019-03-08 10:42
**Please pay more attention to this bug.**
This is a very serious problem, as the editor's base function is replacement, and in this case the Code claims, for example, to replace all the results, even if it is not.

**It can be simulated as follows:**
- Run the Code in mode without extensions.
- In a new document you can enter any text, for example:

```text
aaa aaa aaa aaa
bbb aaa aaa bbb
aaa aaa ccc ddd
```

- Press CTRL + F and enter text "aaa" _(find x of 8 - ok)_
- Select entire line 2
- Click / enable Find in selection _(find x of 2 - ok)
- Click into line 2 and press ESC to exit searching

- Select text to find (second aaa on line 3)
- Press CTRL + F => first bug _(find 1 of 1)_

Find in selection is still enabled! This is bug for me, if I select something which is copied into search field (one word from document) then Find in selection should be disabled. If I select multiple rows and then press CTRL + F so none is copied into search field, then Find in selection should be enabled and I can find in selected area.

- Disable Find in selection => second bug _(find 1 of 1)_

VSCode ignore all others "aaa" strings and return only 1 result in find even if selection scope is whole document. It looks like internally VSCode works with some invisible selection and this selection is not cleared if I disable Find in selection.

- Double click first "bbb" and press CTRL + F => second bug _(find 0 of 0)_

In this case VSCode can not find even selected word! Whether the "Find in selection" is on or off. After switch Find in selection state it find only one bbb.

This is especially important when replacing. Man assumes that he will replace all occurrences of something in the document and VSCode says that (no more result in search), but in fact he will replace only a part or none of the search strings.

_My system informations:_

Parameter | Value
-- | --
CPUs | Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwaresurface_synchronization: enabled_onvideo_decode: unavailable_offwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 30.83GB (5.45GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%
Extensions | none

**Comment by atiris** [comment] 2019-03-11 13:08
**Update:** It is partially fixed in 1.32.0.

First bug is still there. After CTRL+F if any "substring" is copied into Find text input field, a selection is automatically created from it (in what situation can it be useful?)

Second bug is resolved.

All strange behavior reported as feature request here: https://github.com/Microsoft/vscode/issues/70210

Version: 1.32.0
Commit: 507312a3e3b34b084b467dfd983263bc7c9d87e0
Date: 2019-03-06T18:53:01.021Z

**Comment by Rycochet** [comment] 2019-03-11 13:16
> **Update:** It is partially fixed in 1.32.0.
> 
> First bug is still there. After CTRL+F if any "substring" is copied into Find text input field, a selection is automatically created from it (in what situation can it be useful?)

This has been around for several releases - long before the utter breakage of the previous release.

**Comment by rebornix** [comment] 2019-07-26 00:35
I can't reproduce this issue in latest Insiders, can anyone help provide detailed steps for reproduce?

**Comment by atiris** [comment] 2019-07-26 07:20
I also tried it (on latest production version), I can't simulate it on windows or linux (Fedora) too. If I'm not wrong, this was fixed in `src/vs/editor/contrib/find/simpleFindWidget.ts` in this commit https://github.com/microsoft/vscode/commit/7162bd579459b89f09ba50db92589d82b6beb5ac#diff-c91a81b861d816a65988adee But I can't say for sure, I'm not working on VSCode :smiley_cat:  
@rebornix try to see if such a modification could fix this problem... :wink:

**Comment by rebornix** [comment] 2019-07-26 17:59
Thanks, let's close it first and we can reopen whenever you run into it again.

**Closed by rebornix** 2019-07-26 17:59 UTC
Labels: editor-find, needs more info
