### ISSUE TITLE
"Rename symbol" does not commit changes

### ISSUE THREAD

**Issue by mloffer** [Microsoft/vscode#62323] opened 2018-10-31 20:31 UTC
- VSCode Version: 1.28.2
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Rename symbol.

Affected files are opened in new tabs with the symbol refactored, instead of simply being written to disk. This is confusing and unintuitive.

**Comment by mjbvz** [comment] 2018-10-31 20:40
Duplicate of #47573

**Closed by mjbvz** 2018-10-31 20:40 UTC
