### ISSUE TITLE
proposal-optional-chaining

### ISSUE THREAD

**Issue by zhouxianjun** [Microsoft/vscode#65060] opened 2018-12-14 08:22 UTC
Issue Type: <b>Feature Request</b>

Optional chaining suport in Javascript

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

![image](https://user-images.githubusercontent.com/5254523/49991541-62b89a80-ffbc-11e8-836f-daae8f995f81.png)

**Comment by mjbvz** [comment] 2018-12-14 19:34
Duplicate of https://github.com/Microsoft/TypeScript/issues/16

**Closed by mjbvz** 2018-12-14 19:34 UTC
Labels: new release
