### ISSUE TITLE
In the integrated terminal CTRL + V prints ^V and do not paste.

### ISSUE THREAD

**Issue by bldesign** [Microsoft/vscode#8700] opened 2016-07-03 22:40 UTC
In the integrated terminal CTRL + V prints ^V and do not paste.

- VSCode Version: 1.2.1
- OS Version: Windows 10
- Node 5.10.0

Steps to Reproduce:

1. Press CTRL + V in the integrated terminal
2. It prints ^V and do not paste

**Comment by Tyriar** [comment] 2016-07-04 04:58
Duplicate of https://github.com/Microsoft/vscode/issues/6451, see there for advice

**Closed by Tyriar** 2016-07-04 04:58 UTC
