### ISSUE TITLE
cannot copy ANYTHING from VS Code Stable Jupyter Notebook and paste into VS Code Insider

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#182886] opened 2023-05-18 15:49 UTC
I cannot copy ANYTHING from VS Code Stable and paste into VS Code Insider. 

So what I am having to do is first copy from VSCode Stable to any other Text Editor, then copy from there, and paste it into VSCode Insider

I have tried opening inside with `code-insiders --disable-extensions` - BUT that did not help

Also manually deleted `C:\Users\user_name\AppData\Roaming\Code - Insiders\Local Storage` - Did not help though.

Stable Version

```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

Insider Version 

```
Version: 1.79.0-insider (user setup)
Commit: f1258a5fbed44b8f84a097c73c1799c13c5c3646
Date: 2023-05-17T05:27:38.052Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by meganrogge** [comment] 2023-05-18 16:16
has this always been the case? I'm confident this is an issue with your setup as I cannot reproduce.

**Comment by rohan-paul** [comment] 2023-05-19 08:27
> has this always been the case? I'm confident this is an issue with your setup as I cannot reproduce. maybe electron?

It has always worked fine, this problem started pretty recently. Today I completely uninstalled Insiders and re-installed it. But the problem remains.

**Comment by amunger** [comment] 2023-05-19 16:27
I can repro for any type of file in stable to anything in insiders

with keyboard shortcut troubleshooting:

```
2023-05-19 09:26:06.649 [info] [KeybindingService]: + Invoking command editor.action.clipboardPasteAction.
2023-05-19 09:26:06.665 [error] Cannot read properties of undefined (reading 'pasteOnNewLine'): TypeError: Cannot read properties of undefined (reading 'pasteOnNewLine')
    at al.F (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:750:36052)
    at async vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:750:33983
2023-05-19 09:26:06.843 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by mjbvz** [comment] 2023-07-25 21:55
@amunger Can you test this again? I think it may have already been fixed but am not sure I am following the correct steps

**Comment by amunger** [comment] 2023-07-25 22:45
can't repro anymore

**Comment by mjbvz** [comment] 2023-07-25 22:53
Thanks for confirming. Closing as fixed

**Closed by mjbvz** 2023-07-25 22:53 UTC
