### ISSUE TITLE
Multi byte characters (like a checkmark) break the up and down movement of the cursor

### ISSUE THREAD

**Issue by Wokarol** [microsoft/vscode#144347] opened 2022-03-03 22:48 UTC
Issue Type: <b>Bug</b>

Character like a checkmark is internally two bytes, which causes weird behaviour when moving up and down with the cursor as it jumps left/right. This is probably cause by column calculation not taking into consideration such characters (the Ln Col information on the bottom bar does take that into consideration).

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30438800
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by alexdima** [comment] 2022-03-09 11:59
Duplicate of #142738

**Closed by alexdima** 2022-03-09 11:59 UTC
