### ISSUE TITLE
Update of remote extensions failed

### ISSUE THREAD

**Issue by ArcticOc** [microsoft/vscode#215622] opened 2024-06-15 18:53 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.1 (Universal)
- OS Version: Darwin arm64 24.0.0

Steps to Reproduce:
Unable to update the remote extension. And there is no change after clicking 'Update'.
Many extensions have this issue. Here is one example.

![CleanShot](https://github.com/microsoft/vscode/assets/43022588/fdf902f6-744e-4dd9-875c-b5ec7bdf49a7)

**Comment by polyrand** [comment] 2024-06-17 08:06
I've also been experiencing this. VSCode Version: `1.90.1`. Local OS: `macOS Sonoma 14.5`. Remote OS: `Ubuntu 22.04 LTS`

I have tried rebooting the remote VM, killing `vscode-server` on the remote VM, killing `vscode-server` on the remote VM and removing all the `vscode-server` files (`rm -rf ~/.vscode-server/`). Nothing worked. After removing all the files inside ` ~/.vscode-server/`, it seems that after the first connection, it correctly installed the latest version of all the extensions. But now that one of them has received an update, I'm experiencing the same issue as the original message.

**Comment by sandy081** [comment] 2024-06-17 08:27
Can you please share following log while you reproduce the issue

- F1 > Set Log Level... > Trace
- Reproduce the issue
- F1 > Open View... > Server

**Comment by polyrand** [comment] 2024-06-17 08:34
Yes, here's the relevant part of the logs (the rest of the messages are unrelated to this issue, I replaced the profile ID with `{PROFILE ID}`:

```
2024-06-17 08:30:34.296 [trace] Scanned system extensions: 31
2024-06-17 08:30:34.297 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
2024-06-17 08:30:34.297 [warning] [mypy-type-checker]: Couldn't find message for key settings.ignorePatterns.description.
2024-06-17 08:30:34.314 [trace] Scanned user extensions: 27
2024-06-17 08:30:34.323 [trace] Started scanning system extensions
2024-06-17 08:30:34.323 [trace] Started scanning user extensions {"$mid":1,"fsPath":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","external":"file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","path":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","scheme":"file"}
2024-06-17 08:30:34.346 [trace] Scanned system extensions: 31
2024-06-17 08:30:34.347 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
2024-06-17 08:30:34.347 [warning] [mypy-type-checker]: Couldn't find message for key settings.ignorePatterns.description.
2024-06-17 08:30:34.364 [trace] Scanned user extensions: 27
2024-06-17 08:30:34.377 [trace] ExtensionGalleryService#downloadSignatureArchive github.copilot
2024-06-17 08:30:34.377 [trace] resolveShellEnv(): running (macOS/Linux)
2024-06-17 08:30:34.386 [trace] Verifying extension signature for github.copilot...
2024-06-17 08:30:35.372 [info] Extension signature verification result for github.copilot: Success. Executed: true. Duration: 986ms.
2024-06-17 08:30:35.373 [trace] Extension signature verification output for github.copilot:
Package file size:  8605481
Signature archive file size:  11772
Manifest file size:  6677
Signature file size:  12126
Manifest file hash:  hH9Q1q1dG7Tk24sKNLLoJpccRLPXgSnCNL/rJx4MdEo=
Signature file hash:  mDeB5Nc2E3tAolg8d9G4IAG0AF8fCWh32Mdso4ePozc=
Package file hash:  qCBmbkCOenEiE/NC+PRGvuIp+xlV3ITq4E3RAuJPHw0=
ManifestPackageIntegrityPolicy succeeded.
SignatureIntegrityPolicy for primary signature succeeded.
SignatureValidityPolicy for primary signature succeeded.
SignatureIntegrityPolicy for primary timestamp signature succeeded.
SignatureValidityPolicy for primary timestamp signature succeeded.
X.509 certificate chain validation will use the fallback certificate bundle for timestamping.
SignatureTrustPolicy for repository primary signature timestamp signature succeeded.
X.509 certificate chain validation will use the fallback certificate bundle for code signing.
SignatureTrustPolicy for repository primary signature succeeded.
RepositoryCountersignaturePolicy for repository primary signature succeeded.
Primary signature type:  repository primary signature
Primary signature status:  OK
Timestamp signature status:  OK
Exit code:  Success

2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:30:35.382 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:30:35.384 [trace] Started scanning system extensions
2024-06-17 08:30:35.384 [trace] Started scanning user extensions {"$mid":1,"fsPath":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","external":"file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","path":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","scheme":"file"}
2024-06-17 08:30:35.409 [trace] Scanned system extensions: 31
2024-06-17 08:30:35.410 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
2024-06-17 08:30:35.410 [warning] [mypy-type-checker]: Couldn't find message for key settings.ignorePatterns.description.
2024-06-17 08:30:35.427 [trace] Scanned user extensions: 27
```

It seems the extension is correctly installed, but the UI still shows the `Update` button?

**Comment by sandy081** [comment] 2024-06-17 08:43
> Yes, here's the relevant part of the logs (the rest of the messages are unrelated to this issue

I think there is some information related to this issue is missing in the log. There should be a log statement when extension installation started and when extension installation finished. Can you please include them?

**Comment by polyrand** [comment] 2024-06-17 09:19
```
2024-06-17 08:55:26.128 [trace] Scanned user extensions: 27
2024-06-17 08:55:26.143 [trace] ExtensionGalleryService#downloadSignatureArchive github.copilot
2024-06-17 08:55:26.143 [trace] resolveShellEnv(): running (macOS/Linux)
2024-06-17 08:55:26.152 [trace] Verifying extension signature for github.copilot...
2024-06-17 08:55:27.147 [info] Extension signature verification result for github.copilot: Success. Executed: true. Duration: 995ms.
2024-06-17 08:55:27.147 [trace] Extension signature verification output for github.copilot:
Package file size:  8605481
Signature archive file size:  11772
Manifest file size:  6677
Signature file size:  12126
Manifest file hash:  hH9Q1q1dG7Tk24sKNLLoJpccRLPXgSnCNL/rJx4MdEo=
Signature file hash:  mDeB5Nc2E3tAolg8d9G4IAG0AF8fCWh32Mdso4ePozc=
Package file hash:  qCBmbkCOenEiE/NC+PRGvuIp+xlV3ITq4E3RAuJPHw0=
ManifestPackageIntegrityPolicy succeeded.
SignatureIntegrityPolicy for primary signature succeeded.
SignatureValidityPolicy for primary signature succeeded.
SignatureIntegrityPolicy for primary timestamp signature succeeded.
SignatureValidityPolicy for primary timestamp signature succeeded.
X.509 certificate chain validation will use the fallback certificate bundle for timestamping.
SignatureTrustPolicy for repository primary signature timestamp signature succeeded.
X.509 certificate chain validation will use the fallback certificate bundle for code signing.
SignatureTrustPolicy for repository primary signature succeeded.
RepositoryCountersignaturePolicy for repository primary signature succeeded.
Primary signature type:  repository primary signature
Primary signature status:  OK
Timestamp signature status:  OK
Exit code:  Success

2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [raw] ["change"] extensions.json
2024-06-17 08:55:27.156 [trace] [File Watcher (node.js)] [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.158 [trace] Started scanning system extensions
2024-06-17 08:55:27.158 [trace] Started scanning user extensions {"$mid":1,"fsPath":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","external":"file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","path":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","scheme":"file"}
2024-06-17 08:55:27.187 [trace] Scanned system extensions: 31
2024-06-17 08:55:27.188 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
2024-06-17 08:55:27.188 [warning] [mypy-type-checker]: Couldn't find message for key settings.ignorePatterns.description.
2024-06-17 08:55:27.210 [trace] Scanned user extensions: 27
2024-06-17 08:55:27.218 [info] Extension installed successfully: github.copilot file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.230 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:27.230 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] /home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:37.556 [info] Getting Manifest... github.copilot
2024-06-17 08:55:37.556 [trace] resolveShellEnv(): running (macOS/Linux)
2024-06-17 08:55:37.570 [info] Installing extension: github.copilot file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json
2024-06-17 08:55:37.570 [trace] Started scanning system extensions
2024-06-17 08:55:37.570 [trace] Started scanning user extensions {"$mid":1,"external":"file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","path":"/home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json","scheme":"file"}
2024-06-17 08:55:37.609 [trace] Scanned system extensions: 31
2024-06-17 08:55:37.610 [warning] [mypy-type-checker]: Couldn't find message for key settings.cwd.description.
```

The only extra line I found is `2024-06-17 08:55:27.218 [info] Extension installed successfully: github.copilot file:///home/ubuntu/.vscode-server/data/User/profiles/{PROFILE ID}/extensions.json`.

Then it goes back to fetching the extension manifest again, gets back the same hashes, installs the extensions again, etc.

Note that even if I'm using GitHub copilot as the example, it happens with all the other extensions running in the remote.

This does **not** happen when update extensions locally.

**Comment by sandy081** [comment] 2024-06-17 09:39
> Then it goes back to fetching the extension manifest again, gets back the same hashes, installs the extensions again, etc.

What do you mean by it here? Are you triggering this by any UI action?

**Comment by polyrand** [comment] 2024-06-17 09:50
> What do you mean by it here? Are you triggering this by any UI action?

No. Here's a more complete set of actions.

1. Close VSCode remote
2. Open VSCode
3. Open connection to remote workspace
4. (Quickly) set log level = TRACE and open server logs

**Without any UI interaction**, this string (and the others related to that same extension) appear twice in the logs:

```
[info] Extension installed successfully: github.copilot
```

5. At this point, the UI button shows the same as the GIF in the original issue message. (*Installed* **`Update`**)

If I now click the `Update` button again, it goes on and repeats the same sequence of actions (fetch manifest, verify hashes, install extension, show the `Extension installed successfully: github.copilot` log, etc). Then it goes back to showing the **`Update`** button again. Every time it's clicked, the same sequence of logs appear.

In case it's useful, at the top of the logs I see:

```
2024-06-17 09:40:32.323 [info] Extension 'github.copilot' v1.202.0 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'github.copilot@1.2.3'.
```

However, the new version it's trying to install (and supposedly gets successfully installed) is `v.1.203.0`

<img width="216" alt="image" src="https://github.com/microsoft/vscode/assets/37962604/4552d6a3-14ce-44fa-8b54-c108bf5019ef">

Even if I:

1. Install update
2. See `Extension installed successfully: github.copilot`
3. Reload window and/or Kill remote VSCode server and/or completely closed and reopen VSCode

The same thing happens.

**Comment by polyrand** [comment] 2024-06-17 13:16
> Are you using any profiles?

Yes.

**Comment by Velocet** [comment] 2024-06-17 17:03
Got the same problem as shown by OP.

Updated to the latest (stable) version and the problem is still there.

Impossible to update any extension. The whole process is slow (eg. trying to search for extensions). Before the update the whole extension section wasn't listing any of the installed extension and stopped working completely.

Which logs do you need? Setting to Debug/Trace does not yield any results which point to an error.

**Comment by sandy081** [comment] 2024-06-21 14:55
Can you please try our insiders and see if you can reproduce the issue - https://code.visualstudio.com/insiders/

**Comment by ArcticOc** [comment] 2024-06-21 15:24
> Can you please try our insiders and see if you can reproduce the issue - https://code.visualstudio.com/insiders/

In insiders, it works fine now.

**Comment by sandy081** [comment] 2024-06-21 17:11
Then I believe this would have been fixed in Insider. So fix will be available in our next release in 2 weeks. Thanks for sharing the information.

Is this extension configured to be available in all profiles?

**Comment by ArcticOc** [comment] 2024-06-21 17:24
> Then I believe this would have been fixed in Insider. So fix will be available in our next release in 2 weeks. Thanks for sharing the information.
> 
> Is this extension configured to be available in all profiles?

Thanks for your help. No, this extension is only enabled in specific profile.

**Comment by sandy081** [comment] 2024-06-24 10:21
Thanks for the info. I believe this is fixed in insiders and would like to wait for next release for the fix which will be in a week.

**Closed by sandy081** 2024-06-24 10:21 UTC
Labels: info-needed
