### ISSUE TITLE
Missing auto import

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61905] opened 2018-10-26 21:36 UTC
- Open a .ts file
- Type the name of a symbol from a different file quickly
- The symbol shows up in the suggest list but without the Auto Import details
- If I select it, it is not auto imported

Debugged offline with @mjbvz, saw that the details request is canceled right after its sent:

```
[Trace  - 2:33:07 PM] Sending request: completionEntryDetails (326). Response expected: yes. Current queue length: 0
[Trace  - 2:33:07 PM] TypeScript Server: trying to cancel ongoing request with sequence number 326
```

**Comment by G1itcher** [comment] 2018-11-06 11:33
I'm also experiencing this also. Seems to not only fail to get the information about the module, but also leaves the information regarding another module showing when the selecting the local module.

![image](https://user-images.githubusercontent.com/4215816/48061728-cf6b9880-e1b7-11e8-9a3e-c99f49bf3dc5.png)

**Comment by mjbvz** [comment] 2018-11-30 22:01
Duplicate of #63013

**Closed by mjbvz** 2018-11-30 22:01 UTC
Labels: bug, typescript
