### ISSUE TITLE
Notebook diff accordions should use or align with existing components

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#226815] opened 2024-08-27 17:08 UTC
Testing #226663

These:

![Image](https://github.com/user-attachments/assets/226b9c49-2b6e-424e-b50b-f9dfa583e5b3)

Look similar, but not quite the same, as these other tree/accordion elements we have 

![Image](https://github.com/user-attachments/assets/b9aa4b38-38f5-4dc4-85ee-0ce35464e6a4)

![Image](https://github.com/user-attachments/assets/05b6b4f0-ab70-4cbf-95db-7d9bb40588b9)

![Image](https://github.com/user-attachments/assets/ae58307a-f5e7-48f6-8b41-e57225eaca12)

Off the top of my head, it probably makes the most sense to align to the tree view both from a styling and interaction POV. For example, the collapsible sections in the notebook diff and only be expanded/collapsed by clicking on the chevron. In tree views/views/settings TOC, you can click anywhere on the containing element. 

It also looks like I can't focus on the element to expand/collapse with just the keyboard.

**Comment by DonJayamanne** [comment] 2024-08-27 23:45
> It also looks like I can't focus on the element to expand/collapse with just the keyboard.

Duplicate of https://github.com/microsoft/vscode/issues/105922

**Closed** 2024-08-28 00:45 UTC
Labels: notebook, papercut :drop_of_blood:, notebook-diff

**Comment by amunger** [comment] 2024-08-28 16:49
looks good to me (I can click anywhere to expand), but maybe @daviddossett should take another look since I don't see much inconsistency in those screenshots.
