### ISSUE TITLE
When a file name is edited in Explorer, right-clicking on the textbox loses focus and exits the editing state.

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/vscode#130952] opened 2021-08-16 23:59 UTC
![image](https://user-images.githubusercontent.com/20025591/129643326-0ce8ca7e-d174-4a35-b854-4ec098df5d9d.png)
version:1.59.0

**Comment by JacksonKearl** [comment] 2021-08-17 00:12
Seems to work for me, what is your platform?

![image](https://user-images.githubusercontent.com/8586769/129644248-0dfe0e74-21a0-458d-ad0e-6a04453f965e.png)

**Comment by IllusionMH** [comment] 2021-08-17 00:16
Looks like duplicate of #130564

@JacksonKearl are you using native title bar and contex menus?

**Comment by JacksonKearl** [comment] 2021-08-17 00:44
Yes I'm on MacOS, so always native. Is this custom only?

**Comment by IllusionMH** [comment] 2021-08-17 00:52
Described behavior is reproducible on Windows with custom title bar style (default).

With native it does not exist edit mode but context menu closed almost immediately.
More examples in linked issue

**Comment by JacksonKearl** [comment] 2021-08-17 01:00
cc @sbatten any ideas on best practices for dealing with blur events due to context menus?

**Comment by yilmazdurmaz** [comment] 2021-08-17 16:45
Hi @JacksonKearl , I am the one posted #130952 @IllusionMH  referenced.

it is unfortunate that my post is marked as a duplicate while there is seemingly no duplicate open issues waiting to be solved, nor it was fixed at any point in time since the issue is present for the last 2 years.

I am not sure about the fate of my post, so please check the post for few more details about this problem.

**Comment by IllusionMH** [comment] 2021-08-17 17:20
Most likely underlying case (for this issue and #130952) is that custom context menu force focus on themselves and therefor blur list items. It's tracked in #123771

It's unclear if inputs need separate issue until #123771 resolved. Better - fix for #123771 should take inputs into account.

**Comment by JacksonKearl** [comment] 2021-08-17 17:27
Thanks @IllusionMH, I agree this is a duplicate of #123771. fyi @joaomoreno

**Closed by JacksonKearl** 2021-08-17 17:27 UTC
Labels: bug, file-explorer, menus

**Comment by YexuanXiao** [comment] 2021-08-21 06:08
> Seems to work for me, what is your platform?
> 
> ![image](https://user-images.githubusercontent.com/8586769/129644248-0dfe0e74-21a0-458d-ad0e-6a04453f965e.png)

Windows11
