### ISSUE TITLE
Undo stack is busted when saving a file, switching to another tab, and then going back to the original tab

### ISSUE THREAD

**Issue by boaz-chen** [Microsoft/vscode#10067] opened 2016-08-03 08:30 UTC
- VSCode Version:

1.3.1

- OS Version:
OS X El Capitan 10.11.6

Steps to Reproduce:

1. Create a new file
2. Type 'hello'
3. Save the file
4. ctrl+tab to another tab
5. ctrl+tab back to the first tab
6. Try to undo

Result: undo is not working.

**Comment by boaz-chen** [comment] 2016-08-04 10:23
I cannot repro this issue after restarting vscode, but I have seen it happening in the past as well, so I guess this bug is a tricky one.

**Comment by bpasero** [comment] 2016-08-06 13:18
@boaz-chen if you have reliable steps please update this issue!

**Comment by bpasero** [comment] 2016-08-08 08:08
With the provided steps I could not reproduce. Closing until we find steps. I think I am seeing this from time to time as well, but hard to catch.

@alexandrudima fyi

Imho the only way we can lose the undo stack is that the model gets disposed. However if that happens, we should also not see the file open anymore in the tabs.

**Closed by bpasero** 2016-08-08 08:08 UTC
Labels: bug

**Comment by bpasero** [comment] 2016-08-26 10:49
This is https://github.com/Microsoft/vscode/issues/10932
