### ISSUE TITLE
opening vscode from WSL2 hangs linux prompt

### ISSUE THREAD

**Issue by jgilfoil** [microsoft/vscode#182264] opened 2023-05-12 06:44 UTC
Type: <b>Bug</b>

Before update 1.78.2 (i'm not sure what version I was on prior to this update), I was able to run `code .` from my WSL2 (Windows Subsystem Linux) prompt and launch into vscode in the path inside my WSL VM (usually /home/jason).  As soon as vscode was launched, my linux prompt would return to the prompt ready to accept new commands.
```
╭─jason at computer in ~/repos/github/jgilfoil/mymindinai on main✘✘✘ 23-05-12 - 0:30:09
╰─⠠⠵ code .
╭─jason at computer in ~/repos/github/jgilfoil/mymindinai on main✘✘✘ 23-05-12 - 0:38:50
╰─⠠⠵
```

After the update to 1.78.2. when i run `code .` it launches vscode ok, but the prompt in linux hangs, and does not recover until i close the vscode window. This was not the behavior before, ~~and I suspect it's causing other issues with extensions like Dev Containers malfunctioning.~~ ( I no longer think this is related after further troubleshooting that issue)
```
╭─jason at computer in ~/repos/github/jgilfoil/cluster-infra on feature/docker-control✘✘✘ 23-05-12 - 0:23:24
╰─⠠⠵ code .

```
This happens with or without extensions enabled. It does not happen when i use `code .` from the windows command prompt in a local windows folder. I also tried adding wsl.localhost to my security.allowedUNCHosts setting. This resolved my warning about untrusted unc paths, but did not resolve this issue.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (25.52GB free)|
|Process Argv|. --crash-reporter-id 8e0e1d72-f6ac-4494-8ee8-a442fb2bb154|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: cluster-infra|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 3199)|
|Memory (System)|31.30GB (28.11GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.292.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
showsbindicator:30730056

```

</details>

**Comment by aeschli** [comment] 2023-12-20 16:06
Closing as I can't reproduce.

**Closed by aeschli** 2023-12-20 16:06 UTC
