### ISSUE TITLE
help sofware random blured code on focus elements? 

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#57243] opened 2018-08-27 03:15 UTC
it has happened in a random way for a while now.
I decided to ask the question today because these very hard to code with this feature.
I dont know if it came from windows or the vscode software, but i need help to disable and fix this.
thanks

- VSCode Version: vscode v1.26.1
![image](https://user-images.githubusercontent.com/24865815/44639547-89f64800-a98a-11e8-9b15-5959019ffead.png)

- OS Version:  win10.1830

__________
![image](https://user-images.githubusercontent.com/24865815/44638535-5533c200-a985-11e8-8698-d2787377f7e9.png)
As you can see , i have random blur on vsCode software !!!
it not photoshopped , it true. !!
Steps to Reproduce:

1.start vsCode
2. mouse mouse randomly on elements or code.

current setup profil workspace

```json
{
    "typescript.check.npmIsInstalled": false,
    "editor.dragAndDrop": false,
    "window.zoomLevel": -1,
    "editor.mouseWheelZoom": true,
    "workbench.iconTheme": "vscode-great-icons",
    "editor.fontSize": 16,
    "workbench.colorTheme": "One Dark+ (Sublime)",
    "editor.fontFamily": "DejaVu Sans Mono",
    "window.menuBarVisibility": "toggle",
    "editor.renderControlCharacters": true,
    "git.ignoreMissingGitWarning": true,
    "editor.renderIndentGuides": false,
    "guides.active.gutter": true,
    "guides.active.color.dark": "rgba(89, 63, 102,1)",
    "guides.active.width": 3,
    "guides.stack.color.dark": "rgba(89, 63, 102,1)",
    "guides.updateDelay": 0.1,
    "editor.renderLineHighlight": "all",
    "editor.selectionHighlight": false,
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#31e45b39",
        "editor.selectionHighlightBackground": "#e032a62f",
        "editor.background": "#212121",
        /*"editor.foreground": "#d4d4d4",
        "editorIndentGuide.background": "#404040",
        "editorRuler.foreground": "#333333",
        "activityBarBadge.background": "#007acc",
        "sideBarTitle.foreground": "#bbbbbb",*/
        
      },
      "workbench.list.openMode": "doubleClick",


}


```

**Comment by djmisterjon** [comment] 2018-08-27 03:26
i also try hack how the window manage the blur of this app but not work.
![image](https://user-images.githubusercontent.com/24865815/44638972-6382dd80-a987-11e8-9c80-9004dfc0b895.png)

**Comment by djmisterjon** [comment] 2018-08-27 05:59
i dont know if this can help to understand the issue, but after make some test.
it happen more frequently also if i run a another app in background.
**it's a very frustrating problem.**
![image](https://user-images.githubusercontent.com/24865815/44642978-bf0b9600-a99c-11e8-8ffb-ca609bd13638.png)

**Comment by dbaeumer** [comment] 2018-08-27 09:10
Could this be Electron 2.0 related.

@alexandrudima since it is happening in the editor.

**Comment by djmisterjon** [comment] 2018-08-27 09:42
or it can be the node engine ?
For my debug i use another version of nwjs.
![image](https://user-images.githubusercontent.com/24865815/44652995-77e0cd80-a9bb-11e8-8806-d07e6b168672.png)
vscode app seem to use node **8.9.3**
and in my debug tool, run with node **10.1.0** and i don't see any blur.
I really don't know where this come from :( ...

**Comment by bpasero** [comment] 2018-08-27 09:57
Duplicate of https://github.com/Microsoft/vscode/issues/51789

**Closed by bpasero** 2018-08-27 09:57 UTC
Labels: editor, electron-2.0.x-update

**Comment by djmisterjon** [comment] 2018-08-29 09:05
Edit Fixed, it was the FXAA
