### ISSUE TITLE
The connection to the terminal's pty host is unresponsive error

### ISSUE THREAD

**Issue by Kjenium** [microsoft/vscode#200496] opened 2023-12-10 23:37 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85
- OS Version: 26002.1010

Steps to Reproduce:

1.  open a terminal, close it, open it again
2.

**Comment by meganrogge** [comment] 2023-12-15 19:57
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-12-15 19:57 UTC
