### ISSUE TITLE
"source.organizeImports" shouldn't remove my unused imports

### ISSUE THREAD

**Issue by yardz** [microsoft/vscode#112021] opened 2020-12-07 14:28 UTC
source.organizeImports, remove unused imports, don't remove unused imports.

When i put "source.organize Imports" in "editor.codeActionsOnSave" it removes my unused imports. It would be interesting to have a parameter for it to just organize but not remove.

Many developers save their files all the time, often without even realizing it. This feature is very interesting but ends up "disturbing" who has this habit.

If you can pass a few more configuration parameters (like not removing unused imports or not).

[issue in the typescript repository](https://github.com/microsoft/TypeScript/issues/36085)

**Comment by mjbvz** [comment] 2020-12-07 19:02
Duplicate of https://github.com/microsoft/TypeScript/issues/36085

Please don't open a duplicate issue if you already know it's a duplicate

**Closed by mjbvz** 2020-12-07 19:02 UTC

**Comment by yardz** [comment] 2020-12-07 19:26
This is not a duplicate. It is a vscode bug/request and not a typescript.

I put the other issue just as a reference, because there is nothing wrong with the typescript in this case. The other was opened in the wrong repository.

**Comment by russeg** [comment] 2020-12-16 02:20
> Please don't open a duplicate issue if you already know it's a duplicate

You could also not close an issue before you have actually read it.

Anyway, organize import on save breaks your flow during development, so it's pretty annoying. Probably not meant to be used that way.

**Comment by mjbvz** [comment] 2020-12-16 06:26
@yardz Why did you close the TypeScript issue? The TypeScript project provides organize imports for both JavaScript and TypeScript. If you want it be on the radar of the TS team, reopen the issue

**Comment by yardz** [comment] 2020-12-17 15:14
> @yardz Why did you close the TypeScript issue? The TypeScript project provides organize imports for both JavaScript and TypeScript. If you want it be on the radar of the TS team, reopen the issue

I may be wrong, but from what I found this is a VS Code issue, not TypeScript. So it makes sense for her to be here and not in the TS repo...




> Anyway, organize import on save breaks your flow during development, so it's pretty annoying. Probably not meant to be used that way.
Perhaps not, but a small configuration would maintain the original objective and open possibilities for new uses (If it was not designed to be used like this).
Anyway, I believe that I should be able to configure this type of behavior to suit my editor to my preferences rsrsrs (And each one your preferences, of course)

**Comment by mjbvz** [comment] 2020-12-17 22:00
Yes you are wrong. I made this pretty clear when I first closed this issue as a duplicate of a TS issue

**Comment by yardz** [comment] 2020-12-30 13:38
> Yes you are wrong. I made this pretty clear when I first closed this issue as a duplicate of a TS issue

If you had "made that pretty clear" I would not have had any doubts and other people wouldn’t have commented that you could read the issues before closing. You need to improve your communication and empathy skills as you are failing to be clear in your comments...
