### ISSUE TITLE
Debug pauses, callstack not available

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#24348] opened 2017-04-09 06:18 UTC
- VSCode Version:
    Version 1.12.0-insider
    Commit 77df7646504961abefe7c735d7a10171abce9d4a
    Date 2017-04-07T06:09:22.690Z

- OS Version: Ubuntu 16.04

- Debug protocol: "Auto (inspect, Node 7.7.1)"

![image](https://cloud.githubusercontent.com/assets/19211868/24835249/03b17124-1d05-11e7-8122-01adf292f39b.png)

Steps to Reproduce:

1. Put a breakpoint somewhere,
2. Debug, get to the breakpoint
3. Press F5 - debug will freeze and callstack will show "Callstack not available"

**Comment by Eli-Goldberg** [comment] 2017-04-09 06:20
I had some code with the "co" library, lot's of generator and promises,
if it's any help

**Comment by chrmarti** [comment] 2017-04-10 04:32
Could you post a simple code example that reproduces the problem?

**Comment by weinand** [comment] 2017-04-10 07:57
@Eli-Goldberg does it make a difference if you set the "protocol" to "inspector"?

**Comment by Eli-Goldberg** [comment] 2017-04-10 08:09
@weinand I'm pretty sure it doesn't matter because setting protocol to "auto" runs with inspect since it's node 7.7.1 but I can check.
@chrmarti 
will post a simple example in ~24 hours.
I'm pretty sure it has to do with almost no free RAM (lot's of data is loaded into memory sent via http).

**Comment by weinand** [comment] 2017-04-10 08:11
@Eli-Goldberg in VS Code 1.12.0 "inspect" is only used for node >= 8-0.
see https://code.visualstudio.com/updates/v1_11#_node-debugging

**Comment by weinand** [comment] 2017-04-10 08:14
With the old "legacy" protocol, the node debugger of VS Code will most likely run into callstack timeouts if there are big data structures kept in local variables or passed as parameters.

**Comment by Eli-Goldberg** [comment] 2017-04-10 08:15
@weinand Thanks that's right, the tooltip got me confused:
![image](https://cloud.githubusercontent.com/assets/19211868/24852109/e4a47f76-1dde-11e7-9226-f173fd3a88ce.png)

I will do the check with inspector.

**Comment by weinand** [comment] 2017-04-10 08:15
oh, indeed that's wrong.

**Comment by Eli-Goldberg** [comment] 2017-04-10 08:23
So the original problem does not happen here, but another issue is happening:
First - these errors:
![image](https://cloud.githubusercontent.com/assets/19211868/24852400/fc32be9a-1ddf-11e7-8958-ea057133e063.png)
Also,
If I remove breakpoints (remove all breakpoints), the code still stops where I previously had the breakpoints.

**Comment by roblourens** [comment] 2017-04-11 03:06
That is due to an unfortunate Node bug, https://github.com/nodejs/node/issues/11589, which I think should be fixed in Node 7.8. I don't think it should continue stopping there after removing breakpoints, but I guess it would be part of the same issue. 

Regarding the fact that 'auto' only uses inspector for v8+, that's a good point. Maybe the label of 'auto' should reflect this...

**Comment by Eli-Goldberg** [comment] 2017-04-18 15:08
@roblourens 
This indeed does look fixed in node 7.9.0 (probably in 7.8.0 too),
Can't reproduce it.
Also, I'm afraid I can't provide a code sample that reproduces this on earlier node versions.

**Comment by roblourens** [comment] 2017-04-18 17:02
Glad that worked. I think we can close this issue then right?

**Closed by roblourens** 2017-04-18 17:02 UTC
Labels: bug, debug
