### ISSUE TITLE
Breakpoints 'red dots' not shown in editor

### ISSUE THREAD

**Issue by ankon** [Microsoft/vscode#39547] opened 2017-12-04 13:17 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (8a12b294de610aab61c32c02c7c148d981cf07e4, 2017-12-04T06:14:18.360Z)
- OS Version: Linux x64 4.13.15-300.fc27.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.22
dot|Ste|0.0.1
vscode-nsp|ada|1.0.1
markdown-mermaid|bie|0.1.1
markdown-preview-github-styles|bie|0.1.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
pgsql|dou|0.0.8
scala-lsp|dra|0.2.2
gitlens|eam|6.3.0
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
kubernetes-snippets|ipe|0.1.3
plantuml|jeb|2.3.3
Go|luk|0.6.69
python|ms-|0.8.0
cpptools|ms-|0.14.3
github-issues-prs|ms-|0.9.0
js-atom-grammar|ms-|0.1.14
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.5.0
vscode-code-outline|pat|0.0.12
vscode-jscpd|pau|0.2.0
polymer-ide|pol|0.6.0
java|red|0.15.0
shellcheck|tim|0.2.1
vscode-java-debug|vsc|0.4.0

---

Steps to Reproduce:

1. Open a NodeJS project
2. Try to create a breakpoint by clicking into the space next to the line number
3. Observe that the breakpoint is added to the list of breakpoints, but no 'red dot' appears

Reproduces without extensions: *No*

**Comment by isidorn** [comment] 2017-12-04 13:23
@ankon 
1. can you reproduce this for any javascript file?
2. Can you reproduce if you disable all extensions?
3. Can you reproduce if you add breakpoints while you are not in a debug session?
4. Can you provide a small reproducable sample so we investigate? Thanks

**Comment by ankon** [comment] 2017-12-04 13:29
> 2. Can you reproduce if you disable all extensions?

I did that that (see report): indeed, the issue disappears (i.e. the dot appears) when running with `--disable-extensions`. What is even weirder: after that test I now restarted vscode without that switch, and now things also look alright for my initial setup.

> 3. Can you reproduce if you add breakpoints while you are not in a debug session?

I could at that time, it didn't matter whether I was in a session or not. What I did notice was also that the detached toolbar for debugging commands (does that thing have a name? :D) wouldn't show up, even though hotkeys for debug commands would still work. This problem is similarly gone now :(

So, TL;DR: I cannot reproduce this anymore since I _once_ started with `--disable-extensions` and then restarted again with extensions enabled. My extensions now:
Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.22
dot|Ste|0.0.1
vscode-nsp|ada|1.0.1
markdown-mermaid|bie|0.1.1
markdown-preview-github-styles|bie|0.1.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
pgsql|dou|0.0.8
scala-lsp|dra|0.2.2
gitlens|eam|6.3.0
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
kubernetes-snippets|ipe|0.1.3
plantuml|jeb|2.3.3
Go|luk|0.6.69
python|ms-|0.8.0
cpptools|ms-|0.14.3
github-issues-prs|ms-|0.9.0
js-atom-grammar|ms-|0.1.14
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.5.0
vscode-code-outline|pat|0.0.12
vscode-jscpd|pau|0.2.0
polymer-ide|pol|0.6.0
java|red|0.15.0
shellcheck|tim|0.2.1
vscode-java-debug|vsc|0.4.0

**Comment by isidorn** [comment] 2017-12-04 14:41
Closing this since you cannot reproduce anymore.
Please let us know if you see this again and give us some reproducable steps so we can investiagte.
Thanks

**Closed by isidorn** 2017-12-04 14:41 UTC
Labels: debug, insiders, needs more info
