### ISSUE TITLE
"Define keybinding" doesn't escape \

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21657] opened 2017-03-01 22:04 UTC
- Go to the keybindings page
- Press `cmd+k cmd+k`
- Dialog prompts for a keybinding. Press `cmd+\`
- Keybinding is inserted with `"cmd+\"`, should be `"cmd+\\"`

**Comment by alexandrudima** [comment] 2017-03-08 10:31
Duplicate of #17688

**Closed by alexandrudima** 2017-03-08 10:31 UTC
Labels: bug, keybindings
