### ISSUE TITLE
Only show problems of the tab that currently has the focus

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode#46542] opened 2018-03-26 10:22 UTC
The VS Code eslint plugin (for example) shows all problems in the Problems pane but it would be very useful to only see (and concentrate on) the problems in the file currently working on.
Is there a way to do so and if not, could an option be added to configure this?
(Moved from https://github.com/Microsoft/vscode-eslint/issues/435#issuecomment-376115120)

**Comment by sandy081** [comment] 2018-03-26 15:12
Duplicate of #30038

**Closed** 2018-03-26 15:12 UTC
Labels: *duplicate, error-list
