### ISSUE TITLE
Auto Complete doesn't suggest snippets with TM_SELECTED_TEXT when selecting text.

### ISSUE THREAD

**Issue by izacsc** [Microsoft/vscode#17746] opened 2016-12-22 20:23 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1.  Add this snippet:
    "SurroundTest": {
        "prefix": "SurroundTest",
        "body": [
            "SurroundTest( ${TM_SELECTED_TEXT})"
        ],
        "description": "."
    }

2. Try to surround a word with ctrl+space:
![image](https://cloud.githubusercontent.com/assets/423449/21439148/8aab0b90-c873-11e6-9f1e-bd6c10d11c0d.png)

![image](https://cloud.githubusercontent.com/assets/423449/21439157/96b43a92-c873-11e6-9305-02cbcdf814ad.png)

It only works if you use the command bar:

![image](https://cloud.githubusercontent.com/assets/423449/21439175/ad20967c-c873-11e6-8954-2084fd6cfd40.png)

![image](https://cloud.githubusercontent.com/assets/423449/21439182/b6b1c67a-c873-11e6-9006-b56d6231da0a.png)

**Comment by jrieken** [comment] 2016-12-23 15:51
This happens because IntelliSense always filters suggestion against the word at cursor. Because `word` and `SurroundTest` have nothing in common (no matches) it is filtered.... Not yet sure what to do about this, it's kind of as designed

**Comment by izacsc** [comment] 2016-12-23 16:29
Yeah... I figured it out. But I suppose the correct behavior would be suggesting the templates which use the TM_SELECTED_TEXT when seletcing text and the same for the other variables... ( word and line). Maybe a different comand for inputing these kind of snippets?

**Comment by jrieken** [comment] 2016-12-29 11:23
> Maybe a different comand for inputing these kind of snippets?

That is why we have the separate `Insert Snippet` command. Also, we will add a way to insert a specific snippet via a keybinding.

**Comment by jrieken** [comment] 2017-01-03 15:57
I am closing this as question because there not much we can go. IntelliSense works by filtering suggestion against the currently typed text. Other editor work like VS Code in this respect. There is already `Insert Snippet` and with 1.9 (or Insiders today) there will be [support to insert a snippet via keybinding](#17780)

**Closed by jrieken** 2017-01-03 15:57 UTC
Labels: snippets
