### ISSUE TITLE
Characters are being inserted into middle of word when using Intellisense to import package

### ISSUE THREAD

**Issue by j0hnm4r5** [microsoft/vscode#171347] opened 2023-01-15 06:20 UTC
Type: <b>Bug</b>

When using the Intellisense feature to automatically import a JS module, characters are inserted at the cursor. It looks like it copies everything from the cursor until the end of the word, and then inserts that at the cursor.

I ran the extension bisect utility, and the issue was occurring without any extensions enabled.

![CleanShot 2023-01-14 at 22 20 14](https://user-images.githubusercontent.com/3644972/212526097-39e94ac2-d421-43c7-bc44-7e939f776762.gif)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 6, 5|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id a30b815e-3499-4954-aac3-f2b2ddbd6e3a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
markdown-preview-github-styles|bie|1.0.1
vscode-tailwindcss|bra|0.9.5
vscode-toggle-quotes|Bri|0.3.6
gitignore|cod|0.9.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.5
copilot|Git|1.67.7944
vscode-pull-request-github|Git|0.56.0
svg|joc|1.4.26
rainbow-csv|mec|3.5.0
vscode-styled-components|mf|0.2.2
dotenv|mik|1.0.1
mongodb-vscode|mon|0.10.0
vscode-docker|ms-|1.23.3
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.20
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5803
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.0.12
material-icon-theme|PKi|4.23.1
prisma|Pri|4.8.1
vscode-yaml|red|1.11.0
vscode-sort-json|ric|1.20.0
vscode-scss-formatter|sib|2.4.4
svelte-vscode|sve|107.0.1
gcode|Ton|0.4.0
sort-lines|Tyr|1.9.1
vscode-sort-package-json|uni|1.3.0
quokka-vscode|Wal|1.0.521
vscode-nginx|wil|0.7.2
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.5.0
vitest-explorer|Zix|0.2.36

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by mjbvz** [comment] 2023-01-17 16:46
Duplicate of #169141. My answer in that issue explains insert vs replace mode for suggestions

**Closed by mjbvz** 2023-01-17 16:46 UTC
