### ISSUE TITLE
Inline suggest is suggesting unexpectedly

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#147080] opened 2022-04-08 13:14 UTC
My approximate steps:

1. Create a new file and past a typescript class in
2. Add a new filed to the class. 
3. Type the full type of the new field, then arrow back to see the bug. I was able to completely delete the type, re-input it, and the repro the issue again.

![Recording 2022-04-08 at 15 04 10](https://user-images.githubusercontent.com/38270282/162442870-6fa07ae0-2c05-4464-af57-fdd0b0141a95.gif)

**Comment by jrieken** [comment] 2022-04-12 09:58
/duplicate of https://github.com/microsoft/vscode/issues/146529

**Closed** 2022-04-12 09:58 UTC
Labels: *duplicate
