### ISSUE TITLE
Can't open Visual Studio Code when Offline

### ISSUE THREAD

**Issue by AbnerTaminggu** [Microsoft/vscode#63683] opened 2018-11-23 09:59 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 10 version 1809 (OS build 17763.134)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment] 2018-11-23 13:31
/duplicate of #7570, fixed in Electron 3 #52629

**Closed** 2018-11-23 13:31 UTC
Labels: *duplicate, extensions
