### ISSUE TITLE
Add something besides command line option to configure locale

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4118] opened 2016-03-14 11:01 UTC
Testing #4018

IMHO, there is a case not covered well enough. e.g.:
- having Windows locale in English and wanting to run VSCode in Spanish.
- or having Windows locale in Spanish and wanting to run VSCode in English.

The only way to do this now is to use a command line argument.

But especially in Windows, it is unusual to launch a UI app from the command line with arguments. E.g: taskbar, windows start button, double clicking a file associated with VSCode, right click open with VSCode.

I suggest some alternative means to define the locale besides the command line argument.

**Comment by dbaeumer** [comment] 2016-03-14 11:05
All we could do is a setting. But it can't be our settings store since this comes in to late.

**Comment by alexandrudima** [comment] 2016-03-14 11:10
I think putting on the backlog is a bit too optimistic, since this is a "breaking change".

If I have Windows locale set to German, VS Code always started up in English.

Starting with the March release, VS Code will start in German and it has no way to durably disable this behaviour.

**Comment by dbaeumer** [comment] 2016-03-14 12:21
I could argue that it is a feature that was missing :-). I understand your point but I think for the majority of the users the new behavior is correct. The reasons is:

- either your native language in non English and you configured your OS to your native language. Then you prefer the native language over English and VSCode will honor that with the March release
- your native language is non English but you configured the OS to English. Then VSCode starts in English.

I don't really see why a German would configure the OS to German and want to have VSCode in English. If his English is good enough for VSCode then I guess he would run the OS in English.

We can discuss tomorrow in the standup. Given that fixing this requires additional work/features I moved it to the backlog given the 'minor' value I see.

**Comment by bpasero** [comment] 2016-03-14 19:09
Accessing our settings from main side is easy, I commented on a duplicate of this one.

**Comment by dbaeumer** [comment] 2016-03-14 19:15
Dups #4170.

**Closed by dbaeumer** 2016-03-14 19:15 UTC
Labels: feature-request, i18n
