### ISSUE TITLE
Horizontal scroll should work on window instead of text...

### ISSUE THREAD

**Issue by Pritraj** [Microsoft/vscode#34677] opened 2017-09-20 06:00 UTC
Ref #32128

Here are GIF you asked for..

**Comment by Pritraj** [comment] 2017-09-20 06:00
![window_scroll](https://user-images.githubusercontent.com/18588781/30628999-216035c0-9df7-11e7-90ab-9587e571d39f.gif)
![textscroll](https://user-images.githubusercontent.com/18588781/30628998-215d0ff8-9df7-11e7-8144-897425477ffe.gif)

**Comment by alexandrudima** [comment] 2017-09-20 13:28
@Pritraj how do you "scroll" ?

 Do you perhaps use your laptop's built-in trackpad for horizontal scrolling ?

**Comment by Pritraj** [comment] 2017-09-21 05:04
Yes I am scrolling with my laptops touchpad.

**Comment by alexandrudima** [comment] 2017-09-21 10:32
Thank you for following up. Duplicate of #17476

**Closed by alexandrudima** 2017-09-21 10:32 UTC
Labels: editor, editor-core, needs more info

**Comment by BladeMF** [comment] 2017-11-13 12:31
Reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=784329&can=2&q=touchpad%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
