### ISSUE TITLE
"An error occurred" while authentication

### ISSUE THREAD

**Issue by jiwonz** [microsoft/vscode#226696] opened 2024-08-27 03:54 UTC
I tried to sign in with my github account using vscode on the vscode.dev website, and when I click Continue to my github account, it says I will be redirected, and a callback site that says Visual Studio Code shows Loading... for a moment and then An error occurred. The sign in doesn't proceed at all. I've been using it fine for a while and suddenly discovered this issue today. Is there a solution? I've already tried revoking vscode oauth and remote tunnel access on my github account and deleting them and retrying several times.

![Screenshot_20240827-125702](https://github.com/user-attachments/assets/34e29f10-f1b9-41e1-a1cb-97441394644e)

Thanks.

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by badien** [comment] 2024-08-27 10:33
i am same issue today, may be error occurs with vscode microsoft / github extension authentication not found with vscode.dev (website). Take note: using still vscode app normally with remote tunnel. Please check. Thanks

**Comment by jiwonz** [comment] 2024-08-27 10:51
![image](https://github.com/user-attachments/assets/20e7bae2-251e-4654-a202-1d07fdb75ec8)
I've tried in windows too but resulted in same issue.

**Comment by badien** [comment] 2024-08-28 02:51
the authentication extension has probably worked back on website today.

**Comment by TylerLeonhardt** [comment] 2024-08-28 04:48
Duplicate of https://github.com/microsoft/vscode/issues/226700

**Comment by joaomoreno** [comment] 2024-08-28 08:11
Merging with #226700

@jiwonz @badien Can you still reproduce?

**Closed by joaomoreno** 2024-08-28 08:11 UTC

**Comment by jiwonz** [comment] 2024-08-29 23:53
> Merging with #226700
> 
> @jiwonz @badien Can you still reproduce?

Sorry for late replying, This just got fixed 2 days ago.
