### ISSUE TITLE
Persistent outlines in non-selected text

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode#204656] opened 2024-02-07 21:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0-insider
- OS Version: macOs 14.3

Since the last insiders release I'm sometimes seeing outlined boxes around letters likes the one in the picture

<img width="763" alt="image" src="https://github.com/microsoft/vscode/assets/568775/a64af927-12cc-4a07-a2a0-8fb43cec810a">

They look like a text search, but they don't correspond to anything I have search or that is currently selected. I can still highlight some other text and that will cause the occurrences of that text to be outlined. The only way to get the outlines to disappear seems to be closing and reopening the tab with the file.

**Comment by andreamah** [comment] 2024-02-07 22:37
I'm wondering whether this is because those characters are ambiguous (they can look like another character). Does it disappear if you disable `editor.unicodeHighlight.ambiguousCharacters`?

**Comment by albireox** [comment] 2024-02-08 00:12
Still seeing it at times with `"editor.unicodeHighlight.ambiguousCharacters": "off"`. I've also seen it happen with text like `/data/gcam/` that doesn't seem like ambiguous characters.

**Comment by andreamah** [comment] 2024-02-20 21:57
@hediet I'm pretty sure that this is unicode highlighting based on the photo, so assigning you, but feel free to re-assign if this is incorrect.

**Comment by hediet** [comment] 2024-02-21 11:56
What does the hover say?

**Comment by albireox** [comment] 2024-02-21 16:12
As far as I can see it doesn't do anything when you hover over it.

**Comment by mattmc3** [comment] 2024-02-29 14:33
Seems like a bug in 1.87.0. After upgrading yesterday, this is happening to me as well and it's really annoying. Some symbol gets picked up as a thing to highlight, and no amount of hitting ESC or selecting something else, or scrolling away seems to unselect it. It's not related to unicode characters as one of the other comments suggests. With my theme, it showed up as an outline box like OPs screenshot, but running `/opt/homebrew/bin/code --disable-extensions .` to open Code without extensions shows it as a simple word highlight. By opening a side-by-side window of the same file, I can get what's highlighted to change, but I can't seem to get rid of it.

Here's a screenshot of a no-extension load where the `$HOME` symbol is stuck highlighted.

<img width="1143" alt="Screenshot 2024-02-29 at 9 25 24 AM" src="https://github.com/microsoft/vscode/assets/978625/14a37d02-8c6e-4b45-8ae1-b91c7f44b119">

```
Version Info:
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:51.279Z (1 day ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Comment by mattmc3** [comment] 2024-02-29 15:09
Here's a gif demonstrating the weird boxing behavior. As I said in the previous comment, having a split window can let me show the issue more clearly, but it happens in a single editor window.

![Weird VSCode bug](https://github.com/microsoft/vscode/assets/978625/ea3bb0b2-9ed9-46e0-a3e2-bc5fb58d7ea0)

**Comment by Yoyokrazy** [comment] 2024-03-01 18:14
Jumping in here to say that this is likely the same issue as #206486, and should be fixed in the latest insiders build. 

To confirm that this is the latest issue, did you have the setting `"editor.occurrencesHighlight"` set to `"off"`? This was the cause of stuck highlighting upon editors gaining focus as demonstrated in the gifs and images above

**Comment by Yoyokrazy** [comment] 2024-03-01 19:10
Thanks for the quick reply @albireox. Can you also confirm that this issue does not repro in the latest insiders?

**Comment by albireox** [comment] 2024-03-01 19:29
I've been trying for 10 minutes (with `editor.occurrencesHighlight: off`) in the latest insiders and cannot make it happen anymore, so I think it's indeed fixed there.

**Comment by Botan626** [comment] 2024-03-01 20:32
When will stable recovery release 1.87.1 come out?

**Comment by hediet** [comment] 2024-03-04 10:58
/duplicate https://github.com/microsoft/vscode/issues/206486,

**Closed by hediet** 2024-03-04 10:58 UTC
Labels: info-needed
