### ISSUE TITLE
Intellisense stops working

### ISSUE THREAD

**Issue by harishjus4u** [Microsoft/vscode#71760] opened 2019-04-05 05:29 UTC
Issue Type: <b>Bug</b>

Intellisense stops working, I have to frequently restart  VS code to make it work

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (5.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
dart-code|Dar|2.25.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
easy-icons|jam|0.3.1
vscode-styled-sort|joh|0.0.7
vscode-styled-components|jpo|0.0.26
code-beautifier|mic|2.2.1
csharp|ms-|1.18.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
java|red|0.42.1
Align|ste|0.2.0
language-stylus|sys|1.11.0
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.16.0
vscode-icons|vsc|8.4.0
glean|wix|4.10.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-04-05 07:08
Please describe how to reproduce the issue

/needsMoreInfo

**Comment by kanitsharma** [comment] 2019-04-05 09:23
@mjbvz Intellisense and go to definition both aren't working since after the update.

**Comment by nguyenkhois** [comment] 2019-04-05 11:28
I have the same problem today when VSCode update to version 1.33. I have been downgrading to version [1.32.3](https://code.visualstudio.com/updates/v1_32) and stop the option [automatic update checking](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates). It works fine while we are waiting for the hot fix from the VSCode team.

**Comment by kolengri** [comment] 2019-04-05 11:58
Same problem after update

**Comment by optimistiks** [comment] 2019-04-05 12:11
Same problem, however it also reproduces on 1.32 if I select the project Typescript version (3.4) instead of internal VSCode version (3.3).

**Comment by gonzofish** [comment] 2019-04-05 13:49
I was looking through the extension host log and saw and error that reads:

```
[error] Error: TypeScript Server Error (3.4.1)
Debug Failure. Expected 1 === 2. Registered script kind should match new script kind. <path to file>
```

And a bunch of:

```
[error] Error: TypeScript Server Error (3.4.1)
Debug Failure. Expected <# greater than 190> <= 190
```

Not sure if this helps

**Comment by mjbvz** [comment] 2019-04-05 19:08
Duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for possible workarounds

If that doesn't solve the issue for you, please open a new issue

**Closed by mjbvz** 2019-04-05 19:08 UTC
Labels: needs more info, new release
