### ISSUE TITLE
[BUG] HTML attribute suggestions: Snippet session does not have end-position set

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#33147] opened 2017-08-25 11:18 UTC
- VSCode Version: In Video
- OS Version: Windows 8.1 and Linux Ubuntu 17.04 Gnome

Steps to Reproduce:

https://www.youtube.com/watch?v=vMqY3s4KiW0&ab_channel=GabrielMlocik

Reproduces without extensions: **Yes**/No

---

Popis:

Vo verzii 1.11 funguje všetko korektne, v prípade potvrdenia Emmet alebo "suggestions" kurzor presunie do zvýraznenej oblasti (cielový kurzor).

Ale v novších verziách to už nefunguje, čím novšia verzia tým horšie... napríklad potvrdenie emmet vytvorí nový riadok namiesto potvrdenia. Ručne je potreba presunúť kurzor do správnej pozície. V prípade niektorých suggestií to radí nezmysli, ako napr. "<img <source>".

Prosím opravte to, ať to funguje ako vo verzii 1.11, prípadne ešte lepšie to fungovalo v staršej verzii kde aj po "<script src=""><|" suggescia bola </script>

---

[translate to EN from CZ/SK] : [by Google Translator]

description:

In version 1.11, everything works correctly, in the case of Emmet confirmation or "suggestions", the cursor moves to the highlighted area (target cursor).

But in newer versions it does not work anymore, the newer version the worse ... for example emmet confirmation creates a new line instead of confirmation. You need to manually move the cursor to the correct position. For some suggestions, it does not seem like, "<Img <source>".

Please fix it to work as in version 1.11, or even better it worked in an older version where even after "<script src =" "> <|" Suggestion was </ script>

**Comment by vvs** [comment] 2017-08-25 12:59
@Mlocik97-issues you have two ways of solving this depending on your style of working with the sources.

1. Embrace our Emmet overlords and use Emmet extensively. That way, your three lines from the video could be written very fast and conventient with Emmet:
* `link` and then Enter
* `img` and then Enter
* `script:src` and then Enter

2. If you prefer the "old" way of editing the HTML files, with brackets and manually inserting the closing tags, etc, you could adjust the following setting for the Emmet, so that Emmet will be less noisy with its suggestions:

`"emmet.showAbbreviationSuggestions": false`

**Comment by ramya-rao-a** [comment] 2017-08-25 18:17
@Mlocik97-issues 

In your video, when you were using the old version, nothing you did was emmet. That was html completions.

Looks like you are not an emmet user and the new emmet features are getting in your way of doing html. 

For old behavior set `emmet.triggerExpansionOnTab` to `true` and `emmet.showExpandedAbbreviation` to `never`.

**Comment by Mlocik97-issues** [comment] 2017-08-25 19:07
Skúsil som to, ale nefunguje to ani s tým nastavením.

---

[translate to EN from CZ/SK] : [by Google Translator]

I tried it, but it does not work with the settings.

**Comment by Mlocik97-issues** [comment] 2017-08-25 19:10
Chcem aby když použiju sugesciu a doplním value, potvrdím aby následne presunlo kurzor na správnu pozíciu. Ako v 1.11 verzi.

---

[translate to EN from CZ/SK] : [by Google Translator]

I want to confirm that when I use the suggestion and the value to add it, it will then move the cursor to the correct position. As in version 1.11.

**Comment by ramya-rao-a** [comment] 2017-08-25 21:56
Ok I think I understand what you are saying.

In old vs code

1. Type `<script s`
2. `src` is one of the suggestions, choose it
3. You now have `<script src="|"`
4. Enter some text, and press ENTER, the cursor goes to the end of `<script src="sometext"`

In the latest vscode, after pressing ENTER in Step 4 a new line is entered instead of cursor going to the end of `<script src="sometext"`

This is not due to Emmet
The suggestion for `src` comes from the html extension.

@aeschli Looks like the `src` suggestion for `<script s` was adding a snippet which had the final tabstop at the end of `src=""`
Are we not using snippet for attribute completions anymore?

**Comment by Mlocik97-issues** [comment] 2017-08-25 22:10
ramya-rao-a

áno presne tak, když som použil sugesciu a následne som doplnil value a zmáčknul enter, kurzor presunulo do zvýraznenej časti (svetlá neblikajúca | ).

A ospravedlňujem sa za nedorozumenie, moja Angličtina funguje len skrz prekladače.

---

[translate to EN from CZ/SK] : [by Google Translator]

Yes exactly when i used the suggestion and then I added the value and pressed the enter, the cursor moved to the highlighted part (the blinking lights).

And to apologize for misunderstanding, my English works only through translators.

**Comment by aeschli** [comment] 2017-08-31 12:22
The HTML completion proposal has the insertText 'src=\"$1\"'.

**Closed** 2017-09-04 13:00 UTC
Labels: bug, snippets

**Comment by ramya-rao-a** [comment] 2017-09-04 18:34
@jrieken Can we have this for August?

**Comment by jrieken** [comment] 2017-09-05 06:57
Yeah, I don't think is is caused by a recent change and in there since a few milestones but the code change is small and low risk

**Comment by ramya-rao-a** [comment] 2017-09-05 18:39
Thanks @jrieken 

@Mlocik97-issues Please try out our latest Insiders from https://code.visualstudio.com/insiders or wait for the release of VS Code 1.16

Your new workflow would be
1. Type `<script s`
2. `src` is one of the suggestions, choose it
3. You now have `<script src="|"`
4. Enter some text, and press TAB instead of ENTER, the cursor goes to the end of `<script src="sometext"`

You need to use TAB instead of ENTER here due to https://github.com/Microsoft/vscode/issues/5427
