### ISSUE TITLE
VS code opens previously closed files at startup when turned of by OS (kubuntu)

### ISSUE THREAD

**Issue by petermilan** [Microsoft/vscode#45380] opened 2018-03-09 06:08 UTC
- VSCode Version:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:10:15.949Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Steps to Reproduce:

1.Open VS code
2.Close previously opened files 
3. Open new files 
3. Shutdown your OS without closing VS code
4.Start OS and VS code

Issue is that VS code still show files I previously closed (And also all settings like last searched path etc.)

**Comment by bpasero** [comment] 2018-03-09 06:17
/duplicate of https://github.com/Microsoft/vscode/issues/12058

**Closed** 2018-03-09 06:17 UTC
Labels: *duplicate, workbench-state
