### ISSUE TITLE
collapse block of code

### ISSUE THREAD

**Issue by mukesh100592** [Microsoft/vscode#53940] opened 2018-07-10 08:53 UTC
Issue Type: <b>Feature Request</b>

In earlier versions of VS code, the cases of switch blocks were collapsible. But now it does not collapse.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:11.248Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by mukesh100592** [comment] 2018-07-10 09:05
Even collapse button[-] and Expand button[+] is not visible.

**Comment by mjbvz** [comment] 2018-07-10 21:36
Which language? Please share a code example

**Comment by romanlex** [comment] 2018-07-13 20:04
I can confirm in jsx collapse not working
button is not visible
<img width="611" alt="screen shot 2018-07-13 at 23 03 13" src="https://user-images.githubusercontent.com/3369304/42711588-190a9210-86f1-11e8-946b-fe43de06765f.png">

**Comment by mjbvz** [comment] 2018-07-16 19:44
@romanlex That is a duplicate of https://github.com/Microsoft/TypeScript/issues/23273

I'm assuming this issue is for js/ts and closing it as a duplicate of https://github.com/Microsoft/TypeScript/issues/23380

**Closed by mjbvz** 2018-07-16 19:44 UTC
Labels: needs more info
