### ISSUE TITLE
Support showing KaTeX in jsdoc

### ISSUE THREAD

**Issue by MuTsunTsai** [microsoft/vscode#180468] opened 2023-04-21 03:31 UTC
In VS Code we can already use most of the Markdown syntax in jsdoc (and will be displayed accordingly on hovering over symbols), and we can also use KaTeX in standalone Markdown documents, so it makes sense to combine both and allowing KaTeX to render in hovering docs, instead of this:

![image](https://user-images.githubusercontent.com/39870664/233534370-fbad9324-56e7-4421-95d8-e0b2edcb42aa.png)

**Comment by mjbvz** [comment] 2023-04-24 18:03
Duplicate of #129933. Not something we plan on adding natively at this time

**Closed by mjbvz** 2023-04-24 18:03 UTC
