### ISSUE TITLE
Visual Studio Code doesn't open when there is an Admin VSCode open

### ISSUE THREAD

**Issue by jayongg** [Microsoft/vscode#7153] opened 2016-06-02 18:05 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:
1. launch a command line with admin privileges
2. from this command line, type "code .". Observe VS Code open
3. Launch a command line without admin privileges
4. from this command line, type "code .". 
Expected:
VS Code opens in a new window

Actual:
Nothing, no error message, no indication of anything.

**Comment by Tyriar** [comment] 2016-06-02 18:23
Not sure there's a way around this, at least an error message would be good though.

**Comment by jayongg** [comment] 2016-06-02 18:47
Thanks. Is ut not possible to just launch a separate low privilege instance?

**Comment by Tyriar** [comment] 2016-06-02 18:50
I don't think so given the way that Electron works, @bpasero will probably know more on the subject.

**Comment by bpasero** [comment] 2016-06-03 04:49
No there is always just one main process. I think the real issue here is that you are not able to start an instance as admin and not as admin. I wonder if we should just allow to open 2 instances if one is admin and one is not and they just run at the same time side by side. This would however require 2 distinct data directories and extension directories to not cause trouble.

**Comment by bpasero** [comment] 2016-06-03 04:50
See also: https://github.com/Microsoft/vscode/issues/6560

**Comment by Tyriar** [comment] 2016-07-05 17:52
Closing as duplicate of https://github.com/Microsoft/vscode/issues/6560

**Closed by Tyriar** 2016-07-05 17:52 UTC
Labels: bug
