### ISSUE TITLE
Different behaviour of Ctrl+K + Ctrl+C

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#12801] opened 2016-09-27 17:43 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 10 Version 1607 OS Build: 14393.187

Steps to Reproduce:

1. Doing Ctrl+K + Ctrl+C (for commenting) in line 14 in the end, comments the code in a different way. 
![1](https://cloud.githubusercontent.com/assets/16834561/18885138/00e36302-8508-11e6-8bf4-b3d042604452.png)

**Comment by aeschli** [comment] 2016-10-17 15:25
duplicate of #11081

**Closed by aeschli** 2016-10-17 15:25 UTC
