### ISSUE TITLE
Output pane silently truncates start of C++ build error output

### ISSUE THREAD

**Issue by nitrologic** [Microsoft/vscode#24556] opened 2017-04-12 00:37 UTC
- VSCode Version: 1.11.1
- OS Version: Ubuntu 64

Steps to Reproduce:

1. create an error in your c++, leave out a squiggly bracket say
2. once the build has generated 19849 lines note note how it silently truncates from the start (not the end) and does not bring up a warning or help me make the plainly inadequate OUTPUT window buffer bigger

**Comment by isidorn** [comment] 2017-04-12 08:46
This is by design of the output buffer, we always truncate for performance reasons (some extensions can spam the output channel leading to bad vscode behavior).
We are truncating from the start since the last received output is the freshest and should be shown.

What solution are you proposing to improve this experience?
If there are some good ideas I can leave this as a feature request, otherwise I plan to close it as-designed.

Thanks

**Comment by nitrologic** [comment] 2017-04-12 21:05
We are truncating from the start since the last received output is the freshest and should be shown.

In a c++ build environment this statement is not true.

**Comment by nitrologic** [comment] 2017-04-12 21:06
I am also suggesting in my issue detail that you suggest how I make this buffer bigger, either using helpful ui or here on github.

**Closed** 2017-11-17 17:56 UTC
Labels: *out-of-scope, feature-request, output

**Comment by nitrologic** [comment] 2017-11-19 20:52
I don't think it is adequate that the produce silently truncate output based on an undefined limit.
