### ISSUE TITLE
"scss.lint.unknownProperties" : "ignore" does not work on latest insiders build

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#7802] opened 2016-06-17 07:45 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Using an unknown property (working with the Lost grid) - such as lost-column.
2. Set "scss.lint.unknownProperties" to "ignore".
3. VSCode complains about lost-column being an unknown property.

This occurs in the recent builds and I'm fairly sure is as a result of the recent refactor - this does not occur in the main.

Just as a side note - it may be of value to teach VSCode about certain "unknown" properties - lost grid is an example, in a similar way to how we teach VSCode or other editors about json schemas, especially with post-css plugins becoming a bigger deal.

**Comment by aeschli** [comment] 2016-06-17 14:17
duplicate of #7777

**Closed by aeschli** 2016-06-17 14:17 UTC
Labels: bug, css-less-sass
