### ISSUE TITLE
vscode-insiders embed terminal behavior since 1.9.0

### ISSUE THREAD

**Issue by soyuka** [Microsoft/vscode#19055] opened 2017-01-23 16:39 UTC
Hi!

I've an issue with latest update.

```
Version 1.9.0-insider
Commit 882244ea24cb0b89a9a0c6c649c8f857fb0bc408
Date 2017-01-23T07:03:07.900Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

OS: Debian 8

Steps to Reproduce:

1. Launch `vim` in the embed terminal

Used to work before `1.9.0`. Now I can't do my `git commit` command anymore because it does open the `$EDITOR`. 

Nano, less etc. are still working. Therefore, I think it has to do with my vim configuration. What are recent changes that could affect this? Note that `vi` prints black on black.

**Comment by mousetraps** [comment] 2017-01-24 01:07
Sorry to hear that - can't reproduce this on OSX or Windows, but please welcome the one, the only, linux + terminal wizard.... @Tyriar!!! 👏 🎩 (hope I didn't set expectations too high there)

**Comment by mousetraps** [comment] 2017-01-24 01:09
Also another thought - you mentioned black on black text - does changing the theme impact anything at all?

Potentially related: https://github.com/Microsoft/vscode/issues/18544

**Comment by Tyriar** [comment] 2017-01-24 06:44
This was actually a bug in today's Insiders due to a refactor in the terminal's parser, it should be fixed in tomorrow's build. If you open dev tools you should see an error related to `InputHandler.setMode`. https://github.com/Microsoft/vscode/issues/19074

As for the black on black text, not sure what's going on there but you should be able to open dev tools and inspect the element to see which class is doing the coloring, that should help answer whether it's an issue with your config or vscode.

**Closed by Tyriar** 2017-01-24 06:44 UTC
Labels: integrated-terminal, needs more info

**Comment by soyuka** [comment] 2017-01-24 08:37
Has been fixed! Thanks!
