### ISSUE TITLE
Words position from terminal panel is incorrect

### ISSUE THREAD

**Issue by TianyiLi** [Microsoft/vscode#25185] opened 2017-04-22 10:06 UTC
- VSCode Version:1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. 
![1492855528537](https://cloud.githubusercontent.com/assets/15644242/25303477/5017c000-2786-11e7-8408-9bd3b5999731.jpg)

2.

**Comment by mjbvz** [comment] 2017-04-22 19:22
Duplicate of #24941 / #19665

**Closed by mjbvz** 2017-04-22 19:22 UTC
Labels: duplicate
