### ISSUE TITLE
Markdown Language Features fails to open the MD file in WSL2

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#130830] opened 2021-08-14 15:51 UTC
Issue Type: <b>Bug</b>

When running VS Code from WSL2, the built-in extension fails to locate the MD file inside the Ubuntu installation and throws an error message "Could not open file:///path/to/markdown-file.md". Problem might be because it is attempting to read the file from the Windows file system.

![image](https://user-images.githubusercontent.com/6047296/129452026-3ff5f65f-d94f-4b1d-ac72-09e23cffe0f9.png)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.94GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/adtc/shared-login-php --remote=wsl+Ubuntu --crash-reporter-id 38c0c73b-2ac9-41c1-8092-f95b3478669c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|Memory (System)|12.42GB (11.62GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.6.0
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
vscode-liquid-snippets|kil|2.0.2
remote-wsl|ms-|0.56.5
language-liquid|nei|0.1.1
EmberES6Snippets|pha|2.3.3
vscode-jsp|pth|0.0.3
vscode-icons|vsc|11.6.0
vscode-ruby|win|0.28.0
rails-db-schema|aki|0.2.3
rails-routes|aki|0.6.0
ng-template|Ang|12.1.1
solargraph|cas|0.23.0
gitignore|cod|0.7.0
vscode-ruby-test-adapter|con|0.9.0
githistory|don|0.6.17
gitlens|eam|11.4.1
vscode-pull-request-github|Git|0.26.0
vscode-test-explorer|hbe|2.20.4
rails-fast-nav|jem|1.3.6
vscode-rufo|jnb|0.0.4
endwise|kai|1.4.2
test-adapter-converter|ms-|0.0.10
vscode-thunder-client|ran|1.7.1
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by mjbvz** [comment] 2021-08-16 21:40
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, how are you opening the file?

**Comment by ADTC** [comment] 2021-08-16 21:51
1. Can't check insiders build right now.
2. I launch VS Code from WSL2 Ubuntu's Bash shell using `code .` and then I try to open the file in the WSL2 connected VS Code instance.

**Comment by ADTC** [comment] 2021-11-05 19:11
I wish I could test this further for you but I don't seem to have the time. If you can't reproduce it on your end, feel free to close.

**Comment by mjbvz** [comment] 2021-11-19 23:45
Ok, closing since we haven't seen other reports of this

**Closed by mjbvz** 2021-11-19 23:45 UTC
Labels: needs more info, markdown
