### ISSUE TITLE
"Update imports" action on file rename causes syntax errors throughout project

### ISSUE THREAD

**Issue by briman0094** [Microsoft/vscode#55156] opened 2018-07-26 14:54 UTC
I just tried out the new "Update Imports" feature when moving a file for the first time, and it broke the imports in almost every file in my (fairly large) project. I now have to go undo each file individually and make sure I only undo the imports. It seems like instead of just updating the imports for the particular files that were moved, VS Code attempted to make every local import a relative import instead of absolute (my project is configured to use absolute import paths even for local files, as both TypeScript and Webpack allow this), but it also created a syntax error on each of these. It touched files that have never referenced the moved file as well.

The files that were moved (two of them) were both React components, but some of my non-React utility files were changed as well. For example, one of the files changed is `PaperUtils.ts` which provides some Paper.js-specific utilities. One of the imports changed in this file was a reference to `sketch/util/Constants`, which is a local file. It seems like the imports were changed in two steps, as I can Ctrl+Z twice in each of the changed files.

The original import was `import { Zoom, Layers } from "sketch/util/Constants";`
In the first step, it was changed to `import { Zoom, Layers } from "../Constants";`, which is a valid relative import for the same file.
In the second step, it was changed to `import { Zoom, Layers } from "../Constants`. The last quote of the import, as well as the trailing semicolon, were deleted.

This happened in 70 files in my project and almost every single import in these files.

- VSCode Version: 1.25.1
- OS Version: Windows 10 build 1709

Steps to Reproduce:

1. Have project with multiple `.ts` and `.tsx` files
2. Have TypeScript configured to use absolute imports instead of relative
3. Move a file in the project and choose "Yes" when asked if imports should be updated

Does this issue occur when all extensions are disabled?: Unsure; I'm already having to spend a significant amount of time weeding out these import changes from my actual file changes in Git to undo the syntax errors and don't have the time to redo this with no extensions.

**Comment by mjbvz** [comment] 2018-07-26 18:01
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-26 18:01 UTC
Labels: javascript
