### ISSUE TITLE
Missing autocomplete for TypeScript

### ISSUE THREAD

**Issue by Majirefy** [Microsoft/vscode#30707] opened 2017-07-14 13:36 UTC
- VSCode Version: 1.14.1 (1.14.1)
- OS Version: macOS 10.12.5 (16F2104)

When editing *.ts files, code autocomplete misses many hints like datatypes, const, let, etc.
 
Steps to Reproduce:
1. In a TypeScript file, type some code.
2. like below:
<img width="827" alt="2017-07-14 9 34 11" src="https://user-images.githubusercontent.com/3023607/28214284-362cdee0-68dc-11e7-866a-924b10bfb286.png">
There should be const instead of ctor(constructor)

<img width="355" alt="2017-07-14 9 35 09" src="https://user-images.githubusercontent.com/3023607/28214308-54355548-68dc-11e7-9fc0-8fe2626630f2.png">
No hint for boolean, or number, or string.

In 1.13, everything is fine.

Plus, when I refer to developer tools, there are errors:

> [Extension Host] Activating extension `vscode.typescript` failed:  [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript
> h.logExtensionHostMessage @ extensionHost.ts:320

<img width="912" alt="2017-07-14 10 29 09" src="https://user-images.githubusercontent.com/3023607/28216337-df90f0be-68e3-11e7-9814-87ccbd7c122a.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-14 18:56
Duplicate of #30716

**Closed by mjbvz** 2017-07-14 18:56 UTC
Labels: new release, typescript
