### ISSUE TITLE
Code is slow to open - usually 10 - 20 seconds

### ISSUE THREAD

**Issue by garethc123** [Microsoft/vscode#59784] opened 2018-10-01 21:00 UTC
Issue Type: <b>Performance Issue</b>

I find that Code is /very/ slow to open sometimes. For example, I have a simple text document on the desktop. When I double click it to open it in Code, it can take anywhere from 10 to 20 seconds before the file is acutal open. The file isn't very big either - maybe 300 lines, 500 words, white quite a lot of white space. Once open it performs very well...

Is there any info I can give you that will help?

Please note that this slowness only started to happen some 6 weeks ago. Prior to a certain build everything opened very quickly (you're going to ask if I recall which version started the slow trend... alas, I don't).

VS Code version: Code - Insiders 1.28.0-insider (83d5a29433d7f576b59db8019575a0c9dc78a967, 2018-10-01T13:31:33.485Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (4.60GB free)|
|Process Argv|C:\Users\crawfog\Desktop\New Text Document.txt|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    81	 14612	code-insiders main
    0	   157	 11760	   window (New Text Document.txt - Visual Studio Code - Insiders)
    0	    55	 19260	     extensionHost
    5	    42	 19108	       electron_node server.js 
    1	    71	 11876	   window (Issue Reporter)
    0	   114	 16588	   gpu-process
    0	    67	 19368	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-spell-checker|str|1.6.10

</details>

**Comment by ipip2005** [comment] 2018-10-01 22:16
Duplicate of #56644?

**Closed** 2018-10-02 04:57 UTC
Labels: *duplicate, insiders, perf, perf-startup
