### ISSUE TITLE
cannot update Node debug

### ISSUE THREAD

**Issue by MAXMASTER001** [Microsoft/vscode#67486] opened 2018-12-03 19:14 UTC
cannot update Node debug. I think this gievs me the error "Debug adapter process has terminated unexpectedly (exit code: 1)"

![image](https://user-images.githubusercontent.com/11816983/49395763-748e7800-f748-11e8-9c78-287f9085cf21.png)

**Comment by weinand** [comment] 2019-01-29 21:06
@sandy081 We'll have to investigate this issue. More users are seeing this.

**Comment by sandy081** [comment] 2019-04-01 12:39
Duplicate of #66774

**Closed** 2019-04-01 12:39 UTC
Labels: *duplicate, bug, extensions
