### ISSUE TITLE
[VSCode insider] Seti icons are smaller than normal

### ISSUE THREAD

**Issue by nicolaerario** [microsoft/vscode#234121] opened 2024-11-18 17:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

- VS Code Version: 
Version: 1.96.0-insider
Commit: 0c9dd26823dc38dd59d6240e1b6698add43d942c
Date: 2024-11-18T05:05:45.838Z
Electron: 32.2.3
ElectronBuildId: 10561341
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

Steps to Reproduce:

1. Update to 1.96.0-insider version
2. Make sure Seti (vs-seti) icon theme is activated
3. CMD + B to open the file tree

<details><summary>Screenshot details</summary>
<p>

VSCode
![Image](https://github.com/user-attachments/assets/2bf7f300-c8ec-41ab-8df3-351f972b2cfd)

VSCode `insider` version
![Image](https://github.com/user-attachments/assets/96dc2e6e-d01c-4436-99a9-0756ba502453)

</p>
</details>

**Comment by gjsjohnmurray** [comment] 2024-11-18 18:26
/duplicate of https://github.com/microsoft/vscode/issues/234080 which will be fixed in tomorrow's Insiders

**Closed** 2024-11-18 18:27 UTC
Labels: *duplicate
