### ISSUE TITLE
Allow creating file/folder in simple file dialog

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#196693] opened 2023-10-26 09:14 UTC
1. Enable `files.simpleDialog.enable`
2. <kbd>Ctrl/Cmd O</kbd> to use it to open a file/folder
3. Type in a name which doesn't exist

I'd love that it would let me create a folder/file right from that flow. I usually end up closing it, opening Finder, creating the folder myself, opening the dialog again and navigating to the new folder.

<img width="620" alt="image" src="https://github.com/microsoft/vscode/assets/22350/08e8a7ca-e68a-4cc4-809d-575ec081434f">

**Comment by gjsjohnmurray** [comment] 2023-10-26 09:40
Related to #158994

**Comment by alexr00** [comment] 2023-10-26 09:53
When saving, you can create a folder by adding a path segment that doesn't exist.

**Comment by babakfp** [comment] 2024-01-14 10:45
I think the person who implemented the `files.simpleDialog.enable` feature, didn't care about the feature and they treated it as just a task. Now because of that, we have a feature that isn't usable and it's going to take years to get fixed. Good job.

**Comment by alexr00** [comment] 2024-12-10 15:53
Duplicate of https://github.com/microsoft/vscode/issues/186511

**Closed by alexr00** 2024-12-10 15:53 UTC
Labels: feature-request, simple-file-dialog
