### ISSUE TITLE
Opening explorer viewlet opens the selected file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68946] opened 2019-02-19 02:10 UTC
I thought https://github.com/Microsoft/vscode/issues/68227 was about this, but the OP says that one's fixed.

- Select a file in the explorer
- Close all open files
- Collapse all open folders in the viewlet
- Open any other viewlet
- Open the explorer
- The previously selected file is opened again, and folders are expanded to reveal the selected file (I think that's what #68227 was saying)

I think that just opening the explorer should not cause a file to be opened.

**Comment by karevn** [comment] 2019-02-19 09:00
I've got this issue too, same steps to reproduce. 
OS: macOS, 
Version: 1.31.1

**Comment by Tyriar** [comment] 2019-02-25 22:05
This doesn't appear to be fixed:

1

![image](https://user-images.githubusercontent.com/2193314/53371892-55962100-3906-11e9-868d-1e90df9ae506.png)

2

![image](https://user-images.githubusercontent.com/2193314/53371906-5c249880-3906-11e9-8452-1781f7b7a08f.png)

3

![image](https://user-images.githubusercontent.com/2193314/53371920-63e43d00-3906-11e9-922e-404f5ea75f4a.png)

**Comment by isidorn** [comment] 2019-02-26 10:50
This is fixed. Make sure you do not have anything selected in the explroer when you open the other viewlet (which you get by following the exact steps @roblourens provided).
What you are showing is how vscode stable always behaved. If you left something selected we reopen when explorer gets opened, Thus closing

**Comment by roblourens** [comment] 2019-02-26 17:15
@Tyriar how did you get in state 1? When I close the last file I lose my focus and selection in the tree and I see the same in an old release.

**Comment by Tyriar** [comment] 2019-02-26 18:09
This setting is causing the behavior for me:

```
"explorer.autoReveal": false
```

This is because the selection remains untouched when closing files (which is a good thing), it's just a bit weird that opening the explorer will open the selected file.

**Comment by isidorn** [comment] 2019-02-27 08:44
That is behavior which we always had in stable.
Closing as designed.
Will only fix if more people complain.

**Closed by isidorn** 2019-02-27 08:44 UTC
Labels: bug, file-explorer

**Comment by RMacfarlane** [comment] 2019-02-27 20:47
Marking as verified since behavior now matches stable, but I agree that having the selected file open with `"explorer.autoReveal": false` is strange
