### ISSUE TITLE
Ruler disappears after reloading window with zoomLevel < 0

### ISSUE THREAD

**Issue by WesleyYue** [Microsoft/vscode#38901] opened 2017-11-21 19:44 UTC
- VSCode Version: Version 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Set a ruler in user settings
2. Zoom out
3. Reload window

Any change to the ruler length fixes it temporarily.

Reproduces without extensions: Yes

Related: #9634

**Comment by alexandrudima** [comment] 2017-11-22 09:53
Duplicate of #38656

**Closed by alexandrudima** 2017-11-22 09:53 UTC
Labels: editor, editor-core
