### ISSUE TITLE
Duplicate items in contextmenu (TypeScript)

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#44850] opened 2018-03-01 16:11 UTC
- VSCode Version: 1.20.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Create a TypeScript project
2. Create an abstract class
3. Create a class that inherits from the abstract class above.
3.1 The IDE should provide you with a hint
4. Click on the hint and observe the context menu
[Please see screenshot here](https://truesoftware.net/blend/contextmenu.png)

**Comment by mjbvz** [comment] 2018-03-01 19:38
Duplicate of #43181

**Closed by mjbvz** 2018-03-01 19:38 UTC
Labels: javascript
