### ISSUE TITLE
\r\n line endings confuse automatic language detection

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129730] opened 2021-07-29 00:37 UTC
Testing #129436

![image](https://user-images.githubusercontent.com/19276747/127413410-f15afd3d-14bf-4948-9f58-151d21fe3ffe.png)

```
public class Alphabet {

    public static void main(String[] args) {

        char c = '*';

        if( (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
            System.out.println(c + " is an alphabet.");
        else
            System.out.println(c + " is not an alphabet.");
    }
}
```

![image](https://user-images.githubusercontent.com/19276747/127413499-f2cf2d8e-04a7-497a-be98-08b34ada681d.png)

```
public class Reverse {

  public static void main(String[] args) {
    String sentence = "Go work";
    String reversed = reverse(sentence);
    System.out.println("The reversed sentence is: " + reversed);
  }

  public static String reverse(String sentence) {
    if (sentence.isEmpty())
      return sentence;

    return reverse(sentence.substring(1)) + sentence.charAt(0);
  }
}
```

**Comment by isidorn** [comment] 2021-07-29 07:56
Hopefully when we fine tune our heuristics towards popular vscode languages cases like this will become better.

**Comment by TylerLeonhardt** [comment] 2021-07-29 16:01
Yeah this is a perfect case for when we can say that in VS Code the user is likely messing with untitled Java than Groovy. This is a duplicate of https://github.com/microsoft/vscode/issues/129596

**Comment by TylerLeonhardt** [comment] 2021-07-29 16:01
Oh also cc @yoeo for model feedback.

**Comment by yoeo** [comment] 2021-07-29 20:11
Thanks for the feedback.

Actually both examples are actually as Java code by the base Tensorflow model:
```sh
echo 'public class Alphabet {

    public static void main(String[] args) {

        char c = '*';

        if( (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
            System.out.println(c + " is an alphabet.");
        else
            System.out.println(c + " is not an alphabet.");
    }
}' | guesslang -p 
Language name       Probability
 Java                 48.56%
 Groovy               12.76%
 C#                    8.12%
 R                     2.73%
 Visual Basic          2.70%
 ...
```
and
```sh
echo 'public class Reverse {

  public static void main(String[] args) {
    String sentence = "Go work";
    String reversed = reverse(sentence);
    System.out.println("The reversed sentence is: " + reversed);
  }

  public static String reverse(String sentence) {
    if (sentence.isEmpty())
      return sentence;

    return reverse(sentence.substring(1)) + sentence.charAt(0);
  }
}' | guesslang -p
Language name       Probability
 Java                 41.81%
 Groovy               16.90%
 C#                    7.85%
 Dart                  5.42%
 Rust                  3.47%
 ...```

**Comment by TylerLeonhardt** [comment] 2021-07-29 20:19
Interesting discovery @yoeo. I wonder what could have happened between that conversion that might have changed this. 
cc @pyu10055

**Comment by isidorn** [comment] 2021-07-30 07:39
@TylerLeonhardt I think we should file an issue in the tensorflow repo. Let me know if you would like me to do that. Thanks

**Comment by TylerLeonhardt** [comment] 2021-07-30 17:51
So I actually gave this a go and I can't seem to repro the groovy behavior.  @claudiaregio / @isidorn can you give it a test again?

The percentages I got were around the same as @yoeo's guesslang.

![image](https://user-images.githubusercontent.com/2644648/127689533-ae919439-316f-48cb-8aef-660a1abff524.png)

Interestingly, it's not the exact probability as @yoeo's numbers... that's when I noticed something... if I put the `public class` on a new line (thus starting out with a new line in the file, then the confidence changes:
![image](https://user-images.githubusercontent.com/2644648/127689770-0369c609-a2b6-4143-8026-149319f61176.png)
... it actually would impact if the Untitled file on our case because our threshold is 20%
So the other test I ran was having tabs instead of spaces... and the results are different too!
![image](https://user-images.githubusercontent.com/2644648/127690169-22b6cbee-130b-4da5-9c80-615621645490.png)

So based on my testing, this appears to be working as expected. I'm not entirely sure how @claudiaregio ended up in this groovy state... 

@yoeo what are your thoughts on the whitespace effecting the results? To me I feel like whitespace shouldn't really matter... or it should be normalized somehow...

**Comment by TylerLeonhardt** [comment] 2021-07-30 18:25
Oh shoot I figured it out... I can repro this on Windows... why? Because of the line endings! If I switch the line endings to `\r\n` instead of just `\n` Groovy ends up being the top result!

@yoeo I think this is something that should probably be figured out in the model... what do you think?

**Comment by yoeo** [comment] 2021-08-01 12:02
>  If I switch the line endings to \r\n instead of just \n Groovy ends up being the top result!

Nice guess, I understand the issue now :-)

The model doesn't know about `\r\n` line endings because they where replaced with `\n` during training by Python libraries (see `newline` option in https://docs.python.org/3/library/functions.html#open ).

I propose that you also replace `\r\n` line endings with `\n` before the inference.

**Comment by isidorn** [comment] 2021-08-02 07:54
@TylerLeonhardt Good catch 
Since we are classifying based on 100 000 characters at most doing a replace should be fast.

Let me reopen this so @TylerLeonhardt considers @yoeo suggestion.

**Comment by yoeo** [comment] 2021-08-03 10:04
[Maybe off-topic]

The is an other possible source of confusion.

The model was trained with Unicode strings, UTF-8 encoded according to Tensorflow documentation https://www.tensorflow.org/text/guide/unicode
So if you compute the probabilities using strings with a different character encoding you can get strange results.

**Comment by TylerLeonhardt** [comment] 2021-08-06 20:54
Fixed in https://github.com/microsoft/vscode-languagedetection/commit/88445fadeb56b364d37707f62dac4921d0abecb1

**Closed by TylerLeonhardt** 2021-08-06 20:54 UTC

**Comment by TylerLeonhardt** [comment] 2021-08-06 20:55
verification...on Windows, paste this in an untitled editor:

```java
public class Reverse {

  public static void main(String[] args) {
    String sentence = "Go work";
    String reversed = reverse(sentence);
    System.out.println("The reversed sentence is: " + reversed);
  }

  public static String reverse(String sentence) {
    if (sentence.isEmpty())
      return sentence;

    return reverse(sentence.substring(1)) + sentence.charAt(0);
  }
}
```

it should guess Java not Groovy.
