### ISSUE TITLE
Left Panel - multiple Add Folder buttons

### ISSUE THREAD

**Issue by cyber-developer** [microsoft/vscode#94662] opened 2020-04-08 06:32 UTC
Issue Type: <b>Bug</b>

1. Open visual studio code without any active project or folder in it.
You will see Clone Repository and Add Folder buttons in second accordion item.
2. Now if you open some folder and then proceed remove this folder. Then you will again see Clone Repository button but "2" Add Folder buttons.

And "Add Folder" buttons keeps on adding extra clones if you repeat step 2.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (12.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vscode-eslint|dba|2.1.2
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.1.1
terminal|for|0.0.10
beautify|Hoo|1.5.0
vscode-react-native|msj|0.14.2
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
vscode-icons|vsc|10.0.0
vuetify-vscode|vue|0.2.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-04-08 07:37
/duplicate of #92381 and fixed in the upcoming 1.44 release

**Closed** 2020-04-08 07:37 UTC
Labels: *duplicate
