### ISSUE TITLE
Sticky tabs miscalculation with word wrap

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#114492] opened 2021-01-17 14:35 UTC
Issue Type: <b>Bug</b>

There's a slight bug with the new sticky tab stops setting (#107126 ; my fault!). If you turn on word wrap it doesn't handle the start of wrapped lines correctly - for some reason it thinks the first bit is whitespace.

1. Turn on the `editor.stickyTabStops` setting.
2. Turn on word wrap.
3. Indent one tab stop.
4. Write lots of text that overflows the line.
5. Try to go into the first word on the second line.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

**Comment by alexdima** [comment] 2021-01-18 07:32
No worries, I already saw this reported and a fix is out in Insiders -- Duplicate of #112301

**Closed by alexdima** 2021-01-18 07:32 UTC
