### ISSUE TITLE
Refresh of file when changed outside of VSCode

### ISSUE THREAD

**Issue by dlindeque** [Microsoft/vscode#36445] opened 2017-10-17 18:57 UTC
- VSCode Version: 1.17.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open file in VSCode
2. Edit something, but keep it dirty
3. Change that same file using some other means and save
4. VSCode does nothing (expected)
5. Undo the edit in VSCode.
6. At this point, VSCode thinks the file is 'not dirty', but what VSCode show is not the same as what the file contains.
7. Switch to another file (inside VSCode)
8. Switch back to the original file (inside VSCode)
9. Now you'll notice that VSCode did pick up the new contents.

**Comment by bpasero** [comment] 2017-12-09 07:13
Marking as duplicate of https://github.com/Microsoft/vscode/issues/919

**Closed by bpasero** 2017-12-09 07:13 UTC
Labels: feature-request, workbench-editors
