### ISSUE TITLE
VS Code Windows 64 Bit - Copy on right click in terminal does not work

### ISSUE THREAD

**Issue by sanketmeghani** [Microsoft/vscode#32706] opened 2017-08-17 09:43 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
vscode-icons|rob|7.12.0
---
I have "terminal.integrated.rightClickCopyPaste" set to true. Still when I right click in embedded terminal it opens a context menu instead of copy/paste selected text in the terminal.

Steps to Reproduce:

1. Open embedded terminal (Ctrl + `)
2. Select any text in the terminal
3. Right click in the terminal
4. Expected behavior: It should copy the selected text
5. Actual behavior: It shows context menu 

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-08-17 15:20
Duplicate of https://github.com/Microsoft/vscode/issues/32336

**Closed by Tyriar** 2017-08-17 15:20 UTC
Labels: integrated-terminal, new release
