### ISSUE TITLE
Corrupted font in vscode

### ISSUE THREAD

**Issue by FacepalmMute** [Microsoft/vscode#37623] opened 2017-11-03 16:39 UTC
My global vscode font was corrupted, after i upgrade my Linux Distro(VScode don't included) and installed these plugins for vscode:
* LaTeX Workshop
* German - Code spell checker

I already tried to uninstall the named plugins, but the corruption still remains.
The Verbose output from vscode neither give a clue.

VSCode: 1.17.2
Linux: Parrot OS 

- VSCode Version: Code 1.17.2  b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z  - OS Version: Linux x64 4.13.0-parrot4-amd64 - Extensions: Extension|Author  truncated |Version -|-|- latex-workshop|Jam|3.6.0 code-runner|for|0.8.2 cpptools|ms-|0.14.0 platformio-ide|pla|0.7.3 markdown-preview-enhanced|shd|0.2.9 code-spell-checker|str|1.4.12 code-spell-checker-german|str|0.1.2 debug|web|0.21.2 - Steps to Reproduce: 1. 2. !- Launch with  code -disable-extensions  to check. -> Reproduces without extensions: Yes/No

![vscode_font](https://user-images.githubusercontent.com/13970572/32385189-9acd6d36-c0bd-11e7-9f24-3aa445599c05.png)

**Comment by maxibanki** [comment] 2017-11-03 17:01
Possible duplicate of #37495

**Comment by octref** [comment] 2017-11-03 18:15
@maxibanki Possibly, thanks.

@FacepalmMute 
Does the Insider have the same problem on your machine? https://code.visualstudio.com/insiders/

**Comment by Tyriar** [comment] 2017-11-03 18:27
Duplicate https://github.com/Microsoft/vscode/issues/35675

**Closed by Tyriar** 2017-11-03 18:27 UTC
Labels: editor, workbench

**Comment by FacepalmMute** [comment] 2017-11-03 19:25
@octref Yes, same problem with the latest insiders.

**Comment by octref** [comment] 2017-11-03 19:28
@FacepalmMute See #35675, downgrade your libfreetype6 from 2.8.1 to 2.8.0 should solve the problem.

**Comment by FacepalmMute** [comment] 2017-11-03 19:41
@octref already seen, thanks
