### ISSUE TITLE
Invisible main menu, black text and background

### ISSUE THREAD

**Issue by stripTM** [Microsoft/vscode#63288] opened 2018-11-16 09:37 UTC
Issue Type: <b>Bug</b>

When VSCode has the focus the main menu is not visible, but it is accessible if you click on its location.

If another window is selected the menu appears. Ubuntu 18.10.

VSCode on focus:
![menu_vscode_onfocus](https://user-images.githubusercontent.com/1289297/48613185-54f70180-e98b-11e8-9069-0879be8bade6.png)

VSCode blured:
![munu_vscode_onblur](https://user-images.githubusercontent.com/1289297/48613207-63451d80-e98b-11e8-8785-45a066466d5b.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 2838)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 2, 2|
|Memory (System)|15.55GB (10.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
json-pretty-printer|eus|1.0.1
php-debug|fel|1.12.6
vscode-language-pack-es|MS-|1.29.2
vetur|oct|0.13.0
vscode-workspace-switcher|sad|1.9.0

</details>

**Comment by krax1337** [comment] 2018-11-16 12:30
I have some problem on Ubuntu 18.10. How to fix? 
![Screenshot](https://image.ibb.co/dqiOKf/ksnip-20181116.png)

**Comment by krax1337** [comment] 2018-11-16 15:36
Another solution is to change the type of tittle bar to custom. By the way I noticed that this problem only on Yaru. On Yaru-dark all well.
![Screenshot](https://preview.ibb.co/msPsef/2.png)
![Screenshot](https://image.ibb.co/bJn3Kf/dsadsa.png)

**Comment by mattvend** [comment] 2018-11-16 16:06
Changing bar style works for me, thanks for the tip.

**Comment by drguildo** [comment] 2018-11-16 18:20
> > I have some problem on Ubuntu 18.10. How to fix?
> 
> My temporary solution is to change the Ubuntu theme, instead of Yaru use Adawaita. Adawaita shows the top of the window (title and menú bar) with light background instead of dark.
> 
> ![menu_vscode_adawaita](https://user-images.githubusercontent.com/1289297/48624054-c646ac80-e9ab-11e8-976d-a9dd5eb42d70.png)

This worked for me but it's worth noting that, unless I'm missing something, it requires installing GNOME Tweaks (at least on Ubuntu 8.10).

**Comment by sbatten** [comment] 2018-11-16 18:49
Duplicate of #62593

**Closed by sbatten** 2018-11-16 18:49 UTC
Labels: new release
