### ISSUE TITLE
[xml] XML Language color preference parsing degraded in latest release.

### ISSUE THREAD

**Issue by AlexChesser** [Microsoft/vscode#244] opened 2015-11-19 14:55 UTC
Prior to yesterday's update, VS code coloring in XML files (specifically web.config) had more variation between various tags and values than the screenshot included.

![capture](https://cloud.githubusercontent.com/assets/355561/11273523/b88f74ea-8ea1-11e5-9c5c-9e8eede4c42d.PNG)

as a comparison, the syntax highlighting in XML under a light themed notepad++ window

![capture](https://cloud.githubusercontent.com/assets/355561/11273814/5d758502-8ea3-11e5-916a-f422c90adea0.PNG)

Is a lot closer to the level of highlighting we used to have in XML files.  DEFAULT TAGS were one color, attributes another, values a third.

Perhaps something broke in XML language parsing?

**Comment by aeschli** [comment] 2015-11-24 15:59
duplicate of #23

**Closed** 2015-11-27 15:49 UTC
