### ISSUE TITLE
Webview does not load on github.dev and vscode.dev in firefox

### ISSUE THREAD

**Issue by yuyichao** [microsoft/vscode#152049] opened 2022-06-14 12:18 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: Linux Firefox

Steps to Reproduce:

1. Open a webview in vscode.dev or github.dev (Preview of markdown or simple browser both show the issue)
2. The content of the webview does not load

I can reproduce this on both vscode.dev and github.dev which both seem to have 1.68.0. These used to work about a month ago and is still working on the gitpod.io version which is 1.67.2. Local testing of extension (1.69.0-insider) doesn't seem to have this issue either but I'm not sure if it's from the version or because it's running on local host...

The symptom is very similar to https://github.com/microsoft/vscode/issues/142817 but I don't see any CSP errors. I don't think this is exactly the same as https://github.com/microsoft/vscode/issues/145647 since the page does load for me, even the markdown source file. It's only the preview (and other webviews) that doesn't work.

Tested on two computers (one x86, one aarch64) and with clean profile as well as incognito mode.

**Comment by yuyichao** [comment] 2022-06-14 12:19
(This was also working about a month ago...)

**Comment by yuyichao** [comment] 2022-06-14 16:21
Also confirmed on windows.

**Comment by mjbvz** [comment] 2022-06-14 17:47
Duplicate of #151648

**Closed by mjbvz** 2022-06-14 17:47 UTC
