### ISSUE TITLE
Format Code for JS file doesn't work with ESLint

### ISSUE THREAD

**Issue by kinergy** [Microsoft/vscode#13186] opened 2016-10-04 00:32 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:
1. install and run the eslint extension (I"m using 1.0.7 presently)
2. formatting an ugly JS file doesn't work, no changes are made when selecting Format Code
3. if I uninstall the ESLint extension, code formatting works again

**Comment by dbaeumer** [comment] 2016-10-05 08:28
I can't reproduce this in a simple example. @kinergy could you share a setup exposing this.

![cast](https://cloud.githubusercontent.com/assets/1931590/19106218/7f13f12c-8ae6-11e6-8e22-3bcecf7db4f2.gif)

**Comment by waderyan** [comment] 2016-11-21 23:27
Closing until more info is obtained.

**Closed by waderyan** 2016-11-21 23:27 UTC
Labels: javascript, needs more info
