### ISSUE TITLE
English language pack: Translation misses a backslash in the label

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#116198] opened 2021-02-09 13:50 UTC
It's not clear from the hover that you're meant to use `$(id)` because the icon gets resolved:

![image](https://user-images.githubusercontent.com/2193314/107372776-a4f59d80-6a9a-11eb-93d2-1b267a47aa06.png)

Making `theme icon reference` a link pointing to API docs would be helpful too.

**Comment by misolori** [comment] 2021-02-09 14:29
@aeschli I think this is a regression?

**Comment by aeschli** [comment] 2021-02-09 16:42
Yes, I probably cased that some days ago.

**Comment by aeschli** [comment] 2021-02-12 11:02
I'm not able to reproduce in insiders:

(Version: 1.54.0-insider Commit: 93f705ab40b37aade9d3b5165ed09114a8c87ac9 Date: 2021-02-11T05:44:44.032Z)
![image](https://user-images.githubusercontent.com/6461412/107760424-00898a80-6d2a-11eb-9261-9b85fff3f7b6.png)

**Comment by Tyriar** [comment] 2021-02-12 13:37
I can:

![recording (4)](https://user-images.githubusercontent.com/2193314/107774852-6b1fd380-6cf4-11eb-86f7-a691f49e6dcb.gif)

Version: 1.54.0-insider (user setup)
Commit: 6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197
Date: 2021-02-12T05:13:16.111Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment] 2021-02-12 14:51
Hmm, strange, I tested also on Window on the same commit (6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197)
Can you turn on `"json.trace.server": "verbose",` and check out  the JSON Language Server output view. It should be:
![image](https://user-images.githubusercontent.com/6461412/107781448-33db1200-6d48-11eb-93ba-d44e2b6105f9.png)

Then setting a breakpoint in markdownRenderer.ts - renderMarkdown: https://github.com/microsoft/vscode/blob/6a698d7d435466f13dff1b9852e95954a91c87f4/src/vs/base/browser/markdownRenderer.ts#L48

![image](https://user-images.githubusercontent.com/6461412/107781340-173eda00-6d48-11eb-9c76-121a2c6a039d.png)

**Comment by Tyriar** [comment] 2021-02-12 15:02
```
[Trace - 6:54:50 am] Received response 'textDocument/hover - (59)' in 9ms.
Result: {
    "contents": [
        "\\(Optional\\) Icon which is used to represent the command in the UI\\. Either a file path, an object with file paths for dark and light themes, or a theme icon references, like \\`$\\(zap\\)\\`"
    ],
    "range": {
        "start": {
            "line": 51,
            "character": 8
        },
        "end": {
            "line": 51,
            "character": 14
        }
    }
}
```

I disabled the en-gb language pack and it still seems to happen.

I tried to use Code - OSS and set a breakpoint but it works fine there 🤷. Source maps don't want to work for me in insiders and I couldn't find the minified part to debug into.

**Comment by aeschli** [comment] 2021-02-12 16:32
I can reproduce with the English language package. 
It's missing the `\` before the `$(zap)`:
https://github.com/microsoft/vscode-loc/blob/8414365cca49966a7e50894ecc6106db6a6def64/i18n/vscode-language-pack-en-GB/translations/main.i18n.json#L2165

**Comment by misolori** [comment] 2021-02-12 16:56
I can see the `\` on the suggest widget but not on hover (today's Insiders on macOS):

![image](https://user-images.githubusercontent.com/35271042/107797691-112d0700-6d10-11eb-87d7-4e3a4814f04c.png)

**Comment by Tyriar** [comment] 2021-02-12 18:30
Oh I guess I didn't reload properly to apply the uninstalled language pack, thanks 👍

**Comment by Tyriar** [comment] 2021-02-12 18:35
@aeschli shouldn't `\\$(zap)` in the string be `{0}` so we don't hit translation problems like this?

**Comment by aeschli** [comment] 2021-02-22 13:20
I added a message to the NLS key to let translators know.

**Comment by v-mholloway** [comment] 2021-09-27 12:33
Note: All translations have been reviewed and I have ensured that they are all set with...

`\$(zap)`

any changes will be reflected in the build in a few days

**Comment by v-mholloway** [comment] 2021-09-29 11:05
relevant culture fixes would be in the build by now... closing

**Closed by v-mholloway** 2021-09-29 11:05 UTC
Labels: L10N
