### ISSUE TITLE
git add

### ISSUE THREAD

**Issue by zhaoshaokun** [microsoft/vscode#99935] opened 2020-06-12 03:28 UTC
Issue Type: <b>Feature Request</b>

git add .   fail: outside repository

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by zhaoshaokun** [comment] 2020-06-12 03:29
version 1.46

**Comment by gjsjohnmurray** [comment] 2020-06-12 05:05
/duplicate of #99881 
Maybe https://github.com/microsoft/vscode/issues/99881#issuecomment-643056608 is useful for advice for you.

**Closed** 2020-06-12 05:06 UTC
Labels: *duplicate, new release
