### ISSUE TITLE
VSCode terminal becomes unusable after locking screen

### ISSUE THREAD

**Issue by herodionem** [microsoft/vscode#117781] opened 2021-02-26 17:45 UTC
Most often happens while an active ssh or python session is running when screen is locked.
Have VSCode terminal open 
sleep or lock screen
log back in
VSCode terminal has no text, the cursor is in random places. Acts like it might still be running as I still have to keyboard interrupt and ctrl+d twice to exit terminal.
Functions as expected when new terminal is opened

VSCode:
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-44-generic snap

Machine:
Model: ASUS TUF506
Processor: AMD® Ryzen 7 4800h with radeon graphics × 16
Graphics: NVIDIA Corporation / GeForce RTX 2060/PCIe/SSE2
OS: Ubuntu 20.04.2 LTS
GNOME: 3.36.8
Windowing System: X11

**Comment by meganrogge** [comment] 2021-02-26 17:59
Duplicate of #69665

**Closed** 2021-02-26 18:00 UTC
Labels: *duplicate, bug, integrated-terminal
