### ISSUE TITLE
Call stack is not showing the right frames 

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42280] opened 2018-01-28 21:07 UTC
I see this consistently when I debug the adapter. The call stack shows the frames jumbled up, or it doesn't update when the debugger pauses, or it shows multiple "Load more frames" entries in the wrong places. The devtools console is full of this error from vscode, `Cannot read property 'id' of null: TypeError: Cannot read property 'id' of null`. Its stack is:

```
e.onInsertItems (treeViewModel.ts:70)
t.onItemChildrenRefreshed (treeView.ts:944)
e.fire (event.ts:144)
e.fire (event.ts:144)
(anonymous) (event.ts:212)
e.fire (event.ts:142)
(anonymous) (treeModel.ts:516)
then (winjs.base.raw.js:1566)
a (treeModel.ts:516)
(anonymous) (treeModel.ts:106)
n.Class.derive._oncancel (winjs.base.raw.js:1641)
e.run (treeModel.ts:98)
e.refreshChildren (treeModel.ts:519)
e.doRefresh (treeModel.ts:529)
e.refresh (treeModel.ts:533)
e.refresh (treeModel.ts:982)
e.refresh (treeImpl.ts:158)
(anonymous) (callStackView.ts:78)
e.onTimeout (async.ts:646)
```

**Comment by isidorn** [comment] 2018-01-29 15:42
@roblourens this means the tree is in a broken state.
It would be great to catch this issue, can you please "break on error" so next time we see which exact element seems to be null.
Are there some steps for us reproducing this?
It would be interesting to see if this [method](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/callStackView.ts#L291) returns some child that is null.

Anyways more details are needed for me to do something about this

**Comment by roblourens** [comment] 2018-01-29 18:59
I think the key is debugging with a deep call stack where "load more frames" becomes visible. It shows up about 100% of the time when that happens. I don't see that method returning a null child, but I also am not seeing the exact same error today.

Today I'm seeing `Cannot read property 'name' of undefined` at

```
get (debugSource.ts:40)
x (callStackView.ts:535)
e.getAriaLabel (callStackView.ts:527)
e.render (treeView.ts:202)
e.insertInDOM (treeView.ts:280)
t.insertItemInDOM (treeView.ts:1588)
t.refreshViewItem (treeView.ts:1114)
t.onInsertItem (treeView.ts:1093)
e.onInsertItems (treeViewModel.ts:74)
t.onItemChildrenRefreshed (treeView.ts:944)
e.fire (event.ts:144)
e.fire (event.ts:144)
(anonymous) (event.ts:212)
e.fire (event.ts:142)
(anonymous) (treeModel.ts:516)
then (winjs.base.raw.js:1566)
a (treeModel.ts:516)
(anonymous) (treeModel.ts:106)
n.Class.derive._oncancel (winjs.base.raw.js:1641)
e.run (treeModel.ts:98)
e.refreshChildren (treeModel.ts:519)
e.doRefresh (treeModel.ts:529)
e.refresh (treeModel.ts:533)
e.refresh (treeModel.ts:982)
e.refresh (treeImpl.ts:158)
(anonymous) (callStackView.ts:78)
e.onTimeout (async.ts:646)
```

but with the same symptoms in that the callstack shows the wrong frames. It seems to be happening on 'label' frames that don't have a source like the `[async]` markers. Could this be related to that other change to force-update properties that change on the source, like presentationHint?

**Comment by roblourens** [comment] 2018-01-29 19:00
Example screenshot

![image](https://user-images.githubusercontent.com/323878/35528726-a6e1c90e-04e3-11e8-8ba9-fb2b4c839423.png)

**Comment by eamodio** [comment] 2018-01-30 03:03
I am seeing no call stack when debugging GitLens -- just started with today's insiders release.

**Comment by isidorn** [comment] 2018-01-30 09:48
@roblourens yes that change with the force update of source might be related. I have pushed a potential fix for this. 
@roblourens @eamodio Please try in tomorrow's insiders and let me know if it reproes (note that the tuesday morning insider does not contain this fix).

Thanks for the nice pictures guys but I do not really need those as that just means the tree is broken.
I need repro steps. Example program where this is easily being shown so I can investigate more on my machine.

I tried a fibonaci function with 200 recursive calls and that does not repro (so it is not the load more stack frames).

**Closed** 2018-01-30 09:47 UTC
Labels: debug, needs more info

**Comment by roblourens** [comment] 2018-01-30 17:12
I ran it out of sources and verified that it's fixed. I think the key is having the async label frames. Here are better repro steps just a little too late:

- Debug my async frame test file: https://github.com/Microsoft/vscode-node-debug2/blob/master/testdata/native-async-await/main.js (has a launch config in the native-async-await folder)
- Set breakpoints anywhere and step around
- In current insiders, the above error shows up and the stack gets messed up. In master, it works perfectly :tada:

**Comment by isidorn** [comment] 2018-01-31 10:25
@roblourens thanks for the repro steps
The issue was probably in the way how we compute id for a async call stack entry. That id is dependendt on the source, and my bet would be that a new raw source was incoming which was not containing all the data, thus the id computation was flawed and was causing corruption in the tree.
Thanks for trying it quickly in the out of source!

**Comment by ramya-rao-a** [comment] 2018-02-03 01:08
@roblourens Marking this as verified as you have already done so
