### ISSUE TITLE
HTML code snippet do not working in VScode 1.11.1

### ISSUE THREAD

**Issue by yy7054wyq5** [Microsoft/vscode#24401] opened 2017-04-10 06:15 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.5|
|angular1-code-snippets|alexandersage|0.0.3|
|ng-template|Angular|0.1.2|
|jquerysnippets|donjayamanne|0.0.1|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.8|
|vscode-great-icons|emmanuelbeziat|1.1.47|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|beautify|HookyQR|1.0.2|
|Angular2|johnpapa|2.2.3|
|vscode-exec-node|miramac|0.4.1|
|debugger-for-chrome|msjsdiag|2.7.3|
|syncing|nonoroazoro|1.3.4|
|autoimport|steoates|1.2.2|
|vscode-react-native|vsmobile|0.3.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.4.11|;

---

Steps to Reproduce:

1.I had update VScode to 1.11.1
2.And the html code snippet does't work.

**Comment by jrieken** [comment] 2017-04-10 08:15
@yy7054wyq5 Is this a user snippet or an extension snippet? Is this from the `Insert Snippet` command or when typing in source?

**Comment by yy7054wyq5** [comment] 2017-04-11 01:54
It's a user snippet and when i typing.But today, this problem had disappear.
And i think this is still a VScode problem.
Because,when i submit this issue,i see three vscode-process in Windows Task Manager occupy above 75% cpu.
And today,vscode occupy 0% cpu when i submit this comment.
At last, in html.When i typing inline style. vscode didn't  prompt 'css attribute'

**Comment by jrieken** [comment] 2017-04-11 07:33
Please attach the snippet in question and what you have typed

**Comment by yy7054wyq5** [comment] 2017-04-11 10:46
HTML snippet json:
```
{
  "a delete button":{
    "prefix": "scm_del_btn",
    "body": ["<a class=\"fa fa-trash\"></a>"],
      "description": "删除按钮"
     },
  "a edit button":{
    "prefix": "scm_edit_btn",
    "body": ["<a class=\"w-btn-sm w-btn\" translate=\"edit\"></a>"],
		"description": "编辑按钮"
	},
}
```
If i code:
```
scm
```
There is not prompt.

**Comment by jrieken** [comment] 2017-04-11 11:58
<img width="1019" alt="screen shot 2017-04-11 at 13 57 51" src="https://cloud.githubusercontent.com/assets/1794099/24908036/e5b01f2a-1ebe-11e7-8b8b-3baf590fe659.png">

Still not reproducible for me. Where in the HTML-file do you type?

**Comment by yy7054wyq5** [comment] 2017-04-11 13:10
In fact, this problem had disappear.I mean when i found the problem, vscode occupy 75% of cpu. And now ,vscode occupy 0% of cpu. Then the problem never appear.
But, when i code html inline style. vscode didn't association css attribute.
```
<div style="mar"></div>
```

**Comment by jrieken** [comment] 2017-04-11 13:21
close as dupe of #24464 because the previous comment

**Closed by jrieken** 2017-04-11 13:21 UTC
Labels: needs more info

**Comment by yy7054wyq5** [comment] 2017-04-11 14:01
Thanks.
