### ISSUE TITLE
Setting for unicodeVersion of terminal show warning message "invalid type"

### ISSUE THREAD

**Issue by longnt0707** [microsoft/vscode#97221] opened 2020-05-08 07:08 UTC
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open setting by Ctrl+,
2. Search Unicode

Does this issue occur when all extensions are disabled?: Yes
<img width="817" alt="vscode_145" src="https://user-images.githubusercontent.com/6789129/81380609-243df580-9146-11ea-8ed2-91ad76a14033.PNG">

**Comment by gjsjohnmurray** [comment] 2020-05-08 07:17
/confirm

My settings.json contained `"terminal.integrated.unicodeVersion": "",`

I haven't knowingly ever set this.

Interestingly when I do the following
![image](https://user-images.githubusercontent.com/6726799/81381139-10719f80-9104-11ea-96a4-c89f81afdd6a.png)

my clipboard contains `"terminal.integrated.unicodeVersion": "11"`

**Comment by gjsjohnmurray** [comment] 2020-05-08 07:53
> My settings.json contained `"terminal.integrated.unicodeVersion": "",`
> 
> I haven't knowingly ever set this.

Correction. My settings.json contained no entry for `terminal.integrated.unicodeVersion'. The "" value got added when I clicked the "Edit in settings.json" link shown in the screenshot above.

So this is probably a duplicate of #97034

**Comment by Tyriar** [comment] 2020-05-08 12:35
@roblourens this setting's default value is "11", not null. This error might be correct I think?

**Comment by roblourens** [comment] 2020-05-08 14:02
/duplicate of https://github.com/microsoft/vscode/issues/97192

**Closed** 2020-05-08 14:03 UTC
Labels: *duplicate, confirmed
