### ISSUE TITLE
Autoformatting breaks jekyll meta

### ISSUE THREAD

**Issue by mariusa** [Microsoft/vscode#31241] opened 2017-07-22 05:32 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.11.10-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
debugger-for-chrome|msj|3.1.6
vscode-sql-beautify|sen|0.0.4

---

Steps to Reproduce:

1. Create a .html file to be used with jekyll:
```
--- 
title: My page
---
content goes here
```
2. Save
Expected: stay as entered
Result:
```
--- title: My page ---
content goes here
```

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-08-02 14:20
duplicate of #24088

**Closed by aeschli** 2017-08-02 14:20 UTC
