### ISSUE TITLE
When panel does not have enough width, toggle vertical layout hides it

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37381] opened 2017-11-01 06:10 UTC
Testing #36906 with 8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791

After that toggle, first Cmd+J strangely only makes the editor wider but not show the panel. Second Cmd+J shows the panel.

![panel](https://user-images.githubusercontent.com/4033249/32262183-7a355748-be90-11e7-983f-016396356f4e.gif)

**Comment by isidorn** [comment] 2017-11-01 07:18
Good catch, but duplicate of some issue ben already found.
This should be fixed in tomorrows insiders. Please let me know if you still see it and I will reopen

**Closed by isidorn** 2017-11-01 07:18 UTC
Labels: bug, workbench
