### ISSUE TITLE
VSCode incorrectly processes responses from extensions.

### ISSUE THREAD

**Issue by vistatest** [microsoft/vscode#82392] opened 2019-10-11 19:41 UTC
When multiple different extensions return the same response(s),
VSCode displays duplicates. 

This is a bug in VSCode. Extensions are not aware of each other. They should not be. Different extensions that run simultaneously could provide intersecting responses.

VSCode should remove duplicates from the final merged list before displaying it to user.

Please, stop closing this bug report - this is about a bug in VSCode core, in the way how it handles responses by extensions. It's not a bug in any particular extension. Extension authors could not do anything about this bug.

VSCode Version: Version: 1.38.1
Commit: b37e54c
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
Installed extensions: Python LS, Pyright

Steps to Reproduce:
Search for a symbol (Command-T) - see all entries twice in the list.
Several other search-related commands also have entries duplicated on the lists.

**Comment by jrieken** [comment] 2019-10-14 07:49
/needsMoreInfo

>  in the way how it handles responses by extensions.

Responses to what requests?

**Comment by vistatest** [comment] 2019-10-14 10:18
Installed extensions: Python LS, Pyright

_Go to Symbol in Workspace_ (Command-T) and see all entries twice in the list. I assume Command-T causes VSCode core to request information from extensions(s) and then shows received responses.

_Go to symbol in File_ (Shift-Command-O) also have entries duplicated in the list shown to the user.

_Find All References_ (Shift-Option-F12) - same issue. Etc.

**Comment by jrieken** [comment] 2019-10-14 10:35
Closing as duplicate of https://github.com/microsoft/vscode/issues/80889

**Closed** 2019-10-14 10:36 UTC
Labels: *duplicate
