### ISSUE TITLE
Blurry fonts in Insiders

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82521] opened 2019-10-14 18:24 UTC
I see this on a non-retina display when using Electron 6. Offline we established that other people do not see this. It seems worst with red text and is especially obvious in Monokai.

Seems related to https://github.com/microsoft/vscode/issues/51132 somehow.

Stable, Insiders
![image](https://user-images.githubusercontent.com/323878/66773942-1f95b500-ee75-11e9-9fae-8aa5d15dbaed.png)

**Comment by usernamehw** [comment] 2019-10-14 19:03
duplicate of #81391 ?

**Comment by roblourens** [comment] 2019-10-14 20:59
That looks sort of different but I'll let @deepak1556 judge.

**Comment by deepak1556** [comment] 2019-10-15 18:57
@roblourens is right, this is different from #81391 but is the same issue as #51132 affecting non-retina displays. Also said that, this has been addressed in chromium to their best effort https://bugs.chromium.org/p/chromium/issues/detail?id=901611 and the fix is available in our latest insiders. I am merging this to the above issue.

**Closed** 2019-10-15 18:57 UTC
Labels: *duplicate
