### ISSUE TITLE
Allow to show multiple panels at the same time (split pane)

### ISSUE THREAD

**Issue by fronteed** [microsoft/vscode#11889] opened 2016-09-12 15:26 UTC
- VSCode Version: 1.5.1
- OS Version: OS X El Capitan

![2016-09-12-ifk3n](https://cloud.githubusercontent.com/assets/1612675/18441274/17f0863c-7915-11e6-8742-4635fab63e57.png)

While there's a double pane for files, an errors/terminal board can't be divided into two panes right now. This would be very helpful, since terminal and errors are usually needed together - you type some code and see compilation notes in terminal. Most of the time there's too much whitespace at the right side of the terminal/errors board, so we can add same double-pane toggle icon [ | ] at the right side of the board and make it work:
- if double-pane mode is switched on and one side is empty, then, we would add a terminal/errors board right there
- if double-pane mode is switched off, then, make visible only left board, right one should disappear
- if one of the boards is switched off using hotkey, then, remove it and make a board single-pane (if there's one board in double-pane - remove both panes)

**Comment by DmitryEfimenko** [comment] 2016-09-15 22:05
I think there should be a way to split **terminal window** independently of the amount of **code windows**.

**Comment by fronteed** [comment] 2016-10-22 12:21
@bpasero any progress on this issue?

**Comment by bpasero** [comment] 2016-10-22 15:21
No, this is something we are not working on currently or planning short term.

**Comment by stealthybox** [comment] 2017-01-24 23:39
Duplicate of #10546
There's movement on this.

**Comment by JasonMFry** [comment] 2018-09-14 13:29
I'm bummed to see that this feature request has been closed, I would love the ability to see both the terminal and the problems pane at the same time.

**Comment by isidorn** [comment] 2018-09-18 12:48
This feature request is not closed.

**Comment by bradharms** [comment] 2019-01-23 15:56
Correct me if I'm wrong, but doesn't the terminal panel actually allow split view now?

![image](https://user-images.githubusercontent.com/1239044/51619049-10d92d80-1ef5-11e9-84cf-8f7549b8c59f.png)

**Comment by Elyx0** [comment] 2019-05-09 15:05
Please make it happen!

**Comment by dsovino-alma** [comment] 2019-05-27 15:44
I'd love to see Output / Terminal at the same time as well.
Really any combination of Output, Debug / Terminal as needed.

**Comment by pinnekamp** [comment] 2019-05-28 10:57
Also multiple Outputs, e.g. Output <Python> and Output <Python Test Log>

**Comment by vamseekm** [comment] 2019-05-31 12:55
In my use case I would love to see Problems and Terminal side by side in a split mode. This allows me to see lint errors and as well as see terminal output at the same time and constantly not to move away my hand from keyboard to mouse to switch between panels.

**Comment by infinite-persistence** [comment] 2019-06-19 08:49
How to up-vote items in github?

**Comment by Gummy47** [comment] 2020-02-26 11:08
Would love such a feature. Any news?

**Comment by bramjoosten** [comment] 2020-03-09 08:49
Great to see it's On Deck, still very interested in this one for me.

**Comment by thinkloop** [comment] 2020-03-21 20:36
Critical feature for me, glad to see it's On Deck, will keep an eye out and switch from Sublime when it's out.

**Comment by TheTomer** [comment] 2020-03-23 18:28
Indeed, having this feature would make things so much easier, especially when working with C++.

**Comment by sbatten** [comment] 2020-03-30 14:05
With work done this milestone, it is now possible in insiders to drop `Terminal` next to `Problems` to see them (or any set of views) at the same time. While we will continue to improve the look and feel of this feature, I believe this satisfies the original request.

**Closed by sbatten** 2020-03-30 14:05 UTC
Labels: feature-request, layout

**Comment by JoshArdito** [comment] 2020-04-17 11:41
Thanks @sbatten ! I'm finally ready to completely move over to VS Code due to this feature. Any video / documentation on how to use it? I'm running the latest VS Code version ( 1.45.0-insider), trying to follow the steps in your test (#93787) 

> Drag views into a single panel so that they are split horizontally.

I click and drag the Title "Problems" for example and try to drag it into terminal. It doesn't seem to do anything more than re-order the panels. I can't seem to get them into a split screen mode.

**Comment by sbatten** [comment] 2020-04-17 14:13
@JoshArdito, after dragging "Problems" over "Terminal", hover until the panel switches to "Terminal".  At this point, you can continue to drag the "Problems" inside the panel to side-by-side with "Terminal"
