### ISSUE TITLE
Jump to function beginning

### ISSUE THREAD

**Issue by acming92** [microsoft/vscode#57102] opened 2018-08-23 19:33 UTC
I think it's useful provide a way to jump at the beginning of the current function, especially when the function is very long and team likes to define variable in the beginning of the function.

**Comment by waynchi** [comment] 2019-02-12 21:58
Is there any update on this? Being able to jump to the beginning or end of functions has been pretty useful to me on emacs (C-M-a and C-M-e) and Vim.

**Comment by jrieken** [comment] 2019-10-22 15:07
/duplicate of https://github.com/microsoft/vscode/issues/46153

**Closed** 2019-10-22 15:08 UTC
Labels: *duplicate, feature-request, outline
