### ISSUE TITLE
JavaScript debugging: run to cursor can skip to next statement if cusor is after semicolon

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#102199] opened 2020-07-11 07:33 UTC
Issue Type: <b>Bug</b>

**Repro**
1. For the following node code:

```js
let a = 0;

for (let i = 0; i < 1000; ++i) {
    if (a % 10 === 0) {
        a /= 2;
    }
    a += i;
}

console.log(a);
```

1. Use a debug terminal to debug it
1. Place your cursor at the end of the line after `a /= 2;` and run `Debug: Run to cursor`

**Expected**
Program runs to that line

**Actual**
The program runs to the next line: `a += i`:

 
<img width="809" alt="Screen Shot 2020-07-11 at 12 30 11 AM" src="https://user-images.githubusercontent.com/12821956/87219210-2838f000-c30e-11ea-971c-6726fb666ec7.png">

Even though this behavior makes sense from a program structure perspective, it still caught me off guard  
VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|
</details>

**Comment by connor4312** [comment] 2020-07-11 16:48
I hadn't actually used this command before, thanks for the tweet tip 😄 

It looks like this works purely in UI by setting a breakpoint at the cursor position and then resuming the debugger. We accordingly bubble that breakpoint position to Chrome, which (correctly) resolves that to the following statement.

I think the nicest fix here would be adjusting the logic in VS Code such that:

- If the cursor is on a line different than the one the debugger is currently paused on, then send the breakpoint at column 0 on the line
- otherwise use the current behavior

I already outed myself by saying I don't use this feature, but this seems like it would generally be desirable behavior, at least for JS. Thoughts @weinand?

**Comment by weinand** [comment] 2020-08-06 07:05
IMO this works as designed.
@isidorn but I think we could try @connor's suggestion and see whether this improves the feature.

**Comment by isidorn** [comment] 2020-08-06 07:44
Yes, I like @connor4312 suggestion.
Assigning this to August so we experiment with the suggestion next week.

**Comment by isidorn** [comment] 2020-08-11 14:47
I tried out the @connor4312 suggestion and it seems to work just fine for me.
I have pushed it, so try it out and let me know how it goes for you,

**Closed** 2020-08-11 14:46 UTC
Labels: debug, feature-request
