### ISSUE TITLE
Mac shortcut Cmd + Shift + Slash broken after 1.31.1

### ISSUE THREAD

**Issue by jasperkuperus** [microsoft/vscode#68604] opened 2019-02-13 09:48 UTC
I use the Mac shortcut `Cmd + Shift + /` quite often, to navigate the menu of an application (as described here: https://www.imore.com/how-use-macs-help-menu). This shortcut seems to be broken in version 1.31.1. Nothing happens, it also doesn't seem to be bound to a new command.

It's also broken in the insiders build, and when starting without extensions.

- VSCode Version: 1.31.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Press Cmd + Shift + /
2. Mac OS should open the help window, in stead, nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by dlcmh** [comment] 2019-04-29 04:51
Cmd + Shift + / works only when there are no open editors

**Comment by kinueng** [comment] 2019-06-29 16:34
Related to #69375
It looks like `Cmd + Shift + /` is broken for many Electron based applications.

I am unable to use `Cmd + Shift + /` on MacOS 10.14.5 for
- Spotify Desktop App 1.1.9.383.g9f48828e
- Slack Desktop App 3.4.2

**Comment by kinueng** [comment] 2019-06-29 17:12
I opened electron/electron#19048 to see if the electron team can help

**Comment by sr3d** [comment] 2019-09-04 18:03
This is confirmed to be still broken:

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by alexandrudima** [comment] 2019-09-09 12:48
Filed upstream as https://github.com/electron/electron/issues/19048 . Please comment there.

**Comment by alexandrudima** [comment] 2019-10-09 10:30
@bpasero @deepak1556 Assigning to you, as this is 100% an Electron issue. The way this should work via cmd+shift+/ has nothing to do with out keybindings story.

**Comment by kinueng** [comment] 2021-04-07 16:41
This issue is now fixed for me in VSCode.
```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

See the corresponding issue I opened in electron https://github.com/electron/electron/issues/19048 mentioned in https://github.com/microsoft/vscode/issues/68604#issuecomment-506972872.
See the fix in PR https://github.com/electron/electron/pull/27701

**Comment by jaquinocode** [comment] 2021-05-16 08:27
I'm trying to set cmd+shift+slash to make a block comment in vscode, but vscode doesn't even recognize the shortcut.

When recording my keys, vscode interprets 'shift+cmd+/' as just 'shift+cmd'.

Using 1.56.0.

Update: strangely enough, upgrading to 1.56.2 fixed my problem. What...

**Comment by tnrich** [comment] 2021-09-08 21:51
Seeing this on 1.60.0 for the first time.. On a mac running big sur 11.2.3

**Comment by deepak1556** [comment] 2021-09-09 00:58
Sorry missed on following-up here, the relevant upstream issue fix has been available in our stable build for a while now. Verified that https://github.com/microsoft/vscode/issues/68604#issue-409715138 works.

**Closed by deepak1556** 2021-09-09 00:58 UTC
Labels: upstream, macos, electron, upstream-issue-linked

**Comment by deepak1556** [comment] 2021-09-09 01:00
@tnrich please open a separate issue for the issue you are seeing, can you also run the command "Toggle keyboard shortcuts troubleshooting", then use that keybinding and attach the output in the issue. Thanks!
