### ISSUE TITLE
Background color for theme is not applied

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19402] opened 2017-01-25 23:28 UTC
Reproes on MacOS and Windows right now

- Switch 'color theme' to "Tomorrow Night Blue" or "Red"
- The editor background color is the same generic dark color, not blue/red

Was this changed on purpose?

**Comment by ramya-rao-a** [comment] 2017-01-26 00:03
Duplicate of #19344

**Closed** 2017-01-26 19:45 UTC
Labels: duplicate, themes
