### ISSUE TITLE
Windows 10 freezes and crashes

### ISSUE THREAD

**Issue by deanapeterson** [Microsoft/vscode#35590] opened 2017-10-04 18:49 UTC
[0ad2_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1357005/0ad2_main.cpuprofile.txt)
[0ad2_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1357004/0ad2_renderer.cpuprofile.txt)

- VSCode Version: <code>vscode-oss 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-17T13:14:00.750Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)</code>
- Memory (System): <code>15.83GB (12.39GB free)</code>
- Memory (Process): <code>188.07MB working set (188.07MB peak, 156.04MB private, 46.63MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|32|
|main|app.isReady => window.loadUrl()|236|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|409|
|renderer|require(workbench.main.js)|577|
|renderer|create extension host => extensions onReady()|438|
|renderer|restore viewlet|0|
|renderer|restore editor view state|93|
|renderer|overall workbench load|219|
|main + renderer|start => extensions ready|1709|
|main + renderer|start => workbench ready|1481|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`0ad2_main.cpuprofile.txt`
-`0ad2_renderer.cpuprofile.txt`

**Comment by chrmarti** [comment] 2017-10-05 04:19
@deanapeterson Is this Windows or VSCode crashing? Could you describe what you did at the time the crash occurred?

**Comment by jrieken** [comment] 2017-10-05 08:07
This needs more info, like a crash dump. The profile looks proper

**Comment by loicraux** [comment] 2017-10-06 09:08
@deanapeterson Are you using extended display on several screens with an nVidia GPU ?

I have a similar issue since this morning : VSCode crashes at startup and running it with `--disable-extensions --disable-gpu --new-window` arguments does not help.
But the crash only occurs if I have extended display on 3 screens. If I launch VSCode only on my laptop screen, then everything is fine ...

It is confirmed by this application error log in Windows Event Viewer :
```
Description:
Faulting application name: Code.exe, version: 1.16.1.0, time stamp: 0x599e9d56
Faulting module name: nViewH64.dll, version: 6.14.10.14847, time stamp: 0x58524e98
Exception code: 0xc000041d
Fault offset: 0x0000000000098c31
Faulting process id: 0x3b0c
Faulting application start time: 0x01d33e80641789f8
Faulting application path: C:\Program Files\Microsoft VS Code\Code.exe
Faulting module path: C:\Program Files\NVIDIA Corporation\nview\nViewH64.dll
```
=> Related to my nVidia graphics card. I updated the drivers yesterday because I had BSOD with Skype (now fixed) 🤣 ...

**Comment by goodbomb** [comment] 2017-10-25 17:58
Hi, not sure if this is related, so I haven't opened a new bug yet, but I'm encountering a full system freeze on Windows 10 after I wake my computer in the morning and click on VS Code. VS Code was already open, I was just switching to it by clicking on the Taskbar icon.

I've been encountering full system freezes (requiring a hard reboot) on my work machine for several months now. I've gone through 4 machines at work trying to figure out what the problem is, but after the release of 1.17.x, it seems clearer that VS Code appears to be the culprit. This has happened to me two days in a row now (ever since I upgraded to 1.17.2).

I've noticed that I get a `Perflib` error (event ID: 1008) in the Windows Event Viewer right before the freeze happens.

```
The Open Procedure for service "WmiApRpl" in DLL "C:\WINDOWS\system32\wbem\wmiaprpl.dll" failed. 
Performance data for this service will not be available. 
The first four bytes (DWORD) of the Data section contains the error code.
```

There's also a `PerfNet` error (event ID: 2004) right before the `Perflib` error.

```
Unable to open the Server service performance object. 
The first four bytes (DWORD) of the Data section contains the status code.
```

**Comment by goodbomb** [comment] 2017-11-01 22:30
Just following up on this, now that it's been a week. Has anyone else encountered a problem like mine?

**Comment by deanapeterson** [comment] 2017-11-03 20:29
It appears that it was a rogue backup app that was causing my system crashes and not VSCode.

**Comment by goodbomb** [comment] 2017-11-03 23:39
Mine seems to be directly related to VS Code in some fashion. I've been logging each freeze for the past couple of weeks.

Computer Freezes:
- 10/17/2017 @ 2:35PM
- 10/20/2017 @ 2:31PM
- 10/20/2017 @ 4:22PM
- 10/20/2017 @ 5:39PM
- 10/24/2017 @ 9:48AM (clicking on VS Code after logging on)
- 10/25/2017 @ 9:16AM (clicking on VS Code after logging on)
- 11/01/2017 @ 3:20PM (executing a git pull command in terminal after running npm start in another window)
- 11/01/2017 @ 4:45PM (reloading VS Code after syncing changes with the Settings Sync plugin)
- 11/02/2017 @ 10:15AM (clicking on the VS Code icon a couple of times)
- 11/03/2017 @ 1:48PM (clicking on VS Code to maximize it)
- 11/03/2017 @ 4:16PM (clicking on VS Code to maximize it)

**Comment by jrieken** [comment] 2017-12-11 14:03
@goodbomb Do you still see this? Can you try to repo with latest insiders? https://code.visualstudio.com/insiders/?

**Comment by goodbomb** [comment] 2017-12-11 17:18
Hi @jrieken, I actually haven't had this issue for the last couple of weeks. Seems that it has resolved itself on its own. Not sure if it was a new release of VS Code or a Windows update, but my windows machine has finally stopped freezing on a daily basis.\

One thing I have been doing is closing and re-launching VS Code every day, and I figured that was helping. I'll hold off relaunching VS Code for a few days and see what happens. For now, you can assume this issue is resolved for me.

**Comment by jrieken** [comment] 2017-12-11 17:36
Ok, closing then. Please add a comment in case you still see this and I'll reopen the issue

**Closed by jrieken** 2017-12-11 17:36 UTC
Labels: needs more info, perf-profile
