### ISSUE TITLE
Status bar: allow extensions to contribute context menu entries on items

### ISSUE THREAD

**Issue by jeffyoung** [microsoft/vscode#27196] opened 2017-05-24 13:18 UTC
Now that VS Code provides a "Manage Extension" right-click context menu off of each status bar item provided by an extension, can extension authors get the ability to extend it?  I'd like to be able to add commands, custom text and a tooltip to the menu (much like SCM context menus) to provide additional functionality.  (I get frequent requests for functionality that would be perfect there in lieu of continually adding new status bar items.)

![image](https://cloud.githubusercontent.com/assets/2796865/26404934/9c975186-4061-11e7-8a9c-9b2e0538d2c6.png)

**Comment by laurentlb** [comment] 2022-11-04 21:34
Examples of actions to add in a context menu:
- on the workspace name: "Copy Workspace Name"
- on the scm label: "Copy Branch Name", "Copy Commit Hash", "Sync"
- on the pull request information: "Open in GitHub"

![image](https://user-images.githubusercontent.com/485572/200077876-5560a96b-cd2a-4365-b5d7-277d076b5902.png)

At Google, we've had a lot of feedback from users confused they couldn't copy the workspace name easily. Since it's displayed in the status bar, it feels natural to copy it from there too.

I wonder if there's any concern about this feature. I believe it can make some features more discoverable / accessible.

**Comment by isidorn** [comment] 2022-12-06 11:38
Duplicate of https://github.com/microsoft/vscode/issues/167874

**Closed by isidorn** 2022-12-06 11:38 UTC
Labels: feature-request, api, extensions, workbench-status
