### ISSUE TITLE
File name in tab doesn't update when updating file capitalization

### ISSUE THREAD

**Issue by SoSDylan** [microsoft/vscode#101256] opened 2020-06-29 02:16 UTC
Issue Type: <b>Bug</b>

Let's say I create a new file (eg. 'date.js'), and I then open the file up.

If I then decide to change it to 'Date.js' with the file still open, the file name in the explorer will update to the new name with capitals but the tab in the open editor doesnt update (still says 'date.js')

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|-psn_0_389215|
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
svelte-intellisense|ard|0.7.1
vscode-django|bat|0.20.0
vscode-custom-css|be5|3.0.10
dart-code|Dar|3.12.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.0
vscode-svelte-snippets|fiv|0.4.0
todo-tree|Gru|0.0.177
svelte-vscode|Jam|0.9.3
restructuredtext|lex|128.0.0
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.90262
vsliveshare|ms-|1.0.2377
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
quicktype|qui|12.0.46
java|red|0.63.0
postcss|ric|2.0.0
synthwave-vscode|Rob|0.1.5
sass-indented|syl|1.8.7
language-stylus|sys|1.11.0
vscode-djaneiro|the|1.4.2
lorem-ipsum|Tyr|1.2.0
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
quokka-vscode|Wal|1.0.301
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|3.1.0

(8 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2020-06-29 02:38
Duplicate of #100436

**Comment by isidorn** [comment] 2020-06-29 08:21
@yume-chan thanks a lot for providing a duplicate link.

**Closed by isidorn** 2020-06-29 08:21 UTC
Labels: *duplicate
