### ISSUE TITLE
CSS color decorations increase the height of the line they appear in

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11299] opened 2016-08-31 09:54 UTC
Seen on OS X

The decorations are not vertically aligned on the line and push the line a few pixels down, making it taller than the average line.

![image](https://cloud.githubusercontent.com/assets/22350/18124236/ae431ddc-6f71-11e6-8d22-db53083bc056.png)

**Comment by aeschli** [comment] 2016-09-07 19:01
duplicate of #11296

**Closed by aeschli** 2016-09-07 19:01 UTC
