### ISSUE TITLE
Usage of "limit" in timelineoptions is not clear

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91629] opened 2020-02-26 23:12 UTC
https://github.com/microsoft/vscode/issues/91330

I haven't ran code with it yet, but from reading the API I'm not totally sure how I would use `TimelineOptions.limit`

```
  /**
   * The maximum number or the ending cursor of timeline items that should be returned.
   */
  limit?: number | string;
```

Maybe my mental model of paging coming from db/service land is preventing me from understanding it totally, but the docs could be better here. I'm not sure exactly when I would get a number versus a string versus undefined and how I would deal with those, and I'm not sure how limiting by a cursor would work.

Also, how would limit work and interact when `options.before == true`?

**Comment by eamodio** [comment] 2020-02-27 16:28
Thanks, I'll clarify it better in the docs.

Limit only applies when `before` isn't `true`. And if its a number, then you should only return that many items. If its a string, it should be treated as and ending cursor, so you should return all items between the cursor (if there is one) and the limit cursor.

I didn't want to introduce an `endCursor` or something like that, because it leaves it very ambiguous as to when the number limit would apply vs the ending cursor. But I'm certainly open to suggestion here.

**Comment by connor4312** [comment] 2020-02-27 16:39
What's the benefit to having an ending cursor as an alternative to a numeric limit? As an implementor, I'll be handling the numeric limit anyway, I would just need to write extra code to handle an end cursor.

**Comment by eamodio** [comment] 2020-03-23 17:48
Closing as a duplicate of #91722

**Closed by eamodio** 2020-03-23 17:48 UTC
Labels: bug, timeline
