### ISSUE TITLE
In JSX does not create new line between tags with right indentation after heating enter

### ISSUE THREAD

**Issue by twoperkg** [Microsoft/vscode#61954] opened 2018-10-27 17:34 UTC
- VSCode Version: 1.28.2
- OS Version: Mac OS 10.14

In .js or .jsx I have strange behaviour. When I have cursor between tags and press enter the vscode does not create empty line between tags and put cursor back to empty line with right indentation. It moves tag to new line. Then I have to create manually empty line between tags and indentation.
Actually is does behave as it should when tag does not have any attributes. But when ever I pass any attribute to tag it start to behave as I mentioned above. Have to mention that in .html files it behaves as expected even with attributes in tags. I have tried to disable all extensions, install insiders versions but getting the same behaviour.

Does this issue occur when all extensions are disabled?: Yes

Heres is JS/JSX:
![jsx](https://user-images.githubusercontent.com/42322073/47677345-8029d480-dbc7-11e8-95e4-d27c6800703d.gif)

Heres is HTML behaviour:
![html](https://user-images.githubusercontent.com/42322073/47677363-8f108700-dbc7-11e8-9427-27dc0ad9dd44.gif)

**Comment by mjbvz** [comment] 2018-10-29 19:04
Can you please provide a gif or screenshots or the problem, along with a small snippet of code that demonstrates the issue

**Comment by mjbvz** [comment] 2019-04-09 21:34
Duplicate of #65955

**Closed by mjbvz** 2019-04-09 21:34 UTC
Labels: bug, editor-autoindent, javascript, typescript
