### ISSUE TITLE
Unable to open first editor from Open editors list

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#100839] opened 2020-06-23 10:11 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Make sure that you don't have editor grups and have several files open.
1. Click on any file but first - list item is highlighted and active editor tab is changed.
1. Click on first editor in list - list item is highlighted but active editor tab stays same.

Same behavior if I navigate to first item with keyboardand press <kbd>Enter</kbd>.

Can't reproduce if I have editor groups, context menu and Close Editor button works as expected.

VS Code version: Code - Insiders 1.47.0-insider (269f0fdd83f1e6611dd0c6d225a1685719eafedb, 2020-06-22T05:53:42.894Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yume-chan** [comment] 2020-06-23 11:56
Duplicate of #100528

**Comment by IllusionMH** [comment] 2020-06-23 12:00
@yume-chan thank you!

**Closed** 2020-06-23 12:00 UTC
