### ISSUE TITLE
Invalid git display in editor

### ISSUE THREAD

**Issue by hwd-2020** [microsoft/vscode#176881] opened 2023-03-12 03:14 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.76.1
- OS Version: windows 11

Steps to Reproduce:

<img width="1260" alt="屏幕截图 2023-03-12 110147" src="https://user-images.githubusercontent.com/65169631/224522143-557c2e62-3237-4503-9661-044fbe6d7234.png">
<img width="1260" alt="屏幕截图 2023-03-12 110542" src="https://user-images.githubusercontent.com/65169631/224522157-44307bfd-9802-4fa5-9b45-446951e77b7d.png">
No green mark is displayed at the position of the code line

**Comment by hwd-2020** [comment] 2023-03-12 05:03
git output

2023-03-12 12:59:19.840 [info] 日志级别: Info
2023-03-12 12:59:19.840 [info] 正在验证在以下位置找到的 git: "C:\Program Files\Git\cmd\git.exe"
2023-03-12 12:59:19.874 [info] 将使用位于 "2.39.2.windows.1" 的 Git "C:\Program Files\Git\cmd\git.exe"
2023-03-12 12:59:19.949 [info] > git rev-parse --show-toplevel [69ms]
2023-03-12 12:59:19.949 [info] fatal: not a git repository (or any of the parent directories): .git
2023-03-12 12:59:19.987 [info] > git rev-parse --show-toplevel [34ms]
2023-03-12 12:59:19.987 [info] fatal: not a git repository (or any of the parent directories): .git
2023-03-12 12:59:30.954 [info] > git rev-parse --show-toplevel [41ms]
2023-03-12 12:59:30.954 [info] fatal: not a git repository (or any of the parent directories): .git
2023-03-12 12:59:43.375 [info] > git rev-parse --show-toplevel [38ms]
2023-03-12 12:59:43.411 [info] > git rev-parse --git-dir --git-common-dir [32ms]
2023-03-12 12:59:43.417 [info] Open repository: d:\新建文件夹
2023-03-12 12:59:43.430 [info] No remotes found in the git config file.
2023-03-12 12:59:43.459 [info] > git config --get commit.template [36ms]
2023-03-12 12:59:43.465 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [36ms]
2023-03-12 12:59:43.503 [info] > git status -z -uall [34ms]
2023-03-12 12:59:43.515 [info] No remotes found in the git config file.
2023-03-12 12:59:43.552 [info] > git config --get commit.template [39ms]
2023-03-12 12:59:43.560 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [40ms]
2023-03-12 12:59:43.596 [info] > git status -z -uall [33ms]
2023-03-12 12:59:43.985 [info] > git check-ignore -v -z --stdin [37ms]
2023-03-12 13:00:05.720 [info] 日志级别: Info
2023-03-12 13:00:05.720 [info] 正在验证在以下位置找到的 git: "C:\Program Files\Git\cmd\git.exe"
2023-03-12 13:00:05.751 [info] 将使用位于 "2.39.2.windows.1" 的 Git "C:\Program Files\Git\cmd\git.exe"
2023-03-12 13:00:05.804 [info] > git rev-parse --show-toplevel [47ms]
2023-03-12 13:00:05.977 [info] > git rev-parse --git-dir --git-common-dir [164ms]
2023-03-12 13:00:05.990 [info] Open repository: d:\新建文件夹
2023-03-12 13:00:06.066 [info] No remotes found in the git config file.
2023-03-12 13:00:06.188 [info] > git config --get commit.template [157ms]
2023-03-12 13:00:06.198 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [133ms]
2023-03-12 13:00:06.401 [info] > git status -z -uall [195ms]
2023-03-12 13:00:06.438 [info] No remotes found in the git config file.
2023-03-12 13:00:06.535 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [97ms]
2023-03-12 13:00:06.537 [info] > git config --get commit.template [110ms]
2023-03-12 13:00:06.598 [info] > git status -z -uall [57ms]
2023-03-12 13:00:06.641 [info] > git check-ignore -v -z --stdin [83ms]

**Comment by hwd-2020** [comment] 2023-03-12 05:59
git output is not triggered when switching files

**Comment by vsDizzy** [comment] 2023-03-12 09:45
this is duplicate of https://github.com/microsoft/vscode/issues/176749

**Closed** 2023-03-20 19:04 UTC
