### ISSUE TITLE
Reproducible crash with regexp

### ISSUE THREAD

**Issue by joshuambg** [microsoft/vscode#172202] opened 2023-01-24 16:55 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3 
- OS Version: macOS 12.6

Steps to Reproduce:

1. Open large file with JSX
2. Search file for regexp: `\((?:[^<]|\n)+<` 
  - Copy & Paste in search
3. On Mac get message application is not responding

**Comment by IllusionMH** [comment] 2023-01-24 18:54
Probably related to #30874 even if proveded example doesn't contain obvious backtracking.

However https://github.com/microsoft/vscode/issues/171514#issuecomment-1385811810 sounds promising.

**Comment by andreamah** [comment] 2023-01-30 16:49
Likely a duplicate of https://github.com/microsoft/vscode/issues/30874

**Closed by andreamah** 2023-01-30 16:49 UTC
