### ISSUE TITLE
IntelliSense not working

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#26661] opened 2017-05-15 15:11 UTC
- VSCode Version: 1.12
- OS Version: Linux Ubuntu 16.04

I don't know how to reproduce that, but after some time I don't get any suggestions it shows to me just `Loading...` and that's it. No errors in TypeScript output, no errors in developer tools. Everything is fixed after I did VS Code restart.

**Comment by xdave** [comment] 2017-05-15 15:23
I can second this.  Restarting vscode is an extremely common occurrence.

**Comment by JannieI** [comment] 2017-05-16 09:24
I run VSCode 1.12.2 & Ubuntu 16.04.  Same problem since 2 days ago

**Comment by lbellows** [comment] 2017-05-25 01:06
I've gotten this recently as well on Windows and 1.12.2  Mostly using TS and JS.

**Comment by svipben** [comment] 2017-05-25 01:18
The weird thing there's no errors, nothing. If somebody will get this problem again, check if you get code validation, just write bad code and check if you get errors/warnings, if there's no errors/warnings it will be related with language server.

**Comment by mjbvz** [comment] 2017-05-25 01:18
If you are seeing this issue, first try out insiders builds which may have resolved it. If you are still running into the problem on our insiders builds, please try collecting a trace of the TypeScript server:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Thanks

**Comment by lbellows** [comment] 2017-05-25 01:26
Mine did say something about 'tsserver crashed' but then it said it restarted but the intellisense didnt work.  I'll try to get more detailed info.

**Comment by atrefz** [comment] 2017-05-25 02:22
I also have this issue. For all those that are also suffering, a better workaround than restarting Code is to just CMD+Shift+P -> Reload Window. That is somewhat faster than restarting.

**Comment by mjbvz** [comment] 2017-05-26 22:54
In the current insiders builds, there's also a `Restart TS Server command` that should be even quicker. This command should be in VSCode 1.13 as well

If you find yourself using these workarounds though, please let us know and try collecting a trace so that we can investigate further. We want to fix bugs with the ts extension and ts server so that you never have to do this

**Comment by mjbvz** [comment] 2017-05-31 03:22
Closing this issue as it not actionable without logs or additional information

**Closed by mjbvz** 2017-05-31 03:22 UTC
Labels: needs more info
