### ISSUE TITLE
branch name conceals folder name

### ISSUE THREAD

**Issue by luminofoor** [microsoft/vscode#196575] opened 2023-10-25 10:45 UTC
Type: <b>Feature Request</b>

in source control the branch name hides folder name. Solution would be to put it in second row, please fix it soon

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 5.15.0-87-generic
Modes:

**Comment by lszomoru** [comment] 2023-10-25 11:47
@luminofoor, could you please provide a screenshot? Thanks!

**Comment by luminofoor** [comment] 2023-10-25 12:05
![Untitled](https://github.com/microsoft/vscode/assets/147694603/2cfee36c-eb44-4bf4-b381-e1cac2da7a84)
there is only partial folder name and then three dots (...)

**Comment by MynockSpit** [comment] 2024-04-16 23:40
This problem gets even worse if you're not willing to give source control 500 px of width. 

An example:

```
prc-autodiscovery
prc-ops-tooling
prc-runbooks
ranger-flash-tools
ranger-host-agent
ranger-host-agent-configs
ranger-host-configs
```

Even in the best-case scenario (all on `main` or an otherwise short branch name), you still can't tell between `ranger-host-agent` and `ranger-host-agent-configs`.

![image](https://github.com/microsoft/vscode/assets/5713867/58789272-38d9-4e5b-8850-2fe3b19635b8)

In a worst-case scenario, it gets much harder to tell them apart.

![image](https://github.com/microsoft/vscode/assets/5713867/21f52de8-a847-453c-acf8-693a3652c305)

It's not reasonable to support arbitrarily long branch and folder names, but as this example shows, even reasonably-sized folder and branch names cause issues.

---

@luminofoor suggested a second row as a way to solve it, and while that would work, I would personally prefer a mechanism to hide "branch" and "sync" the same way you can currently hide "commit", "refresh", and "commit graph". I just don't need that information in the "Source Control Repositories" panel.

**Comment by lszomoru** [comment] 2024-12-20 16:46
Duplicate of [#207814](https://github.com/microsoft/vscode/issues/207814)

**Closed by lszomoru** 2024-12-20 16:46 UTC
Labels: git, ux, under-discussion
