### ISSUE TITLE
cursor jumps to the bottom

### ISSUE THREAD

**Issue by achillesss** [Microsoft/vscode#47422] opened 2018-04-08 08:59 UTC
Issue Type: <b>Bug</b>

im coding in golang.

my cursor jumps to the page bottom everytime after I save the code with 'command+S'

'format when save' is on

this problem exists in a history version, and this version. it makes me very unhappy

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.37GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
solidity|Jua|0.0.37
solidity-extended|bea|3.0.2
better-toml|bun|0.3.2
Go|luk|0.6.78
mssql|ms-|1.3.0
python|ms-|2018.3.1
rust|rus|0.4.1
RustyCode|sav|0.19.1
JavaScriptSnippets|xab|1.5.0
vscode-proto3|zxh|0.1.3

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2018-04-08 14:52
I think duplicate of #47382

**Closed** 2018-04-08 14:52 UTC
Labels: *duplicate
