### ISSUE TITLE
Settings Search Results Folded On Clear

### ISSUE THREAD

**Issue by dusski** [microsoft/vscode#146469] opened 2022-03-31 19:35 UTC
Issue Type: <b>Bug</b>

1. Open Settings
2. Search for something that doesn't exist (for example, "kernel")
3. Clear the search field by ctrl+a > backspace

Expected result:
Settings overview taking the full height of the window

Actual result:
Settings overview is taking just a couple dosen pixels at the top below search. They are still scrollable though, just very tiny. 

I am on a 2k screen if this counts as useful info.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.28GB free)|
|Process Argv|. --crash-reporter-id efe5d7fb-770a-4014-a8b0-d2a22677d12c|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
switcher|adr|1.0.4
vscode-angular2-files|ale|1.6.4
ng-template|Ang|13.3.0
gitstash|art|5.1.0
atlascode|atl|2.10.11
path-intellisense|chr|2.8.0
vscode-autohotkey-plus|cwe|2.6.2
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
gitlab-workflow|Git|3.41.2
vue-snippets|hol|1.0.4
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
volar|joh|0.33.10
vscode-github|Kni|0.30.7
copilot-vscode|Met|1.3.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.21.0
remote-wsl|ms-|0.66.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5449
debugger-for-edge|msj|1.0.15
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
code-spell-checker|str|2.1.11
gistfs|vsl|0.3.0
vscode-jumpy|wma|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30463512

```

</details>

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/1636007/161135990-35c6a00e-b84a-4e71-a33d-c5ee6dfcba17.png)<br>
![image](https://user-images.githubusercontent.com/1636007/161136187-e211f0f5-2267-4bc3-9617-2ef9d62d4db7.png)<br>

</details>

**Comment by rzhao271** [comment] 2022-03-31 20:22
Duplicate of https://github.com/microsoft/vscode/issues/146285.
It will be in the next recovery release (i.e. 1.66.1). You can also use [Insiders](https://code.visualstudio.com/insiders/) if you want to get the fix faster.

**Closed** 2022-03-31 20:51 UTC
Labels: *duplicate, new release
