### ISSUE TITLE
workbench.action.terminal.clear does not clear terminal output

### ISSUE THREAD

**Issue by nathagey** [Microsoft/vscode#49241] opened 2018-05-04 19:20 UTC
- VSCode Version: 1.23.0
- OS Version: macOS v10.13.4 

Steps to Reproduce:

1. Start an NPM script in terminal that stays open, and has terminal output.
2. Focus on the terminal window.
3. Use default `⌘ + K` keyboard shortcut to clear terminal output.
4. `^L` shows up at the end of the output, and terminal does not clear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2018-05-07 03:35
Duplicate of https://github.com/Microsoft/vscode/issues/49162

**Closed by rebornix** 2018-05-07 03:35 UTC
Labels: new release
