### ISSUE TITLE
Add file icons support in the explorer

### ISSUE THREAD

**Issue by marzubov** [Microsoft/vscode#211] opened 2015-11-19 13:20 UTC
Can you please add file icons support in the tree view?

I know that access from extension to the DOM is restricted. But it will be good to add some language-id attribute to the tree-view element. For example in the [render function](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L219). So it will be easy to modify view of files with different types with CSS, without modifying DOM.

And also It will be nice to add possibility to add/modify directly CSS from extension.

**Comment by samueleaton** [comment] 2015-11-21 20:42
I agree. Here is a screenshot of what I have in sublime. 

![screen shot 2015-11-21 at 1 41 13 pm](https://cloud.githubusercontent.com/assets/9119269/11320456/a16777bc-9055-11e5-905e-ebe213358a43.png)

**Comment by roddolf** [comment] 2016-01-26 21:47
+1

**Comment by philipgiuliani** [comment] 2016-01-27 08:13
+1 I can find files much faster with the icons!

![bildschirmfoto 2016-01-27 um 09 09 45](https://cloud.githubusercontent.com/assets/5446019/12607547/21a3b10c-c4d6-11e5-9f54-4c0e80c98c67.png)

**Comment by zippoxer** [comment] 2016-01-30 17:20
Any progress on this?

**Comment by pflannery** [comment] 2016-01-31 04:57
+1

Maybe its possible to add a language and\or file-ext attributes [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L277) for themes to render icons?

**Comment by TheColorRed** [comment] 2016-02-06 15:10
+1

I mostly have issues trying to distinguish the difference between a file and a folder quickly.

**Comment by snpai** [comment] 2016-02-18 12:28
What is interesting is that there is logic in place to add icon classes:
[https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts](url)

```typescript
private iconClass(element: FileStat): string {
		if (element.isDirectory) {
			return 'folder-icon';
		}

		return 'text-file-icon';
}
```

As seen above, vscode currently adds a folder-icon css class to all folders but a style is not defined for it. So if you want to see folder icon in explorer, all you have to do is add the below style in **\<vs install path\>/resources/app/out/vs/workbench/workbench.main.css**

```css
.explorer-item.folder-icon {
    padding-left: 22px;
    background: url(./parts/files/browser/media/Folder.svg) 1px 4px no-repeat;
}
```
Here is a preview of it in action:
![Preview](http://i.imgur.com/XKVTUxN.png)

In it's simplest form, implementing the file icon feature would require modifying the above iconClass method to return 'text-file-' + getFileExtension(element.name) and adding corresponding icon svg/font to each css classes (i.e., text-file-js, text-file-md, etc.)

**Comment by philipgiuliani** [comment] 2016-02-18 12:31
Nice find @snpai. It would be very easy if they could add another class like `text-file text-file-md`. So extensions could use it to just add another CSS with all the icons.

**Comment by nelsonlaquet** [comment] 2016-02-26 22:16
This feature is sorely needed, and is trivial to implement. I was able to use @pflannery's fork and https://github.com/mrmartineau/SetiUI-Icons-Sublime to add in default icons right into the my own build.

One thing though: some files should be themed based off of more than extension. package.json, gulpfile.js, etc should be themed based off of name. I suppose adding built-in support for specific filename classes would be better (faster/less cluttering to the DOM) than adding a class for the entirety of every file's name.

While we wait, does anyone have a comprehensive, "good" looking grayscale icon pack? The icon pack I used doesn't mesh very well with the dark theme and is a little distracting.

**Comment by pflannery** [comment] 2016-03-10 04:32
@nelsonlaquet you made a good point about the gulp, grunt and package.json files and thanks for linking the icons too. 
I've updated my PR which puts the filename in to attributes allowing special icons for specific files. 
I've also added support for css theming because I feel that this is the cleanest and simplest way to deliver this feature. 
Check out my comments here for more info https://github.com/Microsoft/vscode/pull/3200#issuecomment-194656772

**Comment by ianwesterfield** [comment] 2016-03-10 20:05
I implemented this in a local copy with relative ease - supported color and light/dark theme, but didn't issue a PR on it because I thought perhaps there would be issues with licensing as not one open font contains good icons for all types of files.

I might submit it anyway, but I do believe it is best handled through an extension should they ever expand what an extension has access to.

**Comment by nepaul** [comment] 2016-03-24 03:49
+1
I can find files much faster with the icons!

**Comment by fa7ad** [comment] 2016-04-01 16:37
Is the file tree exposed to extensions api? if you can expose it, i think that would allow the community to create an extension for this and for any further opinionated customizations all the while VSCode itself can remain neutral on the issue

**Comment by ivogabe** [comment] 2016-04-01 17:06
If that would be added, I'd like to port my icon extension ([Brackets Icons](https://github.com/ivogabe/Brackets-Icons)) for Brackets to VS Code. In Brackets, an icon provider can be added, which is a function that returns an icon as a DOM element for a specified file name ([docs](http://brackets.io/docs/current/modules/project/ProjectManager.html#-addIconProvider)). Since VS Code doesn't expose the DOM, there should be a layer between, but similar ideas can be used.

**Comment by bpasero** [comment] 2016-04-01 17:21
No API atm to change the explorer.

**Comment by fa7ad** [comment] 2016-04-01 18:52
@bpasero is there plans for such a thing in the near future? if yes, any rough ETA?

**Comment by bpasero** [comment] 2016-04-01 18:55
@egamma @chrisdias please chime in.

**Comment by atilkan** [comment] 2016-04-05 00:22
+1

**Comment by donaldpipowitch** [comment] 2016-04-05 10:30
@bpasero Could you list the needed acceptance criteria to get a pull request merged? Maybe I could help then.

**Comment by bpasero** [comment] 2016-04-05 10:33
@donaldpipowitch I would think this feature should:
* be configurable with a flag in settings
* provide the necessary icons for all themes (SVG)

Still, our PM/UX might decide to veto. @chrisdias @stevencl please chime in.

**Comment by donaldpipowitch** [comment] 2016-04-05 10:35
@bpasero Thank you. Could you define "be configurable with a flag in settings" a little bit more? What do you want to configure?
- show/hide icons
- match existing (built in) icons to file patterns
- change existing (built in) icons to custom icons
- ...?

**Comment by bpasero** [comment] 2016-04-05 10:57
I think the first step would be to allow to show/hide built in icons. Being able to customize icons from themes is a lot larger task and would probably fall into the category of being able to theme the entire workbench (#3112)

**Comment by stevencl** [comment] 2016-04-05 11:07
In the past we had explored icons in the explorer but we were concerned about the 'Christmas tree' effect (where the number of differently coloured icons is distracting rather than helpful). Perhaps it is due more to the icon designs we used at the time but when we experimented with this we found that when we took the icons away there was no negative impact on productivity or product satisfaction. So we went with that option as we have always tried to design the product so that the main focus is on the code and not on any of the UI.

However, after saying all of that, we're obviously not opposed to anything that helps users use the product more effectively so if the consensus is that this adds value, I am fine with it. I would just reiterate @bpasero's request that there should be an option to enable and disable the icons in the explorer.

**Comment by donaldpipowitch** [comment] 2016-04-05 13:18
Thanks. I'll try it. Please be patient, it would be my first contribution to the vscode code base.

**Comment by fa7ad** [comment] 2016-04-05 16:15
@stevencl I understand your concerns, to some people it can be distracting. that's why I think the idea of being able to disable/enable it is a good one.

One other thing I want to suggest is the use of SVG icons, rather than raster types like png, that way the icons could be following the color scheme of the current theme and not be multi-colored and distracting.

**Comment by Tyriar** [comment] 2016-04-05 17:20
I'd personally love to see this added, good quality icons that are easy to distinguish are very useful in reducing the time it takes to find a file in the file explorer. Plus when done right, it can makes the editor look quite beautiful.

Having said that, I don't see this working with a single icon set for dark and light themes. It should be extensible so that users can develop "icon packs" and plug them into any theme.

Re Christmas tree effect: They don't even need to be color icons or even on by default.

**Comment by pflannery** [comment] 2016-04-05 18:26
This is what PR #3200 already solves for this feature:

- Icons packs as a standalone icon theme (they can also be included with colour themes)
- 'No icons' as an option (currently defaults to this)
- Capable of using SVG as icons
- Colouring of file\folder resources

What it doesn't include is:

- Exposing Icon or Colouring via javascript extensibility.
- User theme settings (i.e. settings stored globally or with the .vscode folder)

I believe we're now just waiting for the 6 month goal plan as mentioned here https://github.com/Microsoft/vscode/pull/3200#issuecomment-196675666 to get the green light on this feature.

**Comment by donaldpipowitch** [comment] 2016-04-06 04:27
@pflannery I'm confused. I thought this pull request was rejected. Do you want to finish it? I wouldn't start another pull request then.

**Comment by Tyriar** [comment] 2016-04-06 05:26
@donaldpipowitch see https://github.com/Microsoft/vscode/pull/3200#issuecomment-196675666 for context

**Comment by fa7ad** [comment] 2016-04-07 13:08
so there's no hope for icons? :cry: why?!

**Comment by pflannery** [comment] 2016-04-07 13:22
@donaldpipowitch From what I understand the PR is on hold until they make their plan after the March release. The PR has not been closed by anyone on the team and I'm still happy to push it through. 

@fa7ad I'm sure icons will make it and hopefully sooner than later.

**Comment by donaldpipowitch** [comment] 2016-04-07 14:47
@pflannery Okay, thanks. Good luck to you and thank you for the pull request so far :)

**Comment by jeysak** [comment] 2016-04-15 00:03
![folder_opened](https://cloud.githubusercontent.com/assets/18233552/14547467/49922aea-0284-11e6-82d0-e93259de8d8d.png)
![folder](https://cloud.githubusercontent.com/assets/18233552/14547465/497c8960-0284-11e6-87b6-2aa5f58e9940.png)
![textfile](https://cloud.githubusercontent.com/assets/18233552/14547466/4980cc32-0284-11e6-91c8-62dbc7e3a77d.png)
My icons for the dark theme.

**Comment by cloverhsc** [comment] 2016-04-15 07:32
+1

**Comment by fa7ad** [comment] 2016-04-17 10:05
@jeysak how's you do that? make a gist. until vscode master does something, I need a temporary solution :3

**Comment by jeysak** [comment] 2016-04-18 04:51
@fa7ad read snpai comment.

**Comment by skol-pro** [comment] 2016-04-18 10:07
Cool, @snpai stuff is working, except that the default Folder isn't showing up, weird :(

**Comment by equinusocio** [comment] 2016-04-29 10:07
![screen shot 2016-04-29 at 12 04 57](https://cloud.githubusercontent.com/assets/10454741/14913359/c5ddf0e6-0e02-11e6-8b64-a1482642ad9d.png)

### CSS

```css
.monaco-tree-row .content .sub-content .explorer-item.folder-icon {
    padding-left: 22px;
    background: url(./parts/files/browser/media/Folder_inverse.svg) 1px 4px no-repeat;
}
.monaco-tree-row.expanded .content .sub-content .explorer-item.folder-icon {
    padding-left: 22px;
    background: url(./parts/files/browser/media/Folder_opened.svg) 1px 4px no-repeat;
    background-size: 16px;
}
.explorer-item.text-file-icon {
    padding-left: 22px;
    background: url(./parts/files/browser/media/File.svg) 1px 3px no-repeat;
    background-size: 16px;
}
```

### Icons
[icons.zip](https://github.com/Microsoft/vscode/files/242099/icons.zip)

**Comment by TheColorRed** [comment] 2016-04-29 15:59
Wow these Icons make it look like a whole new editor!

If anyone makes it so Icons can be added they should make sure people can add Icon packs to the marketplace that can be used with the editor.

**Comment by FeaRCODE** [comment] 2016-05-12 06:22
@jeysak Please tell me how you did that: https://github.com/Microsoft/vscode/issues/211#issuecomment-210210437

**Comment by snpai** [comment] 2016-05-12 06:28
@FeaRCODE Please refer to my comment above

**Comment by Tyriar** [comment] 2016-05-12 06:37
@FeaRCODE RE your comment on https://github.com/Microsoft/vscode/pull/3200#issuecomment-218669706 (which won't be read by many people as its closed).

> @Tyriar I agree. I am not sure how they went about their research, but a monotone list of names is hard to look at when I have a ton of files. Also, his comment on "multi-colored" distracting icons is false. As pictured here, these icon DRASTICALLY improve the speed at which i can find my folder/files. https://github.com/Microsoft/vscode/issues/211#issuecomment-210210437

> I think that themes should also control what the icons look like and i do agree there should be an option to disable them. 

I'm not that big on differentiating folders and files personally, as the expand/collapse arrows accomplish that currently. I want it on a file type basis so that it's easier to tell what file type files are, plus it will make the editor more attractive (subjective of course).

**Comment by FeaRCODE** [comment] 2016-05-12 06:41
@Tyriar I guess you're right. For some reason my mind can process the icons faster. I prefer them regardless :)

**Comment by skol-pro** [comment] 2016-05-12 07:04
I know this is only "half-related" but is there a way to alter the file viewer using the vsCode API ?
What I'd like to do is add the folder behavior to .ts files, so that we can expand it from the viewer and see .js version. Any one any idea ? :)

**Comment by marzubov** [comment] 2016-05-12 08:49
Hello.

I know that 6 months ago icons weren't in vscode planning list. And I know that initially you wanted to keep workbench very simple.
As you can see here, many people like icons which help them to process files faster.

In [update 1.1](https://code.visualstudio.com/updates/) you introduced [Visual design](https://github.com/Microsoft/vscode/issues/224#issuecomment-213015687) proposal which modifies workbench and editor. It will be nice to hear if vscode team reviewed possibility to add icons.

@bpasero any thoughts?

**Comment by bpasero** [comment] 2016-05-12 09:05
@marzubov we did not have a chance to talk about this feature request with the UX team. as you can understand, tabs are currently our #1 priority and gets our full attention. this might keep us busy for another few sprints because there are related follow up work items (empty layouts, horizontal split, etc.).

**Comment by marzubov** [comment] 2016-05-12 09:20
@bpasero ok, got it.
Thanks for such a quick response.
Keep us in touch.

**Comment by sbowler** [comment] 2016-05-16 21:33
At the very least you should be able to have different icons for different file extensions I believe. Ideally it might be nice to support some sort of regex matching so you could have custom icons for Angular Javascript files named with -controller.js for example. 

I for one would rather have this then tabs and it seems like a lot less work for at least some basic start to be implemented.

**Comment by CristyTarantino** [comment] 2016-05-27 11:40
+1

**Comment by nelsonlaquet** [comment] 2016-05-27 19:43
Yeah, I'm not sure why so many people are complaining about tabs, which are a major UI overhaul and virtually unnecessary (with most of the reasons being "because every other editor has them")... Icons are a much easier thing to implement and have a considerably higher return on investment in regards to usability.

**Comment by vothanhdat** [comment] 2016-05-29 19:48
Thanks you for @equinusocio . From your totural, i have an some modify in file workbench.main.js and workbench.main.css for my web project.

First, open file workbench.main.js, find string 'text-file-icon', and we will see an function : 
`t.prototype.iconClass=function(e){return e.isDirectory?"folder-icon":"text-file-icon"}` , and we need modify it  to return and class name for each file type. Here is my modify : `t.prototype.iconClass=function(e){if(e.isDirectory)return'folder-icon';var type=e.name.substring(e.name.lastIndexOf('.')+1).toLowerCase();switch(type){case'js':case'jsx':case'css':case'scss':case'md':case'json':case'html':case'htm':return type+'-file-icon';default:return'text-file-icon';}}`.
Then we just  add some line css in file workbench.main.css and add icon ...

Here is my screenshort : 
![capture](https://cloud.githubusercontent.com/assets/8221386/15635721/ef53e3d8-2610-11e6-8ced-e6ef23920b5a.PNG)

**Comment by robertohuertasm** [comment] 2016-05-31 00:01
I've put all this information in a easy list of steps to make this work with sublime icons:
https://github.com/robertohuertasm/vscode-icons

**Comment by nelsonlaquet** [comment] 2016-05-31 01:12
Fantastic! Works great!

**Comment by fa7ad** [comment] 2016-05-31 16:17
@robertohuertasm jsut forked your repo. will try to automate the process using python or bash script. will try to push it by tomorrow, no guarantees though :stuck_out_tongue:

**Comment by robertohuertasm** [comment] 2016-05-31 16:21
@fa7ad ok! I was about to start the same process but you're very welcome to contribute to the cause! 😉

**Comment by robertohuertasm** [comment] 2016-06-01 00:50
Hi I've just published an extension. It's still in beta but it seems to be working in OS X and Windows.
https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons

**Comment by Tyriar** [comment] 2016-06-01 01:37
@robertohuertasm you should probably put a disclaimer in the README indicating that it's literally modifying vscode and that the extension will probably break every update (and potentially break the update).

**Comment by robertohuertasm** [comment] 2016-06-01 07:11
@Tyriar you're right. I assumed that every update will rewrite the mods. I'll address the rollback behavior and warn the users about the inner workings of the extension.

**Comment by robertohuertasm** [comment] 2016-06-01 09:54
@Tyriar, thanks for your feedback. It's done. I've added a small disclaimer and enhanced the rollback functionality to avoid potential conflicts with vs code updates.

**Comment by asvetliakov** [comment] 2016-06-01 10:06
I hope this extension will be a warning bell for vs code team that something is not going well and people started to write extensions which are modifying vscode files directly.

**Comment by Tyriar** [comment] 2016-06-01 18:10
Thanks @robertohuertasm.

@asvetliakov I really want this feature too, the team is spread a little thin at the moment is the main blocker for this.

**Comment by gsaadeh** [comment] 2016-06-02 17:43
Thank you for the very useful extension @robertohuertasm. It's unfortunate that this feature is not even scheduled although the logic is pretty much there. How would be move away from Sublime or Atom if they don't have visual indicator of what files they are dealing with. I guess it's time for a pull request.

**Comment by Tyriar** [comment] 2016-06-02 18:19
@gsaadeh there was already a PR put out by @pflannery, the problem is this would be a new API and we need to make sure it's done right. The icon guidance in this issue is done with a hack so it couldn't be contributed.

**Comment by fa7ad** [comment] 2016-06-02 18:28
@Tyriar do you guys (core team) have a proper API planned then? I understand this is a hack, but this is as close as we can get without support from the core team.

**Comment by gsaadeh** [comment] 2016-06-02 18:28
Thanks for the explanation @Tyriar. I agree that it's a hack but at least it will keep a few of us happy until the official support. If there is an existing plan of how you guys want to implement it, I will be very glad to contribute.

**Comment by Tyriar** [comment] 2016-06-02 18:49
A few of us have been talking about it, we need to have a team-wide discussion ideally in a GitHub issue.

**Comment by marzubov** [comment] 2016-06-02 19:45
Thanks, @robertohuertasm for making an extension that gives file icons to the vscode is really nice, even if it's hacky.
Since the team is spread and focused on other tasks, I think we could analyze and propose some changings to existing extension API, that will allow fully support extensions like `vscode-icons` without any hacks and won't break existing one. Then we can apply changes to the fork and make a custom build, so users could easily install it and perhaps even update.
Any thoughts?

**Comment by Sequoia** [comment] 2016-06-14 15:43
I know I should know better than to armchair project-manage, but this feels like low hanging fruit with a big ROI. I like VSCode for it's deep support of various JS features + intellisense --icons aren't a make or break feature for me-- but there a lot of people for whom this *is* a make-or-break feature. I guarantee there are visually oriented folks who will try VSCode then quickly bounce back to Sublime/Brackets/whatever when they see that this basic feature is missing.

My intuition-based belief: **not having this feature will have a significant negative impact on the adoption of VS Code**. It's silly but I believe it's true. I care because I really like VS Code & I am recommending it to people, I want them to like it. 😸

**Comment by miguelchico** [comment] 2016-06-25 22:54
+1

**Comment by leaxoy** [comment] 2016-07-10 07:43
+1

**Comment by darkguy2008** [comment] 2016-07-21 17:33
Any progress on this? I want to replace sublime with vscode but it's hard to find file types without icons. I can't believe something so essential is missing...

**Comment by gsaadeh** [comment] 2016-07-21 17:55
@darkguy2008 For now you can use https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons until the official support. It works well!

**Comment by darkguy2008** [comment] 2016-07-21 19:08
@gsaadeh yeah I just found it, thanks! it takes some trial and error to get it installed and working at first though. It'd be a good idea to merge the extension in VSCode's core though :+1:

**Comment by MarkPieszak** [comment] 2016-07-26 15:34
Anyone having issues on Win7 with the vscode-icons install?
Running as administrator, installed & enabled it. Closing/reopening VSCode or anything doesn't help, can't see them :(

**Comment by wbsdty331** [comment] 2016-08-24 14:56
+1
Very useful feature.

**Comment by aeschli** [comment] 2016-09-02 12:35
Added support for file icon themes. See #10804 for documentation.

**Closed by aeschli** 2016-09-02 12:35 UTC
Labels: api, explorer-files, feature-request, plan-item
