### ISSUE TITLE
Open Recent yields Save prompt with Hot Exit enabled

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#17440] opened 2016-12-17 00:41 UTC
- VSCode Version: 1.8.0
- OS Version: Win10 version 1611

Steps to Reproduce:

1. Enable Hot Exit. (on by default)  Make changes in an editor, don’t save, and close VS Code, it closes with no Save prompt.  Restart Code and there’s the editor with unsaved changes.  So far, so good.
2. Now, when you have unsaved changes, use ctrl-R to switch to a recent editor. Save changes prompt appears. 

Expected: switches with no save prompt, caching the modified file (same as exiting VS Code)

**Comment by bpasero** [comment] 2016-12-17 08:24
I think this works "as-designed" because you are basically giving up the window that contains dirty files and in that case we ask to save. The same happens when closing a window with dirty files that is not the last window.

**Comment by Tyriar** [comment] 2016-12-17 08:29
Yes this is as designed, in the future it will be a little more flexible when hot exit triggers (see https://github.com/Microsoft/vscode/issues/15467), in the meantime it's quite conservative.

**Closed by Tyriar** 2016-12-17 08:29 UTC
Labels: hot-exit
