### ISSUE TITLE
Markdown: editor jumps up while typing having preview open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20436] opened 2017-02-10 16:43 UTC
Noticed this since a couple of days that when I type in the editor with markdown, sometimes the editor would jump up, even though I am not giving focus to the markdown preview that is opened on the right hand side.

This happens to me editing our release notes. I am on macOS and have a zoom level of 1.

![kapture 2017-02-10 at 17 43 00](https://cloud.githubusercontent.com/assets/900690/22835278/6b34eb02-efb8-11e6-9929-355f6875056c.gif)

I think I would never change the scrolling on the editor unless I am scrolling inside the markdown preview.

**Comment by tinyAdapter** [comment] 2017-02-15 11:04
Same happens on Windows 10 Build 14393. Zoom level is set to default.

**Comment by mattbierner** [comment] 2017-03-01 21:45
This was a general webview issue that I believe was fixed by #21531

There's still a little jitter in some our release notes due to image reloading, but we no longer jump to the top of the page. To fully fix the jitter caused by images, I think we would have to move to send dom deltas instead of recreating the document every time

**Comment by mjbvz** [comment] 2017-03-01 21:46
This was a general webview issue that I believe was fixed by #21531

There's still a little jitter in some our release notes due to image reloading, but we no longer jump to the top of the page. To fully fix the jitter caused by images, I think we would have to move to send dom deltas instead of recreating the document every time

**Closed by mjbvz** 2017-03-01 21:46 UTC
Labels: bug, markdown
