### ISSUE TITLE
TS/JS missing syntax hilighting in type information tooltips

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#79607] opened 2019-08-22 00:40 UTC
Issue Type: <b>Bug</b>

When hovering over a token, the rendered tooltip is in plaintext, as opposed to syntax highlighted text.

![image](https://user-images.githubusercontent.com/8586769/63477600-b710f580-c43a-11e9-8f05-8c7cb8bee5ad.png)
![image](https://user-images.githubusercontent.com/8586769/63477610-c09a5d80-c43a-11e9-9428-928d41d2196a.png)

(this is a purplebar editor on a non-saved file with filetype set to JS)

VS Code version: Code - Insiders 1.38.0-insider (ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8, 2019-08-21T13:23:36.029Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv|-psn_0_6661722|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment] 2019-08-22 00:50
Duplicate of https://github.com/microsoft/vscode/issues/79589 👍

**Closed** 2019-08-22 00:50 UTC
Labels: *duplicate

**Comment by JacksonKearl** [comment] 2019-08-22 00:53
Oops, thanks @RMacfarlane!
