### ISSUE TITLE
Integrated Terminal Misrendering Text

### ISSUE THREAD

**Issue by AwesomeCronk** [microsoft/vscode#120483] opened 2021-04-03 23:23 UTC
Issue Type: <b>Bug</b>

I have the powershell script winfetch installed and in my powershell profile (PowerShell 7). If I use the integrated terminal, it is completely unable ot properly render winfetch's output. It appears to make winfetch think that the terminal is about ten characters narrower than it actually is and when I run the powershell command for clearing the screen (aliased to cls by default), it prints the output below itself and then clears only part of the terminal. If I resize the terminal in VSCode or open a new folder in VSCode, the issue is fixed until next launch.
If I manually open a terminal (not VSCode opening it because I had it open last session), it works fine.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.60GB free)|
|Process Argv|--crash-reporter-id 9a6c8345-3bbe-4f26-ab0d-4ecc5573a7c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.13.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by AwesomeCronk** [comment] 2021-04-03 23:31
This is the output of winfetch on launch:
![image](https://user-images.githubusercontent.com/55630616/113494036-61bc1780-94aa-11eb-9c07-f277314a1f1e.png)
This is what happens when I run `cls`:
![image](https://user-images.githubusercontent.com/55630616/113494069-b364a200-94aa-11eb-9d16-57308a4415d0.png)

Again, if I resize the terminal slightly, these issues go away and everything works as expected.

**Comment by AwesomeCronk** [comment] 2021-04-03 23:33
Output of winfetch after resizing the terminal:
![image](https://user-images.githubusercontent.com/55630616/113494131-22da9180-94ab-11eb-81e4-56b45dd100a9.png)

**Comment by meganrogge** [comment] 2021-04-08 03:38
related to and likely Duplicate of #120004

**Closed by meganrogge** 2021-04-08 03:38 UTC
