### ISSUE TITLE
settings sync creates too many requests?

### ISSUE THREAD

**Issue by mwarger** [microsoft/vscode#112754] opened 2020-12-17 16:30 UTC
Issue Type: <b>Bug</b>

Doing something that affects settings sync (like resizing text) while having multiple windows open appears to hit some sort of rate-limiting error.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 8272335d-86bd-463b-8515-a55ed4b8469a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
tailwindcss-extension-pack|and|1.1.4
vscode-apollo|apo|1.17.1
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.5.6
rescript-vscode|che|1.0.2
npm-intellisense|chr|1.3.1
overmind-devtools-vscode|chr|0.0.36
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
vscode-deno|den|2.3.3
gitlens|eam|11.0.6
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vscode-diff|fab|1.4.0
vscode-jest-runner|fir|0.4.31
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.5
vscode-pull-request-github|Git|0.22.0
headwind|hey|1.7.0
easy-snippet|inu|0.6.2
vscode-git-add-and-commit|iva|2.1.1
reason-vscode|jar|1.7.13
vscode-markdown-notes|kor|0.0.21
tailwind-sass-syntax|mac|1.2.1
code-coverage|mar|1.2.3
vscode-language-babel|mgm|0.0.30
vscode-docker|ms-|1.9.0
mssql|ms-|1.10.0
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.154.1
vscode-typescript-tslint-plugin|ms-|1.3.2
vsliveshare|ms-|1.0.3303
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
color-highlight|nau|2.3.0
angular-console|nrw|15.0.0
docker-compose|p1c|0.3.5
prisma|Pri|2.13.0
vscode-yaml|red|0.13.0
mdx|sil|0.1.0
svelte-vscode|sve|102.8.0
markdown-links|tch|0.8.0
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.10
vscode-wakatime|Wak|4.0.9
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by lszomoru** [comment] 2020-12-17 18:56
@mwarger, looked at the service-side telemetry and between `2020-12-17 16:15 UTC` and `2020-12-17 16:50 UTC`, one of the Settings Sync regions has experienced an increased rate of throttling on requests made to Azure CosmosDB requests. There was no increase in the number of requests so we will work with our Azure partner team to understand the root cause of the throttling. 

As of `2020-12-17 16:50 UTC`, all service health indicators returned to a healthy baseline.
I will close this issue but please feel free to reopen if you are still seeing the issue. Apologies for the inconvenience.

**Closed by lszomoru** 2020-12-17 18:56 UTC
Labels: new release
