### ISSUE TITLE
missing imports should trigger on CommitCharacter

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#143384] opened 2022-02-18 16:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

- VS Code Version: 1.65.0-insider
- OS Version: 12.2.1

Steps to Reproduce:

1. open a node, ts project
2. write code `const p = path`
3. input `.` to accept `path` suggestion item

In flowing screenshot, when I input `.`, will not auto add `path` module.
If I just press `enter`, will auto import `path` module.

@mjbvz

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/154718895-f6e37d8e-2fa6-47e9-81e0-ce0552239349.png">

**Comment by mjbvz** [comment] 2022-03-09 22:52
This has the same root cause as https://github.com/microsoft/TypeScript/issues/31244

`isNewIdentifierLocation` is returned in this case, which disables all commit characters. Closing in favor of that and will continue investigating upstream

**Closed by mjbvz** 2022-03-09 22:52 UTC
