### ISSUE TITLE
Fold all regions not working for VSCode

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/vscode#46776] opened 2018-03-27 22:36 UTC
- VSCode Version: Code-Insiders
- OS Version:

Steps to Reproduce:

1. Create a javascript file with some contents and specify a region e.g.:

```
test.js
// #region
import { React } from "react-native"
// #endregion
```

2. Select command to 'Fold All Regions' and notice that the region does _not_ collapse as it should

**Comment by aeschli** [comment] 2018-03-28 10:33
duplicate of #44530

**Closed by aeschli** 2018-03-28 10:33 UTC
Labels: insiders
