### ISSUE TITLE
ctrl + z  Can undo closed files

### ISSUE THREAD

**Issue by awhlmycn** [microsoft/vscode#122158] opened 2021-04-26 02:30 UTC
1. Make changes to a file, save the file, then close it.
Reopen said file, hitting ctrl + z will undo the changes that was made before closing the file
How come it's possible to undo changes to a file that has been saved and closed previously?
Feature request: once a file have been closed, ctrl + z shouldn't undo the changes that was made before the file was closed

**Comment by markkyaw** [comment] 2021-04-26 04:33
Duplicate of issue https://github.com/microsoft/vscode/issues/122127

**Comment by alexdima** [comment] 2021-04-26 07:24
You can configure `"files.restoreUndoStack": false` to avoid restoring the undo stack when the file is reopened.

**Closed by alexdima** 2021-04-26 07:24 UTC
