### ISSUE TITLE
pasting HTML add incorrect closing tag at the first line which break html file tags

### ISSUE THREAD

**Issue by amro93** [microsoft/vscode#228228] opened 2024-09-11 12:24 UTC
Type: <b>Bug</b>

pasting the following html (
<div class="col-12 col-md-6">
                <mat-form-field class="w-100">
                </mat-form-field>
            </div>
)
results:  <div class="col-12 col-md-6"></div>
                <mat-form-field class="w-100">
                </mat-form-field>
            </div>

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by aeschli** [comment] 2024-09-12 08:38
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-12 08:38 UTC
