### ISSUE TITLE
The settings menu on Activity Bar is not fully displayed if zoomed in

### ISSUE THREAD

**Issue by adam8157** [microsoft/vscode#99830] opened 2020-06-11 06:44 UTC
- VSCode Version: 1.46
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. View -> Appearance -> Zoom In
2. Click the settings icon on Activity Bar

Does this issue occur when all extensions are disabled?: Yes
![Normal look](https://user-images.githubusercontent.com/153160/84353516-e5daa100-abf1-11ea-9680-20987b58afd9.png)
![Zoomed in](https://user-images.githubusercontent.com/153160/84353523-e7a46480-abf1-11ea-88b1-c400f966264c.png)

**Comment by sbatten** [comment] 2020-06-11 16:05
duplicate of https://github.com/microsoft/vscode/issues/40262

**Closed** 2020-06-11 16:05 UTC
Labels: *duplicate
