### ISSUE TITLE
Npm install fails during finalize with VS Code Open.

### ISSUE THREAD

**Issue by mikerhyssmith** [Microsoft/vscode#26644] opened 2017-05-15 08:27 UTC
- VSCode Version: 1.13.0-insider
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open VS Code
2. Run npm install in a directory currently open in VS Code

Npm install will run through to the finalize stage at which point:
`Error: EPERM: operation not permitted, rename` for some library is thrown. The library installing when this error occurs varies with each install.

Closing VS code and running npm install again will work correctly.

**Comment by egamma** [comment] 2017-05-15 09:18
@mikerhyssmith what kind of proect is contained the current directory when this happens? Is this a JS, TS project, is it large?

@mattbierner I suspect that automatic type acquisition or the TS language server is keeping some files open.

**Comment by mikerhyssmith** [comment] 2017-05-15 09:28
It is a relatively large typescript project yes !

**Comment by egamma** [comment] 2017-05-15 13:51
@mattbierner This reminds of https://github.com/Microsoft/TypeScript/issues/7762, but this issue has been closed.

**Comment by mikerhyssmith** [comment] 2017-05-15 13:56
I'm using version 2.3.2 of Typescript if that's any help !

**Comment by mjbvz** [comment] 2017-05-16 04:49
@mikerhyssmith Can you please try setting: `"typescript.disableAutomaticTypeAcquisition": true` and then seeing if the issue still reproduces? Also, can please make sure an extension is not the root cause by starting code with `--disable-extensions`

**Comment by mikerhyssmith** [comment] 2017-05-16 09:13
`"typescript.disableAutomaticTypeAcquisition": true `this seems to have fixed the issue. Noticeably a different typescript project maybe a little smaller doesn't seem to have the same issue.

**Comment by schneiderpat** [comment] 2017-05-17 08:28
I have a very small ts project and I´m facing this issue too.
This also seemes to be fixed when closing the editor onces. 
After that I can run ```npm install``` without any issues and vs code open.

**Comment by mjbvz** [comment] 2017-05-19 23:03
Thanks @mikerhyssmith. I've opened https://github.com/Microsoft/TypeScript/issues/15961 to continue the investigation of this issue on the TypeScript side

**Closed by mjbvz** 2017-05-19 23:03 UTC
Labels: javascript, upstream
