### ISSUE TITLE
Cursor in incorrect position

### ISSUE THREAD

**Issue by rmgreenstreet** [microsoft/vscode#107749] opened 2020-09-29 20:27 UTC
Issue Type: <b>Bug</b>

Occasionally, when editing a javascript file, using the mouse or arrow keys to move the cursor to a position within a line results in visual representation of the cursor being placed approximately three spaces to the right of the selected position.

Using the mouse or the shift+arrow keys to select a line or part of a line still shows the cursor out of position, but does select the "intended" text.

**I am unsure how to reproduce the issue on purpose**

In the screenshot below, the item "textContent" has been double-clicked in order to select that part of the line, but the selection shows that it begins at the "x" and continues for three spaces past the end of "textContent".

If ctrl+c is pressed, then ctrl+v, the correct text, "textContent" is copied and pasted, but it is very confusing to try to move to a position within a line to make changes with this issue

![image](https://user-images.githubusercontent.com/50469309/94610454-f167db80-0265-11eb-8f1b-0c88cd299bda.png)

In this screenshot, the mouse was used to click past the end of the line beginning with "sectionTitleField.value". There are no extra spaces after the semicolon, but it appears that the cursor is placed three spaces past the semicolon. In this case, if the backspace key is pressed, the semicolon will be removed, showing that there are no spaces after it.

![image](https://user-images.githubusercontent.com/50469309/94610849-84087a80-0266-11eb-89f1-7aaf60f833c9.png)

This issue persists until the file is closed, _then_ VS Code is closed and reopened, and then the file is opened.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (9.05GB free)|
|Process Argv|--crash-reporter-id 4851cb94-5697-449e-8b4f-3b73335f9c87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
rest-client|hum|0.24.2
lorem-whatever|job|1.0.2
vscode-cosmosdb|ms-|0.15.0
azure-account|ms-|0.9.3
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1

</details>

**Comment by alexdima** [comment] 2020-10-01 12:56
@rmgreenstreet What font / settings do you have?

**Comment by sandrosc** [comment] 2020-10-07 09:45
@alexdima I can reproduce this issue with the following settings:
```
  "editor.fontFamily": "'Operator Mono', Consolas, 'Courier New', monospace",
  "editor.fontSize": 18,
```
This is on a mac with an external monitor with the default zoom level. It happened right after I added the font (Operator Mono) and disappeared when I moved the window to another screen.
![image](https://user-images.githubusercontent.com/12650063/95314686-e3cbda80-0891-11eb-8fde-acee971d875d.png)

**Comment by alexdima** [comment] 2020-11-20 15:07
Duplicate of #99313

**Closed by alexdima** 2020-11-20 15:07 UTC
Labels: editor-rendering, needs more info, windows
