### ISSUE TITLE
Sass @at-root (without) error

### ISSUE THREAD

**Issue by zohairmansoor** [microsoft/vscode#158861] opened 2022-08-23 08:42 UTC
@media print{
    .container{
        font-size: 12px;
        color: black;

        @at-root (without: media) {
            font-size: 14px;
             color: gray;
        }
    }
 }

Visual studio Code show me two errors 

1. { expected scss(css-lcurly expected)

2. at-rule or selector expected scss(css-rule or selector expected)

this code is working find no error showing after compile scss

**Comment by aeschli** [comment] 2022-08-26 14:14
duplicate of https://github.com/microsoft/vscode/issues/153202

**Closed by aeschli** 2022-08-26 14:14 UTC
