### ISSUE TITLE
Focus not moved to correct window

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#83697] opened 2019-10-30 22:23 UTC
Issue Type: <b>Bug</b>

- Open two (or more) VS Code windows and have them side by side
- Focus on one of the windows
- Right click on tree view folder in the *other* window and select "add file" (this can also be reproduced with other commands though)
- Start typing the file name
- Observe that you're actually typing in the first editor window, and not the filename as expected, because editor focus didn't shift to the correct window after the right click action.

VS Code version: Code - Insiders 1.40.0-insider (ceeb587991f647659d42a82f87acf3d9778b4d0e, 2019-10-14T10:18:06.503Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
file-icons|fil|1.0.19
gc-excelviewer|Gra|2.1.32
json2csv|kha|0.0.1
l13-diff|L13|0.21.0
git-tree-compare|let|1.7.0
vetur|oct|0.22.6
multi-command|ryu|1.3.0
vscode-fileutils|sle|3.0.0
control-snippets|svi|1.4.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.9.5
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2019-11-12 10:45
Duplicate of context menu does not pass focus to the application.
https://github.com/microsoft/vscode/issues/70966

**Closed** 2019-11-12 10:45 UTC
Labels: *duplicate, file-explorer
