### ISSUE TITLE
problem when i click right-click in my vs code

### ISSUE THREAD

**Issue by Islamzsc** [microsoft/vscode#136446] opened 2021-11-04 15:41 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
I have in my vs code when I click right-click in my mouse it makes left-click by itself and click into anything cut, copy, format, configure or anything it makes me can't work 
 I use ubuntu 21.10 and this problem is just in vs code, not any app else

**Comment by Islamzsc** [comment] 2021-11-04 15:42
please need help in my vs code

**Comment by gjsjohnmurray** [comment] 2021-11-04 16:02
Probably a duplicate of #113175 

Hint for future issue reports - Use the "Report Issue" option on the Help menu. This will fill in your platform and version information automatically.

**Comment by Islamzsc** [comment] 2021-11-04 16:15
Sorry but i don't know how

**Comment by joyceerhl** [comment] 2021-11-05 01:53
Did this start happening after a recent update?

**Comment by Tyriar** [comment] 2021-11-05 13:48
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com).

/label "needs more info" terminal

**Comment by Islamzsc** [comment] 2021-11-05 14:12
Yes

**Comment by Tyriar** [comment] 2021-12-21 18:57
We don't have the info to action this.

**Closed** 2021-12-21 18:57 UTC
Labels: needs more info, terminal
