### ISSUE TITLE
Constant High CPU Usage (clean install no open project/file)

### ISSUE THREAD

**Issue by jlvcm** [Microsoft/vscode#27327] opened 2017-05-26 10:44 UTC
- VSCode Version: <code>Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:11:49.288Z)</code>
- OS Version: <code>Linux x64 4.9.28-1-MANJARO</code>
- CPUs: <code>Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 3299)</code>
- Memory (System): <code>7.76GB (0.17GB free)</code>
- Memory (Process): <code>213.52MB working set (214.75MB peak, 145.11MB private, 68.53MB shared)</code>
- Load (avg): <code>2, 2, 3</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|228|
|main|app.isReady => window.loadUrl()|175|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|529|
|renderer|require(workbench.main.js)|623|
|renderer|create extension host => extensions onReady()|3074|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|1297|
|main + renderer|start => extensions ready|4662|
|main + renderer|start => workbench ready|2857|

---
![spectacle j12464](https://cloud.githubusercontent.com/assets/1488668/26491685/7f2d1696-4208-11e7-93a0-61da97b50dea.png)

-[undefined_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1031554/undefined_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-05-26 17:09
dupe of https://github.com/Microsoft/vscode/issues/24884. Spawning process is very slow in that profile

**Closed by jrieken** 2017-05-26 17:09 UTC
