### ISSUE TITLE
onDebugInitialConfigurations activates very eager.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#39696] opened 2017-12-05 15:05 UTC
Testing #39535

I create an extension that declares a debug type 'foo"
```ts
    console.log('Congratulations, your extension "test-debug-activation" is now active!');
    vscode.debug.registerDebugConfigurationProvider('foo', {
        provideDebugConfigurations: () => {
            console.log('provideDebugConfigurations');
            return [{
                type: 'foo',
                name: 'Foo',
                request: 'launch',
                fooMain: 'foo'
            }];
        }
    });
```
```json
    "activationEvents": [
        "onDebugInitialConfigurations"
    ],
    "contributes": {
        "debuggers": [
            {
                "type": "foo",
                "label": "Foo",
                "enableBreakpointsFor": {
                    "languageIds": [
                        "foo"
                    ]
                },
                "configurationAttributes": {
                    "launch": {
                        "required": [
                            "fooMain"
                        ],
                        "properties": {
                            "fooMain": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        ]
    }
```

- start with an empty workspace, open the debug viewlet, click on the 'Open launch.json' config button
- note that your extension is activated
- a drop down is shows where I can select which type of launch config to create. `Foo` is part of it
- Click on Foo

It would be great if the activation of the extension only happens after the user click on  'Foo'.
Would it make sense to add a 'type' parameter?
'onDebugInitialConfigurations:foo'

**Comment by weinand** [comment] 2017-12-05 15:07
duplicate of #37929

**Closed by weinand** 2017-12-05 15:07 UTC
Labels: debug
