### ISSUE TITLE
Recognize gnome-keyring as OS keyring on Hyprland

### ISSUE THREAD

**Issue by StrangeGirlMurph** [microsoft/vscode#231290] opened 2024-10-14 10:21 UTC
Following the call to create an issue for desktop environments that aren't detected from the docs article [here](https://code.visualstudio.com/docs/editor/settings-sync#_other-linux-desktop-environments)

> [Other Linux desktop environments](https://code.visualstudio.com/docs/editor/settings-sync#_other-linux-desktop-environments)
> 
> First off, if your desktop environment wasn't detected, you can [open an issue on VS Code](https://github.com/microsoft/vscode/issues/new/choose) with the verbose logs from above. This is important for us to support additional desktop configurations.

I am using Hyprland on NixOs. I am not sure if Hyprland falls under what you call desktop environments.
I have set `services.gnome.gnome-keyring.enable = true;` and installed `libsecret` globally.

The verbose log with `code --verbose --vmodule="*/components/os_crypt/*=1"` gives me:
```
[21880:1014/115313.567450:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: (unknown)
```

Which results to the typical keyring error:

![Image](https://github.com/user-attachments/assets/bf742884-473e-4fe0-aa86-b98ea871b497)

I would have hoped that vscode just recognizes that I have the gnome-keyring installed and use it. However adding `"password-store": "gnome-libsecret"` to `.vscode/argv.json` as mentioned [here](https://code.visualstudio.com/docs/editor/settings-sync#_recommended-configure-the-keyring-to-use-with-vs-code) does seem to make everything work.

The full logs:
```
» code --verbose --vmodule="*/components/os_crypt/*=1"

Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
[1014/115313.496596:ERROR:file_io_posix.cc(153)] open /home/murphy/.config/Code/Crashpad/pending/aff2853b-406b-442c-b379-5026bd95ef70.lock: File exists (17)
[21880:1014/115313.506705:WARNING:wayland_object.cc(164)] Binding to wl_seat version 8 but version 9 is available.
[21880:1014/115313.506802:WARNING:wayland_object.cc(164)] Binding to zwp_pointer_gestures_v1 version 1 but version 3 is available.
[21880:1014/115313.506870:WARNING:wayland_object.cc(164)] Binding to zwp_linux_dmabuf_v1 version 3 but version 5 is available.
[21880:1014/115313.567450:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: (unknown)
[21880:1014/115313.595811:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[21924:1014/115313.666886:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2024-10-14T09:53:13.696Z] [File Watcher (node.js)] Request to start watching: /home/murphy/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/murphy/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-10-14T09:53:13.701Z] Sending env to running instance...
[main 2024-10-14T09:53:13.702Z] [File Watcher (node.js)] Started watching: '/home/murphy/.config/Code/User'
[main 2024-10-14T09:53:13.703Z] [File Watcher (node.js)] correcting a path to watch that seems to be a symbolic link or wrong casing (original: /home/murphy/.config/Code/User/settings.json, real: /nix/store/dzfimkbb9m4ghrsq9mqrm8nm3wh785ia-vscode-user-settings)
[main 2024-10-14T09:53:13.703Z] [File Watcher (node.js)] Started watching: '/nix/store/dzfimkbb9m4ghrsq9mqrm8nm3wh785ia-vscode-user-settings'
[main 2024-10-14T09:53:13.709Z] Sent env to running instance. Terminating...
[main 2024-10-14T09:53:13.709Z] Lifecycle#kill()
[main 2024-10-14T09:53:13.709Z] Lifecycle#onWillShutdown.fire()
```

**Comment by TylerLeonhardt** [comment] 2024-10-21 23:15
/duplicate of https://github.com/microsoft/vscode/issues/187338

**Closed** 2024-10-21 23:15 UTC
Labels: *duplicate
