### ISSUE TITLE
Links in internal bash console are not clickable

### ISSUE THREAD

**Issue by tomaszs** [microsoft/vscode#94683] opened 2020-04-08 12:14 UTC
Steps to reproduce:

1. Create Angular project
2. Create a bug in the code
3. Try to click a link in the bash console where npm run start was executed

Expected result:

Clicking a link navigates to the code where the code occurs

Actual results:

Links are not clicable

**Comment by IllusionMH** [comment] 2020-04-08 13:34
/needsMoreInfo

Could you provide more about file structure, opened folder and what path you try to open?

Possible duplicate of #88259 or #22772

**Closed** 2020-04-13 02:54 UTC
Labels: needs more info
