### ISSUE TITLE
Slow intellisense suggestions

### ISSUE THREAD

**Issue by rafkus** [microsoft/vscode#233360] opened 2024-11-07 20:37 UTC
[Trace-20241107T211941.json.zip](https://github.com/user-attachments/files/17669225/Trace-20241107T211941.json.zip)

Type: <b>Performance Issue</b>

It takes +2-3 seconds for suggestions popup to show, really slows down development time. Medium-big project, ~7200 files (ts, tsx), without node_modules of course. Intellisense is immediate until project initialization is finished. No helpful information on the official page how to try to speed up intellisense (how to increase system resources, which settings to toggle)... I wouldn't mind consuming more RAM to make it work faster. Hard to believe my processor is too slow to handle this...

Noticed I have specified tsdk:

```
    "typescript.tsdk": "frontend/node_modules/typescript/lib",  // it is within a project folder
```

It is 5.6.3 version, the same as the version bundled in vscode, but it is much slower when specified 🤔 

Would appreciate any tips/suggestions for further investigation.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.8.0-48-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.26GB (24.54GB free)|
|Process Argv|--crash-reporter-id f71879db-bb6f-4c6f-a9c7-1e5dae6efcd8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   192	158920	code main
    0	    32	158926	   zygote
    1	   224	158964	     gpu-process
    0	     0	159008	       broker
    0	    32	158927	   zygote
    0	     0	158929	     zygote
    5	   352	158983	window [1] (job-bids-page-content.tsx - braintrust - Visual Studio Code)
    0	    32	160790	       utility-process
    0	    64	158968	   utility-network-service
    0	   128	159425	extensionHost [1]
    0	    96	159899	     electron-nodejs (tsserver.js )
    0	   672	159900	     electron-nodejs (tsserver.js )
    0	    64	161496	     /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=159425
    0	    96	159438	shared-process
    0	     0	161559	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	161560	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    96	159440	fileWatcher [1]
    0	    96	159819	ptyHost
    0	     0	159918	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	     0	159922	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (job-bids-page-content.tsx - projectfolder - Visual Studio Code)
|    Folder (projectfolder<!-- Failed to upload "Trace-20241107T211941.json" -->
<!-- Failed to upload "Trace-20241107T211941.json" -->
): more than 20366 files
|      File types: png(3932) py(3889) pyc(2976) tsx(2905) ts(1513) scss(593)
|                  svg(413) txt(287) html(283) sh(51)
|      Conf files: dockerfile(8) jsconfig.json(1) package.json(1)
|                  tsconfig.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by mjbvz** [comment] 2024-11-08 18:29
Does your project also happen to use any typescript plugins? These would be specified in your tsconfig file and would only be loaded if you are using the workspace version of typescript

**Comment by rafkus** [comment] 2024-11-09 10:22
@mjbvz yeah, it seems to 🤔 
```
"plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "classnameTransform": "camelCaseOnly"
        }
      }
    ],
```

Without it speed seems to be similar to the bundled version, thanks 🙏  

Can I do anything to improve the performance with enabled plugin? Can I make vscode more resource-greedy or something? 🤔

**Comment by mjbvz** [comment] 2024-11-11 18:17
Thanks for checking this. Please file an issue against the plugin so  they can take a look and figure out what's causing the slowdown 

Closing this since it sounds like it's caused by that plugin

**Closed by mjbvz** 2024-11-11 18:17 UTC
Labels: info-needed
