### ISSUE TITLE
Variables view list array entries twice

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12989] opened 2016-09-29 10:19 UTC
- VSCode Version: 1.6.0
- OS Version: Windows

![capture](https://cloud.githubusercontent.com/assets/1931590/18950174/f1c96c8a-863e-11e6-9084-a76922dcef23.png)

**Comment by bpasero** [comment] 2016-09-29 10:27
I have seen this too.

**Comment by isidorn** [comment] 2016-09-29 12:02
Dirk's steps:

1. put a breakpoint here https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/documentSymbolProvider.ts#L66
2. attach to extension host, open js file -> cmd + shift + o

**Comment by isidorn** [comment] 2016-09-29 12:24
@weinand @roblourens this is happening because I get indexed properties for an array back both when I ask for 'indexed' and when I ask for 'named' in a [variables request](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L621). Bottom line issue should be somewhere [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L2254) 
Investigating further why this is happening in node debug, as a workaround I can filter for duplicate entries on vscode side.

**Comment by isidorn** [comment] 2016-09-29 13:09
The root cause seems to be in node injection for [getting index / named variables](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/debugInjection.js#L153)
Since I am not very comfortable changing that I have added a distinct filter on the vscode side. We already have one of these filters, just we did not have it for looking at indexed and named variables combined.

**Comment by isidorn** [comment] 2016-09-29 13:11
Closing this as I introduced the workaround. @weinand can investigate the root cause in issue #12554

**Closed by isidorn** 2016-09-29 13:11 UTC
Labels: bug, debug, important

**Comment by roblourens** [comment] 2016-09-29 16:45
Is this when you use a filter for 'indexed', but start and count are undefined? I remember that the filter is ignored in that case, and I think I do the same.

**Comment by isidorn** [comment] 2016-09-30 10:02
No, in this case for 'indexed' we pass the `start` and `count` which are not `undefined`.
For 'named' we pass `undefined` and `undefined` since we do not support paging of 'named' variables. 

And the bottom line issue is that 'indexed' variables get returned as part of the 'named' request. And as mentioned above in that case we pass a proper start and count.

**Comment by weinand** [comment] 2016-10-24 10:05
@isidorn I've fixed #12554. Please remove this workaround.

**Comment by isidorn** [comment] 2016-10-24 12:22
@weinand great, I removed the workaround
