### ISSUE TITLE
Underscores are missing inside the terminal

### ISSUE THREAD

**Issue by reznov11** [Microsoft/vscode#38697] opened 2017-11-18 19:56 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: terminal

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|3.0.0

---

Steps to Reproduce:

1. After i updated the editor to the latest version underscores ( _ ) inside the terminal are missing 

Reproduces without extensions: Yes

**Comment by Jeyanthinath** [comment] 2017-11-18 19:57
I thought I am the one who facing this problem +1 :stuck_out_tongue_closed_eyes: 

os : Linux Ubuntu 16

**Comment by maxibanki** [comment] 2017-11-19 15:37
Duplicate of #35901

Use `"terminal.integrated.fontSize": 13` as a workaround

**Comment by vasergen** [comment] 2017-11-19 18:39
same here, OS: Fedora 25

**Closed** 2017-11-28 18:22 UTC
Labels: *duplicate, integrated-terminal
