### ISSUE TITLE
markdown code-preview does not match text

### ISSUE THREAD

**Issue by pixelmager** [microsoft/vscode#90444] opened 2020-02-11 11:55 UTC
Issue Type: <b>Feature Request</b>

When writing markdown with code sections, the sytax highlighting in the preview does not match the highlighting in the markdown-text. See attached screenshot.

```cpp
float4 PSMain( float4 p : SV_POSITION ) : SV_TARGET
{
    float4 color = CalcColor();
    float rnd = tex.Load(noisetex, p.xy).x; //note: [0;1]
    rnd = remap_pdf_tri( rnd ); //note: [-1;1]
    return color + rnd/255.0; //8bit dithering
}
```

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

**Comment by pixelmager** [comment] 2020-02-11 11:55
![vscode_markdown_code](https://user-images.githubusercontent.com/3230052/74234750-d5f79280-4ccd-11ea-85e5-9e606b6cdff3.PNG)

**Comment by usernamehw** [comment] 2020-02-11 12:14
Possible duplicate of #84572

**Comment by pixelmager** [comment] 2020-02-11 13:31
> Possible duplicate of #84572

That looks likely.

Before closing this with "as designed" and "you can make the preview match vscode", again: If the decision is to use highlight.js for the preview because that is the most accurate in most cases, then the textview should probably use that as well?

**Comment by mjbvz** [comment] 2020-02-11 17:26
Highlight js is lightweight and used by many websites. It would not be appropriate to use in the main editor as it lacks a lot of functionality

**Closed** 2020-02-11 17:25 UTC
