### ISSUE TITLE
show line numbers in REFERENCES: RESULTS

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#105254] opened 2020-08-23 17:08 UTC
Issue Type: <b>Feature Request</b>

I would like an option like search.showLineNumbers but for Find All References.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

**Comment by jrieken** [comment] 2020-10-01 12:28
/duplicate of https://github.com/microsoft/vscode/issues/64521

**Closed** 2020-10-01 12:29 UTC
Labels: *duplicate, feature-request, references-viewlet
