### ISSUE TITLE
Optionally-Enabled Generalized Composable, Tilable Interface

### ISSUE THREAD

**Issue by bradharms** [Microsoft/vscode#66994] opened 2019-01-23 16:11 UTC
References: #11889, #9659, #10546

See the referenced issues above. Rather than implementing any of these, I would like to suggest adding an option (disabled by default) to allow the entire VS Code UI to be customizable in a general way, where all panels can be grouped into tabs, and those tab groups can be moved into geometric groups in the same way code panels currently can. This would include code panels, every tab in the bottom area (problems, output, debug console, terminals, etc.), as well as the different sections of the side bar (which is really just a vertically-arranged tab bar). I feel like recent additions to the UI have already been moving in this direction, subsets of this feature have already been requested (see above), so generalizing everything would be the natural conclusion.

Due to the complexity of this feature we would **disable it by default** to avoid overwhelming new users.

**Comment by sbatten** [comment] 2019-01-23 18:18
Work in this area is on our road map https://github.com/Microsoft/vscode/wiki/Roadmap. While this feedback is not the same as what is listed there, I will resolve this as a duplicate of https://github.com/Microsoft/vscode/issues/10121 to keep it in mind.

**Closed by sbatten** 2019-01-23 18:18 UTC

**Comment by bradharms** [comment] 2019-01-24 15:37
Thanks.
