### ISSUE TITLE
Extension provided keyboard shortcuts show as source "Default"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#41433] opened 2018-01-10 21:46 UTC
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Sublime keymap extension
2. Open Keyboard Shortcuts editor
3. Search for "zen"

Both the VS Code default Toggle Zen Mode (Ctrl+K Z) and Sublime keymap (Shift+F11) are displayed as source "Default".

We should at least let the user know if a keyboard shortcut came from an extension, better yet the specific extension name.

**Comment by usernamehw** [comment] 2018-01-11 00:58
Could be a duplicate of https://github.com/Microsoft/vscode/issues/37034

**Comment by sandy081** [comment] 2018-01-11 08:55
Thanks @usernamehw for mentioning the dup

**Closed** 2018-01-11 08:56 UTC
Labels: *duplicate, extensions
