### ISSUE TITLE
Installing autopep8 extension removes python and pylance extensions.

### ISSUE THREAD

**Issue by yuanyehome** [microsoft/vscode#189837] opened 2023-08-04 06:59 UTC
After I updated my vscode and python extension in my server, the python and pylance extensions can not be found when loading extensions. However, the extensions are truly in the `~/.vscode-server/extensions/extension.json` file and they are really downloaded in the `~/.vscode-server/extensions/` folder.
When I deleted the `.vscode-server` folder and rebuild the whole environment in the remote server, I will never be able to load python extension after I download the `autopep8` extension or `black` extension. Perhaps there are some conflicts between the formatter and the newest python extensions?

**Comment by bpasero** [comment] 2023-08-09 17:49
Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

**Comment by yuanyehome** [comment] 2023-08-09 17:55
> Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

I think I'm using the default profile and didn't change configs about it. I export my profile now, maybe you can check it.
[example.code-profile.txt](https://github.com/microsoft/vscode/files/12305528/example.code-profile.txt)

**Comment by joyceerhl** [comment] 2023-08-10 00:45
This may be a duplicate of https://github.com/microsoft/vscode/issues/189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

**Comment by yuanyehome** [comment] 2023-08-10 03:04
> This may be a duplicate of #189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

Yes, I've tried insider version and this is fixed in the current insider version.

**Comment by yuanyehome** [comment] 2023-08-10 03:17
I have now encountered another problem.
After I updated my `Pylance` extension, both `Pylance` and `Python` extension disappear after realoading.
Is this the same issue with here?

**Comment by joyceerhl** [comment] 2023-08-10 03:54
That may be related. Can you please share the logs from the Window output channel?

**Comment by yuanyehome** [comment] 2023-08-10 04:04
> That may be related. Can you please share the logs from the Window output channel?


https://github.com/microsoft/vscode/assets/36473484/08df54e1-cc52-4ace-93ae-4dfa8fce113e

Sure, here is the video of several logs in the output panel including "Window".

**Comment by joyceerhl** [comment] 2023-08-10 04:50
Thanks, there is still a bug here:
![image](https://github.com/microsoft/vscode/assets/30305945/d8c23c49-bc6b-430b-816c-9e82ae89d6fb)

Is the scenario as follows, or are there more steps?
1. Use Remote SSH
2. Install Python and Pylance on the remote 
3. Update Pylance (I assume this is the extension publishing an update?)
4. Reload window
5. :bug: Python and Pylance are uninstalled on the remote

**Comment by yuanyehome** [comment] 2023-08-10 04:55
Almostly right. I've installed python and pylance in the remote server before and they worked fine yesterday. After the `Pylance` is auto-updated today and I reloaded window, both of them disappeared.

**Comment by joyceerhl** [comment] 2023-08-10 05:03
And this is with the latest VS Code Insiders on commit e529c0a7c946b45ea3e54c7708664d56fc040a69? I tried simulating this by doing the following but was unable to repro:

1. Install Python and Pylance in a GitHub codespace
2. Downgrade Pylance to an earlier version using Install Another Version...
3. Reload
4. Click Update for Pylance
5. Reload
6. Both Pylance and Python are still installed in my GitHub codespace

**Comment by yuanyehome** [comment] 2023-08-10 05:05
> And this is with the latest VS Code Insiders on commit [e529c0a](https://github.com/microsoft/vscode/commit/e529c0a7c946b45ea3e54c7708664d56fc040a69)? I tried simulating this by doing the following but was unable to repro:
> 
> 1. Install Python and Pylance in a GitHub codespace
> 2. Downgrade Pylance to an earlier version using Install Another Version...
> 3. Reload
> 4. Click Update for Pylance
> 5. Reload
> 6. Both Pylance and Python are still installed in my GitHub codespace

Sorry for misleading. This happens in current stable version. The insider version will not have this bug for me now.

**Closed** 2023-08-10 06:19 UTC
Labels: info-needed
