### ISSUE TITLE
${Env.<envvar>} not getting expanded in PowerShell debug configuration

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#20022] opened 2017-02-06 09:16 UTC
_From @rkeithhill on February 6, 2017 5:25_

This [page](http://code.visualstudio.com/docs/editor/debugging) says:

> You can also reference environment variables through ${env.Name} syntax (e.g. ${env.PATH}). Be sure to match the environment variable name's casing, for example ${env.Path} on Windows.

Yet I'm finding with our PowerShell extension, no value gets passed to the PowerShell debugger for the specified environment variable.  Is there something we need to do in the extension e.g. call an env var expansion API to make this work?

_Copied from original issue: Microsoft/vscode-debugadapter-node#99_

**Comment by weinand** [comment] 2017-02-06 09:16
@rkeithhill variable expansion happens on the VS Code side. No debug adapter is involved in this.

**Comment by isidorn** [comment] 2017-02-06 15:17
@rkeithhill works for me. My example: have a launch.json with a "program": "${env.PATH}" - I nicely get the path substituted.
Can you please provide a minimalistic sample for which I can reproduce this issue?

Maybe your issue is that you are using `Env.` instead of `env.`

**Comment by rkeithhill** [comment] 2017-02-06 15:35
You're right.  Didn't realize that case mattered.  Thanks!

**Comment by isidorn** [comment] 2017-02-06 15:47
Closing as designed then.
Not an expert for Windows env variables though :)

**Closed by isidorn** 2017-02-06 15:47 UTC
Labels: debug, needs more info

**Comment by rkeithhill** [comment] 2017-02-06 15:52
Yeah, hard for VSCode to expand an env var that doesn't exist.  :-)
