### ISSUE TITLE
Hanja(=Chinese Character) Input on Korean IME Fails after Update to 1.68.0

### ISSUE THREAD

**Issue by JJKylee** [microsoft/vscode#151669] opened 2022-06-10 01:52 UTC
Issue Type: <b>Bug</b>

Hanja input on Korean IME fails after the most recent update. It worked OK just before the update.

**Expected behavior** (other text editors like EditPlus):
![Hanja input on Korean IME in EditPlus](https://user-images.githubusercontent.com/3157518/172974587-08820a5b-5537-4156-8c7a-d4e02f369a63.gif)

**Actual behavior** in VS Code:
![Hanja input fails on Korean IME in VSCode](https://user-images.githubusercontent.com/3157518/172974628-2f84b465-0fe8-4962-acc3-231a909319d9.gif)

**Steps to Reproduce**:
1. Input _any_ Korean letter on Korean IME.
2. Try change the letter into a Chinese charater (=Hanja) via a shortcut to see it doesn't work.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.60GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 0764103e-5684-4f8e-9571-e57e414c61bd|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by JJKylee** [comment] 2022-06-10 16:40
FYI, after looking into this issue, I've found that this is related to _**Electron/Chromium**_.
An additional switch `--disable-features=TSFImeSupport` solves this issue.

Chrome also suffered from the same issue in its second latest version, 102.0.5005.63, but they applied a quick patch and released an update version 102.0.5005.115 that fixed this issue. I guess VS Code needs to adopt the new Electron engine asap.

Thanks.

**Comment by alexdima** [comment] 2022-06-15 12:31
@deepak Looking at https://chromium.googlesource.com/chromium/src/+log/102.0.5005.61..102.0.5005.115?pretty=fuller&n=10000 , [this commit](https://chromium.googlesource.com/chromium/src/+/8d2b34fdf344d46636a21735fc14bf3e13a35644) fixing [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1329857) stood out. But that bug only mentions Chromium 102 🤷  while on stable we are on Chromium 98.

**Comment by deepak1556** [comment] 2022-06-16 00:52
Thanks for narrowing down the change @alexdima , after a bit of digging through the commit history, here is what happened.

*Timeline*

1) Chromium first landed the offending commit in https://chromium-review.googlesource.com/c/chromium/src/+/3449664 ( 100.0.4891.0)
2) The above change was later reverted in https://chromium-review.googlesource.com/c/chromium/src/+/3573166 (100.0.4896.88)
3) A reland of the above reverted was then performed in https://chromium-review.googlesource.com/c/chromium/src/+/3573299 (102.0.4991.0)
4) This reland then caused the regression mentioned in https://bugs.chromium.org/p/chromium/issues/detail?id=1329857. Please note at this point the issue should only affect Chromium versions >= 102

So why did it regress in VSCode for `1.68` release which is based on Chromium 98, it turns out the change from point 3) above was backported into our internal builds https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/519512

I will get this addressed in our internal builds with the newer fix from 4) for both Electron 17 and Electron 18. @alexdima should this be treated as a candidate issue ?

**Comment by deepak1556** [comment] 2022-06-16 01:41
Fix has been backported https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/543137

**Closed** 2022-06-17 04:35 UTC
Labels: bug, windows, editor-input-IME, confirmed, chromium

**Comment by JJKylee** [comment] 2022-06-30 07:07
Hi.

Thanks a million for the patch. It works OK now.

![Hanja Input VS Code Insiders 20220630](https://user-images.githubusercontent.com/3157518/176614135-53682153-1e5c-4607-bb1b-94e967f78e2e.gif)

/verified
