### ISSUE TITLE
UI element to run NPM scripts

### ISSUE THREAD

**Issue by adampresley** [Microsoft/vscode#49147] opened 2018-05-03 20:44 UTC
I'm really enjoying the latest release 1.23.0, especially the NPM Scripts panel. One little enhancement idea that I feel could improve my workflow would be to add a button next to each task to execute the task. Currently there is a wrench icon next to each task to configure. I'm proposing an additional icon to execute the task. Currently you can right-click and run the task, however adding a button here will reduce the steps down to a single click, making this even more convenient. Thanks for all the hard work!

**Comment by egamma** [comment] 2018-05-07 09:50
Duplicate of #49204 and pls see this https://github.com/Microsoft/vscode/issues/49204#issuecomment-386990673

**Closed by egamma** 2018-05-07 09:50 UTC
Labels: tasks
