### ISSUE TITLE
El host de extensiones finalizó inesperadamente. Recargue la ventana para recuperarlo.

### ISSUE THREAD

**Issue by rvigia** [Microsoft/vscode#11883] opened 2016-09-12 13:34 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:34:58.760Z)
- OS Version: Linux x64 4.1.27-27-default

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment] 2016-09-13 10:38
@rvigia can you share more details in english please?

**Comment by bpasero** [comment] 2016-09-19 04:53
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-09-19 04:53 UTC
Labels: freeze-slow-crash, needs more info

**Comment by iainelder** [comment] 2017-04-06 11:01
@bpasero I just installed Visual Studio Code today and I'm getting the same error regularly. In English it would say something like "The extension host terminated unexpectedly. Reload the window to recover it."

To reproduce it, just open a file and do some editing, reading, idling, whatever. Eventually the message appears at the top of the screen. The editor window is still usable while the message is visible.

* VSCode version: Versión 1.11.0 (1.11.0)
* OS version: macOS Sierra Versión 10.12.3

**Comment by BosioGerman** [comment] 2017-04-06 12:52
Here too

- VSCode version: Version 1.11.0 (1.11.0)
- OS version: macOS Sierra Version 10.12.4

**Comment by bpasero** [comment] 2017-04-06 13:21
@iainelder @BosioGerman 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by iainelder** [comment] 2017-04-07 11:30
I won't be able to check that until 2917-04-17 at the earliest. @BosioGerman , feel free to check it out in the meantime ;-)

**Comment by BosioGerman** [comment] 2017-04-07 12:56
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

Cant reproduce

**code verbose output**

[main 9:24:03] Starting VS Code in verbose mode
[main 9:24:03] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 9:24:03] args: { _: [ '/Users/germanbosio/codigo/master/backupsql-api/tests/client_tasks' ],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 9:24:04] IPC#vscode-machineId
[39475:0407/092405:INFO:CONSOLE(28)] "Conflict detected, command `workbench.action.terminal.clear` cannot be triggered due to html.previewToSide", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[main 9:24:05] IPC#vscode-workbenchLoaded
[39475:0407/092406:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092406:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092407:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/092504:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/092504:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/092531:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/092531:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
2017-04-07 09:30:50.065 Code Helper[39479:2448118] Couldn't set selectedTextBackgroundColor from default ()
[39475:0407/093104:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093104:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093116:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093116:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093152:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093152:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093214:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093214:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093222:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093314:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093314:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/093320:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093320:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093320:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093320:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093320:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093321:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/093321:INFO:CONSOLE(29)] "TextEditor disposed", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/094343:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094343:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094513:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094513:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094652:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094652:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1:
node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2:
node::Environment::exports_string() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::Utils::ApiCheck(bool, char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: 0x345b2a55df2f
[39475:0407/094708:INFO:CONSOLE(5)] "[uncaught exception]: Error: write EPIPE", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[39475:0407/094708:INFO:CONSOLE(5)] "Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[39475:0407/094708:INFO:CONSOLE(160)] "Uncaught Error: write EPIPE", source: events.js (160)
[39475:0407/094708:INFO:CONSOLE(28)] "El host de extensiones finalizó inesperadamente. Recargue la ventana para recuperarlo.", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
<--- Last few GCs --->

 1381093 ms: Mark-sweep 1344.5 (1480.6) -> 1344.5 (1487.6) MB, 489.4 / 0.0 ms [allocation failure] [GC in old space requested].
 1381657 ms: Mark-sweep 1344.5 (1487.6) -> 1344.3 (1495.6) MB, 564.5 / 0.0 ms [allocation failure] [GC in old space requested].
 1382232 ms: Mark-sweep 1344.3 (1495.6) -> 1344.3 (1456.6) MB, 574.6 / 0.0 ms [last resort gc].
 1382794 ms: Mark-sweep 1344.3 (1456.6) -> 1344.3 (1452.6) MB, 561.8 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24cd009cc421 <JS Object>
    1: fromString(aka fromString) [buffer.js:~181] [pc=0x345b2af06867](this=0x24cd00904399 <undefined>,string=0x23ee911f4959 <Very long string[53035928]>,encoding=0x24cd00904399 <undefined>)
    2: t(aka t) [/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:~4] [pc=0x345b2afbe7fa](this=0x24cd00904399 <undefined>)
    3: _tickCallback(aka _...
[39475:0407/094708:INFO:CONSOLE(29)] "Extension host terminated unexpectedly. Code: ", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[39475:0407/094746:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[39475:0407/094746:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)

**Comment by bpasero** [comment] 2017-04-07 13:08
@BosioGerman 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BosioGerman** [comment] 2017-04-07 13:17
Sorry, this is with --disable-extensions

germanbosio@MBP-2  ~/codigo/master/backupsql-api/tests/client_tasks   master  code --verbose --disable-extensions .                                                                                                                                          ([gone]|…)
[main 9:57:03] Starting VS Code in verbose mode
[main 9:57:03] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 9:57:03] args: { _: [ '/Users/germanbosio/codigo/master/backupsql-api/tests/client_tasks' ],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 9:57:05] IPC#vscode-machineId
[main 9:57:06] IPC#vscode-workbenchLoaded
[42003:0407/095716:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[42003:0407/095812:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/095812:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/095946:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/095946:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100008:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100008:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[main 10:00:12] App#activate
[42003:0407/100020:INFO:CONSOLE(29)] "%c[Extension Host]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[42003:0407/100026:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100026:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100028:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100028:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100057:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100057:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100129:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100129:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100159:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100159:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100300:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100300:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100315:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100315:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100459:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100459:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100511:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100511:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100617:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/100617:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1:
node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::Environment::exports_string() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::Utils::ApiCheck(bool, char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x3e2265606147
15: 0x3e22661712be
<--- Last few GCs --->

  913581 ms: Mark-sweep 1334.4 (1427.5) -> 1333.9 (1430.5) MB, 541.7 / 0.0 ms [allocation failure] [GC in old space requested].
  914142 ms: Mark-sweep 1333.9 (1430.5) -> 1333.8 (1392.5) MB, 561.0 / 0.0 ms [last resort gc].
  914694 ms: Mark-sweep 1333.8 (1392.5) -> 1333.8 (1383.5) MB, 552.1 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3675dc7cc421 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x3e22661712be](this=0x3675dc704399 <undefined>,string=0x3665d23c47d9 <Very long string[53036605]>,encoding=0x3675dc7d5ed1 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x3e22661c5c52](this=0x1dc2ebd20711 <JS Function Buffer (SharedFunctionInfo 0x137d3cbf63e9)>,value=0x3665d23c47d9 <Very long string[53036605]>,encodingOrOffset=0x3675dc70...
[42003:0407/101220:INFO:CONSOLE(28)] "El host de extensiones finalizó inesperadamente. Recargue la ventana para recuperarlo.", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/101220:INFO:CONSOLE(29)] "Extension host terminated unexpectedly. Code: ", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[42003:0407/101508:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[42003:0407/101508:INFO:CONSOLE(28)] "%c[IPC Library: Watcher]", source: file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[main 10:15:12] App#activate
[main 10:15:35] Lifecycle#unload() 1
[main 10:15:36] IPC#vscode-machineId
[main 10:15:37] IPC#vscode-workbenchLoaded

**Comment by bpasero** [comment] 2017-04-07 13:39
@BosioGerman can you add your voice to https://github.com/Microsoft/vscode/issues/23960 I think this is where others are also seeing it.

**Comment by 50l3r** [comment] 2017-09-30 22:22
Same problem on 1.16.1
Windows 10 x64

**Comment by Keosuve** [comment] 2017-11-10 16:42
I have the same problem with the new Version 1.18!!! 

![image](https://user-images.githubusercontent.com/13707550/32668451-5e5fdec4-c61c-11e7-975d-2b80fba85bb0.png)

![image](https://user-images.githubusercontent.com/13707550/32668594-c786ab4e-c61c-11e7-99f2-ada94e08c602.png)
