### ISSUE TITLE
Indent guides not rendered on code lens lines

### ISSUE THREAD

**Issue by pdaniel3** [microsoft/vscode#50751] opened 2018-05-29 22:20 UTC
- VSCode Version: 1.23.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/11820265/40688619-fd3cdcb8-635b-11e8-9d0d-304c6cfd1b43.png)

Notice the vertical line breaks on the "_ references" lines

Does this issue occur when all extensions are disabled?: Yes/No
It only happens when the C# extension is enabled

**Comment by rmunn** [comment] 2018-05-30 03:37
The "line matching brackets" in the title is called the "indent guide" or "indentation guide" in VS Code, and the place where the chunks are missing is where a code lens has rendered a line. I'd suggest editing the title of this issue to be something like "Indent guides not rendered on code lens lines" so that it better reflects the cause of the issue, and so that it will be easier for other people to find if they do a GitHub issue search.

**Comment by pdaniel3** [comment] 2018-05-30 19:05
Changed title. As a comment on this post in general, it's worth noting that the visual studio ide does not behave like this. I understand they are different products, but I think the expected behavior of something like this should be that the indent guide should remain solid all the way through

**Comment by alexandrudima** [comment] 2018-05-31 10:06
Currently, the indent guides "don't know" what the vertical space (viewZone) is used for. e.g. diff editors and inline peek editors use the same view zones concept and in those cases indent guides should not be painted in the areas of view zones...

e.g. of cases where view zones should not paint indent guides:

![image](https://user-images.githubusercontent.com/5047891/40776438-03fdb5e8-64cb-11e8-8d16-259a723af2ca.png)

![image](https://user-images.githubusercontent.com/5047891/40776362-d4b2c56c-64ca-11e8-95bc-78f3a2396ed6.png)

![image](https://user-images.githubusercontent.com/5047891/40776392-e76bbc36-64ca-11e8-9579-bf08d06d8db3.png)

![image](https://user-images.githubusercontent.com/5047891/40776408-f2b6b8c0-64ca-11e8-8d39-40fe8b36e54e.png)

**Comment by rmunn** [comment] 2018-06-01 04:00
I wonder if the code lens API needs to acquire a parameter to say what should or shouldn't be painted over the top of the code lens. Not just a boolean that says "paint indent guides", but a more generic API that would allow for future features to be managed as well. E.g., `allowedOverlays = []` if you don't want anything painted over the code lens, or `allowedOverlays = ["indent-guides"]` if indent guides are okay. That way if in the future there's a Foo overlay that doesn't yet exist, code lenses will be able to say "Yes, paint the Foo overlay over me as well" without any API changes needed; just do `allowedOverlays = ["indent-guides", "foo"]`.

**Comment by jrieken** [comment] 2019-05-21 16:27
/duplicate of https://github.com/microsoft/vscode/issues/9604

**Closed** 2019-05-21 16:27 UTC
Labels: *duplicate, editor-code-lens, editor-rendering, feature-request
