### ISSUE TITLE
Changes won't commit

### ISSUE THREAD

**Issue by snl321** [microsoft/vscode#166371] opened 2022-11-15 15:06 UTC
Running into a little trouble committing changes within our Codespace and hoping for help to identify the problem. I took a quick video of where i'm stuck: https://www.loom.com/share/c3ff451d0f734f4fb7b904c775aaebc8

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment] 2022-11-15 17:12
@snl321, thank you very much for the recording and apologies for the caused inconvenience. 

When you commit without specifying a commit message (input field above the "Commit" button), we open a new editor with the COMMIT_EDITMSG file so that you can use the power of the full editor to enter your commit message. Entering a message into the file and closing the editor completes the commit operation. You can find more information about this flow in our release notes - https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor

**Comment by lszomoru** [comment] 2022-12-05 16:21
@snl321, please feel free to reopen this issue in case you still have any questions or concerns. Thanks!

**Closed** 2022-12-05 16:21 UTC
Labels: git, *as-designed
