### ISSUE TITLE
Unexpected output when toggle line comment on TypeScript triple-slash directives

### ISSUE THREAD

**Issue by ntnyq** [microsoft/vscode#179663] opened 2023-04-11 06:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.77.1
- OS Version: Darwin arm64 22.1.0

Steps to Reproduce:

1. Create a `.d.ts` file and paste `/// <reference types="node" />` in it
2. Toggle line comment on the code

## Expected output

```ts
// /// <reference types="node" />
```

## Actual output

```ts
/ <reference types="node" />
```

**Comment by mjbvz** [comment] 2023-04-12 17:58
Duplicate of #64659

Currently not possible until #64659 is addressed

**Closed by mjbvz** 2023-04-12 17:58 UTC
