### ISSUE TITLE
can not format HTML  correctly  when HTML tags have style="....."

### ISSUE THREAD

**Issue by WoShiSunWuKong** [Microsoft/vscode#17504] opened 2016-12-19 02:09 UTC
- VSCode Version: 1.8
- OS Version: win10

Steps to Reproduce:

1. 
with out  **“style="width:30px;height:30px;"”**，the format is right
![image](https://cloud.githubusercontent.com/assets/16789187/21299029/827832de-c5d2-11e6-8285-fb85cf8d1181.png)

2. 
write  **“style="width:30px;height:30px;"”** for  div tag ,then press   Shift+Alt+F，the format is not  right
![image](https://cloud.githubusercontent.com/assets/16789187/21299032/8b3e86f2-c5d2-11e6-8d05-16a630e20bc8.png)

**Comment by ywmail** [comment] 2016-12-22 09:44
any workaround or downgrade to 1.7?

**Comment by aeschli** [comment] 2016-12-29 03:34
duplicate of #17849

**Closed by aeschli** 2016-12-29 03:34 UTC
Labels: html
