### ISSUE TITLE
Test: VS Code Server Work

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#158840] opened 2022-08-23 01:06 UTC
- [x] macOS @isidorn
- [x] linux @karthiknadig
- [ ] windows @DonJayamanne

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158840%0A%0A&assignees=connor4312)

---

This iteration, the `code-server` has moved to use the tunneling service natively, instead of a separate CLI. This impacts how connections are made as well as how reconnections work. We also implemented port forwarding. Please test these things!

1. Install the server using the docs on https://code.visualstudio.com/docs/remote/vscode-server
2. Run `code-server --verbose` and open the vscode.dev link, as usual
3. Forward a port, and verify you can hit it. Remove the port from forwarding.
4. Now, connect to the machine from desktop VS Code ([instructions](https://code.visualstudio.com/docs/remote/vscode-server#_extension-commands)). Verify port forwarding works as well.
5. Try keeping the `code-server --verbose` running for the duration of endgame. Verify occasionally, e.g. once a day, that you're able to connect to it without having to restart the CLI. If you are unable to connect, please message me _without_ restarting the 'broken' CLI!

**Comment by isidorn** [comment] 2022-08-23 13:51
Marking as done since all of the above works as expected. I will keep `code-server --verbose` running. Should I try to connect to it occasionally from the browser, from the desktop app or does not really matter?

**Comment by connor4312** [comment] 2022-08-23 15:35
> Should I try to connect to it occasionally from the browser, from the desktop app or does not really matter?

It doesn't matter 🙂

**Comment by karthiknadig** [comment] 2022-08-23 22:13
This is working well. I will continue testing over this week.

**Comment by DonJayamanne** [comment] 2022-08-23 22:58
Tan into an issue when using port forwarding on the local machine https://github.com/microsoft/vscode/issues/158993

**Comment by DonJayamanne** [comment] 2022-08-23 23:23
Connecting to remote from desktop vscode seems to be flaky, couldn't test port forarding for desktop

@connor4312 Should I leave this issue open, even if its not verified?

**Comment by DonJayamanne** [comment] 2022-08-24 16:40
Closing as a duplicate of https://github.com/microsoft/vscode/issues/158995

**Closed by DonJayamanne** 2022-08-24 16:40 UTC
Labels: verification-found, testplan-item
