### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by NikhilSagar2000** [microsoft/vscode#140396] opened 2022-01-10 09:31 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Proxy.getProgram (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/private/var/folders/yx/tnnnmzdd58g2s91t29s0xcgc0000gn/T/AppTranslocation/B46854FB-7735-4A7A-B346-25FFFEA592BA/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 6|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-color|ans|0.4.5
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.1.0
vscode-styled-components|jpo|0.0.31
debugger-for-chrome|msj|4.13.0
color-highlight|nau|2.5.0
gitblame|wad|8.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617
py55gd98:30419165
vscexrecpromp3c:30407761

```

</details>

**Comment by IllusionMH** [comment] 2022-01-10 09:42
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

**Closed** 2022-01-10 09:43 UTC
Labels: *duplicate
