### ISSUE TITLE
Wrong window fullscreen positioning with "window.titleBarStyle": "custom"

### ISSUE THREAD

**Issue by XandruDavid** [Microsoft/vscode#53589] opened 2018-07-05 12:52 UTC
Issue Type: <b>Bug</b>

When "window.titleBarStyle" is set to "custom" and I activate fullscreen by double-clicking on the top bar, the window is shifted 15px or so down (windows height is correct so 15px are out of view on bottom).
Same issue happens when i move the window from one screen to another while using a dual monitor setup.

VS Code version: Code - Insiders 1.25.0-insider (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-04T14:17:16.571Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.79GB (9.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.22.1
svn-scm|joh|1.29.6

</details>

**Comment by XandruDavid** [comment] 2018-07-05 15:32
It actually happens **once every two** times I maximize the window no matter how (moving from one screen to another / double clicking on bar / clicking the maximize button on bar).

**Comment by V-ed** [comment] 2018-07-05 19:15
This is not a VSCode issue but rather a Windows 10 issue.

The same issue happens to Discord, the newer version of Chrome, Slack I believe (don't quote me on that one), etc.

I'll find a link talking about this exact problem and edit this comment shortly. Probably a screenshot would help too.

**A temporary fix for everyone experiencing this issue** : once you have maximized VSCode and get this issue, drag vscode so it becomes a windowed app and put it back in full screen.
As @XandruDavid already said, it happens once every two times, so you'll have to do this fix again. (I'm explaining it again just to make this temp fix clear, @XandruDavid ;) ).

Hopefully Windows will get this fixed soon, this problem affects me often times too and it's very frustrating!

**Comment by V-ed** [comment] 2018-07-05 19:31
_From a comment on [this reddit thread](https://www.reddit.com/r/Windows10/comments/8h3eqo/windows_1803_white_bar_across_top_of_maximized/) :_

> [...] I fixed the issue for discord by activating the windows 8 compatibility mode

@XandruDavid (and everyone having this issue) : Maybe in the meantime Windows fixes this problem (_view my previous comment if you don't understand why I talk about Discord and Windows_), you could try activating compatibility mode for VSCode. I'm not on my personal computer to try myself unfortunately, will come back here with my personal results once I'll be home.

**Comment by sbatten** [comment] 2018-07-05 20:34
duplicate of #52265

**Closed by sbatten** 2018-07-05 20:34 UTC
Labels: bug, windows, workbench-title
