### ISSUE TITLE
Regular expression search freezes.

### ISSUE THREAD

**Issue by kondo-hokuto** [microsoft/vscode#139189] opened 2021-12-14 06:39 UTC
- VSCode Version: 1.63.0
- OS: Windows10 x64 and Ubuntu20.04 x64

Steps to Reproduce:

1. Open a new editor tab.
2. Enter `123456789012345678901234567890` in the editor.
3. Open the search panel (Ctrl + F).
4. Search for `(.*\n)*a` in a regular expression.
5. Delete the `\n` in the search string.

If the string entered in the editor exceeds about 20 characters, the operation will be slow, and 30 characters will not respond for a long time.
![code_freeze](https://user-images.githubusercontent.com/96103034/145946082-d80f07ef-3896-487c-b751-472fa936ed1d.png)

**Comment by JacksonKearl** [comment] 2021-12-16 00:05
Duplicate of #30874

**Closed by JacksonKearl** 2021-12-16 00:05 UTC
