### ISSUE TITLE
Inspect Protocol - Debug Hover Box don't show up even in the right scope

### ISSUE THREAD

**Issue by Aetherall** [Microsoft/vscode#37838] opened 2017-11-08 18:03 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (15449873f130d7f3e5604a1cac94f32a1f15f604, 2017-11-02T06:22:24.153Z)
- OS Version: Linux x64 4.13.11-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
quokka-vscode|Wal|1.0.76
wallaby-vscode|Wal|1.0.64
html-css-class-completion|Zig|1.13.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|0.24.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
partial-diff|ryu|0.4.1
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Write es6 code in src directory
2. babel src --out-dir dist --watch --source-maps
3. launch debugger

````json
{
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/src/index.js",
      "outFiles": [
        "${workspaceFolder}/dist/**/*"
      ],
      "sourceMaps": true,
      "protocol": "inspector",
      "restart": true,
      "skipFiles": [
        "/home/aetherall/Workspace/Omni/playground/3/node_modules/**/*.js", "// doesn't seems to work BTW",
        "<node_internals>/**/*.js"
    ]
    }

````

**Comment by isidorn** [comment] 2017-11-09 10:02
Forwarindg to @roblourens since 90% the scope information coming from the debug adapter is wrong. Most likely a duplicate of some known issue.

@Aetherall could you share your repository so we try to reproduce this on our end?

**Comment by Aetherall** [comment] 2017-11-09 11:54
https://github.com/Aetherall/vscode-debug-hover-bug/tree/master

**Comment by roblourens** [comment] 2017-11-10 01:02
@isidorn This is just another case where the sourcemappings make no sense, like https://github.com/Microsoft/vscode/issues/35612, and some others.

I don't think this problem will ever go away, because the sourcemaps are broken in a way that is hard to notice if you are just stepping with chrome devtools. They are correct on code lines, but wrong around the ends of functions and function declarations, e.g. scope boundaries, which wouldn't affect stepping. I can file a bug on Babel, but it will either not get fixed or break again, because few users will notice.

The babel config here is very basic, so this is easy to repro. I propose that we show hovers anywhere, not just in the current scope, or make it configurable. _But_, I think the scope locations should still be respected for inline debug values.

**Comment by isidorn** [comment] 2017-11-10 16:55
> I propose that we show hovers anywhere, not just in the current scope, or make it configurable. But, I think the scope locations should still be respected for inline debug values.

Making this configurable sounds very strange, as it is quite technicaly involved. How would a user be supposed to know what to do, or even that such a configuraiton exists.

I am all up for disabling using the scope since it seems to create more harm than good.
Sure, we can use it for inline debug values.

Let me know what you think @roblourens @weinand

**Closed** 2017-11-20 10:29 UTC
Labels: bug, debug, insiders
