### ISSUE TITLE
[sql] Add more keywords to the default highlighter

### ISSUE THREAD

**Issue by SR--** [Microsoft/vscode#22725] opened 2017-03-16 07:07 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. The default SQL highlighter does not see some of the keywords.

![image](https://cloud.githubusercontent.com/assets/1008059/23985464/539c5bb2-0a73-11e7-8817-7da6e8b09731.png)

**Comment by aeschli** [comment] 2017-03-16 10:09
duplicate of https://github.com/textmate/sql.tmbundle/issues/21

**Closed by aeschli** 2017-03-16 10:09 UTC
