### ISSUE TITLE
Terminal not updating view correctly. Backspace not removing all characters on screen

### ISSUE THREAD

**Issue by amorganPD** [Microsoft/vscode#19288] opened 2017-01-24 22:10 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|Arduino|moozzyk|0.0.4|
|cpptools|ms-vscode|0.9.2|
|cmake|twxs|0.0.15|
|cmake-tools|vector-of-bool|0.7.4|

---

User Settings:
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

![image](https://cloud.githubusercontent.com/assets/7513089/22269046/c202371e-e257-11e6-9fa7-a91ce22ff113.png)

I have also seen other instances where other areas of the screen are not updated correctly, for example when using vim. I do not have a screenshot of this, though.

Steps to Reproduce:

1. Open Terminal
2. Type "git status"
3. Press backspace rapidly until line is gone (leaves behind characters)

**Comment by Jule-** [comment] 2017-01-25 14:24
I can confirm that.
It seems it is fixed in the insider preview.

**Comment by mousetraps** [comment] 2017-01-25 19:42
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/7345

@amorganPD: as @Jule- mentioned, it looks like this issue has already been addressed in the [latest insiders builds](https://code.visualstudio.com/insiders). Could you give that a whirl and verify it's working for you?  Thanks!

fyi @Tyriar

**Closed by mousetraps** 2017-01-25 19:42 UTC
Labels: duplicate, integrated-terminal

**Comment by amorganPD** [comment] 2017-01-25 19:52
Just installed the latest insiders build and it appears to be working!

Thank you
