### ISSUE TITLE
Reveal debug configuration when pressing edit

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31544] opened 2017-07-27 09:49 UTC
testing #31396

Unsure if I have filed this already before

* open the vscode workspace which has ~15 launch configs
* select one to launch, notice you want to reconfigure it
* press the gear icon
* you are lost, the file is large, and the part which defines the currently selected configuration isn't revealed (but the last I have edited)

**Comment by jrieken** [comment] 2017-07-27 09:50
An alternative (or addition) would be to have a special outline provider for that file. Today it's not very helpful and I'd prefer seeing the names of the launch configs in there...

<img width="639" alt="screen shot 2017-07-27 at 11 49 55" src="https://user-images.githubusercontent.com/1794099/28664789-d2887026-72c1-11e7-878c-81a11d53a659.png">

**Comment by weinand** [comment] 2017-07-28 13:23
I would love to have this feature (since my launch.jsons have 30++ entries)

**Comment by isidorn** [comment] 2017-07-28 13:26
I think this can be quite useful for large launch.json -> august

**Comment by isidorn** [comment] 2017-08-04 15:26
Now when pressing edit I reveal the select configuration.
I have also added a special outline provider for the launch.json. However I am having issues that my results are being merged in with the default results which make the feature useless.

@jrieken looking at the docs [here](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/vscode.d.ts#L5125) it seems that is expected behavior. Is there some workaround for this to make this feature useful.
You can find my provider [here](https://github.com/Microsoft/vscode/blob/isidorn/next/extensions/configuration-editing/src/extension.ts#L151)

**Closed** 2017-08-05 10:33 UTC
Labels: debug, feature-request

**Comment by sandy081** [comment] 2017-08-30 08:49
@isidorn Since the results are merged, is it possible to show your results on the top?

**Comment by jrieken** [comment] 2017-08-30 08:53
Nah, they are all sorted by range (start_pos) and that's show it currently works... Little we can do
