### ISSUE TITLE
Huge dialog box on multi-monitor setup

### ISSUE THREAD

**Issue by jbx1** [microsoft/vscode#113452] opened 2020-12-26 19:47 UTC
- VSCode Version: 1.52.1  
- Electron: 9.3.5
- OS Version: Windows 10 Pro 20H2 19042.685
- Dell XPS 13 9300 with 3840x2400 display resolution with font scaling set to 250%.
- Secondary monitor: Samsung SyncMaster B2430 with 1920 x 1080 resolution with font scaling set to 100%.

Steps to Reproduce:

1. Start VSCode 
2. If it starts on the higher resolution monitor move it to the lower resolution one. 
3. Choose any of File -> Open File, or File -> Open Folder etc.

The dialog box will be huge (see screenshot)

Does this issue occur when all extensions are disabled? Yes.

These issues were supposedly solved with Electron 6.0.x according to issue 69392, but evidently they are not (or reoccurred).
https://github.com/microsoft/vscode/issues/69392

Full about details:

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

![vscode_large_dialog](https://user-images.githubusercontent.com/6760528/103158238-ea485f00-47bb-11eb-9b00-e4b279d655a6.PNG)

**Comment by pedrolamas** [comment] 2021-02-03 15:54
I've been experiencing this issue for a loooong time now on my machine, using a similar setup (Dell XPS 15" laptop with a 4k screen @200% scale, and a couple of Dell 1080p external monitors @100% scale)

**Comment by pedrolamas** [comment] 2021-02-03 15:57
This issue has been reported over and over, with no solution in sight...

Here are a few examples:

- https://github.com/microsoft/vscode/issues/45424
- https://github.com/microsoft/vscode/issues/69392
- https://github.com/microsoft/vscode/issues/73295

**Comment by kwinz** [comment] 2021-11-27 02:34
This is still not fixed. There are 10 different issues and duplicates that have all been closed by a bot after not being addressed for a few years.

`Open File` dialog is still opened tiny (or huge) if you have a multi monitor setup with different DPI. That's kind of a basic functionality for an editor, and multi monitor setups are prevalent for programmers. I am not sure why you are not pouring resources into this?

**Comment by kwinz** [comment] 2021-11-27 02:40
Possible duplicate of #85898

**Comment by deepak1556** [comment] 2021-11-29 04:57
Merging to https://github.com/microsoft/vscode/issues/85898

**Closed by deepak1556** 2021-11-29 04:57 UTC
Labels: bug, electron
