### ISSUE TITLE
Wrong tag closing highlighted inside React component

### ISSUE THREAD

**Issue by yakirsobelman** [Microsoft/vscode#34279] opened 2017-09-13 09:04 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-file-templates|bam|1.1.0
npm-intellisense|chr|1.3.0
vscode-javascript-snippets|cod|1.0.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
RelativePath|jak|1.0.0
vs-color-picker|lih|0.6.0
Runner|mat|0.1.14
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
vscode-icons|rob|7.12.0
git-merger|sha|0.3.6
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0
local-history|xyz|1.4.0

---

Steps to Reproduce:

1. Create a self closing React Component.
2. Inside one of properties write an arrow function.
3. Move cursor to the component's opening tag
4. the arrow is highlighted as closing tag instead of the real closing tag.

![image](https://user-images.githubusercontent.com/8408452/30368999-a61d44c8-987b-11e7-8a4e-070f6e48aae3.png)

**Comment by mjbvz** [comment] 2017-09-13 18:10
Duplicate of #30097

**Closed by mjbvz** 2017-09-13 18:10 UTC
Labels: duplicate, javascript
