### ISSUE TITLE
Textmate scope broken for `support.variable.object.node`

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#105267] opened 2020-08-24 04:47 UTC
Issue Type: <b>Bug</b>

The Textmate scope for `support.variable.object.node` has been broken in the latest stable version.
This now simply turns into `variable.other`:

![image](https://user-images.githubusercontent.com/490562/91004883-7fc6bd00-e629-11ea-9fa9-81c6a2c69b7e.png)

Expected for `console` to be flagged as `support.variable.object.node`.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 5, 3|
|Memory (System)|24.00GB (2.38GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by mjbvz** [comment] 2020-08-24 15:16
Duplicate of #104616

**Closed by mjbvz** 2020-08-24 15:16 UTC
