### ISSUE TITLE
Add border options to `selectionBackground`

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/vscode#30793] opened 2017-07-16 07:17 UTC
- VSCode Version: 1.14.1: 
- OS Version: Windows 10 build 15063

Add border options to `selectionBackground` and `findMatchBackground`. They would be called like `selectionBorder` and `findMatchBorder`. You cannot find them on:

1. https://code.visualstudio.com/docs/getstarted/theme-color-reference

Currently the selection has no border:

![image](https://user-images.githubusercontent.com/5332158/28245458-8281e9aa-69dd-11e7-8952-ad69839e7cd4.png)

Would be awesome if it has borders like Sublime Text selections:

![image](https://user-images.githubusercontent.com/5332158/28245453-66aa5410-69dd-11e7-912b-868638cb7ffa.png)

Reproduces without extensions: Yes

___ 

Related issues:

1. https://github.com/Microsoft/vscode/issues/8050 additional options for `editor.selectionHighlight`

**Comment by ro31337** [comment] 2017-07-31 18:46
+1

**Comment by johnpapa** [comment] 2017-11-29 15:58
Moving here as per @aeschli and @chrisdias 

This looks awesome! :)

## Selection Highlight and Find Match

Expose border, and background for `selectionHighlight` and `findMatch`

![image](https://user-images.githubusercontent.com/1202528/33155041-f72b7de6-cfba-11e7-830f-61a5c38c8534.png)

```css
/*
  This puts a thin yellow border around the found items like Sublime did it
*/
.monaco-editor .findMatch,
.monaco-editor .selectionHighlight {
  border-top: 0.1px solid #f7ecb5;
  border-bottom: 0.1px solid #f7ecb5;
  background: transparent;
}
```

**Comment by aeschli** [comment] 2018-02-16 11:12
I added border options for most of the text decorations (findMatch, wordHighlight...). Not for selection as this needs more work to look good.

**Comment by Enteleform** [comment] 2018-06-29 14:03
# +1
This makes it much easier to create a high-visibility style for the active selection.

![comparison](https://user-images.githubusercontent.com/10906415/42095798-a6ecc330-7b81-11e8-92ea-a8e6fc72a0f7.png)

On a related note, the lack of `selectionForeground` for non-high-contrast themes is definitely a detriment to achieving the same effect.

Also, I just noticed that the `selection` & `selectionHighlight` properties have kind of an odd behavior in relation to `addSelectionToNextFindMatch`.

![selection](https://user-images.githubusercontent.com/10906415/42096310-f5e7b6ba-7b82-11e8-9798-0b54f2a26c4c.gif)

When using `addSelectionToNextFindMatch`, the `selection` & `selectionHighlight` properties are both applied to each additionally selected match. I would expect `selection` properties to activate, and `selectionHighlight` properties to deactivate, in this case. The expected behavior is exhibited in the second half of the GIF, when multiple selections are made simultaneously.

**Comment by blacktop** [comment] 2019-02-02 18:15
+1 please!

**Comment by kanlukasz** [comment] 2019-03-14 17:55
I miss this too much

**Comment by FrancisVila** [comment] 2020-02-18 10:55
Here"s an extra take on this old issue:
The following image illustrates the problem. Here editor.selectionhighlightborder works, but not editor.selectionBorder.

![image](https://user-images.githubusercontent.com/23334974/74729719-32fec580-5245-11ea-902c-d3def1414e76.png)

    The currently seleted item is the AAFFAA of editor.selectionBorder. It is **_not bordered_**, when this is where you want to point out the current selection, which is **the most important item** in the whole editor: where things will happen if you hit keys on the keyboard.
    The AAFFAA of editor.selectionHighlightBorder is bordered. This _is_ important, but _much less_ than editor.selectionborder. It's there to say "hey, the one you've got selected isn't the only one, if you're thinking of editing this one, don't forget all the rest".

**Comment by blacktop** [comment] 2020-03-13 17:54
This would make some themes MUCH more readable.

**Comment by haakonstorm** [comment] 2020-05-10 11:45
Bump

**Comment by rebornix** [comment] 2020-11-04 23:06
/duplicate of https://github.com/microsoft/vscode/issues/21898 , let's track it there.

**Closed** 2020-11-04 23:06 UTC
Labels: editor-highlight, editor-theming, feature-request, ux
