### ISSUE TITLE
EACCESS error when running extension tests on Travis

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#45173] opened 2018-03-07 04:56 UTC
- VSCode Version: 1.21.0-insider
- OS Version: Ubuntu 14.04 (Travis)

Steps to Reproduce:

1. call `vscode.workspace.findFiles` in test
2. run test on Travis

Does this issue occur when all extensions are disabled?: Yes

---

Related issues: #38406, https://github.com/Microsoft/vscode-extension-vscode/issues/88

I followed the suggestion in #38406, run insider version as a workaround, however, it seems not work for me.

```
[04:40:27] Downloading VS Code into "/home/travis/build/Sneezry/vscode-arduino/.vscode-test" from: https://vscode-update.azurewebsites.net/1.21.0-insider/linux-x64/insider
...
[04:40:54] vscode.workspace.findFiles
[04:40:54] .vscode/arduino.json
[04:40:54] [ 'Error: spawn EACCES',
  '    at exports._errnoException (util.js:1050:11)',
  '    at ChildProcess.spawn (internal/child_process.js:319:11)',
  '    at Object.exports.spawn (child_process.js:390:9)',
  '    at Object.a [as spawnRipgrepCmd] (/home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:143:122)',
  '    at e.cmdTraversal (/home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:146:96)',
  '    at e.call (/home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:145:810)',
  '    at v.parallel.n (/home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:145:497)',
  '    at /home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:98:442',
  '    at Array.forEach (native)',
  '    at Object.t.parallel (/home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:98:420)' ]
...
```

---

### Test file

https://github.com/Microsoft/vscode-arduino/blob/dc4f3d707043d33a15cbc95de1cf16703c1ecc74/test/devicecontext.test.ts#L13

### `vscode.workspace.findFiles` called from

https://github.com/Microsoft/vscode-arduino/blob/dc4f3d707043d33a15cbc95de1cf16703c1ecc74/src/deviceContext.ts#L124

**Comment by roblourens** [comment] 2018-03-07 07:28
Can you check the permissions of the downloaded `rg`? `ls -l /home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/node_modules/vscode-ripgrep/bin/rg`

**Comment by Sneezry** [comment] 2018-03-07 07:45
I got such error:

```
Error: Command failed: ls -l /home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/node_modules/vscode-ripgrep/bin/rg
ls: cannot access /home/travis/build/Sneezry/vscode-arduino/.vscode-test/VSCode-linux-x64/resources/app/node_modules/vscode-ripgrep/bin/rg: No such file or directory
```

You can find the full log if you need:

https://travis-ci.org/Sneezry/vscode-arduino/jobs/350193074

**Comment by roblourens** [comment] 2018-03-07 17:32
Does it work when you run the tests locally?

**Comment by Sneezry** [comment] 2018-03-08 05:50
I do not have Ubuntu machine now, but I will try it tomorrow.

I found the test can **pass** yesterday with VSCode 1.20.1, however, it **fails** today with the same code, and I find VSCode has upgraded to 1.21.1.

**Comment by roblourens** [comment] 2018-03-09 17:52
/duplicate of #45287, fix on the way

**Closed** 2018-03-09 17:52 UTC
Labels: *duplicate, needs more info
