### ISSUE TITLE
Node JS debugging is inconsistent

### ISSUE THREAD

**Issue by joelwatson** [Microsoft/vscode#54184] opened 2018-07-12 15:09 UTC
Issue Type: <b>Bug</b>

When using the built-in debugger for Node JS scripts, I've noticed that the accuracy of the debugger in terms of line placement and breakpoints is extremely hit or miss in 1.2.5.0 (worked perfectly in 1.2.4). A few issues I've run into:

* With source maps enabled, the actual file opened in debugging will sometimes be wrong (if there are files in different directories with the same name, e.g., `utils.js`).

* Breakpoints will not respect the original line they were placed at, and will instead be indicated at a completely different location (even though the variables context is technically correct)

* Debugger statements will halt execution in the correct location, but the debugger itself will choose a random location in the file (or possibly a different file...see above). 

Unfortunately, this isn't 100% consistent; some files work as expected, others fail in one or two areas of the issues above, others are completely messed up. I'm not sure of the difference in the files, other than possibly collisions in files with the same name under different directories.

Here is the script I use to start my node script:
`"./node_modules/.bin/nodemon app/server.js --inspect --exec ./node_modules/.bin/babel-node"`

And here is the `launch` config:

```
{
    "type": "node",
    "request": "attach",
    "name": "Debug",
    "processId": "${command:PickProcess}",
    "restart": true,
    "protocol": "inspector",
    "sourceMaps": false // tried both true and false
}
```

As I mentioned above, this configuration worked in 1.24, and the debuggin experience was superb. In 1.25.0, the debugging experience has significantly degraded, making it nearly unusable. 

Please let me know if there is any other information I can provide to help facilitate a speedy fix for this. Thanks for this awesome product; hoping the debugging gets back up to snuff soon!

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_2495073|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nsp|ada|1.0.1
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
vscode-great-icons|emm|2.1.36
auto-rename-tag|for|0.0.15
icon-fonts|idl|2.1.0
debugger-for-chrome|msj|4.7.0
indent-rainbow|ode|7.2.2
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.5.1

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2018-07-12 16:39
Can you share the project at all?

Or can you set `"trace": true`, repro one of these issues, and upload the log here?

**Comment by roblourens** [comment] 2018-07-12 16:39
Can you share the project at all?

Or can you set `"trace": true`, repro one of these issues, and upload the log here?

**Comment by joelwatson** [comment] 2018-07-12 16:47
@roblourens Unfortunately, I can't share the project, but I can definitely set the flag (and have done so). Where is the log written?

**Comment by roblourens** [comment] 2018-07-12 17:00
The log file path is written to the top of debug console

**Comment by joelwatson** [comment] 2018-07-12 17:32
@roblourens I don't really want to share the full file here, since scrubbing it will be quite onerous. However, a few things I noticed relating specifically to file I'm having issues with:

First:

```
From target: 
{  
   "method":"Debugger.scriptParsed",
   "params":{  
      "scriptId":"3419",
      "url":"/path/to/my/utils.js",
      "startLine":0,
      "startColumn":0,
      "endLine":236,
      "endColumn":3,
      "executionContextId":1,
      "hash":"71A41363304CEC779488B7B70520B7A9A482A9D0",
      "isLiveEdit":false,
      "sourceMapURL":"data:application/json;charset=utf-8;base64,eyJ2ZXJZ {...}"
   }
}
```

Next:

```
Paths.scriptParsed: could not resolve /path/to/my/utils.js to a file with pathMapping/webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
```
Next:

```
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /path/to/my/utils.js by URI: data:application/json;charset=utf-8;base64,eyJ2ZXJ {...}
```

Next:

```
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in /path/to/my/utils.js
```

Next:
```
SourceMap: creating for /path/to/my/utils.js
SourceMap: sourceRoot: /path/to/my
SourceMap: sources: ["utils.js"]
```

Next:
```
SourceMap: resolved sourceRoot /path/to/my -> 
SourceMaps.scriptParsed: /path/to/my/index.js was just loaded and has mapped sources: ["/index.js"]
SourceMaps.scriptParsed: /path/to/my/utils.js was just loaded and has mapped sources: ["/utils.js"]
```

Next: 

```
To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"utils.js","path":"/path/to/my/utils.js","origin":"read-only content from Node.js"}}}
```

Next:

```
To client:
{  
   "seq":0,
   "type":"response",
   "request_seq":11,
   "command":"stackTrace",
   "success":true,
   "body":{  
      "stackFrames":[  
         {  
            "id":1070,
            "name":"tryCatch",
            "source":{  
               "name":"runtime.js",
               "path":"/path/to/node_modules/regenerator-runtime/runtime.js"
            },
            "line":65,
            "column":40
         },
         {  
            "id":1071,
            "name":"invoke",
            "source":{  
               "name":"runtime.js",
               "path":"/path/to/node_modules/regenerator-runtime/runtime.js"
            },
            "line":303,
            "column":22
         },
         {  
            "id":1072,
            "name":"prototype.(anonymous function)",
            "source":{  
               "name":"runtime.js",
               "path":"/path/to/node_modules/regenerator-runtime/runtime.js"
            },
            "line":117,
            "column":21
         },
         {  
            "id":1073,
            "name":"step",
            "source":{  
               "name":"utils.js",
               "path":"/path/to/my/utils.js"
            },
            "line":31,
            "column":191
         },
         {  
            "id":1074,
            "name":"(anonymous function)",
            "source":{  
               "name":"utils.js",
               "path":"/path/to/my/utils.js"
            },
            "line":31,
            "column":437
         },
         {  
            "id":1075,
            "name":"(anonymous function)",
            "source":{  
               "name":"utils.js",
               "path":"/path/to/my/utils.js"
            },
            "line":31,
            "column":99
         },
         {  
            "id":1076,
            // THIS IS THE METHOD WHERE I'VE PLACED THE DEBUGGER STATEMENT
            "name":"someMethodToDebug",
            "source":{  
               "name":"utils.js",
               "path":"/utils.js", //THIS IS WHAT IS IN THE LOG, BUT PATH IS NOT RIGHT!!!!
               "sourceReference":4874,
               "origin":"read-only inlined content from source map"
            },
            "line":38,
            "column":7
         },
         .........
      ],
      "totalFrames":69
   }
}
```

So the actual file that is displayed in the "read-only inlined content from source map" tab is another file named `utils.js`, but which lives in an entirely different folder:

```
SourceMap: resolved sourceRoot /path/to/elsewhere -> 
SourceMap: creating for /path/to/elsewhere/utils.js
SourceMap: sourceRoot: /path/to/elsewhere
SourceMap: sources: ["utils.js"]
```

**Comment by roblourens** [comment] 2018-07-12 18:06
Thanks for these details. Given `SourceMap: sourceRoot: /path/to/elsewhere`, this sounds like the same as https://github.com/Microsoft/vscode/issues/54026.

I'm working on a fix that will end up in insiders. You may also be able to work around it on your end by finding a ts configuration that doesn't write sourceRoot as an absolute path.

**Comment by joelwatson** [comment] 2018-07-12 18:21
@roblourens Thanks, although I'm not currently using TypeScript...would this be caused by something else?

I've tried creating a simple project to demonstrate the issue, but haven't had an luck. However, in trying to reproduce in a small scenario, I did notice that the breakpoints don't seem to work unless a `debugger` statement has been executed and the script execution is halted. I swear I remember being able to simply start the debugger, set a breakpoint somewhere in code, and it would break as expected without the need for a prior `debugger` statement in code. Has something in relation to this changed? Should I be able to do what I'm remembering? Or am I misremembering?

**Comment by joelwatson** [comment] 2018-07-12 18:36
@roblourens I just reverted to 1.24 and tried out the breakpoint test I mentioned above; it works exactly as expected in 1.24 (halts execution with no need for a `debugger` statement), but in 1.25, the breakpoint will only work if I've first stopped execution with a `debugger` statement. 

Do you think these are related, or should I create a new ticket?

**Comment by joelwatson** [comment] 2018-07-12 19:09
Ok, one final note on this. I installed 1.24 again, and tried out my original test. I'll put the side-by-side comparison below:

### Adding Breakpoint to Method
In my file (/path/to/my/utils.js), I place a breakpoint within the method.
**1.24.1** Debugger stops execution at the breakpoint in the desired location, in the correct file
**1.25.0** Debugger does not stop execution whatseover

### Adding `debugger` to Method
In my file (/path/to/my/utils.js), I insert a `debugger` statement within my method, and save. When code runs:
**1.24.1** Debugger stops execution precisely at the line where the `debugger` is located. Original source file is focused, and the correct line is highlighted.
**1.25.0** Debugger stops execution. However, I have another file named `utils.js` elsewhere in the project, so this file is opened and focused; since it's the wrong file, the wrong line is highlighted. Furthermore, a new tab is opened to display the "read-only inlined content from source map". This never occurred before in 1.24.1...

Finally, in comparing the `trace` logs, I noticed a pretty telling difference between the two results:

**1.24.1**
```
SourceMaps.scriptParsed: /path/to/my/utils.js was just loaded and has mapped sources: ["/path/to/my/utils.js"] (CORRECT)
```
**1.25.1**
```
SourceMaps.scriptParsed: /path/to/my/utils.js was just loaded and has mapped sources: ["/utils.js"] (INCORRECT)
```

AND

**1.24.1**
```
{
    "id":1076,
    "name":"someMethodToDebug",
    "source":{
        "name":"utils.js",
        "path":"/path/to/my/utils.js" // CORRECT!~
    },
    "line":38,
    "column":7
}
```
**1.25.0**
```
{  
    "id":1076,
    "name":"someMethodToDebug",
    "source":{  
        "name":"utils.js",
        "path":"/utils.js", // INCORRECT!~
        "sourceReference":4874,
        "origin":"read-only inlined content from source map"
    },
    "line":38,
    "column":7
}
```

**Comment by rynmng** [comment] 2018-07-13 16:21
Just wanted to chime in and note I'm seeing similar issues (also using `babel-node`) recently. Thanks for the thorough investigation and upcoming workaround!

**Comment by roblourens** [comment] 2018-07-13 16:33
I'd be interested to see the babel-node config that causes this. I may have to file an issue on them too.

**Comment by joelwatson** [comment] 2018-07-13 17:06
@roblourens I don't have anything terribly interesting in regard to configuration.

Here's my .babelrc:

```
{
    "presets": [
        "es2015",
        "stage-3",
        "react"
    ],
    "plugins": [
        [
            "react-require",
            "transform-runtime",
            {
                "polyfill": false,
                "regenerator": true
            }
        ],
        ["module-alias", [{
            "src": "./app",
            "expose": "-"
        }]]
    ]
}
```

And I launch my debug mode like so:

```
./node_modules/.bin/nodemon app/server.js --inspect --exec ./node_modules/.bin/babel-node
```

**Comment by danielvy** [comment] 2018-07-16 13:08
> I just reverted to 1.24 and tried out the breakpoint test I mentioned above; it works exactly as expected in 1.24 (halts execution with no need for a debugger statement), but in 1.25, the breakpoint will only work if I've first stopped execution with a debugger statement.

Was about to open a new issue when I found this one, so just adding my 2¢

Setting breakpoints directly inside javascript source hasn't worked for me in a while if the code is transpiled with babel.

With **1.24**, I was able to put a `debugger` statement in my source, the debugger would stop and then I was able to set additional breakpoints anywhere and it worked as expected.

Since **1.25**, this is not longer the case - I'm able to break on a `debugger` statement but breakpoints no longer work consistently. Also, Just stepping over/into the code is not working consistently either, it often fails to step over/into that code and just jumps sporadically to unrelated source lines.

My babel config is simple:
```
"presets": [
  [
    "env",
     {
       "targets": {
	  "node": "current"
       }
     }
  ]
],
"sourceMaps": "inline",
"retainLines": false

```

I verified that the source maps are generated correctly (loading them in external tool). Both inline and external source maps. Tried many settings combinations, I'm unable to make debugging with breakpoints work no matter what I try.

I'll wait and see if the mentioned fixes will resolve the issue in the next build and will try to create a bare bones repo that demonstrates the issue if not.

**Comment by roblourens** [comment] 2018-07-17 16:15
The fix will be in tomorrow's Insiders, if that doesn't fix it @danielvy please open a new issue.

Closing this as a dupe of https://github.com/Microsoft/vscode/issues/54026 unless we find otherwise.

**Closed** 2018-07-17 16:15 UTC
Labels: *duplicate, debug

**Comment by joelwatson** [comment] 2018-07-17 21:03
@danielvy @rynmng On #54026, I noticed a [comment](https://github.com/Microsoft/vscode/issues/54026#issuecomment-405262480) about a possible workaround:

```
// add to launch.json
"pathMapping": {
    "/": "/"
}
```

I tried it in 1.25.1, and debugging seems to be working again for me as expected. You might try it out if you need a quick fix!

**Comment by joelwatson** [comment] 2018-07-18 15:47
Just tried this out in the latest `Insiders` version; seems to work as expected now! Thanks for the quick fix :)

**Comment by roblourens** [comment] 2018-07-18 16:01
Awesome thanks for trying it!
