### ISSUE TITLE
source control tab not showing merge conflict files

### ISSUE THREAD

**Issue by aleksandarbos** [microsoft/vscode#115237] opened 2021-01-27 16:27 UTC
- VSCode Version: 1.52.1 (user setup)
- OS Version: OS: Windows_NT x64 10.0.18363

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. initialize merging with some branch that has some conflicting docx files:
`added by them:   print/templates/supplement.docx`
2. expected: VS code should be showing all conflicting and modified files within the source control tab like:
4. actual: 
![image](https://user-images.githubusercontent.com/15141614/106020803-6b00c080-60c4-11eb-95c5-f5681221e737.png)

there's workaround, if the `print/templates/supplement.docx` file gets staged by:
`git add print/templates/supplement.docx` then files are properly displayed within source control tab. 

what might be also interesting is that there were no issues when other binary files like `png` were modified. not quite sure what might go wrong :/

Does this issue occur when all extensions are disabled?: Yes

**Comment by FeldmannJR** [comment] 2021-01-27 16:49
This just occurred to me as well, in my case i don't have any .docx in the repository, just javascript source files.

![image](https://user-images.githubusercontent.com/19637003/106024295-66c5aa80-60a6-11eb-8244-80370ecd71de.png)

**Comment by aleksandarbos** [comment] 2021-01-27 17:05
> This just occurred to me as well, in my case i don't have any .docx in the repository, just javascript source files.
> 
> ![image](https://user-images.githubusercontent.com/19637003/106024295-66c5aa80-60a6-11eb-8244-80370ecd71de.png)

@FeldmannJR have you tried to reproduce the bug by having all extensions disabled? 
![image](https://user-images.githubusercontent.com/15141614/106026513-309a2200-60ca-11eb-9e51-924a2ce86eb1.png)

**Comment by FeldmannJR** [comment] 2021-01-27 17:11
Yes, 
Just enabled WSL support.
![image](https://user-images.githubusercontent.com/19637003/106027311-8a3e2480-60a9-11eb-9875-ee2cbb3f7e0e.png)

**Comment by eamodio** [comment] 2021-01-27 18:12
Duplicate of https://github.com/microsoft/vscode/issues/112537

**Closed by eamodio** 2021-01-27 18:12 UTC
