### ISSUE TITLE
VS Code is unable to activate a debugger extension because of path casing discrepancies

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode#118562] opened 2021-03-09 16:59 UTC
- VS Code Version: 1.54.1
- OS Version: Windows 10 19041

More information here: https://github.com/microsoft/vscode-cpptools/issues/7114

I want to highlight this from the customer's logs.  They are trying to load the `ms-vscode.cpptools` extension, but the reasoning in the log does not make sense because `ms-vscode.cpptools` registers the `'cppvsdbg'` debugger type).  Downgrading VS Code to 1.53.2 fixes the issue for the customer.  We're not sure what would cause this.

```
[2021-03-05 16:49:27.882] [exthost] [error] Activating extension ms-vscode.cpptools failed due to an error:
[2021-03-05 16:49:27.886] [exthost] [error] Error: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'cppvsdbg' debugger.
	at m.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:25505)
	at Object.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:37807)
	at Object.initialize (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:18300:35)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26903:27
	at Generator.next (<anonymous>)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26841:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26837:12)
	at activate (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26870:12)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14037)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:13714)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11746
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Does this issue occur when all extensions are disabled?: No

**Comment by michalfita** [comment] 2021-03-09 17:08
I'm affected.

**Comment by fabioz** [comment] 2021-03-10 15:30
As a note, downgrading VSCode to 1.53.2 also works for me (so, it seems like a regression in the latest release).

**Comment by weinand** [comment] 2021-03-11 21:36
@isidorn here is my analysis of the issue:

The error occurs because a check in the extension API fails that verifies that a "debug adapter factory" can only be registered in the extension that defines the corresponding "debugger".

The error occurs here:

https://github.com/microsoft/vscode/blob/d574f8e9163f08213376560e5ab321fd02e48332/src/vs/workbench/api/common/extHostDebugService.ts#L328-L330

Here is the code of the "check":

https://github.com/microsoft/vscode/blob/d574f8e9163f08213376560e5ab321fd02e48332/src/vs/workbench/api/common/extHostDebugService.ts#L745-L760

An example context where this check fails can be seen above in this https://github.com/microsoft/vscode/issues/118562#issuecomment-795500260:
A debugger with type "robotframework-lsp" is defined in the package.json and in the extension's activation code a debug adapter factory is registered for the same type "robotframework-lsp" with the call `debug.registerDebugAdapterDescriptorFactory('robotframework-lsp', <factory>)`.

The check fails which means that the `IExtensionDescription` does not seem to contain the correct data.

This check exists for a long time and never failed for any other reason than the one it was introduced for.

I'm not aware of any changes in debug land that could cause this (there were no changes in that area).

Until now, this issue was only reported for Windows.

@alexdima @sandy081 @bpasero @isidorn  are you aware of anything related to this?

**Comment by alexdima** [comment] 2021-03-11 22:17
Thank you @weinand , that helped to point in the right direction. Looking again at the full logs contained [in the original issue](https://github.com/microsoft/vscode-cpptools/issues/7114#issue-823270676), the problem is that the `require('vscode')` call is not identified as coming from the C++ extension:

@jrieken It looks like an uppercase/lowercase problem (`sesa404214` vs `SESA404214`):

#### Relevant lines:
```
Could not identify extension for 'vscode' require call from 
c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js
c:\Users\SESA404214\.vscode\extensions\ms-vscode.cpptools-1.2.2 -> ms-vscode.cpptools
```

#### Full relevant logs:
```
[2021-03-05 16:49:27.182] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main
[2021-03-05 16:49:27.321] [exthost] [warning] Could not identify extension for 'vscode' require call from c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js. These are the extension path mappings: 
	c:\Program Files\Microsoft VS Code\resources\app\extensions\configuration-editing -> vscode.configuration-editing
	c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features -> vscode.css-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-auto-launch -> vscode.debug-auto-launch
	c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-server-ready -> vscode.debug-server-ready
	c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet -> vscode.emmet
	c:\Program Files\Microsoft VS Code\resources\app\extensions\extension-editing -> vscode.extension-editing
	c:\Program Files\Microsoft VS Code\resources\app\extensions\git -> vscode.git
	c:\Program Files\Microsoft VS Code\resources\app\extensions\git-ui -> vscode.git-ui
	c:\Program Files\Microsoft VS Code\resources\app\extensions\github -> vscode.github
	c:\Program Files\Microsoft VS Code\resources\app\extensions\github-authentication -> vscode.github-authentication
	c:\Program Files\Microsoft VS Code\resources\app\extensions\grunt -> vscode.grunt
	c:\Program Files\Microsoft VS Code\resources\app\extensions\gulp -> vscode.gulp
	c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features -> vscode.html-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\image-preview -> vscode.image-preview
	c:\Program Files\Microsoft VS Code\resources\app\extensions\jake -> vscode.jake
	c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features -> vscode.json-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features -> vscode.markdown-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict -> vscode.merge-conflict
	c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication -> vscode.microsoft-authentication
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender -> ms-vscode-remote.remote-wsl-recommender
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug -> ms-vscode.js-debug
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug-companion -> ms-vscode.js-debug-companion
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug -> ms-vscode.node-debug
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2 -> ms-vscode.node-debug2
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.references-view -> ms-vscode.references-view
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.vscode-js-profile-table -> ms-vscode.vscode-js-profile-table
	c:\Program Files\Microsoft VS Code\resources\app\extensions\npm -> vscode.npm
	c:\Program Files\Microsoft VS Code\resources\app\extensions\php-language-features -> vscode.php-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\search-result -> vscode.search-result
	c:\Program Files\Microsoft VS Code\resources\app\extensions\simple-browser -> vscode.simple-browser
	c:\Program Files\Microsoft VS Code\resources\app\extensions\testing-editor-contributions -> vscode.testing-editor-contributions
	c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features -> vscode.typescript-language-features
	c:\Users\SESA404214\.vscode\extensions\asabil.meson-1.3.0 -> asabil.meson
	c:\Users\SESA404214\.vscode\extensions\asciidoctor.asciidoctor-vscode-2.8.7 -> asciidoctor.asciidoctor-vscode
	c:\Users\SESA404214\.vscode\extensions\belfz.search-crates-io-1.2.1 -> belfz.search-crates-io
	c:\Users\SESA404214\.vscode\extensions\bierner.markdown-checkbox-0.1.3 -> bierner.markdown-checkbox
	c:\Users\SESA404214\.vscode\extensions\bungcip.better-toml-0.3.2 -> bungcip.better-toml
	c:\Users\SESA404214\.vscode\extensions\gruntfuggly.shifter-0.0.6 -> Gruntfuggly.shifter
	c:\Users\SESA404214\.vscode\extensions\jebbs.plantuml-2.14.3 -> jebbs.plantuml
	c:\Users\SESA404214\.vscode\extensions\matklad.rust-analyzer-0.2.505 -> matklad.rust-analyzer
	c:\Users\SESA404214\.vscode\extensions\ms-python.python-2021.2.582707922 -> ms-python.python
	c:\Users\SESA404214\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157 -> ms-toolsai.jupyter
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0 -> ms-vscode-remote.remote-containers
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.0 -> ms-vscode-remote.remote-ssh
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-ssh-edit-0.65.0 -> ms-vscode-remote.remote-ssh-edit
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-wsl-0.54.0 -> ms-vscode-remote.remote-wsl
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.cmake-tools-1.6.0 -> ms-vscode.cmake-tools
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.cpptools-1.2.2 -> ms-vscode.cpptools
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.powershell-2021.2.2 -> ms-vscode.powershell
	c:\Users\SESA404214\.vscode\extensions\rust-lang.rust-0.7.8 -> rust-lang.rust
	c:\Users\SESA404214\.vscode\extensions\serayuzgur.crates-0.5.6 -> serayuzgur.crates
	c:\Users\SESA404214\.vscode\extensions\twxs.cmake-0.0.17 -> twxs.cmake
	c:\Users\SESA404214\.vscode\extensions\wakatime.vscode-wakatime-5.0.1 -> WakaTime.vscode-wakatime
```

**Comment by Bellybutn278** [comment] 2021-03-11 22:23
What was the issue

**Comment by weinand** [comment] 2021-03-11 23:16
@alexdima wow, thanks a lot for connecting the dots!
@isidorn we are off the hook!

**Comment by jrieken** [comment] 2021-03-12 09:33
Maybe the same as https://github.com/microsoft/vscode-remote-release/issues/4602. I don't recall any changes and the code that builds the extension tree is quite old (mature). However, we did change the node version this milestone and maybe some things around realPath have changed

**Comment by jrieken** [comment] 2021-03-12 11:09
@michalfita thanks for reporting. This is a very interesting issue. A few questions

* VS Code seems to be confused about the casing for the folder in which your extension live. What is the actual casing of your user folder: `c:\Users\sesa404214` or `c:\Users\SESA404214`?
* How do you start VS Code? From the command line? Iff so what case path & casing was used in the command line?

**Comment by bpasero** [comment] 2021-03-12 11:50
It would be great to figure out if this is indeed a regression from us or not, as such, posting Windows standalone versions of VSCode to try to see whether the issue reproduces:
* `1.53.x` (this version [updated](https://code.visualstudio.com/updates/v1_53#_electron-11-update) Electron to 11): [Download](https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip)
* `1.52.x` (this version still runs with Electron 9): [Download](https://az764295.vo.msecnd.net/stable/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/VSCode-win32-x64-1.52.1.zip)

**Comment by fabioz** [comment] 2021-03-12 11:51
I can't say for @michalfita, but I'm able to reproduce the issue when running my extension in development mode. 

There's no special casing, but I use a subst drive (i.e.: `x:` points to `c:\x`).

Note that until now my extension used the `"vscode": "^1.43.0"` engine, and in a branch (after this commit: https://github.com/robocorp/robotframework-lsp/commit/e3fb5c023ef4bc6243e3fa4b798cc8fb209636fe) when I upgraded to the `"vscode": "^1.53.0"` engine (with an install of vscode `1.54.1`) it started failing.

If you want to reproduce, I think you could:
1. Create the `x:` subst
2. Make sure you have a Python 3.8 env with the fire library -- in Python 3.8 it's something as:

```
conda create -n temp python=3.8
activate temp
pip install fire
```

3. Get the code and start the extension

```
x:
mkdir temp
cd temp
git clone https://github.com/robocorp/robotframework-lsp.git -b syntax_259
cd robotframework-lsp/robotframework-ls
yarn install
python -m dev vendor-robocorp-ls-core
```

4. Open the folder: `X:\temp\robotframework-lsp\robotframework-ls`, run the extension with the launch available and see the error in the output (I'm catching the error and printing it to the output in that branch for now: https://github.com/robocorp/robotframework-lsp/blob/syntax_259/robotframework-ls/vscode-client/src/extension.ts#L215 -- if you remove that try..catch the extension will fail to start).

![image](https://user-images.githubusercontent.com/117621/110936693-0e720180-8310-11eb-8ed4-8ab32a1d6865.png)

**Comment by fabioz** [comment] 2021-03-12 11:52
> It would be great to figure out if this is indeed a regression from us or not, as such, posting Windows standalone versions of VSCode to try to see whether the issue reproduces:
> 
>     * `1.53.x` (this version [updated](https://code.visualstudio.com/updates/v1_53#_electron-11-update) Electron to 11): [Download](https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip)
> 
>     * `1.52.x` (this version still runs with Electron 9): [Download](https://az764295.vo.msecnd.net/stable/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/VSCode-win32-x64-1.52.1.zip)

If I run with `1.54.1` it fails. If I run with `1.53.2` it does NOT fail.

**Comment by fabioz** [comment] 2021-03-12 11:56
i.e.: 

Working:
![image](https://user-images.githubusercontent.com/117621/110937115-aec82600-8310-11eb-8a7a-e33bf015a771.png)

Not working:
![image](https://user-images.githubusercontent.com/117621/110937233-d61ef300-8310-11eb-8f76-681b79c6078a.png)

**Comment by jrieken** [comment] 2021-03-12 12:27
> There's no special casing, but I use a subst drive (i.e.: x: points to c:\x).

Very likely the same as https://github.com/microsoft/vscode/issues/118812#issuecomment-797458607

@fabioz How do you start vscode? From the console? Iff so from what path?

>The issue is NOT present when code.exe is started from command prompt with cwd being the actual physical path i.e. NOT using the subst.

Can you also try that (see https://github.com/microsoft/vscode/issues/118812#issuecomment-797445161)

**Comment by fabioz** [comment] 2021-03-12 12:30
> @fabioz How do you start vscode? From the console? Iff so from what path?

No, I just double-click the launcher (which points to `C:\Program Files\Microsoft VS Code\Code.exe`).

**Comment by bpasero** [comment] 2021-03-12 12:32
Thanks a lot for trying this, I have pinged @deepak1556 to update us whether anything changed in electron/node for our latest stable release.

**Comment by VincencPodobnik** [comment] 2021-03-12 13:02
Investigated a little bit more and the problem is also present when using `net use`

**Comment by michalfita** [comment] 2021-03-12 15:57
> VS Code seems to be confused about the casing for the folder in which your extension live. What is the actual casing of your user folder: c:\Users\sesa404214 or c:\Users\SESA404214?

I'm surprised anything on Windows would be case sensitive. It's the former - all uppercase.

**Comment by bpasero** [comment] 2021-03-12 16:15
@michalfita when this problem happens, how do you launch VSCode. From a terminal or start menu / launcher?

**Comment by michalfita** [comment] 2021-03-12 16:34
In this case they were launched from the Start menu eventually a new windows from inside already running vscode if that matters.

**Comment by deepak1556** [comment] 2021-03-12 23:33
There is indeed electron minor version bump from `1.53.2` to `1.54.0` but there is no node version change and I have looked through the electron commits, nothing related to this code path in node was changed.

To rule out runtime effects, I updated `1.54` branch to same runtime as `1.53` and followed steps https://github.com/microsoft/vscode/issues/118812#issuecomment-797527967, the issue was still reproducible. I also switched the runtime to use binaries from https://electronjs.org/ to rule out any internal patches.

So this is purely a regression on our app code, maybe git bisect would be next course of action ?

**Comment by deepak1556** [comment] 2021-03-13 04:05
```
b28cd23d521059938e08515618cdc670f3baa79b is the first bad commit
commit b28cd23d521059938e08515618cdc670f3baa79b
Author: Benjamin Pasero <benjpas@microsoft.com>
Date:   Wed Feb 3 11:29:26 2021 +0100

    fs - more removal of promisify utility

 src/vs/base/node/extpath.ts                                         | 5 ++---
 src/vs/base/node/pfs.ts                                             | 5 ++---
 src/vs/base/node/processes.ts                                       | 6 +++---
 src/vs/platform/files/node/diskFileSystemProvider.ts                | 4 ++--
 src/vs/workbench/api/node/extHostTunnelService.ts                   | 3 +--
 .../contrib/performance/electron-browser/startupTimings.ts          | 5 ++---
 src/vs/workbench/services/extensions/node/proxyResolver.ts          | 3 +--
 7 files changed, 13 insertions(+), 18 deletions(-)
 ```

**Comment by deepak1556** [comment] 2021-03-13 04:07
This is a fun one, the problematic call was the conversion from `fs.realpath` callback version to the promise version on line https://github.com/microsoft/vscode/commit/b28cd23d521059938e08515618cdc670f3baa79b#diff-505206763bd72133dfaa593fe504440c0d863477741e23d87ed706bca6aa8a57R55 . Node gives different results for these.

```
> fs.realpath('.\\vscode-oss\\vscode\\extensions\\microsoft-authentication\\out\\extension.js', (err, path) => console.log(path))
undefined
> A:\vscode-oss\vscode\extensions\microsoft-authentication\out\extension.js

>
> fs.promises.realpath('.\\vscode-oss\\vscode\\extensions\\microsoft-authentication\\out\\extension.js').then((path) => console.log(path))
Promise { <pending> }
> D:\github\vscode-subst\vscode-oss\vscode\extensions\microsoft-authentication\out\extension.js
```

**Comment by deepak1556** [comment] 2021-03-13 04:10
According to the docs, the promise version of `realpath` is equivalent to `realpath.native`

**Comment by bpasero** [comment] 2021-03-13 07:44
👏

**Comment by weinand** [comment] 2021-03-13 09:57
@deepak1556 great work, thanks a lot!

**Comment by jrieken** [comment] 2021-03-15 07:25
wow, nice find @deepak1556

**Comment by bpasero** [comment] 2021-03-15 10:38
This fix has been pushed to `main` for insiders but also a recovery for Feb.

**Closed by bpasero** 2021-03-15 10:38 UTC
Labels: candidate, important, regression

**Comment by weinand** [comment] 2021-03-15 11:44
The fix for this should also fix the following issues:
- Remote-SSH does not work with 1.54 and --extensions-dir option https://github.com/microsoft/vscode/issues/118812
- Extensions using proposed API don't work in 1.54

And maybe:
- VSCode can't sign in with GitHub and creates endless boxes in the "Source Control" panel https://github.com/microsoft/vscode/issues/118351

**Comment by AnrDaemon** [comment] 2021-03-16 07:11
Does it also fix #92945 and #112231 or they require a separate attention?

**Comment by weinand** [comment] 2021-03-16 08:24
@AnrDaemon no, those two issues preceded the commit that resulted in this regression.

**Comment by SlurpTheo** [comment] 2021-03-23 13:27
> This is a fun one, the problematic call was the conversion from `fs.realpath` callback version to the promise version on line [b28cd23#diff-505206763bd72133dfaa593fe504440c0d863477741e23d87ed706bca6aa8a57R55](https://github.com/microsoft/vscode/commit/b28cd23d521059938e08515618cdc670f3baa79b#diff-505206763bd72133dfaa593fe504440c0d863477741e23d87ed706bca6aa8a57R55) . Node gives different results for these.
> 
> ```
> > fs.realpath('.\\vscode-oss\\vscode\\extensions\\microsoft-authentication\\out\\extension.js', (err, path) => console.log(path))
> undefined
> > A:\vscode-oss\vscode\extensions\microsoft-authentication\out\extension.js
> 
> >
> > fs.promises.realpath('.\\vscode-oss\\vscode\\extensions\\microsoft-authentication\\out\\extension.js').then((path) => console.log(path))
> Promise { <pending> }
> > D:\github\vscode-subst\vscode-oss\vscode\extensions\microsoft-authentication\out\extension.js
> ```

Whoa, has an issue been filed with node? [That](https://github.com/microsoft/vscode/pull/118956/files) `promisify(fs.realpath)(path)` behaves differently than `fs.promises.realpath(path)` (i.e., it performs like `fs.realpath(path)`)?
