### ISSUE TITLE
Spam find next and find previous in iFrame search leads to no selection

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127485] opened 2021-06-29 14:28 UTC
Testing #127173

1. Search a word
2. Spam find next / find previous
3. 🐛 You will get to a point where both buttons are disabled and nothing is highlighted.

**Comment by rzhao271** [comment] 2021-06-30 19:55
Duplicate of #127458.

**Closed by rzhao271** 2021-06-30 19:55 UTC
