### ISSUE TITLE
VSCode forgets the file that was open after restarting it when uninstalling an extension.

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#264] opened 2015-11-19 17:42 UTC
Clicking on the Restart Now button after uninstalling an extension loads an empty VSCode instance with an empty new file and forgets the file that I was working on.

Only happens with files, not if I have a folder open.

I couldn't seem to trace it.

**Comment by hashhar** [comment] 2015-11-19 17:48
Which of these files is it related to?
https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchExtension.ts
OR https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts

**Comment by hashhar** [comment] 2015-11-19 17:57
Ironically the code looks perfectly fine here https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts#L173-L182

https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/platform/instantiation/common/instantiation.ts

Might be an isolated occurrence. I'll try reproducing it.

**Comment by bpasero** [comment] 2015-11-19 17:58
@hashhar we currently do not persist any UI state when you dont open a folder. So you should be able to easily reproduce this by opening Code empty, open a file in it, close and reopen and it will be empty again.

**Comment by hashhar** [comment] 2015-11-19 18:01
I was able to reproduce it. And you are right, opening a workspace didn't face this issue. So, is there going to be a fix for this? Because I find this a normal scenario.

I would like to try to and work on it too (but don't expect my work to be merge worthy). So could you guide me about the related files?

**Comment by bpasero** [comment] 2015-11-19 18:12
If you open a folder in VS Code, we associate all UI state with the folder you opened (you could call this a "session"). When you open no folder, but just files, we do not store any UI state at all. 

Basically in the no-workspace case we need to come up with meaningful identifiers to associate the UI state to. You can have more than one window opened, each without workspace and each with different set of files opened, so it is not as trivial as just picking one random identifier :)

**Comment by bpasero** [comment] 2015-11-22 13:35
Dupe of #207

**Closed by bpasero** 2015-11-22 13:35 UTC
