### ISSUE TITLE
Can't click on inline diff icon if cursor is not not directly on top of it

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/vscode#214541] opened 2024-06-07 02:42 UTC
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

https://github.com/microsoft/vscode/assets/68118705/b13532bb-278a-4aad-b9f6-9d14732ed929

It even shows the hover tooltips, but can't click on it, I know this is for not colliding with folding (#36237), but this is quite hard to click on if there's no folding button in the way

**Comment by lszomoru** [comment] 2024-06-07 12:19
@alexr00, do I remember correctly that we have spoken about this being a regression?

**Comment by alexr00** [comment] 2024-06-20 07:47
I went back 6 years ago to version 1.20 and found the same behavior there, so if it's a regression it's a really old one. It's still confusing and should be fixed though.

**Comment by lszomoru** [comment] 2024-12-10 12:03
Duplicate of [#197883](https://github.com/microsoft/vscode/issues/197883)

**Closed by lszomoru** 2024-12-10 12:03 UTC
Labels: bug, scm
