### ISSUE TITLE
Replace all not working on large file

### ISSUE THREAD

**Issue by clankill3r** [Microsoft/vscode#47960] opened 2018-04-16 13:06 UTC
- VSCode Version: 1.22.2
- OS Version: OS X 10.12.6

I have a really large svg file (900mb).
I try to use replace all on `<!-- Circle -->` to get rid of those comments.
It has more then 19999+ of those.
Replace all does nothing, replace 1 by 1 does work.

If you can't reproduce this then I can see if I can upload the file somewhere.

**Comment by rebornix** [comment] 2018-09-04 23:30
Duplicate of https://github.com/Microsoft/vscode/issues/40580, let track it there. Thanks!

**Closed** 2018-09-04 23:30 UTC
Labels: *duplicate, bug, editor-find, editor-textbuffer
