### ISSUE TITLE
Terminal Clear Issue

### ISSUE THREAD

**Issue by CluxOP** [microsoft/vscode#212590] opened 2024-05-13 10:06 UTC
Type: <b>Bug</b>

1) Create  a basic script. (I am facing problem while using python)
2) Run the file in the terminal.
3) Clear the terminal.
4) Run the file again.

I am doing the same step as above and when i run the file again my terminal is blank in the places where there were text and if i just zoom in the window I can see the previous command again and if I write before running, my cursor automatically just goes down 5-7 line below.

And also I just tried this on my brand new windows laptop and the same problem is faced.
Here is the Screenshot:
![Terminal Issue](https://github.com/microsoft/vscode/assets/129303370/a4a53f9c-b7ee-4a17-99af-d3d65472e890)

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.73GB (0.60GB free)|
|Process Argv|--crash-reporter-id 129ab40d-3362-40ae-a7ae-d5cf37bbb41f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
font-switcher|eva|4.1.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31038041
pythonprt:31039817
dwnewjupyter:31039675

```

</details>

**Comment by meganrogge** [comment] 2024-05-13 15:15
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-05-13 15:15 UTC
