### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by ovidius72** [Microsoft/vscode#12376] opened 2016-09-21 11:23 UTC
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

I'm trying to switch to vscode from another IDE.
I was wondering if it is possible to have an intellisense that do this:

if I have a variable called myVariable I would like to have it suggested if i enter just a few letters.. For example "mv" or "vbl" that are part of the variable name.
It looks like it only work for uppercase letter, so for example if the variable name is MyVariable and I enter MV it is correctly suggested.
I think it is related to case-sensitive settings, but I haven't found anything to change for this.
I appreciate any suggestions
Thx.

**Comment by chrmarti** [comment] 2016-09-21 17:44
@aeschli Maybe an extension could contribute this?

**Comment by joaomoreno** [comment] 2017-02-02 08:24
Duplicate of #10324

**Closed by joaomoreno** 2017-02-02 08:24 UTC
Labels: extension-candidate, question
