### ISSUE TITLE
Visual Studio Code stuck off screen

### ISSUE THREAD

**Issue by PetterS** [microsoft/vscode#86733] opened 2019-12-11 09:53 UTC
- VSCode Version: 1.40.2
- OS Version: Windows 10 1909

Visual Studio sometimes gets stuck completely off screen and closing and reopening the program does not help. External monitor combined with changes to the scale in 4k mode seems to cause this somehow.

This has been reported many times; e.g. #73534 #35148 #36122

Workaround
========
- Select the window in the taskbar (it will not be visible)
- Press Alt+Space. Then press x
- Resize the now maximized window with the mouse.

**Comment by PetterS** [comment] 2019-12-12 09:28
Sure, feel free to close this issue if you want.

But there really is something going on here. There are many issues reported about this.

Just add a check so that VS Code never opens completely off screen. That would go a long way. Surely there is no use case where one wants VS Code completely off screen?

**Comment by bpasero** [comment] 2019-12-12 09:30
@PetterS there are checks to do that, feel free to review the code here:

https://github.com/microsoft/vscode/blob/101335eaf0ff3a15ad38732323df637efb5f9bb3/src/vs/code/electron-main/window.ts#L847-L858

> Visual Studio sometimes gets stuck completely off screen

The reason I asked for more info is to understand how you got there so that I can reproduce this issue. If you are not able to provide this information, then yes, please close the issue.

**Comment by PetterS** [comment] 2019-12-12 09:55
It appeared on a laptop running:
- in 4k, 200% scale.
- Then a cloned external monitor was attached and scale reduced to 100%.
- When scale was changed again, VS code got stuck outside. No combination of restarting, changing scale, rebooting could fix that.

Somehow the code you linked gets incorrect input.

**Comment by bpasero** [comment] 2019-12-12 09:58
@PetterS wait, so you say VSCode was running all the time and the OS decided to move windows around, is that true? Or was VSCode closed, you attached the monitor, you started VSCode and then it was off?

In the former case, I encourage you to file a bug against the OS why the OS puts the window out of view. That is nothing VSCode can control.

**Comment by PetterS** [comment] 2019-12-12 10:14
One more detail that could be relevant: VS Code was attached to the right side of the screen.

I closed VS code when it was in view, then could not reopen it.

**Comment by bpasero** [comment] 2019-12-12 10:16
@PetterS can we add more details to https://github.com/microsoft/vscode/issues/86733#issuecomment-564933990 and outline where exactly VSCode was running, was stopped, was restarted, was moved or was not touched? Otherwise I will have a hard time to reproduce.

**Comment by PetterS** [comment] 2019-12-12 10:32
I'm sorry, I'm afraid not.

**Comment by bpasero** [comment] 2019-12-13 07:05
@PetterS Latest insider builds have a bit more logging around this (https://code.visualstudio.com/insiders/). When you run `code-insiders --verbose` from the command line, there are 3 things in the output that would help to diagnose this issue:
* `window#validateWindowState: 1 display { x: 0, y: 23, width: 2560, height: 1332 }` - this is the state to restore as we found it from the previous session
* `window#ctor: using window state { mode: 1, x: 0, y: 23, width: 2560, height: 1331 }` - this is the validated state from the previous session which will try to prevent putting the window outside the visible rectangle
* ```
onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: {
      id: 'e3cdb405dff44ddaeb3d6c68dd167e33',
      configURIPath: 'file:///Users/bpasero/Development/Microsoft/vscode.code-workspace'
    },
    folder: undefined,
    backupPath: '/Users/bpasero/Library/Application Support/Code - ' +
      'Insiders/Backups/e3cdb405dff44ddaeb3d6c68dd167e33',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 0,
      y: 23,
      width: 2560,
      height: 1331
    }
  },
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 1, x: 384, y: 176, width: 1024, height: 768 }
  },
  openedWindows: []
}
``` - this is on shutdown the state we persist (which should match the state we get on the next startup)

Can you try when this happens to capture these values?

**Comment by bpasero** [comment] 2019-12-13 07:24
Also: does it reproduce with our previous release (needs to be 1.40.1) from: https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip

**Comment by PetterS** [comment] 2019-12-13 07:31
I'm afraid I don't have the external monitor any more (was travelling), so cannot reproduce.

That logging looks like exactly want we want to capture to diagnose this, though. Thanks! Will keep that in mind.

**Comment by bpasero** [comment] 2019-12-13 09:02
Ok, then I will close this issue.

**Closed by bpasero** 2019-12-13 09:02 UTC
Labels: needs more info, workbench-window
