### ISSUE TITLE
complet is not useful and prefect !

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Microsoft/vscode#37130] opened 2017-10-30 10:10 UTC
- VSCode Version:
1.17.2
- OS Version:
10.13

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/7554917/32165078-8db5ad08-bd9c-11e7-9199-ba526fedc810.png)
![image](https://user-images.githubusercontent.com/7554917/32165101-9a54e7c2-bd9c-11e7-87a0-2032e6096d51.png)

On sublime text, if i open __file_a.txt__ and __file_b.txt__, in __file_a.txt__ when i type "a" and type tab,sublime will complet with "asdfghjkl". 
But on vscode can't complet it.  vscode just complet strings which appear in current file!

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment] 2017-10-30 10:13
dupe of #20886

**Closed by jrieken** 2017-10-30 10:13 UTC
Labels: suggest
