### ISSUE TITLE
It's not possible to step into the code when not running

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2471] opened 2016-01-27 21:15 UTC
F10 or F11 do not function to step into the code when in the debugger is not running. I think they should step and stop on first line

**Comment by isidorn** [comment] 2016-01-28 08:47
@SteveALee can you please elaborate? You want the F10 and F11 to step and stop while you are not in a debug session?

**Comment by SteveALee** [comment] 2016-01-28 10:16
@isidorn  Sorry - that was a rubbish bug

VSCode 0.10.6 (would be helpful if could copy text from "About")
Node 4.2.5 (using npm-windows but that should have no impact)
Windows 10 Pro 1511

Steps
1) Select the debug icon so the debug view is open
2) Press F10 or F11

Expected results
* The debugger is started and execution stopped on the first line of program
* Perhaps stop on first line of the open file if the 'main' file of the program is not known
* See Visual Studio for reference

Actual Results
F10 does nothing and F11 goes full screen.

**Comment by isidorn** [comment] 2016-01-28 10:26
Thanks for more details. However that is expected behavior. F10 and F11 are only active once you start a debug session.
We can not change the behavior of F11 -> full screen since that might break some people's flow.
For the debug to stop on the first line we would have to modify the user's launch.json which we do not touch automatically (set stopOnEntry:true).

Due to this two things I am closing this feature request as will not be supported

**Closed by isidorn** 2016-01-28 10:26 UTC
Labels: needs more info

**Comment by SteveALee** [comment] 2016-01-28 10:28
OK. Disappointing but I understand
