### ISSUE TITLE
High CPU and RAM consumption!!!

### ISSUE THREAD

**Issue by khteh** [microsoft/vscode#83275] opened 2019-10-25 06:47 UTC
With only ONE VSCode opened, load a solution, do nothing and just observe `top` output!
![VSCodeHighLoad](https://user-images.githubusercontent.com/3871483/67549061-f3601b00-f735-11e9-9b71-054e26176210.png)

```
$ ps -ef|grep "usr\/share\/code"
khteh    23018 30136 19 13:59 tty2     00:08:34 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --service-pipe-token=16400439426023775019 --lang=en-US --app-path=/usr/share/code/resources/app --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.39.2 Chrome/69.0.3497.128 Electron/4.2.10 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=16400439426023775019 --renderer-client-id=25 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
khteh    23245 23018 45 13:59 tty2     00:19:55 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
khteh    23340 23018  2 13:59 tty2     00:01:05 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=watcherService
khteh    23824 23018  0 13:59 tty2     00:00:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=searchService
khteh    30132  2099  6 Oct24 tty2     01:24:41 /usr/share/code/code --unity-launch
khteh    30136 30132  0 Oct24 tty2     00:00:00 /usr/share/code/code --type=zygote --no-sandbox
khteh    30168 30132  6 Oct24 tty2     01:29:04 /usr/share/code/code --type=gpu-process --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --disable-color-correct-rendering --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=15744226872408331532
khteh    30280 30136  0 Oct24 tty2     00:02:05 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --service-pipe-token=7853313932619912964 --lang=en-US --app-path=/usr/share/code/resources/app --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.39.2 Chrome/69.0.3497.128 Electron/4.2.10 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=7853313932619912964 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

- VSCode Version: 1.39.2
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. With only ONE VSCode opened, load a solution, do nothing and just observe `top` output!
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment] 2019-10-25 14:55
duplicate of https://github.com/microsoft/vscode/issues/83319

**Closed** 2019-10-26 10:01 UTC
Labels: needs more info
