### ISSUE TITLE
Hotkeys vs language switcher

### ISSUE THREAD

**Issue by o-rey** [Microsoft/vscode#27321] opened 2017-05-26 08:53 UTC
Some hotkeys stop working when the input language is switched.

- VSCode Version: 1.12.2
- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Make sure the hotkeys are working (example: Cmd+] - indent)
2. Switch input language (En -> Ru)
3. Try Cmd+] again (not working)

**Comment by alexandrudima** [comment] 2017-05-29 09:38
Duplicate of #27023

**Closed by alexandrudima** 2017-05-29 09:38 UTC
