### ISSUE TITLE
TypeScript "exclude" conflicts with types resolution

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#10285] opened 2016-08-08 02:43 UTC
- VSCode Version: 1.4.0
- OS Version: Win 10
- TypeScript Version: 2.0 beta (also set with `"typescript.tsdk": "./node_modules/typescript/lib"`)

Steps to Reproduce:

1. Create project with /src and /test folders.
2. Create tsconfig.json with:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "rootDir": "src/",
        "outDir": "lib/",
        "inlineSourceMap": true,
        "inlineSources": true
    },
    "exclude": [
        "node_modules",
        "test"
    ]
}
```
3. Run `npm install --save @types/node`
4. Create /test/test.ts and import `assert`.

The `assert` import leads to "Cannot find module 'assert'".

The reason why I excluded `test` in `tsconfig.json` is that the tests should not become part of the lib/ folder. Also, I have a separate tsconfig.json in the test/ folder which gets used by mocha via `mocha --require ./test/init.js test/**/*.ts`:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "inlineSourceMap": true,
        "inlineSources": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

The `init.js` file that is require'd by mocha contains:
```js
require('ts-node').register({
    project: 'test/',
    disableWarnings: true,
    fast: true
})
```

**Comment by dbaeumer** [comment] 2016-08-08 08:50
The problem is that the test folder doesn't see the global install typings due to the existence of the tsconfig.json. You can either install the typing there are well or link to the typing using a typings.d.ts file having a content like this
```ts
/// <reference path="../typings/index.d.ts" />
```

**Comment by letmaik** [comment] 2016-08-08 12:39
I see. Although I don't have a "typings/" folder anymore as I use the new typescript 2 way with the `@types/..` npm packages. What would be the best way in that scenario?

**Comment by dbaeumer** [comment] 2016-08-09 08:45
Then it should work as long as the node_modules folder is above the test folder. However I tried it and I couldn't make it work. Moving to the TS team to comment on this.

**Comment by dbaeumer** [comment] 2016-08-09 08:48
OK. I found out what needs to be done. You need to add the typings you need to see in the test folder to the tsconfig.json file. Something like this to see the node typings installed via @types/node.
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "inlineSourceMap": true,
        "inlineSources": true,
        "types": [
            "node"
        ]
    }
}
```

**Closed by dbaeumer** 2016-08-09 08:49 UTC

**Comment by dbaeumer** [comment] 2016-08-09 08:54
Opened https://github.com/Microsoft/TypeScript/issues/10221
