### ISSUE TITLE
Extensions and suggestions stopped working

### ISSUE THREAD

**Issue by MarioSamison** [Microsoft/vscode#71998] opened 2019-04-09 13:38 UTC
After the last update of VS Code, all of our extensions such as automatic import replacement and typescript suggestions aren't working anymore. Also VS Code runs really slow.

**Comment by polishedwp** [comment] 2019-04-09 16:10
For what is worth, @ #71863. 
This is happening with several extensions. I did test in Linux/Ubuntu VM and the problem doesn't "seem" to exist there. However, it was running slow but since I have not used VSC in a Virtual Machine before, the speed could have been from the VM. It was inserting the snippets properly though.

**Comment by Updy-karim** [comment] 2019-04-10 01:32
Is this the same us this issue you guys have encountered /Seen ?
https://github.com/Microsoft/vscode/issues/72037

**Comment by polishedwp** [comment] 2019-04-10 02:12
No, that is a different issue

**Comment by will-stone** [comment] 2019-04-10 08:21
@lewisflude upgraded `@types/styled-components` to 4.1.14 and pointed VSCode to use TS 3.3.3333 and all issues are gone. Thanks all.

**Comment by jdahdah** [comment] 2019-04-10 11:47
I can confirm that forcing VSCode (1.33.0) to use TypeScript 3.3.3333 has fixed the problems I was experiencing with the related issue https://github.com/dsznajder/vscode-es7-javascript-react-snippets/issues/61.

**Comment by mjbvz** [comment] 2019-04-10 21:36
Sounds like it could be #71886 but the description is too vague to tell. @MarioSamison please describe exactly what you are doing, what the expected behavior is, and what actually happens

Also test using [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by MarioSamison** [comment] 2019-04-11 07:41
@mjbvz changing the typescript version to the workspace typescript version fixed everything for me. It seems like the new typescript version in VS Code collides with the typescript versions in the projects we're working on.

**Comment by polishedwp** [comment] 2019-04-11 16:08
@MarioSamison In my case, I did not have typescript in my project, the version supplied in VS 1.33 was causing issues. I hope this is investigated before the next release.

**Comment by mjbvz** [comment] 2019-04-12 21:20
@MarioSamison Can you please check to see if the new VS Code 1.33.1 release also fixed the issue for you

@polishedwp Typescript tooling also powers our javascript support

**Comment by arilenz** [comment] 2019-04-15 08:50
@mjbvz I had the same issue as @MarioSamison in 1.33.0 release. Still have the same issue in 1.33.1

**Comment by polishedwp** [comment] 2019-04-15 10:52
@mjbvz The problem is better, but not entirely fixed. It works but in significantly slower than previous versions. For now, I have downgraded Typescript used by VS.

**Comment by mjbvz** [comment] 2019-04-17 18:10
Closing as duplicate of #71863 for original poster

@arilenz @polishedwp Please open new issues

**Closed by mjbvz** 2019-04-17 18:10 UTC
Labels: needs more info
