### ISSUE TITLE
Selection with Ctrl A selects also console

### ISSUE THREAD

**Issue by Phisherman** [Microsoft/vscode#10818] opened 2016-08-23 06:01 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 Enterprise 2015 LTSB

Steps to Reproduce:

1. Open terminal and explorer in VS Code. Click on file in explorer.
2. Press `Ctrl A`. This should only select the text from the opened file but it also selects the terminal text.

![image](https://cloud.githubusercontent.com/assets/2873986/17881711/d15f2402-6907-11e6-9c3d-567049e5249e.png)

**Comment by Tyriar** [comment] 2016-08-23 16:35
Cannot reproduce on Ubuntu, @Phisherman does this repro 100% of the time for you? Also does it occur on the [Insiders build](https://code.visualstudio.com/insiders) too?

**Comment by Phisherman** [comment] 2016-08-23 16:38
@Tyriar Yes. I tried it on two different PCs. Both with Windows 10 and I can reproduce this behaviour every time. I'll try the Insiders build later and will notice you.

**Comment by Phisherman** [comment] 2016-08-23 16:42
@Tyriar The Insiders build doesn't have this problem.

**Comment by Tyriar** [comment] 2016-08-23 16:52
@Phisherman great, looks like it's fixed already then :+1: I'll close this off.

**Closed by Tyriar** 2016-08-23 16:52 UTC
Labels: integrated-terminal, needs more info
