### ISSUE TITLE
Keep the history of find and replace strings

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18735] opened 2017-01-18 13:31 UTC
- VSCode Version:

Version 1.9.0-insider
Commit 39d761bf1f4ce7ea605539bdba41a8727b3c7ce0
Date 2017-01-18T07:21:35.814Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

1. Open any file, Enter find and replace strings
2. Close find & replace dialog & then close file
3. Open the same file. Click any word in the file & press `ctrl+f`. Your earlier search string is gone. You need to retype the whole search string & replace strings.

Like notepad++, you should have the ability to select previous search strings & replace strings. Otherwise, all complex regex you write for both search & replace strings are screwed as soon as you click in the wrong area and open the find dialog.

Currently `up` & `down` arrow move the cursor to the start & end of the search string, but they should be mapped to navigate search/replace string history

**Comment by thekalinga** [comment] 2017-01-18 13:34
Also, `ctrl+z` does not work properly with in search string field, in the above scenario aswell.

If the editor automatically replaces the search string with the work under cursor, `ctrl+z` behaviour is wierd

**Comment by roblourens** [comment] 2017-01-26 01:08
You can use alt+up/down to navigate the search string history and get back the replaced one.

**Comment by thekalinga** [comment] 2017-01-26 07:15
Thanks for that.

This comment is still valid

>Also, ctrl+z does not work properly with in search string field, in the above scenario aswell.

> If the editor automatically replaces the search string with the word under cursor, ctrl+z behaviour is weird & messes up the whole search string

**Comment by thekalinga** [comment] 2017-01-31 14:45
Also, alt+up, alt+down does not work for replace string input box, this works only for search input box

**Comment by smuuf** [comment] 2017-07-28 13:01
I usually have some complex wildcards in *"files to include"* and/or *"files to exclude"* fields and it's very annoying that these fields don't have some sort of history, too. 😭

**Comment by sandy081** [comment] 2017-08-21 09:12
@smuuf We recently implemented history navigation for `files to include` and `files to exclude` fields. Please check it out in latest stable or insiders. 

Only field to be supported is `replace`.

**Comment by smuuf** [comment] 2017-08-31 23:01
@sandy081 Yes, I believe that in the latest stable `1.15.1` the `files to include/exclude` fields do really have a history. Using `alt+up/down` while having focus in that fields lets user to browse its history.

Which is really cool. :) Thank you, guys.

**Comment by sandy081** [comment] 2017-12-04 09:31
Duplicate of #18233

**Closed** 2017-12-04 09:31 UTC
Labels: *duplicate, feature-request, search-replace
