### ISSUE TITLE
Settings sync removed an extension for no reason

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155990] opened 2022-07-22 19:06 UTC
All of a sudden, I no longer have GHPRI installed. When I go into `Show Sync Data` I see Settings Sync removed it 11 hours ago, but I'm 100% sure I never uninstalled it.

I know I have Settings Sync enabled in both vscode.dev and github.dev... are those scenarios doing unexpected things to my settings sync?

![image](https://user-images.githubusercontent.com/22350/180506704-e8819605-7789-4b86-8c59-d1c2b4817886.png)

**Comment by joaomoreno** [comment] 2022-07-26 11:50
I am sure that 4 days ago I re-added the extension.

Today, I'm on another machine, and GHPRI is again gone.

**Comment by sandy081** [comment] 2022-07-27 07:05
Lets sync on this

**Comment by joaomoreno** [comment] 2022-08-24 13:44
Closing as I couldn't repro.

**Comment by cam-rod** [comment] 2022-08-26 17:23
I was able to reproduce this issue. [github.dev](https://github.dev) will sometimes remove and then readd the GitHub Repositories, Issues & PR, and remotehub extensions, except it doesn't readd the `installed` keypair to the config, so when I return to my local installation the extensions will sometimes disappear. 

Not sure why it doesn't always reinstall though. Sometimes github.dev won't readd the missing extensions in time, so it gets removed. When the extensions are added without the `installed` keypair, the local machine can occasionally readd the missing config and keep the extension installed; other times it won't and the extension is removed.

Local machine logs from yesterday:

- [userDataSync.log](https://github.com/microsoft/vscode/files/9435032/userDataSync.log)
- Extension config history:
    - Remote removes extensions: [5c75facc-ffe2-4d12-b15e-b8d102652653_extensions_removed.log](https://github.com/microsoft/vscode/files/9435049/5c75facc-ffe2-4d12-b15e-b8d102652653_extensions_removed.log)
    - Remote readds extensions, but not marked as installed: [123c8a84-ac02-4050-8c2d-af9cdd32c2ef_readd_not_installed.log](https://github.com/microsoft/vscode/files/9435039/123c8a84-ac02-4050-8c2d-af9cdd32c2ef_readd_not_installed.log)
    - After I reinstall the extensions locally: [84cc92c6-8512-4d3a-9049-e08680c25817_manual_reinstall.log](https://github.com/microsoft/vscode/files/9435055/84cc92c6-8512-4d3a-9049-e08680c25817_manual_reinstall.log)

github.dev logs from a repro today:

- [userDataSync.log](https://github.com/microsoft/vscode/files/9435079/userDataSync.log)
- [extHost.log](https://github.com/microsoft/vscode/files/9435081/extHost.log)
- Extension sync history:
    - Removed extensions: [ded7e356-ac88-4753-8ee1-b562fb061746_remove.log](https://github.com/microsoft/vscode/files/9435091/ded7e356-ac88-4753-8ee1-b562fb061746_remove.log)
    - Readd extensions: [342a13eb-94ce-4fdc-b256-b7e12260f7c0_readd.log](https://github.com/microsoft/vscode/files/9435090/342a13eb-94ce-4fdc-b256-b7e12260f7c0_readd.log)

**Comment by sandy081** [comment] 2022-08-31 08:00
@cam-rod Thanks for logs and info. Reopening for investigation.

**Comment by sandy081** [comment] 2022-10-03 10:16
I am able to reproduce this with following steps:

1. Desktop 1: Install GHPRI pre-release extension and sync
2. vscode.dev: Trigger Sync. Note that this is a builtin extension here.
3. Desktop 2: Trigger Sync - Make sure GHPR extension is installed.
4. Desktop 1: Uninstall GHPRI extension
5. Desktop 2: Trigger Sync - Make sure GHPR extension is uninstalled.
6. vscode.dev: Trigger Sync. Make sure GHPRI extension exists in builtin extensions.
7. Desktop 1: Trigger Sync. Nothing changes. 
8. Desktop 2: Trigger Sync. Nothing changes. This step and above step are important because, even though nothing has changed, these machines update their last sync state to have GHPRI extension has builtin extension.
9. Desktop 1: Install GHPRI pre-release extension and sync  
10. Desktop 2: Trigger Sync

🐛 GHPRI extension is not installed.
🐛 Come back to Desktop 1: GHPRI extension is removed.

**Comment by sandy081** [comment] 2022-10-06 14:04
Improved extensions merging to make sure the builtin extensions are handled properly. Each machine remembers what builtin extensions it syncs and make sure it won't remove them while syncing. Also added some logs to get more information if the issue still occurs.

**Closed** 2022-10-06 14:21 UTC
Labels: bug, web, settings-sync

**Comment by joyceerhl** [comment] 2022-10-26 22:38
If I uninstall GHPRI from desktop and then Sync Now in vscode.dev, the extension appears to be 'uninstalled' on vscode.dev, is that expected? 
![image](https://user-images.githubusercontent.com/30305945/198151723-66848acb-b02c-4019-a284-d1dfa9899fc1.png)

After reloading the extension is still installed though.

**Comment by joyceerhl** [comment] 2022-10-26 22:39
I don't have a second desktop to verify with at the moment.
