### ISSUE TITLE
JSX attributes suggestions not showing

### ISSUE THREAD

**Issue by ccalvarez** [Microsoft/vscode#71496] opened 2019-03-31 02:15 UTC
- VSCode Version:  1.32.3
- OS Version: macOS High Sierra Version 10.13.6

Steps to Reproduce:

1. Create a new file named:  prueba.jsx
2. Add this code: 

```
import React, { Component } from 'react';
class prueba extends Component {
  state = {};
  render() {
    return <button />;
  }
}

export default prueba;
```

3. Place cursor after the `button` word, press `Space`, write _'onC'_ and press `Ctrl` + `Space` to show suggestions for the events supported by the button element.

Expected behaviour:  supported events shown:

![image](https://user-images.githubusercontent.com/2665104/55283790-a1821e80-5327-11e9-89d0-45c6e79290fa.png)

Actual behaviour:  No suggestions.

![image](https://user-images.githubusercontent.com/2665104/55283783-83b4b980-5327-11e9-866f-6a662f60b901.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-03-31 18:47
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? I can't reproduce this issue:

<img width="1080" alt="Screen Shot 2019-03-31 at 12 46 07 PM" src="https://user-images.githubusercontent.com/12821956/55293364-033b9a80-53b3-11e9-93cf-ee0141bad8c0.png">


Also, try adding `// @ts-check` to the top of the file to enable type checking in it. Does this show any errors?

**Comment by ccalvarez** [comment] 2019-04-01 17:17
@mjbvz hi.

I'm not on my macOS at the moment.  Right now I'm at work using:

VSCode Version: 1.32.3
OS Version: Windows 10 Pro Version 1709, Build 16299.847

and the suggestions are working fine:

![image](https://user-images.githubusercontent.com/2665104/55346242-41968f80-546f-11e9-8f41-ee6635b1d5af.png)

So it seems it's a problem with my macOS.  I'll do the test with VS Code Insiders as soon as I get home, and I'll let you know the result.

Thank you very much.

**Comment by mjbvz** [comment] 2019-04-12 21:46
Closing as more information is needed to investigate this

**Closed by mjbvz** 2019-04-12 21:46 UTC
Labels: javascript, needs more info
