### ISSUE TITLE
TS sever craches

### ISSUE THREAD

**Issue by Lemoneey** [microsoft/vscode#203810] opened 2024-01-30 16:17 UTC
Type: <b>Bug</b>

It is hard to reproduce.  Seems like its not overall vscode issue. Because this happens in particular project. Kinda found what causes the problem. If I remove all imports in file, where usually this error happens. Seems every thinks is fine. I think it might happen because of type issue

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:11.430Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (5.04GB free)|
|Process Argv|--crash-reporter-id 57210c59-122e-44fc-94ef-9392e07b98bc|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
vscode-great-icons|emm|2.1.102
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.155.0
copilot-chat|Git|0.11.1
todo-tree|Gru|0.0.226
svg|joc|1.5.3
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.28.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
vscode-mdx|uni|1.7.0
vim|vsc|1.27.2
pretty-ts-errors|Yoa|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30951919
3ef8e399:30949928

```

</details>

**Comment by mjbvz** [comment] 2024-01-30 19:18
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Lemoneey** [comment] 2024-01-31 07:31
@mjbvz My vs code version is 1.85.2. And I've tried it with ext disabled. Same problem

**Comment by Lemoneey** [comment] 2024-01-31 09:00
Update: Now Intellisence freezes. It takes too much time to figure out imports
![Screenshot 2024-01-31 at 14 59 26](https://github.com/microsoft/vscode/assets/47971145/ec8cc08d-fc9b-47b5-a990-6c669ee86ae7)

**Comment by mjbvz** [comment] 2024-01-31 22:16
Please test on the insiders build: 1.86

If you still see the issue, share a project which causes the issue

**Comment by Lemoneey** [comment] 2024-02-01 07:47
@mjbvz So far its good on 1.86. I had same problem with IntelliSense freezing, but after changing Typescript version from builtin to projects` one the freezes not happening anymore.

**Comment by mjbvz** [comment] 2024-02-21 21:51
Closing since it sounds like it's fixed. If it is still happening, please share an example project so we can investigate

**Closed by mjbvz** 2024-02-21 21:51 UTC
Labels: info-needed
