### ISSUE TITLE
ctrl+alt+arrow-up or ctrl+alt+arrow-dn flips the screen and NOT do multiple selection (see multiple selection in documentation). please remove from documantation

### ISSUE THREAD

**Issue by TsamiSH** [microsoft/vscode#105572] opened 2020-08-28 10:03 UTC
- VSCode Version: 1.48.2
- OS Version: win10

Steps to Reproduce:

1. remove from documentation
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ChrisLynchHPE** [comment] 2020-08-28 19:08
Wouldn't this be a defect?  Or did the feature get removed, in which case would warrant documentation to be  updated?

**Comment by RMacfarlane** [comment] 2020-08-28 22:31
I'm not able to reproduce this, the keybindings work as expected. Can you check your keybindings to see if there is an extension conflicting with them? Or perhaps you have another program that is causing the flip?

**Comment by senyai** [comment] 2020-08-29 12:24
Intel drivers typically flip the screen on `ctrl+alt+arrows`. I believe there's nothing vscode team can do about it. After the shortcuts are be disabled in Intel software, they work in vscode.

**Comment by TsamiSH** [comment] 2020-08-29 13:06
hi. thank you for your fasr reply.
at office it is a common prank on new workers to flip the screen with
ctrl+alt+arrow.
no connection to vscode. it is a Windows feature. with vscode flips screen
the same....

**Comment by RMacfarlane** [comment] 2020-08-29 17:02
Going to go ahead and close this, since changing the default keybinding would be disruptive.

**Closed by RMacfarlane** 2020-08-29 17:02 UTC
Labels: needs more info
