### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by s809** [microsoft/vscode#134495] opened 2021-10-06 11:28 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.5.0-dev.20211005

**Steps to reproduce crash**
1. Launch VS Code

**TS Server Log**
[tsserver.log](https://github.com/microsoft/vscode/files/7293279/tsserver.log)

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:56829:22)
    at getPropertyOfType (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:57479:24)
    at tryGetQualifiedNameAsValue (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49292:26)
    at resolveEntityName (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49349:133)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49272:24)
    at getTargetOfImportEqualsDeclaration (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:48729:28)
    at getTargetOfAliasDeclaration (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49091:28)
    at resolveAlias (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49140:30)
    at resolveSymbol (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:49130:67)
    at mergeSymbol (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47491:42)
    at c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47606:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47604:20)
    at mergeSymbol (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47515:21)
    at c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47606:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47604:20)
    at initializeTypeChecker (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:84706:21)
    at Object.createTypeChecker (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:47262:9)
    at Object.getTypeChecker (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:114142:79)
    at synchronizeHostData (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:159246:21)
    at Object.getProgram (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:159367:13)
    at AutoImportProviderProject.Project.updateGraphWorker (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:164377:53)
    at AutoImportProviderProject.Project.updateGraph (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:164306:42)
    at AutoImportProviderProject.updateGraph (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:165151:70)
    at Object.updateProjectIfDirty (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:165788:45)
    at InferredProject.Project.getPackageJsonAutoImportProvider (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:164926:32)
    at InferredProject.Project.updateGraph (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:164344:26)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:166483:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:168172:26)
    at c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:168446:97
    at Object.flatMap (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:168446:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:169604:46)
    at c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:171537:88
    at IOSession.Session.executeWithRequestId (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:171528:28)
    at IOSession.Session.executeCommand (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:171537:33)
    at IOSession.Session.onMessage (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:171563:35)
    at Interface.<anonymous> (c:\Users\NoNick\.vscode\extensions\ms-vscode.vscode-typescript-next-4.5.20211005\node_modules\typescript\lib\tsserver.js:174168:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by mjbvz** [comment] 2021-10-07 22:57
Duplicate of https://github.com/microsoft/TypeScript/issues/45874

**Closed** 2021-10-07 22:57 UTC
Labels: *duplicate
