### ISSUE TITLE
VSCode startup freezes - 1.18

### ISSUE THREAD

**Issue by codingcooker** [Microsoft/vscode#37878] opened 2017-11-09 05:28 UTC
Has been happening since the last few versions. Running on 1.18 now. Startup profiles as below

[dba8_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1456385/dba8_main.cpuprofile.txt)
[dba8_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1456386/dba8_renderer.cpuprofile.txt)

- VSCode Version: <code>Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)</code>
- OS Version: <code>Windows_NT x64 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)</code>
- Memory (System): <code>7.89GB (1.86GB free)</code>
- Memory (Process): <code>170.27MB working set (195.93MB peak, 142.36MB private, 43.43MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|44|
|main|app.isReady => window.loadUrl()|308|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|35058|
|renderer|require(workbench.main.js)|912|
|renderer|create extension host => extensions onReady()|52834|
|renderer|restore viewlet|91|
|renderer|restore editor view state|53416|
|renderer|overall workbench load|77731|
|main + renderer|start => extensions ready|113137|
|main + renderer|start => workbench ready|114108|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`dba8_main.cpuprofile.txt`
-`dba8_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-11-09 08:29
😱 this is known upstream issue that spawning processes is very slow at times... I am closing this as a dupe of https://github.com/Microsoft/vscode/issues/24884

<img width="1800" alt="screen shot 2017-11-09 at 09 27 05" src="https://user-images.githubusercontent.com/1794099/32595486-6847c5ec-c530-11e7-8d74-094fa42a7e63.png">

@codingcooker To understand more of this I wonder if this always happens to you or just sometimes?

**Closed** 2017-11-09 08:30 UTC
Labels: duplicate, perf-profile

**Comment by codingcooker** [comment] 2017-11-09 14:01
@jrieken Nothing special about the setup. It used to be fine like 4-5 versions ago, but then it started showing bad responsiveness ever since. The release notes for 1.18 mentioned performance improvements - so I jumped back by doing a clean install hoping that it would fix it, but in vain!

And yes, it happens all the time. Tried with disabling extensions - but the same issue.

**Comment by jrieken** [comment] 2017-11-09 16:22
> And yes, it happens all the time.

That is bad, but also a good thing because it'll allows us to drill into this. If you are up for it, please help us with this (as we don't see this on our machine). Please do the following:

1. Install Procmon, https://docs.microsoft.com/en-us/sysinternals/downloads/procmon
2. Close VS Code and other processes because procmon will record everything that happens on your machine
3. Start a recording via Procmon > File > Capture Events
4. Reproduce the slow startup of VS Code
5. Stop event capturing in procmon (uncheck File > Capture Events)
6. Right click the table title in procmon and ensure that "Duration" and  "Thread ID" are shown (in addition to the defaults)
7. Last, save the data (All events) as Comma-Separated-Values (CSV) and share it with us

*Note* that this file will contain things like fully qualified paths and processes other than VS Code. Feel free to share the data with me by email (https://github.com/jrieken) or other means.
