### ISSUE TITLE
Webview ViewColumn in API incorrrect

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#168350] opened 2022-12-07 22:28 UTC
Repro:
1. Run the webview extension sample.
2. Add 
```
console.log(`view column: ${this._panel.viewColumn}`);
```

to the `doRefactor` call in `extension.ts`

<img width="394" alt="image" src="https://user-images.githubusercontent.com/31675041/206309435-396059b4-d30e-4f4d-ace8-6d96b9b2e3c4.png">

3. Run the extension sample. Open a text editor and have the cat coding webview in the second column.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/31675041/206309747-ecc43e1d-33e5-4209-8dc0-0fc12f4545c1.png">

4. Close the text editor.
5. Notice that the viewColumn is still 2 for the webview panel. You can run `doRefactor` to see this printed in the console or just see that the cat is the Compiling Cat instead of the Coding Cat (my favourite cat gif in the sample) :'(
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/31675041/206309984-1902deec-02b6-4f3e-86b3-1f224d0e5814.png">

Causes https://github.com/microsoft/vscode-livepreview/issues/62

**Comment by mjbvz** [comment] 2022-12-08 00:20
Duplicate of #131677 I believe

**Closed by mjbvz** 2022-12-08 00:20 UTC
