### ISSUE TITLE
Extension fails to start in VScode latest (1.62.2)

### ISSUE THREAD

**Issue by vitalEol** [microsoft/vscode#137300] opened 2021-11-16 12:54 UTC
Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/42639787/141988344-63fd1279-a7a6-4b27-b4e6-c555d9abe2a7.png)

Steps to Reproduce:
1. Install & start Ungit extension [vscode-ungit](https://github.com/Hirse/vscode-ungit)
2. Extension fails to start (loading prompt never finishes)

Same extension is working on previous release of vscode
![image](https://user-images.githubusercontent.com/42639787/141988504-4e07ff19-522c-499b-a00a-117f8b73933e.png)

I have an issue logged on the extension project https://github.com/Hirse/vscode-ungit/issues/96 but it appears to be related to the latest updates to VScode

**Comment by gjsjohnmurray** [comment] 2021-11-16 12:59
Maybe related to #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Comment by vitalEol** [comment] 2021-11-23 10:28
Issue remains in latest update (v1.62.3), extension fails to start....
![image](https://user-images.githubusercontent.com/42639787/143008054-540131ae-1d5a-4171-bb5e-98a3fd5b1b22.png)

**Comment by lszomoru** [comment] 2021-11-26 15:51
I have looked into this and it looks like for some reason the `unit` server fails to [start](https://github.com/Hirse/vscode-ungit/blob/2b5d9cdbe56e3aa7831dad385308e4e93b34cbe3/src/extension.ts#L93). 
I have debugged the extension and it looks like the ungit process exits with [this message](https://github.com/FredrikNoren/ungit/blob/68feee8f989744493cf57ec6d700503e57552cfd/bin/ungit#L69).
I would suggest that you work with the extension author and see if you are able to track down the root cause of the problem. In the meantime you can manually start the ungit server before invoking the `Open ungit` command from the command palette.

**Closed** 2021-11-26 15:52 UTC
Labels: git, *caused-by-extension

**Comment by vitalEol** [comment] 2021-11-29 07:53
> I have looked into this and it looks like for some reason the `unit` server fails to [start](https://github.com/Hirse/vscode-ungit/blob/2b5d9cdbe56e3aa7831dad385308e4e93b34cbe3/src/extension.ts#L93). I have debugged the extension and it looks like the ungit process exits with [this message](https://github.com/FredrikNoren/ungit/blob/68feee8f989744493cf57ec6d700503e57552cfd/bin/ungit#L69). I would suggest that you work with the extension author and see if you are able to track down the root cause of the problem. In the meantime you can manually start the ungit server before invoking the `Open ungit` command from the command palette.

Logically, when the extension version has not changed and still works with VScode v1.61.2 but fails on v1.62.2+ then the first place to look at any issue is with changes.
The changes have occurred within the VScode - as to what those changes are and why those affect the extension starting up are unknown.
Has there been a change to how extensions are handled following v1.61.2?
