### ISSUE TITLE
window.titleBarStyle: custom menu items not visible when window too small

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/vscode#54274] opened 2018-07-13 18:48 UTC
- VSCode Version: 1.26.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code with `"window.titleBarStyle": "custom"` enabled in preferences.
2. Resize window to a small enough size
3. Open a menu
4. Observe that some menu items cannot be seen:

![code-small](https://user-images.githubusercontent.com/3902892/42707591-8f9e7ffc-868f-11e8-8e3d-a7e44454da07.png)

5. Using keyboard navigation, navigating down beyond the last visible item scrolls the entire window contents up out of sight:

![code-small2](https://user-images.githubusercontent.com/3902892/42707882-68dfcd8e-8690-11e8-9e05-3296fa47d10f.png)

Does this issue occur when all extensions are disabled?: Yes

I would suggest adding a mechanism to scroll the menu to see items that are outside of the available space for the window whenever possible, similar to system menus:

![code-suggestion](https://user-images.githubusercontent.com/3902892/42708529-6b5a3d04-8692-11e8-805c-f237acf105ae.png)

**Comment by sbatten** [comment] 2018-07-16 18:17
dupe of #52533

**Closed by sbatten** 2018-07-16 18:17 UTC
Labels: workbench-menu
