### ISSUE TITLE
Right click menu closes on right click release

### ISSUE THREAD

**Issue by cmsolomon** [microsoft/vscode#116517] opened 2021-02-12 02:54 UTC
Issue Type: <b>Bug</b>

I am using VS Code on ubuntu 20.04.1LTS 5.8.0-43-generic, x86_64.
VS Code is installed using deb file, not snap.
I am developing in C++ (linux-gcc-arm).

Problem:
In the editor window, when I right click (to find all references, or whatever), the right click menu is only shown for as long as I hold the right button down - releasing the button behaves as if I had left clicked whichever menu item the pointer is currently over.

I have confirmed behaviour is normal outside VS Code.

I have read of a similar issues with GitLense, so I have disabled that extension, which had no effect.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 3291)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.97GB (14.66GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b83f6678-03cd-4f96-a387-0f2fce063f0e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
vscode-great-icons|emm|2.1.64
shell-format|fox|7.0.1
gc-excelviewer|Gra|3.0.41
vscode-back-forward-button|gri|0.1.4
easy-icons|jam|0.3.1
theme-dark-plus-contrast|k3a|0.1.101
ruby-rubocop|mis|0.8.5
prettify-json|moh|0.0.3
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
cpptools|ms-|1.2.0
deepdark-material|Nim|3.3.0
ruby|reb|0.28.1
c-cpp-definition-generator|rei|0.0.2
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.1.0
debug|web|0.25.0
vscode-ruby|win|0.28.0
linkerscript|Zix|1.0.1
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by jayschwa** [comment] 2021-02-12 04:12
This might be a duplicate of https://github.com/microsoft/vscode/issues/113175.

**Comment by cmsolomon** [comment] 2021-02-14 23:08
Yes, it looks like a duplicate - should I just close this one or is there some way to mark it as a duplicate?

**Closed** 2021-02-16 15:12 UTC
Labels: *duplicate
