### ISSUE TITLE
Chinese display problem in integrated terminal

### ISSUE THREAD

**Issue by JiejiaH** [Microsoft/vscode#7036] opened 2016-05-31 02:16 UTC
- VSCode Version: 1.2.0-insider
- OS Version: 10.0.10586

All Chinese characters huddle together when I open the terminal, and if I resize the window , the space will change too.

![vscode-problem](https://cloud.githubusercontent.com/assets/13583692/15661209/1d832158-2718-11e6-95c2-14ca88311c72.png)

**Comment by Tyriar** [comment] 2016-06-21 17:58
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-21 17:58 UTC
Labels: bug, i18n, integrated-terminal
