### ISSUE TITLE
Support HTML Tags with Optional Closing Tag

### ISSUE THREAD

**Issue by nikeee** [microsoft/vscode#94287] opened 2020-04-02 13:57 UTC
HTML5 has tags where the closing tag is optional. These are: `html, head, body, p, dt, dd, li, option, thead, th, tbody, tr, td, tfoot, colgroup` ([source](https://blog.teamtreehouse.com/to-close-or-not-to-close-tags-in-html5))

A `<p>` tag automatically closes the one before, if there was one. So this:
```html
<p>Lorem
<p>ipsum
<p>dolor
<p>sit
<p>amet
```
is equivalent to this:
```html
<p>Lorem</p>
<p>ipsum</p>
<p>dolor</p>
<p>sit</p>
<p>amet</p>
```

The breadcrumbs (and the document outline) do not seem to be aware of this semantic. Instead of treating both code samples equally, it treats the paragraphs as nested elements when the optional closing tag is omitted.
![image](https://user-images.githubusercontent.com/4068864/78256803-503bda80-74f9-11ea-82e0-81846ac9e8f3.png)
![image](https://user-images.githubusercontent.com/4068864/78256850-5d58c980-74f9-11ea-93f1-3714dd4e6fcc.png)

This behaviour is the same for all of the above mentioned tags.

Link to spec: https://html.spec.whatwg.org/multipage/syntax.html#optional-tags ("12.1.2.4 Optional tags")

This also effects automatic indentation. VSCode formats the code as follows:
```html
<p>Lorem
    <p>ipsum
        <p>dolor
            <p>sit
                <p>amet
```
...which is unexpected.

The feature requested is that VSCode should detect HTML tags that get implicitly closed and treat them as if they were closed explicitly. This should be reflected in the document outline as well as in  code formatting.

**Comment by aeschli** [comment] 2020-04-03 08:58
duplicate of https://github.com/microsoft/vscode/issues/89850

**Closed by aeschli** 2020-04-03 08:58 UTC
