### ISSUE TITLE
Test Tour: Angular 2

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#23895] opened 2017-04-04 17:20 UTC
see #23385 for the theory.

Angular quick starter: https://github.com/angular/quickstart

Extensions: 
- [Angular language service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template)
- Setup tasks or use [NPM Script Runner](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script) to run the scripts in the package.json

Implement & run some [protractor tests](http://www.protractortest.org/#/).

**Comment by egamma** [comment] 2017-04-07 10:08
The quick start doesn't compile into a separate build directory, as a consequence the explorer is cluttered with derived resourced for `.js` and `.map.js`. You really need to configure `files.exclude`
```json
	"files.exclude": {
		"**/*.js": { "when": "$(basename).ts"},
		"**/*.js.map": true
	},
```
These settings are not trivial to configure. One idea would be that the TS extension detects this setup and prompts the user whether they want to exclude deriver `.js` and `.js.map` files.

**Comment by egamma** [comment] 2017-04-07 10:17
- Intellisense/hovering works out of the box
- with the Angular Language Service extension you also get Intellisense inside templates:
![image](https://cloud.githubusercontent.com/assets/172399/24796163/32ac5d6a-1b8c-11e7-99dd-1309634da28f.png)

**Comment by egamma** [comment] 2017-04-07 12:38
Tslint setup with the vsocde-tslint extension works out of the box. The quickstarter bundles its own tslint extension. 

Configuration: setting up a task that runs tslint with a problem matcher. Using `Configure Task Runner` > npm. This action does't create a task for tslint?  @dbaeumer 

```json
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "update",
            "args": ["update"]
        },
        {
            "taskName": "test",
            "args": ["run", "test"]
        }
    ]
}
```

Adding one for tslint with a problem matcher:
```json
        {
            "taskName": "lint",
            "args": ["run", "lint"],
            "problemMatcher": "$tslint4"
        }   
```
Would be nice to get Intellisense for variables after `"$`.

Tslint4 problemmatcher doesn't handle verbose output properly: https://github.com/Microsoft/vscode-tslint/issues/188

Could make it work when disabling the verbose output and overwriting the `absolute` `fileLocation` setting. (Nice that you can use a problem matcher as a template :rose:)
```
            "taskName": "lint",
            "args": ["run", "lint"],
            "problemMatcher": {
                "base": "$tslint4",
                "fileLocation": "relative"
            }
        }
```

**Comment by egamma** [comment] 2017-04-07 12:39
Karma Test Running. Just works and is neat, triggered using file watching, forced to create a test failure

![image](https://cloud.githubusercontent.com/assets/172399/24797585/2c6afa0a-1b92-11e7-922f-e9c373833b11.png)

**TO DO** Trying to debug a karma test

**Comment by egamma** [comment] 2017-04-07 12:41
The Angular Language Service extension is nice, we should recomment it for Angular development. This could be done by peeking into the package.json.

![image](https://cloud.githubusercontent.com/assets/172399/24800408/4da0a2c0-1ba0-11e7-8ecc-75dba7024907.png)

**Comment by kieferrm** [comment] 2017-04-08 00:14
Notes from our test tour. Neither @mjbvz nor I had any angular experience.

# Angular Starter Kit

## Setup
- bring up a fresh instance of vscode that has no extensions installed
- clone the starter kit repository
- open vscode on the cloned repo
- open a `.ts` file and the `package.json` file
- the files are showing errors because of missing dependencies (which is expected)
- **Note**
  - In both cases there should be a quick fix for running `npm install`
- when you run `npm install`, squiggles don't go away
-  `npm start ` .. success
- when simply pressing <kbd>F5</kbd> to launch you run into #24244 
- **Note**:
  - there are no recommendations in this scenario although the `package.json` file has clear references to `@angular`
  - when looking for an Angular extension, you don't have any idea which extension to choose. There are many, all using the same icon... You need to know that you want the **Angular Language Service**.
  - you want to use **angular-inline** extension to get `html` colorization in `@Component({ template: <html here})`
  - once you have that all setup, pretty much everything works out of the box
 - at one point I ended up in a state where the NG server started to use 100% CPU endlessly when I opened `${workspaceRoot}/node_modules/core-js/client/shim.js`. however, when I started with a fresh extension-dir and fresh user-dir I could not reproduce the issue (see https://github.com/angular/vscode-ng-language-service/issues/32#issuecomment-292622001)

## Debug
- you need to know that you need the **Chrome Debugger**, there is no recommendation
- when chrome is already open you run into #24250
- when setting up the chrome launch config you need to figure out the right value for `webroot`
- **Note**
  - When somebody is new to Angular and new to vscode, getting the debugger to work is just hard enough to be frustrated.
- combined launch config for server and protract tests just works

## Tasks
- straight forward - no issues


## Editing & Test Running
- works out of the box


## General
- when you get started with angular you need to know a lot of stuff (several layered test frameworks, ....)
- **Angular Productivity Pack** extension pack has a lot of goodies in it, Chrome however is missing
- everything is even easier once you know :wink:

# Using the Angular CLI
- using the angular CLI setup is comparable to the above although Matt and I preferred it over the starter kit
- one issue is that building happens through `ng build` rather than `tsc`. `ng uses `webpack`. When you setup the build task you need to setup your own problem matcher @mjbvz pls paste the problem matcher.

**Comment by dbaeumer** [comment] 2017-04-10 08:32
@egamma with the new extension story the tslint task should come from the tslint extension. The core should IMO not parse the package.json and should add any tslint tasks.

**Comment by mjbvz** [comment] 2017-04-11 20:10
Closing since we've complete the test tour. We've already opened a few issues to track discovered bugs and for a few feature requests, and feel free to open additional ones to track findings of this test tour

**Closed by mjbvz** 2017-04-11 20:10 UTC
Labels: testplan-item
