### ISSUE TITLE
The keyword color wrong after update to 1.86.0

### ISSUE THREAD

**Issue by qaqz111** [microsoft/vscode#204223] opened 2024-02-03 07:57 UTC
Type: <b>Bug</b>

I use portable mode that place a sub dir named "data" at VSCode dir where code.exe resides.
I do the update action by extracting new version zip file to a new directory and then move the sub dir "data" from old version to new version VSCode dir.

After update to 1.86.0 from 1.85.2, the keyword color of python file was wrong. 

I'm using the "Tomorrow Night Blue" theme.
The keywords lost their color which was set to #EBBBFF in TNB theme and presented with pure white (#FFFFFF).
![无标题1](https://github.com/microsoft/vscode/assets/3367034/72e2e6c2-dcf2-4e28-8371-e5bd2a464466)

When I move the "data" dir back to old v1.85.2 VSCode dir and launch v1.85.2 of code.exe, the color comes back.

I also tried a clean launch with an empty "data" folder, then change theme and load a python source code file, the problem is still there no matter install python language extension or not.

**Comment by qaqz111** [comment] 2024-02-03 15:20
I found this issue maybe referring the same problem #204197

**Comment by zackslash** [comment] 2024-02-03 16:48
Another issue referencing this same problem, unfortunately marked as *as-designed
[#203998](https://github.com/microsoft/vscode/issues/203998)

**Comment by KeeganEad** [comment] 2024-02-04 12:04
Same for me on TNB theme.  You get so used to a theme over years, that changes like these are very jarring.

**Comment by KeeganEad** [comment] 2024-02-04 12:31
Based on the thread above, I modified my settings like so to apply `#EBBBFF` to several text rules.   

Depending on your language you might have different scopes.    These were for Typescript. 

But you can use `CMD+SHIFT+P` `Developer: Inspect Editor Tokens and Scopes` to hover over the syntax and find the scope keys to use.   

```
{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "keyword.control.import.ts",
          "keyword.control.from.ts",
          "keyword.control.export.ts",
          "storage.type.ts",
          "meta.function.ts"
        ],
        "settings": {
          "foreground": "#EBBBFF",
          "fontStyle": ""
        }
      }
    ]
  }
}

```

**Comment by KeeganEad** [comment] 2024-02-04 12:52
I agree. I was just having a lot of trouble getting to work yesterday and this morning until I found a solution.  Like ain't nobody got time to be tweaking theme colors right now.   But it was just too distracting otherwise.

**Comment by zackslash** [comment] 2024-02-04 13:03
Downgrading to [v1.85](https://code.visualstudio.com/updates/v1_85) is also a temporary fix for this (i'm in the same boat, don't have bandwidth right now for the distraction)

**Comment by qaqz111** [comment] 2024-02-04 15:34
It looks like the grammar parsing rule has been at least partially changed, but I didn't find any information in 1.86 ReleaseNotes. For python the variables lost their color and presented using #FFFFFF confused that whether there were errors in the code file, which really is a disturb in working.

Also downgraded to v1.85.2 for now, looking forward next update to see if the problem will be settled down or at least an explanation about the rule change, or TNB theme update for 1.86+.

**Comment by sethvargo** [comment] 2024-02-04 15:44
Asking theme maintainers to update (many of which are archived and unmaintained) without any warning or guidance seems like a regression.

**Comment by aeschli** [comment] 2024-02-05 21:56
This was caused by https://github.com/microsoft/vscode/pull/200043/files#diff-feb7ff0a1e168824a90fd0d2f324602089bf3f6d84013c66880673952b5d306f

Fix is on the way...

**Closed** 2024-02-05 22:09 UTC

**Comment by levrik** [comment] 2024-02-06 07:59
Add the following to your `settings.json` to fix it while we wait for a release:

```jsonc
// Temporary workaround for https://github.com/microsoft/vscode/issues/204223
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "keyword, storage, storage.type, entity.name.tag.css, entity.name.tag.less",
      "settings": {
        "foreground": "#EBBBFF"
      }
    }
  ]
}
```
