### ISSUE TITLE
hard linked .env file gets misinterpreted as a shell script

### ISSUE THREAD

**Issue by ErnestoBorio** [microsoft/vscode#133294] opened 2021-09-17 00:05 UTC
Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. open .env file that is a hard link to other file.
2. observe that it's incorrectly recognized as a shell script.

I have several environment variables like `.env.local`, `.env.prod`, etc, and I make a hard link named '.env' to point to the environment I want to test.
All other `.env*` files I open get correctly recognized as `env` file type.
But `.env`, for a brief moment gets recognized as an env file, but after a second it turns into `shell script`.

The extension does the correct syntax highlighting for that brief moment but then the shell script highlighting kicks in.
I've tried the 3 most popular .env highlighting extensions and this happens with either and with none at all.

I have this in my `settings.json`:
```json
	"files.associations": {
		".env": "env",
		".env*": "env"
	},
```

- OS Version:
MacOS 11.5.2

- VS Code Version:
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (2 wks ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by IllusionMH** [comment] 2021-09-17 07:52
Looks like duplicate of #132173

Is it reproducible in latest stable version 1.60.1? Fix should be in place.
https://code.visualstudio.com/Download

**Comment by aeschli** [comment] 2021-09-17 10:00
duplicate of #132173

**Closed by aeschli** 2021-09-17 10:00 UTC

**Comment by GoudekettingRM** [comment] 2021-09-20 15:18
@IllusionMH I seem to have the same issue, but running `1.60.1`

```
Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

Running MacOs 10.15.7.

My `.env` gets recognized as a TS file though.
