### ISSUE TITLE
Add settings to show and insert file extension on import

### ISSUE THREAD

**Issue by wenfangcn** [microsoft/vscode#76789] opened 2019-07-07 03:13 UTC
When `"javascript.suggest.paths": true, "typescript.suggest.paths": true`  are enabled, currently vscode doesn't show and insert file extension on import. Can you add settings to enable them? It would result in cleaner and more efficient code.
![vscod](https://user-images.githubusercontent.com/28700378/60763477-34a9bd80-a0a8-11e9-858c-6e1be43ea3f5.gif)

**Comment by mjbvz** [comment] 2019-07-08 16:08
Duplicate of #https://github.com/microsoft/TypeScript/issues/16577

**Closed by mjbvz** 2019-07-08 16:08 UTC
Labels: javascript
