### ISSUE TITLE
Wrongly shows error - "expected '}'"

### ISSUE THREAD

**Issue by HoWingYip** [Microsoft/vscode#26505] opened 2017-05-12 04:30 UTC
![image](https://cloud.githubusercontent.com/assets/25481871/25982397/c494fa8c-370e-11e7-9cf0-0b8599598ec6.png)
HTML - shows error when there is none. It says it expected a curly brace at end of file.

EDIT: Attached zipped HTML file.
[sign-up.zip](https://github.com/Microsoft/vscode/files/999291/sign-up.zip)
This is for a school project. Thanks!

**Comment by egamma** [comment] 2017-05-12 06:33
@HoWingYip can you please share the entire html file that shows the error. We cannot reproduce this issue given the screenshot only.

**Comment by egamma** [comment] 2017-05-14 06:54
@HammyHavoc ping? please provide the requested additional information?

**Comment by egamma** [comment] 2017-05-15 07:50
@HammyHavoc We cannot handle this issue given the information above and have to close the issue. Please reopen the issue when you provide more information.

**Closed by egamma** 2017-05-15 07:50 UTC
Labels: needs more info
