### ISSUE TITLE
Open multiple files with the right-click menu "Opoen with Code" and only open one file.

### ISSUE THREAD

**Issue by panzhiyi3** [microsoft/vscode#68862] opened 2019-02-17 05:58 UTC
Issue Type: <b>Bug</b>

Open multiple files with the right-click menu "Opoen with Code" and only open one file.
0.Close all Code instance
1.Select multiple files
2.right click on one
3.Open with Code

If you have opened a Code instance, all files will be opened correctly

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (7.53GB free)|
|Process Argv|D:\development\DimensionTwo\Debug\resources\RefImageShader.fx|
|Screen Reader|no|
|VM|71%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.7
vscode-language-pack-zh-hans|MS-|1.31.4
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.2
vscode-lua|tri|0.12.4

</details>

**Comment by johnendev** [comment] 2019-02-25 23:18
Getting same issue. Opening multiple files simultaneously from Explorer starts Code and only opens 1 file. Sometimes Code also shows a message box that Code is not responding.

If Code is already running then it opens all the files correctly.

**Comment by YisraelV** [comment] 2019-03-03 16:56
I am not able to reproduce on Linux. 

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60

**Comment by devilirium** [comment] 2019-03-03 21:27
I wasn't able to reproduce it either. It was failing on Friday before the update that I've installed today. 

Version: 1.31.1 (Commit: 1b8e830)
OS: Windows 10 Enterprise N - 1803 (17134.590)

**Comment by lippens** [comment] 2019-03-12 07:59
![VSCode_issue](https://user-images.githubusercontent.com/14270073/54183129-4dc9a580-44de-11e9-9f8e-53167591b617.gif)
I reproduced this bug, see the gif attached.
And, I use the default for Window|New Window settings.

Version: 1.32.1 (Commit: [05f146c](https://github.com/Microsoft/vscode/commit/05f146c7a8f7f78e80261aa3b2a2e642586f9eb3))

**Comment by panzhiyi3** [comment] 2019-03-14 08:04
Problem still in 1.32.2
And each time I try to open multiple files,I got this messagebox
![image](https://user-images.githubusercontent.com/2980716/54340557-9914bd00-4672-11e9-99d5-f8d52dec9f18.png)

版本: 1.32.2 (system setup)
提交: e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
日期: 2019-03-13T02:00:46.035Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment] 2019-06-16 07:18
Possibly fixed by https://github.com/microsoft/vscode/commit/3fe6a332950c098557396c0dcd9ecf2dd2939fce and https://github.com/microsoft/vscode/commit/2af4677f96652c7120d56428bf557f6451278890

People should please try to reproduce with next weeks insider builds.

**Comment by panzhiyi3** [comment] 2019-06-18 08:07
> Possibly fixed by [3fe6a33](https://github.com/microsoft/vscode/commit/3fe6a332950c098557396c0dcd9ecf2dd2939fce) and [2af4677](https://github.com/microsoft/vscode/commit/2af4677f96652c7120d56428bf557f6451278890)
> 
> People should please try to reproduce with next weeks insider builds.

Tried new insider version, it works on my machine :D Thanks

Version: 1.36.0-insider
Commit: 11b88a3323878a98b418e4efca77e7afabd50d01
Date: 2019-06-17T05:17:47.485Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment] 2019-06-18 09:27
Awesome!

**Closed by bpasero** 2019-06-18 09:27 UTC
Labels: bug, help wanted, needs more info, windows, workbench-os-integration
