### ISSUE TITLE
Icons missing from sidebar in WSL - #687 on github

### ISSUE THREAD

**Issue by loftwah** [microsoft/vscode#80305] opened 2019-09-04 08:34 UTC
Issue Type: <b>Bug</b>

I am missing extension icons from the sidebar of vscode when using it within WSL. It doesn't seem to matter how I use the application, I get the same results.

Not a problem when using in Windows. WSL is getting awesome though, great stuff!

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.87GB (0.43GB free)|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.4.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
cisco|jam|1.6.2
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.7.0
remote-wsl|ms-|0.39.2
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.9.0
vscode-icons|vsc|9.3.0
JavaScriptSnippets|xab|1.7.2
Bookmarks|ale|10.5.0
project-manager|ale|10.7.0
azds|azu|1.0.120190830
vscode-django|bat|0.19.0
vscode-intelephense-client|bme|1.2.3
path-intellisense|chr|1.4.2
excel-to-markdown-table|csh|1.1.0
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
filter-line|eve|1.3.2
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
cloudcode|goo|0.0.11
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
rest-client|hum|0.22.0
reg|ion|1.0.1
sftp|lix|1.12.8
reflow-markdown|mar|2.0.0
vscode-azureappservice|ms-|0.15.0
vscode-kubernetes-tools|ms-|1.0.4
mssql|ms-|1.6.0
python|ms-|2019.8.30787
azure-account|ms-|0.8.4
Go|ms-|0.11.4
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.766
team|ms-|1.149.2
heroku-command|pko|0.0.8
text-power-tools|qcz|1.11.1
vscode-yaml|red|0.5.2
vscode-filter-json|ric|1.0.0
LiveServer|rit|5.6.1
copy-text|sal|0.4.3
todotasks|san|0.5.0
markdown-preview-enhanced|shd|0.4.3
stylelint|shi|0.51.0
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.1.9
FilterText|yhi|0.0.15
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-09-04 09:20
/duplicate of https://github.com/microsoft/vscode-remote-release/issues/966 > https://github.com/microsoft/vscode-remote-release/issues/687

Fixed in Insiders builds https://code.visualstudio.com/insiders/ and will be available with August 1.38 release.

**Closed** 2019-09-04 09:20 UTC
Labels: *duplicate
