### ISSUE TITLE
 Cannot set property 'theme' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32562] opened 2017-08-15 15:05 UTC
Issue Id: <b>f40c44ff-2959-779d-f3ef-83f96ed97c10</b><br /><br />*Versions* <br />- 1.15.0<br />-  2c3e2c291c515619f64e7c9cddf14c565b7f3d92<br />*Stack* <br />TypeError: Cannot set property 'theme' of null<br />[/vs/workbench/common/theme.ts#L405:15 (theme)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/common/theme.ts#L405:15 (theme))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L551:29 (fire)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L551:29 (fire))<br />[/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L377:8 (updateColorCustomizations)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L377:8 (updateColorCustomizations))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/workbench/services/configuration/node/configuration.ts#L324:34 (fire)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/configuration/node/configuration.ts#L324:34 (fire))<br />[/vs/workbench/services/configuration/node/configuration.ts#L305:82 (onBaseConfigurationChanged)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/configuration/node/configuration.ts#L305:82 (onBaseConfigurationChanged))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />

**Comment by aeschli** [comment] 2017-08-16 07:14
duplicate of #32385

**Closed by aeschli** 2017-08-16 07:14 UTC
Labels: error-telemetry
