### ISSUE TITLE
Hover doesn't show anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#200315] opened 2023-12-08 08:31 UTC
* type a word
* have a squiggle
* the hover doesn't show

https://github.com/microsoft/vscode/assets/5047891/2d7d71f6-4999-4c43-8596-72338ec47a2f

```
Version: 1.86.0-insider
Commit: ab0520decb7284b2b2a9bbe3ababea57ac83c86b
Date: 2023-12-08T01:25:06.391Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.1.0
```

**Comment by gjsjohnmurray** [comment] 2023-12-08 08:43
Is this a duplicate of #200283?

**Closed** 2023-12-08 14:46 UTC
Labels: important, editor-hover
