### ISSUE TITLE
One esc shuold close breadcrumb tree

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54742] opened 2018-07-20 15:49 UTC
Currently it takes 3 escape kayes to close the breadcrumb tree.
IMHO there is no value in the first 2 escapes moving focus. The first one should just close the breadcrumb tree.

**Comment by jrieken** [comment] 2018-07-25 09:13
/duplicate of https://github.com/Microsoft/vscode/issues/53950

**Closed** 2018-07-25 09:13 UTC
Labels: *duplicate, breadcrumbs, bug
