### ISSUE TITLE
Webview badges provided by an extension are not shown until the webview has been opened by the user

### ISSUE THREAD

**Issue by lgrammel** [microsoft/vscode#164974] opened 2022-10-29 13:11 UTC
Does this issue occur when all extensions are disabled?: Not relevant

- VS Code Version: 1.72.2
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

1. Write an extension that provides badges on a Webview (e.g. a static badge with a count > 0)
2. Add view to a custom view container (in the extension setup, package.json)
3. Start VS Code with that custom view container being hidden.
4. The badge is not shown. Expected: the badge with a count should be shown on the container to indicate relevant counts to the user (that might lead to the user opening the actual view).

The underlying problem seems to be that Webview gets activated when they are first shown (via `resolveWebviewView`) and that the badge API is tied to `WebviewView`. This means that the user needs to activate the view at least once in order to show badges. Ideally an extension would be able to calculate and indicate badges even when `resolveWebviewView` has not been called yet.

**Comment by gjsjohnmurray** [comment] 2022-10-29 15:06
What activation events does your extension subscribe to? Have you verified that your activate method has already been called at the point you are looking for the badge on its activity bar icon?

**Comment by lgrammel** [comment] 2022-10-29 15:08
Yes, the extension has been activated.

**Comment by smeijer** [comment] 2022-11-09 12:47
Same problem, the extension is activated, but the `resolveWebviewView` hasn't been called yet. Making it impossible to assign anything to `webview.badge`.

**Comment by mjbvz** [comment] 2022-11-14 22:08
Duplicate of #146330

**Closed by mjbvz** 2022-11-14 22:08 UTC
