### ISSUE TITLE
Delete and Enter do not work

### ISSUE THREAD

**Issue by IshiKura-a** [microsoft/vscode#100252] opened 2020-06-16 02:55 UTC
Issue Type: <b>Bug</b>

When editing a md file, I type in |$1-$9| to form a tuple of a table. Then I cannot delete and enter to edit the md file. But other keys still work .

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
code-gnu-global|aus|0.2.2
markdown-extension-pack|bat|0.6.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.5.1
markdown-preview-github-styles|bie|0.1.6
excel-to-markdown-table|csh|1.2.2
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.36.0
vscode-drawio|eig|1.0.3
code-runner|for|0.10.0
vscode-pull-request-github|Git|0.17.0
mdmath|goe|2.5.1
path-autocomplete|ion|1.13.6
kite|kit|0.117.0
markdown-shortcuts|mdi|0.12.0
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.5.86806
remote-wsl|ms-|0.44.3
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2302
material-icon-theme|PKi|4.1.0
markdown-preview-enhanced|shd|0.5.12
vscode-markdown-paste-image|tel|0.12.3
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.0.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2020-06-16 05:45
Please run the command to reload with all extensions disabled. If the problem is fixed, do a bisect of your 27 extensions to find the culprit.

**Comment by mjbvz** [comment] 2020-06-23 22:06
Closing as more information is needed to investigate

From the description it sounds like this is caused by an extension

**Closed by mjbvz** 2020-06-23 22:06 UTC
Labels: needs more info
