### ISSUE TITLE
Save Workspace Dialoge does not have focus on Ubunt-Linux

### ISSUE THREAD

**Issue by abdollahkahne** [microsoft/vscode#184038] opened 2023-06-01 09:43 UTC
Type: <b>Bug</b>

When I open a folder and try to save it as workspace using Save As WorkSpace from File (in top menu), It open the dialog but it does not have focus by default and I should click on it myself to make it active dialog and then save the workspace. 

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 5.15.0-73-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz (4 x 2181)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.64GB (1.63GB free)|
|Process Argv|--unity-launch --crash-reporter-id fc1c42ee-dee6-4911-8cbf-68c19b6d4fc8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
vscode-resx-editor|Dom|0.0.5
prettier-vscode|esb|9.13.0
rest-client|hum|0.25.1
sharppad|jma|1.1.0
docomment|k--|1.0.0
csharpextensions|kre|1.7.3
razor-switcher|Len|1.0.0
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
test-adapter-converter|ms-|0.1.7
markdown-preview-enhanced|shd|0.6.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-06-01 10:38
/duplicate of https://github.com/microsoft/vscode/issues/146422

**Closed** 2023-06-01 10:38 UTC
Labels: *duplicate
