### ISSUE TITLE
Icons missing in remote wsl in windows

### ISSUE THREAD

**Issue by sheikalthaf** [microsoft/vscode#79353] opened 2019-08-17 11:29 UTC
- VSCode Version: 1.37.1
- OS Version: windows 10

Icons are missing in wsl mode.

![image](https://user-images.githubusercontent.com/22526247/63211066-fe804480-c10f-11e9-8bd2-e0dbd99f6de9.png)

Does this issue occur when all extensions are disabled?: Yes/No

It is related to the Remote - WSL extension

**Comment by gjsjohnmurray** [comment] 2019-08-17 12:18
/duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed** 2019-08-17 12:19 UTC
Labels: *duplicate, new release
