### ISSUE TITLE
Organize Import removes metaReducer 

### ISSUE THREAD

**Issue by daBishMan** [Microsoft/vscode#48166] opened 2018-04-19 00:04 UTC
Issue Type: <b>Bug</b>

I have the following import 
import {  metaReducers } from './state';

and I am adding to the imports array like
  StoreModule.forRoot(appReducers, { metaReducers }),

But when I run Organize Imports it removes the metar reducers import

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.86GB (10.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
bracket-pair-colorizer|Coe|1.0.37
gitlens|eam|8.2.1
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
debugger-for-chrome|msj|4.3.0
vscode-icons|rob|7.22.0
code-settings-sync|Sha|2.9.0
code-spell-checker|str|1.6.7
move-ts|str|1.11.3
vscode-todo-highlight|way|0.5.12

</details>

**Comment by mjbvz** [comment] 2018-04-19 05:52
Duplicate of #47531

**Closed by mjbvz** 2018-04-19 05:52 UTC
Labels: javascript
