### ISSUE TITLE
Windows file dialogs don't scale on mixed DPI setups

### ISSUE THREAD

**Issue by parkovski** [microsoft/vscode#38976] opened 2017-11-22 19:01 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
jupyter|don|1.1.4
pgsql|dou|0.0.8
vsc-material-theme|Equ|1.1.2
file-icons|fil|1.0.7
referenceshelper|gay|0.2.1
base16-generator|gol|1.3.0
language-julia|jul|0.8.1
DocFX|ms-|0.1.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-code-outline|pat|0.0.12
material-icon-theme|PKi|3.0.0
vscode-yaml|red|0.0.6
vscode-icons|rob|7.18.1
rust|rus|0.3.2
ayu|tea|0.10.0
unity-debug|Uni|1.2.1
vscode-lldb|vad|0.7.1
vim|vsc|0.10.5

(28 theme extensions excluded)

---

Steps to Reproduce:

1. Set up two monitors with different DPIs (mine is an SP4 and a standard DPI monitor set as the primary).
2. Do any action that brings up a native folder dialog on the non-primary monitor (open folder, add workspace folder, etc).
3. On my setup, with the standard DPI primary monitor, the folder dialogs and tooltips are tiny on the HiDPI Surface Pro screen.

Reproduces without extensions: Yes

**Comment by the-ress** [comment] 2017-12-06 15:51
Chromium issue for the toolltips: [#624992](https://bugs.chromium.org/p/chromium/issues/detail?id=624992)

**Comment by burtonrodman** [comment] 2018-04-16 18:34
+1

Surface Pro 4 @ 2736x1824, 175%, primary
(2) Dell 23" @ 1920x1080, 125%

Open Folder Dialog on either Dell displays with very large font size compared to main VS Code window.

**Comment by PoulChapman** [comment] 2018-08-01 16:30
+1
Surface Book 2 @ recommended 3240 x 2160 and recommended 100% scale
Surface dock to two Dell U2717D @ recommended 2560 x 1440 and recommended 100% scale

Repro
1. While laptop is undocked, open up VS Code.
2. Dock the laptop
3. Do a File Save As
Result: Fonts in File Save Dialog on external displays are very large compared to VS Code 

Non-repro:
1. While laptop is docked open up VS Code
2. Do a File Save As
Result: Dialog fonts are same expected size compared with VS Code.

Repro:
1. While laptop is docked, open up VS Code
2. Undock the laptop
3. Do a file save as
Result: File Save Dialog is very teensy compared to VS Code.

Non-repro
1. While laptop is docked, open up VS Code
2. Undock the laptop
3. Open up second instance of VS Code
4. Dock the laptop again
5. Do file save as in *both* of the two instances
Result: Instance #1 has expected File Save dialog. Instance #2 also has expected dialog size even though it was opened while undocked.

**Comment by valkum** [comment] 2019-02-13 15:57
> Chromium issue for the toolltips: [#624992](https://bugs.chromium.org/p/chromium/issues/detail?id=624992)

This seems to be fixed now in chromium. Any plans to fix this in VS Code now?

**Comment by ericrboidi** [comment] 2019-02-15 20:34
+1, also on scrollbars!

**Comment by PaluMacil** [comment] 2019-03-12 05:53
Looks like we're currently on Chrome 66 with VS Code 1.32.2, so the pain continues for computers like the Surface Book.

**Comment by 2coder** [comment] 2019-08-26 10:00
It's August 26th, 2019 and this is still an issue.

**Comment by bpasero** [comment] 2019-10-08 07:25
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Closed** 2019-10-15 06:37 UTC
Labels: electron, needs more info, upstream
