### ISSUE TITLE
Extension published, tested, uploaded, refuses to install - "not found".

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#12497] opened 2016-09-23 06:31 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 10

I wrote a simple extension today and published it for use. 1.0.0 apparently published successfully and appeared on the marketplace and in the extensions list, but attempts to install it failed, as per this issue. I then wondered if the publish had silently failed somehow, so I published a minor 1.0.1 update, and that seemed to work. After I used it for a few minutes, I found a minor issue that I wrote a small fix for, and then published a 1.0.2 update, and though it appeared in the marketplace as it should, I was unable to update from 1.0.1. After I restarted vs code, the extension failed to load at all and I discovered that the extension folder had only a manifest file and none of the other files in the extension package. I tried then installing it from the command line and got an HTTP 500 error.

I then tried unpublishing and republishing, to no avail. I also tried updating the version to 1.0.3 and though the publish appeared to complete successfully, VS Code refuses to download and install it locally. I have verified with a friend who lives in different country and uses a different OS, and he is experiencing the same issue.

Steps to Reproduce:

1. Verify that the extension exists in the marketplace: https://marketplace.visualstudio.com/items?itemName=NathanRidley.autotrim
2. Try to install it in vs code ("autotrim")
3. Error: "extension not found"
4. Try installing from command line
5. "Extension 'NathanRidley.autotrim' not found."

![image](https://cloud.githubusercontent.com/assets/298883/18776079/126ca270-81aa-11e6-8100-ba6db800cf78.png)

![image](https://cloud.githubusercontent.com/assets/298883/18776179/d0ca7dc8-81aa-11e6-907a-dff7233dd266.png)

![image](https://cloud.githubusercontent.com/assets/298883/18776189/e52d2fcc-81aa-11e6-990b-f01070321626.png)

![image](https://cloud.githubusercontent.com/assets/298883/18776199/fb44c0ae-81aa-11e6-9250-58260f165f78.png)

**Comment by joaomoreno** [comment] 2016-09-23 06:35
Very likely duplicate of #12011

**Comment by joaomoreno** [comment] 2016-09-23 06:38
cc @modigrv @hamenon

**Comment by axefrog** [comment] 2016-09-23 06:41
Update: it just installed, finally. Server issue? CDN propagation? If the latter, might be worth factoring this into documentation or error messages to avoid developer confusion/frustration.

**Comment by mrmlnc** [comment] 2016-09-23 06:53
IMHO, timeout. Yesterday was the same. Previously, the extension was not displayed in the list of extensions until the expiration of a period of time. Now extensions appear immediately.

**Comment by joaomoreno** [comment] 2016-09-23 07:05
Great to know! I'm also positive that this is due to CDN propagation lag. I'll close it as a duplicate of #12011.

**Closed by joaomoreno** 2016-09-23 07:05 UTC
Labels: bug, marketplace
