### ISSUE TITLE
Displaying annoying info bar every time i save the .ts file

### ISSUE THREAD

**Issue by uma5b3** [Microsoft/vscode#6351] opened 2016-05-13 13:51 UTC
- VSCode Version: 1.1.0
- OS Version: Windows 10

Steps to Reproduce:

1. showing this info : Sorry, this language is not supported. Only support Javascript, CSS and HTML
 every time i save file *.ts

**Comment by umasgn** [comment] 2016-05-13 13:52
same Issue.

**Comment by bpasero** [comment] 2016-05-13 15:17
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-05-18 05:13
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-05-18 05:13 UTC
Labels: needs more info
