### ISSUE TITLE
Go to defination very very slow to to response in ver 1.33

### ISSUE THREAD

**Issue by hailuabk** [Microsoft/vscode#71780] opened 2019-04-05 09:31 UTC
Issue Type: Bug

[Window Title]
Go to defination very very slow to to response in ver 1.33

[Main Instruction]
Visual Studio Code

When I press ctrl + F12 (ctrl + click) it loading and very very slow go to defination
I tried to disabled all extensions but it still very very slow.
For the same source code, I used version 1.32.3, it worked well.

Please let me know, how to fix it?
Thank you!

Version: 1.33.0 (user setup)
Date: 2019-04-04T15:14:28.026Z
OS: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment] 2019-04-05 14:29
/duplicate of https://github.com/Microsoft/vscode/issues/71779

**Closed** 2019-04-05 14:29 UTC
Labels: *duplicate
