### ISSUE TITLE
Allow storing settings outside of working directory

### ISSUE THREAD

**Issue by remcohaszing** [Microsoft/vscode#56148] opened 2018-08-10 12:49 UTC
I use git for version control. I regularly type `git clean -xdf` from muscle memory, so I can work in a pristine environment, for example when switching branches.

Often I totally forget about my *.vscode* directory, so I will need to restore them manually. Of course it is possible to use workspaces instead, but it’s so convenient to just use `code .` from the terminal. It would be a shame to give this up.

My idea is to offer a different location for these configurations, which will be loaded when a directory is loaded, like *.vscode*, but outside of the version control.

Some potential locations:

- *.git/vscode*
- *$XDG_CONFIG_HOME/Code/Projects/${dirname}*

**Comment by joaomoreno** [comment] 2018-08-10 13:38
Why don't you check in the `.vscode` to your repository? Or set the settings in your user settings file?

**Comment by remcohaszing** [comment] 2018-08-10 13:49
Editor specific files don’t belong in version control. A code base should be editor agnostic.

Some settings might be related to just one project, such as debugging configurations.

**Comment by joaomoreno** [comment] 2018-08-10 14:39
You seem to have a pickle then, don't know anyone else struggling with this issue. I suggest putting the settings somewhere in your code and make a bash alias/script which simply symlinks it to `$PWD/.vscode/settings.json`, so you can always restore them after `git clean`.

**Comment by joaomoreno** [comment] 2018-08-16 14:01
@bpasero Do we have a dupe of this?

**Comment by bpasero** [comment] 2018-08-16 14:36
@sandy081 might know. The best is to create a workspace file and store settings in there.

**Comment by sandy081** [comment] 2018-08-17 09:09
https://github.com/Microsoft/vscode/issues/40233

**Comment by remcohaszing** [comment] 2018-08-17 12:13
@bpasero Creating a workspace file is a workaround, but that does mean one would need to run `code path/to/workspace.code-workspace` instead of `code path/to/project`, which in practice is as simple as `code .` 99% of the time.

A solution could be to resolve a matching workspace file when `code path/to/project`, although that might cause other issues when this behaviour is undesired.

@sandy081 This is not a duplicate of #40233.

That issue is about committing partial VSCode configuration.

This issue is about moving project configuration outside of the git tracked files.

Actually, the solution from the other issue still suffers from the problem described in this issue.

**Closed** 2018-08-20 08:25 UTC
Labels: *duplicate, needs more info
