### ISSUE TITLE
The default Typescript build task v2.0.0 does not work with the bash-based integrated terminal

### ISSUE THREAD

**Issue by dmitriyrepin** [Microsoft/vscode#40907] opened 2017-12-28 16:18 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 7 Enterprise

Steps to Reproduce:

1. **Set the integrated terminal to use the bash shell** (as recommended here https://code.visualstudio.com/docs/editor/integrated-terminal):
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

2. **Define a v 2.0.0 build task** 
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "problemMatcher": [
        "$tsc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "silent",
        "panel": "dedicated"
      }
    }
  ]
}

3. **Try to compile and observe an error**:
> Executing task: e:\_Dev\_Prototypes\2017_WEB\gika-web\server\node_modules\.bin\tsc.cmd -p "e:\_Dev\_Prototypes\2017_WEB\gika-web\server\tsconfig.json" <
/usr/bin/bash: e:_Dev_Prototypes2017_WEBgika-webservernode_modules.bintsc.cmd: command not found
The terminal process terminated with exit code: 127
Terminal will be reused by tasks, press any key to close it.

4. **Switch to the PowerShell-based terminal**
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"

5. **Everything works correctly**:
> Executing task: e:\_Dev\_Prototypes\2017_WEB\gika-web\server\node_modules\.bin\tsc.cmd -p "e:\_Dev\_Prototypes\2017_WEB\gika-web\server\tsconfig.json" <
Terminal will be reused by tasks, press any key to close it.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment] 2018-01-08 08:56
This is a known problem, The reason is that when running under Windows VS Code assumes windows slashes as drive letters and not WSL / git bash drive layouts and back slashes.

**Comment by arthurwhite** [comment] 2018-03-14 00:45
@dbaeumer, I'm on macOS and get the same error since yesterday, in every project.
The buit-in task runner just doesn't work anymore.

And the only thing I remember doing is to update VS Code to 1.22.0-insider.

**Comment by dbaeumer** [comment] 2018-03-14 09:40
@arthurwhite I broke that in the insider. Sorry for that. Got fixed for todays.

**Comment by Zate** [comment] 2018-03-25 17:07
Just a note, I got around this by creating a custom task with what I needed and setting it as my default build task.  Not 100% sure this is correct (learning typescript) but seems to work ok so far.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "tsb",
            "type": "shell",
            "command": "tsc -p tsconfig.json",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "panel": "new"
            }
        }
    ]
}
```

**Comment by webia1** [comment] 2018-05-08 09:25
No, it does not work with git bash :/
See also here: https://github.com/Microsoft/vscode/issues/38178

**Comment by alexr00** [comment] 2018-12-21 14:09
Duplicate of #35593

**Closed** 2018-12-21 14:10 UTC
Labels: *duplicate, WSL, feature-request, tasks
