### ISSUE TITLE
Theme not working with the latest update on 24th November 2019

### ISSUE THREAD

**Issue by Keerttik** [microsoft/vscode#85524] opened 2019-11-25 08:37 UTC
With the latest update in VS code on 24th November the themes are not working. I had one dark Pro theme installed and after the update it say "Cannot read property 'id' of undefined " .

**Comment by egamma** [comment] 2019-11-25 10:11
Duplicate of https://github.com/microsoft/vscode/issues/82610

**Closed** 2019-11-25 10:12 UTC
Labels: needs more info
