### ISSUE TITLE
vscode.window.showTextDocument loads file in editor but Thenable calls onrejected when loading multiple files

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#145969] opened 2022-03-24 12:08 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

In my extension FileGroup a user reported an issue: rioj7/fileGroup#6 where the files get loaded in editors but he gets error messages for each file with the text: `Error: Could NOT open editor for "file:///d%3A/dir1/dir2/file.ext".`

All files exist but still a `Could NOT open editor for ` error message is generated.

* If he wants to load 1 file the error message does not happen
* If he wants to load 2 files the error messages **sometimes does NOT** happen
* If he wants to load 3+ files the error messages (most likely) always happen

A slimmed down version of the `extention.js` (before the workaround) is:

```
const vscode = require('vscode');

function activate(context) {
  context.subscriptions.push(vscode.commands.registerCommand('fileGroup.openGroup', async (args) => {
    let column = vscode.ViewColumn.Active;
    let group = { files: [
      "d:\\dir1\\dir2\file1.txt",
      "d:\\dir1\\dir2\file2.txt",
    ]};
    const openFile = filePath => new Promise((resolve, reject) => {
      vscode.window.showTextDocument(vscode.Uri.file(filePath), { preview: false, viewColumn: column }).then( editor => { resolve(true); },
        error => { vscode.window.showErrorMessage(String(error)); reject(error); });
    });
    await Promise.all(group.files.map(openFile));
  }) );
};

function deactivate() {}

module.exports = {
  activate,
  deactivate
}
```

I have wrapped `vscode.window.showTextDocument` in a `Promise` because I do not expect that a `Thenable` will work with `Promise.all()`.

The question is why is the `onrejected` callback of `.then(onfulfilled, onrejeted)` called when the file is loaded in an editor. It only happens when multiple file load Promises are created and waited for. If the function `vscode.window.showTextDocument` performs correct the `.then()` should call the `onfulfilled` callback (no error message).

Can there be some "race" condition internally where multiple calls to `vscode.window.showTextDocument` manipulate some global data that is not guarded by some "mutex"? Because with 2 files it sometimes happens.

The workaround is to replace

```
    await Promise.all(group.files.map(openFile));
```

with serial loading of the files

```
    for (const file of group.files) { await openFile(file).catch( () => {} ); }
```

**Comment by jrieken** [comment] 2022-03-24 16:02
related/dupe of https://github.com/microsoft/vscode/issues/98871

> It only happens when multiple file load Promises are created and waited for. If the function vscode.window.showTextDocument performs correct the .then() should call the onfulfilled callback (no error message).

You are asking us to show different document with the same editor in parallel, the first might open but then the second or third request "overrides" it.  The `showTextDocument`-function returns an editor but in the meantime the editor is used for another document, not the one you have asked for and therefore we fail

**Closed by jrieken** 2022-03-24 16:02 UTC

**Comment by rioj7** [comment] 2022-03-24 19:49
@jrieken None of the `showTextDocument` calls fails, all the requested files are loaded (have a tab in the requested column). If one would fail not all files would be loaded and an error message for the file(s) not loaded. Not an error message for all files.

**Comment by jrieken** [comment] 2022-03-25 07:17
Two important things: show is not the same as loading, a tab is not the same as an editor. Yes, the files can be loaded, yes tab can be shown, but only one editor is created. Tab are just buttons and per tab group only one editor exists. So, this fails because of three _show_ requests only one successes (because only one editor shows)
