### ISSUE TITLE
Not Expand/Collapsible  multi line comments

### ISSUE THREAD

**Issue by shaishab** [Microsoft/vscode#57477] opened 2018-08-29 07:29 UTC
Currently unable to expand or collapse for multiline comments (for documentation). It would be better if we could that. 

![image](https://user-images.githubusercontent.com/3139652/44772337-60f2d480-ab8f-11e8-86b2-0005180c77fd.png)

**Comment by mjbvz** [comment] 2018-09-04 18:54
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Closed by mjbvz** 2018-09-04 18:54 UTC
Labels: editor, editor-folding
