### ISSUE TITLE
Terminal search improve

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#144371] opened 2022-03-04 07:11 UTC
Vscode terminal use 'text selection' to emulate 'search highlight'. This fact is the reason to:
1. Search highlight will always show at most one result even if there are many results in terminal text.
2. After a search, once I focused on the terminal cursor, the highlighted search result is no longer highlighted.
3. (the direct proof) The only way to change terminal search highlight color is to change this setting: "terminal.selectionBackground". As you can see, this setting is intend to control the selection color instead of search highlight color.

I want vscode to implement the real search highlight, just like what iTerm2 do:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/10379994/156716427-32a9df2b-9d24-4b63-8055-26d43633b916.png">

**Comment by yume-chan** [comment] 2022-03-04 08:12
Duplicate of #134790

**Closed** 2022-03-04 16:38 UTC
Labels: *duplicate
