### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.darwin eat cpu on mac

### ISSUE THREAD

**Issue by sunnyawake5** [Microsoft/vscode#50433] opened 2018-05-25 06:18 UTC
vscode: 1.23.1
macos: 10.13.4

**Comment by weinand** [comment] 2018-05-25 08:54
duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2036

**Closed by weinand** 2018-05-25 08:54 UTC
Labels: extensions

**Comment by sean-mcmanus** [comment] 2018-05-26 00:19
@sunnyawake5 We've found/fixed a deadlock that can lead to infinite CPU usage (i.e. "livelock"): https://github.com/Microsoft/vscode-cpptools/issues/2043 . We'll try to release an update soon.

**Comment by duzhen16** [comment] 2018-06-20 11:41
@sean-mcmanus This extension is very nice to use except causing high CPU usage, could you please fix this bug as fast as you can ? Thank you

**Comment by weinand** [comment] 2018-06-20 13:13
@duzhen16 you've just added a comment meant for the cpp extension in the wrong place.
This is the VS Code repository. Your comment really should go to https://github.com/Microsoft/vscode-cpptools/issues/2043

**Comment by sean-mcmanus** [comment] 2018-06-20 18:48
@duzhen16 The bug I mentioned was fixed with 0.17.4. If you're experiencing other issues still, please file an issue with repro details at https://github.com/Microsoft/vscode-cpptools/issues .
