### ISSUE TITLE
Two icons shown in automation terminal

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#138367] opened 2021-12-02 20:51 UTC
Testing #138078

I didn't see this yesterday so it feels like a new issue from recent changes? Using the following the setting:

```json
  "terminal.integrated.automationProfile.osx": {
    "path": "/opt/homebrew/bin/zsh",
    "icon": "zap",
    "color": "terminal.ansiBlue"
  },
```
<img width="197" alt="CleanShot 2021-12-02 at 12 47 58@2x" src="https://user-images.githubusercontent.com/35271042/144500603-47b0cfd0-e434-47da-81fa-e9e2024869e2.png">

Then when i remove the setting I stills see two icons:

<img width="197" alt="CleanShot 2021-12-02 at 12 49 28@2x" src="https://user-images.githubusercontent.com/35271042/144500771-7ed3948a-a833-475c-996d-2c41837ab8d3.png">

**Comment by alexr00** [comment] 2021-12-03 10:15
@misolori I can't repro this, does it persist across reload?

@Tyriar in case you have any ideas. The only change I made yesterday was a schema change.

**Comment by misolori** [comment] 2021-12-03 20:46
I can't seem to repro as well, must've been a weird bug.

**Comment by Tyriar** [comment] 2021-12-03 21:34
@meganrogge

**Comment by meganrogge** [comment] 2021-12-04 01:42
I can't reproduce this either and haven't made changes in this area in the past month.

**Comment by Tyriar** [comment] 2021-12-06 14:11
I can't repro either. Not sure how this could happen based on the code as we only use `iconId` once in all cases:

https://github.com/microsoft/vscode/blob/6df426e6702962959978bbf670af6ba4d5e57d80/src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts#L306-L325

@misolori if you see this again can you inspect the DOM and expand the elements related to that terminal tab?

Taking ownership of the issue as it's related to terminal UI and closing as not reproducible.

**Closed by Tyriar** 2021-12-06 14:11 UTC
Labels: bug, tasks
