### ISSUE TITLE
The limit of Selection

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#33589] opened 2017-08-31 12:06 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vsc-material-theme|Equ|1.0.2
Go|luk|0.6.63
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. a big file (>2000 lines)
2. select some words
3. when the selections are larger than 1000, only the first 1000 can be highlight while others stay unchanged.
4. the scroll bar are also consistent with the selection, cannot highlight more selections.
![selection](https://user-images.githubusercontent.com/10704251/29922256-6b47b0ac-8e87-11e7-98b4-01095ba23b39.png)

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment] 2017-09-28 10:01
Duplicate of #1110

**Closed by alexandrudima** 2017-09-28 10:01 UTC
Labels: editor, editor-1000-limit, editor-contrib
