### ISSUE TITLE
`ERR [lifecycle] Long running operations during shutdown are unsupported in the web (id: autoStoreWorkingChanges)`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#171716] opened 2023-01-19 11:45 UTC
Seeing that on window reload in web. Note that in web we cannot have long running operations on reload / shutdown.

**Comment by joyceerhl** [comment] 2023-02-03 23:11
Duplicate of https://github.com/microsoft/vscode/issues/161296

**Closed by joyceerhl** 2023-02-03 23:11 UTC
Labels: web
