### ISSUE TITLE
Add a tagbar to VSCode

### ISSUE THREAD

**Issue by drinktee** [Microsoft/vscode#22124] opened 2017-03-07 06:48 UTC
In VIM there is a tagbar like this.

![tagbar](https://cloud.githubusercontent.com/assets/7619792/23644969/c6d776a6-0344-11e7-8d9a-dc9490d8e123.jpg)

In vscode I found that I can see the same thing by 'command +p  and @'.
![image](https://cloud.githubusercontent.com/assets/7619792/23645032/11096e0a-0345-11e7-8d45-e990779bacbc.png)

How about create a tagbar like vim?

**Comment by rmunn** [comment] 2017-03-07 07:03
Looks like this is a duplicate of #5605.

**Comment by ramya-rao-a** [comment] 2017-03-07 18:43
Thanks for finding the duplicate @rmunn 
@drinktee Please follow the discussion at #5605 and add your inputs there.

**Closed by ramya-rao-a** 2017-03-07 18:43 UTC
