### ISSUE TITLE
Got stuck in `Tab moves focus` mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9766] opened 2016-07-26 10:15 UTC
Steps to Reproduce:

1. Have a 2 pane layout.
2. Hit <kbd>Cmd ,</kbd> to open user settings.
3. Hit <kbd>Cmd 1</kbd> to focus the first pane.
4. Use quick open to switch to an editable file.
5. Hit <kbd>Cmd 2</kbd> to focus the user settings and make any **valid** change there.
6. Hit <kbd>Cmd 1</kbd> to focus the first pane.

<kbd>Tab</kbd> will now focus away from the editor instead of inserting a `TAB`.

**Comment by jrieken** [comment] 2016-07-26 12:01
let's treat this as dupe of #9705

**Closed by jrieken** 2016-07-26 12:01 UTC
Labels: bug, duplicate
