### ISSUE TITLE
No DST in Brazil

### ISSUE THREAD

**Issue by jvvasquesn** [microsoft/vscode#90516] opened 2020-02-12 11:17 UTC
Issue Type: <b>Bug</b>

The government of Brazil has announced that there will be no DST in Brazil

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2766)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.73GB (0.26GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
activitusbar|Gru|0.0.25
todo-tree|Gru|0.0.167
svn-scm|joh|2.7.0
tds-monitor|TOT|0.0.7
tds-vscode|TOT|0.3.23
vscode-icons|vsc|9.7.0

</details>

**Comment by IllusionMH** [comment] 2020-02-12 13:43
Could you provide more details how it affects VS Code editor?

**Comment by gusbemacbe** [comment] 2020-02-12 17:28
@IllusionMH 

I am also Brazilian. It means that your text editor still uses the traditional UTC time, and has to adapt to Brazil's time using the DST without summer adaptation. 

Under our government, we will have no summer adaptation.

**Comment by IllusionMH** [comment] 2020-02-12 17:46
Just in case - I'm not a developer.
Do you have an example where time is displayed in VS Code is or would be wrong?

Only case I can see Gitlens extension and new experimental Timeline (editor itself).

However I have big doubts that VS Code does some date/time conversions other than available in Chromium.

**Comment by gusbemacbe** [comment] 2020-02-12 18:01
As VSCode is written in Electron, look: https://github.com/electron/electron/issues/20998

**Comment by IllusionMH** [comment] 2020-02-12 18:53
Thanks for the link. That what I implied in my previous comment, but had to be more clear - it is external issue to the editor itself and should be fixed in Chrome, Node, or Electron.

However in linked issue notes that 
> Last Known Working Electron version:
> 7 and up works

and confirmed by the comment https://github.com/electron/electron/issues/20998#issuecomment-551208651
> Also the above ICU change is minimal and only needed for 6-1-x branch

February insiders build has Electron v7.1.11 so it shouldn't be a problem after 1.43 will be released in early March. 

@deepak1556 is there anything needed to handle DST removal after 1.43 release?

**Comment by gusbemacbe** [comment] 2020-02-12 19:06
@IllusionMH 

I got, @jvvasquesn is using the current VSCode version – 1.42. I am using Insiders – the version 1.43, and installed the "Date & Time" extension to test and the time seems OK:

![image](https://user-images.githubusercontent.com/2257024/74368002-8f7b6400-4db1-11ea-8abb-612eda1a0c51.png)

**Comment by deepak1556** [comment] 2020-02-13 00:21
@IllusionMH the fix should propagate automatically, there is no change required on the app end. And yup to reiterate this is fixed in electron 7 and above. Electron won't be fixing it for earlier release lines than 7 due to the patch required in  ICU.

**Comment by deepak1556** [comment] 2020-02-26 10:57
Closing issue for milestone, should be available in stable soon.

**Closed by deepak1556** 2020-02-26 10:57 UTC
Labels: bug, electron-6-update, fixed-in-electron-7, upstream-issue-linked
