### ISSUE TITLE
Workspace folder collapsing when opening file in multi-root workspace

### ISSUE THREAD

**Issue by boy-vd** [microsoft/vscode#108427] opened 2020-10-09 23:42 UTC
- VSCode Version: 1.50.0
- OS Version: 10.15.6

Steps to Reproduce:

1. Choose some directory 'A' on your file system that has some files in it and also a child directory 'B' (the actual names are irrelevant, I just use 'A' and 'B' for reference),
2. Create a multi-root workspace and add 'A' and 'B' as separate workspace folders
3. Exclude folder 'B' in the workspace folder 'A' by with the following configuration in a `settings.json` in a `.vscode` folder in the workspace folder 'A':

```
{
    "files.exclude": {
        "**/B": true,
    },
}
```

4. In workspace folder 'B', open a file by clicking on it in the Explorer
5. The file opens as expected, but: witness the workspace folder 'B' collapsing
6. Note that workspace folder 'B' will only collapse if you click on a file that is not open already (so not when clicking on an already open file in workspace folder 'B' to switch to that particular file)

Obviously, the culprit is the specific configuration of workspace folder 'A' that excludes folder 'B' from it. But although I do agree that this probably isn't the most common configuration, I don't think it's too outlandish to consider it irrelevant to fix. If you're using a multi-root workspace configuration where one of the workspace folders is a child (e.g., 'B') of another (e.g., 'A'), I believe it's reasonable to not want to have a duplicate of this folder ('B') in your overall workspace.

So, on my file system I have:

```
+---A
    |
    +---B
```

And in VSCode I want to represent this as:

```
+---A
|
+---B
```

Without 'B' collapsing if I open a file in it ;-).

PS: When opening a file in workspace folder 'A', everything is normal and as expected, and the workspace folder doesn't collapse.
PPS: This behavior has been reproduced on Windows 10 as well, but I didn't check which version exactly (it was running VSCode 1.50.0 though).

Does this issue occur when all extensions are disabled? Yes.

**Comment by usatiuk** [comment] 2020-10-12 12:49
This seems to be caused by a feature introduced in commit https://github.com/microsoft/vscode/commit/1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef and that, as far as I understand, `isVisible()` (https://github.com/microsoft/vscode/commit/1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef#diff-18552b0ae82758a2b0227eb483bdc8d8R565) doesn't see the difference between (as in the example) folder B *as a child of A* and folder B *as a workspace folder/root*, so when any child of B is open, `files.exclude` for B is ignored, and it is shown both as *as a child of A* (so `files.exclude` is actually useless in this scenario), and as *as a workspace folder/root*, which also, for whatever reason, collapses

**Comment by isidorn** [comment] 2020-10-20 14:26
As @usatiuk explained this is designed behavior. We will not change this for now, thus closing

**Closed by isidorn** 2020-10-20 14:26 UTC

**Comment by boy-vd** [comment] 2020-10-21 11:54
So If I understand this correctly, it is designed behavior that a setting that is limited in scope to one workspace root, also affects behavior in another workspace root? To me, it seems like this is an unintended side-effect of the behavior that was implemented instead, and thus might warrant a fix.
