### ISSUE TITLE
Notebook: running query does not show any results (web)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104538] opened 2020-08-13 06:30 UTC
Steps to Reproduce:

1. open our `my-work.github.issues` in web
2. run any query

=> 🐛 not result showing up

Works fine in insiders native.

![recording](https://user-images.githubusercontent.com/900690/90101545-2ca65d80-dd3f-11ea-96ca-a4b81ba6c00c.gif)

I am seeing this in devtools:

```
VM10:7 GET https://a62bc1b8-38eb-4214-bd84-57c485de2fbb.vscode-webview-test.com/db40434f562994116e5b21c24015a2e40b2504e6/vscode-resource/vscode-remote//localhost%3A9777/Users/bpasero/.vscode-web/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.39/dist/renderer.js net::ERR_ABORTED 404
```

**Comment by jrieken** [comment] 2020-08-13 08:09
@connor4312 looks like the render doesn't load correctly on the web. Looks like paths are double-joined

**Comment by connor4312** [comment] 2020-08-13 15:17
@jrieken are you hitting this? https://github.com/microsoft/vscode-internalbacklog/issues/1318

**Comment by bpasero** [comment] 2020-08-24 11:58
This still reproduces with today's insider and the linked issues are closed.

**Comment by connor4312** [comment] 2020-08-24 15:06
This works in the playground for me -- are you seeing the same 404 error?

**Comment by bpasero** [comment] 2020-08-24 15:24
@connor4312 can you try running locally? Via `resources/server/web-selfhost.sh`?

**Comment by connor4312** [comment] 2020-08-24 16:06
cc @mattbierner

**Comment by mjbvz** [comment] 2020-08-24 19:03
@connor4312 This seems caused by 24b712d7c201f74a6bd50742f1eb7602f699e640. Other webview resources are loading fine so I think it is notebook specific.

The requesting uri looks like:

```
https://UUID.vscode-webview-test.com/COMMIT/vscode-resource/vscode-remote//localhost%3A9888/Users/matb/.vscode-web-dev/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.41/dist/renderer.js
```

While one from the markdown preview looks like:

```
https://UUID.vscode-webview-test.com/COMMIT/vscode-resource/file///Users/matb/projects/vscode/extensions/markdown-language-features/media/markdown.css
```

The part after `vscode-resource` is supposed to be the uri scheme.  Notice how the markdown resource is using `file` here while the notebook one is using  `vscode-remote`. 

Will keep investigating

**Comment by mjbvz** [comment] 2020-08-24 19:05
The `vscode-remote` part comes from the extension location here: 

https://github.com/microsoft/vscode/blob/24b712d7c201f74a6bd50742f1eb7602f699e640/src/vs/workbench/contrib/notebook/common/notebookOutputRenderer.ts#L34

**Comment by connor4312** [comment] 2020-08-25 15:45
After investigating I think that notebook resource loading never worked in web. It seems like we had shims for webviews loading remote resources when associated with a single extension, but this is not the case for renderers.

I don't have a deep understanding of webview related things, but I learned a lot more and made a commit that fixes it here: https://github.com/microsoft/vscode/commit/41fb3d6e8160a7360c438360a7951f2b371954c7 Let me know if you think this is the right approach.

**Comment by mjbvz** [comment] 2020-08-25 19:19
Thanks for the investigation @connor4312.

https://github.com/microsoft/vscode/commit/02bafd47bb732773b77882b1a15e2f2dd09fa987 seems to have fixed the issue for me? Can someone else please verify this though before I close this out

![Screen Shot 2020-08-25 at 12 19 31 PM](https://user-images.githubusercontent.com/12821956/91217998-421b7000-e6cd-11ea-9702-499b24af974f.png)

**Comment by connor4312** [comment] 2020-08-25 19:51
I'll give it a shot, might have overcomplicated things when debugging :)

**Comment by connor4312** [comment] 2020-08-25 22:49
Yep that works.

**Closed by connor4312** 2020-08-25 22:49 UTC
Labels: bug, important, notebook, web
