### ISSUE TITLE
[python] Replace TextMate for Python syntax highlighting

### ISSUE THREAD

**Issue by nchammas** [Microsoft/vscode#2208] opened 2016-01-24 18:50 UTC
VS Code's syntax highlighting for Python is [broken in a few ways](https://github.com/Microsoft/vscode/issues/1467).

VS Code currently uses [TextMate's Python bundle](https://github.com/textmate/python.tmbundle) for syntax highlighting. The problem is that this project seems to be unmaintained. The last commit was from mid-2014.

We should replace this with a project that is more up-to-date and actively maintained. [PythonImproved](https://github.com/MattDMo/PythonImproved) seems to fit the bill, though I haven't used it yet. I've asked the maintainers of that project about [compatibility with VS Code](https://github.com/MattDMo/PythonImproved/issues/57).

If anyone has other suggestions for a better tokenizer for Python, please speak up.

**Comment by aeschli** [comment] 2016-02-10 09:25
There's also https://github.com/Microsoft/vscode/issues/2867 suggesting to take MagicPython.
Did give this a try? (There's already a MagicPython extension)

**Comment by nchammas** [comment] 2016-02-10 17:39
Just gave it a try. Looks good to me!

**Comment by MattDMo** [comment] 2016-02-22 19:09
I'm the maintainer of Python Improved, and I have no issues at all with your using it to supplement or replace the TextMate syntax definition in VSCode. One issue I've found with Magic Python is that a number of the scopes are rather different than the TM/Sublime Text originals, so switching to that could cause issues with color schemes that aren't compatible with MP. Those of us working on PI with me have tried to maintain compatibility with the original scopes as much as possible (or, at least, as much as makes sense), so it should work with a broader array of color schemes. I've tailored my [Neon Color Scheme](https://github.com/MattDMo/Neon-color-scheme) to work with all the new scopes in PI, in case you want to include that as well.

Let me know what you think, or if I can help in any way. Alternatively, I can add PI and Neon to the VSCode store if you think that would be a better option.

**Comment by nchammas** [comment] 2016-02-22 19:15
Perhaps @aeschli can offer advice on a path to take (I'm just a random user), but I would guess a solid first step would be to make PythonImproved available as a VS Code extension and then take it from there.

**Comment by aeschli** [comment] 2016-02-23 09:44
@MattDMo Thanks Matt for your comment. Yes, making Python Improved available as a VS Code extension would be a great first step so more people can try it out.
Let me know if you need help with the extension. We have a yeoman generator that helps you setting up an extension that contributes a grammar. Check out https://code.visualstudio.com/docs/tools/yocode.
To replace an existing grammar use the same language id ('python') and additionally add 
```json
	"extensionDependencies": [
		"vscode.python"
	]
```
to your `package.json`

**Comment by aeschli** [comment] 2016-04-21 12:16
There has been new work in the [TextMate's Python bundle](https://github.com/textmate/python.tmbundle). So I've updated the grammar to the latest.

I'm still open to update to any other grammar if the community has a clear preference. But then, as said, thanks to the extension model it's possible to add grammars as extensions and each user is free to choose what to use.

**Comment by DonJayamanne** [comment] 2016-06-20 02:56
@MattDMo , have you had any luck in building an extension for VS Code. I'm certain there would plenty of people within the community and the VS Code team willing to help you with this.

**Comment by DonJayamanne** [comment] 2016-07-15 07:22
@MattDMo , @aeschli , I'm am in the process of creating a VS Code extension using the code from  [Python Improved](https://github.com/MattDMo/PythonImproved). 

The issue #2936 doesn't appear in Magic Python, however when using the tmLanguage file from PythonImproved, I can see that the issue still exists.
Issue #7688 doesn't seem to be a non-issue in both Magic Python and Python Improved.
However, #7688 can be replicated when using PythonImproved on TextMate!

Those are the only two issues I could find.
Anyways, I haven't published the extension yet and it can be found [here](https://github.com/DonJayamanne/pythonImproved)

**Comment by 1st1** [comment] 2016-07-28 14:12
@DonJayamanne As a maintainer of MagicPython I'd strongly recommend you to go with it. Simply because we embrace TDD, MP is super stable and we can add new features very quickly. It's also used by GitHub to highlight Python sources. We have 100s of complex automated unittests, something that no other syntax highlighter for any other language does (for tmLanguage format anyways).

Some additional features of MP (I just went through our unittests and checked which one break standard highlighter or PI):

* It parses docstrings differently from string literals, allowing you to highlight them in a different way and making sure raw strings aren't highlighted as regexps.

* Highlights cases like illegal use of literals:
```python
some. True
a = True
```

* Highlights `self` and `cls` for methods:
```python
class F:
    def __init__(self, a, b=1):
        self.a = a
```

* Can highlight type annotations (GH's color schema doesn't support them yet, but try it with MP and Chromodynamics color schema):
```python
x = None # type: List[str, a]
y = None # type: Dict[int, Any] # int
```

* Highlights doctests:
```python
r'''Module docstring

    Some text followed by code sample:
    >>> for a in foo(2, b=1,
    ...                 c=3):
    ...   print(a)
    0
    1
'''
```

* Correctly handles parameter annotations (try that in PythonImproved):
```python
def some_func(a:
                 lambda x=None:
                    {key: val
                        for key, val in
                            (x if x is not None else [])
                    }=42):
```

* Correctly handles invalid line continuations:
```python
1 + \ sdgfsdf
def foo(): pass
```

* Superb support of both old and new style string formatting:
```python
a = 'qqq{0:{width}{base}}www'
a = 'qqq{0:$20}www'
a = 'qqq{0}www'
```

* Unicode is, of course, fully supported (as in PI, I believe):
```python
class Üa(Êa):
    'Œ\nŃ'
    @æaœ
    def ŌÏŒĘ(self, Ú=1):
        print('превед 你好')
        return Ù
    你好 = lambda: 你好
    def 你好(): pass
```

There are much more small, but handy (sometimes obscure) features in MP, but I don't want to list too many examples.

**Comment by 1st1** [comment] 2016-07-28 14:18
Also, MP is already used by >31000 VSCode users: https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython

**Comment by nchammas** [comment] 2016-07-28 14:26
As the person who reported this issue, I can also add that I'm a happy MagicPython user too. :+1:

**Comment by MattDMo** [comment] 2016-07-28 17:53
I have no issues with using MagicPython, if that's the way you want to go. PythonImproved is just a side project in my free time (I'm actually a research scientist in biotech in real life), and honestly I just don't have the time at the moment to support some of the features that MP does already. If there's anything in PI that can be useful, please feel free to grab it (just attribute me in some way). Hopefully I'll eventually get around to releasing PI for VSCode, but work is definitely my top priority at the moment, so I don't know when that will be.

Sorry I can't spend more time on it, but since PI isn't directly related to my primary job functions at work, the company won't support my time spent on an open source project. Please do keep me in the loop, though, and I'll try to answer any concerns that may arise.

**Comment by DonJayamanne** [comment] 2016-08-16 23:48
@aeschli , my plan is to update the Python tmlanguage files (later today) with the ones from MagicPython:
- Will I need to create any test plans? I don't see the need for this? However, a sanity check wouldn't hurt  
- Will I (or someone else) need to update the August iteration plan?

FYI - as this is a simple update to a tmlanguage file, I won't be creating a PR.

**Comment by 1st1** [comment] 2016-08-17 02:07
> FYI - as this is a simple update to a tmlanguage file, I won't be creating a PR.

One quick note just in case: please make sure that the `name` key is set to `Python` (not `MagicPython`) in the replaced tmLanguage.  We'd like to have an option for our users to manually install MagicPython and not have any potential conflicts.

Also, would it be possible to publicly state that VSCode uses MagicPython and to direct highlighter related issues to our tracker?

**Comment by DonJayamanne** [comment] 2016-08-17 02:17
@1st1 
>make sure that the name key is set to Python     

sure thing   
>publicly state that VSCode uses MagicPython

No sure how this would work, any idea how this would work @aeschli? However redirecting highlighter related issues to Magic Python tracker shouldn't be an issue.

**Comment by aeschli** [comment] 2016-08-17 07:45
- Can you point me to the github repo where the magic python grammar file is located? I'll then file  a legal approval request and we can update OSSReadme.json which will add a reference to Magic Python and it's license to our thirdpartynotices file.
- We currently have no mechanism to tell users to directly file issues against to the Magic python repo, but we will move the requests if they are filed against us after verifying it's not a bug in our text-mate parser or theme infrastructure.
- A test plan item would make sense. We should test the grammar with all our built-in themes. Just create a issue that explains what to test and add the 'test-item' label and set milestone to August.
- When updating, also verify the highlighting of the [test file](https://github.com/Microsoft/vscode/blob/master/extensions/python/test/colorize-fixtures/test.py) at update the syntax highlighting tests (run with ./scripts/test-integration, accept changes if you have verified that the new result makes sense).
Feel free to add more syntax highlighting tests.
- I started adding update scripts as to make it easier to update grammar files. Check out
https://github.com/Microsoft/vscode/blob/master/extensions/scss/package.json#L7 as an example. It's invoked with `npm run update-grammar`

**Comment by DonJayamanne** [comment] 2016-08-17 12:45
@aeschli 
- Here's the location:
https://github.com/MagicStack/MagicPython/tree/master/grammars
- Thanks for the tip on automating the update of the grammar files. Will check this out.

**Comment by aeschli** [comment] 2016-08-17 15:02
I initiated the OSSRequest. You can proceed and change the OSSReadme file to
```
// ATTENTION - THIS DIRECTORY CONTAINS THIRD PARTY OPEN SOURCE MATERIALS:
[{
	"name": "MagicStack/MagicPython",
	"version": "0.0.0",
	"license": "MIT",
	"repositoryURL": "https://github.com/MagicStack/MagicPython"
}]
```
Let me know one you committed the changes, then I'll trigger the script that updates the ThirdPartyNotices.

**Comment by DonJayamanne** [comment] 2016-08-18 00:43
@aeschli , I will submit a PR later today. 
With regards to the update-grammar script:  
- Is this something that needs to be run manually or is this part of the build process? If it is manual, then that's fine
  
- The update-grammar script converts the tmLanguage file to json. However looking at existing code, we don't do this for the [Regular Expressions (JavaScript).tmLanguage](https://github.com/Microsoft/vscode/blob/5ca799fd0729cec5e7c30e70022f37bb3cb4b608/extensions/javascript/package.json#L66) file. 
Would the same apply to the python regular expressions tmLanguage file.

I.e. the final result would be as follows (one json and other tmLanguage):
```json
"grammars": [{
			"language": "python",
			"scopeName": "source.python",
			"path": "./syntaxes/Python.tmLanguage.json"
		},{
			"scopeName": "source.regexp.python",
			"path": "./syntaxes/Regular Expressions (Python).tmLanguage"
		}]
```

**Comment by aeschli** [comment] 2016-08-18 07:05
@DonJayamanne Thanks for looking into the grammar update scripts.

It’s a manual step. We want to update at a controlled time (e.g. not right before a release so that we get a chance to receive bug reports in time) and also do some sanity testing before pushing a grammar update. 

I have just started adopting the scripts. I will add the script and migrate from using .json instead of plist/tmLanguage when there is a need to update the grammar.
Care is required as in some grammars we made manual changes, in anticipation of a fix or from a pull request, that I need to port over. So best is to check the commit history of the grammar to see what happened. Ideally such additions always have a test with them, like https://github.com/Microsoft/vscode/blob/master/extensions/javascript/test/colorize-fixtures/test6916.js

Yes, if Regular Expressions (Python).tmLanguage is still in use, then I’d suggest to update it as well.
The script takes multiple parameters if both grammars are from the same repo (see https://github.com/Microsoft/vscode/blob/master/extensions/cpp/package.json#L7).
Otherwise use && to run multiple commands in one script.

**Closed** 2016-08-22 06:40 UTC
Labels: feature-request, languages basic
