### ISSUE TITLE
Recover deleted files

### ISSUE THREAD

**Issue by Mosespimor** [microsoft/vscode#143928] opened 2022-02-24 23:28 UTC
Issue Type: <b>Performance Issue</b>

Good day! l lost my files trying to track by files with git, really frustrating right now. what should be done to recover files back?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.15063
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.71GB free)|
|Process Argv|--crash-reporter-id 858467cb-44d1-4da7-9497-ab904ee8e1db|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	  6040	code main
    0	    10	   848	   crashpad-handler
    0	   130	  1300	   window (USER-INFO - Visual Studio Code)
    1	   152	  1564	   gpu-process
    0	    69	  8212	   shared-process
    0	    32	  8944	     ptyHost
    0	     6	  8628	       winpty-process
    0	     9	 10392	         console-window-host (Windows internal process)
    0	    60	 10564	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    32	 10648	     fileWatcher
    0	    20	  8376	   utility-network-service
    0	    93	 10344	   extensionHost
    0	    96	  8644	     "C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\hp\.vscode\extensions\zenclabs.reactpreview-0.7.1\dist\server\bundle.js --node-ipc --clientProcessId=10344
    0	    30	  9716	     "C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=10344
    0	    26	 10748	     "C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10344
    1	    48	 10664	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (USER-INFO - Visual Studio Code)
|    Folder (USER-INFO): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
zcy-emmet|alf|0.1.9
simple-react-snippets|bur|1.2.6
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
node-snippets|dev|0.1.1
es7-react-js-snippets|dsz|4.4.3
vscode-npm-script|eg2|0.3.24
eventlistener-intellisense|fat|0.0.1
beautify|Hoo|1.5.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
nodejs-repl|los|0.5.15
vscode-docker|ms-|1.20.0
live-server-preview|neg|0.1.4
vscode-for-node-js-development-pack|nod|2.0.1
LiveServer|rit|5.7.4
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
cors-browser|Wsc|1.0.11
emmet-live|yse|1.0.0
reactpreview|zen|0.7.1
js-runner|Zol|3.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by hello-smile6** [comment] 2022-02-24 23:47
Maybe, seems like duplicate of #143195 #139991 (from titles)

**Comment by lszomoru** [comment] 2022-03-01 13:19
@Mosespimor, could you please elaborate on the steps that resulted in you losing your files? Thank you!

**Closed** 2022-03-09 11:27 UTC
Labels: needs more info, git
