### ISSUE TITLE
New keyboard layout support does not handle layouts with different maps for different modifiers

### ISSUE THREAD

**Issue by DanielStolt** [Microsoft/vscode#24383] opened 2017-04-10 00:20 UTC
- VSCode Version: 1.11.1
- OS Version: Mac OS X Seirra 10.12.4 (16E195

I am using a keyboard layout (Swedish Dvorak) which has different key maps depending on modifier. For unmodified, Shift and Option keys, the maps correspond to the Dvorak layout. For Cmd and Ctrl keys, the maps correspond to the QWERTY layout.

This is common with non QWERTY layouts; it is a way to ensure that the user can still operate all the commonly used keyboard shortcuts one-handed, such as those for copy, cut, paste, undo, redo, bold, etc. It is also done because many non-QWERTY users still have QWERTY printed keys on their keyboards, and keyboard shortcuts often require visual orientation rather than pure tactile orientation.

Regardless of the reasons why this is done, it is something that is fully supported by the Mac OS X input model.

In all other Mac applications I have come across (except, coincidentally, for Xamarin and Visual Studio for Mac) this behaves as expected. E.g. in my case pressing the C key on a QWERTY-marked keyboard inputs the letter J as per the Dvorak layout, while pressing Ctrl+C is still processed as Ctrl+C and invokes the copy command.

Starting with version 1.11.1 this is not the case for VS Code. VS Code now seems to completely disregard the modifier map and instead process shortcut key combinations against the letter each key happens to correspond to in the **unmodified** map.

This renders VS Code practically useless for me.

**Comment by alexandrudima** [comment] 2017-04-10 08:14
Duplicate of #23964 . A workaround is presented in the comments - https://github.com/Microsoft/vscode/issues/23964#issuecomment-292344329

**Closed by alexandrudima** 2017-04-10 08:14 UTC

**Comment by DanielStolt** [comment] 2017-04-10 22:46
Yep, workaround fixes the issue for me. Thanks!
