### ISSUE TITLE
macOS10.15.4 Restart the vs cursor to automatically thicken

### ISSUE THREAD

**Issue by shenzhimanong** [microsoft/vscode#97573] opened 2020-05-12 03:42 UTC
Issue Type: <b>Bug</b>

Restart the vs cursor to automatically thicken

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

**Comment by alexdima** [comment] 2020-05-12 13:41
Duplicate of #97550

**Closed by alexdima** 2020-05-12 13:41 UTC
Labels: new release
