### ISSUE TITLE
[json] Cache JSON schemas locally

### ISSUE THREAD

**Issue by DovydasNavickas** [Microsoft/vscode#31121] opened 2017-07-20 10:22 UTC
At the moment I'm travelling and it's not 100% of the time that I have an internet connection.
Turns out that vscode does not cache JSON schemas that are defined in URLs, I presume, here:
https://github.com/Microsoft/vscode/blob/ac8f47b193f08b93e0d05201cf3ecc896914e6a5/extensions/typescript/package.json#L447

It's a pitty that JSON schema for sure did not change since an hour ago, when I had the internet connection, but I have zero completion for `tsconfig.json` right now, just because I'm offline.

Therefore, it would be super amazing to have JSON schemas cached if the URL did not change.

**Comment by aeschli** [comment] 2017-09-15 14:31
duplicate of #11828

**Closed by aeschli** 2017-09-15 14:31 UTC
Labels: feature-request, json
