### ISSUE TITLE
Error when try to connect with WSL Server

### ISSUE THREAD

**Issue by Drummond-Dev** [microsoft/vscode#127121] opened 2021-06-25 01:25 UTC
Issue Type: <b>Bug</b>

Alwas I try to connect a WSL Ubuntu give a error:

sh: 1: /mnt/c/Users/danie/.vscode/extensions/ms-vscode-remote.remote-wsl-0.56.5/scripts/wslServer.sh: Input/output error

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (5.80GB free)|
|Process Argv|--crash-reporter-id 54f81e63-6095-4159-9851-271ff026096d|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by aeschli** [comment] 2021-06-25 11:24
It's a duplicate of https://github.com/microsoft/vscode-remote-release/issues/2297

It's a WSL issue. You need to run wsl --shutdown to solve the problem.

**Closed by aeschli** 2021-06-25 11:24 UTC
