### ISSUE TITLE
can you add ALT-SELECT ?

### ISSUE THREAD

**Issue by crillion** [Microsoft/vscode#29110] opened 2017-06-20 14:42 UTC
In Visual Studio / Notepad++ / QtCreator, one can select text while pressing ALT, and this allows to grab a rectangle which doesn't start necessarily on the first column. I've seen that this feature is missing in VS Code (it instead just grabs everything from topleft first character through all the lines untile the last character. Can this feature be added ?

- VSCode Version: 1.13.1
- OS Version: windows 10

Steps to Reproduce:

1. load a text into Visual Studio Standard
2. highlight a rectangle of text whose top left corner is not on the first column
-> in Visual Studio it works.
3. load a text into VSCode
4. try highlighting a rectangle of text whose top left corner is not on the first column
-> in VSCode it doesn't work.

**Comment by celfrumos** [comment] 2017-08-29 20:45
I have been hoping for this feature for a while now. It's one of the things I like most about both Visual Studio and Notepadd++. It makes many tasks so much easier.

**Comment by TarAlacrin** [comment] 2017-09-05 22:30
Here's the thing; the feature is "there" in the program with just a bafflinngly poor implementation:

You can use Shift-Alt-Drag to achieve basically the same thing. But it works based off of your original pointer position, rather than functioning like all those other programs and literally every other program when it comes to drag selection.

I don't know why they don't just bump it from Shift-Alt-Drag to just Alt-Drag, and make it so it functions sensibly, not the unintuitive mess they use now.

**Comment by rjmunro** [comment] 2018-03-05 09:09
This is a duplicate of #5402. Please ensure you give that one a thumbs up.

**Closed** 2018-03-05 13:23 UTC
Labels: editor-columnselect, feature-request
