### ISSUE TITLE
Double paste after copy

### ISSUE THREAD

**Issue by matteocabe** [microsoft/vscode#102466] opened 2020-07-14 07:39 UTC
- VSCode Version: 1.47.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Ctrl+c whatever you want
2. Ctrl+v

Does this issue occur when all extensions are disabled?: Yes/No

Whenever I try to copy and then paste a part of my code it pastes it twice. It's very annoying because every time I have to do ctrl+z to delete the second copy.

**Comment by kshitij86** [comment] 2020-07-14 08:27
It doesn't appear to be happening with my install. I have the same version. It could be problem with you system rather than **VSCode**. Does this happen with other apps in your system?

**Comment by gjsjohnmurray** [comment] 2020-07-14 10:11
Probably duplicate of #101946

**Comment by micheledemeo** [comment] 2020-07-14 13:41
I have the same issue when I paste in a Python Interactive Window.

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment] 2020-07-14 13:49
The fix for #101946 is due to get fixed in the upcoming recovery release of 1.47.x

/duplicate

**Closed** 2020-07-14 13:50 UTC
Labels: *duplicate
