### ISSUE TITLE
Replace all doesn't work when there are > 999 matches

### ISSUE THREAD

**Issue by bootstraponline** [Microsoft/vscode#35440] opened 2017-09-30 21:56 UTC
- VSCode Version: Version 1.16.1 (1.16.1)
- OS Version: macOS High Sierra Version 10.13

Steps to Reproduce:

1. Open file with lots of text.
2. Replace text that matches thousands of times
3. Observe nothing happens

<img width="999" alt="vscode_replace_fail" src="https://user-images.githubusercontent.com/1173057/31049775-9ccb396c-a608-11e7-94b2-581c501cc79c.png">

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-10-26 07:44
Duplicate of #32522. Fixed already in stable starting with 1.17

**Closed by alexandrudima** 2017-10-26 07:44 UTC
Labels: editor, editor-find-widget
