### ISSUE TITLE
"Linking" CSS JS and HTML to have access to classes from other files in your project

### ISSUE THREAD

**Issue by snakebite-382** [microsoft/vscode#108743] opened 2020-10-15 14:01 UTC
It would be super helpful if you could link CSS HTML and JS pages together. <br>Essentially you could use a setting to, for example, "link" your CSS to you HTML so you wouldn't have to search through your HTML for a class or ID it would just appear as a suggestion in your CSS. This would save so much debugging and searching time. Please tell me if this already exists as an extension.

**Comment by aeschli** [comment] 2020-10-15 15:29
duplicate of #47331

**Closed by aeschli** 2020-10-15 15:29 UTC
