### ISSUE TITLE
Keep all my extensions

### ISSUE THREAD

**Issue by kalber** [microsoft/vscode#88982] opened 2020-01-20 16:30 UTC
As an user, I want to login to keep all my extensions when I change my computer.
Thanks, Greetings.

**Comment by Borks** [comment] 2020-01-20 16:34
Could use settings sync extension. 
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by IllusionMH** [comment] 2020-01-20 16:59
/duplicate of #2743 which is in progress for January release.

In the meantime you can use extension recommended by **Borks** above

**Closed** 2020-01-20 16:59 UTC
Labels: *duplicate, extensions
