### ISSUE TITLE
macOs Big Sur Split Terminal stutters

### ISSUE THREAD

**Issue by iloveswift** [microsoft/vscode#111076] opened 2020-11-21 03:03 UTC
Issue Type: <b>Bug</b>

1、macOs Big Sur 
2、Click [Ctrl + `]
3、Click button [Split Terminal] 

It is stutters when i input in the new terminal

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id cbf70485-c662-410a-b855-71e46c5b1122|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|2.1.13
EditorConfig|Edi|0.15.1
vue|jcb|0.1.5
node-module-intellisense|lei|1.5.0
mssql|ms-|1.9.0
vetur|oct|0.30.2

</details>

**Comment by the-kenny** [comment] 2020-11-21 10:46
Are you experiencing periodic slowdowns? If so, it's likely the same issue as #111074

**Comment by iloveswift** [comment] 2020-11-22 00:23
Yes， it is same issue. And there is another problem: the new terminal's pop-up speed is very slow

**Comment by meganrogge** [comment] 2020-11-22 02:33
Duplicate of #111074

**Closed** 2020-11-22 02:34 UTC
Labels: *duplicate, bug, integrated-terminal
