### ISSUE TITLE
Hard tabs that are equivalent to only one space generate shorter character display widths

### ISSUE THREAD

**Issue by wmaynard** [Microsoft/vscode#58133] opened 2018-09-07 00:29 UTC
- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13.6

Settings for tabs:
"editor.tabSize": 4,
"editor.detectIndentation": false,
"editor.insertSpaces": false,
"editor.renderWhitespace": "all"

Steps to Reproduce:

1. Enter the text `888	` (888{tab}) fifteen times on a single line.
2. Enter another 8.
3. The cursor will be offset from the last 8 by several character widths.

![image](https://user-images.githubusercontent.com/17485484/45191828-38578400-b1fa-11e8-942f-76669a969aff.png)

Expected result: the cursor will appear immediately after the 8 with no extra space.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-09-10 07:56
Duplicate of #54146.

@wmaynard Can you please update, the fix should be in 1.27.

**Closed by alexandrudima** 2018-09-10 07:56 UTC
Labels: editor, editor-autoindent
