### ISSUE TITLE
Text overlap in output cell and disappearing content in code cell (jupyter notebook)

### ISSUE THREAD

**Issue by jfbvalente** [microsoft/vscode#173797] opened 2023-02-08 11:26 UTC
Type: <b>Bug</b>

After updating to the latest VS Code version, I noticed two issues in the jupyter notebook:
a) in the output cell, both the content and the text "Outputs are collapsed" overlap. This text disappears once I collapse the output and show it again.
![image](https://user-images.githubusercontent.com/68605732/217516949-89fd84db-9da8-4fa0-b791-90d2f57e555a.png)

b) in the code cell, if I'm writing something and then scroll up/down, the content of this cell is no longer visible

Thanks

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.77GB free)|
|Process Argv|--crash-reporter-id eb2b3319-2545-4a3e-b5a5-dade30a4855e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|3.5.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30657576
f6dab269:30613381
pythonsymbol12cf:30657549
vsccsb:30659829

```

</details>

**Comment by matangover** [comment] 2023-02-08 15:22
Happens to me all the time, not sure exactly what are the steps to reproduce, it has something to do with collapsing cells and then running them again, or something to do with restarting the kernel...

![image](https://user-images.githubusercontent.com/5028956/217572697-980ee584-b25f-40a2-9096-7c6c83567164.png)

**Comment by JLune** [comment] 2023-02-08 17:43
Issue "a)" happened to me already before the last update as well, but the issue "b)" happens to me only since the last version and is quite incapacitating.

**Comment by rebornix** [comment] 2023-02-08 17:46
> b) in the code cell, if I'm writing something and then scroll up/down, the content of this cell is no longer visible

This issue should be fixed now in latest Insiders and will be released with next Stable recovery build.

**Closed** 2023-02-08 18:40 UTC
Labels: bug, notebook-output
