### ISSUE TITLE
[Terminal - Windows] Ctrl+c doesn't work

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#28635] opened 2017-06-13 15:52 UTC
- VSCode Version: Insiders bbcd10...
- OS Version: Windows 10 (Insiders)

Steps to Reproduce:

1. Open a new integrated terminal
2. Type "node" to run nodejs
3. Type `ctrl + c` (several times)

What happens?
Nothing

What should happen?
The first time `ctrl + c` is pressed, nodejs should print out `(To exit, press ^C again or type .exit)` and the second time it is pressed, it should exit nodejs.

Note that it works fine with a standard (external) cmd prompt.

Here is my settings.json file:

```
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.lineHeight": 1.3,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.openFilesInNewWindow": false,
    "window.reopenFolders": "one",
    "typescript.check.tscVersion": false,
    "workbench.sideBar.location": "left",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",
    "terminal.integrated.rightClickCopyPaste": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontLigatures": true,
    "terminal.integrated.fontFamily": "Consolas",
    "workbench.quickOpen.closeOnFocusLost": true,
    "workbench.iconTheme": "vscode-great-icons",
    "hexdump.width": 32,
    "window.menuBarVisibility": "toggle",
    "workbench.colorTheme": "Dracula",
    "editor.formatOnPaste": true
}
```

**Comment by Tyriar** [comment] 2017-06-13 18:58
This has been a long standing issue I believe related to winpty. Currently tracked upstream in https://github.com/Tyriar/node-pty/issues/7

@rprichard could this have something to do with the processes not dying when ctrl+c is pressed, similar to https://github.com/Microsoft/vscode/issues/26807?

**Comment by rprichard** [comment] 2017-06-13 19:53
> @rprichard could this have something to do with the processes not dying when ctrl+c is pressed, similar to 26807?

No, those two issues aren't likely to be related.

It could be related to this upstream winpty issue, https://github.com/rprichard/winpty/issues/116.  For now, I'm considering it a limitation.  The master branch in winpty has a change that improved Ctrl-C handling in new versions of PowerShell (e.g. Windows 10, not Windows 7).  Maybe it'd also improve node.js?

However, I just tested winpty+node, and it worked fine, even with old versions of winpty.  When I hit Ctrl-C, I see the message prompting me to hit Ctrl-C again, and when I do, it exits.  It also worked fine in VS Code.  I'm using Win 10.0.15063.332 (Creators Update) and node v6.10.3.  I first tested in Cygwin64's mintty running winpty 0.4.2, 0.4.3, and master.  I then tested with VS Code 1.12.2.  VSCode updated itself to 1.13.0 today, and that also worked fine.  My VSCode's `terminal.integrated.shell.windows` setting is unset, so VSCode initially runs PowerShell under winpty.

Here's what I see in VSCode when I type: `1 + 2 Enter Ctrl-C Ctrl-C.`

```
C:\Users\rprichard>node.exe
> 1 + 2
3
>
(To exit, press ^C again or type .exit)
>

C:\Users\rprichard>
```

Maybe report your `node --version`.

**Comment by rprichard** [comment] 2017-06-13 20:04
I installed node 8.1.0, and it also worked fine.  In Cygwin64's mintty:

```
rprichard@duck15063 ~/proj/winpty
$ build/winpty --version
winpty version 0.4.4-dev
commit ce9239af5d751195ea6982a41c7d71356ac9201c

rprichard@duck15063 ~/proj/winpty
$ /c/Program\ Files/nodejs-8.1.0-x64/node.exe --version
v8.1.0

rprichard@duck15063 ~/proj/winpty
$ build/winpty /c/Program\ Files/nodejs-8.1.0-x64/node.exe
> 1 + 2
3
>
(To exit, press ^C again or type .exit)
>

rprichard@duck15063 ~/proj/winpty
```

It also worked fine in VSCode.

**Comment by warpdesign** [comment] 2017-06-13 20:51
I am using node 7.0.0, and the standard cmd.exe (no powershell or bash but I have the same problem from vscode/bash).

**Comment by Tyriar** [comment] 2017-06-13 21:44
@rprichard it seems to happen about 50% of the time to me..

**Comment by jpmckearin** [comment] 2017-06-15 09:44
Could it be that this is fixed with the Creator's Update? I am on Anniversary Update and have this problem.

**Comment by warpdesign** [comment] 2017-06-15 09:53
@Tyriar Something interesting. I downloaded VSCode 1.13.1 (public stable build) and ctrl+c works as expected.

**Comment by eamodio** [comment] 2017-06-20 05:11
Is there a workaround for now to kill a running task in the terminal (without killing the whole terminal)?

**Comment by Tyriar** [comment] 2017-06-20 19:25
@eamodio I'm not aware of a workaround.

**Comment by tonoslav** [comment] 2017-06-21 15:39
Solution for my problem:

 - in **User settings** 
 - edit setting **terminal.integrated.commandsToSkipShell** 
 - remove **workbench.action.terminal.copySelection** from array

now terminating of batch job in terminal works via CTRL + C for me

**Comment by Tyriar** [comment] 2017-06-21 15:58
@tonoslav bingo, you found the bug! I actually fixed this yesterday in Insiders 😄, here's the root cause: https://github.com/sourcelair/xterm.js/issues/724

**Closed by Tyriar** 2017-06-21 15:58 UTC
Labels: bug, integrated-terminal, upstream

**Comment by mikemaccana** [comment] 2017-07-13 16:31
Hrm `"workbench.action.terminal.copySelection"` is in `DEFAULT SETTINGS` but not in `USER SETTINGS`. How can I undo the default setting?

**Comment by Tyriar** [comment] 2017-07-13 17:16
@mikemaccana I doubt you're experiencing this issue. Also `workbench.action.terminal.copySelection` is a command (keybinding), not a setting.
