### ISSUE TITLE
Document hint in VS Code shows HTML tags

### ISSUE THREAD

**Issue by BrainCrumbz** [Microsoft/vscode#17298] opened 2016-12-15 12:39 UTC
- VSCode Version: 1.8.0
- OS Version: Windows 10 64bit 1511

We noticed a *visual* issue with documentation tooltip when hovering the mouse on an API from RxJs library. Then created an issue [over there](https://github.com/ReactiveX/rxjs/issues/2197): outcome is that document format respects JSDoc standard, so now it's more a question of whether VS Code should fully support JSDoc or what.

Steps to Reproduce:

1. have an Angular 2 / TypeScript 2 web application with a dependency on RxJs (5.0.0-rc.1)
1. open it in Visual Studio Code, v1.8.0
1. reach for an `Observable<>.do()` invocation
1. hover mouse to show documentation tooltip

Here's a screenshot showing the unexpected tags:

![vscode-jsdoc-rxjs](https://cloud.githubusercontent.com/assets/3185573/21224286/c1688a3e-c2cb-11e6-82fe-78593f8623d5.png)

**Comment by mjbvz** [comment] 2016-12-15 19:11
Related to #1920. Even for markdown content we display, we usually strip out html tags to workaround fun security and ui issues. We could look into preprocessing jsdocs perhaps

**Comment by mjbvz** [comment] 2017-08-24 02:38
Closing as a duplicate of #1920. We likely will not support regular html contents in jsdocs, but do want to provide better support for markdown content

**Closed by mjbvz** 2017-08-24 02:38 UTC
Labels: api, feature-request, intellisense, javascript
