### ISSUE TITLE
Unable to download vscode windows

### ISSUE THREAD

**Issue by crostine** [Microsoft/vscode#72441] opened 2019-04-16 21:26 UTC
The download page links to a "Internal Server Error" or "Not Found".
I read some other issues, one was about VPN settings, for me this makes no change.

https://update.code.visualstudio.com/1.33.1/win32-x64-user/stable says "Internal Server Error".
https://update.code.visualstudio.com/latest/win32-x64-user/stable says "Not Found".

**Comment by creativeguy2013** [comment] 2019-04-16 21:27
duplicate of #72438

**Closed** 2019-04-16 21:27 UTC
Labels: install-update
