### ISSUE TITLE
Icon for R files overlap filename.

### ISSUE THREAD

**Issue by deathly809** [Microsoft/vscode#59867] opened 2018-10-03 00:19 UTC
Seems the icon for R is a little too large.  It is overlapping the text on my machine.

In the search:
![image](https://user-images.githubusercontent.com/1381210/46383735-c9d5dc80-c666-11e8-8a62-9e3cbd637b91.png)

In the explorer window:
![image](https://user-images.githubusercontent.com/1381210/46383752-e4a85100-c666-11e8-98ca-c25d3779d5c6.png)

- VSCode Version: 1.28.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create R file
2. Open in VSCode and look at icon

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by yeahok** [comment] 2018-10-03 11:08
I should be able to fix this.

**Comment by RMacfarlane** [comment] 2018-10-03 15:33
Duplicate of https://github.com/Microsoft/vscode/issues/57595

**Closed by RMacfarlane** 2018-10-03 15:33 UTC
Labels: insiders
