### ISSUE TITLE
Opens only once in portable mode

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#122539] opened 2021-04-28 13:09 UTC
https://user-images.githubusercontent.com/15984272/116408501-299ebf00-a833-11eb-9021-5ba12b74e5e3.mp4

Steps to Reproduce:

1. Download code-insiders 64-bit .tar.gz for debian here: https://code.visualstudio.com/insiders/
2. Inflate with tar -zxvf
3. Create a `data` folder inside
4. Launch code-insiders
5. Close it
6. Launch again, it never opens, and there is no error message (not in the terminal, nor in dmesg)

It works again once, when I do `rm -rf data && mkdir data`. I guess it becomes corrupt for some reason.

When I try the same steps to reproduce in an empty folder in `/tmp/repro`, it opens every time.

Tried with version `code-insider-x64-1619586588.tar.gz`

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2021-04-29 08:51
I just tried this in Ubuntu 18.04 and I can't reproduce. Can you run with `--verbose` and see if there's any additional info?

Also, can you check if any code processes are running with `ps ax | grep code-insiders`?

**Comment by sguillia** [comment] 2021-04-30 08:18
@joaomoreno Here is additional info with `--verbose`. It prints this when it doesn't open:
```
WARNING: IPC handle "/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/data/user-data/1.56.0-insider-main.sock" is longer than 107 chars, try a shorter --user-data-dir
[main 2021-04-30T08:15:34.713Z] Could not delete obsolete instance handle Error: ENOENT: no such file or directory, unlink '/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/data/user-data/1.56.0-insider-main.sock'
    at unlinkSync (original-fs.js:1210:3)
    at Z.claimInstance (/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:4557)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:1950
    at async Z.startup (/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:1821) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/data/user-data/1.56.0-insider-main.sock'
}
[main 2021-04-30T08:15:34.716Z] Error: ENOENT: no such file or directory, unlink '/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/data/user-data/1.56.0-insider-main.sock'
    at unlinkSync (original-fs.js:1210:3)
    at Z.claimInstance (/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:4557)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:1950
    at async Z.startup (/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:59:1821)
[main 2021-04-30T08:15:34.716Z] Lifecycle#kill()
```

**Comment by joaomoreno** [comment] 2021-04-30 08:31
> WARNING: IPC handle "/media/user/Storage/Applications-HDD/vscode-preprod/VSCode-linux-x64/data/user-data/1.56.0-insider-main.sock" is longer than 107 chars, try a shorter --user-data-dir

Yeah this could be problematic. Can you try placing VS Code on a shorter path, see if that works?

**Comment by sguillia** [comment] 2021-04-30 08:43
It works

It doesn't with a symlink in a shorter path, but it works when I move the installation on a shorter path

Although not convenient, it unblocked me so thank you

**Comment by joaomoreno** [comment] 2021-04-30 09:57
Yeah it's a bit sad that there are strict file path limits on named pipes. Closing this for now, hopefully not a lot of poeple hit the issue. 🤞 It's the first time I see it.

**Closed by joaomoreno** 2021-04-30 09:57 UTC
Labels: needs more info
