### ISSUE TITLE
character choose bug

### ISSUE THREAD

**Issue by chenxuuu** [Microsoft/vscode#58877] opened 2018-09-18 10:04 UTC
Issue Type: <b>Bug</b>

change "window.titleBarStyle" to "custom"
choose any letters, and still press the mouse, move mouse to menu bar, on any menu button
release mouse, move mouse to text area ,letters still be chose and changed by mouse

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\Desktop\学生卡.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
blamer-vs|bea|0.4.0
vscode-markdownlint|Dav|0.20.0
lualinter|dcr|1.0.3
gitlens|eam|8.5.6
vscode-pull-request-github|Git|0.1.5
diff-tool|jin|0.0.1
svn-scm|joh|1.35.1
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.27.2
python|ms-|2018.8.0
cpptools|ms-|0.18.1
team|ms-|1.136.0
luaide-lite|wel|0.1.5

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment] 2018-09-18 17:46
duplicate of https://github.com/Microsoft/vscode/issues/58446

**Closed by sbatten** 2018-09-18 17:46 UTC
Labels: editor
