### ISSUE TITLE
VSCode's CMD in Windows should automatically erase the entire terminal when full or use ANSI `\e[0;4H`

### ISSUE THREAD

**Issue by donno2048** [microsoft/vscode#142001] opened 2022-02-02 13:51 UTC
Basically, I wrote a game in C which works great in windows CMD but buffering in Linux Terminal this issue is solved using `\33[0;4H` printed at the beginning of each print to set it to the top and erase what was printed using insert mode (equivalent to `$ printf '\e[0;4H'`), but in VSCode CMD on Windows it's not working...

**Comment by Tyriar** [comment] 2022-02-02 18:20
The `H` sequence you mention moves the cursor, it doesn't erase anything:

> CSI Ps ; Ps H
>          Cursor Position [row;column] (default = [1,1]) (CUP).

Do you mean J or K? Any differences with Windows could be due to how the backend "conpty" works.

**Comment by donno2048** [comment] 2022-02-02 19:03
> The `H` sequence you mention moves the cursor, it doesn't erase anything:

Of course, it doesn't erase anything directly, the next print(f) statement replaces the previous text...

**Comment by Tyriar** [comment] 2022-02-02 20:53
Ah ok, I suspect this is due to conpty because of the way it renders is not like a regular terminal.

---

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2022-02-02 20:53 UTC
Labels: needs more info
