### ISSUE TITLE
Running docker in the background gives "Attribute 'program' does not exist ('path')" when clicking launcher

### ISSUE THREAD

**Issue by srlim** [Microsoft/vscode#6173] opened 2016-05-06 16:28 UTC
- VSCode Version: 1.0.0
- OS Version: 10.11.4

Steps to Reproduce:
1. Run docker in the background (doesn't need to use the project I use VSCode)
2. Click the launcher button
   Error: Attribute 'program' does not exist ('path')

This error doesn't happen when I am not running docker in the background

Please fix this problem. It's blocking me from developing effectively.

**Comment by isidorn** [comment] 2016-05-09 10:08
@srlim can you please share a small repository for which this can be reproduced. Can you share your `launch.json`. I suspect you are debugging node since that error happens in our node adapter, thus following to @weinand

**Comment by weinand** [comment] 2016-05-09 10:46
@srlim please add your `launch.json` and a screenshot of the error message `Error: Attribute 'program' does not exist ('path')` here.

**Comment by srlim** [comment] 2016-05-09 12:55
This issue is not very consistent. One day it works but another day it doesn't. I'll try to get a screenshot when I see it again. So I think the repo itself doesn't have a problem but maybe there are some conflicts with Docker running in the background?

**Comment by weinand** [comment] 2016-05-09 12:58
@srlim it would help if you could share the launch config that produces the `Error: Attribute 'program' does not exist ('path')` error.

**Comment by srlim** [comment] 2016-05-09 13:05
This is the launcher.json:
`{
			"name": "test",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/node_modules/mocha/bin/mocha",
			"stopOnEntry": false,
			"args": ["test/ui-tests/*-tests.js"],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		}`

**Comment by styfle** [comment] 2016-06-09 21:32
I also had this problem. I think it might be related to moving several "services" to the same git repo.
Example directory structure:

```
app/
├── .git/
├── .gitignore
├── catalog-service/
|   ├── .vscode/
|       └── launch.json
|   ├── node_modules/
|   └── server.js
├── user-service/
|   ├── .vscode/
|       └── launch.json
|   ├── node_modules/
|   └── server.js
└── docker-compose.yml
```

Then doing `cd app/catalog-service/ && code .` will open vscode for the catalog service and everything works fine except debugging. Note that `launch.json` has `program: "${workspaceRoot}/server.js"`.

### Workaround
The workaround was to `cd app/ && code .` will open vscode for the root directory with all services (main git repo). Then set `launch.json` at the top level to  `program: "${workspaceRoot}/catalog-service/server.js"`.

**Comment by neubeee** [comment] 2016-10-06 19:52
I also have the error: 
> Attribute 'program' does not exist ('c:\wamp64\www\myproj/app.js')

My project is an open source, that I downloaded, cannot find app.js or server.js anywhere. I'm a .net person, so this is all  new to me. I use 
- Win7
- VSCode 1.5.3
- Xdebug v2.4.1

Please advice. Thanks!

**Comment by jimsorock** [comment] 2016-11-16 06:46
@neubeee you have slashes going one way and then the other. Check your launch.js and make sure it is using escaped slashes since youre on windows. i.e.
`"${workspaceRoot}\\server.js"`
Chances are you're using or sharing this project with someone running vs code on a mac.  I switch between machines and noticed this issue.  It is probably best practice to not commit the launch.json imho.

**Comment by weinand** [comment] 2017-05-05 15:03
For the node.js ecosystem use of forward slashes should work on Windows too. But if you need OS specific settings in your launch config, please see this documentation: https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties

This applies to the "launch.json" too.

**Comment by weinand** [comment] 2017-05-05 15:12
Closing, since we weren't able to reproduce this problem.

**Closed by weinand** 2017-05-05 15:12 UTC
Labels: debug, needs more info
