### ISSUE TITLE
New Setting - don't open default keybindings

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#54825] opened 2018-07-22 16:39 UTC
There is a setting which toggles off the loading of the default settings when opening the settings.json called with: ```("workbench.settings.openDefaultSettings": false,).``` I propose that keybindings.json also have this feature.

**Comment by sandy081** [comment] 2018-07-24 14:31
Duplicate of #53372

**Closed** 2018-07-24 14:31 UTC
Labels: *duplicate
