### ISSUE TITLE
Simple color tabs/bubbles for the file explorer.

### ISSUE THREAD

**Issue by Drungle** [microsoft/vscode#92050] opened 2020-03-05 02:49 UTC
Hello. I had a random idea of implementing a simple color tab/bubble to the left of each file (if desired). This would allow for easy identification for "groups" of files when using a folder is not an option for a project. Thanks.

![File Explorer Colors](https://user-images.githubusercontent.com/30103848/75942566-b680ff00-5e60-11ea-877c-610b2b252fb7.png)
![File Explorer Colors Tabs](https://user-images.githubusercontent.com/30103848/75942791-58a0e700-5e61-11ea-9824-626f7e551814.png)

**Comment by isidorn** [comment] 2020-03-05 09:54
Somewhat a duplicate of https://github.com/microsoft/vscode/issues/62104
So please comment there, closing this one. Thanks

**Closed by isidorn** 2020-03-05 09:54 UTC
