### ISSUE TITLE
Changes view with screen reader shortcut not working when editor is not focused

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#94196] opened 2020-04-01 18:11 UTC
Refs #93301

I was very confused as to how to get into this mode and then I realized that when I click on a diff, the focus is still on the list:

![image](https://user-images.githubusercontent.com/35271042/78170710-32db1380-7408-11ea-95ec-898a8248b9c7.png)

So using the shortcut yields nothing, I have to enter focus into the editor and then use the shortcut to initiate that mode:

![image](https://user-images.githubusercontent.com/35271042/78171484-5a7eab80-7409-11ea-8eec-87030373b18a.png)

The editor should get focus when clicking on a diff as that's how it works in the explorer.

**Comment by isidorn** [comment] 2020-04-02 10:13
This makes sense, however it is a duplicate of https://github.com/microsoft/vscode/issues/93493

**Closed by isidorn** 2020-04-02 10:13 UTC
