### ISSUE TITLE
activeFolderShort in task.json

### ISSUE THREAD

**Issue by jacobSpitzer** [microsoft/vscode#110915] opened 2020-11-19 04:58 UTC
Hi,
I'm looking a long time for a solution to get the subfolder name of the current active file. i want to use it in tasks.json to run tasks.
Is there any predefined variable for current file folder-name to use in tasks (tasks.json) ? like the predefined variable in window settings ${activeFolderShort}.
on the documentation [variables-reference](https://code.visualstudio.com/docs/editor/variables-reference) i don't find any solution to get only the subfolder name of the current file. only the file name or the workspace path or the full path.

Thanks in advance

**Comment by alexr00** [comment] 2020-11-19 12:41
Duplicate of https://github.com/Microsoft/vscode/issues/78316

**Closed by alexr00** 2020-11-19 12:41 UTC

**Comment by jacobSpitzer** [comment] 2020-11-22 05:40
Thanks to [riov8's answer](https://stackoverflow.com/a/64911406/6509536) in stackoverflow, i got the quick answer:
You can use the extension [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable)

Use the variable

`${command:extension.commandvariable.file.fileDirBasename}
`
