### ISSUE TITLE
Requires for json files without explicit .json extension return error when checkJs is on

### ISSUE THREAD

**Issue by govindrai** [microsoft/vscode#118631] opened 2021-03-10 13:04 UTC
Issue Type: <b>Bug</b>

Enable JS/TS › Implicit Project Config: Check JS setting. 
Load any JSON file with a require statement without specifying `.json` extension. 
See red underline and ts error. 

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.34GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 7e7d0584-5292-4687-8ba9-8a7ade7a807f|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

Example Screenshot: ("Adding `.json` resolves the error). 
![image](https://user-images.githubusercontent.com/13859249/110633908-33bf0e00-815e-11eb-9ae6-865120fd023e.png)

My expectation is that node is able to resolve JSON files without an explicit extension so I shouldn't be seeing any error.

**Comment by mjbvz** [comment] 2021-03-10 19:50
Duplicate of https://github.com/microsoft/TypeScript/issues/24357

**Closed by mjbvz** 2021-03-10 19:50 UTC
