### ISSUE TITLE
Broken behavior of ctrl+click multiselection in explorer

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#74573] opened 2019-05-29 17:22 UTC
**Actual behavior**
First `ctrl+click` in explorer opens to side, then multiselect.

**Desired behavior**
Ctrl+click in explorer should begin multiselection from first ctrl+click as it is set as `multiSelectModifier` not  `firstOpenToSideThenMultiSelectModifier`.

[My settings](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e#file-settings-json)

**Comment by usernamehw** [comment] 2019-05-29 18:09
duplicate of #66925 ?

**Comment by isidorn** [comment] 2019-05-29 20:03
@usernamehw thanks

**Closed by isidorn** 2019-05-29 20:03 UTC
Labels: *duplicate
