### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by leeahoward** [microsoft/vscode#116231] opened 2021-02-09 21:28 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1. Error message displays when starting VSCode.
*This just started happening today.  I haven't made any changes to my configuration that I am aware of.  I will update if I learn more.

**TS Server Log**
`/Users/leehoward/Library/Application Support/Code/logs/20210209T162546/exthost2/vscode.typescript-language-features/tsserver-log-9qtBeb/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 6, 4|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv|--crash-reporter-id 84bdf4b4-b854-41f4-8f5e-756749af4094|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.11.1
ng-template|Ang|11.1.3
vscode-apollo|apo|1.18.0
vscode-twig-pack|baj|1.1.0
markdown-mermaid|bie|1.9.1
gitup|Bra|0.1.0
yaml-symbols|Cro|0.1.1
vscode-eslint|dba|2.1.14
vscode-html2pug|dba|4.0.0
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.15
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.9.1
filter-line|eve|2.0.1
git-project-manager|fel|1.7.1
vscode-graphiql-explorer|Gab|1.3.0
todo-tree|Gru|0.0.196
jenkinsfile-support|ivo|1.1.0
yuml|Jai|3.5.1
recent-files|jun|1.1.10
vscode-cfml|Kam|0.5.3
vscode-phpfmt|kok|1.0.30
pug2html|kru|0.0.2
vscode-docker|ms-|1.9.1
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
debugger-for-chrome|msj|4.12.12
vscode-ts-uml|myx|1.0.4
vscode-intellij-recent-files|per|1.0.0
explorer-exclude-vscode-extension|Red|1.2.0
vscode-workspace-switcher|sad|1.15.3
preview-vscode|sea|2.2.5
vscode-docker-ws|tii|0.5.0
email-viewer|Tom|5.0.0
vim|vsc|1.18.9
vscode-preview-server|yui|1.3.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by meganrogge** [comment] 2021-02-09 21:41
Duplicate of #116229

**Closed** 2021-02-09 21:42 UTC
Labels: *duplicate, new release
