### ISSUE TITLE
Keyboard shortcuts have reversed position of ` and §

### ISSUE THREAD

**Issue by lordchancellor** [Microsoft/vscode#24186] opened 2017-04-07 07:58 UTC
- VSCode Version: 1.11.0/1
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

Since updating to VS Code 1.11 I was unable to toggle the integrated terminal. Checking the new keybindings confirmed that the shortcut had not changed from (ctrl + \`). When attempting to re-bind the shortcut, I noticed that this screen has mixed up the position of the \` and  § keys, although in the standard editing window, \` and § are correctly positioned.

1. In the editing window, the \` and § keys behave as normal
2. In the key bindings menu, (attempting to add a new, or change an existing key binding), \` and § are reversed
3. In order to open the integrated terminal, you have to press (ctrl + §), even though the binding is set to (ctrl + \`)

**Comment by jsynowiec** [comment] 2017-04-07 08:57
Duplicate of #24173

**Comment by jsynowiec** [comment] 2017-04-07 08:58
Duplicate of #24086

**Comment by chrmarti** [comment] 2017-04-07 14:15
@lordchancellor Which keyboard layout are you using?

**Comment by lordchancellor** [comment] 2017-04-07 14:20
@chrmarti British. Sorry, should have realised that would be important to mention.

**Comment by alexandrudima** [comment] 2017-04-10 08:54
@lordchancellor This might be an issue in our native node module that reads the keyboard layout. Could you please do the following:

* open an editor
* run `F1 > Developer: Inspect Keyboard mappings`
* save the output to a file
* attach it here.

**Comment by alexandrudima** [comment] 2017-04-10 09:00
Let's track in #24153

**Closed by alexandrudima** 2017-04-10 09:00 UTC
Labels: keybindings, keyboard-layout, mac, needs more info

**Comment by lordchancellor** [comment] 2017-04-12 07:10
@alexandrudima I can see that you have the key mappings in #24153 - ping me if you need anything more from me on this! Thanks for your help.
