### ISSUE TITLE
Add editor action copySelection[Up/Down]

### ISSUE THREAD

**Issue by and-y** [Microsoft/vscode#15507] opened 2016-11-15 11:33 UTC
An action like `editor.action.copySelectionUpAction` and `editor.action.copySelectionDownAction` additional to `editor.action.copyLinesUpAction` and `editor.action.copyLinesDownAction` would make code copying even better.

E.g. you have the following code

```javascript
var user = [
    {
        name: 'Andy',
        age: 25
    }, 
    {
        name: 'Bob',
        age: 19
    }
];
```

Now I want to add some more users by copying the last user Object and editing the values.
I select the last Object with `SHIFT` + `UP` including the comma, but without the closing bracket.

```javascript
    , 
    {
        name: 'Bob',
        age: 19
    }
```

With  `editor.action.copyLinesDownAction` the whole line including the previous closing bracket is copied.
A new editor action  `editor.action.copySelectionDownAction`  would solve this.

**Comment by kaiwood** [comment] 2016-11-15 14:01
Proper duplication of text, the feature request would be the same as this one: https://github.com/Microsoft/vscode/issues/13780

**Comment by kaiwood** [comment] 2016-11-15 14:36
@and-y I checked the market place because I consider this essential too, this extension solves your usecase while waiting for it to be implemented in VSCode: https://marketplace.visualstudio.com/items?itemName=lafe.contextualduplicate

**Comment by ramya-rao-a** [comment] 2016-11-16 03:04
Closing as duplicate of #13780

**Closed by ramya-rao-a** 2016-11-16 03:04 UTC
