### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by srudhish** [microsoft/vscode#73386] opened 2019-05-07 05:29 UTC
Issue Type: <b>Bug</b>

when adding examplecomponent to app-routing after generating examplecomponent it returns error "examplecomponent is not a part of ngModule. Sometimes it shows irrelevant error messages. I have captured these bugs and I would like to let you see.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

![app-routing](https://user-images.githubusercontent.com/50352467/57273908-15e27700-70b7-11e9-86c9-e1676ee97005.png)
![Capture](https://user-images.githubusercontent.com/50352467/57273909-15e27700-70b7-11e9-8b39-810d5665dd8c.PNG)
![Capture1](https://user-images.githubusercontent.com/50352467/57273910-167b0d80-70b7-11e9-8124-f2fa0c2c1864.PNG)
![Capture2](https://user-images.githubusercontent.com/50352467/57273911-167b0d80-70b7-11e9-9ff8-36cd401d0d02.PNG)
![Capture3](https://user-images.githubusercontent.com/50352467/57273912-167b0d80-70b7-11e9-98fe-19ff3b669547.PNG)

**Comment by chrmarti** [comment] 2019-05-07 09:28
Looks like an issue with the Angular compiler. Which extensions do you have installed?

**Comment by mjbvz** [comment] 2019-05-07 20:24
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment] 2019-05-17 17:28
Closing as more information is needed to investigate this

**Closed by mjbvz** 2019-05-17 17:28 UTC
Labels: needs more info
