### ISSUE TITLE
HTML Javascript Syntax Highlighting bug

### ISSUE THREAD

**Issue by Jose134** [microsoft/vscode#100668] opened 2020-06-20 23:06 UTC
![highlightingBug](https://user-images.githubusercontent.com/12801876/85213164-f4942700-b35a-11ea-83e7-571a6c8a6d71.PNG)
The first </script>, the HTML comments and the code of the script at the bottom don't get correctly highlighted

(This code is right before the end of the body and html tags at the end of the file)

- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.18363
As it appears on VSCode's About dialog

Steps to Reproduce:

1. Write the following code in a HTML file
```
<!-- Insert this line above script imports  -->
        <script> if (typeof module === 'object') { window.module = module; module = undefined; } </script>

        <!-- Black Dashboard JS dependencies -->
        <script src="black-dashboard/assets/js/core/jquery.min.js" type="text/javascript"></script>
        <script src="black-dashboard/assets/js/core/popper.min.js" type="text/javascript"></script>
        <script src="black-dashboard/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
        <script src="black-dashboard/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
        <script src="black-dashboard/assets/js/plugins/chartjs.min.js"></script>
        <script src="black-dashboard/assets/js/plugins/bootstrap-notify.js"></script>
        <script src="black-dashboard/assets/js/black-dashboard.js?v=1.0.0" type="text/javascript"></script>

        <!-- Insert this line after script imports -->
        <script> if (window.module) module = window.module; </script>
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-06-21 03:03
First recommendation is to update to the current release (1.46.1) and retest.

**Comment by Jose134** [comment] 2020-06-21 09:07
> 
> 
> First recommendation is to update to the current release (1.46.1) and retest.

I've just tested on the latest version and also in VSCode insiders (1.47.0). The bug was still there on both versions.

**Comment by alexr00** [comment] 2020-06-22 11:40
Looks like the javascript scope is leaking out of `script` tags
![image](https://user-images.githubusercontent.com/38270282/85283620-f579a580-b48d-11ea-878f-3e80163bb7e8.png)

**Comment by alexr00** [comment] 2020-06-22 11:47
Duplicate of https://github.com/textmate/html.tmbundle/issues/85, which is about javascript scope leaking out.

**Closed by alexr00** 2020-06-22 11:47 UTC
