### ISSUE TITLE
Ubuntu Installation Not Installing Launcher Icon Pack

### ISSUE THREAD

**Issue by iamaaron** [Microsoft/vscode#17644] opened 2016-12-21 06:49 UTC
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. Install VSCode on Ubuntu via .deb file from https://code.visualstudio.com/
2. Notice that the Launcher icon is missing.

Some notes:
- /usr/share/icons/ does not include an icon pack for VSCode.
- The solution to copy an image to /usr/share/icons/ does not apply the Launcher icon.
- The solution to create a code.desktop file and placing it in ~/.local/share/applications/ with a corresponding image does not work.

My solution was to place a .png icon in /usr/share/icons/ and update the Applications properties icon to point to that image.

I am not extremely familiar with how the application is being built or installed, but I thought I'd bring this to attention.

Thanks!

**Comment by cybercatalyst** [comment] 2016-12-21 20:39
@iamaaron Can you be more specific? I tried it here, but cannot reproduce the bug here. The launcher icon just appears fine. Are you using a default Ubuntu with Unity?

**Comment by bgse** [comment] 2016-12-21 22:26
@iamaaron Was this a full fresh install, and how did you install the .deb exactly?

I couldn't reproduce on 16.04 with vscode 1.8.1 when uninstalling and reinstalling the .deb using Ubuntu Software.

**Comment by iamaaron** [comment] 2016-12-21 22:59
@cybercatalyst I am using vanilla Ubuntu with Unity.

@bgse This a rather fresh OS install with minimal customization. I installed the .deb file through the Software Center once downloaded from the website.

Yeah, my install was a fresh install of 1.8.1.

I found other **Issues** where are users were experiencing the same problem, none of their solutions worked and it was denoted by the contributors that this would be resolved in the following version, but didn't appear that way for me.

https://github.com/Microsoft/vscode/issues/4077

https://github.com/Microsoft/vscode/issues/6432

Thanks!
Aaron

**Comment by bgse** [comment] 2016-12-21 23:18
@iamaaron Can you check if the application launcher is there?

```
bgse@thundercat:~$ ls -la /usr/share/applications/code.desktop 
-rw-r--r-- 1 root root 671 Dez 21 23:24 /usr/share/applications/code.desktop
```

You should see modification date as above, which corresponds to install time.

**Comment by Tyriar** [comment] 2016-12-21 23:29
Any additional information would be helpful, the .desktop file should be installed to `/usr/share/applications` as @bgse mentioned ([done here](https://github.com/Microsoft/vscode/blob/651c27dc87bf92567b3236dabbbbad95d4db0360/build/gulpfile.vscode.linux.js#L58)).

I suspect the software center is to blame as I've had issues with it not installing correctly. Did you get a permissions prompt when installed?

Installing it manually via `dpkg` may fix the issue:

```
sudo dpkg -i <file>.deb
```

**Comment by Tyriar** [comment] 2017-04-21 04:49
Closing as not enough info to repro.

**Closed by Tyriar** 2017-04-21 04:49 UTC
