### ISSUE TITLE
Add Bracket Notation support to "Convert to optional chain refactoring" Feature

### ISSUE THREAD

**Issue by Whobeu** [microsoft/vscode#107017] opened 2020-09-18 14:16 UTC
I was testing out the new "Convert to optional chain refactoring" feature in the TypeScript support of VSCode 1.49. I found it was working correctly with fixed property statements like:

```
const access = permissions &&
  permissions.scopes &&
  permissions.scopes.status === "GRANTED";
```
With the result being:

`const access = permissions?.scopes?.status === "GRANTED";`

But when I tried to convert statements using a variable property with bracket notation, VSCode failed to recognize the statement as one that could be converted to Optional Chaining:

```
const access = permissions &&
  permissions.scopes &&
  permissions.scopes[permission] &&
  permissions.scopes[permission].status === "GRANTED";
```

The Optional Chaining equivalent of this statement would be:

`const access = permissions?.scopes?.[permission]?.status === "GRANTED";`

VSCode does understand that the variable property notation is syntactically valid and the TypeScript compiler will convert the statement correctly to pre-ES2020 format. It would appear the conversion routine in VSCode is simply missing the ability to recognize this form of Optional Chaining.

**Comment by mjbvz** [comment] 2020-09-18 16:36
Duplicate of https://github.com/microsoft/TypeScript/issues/40510

**Closed by mjbvz** 2020-09-18 16:36 UTC
