### ISSUE TITLE
Problem with auto-completion on JavaScript

### ISSUE THREAD

**Issue by writedev** [microsoft/vscode#230811] opened 2024-10-08 15:21 UTC
**Type**: Performance Issues

I have an issue with auto-completion when using "module" in JavaScript. The "module" keyword and its functions are not being auto-completed, even without any extensions.

## Steps to reproduce:

1. Create a file named `config.js`.
2. Type "mod" (to test the auto-completion).
3. Then delete it and paste:

    ```
    module.
    ```

   (to see if the functions are also auto-completed).

VS Code Version: 1.94.0 x64  
OS Version: Windows 11 23H2

**Comment by IllusionMH** [comment] 2024-10-08 20:13
Looks like issue wit Node.js types ATA

/duplicate of #230596

Needs TS release and then VS Code recovery built to include fixed TS version.

**Closed** 2024-10-08 20:13 UTC
Labels: *duplicate
