### ISSUE TITLE
Remember recent user input variables in launch configs

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#78213] opened 2019-07-30 20:22 UTC
It would be extremely useful if VS Code would remember recent values used for user inputs of type "promptString" and offer them as quick input.

**Comment by isidorn** [comment] 2019-07-31 09:33
fyi @weinand @alexr00

**Comment by weinand** [comment] 2019-07-31 09:47
Makes sense.

**Comment by alexr00** [comment] 2019-07-31 10:15
Duplicate of https://github.com/microsoft/vscode/issues/72944

**Closed by alexr00** 2019-07-31 10:15 UTC
Labels: feature-request
