### ISSUE TITLE
An option to easily import a function from one file to another!

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#96984] opened 2020-05-05 12:02 UTC
I got a big project, probably 100s of files. Lot of files have same name, and lot of them have deprecated. Autocomplete for import can't tell that.

I wish I could simply right click function and click **select for import** and then go to file I'm working on and right click and click **import selected symbol** and/or **import selected file**.

It's really annoying to find right path to another file when both files are nested 10 directories deep in completely different folders.

**Comment by Tyriar** [comment] 2020-05-05 16:00
What language is this for? Have you tried using find all references/go to implementation?

**Comment by techsin** [comment] 2020-05-05 16:50
File a.js has a function I want. I want to use that function in File b.js, but it is very far location wise. 
So I've to figure out a relative path to that file.

`import { func } from '../../../../views/src/utilities/ads/stuff`

**Comment by yume-chan** [comment] 2020-05-05 18:24
See #5240

@ElecTreeFrying has made an [extension](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.auto-import) that pretty close to your proposed steps. (See [#5240 (comment)](https://github.com/microsoft/vscode/issues/5240#issuecomment-598757842))

**Comment by mjbvz** [comment] 2020-05-05 18:44
Duplicate of #94729

@techsin Don't open duplicate issues. You really seem to care about this so I suggest that you try writing an extension that does this

**Closed by mjbvz** 2020-05-05 18:44 UTC
