### ISSUE TITLE
Interactive Playground attempt to create files in URI styled path resulting in file not found errors

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [Microsoft/vscode#55101] opened 2018-07-26 01:50 UTC
- VSCode Version: 1.25.1
- OS Version: Microsoft Windows [Version 10.0.17134.165] _and_ macOS 10.13.6

Steps to Reproduce:

1. Go to the Interactive Playground (**Help > Interactive Playground**)
2. Find the header **Refactoring via Extraction** and invoke `Quick Fix...` Command as instructed on places where appropriate (Default shortcut for Windows is `Ctrl+.` and macOS is `⌘+.`, you can also click the light bulb symbol using a mouse)
3. Select _any_ extraction method on the drop down menu displayed (If you see "no code actions available", try another part of the code: `arr[i]` is tested to work) and the result is the same (see the next step)
4. Nothing happens except for an error thrown in Developer Tools' console and also in **Bottom pane > Output tab > Select "Log (Window)" in the drop down menu**:
**Windows**:
```
[renderer1] [error] Error: Failed to create file walkThroughSnippet:/c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#4.js
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1349:65)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3195:251
    at n.Class.derive.supportedForProcessing.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:736)
    at t.createFile (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3195:51)
    at e.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3976:232)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161:768
    at Object.s.__generator.a.label [as next] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161:873)
    at s (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:856)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
**macOS**:
```
[renderer1] [error] Error: Failed to create file walkThroughSnippet:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#4.js
    at new t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1349:65)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3195:251
    at n.Class.derive.supportedForProcessing.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:736)
    at t.createFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3195:51)
    at e.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3976:232)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:161:768
    at Object.s.__generator.a.label [as next] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:161:873)
    at s (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:160:856)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
**Notes**:
It seems that it is trying to build a filesystem path from a URI path, but failed to convert `%20`s into spaces and `%3A`s into colons. It also left the scheme (`walkThroughSnippet` in this case) in the path, which results in the inability to create files necessary for extraction to work

This is **NOT** #51575 and **DO NOT** confuse this as a duplicate of that. This occurs after VSCode has detected that it _can_ be refactored. (When "no code actions available" is **not** shown) It goes as far as the step showing the drop down menu asking to choose between extraction to constant, function in global scope, and inner function. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-07-26 01:53
Duplicate of #53113

**Closed by mjbvz** 2018-07-26 01:53 UTC
