### ISSUE TITLE
Sometimes sticky header for an old file shows up for a new file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166018] opened 2022-11-10 15:21 UTC
I end up seeing this quite a bit:

![image](https://user-images.githubusercontent.com/2193314/201134563-f016fc65-007b-4515-99f4-7786cf204fd4.png)

Not sure on exact repro, but sometimes when opening a different file or creating a new file the sticky header from another file sticks around.

Couldn't see it in https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aeditor-sticky-scroll+label%3Abug

**Comment by Tyriar** [comment] 2022-11-11 23:58
When debugging a notebook just now it was obscuring the debugged line completely:

![image](https://user-images.githubusercontent.com/2193314/201445773-015bd148-25e6-41d4-95a6-666c560fafda.png)

**Comment by ahkhanjani** [comment] 2022-11-13 16:41
Perhaps related to #165385?

**Comment by alkatar21** [comment] 2022-11-15 14:16
I can not reproduce it yet, but I have over time also always sticky scrolls from other files in other files. I noticed it in the div views when staging files for git, that every now and then wrong sticky scrolls appear in empty windows with new files or also cover the top lines with existing files. I suspect the underlying bug is the same.

**Comment by beejaz** [comment] 2022-11-15 15:07
Hi,

I have this issue also and kind of know how to reproduce/trigger it. The problem for me only shows up in "Source Control" panel, it doesnt show up when scrolling trough in regular "Explorer" view.

1) Have a git repo initialized, open a large file where sticky scroll is active. Make a change and save.
2) Open a second long file file, make a change and save.
3) Go to "Source control" so you see your two modified files. Open the first file so it show split window with your change, scroll down activating sticky scroll.
4) Change to second file still in source control tab. Sticky scroll from previous file / line is still showing.

![image](https://user-images.githubusercontent.com/9569157/201953607-f9acf4ea-3c12-4748-bec8-e372eb6dc3ce.png)

```
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z (6 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

Hope it helps!

**Comment by jrieken** [comment] 2022-11-18 14:57
Due to the lack of steps and new insights I am closing this as dupe https://github.com/microsoft/vscode/issues/165385. @Tyriar please keep an eye out but I am optimistic because we should not clear existing sticky scrolls when having no new elements (empty or "flat" file)

**Closed by jrieken** 2022-11-18 14:57 UTC
Labels: papercut :drop_of_blood:, editor-sticky-scroll
