### ISSUE TITLE
Can not find file in html 'src' and 'href' attrs (html file is not in the project root dir)

### ISSUE THREAD

**Issue by imzhengfei** [Microsoft/vscode#40100] opened 2017-12-12 14:29 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
material-icon-theme|PKi|3.1.0
code-settings-sync|Sha|2.8.7
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
Angular1|joh|0.2.0
Angular2|joh|2.11.2
intellij-idea-keybindings|k--|0.2.16
debugger-for-chrome|msj|3.5.0
view-in-browser|qin|0.0.5
autoimport|ste|1.5.3
code-spell-checker|str|1.6.0
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

---

**Steps to Reproduce:**

1. code in html file:
```html
  <script src="app.routes.js"></script>
```
html file location in project: src/index.html
press `command + left click` on `src` attr.

2. Error: `can not open “app.routes.js”: can not find file (file:///Users/Avin/Dev/WorkSpace/angularjs-seed/app.routes.js)`
the right path is: `/Users/Avin/Dev/WorkSpace/angularjs-seed/src/app.routes.js`
`src` was missing

**Reproduce**
produces without extensions: Yes

**Comment by aeschli** [comment] 2017-12-13 10:38
duplicate of #18096

**Closed by aeschli** 2017-12-13 10:38 UTC
Labels: html
