### ISSUE TITLE
Give option for changing rendered markup content in Jupyter Notebook

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#209669] opened 2024-04-05 17:13 UTC
![image](https://github.com/microsoft/vscode/assets/54276661/a012f1b4-8e8f-4b99-b62c-9fb696fe7bb7)

Looking at image of a opened jupyter notebook above; we see three fonts: SF Mono, Fira Code and default Windows font Segoe UI.
Currently vscode provides option for customising two of them: SF Mono and Fira Code (i.e. those element's font family can be customised), but no customisation is there for changing Markup font. 

We need new markup font customisation option. 
A option like `notebook.markup.fontFamily` is needed.
Thank You.

**Comment by rebornix** [comment] 2024-12-09 23:55
/duplicate of https://github.com/microsoft/vscode/issues/143907

**Closed by rebornix** 2024-12-09 23:55 UTC
Labels: feature-request, notebook-markdown
