### ISSUE TITLE
Allow extensions to update folder based configuration

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29675] opened 2017-06-27 20:59 UTC
testing  #29466:

- this 3 folder setup:
  ![2017-06-27_22-40-31](https://user-images.githubusercontent.com/1898161/27608991-a84497b2-5b89-11e7-895c-7e8c2390a1d2.png)
- value for "editor.lineNumbers" in the 3 setting files:
  - main: "relative"
  - f1: "on"
  - f2: "off"
- this code in "sayHello" handler of "hello world" extension:
  ```ts
        const uri = vscode.window.activeTextEditor.document.uri;
        const config = vscode.workspace.getConfiguration2("editor", uri);
        config.update("lineNumbers", "on");
  ```
- open f2.txt in editor (which lives in folder f2 and has the editor.lineNumbers value "off")
- trigger sayHello command

Observe:
"editor.lineNumbers" in f2's settings file does not change.

**Comment by sandy081** [comment] 2017-06-28 09:30
@weinand Yes, multi root aware update through API is not yet supported. Planned for next milestone.

**Comment by sandy081** [comment] 2017-07-25 11:16
Duplicate of #31358

**Closed by sandy081** 2017-07-25 11:16 UTC
Labels: multi-root, settings
