### ISSUE TITLE
Image preview: cannot drag tab to the side anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81948] opened 2019-10-04 09:50 UTC
Steps to Reproduce:

1. open an image (png)
2. try to drag the tab to the side to create a new group

=> 🐛 not possible

**Comment by mjbvz** [comment] 2019-10-04 18:06
Duplicate of #25854

Not so bad when this bug only effected the md preview but we should try fixing this in October now that webviews are also used for image previews

**Closed by mjbvz** 2019-10-04 18:06 UTC
Labels: bug
