### ISSUE TITLE
Arrange terminals as easily as the editors

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode#120717] opened 2021-04-07 09:39 UTC
In the most recent versions of Vim, you can split a screen into four panes like this:
<img width="1082" alt="Screenshot" src="https://user-images.githubusercontent.com/16488226/113844749-7dbb0400-979d-11eb-935e-86b564e813a9.png">
This I find the most efficient layout for most of the coding I do. But in VSCode I have to be satisfied with something like this: 
![Screenshot](https://user-images.githubusercontent.com/16488226/113845217-f15d1100-979d-11eb-9349-cd20c6a40803.png)
As you can see, there is no way to bring an editor below a terminal. This kills a whole lot of usable space.

**Comment by meganrogge** [comment] 2021-04-08 03:26
an extension on and duplicate of #10546

**Closed** 2021-04-08 03:34 UTC
Labels: *duplicate
