### ISSUE TITLE
NPM Scripts should be sorted

### ISSUE THREAD

**Issue by orokanasaru** [microsoft/vscode#90902] opened 2020-02-18 17:06 UTC
![image](https://user-images.githubusercontent.com/5751627/74758873-cd064400-522c-11ea-9393-3d30c22d6e8f.png)

I opened up a directory containing subdirectories 1, 2, 3, ..., and the NPM Scripts panel lists them out of order. The pane becomes pretty much unusable in 100+ project monorepos because there's no way to find the specific project you want to run scripts in.

The listed package.json files should be sorted by directory.

**Comment by alexr00** [comment] 2020-07-01 07:49
duplicate of https://github.com/microsoft/vscode/issues/92773

**Closed** 2020-07-01 07:49 UTC
Labels: *duplicate
