### ISSUE TITLE
Markdown files are saved as Objective-C when XCode is not installed on macOS

### ISSUE THREAD

**Issue by sirviot** [microsoft/vscode#229662] opened 2024-09-25 05:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: macOS Sequoia 15.0 (24A335), Darwin arm64 24.0.0

Steps to Reproduce:

1. Install VSCode on macOS 15.0 without XCode
2. Open VSCode
3. New Text File
4. Write Markdown syntax and save the file
5. Save As: `tiedosto.md`
7. Format: All Files
8. Click Save

Expectations: I have a file name `tiedosto.md`
What happened: I got a file named `tiedosto.md.m`

This occurred after I updated the OS to macOS 15.0. The XCode was not installed along with the update.
I cleared all my settings, removed all my extensions, and as a last resort deleted the VSCode entirely and reinstalled it. Nothing helped.

Then I reinstalled XCode from AppStore, and allowed me to save markdown files with the suffix `.md` correctly. I do not know if this is an issue with the operating system itself, of if there is something that can be done with VSCode.  

Here is a screenshot of a dialogue that I got when I tried to save the file a second time. It shows that I entered the name `tiedosto.md` but it tries to produce a file named `tiedosto.md.m`.
 
<img width="264" alt="Screenshot 2024-09-24 at 16 57 06" src="https://github.com/user-attachments/assets/581d9469-95f9-43f2-a262-2f93a7e2d128">

**Comment by IllusionMH** [comment] 2024-09-25 19:57
/duplicate of #229294

Unfortunately it looks like OS issue which affects not only VS Code.

**Closed** 2024-09-25 19:58 UTC
Labels: *duplicate
