### ISSUE TITLE
Filename changed when saving a file with '/' rather than creating a folder

### ISSUE THREAD

**Issue by jakubLangr** [microsoft/vscode#75159] opened 2019-06-09 20:39 UTC
Issue Type: <b>Bug</b>

Filename is changed from 'nodes/file.py' to 'nodes:file.py'. I understand this is against naming conventions, but prior versions of VS Code handled the intent appropriately and created a folder 'nodes' with 'file.py' rather than replacing the ":" with "/".

(On a separate note, _love_ the work you guys are doing. VS Code is now my main editor.)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.96GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
mermaid-markdown-syntax-highlighting|bpr|1.0.1
vscode-dash|dee|2.1.0
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.5.18875
sublime-keybindings|ms-|4.0.0
vscode-yaml|red|0.4.1
vscodeintellicode|Vis|1.1.6
vscode-mermaid-preview|vst|0.12.0
jinja|who|0.0.8

</details>

**Comment by isidorn** [comment] 2019-06-10 10:39
This works for me.
What are you doing differently than me?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

![rename](https://user-images.githubusercontent.com/1926584/59190358-cba05a00-8b7c-11e9-94db-125c1f4f9b5c.gif)

**Comment by jakubLangr** [comment] 2019-06-10 10:44
Wow. Thanks for the amazing response.

Sorry should have specified.

This happens when I do new file and try to save a new file with a slash.

Maybe this is not intended or allowed by OS?

Thanks!

Le lun. 10 juin 2019 à 11:41, Isidor Nikolic <notifications@github.com> a
écrit :

**Comment by isidorn** [comment] 2019-06-10 10:59
This also works for me. Please try to be more specific and try with vscode insiders as I have mentioend in my previous comment. Thank you

![newFile](https://user-images.githubusercontent.com/1926584/59191355-90535a80-8b7f-11e9-950c-a1d3d40b376e.gif)

**Comment by jakubLangr** [comment] 2019-06-10 16:40
Ok back on my laptop.

Exact steps:
1. File > New File
2. Save (CMD-S)
3. 'Save as' and in the contextual menu write `nodes/file.py` 
4. File is saved in the current directory as `nodes:file.py`

Tested on Insiders as well. Same problem.

**Comment by isidorn** [comment] 2019-06-11 08:01
This is not supported and this never worked. Sorry. 
That is a native electron dialog. So basically this will work when finder starts supporting it.

Closing as will not fix / as designed.

**Closed by isidorn** 2019-06-11 08:01 UTC
Labels: file-explorer, needs more info
