### ISSUE TITLE
Autocompleted JavaScript imports do not include file extension

### ISSUE THREAD

**Issue by coderpatsy** [Microsoft/vscode#51259] opened 2018-06-06 20:35 UTC
- VSCode Version: 1.24.0
- OS Version: Windows 8.1

This problem was first noticed a couple days ago on 1.23.1, but I waited for the new release.

Steps to Reproduce:

1. Have a module file with an export, say `export.js`
```js
export function exampleExport() { }
```
2. In another blank js file, start typing the name of your export and autocomplete it.
`exam` [tab] becomes
```js
import { exampleExport } from "./export";

exampleExport
```
Note that it it's trying to import from `"./export"`, not from `"./export.js"`. This breaks the import, at least in a browser context.

Does this issue occur when all extensions are disabled? Yes

**Comment by albertosantini** [comment] 2018-06-07 06:20
Duplicate of Microsoft/TypeScript#24493

**Comment by mjbvz** [comment] 2018-06-07 23:01
Moved upstream to get more feedback: https://github.com/Microsoft/TypeScript/issues/24779

**Closed by mjbvz** 2018-06-07 23:01 UTC
Labels: new release
