### ISSUE TITLE
No task color in terminal tab

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#153490] opened 2022-06-28 14:21 UTC
Testing https://github.com/microsoft/vscode/issues/153377

I added the following to the "Core - Build" task in this repo:
```json
			"icon": {
				"color": "terminal.ansiMagenta"
			}
```

The color shows in the "Run Task" quick pick, but not in the terminal tabs (I tried reloading, but still no color).

![image](https://user-images.githubusercontent.com/38270282/176202492-9e014e1a-5918-4f0c-8a7e-89cf949c7e1d.png)

**Comment by meganrogge** [comment] 2022-06-28 16:07
the color will only take effect the next time you run the task - don't think it's worth listening to the config and updating. we don't do that for existing terminals either when an icon or color is set for their profile
<img width="1291" alt="Screen Shot 2022-06-28 at 12 06 04 PM" src="https://user-images.githubusercontent.com/29464607/176227504-5ba64122-c4ee-4408-8506-8fdc790f1110.png">

**Comment by Tyriar** [comment] 2022-06-28 16:08
@meganrogge Alex mentioned `I tried reloading, but still no color`, I actually reproduced the icon and color not applying when testing https://github.com/microsoft/vscode/issues/153491 also

**Comment by Tyriar** [comment] 2022-06-28 16:14
I'm guessing it's just on tasks run via `dependsOn`? It works when running Core - Build explicitly but not ctrl+shift+b:
![Recording 2022-06-28 at 09 13 15](https://user-images.githubusercontent.com/2193314/176229151-25652223-233e-4a30-955d-77b7272b1640.gif)

**Comment by meganrogge** [comment] 2022-06-28 18:48
strange works w ctrl+shift+b for other default build tasks (xterm.js)
https://user-images.githubusercontent.com/29464607/176259274-588ac84b-c986-421e-931c-a02994cccfa4.mov

**Comment by meganrogge** [comment] 2022-06-28 18:52
works w ctrl+shift+b and the VS Code build task for me 

https://user-images.githubusercontent.com/29464607/176260051-72b3f938-5d01-4899-8774-3546626cf9c0.mov

**Comment by meganrogge** [comment] 2022-06-28 21:17
not sure why I can't reproduce it, but could be fixed by #153607

**Comment by alexr00** [comment] 2022-06-29 14:22
I can still repro this in the latest insiders.

**Comment by meganrogge** [comment] 2022-06-29 14:25
yes so can @Tyriar on Windows. we're going to debug

**Comment by meganrogge** [comment] 2022-06-29 14:29
are there any task load messages in the output channel?

**Comment by meganrogge** [comment] 2022-06-29 14:30
or any way the build task on windows is handled specially?

**Comment by meganrogge** [comment] 2022-06-29 14:35
maybe related https://github.com/microsoft/vscode/issues/153699

**Comment by alexr00** [comment] 2022-06-29 15:13
If there's an issue reading tasks from tasks.json then an error should be logged to the tasks output channel. The Run Build Task command shouldn't be handled any differently here, and I confirmed that this isn't build specific by making this keybinding:
```
    {
        "key": "ctrl+shift+alt+b",
        "command": "workbench.action.tasks.runTask",
        "args": "VS Code - Build"
    },
```

**Comment by meganrogge** [comment] 2022-06-29 18:52
to verify: set an icon for a dependency task

**Comment by alexr00** [comment] 2022-06-30 11:40
If I just set the icon color it now changes the icon away from the tools icon (its still the tools icon in the task quick pick):

![image](https://user-images.githubusercontent.com/38270282/176668640-be3bd27d-ad3c-42a7-bdca-adc37b40b5bb.png)

**Closed** 2022-06-30 15:18 UTC
Labels: bug, tasks, verification-found, windows
