### ISSUE TITLE
Source Control section blank, not showing changes

### ISSUE THREAD

**Issue by Fsenler** [microsoft/vscode#112563] opened 2020-12-15 13:37 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10 version 1909

Steps to Reproduce:

1. Have a repository cloned
2. make a change and see if the changes show up

Does this issue occur when all extensions are disabled?: Yes

Extensions used mostly being, salesforce CLI.

Thanks in advance!
FS

**Comment by stuartbrussell-intuit** [comment] 2020-12-17 00:38
Git integration is broken for me. "The folder currently open doesn't have a git repository. You can initialize...". I can go to the VSCode integrated terminal and use git just fine.

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

This looks like the same as https://github.com/microsoft/vscode/issues/112506

**Comment by Fsenler** [comment] 2021-01-11 16:18
Tried to do a merge via git and well...this happened...

![image](https://user-images.githubusercontent.com/76052135/104208618-75a62f00-540f-11eb-92ee-3777d29dc9fc.png)

**Comment by restjohn** [comment] 2021-01-12 17:51
I have had this problem under various merge conditions.  Here is a merge scenario that resulted in an empty change list in the SCM panel until I staged some specific changes, at which point the SCM view populated the change list.  

The screenshot below shows, after `git merge`, the SCM tab on the side bar has a badge with the count of changes, and  the repository node in the SCM view has the change count badge.  Note the chevron on the repository node with the changes is expanded, but no change list items are present under the repository node.
<img width="479" alt="empty scm change list" src="https://user-images.githubusercontent.com/1292665/104351784-0f7ae400-54c3-11eb-8338-9f8dae0218c1.png">
Below are the outputs from `git merge` and the subsequent `git status` that show the merge conditions.
```
% git merge develop
Auto-merging web-app/src/ng1/factories/map.service.js
CONFLICT (content): Merge conflict in web-app/src/ng1/factories/map.service.js
Auto-merging web-app/src/ng1/app.js
CONFLICT (content): Merge conflict in web-app/src/ng1/app.js
Auto-merging web-app/src/app/user/user-popup/user-popup.component.ts
CONFLICT (content): Merge conflict in web-app/src/app/user/user-popup/user-popup.component.ts
Auto-merging web-app/src/app/user/user-list/user-list-item.component.ts
Auto-merging web-app/src/app/observation/observation-view/observation-view.component.ts
CONFLICT (content): Merge conflict in web-app/src/app/observation/observation-view/observation-view.component.ts
Auto-merging web-app/src/app/observation/observation-popup/observation-popup.component.ts
CONFLICT (content): Merge conflict in web-app/src/app/observation/observation-popup/observation-popup.component.ts
Auto-merging web-app/src/app/observation/observation-list/observation-list-item.component.ts
CONFLICT (content): Merge conflict in web-app/src/app/observation/observation-list/observation-list-item.component.ts
Auto-merging web-app/src/app/map/map-popup.service.ts
Auto-merging web-app/src/app/map/map-popup.service.spec.ts
CONFLICT (content): Merge conflict in web-app/src/app/map/map-popup.service.spec.ts
CONFLICT (rename/add): Rename web-app/src/app/feed/feed.service.ts->web-app/src/app/feed-panel/feed-panel.service.ts in develop.  Added web-app/src/app/feed-panel/feed-panel.service.ts in HEAD
Auto-merging version of web-app/src/app/feed-panel/feed-panel.service.ts from web-app/src/app/feed/feed.service.ts
Auto-merging web-app/src/app/feed-panel/feed-panel.service.ts
CONFLICT (rename/add): Rename web-app/src/app/map/popup.service.spec.ts->web-app/src/app/feed-panel/feed-panel.service.spec.ts in develop.  Added web-app/src/app/feed-panel/feed-panel.service.spec.ts in HEAD
Auto-merging web-app/src/app/feed-panel/feed-panel.service.spec.ts
Auto-merging web-app/src/app/feed-panel/feed-panel.component.ts
CONFLICT (content): Merge conflict in web-app/src/app/feed-panel/feed-panel.component.ts
CONFLICT (rename/delete): web-app/src/app/feed/feed.component.html deleted in HEAD and renamed to web-app/src/app/feed-panel/feed-panel.component.html in develop. Version develop of web-app/src/app/feed-panel/feed-panel.component.html left in tree.
Auto-merging web-app/src/app/app.module.ts
CONFLICT (content): Merge conflict in web-app/src/app/app.module.ts
CONFLICT (rename/rename): Rename "web-app/src/app/feed/feed.component.spec.ts"->"plugins/image/web-app/projects/mage-image/src/lib/mage-image.component.spec.ts" in branch "HEAD" rename "web-app/src/app/feed/feed.component.spec.ts"->"web-app/src/app/feed-panel/feed-panel.component.spec.ts" in "develop"
Auto-merging plugins/image/web-app/projects/mage-image/src/lib/mage-image.component.spec.ts and web-app/src/app/feed-panel/feed-panel.component.spec.ts, both renamed from web-app/src/app/feed/feed.component.spec.ts
Auto-merging web-app/src/app/feed-panel/feed-panel.component.spec.ts
Automatic merge failed; fix conflicts and then commit the result.
```
```
% git status
On branch feeds
Your branch is ahead of 'origin/feeds' by 1 commit.
  (use "git push" to publish your local commits)
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)
Changes to be committed:
        deleted:    web-app/src/app/feed/feed.service.spec.ts
        deleted:    web-app/src/app/feed/feed.service.ts
        renamed:    web-app/src/app/map/popup.service.ts -> web-app/src/app/map/map-popup.service.ts
        deleted:    web-app/src/app/map/popup.service.spec.ts
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        added by us:     plugins/image/web-app/projects/mage-image/src/lib/mage-image.component.spec.ts
        both modified:   web-app/src/app/app.module.ts
        added by them:   web-app/src/app/feed-panel/feed-panel.component.html
        both added:      web-app/src/app/feed-panel/feed-panel.component.spec.ts
        both modified:   web-app/src/app/feed-panel/feed-panel.component.ts
        both added:      web-app/src/app/feed-panel/feed-panel.service.spec.ts
        both added:      web-app/src/app/feed-panel/feed-panel.service.ts
        both deleted:    web-app/src/app/feed/feed.component.spec.ts
        both modified:   web-app/src/app/map/map-popup.service.spec.ts
        both modified:   web-app/src/app/observation/observation-list/observation-list-item.component.ts
        both modified:   web-app/src/app/observation/observation-popup/observation-popup.component.ts
        both modified:   web-app/src/app/observation/observation-view/observation-view.component.ts
        both modified:   web-app/src/app/user/user-popup/user-popup.component.ts
        both modified:   web-app/src/ng1/app.js
        both modified:   web-app/src/ng1/factories/map.service.js
```
Here are the commands to stage the files that made the SCM view populate the change list.
```
% git rm plugins/image/web-app/projects/mage-image/src/lib/mage-image.component.spec.ts
rm 'plugins/image/web-app/projects/mage-image/src/lib/mage-image.component.spec.ts'
% git add web-app/src/app/feed-panel/feed-panel.component.html
% git rm web-app/src/app/feed/feed.component.spec.ts
rm 'web-app/src/app/feed/feed.component.spec.ts'
```
In this case, to make the SCM change list appear, I had to stage files that were
1. deleted on the incoming branch.
2. added on both branches.
3. deleted on both branches.

**Comment by eamodio** [comment] 2021-01-12 20:52
Duplicate of https://github.com/microsoft/vscode/issues/112537

**Closed by eamodio** 2021-01-12 20:52 UTC
