### ISSUE TITLE
Error: Invalid group provided

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71143] opened 2019-03-26 09:34 UTC
Refs: https://github.com/Microsoft/vscode/issues/71049

Start the cat example and get this in the console right away:

```
 ERR Invalid group provided: Error: Invalid group provided
    at Object.t.editorGroupToViewColumn (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2841:274)
    at k.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3588:178)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at e.doEmitActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4613:364)
    at e.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4613:160)
    at t.push.e.onDidGroupChange.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4613:456)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:416)
    at t.editorControl.openEditor.then.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5026:483)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mjbvz** [comment] 2019-03-28 03:11
Duplicate of #71107

**Closed by mjbvz** 2019-03-28 03:11 UTC
Labels: webview
