### ISSUE TITLE
every time I do anything in the Source Control panel, it resets all tree views (very annoying)

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#116721] opened 2021-02-15 18:48 UTC
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-19T14:42:39.893Z
Electron: 9.4.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.85-1-MANJARO

**Steps to Reproduce:**

In the video, notice every time I add a change, or any time source control refreshes, the tree view is reset.

https://user-images.githubusercontent.com/297678/107983571-e98da700-6f7a-11eb-91a8-52784e614de5.mp4

It seems that any time the git state refreshes, the source control tree auto-expands everything (I assume it probably replaces the whole UI with a new one).

As you can imagine, this is very annoying.

**Does this issue occur when all extensions are disabled?:** Yes, the same exact problem happens without any extensions.

**Comment by trusktr** [comment] 2021-02-15 18:49
This started happening in a fairly recent update.

**Comment by trusktr** [comment] 2021-02-15 20:19
Updated the OP. The issue also happens without extensions enabled.

**Comment by IllusionMH** [comment] 2021-02-15 20:35
@trusktr have you tried latest Stable version 1.53.2 and Insiders (https://code.visualstudio.com/insiders/)?

However I don't see this behavior on Windows with Insiders, but I don't have large changes tree ATM.

**Comment by alexisfrjp** [comment] 2021-04-07 02:50
It seems that issue is very recurrent here... there are tens of issues raising it! After years, this is still not solved.

![image](https://user-images.githubusercontent.com/6713988/113803271-29ad2100-9797-11eb-8084-6cebbba7ed8e.png)

Can't update VSCode, 1.52.1 is the last version that supports Centos 7.

**Comment by eamodio** [comment] 2021-04-14 05:10
I can't reproduce this in the latest version of VS Code. I'm going to close this issue. If it can be reproduced on the most recent version of VS Code we can re-open this.

**Closed by eamodio** 2021-04-14 05:10 UTC

**Comment by alexisfrjp** [comment] 2021-04-14 05:30
The centos 7 repository shouldn't contain the new versions of VSCode then. The VSCode's versions not supported in Centos 7 shouldn't be available.
