### ISSUE TITLE
Remapping of escape character not handled (Dockerfile language)

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#82985] opened 2019-10-21 14:06 UTC
From @paulcallen original issue here: https://github.com/microsoft/vscode-docker/issues/245

> put this at the top of a docker file: # escape=`
>
> and it remaps the escape character such that windows file paths can exist as c:\foo. Really nice feature.
Unfortunately this plug-in does not recognize this and as a result it thinks \f is an invalid escape sequence.
>
> ![image](https://user-images.githubusercontent.com/36966225/67212453-62faa100-f3ea-11e9-80f5-4914e96d87bf.png)

**Comment by alexr00** [comment] 2019-10-21 15:30
I don't think this is possible with a textmate grammar. This would require some other tokenization engine, so duplicate of https://github.com/microsoft/vscode/issues/77140

**Closed by alexr00** 2019-10-21 15:30 UTC
