### ISSUE TITLE
Broken TypeScript hover 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18511] opened 2017-01-13 11:45 UTC
* open vscode.d.ts, go to line 3679
* hover over `setStatusBarMessage`
* 🐛 the message show show 'Note' in italic but shows '*Note', debug and see that the provider returns an invalid string

![screen shot 2017-01-13 at 12 44 25](https://cloud.githubusercontent.com/assets/1794099/21928944/181a0776-d98e-11e6-8062-5da9dce7739c.png)

![screen shot 2017-01-13 at 12 43 28](https://cloud.githubusercontent.com/assets/1794099/21928948/1b54a1d0-d98e-11e6-940b-73bd6e833bfe.png)

**Comment by mjbvz** [comment] 2017-01-13 22:10
I'm unable to repo this in insiders or building from master:

![screen shot 2017-01-13 at 2 08 37 pm](https://cloud.githubusercontent.com/assets/12821956/21947382/ced19816-d999-11e6-9324-7ace74b7ff24.png)

@jrieken Were any additional steps required to reproduce this issue?

**Comment by jrieken** [comment] 2017-01-14 08:18
Maybe the use of TypeScript 2.1.4

**Comment by mjbvz** [comment] 2017-01-17 20:55
Thanks @jrieken. I'm able to repo using TS2.1.4, but it looks like TS 2.1.5 fixed this. I've updated the bundled version of TS to 2.1.5, and also updated our VSCode build to use TS2.1.5

Closing as upstream.

**Closed by mjbvz** 2017-01-17 20:55 UTC
Labels: bug, javascript, typescript, upstream
