### ISSUE TITLE
Internet Local and SVG images not shown in VSCode Insiders on Linux

### ISSUE THREAD

**Issue by gusbemacbe** [Microsoft/vscode#67967] opened 2019-02-06 08:31 UTC
- VSCode Version: 1.31.0-Insiders
- OS Version: Manjaro Linux 18.0 Illyria and Linux Kernel 4.14.94-1

**Observation:** I refer to https://github.com/Microsoft/vscode/issues/45476 and to https://github.com/Microsoft/vscode/issues/48809, but this bug is not fixed yet. 

**Steps to Reproduce:**

1. I use both non-local and local SVG images in Markdown:

```markdown

<! -- Based on Shields -->
<p align="center">
  <img alt="apps" src="https://img.shields.io/badge/apps_icons-5200%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
  <img alt="actions" src="https://img.shields.io/badge/actions_icons-1800%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
  <img alt="devices" src="https://img.shields.io/badge/devices_icons-150%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
  <img alt="mimetypes" src="https://img.shields.io/badge/mimetypes_icons-1100%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
  <img alt="panel" src="https://img.shields.io/badge/panel_icons-1900%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
  <img alt="places" src="https://img.shields.io/badge/places_icons-1300%2B-1AD6AB.svg?style=plastic?&colorA=329DB6"/>
</p>

|  Icon name   |                   Default                   |                      Alt 1                      | Alt 2 |
| :----------: | :-----------------------------------------: | :---------------------------------------------: | :---: |
| sublime-text | ![default](Suru++/apps/64/sublime-text.svg) | ![default](Suru++/apps/64/sublime-text-alt.svg) |   -   |
```

2. I activated the preview and selected to allow all insecure contents and also to disable.
3. Both non-local and local SVG images are not loaded.

**Does this issue occur when all extensions are disabled?**

Yes

**Comment by mjbvz** [comment] 2019-02-07 21:47
Duplicate of #68033

**Closed by mjbvz** 2019-02-07 21:47 UTC
Labels: *duplicate
