### ISSUE TITLE
Formatter & IntelliSense stops working!

### ISSUE THREAD

**Issue by BardiaN** [Microsoft/vscode#43427] opened 2018-02-11 14:28 UTC
Greetings!
At first, I should say thanks for this cool IDE, I'm a big fan of VS Code.
It's been a while that I've been trying to find out how this bug happens and today I found it out finally!!
- Symptom: Visual Studio Code formatter (Alt + Shift + F) stops working and IntelliSense also gets stuck in loading!
- Development Stack: JS (Nodejs, React & etc.)
- What causes this? An invalid IntelliSense request (using Ctrl+Space) causes this bug, like for example when you want to import something on top of the file and in the string part you close the already opened intelliSense and then you use "CTRL +Space" to reopen it. So it shows you a loading IntelliSense menu and after this, formatting & other IntelliSense stop working!

**Comment by TheDrunkenLordOfEverything** [comment] 2018-02-12 20:20
FWIW, same thing happening here--never noticed it until the 1.20 release. It will work until some unknown (to me) trigger occurs, then Intellisense doesn't work and problem highlighting is 'off'...partial underlines and nonsensical errors (for example: make a typo in initial typing of 'require' as 'rewuire', problem is underlined, fix typo...underline remains with same message). 

My current workflow is to hit my 'restart IDE' button combo a lot. 

Not seeing anything incredibly useful in the various logs, but I could definitely be looking in the wrong places.

**Comment by mjbvz** [comment] 2018-02-12 22:33
@BardiaN Can you please:

1. Set `"typescript.tsserver.trace": "verbose"` in your user settings.
1. Restart code and reproduce the issue
1. Open the output panel and go to the `typescript` section.

Look for any errors or stack traces in the output. If you share the output I can also take a look

**Comment by lagerone** [comment] 2018-02-13 15:26
@mjbvz I have the same issue as @BardiaN 

From my output panel when the crash happened:

```
[Trace  - 3:12:56 PM] TypeScript Service: canceled request with sequence number 2954
[Trace  - 3:13:00 PM] TypeScript Service: trying to cancel ongoing request with sequence number 2951
[Trace  - 3:13:00 PM] Sending request: definition (2952). Response expected: yes. Current queue length: 2
Arguments: {
    "file": "c:/some-dir/some-file.js",
    "line": 10,
    "offset": 9
}
[Trace  - 3:13:01 PM] TypeScript Service: canceled request with sequence number 2957
[Trace  - 3:13:01 PM] TypeScript Service: canceled request with sequence number 2958
[Trace  - 3:13:03 PM] TypeScript Service: canceled request with sequence number 2959
[Trace  - 3:13:38 PM] TypeScript Service: canceled request with sequence number 2962
[Trace  - 3:13:39 PM] TypeScript Service: canceled request with sequence number 2963
[Trace  - 3:13:39 PM] TypeScript Service: canceled request with sequence number 2964
[Trace  - 3:13:40 PM] TypeScript Service: canceled request with sequence number 2965
[Trace  - 3:13:44 PM] TypeScript Service: canceled request with sequence number 2967
[Trace  - 3:13:51 PM] TypeScript Service: canceled request with sequence number 2971
[Trace  - 3:13:52 PM] TypeScript Service: canceled request with sequence number 2972
[Trace  - 3:14:02 PM] TypeScript Service: canceled request with sequence number 2977
...
```

**Comment by BardiaN** [comment] 2018-02-13 16:10
@mjbvz Sorry for the late answer. Actually, I did what you asked but nothing happened. I mean there is no "TypeScript" tab in my output window and I should mention that I'm developing JS, not TS if it matters.
It's a React js project and I already disabled all extensions and tested it out, no changes.

**Comment by mjbvz** [comment] 2018-02-14 19:45
@BardiaN Make sure you've added `"typescript.tsserver.trace": "verbose"` to your user settings and have saved the user settings file. Try reloading vscode after this as well to make sure you are staring from a clean state

**Comment by benhamlin** [comment] 2018-02-14 22:22
Same issue here. tsserver trace:
```

[Trace  - 2:12:18 PM] Response received: formatonkey (137). Request took 6214 ms. Success: true 
Result: []
[Trace  - 2:12:18 PM] Sending request: geterr (138). Response expected: no. Current queue length: 16
Arguments: {
    "delay": 0,
    "files": [
        "c:/dir/file1.js",
        "c:/dir/file1.test.js",
        "c:/dir/file2.js"
    ]
}
[Trace  - 2:12:18 PM] Sending request: getApplicableRefactors (140). Response expected: yes. Current queue length: 15
Arguments: {
    "file": "c:/dir/file.js",
    "startLine": 7,
    "startOffset": 9,
    "endLine": 7,
    "endOffset": 23
}
[Trace  - 2:12:24 PM] TypeScript Service: canceled request with sequence number 143
[Trace  - 2:12:42 PM] TypeScript Service: canceled request with sequence number 190
[Trace  - 2:12:42 PM] TypeScript Service: canceled request with sequence number 191
[Trace  - 2:13:05 PM] TypeScript Service: canceled request with sequence number 192
[Trace  - 2:13:09 PM] TypeScript Service: canceled request with sequence number 193
[Trace  - 2:13:09 PM] TypeScript Service: canceled request with sequence number 194
[Trace  - 2:13:11 PM] TypeScript Service: canceled request with sequence number 195
[Trace  - 2:13:19 PM] TypeScript Service: canceled request with sequence number 196
[Trace  - 2:13:20 PM] TypeScript Service: canceled request with sequence number 197
[Trace  - 2:13:21 PM] TypeScript Service: canceled request with sequence number 198
[Trace  - 2:13:23 PM] TypeScript Service: canceled request with sequence number 203
[Trace  - 2:13:23 PM] TypeScript Service: canceled request with sequence number 210
[Trace  - 2:13:28 PM] TypeScript Service: canceled request with sequence number 221
(...snip)
```

**Comment by Yonsh** [comment] 2018-02-27 05:55
Same problem, seems to be happening (few seconds) after any import path suggestion.
For now I'm using the setting `"typescript.quickSuggestionsForPaths": false` to avoid this issue.

**Comment by manu1222** [comment] 2018-03-02 07:20
Same problem here, on Windows 8.1 but never got it on Windows 7. I have to restart VS Code.

**Comment by Wedvich** [comment] 2018-03-13 10:03
Same issue - haven't been able to pin the cause down to anything in particular, but it happens randomly after using VSCode for a while (anything from 2 to 20 minutes):

```
[Trace  - 10:54:47] Sending request: quickinfo (980). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Repos/(...snip...)/src/js/authentication/context.js",
    "line": 3,
    "offset": 11
}
[Trace  - 10:54:47] TypeScript Service: trying to cancel ongoing request with sequence number 980
[Trace  - 10:54:47] Sending request: occurrences (981). Response expected: yes. Current queue length: 1
Arguments: {
    "file": "c:/Repos/(...snip...)/src/js/authentication/context.js",
    "line": 3,
    "offset": 11
}
[Trace  - 10:54:52] TypeScript Service: canceled request with sequence number 985
[Trace  - 10:54:53] TypeScript Service: trying to cancel ongoing request with sequence number 981
[Trace  - 10:54:53] Sending request: getApplicableRefactors (982). Response expected: yes. Current queue length: 4
Arguments: {
    "file": "c:/Repos/(...snip...)/src/js/authentication/context.js",
    "startLine": 3,
    "startOffset": 10,
    "endLine": 3,
    "endOffset": 28
}
[Trace  - 10:54:53] TypeScript Service: canceled request with sequence number 986
[Trace  - 10:54:53] TypeScript Service: canceled request with sequence number 988
[Trace  - 10:54:53] TypeScript Service: canceled request with sequence number 987
[Trace  - 10:54:55] TypeScript Service: canceled request with sequence number 992
[Trace  - 10:54:55] TypeScript Service: canceled request with sequence number 993
[Trace  - 10:54:57] TypeScript Service: canceled request with sequence number 999
[Trace  - 10:55:05] TypeScript Service: canceled request with sequence number 1017
[Trace  - 10:55:07] TypeScript Service: canceled request with sequence number 1018
[Trace  - 10:55:10] TypeScript Service: canceled request with sequence number 1019
[Trace  - 10:55:10] TypeScript Service: canceled request with sequence number 1020
[Trace  - 10:55:12] TypeScript Service: canceled request with sequence number 1021

etc...
```

This is with the `--disable-extensions` flag.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|31.85GB (21.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Wedvich** [comment] 2018-03-13 16:25
Setting `"typescript.quickSuggestionsForPaths": false` like @Yonsh suggested seems to eliminate the issue for me as well - after making that change, it hasn't occurred again in the past 5 hours.

**Comment by StickyCube** [comment] 2018-04-16 16:33
I can reliably reproduce this with the following steps:

```
  my-project/
  ├─ .vscode/
  |  └─ settings.json
  ├─ node_modules/
  |  └─ redux/ 
  └─ index.js
```

1. With the following settings and redux installed. Hitting ctrl+space correctly suggests exports from 'redux'

##### my-project/.vscode/settings.json
```json
{
  "typescript.quickSuggestionsForPaths": true,
  "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": false
  }
}
```

##### my-project/index.js
```javascript
// Hitting ctrl+space works here
import {compose} from 'redux';
```

2. Save file (not sure if this is required) and add another import for an unknown package

##### my-project/index.js
```javascript
import {compose} from 'redux';
import {} from 'module-that-doesnt-exist';
// Hitting ctrl+space here pops up with Loading...
```

3. At this stage, hitting ctrl+space anywhere is stuck. It always displays "Loading...". The following is the output from the Typescript output panel:

![image](https://user-images.githubusercontent.com/4573741/38822596-d7e45dc4-419b-11e8-957d-ab0986570f1f.png)


4. If the quickSuggestions settings are changed, it works flawlessly:

##### my-project/.vscode/settings.json
```json
{
  "editor.quickSuggestions": {
      "other": false,
      "comments": false,
      "strings": false
  }
}
```

**Comment by mjbvz** [comment] 2018-04-16 23:33
Please try the latest vscode insiders release. This could be https://github.com/Microsoft/TypeScript/issues/23183 which should be fixed in insiders

**Comment by shaun-sweet** [comment] 2018-04-17 01:01
nope.  Using insiders on ubuntu with no extensions... intellisense not working.

**Comment by mjbvz** [comment] 2018-04-17 01:09
Can everyone who is not @BardiaN please open new, separate issues for this. Issues like this one often have different root causes, so separate threads per user makes tracking them much easier 

@BardiaN + others, if you still see this issue in vscode insiders, please try collecting the tsserver log:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Open the output panel and go to the  `TypeScript` section. At the very top, look for a message that says: `TSServer log file:`  followed by the path to the log file. Open that log file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by byteskw** [comment] 2018-04-18 09:39
me to, im using react native for my vscode, after 2 minutes - 10 minutes always infinite loading my intellisense vscode,

please fix this

**Comment by mjbvz** [comment] 2018-04-27 20:46
@hugmanrique  Please open a new issue for this.

@BardiaN Did you have a chance to try this in VS Code insiders and collect the TS Server logs?

**Closed** 2018-05-04 22:43 UTC
Labels: javascript, needs more info
