### ISSUE TITLE
view in browser option

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [Microsoft/vscode#29083] opened 2017-06-20 05:40 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.10.0|;

---

why there is no option for view in browser for web pages ex. html ?

**Comment by RobertBColton** [comment] 2017-06-20 13:33
I believe this is a duplicate of #15928

**Comment by mjbvz** [comment] 2017-11-03 01:30
Duplicate of #15928

**Closed by mjbvz** 2017-11-03 01:30 UTC
Labels: duplicate, extension-candidate, feature-request, html
