### ISSUE TITLE
inline values: debugger UI holds onto some state which confuses future debug sessions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19361] opened 2017-01-25 13:39 UTC
while debugging #18670:

- use this program: `var x = 123;`
- set breakpoint on that line and then start debugging
- step over the line

Observe: inline value is shown for 'x'

- rename variable x to 'x1'
- start debugging
- step over the line

Observe: no inline values are shown for 'x1'

- reload window
- start debugging
- step over the line

Observe: inline values are shown for 'x1'

It seems that the VS Code UI holds onto some state which confuses future debug sessions

**Comment by isidorn** [comment] 2017-01-25 13:41
Yeah, this feels like a duplicate of #19212 which I plan to investigate now

**Closed** 2017-01-25 14:43 UTC
Labels: bug, debug, duplicate
