### ISSUE TITLE
Context menu in file.

### ISSUE THREAD

**Issue by luclegen** [microsoft/vscode#132604] opened 2021-09-08 02:32 UTC
Issue Type: <b>Bug</b>

I click right in code then the context menu show is wrong.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz (4 x 3201)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|11.57GB (4.43GB free)|
|Process Argv|/home/l/.workspaces/Java//.settings/Java.code-workspace --crash-reporter-id 2d9cef2b-cb98-4b96-b07f-e4142f7210fb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
ng-template|Ang|12.2.0
vscode-color|ans|0.4.5
intellij-parameter-hints|Bob|0.3.0
insert-unicode|bru|0.12.3
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
vscode-svgviewer|css|2.0.0
vscode-office|cwe|2.4.0
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.22
pipenv-scripts|Fed|1.0.3
vscode-mysql|for|0.4.1
vscode-drawio|hed|1.6.2
vscode-env|Iro|0.1.0
Angular2|joh|12.0.0
restructuredtext|lex|165.0.0
mongodb-vscode|mon|0.6.10
vscode-docker|ms-|1.16.1
mssql|ms-|1.10.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.6.1
material-icon-theme|PKi|4.10.0
java|red|0.81.0
sass-indented|syl|1.8.18
tabnine-vscode|Tab|3.4.26
pdf|tom|1.1.0
simple-rst|tro|1.5.0
autocomplate-shell|tru|0.1.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0
generic-pseudocode|Wil|1.4.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by luclegen** [comment] 2021-09-12 14:25
Please watch my Video at: https://youtu.be/rxnjKquM8AI. Thanks!

https://user-images.githubusercontent.com/34211672/132991421-a6cfcadd-7fb1-4550-b2c6-5990d3a0d046.mp4

**Comment by sbatten** [comment] 2021-09-13 17:35
dupe of https://github.com/microsoft/vscode/issues/113175

**Closed by sbatten** 2021-09-13 17:35 UTC
