### ISSUE TITLE
Support for chunk reading / writing in vscode.fs

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#102000] opened 2020-07-09 13:52 UTC
Currently there is support within VS Code's extension APIs to read and write files in chunks when utilizing a custom fileSystemProvider, but this same feature isn't mirrored to VS Code's exposed file system. This becomes especially useful with the advent of custom editors which will be reading and writing files as it loads them into the editor. For example, the HexEditor extension when saving even a couple of edits to a 1gb file must delete the whole file from disk and rewrite it causing the editor to lock up. Extensions shouldn't have to rely on Node APIs as this gets tricky with things like remote.

**Comment by jrieken** [comment] 2020-07-09 14:06
related https://github.com/microsoft/vscode/issues/84515

**Comment by jrieken** [comment] 2020-07-09 14:29
actually a dupe of https://github.com/microsoft/vscode/issues/84515

**Closed by jrieken** 2020-07-09 14:29 UTC
Labels: api-proposal, feature-request, file-io

**Comment by jrieken** [comment] 2020-07-16 09:06
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aapi-proposal+label%3Afeature-request+label%3Afile-io
