### ISSUE TITLE
Out of Memory exception opening a workspace

### ISSUE THREAD

**Issue by brunocasado** [Microsoft/vscode#10805] opened 2016-08-22 17:29 UTC
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04.1 LTS 64-bit

Steps to reproduce the issues:

After some hours in current project

1. in current project change folder.: file > open folder
2. change project
3. see you vscode slow down and get some errors

![image](https://cloud.githubusercontent.com/assets/1511338/17864524/c9da63f6-6874-11e6-9299-771b98e85236.png)

To solve: exit completely and start vscode again,.

**Comment by bpasero** [comment] 2016-08-23 04:47
@brunocasado looks like something in that folder causes our extension host to crash. Would you be able to share this folder with us?

**Comment by brunocasado** [comment] 2016-08-23 13:39
@bpasero  can be a image? or?

**Comment by bpasero** [comment] 2016-08-23 14:04
@brunocasado I meant the contents of the folder if possible?

**Comment by brunocasado** [comment] 2016-08-23 14:19
Removed:

./assets/bower_components
./node_modules

if you want this folders let me know

[list.txt](https://github.com/Microsoft/vscode/files/432627/list.txt)

**Comment by bpasero** [comment] 2016-08-23 14:33
@brunocasado great, what are the steps to get these 2 folders back?

**Comment by brunocasado** [comment] 2016-08-23 14:36
not exclude them hehe

[list.txt](https://github.com/Microsoft/vscode/files/432675/list.txt)

**Comment by bpasero** [comment] 2016-08-23 14:50
Sorry, without being able to reproduce on our end we will have a hard time finding out what the issue is.

Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by brunocasado** [comment] 2016-08-23 16:43
@bpasero  

I'll try.

**Comment by brunocasado** [comment] 2016-08-24 00:13
@bpasero even with disabled-extensions error occurs.

Look the out in terminal. See if this have any relation.

`
bruno@bruno-Latitude-3540:~/projects$ nvm use node && code --disable-extensions transactionals
Now using node v4.2.6 (npm v2.14.12)
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

<--- Last few GCs --->

   10244 ms: Mark-sweep 1157.1 (1265.6) -> 1157.1 (1265.6) MB, 7.2 / 0 ms (+ 6.5 ms in 323 steps since start of marking, biggest step 0.6 ms) [allocation failure] [GC in old space requested].
   10257 ms: Mark-sweep 1157.1 (1265.6) -> 1157.0 (1271.6) MB, 13.3 / 0 ms [allocation failure] [GC in old space requested].
   10273 ms: Mark-sweep 1157.0 (1271.6) -> 1157.0 (1265.6) MB, 15.6 / 0 ms [last resort gc].
   10288 ms: Mark-sweep 1157.0 (1265.6) -> 1157.0 (1258.6) MB, 15.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x21d802ccba81 <JS Object>
    1: Join(aka Join) [native array.js:187] [pc=0xba38808fb2f] (this=0x21d802c04189 <undefined>,y=0x38de29adc8d1 <JS Array[2]>,z=2,P=0x12e44024489 <String[1]: ,>,O=0x21d802cb6281 <JS Function ConvertToString (SharedFunctionInfo 0x21d802c50041)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:364] [pc=0xba38808221b] (this=0x21d802c04189 <undefined>,P=0x12e44024489 <String[1]: ,>,y=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
`

**Comment by bpasero** [comment] 2016-08-24 05:12
@brunocasado thanks, this is useful information. So we run out of memory opening that folder in Code.

Is that folder a git repository that you checked out from GitHub or a project generated with Yeoman?

**Comment by brunocasado** [comment] 2016-08-24 13:22
@bpasero  from azure git.

**Comment by bpasero** [comment] 2016-08-24 13:42
@brunocasado can you share the git repository URL. is it publicly accessible?

**Comment by brunocasado** [comment] 2016-08-24 13:49
unfortunately its not possible.

**Comment by dbaeumer** [comment] 2016-08-30 09:34
@alexandrudima assigning to you. May be we could have some tracing options for the extension host to better track down these issues.

**Comment by alexandrudima** [comment] 2016-08-30 09:54
@brunocasado 
* It would be useful for me to understand which process runs out of memory: the renderer process or the extension host process or perhaps some other process we spawn. From the file list this looks like a small workspace, so I am thinking the file watcher process should not have any problems with it.
* Initially you state the crash occurs after some hours in a certain folder. Is it the case that the memory consumption is growing and growing and at one point it runs out of memory or is it that as soon as you open this specific folder / a specific file VSCode crashes with OOM?
* Do you regularly close open editors or do you keep the open indefinitely -- the undo history of each one of those is currently kept in memory.

**Comment by brunocasado** [comment] 2016-08-30 13:32
@alexandrudima yes its a small workspace.

This problems after some minutes (not hours). Apparently this problem not occurs because specific folder of project.

If i close vscode this problem not occur, but if i change project (file > open folder) folder yes. generally I keep vscode open for hours.

The vscode open, i see my code, but vscode starts getting slow. The highlight sintax broken and vscode show the image above.

Today i'll clean my linux installation because i experienced some strange issues in my OS ( slowness ).

Maybe this can solve this problem... or maybe not

**Comment by alexandrudima** [comment] 2016-08-30 13:37
Thank you for the additional information. At this point, I am not sure what could be the root cause of vscode eating up so much memory on your machine. If this reproduces for you on any workspace (any folder), then it might be an installation issue (config options, extensions) or an env issue (something about the OS). 

To narrow down the possible root causes, I can recommend to try running the insider version for a couple hours and without installing too many extensions / keeping configuration changes to a minimum from https://code.visualstudio.com/insiders - I would also recommend to get the zip version to be sure it is not some installer related issue.

Thanks for bearing with us in figuring out what's causing this.

**Comment by brunocasado** [comment] 2016-08-31 14:06
Well,

How i said, my linux have issues with slowness but after cleaned (format)
and reinstalled ubuntu 16.04 apparently the issues is over.

Vscode is very fast, it's much more than before.

I think this problem occurred because my linux =/

**Comment by alexandrudima** [comment] 2016-08-31 15:40
@brunocasado Thank you for following up on this! I'll close this issue for now, please feel free to open a new one if you notice crashes or slowness.

**Closed by alexandrudima** 2016-08-31 15:40 UTC
Labels: extension-host, needs more info
