### ISSUE TITLE
Command Prompt `getmac` run every time I launch VSCode on Windows 10

### ISSUE THREAD

**Issue by macintacos** [Microsoft/vscode#26484] opened 2017-05-11 19:44 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Currently every time when I open VS Code, the `getmac` command is run on command prompt (regardless of whether or not that application is open). I'd like to either remove this functionality or just stop the window from coming up, since I have to manually dismiss it every time I open the application.

Not entirely how/why it started happening, as I noticed it a while ago but never got around to reporting it. Is this a normal occurance? This doesn't happen to me on the Mac version of the app.

Steps to Reproduce:

1. Launch VS Code
2. Command prompt opens (in my case, ConEmu, since I have that overriding the default command prompt) and runs `getmac`.

**Comment by egamma** [comment] 2017-05-12 06:59
@macintacos 

>is run on command prompt

Can you clarify what exactly you mean by command prompt? Does this happen in the integrated terminal of VS Code or does it happen in the command prompt where you launched vscode. Can you please add a screenshot.

**Comment by egamma** [comment] 2017-05-13 08:10
@macintacos ping?

**Comment by macintacos** [comment] 2017-05-13 19:55
Sorry about that, wasn't around a computer for a bit that could reproduce it.

Gif below explaining the issue. It's not when I'm launching from the command prompt itself, even just opening something from the File Explorer will do it. Happens whenever I open from a cold start, doesn't happen if VS Code is already open.

GIF: https://www.dropbox.com/s/au8lyqy8i569jm5/vscode-getmac-vids.gif?dl=0

**Comment by egamma** [comment] 2017-05-14 06:50
@macintacos thanks the video helps a lot. VS Code makes use of the `getmac` utility, but this is not the expected behaviour.

As a workaround you can try to disable the telemetry collection: https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting

**Comment by jrieken** [comment] 2017-05-15 07:47
wow - that is interesting

**Comment by jrieken** [comment] 2017-05-15 07:49
@chrmarti I remember you made some changes how the machine ids are computed. Do we still need the `getmac` module/command? I am hoping we don't and to solve this problem indirectly (apart from others)

**Comment by macintacos** [comment] 2017-05-15 14:27
@egamma I don't mind giving the telemetry, but this works as a workaround. If this is addressed I'll definitely turn it back on.

**Comment by chrmarti** [comment] 2017-05-15 14:35
@jrieken The computation itself did not change.

**Comment by jrieken** [comment] 2017-05-15 15:20
Can we change it @chrmarti? Apart from this issue it's really not good a solution...

@macintacos On the issue: you are using conemu, right? @joaomoreno suggested that there is a setting that always run conemu with cmd.exe. can you check

**Comment by macintacos** [comment] 2017-05-15 15:41
@jrieken yes that setting is available. Currently everything (as far as I know) runs through ConEmu on my machine, rather than the normal command prompt.

**Comment by chrmarti** [comment] 2017-05-15 16:10
@jrieken Sure, go ahead. All we need is some sort of id that is stable across stable/insiders releases and reinstalls of the application on all platforms. Also, existing ids should not change, that would break many reports. /cc @ramya-rao-a

**Comment by ramya-rao-a** [comment] 2017-05-15 22:50
> Can we change it?

Change it to what? Didnt we try this in #16151?

**Comment by jrieken** [comment] 2017-05-16 10:10
There would be this which I suspect is much more reliable: https://github.com/automation-stack/node-machine-id

> Also, existing ids should not change, that would break many reports

Well, I guess that's why we store them. However, if we starting using a different technique to generate them, machine ids will change after a reinstall. Tho, I suspect this happens with `getmac` as well.


fyi @joaomoreno this is most likely caused by this: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L271 because for telemetry we store the machine id and read it from there subsequently.

**Comment by chrmarti** [comment] 2017-05-16 14:02
@jrieken Sounds good. We keep the user data across reinstalls, so the old id will be kept. There will be a few users with the old id in stable and the new id in insiders (and potentially the other way around), but that shouldn't be a significant number.

**Comment by joaomoreno** [comment] 2017-05-17 10:23
@jrieken 

> fyi @joaomoreno this is most likely caused by

What is most likely caused?

**Comment by jrieken** [comment] 2017-05-17 11:48
@joaomoreno Your code *always* gets to call `getmac` whereas the telemetry logic makes this run only once (unless you nuke local storage). So *this* issue, conemu always popping up, is most likely caused by the http-header setting

**Comment by joaomoreno** [comment] 2017-05-19 09:23
I don't mind dropping it, in favour of a UUIDv4. The Marketplace people even asked for it.

**Comment by jrieken** [comment] 2017-05-19 09:49
As a as stable thing or just per session?

**Comment by joaomoreno** [comment] 2017-05-19 13:10
Stable.

**Comment by chrmarti** [comment] 2017-05-19 15:08
https://github.com/automation-stack/node-machine-id would be nice because it is the same for stable/insiders and also when the user uses multiple user data dirs. What are the advantages of UUIDv4?

**Comment by jrieken** [comment] 2017-05-19 15:48
I think the marketplace folks have trouble parsing something else

**Comment by chrmarti** [comment] 2017-05-19 16:44
Remind me what the reason is for parsing a UUID. I always think of these as something opaque (apart from the ability to store and compare them).

**Comment by joaomoreno** [comment] 2017-05-24 06:38
We didn't ask for a reason, they just asked for it explicitly.

**Comment by jrieken** [comment] 2017-06-28 13:03
@joaomoreno @chrmarti I leave this up to you guys

**Comment by joaomoreno** [comment] 2017-08-25 09:26
I've changed the ID we send to the Marketplace guys to be UUID. This allowed me to remove `getmac` from the critical path.

**Comment by bpasero** [comment] 2017-11-24 06:43
We only run getMac once on startup and then store it in either local storage or the storage.json on the main side. I do not think this is still an issue anymore. @chrmarti I suggest to close it.

**Comment by bpasero** [comment] 2017-11-24 11:18
Well we should probably still discuss if we can replace getMac with a different solution that requires less time 👍

**Comment by chrmarti** [comment] 2017-11-27 18:15
@bpasero We shouldn't block startup on having the machine id. I see you have started the discussion on resolving 'common' properties only in the shared process, we can take care of it with that. Closing this issue.

**Closed by chrmarti** 2017-11-27 18:15 UTC
Labels: bug, perf-startup, telemetry
