### ISSUE TITLE
converting emoji images

### ISSUE THREAD

**Issue by Kevinwere** [microsoft/vscode#87798] opened 2019-12-28 11:26 UTC
Issue Type: <b>Feature Request</b>

visual studio does not convert all emoji images

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.10586

**Comment by IllusionMH** [comment] 2019-12-29 04:17
/needsMoreInfo

VS Code uses system font for Emoji. (Segoe UI Emoji in case of Windows).

Can you see these emojis in other applications (e.g. Word, Notepad)?

Most likely the problem is in really old Windows version (if system info is correct `10.0.10586` was released in November 2015 and doesn't contain latest version of Emoji font. Also Windows doesn't have countries flag emojis.

**Closed** 2020-01-06 15:37 UTC
Labels: needs more info
