### ISSUE TITLE
Failed to create terminal for task 

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71311] opened 2019-03-27 18:57 UTC
- Paste the tasks from #70774 into the vscode repo's tasks.json file
- Start the watch task
- Kill the terminal before the build is totally done
- Get an error popup `Failed to create terminal for task `

**Comment by alexr00** [comment] 2019-03-28 09:52
A bad merge deleted the fix for the original issue 😓

**Comment by alexr00** [comment] 2019-03-28 09:55
duplicate of #70557

**Comment by alexr00** [comment] 2019-03-28 10:25
Actually not a bad merge. Fixing again.

**Closed** 2019-03-28 10:25 UTC
Labels: *duplicate, bug, tasks
