### ISSUE TITLE
error thrown when enableBreakpointsFor...languageIds missing from package.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3589] opened 2016-03-01 16:00 UTC
0.10.10-insiders on OSX
Check Console, see the following errors:

Cannot read property 'languageIds' of undefined: TypeError: Cannot read property 'languageIds' of undefined
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:9263
    at Array.forEach (native)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:8740
    at Array.forEach (native)
    at e._handler (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:8712)
    at Object.listener (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:27336)
    at e._triggerPointListener (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:29319)
    at e.registerPlugins (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:29919)
    at t.$onPluginHostReady (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:20850)
    at t.e.handle (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:28735)e.onUnexpectedError @ shell.ts:480(anonymous function) @ shell.ts:342e.onUnexpectedError @ errors.ts:72u @ errors.ts:87e._triggerPointListener @ pluginsRegistry.ts:432e.registerPlugins @ pluginsRegistry.ts:461t.$onPluginHostReady @ nativePluginService.ts:222e.handle @ abstractThreadService.ts:100c @ ipcRemoteCom.ts:172f @ ipcRemoteCom.ts:120doNTCallback0 @ node.js:420_tickCallback @ node.js:349
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:98emitOne @ events.js:77emit @ events.js:169window.onerror @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/atom.asar/renderer/lib/init.js:74e.enableGlobalErrorHandler.t @ abstractTelemetryService.ts:154
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.logException (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:30795)
    at e.log (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:112:14554)
    at t.handleEvent (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:1617)
    at t.e.publicLog (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:30855)
    at t.publicLog (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:3844)
    at t.e.flushErrorBuffer (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:28864)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:28724onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:98emitOne @ events.js:77emit @ events.js:169window.onerror @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/atom.asar/renderer/lib/init.js:74e.enableGlobalErrorHandler.t @ abstractTelemetryService.ts:154
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/applicationinsi…:67 Uncaught TypeError: Cannot convert object to primitive valueClient.trackException @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/applicationinsi…:67e.logException @ aiAdapter.ts:151e.log @ nodeAppInsightsTelemetryAppender.ts:167t.handleEvent @ mainTelemetryService.ts:90e.publicLog @ abstractTelemetryService.ts:251t.publicLog @ electronTelemetryService.ts:61e.flushErrorBuffer @ abstractTelemetryService.ts:121(anonymous function) @ abstractTelemetryService.ts:114

**Comment by isidorn** [comment] 2016-03-01 22:03
Adding important label since @chrisdias decided to put this to feb milestone

Assigning to @chrisdias since I can not reproduce this with just opening the insiders release. Please provide detailed steps on how to get this

**Comment by chrisdias** [comment] 2016-03-02 09:00
ok, i figured out what is causing this - the [react-native tools](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native).  with this extension installed, i get these console errors.

**Comment by isidorn** [comment] 2016-03-02 09:01
Then please file the bug against this repo
https://github.com/Microsoft/vscode-react-native

**Comment by chrisdias** [comment] 2016-03-02 09:12
@isidorn The errors show up in the console before any line of code is hit in the extension - its throwing from VSCode, not the extension as far as I can tell.  So, I don't know if this is an issue with VS Code or the extension.

**Comment by chrisdias** [comment] 2016-03-02 15:27
The react-native extension does not have the property enableBreakpointsFor defined in its package.json, if I define it and set "languageIds" then the exception is no longer thrown.

According to @weinand we are setting this in the node debugger and the extension should not have to set these property values and we shouldn't be throwing.

I see the same exception being thrown in the Jan2016 stable release, so this is not a regression from last month, meaning it is not a ship-stopper for Feb2016.

I believe the exception is being thrown in src/vs/workbench/parts/debug/node, in the registerListeners method.

**Comment by isidorn** [comment] 2016-03-02 15:50
@chrisdias nice investigation, I'll fix it right away. I agree it is not a stable-candadate

**Closed** 2016-03-02 15:55 UTC
Labels: bug

**Comment by chrisdias** [comment] 2016-03-16 02:30
react-native extension doesn't load in alpha, see https://github.com/Microsoft/vscode-react-native/issues/155

**Comment by chrisdias** [comment] 2016-03-22 00:46
waiting for react native extension fix to be published...

**Comment by egamma** [comment] 2016-03-29 12:09
assigning to @weinand for verification
