### ISSUE TITLE
Can not use input method to type Chinese on Ubuntu | 无法输入中文

### ISSUE THREAD

**Issue by Logic530** [microsoft/vscode#97565] opened 2020-05-12 01:23 UTC
Issue Type: <b>Bug</b>

The problem only happen with snap store installed code. The .deb package works fine.
OS: Ubuntu 20.04
Desktop: Gnome 3.36.1
Input Method: [A IBus Input Method](https://github.com/libpinyin/ibus-libpinyin) that comes with ubuntu

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.4.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|15.56GB (9.41GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by rebornix** [comment] 2020-06-05 00:33
It looks like a duplicate of https://github.com/microsoft/vscode/issues/51308 but can @Tyriar or @flexiondotorg  confirm if it's fixed or it regressed?

**Closed** 2020-06-08 14:24 UTC
Labels: *duplicate, editor-input-IME, linux, upstream
