### ISSUE TITLE
Reload the window to return to the previous state doesn't work

### ISSUE THREAD

**Issue by nithil** [microsoft/vscode#100396] opened 2020-06-17 15:15 UTC
- VSCode Version: 1.46.0
- OS Version: macOS 10.13.6 Darwin x64 17.7.0

Steps to Reproduce:

1. Launch a workspace using `code --disable-extensions .` which will open with all extensions disabled. At the bottom right corner there is a pop up 
![Screen Shot 2020-06-17 at 20 41 11](https://user-images.githubusercontent.com/31035540/84915844-f5b72100-b0da-11ea-8b9a-e12c21fd2bc0.png)

2. Clicking on the reload button doesn't change anything. since this is a newly opened workspace I don't think there will be any previous state to go to.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment] 2020-06-18 20:43
This is working as designed -- in that clicking reload will reload the window with extensions enabled again.

**Comment by nithil** [comment] 2020-06-20 04:11
@eamodio For me clicking on Reload is not loading the window with extensions enabled. Once the window is reloaded I get the same reload toast notification. I keep pressing the reload but every time it opens with extensions disabled only.

**Comment by RMacfarlane** [comment] 2020-08-11 18:01
Duplicate of https://github.com/microsoft/vscode/issues/94532

**Closed by RMacfarlane** 2020-08-11 18:01 UTC
Labels: bug
