### ISSUE TITLE
2 enable source map stepping commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194233] opened 2023-09-26 21:50 UTC
Testing #194071

Repro:

1. Debug fibonacci example
2. Disable source map stepping
3. Try enable it again

![Image](https://github.com/microsoft/vscode/assets/2193314/dd52b495-64b4-46b0-b593-255f4f418e2b)

I only have nightly installed, not stable.

**Comment by connor4312** [comment] 2023-09-26 22:15
dupe of https://github.com/microsoft/vscode/issues/194190

**Closed by connor4312** 2023-09-26 22:15 UTC
