### ISSUE TITLE
Introduce a "solution" configuration which enables manual mapping of folders to a workspace representation

### ISSUE THREAD

**Issue by alshdavid** [microsoft/vscode#89830] opened 2020-02-01 03:13 UTC
When working with large projects such as mono-repos which contain many internal projects, developers often experience a lot of clutter when trying to traverse the folder structure tree.

Most of the clutter will be compiler configuration or similar which is not directly pertinent to the goal of developing features.

My suggestion is to enable to manual mapping/grouping of files/folders into a solution like so:

![solution mode](https://user-images.githubusercontent.com/12656294/73586096-d5f0d900-44fc-11ea-8716-c9d9901a54ef.png)

My follow up question is surrounding the plugin engine. Is it rich enough for me to be able to create this in a plugin?

(Things like cntl + click a code to be transported to the implementation, expand the appropriate solution explorer block rather than file explorer, unless not mapped)

**Comment by isidorn** [comment] 2020-02-03 10:13
Duplicate of working files
For example this PR has all the details https://github.com/microsoft/vscode/pull/87666

**Closed by isidorn** 2020-02-03 10:13 UTC
