### ISSUE TITLE
Dirty write prevention does not function on my FileSystemProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#71113] opened 2019-03-25 21:43 UTC
My extension implements a FileSystemProvider similar to Remote FS. If I open a file in VSCode, then modify it directly on the server, VSCode spots this and loads the new version, which is neat. But if I modify the file in VSCode without saving it, then modify it directly on the server, then tell VSCode to save its change, I don't get the dirty write prevention described [here](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_preventing-dirty-writes). That behaviour only seems to happen when working on local files.

I've tested in 1.32.3 and in 1.33.0-insider.

Maybe my extension isn't implementing everything it needs to. Or perhaps dirty write prevention hasn't yet been implemented for FileSystemProvider.

**Comment by bpasero** [comment] 2019-03-26 07:15
If this reproduces in 1.32.3 it cannot be a regression from my file service work.

I suggest to mark this as duplicate of https://github.com/Microsoft/vscode/issues/34840 where we will get to a point where all providers are treated equally and full `etag` support must work as before.

**Closed** 2019-03-26 08:46 UTC
Labels: *duplicate
