### ISSUE TITLE
Incremental update to the markdown preview 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#134796] opened 2021-10-11 14:08 UTC
The markdown preview is completely replaced with every edit in the source file. This is particularly noticeable when the markdown file contains images. In my case, for example, the source file contains links to images stored on cleanshot. If I keep the preview open (with I prefer) and keep typing the images flash constantly and in no time I get 429s from the cleanshot service.

**Comment by mjbvz** [comment] 2021-11-10 00:25
Duplicate of #136703

(sorry opened a duplicate and added it to the plan without realizing this issue was already tracking the same thing)

**Closed by mjbvz** 2021-11-10 00:25 UTC
Labels: bug, markdown
