### ISSUE TITLE
编辑器遇到这段代码发生无响应

### ISSUE THREAD

**Issue by lanmp** [microsoft/vscode#55738] opened 2018-08-03 08:29 UTC
Issue Type: <b>Bug</b>

禁用所有扩展的情况下
复制下面这段代码到任意一个扩展名为.php的文件里面
if ($output->asset_id != 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff') {
                        continue;
                    }
编辑器马上卡死

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.11GB free)|
|Process Argv|D:\Portabel\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

Google translate:
Copy the following code into any file with a .php extension.
```
if ($output->asset_id != 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff') {
                        continue;
                    }
```

The editor is stuck right away.

**Comment by roblourens** [comment] 2018-08-03 22:32
Probably same as https://github.com/Microsoft/vscode/issues/46907

@aeschli @alexandrudima What's the best way to debug these hangs while colorizing?

**Comment by aeschli** [comment] 2018-08-06 08:32
@roblourens  You can use these steps to pin down the problematic regexp.
https://github.com/Microsoft/vscode/issues/40279#issuecomment-361405690

**Comment by roblourens** [comment] 2018-09-24 04:18
I can reduce it to `Searching for (?i)([a-z0-9_\x{7f}-\x{7fffffff}]+)\s*\( in  (ffffffffffffffffffffffffff` but I have no idea what the problem with that is.

**Comment by alexandrudima** [comment] 2018-10-08 08:41
@roblourens Have you tried https://regex101.com/ -- I have used that successfully to pinpoint catastrophic backtracking.

**Comment by roblourens** [comment] 2018-10-08 16:37
It seems like it's not catastrophic backtracking. I think I need to debug some more inside oniguruma.

**Comment by connor4312** [comment] 2019-10-11 20:43
This appears fixed in recent versions, likely the same root cause as #75468

**Closed** 2019-10-11 20:43 UTC
Labels: *duplicate, bug, php
