### ISSUE TITLE
Holding a key doesn't send repeated keypress to integrated terminal

### ISSUE THREAD

**Issue by avarun42** [Microsoft/vscode#10398] opened 2016-08-10 15:07 UTC
- VSCode Version: 1.4.0
- OS Version: macOS 10.11.6 El Capitan

Steps to Reproduce:
1. Open integrated terminal.
2. Use `git log` in a git project directory
3. Hold down arrow key to scroll down.

Only one line movement occurs, and key has to be tapped repeatedly.

**Comment by Tyriar** [comment] 2016-08-11 20:03
Cannot reproduce on Linux, perhaps this is mac specific?

**Comment by Tyriar** [comment] 2016-09-06 21:53
Upstream issue: https://github.com/sourcelair/xterm.js/issues/265

**Comment by pibone** [comment] 2016-11-14 09:22
You can disable key holding on macOS
`defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false`

**Comment by Tyriar** [comment] 2016-11-14 17:33
I can no longer reproduce this on Mac. I'm pretty sure I have the default settings in this regard and repeat keystrokes seems to work fine so closing off.

**Closed by Tyriar** 2016-11-14 17:33 UTC
Labels: integrated-terminal, mac, upstream

**Comment by lamielle** [comment] 2017-07-27 23:16
Hi @Tyriar, I'm hitting this issue on Mac, VSCode 1.14.2.  Any chance you could try to repro quickly again? The upstream issue is still open.  Wondering if this issue should get re-opened?

The curious thing is that backspace repeats for me, but other characters, such as 'a', do not.

**Comment by Tyriar** [comment] 2017-07-28 15:48
@lamielle 'a' is covered in https://github.com/sourcelair/xterm.js/issues/265, down/backspace definitely work for me.

**Comment by lamielle** [comment] 2017-07-28 15:59
Right, thanks for the reply @Tyriar .  I guess my point here is that the bug from a user's perspective is in VSCode, so doesn't it make sense to leave this issue open until that xterm.js issue is fixed and VSCode pulls in the version with the fix?

Basically I'm looking for a way to know when I can update VSCode and expect repeated 'a' to work.  : )

**Comment by Tyriar** [comment] 2017-07-28 16:21
@lamielle good point, I created https://github.com/Microsoft/vscode/issues/31676 as this issue is specifically about holding the down arrow which works fine now.

**Comment by lamielle** [comment] 2017-07-28 16:32
Awesome, thank you for the help @Tyriar !  I'll subscribe to the new issue you created.  I apologize, I missed that this specific issue was focused just on the arrow key.  The title of the issue was misleading to me!  Anyway, thanks again.
