### ISSUE TITLE
vscode auto completes certain patterns without consent

### ISSUE THREAD

**Issue by Nuc1eoN** [microsoft/vscode#78650] opened 2019-08-07 17:25 UTC
Ok so this happened for me on a few different occasions and I think it really should be fixed. I have a few patterns in mind that trigger the bug, but lets go with the one everybody should be able to reproduce instantly:

1. Create a `.js` file
2. Type `ul.`

Upon writing the dot `.` vscode autocompletes the expressions to either `URL.` or `userList.` on my side. I can 100% reproduce this every time, with all of my extensions disabled.

So I am pretty sure vscode is not supposed to automagically replace strings without pressing `enter` or `TAB`

As I said there have been other patterns also triggering this, but lets go with the above mentioned example for now, as it seems very simple to reproduce and maybe all those occurrences have the same root cause.

**Comment by gjsjohnmurray** [comment] 2019-08-07 22:56
For .js and .ts files the dot is a completion character, and the setting `editor.acceptSuggestionOnCommitCharacter` defaults to true.

See https://github.com/microsoft/vscode/issues/70176#issuecomment-471366315

**Comment by jrieken** [comment] 2019-08-08 07:22
What version is this? This is likely a duplicate of https://github.com/microsoft/vscode/issues/77926

**Comment by Nuc1eoN** [comment] 2019-08-08 20:43
> For .js and .ts files the dot is a completion character, and the setting editor.acceptSuggestionOnCommitCharacter defaults to true.

Yes disabling that fixes it, even though I would consider this to be a very unintuitive default.

Also I still think this might be some kind of a bug since it is not consistent at all what will be autocompleted. As I have mentioned, `ul.` gets randomly converted to either `URL.` or `userList.`.

> What version is this? This is likely a duplicate of #77926

Might be! I'm on v1.36.1

One other case was, that writing something like `.style` would get autocompleted to `.getElementsByClassName`, however I currenlty didnt find a way to trigger it in a reproducable manner. You can see the issue here: https://youtu.be/hdI2bqOjy3c?t=5261

**Comment by jrieken** [comment] 2019-08-09 07:19
> Might be! I'm on v1.36.1

Very, very likely. Closing as duplicate, please report back if this happens with 1.37 (released yesterday)

**Closed** 2019-08-09 07:19 UTC
Labels: *duplicate, needs more info, suggest

**Comment by Nuc1eoN** [comment] 2019-08-14 20:55
Hey, seems it is still happening with v1.37

I can definately still reproduce the `.ul` issue described above in .js files
