### ISSUE TITLE
Integrated Terminal (ConPty) picks up AudioVolumeUp etc. from Dell AC511 Soundbar Volume Scroller

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#66015] opened 2019-01-04 08:55 UTC
Issue Type: <b>Bug</b>

When scrolling the volume wheel of my Dell soundbar the integrated terminal prints volumeup and down control keys. I don't know if this is related to VSCode or ConPty, but it definitely appeared with the move to ConPty. Feel free to move this over there, if this isn't vscode related.

![2019-01-04_09-49-09](https://user-images.githubusercontent.com/6466560/50680015-4b425f80-1006-11e9-9110-60055d7a6348.gif)

All you need is focus and a volume wheel 😄 

VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:17:20.719Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
soy|ant|0.0.1
cake-vscode|cak|0.11.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.22.0
docs-article-templates|doc|0.1.4
docs-markdown|doc|0.2.1
docs-preview|doc|0.3.16
xml|Dot|2.4.0
gitlens|eam|9.3.0
vscode-solution-explorer|fer|0.3.1
beautify|Hoo|1.4.7
rest-client|hum|0.21.0
XMLLanguageSupport|IBM|0.0.1
vscode-kubernetes-tools|ms-|0.1.14
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.10.2
vscode-docker|Pet|0.4.0
ruby|reb|0.21.0
java|red|0.36.0
vscode-yaml|red|0.2.0
vscode-icons|rob|8.0.0
velocity|sod|0.1.0
msbuild-project-tools|tin|0.2.51
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
omnipascal|Wos|0.17.0

</details>

**Comment by MeikTranel** [comment] 2019-01-04 08:58
Hey @Tyriar, hope you had some quality holidays 😉 

I don't know whether to put this under conpty or vscode? Feel free to move this now that we can move issues 😄

**Comment by cedric05** [comment] 2019-01-04 14:51
happening for me as well
my laptop configuration:
lenovo thinkpad
> Version: 1.31.0-insider (user setup)
> Commit: 7805023eaa46db45d3c24a4c38c0d07c087cf1b3
> Date: 2019-01-03T06:20:50.629Z
> Electron: 3.0.10
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment] 2019-01-04 18:08
Duplicate of #65949, will be fixed in the next build 😃

**Closed by Tyriar** 2019-01-04 18:08 UTC
Labels: integrated-terminal
