### ISSUE TITLE
HTML:5 Snippets. "!" isn´t works anymore on VScode ubuntu 22.04

### ISSUE THREAD

**Issue by alves-leandro** [microsoft/vscode#154943] opened 2022-07-12 15:10 UTC
Does this issue occur when all extensions are disabled?: Fresh instalation, no extra extensions 

- VS Code Version: 1.69.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. open a new project
2. create a index.html
3. start with "!" (should start with html script)

we still can use "html" and chose emmet option, but the "!" shortcut isnt workin anymore

hoppe it can be helpful

**Comment by rzhao271** [comment] 2022-07-12 16:12
Duplicate of https://github.com/microsoft/vscode/issues/154375

**Closed by rzhao271** 2022-07-12 16:12 UTC
Labels: *duplicate
