### ISSUE TITLE
Black text displays as white on red background in default dark and several other themes

### ISSUE THREAD

**Issue by carbon-starlight** [microsoft/vscode#213865] opened 2024-05-29 23:02 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open the terminal (under the workspace, the one under `PROBLEMS` `OUTPUT` `DEBUG CONSOLE` `TERMINAL`)
2. Launch Python3 with `py`
3. Run the line I was testing: `print('\033[30m\033[41m🭪 All subprocesses were terminated 🭨\033[0m'`

In Windows Terminal (app) and with some themes it displays correctly, in VSCode with default dark theme the text is white (should be black due to escape code `\033[30m`).

The following themes are affected:

* 2017 Dark
* Dark (Visual Studio -- C/C++)
* Dark (Visual Studio)
* Dark Modern
* Dark+
* Kimble Dark
* Monokai
* Monokai Dimmed 
* Red 
* Selclouth
* _etc._

Examples of themes there the coloring is correct:

* Solarized Light
* Abyss
* Solarized Dark
* SynthWave '84
* Tomorrow Night Blue

**Comment by Tyriar** [comment] 2024-12-18 19:22
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-18 19:22 UTC
