### ISSUE TITLE
Quality of Life Suggestion: open files in the same window

### ISSUE THREAD

**Issue by Accelyte** [Microsoft/vscode#20834] opened 2017-02-17 21:47 UTC
I have 5 untitled files in hot exit (I leave them there as memos). When I open a file without Code opened, the file opens in a window separate to the hot exit files. It would be great to unify the windows when a file is being opened.
Demonstration:
![2017-02-17_21-46-08](https://cloud.githubusercontent.com/assets/21363469/23084530/a0a838a0-f55a-11e6-9b15-7e7064e74dae.gif)

**Comment by bpasero** [comment] 2017-02-19 08:52
Yes, I would say this is a duplicate of https://github.com/Microsoft/vscode/issues/16820

**Closed by bpasero** 2017-02-19 08:52 UTC
