### ISSUE TITLE
code folding does not supoort nested if or #ifdef

### ISSUE THREAD

**Issue by JYU2018** [microsoft/vscode#87009] opened 2019-12-15 02:00 UTC
not sure it's a bug. 
current version only support code folding for the portion between the adjacent two ifs blocks (the second if statement is the nested if block statement), can not fold the whole if block statement (the most outest if). the same phenomenon happens on  #ifdef directives. 
especially for header file, there are many nested #ifdef directives, and can not judge easily which #ifdef pairs with which #endif.

it seems current code folding is designed simply based on indentation.

Ubuntu 18.04 LTS
VScode 1.41.0

**Comment by JYU2018** [comment] 2019-12-15 02:07
correct my descriptions: I just check my new version 1.41, and did not find problem with if blcok statement,  but #ifdef directives issue still exists.

**Comment by JYU2018** [comment] 2019-12-17 05:35
another finding: if #ifdef directives are in the if statement block, the code folding only folds from if to the #ifdef directive.

**Comment by JYU2018** [comment] 2019-12-17 05:37
it's C/C++ language.

**Comment by aeschli** [comment] 2019-12-17 09:20
duplicate of https://github.com/microsoft/vscode-cpptools/issues/407

**Closed by aeschli** 2019-12-17 09:20 UTC
