### ISSUE TITLE
git 

### ISSUE THREAD

**Issue by Lianjinlei** [Microsoft/vscode#36024] opened 2017-10-11 06:26 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.7.0
beautify|Hoo|1.1.1
annotator|ryu|0.10.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by 06needhamt** [comment] 2017-10-11 09:40
What exactly is the issue here?

**Comment by egamma** [comment] 2017-10-11 09:52
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment] 2017-10-13 07:39
Closing, please reopen with more information.

**Closed by egamma** 2017-10-13 07:39 UTC
Labels: extensions, needs more info
