### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by WillemLabu** [microsoft/vscode#84254] opened 2019-11-08 11:32 UTC
Issue Type: <b>Bug</b>

When I right-click a directory, and select Find in Folder, the search is completely blank.

<img width="1101" alt="Screenshot 2019-11-08 at 11 31 35" src="https://user-images.githubusercontent.com/2142636/68473609-5adc9700-021b-11ea-8ad9-83b2ecfae7fa.png">

VS Code version: Code - Insiders 1.41.0-insider (fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347, 2019-11-08T05:26:43.949Z)
OS version: Darwin x64 18.7.0

**Comment by gjsjohnmurray** [comment] 2019-11-08 11:37
Possible duplicate of #84250

**Comment by WillemLabu** [comment] 2019-11-08 12:07
I'd be happy to give you a error log if someone could explain how to trace it.

**Comment by IllusionMH** [comment] 2019-11-08 12:21
Yes, looks like same issue. You can see error trace in DevTools **Help > Toggle Developer Tools**

In the meantime you can use next workaround: set `search.location` to`"sidebar"` and reload window.

**Closed** 2019-11-08 12:23 UTC
