### ISSUE TITLE
d.ts files not reloaded when updated causing outdated type information to influence IntelliSense

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/vscode#14862] opened 2016-11-02 17:20 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: bialikover.theme-seti-0.0.1, donjayamanne.createuniqueid-0.0.3, florianloch.text-transform-0.0.2, gerane.Theme-FlatlandMonokai-0.0.4, HookyQR.beautify-0.1.10, ionutvmi.path-autocomplete-1.1.0, joelday.docthis-0.3.3, ms-vscode.csharp-1.4.0, msjsdiag.debugger-for-chrome-0.5.2, peterj.proto-0.0.2, qinjia.seti-icons-0.0.7

Steps to Reproduce:

1. Setup TS files to compile to js/d.ts files in a different folder (eg. src->lib)
2. Import js files from lib and use Intellisense feature (e.g call a function using types)
3. Make a change to TS causing js/d.ts file to update

 Causes outdated type annotations to appear

`Reload Window`  fixes that but is cumbersome of course

**Comment by rebornix** [comment] 2016-11-02 18:29
I have a feeling that ppl already filed an issue about it but right now I can't find that one so assign to @waderyan first.

**Comment by waderyan** [comment] 2016-11-02 20:36
@dbaeumer can you take a look at this for me? It seems the issue is caused because TSServer is not reloading when the *.d.ts files change. Is that correct?

**Comment by dbaeumer** [comment] 2016-11-04 11:11
@waderyan actually I don't know what the tsserver does here. Since the files out of lib come through a import statement it might be that tsserver decides not to list on file events on them since they don't belong to the project scope.

From a conceptual point of view the problem sounds to me like a project to project dependency. In that case tsserver would know to track changes to the dependent project.

**Comment by waderyan** [comment] 2016-11-07 16:11
@mhegazy can you advise us on this?

**Comment by mhegazy** [comment] 2016-11-07 17:31
can you share a repro project we can debug against?

**Comment by waderyan** [comment] 2016-11-21 23:09
Closing until more info is obtained.

**Closed by waderyan** 2016-11-21 23:09 UTC
Labels: intellisense, needs more info, typescript
