### ISSUE TITLE
Slow startup profile on Windows 10

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#34167] opened 2017-09-11 20:59 UTC
[e8fb_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1294051/e8fb_main.cpuprofile.txt)
[e8fb_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1294050/e8fb_renderer.cpuprofile.txt)

- VSCode Version: <code>Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)</code>
- OS Version: <code>Windows_NT x64 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)</code>
- Memory (System): <code>7.89GB (1.08GB free)</code>
- Memory (Process): <code>227.32MB working set (236.92MB peak, 198.76MB private, 52.56MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|80|
|main|app.isReady => window.loadUrl()|566|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|969|
|renderer|require(workbench.main.js)|1425|
|renderer|create extension host => extensions onReady()|3855|
|renderer|restore viewlet|2532|
|renderer|restore editor view state|2199|
|renderer|overall workbench load|3189|
|main + renderer|start => extensions ready|7026|
|main + renderer|start => workbench ready|6308|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`e8fb_main.cpuprofile.txt`
-`e8fb_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-11-13 11:33
dupe of https://github.com/Microsoft/vscode/issues/34371

**Closed by jrieken** 2017-11-13 11:33 UTC
Labels: perf-profile
