### ISSUE TITLE
--debug-brk is deprecated

### ISSUE THREAD

**Issue by victor0801x** [Microsoft/vscode#38748] opened 2017-11-20 06:05 UTC
- VSCode Version: 1.18
- OS Version: CentOS 7.4.1708

using `nodemon` launch debug show DeprecationWarning
```
`node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
```

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-11-20 09:24
duplicate of #32529

**Closed** 2017-11-20 09:25 UTC
Labels: *duplicate, debug
