### ISSUE TITLE
Settings editor scrolls over focus outline

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#233256] opened 2024-11-06 20:41 UTC
See:

![Image](https://github.com/user-attachments/assets/6c2f6721-c2a1-4019-9dd8-2460173fdae1)

**Comment by rzhao271** [comment] 2024-12-11 17:48
Duplicate of https://github.com/microsoft/vscode/issues/183503

**Closed by rzhao271** 2024-12-11 17:48 UTC
Labels: bug, settings-editor
