### ISSUE TITLE
Wrong values for CompletionItemKind.

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#61217] opened 2018-10-18 08:32 UTC
- VSCode Version: 1.28.1
- OS Version: All

My version info:
```
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

### Problem

The definitions of CompletionItemKind are different between LSP and VS Code. So when I use `vscode.languages.registerCompletionItemProvider` to provide completion items, it renders the wrong icons.

In the below screenshot, the item is a `Class`, but the icon is for `Interface`.
![image](https://user-images.githubusercontent.com/2351748/47141458-4d442e80-d2f3-11e8-8d6a-bbb986365bae.png)

### Details

See [LSP specs for completion](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion):

```ts
/**
 * The kind of a completion entry.
 */
namespace CompletionItemKind {
	export const Text = 1;
	export const Method = 2;
	export const Function = 3;
	export const Constructor = 4;
	export const Field = 5;
	export const Variable = 6;
	export const Class = 7;
	export const Interface = 8;
	export const Module = 9;
	export const Property = 10;
	export const Unit = 11;
	export const Value = 12;
	export const Enum = 13;
	export const Keyword = 14;
	export const Snippet = 15;
	export const Color = 16;
	export const File = 17;
	export const Reference = 18;
	export const Folder = 19;
	export const EnumMember = 20;
	export const Constant = 21;
	export const Struct = 22;
	export const Event = 23;
	export const Operator = 24;
	export const TypeParameter = 25;
}
```

But in VS Code, the value starts from 0.   See 
https://github.com/Microsoft/vscode/blob/078b1415e40ac476d6b15ceab9795598f9009fac/src/vs/workbench/api/node/extHostTypes.ts#L1132-L1158

**Comment by jrieken** [comment] 2018-10-18 16:08
We didn't change them in `vscode.d.ts`...

**Comment by dbaeumer** [comment] 2018-10-19 10:38
This is on purpose since all number / enums in the LSP start with 1 to avoid problems with falsify values.

The client library converts them into the correct value here:

https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L314

Will check if there is a bug somewhere missing a conversion.

**Comment by dbaeumer** [comment] 2018-10-19 10:46
I tested this on the latest version of the LSP libraries and this works as expected.

![capture](https://user-images.githubusercontent.com/1931590/47213943-ca77ae00-d39c-11e8-9326-55d0f7352a2d.png)


Server code:

```typescript
connection.onCompletion((textPosition, token): CompletionItem[] => {
	return [
		{
			label: "Class",
			kind: CompletionItemKind.Class,
			data: 999
		},
		{
			label: "Interface",
			kind: CompletionItemKind.Interface,
			data: 999
		}
	]
});
```

Do you have a middleware injected into the LSP client that might not convert these enums correctly?

**Comment by Eskibear** [comment] 2018-10-19 17:17
In the following GIF, I registered 2 `CompletionItemProvider` for python. 
* provider1 uses lsp.CompletionKind from `vscode-languageserver-protocol`, triggered by `#`.
```ts
   const provider1 ...
...
                kind: lsp.CompletionItemKind.Class,
...
    vscode.languages.registerCompletionItemProvider(selector, provider1, "#");
```
* provider2 uses vscode.CompletionKind from `vscode`, triggered by `$`. 
```ts
   const provider2 ...
...
                kind: vscode.CompletionItemKind.Class,
...
    vscode.languages.registerCompletionItemProvider(selector, provider2, "$");
```

You can see the icons is wrong for provider1, because vscode doesn't honor specs in LSP, there's an offset. 

![completionkind](https://user-images.githubusercontent.com/2351748/47233134-596be100-d404-11e8-9bf7-9ca6c598440e.gif)

Attaching the code, you can have a try yourself:

[extension.ts.zip](https://github.com/Microsoft/vscode/files/2496714/extension.ts.zip)

**Comment by dbaeumer** [comment] 2018-10-22 07:48
Yes, this is correct. You can't use the LSP enum kinds when directly talking to the VS Code API. They can only be used when implementing an LSP server. As said the conversion is happening in Microsoft/vscode-languageserver-node:client/src/protocolConverter.ts@master#L314

The reason why the LSP enums all start with 1 is that zero values can cause problems when transferred between processes especially if one language as a falsify concept like JS does.

I am closing the issue since the different enum values are by design.

**Comment by dbaeumer** [comment] 2018-10-22 07:48
Yes, this is correct. You can't use the LSP enum kinds when directly talking to the VS Code API. They can only be used when implementing an LSP server. As said the conversion is happening in Microsoft/vscode-languageserver-node:client/src/protocolConverter.ts@master#L314

The reason why the LSP enums all start with 1 is that zero values can cause problems when transferred between processes especially if one language as a falsify concept like JS does.

I am closing the issue since the different enum values are by design.

**Closed by dbaeumer** 2018-10-22 07:48 UTC
Labels: needs more info
