### ISSUE TITLE
Latest upgrade to Version 1.19.1 (1.19.1) breaks Jest Test Debugging Capabilities

### ISSUE THREAD

**Issue by Dimomir** [Microsoft/vscode#40896] opened 2017-12-28 11:04 UTC
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: OS X El Capitan 10.11.6 (15G1421)

Hi there, I suspect the newest update might be breaking the Jest debugging. Here's my config taken straight from [Jest's website](https://facebook.github.io/jest/docs/en/troubleshooting.html#debugging-in-vs-code): .

 _Note: I'm using the CRA setup_

```
{
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/client/node_modules/.bin/react-scripts",
      "runtimeArgs": ["--inspect-brk", "test"],
      "args": ["--runInBand", "--no-cache", "--env=jsdom"],
      "cwd": "${workspaceRoot}/client",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
}
```

Steps to Reproduce:

When I try to start debugging (which I can confirm was working with previous versions) I now get the error:
`Error: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:3269)`.

Could you please point me to what I'm missing? 
   💭
🤔

**Comment by weinand** [comment] 2017-12-28 13:12
duplicate of https://github.com/Microsoft/vscode/issues/40254.

The launch config from Jest's website is wrong.
Use this launch config:
```json
{
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/client/node_modules/.bin/react-scripts",
      "args": [ "test", "--runInBand", "--no-cache", "--env=jsdom" ],
      "cwd": "${workspaceRoot}/client",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
}
```

**Closed by weinand** 2017-12-28 13:12 UTC
Labels: debug

**Comment by Dimomir** [comment] 2017-12-28 13:38
I can confirm the above solution works 👌 

Thank you kindly for your time @weinand

**Comment by Phlow2001** [comment] 2018-02-09 05:57
For those that ended up here because VSCode debugging for jest on windows STILL doesn't work, try the following:
        {
          "name": "Debug Jest Tests",
          "type": "node",
          "request": "launch",
          "runtimeArgs": [
              "--inspect-brk=5555",
              "${workspaceRoot}/node_modules/jest/bin/jest.js"
          ],
          "args": [
              "--runInBand",
          ],
          "port": 5555,
          "protocol": "inspector",
          "console": "integratedTerminal",
          "internalConsoleOptions": "neverOpen"
        }

**Comment by weinand** [comment] 2018-02-09 09:09
@Phlow2001 this (simpler) launch config should be equivalent for VS Code > 1.19:
```json
        {
          "name": "Debug Jest Tests",
          "type": "node",
          "request": "launch",
          "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
          "args": [
              "--runInBand",
          ],
          "protocol": "inspector",
          "console": "integratedTerminal",
          "internalConsoleOptions": "neverOpen"
        }
```

And you only need the "protocol" attribute if you are using node.js < 8.0
