### ISSUE TITLE
Add postDebugTask to debugger launch.json

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#11522] opened 2016-09-04 15:34 UTC
There is preLaunchTask already which runs a task right before debugging, it would be cool also having a `postDebugTask` which would run a task when finishing debugging.

Users could then provide a custom start server and stop server task for example.

**Comment by weinand** [comment] 2016-09-20 09:11
duplicate of #2405

**Comment by newbrain** [comment] 2016-09-20 09:18
Hi,
are you sure it's a duplicate?
The postDebug task should not run once the debugger is started, but rather when it's ended (i.e. when the "Stop" red sqare icon is clicked).
The idea behind the proposal, that I originally sent to the native gdb extension, is to have a clean up task that can, e.g., stop debug servers.

**Comment by weinand** [comment] 2016-09-20 09:20
@newbrain you are right.

**Comment by MeirionHughes** [comment] 2017-01-26 11:20
Something like this would make clean up after transpiling (for debugging) a bit easier.

**Comment by rei-vilo** [comment] 2017-03-09 19:48
Any update on this `postLaunchTask` feature? Thank you!

**Comment by isidorn** [comment] 2017-03-10 08:34
To be honest I am not undestadning how this is not a duplicate of https://github.com/Microsoft/vscode/issues/2405

All in all, this is still on the backlog. And if demand increases we can consider introducing it in one of the coming releases.

**Comment by newbrain** [comment] 2017-03-10 09:00
@isidorn:
[#2405](https://github.com/Microsoft/vscode/issues/2405) request that a task be started after the launch, so AFAICU, when the debug session is still active.

This one, instead, is asking for a task to be started when the debugging session is terminated ("Stop" button clicked): quite the opposite.

My use case: cleanly stopping a local debug server process (OpenOCD) when debugging embedded code, so that the e.g. DUT is properly reset.

As for #2405, I used a workaround: start a background script with a "reasonable" delay.

**Comment by isidorn** [comment] 2017-03-10 09:05
@newbrain Got it. Thanks for the explanation,

**Comment by weinand** [comment] 2017-03-10 09:45
@isidorn issue #2405 asks for a hook to launch something (e.g. a browser) after the debug session has started whereas this issue asks for a hook when the debug session has ended.

I believe that this request is actually more important than #2405  because that one can be emulated by using a delay.

**Comment by MeirionHughes** [comment] 2017-03-10 09:57
Main problem at the moment is that there is no way to clean up _after_ debugging ts-compiled code, which all needs to be on the file system in order for vscode to find it. We either need a way to clean up after debugging (this issue), or a way to have vscode debug without the js and map file on the fs.

**Comment by weinand** [comment] 2017-03-10 11:58
@MeirionHughes any suggestions how VS Code could support debugging without js and map files on the filesystem?

**Comment by MeirionHughes** [comment] 2017-03-10 14:08
Well I'm currently using webpack-dev-server quite a lot, and it keeps everything in memory and serves up those files when requested by chrome. 

In principle, all you'd really need is

* a webpack plugin that calls
* a vscode-debugger server API to supply and update the sourcemaps files (and paths). 

whenever the in-memory source/sourcemap is compiled it could then continually update the vscode debugger via the API. I would think main innards of how vscode debugger deals with the source mapping would be unaffected - perhaps it would need testing to make sure you can actually update the sourcemaps on the fly... i.e. for hot-module reloading where the chrome-debugger won't actually be refreshing the whole page.

**Comment by xinyanmsft** [comment] 2017-05-23 18:41
Having a Post debug task is very help for us to clean up remote connections. 
Scenario:
  We automate some remote debugging scenario by having the prelaunch task establish a SSH connection (port forwarding) to the remote host. The problem now is, we don't have a good way to know when to safely clean up this connection after debugging stops. There is no way to get that event from an extension as well.
  If there is a post debug task, we can use it to reliably clean up remote connections.

**Comment by G1itcher** [comment] 2017-07-17 11:08
Would the team consider an external contribution for this?

**Comment by isidorn** [comment] 2017-07-17 12:25
@G1itcher yes PRs are welcome, however before writing code feel free to just create a PR with a proposed solution. Once we agree on the structure we can start coding.
If you prefer to code you can just start with that however be aware that we might reject it
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L880

Also ping me on the pr. Thanks!

**Comment by cleidigh** [comment] 2017-11-28 22:51
@G1itcher 
Did you decide to work on this?  If not let me know as I can do a PR also.

**Comment by G1itcher** [comment] 2018-01-26 13:05
Hi @cleidigh. Unfortunately my situation has changed and I've had 0 free time to sit down and look at this.

**Comment by isidorn** [comment] 2018-03-07 21:09
I started looking into this `"postDebugTask"`. This task will be launched when a debug process ends, which basically means when you stop debugging or when you restart your session.
preLaunchTask also gets run on restart so I think this is consistent.

How should we call this? Is "postDebugTask" a good name, how about "postLaunchTask"?
How to make it clear that users do not confuse it with #2405 since both @weinand and me confused it a couple of times.

An alternative to adding a new string field is adding a structured object, something like: 
```json
"task": {
  "name" : "foo",
  "whenToExecute": "preLaunch" | "postLaunch" | "onSessionEnd"
}
```

The upside of this is that it makes it a bit clearer when it will be executed and we can also cover #2405. Downside is that strucutred objects are more complex.

Let me know what you think @weinand

**Comment by newbrain** [comment] 2018-03-07 21:35
@isidorn:
`"onSessionEnd"` is quite self-explicative, I prefer it to my original proposal of `"postDebug(Task)"`.
If a structured object is not used, `"onSessionEndTask"` seems quite right.

Thanks for picking this up.

**Closed** 2018-03-08 14:48 UTC
Labels: debug, feature-request

**Comment by isidorn** [comment] 2018-03-08 14:51
I have pushed the initial support for this. Try it out in tomorrow's vscode insiders and let us know what you think.

@weinand what you are saying makes sense, however I think the use case is that people want to deconstruct whatever they contructed in `preLaunchTask`. So I think this should run symetrical to `preLaunchTask`. As a seperate discussion we can figure out if `preLaunchTask` should be run on restart (currently it does)?

A seperate issue on my end is that I do not know what is the reason that a session stopped, or started so in both those I run `preLaunch` or `postDebug` task.

I am open to changing this but pushed a first version so we get some feedback.

**Comment by weinand** [comment] 2018-03-08 15:30
@isidorn you said:
> I do not know what is the reason that a session stopped, or started so in both those I run preLaunch or postDebug task.

This is not true for the "restart" case (2. from above). In this case you receive a ["restart" attribute](https://github.com/Microsoft/vscode-debugadapter-node/blob/734c9860efa5cef524bf12223d9c2f1512a833da/protocol/src/debugProtocol.ts#L132) in the "terminate" event, so you could know that a "preLaunchTask" and "postDebugTask" is not needed for an automatic "restart".

I don't think that Docker users want to shutdown and relaunch a Docker session on every source code edit.

@chrisdias what do you think?

**Comment by isidorn** [comment] 2018-03-08 15:33
@weinand I did not mean it is not possible, just my code is structured in such a way that I do not have that knowledge when I am reacting on seassion has ended event.
As I mentioned above I am open to changing this.

**Comment by isidorn** [comment] 2018-03-08 15:53
@weinand also it seems than for that scenario we should also not run the preLaunchTask again. So it still feels to me these two are "symetric".

**Comment by rei-vilo** [comment] 2018-03-08 15:55
The use case I have is about debugging MCUs.

+ Launch the GDB server (OpenOCD, JLinkGDBServer or other) with `preLaunchTask`,
+ Perform the debugging session, 
+ Once the debugging session is completed, stop the GDB server with `postDebugTask`. 

Some GDB clients allows to start the server from the GDB clients and to stop it when closing the debugging session, but not all. However, even in that case, I haven't figured out how to set all those parameters on the `launch.json` file, as the client tries to connect to the server _before_ it starts.

**Comment by rei-vilo** [comment] 2018-03-08 15:57
@isidorn 

Could `preLaunchTask` be called `preDebugTask`?

**Comment by isidorn** [comment] 2018-03-08 15:58
@rei-vilo no, since that would be a breaking change.

**Comment by weinand** [comment] 2018-03-08 16:00
@rei-vilo let's talk about semantics first, and then discuss name changes.

@isidorn yes, preLaunchTask should not be called on automatic "restart" (case 2). In the Docker scenario (https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript) we are lucky and survive multiple activations of the task because it is a background watcher task anyway.

**Comment by isidorn** [comment] 2018-03-08 16:47
@weinand I have pushed a change that both preLaunch and postDebug task are not being run on automatic restarts.
Let's try it out and then we can decide if they should be run for explitcit user restarts - currently they are being run.
Thanks

**Comment by weinand** [comment] 2018-03-08 16:49
Great, thanks. I'll try my scenarios tomorrow.
