### ISSUE TITLE
Better support for ES module imports

### ISSUE THREAD

**Issue by oskargustafsson** [Microsoft/vscode#61431] opened 2018-10-21 10:03 UTC
Thanks for a fantastic product! I have the following feature requests, all related to ES module imports.

- When auto importing things from ES modules, the generated import path does not contain a `.js` suffix. As far as I know, this is not part of the standard, and e.g. Chrome and Firefox are not able to resolve such paths.
- The auto generated import paths are always relative. It would be nice with an option to generate absolute paths (starting with a `/`). The generated paths could be "absolute" either with regards to the workspace root, or to some configured root path. I have tried adding the setting `"javascript.preferences.importModuleSpecifier": "non-relative"` but it does not seem to have any effect.
- Symbols imported using absolute paths are not resolved by the static code analyzer, so it is not possible to e.g. jump to definition. Example: `import { renderDifferential } from './render';` works; `renderDifferential` is recognized as a function and enjoys full code intelligence. `import { renderDifferential } from '/lib/render.js';` does not.

**Comment by mjbvz** [comment] 2018-10-22 21:16
Please try keeping it to one problem per issue


1. Is tracked by https://github.com/Microsoft/TypeScript/issues/24779

2. Did you configure `baseUrl` in your [`jsconfig`](https://code.visualstudio.com/Docs/languages/javascript)?

3. This is tracked by https://github.com/Microsoft/TypeScript/issues/13730

**Comment by oskargustafsson** [comment] 2018-10-23 18:10
1. That's good, but how does TypeScript issues relate to VS Code JS issues?
1. I tested adding `{
	"compilerOptions": {
		"baseUrl": "."
	}
}` and after that absolute paths are generated instead, nice! They still don't contain a leading `/`, which has to be manually added. Also, adding the leading slash triggers issue 3. It is a bit awkward though, that `baseUrl` is a "compiler option", considering that JS is not a compiled language - especially now that native [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is gaining support.
1. Same here, will the TypeScript issue's resolution have positive implications for JS editing in VS Code?

How should I move forward? Maybe drop 1 and 3, as they are already tracked, and create a new issue for 2?

**Comment by mjbvz** [comment] 2018-10-23 18:20
TypeScript (the tooling) powers both our built-in JavaScript and our TypeScript intellisense. These are the correct upstream issues for JavaScript

2 is by design. The slash being added is the same as 3. The reasons that a jsconfig is required is that there are lots of different module systems with different ways of resolving paths. The jsconfig tells us how to handle these

I think this addresses the original questions so I'm closing this issue but feel free to follow up here if the explanation is not clear

**Closed by mjbvz** 2018-10-23 18:20 UTC
Labels: javascript, needs more info
