### ISSUE TITLE
VSCode launch configuration uses wrong path

### ISSUE THREAD

**Issue by SirWindfield** [Microsoft/vscode#23282] opened 2017-03-27 14:27 UTC
### Overview
- VSCode Version: 1.10.2
- OS Version: Windows 10
- Node Version: 7.7.1

### Installed Extensions:
abusaidm.html-snippets
AdamCaviness.theme-monokai-dark-soda
akamud.vscode-theme-onedark
alefragnani.Bookmarks
alefragnani.project-manager
anseki.vscode-color
be5invis.vscode-icontheme-nomo-dark
brunnerlivio.materialcolorsnippets
capaj.vscode-standardjs-snippets
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
codezombiech.gitignore
Compulim.indent4to2
cssho.vscode-svgviewer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
dbankier.vscode-instant-markdown
donjayamanne.githistory
donjayamanne.jquerysnippets
donjayamanne.python
DotJoshJohnson.xml
dzannotti.vscode-babel-coloring
EditorConfig.EditorConfig
eg2.tslint
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
felipecaputo.git-project-manager
flowtype.flow-for-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
hars.CppSnippets
hashhar.gitattributes
HookyQR.beautify
HookyQR.GitHubIssues
hoovercj.ruby-linter
humao.rest-client
ianhoney.task-master
ilich8086.launcher
ithildir.java-properties
joelday.docthis
KnisterPeter.vscode-github
LaurentTreguier.vscode-simple-icons
lukehoban.Go
michelemelluso.code-beautifier
minhthai.vscode-todo-parser
mohsen1.prettify-json
ms-mssql.mssql
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.PowerShell
msjsdiag.debugger-for-chrome
Orta.vscode-jest
PeterJausovec.vscode-docker
PKief.material-icon-theme
qinjia.view-in-browser
rebornix.Ruby
redhat.java
robertohuertasm.vscode-icons
seanmcbreen.Spell
Shan.code-settings-sync
silverlakesoftware.searchdocsets-vscode
slevesque.vscode-hexdump
steoates.autoimport
steve8708.Align
stevencl.addDocComments
tushortz.java-imports-snippets
tushortz.java-snippets
vector-of-bool.cmake-tools
vilicvane.es-quotes
vsmobile.vscode-react-native
wayou.vscode-todo-highlight
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
zhuangtongfa.Material-theme

__NOTE: Only `msjsdiag.debugger-for-chrome` is enabled within the workspace!__

### Steps to Reproduce:

1. Create a simple project using launch.json and an electron entry file.
2. try to debug main process. 

### What happens?
VSCode resolves the path of the `runtimeExecutable` wrong. Instead of `D:\Data\Desktop\theclassic-desktop/node_modules/.bin/electron.cmd` VSCode creates the path `d:\Data\Desktop\theclassic-desktop/node_modules/.bin/electron.cmd`, which does not exist on the device. Therefore the launch failes with no errors thrown (except an entry within the `CALL STACK` pane under the debug view. It says `No call stack available (vscode_backtrace: Internal Error: undefined is not a function)`. 

My `launch.json` looks like this:
```json
{
  "version": "0.2.0",
  "configurations": [{
    "name": "Debug Main Process",
    "type": "node",
    "request": "launch",
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
    "windows": {
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
    },
    "program": "${workspaceRoot}/src/main-process/main.js"
  }],
  "compounds": []
}
```

Looks like `${workspaceRoot}` lowers the first letter for some reason.

**Comment by dbaeumer** [comment] 2017-03-28 07:36
@isidorn assigning to you since this looks like debug / configuration resolver.

**Comment by isidorn** [comment] 2017-03-29 10:18
@bpasero it seems like the `workspace.resource` does not respect the casing of the driver letter since I pass it to the `configurationResovlerService` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L530)

**Comment by SirWindfield** [comment] 2017-03-29 10:35
If that is important, I have two drives, `C:` and `D:` where `C:` is the Windows drive and `D:` is used for any kind of data (programs, projects, music etc.). My projects and VSCode are both on the `D:` drive, the secondary drive.

**Comment by bpasero** [comment] 2017-03-29 13:04
@isidorn how is a lowercase drive letter a problem on a case insensitive file system? We have so many code that works with files that do not care about uppercase or lowercase drive letter, so why does it not work for debugging?

![image](https://cloud.githubusercontent.com/assets/900690/24455700/6e23ed2a-1445-11e7-945c-8ef8fd676743.png)

**Comment by isidorn** [comment] 2017-03-29 13:13
It is up to the debug adapter -> thus assigning to @roblourens

**Comment by SirWindfield** [comment] 2017-03-29 13:29
> @isidorn how is a lowercase drive letter a problem on a case insensitive file system? We have so much code that works with files that do not care about uppercase or lowercase drive letter, so why does it not work for debugging?

Not sure, my filesystem is NTFS on both drives. Starting the `Debug Main Process` using the above configuration fails silently and does not show any window nor any stack trace.

**Comment by roblourens** [comment] 2017-03-29 18:49
I'm not sure the drive path is actually the problem here. This is using the node debugger (legacy) and the error is `No call stack available (vscode_backtrace: Internal Error: undefined is not a function)`

**Comment by weinand** [comment] 2017-03-29 19:40
@SirWindfield the driveletter casing should not be the problem here.

This is a duplicate of #16059.
 
Adding a `"protocol": "inspector"` to your launch config should fix this issue for you.

**Comment by weinand** [comment] 2017-03-29 19:45
Oh, I noticed you are using Electron. In this case the `"protocol": "inspector"` option is not yet supported.

So I suspect that this is a duplicate of #22015 (which should be fixed in the VS Code Insiders build).

**Comment by SirWindfield** [comment] 2017-03-29 19:51
@weinand Oh sorry, I tried to look for the issue before reporting it, seems like I missed it. Sorry for the inconvenience. So using the Insider build should allow me to debug electron processes again?

**Comment by weinand** [comment] 2017-03-29 19:53
@SirWindfield no problem. Yes, please try the Insiders.

**Comment by SirWindfield** [comment] 2017-03-29 20:05
@weinand Thanks for your help. It works now :smile: Can I close the issue then?

**Comment by weinand** [comment] 2017-03-29 20:18
Sure. The Insiders will be released as stable in about a week.

**Closed** 2017-03-29 20:29 UTC
Labels: bug, debug, duplicate

**Comment by weinand** [comment] 2017-03-30 08:34
Added "verified" label because @SirWindfield did verify this issue.
