### ISSUE TITLE
没有代码提示了

### ISSUE THREAD

**Issue by artlifecq** [microsoft/vscode#87046] opened 2019-12-16 02:19 UTC
Issue Type: <b>Bug</b>

版本更新之后没有代码提示了

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (22.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
vscode-language-pack-zh-hans|MS-|1.41.1
vetur|oct|0.22.6

</details>

**Comment by artlifecq** [comment] 2019-12-16 02:20
![image](https://user-images.githubusercontent.com/19888055/70874573-b7d32600-1fed-11ea-9669-e899c511b654.png)

**Comment by jonas-wu** [comment] 2019-12-16 03:01
我这也一样，一直显示Loading

**Comment by RMacfarlane** [comment] 2019-12-16 16:28
duplicate of https://github.com/microsoft/vscode/issues/87034

**Closed by RMacfarlane** 2019-12-16 16:28 UTC
Labels: new release

**Comment by artlifecq** [comment] 2019-12-17 06:17
@RMacfarlane Downgrade to 1.35 is ok
![image](https://user-images.githubusercontent.com/19888055/70969907-0361fe80-20d8-11ea-8f87-5c48aa40da15.png)

**Comment by MATACE** [comment] 2019-12-17 09:51
Try to install MINGW.
