### ISSUE TITLE
VS Code crashes

### ISSUE THREAD

**Issue by jkristia** [Microsoft/vscode#34305] opened 2017-09-13 15:56 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
tslint|eg2|1.0.4
rest-client|hum|0.15.2
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.1

---

Steps to Reproduce:

1. VS Code crashes after latest upgrade. It has crashed 2 times in 10 minutes. I'm working on a angularJs project. The workflow is as follow
 - in first terminal (powershell) start TS with watch : >>tsc -w
 - in second terminal (powershell) start live server: >>live-server

After a little while VS Code will crash.
**Work around**:  Launch external shells and run the commands there. After doing this I have not seen any crash.

Reproduces without extensions: Have not tried.

Edit: add versions

- node v6.11.1
- tsc v2.4.2
- live-server v1.2.0

**Comment by Tyriar** [comment] 2017-09-16 00:34
Duplicate of https://github.com/Microsoft/vscode/issues/34301

**Closed by Tyriar** 2017-09-16 00:34 UTC
Labels: integrated-terminal, new release
