### ISSUE TITLE
Sync to Microsoft account failed

### ISSUE THREAD

**Issue by diverger** [microsoft/vscode#108484] opened 2020-10-11 11:51 UTC
Issue Type: <b>Bug</b>

When sign in to Microsoft account, it throws "Writing login information to the keychain failed with error 'ռλ������յ��������ݡ�".

VS Code version: Code - Insiders 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1, 2020-10-09T05:34:54.647Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.92GB (18.06GB free)|
|Process Argv| --crash-reporter-id e3368947-bfb6-4f07-b221-c98951fc9a64|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by alannt777** [comment] 2020-10-11 13:18
Duplicate of #108392

**Comment by Taikamya** [comment] 2020-10-11 23:45
Exact same problem for me. I just updated to 1.51.0-insider and I get the same error.

**Comment by RMacfarlane** [comment] 2020-10-23 23:05
@diverger Do you still see this in the latest insiders?

**Comment by diverger** [comment] 2020-10-23 23:45
It seems the bug has been fixed. Thanks.

**Closed** 2020-10-23 23:46 UTC
