### ISSUE TITLE
Moving  row causes wrong indentations

### ISSUE THREAD

**Issue by HanyuuFurude** [microsoft/vscode#78788] opened 2019-08-09 11:03 UTC
- VSCode Version: 1.37.0
- OS Version: microsoft windows 10 enterprise build 18950

Steps to Reproduce:

1. open a python file
2. using Move line Up/Down(Alt + UpArrow/DownArrow) function to move a line to other position
![out](https://user-images.githubusercontent.com/24761242/62774676-0caedf00-bad8-11e9-88fb-ab61a742ebd3.gif)

3. if you move a line through a line with different indentation, its indentation would bu changed.
4. that will cause the change of the program run logic

Does this issue occur when all extensions are disabled?: Yes(no formatting program worked)

**Comment by DonJayamanne** [comment] 2019-08-09 18:16
Duplicate of https://github.com/microsoft/vscode-python/issues/6886
(this is an issue with the Python extension).

**Comment by HanyuuFurude** [comment] 2019-08-10 02:10
Got it, thanks for your help.

**Closed** 2019-08-10 02:11 UTC
Labels: new release
