### ISSUE TITLE
Disable Italics.

### ISSUE THREAD

**Issue by ekoschik** [microsoft/vscode#92396] opened 2020-03-10 19:11 UTC
holy shit. i wrote up a discription, got a box as i submitted saying it would be clipped. hit ok, and its gone. are you kidding me?

How do i disable italics? If there's no way, shame. Shame shame shame. What on earth is a code editor doing italicizing text? randomly? by default, without a way to disable.

Someone thought they were clever. Someone was WRONG. LET ME SHOW MY DAMN CODE WITHOUT IT BEING RANDOMLY SQUIGGLY!!!

i did find a setting that amounts to a hack, for those that care:

    "editor.tokenColorCustomizations": {
        "textMateRules": [
          {
            "scope": [
                "comment",
                "comment.block",
                "comment.block.documentation",
                "comment.line",
                "constant",
                "constant.character",
                "constant.character.escape",
                "constant.numeric",
                "constant.numeric.integer",
                "constant.numeric.float",
                "constant.numeric.hex",
                "constant.numeric.octal",
                "constant.other",
                "constant.regexp",
                "constant.rgb-value",
                "emphasis",
                "entity",
                "entity.name",
                "entity.name.class",
                "entity.name.function",
                "entity.name.method",
                "entity.name.section",
                "entity.name.selector",
                "entity.name.tag",
                "entity.name.type",
                "entity.other",
                "entity.other.attribute-name",
                "entity.other.inherited-class",
                "invalid",
                "invalid.deprecated",
                "invalid.illegal",
                "keyword",
                "keyword.control",
                "keyword.operator",
                "keyword.operator.new",
                "keyword.operator.assignment",
                "keyword.operator.arithmetic",
                "keyword.operator.logical",
                "keyword.other",
                "markup",
                "markup.bold",
                "markup.changed",
                "markup.deleted",
                "markup.heading",
                "markup.inline.raw",
                "markup.inserted",
                "markup.italic",
                "markup.list",
                "markup.list.numbered",
                "markup.list.unnumbered",
                "markup.other",
                "markup.quote",
                "markup.raw",
                "markup.underline",
                "markup.underline.link",
                "meta",
                "meta.block",
                "meta.cast",
                "meta.class",
                "meta.function",
                "meta.function-call",
                "meta.preprocessor",
                "meta.return-type",
                "meta.selector",
                "meta.tag",
                "meta.type.annotation",
                "meta.type",
                "punctuation.definition.string.begin",
                "punctuation.definition.string.end",
                "punctuation.separator",
                "punctuation.separator.continuation",
                "punctuation.terminator",
                "storage",
                "storage.modifier",
                "storage.type",
                "string",
                "string.interpolated",
                "string.other",
                "string.quoted",
                "string.quoted.double",
                "string.quoted.other",
                "string.quoted.single",
                "string.quoted.triple",
                "string.regexp",
                "string.unquoted",
                "strong",
                "support",
                "support.class",
                "support.constant",
                "support.function",
                "support.other",
                "support.type",
                "support.type.property-name",
                "support.variable",
                "variable",
                "variable.language",
                "variable.name",
                "variable.other",
                "variable.other.readwrite",
                "variable.parameter"
            ],
            "settings": {
              "fontStyle": ""
            }
          }
        ]
    },

**Comment by jmadelaine** [comment] 2020-03-10 23:47
I had the same issue.

This looks like it is caused by the new semantic highlighting functionality. Most themes don't support it yet.

You can disable it in settings with `"editor.semanticHighlighting.enabled": false`.

**Comment by aeschli** [comment] 2020-03-11 13:54
That's not related to semantic highlighting. 

It's a duplicate of https://github.com/microsoft/vscode/issues/32579

What I wonder, why don't you pick a theme that doesn't use italics?
E.g. the Default+ doesn't. 
You could even think of take your favourite theme, remove the italics and publish it as a new extension for everyone.

**Closed by aeschli** 2020-03-11 13:54 UTC

**Comment by ekoschik** [comment] 2020-03-14 17:48
Oh wow, a theme either does, or does not, italicized text randomly, and
there's no way to disable it? Is that what you're saying?

Theme is color, no? Should it also be a font? Maybe the location of the
menu bar? No, I chose a color via the theme marketplace, then a font, and
now my code text is randomly italicized. That italics cannot be switched by
a setting is a massive, confusing gap.

Should every theme author make two versions? One with italics and one
without? The problem I have with vs code themes is that there's too many
already.

Evan
