### ISSUE TITLE
vscode can't open twon instance?

### ISSUE THREAD

**Issue by liminjun** [Microsoft/vscode#1116] opened 2015-12-09 02:08 UTC
I writing the fron-end code from Sublime Text3 to Visual Studio Code. But I only open one instance of vscode one times, sometimes, I should open another project at same time. Now the vscode on windows only support one intance one time?

**Comment by Tyriar** [comment] 2015-12-09 02:58
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/48

**Closed** 2015-12-09 05:31 UTC
