### ISSUE TITLE
Javascript ES6 class suggested code action is shown but no lightbulb appears

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode#47392] opened 2018-04-07 13:58 UTC
- VSCode Version:1.22.1
- OS Version: Fedora 27

Steps to Reproduce:

1. load this file:
https://github.com/natetarrh/frogger/blob/master/game.js
2. go to line 520 and see the dotted underscore, mouse over and see the suggestion to convert to a class declaration
3. click on it and see NO lightbulb to allow you to perform the action
4. copy and paste the Game function into a new file and it will now work

Yes, ran with 'code --disable-extensions'

**Comment by mjbvz** [comment] 2018-04-09 17:33
Thanks. Duplicate of https://github.com/Microsoft/TypeScript/issues/23235

**Closed by mjbvz** 2018-04-09 17:33 UTC
Labels: javascript, upstream
