### ISSUE TITLE
Intellisense and Error Detection Not working in 1.6.0

### ISSUE THREAD

**Issue by dijitalmunky** [Microsoft/vscode#13640] opened 2016-10-13 03:22 UTC
- VSCode Version: 1.6.0
- OS Version: Mac OS Sierra 10.12
- Plugins: ms-vscode.csharp 1.4.1, EditorConfig.EditorConfig 0.3.3
 
After upgrading from 1.5.3, Intellisense and Error Detection seem to have stopped working.  I am coding a .NET Core project written in C#.

What happens is that Intellisense and Error Detection show up (i.e. the red squiggly underlines) when I make an edit in my C# file.  However, after a moment, they disappear again and I can't get them to stay visible.

I noticed that JS/Node/Typescript users seem to be having a similar issue, So I will mention that we do have one JS file in this project as well as a `package.json`.  The purpose of this one JS file is to do a cross-platform script that will build the whole project in one go.  Regardless, this issue happens no matter if the JS File is opened or closed in VS Code.

**Comment by dijitalmunky** [comment] 2016-10-13 03:25
I just shut down VSCode completely and opened a different .NET Core project that had no JS/Node/Typescript files and the same thing is happening.

**Comment by elgerm** [comment] 2016-10-13 07:43
+1, javascript and angularjs intellisense stopped working. All my settings are gone too.

**Comment by djx339** [comment] 2016-10-13 09:07
Almost all the intellisenses stopped working for me on vscode 1.6

**Comment by dbaeumer** [comment] 2016-10-13 09:59
For the TS/JS code complete problem we have https://github.com/Microsoft/vscode/issues/13575 which we tracked down to be a problem in the tsserver. 

@jrieken assigning to you since the original reporter complains about C#

**Comment by dbaeumer** [comment] 2016-10-13 10:00
@djx339 could you open Help > Toggel Developer tools and see if there is anything in the console.

**Comment by jrieken** [comment] 2016-10-13 10:14
@dijitalmunky Lets focus on C# here. I need more information understand this because the simple sample works for me. There is the dev console (F1 > Developer Tools) and also the OmniSharp output (View > Output > Omnisharp Log). Please attach check them for errors/warnings and report back

<img width="464" alt="screen shot 2016-10-13 at 12 11 51" src="https://cloud.githubusercontent.com/assets/1794099/19345396/6e3bbd36-913e-11e6-9282-df01bffd9e9f.png">

**Comment by nakedpony** [comment] 2016-10-13 13:08
@jrieken I also have the same issue. There is nothing suspicious in logs during the error disappearance so I've made a small screencast to show how it happens: https://www.dropbox.com/s/mlwm9wrjk49zu73/vscode.mov?dl=0

Version 1.6.0 (1.6.0)
e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
2016-10-10T18:26:55.336Z

If you need more info just contact me.

**Comment by jrieken** [comment] 2016-10-13 14:09
Can someone try to get a small reproducible sample and attach it here? I am trying with a simple 2 file repo but that doesn't work...

**Comment by jrieken** [comment] 2016-10-13 14:18
@DustinCampbell does this ring a bell? do you see similar issues?

**Comment by DustinCampbell** [comment] 2016-10-13 14:47
I've received this issue over in the C# extension repo: https://github.com/OmniSharp/omnisharp-vscode/issues/812. Since a few people have solved the problem by rolling back to VS Code 1.5.3, it's potentially related.

Note that the C# extension hasn't shipped a release for a couple of sprints (~6 weeks), so there's no change to the extension.

**Comment by nakedpony** [comment] 2016-10-13 15:07
So I managed to reproduce it. It's not really a minimal project but a template one from Unity.
So steps are the following:
1. Create a new project in Unity (v5.4.0f3 Personal)
2. Select 2D project and add 2D asset package (This is the crucial part here. Without it all works normal)
3. Create a `simpleScript.cs` in `Assets` folder and open it from Unity via MonoDevelop which generates `.sla`. Close MonoDevelop.
4. Open the project folder via VSCode.
5. Create any compilation error in `simpleScript.cs` and you'll see error being displayed and then disappeared as you can find in my screencast.

[template_project_3.zip](https://github.com/Microsoft/vscode/files/527452/template_project_3.zip)

**Comment by nakedpony** [comment] 2016-10-13 15:32
@jrieken Version 1.5.3 (1.5.3) works just fine. So I guess to me it would be a nice workaround so far.

**Comment by leafi** [comment] 2016-10-13 15:57
Given that this is tagged 'needs more info': I posted more info & another non-Unity sample project that exhibits the issue at https://github.com/OmniSharp/omnisharp-vscode/issues/812#issuecomment-253550970 .

**Comment by djx339** [comment] 2016-10-14 01:58
@dbaeumer this is my console output
![snip20161014_2](https://cloud.githubusercontent.com/assets/5222084/19373185/c357e964-91f4-11e6-87b5-418a7734070f.png)

**Comment by vbrosch** [comment] 2016-10-14 06:05
Same problem here...

- VSCode Version: 1.6.1
- OS Version: MacOS Sierra 10.12
- Plugins: ms-vscode.csharp 1.4.1

@dbaeumer The developer console contains an error:
![screen shot 2016-10-14 at 07 56 46](https://cloud.githubusercontent.com/assets/22639607/19377176/3ef26f42-91e4-11e6-86f5-72fa53f24ce7.png)

**Comment by DJ-Icebear** [comment] 2016-10-14 07:48
Exact same problem here.
VSCode Version: 1.6.1
OS Version: MacOS El Capitan 10.11.5 
Plugins: ms-vscode.csharp 1.4.1

I downgraded to 1.5.3 and disabled auto-updates for now. That solved it.

**Comment by jrieken** [comment] 2016-10-14 08:11
@vbrosch Your problem seems to be different and it's likely a comment in one of the JSON-files.

**Comment by jrieken** [comment] 2016-10-14 08:37
Thanks for all the input. Closing this as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/812 and I suspect OmniSharp diagnostics provider (https://github.com/OmniSharp/omnisharp-vscode/issues/812#issuecomment-253741159)

**Closed by jrieken** 2016-10-14 08:37 UTC
Labels: duplicate

**Comment by dijitalmunky** [comment] 2016-10-14 15:04
@jrieken Sorry It took me so long to get back to you.  Work has been crazy these last couple days.

As indicated above, if I revert to 1.5.3 things work again.

I tried your sample project, and I couldn't get it to do it again either.


However, in my project that is happening in, I see two errors in the dev console:
- the one that @vbrosch  has indicated above - I have double and triple checked my `.json` file in the project and cannot find any comments in them.
- The second is this (it happens whenever I close a file tab):
![screen_shot_2016-10-14_at_8_54_14_am](https://cloud.githubusercontent.com/assets/9633271/19392217/1199307c-91ed-11e6-9c01-799908bb5494.png)

So, yeah looks like an omni-code thing.  I'll add info to their bug as well. Thanks!

**Comment by DustinCampbell** [comment] 2016-10-14 15:11
@dijitalmunky: Head over to https://github.com/OmniSharp/omnisharp-vscode/issues/812. We've got a solution in progress there.
