### ISSUE TITLE
Debugging within vscode using Babel sourcemaps.

### ISSUE THREAD

**Issue by Alanz2223** [Microsoft/vscode#13405] opened 2016-10-09 23:37 UTC
- VSCode Version:1.5.3
- OS Version:Windows 8.1

I am trying to attach a debugger to the Jest testing environment in order to debug and test my react app. After some wrestling, I can start the Jest client via npm by running the command `node --debug-brk=5858 --harmony node_modules/jest/bin/jest.js --runInBand` through npm. I can also set breakpoints, but the issue is that I am using a babel transformer and instead of having my code brake at the original source, it breaks at the transpiled output which is not very intuitive. 

This is my launch configuration

`{
            "name" : "Attach via jest",
            "type": "node",
            "request": "attach",
            "sourceMaps" : true,
            "port": 5858,
            "timeout" : 5000

 }`

And within my .babelrc I have the following

`{
    "presets" : ["react-native"],
    "sourceMaps" : "inline"
}`

for inline source maps. Now I am not too familiar with how the inline source maps are supposed to work and even less if vscode supports them. So I would like to know if anyone could me with getting vscode to obtain the sourcemaps from babel and break at the correct points on the original source, rather than the transpiled output. Are there any other options I overlooked?

**Comment by Alanz2223** [comment] 2016-10-12 00:45
@weinand I will also add that I added the "outDir" option to both the launch.json task and the .babelrc file, but vscode threw a "outDir" option not recognized.. Could it be that the attach option doesn't work with outDir? also I will point out that I upgraded to version 1.6

**Comment by catwarrior** [comment] 2016-10-27 10:15
the same thing happens to me.

VS Code v1.6.1
OS Windows 10 v10.0.14393
Node v6.5
babel 6.5.2

I'm trying to use `gulp-sourcemaps`, now it could break to the line as expected, the problem is I have to set the breakpoint both in transformed version of the code, and the original source code.

I didn't try inline option yet, I will try it later.

here is my vscode launch.json
![image](https://cloud.githubusercontent.com/assets/11207001/19763529/0511ec3e-9c71-11e6-8901-9d1d4e963d65.png)

code structure as:
`
- build
  - transformed code here.
- node_modules
- src
 - original js code here.
- package.json
`

**Comment by weinand** [comment] 2016-10-27 10:28
The values of the attribute `outFiles` must be glob patterns.
So if your generated *.js files live anywhere in the 'build' directory, the pattern would be:
```json
"outFiles": [ "${workspaceRoot}/build/**/*.js" ]
```

**Comment by weinand** [comment] 2016-10-27 10:32
@catwarrior if you are not using remote debugging, don't specify `localRoot` and `remoteRoot`.

**Comment by catwarrior** [comment] 2016-10-27 10:38
@weinand 

> if you are not using remote debugging, don't specify localRoot and remoteRoot.
yes, I'm doing remote debugging.

update the launch.json didn't help
`
"outFiles": [ "${workspaceRoot}/build/**/*.js" ]
`

**Comment by catwarrior** [comment] 2016-10-27 11:08
I got more information:

two file, let say: 
`src/tokenValidate.js`
![image](https://cloud.githubusercontent.com/assets/11207001/19765014/b7d6f4ca-9c78-11e6-867c-4c07b75fbde3.png)

`build/tokenValidate.js`
![image](https://cloud.githubusercontent.com/assets/11207001/19764989/93bec144-9c78-11e6-8cb3-860f62c11f2a.png)


1. set breakpoint in `src/tokenValidate.js`, the breakpoint won't work.

2. set breakpoint in `build/tokenValidate.js`, the breakpoint works.

3. set breakpoint in both of them, only the breakpoint in `build/code.js` works.

hope it helps.
best regards

**Comment by fkarlsson** [comment] 2017-02-01 16:39
Has anyone succeeded with this yet? I have the same problem.

**Comment by mherodev** [comment] 2017-02-16 22:16
I recently got local-dev and test-based debugging in VS Code working today with an app based on react-slingshot (https://github.com/coryhouse/react-slingshot)

I figured I'd share my `.babelrc`, `jest.json` and `launch.json` in hopes that it'd help anyone else trying to get the same thing done (below).

The key change I found around avoiding see transpiled code for us was related to `jest` code coverage. If we removed the code coverage configuration, we no longer saw transpiled output (with a lot of references to istanbul). The key to resolving this was adding the line: `"testRegex": "src/.*\\.test\\.js$"`

Feel free to lift from my configuration below.

### .babelrc
```json
{
  "presets": [
    "es2015",
    "latest",
    "react",
    "stage-0"
  ],
  "sourceMaps": "inline",
  "retainLines": true,
  "env": {
    "development": {
      "presets": [
        "react-hmre"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-remove-prop-types"
      ]
    },
    "test": {
      "plugins": []
    }
  }
}
```
### jest.json
```json
{
  "collectCoverageFrom": [
    "src/**/*.{js,jsx}"
  ],
  "coverageDirectory": "<rootDir>/coverage",
  "coverageReporters": [
    "html",
    "text-summary"
  ],
  "moduleNameMapper": {
    "\\.(css|scss)$": "identity-obj-proxy",
    "^.+\\.(gif|ttf|eot|svg|woff|woff2|ico)$": "<rootDir>/tools/fileMock.js"
  },
  "modulePaths": [
    "<rootDir>/src/"
  ],
  "testRegex": "src/.*\\.test\\.js$"
}
```
### launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Active Terminal",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "userDataDir": "${workspaceRoot}/.vscode/chrome",
      "webRoot": "${workspaceRoot}",
      "sourceMapPathOverrides": { "webpack:///*": "${webRoot}/*" }
    },
    {
      "name": "Debug Tests",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",
      "stopOnEntry": false,
      "args": [
        "--config", "tools/config/jest.json"
      ],
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
      "runtimeArgs": [
          "--nolazy"
      ],
      "sourceMaps": true,
      "console": "internalConsole",
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```

**Comment by silvenon** [comment] 2018-02-24 01:45
This is the part I was missing:
```
"sourceMapPathOverrides": { "webpack:///*": "${webRoot}/*" }
```
Thanks @mherodev!

**Closed** 2018-04-06 22:56 UTC
Labels: bug, debug
