### ISSUE TITLE
Renaming file case. A Rename record is not generated in git records

### ISSUE THREAD

**Issue by whyour** [microsoft/vscode#101776] opened 2020-07-06 05:54 UTC
- VSCode Version: 1.46.1
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. rename file case
2. git status show a new untraced files, should show renamed file

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2020-07-06 07:21
Duplicate of #93299

**Closed** 2020-07-06 07:36 UTC
