### ISSUE TITLE
SideBySideEditorControl: can not read property done of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7991] opened 2016-06-22 10:00 UTC
Can not easily repro this. But I got it with having two editor groups, and closing all of the tabs in one group one by one. Got an exception in the console

![screen shot 2016-06-22 at 11 59 30](https://cloud.githubusercontent.com/assets/1926584/16262673/e87d6ff8-3870-11e6-9962-1d5d98dad901.png)

**Comment by bpasero** [comment] 2016-06-22 10:01
@isidorn yes I am hunting this down for a while, super hard to reproduce. Happy to hear if you can find steps to reproduce.

**Comment by bpasero** [comment] 2016-06-22 10:50
@isidorn if it helps to reproduce, this must be related to closing the last editor in a group in the left area such as the right group moves to the position of the left one. Somehow during this move, I end up opening an editor which does not know in which group it belongs to...

**Comment by bpasero** [comment] 2016-06-27 12:41
I hate to close this but I really cannot reproduce this anymore, trying for 5 minutes. This is a tough one, please report back if you have any clue how to reproduce.

**Closed by bpasero** 2016-06-27 12:41 UTC
Labels: bug, tabs

**Comment by isidorn** [comment] 2016-06-27 12:47
I did not see it since then - I will reopen if I hit it again - I also tried reproducing but failed.
