### ISSUE TITLE
Settings merge: UX feedback

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#103950] opened 2020-08-04 13:12 UTC
I was invited to GitHub Codespaces where I turned on the settings sync. It reported some conflicts so I opened this diff mode:

<img width="1574" alt="Screenshot 2020-08-04 at 14 36 26" src="https://user-images.githubusercontent.com/101152/89294835-5802bb80-d660-11ea-80c2-4af8a5e2e110.png">

A few things that I found confusing about the UX:

1. Since this is the first other machine I'm adding to sync (so far, I've only had this enabled in VSCode Insiders on my Mac), why am I seeing a conflict?

2. Some of the diffs are plain reformatting (e.g., blank lines removed), why was it done?

3. The reformatting also stripped some of my comments (this is a data loss, technically speaking):

    <img width="1218" alt="Screenshot 2020-08-04 at 14 51 03" src="https://user-images.githubusercontent.com/101152/89296853-4373f280-d663-11ea-8012-799c15d57732.png">

4. Some lines seem to be moved from the top of the file:

    <img width="1200" alt="Screenshot 2020-08-04 at 14 43 12" src="https://user-images.githubusercontent.com/101152/89295275-06a6fc00-d661-11ea-9824-6c192df685af.png">
    
    to the bottom:
    
    <img width="1196" alt="Screenshot 2020-08-04 at 14 44 00" src="https://user-images.githubusercontent.com/101152/89295294-0c044680-d661-11ea-8c9d-af04cc0d2c74.png">
    
    It only happened for a couple of lines, I'm not sure why.

4. I'm not sure what "Accept **Merges**" means. Will that eventually sync back to my Mac machine and will I e.g. lose the comments?

    UPDATE: there's a confirmation after that. Maybe the button should say "Accept Merges..." (note the ellipsis.)
    
    <img width="547" alt="Screenshot 2020-08-04 at 15 04 39" src="https://user-images.githubusercontent.com/101152/89297249-d745be80-d663-11ea-85be-95e1ffadb193.png">

Previous similar issue: #102581

**Comment by sandy081** [comment] 2020-08-06 08:55
Thanks for the feedback.

> Since this is the first other machine I'm adding to sync (so far, I've only had this enabled in VSCode Insiders on my Mac), why am I seeing a conflict?

Because you have some settings configured in the opened code space and while turning on sync there are conflicts between your local and remote settings. 

The diff view is showing diff between the remote content and merged content (merging local with remote). We try to merge by adding contents to local file and we try to retain comments and order as much as possible. But I see in your case this is not happening completely. It would be great if you can share us with your local and remote settings contents to reproduce and explain why this is the case and fix it.

Anyways, there are improvements made to Settings Sync turning on experience recently and as part of it, I changed the flow, when there are conflicts while turning on sync, to align with manual sync. With this you will not see above conflicts view instead following:

- Turn on Sync on a second machine that has potential conflicts
- You get merge/replace dialog

<img width="650" alt="image" src="https://user-images.githubusercontent.com/10746682/89427920-147d7f80-d73c-11ea-8f9c-b589f64b6e6b.png">

- You choose to merge
- If there are conflicts, following dialog is shown asking user to merge manually

<img width="454" alt="image" src="https://user-images.githubusercontent.com/10746682/89476443-01de6700-d78b-11ea-94ba-8b5aa10d371c.png">

- This opens Manual Merge view allowing user to merge manually where user has options to accept local or remote or merge and resolve conflicts.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/10746682/89428102-50184980-d73c-11ea-9d2d-59cbfa20bda7.png">

I would request to please try it out again with latest insiders and let us know the feedback on new flow.

Thanks.

**Comment by borekb** [comment] 2020-08-09 16:14
Thanks, @sandy081, I'll be glad to do that. How do I reset reset the Codespaces' `settings.json` to the state before the merge? That version doesn't appear in the Settings Sync view if I'm not missing anything (I can only see remote versions).

BTW I'm attaching my "main" (remote) settings file: [`settings.json`](https://github.com/microsoft/vscode/files/5047981/settings.json.txt)

**Comment by sandy081** [comment] 2020-08-09 23:03
> How do I reset reset the Codespaces' settings.json to the state before the merge?

You can get that from `Sync Activity (Local)` view. This view is hidden by default and you can enable it from the `...` -> `views` in Settings Sync viewlet.

**Comment by borekb** [comment] 2020-08-10 20:34
Bad luck, Codespaces currently cannot turn sync on due to this error:

> Settings sync cannot be turned on because the current version (1.48.0-insider, 5696babbc1dce41788bae04b1a04ad35140bebfb) is not compatible with the sync service. Please update before turning on sync.

I'll try to do it again next week or so.

**Comment by borekb** [comment] 2020-10-30 14:12
This is an old issue, I didn't verify in the end, hopefully it doesn't matter too much anymore, right, @sandy081?

**Comment by sandy081** [comment] 2020-10-30 14:20
If you say so :). I think so too.

Closing this then.

**Closed by sandy081** 2020-10-30 14:20 UTC
Labels: needs more info, settings-sync
