### ISSUE TITLE
Typescript Incorrect line indentation braces inside of Case statement blocks

### ISSUE THREAD

**Issue by jon-valliere** [Microsoft/vscode#41358] opened 2018-01-09 16:56 UTC
- VSCode Version: 1.19.1
- OS Version: 10.13.2

Steps to Reproduce:

1. Setup workspace config

```
{
	// Exclude specific files from the explorer
	"files.exclude": {
		"**/.git": true,
		"**/.DS_Store": true,
		"src/**/*.js": {
			"when": "$(basename).ts"
		},
		"src/**/*.js.map": {
			"when": "$(basename)"
		}
	},
	// Format the document when saved
	"editor.formatOnSave": true,
	// Enables/Disables using spaces instead of tabs
	"editor.insertSpaces": false,
	// Enables/Disables automatic indentation detection
	"editor.detectIndentation": false,
	// Defines whether an open brace is put onto a new line for functions or not.
	"typescript.format.placeOpenBraceOnNewLineForFunctions": true,
	// Defines whether an open brace is put onto a new line for control blocks or not.
	"typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
	// Defines whether an open brace is put onto a new line for functions or not.
	"javascript.format.placeOpenBraceOnNewLineForFunctions": true,
	// Defines whether an open brace is put onto a new line for control blocks or not.
	"javascript.format.placeOpenBraceOnNewLineForControlBlocks": true
}
```

2. Create Typescript file with `Switch` and `Case` statements.  Add block braces inside of the `Case` block and format the document.  The braces are indented beyond the `Case` statement level.  They should align with `Case`.

See Attachment:
![screen shot 2017-12-30 at 2 11 31 pm](https://user-images.githubusercontent.com/21211770/34732656-e4d71cc4-f533-11e7-9920-290d288d52e4.png)

![screen shot 2018-01-12 at 1 04 30 pm](https://user-images.githubusercontent.com/21211770/34888725-5ddd478a-f799-11e7-980f-70e1b769c34d.png)

**Comment by mjbvz** [comment] 2018-01-12 22:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/18682

**Closed by mjbvz** 2018-01-12 22:47 UTC
Labels: editor, formatting, javascript, typescript, upstream

**Comment by jon-valliere** [comment] 2018-01-13 17:15
@mjbvz How is this a duplicate of #18682? - this bug deals with incorrect indentation when braces are present and not limited to switch-case statements.
