### ISSUE TITLE
False Reports of Multiple Definitions

### ISSUE THREAD

**Issue by JonasMS** [Microsoft/vscode#54487] opened 2018-07-17 16:24 UTC
- VSCode Version: 1.25.0
- OS Version: High Sierra 10.13.6

Steps to Reproduce:

1. Navigation to definition of React component (cmd + left-click)

Does this issue occur when all extensions are disabled?: Yes

I get this "popup" claiming multiple definitions, and yet both definitions point to the same line of code. This occurs for React classes and pure functions alike.

[#24861](https://github.com/Microsoft/TypeScript/issues/24861) claims the issue is resolved. I'm still having the issue with React components.

**Comment by mjbvz** [comment] 2018-07-17 18:10
Duplicate of #51459

**Closed by mjbvz** 2018-07-17 18:10 UTC
Labels: javascript
