### ISSUE TITLE
after the new v1.77 update the webview does not work

### ISSUE THREAD

**Issue by bethropolis** [microsoft/vscode#178834] opened 2023-03-31 18:01 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: windows 10

Steps to Reproduce:

1. updates vscode to v1.77
2.  open any webview be it extensions readme, extensions using it, the release notes etc

keep getting:
```
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by qadram** [comment] 2023-04-02 15:43
I'm getting the same issue.

**Comment by maciej-irl** [comment] 2023-04-03 12:21
However, some combination of restarting VSCode a dozen times, checking for updates twice, and silently contemplating evicting it from the Applications folder seems to have fixed it.

**Comment by mjbvz** [comment] 2023-04-03 21:25
Duplicate of #125993

**Closed by mjbvz** 2023-04-03 21:25 UTC
