### ISSUE TITLE
Add "always_show_minimap_viewport" option to always highlight visible area

### ISSUE THREAD

**Issue by paulklemm** [Microsoft/vscode#28499] opened 2017-06-12 09:15 UTC
Sublime Text knows the `always_show_minimap_viewport` setting for the minimap:

*If `true`, shows a rectangle on the minimap highlighting the file’s visible area. If `false`, only shows the rectangle when you hover the cursor over the minimap.* 
(Source: [http://docs.sublimetext.info/en/latest/reference/settings.html](http://docs.sublimetext.info/en/latest/reference/settings.html))

![screen_shot_2017-06-12_at_10_58_29](https://user-images.githubusercontent.com/2169489/27026947-dca0eb4a-4f5f-11e7-86ea-6a457514e433.png)

I did not find an option enable this behavior in Code, I assume it is not there. I suggest implementing this. It helps a lot when navigating the file. Personally I see no benefit in the default behavior of only showing it on mouse-over since this actively reduces the usefulness of the minimap.

**Comment by alexandrudima** [comment] 2017-06-13 09:31
Duplicate of #21784

**Closed by alexandrudima** 2017-06-13 09:31 UTC
