### ISSUE TITLE
files.autoSave: afterDelay causes distractingly blinking Source Control working indicator 

### ISSUE THREAD

**Issue by fj128** [Microsoft/vscode#29946] opened 2017-06-30 13:47 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows 7
---

Steps to Reproduce:

1. Configure "files.autoSave": "afterDelay", leave the default delay of 1000 ms.
2. Initialize an empty git repository in the current directory
3. Start editing a file, especially not under source control (so that there's no changed files and no git badge counter on the Source Control icon)
4. Observe that about once every 5 seconds or so a clock badge briefly appears on the Source Control icon and, if you have Source Control panel open, the blue dash moves above the commit message field.

![vscode-source-control-annoyance](https://user-images.githubusercontent.com/308111/27737578-4adbe786-5db1-11e7-94fb-25a893934196.gif)

Thats pretty annoying and distracting! It's less noticeable if you're editing a file under source control, since that "in progress" icon then doesn't appear out of the blue but replaces the number of changed files. It's also less noticeable when you don't have the source control panel open so there's no blue dash.

The cause is obvious: vscode saves the file you're actively working on every second, after some further delay the git plugin notices that something changed and asks git what exactly (which can be seen in the output console - Git) and while doing that indicates that it's busy.

Maybe just don't do that? Just don't show the busy indicator when routinely rescanning the source folder? And when autofetching too, by the way, if it does that now.

**Comment by joaomoreno** [comment] 2017-06-30 13:54
Can you confirm that this reproduces even without files.autoSave: afterDelay  ?

**Comment by fj128** [comment] 2017-06-30 14:02
With autosave disabled the busy indicator does not appear until after a few seconds after I save manually.

**Comment by joaomoreno** [comment] 2017-06-30 14:29
But it just appears once, not repeatedly? And the file isn't inside your workspace?

**Comment by fj128** [comment] 2017-06-30 15:21
When I save manually, the indicator appears only when I do that, not repeatedly by itself.

The file is inside the workplace, that's the entire reason why saving it triggers git source rescan. In particular, it does this according to the output window:

    git status -z -u
    git symbolic-ref --short HEAD
    git rev-parse master
    git rev-parse --symbolic-full-name --abbrev-ref master@{u}
    git rev-list --left-right master...origin/master
    git for-each-ref --format %(refname) %(objectname)
    git remote --verbose

**Comment by joaomoreno** [comment] 2017-07-03 08:38
Oh I see. I misunderstood. I thought it kept on refreshing even if you did no changes. Now I realise you're just annoyed by the refreshing animation.

We won't take the animation out by default, obviously, since it indicates that something is indeed happening. But maybe we can have a setting for it? Would you like to attempt a PR? Maybe something like `git.showProgress` with possible values `always | explicit | never`, defaulting to `always`, the current behaviour. `explicit` would prevent the automatic `status` calls from triggering progress.

It doesn't animated while automatically fetching, btw.

**Comment by glen-84** [comment] 2017-11-17 18:43
I'm seeing the following every few seconds:

```
git status -z -u
git symbolic-ref --short HEAD
git rev-parse ap/WEB-2751
git rev-parse --symbolic-full-name --abbrev-ref ap/WEB-2751@{u}
git rev-list --left-right ap/WEB-2751...origin/ap/WEB-2751
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
```

... which triggers the animation, and it's *really* distracting.

**Comment by joaomoreno** [comment] 2017-11-23 13:24
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Closed by joaomoreno** 2017-11-23 13:24 UTC
Labels: feature-request, git, good first issue, help wanted
