### ISSUE TITLE
v1.46 New file/window menu items not functional with no window open

### ISSUE THREAD

**Issue by richardowen** [microsoft/vscode#99998] opened 2020-06-12 14:03 UTC
**Versions**
- VSCode Version: 1.46.0
- OS Version: macOS 10.15.5 (Darwin x64 19.5.0)

**Overview**

In v1.46, the new file & new window menu items do not do anything when all windows are closed. The behaviour is the same with the keyboard shortcuts (Cmd+N, Cmd+Shift+N).

The bug is not present in v1.45.1.
The bug is present in the insiders build.

**Steps to Reproduce**
1. Open Visual Studio Code
1. Close all windows
1. From the File menu, choose either "New File" or "New Window"

**Expected Result**
1. A new file or window is opened

**Actual Result**
1. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-06-12 17:20
Duplicate of #99831 but this one has a better title and clearer description, and reports the problem occurring from menu options as well as keybindings.

I was not able to reproduce it on Windows, so it seems to be macOS-specific.

**Comment by richardowen** [comment] 2020-06-12 17:23
Yep it's the same issue. I'm afraid I didn't find that one while searching for duplicates.

**Comment by sbatten** [comment] 2020-06-15 18:47
I haven't found out the cause yet, but I can repro.

**Comment by sbatten** [comment] 2020-06-15 19:50
Looks like it was introduced by this change. https://github.com/Microsoft/vscode/commit/5356ceb23cca764874d675fc01f3c09839cb26f0

win is undefined when no window is open  https://github.com/microsoft/vscode/blob/5356ceb23cca764874d675fc01f3c09839cb26f0/src/vs/platform/menubar/electron-main/menubar.ts#L116-L119

**Comment by tabaddor** [comment] 2020-06-15 22:26
Is this still unresolved? I can't seem to reproduce this issue.

**Comment by bpasero** [comment] 2020-06-16 05:35
@sbatten thanks for the fix, yes this was a regression I introduced. I filed https://github.com/electron/electron/issues/24144 because the TypeScript types are not catching this issue.

**Closed by bpasero** 2020-06-16 05:35 UTC
Labels: bug, candidate, menus
