### ISSUE TITLE
Instant markdown preview displays text out of bounds when editor UI is zoomed out

### ISSUE THREAD

**Issue by SuperV1234** [Microsoft/vscode#19924] opened 2017-02-04 11:41 UTC
- VSCode Version: 1.9 and 1.10 insiders
- OS Version: Arch Linux x64

Steps to Reproduce:

1. Zoom editor out *(e.g. by pressing Ctrl+-)*
2. Open a markdown file and instant preview on the side
3. Text in the preview will go out of bounds 
4. Zooming the editor back to the default will fix the issue

![screenshot from 2017-02-04 11-36-41](https://cloud.githubusercontent.com/assets/918661/22618194/88f211cc-eace-11e6-9b72-c2867172c30c.png)

**Comment by mjbvz** [comment] 2017-02-06 18:29
Closing as duplicate of #5745

**Closed by mjbvz** 2017-02-06 18:29 UTC
Labels: duplicate, markdown, webview
