### ISSUE TITLE
Make to be able select and copy deleted text

### ISSUE THREAD

**Issue by dmitryuck** [microsoft/vscode#140024] opened 2022-01-03 08:39 UTC
I can not select a piece of code that I removed, I can only revert all, but if I need to copy it is not possible

![Screenshot_1](https://user-images.githubusercontent.com/20966824/147911857-1df02d86-db5c-4d9d-b523-f0d74825ff03.png)

**Comment by IllusionMH** [comment] 2022-01-03 12:36
/duplicate of #8226

Please see https://github.com/microsoft/vscode/issues/8226#issuecomment-528103843 for a way that is available at this moment.

**Closed** 2022-01-03 12:37 UTC
Labels: *duplicate, triage-needed
