### ISSUE TITLE
builtin shell closes with esc which is a keybinding for vim

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7319] opened 2016-06-07 11:54 UTC
- VSCode Version:1.2.0
- OS Version:ubuntu 16.4

while using vim on a remote server using esc will toggle the terminal

**Comment by Tyriar** [comment] 2016-06-07 19:11
Duplicate of https://github.com/Microsoft/vscode/issues/6455, coming in 1.3.0

**Closed by Tyriar** 2016-06-07 19:11 UTC
