### ISSUE TITLE
Autocomplete stopped working after 1.41 update.

### ISSUE THREAD

**Issue by hrds** [microsoft/vscode#87034] opened 2019-12-15 18:17 UTC
Issue Type: <b>Bug</b>

Every type of auto complete(snippets, intellisense etc) stopped working after 1.41 update. This issue reproducing on my laptop, on other computers everything is okay.

VS Code version: Code - Insiders 1.42.0-insider (cbeff45f80213db0ddda2183170281ed97ed3b12, 2019-12-13T07:08:57.560Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscodeintellicode|Vis|1.2.0

</details>

**Comment by gjsjohnmurray** [comment] 2019-12-15 21:25
Does the problem also happen if you launch with all extensions disabled?

**Comment by StebanDev** [comment] 2019-12-15 22:08
I have the exact same problem, tried in stable version and in insiders too. Got all extensions disabled, it is happening after 1.41 update, it works only for the first suggestion and then doesn't work anymore.
I noticed one of the code processes keep with 25% avg cpu load

**Comment by hrds** [comment] 2019-12-15 22:09
> I have the exact same problem, tried in stable version and in insiders too. Got all extensions disabled, it is happening after 1.41 update, it works only for the first suggestion and then doesn't work anymore.
> I noticed one of the code processes keep with 25% avg cpu load

i have same behavior, works only for first suggestion and without extensions too

**Comment by RMacfarlane** [comment] 2019-12-16 00:03
@hrds What languages are you coding in?

**Comment by hrds** [comment] 2019-12-16 07:53
@RMacfarlane JavaScript in this case, but it's problem with suggestions overall.

**Comment by St-Permiakov** [comment] 2019-12-16 14:21
Same issue here.
JavaScript, with extensions and without.

Intellisense stops responding alongside some other functions (like GoTo).
I guess it has something to do with imports and code size (removing most part of imports from js file may have helped), but I'm not sure.

Downgrade to 1.40 helps for sure, so it's a valid tmp fix.

Please, let us know when the issue is resolved somehow.

**Comment by aboe026** [comment] 2019-12-16 21:06
I'm seeing the same behavior as well. uninstalling vs-code then installing 1.41 did not seem to help.

**Comment by drillprop** [comment] 2019-12-16 21:43
Same for me. When i do "Restart TS server" for a one import it works, but then stops again and showing 'No Suggestions'.

**Comment by mjbvz** [comment] 2019-12-16 22:52
@hrds Do you see this issue in other files, such as json or html? 

Also does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by drillprop** [comment] 2019-12-17 00:46
I found workaround here: https://github.com/microsoft/TypeScript/issues/35716#issuecomment-566311104. At least it works for me.  It seems autocompletion with this extension works even better than before.

**Comment by jonas-wu** [comment] 2019-12-17 01:57
mark，I have the same problem.

**Comment by bailiyang** [comment] 2019-12-17 02:18
so do i
.cpp and .h and .js have no Autocomplete at all
i just use my vim + YCM now until fix Autocomplete

**Comment by hrds** [comment] 2019-12-17 06:17
> Autocomplete back again now
> what's happen

Same, I'm checking right now, everything works. idk what you did, but thanks

**Comment by givionte** [comment] 2019-12-17 07:27
I'm not having the same luck as the above 2, Intellisense is just showing Loading while hovering, and not providing autocomplete.  Extensions or not it is failing.  I am working with JS files, it appears like it is breaking when a file can be auto-imported.

I was able to produce a Typescript server error in the exthost log.  Turning off all extensions did not solve the issue, but the error was gone.

`[2019-12-17 14:38:19.524] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-12-17 14:38:19.525] [exthost] [error] Error: <semantic> TypeScript Server Error (3.7.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133314:23)
    at ScriptInfo.getDefaultProject (tsserver.js:134061:46)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:136599:48)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:136594:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:140251:87)
    at IOSession.Session.getFileAndProject (tsserver.js:140234:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:140684:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139539:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:47388)
	at h.dispatchResponse (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:206361)
	at h.dispatchMessage (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:205259)
	at c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:204735
	at l.fire (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
	at t.Reader.onLengthData (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:211825)
	at Socket.<anonymous> (c:\Users\dandm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:211473)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by slaci** [comment] 2019-12-17 07:31
Intellisense doesn't work for me either on `1.41.0` (win 10 1909) with a react-native project. I had to downgrade to `1.40.2` where ac is instant. If I install the `typescript@next` plugin for `1.40.2` then the same happens, no intellisense anywhere (thats a nightly build so maybe just broken atm, otherwise related).

**Comment by jsm1003** [comment] 2019-12-17 11:02
同样的问题，没有代码提示也没有 eslint 自动修复功能了

**Comment by alexdima** [comment] 2019-12-17 13:56
Hey, does anyone here have any steps or any commonalities? Is everyone having trouble with react based projects only?

**Comment by St-Permiakov** [comment] 2019-12-17 14:33
Well, not **React** based, but JS + ES6 Modules based.
Can't tell for others.

**Comment by drillprop** [comment] 2019-12-17 15:04
@alexdima I tested on  typescript and javascript react based projects, it's not working.  For some reason in typescript projects when i enable typescript@next extension, intellisense and autoimports works fine.

**Comment by givionte** [comment] 2019-12-17 15:21
@alexdima I've only tried with React JS files thus far.  Everything seems to work fine for the first minute or so, and than Intellisense starts failing.  I'm not sure if there is a way to get a log of Intellisense, but I didn't find anything digging around the dev log file folder.

**Comment by mckennatim** [comment] 2019-12-17 21:25
For me it autocomplete stopped a while ago on code insiders, switched to regular and it came back until 1.41. Just downgraded to 1.40 regular and all is good. 1.42 insiders is also broken

**Comment by fanzkday** [comment] 2019-12-18 02:12
@alexdima Can use lower version. 1.30 is working!

**Comment by fanzkday** [comment] 2019-12-18 02:14
Me, too. But, can use lower version, 1.30 is working!

**Comment by crysispht** [comment] 2019-12-18 06:57
I use typescript@next extension and choose the version of 3.6.*, it seems to work
![image](https://user-images.githubusercontent.com/16445318/71062938-ae40ee00-21a6-11ea-81b1-1a456a6ee7c0.png)

**Comment by jonas-wu** [comment] 2019-12-18 09:09
I added extension(JavaScript and TypeScript Nightly), and the problem is gone

**Comment by alexdima** [comment] 2019-12-18 09:46
@mjbvz From the comments, I think this is a problem with the specific `tsserver` version we shipped in 1.42

**Comment by Cellv2** [comment] 2019-12-18 18:46
Check the drive that your project is on. If it's on a different drive to the one you put your VS Code install on, try putting it on the same drive. Else install the nightly TS extension as mentioned above

This was raised a few weeks ago on insiders (#85889) - is down to the TS version. VS Code ships with TS 3.7.3, which has the issue

Fix is there (https://github.com/microsoft/TypeScript/issues/35512), but it's not out the gates yet

**Comment by mjbvz** [comment] 2019-12-20 02:15
@hrds So has the issue been fixed for you? Are your projects stored on non-c drives on windows? If so, please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by aboe026** [comment] 2019-12-21 00:46
i was seeing this issue and my projects are on a different drive than vscode is installed on, so there is probably some credence in that being the culprit. I've since downgraded to 1.4.0.2 so I cannot attempt the typescript workaround

**Comment by Cl00e9ment** [comment] 2019-12-21 11:15
For me the issue was a bit different: `Editor: Accept Suggestion On Enter` has been put to `off` after updating. Putting to `on` again fixed the problem.

**Comment by codenoobforreal** [comment] 2019-12-29 22:39
Use typescript@next is work for me!

**Comment by mjbvz** [comment] 2019-12-30 00:16
Closing this as a likely duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2019-12-30 00:16 UTC
Labels: javascript, needs more info, suggest

**Comment by prabhaw** [comment] 2020-01-18 07:19
i was seeing this issue and i install older version 1.40 it work fine for me.

**Comment by lomeat** [comment] 2020-02-04 16:14
> I added extension(JavaScript and TypeScript Nightly), and the problem is gone

WOW. Its worrks. Thank you man!

**Comment by gjsjohnmurray** [comment] 2020-02-05 10:29
> P.S. I honestly don't understand why I should install noname extension to use default features of editor.

As I understand the situation, that extension allows a 1.41 user to benefit in advance from a set of fixes that will land in 1.42, expected to ship later this week. @mjbvz is this true?
