### ISSUE TITLE
Typescript server has failed 5 times after restarting.

### ISSUE THREAD

**Issue by KenAtBigVision** [microsoft/vscode#123893] opened 2021-05-14 14:01 UTC
Issue Type: <b>Bug</b>

When starting VS Code I get this error

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id d2114473-6f94-46f1-8282-468828b3d1c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
markdown-toc|Ala|1.5.6
ACF-Snippet|ant|1.9.0
vscode-mjml|att|1.6.0
vscode-intelephense-client|bme|1.7.1
gulp-lattice|chr|0.2.0
jsrefactor|cms|2.20.6
bracket-pair-colorizer|Coe|1.0.61
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.4.0
php-intellisense|fel|2.3.14
vscode-env|Iro|0.1.0
RelativePath|jak|1.4.0
vscode-wordpress-hooks|joh|0.5.4
vscode-styled-components|jpo|1.5.2
vscode-postcss-sorting|mrm|3.0.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.6.0
nunjucks|ron|0.3.0
markdown-preview-enhanced|shd|0.5.18
sass-indented|syl|1.8.16
todo-list|Tza|1.6.0
vscode-import-cost|wix|2.15.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscod805cf:30301675

```

</details>

**Comment by egamma** [comment] 2021-05-14 16:10
Can you please provide more information about the project and its setup. Does it happen for any repository? Is there a way for us to reproduce the issue?

**Comment by LohitakshTrehan** [comment] 2021-05-15 08:00
Hi @egamma this issue is getting posted by many people now. I will attach the url of my issue here. There in comments do let me know if *.dmp files created later will be relevant for you.
My reported issue:https://github.com/microsoft/vscode/issues/123545#issue-886195317

**Comment by GaikwadPratik** [comment] 2021-05-16 22:27
I get the same thing in `DevContainer` on osx.

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

**Comment by bobmagicii** [comment] 2021-05-21 16:55
this has happened to me on occasion but never was able to pin it down. its always never while im working on typescript (since i dont work in typescript).

**Comment by mjbvz** [comment] 2021-07-01 20:39
Closing as we need more information from the original poster to investigate

**Closed by mjbvz** 2021-07-01 20:39 UTC
Labels: needs more info
