### ISSUE TITLE
Debug current line indicator missing

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode#58121] opened 2018-09-06 21:37 UTC
_From @tchapin on September 6, 2018 18:24_

## Environment data

- VS Code version: 1.27.1
- Extension version (available under the Extensions sidebar): 2018.8.0
- OS and version: Windows 10 64bit
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

debugger does not show current line at breakpoints or while stepping

## Expected  behavior

When a breakpoint is hit, the current line should be indicated and should follow the stepping.

## Steps to reproduce:
1. Change the setting "window.titleBarStyle" to "custom". After this, the current line indicator no longer appears. Reverting this setting to "native" does not resolve the issue.

![vscode debug missing current line](https://user-images.githubusercontent.com/6968474/45177031-c2462380-b1df-11e8-9984-33ca8ae64595.gif)

_Copied from original issue: Microsoft/vscode-python#2505_

**Comment by brettcannon** [comment] 2018-09-06 21:37
_From @tchapin on September 6, 2018 20:12_

Update:
This problem only exists when the folder was opened via UNC path. it works correctly when the same folder is opened via mapped drive letter.

**Comment by weinand** [comment] 2018-09-06 23:35
@brettcannon did this work correctly in the previous version of VS Code (1.26.1)?

**Comment by tchapin** [comment] 2018-09-07 12:52
Yes this works correctly at 1.26. It also works at 1.27 until the "window.titleBarStyle" is set to "custom". Also, see comment about UNC vs drive letter.

**Comment by weinand** [comment] 2018-09-10 08:07
duplicate of #58106

**Closed** 2018-09-10 08:07 UTC
Labels: *duplicate, bug, debug, new release
