### ISSUE TITLE
1.18 Insiders using default electron icon?

### ISSUE THREAD

**Issue by Jaykul** [Microsoft/vscode#36710] opened 2017-10-22 19:42 UTC
Like it says in the title, I updated today and the VS Code icon is missing in favor of the blurry Electron circle.

![image](https://user-images.githubusercontent.com/192942/31865610-7ee6f718-b73f-11e7-87dd-3fc68001efd3.png)

- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T15:35:45.848Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
armsnippet|art|0.7.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
vscode-great-icons|emm|2.1.17
vsc-material-theme|Equ|1.0.5
code-runner|for|0.7.4
fontsize-shortcuts|fos|1.4.0
rest-client|hum|0.15.3
easy-icons|jam|0.3.1
vstsbuildstatus|jep|0.7.1
Angular2|joh|2.9.0
copy-github-url|mat|0.1.0
theme-monokai-pro-vscode|mon|1.1.2
azure-account|ms-|0.1.3
PowerShell|ms-|1.4.3
sublime-keybindings|ms-|2.9.1
vscode-code-outline|pat|0.0.11
vscode-docker|Pet|0.0.20
startanyshell|rem|0.3.1
vscode-icons|rob|7.16.0
code-settings-sync|Sha|2.8.3
cucumber|ste|0.9.6
ayu|tea|0.8.0
tmlanguage|Tog|0.8.4
expand-selection-to-scope|vit|0.2.0
bootstrap-3-snippets|wcw|0.1.0
better-align|wwm|1.1.6
sublime-commands|Zar|0.1.0
html-css-class-completion|Zig|1.11.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-10-22 20:25
Duplicate of #36665

**Comment by mjbvz** [comment] 2017-10-23 04:12
closing as duplicate of #36665

**Closed by mjbvz** 2017-10-23 04:12 UTC
Labels: duplicate, workbench
