### ISSUE TITLE
Newest version clobbers window manager keyboard shortcuts

### ISSUE THREAD

**Issue by bjnsn** [microsoft/vscode#86130] opened 2019-12-03 17:56 UTC
Issue Type: <b>Bug</b>

Windows manager ShiftIt no longer controls the window size/position after the most recent version update. Windows of other applications continue to work properly. Changing keyboard shortcuts appears to have no effect. Controlling directly through window manager menu not controlling either. Either shortcuts or menu based control works with common apps such as Chrome, Finder, Firefox, Outlook, Photoshop.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment] 2019-12-07 03:56
@bjnsn can you test with `1.40.1` https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-darwin-stable.zip to confirm if its a regression from electron update. Thanks!

**Comment by bjnsn** [comment] 2019-12-09 16:29
@deepak1556 `1.40.1` works correctly unlike `1.40.2`.

**Comment by deepak1556** [comment] 2019-12-09 17:51
Thanks for confirming!

**Comment by bpasero** [comment] 2019-12-12 15:09
@deepak1556 maybe same cause as https://github.com/microsoft/vscode/issues/84195 ?

**Comment by deepak1556** [comment] 2019-12-12 21:55
@bpasero they are not same, #84195 has been since electron 6.0.0 upgrade and this only started with `1.40.2` and electron `6.1.5` so something in this bump broke.

**Comment by bjnsn** [comment] 2020-01-15 21:36
FYI, this appears to have been fixed. My settings with it working are:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by isidorn** [comment] 2020-06-09 19:19
@deepak1556 @bpasero should we close this, seems to be fixed?

**Closed** 2020-06-10 06:15 UTC
Labels: accessibility, confirmed, electron, electron-6-update, mac, upstream
