### ISSUE TITLE
SFTP extension keeps reporting 'no such file' on vscode 1.56

### ISSUE THREAD

**Issue by mpalencia** [microsoft/vscode#123249] opened 2021-05-07 07:06 UTC
- VS Code Version: 1.56
- OS Version: Windows 10

Steps to Reproduce:

1. Update VScode to 1.56
2. Install SFTP by liximomo
3. setip up and make sure upload when ctrl+s is On
4. try to upload your code to the server.. it always display an error, but on vscode 1.55 version it works smoothly

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gjsjohnmurray** [comment] 2021-05-07 07:18
Have you reported the issue to the extension developer?

**Comment by gjsjohnmurray** [comment] 2021-05-07 08:01
Also #123240

**Comment by n3svarbu** [comment] 2021-05-07 08:48
VSCode Node version was bumped and supposedly this issue appered because of a regression on streams in Node v14, that's been fixed in v15

**Comment by INTMIN** [comment] 2021-05-07 09:01
I've had this problem, too

**Comment by INTMIN** [comment] 2021-05-08 02:49
I looked at the most recent changes to this warehouse two years ago.... @mpalencia @gjsjohnmurray @n3svarbu

**Comment by deepak1556** [comment] 2021-05-09 01:46
/duplicate https://github.com/microsoft/vscode/issues/122325

`1.56` updated the node version from `12.18.3` to `14.16.0`, please ensure the extension works with this node version.

**Closed by deepak1556** 2021-05-09 01:46 UTC
