### ISSUE TITLE
--verbose non-stop reports log file changes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#126477] opened 2021-06-16 12:39 UTC
Version: 1.58.0-insider
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:18:57.982Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-18-generic

- start code with `--verbose` from the terminal
- the terminal is non-stop flooded with logged watcher evens caused by the log file entries

![image](https://user-images.githubusercontent.com/6461412/122220351-8a03c180-ceb0-11eb-81b2-9bb1b607f3c9.png)

**Comment by rzhao271** [comment] 2021-06-17 15:46
On Windows, I confirmed that there are many log messages showing up, but it's not a consistent stream of file watcher changes.

**Comment by aeschli** [comment] 2021-06-18 05:01
All trace statements go in a log file. That log file is watched by a file watcher, which generates a trace statement for it. 

@sandy081 I assume we need a watcher for the log file? Where is it set up?

**Comment by sandy081** [comment] 2021-06-18 13:59
> I assume we need a watcher for the log file? Where is it set up?

Yes, it is for updating logs in output channels. Here:

https://github.com/microsoft/vscode/blob/51ed283cc5bfcce3d331b5e028d0a2be3d8fafaf/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L205

I can see if I can stop watching when channel is not visible.

**Comment by aeschli** [comment] 2021-06-21 14:10
We could add a new flag to the watchOptions in `IFileService.watch` to turn off verbose logging for the given location.

**Comment by sandy081** [comment] 2021-06-22 13:45
That would be nice.

**Comment by awerlang** [comment] 2021-06-27 04:29
I noticed this behavior starting with the June release. I always launched Code with `--verbose` and I can tell from older logs that renderer1.log was getting caught by file watcher before, the regression here is that it became repetitive.

**Comment by bradleyharden** [comment] 2021-07-14 16:42
I'm using 1.58.1 on Ubuntu 20.04. I noticed that any time VS Code was running, it would peg a core at 100%. Upon running with `--verbose` and `--disable-extensions`, I found this logging issue.

Is this issue the cause of my 100% CPU problem? Or is this an unrelated issue? For the moment, VS Code is unusable to me. I'll have to try downgrading to 1.56.1.

**Comment by deepak1556** [comment] 2021-07-14 17:01
@bradleyharden the cpu issue is unrelated to this logging regression, can you open a separate issue with the output of `code --status` and `code --verbose`. Thanks!

**Comment by bpasero** [comment] 2021-08-31 05:42
I see this without any editor opened and without output view being opened, can we reconsider this?

**Comment by sandy081** [comment] 2021-09-08 16:35
It seems I am not using our watcher to watch the log files, instead I am polling myself because our file watcher is not working with spdlog changes. See following

https://github.com/microsoft/vscode/blob/90347144857be0a9977b6636e3680718512e67a2/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L168-L181

I am using our watcher only to check if the log files are created or not. Once the log files are created, I am disposing the watcher. See below:

https://github.com/microsoft/vscode/blob/47a956eb2e074720cdc51aef74ba61d628061c54/src/vs/workbench/contrib/logs/common/logs.contribution.ts#L91-107

So, I am not sure why our watcher is still watching these log files. May be disposing above watcher has a bug? or using file service to resolve the log file is automatically adding the file to watch list? Hence assigning to @bpasero to see where this is happening.

Nevertheless, I added a change to not to poll when the log channel is not active.

**Comment by bpasero** [comment] 2021-09-09 06:49
I just verified that disposing `IFileService.watch` does not have a bug using this code:

```ts
const dispose = fileService.watch(URI.file('/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/browser/parts/editor/editorCommands.ts'));
fileService.onDidFilesChange(e => {
	console.log(e);
});

setTimeout(() => {
	console.log("disposing");
	dispose.dispose();
}, 5000);
```

**Comment by sandy081** [comment] 2021-09-09 07:34
Output channel uses editor control but I do not think it is opened in above fashion. Moreover I see these file watching statements for log files only on Linux but not on Mac. I assume you also checked on Linux.

**Comment by bpasero** [comment] 2021-09-09 07:41
Yeah this only applies to workbench editors that are opened in the workbench editor area.

**Comment by bpasero** [comment] 2021-09-10 07:33
@sandy081 not all watchers are disposed as you can see from my debug logging:

![image](https://user-images.githubusercontent.com/900690/132817199-73913ac8-e49c-4a0a-bf59-8635699653f2.png)

**Comment by bpasero** [comment] 2021-09-10 16:37
Doing a window reload and putting breakpoints I can see that for the number of calls to `watch`, there is also calls to `dispose`. But maybe on a window reload, all these files exist, but not directly on startup?

Unfortunately it is hard to debug a production build right on startup, so if we cannot figure this out we need to add some more logging around here:

https://github.com/microsoft/vscode/blob/47a956eb2e074720cdc51aef74ba61d628061c54/src/vs/workbench/contrib/logs/common/logs.contribution.ts#L92-L98

**Comment by sandy081** [comment] 2021-09-13 16:32
@bpasero Right that not all watchers are getting disposed as the telemetry file is not getting created and the watcher is watching until it is created. This is because telemetry is disabled in dev by default. In the product, telemetry is enabled by default and therefore this shall not happen by default. However I added a fix to create telemetry channel only when telemetry is enabled which means watcher will not start watching.

I also added debug logs whenever watching starts and disposed. Lets see if it gives us any insights

**Comment by bpasero** [comment] 2021-09-14 07:24
Running this build from today:

```
DEBUG [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/userDataSync.log
log.ts:283 DEBUG [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/renderer1.log
log.ts:283 DEBUG [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/telemetry.log
log.ts:283 DEBUG [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/main.log
log.ts:283 DEBUG [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/sharedprocess.log
log.ts:283 DEBUG [Registering Log Channel] Stopped watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/renderer1.log
log.ts:283 DEBUG [Registering Log Channel] Stopped watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092347/main.log
```

It looks like many watchers are not disposed.

**Comment by sandy081** [comment] 2021-09-14 07:54
Yes, I also observed the same

```
[2021-09-14 09:24:16.834] [renderer1] [debug] [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/userDataSync.log
[2021-09-14 09:24:16.835] [renderer1] [debug] [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:16.835] [renderer1] [debug] [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/telemetry.log
[2021-09-14 09:24:16.835] [renderer1] [debug] [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/main.log
[2021-09-14 09:24:16.835] [renderer1] [debug] [Registering Log Channel] Started watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/sharedprocess.log
[2021-09-14 09:24:16.860] [renderer1] [debug] [Registering Log Channel] Stopped watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:16.863] [renderer1] [debug] [Registering Log Channel] Stopped watching: file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/main.log
[2021-09-14 09:24:16.995] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:17.022] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/main.log
[2021-09-14 09:24:17.047] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:17.051] [renderer1] [trace] Started polling file:///home/parallels/.config/Code%20-%20Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:17.185] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:17.186] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/main.log
[2021-09-14 09:24:17.484] [renderer1] [trace] Settings Sync: Initializing accounts
[2021-09-14 09:24:17.487] [renderer1] [trace] Settings Sync: Getting accounts for microsoft
[2021-09-14 09:24:17.514] [renderer1] [trace] [File Watcher (node.js)] [ADDED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/output_1_20210914T092416
[2021-09-14 09:24:17.514] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/renderer1.log
[2021-09-14 09:24:17.515] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/main.log
[2021-09-14 09:24:17.515] [renderer1] [trace] [File Watcher (node.js)] [ADDED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/sharedprocess.log
[2021-09-14 09:24:17.516] [renderer1] [trace] [File Watcher (node.js)] [ADDED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/telemetry.log
[2021-09-14 09:24:17.517] [renderer1] [trace] [File Watcher (node.js)] [ADDED] /home/parallels/.config/Code - Insiders/logs/20210914T092415/userDataSync.log
```

Missing watchers to dispose are `sharedprocess.log`, `telemetry.log` and `userDataSync.log`. From the above log, it seems fs service is sending change event when these files are added but my listener is not getting them:

https://github.com/microsoft/vscode/blob/758bf79321a04ec4c5a31ea5f0f11ed4101ee1c3/src/vs/workbench/contrib/logs/common/logs.contribution.ts#L101-L119

I suspect there is a race condition here - I am adding the listener too late and by that time change events are getting missed. I will see if I can adjust above code to handle this missing change events.

**Closed** 2021-09-14 12:51 UTC
Labels: debt, output, file-watcher, log

**Comment by sandy081** [comment] 2021-09-14 12:53
To verify:

- To be verified on Linux
- Start code with verbose mode `code-insiders --verbose`
- Open window log and make sure you do not see file watcher reporting changes for renderer log file
