### ISSUE TITLE
[typescript] Syntax highlighting fails after ++ < characters

### ISSUE THREAD

**Issue by nickjbishop** [Microsoft/vscode#37528] opened 2017-11-02 14:33 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

![bad-parsing](https://user-images.githubusercontent.com/3863014/32331368-9586dd6e-bfda-11e7-8a3d-197c407cf540.gif)

Type the following code in a blank TypeScript file:
```javascript
let a = 0;
a++ < 0;
let b = 0;
```
All syntax highlighting for lines following the `++ <` characters is corrupted (for example, in the GIF above, the `let` keyword has the wrong colour). The following expressions are fine:
```javascript
(a++) < 0
a++ <= 0
a++ > 0
++a < 0
```
The issue does not occur when JavasScript syntax highlighting is used.

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-11-02 14:47
This has already been fixed in Insiders.

**Comment by mjbvz** [comment] 2017-11-02 17:37
Duplicate of #35768

**Closed by mjbvz** 2017-11-02 17:37 UTC
Labels: duplicate, javascript
