### ISSUE TITLE
[I18N] Unresolved message placeholder

### ISSUE THREAD

**Issue by kthoms** [Microsoft/vscode#29569] opened 2017-06-27 10:36 UTC
When opening a typescript file I get the message 
<img width="1433" alt="screenshot 26" src="https://user-images.githubusercontent.com/265597/27583545-1431e984-5b35-11e7-804c-0a7192c1094b.png">

Note the brackets ```({1)}```. Seems to be a error in the order of the closing brackets.

**Comment by mjbvz** [comment] 2017-06-29 21:38
Duplicate of #28371

**Closed by mjbvz** 2017-06-29 21:38 UTC
Labels: duplicate
