### ISSUE TITLE
cannot create random location multi cursor

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5160] opened 2016-04-11 10:19 UTC
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

i can create multi cursors by alt-shift+(down/up) but not all the time where i wanna place cursor is exactly under the line in sublime i can press and hold ctrl and click to add cursor to any location but seems theres no way to do this in vscode . is there a way to to this without hacking ctrl-d combination by adding prefix?

**Comment by Tyriar** [comment] 2016-04-13 17:51
Duplicate of https://github.com/Microsoft/vscode/issues/3091

**Closed by Tyriar** 2016-04-13 17:51 UTC

**Comment by alexandrudima** [comment] 2016-04-28 09:52
@NikosEfthias It is possible with Alt+click, but there is no way to change it to Ctrl+click.

**Comment by NikosEfthias** [comment] 2016-04-28 11:23
@alexandrudima  the problem is alt click is reserved on linux by the X
