### ISSUE TITLE
vscode unable to modify folder name or move folder and files for other path.

### ISSUE THREAD

**Issue by RicardoGEsteves** [microsoft/vscode#203900] opened 2024-01-31 14:45 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Go to vscode with a medium to gib project and try to create any action on existing files or folders. 
2. After making the action the action(move, delete, cut) it will stay in an infinite loop and sometimes throw an error.
3. Already trying to clear cache
4. Already restart my vscode
5. Already clear temp files
6. Already deleted cache folder from next.js
7. Already reboot vscode window with command pallet.

Nothing worked, I'm just able to create add new entries(create new files and folders), or make the other actions directly on windows on folder explorer.

![Capture](https://github.com/microsoft/vscode/assets/30535937/739fb069-0608-41c5-bd54-059527b35243)

![Capture2](https://github.com/microsoft/vscode/assets/30535937/81c23ff4-5917-4ac3-801e-ae03c54d4bc6)

![Capture3](https://github.com/microsoft/vscode/assets/30535937/21252704-ef3e-4d4b-9e6e-86e1f524ffa3)

![Capture4](https://github.com/microsoft/vscode/assets/30535937/cc8823eb-c167-4cf2-a708-4bed808d8964)

**Comment by gjsjohnmurray** [comment] 2024-01-31 16:00
Maybe another Windows process has the folder locked. Did you try a Windows reboot?

**Comment by lramos15** [comment] 2024-01-31 16:20
Likely duplicate of https://github.com/microsoft/vscode/issues/184145

**Closed by lramos15** 2024-01-31 16:20 UTC

**Comment by RicardoGEsteves** [comment] 2024-01-31 16:21
> Maybe another Windows process has the folder locked. Did you try a Windows reboot?

Yes was exactly that, I'm pretty sure that was powershell.
It's fine now, thanks @gjsjohnmurray .
