### ISSUE TITLE
File paths not clickable in the output pane in Insiders

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23228] opened 2017-03-26 03:37 UTC
- VSCode Version: Insiders dated 24th March, 2017
- OS Version: Windows and Mac

The Go extension sends the build output to the output channel, and the file path (absolute path) is clickable and takes you to the right file/line in the stable build.

![image](https://cloud.githubusercontent.com/assets/16890566/24328304/93afa62c-119a-11e7-8729-54326b97e59d.png)

In the insiders, there are no such links

![image](https://cloud.githubusercontent.com/assets/16890566/24328310/cfe294a6-119a-11e7-96c4-5552ff001f50.png)

**Comment by dbaeumer** [comment] 2017-03-27 07:42
This is output window. Assigning to @isidorn

**Comment by isidorn** [comment] 2017-03-27 09:14
Probably duplicate of https://github.com/Microsoft/vscode/issues/22869
fyi @jrieken

**Comment by ramya-rao-a** [comment] 2017-03-27 20:26
@isidorn #22869 is about providing doc links in a whole new language.

In the Go extension, we just send simple text to the output channel.
If the text is absolute path, then it used to be clickable and now its not.

So still a bug and a regression.

**Comment by dbaeumer** [comment] 2017-03-28 07:41
@isidorn to my knowledge the workbench registeres some predefined document link providers (regexp matching) for the output panel. @bpasero knows the details were the code lives. I think we need to adjust this on our end to now register the link provider with a right scheme.

**Comment by ramya-rao-a** [comment] 2017-03-28 14:51
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputLinkProvider.ts#L40 ?

**Comment by dbaeumer** [comment] 2017-03-28 15:06
Looks like the right place to me. @jrieken do you know which scheme the output panel uses. inmemory: or?

**Comment by isidorn** [comment] 2017-03-28 15:08
@dbaeumer https://github.com/Microsoft/vscode/issues/22869#issuecomment-287789649

**Comment by dbaeumer** [comment] 2017-03-28 15:10
@isidorn thanks

**Comment by jrieken** [comment] 2017-03-28 15:11
Thanks @isidorn! Again the new matching of the doc-selector...

**Closed** 2017-03-28 15:50 UTC
Labels: bug, important
