### ISSUE TITLE
screen cheese with german and keybinding ui

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5983] opened 2016-04-29 13:51 UTC
see screen shot. text overflows the box

![screen shot 2016-04-29 at 15 28 06](https://cloud.githubusercontent.com/assets/1794099/14918028/2289a618-0e22-11e6-865b-a268d2f6c7b2.png)

**Comment by alexandrudima** [comment] 2016-04-29 14:19
Neeeein!!

**Comment by alexandrudima** [comment] 2017-04-18 15:18
Duplicate of #24817

**Closed by alexandrudima** 2017-04-18 15:18 UTC
Labels: bug, editor-contrib, i18n, keybindings
