### ISSUE TITLE
Auto Scrolling in Markdown Preview

### ISSUE THREAD

**Issue by raztd** [Microsoft/vscode#13658] opened 2016-10-13 09:04 UTC
It would be nice if when I'm editing a .md file and have the MD Preview open on the side, it would scroll along with the source file.
Something like what stackedit.io does

![previewscrolling](https://cloud.githubusercontent.com/assets/6805609/19343037/32272386-913d-11e6-8e88-558fe995eb3b.png)

**Comment by gregvanl** [comment] 2016-10-13 16:46
Duplicate of https://github.com/Microsoft/vscode/issues/5047
Please feel free to vote up this issue.

**Closed by gregvanl** 2016-10-13 16:46 UTC
