### ISSUE TITLE
Broke code while clicking save button

### ISSUE THREAD

**Issue by officefish** [microsoft/vscode#131517] opened 2021-08-24 14:13 UTC
Issue Type: <b>Bug</b>

Vscode makes page with broken (js/jsx) code while clicking 'save' function 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.98GB (6.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.22
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
debugger-for-chrome|msj|4.12.4
cmake|twx|0.0.17
gitblame|wad|8.1.0

</details>

**Comment by mjbvz** [comment] 2021-08-24 18:18
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by mjbvz** [comment] 2021-09-01 00:06
Closing as likely caused by an extension

**Closed by mjbvz** 2021-09-01 00:06 UTC
Labels: needs more info
