### ISSUE TITLE
Support for iPadOS

### ISSUE THREAD

**Issue by raphaellueckl** [microsoft/vscode#75126] opened 2019-06-08 12:06 UTC
I always hoped that web development will become possible on the iPad. Now, it seems we are getting there.

I always hoped that you guys would provide VSC for iPad. Now it would be the best time to make this step forward imho. Being able to code on the iPad is probably going to give you a huge push forward. I would love to see that happen! :)

Keep up the good work, thanks for everything!

**Comment by egamma** [comment] 2019-06-09 12:40
duplicate of #70764

**Closed by egamma** 2019-06-09 12:40 UTC
Labels: *duplicate
