### ISSUE TITLE
Expose extension URL for SSL white listing

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#2161] opened 2016-01-21 21:43 UTC
doc feedback verbatim:
"please put the extensions url that visual studio code tries to reach (all of them) when installing an extension. we use ssl inspection and installation is failing because of certificates. but I'm not able to whitelist the urls"

**Comment by mmrath** [comment] 2016-01-22 03:40
I have the same issue with VS Code. I think the next version will have the option to disable SSL cert checking. But a proper solution could be to add the ssl inspection CA to the list of CA used by node/vs code?

**Comment by joaomoreno** [comment] 2016-01-25 09:33
Duplicate of #155

**Closed by joaomoreno** 2016-01-25 09:33 UTC
Labels: install-update
