### ISSUE TITLE
Window is 1 pixel too large when maximized on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96252] opened 2020-04-27 12:36 UTC
For my 2 monitor setup (vscode on left), when launching a maximized window there is a white bar on the right:

![image](https://user-images.githubusercontent.com/2193314/80372535-89414380-8848-11ea-9938-8e214cdd841b.png)

After restoring and then maximizing the window the bar turns blacks:

![image](https://user-images.githubusercontent.com/2193314/80372709-cb6a8500-8848-11ea-99e0-f3916edd1bc6.png)

Native apps do not do this, I've seen something similar happen in Teams.

**Comment by deepak1556** [comment] 2020-04-27 20:38
Thanks for the report! merging as duplicate of https://github.com/microsoft/vscode/issues/85310

**Closed by deepak1556** 2020-04-27 20:38 UTC
Labels: windows
