### ISSUE TITLE
Latex stdout is not converted to latex (was: Julia help text rendered poorly)

### ISSUE THREAD

**Issue by hammer** [microsoft/vscode#133172] opened 2021-09-15 12:38 UTC
### How are you mainly using the Jupyter extension?

- [X] Notebooks (.ipynb)
- [ ] Interactive Window and or Cell Scripts (ex. .py files with \#%%)
- [ ] Both

### What happened?

I wrote `?rand` (for example) in a Julia notebook cell and executed the cell. The output of the cell was very difficult to read, as it appears to be unrendered LaTeX with strange coloring:

> \begin{verbatim}
rand([rng=GLOBAL_RNG], [S], [dims...])
\end{verbatim}
Pick a random element or array of random elements from the set of values specified by \texttt{S}; \texttt{S} can be
\begin{itemize}
\item an indexable collection (for example \texttt{1:9} or \texttt{('x', "y", :z)}),

### What flavor of VS Code are you using?

Stable

### Jupyter Extension Version

v2021.8.2041215044

### Jupyter logs

```shell
\begin{verbatim}
rand([rng=GLOBAL_RNG], [S], [dims...])
\end{verbatim}
Pick a random element or array of random elements from the set of values specified by \texttt{S}; \texttt{S} can be
\begin{itemize}
\item an indexable collection (for example \texttt{1:9} or \texttt{('x', "y", :z)}),


\item an \texttt{AbstractDict} or \texttt{AbstractSet} object,


\item a string (considered as a collection of characters), or


\item a type: the set of values to pick from is then equivalent to \texttt{typemin(S):typemax(S)} for integers (this is not applicable to \href{@ref}{\texttt{BigInt}}), to $[0, 1)$ for floating point numbers and to $[0, 1)+i[0, 1)$ for complex floating point numbers;

\end{itemize}
\texttt{S} defaults to \href{@ref}{\texttt{Float64}}. When only one argument is passed besides the optional \texttt{rng} and is a \texttt{Tuple}, it is interpreted as a collection of values (\texttt{S}) and not as \texttt{dims}.
\begin{quote}
\textbf{compat}

Julia 1.1

Support for \texttt{S} as a tuple requires at least Julia 1.1.

\end{quote}
\section{Examples}
\begin{verbatim}
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2

julia> rand((2, 3))
3

julia> rand(Float64, (2, 3))
2×3 Array{Float64,2}:
 0.999717  0.0143835  0.540787
 0.696556  0.783855   0.938235
\end{verbatim}
\begin{quote}
\textbf{note}

Note

The complexity of \texttt{rand(rng, s::Union\{AbstractDict,AbstractSet\})} is linear in the length of \texttt{s}, unless an optimized method with constant complexity is available, which is the case for \texttt{Dict}, \texttt{Set} and \texttt{BitSet}. For more than a few calls, use \texttt{rand(rng, collect(s))} instead, or either \texttt{rand(rng, Dict(s))} or \texttt{rand(rng, Set(s))} as appropriate.

\end{quote}
\rule{\textwidth}{1pt}
\begin{verbatim}
rand([rng::AbstractRNG,] s::Sampleable)
\end{verbatim}
Generate one sample for \texttt{s}.
\begin{verbatim}
rand([rng::AbstractRNG,] s::Sampleable, n::Int)
\end{verbatim}
Generate \texttt{n} samples from \texttt{s}. The form of the returned object depends on the variate form of \texttt{s}:
\begin{itemize}
\item When \texttt{s} is univariate, it returns a vector of length \texttt{n}.


\item When \texttt{s} is multivariate, it returns a matrix with \texttt{n} columns.


\item When \texttt{s} is matrix-variate, it returns an array, where each element is a sample matrix.

rand([rng::AbstractRNG,] s::Sampleable, dim1::Int, dim2::Int...)   rand([rng::AbstractRNG,] s::Sampleable, dims::Dims)

\end{itemize}
Generate an array of samples from \texttt{s} whose shape is determined by the given dimensions. \rule{\textwidth}{1pt}
\begin{verbatim}
rand(rng::AbstractRNG, d::UnivariateDistribution)
\end{verbatim}
Generate a scalar sample from \texttt{d}. The general fallback is \texttt{quantile(d, rand())}. \rule{\textwidth}{1pt}
\begin{verbatim}
rand(rng, d)
\end{verbatim}
Extract a sample from the p-Generalized Gaussian distribution 'd'. The sampling procedure is implemented from from [1]. [1] Gonzalez-Farias, G., Molina, J. A. D., \& Rodríguez-Dagnino, R. M. (2009). Efficiency of the approximated shape parameter estimator in the generalized Gaussian distribution. IEEE Transactions on Vehicular Technology, 58(8), 4214-4223. \rule{\textwidth}{1pt}
\begin{verbatim}
rand(::AbstractRNG, ::Distributions.AbstractMvNormal)
\end{verbatim}
Sample a random vector from the provided multi-variate normal distribution. \rule{\textwidth}{1pt}
\begin{verbatim}
rand(::AbstractRNG, ::Sampleable)
\end{verbatim}
Samples from the sampler and returns the result. \rule{\textwidth}{1pt}
\begin{verbatim}
rand(d::Union{UnivariateMixture, MultivariateMixture})
\end{verbatim}
Draw a sample from the mixture model \texttt{d}.
\begin{verbatim}
rand(d::Union{UnivariateMixture, MultivariateMixture}, n)
\end{verbatim}
Draw \texttt{n} samples from \texttt{d}.
```

### What coding language are you working with?

Julia

### VS Code Version?

1.60.1

### What OS are you running on?

Mac

### Running Jupyter locally or remotely?

Local

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DonJayamanne** [comment] 2021-09-15 16:56
@rchiodo this is actually a duplicate of https://github.com/microsoft/vscode-jupyter/issues/6802
We need to discuss whether we should support latex in regular outputs or not (ipywidgets, plain html output, stdout, etc)

**Comment by hammer** [comment] 2021-09-15 18:18
> We need to discuss whether we should support latex in regular outputs or not

In the case of Julia, the ability to look up documentation with `?` is quite fundamental, so I'm a big +1 for LaTeX support. That said, the use of LaTeX in Julia's docs is primarily for document structure and formatting, so another solution upstream might be to convert their LaTeX to Markdown on the client...

**Comment by mjbvz** [comment] 2021-09-15 23:30
@DonJayamanne Should we close this as an upstream issue?

**Comment by hammer** [comment] 2021-09-16 01:52
Ah it appears https://github.com/microsoft/vscode-jupyter/issues/6529 is a precise duplicate of this issue as well.

**Comment by rchiodo** [comment] 2021-09-27 20:46
This is something that Jupyter supports so it should be supported in VS code (otherwise people can't open notebooks generated with Jupyter).

**Comment by mjbvz** [comment] 2021-10-04 19:22
I'm closing this as an upstream issue based on my understanding of it. Rendering of output is left up to output renderers; we don't  parse the output looking for latex  but a renderer could

**Closed by mjbvz** 2021-10-04 19:22 UTC
Labels: notebook, notebook-output

**Comment by rchiodo** [comment] 2021-10-04 19:50
@mjbvz shouldn't the core support text/latex as an output type though? We had discussing submitting a PR to core to make so that markdown-it could actually render these latex outputs. They can also be embedded in regular markdown, so it seems to make sense to support them in the core itself.

**Comment by mjbvz** [comment] 2021-10-04 20:18
Latex output was #123144 (which should be reopened since it was since reverted)

If there's something else you think VS Code itself should handle, please open an issue that explains the problem independently of Jupyter directly

**Comment by rchiodo** [comment] 2021-10-04 20:21
@mjbvz sorry I was incorrect. This issue here is about latex outputs in stdout or text/html. For example the julia kernel generates latex in their stdout.
