### ISSUE TITLE
Messy RTL words on text highlights

### ISSUE THREAD

**Issue by it-giants** [microsoft/vscode#147040] opened 2022-04-07 22:10 UTC
Simply once I highlight any RTL text such as Arabic text it's getting reversed and resulting in very hard to modify this specific area,
take a look on the screenshot it can explain itself:

Wrong Text: https://prnt.sc/7dw-JNnEmJeP
Correct Text: https://prnt.sc/prW7TiRThrPg

the original text suppose to be "تأكد من ال"

Hopefully someone can help.

Regards.

**NOTE: this issue happened after some recent updates it wasn't like that before.**

**Comment by alih70442** [comment] 2022-04-08 05:28
If you type any rtl base text after any ltr base chars, it get reversed too.
for example:
| وی اس کد
you can try this by coping last line to vscode.

**Comment by gjsjohnmurray** [comment] 2022-04-08 07:19
Have you updated to 1.66.1 yet?

/needsMoreInfo

**Comment by alexdima** [comment] 2022-04-08 07:23
Duplicate of https://github.com/microsoft/vscode/issues/99589 . Please update to 1.66.1

**Closed by alexdima** 2022-04-08 07:23 UTC
Labels: needs more info, editor-RTL
