### ISSUE TITLE
Popup Error Message

### ISSUE THREAD

**Issue by jeffhoye** [Microsoft/vscode#45998] opened 2018-03-16 20:22 UTC
Issue Type: <b>Bug</b>

After updating this week, vscode error messages are now popups!  In the attached screen shots, I'm not interested in the specific errors, I know what they are and how to handle them.  I'm reporting that now they are popups rather than banner messages or notifications in the lower right corner.

Steps to reproduce: write some code that doesn't properly compile and try to debug it.

With extensions:
![image](https://user-images.githubusercontent.com/1181397/37542959-5ce75a04-2936-11e8-9ae1-dda652fb73fb.png)

Without extensions:
![image](https://user-images.githubusercontent.com/1181397/37542935-4322e584-2936-11e8-95c3-92dcec7abc7c.png)

Love vscode!  Thanks for making this great product!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4080)|
|Memory (System)|31.94GB (17.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-code-outline|pat|0.0.13
vscode-icons|rob|7.21.0
vim|vsc|0.11.2

</details>
Reproduces without extensions

**Comment by jeffhoye** [comment] 2018-03-16 20:31
Settings:
```
{
    "workbench.iconTheme": "vscode-icons",
    "vim.overrideCopy": true,
    "vim.useSystemClipboard": true,
    "go.lintTool": "gometalinter",
    "go.lintFlags": [
        "--disable-all",
        "--enable=errcheck",
        "--enable=gotype",
        "--enable=varcheck",
        "--enable=vet",
        "--enable=vetshadow"
    ], 
    "workbench.sideBar.location": "left",
    "files.eol": "\n",
    "workbench.editor.enablePreview": false, 
    "editor.tabSize": 2,
    "terminal.integrated.scrollback": 999999,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    },
    "git.confirmSync": false,
    "go.testEnvVars": {
       <secret>
    },
    "gitlens.keymap": "alternate",
}
```

**Comment by isidorn** [comment] 2018-03-19 10:06
We decided on this behavior on purpose since all those errors are blocking. You can not contiue debugging and they should be modal imho
More about this can be found here https://github.com/Microsoft/vscode/issues/44720

Closing as designed

**Closed by isidorn** 2018-03-19 10:06 UTC
Labels: new release
