### ISSUE TITLE
What happened to highlight all occurrences with cursor?

### ISSUE THREAD

**Issue by Brade** [Microsoft/vscode#31081] opened 2017-07-19 22:40 UTC
Used to be able to place the cursor on a word and it would highlight all occurrences in gray, both in the document and in the scroll bar. This seems to be gone. Also when I hover over a word, the word "any" shows up in a tooltip. What is this for?

**Comment by rebornix** [comment] 2017-07-19 22:59
@Brade I suppose you are using JavaScript/TypeScript, right?  The hover tooltip you see is actually the intellisense support from TypeScript LSP. BTW, can you check your personal setting or workspace setting to see if `editor.selectionHighlight` is set to `false` which disables this feature.

**Comment by Brade** [comment] 2017-07-19 23:25
Ya, just noticed it still works when putting cursor on words that aren't functions. Would be nice if this weren't a limitation.

**Comment by rebornix** [comment] 2017-07-20 18:26
This seems being controlled by our JS/TS extension.

**Comment by mjbvz** [comment] 2017-07-25 01:05
@Brade Can you make sure you are on VSCode 1.14.2. There were a few bugs in 1.14.1 that could have disabled this feature.

Also can you provide some example code that shows where occurrences should be highlighted but are not

Thanks

**Comment by Brade** [comment] 2017-07-25 13:45
Yep, it's 1.14.2. I attached 3 screenshots: one with PHP code which behaves normally when I highlight a word. The next 2 are javascript, where the first is highlighting the word "item" but doesn't get them all. The second has the cursor on "bind" but nothing happens.

<img width="1560" alt="ghc1" src="https://user-images.githubusercontent.com/46009/28575061-cd360c46-711d-11e7-832b-24ef2b33459f.png">

<img width="1561" alt="ghc2" src="https://user-images.githubusercontent.com/46009/28575057-ccbc1bfc-711d-11e7-80b6-17c479ac0c99.png">

<img width="1562" alt="ghc3" src="https://user-images.githubusercontent.com/46009/28575056-ccba39ae-711d-11e7-9130-70f8fc5c33aa.png">

**Comment by mjbvz** [comment] 2017-07-26 04:50
This is by design. JavaScript tries to highlight all references of a symbol when you place the cursor over that symbol. That's why only the `item` occurrences inside the function scope are highlighted in your second example. Other languages such as PHP that do not provide logic for finding actual  occurrences just do basic string searches for occurrences

The `bind` one looks like a bug though. Can you share a small code sample that demonstrate this problem

**Comment by Brade** [comment] 2017-07-26 13:35
Can't really provide more than what I already have. Anyway, I actually prefer the way things behave in PHP files, where every occurrence in the file is highlighted.

**Comment by mjbvz** [comment] 2017-07-27 05:48
@Brade Do you get any completions or intellisense for jquery? For example, after typing `$('a').` do you get completions? If you are not seeing completions, we may not have loading the typing information for jquery. This would explain why the various occurrences of `bind` are not being highlighted.

Please just share a stripped down version of the actual source along with the screenshots. The code does not need to be complete or functional, it just needs to demonstrate this issue

**Comment by mjbvz** [comment] 2017-08-02 19:40
Closing as by-design. Please make sure you have the typings for jquery installed and open a new issues if you notice some occurrences of a method or property not being highlighted as expected

**Closed by mjbvz** 2017-08-02 19:40 UTC
Labels: needs more info, typescript
