### ISSUE TITLE
Terminating building task will hang VS Code

### ISSUE THREAD

**Issue by jyavenard** [microsoft/vscode#100905] opened 2020-06-24 03:36 UTC
Visual Studio Vode version: 1.46.1, on Windows 10 x64 18363
![image](https://user-images.githubusercontent.com/505748/85496478-b418ff80-b61f-11ea-9822-e4ba6f6c2624.png)

In launch.json I have a "build" task which will run an external command to build my project.

Either closing the terminal window, or selecting Terminal ->Terminate Task -> Selecting build task
will cause VS Code to hang, which requires the application to be terminated.

This is a recent regression.

![image](https://user-images.githubusercontent.com/505748/85496196-466cd380-b61f-11ea-9c02-bd0795122ed4.png)

**Comment by alexr00** [comment] 2020-06-24 08:33
@jyavenard can you try setting the `terminal.integrated.windowsEnableConpty` setting to `false` and see if it still happens?

**Comment by jyavenard** [comment] 2020-06-24 08:39
I can confirm that this indeed fixes the problem.

**Comment by alexr00** [comment] 2020-06-24 08:46
This is a duplicate of https://github.com/microsoft/vscode/issues/76548.

**Closed by alexr00** 2020-06-24 08:46 UTC
Labels: needs more info

**Comment by jyavenard** [comment] 2020-06-24 09:03
Bug #76548 states that this would be resolved with Windows 1903 and later. I'm running 1909.

I can reproduce this issue 100% of the time. 

I didn't experience this issue prior the latest Visual Studio Code update of a couple of weeks ago.

**Comment by alexr00** [comment] 2020-06-24 14:40
In that case, it is a duplicate of https://github.com/microsoft/vscode/issues/71966, which is the other conpty freeze bug.
