### ISSUE TITLE
Adding Jupyter Notebook causes disconnect from remote server

### ISSUE THREAD

**Issue by loganriggs** [microsoft/vscode#196089] opened 2023-10-20 14:31 UTC
Type: <b>Bug</b>

When ssh-ed into a node, I can run files & use the terminal normally.

However, when I add a new jupyter notebook, it shows the "setting up ssh..." notification, then disconnects from the server. 

This does not happen when I add a new text file or python file, so maybe an extension. 

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'SSH: 209.137.198.14' could not be established  Canceled
Connection to 'SSH: 209.137.198.14' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (2.81GB free)|
|Process Argv|--crash-reporter-id 85b6318c-39aa-4637-93f5-fc2aac3f163d|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: 209.137.198.14' could not be established  Canceled

Connection to 'SSH: 209.137.198.14' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythoncet0:30866520
h48ei257:30867296
pythontbext0:30864172

```

</details>

**Comment by itrase** [comment] 2023-10-20 15:30
I'm having this exact same issue, also when ssh-ed in. I can also execute the notebook through code - it's only when it's brought up on the VSCode UI that the disconnect occurs.

**Comment by rebornix** [comment] 2023-10-20 17:49
This is a duplicate of https://github.com/microsoft/vscode/issues/195617 and we are working on a fix now. Let's track this in https://github.com/microsoft/vscode/issues/195617, thank you!

**Closed by rebornix** 2023-10-20 17:49 UTC
Labels: triage-needed
