### ISSUE TITLE
Not being notified when a settings file from a root folder (Other than first)  is changed

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29438] opened 2017-06-26 09:30 UTC
Enable experimental file watching service.

Set up multi-root workspace, say Root A, Root B.
Let's say Root B has a setting `"editor.lineNumbers" = "off"` in its `.vscode` folder.

Open a file from Root B, observe that line numbers are off.
Change the value of the setting to `"relative`" and save.

Expected: File from Root B should show relative line numbers
Observed: Nothing changes

Only works after refresh

**Comment by bpasero** [comment] 2017-06-26 09:53
@sandy081 I cannot reproduce, just tried it out. Can you run with --verbose to see the file events being reported to you in the console.

@sandy081 is this setup a transition from 1-2 folders within the window or after a restart?

@Tyriar can you also try please

**Comment by sandy081** [comment] 2017-06-26 14:13
There is no transition involved.. I opened the workspace with multiple roots and then I changed the settings file under a second root folder for which events are not triggered or something.

I ran with --verbose and I do not see any events for file changes in second root folder

**Comment by Tyriar** [comment] 2017-06-26 14:45
@sandy081 what version and OS are you on?

**Comment by sandy081** [comment] 2017-06-26 16:00
![image](https://user-images.githubusercontent.com/10746682/27548462-4a650c44-5a99-11e7-80b0-7d3a1e1f2d7a.png)

**Comment by Tyriar** [comment] 2017-06-26 17:56
We're disabling the ability to have multiple roots in stable so this should not have an impact as it only appears to occur in the non-master folder. Moving to July as it doesn't block June.

**Comment by sandy081** [comment] 2017-06-27 14:04
@Tyriar Don't you think, this blocks early adoption / self host of multi root workspaces?

**Comment by Tyriar** [comment] 2017-06-27 16:43
Closing as duplicate of #29605, @sandy081 let me know if root B's path didn't start with root A's path (it's not a duplicate).

**Closed by Tyriar** 2017-06-27 16:43 UTC
Labels: bug, file-watcher, multi-root, workbench

**Comment by sandy081** [comment] 2017-06-28 07:05
Its dup of #29605
