### ISSUE TITLE
[ts] cannot find module

### ISSUE THREAD

**Issue by oleersoy** [Microsoft/vscode#53733] opened 2018-07-06 16:33 UTC
For [this repository](https://github.com/fireflysemantics/is) vscode draws a red squiqqly under the all `@fireflysemantics/is` targets :

```
import { isBoolean } from "@fireflysemantics/is";
```

The repository tests and builds fine though.  I suspect that it has something to do with excluding the tests in the `src` directory with the option:

```
  "exclude": ["**/*.spec.ts"]

```

**Comment by mjbvz** [comment] 2018-07-06 21:38
Can you please share a more complete example of your project structure or small sample project

**Comment by oleersoy** [comment] 2018-07-07 02:59
Ooops - Sorry - Forgot to paste the github URL.  I updated the original post.  Here's the URL again just in case:
https://github.com/fireflysemantics/is

**Comment by mitchellsimoens** [comment] 2018-08-14 15:07
I have the same issue (sorry, repo is a private repo). Interestingly, I can get rid of the red squiggly (and problem in problems tab) by commenting out the line and saving and then uncommenting the line and saving.

Tried closing code and reopening to see if this workaround just persists for a session but it didn't mark the issue after opening code again.

**Comment by mjbvz** [comment] 2018-09-07 22:31
The `is.spec.ts` file is not part of the `tsconfig.json` project due to the exclude rule:

```
  "exclude": ["**/*.spec.ts"]
```

Therefore the path mapping in the tsconfig is not applied. If you make the file part of a project with the path mapping, then everything works

**Closed by mjbvz** 2018-09-07 22:31 UTC
Labels: needs more info, typescript

**Comment by oleersoy** [comment] 2018-09-08 04:45
@mjbvz are you sure it should draw the red squiggly?  The typescript documentation uses `"exclude": ["**/*.spec.ts"]` do demo what `exclude is for:

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Also what VSCode is displaying is not consistent with the runtime.  Tests run fine.  The code compiles fine.  Yet VSCode is not happy.

It seems like just because we don't want something compiled, does not mean that we don't want to know that it is correct or that VSCode should signal that it is incorrect....unless I'm totally missing something ... would not be the first time :).

**Comment by mjbvz** [comment] 2018-09-10 06:29
The exclude pattern effectively says: spec files are not part of this project. This is how we are using the tsconfig's exclude. You should setup a project that does include the spec files if you want proper path mappings to apply in them

**Comment by oleersoy** [comment] 2018-09-10 13:32
Isn't the point of the `exclude` to exclude the files from compilation?

Why is can't path mapping and excluding something from compilation be two separate things?

**Comment by mjbvz** [comment] 2018-09-10 17:13
If you don't want this file in your main project, setup a separate tsconfig.json that includes your spec files and defines that path mapping

**Comment by oleersoy** [comment] 2018-09-10 18:05
Thanks - That's helpful, but now more files are needed when we could just have one to do the job.  We keep going around in circles on whether the VSCode behavior is correct or not.  It's not that I don't want the files in the project.  I want VSCode to analyze it correctly even though I've excluded it from compile time distribution.  

If this is not a bug, then I think you should be able to tell me why VSCode can't do that or why it's a bad idea?

**Comment by mjbvz** [comment] 2018-09-10 18:15
This is not a bug. A `tsconfig.json` file defines a project. This project is used for both build (emit) and intellisense because intellisense should generally match what the build will produce. 

If you want different different behavior for intellisense and build (such as having spec files in one but not in the other), create a separate `tsconfig.json` projects. One possible structure would be:

```
tsconfig.json # no excludes
tsconfig.base.json # spec exclude here
```

You can use the `extend` property in the tsconfig to minimize duplication

**Comment by oleersoy** [comment] 2018-09-10 18:31
The reason it's a bug is that intellisense could still work properly for the `*.spec` files even though they are excluded from output.  

Right now the intellisense is saying that I file cannot be resolved, even though it can.  

Resolving a file and excluding something from compiled output are two mutually exclusive areas and if VSCode is not designed to understand that then that's wrong.

**Comment by oleersoy** [comment] 2018-09-10 21:32
https://stackoverflow.com/questions/52265758/should-vscode-report-errors-for-ts-files-that-are-excluded-from-compilation
