### ISSUE TITLE
TreeItem tooltips get overridden when setting resourceUri

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#115745] opened 2021-02-04 12:05 UTC
In my tree view I use the resourceUri attribute, but this overrides the tooltip attribute. If the tooltip is not specified I would expect the default tooltip to be generated for the resourceUri, but if I've specified it myself it should be honoured.

**Comment by gjsjohnmurray** [comment] 2021-02-04 12:12
/duplicate of #113180 assuming you're using the current Stable build (1.52.1)

Please provide more information on future issues you raise. Using the "Report Issue" option from the Help menu will do that for you automatically.

**Closed** 2021-02-04 12:19 UTC
Labels: *duplicate
