### ISSUE TITLE
JSDoc not work properly with default values

### ISSUE THREAD

**Issue by OMendozaG** [microsoft/vscode#177529] opened 2023-03-17 21:20 UTC
- VS Code Version: Versión: 1.76.2
- OS Version: W11

Steps to Reproduce:

1. Create a function documentated with default value on parameter
`/**
 * Testing default values
 *
 * @param {boolean} [p=true] Parameter with default value
 * @returns {boolean} Return value
 */
function f(p = true) {
    return p;
}
`

2. Why not show on any description the default value por "p" parameter?
![Captura 1470 2023 03 17 22 19 27](https://user-images.githubusercontent.com/4358881/226055059-f752f477-b28f-4b5e-993f-89bc82b3c0fe.png)
![Captura 1471 2023 03 17 22 19 39](https://user-images.githubusercontent.com/4358881/226055063-7c0b35aa-a0c4-4db1-9166-081ad96dec1c.png)

**Comment by mjbvz** [comment] 2023-03-20 20:14
Duplicate of https://github.com/microsoft/TypeScript/issues/16665

**Closed by mjbvz** 2023-03-20 20:14 UTC
