### ISSUE TITLE
Retry as Admin/Sudo to create a new file

### ISSUE THREAD

**Issue by drujd** [microsoft/vscode#106244] opened 2020-09-07 15:36 UTC
'Retry as Admin/Sudo' works well when saving an existing file. However, when attempting to e.g. re-create a deleted (yet still open in code) file or just running 'code nonexistent_file' in a dir where admin permissions are needed, 'Retry as Admin/Sudo' is not offered. It would be nice for the functionality to be offered in this case as well, right now it is necessary to first create the file(s).

**Comment by bpasero** [comment] 2020-09-07 16:30
Duplicate of https://github.com/microsoft/vscode/issues/42411

**Comment by drujd** [comment] 2020-09-07 16:49
Not exactly a duplicate as I did not have 'Save As' in mind - only saving a file already open as some (non-existent) filename.

But having the functionality for 'Save As' would be nice as well, of course! :)

**Closed** 2020-11-08 02:27 UTC
Labels: feature-request, file-io, workbench-run-as-admin
