### ISSUE TITLE
v1.43.0的bug - ActivityBar侧边栏[打开文件夹]按钮不可用,显示了Markdown代码

### ISSUE THREAD

**Issue by YugeCse** [microsoft/vscode#92303] opened 2020-03-10 00:40 UTC
Issue Type: <b>Bug</b>

> 无打开文件夹

你尚未打开文件夹

**[打开文件夹](命令：workbench.action.files.openFolder)** 

....

**[打开文件夹](命令：workbench.action.files.openFolder)**  显示的是 `[打开文件夹](命令：workbench.action.files.openFolder)`

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
ccs-flutter-color|cir|0.0.3
gitignore|cod|0.6.0
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
auto-close-tag|for|0.5.6
kotlin|fwc|0.2.11
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
intellij-idea-keybindings|k--|0.2.37
vscode-language-babel|mgm|0.0.26
vscode-language-pack-zh-hans|MS-|1.43.2
Go|ms-|0.13.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.1
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
vscode-java-debug|vsc|0.25.1
vscode-maven|vsc|0.21.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2020-03-10 01:58
@YugeCse could you please share a screenshot of what you are seeing?

**Comment by he0119** [comment] 2020-03-10 03:57
![image](https://user-images.githubusercontent.com/5219550/76278242-15fa6700-62c6-11ea-99d3-69f453438965.png)
Just like this.

**Comment by YugeCse** [comment] 2020-03-10 05:58
@he0119 you are right, i dont know how to upload image, i dont find the location where to add image.

**Comment by soocute** [comment] 2020-03-10 07:49
我也是这样，是我电脑的问题，还是插件的问题？
请问，你的vscode修复了这个bug没？
我记得我上个礼拜新装vscode是没有这个问题的。

**Comment by YugeCse** [comment] 2020-03-10 08:45
@soocute 就是更新这个版本出的问题的，This problem ocurred after I updated this version.

**Comment by rebornix** [comment] 2020-03-10 19:36
/duplicate of https://github.com/microsoft/vscode/issues/92306

**Closed by rebornix** 2020-03-10 19:36 UTC
Labels: *duplicate, needs more info, new release
