### ISSUE TITLE
Provide access to theme colours from extensions

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#67416] opened 2019-01-29 14:41 UTC
It would be great if there was a mechanism to get the current themed colours by an extension.

e.g. something along the lines of:
`vscode.window.getThemeColor( id: string )`

and then having a method of ThemeColor that returns the rgb(a). That way extensions could match colours to themes. 

At the moment I have to use a configuration setting...

**Comment by usernamehw** [comment] 2019-01-29 15:10
There is one method (only it just returns reference and not rgb):
```typescript
new vscode.ThemeColor('activityBar.background')
```

**Comment by Gruntfuggly** [comment] 2019-01-29 18:38
Yeh, that gets you half way, but you can only use it as input into other API calls...

**Comment by aeschli** [comment] 2019-01-30 15:52
duplicate of #32813

**Closed by aeschli** 2019-01-30 15:52 UTC
Labels: themes
