### ISSUE TITLE
Don't scroll the file explorer when closing a file

### ISSUE THREAD

**Issue by davidfig** [microsoft/vscode#101640] opened 2020-07-02 23:44 UTC
I run into this scenario a bunch when using the file explorer-thingy (left file panel):

1. have a large codebase open with lots of directories and files
2. open some files
3. go to a different part of the codebase and open a file
4. realize that it's the wrong file
5. close that file
6. try to open a neighboring file
7. discover that the file explorer has repositioned to show the file that took focus after closing the file
8. get frustrated and scroll the file explorer back to the desired directory

Ideally, when closing a file, the file explorer would not scroll to the newly focused file. This, however, would only change the behavior when closing a file. Clicking on the tab for a file or opening a file would still scroll the file explorer to the proper position.

**Comment by yume-chan** [comment] 2020-07-03 03:30
Duplicate of #38899

**Closed** 2020-07-03 03:45 UTC
