### ISSUE TITLE
Git buttons are not visible when changed files names are long

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#69826] opened 2019-03-05 08:24 UTC
Issue Type: <b>Bug</b>

Give any file a long name. Make some changes and open the Source Control section. If the file name is long enough operations buttons get out of the visible area. The only way to see them is to change the whole sidebar width.

![modelfactory php untitled workspace 2019-03-05 15-54-56](https://user-images.githubusercontent.com/839349/53789687-fc5e6b00-3f5f-11e9-9bbc-f727d17e01dc.png)
![modelfactory php untitled workspace 2019-03-05 15-57-46](https://user-images.githubusercontent.com/839349/53789689-fc5e6b00-3f5f-11e9-9bfe-7a740c726ba6.png)

BTW, why no to make it the same as in Atom: double-click on a file name puts it into staging? It would be much faster than aiming the "+" button or using a context menu.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
file-icons|fil|1.0.16
beautify|Hoo|1.4.9
phpcs|ika|1.0.5
dotenv|mik|1.0.1
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
subtle-brackets|raf|3.0.0
code-settings-sync|Sha|3.2.5
vscode-wakatime|Wak|1.2.7

(1 theme extensions excluded)

</details>

**Comment by adamtajti** [comment] 2019-03-05 11:34
Unable to reproduce this on Windows. Might be a Darwin specific bug.

The behavior on my side is that the action buttons only show up when you hover over the row itself. If you do that, it shows the buttons _even if the file name is extremely long_ for the sidebar width:

![image](https://user-images.githubusercontent.com/1270407/53802410-0e311580-3f42-11e9-8436-4c93ab7cbb5d.png)

Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
OS: Windows_NT x64 10.0.17134

**Comment by njkevlani** [comment] 2019-03-05 13:50
Duplicate of #68027

**Comment by njkevlani** [comment] 2019-03-05 13:51
@adamtajti You can notice this if you set `workbench.tree.horizontalScrolling` to `true`

**Comment by adamtajti** [comment] 2019-03-05 15:41
Thanks for that info @njkevlani! I was able to reproduce it after setting that and checked your changes in the original issue.

**Closed** 2019-03-06 08:20 UTC
