### ISSUE TITLE
When I rename a file, the rest of the file names are bugged.

### ISSUE THREAD

**Issue by MedzikUser** [microsoft/vscode#154716] opened 2022-07-10 19:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0
- OS Version: Arch Linux/Fedora

Steps to Reproduce:

1. Press F2 or click Rename from right click menu

![image](https://user-images.githubusercontent.com/87065584/178158508-9801610f-4a67-4a79-b8a6-e776a029e2b2.png)

when I don't rename the file it is normal

![image](https://user-images.githubusercontent.com/87065584/178158629-624678eb-d4d4-4895-b231-1440b95080d2.png)

In the earlier version this was not present

**Comment by MedzikUser** [comment] 2022-07-10 19:11
in home page is also bugged

![image](https://user-images.githubusercontent.com/87065584/178158706-8c9cd35b-696d-4fcc-ac7e-0d039c77ec88.png)

**Comment by lramos15** [comment] 2022-07-11 18:47
cc @deepak1556 This looks like another rendering bug!

**Comment by lramos15** [comment] 2022-08-30 14:51
@MedzikUser Can you still reproduce this on the latest version of VS Code

**Comment by MedzikUser** [comment] 2022-08-30 14:55
> @MedzikUser Can you still reproduce this on the latest version of VS Code

only in "home" page

![image](https://user-images.githubusercontent.com/87065584/187470041-72c1b845-74bc-44af-889e-069251eeaf8d.png)

**Comment by lramos15** [comment] 2022-08-30 14:59
Can you elaborate more on computer specifications and the type of monitor + resolution you're using

**Comment by MedzikUser** [comment] 2022-08-30 15:15
> Can you elaborate more on computer specifications and the type of monitor + resolution you're using

Display settings:

![image](https://user-images.githubusercontent.com/87065584/187473916-f6a0eda3-06cd-43ce-9a1e-ad80e483874e.png)

Computer specs:
CPU: i5 11500
GPU: UHD 750 (driver i915)
OS: Fedora
Monitor: LG 21:9 2560x1080

**Comment by deepak1556** [comment] 2022-08-31 15:48
Can you start with `--disable-gpu` and see if the issue happens.

**Comment by MedzikUser** [comment] 2022-09-02 18:30
> Can you start with `--disable-gpu` and see if the issue happens.

![image](https://user-images.githubusercontent.com/87065584/188215872-e746dbee-4e49-40e5-a1e6-a24edb2a3330.png)

it doesn't happen

**Comment by MedzikUser** [comment] 2022-09-04 14:12
> > @MedzikUser Can you still reproduce this on the latest version of VS Code
> 
> only in "home" page
> 
> ![image](https://user-images.githubusercontent.com/87065584/187470041-72c1b845-74bc-44af-889e-069251eeaf8d.png)

however, it is also when renaming a file

![image](https://user-images.githubusercontent.com/87065584/188317915-bd351da2-5cb6-42b8-bf96-f6a58d5b0946.png)

**Comment by deepak1556** [comment] 2022-09-05 06:59
Thanks for confirming the flag, you can disable gpu acceleration permanently following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration. This is usually a case where a newer runtime version might resolve the gpu support issue. Closing as not addressable in VSCode.

**Closed by deepak1556** 2022-09-05 06:59 UTC
Labels: info-needed
