### ISSUE TITLE
Editor of first group not disposed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99887] opened 2020-06-11 16:13 UTC
Related to https://github.com/microsoft/vscode/issues/99770

* set a breakpoint in `NotebookEditor#dispose`
* open two notebooks in two groups
* close all editors
* :bug: dispose is only called once

**Comment by bpasero** [comment] 2020-06-12 07:48
@jrieken related https://github.com/microsoft/vscode/issues/99770#issuecomment-642719879

I added a new `EditorInput#close()` method that you can override to `dispose` or not. The rationale is that the editor part should not make any assumptions about disposing or not but the implementor of an editor input should decide.

**Comment by jrieken** [comment] 2020-06-12 08:02
> r not but the implementor of an editor input should decide.

I find that weird because the input doesn't create nor own the editor

**Comment by bpasero** [comment] 2020-06-12 08:26
I am open for suggestions, but note that editor inputs can have a lifecycle outside of an editor. I.e. many editor inputs can be opened but there is only ever 1 editor to display (per group). And an editor input might not even be associated with any editor if it was not opened yet (an inactive tab after a window reload).

**Comment by jrieken** [comment] 2020-06-12 09:46
Yeah, I believe the inputs should have nothing to do with this. An editor group creates an editor and disposed it. That's it and that's how it actually works with all N+1 groups and I think that sane. 

In notebook land all those input tricks are only required because the editor doesn't know anything, e.g an editor (not input) doesn't know that it's inactive vs active vs closed, e.g setVisible and clearInput are called in all cases which makes it very hard to know that a "web view is free to reuse". I'd prefer to have to more clarity there and ignore inputs for a moment tbh.

**Comment by jrieken** [comment] 2020-06-12 09:51
Things that I would like to have

* [x] select first notebook per group -> call `ctor`, call `setInput`
* [ ] close whole group -> call `dispose`
* [ ] select another editor (type) -> call `setVisible(false)`
* [ ] re-select notebook editor -> call `setVisible(true)`
* [ ] select different notebook -> call `setInput`
* [ ] close editor but keep group -> call `clearInput`
* [ ] move editor to different gourp -> call something _before_ interacting with other editor

**Comment by bpasero** [comment] 2020-06-12 12:20
@jrieken should we maybe close this as duplicate of https://github.com/microsoft/vscode/issues/99770, I just posted a comment (https://github.com/microsoft/vscode/issues/99770#issuecomment-643240919) giving a bit more detail. 

I see your list of requirements and as suggested in https://github.com/microsoft/vscode/issues/99770#issuecomment-643240919 would need a call also with Matt and Pung to discuss this.

**Comment by jrieken** [comment] 2020-06-12 13:25
> @jrieken should we maybe close this as duplicate of #99770,

I would actually prefer the other way around. At least for notebooks, the input trouble only exists because inputs are used in funny ways and in order to know when editors move. I'd prefer to have

* have NotebookEditorInput just like FileEditorInput using ref-counted notebook models
* have a few move editor APIs that allow to reuse the underlying widget (webview)

**Comment by bpasero** [comment] 2020-06-12 16:23
Fair enough, let's have a call next week to clear things up.

**Comment by jrieken** [comment] 2020-06-16 10:57
@bpasero That `dispose` isn't called is still a problem. It still needs code like this to clean up webviews when all editors have closed: https://github.com/microsoft/vscode/blob/9d5a45a6fb26d491cf96cfd45545e048c810cfdb/src/vs/workbench/contrib/notebook/browser/notebookEditor.ts#L152

**Comment by bpasero** [comment] 2020-06-16 11:09
@jrieken yes, I see the issue and I currently see no other clean solution unless there was an explicit tab model that would reflect what is going on in the editor. The lifecycle of webviews cannot be tied together with editor inputs, it needs to be a concept outside of that lifecycle. 

@mjbvz how do you do that for webviews, e.g. when do you know when to release webviews based on editors closing? I am sure you solved this, maybe you can shed some light on this.

**Comment by jrieken** [comment] 2020-06-16 11:45
@bpasero we do you not dispose the editor like you do for all other groups?

**Comment by bpasero** [comment] 2020-06-16 12:00
@jrieken I assume you mean `EditorInput.dispose()`: if the editor input was disposed but still opened in another group, it would mean that group suddenly has a disposed input to show. The culprit is that the editor input is only being disposed when its last instance is closed across all groups to prevent that. I think it may be easier to talk this through in a call though as I probably do not understand the issue in full yet.

**Comment by jrieken** [comment] 2020-06-16 12:01
> @jrieken I assume you mean EditorInput.dispose():

No. `IEditor#dispose`

**Comment by bpasero** [comment] 2020-06-16 12:31
That should actually happen as soon as the group is closed:

https://github.com/microsoft/vscode/blob/85bedc79634d103cc32951a1362f4962557ace24/src/vs/workbench/browser/parts/editor/editorControl.ts#L130

You may not see that for the very first group simply because that group never really closes unless you open a second group and close the original one.

**Comment by jrieken** [comment] 2020-06-16 12:52
I run "F1 >  Close All Editor", see the watermark, and only a single time dispose is called

**Comment by jrieken** [comment] 2020-06-17 12:43
No more requirements from notebook land... Leaving further work/refactorings to @bpasero

**Comment by bpasero** [comment] 2020-06-17 12:54
Ok, I will push some cleanup over the week, made some notes in my backlog.

**Closed by bpasero** 2020-06-17 12:54 UTC
Labels: notebook
