### ISSUE TITLE
Typescript: Run Build Task... conflicts with Terminal Argument Settings

### ISSUE THREAD

**Issue by tuldoklambat** [microsoft/vscode#77410] opened 2019-07-15 16:22 UTC
Issue Type: <b>Bug</b>

I had the following setting in my Terminal Shell preference:

"terminal.integrated.shellArgs.windows": ["/K", "prompt $E[1;32m$D$E[0m $P$G$S"]

Whenever I do Terminal | Run Build Task... VS seems to do nothing and status bar displays Building... and in the Terminal output it display the following:

> Executing task: tsc -p e:\source\study\typescript\debugging\tsconfig.json <

Tue 07/16/2019 e:\source\study\typescript\debugging>  /d /c tsc -p e:\source\study\typescript\debugging\tsconfig.json

Removing the above shell setting makes it work but I would like to customize my terminal cmd prompt.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment] 2019-07-29 12:19
Duplicate of https://github.com/microsoft/vscode/issues/59789

**Closed by alexr00** 2019-07-29 12:19 UTC
Labels: tasks
