### ISSUE TITLE
Source Control Is not Showing Change Files

### ISSUE THREAD

**Issue by dumblerod** [microsoft/vscode#102402] opened 2020-07-13 15:59 UTC
Issue Type: <b>Bug</b>

For some reason, when I use VS Code for a while, the Source Control tab does not have anything in it.  I have to shutdown and restart VSCode in order to get the ability to use the source control tab again.  This started happening in past few weeks.

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:58:37.847Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
gitlens|eam|10.2.2
terraform|has|2.0.2
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
azure-account|ms-|0.9.0
powershell-preview|ms-|2020.6.1
sqltools|mtx|0.22.10
vscode-icons|vsc|10.2.0
vscode-ansible|vsc|0.5.2

</details>

**Comment by dumblerod** [comment] 2020-07-13 16:02
This is related to issue: #102358 but I am not using Gitlab repos.  I'm using Azure DevOps repos.  The view of the repos just seems to disappear after some amount of use.

**Comment by joaomoreno** [comment] 2020-07-13 20:48
Duplicate of https://github.com/microsoft/vscode/issues/102358

@dumblerod Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?

**Closed by joaomoreno** 2020-07-13 20:48 UTC
