### ISSUE TITLE
files.trimTrailingWhitespace is inverted

### ISSUE THREAD

**Issue by kevin-ashton** [Microsoft/vscode#8105] opened 2016-06-24 13:57 UTC
- VSCode Version: 1.2.1
- OS Version: OSX 10.11.2

Steps to Reproduce:

1.  I have the following settings: 
```
    "editor.renderWhitespace": true,
    "editor.trimAutoWhitespace": false,
    "files.trimTrailingWhitespace": false,
    "files.autoSave": "afterDelay",
```
2.  Hit space a few times at the end of a line and wait a second. Your cursor will jump back to the last character (since it trims the whitespace on the autosave). 

3. However, if I set `files.trimTrailingWhitespace: true` then it does not trim the file. When I tell it trim it does not trim. When I tell it not to trim then it trims. 

Is this intended behavior? It feels opposite of what I would expect based on the setting name.

**Comment by emiljas** [comment] 2016-06-24 14:23
On my machine (VSCode 1.2.1, Windows 7) files.trimTrailingWhitespace just do not work when "files.autoSave" is "afterDelay".

**Comment by bpasero** [comment] 2016-06-26 06:51
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-07-04 07:08
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-07-04 07:08 UTC
Labels: bug, needs more info, workbench
