### ISSUE TITLE
interllisence does not work in some project

### ISSUE THREAD

**Issue by baiyunshenghaishang** [microsoft/vscode#86807] opened 2019-12-12 09:17 UTC
- VSCode Version: 1.40.2
- OS Version: win10

Steps to Reproduce:

1. open a big project and a js file
2. status bar shows "Initializing JS/TS language features". this took one or two minutes.  interllisence does not work during the time and after finished. sometimes it works again several minutes later.
and interllisence works well in another small project except for 'Initializing JS/TS language features' period

I am not sure if this is a bug. any suggestion would be great.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-12-12 18:01
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2019-12-12 18:01
Also, can you share the project?

**Comment by baiyunshenghaishang** [comment] 2019-12-13 02:02
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

yes. I can reproduce in version 1.41.0 with all extensions disabled

**Comment by baiyunshenghaishang** [comment] 2019-12-13 02:07
> Also, can you share the project?

I am afraid not.  this is a business project.
this is a react project and a little big(20M without node_modules)。I don't know what to describe

**Comment by baiyunshenghaishang** [comment] 2019-12-13 08:30
it fails again in another vue project. But still works well in my test project. Feeling so bad...

**Comment by baiyunshenghaishang** [comment] 2019-12-13 09:04
Maybe I found the problem. 
Intelligence fails when a jsconfig.json in project root dir. Even this file is empty. and "Initializing JS/TS language features" would take much more time.
everything works well when I remove this file

**Comment by baiyunshenghaishang** [comment] 2019-12-13 11:13
another vue project failed because of "package.json"

**Comment by mjbvz** [comment] 2019-12-16 23:03
@baiyunshenghaishang Does this only happen in Vue projects? If so, you should probably file this against the Vue extension instead

**Comment by baiyunshenghaishang** [comment] 2019-12-17 02:54
> @baiyunshenghaishang Does this only happen in Vue projects? If so, you should probably file this against the Vue extension instead

No.  A react project failed because of jsconfig.json existed. 
Interlligence failed after I disabled all extensions. It work again after I delete the jsconfig.json file. 
This only exist in windows. Mac works well in same project with all extensions enabled.

**Comment by mjbvz** [comment] 2019-12-20 19:45
@baiyunshenghaishang Is your code stored on a separate letter drive, such as `D:` or `Z:`?

**Comment by baiyunshenghaishang** [comment] 2019-12-23 03:27
> @baiyunshenghaishang Is your code stored on a separate letter drive, such as `D:` or `Z:`?

Yes.

**Comment by mjbvz** [comment] 2019-12-30 00:50
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

**Closed by mjbvz** 2019-12-30 00:50 UTC
Labels: javascript, needs more info
