### ISSUE TITLE
Freezes when switching from the taskbar after the browser

### ISSUE THREAD

**Issue by sholohov** [Microsoft/vscode#46243] opened 2018-03-21 11:19 UTC
Problem type: <b> Performance Error </b>

1. Launch the Chrome browser
2. Run the Vicual Studio code
3. Open the browser.
4. Press the alt + tab buttons and switch to the editor - does not respond
5. Minimize all windows
6. Maximize the editor only - it works great!

Tried different browsers, when switching from other applications (not to the browser) this is not observed. Perhaps this is after the update.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|5.91GB (1.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   -1	   102	   848	code main
   -1	    65	  2976	   shared-process
   -1	    70	  5044	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
   -1	     7	  9664	     console-window-host (Windows internal process)
   -1	    66	  7584	   shared-process
   -1	    56	  8360	   shared-process
   -1	   225	  9712	   window (dialogs.hbs - hud-display - Visual Studio Code)
   -1	    15	  5220	     watcherService 
   -1	     5	  8280	       console-window-host (Windows internal process)
   -1	    21	  7232	     searchService
   -1	    76	  8588	     extensionHost
   -1	    30	  1824	       electron_node eslintServer.js 
   -1	    61	  5304	       electron_node server.js 
   -1	    39	  7384	       electron_node dbaeumer.js dbaeumer.js server.js 
   -1	    43	  8092	       electron_node server.js 
   -1	    89	  8704	       electron_node electronForkStart.js tsserver.js 
   -1	    34	 10832	         electron_node typingsInstaller.js tsserver.js typesMap.js 
   -1	    54	 10408	       electron_node htmlServerMain.js 
   -1	    61	 12552	       electron_node cssServerMain.js 
   -1	    33	  9984	     terminal
   -1	     6	 10904	       winpty-process
   -1	    10	  7200	         console-window-host (Windows internal process)
   -1	    60	 14956	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
   -1	     4	  9552	           C:\WINDOWS\system32\cmd.exe /c ""C:\Users\Alexey\AppData\Roaming\npm\gulp.cmd" debug"
   -1	    96	 15068	             node   "C:\Users\Alexey\AppData\Roaming\npm\\node_modules\gulp-cli\bin\gulp.js" debug
   -1	   240	 11136	   gpu-process
   -1	    70	 12724	   powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code.exe' -MaxSamples 3}"
   -1	     7	  8648	     console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dialogs.hbs - hud-display - Visual Studio Code)
|    Folder (hud-display): 598 files
|      File types: png(234) ttf(178) js(44) less(36) TTF(22) json(17) css(17)
|                  svg(10) hbs(9) jpg(8)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1) gulp.js(1)
|                  package.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.17
vscode-eslint|dba|1.4.7
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.4.0
beautify|Hoo|1.3.0
docthis|joe|0.6.0
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
material-icon-theme|PKi|3.2.6
stylelint|rap|0.32.0
LiveServer|rit|3.2.1

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by bpasero** [comment] 2018-03-23 17:30
@sholohov does it reproduce with this version of VS Code that comes with a newer Electron version: https://az764295.vo.msecnd.net/exploration/b1513227ace6929e278c5d531250bc1d0cf89e2f/VSCode-win32-x64-1.22.0-exploration.zip

**Comment by sholohov** [comment] 2018-03-24 08:49
@bpasero 
Nothing has changed, the same freezes. Maybe you need some more information?

I found that the same thing happens with several other applications. After switching over alt + tab, the application is temporarily unavailable for any actions, sometimes on a black screen, and then partially, with squares, an image appears. I have a suspicion that this is a mistake of updating some divers. But most of all it is noticeable on the editor.

**Comment by bpasero** [comment] 2018-03-24 09:06
@sholohov are these other applications all Electron applications? Does it reproduce if you run "`code --disable-gpu`"?

**Comment by sholohov** [comment] 2018-03-24 12:20
@bpasero 
Relatively Electron does not know. How can I find out about this?
If I run through `code --disable-gpu` then freezes are not observed.

**Comment by sholohov** [comment] 2018-03-26 10:13
Is it a problem with my PC or application? I did not quite understand :)

**Comment by bpasero** [comment] 2018-03-29 09:11
Duplicate of https://github.com/Microsoft/vscode/issues/28709

**Closed by bpasero** 2018-03-29 09:11 UTC
Labels: electron, gpu, needs more info, upstream, windows
