### ISSUE TITLE
False/Fake return error

### ISSUE THREAD

**Issue by xKyro** [microsoft/vscode#147267] opened 2022-04-12 01:18 UTC
Issue Type: <b>Bug</b>

When I opened vsc, everything started as usual, no bugs or errors, but then the editor shows me that 1 error has been found in the covert.js file, so I look at it and it says that "A return statement can only be used within a function body", I was wondering why, then I ran the program and everything worked, no error like I said before

So, I think that's an error of the vsc or an extension is interfering with the editor

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.83GB free)|
|Process Argv|--crash-reporter-id 3e490237-070c-4f0f-86d2-7adac9dd7d2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
vscord|Leo|4.5.0
theme-monokai-pro-vscode|mon|1.1.20
csharp|ms-|1.24.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
java|red|1.4.0
LiveServer|rit|5.7.5
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment] 2022-04-12 15:49
Duplicate of https://github.com/microsoft/TypeScript/issues/48224

**Closed by mjbvz** 2022-04-12 15:49 UTC
