### ISSUE TITLE
Big Sur - Native dialog design issue

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#113968] opened 2021-01-07 09:23 UTC
The native dialog contains:
* primary, secondary actions
* two link button which on hover are rendered as secondary actions
* weird separator between the link buttons that goes away when hovering over any of the link buttons

![image](https://user-images.githubusercontent.com/3372902/103874934-132cf600-50d2-11eb-933d-eeb248fa6887.png)

**Comment by bpasero** [comment] 2021-01-07 09:34
It turns out that this seems to be what macOS does now, was able to reproduce with a simple Electron sample:

![image](https://user-images.githubusercontent.com/900690/103876361-d3ffa480-50d3-11eb-8d1f-95177969d801.png)

I am not sure if there is something Electron could do, moving to Deepak.

**Comment by deepak1556** [comment] 2022-12-12 18:29
Closing as designed.

**Closed by deepak1556** 2022-12-12 18:29 UTC
Labels: upstream, electron, dialogs, macos-big-sur
