### ISSUE TITLE
Can't download Visual Studio Code 2019

### ISSUE THREAD

**Issue by thirst4combat** [microsoft/vscode#74736] opened 2019-06-02 05:51 UTC
So I heard VS code was the best editor at the moment, however, when I go to download it takes me to the download page only for a split second then redirects me to a blank page that just says not found. I am using google chrome as my browser and I have already tried to download while disabling VPNs. Not sure what to do.

**Comment by Xiaoqii** [comment] 2019-06-02 05:59
![image](https://user-images.githubusercontent.com/26139504/58757398-8d80b600-853e-11e9-9ea7-0d8897eb2426.png)
Can't download Visual Studio

**Comment by justmao945** [comment] 2019-06-02 06:06
+1

**Comment by llussy** [comment] 2019-06-02 06:17
+1

**Comment by justClouds** [comment] 2019-06-02 06:18
Duplicate of [#74732](https://github.com/microsoft/vscode/issues/74732) and [#74734](https://github.com/microsoft/vscode/issues/74734) and [#74737](https://github.com/microsoft/vscode/issues/74737).

**Comment by jebai0521** [comment] 2019-06-02 06:28
+1

**Comment by sfdkems4263** [comment] 2019-06-02 06:47
Having the same issue

**Comment by 372338552** [comment] 2019-06-02 06:52
+1

**Comment by stephwongwt** [comment] 2019-06-02 07:50
+1

**Comment by lifanping** [comment] 2019-06-02 07:59
+1

**Comment by RussellOng95** [comment] 2019-06-02 08:09
+1

**Comment by SHawnHardy** [comment] 2019-06-02 08:34
same here

**Comment by llussy** [comment] 2019-06-02 09:28
Can be downloaded！

**Comment by stephwongwt** [comment] 2019-06-02 09:30
Can confirm it works now!

**Comment by stephwongwt** [comment] 2019-06-02 09:32
Can confirm it works now!

**Comment by justmao945** [comment] 2019-06-02 09:33
Can confirm it works now!

**Closed** 2019-06-03 07:17 UTC
Labels: *duplicate
