### ISSUE TITLE
IntelliSense just got out of position

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#13773] opened 2016-10-14 16:12 UTC
- VSCode Version: 1.6.1
- OS Version: macOS El Capitan

While editing this code:

```

//
// Copyright 2016 Kary Foundation, Inc.
//   Author: Pouya Kary <k@karyfoundation.org>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//

//
// ─── EXPORTS ────────────────────────────────────────────────────────────────────
//

    module.exports = blockASTinRecArray => {
        let last = null;
        return {

        }
    }

//
// ─── RECURSIVE ADDER ────────────────────────────────────────────────────────────
//

// ────────────────────────────────────────────────────────────────────────────────
```

I fixed a spell problem with: ![Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). and then vscode started computing the intelliSense location wrong:

<img width="603" alt="screen shot 2016-10-14 at 7 37 44 pm" src="https://cloud.githubusercontent.com/assets/2157285/19394524/64039e02-9246-11e6-899a-ca579d03c578.png">
<img width="941" alt="screen shot 2016-10-14 at 7 37 58 pm" src="https://cloud.githubusercontent.com/assets/2157285/19394525/64071992-9246-11e6-856e-0e2511c400f2.png">

**Comment by joaomoreno** [comment] 2016-10-20 12:46
I don't understand what the problem is. Can you explain *exactly* and *step-by-step* what you have done, what happened and what did you expect would happen?

**Comment by joaomoreno** [comment] 2016-10-24 08:35
Alright, closing it for now then. Thanks for the update!

**Closed by joaomoreno** 2016-10-24 08:35 UTC
Labels: needs more info
