### ISSUE TITLE
Linux Deb download Broken

### ISSUE THREAD

**Issue by subodhp** [microsoft/vscode#74737] opened 2019-06-02 06:07 UTC
https://update.code.visualstudio.com/latest/linux-deb-x64/stable is broken, file is not found.

Please suggest.

**Comment by justClouds** [comment] 2019-06-02 06:16
Duplicate of [#74732](https://github.com/microsoft/vscode/issues/74732) and [#74734](https://github.com/microsoft/vscode/issues/74734),

**Comment by StijnMaenhaut** [comment] 2019-06-02 07:28
Same for the macOS download

**Comment by subodhp** [comment] 2019-06-02 13:03
Closing this, the Debian Deb download is working now.

**Closed** 2019-06-02 13:04 UTC
Labels: install-update
