### ISSUE TITLE
Build failed: `Push English strings to extension localization repository`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#233054] opened 2024-11-05 06:17 UTC
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=302954
Changes: https://github.com/microsoft/vscode-copilot/compare/fa99c8f...fa0bfb3

**Comment by TylerLeonhardt** [comment] 2024-11-05 16:33
Duplicate of https://github.com/microsoft/vscode-extensions-loc/issues/1168

**Closed by TylerLeonhardt** 2024-11-05 16:33 UTC
Labels: vscode-build
