### ISSUE TITLE
.html files  creates c++ files

### ISSUE THREAD

**Issue by smanivarma** [microsoft/vscode#126123] opened 2021-06-12 09:18 UTC
Hi,
When  Creating a .html files in the vscode, its creating a C++ files. How to make change in it??
Attached the files
![Screenshot (29)](https://user-images.githubusercontent.com/84104219/121771463-2403fb00-cb8d-11eb-8f67-6ee7fa3c893d.png)

**Comment by IllusionMH** [comment] 2021-06-12 13:04
It's only editor icon in Explorer that is wrong (icon in tab is correct, language mode correct as well). Is it only during rename?
Not able to reproduce it in latest stable version 1.57.0

/needsMoreInfo
What version are you using?

Do you have any file association set in your settings?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by smanivarma** [comment] 2021-06-12 21:46
> It's only editor icon in Explorer that is wrong (icon in tab is correct, language mode correct as well). Is it only during rename?
> Not able to reproduce it in latest stable version 1.57.0
> 
> /needsMoreInfo
> What version are you using?
> 
> Do you have any file association set in your settings?
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`

Hi, I am using 1.57.0
 i have solved the issue by changing the file name in the extension. .But I don"t know how it has been changed.
Thanks for your reply.
Manivarma
![Screenshot (31)](https://user-images.githubusercontent.com/84104219/121789705-aaecbe00-cbf5-11eb-8f44-b1c9f63ba939.png)

**Comment by javid0416** [comment] 2021-06-12 21:51
microsoft/vscode <
***@***.***>

**Comment by IllusionMH** [comment] 2021-06-13 01:08
/question

@smanivarma why do you have that file association in place?
They look wrong - `*.json` assigned to HTML, `*.html` is C++. Why?

It's better to use Reset Setting to avoid problem you descrived above.
![image](https://user-images.githubusercontent.com/1312662/121792399-ea6ad880-cbfc-11eb-9417-3eb9077df7f6.png)

**Closed** 2021-06-13 01:09 UTC
Labels: *question, needs more info
