### ISSUE TITLE
Auto-Rename Tag exhibiting weird behaviour with Emmet

### ISSUE THREAD

**Issue by abhijit-hota** [microsoft/vscode#106056] opened 2020-09-03 17:02 UTC
- VSCode Version: `1.48.2 (system setup)`
- OS Version: `Windows_NT x64 10.0.19041`

Steps to Reproduce:

1.  Start writing `div` (or any other element that triggers Emmet suggestions) and press enter on the Emmet auto suggestion. You should now see a `<div></div>` (As expected).
2. Press <kbd>Ctrl </kbd>+ <kbd>Z</kbd>. (Undo it, basically.)
3. The auto-rename function is still active and behaves weirdly (Try pressing <kbd>Backspace</kbd> or type anything else. <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> works though).

Below is a gif that will hopefully help.

![dd](https://user-images.githubusercontent.com/8116174/92144854-f25b4800-ee34-11ea-8106-79b0f0f4fd22.gif)

Does this issue occur when all extensions are disabled?: **Yes**

----

P.S:  I'm not sure whether it's auto rename tag or mirror tag. Please edit it accordingly. Also hope that it's not a duplicate. =)

**Comment by aeschli** [comment] 2020-09-04 06:51
duplicate of https://github.com/microsoft/vscode/issues/101511

**Closed by aeschli** 2020-09-04 06:51 UTC
