### ISSUE TITLE
[Node.js] go to definition and intellisense not working anymore after version update

### ISSUE THREAD

**Issue by Ntobon** [Microsoft/vscode#43548] opened 2018-02-12 23:31 UTC
### Issue Type
Bug

### Description

After updating to the new version ,  go to definition and intellisense is not working any more for a my node js project.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:31.920Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|15.89GB (4.54GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
docthis-customize-tags|dwe|0.4.5
vscode-babel-coloring|dza|0.0.4
mithril-emmet|Fal|0.6.1
beautify|Hoo|1.3.0
vscode-angular2-emmet|jak|2.0.3
sublime-babel-vscode|jos|0.2.9
cpptools|ms-|0.14.6
sublime-keybindings|ms-|3.0.3
Spell|sea|1.0.0
Align|ste|0.2.0
addDocComments|ste|0.0.8
jsx|Twe|0.0.1
lorem-ipsum|Tyr|1.2.0
JavaScriptSnippets|xab|1.5.0

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-02-13 01:23
Please provide some example code or a small project that  shows the problem

**Comment by irfan88** [comment] 2018-02-14 10:34
i have same issue. please help me..

**Comment by byroniac** [comment] 2018-02-15 20:26
Intellisense on C# (ASP.NET, only language I use this editor for) is now fubarred with latest update, on both VSCode and VSCode insiders. I've tried deleting the "Code" and "Code - Insiders" folders in my %APPDATA% on Windows 10 Pro, and also deleting the ".vscode" and ".vscode-insiders" folders in my user profile directory. No banana. It has not even worked in order to lag or crash, for me. I see a "Loading..." pop up and then nothing. Is there a log of some kind somewhere?

**Comment by mjbvz** [comment] 2018-02-15 20:58
@byroniac Please file a new issue against the C# extension. This issue is for intellisense not working in a node.js project

**Comment by Ntobon** [comment] 2018-02-16 15:30
Was working perfectly before, version 1.20 update. 
Broken Intellisense is for this kind of export.

class MyClass { 
}

 module.exports = new MyClass() 

And the import 

var MyClass = require('myClass.js')

Thanks in advance.

**Comment by mjbvz** [comment] 2018-02-16 23:04
@Ntobon Can you add [`// @ts-check`](https://code.visualstudio.com/docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) at the top of your files and seeing if any errors are reported

**Comment by TimYi** [comment] 2018-02-17 13:54
I met the same error.

My code is

`// @ts-check

import { Table } from 'element-ui';`

and an error is reported: ``[js] Cannot find module 'element-ui'.

**Comment by TimYi** [comment] 2018-02-17 14:04
I find when go to definition is broken.

I deleted my jsonconfig.json file, and then go to definition works fine.

I add module target es6 in my jsconfig.json, I think this may break go to definition function.

**Comment by RyM934** [comment] 2018-02-19 14:37
It seems like if you import from an es6 module with multiples exports it can crash intellisense when you type `import {} from 'someDir/component';` I usually start with this syntax and fill in the brackets with the exports that I need. but every time I do this the intellisense crashes. If I use some name instead of the brackets before I type the `from` part of the statement the intellisense does not fail.

**Comment by gabrielruss** [comment] 2018-02-19 18:26
@RyM934 I am getting this exact same behavior. I tried uninstalling my extensions one at a time and for some reason there seems to be some correlation to any icon pack that I install. Is this coincidence or are other people seeing the same?

**Comment by RyM934** [comment] 2018-02-20 17:10
I ended up moving my jsconfig.json file inside my "src" folder where my code lives instead of at my project root where config files and node_modules existed. All the intellisense problems went away. I thought I could get away with using the "include" option to tell vs-code to only apply the "compilerOptions" to my src folder but it appears it must actually be located in the src folder for vs-code intellisense to work correctly now. I also had to update the "include" property accordingly.

**Comment by rhyek** [comment] 2018-02-27 08:30
I can confirm that this problem exists in 1.20.1 if I have a `jsconfig.json` file in the root directory. I downgraded to 1.19.3 without moving it and the problem cleared up. Moved the file inside `src/`, upgraded to 1.20.1 and, again, no issues.

The `jsconfig.json` has path mappings.

The behavior is, basically, I'm typing out an import with a long relative path (`'../../../../../shared/consts/organization-status'`), and as I'm typing out each `../`, the path hints take longer and longer to show up, and after the 4th or so they completely stop and IntelliSense in general stops working.

**Comment by rhyek** [comment] 2018-02-27 14:50
Coming back to my project a few hours later, IntelliSense and F12 still work, but they are very very slow. This is with 1.20.1 and with `src/jsconfig.json`.

**Comment by rhyek** [comment] 2018-03-09 00:55
This is still happening in 1.21.0.

**Comment by nhuthan** [comment] 2018-03-09 14:07
I have same issue. The format document stop working too.

**Comment by rhyek** [comment] 2018-03-09 18:44
I'm basically stuck on 1.19.3 for now.

**Comment by rhyek** [comment] 2018-03-26 16:06
Ok, so I'm using 1.21.1 and removed the jsconfig.js file. So no mappings of any sort now. I am still getting this issue every now and then. Not sure what is causing it. The output logs aren't showing anything I would consider relevant at first glance.

**Comment by sethduncan** [comment] 2018-04-18 12:38
I'm on version 1.22.2 (PC) and I am experiencing the same issue. F12 doesn't work, right click doesn't work, and running Go To Definition doesn't work.

**Comment by mjbvz** [comment] 2018-04-19 06:10
Closing this issue because I have not heard anything back from @Ntobon. 

If you are having still running into problems, please open new issues. This makes it much easier to track these investigations

**Closed by mjbvz** 2018-04-19 06:10 UTC
Labels: javascript, needs more info

**Comment by rhyek** [comment] 2018-04-19 11:35
@mjbvz you literally have 8 other people confirming there is an issue here. Your reason for closing is not justified.

**Comment by sethduncan** [comment] 2018-04-19 14:35
Restarting VS code does not solve the issue for me. I cannot get the function to work, period.

**Comment by rhyek** [comment] 2018-04-19 14:38
Restarting does work for me.

**Comment by mjbvz** [comment] 2018-04-19 14:51
I explained why I closed it. Intellisense not working is a very generic problem with any number of root causes. I cannot effectively track 8 different investigations in the same issue. Please open new issues instead if you are still seeing problems

**Comment by Tracis** [comment] 2018-05-06 06:25
I have the same problem in Version 1.22.2 (1.22.2)

**Comment by jgpieters** [comment] 2018-05-09 10:36
I have the same issue V1.23.2
