### ISSUE TITLE
Typescript error highlighting in for loop

### ISSUE THREAD

**Issue by loint** [Microsoft/vscode#3724] opened 2016-03-04 16:28 UTC
Hi everyone,

I found a wrong highlighting in for loop, please have a look below screenshot.
This error can make all below lines go wrong syntax highlight too.
 
<img width="429" alt="screen shot 2016-03-04 at 11 25 13 pm" src="https://cloud.githubusercontent.com/assets/5317864/13532930/a6dec7ec-e260-11e5-8cff-1f0ac4613621.png">

**Comment by aeschli** [comment] 2016-03-04 16:43
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-03-04 16:43 UTC
