### ISSUE TITLE
The 'view' menu has too many options

### ISSUE THREAD

**Issue by pedrogarcia** [Microsoft/vscode#53914] opened 2018-07-10 00:41 UTC
Issue Type: <b>Bug</b>

The 'view' menu has too many items. A lot of the options there are redundant, or the kind of option that you only use once, if at all. They could be merged or moved into settings only. 
There are so many options there, that I often have trouble finding the thing I want quickly. Many options that I use a lot are harder to access because there are so many things I don't want in between. 
Often, I will click in a menu to see if it has the option I want, find it does not, drag mouse, but since the menu overflows becase there are so many items, the flow is broken and the next menu does not show. 
Overall, it looks very ugly and intimidating as well. 
On sublime text, everything in the view menu is neatly organized around submenus and it does not look cluttered at all, even though it has more options than vscode. 

See these two screenshots comparing the two. 
![snipaste_2018-07-09_22-43-35](https://user-images.githubusercontent.com/2473545/42484508-b071ee80-83c9-11e8-97a5-3d0dc01d0b66.png)
![snipaste_2018-07-09_22-43-57](https://user-images.githubusercontent.com/2473545/42484507-b04767aa-83c9-11e8-99c9-fc6e070ddd78.png)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (4.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-search|bur|1.0.1
wolfram-language|fli|0.1.0
code-runner|for|0.9.3
terminal|for|0.0.10
matlab|Gim|0.9.0
nim|kos|0.5.29
python|ms-|2018.6.0
cpptools|ms-|0.17.6
markdown-preview-enhanced|shd|0.3.5
shell-launcher|Tyr|0.2.0

</details>

**Comment by bpasero** [comment] 2018-07-10 07:54
Duplicate of https://github.com/Microsoft/vscode/issues/16826

**Closed by bpasero** 2018-07-10 07:54 UTC
Labels: new release
