### ISSUE TITLE
Break points are hit or miss on node 6.2.0 on Windows

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#6839] opened 2016-05-24 22:00 UTC
While testing #6659.

If I simply follow the steps, the break point in index.js line 6 is never hit. However, if I insert a debugger statement everything is fine. 

The NTVS team (@mjbvz and @mousetrap) are seeing the same / a similar issue.

**Comment by mjbvz** [comment] 2016-05-24 22:09
Here's the issue NTVS where is tracking this problem: https://github.com/Microsoft/nodejstools/issues/934

The behavior we seeing is nondeterministic, sometime debugging works and sometimes it doesn't. I first noticed it in node 6.1, but also see it in 6.2 and suspect 6.0 is also effected.

This Node-inspector issue may be related too: https://github.com/node-inspector/node-inspector/issues/864

**Comment by weinand** [comment] 2016-05-24 22:35
@kieferrm VS Code should not have the same issue as NTVS (our code injection should work around the "illegal access" issue in callbacks).
I think you are seeing a different issue, but I'll try to reproduce tomorrow.

**Comment by weinand** [comment] 2016-05-25 14:20
@kieferrm I could not reproduce with node 6.0, 6.1, 6.2 on WIndows 10 (Parallels VM):

![jf2xitkf0x](https://cloud.githubusercontent.com/assets/1898161/15543260/78c35dae-2294-11e6-9074-437fec4c3eb0.gif)

Is there anything I am doing differently?

**Comment by weinand** [comment] 2016-05-25 14:42
To rule out that Parallel is the reason for the difference, I just tried to reproduce on a Lenovo X Carbon laptop with Window 8 and node.js 6.2. But again, breakpoints are reliably hit and I never missed any.

**Comment by kieferrm** [comment] 2016-05-25 15:14
I found the difference: 

I run in a VM. When I have the source in the window file system everything works fine and the break point is hit. When I have the source on the Mac (which is transparently mounted  as a windows drive) then - playing exactly the same scenario - the break point is not hit.  This seems to suggest that this is either a timing issue or some kind of line delimiter issue. If it's a timing issue I wonder if people using code on mounted network drives etc. could experience it too.

**Comment by weinand** [comment] 2016-05-25 15:26
@kieferrm I suspect this is UNC file path issue.

**Comment by weinand** [comment] 2016-05-25 16:28
@kieferrm I've verified that this is in fact a UNC path issue.

The following screenshot shows that node.js reports the file path for the 'debugger' statement back with a UNC path (green border), which VS Code opens in read-only mode in the editor (see the bogus "core module" detaill at the end).

But the breakpoint is registered with a driveletter path (red border in the tracing information). 

![2016-05-25 18-19-31](https://cloud.githubusercontent.com/assets/1898161/15547761/8a436a40-22a5-11e6-8121-72b6419b0d47.png)

I will close this issue (because with this finding the title has become misleading) and create a new bug.

**Comment by weinand** [comment] 2016-05-25 21:48
Since this is not an issue specific to node 6.2, I've created a bug that better reflects the real issue: https://github.com/Microsoft/vscode/issues/6894

**Closed by weinand** 2016-05-25 21:48 UTC
Labels: bug
