### ISSUE TITLE
Whitespace not monospace in front of Unicode symbols

### ISSUE THREAD

**Issue by vchuravy** [microsoft/vscode#62852] opened 2018-11-09 16:12 UTC
- VSCode Version: 1.28.2
- OS Version: Linux

Steps to Reproduce:
In a line with unicode characters (even with a font that supports monospace unicode) the *leading* whitespace characters are not monospaced
```
    # comment
    Î = one(I⃗₀)
```
1. Have a file with content as above, both lines should be aligned.
2. As a font I am using `Fira Code`, but I have observed this with several other fonts.

![screenshot from 2018-11-09 11-08-43](https://user-images.githubusercontent.com/145258/48273936-2c618b80-e410-11e8-9229-e233b1620cf3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-11-10 23:11
The trigger appears to be the usage of [`'COMBINING RIGHT ARROW ABOVE' (U+20D7)`](http://www.fileformat.info/info/unicode/char/20d7/index.htm)

Once that is removed, the line looks ok. It also appears that character is causing the font to change:

Notice the `I` and the `=` changing as I remove/add that character:
![62852](https://user-images.githubusercontent.com/5047891/48307098-21107c00-e546-11e8-860a-06b80c9c5859.gif)

Since I cannot reproduce this in Chrome with the editor at https://microsoft.github.io/monaco-editor/, I suspect this is an issue that Chromium fixed in the meantime, and it will simply just take some time until we adopt a new Electron version (which contains a new Chromium version). VS Code is now on Chromium 61, while Chrome is already at version 70

**Closed** 2019-10-09 10:16 UTC
Labels: *out-of-scope, electron, font-rendering, upstream
