### ISSUE TITLE
[html] Pasting HTML adds extraneous closing tag

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#46435] opened 2018-03-23 18:55 UTC
Issue Type: <b>Bug</b>

1. Copy or cut some code like:
```
<p>Badges offer a compact, attention-grabbing means to direct the user’s attention to important updates or statuses.</p>
```
2. Past it elsewhere, such as inside a div:
```
      <div class="doc-lede">

      </div>
```
3. it wraps the `p` tag and adds a closing `p` tag right after the opening one.  Here is the result:
```
      <div class="doc-lede">
<p></p>
  Badges offer a compact, attention-grabbing means to direct the user’s attention to important updates or statuses.</p>
      </div>
```
which is, of course, incorrect

![mar-23-2018 14-51-47](https://user-images.githubusercontent.com/835148/37848367-3d8b89b8-2eaa-11e8-8799-119e29e68311.gif)

VS Code version: Code - Insiders 1.22.0-insider (b75321329388d74e34f79dcfcb789246e31836a8, 2018-03-22T06:11:18.197Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5948844|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.5.0
Bookmarks|ale|0.18.2
project-manager|ale|0.25.0
vscode-intelephense-client|bme|0.8.8
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
svg|joc|0.0.9
Angular2|joh|2.14.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
nunavut|sml|0.1.0
vscode-versionlens|pfl|0.20.0
stylelint|shi|0.35.0
rewrap|stk|1.8.0
ayu|tea|0.14.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by smlombardi** [comment] 2018-03-23 18:57
Why does the "Experimental duplicate detection" simply detect other bugs I have a reporter

**Comment by aeschli** [comment] 2018-03-26 12:25
I'm not able to reproduce on a regular VSCode build. Can you run without extensions? Any special settings enabled?

**Comment by smlombardi** [comment] 2018-03-26 13:00
It's not happening today in 2018-03-26T05:05:33.957Z

With or without extensions.

**Comment by aeschli** [comment] 2018-03-26 13:35
Hmm, closing then. Please reopen if you see it again.

**Closed by aeschli** 2018-03-26 13:35 UTC
Labels: html, needs more info
