### ISSUE TITLE
changing collapsibleState to expanded does not expand node

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#40179] opened 2017-12-13 21:53 UTC
Steps:

- for a `TreeItem with collapsibleState !== TreeItemCollapsibleState.Expanded` set the collapsibleState to `TreeItemCollapsibleState.Expanded` and fire a `onDidChangeTreeData` event.

Observe: the tree item starts to show a expand triangle but the node does not actually expand.

**Comment by sandy081** [comment] 2018-02-14 09:54
Duplicate of #30918

**Closed by sandy081** 2018-02-14 09:54 UTC
Labels: bug, explorer-custom
