### ISSUE TITLE
Add option to delete remote branch, after merging GitHub PR

### ISSUE THREAD

**Issue by smeijer** [Microsoft/vscode#66234] opened 2019-01-08 22:17 UTC
After merging a PR through the GitHub "Pull request" page, I get an option to delete the remote branch after the merge:

![image](https://user-images.githubusercontent.com/1196524/50861990-ad9ab780-139a-11e9-8142-3ca77b50f253.png)

Currently, the Visual Code - Github pull requests page does not have this option:

![image](https://user-images.githubusercontent.com/1196524/50862040-cc994980-139a-11e9-8cee-39947304af1b.png)

Would be nice if there could be an extra button "Delete branch" once the PR has been merged. And it would even be awesome if this could be configured as default behavior. We allways remove merged branches. So bonuspoints if "Merge" would do a "merge" + "delete remote".

To be clear; this is about the remote branch. What the developers do with their local versions; is up to them. I just like the github repo to be clean.

**Comment by RMacfarlane** [comment] 2019-01-09 00:33
Thanks! This looks like a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/350

**Closed by RMacfarlane** 2019-01-09 00:33 UTC
Labels: git
