### ISSUE TITLE
Include into tasks.json and launch.json

### ISSUE THREAD

**Issue by md2perpe** [microsoft/vscode#90530] opened 2020-02-12 15:24 UTC
From https://github.com/stuartthomson/vscode-buttons/issues/1:
> It's currently not possible to have more than one tasks.json file per workspace. This means that tasks must either all be shared by a team or ignored by source control.

This gave me the idea to allow for includes into tasks.json (and other files like launch.json), for example with the following syntax:
```
{
    "tasks": [
        {
            ...
        }
    ],
    "include": [
        "team_tasks.json",
        "smart_tasks.json"
    ]
}
```

Here, team_tasks.json could be a file of tasks shared in your development team and smart_tasks.json a file of tasks that you have found on the Internet.

Inclusion could also be a way to [share variables between tasks.json and launch.json](https://github.com/microsoft/vscode/issues/89703).

**Comment by alexr00** [comment] 2020-11-09 14:18
duplicate of https://github.com/microsoft/vscode/issues/60043

**Closed by alexr00** 2020-11-09 14:18 UTC
Labels: feature-request, tasks
