### ISSUE TITLE
Completions for adding a new identifier in front of an existing one

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#48157] opened 2018-04-18 21:13 UTC
Issue Type: <b>Bug</b>

* Type:
```ts
declare function myFunction(x: number): number;
function f(y: number): number { return y; }
```
* We want to return `myFunction(y)` instead of just `y`. So put the cursor in front of `y` and start typing `myFun`.
* I would expect to get completions here. But vscode does not make any completion request.

VS Code version: Code - Insiders 1.23.0-insider (88f500e805ecc4efd064f7886c1a5ce8a2a2c087, 2018-04-18T05:12:32.564Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (1.94GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.39

</details>

**Comment by mjbvz** [comment] 2018-04-18 21:58
I believe this is by design. @jrieken should be able to say for sure.

You can manually re-trigger suggestions in this case  using ctrl+space but we don't auto re-trigger them if you are editing a word at any location except the end

**Comment by jrieken** [comment] 2018-04-19 07:32
Yep, we only trigger completions-as-you-type when typing at the end of a word.

**Comment by jrieken** [comment] 2018-04-19 07:33
dupe of #32201

**Closed** 2018-04-19 07:33 UTC
Labels: *duplicate
