### ISSUE TITLE
"Visual Studio Code has crashed" when editing an ES6 file

### ISSUE THREAD

**Issue by jacek-dargiel** [Microsoft/vscode#965] opened 2015-12-03 13:49 UTC
VSCode crashes every time I open an ES6 file, after a few seconds. This started happening after the 0.10.3 update.

Here's the output:

```
$ ./code --verbose

### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code\resources\app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded

<--- Last few GCs --->

   11777 ms: Scavenge 715.1 (742.6) -> 715.1 (742.6) MB, 0.2 / 0 ms (+ 5.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   11865 ms: Mark-sweep 715.1 (742.6) -> 714.3 (738.6) MB, 88.2 / 1 ms (+ 6.0 ms in 2 steps since start of marking, biggest step 5.0 ms) [last resort gc].
   11919 ms: Mark-sweep 714.3 (738.6) -> 714.4 (737.6) MB, 54.1 / 1 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 12320E39 <String[7]: file://>
    1: slowToString [buffer.js:344] [pc=0F1B78F8] (this=0F9F3DA5 <an Uint8Array with map 34609681>,encoding=123236C9 <String[4]: utf8>,start=0,end=3694146)
    2: toString [buffer.js:~371] [pc=24AAD709] (this=0F9F3DA5 <an Uint8Array with map 34609681>)
    3: arguments adaptor frame: 3->0
    4: write [string_decoder.js:129] [pc=24A3D6FD] (this=0F9FD0C5 <an InternalDecoder with map 2C6981DD>...

[VS Code]: render process crashed!
Lifecycle#window-all-closed
Lifecycle#before-quit
App#dispose: deleting running instance handle
```

**Comment by jrieken** [comment] 2015-12-04 08:06
@jacek-dargiel Can give me estimate of your workspace size?

**Comment by jacek-dargiel** [comment] 2015-12-04 11:20
This particular project has ~30 JS files. There's also quite a few JS files in `web/node_modules`, but I'm excluding them with a `jsconfig.json` file:
```
{
	"compilerOptions": {
		"target": "ES6",
		"module": "amd"
	},
	"exclude": [
		"node_modules"
	]
}
```

**Comment by jrieken** [comment] 2015-12-04 12:15
yeah, we also won't go into those folders for perf reasons... can reproduce take a look at the process tree. one of the child process should go crazy (CPU, mem) before the crash happens

**Comment by jacek-dargiel** [comment] 2015-12-04 12:19
How can I do this on Windows? What info do you need?

**Comment by jrieken** [comment] 2015-12-04 13:30
the best tool is this: https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

**Comment by jacek-dargiel** [comment] 2015-12-05 15:40
Yes, I can confirm that one of the code processes did consume 800+ MB of memory just before crashing.

**Comment by jrieken** [comment] 2015-12-07 09:05
Thanks. What is the name of the process? even better can you attach a screen shot of process explorer before it happens?

**Comment by jacek-dargiel** [comment] 2015-12-07 11:42
Here you go. This is moments before the crash.

![code-crash](https://cloud.githubusercontent.com/assets/6029412/11626048/ea7bc39a-9cdf-11e5-8eea-841339aff346.png)

**Comment by jacek-dargiel** [comment] 2015-12-07 11:49
And here are the details of the of the process:

The command line is: `"C:\Program Files (x86)\Microsoft VS Code\code.exe" --type=renderer --no-sandbox --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --enable-pinch --device-scale-factor=1 --enable-delegated-renderer --num-raster-threads=4 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --channel="4212.1.1281448818\2102388047" /prefetch:673131151`

![code-crash-details](https://cloud.githubusercontent.com/assets/6029412/11626134/af46baf4-9ce0-11e5-8f15-3790d6499e91.png)

**Comment by jrieken** [comment] 2015-12-08 09:18
It seems like a worker in going crazy and is able to bring down the system. Soon, we will move the JavaScript language service out of process which will make this issue go away. Also, there was a problem with exclude-rules not being honoured. That got fixed with #703.

**Comment by bpasero** [comment] 2016-03-11 08:29
Looks like a good chance for endgame leak testing if it still happens.

**Comment by jrieken** [comment] 2016-03-11 08:31
@bpasero I don't see how that will be useful? Everything happens now in a separate process.

**Comment by bpasero** [comment] 2016-03-11 08:41
@jrieken yeah looks like this should move to salsa if it still happens

**Comment by jrieken** [comment] 2016-03-11 14:58
dupe of #4001

**Closed by jrieken** 2016-03-11 14:58 UTC
Labels: bug, freeze-slow-crash, important, js, upstream
