### ISSUE TITLE
How do I disable/fix automatic semicolon in CSS

### ISSUE THREAD

**Issue by edwin1217** [microsoft/vscode#101386] opened 2020-06-30 11:01 UTC
- VSCode Version: May 2020 (version 1.46)
- OS Version: macOS Catalina 10.15.3

Steps to Reproduce:

Whenever I write a line in CSS, VS Code will insert a semicolon for me. That’d be fine if this automatic insertion worked like those in HTML and JS, where if I manually enter a semicolon it replaces the automatically inserted one . . . However, it doesn’t, which is really frustrating. For example, if I write, “background-color:,” it’ll add ”;,” which I then have to skip over with the arrow-keys to proceed to the next line. This slows down everything drastically.

How do I (preferably) fix this, or just remove the feature entirely?

I've set "css.completion.completePropertyWithSemicolon": false, but it doesn't work.

**Comment by aeschli** [comment] 2020-06-30 18:36
`"css.completion.completePropertyWithSemicolon"` is the setting to disable the feature but the setting was broken due to a bug.

It is fixed in the latest insiders.
Duplicate of https://github.com/microsoft/vscode/issues/100684

**Closed by aeschli** 2020-06-30 18:36 UTC
