### ISSUE TITLE
Chinese command is not good idea

### ISSUE THREAD

**Issue by fishg** [Microsoft/vscode#5294] opened 2016-04-15 02:39 UTC
We coding almost on US.en keyboard, if need switch input method and switch command name to Chinese in brain then input, it's not good idea.
![qq20160415-0](https://cloud.githubusercontent.com/assets/1423545/14549803/dc8c4c4c-02f5-11e6-9422-2662ef4edc18.png)

**Comment by hax** [comment] 2016-04-15 03:00
duplicate #4679 ?

**Comment by egamma** [comment] 2016-04-15 06:57
Yes duplicate of #4679, thanks @hax

**Closed by egamma** 2016-04-15 06:57 UTC
