### ISSUE TITLE
ssh does not work 

### ISSUE THREAD

**Issue by roccasal** [microsoft/vscode#204609] opened 2024-02-07 14:06 UTC
Type: <b>Bug</b>

when i try to setup an ssh connection I got the error

Failed to connect to the remote extension host server (Error: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory))

i I try the same ssh connction dorm the linux terminal it works

ubuntu version 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.5.0-15-generic snap
Modes:
Connection to 'SSH' could not be established  A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 3265)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|30.55GB (26.84GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id fbd337e4-b6dd-4a2a-be90-e8848b8b35af|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

Connection to 'SSH' could not be established  A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30951795
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929
bg6jg535:30958357

```

</details>

**Comment by zxc2012** [comment] 2024-02-07 23:13
same here

**Comment by IllusionMH** [comment] 2024-02-08 00:28
Looks like duplicate of #204178

Please check steps from the end to see if it works

**Comment by roccasal** [comment] 2024-02-08 08:19
I , I have solved for the moment downgrading to version 1.85.2

**Comment by cipherLord** [comment] 2024-02-09 05:18
Doesn't work for me on version 1.85.2 on Mac since today. Previously I had also downgraded to lower version to make it work.

**Comment by roblourens** [comment] 2024-02-15 18:07
https://github.com/microsoft/vscode/issues/204178

**Closed by roblourens** 2024-02-15 18:07 UTC
