### ISSUE TITLE
mac 程序坞中的 图标特别小

### ISSUE THREAD

**Issue by langgo** [Microsoft/vscode#72990] opened 2019-04-28 08:07 UTC
Issue Type: <b>Bug</b>

不清楚

![image](https://user-images.githubusercontent.com/15521789/56861031-9a563b00-69cf-11e9-9cdd-43580a8b15bb.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
sqlformatter|bre|0.0.7
rainbow-csv|mec|1.0.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.4.11987
sqltools|mtx|0.17.15

</details>

**Comment by gjsjohnmurray** [comment] 2019-04-28 08:26
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/63068

**Closed** 2019-04-28 08:38 UTC
