### ISSUE TITLE
Close Tab with keyboard shortcut on Mac sometimes closes two tabs

### ISSUE THREAD

**Issue by brycefranzen** [microsoft/vscode#86944] opened 2019-12-13 16:15 UTC
Issue Type: <b>Bug</b>

Open 3 files. Have far right file selected.
Press `cmd+w` to close tab.
Press `cmd+w` to close the next tab.

Notice the last two open tabs are closes simultaneously.  This should only close ONE tab at a time.

This was NOT a bug in the previous version.

This appears to have been introduced recent update
version: 1.41.0 
commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|-psn_0_2273835|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.4.2
project-manager|ale|10.9.1
laravel-extra-intellisense|ami|0.2.3
tasks-shell-input|aug|0.3.2
laravel-docs|aus|1.4.3
touch-bar-display|bla|1.3.1
vscode-intelephense-client|bme|1.2.3
multi-cursor-case-preserve|Car|1.0.4
turbo-console-log|Cha|1.3.1
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.2
open-in-sketch|dav|2.1.0
gitlens|eam|10.2.0
clipboard-manager|Edg|1.2.0
LogFileHighlighter|emi|2.6.0
prettier-vscode|esb|3.11.0
comment-anchors|Exo|1.6.1
php-debug|fel|1.13.0
macros|ged|1.2.1
html-slim-scss-css-class-completion|gen|1.5.23
vscode-nginx-conf-hint|han|0.1.0
minify|Hoo|0.4.3
output-colorizer|IBM|0.1.2
vscode-cdnjs|Jak|0.18.0
gitlab-mr|jas|1.4.2
search-node-modules|jas|1.3.0
chat|kar|0.29.0
cssSuggestions|kun|1.0.11
twig-language-2|mbl|0.9.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.9.0
atom-keybindings|ms-|3.0.6
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1377
vsliveshare-audio|ms-|0.1.80
debugger-for-edge|msj|1.0.13
php-docblocker|nei|2.1.0
vetur|oct|0.22.6
react-proptypes-intellisense|OfH|1.0.3
vscode-jest|Ort|3.0.2
material-icon-theme|PKi|3.9.2
vscode-react-refactor|pla|1.0.5
tsimporter|pmn|2.0.1
react-maker|Qes|0.2.3
laravel-helpers|raf|0.2.2
sass-helper|ram|0.0.2
code-spell-checker-fullstack|rba|0.0.8
datetime|rid|1.0.5
laravel-artisan|rya|0.0.27
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
svg-preview|Sim|2.7.7
laravel-goto-controller|ste|0.0.7
code-spell-checker|str|1.7.20
tabnine-vscode|Tab|2.1.22
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.9.0
errorlens|use|2.8.1
quokka-vscode|Wal|1.0.265
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.6.1
file-size|zh9|0.1.3
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2019-12-13 18:18
Closing as a duplicate of https://github.com/microsoft/vscode/issues/86790

**Closed by RMacfarlane** 2019-12-13 18:18 UTC
Labels: new release
