### ISSUE TITLE
Snippets should work with JSX DOM

### ISSUE THREAD

**Issue by bang88** [Microsoft/vscode#21477] opened 2017-02-27 08:58 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10
- TypeScript Version: 2.2.1

Steps to Reproduce:

1.  Install snippets https://marketplace.visualstudio.com/items?itemName=bang.antd-snippets
2.  Create a React Component test.tsx file,

Or see the gif here.

![preview](https://cloud.githubusercontent.com/assets/433259/23354736/87607848-fd0d-11e6-97fc-c3733b984856.gif)

**Comment by mjbvz** [comment] 2017-02-27 23:23
I believe this is a duplicate of #19954

I just tried this out in [VSCode insiders](https://code.visualstudio.com/insiders) (1.10) and we unable to reproduce this issue. Please trying upgrading and let me know if you still see this problem

**Closed by mjbvz** 2017-02-27 23:23 UTC
Labels: duplicate, javascript, snippets, typescript
