### ISSUE TITLE
keybinding "shift+cmd+/" dosen't work

### ISSUE THREAD

**Issue by Z-HNAN** [microsoft/vscode#105471] opened 2020-08-27 05:19 UTC
- VSCode Version: Version: 1.48.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. setting keybinding in `keybindings.json`
```json
[
  {
  "key":"shift+cmd+/",
  "command":"editor.action.blockComment",
  "when":"editorTextFocus"
  }
]
```
![image](https://user-images.githubusercontent.com/38390666/91387267-79be1f80-e867-11ea-89b0-e2ab1c93108a.png)

2. when i type `shift+cmd+/`，open this window

![image](https://user-images.githubusercontent.com/38390666/91387336-a2461980-e867-11ea-90e9-5e8d0ca973f5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-08-27 11:07
Did you check whether that key is also assigned to another command?

**Comment by gjsjohnmurray** [comment] 2020-08-27 11:12
Forget my previous question.

/duplicate of #85901

**Closed** 2020-08-27 11:13 UTC
Labels: *duplicate
