### ISSUE TITLE
VSCode - Visual Problem

### ISSUE THREAD

**Issue by MhmdItani** [microsoft/vscode#102523] opened 2020-07-14 17:54 UTC
Image will describe my problem better.. I've been facing this problem for quite some time which made me use another text editor but I need to find a fix for my problem!
I've tried uninstalling and re-installing, gave it real-time priority in task manager, updated all my drivers and windows 10 to latest versions, and still the problem isn't solved.. I'm not sure if it's a problem from my pc or from VSCode itself but for the most part I did everything I could do on my side

![Screenshot (15)](https://user-images.githubusercontent.com/60862612/87459371-fa0c2680-c613-11ea-931e-5944866242ec.png)

**Comment by IllusionMH** [comment] 2020-07-14 18:05
/duplicate of #93356 or #94523

Should be fixed with starting VS Code with `code --disable-gpu` or more permanent setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed** 2020-07-14 18:06 UTC
Labels: *duplicate
