### ISSUE TITLE
Commit warning gets on top of "staged changes"

### ISSUE THREAD

**Issue by bernaferrari** [microsoft/vscode#101628] opened 2020-07-02 18:53 UTC
The "x characters over 50 in current line" can get on top of "Staged Changes". This is bad, because "Staged Changes" contains:
- a button to minimize,
- the number of files,
- and its own name. 

I was committing and thought "ok, what am I committing? Where are the staged changes?", only to find out it was behind the warning. This might also be an accessibility issue since it might block screen readers from finding the staged changes and, therefore, can confuse people.

![image](https://user-images.githubusercontent.com/351125/86398159-8b29e780-bc7b-11ea-90f5-95f7c29c9c89.png)

![image](https://user-images.githubusercontent.com/351125/86398139-8402d980-bc7b-11ea-9661-293f78f1acd0.png)

**Comment by gjsjohnmurray** [comment] 2020-07-02 19:56
Several duplicates including #72304, #92362. The SCM refactor in upcoming 1.47 hasn't improved this.

**Comment by bernaferrari** [comment] 2020-07-02 20:02
Uh oh! I couldn't find them. So.. should I close? They were closed as designed, but the bug is still there.

**Comment by gjsjohnmurray** [comment] 2020-07-02 20:05
Maybe wait to see if @joaomoreno's position on this has changed.

**Comment by joaomoreno** [comment] 2020-07-03 07:42
We decided to close this as designed simply because:

- Pushing content down due to a validation error would to overkill
- There are many ways to dismiss the validation (<kbd>Escape</kbd>, click it)
- It doesn't block accessibility, since screen readers don't really _read_ the screen, but inspect the DOM
- It doesn't block actual content, but just the `Staged Changes` or `Changes` row, most of the time

**Closed by joaomoreno** 2020-07-03 07:42 UTC

**Comment by gjsjohnmurray** [comment] 2020-07-03 08:20
@joaomoreno thanks for the well-reasoned response. Did you ever experiment with giving the message background a bit of transparency as a subtle reminder to the user that there's something behind it? I had a go at doing this with developer tools open, but couldn't work out how to get hold of the DOM item without it vanishing.

**Comment by joaomoreno** [comment] 2020-07-03 08:47
Ehehe yeah grabbing elements which go away is always tricky. I think opacity wouldn't work so well as it would make the text less legible, right?

**Comment by gjsjohnmurray** [comment] 2020-07-03 09:25
> I think opacity wouldn't work so well as it would make the text less legible, right?

Probably. Maybe it's possible to leave text background fully opaque and only add transparency to the unoccupied background of the warning.

**Comment by joaomoreno** [comment] 2020-07-03 09:27
Hmm still not convinced 🤔, wouldn't it look broken?

**Comment by gjsjohnmurray** [comment] 2020-07-03 10:07
With `opacity: 0.8;` (theme is Quiet Light)

![image](https://user-images.githubusercontent.com/6726799/86458087-9bde6a00-bd1c-11ea-866e-f3d8db85f621.png)

Same with Dark+

![image](https://user-images.githubusercontent.com/6726799/86458384-10b1a400-bd1d-11ea-8000-bab73b0f35c1.png)

**Comment by joaomoreno** [comment] 2020-07-03 10:37
Thanks for the screenshots, good job! But I still don't really think it's good UI. 😢 Also, the user's concern is still not address: to read what's underneath. I mean, they know there's something underneath, but not what.

**Comment by gjsjohnmurray** [comment] 2020-07-03 11:07
@bernaferrari is this opacity any improvement for you? For me it acts as a better hint that there's information behind the message. Particularly the count badge. We already get small clues from the parts that the message doesn't overlap (e.g. the descender of the 'g' in 'Staged Changes'. But that sort of clue may not be present in some localizations.

**Comment by yume-chan** [comment] 2020-07-03 11:28
Relates to #33752 for tooltips covering thing below.

Opacity may not work for High Contrast themes.

However as I mentioned there, Visual Studio (not Code) will make tooltips almost transparent (can see through very clearly, but still know there is a tooltip) when user holding down Ctrl key for about one second.

**Comment by bernaferrari** [comment] 2020-07-03 15:58
@gjsjohnmurray Yes! But as pointed by others, it doesn't seem like "the best" solution, specially concerning other modes like high contrast.

When I opened the issue, I was actually thinking "what if the alert message could slide down the interface?". I think it could work better than being a pop-up on top of everything - would also solve the issue for other scenarios. Plus, users would get a free animation.
