### ISSUE TITLE
JsDoc - import in html file failed

### ISSUE THREAD

**Issue by ObscurusGrassator** [microsoft/vscode#115592] opened 2021-02-02 08:43 UTC
- VSCode Version: 1.52.1
- OS Version: macOS Catalina (10.15.7)

a.html
```
<html>
	<script>
		/** @type {typeof import('./c.js')} */
		var that;


		that.
	</script>
</html>
```
b.js
```
/** @type {typeof import('./c.js')} */
var that;


that.
```
c.js
```
module.exports = function() {

	/** @type { String } */
	this.myVariale = 'aaa';

	return this;
}();
```

WORKING:
<img width="593" alt="Snímka obrazovky 2021-02-02 o 9 39 07" src="https://user-images.githubusercontent.com/17063579/106574131-cd314980-653a-11eb-864b-b6db51916c52.png">

FAILED:
<img width="655" alt="Snímka obrazovky 2021-02-02 o 9 38 42" src="https://user-images.githubusercontent.com/17063579/106574104-c73b6880-653a-11eb-8e6f-64084719e319.png">

**Comment by aeschli** [comment] 2021-02-02 13:19
duplicate of https://github.com/microsoft/vscode/issues/114115

**Closed by aeschli** 2021-02-02 13:19 UTC
