### ISSUE TITLE
quick fix popmenu not show 

### ISSUE THREAD

**Issue by marshalys** [microsoft/vscode#92861] opened 2020-03-17 15:27 UTC
my mac work with 2 screen. when vscode is on my right screen the popmenu is not show, but  it is work fine on my left screen.

- VSCode Version: 1.43.0
- commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
- date: 2020-03-09T19:34:44.548Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. move vscode window to my right screen.
2. click quick fix

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-03-17 19:05
I'm not able to reproduce this issue. Do other context menus work for you (for example, in the explorer or when you right click in the editor?)

**Comment by marshalys** [comment] 2020-03-18 04:57
I'm sorry, maybe I didn't describe clearly .
the popmenu didn't show is: 
![image](https://user-images.githubusercontent.com/344530/76926666-dfe96280-6917-11ea-879e-0747e3a42615.png)

**Comment by mjbvz** [comment] 2020-03-18 06:36
Yes, I always see that menu even in a multi monitor setup on MacOS.

Is it just the lightbulb menu that doesn't work? Do right click menus work?

**Comment by marshalys** [comment] 2020-03-18 13:18
Yes, only lightbulb menu doesn't work. Right click menus work fine.

**Comment by mjbvz** [comment] 2020-11-10 21:39
Closing as I've been unable to reproduce this in any window/monitor setup and have not seen other reports of this issue

**Closed by mjbvz** 2020-11-10 21:39 UTC
Labels: bug, editor-code-actions, help wanted
