### ISSUE TITLE
Open Folder doesn't work

### ISSUE THREAD

**Issue by helloanil** [microsoft/vscode#85455] opened 2019-11-23 12:47 UTC
Issue Type: <b>Bug</b>

I don't know if it's because of an extension or the latest version but suddenly `code .` command from the shell and Open Folder feature stopped working for me. They both show me empty workspace.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.8.0
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.27
graphql-for-vscode|kum|1.15.3
vscode-icons|vsc|9.5.0

</details>

**Comment by egamma** [comment] 2019-11-23 16:26
/needsMoreInfo

Can you reproduce this for different folders?
Can you reproduce this when using the insiders version?

**Comment by sestegra** [comment] 2019-11-24 09:33
Same issue with same VS Code version on same OS version.
In the VS Code UI, "No Folder opened" is displayed instead of the desired folder.

I tried on many different folders without success using following commands:
- `code .`
- `code <relative folder>`
- `code <absolute folder>`
- `code --disable-extensions .`
- `code --disable-extensions <relative folder>`
- `code --disable-extensions <absolute folder>`

After installing VS Code Insiders, `code-insiders .` is working as expected.

**Comment by egamma** [comment] 2019-11-24 12:42
@sestegra some more questions:

Is there an error message in the dev tools console  (Help>Toggle Developer Tools, then open the Console tab) when it happens.

Does it help when you resize the window.

Can you start code with a different location of your configuration data `code --user-data-dir SOME_DIR .`

**Comment by sestegra** [comment] 2019-11-24 15:54
When launching `code --disable-extensions .`, I got following error in console.
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:5 [uncaught exception]: Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:11:19)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6187:387)
    at Q.resolveWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6186:742)
    at Q.initServices (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6186:202)
    at Q.open (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6183:733)
    at Object.t.main (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6188:826)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.js:8:763
onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:5
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:6 Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/internal/process/main_thread_only.js:42)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:11)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6187)
    at Q.resolveWorkspaceInitializationPayload (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6186)
    at Q.initServices (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6186)
    at Q.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6183)
    at Object.t.main (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6188)
    at workbench.js:8
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:51
onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:6
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1541   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

When launching `code --user-data-dir . .` is working as expected.

**Comment by egamma** [comment] 2019-11-25 09:54
>When launching code --user-data-dir . . is working as expected.

Given that starting with a different UI state works, this indicates that you have something in the UI state that makes VS Code crash.

Assigning to @jrieken for further guidance.

**Comment by jrieken** [comment] 2019-11-25 10:12
@sestegra Any chance you deleted the folder you are in? Can you try `cd ..` and the `cd FOLDER` and try again?

**Comment by sestegra** [comment] 2019-11-25 10:27
@jrieken After executing `code --user-data-dir . .` and since I moved back user-data to the default folder, the issue isn't reproductible with my computer anymore.

**Comment by jrieken** [comment] 2019-11-25 10:29
Ok, then waiting for @helloanil

**Closed** 2019-12-02 13:15 UTC
Labels: needs more info

**Comment by avinashsivaraman** [comment] 2020-01-02 07:58
I faced the same issue today. I restarted my machine and the issue is gone. I don't know how it is related.
