### ISSUE TITLE
Opening settings while having the tiny find box open will cause it to error.

### ISSUE THREAD

**Issue by KingDGrizzle** [Microsoft/vscode#56456] opened 2018-08-15 09:44 UTC
Issue Type: <b>Bug</b>

Have a split screen layout of tabs (in halves, I have 2 tabs on the left and 2 on the right)
Press CTRL + F in the first file from the right side of the screen.
Go to File -> Preferences -> Settings

Two errors can occur:

- ModelService: Cannot add model because it already exists!
- Cannot read property 'focus' of undefined IF you do the same steps in another file that's open on the right side, that is NOT the first file

VS Code version: Code - Insiders 1.27.0-insider (ffa660576d3a8da3f6cf9b94cbfb879632688ebd, 2018-08-15T05:19:24.200Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 3010)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (2.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
klasa-vscode|bdi|0.2.4
emojisense|bie|0.4.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
vscode-yarn|gam|1.6.0
gc-excelviewer|Gra|2.1.25
discord-vscode|icr|2.7.0
svg|joc|0.1.1
docthis|joe|0.7.1
vscode-gist|ken|1.2.1
git-indicators|lam|2.1.1
prettify-json|moh|0.0.3
vscode-cosmosdb|ms-|0.8.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
Go|ms-|0.6.87
vsliveshare|ms-|0.3.535
vetur|oct|0.12.6
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.2
polacode|pnp|0.2.2
code-settings-sync|Sha|3.0.0
html-preview-vscode|tht|0.1.1
vscodeintellicode|Vis|1.0.3
vscode-wakatime|Wak|1.2.3
quokka-vscode|Wal|1.0.136
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by roblourens** [comment] 2018-08-16 00:58
Dupe of https://github.com/Microsoft/vscode/issues/56432

**Closed by roblourens** 2018-08-16 00:58 UTC
Labels: search
