### ISSUE TITLE
Have a "Close All" button as editor action in the toolbar

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#49591] opened 2018-05-10 03:26 UTC
This may be the best extension that no one knows about...

https://marketplace.visualstudio.com/items?itemName=benjpas.close-all

but, i'm tired of reinstalling it!

Suggestion: Include this functionality in the core of VS Code.

**Comment by Emeryao** [comment] 2018-05-10 04:03
I think the `Close All Editors` works fine for me 😝 

![image](https://user-images.githubusercontent.com/3591899/39851566-1ed28b1e-544a-11e8-9469-afb96f04c759.png)

**Comment by usernamehw** [comment] 2018-05-13 17:36
Possible duplicate of #9285

**Comment by bpasero** [comment] 2018-06-02 09:02
I am now showing this command when you press the `Alt` key:

![before](https://user-images.githubusercontent.com/900690/40872768-580f1c78-6654-11e8-9879-16201d4daf62.gif)

**Closed by bpasero** 2018-06-02 09:02 UTC
Labels: feature-request, workbench-editors
