### ISSUE TITLE
Strange syntax highlighting

### ISSUE THREAD

**Issue by zgoda** [Microsoft/vscode#24230] opened 2017-04-07 14:18 UTC
- VSCode Version:

```
Version 1.11.1
Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
Date 2017-04-06T13:55:56.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

- OS Version:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

I stumbled across strange syntax coloring, I can't recall if this was present before.

![zrzut ekranu z 2017-04-07 16-09-02](https://cloud.githubusercontent.com/assets/141999/24803972/39054138-1bad-11e7-9007-70c876ff5ddf.png)

I used Monokai theme to make the problematic parts more visible - note `define` on lines 13 and 22, and `include` on lines 17 and 18. This is consistent across all colour schemes I have installed, including defaults.

**Comment by chrmarti** [comment] 2017-04-07 15:22
This in a .h file reproduces it:
```h
#ifdef FOO
    #define BAR
    #define BAZ
#endif
```

**Comment by aeschli** [comment] 2017-04-07 16:01
duplicate of #23630

**Closed by aeschli** 2017-04-07 16:01 UTC
