### ISSUE TITLE
Increased sash size makes scrolling diff view difficult

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#99289] opened 2020-06-03 15:30 UTC
Testing #99016

1. Set the workbench.sash.size to 20
2. Open the diff view for a pending commit diff with the diff view using the inline view
3. Try to grab the scroll bar at the bottom.

The scroll bar grab region is very small. You only get an arrow cursor if you are at the top of the scroll bar, otherwise you get the resize cursor.

When set to the default 4 pixels, you can grab most of the scroll bar.

**Comment by lszomoru** [comment] 2020-06-04 08:46
Thanks @gregvanl. Will have a chat with @joaomoreno to see if there is anything we can do to improve this.

**Comment by joaomoreno** [comment] 2020-06-04 08:58
Yeah there's no winning here, unless sashes are visible themselves. I would close this as designed since systems which require large sashes (20) also feature scrolling by dragging the view instead of the scrollbar.

**Comment by lszomoru** [comment] 2020-06-08 09:03
Since sashes and scroll bar compete the same screen real estate, I agree with @joaomoreno.
Will be monitoring customer feedback as this setting is being rolled out and will reconsider if needed.

**Closed by lszomoru** 2020-06-08 09:03 UTC
