### ISSUE TITLE
Toggle Extension auto update

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#26960] opened 2017-05-19 18:58 UTC
I think we should add an option to toggle the extension auto-update in this menu - perhaps we considered this and did not do it for some reason?

From my point of view it will help with discovery and it's also good even if we do many auto-update the new default i.e. users will be able to turn off without needing to go int settings editing.

![image](https://cloud.githubusercontent.com/assets/1051190/26262642/55a02602-3c8a-11e7-88f8-bb62dae674be.png)

cc // @egamma

**Comment by egamma** [comment] 2017-05-22 07:12
@seanmcbreen this is a duplicate of #25246

**Closed by egamma** 2017-05-22 07:12 UTC
Labels: duplicate, feature-request
