### ISSUE TITLE
allow global renaming like it used to be

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#66377] opened 2019-01-11 05:02 UTC
there is this shiny new feature of defensive renaming where, if possible, renaming only affects local symbols, it's amazing and all, but can we have the old behavior back as an option:
- **do aggressive renaming up to the declaration of a symbol**

cross posted at: https://github.com/Microsoft/TypeScript/issues/29362

**Comment by mjbvz** [comment] 2019-01-11 18:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/29238

**Closed by mjbvz** 2019-01-11 18:47 UTC
Labels: typescript
