### ISSUE TITLE
Please create meaningful error messages

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/vscode#27962] opened 2017-06-03 00:52 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|vscode-npm-script|eg2|0.2.0|
|code-runner|formulahendry|0.6.18|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.5|
|debugger-for-chrome|msjsdiag|3.1.2|
|open-in-browser|techer|1.0.0|
|iis-express|warren-buckley|1.0.0|;

---
Please crate a better error message. You do not really expect me to count characters, do you?
So where in the example below is position 449? Please print the line number instead.

Kind regards, Lord Saumagen.

Steps to Reproduce:

Open a JSON file and create an error.

![vscode_error_message](https://cloud.githubusercontent.com/assets/9468599/26749243/2b85754c-4807-11e7-9d65-95e88dadab55.png)

**Comment by mjbvz** [comment] 2017-06-05 17:16
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10384 which tracks showing the correct error location in ts/jsconfig files

**Closed by mjbvz** 2017-06-05 17:16 UTC
Labels: duplicate, javascript, typescript, upstream
