### ISSUE TITLE
Exiting last terminal does not close the view if other panels are present & obstructs opening a new one

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#236517] opened 2024-12-18 20:12 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.96.0
- OS Version: Ubuntu 22.04

This is a resubmission (by a different person) of #165067 which was closed as unable to reproduce. I'm seeing it frequently (more often than not), but not 100% of the time.

The prior submission pointed the blame at the gitlens extension, but I don't have that extension installed.

I am available and happy to collect any additional trace data that would assist in pinpointing this issue.

Steps to Reproduce:

0. Work for a while in vscode (I haven't figured out what gets things into a bad state yet)
1. Use `` Ctrl-` `` to open a terminal
2. Use `Ctrl-D` or such to exit the terminal
3. Observe the bottom panel stays open
4. Try `` Ctrl-` `` again, observe no terminal opens
5. Use the `X` button to close the bottom panel and try again, observe that things are working again now
6. ... for a little while, but the problem comes back
7. Run `Developer: Reload Window`
8. Try `` Ctrl-` `` again and observe things are working
9. ... for a little while, but the problem comes back

EDIT: Full standalone repro steps are in https://github.com/microsoft/vscode/issues/236517#issuecomment-2555621925

**Comment by meganrogge** [comment] 2024-12-18 21:14
Closing as I cannot reproduce

**Comment by mgabeler-lee-6rs** [comment] 2024-12-18 21:23
@meganrogge So ... you are certain you have the exact same setup as I do and did the exact same things I did? It doesn't matter to you that someone else _can_ reproduce it _hundreds of times a day_?

This feels like an extremely user-hostile reaction from you.

**Comment by meganrogge** [comment] 2024-12-18 21:28
>This feels like an extremely user-hostile reaction from you.

I have hundreds of issues I'm responsible for. I do value your issue, but given I cannot reproduce, it's hard to investigate it.

Does using `Developer: Toggle Keyboard Shortcuts Troubleshooting` reveal anything interesting?

Also, you could create a gif after running `Developer: Toggle Screencast Mode` that might help.

**Comment by mgabeler-lee-6rs** [comment] 2024-12-18 23:12
> I do value your issue, but given I cannot reproduce, it's hard to investigate it.

I definitely understand this dilemma. My note "I am available and happy to collect any additional trace data that would assist in pinpointing this issue." was meant to help address this 🙂.

And since you did provide some pointers, I'll use them to gather more data when this next happens, thanks.

**Comment by mgabeler-lee-6rs** [comment] 2024-12-18 23:39
Just happened to me. Here's the keyboard shortcuts troubleshooting output from hitting `` Ctrl-` `` while the terminal panel was focused but no terminal was present:
```
2024-12-18 18:30:32.816 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backquote, keyCode: 192, key: `
2024-12-18 18:30:32.816 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backquote, keyCode: 91 ('`')
2024-12-18 18:30:32.816 [info] [KeybindingService]: | Resolving ctrl+[Backquote]
2024-12-18 18:30:32.817 [info] [KeybindingService]: \ From 1 keybinding entries, matched workbench.action.terminal.toggleTerminal, when: terminal.active, source: built-in.
2024-12-18 18:30:32.817 [info] [KeybindingService]: + Invoking command workbench.action.terminal.toggleTerminal.
2024-12-18 18:30:32.951 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

I also noticed that switching to a different panel in the bottom region (e.g. the output view to see this diagnostic text) would cause the keybinding to work while that other panel was focused, but going back to the terminal and hitting `Ctrl-d` would produce the "bad state" again. Screencast attached.

https://github.com/user-attachments/assets/797bd714-e7ef-417f-8695-e334070bc8a8

I'll leave this window open in the state where I can reproduce this easily so I can gather any more trace data that would help

**Comment by meganrogge** [comment] 2024-12-19 16:56
> Observe the bottom panel stays open

This is the part that I'm unable to reproduce and that should not be happening 

https://github.com/user-attachments/assets/e98222bc-7b8c-4ad8-963d-23479404a04e

**Comment by meganrogge** [comment] 2024-12-19 16:58
What are your terminal settings?

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 19:21
Terminal settings:
```json
  "terminal.integrated.fontSize": 11,
  "terminal.integrated.scrollback": 5000,
  "terminal.integrated.allowChords": false,
  "terminal.integrated.sendKeybindingsToShell": true,
  "debug.terminal.clearBeforeReusing": true,
  "terminal.integrated.tabs.enabled": true,
  "terminal.integrated.showExitAlert": false,
  "accessibility.signals.terminalBell": {
    "sound": "on"
  },
  "terminal.integrated.enableVisualBell": true,
  "terminal.integrated.shellIntegration.enabled": false,
```

Is there some "trace" options I could enable to help get more diagnostic data when this is happening? Or a way to figure out which of my enabled extensions have stuck "hooks" into the terminal logic? The only ones that seems _likely_ to have done that are the copilot/chat ones.

And maybe the Go extension:
- The workspace I showed the screencast of is a go project
- When I closed the terminal and the panel stayed open, I noticed that there was a "hidden" `go` terminal: ![Image](https://github.com/user-attachments/assets/bf71d39a-3a44-4468-82b0-015803121e9d)
- If I click (check) the menu item to show it, I get this: ![Image](https://github.com/user-attachments/assets/2cc13254-16f7-416b-8d06-020a7205ba53)

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 19:22
Addendum: with the "go terminal" visible, Ctrl-backtick still doesn't work after I've closed the "normal" terminal, and the normal terminal's menu item in the `...` is still checked, but also disabled: ![Image](https://github.com/user-attachments/assets/c32dacd0-3e1b-4d9a-bdb9-2a169b32f5d3)

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 19:30
OK, making progress. I can make this happen without any bits from the Go extension. I seem to have dragged a "right side panel" pane for that Go stuff into the terminal area by accident at some point. If I "reset location" on that panel, the problem goes away.

And with that information, I can now provide repro steps that work in a "clean" window and so _hopefully_ aren't specific to my environment:
1. Start vscode clean -- `code --new-window --disable-extensions`
2. Create a new document
3. Create a new terminal
4. Use the command pallet to run "Focus on Outline view"
5. Drag the outline view into the terminal panel so they are side by side
6. Put keyboard focus in the terminal and exit the shell
7. Observe the panel stays open with the outline view
8. Right click the outline panel header and choose "Hide Outline" -- now we have a blank terminal panel
9. Try to start a new terminal e.g. via Ctrl-backtick -- it doesn't work
10. Etc... as per the earlier repro steps

And to "un-break" things:
11. Click the `...` in the terminal panel and show the outline view
12. Right click the Outline view and choose Reset location to move it back to the right bar
13. Use the `X` to close the terminal panel
14. Now starting & exiting a terminal works "normally" again

**Comment by meganrogge** [comment] 2024-12-19 19:45
Nice, thanks for the repro steps!

Adding this for anyone who wants to take a stab at the fix https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 20:11
> Are there any errors in the dev tools console

I was checking for this hoping for something helpful, but no. There's nothing added to the developer console in any of steps 2-9.

> Create new terminal

This _does_ work. That's `` Ctrl+Shift+` `` for me. `` Ctrl+` `` is bound to `View: Toggle Terminal` (I think those are defaults)

**Comment by meganrogge** [comment] 2024-12-19 20:23
This is happening because the panel is not focused in this case, since there's no terminal. See how if I focus the terminal panel header, using `ctrl+`` does work. 

https://github.com/user-attachments/assets/aa528c8d-ed1c-49ff-9c75-318d2c0a0794

**Comment by Tyriar** [comment] 2024-12-19 20:40
I think there are some obscure cases where you can get into this state where the terminal panel is visible but there is no terminal inside it. The example of having outline beside terminal is one of these cases by design as far as I can recall.

This one is not and I have no idea how you pulled this one off:

![Image](https://github.com/user-attachments/assets/f6fcebec-1ff3-4de5-9af5-b704a912fa73)

ctrl+d definitely closes all shells and the panel for me.

> Try to start a new terminal e.g. via Ctrl-backtick -- it doesn't work

All ctrl+` does is toggles the view, which when not visible will create a new terminal. It feels a little risky to do this when the panel is empty as it could get into a loop of terminal creation/failure. ctrl+shift+` should reliably create and focus a new terminal so I'd recommend using that when you know you want a new one.

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 21:01
> This one is not and I have no idea how you pulled this one off

Repro step 8 above -- "Right click the outline panel header and choose "Hide Outline" -- now we have a blank terminal panel" is how this happens. There's another view in the panel (Go in the case of that screencast, Outline in the case of the isolated repro steps), but it's hidden so it just shows as an empty panel.

**Comment by meganrogge** [comment] 2024-12-19 21:03
Yes, I am able to reproduce that ^ by moving the outline view out for example.

**Comment by Tyriar** [comment] 2024-12-19 21:06
> Repro step 8 above -- "Right click the outline panel header and choose "Hide Outline" -- now we have a blank terminal panel" is how this happens.

Ah in that case it's working as intended since you're managing views and wouldn't want the view to suddenly disappear or have a process created just by moving things around.

**Comment by Tyriar** [comment] 2024-12-19 21:45
After a bunch of discuss with @meganrogge this is where we landed on improvements for this:

1. Align single visible view in container behavior with single view in container - so ctrl+d in your original report would close the terminal and fix the primary problem here
2. Add setting to allow users to disable hiding the terminal on last killed if they want - this has been an ask for a while and might be a good time to do that
3. Add a welcome message to advertise ctrl+shift+` - if we do 2 we should try do this too so it doesn't look broken and advertises the shortcut

**Comment by mgabeler-lee-6rs** [comment] 2024-12-19 21:47
One more thought on that: Even with the secondary panel visible, _empirically_ users (like me) are going to be used to thinking of "Ctrl+backtick brings me to a terminal if I'm not already there", even if that isn't _technically_ what the command says it does -- the mental model seems likely to be "toggle the terminal" vs "toggle the terminal panel".

As such, even in the case of having a secondary view visible in the terminal panel, having that keybind only _sometimes_ create a new terminal when there isn't an existing one is confusing behavior. Yes, the command has an internally consistent behavior spec, but IMO it's not a spec folks would choose to write up "intentionally". The distinction between the terminal panel vs a terminal view within it, for that specific command, doesn't seem helpful to me. A command that does "bring me to a terminal if I'm not already in one" seems more useful / more like what people probably expect. It's at least what _I_ expect :)

**Comment by Tyriar** [comment] 2024-12-19 21:49
@mgabeler-lee-6rs added a 4 as well based on that 👌

**Comment by Tyriar** [comment] 2024-12-20 13:40
Ended up doing all but 3 and the experience is pretty nice: https://github.com/microsoft/vscode/pull/236696

![Image](https://github.com/user-attachments/assets/e7d9c049-429d-41f1-9a29-48eaf1b5a495)

**Closed** 2024-12-20 14:03 UTC
Labels: bug, terminal-layout

**Comment by mgabeler-lee-6rs** [comment] 2024-12-20 14:20
Thank you!

**Comment by Tyriar** [comment] 2025-01-27 19:02
To verify this please test the new `terminal.integrated.hideOnLastClosed` setting.
