### ISSUE TITLE
file name changes to all uppercase letters

### ISSUE THREAD

**Issue by hei06j** [microsoft/vscode#115644] opened 2021-02-02 23:51 UTC
Issue Type: <b>Bug</b>

Hi, I am developing a package in julia and have used all lowercase for the module name and module file name, but as soon as I save the module file, the filename becomes all uppercase. This is causing my package to crash. Any idea how to fix it?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
toml-formatter|ice|0.0.3
language-julia|jul|1.0.10
vscode-docker|ms-|1.9.1
beautify-json|ran|1.0.2
language-opendss|tsh|0.1.1

</details>

**Comment by IllusionMH** [comment] 2021-02-03 00:03
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

How you create and save file? Do you create it in Explorer view with all lower case characters or you create Untitled file and save it?

**Comment by hei06j** [comment] 2021-02-03 04:23
I created the file within VScode, in uppercase letters first, then commit to github, then changed the filename to lowercase. Even though the file name in VScode explorer and github shows lowercase, the filename appears uppercase on the top of the page when the file is open. 
<img width="1788" alt="Screen Shot 2021-02-03 at 3 21 50 pm" src="https://user-images.githubusercontent.com/29138184/106697848-bd496080-6633-11eb-8e17-f204d7e3ed26.png">

**Comment by IllusionMH** [comment] 2021-02-03 11:49
This one like duplicate of #101040 however it's duplicate of some other issue which is hard to find.

**Closed** 2021-02-15 11:30 UTC
Labels: needs more info

**Comment by IllusionMH** [comment] 2021-02-15 11:37
@JacksonKearl is this one correctly closed? Author replied after `needsMoreInfo` command

**Comment by JacksonKearl** [comment] 2021-02-16 16:10
@IllusionMH you count as team for purposes of needs-more-info. Would you like me to change that? https://github.com/microsoft/vscode/blob/main/.github/workflows/needs-more-info-closer.yml#L27

**Comment by IllusionMH** [comment] 2021-02-16 16:24
I thought that comment https://github.com/microsoft/vscode/issues/115644#issuecomment-772215159 which comes after Bot's comment https://github.com/microsoft/vscode/issues/115644#issuecomment-772100913 should count as answer to request.

No need to change config.

**Comment by JacksonKearl** [comment] 2021-02-16 17:26
Bot works by closing issues after one week of no activity if they have the `needs-more-info` label and were last commented on by a team(+) member.

**Comment by IllusionMH** [comment] 2021-02-16 17:34
Thanks for confirmation.
