### ISSUE TITLE
Toggle Mouse Button Editor Switching

### ISSUE THREAD

**Issue by ShadowRanger** [Microsoft/vscode#56755] opened 2018-08-19 04:11 UTC
I already made a feature request for this however I don't think I described what I was saying properly and as a result gave out the wrong meaning of what I said.

In Visual Studio Code, mouse button 4 and 5 switch between open editors, which can be an issue for people who use these buttons for other reasons. The ability to toggle this feature would be extremely helpful.

According to this issue https://github.com/Microsoft/vscode/issues/8641 these buttons are bindable in Windows at least.

This may also be helpful: https://github.com/jostrander/mouse-forward-back

**Comment by sandy081** [comment] 2018-08-20 06:59
@ShadowRanger Is not this a duplicate of #56627?

**Comment by ShadowRanger** [comment] 2018-08-20 07:33
@sandy081 As I said, I did already make one for this however I don't believe I provided the correct information and I also received no response on it either so I thought I would make a new one with more clarification on the request.

**Comment by sandy081** [comment] 2018-08-20 08:09
I do not think it will be helpful if you create a duplicate. Moreover you might loose the context or any discussion that already happened. I would recommend to continue discussion in the original issue.

**Closed** 2018-08-20 08:09 UTC
Labels: *duplicate, needs more info
