### ISSUE TITLE
The programe can not run !

### ISSUE THREAD

**Issue by GitSoftwareNow** [Microsoft/vscode#39028] opened 2017-11-23 11:56 UTC
when I download vscode in offficial website and run in console but the console says ./code: symbol lookup error: ./code: undefined symbol: g_bytes_unrefce
my glib version is 2.0 os is centos6.5

**Comment by maxibanki** [comment] 2017-11-23 12:52
Duplicate of #23232.
As @Tylor said:
> We don't support < RHEL7 and its derivatives as per the el7 in the filename and this page https://code.visualstudio.com/docs/supporting/requirements#_platforms

**Comment by joaomoreno** [comment] 2017-11-23 21:48
Thanks @maxibanki

**Closed** 2017-11-23 21:49 UTC
Labels: *duplicate
