### ISSUE TITLE
Global variable `name` is marked deprecated

### ISSUE THREAD

**Issue by humphd** [microsoft/vscode#114725] opened 2021-01-21 21:27 UTC
- Version: 1.52.1
- Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- Date: 2020-12-16T16:30:02.420Z (1 mo ago)
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Create a new JavaScript file
2. Add a variable `name`, for example: `let name = 'foo';`
3. Try using the `name` variable, for example: `console.log(name);`

<img width="389" alt="Screen Shot 2021-01-21 at 4 14 11 PM" src="https://user-images.githubusercontent.com/427398/105413272-e1547d00-5c03-11eb-9a89-4fbb7add6fe3.png">

Does this issue occur when all extensions are disabled?: No

I suspect this is an eslint bug, or bug in the vscode-eslint extension, not distinguishing between a user-defined `name` variable and the global.  But I'm not sure where to file it other than here.

**Comment by IllusionMH** [comment] 2021-01-21 22:13
This is "intended" TS behavior for global `name` until there is beter solution.
See https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/883 and linked issue

**Comment by mjbvz** [comment] 2021-01-21 22:47
Yep, duplicate of microsoft/TypeScript#18433

**Closed by mjbvz** 2021-01-21 22:47 UTC

**Comment by thw0rted** [comment] 2021-01-22 15:27
Maybe I misunderstand the scope here? The issue says they're declaring a locally-scoped `name` variable, but the warning is being shown because of the globally scoped `window.name`.  Right?  Shouldn't `let name` shadow out the `name` that comes from `window` or `globalThis` or whatever?

**Comment by IllusionMH** [comment] 2021-01-25 12:40
If you are talking about JS runtime - yes.
In JS/TS there will be no problems with `name` in case when you have module scope (file has `import` or `export`). Or if it's not script that will be executed in browser - make sure that `dom` is excluded form `lib` compiler options.

For global scope it becomes tricky especially for `name` that intentionally declared to prevent usage.
Conflict with `let` looks like design limitation and/or intended behavior (because in TS you'll get "Cannot redeclare block-scoped variable 'name'." error on `let name`) until there is better solution.

I don't think that this case can be fixed in VS Code so it's better to check existing issues in TS repo or rise new one there.

**Comment by JacksonFagundes2007** [comment] 2021-02-23 00:31
Hi! I know how to solve this error ... If I don't, I don't know what to do.

In my case the problem happened because the "[Discord Rich Presence](https://marketplace.visualstudio.com/items?itemName=LeonardSSH.vscord)" extension is down ... Try disabling it.
<img width="500px" src="https://cdn.discordapp.com/attachments/811651647956189244/813567817442000916/Captura_de_tela_2021-02-22_212720.png">
result:
<img src="https://cdn.discordapp.com/attachments/811651647956189244/813568579672080424/Captura_de_tela_2021-02-22_213054.png">
