### ISSUE TITLE
Issue when doing right click.

### ISSUE THREAD

**Issue by daniel-vera-g** [Microsoft/vscode#58959] opened 2018-09-19 13:41 UTC
When doing a right click the right click menu flashes very fast.

- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Have extensions that create menu points when doing right click.
2. Do right click on a word.

* Video: https://www.useloom.com/share/dde0c11b404544b6a4e5b91bdaba1550

Does this issue occur when all extensions are disabled?: No, but after testing a bit I assume that it's not because of an special extension but rather because extensions put menu points in the right click menu and when the amount is to high the issue occurs.

Currently the issue only happens in javascript files.

**Comment by sbatten** [comment] 2018-09-21 17:46
duplicate of #57399

**Closed by sbatten** 2018-09-21 17:46 UTC
Labels: workbench-menu
