### ISSUE TITLE
OSX 10.15 WindowServer high cpu load showing ProgressBar

### ISSUE THREAD

**Issue by fnicastri** [microsoft/vscode#97900] opened 2020-05-15 10:56 UTC
Really high CPU load of the WindowServer process on OSX during the use of the dart-code extension.
I have tracked it down to the displayed progress bar.
When a notification with the progress bar is shown WindowServer CPU usage go between 50% and 80%.
Stopping the task it drop to the usual sub 10% value.

I could see a similar behaviour with other extensions.

Possible duclicate of https://github.com/microsoft/vscode/issues/83991.
But that issue is closed and the problem is still present.

- VSCode Version: 1.46.0-insider
- OS Version: MacOS X 10.15.4

Steps to Reproduce:

1. Launch a command that show a ProgressBar
2. look at cpu usage of WindowServer
3. stop the task

**Comment by bpasero** [comment] 2020-05-18 07:23
This seems very similar to https://github.com/microsoft/vscode/pull/96096 (@evangrayk @joaomoreno fyi) and I wonder if using the `steps` trick helps here too. 

@fnicastri since this is very likely browser reproducible, can you try to:
* open https://jsfiddle.net/
* paste the code [1] for HTML and [2] for CSS
* run it
* monitor the CPU usage

[1] HTML

```html
<div class="monaco-progress-container infinite">
  <div class="progress-bit">
  
  </div>
</div>
```

[2] CSS

```css
.monaco-progress-container {
	width: 100%;
	height: 5px;
	overflow: hidden; /* keep progress bit in bounds */
  background-color: red;
}

.monaco-progress-container .progress-bit {
	width: 2%;
	height: 5px;
	position: absolute;
	left: 0;
}

.monaco-progress-container.infinite .progress-bit {
	animation-name: progress;
	animation-duration: 4s;
	animation-iteration-count: infinite;
	animation-timing-function: linear;
	transform: translate3d(0px, 0px, 0px);
  background-color: blue;
}

/**
 * The progress bit has a width: 2% (1/50) of the parent container. The animation moves it from 0% to 100% of
 * that container. Since translateX is relative to the progress bit size, we have to multiple it with
 * its relative size to the parent container:
 *  50%: 50 * 50 = 2500%
 * 100%: 50 * 100 - 50 (do not overflow): 4950%
 */
@keyframes progress { from { transform: translateX(0%) scaleX(1) } 50% { transform: translateX(2500%) scaleX(3) } to { transform: translateX(4950%) scaleX(1) } }
```

**Comment by fnicastri** [comment] 2020-05-20 09:43
@bpasero 
I tried.
The effect is similar but the CPU usage of WindowServer is much lower than vscode.
It spikes  just over 30%, so much less than VSCode.

**Comment by bpasero** [comment] 2020-05-20 10:14
This seems machine dependent, for me it spikes only at around 15% in Electron. What hardware is this?

**Comment by fnicastri** [comment] 2020-05-21 08:08
@bpasero 
For sure is machine dependent, this is a mac mini (2x2.6GHz, 16 GB), not the most powerful Mac.
But the behavior of the progressbar of Code is anyway abnormal.

I tried the fiddle in Safari too and the cpu usage is lower than chrome, something that not surprise me at all.

**Comment by bpasero** [comment] 2020-05-22 17:01
@fnicastri is it any better with our exploration builds using a newer Electron (and thus Chrome) version: https://az764295.vo.msecnd.net/exploration/46220344f3ad11ca25cde7c95c5f1be5c3fe71ff/VSCode-darwin-exploration.zip

**Comment by fnicastri** [comment] 2020-05-23 08:33
@bpasero No, it's the same.

To test it I just installed the Dart extension so basically it was a clean environment.
If you know a lighter extension that will show the progress bar let me know, I'll test with it.

I did another test: try to hide (cmd-h) Code's window during the build and you'll see that WindowServer's cpu usage drop to normal levels.

Anyway I'm usually on the Insider channel and the Electron and Chrome versions are the same as the Exploration you linked.

![Screen Shot 2020-05-23 at 10 19 08 AM](https://user-images.githubusercontent.com/5978520/82725780-b239e480-9cdf-11ea-9f43-ebeefc8c5749.png)

**Comment by bpasero** [comment] 2020-05-24 07:27
@fnicastri are you willing to conduct a little experiment running VSCode out of sources with modifications how the progress bar animation to see if that reduces the CPU overhead? Instructions are here: https://github.com/microsoft/vscode/wiki/How-to-Contribute

Alternatively we can try to patch the built CSS of VSCode, but that file will be hard to edit because it is minified into a single line.

**Comment by fnicastri** [comment] 2020-05-24 07:52
@bpasero not much time these days but I give it a try,
tell me what I have to do other than cloning a building code from sources

**Comment by fnicastri** [comment] 2020-05-24 08:10
@bpasero I start to think that the issue is present not just with the progressbar but with the statusbar spinner too
![image](https://user-images.githubusercontent.com/5978520/82749005-8cc3de00-9da6-11ea-874a-b46bd49d4fde.png)

WindowServer cpu usage is high with that component too and hiding vs code window make it go back as well.

**Comment by bpasero** [comment] 2020-05-24 14:03
@fnicastri if you look at https://github.com/microsoft/vscode/pull/96096 you can see how a fix went in to our insiders build. On what commit (check in about dialog) do you still see high CPU from that animation?

**Comment by fnicastri** [comment] 2020-05-24 17:27
> @fnicastri if you look at #96096 you can see how a fix (or workaround via CSS) went in to our insiders build. On what commit (check in about dialog) do you still see high CPU from that animation?

Commit: 2591ede95a52400d5d22989b16706f9b8b4831da as prevous screenshot

**Comment by fnicastri** [comment] 2020-05-26 10:52
@bpasero 
Sorry but I have not enough time these days.
If you can point me to some quick test I can do them but right now I can't spend much time in
building code and understand how to make a new extension to test the animations...

Let me know

**Comment by bpasero** [comment] 2020-05-26 11:33
@fnicastri well actually given you see high CPU spikes also from the status bar animation where we actually pushed a fix to throttle the animation I am not having a lot of hopes that we can resolve the progress bar CPU spin with the same approach. I am not having a lot of ideas left how to resolve this in VSCode itself....

**Comment by bpasero** [comment] 2020-05-26 15:16
@fnicastri something easy to try out would be this:
* install Electron Fiddle https://electronjs.org/fiddle
* pick a recent Electron version (I picked `8.2.3`)
* for `HTML` enter the code in [1]
* run
* monitor your CPU consumption

[1] HTML

```html
<style>
.monaco-progress-container {
	width: 100%;
	height: 5px;
	overflow: hidden; /* keep progress bit in bounds */
  background-color: red;
}

.monaco-progress-container .progress-bit {
	width: 2%;
	height: 5px;
	position: absolute;
	left: 0;
}

.monaco-progress-container.infinite .progress-bit {
	animation-name: progress;
	animation-duration: 4s;
	animation-iteration-count: infinite;
	animation-timing-function: linear;
	transform: translate3d(0px, 0px, 0px);
  background-color: blue;
}

/**
 * The progress bit has a width: 2% (1/50) of the parent container. The animation moves it from 0% to 100% of
 * that container. Since translateX is relative to the progress bit size, we have to multiple it with
 * its relative size to the parent container:
 *  50%: 50 * 50 = 2500%
 * 100%: 50 * 100 - 50 (do not overflow): 4950%
 */
@keyframes progress { from { transform: translateX(0%) scaleX(1) } 50% { transform: translateX(2500%) scaleX(3) } to { transform: translateX(4950%) scaleX(1) } }
  </style>

<div class="monaco-progress-container infinite">
  <div class="progress-bit">
  
  </div>
</div>
```

**Comment by fnicastri** [comment] 2020-05-27 18:19
@bpasero 
Done. Same as Code.
Before running the fiddle WindowsServer was between 5 and 10%.
With the electron window running is always over  54% with peaks up to 75 %.
Hiding Electron window (cmd-h or just putting another window on top of it) brings WindowServer's cpu back to normal values.

Electron 8.3.0 (the one that comes with the fiddle)
![image](https://user-images.githubusercontent.com/5978520/83057002-98d5c700-a056-11ea-91c2-cb3a4ae07100.png)

With Electron 9 the consumption is lower, between 45 and 55%.

**Comment by fnicastri** [comment] 2020-05-27 18:52
With this little mod the consumption is much better `  animation: progress 4s steps(40) infinite;`
For sure the animation is a bit less fluid but is not bad IMO.

CPU is around 20% os even less with very few peaks around 30% 

```HTML
<style>
.monaco-progress-container {
	width: 100%;
	height: 5px;
	overflow: hidden; /* keep progress bit in bounds */
  background-color: red;
}

.monaco-progress-container .progress-bit {
	width: 2%;
	height: 5px;
	position: absolute;
	left: 0;
}

.monaco-progress-container.infinite .progress-bit {
	/* animation-name: progress;
	animation-duration: 4s;
	animation-iteration-count: infinite;
	animation-timing-function: linear; */
	transform: translate3d(0px, 0px, 0px);
  background-color: blue;
  animation: progress 4s steps(40) infinite ; 
}

/**
 * The progress bit has a width: 2% (1/50) of the parent container. The animation moves it from 0% to 100% of
 * that container. Since translateX is relative to the progress bit size, we have to multiple it with
 * its relative size to the parent container:
 *  50%: 50 * 50 = 2500%
 * 100%: 50 * 100 - 50 (do not overflow): 4950%
 */
@keyframes progress { 
    from { transform: translateX(0%) scaleX(1) } 
    50% { transform: translateX(2500%) scaleX(3) } 
    to { transform: translateX(4950%) scaleX(1) } 
  }
  </style>

<div class="monaco-progress-container infinite">
  <div class="progress-bit">
  
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/5978520/83060590-fa4c6480-a05b-11ea-82df-6e42de63c2fb.png)

**Comment by bpasero** [comment] 2020-05-28 05:24
@fnicastri thanks a lot for trying this. how about a higher `steps` value to get it fluid, does that still reduce CPU? E.g. `60`, `80` or even `100`?

**Comment by fnicastri** [comment] 2020-05-28 07:45
@bpasero 
I tried with a 300 x 100 window to simulate more the conditions of the progress bar.
You are right, 40 could be too low, 60 is still very conservative for the cpu. 80 or 100 are more expensive but still much better than the current situation.

**Comment by bpasero** [comment] 2020-05-28 08:35
@fnicastri that sounds like we could try a solution that still results in smooth animation but reduces the CPU pressure. What number works best for you in terms of CPU but smooth animations?

**Comment by fnicastri** [comment] 2020-05-28 18:28
@bpasero 
Hi Benjamin, thanks a lot for the time you are spending in this.

I would stick with 60 or 80, not more.
I think that 60 is already smooth enough cause the progress bit is changing size too so it mask the non perfect smooth animation.

**Comment by bpasero** [comment] 2020-05-29 07:41
@fnicastri I found anything below `steps(120)` to look bad on my MBP display, especially in the editor area where the progress bar almost spans the entire width of the editor. How does CPU look like with `steps(120)` for you?

**Comment by fnicastri** [comment] 2020-05-29 09:33
@bpasero 
120 steps are too much on my machine, imo, but I'm not using Retina displays so probably the result is less hugly with 60 steps.
In any case this solution with 120 steps is already less cpu intense than the current animation!

A solution could be to change the step value when a HiDPI display is used and when the progressbar is displayed in the full editor window or in the small progress popup.

I think this could be a good solution because, usually, when the progress animation is displayed in the editor window it is just for a short time, so it would not be a big problem.

In my experience the problem is that Code show the small popup while building projects and we already have two compilers working (dart and Java or Xcode in my case) and wasting all that CPU for an animation is a very bad deal.

**Comment by bpasero** [comment] 2020-05-29 12:27
@fnicastri yeah that is a good point, maybe we only change this for notifications that potentially can show for a very long time, while in the other places I do not think they would show as long and often.

Curious, what kind of notification is this. Is an extension bringing up a notification, and why?

**Comment by fnicastri** [comment] 2020-05-29 14:42
@bpasero Dartcode, an extension for Dart and Flutter.
Basically, when compiling the project, it shows the progress popup.
![image](https://user-images.githubusercontent.com/5978520/83272174-2508fb00-a1cb-11ea-8c44-2136b799e165.png)

**Comment by bpasero** [comment] 2020-05-29 15:06
@DanTup is that an extension you or someone you know owns? Why is this a notification and not `ProgressLocation.Window` which would put it into the status bar?

**Comment by bpasero** [comment] 2020-05-30 06:39
@DanTup yes, status progress indications will now show as "hidden" notifications, meaning that when you click the status bar it will show the notification. I would prefer if extensions would use the more lightweight status progress reporting over notifications, but of course that is up to extensions.

The issue here is a performance issue that I still want to look into, but I am also interested in extensions using as little notifications as possible.

**Comment by bpasero** [comment] 2020-06-01 06:34
With https://github.com/microsoft/vscode/commit/06524e63d00a7af0a1a71af7113432687d6fc7fb there is now the following rule to add `steps` only on macOS native for low DPI screens:

https://github.com/microsoft/vscode/blob/06524e63d00a7af0a1a71af7113432687d6fc7fb/src/vs/workbench/browser/parts/notifications/media/notificationsList.css#L125-L135

**Closed** 2020-06-01 06:34 UTC
Labels: mac, perf

**Comment by fnicastri** [comment] 2020-06-01 06:59
@bpasero Thank you!

**Comment by DanTup** [comment] 2020-06-01 09:19
@bpasero 

> I would prefer if extensions would use the more lightweight status progress reporting over notifications

It would be good to have some general guidelines about this - the API docs are pretty light on what each should be used for so we just have to make judgement calls (which may also lead to inconsistencies across languages).

I used this one here mainly because it's a potentially very slow step and one the user is specifically waiting for (this is them launching an app, not just some background task the extension is doing). I wanted to make sure it was obvious what was going on.
