### ISSUE TITLE
Allow to autocomplete html inline style on a file other than html.

### ISSUE THREAD

**Issue by Fr3027** [microsoft/vscode#84133] opened 2019-11-07 13:34 UTC
I want to use vscode built-in html inline style autocomplete in wxml file, which  is similar to html, but i can't find a way to do this .I know i can do :
`  "files.associations": {
        "*.wxml": "html"
    },` .
But if i do this, then i can't use wxml file extensions, so , can you add a feature to do this better? 
Thank you.

**Comment by aeschli** [comment] 2019-11-07 15:03
There's currently no better way. 
The best way would be someone writes a real wxml language server that uses our html-language-service as backend.  
But we are thinking of a good way to make the HTML support available for HTML-like languages: https://github.com/microsoft/vscode/issues/49210

Do you have a pointer to more information about wxml?

**Comment by octref** [comment] 2019-11-07 16:30
wxml takes inspiration from Vue Single File Component:
https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/

Duplicate of #49210. There's currently no way to easily "inherit" HTML features. The best you can do is to fork the HTML Language Server for your file type: https://github.com/microsoft/vscode/tree/master/extensions/html-language-features

**Closed by octref** 2019-11-07 16:30 UTC
