### ISSUE TITLE
With hungarian layout '\' cannot be entered to the the nested terminal

### ISSUE THREAD

**Issue by kodfodrasz** [Microsoft/vscode#7957] opened 2016-06-22 06:47 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 10 Professional versin 1511 build 10586.420

Steps to Reproduce:

1. Start VSCode
2. Press the Ctrl+ö keys, which toogle the terminal (why not Ctrl+0, the key placed to the same position as Ctrl+` on the US layout?
3. Press AltGr+q to input '\' on hungarian layout

Expected result:
Terminal opens with cmd.exe, and \ appears in the terminal.

Actual result:
Terminal opens with cmd.exe and q appears in the terminal.

**Comment by Tyriar** [comment] 2016-06-22 09:18
Duplicate of https://github.com/Microsoft/vscode/issues/7061

**Closed by Tyriar** 2016-06-22 09:18 UTC
Labels: bug, integrated-terminal
