### ISSUE TITLE
no format on paste/save on v 1.50.0

### ISSUE THREAD

**Issue by BernardA** [microsoft/vscode#108365] opened 2020-10-09 07:45 UTC
- VSCode Version: 1.50.0
- OS Version:Mas 10.15.7

Steps to Reproduce:

1. save or paste unformatted code

Does this issue occur when all extensions are disabled?: Yes/No Not applicable as the issue is related to extensions ESLint or Prettier

This was working properly prior to latest update. Both ESLint and Prettier are shown as active 

Note that is does show the errors as you can see on the enclosed image.

This is eslinrc.json

       {
    "env": {
        "browser": true,
        "es2020": true
    },
    "extends": [
        //"plugin:react/recommended",
        "airbnb",
        // "prettier",
        "plugin:prettier/recommended",
        "prettier/react"
    ],
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 11,
        "sourceType": "module"
    },
    "plugins": ["react", "react-hooks", "jsx-a11y", "import", "prettier"],
    "rules": {
         ......
        "no-unused-expressions": [
            "error",
            {
                "allowShortCircuit": true
            }
        ],
        "quotes": [
            2,
            "single",
            {
                "avoidEscape": true,
                "allowTemplateLiterals": true
            }
        ]
    },
    "globals": {
        "React": "writable"
    }
    }

And prettier.rc

     {
    "singleQuote": true,
    "trailingComma": "all",
    "tabWidth": 4,
    "printWidth": 90
    }

![Screenshot 2020-10-09 at 09 43 38](https://user-images.githubusercontent.com/9449665/95556730-08e85680-0a14-11eb-8342-6cc37604e547.png)

**Comment by devJang** [comment] 2020-10-09 07:53
I get the same issue

**Comment by RanSatious** [comment] 2020-10-09 08:17
got the same issue
resolved by adding `"editor.defaultFormatter": "esbenp.prettier-vscode"` to `settings.json`

**Comment by uglyraptor** [comment] 2020-10-09 08:54
same problem since updating vscode, RanSatious solution worked for me!

**Comment by cyntl3r** [comment] 2020-10-09 10:21
> got the same issue
> resolved by adding `"editor.defaultFormatter": "esbenp.prettier-vscode"` to `settings.json`

Thanks! It works fine.

**Comment by YoannBuzenet** [comment] 2020-10-09 12:06
It works thank you. But some autoformat cases that used to be formatted automatically are now just underlined by eslint. Do I have to update settings in .prettierrc too ? Or somewhere else ?

**Comment by ZnK88** [comment] 2020-10-09 14:10
Bonjour,

Meme soucis sur la 1.50 c'est possible de le fix avec cette manipulation indiquez plus haut
![prettier](https://user-images.githubusercontent.com/58308663/95593403-ef620180-0a49-11eb-98d8-3997af9a6600.PNG)

**Comment by nathanshanahan** [comment] 2020-10-10 00:52
> got the same issue
> resolved by adding `"editor.defaultFormatter": "esbenp.prettier-vscode"` to `settings.json`

This solution only solved the problem temporarily for me, on subsequent reload I'm seeing the failure to format issue resurface even though editor.defaultFormatter is set to esbenp.prettier-vscode.

**Comment by pabloluz** [comment] 2020-10-10 12:26
I was running into the same issue. I can confirm @RanSatious and @ZnK88 solutions together worked like a charm.

**Comment by jrieken** [comment] 2020-10-15 09:12
Maybe the same as https://github.com/microsoft/vscode/issues/108447

**Comment by BernardA** [comment] 2020-10-19 11:52
adding `"editor.defaultFormatter": "esbenp.prettier-vscode"` to settings.json seems to have resolved the format on save issue. 
Format on paste still does not work though. 

Note that in previous versions, `"editor.defaultFormatter"` was set to `null` and both format on save and paste worked fine.

**Comment by nathanshanahan** [comment] 2020-10-19 12:01
Was having issue with SCSS and JS files formatting but was not having the same luck with PHP files being ignored. 

Solution for me was to remove the previous settings I had assigned in settings.json and reset by making the same selections through the newer settings interface.

**Comment by jrieken** [comment] 2020-10-20 07:06
/duplicate of https://github.com/microsoft/vscode/issues/108447

**Closed** 2020-10-20 07:06 UTC
Labels: *duplicate, formatting, needs more info
