### ISSUE TITLE
Emmet in vscode works too slowly.

### ISSUE THREAD

**Issue by seasofttongkhanh** [microsoft/vscode#110577] opened 2020-11-13 14:14 UTC
For a 5000 line HTML fragment it seems that emmet does not work as well as other editors.

When I use balance (outward), remove tags, etc. It takes up to 3 - 4s to complete one task.

This I have experimented with without any extensions at all.

* VSCode Version: 1.51.0
* OS: Windows 10 1809 build and Xubuntu 20.04.

**Comment by rzhao271** [comment] 2020-11-13 15:52
Duplicate of #83423

**Comment by rzhao271** [comment] 2020-12-17 00:26
Un-duplicating to use this issue as a general placeholder for perf upgrades.

**Closed** 2020-12-30 19:00 UTC
Labels: bug, debt, emmet, perf
