### ISSUE TITLE
syntax hightlighting

### ISSUE THREAD

**Issue by riojudeen** [microsoft/vscode#123334] opened 2021-05-07 23:17 UTC
why i can not get syntax highlight after update?

**Comment by Ri-Dearg** [comment] 2021-05-11 11:07
I'm suffering from a similar issue since the update.
Python interpreter has stopped highlighting syntax since its update. I was previously using python and pylance easily, now since it's integration into the main extension and update I have no syntax highlighting. I have tried uninstalling and reinstalling the extensions. Nothing is working.
Javascript is also not functional anymore. HTML is the only one that functions.
Mac OS Mojave 10.14.6

**Comment by andreabradpitto** [comment] 2021-06-13 15:19
I have the same issue with Python (Python extension + Pylance as default) on ubuntu after the update to vscode 1.57, but not with C, which seems to be ok.

I updated to 1.57 in Windows 10 too, and here everything works fine, i.e. the syntax highlighting is still the same as before.

I am suing the default Dark+ theme.

**Comment by JacksonKearl** [comment] 2021-06-17 17:52
Hey sorry you're having this problem. Does it still reproduce in the latest VS Code stable (1.57.0)?

**Comment by andreabradpitto** [comment] 2021-06-17 18:01
I had this issue too, and it got solved via Python extension update recently (I am not in the insiders channel of that extension)

**Comment by JacksonKearl** [comment] 2021-06-17 18:08
Thanks for the feedback, I'll close this out as it seems to have been fixed by an extension update.

**Closed by JacksonKearl** 2021-06-17 18:08 UTC
Labels: needs more info
