### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by CqLouisLiu** [Microsoft/vscode#25204] opened 2017-04-23 06:27 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|beautify|HookyQR|1.0.2|
|vscode-great-icons|emmanuelbeziat|1.1.52|
|cpptools|ms-vscode|0.10.5|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---

Steps to Reproduce:

1.When I use template in C++ like <img width="248" alt="qq20170423-152948 2x" src="https://cloud.githubusercontent.com/assets/24524721/25311348/ba137a5e-2839-11e7-90db-bb6a2da8d2eb.png"> in VSCode, there is a red line appear in the editor, I know the grammar in C++ Standard 98 need a space between consecutive right angle brackets (use '> >'), but after C++ standard 11, this grammar is not needed like before. 
2.I like VSCode very much, thank you!
<img width="435" alt="7f8cfc9c-4713-40a2-b2fe-5148e4f571e0" src="https://cloud.githubusercontent.com/assets/24524721/25311327/f24f7ef0-2838-11e7-9477-cc22724cb980.png">

**Comment by mjbvz** [comment] 2017-04-24 05:44
I don't think that VSCode generates any errors for c++ out of the box so I suspect one of your extensions is causing this. Can you try running code with the `--disable-extensions` command line flag to check this. The error itself may also have information about its source

**Comment by sean-mcmanus** [comment] 2017-04-27 13:12
@CqLouisLiu Our cpptools extension recently added error squiggles, but I'm not able to repro the error shown in the screenshot. What does the text of the error say when you hove over or view it in the Problems window.

**Comment by sean-mcmanus** [comment] 2017-04-27 13:13
@CqLouisLiu Oops, ignore my previous comment. It shows you're using 0.10.5, which didn't have error squiggles, so it must be another extension causing it.

**Comment by mjbvz** [comment] 2017-05-01 19:54
Closing as likely caused by extension

**Closed by mjbvz** 2017-05-01 19:54 UTC
Labels: needs more info
