### ISSUE TITLE
Context menu for 'non-admin' users

### ISSUE THREAD

**Issue by teuna** [Microsoft/vscode#510] opened 2015-11-23 18:42 UTC
I'm running VSCode in a corporate network (Active Directory), when I install VSCode I'm asked for an admin password, after the installation normal users sessions don't have the VSCode context menu options, only the admin account has that menu.

How can I add the context menu for all users?

**Comment by joaomoreno** [comment] 2015-11-24 09:48
Duplicate of #534

**Closed by joaomoreno** 2015-11-24 09:48 UTC
