### ISSUE TITLE
Double 'l' showing problem

### ISSUE THREAD

**Issue by haifenghuang** [microsoft/vscode#115279] opened 2021-01-28 02:45 UTC
Issue Type: <b>Bug</b>

Two 'l' character is not show correctly. for example, when I type 'channelloop', the two 'l'  look very weird. When I remove one 'l', It shows correctly.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.93GB (0.55GB free)|
|Process Argv|C:\\work\\mycontroller --crash-reporter-id 70ddb8f7-0c8f-4b67-a327-7ae146987cba|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-vlang|0x9|0.1.2
vscode-openapi|42C|3.10.0
gitdiffer|aag|0.0.3
numbered-bookmarks|ale|7.3.0
primer-light|and|0.0.6
swagger-viewer|Arj|3.0.1
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.3
vscode-django|bat|1.2.0
vscode-perl|cfg|1.18.0
vscode-astyle|chi|0.9.0
bracket-select|chu|2.0.2
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.1.0
vscode-office|cwe|1.9.1
make-hidden|dev|3.0.3
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
gitlens|eam|11.1.3
tslint|eg2|1.0.44
vscode-statusbar-debugger|fab|2.0.6
go|gol|0.22.0
gc-excelviewer|Gra|3.0.40
perl-outline|hit|0.0.6
rest-client|hum|0.24.4
mysql-syntax|jak|1.3.1
swift|Kas|0.2.0
kite|kit|0.136.0
nim|kos|0.6.6
vs-color-picker|lih|1.0.0
remotefs|lix|0.0.16
lzwme-eye-care|lzw|1.0.2
MagicPython|mag|1.1.0
copy-code-block|Mat|0.0.7
mp|mag|0.0.1
csharp|ms-|1.23.8
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.3
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0-insiders3
gradle-language|nac|0.2.3
peep|nwa|0.0.5
material-icon-theme|PKi|4.5.0
java|red|0.74.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.14.0
vscode-gradle|ric|3.5.2
highlight-words|rsb|0.1.4
yo|sam|0.9.3
perltidy|sfo|1.3.2
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
shell-launcher|Tyr|0.4.1
cscs-debugger|vas|0.7.2
vscodeintellicode|Vis|1.2.10
extension|vla|0.1.3
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
debug|web|0.25.0
jinja|who|0.0.8
markdown-pdf|yza|1.4.4

(23 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by IllusionMH** [comment] 2021-01-28 10:36
/needsMoreInfo

What font are you using? Most likely it's forn that supports [ligatures](https://en.wikipedia.org/wiki/Orthographic_ligature)
In this case `"editor.fontLigatures": false` should disable them for editor, for terminal you would need to set font without ligatures.

**Comment by haifenghuang** [comment] 2021-01-28 13:51
my editor font  is `Source Code Pro Semibold`。Below is the image Which shows the problem:
![image](https://user-images.githubusercontent.com/4425219/106147310-ae395d00-61b2-11eb-9ba0-f86af238ca9b.png)

But when I change the font to `Consolas`, It shows as expected. Maybe it's the font problem which I use.

**Comment by IllusionMH** [comment] 2021-01-28 15:03
/duplicate of #106583

See https://github.com/microsoft/vscode/issues/106583#issuecomment-694121145 for more details and one of possible workarounds

**Closed** 2021-01-28 15:03 UTC
Labels: *duplicate, needs more info
