### ISSUE TITLE
auto-update not working on mac

### ISSUE THREAD

**Issue by jtourlamain** [Microsoft/vscode#9151] opened 2016-07-12 18:20 UTC
- VSCode Version: 1.2.1 tried to update to 1.3.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

I'm not working as a root user. Each time the app asks me to download/install the update, it seems to work, but when the app is restarted, I get the old version. After a while the app asks again to update.
I always need to download the new version manually from the site and install it.

**Comment by joaomoreno** [comment] 2016-07-13 05:58
Does root own the `Applications` folder?

**Comment by jtourlamain** [comment] 2016-07-13 07:37
On the Applications folder the owner is root, the group is admin. But vscode is actually under /Applications/Tools. That folder is owned by myroot (an admin user) and group admin

**Comment by joaomoreno** [comment] 2016-07-13 08:04
And what's the user you are logged in as?

Does it reproduce after a system reboot?

Do you see any error messages in the `Console` OS X app?

**Comment by jtourlamain** [comment] 2016-07-13 09:07
after a reboot I still have the same problem.
There are however errors in the console:

13/07/16 11:03:02,490 ShipIt[614]: Couldn't abort install and restore owned bundle to previous location file:///Applications/Tools/Visual%20Studio%20Code.app, error NSError { domain: NSPOSIXErrorDomain, code: 2, description: "No such file or directory" }
13/07/16 11:03:04,267 ShipIt[614]: Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
13/07/16 11:03:04,267 ShipIt[614]: ShipIt quitting
13/07/16 11:03:04,295 ShipIt[619]: Resuming installation attempt 2
13/07/16 11:03:04,309 ShipIt[619]: Couldn't abort install and restore owned bundle to previous location file:///Applications/Tools/Visual%20Studio%20Code.app, error NSError { domain: NSPOSIXErrorDomain, code: 2, description: "No such file or directory" }

then after some attempts:

13/07/16 11:03:10,103 ShipIt[621]: Too many attempts to install, aborting update
13/07/16 11:03:10,105 ShipIt[621]: Error aborting installation: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSLocalizedDescription=No such file or directory}
13/07/16 11:03:10,140 ShipIt[621]: Application launched at file:///Applications/Tools/Visual%20Studio%20Code.app
13/07/16 11:03:10,140 ShipIt[621]: ShipIt quitting

**Comment by joaomoreno** [comment] 2016-07-13 10:27
Closing as duplicate of #3520

**Closed by joaomoreno** 2016-07-13 10:27 UTC
Labels: needs more info
