### ISSUE TITLE
Go to Symbol in Workspace includes symbols from excluded files and folders

### ISSUE THREAD

**Issue by eclazi** [microsoft/vscode#169305] opened 2022-12-15 18:53 UTC
Type: <b>Bug</b>

1. Create new folder, `test`
2. Create `test\main.py`
4. Create `test\exclude\exclude.py`
5. Add `exclude` to files / folders to exclude
6. Use Go to Symbol in workspace and search for a symbol in `exclude.py`, symbol appears in results.

Expect that symbols are not indexed in excluded files and folders.

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)

Also tested in 1.75.1-insiders

OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (20.46GB free)|
|Process Argv|C:\\src\\test folder|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.63.7601
go|gol|0.36.0
vscode-catch2-test-adapter|mat|4.3.7
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.7
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2022.11.0
fastbuild|Ros|1.0.0
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2022-12-15 19:28
Duplicate of #46718

**Closed by mjbvz** 2022-12-15 19:28 UTC

**Comment by eclazi** [comment] 2022-12-16 00:12
I was trying to follow the thread in #46718. It seems as this is supposed to be resolved - https://github.com/microsoft/vscode/issues/46718#issuecomment-599397590

Or am I misunderstanding?

**Comment by eclazi** [comment] 2022-12-19 21:54
@mjbvz Just following up on my question above

**Comment by eclazi** [comment] 2023-01-26 22:25
@mjbvz hello, following up on this again

**Comment by eclazi** [comment] 2023-01-27 18:48
@lramos15 wonder if you can help. Let me know the best way forward.
