### ISSUE TITLE
Activity bar overflow logic broken

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#29889] opened 2017-06-29 21:09 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|gitlens|eamodio|4.2.0|
|tslint|eg2|0.16.0|
|githd|huizhou|0.1.0|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.6|
|sourcegraph|sourcegraph|1.0.8|
|vim|vscodevim|0.9.0|;
---

![dotdotdot](https://user-images.githubusercontent.com/754768/27710389-6be82292-5cd4-11e7-8c0b-d28c11b8e392.gif)

Steps to Reproduce:

1. Resize VS Code window vertically until activity bar icons overflow.

**Comment by bpasero** [comment] 2017-06-30 04:22
I cannot reproduce from insiders where we have the new settings icon down there:

![panel-red](https://user-images.githubusercontent.com/900690/27720822-667bb7dc-5d5c-11e7-943a-b78e6717c92d.gif)

I can only imagine this is a bug that was introduced with the settings icon, so moving to @isidorn

**Comment by nicksnyder** [comment] 2017-06-30 15:42
I am observing the same behavior you are on insiders so it looks like it is partially fixed already (compared to released 1.13.1).

The current behavior still isn't ideal imo. I think as soon as the bottom element is partially obscured, it should completely disappear and the next element should be replaced with a `...`

**Comment by isidorn** [comment] 2017-07-03 06:40
@nicksnyder Closing this issue then since you can no longer repro it
For your other suggestion please file a new feature request and ping Ben or me

**Closed by isidorn** 2017-07-03 06:40 UTC
Labels: workbench
