### ISSUE TITLE
Command `typescript.sortImports` appears multiple times in the `commands` section

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164735] opened 2022-10-26 18:06 UTC
```
log.ts:312  INFO [vscode.typescript-language-features]: Command `typescript.sortImports` appears multiple times in the `commands` section.
log.ts:312  INFO [vscode.typescript-language-features]: Command `javascript.sortImports` appears multiple times in the `commands` section.
log.ts:312  INFO [vscode.typescript-language-features]: Command `typescript.removeUnusedImports` appears multiple times in the `commands` section.
log.ts:312  INFO [vscode.typescript-language-features]: Command `javascript.removeUnusedImports` appears multiple times in the `commands` section.

```

**Comment by mjbvz** [comment] 2022-10-26 18:48
Duplicate of #164688

**Closed by mjbvz** 2022-10-26 18:48 UTC
