### ISSUE TITLE
Change all occurrences works for first 1000 entries only

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#20854] opened 2017-02-18 10:34 UTC
- VSCode Version: 1.9
- OS Version: Linux

Steps to Reproduce:

1. Open a file with same word present multiple times( > 2000).
2. Select some part of word and right click -> change all occurrences. Only selects first 1000 entries.

**Comment by Bill-Stewart** [comment] 2017-02-21 17:35
Duplicate of https://github.com/Microsoft/vscode/issues/5887 ?

**Comment by alexandrudima** [comment] 2017-02-22 08:33
Yes, thanks @Bill-Stewart . Let's track in #5887

**Closed by alexandrudima** 2017-02-22 08:33 UTC
