### ISSUE TITLE
Checkbox can't choose while create profile from default or templates

### ISSUE THREAD

**Issue by StarUnderNight** [microsoft/vscode#225557] opened 2024-08-14 03:35 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Create new profile and choose template from Default, however the checkbox can't choose, and version 1.91 is normal

**Comment by gjsjohnmurray** [comment] 2024-08-14 04:31
/duplicate of #224788 which offers a workaround.

**Closed** 2024-08-14 04:31 UTC
Labels: *duplicate
