### ISSUE TITLE
Terminal does not display underscores

### ISSUE THREAD

**Issue by radustefan95** [Microsoft/vscode#40749] opened 2017-12-23 10:29 UTC
The actual file name is `test_disk_space.sh` . Makes it difficult to work with Python using the terminal as most people use `snake_case`...
![bug image](http://i.imgur.com/WnYvECN.png)

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.13.5-100.fc25.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
gitlab-ci-validator|cst|1.0.0
gitlab-ci-templates|jgs|0.3.0
python|ms-|0.9.1
vscode-todo-highlight|way|0.5.11

**Comment by usernamehw** [comment] 2017-12-23 12:22
A duplicate of https://github.com/Microsoft/vscode/issues/40084 ?

**Comment by maxibanki** [comment] 2017-12-23 21:14
Duplicate of #35901

**Closed** 2017-12-27 16:16 UTC
Labels: integrated-terminal
