### ISSUE TITLE
Suggest adding imports above changing spelling when showing quick fixes

### ISSUE THREAD

**Issue by twk** [microsoft/vscode#116004] opened 2021-02-06 23:50 UTC
Here's a good example of a problem I run into a few times a week:

![image](https://user-images.githubusercontent.com/15460/107132301-7efdac80-6892-11eb-9885-9e4ce659714d.png)

Virtually every time I'm faced with a choice between making a spelling change and adding a missing import, I want to add the missing import. I usually fix these with keystrokes and I'm always expecting the missing import to be at the top, because it usually isn't a spelling issue. So, it would be a really nice little improvement to put the missing import quick fix at the top.

**Comment by gjsjohnmurray** [comment] 2021-02-07 00:16
/duplicate of #115372

If you are able to use Insiders you should see it already fixed there, ready for next month's release.

**Closed** 2021-02-07 00:17 UTC
Labels: *duplicate

**Comment by twk** [comment] 2021-02-07 00:28
Awesome, thank you!
