### ISSUE TITLE
Save my search regular expression conditions

### ISSUE THREAD

**Issue by charlyzeng** [Microsoft/vscode#48881] opened 2018-04-28 08:45 UTC
Issue Type: <b>Feature Request</b>

Dear Developers:
Sometimes, we need search and replace some text by regular expression iteratively. However, I must reinput my regular expression after I changed my search condition.This is inconvenient, I hope I can get back my historical regular expression. For example, when I focus in "search input", there will be a dropdown that show my historical search regular expressions, so that I can select one or input a new one.

Thanks!

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 16.7.0

**Comment by yume-chan** [comment] 2018-04-28 09:17
Duplicate of #23099

Workaround: there is no any UI (dropdown) for it but you can use <kbd>Alt</kbd> + <kbd>Up Arrow</kbd>/<kbd>Down Arrow</kbd> keys to navigate your search history.

**Closed** 2018-04-28 23:24 UTC
Labels: search
