### ISSUE TITLE
single git branch related to remote not showing in checkout options

### ISSUE THREAD

**Issue by sebastian-fredriksson-bernholtz** [microsoft/vscode#113887] opened 2021-01-06 08:06 UTC
Issue Type: <b>Bug</b>

My remote branch `origin/production` is not showing when I go to checkout branches in VSCode unless I have a local tracking branch.
<img width="1552" alt="Screen Shot 2021-01-06 at 18 44 58" src="https://user-images.githubusercontent.com/14281373/103742677-542ff680-504f-11eb-8d0a-664e77cc7e5e.png">

If I checkout local tracking branches through `git checkout -b <local_branch_name> origin/production` the remote `origin/production` shows, but one of the local branches doesn't. I've played around a bit creating and deleting branches to figure out which branch doesn't show, and it seems like a local branch named `production` will never show but I'm not really sure.
![example](https://user-images.githubusercontent.com/14281373/103744484-f9e46500-5051-11eb-81aa-1075b679cf6b.gif)

Just before this happened I deleted a few local branches, including `production` via the GUI of `Git History` extension. It is possible that I might have tried to delete `origin/production` as well but I don't think I did. It is protected on remote. 

I've uninstalled and reinstalled the `Git History` extension, and deleted and recloned the repo, but still having the same issue.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id abd2cf10-ca00-44af-844d-7ad43e45f222|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.1.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
todo-tree|Gru|0.0.193
rest-client|hum|0.24.4
search-node-modules|jas|1.3.0
plantuml|jeb|2.14.1
socket-io-vscode|lit|1.0.0
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-wsl|ms-|0.52.0
vetur|oct|0.31.3
indent-rainbow|ode|7.5.0
vscode-yaml|red|0.13.0
vscode-sort-json|ric|1.19.1
create-file-folder|rit|0.0.5
code-settings-sync|Sha|3.4.3
numbermonger|sof|0.5.0
rewrap|stk|1.13.0
sort-lines|Tyr|1.9.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.335
vscode-ruby|win|0.28.0
unsaved-files-vscode|wra|2.1.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
sort-js-object-keys|zen|1.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617cf:30237717
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30236574
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30241727
vsjup459cf:30237188

```

</details>

**Comment by eamodio** [comment] 2021-01-06 08:36
Duplicate of #112481

**Closed by eamodio** 2021-01-06 08:36 UTC
