### ISSUE TITLE
Accessibility: macOS Native tabs

### ISSUE THREAD

**Issue by rcarmo** [microsoft/vscode#79920] opened 2019-08-27 14:16 UTC
Issue Type: <b>Bug</b>

I am running the latest prod build on Mojave and require native tabs to work so that I can use a macOS Accessibility extension to enumerate individual editor tabs and switch to them.

However, native tabs create separate workspaces and not individual, per-file editors. I've reviewed #76537, #77047 and other similar issues and none seem to mention accessibility requirements, but one of the points of having native Cocoa tab support is, indeed, allowing screen readers and other tools to work seamlessly on the platform.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
amvim|aui|1.30.0
spellright|ban|3.0.46
calva|bet|2.0.33
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.71
paredit-revived|cos|0.1.22
vscode-markdownlint|Dav|0.30.1
gitlens|eam|9.9.3
Kotlin|mat|1.7.0
terraform|mau|1.4.0
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-azureterraform|ms-|0.2.4
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
azure-account|ms-|0.8.4
cpptools|ms-|0.25.0
csharp|ms-|1.21.1
Go|ms-|0.11.4
azurerm-vscode-tools|msa|0.6.0
vscode-yaml|red|0.5.1
vscode-parinfer|sha|0.6.2
nativescript|Tel|0.10.1
clojure-warrior|ton|0.2.4
vscode-arduino|vsc|0.2.27

</details>

**Comment by isidorn** [comment] 2019-08-27 15:08
This looks like a duplicate of #76537
Though assigning to @deepak1556 to decide

**Comment by rcarmo** [comment] 2019-08-27 18:12
Yes, of course :) I did my homework and read through a set of similar issues. My issue is about Mojave and individual native tabs per file.

I will try those builds and report back ASAP.

**Comment by deepak1556** [comment] 2019-10-10 01:00
@rcarmo where you able to give those builds a try ?

**Comment by rcarmo** [comment] 2019-10-10 08:54
Once. The UX was not to my liking, to be honest, and the build wouldn’t load one of my extensions, so I moved on and installed Sublime on my Mac again.

**Closed** 2019-10-10 19:24 UTC
Labels: *not-reproducible
