### ISSUE TITLE
Goto Definition not working - Cannot read property getSourceFiles of undefined

### ISSUE THREAD

**Issue by dylmye** [microsoft/vscode#75991] opened 2019-06-24 08:49 UTC
Issue Type: <b>Bug</b>

Hello! Last week my ctrl+click for goto definition has stopped working. I get the following message from the Typescript output window (on verbose setting):

> [Trace  - 09:40:00] Response received: documentHighlights (4). Request took 545 ms. Success: false . Message: Error processing request. Cannot read property 'getSourceFiles' of undefined
TypeError: Cannot read property 'getSourceFiles' of undefined
    at ConfiguredProject.Project.getScriptInfos (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:126095:44)
    at ProjectService.sendProjectTelemetry (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128117:66)
    at ConfiguredProject.updateGraph (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:126726:37)
    at Object.updateProjectIfDirty (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:127081:45)
    at ConfiguredProject.Project.getLanguageService (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125915:28)
    at IOSession.Session.getDocumentHighlights (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130772:50)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130173:61)
    at c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131628:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131659:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft Visual Studio Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:132950:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)

I've tried the following:

* Restarting typescript server
* Disabling the inbuilt features extension
* Restarting the machine
* Full re-install
* Running with `--disable-extensions`

What I've not yet tried:

* Upgrading to Insiders
* Downgrading
* Cleaning the TS Server cache (does such a thing exist?)
* Copying all files over to a new folder

I'd rather not go to the hassle of changing edition unless an issue has actually been identified in this version. 

Thanks!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.800.0
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
gitlens|eam|9.8.2
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.9.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
vscode-pull-request-github|Git|0.8.0
ftp-simple|hum|0.7.0
icon-fonts|idl|2.1.5
node-module-intellisense|lei|1.5.0
gitignore|mic|1.0.1
vscode-apache|mrm|1.2.0
node-debug2|ms-|1.33.0
material-icon-theme|PKi|3.8.0
cinnamon-snippets|red|0.0.10
sass-indented|rob|1.5.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by dylmye** [comment] 2019-06-24 08:56
Related: 

* #71109 - I get past the initialising stage. I've also tried troubleshooting from this issue.
* #75430 - Followed instructions [here](https://github.com/microsoft/vscode/issues/75430#issuecomment-504584352) to provide the error output above. I'm also missing other JS features like hovertext.
* #17221 - Haven't tried [these 2016 instructions](https://github.com/microsoft/vscode/issues/17221#issuecomment-267932516) yet, are they still relevant? Issue was supposedly [fixed in 2017](https://github.com/microsoft/TypeScript/issues/13698). Below is my jsconfig.json:

```json
{
  "compilerOptions": {
    "baseUrl": "./app",
    "paths": {
      "components/*": ["./components/*"],
      "features/*": ["./features/*"],
      "modules/*": ["./modules/*"],
      "pages/*": ["./pages/*"]
    }
  },
  "exclude": ["build", "node_modules"]
}
```

**Comment by mjbvz** [comment] 2019-08-15 00:33
Possibly duplicate of https://github.com/microsoft/TypeScript/issues/32073

Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Using the latest VS Code insiders build, does that fix the issue?

**Closed** 2019-08-22 01:17 UTC
Labels: needs more info, typescript
