### ISSUE TITLE
Extensions stopped

### ISSUE THREAD

**Issue by robinbenitezmora** [microsoft/vscode#176714] opened 2023-03-10 02:55 UTC
Type: <b>Bug</b>

Every 5 minutes VS Code is bloqued for extensions, appearing the Jest and compiling suddenly

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.89GB (2.92GB free)|
|Process Argv|--crash-reporter-id 91c188a2-86e8-45bb-879f-61db2cd91e2c|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
node-essentials|afr|1.1.0
Coderslang|Agi|0.5.1
amvim|aui|1.34.0
bracket-pair-color-dlw|Bra|0.0.6
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-devtools-for-chrome|cod|0.0.7
codestream|Cod|14.16.0
bracket-pair-colorizer-2|Coe|0.2.4
dscodegpt|Dan|2.0.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.77.9225
vscode-auto-open-markdown-preview|hnw|0.0.4
import-cost|hyr|0.0.5
search-node-modules|jas|1.3.0
vscode-gutter-preview|kis|0.30.0
node-module-intellisense|lei|1.5.0
nodejs-repl|los|0.5.15
vscode-language-babel|mgm|0.0.37
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.10.4
vscode-azureresourcegroups|ms-|0.6.1
vscode-docker|ms-|1.24.0
python|ms-|2023.4.1
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
azure-account|ms-|0.11.3
remote-explorer|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5834
color-highlight|nau|2.5.0
elmmet|nec|1.0.1
vscode-for-node-js-development-pack|nod|2.0.1
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
vscode-jest|Ort|5.2.3
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
vscode-css-navigation|puc|1.13.3
vscode-thunder-client|ran|2.5.1
ruby|reb|0.28.1
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
vs-code-prettier-eslint|rve|5.0.4
code-settings-sync|Sha|3.4.3
js-jsx-snippets|sky|11.0.1
bunker|sld|1.1.6
css-auto-prefix|spo|0.1.7
vscode-stylelint|sty|1.2.4
rainbow-bracket|tal|1.0.2
ayu|tea|1.0.5
bootstrap4-vscode|the|6.1.0
vscode-plpgsql-lsp|uni|2.7.2
errorlens|use|3.7.0
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.2.0
nodejs-extension-pack|wad|0.1.9
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.8
html-css-class-completion|Zig|1.20.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
pythonb192:30669360
funwalk2cf:30682975
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:17
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:17 UTC
Labels: freeze-slow-crash-leak, extension-host
