### ISSUE TITLE
Auto attach is not working on Windows

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#46782] opened 2018-03-27 23:26 UTC
Testing #46570

On Windows 10, I am unable to see this feature working at all. I have a simple server.js file with a recursive setTimeout and am using Node v8.9.7. I use inspect and inspect-brk with no success. I can however use the UI to attach after launching from the integrated terminal.

**Comment by weinand** [comment] 2018-03-28 08:16
If you are using PowerShell then this is most likely a duplicate of https://github.com/Microsoft/vscode/issues/46704

**Comment by sbatten** [comment] 2018-03-28 20:24
@weinand I am unable to auto-attach with cmd or powershell. I can however attach manually with both. I will reopen. Please close if you feel these are the same root cause.

**Comment by weinand** [comment] 2018-03-28 21:07
- What is the commit id of the VS Code build you are using?
- what are the exact steps?
- a screencast could help too.

**Comment by sbatten** [comment] 2018-03-28 21:16
Version 1.22.0-insider
Commit 95b0cffe72a9d32e6ef3780dcc050a336e7b2968
Date 2018-03-28T05:17:37.707Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

In the below image, I have simple server.js file launched in cmd in the integrated terminal with inspect-brk and auto attach on, but we never attach.

![image](https://user-images.githubusercontent.com/6561887/38056777-4d32d0f6-3292-11e8-89ff-b929f79f7010.png)

**Comment by weinand** [comment] 2018-03-28 21:36
Cannot reproduce:

**Comment by sbatten** [comment] 2018-03-28 22:07
still no luck after a full reboot with the changes you suggested. @RMacfarlane also tried and has the same issue as me. We both can successfully attach on Mac so we believe we have the scenario correct.

**Comment by weinand** [comment] 2018-03-29 08:49
@sbatten @RMacfarlane This works for us in ZRH. We are not able to reproduce.

**Comment by weinand** [comment] 2018-03-29 08:50
I'm leaving this open...

**Comment by roblourens** [comment] 2018-03-29 22:18
The regex that parses the wmic output is not matching. The output for me looks like 

```
"C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap" --type=extensionHost






                                                                                                                                                              20180329150840.878313-420
 2736             6040
```

So the problem is that the regex expects a `+` at `-420`, which is the time zone! It works if I change the regex. That's a good one...

**Comment by roblourens** [comment] 2018-03-29 22:18
I also noticed that some lines only have empty space for the CommandLine attribute, so the regex doesn't match for those either. Is that expected?

**Comment by weinand** [comment] 2018-03-29 22:37
Ha, excellent find! Thanks for you investigation.

afters today's finding that it works in ZRH but not in the US I had a similar speculation (but I had forgotten that I had added the start time to get the sorting right). It would be great if you could add a '-'. Maybe there is even a ' ' if you are in the Greenwich time zone ;-)

If the CommandLine is really empty, then the process is not really interesting for the functionality built into node-debug (there are no --inspect args etc.). For the process viewer it would be a problem because there we are interested in all child processes of VS Code. So, I think we can live with that bug for now.

**Closed** 2018-03-30 00:14 UTC
Labels: bug, debug

**Comment by roblourens** [comment] 2018-03-30 00:16
Fixed, and verified that it writes +000 in the UTC zone
