### ISSUE TITLE
CSS Tab Completions giving unexpected results ?

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode#26792] opened 2017-05-17 05:26 UTC
- VSCode Version: 1.12.2
- OS Version: MacOS sierra 10.12.4
## List of installed extensions
```
EditorConfig.EditorConfig@0.9.3
HookyQR.beautify@1.0.2
christian-kohler.path-intellisense@1.4.2
dbaeumer.vscode-eslint@1.2.8
dracula-theme.theme-dracula@1.17.0
eg2.tslint@0.15.0
mitchdenny.ecdc@0.10.3
msjsdiag.debugger-for-chrome@3.1.1
naumovs.theme-oceanicnext@0.0.4
robertohuertasm.vscode-icons@7.7.0
```
### Expected
```scss
//type and hit tab.
df --> display: flex;
posa --> position: absolute;
```

### Actual
```scss
//type and hit tab
df --> stroke-dashoffset: 
posa --> padding-block-start: 
```

The funny thing is, if I hit undo and hit tab again, they give me the desired result. So
```scss
df --> stroke-dashoffset: **UNDO** df --> display: flex;
```

**NOTE:** The problem exists in the insiders build, 1.13.0 too with ZERO extensions installed.

**Comment by Tyriar** [comment] 2017-05-17 18:07
I think this is emmet?

**Comment by ramya-rao-a** [comment] 2017-05-17 18:36
Duplicate of #1952

You can use https://github.com/Microsoft/vscode/issues/1952#issuecomment-293770991 as a workaround for now.

We are working on getting the emmet expansions in the suggestion list, when that is done you won't need the workaround. That work is tracked in #21943

**Closed by ramya-rao-a** 2017-05-17 18:36 UTC
Labels: emmet

**Comment by praveenpuglia** [comment] 2017-05-18 04:55
Thanks a lot. Works as expected now! :)

**Comment by ramya-rao-a** [comment] 2017-06-01 05:24
@praveenpuglia See https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464 for updates on this issue. You can now get emmet abbreviation expansion in the suggestion list without giving up on quick suggestions
