### ISSUE TITLE
Replace All doesn’t work in large files

### ISSUE THREAD

**Issue by JensRoland** [Microsoft/vscode#52813] opened 2018-06-25 14:20 UTC
Editing a >300MB text file, I noticed that ‘find’ cleverly caps the match count at 20k, but ‘replace all’ doesn’t work. It seems to be trying to do something (the button is unresponsive for maybe a second or two) but when it ‘finishes’ nothing has been replaced in the document. I waited for >2 minutes without touching anything, to no effect. I’m sure it shouldn’t take that long regardless (I checked and Sublime Text does the same operation in ~4 seconds on the same hardware).

I tried searching a different word with just 1100 occurrences and ‘replace all’ still does nothing.

Replace (one) works as expected in all cases.

I am running the latest stable version (updated today) on MacOS.

**Comment by rebornix** [comment] 2018-09-04 23:30
Duplicate of https://github.com/Microsoft/vscode/issues/40580, let track it there. Thanks!

**Closed** 2018-09-04 23:31 UTC
Labels: *duplicate, editor, editor-find
