### ISSUE TITLE
Freeze when delete folder

### ISSUE THREAD

**Issue by chiro-hiro** [Microsoft/vscode#65802] opened 2018-12-29 05:12 UTC
Issue Type: <b>Performance Issue</b>

**Steps:**

1. Open Node.JS project
2. Delete node_modules

**Result:**

- Visual Code got freezed
- Not able to interactive with UI
- Visual Code return to normal after 1-2 mins

**Expected:**

- Hide deleting folder
- Process delete command in background
- Visual Code UI should not freeze

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>Workspace Info</summary>

```
|  Window (package-lock.json - web3.js-interface - Visual Studio Code)
|    Folder (web3.js-interface): 30 files
|      File types: js(14) json(5) gitignore(2) md(2) html(2) css(2) ico(1)
|                  svg(1) sol(1)
|      Conf files: package.json(2) webpack.config.js(1);
```

</details>

**Comment by usernamehw** [comment] 2018-12-30 23:02
Possible duplicate of #43508

**Comment by isidorn** [comment] 2019-01-03 10:05
@usernamehw thanks
Closing as dup of that one. @chiro-hiro please comment more here if needed #43508

**Closed by isidorn** 2019-01-03 10:05 UTC
Labels: javascript
