### ISSUE TITLE
Uninstalling extension on Windows 10 does not prompt for a restart

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#14542] opened 2016-10-26 14:50 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1. Uninstall extension through VSCode interface
2. Extension remains visible in the list
3. VSCode does not prompt for a restart

Note: On a Mac OS X and Linux works as expected.

Is behavior on windows a feature or a bug?

Thank you

**Comment by sandy081** [comment] 2016-11-02 08:16
@riteshatsencha I am not able to reproduce it. 
On 1.6.1, I am seeing the reload window prompt on uninstalling an extension. Can you please confirm? Thanks.


For heads-up, In up-coming stable version and latest insiders, following would be the behavior in all platforms
- Uninstall extension
- Prompts a dialog for confirmation
- Confirming will uninstall
- A reload button will appear
- Clicking on reload button prompts dialog for reloading window
- Confirming will reload the VS Code window

L

**Comment by riteshatsencha** [comment] 2016-11-15 15:38
It's not consistent. Upon uninstalling extension on windows sometimes I see "Reload" option otherwise nothing happens, which means I stay on the extension page in the editor. When I reopen vscode the extension is removed. This is with 1.7.1.

Thx

**Comment by sandy081** [comment] 2016-11-15 20:55
@riteshatsencha If you uninstall an extension which you installed (without reopening VSCode) reload action will not be shown as it is not required. Reload action is shown only if required. 

May I ask you to try latest insiders and tell us what you see?

Thanks

**Comment by sandy081** [comment] 2017-02-27 14:53
Closing this as there is no feedback

**Closed by sandy081** 2017-02-27 14:53 UTC
Labels: extensions, needs more info
