### ISSUE TITLE
U+301C and U+FF5E are not correctly mapped in EUC-JP/Shift_JIS/CP932

### ISSUE THREAD

**Issue by yh1224** [microsoft/vscode#48802] opened 2018-04-27 09:03 UTC
expected: A1 C1
actual: 8F A2 B7

- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro (1709)

Steps to Reproduce:

1. Type "～" (U+FF5E)
2. Open Command Palette
3. Change File Encoding -> Save with Encoding -> Japanese (EUC-JP)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-04-27 09:15
@yh1224 I cannot reproduce, the file saves and opens fine for me. Find it attached:

[eu-jp.txt](https://github.com/Microsoft/vscode/files/1954506/eu-jp.txt)

What do you see?

**Comment by yh1224** [comment] 2018-04-27 22:30
@bpasero
I can see "～" when reopened by VSCode, but some other editor cannot see it.

Open it by Atom editor, it changes to "潤"(0xBDE1).

**Comment by yh1224** [comment] 2018-04-28 00:26
8F A2 B7 is valid code point but might cause interoperability issues.

**Comment by AzetJP** [comment] 2018-11-28 09:56
I encounter the same problem, the character in the file I have is U+301C which is called "wave dash".
But once I save the file, that character becomes U+FF5E which is called "full width tilde".

I realized the problem in git (before a commit) and checked the code points in Emacs.

It would be great if this could be addressed, we have a couple of large projects using EUC-JP and it's dangerous to open files if their content is wrongly re-encoded when saved...

**Comment by bpasero** [comment] 2020-11-04 07:44
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming

**Closed by bpasero** 2020-11-04 07:44 UTC
Labels: file-encoding, upstream, upstream-issue-linked
