### ISSUE TITLE
[Feature] add support to use a custom UriHandler with DocumentSymbolProvider

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#146115] opened 2022-03-26 21:09 UTC
am creating a symbol provider for env files & i wanted to have a way to execute a command after a symbol is selected, 
so i though about using the `Uril.with()` to add a uri handler that i can listen to somewhere else and act accordingly but sadly its not working.

am not sure if this is considered as a new a feature or am i missing something.

here is an example for what am trying to achive
https://github.com/ctf0/env-symbol-provider/blob/main/src/extension.ts

**Comment by jrieken** [comment] 2022-03-28 06:19
When selecting document symbols we always attempt to open an editor, we don't look at its uri as a generic uri. What are you trying to achieve here? Document symbol elements always need a document position. Having additional commands is something that has been asked for but document positions and revealing them on click are key

**Comment by ctf0** [comment] 2022-03-28 06:37
i was trying to add a copy to clipboard when a symbol is selected.

however i still dont quite understand why when using the same uri we pass to the symbol provider with another provider ex.a link provider we get a different behavior.

**Comment by jrieken** [comment] 2022-03-28 07:45
> however i still dont quite understand why when using the same uri we pass to the symbol provider with another provider ex.a link provider we get a different behavior.

The API generally corresponds to an element/feature in the UI - document symbols correspond to the dynamic/static trees of symbols of a the active editor which reveal themselves when clicked. That means we open an editor, don't even attempt to open a link

**Comment by ctf0** [comment] 2022-03-28 08:22
oh ok, thank you for clarifying that, as for the ticket, would u consider something like this to add or should i close it ?

**Comment by jrieken** [comment] 2022-03-28 11:30
Closing this as duplicate of https://github.com/microsoft/vscode/issues/49925. That is an ask for contributable commands for outline elements. That would also allow for a copy-paste command

**Closed by jrieken** 2022-03-28 11:30 UTC
Labels: needs more info, outline
