### ISSUE TITLE
Hot Exit: Restore files after an editor crashes

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/vscode#12327] opened 2016-09-20 15:28 UTC
Vscode is so excellent , we love it very much!  But this days vscode still has some bugs making it crash, especially when I work with big project that open so many files at the same time. And when vscode reopenes after crashed, the file openning status rolls back to that when I openned it last time, not the status when it alert  "no responding". This make some inconvenience for us to contunue our work. So I hope vscode can save the file openning status when it crash.

**Comment by chrmarti** [comment] 2016-09-20 16:35
Related to #101

**Comment by Tyriar** [comment] 2016-09-20 17:02
Duplicate of #101

**Comment by Tyriar** [comment] 2016-09-21 07:40
I'm going to track this feature separately to #101

**Comment by Tyriar** [comment] 2016-11-11 20:20
I believe this is mostly working, it will currently not attempt to restore the changes until VS Code has been completely exited though. We probably want a dialog asking whether the user wants to restore.

**Comment by bpasero** [comment] 2016-11-18 10:09
Needs https://github.com/Microsoft/vscode/issues/15718

**Comment by bpasero** [comment] 2016-11-29 11:45
@Tyriar should we look into enabling this scenario now that I landed https://github.com/Microsoft/vscode/commit/6422acbb006f9a32ef34dc1d98ebd6c75688cfcd ?

Imho the only thing needed is to remove the checks for hot exit being enabled in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/backup/common/backupModelTracker.ts#L58

**Comment by Tyriar** [comment] 2016-11-29 19:47
The checks must remain for the extension development case. I suggest we support crash recovery on empty workspaces when we support hot exit on empty workspaces (which should be soon). https://github.com/Microsoft/vscode/issues/13733

**Comment by bpasero** [comment] 2016-11-30 06:00
@Tyriar sure for extension development we can have another check to not do backups. I am not sure how crash recovery and empty workspaces are related, I could have a folder opened with dirty files and a crash takes down my changes. I would want them to restore even if hot exit is disabled.

**Comment by Tyriar** [comment] 2016-12-03 05:36
Backups should be happening all the time now due to empty workspace restore :fireworks:

**Comment by bpasero** [comment] 2016-12-03 06:43
@Tyriar does not work for me:
* make some files dirty
* kill the process
* restart
=> no restore

I think you still check for `isHotExitEnabled` in `backupModelTracker.ts`?

**Closed** 2016-12-04 01:21 UTC
Labels: feature-request, hot-exit

**Comment by Tyriar** [comment] 2016-12-05 22:06
Test plan https://github.com/Microsoft/vscode/issues/16544
