### ISSUE TITLE
[Linux] Emojis not displayed correctly

### ISSUE THREAD

**Issue by teohhanhui** [microsoft/vscode#107433] opened 2020-09-25 11:30 UTC
Issue Type: <b>Bug</b>

Some emojis are displayed as the text variant (not coloured). Other emojis are displayed as square boxes. This happens in both the editor and built-in terminal.

I've tried with the following settings:

```json
{
    "editor.fontFamily": "'Fira Code', 'Noto Sans Mono', 'Noto Sans CJK TC', 'Noto Color Emoji', 'monospace', monospace, 'Droid Sans Fallback'",
    "terminal.integrated.fontFamily": "'Hack', 'Noto Sans Mono', 'Noto Sans CJK TC', 'Noto Color Emoji', 'monospace', monospace, 'Droid Sans Fallback'",
}
```

The emojis are displayed correctly in other apps, including in Firefox, Google Chrome, and Gnome Terminal.

Related:
* https://github.com/microsoft/vscode/issues/50122
* https://github.com/microsoft/vscode/issues/32840

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.8.11-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics (8 x 3241)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.09GB (3.47GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8588a123-c2a1-4176-9fc4-76f5102045d0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
rust-analyzer|mat|0.2.320
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
crates|ser|0.5.3
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by teohhanhui** [comment] 2020-09-25 11:55
Looks like doing `chsh -s /usr/bin/bash` has fixed the problem. Manjaro Gnome recently switched to `zsh` as the default shell.

**Comment by rzhao271** [comment] 2020-11-04 18:46
Closing because it seems to do more with the shell than VS Code.

**Comment by teohhanhui** [comment] 2020-11-04 19:08
I don't see how it makes sense that using a different shell would break this for vscode. I think this warrants more investigation.

**Comment by Tyriar** [comment] 2020-11-04 19:20
Hmm, if bash fixes it and zsh doesn't then chances are they're sending different data for the various emoji. Some more info that would be useful:

- Which emoji you're using
- Show a screenshot of bash vs zsh

I don't have a Manjaro setup, but the next steps would be figuring out what the shell is sending over and checking if this is reproducible also in [xterm.js](https://github.com/xtermjs/xterm.js) and fixing it there as that's the terminal frontend project.

**Closed** 2021-10-12 17:18 UTC
Labels: bug, upstream, terminal
