### ISSUE TITLE
Feature Request: API: Subscribe to the "data" event on a terminal

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#16989] opened 2016-12-09 16:25 UTC
Hi everybody,

I suggest to add a new function `on` to the class `Terminal`.

## Motivation
There is an extension for Rust [RustyCode](https://github.com/saviorisdead/RustyCode).
There is a command **build**.
When build is finished, we parse output and show warnings, errors and etc. in user's code.
Currently it is made via the class `OutputChannel`, which doesn't support input.

## Example
```typescript
let terminal = vscode.window.createTerminal('Build');
terminal.on('data', data => {
    let buildProgress = this.parseBuildProgress(data);
    this.updateBuildProgress(buildProgress);
});
terminal.show();
terminal.sendText('make');
```

### Write to a file
```typescript
let terminal = vscode.window.createTerminal('Build');
terminal.show();
terminal.sendText('make |& tee /tmp/some_file');
```

I will implement it myself.
I am opening this issue to receive opinions.

Regards,
Alexey

**Comment by Tyriar** [comment] 2016-12-09 20:43
Closing this off as a duplicate of https://github.com/Microsoft/vscode/issues/13337, not quite ready to accept a PR for this yet but the terminal API is one of the areas I'll be looking at in January. We have a similar need though as we want the tasks framework to use the terminal instead of output https://github.com/Microsoft/vscode/issues/15584

**Closed by Tyriar** 2016-12-09 20:43 UTC
Labels: api, feature-request
