### ISSUE TITLE
Does not open the folder

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#17640] opened 2016-12-21 05:06 UTC
- VSCode Version: 1.8.1
- OS Version: win 10

Steps to Reproduce:

1. right click on any file and open it with visual studio.
2. click on explorer and it is said no folder opened which is a problem.
https://postimg.org/image/jpw8sbmsx/

if I have to use another file of the folder then I have to open the folder manually or I have to drag a file inside. I request to open the folder automatically as atom does. its easier to work.

**Comment by egamma** [comment] 2016-12-21 15:27
When you select a single file then VS Code opens the single file. When you select a folder in the explorer then VS Code opens the folder. Therefore rather than opening a single file you should open its parent folder in VS Code.

Assigning the issue to @chrmarti he is looking into improving the getting started experience and mentioned this issue in a recent discussion.

**Comment by khaled-hossain-code** [comment] 2016-12-26 04:14
@egamma I know that but I wanted to use VS code to peek files. It would be a nice feature to have and makes more scene rather than showing a open folder button inside vs code. Neither atom will be a easy to use option for peeking at files. But I love VS code more. :)

**Comment by chrmarti** [comment] 2017-02-07 16:58
Related: #15654

**Comment by chrmarti** [comment] 2017-02-16 05:34
Pushed #20671, which will use the `.vscode` folder as a hint that its folder should be opened. We have so far avoided always opening a folder, because that might not be what the user wants us to do. If we still decided to do that, we might put it behind a setting.

**Comment by bpasero** [comment] 2017-11-21 06:19
Closing as designed, I think our current behaviour is fine.

**Closed by bpasero** 2017-11-21 06:19 UTC
Labels: feature-request, workbench
