### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by mkoci** [microsoft/vscode#88443] opened 2020-01-10 19:06 UTC
Issue Type: <b>Bug</b>

To my extensions are included, so to reproduce, just install the extensions and edit any .jsx file. Whether I select JavaScript React or TypeScript react to render it, it still produces the infamous 'The TypeScript language service died 5 times right after it got started. The service will not be restarted.'

I have seen so many dupes of this issue. Does this happen because I'm trying to edit normal React/JS rather than React/TS? 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.86GB (7.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.48
vscode-styled-jsx|bla|1.5.0
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.13
githistory|don|0.4.13
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
vscode-indent-on-paste|gaz|2.3.3
html-slim-scss-css-class-completion|gen|1.5.23
node-module-intellisense|lei|1.5.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
ActiveFileInStatusBar|Ros|1.0.3
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.1
autoimport|ste|1.5.3
unique-window-colors|stu|1.0.51
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.2
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.26.0
vscode-import-cost|wix|2.12.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

Here are my debug console logs for tsserver leading up to the crash:

```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///c%3A/Users/matth/.vscode/extensions/wingrunr21.vscode-ruby-0.26.0/syntaxes/ruby.cson.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Looking for parseable documents...
console.ts:137 [Extension Host] Found all parseable documents.
console.ts:137 [Extension Host] Parsing documents and looking for CSS class definitions...
console.ts:137 [Extension Host] Summary:
console.ts:137 [Extension Host]% 9 parseable documents found
console.ts:137 [Extension Host]% 7710 CSS class definitions found
console.ts:137 [Extension Host]% 2515 unique CSS class definitions found
console.ts:137 [Extension Host]% 0 failed attempts to parse. List of the documents:
console.ts:137 [Extension Host] 
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command '_typescript.configurePlugin' not found
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: command '_typescript.configurePlugin' not found    at u._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3222:836)    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3222:717    at processTicksAndRejections (internal/process/task_queues.js:89:5)
t.log @ console.ts:137
log.ts:196   ERR command '_typescript.configurePlugin' not found: Error: command '_typescript.configurePlugin' not found
    at u._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3222:836)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3222:717
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
2console.ts:137 [Extension Host] (node:32340) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
extensionsViews.ts:258 Error querying extensions gallery Canceled
(anonymous) @ extensionsViews.ts:258
event.ts:446 [73f] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:446
event.ts:447     at new e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5827:384)
    at h._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1556:381)
    at h.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1555:754)
    at S.renderTemplate (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5910:621)
    at a.renderTemplate (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:919:718)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:907:955
    at Array.map (<anonymous>)
    at V.renderTemplate (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:907:946)
    at t.RowCache.alloc (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:309:214)
    at y.insertItemInDOM (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:482:858)
    at y.render (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:482:474)
    at y.onScroll (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:487:771)
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:913)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:511
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:893)
    at o._setState (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:215:542)
    at o.setScrollDimensions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:213:761)
    at _.setScrollDimensions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:461:766)
    at y.layout (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:481:953)
    at H.layout (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:914:649)
    at W.layout (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:922:201)
    at t.BuiltInExtensionsView.layoutBody (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6078:622)
    at t.BuiltInExtensionsView.layout (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:545:623)
    at f.layout (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:496:709)
    at b.layoutViews (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:508:864)
    at b.onSashChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:503:619)
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:913)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:110:396
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:893)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:455:783
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:893)
    at s (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:649)
check @ event.ts:447
notificationsAlerts.ts:40 The TypeScript language service died 5 times right after it got started. The service will not be restarted.
```

**Comment by mjbvz** [comment] 2020-01-11 00:31
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mkoci** [comment] 2020-01-12 22:38
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

It does not reproduce in insiders with extensions disabled...

**Comment by kaoDev** [comment] 2020-01-13 11:46
I just had the same issue and could trace the cause to an open unsaved file with the language mode set to typescript or javascript

Hope this information helps

**Comment by mjbvz** [comment] 2020-01-13 21:15
Closing this as not-reproducible since it does not happen in insiders. (also could be caused by an extension)

**Closed by mjbvz** 2020-01-13 21:15 UTC
Labels: needs more info
