### ISSUE TITLE
Cannot terminate task when running using the regular task runner then switching to terminal runner 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19241] opened 2017-01-24 17:47 UTC
Testing #19057

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

Steps to Reproduce:

1. Setup and run a watch task that doesn't terminate
2. Add `"_runner": "terminal"` to `tasks.json`
3. Try run the task again
4. You will be asked to terminate, it doesn't appear to do it, repeat 3-4

**Comment by Tyriar** [comment] 2017-01-24 17:56
Even when I remove `_runner` I keep getting this message:

<img width="587" alt="screen shot 2017-01-24 at 9 56 20 am" src="https://cloud.githubusercontent.com/assets/2193314/22259767/6dc348a0-e21b-11e6-8fbe-ebd6ee8ff393.png">

**Comment by dbaeumer** [comment] 2017-01-25 13:38
The fact that you couldn't kill the build task even in the output runner is a dup of #19328. Hot switching the runner with running processes is currently not support I don't intend to do so (not a common use case since the Output runner will go away in 1 - 3 releases). I will add a warning that hot swapping is not supported.

**Comment by aeschli** [comment] 2017-01-27 13:27
What I see now is that on step 3, you get a dialog:
The task is already active and in watch mode. To terminate the task use `F1 > terminate task`
Which of course is not true.

I understand that this is a bit of a constructed example, with switching the runner while a task is running.
@dbaeumer What is the expected behaviour?

**Comment by dbaeumer** [comment] 2017-01-27 14:02
@aeschli hot switching is not supported and will never be. I added a message that if you try to hot switch the runner that informs you that you need to reload the window. So you should still be able to terminate the task. I will reopend and reinvestigate in Feb.

**Comment by dbaeumer** [comment] 2017-01-27 14:02
Not critical.

**Comment by dbaeumer** [comment] 2017-03-24 14:29
Fixed by two things:

- you can't hot switch the runner anymore. It stays the same even if you change values in the tasks.json
- if the terminal runner is used then you now get a list of active tasks to terminate (if more than one). 

No further action planned since hot switching will not be supported.

**Closed by dbaeumer** 2017-03-24 14:29 UTC
Labels: bug, tasks
