### ISSUE TITLE
How to view list function

### ISSUE THREAD

**Issue by destosuce** [Microsoft/vscode#33598] opened 2017-08-31 14:34 UTC
- VSCode Version: 
- OS Version: Windows 7

Questions: I am very like to use this app to develop app with C language. It almost the best app which I have developed before(Sakura editor, Hidemaru editor). 
But, It's has a big problem which I can"t manage my project when my project have more than 50 functions at the same files. In Sakura editor or Hidemaru, I easy to sea list functions at each file that I had opened. This list functions was auto list at the left panel... So convenient.

Realy, I want to use Visual Studio Code, Because It's have a Intelegent, Easy to load folders  in Visual Studio Code....

Please ! Please add the panel which auto list function of file when I open that file.

Wait your response!!!!!! Thanks team for the best App. 

Reproduces without extensions: Yes

**Comment by jrieken** [comment] 2017-08-31 14:39
duplicate of #5605

**Closed by jrieken** 2017-08-31 14:39 UTC
Labels: workbench
