### ISSUE TITLE
can not input the commit message

### ISSUE THREAD

**Issue by WuHanMuMu** [microsoft/vscode#113278] opened 2020-12-22 08:34 UTC
when inputting,  if the auto refresh runned,  cannot input the message anymore

**Comment by GzhiYi** [comment] 2020-12-24 02:44
Same issue.

Basic info:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0
```

**Comment by eamodio** [comment] 2021-01-05 06:13
Duplicate of #112621

**Closed by eamodio** 2021-01-05 06:13 UTC
