### ISSUE TITLE
Focus current cursor position in multiline select

### ISSUE THREAD

**Issue by sAs59** [Microsoft/vscode#38330] opened 2017-11-14 15:55 UTC
VSCode Version: 1.18.0 
OS Version: macOS High Sierra (10.13.1)

- Focusing current cursor position doesn't work when working with multiple lines.

![nov-14-2017 21-39-14](https://user-images.githubusercontent.com/9218560/32788764-51f6c236-c984-11e7-8459-94874eee85e0.gif)

**Comment by alexandrudima** [comment] 2017-11-16 08:36
@sAs59 I do not understand what the problem is from looking at the gif. What steps are you doing? What would you expect to happen vs. what happens ?

**Comment by sAs59** [comment] 2017-11-16 15:52
@alexandrudima With _word_wrap: off_ and moving the cursor to end of the line (cmd+right) window follows the cursor position. But, if we do the same opearation with multiline cursor, it doesn't focus.

**Comment by alexandrudima** [comment] 2017-11-17 10:07
Thank you for the extra info. Duplicate of #9593

**Closed by alexandrudima** 2017-11-17 10:07 UTC
Labels: editor, editor-multicursor, needs more info
