### ISSUE TITLE
Feature: Working files should reload on refresh

### ISSUE THREAD

**Issue by EWhite613** [Microsoft/vscode#5612] opened 2016-04-21 14:52 UTC
Currently only the project tree reloads. But if a file was modified outside vscode the working file is never updated. You have to close the file and re-open.

So working files should have some sort of message that a file has been modified outside vscode, and give the option to reload. But at the very least the functionality to reload the project tree should also reload the working files if they have been modified outside vscode

**Comment by bpasero** [comment] 2016-04-21 15:03
@EWhite613 it should reload its contents when it changed outside.

**Comment by EWhite613** [comment] 2016-04-21 15:08
@bpasero are you not able to reproduce? I've had it happen on big and small projects. Our files change after git pull and we have to close and close re-open all the files to see the changes. So has my co-worker

**Comment by bpasero** [comment] 2016-04-21 15:12
Right, it is known to not work with git so well due to bugs in node.js. Closing as duplicate of https://github.com/Microsoft/vscode/issues/2592

**Closed by bpasero** 2016-04-21 15:12 UTC
