### ISSUE TITLE
Initial output in terminal wraps at 80 columns instead of screen width

### ISSUE THREAD

**Issue by ridiculousfish** [microsoft/vscode#98399] opened 2020-05-22 21:28 UTC
Issue Type: <b>Bug</b>

Originally reported as https://github.com/fish-shell/fish-shell/issues/7015 but it is not fish specific.

Output that occurs early in the integrated terminal will often wrap at 80 even if $COLUMNS is larger.

To reproduce with bash:

1. Use `chsh` to switch your login shell to bash
2.  Place the following into `~/.bash_profile`:

```
END=$COLUMNS
for ((i=1;i<END;i++)); do
    echo -n x
done
echo -e -n "\r"
tput el
```

This will output a bunch of literal `x`, followed by a carriage return and `clr_eol`. The result should be an empty line, with all `x`s deleted.

3. Open a new terminal using Terminal.app or iTerm2, and you will not see any `x`s.

4. Open a new VSCode integrated terminal that is wider than 80 columns, with bash as the shell. You will see several rows of `x` because the output wrapped at 80 columns.

This also reproduces with zsh (using `~/.zshrc`) though it collides with some of zsh's own tricks.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 5.6.10-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sunfire|
|OS|Linux x64 5.6.10-arch1-1|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 800)|
|Memory (System)|15.51GB (1.68GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
clojure|avl|0.13.1
mdmath|goe|2.4.0
vscode-ghc-mod|hoo|1.2.0
language-haskell|jus|3.2.1
restructuredtext|lex|128.0.0
rust-analyzer|mat|0.2.174
vscode-docker|ms-|1.2.0
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.1
vscode-proto3|zxh|0.4.2

</details>

**Comment by Tyriar** [comment] 2020-06-08 19:22
I can't reproduce in bash Windows -> Linux (WSL) which should act the same as Mac -> Linux (SSH). I see the x's flash and then go away, it only happens in a single frame though so I'm having trouble capturing in a gif:

![recording (17)](https://user-images.githubusercontent.com/2193314/84071538-b70ac380-a982-11ea-80e5-a728532cac79.gif)

**Comment by ridiculousfish** [comment] 2020-06-09 06:21
I am able to reproduce on macOS Catalina 10.15.4 with integrated terminal using local files (no remote).

I cannot reproduce on a Linux box (Ubuntu 19.10) with local files. I also cannot repro from my Mac using the Linux machine as remote. So I think this is specific to using a Mac locally. Do you have access to a Mac to test on?

Here is what I see on my Mac, notice the x's wrap too early:

![ezgif-4-b8a055263ae9](https://user-images.githubusercontent.com/920838/84113045-b3a52580-a9de-11ea-8dd9-702890d26a1e.gif)

**Comment by shroudedcode** [comment] 2020-06-09 10:20
I'm able to reproduce this on Linux (Pop!_OS / Ubuntu 20.04 LTS).

First with less than 80 columns, then with more than 80 columns:

![](https://user-images.githubusercontent.com/29176678/84133440-7923a300-aa47-11ea-80fc-32a5086c34bf.gif)

**Comment by Tyriar** [comment] 2021-03-16 17:35
Probably same root cause as https://github.com/microsoft/vscode/issues/110696

**Comment by Tyriar** [comment] 2021-03-29 15:57
I believe this is fixed by https://github.com/microsoft/vscode/issues/117188

**Closed by Tyriar** 2021-03-29 15:57 UTC
Labels: bug, integrated-terminal
