### ISSUE TITLE
Pressing Tab removes code

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9870] opened 2016-07-27 21:20 UTC
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

1. 
![image](https://cloud.githubusercontent.com/assets/1723815/17192847/521bd76a-541e-11e6-9008-2081d1f6be36.png)

2. Press Tab

3. 
![image](https://cloud.githubusercontent.com/assets/1723815/17192852/59205e82-541e-11e6-8ad5-0b890f4adfe1.png)

**Comment by wallverb** [comment] 2016-07-28 22:42
1. Create `test.js` file
2. Paste this code:
```
    var test = [123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 124, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 125, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123]
```
3. Make sure that you have default setting `"editor.wrappingColumn": 300,`
4. Select lines in this way:
![image](https://cloud.githubusercontent.com/assets/1723815/17231842/4e000fb4-54f2-11e6-862c-afd90ce5844e.png)
5. Press Tab expecting to indent text
6. Selected part of text is gone
![image](https://cloud.githubusercontent.com/assets/1723815/17231960/e868b182-54f2-11e6-9373-f1a4020b9a2b.png)

I compared it with Atom - and they handle it properly (indents the text)

**Comment by Tyriar** [comment] 2016-08-01 20:48
I can repro this. @alexandrudima consider looking into this for 1.4.0

**Comment by alexandrudima** [comment] 2016-08-02 13:10
Duplicate of #8805

**Closed by alexandrudima** 2016-08-02 13:10 UTC
Labels: bug, editor, important
