### ISSUE TITLE
Open the html in either Finder or specific Browser

### ISSUE THREAD

**Issue by upradeepk** [Microsoft/vscode#22384] opened 2017-03-10 11:35 UTC
- VSCode Version:Version 1.9.1 (1.9.1)
- OS Version:10.11.5

Steps to Reproduce:

There is currently no option to open the html file in Finder or a browser directly from VSCode. You have to Reveal the item in Finder and then open it from there. Would be handy to have a open in browser feature directly.

**Comment by mjbvz** [comment] 2017-11-03 20:39
Duplicate of #15928

**Closed by mjbvz** 2017-11-03 20:39 UTC
Labels: duplicate, extension-candidate, feature-request, workbench
