### ISSUE TITLE
MacOS window focus issue with explorer and "New File"

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#233983] opened 2024-11-16 14:31 UTC
Type: <b>Bug</b>

I can't quite put my finger on it exactly, but I keep on being in the wrong window randomly or scrolling up to the top in the current pane. For example clicking new file, usually opens up the pane but doesn't focus, then when you focus it using the mouse it closes or you end up on another project's window. A lot of time inside of terminal it all of a sudden scrolled to the top and I have not figured out if it's anything I did. The scrolling problem I am also seeing on ubuntu, but the focus problem is fine there.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.90GB free)|
|Process Argv|--crash-reporter-id befd3bac-437d-406e-90c6-88d659dbcb8b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (113)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
vscode-sql-formatter|adp|1.4.4
golangwithdidi|ald|0.0.1
rtf|ale|2.8.0
astro-vscode|ast|2.15.4
vscode-django|bat|1.15.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.26.0
markdown-preview-github-styles|bie|2.1.0
markdown-yaml-preamble|bie|0.1.0
biome|bio|2.3.0
gotemplate|cas|0.5.0
rescript-vscode|che|1.58.0
vscode-eslint|dba|3.0.10
vscode-motoko|dfi|0.16.13
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
rust-syntax|dus|0.6.1
gitlens|eam|16.0.1
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.245.0
copilot-chat|Git|0.23.2024102903
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.1
go|gol|0.42.1
todo-tree|Gru|0.0.226
terraform|has|2.34.0
haskell|has|2.4.4
vscode-ansi|ili|1.1.7
elixir-ls|Jak|0.24.2
plantuml|jeb|2.18.1
crates-completer|jed|1.2.1
vscode-peacock|joh|4.2.2
rust-doc-viewer|JSc|4.2.0
solidity|Jua|0.0.179
language-haskell|jus|3.6.0
vsc-python-indent|Kev|1.18.0
Kotlin|mat|1.7.1
rainbow-csv|mec|3.12.0
vscode-html-format|moh|0.1.6
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
playwright|ms-|1.1.12
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-ssh-explorer|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.26.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.11.1
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-js-profile-flame|ms-|1.0.9
vsliveshare|ms-|1.0.5941
gremlins|nho|0.26.0
env-cmd-file-syntax|Nix|0.3.0
autodocstring|njp|0.6.1
vscode-twoslash-queries|Ort|1.4.0
bun-vscode|ove|0.0.16
gotestexplorer|pre|0.1.13
prisma|Pri|5.22.0
quicktype|qui|23.0.170
java|red|1.36.0
vscode-yaml|red|1.15.0
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.2180
svg-preview|Sim|2.8.3
vsc-quokka-statusbar|ske|1.3.6
slint|Sli|1.8.0
stately-vscode|sta|2.1.0
code-spell-checker|str|3.0.1
svelte-vscode|sve|109.2.3
rust-pack|Swe|0.3.38
even-better-toml|tam|0.19.2
tauri-vscode|tau|0.2.9
stylelint|thi|0.51.0
vscode-ide|tla|2024.11.130034
cmake|twx|0.0.17
har-viewer|unc|0.0.2
vscode-mdx|uni|1.8.11
errorlens|use|3.20.0
vscode-lldb|vad|1.11.1
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
explorer|vit|1.6.9
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
volar|Vue|2.1.10
console-ninja|Wal|1.0.369
quokka-vscode|Wal|1.0.661
wallaby-extension-pack|Wal|1.0.1
wallaby-vscode|Wal|1.0.394
jinja|who|0.0.8
vscode-surround|yat|1.5.0
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by richtera** [comment] 2024-11-18 20:27
I figured out the scrolling problem can be reproduced with something like the turbo build command. It uses ansi control sequences to put up a multi pane display, and then tears it down. After the command executes. You can type a command and execute the next command normally, but when scrolling you're at the top of the buffer rather than at the end.

**Comment by justschen** [comment] 2024-12-10 10:04
is this window/aux window related? don't think I really follow the repro steps here

**Comment by richtera** [comment] 2024-12-10 21:20
I don't think so. This just happens on a Mbp with either an external monitor or without. It seems be somehow affect focus randomly.

The scrolling problems seems to be related with CLI command lines which use positioning on the output. For some reason after the command the screen looks ok, but it's scrolled to the wrong line when looking at the scroll bar. When typing in the next command things move. I think the cli might be doing the wrong thing. This is specifically a problem with the turbo monorepo tool.

The focus most often happens when clicking on the exporer and clicking the new file button in the explorer. This correctly opens up the new area where the name of the new file should be, however the keyboard is not focused on the new file name. Then clicking on the file name actually aborts the file creation and you have to try it a second time when it works successfully.

**Comment by lramos15** [comment] 2024-12-17 17:47
This sounds like a duplicate of https://github.com/microsoft/vscode/issues/143968

**Closed by lramos15** 2024-12-17 17:47 UTC
Labels: bug, file-explorer, macos, confirmation-pending

**Comment by richtera** [comment] 2024-12-17 18:00
Yes it looks that way, the scrolling problem was apparent at the same time but doesn't seem related at all. The scrolling problem might be a problem with turbo, but somehow when using a lot of ansi positioning codes in the terminal the scroll bar gets confused.
