### ISSUE TITLE
 add compatibility for voice control dictation on Mac

### ISSUE THREAD

**Issue by motclem** [microsoft/vscode#123511] opened 2021-05-10 20:27 UTC
I would like to be able to  dictate to Visual studio code are using dictation and voice control on macOS at the moment nothing happens when I have Voice control enabled  and I try  to talk to vsc

**Comment by isidorn** [comment] 2022-12-08 14:32
Closing as duplicate of https://github.com/microsoft/vscode/issues/40976

fyi @meganrogge

**Closed by isidorn** 2022-12-08 14:32 UTC
