### ISSUE TITLE
Ranking for "night-owl-vscode-theme" search in marketplace doesn't return obvious results

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#69810] opened 2019-03-04 22:15 UTC
When searching for `night-owl-vscode-theme` in the marketplace the ranking doesn't return obvious extensions as the priority.

Search ranking should factor in install count / usage.

![image](https://user-images.githubusercontent.com/173559/53766488-c352c780-3e87-11e9-8e70-e935ecc2e77b.png)

See Twitter thread, https://mobile.twitter.com/bslobodin/status/1102693377886216198

**Comment by bslobodin** [comment] 2019-03-04 22:25
Could it be as simple as [README](https://github.com/sdras/night-owl-vscode-theme/blob/master/README.md#installation) needing to be updated to search for something else, like `night-owl`, which is the name [specified for the package](https://github.com/sdras/night-owl-vscode-theme/blob/f383bdbeabb54b04584d009af1e8acab2c868a95/package.json#L2)?

I noticed `night-owl-vscode-theme` isn't a thing that appears in the name, or keywords, only appearing as [part of the url](https://github.com/sdras/night-owl-vscode-theme/blob/f383bdbeabb54b04584d009af1e8acab2c868a95/package.json#L10).

**Comment by usernamehw** [comment] 2019-03-05 02:30
duplicate of #42890 ?

**Comment by kesane-msft** [comment] 2019-03-05 10:43
We do factor in install count and rating of the extension while returning the search results from the Marketplace. However that comes into picture when the search term is part of the extension display name. In this case whenever we use `night-owl-vscode-theme` SQL Full Text Search (FTS) doesn't find the `vscode` and `theme` words in the display name and hence the install count / rating calculations don't kick in.

I was interested in understanding why the term `night-owl-vscode-theme` was used for searching for extensions, as against `night owl`? Reason being we are onboarding to use Azure Search in the Marketplace and we understanding the use cases / scenarios will help us tweak our search indexes to give better / expected search results.

**Comment by bslobodin** [comment] 2019-03-06 13:58
@kesane-msft am wondering that myself, in retrospect, as I could only find that term in the README, and not in the package itself, hence https://github.com/sdras/night-owl-vscode-theme/pull/173.

**Comment by kesane-msft** [comment] 2019-03-07 04:06
@bslobodin , got it. Thanks! I was wondering if it had anything to do with the github repo name. :)

**Comment by isidorn** [comment] 2021-08-19 15:15
Upstream issue https://github.com/microsoft/vsmarketplace/issues/154

**Closed** 2022-06-08 12:18 UTC
Labels: upstream, marketplace, upstream-issue-linked
