### ISSUE TITLE
[Terminal] Tabs for project

### ISSUE THREAD

**Issue by youra-halloween** [microsoft/vscode#112356] opened 2020-12-12 10:07 UTC
Hi!
Sometimes I accumulate 10 open terminals for 2-3 projects. It would be nice to add open windows at the bottom of the terminal.
![image](https://user-images.githubusercontent.com/5162766/101981031-ac135180-3c8b-11eb-946b-4542ffca454b.png)

**Comment by septatrix** [comment] 2020-12-12 15:49
Duplicate of #10546?

**Comment by YouraHalloween** [comment] 2020-12-12 18:06
> Duplicate of #10546?

Does not look like it.
I did not mean terminal division. And so that the running terminals are displayed as tabs with the name of the project. Currently running terminals are visible only in the combo box. It is not very convenient when several work projects are at hand. You don't notice how you launch several terminals on the same project.

**Closed** 2021-02-14 02:38 UTC
Labels: feature-request, integrated-terminal
