### ISSUE TITLE
HTML files and format code with tabs

### ISSUE THREAD

**Issue by dcoferraz** [Microsoft/vscode#13993] opened 2016-10-19 11:09 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a HTML file and define this `.vscode/settings.json`

`{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.renderWhitespace": "all"
}`

2. Auto format ALWAYS changes indentation to Tabs, even when choosing to spaces.

**Comment by johan13** [comment] 2016-10-19 20:40
The bug is reproducible on VSCode 1.6.1 on Mac OS X. The toolbar says indentation is done with 4 spaces and when typing that setting is respected, but when clicking "Format Code" the indentation is replaced with tabs. I have only observed this with HTML files.

**Comment by aeschli** [comment] 2016-10-19 21:06
duplicate of #13563

**Closed by aeschli** 2016-10-19 21:06 UTC
