### ISSUE TITLE
Installing extensions problem version 1.3.0

### ISSUE THREAD

**Issue by ram-you** [Microsoft/vscode#8923] opened 2016-07-08 09:53 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.13.0-37-generic

Steps to Reproduce:

1.Can't install extensions: nothing happened when I click on Install

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:06
This worked for me:

- zipped & wiped out ./vscode in home
- run ./code --verbose from VSCode installation bin path
- extensions were available and responsive to install
- installed one
- following runs without verbose were OK

HTH

-- Roberto

**Comment by matej-marcisovsky** [comment] 2016-07-08 10:26
Same problem here, running with verbose did not help.

**Comment by belstgut** [comment] 2016-07-08 10:31
Can reproduce. Install button does nothing.

+ vscode 1.3.0
+ Linux 4.6.3-1-ARCH

**Comment by matej-marcisovsky** [comment] 2016-07-08 10:37
Also before wiping out ./vscode in home directory extensions manager showed no installed extensions but extensions were still available - commands worked etc.

**Comment by gudvinr** [comment] 2016-07-08 10:39
Duplicate of #8859

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:42
Do not use DEBs. They split **everywhere** and taint your system.
Use the zip one.
That way you can have multiple versions as well.

**Comment by joaomoreno** [comment] 2016-07-08 11:48
Closing as duplicate.

**Closed by joaomoreno** 2016-07-08 11:48 UTC
