### ISSUE TITLE
Bug: no inline word suggestions for Markdown

### ISSUE THREAD

**Issue by j-lakeman** [microsoft/vscode#202341] opened 2024-01-12 13:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Debian Sid

Steps to Reproduce:

1. have the settings below
2. no inline suggestions are shown, unlike for e.g. LaTeX files

Related settings:

```json
"editor.quickSuggestions": {
			"other": "inline",
			"comments": "inline",
			"strings": "inline"
		},
"editor.suggest.shareSuggestSelections": true,
"editor.suggestSelection": "recentlyUsedByPrefix",
```

**Comment by mjbvz** [comment] 2024-01-12 16:59
Duplicate of #174974

**Closed by mjbvz** 2024-01-12 16:59 UTC
