### ISSUE TITLE
Stage selected ranges messes with enconding/bom

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#125719] opened 2021-06-08 04:44 UTC
When I use vscode to stage lines it messes with encoding (or maybe bom?)
When I do it using git gui it is ok

using vscode
![1](https://user-images.githubusercontent.com/56554900/121124238-04439e80-c83e-11eb-8e45-55355bef7b35.gif)

using git gui
![2](https://user-images.githubusercontent.com/56554900/121124249-0b6aac80-c83e-11eb-94a7-230041d43f0d.gif)

using vscode to stage the whole file is ok however
![3](https://user-images.githubusercontent.com/56554900/121124497-7916d880-c83e-11eb-926a-daa3e658fcf7.gif)

**Comment by lramos15** [comment] 2021-10-21 17:39
Closing due to being duplicate of other issues and a ghost account

**Closed by lramos15** 2021-10-21 17:39 UTC
