### ISSUE TITLE
Update spdlog

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#121513] opened 2021-04-16 21:29 UTC
**Current issue**

We're using a very outdated version of spdlog. It's probably not what's causing freezing when enabling reuse, so I moved this issue from a bug to a debt issue.

**Original issue**

Attaching some logs displaying backtraces:

[mainlog.log](https://github.com/microsoft/vscode/files/6327949/mainlog.log)
[ptylog.log](https://github.com/microsoft/vscode/files/6327950/ptylog.log)
[sharedlog.log](https://github.com/microsoft/vscode/files/6327951/sharedlog.log)
[wbenchlog.log](https://github.com/microsoft/vscode/files/6327952/wbenchlog.log)

This is with process reuse enabled on a Mac.

**Comment by deepak1556** [comment] 2021-04-17 03:58
very likely duplicate of https://github.com/microsoft/vscode/issues/103124, at that time spdlog seemed like a culprit and we wanted to update it to a newer version but didn't get to it. Also we don't have spdlog in the renderer anymore, but to rule its effect out

1) Compare the thread states
2) Update spdlog dep to latest https://github.com/microsoft/node-spdlog

**Comment by rzhao271** [comment] 2021-04-19 19:35
@deepak1556 thanks for the hint, there.
I kept looking in the non-spdlog threads, and though I saw that several threads were waiting, including potentially the spdlog ones, I didn't think to look into them for some reason.
The threads that I did look into didn't show anything; I only learned that one of them was requesting a font.

**Comment by rzhao271** [comment] 2021-04-23 16:31
Updating this to a debt task, because even after commenting out spdlog while testing #121513, I still see freezing at times. I wouldn't be surprised if the freezing came from the interaction between the render process and extension host.

**Closed** 2021-05-11 14:29 UTC
Labels: debt, sandbox
