### ISSUE TITLE
After update to 1.24.0 "go definition"  in JS stop working

### ISSUE THREAD

**Issue by AnatolyKovalenko** [Microsoft/vscode#51694] opened 2018-06-12 12:55 UTC
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.5 
- Language: JS

Steps to Reproduce:
1. After update VSCode 1.23.0 to 1.24.0 "go to definition" in JS stopped working.

All extensions removed and reinstall VSCode.
If remove node_modules all be good.
If language TS all be good.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by whhhooop** [comment] 2018-06-12 14:36
Check the Typescript logs. Might be the same problem as in [#51626](https://github.com/Microsoft/vscode/issues/51626)

**Comment by AnatolyKovalenko** [comment] 2018-06-12 15:32
@whhhooop Thx, but it not my case. Not have errors, just not works.

**Comment by mjbvz** [comment] 2018-06-12 16:49
Please share some example code or small example project

**Comment by zepster** [comment] 2018-06-13 06:48
example [gif](https://www.dropbox.com/s/wbdbujljt139uxc/gotodef.gif?dl=0)

**Comment by KovalenkoA** [comment] 2018-06-13 07:38
@mjbvz view @zepster gif same problem

**Comment by AnatolyKovalenko** [comment] 2018-06-13 07:40
@mjbvz view @zepster gif same problem

**Comment by jrieken** [comment] 2018-06-13 13:38
same as https://github.com/Microsoft/vscode/issues/51349

**Comment by mjbvz** [comment] 2018-06-13 18:57
Please share small piece of example code that demonstrates this problem as text

**Comment by AnatolyKovalenko** [comment] 2018-06-14 09:46
@mjbvz If i CMD + CLICK  "test()" reference not work.
<img width="529" alt="2018-06-14 12 40 41" src="https://user-images.githubusercontent.com/16515651/41404613-57ffd95e-6fd0-11e8-9b2f-b2a68a0ce691.png">

**Comment by mjbvz** [comment] 2018-06-14 23:29
What happens when you click on it? Do you see something like this:

![screen shot 2018-06-14 at 4 29 09 pm](https://user-images.githubusercontent.com/12821956/41443162-195acf7c-6ff0-11e8-8c0f-6e640eb6b62a.png)

**Comment by Kerumen** [comment] 2018-06-15 07:50
I have the same problem. Do you need some help to repro / fix it? :)

**Comment by tempora-mutantur** [comment] 2018-06-16 18:47
@mjbvz Is this behaviour expected? And after the 1.24 update the "vscode.executeDefinitionProvider" vscode command leads to this behaviour. Is it ok? I can't see any difference between this new "Go to Definition" and the "Peek Definition" commands.

**Comment by mjbvz** [comment] 2018-06-18 15:42
No, it's https://github.com/Microsoft/TypeScript/issues/24861

@AnatolyKovalenko Is this what you are seeing?

**Comment by Kerumen** [comment] 2018-06-20 08:11
Note: I don't have the problem on insiders.

**Comment by mjbvz** [comment] 2018-06-25 20:43
Closing this issue as a possible duplicate of Microsoft/TypeScript#24861 or fixed in insiders

**Closed by mjbvz** 2018-06-25 20:43 UTC
Labels: needs more info

**Comment by AnatolyKovalenko** [comment] 2018-07-04 11:14
@mjbvz This problem not fixed!
Go definition not work in pure .js files !!!
If i CMD + click, nothing happens.
Microsoft/TypeScript#24861  not help me, that not my problem!

**Comment by AnatolyKovalenko** [comment] 2018-07-04 13:59
@Kerumen You know how to fix it ? =)
