### ISSUE TITLE
Debugging Stop

### ISSUE THREAD

**Issue by huanhexiao** [Microsoft/vscode#65057] opened 2018-12-14 08:18 UTC
Issue Type: <b>Bug</b>

I just update code to the latest version,  any debugging stops with this msg:
"Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object".
I use code under Xubuntu

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2402)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (2.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|0.0.9
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.0
cpptools|ms-|0.20.1
vscode-icons|rob|7.28.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by huanhexiao** [comment] 2018-12-14 08:34
How to check it 
You mean it may be covered by an old version of code?
No!

**Comment by mjbvz** [comment] 2018-12-14 19:38
Duplicate of #65047

**Closed by mjbvz** 2018-12-14 19:38 UTC
Labels: new release
