### ISSUE TITLE
User account to save editor preferences

### ISSUE THREAD

**Issue by radixzz** [Microsoft/vscode#33688] opened 2017-09-01 16:08 UTC
It would be nice to load and save editor preferences from an online account so config files stay on the cloud?. Kind of what chrome does... huge benefits when working on multiple devices on a daily basis.

Not sure if asking for a microsoft account is a good idea though.

**Comment by seanmcbreen** [comment] 2017-09-02 05:33
This is something we are considering in the future - but for now the best solution is:

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

Let us know is that's not sufficient for now.

**Comment by xiaotan0305** [comment] 2017-09-08 07:25
Very urgent needs, home computers need office computer synchronization settings and plugins.

**Comment by yume-chan** [comment] 2017-09-25 05:01
Duplicate of #2743.

**Comment by shanalikhan** [comment] 2017-11-04 07:31
@seanmcbreen do you think this feature should be a part of Code to do upload / download to GitHub Gist and manage other things.
What i suggest provide authors a way to get all those files using API and let authors use those information to push like my settings Sync (github gist) or SVN , GIT , OneDrive and other things
And let them manage this thing.

**Closed** 2017-11-30 02:28 UTC
Labels: *duplicate, config, feature-request
