### ISSUE TITLE
Workbench Appearance color theme keeps being overridden

### ISSUE THREAD

**Issue by noelrappin** [microsoft/vscode#105102] opened 2020-08-20 19:25 UTC
- VSCode Version: 1.48.1
- OS Version: Mac 10.15.6

Steps to Reproduce:

1. In Settings, set a "Preferred Dark Color Theme", a "Preferred Light Color Theme"
2. Set the "Color Theme" to the same as the "Preferred Light Color Theme"
3. Have  'window.autoDetectColorScheme' enabled
4. Restart VS Code or open any new window

The Workbench Color Theme will be reset to Default Light+ and that theme will be re-adapted as part of the restart process.

Does this issue occur when all extensions are disabled?: No

But I'm not sure which extension is causing this.

**Comment by noelrappin** [comment] 2020-08-20 19:27
This might be related to #102795?

**Comment by IllusionMH** [comment] 2020-08-20 23:50
Looks more like duplicate of #91231

**Comment by noelrappin** [comment] 2020-08-21 00:33
Maybe, but it's not clear to me that the other issue is actually changing the theme on already open windows if I open a new window, which is the behavior that I'm seeing.

**Comment by aeschli** [comment] 2020-09-01 20:01
It's a bug. The preferred theme should only be applied when OS color scheme is detected.
That's either when the the scheme change event happens while VSCode is open, or when we detect a scheme change when the window is opened. For that we remember the last seen scheme.

**Closed** 2020-09-01 20:01 UTC
Labels: bug, editor-theming

**Comment by aeschli** [comment] 2020-09-03 15:10
To verify (on Windows or Mac):
- Have 'window.autoDetectColorScheme' enabled and set a "Preferred Dark Color Theme", a "Preferred Light Color Theme"
- switch the OS color scheme (for dark to light or vice versa). Verify that the theme in VSCode changes to one of the preferred themes
- use the theme picker and change to any other theme
- restart VSCode: Verify that no theme switch happens
- close VSCode, switch the OS color scheme, start VS Code: verify that the theme in VSCode changes.
