### ISSUE TITLE
A column of a tab doesn't match

### ISSUE THREAD

**Issue by lettucejp** [Microsoft/vscode#10196] opened 2016-08-05 14:17 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 3.16.0-4-amd64

Steps to Reproduce:
1. "hello[tab-code]world"
2. "ハロー[tab-code]世界"
   A column of a tab doesn't match

**Comment by alexandrudima** [comment] 2017-09-27 15:05
Wide characters are not considered when painting tabs.

**Comment by yh1224** [comment] 2018-03-04 12:24
This issue is also fixed by #44259.

**Comment by alexandrudima** [comment] 2018-03-05 13:10
Duplicate of #22832

**Closed by alexandrudima** 2018-03-05 13:10 UTC
Labels: editor-rendering, feature-request
