### ISSUE TITLE
Don't show ext getting started page if installed via settings sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137525] opened 2021-11-19 15:45 UTC
Setting up new computer I log into settings sync which installs Luna Paint and it shows the getting started page:

![image](https://user-images.githubusercontent.com/2193314/142650581-84ea03b6-6425-40e8-b339-1192c3934ebe.png)

We shouldn't be automatically showing the new getting started if the install was triggered by sync imo.

**Comment by JacksonKearl** [comment] 2021-12-02 02:32
Hm... we have code to protect against that but there may be a race condition whereby the synced state representing the set of previously auto-opened walkthroughs state isn't available at the time the extension gets installed.

**Comment by digitarald** [comment] 2022-11-11 22:33
This also seems to happen a lot with Codespaces, confirmed by @burkeholland and others.

**Comment by lramos15** [comment] 2022-11-14 13:17
@Tyriar Do you have any suggestions for debugging setting sync related issues like this? I've never had to work with a bug caused by a race condition so I'm not sure. Do I enable sync in OSS and just keep clearing my data directory?

**Comment by sandy081** [comment] 2022-11-14 14:05
@lramos15 Please feel free to ping me on Slack and we can sync offline.

**Comment by bhavyaus** [comment] 2022-12-28 18:32
This should be fixed with https://github.com/microsoft/vscode/pull/170108

Related https://github.com/microsoft/vscode/issues/137526.

**Closed by bhavyaus** 2022-12-28 18:32 UTC
Labels: bug, getting-started

**Comment by andreamah** [comment] 2023-01-26 17:52
@bhavyaus @lramos15 are there verif steps to trigger the race condition? I tested on codespaces and didn't see the welcome page for installed extensions by settings sync.

**Comment by lramos15** [comment] 2023-01-26 18:26
@andreamah That should be enough so I'll mark as verified as I also haven't seen it in a bit on newly synced machines
