### ISSUE TITLE
Getting error while launching "npm" install task from launch.json.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4987] opened 2016-04-05 23:03 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: WIndows10

Steps to Reproduce:

1. Launch app and open any folder which contains .ts file.
2. Install eslint extension and restart app.
3. Configure task by generating tasks.json for npm.
4. Update install task as below:
                 {
			"taskName": "install",
			"args": ["install","-g","eslint"]
		},
5. Set node debugger and generate launch.json and set prelaunchtask as "install".
6. Start debugging and verify output.

Actual:
1. Getting error " Errors detected while running the preLaunchTask 'install'.
2. There is no error message on output window.
Expected: When I run the command "npm install -g eslint" from command prompt under the workspace folder then I didn't get any error .
![image](https://cloud.githubusercontent.com/assets/17735796/14300760/7ef27e2c-fb47-11e5-8da2-44e04bca4995.png)

**Comment by dbaeumer** [comment] 2016-04-07 08:35
@isidorn I move this to you since it is prelaunch related. Is this an error reported by the task or is this message referring to the error count in the status bar ?

**Comment by isidorn** [comment] 2016-04-11 12:24
Well this is the current design limitation of our approach. After a prelaunchTask is finished we check the global error count, if > 0 then we abort.
The task framework is not giving me a correlation between a task run and the errors.
Due to this limitation we have a 'Continue' action in the message box

Closing as designed

**Closed by isidorn** 2016-04-11 12:24 UTC
Labels: v-test

**Comment by dbaeumer** [comment] 2016-04-13 07:17
@isidorn I think that could be made more clear with a better message. Errors detected sounds a little harsh. I too had the impression that the task failed with errors. What's about saying something like: 'Build errors have been detected during preLaunchTask. Do you want to debug anyways?

**Comment by isidorn** [comment] 2016-04-13 07:54
@dbaeumer agree. I have improved the wording.
