### ISSUE TITLE
wsl can not input chinese 

### ISSUE THREAD

**Issue by smxyzb** [microsoft/vscode#117563] opened 2021-02-24 10:47 UTC
Issue Type: <b>Bug</b>

wsl can not input chinese 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.10GB free)|
|Process Argv|--crash-reporter-id ef6ded06-93f0-4794-962b-12bab53f35ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
le5le-topology-plugin|Als|0.0.1
npm-intellisense|chr|1.3.1
vscode-wxml|cod|0.1.9
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
vscode-new-file|dku|4.0.2
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
windows-explorer-context-menu|ele|2.1.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
path-autocomplete|ion|1.17.1
markdown-formatter|mer|0.8.9
vscode-language-pack-zh-hans|MS-|1.53.2
sublime-keybindings|ms-|4.0.7
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.1.0
view-in-browser|qin|0.0.5
vue-vscode-snippets|sdr|2.2.0
html5-boilerplate|sid|1.1.1
win-opacity|ska|1.1.4
code-autocomplete|svi|1.2.1
highlight-matching-tag|vin|0.10.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30260844

```

</details>

**Comment by rzhao271** [comment] 2021-02-24 17:54
Can you paste a screenshot, or steps to help us reproduce the problem?
For example, are you trying to type into the integrated terminal? (In which case it would be #115814).

**Comment by meganrogge** [comment] 2021-02-26 19:20
Duplicate of #115814

**Closed** 2021-02-26 19:21 UTC
Labels: *duplicate, bug, integrated-terminal, needs more info
