### ISSUE TITLE
New release shows incorrect release notes upon opening (v1.22.0 shows v1.21.1)

### ISSUE THREAD

**Issue by ssilverman** [Microsoft/vscode#47613] opened 2018-04-10 20:31 UTC
- VSCode Version: 1.22.0
- OS Version: OSX 10.13.4

I just upgraded to v1.22.0 but when the app opened the first time, it showed release notes for v1.21.1.

**Comment by mjbvz** [comment] 2018-04-10 21:24
Duplicate of #47256 . Already fixed in 1.22.1

**Closed by mjbvz** 2018-04-10 21:24 UTC
