### ISSUE TITLE
Markdown preview window shrinks when zooming in with 'Cmd + ='.

### ISSUE THREAD

**Issue by ghjang** [Microsoft/vscode#22458] opened 2017-03-11 20:01 UTC
- VSCode Version: 1.10.2
- OS Version: macOS Sierra 10.12.3

I've tested it on a fresh VM. No extensions were installed.

Steps to Reproduce:

1. make a .md file.
2. 'Shift + Cmd + v' to preview markdown file.
3. Hit 'Cmd + =' several times to zoom in. Following screenshots show the window shrinking problem:

![screen_shot_00](https://cloud.githubusercontent.com/assets/13075164/23826424/2a705f8c-06df-11e7-82b2-3bcd9ba4b307.png)
![screen_shot_01](https://cloud.githubusercontent.com/assets/13075164/23826426/335282ec-06df-11e7-91b1-1ace01a56319.png)
![screen_shot_02](https://cloud.githubusercontent.com/assets/13075164/23826428/3a4f6a10-06df-11e7-8f1b-2cceb86ab78d.png)

I've found a similar issue on the StackOverflow: <https://stackoverflow.com/questions/42172373/when-the-zoom-increses-ctrl-the-markdown-preview-width-shrinks>

But, the answer on the issue does not solve the problem.

**Comment by mjbvz** [comment] 2017-03-12 02:23
Duplicate of #5745

**Closed by mjbvz** 2017-03-12 02:23 UTC
Labels: duplicate, markdown, webview
