### ISSUE TITLE
Editor's scroll width does not automatically shrink

### ISSUE THREAD

**Issue by Akeepers** [microsoft/vscode#47709] opened 2018-04-12 03:20 UTC
Issue Type: <b>Bug</b>

After selecting all occurrances and press "enter", the editor's width is not adjusted accordingly.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|15.91GB (5.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\work\data\From Xiao\DataFromProductTeam\maalam\MVP - file.csv|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
language-kuka-krl|d4n|1.4.1
gc-excelviewer|Gra|2.0.20
vscode-github|Kni|0.27.1
python|ms-|2018.3.1
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
txt-syntax|xsh|0.0.3

</details>
Reproduces only with extensions

**Comment by Akeepers** [comment] 2018-04-13 09:37
There is a long content on one line with some similar words. I I divided it into several lines based on the word. After selecting all occurrances and press "enter", It works but the editor's width is not adjusted accordingly. It's like I deleted everything.

**Comment by alexandrudima** [comment] 2018-04-13 13:43
@Akeepers I cannot reproduce anything wrong. Here I am:
* having a long line with similar words
* selecting similar words
* pressing enter 
![kapture 2018-04-13 at 15 42 29](https://user-images.githubusercontent.com/5047891/38738027-574ff248-3f31-11e8-93c5-fad9e5edf085.gif)

**Comment by Akeepers** [comment] 2018-04-14 12:31
You can try a longer sentences.  In my case, there are about 6000 words in one line. And it‘s divided into 93 lines.

**Comment by alexandrudima** [comment] 2018-04-16 13:39
I have tried with a longer sentence. I believe you are referring to the fact that the **scroll width** of the editor does not shrink.

![kapture 2018-04-16 at 15 37 39](https://user-images.githubusercontent.com/5047891/38812312-4554513a-418c-11e8-88f8-7f81158536e0.gif)

**Comment by Akeepers** [comment] 2018-04-23 11:29
Please see the gif. And my version is 1.22.1.

![bug report](https://user-images.githubusercontent.com/22610351/39124050-8c971924-472c-11e8-81ab-7416df3f34cc.gif)

**Comment by alexandrudima** [comment] 2019-10-23 17:53
Duplicate of #13516

**Closed by alexandrudima** 2019-10-23 17:53 UTC
Labels: editor-rendering, feature-request
