### ISSUE TITLE
Clearing terminal keeps find annotations

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#146010] opened 2022-03-24 22:53 UTC
Testing https://github.com/microsoft/vscode/issues/145920

I ran clear while I had the find widget open, and the find result highlighting + sidebar annotations didn't update.
I have shell integration on.

**Comment by meganrogge** [comment] 2022-03-25 14:27
They don't for the current line, which is expected. Can you attach a gif? They're getting cleared for me. Also are you on windows?

**Comment by Tyriar** [comment] 2022-03-25 14:37
@meganrogge after `clear` on Windows:

![image](https://user-images.githubusercontent.com/2193314/160141815-fe2ffd39-1d38-4437-b5c5-e3d9ae826c01.png)

**Comment by meganrogge** [comment] 2022-03-25 14:42
interesting - on mac:
https://user-images.githubusercontent.com/29464607/160142736-32add2d0-53ec-4662-a635-8026b823d10d.mov

**Comment by meganrogge** [comment] 2022-04-18 19:10
I also can't reproduce this on windows. @rzhao271 are you still able to?

**Comment by rzhao271** [comment] 2022-04-18 21:45
I'm not able to repro the exact bug. I still do see the scroll bar annotations stay even after I clear a query, though.
1. Open the terminal find widget.
2. Search for something that has results (like a single letter).
3. Clear the query.
4. :bug: The scroll bar annotations stay.

![A screenshot showing the annotations stay after clearing the find widget](https://user-images.githubusercontent.com/7199958/163882585-4db1a159-a804-418f-b8d5-71067f7a04fd.PNG)

**Comment by meganrogge** [comment] 2022-04-19 01:18
I've seen that too. For clarity, closing this and will make a new issue for that one.

**Closed by meganrogge** 2022-04-19 01:18 UTC
Labels: bug, windows, terminal-find
