### ISSUE TITLE
Using jsconfig.json and custom .d.ts file with non js extensions

### ISSUE THREAD

**Issue by georgerobo** [Microsoft/vscode#37772] opened 2017-11-07 12:50 UTC
Hello!

I have a JSConfig.json file in my working directory containing the following:
```json
{
    "compilerOptions": {
        "checkJs": true,
        "lib": ["es6"]
    }
}
```

I also have a custom 'globals.d.ts' file which contains the data I want for the autocomplete options. This works perfectly for .js file extensions, but it seems to ignore it for custom file extensions I associated with the javascript language. The extensions added to the settings like this:
"files.associations": {
        "*.sample": "javascript"
    },

Should also use these files. 

At the moment, the custom file extensions I have just use the standard es6 library for Autocomplete, rather than the file in my working directory (which .js files use).

**Comment by mjbvz** [comment] 2017-11-08 18:45
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10939

We currently support single-file intellisense for JavaScript code with a custom file extension, but we do not support module resolution and project wide intellisense. That is why your `jsconfig.json` has no effect.

This has been won't fixed upstream and there's not much we can do on the VS Code side to work around this. I recommend always using a `*.js` extension for these cases

**Closed by mjbvz** 2017-11-08 18:45 UTC
Labels: duplicate, javascript
