### ISSUE TITLE
Cannot open two folders with the same name but different capitalization simultaneously

### ISSUE THREAD

**Issue by Saydemr** [microsoft/vscode#201457] opened 2023-12-24 12:49 UTC
Type: <b>Bug</b>

1. create two folders with the same string but different capitalization
mkdir ns-eof
mkdir NS-EOF
2. Open one of the folder on vscode
code --disable-extensions ns-eof
3. Try to open the other
code --disable-extensions NS-EOF

Actual Result
VSCode switches to earlier window.

Expected result
VSCode opens the new folder on a new window.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.79GB free)|
|Process Argv|--disable-extensions --folder-uri=vscode-remote://wsl+Ubuntu/home/username/ns-eof --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|Memory (System)|11.68GB (10.59GB free)|
|VM|0%|
</details>Extensions disabled

**Comment by aeschli** [comment] 2024-01-08 10:48
Duplicate of https://github.com/microsoft/vscode/issues/123421

**Closed by aeschli** 2024-01-08 10:48 UTC
