### ISSUE TITLE
Create task terminal from existing instances. 

### ISSUE THREAD

**Issue by cuichenli** [microsoft/vscode#73581] opened 2019-05-10 13:57 UTC
Is that possible to run a task through an already existing terminal instance? 

My build script aims to run specific preparation at its first run, which is to add some environment variable. It should be a one-time thing but currently, every time I run the task, this preparation step would be triggered. I found one similar case [here](https://stackoverflow.com/questions/48655347/run-same-instance-of-terminal-with-build-task-in-vs-code). Thanks!

**Comment by alexr00** [comment] 2019-05-15 17:23
This does not currently exist. However, you can set environment variables using `options` attribute https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

**Comment by alexr00** [comment] 2019-10-08 09:19
duplicate of https://github.com/microsoft/vscode/issues/78319 since that would provided a solution to the problem.

**Closed by alexr00** 2019-10-08 09:19 UTC
Labels: feature-request, tasks
