### ISSUE TITLE
Integration tests haven't been printing correctly for a while

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#77657] opened 2019-07-19 16:55 UTC
It's printing a string[] instead of the entries within the array. Happens on Linux and mac (not sure Windows)

![image](https://user-images.githubusercontent.com/2193314/61551858-2f833180-aa0b-11e9-8221-582d7e39b84b.png)
![image](https://user-images.githubusercontent.com/2193314/61551872-3ca02080-aa0b-11e9-92d0-d30045587adc.png)

**Comment by mjbvz** [comment] 2019-07-20 00:13
Duplicate of #77550

**Closed by mjbvz** 2019-07-20 00:13 UTC
Labels: bug, integration-test
