### ISSUE TITLE
//@ts-check can not support vue file

### ISSUE THREAD

**Issue by Moerj** [Microsoft/vscode#26165] opened 2017-05-07 18:07 UTC
- VSCode Version:1.12.1
- OS Version:macOS sierra

Steps to Reproduce:

When I use //@ts-check for *.vue files. It not supports.
Variable can not be recognized correctly.

Like this:

![qq20170508-020234 2x](https://cloud.githubusercontent.com/assets/13795438/25783666/ed2f0930-3392-11e7-8b6a-a21c95078b85.jpg)

How can I use ts-check on vue?

**Comment by mjbvz** [comment] 2017-05-08 23:25
What vue extension are you using? In current insiders builds this should now work if you just set vue files to use the html language mode, but a vue extension may have to be updated to support this

**Comment by Moerj** [comment] 2017-05-09 10:06
I am using  vetur

**Comment by octref** [comment] 2017-05-09 15:50
@mjbvz This wouldn't be resolved until [contextual typing](https://github.com/Microsoft/TypeScript/pull/14141) is added to `vue.d.ts`.

`active` is in the object returned by `this.data`. With vue's current type declaration the return result won't be used to contextually type `this`.

More details here: https://github.com/octref/vetur/pull/94#issuecomment-299935258

**Comment by octref** [comment] 2017-05-09 15:53
@mjbvz So I think it's ok to close this as it's really a vue / TS issue. `// @check-ts` works fine in vetur.

**Comment by mjbvz** [comment] 2017-05-10 05:23
Thanks @octref! Closing as caused by extension. Please follow up on the Vetur repo

**Closed by mjbvz** 2017-05-10 05:23 UTC
Labels: caused-by-extension, javascript, needs more info
