### ISSUE TITLE
Search doesn't exclude gitignored files

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#45487] opened 2018-03-10 20:00 UTC
I just encountered a situation where "Use exclude settings and ignore files" is not honored:

![image](https://user-images.githubusercontent.com/101152/37246213-74768f40-24a5-11e8-8d5d-2f9ee56dfe4b.png)

This is strange because it usually works fine for me. Also, it has _some_ effect because if I unclick the gear icon, I get different results:

![image](https://user-images.githubusercontent.com/101152/37246230-ca3cfdd8-24a5-11e8-9968-c293963cff6b.png)

I do not quite understand. I've tried in both current version and insiders, it behaves the same in both.

My main VSCode version:

```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```

My insiders version:

```
Version 1.22.0-insider
Commit 3817c899cae312e0e989da8bfbc61308cfbf45f1
Date 2018-03-09T05:15:56.454Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by borekb** [comment] 2018-03-27 08:55
Confirmed by a colleague on a Mac, VSCode 1.21.1.

**Comment by roblourens** [comment] 2018-03-27 15:11
Any clue what's different about the files in .cache that are correctly excluded vs the ones that aren't? Is it the same set every time?

**Comment by borekb** [comment] 2018-03-27 15:37
I found out what is causing it: the fact that I want to search in a specific folder in our monorepo (the folder is `website` in the screenshots above). If "files to include" is empty, the problem goes away.

Our monorepo has a structure like this:

```
- app1
  - .gitignore
- app2
  - .gitignore
- website
  - .gitignore
```

My goal is to search inside `website` but still apply the exclude rules in `websites/.gitignore`.

**Comment by roblourens** [comment] 2018-03-27 16:32
Seems that ripgrep doesn't look at child .gitignore files as it searches. Does using `./website` instead work?

**Comment by borekb** [comment] 2018-03-27 17:45
Yes although I'm not sure the results are as expected. I created this repo so that you can try yourself: https://github.com/borekb/vscode-search-issue-45487

Some screenshots:

---

This is how the structure looks:

![image](https://user-images.githubusercontent.com/101152/37984354-61da6d1c-31f6-11e8-9822-cb5ab463e2f0.png)

All four .txt files contain the same thing, a string "hello".

---

Plain search works as expected:

![image](https://user-images.githubusercontent.com/101152/37984433-8bc5a1b4-31f6-11e8-853b-dbd57d2fab41.png)

---

Scoping to just "a" doesn't work:

![image](https://user-images.githubusercontent.com/101152/37984524-c4abd57a-31f6-11e8-815d-fdae4c8aa36e.png)

---

Scoping to "./a" works better but looks differently, for example, the small gray "a" is missing from the search result:

![image](https://user-images.githubusercontent.com/101152/37984580-e88d2b7e-31f6-11e8-8515-17af9485b202.png)

---

Including both folders makes this more apparent, especially compared to the original result:

![image](https://user-images.githubusercontent.com/101152/37984603-fd663aa4-31f6-11e8-87bc-6ae60cf21c66.png) ![image](https://user-images.githubusercontent.com/101152/37984633-1105923a-31f7-11e8-9511-1f8949fc28a8.png)

**Comment by borekb** [comment] 2018-03-27 17:50
Thanks for the tip about `./something` by the way, it's much better than getting `.gitignored` results.

**Comment by roblourens** [comment] 2018-03-27 18:19
Actually it's not what I said before, this is about the include pattern overriding the gitignore file, which ripgrep does.

The result format is what I expect - that syntax roots the search in that folder, rather than searching from the open folder, with the given folder name as `**/a/**`. That also causes it to use the multi-folder result format.

Will have to play with this some more, I don't think glob patterns should override the gitignore file.

**Comment by jameshulse** [comment] 2018-05-01 09:38
In VSCode 1.22.2 the issue which you originally mentioned does exist @roblourens. Search is finding results in files which should be ignored by **sub** .gitignore files.

It seems that only the root .gitignore is being used and the others are being ignored.

A standard Laravel project contains the structure:
```
/storage
    .gitignore
    /framework
        .gitignore
        /cache
            .gitignore                 <- ignores '*'
            /data                        <- should be ignored
```
Everything in the `/storage/framework/cache/data/` folder should be ignored by its most local .gitignore, but results from this folder are being returned.

As a note, the project explorer itself is correctly dimming the ignored `data` folder.

**Comment by roblourens** [comment] 2018-05-01 21:44
Are you sure @jameshulse? Like @borekb said, 

> Plain search works as expected 

And that's what I saw. So I don't think child .gitignore files are ignored entirely. If you have an include pattern, it might override the gitignore file.

**Comment by jameshulse** [comment] 2018-05-02 08:40
Hopefully these screenshots will show the issue. I am searching for some arbitrary text in one of the ignored cache files in my project.

![screen shot 2018-05-02 at 09 31 47](https://user-images.githubusercontent.com/797280/39513482-69da0268-4dec-11e8-98af-5236c8af427e.png)
![screen shot 2018-05-02 at 09 32 09](https://user-images.githubusercontent.com/797280/39513488-6e796f0c-4dec-11e8-9a8e-1a3ea0fa8428.png)

Nothing in the include / exclude patterns box and results are the same whether I have the "Exclude settings" toggle on or off.

The nearest .gitignore simply has:
```
*
!.gitignore
```

Let me know if there is anything else I can provide.

**Comment by roblourens** [comment] 2018-05-03 01:11
It looks like that file was open before you searched - open files can still be searched even when they should be excluded. That's another bug: https://github.com/Microsoft/vscode/issues/31819

**Comment by jameshulse** [comment] 2018-05-03 09:38
Good catch. I think you might be right - I'm not sure how I originally came across the issue now, but I might have had an inclusion string set.

Sorry for the time waste, I really appreciate all your team do on VS Code!

**Comment by ifeltsweet** [comment] 2018-06-29 16:40
I can confirm this is happening in 1.24.1

**Comment by roblourens** [comment] 2018-09-13 19:44
I believe this is actually a dupe of https://github.com/Microsoft/vscode/issues/26574

**Closed by roblourens** 2018-09-13 19:44 UTC
Labels: bug, search
