### ISSUE TITLE
Settings Sync picks up theme change

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#145803] opened 2022-03-22 22:22 UTC
Testing #145616

![image](https://user-images.githubusercontent.com/98423974/159585980-d4edd34e-7ad5-478f-8684-eda68577bcf9.png)

Since you are automatically changing the theme color based on the OS, I don't think this theme change should be synced... otherwise, when I move to another machine where I don't use high contrast, my theme will be overwritten and the high contrast theme will be used and that will be jarring.

This is @TylerLeonhardt's alt account for linux testing

**Comment by TylerLeonhardt** [comment] 2022-03-22 23:08
A symptom of this ... a few times for me this caused Settings Sync merge conflicts when I opened VS Code after switching on high contrast.

**Comment by sandy081** [comment] 2022-03-23 07:04
Settings Sync does not have knowledge about themes and auto switching. I would leave this to the owner of this setting @aeschli

**Comment by aeschli** [comment] 2022-03-23 21:13
Duplicate of https://github.com/microsoft/vscode/issues/124572

**Closed by aeschli** 2022-03-23 21:13 UTC
