### ISSUE TITLE
Performance Report

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#20830] opened 2017-02-17 19:44 UTC
- VSCode Version: <code>Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>3.88GB (1.75GB free)</code>
- Memory (Process): <code>126.34MB working set (126.34MB peak, 109.62MB private, 25.29MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>50%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|3799|
|main|app.isReady => window.loadUrl()|12647|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|24980|
|renderer|require(workbench.main.js)|13897|
|renderer|create extension host => extensions onReady()|29691|
|renderer|restore viewlet|26448|
|renderer|restore editor view state|24677|
|renderer|overall workbench load|37754|
|main + renderer|start => extensions ready|91087|
|main + renderer|start => workbench ready|93568|

---
tested on a laptop, is it fine?

**Comment by bpasero** [comment] 2017-02-19 08:51
@jens1o thanks, those times are terrible. Is this inside a VM?

**Comment by jens1o** [comment] 2017-02-19 09:26
No, it's not. Can I help you with something? @bpasero

**Comment by bpasero** [comment] 2017-02-19 09:46
@jens1o does it reproduce each time you start? are you using some anti virus software that could have an impact?

**Comment by jens1o** [comment] 2017-02-19 09:47
Yes it does, and no, I am not using any AV. How I am able to export the extension list?

**Comment by bpasero** [comment] 2017-02-19 17:06
@jens1o that looks like a major speed increase when running without extensions. you can export a list of your extensions by Help > Report Issue and copying that extension list. Would be interesting to know how many / which ones.

**Comment by jens1o** [comment] 2017-02-19 19:07
Thanks, but that menu item does not work for me. Just nothing happens... I'm frustrated. What am I doing wrong?

**Comment by bpasero** [comment] 2017-02-20 06:14
@jens1o I wonder if your installation is somehow corrupt. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jens1o** [comment] 2017-02-20 14:03
- VSCode Version: <code>Code - Insiders 1.10.0-insider (64801727521592cf5fe64fd911b1efe41b1ea732, 2017-02-20T07:13:27.765Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>3.88GB (1.34GB free)</code>
- Memory (Process): <code>117.18MB working set (117.78MB peak, 92.91MB private, 30.75MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>50%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|40|
|main|app.isReady => window.loadUrl()|727|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1370|
|renderer|require(workbench.main.js)|1461|
|renderer|create extension host => extensions onReady()|2184|
|renderer|restore viewlet|0|
|renderer|restore editor view state|611|
|renderer|overall workbench load|1958|
|main + renderer|start => extensions ready|6015|
|main + renderer|start => workbench ready|5577|

Looks way more better. What did you do?
Is it possible that a corrupt installation slows down the program?

**Comment by bpasero** [comment] 2017-02-20 14:06
@jens1o well for once, you are likely not having any extensions installed in that insiders build. Maybe you start to install them back and watch after each installation if the time is going down considerably?

**Comment by jens1o** [comment] 2017-02-20 14:07
Okey, I'll look. But there are *lots* of extensions... I should shown it to you...

**Comment by bpasero** [comment] 2017-02-20 14:30
@jens1o to be fair, even with 100 installed extensions I would not expect a slowdown like the one you have. Especially since extensions typically get loaded after the window opens.

**Comment by jens1o** [comment] 2017-02-20 14:32
Reinstalled 25% of all extensions. So far nothing special. But when you are having extensions that try to reserve the same keybind (by default) you'll see a slow down.

**Comment by bpasero** [comment] 2017-02-20 14:44
@jens1o how do you notice that? I think you are seeing a warning about the keybinding but I doubt it would cause any slowdown. It must be something else the extension is doing.

**Comment by jens1o** [comment] 2017-02-20 14:53
It takes a moment more to load when you have installed the extension or not. (used a stopwatch to measure this)

Now it begins to run slower, maybe I've caught somebody. I'd seen that the extension "HTML Boilerplate" slows down the startup?(uninstalled)

List until now:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|Bookmarks|alefragnani|0.11.0|
|vscode-color|anseki|0.2.3|
|cdn-list|AryanMann|1.0.0|
|color-info|bierner|0.2.1|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|EditorConfig|EditorConfig|0.3.4|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.2|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.10|
|vscode-firefox-debug|hbenl|0.8.8|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|GitHubIssues|HookyQR|0.1.2|
|composer|ikappas|0.5.0|
|docthis|joelday|0.4.0|
|to-data-uri|kieferrm|0.1.1|
|Go|lukehoban|0.6.53|
|copy-github-url|mattlott|0.1.0|
|font-awesome-codes-html|medzhidov|0.0.4|
|hex-rgba-converter|medzhidov|1.0.3|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-css-peek|pranaygp|1.2.4|
|dark-win16-theme|rbukovansky|0.0.4|
|vscode-hexdump|slevesque|1.1.4|
|vscode-gulp|tanato|0.0.4|
|highlight-trailing-white-spaces|ybaumes|0.0.2|
|intelligence-change-case|zhengxiaoyao0716|1.1.0|

**Comment by bpasero** [comment] 2017-02-20 14:56
@jens1o ok and the startup time is now at what value?

**Comment by jens1o** [comment] 2017-02-20 15:00
I'm getting the values just in the console...
![image](https://cloud.githubusercontent.com/assets/11234139/23130124/95e7395c-f785-11e6-9196-9e098334e082.png)

**Comment by bpasero** [comment] 2017-02-20 15:04
Looks like it. This is super weird because some of the timers are going up (e.g. require...) even though at that time extensions are not even being looked at. 

I notice you seem to be doing a window reload instead of restart, does a clean restart change something?

**Comment by jens1o** [comment] 2017-02-20 15:06
![image](https://cloud.githubusercontent.com/assets/11234139/23130364/75eb57a4-f786-11e6-8a49-8f40bbd4b928.png)
Yes, it does. 😮 I thought it would be the other way around... Since electron itself(and the Chromium Engine) won't need to restart...

**Comment by bpasero** [comment] 2017-02-21 12:04
@jens1o I just went ahead and installed exactly the extensions from https://github.com/Microsoft/vscode/issues/20830#issuecomment-281099165 but do not see any slowdown on my Windows 10 laptop. I wonder if this is dependent on the folder you are opening? does it repro when you open an empty workspace (= no folder)?

**Comment by jens1o** [comment] 2017-02-21 15:22
It doesn't care which folder I open, I don't see any (measurable) difference.

**Comment by bpasero** [comment] 2017-02-21 16:07
@jens1o that is quite a big difference to https://github.com/Microsoft/vscode/issues/20830#issuecomment-281101032 if you have the same extensions installed. Any chance you have some stuff running in the background that interferes from time to time?

**Comment by jens1o** [comment] 2017-02-21 16:52
Well, yes. I have Firefox installed and use it on the second monitor when coding something(because I make Web-Development the most), but this only includes full loaded pages. It only uses a bit more RAM, but not that CPU to be a huge difference.
The websites aren't that expensive(for example YouTube/Twitch...)
![image](https://cloud.githubusercontent.com/assets/11234139/23174889/136ea1e8-f85e-11e6-8caf-a01b20cd7327.png)
That's the current state... But it's just after I've installed the update. Before it, it was really like above. Did you changed anything? Can I help you with something out? Like a CPU Trace?

**Comment by bpasero** [comment] 2017-02-21 16:59
@jens1o you mean did we change anything in Insiders that could have an impact on performance?

**Comment by jens1o** [comment] 2017-02-21 17:04
Yeah, that's what I think. The first start was very fast. I was really surprised.

**Comment by bpasero** [comment] 2017-03-07 14:32
I am closing this and ask people that hit slow performance to run `code-insiders --prof-startup` (from our insiders build: http://code.visualstudio.com/Download#insiders) which now supports to run CPU profiles so that we can have a closer look. Running with this argument will guide you through the process of creating a performance report here.

**Closed by bpasero** 2017-03-07 14:32 UTC
Labels: needs more info, perf

**Comment by jens1o** [comment] 2017-03-07 15:19
And then I'm supposed to do a new issue?

**Comment by bpasero** [comment] 2017-03-07 16:36
Yes!
