### ISSUE TITLE
Can not delete a break point if it's at the last line of code

### ISSUE THREAD

**Issue by uyhung** [Microsoft/vscode#22962] opened 2017-03-21 16:45 UTC
If I set a break point at the last line of code I cannot delete it. My work around is to change where the last line at, for example I press Enter to push down the last line one more new line.

![cannotdeletebreakpoint](https://cloud.githubusercontent.com/assets/1470309/24158980/79a972e2-0e90-11e7-9d75-7d75e7f7bad8.png)

**Comment by isidorn** [comment] 2017-03-21 17:10
If i add a breakpoint on the last line I can nicely delete it.
Are you doing this while debugging, or while not being in a debug session.
Might be dupe of https://github.com/Microsoft/vscode/issues/18126

**Comment by uyhung** [comment] 2017-03-27 06:44
yes you can if you just simply add a break point to the last line and then remove it. Let try add a break point at some code line above the last line, then remove some lines of code between to make that line become the last line then you cannot remove the break point anymore.

**Comment by isidorn** [comment] 2017-03-27 09:27
Works for me. What am I doing differently than you?

![lastbp](https://cloud.githubusercontent.com/assets/1926584/24349753/46de2ae8-12e0-11e7-93b6-28300e395bc6.gif)

**Comment by isidorn** [comment] 2017-04-13 13:02
Closing since the user did not provide more info. Will reopen if I get repro steps

**Closed by isidorn** 2017-04-13 13:02 UTC
Labels: debug, needs more info
