### ISSUE TITLE
Missing icons for extensions after redesign

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode#77488] opened 2019-07-17 00:02 UTC
Version: 1.37.0-insider (user setup)
Commit: 8e0f348413f4f616c23a88ae30030efa85811973
Date: 2019-07-16T05:25:39.655Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18936

![image](https://user-images.githubusercontent.com/13103165/61337677-22b1e280-a83f-11e9-8b6d-c76729535e57.png)

**Comment by misolori** [comment] 2019-07-18 04:31
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed by misolori** 2019-07-18 04:31 UTC
