### ISSUE TITLE
VSCode is not per monitor DPI aware

### ISSUE THREAD

**Issue by ivanz** [Microsoft/vscode#6196] opened 2016-05-08 12:14 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:
1. Connect second monitor and adjust DPI such as the second monitor has different DPI than the main one
2. Drag Vscode window to the second monitor - UI becomes all blurry.

Possibly related to #1896 and also this upstream Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=426656

**Comment by Chococat** [comment] 2016-05-09 10:35
Also happens on VSCode Version: 1.1.0-insider; OS: Windows 10 14332

**Comment by bpasero** [comment] 2016-09-18 07:19
@ivanz @Chococat could you try our latest insider release to see if this issue still reproduces? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by ivanz** [comment] 2016-09-20 14:33
@bpasero Not as far as I can tell. You can easily test this without multiple monitors on Windows by simply changing the size of text etc. As far as I can tell the work is still in progress on the Chromium side [here](https://bugs.chromium.org/p/chromium/issues/detail?id=426656) and is currently available in their dev and canary builds only.

![image](https://cloud.githubusercontent.com/assets/79742/18674515/64e934c4-7f47-11e6-8796-0f6ed28e3c22.png)

**Comment by bpasero** [comment] 2016-09-20 14:54
Ok but good to know they plan for it because that means we will eventually also benefit.

**Comment by bpasero** [comment] 2016-11-21 14:29
@ivanz we recently updated Chrome again to 53 in our insider builds, maybe this improved? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2016-11-22 05:47
Got it, thanks 👍

**Comment by Ciantic** [comment] 2016-11-23 10:17
This is bothering, I'm running Google Chrome 54, and it works perfectly but not the Electron which is running with Chromium 53. I opened issue to Electron https://github.com/electron/electron/issues/8062

**Comment by ibujs** [comment] 2017-01-28 06:09
Electron 1.5 fixes this by updating to Chrome 54.

**Comment by bpasero** [comment] 2017-04-10 17:09
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by ivanz** [comment] 2017-04-10 17:17
I am afraid not. I changed the DPI of one of my monitors and with build from sha `61753c029226f43c12124a75020b5d8b86c60700` and date `2017-04-10T07:15:44.057Z` when I drag across monitors it remains blurry. :(

**Comment by rhyek** [comment] 2017-04-10 17:22
Electron still hasn't resolved this on their end, right? https://github.com/electron/electron/issues/5429

**Comment by bpasero** [comment] 2017-04-10 17:36
True that, would still be happy for more people trying out this new electron release.

**Comment by miparnisari** [comment] 2017-05-18 03:12
@bpasero it does for me :) I have a Surface Book and the Explorer panel used to look super tiny, now it's fine.

**Comment by ivanz** [comment] 2017-05-18 13:12
The default scaling factor ("zoom") is now more sensible out of the box (guess DPI aware) indeed.

**Comment by jnm2** [comment] 2017-05-18 13:54
It's now system DPI aware, but not yet per-monitor DPI aware.

**Comment by CnSimonChan** [comment] 2017-06-02 02:59
Recently I started a test project with Electron, and I found it's now Per-Monitor Aware.

I'm using Electron 1.6.10, Renderer 56.0.2924.87, while VS Code 1.12.2 is using Electron 1.6.6 and same Renderer 56.0.2924.87.

![capture](https://cloud.githubusercontent.com/assets/1330321/26709046/689578fe-4782-11e7-8f65-fa472d26ec66.PNG)

Maybe another upgrade required? It's really annoying.

**Comment by jnm2** [comment] 2017-06-02 03:07
I temporarily have a setup with mixed-DPI screens and it *is* really annoying that VS Code isn't per-monitor DPI aware.

**Comment by wryun** [comment] 2017-07-06 20:49
This is supposedly fixed in Electron 1.6.7: https://github.com/electron/electron/releases/tag/v1.6.7

Enabled per-monitor DPI awareness in the app manifest. https://github.com/electron/electron/pull/8786

**Comment by wryun** [comment] 2017-07-06 20:50
(any chance of updating to the latest 1.6.x in the near term?)

**Comment by bpasero** [comment] 2017-07-07 15:00
Updating to Electron 1.7.x is on the plan for July.

**Comment by kring** [comment] 2017-08-15 05:43
I just found a great workaround for this that might be helpful to others.  You will need a recent build of Windows 10.  Find the shortcut you use to launch Visual Studio Code, right click on it and choose Properties.  Go to the Compatibility tab, check the "Override high DPI scaling behavior" checkbox, and choose Scaling performed by "Application".  Close and restart Visual Studio Code.
![image](https://user-images.githubusercontent.com/924374/29303451-5636fdb2-81d0-11e7-9117-0eb0a9c926b2.png)

Now, when you drag VS Code between monitors with different DPI, it will initially fail to resize the text.  So going from a high DPI screen to a low DPI screen, the text will apear huge.  But all you have to do is resize the window on the new monitor and the text will instantly size properly for the monitor and be perfectly sharp.

**Comment by CnSimonChan** [comment] 2017-08-15 05:53
@kring I have heard that choose `System (Enhanced)` will also work.

But anyway, after a month of postpone, Electron 1.7.4 is now in the master branch, so Insider builds from today should be per-monitor DPI aware now, at least in theory.

**Comment by bpasero** [comment] 2017-08-15 06:14
@kring (and others), yeah let us know if the insiders build (e.g. from today) fixes this.

**Comment by kring** [comment] 2017-08-15 06:39
Yep today's Insiders looks great, no settings tweak or manual resize necessary.  Thanks!

**Closed** 2017-08-21 09:51 UTC
Labels: bug, electron, electron-update, upstream, workbench

**Comment by bpasero** [comment] 2017-08-30 15:20
Marking as verified based on @kring comment.

**Comment by yaomtc** [comment] 2017-09-08 01:15
After testing many text editors, this and Notepad are the only ones I could find that have per monitor DPI awareness, which is a big help to me, with a 4K monitor next to a 1080p one. Since Notepad still doesn't support Unix style line endings, and I often create text files on Linux, MacOS, and Android, that was not an option. I'm now using Visual Studio Code as my text editor for all my personal notes and lists. I am not a programmer, but I'm very glad VS Code now works this way. Many thanks to the Electron team for fixing this and to you folks making it work with Code.

**Comment by alper6** [comment] 2017-11-01 12:20
Windows 8.1 x64, VS Code 1.17.2 x64, external 20" HP monitor @1600x900, here is a screenshot with VS Code on the left and Notepad++ on the right.
![vsc-blurry](https://user-images.githubusercontent.com/33016508/32274452-e910320a-bf17-11e7-8d5f-b32ea0e09f88.jpg)
This is basically unusable, too blurry. Will this ever be fixed? I really want to use VS Code.

**Comment by jnm2** [comment] 2017-11-01 12:44
@alper6 VS Code has not done that for a while on any of my computers. As I drag it between monitors with different DPIs, it rescales so that it never becomes blurry. What version are you using?

**Comment by alper6** [comment] 2017-11-01 18:46
@jnm2 the version is 1.17.2. I periodically test every latest version to see if anything has improved.

**Comment by ivanz** [comment] 2017-11-01 19:27
Random thing to check: Have you by any chance maybe set a "Custom scaling" in Windows for the monitor or any monitor? I *think* that turns off lots of multi-DPI goodness in Windows and reverts back to legacy behavior (not 100% sure)

**Comment by alper6** [comment] 2017-11-01 20:37
@ivanz I mentioned details about my system in first post, top of screenshot (is it not visible?)
It's not Windows 10, but Windows 8.1
I'm not using multi-monitor, it's set as "show desktop only on 2nd monitor", here's a shot:

![ss1](https://user-images.githubusercontent.com/33016508/32296549-93eef810-bf5d-11e7-8e75-53f8319a4477.jpg)

There's also no custom scaling, those settings are all at default, here's a shot:

![ss2](https://user-images.githubusercontent.com/33016508/32296589-ab6b462e-bf5d-11e7-947b-b2bbf39f2ba0.jpg)

**Comment by jnm2** [comment] 2017-11-01 21:40
Your Notepad++ is super blurry in your [first screenshot](https://github.com/Microsoft/vscode/issues/6196#issuecomment-341091305) too.

**Comment by delcon** [comment] 2017-11-07 08:58
I would like to reopen this issue.
VSCode seems to support 'per monitor aware scaling', at my surface.
Link to some [explanation about scaling modes.](https://support.office.com/en-us/article/Office-apps-appear-the-wrong-size-or-blurry-on-external-monitors-bc9f7279-4e42-4b15-a949-46ab8bcfe44f?ui=en-US&rs=en-US&ad=US&fromAR=1)
However, Tooltips and Dialog Boxes are still only system aware.
![image](https://user-images.githubusercontent.com/9477898/32485001-1a00ea74-c3a2-11e7-944e-640f1257fde0.png)
