### ISSUE TITLE
Context menu automatically gets triggered in explorer sidebar when right clicking

### ISSUE THREAD

**Issue by manojbaishya** [microsoft/vscode#121157] opened 2021-04-13 06:58 UTC
Issue Type: <b>Bug</b>

Right-click and release on a file in the Explorer automatically selects the context menu item under the mouse pointer. Right click-hold-select item-release is difficult on a touchpad.

Possible duplicate of https://github.com/microsoft/vscode/issues/65787 and https://github.com/microsoft/vscode/issues/69961 but those conversations are locked.

https://user-images.githubusercontent.com/28330014/114510087-deda5000-9c53-11eb-8597-914ad1f2340a.mp4

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:01:24.315Z)
OS version: Linux x64 5.4.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2161)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (4.84GB free)|
|Process Argv|/media/manoj/DATA/Masters/Coursework/Dissertation/Workspace/Simulations --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
TabOut|alb|0.2.0
read-only-indicator|ale|3.4.1
All-Autocomplete|Ati|0.0.23
vscode-django|bat|1.6.0
markdown-preview-github-styles|bie|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
python-snippets|cst|0.0.9
vscode-markdownlint|Dav|0.40.3
vscode-new-file|dku|4.0.2
python-preview|don|0.0.4
gitlens|eam|11.4.0
python-ultisnippets|eli|2.7.0
code-runner|for|0.11.3
pythonsnippets|frh|1.0.2
mdmath|goe|2.5.1
todo-tree|Gru|0.0.211
vscode-test-explorer|hbe|2.19.6
error-gutters|Igo|1.0.1
vscode-icon-theme|jtl|1.6.6
vsc-python-indent|Kev|1.13.1
vscode-python-test-adapter|lit|0.6.7
rainbow-csv|mec|1.8.1
python-path|mge|0.0.11
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.7
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.5.702919634
sqltools|mtx|0.23.0
vscode-json-editor|nic|0.3.0
autodocstring|njp|0.5.4
vscode-python-typehint|njq|1.4.1
repeat-paste|nwb|0.0.1
indent-rainbow|ode|7.5.0
python-string-sql|ptw|1.1.0
text-power-tools|qcz|1.26.0
ispy|Ric|0.0.4
vscode-sort-json|ric|1.20.0
python-template-snippets|Ric|1.2.0
vscode-qt-for-python|sea|0.6.1
comment-divider|sta|0.3.0
python-extended-snippets|tus|0.0.1
errorlens|use|3.2.5
vscodeintellicode|Vis|1.2.12
jinja|who|0.0.8
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
pyqt-integration|zho|0.2.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2021-04-13 10:24
Looks like a duplicate of https://github.com/microsoft/vscode/issues/65787 so assigning also to @joaomoreno
fyi @sbatten for custom menus

**Comment by sbatten** [comment] 2021-04-13 14:58
duplicate https://github.com/microsoft/vscode/issues/113175

**Closed by sbatten** 2021-04-13 14:58 UTC

**Comment by manojbaishya** [comment] 2021-04-13 17:01
@sbatten Thanks. Should I include the above info in that issue (since it is discussing the editor area right-click), or is it fine staying here (will reduce noise)?
