### ISSUE TITLE
Massy `import` statement highlight accidentally

### ISSUE THREAD

**Issue by CarterLi** [microsoft/vscode#73569] opened 2019-05-10 08:59 UTC
Issue Type: <b>Bug</b>

Sometimes `import` statement shows invalid charactor on white space. There is no syntax error on this line.

I can't reproduce this issue permanently, It seems that it happens only when the import variable is not used. I'll update this issue when I find more information.

![image](https://user-images.githubusercontent.com/6134068/57515184-9bc72200-7344-11e9-9551-a886f8afcf29.png)

![image](https://user-images.githubusercontent.com/6134068/57516314-1133f200-7347-11e9-9fbd-ca254b473aca.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
indent4to2|Com|0.1.2
vscode-todo|Mat|0.8.0
ejs-language-support|Qas|0.0.1
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
color-info|bie|0.5.1
iview-snippets|bos|0.2.1
ng-zorro-vscode|cip|7.3.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.6.0
dart-code|Dar|3.0.1
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
vscode-dash|dee|2.1.0
githistory|don|0.4.6
gitlens|eam|9.7.1
vscode-npm-script|eg2|0.3.7
vimL|fal|0.0.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.5.0
icon-fonts|idl|2.1.5
gitlab-mr|jas|1.4.2
vscode-map-preview|jum|0.4.8
color-the-tag-name|jzm|0.17.0
codeacejumper|luc|2.1.5
rainbow-csv|mec|1.0.0
Angular-BeastCode|Mik|8.0.6
vscode-stylefmt|mrm|2.5.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
csharp|ms-|1.19.1
Go|ms-|0.10.2
mono-debug|ms-|0.15.8
vetur|oct|0.20.0
sass-indented|rob|1.5.1
rust|rus|0.6.1
vscode-nginx|sha|0.6.0
gitconfig|sid|2.0.0
vscode-csstree|sme|0.7.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
highlight-matching-tag|vin|0.9.1
vscode-icons|vsc|8.6.0
vscode-todo-highlight|way|1.0.4
swig-tpl|zha|0.0.6
swig|zhu|0.0.5
html-css-class-completion|Zig|1.18.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-05-10 17:53
I don't understand the issue. Can you please explain what the expected behavior and what the specific issue is?

**Comment by CarterLi** [comment] 2019-05-11 02:54
@mjbvz As my the screenshot shown above, `import { url } from '@/app'` is incorrectly rendered as `import {{url }}from '@/app';`

Sorry I don't speak English natively

**Comment by mjbvz** [comment] 2019-05-14 01:07
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment] 2019-05-22 22:55
Without more information, I suspect this is caused by one of the extensions you have installed

Closing as more information is needed

**Closed by mjbvz** 2019-05-22 22:55 UTC
Labels: needs more info
