### ISSUE TITLE
Go to definition not working for objects in function parameters

### ISSUE THREAD

**Issue by csnv** [Microsoft/vscode#38198] opened 2017-11-13 08:41 UTC
- VSCode Version: 1.18
- OS Version: Mac OS 10.12.6

Go to definition doesn't work for the following snippet, when ctrl+clicking on this.fn():
```
a({
	fn: function() {
		this.fn();
	}
});
```

**Comment by mjbvz** [comment] 2017-11-13 19:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/11072

The root cause is that our IntelliSense does not understand what `this` is inside of object literals

**Closed by mjbvz** 2017-11-13 19:18 UTC
Labels: javascript, new release, upstream
