### ISSUE TITLE
Remote-SSH Leaving Orphan Processes and Creating Multiple Shell Scripts

### ISSUE THREAD

**Issue by SimchaWood** [microsoft/vscode#76903] opened 2019-07-08 17:49 UTC
- VSCode Version: 1.36.0
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Use Remote-SSH to connect to host or open remote workspace.

Does this issue occur when all extensions are disabled?: Yes

Each occurrence of connecting to the remote host or a remote workspace spawns additional **sleep infinity** processes that do not go away when the remote workspace and/or connection is closed:
```
$ pstree -a
systemd --switched-root --system --deserialize 22
  ...
  ├─bash
  │   └─sleep infinity     <-- From previous session.
  ├─bash
  │   └─sleep infinity     <-- From previous session.
  ├─bash
  │   └─sleep infinity     <-- From previous session.
  ├─bash
  │   └─sleep infinity     <-- From previous session.
  ...
  ├─sshd -D
  │   └─sshd
  │       └─sshd
  │           └─bash
  │               └─sleep infinity  <-- From current session.
  ├─systemd-journal
  ├─systemd-logind
  └─systemd-udevd
```
Also, in C:\Users\[username]\AppData\Local\Temp, multiple files with the name vscode-linux-multi-line-command-[hostname]-[number].sh are being created with each session.

**Comment by adityamandaleeka** [comment] 2019-07-08 21:25
Adding to this, I left my computer running over the weekend with an active Remote-SSH connection, which ran into some failure mode where it kept spawning new ssh/conhost/etc. When I caught it, VSCode and its child processes totaled 5598. I tried to debug it to provide more info about where the issue is, but the machine was pretty unusable so I had to reboot.

**Comment by roblourens** [comment] 2019-07-10 17:36
I can repro processes leaking, this is new.

> Also, in C:\Users[username]\AppData\Local\Temp, multiple files with the name vscode-linux-multi-line-command-[hostname]-[number].sh are being created with each session.

This is expected, it's your temp folder, the OS will clean them up

@adityamandaleeka That sounds different but that does not sound good. Please open a new issue with a list of the processes, if possible, if you see it again.

**Comment by roblourens** [comment] 2019-07-31 16:15
The leaking processes are fixed in the nightly ssh build.

**Closed by roblourens** 2019-07-31 16:15 UTC
Labels: bug
