### ISSUE TITLE
Color escape sequence cannot be displayed correctly in vscode terminal

### ISSUE THREAD

**Issue by Real-YuZhe** [microsoft/vscode#206173] opened 2024-02-24 20:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows 11 22631.2861

Steps to Reproduce:

1. Build the sample code and run the sample. It happens when terminal is relatively large, like 245*66 in my case. I  build this [sample code](https://github.com/Real-YuZhe/vscode_issue_report) in WSL2 on kali-linux distribution:
<img width="1679" alt="1" src="https://github.com/microsoft/vscode/assets/68314620/1c1b2a5f-4322-4edd-b736-b8cff83caf86">

2. Resize terminal size and the image can be displayed correctly:
<img width="1676" alt="2" src="https://github.com/microsoft/vscode/assets/68314620/4ca21da6-fdeb-4b7e-b702-8a0d56251212">

3. It works well on Windows Terminal:
<img width="1545" alt="3" src="https://github.com/microsoft/vscode/assets/68314620/b667aacb-4bb6-4c3e-a782-9e2ed534aced">

**Comment by Tyriar** [comment] 2024-12-10 17:51
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-10 17:51 UTC
Labels: confirmation-pending, terminal-rendering
