### ISSUE TITLE
When debugging node over WSL, the node debugger process is left hanging

### ISSUE THREAD

**Issue by alanosman** [Microsoft/vscode#42746] opened 2018-02-01 15:55 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
debugger-for-chrome|msj|4.1.0
better-align|wwm|1.1.6

(1 theme extensions excluded)

---
Hello,

I have run into a situation where if I am debugging a node program via the newly incorporated setting `useWSL`, it works the first time, but the process does not always get terminated when debugging ends.  

**launch.json**
```
        {
            "type": "node",
            "request": "launch",
            "name": "Run Elastc",
            "program": "${workspaceFolder}/elastc.js",
            "useWSL": true
        },
```

**Steps to Reproduce:**

My environment is all WSL based.  I set VC to open a bash shell instead of Powershell.   I also use hyper.is for multiple sessions outside of VC.

1.  Open VC with a working node app
2.  Set the launch.json to start debugging within WSL
3.  Run the debugger on your program
4.  Quit the debugger
5.  Switch to a different terminal outside of VC on WSL
6.  Try and run your program again (in our case it was `node elastc`)

Our app is using port 8080 for HTTP access.  That port is never released so the app fails to start.

After I terminate debugging from VC, if I run a `ps -ef` command I see that the node debugger is still running.  If I re-run the debugger again, it works, but if I go outside VC to a terminal and start my process, it will compete for port 8080 because the debugger is holding onto that process.  I think when we stop debugging, the process should end. 

The screen shot shows that the last line in the process list has the debugger running.  It remains even if I close VC.
![image](https://user-images.githubusercontent.com/2914981/35687961-19613d8c-073e-11e8-852b-e5ab0139c20a.png)

Reproduces without extensions: Yes/No   **YES**

**Comment by thecodingdude** [comment] 2018-02-04 15:51
This is the same as #38424 so I don't understand why this has a Feb milestone and the other is "on deck". It's literally been broken since November but nobody seems to care.

**Comment by weinand** [comment] 2018-02-04 16:31
duplicate of #38424

**Closed by weinand** 2018-02-04 16:31 UTC
Labels: WSL, bug, debug
