### ISSUE TITLE
Debugging crashes when adding watch

### ISSUE THREAD

**Issue by gourangaAngularjs** [Microsoft/vscode#3863] opened 2016-03-08 15:53 UTC
Debugging crashes when adding watch and i get the below message

**Assertion failed: object->InternalFieldCount() > 0, file d:\jenkins\workspace\nodejs-msi-julien\d8c2e2bb\src\util-inl.h, line 117**

Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135

**Comment by weinand** [comment] 2016-03-08 16:00
duplicate of #3111

**Closed by weinand** 2016-03-08 16:00 UTC

**Comment by weinand** [comment] 2016-03-08 16:06
@gourangaAngularjs what node version is this?
