### ISSUE TITLE
Transform tips to links or buttons?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#34397] opened 2017-09-14 17:54 UTC
When no editor is open there's an area in the middle of the screen with some commands and hotkeys:

![no-editor](https://user-images.githubusercontent.com/9638156/30444998-6260f6cc-998d-11e7-89c8-4166c3532363.png)

I expected them to trigger actions on click but that didn't happen. Was it done to promote hotkeys (intentionally) or not?

It just so happens "Welcome page" has both (links and buttons) that invoke commands written on them.

**Comment by bpasero** [comment] 2017-11-16 17:44
I saw a duplicate of this one.

**Closed by bpasero** 2017-11-16 17:44 UTC
Labels: feature-request, workbench

**Comment by usernamehw** [comment] 2017-11-16 17:55
Of this one https://github.com/Microsoft/vscode/issues/16601
