### ISSUE TITLE
Integrated terminal keep defaulting to powershell even though I have explicitly set it as cmd

### ISSUE THREAD

**Issue by chadleong** [microsoft/vscode#132413] opened 2021-09-06 00:08 UTC
My default profile is cmd. But vscode keep defaulting to powershell even though I have explicitly set it as cmd.

<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
vscode-django | bat | 1.6.0
markdown-table-prettify | dar | 3.5.0
vscode-markdownlint | Dav | 0.43.2
githistory | don | 0.6.18
xml | Dot | 2.5.1
es7-react-js-snippets | dsz | 3.1.1
vscode-npm-script | eg2 | 0.3.22
prettier-vscode | esb | 8.1.0
vs-code-xml-format | fab | 0.1.5
code-runner | for | 0.11.5
vscode-yarn | gam | 2.0.0
copilot | Git | 1.4.2586
gc-excelviewer | Gra | 3.0.44
beautify | Hoo | 1.5.0
vscode-map-preview | jum | 0.5.8
compare-folders | mos | 0.22.2
vscode-azurefunctions | ms- | 1.5.0
vscode-azureresourcegroups | ms- | 0.4.0
vscode-azurestorage | ms- | 0.12.1
vscode-docker | ms- | 1.16.1
csharp | ms- | 1.23.15
anaconda-extension-pack | ms- | 1.0.1
python | ms- | 2021.9.1191016588
vscode-pylance | ms- | 2021.9.0
jupyter | ms- | 2021.8.2031190714
jupyter-keymap | ms- | 1.0.0
remote-containers | ms- | 0.194.0
remote-wsl | ms- | 0.58.2
azure-account | ms- | 0.9.8
cpptools | ms- | 1.6.0
material-icon-theme | PKi | 4.10.0
vscode-commons | red | 0.0.6
vscode-xml | red | 0.18.0
vscode-yaml | red | 0.22.0
LiveServer | rit | 5.6.1
pin-up | sae | 1.4.1
markdown-preview-enhanced | shd | 0.6.0
html5-boilerplate | sid | 1.1.1
vscode-icons | vsc | 11.6.0
vim | vsc | 1.21.7
markdown-all-in-one | yzh | 3.4.0
html-css-class-completion | Zig | 1.20.0

</body>
</html>

**Comment by LongYue9608** [comment] 2021-09-06 01:44
Just today, I also encountered this problem

**Comment by odajapan** [comment] 2021-09-06 02:38
I also encountered this issue.

**Comment by kohane27** [comment] 2021-09-06 03:20
https://github.com/microsoft/vscode/issues/128763
This is a bug occurring in version 1.6 for me too. I rolled back to 1.59 and the problem is gone.

**Comment by lakshits11** [comment] 2021-09-06 04:27
I am also facing this issue. And thanks to @kohane27 , when I rolled back to 1.59, issue was gone. But please look into this.
I am using extension [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and I have set its commands for cmd, but whenever I run code, powershell opens and gives error since commands were written for the sole purpose of running in cmd. Anyone have a solution for this btw ?

**Comment by gjsjohnmurray** [comment] 2021-09-06 06:58
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-06 06:59 UTC
Labels: *duplicate
