### ISSUE TITLE
VSCode Opens Slowly after 1.9.1 update

### ISSUE THREAD

**Issue by davidtaylorjr** [Microsoft/vscode#21643] opened 2017-03-01 18:16 UTC
- VSCode Version: <code>Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)</code>
- Memory (System): <code>7.90GB (2.72GB free)</code>
- Memory (Process): <code>109.97MB working set (110.17MB peak, 81.58MB private, 31.11MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|750|
|main|app.isReady => window.loadUrl()|2862|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|3802|
|renderer|require(workbench.main.js)|2533|
|renderer|create extension host => extensions onReady()|5694|
|renderer|restore viewlet|2402|
|renderer|restore editor view state|1|
|renderer|overall workbench load|7386|
|main + renderer|start => extensions ready|17964|
|main + renderer|start => workbench ready|17377|

---

VScode is opening very slowly from the command line using `code .` when in a folder.

It is also slower overall when opening after the latest update, not sure what might be factors you need to know about.

**Comment by bpasero** [comment] 2017-03-02 05:32
@davidtaylorjr maybe you can compare with the 1.9.1 version: https://az764295.vo.msecnd.net/stable/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/VSCode-win32-1.9.1.zip ?

**Comment by bpasero** [comment] 2017-03-02 05:32
Ah sorry, you see this in the 1.9.1 release, what about our current release 1.10.1?

**Comment by davidtaylorjr** [comment] 2017-03-02 12:54
I updated last night and it is no better.

**Comment by bpasero** [comment] 2017-03-02 15:27
@jrieken what are the steps to let a user report that profile? would be interesting in this case here

**Comment by jrieken** [comment] 2017-03-02 15:53
@davidtaylorjr Can you try with [Insiders](https://code.visualstudio.com/insiders) and start the editor from the command line via `code --prof-startup`. Since the `appReady`-event comes very slow I also wonder which AV software you are using

**Comment by bpasero** [comment] 2017-03-02 16:16
@davidtaylorjr I guess that should be `code-insiders --prof-startup`

**Comment by davidtaylorjr** [comment] 2017-03-02 16:53
@jrieken what do you mean by AV software?

@bpasero below is the insider's startup info:

- VSCode Version: <code>Code - Insiders 1.11.0-insider (0bc62d1679fbb59a4bd8f62203743408893ba4ee, 2017-03-02T13:51:59.532Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)</code>
- Memory (System): <code>7.90GB (2.17GB free)</code>
- Memory (Process): <code>128.80MB working set (129.51MB peak, 102.99MB private, 32.21MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|42|
|main|app.isReady => window.loadUrl()|437|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|485|
|renderer|require(workbench.main.js)|1203|
|renderer|create extension host => extensions onReady()|2189|
|renderer|restore viewlet|0|
|renderer|restore editor view state|549|
|renderer|overall workbench load|3617|
|main + renderer|start => extensions ready|6165|
|main + renderer|start => workbench ready|5798|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\davidtaylorjr\c30e_main.cpuprofile.txt`
-`C:\Users\davidtaylorjr\c30e_renderer.cpuprofile.txt`

**Comment by davidtaylorjr** [comment] 2017-03-02 16:54
[c30e_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814505/c30e_renderer.cpuprofile.txt)
[c30e_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814506/c30e_main.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-03-03 08:41
> what do you mean by AV software?

@davidtaylorjr Anti-virus software. Some are known to have a negative impact on the startup performance of electron apps:

**Comment by davidtaylorjr** [comment] 2017-03-03 12:58
Ah yes, I'm actually just using Windows Defender.

**Comment by jrieken** [comment] 2017-03-03 13:03
That shouldn't be a problem

**Comment by davidtaylorjr** [comment] 2017-03-03 13:06
I figured not. I used insiders exclusively last night doing some work and
it was the same thing, slow startup, not as slow but still slow and I
purposefully did not install any extensions.

Once you are actually in the software it is fine, it is just the startup so
it isn't unbearable just not like it used to be.

VSCode used to be much faster than Atom, now it is about the same for me.

**Comment by jrieken** [comment] 2017-03-03 13:36
@alexandrudima reading from the dom takes 1.7 seconds which isn't normal, right?

<img width="652" alt="screen shot 2017-03-03 at 14 33 44" src="https://cloud.githubusercontent.com/assets/1794099/23552914/812c448e-001e-11e7-9278-391eb4f50044.png">

Also trying to listen on the pipe is slow and blocking  as it seems...

<img width="747" alt="screen shot 2017-03-03 at 14 35 58" src="https://cloud.githubusercontent.com/assets/1794099/23552961/bdbfe0a4-001e-11e7-935d-957ec7ff5ee2.png">

**Comment by jrieken** [comment] 2017-03-03 14:27
and then for @bpasero the `setJumplist` call seems to be very slow. can that be made faster/smarter or can that be moved after starting loading of the main window (waterfall)?

![screen shot 2017-03-03 at 15 25 46](https://cloud.githubusercontent.com/assets/1794099/23554556/e4d0c8d2-0025-11e7-82f6-2abcbab14599.png)

**Comment by bpasero** [comment] 2017-03-03 14:50
@jrieken yeah should be no problem to call setJumpList after the first window opened.

**Comment by alexandrudima** [comment] 2017-03-03 17:38
regarding `_readFromDomElements`:

```
	private _readFromDomElements(): void {
		for (let i = 0, len = this._requests.length; i < len; i++) {
			const request = this._requests[i];
			const testElement = this._testElements[i];

			request.fulfill(testElement.offsetWidth / 256);
		}
	}
```

I've no idea what Chromium needs to do behind the scenes to initialize for a first layout. I can only imagine this forced layout blocks on Chromium initialization. If Chromium is slow, the profile will reflect the Chromium initialization time in this function call, but this call most likely reflects the time it takes Chromium to be able to do a first layout, rather than anything else.

The only thing that I can think might impact this is the `fontFamily`. Perhaps Chromium needs to load the font in order to service this forced layout. @davidtaylorjr Can you please share your settings, perhaps we spot something in there?

**Comment by davidtaylorjr** [comment] 2017-03-03 17:58
@alexandrudima 

On my regular build here are my settings:

```
// Place your settings in this file to overwrite the default settings
{
    "http.proxyStrictSSL": true,
    "extensions.autoUpdate": true,
    "sync.gist": "01ddc2efef9ea07ac37cf8666388352d",
    "sync.lastUpload": "2017-03-03T17:04:55.581Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "",
    "sync.version": 251,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "cdnjs.protocol": "https://",
    "cdnjs.quoteStyle": "double",
    "auto-close-tag.SublimeText3Mode": true,
    "files.autoSave": "afterDelay",
    "editor.wordWrap": "on",
    "vsicons.projectDetection.autoReload": false,
    "vsicons.projectDetection.disableDetect": true,
    "typescript.tsdk": "C:/Users/davidtaylorjr/AppData/Roaming/npm/node_modules/typescript/lib",
    "workbench.iconTheme": "vscode-icons"
}

```

On the Insider's Build I have no custom settings or extensions installed.

**Comment by jrieken** [comment] 2017-03-08 09:00
From this and other cpu profiles we have extracted (and fixed) various separate issues and I am going to close this as dupe of #22090, #22086, #21963. Thanks and Happy Coding

**Closed by jrieken** 2017-03-08 09:00 UTC
Labels: perf-profile
