### ISSUE TITLE
Having Offline Issues

### ISSUE THREAD

**Issue by ericasamoah** [Microsoft/vscode#59705] opened 2018-09-30 22:33 UTC

**Comment by ericasamoah** [comment] 2018-09-30 22:35
nope!

**Comment by V-ed** [comment] 2018-10-01 15:17
Did you at least try digging into the issues proposed by the duplicate detection bot? You provide no info upon your problem, what is your OS, what even your offline means (Airplane mode on? no hardware card? wifi enabled but not connected? etc), or any other info than simply "nope! - it's not what any of the discussion about VSCode not opening in offline mode talked about!".

Have you taken a look at this comment (found using the first link of the bot) : https://github.com/Microsoft/vscode/issues/7570#issuecomment-422815878 ? What did you try? To make it short, there seems to be a problem in electron that messes up the telemetry services, but the newer versions of Electron (which is present in the build provided in the comment I linked) should not have this problem. Did you try using this build to see if your problem still happens?

Without any further information, I'd consider this as a Duplicate of #7570.

Sorry if I sound passive-aggressive in this comment. I just can't understand when developpers file issues not explaining any of the steps they did themselves. What if you were the one to receive this issue? How would *you* try to help someone filing this issue? There's 0 more information in here that wasn't already discussed in another issue.

**Closed** 2018-10-01 15:33 UTC
