### ISSUE TITLE
VS Code file icon leaks around

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19486] opened 2017-01-27 10:31 UTC
I have no icon theme or anything alike configured but see icons for two files, in quick open as well as in the editor title

![screen shot 2017-01-27 at 11 30 06](https://cloud.githubusercontent.com/assets/1794099/22367873/1dd85f0e-e484-11e6-872e-e1679654e0cf.png)

**Comment by jrieken** [comment] 2017-01-27 10:32
Also in the explorer...
![screen shot 2017-01-27 at 11 32 21](https://cloud.githubusercontent.com/assets/1794099/22367911/4ad524b0-e484-11e6-85e0-d5d7c19082b3.png)

**Comment by joaomoreno** [comment] 2017-01-27 13:07
This might be related to the fact that the welcome "editor" has an icon even though icons are disabled.

![image](https://cloud.githubusercontent.com/assets/22350/22371850/e87db1e0-e499-11e6-99d6-b39d0ee7d7f4.png)

**Comment by chrmarti** [comment] 2017-01-27 16:41
Correct, duplicate of #19501

**Closed by chrmarti** 2017-01-27 16:41 UTC
Labels: bug, duplicate
