### ISSUE TITLE
Terminal window fonts are squashed and difficult to read

### ISSUE THREAD

**Issue by alfalabs** [Microsoft/vscode#36231] opened 2017-10-13 14:03 UTC
VSCode Version: Code 1.17.1  1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z  - OS Version: Windows_NT x64 6.1.7601 - Extensions: Extension|Author  truncated |Version -|-|- jshint|dba|0.10.15 vscode-eslint|dba|1.3.2 sass-lint|gle|0.0.4 vs-color-picker|lih|0.7.0 mssql|ms-|1.2.0 csharp|ms-|1.12.1 debugger-for-chrome|msj|3.3.1 vetur|oct|0.9.11 live-sass|rit|1.0.1 LiveServer|rit|2.2.1 sass-indented|rob|1.4.4 vsc-nwjs|rua|1.0.11 partial-diff|ryu|0.3.3 vscode-table-formatter|shu|1.2.1 easysass|spo|0.0.6 markdown-pdf|yza|0.1.7 markdown-all-in-one|yzh|0.10.3 - Steps to Reproduce: 1. 2. !- Launch with  code -disable-extensions  to check. -> Reproduces without extensions: Yes

- Code area: fonts are correctly displayed
- Terminal window: fonts are squashed horizontally, hard to read

![clipboard01](https://user-images.githubusercontent.com/11356118/31549858-689fe954-affd-11e7-807a-bb6c6e9a3344.png)
see included screenshot in 100% size and note how the letter "m" is rendered in both cases

**Comment by egamma** [comment] 2017-10-13 16:04
Duplicate of #35991 will be fixed in 1.17.2.

**Closed by egamma** 2017-10-13 16:04 UTC
Labels: new release
