### ISSUE TITLE
Freezes when select some lines in a HTML file

### ISSUE THREAD

**Issue by patrickmaciel** [Microsoft/vscode#16142] opened 2016-11-28 11:40 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 x64 Build 1607

Steps to Reproduce:

1. Open a html file
2. Use mouse/keyboard to select some lines (fast, not slowly)
3. Some freezes when I do that

See the gift below: 

![vscode-slow-select-html](https://cloud.githubusercontent.com/assets/671670/20667058/94d4fc9e-b54e-11e6-855c-7f6ef55ba6ce.gif)

**Comment by alexandrudima** [comment] 2016-11-28 17:06
@patrickmaciel Does this reproduce when disabling all extensions? Can you please try to profile and find out where the time is being spent (`Help` > `Toggle Developer Tools` > `Profiles` tab > Start ).

**Comment by patrickmaciel** [comment] 2016-11-28 17:59
@alexandrudima when I disable all extensions, everything works great. I'll try enable one by one to test that.

Below the image related to "Developer Tools" and the CPU Profile.
![log1](https://cloud.githubusercontent.com/assets/671670/20679818/98549570-b583-11e6-84bf-b49af132c397.JPG)
![log2](https://cloud.githubusercontent.com/assets/671670/20679822/9ba94a90-b583-11e6-906a-90f35c3fee43.JPG)
[CPU-20161128T155426.zip](https://github.com/Microsoft/vscode/files/617034/CPU-20161128T155426.zip)

**Comment by alexandrudima** [comment] 2017-03-30 10:01
Closing as this is caused by an extension

**Closed by alexandrudima** 2017-03-30 10:01 UTC
Labels: needs more info
