### ISSUE TITLE
Allow extensions to provide commands for their custom treeviews programatically

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#78572] opened 2019-08-06 16:43 UTC
This is similar to https://github.com/microsoft/vscode/issues/9285, but that seems to be about letting the end user configure the context menu, whereas I want to provide context menu commands from my extension, but dynamically (such that they can't be in the package manifest).

I know we've previously discussed something similar to this around making context menus *async*, but that's not required here - the context menus can be provided up-front (and periodically updated), but they are based on launch configs and therefore can't be in package.json.

Here's a screenshot fo a new feature I added to my extension:

![Screenshot 2019-08-06 at 5 23 29 pm](https://user-images.githubusercontent.com/1078012/62557457-ee927600-b86e-11e9-93ac-51d90680f946.png)

The "Run" and "Debug" code lens already existed - they're hard-coded. The other two are are user-defined - the user can configure additional launch configurations for launching tests. In `provideCodeLens` I read the launch configs, see if any are marked as templates, and include them in the result.

I'd like to also add them to the context menu for the test tree here:

![Screenshot 2019-08-06 at 5 41 28 pm](https://user-images.githubusercontent.com/1078012/62558721-74afbc00-b871-11e9-952f-48dd1838dc5a.png)

However AFAIC these need to be pre-declared in the package.json - and of course I don't know what custom configs the users will add. I'd like to instead supply these commands (like I do in `provideCodeLens`) for each node (either at node creation time, on-demand, or just at extension startup + whenever the user modifies the launch configs).

**Comment by DanTup** [comment] 2019-08-06 16:47
FWIW, it's not actually a custom command required here - it's just the display text and arguments that are passed to the existing command. So for the Code Lens, the code looks like:

```ts
runTestTemplates.map((t) => new CodeLens(
	toRange(document, test.offset, test.length),
	{
		arguments: [test, t],
		command: "_dart.startWithoutDebuggingTestFromOutline",
		title: t.name,
	},
))
```

The command `_dart.startWithoutDebuggingTestFromOutline` is already declared in `package.json`, but we return it multiple times with different title/args for these code lens actions (I don't know whether that simplifies this - there doesn't need to actually be custom registration of commands, rather just supply a `vscode.Command` instance).

**Comment by alexr00** [comment] 2020-11-06 14:18
duplicate of https://github.com/microsoft/vscode/issues/27536

**Closed by alexr00** 2020-11-06 14:18 UTC
Labels: api, explorer-custom, feature-request
