### ISSUE TITLE
Editor not scrolling horizontally with multiple carets

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/vscode#72330] opened 2019-04-15 10:51 UTC
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.34.0-insider (3d67364fbfcf676d93be64f949e9b33e7f1b969e, 2019-04-15T05:21:42.563Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-switcher|bla|0.1.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
ini-for-vscode|Dav|0.0.4
gitlens|eam|9.6.0
permute-lines|ear|0.0.10
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
font-switcher|eva|3.0.0
code-runner|for|0.9.8
vscode-postfix-ts|ipa|1.8.1
tabsanity|jed|0.0.11
Lua|key|0.0.9
macrosRe|l7s|1.3.0
quicktask|lky|3.5.4
metago|met|2.11.0
goto-next-previous-member|mis|0.0.4
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-project-name-in-statusbar|muj|1.0.0
incrementor|nms|0.1.0
material-icon-theme|PKi|3.7.0
quicktype|qui|12.0.46
bracket-jumper|sas|1.1.8
code-settings-sync|Sha|3.2.8
lua|sum|0.8.4
lorem-ipsum|Tyr|1.2.0
vscode-icons|vsc|8.5.0
vscode-wakatime|Wak|1.2.14
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
vscode-surround|yat|1.0.2

(5 theme extensions excluded)

</details>

Steps to Reproduce:

1. Open a file with at least two lines long enough to produce horizontal scroll (when wrap is disabled).
2. Add carets to the beginning of both lines.
3. Press `End`.

Expected result: Both carets are moved to the end of each line and editor is scrolled to show them.

Actual result: Carets are moved properly, but editor is not scrolled to show carets.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2019-05-07 13:51
Duplicate of #6995

**Closed by alexandrudima** 2019-05-07 13:51 UTC
Labels: editor-multicursor
