### ISSUE TITLE
[Extensions] [Explorer] [Multi select] - when command is specified to show using resourcelang, it shows in context menu inconsistently

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode#59782] opened 2018-10-01 20:31 UTC
[Github reference](https://github.com/Microsoft/vscode-cosmosdb/pull/831/files#r221035893)
1. In an extension create a command with a when clause contraining the resourceLangID, say JSON. 
2. In extension host, open a workspace with multiple file types. 
You can skip 1&2 by cloning vscode-cosmosdb , at the branch ps/ImportDocuments, at this commit:  62fd48101811551977af592168751bcb969213a8

3. Select a group of files, with multiple types. 
4. a) right-click at a JSON file, you see the command. 
b) right click on another file, you don't see it. 
This seems inconsistent - the group of files is the same. 

Screenshots from the reference comment: 
![image](https://user-images.githubusercontent.com/30420973/46314027-4214a300-c57e-11e8-9bd4-4b01b83f65da.png)

![image](https://user-images.githubusercontent.com/30420973/46314035-4640c080-c57e-11e8-840a-0df3aa4e44de.png)

I can understand why this behavior exists - it was a hard bug to catch. :)

**Comment by isidorn** [comment] 2018-10-02 08:21
@PrashanthCorp thanks for the nice issue report, however I think this is designed behavior.
The context menu enablement is based on the primary selected resource and that is always the one you clicked upon. So even if the selected group is the same we make a distinction based on the primary click.
The reason why we need a primary selected resource is that the context enablement only happens based on one resource, not on multiple as per definition of each context.

Closing this as designed, however if you have an idea on how to solve this please let us know and I can reopen this.

**Closed by isidorn** 2018-10-02 08:21 UTC
