### ISSUE TITLE
Slow intellisence, slow navigation, slow formatting etc, it was fast before

### ISSUE THREAD

**Issue by JanBN** [microsoft/vscode#117853] opened 2021-02-28 16:09 UTC
**The problem**
From time to time everything gets very slow. I'm working with c# and typescript. When I want to navigate to the object (pressing F12) or searching for references, or when I type some code perfectly aware it should be underline with red or format the code it takes time. Tiny progress bar appear below the tabs (or above) and it loads and loads like 30 seconds to 1 minute and then it is fast again for some time. And then after a while the same. Even when I want to navigate to the property in the same file it starts loading something and I find it faster by searching the text. **It seems like it keeps everything in the memory but from time to time it needs to reload it all or something like that**. I did not have these issues before the last update.

Tried disabling all extensions, clearing the cache, deleting workspace directory nothing helps.

- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:
Don't know how to reproduce

Does this issue occur when all extensions are disabled?: Yes

**Comment by heartacker** [comment] 2021-02-28 17:06
i have the same slow appearance  when coding c++
elusive that i can't  paste my last clipboard item until few second later. at the same time,i usually click ctrl+v twice or more, after that.,there are so many text-block  are pasted.
![image](https://user-images.githubusercontent.com/1876302/109426776-4cc31300-7a2a-11eb-9386-a6a3ed062e1e.png)

**Comment by JanBN** [comment] 2021-02-28 20:40
Also when debugging c# it seems like vscode freezes first and only then hit the breakpoint.

**Comment by deepak1556** [comment] 2021-03-01 21:30
Do you see the behavior when you start the app like `code --disable-features=CalculateNativeWinOcclusion`

**Comment by JanBN** [comment] 2021-03-01 22:00
Thank you. 

`code --disable-features=CalculateNativeWinOcclusion` debugging is fast with this. 
Intellisense seems ok too. But I tried only for a while so can't confirm it won't happen again. I check also tomorrow.

Anyway in the meantime I have installed insiders version of vscode and there are not these problems.

**Comment by deepak1556** [comment] 2021-03-01 22:08
Thanks for checking, the underlying issue should be same as https://github.com/microsoft/vscode/issues/114459. Feel free to close the issue if you no longer see the issue in current stable with the command line flag after more testing.

**Comment by JanBN** [comment] 2021-03-02 12:09
Well it does not seem to help. It still runs loading bar under the tabs from time to time for about a 30 seconds. Usually when I want to navigate to the property or method

**Comment by deepak1556** [comment] 2021-03-02 20:39
Are you seeing the issue with insiders with extensions disabled ? If so, then please take the cpu profile following the steps

* Open window devtools
* Go to performance tab
* Click start profiling and reload page icon
* Perform actions that cause the slowdown
* Download the profile

**Comment by JanBN** [comment] 2021-03-02 21:56
Hi, I do not see any issues with insiders. Insiders works fine for me. I'm using it instead of stable version for now. 
In the stable version this flag `code --disable-features=CalculateNativeWinOcclusion` did solve the debugging issue.
However it does not solve from time to time long loading whatever it loads. This loading problem is not in insider version.

So probably when you release next stable version it would be ok (if the next stable version is current insiders version)

**Comment by JanBN** [comment] 2021-03-02 22:10
I did reecord the profile. However I started when it was actually loading. This is what I did:
1) started stable version
2) started working
3) after 5 minutes, it stops navigating instantly and started loading somethin
4) pressed record. 
5) pressed stop record when the loading bar disappears.

here is the profile https://we.tl/t-Q5VOVV48uY

**Comment by deepak1556** [comment] 2021-03-02 23:44
> So probably when you release next stable version it would be ok (if the next stable version is current insiders version)

Yes current insiders will get promoted to next stable release.

Thanks for the profile, @alexdima in the profile at the frame drop region there is unusual amount of tokenization calls happening, can you check if this needs any attention. 

<img width="263" alt="Screen Shot 2021-03-02 at 3 41 21 PM" src="https://user-images.githubusercontent.com/964386/109730227-08409000-7b6e-11eb-8a6c-f558b8d5aac4.png">

**Comment by EdNutting** [comment] 2021-05-08 15:29
I am experiencing the same issue since updating VSCode last month. Please see attached profile. This appears to contain a lot of tokenization calls too. Everything was fine until I upgraded VSCode. Additionally, my colleague is running VSCode on both his Windows and Mac machines with the same codebase, versions and extensions and has no problems, so I'd love to know what's different about my computer that causes VSCode to hang up for seconds at a time every time I try to use intellisense or "go-to-definition/use" navigation, etc.

The issue occurs even after twice totally wiping VSCode (uninstall, delete everything the uninstaller misses, reinstall) and my dev setup (delete folder, re-clone, reinstall packages, etc). Including when not enabling any VSCode extensions.

[Profile-20210508T162214.zip](https://github.com/microsoft/vscode/files/6446078/Profile-20210508T162214.zip)

**Comment by EdNutting** [comment] 2021-05-08 19:03
Update: Performance has dropped back to being unusable again. Intellisense takes tens of seconds to respond, if it ever does at all. Problems view takes literally minutes to update and frequently I have to close/reopen a file to get it to refresh the problems list.

I'm resorting to use an external build tool in "watch mode" to get a list of errors quickly.

**Comment by alexdima** [comment] 2021-06-07 21:07
AFAIK we have a well known perf issue on Windows -- https://github.com/microsoft/vscode/issues/107016 .

If you close all windows of VS Code and launch with `code --disable-renderer-accessibility` does VS Code become smooth again?

**Comment by EdNutting** [comment] 2021-06-09 14:11
@alexdima Thank you for the suggestion. This seems to solve a small fraction of the problem. This makes the intellisense popover render more instantaneously, but the intellisense itself is unfortunately still very slow. 

With the above flag applied, the intellisense popover now renders instantly but I still have to keep closing and reopening it (Esc -> Ctrl + .) for a minute or two before it shows anything other than the default results - see comparative screenshots below. 

Note that any significant edit to the current file seems to clear the results and I have to wait again for them to be recomputed. The error lines underneath code also go out of alignment as soon as I edit code above them and take just as long to update (sometimes they never do and I have to close-and-reopen a file to get ESLint / VSCode Error Highlights to reset).

Default results shown instantly:

![image](https://user-images.githubusercontent.com/1746336/121369864-21f32f80-c934-11eb-8120-cc637ad197b0.png)

Useful results after waiting a long time:
 
![image](https://user-images.githubusercontent.com/1746336/121369381-b610c700-c933-11eb-87e6-9cd22473668d.png)

At this point VSCode intellisense and error bars are proving to be a hindrance (and I am sorry to say I am frequently resorting to Notepad++ in order to get work done).

Lastly, this is not a TSServer logging/tracing problem. As you'll see from my other reports (and feature requests), I turned off TSServer logging etc so it shouldn't be causing this level of performance issue.

**Comment by EdNutting** [comment] 2021-06-09 14:23
By the way, I would be happy to have a Zoom meeting with a VSCode or TSServer engineer to spend a few hours exploring this issue and trying to find the root cause. Clearly nobody has a proper reproduction yet and it's something system-specific because my colleague on a seemingly identical dev-setup / codebase doesn't have these issues. Please, if anyone with some expertise can help diagnose this, it would save me so much time and pain. This performance issue is costing me at least an hour a day in development time.

**Comment by alexdima** [comment] 2021-06-11 14:29
@EdNutting I am sorry for the slowness you are experiencing, that doesn't sound right. I have looked at your performance profile, which captures the CPU usage of the renderer process, but there is nothing that appears wrong there, basically I can see how the renderer process is idle for 5-10 seconds until the quick fixes come in.

My colleague @mjbvz knows a lot more about quick fixes, but I believe the quick fixes will be rendered when all extensions that contribute quick fixes have finished computing them. So it is extremely likely that you have an extension which takes a really long time to compute quick fixes and that causes a delay to all the other quick fixes. AFAIK the same is true for suggestions, about which @jrieken knows more. If one suggestion provider is slow, then all suggestions might arrive after a long time.

@EdNutting Could you please try the following:

- Close all instances of vscode (use task manager to make sure)
- Launch `code.exe --disable-extensions`
- Open your project and press ctrl+space somewhere

**Comment by EdNutting** [comment] 2021-06-11 14:51
Hi @alexdima, thank you for the suggestions. I have re-tried launching vscode with extensions disabled and unfortunately it doesn't make a difference. 

This issue impacts anything that has to do with inference from the code - by which I mean, everything from Go To Definition through to auto-import through to quick fixes and suggestions, etc. I highly doubt this is a rendering issue and nor is it impacted by extensions (my colleague runs the same set of extensions too without any issue). 

It feels like either VSCode or TSServer is hitting some corner case that's causing it to do a lot of processing. Error highlighting, quick fixes, etc all go completely out of sync unless I save the file every time before trying to use them (suggesting that the language server is not integrating real-time, unsaved edits but is having to go back to the version of disk all the time). 

Is there a way to diagnose whether the slowness/waiting is being caused by something inside VSCode or inside TSServer (or in the communication in between)?

**Comment by alexdima** [comment] 2021-06-11 15:03
Yes, there are ways, I'm just not super familiar with them, sorry about that. One thing that I do know is that it is possible to load the TSServer from a custom path, maybe you are loading TSServer from a bad location?

So to get a really clean environment, you could try: 
- close all instances of vscode
- `code.exe --disable-extensions --user-data-dir=C:\newfolderthatyoucreatedbefore`

But let's ask @mjbvz to help further with troubleshooting why tsserver is slow for you.

**Comment by EdNutting** [comment] 2021-06-11 15:11
Thank you! I am hopeful we can diagnose this soon. I tried a blank user data directory on each of my four SSDs, to no avail. (I'll be back online on Monday to debug further.)

**Comment by EdNutting** [comment] 2021-06-27 14:15
Update: Changing `typescript.workspaceSymbols.scope` to `currentProject` has increased performance a bit. Not sure why having it set to `allOpenProjects` would be affecting me worse than my colleagues though.

This further confirms my suspicion that this is a TSServer performance issue with some kind of corner case handling the symbol service.

**Comment by mjbvz** [comment] 2021-06-29 16:52
@EdNutting  Please open  a separate issue. Make sure to fill in the issue template and note if you are using a custom TS version

**Comment by mjbvz** [comment] 2021-06-29 16:53
@JanBN Are you still seeing this issue in VS Code insiders with extensions disabled?

**Comment by fatiz1997** [comment] 2021-07-07 08:27
My problem is long execution of `Go to References (Shift+F12)` option. 
Why am I so sure that this is kind of a bug? Well, because before some update there wasn't any hanging, everything has been flying quickly. Also, here is very important note: it works slowly not each time. One time it works very slowly even without any loading indicator (just hangs on and after few seconds popup with references appears) and the other time it works OK with no time delay.

Starting as `code.exe --disable-extensions` helped me with performance issue. 

But I use some quite really needed extensions (for example, IDEA keyboard, Angular Lang Service, Debugger for Chrome, git extens, tslint and some more others), and once more: `it worked OK with the same pack of extensions before some update`, so I believe this is fixable in some way

**Comment by fatiz1997** [comment] 2021-07-07 08:29
One more note:
`code --disable-renderer-accessibility` and `code --disable-features=CalculateNativeWinOcclusion` didn't help

**Comment by mjbvz** [comment] 2021-08-12 23:07
Closing this as we need more information from the original poster to investigate

**Closed by mjbvz** 2021-08-12 23:07 UTC
Labels: needs more info, windows, confirmation-pending
