### ISSUE TITLE
VS Code unable to open when there is not internet

### ISSUE THREAD

**Issue by Alfred20697** [Microsoft/vscode#61047] opened 2018-10-16 13:17 UTC
- VSCode Version: 1.27.2 User Setup
- OS Version: Windows 10 Feature Update 1809

Steps to Reproduce:

1. Install using the VS Code installer (fresh installation)
2. Turn off the Internet connection
2. Open VS Code

Does this issue occur when all extensions are disabled?: (Fresh installation)

Additional information: 
1. Add ```code``` to path variable.
2. Open command prompt
3. Run ```code --verbose```
4. Then this error message will appear. 
```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

**Comment by mjbvz** [comment] 2018-10-16 20:42
Duplicate of #7570

**Closed by mjbvz** 2018-10-16 20:42 UTC
