### ISSUE TITLE
Relative Links are not clickable in Terminal

### ISSUE THREAD

**Issue by sharadgupta-north** [microsoft/vscode#87892] opened 2019-12-30 17:57 UTC
Issue Type: <b>Bug</b>

Building using gcc and none of the relative links are clickable in the Terminal. Absolute links work.
Tried setting "fileLocation": [ "relative", "${workspaceFolder}/out/build"], and still no luck.
Tried possible solutions in #58256 but no luck.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3088)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|31.31GB (1.89GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
codealignment-vscode|cpm|2.0.19
gitlens|eam|10.2.0
cortex-debug|mar|0.3.4
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.1404
clang-tidy|not|0.2.2
code-spell-checker|str|1.7.20
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.2
better-align|wwm|1.1.6

</details>

**Comment by IllusionMH** [comment] 2019-12-30 18:12
/needsMoreInfo

Can you provide examples of paths that are not clickable?
Most likely duplicate of #21125

**Comment by jacksteamdev** [comment] 2019-12-31 14:49
I'm pretty sure this is a regression. The link below (`src/md-sections.test.ts:22:36`) isn't clickable.

![terminal-link-not-clickable](https://user-images.githubusercontent.com/23390212/71624841-3d3c0600-2baa-11ea-9043-c0b9e66d874f.png)

**Comment by Tyriar** [comment] 2019-12-31 19:42
Still work fine for me in the terminal, it's probably related to the cwd of the terminals.

**Comment by sharadgupta-north** [comment] 2020-01-02 16:26
Same screen capture, full paths work, relatives don't.
![NoHoverLink](https://user-images.githubusercontent.com/57115510/71678191-95ae0780-2d52-11ea-8d14-b4039ad93fc5.gif)
![HoverLink](https://user-images.githubusercontent.com/57115510/71678197-98106180-2d52-11ea-96d5-2f44474a2f33.gif)

Not sure about the cwd comment, all relative paths are from build folder.

**Comment by alexr00** [comment] 2020-01-06 10:31
@sharadgupta-north tasks doesn't do anything special for clickable links in the terminal, it just relies on the terminal link detection. If you run the same command that your task runs manually in the terminal, are the links clickable?

**Comment by sharadgupta-north** [comment] 2020-01-06 14:44
No they are not.

**Comment by alexr00** [comment] 2020-01-06 14:51
The `fileLocation` you mentioned in the original post is for the links in Problems that are created from running the task, so it also has no affect on the terminal links. 

I suppose tasks could create a new terminal link matcher based on the problem matcher, but right now that's out of scope.

**Closed** 2020-01-06 14:51 UTC
Labels: *out-of-scope

**Comment by sharadgupta-north** [comment] 2020-01-06 14:56
That was me just trying to fix my problem not the expected solution.
As 'jacksteamdev' mentioned it seems to be a regression and not sure how a regression could be a design decision?
So what you are saying is relative links should not work as clickable links? you are basically excluding a major chunk of your user base.

**Comment by alexr00** [comment] 2020-01-06 15:02
Relative links that are relative to the terminal's cwd should be clickable. 
Example where the following exist:
c:\one\two\filetwo.txt
c:\one\fileone.txt
Terminal cwd is c:\one.
This relative path should be clickable: fileone.txt
This relative path should be clickable: \two\filetwo.txt
This path is not relative to the cwd and shouldn't be clickable: filetwo.txt.

@Tyriar please correct me if I'm wrong!

**Comment by Tyriar** [comment] 2020-01-06 17:17
> This relative path should be clickable: fileone.txt
> This relative path should be clickable: \two\filetwo.txt
> This path is not relative to the cwd and shouldn't be clickable: filetwo.txt.

Paths must start with `.\` or `..\` for Windows. Simply `fileone.txt` is not specific enough currently (improvements planned in https://github.com/microsoft/vscode/issues/21125, https://github.com/xtermjs/xterm.js/issues/583)

**Comment by alexr00** [comment] 2020-01-07 08:54
@Tyriar thanks for the clarification!
Corrected example:
c:\one\two\filetwo.txt
c:\one\fileone.txt
Terminal starting cwd is c:\one.
This relative path should be clickable: .\fileone.txt
This relative path should be clickable: .\two\filetwo.txt
This path is not relative to the_starting_ cwd and shouldn't be clickable: .\filetwo.txt.
