### ISSUE TITLE
Focus not restored to <webview> after tabbing out and back into window

### ISSUE THREAD

**Issue by 1983cc** [Microsoft/vscode#12081] opened 2016-09-15 14:16 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10 Professiona

Steps to Reproduce:
1.  Open a markdown file and swtich to preview
2.  Use Ctrl + Tab to switch to another window and then switch back
3. The Preview window cannot scorll with the Up and Down key

**Comment by bpasero** [comment] 2016-09-15 15:24
Looks like after tabbing back to the Window, focus is put into the body element of that window and not the webview. Smells like an upstream issue to me with webviews.

**Comment by mjbvz** [comment] 2018-04-27 23:40
Upstream electron issue: https://github.com/electron/electron/issues/5900

We should be able to hook into `window.on('focus'` to restore focus ourselves

**Comment by mjbvz** [comment] 2018-05-24 23:00
Duplicate of #49998

**Closed by mjbvz** 2018-05-24 23:00 UTC
Labels: electron, upstream, webview
