### ISSUE TITLE
Honor Windows accessibility keyboard shortcut setting or provide one.

### ISSUE THREAD

**Issue by rpm0372** [Microsoft/vscode#63300] opened 2018-11-16 12:33 UTC
On Windows platforms, VS Code should honor the setting at:
Control Panel / Ease Of Access Center / Make the keyboard easier to use / Underline keyboard shortcuts and access keys
by always underlining menu shortcut hotkeys when this setting is enabled.

Or, for a platform-agnostic solution, at least provide a setting in VS Code to effect always underlining menu hotkeys.

**Comment by sbatten** [comment] 2018-11-16 18:44
duplicate of #54349

**Closed by sbatten** 2018-11-16 18:44 UTC

**Comment by rpm0372** [comment] 2018-11-16 22:35
Much apologies.  My initial search for "accelerator" and "hotkey" did not reveal that submission.
