### ISSUE TITLE
Column selection (rectangle mode)

### ISSUE THREAD

**Issue by pug77** [microsoft/vscode#73837] opened 2019-05-16 18:32 UTC
Issue Type: <b>Feature Request</b>

Possibility to select rectagle of text and copy / paste.
multi cursors should be aligned during selection and stay aligned also after pasting coppied text and when you start typing, typed text will appear on all lines right after pated rectangle 

Example: https://pasteboard.co/IeZZrQH.jpg

for reference see IntelliJ comunity edition  "column selection mode"

this should work with keyboard only and also with mouse
shortcuts:  toggle column mode, direclty start multi selection, directly start rectangle selection

(selection, column, vertical, rectangle, multi-cursor)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gazzar** [comment] 2019-05-19 01:30
Dupe of #5940

**Comment by ArashPartow** [comment] 2019-05-19 09:47
More examples of this problem can be found here: #43145

**Closed** 2019-07-22 21:11 UTC
Labels: editor-columnselect
