### ISSUE TITLE
Still having to scroll horizontally to see my whole file with word wrap enabled (there's some text under the minimap)

### ISSUE THREAD

**Issue by paulalbertdev** [microsoft/vscode#119875] opened 2021-03-25 13:58 UTC
Issue Type: <b>Bug</b>

Hi ! 
Even when word wrapping is enabled, I still have to scroll horizontally to see my whole files content (there's some text under the minimap).
Please tell me if you need additional informations !
Cheers

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4030)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.64GB (0.51GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 3254e2ed-6b7f-42b4-8105-e9b4cf9606cd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
ionic-docs|4tr|0.0.7
better-comments|aar|2.1.0
formatter-pug|ale|0.0.1
git-rename|amb|1.1.3
html-class-suggestions|And|1.1.1
sublime-cmd-shift-d|and|1.2.2
vscode-back-forward-buttons|bai|1.0.1
vscode-intelephense-client|bme|1.6.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-mysql-client2|cwe|3.6.0
multi-file-renamer|dan|1.0.0
meld-diff|dan|1.1.0
vue-peek|dar|1.0.2
jshint|dba|0.11.0
vscode-eslint|dba|2.1.19
yarn-task-provider|dkn|0.2.2
jquerysnippets|don|0.0.1
pug-formatter|duc|0.6.0
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.18
git-project-manager|fel|1.7.1
docker-explorer|for|0.1.7
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.208
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
path-autocomplete|ion|1.17.1
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
css-snippets|joy|1.0.2
vue-beautify2|ker|0.0.3
chmod-command|lab|0.0.1
inline-parameters|lia|0.2.1
vscode-phpstan|Man|0.2.0
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.29.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.163.2
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
indent-rainbow|ode|7.5.0
lorem-text-generator|ogu|1.0.1
vscode-versionlens|pfl|1.0.9
autolaunch|phi|2.0.3
vscode-php-getters-setters|php|1.2.3
vscode-css-peek|pra|4.1.2
ruby|reb|0.28.1
missinglineendoffile|ric|0.3.1
blank-line-organizer|rin|0.1.5
copy-relative-path-posix|rss|0.0.4
vscode-open|san|0.1.0
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.7.0
swdc-vscode|sof|2.5.3
php-formatter|Sop|0.2.4
guides|spy|0.9.3
autoimport|ste|1.5.3
vscode-stylelint|sty|0.86.0
sass-indented|syl|1.8.16
tabnine-vscode|Tab|3.2.13
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.2.0
twig|wha|1.0.2
vscode-ruby|win|0.28.0
change-case|wma|1.0.0
vue|Wsc|1.0.26
local-history|xyz|1.8.1
livereload|zii|0.2.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
openwsldoc:30280162
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by paulalbertdev** [comment] 2021-03-25 14:01
![image](https://user-images.githubusercontent.com/22445690/112485140-e310fd00-8d7a-11eb-91e4-31b129f7c2a9.png)

**Comment by paulalbertdev** [comment] 2021-03-25 14:04
![image](https://user-images.githubusercontent.com/22445690/112485445-3d11c280-8d7b-11eb-9ad4-b2148aeb0c55.png)
Could it be due to the parameters names hinting ?

**Comment by paulalbertdev** [comment] 2021-03-25 14:04
PS: I've tried with and without "editor.wrappingStrategy": "advanced", and it seems to have no effect

**Comment by paulalbertdev** [comment] 2021-03-25 14:08
Could it be due to parameters names hinting no being taken into account ?
![image](https://user-images.githubusercontent.com/22445690/112486147-e953a900-8d7b-11eb-8265-b52762b83052.png)

**Comment by usernamehw** [comment] 2021-03-25 16:05
/duplicate of #32856

Inline decorations from extension break word wrap.

**Closed** 2021-03-25 16:07 UTC
Labels: *duplicate
