### ISSUE TITLE
Git History Graph: enable jumping to associated PR

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#223043] opened 2024-07-22 10:52 UTC
Type: <b>Feature Request</b>

In the screenshot below I'd like to be able to jump to the associated PR on the GH site, perhaps using the context menu.

![image](https://github.com/user-attachments/assets/857b4d56-475a-47c0-9306-afe600cf7425)

I'm not sure if this would need to be implemented in the bundled Git extension or is more appropriately handled by the GitHub Pull Requests extension (pinging @alexr00)

VS Code version: Code - Insiders 1.92.0-insider (97d1b933ada0ca69bea107f7a89e029991277ccc, 2024-07-22T05:03:41.362Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by alexr00** [comment] 2024-07-22 11:22
Cool idea. @lszomoru is there a menu that GHPR could contribute to for this?

**Comment by lszomoru** [comment] 2024-07-22 12:50
There is, but I think that we should chat as I think you would need more information in order to decide when to show the action.

**Comment by gjsjohnmurray** [comment] 2024-07-22 14:58
It would be particularly useful when the commit message doesn't give any indication what the change does. Some of the VS Code team commonly use such messages:

![image](https://github.com/user-attachments/assets/a2753d2a-a36f-40a0-9ad1-c2ecbdfbdbd1)

**Comment by lszomoru** [comment] 2024-07-22 15:04
Ideally would should be able to link out to both GitHub issues as well as pull requests.

**Comment by gjsjohnmurray** [comment] 2024-07-24 06:35
A plea to @sandy081 to use more informative PR descriptions:

![image](https://github.com/user-attachments/assets/345b22dc-d65a-45ef-861c-eae9a80778c1)

**Comment by sandy081** [comment] 2024-07-24 11:28
Definitely! It would be helpful to show the associated issue in the hover.

**Comment by lszomoru** [comment] 2024-12-10 15:41
Closing as duplicate of https://github.com/microsoft/vscode/issues/226427

**Closed by lszomoru** 2024-12-10 15:41 UTC
Labels: feature-request, git
