### ISSUE TITLE
IntelliSense suggestion order and icon

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#64489] opened 2018-12-06 07:28 UTC
- VSCode Version: 1.29.1
- OS Version: macOS latest

![image](https://user-images.githubusercontent.com/10441177/49568178-ea593600-f938-11e8-975b-e70f81d4a13e.png)

As you can see these word-based suggestions should be at the end. Also, very weird is their icon is like my icon theme Untitled file icon which is wrong too because before 1.29 version they looked different.

This is with JavaScript, seems with TS everything is OK since it doesn't give me word-based suggestions.

**Comment by svipben** [comment] 2018-12-06 07:40
With Insiders build order seems correct, but the icon is wrong.

![image](https://user-images.githubusercontent.com/10441177/49568828-cf87c100-f93a-11e8-8aaf-0d4688245425.png)

P.S. But to be 100% sure with order I suggest to check it by yourself with Stable and Insiders.

**Comment by svipben** [comment] 2018-12-06 07:43
Seems even in Insiders order is wrong, it's mixed which isn't good, all word-based suggestions should go to the bottom.

![image](https://user-images.githubusercontent.com/10441177/49568986-4cb33600-f93b-11e8-8e82-3f752a117722.png)

**Comment by svipben** [comment] 2018-12-06 07:49
@jrieken Seems order is messed up with `Locality Bonus` setting enabled.

But without `Locality Bonus` still they are mixed like in this comment: https://github.com/Microsoft/vscode/issues/64489#issuecomment-444777998

**Comment by jrieken** [comment] 2018-12-06 08:11
> But without Locality Bonus still they are mixed like in this comment: #64489 (comment)

https://github.com/Microsoft/vscode/issues/64489#issuecomment-444777998 shows the expected order after typing `h`

> @jrieken Seems order is messed up with Locality Bonus setting enabled.

Without the full sample, *in source*, I cannot say anything.

**Comment by jrieken** [comment] 2018-12-06 16:10
> Is with word-based suggestions icon which is wrong because it takes it from Untitled file.

The suggestion marks itself as of type `File` and that it then uses that icons is to be expected - @mjbvz for why that actually is

> Suggestions order is wrong with Locality Bonus enabled.

Why? `editor` appears in the document whereas `anchor` doesn't and the rules of locality search are that "closer" items are sorted up

**Comment by svipben** [comment] 2018-12-06 16:24
But in this context it makes sense to get anchor since it’s string. Also, it gives a lot of noise and it’s only usable in TS since it doesn’t have word-based suggestions. I expected Locality Bonus to order variables which are nearest not the object properties.

**Comment by jrieken** [comment] 2018-12-06 16:34
> Also, it gives a lot of noise and it’s only usable in TS since it doesn’t have word-based suggestions.

This is the default behaviour of JavaScript - in addition to members it always suggestions all known symbols because it's JavaScript and that means everything is possible

**Comment by jrieken** [comment] 2018-12-06 16:35
closing as question, leaving it up to @mjbvz to change the icon/type for default suggestions but everything else works as designed here

**Closed** 2018-12-06 16:34 UTC
Labels: *question, needs more info, suggest

**Comment by svipben** [comment] 2018-12-11 06:02
Created a separate issue for the wrong icon https://github.com/Microsoft/vscode/issues/64777
