### ISSUE TITLE
Limited native window tabs functionality in macOS high sierra

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode#35361] opened 2017-09-29 07:55 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 17.0.0
- Extensions: (unimportant, see below)

Steps to Reproduce:

1. Try to use `"window.nativeTabs": true` option, notice the squiggles and message says _Unknown configuration setting_
2. If you remove the setting, opening a new window **does** create a new window
3. If you put the setting back, it **is** respected, but creating a new window creates (visually) empty native tab bar (previously it showed two tabs, as expected); clicking on the tab creates a new window, as if the whole tab bar is in fact the newly added (looking at 1.17 release notes) "+" button to add a new window/tab
4. Switching windows works, my custom shortcuts are respected etc. all is well, except tabs display

One more thing 😉  bizarrely my insider hasn't been updates since 20th of September (never seen insider go for 10 days without update). Downloading insider from Code's site also yields 20th of Sep version. 

Reproduces without extensions: YES (as expected)

**Comment by bpasero** [comment] 2017-09-29 08:23
@ddotlic but you are seeing the native tab bar to the top of the window?

![image](https://user-images.githubusercontent.com/900690/31007241-32f6a656-a500-11e7-9e03-1bcea32649f5.png)

**Comment by ddotlic** [comment] 2017-09-29 08:27
Sorry, I'll post a screenshot now, it might be clearer (or not, you'll see):
![screen shot 2017-09-29 at 10 25 35](https://user-images.githubusercontent.com/1737586/31007372-b01da918-a500-11e7-980f-d855a77a0675.png)

The whole "tab" area behaves like a "+" button in your screenshot.

**Comment by ddotlic** [comment] 2017-09-29 08:28
Needless to say, this worked fine yesterday (before I installed High Sierra update), this is a MacBook Pro 2015, always up to date so I expect no issues with drivers etc.

If I can do something else to help (provide more info by running with particular command line switches) please do not hesitate to ask.

**Comment by bpasero** [comment] 2017-09-29 09:25
Unfortunately this looks like an issue in Elecron, I filed: https://github.com/electron/electron/issues/10657

For now the functionality seems limited at best. I think all that is going wrong is the rendering of native tabs, but otherwise the tabs are there.

**Comment by ddotlic** [comment] 2017-09-29 09:28
Thanks for the info. We'll likely either see more people confirming the same when 1.17 comes out, or not 😄 in which case it'll be some fluke on my machine that I'll need to figure out somehow.

@bpasero Do you have any idea if it's normal for insider to not be updated for the last 10 days??

**Comment by bpasero** [comment] 2017-09-29 10:07
@ddotlic yes, our signing service currently is not active.

**Comment by giricgoyal** [comment] 2017-10-01 20:47
Having this issue with VS Code v 1.16.1 and Mac OS High Sierra.

**Comment by primalmotion** [comment] 2017-10-05 20:29
I confirm I have the exact same issue with VSCode 1.17.0. It was working with the previous version (even if the `window.nativeTabs` was not officially supported)

**Comment by williamli** [comment] 2017-10-06 02:17
Just upgraded to v1.17.0 on High Sierra and I too experience this problem when "window.nativeTabs": true is enabled. Got a massive + new tab button (with no label on it) and not seeing any tabs until I go to "Show All Tabs"

**Comment by primalmotion** [comment] 2017-10-06 02:21
I sent a fix here https://github.com/electron/electron/pull/10696#pullrequestreview-67556591

You can work around the issue by building Electron from my PR, then replace it from the `VSCode.app/Contents/MacOS`. A bit complicated, but I can't live without native tabs support :)

**Comment by Hum4n01d** [comment] 2017-10-15 20:47
Same issue here

**Comment by hemedani** [comment] 2017-10-26 07:55
I have the same issue

**Comment by ddotlic** [comment] 2017-10-26 08:19
Everyone: the proposed fix is "flaky" in the sense that it depends on which macOS version Electron/VS Code is **built on**, not **what it runs on**. It's a compile time thing, not a runtime thing. As long as VS Code is _not built_ on High Sierra, this fix will do nothing.

Please don't spam this item with useless comments like "me too" - there's a reaction you can use for that. Let's leave this item for pertinent comments regarding the inclusion of an eventual fix.

This should be a lesson to us all to not upgrade to a new OS as soon as possible 😉

**Comment by michaelduminy** [comment] 2017-10-31 13:55
Maybe the VSCode team could adjust their build process to fix this?

**Comment by rkistinger** [comment] 2017-11-02 15:45
Also having the "massive '+' tab with no label" issue & want to follow this thread

**Comment by ermamud** [comment] 2017-11-09 03:25
Any update on this issue? I just update to `High Sierra` and `VS Code 1.18` and still having the missing native tabs :(

**Comment by bpasero** [comment] 2017-11-09 09:20
We are waiting for a real fix from Electron. Forcing a change of build machines to use high sierra is not a fix of this issue.

**Comment by michaelduminy** [comment] 2017-11-09 09:25
It's not a terrible stopgap though, which would give time for Electron to fix the issue on their side before the next MacOS release.

**Comment by PSalant726** [comment] 2017-11-09 16:12
It doesn't seem like a lot to ask to use the latest macOS for macOS software development.

**Comment by Shafley** [comment] 2017-11-13 02:59
Same issue here.

**Comment by ACCBizon** [comment] 2017-11-15 09:20
+1 ;(

**Comment by tomitrescak** [comment] 2017-11-19 23:01
@PSalant726 be nice and patient. You are more then welcome to submit a PR here. As far as I know this is still open source project and you spend zilch to use this browser. There are alternative editors you can use.

**Comment by smith64fx** [comment] 2017-11-24 08:39
Hey guys, just be patient :D This is not the end of the world!

**Comment by phoenixgao** [comment] 2017-12-11 05:18
since the electron bug hasn't been fixed so far, is there any workaround we can do in vscode?

**Comment by dastoori** [comment] 2017-12-11 17:30
@phoenixgao, This is my workaround:

1. Add `"window.nativeTabs": true` to your settings
1. Restart the vscode
1. Open multiple windows
1. Use `Window > Merge All Windows` (`workbench.action.mergeAllWindowTabs` command) to merge all windows into one
1. Use either one of the followings to switch between windows:
    - native way: `View > Show All Tabs` or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>\\</kbd> 
    - vscode menu: `Window > Switch Window...` or <kbd>Ctrl</kbd>+<kbd>w</kbd> (`workbench.action.switchWindow` command) 

The only problem with this is that it always shows a blank bar on top of the window

**Comment by linmodev** [comment] 2017-12-26 02:22
@primalmotion Hi,I cloned electron repo, but I can't build this project success. But I really need this function. Can you provide an available electron?

**Comment by leopoiroux** [comment] 2018-01-11 17:28
+1

**Comment by haad** [comment] 2018-01-12 09:52
Hi,
Just follow this manual and you should be able to build it.

https://electronjs.org/docs/development/build-instructions-osx

**Comment by maephisto** [comment] 2018-01-23 12:33
@bpasero Any _official_ updates on this?

**Comment by phoenixgao** [comment] 2018-01-23 12:48
I followed the manual and took me 6 hours but still not finish downloading the vendor files, I might have a poor network but it requires several gigabytes chromium runtime or so... anyway I gave up and installed Vscode Insider, and put multiple projects under one workspace if that could be considered as a workaround.

**Comment by silentred** [comment] 2018-01-26 11:30
+1

**Comment by silentred** [comment] 2018-01-26 11:31
+1

**Comment by tomitrescak** [comment] 2018-02-04 22:42
Ok, I built the Electron from the source (6 hours), what do I do with it now? How do I add the VSCode functionality to it? Thanks!

**Comment by LFeh** [comment] 2018-02-05 14:42
Any update?

**Comment by pi0** [comment] 2018-02-05 21:11
@microsoft @billgates @SatyaNadella

**Comment by tomitrescak** [comment] 2018-02-06 21:53
I have a version of Electron built from the source from master which I can share. But it would be great if someone could come up with some instructions of what to do with it. I have replaced the Electron.framework from inside the package and that just crashed the whole thing.

**Comment by phoenixgao** [comment] 2018-02-07 06:35
It's a bug of Electron, so guys you could follow https://github.com/electron/electron/issues/10657

It's a bit hard to build electron from source unless you have built it before, at least I didn't make it -- it need download several gigabytes dependencies.

Someone shared a build you could try:
https://github.com/electron/electron/pull/10696#issuecomment-360061076
But like he said, you need to trust him.

**Comment by linmodev** [comment] 2018-02-07 06:45
@phoenixgao The file is deleted already.

**Comment by silentred** [comment] 2018-02-07 07:24
@phoenixgao what to do next when the electron was built? replace some files under the vscode dir?

**Comment by phoenixgao** [comment] 2018-02-07 07:43
@silentred yes, check readme file here
https://github.com/phoenixgao/electron-high-sierra-build

**Comment by harrykroon** [comment] 2018-02-07 08:30
I build the app using `yarn`.
In the root of the cloned vscode project, choose a branche or tag and then:
`yarn run gulp vscode-darwin`

A complete standalone app is build. When finished building, you can find it here:` ../VSCode-darwin/Code - OSS.app` (check the size, it should be about 200MB)
From there, you can move it to `/Applications`.

I did alter the `project.json`, because the default does not include the config for the `extensions` repository.

**Comment by tomitrescak** [comment] 2018-02-10 09:03
@phoenixgao you are a freaking lifesaver !!! ❤️Works like a charm in High Sierra. I hope we can trust YOU!

**Comment by maephisto** [comment] 2018-02-15 13:15
@phoenixgao It's... beautiful!
You build from https://github.com/phoenixgao/electron-high-sierra-build worked perfectly and now native tabs work again!

**Comment by LFeh** [comment] 2018-02-15 19:48
@phoenixgao It's working now! Thanks! 😍

**Comment by julianmontagna** [comment] 2018-02-15 22:04
@phoenixgao working for me too! Thanks a lot! 💘

**Comment by johnelm** [comment] 2018-02-15 23:27
Works for me too.  

As the README says, all vscode automatic updating will be disabled if you use the downloaded Electron (the menu items don't even show).  

I've tested with moving the original `Electron` back into place and the auto updates are restored, and they work.

Thanks @phoenixgao , I thought I'd be able to wait for a proper fix - but having my workspaces in separate windows was driving me nuts.

**Comment by fmunteanu** [comment] 2018-03-06 23:23
What a nice surprise I had today, after completing the High Sierra upgrade. Looking forward to have an Electron fix as part of the official VSCode release. 🤒

**Comment by irfaan008** [comment] 2018-04-12 01:35
Still the same issue and even the march release of VS code doesn't have this fix.

**Comment by bpasero** [comment] 2018-06-07 10:02
I did some more digging into this and found out that a simple change to the `CFBundleIdentifier` (in `/Applications/Visual Studio Code - Insiders.app/Contents/Info.plist`) from `com.microsoft.VSCodeInsiders` to `com.microsoft2.VSCodeInsiders` makes native tabs show up properly for me. 

I cannot explain this behaviour though and feel uneasy about making such a change as a fix. If someone has friends over at Apple that could explain this behaviour, I am happy for some help. 

It is true that we are building Electron against the `macOS SDK 10.10` which may have an impact on this issue.

**Comment by pavelloz** [comment] 2018-06-07 12:14
I confirm, update from sierra to high sierra breaks merge all windows feature.

**Comment by Mokkapps** [comment] 2018-06-07 13:38
This is not a real solution to this problem but I want to mentioned it anyways:

Due to this bug I changed my workflow in Visual Code to use [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces). 

They can be very helpful when you are working on several related projects at one time. For example, I have created a workspace for all of my private projects.

Using workspaces I do not have to handle multiple VS Code editor windows but always work with one window which includes my current workspace.

**Comment by ryenus** [comment] 2018-06-07 14:08
@bpasero hardly believable but that's totally true, I just tested using 
the latest 1.24 release on macOS 10.13.4. I tried the following:
* com.microsoft2.VSCode
* com.msn.VSCode
* com.github.VSCode

They all work, so weird!

**Comment by haad** [comment] 2018-06-07 15:18
I think everything which is not `com.microsoft.VSCode` will work fine.

**Comment by primalmotion** [comment] 2018-06-07 17:33
awesome!

**Comment by pi0** [comment] 2018-06-07 19:02
Same as @johnelm but for **Insiders**:

`sed -i -- 's/com.microsoft.VSCode/com.microsoft2.VSCode/g' /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Info.plist`

**Comment by pi0** [comment] 2018-06-07 19:22
@primalmotion True. This may be related to one of this "check fixes" in AppKit binary:

![image](https://user-images.githubusercontent.com/5158436/41121475-b9fc092a-6aad-11e8-9515-97dec4bc7e07.png)

**Comment by bpasero** [comment] 2018-06-08 05:40
@primalmotion 
> awesome! Could this be due to this https://worthdoingbadly.com/appkitcompat/

Interesting theory, but I can reproduce this with a different identifier (`com.microsoft.VSCodeExploration`) from a custom build we are using for testing Electron 2.0.x and I doubt that one would have made it into that list so quickly.

@pi0 can you explain what I am looking at in https://github.com/Microsoft/vscode/issues/35361#issuecomment-395535757 ?

**Comment by ddotlic** [comment] 2018-06-08 06:47
> Interesting theory, but I can reproduce this with a different identifier

@bpasero Speculation on my part, but there might be a _startsWith_ thing going on here, as long as the identifier is `com.microsoft.whatever` the fixes kick in? Either way, I've learned something interesting (Apple doing these kinds of fixes) 😄

**Comment by primalmotion** [comment] 2018-06-08 06:58
Yeah. I am sure they have some `if microsoft`. How could we blame them when you see office on mac ;) but know it leaks on a good product

**Comment by bpasero** [comment] 2018-06-08 08:48
@ddotlic @primalmotion good point, I guess we somehow need to validate that theory

**Comment by DirtyHairy** [comment] 2018-06-08 13:08
Confirmed; I've gone for `m1cr0s0ft`, and tabs work beautifully 🚀

**Comment by primalmotion** [comment] 2018-06-09 03:29
@bpasero I guess we could confirm by creating a new electron project with tabs and set the bundle identifier to com.microsoft.whatever and see if the tabs are misbehaving.

**Comment by bpasero** [comment] 2018-06-09 13:45
@primalmotion yes I can confirm that by just setting `CFBundleIdentifier` to `com.microsoft.`

Result:

![image](https://user-images.githubusercontent.com/900690/41192283-e14d1c22-6bfb-11e8-9c34-4e2bbcc256b0.png)

I guess the next questions are:
* how risky would it be to change the `CFBundleIdentifier` to something else and shipping that, what is the potential impact of doing that for the OS integration of VS Code
* can we reach out to Apple to remove this behaviour (that would probably need an OS update)

I also think that Apple might have done this for another application that is not necessarily VS Code because it goes bad as soon as the bundle identifier is `com.microsoft.`

**Comment by bpasero** [comment] 2018-06-09 13:54
@zhuowei as author of https://worthdoingbadly.com/appkitcompat/, I hope you don't mind my question: did you see `com.microsoft.VSCode` in the list of bundle identifiers? When I look at https://worthdoingbadly.com/assets/blog/appkitcompat/appkit_processed.html I see some Microsoft applications, but not VS Code. I wonder if that list is complete?

**Comment by zhuowei** [comment] 2018-06-09 14:06
@bpasero I didn't see it, but you could try loading AppKit in IDA and checking the `_NSDisableAutomaticWindowTabbingDefaultValueFunction` yourself.

**Comment by bpasero** [comment] 2018-06-10 06:06
@zhuowei thanks for looking into that. maybe this is actually not related to `allowsAutomaticWindowTabbing` but something else, because even though visually it does not look like native tabs are working, you can create multiple windows and open them in one tabbed window and switch between them. there is "just" this visual glitch where the tab bar is not displayed properly.

**Comment by jonathanmarvens** [comment] 2018-06-11 08:11
This bug is extremely frustrating and has negatively impacted my productivity in several ways; and I wasted literally at least 1hr to 1.5hrs trying to figure out why my window tabs just disappeared 😕. Until this is fixed, may I suggest adding a note re this bug to the `window.nativeTabs` setting documentation in __Visual Studio Code__ (at least for __High Sierra__ users)? Any fixes in the works for this that I can subscribe to?

Thank you for the hard work.

\- Jonathan

**Comment by tomitrescak** [comment] 2018-06-11 09:11
@jonathanmarvens read the thread, there is one liner that you need to execute to make it work. As simple as that.

**Comment by jrz** [comment] 2018-06-18 19:30
Well I would like to have double-tabs
One row for open windows / projects
One row for the files.

I'd love to have that for chrome too.. would allow me to run fullscreen without having so many windows open

**Comment by zhuowei** [comment] 2018-06-24 22:42
@bpasero I found the compatibility fix that's breaking the tabs!

I used a DYLD_INSERT_LIBRARIES library to swizzle `-[NSBundle bundleIdentifier]` to only return a non Microsoft bundle ID for some methods. Using this I was able to isolate the method that breaks tabs: `NSUseImprovedLayoutPassDefaultValueFunction`.

It indeed checks for a Microsoft bundle ID:

```
__text:00000000008E776D _NSUseImprovedLayoutPassDefaultValueFunction proc near
__text:00000000008E776D                                         ; DATA XREF: _NSUseImprovedLayoutPass+23↑o
__text:00000000008E776D                                         ; _NSInvalidateSelfLayoutOnFrameChangesDefaultValueFunction+23↓o ...
__text:00000000008E776D                 push    rbp
__text:00000000008E776E                 mov     rbp, rsp
__text:00000000008E7771                 push    rbx
__text:00000000008E7772                 push    rax
__text:00000000008E7773                 lea     rdi, cfstr_ComOvermacsPho ; "com.overmacs.photosweeper"
__text:00000000008E777A                 movsd   xmm0, cs:qword_C170E0
__text:00000000008E7782                 mov     esi, 0Ch
__text:00000000008E7787                 call    __CFAppVersionCheckLessThan
__text:00000000008E778C                 test    al, al
__text:00000000008E778E                 jnz     loc_8E781B
__text:00000000008E7794                 mov     rdi, cs:classRef_NSBundle ; void *
__text:00000000008E779B                 mov     rsi, cs:selRef_mainBundle ; char *
__text:00000000008E77A2                 mov     rbx, cs:_objc_msgSend_ptr
__text:00000000008E77A9                 call    rbx ; _objc_msgSend
__text:00000000008E77AB                 mov     rsi, cs:selRef_bundleIdentifier ; char *
__text:00000000008E77B2                 mov     rdi, rax        ; void *
__text:00000000008E77B5                 call    rbx ; _objc_msgSend
__text:00000000008E77B7                 mov     rsi, cs:selRef_hasPrefix_ ; char *
__text:00000000008E77BE                 lea     rdx, cfstr_ComMicrosoft_0 ; "com.microsoft."
__text:00000000008E77C5                 mov     rdi, rax        ; void *
__text:00000000008E77C8                 call    rbx ; _objc_msgSend
__text:00000000008E77CA                 test    al, al
__text:00000000008E77CC                 jz      short loc_8E77E1
__text:00000000008E77CE                 cmp     cs:_NSViewLinkedOnFuji_onceToken, 0FFFFFFFFFFFFFFFFh
__text:00000000008E77D6                 jnz     short loc_8E7847
```

Indeed, launching VSCode with this compatibility fix's NSUserDefaults value overridden on the command line:

```
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron -- -NSUseImprovedLayoutPass true
```

Fixes the tabs without changing the bundle ID.

I think this can be worked around with a [NSUserDefaults override](https://developer.apple.com/documentation/foundation/nsuserdefaults/1417065-registerdefaults?language=objc): in [Electron](https://github.com/electron/electron/blob/master/docs/api/system-preferences.md#systempreferencesregisterdefaultsdefaults-macos) it'll be something like `systemPreferences.registerDefaults({NSUseImprovedLayoutPass: true})` at startup.

**Comment by jonathanmarvens** [comment] 2018-06-24 22:47
@zhuowei Yes, this is wonderful news! Thank you for your work 🙂.

**Comment by bpasero** [comment] 2018-06-25 08:01
@zhuowei I really appreciate you taking the time to investigate this ❤️, but can you give me some pointers what the impact of `NSUseImprovedLayoutPass: true` is besides fixing this issue? I am a little bit worried that it could have other consequences that would be hard to understand without knowing and I am not able to find any documentation around this.

**Comment by zhuowei** [comment] 2018-06-25 12:57
@bpasero I'm not sure what the flag does: it's referred to by a bunch of other config variables, and it'll take too long to check what they all do:

![cropped1](https://user-images.githubusercontent.com/704768/41851334-8876551c-7855-11e8-95c3-dbfaf2c6fe3d.png)
![cropped2](https://user-images.githubusercontent.com/704768/41851335-889c9d30-7855-11e8-92c2-15793a40e420.png)

It might be a good idea to file a Radar with Apple to ask about why this "com.microsoft." check exists and whether it's possible to remove VS Code from the check in future macOS versions.

At any rate, Code-OSS has always worked fine, and its bundle ID doesn't trigger the patch, so I doubt changing it would cause any issues.

**Comment by ddotlic** [comment] 2018-06-25 13:04
> At any rate, Code-OSS has always worked fine, and its bundle ID doesn't trigger the patch, so I doubt changing it would cause any issues.

@zhuowei  First, thanks for looking into this, I'm sure everyone will agree that without your contribution, this item would have lingered quite a bit longer (not for the lack of trying)!

@bpasero I hope I speak for everyone using the insiders release: while we aren't expecting any breakage, we are aware that it's possible. Why don't you simply enable this flag right after the next release (due in a few days) and let us all verify that nothing is broken? (OTOH if you could turns this on _only_ for insiders, then turning it on right now is fine too). The nature of the "fix" is such that I really don't see any smarter way of testing this explicitly.

**Comment by bpasero** [comment] 2018-06-25 15:17
@zhuowei yeah I was just wondering if `NSUseImprovedLayoutPass: true` makes the application behave exactly like the OSS one that has a different bundle identifier or if there is more to it, but I guess we will have to just try it out.

@ddotlic we could always go for a change where `NSUseImprovedLayoutPass: true` is only set if the setting to use native tabs on macOS is also enabled. This means there is only a limited amount of people that would hit issues if there are any.

**Comment by bpasero** [comment] 2018-06-25 16:32
The fix will be in tomorrows insider build and should land in the June stable release (out next week) unless we find some critical issue with it.

I also reported this to Apple, let's see what happens there.

**Comment by bpasero** [comment] 2018-06-25 17:04
I spoke too soon, it looks like `systemPreferences.registerDefaults()` is a method that is not available in Electron 1.7.x (the version we are using). I can add this change to the Electron 2.0.x branch, but we are still at least 1-2 months away from shipping that given all the issues we are seeing with that version.

**Comment by nesl247** [comment] 2018-06-25 17:11
Could `systemPreferences.setUserDefault` not be used? https://github.com/electron/electron/blob/1-7-x/docs/api/system-preferences.md#systempreferencessetuserdefaultkey-type-value-macos

**Comment by bpasero** [comment] 2018-06-25 17:15
Ah maybe it was just a method rename?

**Comment by zhuowei** [comment] 2018-06-25 17:35
@nesl247 @bpasero setUserDefault writes a value permanently to the user preferences; registerDefaults writes it temporarily.

**Comment by bpasero** [comment] 2018-06-25 18:41
@zhuowei that would still be OK though right because the value would only be valid for the bundle identifier, not for all applications?

**Comment by bpasero** [comment] 2018-06-26 04:57
Let's try how it goes with `systemPreferences.setUserDefault()`, I pushed this for todays insider build.

**Comment by zhuowei** [comment] 2018-06-26 05:51
@bpasero Yeah, it will only affect our application. Anyways, my concern was that setUserDefault is persisted, so if a user turns on native tabs, the preference is set, and after the user disables native tabs, the preference is still set. registerDefaults is in memory only, so that may be a better choice. This should work though.

**Comment by bpasero** [comment] 2018-06-26 07:56
@zhuowei that is a good point, however I would at one point maybe even turn this on for everyone once we have a better understanding what the impact is

**Comment by ddotlic** [comment] 2018-06-26 08:18
@bpasero The fix works like a charm for me (latest insider from couple hours ago, latest possible macOS).

Thanks for not giving up on this!

**Comment by chrmarti** [comment] 2018-06-28 13:07
Trying to verify this (as per our end-of-milestone ritual), but don't see a difference between the default and native tabs enabled.

With native tabs enabled:
![image](https://user-images.githubusercontent.com/9205389/42036127-deb78d1a-7ae4-11e8-8e31-c879ae2ddccf.png)

**Comment by ddotlic** [comment] 2018-06-28 13:10
@chrmarti I'm not sure but it seems like you're looking at document tabs? These don't change either way.

The tabs this relates to are the ones for the workspace, you need to have multiple workspaces open to be able to see them.

**Comment by jeffaxial** [comment] 2018-06-28 13:11
@chrmarti Open a new window. The native tabs aren't for file tabs, they are for window/workspace tabs. If working correctly, when you open a new window, you should see 2 window tabs. If not working correctly (as it has been for months now), you will just see a blank gray bar at the top.

**Comment by fmunteanu** [comment] 2018-06-28 13:19
@bpasero when is the insider build will make it to stable release?

**Comment by chrmarti** [comment] 2018-06-28 13:19
Thanks! Still no tabs though, I get additional windows. I'm on:
- VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:11:09.274Z)
- OS version: Darwin x64 17.6.0

**Comment by jeffaxial** [comment] 2018-06-28 13:21
@chrmarti Make sure that "window.nativeTabs" is set to true in your user settings.

**Comment by ddotlic** [comment] 2018-06-28 13:22
@chrmarti You are holding it wrong 😉 You cannot verify whether this works or not unless you have triggered the appearance of tabs per workspace. This is another row of tabs above the document tabs.

**Comment by chrmarti** [comment] 2018-06-28 13:27
Got some help from @bpasero. Everything works now, thanks! Marking verified.

**Closed by chrmarti** 2018-06-28 13:27 UTC
Labels: bug, mac, os-integration, upstream, verification-found

**Comment by fmunteanu** [comment] 2018-06-28 13:42
@chrmarti when do we have this fix pushed into stable release?

**Comment by chrmarti** [comment] 2018-06-28 14:42
@fmunteanu With 1.25 some time next week.

**Comment by tomitrescak** [comment] 2018-07-06 07:13
I just launched 1.25 on my mac and tabs are not working ;(

**Comment by sebastianreloaded** [comment] 2018-07-06 07:37
for me it didn't work at first but after disabling nativeTabs and reenabling them through the new settings editor worked.

**Comment by pi0** [comment] 2018-07-06 07:39
I can confirm it is working like a charm now :)

MacOS: `10.13.4` 
VSCode: `1.25.0-insider`

![image](https://user-images.githubusercontent.com/5158436/42366009-4f3b045a-8115-11e8-98fa-fd2f0c846f5d.png)

**Comment by deyhle** [comment] 2018-07-06 07:50
Wait, so the native tabs are replacing the _file_ tabs? I was under the impression that native tabs are (finally) a way to properly switch between multiple project windows, and that we have the file tabs rendered in VS Code below those for each project. So with native tabs we're also losing the grid layout editor functionality?

**Comment by chabou-san** [comment] 2018-07-06 08:07
@deyhle They are not replacing the file tabs, see my screenshots below :

![screen shot 2018-07-06 at 10 04 43](https://user-images.githubusercontent.com/5517463/42367360-3fab6d92-8104-11e8-84f2-fd82941fb794.png)

It's behaving exactly as you'd have them to. I could have show you the grid layout functionality too, it's just that I didn't in my screenshot. But I can confirm it's also working. ;)

**Comment by fmunteanu** [comment] 2018-07-06 20:55
@chrmarti I don't see the feature listed in 1.25, can you please confirm it is implemented? Thanks!

**Comment by scottohara** [comment] 2018-07-07 00:10
@fmunteanu As it's not a new feature (but rather a fix to an existing feature that broke in High Sierra), you'll find it under the "Notable Changes" and "Thank You" sections of the release notes.

I can confirm that it is implemented and working in stable. 🎉 

![release_notes__1_25_0_and_limited_native_window_tabs_functionality_in_macos_high_sierra_ _issue__35361_ _microsoft_vscode](https://user-images.githubusercontent.com/289327/42404574-960ad42e-81cd-11e8-96c0-58fad7a3a085.jpg)


![release_notes__1_25_0_ _confluence-open-api-connect](https://user-images.githubusercontent.com/289327/42404543-56084ed8-81cd-11e8-99d7-1a84b5399b46.jpg)

**Comment by RoarkeRandall** [comment] 2018-07-07 00:18
I had changed plist setting to com.microsoft2.vscode earlier as a fix. 1.25
reverted that change and broke tabs for me again.
