### ISSUE TITLE
Stop showing the web page on first run after installing vs code

### ISSUE THREAD

**Issue by CodingSpiderFox** [microsoft/vscode#79510] opened 2019-08-20 13:43 UTC
It's incredibly annoying and a waste of time and network bandwith (one could argue that the bandwidth is not a problem but think if environmental pollution. Less server resources would be needed to host that page, other resources like switch capacity etc. would be used more efficiently and so on and so on)

**Comment by RMacfarlane** [comment] 2019-08-20 18:23
Thanks @CodingSpiderFox, this looks like a duplicate of https://github.com/microsoft/vscode/issues/14934. Let's track the issue there, please add any additional feedback to the discussion!

**Closed by RMacfarlane** 2019-08-20 18:23 UTC
