### ISSUE TITLE
Can't drag release notes editor to different editor group

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27492] opened 2017-05-30 07:43 UTC
- VSCode Version: 1.13 insider
- OS Version: Linux Fedora

Testing:  #27350

Steps to Reproduce:

1. open release notes
1. have tabs enabled 
1. try to drag the editor to a different group. 

Observe: this is not possible and you don't get any drag and drop feedback either. 

Unsure if this is @bpasero or @mjbvz

**Comment by bpasero** [comment] 2017-05-30 07:45
I think we have duplicates for this one.

**Comment by mjbvz** [comment] 2017-05-30 22:26
@dbaeumer Can you detail the steps  more.  Are you dragging the release notes into an existing group or trying to drag them to create a new group.

Possibly a duplicate of #25854?

**Comment by dbaeumer** [comment] 2017-05-31 05:18
@mjbvz start with one group. Drag the tab try to create a new group using D&D. E.g. drag it onto itself to the left or right part of itself. With other editors this give a nice feedback and creates a new group to the left or right.

**Comment by mjbvz** [comment] 2017-06-01 01:28
Thanks. Yes this sounds like a duplicate of #25854

**Closed by mjbvz** 2017-06-01 01:28 UTC
Labels: duplicate, webview
