### ISSUE TITLE
& added to command to run python code in terminal

### ISSUE THREAD

**Issue by mnrao2001** [microsoft/vscode#124763] opened 2021-05-27 15:33 UTC
Latest version of VS CODE with Python Extension
Issue: 
(base) C:\dock_python>& C:/<directory>/python.exe c:/<directory>/server.py
& was unexpected at this time.

Reproduce step:
Click on play button "Run Python File in Terminal"

**Comment by IllusionMH** [comment] 2021-05-27 19:21
/extPython

Also duplicate of https://github.com/microsoft/vscode-python/issues/16175

**Closed** 2021-05-27 19:22 UTC
Labels: *caused-by-extension
