### ISSUE TITLE
Update to 1.64 / 1.64.1  breaks Add/Edit function break point

### ISSUE THREAD

**Issue by jhoneill** [microsoft/vscode#142717] opened 2022-02-10 11:33 UTC
Does this issue occur when all extensions are disabled?:  Can not display the parts of the debug pane when all disabled.

- VS Code Version: 1.64.1
- OS Version: Windows 10.0.19042

Steps to Reproduce:
(this is with the PowerShell extension but I do not believe that it is extension specific)
1. Select debug on the activity bar
2. At the bottom of the side bar if Breakpoints is not expanded click the > symbol
3. Hover over Breakpoints, and click the + for Add function breakpoint. The input box no longer appears and a blank function break point appears
4. Right click the new blank break point and choose Edit Function BreakPoint ...   No edit box appears.

**Comment by gjsjohnmurray** [comment] 2022-02-10 12:31
/duplicate of #142010 and will be fixed in 1.64.2

**Closed** 2022-02-10 12:32 UTC
Labels: *duplicate, new release

**Comment by jhoneill** [comment] 2022-02-10 13:03
@gjsjohnmurray  Thanks. When I searched for breakpoint I didn't find that one - sorry for the duplicate.
