### ISSUE TITLE
Visual Studio and Jetbarins IDE like avtivity bar with smaller icon and vertical tool tip.

### ISSUE THREAD

**Issue by EvadeGame** [microsoft/vscode#128376] opened 2021-07-10 10:51 UTC
Current activity bar is too wide for low resolution screen especially when vertical split edit. A narrower activity bar like Visual Studio and Jetbrains IDE can be helpful.

### Example:
Visual Studio sidebar toggle (Icons come form Visual Studio Iconizer)
![VisualStudio](https://user-images.githubusercontent.com/76169889/125160266-97118900-e1ae-11eb-9a60-ec9e936e6a55.png)
Jetbrains IDE:
![Jetbrains](https://user-images.githubusercontent.com/76169889/125160315-d63fda00-e1ae-11eb-9774-9584f982ac68.png)

**Comment by misolori** [comment] 2021-07-12 20:27
Marking this as duplicate of https://github.com/microsoft/vscode/issues/128376 please upvote that issue

**Closed by misolori** 2021-07-12 20:27 UTC
