### ISSUE TITLE
Expect Shift+END to select to end of line

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#3686] opened 2016-03-03 19:09 UTC
With cursor in the middle of a line, when I press Shift + End, I expect the selection to extend to the end of line.   Current behavior seems to just move the cursor to the end of line.

**Comment by Tyriar** [comment] 2016-03-04 04:00
Cannot reproduce (Ubuntu 15.10).

**Comment by katopz** [comment] 2016-03-04 06:17
Cannot reproduce (Windows7 x64) v0.10.8

**Comment by mquandalle** [comment] 2016-04-21 21:32
It looks like there is no issue and this could be closed. @BurtHarris?

**Comment by Tyriar** [comment] 2016-04-21 21:40
Yes, closing this due to its age and I use it all the time without any problems.

**Closed by Tyriar** 2016-04-21 21:40 UTC
Labels: editor

**Comment by BurtHarris** [comment] 2016-06-20 15:32
Finally reproduced this, of course it was my silly mistake - I had changed my Numlock preference in the BIOS.
