### ISSUE TITLE
No terminal tab titles after enabling them

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121389] opened 2021-04-15 14:28 UTC
* enabled the `terminal.integrated.showTabs` for the very first time
* the tabs missed titles, there was much wasted space
* after reload the titles where showing

<img width="1343" alt="Screenshot 2021-04-15 at 16 27 39" src="https://user-images.githubusercontent.com/1794099/114886138-95326680-9e07-11eb-9563-60e379e85fa9.png">

**Comment by Tyriar** [comment] 2021-04-15 23:20
Maybe same root cause as https://github.com/microsoft/vscode/issues/121405

**Comment by Tyriar** [comment] 2021-04-16 19:17
Fixed in https://github.com/microsoft/vscode/commit/a3ac715bfb590c79639af9b5ed08ac79efe72b82

**Closed by Tyriar** 2021-04-16 19:17 UTC
Labels: bug, integrated-terminal, integrated-terminal-tabs
