### ISSUE TITLE
Color selector should work inside cascade layers @layer {}

### ISSUE THREAD

**Issue by eli-crow** [microsoft/vscode#156848] opened 2022-08-01 23:28 UTC
Issue Type: <b>Bug</b>

Expected Behavior:
- Colors in cascade layer delcarations should show the color picker when hovering
- A preview of the color should appear inline with the color expression
<img width="601" alt="expected" src="https://user-images.githubusercontent.com/19712894/182261941-e184f926-d817-4b0a-adfb-6a0190a56214.png">

Actual Behavior:
- Neither of the above occur
<img width="563" alt="actual" src="https://user-images.githubusercontent.com/19712894/182261948-07e2b327-ea0d-4466-b847-ebb623ecd8fe.png">

See: [MDN docs on cascade layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)

VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (15.00GB free)|
|Process Argv|--crash-reporter-id f431a099-00ad-4bab-a13a-92ba4d461919|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.9.0
vscode-css-formatter|aes|1.0.2
comment-tagged-templates|bie|0.3.1
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
better-toml|bun|0.3.2
gltf-vscode|ces|2.3.16
npm-intellisense|chr|1.4.2
hex-to-rgba|dak|1.0.0
dart-code|Dar|3.44.0
vscode-eslint|dba|2.2.6
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
shell-format|fox|7.2.2
godot-tools|gee|1.3.1
remotehub|Git|0.38.0
todo-tree|Gru|0.0.215
blender-development|Jac|0.0.17
svg|joc|1.4.19
rainbow-csv|mec|2.4.0
vscode-azureappservice|ms-|0.24.3
vscode-azureresourcegroups|ms-|0.5.5
vscode-docker|ms-|1.22.1
vscode-logicapps|ms-|1.1.9
csharp|ms-|1.25.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
azure-account|ms-|0.11.0
cpptools|ms-|1.11.4
live-server|ms-|0.2.13
remote-repositories|ms-|0.16.0
vsliveshare|ms-|1.0.5669
fix-json|oli|0.1.2
prisma|Pri|4.1.0
java|red|1.9.0
vscode-xml|red|0.21.2022062916
r|REd|2.5.2
rust-analyzer|rus|0.3.1148
vscode-stylelint|sty|1.2.2
wav-preview|suk|2.0.4
svelte-vscode|sve|105.20.0
vscode-java-debug|vsc|0.43.0
vscode-java-pack|vsc|0.25.0
vscode-maven|vsc|0.37.0
volar|Vue|0.39.4
change-case|wma|1.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by aeschli** [comment] 2022-08-24 11:53
duplicate of https://github.com/microsoft/vscode/issues/152058

**Closed by aeschli** 2022-08-24 11:53 UTC
