### ISSUE TITLE
Bottom panel's dropdown list behaves incorrectly when click it for the first time

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/vscode#26583] opened 2017-05-13 02:03 UTC
- VSCode Version: 1.12.1
- OS Version: Microsoft Windows [Version 10.0.16193.1001]

Steps to Reproduce:

1. Open vscode and toggle panel
2. Click the dropdown list in 'Output' or 'Terminal' tab
3. When click it for the first time all its items will downward shift by one item's height
4. After that it will behave normally

Click it for the first time:
![image](https://cloud.githubusercontent.com/assets/8000820/26021573/5aed7b26-37c3-11e7-8883-3b95cf9cfd37.png)

After that:
![image](https://cloud.githubusercontent.com/assets/8000820/26021579/6df6649e-37c3-11e7-9b64-32f391b3c836.png)

**Comment by egamma** [comment] 2017-05-13 07:14
Duplicate of #25700

**Closed by egamma** 2017-05-13 07:14 UTC
Labels: duplicate
