### ISSUE TITLE
Task running indicator does not appear after first terminate

### ISSUE THREAD

**Issue by osenvosem** [Microsoft/vscode#6230] opened 2016-05-10 06:46 UTC
- VSCode Version: Version 1.0.0 (1.0.0)
- OS Version: OSX 10.11.4 (15E65)

Steps to Reproduce:
1. Run task.
2. Terminate running task.
3. Run the task again.

![j5xdyswffl](https://cloud.githubusercontent.com/assets/6762673/15137663/e13d5a40-1693-11e6-890f-be7571dd89e4.gif)

**Comment by dbaeumer** [comment] 2017-04-10 08:38
Closing. I am not able to reproduce on latest.

**Closed by dbaeumer** 2017-04-10 08:38 UTC
Labels: tasks
