### ISSUE TITLE
Color picker has selector in the wrong position?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31654] opened 2017-07-28 10:14 UTC
testing #31457

* hover on color blue
* picker comes up
* :bug: the little selector-circle isn't on a color that is anywhere blue, now when I start dragging it I pick a very different color which is unexpected

<img width="368" alt="screen shot 2017-07-28 at 12 12 09" src="https://user-images.githubusercontent.com/1794099/28713124-1daef800-738e-11e7-9dd9-77d74102fd91.png">

**Comment by michelkaporin** [comment] 2017-07-28 12:35
Duplicate of #31642

**Closed by michelkaporin** 2017-07-28 12:35 UTC
