### ISSUE TITLE
Support to Auto hide panels

### ISSUE THREAD

**Issue by inamvar** [Microsoft/vscode#22653] opened 2017-03-15 09:08 UTC
# Please add auto hide feature for panels such  output, terminal, ...

**Comment by bpasero** [comment] 2017-03-15 10:40
@inamvar can you explain more how you would expect a panel to hide?

**Comment by mherodev** [comment] 2017-04-01 03:17
Adding details from my issue, here:

e.g. when reporting git information on commit/push/etc. the output panel will show itself, and only go away when the user takes action.

This for me means hitting ctrl+` twice after every git operation to get the output out of my way.

It'd be lovely if it had an autohide behavior when displayed passively, and a sticky behavior when brought up intentionally (via key command).

Alternatively, a push-pin icon for establishing its sticky/non-sticky behavior would also work great.

Thanks in advance!

Best
Michael

**Comment by joelpresence** [comment] 2017-06-20 18:17
Hi,

Is there an ETA for this feature?  Any way I can help?  :-)

Thanks!

**Comment by Tyriar** [comment] 2017-08-14 21:37
Duplicate of https://github.com/Microsoft/vscode/issues/10952

**Closed by Tyriar** 2017-08-14 21:37 UTC
Labels: feature-request, workbench
