### ISSUE TITLE
Minimap becomes weird after a while

### ISSUE THREAD

**Issue by ishidex2** [Microsoft/vscode#67106] opened 2019-01-25 09:49 UTC
- VSCode Version: 1.30.2
- OS Version: Linux Mint 19.1

Steps to Reproduce:

1. Wait until mini-map becomes weird 

Does this issue occur when all extensions are disabled?: Yes

![screenshot from 2019-01-25 12-45-24](https://user-images.githubusercontent.com/27076041/51737997-22f6cf80-209f-11e9-8f81-4d8c9abd3b1b.png)

**Comment by usernamehw** [comment] 2019-01-25 12:59
Possible duplicate of #58167

**Comment by sbatten** [comment] 2019-01-25 17:53
@ishidex2 does your behavior reproduce on the lastest insiders? https://code.visualstudio.com/insiders/

**Comment by mikemalisz** [comment] 2019-01-29 03:51
I get the same issue except it happens when the computer suspends for me. Also effects the terminal if I have it open.

I'm on the same VS Code version, OS is Fedora 29

**Comment by rjbrooksjr** [comment] 2019-02-08 12:58
I also have the same issue in both mini map and terminal after a suspend.

Same VS code version, Ubuntu 18.04

**Comment by bpasero** [comment] 2019-02-08 14:31
Does it reproduce with the latest stable version?

**Comment by aibtcare** [comment] 2019-02-08 14:56
> Does it reproduce with the latest stable version?

Seems to happen on the latest stable version and on the Insiders build as well. I noticed I get the same effect happening in Chrome (in the address bar) when waking from a suspend as well. As others have mentioned, I think it might be an issue with Chromium.

**Comment by aibtcare** [comment] 2019-02-14 20:32
If anyone else gets similar problems in Chrome too I started a thread on their bug tracking website: https://bugs.chromium.org/p/chromium/issues/detail?id=932219&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by alexandrudima** [comment] 2019-02-18 15:56
Related or possible duplicate: #68346

**Closed** 2019-03-08 07:15 UTC
Labels: linux, needs more info, upstream
