### ISSUE TITLE
html formatting (shift + alt+ f) not working with certain tags

### ISSUE THREAD

**Issue by gbreeze** [Microsoft/vscode#6341] opened 2016-05-13 10:26 UTC
The formatting on a .html file is not working if there is for example a `<template>` tag in it:

```
<template>
    <require from="valueConverters"></require>
    <div class="artistView" if.bind="!loading">
        <div class="row">
            <div class="col-xs-12">
                <h3>${artist.name}</h3>
            </div>
        </div>
                        </div>
</template>
```
Without the <template> tag, the formatting is working. Please support any tags here. Thanks.

- VSCode Version: 1.1.0
- OS Version: Win10

Steps to Reproduce:

1. Copy my code
2. paste it in VSCode
3. press shift + alt + f
4. code will not be formatted < --- wrong, should be formatted
5. remove the <template> tags
6. press shift + alt + f
7. code will be formatted

**Comment by aeschli** [comment] 2016-05-13 18:19
duplicate of https://github.com/Microsoft/vscode/issues/5426

See my comment there that explain what you have to do to also format `template` elements

**Closed by aeschli** 2016-05-13 18:19 UTC
