### ISSUE TITLE
Menu not dismissed on markdown rendered tab

### ISSUE THREAD

**Issue by cpxPratik** [Microsoft/vscode#68039] opened 2019-02-07 04:26 UTC
Issue Type: <b>Bug</b>

Go to help menu->Release Notes or Go to any extension detail page, then click on any top manu bar item, the expanded menu does not dismiss on clicking elesewhere. Same issue occurs on preview of markdown file.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.58GB (3.63GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.2.0
systemd-unit-file|coo|1.0.2
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.4.8
yarn-lock-syntax|mar|0.1.3
terraform|mau|1.3.7
dotenv|mik|1.0.1
mssql|ms-|1.4.0
vetur|oct|0.14.5
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
jinjahtml|sam|0.7.0
vscode-nginx|sha|0.6.0
twig|wha|1.0.2

</details>

**Comment by frobinsonj** [comment] 2019-02-07 10:11
Same issue.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.85GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
jshint|dba|0.10.20
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.8
ftp-sync|luk|0.3.7
vscode-apache|mrm|1.2.0
vscode-autoprefixer|mrm|2.2.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.7.0
es6-css-minify|olb|2.2.0


</details>

**Comment by mjbvz** [comment] 2019-02-12 01:31
Duplicate of #68313

**Closed by mjbvz** 2019-02-12 01:31 UTC
