### ISSUE TITLE
Process explorer not visible after alt-tab to VS Code

### ISSUE THREAD

**Issue by samal-rasmussen** [microsoft/vscode#81627] opened 2019-09-30 08:43 UTC
- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. Open process explorer
3. Alt-tab away from VS Code
4. Alt-tab back to VS Code

Expected result:
Process explorer window is visible

Actual result:
Process explorer window is hidden by VS Code main window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by samal84** [comment] 2019-09-30 08:45
Not being able to see the process explorer has made it really hard for me to diagnose a freeze I've been seeing when alt-tabbing to VS Code.

Alternatively the process explorer window could be made selectable in the alt-tab selection. So you could just alt-tab directly to the process explorer window.

**Comment by RMacfarlane** [comment] 2021-05-12 17:38
I've made a change to keep the process explorer always on top to fix https://github.com/microsoft/vscode/issues/120391, so going to go ahead and close this as a duplicate of that

**Closed by RMacfarlane** 2021-05-12 17:38 UTC
Labels: bug, workbench-diagnostics
