### ISSUE TITLE
intellisense stops working while editing big CSS/LESS

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#13997] opened 2016-10-19 12:26 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10 pro x64

Steps to Reproduce:
1. open big CSS file (over 5000 lines)
2. remove line of code
3. save **success**
4. add line of code
5. save **file wont save, editor will freeze after a while**

editing file shared over SMB (CentOS 7 running in hyper-v virtual machine on same PC)

**Comment by wUFr** [comment] 2016-10-19 12:32
both CSS and LESS files will make editor freeze.

**Comment by aeschli** [comment] 2016-10-19 17:05
@wUFr Just to confirm. That's without any extensions, right?
As there's nothing I'm aware that the css mode does on save, I wonder if it really has to do with css. Can you change the file suffix to .txt and see if it also fails on save?

**Comment by wUFr** [comment] 2016-10-20 08:08
tested again, its not extension related, VSC will freeze even when starting with

`code --disable-extensions` in cmd

**Comment by wUFr** [comment] 2016-10-20 08:20
video: https://www.youtube.com/watch?v=-sZmFCvoRRA

**Comment by aeschli** [comment] 2016-10-21 07:02
@wUFr Can you change the file suffix to .txt and see if it also fails on save?
I'm trying to find out if it is a css problem or a general file system issue.

**Comment by wUFr** [comment] 2016-10-21 08:17
.txt as "plain text" **saving OK**
.txt as "Less" **will save when removing code, won't save after adding code**
.txt as "CSS" **will save when removing code, won't save after adding code**

also found another way. When i edit file as Less or CSS and close it without saving changes (new code added), editor will freeze as well with file still visible in Explorer bar:

![code_freeze_on_close](https://cloud.githubusercontent.com/assets/10975377/19591380/068dc5b4-9777-11e6-8296-80a6a52884c5.png)

it probably has to do something with code highlighting/formating. When i add new styles, it will throw warning "[css] do not use empty rulesets" even tho, its not empty. More here:

![code_empty_ruleset](https://cloud.githubusercontent.com/assets/10975377/19591465/8654ab96-9777-11e6-8d1b-db4129ad3144.png)

**Comment by aeschli** [comment] 2016-10-26 15:00
Thanks a lot for the video. Unfortunately I still didn't succeed in reproducing your crash, repeating your steps. I'm on the same version, also Windows 10. I can not see the slowish syntax highlighting you see when scrolling down, so likely my machine is faster than yours.

Can you try to disable folding? 
"editor.folding": false

**Comment by wUFr** [comment] 2016-10-26 16:43
tried `"editor.folding": false` sadly, its still freezing. Gonna try it at home on AMD FX-8300 and few notebooks with i3 and pentium

**Comment by wUFr** [comment] 2016-10-28 13:48
same issue appears on my home PC, but only if i made file way larger with more lines of code (probably becouse my CPU at home is bit better - 8core 4,0GHZ vs. 6core 3,1GHZ)

strange thing is: when i copied everything to make it 2x or even 3x larger and immediately save it, it saved no problem, but after color highlighting appeared and added empty line or new CSS and save it, it froze

**so saving itself is probably ok and that's why it works when editing file as plaintext.. it must have to be something with CSS / Less code highlighting / formating**

**Comment by wUFr** [comment] 2016-11-01 14:58
btw these freezes were introduced after 1.2.1 version... that was last stable VSC version..

**Comment by wUFr** [comment] 2016-11-04 12:42
**looks like its fixed in 1.7.1** - file will take bit longer to save, but it will save without freezing whole editor

tested with 15K lines CSS

**Comment by wUFr** [comment] 2016-11-08 16:41
reopening - saving big files works, but will break intellisense

**Comment by aeschli** [comment] 2016-11-08 18:12
@wUFr Can you add the setting "css.trace.server": "verbose" and go the the CSS language service tab in the Output view?

**Comment by wUFr** [comment] 2016-11-09 14:14
@aeschli output: https://wufr.cz/vsc_intellisence_css-less_debug.txt after intellisense stopped working, it stopped generating new debug info

CSS being used for testing: https://www.kdpcr.cz/layout/css/theme.css

*sorry for link to TXT file, tried to paste it in pastebin, but chrome didn't like it*

**Comment by wUFr** [comment] 2017-01-12 12:15
sadly problem still persists in version 1.8.1

I will buy you a beer if you make it working! :D

**Comment by aeschli** [comment] 2017-02-01 17:02
No luck on my side to reproduce this...

**Comment by aeschli** [comment] 2017-02-21 22:27
Most likely a duplicate of #19840, now fixed. Please try the latest [insiders](https://code.visualstudio.com/insiders) build.

**Closed by aeschli** 2017-02-21 22:27 UTC
Labels: freeze-slow-crash

**Comment by wUFr** [comment] 2017-02-22 12:03
@aeschli thanks for fixing, i can notice slight delay, but huraay, its actually working now :)

promised beer bellow:

```
  .   *   ..  . *  *
*  * @()Ooc()*   o  .
    (Q@*0CG*O()  ___
   |\_________/|/ _ \
   |  |  |  |  | / | |
   |  |  |  |  | | | |
   |  |  |  |  | | | |
   |  |  |  |  | | | |
   |  |  |  |  | | | |
   |  |  |  |  | \_| |
   |  |  |  |  |\___/
   |\_|__|__|_/|
    \_________/
```
