### ISSUE TITLE
Markdown syntax highlighting mis-italicizes underscored words

### ISSUE THREAD

**Issue by nategraf** [Microsoft/vscode#36083] opened 2017-10-11 17:39 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
json-tools|eri|1.0.2
sftp|lix|0.8.4
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
partial-diff|ryu|0.3.3
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Create  new markdown document
2. type a word separated by underscores

![mdbug](https://user-images.githubusercontent.com/5684286/31457028-63a6ef80-ae70-11e7-8748-697125ee1ec9.png)

Reproduces without extensions: Yes

The issue is that the syntax highlighting italicizes the middle bit or the word, even though it will not be rendered in italics

**Comment by mjbvz** [comment] 2017-10-11 18:01
Duplicate of https://github.com/Microsoft/vscode/issues/34669

**Closed by mjbvz** 2017-10-11 18:01 UTC
Labels: duplicate, grammar, markdown, new release
