### ISSUE TITLE
When I write code, intellisense propose only one item

### ISSUE THREAD

**Issue by maxime-aubry** [microsoft/vscode#111401] opened 2020-11-27 08:16 UTC
Hello.

I have bug when I write code.
When I write code, vs code proposes an only one item.

Here, I have a class with 4 members.
When I write "this.", I VS Code does not provide all choices. Only the first.

![image](https://user-images.githubusercontent.com/6122959/100426385-0eb3fd00-3091-11eb-9e53-d5c2a66a76ea.png)

I did not change vs code settings, so I think it's a bug.
Thanks.

**Comment by jrieken** [comment] 2020-11-27 08:39
/duplicate of https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206

**Closed** 2020-11-27 08:40 UTC
Labels: *duplicate, suggest
