### ISSUE TITLE
Make the Git "Thinking" badge respect the activityBarBadge.foreground rule

### ISSUE THREAD

**Issue by dhershman1** [Microsoft/vscode#58202] opened 2018-09-07 15:11 UTC
Currently the foreground for the clock icon used when git is "thinking" or processing something only stays true to the overall "dark" or "light" theme setting. It doesn't seem to change based on the `activityBarBadge.foreground` rule.

![example](https://user-images.githubusercontent.com/8997380/45227525-b6fe0100-b28e-11e8-98a1-0e761aad3f79.png)

Side Note: I selected Feature Request because I wasn't sure if this was intended or not

**Comment by usernamehw** [comment] 2018-09-07 15:42
Duplicate of #44604

**Comment by dhershman1** [comment] 2018-09-07 16:04
Ah, I was being too specific with my searching.

**Closed** 2018-09-07 17:16 UTC
Labels: git
