### ISSUE TITLE
Empty file named "... ungültige Kodierung" (= invalid encoding) is created after closing Visual Studio Code

### ISSUE THREAD

**Issue by managedata** [Microsoft/vscode#15335] opened 2016-11-11 08:41 UTC
- VSCode Version: 1.7.1
- OS Version: cat /etc/issue

Steps to Reproduce:

1. Create a link on the gnome desktop for Visual Studio Code -> /usr/share/code/code
2. Doubleclick new link on desktop to start VSC
3. Close Visual Studio Code
4. A file with a crytic name is created on the desktop

When I start VSC directly from /usr/share/code/code the file is not created.

**Comment by sungb** [comment] 2017-03-11 05:15
Problem still shows in 1.10.2 ubuntu 32 bit version.

Running cli cmd with file name argument always creates a zero bye cryptic file in the same dir.
code <somefile>

**Comment by Tyriar** [comment] 2017-03-13 18:54
@sungb can you provide some more details?

- What's the output of `echo $LANG`?
- What's in your settings.json file?

**Comment by sungb** [comment] 2017-03-14 04:20
@Tyriar thanks for responding.

Here is the info requested.
`echo $LANG` gives `en_US.UTF-8`
I commented out everything in `.config/Code/User/settings.json`, and the issue is still there.

And one more thing, xubuntu 14.04 is running as guest os on vmware fusion on mac host.  Maybe it happens with vm graphics. not sure.

Thanks again for looking into the issue.  It leaves this 0 byte garbage file everywhere I opened files, and it's quite frustrating.

**Comment by sungb** [comment] 2017-03-14 04:27
<img width="703" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3499071/23885902/f61e6206-08b9-11e7-81e8-d9d182fdb683.png">
The screenshot of the file.

**Comment by managedata** [comment] 2017-03-14 06:47
Maybe it's a problem with VMWare. I used Debian Linux on a VMWare workstation.

**Comment by sungb** [comment] 2017-03-14 10:47
@managedata thanks for the data.  So the problem also exists with Windows host, when used with VMWare.

**Comment by Tyriar** [comment] 2017-03-14 22:03
Interesting... Seen anything like this @bpasero? TLDR: It looks like VMWare might be playing a part in some random file showing up when launching the Linux desktop shortcut but not when launching from the CLI.

**Comment by bpasero** [comment] 2017-03-15 05:15
No, not heard before.

**Comment by sungb** [comment] 2017-03-15 06:31
@Tyriar @bpasero running cli cmd `code some.txt` create the garbage file. Always reproducible.

**Comment by bpasero** [comment] 2017-03-15 09:09
@sungb how about using the executable directly instead of our cli launcher? Wondering if this is produced from the launcher or the app.

**Comment by sungb** [comment] 2017-03-15 10:06
@bpasero  Even with cli, when run code without a file argument, the file is not produced.  But, at this point if I open a file via code ui, the file gets produced.

**Comment by bpasero** [comment] 2017-03-15 10:49
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sungb** [comment] 2017-03-16 06:41
@bpasero @Tyriar 
I think I found the culprit.  Once I uninstalled [microsoft cpptools](https://github.com/Microsoft/vscode-cpptools) the garbage file does not get produced anymore.

**Comment by sungb** [comment] 2017-03-16 06:43
@bpasero The insiders build show the same symptom if microsoft cpptools are installed.

**Comment by bpasero** [comment] 2017-03-16 06:56
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-03-16 06:56 UTC
Labels: bug, linux, needs more info

**Comment by sungb** [comment] 2017-03-16 07:04
@bpasero Thank you.

**Comment by sean-mcmanus** [comment] 2017-03-16 13:57
This bug was reported 6 months ago, but we still don't have a repro or a fix: https://github.com/Microsoft/vscode-cpptools/issues/217 .

**Comment by Tyriar** [comment] 2017-03-16 19:04
@sungb @managedata providing @sean-mcmanus with your OS/version and output of `localectl` on https://github.com/Microsoft/vscode-cpptools/issues/217 would probably be helpful.
