### ISSUE TITLE
Program Icon is default Electron icon

### ISSUE THREAD

**Issue by grantborthwick** [Microsoft/vscode#36783] opened 2017-10-23 22:26 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (c1be82537d9fda852a258851f48ea78b7fc8a7a3, 2017-10-23T04:18:13.902Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
team|ms-|1.122.0

---

Steps to Reproduce:

1. Install latest update
2. Launch program

Reproduces without extensions: Yes

![electron](https://user-images.githubusercontent.com/2301725/31916283-bcc2bd20-b806-11e7-8978-7e6c8ab58126.png)

**Comment by mjbvz** [comment] 2017-10-23 22:34
Duplicate of #36665

**Closed by mjbvz** 2017-10-23 22:34 UTC
Labels: duplicate
