### ISSUE TITLE
comments brackets

### ISSUE THREAD

**Issue by ArtGarm** [Microsoft/vscode#47300] opened 2018-04-06 09:07 UTC
Issue Type: <b>Bug</b>

i cant hide parts of code between comment 
it was wery cool in last wersion

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_479349|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vue-snippets|hol|0.1.5
mssql|ms-|1.3.0
vetur|oct|0.11.7
vscode-icons|rob|7.22.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2018-04-06 16:53
Please give a specific example of what you're trying.

**Comment by ArtGarm** [comment] 2018-04-09 08:57
hello
for me was awesome hide parts of code between comments
as for js and scss but after update its doesn't work(

http://joxi.ru/Y2LeypBHnp5JpA

2018-04-06 19:54 GMT+03:00 Rob Lourens <notifications@github.com>:

**Comment by ArtGarm** [comment] 2018-04-09 08:57
hello
for me was awesome hide parts of code between comments
as for js and scss but after update its doesn't work(

**Comment by aeschli** [comment] 2018-04-10 08:36
duplicate of #46591

**Closed by aeschli** 2018-04-10 08:36 UTC
Labels: needs more info
