### ISSUE TITLE
Git console is super buggy

### ISSUE THREAD

**Issue by vasametropolis** [Microsoft/vscode#6612] opened 2016-05-21 15:51 UTC
- VSCode Version:

1.1.1

- OS Version:

Windows 7

Scenario 1:

We have git hooks installed (a mix of #!/bin/sh and #!/bin/node). The printout messages from these do not show in the VSCode console, only when running from command line (in this case, CMD)

Steps

1. Try to commit something with an improper commit message 
2. VSC says the commit failed, offers to show console output for git. Console does not contain output message.

Scenario 2:

We use git pull rebase by default (git config --global pull.rebase true). When Syncing or pulling, VSC will show an error if it didn't succeed. When you show the console output for the error, it does not contain the output message.

Steps

1. Try to rebase after all your commits are in
2. VSC says the action failed, offers to show console output for git. Console does not contain rebase output

Scenario 3:

All git console output just randomly stops sometimes (sometimes totally blank) and won't fix until restarting the editor. Dies again shortly after after usually. It may be dying from one of the above scenarios, however.

Summary:

In all scenarios, git from the command line produces output just fine.

**Comment by joaomoreno** [comment] 2016-05-24 08:00
Duplicate of #5838

**Closed** 2016-05-24 08:18 UTC
Labels: duplicate
