### ISSUE TITLE
Odd duplicate phantom editor in tree

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode#67521] opened 2019-01-30 07:13 UTC
Issue Type: <b>Bug</b>

It's hard to explain this one.  It's best to see it in action via attached animated GIF.  Whenever clicking on a file to open an editor there is a duplicate/phantom entry that shows up in the tree, but the tree pane also doesn't resize it's height to account for the phantom editor entry.  If another file is clicked, the phantom entry changes to the name of the newly clicked file.  In the animation I successively clicked on 4 different files, pausing in between each to scroll the editor tree pane to show that there is one more entry out of view.  This is with all extensions disabled.
![vscode-editor-tree-issue](https://user-images.githubusercontent.com/430481/51964424-8c2a6a00-2434-11e9-9a70-fe3f8ad86d64.gif)

VS Code version: Code - Insiders 1.31.0-insider (2c987b20a4d65ee51c48b9e4eb8f50c926199468, 2019-01-30T06:24:37.529Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2672)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.99GB (2.51GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by isidorn** [comment] 2019-01-30 11:35
Good catch however duplicate of https://github.com/Microsoft/vscode/issues/67041#issuecomment-458580679

Thanks for using insiders!

**Closed** 2019-01-30 11:35 UTC
Labels: *duplicate
