### ISSUE TITLE
Open panel maximized doesn't work

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#127981] opened 2021-07-05 07:51 UTC
1. 
```js
"workbench.panel.opensMaximized": "always",
```

2. Maximize the panel
3. After window reload it's no longer maximized

**Comment by sbatten** [comment] 2021-07-06 17:27
@bpasero it seems that even though we restore properly, this workaround is no longer valid as more than one event is being sent on startup https://github.com/microsoft/vscode/blob/66de74f58cdefe164f114093a735902aa5c95517/src/vs/workbench/browser/layout.ts#L280-L290

**Comment by bpasero** [comment] 2021-07-07 06:17
@sbatten possible, but how does that relate to the setting `workbench.panel.opensMaximized`? I think the issue here is that when a panel is maximized and you restart the panel is no longer maximized, independent from this setting.

I feel this is a grid state issue, I would not think you need to listen to editor events for this to work. The grid should persist its UI state and restore it on startup, ideally without flicker.

**Comment by sbatten** [comment] 2021-07-07 15:22
@bpasero Yes, the grid does indeed store and restore the state correctly. The issue is that certain editor events force the editor to show again (i.e. unmaximize the panel). In the past, only one of these events triggered on startup so we knew to ignore it. Now, 2 events are triggering, but I don't know how many we should ignore. or maybe there should just be a delay to registering that listener.

**Comment by bpasero** [comment] 2021-07-07 16:21
Hm, maybe delay listening for events further until editors have restored to be independent from the number of events firing. We have:

https://github.com/microsoft/vscode/blob/f489dc7b2f91786d7af6a75ce36ca735047e1d79/src/vs/workbench/services/editor/common/editorGroupsService.ts#L213-L213

Which will resolve when the editor part itself has been created (and editor groups and inputs are visible but maybe not yet resolved), and then:

https://github.com/microsoft/vscode/blob/f489dc7b2f91786d7af6a75ce36ca735047e1d79/src/vs/workbench/services/editor/common/editorGroupsService.ts#L224-L224

Which will resolve when all active editors have loaded.

I feel the first event would be more correct because the second could hang for seconds depending on how slow the editor loads.

**Comment by sbatten** [comment] 2021-07-07 18:03
I ended up using the second one because the first one was still before the startup events were firing. I don't think this is a huge issue to be later since it will only mean someone who has a maximized terminal on startup that is rushing to open a new editor before it is ready will not auto swap to the editor.

**Comment by sbatten** [comment] 2021-08-05 15:41
@meganrogge no i don't think that is the intent of that setting. @rzhao271 worked on that item and I believe the intent is to determine the behavior when the user triggers the open panel command, not on restore.

**Comment by rzhao271** [comment] 2021-08-05 19:53
Closing for now, because reloading results in a more consistent state especially for debugging purposes.
If it is important for the panel to show up maximized after a reload, that can be placed in a new feature request.

**Closed by rzhao271** 2021-08-05 19:53 UTC
Labels: bug, verified, layout
