### ISSUE TITLE
Account still claims it is used by settings sync

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96358] opened 2020-04-28 09:35 UTC
re #96226

* turn on settings sync
* pick MSFT account
* wait till "sync is on" message appears
* turn off settings sync
* select accounts, MSFT account, sign out
* ⚠️ a message appears that says pref-sync is still using my account. this is creepy!

<img width="733" alt="Screenshot 2020-04-28 at 11 33 49" src="https://user-images.githubusercontent.com/1794099/80471868-495f8680-8944-11ea-841e-5e3b06af0fee.png">

**Comment by RMacfarlane** [comment] 2020-11-03 17:20
Closing, as this is not longer reproducible since this dialog now only lists extension usage of accounts. I've created https://github.com/microsoft/vscode/issues/109926 to track adding back settings sync in the sign out dialog

**Closed by RMacfarlane** 2020-11-03 17:20 UTC
Labels: authentication
