### ISSUE TITLE
Watcher crashes when large folder has lots of changes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#29711] opened 2017-06-28 07:41 UTC
Refs: #29478
Linux Ubuntu 14, vscode 64 bit

1. Clonse vscode, electron, open both repositories in VS Code
2. while VS Code is open do a `npm install` in electron, and then a `scripts/npm.sh i` in vscode
3. I see the file watcher crashing and all file events after that are ignored for the second repository

Do we have file watcher per repo? If yes then it seems like in this case the file watcher for repository vscode crashed. Could we detect a crash and just restart it?

![screen shot 2017-06-28 at 09 38 10](https://user-images.githubusercontent.com/1926584/27625651-9c472ac2-5be5-11e7-9f2d-436bd974b7f8.png)

**Comment by Tyriar** [comment] 2017-07-20 17:20
Cannot repro on macOS, will have to try on Linux.

@isidorn did you increase your watch limit as in https://code.visualstudio.com/docs/setup/linux#_error-enospc?

**Comment by isidorn** [comment] 2017-07-21 07:28
@Tyriar yes, I increased it to 524288

**Comment by bpasero** [comment] 2017-07-21 15:01
It would be nice if this limit could be set per-process and actually by the watcher process itself. Not sure that is possible though.

**Comment by Tyriar** [comment] 2017-07-21 15:13
I think it's a system-wide limit and you need sudo to be able to set it, so we can't really do it on our side AFAIK.

**Comment by bpasero** [comment] 2017-07-21 16:19
Yeah, sucks. I was always hoping that [`process.setFdLimit(maxDescriptors)`](https://github.com/electron/electron/blob/master/docs/api/process.md#processsetfdlimitmaxdescriptors-macos-linux) could be used to set it higher, but it will never be higher than the system limit it seems.

**Comment by bpasero** [comment] 2021-09-22 17:18
This bug is quite old and we have since then updated to a newer version of `nsfw`. I cannot reproduce, on Ubuntu 20 at least. I suggest we close this. I also didn't see this reported from other users.

**Closed** 2021-09-30 11:25 UTC
Labels: help wanted, needs more info, upstream, linux, file-watcher
