### ISSUE TITLE
Escape characters in links

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#175994] opened 2023-03-03 01:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows 11

Steps to Reproduce:

1. Create a markdown file test.md
2. Enter the following:

```markdown
[test link](https://www.vultr.com/news/Constant%2C-Vultrs-parent-company%2C-surpasses-%24125M-in-ARR/)

https://www.vultr.com/news/Constant%2C-Vultrs-parent-company%2C-surpasses-%24125M-in-ARR/

```

3. Use the Ctrl+click shortcut to open two web pages in sequence.
4. The two URLs are exactly the same, but the former will be escaped before opening. The former escapes `%2C` as `,` and `%24` as `$`, and the latter opens directly without escaping. Some websites/blog programs may not be able to handle it, resulting in jumping to other pages.

**Comment by mjbvz** [comment] 2023-03-06 16:58
Duplicate of https://github.com/microsoft/vscode/issues/156859#issuecomment-1263039057 (see comment for details)

**Closed by mjbvz** 2023-03-06 16:59 UTC
