### ISSUE TITLE
Idea of snippet feature enhancement

### ISSUE THREAD

**Issue by yangshuairocks** [Microsoft/vscode#56238] opened 2018-08-13 01:12 UTC
> Code snippets are templates that make it easier to enter repeating code patterns, such as loops or conditional-statements.

Above is copied from VSCode documentation website. Yes, we do need to `enter repeating code patterns` from time to time. But sometime, we also want to create files in our project and this is **a part** of the `repeating pattern`. For example, when I have a snippet like this:

```
{
    "link_to_css_file": {
        "prefix": "csssrc",
        "scope": "html",
        "body": [
          "<link href=\"${1:main}.css\" rel=\"stylesheet\" media=\"screen\">"
        ],
        "description": "Link to a css file"
    },
}
```

When I type `csssrc` and press <kbd>Tab</kbd>, the above snippet is inserted. But remember this `repeating pattern` doesn't finished, and the next step I will do is probably manually create a file called `main.css`. My idea of this snippet feature enhancement just comes from this situation. So my suggestion is, we can add some special comments in the snippet like this:

```
{
    "link_to_css_file": {
        "prefix": "csssrc",
        "scope": "html",
        "body": [
          "<link href=\"${1:main}.css\" rel=\"stylesheet\" media=\"screen\">"
        ],
        "description": "Link to a css file"
    },
}

//<file start>, name: $1.css
// body {
//     margin: 0
// }
//<file end>
```

By using `//<file start>` and `//<file end>`, vscode knows that a file need to be generated and its name is `$1.css`. By the end of the snippet expanding process, we have the value of `$1` so the file name may be something like `main.css` and vscode will create it at the root folder of the project. We can specify the generated file is in a specific folder too like this.

```
{
    "link_to_css_file": {
        "prefix": "csssrc",
        "scope": "html",
        "body": [
          "<link href=\"${1:main}.css\" rel=\"stylesheet\" media=\"screen\">"
        ],
        "description": "Link to a css file"
    },
}

//<file start>, name: stylesheets/$1.css
// body {
//     margin: 0
// }
//<file end>
```
vscode notice the folder `stylesheets` doesn't exist so it will be  created automatically and the file `$1.css` will be placed into it. 

We can create multiple **file section**s in a snippet. Let's say we have this snippet:

```
{
    "link_to_css_file": {
        "prefix": "csssrc",
        "scope": "html",
        "body": [
          "<link href=\"${1:main}.css\" rel=\"stylesheet\" media=\"screen\">",
          "<script type=\"text/javaScript\" src=\"js\${2:main}.js\"></script>"
        ],
        "description": "Link to a css file"
    },
}

//<file start>, name: stylesheets/$1.css
// body {
//     margin: 0
// }
//<file end>

//<file start>, name: js/$2.js
// var that = this;
//<file end>
```
Here when we filled `$1` and `$2`, vscode will insert the `link` and `script` tags into our text document, it will also create two folders `stylesheets` and `js`. A file named `main.css` with the specified content will be created in the folder `stylesheets` and a file named `main.js` will be created in the folder `js`. 

For blob objects like an image file, we can also add them with base64 encoded text string like this.

```
{
    "link_to_css_file": {
        "prefix": "csssrc",
        "scope": "html",
        "body": [
          "<link href=\"${1:main}.css\" rel=\"stylesheet\" media=\"screen\">",
          "<script type=\"text/javaScript\" src=\"js\${2:main}.js\"></script>"
        ],
        "description": "Link to a css file"
    },
}

//<file start>, name: stylesheets/$1.css
// body {
//     margin: 0
// }
//<file end>

//<file start>, name: js/$2.js
// var that = this;
//<file end>


//<blob start>, name: image/background.png
// iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAYAAABG1c6oAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAB3RJTUUH4ggNAQUUMy3JOgAAAAd0RVh0QXV0aG9yAKmuzEgAAAAMdEVYdERlc2NyaXB0aW9uABMJISMAAAAKdEVYdENvcHlyaWdodACsD8w6AAAADnRFWHRDcmVhdGlvbiB0aW1lADX3DwkAAAAJdEVYdFNvZnR3YXJlAF1w/zoAAAALdEVYdERpc2NsYWltZXIAt8C0jwAAAAh0RVh0V2FybmluZwDAG+aHAAAAB3RFWHRTb3VyY2UA9f+D6wAAAAh0RVh0Q29tbWVudAD2zJa/AAAABnRFWHRUaXRsZQCo7tInAAACJklEQVQ4jc2Tz2sTURDHP0naYrKNu0mbghTlHawac7PQHAL2GKUNHirYQ6XgqV7q2Z56qYj4LyT/Q9JAIP0LjNWDNQqthx5sQVJouuYl0k3yPLQb8nNT8OIXBvbNm/kwM2/HZZqmajSaGIZOu8rlMyqV39T+1PBe86LrOn6/v3Uvq1WajQbdcimlFIBlWeRyOT4Wdinu7XH06xhpSmRNonk1tOsa4uYt7twN8+hxnFgshp0nZRWPx31BVEqpVDKlIuGIAjosNBlqWffd4kJCpdNpZcs0TXV6WlauueicKnwoACCE6GlhkA4PDwFYXEjw7v1bwvfuX7QMqEEgWZGUTkodvu5YG/xma4vXGxt4IuHIplW3+lag+TSeLi2RSDzhwewsTdWkWCwyOjJKQA9g1S2mb0wDsJ3dplFvghBCtZs9y/mH8+rb96Jq1/n5uUolU625tue15twNtGFOSqfT6nJUPbmuy4+OVvcP9pm5PeP4KPF4nHw+3zFTzavh7oYtLiSGwgCWny33+GRNdgIBgkFjKAxg3Ofr6+8Bftr9fCXgl6/Fvn6PYRib9sEwDA5+HDARnCAajQ6EyWqV5ysraD6NsbEx5wpDkyHWX62TyWQGAl+srlI6KTEVmnKuECCgBwBIppKcnZn4/eO43W6Ojn+SzWRZe7lGfmcHIQT9FqLnt2mXvVZCiI41dNp5R6AtWZEAaOPasFBGhkZcEWSr51H+Vf8/8C8zyyrm8/kxHgAAAABJRU5ErkJggg==
//<blob end>
```

Here when we insert the snippet, the folder `image` will also be created and the image file `background.png` will be created in the folder and will be filled using the the base64 data.

Hope you can consider my idea.  Thanks.

**Comment by jrieken** [comment] 2018-09-10 10:16
Closing as dupe of #10561

**Closed** 2018-09-10 10:16 UTC
Labels: *duplicate, feature-request, snippets
