### ISSUE TITLE
brackets match guide line is not rendered correctly

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#52033] opened 2018-06-15 12:24 UTC
Issue Type: <b>Bug</b>

# reproduce
edit a golang or C/CPP source file.
click on a bracket.
the bracket match line is not render between the matching brackets, but the upper level match brackets.

![image](https://user-images.githubusercontent.com/14314478/41467625-c8722e08-70d9-11e8-9ffb-9b9e153cb996.png)

just as the above picture, the current matching brackets are lines 103 and 105, but brackets in lines 99 and 109 is rendered.

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B950 @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.60GB (3.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.18.4
vscode-language-pack-zh-hans|MS-|1.24.3
Go|ms-|0.6.82

</details>

**Comment by shizengzhou** [comment] 2018-06-16 20:07
I think this is as designed. The line is indent guide line not brackets match guide line.

**Comment by alexandrudima** [comment] 2018-06-18 07:39
Duplicate of #49342

**Closed by alexandrudima** 2018-06-18 07:39 UTC
Labels: editor, editor-brackets
