### ISSUE TITLE
Centered layout fixed width

### ISSUE THREAD

**Issue by JSRossiter** [microsoft/vscode#127569] opened 2021-06-29 21:14 UTC
When using centered layout it would be nice to have the option to keep a fixed width. I switch my window between maximized, 1/2 screen width and 1/3 screen width regularly and it's not possible to set a width that is usable at 1/3 and accomplishes the purpose of centering when maximized.

**Comment by isidorn** [comment] 2021-06-30 07:41
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Closed** 2021-08-06 12:27 UTC
Labels: feature-request, layout, *out-of-scope

**Comment by akbyrd** [comment] 2021-09-03 18:10
Dupe of https://github.com/microsoft/vscode/issues/54731 which is still open and has more traction.
