### ISSUE TITLE
Twelve Second Delay In Startup Due To Electron + Audio

### ISSUE THREAD

**Issue by JohnMarzulli** [microsoft/vscode#154591] opened 2022-07-09 03:00 UTC
Issue Type: <b>Performance Issue</b>

My installation of VS Code has started suffering from a mysterious delay during startup.

The period from launching Code to a window being displayed is averaging 13 seconds. This is when launched from the Taskbar OR from terminal (Win11)

I have attempted to capture the issue with `code --prof-startup` BUT starting code with `--prof-startup` results in a normal startup time (<3 seconds)

Windows Event view has not revealed any errors during the startup period. I have tried unplugging network jacks, disabling networking entirely, and more to see if this is a call timeout.

Other systems I own on Windows 11 do not suffer from this delay. I have attempted disabling all extensions. This did not change the launch time.

Interestingly Chrome appears to suffer from the same delay. The latest version of Edge launches fine.

WPR/WPA files of the launch are available upon request.

![image](https://user-images.githubusercontent.com/23081324/178089105-868a8cbf-0082-46c3-96ee-22ad626807f2.png)

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (24.09GB free)|
|Process Argv|--crash-reporter-id 187b8ecd-61de-4168-bc95-0c5938d2350e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   125	 20288	code main
    0	    88	   172	   issue-reporter
    1	   219	 14316	   window (● <REDACTED> • Untitled-1 - StratuxHud - Visual Studio Code)
    1	   129	 16256	   gpu-process
    0	   314	 17252	   extensionHost
    0	   138	  1468	     "c:\Users\John Marzulli\.vscode\extensions\sourcery.sourcery-0.12.3\sourcery_binaries\install\win\sourcery.exe" lsp
    0	    10	 10852	       console-window-host (Windows internal process)
    0	   101	 16796	     "C:\Users\John Marzulli\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\John Marzulli\.vscode\extensions\ms-python.vscode-pylance-2022.7.20\dist\server.bundle.js" --cancellationReceive=file:d182e9c4a5ae0ff475abf7d8e20720c21045715fbc --node-ipc --clientProcessId=17252
    0	    76	 20324	     "C:\Users\John Marzulli\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\John Marzulli\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17252
    0	    66	 19376	   crashpad-handler
    0	   117	 19536	   shared-process
    0	    82	 19672	     ptyHost
    0	    85	 12052	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	     8	 16036	       console-window-host (Windows internal process)
    0	    89	 19704	     fileWatcher
    0	    67	 20040	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● <REDACTED> • Untitled-1 - StratuxHud - Visual Studio Code)
|    Folder (StratuxHud): 261 files
|      File types: pyc(104) py(69) png(13) json(7) txt(6) jpg(6) md(4) ttf(4)
|                  xcf(2) sh(2)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: python(10);
```

</details>
<details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-json|and|1.5.0
QML|bbe|1.0.0
path-intellisense|chr|2.8.1
systemd-unit-file|coo|1.0.6
c-cpp-compile-run|dan|1.0.15
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
docs-markdown|doc|0.2.113
xml|Dot|2.5.1
gitlens|eam|12.1.1
vscode-html-css|ecm|1.13.0
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
prettier-vscode|esb|9.5.0
vscode-language-todo|fir|1.2.3
vscode-pull-request-github|Git|0.46.0
go|gol|0.34.1
handlebars-preview|Gre|1.4.0
vscode-test-explorer|hbe|2.21.1
polacode-2019|jef|0.5.2
docthis|joe|0.7.1
docomment|k--|0.1.31
vscode-codemetrics|kis|1.24.0
csharpfixformat|Leo|0.0.84
vscode-python-test-adapter|lit|0.7.1
bash-ide-vscode|mad|1.14.0
rainbow-csv|mec|2.4.0
ecdc|mit|1.8.0
nc-gcode|ML|0.13.0
csharp|ms-|1.25.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1001902341
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
cpptools|ms-|1.10.8
powershell|ms-|2022.6.3
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5641
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.19.0
quicktype|qui|12.0.46
bash-beautify|sha|0.1.1
sonarlint-vscode|Son|3.6.0
sourcery|sou|0.12.3
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.12.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.15.2

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by JohnMarzulli** [comment] 2022-07-09 14:24
UPDATE:

This is an Electron issue with audio drivers.

With the help of a performance engineer, we traced the issue to an audio delay.

Electron on startup is attempting to do something with the onboard audio of my machine, which results in a 12 second timeout.

This issue affected multiple Electron based apps on the machine.

I have been able to resolve the issue by disabling the onboard Realtek Audio, and uninstalling all of the associated Realtek device drivers.

![image](https://user-images.githubusercontent.com/23081324/178109894-ab733fbe-8142-41c0-8b48-d95d45b040af.png)
![image](https://user-images.githubusercontent.com/23081324/178109902-3ee72ec5-f957-432f-98d1-152a190de7f4.png)

**Comment by JohnMarzulli** [comment] 2022-07-10 17:01
To reiterate:

The delay occurred during normal application startup, but DID NOT when starting with `--prof-startup`.

This implies `--prof-startup` exercises substantially different startup code than normal startup.

**Comment by deepak1556** [comment] 2022-08-04 07:04
I got access to the above WPA trace and the delay happens when trying to initialize the `IMMDeviceEnumerator` interface on startup by chromium https://source.chromium.org/chromium/chromium/src/+/main:media/audio/win/core_audio_util_win.cc;l=373-376

You might also be able to workaround this delay by starting the application with `--force-wave-audio`. I believe the issue is being forwarded to the chromium team internally but I am not aware on the details, pushing this to backlog since there is nothing actionable from VSCode end for now.

**Comment by deepak1556** [comment] 2022-12-13 13:27
Closing as issue is not actionable.

**Closed by deepak1556** 2022-12-13 13:27 UTC
Labels: upstream, windows, perf-startup, chromium
