### ISSUE TITLE
electron_node tsserver.js - running at 100%

### ISSUE THREAD

**Issue by LeeCampbellr** [microsoft/vscode#72631] opened 2019-04-20 02:38 UTC
Issue Type: <b>Bug</b>

Running a gatsby project with the base styled-components installed - tried the clearing of the typescript version cache.  tsserve processr is running at 100% anytime I edit any file with styled-components. I'm running the insiders edition with no extension active.  

VS Code version: Code - Insiders 1.34.0-insider (f89390fcec44a24ce74dfc4efbc1438f35b7357a, 2019-04-18T13:31:41.962Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (10.94GB free)|
|Process Argv|-psn_0_3789725|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.7.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-04-22 18:04
Do you have `@types/styled` components installed under `node_modules`? If so, what version?

**Comment by LeeCampbellr** [comment] 2019-04-22 18:14
I do not have `@types/styled` in the project.

**Comment by mjbvz** [comment] 2019-04-22 18:20
Sorry, should be `@types/styled-components`. I updated my comment for this.

Can you please try collecting the TS Server log to help us investigate:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a `tsserver.log` file in the editor

If you can share that log, I can take a look to see if anything stands out 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by LeeCampbellr** [comment] 2019-04-23 01:24
I do not have `@types/styled-components` in the project.

I've attached a TS Server log following your steps - let me know if there's anything else I can help to resolve.

[tsserver.log](https://github.com/Microsoft/vscode/files/3105401/tsserver.log)

**Comment by mjbvz** [comment] 2019-04-23 18:57
Thanks. I don't see anything in the logs that indicates a long running request or expensive ongoing operation. Was the high cpu usage happening when you collected the log? How long does the spike last?

One idea: can you try creating a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) at the root of your project. This file explicitly defines a javascript project and may prevent a few `js` files under `node_modules` from being included

**Comment by LeeCampbellr** [comment] 2019-04-24 01:42
It was happening - if I do any typing in the code editor with a Gatsby project open it goes nuts, especially copy and pasting sections of code around - but the second I stop typing the CPU drops back down. 

I created a jsconfig.json at the root of the project this morning and it did not help.

**Comment by fortydegrees** [comment] 2019-05-20 22:01
FWIW, I also encounter this issue with a similar setup

**Comment by mjbvz** [comment] 2019-05-22 23:00
@LeeCampbellr Can you also please test this again using the latest VS Code insiders build (which includes TypeScript 3.5)

I believe you could have been hitting https://github.com/microsoft/TypeScript/issues/30819  which should now be fixed

**Comment by mjbvz** [comment] 2019-05-29 00:02
Closing this as a likely duplicate of microsoft/TypeScript#30819 based on the repo

**Closed by mjbvz** 2019-05-29 00:02 UTC
Labels: freeze-slow-crash, javascript, needs more info

**Comment by LeoLozes** [comment] 2019-05-29 08:54
I'm consistently getting a 25%-40% CPU usage from electron_node tsserver.js, both on the last stable and last exploration build, with no extensions. Also, between 600 and 1.200 MB of RAM usage:

![ProcessExplorer](https://user-images.githubusercontent.com/11133817/58543355-9d775d80-81ff-11e9-81dd-18e3c7f0608f.png)

I don't have `@types/styled-components` installed under `node_modules`, however I do have `@types/styled-jsx@^2.2.8`, I don't know if it can impact as well.
