### ISSUE TITLE
Markdown preview problem

### ISSUE THREAD

**Issue by ailinhomu** [Microsoft/vscode#20848] opened 2017-02-18 05:20 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Preview for markdown cannot fit to zoom when the window.zoomLevel got a value.
```
    {"window.zoomLevel": 1}
```
![20170218131759](https://cloud.githubusercontent.com/assets/12998371/23090618/b984e454-f5dc-11e6-9065-f118a67939f6.png)

*sorry for my poor English*

**Comment by mjbvz** [comment] 2017-02-18 20:30
Duplicate of #5745

**Closed by mjbvz** 2017-02-18 20:30 UTC
Labels: duplicate
