### ISSUE TITLE
PDF view is broken

### ISSUE THREAD

**Issue by damiponce** [microsoft/vscode#104959] opened 2020-08-18 23:15 UTC
Issue Type: <b>Bug</b>

When I open a .pdf file (from LaTeX, although I doubt it makes a difference) instead of showing the PDF web viewer, it displays all of the buttons of the viewer in what seems like pure HTML, therefore not showing the PDF.

![alt text](https://i.imgur.com/L0DmTIo.png "screenshot")

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 x 3504)|
|Memory (System)|11.95GB (2.67GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.8.3
react-native-react-redux|EQu|2.0.4
helium-icon-theme|hel|1.0.0
theme-monokai-pro-vscode|mon|1.1.17
remote-wsl|ms-|0.44.4
JavaScriptSnippets|xab|1.8.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
latex-workshop|Jam|8.11.1
cpptools|ms-|0.29.0
vscode-react-native|msj|0.17.0
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|0.3.2
lorem-ipsum|Tyr|1.2.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by tamuratak** [comment] 2020-08-18 23:19
Duplicate of James-Yu/LaTeX-Workshop/issues/2206

**Closed** 2020-08-19 00:07 UTC
Labels: *duplicate
