### ISSUE TITLE
GitHub push results in an auth error

### ISSUE THREAD

**Issue by SirTurboPascal** [microsoft/vscode#137381] opened 2021-11-17 18:11 UTC
Issue Type: <b>Bug</b>

With every Git Push command I get the error that anonymous authentication is not possible: "No Anonymous Write Access!". This problem occurred from the beginning on my new M1 Mac, but not on my other computers.

I followed the instructions according to Git and GitHub exactly for the setup steps for the initial installations and made sure that the entries that appear for a "git command --list" match all other devices. Of course, a new SSH key pair was created for the new M1 Mac.

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (4.17GB free)|
|Process Argv|--crash-reporter-id 2c24c0ba-4be1-43c9-8104-5b6111bdb73a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
vscode-styled-components|jpo|1.6.6
vscode-language-pack-de|MS-|1.62.4
LiveServer|rit|5.6.1
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.14
vscode-import-cost|wix|2.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-17 19:32
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

Fix also became available today in Insiders.

**Closed** 2021-11-17 19:32 UTC
Labels: *duplicate
