### ISSUE TITLE
Is it possible to edit files on remote server?

### ISSUE THREAD

**Issue by alandawkins** [Microsoft/vscode#32434] opened 2017-08-14 01:12 UTC
It's really nice if vscode can edit files on remote servers or vm, like develop a website in python on vm, get snippets from vm, etc. Is this possible in practise? (For best, this vscode on Win with linux server combination can provide same experience as vscode on local linux desktop.)

**Comment by jrieken** [comment] 2017-08-14 08:52
duplicate of #29194

**Closed** 2017-08-14 08:53 UTC
Labels: duplicate, workbench
