### ISSUE TITLE
Auto update import on file moved issue

### ISSUE THREAD

**Issue by nmhung1210** [Microsoft/vscode#53832] opened 2018-07-09 05:16 UTC
Issue Type: <b>Bug</b>

After I moved a file in the workplace, the VS code auto update import run with the wrong path result. It's import the module from the global cache path instead of the workplace folder.
Like below:

<img width="1659" alt="screen shot 2018-07-09 at 12 14 57" src="https://user-images.githubusercontent.com/6645185/42431800-b7c865f4-8371-11e8-9c1a-021c0485362e.png">

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
python|ms-|2018.6.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
shader|sle|1.1.3
vscode-react-native|vsm|0.6.11

</details>

**Comment by mjbvz** [comment] 2018-07-09 16:22
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by nmhung1210** [comment] 2018-07-09 17:28
It seems not happen after I re-installed the VS Code and disabled all the extensions. However, It might be because of that feature did not work as intended:

Reproduce steps as below:
![auto_update_import](https://user-images.githubusercontent.com/6645185/42465900-8d897fd8-83d7-11e8-8185-800833050af4.gif)

**Comment by kevbost** [comment] 2018-07-13 16:12
This is a serious issue.  I was prompted to update imports for a renamed file in a react project, i thought I'd give it a try.

Spent an hour carefully undoing the changes in my uncommitted files, all while vscode and docker freaked out trying to map the hundreds of changes to pathing made to almost every js file in the solution.

**Comment by furier** [comment] 2018-07-13 19:20
having the same issue, moved a file and got 350 files changed where all paths went from being absolute to relative even tho my user settings are set to `"typescript.preferences.importModuleSpecifier": "non-relative",`

**Comment by danielriley06** [comment] 2018-07-14 07:55
Count me in as well. I changed a file extension (.js => .jsx, or something like that) and every file in our production app opened and had the import paths changed.

I've since switched to "javascript.updateImportsOnFileMove.enabled": "prompt", and have yet to receive any prompts. If someone had autosave turned on, good times would definitely be had.

**Comment by victorschinaider** [comment] 2018-07-15 22:57
I'm having same problem here. I spent 30 minutes undoing changes of almost all files of project.

**Comment by Kamahl19** [comment] 2018-07-16 16:23
I am having the issue on the latest version as well.

**Comment by jordwest** [comment] 2018-07-17 03:59
Same issue here on v1.25.1.

After renaming a module directory, the auto-rename caused VSCode to freeze up for a few minutes, then showed unsaved changes to >1000 files. Absolute imports in unrelated files were all converted to relative imports.

Note for anyone else running into this: As long as you've saved changes before the rename, you can click "Close All Editors" and choose "Don't Save" to undo all the auto-renames.

**Comment by alebrozzo** [comment] 2018-07-18 12:56
I have the same problem when moving a file, all imports from _any file in the project_ that are pointing to an external library like react are being updated to point to node_modules.
Also, if I do a close all, it asks me to save or drop changes in a file by file basis instead of all or nothing, which I understand is supposed to be an already implemented feature.

Since I use git, the way I handle this is to save all files and then discard changes using the git discard changes. I can't do it all at once because it gives me an error, so I do it in batches of about 100 files a time.

**Comment by DBosley** [comment] 2018-07-18 17:07
This is a major issue that needs addressed quickly. I haven't seen it on the insiders build, but I'd prefer to stay on the stable build when possible.

**Comment by nmhung1210** [comment] 2018-07-18 17:52
@mjbvz Could you please give some update here? 
A lot of peoples are suffering because of this. Let's save the developer life, please :)

**Comment by mjbvz** [comment] 2018-07-18 21:38
This is fixed on insiders builds or if you [upgrade your workspace to use TypeScript 3.0](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

If you still see this issue when using TS 3.0, please open a new issue

**Closed by mjbvz** 2018-07-18 21:38 UTC
Labels: needs more info

**Comment by NawarYossef** [comment] 2018-08-02 14:37
This is still happening. I rename or move one file, and all import paths will change in all files.

**Comment by anthonychung14** [comment] 2018-08-02 17:29
FYI because it's taking more than 2 weeks to solve this (or you have to use a specific build/version just to get VSCode to not be broken), I'm moving to WebStorm. 🤷‍♂️ c ya

**Comment by doriclaudino** [comment] 2018-08-02 17:52
The same happens to me.

![image](https://user-images.githubusercontent.com/3863501/43601327-e4fb5f08-965a-11e8-88a7-6147a61723ee.png)


Disable all extensions:
![image](https://user-images.githubusercontent.com/3863501/43601473-406bedbc-965b-11e8-8d4a-af56d47926b9.png)


Before rename a file:
`import React from "react";`

After rename a file:
`import React from '../../../Users/[...]node_modules/@types/react';`
