### ISSUE TITLE
Keep getting extension error stopped and needs window reload but unable to know which extension is failing

### ISSUE THREAD

**Issue by istian** [Microsoft/vscode#24716] opened 2017-04-13 20:38 UTC
- VSCode Version: 1.11.2
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Happens intermittently while vs code is open. It will just show after few minutes or hours.

![image](https://cloud.githubusercontent.com/assets/200690/25023332/1166a508-20cc-11e7-9aa4-537c9d82bec7.png)

can you make the error show which extension is failing so to have an idea which one should I disable or uninstall?

**Comment by jrieken** [comment] 2017-04-14 07:13
most likely dupe of https://github.com/Microsoft/vscode/issues/24742

**Closed by jrieken** 2017-04-14 07:13 UTC
