### ISSUE TITLE
Emmet Expansion looses against completion proposals

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19234] opened 2017-01-24 17:18 UTC
Test item #19079

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|autofilename|JerryHong|0.1.3|

---

Steps to Reproduce:

1. Install AutoFileName extension
2. Open empty html file
3. Type: html`<tab>`
4. Unexpected: the completion proposals from AutoFileName win against the Emmet Expansion command

Not sure if this is specific to how this extension sets up it completion items, but maybe we can improve that on our side.

**Comment by chrmarti** [comment] 2017-01-24 17:52
Also with other proposals:
1. Start with an empty html
2. Type: hr`<tab>`
3. Ok
4. Again type: hr`<tab>`
5. Expected: Expansion to `<hr>`
6. Actual: `<tab>` only accepts completion proposal, I have to hit `<tab>` a second time to get the expansion to `<hr>`

**Comment by chrmarti** [comment] 2017-01-24 18:12
Not an Emmet power user, but this seems to make it hard to use.

**Comment by ramya-rao-a** [comment] 2017-02-01 01:58
Duplicate of #1952

**Closed by ramya-rao-a** 2017-02-01 01:58 UTC
Labels: emmet
