### ISSUE TITLE
Extension host terminated unexpectedly - VSCode 1.44

### ISSUE THREAD

**Issue by Jagruttam** [microsoft/vscode#94922] opened 2020-04-10 15:38 UTC
Issue Type: <b>Bug</b>

Just install this version and open.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by KKacer** [comment] 2020-04-10 15:55
Have the same issue, in the previous minor version also I think was the same issue.
can't really work with SCSS files, which I think there could be native support for that.
Even Live Sass compiler is too old! and there is not good alternative there.
VSCode seems buggy on this side.

**Comment by SqrTT** [comment] 2020-04-10 16:26
#94916 duplicate?

**Comment by gjsjohnmurray** [comment] 2020-04-10 16:28
Maybe caused by false positive detection by your antivirus software. 

See #94807 and linked issues.

**Comment by RMacfarlane** [comment] 2020-04-10 19:14
We are seeing many reports of Quick Heal incorrectly flag and remove a file. If you're using Quick Heal, please see this discussion on how to correct it: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

I have tried contacting their support but have not yet received a response

**Comment by RMacfarlane** [comment] 2020-04-10 19:21
I'm closing this as a duplicate of https://github.com/microsoft/vscode/issues/94807, please let us know if the discussion in https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765 does not solve the problem

**Closed by RMacfarlane** 2020-04-10 19:21 UTC
Labels: needs more info, new release

**Comment by Jagruttam** [comment] 2020-04-11 12:10
> We are seeing many reports of Quick Heal incorrectly flag and remove a file. If you're using Quick Heal, please see this discussion on how to correct it: [#94858 (comment)](https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765)
> 
> I have tried contacting their support but have not yet received a response

#94858 helped me. It was because of Quick Heal, not VS Code bug.
