### ISSUE TITLE
Javascript typing tips

### ISSUE THREAD

**Issue by agsea** [Microsoft/vscode#40379] opened 2017-12-17 13:54 UTC
Now, i want to konw how can i get js snippets from a js file (generally, it's a js library, such as the three.js) while i'm working in other js file. As far as i can see, existing plugings for js in vscode not has the function.

**Comment by RobertAKARobin** [comment] 2017-12-17 21:30
Possibly duplicated by https://github.com/Microsoft/vscode/issues/40392

**Comment by mjbvz** [comment] 2017-12-18 18:56
Please provide a code example and describe the expected behavior

**Comment by GoToSea** [comment] 2017-12-21 01:25
[code_example.zip](https://github.com/Microsoft/vscode/files/1577560/code_example.zip)

**Comment by GoToSea** [comment] 2017-12-21 01:33
Here is sample code and two shortcut of the expected behavior in the 'code_example.zip' file.

[code_example.zip](https://github.com/Microsoft/vscode/files/1577582/code_example.zip)

**Comment by mjbvz** [comment] 2018-03-06 04:37
Duplicate of #26338

**Closed by mjbvz** 2018-03-06 04:37 UTC
Labels: javascript, needs more info
