### ISSUE TITLE
console key word is with different color

### ISSUE THREAD

**Issue by Alexander-Ivanov91** [microsoft/vscode#92351] opened 2020-03-10 12:31 UTC
Issue Type: <b>Bug</b>

Write console.log and observe the color of the console keyword. Used to be green an this way is much more recognisable. When VS code initializes console keyword is green, but when VS code is initialized it becomes blue.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.900.15
turbo-console-log|Cha|1.4.0
closing-tags|lko|0.0.3

</details>

**Comment by gjsjohnmurray** [comment] 2020-03-10 12:46
/duplicate of #90379

As a workaround you could disable semantic highlighting.

**Closed by gjsjohnmurray** 2020-03-10 12:46 UTC
Labels: *duplicate, new release

**Comment by Alexander-Ivanov91** [comment] 2020-03-10 13:09
Thank you, gjsjohnmurray!
