### ISSUE TITLE
Can't kill a Terminal without focusing it at least once

### ISSUE THREAD

**Issue by biro456** [microsoft/vscode#128264] opened 2021-07-08 23:57 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Start VS Code with WSL Remote on WSL 2
2. Open a new Terminal (it doesn't autofocus anymore)
3. Without giving focus to the Terminal, click the trash icon to kill it

The terminal should close, but doesn't

The autofocus problem seems to be already reported as well: #128255

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.32GB free)|
|Process Argv|--crash-reporter-id 4db21ffc-61bb-4e0f-84f1-1d0c8fc0bf39|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (4 x 3792)|
|Memory (System)|7.77GB (3.33GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
Handlebars|and|0.4.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
remote-wsl|ms-|0.58.2
proto|pet|0.0.2
toml|be5|0.5.1
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
vscode-graphql|Gra|0.3.16
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
vscode-kubernetes-tools|ms-|1.3.3
vscode-xml|red|0.17.0
vscode-yaml|red|0.21.0
rust|rus|0.7.8
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment] 2021-07-09 03:15
This will be fixed in the recovery build - the root cause is #128255

**Comment by Marines1775** [comment] 2021-07-13 15:24
How long does a recovery build take?  When would user's be notified?

Thank you

**Comment by meganrogge** [comment] 2021-07-13 15:58
It will be released within a week. You can use Insider's now - where it's been fixed.

**Closed** 2021-07-14 11:41 UTC
Labels: bug, candidate, terminal
