### ISSUE TITLE
Emmet commands that do no change to selection or content incorrectly add tab/indent block

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8438] opened 2016-06-28 20:58 UTC
#8207

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

For the text:

```html
<div id="page">
	<div class="logo"></div>
	<ul id="navigation">
		<li><a href="">Item 1</a></li>
		<li><a href="">Item 2</a></li>
		<li><a href="">Item 3</a></li>
		<li><a href="">Item 4</a></li>
		<li><a href="">Item 5</a></li>
	</ul>
</div>
```

Balance outward works fine until the whole second is selected, if triggered again the selection gets indented. Resulting in:

```html
	<div id="page">
		<div class="logo"></div>
		<ul id="navigation">
			<li><a href="">Item 1</a></li>
			<li><a href="">Item 2</a></li>
			<li><a href="">Item 3</a></li>
			<li><a href="">Item 4</a></li>
			<li><a href="">Item 5</a></li>
		</ul>
	</div>
```

This also happens when balance outward is run on an empty file.

**Comment by Tyriar** [comment] 2016-06-28 20:59
Does not repro in upstream http://docs.emmet.io/actions/match-pair/

**Comment by Tyriar** [comment] 2016-06-28 21:38
Updated title to be more generic, this seems to be a problem with most commands if not all.

**Comment by mrmlnc** [comment] 2016-06-29 14:07
Fixed by #8489.

**Comment by egamma** [comment] 2016-06-29 14:51
This is issue has the same root cause as #8450, which has been fixed.

**Closed by egamma** 2016-06-29 14:51 UTC
Labels: bug

**Comment by Tyriar** [comment] 2016-06-29 18:52
Thanks a lot for the quick fix @mrmlnc, this was the biggest issue I found in my testing :+1:
