### ISSUE TITLE
Backspace disabled

### ISSUE THREAD

**Issue by benjaminglass1** [Microsoft/vscode#49714] opened 2018-05-11 17:58 UTC
Issue Type: <b>Bug</b>

Enable Colemak keyboard. Attempt to utilize remapped "Caps Lock" backspace (Colemak default). This backspace does not work in the code editing window, although the normal backspace key does.
The remapped backspace key does seem to work in the built-in terminal window, just not in the code editing section.

Bug in VS Code Snap, running on Ubuntu 18.04.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (0.30GB free)|
|Process Argv|/snap/vscode/34/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
language-julia|jul|0.10.2

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2018-05-14 11:59
Duplicate of #32369

**Closed by alexandrudima** 2018-05-14 11:59 UTC
Labels: editor
