### ISSUE TITLE
VSCode can't save TypeScript files when tslint-plugin hangs

### ISSUE THREAD

**Issue by JamesMessinger** [microsoft/vscode#65862] opened 2018-12-31 14:32 UTC
Issue Type: <b>Bug</b>

Ever since switching from the old [vscode-tslint plugin](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) to the new [vscode-typescript-tslint plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin), I frequently encounter a situation where VSCode is unable to save any TypeScript file.  I can save other file types, just not TypeScript files.  The only solution I've found is to restart VSCode - which means losing any unsaved changes in TypeScript files. ☹  After restarting, everything works fine again... for a few minutes.  But usually within 15 minutes or less the problem happens again and I'm forced to restart VSCode again.

I believe the problem is that the file save operation in VSCode somehow interacts with the typescript-tslint-plugin, but the plugin has crashed or hung, so VSCode just waits forever for the plugin to respond.  IMHO a hung plugin shouldn't prevent VSCode from being able to save a file. 

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-typescript-tslint-plugin|ms-|0.2.1
vscode-icons|rob|8.0.0

</details>

**Comment by mjbvz** [comment] 2019-01-02 19:11
Do you have format on save or code actions on save enabled?

Can you also please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

What is the last message in the output? Are there any errors or call stacks?

**Comment by JamesMessinger** [comment] 2019-01-09 18:53
@mjbvz - Thanks for providing instructions to get trace output.  The problem just happened again, and here's a snippet of what I see in the output panel.  There's a *lot* more than this, but it's basically this same pattern over and over.

```
[Trace  - 12:45:20 PM] Sending request: change (1252). Response expected: no. Current queue length: 11
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 25,
    "offset": 110,
    "endLine": 25,
    "endOffset": 110
}
[Trace  - 12:45:20 PM] Sending request: change (1253). Response expected: no. Current queue length: 10
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 24,
    "offset": 96,
    "endLine": 24,
    "endOffset": 96
}
[Trace  - 12:45:20 PM] Sending request: change (1254). Response expected: no. Current queue length: 9
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 23,
    "offset": 72,
    "endLine": 23,
    "endOffset": 72
}
[Trace  - 12:45:20 PM] Sending request: change (1255). Response expected: no. Current queue length: 8
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 22,
    "offset": 62,
    "endLine": 22,
    "endOffset": 62
}
[Trace  - 12:45:20 PM] Sending request: change (1256). Response expected: no. Current queue length: 7
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 21,
    "offset": 54,
    "endLine": 21,
    "endOffset": 54
}
[Trace  - 12:45:20 PM] Sending request: change (1257). Response expected: no. Current queue length: 6
Arguments: {
    "insertString": "/",
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 20,
    "offset": 54,
    "endLine": 20,
    "endOffset": 54
}
[Trace  - 12:45:20 PM] Sending request: completionInfo (1258). Response expected: yes. Current queue length: 5
Arguments: {
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 20,
    "offset": 55,
    "includeExternalModuleExports": true,
    "includeInsertTextCompletions": true,
    "triggerCharacter": "/"
}
[Trace  - 12:45:20 PM] TypeScript Server: trying to cancel ongoing request with sequence number 1258
[Trace  - 12:45:20 PM] TypeScript Server: canceled request with sequence number 1262
[Trace  - 12:45:20 PM] Sending request: jsxClosingTag (1259). Response expected: yes. Current queue length: 4
Arguments: {
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx",
    "line": 20,
    "offset": 55
}
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1265
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1266
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1267
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1268
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1264
[Trace  - 12:45:21 PM] TypeScript Server: canceled request with sequence number 1269
[Trace  - 12:45:22 PM] TypeScript Server: canceled request with sequence number 1270
[Trace  - 12:45:22 PM] TypeScript Server: canceled request with sequence number 1271
[Trace  - 12:45:26 PM] TypeScript Server: canceled request with sequence number 1261
[Trace  - 12:45:26 PM] TypeScript Server: canceled request with sequence number 1272
[Trace  - 12:45:26 PM] TypeScript Server: canceled request with sequence number 1273
[Trace  - 12:45:26 PM] TypeScript Server: canceled request with sequence number 1274
[Trace  - 12:45:26 PM] TypeScript Server: canceled request with sequence number 1275
[Trace  - 12:45:27 PM] TypeScript Server: canceled request with sequence number 1276
[Trace  - 12:45:27 PM] TypeScript Server: canceled request with sequence number 1277
[Trace  - 12:45:27 PM] TypeScript Server: canceled request with sequence number 1278
[Trace  - 12:45:29 PM] TypeScript Server: canceled request with sequence number 1279
[Trace  - 12:45:32 PM] TypeScript Server: canceled request with sequence number 1280
[Trace  - 12:45:32 PM] TypeScript Server: canceled request with sequence number 1281
[Trace  - 12:45:32 PM] TypeScript Server: canceled request with sequence number 1285
[Trace  - 12:45:34 PM] TypeScript Server: canceled request with sequence number 1282
[Trace  - 12:45:34 PM] TypeScript Server: canceled request with sequence number 1283
[Trace  - 12:45:34 PM] TypeScript Server: canceled request with sequence number 1284
[Trace  - 12:45:37 PM] TypeScript Server: canceled request with sequence number 1289
[Trace  - 12:45:37 PM] TypeScript Server: canceled request with sequence number 1290
[Trace  - 12:45:38 PM] TypeScript Server: canceled request with sequence number 1287
[Trace  - 12:45:38 PM] TypeScript Server: canceled request with sequence number 1288
[Trace  - 12:45:39 PM] TypeScript Server: canceled request with sequence number 1293
[Trace  - 12:45:41 PM] TypeScript Server: canceled request with sequence number 1294
[Trace  - 12:45:41 PM] TypeScript Server: canceled request with sequence number 1295
[Trace  - 12:45:41 PM] TypeScript Server: canceled request with sequence number 1297
[Trace  - 12:45:41 PM] TypeScript Server: trying to cancel ongoing request with sequence number 1259
[Trace  - 12:45:41 PM] TypeScript Server: canceled request with sequence number 1260
[Trace  - 12:45:41 PM] Sending request: navtree (1263). Response expected: yes. Current queue length: 7
Arguments: {
    "file": "c:/path/to/my/project/src/components/layouts/seo.tsx"
}
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1296
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1298
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1301
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1302
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1303
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1304
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1305
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1306
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1307
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1308
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1309
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1310
[Trace  - 12:45:42 PM] TypeScript Server: canceled request with sequence number 1286
[Trace  - 12:45:42 PM] TypeScript Server: trying to cancel ongoing request with sequence number 1263
[Trace  - 12:45:42 PM] Sending request: organizeImports (1291). Response expected: yes. Current queue length: 5
Arguments: {
    "scope": {
        "type": "file",
        "args": {
            "file": "c:/path/to/my/project/src/components/layouts/seo.tsx"
        }
    }
}
[Trace  - 12:45:55 PM] TypeScript Server: canceled request with sequence number 1300
[Trace  - 12:45:55 PM] TypeScript Server: canceled request with sequence number 1311
[Trace  - 12:45:55 PM] TypeScript Server: canceled request with sequence number 1312
[Trace  - 12:46:02 PM] TypeScript Server: canceled request with sequence number 1316
[Trace  - 12:46:03 PM] TypeScript Server: canceled request with sequence number 1319
[Trace  - 12:46:03 PM] TypeScript Server: canceled request with sequence number 1315
[Trace  - 12:46:04 PM] TypeScript Server: canceled request with sequence number 1292
[Trace  - 12:46:05 PM] TypeScript Server: canceled request with sequence number 1321
[Trace  - 12:46:16 PM] TypeScript Server: canceled request with sequence number 1320
[Trace  - 12:46:17 PM] TypeScript Server: canceled request with sequence number 1324
[Trace  - 12:47:32 PM] TypeScript Server: canceled request with sequence number 1323
[Trace  - 12:47:39 PM] TypeScript Server: canceled request with sequence number 1327
[Trace  - 12:47:39 PM] TypeScript Server: canceled request with sequence number 1325
[Trace  - 12:47:39 PM] TypeScript Server: canceled request with sequence number 1329
[Trace  - 12:47:39 PM] TypeScript Server: canceled request with sequence number 1326
[Trace  - 12:47:43 PM] TypeScript Server: canceled request with sequence number 1328
[Trace  - 12:47:43 PM] TypeScript Server: canceled request with sequence number 1330
[Trace  - 12:47:44 PM] TypeScript Server: canceled request with sequence number 1332
[Trace  - 12:48:17 PM] TypeScript Server: canceled request with sequence number 1331
[Trace  - 12:48:17 PM] TypeScript Server: canceled request with sequence number 1335
[Trace  - 12:48:17 PM] TypeScript Server: canceled request with sequence number 1336
[Trace  - 12:48:17 PM] TypeScript Server: canceled request with sequence number 1337
[Trace  - 12:48:18 PM] TypeScript Server: canceled request with sequence number 1314
[Trace  - 12:48:18 PM] TypeScript Server: canceled request with sequence number 1334
[Trace  - 12:48:18 PM] TypeScript Server: canceled request with sequence number 1339
[Trace  - 12:48:20 PM] TypeScript Server: canceled request with sequence number 1341
[Trace  - 12:48:20 PM] TypeScript Server: canceled request with sequence number 1340
[Trace  - 12:48:21 PM] TypeScript Server: canceled request with sequence number 1338
[Trace  - 12:48:31 PM] TypeScript Server: canceled request with sequence number 1343
[Trace  - 12:48:32 PM] TypeScript Server: canceled request with sequence number 1344
[Trace  - 12:48:32 PM] TypeScript Server: canceled request with sequence number 1345
```

**Comment by mjbvz** [comment] 2019-01-11 22:46
@JamesMessinger Looks like something is hanging with the typescript server. Can you check Please try collecting the Typescript server Server log since the trace does not include all the information we need:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by JamesMessinger** [comment] 2019-01-12 20:08
@mjbvz - Thanks for the instructions.  Here's my `tsserver.log` file.  Based on the last line in the log, I'm guessing that it hung while waiting for TSLint to respond.

[tsserver.log](https://github.com/Microsoft/vscode/files/2752451/tsserver.log)

**Comment by mjbvz** [comment] 2019-08-15 01:09
Closing this issue as out of date.

Sorry but I have not ever been able to reproduce this issue and the logs did not provide any hints as to what is going wrong. Let me know if you still see this with the latest versions of VS Code and the extension

**Closed by mjbvz** 2019-08-15 01:09 UTC
Labels: needs more info
