### ISSUE TITLE
Intellisense Behavior Change near 1.79.2

### ISSUE THREAD

**Issue by CharlieHess** [microsoft/vscode#185588] opened 2023-06-19 15:45 UTC
Type: <b>Bug</b>

See this video for the repro: https://imgur.com/a/5r3ht98

There's a subtle but extremely annoying Intellisense regression in the latest version. Previously, when I pressed the period key midexpression, it would open Intellisense suggestions but retain the rest of the expression after the period. Now, when I press period, everything after the period is erased.

This breaks one of the fundamental rules of text editing: preserve the user's text! Why on god's green earth are you fucking with Intellisense behavior on an 8 year old text editor?

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.6.0

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id da296e29-1fc8-4490-861c-34888e4cdeaf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
require-sort|Per|0.0.1
vscode-css-formatter|aes|1.0.2
shaderlabvscodefree|aml|1.3.3
ink|bru|1.3.1
gltf-vscode|ces|2.4.0
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
vscode-eslint|dba|2.4.0
gitlens|eam|14.0.0
prettier-vscode|esb|9.13.0
github-actions|for|0.0.1
csharp-format-usings|gao|0.0.4
vscode-glsl|GeF|0.2.10
copilot|Git|1.89.156
unity-code-snippets|kle|1.3.0
shaderlabformatter|lit|0.4.3
import-sorter|mik|3.3.1
vscode-docker|ms-|1.25.1
csharp|ms-|1.25.9
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
prisma|Pri|4.15.0
vscode-commons|red|0.0.6
vscode-xml|red|0.25.0
shader|sle|1.1.5
wallaby-vscode|Wal|1.0.357
clang-format|xav|1.9.0
material-theme|zhu|3.15.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showindicator:30766890
pythongtdpath:30769146
dh2dc718:30770000

```

</details>

**Comment by jrieken** [comment] 2023-06-19 16:18
/duplicate of https://github.com/microsoft/vscode/issues/185286

**Closed** 2023-06-19 16:19 UTC
Labels: *duplicate
