### ISSUE TITLE
vscode.env.openExternal double encodes the data if you pass a param in the query that also requires encoding

### ISSUE THREAD

**Issue by danechitoaie** [microsoft/vscode#135949] opened 2021-10-27 12:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.61.2
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:
I have the following code in a VSC extension:
```typescript
const callbackUri = await vscode.env.asExternalUri(vscode.Uri.parse(`${vscode.env.uriScheme}://${context.extension.id}/callback`));
const redirectUri = vscode.Uri.parse("http://localhost:3000/?callbackUri=" + encodeURIComponent(callbackUri.toString()) + "&test=ok");
await vscode.env.openExternal(redirectUri);
```

When `vscode.env.openExternal` is executed this messes up with the proper encoding of the URL query params and the browser is opened to a URL like: `http://localhost:3000/?callbackUri=vscode://hello.vsc-develop/callback%253FwindowId%253D13&test=ok`

Notice how the `?` and `=` are encoded twice (`%253F`, `%253D13`)

I would expect callbackUri to be encoded as `vscode%3A%2F%2Fhello.vsc-develop%2Fcallback%3FwindowId%3D13` as that how encodeURIComponent encodes it.

So two questions here:
1. Why aren't the `://` and `/` parts also encoded by `vscode.Uri.parse` + `vscode.env.openExternal`?
2. And why is the `?` and `=` characters encoded twice?

**Comment by zardoy** [comment] 2021-12-09 00:17
There are also real-world cases in which `vscode.env.openExternal` would open incorrect URL.
For example I have an ext that contributes code action to test regex against strings at regex101

```ts
// Example: /.+:.+;/
// const urlToOpen = `https://regex101.com/?regex=${encodeURIComponent('.+:.+;')}?&flags=gi`
// resolved: https://regex101.com/?regex=.%2B%3A.%2B%3B%3F&flags=gi
```

At very first time I though this is problem with `vscode.Uri.from` and `parse` as they decode parts for some reason (like seriously, I didn't understand why then even this repo uses `encodeURIComponent`).

I was using workaround with a package called [open](https://www.npmjs.com/package/open) for a while, but then realized from src that `vscode.env.openExternal` actually receives string, so you can just do that:
```ts
const callbackUri = await vscode.env.asExternalUri(vscode.Uri.parse(`${vscode.env.uriScheme}://${extensionCtx.extension.id}/callback`))
const redirectUrl = `http://localhost:3000/?callbackUri=${encodeURIComponent(callbackUri.toString())}&test=ok`
vscode.env.openExternal(redirectUrl as any)// doesn't change string
```
As I understand `vscode.env.openExternal` is just failing to use `toString(true)` on URI at some point.

The difference:

![image](https://user-images.githubusercontent.com/46503702/145293179-b6ea27a1-2b65-44a5-ab74-599a7125aacf.png)

[THIS](https://github.com/microsoft/vscode/blob/5128d2c32c217dcc33da2527a6936acd083f0603/src/vs/base/test/common/uri.test.ts#L395) should be definitely tested with `openExternal` as it fails on stable.

> Why aren't the :// and / parts also encoded by vscode.Uri.parse + vscode.env.openExternal ?

Do you mean scheme? Its [never being encoded](https://github.com/microsoft/vscode/blob/5128d2c32c217dcc33da2527a6936acd083f0603/src/vs/base/common/uri.ts#L273)

/cc @jrieken why there is no continuation of https://github.com/microsoft/vscode/issues/83645? URL support would not only be extremely convenient in some cases, but I also believe would resolve the case described above. And why there isn't a word in API that `from` does decode components?

**Comment by jrieken** [comment] 2021-12-09 08:43
/duplicate of https://github.com/microsoft/vscode/issues/85930

**Closed** 2021-12-09 08:44 UTC
Labels: bug, help wanted, *duplicate, uri
