### ISSUE TITLE
Weird blur on Win 10 Latest build.

### ISSUE THREAD

**Issue by nlxdodge** [Microsoft/vscode#16407] opened 2016-12-02 21:06 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|Theme-GoldenDragon|gerane|0.0.2|
|Theme-WarpOS|gerane|0.0.2|
|format-php|Kasik96|1.1.2|
|ftp-sync|lukasz-wronski|0.3.1|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Open visual studio code, That's all what I do.

I tried to delete some extentions but that didn't help. I will try to re-install after posting this. I can't work like this.
![blur](https://cloud.githubusercontent.com/assets/8994983/20850335/df11a246-b8da-11e6-9fc5-919eb86cf81c.png)

I have a 1920x1080 screen, chrome is not blurry but VS code is.
It kinda looks like some transition as it gets worse over time when I don't move my mouse over a region.

Settings:
![schermopname 3](https://cloud.githubusercontent.com/assets/8994983/20850455/97b6a8e6-b8db-11e6-84da-a8bd81c0ec46.png)

**Comment by chrmarti** [comment] 2016-12-02 22:00
Could you confirm it also occurs when starting with `code --disable-extensions`?

**Comment by nlxdodge** [comment] 2016-12-02 22:33
Issue still persists even after using: "--disable-extensions" and also removing al extensions.
I will do a re-install tommorow to see if that fixes it.

![schermopname 4](https://cloud.githubusercontent.com/assets/8994983/20852733/b55988e4-b8e7-11e6-8aaf-81c37e9a3c4e.png)

**Comment by bpasero** [comment] 2016-12-03 05:59
@nlxdodge 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by nlxdodge** [comment] 2016-12-03 19:04
@bpasero

Re-installed the latest insider build as you asked. Again tested with --disable-extensions
![schermopname 8](https://cloud.githubusercontent.com/assets/8994983/20861550/3b5024ca-b993-11e6-8694-5bf55e35bfe3.png)
![schermopname 9](https://cloud.githubusercontent.com/assets/8994983/20861551/3edef792-b993-11e6-913f-d05c05de70e0.png)

When I mouse over a certain area, well that area becomes clear again. But all the other area's get more blurry. Could this relate to webkit? It also starts clear and does an animation that translates to blurry text.

**Comment by bpasero** [comment] 2016-12-04 07:20
@nlxdodge does it reproduce if you start from the command line `code --disable-gpu`?

**Comment by nlxdodge** [comment] 2016-12-04 11:58
@bpasero I can't thank you enough. this worked. 
Here are the specs of my laptop:

- Lenovo Y510P
- Intel Core i7-4700MQ default clock,
- 12 GB of ram,
- GT 755M I guess that nvidia has something to do with this. I also haven't tinkerd with any settings from nvidia. But it could be a driver issue.
- Samsung 850 500GB.

**Comment by bpasero** [comment] 2016-12-04 13:45
Ok good to know. We have heard numerous issues with graphics that people could solve by running with this flag. Some also ask for a setting to enable this.

**Comment by klauern** [comment] 2017-01-18 16:52
I get this same issue with the latest 1.9 Insiders build, but found that `--disable-gpu` fixed it.

![image](https://cloud.githubusercontent.com/assets/4735/22073872/24304c14-dd6c-11e6-8f93-f5527913000d.png)

**Comment by bpasero** [comment] 2017-04-10 17:14
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment] 2017-11-14 17:26
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.

**Closed by bpasero** 2017-11-14 17:26 UTC
Labels: electron, font-rendering, upstream
