### ISSUE TITLE
webview not working whilst using WSL 2 on VPN

### ISSUE THREAD

**Issue by ash0803** [microsoft/vscode#103884] opened 2020-08-03 23:21 UTC
Issue Type: <b>Bug</b>

- Install a webview extension such as git graph
- Connect to VPN
- Open Command Prompt and run `wsl --shutdown`
- Open vscode with location in WSL
- Open Git Graph

## Expected
- Git Graph to load as usual

## Actual
- It is not rendered at all

## Notes
- Everything worked fine in vscode v1.46
- Everything works fine without connecting to the VPN

VS Code version: Code - Insiders 1.48.0-insider (5696babbc1dce41788bae04b1a04ad35140bebfb, 2020-08-03T05:51:31.732Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.45GB free)|
|Process Argv|--folder-uri=vscode-remote://xyz/xyz --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|24.85GB (23.12GB free)|
|VM|0%|
</details>

**Comment by ash0803** [comment] 2020-08-27 16:15
To add more information

When connecting to the WSL remote server v1.46 uses this address `http://[::1]:35407/version`

v1.47+ uses something similar to this `http://172.28.159.89:45723/version` which is not routed correctly by my VPN client.

Is there any way to change this functionality back in the newer versions at all?

Thanks

**Comment by ash0803** [comment] 2020-08-27 16:38
Just to mention that the above comment isn't relevant to the problem in question. After restarting vscode AND the VPN I am able to successfully connect to the WSL remote server as it falls back to using the [::1] address.

However, the webviews for git graph or the atlassian extension for example still do not load.

**Comment by thor** [comment] 2020-12-09 08:59
Chiming in here to confirm this issue. The VPN (win32 Cisco AnyConnect) does block access to the `172.28.128.0/20` net for me, but VScode instead connects to `[::1]` after (seemingly?) checking with the WSL resolver.

Could there be something in the resource handling that fails for IPv6, yet works for IPv4?

**Comment by mjbvz** [comment] 2021-02-27 00:39
I believe this is a duplicate of #105536, which should be fixed in current insiders builds

If you are still seeing this issue with VS Code 1.54+, please let me know

**Closed by mjbvz** 2021-02-27 00:39 UTC
Labels: bug, help wanted, remote, webview
