### ISSUE TITLE
Profile creation: selecting second extension will always select all

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#185253] opened 2023-06-15 16:56 UTC
* Create a new profile from existing one
* Unselect all extensions
* Manually select first extension
* Manually select second extension -> now all extensions are selected

**Comment by burkeholland** [comment] 2023-06-16 19:44
Hit this today. Reproduction...

https://github.com/microsoft/vscode/assets/686963/bf04eb8e-c128-4184-a109-3220f3b16e33

**Comment by rzhao271** [comment] 2023-06-28 22:50
The select issue is fixed, but after creating the new profile, it looks like the extensions didn't get reinstalled into the profile. The installed extensions section only lists the language packs even after reloading the window.

**Comment by rzhao271** [comment] 2023-06-28 22:51
Actually, closing again to file a new issue for it instead.

**Closed by rzhao271** 2023-06-28 22:51 UTC
Labels: bug, important, verified, user-profiles
