### ISSUE TITLE
highlight C++ code failed in one file

### ISSUE THREAD

**Issue by Andy-Amoy** [Microsoft/vscode#16605] opened 2016-12-06 10:28 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|java-debug|DSnake|0.0.2|
|Lua|keyring|0.0.8|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.3.2|
|java|redhat|0.0.7|
|Spell|seanmcbreen|0.9.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. just open a cpp file, the file generated by protobuffer, from line 1106, there is no more colors for any token
I have close the file and reopen it, while the issue is still there.

**Comment by aeschli** [comment] 2016-12-06 13:35
@Andy-Amoy Do you have a link such a file?

**Comment by aeschli** [comment] 2016-12-29 03:09
closing as duplicate of #17840

**Closed by aeschli** 2016-12-29 03:09 UTC
