### ISSUE TITLE
Extension Host is unresponsive

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#58661] opened 2018-09-14 06:38 UTC
Issue Type: <b>Bug</b>

It currently seems to be the case that the extension host is unresponsive frequently.

![image](https://user-images.githubusercontent.com/30625381/45533876-6db33180-b7f9-11e8-8efd-326be852ed8f.png)

When you open up the Running Extensions window it turns to

![image](https://user-images.githubusercontent.com/30625381/45533897-87547900-b7f9-11e8-81bc-13b076b4e664.png)

And after a while this process starts over

VS Code version: Code - Insiders 1.28.0-insider (a542a0afb5ff12a878dcf4b6a914f10d1318cb2e, 2018-09-14T05:12:35.372Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4351014|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
comment-anchors|Exo|1.2.0
vscode-pull-request-github|Git|0.1.5
beautify|Hoo|1.4.3
smarty|imp|0.3.0
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.85
php-symbols|lin|2.1.0
VS-code-vagrantfile|mar|0.0.7
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.10.1
color-highlight|nau|2.3.0
vetur|oct|0.12.6
vscode-docker|Pet|0.2.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
vscode-yaml|red|0.0.16
code-settings-sync|Sha|3.1.2
autoimport|ste|1.5.3
easy-snippet-maker|tar|0.0.6
Snippet|vsc|0.2.4
vim|vsc|0.16.4
quokka-vscode|Wal|1.0.148
vscode-import-cost|wix|2.9.0
sort-js-object-keys|zen|1.0.1

(1 theme extensions excluded)

</details>

**Comment by lyndonjohn** [comment] 2018-09-14 07:12
#58663

**Comment by lyndonjohn** [comment] 2018-09-14 07:13
#58663 Extension Host is unresponsive/Extension Host is now responsive

**Comment by clintwood** [comment] 2018-09-14 08:32
As a per session workaround, what works for me is to go to extensions, select the `...` menu and **Disable All Installed Extentions**, reload (on any one of the disabled extensions), once reloaded, **Enable All Extensions** then **Show Disabled Extensions** and hit reload on any of the extensions.

**Comment by alexandrudima** [comment] 2018-09-14 09:38
Duplicate of #58672

Please update, a new build with a fix is available. Sorry about that!

**Closed by alexandrudima** 2018-09-14 09:38 UTC
Labels: insiders

**Comment by Eventyret** [comment] 2018-09-14 09:58
@alexandrudima I still have the same issue even after the new build.

Version: 1.28.0-insider (user setup)
Commit: 29e6dce4352db76d8956035990b8630580226588
Date: 2018-09-14T08:23:30.210Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by alexandrudima** [comment] 2018-09-14 10:59
Please keep an eye out and let us know if you still see this false positive after you have updated and if you have some good steps.

If you see the popup you can also take a peek at Task Manager and check, perhaps the extension host is indeed busy and it wasn't a false positive after all.

In any case, if you see it please reach out. Thank you!

**Comment by clintwood** [comment] 2018-09-14 11:11
The update works for me - thank you!

**Comment by alexandrudima** [comment] 2018-09-14 12:51
@Eventyret Sorry for not being clear. After updating to the latest Insiders (kill all running processes of VSCode), do you still see the following popup:

![image](https://user-images.githubusercontent.com/5047891/45551235-85a4a880-b82d-11e8-966d-9b14eb26ad93.png)

If you do, can you please open a new issue with your environment, installed extensions, and perhaps some steps if any steps are required to reproduce.

**Comment by Eventyret** [comment] 2018-09-14 12:55
@alexandrudima i feel this can be closed. I will open a new issue and refer to this if it happends again (have a computer without the update so will update and test it straight off there in a few hours)

Thanks again.

**Comment by lyndonjohn** [comment] 2018-09-14 23:32
The last update fixed the issue. 👍

**Comment by joelgetaction** [comment] 2018-09-20 20:46
I still see this issue constantly.  I have upgraded to the latest build and it did not help.  I am on Version 1.28.0-insider (1.28.0-insider) at af3614909b837c46a260666cb7baab7a8468a9c8.

Any suggestions?  This is making it difficult to use VSCode because all my save on format, etc is all messed up and it's really slowing me down ... :-(

**Comment by alexandrudima** [comment] 2018-09-21 07:08
@joelgetaction Here is how you can profile extensions -- https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions -- use those steps to identify which extensions consume a lot of CPU.

**Comment by DuncanFaulkner** [comment] 2018-09-27 11:28
This seems to be happening more, updated this morning to latest insiders version, and get message popping up every 15 / 20 minutes or so. not installed any new extensions recently. would be nice for the pop up to mention which extension was having an issue.

Version: 1.28.0-insider
Commit: 2291080075f17a27a8cd709def0a2c9298a4155c
Date: 2018-09-27T05:18:27.312Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by joelgetaction** [comment] 2018-09-27 16:17
I am seeing this way more often as well lately. It got so bad that I had to switch back to the regular non-insiders build and that build had no issues.    Note that with the same exact setttings and installed extensions, the insiders build had serious issues with the extension host while the regular build did not. So the issue definitely seems to be with the insiders build ...
  

  
  

  
  
>

**Comment by icyJoseph** [comment] 2018-10-03 13:16
I've got the same problem now too. In the two computers I own, both with the insiders build. It seems that killing the process fixes it temporarily.

**Comment by monirkohi2006** [comment] 2018-10-03 22:45
Same here!

![image](https://user-images.githubusercontent.com/32991357/46443654-5219b780-c723-11e8-846e-3267beee77d4.png)

**Comment by toplinuxsir** [comment] 2018-10-09 23:32
version :  1.28 stable , the bug still exist!

**Comment by MoisesJR2016** [comment] 2018-10-10 03:52
i have the same trouble.

**Comment by technoiswatchingyou** [comment] 2018-10-10 04:59
Ma OSX 10.13.6. VSCode: 1.28 stable. The bug still exist.

**Comment by AreyXo** [comment] 2018-10-10 07:19
It's driving me nuts! the bug still exists.

Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by AreyXo** [comment] 2018-10-10 07:28
My running extenstions are:

![1](https://user-images.githubusercontent.com/28868973/46719626-162ca800-cc77-11e8-9771-660610346d01.PNG)
![2](https://user-images.githubusercontent.com/28868973/46719625-162ca800-cc77-11e8-8b23-68409844104c.PNG)

**Comment by wechuli** [comment] 2018-10-10 07:58
This is annoying as hell, every few minutes the notification pops up. Started seeing the problem after upgrading to 1.28

**Comment by NicolasReibnitz** [comment] 2018-10-10 11:16
Same here. Almost unusable since v1.28.

**Comment by nicubarbaros** [comment] 2018-10-10 11:19
Same here  Version 1.28.0

**Comment by shermendev** [comment] 2018-10-10 11:48
Same, have to restart a couple times.

**Comment by jsharer2** [comment] 2018-10-10 12:13
Same here, also v1.28.0

**Comment by simioluwatomi** [comment] 2018-10-10 13:05
Same here, v1.28.0 (user setup). Very annoying!!!!

**Comment by icyJoseph** [comment] 2018-10-10 13:33
Same here, again, for the n-th time, latest vs code insiders and regular. You managed to bloat VS Code out of proportion.

**Comment by HopeForToday** [comment] 2018-10-10 13:37
same here, also 1.28.0

**Comment by HopeForToday** [comment] 2018-10-10 13:46
> same here, also 1.28.0

It may take several minutes to get normal after I click `Restart Extension Host` button.

**Comment by Da13Harris** [comment] 2018-10-10 15:27
I'm also seeing this (1.28.0 user setup) every time I start up. If it's actually related to the extensions, these ones are common between mine and the two sets listed above by @NicolasReibnitz and @monirkohi2006.

CoenraadS.bracket-pair-colorizer
eg2.vscode-npm-script
esbenp.prettier-vscode
robertohuertasm.vscode-icons

**Comment by ryanaltvater** [comment] 2018-10-10 17:52
@alexandrudima This issue has completely killed my editor/workflow. I tried downgrading, but 1.27.7 also had a similar issue where the Extension Host was terminated. From the list above, I have `bracket-pair-colorizer`, but I noticed an issue where the `project-manager` extension seemed to bug out as well. So I tried disabled that as well and I'm still getting the unresponsive issue. Restarting the extension host just reproduces the popup again a minute later. VS Code is practically unusable in this state, unless I disable all of my extensions.

**Comment by MAQ7** [comment] 2018-10-10 18:10
Same issue here as well :(

**Comment by elmergomez** [comment] 2018-10-10 18:16
No matter what I do unresponsive issue continues popping up :(

**Comment by mikelnorth** [comment] 2018-10-10 20:18
The same issue, if it keeps happening I will have to try and uninstall and reinstall vs code entirely. 
Version 1.28.0 (user setup)
Electron: 2.0.9
Chrome: 61:0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

I don't even know what causes it. seems random for me, and on startup.

**Comment by CoolLby** [comment] 2018-10-11 01:29
The same issue, It affected my job.

### system info
- Version: 1.28.0 (user setup)
- Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
- Date: 2018-10-05T14:58:53.203Z
- Electron: 2.0.9
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

### Extension plug-in
![snipaste_2018-10-11_09-25-34](https://user-images.githubusercontent.com/38807139/46774997-c8c43f80-cd37-11e8-91eb-34ccb65be2fc.png)
![snipaste_2018-10-11_09-25-48](https://user-images.githubusercontent.com/38807139/46774998-c8c43f80-cd37-11e8-8254-34aae1caaab6.png)
![snipaste_2018-10-11_09-26-01](https://user-images.githubusercontent.com/38807139/46774999-c8c43f80-cd37-11e8-9fab-78f70ba6689b.png)
![snipaste_2018-10-11_09-26-13](https://user-images.githubusercontent.com/38807139/46775000-c95cd600-cd37-11e8-9eed-9c5de95c9f77.png)
![snipaste_2018-10-11_09-26-25](https://user-images.githubusercontent.com/38807139/46775001-c95cd600-cd37-11e8-98e0-98815fd5b4a1.png)

**Comment by howar31** [comment] 2018-10-11 02:09
Just updated to 1.28 and having this issue.  (was fine in 1.27)

> Version: 1.28.0 (user setup)
> Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
> Date: 2018-10-05T14:58:53.203Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

**Comment by ninja-saigon** [comment] 2018-10-11 06:59
The same problem to me after upgrading to Version: 1.28.0 (system setup) today.

> Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by nicubarbaros** [comment] 2018-10-11 08:20
Is there a way to go back to the previous version of VS Code?

**Comment by wechuli** [comment] 2018-10-11 08:51
@nicubarbaros , Not sure if this functionality is inside vs code itself but you can download a previous version and reinstall vs code- it will retain all your settings and extensions. Here is a link to previous versions, the August release should be okay.  https://code.visualstudio.com/updates/v1_26

**Comment by lolimay** [comment] 2018-10-11 09:59
> As a per session workaround, what works for me is to go to extensions, select the `...` menu and **Disable All Installed Extentions**, reload (on any one of the disabled extensions), once reloaded, **Enable All Extensions** then **Show Disabled Extensions** and hit reload on any of the extensions.

Thank you! Your solution is quite useful!

**Comment by NicolasReibnitz** [comment] 2018-10-11 11:45
Strangely enough it stopped bugging around since yesterday evening. The message that came up every ten minutes or so didn't come up since.
I keep my fingers crossed.

**Comment by t0mpy** [comment] 2018-10-11 13:11
This is the exact problem my friend and I are having when collaborating with VS live share. 
As soon as he minimises the project it throws the error and I can no longer do anything or view the localhost. Baffles me that this is even a topic of discussion and wasn't sorted with the update.

**Comment by J-J-J** [comment] 2018-10-11 15:34
same for me

**Comment by mikecarr** [comment] 2018-10-11 16:48
I am seeing some extensions taking a while to activate (~14 seconds) which correlates to the Unresponsive popup. Is is the extension loading blocking?

**Comment by hessnd** [comment] 2018-10-11 19:06
I have noticed the extension host going unresponsive consistently when having a typescript file open, then opening an html file in a second window pane. It seems that the process `Initializing JS/TS Features` may be causing this as that process is running for a long time in the bottom status bar.

**Comment by auchenberg** [comment] 2018-10-12 00:01
We have pushed a fix today to reduce the confusion about the unresponsive notification. See https://github.com/Microsoft/vscode/issues/60318

**Comment by Greyze** [comment] 2018-10-12 09:13
For me it's more annoying than anything because you can't stop them from appearing. My laptop is slow so it takes some time to load all extensions. I always get the 2 msgs (extension host is unresponsive, is now responsive).

I already knew code takes time to load on my machine and I know when it's ready and working. I don't need the constant notifications. They also don't go away by themselves so I have to click them away every single time I load code.

Need an option to disable these extension host notifications

**Comment by distante** [comment] 2018-10-12 14:30
> For me it's more annoying than anything because you can't stop them from appearing. My laptop is slow so it takes some time to load all extensions. I always get the 2 msgs (extension host is unresponsive, is now responsive).
> 
> I already knew code takes time to load on my machine and I know when it's ready and working. I don't need the constant notifications. They also don't go away by themselves so I have to click them away every single time I load code.
> 
> Need an option to disable these extension host notifications



> We have pushed a fix today to reduce the confusion about the unresponsive notification. See #60318
