### ISSUE TITLE
Chinese Characters Displayed Mistakenly in Mouse Hover

### ISSUE THREAD

**Issue by USHI-J** [microsoft/vscode#138308] opened 2021-12-02 03:37 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Enable auto guess encoding in setting, Chineses characters in files using GB2312 or other encodings designed for simplified Chinese can be displayed correctly as shown in figures:
![image](https://user-images.githubusercontent.com/88425098/144352588-186d5e6b-91ee-4c4a-951c-feba92189baf.png)

2. Enable hover in setting, when it works, Chinese charaters still will be processed errorly:
![image](https://user-images.githubusercontent.com/88425098/144352780-7407a892-c0b6-4216-8b6a-21aa8f5f0b29.png)
And it's intended to be like this:
![image](https://user-images.githubusercontent.com/88425098/144353135-db20339f-eda1-467c-89b9-0fe98d49eb74.png)
Which means auto guess encoding doesn't work for hover. Hope to repair it.

**Comment by yume-chan** [comment] 2021-12-02 18:32
Duplicate of microsoft/vscode-cpptools#4753

**Closed** 2021-12-02 22:27 UTC
Labels: *duplicate, *caused-by-extension
