### ISSUE TITLE
Context menu invoked with ContextMenu key always triggered from center in Explorer

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#109870] opened 2020-11-02 23:21 UTC
Issue Type: <b>Bug</b>

Every time when I use <kbd>ContextMenu</kbd> (code 93) in Explorer it is triggered on element it the center of the view and not for selected elements.
"Somewhat similar" behavior observed in Outline view - no context menu, but keyboard focus moved to element in the center.

This behavior is dangerous because it's easy to hit Delete or other action that hard to revert for wrong element and really breaks workflow because works as expected in any other view.

There are no problems with other tree views: References, NPM, Git, GitLens, GitHub Pull Request, Search Results.

There are no problems <kbd>Shift</kbd>+<kbd>F10</kbd> but this is much harder than dedicated context menu key.

Reproducible with `"window.titleBarStyle": "custom"`, in case of native there is another #79544 - context menu is hidden immediately (most likely because of focus change).

VS Code version: Code - Insiders 1.51.0-insider (49696e87c64f478f97909a91d41ff2913df9bf71, 2020-10-31T00:22:00.097Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.59GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04 --crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04 --crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by eamodio** [comment] 2020-11-03 00:00
I can reproduce this -- as mentioned `Shift+F10` works fine, but the `menu` key doesn't

**Comment by isidorn** [comment] 2021-01-28 11:01
Is there some simulator for the menu key, since I do not think I have it on my keyboard.
Do you have some ideas how I could reproduce this with a small apple keyboard

**Comment by IllusionMH** [comment] 2021-01-28 11:30
If you are going to reproduce this issue on Windows - best I can propose is built-in into **On-Screen Keyboard**.
Not sure if this issue exists on MacOS or how to trigger context menu there.

<details>
<summary>Screenshot</summary>

Button on keyboard is highlighted and underlined
![image](https://user-images.githubusercontent.com/1312662/106131211-119f9c80-616b-11eb-806a-a696f83901cf.png)

Triggered from On-Screen Keyboard in VS Code with `splash\electron-browser` selected
![image](https://user-images.githubusercontent.com/1312662/106131772-c639be00-616b-11eb-961f-13a27c60464a.png)

</details>

**Comment by isidorn** [comment] 2021-01-28 12:37
@IllusionMH thanks, I can try with Windows then.

**Comment by IllusionMH** [comment] 2021-01-28 12:48
@isidorn just in case there is PR #112168 which fixes issue for me when I apply it, however it has different assignee from this issue.

**Comment by gjsjohnmurray** [comment] 2021-01-28 15:21
Maybe close this as a duplicate of #100151, for which I submitted that PR.

**Comment by IllusionMH** [comment] 2021-01-28 15:27
It's nice to have at least one open issue so it won't be lost. I have no objections to close this one if #100151 reopened.

**Comment by isidorn** [comment] 2021-01-28 15:46
Ok, lets close this, and reopen the other one.

**Closed by isidorn** 2021-01-28 15:46 UTC
Labels: bug, file-explorer
