### ISSUE TITLE
vscode doesn't work with xmodmap on mapping about "tab"

### ISSUE THREAD

**Issue by deepkolos** [microsoft/vscode#81960] opened 2019-10-04 13:46 UTC
Issue Type: <b>Bug</b>

Tab -> BackSpace and Ctrl_L -> Tab,  doesn't work as expected in vs code

my `.Xmodmap` as below

```
! Tab -> BackSpace
keycode  23 = BackSpace KP_Enter BackSpace BackSpace

! Control_L -> Tab
keycode  37 = Tab ISO_Left_Tab Tab ISO_Left_Tab

! Shift_L -> Control_L
keycode  50 = Control_L NoSymbol Control_L

! Caps_Lock -> Shift_L
keycode  66 = Shift_L NoSymbol Shift_L

clear control
add control = Control_L
add control = Control_R

clear shift
add shift = Shift_L
add shift = Shift_R

clear lock
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.2.11-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2826)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|11.66GB (2.96GB free)|
|Process Argv|/run/media/deepkolos/Data/DEV/Github/opensource/vscode|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment] 2019-10-04 13:52
Can you elaborate a little on what you're trying to do here and what doesn't work? I suspect you're running into an issue with how the keybinding system works within VS Code.

**Comment by deepkolos** [comment] 2019-10-04 16:15
@Tyriar i just move to manjaro from windows, but i have some key remap on windows and i want to continue have that, so i search the web, it tells me xmodmap can do that, and it works, expect vscode.

and i found, after `xmodmap ~/.Xmodmap`

in first log Event.code still 'Tab' but key has changed to 'Backspace' , the second event log is trigger by original real backspace key

![无标题](https://user-images.githubusercontent.com/12824616/66222034-cefabb00-e702-11e9-9462-64021f279285.png)

And vs code read `event.code` so the map (tab -> backspace) doesn't work

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L534

![图片](https://user-images.githubusercontent.com/12824616/66222626-2fd6c300-e704-11e9-8541-bd94ea58c3fa.png)

**Comment by alexandrudima** [comment] 2019-10-04 19:17
Duplicate of https://github.com/microsoft/vscode/issues/23991

**Closed by alexandrudima** 2019-10-04 19:17 UTC
Labels: keybindings, needs more info
