### ISSUE TITLE
Bug in any color theme (closing quote) with font ligatures enabled

### ISSUE THREAD

**Issue by n1rdeks** [microsoft/vscode#115863] opened 2021-02-05 11:37 UTC
- VSCode Version: 1.53 and olders
- OS Version: Linux Debian

Steps to Reproduce:

1. Select color theme (any) - for example, Solarized Light
2. Write ```<div class="VSCode - nice text editor">``` (or change 'nice' to another word)

Does this issue occur when all extensions are disabled?: Yes

BUG  - closing quote change color 

![2021-02-05-144251_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/107029714-89e80c80-67c0-11eb-8d33-c55b1dda69f1.png)

**Comment by mjbvz** [comment] 2021-02-05 20:20
Please share example code as text (not just screenshots)

Also, your code is invalid (missing close tag). Does this happen with valid code too?

/needMoreInfo

**Comment by n1rdeks** [comment] 2021-02-05 20:43
Thanks for fast answer.

This is just example, guys. EVER code with tags reproduce this bug: HTML, JSX, TSX.


this another example (with screenshot), theme 'Dark+'
![2021-02-05-234137_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/107087000-d9075f00-680b-11eb-9d4c-36c78ea127be.png)
):

**Comment by n1rdeks** [comment] 2021-02-05 20:44
and code:

```
<header class="header">
    <div class="header__logo-box">
      <img class="header__logo" src="img/logo-white.png" alt="Logo must be here">
    </div>

    <div class="header__text-box">
      <h1 class="heading-primary">
        <span class="heading-primary_main">Outdoors</span>
        <span class="heading-primary_sub">is where life happens</span>
      </h1>

      <a href="#section-tours" class="btn btn_white btn_animated">Discover our tours</a>
    </div>
  </header>
```

**Comment by mjbvz** [comment] 2021-02-05 20:46
Thanks for the text. This doesn't happen for me though in an html file:

<img width="1011" alt="Screen Shot 2021-02-05 at 12 45 48 PM" src="https://user-images.githubusercontent.com/12821956/107087287-1807c700-67b0-11eb-8449-781ab7bda5a6.png">

Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by n1rdeks** [comment] 2021-02-05 21:06
this reproduce without extenions. BUT! If i remove ~./config/Code/User/settings.json - all fine.

this is my settings:
[settings.tar.gz](https://github.com/microsoft/vscode/files/5935333/settings.tar.gz)

But how? Where option for this bug?

**Comment by n1rdeks** [comment] 2021-02-05 21:09
i found. This is font. i remove PragmataPro and paste Dejavu Sans. Maybe ligatures? But PragmataPro i buy in 2017.

**Comment by mjbvz** [comment] 2021-02-05 21:36
How can we reproduce this without buying a font?

**Comment by n1rdeks** [comment] 2021-02-05 21:41
only for the science ;)
[liga.tar.gz](https://github.com/microsoft/vscode/files/5935464/liga.tar.gz)

**Comment by mjbvz** [comment] 2021-02-05 21:43
Please share how to use the font in VS Code too

**Comment by n1rdeks** [comment] 2021-02-05 21:47
```
    "editor.fontFamily": "PragmataPro Mono Liga",
    "editor.fontLigatures": true,
```

**Comment by fabrizioschiavi** [comment] 2021-02-08 09:07
@n1rdeks I don’t think this is caused by PragmataPro because if I change the color theme the issue disappears.
How a font can caused a similar issue?

**Comment by n1rdeks** [comment] 2021-02-08 10:42
Thanks for fast replay, @fabrizioschiavi. I checked on another fonts with ligatures (iosevka, fira and more) - no problem. 
This bug reproducing only with PragmataPro Liga (and Mono Liga too). I think (IMHO), because symbols  '"' and '>' in ligature mode create 1 symbol. If i set space between 'quote' and '>' - all fine. 

I say again. In Emacs with ligatures this bug reproduce too. Only in PragmataPro Liga.

**Comment by fabrizioschiavi** [comment] 2021-02-08 14:09
Doesn’t exists `'>` ligature in PragmataPro Liga and Mono Liga.
I’ll investigate about `'>` combination but I have serious doubt it that can be the cause

**Comment by n1rdeks** [comment] 2021-02-08 14:50
Thanks.  ">  - this combination corrupt themes. If i set space, all normal.

**Comment by fabrizioschiavi** [comment] 2021-02-08 15:27
Ah ok! Sorry for this misunderstanding. `">` exists as ligature. 
I know how to fix it. I'll do it soon.

**Comment by n1rdeks** [comment] 2021-02-08 16:28
Nice. So? We close this thread and w8 new  cool  version PragmataPro (.830)? Or you commit here fix history with notes?

**Comment by fabrizioschiavi** [comment] 2021-02-08 16:39
We can close this thread and waiting/working at version .829 😉

**Closed** 2021-02-08 16:40 UTC
