### ISSUE TITLE
Is not opennig the default terminal

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#130285] opened 2021-08-06 19:31 UTC
We have written the needed data into your clipboard because it was too large to send. Please 
Issue Type: <b>Bug</b>

When you open a new terminal, either using mouse or shortcut, it's not opening  the default terminal we had configured. It opens the previous default terminal. In my case, I've set git bash as default terminal, but vscode still opens powershell.

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.01GB free)|
|Process Argv|--crash-reporter-id 63821a43-8652-4354-909d-b2d830113442|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
delphi-pack|ale|2.0.0
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
project-manager|ale|12.3.0
read-only-indicator|ale|3.5.0
vscode-django|bat|1.6.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.43.2
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
gitlens-insiders|eam|2021.7.1905
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
MagicPython|mag|1.1.0
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-ssh-edit-nightly|ms-|2021.8.5221
remote-ssh-nightly|ms-|2021.8.5221
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4650
resourcemonitor|mut|1.0.7
embrace|myc|1.0.0
autodocstring|njp|0.5.4
remove-comments|pli|1.2.2
java|red|0.80.0
markdown-preview-enhanced|shd|0.5.22
open-in-browser|tec|2.0.0
remove-empty-lines|use|0.0.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.2
vscode-java-test|vsc|0.31.0
vscode-maven|vsc|0.32.2
vscode-icons|vsc|11.6.0
vscode-wakatime|Wak|14.0.3
jinja|who|0.0.8
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedc:30346832

```

</details>

paste.

**Comment by IllusionMH** [comment] 2021-08-06 19:36
/duplicate of #130268

Fixed for tomorrow night Insiders build

**Closed** 2021-08-06 19:37 UTC
Labels: *duplicate
