### ISSUE TITLE
git source control showing wrong layout

### ISSUE THREAD

**Issue by jlgenesis** [microsoft/vscode#103865] opened 2020-08-03 21:28 UTC
Issue Type: <b>Bug</b>

1. click git icon left icon collection.
2. click ... icon in source control panel.

When I click Source Control ... icon it shows category of what i can choose. However, I select one of the list like [pull, push], it shows related sub panel after more than 100px blank space. 

main panel   [space]  sub panel.

VS Code version: Code - Insiders 1.48.0-insider (5696babbc1dce41788bae04b1a04ad35140bebfb, 2020-08-03T05:51:31.732Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.5.3
vscode-standardjs|che|1.3.0
vscode-html-css|ecm|0.2.3
auto-rename-tag|for|0.1.4
vscode-docker|ms-|1.4.1
color-highlight|nau|2.3.0
java|red|0.65.0
vscode-scss-formatter|sib|2.0.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-08-03 22:41
/duplicate of #103815 which should be fixed in Tuesday's Insiders.

**Closed** 2020-08-03 22:41 UTC
Labels: *duplicate
