### ISSUE TITLE
CSS string with escape newline (`'\`) breaks syntax hightlighting

### ISSUE THREAD

**Issue by hibiyasleep** [microsoft/vscode#159730] opened 2022-09-01 06:21 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS 12.4

Steps to Reproduce:

1. Open empty document, set language to CSS.
2. write: `body { content: 'a\` (newline here) `b'; }`
3. write some valid (or not) CSS code, all syntax highlighting gone.

when inspected, `\` and all after is interpreted as `constant.character.escape.newline.css`.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/5380174/187843140-f0d8f250-254b-47bd-9dd3-f4f2946287e3.png">

css3 specs here: https://www.w3.org/TR/css-syntax-3/#consume-string-token
css21 specs here (with example of this case): https://www.w3.org/TR/CSS21/syndata.html#strings

**Comment by aeschli** [comment] 2022-09-01 14:32
Duplicate of https://github.com/atom/language-css/issues/181

**Closed by aeschli** 2022-09-01 14:32 UTC
