### ISSUE TITLE
Kernel picker in vscode for web on codespaces is empty (shows only "Existing Jupyter Server")

### ISSUE THREAD

**Issue by ucovcoder** [microsoft/vscode#189276] opened 2023-07-30 20:38 UTC
Created a new Codespace using the universal image on a new python repo. On first usage I was able to run Jupyter notebooks and Python Interactive windows just fine but the second time I started the Codespace the kernel picker was empty except for one option to "Select existing Jupyter server..."

The option to choose my current Python env as the Kernel source is not available:
![image](https://github.com/microsoft/vscode/assets/140887360/ca2c2966-9d1a-4633-9f88-b50986098d6f)

`ipykernel` is available and up-to-date in my env:
![image](https://github.com/microsoft/vscode/assets/140887360/fe26c5f4-a77f-4a04-bdda-8263f5146e95)

Jupyter extension properly installed:
![image](https://github.com/microsoft/vscode/assets/140887360/be570071-d02d-4d21-a8ce-6df1500541ae)

When opening the Codespace in VSCode desktop the kernel picker works as expected.

Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188
Embedder: codespaces

**Comment by DonJayamanne** [comment] 2023-07-31 06:05
Duplicate of https://github.com/microsoft/vscode/issues/189280

**Closed by DonJayamanne** 2023-07-31 06:05 UTC
