### ISSUE TITLE
VS code installation

### ISSUE THREAD

**Issue by faisu411** [microsoft/vscode#128938] opened 2021-07-18 06:48 UTC
I followed all the steps mentioned on " https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started ". But still, VS Code is not installed in my chromebook.
![image](https://user-images.githubusercontent.com/79015005/126058355-0853620f-a43c-4b94-b255-c72bb42ba8cf.png)

**Comment by ItalyPaleAle** [comment] 2021-07-19 15:04
Can you try running:

```sh
sudo apt-get install -y libnss3
```

Please let me know if this works

**Comment by rzhao271** [comment] 2022-12-06 00:09
This bug should be fixed on newer versions of the VS Code deb package. Let me know if the issue is still not resolved for you.

**Closed by rzhao271** 2022-12-06 00:09 UTC
Labels: bug, install-update, linux
