### ISSUE TITLE
Wrong order for a LTR & RTL languages ,numbers

### ISSUE THREAD

**Issue by FlavaSava7** [microsoft/vscode#94784] opened 2020-04-09 12:44 UTC
- VSCode Version: 1.44.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce(with out without spaces between words&numbers):

1. type any english word
2. type RTL word (i.e. arabic)
3. type any number

result - > qwerأبجد123 (wrong)
'أبجد' should come after 'qwer' (correct)

It was working before the latest version. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-04-09 15:27
Duplicate of https://github.com/microsoft/vscode/issues/11770

**Closed** 2020-04-09 15:27 UTC
Labels: *duplicate, new release
