### ISSUE TITLE
Variable expressions in template strings are no longer being highlighted

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#15990] opened 2016-11-23 23:31 UTC
- VSCode Version: 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
- OS Version: OS X El Cap 10.11.5

Steps to Reproduce:

1. Create a `.js` file
2. Write a template string.

![VS Code Screenshot](https://cloud.githubusercontent.com/assets/829827/20582007/c94ff368-b191-11e6-9ea3-375ecdd0262d.png)

I would expect to see the `${expr}` to be highlighted separately from the rest of the string. VS Code used to do this, but has stopped with more recent releases.

**Comment by aeschli** [comment] 2016-11-24 08:46
duplicate of #13166

**Closed by aeschli** 2016-11-24 08:46 UTC
