### ISSUE TITLE
The Typescript language service died unexpectedly 

### ISSUE THREAD

**Issue by JT4nk** [Microsoft/vscode#22459] opened 2017-03-11 20:04 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|ccd-typescript|codechemistry|0.1.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|xml|DotJoshJohnson|1.7.0|
|vscode-html-css|ecmel|0.0.33|
|vscode-npm-script|eg2|0.1.8|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.1|
|vscode-javac|georgewfraser|0.0.23|
|ionic2-vscode|jgw9617|1.0.0|
|cpptools|ms-vscode|0.10.1|
|material-icon-theme|PKief|1.3.4|
|qub-xml|qub|1.0.3|
|java|redhat|0.0.10|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment] 2017-03-11 23:27
Closing as duplicate of #22457 logged by the same person

**Closed by ramya-rao-a** 2017-03-11 23:27 UTC
