### ISSUE TITLE
code crashed with SIGSEGV in __start_google_malloc()

### ISSUE THREAD

**Issue by davidgu** [Microsoft/vscode#45490] opened 2018-03-10 22:12 UTC
- VSCode Version: 1.21.0-1520420608
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install VS Code from .deb package
2. Attempt to launch VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-03-23 22:31
@flexiondotorg have you seen anything like this happening on Ubuntu 18.04? This is the first time I've seen mention of "__start_google_malloc"

**Comment by bartvanheukelom** [comment] 2018-03-27 15:10
I'm experiencing this crash as well, VSCode 1.21.1 on Ubuntu 17.10, but I've found a workaround at https://divideandconquer.se/2017/11/23/workaround-for-crashing-electronatom-applications/

* The workaround is starting VSCode using `GTK2_RC_FILES= code`

**Comment by Tyriar** [comment] 2018-03-27 17:42
Thanks for the info @bartvanheukelom. I'll close this off as it seems to be a problem with Ubuntu/GTK2 and we'll be moving to GTK3 soon.

**Comment by Tyriar** [comment] 2018-03-27 17:42
FYI @bpasero

**Closed by Tyriar** 2018-03-27 17:42 UTC
Labels: linux, needs more info

**Comment by bpasero** [comment] 2018-03-28 04:43
@davidgu @bartvanheukelom does it reproduce with https://az764295.vo.msecnd.net/exploration/cf078a8a932cd399f9e475b5ad4226bbc93543ab/code-exploration-1.22.0-1522130024_amd64.tar.gz ?
