### ISSUE TITLE
Global find/replace freezes visual studio code

### ISSUE THREAD

**Issue by MadCoder253** [Microsoft/vscode#12408] opened 2016-09-21 21:16 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10 (1607) 8GB ram

Steps to Reproduce:
1. Open PHP source code folder in Visual Studio Code
2. Roughly 250 code files 
3. NOTE: Going through process of upgrading to mysqli, so created equivalent functions that use mysqli instead of mysql
4. Set Search = mysql_num_rows(
5. Set Replace = num_rows(
6. Click the replace all button
7. Dialog: Replace 162 occurences across 89 files with 'num_rows'?
8. Clicked Replace button
9. Visual Studio Code Freezes
10. Dialog: The window is longer responding. You can reopen or close the window or keep waiting. [Reopen] [Keep Waiting] [Close]
11. The only button that seems to work is clicking [Close]

NOTE: I tried other searches with fewer than 50 files and it worked fine. All the files get opened in Visual Studio Code and I can click save all, then close all the windows.

**Comment by MadCoder253** [comment] 2016-09-21 21:32
Just did some more testing. Find/Replace worked when I got down to about 20 files, I didn't check between 30 to 40 files.

**Comment by sandy081** [comment] 2016-10-03 12:05
@MadCoder253  Sorry to know that VS Code freezes during this. It would be helpful to profile and find out where most time is spend. Can you follow below steps and after starting profiling to the reload action and when everything is loaded stop the profiling?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* Perform serch and wait for results
* click the start button
* Perform replace
* wait for some time (it would be good until the replace is finished)
* If it is not finishing, stop the profiling 
* click the save button and attach the output file to this issue

Thanks

**Comment by MadCoder253** [comment] 2016-10-03 19:31
Hi @sandy081, 

I think I have a little more information on the crash that's happening on my computer. Today I restarted my computer due to some updates and then I opened Visual Studio Code and performed the search and replace, and it worked fine. I then tried doing a few more and on the 5th attempt, Visual Studio Code crashed. 

I wasn't able to save the Profile, instead I saw the following dialog box...
<img width="314" alt="vs code crash" src="https://cloud.githubusercontent.com/assets/9192404/19050754/da53acc2-8964-11e6-9657-563941f11ef3.png">

After VS Code restarted, I saw this dialog box. 
<img width="260" alt="vs code crash 2" src="https://cloud.githubusercontent.com/assets/9192404/19050771/efb84df2-8964-11e6-854c-8c59ea73aafb.png">

After closing the dialog, I was able to save a profile, but it had very little info, see attachment. 
[CPU-20161003T121520 crash.zip](https://github.com/Microsoft/vscode/files/507029/CPU-20161003T121520.crash.zip)

**Comment by sandy081** [comment] 2016-10-04 09:31
@MadCoder253 Attached profile is not helpful.. May I know if you have a special setup
- If you have extensions installed, can you please disable them and try `code --disable-extensions`
- If your workspace is in a mapped network drive?


Attaching the screenshot of my experience of replacing around 300+ files. It is quiet fast.

![oct-04-2016 11-27-40](https://cloud.githubusercontent.com/assets/10746682/19069166/ff7ac488-8a25-11e6-8ba6-6fee22490bc9.gif)

**Comment by carlin-q-scott** [comment] 2016-10-12 17:12
I can reproduce this with a single large file (~10k lines). I tried profiling the issue but the profiler didn't stop after clicking stop. The developer tools are fully responsive and so is the menu bar but everything else is not responsive. I cannot exit the application at all, even Windows doesn't offer to terminate it.

**Comment by sandy081** [comment] 2016-12-07 20:29
@carlin-q-scott Sorry for getting back to it very late, is it possible to provide CPU profile this could be helpful to know where the time takes. Is it also possible to get the file and what are you replacing in it so that I can reproduce it from my side.

- To create a CPU profile using developer tools in VS Code:
    * select Help > Toggle Developer Tools
    * click on Profiles
    * click the start button
    * do replace functionality to get the CPU spin high
    * wait for some time (10-20 seconds should be enough)
    * stop the profiling
    * click the save button and attach the output file to this issue

**Comment by carlin-q-scott** [comment] 2016-12-10 00:08
The Profiler doesn't stop when I click stop so I cannot provide a CPU profile. I used a minified webapp but it's not a public webapp so I can't share that yet. Maybe this [public site's js](https://www.tuftandneedle.com/javascripts/vendor/all-edebd8b0.js) will work.

I actually cannot reproduce this issue right now and that may have something to do with the fact that the syntax highlighter isn't running on the large minified files. It's all just gray text now.

**Comment by sandy081** [comment] 2017-01-23 19:46
Closing this as it is not able to reproducable

**Closed** 2017-01-23 19:46 UTC
Labels: freeze-slow-crash, needs more info, search

**Comment by MadCoder253** [comment] 2017-01-23 20:15
Thank you, with the last few updates, I haven't had any search issues. Very fast, even on large codebases. Kudos.

**Comment by ankitrg** [comment] 2017-06-08 06:56
I am still facing this problem. My system freezes if I do a project wide search. Any feedback on how can I fix this?

**Comment by chrmarti** [comment] 2017-06-08 15:11
@ankitrg Could you file a new issue through Help > Report Issues? The implementation has changed significantly since and you are most likely seeing a new problem.

**Comment by cino893** [comment] 2017-07-25 13:55
Solution for ubuntu/mint distro GNU/Linux:
In first of all remove VSCode:
***note** in case important settings/snippets do backup
```
sudo apt-get remove code 
sudo apt-get purge code
rm -r ~/.config/Code
rm -r ~/.vscode
```
also it's good to rm .vscode and .tmp directory in your project directory
then
`
apt-get install code
`
or
`
dpkg -i YOUR_DOWNLOADED_VS_CODE_PACKAGE.deb
`
enjoy vscode without hanging
