### ISSUE TITLE
Emmet 2.0:  Insertion point is in wrong place after completion

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29276] opened 2017-06-22 16:54 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (d5e10a589ff68d026ba9cf57485d3004149a9c8a, 2017-06-22T05:33:25.311Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.3
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.15.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.25.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Type a tag, e.g. `h1`
2. Accept the emmet completion, you get `<h1></h1>` as expected
3.Except the cursor is _after_ the completion, instead of inside the tag, so you can enter the text that goes in the `h1` as expected.

![jun-22-2017 12-51-54](https://user-images.githubusercontent.com/835148/27445998-e8da4a9a-5749-11e7-93ed-c347c5f57917.gif)

**Comment by ramya-rao-a** [comment] 2017-06-22 17:43
This is because the snippet returned by the [emmet expand module](github.com/emmetio/expand-abbreviation) in this case is `<h1></h1>` and not `<h1>${0}</h1>`

@sergeche This is not the case in your emmet plugin. Is there anything extra that the plugin is doing? If so, shouldnt that be moved into the emmet module?

**Comment by sergeche** [comment] 2017-06-22 21:04
The `${0}` marker etc is controlled by the `field` option of `expand-abbreviation`: https://github.com/emmetio/expand-abbreviation/blob/master/test/html.js#L14
It must be missing

**Comment by smlombardi** [comment] 2017-06-22 22:03
"Sequential" insertion points are missing too, such as when inserting two divs (e.g. `div>div.foo+div.bar`)

**Comment by ramya-rao-a** [comment] 2017-06-22 22:52
@sergeche That's exactly what I am using https://github.com/ramya-rao-a/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L118

The issue is not that none of the tab stops are being returned. For eg: `a` gives `<a href="${1}"></a>`  where as I'd expect  `<a href="${1}">${0}</a>`

**Comment by sergeche** [comment] 2017-06-22 23:01
The examples above works fine in Atom and unit-tests. Can you ensure that generated snippet doesn’t have expected tab stops?

**Comment by ramya-rao-a** [comment] 2017-06-22 23:35
Ah! I found the issue

https://github.com/ramya-rao-a/vscode-emmet-helper/blob/8272da0dc9e31d13b9f7c72ec6872c5daf23b54c/src/emmetHelper.ts#L151

Need to send `null` and not empty string in the `text` option

Thanks @sergeche !

**Comment by ramya-rao-a** [comment] 2017-06-23 00:02
Fixed with https://github.com/ramya-rao-a/vscode-emmet-helper/commit/cbef48cafbe879fd02813519d4d85bea73d2e531

Thanks for reporting @smlombardi !

**Closed** 2017-06-23 00:02 UTC
Labels: bug, insiders
