### ISSUE TITLE
Error looping: "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

### ISSUE THREAD

**Issue by gitcarter** [Microsoft/vscode#42236] opened 2018-01-27 08:30 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
vscode-docker|Pet|0.0.23
vscode-eslint|dba|1.4.4
prettify-json|moh|0.0.3
python|ms-|0.9.1
debugger-for-chrome|msj|4.1.0
sqltools|mtx|0.11.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2018-01-29 17:34
A few questions:

- Does this happen if you disable all extensions?
- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by jpike88** [comment] 2018-02-01 09:18
I am getting the same issue.

**Comment by jpike88** [comment] 2018-02-01 09:22
vscode-deepscan|Dee|1.5.0
code-settings-sync|Sha|2.8.7
vscode-standardjs-snippets|cap|0.7.5
sql-formatter|cym|1.0.2
vscode-statusbar-debugger|fab|1.3.2
debugger-for-chrome|msj|4.1.0
change-case|wma|1.0.0

**Comment by jpike88** [comment] 2018-02-01 09:23
![screen shot 2018-02-01 at 4 23 11 pm](https://user-images.githubusercontent.com/9585787/35670846-3a24fd46-076c-11e8-8f74-54e8bdd9c445.png)

**Comment by jpike88** [comment] 2018-02-01 09:23
looks like git is freaking out...? the project isn't even a TypeScript project either...

**Comment by jpike88** [comment] 2018-02-01 09:26
funny thing is i just opened a seperate window which I have a TypeScript task for and fired it up, works fine. This error is occuring in a project that doesn't have a .tsconfig or anything like that.

**Comment by jpike88** [comment] 2018-02-01 09:38
OK now it's happening in both windows. This is probably the result of the upgrade to 1.19.3, it started happening today when I updated.

And it's an incredibly frustrating error, I have no idea how to provide more useful information. Nothing in output or debug console or whatever, no way to debug it. Please tell me this is showing up in your error reporting tools or something.

**Comment by jpike88** [comment] 2018-02-01 09:52
Ok this needs to be treated as a critical bug, I'm slowly going insane from that stupid error bar getting in the way of my tabs.

Does this happen if you disable all extensions?
**Yes**

Does this happen for all projects you open, or just one specifically?
**All projects. One is TypeScript, one is plain NodeJS Javascript.**

Have you set a custom typescript.tsdk value in your workspace or user settings?
**No.**

Can you also please try collecting the TypeScript server logs:
**a buttload of folders are being generated with zero contents in them**

![screen shot 2018-02-01 at 4 46 20 pm](https://user-images.githubusercontent.com/9585787/35671974-8e6a47d2-076f-11e8-8858-60b8831a3136.png)

**The output looks like this... it keeps failing on the configure request**

[dump.txt](https://github.com/Microsoft/vscode/files/1684950/dump.txt)

**Comment by jpike88** [comment] 2018-02-01 09:52
Ok a fresh install seemed to have fixed the issue. This was very triggering so I'm going to pretend it didn't happen... hopefully the info I provided helped.

**Comment by mjbvz** [comment] 2018-02-06 02:42
Closing as we need the requested information from the original poster in order to investigate this issue

**Closed by mjbvz** 2018-02-06 02:42 UTC
Labels: needs more info
