### ISSUE TITLE
SCM did not show the changed files

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#192973] opened 2023-09-13 07:25 UTC
Type: <b>Bug</b>

SCM did not show the changed files in vscode remote, I have retry to reconnect and re-open. But it doesn't work

Here is video

https://github.com/microsoft/vscode/assets/9758711/ffcb0872-c184-4d87-9c04-c19070990f63

and here is Git output, it seem there is no error output

```
2023-09-13 15:13:58.184 [info] 日志级别: Info
2023-09-13 15:13:58.184 [info] 正在验证在以下位置找到的 git: "C:\Program Files\Git\cmd\git.exe"
2023-09-13 15:13:58.184 [info] 将使用位于 "2.30.0.windows.1" 的 Git "C:\Program Files\Git\cmd\git.exe"
2023-09-13 15:13:58.184 [info] > git rev-parse --show-toplevel [51ms]
2023-09-13 15:13:58.184 [info] > git rev-parse --git-dir --git-common-dir [47ms]
2023-09-13 15:13:58.184 [info] Open repository: c:\Users\Admin\gpm\192.168.0.254\digimaple\cloudoc_im_pc
2023-09-13 15:13:58.184 [info] > git config --get commit.template [57ms]
2023-09-13 15:13:58.184 [info] > git rev-parse --show-toplevel [53ms]
2023-09-13 15:13:58.184 [info] > git rev-parse --show-toplevel [55ms]
2023-09-13 15:13:58.185 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [104ms]
2023-09-13 15:13:58.185 [info] > git rev-parse --show-toplevel [54ms]
2023-09-13 15:13:58.185 [info] > git rev-parse --show-toplevel [154ms]
2023-09-13 15:13:58.240 [info] > git rev-parse --git-dir --git-common-dir [61ms]
2023-09-13 15:13:58.245 [info] Open repository: c:\Users\Admin\gpm\192.168.0.254\digimaple\cloudoc_im_pc\brand
2023-09-13 15:13:58.259 [info] > git status -z -uall [306ms]
2023-09-13 15:13:58.319 [info] > git config --get commit.template [65ms]
2023-09-13 15:13:58.341 [info] > git rev-parse --show-toplevel [84ms]
2023-09-13 15:13:58.354 [info] > git config --get commit.template [83ms]
2023-09-13 15:13:58.370 [info] > git for-each-ref --format %(refname) %(objectname) %(*objectname) refs/tags [89ms]
2023-09-13 15:13:58.405 [info] > git rev-parse --show-toplevel [56ms]
2023-09-13 15:13:58.420 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [131ms]
2023-09-13 15:13:58.473 [info] > git rev-parse --show-toplevel [63ms]
2023-09-13 15:13:58.532 [info] > git rev-parse --show-toplevel [53ms]
2023-09-13 15:13:58.565 [info] > git status -z -uall [189ms]
2023-09-13 15:13:58.607 [info] > git rev-parse --show-toplevel [70ms]
2023-09-13 15:13:58.657 [info] > git config --get commit.template [68ms]
2023-09-13 15:13:58.673 [info] > git for-each-ref --format %(refname) %(objectname) %(*objectname) refs/tags [75ms]
2023-09-13 15:13:58.681 [info] > git rev-parse --show-toplevel [66ms]
2023-09-13 15:13:58.742 [info] > git rev-parse --show-toplevel [55ms]
2023-09-13 15:13:58.764 [info] > git status -z -uall [338ms]
2023-09-13 15:13:58.813 [info] > git rev-parse --show-toplevel [63ms]
2023-09-13 15:13:58.852 [info] > git status -z -uall [172ms]
2023-09-13 15:13:58.871 [info] > git rev-parse --show-toplevel [53ms]
2023-09-13 15:13:58.927 [info] > git rev-parse --show-toplevel [50ms]
2023-09-13 15:13:58.986 [info] > git rev-parse --show-toplevel [53ms]
2023-09-13 15:13:59.777 [info] > git rev-parse --show-toplevel [784ms]
2023-09-13 15:13:59.848 [info] > git rev-parse --show-toplevel [55ms]
2023-09-13 15:13:59.901 [info] > git rev-parse --git-dir --git-common-dir [47ms]
2023-09-13 15:13:59.908 [info] Open repository: c:\Users\Admin\gpm\192.168.0.254\digimaple\cloudoc_im_pc\src\vendor
2023-09-13 15:13:59.979 [info] > git config --get commit.template [65ms]
2023-09-13 15:13:59.982 [info] > git for-each-ref --format %(refname) %(objectname) %(*objectname) refs/tags [63ms]
2023-09-13 15:14:00.061 [info] > git status -z -uall [72ms]
2023-09-13 15:14:00.132 [info] > git config --get commit.template [55ms]
2023-09-13 15:14:00.148 [info] > git for-each-ref --format %(refname) %(objectname) %(*objectname) refs/tags [66ms]
2023-09-13 15:14:00.216 [info] > git status -z -uall [63ms]
2023-09-13 15:14:01.729 [info] > git check-ignore -v -z --stdin [67ms]
2023-09-13 15:14:01.732 [info] > git check-ignore -v -z --stdin [76ms]
2023-09-13 15:14:02.275 [info] > git check-ignore -v -z --stdin [71ms]
2023-09-13 15:15:56.612 [info] > git config --get commit.template [48ms]
2023-09-13 15:15:56.667 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [94ms]
2023-09-13 15:15:56.992 [info] > git status -z -uall [320ms]
2023-09-13 15:15:57.055 [info] > git config --get commit.template [53ms]
2023-09-13 15:15:57.108 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [100ms]
2023-09-13 15:15:57.405 [info] > git status -z -uall [292ms]
2023-09-13 15:16:20.419 [info] > git config --get commit.template [52ms]
2023-09-13 15:16:20.481 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [103ms]
2023-09-13 15:16:20.838 [info] > git status -z -uall [352ms]
2023-09-13 15:16:22.232 [info] > git config --get commit.template [65ms]
2023-09-13 15:16:22.285 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [105ms]
2023-09-13 15:16:22.650 [info] > git status -z -uall [360ms]
2023-09-13 15:20:15.044 [info] > git check-ignore -v -z --stdin [55ms]
2023-09-13 15:20:15.078 [info] > git check-ignore -v -z --stdin [77ms]
2023-09-13 15:20:15.850 [info] > git check-ignore -v -z --stdin [53ms]
2023-09-13 15:20:56.648 [info] > git config --get commit.template [55ms]
2023-09-13 15:20:56.701 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [100ms]
2023-09-13 15:20:56.995 [info] > git status -z -uall [289ms]
2023-09-13 15:20:57.130 [info] > git config --get commit.template [58ms]
2023-09-13 15:20:57.182 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [99ms]
2023-09-13 15:20:57.522 [info] > git status -z -uall [335ms]
2023-09-13 15:20:58.595 [info] > git config --get commit.template [55ms]
2023-09-13 15:20:58.659 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [108ms]
2023-09-13 15:20:58.955 [info] > git status -z -uall [289ms]
2023-09-13 15:21:02.601 [info] > git config --get commit.template [52ms]
2023-09-13 15:21:02.647 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [90ms]
2023-09-13 15:21:03.008 [info] > git status -z -uall [355ms]

```

VS Code version: Code 1.82.1 (Universal) (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:32.930Z)
OS version: Darwin x64 21.6.0
Modes:
Remote OS version: Windows_NT x64 10.0.19045

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: windows/amd64(remote)|
|OS|Windows_NT x64 10.0.19045|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 2594)|
|Memory (System)|63.92GB (13.78GB free)|
|VM|50%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-nginx-conf|ahm|0.3.2
s4|axe|0.1.1
vscode-plist|ivh|0.1.3
dotenv|mik|1.0.1
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.107.2023091215
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.2023091209
material-icon-theme|PKi|4.30.1
sqlite-viewer|qwt|0.3.13
vscode-nginx|sha|0.6.0
svg-preview|Sim|2.8.3
vscode-icons|vsc|12.5.0
vscode-todo-highlight|way|1.0.5
vscode-nginx|wil|0.7.2
vscode-caddyfile-syntax|zam|1.0.4
vscode-gpm|axe|2.7.8
vscode-whatchanged|axe|0.2.5
vscode-css-modules|cli|0.5.1
vscode-eslint|dba|2.4.2
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
copilot|Git|1.111.404
git-graph|mhu|1.30.0
websocket-client|moh|0.2.0
vscode-language-pack-zh-hans|MS-|1.82.2023090609
vetur|oct|0.37.3
vscode-versionlens|pfl|1.7.2
vscode-thunder-client|ran|2.12.0
luna-paint|Tyr|0.16.0
pretty-ts-errors|yoa|0.5.1

(1 theme extensions excluded)

</details>

**Comment by axetroy** [comment] 2023-09-28 07:49
> @axetroy, sorry for not getting back to you on this. Could you please share more information about your setup? How are you connecting to the remote? From the recording I see that you are running `git status` in a folder on the C:\ drive, but the title in VS Code says that you are using SSH. Are you using SSH to connect to a Windows machine or you have somehow mapped the remote machine locally? Thanks!

@lszomoru

Yes, I am connecting to remote via `Remote - SSH` and running `git status` command at remote Windows server.

Command line works fine, but SCM not. I just found thi issue and report it.

sorry, I can not repro this issue.

If you feel there is insufficient information to find the bug, please feel free to close the issue.

Because it's hard for me to go back to where I was at that time. Thanks for your time.

**Comment by lszomoru** [comment] 2023-09-28 11:41
@axetroy, thanks for getting back to me on this. I am unable to reproduce the issue and based on the provided information I am currently stuck. I will go ahead and close this issue but please feel free to reopen it inc case you are able to reproduce the issue. Thank you!

**Closed** 2023-09-28 11:41 UTC
Labels: info-needed, git, ssh
