### ISSUE TITLE
Bad scrolling in "Open Editors" pane

### ISSUE THREAD

**Issue by SpaceManiac** [Microsoft/vscode#10509] opened 2016-08-14 06:14 UTC
- VSCode Version: 1.4.0 (6276dcb0)
- OS Version: Windows 7 x64

Steps to Reproduce:
1. Open four or more files in the left pane and four or more files in the right pane
2. Open, close, and rearrange tabs in these panes over time

Extensions: TOML Language Support, Rusty Code

Dev console contains no errors obviously related to this issue. Proper functionality can be restored by issuing `>Reload Window`.

GIFs of issue (two separate occasions):
![anim1](https://cloud.githubusercontent.com/assets/222630/17647587/41efc7d0-61ab-11e6-961c-27f7031528fb.gif)
![anim2](https://cloud.githubusercontent.com/assets/222630/17647588/445f7f24-61ab-11e6-8e36-f1175828fab3.gif)

**Comment by joaomoreno** [comment] 2016-08-15 09:27
@isidorn Try to reproduce this and let me know what you find.

**Comment by isidorn** [comment] 2016-08-24 14:38
@joaomoreno I can repro this consistently on win7, but not on the mac

**Comment by entr0cks** [comment] 2017-03-19 09:44
Still a thing - like "right" pane would be fixed while scrolling. 
Adding a third pane added "center" to the top that behaved the same way. 
After rearranging tabs with keyboard shortcuts a few times reverted scrolling to normal.
VSCode Version 1.10.2
Windows 10 Pro x64 
![scrolling](https://cloud.githubusercontent.com/assets/5465193/24079755/49177a2e-0c98-11e7-9dfe-20595eef34b5.gif)

**Comment by joaomoreno** [comment] 2017-03-20 12:00
Duplicate of #21833

**Closed by joaomoreno** 2017-03-20 12:00 UTC
Labels: bug
