### ISSUE TITLE
Problems have been highlighted

### ISSUE THREAD

**Issue by MrGoldSky** [microsoft/vscode#140660] opened 2022-01-13 19:07 UTC
Errors in the Errors(ПРОБЛЕМЫ) tab are now highlighted in orange.
![Screenshot_1](https://user-images.githubusercontent.com/68150241/149393488-51a71e3d-4fef-47d6-a7c0-f23efab6f433.png)

**Comment by sandy081** [comment] 2022-01-14 18:01
I don't see it. Do you have any special themes or color theme settings? 

Can you please try reproducing it using fresh user data dir, you can do this by starting VS Code from command line as follows:

`code --user-data-dir <folder_path>`

**Comment by MrGoldSky** [comment] 2022-01-14 19:00
[image: image.png][image: image.png]
I tried using code --user-data-dir <folder_path> in cmd and the problem
went away. I have a theme, but when I disabled it and restarted vs code
nothing changed. (first screenshot)
 How can I do something when the program starts normally, this problem is
gone? (second screenshot)

пт, 14 янв. 2022 г. в 21:01, Sandeep Somavarapu ***@***.***>:

**Comment by sandy081** [comment] 2022-01-17 20:52
> I tried using code --user-data-dir <folder_path> in cmd and the problem
went away.

This says the problem is with one of the extensions you have. You can follow [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to know which extension is causing this and file issue against that extension.

**Comment by MrGoldSky** [comment] 2022-01-18 13:23
> > I tried using code --user-data-dir <folder_path> in cmd and the problem
> > went away.
> 
> This says the problem is with one of the extensions you have. You can follow [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to know which extension is causing this and file issue against that extension.

I used bisect, it showed that the bug is in the Microsoft verified Python extension. When I uninstalled the extension, I didn't get any errors at all and I can't check if it's related to the extension or not.

**Comment by sandy081** [comment] 2022-01-19 10:45
Can you please not include Python extension in the bisect and check if other extension is causing it?

**Comment by MrGoldSky** [comment] 2022-01-19 10:50
> 

Without this extension, no errors are shown to me at all.

**Comment by sandy081** [comment] 2022-01-19 10:55
Right, hence I am asking to not to disable this extension and see if disabling another extension is not causing the highlights?

**Comment by MrGoldSky** [comment] 2022-01-19 11:05
> bisect

It didn't work. With Python extension enabled, there is always highlighting

**Comment by sandy081** [comment] 2022-01-19 18:40
Can you please try creating some problems using other languages, say for eg., write some invalid json or javascript files and check if you have the same issue?

**Comment by sandy081** [comment] 2022-01-22 16:30
Thats weird that turning errors filter on should not highlight text. Anyway since it is solved for you, closing this for now.

**Closed by sandy081** 2022-01-22 16:30 UTC
Labels: needs more info
