### ISSUE TITLE
Go To Definition does not Work on `import './index.css'`

### ISSUE THREAD

**Issue by joshglenn** [microsoft/vscode#90155] opened 2020-02-06 17:02 UTC
From what I understand, [issue 29899](https://github.com/microsoft/vscode/issues/29899#issue-239643470) solved this problem... except, for me it does not appear to be working. 

I just want to be able to right click and click "Go to definition" and open the css file, instead of having to dig through the folder tree to open it.

What do I need to do to get this working?

**Comment by octref** [comment] 2020-02-06 21:09
I assume you meant in a JS file, where you handle this import with webpack, is that correct?

**Comment by joshglenn** [comment] 2020-02-07 00:13
yes. inside a gatsby project is where I tried it initially. But then I created a new project from scratch and I included only an index.js file and an index.css file. I put the import statement in the index.js file and jump to definition won't work.

**Comment by mjbvz** [comment] 2020-02-07 00:36
Duplicate of https://github.com/microsoft/TypeScript/issues/15146

**Closed by mjbvz** 2020-02-07 00:36 UTC
Labels: needs more info
