### ISSUE TITLE
git fatal error: file is outside directory

### ISSUE THREAD

**Issue by feeva** [microsoft/vscode#100257] opened 2020-06-16 05:07 UTC
- VSCode Version: 1.46.0
- OS Version: Win 64 10.0.18363

Steps to Reproduce:

1. Edit a file and click "stage changes"

I found this same error was reported as "git fatal error: file is outside directory #88890" but I am experiencing it now. This is in the output view:

```
> git add -A -- e:\.....\include\top.jsp
fatal: e:\.....\include\top.jsp: 'e:\....\include\top.jsp' is outside repository
```
I can do it normally with git in terminal or Eclipse Git.

**Comment by gjsjohnmurray** [comment] 2020-06-16 05:35
/duplicate of #99881 and others (search for 'outside repository')

People have reported resolving this by updating their local Git.

**Closed** 2020-06-16 05:36 UTC
Labels: *duplicate

**Comment by feeva** [comment] 2020-06-16 07:35
So I upgraded to Git 2.27 as others did, it's ok now.

**Comment by joaomoreno** [comment] 2020-06-16 10:20
@feeva which git version did you have before, which caused the issues, do you still know?
