### ISSUE TITLE
VS code doesn't auto-complete classes and ids (already declared in html files) while coding in css files.

### ISSUE THREAD

**Issue by kmrmukesh1704** [Microsoft/vscode#49247] opened 2018-05-04 20:21 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment] 2018-05-07 08:46
duplicate of #28442

**Closed by aeschli** 2018-05-07 08:46 UTC
