### ISSUE TITLE
Pressing Ctrl+Shift+B when a task is already running should show terminate task button. This is a regression

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#12411] opened 2016-09-21 22:20 UTC
- VSCode Version: [Window Title]
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
Date 2016-09-12T13:30:03.456Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version:

Steps to Reproduce:

1. Start Task with Ctrl+Shift+B.
2. Press Ctrl+Shift+B. The notification bar shows info, no way to terminate task.

Before it had a "Terminate" Button allowing to stop the task. Now stopping is undiscoverable.

Before Ctrl+Shift+B could be used as start, stop and restart. It was a very useful shortcut.

**Comment by chrmarti** [comment] 2016-09-22 15:32
I still get the prompt:

![screen shot 2016-09-22 at 8 30 53 am](https://cloud.githubusercontent.com/assets/9205389/18754844/efc235c0-809e-11e6-8313-2d0262a8153b.png)

Could you paste the task definition you are using?

**Comment by nojvek** [comment] 2016-09-22 22:41
This is what I get

![image](https://cloud.githubusercontent.com/assets/1018196/18768549/dc003028-80da-11e6-967d-7db84e8c6c8b.png)

I'm pressing Ctrl+shift+b. No custom key bindings.

{ "key": "ctrl+shift+b",          "command": "workbench.action.tasks.build" },

**Comment by chrmarti** [comment] 2016-09-23 18:14
Could you paste your tasks.json?

**Comment by nojvek** [comment] 2016-09-23 18:33
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "watch",
            "args": [],
            "isBuildCommand": true,
            "isWatching": true,
            "problemMatcher": {
                "owner": "f12",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^.*?] (.*?\\.ts)\\((\\d+|\\d+,\\d+)\\):
(error|warning|info) (TS\\w+): (.*)$",
                    "file": 1,
                    "location": 2,
                    "severity": 3,
                    "code": 4,
                    "message": 5
                },
                "watching": {
                    "activeOnStart": true,
                    "beginsPattern":  "File change detected",
                    "endsPattern": "Compilation complete"
                }
            }
        }
    ]
}
```

**Comment by chrmarti** [comment] 2016-09-23 21:53
That's the expected behavior when the task is 'watching'. You should get the other behavior when setting isWatching to false. It would seem to make sense to offer to terminate a watching task just like any other task. Will mark as feature request.

**Comment by nojvek** [comment] 2016-09-23 22:19
However isWatching used to give terminate task button. After doing an
upgrade it gives an info box.

**Comment by dbaeumer** [comment] 2016-09-26 07:18
@nojvek we changed the behavior since a lot of people started a 'watching' task twice and needed to dismiss the dialog. Since there is a Terminate Task action we decided to 'ignore' the start task action when a task is already running and in watching mode and show an auto closing message. So no need to press Escape or the Close button. I understand that the 'Terminating' is now more work but it is the less wanted action for most people when pressing Ctrl+Shift+B. They just want to keep the current task running.

If you need to terminate task quite frequently then I suggest you bind a keyboard shortcut to the action.

No further action planned.

**Closed by dbaeumer** 2016-09-26 07:18 UTC
Labels: feature-request, tasks

**Comment by nojvek** [comment] 2016-09-26 15:29
But what was wrong with previous functionality? If watching task is already
on, the info message should offer an option to terminate like it did
before.

I'm arguing that you're making the user experience worse. Also there is no
default key binding for terminate task like there is for starting a task.

The user experience of tasks is worse than what it was before. I'm happy to
make a fix if you point me to the right direction.

Also please don't just close the issue, this may feel minor to you, but
someone who uses watching tasks all day, it's a major annoyance not being
able to terminate a task with a single click.

I know I can add a custom command but I work with multiple machines, some
of which are newly created VMs and having a default terminate functionality
means a lot.

**Comment by dbaeumer** [comment] 2016-09-27 09:40
@nojvek it is very hard to make all people happy :-). We still try our best to make this a pleasant experience and I kept quite some items open around this for October. They are:

https://github.com/Microsoft/vscode/issues/6578
https://github.com/Microsoft/vscode/issues/6550
https://github.com/Microsoft/vscode/issues/7236
https://github.com/Microsoft/vscode/issues/12065

Overall I am not happy with how things work right now. So right now I lean towards a status bar item with some sort of actions plus a way to let people define in the tasks.json file what happens if the task is requested to run again. See https://github.com/Microsoft/vscode/issues/6578#issuecomment-229645715

I closed this one since I don't want to restore the old behavior. However I should have pointed you to https://github.com/Microsoft/vscode/issues/6578#issuecomment-229645715. Will this address your concern.

**Comment by nojvek** [comment] 2016-09-27 16:22
I still don't understand what was wrong with previous functionality. 

Is there something I can add to my current tasks.json to restore old functionality?

**Comment by dbaeumer** [comment] 2016-09-27 18:19
People complained that if they pressed Ctrl+Shift+B a second time for a watching task they saw a dialog which they add to dismiss with Close or Escape. They told me that in 99% of the cases they didn't remember that they had the task already started and for watching task it shouldn't make a difference anyways. That resonated with me. So I changed it in a way that a message is still shown but the message out closes (no need to press Escape or Close). But I see your use case as well.

Currently there is no way to configure this #6578 is about this.

**Comment by akoskm** [comment] 2016-09-30 10:34
> I still don't understand what was wrong with previous functionality.

Neither I do. I might miss something but I think that @nojvek is OK with having the current info dialog present but would also add a terminate button:

![dc003028-80da-11e6-967d-7db84e8c6c8b](https://cloud.githubusercontent.com/assets/3111627/18988943/6d302dbc-8709-11e6-96f9-661991cef4e2.png)

> People complained that if they pressed Ctrl+Shift+B a second time for a watching task they saw a dialog which they add to dismiss with Close or Escape.

So the behavior people were complaining about wouldn't return, only a button would be added to the current dialog.

Does it make sense?

**Comment by dbaeumer** [comment] 2016-10-03 08:53
It would return since your guideline is right now that message which have a second action can't be auto closed. So those people you simply want to keep the current task running needed to press close or escape. With the new implementation the don't need to do anything. 

I think that people in more cases press Ctrl+Shift+B to start a task and then recognize that it is already running than using Ctrl+Shift+B to terminate a task.

**Comment by akoskm** [comment] 2016-10-03 09:19
Thanks @dbaeumer for pointing this out:

> It would return since our guideline is right now that message which have a second action can't be auto closed. So those people you simply want to keep the current task running needed to press close or escape. With the new implementation they don't need to do anything.

I didn't know about the guideline, it definitely makes sense, however:

> So those people you simply want to keep the current task running needed to press close or escape. 

This is _a lot_ easier compared to what a user who wants to terminate the task has to do:

`Ctrl + Shift + P > type terminate correctly  > Enter`

I'm totally :+1: for respecting the guidelines, but the way this has been fixed made things much harder to a certain group of users.

**Comment by dbaeumer** [comment] 2016-10-03 09:23
You can easily bind a keybinding to the terminate action if it is an action you need quite frequently. Since key bindings are very controversial as well I didn't bind one by default :-) (File >Preferences > Keyboard Shortcuts). I for example have bound an action.

**Comment by akoskm** [comment] 2016-10-03 09:48
Thanks @dbaeumer! For future reference, here's the binding which terminates the task if you press `Ctrl+T`:

```
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+t",
        "command": "workbench.action.tasks.terminate"
    }
]
```
