### ISSUE TITLE
Diff view shows output changes even when there is no actual change (only change is in the metadata)

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#141966] opened 2022-01-31 21:47 UTC
## Environment data

-   VS Code version: 1.64.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001760686
-   Python Extension version (available under the Extensions sidebar): v2022.0.1762517795-dev
-   OS (Windows | Mac | Linux distro) and version: Windows (WSL2)
-   Python and/or Anaconda version: conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

1. Open an existing notebook
2. Run the first cell
3. Run all cells (so that the first cell's execution count becomes "2")
4. Open diff view
5. Assuming that no changes were made to the notebook / data, there shouldn't be any diffs displayed

## Actual behaviour

Output is exactly the same, but is marked as "changed"
![image](https://user-images.githubusercontent.com/10833267/151878286-d0ac5e10-2fed-4960-8762-a3a09d44ed5c.png)

Because the "executionCount" changed in the output metadata
![image](https://user-images.githubusercontent.com/10833267/151878304-13291b97-284d-4647-b326-904de2ff96d8.png)

**Comment by greazer** [comment] 2022-02-04 01:47
@rebornix, I believe we've had a similar bug in the past. However, I think the main gist of this one isn't that a diff is displayed at all, but rather the diff is shown as being a diff of the output of the cell. Or maybe this is identical to the other. 

In any event, @minsa110, note that in your screenshot there's a sentence that says "Output metadata has changed". That should be a key that the output itself may not have changed. Does this change your assessment?

IMO, I think the minimum ideal behavior here would be to be able to not highlight the actual output, but rather whatever represents the metadata. In this case, it would be the line with the "> Output" heading only.

**Comment by greazer** [comment] 2022-02-04 01:59
Dupe of #135820.

**Closed by greazer** 2022-02-04 01:59 UTC
Labels: bug, notebook-diff, nb-golden, notebook-triage
