### ISSUE TITLE
After upgrading insiders build from 1.26.0-insider to 1.27.0-insider our DA is not sending events to our extension

### ISSUE THREAD

**Issue by JimSuplizio** [Microsoft/vscode#57641] opened 2018-08-30 21:43 UTC
After upgrading to the 1.27.0-insider build from the 1.26.0-insider our Debug Adapter we're receiving the initializeRequest event and in that even we're sending a custom event to our extension, which has an event handler for onDidReceiveDebugSessionCustomEvent registered, but the event is never received. I tracked the sendEvent to the point where it gets written to the writableStream in protocol.ts and everything looks fine. On the extension side I was broken in rpcProtocol.ts and the only events that came in were onDidChangeWindowFocus events that were happening due to me swapping VS Code instances (I'm debugging the DA and Extension in one VS Code instance and the actual project in the other).

After uninstalling 1.27.0-insider and re-installing 1.26.0-insider things were working just fine.

Our debug adapter's initializeRequest method is here:
https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts#L220

Our extension's onDidReceiveDebugSessionCustomEvent handler is setup here:
https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts#L145

- VSCode Version: 1.27.0-insider
- OS Version: Linux: Ubuntu 14.04 Architecture x64 and Mac OSX 10.13.6 (windows wasn't tried)

Steps to Reproduce:
I'm kind of hoping you guys recognize what's going on or can give me some tips on trying to diagnose this further as there's no good way to trim down the DA and the extension code for a small repro. I can also setup a goto meeting or hangout to walk someone through it. 

1. git clone https://github.com/forcedotcom/salesforcedx-vscode  - pull down the repository, run npm install. In an VS Code instance (1.27.0-insider) open up the salesforcedx-vscode, select **Launch Replay Debugger adapter** which will build everything and launch the debugger adapter. 
2. After launching the Replay Debugger adapter select *Launch Extensions without compile*, this will launch another instance of VS Code which we'll be loading the project.
3. git clone https://github.com/dreamhouseapp/dreamhouse-sfdx - Using the instance of VS Code opened up in step 2, open up the dreamhouse-sfdx directory.
4. In the project select add configuration and select Apex Replay Debugger: Launch. In that configuration add the "debugServer": 4712 after the "trace": true entry. This allows debugging of both the extension and debug adapter locally. 
5. Launch Apex Replay Debugger - you'll get prompted to select a log file however any .txt will do since it'll hang before it even gets to the point where it does anything with.
Putting breakpoints in apexReplayDebug.ts#L220 and index.ts#L145 you can see the event get sent by the DA and never get it by the extension. The VS Code that launched the replay debugger will continue to spin and never start responding. It'll have to be killed. In order to start things again you're going to have to run *kill -9 $(lsof -t -i :4712)* because it's still listening on the port and run steps 2 and 5 again.

**Comment by weinand** [comment] 2018-08-31 09:19
@egamma we are planning to fix this regression fro the August release. It was introduced by the refactoring necessary for the EH debugging fix and it was not discovered in the test pass (#56822).

**Comment by egamma** [comment] 2018-08-31 10:14
OK to fix 👍

**Comment by isidorn** [comment] 2018-08-31 10:32
@JimSuplizio thanks a lot for filling this and for using insiders.

**Comment by weinand** [comment] 2018-08-31 11:02
@JimSuplizio yes, thanks a lot for testing your extension with Insiders and reporting any regressions you find.
And the earlier you test and report, the better ;-)

**Comment by JimSuplizio** [comment] 2018-08-31 14:00
@weinand, @isidorn and @egamma thank you all for looking at this. I use insiders whenever possible, especially while doing development with the exception being if there's something blocking, So far, this been one of the only issues I've hit in the past 8 months. Everyone working on VS Code has done a great job with the product and I've been more than happy with the quality of VS Code.

**Comment by weinand** [comment] 2018-08-31 14:17
Does the fix work for you?

**Comment by isidorn** [comment] 2018-08-31 14:18
The current insiders build has the fix (update came out a couple of hours ago).

**Comment by JimSuplizio** [comment] 2018-08-31 15:00
@weinand 
I just installed this version and it still hangs. Is this the version with the fix in?
Version: 1.27.0-insider
Commit: 1097b5e9ed81d5f9241648774b35048be168c203
Date: 2018-08-31T10:41:42.550Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by weinand** [comment] 2018-08-31 16:16
@JimSuplizio yes, you are using the correct version.

We could not get your debugger to work because we couldn't build it successfully.
So we tried to reproduce your problem with our example debugger "mock-debug" by making these changes:

https://github.com/Microsoft/vscode-mock-debug/commit/16ab549f99662c4b074e37f492a759fb2399ac54 

So basically we register for custom events on activate and we send the custom event from the "initialize" request before returning the "initialize" response. These changes were based on the two source code links that you had in your original comment.

We could reproduce the problem the Insider release from yesterday and our fix solved the problem for us.

Please note that you are living a bit on the edge by sending custom events that early.

For VS Code a debug session starts after it has received a successful "initialize" response. 
From then on it is possible to receive custom events. 
Your implementation seems to send custom events **before** the "initialize" response. 
You were lucky that this worked previously, and for a refactoring that we had to do, this code had been cleaned up and we were only accepting custom events after the a successful "initialize" response.

Since we did not expect that any DA implementation would rely on that behaviour, we wasn't aware that this change was a breaking change.

For this reason we've decided to revert the new behaviour and accept custom events "early" again.

If our change doesn't work for you, then there must be another timing-related thing that your code is relying on.

One thing that looked suspicious to me is the fact that you delay the "initialize" response until you receive a customRequest from the custom event handler...

I've just tried to add this to my mock-debug branch (see https://github.com/Microsoft/vscode-mock-debug/commit/e73a8653171626831ff3139c8cc3faae4a2793c6) and this in fact shows the next problem: the custom request again comes too early and is ignored because the session has not yet been initialized.

/cc @isidorn

**Comment by JimSuplizio** [comment] 2018-08-31 17:07
@weinand First, I'd like to acknowledge the effort you've put into assisting me with this. I thank you, it is very much appreciated. I'm probably still going to need some of your expertise to fix this on our end then.

I'm not 100% sure what the correct ordering of events needs to be here. What's going on with our code is that we'd fail initialization if we weren't able to get the source/line information for breakpoints from our language server. This had seemed like the correct thing to do since we didn't want to start the session if we couldn't get the source/line breakpoint information. If initialization has to complete before any custom events can be sent then I guess the follow apply:
1. Where's the next, best, earliest place to fire that event? We really can't do anything unless the call to our language server is successful.
2. If the session is initialized and we figure out where to move the the breakpoint information call, what's the best way to un-initialize or stop the session?

Thanks,
Jim

**Comment by weinand** [comment] 2018-08-31 21:40
Another approach is to run the DA inside your Debugger extension. In this case the DA can directly access the vscode API to fetch data from your language extension and you do not have to "tunnel" the info from the extension to the DA.
The mock-debugger has a simple [flag](https://github.com/Microsoft/vscode-mock-debug/blob/8da8a32a80a151acd7910bf04190d12f0f04a6cd/src/extension.ts#L17) to enable this mode.
And the few lines of code that implement this approach are [here](https://github.com/Microsoft/vscode-mock-debug/blob/8da8a32a80a151acd7910bf04190d12f0f04a6cd/src/extension.ts#L66-L80).

**Comment by weinand** [comment] 2018-08-31 21:43
Another approach merges the Language Server and the Debug Adapter into one server that serves both protocols at the same time. Here the DA has easy access to Language Server info.
The Java Debugger extension uses this approach because the language server and debugger are basically one component.

**Comment by weinand** [comment] 2018-08-31 23:35
@JimSuplizio it would be great if you could that your debugger extension works with this Insiders build (that contains the fix #57716): https://az764295.vo.msecnd.net/insider/812fe77b89d6dbd6197e0bc258fdb5f937411655/VSCode-darwin-insider.zip
You don't have to uninstall anything. Just unzip the download into another folder and make sure that the official Insiders is not running when starting the new Insiders with the fix.

**Comment by JimSuplizio** [comment] 2018-09-02 18:57
@weinand, my apologies, I had to leave early on Friday. I'd need a Linux build to test your changes.
What I'm about to try to is exactly what you'd described which is to move the code that gets the source/line information into the resolveDebugConfiguration method and send it over as an argument. The resolveDebugConfiguration already has an argument (the logfile) that's checked inside of the DA's launchArguments. I figure that the line breakpoint info, if passed over as an argument, can be verified there and error out in a similar manner if there's a problem. This should simply alleviate the message ping pong during the initialize. I'll post something shortly with my findings there.

**Comment by weinand** [comment] 2018-09-02 21:06
I've started a linux 64 build

**Comment by weinand** [comment] 2018-09-02 21:44
@JimSuplizio here is the linux build in three archive formats:
https://az764295.vo.msecnd.net/insider/812fe77b89d6dbd6197e0bc258fdb5f937411655/code-insider-1535923719.tar.gz
https://az764295.vo.msecnd.net/insider/812fe77b89d6dbd6197e0bc258fdb5f937411655/code-insiders_1.27.0-1535923767_amd64.deb
https://az764295.vo.msecnd.net/insider/812fe77b89d6dbd6197e0bc258fdb5f937411655/code-insiders-1.27.0-1535923957.el7.x86_64.rpm

**Comment by JimSuplizio** [comment] 2018-09-02 22:09
The .deb file format works. I just pulled it and I'll let you know in a few minutes what happens.

**Comment by JimSuplizio** [comment] 2018-09-02 23:59
@weinand My apologies for the delay. After installing your fix things work as they used to which is to say that we receive the event that's fired from inside of the initializeRequest. Will this be able to get into a code-insiders build as well as the code release that's scheduled for this week?

I thank you for doing this and I do plan on trying to remove this interaction from our code in the very near future. Your change will give us some breathing room to do this.

You'll have to pardon my previous bit of clueless but I did have to play around a bit to see what you were talking about with your suggestion of moving things into the resolveDebugConfiguration. I'm less familiar with that than I am with other areas of the DA/Extension code. I didn't realize that just adding that to the DebugConfiguration would allow automatically add it to the args passed into the launchRequest (this is partially because our own LaunchRequestArguments class limit what we see).

The problem I believe that I'm going to run into with trying to fetch the source/line information, the way you'd suggested above with your resolveDebugConfiguration implementation is that that call to get the line breakpoint information "const lineBpInfo = await sfdxApex.exports.getLineBreakpointInfo();" is an async call. Unless I'm mistaken, I don't believe I can make that resolveDebugConfiguration function async due to the return type.

**Comment by weinand** [comment] 2018-09-03 06:35
@JimSuplizio thanks for verifying that my fix makes VS Code work again with your debugger. The plan is to include that fix in the next Insiders and the upcoming stable version.

--

The `DebugConfigurationProvider.resolveDebugConfiguration` method returns an "ProviderResult" which indicates that it is async. That means you can just either return a Promise or you can add "async" to your `resolveDebugConfiguration` declaration if you want to use "await" in its body.

All provider APIs are async by definition because they run in a different process anyway.

**Comment by bpasero** [comment] 2018-09-03 09:33
@weinand can we close this one and verify?

**Closed** 2018-09-03 09:48 UTC
Labels: bug, candidate, debug, insiders

**Comment by weinand** [comment] 2018-09-03 09:55
@JimSuplizio verified my fix already in a private build. 
I've verified again that my simulation of the issue is fixed in Insiders.
Adding verification label.

**Comment by weinand** [comment] 2018-09-03 09:57
@JimSuplizio the fix is now in Insiders.
Could you please verify again that your debugger works in Insider.
Thanks.

**Comment by JimSuplizio** [comment] 2018-09-03 16:54
@weinand I've installed the latest insiders, here's (version information below) and things worked just fine. Just to confirm, this fix will also be in the code build released this week as well?

This build information from the installed insiders build, just to confirm
Version: 1.27.0-insider
Commit: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Date: 2018-09-03T09:15:27.927Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Am I correct in running under the assumption that this particular fix is temporary and is code you guys would ultimately like to remove? I've every intention of fixing this on our end within the next week or two (I'm in the middle of a feature that has a more immediate deadline).

As for the resolveDebugConfiguration, you are correct, I'd gotten tangled in the return value vscode.ProviderResult<vscode.DebugConfiguration> which just had to be changed to Promise<vscode.DebugConfiguration>. Sometimes leaving and coming back to code with fresh eyes is a good thing.

**Comment by weinand** [comment] 2018-09-03 19:14
@JimSuplizio thanks for verifying (again).

Yes, this Insider will be promoted to Stable this week.

**Comment by JimSuplizio** [comment] 2018-09-03 19:44
@weinand that's great news. Again, thanks for doing this, especially over a holiday weekend.

**Comment by weinand** [comment] 2018-09-03 20:06
@JimSuplizio no holiday weekend here in Switzerland... :-(

BTW, since we do not want to break extensions, we are not planning to remove the fix on our side any time soon. But I still recommend that you change the code on your side a bit to make it simpler and less likely to fail when we again refactor something on our side.

**Comment by JimSuplizio** [comment] 2018-09-04 18:58
@weinand that's the plan. We'd like to prevent fire drills like this in the future. If you're ever in Redmond, I'm just over in Bellevue, drinks are on me.
