### ISSUE TITLE
Extension viewlet breaks

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38817] opened 2017-11-20 20:39 UTC
1. Search for `a`
2. Scroll a few pages down

![image](https://user-images.githubusercontent.com/22350/33040407-4516cbae-ce3b-11e7-9378-430915c5a101.png)

**Comment by sandy081** [comment] 2017-11-21 08:35
Duplicate of #38357

**Closed** 2017-11-21 08:35 UTC
Labels: *duplicate, bug, important
