### ISSUE TITLE
Terminal: sometimes the top of the terminal is cropped

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17538] opened 2016-12-19 13:51 UTC
I am sometimes seeing the prompt being scrolled to the top. I just saw this on Linux but also seen this on macOS:

![image](https://cloud.githubusercontent.com/assets/900690/21315047/8d0c0400-c5fa-11e6-93d9-992fe82b235d.png)

**Comment by thekalinga** [comment] 2016-12-19 16:34
I have faced this issue with default settings in my Ubuntu 14.04 aswell

**Comment by bpasero** [comment] 2016-12-19 19:16
Btw I am using VS Code with a zoom level of 1, not sure if that is related.

**Comment by Tyriar** [comment] 2017-01-03 17:55
Yes it's to do with zoom, duplicate of https://github.com/Microsoft/vscode/issues/14479

**Closed by Tyriar** 2017-01-03 17:55 UTC
Labels: bug, integrated-terminal
