### ISSUE TITLE
Dragging files and other draggable items causes complete lock on linux

### ISSUE THREAD

**Issue by chrisdruta** [microsoft/vscode#57766] opened 2018-09-02 03:59 UTC
- VSCode Version: 1.26.1, 493869ee8e8a846b0855873886fc79d480d342de, x64
- OS Version: Arch Linux (kernel: 4.18.5-arch1-1-ARCH)

I've been encountering quiet a weird bug for a couple of weeks now. As per the title, this bug occurs when I drag draggable items and let go of them. This could be me moving files, highlighting and moving text within a file, etc...

Steps to Reproduce:
1. Open Code
2. Open workspace file
3. Move a file from the explorer to a subfolder in the same directory

The whole application is now frozen (at least visually) and behaves extremely strange with my window manager/ compositor (i3-gaps). I cannot force quit, and have to sigkill the process in htop or something.

Now time for the strange part - there are two binaries I get of vscode from this package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code-bin

One in `/opt/visual-studio-code/code`, and another in `/opt/visual-studio-code/bin/code`. The `/opt/visual-studio-code/code` has this bug. The one in  `/opt/visual-studio-code/bin/code` does not. This is a problem because the default FreeDesktopOrg desktop file for code points to the first, which has the bug.

Note about the bug:
On the bug-free binary, when dragging the file, the whole destination sub-folder is highlighted before release, while on the bugged binary it doesn't highlight (and the tool tip breaks, and on release, everything breaks)

I have temporarily fixed the issue by pointing my desktop file for code to `/usr/bin/code` (which I think is the one in `/opt/visual-studio-code/bin/`) instead. If you guys think this is an issue more specific to my linux distribution/ package, I let the package maintainer know about this as well.

The fact that the process doesn't response (at least the frontend) and behaves strangely with my wm/compositor leads me to believe that the problem is more so on the rendering side. Some possibly related verbose log messages:

```[17409:0901/193844.207598:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.```

```[17409:0901/193856.377488:ERROR:buffer_manager.cc(453)] [.DisplayCompositor-0x231466a4a400]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-09-03 07:57
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by chrisdruta** [comment] 2018-09-04 23:56
Nope, same exact bug, down to the difference behavior between the binary in the root folder vs the bin folder. What exactly is the difference between the two? They both seem to be the same version (at least by commit)

**Comment by bpasero** [comment] 2018-09-05 04:32
Does it reproduce if you run `code --disable-gpu` from the command line?

**Comment by chrisdruta** [comment] 2018-09-05 04:47
Yes! That seems to have fixed it. Might be something with electron and the linux mesa display drivers. Thanks for the help :)

**Comment by jgsqware** [comment] 2018-09-18 12:40
Still experiencing the same currently on same version.

**Comment by bpasero** [comment] 2018-09-18 13:29
If someone has ideas, help is welcome. I can also reproduce but I have no idea what could trigger this.

**Comment by bpasero** [comment] 2018-09-18 13:30
Actually this seems to be: https://github.com/electron/electron/issues/12820

**Comment by KevinGrant12** [comment] 2019-05-29 02:24
I still have this issue.

**Comment by deepak1556** [comment] 2022-12-12 11:07
Closing as it is resolved in upstream since Electron 11.

**Closed by deepak1556** 2022-12-12 11:07 UTC
Labels: help wanted, upstream, electron, gpu, upstream-issue-linked
