### ISSUE TITLE
when run not restore zen mode if it was enabled in previous run

### ISSUE THREAD

**Issue by deemetrius** [microsoft/vscode#142570] opened 2022-02-08 23:43 UTC
Issue Type: <b>Bug</b>

version 1.64.1 not restores zen mode on start
version 1.63.2 restores zen mode
So why it changed? Please fix back.

or: I need a way to hide tabs line from ui. Then zen mode is not necessary

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.52GB free)|
|Process Argv|--crash-reporter-id 30f4f83a-c290-4fa8-a964-af8b69e10949|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
better-cpp-syntax|jef|1.15.11
php-symbols|lin|2.1.0
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2022-02-08 23:55
> or: I need a way to hide tabs line from ui. Then zen mode is not necessary

`"workbench.editor.showTabs": false`

**Comment by JacksonKearl** [comment] 2022-02-09 00:50
@sbatten could this be from layout changes?

**Comment by sbatten** [comment] 2022-02-09 01:44
@JacksonKearl yes probably

**Comment by JacksonKearl** [comment] 2022-02-09 02:12
Looks like @deemetrius's issue is solved by `"workbench.editor.showTabs": false`, we can close this out or leave it open if you want to track zen restore. (I confirmed it is a regression)

**Comment by deemetrius** [comment] 2022-02-09 09:38
> Looks like @deemetrius's issue is solved by `"workbench.editor.showTabs": false`, we can close this out or leave it open if you want to track zen restore. (I confirmed it is a regression)

In case Zen mode is used by someone - I think it should be restored in next run.

Currently I'm fine with workbench.editor.showTabs setting.

**Comment by amatiasq** [comment] 2022-02-24 14:10
Came here to report this bug. Has been failing for a few versions now (didn't check but since 1.64.1 sounds reasonable).

Can someone point to what the layout changes are? maybe I can provide a PR.

**Closed** 2022-02-24 17:35 UTC
Labels: bug, layout, workbench-zen
