### ISSUE TITLE
Show zoom scale indicator in status bar

### ISSUE THREAD

**Issue by qasims** [Microsoft/vscode#14602] opened 2016-10-27 15:01 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by weinand** [comment] 2016-10-27 21:05
@qasims please do not combine multiple requests in one issue. I've removed the second request.

**Comment by mjbvz** [comment] 2017-11-03 23:16
Duplicate of #12318

**Closed by mjbvz** 2017-11-03 23:16 UTC
Labels: duplicate, feature-request, workbench
