### ISSUE TITLE
Region suggestions are not shown when typing region

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35078] opened 2017-09-26 10:53 UTC
Testing #34989

- Type `//`
- Trigger intelli-sense
- Type `reg`

You do not see proposals for regions

![kapture 2017-09-26 at 12 52 09](https://user-images.githubusercontent.com/10746682/30856778-b375c4d6-a2b9-11e7-9c3f-312222747e9a.gif)

**Comment by aeschli** [comment] 2017-09-28 14:02
'#region' and '#endregion'  are snippets and the filtering is likely done in the snippet provider. I think we insist on a prefix match in order to avoid too many snippets to clutter the suggestion window. @jrieken knows it all.
But I personally think the current behaviour is ok. '#region' and '#endregion' are not the most important thing in the word, and I would hate to have them show up all the time. Ideally, I could annotate that  '#region' and '#endregion' should only show at the beginning of a line (incl. whitespace).

**Comment by jrieken** [comment] 2017-09-28 14:36
>  I think we insist on a prefix match in order to avoid too many snippets to clutter the suggestion window.

No, all are equal these days. @sandy081 Do you have snippet suggestions enabled?

**Comment by jrieken** [comment] 2017-09-28 14:57
Problem is that we use the `prefix` of a snippet and that the prefix is `#region`. That prefix doesn't match `// reg` nor `reg` (line until, word until). Not sure what to do, it's kind of the design of snippets to match on prefix and not the inserts text. 

<img width="322" alt="screen shot 2017-09-28 at 16 53 55" src="https://user-images.githubusercontent.com/1794099/30973584-c35ca7d8-a46d-11e7-85f3-491e4e41342d.png">

**Comment by jrieken** [comment] 2017-09-28 14:59
@aeschli You should maybe consider changing your snippets

**Comment by aeschli** [comment] 2017-09-28 15:39
As said, I like that that the region/endregion proposals only show with prefix '#'. They should only show when wanted, and not clutter the suggestions. Sure the user has to learn about it, but I think that's acceptable.

I suggest to close as designed.

**Comment by jrieken** [comment] 2017-09-28 15:52
Fair enough, tho I would change the insert text to `#region $0` because a user might type `// #`, sees the snippets, and ends up with a double comment

**Comment by sandy081** [comment] 2017-09-28 15:54
>>No, all are equal these days. @sandy081 Do you have snippet suggestions enabled?

**Comment by jrieken** [comment] 2017-09-28 15:58
@aeschli Moving back to you to consider changing the snippet or closing this

**Closed** 2017-09-29 07:04 UTC
Labels: snippets, suggest, under-discussion
