### ISSUE TITLE
Extension host crashes leaving VSCode in inconsistent state

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#86723] opened 2019-12-11 08:14 UTC
Issue Type: <b>Bug</b>

I have noticed last week or so that if I have some TypeScript compilation error (something that happens very often - essentially can happen after every keystroke) VSCode eventually starts eating RAM (more than 3.5-4GB) and uses 100% CPU.  This finishes either with VSCode in an inconsistent state (TypeScript service stops working and you don't have code completion in VSCode anymore) or VSCode stops responding - in both cases it must be restarted. Several updates happened since I noticed this for the first time. Today it happened again. This is a screenshot of developer tools (after VSCode showed me notification that "Extension host stopped working"):

![image](https://user-images.githubusercontent.com/7610713/70603237-c04aeb80-1bfe-11ea-9ee7-5911c83ad6d6.png)

After restart it could happen again until the rest of the day but not always reproducable.

VS Code version: Code - Insiders 1.41.0-insider (455d8f73cd7c73285fba70ab039a26279f19bb57, 2019-12-10T12:59:54.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.88GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/azavista/azavista3.0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-icons|vsc|9.6.0

</details>

**Comment by darkpoetcc** [comment] 2019-12-11 16:49
On my system, it gobbled up over ~24 GB RAM before crashing.  It seems it will run away and use as much RAM as it finds free, which could be a problem for OS stability (at least in Windows).

![image](https://user-images.githubusercontent.com/6785272/70641757-18d4b580-1c0c-11ea-96a5-4942119ac665.png)

**Comment by darkpoetcc** [comment] 2019-12-11 17:12
@varadero -- I noticed you are using Angular, as am I.  I noticed this updated only 5 days back, and now I am having a bunch of issues.  I am going to try disabling the Angular Lang Service and see if normal typescript projects are problematic.

**Comment by darkpoetcc** [comment] 2019-12-11 17:35
> @varadero -- I noticed you are using Angular, as am I. I noticed this updated only 5 days back, and now I am having a bunch of issues. I am going to try disabling the Angular Lang Service and see if normal typescript projects are problematic.
> 
> ![image](https://user-images.githubusercontent.com/6785272/70644056-3c99fa80-1c10-11ea-913a-ef77e11fb79e.png)

So, after some testing, I disabled my Angular extensions, and can write generic TypeScript files without any problems.  Whereas I was getting an error every 1-5 lines in an Angular project, that same project with only a TypeScript file is working just fine.

I will continue digging, in case it can save some time for the devs, but I am already seeing more stability in 55 lines of generic TypeScript than I was in a single bit of Angular (~10 lines between 5 crashes).

**Comment by mjbvz** [comment] 2019-12-11 19:02
@varadero Does this happen when you disable the angular extension? What if you disable tslint as well?

**Comment by varadero** [comment] 2019-12-11 22:19
@mjbvz I will test now but I am already with slightly new VSCode version (2019-12-10T21:44:16.632Z) compared to these that crashed (including and prior to 2019-12-10T12:59:54.138Z). My new version:

Version: 1.41.0-insider (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-10T21:44:16.632Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by darkpoetcc** [comment] 2019-12-11 22:32
> @varadero Does this happen when you disable the angular extension? What if you disable tslint as well?

@mjbvz I noticed later today that it crashes slower, but still crashes, when disabling the Angular extension.  Disabling TSLint altogether, however, has led to no crashes at all the rest of the day.

**Comment by varadero** [comment] 2019-12-12 09:45
I can confirm that I disabled TSLint extension (leaving Angular Language Service and vscode-icons enabled) for one of my workspaces and was able to work a couple of hours without any problems despite that I got a pile of TypeScript compilation errors while I changed my code. I have another VSCode instance (running at the same time as the first VSCode instance) opened with another workspaces which has TSLint extension enabled (and vscode-icons also but not Angular Language Service) and this workspace (much simpler than the first one) just crashed after about 10 minutes of work because of high memory usage. I have restarted the crashed VSCode an will continue to work with it but probably @darkpoetcc observation about TSLint extension being the reason for crashes has very high probability to me.

**Comment by varadero** [comment] 2019-12-13 08:52
I still have problems with only two plug ins started - TSLint and vs-icons.
The process that consumes so much memory and crashes is started with the following parameters:

C:\Users\Svincho\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --max-old-space-size=3072 "c:\Users\Svincho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\Svincho\AppData\Local\Temp\vscode-typescript\ac186885606f47fe1349\tscancellation-2527f77cff46481fe48d.tmp* --globalPlugins typescript-tslint-plugin --pluginProbeLocations C:\Users\Svincho\.vscode-insiders\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.2.3 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation	Disabled

**Comment by darkpoetcc** [comment] 2019-12-13 15:42
Just a report back; I had no crashes at all yesterday with only the TSLint extension disabled; my working day was ~9 hours.

![image](https://user-images.githubusercontent.com/6785272/70812212-2ff2df00-1d95-11ea-9fe6-ca454782bbb7.png)

**Comment by mjbvz** [comment] 2019-12-16 23:09
@varadero Can you check to see if disabling the tslint plugin fixes this for you?

**Comment by varadero** [comment] 2019-12-18 07:06
@mjbvz I am working with TSLint extension turned off for two of my workspaces and I don't have the crashes anymore. I have it enabled for another workspace and it crashes more than once a day.

**Comment by mjbvz** [comment] 2019-12-18 19:29
Duplicate of #86707

**Closed by mjbvz** 2019-12-18 19:29 UTC
Labels: needs more info
