### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2892] opened 2016-02-10 15:13 UTC
Issue Id: <b>5ff55400-6d9e-cf2f-f43a-b414cfe1e50b</b><br /><br />*Versions* <br />- 043a4e760131b3bedc328b748a604494240ed0e5<br />-  6c2d51a4b7b81753a3a4c46f9de9a15179e20304<br />-  a5a983da6c98263aa603c2ca27b1a7297c7d9e1f<br />-  b0b6af5754c6cae2574a540a0eb4f5ebfceec1ed<br />*Stack* <br />TypeError: Cannot read property 'className' of null<br />[/vs/base/browser/dom.ts#L65:20 (_findClassName)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/browser/dom.ts#L65:20 (_findClassName))<br />[/vs/base/browser/dom.ts#L172:1 (toggleClass)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/browser/dom.ts#L172:1 (toggleClass))<br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L650:2 (SuggestWidget.setState)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L650:2 (SuggestWidget.setState))<br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L576:9 (SuggestWidget.onEditorBlur)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L576:9 (SuggestWidget.onEditorBlur))<br />[/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1448:0 (call)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/common/winjs.base.raw.js#L1448:0 (call))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/043a4e760131b3bedc328b748a604494240ed0e5/src/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />

**Comment by joaomoreno** [comment] 2016-02-24 15:45
Duplicate of #3133

**Closed by joaomoreno** 2016-02-24 15:45 UTC
Labels: error-telemetry
