### ISSUE TITLE
Include Only a number of folders inside a solution

### ISSUE THREAD

**Issue by eyeris** [Microsoft/vscode#30921] opened 2017-07-18 10:18 UTC
vscode currently support only including folders inside a solution.
```
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true

}
```
However, its very useful to add` include` option to add only a selected/filtered list of directories to the solution.

**Comment by isidorn** [comment] 2017-07-18 12:53
I think this is a duplicate of multi root folder work we are currently working on

**Closed by isidorn** 2017-07-18 12:53 UTC
