### ISSUE TITLE
Oh My Posh not rendered properly in terminal

### ISSUE THREAD

**Issue by tinkeringtuck** [microsoft/vscode#191478] opened 2023-08-28 16:22 UTC
Type: <b>Bug</b>

Oh my posh is rendered properly in windows terminal using command prompt or PowerShell terminal. However, in VS code neither command prompt nor PowerShell will properly render oh my posh. 

Unexpected: ![with VS code](https://github.com/microsoft/vscode/assets/64051003/b9f966fb-b771-4e42-84ee-55b863a42d27)

Expected: ![with windows terminal](https://github.com/microsoft/vscode/assets/64051003/e94ee5aa-51f6-4cf2-83fb-d5705203b213)

I have tried several fixes I have seen in other issues such as terminal.integrated.minimumContrastRatio = 1 and terminal.integrated.gpuAcceleration = off but nothing seems to help. 

Specifically, the unexpected rendering is the broken blocks (i.e. separated with no color in magenta block) and the faint lines next to the arrows of each block. I have tried several nerd fonts but am currently using "FiraCode Nerd Font"

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.20GB (16.20GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/jtuck/sitka_weather --crash-reporter-id 8e67fd53-84be-44f1-ad7e-2a94dca9ca42|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by nklowns** [comment] 2023-09-08 21:56
Hello, I'm also having the same problem,
I had opened an [issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/4233) in JanDeDobbeleer's git, but the problem is in the vscode

**Comment by nklowns** [comment] 2023-09-08 21:58
When I test the theme in wsl bash, it behaves correctly, so I believe it's something in powershell in vscode
The powershell in the vscode looks strange with blank spaces, I use the FiraCode NerdFonts font, follow images for identification:

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/17345221/81ef37cf-2138-4b06-a16a-829b88751fda)

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/17345221/21a550a4-753c-4e24-886f-5f2504e0298b)

**Comment by Tyriar** [comment] 2023-09-10 14:48
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/label terminal terminal-conpty windows

**Closed by Tyriar** 2023-09-10 14:48 UTC
Labels: confirmation-pending, terminal-rendering
