### ISSUE TITLE
Code Editor does not render in build - Insiders 1.19.0-insider (432b53b)

### ISSUE THREAD

**Issue by FjVillar** [Microsoft/vscode#37698] opened 2017-11-06 08:00 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.2
atom-keybindings|ms-|3.0.2
vscode-icons|rob|7.17.0

(1 theme extensions excluded)

I use Material Palenight theme.

---

Steps to Reproduce:

1. Today update.
2. The text of my js files don't appear
3. Change theme, the text still not appearing.
3. Re-installed 1.18, everything is fine.

Reproduces without extensions: Yes

**Comment by Outpox** [comment] 2017-11-06 16:06
Can reproduce the issue as well 

- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-formatter|Sop|0.2.4
quokka-vscode|Wal|1.0.75
vscode-intelephense-client|bme|0.8.0
vscode-standardjs|che|1.2.0
githistory|don|0.2.3
php-intellisense|fel|1.5.4
vetur|oct|0.11.0
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
twig|wha|1.0.2

**Comment by bpasero** [comment] 2017-11-07 06:24
@alexandrudima it looks like 1.19 shipped only on Linux to some people. Related stack:

```
charCode is not defined: ReferenceError: charCode is not defined
    at o (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:530695)
    at Object.s [as renderViewLine] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:531359)
    at e.renderLine (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1491408)
    at e._finishRendering (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:400302)
    at e.render (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:398052)
    at e.renderLines (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:397467)
    at t.renderText (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1538123)
    at t._actualRender (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1641210)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1640476
    at z (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1633012)
```

**Comment by payonel** [comment] 2017-11-07 08:02
If i only need to thumbs up the original poster, I'll remember to do that next time. Otherwise, I'd like to add:

same here

Can get any editor window to display. c++, scala, java, lua, ruby, js

**Comment by payonel** [comment] 2017-11-07 08:04
interesting test. if i open vscode with no folder, ^n to get a blank new unnamed document and just start typing - no text is displayed
but if i ^a ^c to copy all, i can confirm the text i wrote is copied to the clipboard

**Comment by alexandrudima** [comment] 2017-11-07 09:43
I cannot reproduce on master or when locally checking out that commit.

I will download the actual build to try to understand what's going on.

**Comment by Outpox** [comment] 2017-11-07 09:52
I've had an update this morning (I'm using code-insiders from aptitude on a Linux Mint) which seems to have solved this issue.  
```
Version 1.19.0-insider
Commit 3f9457a75003de5c813701e1c1653238c74fdeaf
Date 2017-11-07T06:22:51.567Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by alexandrudima** [comment] 2017-11-07 10:12
I can reproduce in the built (minified) version.

**Comment by alexandrudima** [comment] 2017-11-07 10:33
I believe this is a bug with the uglifier we are using. @joaomoreno I see a lot of activity at https://github.com/mishoo/UglifyJS2/commits/master

How can we find which version our built-machine used ?

**Comment by alexandrudima** [comment] 2017-11-07 10:47
The bad build (432b53b) was minified with `uglify-js@3.1.7`
The good build (3f9457a75003de5c813701e1c1653238c74fdeaf) was minified with `uglify-js@3.1.8`

**Comment by bpasero** [comment] 2017-11-17 13:25
@alexandrudima I think we fixed this meanwhile?

**Comment by alexandrudima** [comment] 2017-11-17 13:53
This got fixed by @joaomoreno where we now lock our dev deps. Thanks @joaomoreno

**Closed by alexandrudima** 2017-11-17 13:53 UTC
Labels: important, insiders, upstream
