### ISSUE TITLE
Find in files

### ISSUE THREAD

**Issue by poblouin** [microsoft/vscode#88255] opened 2020-01-08 02:01 UTC
Find in files not working with latest insiders version on Mac OS Catalina? Even using the command palette it doesn't work

**Comment by IllusionMH** [comment] 2020-01-08 10:33
/duplicate of #88132


Already works as expected in latest insider build
Version: 1.42.0-insider (user setup)
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:39:25.874Z

**Closed** 2020-01-08 10:33 UTC
Labels: *duplicate
