### ISSUE TITLE
LinkLocation uses targetRange as the selection range not tragetSelectionRange

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#64985] opened 2018-12-13 11:09 UTC
The read through the code and found the following in our renderer code:

- `selectionRange` on DefinitionLink is not used
- `openReference` code looks like this:
```
	private _openReference(editor: ICodeEditor, editorService: ICodeEditorService, reference: Location, sideBySide: boolean): Thenable<ICodeEditor> {
		return editorService.openCodeEditor({
			resource: reference.uri,
			options: {
				selection: Range.collapseToStart(reference.range),
				revealIfOpened: true,
				revealInCenterIfOutsideViewport: true
			}
		}, editor, sideBySide);
	}
```
- code to convert from API does:
```
	export function from(value: vscode.Location | vscode.DefinitionLink): modes.DefinitionLink {
		const definitionLink = <vscode.DefinitionLink>value;
		const location = <vscode.Location>value;
		return {
			origin: definitionLink.originSelectionRange
				? Range.from(definitionLink.originSelectionRange)
				: undefined,
			uri: definitionLink.targetUri ? definitionLink.targetUri : location.uri,
			range: Range.from(definitionLink.targetRange ? definitionLink.targetRange : location.range),
			selectionRange: definitionLink.targetSelectionRange
				? Range.from(definitionLink.targetSelectionRange)
				: undefined,
		};
	}

```

**Comment by jrieken** [comment] 2018-12-13 11:10
@mjbvz it looks you added the API but didn't adopt it. Is this something you wanna take?

**Comment by jrieken** [comment] 2018-12-13 11:12
/duplicate of https://github.com/Microsoft/vscode/issues/58649

**Closed** 2018-12-13 11:12 UTC
Labels: *duplicate, bug, editor-symbols
