### ISSUE TITLE
[new-feature] History File

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#120633] opened 2021-04-06 13:11 UTC
feature=history_file

[original][pt-br]
1. criar uma pasta oculta no diretorio do arquivo com nome code.git e iniciar o repositorio git dessa pasta
2. sempre que o arquivo for salvo deve-se copia-lo para a pasta code.git e realizar o "git add file & git commit -m \"${msg}\"". msg deve ser configurada em settings.json com direito a parâmetros diversos, que envolvem o Code e o arquivo, como versão do Code, caso contrário deve ser gerado alguma mensagem padrão`
3. na barra lateral esquerda deve ser colocado uma segunda coluna após a coluna de collapse e expand brackets. Essa coluna a ser adicionada deve ser idêntica a coluna que já existe para arquivos git versionados. Essa barra deve permanecer após a coluna collapse e expand brackets mesmo se nunca tiver sido feito um commit desse arquivo ou a pasta desse arquivo não for um repositório git desde que tenha algum commit desse arquivo no repositório code.git
4. Essa feature deve funcionar se estiver habilitada mesmo se a feature de salvar automático estiver habilitada.
5. Essa feature deve ser fornecida desabilitada por padrão.
6. Deve-se informar nas release notes das versões insider e stable que a feature está disponível com apresentação de uso com gifs animados como ocorre para outras features.

[en][Bing Translate]
1. create a hidden folder in the directory of the file named code.git and start the git repositorio of that folder
2. whenever the file is saved, copy it to the code.git folder and perform the "git add file & git commit -m "${msg}". msg must be configured in settings.json with the right to various parameters, which involve the Code and the file, such as code version, otherwise some standard message should be generated'
3. In the left sidebar should be placed a second column after the collapse column and expand brackets. This column to be added must be identical to the column that already exists for versioned git files. This bar should remain after the collapse column and expand brackets even if this file has never been committed, or the folder of that file is not a git repository as long as it has some commit of that file in the code.git repository
4. This feature should work if it is enabled even if the auto save feature is enabled.
5. This feature should be provided disabled by default.
6. It should be informed in the release notes of the insider and stable versions that the feature is available with presentation of use with animated gifs as occurs for other features.

![image](https://user-images.githubusercontent.com/38570195/113715333-61dd3280-96b7-11eb-882d-28e8c15461a7.png)

**Comment by IllusionMH** [comment] 2021-04-06 14:23
Looks like it's #98601 should be tracking file history and showing it in Timeline view.

And I'm doubt it's make to bring second indicators for gutter for file history - noisy + would be confusing with actual VCS.

/cc @eamodio

**Comment by AlexandroGonSan** [comment] 2021-04-06 17:36
> Looks like it's #98601 should be tracking file history and showing it in Timeline view.
> 
> And I'm doubt it's make to bring second indicators for gutter for file history - noisy + would be confusing with actual VCS.
> 
> /cc @eamodio

should be also jointly Timeline view + second column after the collapse column and expand brackets

**Comment by AlexandroGonSan** [comment] 2021-04-07 12:09
case use database standards is required then export to code.git should to be true with option of export all to one specified uri of code.git than should keep uri of files.

**Comment by eamodio** [comment] 2021-04-14 05:06
Duplicate of https://github.com/microsoft/vscode/issues/26339

**Closed** 2021-04-14 05:06 UTC
Labels: *duplicate
