### ISSUE TITLE
Focus/scroll position often jumps to the top on many operations

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119729] opened 2021-03-23 22:55 UTC
Testing #119118

Drag and dropping often causes focus to be lost and the scroll position to be reset to the top.

Duplicating a cell (shift+alt+down), causes focus to be lost and the scroll position to be reset to the top -- so it is really hard to see where new items are being inserted

Join with previous cell seems to do the same.

**Comment by rebornix** [comment] 2021-03-24 23:18
This is a duplicate of https://github.com/microsoft/vscode/issues/119767 , which has more details, let's merge into that.

**Closed by rebornix** 2021-03-24 23:19 UTC
Labels: bug, notebook-layout
