### ISSUE TITLE
Typescript "Go to Definition" goes to function type, not its implementation

### ISSUE THREAD

**Issue by ta-stott-oe** [Microsoft/vscode#18321] opened 2017-01-09 15:27 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

**Steps to Reproduce:**

1. In `a.ts`, export a function type:
```typescript
export interface MyFunctionType {
    (): string;
}
```
2. In `b.ts`, import the type and export a variable which implements it
```typescript
import {MyFunctionType} from "./a";
export function MyFunction: MyFunctionType = () => {
    return "test";
}
```
3. In `c.ts`, import the function variable, and invoke it
```typescript
import {MyFunction} from "./b";
MyFunction();
```
4. Place the caret somewhere inside the function call and *Go to Definition*.

**Outcome**
VSC takes you to `a.ts` (where the type of the variable is defined), not `b.ts` (where the variable is defined).

**Real life example**
You have a Knockout view model class with properties of type `KnockoutObservable<T>` (which may be invoked as a function). When you try to navigate to the definition of such a property, VSC takes you to the definition of `KnockoutObservable` in `knockout.d.ts`, not to the view model class.

**Comment by mjbvz** [comment] 2017-01-09 18:45
Closing as duplicate of #10806

**Closed by mjbvz** 2017-01-09 18:45 UTC
Labels: duplicate, feature-request, javascript, typescript
