### ISSUE TITLE
Extenstions are not working

### ISSUE THREAD

**Issue by harshilparmar** [microsoft/vscode#94762] opened 2020-04-09 08:45 UTC
After the last update of VS code,I can not use any extensions. Please help...

**Comment by gjsjohnmurray** [comment] 2020-04-09 09:13
Please find out which of your extensions is causing the issue. Either disable all and then re-enable one at a time, or disable half of them to narrow the field faster (bisecting).

Similar to #94756

**Comment by RMacfarlane** [comment] 2020-04-09 16:10
Duplicate of https://github.com/microsoft/vscode/issues/94807

**Closed** 2020-04-09 16:10 UTC
Labels: *duplicate
