### ISSUE TITLE
Allow to configure the tab title using variables

### ISSUE THREAD

**Issue by aazarkhish** [Microsoft/vscode#21662] opened 2017-03-01 22:26 UTC
Hi 
I thought it would be good idea to have a title setting for tabs like window.title to be able to add the folder name to the title all the time.

Thanks

**Comment by mcamack** [comment] 2017-08-12 03:58
Is there any update on this feature?

**Comment by comerc** [comment] 2017-08-30 15:01
[Related](https://github.com/Microsoft/vscode/issues/12965#issuecomment-326016306)

**Comment by bpasero** [comment] 2017-09-09 07:30
I am going to mark this as duplicate of https://github.com/Microsoft/vscode/issues/12965 because the summary here asks about showing the parent folder for tabs always and #12965 will address this.

**Closed by bpasero** 2017-09-09 07:30 UTC
Labels: feature-request, workbench, workbench-tabs
