### ISSUE TITLE
Backspace and arrow keys stop working

### ISSUE THREAD

**Issue by dfblackburn** [Microsoft/vscode#23687] opened 2017-03-30 17:10 UTC
- VSCode Version: 1.10.2
- OS Version: Win7 Pro SP1 64 bit on bootcamp partition via VMWare Fusion 8.5.6 (and some previous versions of Fusion)

Steps to Reproduce:
1. Do some work

Then the arrow keys and backspace key stop working.
Up and down arrows typically work.
Left almost always does not.
Backspace does not.
Right usually does, but sometimes does not.
Delete usually does, but sometimes does not.
Delete and right arrow key might work/not work together.
Closing and reopening VS Code is the only way I have found to fix the problem.

Sorry I cannot find some more reasonable steps to reproduce this.

Thank you!

**Comment by alexandrudima** [comment] 2017-03-31 07:39
@dfblackburn Does Chrome suffer from the same issue? Can you please also try the **insiders channel release** where we show a bit more information?

When this occurs, can you please open the define keybindings widget (File > Preferences > Keyboard Shortcuts -> go to keybindings.json):

Then, press the key that doesn't work **and hover with the mouse over the input box**. This will show the values we receive from Electron/Chromium for the key down event (`e.code`, `e.keyCode` and `e.key`). Those are the inputs we receive and react upon.

![image](https://cloud.githubusercontent.com/assets/5047891/24540638/6205b838-15f4-11e7-889d-58fb4f99354f.png)

Also, how does Chrome behave under the same setup? i.e. you can go to https://jsfiddle.net/v1gz5c5m/1/ and press in there the same keys and see what output is produced.

**Comment by dfblackburn** [comment] 2017-03-31 19:29
I have not noticed any problems in Chrome or within the other Electron app I am developing in VS code.
That fiddle displays what I would expect when I hit the keys in question.
I have installed the insiders release; I will get you some more information if the problem pops up again.
It seems to happen a lot for a day or so and then vanish for a month or so.
Let me know if you need anything else before I can get you keybinding info.

**Comment by cyrus86** [comment] 2017-04-07 09:21
I experience the same behavior upon saving a file

**Comment by ianrenauld** [comment] 2017-05-02 19:17
What I have seen is something similar, but I noticed that the arrow keys are actually being sent to the Explorer pane, while all the other "normal keys" are being sent to the editor pane.  Closing the Visual Studio Code window and reopening a new one solves the issue (no need to fully quit). This is on a MacBook pro running macOS Sierra.

Not 100% sure this is the same thing seem by others in the thread, but it might be related.

**Comment by alexandrudima** [comment] 2017-05-10 19:01
@cyrus86 @ianrenauld If you find any reproducible steps please create separate issues, the root causes might be very different, especially across different operating systems.

@dfblackburn Given there's been no update for a month, I will close this issue for now. Please reopen if there are any reproducible steps, although this issue could be in VMWare Fusion

**Closed by alexandrudima** 2017-05-10 19:01 UTC
Labels: needs more info, windows

**Comment by dfblackburn** [comment] 2017-05-11 13:24
I have also seen this issue on macOS a while ago, so I don't think it is limited to VMWare Fusion (though they could have separate causes, as you mentioned).
I will let you know if I get some more information.
I have not seen it again since my original post.

**Comment by peacefixation** [comment] 2017-09-20 02:10
I experience this bug on OSX Yosemite with VSCode 1.16.0. Enter, spacebar, arrow keys all stop working. Alpha and numeric keys still work fine. I tried to follow the steps you outline:

> When this occurs, can you please open the define keybindings widget (File > Preferences > Keyboard Shortcuts -> go to keybindings.json):
> 
> Then, press the key that doesn't work and hover with the mouse over the input box.

But opening keybindings.json fixed the issue and the keys started responding again.

**Comment by danmux** [comment] 2017-10-03 10:34
I have the same issue, it appears to happen when I repeatedly press one of the control keys - i cant be sure, but i just vaguely think it was shortly after I was jamming on a key.

My symptom is the same as @ianrenauld cursors keys being sent to explorer window.

A close and reopen is a work around.

**Comment by smk291** [comment] 2017-10-06 16:53
Similar issue here: backspace stops working. This happens occasionally, not consistently, when the editor fills in HTML/JSX in .tsx files, e.g. when it automatically adds a ">" at the end of the element or automatically creates the closing tag (such as "</div>"). This has been happening consistently in the same place a certain file. Happy to send the code and any-/everything about my setup (OS, VSCode configuration, extensions, etc) if that would help.

**Comment by dfblackburn** [comment] 2017-10-09 14:30
Just as an update, I have been using the Insiders release pretty exclusively since I posted this problem, and I have not seen it occur again.

**Comment by dyyylan** [comment] 2017-10-13 18:49
> What I have seen is something similar, but I noticed that the arrow keys are actually being sent to the Explorer pane, while all the other "normal keys" are being sent to the editor pane. Closing the Visual Studio Code window and reopening a new one solves the issue (no need to fully quit). This is on a MacBook pro running macOS Sierra.
> 
> Not 100% sure this is the same thing seem by others in the thread, but it might be related.

I'm having this same issue on macOS High Sierra. Seems to happen intermittently, I have no idea what could possibly cause it since it happens so infrequently. I can type in the editor, but some keys (arrows, return, backspace) target the explorer pane instead of the editor. Restarting always fixes it.

**Comment by taylorthurlow** [comment] 2017-11-16 01:54
Same issue on Ubuntu 16.04.
