### ISSUE TITLE
Why vscode can not know which plug-in caused by the crash?

### ISSUE THREAD

**Issue by hevily** [Microsoft/vscode#34182] opened 2017-09-12 01:09 UTC

**Comment by alexandrudima** [comment] 2017-09-12 07:23
At this time, all extensions are loaded in the same extension host process. That process ends up executing code from multiple extensions, depending on which ones have activated. It is difficult to automatically figure out which extension is the root cause of a crash. Perhaps if you let us know your specific steps / installed extensions we can try to narrow it down together.

**Comment by ramya-rao-a** [comment] 2017-09-18 16:23
Closing this issue as OP has already logged another issue #34128 for the crashing problem

**Closed by ramya-rao-a** 2017-09-18 16:23 UTC
Labels: needs more info
