### ISSUE TITLE
[VSC] Editor freeze on deleted image

### ISSUE THREAD

**Issue by levrik** [microsoft/vscode#69334] opened 2019-02-25 09:24 UTC
Issue Type: <b>Bug</b>

The whole editor freezes if I click on a deleted image in the changes view of VSC (Git).

![kapture 2019-02-25 at 10 30 37](https://user-images.githubusercontent.com/9491603/53327603-6fc10680-38e8-11e9-9357-a92e0aa0ca54.gif)
_(GIF)_

![image](https://user-images.githubusercontent.com/9491603/53327209-a2b6ca80-38e7-11e9-953d-aa596b6d59b3.png)

This is really annoying if you click on it by accident and have to wait for one/two minutes till you can restart the editor.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|-psn_0_7645002|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
prettier-vscode|esb|1.8.1
vscode-pull-request-github|Git|0.4.0
vscode-styled-components|jpo|0.0.25
vscode-language-pack-de|MS-|1.31.4
vscode-kubernetes-tools|ms-|0.1.16
python|ms-|2019.1.0
vscode-yaml|red|0.2.1
code-settings-sync|Sha|3.2.4

(1 theme extensions excluded)

</details>

With all extensions disabled it hangs for about 10 seconds, then the image loads.
With extensions enabled it hangs a one or two minutes before getting the prompt.

**Comment by joaomoreno** [comment] 2019-02-26 20:11
@bpasero I thought we had size limits here?

**Comment by bpasero** [comment] 2019-02-27 07:16
@joaomoreno are you opening these files via the data-URI trick? The size should be encoded as [`META_DATA_SIZE`](https://github.com/Microsoft/vscode/blob/ce073b0/src/vs/base/common/resources.ts#L274) which then (if large enough) would cause the image to not be rendered inline. But I am not sure that is happening here.

@levrik do you see a text editor opening eventually or the image shown inline?

**Comment by levrik** [comment] 2019-02-27 08:54
@bpasero Without any extensions enabled the image opens normally after about 10 seconds. With all my extensions enabled it loads one or two minutes before getting the unresponsive message.

**Comment by joaomoreno** [comment] 2019-02-27 08:58
@levrik How big, in bytes, is that JPEG?

**Comment by levrik** [comment] 2019-02-27 09:02
@joaomoreno 293.398 bytes

**Comment by joaomoreno** [comment] 2019-02-27 09:14
Any chance you can send it to me?

**Comment by levrik** [comment] 2019-02-27 09:31
@joaomoreno You can download it here: https://hypatos.ai/content/5-imprint/og-image.jpg

**Comment by bpasero** [comment] 2019-02-27 09:32
@levrik can you point out the extension that is causing it e.g. by disabling the extensions one by one?

**Comment by joaomoreno** [comment] 2019-02-27 09:47
@bpasero I can repro this without extensions.

1. Add the file to a git repo, commit
2. Delete the file
3. Open the file in SCM, opens fast
3. Close it and open it again, opens very slowly

**Comment by levrik** [comment] 2019-02-27 09:49
@joaomoreno Yep. Exactly this. With extensions enabled it doesn't load at all. It just shows the unresponsive warning at some point.

**Comment by bpasero** [comment] 2019-02-27 09:50
@joaomoreno can you check if memory goes beserk?

**Comment by joaomoreno** [comment] 2019-02-27 09:55
@bpasero 

![image](https://user-images.githubusercontent.com/22350/53481709-0d017380-3a7e-11e9-85a1-d09caac1225f.png)

[Profile-20190227T105432.json.zip](https://github.com/Microsoft/vscode/files/2909577/Profile-20190227T105432.json.zip)

**Comment by bpasero** [comment] 2019-02-27 12:12
@joaomoreno yeah it looks like V8 is spending a very long time in `this._models[modelId];` where `modelId` is the entire data URI which is probably very long. 

![image](https://user-images.githubusercontent.com/900690/53489334-3bd51500-3a91-11e9-8dc8-b27b626cd8b9.png)

Maybe I can make that call smarter and not do the `getModel` lookup when I have a data resource in hand.

**Comment by joaomoreno** [comment] 2019-02-27 14:14
Yeah could be a good idea. Another couple ideas:

- Maybe try using ES6 map? I wonder...
- Maybe store modelId hashes in the map instead of modelIds themselves.

**Comment by bpasero** [comment] 2019-02-27 14:29
@alexandrudima on https://github.com/Microsoft/vscode/issues/69334#issuecomment-467876875. The idea would be to change to a `Map` for [`getModel`](https://github.com/Microsoft/vscode/blob/dd7f1cd/src/vs/editor/common/services/modelServiceImpl.ts#L393). Though I am not sure that would work given this is in the standalone editor part.

**Comment by bpasero** [comment] 2019-03-02 08:14
My fix is to avoid the `getModel()` call for data URIs and use the metadata encoded in the URI instead.

**Comment by alexandrudima** [comment] 2019-03-04 08:38
@bpasero I suggest we remove the data-uri hack rather than blaming v8 or rewriting our code for the hack.

**Comment by kieferrm** [comment] 2019-05-29 17:42
According to https://github.com/microsoft/vscode/issues/74515 still happening in 1.34.

**Comment by bpasero** [comment] 2019-05-31 07:16
@levrik can you give some exact steps how to reproduce this? I tried with the original image (which I guess I still had) and could not:

![before](https://user-images.githubusercontent.com/900690/58688253-3f27b780-8384-11e9-8a39-8ccb42d32cae.gif)

**Comment by levrik** [comment] 2019-06-03 07:50
@bpasero Happened with a different image this time but I also tried with the original one and it happened there as well. But there was a difference. With all extensions disabled it didn't happen anymore. I could track it down to the Kubernetes extension. Should I open an issue over there? It's a bit weird that this extension is causing this since it shouldn't do anything with version control.

**Comment by itowlson** [comment] 2019-06-06 01:03
I'm the maintainer of the Kubernetes extension that @levrik has identified as suffering from this issue.  The thing is that having the extension present results in the hang _even if the extension has not activated_.  Even if I _delete all of our extension's activation events_, the hang still happens!

From hacking around our `package.json`, it looks like the issue is a particular `filenamePattern` in a language contribution.  I feel this is a VS Code issue, as this is a legitimate pattern and I don't see any reason why it should affected deleted image previews.  I've raised an issue on VS Code, and provided a minimal extension that reproduces the issue at https://github.com/itowlson/git-deleted-image-hang-o-matic.  Hope this helps!

**Comment by bpasero** [comment] 2019-06-06 07:14
We should not test these URIs in our language detection (`mime.ts`?). Happy for a PR if someone has cycles.

**Comment by bpasero** [comment] 2019-06-06 07:16
@mjbvz did we recently increase the max-size for images? I wonder if this also means we now have much larger data URIs in our system. It used to be 1MB I think.

**Comment by joaomoreno** [comment] 2019-06-06 11:44
From #74926

---

Issue Type: <b>Bug</b>

This relates to https://github.com/microsoft/vscode/issues/69334, which was resolved but recurs in this specific situation.  See also https://github.com/Azure/vscode-kubernetes-tools/issues/558 which is how it came to me.

Steps to reproduce:

1. Create a git repo.  Add an image (e.g. JPEG) to it and commit.  Delete the image and do *not* commit.  If you click on the deleted file diff in the SCM explorer, VS Code will show the deleted image.  This is all as expected so far.

2. Create a new VS Code extension and add the following contribution:

```
        "languages": [
            {
                "id": "hanglywangly",
                "filenamePatterns": [
                    "**/foo/*.hanglywangly"
                ]
            }
        ]
```

(I have provided an extension which reproduces the problem at https://github.com/itowlson/git-deleted-image-hang-o-matic.)

3. Run the extension in the Extension Development Host.

4. In the Extension Development Host, open the git repo from step 1, go to the SCM view and click on the deleted image.

VS Code freezes up as described in https://github.com/microsoft/vscode/issues/69334.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

**Closed** 2019-06-11 07:55 UTC
Labels: freeze-slow-crash

**Comment by levrik** [comment] 2019-06-11 08:05
@bpasero Any plans when the fix is getting shipped? I'm running into that issue on a daily basis and it's kinda annoying having to wait for the dialog to come up, reload, and that stuff.

**Comment by bpasero** [comment] 2019-06-11 08:24
@levrik in around 1 hour in our insiders build:  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by levrik** [comment] 2019-06-11 09:15
@bpasero I can confirm that this issue is fixed now! Thanks a lot!
