### ISSUE TITLE
Why do you keep on changing the default behavior of the keyboard shortcuts and commands?

### ISSUE THREAD

**Issue by nonoroazoro** [Microsoft/vscode#70196] opened 2019-03-11 08:36 UTC
- VSCode Version: **1.32.1**
- OS Version: **macOS Sierra**

In recent VSCode updates, seems that you keep on changing the default behavior of the long-existing keyboard shortcuts and commands, **which is very very annoying**.

Here're some of the odd behaviors:

- Wanna **Go to Definition** by pressing **cmd+left_mouse**, but I got a **Peek the definition** instead (Ref PR #68023), here's an example:

    - ![Example](https://user-images.githubusercontent.com/383132/54109636-26a9a000-441a-11e9-8336-08fe8b4fd6dd.gif)

- Wanna **Expand Selection (smartSelect.grow/smartSelect.expand)** by pressing **alt+w** (customized), but I got a wrong behavior instead, especially when the target text contains **hyphens**, here's an example:

    I'm going to **expand and select the text between the quotes** by calling **Expand Selection** command.

    - Incorrect: ![incorrect](https://user-images.githubusercontent.com/383132/54108874-07117800-4418-11e9-8178-ffeebfbaba0c.gif)

    - Correct: ![correct](https://user-images.githubusercontent.com/383132/54108860-ffea6a00-4417-11e9-9f01-27a33c057de9.gif)

Will you consider of keeping the consistency of these and those functionalities?

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2019-03-11 08:50
/duplicate of https://github.com/Microsoft/vscode/issues/70032

**Comment by nonoroazoro** [comment] 2019-03-11 08:51
@jrieken What about the wrong behavior of the `Expand Selection` command?

**Closed** 2019-03-11 08:50 UTC
Labels: *duplicate, new release
