### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by Jxiang-jc** [microsoft/vscode#174208] opened 2023-02-13 01:26 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230210

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33923:11)
    at parseSimpleUnaryExpression (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33552:16)
    at parseUnaryExpressionOrHigher (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33520:35)
    at parseBinaryExpressionOrHigher (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33438:25)
    at parseAssignmentExpressionOrHigher (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33111:18)
    at parseExpression (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33077:16)
    at doOutsideOfContext (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30772:12)
    at allowInAnd (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30793:12)
    at parseExpressionOrLabeledStatement (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34593:24)
    at parseStatement (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34825:12)
    at parseListElement (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31544:12)
    at parseList (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31529:19)
    at parseSourceFileWorker (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30588:24)
    at Object.parseSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30421:20)
    at createSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30282:21)
    at createLanguageServiceSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:134900:22)
    at acquireOrUpdateDocument (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131822:26)
    at Object.acquireDocumentWithKey (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131747:12)
    at getOrCreateSourceFileByPath (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135225:31)
    at Object.getOrCreateSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135205:14)
    at D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135137:42
    at Object.getSourceFileWithCache [as getSourceFile] (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:116904:24)
    at findSourceFileWorker (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119236:23)
    at findSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119156:20)
    at D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119105:22
    at getSourceFileFromReferenceWorker (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119074:26)
    at processSourceFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119103:5)
    at processRootFile (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:118899:5)
    at D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:41
    at forEach (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:5)
    at synchronizeHostData (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135161:15)
    at Proxy.getProgram (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135233:5)
    at ConfiguredProject2.updateGraphWorker (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171784:41)
    at ConfiguredProject2.updateGraph (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171721:32)
    at ConfiguredProject2.updateGraph (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:172903:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:174510:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175601:26)
    at D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:64
    at flatMap (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:24)
    at updateOpen (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:177026:29)
    at D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:69
    at IpcIOSession.executeWithRequestId (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179585:14)
    at IpcIOSession.executeCommand (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:29)
    at IpcIOSession.onMessage (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179635:51)
    at process.<anonymous> (D:\Users\zhangjx195\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:181203:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (19.37GB free)|
|Process Argv|--crash-reporter-id b4461ecc-4874-4c05-b0af-4ee0cc0f87de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
turbo-console-log|Cha|2.6.3
gitlens|eam|13.2.0
leek-fund|gis|3.0.3
vscode-language-pack-zh-hans|MS-|1.75.2023020809
vscode-typescript-next|ms-|5.0.202302100
indent-rainbow|ode|8.3.1
svg-preview|Sim|2.8.3
code-spell-checker|str|2.16.0
vscode-icons|vsc|12.2.0
volar|Vue|1.0.24
vscode-typescript-vue-plugin|Vue|1.0.25

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12cf:30657549
vscodeenable:30660116

```

</details>

**Comment by mjbvz** [comment] 2023-02-21 02:29
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:29 UTC
