### ISSUE TITLE
Selecting a multiline word in the terminal by double-clicking misses the last character

### ISSUE THREAD

**Issue by kevin-he-01** [microsoft/vscode#126799] opened 2021-06-21 04:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows 10 Home Build 19042.1052 on x86-64 (Intel 64 bit)

Steps to Reproduce:

1. Open the Integrated Terminal with a shell of your choice (`pwsh`, `cmd`, and WSL `bash` all confirmed to reproduce this bug)
2. Run a terminal program to output a word long enough to cause it to wrap to the next line of the terminal. Alternatively, input such a word and press enter (Words are defined as sequences of characters that are not in the defined in the value of the setting `terminal.integrated.wordSeparators`)
3. Double-click anywhere on the word to select the word (_do not triple-click_)

Screenshot (made on latest insider build to show it has not been fixed as of the time of writing):
![image](https://user-images.githubusercontent.com/32375681/122705247-2fe56200-d20a-11eb-8aad-ca3414b34b1f.png)

Expected behavior: The last character (the final 9 in the screenshot) should be selected

Actual behavior: The last character isn't selected

**Comment by meganrogge** [comment] 2021-06-28 14:46
Duplicate of #123000, which has been fixed upstream. Will be fixed when we adopt the next version of xterm.js

**Closed by meganrogge** 2021-06-28 14:46 UTC
