### ISSUE TITLE
Code review/comment API exploration

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#45945] opened 2018-03-16 04:09 UTC
To support displaying code comments in the editor, we can leverage viewzone and overlay widget, but as our view components (like view lines, decorations) are absolutely positioned, we want to know the height of viewzone, to archive that

* we can guess by the content. it has limitation as markdown content can contain images
* render the overlay widget first, get its height, resize the viewzone and relayout the editor

The second one is how VSTS manages code comments in monaco editor right now, the experience looks smooth.

**Comment by jrieken** [comment] 2018-03-28 14:24
This could be a dupe of https://github.com/Microsoft/vscode/issues/3220

**Closed** 2018-03-29 18:05 UTC
