### ISSUE TITLE
Interface Overview arrows may not point to the correct tiles in the sidebar

### ISSUE THREAD

**Issue by hkennyv** [microsoft/vscode#118484] opened 2021-03-08 21:14 UTC
- VS Code Version: 1.55.0-insider (Universal)
- OS Version: Darwin arm64 20.1.0

```
Version: 1.55.0-insider (Universal)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:24:34.127Z (15 hrs ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.1.0
```

Hi there again, I have another minor visual bug to report. When rearranging tiles in the vscode sidebar, the "Interface Overview" overlay arrows may point to the wrong tile. It is a very minor bug (almost nitpicking), so please let me know if this is not the proper place for this. 

Steps to Reproduce:

1. Install an extension that adds a new tile to the sidebar (in my example, I'll install `ms-vscode-remote.remote-containers`)
2. Drag the new "Remote Explorer" tile in the sidebar so that it is above the "Extensions" tile (see image below)
![image](https://user-images.githubusercontent.com/29909203/110382372-aa99c100-800f-11eb-90e3-08ff62abc249.png)
3. Open the command palette (cmd+shift+p on macos) and run the "Help: Interface Overview" command
4. See the extension arrow is pointing to the incorrect sidebar tile. This could be incorrect depending on how the user has their sidebar configured.

![image](https://user-images.githubusercontent.com/29909203/110382469-d0bf6100-800f-11eb-90d8-c48322563efb.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by yume-chan** [comment] 2021-03-09 07:46
Duplicate of #92312

**Closed** 2021-03-09 17:24 UTC
