### ISSUE TITLE
breakpoints when debugging docker linux target from windows not set

### ISSUE THREAD

**Issue by geogeim** [Microsoft/vscode#53891] opened 2018-07-09 16:56 UTC
Issue Type: <b>Bug</b>

launch.json: 
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "docker",
      "address": "localhost",
      "port": 9229,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/app",
      "trace": "verbose",
    }
  ]
}
```
debug console messages when removing/adding breakpoint:
```
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"Versions.DebugAdapterCore":"6.3.1","Versions.DebugAdapter":"1.25.5","Versions.Target.Version":"v8.11.3","fileExt":".js"}}}
Mapped localToRemote: d:\Work\anais\bee-forms-extension\middleware\src\rest\requests\pdf.js -> /app/src/rest/requests/pdf.js
SourceMaps.setBP: SourceMaps are enabled but d:\Work\anais\bee-forms-extension\middleware\src\rest\requests\pdf.js is a runtime script
Mapped localToRemote: d:\Work\anais\bee-forms-extension\middleware\src\rest\requests\pdf.js -> /app/src/rest/requests/pdf.js
Paths.setBP: Resolved d:\Work\anais\bee-forms-extension\middleware\src\rest\requests\pdf.js to /app/src/rest/requests/pdf.js
Mapped localToRemote: /app/src/rest/requests/pdf.js -> /app/C:/app/src/rest/requests/pdf.js
→ To target: "{\"id\":15,\"method\":\"Debugger.setBreakpointByUrl\",\"params\":{\"urlRegex\":\"\\\\/app\\\\/C:\\\\/app\\\\/src\\\\/rest\\\\/requests\\\\/pdf\\\\.js\",\"lineNumber\":29,\"columnNumber\":0}}"
← From target: {"id":15,"result":{"breakpointId":"/\\/app\\/C:\\/app\\/src\\/rest\\/requests\\/pdf\\.js/:29:0","locations":[]}}
To client: {"seq":0,"type":"response","request_seq":11,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1000,"verified":false,"message":"Breakpoint set but not yet bound"}]}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/setBreakpoints","data":{"Versions.DebugAdapterCore":"6.3.1","Versions.DebugAdapter":"1.25.5","Versions.Target.Version":"v8.11.3","successful":"true","timeTakenInMilliseconds":"37.400099","requestType":"request"}}}
```

If the debugger stops on exception and I click the file in the stack panel then it opens the right line in the file. But setting breakpoints does not work (breakpoints are "unverified")

EDIT: just tested version 1.24.1 and breakpoints work, so this may be a regression

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (3.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
rightclick-git|Eve|1.0.0
rest-client|hum|0.19.0
debugger-for-chrome|msj|4.7.0

</details>

**Comment by roblourens** [comment] 2018-07-09 18:10
Probably dupe of #53785

**Closed** 2018-07-09 18:11 UTC
Labels: *duplicate, debug, new release
