### ISSUE TITLE
How to install plugins behind a proxy with a self-signed certificate?

### ISSUE THREAD

**Issue by ywmail** [Microsoft/vscode#155] opened 2015-11-19 07:12 UTC
I'm using vs code behind a proxy with a self-signed certificate, when i try to install plugins and typing "ext install ", it shows an error "unable to verify the first certificate".

**Comment by FloMaetschke** [comment] 2015-11-19 07:38
same problem here.

**Comment by joaomoreno** [comment] 2015-11-19 08:15
Duplicate of #69

**Comment by iamzhout** [comment] 2015-11-20 01:54
suggest to reference atom's implementation, by using **strict-ssl = false**
https://atom.io/docs/v1.0.0/getting-started-installing-atom#setting-up-a-proxy

**Comment by joaomoreno** [comment] 2015-11-20 08:50
This might not be a dupe after all, thanks @iamzhout!

**Comment by iamzhout** [comment] 2015-11-20 09:02
@joaomoreno  Welcome, hope this issue could be fixed soon :-) otherwise many corporate users may not be able to install extensions and make full use of vscode.

**Comment by RobertoMD** [comment] 2015-11-23 11:42
Same issue here, but with a corporate proxy and authentication (no certificate). I get a getaddrinfo ENOTFOUND marketplace.visualstudio.com vmarketplace.visualstudio.com:443 (although I'm able to check & install upgrades with http_proxy and https_proxy env variables).

**Comment by timothymschier** [comment] 2015-11-30 04:49
Same issue here, with the same error as @RobertoMD: 
> getaddrinfo ENOTFOUND marketplace.visualstudio.com vmarketplace.visualstudio.com:443
Have set http.proxy and https.proxy settings values. VS Code updates work fine; only Extensions Marketplace seems broken.

**Comment by ericherdzik** [comment] 2015-12-01 15:30
+1

**Comment by joaomoreno** [comment] 2015-12-01 17:21
eaa5bcf introduces a new configuration setting `http.proxyStrictSSL` which when set to false will make the request bypass certificate chain validation

**Comment by simonech** [comment] 2015-12-08 12:55
Will this be in Dec 2015 milestone?

**Comment by joaomoreno** [comment] 2015-12-09 09:14
Yes it will.

**Comment by garystorey** [comment] 2015-12-10 17:25
How do I enable this setting?  Currently running v0.10.3

**Comment by iamzhout** [comment] 2016-01-05 01:41
NOK for me for 0.10.6, also reported in [issue 69 thread](https://github.com/Microsoft/vscode/issues/69#issuecomment-168864832)

**Comment by iamzhout** [comment] 2016-01-05 01:45
I do have added ```"http.proxyStrictSSL":false``` in my User Settings configuration, as below picture shows.

![20160105_vscode_user_setting](https://cloud.githubusercontent.com/assets/14846203/12105548/cc12701c-b390-11e5-9928-58eeed452b9c.PNG)

**Comment by joaomoreno** [comment] 2016-01-05 08:54
@iamzhout did you apply [this workaround](https://github.com/Microsoft/vscode/issues/69#issuecomment-168728904)?

**Comment by iamzhout** [comment] 2016-01-05 09:00
@joaomoreno Yes, I have applied this patch, and restarted vscode, still the same error.

![20160105_vscode_main_js](https://cloud.githubusercontent.com/assets/14846203/12111093/b67d719c-b3cd-11e5-8010-2b04f3b79e0b.PNG)

**Comment by joaomoreno** [comment] 2016-01-05 09:02
Can you somehow show me how I can reproduce your case? Eg: how to set up an untrusted proxy?

**Comment by iamzhout** [comment] 2016-01-05 09:33
@joaomoreno hmm, I think this should be something like SSLStrip, by replacing the https cert from original website to private ones, like [this tool](http://sectools.org/tool/sslstrip/) shows, though I didn't tried this myself. 

Anyway, the ```strict-ssl=false``` [setting for Atom](https://atom.io/docs/v1.3.0/getting-started-installing-atom#setting-up-a-proxy) does works well, so I suggest to refer to the Atom project to see if we can find some clue.

**Comment by joaomoreno** [comment] 2016-01-05 10:54
Atom's implementation is similar to ours.

I've just spent one hour trying to set up this scenario on my dev machine and yielded no significant results. I would love if someone can provide me an environment in which I can reproduce this and fix it myself. Maybe some of you guys have proxies which I can use?

**Comment by iamzhout** [comment] 2016-01-05 11:42
@joaomoreno there is of course no way to give my company proxy to you, as you can not access.
I think this problem for a while and maybe there are some ways we can try:

1. tell me if there is way to get more detailed debug info, so I can collect more info for your analysis.

2. if it will not take you so much trouble, would you like to try this [wallproxy](https://github.com/wallproxy/wallproxy), as it will do https cert replacement, and *maybe* can reproduce this error. You can refer this [tutorial](https://code.google.com/p/wallproxy/wiki/Tutorial2) on how to setup a wallproxy server/client. (you can use google translate to make this tutorial from Chinese to English)

If there is anything I can do to help, please just tell me.

/Tao

**Comment by bleggett** [comment] 2016-01-07 15:56
Can confirm that
* the fix in #69 doesn't work for me.
* the proxyStrictSSL setting doesn't seem to make a difference.
* the Atom setting works for me in Atom

Our corp proxy is Triton Websense, and that's the extent of what I know about it, other than that it consistently interferes with Node apps using SSL.

**Comment by dogfish182** [comment] 2016-01-07 16:39
this one is driving me mad as well. We use zscaler. What I have done 

initially I was getting 'unable to get local issuer certificate' when even trying to choose 'install extensions' bypassing .visualstudio.com at zscaler for ssl inspection fixed that and I could list extensions. 

now I just get the error one step later. 

using 

"http.proxyStrictSSL": false 

in settings.json does nothing. 

I logged a call with zscaler as well to see if they could assist. Same technique what I've done above seems to work fine for atom and sublime text so I think this is a vscode problem.

**Comment by joaomoreno** [comment] 2016-01-07 17:14
Ok guys, this is embarrassing. :dizzy_face: 

Just like #69, this issue wasn't correctly fixed. Pushing a definite fix right now.

**Workaround** until the next release:

1. Launch Code in Administrator mode.
2. In Code, open the `C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\electron-main\sharedProcessMain.js` file.
3. Use the **Find Widget** (<kbd>Ctrl F</kbd>, <kbd>⌘F</kbd> to replace the only occurrence of `http.proxy.strictSSL` with `http.proxyStrictSSL`.
4. Save and restart Code.

**Comment by dogfish182** [comment] 2016-01-07 17:39
I've just tried this and no luck for me. 

after following your instructions, saving and restarting code I get the same issue. print screen attached showing after I reopened it. edited line included as well as the error. 

![2016-01-07_18-35-46](https://cloud.githubusercontent.com/assets/5390419/12177701/d68119de-b56d-11e5-9a9d-d92e1bdca938.png)

**Comment by iamzhout** [comment] 2016-01-08 00:43
@joaomoreno  tried and also not work for me after the workaround, the same to @dogfish182 

seems it would be better to wait a while to verify the patch before closing issue.

**Comment by joaomoreno** [comment] 2016-01-08 08:25
@dogfish182 @iamzhout By *not working* what do you mean? What error do you see? Did you also set the configuration `http.proxyStrictSSL` to `false` in your configuration settings?

**Comment by iamzhout** [comment] 2016-01-08 08:32
@joaomoreno  for me, still the same error message saying "unable to verify the first certificate". 

![20160105_vscode_unable_certificate](https://cloud.githubusercontent.com/assets/14846203/12105415/8d1ca4fa-b38f-11e5-80e9-31eccb1e9902.PNG)

I do have set ```"http.proxyStrictSSL": false```
![20160105_vscode_user_setting](https://cloud.githubusercontent.com/assets/14846203/12105548/cc12701c-b390-11e5-9928-58eeed452b9c.PNG)

**Comment by dogfish182** [comment] 2016-01-08 08:34
@joaomoreno I've included a screenshot 2 replies above yours of both the suggested change and the error message in one screen. Note that after making the change above, I restarted the application and re-opened it to that page to capture the error. 

the error at the top of the screenshot shows 'error unable to get local certificate' which is what I have seen since the initial install of this product. 

Initially I was receiving this error when even attempting to LIST extensions for install. Then I went to zscaler and put in an SSL bypass check for the entire visualstudio.com domain. Now I can list the extensions to install and I can also grab the readme etc. However once I select the extension to install, I immediately fail out. I feel this is an important point to note, because I was able to see some difference after whitelisting the visualstudio domain as bypass. no idea what it means, but I had figured the issue resolved as it let me progress.

**Comment by iamzhout** [comment] 2016-01-08 08:39
@joaomoreno I noticed below stack trace in developer console, but seems not of so much information.

```
unable to verify the first certificate: Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
unable to verify the first certificate: Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
```

**Comment by joaomoreno** [comment] 2016-01-08 08:43
Both of you definitely have different issues.

@dogfish182 Yours definitely sounds like a separate issue, mainly due to the message `unable to get local issuer certificate`. I've moved it to #1862.

@iamzhout Argh, I'm running out of ideas. You get the error when you browse extensions, or when you try to install one?

It would really be helpful if someone could help me setup a scenario in which I could reproduce this...

**Comment by iamzhout** [comment] 2016-01-08 09:18
@joaomoreno should be the time when browsing extensions, 

my OS is windows 7, the steps to reproduce is as below:
* open vscode
* ```ctrl + shift + p``` -> type ```install extension``` -> press enter

then the error will occur. The proxy I configured for vscode is the same to Atom.

Is it possible that I can do something to capture more detailed log for your analysis?

**Comment by joaomoreno** [comment] 2016-01-08 10:57
Ok, I think I got it. I was able to get the same untrusted error using the [Charles](https://www.charlesproxy.com/documentation/proxying/ssl-proxying/) proxy software.

![image](https://cloud.githubusercontent.com/assets/22350/12195919/46beddac-b5fb-11e5-95c8-e8b1e6379fe1.png)

I was then finally able to figure out why the setting was being ignored. Pushed a fix.

Can I ask you to test this out? I've uploaded [a build with the fix in](https://ticino.blob.core.windows.net/build/f88ab736b3382efa2cfa409f80935457c4c6179e/VSCode-win32.zip?st=2016-01-07T10%3A55%3A00Z&se=2016-02-09T10%3A55%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=ogYQg4is25EfNA%2BrIEPLOiPrbZ71h7iBRNuBdNFdmu4%3D). Please close any Code instances, extract it and run the `Code.exe` within it. Let me know how it goes.

**Comment by bleggett** [comment] 2016-01-08 22:18
Still get the "unable to verify the first certificate" error with the new build. I've never gotten the error about the cert being self-signed.

Can I enable logging or get some kind of debug output for you? That might help.

**Comment by iamzhout** [comment] 2016-01-11 01:21
@joaomoreno Your fix build just works for me, now extensions could be installed successfully, thanks for your great work!

**Comment by joaomoreno** [comment] 2016-01-11 11:56
@iamzhout Awesome, many thanks for the confirmation!

@bleggett You're absolutely right, I didn't realise these options could be used independently. I assume you set your proxy address via the `HTTP_PROXY` and `HTTPS_PROXY` environment variables? Give [this build](https://ticino.blob.core.windows.net/build/e48215776341e68c6f15a9319fcfa514fdb09532/VSCode-win32.zip?st=2016-01-10T11%3A55%3A00Z&se=2016-01-17T11%3A55%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=dZCkPenX5lP7f2nvXq11Uj5NWHvBwsL7r5%2B3Z8nU93c%3D) a try and let me know if it solves the issue for you.

**Comment by bleggett** [comment] 2016-01-11 15:06
@joaomoreno That build doesn't work either, sadly.

No, those variables are not set on my box. Since I'm in a corporate setting I have an IT department that apparently doesn't expect me to have to know the proxy URL, so with other node-based stuff I've not had to set a proxy http/https URL to get things working, just disable strict SSL. 

I assume this has worked with other node-based stuff because strictSSL = false has been a global flag that disables strict cert checking regardless of the other proxy settings.

**Comment by FloMaetschke** [comment] 2016-01-11 15:55
@joaomoreno I have set http.proxy, https.proxy and http.proxyStrictSSL = false,

I want to install extensions:
CTRL + P: enter: > inst .. wait a moment, select "Extensions: Install Extensions".

With the latest decembe release: I get a blue loading bar after a few seconds it says: 
"ERROR Unable to verify the first certificate"

With your first build you posted here: 
https://github.com/Microsoft/vscode/issues/155#issuecomment-169963541

I just get an endless loading bar and nothing happens.

With your second build you posted here:
https://github.com/Microsoft/vscode/issues/155#issuecomment-170519605

I just happens nothing, it instantly closes the prompt without any result.

Any idea?

**Comment by joaomoreno** [comment] 2016-01-12 08:46
@bleggett Thanks for the explanation. Sorry for all the ping-pong with the builds and all, but I just can't seem to reproduce your scenario, so we'll have to try to catch it this way.

I've noticed that we can also set `rejectUnauthorized` to `false` when making a non-proxied HTTPS request. [Here's a new build](https://ticino.blob.core.windows.net/build/20ff90c932596961c710ae7d0441705694e2b0a9/VSCode-win32.zip?st=2016-01-11T08%3A46%3A00Z&se=2016-01-18T08%3A46%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=i0EWsjejoKGWGrQdKkA9TLH%2Fm7b5XC9wO7EBuXIaZEc%3D) that does that, do you mind giving it a try? Don't forget to set `http.proxyStrictSSL` to `false`.

**Comment by joaomoreno** [comment] 2016-01-12 08:58
@FloMaetschke moved your issue to #1942

**Comment by bleggett** [comment] 2016-01-12 15:58
@joaomoreno No problem at all, willing to test whatever you need, thanks for sticking with this.

So the new build finally shows me the list of extensions to install, so that part works. Trying to install or click on one of them gives me the same "unable to verify first cert" error I had before.

So that's an improvement, it just doesn't seem to be applied to package downloads/install.

**Comment by aldanor** [comment] 2016-01-12 17:27
Interesting: I get this:
```
getaddrinfo ENOTFOUND 10.170.129.90:8080 10.170.129.90:8080:8080
```
but only when actually trying to install the extension (browsing the list works just fine).

I've set `http.proxy` to `http://10.170.129.90:8080`, `http.proxyStrictSSL` to `false` and fixed `http.proxy.StrictSSL` typo as recommended above, with no success though -- this error message always shows up. Any ideas on how to fix that?

**Comment by joaomoreno** [comment] 2016-01-13 14:44
@aldanor This seems to be the issue reported when the bug was reopened. Please give [this build](https://ticino.blob.core.windows.net/build/0e17d138ca2e7f5a342e049836a2b2b0beb54685/VSCode-win32.zip?st=2016-01-12T14%3A43%3A00Z&se=2016-01-19T14%3A43%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=8F9%2BNvY94xaMZKEtGfXDc4QEXH%2Fn26dXs1%2BnMIqjHm8%3D) a try. Let me know if you still get the issue.

**Comment by joaomoreno** [comment] 2016-01-13 14:44
@bleggett Excellent. Try [this one](https://ticino.blob.core.windows.net/build/0e17d138ca2e7f5a342e049836a2b2b0beb54685/VSCode-win32.zip?st=2016-01-12T14%3A43%3A00Z&se=2016-01-19T14%3A43%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=8F9%2BNvY94xaMZKEtGfXDc4QEXH%2Fn26dXs1%2BnMIqjHm8%3D) now.

**Comment by jchadwick** [comment] 2016-01-13 15:29
This worked for me.  Thanks!

**Comment by bleggett** [comment] 2016-01-13 16:12
@joaomoreno Woot, thanks, that works fine.

**Comment by joaomoreno** [comment] 2016-01-13 16:12
:fireworks: Fix will be out with the next release of VS Code.

Many thanks to all that put up with this ping-pong! :beers:

**Closed by joaomoreno** 2016-01-13 16:12 UTC
Labels: help wanted

**Comment by iccfish** [comment] 2016-01-21 07:58
@joaomoreno I'm now issue the same proxy problem, and have read all posts. But the build you mentioned above can't be downloaded, it says 'AuthenticationFailed'. Could you please provider a new package?

**Comment by joaomoreno** [comment] 2016-01-21 08:29
[Here you go](https://ticino.blob.core.windows.net/build/0e17d138ca2e7f5a342e049836a2b2b0beb54685/VSCode-win32.zip?st=2016-01-20T08%3A28%3A00Z&se=2016-01-26T08%3A28%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=Xit%2Bxckw2%2BoMzH%2FNjkiBWOLzP5Th%2Ba21mE7hBTGEdYU%3D).

**Comment by iccfish** [comment] 2016-01-21 08:30
Got it. Thanks! :+1:

**Comment by nadeem-aslam** [comment] 2016-03-02 21:25
Same issue, can I have the build that works?

**Comment by joaomoreno** [comment] 2016-03-02 22:10
@nadeem-aslam This is already fixed in 0.10.8.

**Comment by nadeem-aslam** [comment] 2016-03-02 22:39
Updated and works great!

**Comment by Healforgreen** [comment] 2016-03-17 12:29
For anyone new doesn't want to sift through all the posts.  In 0.10.11, this works:

Set `"http.proxyStrictSSL": false` in user settings in order to install extensions.

**Comment by joaomoreno** [comment] 2016-03-17 13:28
Motion granted.
