### ISSUE TITLE
The menu bar has a scrollbar on first open that spans the screen height

### ISSUE THREAD

**Issue by ChaseGrant** [microsoft/vscode#138829] opened 2021-12-10 08:24 UTC
Issue Type: <b>Bug</b>

Just start the app and click the file menu

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|29.94GB (9.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
xslt-xpath|del|0.3.16
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
leet-html|Eld|1.1.1
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
dotnet-test-explorer|for|0.7.7
copilot|Git|1.7.4016
go|gol|0.29.0
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
output-colorizer|IBM|0.1.2
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.0.0
vscode-codemetrics|kis|1.24.0
manictime-extension|Man|1.0.0
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
vscode-edge-devtools|ms-|1.4.2
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
cpptools|ms-|1.7.1
live-server|ms-|0.2.11
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
vs-keybindings|ms-|0.2.1
debugger-for-edge|msj|1.0.15
embrace|myc|1.0.0
vscode-sql-formatter-mod|nmr|1.4.5
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
vscode-versionlens|pfl|1.0.9
vscode-sort-json|ric|1.20.0
partial-diff|ryu|1.4.3
vscode-taskexplorer|spm|2.5.7
sass-indented|syl|1.8.18
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.8.0
quokka-vscode|Wal|1.0.431

</details>

**Comment by ChaseGrant** [comment] 2021-12-10 08:25
![image](https://user-images.githubusercontent.com/28922461/145541562-5a075fee-dcb3-4d45-8815-3a1b6f52ec07.png)

**Comment by gjsjohnmurray** [comment] 2021-12-10 12:58
/duplicate of #138110 and scheduled to be fixed in a recovery release

**Closed** 2021-12-10 12:58 UTC
Labels: *duplicate, new release
