### ISSUE TITLE
TypeScript intellisense auto import feature adds the import to a duplicate file (different casing)

### ISSUE THREAD

**Issue by rssfrncs** [microsoft/vscode#71990] opened 2019-04-09 10:01 UTC
- VSCode Version: Tested in 1.32, 1.33 and insiders.
- OS Version: Windows 10

Steps to Reproduce: Please see attached GIF.

![vscode-auto-import-bug](https://user-images.githubusercontent.com/7808978/55791619-cfe5c380-5ab6-11e9-81b6-abed334acfda.gif)

1. Type name of exported function in a file
2. Click yellow helper box to auto import from correct file
3. Observe how code makes the import in a duplicate file (different casing)

Does this issue occur when all extensions are disabled?: No but can't use typescript intellisense features

**Comment by deylin** [comment] 2019-06-12 08:05
@mjbvz , any news on this issue?

**Comment by chibibiscuit** [comment] 2019-07-11 14:26
I can confirm that this is still happening in the July release (v 1.36.1), and that it occurs when no extensions are enabled.  My specific observations:

![image](https://user-images.githubusercontent.com/4705389/61057475-0505f880-a3bb-11e9-9f45-2628e2337d43.png)
When using CTRL-P to open a file, it is displaying several files _twice_ - Once as `UI/filename.ts`, once as `ui/filename.ts`. For this example, the *actual* file path is capitalized (`UI/filename.ts`). Selecting either one  will load the file in its own tab. However, using VSCode's Auto Import feature at any time while editing the one in the lowercase tab will:

Open the other file `UI/filename.ts` in the background. (Keep in mind that this is the file saved on disk, so chances are it does not contain the changes you made to prompt the automatic addition of the Import string. It is unmodified from what exists on disk)
Add the import string to `UI/filename.ts`. (We now have two unsaved files open)
![image](https://user-images.githubusercontent.com/4705389/61057420-e7389380-a3ba-11e9-95c7-16aca5593152.png)
This also does something bizarre to the file you originally opened, which causes the intellisense to break.
![image](https://user-images.githubusercontent.com/4705389/61057750-88274e80-a3bb-11e9-9099-4b8e4222141c.png)
Saving causes more oddities, because now you have two copies of the same file which are out of sync.
![image](https://user-images.githubusercontent.com/4705389/61057848-b60c9300-a3bb-11e9-92ff-9e92640237f8.png)

NOW - Something I just found out while experimenting with this. I was able to clear my recently opened files, and it removed the duplicates from my Ctrl-P Quick Open panel.

`Ctrl-Shift-P` > `File: Clear Recently Opened`

There is still a definite bug here, likely related to how VSCode handles filename case sensitivity - but removing the duplicate entries seems to for the moment be a decent workaround for my version of the issue. I hope this helps someone, this issue was EXTREMELY frustrating.

**Comment by s0nqr3** [comment] 2019-08-09 07:59
As of the 9th of August 2019, this issue is sill present.
Fixed by editing sub-folders to **_only_** contain lower case lettering.

i.ex: 
**works with**: ```using/lowercase/lettering```
**does not work with**: ```Upcased/Folder/Structure```
**does not work with**: ```camelCase/folderStructure```

**Info:**
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

If you wish to keep your Upcased- or camelCased folder structure, only fix I found at the moment is to disable the typescript auto import option altogether.
Intellisense seems to be working fine when manually writing imports in either of these cases.

**Disable Typescript auto import by:**
- settings (_ctrl+,_)
  - search for "**autoimport**"
    - disable "**Typescript > Suggest: Auto Imports**" option

**Comment by d00lar** [comment] 2019-08-21 05:52
same here - any news on this ? i searched half od internet to find here  that that is least possible option for me - bug in vscode :/

**Comment by chibibiscuit** [comment] 2019-08-21 16:30
@d00lar Have you tried the steps in my post to clear your recently opened files? Doing that, and then restarting VS Code was enough to resolve the problem for me, with no recurrence since.

**Comment by d00lar** [comment] 2019-08-23 09:13
yep for me it is now also fine thanks !

**Comment by deylin** [comment] 2019-08-27 08:45
@chibibiscuit , the workaround you suggest does not work in my case. I cleared the 'recently used files', but any quick-fixes are written to the 'old' file (with the old casing).

**Comment by d00lar** [comment] 2019-09-10 07:18
yep for me it again started to happenigng. this workaround help for some time 1-3days in my case
in new update also

**Comment by d00lar** [comment] 2019-09-24 07:44
still nothing ?
the pernament 'workaround fix' is to use all folder names by uppercase in project but this is not solution... strange that only 6pepole here participate - all my colleagues from work have same issue so it is global for shure!

**Comment by swift502** [comment] 2019-10-24 18:27
Same here. Extremely annoying. Intellisense also breaks when the second tab opens.
VSCode **is** open source. This sounds like a challenge.

**Comment by antoinecfmws** [comment] 2019-11-01 18:12
Same here, my experience with it, if you have an uppercase folder name in the path that you are working with it seems to always open a new tab when trying to import. However, when a new window of vscode is open with the sub-folders being the parent with only small case letters, the import works fine. Any workarounds for now?

**Comment by mjbvz** [comment] 2022-12-05 23:23
Duplicate of #55655

**Closed by mjbvz** 2022-12-05 23:23 UTC
Labels: bug, javascript
