### ISSUE TITLE
Explorer pane invalidates while in edit mode; papercut

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#132401] opened 2021-09-05 19:27 UTC
Issue Type: <b>Bug</b>

The Explorer pane invalidates content _while_ an Explorer element is in edit mode (e.g. for renaming a file). This cancels edit mode and all keystrokes then go into the Explorer tree item set, instead of the previously edited explorer _item_ itself.

This can lead to involuntary deleting of data.

The expectation is that the explorer pane does not get refreshed at all while it is in edit mode (it's blacked out anyway, only the edited item is "visible", so nobody will be bothered by the blacked out content not updating). Obviously, once out of edit mode, the explorer pane should refresh.

To experience this,  create a new folder, place the bash script below inside, and open the folder in VS Code:

```
#!/usr/bin/env bash

sleep 10s

while true ; do
    # produce fresh files with names such as "2021-09-05T21:15:20,438239326+02:00"
    touch $(date --iso-8601=ns)

    sleep 1s
done
```

Open a terminal and run the bash script; the intent is to keep invalidating the folder content.

Now press "F2" to rename any one file that is getting produced ... and notice that the rename operation is cancelled, because the explorer pane gets refreshed.

If editing includes pressing the "Del" key, and the timing is right, it's not a character in the file name that is removed, but the explorer item itself. That is philosophically close to "data loss", IMHO.

In real life, the bash script is a (long running) build process, started in a terminal, which keeps producing build output into child folders (which causes the explorer pane to refresh).

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.13.13-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2903)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|31.31GB (18.23GB free)|
|Process Argv|. --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-drawio|hed|1.6.2
rest-client|hum|0.24.5
bash-ide-vscode|mad|1.11.0
rust-analyzer|mat|0.2.727
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
even-better-toml|tam|0.14.2
vscode-lldb|vad|1.6.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn478:30356813
pythonvspyt187cf:30361754
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by JacksonKearl** [comment] 2021-09-08 01:58
Duplicate of https://github.com/microsoft/vscode/issues/112293. 

> If editing includes pressing the "Del" key, and the timing is right, it's not a character in the file name that is removed, but the explorer item itself. That is philosophically close to "data loss", IMHO.

I believe we would prompt about irrecoverable deletion in the cases where the file is not on git or moved to trash?

**Closed by JacksonKearl** 2021-09-08 01:58 UTC

**Comment by shoffmeister** [comment] 2021-09-08 14:34
Part of the annoyance is that edit mode gets cancelled. Once edit mode does not get canceled due to the refresh, the problem with the "sort of data loss scenario" ("Del" hits the explorer item, not the text) disappears for good.

Generally, IMHO, the vscode behaviour for "Del" on Explorer pane items is sane and feature-complete. Adding more confirmation dialogs on top what already exists there would annoy. The problem really is the "explorer pane refresh cancels edit mode" part.
