### ISSUE TITLE
Extension overlays are being stripped from the screen

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#16019] opened 2016-11-24 11:47 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (731c1b034ed009991c29f9ccaf035c236458e3c6, 2016-11-23T07:09:34.296Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|EditorConfig|EditorConfig|0.3.4|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|vscode-subword-navigation|ow|1.1.5|
|Ruby|rebornix|0.10.3|
|vscode-icons|robertohuertasm|4.0.2|
|annotator|ryu1kn|0.10.1|
|cucumber|stevejpurves|0.9.6|
|wallaby-vscode|WallabyJs|1.0.30|

---

I'm not sure if this is a bug in the Wallaby extension or VSCode.

Steps to Reproduce:

1. Clone this repo: https://github.com/massimocode/javascript-exercises
2. NPM install
3. Make sure you have the wallaby extension installed in VS Code
4. Open the file spec\core-javascript\arrays.spec.js
5. Start the wallaby extension
6. You should see coloured dots appear on the side. However, after a few seconds they disappear. Make a change (i.e. press space or remove a semicolon or something) and they appear again. Again, after a few seconds they disappear.

**Comment by massimocode** [comment] 2016-11-24 11:54
Some further information. This issue does not occur when using the Wallaby JS extension on the latest stable version of VS Code:
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)

**Comment by ArtemGovorov** [comment] 2016-11-24 13:06
Thanks @massimocode, I have had a look and managed to reproduce the issue as well. To make it easier to reproduce without having to install wallaby.js, and to provide a title that reflects what exactly is going on, I have [reported it here](https://github.com/Microsoft/vscode/issues/16023). Once it's fixed, I hope the issue with gutter icons should be fixed as well.

**Comment by alexandrudima** [comment] 2016-11-30 09:41
@ArtemGovorov Since you pointed out the root cause of this issue is #16023, I'm going to close this for now.

**Closed by alexandrudima** 2016-11-30 09:41 UTC
