### ISSUE TITLE
Regression: JavaScript Indentation drifts on paste

### ISSUE THREAD

**Issue by patrickhulce** [Microsoft/vscode#36294] opened 2017-10-15 05:21 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
vscode-new-file|dku|3.1.1
tslint|eg2|1.0.11
cpptools|ms-|0.13.1
vscode-icons|rob|7.15.0
vscode-open-in-github|sys|1.6.0

---

Steps to Reproduce:

1. Select a section of javascript with indentation including a newline
2. Paste

![animation](http://g.recordit.co/O9y91vJDbZ.gif)

Reproduces without extensions: Yes
Reproduces in insiders: Yes 1.18 (989c40066d124cde846cf5ded8364251246e100e)

Previously, the indention was as expected on paste. My editor.formatOnPaste is explicitly set to false in my user settings. A basic rule of thumb seems to apply that selecting a text range and pasting once should be a noop. Is there something I'm missing or a new setting I need to disable?

UPDATE: it's worth nothing that the same indentation creep problem does not apply to lines within the same block

**Comment by mjbvz** [comment] 2017-11-15 19:45
@patrickhulce  Can you please share some source code that reproduces this issue

**Comment by patrickhulce** [comment] 2017-11-15 19:59
sure @mjbvz, here's a sample I was just able to reproduce with a screenshot for selection emphasis

![image](https://user-images.githubusercontent.com/2301202/32857324-460721e6-c9fc-11e7-8c95-404a053cb2d2.png)


<details>
<summary>See code
</summary>

```js
describe('test', () => {
  it('test 1', () => {

  }) // select from here ->

  it('should be fine', () => {
    // but it is not :(
  }) // to here ->
})
```

</details>

**Comment by rebornix** [comment] 2017-11-28 00:32
https://github.com/Microsoft/vscode/issues/36294, https://github.com/Microsoft/vscode/issues/29896, https://github.com/microsoft/vscode/issues/38833 share the same root cause: empty lines are not handled gracefully. I pushed a fix which makes this specific case work but it may not work for all cases ;)

**Closed by rebornix** 2017-11-28 00:32 UTC
Labels: bug, editor-autoindent, javascript
