### ISSUE TITLE
Truncate notification buttons that get too long

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#44584] opened 2018-02-27 14:39 UTC
#44319

![image](https://user-images.githubusercontent.com/2193314/36734628-eecb6e8a-1b88-11e8-81fa-a239df4db35b.png)

**Comment by bpasero** [comment] 2018-02-27 14:53
/duplicate of https://github.com/Microsoft/vscode/issues/44538

**Closed** 2018-02-27 14:53 UTC
Labels: *duplicate, workbench-notifications
