### ISSUE TITLE
Incorrect relative path to image when drag and drop image 

### ISSUE THREAD

**Issue by contentedweb** [microsoft/vscode#166646] opened 2022-11-17 22:24 UTC
Type: <b>Bug</b>

When I drag and drop an image into a markdown file with "shift" pressed I expect to get a path like this:

```
![](../../assets/images/fire-sky.jpg)
```

But instead the relative path goes to the root of the file system, not the website and I get this:

```
![](../../../../../../../../../../C:/Users/atana/Documents/Websites/eleventy/website-v2/src/assets/images/fire-sky.jpg)
```

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.21GB free)|
|Process Argv|--crash-reporter-id 4e25fae8-f596-4229-89a4-42f43e194d43|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
vscode-npm-script|eg2|0.3.29
nunjucks-template|ese|0.5.1
vscode-pull-request-github|Git|0.54.1
search-node-modules|jas|1.3.0
vscode-edge-devtools|ms-|2.1.1
powershell|ms-|2022.11.0
pwa-studio|PWA|1.2.1
shopify-liquid|sis|3.1.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by mjbvz** [comment] 2022-11-17 23:02
Duplicate of #165352

Should already be fixed in VS Code insiders

**Closed by mjbvz** 2022-11-17 23:02 UTC
