### ISSUE TITLE
警告条一直在跳动，没法关闭。

### ISSUE THREAD

**Issue by semmy2010** [Microsoft/vscode#20684] opened 2017-02-16 02:25 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.8.0|
|sky-react-create-snippet|lulinmemeda|0.0.3|
|vscode-icons|robertohuertasm|7.2.0|
|vue|seanwash|0.4.2|
|guides|spywhere|0.6.1|
|react-beautify|taichi|0.3.0|

---

Steps to Reproduce:
警告条一直在跳动，没法关闭。
![_20170216102606](https://cloud.githubusercontent.com/assets/4402907/23004534/138b3518-f432-11e6-8f57-0055192169bb.png)
1.
2.

**Comment by ttn10** [comment] 2017-02-16 02:27
請說英語 👍

**Comment by mjbvz** [comment] 2017-02-16 02:41
Closing as duplicate of #20685

**Closed by mjbvz** 2017-02-16 02:41 UTC
