### ISSUE TITLE
Configurable path to *jsconfig.json* file for the project

### ISSUE THREAD

**Issue by xeho91** [microsoft/vscode#106136] opened 2020-09-04 18:23 UTC
**Hi VS Code Team!**

My team is using a very organised project directory structure. For this reason, we are putting all of the configuration files _(ESlint, Prettier, etc)_. inside the `./config/` - the folder at the root of the project(s) directory.

We are also using `jsconfig.json`, however, we would like to be able to put this file inside `./config/` folder, to make our project file structure more clean and organized. In other words, give us a possibility to move this file away from the root directory.

**I propose to create an option to modify a path to `jsconfig.json` inside `./.vscode/settings.json`.**

The same way we've been able to modify path for Prettier config file with:
```json
"prettier.configPath": "./config/.prettierrc.js",
"prettier.ignorePath": "./config/.prettierignore",
```
and ESLint with:
```json
"eslint.options": {
	"configFile": "./config/.eslintrc.js",
},
```

**Comment by mjbvz** [comment] 2020-09-10 23:34
Duplicate of https://github.com/microsoft/TypeScript/issues/33094

**Closed by mjbvz** 2020-09-10 23:34 UTC
