### ISSUE TITLE
Open file slow

### ISSUE THREAD

**Issue by drinktee** [Microsoft/vscode#10879] opened 2016-08-24 09:17 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.4.0
- Macbook pro 2015, i5 , 8G
Steps to Reproduce:

1.just open a source file  xxx.go
2.I feel it's slower than earlier version like 1.3

**Comment by sandy081** [comment] 2016-08-25 13:16
@drinktee Can you please try by disabling extensions from command line  'code  --disable-extensions`. How big is the file and the project? Also can you provide us any metric and diagnostics like how much slow it is and when this happens would you be able to run a CPU profile from the developer tools (help > toggle developer tools) to see where we spend so much time?

**Comment by dbaeumer** [comment] 2016-09-05 08:55
@drinktee I will close the issue since we haven't received a response. Please ping if you still see the issue with steps on how to reproduce the problematic behavior.

**Closed by dbaeumer** 2016-09-05 08:55 UTC
Labels: freeze-slow-crash, needs more info
