### ISSUE TITLE
Error: ListError [SettingsTree] Invalid index 2

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154761] opened 2022-07-11 07:46 UTC
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=a0cdd060-8c95-1810-22a1-fb80705284c5):
```
Error: ListError [SettingsTree] Invalid index 2
[at M.setFocus in src/vs/base/browser/ui/list/listWidget.ts:1564:11](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listWidget.ts#L1564:11)
[at M.setFocus in src/vs/base/browser/ui/tree/abstractTree.ts:1282:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/abstractTree.ts#L1282:9)
[at x.onViewPointer in src/vs/base/browser/ui/list/listWidget.ts:680:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listWidget.ts#L680:13)
[at x.onViewPointer in src/vs/base/browser/ui/tree/abstractTree.ts:1163:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/abstractTree.ts#L1163:17)
[at <anonymous> in src/vs/base/common/event.ts:128:117](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L128:117)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at <anonymous> in src/vs/base/common/event.ts:90:84](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L90:84)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at HTMLDivElement.m in src/vs/base/browser/event.ts:37:41](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/event.ts#L37:41)
```

**Comment by rzhao271** [comment] 2022-08-03 23:12
Duplicate of #148439

**Closed by rzhao271** 2022-08-03 23:12 UTC
Labels: error-telemetry
