### ISSUE TITLE
Notebook outline for code cells does not follow the order of the cells

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#113999] opened 2021-01-07 17:07 UTC
Version: 1.53.0-insider (user setup)
Commit: 4fe3f75c6d3d88a19c47f029524172303f1a1a82
Date: 2021-01-06T15:36:33.674Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Install python extension
2. Open the attached file
[runmany.zip](https://github.com/microsoft/vscode/files/5782950/runmany.zip)

3. Open the outline view
4. Source is not in the correct order. I get this:

![image](https://user-images.githubusercontent.com/19672699/103921733-b593ac00-50c7-11eb-9819-74e09c015d05.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by claudiaregio** [comment] 2021-01-15 20:43
Dupe of https://github.com/microsoft/vscode/issues/114220

**Closed** 2021-01-15 21:12 UTC
Labels: notebook, outline
