### ISSUE TITLE
Path Autocomplete Crashes

### ISSUE THREAD

**Issue by jjacode** [Microsoft/vscode#45993] opened 2018-03-16 17:19 UTC
Issue Type: <b>Bug</b>

Issue:
The extension 'Path Intellisense' by Christian Kohler crashes randomly but takes down other Intellisense as well.

Thinking maybe this was an error with the extension I uninstalled it and tried 'Path Autocomplete' by Mihai Vilcu instead. But this has the same issue. So, now I'm reporting this as a bug with VS Code's Intellisense extension ability.

Likely cause:
When using path related Intellisense, backspacing to a previous folder then re-adding the slash quickly. Ex:

1. `import MyComponent from '../../components/MyComponent/MyC`
2. `import MyComponent from '../../components/MyComponent`
3. `import MyComponent from '../../components/MyComponent/`

This doesn't always happen, but it seems like that pattern, followed quickly trips up Intellisense and then all Intellisense is gone until rebooting VS Code. :(

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|7.88GB (0.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
prettier-vscode|esb|1.2.2
path-autocomplete|ion|1.8.1

</details>
Reproduces only with extensions

**Comment by mikevaleriano** [comment] 2018-03-17 19:43
vscode has a built-in path completion since the last couple updates. 

I've removed path-intellisense and node-intellisense (not sure if that was the name) since the functionality comes included, **BUT** this very same problem happens anyway.

I have a LOT of other extensions installed, and everything worked just fine right until this update where the path intellisense became part of the editor. Now I just sometimes get `An unknown error occurred. Please consult the log for more details.` in the devtools, and I can't find any more info on this.

> Ctrl + Shift + P, Reload Window is now my most used shortcut because of that. =/

**Comment by jrieken** [comment] 2018-03-19 09:21
> ohler crashes randomly but takes down other Intellisense as well.

Can you define crash? Also, please attach readings from the log (F1 > Show Logs > window).

**Comment by mikevaleriano** [comment] 2018-03-19 11:04
I think they meant that intellisense just stops working, there really isn't a crash when it happens.

Right after a `import React from "react";` it stops, and the logs say:

![image](https://user-images.githubusercontent.com/6718750/37592003-1c9af4de-2b4c-11e8-99d6-7c4cdc178faf.png)

**Comment by jjacode** [comment] 2018-03-19 14:21
@jrieken, when I say it crashes I mean that Intellisense stops making suggestions, except for sometimes still offering suggestions for same-document variable/function names, but even that isn't always the case. I'll watch that more carefully next time it crashes.

The logs for window were blank. Here are the logs from ext host.

[2018-03-19 08:07:50.569] [exthost3] [info] extension host started
[2018-03-19 08:07:50.635] [exthost3] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:50.636] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-03-19 08:07:51.204] [exthost3] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:51.204] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-03-19 08:07:52.180] [exthost3] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:52.180] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-03-19 08:07:52.344] [exthost3] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:52.344] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\dbaeumer.vscode-eslint-1.4.7\client\out\extension
[2018-03-19 08:07:52.643] [exthost3] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:52.643] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\esbenp.prettier-vscode-1.2.2\out\src\extension
[2018-03-19 08:07:53.349] [exthost3] [info] ExtensionService#_doActivateExtension ionutvmi.path-autocomplete {"startup":true,"activationEvent":"*"}
[2018-03-19 08:07:53.349] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\ionutvmi.path-autocomplete-1.8.1\out\src\extension
[2018-03-19 08:07:53.468] [exthost3] [info] eager extensions activated
[2018-03-19 08:08:34.423] [exthost3] [info] extension host started
[2018-03-19 08:08:34.452] [exthost3] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:34.452] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-03-19 08:08:34.637] [exthost3] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:34.637] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-03-19 08:08:34.870] [exthost3] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:34.870] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-03-19 08:08:34.897] [exthost3] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:34.897] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\dbaeumer.vscode-eslint-1.4.7\client\out\extension
[2018-03-19 08:08:34.979] [exthost3] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:34.979] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\esbenp.prettier-vscode-1.2.2\out\src\extension
[2018-03-19 08:08:35.212] [exthost3] [info] ExtensionService#_doActivateExtension ionutvmi.path-autocomplete {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:35.212] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\ionutvmi.path-autocomplete-1.8.1\out\src\extension
[2018-03-19 08:08:35.235] [exthost3] [info] eager extensions activated
[2018-03-19 08:08:35.239] [exthost3] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:javascript"}
[2018-03-19 08:08:35.239] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\extension
[2018-03-19 08:08:40.091] [exthost3] [info] extension host started
[2018-03-19 08:08:40.114] [exthost3] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.114] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-03-19 08:08:40.201] [exthost3] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.201] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-03-19 08:08:40.374] [exthost3] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.374] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-03-19 08:08:40.400] [exthost3] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.400] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\dbaeumer.vscode-eslint-1.4.7\client\out\extension
[2018-03-19 08:08:40.483] [exthost3] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.483] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\esbenp.prettier-vscode-1.2.2\out\src\extension
[2018-03-19 08:08:40.726] [exthost3] [info] ExtensionService#_doActivateExtension ionutvmi.path-autocomplete {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:40.726] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\ionutvmi.path-autocomplete-1.8.1\out\src\extension
[2018-03-19 08:08:40.745] [exthost3] [info] eager extensions activated
[2018-03-19 08:08:51.738] [exthost3] [info] extension host started
[2018-03-19 08:08:51.768] [exthost3] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:51.768] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-03-19 08:08:51.902] [exthost3] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:51.902] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-03-19 08:08:52.077] [exthost3] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:52.077] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-03-19 08:08:52.100] [exthost3] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:52.100] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\dbaeumer.vscode-eslint-1.4.7\client\out\extension
[2018-03-19 08:08:52.182] [exthost3] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:52.182] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\esbenp.prettier-vscode-1.2.2\out\src\extension
[2018-03-19 08:08:52.423] [exthost3] [info] ExtensionService#_doActivateExtension ionutvmi.path-autocomplete {"startup":true,"activationEvent":"*"}
[2018-03-19 08:08:52.423] [exthost3] [info] ExtensionService#loadCommonJSModule C:\Users\jason.anderson\.vscode\extensions\ionutvmi.path-autocomplete-1.8.1\out\src\extension
[2018-03-19 08:08:52.451] [exthost3] [info] eager extensions activated
[2018-03-19 08:08:52.455] [exthost3] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"activationEvent":"onLanguage:markdown"}
[2018-03-19 08:08:52.455] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\extension-editing\out\extension
[2018-03-19 08:08:52.480] [exthost3] [info] ExtensionService#_doActivateExtension vscode.markdown-language-features {"startup":false,"activationEvent":"onLanguage:markdown"}
[2018-03-19 08:08:52.480] [exthost3] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown\out\extension

**Comment by jrieken** [comment] 2018-03-19 14:25
likely typescript/javascript

**Comment by jjacode** [comment] 2018-03-19 15:18
Okay, here are logs after the first noticeable error:

Window logs:
[2018-03-19 08:22:58.968] [renderer1] [info] Uninstalling the extension ionutvmi.path-autocomplete-1.8.1 from window 1
[2018-03-19 08:30:35.502] [renderer1] [error] Cannot read property 'match' of undefined: TypeError: Cannot read property 'match' of undefined
	at new MyCompletionItem (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\features\completionItemProvider.js:54:34)
	at TypeScriptCompletionItemProvider.provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\features\completionItemProvider.js:232:26)
	at <anonymous>
[2018-03-19 08:30:52.155] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:31:20.215] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:31:38.122] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:35:36.114] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:39:43.161] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:40:06.017] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:40:20.371] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:43:05.372] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:44:04.489] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:46:23.104] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-19 08:48:45.329] [renderer1] [error] An unknown error occurred. Please consult the log for more details.

ext host logs:
2018-03-19 08:07:42.947] [exthost1] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:javascript"}
[2018-03-19 08:07:42.947] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\extension
[2018-03-19 08:13:11.041] [exthost1] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"activationEvent":"onLanguage:typescript"}
[2018-03-19 08:13:11.041] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\extension-editing\out\extension
[2018-03-19 09:15:34.354] [exthost1] [info] ExtensionService#_doActivateExtension vscode.css {"startup":false,"activationEvent":"onLanguage:scss"}
[2018-03-19 09:15:34.354] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\css\client\out\cssMain

**Comment by mikevaleriano** [comment] 2018-03-20 19:35
Not sure if it matters that much but I was using Windows 10, 64bit and having these issues.

The same messages and initially sluggish behavior appear when I switched to Ubuntu 17.10, but it's no where near that bad. It's just a hiccup when you try to access intellisense once again after a "path" use, but then it becomes normal.

The same errors are there, but intellisense doesn't stop working, it just slows down a little bit, and only once.

**Comment by mjbvz** [comment] 2018-03-23 19:32
Can you try please try the latest insiders build with all extensions disabled. I fixed one of the typescript errors from the logs: https://github.com/Microsoft/vscode/commit/b26862c89b3ee94cad227e821a36e72b89688bbb

**Comment by jjacode** [comment] 2018-03-29 16:42
@mjbvz I've been trying the insider's build all morning. It seems to work now. Whereas my production build of VS Code keeps crashing about every 10 to 15 minutes.

It is commit: 952b2a64

**Comment by jjacode** [comment] 2018-04-13 17:27
It's crashing again. Using

Version | `1.23.0-insider`
Commit | 7c62e560a3e494
Date | 2018-04-13T05:17:33.810Z

All IntelliSense stops working. This is in a create-react-app bootstrapped app.

**Comment by mjbvz** [comment] 2018-04-17 17:06
Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. In vscode with a js/ts file open, run the `TypeScript: Open TS Server logs` command. This should open a log directory with a `tsserver.log` file in it

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by jjacode** [comment] 2018-04-17 21:08
I followed those steps @mjbvz . I have a log file now.

It's about 40k lines and I'm not sure I want to post everything on GitHub anyway.

**Comment by jjacode** [comment] 2018-04-17 21:11
From the log, the last thing is:

`Info 11762[14:42:10.524] event:
    {"seq":0,"type":"event","event":"projectsUpdatedInBackground","body":{"openFiles":["pathToFile.js","pathToFile2.js","pathToFile3.js"]}}
Info 11763[14:42:10.525] Sending request:
    {"projectName":"/dev/null/inferredProject1*",
    "fileNames": [...lotsOfFiles]`, ... }

**Comment by mjbvz** [comment] 2018-05-08 22:27
Do you see this in the latest VS Code insiders builds?

**Comment by jjacode** [comment] 2018-05-08 23:10
@mjbvz , I've not noticed it as much lately, but stopped watching for it. I've also had fewer times I've needed to import at 3+ levels deep. I'll watch for it and respond again in a few days.

That said, I do know today and yesterday I was able to go 4 levels deep 2 different times. So, maybe it is fixed. Thanks for the update!

**Comment by mjbvz** [comment] 2018-05-09 00:14
Ok, let me know if you see it again in the latest insiders builds

**Closed by mjbvz** 2018-05-09 00:14 UTC
Labels: javascript, needs more info
