### ISSUE TITLE
Completions for writing watch expressions

### ISSUE THREAD

**Issue by corneliusweig** [microsoft/vscode#190525] opened 2023-08-15 21:53 UTC
The debugger already supports completions in the debug console via the DAP completions request (https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Completions).

However, when writing a watch expression in the watch section there are no completion suggestions

![watch section](https://code.visualstudio.com/assets/docs/editor/debugging/watch.png)

On the other hand, when writing the expression for a conditional breakpoint there _are_ completion suggestions.

---

Therefore, can we please also have completion suggestions when writing watch expressions?

**Comment by tklajnscek** [comment] 2023-10-13 08:15
+1 for this! :)

**Comment by joyceerhl** [comment] 2023-12-05 22:57
Duplicate of https://github.com/microsoft/vscode/issues/48810

**Closed by joyceerhl** 2023-12-05 22:57 UTC
