### ISSUE TITLE
[css] support comma less color values

### ISSUE THREAD

**Issue by iotacb** [microsoft/vscode#137695] opened 2021-11-23 03:28 UTC
Issue Type: <b>Bug</b>

The color picker itself works fine.
The problem I found is that the color picker is not showing when using
RGB or HSL values in css when spacing the values with spaces.

So rgb(250, 0, 0) shows the color picker when hovering
but rgb(250 0 0) does not.

![GIF](https://i.imgur.com/4VyCMAM.gif)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.86GB free)|
|Process Argv|--crash-reporter-id 8138733d-5015-4265-a27e-fd7203c7953b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
gif-player|bie|0.0.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.32.0
discord-vscode|icr|5.7.0
svg|joc|1.4.14
styled-components-snippets|jon|0.10.0
minifyall|jos|2.10.0
vscode-styled-components|jpo|1.6.6
vscode-gutter-preview|kis|0.29.0
css-sorter|kos|0.0.2
vscode-language-pack-de|MS-|1.62.4
js-debug-nightly|ms-|2021.11.1217
vsliveshare|ms-|1.0.5090
indent-rainbow|ode|8.2.2
emoji|Per|1.0.1
material-icon-theme|PKi|4.10.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
shader|sle|1.1.5
tabnine-vscode|Tab|3.5.1
errorlens|use|3.4.1
vscode-todo-highlight|way|1.0.5
unity-snippets|Ycl|0.1.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246cf:30401891
vscop804cf:30404767

```

</details>

**Comment by aeschli** [comment] 2021-11-23 16:48
duplicate of #111337

**Closed by aeschli** 2021-11-23 16:48 UTC
Labels: css-less-scss
