### ISSUE TITLE
VSCode crashes when you try to close a super large unsaved JSON file

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#41184] opened 2018-01-05 11:52 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (8697a5e4ec152832a2612929c87d56302dbb2e79, 2018-01-03T05:14:21.686Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1
vscode-subword-navigation|ow|1.1.5
vscode-icons|rob|7.19.0
quokka-vscode|Wal|1.0.90
wallaby-vscode|Wal|1.0.70

---

Steps to Reproduce:

1. Paste a very large unformatted JSON file. I haven't been able to attach the one I'm working with as I don't have permission to do that.
2. Format it (alt shift L)... this takes some time... don't save your changes though
3. Try closing the file without saving, it crashes VS Code
4. Reopen VS Code... the file is still there unsaved and you still can't close it

The workaround is to select all the press delete, then close the file without saving, then all is good.

**Comment by pronebird** [comment] 2018-01-21 20:54
I can reproduce this. Also saving the JSON and then closing it works (wat?)

**Comment by rebornix** [comment] 2018-02-12 19:24
@pronebird @massimocode can you still reproduce this issue with latest Insider? We optimized the text buffer and how we save the content, the issue should be gone now but let me know if you still see it.

**Comment by nanoteilchen** [comment] 2018-02-13 08:06
Still the same problem with newest version. How to reproduce it:
https://youtu.be/gGTxZ_4-WjE

When clicking during the "hang"-procedure, after a while, vsc comes back, but the file is still not closed (as shown in the video).
JSON-File from video attached.
[map.geojson.zip](https://github.com/Microsoft/vscode/files/1719120/map.geojson.zip)

**Comment by rebornix** [comment] 2018-02-13 19:00
@bpasero what I found from above case is, 

* Users click *Don't Save*
* File Service tries to revert
* Load content from disk, do diff, set the content to the model
* Send out the REVERT event.

The third step crashes Code and I suppose it's *diff*. Is it necessary to make updates to the model before we close?

**Comment by bpasero** [comment] 2018-02-20 17:15
@rebornix imho this should go into the text model on your end and not from the outside, e.g. it can always happen that a model is there with some value and gets another value applied. You should not do the diff if you see that the value is very large.

**Comment by pronebird** [comment] 2018-02-21 10:20
Still freezing on 1.20.1

Every text editor's problem since year 1971...

**Comment by alexandrudima** [comment] 2018-02-26 22:57
This is also fixed by 814be2f (i.e. dup of #39266)

**Closed by alexandrudima** 2018-02-26 22:57 UTC
Labels: editor-textbuffer, freeze-slow-crash
