### ISSUE TITLE
TS language breaking when pasting code

### ISSUE THREAD

**Issue by guisperandio** [microsoft/vscode#217000] opened 2024-06-24 10:47 UTC
Type: <b>Bug</b>

Open ts file, copy any code on it

VS Code version: Code - Insiders 1.91.0-insider (21decd9342dd2e14f2a7cd2883f84e6ff43ea0df, 2024-06-11T06:46:21.055Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.50GB free)|
|Process Argv|--crash-reporter-id d65139c4-cd5f-4788-b673-f2e1e20c4886|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
turbo-console-log|Cha|2.10.4
path-intellisense|chr|2.9.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.206.0
copilot-chat|Git|0.16.1
helium-icon-theme|hel|1.0.0
path-autocomplete|ion|1.25.0
vscode-codemetrics|kis|1.26.1
live-server|ms-|0.4.13
powershell|ms-|2024.2.2
vscode-typescript-next|ms-|5.6.20240623
color-highlight|nau|2.8.0
quicktype|qui|23.0.170
vs-code-prettier-eslint|rve|6.0.0
vscode-playwright-test-runner|sak|1.4.1
markdown-preview-enhanced|shd|0.8.13
code-spell-checker|str|3.0.1
material-theme|zhu|3.17.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
724cj586:31013169
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pkg_only:31057982
nativerepl1:31071684

```

</details>

**Comment by mjbvz** [comment] 2024-06-24 18:05
Duplicate of https://github.com/microsoft/TypeScript/pull/58846

**Closed by mjbvz** 2024-06-24 18:05 UTC
