### ISSUE TITLE
Objects that can trigger commands can't pass arguments to them

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33088] opened 2017-08-24 14:38 UTC
There are many objects that are able to trigger commands, like [StatusBarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#StatusBarItem), but not all of them (probably none of them) support a complementary `arguments` field defining the arguments that will be passed to that command's handler.

The point is that it's not even impossible to make `StatusBarItem`s pass arbitrary arguments to arbitrary commands, but it requires some [tinkering](https://github.com/fabiospampinato/vscode-commands/blob/master/src/utils.ts#L89).

Why isn't this supported by default?

**Comment by jrieken** [comment] 2017-08-28 07:18
dupe of #22353

**Closed by jrieken** 2017-08-28 07:18 UTC
Labels: api
