### ISSUE TITLE
Intellisense reports type of imported modules as "import <...>" instead of actual type

### ISSUE THREAD

**Issue by alexkrolick** [Microsoft/vscode#16840] opened 2016-12-07 19:07 UTC
- VSCode Version: 1.8.0-insider
- OS Version: Mac OSX 10.11

<img width="340" alt="screen shot 2016-12-07 at 11 05 12 am" src="https://cloud.githubusercontent.com/assets/1571667/20982365/0f0824b2-bc6d-11e6-9770-49335218cc89.png">

<img width="352" alt="screen shot 2016-12-07 at 11 07 52 am" src="https://cloud.githubusercontent.com/assets/1571667/20982452/723d6b0a-bc6d-11e6-97c0-b5e39242c581.png">

Where TStep is defined, Intellisense reports the type as `React.Requirable<any>`

**Comment by mjbvz** [comment] 2016-12-07 22:31
Closing as duplicate of https://github.com/Microsoft/TypeScript/issues/11099

Thanks.

**Closed by mjbvz** 2016-12-07 22:31 UTC
Labels: duplicate, intellisense, javascript, upstream
