### ISSUE TITLE
after using `infer extends` in TypeScript 4.7, everything is recognized as string

### ISSUE THREAD

**Issue by 1adybug** [microsoft/vscode#151546] opened 2022-06-08 19:13 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2 (user setup)
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

```typescript
interface ToUpperCase {
    a: "A"
    b: "B"
    c: "C"
    d: "D"
    e: "E"
    f: "F"
    g: "G"
    h: "H"
    i: "I"
    j: "J"
    k: "K"
    l: "L"
    m: "M"
    n: "N"
    o: "O"
    p: "P"
    q: "Q"
    r: "R"
    s: "S"
    t: "T"
    u: "U"
    v: "V"
    w: "W"
    x: "X"
    y: "Y"
    z: "Z"
}

type LowerCase = keyof ToUpperCase

type MyCapitalize<S extends string> = S extends `${infer First extends LowerCase}${infer Rest}` ? `${ToUpperCase[First]}${Rest}` : S

type A110 = MyCapitalize<"a123456">

// everything is recognized as string
// 1.67.2 (user setup)
// c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
// 2022-05-17T18:15:52.058Z
// Electron: 17.4.1
// Chromium: 98.0.4758.141
// Node.js: 16.13.0
// V8: 9.8.177.13-electron.0
// OS: Windows_NT x64 10.0.22000
```
**TypeScript and VS Code didnt detect any problem, but everything is recognized as string by vs code**

![pic](https://s3.bmp.ovh/imgs/2022/06/09/ed7f94a70a5bdf4f.png)

**Comment by 1adybug** [comment] 2022-06-08 22:31
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> Seems to work fine for me:
> 
> ![Screen Shot 2022-06-08 at 2 35 35 PM](https://user-images.githubusercontent.com/12821956/172721539-0c5016dd-6c30-4876-bf43-40abec586ecd.png)

![pic](https://s3.bmp.ovh/imgs/2022/06/09/7b90a0b638959ec7.png)

tried this in windows sandbox. brand new system and vs code. the problem still exists.

**Comment by mjbvz** [comment] 2022-06-08 22:31
That's looks like the current stable version of VS Code. Can you please test using insiders too: https://code.visualstudio.com/insiders/

**Comment by 1adybug** [comment] 2022-06-08 22:41
> That's looks like the current stable version of VS Code. Can you please test using insiders too: https://code.visualstudio.com/insiders/

ok, it works. the current stable version is using TypeScript 4.6.3. the insider is using 4.7.3.
I think that should be the reason.

**Comment by mjbvz** [comment] 2022-06-08 22:41
Thanks for testing. Closing since it sounds like the issue is already fixed then

**Closed by mjbvz** 2022-06-08 22:41 UTC
Labels: needs more info
