### ISSUE TITLE
`terminal.integrated.defaultProfile.windows` no longer works on launching application.

### ISSUE THREAD

**Issue by Chrg1001** [microsoft/vscode#132475] opened 2021-09-06 14:54 UTC
When I updated VS Code to 1.60.0, despite setting Git Bash as the default Terminal, Powershell is launched when the app starts.

It properly works when I create new terminal with "Plus" button.

Environment:

- VS Code Version: 1.60.0
- OS Version: Microsoft Windows 11 [Insider Preview Build 22000.176]

`settings.json`

```json
{
  "terminal.integrated.fontFamily": "'MesloLGM NF', 'MesloLGS NF', 'Hack', 'Myrica MM'",
  "terminal.integrated.tabs.enabled": true,
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.defaultProfile.linux": "zsh",
  "terminal.integrated.defaultProfile.windows": "Git Bash",
}
```

**Comment by gjsjohnmurray** [comment] 2021-09-06 15:00
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-06 15:01 UTC
Labels: *duplicate
