### ISSUE TITLE
Re-adding a configuration in launch.json doesn't work

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#72728] opened 2019-04-22 19:01 UTC
**THIS IS NOT A PYTHON EXTENSION ISSUE**

- VSCode Version: 1.33
- OS Version: Windows 10

This issue occurs only in vscode insiders, vscode stable works fine.

**Steps to Reproduce:**

- Download development version of python extension from [here](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix).
- Use `Ctrl + Shift + P` -> `Install from VSIX...` to install it, and reload window.
- Open a folder containing a python file in workspace.
- Open a python file to activate the extension.
- Then add configuration in `launch.json` as demonstrated in the gif, and try to re-add another configuration.

![bug](https://user-images.githubusercontent.com/13199757/56518953-9faa1600-64f5-11e9-9f16-748c48b820a3.gif)

**Current behavior:**

When re-adding the configuration a second time, upon clicking `Python` in gif, a red colored "Python" string appears, and selecting any configuration after that does not work. 

![image](https://user-images.githubusercontent.com/13199757/56543288-e57ed280-6525-11e9-9f82-1bcbddfc45cf.png)

**Expected behavior:**

No such "Python" string appears, and configuration is added.

![bug](https://user-images.githubusercontent.com/13199757/56543719-23c8c180-6527-11e9-9ed6-0e8425191546.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by DonJayamanne** [comment] 2019-04-30 19:29
@jrieken @isidorn 
FYI - The way i see it, this is a regression. I.e breaks in VSC Insiders and works in stable.

**Comment by isidorn** [comment] 2019-04-30 20:39
Assigning to April to investigate in the next couple of days

**Comment by jrieken** [comment] 2019-05-08 14:26
It seems that the interpretation of 'insert nothing' has changed. The suggestion is returned with `""` as insertText (see https://github.com/microsoft/vscode-python/blob/f590f9c89ae5ee31f33bc66626e9f8279ea17763/src/client/debugger/extension/configuration/launch.json/completionProvider.ts#L46). It seems that before we would have actually inserted nothing and that now we insert the default, e.g. the label. We always set ['when falsy'](https://github.com/Microsoft/vscode/blob/8ef8aa6b3cb5b96870660fdd3bb8d0755e62fe51/src/vs/vscode.d.ts#L3352-L3353) and now we can argue if the empty snippet string is falsy or not... So, yeah definitely something that changed on our side but unsure if that change is bad or towards more correctness. 

@DonJayamanne May I ask you need a completion item that doesn't do anything expect showing a picker? Why aren't those pick-options presented as individual suggestions?

**Comment by jrieken** [comment] 2019-05-08 14:27
This is very likely caused by this like of code: https://github.com/Microsoft/vscode/blob/8ef8aa6b3cb5b96870660fdd3bb8d0755e62fe51/src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts#L372

**Comment by jrieken** [comment] 2019-05-08 15:10
I have created https://github.com/microsoft/vscode/pull/73477 to restore the old, questionable, behaviour. Tho would love to get feedback/explainer from @DonJayamanne if they are willing to model that fits the suggestion world better, e.g instead of using an empty suggestion as trampoline, have many suggestions with quick pick (basically what quick pick is used for today)

**Closed** 2019-05-08 15:14 UTC
Labels: bug, debug
