### ISSUE TITLE
Do not prompt for saving dirty file if opened as diff editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31511] opened 2017-07-27 08:06 UTC
Testing #30721

- Edit a file
- Run the Compare with file on disk action which opens diff editor
- Close the file

Save prompt is shown. Diff editor with the modified file is still open. We show dirty indicator, in Open editors. May be we can show save prompt when all editors with the file are closed.

**Comment by bpasero** [comment] 2017-08-11 07:51
We do the same when having a dirty file opened and diffing it to another file. I do not remember 100% why I decided to prompt in that case but I think it is because so that the user is not thinking the changes are lost (even though the diff editor is still dirty).

**Comment by bpasero** [comment] 2017-11-16 17:35
Closing "as designed".

**Closed by bpasero** 2017-11-16 17:35 UTC
Labels: feature-request, workbench
