### ISSUE TITLE
Marketplace: Searching for "Twilight theme" gives other extension as first result

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#71713] opened 2019-04-04 09:33 UTC
* Search for "Twilight theme"
* I would expect that the extension with the name "Twilight Theme" is ranked 1st.
* Instead, "Material" theme which has millions of installs appears to be "boosted"...
* I would like to suggest that exact name searches should not get ranked below "boosted" extensions.

![image](https://user-images.githubusercontent.com/5047891/55545346-51abaa80-56cd-11e9-9c65-5b7fb5410b62.png)

**Comment by alexandrudima** [comment] 2019-04-04 09:33
fyi @kesane-msft @auchenberg

**Comment by sandy081** [comment] 2019-04-04 19:55
duplicate of https://github.com/Microsoft/vscode/issues/42890

**Closed by sandy081** 2019-04-04 19:55 UTC
Labels: *duplicate, marketplace
