### ISSUE TITLE
VSCode crashed (reason: 'crashed', code: '132'

### ISSUE THREAD

**Issue by RenanSantos7** [microsoft/vscode#222171] opened 2024-07-19 11:16 UTC
## Informations
- VS Code Version: 1.91.1 x64
- OS Version: Fedora Linux 40

## Steps to Reproduce:
1. Restart system and open a vscode window.

## Similar bug report:
- #184574

## More Details
1. Output of `code --verbose` command: 
```
[12617:0719/080400.029820:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[main 2024-07-19T11:04:00.106Z] [File Watcher (node.js)] Request to start watching: /home/renan/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/renan/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-07-19T11:04:00.118Z] Starting VS Code
[main 2024-07-19T11:04:00.118Z] from: /usr/share/code/resources/app
[main 2024-07-19T11:04:00.118Z] args: {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  'update-extensions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-lcd-text': false,
  'disable-gpu': false,
  'disable-chromium-sandbox': false,
  sandbox: false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'use-inmemory-secretstorage': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '89d3a76e-3776-473c-9a29-67c0c9262a1e',
  'skip-add-to-recently-opened': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'preserve-env': false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  'disable-gpu-sandbox': false,
  '__enable-file-policy': false,
  'enable-coi': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/home/renan/.config/Code/logs/20240719T080400'
}
[main 2024-07-19T11:04:00.119Z] Resolving machine identifier...
[main 2024-07-19T11:04:00.119Z] Resolved machine identifier: 6af071c0d47bbb52a7b2b8f46cbb2096093647c7c5389428f3052684e0740d47
[main 2024-07-19T11:04:00.119Z] Main->SharedProcess#connect
[main 2024-07-19T11:04:00.122Z] [File Watcher (node.js)] Started watching: '/home/renan/.config/Code/User'
[main 2024-07-19T11:04:00.123Z] [File Watcher (node.js)] Started watching: '/home/renan/.config/Code/User/settings.json'
[main 2024-07-19T11:04:00.124Z] StorageMainService: creating application storage
[main 2024-07-19T11:04:00.126Z] ElectronURLListener: waiting for window to be ready to handle URLs...
[main 2024-07-19T11:04:00.126Z] lifecycle (main): phase changed (value: 2)
[main 2024-07-19T11:04:00.126Z] windowsManager#open
[main 2024-07-19T11:04:00.127Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: 'd72b5fd541558f20f18286c2e2053859', uri: [m] },
    type: 2,
    exists: true
  }
]
[main 2024-07-19T11:04:00.127Z] windowsManager#doOpenFolderOrWorkspace {
  folderOrWorkspace: {
    workspace: { id: 'd72b5fd541558f20f18286c2e2053859', uri: [m] },
    type: 2,
    exists: true
  },
  filesToOpen: undefined
}
[main 2024-07-19T11:04:00.128Z] IPC Object URL: Registered new channel vscode:9e90e4a9-7559-418b-b857-79c71f772b0c.
[main 2024-07-19T11:04:00.128Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 768, y: 156, width: 1024, height: 768 }
[main 2024-07-19T11:04:00.128Z] window#validateWindowState: single monitor working area { x: 0, y: 32, width: 2560, height: 1048 }
[main 2024-07-19T11:04:00.128Z] window#ctor: using window state { mode: 0, x: 768, y: 156, width: 1024, height: 768 }
[12660:0719/080400.169794:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2024-07-19T11:04:00.185Z] window#load: attempt to load window (id: 1)
[main 2024-07-19T11:04:00.190Z] StorageMainService: creating workspace storage (d72b5fd541558f20f18286c2e2053859)
[main 2024-07-19T11:04:00.190Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2024-07-19T11:04:00.190Z] lifecycle (main): phase changed (value: 3)
[main 2024-07-19T11:04:00.190Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2024-07-19T11:04:00.190Z] update#setState idle
[main 2024-07-19T11:04:00.231Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
<--- Last few GCs --->

[1:0x16e000568000]       91 ms: Mark-Compact (reduce) 1.1 (3.7) -> 1.1 (2.7) MB, pooled: 0 MB, 0.72 / 0.00 ms  (average mu = 0.368, current mu = 0.028) last resort; GC in old space requested
[1:0x16e000568000]       92 ms: Mark-Compact (reduce) 1.1 (2.7) -> 1.1 (2.7) MB, pooled: 0 MB, 0.66 / 0.00 ms  (average mu = 0.235, current mu = 0.016) last resort; GC in old space requested


<--- JS stacktrace --->
[12718:0719/080400.286056:ERROR:v8_initializer.cc(799)] V8 javascript OOM (CALL_AND_RETRY_LAST).
[0719/080400.296596:ERROR:directory_reader_posix.cc(43)] opendir /home/renan/.config/Code/Crashpad/attachments/1f40f555-9c0b-4d03-a694-bf444bed1006: No such file or directory (2)
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[main 2024-07-19T11:04:00.695Z] CodeWindow: renderer process gone (reason: crashed, code: 132)
[12660:0719/080400.719374:WARNING:angle_platform_impl.cc(49)] ProgramGL.cpp:700 (checkLinkStatus): Program link or binary loading failed with no info log.
[main 2024-07-19T11:04:02.693Z] lifecycle (main): phase changed (value: 4)
[main 2024-07-19T11:04:30.191Z] update#checkForUpdates, state =  idle
[main 2024-07-19T11:04:30.191Z] update#setState checking for updates
[main 2024-07-19T11:04:30.191Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2024-07-19T11:04:30.690Z] update#setState idle
```

2. When I run `code --disable-dev-shm-usage` the issue persists
3. When I run `code --crash-reporter-directory ~/Downloads` the issues doesn't occurs.
[bugreport202407190815.zip](https://github.com/user-attachments/files/16311164/bugreport202407190815.zip)
4. The bug does not occur if I run `code [a/folder/path]` on terminal.

**Comment by tamuratak** [comment] 2024-08-27 03:28
It might be duplicate of  #221886. See https://github.com/microsoft/vscode/issues/221886#issuecomment-2271739803

**Comment by deepak1556** [comment] 2024-12-12 10:55
The crash is oom from javascript heap limit reached. Can you follow the steps below to capture a heap profile,

* From a fresh instance, run `Developer: Toggle Developer Tools`
* Switch to the `Memory` tab and select the option as shown in the screenshot below
 ![Image](https://github.com/user-attachments/assets/a0a32e6c-c350-4890-81e3-2c29a8513f75)
* Start the recording, repeat the steps that repro the crash
* Save the profile and attach it to this issue

**Closed** 2024-12-19 11:28 UTC
Labels: info-needed
