### ISSUE TITLE
Exclude all files and directories except specifics in vscode

### ISSUE THREAD

**Issue by MJoergensen** [microsoft/vscode#214003] opened 2024-05-31 12:44 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 11

I want to exclude everything in the explorer window in vscode I have looked at the following posts on stackoverflow, but I simply can't get the syntax to work:

[how-to-exclude-all-folders-except-one-folder-in-vscode](https://stackoverflow.com/questions/60565855/how-to-exclude-all-folders-except-one-folder-in-vscode)

[how-to-exclude-all-but-certain-files-in-the-sidebar-in-visual-studio-code](https://stackoverflow.com/questions/52331983/how-to-exclude-all-but-certain-files-in-the-sidebar-in-visual-studio-code/52333436#52333436)

I wish to exclude everything except files ending on *_1.pdf. I have the following syntax, which doesn't work:

` "files.exclude": {
    "manuals/**/*[^_][^1][^.][^p][^d][^f]": true,   
}
`

I have also tried the following:

    "files.exclude": {
    "manuals/**/*": true,                            
    "manuals/**/*_1.pdf": false,                     
},

and just about a million other alterations. What am I missing?

Steps to Reproduce:

1. Create vscode workspace
2. directory should include a bunch of files
3. Add the following code to .vscode/settings.json: `{
    "files.exclude": {
        "*": true,
        "*.py": false,
    }
}
`
4. Everything is now gone from the explorer window.

**Comment by IllusionMH** [comment] 2024-05-31 16:31
Looks like duplicate of #869

**Closed** 2024-06-20 15:33 UTC
Labels: *duplicate
