### ISSUE TITLE
Auto imports including full path

### ISSUE THREAD

**Issue by c17r** [Microsoft/vscode#53969] opened 2018-07-10 14:44 UTC
Issue Type: <b>Bug</b>

Not sure whose the cause, VSC or TS, but with VSC 1.25 and TS 2.9.2 the auto-add import process is broken and I end up with something like `import { FormGroup } from '../../../../node_modules/@angular/forms';` where previously it would do `import { FormGroup } from '@angular/forms';`

Nothing changed in any configs

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\cs\source\repos\3SS\Cheetah\FrontEnd\hydra|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
auto-rename-tag|for|0.0.15
dotnet-test-explorer|for|0.3.1
csharpextensions|jch|1.3.0
python|ms-|2018.6.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.7.0
vscode-coverage-gutters|rya|2.0.1
code-settings-sync|Sha|2.9.2
rewrap|stk|1.9.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by DenisVuyka** [comment] 2018-07-10 16:07
Had to rollback to 1.24 because of this bug. Renders entire IDE useless for Angular development so far.

**Comment by olsonjj** [comment] 2018-07-10 18:15
Same issue here. Re-installed 1.24 on Mac.

**Comment by ashley-hunter** [comment] 2018-07-10 18:21
Same issue on Windows 10

**Comment by mjbvz** [comment] 2018-07-10 18:31
Duplicate of #53597

Either upgrade to VS Code insiders or upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-07-10 18:31 UTC
