### ISSUE TITLE
Markdown preview is not working

### ISSUE THREAD

**Issue by sevenryze** [Microsoft/vscode#58151] opened 2018-09-07 06:12 UTC
Issue Type: <b>Bug</b>

1. Update to the latest vscode insider version: 1.28.0
1. Open a single markdown file and open preview, and there is a blank page on screen.
1. Enable or disable all extensions will still not make markdown prewiew working.

By the way, the release note of newest vscode insider is not display properly either.

Please check it, it's a very big problem. :smile:

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Stone-Zeng** [comment] 2018-09-07 13:18
The `Details` and `Changelog` panel of extensions also disappear. Really a very **big** problem!

**Comment by mjbvz** [comment] 2018-09-07 16:54
Duplicate of #58203

**Closed by mjbvz** 2018-09-07 16:54 UTC
Labels: insiders
