### ISSUE TITLE
vs intellisense is very slow 

### ISSUE THREAD

**Issue by khaled-al-hamwie** [microsoft/vscode#156472] opened 2022-07-27 14:57 UTC
hi i am using vs code with java script and every time i try to write something i don't get an code suggestion until a 20 second pass after i stop write ,
i tried to disapple all my extinsion but it didn't do any thing then i tried to reduce the delay in the settings from 10 to 5 which didn't work then i try to reduce it to 1 but also didn't work ,
i hope u fix this proplem as soon as possible and thanks for readding

**Comment by thepolarchimps** [comment] 2022-07-29 13:34
Hiya, I can also confirm that in the past couple days VSCode Intellisense has become very slow for me. Using:

VSCode v1.69.2
Typescript
Darwin arm64 21.5.0

I've reduced active plugins to none, and to those I geuininely use in my every day workflow with the same results.

If you write ```javascript const date = new Date();``` for example, it takes a while to work out 'date' is a Date.

It's also catching up with what you type. It will sometimes display a red ~~ under "Da" in the above code for example after the line has already been completed, and file saved, reading, Cannot find name 'Da'.

Cheers

**Comment by buixuandinh711** [comment] 2022-07-29 15:10
I have the same problem, it's delayed seconds before show the hint.
This issue happens both with Javascript and Typescript.
VSCode v1.69.2
Ubuntu 20.04

**Comment by thepolarchimps** [comment] 2022-07-29 15:18
Could be something to do with file reads/writes, I've just been left hanging on both creating a folder, and a file. Cancelled after a while for both respectively, and they actually showed up in the sidebar. Tried quiting, and it warned me file operations were still underway.

**Comment by khaled-al-hamwie** [comment] 2022-08-09 14:49
a little update on my problem
I figure out it was the mongoose module how is causing the problem (Aka the slow intellisense ) and I found out by commenting the request of the mongoose module the intellisense 
I still don't know why that speed up the Intellisense if u had an explanation please write it and I will be grateful 
and in the end thank for reading

**Comment by mjbvz** [comment] 2022-08-10 16:06
Duplicate of https://github.com/Automattic/mongoose/issues/10349

**Closed by mjbvz** 2022-08-10 16:06 UTC
