### ISSUE TITLE
Can't launch multiple Code instances simultaneously ("Another instance is not responding")

### ISSUE THREAD

**Issue by dorian-marchal** [microsoft/vscode#72531] opened 2019-04-18 07:22 UTC
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

When I start my laptop, I launch two instances of VSCode at the same time (I work on two projects). I do this via a Terminator configuration but it can be reproduced with a shell script:

```shell
code /path/to/first/project &
code /path/to/second/project &
wait
```
90% of the time, I get the following error: "Another instance of code is running but not responding".
Only one instance of code is started after that, I have to manually launch the second one.

Does this issue occur when all extensions are disabled?: Yes, but less often.

**Comment by joaomoreno** [comment] 2019-05-06 09:07
Can you show me a screenshot of the error? I'm interested in knowing where it comes from.

Also, can you show me your `PATH` variable?

**Comment by dorian-marchal** [comment] 2019-05-06 11:56
![Screenshot from 2019-05-06 13-55-20](https://user-images.githubusercontent.com/6225979/57223522-aa40d100-7006-11e9-8a17-645a29874cc6.png)

```shell
$ echo $PATH
/home/dorian/.nvm/versions/node/v10.14.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/.config/composer/vendor/bin/:/home/dorian/repos/fzf/bin:~/.config/composer/vendor/bin/
```

**Comment by bpasero** [comment] 2019-05-07 09:46
@joaomoreno this must be an issue somewhere in your startup server that uses socket/pipes to prevent 2 instances from running at the same time. The warning is cleared when the startup was successful here: https://github.com/Microsoft/vscode/blob/8deb75622216be51d088cc9b86c01a10fdef728b/src/vs/code/electron-main/main.ts#L167

**Comment by joaomoreno** [comment] 2019-05-07 10:04
I can repro but very rarely. Maybe only 10% of the times actually repros.

It seems the second client is able to connect, but one of these promises never returns:

https://github.com/Microsoft/vscode/blob/daf71423252a707b8e396e8afa8102b717f8213b/src/vs/code/electron-main/main.ts#L161-L163

**Comment by YisraelV** [comment] 2019-06-14 08:35
@joaomoreno when I manage to reproduce I'm getting in the output: "Error: Unknown channel: launch"

  what seems to be happening is that the second instance joins in after the first one created the ipc server, ([here](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L201)) but before it had time to register the "launch" channel ([here](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L490)).

You can sort of reproduce this by putting the line that registers the channel inside a timeout (a very short timeout should suffice)

A possible solution would be to do some locking so that other processes have to wait while the first one is initializing (no need of locking between secondary instances)

By the way, I noticed that when this error happens, the second instance (the one that didn't manage to open) is never killed (running ps shows many processes still living)

@dorian-marchal could you please check for this error in the logs? 
cd ~/.config/Code/logs
grep -r "Unknown channel"

**Comment by dorian-marchal** [comment] 2019-06-14 08:59
```
cd ~/.config/Code/logs
grep -r "Unknown channel"
```
Nothing. :+1:

**Comment by joaomoreno** [comment] 2019-06-14 09:40
@YisraelV Great research!

@bpasero This started happening since the last refactorings around this code. Please read https://github.com/microsoft/vscode/issues/72531#issuecomment-502021609. This makes a lot of sense. We should try to put the launch service's registration as much further up as we can, otherwise the socket synchronization won't work.

Alternatively we can add some timeout mechanism in IPC in which a call to a missing service would wait for a predefined amount of time (how much?) and only reject if the service is still missing after that timeout.

@bpasero Also:

> By the way, I noticed that when this error happens, the second instance (the one that didn't manage to open) is never killed (running ps shows many processes still living)

**Comment by bpasero** [comment] 2019-06-14 10:15
@joaomoreno yes I see how this happens but I am not sure we can easily move the channel to a place earlier simply because of the service dependencies. 

I like the idea of having a `client.getChannel('launch', <delay>)` that would wait for a couple of seconds before giving up.

**Comment by bpasero** [comment] 2019-06-14 10:19
@joaomoreno actually the real trouble is that this promise never returns (and as such the process keeps hanging):

```
await launchClient.start(environmentService.args, process.env as platform.IProcessEnvironment)
```

So maybe even better, this call should have a retry mechanism but then eventually really timeout and throw an error.

**Comment by joaomoreno** [comment] 2019-06-14 12:50
@bpasero Doesn't even throw? That should throw if the service isn't found... let me check.

**Comment by bpasero** [comment] 2019-06-14 13:00
@joaomoreno yeah it does not throw it seems. I see an exception only on the other side.

**Comment by joaomoreno** [comment] 2019-06-14 13:08
Yup can definitely repro! This was introduced right here: https://github.com/microsoft/vscode/commit/7a7ccce37a7c78251153a052a8f03995a2026d05#diff-c1b8b3dc3e7d1e387c54da7f7da1b3e5 cc @mjbvz

**Comment by bpasero** [comment] 2019-06-14 13:25
This is a fix for not having dormant startup processes hanging around, thanks. We still need to think about retry logic.

**Comment by joaomoreno** [comment] 2019-06-14 13:44
Actually that fix is more than that, it's a fix for proper error reporting: the server side reports the error and the client side actually gets a promise rejection error.

**Comment by joaomoreno** [comment] 2019-06-14 13:55
Pushed a timeout mechanism, defaulting to 1 second. Basically, in the case of a missing IPC channel, the server will wait 1 second before timing out and returning a promise rejections. If during that second the channel gets registered, all pending request to it get resolved.

**Comment by bpasero** [comment] 2019-06-14 14:19
Cool thanks!

**Comment by YisraelV** [comment] 2019-06-14 14:42
@bpasero for sure, although I couldn't reproduce most of the time so @dorian-marchal maybe you could too?

**Comment by lramos15** [comment] 2019-06-26 17:41
@joaomoreno @bpasero I'm not sure if this is related to this issue, but running the above script provided still does not guarantee that I get two instances of VS Code to open up. I don't get the VS Code not responding error however.

**Comment by bpasero** [comment] 2019-06-26 18:01
@joaomoreno maybe 1s is not enough for slow windows to timeout waiting for launch service?

**Comment by HuppiFluppi** [comment] 2019-06-27 08:32
Experiencing the same on Windows 10 (1903) when opening two files from the explorer at the same time. Sometimes it works (50/50), other times only one file opens and the below message appears.

![image](https://user-images.githubusercontent.com/6770346/60250305-a45cc300-98c6-11e9-9e4c-9b894405c2ee.png)


Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment] 2019-06-27 08:41
@HuppiFluppi 
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by HuppiFluppi** [comment] 2019-06-27 08:48
> @HuppiFluppi
> This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

Cool. Will wait for the stable though. Too old for previous ;-)

**Comment by joaomoreno** [comment] 2019-06-27 09:29
@HuppiFluppi Insiders is actually pretty solid. The entire VS Code team uses it daily, so as soon as it breaks it will be fixed within the day. I highly recommend it!

**Comment by joaomoreno** [comment] 2019-07-31 15:14
@bpasero The timeout mechanism works. It's the flushing of pending requests which has a problem. After 1 hour of `console.log` debugging, I was able to catch this elusive bug.

When two instances start, the first opens a window and the second one sends info to the first to open another window. Since there's no need, the first window is attempted to be open without forcing opening a new window. But the second window has a couple options that tells the workbench that, yes, we definitely want a new window for this.

Since we were flushing pending channel requests *right after* the channel was registered, the `open` call was being run for the second window before the first, because the launch channel gets registered before the call to `open` the very first window. So what happened was: one window would be opened with info to force a new window and another would be attempted to be opened without any force, so no window would actually come up.

That's it for me today, going home.

![so long](https://media.giphy.com/media/3orifhnYavB0PGJPMY/giphy.gif)

**Closed** 2019-07-31 15:19 UTC
Labels: bug, workbench-os-integration
