### ISSUE TITLE
Can't open folders

### ISSUE THREAD

**Issue by Yastea** [microsoft/vscode#208925] opened 2024-03-27 16:51 UTC
Type: <b>Bug</b>

"Hello,

I've used VS Code for a while, and this has never happened before, but today I can't open any folder on my PC. I can open files within the folder, but I can't open the folder itself. I've tried to uninstall all my libraries and VS Code, but it doesn't change anything.

Thanks for your attention and for your help.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.80GB free)|
|Process Argv|--crash-reporter-id 194a37cb-1cf8-4ff5-ac53-1c294ae958a5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
gee8j676:30988843
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by aeschli** [comment] 2024-03-27 18:28
Is it with the custom file dialog?
![image](https://github.com/microsoft/vscode/assets/6461412/a91a6cde-0fdb-4f06-95e3-99ca6b4c087d)

There's a bug that you need to remove the trailing `/` before pressing `Ok`.
When the `/` is there, `Ok` does nothing.

**Comment by youcandanch** [comment] 2024-03-28 13:40
@aeschli can confirm that fixed it for me.

**Comment by alexr00** [comment] 2024-04-02 08:34
duplicate of https://github.com/microsoft/vscode/issues/208937

**Closed by alexr00** 2024-04-02 08:34 UTC
