### ISSUE TITLE
JavaScript and TypeScript auto format inserts space when indexing into the result of a function call

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#41438] opened 2018-01-10 22:49 UTC
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (f4ed56b0d61050f6a94cfa033a058fabfdc0d651, 2018-01-09T06:08:10.994Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li>Extensions: Extensions are disabled</li>
</ul>
---

code 1.19.2 formats JavaScript and TypeScript like this
```js
function getArray(): number[] {
	return [1];
}

function testFormat() {
	const hi = getArray()[0]; // no space before [0]
}
```

code-insiders formats JavaScript and TypeScript like this: 

```ts
function getArray(): number[] {
	return [1];
}

function testFormat() {
	const hi = getArray() [0]; // space before [0]
}
```

This seems like a regression in insiders, but if it is intentional then please add a config to disable this formatting rule (did not find such a rule to disable).

**Comment by benhamlin** [comment] 2018-01-11 01:01
This is happening in a pure javscript file as well, not typescript specific.

**Comment by nicksnyder** [comment] 2018-01-11 01:59
@benhamlin Thanks for pointing this out. I updated the title and description.

**Comment by mjbvz** [comment] 2018-01-11 06:12
Duplicate of https://github.com/Microsoft/TypeScript/issues/21111 . Should be fixed in `typescript@next` already: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2018-01-11 06:12 UTC
Labels: insiders, typescript
