### ISSUE TITLE
[Bug] Sass linter wrong errors for Sass each over a map

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#7538] opened 2016-06-10 14:36 UTC
- VSCode Version: 0.1.2
- OS Version: Mac OSX El Capitan

Steps to Reproduce:

1.  Paste this into a new file with Sass syntax:
```scss
@each $color, $hex in $colors {
  
  .color-#{$color} {
    color: $hex;
  }

  .border-#{$color} {
    border: 1px solid $hex;
    border-radius: 2px;

  }

  @each $side in ('top', 'left', 'right', 'bottom') {
    .border-#{$side}-#{$color} {
      border-#{$side}: 1px solid $hex;
      border-radius: 2px;
    }
  }

  .background-#{$color} {
    background: $hex;
  }
}
```
Current output: 
![image](https://cloud.githubusercontent.com/assets/9698639/15967782/9bf5681a-2eee-11e6-8e91-c61dfde297d3.png)

The errors of the linter:
![image](https://cloud.githubusercontent.com/assets/9698639/15967799/afd12bbc-2eee-11e6-8a7e-b2b945473984.png)

**Comment by glen-84** [comment] 2016-06-11 17:24
Duplicate of #1758 (?)

**Comment by Luchillo** [comment] 2016-06-11 18:06
Not exactly dup but related, the issue he has is when declaring maps, which i also have (just checked my `$colors` map), but mine is when using the map with an `@each` to generate styles, however it's worth mentioning that the base of both is that `map` syntax is still not supported.

**Comment by glen-84** [comment] 2016-06-11 18:19
@Luchillo It might work in the latest insider build, see https://github.com/Microsoft/vscode/issues/7434#issuecomment-225379421.

**Comment by Luchillo** [comment] 2016-06-11 18:37
Ok, but for now i will stick with the style extension mentioned, i'll test when the official release is out.

**Comment by aeschli** [comment] 2016-06-12 13:11
Sorry, there hasn't been any work on SCSS map support yet.

**Comment by aeschli** [comment] 2016-06-15 13:43
Duplicate of #1758

**Closed by aeschli** 2016-06-15 13:43 UTC
