### ISSUE TITLE
Intellisense incorrectly renders in-line code of `@`-characters inside JSDoc tags

### ISSUE THREAD

**Issue by BrunnerLivio** [microsoft/vscode#77484] opened 2019-07-16 19:46 UTC
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2 (LTS Bionic Beaver)
- TypeScript Version: 3.5.2

Steps to Reproduce:

1. Create a new file with and select TypeScript as language
2. Paste in the following snippet:

```typescript
/**
 * @description
 * ```typescript
 * import { Injector } from '@angular/core';
 * ```
 */
function test() { }
```

3. Hover over the `test()` function so VSCode shows further information about the function

![Selection_055](https://user-images.githubusercontent.com/9899423/61324527-f1232200-a812-11e9-90fa-aca0dbf93b9e.png)

4. It should not add asterisks before and after `@angular`.

**Note:** this only occurs when having the in line code snippet after a JSDoc tag such as `@description`, `@usageNotes` etc. and if you are using the `@` character

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-07-20 01:00
Duplicate of https://github.com/microsoft/TypeScript/issues/20000

**Closed by mjbvz** 2019-07-20 01:00 UTC
Labels: javascript
