### ISSUE TITLE
Support for PowerShell App on Microsoft Store as integrated terminal.

### ISSUE THREAD

**Issue by khooz** [microsoft/vscode#111124] opened 2020-11-22 12:36 UTC
Hi,

I've been using the PowerShell Core project for quite some time now and recently tried migrating from its .msi installer to its Store app so that future updates would be streamlined.

Since the migration, I removed the .msi package, and then the integrated terminal broke up while the Windows Terminal app picked up the new shell easily.

If they can do that with Windows Terminal, I hope so or maybe they do but I couldn't find the proper way, that VSCode could call up the shell just like Windows Terminal does. Currently, it calls up an absolute path to the shell executable. I have tried providing the package's `InstallLocation`, `PackageFamilyName!App`, and `Windows.Terminal.PowershellCore` (the way Windows Terminal addresses in its profile) but none works.

**Comment by meganrogge** [comment] 2020-11-22 23:14
Duplicate of #110828

**Closed by meganrogge** 2020-11-22 23:14 UTC
