### ISSUE TITLE
Keybinding context keys seem to be ignored when viewlets and panels are focused

### ISSUE THREAD

**Issue by alexrussell** [Microsoft/vscode#53253] opened 2018-06-28 15:04 UTC
- VSCode Version:
    - Code - Insiders
    - `1.25.0-insider`
    - `07d89abf1522a67f0e8105770505077f454ab021` (07d89abf1522a67f0e8105770505077f454ab021)
    - `2018-06-28T05:05:08.481Z`
- OS Version:
    - macOS High Sierra `10.13.5`

Steps to Reproduce:

1. Have a keyboard shortcut set up `"when": "editorFocus"` (e.g. the default `cmd+d` for `editor.action.addSelectionToNextFindMatch`)
2. Have a different shortcut (but same keybinding) set up `"when": "terminalFocus"` (e.g. `cmd+d` for `workbench.action.terminal.split` - make it work like iTerm!)
3. Focus editor, press `cmd+d` - works fine.
4. Focus terminal, press `cmd+d` - works fine.
5. Focus explorer, press `cmd+d` - splits the terminal?

Does this issue occur when all extensions are disabled?: **Yes**

---

Background: I actually found this issue not because I enjoy pressing `cmd+d` when I'm focussed on the explorer, but because I click a file in the explorer to load it into an editor, then I place my cursor inside a word, and then I press `cmd+d` to select that word and all other instances of it by repeating the keypress (haven't yet got `cmd+shift+l` into my muscle memory). Anyway, I apparently do this so quickly* that, I guess, these `when` conditions haven't have a chance to update, and so my press of `cmd+d` hits the `terminalFocus` rather than the `editorFocus` version. This ends up with me having about 8 split terminals open!

So the speed thing is probably something to look at, but I imagine the underlying issue is that `terminalFocus` is set when the terminal doesn't actually have focus, but it's just that the editor *doesn't*. I don't know how to "query" these expressions other than in a keyboard shortcut so I can't confirm for definite though.

\* realistically at human speed, so min 250ms, probably more like 600-1200ms

**Comment by alexrussell** [comment] 2018-06-28 15:08
As far as I can tell this is not a dupe of #43046.

**Comment by Tyriar** [comment] 2018-06-28 15:16
@alexandrudima do you know what's happening here? I can reproduce in Insiders but not when running out of sources. The context key appears to be getting set correctly when running out of sources.

**Comment by alexandrudima** [comment] 2018-06-29 07:42
@Tyriar Sorry, but you need to first investigate on your side and prove that it is a problem with the `IContextKeyService` and `IKeybindingService`. None of the other users of those two services have reported keys being evaluated to true when they were set to false. It is IMHO much more likely that there is a code path where the key is set to true (by accident).

From my looking through the terminal code, it appears that context key is passed around a lot through `split` and `instantiate` methods until it makes it to `TerminalInstance`... Why the code would pass that around instead of binding it in the `TerminalInstance` ctor I will not understand... Also, the key is set in `blur` and `focus` listeners, which seems to make sense, but `_terminalFocusContextKey` is also set in a `notifyFindWidgetFocusChanged` method which looks particularly fishy.

The context key service can create a child service given a dom node if you experience focus managing trouble. On this scoped context key service you can permanently set `terminalFocus`. This ensures that the `target` of a key event will 100% decide if `terminalFocus` is true or false.

**Comment by Tyriar** [comment] 2018-06-29 16:31
@alexandrudima 

For the default keybinding:

```
{ "key": "ctrl+d",                "command": "editor.action.addSelectionToNextFindMatch",
                                     "when": "editorFocus" }
```

I can reproduce weirdness in Insiders with the following steps:

1. `code-insiders --disable-extensions`
2. Click on some symbol/string in the editor
3. Click in the explorer
4. Press ctrl+d

This will trigger `editor.action.addSelectionToNextFindMatch` despite `editorFocus` only meant to be active when the editor text or widgets being focused:

https://github.com/Microsoft/vscode/blob/049cb9dde0839c0602a8ebeec8e7c7fcebcee4b6/src/vs/editor/common/editorContextKeys.ts#L14-L17

This also reproduces when focusing the search viewlet, extensions, problems, etc.

---

I repro'd out of sources, I may not have had the keybinding setup in the OSS build yesterday. I wanted to make a gif but Peek doesn't seem to be working for me. I added the following to `ContextKey<T>` to track:

```ts
	public set(value: T): void {
		if (this._key === 'terminalFocus') console.log('ContextKey#set', this._key, value);
		this._parent.setContext(this._key, value);
	}

	public reset(): void {
		if (typeof this._defaultValue === 'undefined') {
			if (this._key === 'terminalFocus') 	console.log('ContextKey#reset removeContext', this._key);
			this._parent.removeContext(this._key);
		} else {
			if (this._key === 'terminalFocus') console.log('ContextKey#reset setContext', this._key, this._defaultValue);
			this._parent.setContext(this._key, this._defaultValue);
		}
	}
```

`terminalFocus` was working just fine according to the console logs, but when the viewlets and panels were focused, ctrl+d would split the terminal.

**Comment by DanTopping** [comment] 2018-07-01 13:10
Not sure if related but since this last update I can't split the integrated terminal with default keybindings ( Ctrl + \ ) when the terminal is focused anymore. This keybinding still works to split the editor when the terminal isn't focused though.

VSCode - v1.19

I've checked that this isn't an issue with my powershell setup, since I just installed poshgit. But this is the same with node and cmd terminal instances as well.

![image](https://user-images.githubusercontent.com/31631414/42134667-6a776154-7d38-11e8-9683-f94c78e526dd.png)

**Comment by alexandrudima** [comment] 2018-07-02 08:29
@Tyriar __Can you attempt to run without menus displayed?__.

I don't know if Linux suffers from the same issue OSX suffers from, where displaying a keybinding next to a command in the menu makes it that the menu system invokes the command when the keybinding occurs. Perhaps @bpasero has a duplicate for this somewhere? 
> At least on OSX, displaying a keybinding next to a menu item will lead to the menu system intercepting the keybinding and dispatching it. On our side, we cannot differentiate if the menu action has been triggered by the menu system or by the user clicking.

You can find out this simply by placing a breakpoint in your action and seeing who the caller of the action is in the stacktrace. Is the `IKeybindingService` the caller?

**Comment by bpasero** [comment] 2018-07-02 09:10
@alexandrudima I think you mean https://github.com/Microsoft/vscode/issues/35225

**Comment by Tyriar** [comment] 2018-07-02 16:07
> Can you attempt to run without menus displayed?

It happens still when I hide the menus using the native title bar. When using the custom title bar the issue goes away though, so this is a dupe of https://github.com/Microsoft/vscode/issues/35225

**Closed by Tyriar** 2018-07-02 16:07 UTC
Labels: bug, keybindings

**Comment by alexrussell** [comment] 2018-07-03 12:47
@Tyriar sorry, but am I right in thinking this is closed because is it believed that this behaviour is caused because anything action added to the macOS menu bar that has a keyboard shortcut 'supplied' with the menu item itself automatically has that shortcut bound always (regardless of `when` in the keyboard shortcut config) - because Code's (or Electron's?) own shortcut handling is not handling the shortcut but macOS's, and is activating the action *as if* it were clicked in the menu (thus completely bypassing keyboard shortcut handling entirely in Code)?

I only ask because I'm totally not seeing that behaviour. For one thing, what i have describe here woudl be the opposite in that case: `cmd+d` in my menu system is bound to "Add next occurrence", but I'm getting "split terminal" (which has no menu item I'm aware of) when I press `cmd+d` in the Explorer.

Similarly, if what I have described above *was* happening, I'd be getting the editor selecting the next occurrence in the text editor while I am trying to split a terminal (legitimately, in the terminal), which I do not see happening.

So either #35225 is *not* what's happening here... or (more likely, I'll admit) I'm seriously misinterpreting #35225.

**Comment by alexandrudima** [comment] 2018-07-03 14:16
I believe we had a terminal top level menu for a brief time this month in the insiders channel. It has been removed in the meantime, perhaps you hit the issue at the exact time the top level menu was there ?

**Comment by alexrussell** [comment] 2018-07-03 15:11
A-ha, yes, that must be it. For certain in the latest Insiders build, the behaviour no longer happens (and, indeed, the `editor.action.addSelectionToNextFindMatch` action *does* appear to happen when focussed on the Explorer).

Interestingly, despite `editor.action.addSelectionToNextFindMatch` being tied to `cmd+d` in the menubar, when I'm focussed on the terminal, it correctly *only* splits the terminal, and does not select the next occurrence in the editor, which, based on #35225, I'd expect to happen. (Though, based on the existence of the `terminal.integrated.commandsToSkipShell` setting, I imagine the bad behaviour is mitigated in the terminal only, due to some fun jiggery pokery somewhere in Code.)

**Comment by Tyriar** [comment] 2018-07-03 18:41
@alexrussell yes it must have happened when the Terminal menu was in (it's coming back soon https://github.com/Microsoft/vscode/issues/53158)

`terminal.integrated.commandsToSkipShell` only drives which commands/keybindings should *not* go to the process inside the terminal and instead be evaluated by VS Code's keybinding system.
