### ISSUE TITLE
Multiline snippet expansion

### ISSUE THREAD

**Issue by ds0nt** [Microsoft/vscode#17944] opened 2016-12-30 18:17 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.36-1-MANJARO
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|
|vscode-proto3|zxh404|0.0.5|

---

Steps to Reproduce:

1. inside a go func block make a few lines, and press alt+down to multiselect a few blank lines
2. type in 'iferr' and press tab
3. observe that only one iferr template is expanded into the full block
![2016-12-30-131541_589x158_scrot](https://cloud.githubusercontent.com/assets/1015732/21570222/168a7960-ce92-11e6-9746-32c0af413753.png)

Desired results:

In atom it will expand them all. Not expanding them all is a bug, IMO. It just gets your cursors out of sync and everything becomes a mess.

**Comment by rebornix** [comment] 2016-12-30 18:50
Assign to @ramya-rao-a first and see whether it's Go or our internal multi cursor stuff.

**Comment by ramya-rao-a** [comment] 2016-12-30 19:13
This is not Go extension specific. Happens to snippets in other language files as well.

**Comment by ds0nt** [comment] 2016-12-30 19:14
You guys rock. Thanks for picking it up so fast!

**Comment by jrieken** [comment] 2017-01-03 09:06
dupe of https://github.com/Microsoft/vscode/issues/16037

**Closed by jrieken** 2017-01-03 09:06 UTC
Labels: editor-multicursor, snippets
