### ISSUE TITLE
Search in files not finding any results

### ISSUE THREAD

**Issue by cmov** [Microsoft/vscode#9843] opened 2016-07-27 09:10 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Open a Folder
2.pick a search string that exists on file in the folder structure
3.check the results

The next screenshots are 2 examples:
* Getting results when the file is open
<img width="406" alt="vs_code_search_wresults" src="https://cloud.githubusercontent.com/assets/20679404/17169994/0e3063b8-53e2-11e6-9597-f11824b5aceb.png">

* No results: search in folder without any file open
<img width="403" alt="vs_code_search_noresults" src="https://cloud.githubusercontent.com/assets/20679404/17169995/0e313608-53e2-11e6-871a-d6817d4b28c5.png">

**Comment by kieferrm** [comment] 2016-08-02 01:32
@cmov I can't reproduce the problem with the steps described. What is interesting is that a match is found when the file is open in an editor. Since we add open editors to the scope of files we search it would suggest that the file is not in scope.  Is there anything special about your workspace root? Does the path contain unicode characters?  

Can you create a minimal example that shows the problem for you?

**Comment by sandy081** [comment] 2016-08-22 13:56
Closing this issue as we did not received any information. Please reopen this with necessary information.

**Closed by sandy081** 2016-08-22 13:56 UTC
