### ISSUE TITLE
VSCode Terminal unusable with the bash console. Cannot type any text, scrolled down when typing.

### ISSUE THREAD

**Issue by ievgennaida** [microsoft/vscode#102753] opened 2020-07-17 07:59 UTC
Issue Type: <b>Bug</b>

**Windows 10 Enterprise 1809.**
bash console that goes with GIT package stopped working with **the latest updates of the VS Code.**
Changing **terminal.integrated.windowsEnableConpty**  = true/false has no effect at all.

1. Install git.
2. select installation option windows terminal as default. 
3. open vscode, select bash as default console.
4. see that there is no active cursor.

Typing leads to a scroll bottom. 
This happening only in VS Code. 
powershell works ok.
Resizing of the window can change the console behavior.

Calling bash in windows works ok.

 
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment] 2020-07-17 08:14
Looks like duplicate of #102378

**Comment by ievgennaida** [comment] 2020-07-20 13:24
Sometimes can be reproduced with the WSL terminal as well.

**Comment by Tyriar** [comment] 2020-08-03 17:31
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Closed by Tyriar** 2020-08-03 17:31 UTC
