### ISSUE TITLE
html.suggest.angular1 doesn't work

### ISSUE THREAD

**Issue by luanh6666666** [Microsoft/vscode#18558] opened 2017-01-15 05:10 UTC
- VSCode Version:1.81
- OS Version:win10

I have closed html.suggest.angular1 in settings, but I still see it in new html file.

![wechatimg1](https://cloud.githubusercontent.com/assets/24838088/21960359/45bb6332-db23-11e6-8819-6e195984f704.png)
![wechatimg2](https://cloud.githubusercontent.com/assets/24838088/21960360/46f7871c-db23-11e6-85f6-c08f2c5777e2.png)

**Comment by aeschli** [comment] 2017-01-19 10:04
duplicate of #17613

**Closed by aeschli** 2017-01-19 10:04 UTC
