### ISSUE TITLE
bug in JS highlighting multiline string

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#2070] opened 2016-01-17 20:09 UTC
There is now a bug in the Javascript highlighter when extending a string over multiple lines using backslash at the end. 

var moo = 
'finefine\
notfinenotfine';

**Comment by jrieken** [comment] 2016-01-18 09:08
@frevds And what is the bug? Please provide expected vs actual behaviour

**Comment by frevds** [comment] 2016-01-18 09:16
Oh, sorry, please find attached a script and a screenshot showing what I mean. Thanks. I can also take a look at the regex in question.. 

![js-highlighting-bug](https://cloud.githubusercontent.com/assets/5341447/12387402/908f49d4-bdcc-11e5-8854-d8f5302c7449.png)

**Comment by frevds** [comment] 2016-01-18 10:03
Looks like it can be solved like this: 

![js-highlighting-bug-resolution](https://cloud.githubusercontent.com/assets/5341447/12388399/e66b0cca-bdd2-11e5-9abe-d3a7346770d7.png)

I will leave this in my JavaScript.tmLanguage. Not sure if that is lexically correct but it seems to work (saying the end of the string is where the line end, unless there is an escaped line feed (any of \r or \n depending on the system and file, but with a preceding backslash). Looking forward to the next release.

**Comment by jrieken** [comment] 2016-01-18 10:39
Thanks @frevds. Yet another issue with the tm bundle

**Comment by aeschli** [comment] 2016-01-18 12:38
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/40.

**Closed** 2016-01-18 12:39 UTC
Labels: js
