### ISSUE TITLE
Menus: Strokes for close / min too thin

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53063] opened 2018-06-26 22:25 UTC
Refs: #52854
Related: #52900

Better to make them a bit thicker. Currently they look too thin, and `X` seems to suffer from antialiasing.

![image](https://user-images.githubusercontent.com/4033249/41942650-12cd6ffc-7955-11e8-8f98-ff82ad91e682.png)

**Comment by sbatten** [comment] 2018-07-03 23:42
dupe of #52854

**Closed by sbatten** 2018-07-03 23:42 UTC
Labels: workbench-menu
