### ISSUE TITLE
Python autoDocstring does not work with typing TYPE_CHECKING imports after color change in #182162

### ISSUE THREAD

**Issue by guitarman513** [microsoft/vscode#187166] opened 2023-07-06 17:14 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Upgrade to VSCode 1.79.1
2. create simple python function `def example(foo:"CustomClass"):
3. try to create autodocstring with control+shift+2
4. Watch default docstring pop up without any autocomplete

STEPS TO FIX:
https://stackoverflow.com/questions/76436694/in-vs-code-1-79-python-docstrings-are-colored-like-comments-how-do-i-return-it/76440715#76440715
Followed advice here to fix.

Honestly this color change is not only unnecessary but is a large step backwards. Please revert  #182162 back and get rid of its changes. Python docstrings are very different from comments and should not be treated the same. Many people at the office are saying this is like the "master->main" situation... very unnecessary.

**Comment by chrmarti** [comment] 2023-07-11 06:57
Duplicate of https://github.com/microsoft/vscode/issues/184836

**Closed by chrmarti** 2023-07-11 06:57 UTC
