### ISSUE TITLE
Cannot use IDialogService in some services due to custom dialog service dependencies

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#109056] opened 2020-10-21 04:33 UTC
Trying to use `IDialogService` in [ExtensionService](https://github.com/microsoft/vscode/blob/9be5ce5/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L43) or in its dependencies like [ExtensionManagementService](https://github.com/microsoft/vscode/blob/9be5ce5/src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts#L24) is causing workbench to explode because dialog service is depending on [Layout](https://github.com/microsoft/vscode/blob/9be5ce5/src/vs/workbench/browser/layout.ts#L109) that depends on ExtensionService.

Due to this dependency, DialogService cannot be used in many services. We should allow dialog service to be used by all workbench services and not introduce such a restriction.

**Comment by bpasero** [comment] 2020-10-21 06:22
This came in via https://github.com/microsoft/vscode/commit/1d4c7fa5b7412c1e444865ae84927b662c9c7402 and is probably a consequence of having the `window.dialogStyle: custom` setting even in native. 

It does not seem to be the `ILayoutService` dependency btw, it seems to be these:
* `IThemeService`
* `IKeybindingService`

Possible that we have a cycle somewhere because extensions depend on so many other services. 

I do not have a good idea how to solve this.

Should we drop the support for showing custom dialogs and the related setting altogether? Do we have a desire for people to disable native dialogs?

**Comment by sandy081** [comment] 2020-10-21 07:01
Not sure dropping custom dialog support will fix this, because we use custom dialogs in web and the cyclic dependency remains in web. It would be better to split layout service to break the cycle.

**Comment by bpasero** [comment] 2020-10-21 07:07
Ah yeah good point 👍 .

@sandy081 did you see my note, this is not related to layout service at all. This is because of theme service and keybinding service cycles.

**Comment by sandy081** [comment] 2020-10-21 07:28
Right, seems theme service and keybinding service are the root causes. And these services are pulling lot of services which pulls others and so on... so dialog service cannot be used in many of the services which is very unfortunate.

**Comment by bpasero** [comment] 2020-10-21 07:39
I think the issue is the other way around: extension service is used in a ton of places and services itself e.g. to wait when extensions are ready. As such you cannot use the dialog service in any service that is the extension service itself or depends on it I think. 

We depend on the dialog service successfully from some services like text-file service and workspace editing, so I think it is only an issue when the dependencies overlap but not for all.

In general I would agree though that the dialog service should be very lowlevel, similar to notifications service and not have too many dependencies.

**Comment by sandy081** [comment] 2020-10-21 07:45
I agree that dialog service should be a basic service not depending on other workbench services so that every service can use it - It seems Notification service is a very good example and depending only on storage service, so not sure why dialog service needs other dependencies.

**Comment by bpasero** [comment] 2020-10-21 08:57
Yeah I like that. Notifications have 1 model which is basically the service and then N listeners for UI pieces.

**Comment by sbatten** [comment] 2020-10-21 20:27
So the idea is that the service manipulates the model which acts as a man in the middle for a renderer which has the workbench dependencies, is that right?

**Comment by bpasero** [comment] 2020-10-22 06:14
@sbatten yeah, to explain how notifications do it:
* there is 1 [notification model](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/notification/common/notificationService.ts#L19-L20) that the `INotificationService` owns
* as such, the service has almost no dependencies
* the workbench creates "handlers" for notifications by passing the model in and listen to changes [here](https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/browser/workbench.ts#L368-L388)
* each time a notification is added, the handlers react

I needed this model for notifications anyway because notifications can appear in many different forms. For dialogs I think such a model could work as well:
* dialog service only has a model with events
* participants are either native or custom (depending on environment and settings)
* in this case though I think only one participant would ever handle a dialog request

As for the implementation, I see 3 options:
* you create a workbench contribution "dialog handler" that internally delegates to custom or native
* you create 2 new services "custom dialog service" and "native dialog service" that do the delegation

I feel like we do not need to have 2 more services, given that no-one would actually depend on them.

One gotcha: the handlers for the dialog requests need to make sure they do not forget any dialog requests that have been made before they got instantiated. Notification handlers do this too, e.g. here:

https://github.com/microsoft/vscode/blob/296b20afbacdaa2fea924f1a333330ff07db2cc4/src/vs/workbench/browser/parts/notifications/notificationsToasts.ts#L99-L99

**Comment by bpasero** [comment] 2020-10-22 06:16
Hm, I forgot a third solution which is maybe a lot less work: instead of requiring all the services directly from the native+browser dialog service, you could also depend on `IInstantiationService` and instantiate the handlers internally when you need them. This defers the need for these services to a later point and will prevent the cyclic dependencies. However, this is only safe if we are not having code that brings up a dialog directly from the constructor of a service. You could also defer the dialog instantiation to  a lifecycle phase where services have been created to prevent that from happening.

**Comment by sbatten** [comment] 2020-10-22 17:52
I think the notifications model is nice even if a bigger change. I will try that. Can I schedule this for next week @sandy081 ... I see this is marked as important

**Comment by sandy081** [comment] 2020-10-22 20:33
Yeah works for me. I am using a workaround for now to use Dialog Service.

**Closed** 2020-11-10 18:25 UTC
Labels: debt, dialogs, important

**Comment by bpasero** [comment] 2020-11-11 06:57
@sandy081 maybe you can remove your workaround now.
