### ISSUE TITLE
Switching back and forth in WebView View with retainContextWhenHidden causes ghost renders

### ISSUE THREAD

**Issue by agrawal-d** [microsoft/vscode#113188] opened 2020-12-20 14:25 UTC
Issue Type: <b>Bug</b>

With `retainContextWhenHidden=true`, there appears to be a rendering issue causing ghost/overlapping renders when the webview view changes when it is hidden.

https://user-images.githubusercontent.com/7714968/102715393-2599e800-42fb-11eb-8a1a-9406415dd270.mp4

**Steps to reproduce**

1. Have an extension using webview view, and `retainContextWhenHidden=true`. This extension renders something that changes whenever the active editor changes.
2. Navigate to a file that renders something on to the webview view,
3. Naviagte to Explorer view, such that the folders list replaces the webview view.
4. Open a file from the folders list, this makes the extension to bring the webview view to focus and render something else.
5. However, the previous *render* remains ( *only render, not the HTML/DOM* ) and overlaps with the new render.  **Resizing the view fixes this.** ( See attached video )

Just to make it clear, ( I think ) this is not a DOM/ programming error - i.e. there is no duplicate HTML being rendered - the ghost render does not exist in the DOM, but it can still be seen. I've verified from the inspect tool.

* This bug **does not** happen if the webview view never gets hidden, for example, simply changing between files from the top taps.
* This issue **does not**  occur if `retainContextWhenHidden=false`.

I'll be happy to provide more details/code.

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3448)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (7.43GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 26ab88de-1047-4753-becf-ad5aa2f24ccc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.14
competitive-programming-helper|Div|4.5.6
prettier-vscode|esb|5.8.0
flow-for-vscode|flo|1.5.0
code-runner|for|0.11.1
shell-format|fox|7.0.1
mips|kda|0.0.6
Kotlin|mat|1.7.1
rainbow-csv|mec|1.8.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
language-liquid|nei|0.1.1
LiveServer|rit|5.6.1
rust|rus|0.7.8
vscode-choosealicense|ult|0.4.0
clang-format|xav|1.9.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by mjbvz** [comment] 2020-12-21 03:17
Duplicate of #110450

**Closed by mjbvz** 2020-12-21 03:17 UTC

**Comment by agrawal-d** [comment] 2020-12-21 06:18
@mjbvz #110450 appears to be a bug with the positioning of the webview. This bug is about a rendering issue where the newly rendered content is painted over previous render, causing  'overlapping' appearance. I do not think this is related to positioning.

![image](https://user-images.githubusercontent.com/7714968/102745621-6852d300-4382-11eb-9162-b340fc6a03a5.png)

Are you sure these are the same issues?
