### ISSUE TITLE
WebAssembly.compile not defined

### ISSUE THREAD

**Issue by tareksander** [microsoft/vscode#205537] opened 2024-02-19 12:55 UTC
Does this issue occur when all (other) extensions are disabled?: Yes

````
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.1.0-18-amd64
````

Also in this insiders build:
````
Version: 1.87.0-insider
Commit: 11095a2781bd2a14cbaddc1b925f196f1e9452bc
Date: 2024-02-19T05:47:30.135Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.1.0-18-amd64
````

Steps to Reproduce:

1. Create a new extension from the VSCode extension template
2. Add a `console.log(WebAssembly.compile)`
3. Run the extension and open the devtools, you'll see a `null` message from the extension

I ran into this issue while trying to run [WASI in VSCode](https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi). I also made an issue for the WASI extension (microsoft/vscode-wasm#156), but it doesn't really have anything to do with WASI, just plain WASM, which should be available from Node.

**Comment by dbaeumer** [comment] 2024-02-26 08:33
I can't reproduce this on Ubuntu

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

not on Windows.

@deepak1556 any idea why the WebAssembly modules woule not be available on Node / Electron?

**Comment by dbaeumer** [comment] 2024-02-26 08:34
From the issue in the wasm repository

```
The WebAssembly global is defined, but it contains no functions. WebAssembly.compile is null.
```

**Comment by tareksander** [comment] 2024-02-26 08:53
> I can't reproduce this on Ubuntu

I'm running Debian 12.5, fully updated. I'm using the VSCode release from the tar archive, not the deb.

Running:
````js
for (let a of Object.entries(WebAssembly)) {
    console.log(a)
}
````
yields:
````
workbench.desktop.main.js:sourcemap:149 [Extension Host]% (2) ['compile', null]
workbench.desktop.main.js:sourcemap:149 [Extension Host]% (2) ['validate', null]
workbench.desktop.main.js:sourcemap:149 [Extension Host]% (2) ['instantiate', null]
````
in the console.

**Comment by dbaeumer** [comment] 2024-02-27 13:23
I tested this with Debian 12.5 and `WebAssembly.compile` exists for me:

![Image](https://github.com/microsoft/vscode/assets/1931590/1b0a195e-d313-4d8b-b996-eb696e2a2646)

**Comment by tareksander** [comment] 2024-02-27 18:05
I just checked again, and what's weird is that in the chrome devtools inside VSCode, WebAssembly exists, and when I install the extension it works, too, but if I test the extension via `code --extensionDevelopmentPath="$(pwd)"` in the project, it doesn't work. All other extension functions work normally like that though.

**Comment by dbaeumer** [comment] 2024-02-28 07:56
What happens if you use an `extensionHost` launch config inside VS Code?

**Comment by tareksander** [comment] 2024-02-28 09:44
Ok, maybe it's a bug in how the console gets wired up when using `extensionDevelopmentPath`? Because the console shows null, while `vscode.window.showInformationMessage("compile: " + WebAssembly.compile)` shows `compile: function compile() { [native code] }`, same with the default generated launch config:
````json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			]
		}
	]
}
````

Then it should actually work, but I can't get Typescript to recognize the WebAssembly global when using the Typescript extension template.

**Comment by dbaeumer** [comment] 2024-03-01 14:52
> I can't get Typescript to recognize the WebAssembly global when using the Typescript extension template.

You need to configure the TS compiler to know about the webworker libraries which define the `WebAssembly` global.

**Comment by dbaeumer** [comment] 2024-03-01 14:53
I will close the issue since things should work for you now.

**Closed by dbaeumer** 2024-03-01 14:53 UTC
Labels: info-needed
