### ISSUE TITLE
Feature request for folding code guides

### ISSUE THREAD

**Issue by saidbakr** [Microsoft/vscode#37479] opened 2017-11-02 07:55 UTC
![nb](https://user-images.githubusercontent.com/467554/32315101-7d981c1c-bfb3-11e7-86cf-f5e91306113d.png)
The above screen shot is from other IDE. I suggest to allow VSCode to render the white line on the left for code folding. It is important visual aid that allows easier follow code blocks.

**Comment by aeschli** [comment] 2017-11-10 09:56
duplicate of #25132

**Closed by aeschli** 2017-11-10 09:56 UTC
Labels: editor, editor-folding
