### ISSUE TITLE
[Bug] When opening files of encoding GB-2312, File is truncated if one character's DBCS 2-byte code crosses multiple of 64k border 

### ISSUE THREAD

**Issue by WilliamStone** [microsoft/vscode#101856] opened 2020-07-07 14:30 UTC
The attached file is exactly 128KB+1 bytes long. The file is in encoding GB-2312. The 1st character in it is one byte, and other characters are all 2 bytes. So the 32k-th character's 2-bytes code is at file index of 64k and 64k+1. 
Open the file in VSCode, and the loaded content is only first 64k bytes of the file, and remaining contents are truncated. Save the loaded file back to disk, and the resulting file is also only 64KB long.
This bug happens **at the first 2-byte character that crosses multiple of 64KB border**, e.g. 128KB, 1024KB, etc. In other words, if there occasionally isn't any character in the file occasionally whose 2 bytes cross multiple of 64K border, the file will load normally, and not get truncated.

This is a recent bug. Today I reinstalled windows 10 and VSCode and found this bug. Before today all is normal.

Version: 1.47.0-insider (user setup)
Commit: e95f9e63380a139cb1cbe54bacfc6703b96e30b9
Date: 2020-07-07T07:46:21.608Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

[Test.txt](https://github.com/microsoft/vscode/files/4885398/Test.txt)

**Comment by bpasero** [comment] 2020-07-07 15:52
Hm, this looks like a regression from the encoding work we did during the milestone.

I see this exception in the console:

```
 ERR "list" argument must be an Array of Buffers: TypeError: "list" argument must be an Array of Buffers
    at Object.c.concat (/Users/bpasero/Development/Microsoft/monaco/node_modules/iconv-lite-umd/lib/iconv-lite-umd.js:8:7832)
    at c.write (/Users/bpasero/Development/Microsoft/monaco/node_modules/iconv-lite-umd/lib/iconv-lite-umd.js:10:28377)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/textfile/common/encoding.js:64:42
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/stream.js:170:57
    at Array.forEach (<anonymous>)
    at WriteableStreamImpl.flowData (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/stream.js:170:37)
    at WriteableStreamImpl.resume (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/stream.js:56:22)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/textfile/common/encoding.js:77:49
```

@gyzerok @ashtuchkin any clues?

**Comment by bpasero** [comment] 2020-07-07 15:57
This seems to originate from this method:

```
Buffer.concat = function concat (list, length) {
  if (!isArray(list)) {
    throw new TypeError('"list" argument must be an Array of Buffers')
  }

  if (list.length === 0) {
    return Buffer.alloc(0)
  }

  var i
  if (length === undefined) {
    length = 0
    for (i = 0; i < list.length; ++i) {
      length += list[i].length
    }
  }

  var buffer = Buffer.allocUnsafe(length)
  var pos = 0
  for (i = 0; i < list.length; ++i) {
    var buf = list[i]
    if (!Buffer.isBuffer(buf)) {
      throw new TypeError('"list" argument must be an Array of Buffers')
    }
    buf.copy(buffer, pos)
    pos += buf.length
  }
  return buffer
}
```

`Buffer.isBuffer` fails because `buf` in this case is `Uint8Array`

**Comment by bpasero** [comment] 2020-07-07 16:21
Digging into `Buffer.isBuffer`, I wonder if this is an issue with passing a real node.js `Buffer` into the webpacked version. Because that one seems to do this in `isBuffer`:

```js
Buffer.isBuffer = function isBuffer (b) {
  return !!(b != null && b._isBuffer)
}
```

This actually makes me a bit nervous (because we want to ship a new stable version this week) and I wonder if we can somehow distill a minimal fix from https://github.com/microsoft/vscode/commits/release/1.47 which is already branched off on Friday before I merged the PRs that lead to the web support for encodings.

**Comment by bpasero** [comment] 2020-07-07 16:51
I see 2 minimal fixes that both are a bit risky, unless there is a fix I am not seeing yet:
* switch back to `iconv-lite` where currently `iconv-lite-umd` is being used
* convince `iconv-lite-umd` to not shim `Buffer`

I tried [2] via `node: false` in the web pack config, but did not get it to work. No matter what, the `Buffer` shim ended up in the output. 

Have to log off now, but we need a solution tomorrow at least. If I see no other reply, I will probably go with option [1].

**Comment by bpasero** [comment] 2020-07-07 17:08
Actually there is a solution [3]: `iconv-lite-umd` exposes all methods from `iconv-lite` but makes sure to call `Buffer.from(uint8Array)` before passing on to `iconv-lite`. This would ensure that the correct `Buffer` type ends up in the library. 

The downside is that each call into the library will have to pay the price of creating the `Buffer`, but I would hope that this cost is minimal in the shimmed version of `Buffer` if you pass over a `Uint8Array`.

**Comment by gyzerok** [comment] 2020-07-08 01:25
@bpasero I am currently on it.

The footgun is located [here](https://github.com/ashtuchkin/iconv-lite/blob/v0.6.1/encodings/dbcs-codec.js#L496). It seems like it's some corner case I missed when making a patch for `iconv-lite` and new tests I added there didn't catch this case.

Can't get `node: false` to work either. However it works if you set `target: node`. This is a bit of a hotfix, however [Alex already have made the patch to support `Uint8Array`s directly](https://github.com/ashtuchkin/iconv-lite/commit/21004dd4c642b76575449d6bdd4de72a834b965b) it is just not released yet. So shouldn't be a problem for us to remove this hotfix for the July release.

I have tested hotfix myself with the provided file and everything seems to work. Test suite also works completely.

Here is a setup for you, so you can test it yourself quickly: `mkdir vscode-hotfix && git clone https://github.com/gyzerok/vscode vscode-hotfix && cd vscode-hotfix && git checkout encoding-hotfix-test`

This will install my custom `iconv-lite-umd` with https://github.com/gyzerok/iconv-lite-umd/commit/28088a01f1e9e1659f0cfa04b083ee93f8b12911#diff-11e9f7f953edc64ba14b0cc350ae7b9dR19.

**Comment by ashtuchkin** [comment] 2020-07-08 05:26
I've released v0.6.2 with the fix

**Comment by bpasero** [comment] 2020-07-08 06:13
@gyzerok @ashtuchkin thanks for the fast turn around, here is my suggestion going forward:
* for VSCode June release I will use `iconv-lite-umd@0.6.7` with `target: "node"` (via https://github.com/microsoft/iconv-lite-umd/commit/452c60a351cccf5c9f553d20ef73b3aed717c214)
* for VSCode July release I will jump onto `iconv-lite@0.6.2` and remove the `target: "node"` config

Does that sound reasonable?

**Comment by gyzerok** [comment] 2020-07-08 06:48
@bpasero this sounds like the safest way forward 👍

**Comment by bpasero** [comment] 2020-07-08 07:02
@gyzerok just to add more options to the table: alternatively using `iconv-lite@0.6.1` instead of `iconv-lite-umd` would maybe be the safest option, no? At least that rules out any potential regressions from webpacking and would go back to the direct use of  `iconv-lite` as we used to have it.

**Comment by gyzerok** [comment] 2020-07-08 07:14
@bpasero I agree, it would be definitely even safer. However I would personally expect webpack to be trustable enough to not mess things up by itself.

**Comment by bpasero** [comment] 2020-07-08 07:16
Yeah, and I was able to run the `iconv-lite` tests against the `target: "node"` version with all tests passing, that gives me confidence.

**Closed** 2020-07-08 07:51 UTC
Labels: bug, candidate, file-encoding, file-io, important, regression

**Comment by bpasero** [comment] 2020-07-08 08:26
We have a fix for the June release, but for insiders this is still pending a proper fix that also works in web. I opened https://github.com/microsoft/vscode/issues/101905 to track that.
