### ISSUE TITLE
Surface pro has a lighter color on the vscode interface when it comes with an external monitor

### ISSUE THREAD

**Issue by BenzLeung** [Microsoft/vscode#73036] opened 2019-04-29 13:26 UTC
Issue Type: <b>Bug</b>

On my surface pro 5, an external monitor is attached to expand the display. The display of vscode on the external display is correct. But the appearance on the surface pro screen seems to be wrong. The interface color has become lighter.

The surface pro has a display zoom ratio of 200% and an external monitor that is 100%.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.43
auto-close-tag|for|0.5.6
terminal|for|0.0.10
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.4.11987
vscode-wechat|qin|0.0.6
vscode-yaml|red|0.4.0
html-css-class-completion|Zig|1.18.0

</details>

![image](https://user-images.githubusercontent.com/2764768/56898993-f2229e00-6ac4-11e9-8112-41c85d15a23b.png)

**Comment by RMacfarlane** [comment] 2019-04-29 16:18
Duplicate of https://github.com/Microsoft/vscode/issues/68741

**Closed by RMacfarlane** 2019-04-29 16:18 UTC
