### ISSUE TITLE
JSDoc callbacks unsupported in Node.js

### ISSUE THREAD

**Issue by Wunder-Wulfe** [Microsoft/vscode#32415] opened 2017-08-13 13:38 UTC
VSCode with Node.js does not allow me to use callbacks when using JSDoc comments.

![Attempt#1](https://i.gyazo.com/b849fbf460efcaed9f1a99d26d65ff85.png)

I have to do things like:

```Node.js
/**
* @param {function(type):type} arg desc
*/
```

but then it adds these weird 'arg0, arg1, arg2...' to it when i would rather it say something like

`response: string`

![Attempt#2](https://i.gyazo.com/12ac400af1c952fe0458d24493ed1ee1.png)

**Comment by EternalPhane** [comment] 2017-08-16 02:53
see Microsoft/TypeScript#7515.

**Comment by mjbvz** [comment] 2017-08-16 03:55
Thanks @EternalPhane!

Yes, this is tracked upstream of Microsoft/TypeScript#7515. Closing as a duplicate of Microsoft/TypeScript#7515.

**Closed by mjbvz** 2017-08-16 03:55 UTC
Labels: javascript, upstream
