### ISSUE TITLE
there is NO Scrolling Bar in the Integrated Terminal Panel

### ISSUE THREAD

**Issue by axdhxyzx** [Microsoft/vscode#9563] opened 2016-07-21 04:36 UTC
- VSCode Version: 1.3.1
- OS Version: OS X EI Capitan 10.11.5

Steps to Reproduce:

1. In a word, there is NO Scrolling Bar in the Integrated Terminal Panel, and I can't scroll view up to top to review more information.

2. Detail:
 In the **Integrated Terminal Panel**, execute ```dotnet run``` command, then visit ```http://localhost:5000/api/values/5``` in the Chrome browser, response 500 status code(*I leave an error in my codes purposely, so as to generate more information*) from server side. Back to VSCode, in the Integrated Terminal Panel output information more than shown at Panel's Height, but **MISSING the Scrolling Bar** in the panel, result in failing to scroll view up to review entire exception information. At present, only via resizing the height of Integrated Terminal Panel for looking more output info up.

**Comment by kieferrm** [comment] 2016-07-21 22:00
Duplicate of #6602.

**Closed by kieferrm** 2016-07-21 22:00 UTC
Labels: duplicate
