### ISSUE TITLE
Diff Editor Tab Now Marked Read-Only

### ISSUE THREAD

**Issue by chuckeng** [microsoft/vscode#137663] opened 2021-11-22 17:31 UTC
When I installed the latest version of VSCode (both regular and insiders), I now find that the diff side-by-side *editor* is marked as read-only.

<img width="114" alt="image" src="https://user-images.githubusercontent.com/76965795/142906954-049f6723-4c9c-4893-a438-7bc577fc9386.png">

<img width="231" alt="image" src="https://user-images.githubusercontent.com/76965795/142907933-10199103-8713-4531-a24d-40948b56bdf0.png">

I have disabled all extensions and tested on both regular and insiders and the *problem* still persists.

I am hoping that this is a bug (mistake) or an early April fools joke. Or, that there is some way to re-enable the original behavior.

The ability to look at changes and make subtle edits is very important. And, there is no easy way to jump to the location of change in the normal file. You can only right-click and Open File, which lands you in the file, but does not take you to the location of the change you were looking at. When there are 10s or 100s of similar changes and you finally track down the one causing the issue, and you want to make only a slight edit (change a character or two), the task to do this is error prone and an exhausting labor intensive process.

**Comment by gjsjohnmurray** [comment] 2021-11-22 18:19
The ' (Index)' suffix on the filename before the lock icon (denoting readonly) is unusual.

Where are you launching the diff from? Maybe the Timeline pane?

Are you using git as your source control?

**Comment by chuckeng** [comment] 2021-11-22 18:31
Left clicking in the SCM window (using git). This pulls up the diff window for the change.

**Comment by chuckeng** [comment] 2021-11-22 19:01
Oh, the changes I have are "staged" (in the cache).

**Comment by IllusionMH** [comment] 2021-11-22 19:25
You can edit unstaged changes, but staged changes can't be edited directly without `git add`. Therefre when you open staged diffs they are always read-only and were this way for a long time (probably from the beginning).

You can use button above diff editor to quickly navigate to same position in editable file https://github.com/microsoft/vscode/issues/91274#issuecomment-590442267

I think request to make them readable is no-go and and will be closed as duplicate of https://github.com/microsoft/vscode/issues/91274

**Comment by chuckeng** [comment] 2021-11-22 19:54
Well, I really wish I could edit the current file in the buffer.

But, now at least I understand.

**Closed** 2021-11-22 20:02 UTC
