### ISSUE TITLE
code reminder empty and vscode icon error

### ISSUE THREAD

**Issue by jingchenxu** [Microsoft/vscode#23407] opened 2017-03-28 12:34 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (0b19861f31ed27160c8ea73e55e39dd0213814a6, 2017-03-28T10:48:32.966Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.5|
|color-info|bierner|0.3.0|
|vscode-express|Compulim|0.0.5|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|file-icons|file-icons|1.0.3|
|vue-snippets|hollowtree|0.1.1|
|vue|liuji-jim|0.1.5|
|vscode-jade-snippets|mrmlnc|1.0.1|
|vscode-pugbeautify|mrmlnc|1.0.2|
|vscode-puglint|mrmlnc|2.3.0|
|debugger-for-chrome|msjsdiag|2.7.1|
|vetur|octref|0.5.6|
|java|redhat|0.0.13|
|vscode-icons|robertohuertasm|7.4.0|
|stylelint|shinnn|0.23.0|
|code-spell-checker|streetsidesoftware|1.0.2|
|jsx|TwentyChung|0.0.1|
|ReactSnippets|xabikos|1.2.1|
|Material-theme|zhuangtongfa|2.3.3|;

---

Steps to Reproduce:

1.      
2.

![](https://dn-shimo-image.qbox.me/x2T5GiUKuKkUH9SX/QQ%E6%88%AA%E5%9B%BE20170328202847.png!thumbnail)

![](https://dn-shimo-image.qbox.me/1Ydd0REYqT0DJD0s/QQ%E6%88%AA%E5%9B%BE20170328202920.png!thumbnail)

**Comment by aeschli** [comment] 2017-03-28 13:03
duplicate of #23414

**Closed by aeschli** 2017-03-28 13:03 UTC
