### ISSUE TITLE
Typing a dot in a string literal selects first item in auto-suggest

### ISSUE THREAD

**Issue by use-strict** [Microsoft/vscode#11824] opened 2016-09-10 10:00 UTC
- VSCode Version: 1.6.0-insider
- OS Version: Windows 7

Steps to Reproduce:

```typescript
interface Options {
    webpackConfig: string;
}
let opts: Options = {
    webpackConfig: "./webpack.config.js"
    //                       ^ typing dot here autocompletes with "webpackConfig"
}
```

Expected behavior:
Auto-suggest should trigger when pressing ENTER (or maybe TAB?), but not on dot

Actual behavior:
When typing a dot (`.`), auto-suggest selects the first item

Workaround:
Pressing escape before the dot. Very annoying!!

**Comment by ramya-rao-a** [comment] 2016-09-11 16:55
@use-strict I used your code and couldn't get any suggestions on `.`.
I get suggestion for "webpackConfig" when typing "webpack" but not after the `.`

Can you share your user settings so that we can try to repro this?

**Comment by use-strict** [comment] 2016-09-11 19:51
I'm not sure if we're on the same page: first you type `webpack` and get a suggestion dropdown with `webpackConfig`. Then you type the dot and it should select the suggestion, preventing you from typing `webpack.` and replacing it with `webpackConfig`.

**Comment by ramya-rao-a** [comment] 2016-09-11 19:55
> first you type `webpack` and get a suggestion dropdown with `webpackConfig`

Yes, I got the suggestion dropdown.

> Then you type the dot and it should select the suggestion

No, it did not select the suggestion when I typed the dot

Therefore, I am asking for your user settings to see if something there is causing this for you

**Comment by use-strict** [comment] 2016-09-11 21:14
User settings:
```json
{
    "window.zoomLevel": 2,
    "typescript.tsdk": "D:\\Settings\\npm\\node_modules\\typescript\\lib",
    "diffEditor.renderSideBySide": false,
    "editor.rulers": [80, 120],
    "editor.referenceInfos": false,
    "editor.folding": false,
    "terminal.external.windowsExec": "C:\\Program Files\\Git\\git-bash.exe"
}
```

Workspace settings:
```json
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/node_modules": true
    },
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```

I'm using tsc 2.0.2 in this project, if anything that would be the primary suspect.

**Comment by use-strict** [comment] 2016-09-11 21:17
And the real-life project where I encountered the issue: https://github.com/use-strict/webpack-runner/blob/master/test/test.ts#L78

**Comment by jrieken** [comment] 2016-09-13 14:23
@use-strict What does your keybindings read like (both sides)? Note that usually `.` is bound to accept a selection if auto-acceptable. TypeScript suggestions are, textual aren't. Also what in what language do you see this?

**Comment by use-strict** [comment] 2016-09-13 16:34
My keybindings are:
```json
[
    {
        "key": "ctrl+d",
        "command": "editor.action.deleteLines",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+e",
        "command": "workbench.action.quickOpen"
    }
]
```

The link in my previous comment shows the exact line where I get this behavior.

> Note that usually . is bound to accept a selection if auto-acceptable

I'm not sure what you mean by this. Even if it weren't a string literal, accepting a suggestion by typing dot would be problematic (unless maybe there is a single suggestion). Still it would be a weird behavior.

**Comment by jrieken** [comment] 2016-09-13 17:38
In the *default* keybinding configuration you will find this

```
{ "key": ".",                     "command": "^acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'typescript'" },
```

which means insert selected suggestion *and* insert `.` when `.` is pressed, the file is TypeScript and when the suggestion is auto-acceptable. This is useful for instance when completing and triggering member completion at once (type `cons`, press `.` such that it completes to `console.` and triggers suggest against, hit `tab` such that it completes to `console.log`). Other language may have other accept characters defined, users can un-configure this.

Still, from your steps it's not clear what you are actually doing. To get a better understand of your words: 

> Auto-suggest should trigger when pressing ENTER (or maybe TAB?), but not on dot

I assume you mean by 'trigger' insert from an active suggest window and not show suggestions, correct? 

I have tried both variation and I cannot reproduce. Please update the your step and attach an animated gif. 

![sep-13-2016 19-37-40](https://cloud.githubusercontent.com/assets/1794099/18484630/903d9452-79e9-11e6-9595-e8c9a9442a6f.gif)

**Comment by use-strict** [comment] 2016-09-13 20:58
> I assume you mean by 'trigger' insert from an active suggest window and not show suggestions, correct?

Correct

While trying to reproduce this again with a minimal project, I noticed that it does not reproduce with ts 2.0.0 and no workspace settings. It only reproduces with 2.0.2, installed in the project folder with `npm install` and `"typescript.tsdk": "./node_modules/typescript/lib"`

Judging from your gif, I realize I've also mislead you without realizing. This gif will hopefully clarify that:
![Auto-suggest](http://i.imgur.com/3PkEoXm.gif)

**Comment by jrieken** [comment] 2016-09-19 08:22
ok - it seems like TypeScript is giving you completions in string literals. Unsure if this is a bug or not - @dbaeumer or @waderyan will know. For the auto-acceptability we have issue #7326 and I'll close this issue as duplicate

**Closed by jrieken** 2016-09-19 08:22 UTC
Labels: needs more info, suggest

**Comment by dbaeumer** [comment] 2016-09-19 08:24
@waderyan can you look into this please.

**Comment by waderyan** [comment] 2016-09-21 20:59
I looked into this and was able to reproduce. This seems to be a bug. 

![image](https://cloud.githubusercontent.com/assets/2449568/18728763/8e0c8f60-8003-11e6-81df-7b8f46a988ad.png)

**Comment by waderyan** [comment] 2016-09-21 20:59
This issue was moved to Microsoft/TypeScript#11044
