### ISSUE TITLE
Save As... infinite loop

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#45414] opened 2018-03-09 15:40 UTC
Issue Type: <b>Bug</b>

I opened a file, then `File -> Save as...`, Saved the file as `gamePlays.blade.php` pressed save and it created an endless loop of directories.

1. Open a folder
1. Open a file in the workspace
1. Click on a folder in the explorer (Might have to be empty, I am not sure)
1. `File -> Save As...` (`Save as type` might need to be Plane Text, I am not sure here either)
1. Give the file a name
1. Click `Save`

![createfile](https://user-images.githubusercontent.com/1571806/37215550-dbd67f0c-237d-11e8-8225-4fd295c95c5a.PNG)

Here is what the save screen looked like:

![save-screen](https://user-images.githubusercontent.com/1571806/37216953-dbcf136c-2381-11e8-9cd5-a2e2ccd61850.PNG)

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|15.69GB (4.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kieferrm** [comment] 2018-03-09 17:12
Can you reproduce it or was this a one off? If you can reproduce it does that happen only in a specific parent directory or anywhere? Is there anything special about the parent directory? Is it an a remote drive or something along those lines?  Thanks a ton.

**Comment by TheColorRed** [comment] 2018-03-09 17:30
It is kinda one off, but still doesn't work.

When I have a folder selected (and focused) in the explorer, that is when it somewhat happens. When I focus on a folder in the explorer, while having the file open in the workspace, it saves the selected folder instead of the file. I am not sure why it did a recursive save like the image above though. I can't seem to reproduce the infinite loop at the moment.

**Comment by TheColorRed** [comment] 2018-03-09 17:31
Okay figured it out.

If you have an empty folder and have it focused, then do a save as, it does a recursive save on that folder.

**Comment by kieferrm** [comment] 2018-03-09 18:08
Confirmed. 

1) empty folder needs to be selected
2) File>Save As with defaults, just type a name
3) Expand the empty folder in the explorer

**Comment by bpasero** [comment] 2018-03-09 18:38
@kieferrm I cannot reproduce:

![before](https://user-images.githubusercontent.com/900690/37223624-67c764c4-23d1-11e8-9344-3ccb62d31a6d.gif)

**Comment by TheColorRed** [comment] 2018-03-09 18:39
after typing text, click on the folder before saving

**Comment by bpasero** [comment] 2018-03-09 18:42
@TheColorRed I do not follow, since you seem to be able to reproduce can you do a screen recording? Or @kieferrm ?

**Comment by TheColorRed** [comment] 2018-03-09 18:46
![recursive save](https://user-images.githubusercontent.com/1571806/37224016-e06bb3ba-2397-11e8-9535-60b52834117c.gif)

**Comment by bpasero** [comment] 2018-03-10 09:24
@isidorn exact steps:
* open an empty workspace
* create one file and save it
* create an empty folder
* open the created file
* select the empty folder in the explorer
* File > Save As
* Select the empty folder and save as a file within
* Hit Save

The issue is that the [`fileCommand#save()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L84) method is using the selection of the explorer for the operation instead of the currently active file. As such you end up saving the selected empty folder as child of itself, which recurses endlessly. I think I should guard against this issue better by not allowing to copy a file/folder into itself, however we also need a fix for this issue where we use the currently active editor and not the selection in the explorer.

I see that this may be tricky to fix though because you probably need to respect the selection of the open editors view at least for the right click > save as command.

**Comment by TheColorRed** [comment] 2018-03-10 13:35
@bpasero @isidorn 

I did notice that if the directory isn't empty and the same steps are taken, it just copies the contents of that directory into the newly created one. It doesn't recursively create directories like in the previous case though.

**Comment by isidorn** [comment] 2018-03-12 09:52
I can reproduce this in last 2 stables. So I think this is not a candidate - nobody hit it in more than a month.
I can also reproduce in insiders, but not when running out of source - I nicely get the error `Unable to move/copy when source path is parent of target path`. 
@bpasero it seems your fix 1c91b6ba4a fixes this issue

**Comment by bpasero** [comment] 2018-03-12 14:18
I am fine moving this to March given the little impact so far.

**Comment by isidorn** [comment] 2018-03-12 14:24
After discussing in the standup we decided this is not a candidate since it has been in stable for 30+days already and nobody noticed. For rare people that are affected they can switch to insiders wihch contains a fix.

@bpasero has pushed a fix to master to not allow recursive writes.
I have pushed a fix that for commands coming from the main menu the lists are ignored. @bpasero check out the commit and let me know if you have a better idea how to solve this. I tested and it works nicely

**Closed** 2018-03-12 14:24 UTC
Labels: bug, candidate, important

**Comment by bpasero** [comment] 2018-03-12 14:38
@isidorn ugh, relying on that context will likely not work for other invocations like triggering "Save As" via keybinding or even from the command palette, have you tested those cases?

**Comment by isidorn** [comment] 2018-03-12 14:43
@bpasero triggering from the command palette will work nicely since the list no longer has focus.

Triggering via keybinding makes sense to respect the explorer if you are focused in the explorer. So seems to work fine imho. With the addition of this null check 66a44df0db

**Comment by bpasero** [comment] 2018-03-12 15:02
@isidorn well you could maybe turn it around and handle the context-menu case specially in the "Save As" command, isn't that the only time where we want the list selection to be used?

**Comment by isidorn** [comment] 2018-03-12 15:08
@bpasero agree that it might be better to handle this in the "Save As" command. Not sure if that is the only command where we want to ignore the list selection - I did it the current way to just handle all the top menu commands.
Will do it only for the save as since that fix is more localized.
