### ISSUE TITLE
Process explorer flickers when updating and prevents hover

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102932] opened 2020-07-20 09:02 UTC
The process explorer seems to replace its entire HTML content every second resulting in:
* flicker
* you cannot hover over an item to see the command line because hover goes away

Can we switch to a model where only the text inside each cell is updated, but the HTML structure otherwise left as is?

![image](https://user-images.githubusercontent.com/900690/87919712-808f9080-ca78-11ea-881d-f0ca9a35c34b.png)

**Comment by RMacfarlane** [comment] 2020-11-03 19:22
Closing as a duplicate of https://github.com/microsoft/vscode/issues/104013

**Closed by RMacfarlane** 2020-11-03 19:22 UTC
Labels: bug, workbench-diagnostics
