### ISSUE TITLE
JavaScript IntelliSense NOT WORK In HTML file

### ISSUE THREAD

**Issue by shuaihuGao** [Microsoft/vscode#56580] opened 2018-08-16 15:47 UTC
Hi .
Sir.
Now JavaScript IntelliSense Can't Work in HTML File . It's Only can work with Jquery.

**Comment by shuaihuGao** [comment] 2018-08-18 15:49
Oh.
 i found that it could not automatically find d.ts files.

**Comment by mjbvz** [comment] 2018-08-20 09:41
Please provide repo steps and example code that explains what is now working

**Comment by shuaihuGao** [comment] 2018-08-24 10:55
jsconfig.json Setting as this.
<img width="758" alt="01" src="https://user-images.githubusercontent.com/29368118/44581171-3e4b6f00-a7cf-11e8-87c6-a1f698adfaee.png">

**Comment by mjbvz** [comment] 2018-09-05 01:05
Thanks. After reviewing your example, this is a duplicate of #26338

**Closed by mjbvz** 2018-09-05 01:05 UTC
Labels: javascript, needs more info
