### ISSUE TITLE
Custom editor search functionality crashes visual studio code

### ISSUE THREAD

**Issue by XyntaxCS** [microsoft/vscode#185577] opened 2023-06-19 13:43 UTC
Type: <b>Bug</b>

We are currently writing our own extension to support the coq language using coq-lsp. The extension will be published on the market place very soon under the name Waterproof. Our extension supports multiple panels to be open at the same time displaying different information. Now, in these panals we would like to support search functionality to search through text in these panels. When we have enabled this search functionality we can use it to search terms in this panel. However, when we enter text in the search functionality and click to another panel it crashes the entirety of visual studio code, shutting it down. This only happens when text is present in the search bar. When there is no text one can click to other tabs without crashing. I will update this issue once the extension has been published.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.41GB free)|
|Process Argv|--crash-reporter-id 82c2e57f-aedd-43c4-9103-1af4520c6113|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
coq-lsp|ejg|0.1.6
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
remote-wsl|ms-|0.79.5
js-debug-nightly|ms-|2023.6.1315
vsliveshare|ms-|1.0.5873

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
dh2dc718:30770000

```

</details>

**Comment by mjbvz** [comment] 2023-06-19 18:31
Duplicate of #177046

**Closed by mjbvz** 2023-06-19 18:31 UTC
