### ISSUE TITLE
Native menu labels are invisible in Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62593] opened 2018-11-05 13:58 UTC
This is a fresh Ubuntu 18.10 install, just downloaded Code Insiders and ran it. Toolbar menu is gone.

<img width="1038" alt="screenshot 2018-11-05 at 13 57 08" src="https://user-images.githubusercontent.com/22350/48002198-ba80fd80-e102-11e8-87c0-c3b4beac2038.png">

**Comment by joaomoreno** [comment] 2018-11-05 13:59
Why aren't we already using custom menus in Linux too?

**Comment by joaomoreno** [comment] 2018-11-05 14:05
Actually, this is latest stable 1.18.2:

<img width="1042" alt="screenshot 2018-11-05 at 14 05 05" src="https://user-images.githubusercontent.com/22350/48002570-d638d380-e103-11e8-890c-cf87de0d1065.png">

So, setting this as a candidate.

**Comment by joaomoreno** [comment] 2018-11-05 16:12
Could be related to new dark mode cc @isidorn

**Comment by isidorn** [comment] 2018-11-05 16:52
@sbatten can you please investigate and I can continue investigating tomorrow our time - going home now.
Dark mode should only affect OS X, not linux afaik.

**Comment by sbatten** [comment] 2018-11-05 19:35
It seems this is an issue with electron and only comes up in specific GTK themes. Electron changed the way menubars are themed pulling the background correctly from the themes menubar background color. However, they still pull the menubar foreground color from the theme context menu foreground color. Since the Yaru theme use light context menus with a dark menubar, we are left with dark text on a dark background. You can workaround this issue by using Yaru-dark or Adwaita theme on Ubuntu 18.10 using the Gnome Tweaks app.

**Comment by isidorn** [comment] 2018-11-06 08:30
@sbatten great investigation. This sounds fair to me, I would remove the candidate label and October since we have a workaround in the release notes.
@joaomoreno is that ok for you?

**Comment by joaomoreno** [comment] 2018-11-06 08:39
> You can workaround this issue by using Yaru-dark or Adwaita theme on Ubuntu 18.10 using the Gnome Tweaks app.

This is not great. Notice the issue happens with brand new installations of VS Code and latest Ubuntu.

If there is a low-risk change to fix this, even if temporarily, I'd still take it for October.

**Comment by joaomoreno** [comment] 2018-11-06 08:47
Confirmed that this happens too on vanilla Electron:

![image](https://user-images.githubusercontent.com/22350/48052684-92e07280-e1a0-11e8-85be-e4579320e010.png)

**Comment by joaomoreno** [comment] 2018-11-06 08:48
This is https://github.com/electron/electron/issues/15194

**Comment by joaomoreno** [comment] 2018-11-06 08:50
This is actually https://github.com/Microsoft/vscode/issues/60600 ...

**Comment by isidorn** [comment] 2018-11-06 08:52
I misunderstood and thought that this only happens for a custom theme, however this happens for the default ubuntu theme. Agree this should still be a candidate, let's discuss more in standup...

**Comment by isidorn** [comment] 2018-11-06 09:10
After discussions in Zurich we think this should be fixed. Reason being it happens on the out of the box Linux experience and is quite bad.
@sbatten is there some workaround we could do for the release? What would it take for us to fix this?

**Comment by joaomoreno** [comment] 2018-11-06 09:28
I can reproduce this in Electron 2.0.12, 2.0.13, 3.0.7, 4.0.0 nightly 20181010

**Comment by joaomoreno** [comment] 2018-11-06 14:22
This doesn't reproduce with Electron 2.0.9, so this was caused by the Electron update. cc @bpasero @Tyriar 

Given that there is no easy fix (@sbatten can confirm whether there is one), there are three possibilities:

- Ship it and get a big disclaimer in the release notes that you should switch themes
- Revert to Electron 2.0.9
- Enable custom menus in Linux, as it is already in Windows

**Comment by kieferrm** [comment] 2018-11-06 16:12
@sbatten @joaomoreno

Rolling back to 2.0.9 has a bunch of other side effects and we need something that works for new and existing users. For new users we don't show the release notes.

Proposal:
- test custom menus on Linux to be sure we can recommend them
- create an FAQ entry that talks about the issue
- we test for the issue on startup, when we detect it we show an alert that recommends enabling custom menus and provides the link to the FAQ for more details

**Comment by joaomoreno** [comment] 2018-11-06 17:16
A new update: this doesn't repro on the default theme of 18.04, so it could just affect 18.10 users as well as people who use that specific theme and similar ones. So, it might not hit as many people as we think.

![image](https://user-images.githubusercontent.com/22350/48081295-92b79580-e1e7-11e8-84e8-ac00366e9fdf.png)

FYI, I'm self hosting on custom menus since 2 months.

**Comment by ZanderBrown** [comment] 2018-11-06 23:17
Not sure how it will help you but in Gtk colours are managed but [GtkStyleContext](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html), You should be able to set a dummy widget path to get the right colour for a menubar. I'd also like to point out that from Gtk's perspective anything other than Adwaita is a custom, unsupported, theme even if it's the default of a major distribution.

To do this in C would be something like so:
```c
GtkWidgetPath   *path;
GtkStyleContext *ctx;
GdkRGBA          rgba;

path = gtk_widget_path_new ();
gtk_widget_path_append_type (path, GTK_TYPE_WINDOW);
gtk_widget_path_append_type (path, GTK_TYPE_MENU_BAR);
gtk_widget_path_append_type (path, GTK_TYPE_MENU_ITEM);
gtk_widget_path_append_type (path, GTK_TYPE_ACCEL_LABEL);

ctx = gtk_style_context_new ();
gtk_style_context_set_path (ctx, path);
gtk_style_context_set_screen (ctx, gdk_screen_get_default ());

gtk_style_context_get_color (ctx, 0, &rgba);
```

**Closed** 2018-11-07 07:37 UTC
Labels: bug, candidate, electron, upstream, workbench-menu

**Comment by jflambert** [comment] 2018-11-13 14:39
I'm affected, using stock Ubuntu 18.04 desktop, since downloading the 1.29 update this morning (wasn't a problem in 1.28)

Let me know what kind of info I can provide. For now I've just disabled the menu bar.

![vscode](https://user-images.githubusercontent.com/11539524/48420235-f5e58280-e727-11e8-8746-3dff84e041ff.png)

**Comment by sbatten** [comment] 2018-11-13 22:33
@jflambert do you know what theme is currently enabled on your Ubuntu machine? Could you provide a screenshot of vs code open with the menu enabled and a context menu open like so?

![image](https://user-images.githubusercontent.com/6561887/48447564-1a098980-e751-11e8-9932-d090d3813e3a.png)

**Comment by razikallayi** [comment] 2018-11-14 05:29
Add this to your settings

"window.titleBarStyle" :"custom"

**Comment by jimbo1qaz** [comment] 2018-11-15 01:09
I wasn't affected by this bug, but tried out custom title bar just as an experiment. Turns out you render the menu using fuzzy grayscale antialiasing (made worse by gray-on-gray text), instead of respecting the OS choice to enable subpixel antialiasing. I will not be enabling the custom title bar feature.

**Comment by sbatten** [comment] 2018-11-15 17:57
@jimbo1qaz Are you saying that the custom menu is blurrier and harder to read than the rest of the VS Code UI? Would you be able to provide a screenshot?

**Comment by LinuxJon92** [comment] 2018-11-15 18:13
So what's the fix?

**Comment by sbatten** [comment] 2018-11-15 22:21
@LinuxJon92 Please see https://code.visualstudio.com/docs/setup/linux#_low-contrast-menu-bar for current fix

**Comment by lallenfrancisl** [comment] 2018-11-16 14:37
This happens on solus 3.999 too.

**Comment by jflambert** [comment] 2018-11-16 15:03
@sbatten the theme is "Communitheme". I'm not sure how I can take a screenshot like this since my menu only appears in "custom" mode.

**Comment by e3b0c442** [comment] 2018-11-17 00:57
Just making sure -- this issue is closed, but this workaround is definitely less than ideal. Is a real fix being pursued? If so can we either reopen this issue or be directed to the issue tracking this bug?

Thank you for all your work.

**Comment by GloverDonovan** [comment] 2018-11-18 05:45
Hi @e3b0c442,

The issue is tracked upstream here: electron/electron#15194

**Comment by aral** [comment] 2018-11-23 13:46
In case it helps, the menu bar displays perfectly with Adwaita-dark on Pop!_OS 18.10 running GNOME Shell 3.30.1 under Wayland.

![screenshot from 2018-11-23 13-45-34](https://user-images.githubusercontent.com/41798/48946597-27c7c780-ef26-11e8-8866-39d1d0675208.jpeg)

**Comment by mdsharpe** [comment] 2018-12-02 08:50
I've been struggling with menus not highlighting on select/mouseover, and can confirm that switching to `custom` menu bar has fixed that for me.
Looks great with yaru-dark theme, Ubuntu 18.10.

**Comment by timmy1420** [comment] 2018-12-10 13:44
The custom titleBarStyle has a bug most of the times very buggy when opening menus in code editor and sidebar. When I have to open a menu with my right mouse click, I have to hold the right click mouse button for the menu not to dissapear. How can this issue be fixed?
