### ISSUE TITLE
Unable to select range of text in editor

### ISSUE THREAD

**Issue by elmelundsvej** [microsoft/vscode#85163] opened 2019-11-20 01:13 UTC
Issue Type: <b>Bug</b>

I click and keep left key of mouse down anywhere at current row and drag forward and backward along to select substring in editor.
Issue: The editor is not rendering at all.

![screencast](https://user-images.githubusercontent.com/57971294/69639785-203a8180-1098-11ea-9993-57115eaf8413.gif)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.65GB (2.19GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.7.1
python|ms-|2019.11.49689
cpptools|ms-|0.26.2-insiders
cmake|twx|0.0.17

</details>

**Comment by egamma** [comment] 2019-11-20 11:10
/needsMoreInfo

Cannot reproduce the issue given the steps provided in the description. Please provide a screen recording that illustrates the problem.

**Comment by elmelundsvej** [comment] 2019-11-26 08:57
> /needsMoreInfo
> 
> Cannot reproduce the issue given the steps provided in the description. Please provide a screen recording that illustrates the problem.

It turned out to be a bug in cause of IBUS Pinyin input method. The issue can be reproduced if user switches to IBUS Pinyin (Simplified Chinese) and follow steps above.

**Comment by elmelundsvej** [comment] 2019-12-28 02:38
Is there a coming fix on it? What should I do to work around it if not?

**Comment by rebornix** [comment] 2020-11-05 22:08
/duplicate of https://github.com/microsoft/vscode/issues/70483

**Closed** 2020-11-05 22:08 UTC
Labels: *duplicate, editor-input-IME, linux, upstream
