### ISSUE TITLE
Grid css properties are unknown

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28931] opened 2017-06-17 13:02 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (73015a5e052e6de8ecd60eed2670bea81fad8cac, 2017-06-16T05:13:31.107Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|4.1.2
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.0
php-intellisense|fel|1.4.1
auto-close-tag|for|0.4.2
gc-excelviewer|Gra|1.1.15
GitHubIssues|Hoo|0.1.2
composer|ika|0.5.0
smarty|imp|0.2.0
json-to-ts|Mar|1.4.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.11.4
php-docblocker|nei|1.2.0
vscode-versionlens|pfl|0.19.0
vscode-statusbar-json-path|ric|1.0.7
vscode-icons|rob|7.9.0
sharecode|Rol|0.4.1
code-spell-checker|str|1.2.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

such as
![image](https://user-images.githubusercontent.com/11234139/27253098-06a8a650-536e-11e7-8c9a-7e0926440aaa.png)

**Comment by aeschli** [comment] 2017-06-19 13:15
duplicate of #27590

**Closed by aeschli** 2017-06-19 13:15 UTC
Labels: css-less-sass, insiders
