### ISSUE TITLE
TypeScript settings do not disable TypeScript error messages in tooltips.

### ISSUE THREAD

**Issue by politician** [Microsoft/vscode#54692] opened 2018-07-19 22:57 UTC
**If you are @mjbvz, please consider reading this bug report before closing the ticket with an irrelevant answer.  The steps to reproduce take 60 seconds to complete.**

 

We do not use TypeScript in several of our projects, so we have attempted to disable TypeScript validation in our JavaScript files.  However, VSCode displays TypeScript-related messages despite the settings instructing it not to do so.

Apparently this is a regression in the latest build because there was another long bug closed by @sandy081 about a similar issue back in March 2018 where the team appeared to have communicated that *the ability to disable TypeScript* was a feature that VScode supported.

- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Launch with `code --disable-extensions`
2. Open User Settings and configure it as per below.
2. Create a new file
3. Type `import test from "path"`
4. Change the Language Mode to "JavaScript"
5. Hover over the word `test` and observe the message `[ts] 'test' is declared but its value is never read' appears inside the tooltip.
6. The expected behavior is that VSCode does not attempt to communicate TypeScript-related error messages when TypeScript validation is disabled.

### User Settings for Step 2

**Important Clarification** Default JavaScript settings should not be modified.

```
    # Surely one of these will turn off all [ts] messages in tooltips!
    "typescript.validate.enable": false,
    "typescript.autoImportSuggestions.enabled": false,
    "typescript.check.npmIsInstalled": false,
    "typescript.format.enable": false,
    "typescript.format.insertSpaceAfterCommaDelimiter": false,
    "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": false,
    "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "typescript.format.insertSpaceAfterSemicolonInForStatements": false,
    "typescript.format.insertSpaceBeforeAndAfterBinaryOperators": false,
    "typescript.quickSuggestionsForPaths": false,
    "typescript.reportStyleChecksAsWarnings": false,
    "typescript.showUnused": false,
    "typescript.suggestionActions.enabled": false,
    "typescript.tsc.autoDetect": "off",
    "typescript.updateImportsOnFileMove.enabled": "never",
    "tslint.enable": false
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by politician** [comment] 2018-07-19 23:00
Not a duplicate of #54691 because that was closed without the reviewer answering the ticket correctly.

**Comment by mjbvz** [comment] 2018-07-19 23:06
Duplicate of #54691 

Please post on original issue if you disagree with my response to it

**Closed by mjbvz** 2018-07-19 23:06 UTC
Labels: typescript
