### ISSUE TITLE
Since last update cant debbug my angular application

### ISSUE THREAD

**Issue by lucasmuscolo** [microsoft/vscode#233118] opened 2024-11-05 18:29 UTC
Type: <b>Bug</b>

VS Code Debugging Issue Report - Angular Application Fails to Launch in Chrome
Description:

An Angular application consistently fails to launch in Chrome when debugging through VS Code. The application compiles without errors (ng serve shows no errors), but the browser window opened by the debugger remains blank.  No errors are displayed in the browser console or the VS Code Debug Console.  The issue only occurs in Chrome; other browsers (e.g., Brave, Edge) initially worked but eventually exhibited the same behavior. Cloning the repository temporarily resolves the issue, but it reoccurs after some time.

Steps to Reproduce:

Open the Angular project in VS Code.

Start the development server: ng serve

Initiate debugging by clicking the debug "play" button in VS Code, targeting http://localhost:4200/u/home.

The Chrome window opens with the specified URL, but the page remains blank.

Closing the Chrome window and restarting the debugger does not resolve the issue.

Cloning the repository and repeating steps 1-3 temporarily resolves the issue, but the problem reoccurs after some time.

Expected Behavior:

The Angular application should load and run correctly in the Chrome window opened by the debugger.

Actual Behavior:

The Chrome window remains blank, and the application does not load.

Attempted Solutions:

Clearing Chrome's cache, cookies, and browsing data.

Disabling all Chrome extensions.

Resetting Chrome settings to default.

Trying different Chrome versions (stable, beta, canary).

Creating a new Chrome user profile.

Using the --allow-insecure-localhost flag.

Adding "restart": true to launch.json.

Disabling the VS Code Remote - Tunnels extension.

Disabling all other VS Code extensions.

Clearing VS Code's extension cache.

Reinstalling VS Code.

Using a different debugger (Debugger for JavaScript).

Trying different ports for ng serve.

Disabling antivirus and firewall.

Cleaning npm cache (npm cache clean --force).

Deleting the .vscode folder.

Checking .gitignore for conflicts.

Comparing the project folder with a fresh clone of the repository.

Running ng serve --poll=2000.

Creating a new Windows user profile (temporarily resolves the issue).

Updating Node.js and Angular CLI to various versions.

Downgrading Node.js and Angular CLI to previous versions.

Environment:

VS Code Version:  [VS Code version 1.95.1]

Operating System: Windows 11, Version 10.0.22631, Build 22631

Angular Version: 10.2.4

Node.js Version: 16.20.2

npm Version:  [npm version 8.19.4]

Chrome Version: Versión 130.0.6723.92 (Build oficial) (64 bits)

Additional Information:

The issue only occurs when debugging through VS Code.  Running ng serve and accessing the application directly in the browser sometimes works, but the issue eventually reoccurs.

Cloning the repository provides a temporary fix, suggesting a problem with local configuration or caching.

Double-clicking is required to close the Chrome window or tab when the issue occurs.

Errors related to "xterm disposal" and "Remote Tunnel Service" have been observed in the VS Code Output panel.

Several warnings, including circular dependencies and unused TypeScript files, are present during compilation, but these do not seem to be the direct cause of the debugging issue.

Suspected Cause:

Unknown.  Possibly a conflict between VS Code, Chrome, and the operating system, or a persistent caching issue that is not resolved by clearing the cache.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.76GB (4.01GB free)|
|Process Argv|C:\\workspace\\iurix catamarca\\iurix-cloud-ui --crash-reporter-id a7a2fb8f-e324-4510-aa51-a54e804e5404|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-11-05 18:32
/duplicate of https://github.com/microsoft/vscode/issues/232651 which is fixed in upcoming 1.95.2

**Closed** 2024-11-05 18:33 UTC
Labels: *duplicate

**Comment by lucasmuscolo** [comment] 2024-11-05 20:25
I dont know how to find the similar issue. could you share it if you are
sure that is similar? cos my teammates could fix it just by closing and
opening VS, i can´t

**Comment by gjsjohnmurray** [comment] 2024-11-05 21:44
> I dont know how to find the similar issue

Please see https://github.com/microsoft/vscode/issues/233118#issuecomment-2457893637 above.
