### ISSUE TITLE
Fonts for Languages and panes

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#71909] opened 2019-04-08 03:14 UTC
How can I set only specific languages to have a specific font and the rest of the panes in VSCode (terminal etc) have another font within `settings.json` ?

**Comment by svipas** [comment] 2019-04-08 07:49
Currently it's impossible, you can use extension which overrides css or do it by yourself.

Duplicate of https://github.com/Microsoft/vscode/issues/26128 (I suggest to add 👍 to this issue)

**Comment by SheepDomination** [comment] 2019-04-08 13:24
I know extensions which override CSS, what do you mean; *do it by yourself* ?

**Comment by svipas** [comment] 2019-04-08 17:48
@SheepDomination you can override css by yourself without extension if you want

**Comment by SheepDomination** [comment] 2019-04-10 13:24
@svipas How ?

**Comment by svipas** [comment] 2019-04-11 07:29
You can find all info in this issue: https://github.com/Microsoft/vscode/issues/26128

**Comment by Tyriar** [comment] 2019-04-12 03:12
You can set the terminal and debug console fonts currently.

/duplicate #26128

**Closed by Tyriar** 2019-04-12 03:12 UTC
Labels: integrated-terminal
