### ISSUE TITLE
Set up Git Bash as default profile though Powershell is executed

### ISSUE THREAD

**Issue by Muppet168** [microsoft/vscode#132729] opened 2021-09-09 07:36 UTC
Issue Type: <b>Bug</b>

After selecting Git Bash as default profile, Powershell is executed as integrated terminal. This problem is already related to a bug in earlier versions of VSCode.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.6
vscode-language-pack-de|MS-|1.60.3
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vscode-qt-for-python|sea|1.1.4
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by albertosantini** [comment] 2021-09-09 07:40
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery release.

**Closed** 2021-09-09 17:21 UTC
