### ISSUE TITLE
 SplitLinesCollection: attempt to access a 'newer' model

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43737] opened 2018-02-15 09:02 UTC
Issue Id: <b>c387947c-7708-0efb-edd7-30e99187813d</b><br /><br />*Versions* <br />- 1.20.0<br />-  f9398645d1d624538708eeebf96e6fdeb546f5d7<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />-  7636a7d6f7d2749833f783e94fd3d48d6a1791cb<br />*Stack* <br />Error: SplitLinesCollection: attempt to access a 'newer' model<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L180:9](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/splitLinesCollection.ts#L180:9)<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L671:7 (_ensureValidState)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/splitLinesCollection.ts#L671:7 (_ensureValidState))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L125:21 (convertModelPositionToViewPosition)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/splitLinesCollection.ts#L125:21 (convertModelPositionToViewPosition))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L232:58 (convertModelPositionToViewPosition)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/viewModel/viewModelImpl.ts#L232:58 (convertModelPositionToViewPosition))<br />[/vs/base/common/event.ts#L142:15 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/event.ts#L142:15 (call))<br />[/vs/editor/common/model/textModel.ts#L1598:27 (fire)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L1598:27 (fire))<br />[/vs/editor/common/model/textModel.ts#L1608:8 (forceTokenization)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L1608:8 (forceTokenization))<br />[/vs/editor/contrib/suggest/suggestModel.ts#L48:8 (tokenizeIfCheap)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/contrib/suggest/suggestModel.ts#L48:8 (tokenizeIfCheap))<br />[/vs/editor/contrib/suggest/suggestModel.ts#L439:20 (shouldAutoTrigger)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/contrib/suggest/suggestModel.ts#L439:20 (shouldAutoTrigger))<br />[/vs/editor/contrib/suggest/suggestModel.ts#L389:8 (_onNewContext)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/contrib/suggest/suggestModel.ts#L389:8 (_onNewContext))<br />

**Comment by alexandrudima** [comment] 2018-02-26 12:04
Duplicate of #29033

**Closed by alexandrudima** 2018-02-26 12:04 UTC
Labels: error-telemetry
