### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by maddes** [Microsoft/vscode#49956] opened 2018-05-16 06:05 UTC
- VSCode Version: 1.22.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Update available popup shows up
2. Click Install Update
3. Click Update Now once it downloads
4. Update looking good until suddenly

![image](https://user-images.githubusercontent.com/1455722/40099201-6cd55160-58b5-11e8-98aa-fa49dc3314fd.png)

Does this issue occur when all extensions are disabled?: code is not a recognizable command any longer.

```
May 16 02:52:59.299 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
May 16 02:52:59.305 INFO Checking for running Code.exe processes... (attempt 1)
May 16 02:52:59.308 INFO Code.exe is not running
May 16 02:52:59.309 INFO Checking for possible conflicting running processes... (attempt 1)
May 16 02:52:59.316 INFO Inno Updater v0.4.3
May 16 02:52:59.317 INFO Starting update, silent = false
May 16 02:52:59.367 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
May 16 02:52:59.369 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
May 16 02:52:59.384 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
May 16 02:52:59.385 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
May 16 02:52:59.386 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
May 16 02:52:59.388 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
May 16 02:52:59.389 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
May 16 02:52:59.390 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
May 16 02:52:59.391 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
May 16 02:52:59.392 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
May 16 02:52:59.393 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
May 16 02:52:59.395 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
May 16 02:52:59.396 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
May 16 02:52:59.397 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
May 16 02:52:59.399 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
May 16 02:52:59.400 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
May 16 02:52:59.401 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
May 16 02:52:59.403 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
May 16 02:52:59.404 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
May 16 02:52:59.406 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
May 16 02:52:59.407 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
May 16 02:52:59.408 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
May 16 02:52:59.409 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
May 16 02:52:59.410 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
May 16 02:52:59.411 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
May 16 02:52:59.413 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
May 16 02:52:59.414 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
May 16 02:52:59.415 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
May 16 02:52:59.417 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
May 16 02:52:59.418 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
May 16 02:52:59.420 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
May 16 02:52:59.421 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
May 16 02:52:59.422 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
May 16 02:52:59.423 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
May 16 02:52:59.424 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
May 16 02:52:59.426 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
May 16 02:52:59.427 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
May 16 02:52:59.428 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
May 16 02:52:59.430 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
May 16 02:52:59.431 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
May 16 02:52:59.432 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
May 16 02:52:59.434 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
May 16 02:52:59.435 INFO Delete: "bin" (attempt 1)
May 16 02:52:59.439 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
May 16 02:52:59.440 INFO Delete: "Code.exe" (attempt 1)
May 16 02:52:59.492 INFO Delete: "Code.exe" (attempt 2)
May 16 02:52:59.694 INFO Delete: "Code.exe" (attempt 3)
May 16 02:53:00.148 INFO Delete: "Code.exe" (attempt 4)
May 16 02:53:00.953 INFO Delete: "Code.exe" (attempt 5)
May 16 02:53:02.210 INFO Delete: "Code.exe" (attempt 6)
May 16 02:53:04.020 INFO Delete: "Code.exe" (attempt 7)
May 16 02:53:06.482 INFO Delete: "Code.exe" (attempt 8)
May 16 02:53:09.699 INFO Delete: "Code.exe" (attempt 9)
May 16 02:53:13.769 INFO Delete: "Code.exe" (attempt 10)
May 16 02:53:18.794 INFO Delete: "Code.exe" (attempt 11)
May 16 02:53:18.796 ERRO Access is denied. (os error 5)
```

**Comment by maddes** [comment] 2018-05-16 06:09
Code reopened by itself after clicking `OK`.

**Comment by rprouse** [comment] 2018-05-18 12:59
Same error and log file for me updating to 1.23.1 on Windows 10. Looks like a duplicate of at least #49620 and possibly others. I checked process explorer and `Code.exe` is not running. I also downloaded and installed the update, but unlike @maddes it installed fine, `Code.exe` was no longer locked.

**Closed** 2018-05-29 07:12 UTC
Labels: *duplicate
