### ISSUE TITLE
Support to drag and drop selected text

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#1046] opened 2015-12-06 02:21 UTC
In Microsoft Visual Studio Professional you can click+hold on selected text and then drag that text to a new location.  Like a cut/paste operation by dragging/dropping.  Requesting that VS Code support this feature.  Thanks!

**Comment by MrAndMrsK** [comment] 2015-12-20 17:23
:+1:  Except I think you don't have to hold ctrl just to cut/paste - ctrl once dragging makes it copy instead of cut, right?  But regular drag gets rid of the original, moves it to the new location.

**Comment by Nimzozo** [comment] 2016-03-04 21:50
:+1: +1
Agree with @MrAndMrsK .

**Comment by senjacob** [comment] 2016-04-30 13:27
https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9492333-drag-and-drop-of-selected-text

**Comment by diryboy** [comment] 2016-04-30 13:30
+1, commenting to get notification. Really miss that.

**Comment by Spown** [comment] 2016-05-11 08:14
@senjacob https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7763958-drag-n-drop-selections

**Comment by BeginnerForLife** [comment] 2016-05-26 00:50
Agreed.

**Comment by sheltonjb** [comment] 2016-06-01 23:13
NEEEEED! I use this constantly! feels alien without it and so long winded..

**Comment by Bungalow12** [comment] 2016-06-01 23:50
+1 this is a must have

**Comment by wmjordan** [comment] 2016-06-21 06:50
What the h*ck is going on with Code?
It took more than one year for them to implement this feature!?

**Comment by Spown** [comment] 2016-06-21 06:58
@wmjordan how much did you pay for VSCode?

**Comment by NValerij** [comment] 2016-06-25 15:11
https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7763958-drag-n-drop-selections - more popular request on this topic.

**Comment by Spown** [comment] 2016-06-25 16:44
@NValerij [^^^](#issuecomment-218391868)

**Comment by NValerij** [comment] 2016-06-25 18:11
@Spown sorry for duplicate. Deleted.

**Comment by apmckinlay** [comment] 2016-08-01 17:27
+1

**Comment by tsaltd** [comment] 2016-08-11 02:23
no comments re: being able to drop a library item from the directory tree into a view to set the path for css / js etc libraries ---   a la Visual Studio

**Comment by reactivize** [comment] 2016-08-18 04:12
What's the technical holdback on drag and drop of selected text?

**Comment by Spown** [comment] 2016-08-18 06:34
@reactivize I don't think its technical. I think nobody on the dev team thinks its worth spending time onto because nobody of them uses this coding style. VSCode was meant to be used without taking your hands away from the keyboard, hence no button palettes, a textual command palette, no miniwindows, etc.

They already kinda separated [Monaco editor](/Microsoft/monaco-editor) from the core so maybe it would be possible in the future to plug in a different editor, like [Ace](https://ace.c9.io) that already supports it. But a standartized interface between core and wrapped editor is needed for that and this can be even more difficult to implement.

**Comment by alexandrudima** [comment] 2016-08-18 06:40
@reactivize There is no technical holdback, each milestone we pick features from the backlog to implement. We use thumbs up counts and comment counts as metrics to determine the community desire for a certain feature and then we use our best judgement (effort vs rewards, short-term vs long-term benefits) to pick what to work on.

**Comment by miquelfire** [comment] 2016-08-18 12:30
Starting up some development, decided to use this tool because of the debugger, and this was really annoying to find missing.

**Comment by giddyupgrp** [comment] 2016-08-24 05:37
Adding both my thumbs up to the request for this feature. Its driving me crazy that its not there.

**Comment by SynCap** [comment] 2016-08-27 17:32
Must have!!!
Especially dragging text between docs, editors, drag text to another apps, such as browser, and vice versa.

**Comment by LBLuffy** [comment] 2016-08-29 16:36
A feature that is in visual studio obviously should be in visual studio as well.

**Comment by zaus** [comment] 2016-09-02 15:34
It's just weird that this is the only app I've ever seen that lets you type that _doesn't_ let you drag text as well.  Even web browsers let you drag text.

**Comment by Daivuk** [comment] 2016-09-10 13:12
This is basic text editor feature, really need this! I keep trying to do it then it just reselects :(

**Comment by ipiz** [comment] 2016-09-12 06:08
I really love the drag and drop feature and ctrl+ drag and drop feature for duplicating text selection, this way you don't need to overwrite your clipboard.

**Comment by kevinmoran** [comment] 2016-09-23 00:19
This would be a really nice little addition, I use this feature all the time in other editors. Hope I can help bump this up the priority list a bit.

**Comment by wmjordan** [comment] 2016-09-23 00:32
I won't use VS Code unless this feature is implemented.

**Comment by ocaraveo** [comment] 2016-09-29 23:14
Agreed-- the current VSCode editor needs these basic features (e.g. drang-n-drop text, column select text, multi-line edit), it feels crude/unfinished otherwise.

**Comment by Devcon4** [comment] 2016-09-29 23:24
You can already column select text shift+ alt+click, and you do have multi cursor ctrl+alt+arrows(although that will rotate ur display unless u change the shortcut :p). Drag to move text would be nice though, but with those two I find that I want to use drag and drop less. Vscode was designed to be ran from a keyboard.

**Comment by ocaraveo** [comment] 2016-09-30 00:57
@Devcon4 

> Vscode was designed to be ran from a keyboard.

vscode should be designed to work efficiently with both keyboard & mouse :)

thnx for the key combos!

**Comment by Arnique** [comment] 2016-10-05 00:17
Seriously, how long would it take to code this feature? And people wonder why MS keeps losing.

**Comment by syldub69** [comment] 2016-10-21 11:43
I see this issue/request has been raised since 11 months now... and still not fixed in Visual Studio Code 1.6.1. This is a basic editor functionality that every coder uses... I don't understand why it has not been implemented since the beginning (we see that a lot of more complex useful functionalities have been implemented).
I'm waiting desperately since months, testing this at each new release... Could we just have a status from Microsoft dev team? Have they taken this request into account? Do they have a technical difficulty to implement this?

**Comment by rhires** [comment] 2016-10-21 13:11
In defense of Open Source Software and Microsoft, I write this. The code is open; if you have a particular need and the developer/maintainer doesn't fix it, you certainly can. There is no reason to be so demanding and rude about it. This software is free, both in money you have to pay to use it/get it, and in that it's available for you to review, update, and change. If it's good, they'll take your changes. The number of requests for features, updates, etc for this awesome piece of software is overwhelming, and they can't get to everything right away. Part of the philosophy of Open Source is 'scratch your own itch'. There is nothing that prevents you from getting together with other developers to create changes that you want/need and submit them back to the developer. We are a community. Demanding someone else do something for you is not the way to go. Offering help and solutions for troubles you are having (even just really good bug reports) is how to move the software forward.

**Comment by dvader** [comment] 2016-10-24 20:21
This is a basic feature of every GUI based source code text editor. Sublime, Notepad++, Visual Studio Pro, etc support that feature. I understand the desire to prioritize keyboard input but I assume a lot of people are like me and do a mix of keyboard and mouse input when editing files.
Somebody also mentioned that this method prevents overwriting the clipboard which is a good point.

**Comment by achshar** [comment] 2016-10-24 20:44
@rhires well in that case why have this open bug tracker at all. Why not let everyone and their grandma make a pull request to fix every little thing they come across. No one here is "demanding" anything because putting up a demand requires authority for it to have any success.

Also your argument can be applied to literally every feature request of any open source project ever. Devs take this kind of feedback to assess user trends and focus their effort appropriately. Every "demand" is just another data point that will help them make better decisions.

**Comment by wmjordan** [comment] 2016-10-26 00:53
OMG, it is terrible that @alexandrudima removed the assignment to this issue.

**Comment by alexandrudima** [comment] 2016-10-26 12:59
Don't take the Assignee as a measure for when a feature will be done. The field to look at is the Milestone. You can bring feature requests higher on our list of To-Dos by upvoting them. We pick issues with many upvotes to work on each month.

I've unassigned myself to be able to manage my issues better. I am slowly going though issues assigned to me and removing my assignment until the feature request gets put on the plan.

**Comment by wmjordan** [comment] 2016-11-02 10:26
I now believe that there is no insurmountable technical barrier preventing the implementation to solve this issue.
_Atom_, another editor sharing the same component as _VS Code_, has the same issue and this package has solved it:
https://atom.io/packages/simple-drag-drop-text

**Comment by debuggings** [comment] 2016-11-03 03:12
Oh, it's been more than a year, but I'm still waiting...

> I now believe that there is no insurmountable technical barrier preventing the implementation to solve this issue.
Atom, another editor sharing the same component as VS Code, has the same issue and this package has solved it:
https://atom.io/packages/simple-drag-drop-text

Or is there anyone who can make an extension like that?

**Comment by klaygor** [comment] 2016-11-08 10:50
Sublime suffers from this on Linux even though it works fine on Windows version; yet applications such as VS Code can't even do this on Windows.

Drag'n'drop and printers; the banes of my computing life.

**Comment by PhiLhoSoft** [comment] 2016-11-16 13:40
@rhires I agree with you, and sometime I said that too (in other contexts / projects), but don't forget that users of VSCode have various backgrounds, from HTML coders to Python programmers, etc. so might just lack the competence to do such changes. That's not, eg. just a JS library used by JS devs complaining about some lack of feature...
That said, indeed, the tone used by some people is a bit rude...

@dvader I agree, I guess I used D'n'D primarily to avoid clobbering the clipboard, and I am too used to it to code without it, that's why I test VSCode from time to time, then uninstall it... 😄 
Today I have a clipboard manager, but well, I don't want it cluttered with snippets too...
Admittedly, often D'n'D might be slower than doing the manip with keyboard (aiming at target can be delicate...) but I am a visual guy: I use the keyboard a lot, of course, but the mouse too. Taking a few lines and dragging them at their new place, for example, is visually more satisfying... 😉 

@wmjordan Atom is based on another editor component, which had D'n'D support from the start, I guess the package just exposed it. It would be harder with this one, I guess. Not impossible, I hope.

**Comment by joeyespo** [comment] 2016-11-17 03:52
I'm definitely 👍 for this feature, but wanted to offer some comfort to those waiting.

There was a time when [Sublime Text didn't have this feature either](https://forum.sublimetext.com/t/is-it-possible-to-select-text-and-drag-it-to-a-new-location/3740). It seems "small" features like this are the growing pains of young editors gaining popularity. (It's also amusing how similar the conversations are.) It's likely this *will* get resolved.

In the meantime, keep on +1'ing this issue to show a signal of interest and try to appreciate the good (there's already a lot!) while VS Code matures.

**Comment by PhoenixBlue** [comment] 2016-11-24 06:21
The feature is a must!!
+1

**Comment by sir-marc** [comment] 2016-12-05 08:05
Inside a file you can move code-snippets using alt+arrow keys

**Comment by erocheleau** [comment] 2016-12-05 16:02
@sir-marc Thanks for the input but that is not at all what people here are looking for.

**Comment by PhoenixBlue** [comment] 2016-12-06 07:52
@sir-marc 
Moving the code Up/Down is not the same as dragging $ dropping a selection.
It's much slower!!!

@erocheleau +1

**Comment by PhoenixBlue** [comment] 2016-12-06 07:55
@klaygor +1
I just realised there is no printer either!! Come on guys! please! It cannot be more basic than that?
I just hope we won't be told to copy and paste it somewhere else to print it out...

**Comment by jstaelens** [comment] 2016-12-09 21:06
+1 for drag & drop / ctrl + drag & drop

**Comment by 2Ren** [comment] 2016-12-11 09:46
太需要这个功能啦，加油加油，期待。。。
thanks for  vs code's help

**Comment by jgzheng** [comment] 2016-12-15 18:55
Cannot believe it ... this is the most basic editing feature but missing from VS Code.

**Comment by PhiLhoSoft** [comment] 2016-12-16 09:19
Please people. Refrain from commenting here if you don't bring useful information. Now GitHub allows you to "vote" on an issue by adding a 👍 on the original report. This avoids to send notifications of no real value to everybody.

**Comment by agatlin** [comment] 2017-01-01 08:57
Drag and drop is desperately needed. There are a whole lot of reasons to use VSCode even if you are not a keyboard-only guy. Please add this feature! Please!

**Comment by imspikey** [comment] 2017-01-05 17:30
Pleas Add this feature this is an essential feature for any code editor!

**Comment by pavel-agarkov** [comment] 2017-01-11 10:43
I would love to have this feature + D&D from files tree to insert file path to the editor (maybe with ctrl).
thank you.

**Comment by lanbomo** [comment] 2017-01-15 07:05
This feature is must needed absolutely, please add this feature for vscode. Thanks!

**Comment by Jerry-Shaw** [comment] 2017-01-19 03:59
Yep, we need the feature indeed.

**Comment by mariommoreno** [comment] 2017-01-23 17:23
+1
No one knows an extension?

**Comment by Grix** [comment] 2017-01-27 14:18
Another +1

**Comment by iredwards** [comment] 2017-02-08 17:44
As a user who sometimes has difficulty using the keyboard with one hand, drag-n-drop is a boon at times.  Strange but true, this is the biggest gripe I have with Code.  Keyboard-centric UI is fail for some people.  The challenge isn't learning key bindings... it's pressing the cursor keys that is hard.

**Comment by wmjordan** [comment] 2017-02-09 02:37
I totally agree with you.

Nowadays most notebooks have smaller-than-ordinary arrow keys which sometimes are even squeezed to a small corner.

It is really inconvenient and inefficient.

________________________________
发件人: Richard Edwards <notifications@github.com>
发送时间: 2017年2月9日 1:45:02
收件人: Microsoft/vscode
抄送: wmjordan; Mention
主题: Re: [Microsoft/vscode] Support to drag and drop selected text (#1046)


As a user who sometimes has difficulty using the keyboard with one hand, drag-n-drop is a boon at times. Strange but true, this is the biggest gripe I have with Code. Keyboard-centric UI is fail for some people. The challenge isn't learning key bindings... it's pressing the cursor keys that is hard.

―

**Comment by rebornix** [comment] 2017-02-14 01:02
I don't know how but I heard your voice on Sunday and made the first prototype already. Let's see if we can put it Feb release. Drag and drop breaks part of our existing experience so I'd like to do careful testing against it but there is no blocker. Cheers ❤️

**Comment by Jasonlhy** [comment] 2017-02-14 01:12
Is it also able to add drag and drop API into the vscode? This could be useful for some usages, for example, I can create a extension help to editing the markdown, when I want to insert a image, i can simply drag the image from the folder into the editor.

**Comment by Spown** [comment] 2017-02-14 01:16
@Jasonlhy lets not overextend. first things first. this issue is called "...drag and drop selected **text**"

**Comment by iredwards** [comment] 2017-02-14 01:31
Just drag-n-drop of selected text alone would solve the vast majority of my editing problems, because it fills so much of my every day. Thanks @rebornix, life is about to get sweeter :-)

**Comment by aa-telali** [comment] 2017-02-16 12:56
I can't believe this is even a request. It's a normal feature in all but the most arcane of text editors. Trying to move from Visual Studio to Visual Studio Code shouldn't be this difficult. :(

That said, great job on include Alt+Up/Down to move lines 👍  - I loved it when you introduced this to VS2013 (?) and I'm really happy it's in VSCode :)

**Comment by craiglonsbury2** [comment] 2017-02-17 17:20
+1 for this as well. I find myself dragging code and nothing happens....

**Comment by rotan-hanrahan** [comment] 2017-02-20 20:44
+1 and kudos to @rebornix for even considering taking this on. D&D is not trivial. The edge cases alone are a headache: drag to beginning/end of file, drop into the selected text, drop at start/end of selected text, drop into another instance of the same file, drag off the editor window, escaping the D&D mid-drag, drag to top/bottom of editor window to cause scrolling, drag to edge of window on long line to drop at the end of line, copy instead of move if Ctrl is held, (or other key bindings, of course), "undo D&D" for all cases etc. It's no wonder that this feature is missing from new editors.

**Closed** 2017-02-21 15:04 UTC
Labels: editor, editor-core, feature-request

**Comment by rebornix** [comment] 2017-02-21 19:49
@rotan-hanrahan thank you very much, you helped me create a thorough test plan for this feature :)

**Comment by apazureck** [comment] 2017-02-24 21:38
Would it be a problem to have a drop-handler in the extension api?

I am thinking of a feature of dropping images on markdown code and - like here on github - getting the image uploaded (in this case added to a project).

**Comment by Kureev** [comment] 2017-02-27 13:32
I second that ^. Would be great to see API hooks for workspace drop events. 

Usage example: If you render a list of components / plugins / whatever in the second tab (as a read-only HTML), you can drag and drop them to the workspace then. I'll be happy to collaborate on this feature if needed.

**Comment by iredwards** [comment] 2017-03-02 00:02
Thank you x 10,000 to @rebornix and everyone who contributed to this. I'm enjoying this now in 1.10.0, and life is more pleasant now! This feature makes a big difference for me and I'm truly delighted. I worked for 12 years at MS long ago, including several in the Visual Studio and other Dev Div product groups. I've never been so happy to see a few feature ship, seriously. Thanks again!

**Comment by wmjordan** [comment] 2017-03-02 02:37
Thank you @rebornix very much.
I am using VS Code now.

**Comment by langdonx** [comment] 2017-03-03 16:23
Great start, thanks for adding this!  Some notes for polish on the final product (not sure if there's a better place to put these):

 - The mouse cursor should change to the default arrow when you hover over a selection that can be dragged and while dragging it.
 - A user should not be able to drag a selection into itself (technically you can't, but the mouse cursor and target cursor both lead you to believe you can).
 - A user should be able to hold CTRL (or whatever in other operating systems) to copy the selection instead of move it.

Visual Studio and most editors with drag/drop support do these things if you need an example.

Thanks again!!

**Comment by devuxer** [comment] 2017-03-03 16:31
I second @langdonx suggestions, particularly the one about using CTRL+drag to copy.

**Comment by martinsuchan** [comment] 2017-03-03 16:44
@langdonx @alexandrudima For MVP it's a great start, but it needs some finer tuning, for instance
- dragging selected text **between left and right tab**
- dragging selected text **between VS Code and other app**, in both ways, just like it works in a browser.
- dragging in [column selection mode](https://github.com/Microsoft/vscode/issues/1515)
- pressing **Esc** when dragging should cancel the event altogether. Now after pressing Esc you can start typing, but the text is dropped once you release the mouse anyway.

**Comment by rotan-hanrahan** [comment] 2017-03-03 23:55
I mentioned previously some of the failing test cases that have been raised since the preview of the @rebornix D&D support was released. This D&D feature enhancement, limited as it is, is still a massive improvement over having no D&D support at all. I would like to point out that the "drag to top/bottom of window to cause scrolling" appears to work despite the (closed) test cases documentation #21012 stating that this functionality is not supported. Seems we got lucky with this one.

As people seem to be contributing to the shopping list of must-haves, let me add this proposal: drag selected text over the title tab of an open file in VSC (other than the current file in which the text is selected) so that the hovered-over tab becomes the active document, allowing the user to drag text between files. This would be a bit like the way that tabs in the Windows task bar can activate the corresponding window/application as a drop target when you hover over the tab while dragging. (And please note that this isn't a must-have, but it will be pleasant to see working some day.)

**Comment by dvader** [comment] 2017-03-08 14:23
Not knowing where to comment on the feature, I am adding it here.
Regarding the comment from @langdonx:
- The mouse cursor should change to the default arrow when you hover over a selection that can be dragged and while dragging it.

Looking at other programs, the cursors actually look like so:

1. Hover (as in the comment):  ![arrow over](https://cloud.githubusercontent.com/assets/2127127/23707487/2ff89c76-03d8-11e7-923a-fb7ba46ca1ee.png)
2. Move: ![move arrow](https://cloud.githubusercontent.com/assets/2127127/23707503/40bdbbfe-03d8-11e7-9915-c80832e55b89.png)
3. Copy (holding the Ctrl key): ![copy arrow](https://cloud.githubusercontent.com/assets/2127127/23707514/502dd6c8-03d8-11e7-864c-0de6970c52d6.png)

**Comment by Daivuk** [comment] 2017-03-08 14:55
We shouldn't be able to drag text from the margin select. I use this to
reselect, and it causes problem because it drags text now.
We should be able to copy the text when holding Ctrl. Personally, without
this that DD feature is useless. I use this all the time in VS.

**Comment by rebornix** [comment] 2017-03-08 22:10
@dvader the mouse pointer style update is coming in tomorrow's Insider

DND

![default](https://cloud.githubusercontent.com/assets/876920/23726355/da8fce86-0408-11e7-8b30-b34b0b7f9f1b.gif)

DND with Alt/Ctrl Key pressed

![copy](https://cloud.githubusercontent.com/assets/876920/23726368/e2a3dfea-0408-11e7-81d9-07a14c6a92fe.gif)

@Daivuk you should be able to copy instead of just cutting.

**Comment by Daivuk** [comment] 2017-03-08 22:11
Amazing! Thanks.

Only missing will be the margin select to not drag the text. But that's
already a huuuuge step forward.

**Comment by rv-rsouza** [comment] 2017-03-09 13:49
When is this coming to OSX?

**Comment by martinsuchan** [comment] 2017-03-09 14:33
@rebornix is there a plan to use the standard Windows drag cursors that @dvader shown above? The green Copy cursor looks a bit strange.

**Comment by wellenzhong** [comment] 2017-03-20 03:44
This is now supported as of Feb 2017 release (1.10.1) but it is disabled by default.

To enable it: Go to File > Preferences > Settings and add this line "editor.dragAndDrop": true

Source: https://code.visualstudio.com/updates/v1_10#_preview-drag-and-drop-selected-text

**Comment by langdonx** [comment] 2017-04-06 16:05
Happy to see the continual progress on this.  Just got the March release and noticed one minor (but annoying) issue:

 - In VS Code, the cursor (with copy indication) only changes on mouse move.
 - In VS 20xx, while dragging text you can press and release CTRL to affect the mouse cursor.

My typical workflow is, 1) select text, 2) drag text, 3) hold control, 4) drop text.  With this workflow, since my mouse is still, it's not clear that the text will be copied when I release the mouse.

Thanks for all the hard work!

CC: @rebornix (not sure who else to CC) =[

**Comment by rebornix** [comment] 2017-04-11 18:04
@langdonx it's a valid feature request, do you want to create an issue for me?

**Comment by langdonx** [comment] 2017-04-11 19:33
Cross reference https://github.com/Microsoft/vscode/issues/24547

**Comment by wewake4** [comment] 2017-04-20 04:57
Drag and drop is working fine in visual code but the same code is not updated in Monaco editor ?
[Monaco Editor](https://github.com/Microsoft/monaco-editor)
When it will be avialable ?

**Comment by DRSDavidSoft** [comment] 2017-05-15 21:56
Wow, It's amazing that this feature has been already implemented into VS Code!
Question: Could you feature the comment as a solution for future visitors?

https://github.com/Microsoft/vscode/issues/1046#issuecomment-287673818

**Comment by rebornix** [comment] 2017-05-26 16:50
@DRSDavidSoft do you mind tell me how to feature a comment as a solution?

**Comment by rebornix** [comment] 2017-05-26 16:51
@wewake4 we updated Monaco on Mar 3rd, you should be able to have this feature.
