### ISSUE TITLE
Installed Prettier - Code formatter but can't run in WSL2

### ISSUE THREAD

**Issue by viper7882** [microsoft/vscode#181644] opened 2023-05-05 15:59 UTC
Type: <b>Bug</b>

1. Launch VSCode in WSL2 of UBuntu instance using command `code .`.
2. Install `Prettier - Code formatter` under `Extensions`.
3. Goto Settings -> Settings, search for `formatter`.
4. Ensure `Editor: Default Formatter` entry for `User` tab, `Remote [WSL: Ubuntu-22.04]` tab and `Workspace` tab is set to `Prettier - Code formatter`.
5. Goto any solidity file, activate shortcut key for Format File, `Alt+Shift+F`.

**Observed**: Error message suggesting "No formatter installed for solidity files".

**Expected**: Prettier Formatter could run and no error message is observed.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Connection to 'wsl+Ubuntu-22.04' could not be established
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.50GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/viper7882/github --remote=wsl+Ubuntu-22.04 --crash-reporter-id acee4de4-ad18-4311-8177-f5125d3e2653|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+Ubuntu-22.04' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz (12 x 2496)|
|Memory (System)|7.64GB (6.47GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.4
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vscode-solidity-language|tin|0.0.7
prettier-vscode|esb|9.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30730054
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-05-06 01:37
Looks like a duplicate of #181620

**Comment by jrieken** [comment] 2023-05-09 05:58
@viper7882 please see #181620 and check if you see the same error message

**Comment by viper7882** [comment] 2023-05-09 07:05
Unfortunately, the error is different. However, both errors could be caused by the same issue. Please help me to understand the architect of VSCode first.  The extension will have to be rewritten to support both local and remote workspace? VSCode didn't make the API common for both? I didn't expect extension to be blamed if VSCode made the transition between local and remote workplace seemless for both.

**Comment by jrieken** [comment] 2023-05-09 17:13
How about sharing some concrete information about your extensions failure, like open Output > Prettier and check for eventual errors. From there we see how to continue.

**Comment by viper7882** [comment] 2023-05-10 08:48
The `Output` displayed:
```sh
["INFO" - 7:19:26 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 7:19:26 AM] Extension Version: 9.12.0.
```
Nothing else is printed.

Hold on a second, I thought the complaint is regarding VSCode does not register Prettier plugin is installed. Shouldn't that be removed first before we zoom into Prettier plugin can be ran successfully?

**Comment by jrieken** [comment] 2023-06-21 15:17
not actionable

**Closed by jrieken** 2023-06-21 15:17 UTC
