### ISSUE TITLE
Trying to collapse search file results is throwing an exception

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166499] opened 2022-11-16 19:35 UTC
```
ERR Cannot read properties of undefined (reading 'getNodeLocation'): TypeError: Cannot read properties of undefined (reading 'getNodeLocation')
    at j.u (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:51788)
    at vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:23967
    at f.invoke (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at h.fire (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:23607
    at f.invoke (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at h.fire (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at HTMLDivElement.T (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:8842)
```

![image](https://user-images.githubusercontent.com/2193314/202277021-2764a7e6-4c22-4c4f-8b0d-40ff65537b41.png)

**Comment by andreamah** [comment] 2022-11-16 22:37
This is in the list (non-tree) view for search, right?

**Comment by andreamah** [comment] 2022-12-02 17:47
duplicate of #166499

**Closed by andreamah** 2022-12-02 17:47 UTC
Labels: bug, search
