### ISSUE TITLE
Parameter hints coloring (Dart Language)

### ISSUE THREAD

**Issue by ashharhasan** [microsoft/vscode#94442] opened 2020-04-04 15:42 UTC
Currently there is only one font color in parameter hints pop-up, there should be two, like for "type name" it should be blue or any color which is used for class according to the theme. The pop-up in the below snapshot has only one color (white):

![Capture](https://user-images.githubusercontent.com/19208699/78454421-5aa0d480-76b1-11ea-8341-9bb4e45ce660.PNG)

At first I thought its just because of theme, but I tried many themes and no one offered me this. I am using dart language for flutter app, may be that's only happening in this language.

**Comment by KamasamaK** [comment] 2020-04-04 19:04
Duplicate of #55044

**Comment by gjsjohnmurray** [comment] 2020-04-05 07:03
/duplicate
Thanks @KamasamaK

**Closed** 2020-04-05 07:04 UTC
Labels: *duplicate
