### ISSUE TITLE
Mouse Wheel Scrolling Ignores Mouse Control Panel Settings

### ISSUE THREAD

**Issue by juliantrd** [microsoft/vscode#7640] opened 2016-06-14 06:24 UTC
- VSCode Version: 1.2
- OS Version: Windows 7

Steps to Reproduce:
1. Open any file in VSCode
2. Scroll with mouse wheel

The number of lines scrolled does not match the Mouse Control Panel settings.

**Comment by sandy081** [comment] 2016-06-14 08:47
@juliantrd Can you please let me know which setting option you are mentioning about. Thanks.

**Comment by juliantrd** [comment] 2016-06-16 00:14
In the Mouse Control Panel -> Wheel Tab, there are two settings for Vertical Scrolling.  
Roll the wheel one one notch to scroll:
"The following number of lines at a time", or 
"One screen at a time"

**Comment by alexandrudima** [comment] 2016-06-16 08:25
@juliantrd We do not read this information from the OS, it is most likely Chromium that interprets it. At our level, you could use a setting called `editor.mouseWheelScrollSensitivity` to control it.

**Comment by jcmielle** [comment] 2016-06-18 05:49
I can confirm that scrolling works correctly in Chrome on Windows so it should be possible to fix this in VSCode.

**Comment by brucejo75** [comment] 2017-03-05 05:56
Any progress on this?  I just downloaded VSCode and this is one of the first problems I ran into.

Why doesn't VSCode default to the system scroll setting from the OS like all other apps?  My old version of Outlook 2010 does it right, why can't VSCode?

I set the `editor.mouseWheelScrollSensitivity` to what I wanted.  Great for the editor window, but the other windows: Explorer, Problems, Console, etc. still operate at a sensitivity of 1 (seriously?)

**Comment by ColacX** [comment] 2017-06-30 13:43
guys I have the same issue. fix this please. wtf is this.

**Comment by joaobpedro** [comment] 2017-07-05 16:09
My vscode v 1.13.1 completely ignores the `editor.mouseWheelScrollSensitivity` setting

**Comment by johnwoolee** [comment] 2017-11-28 19:37
Had the same problem for a while. Try setting the `editor.mouseWheelScrollSensitivity` setting to a decimal setting. This just worked for me.

I thought I had tried this in the past, and it had not worked, but just did!

**Comment by n-alex-white** [comment] 2018-05-24 08:48
11 months later and this is still a problem. It seems odd that this is the only app I have running on windows 7 that doesn't obey the system settings for mousewheel set to 'page scrolling'

**Comment by barry-hall** [comment] 2018-07-02 14:14
I have found setting the following in user settings is as close as I can get to scrolling one line at a time; 

`"editor.mouseWheelScrollSensitivity": ".2"`

It will show an error "Incorrect type. Expected "number". But still seems to do the trick.

**Comment by cerebralin** [comment] 2018-10-12 17:01
Still a problem in 1.28.  Hope this get fixed soon.

**Comment by sjas** [comment] 2018-10-13 12:47
chrome / vscode on linux dont scroll nice

chrome + smooth scroll extension and vscode with `"editor.mouseWheelScrollSensitivity": "4"` is about the most manageable i found so far

**Comment by ejonsson** [comment] 2019-01-15 17:09
Please just respect the operating system's mouse settings. There's no need to reinvent the wheel here, quite literally.
The touch and feel of an input device is something that people get very accustomed to. Any slight change is immediately noticed, and it can be very frustrating.

@alexandrudima In my experience across different platforms, Chromium / Chrome has always respected OS scroll settings, unlike the other cross platform browser, so I don't think the blame can be placed there.

**Comment by storm1er** [comment] 2019-12-26 18:56
Problem still exist in 1.41, using "editor.mouseWheelScrollSensitivity": ".01" in settings works into terminal but not in editor :/

**Comment by Ares9323** [comment] 2020-03-11 15:00
> Problem still exist in 1.41, using "editor.mouseWheelScrollSensitivity": ".01" in settings works into terminal but not in editor :/

In my case it works in the editor but not in the terminal..
The strange thing is that the output windows works perfectly

**Comment by thalesnunes** [comment] 2020-06-04 15:39
In my case it worked changing `terminal.mouseWheelScrollSensitivity` to change the terminal sensitivity and `editor.mouseWheelScrollSensitivity` to change the editor

**Comment by waynecnr** [comment] 2021-06-16 20:37
This still isn't fixed in 1.57? This is a huge shortcoming of an otherwise great editor

**Comment by SpriteOvO** [comment] 2021-07-20 03:42
> In my case it worked changing `terminal.mouseWheelScrollSensitivity` to change the terminal sensitivity and `editor.mouseWheelScrollSensitivity` to change the editor

@ejonsson It doesn't work for me. I tried `"terminal.mouseWheelScrollSensitivity": 0.1` and `"terminal.mouseWheelScrollSensitivity": 1`, but the "settings.json" shows error "Unknown Configuration Setting" and the terminal still scrolls 6 lines at a time. The editor's scrolling worked well for me.

Does anyone know of any other workaround?

**Comment by SpriteOvO** [comment] 2021-07-20 03:46
> > In my case it worked changing `terminal.mouseWheelScrollSensitivity` to change the terminal sensitivity and `editor.mouseWheelScrollSensitivity` to change the editor
> 
> @ejonsson It doesn't work for me. I tried `"terminal.mouseWheelScrollSensitivity": 0.1` and `"terminal.mouseWheelScrollSensitivity": 1`, but the "settings.json" shows error "Unknown Configuration Setting" and the terminal still scrolls 6 lines at a time. The editor's scrolling worked well for me.
> 
> Does anyone know of any other workaround?

Oh! I figured it out, the configuration name has changed, it is now named `terminal.integrated.mouseWheelScrollSensitivity`.

**Comment by hediet** [comment] 2021-11-02 16:16
/duplicate of #112134 which has more upvotes.

**Closed** 2021-11-02 16:17 UTC
Labels: feature-request, *duplicate, editor-scrollbar

**Comment by duzenko** [comment] 2021-11-02 18:43
Don't you love how they close tickets? Why fix it when you can just wait a few years for a duplicate
