### ISSUE TITLE
Got error message when turning terminal off

### ISSUE THREAD

**Issue by brian41005** [Microsoft/vscode#38476] opened 2017-11-16 05:14 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ftp-sync|luk|0.3.3
Go|luk|0.6.67
python|ms-|0.8.0
cpptools|ms-|0.14.2

---

Steps to Reproduce:

1. press ctrl+` to  turn on integrated  terminal 
2. then turn it off (kill)
3. I got this...
![image](https://user-images.githubusercontent.com/13401708/32874876-dc2ad7c0-cacf-11e7-9e17-fe99ce7e5755.png)

****

Reproduces without extensions: Yes

**Comment by Bibliofile** [comment] 2017-11-16 18:09
This is a dupe of #38348

**Closed** 2017-12-15 16:22 UTC
Labels: integrated-terminal
