### ISSUE TITLE
Explorer does full recursive refresh when a file system is registered

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71163] opened 2019-03-26 11:48 UTC
* have an extension that contributes a file system provider
* profile startup
* 🐌 when the fs provider is registered the explorer does a full recursive (expensive) refresh even though it doesn't show anything of that provider

<img width="595" alt="Screenshot 2019-03-26 at 12 46 56" src="https://user-images.githubusercontent.com/1794099/54994736-4c5fa900-4fc5-11e9-991c-ca038a33e6c9.png">

**Comment by jrieken** [comment] 2019-03-26 11:49
e.g. the file system provider is `gitlens`

**Comment by isidorn** [comment] 2019-03-26 16:48
Good catch. We refresh the explorer in this case since the file system provider might unregister and register itself to make itself readonly. This requires that all the file stats are refreshed.
To optimaze that I changed that I only refresh the explorer if the file system provider got re-registered. I know that by rembering the schemes of the register providers thus far.

**Comment by jrieken** [comment] 2019-03-26 16:59
👏

**Comment by isidorn** [comment] 2019-03-29 10:09
Due to https://github.com/Microsoft/vscode/issues/71423 I will push a revert for this.
I still want to do this fix, howevere due to timing I decided to do them in debt week when we can get more details why this optimisation broke live share.
Reopening and moving to april

**Comment by isidorn** [comment] 2019-04-01 12:13
Reverted the revert since it is not the cause of the Live Share issue. Thus closing this.
More details here https://github.com/Microsoft/vscode/issues/71423

**Closed** 2019-04-01 12:14 UTC
Labels: bug, file-explorer, perf, perf-startup
