### ISSUE TITLE
Webview: sometimes loosing the scrollbar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8256] opened 2016-06-28 09:05 UTC
Refs: https://github.com/Microsoft/vscode/issues/7945

Not sure how I got into this state, but suddenly my right scrollbar is gone? This is on Windows 7:

![image](https://cloud.githubusercontent.com/assets/900690/16409900/268ee4ee-3d20-11e6-84e0-75d344c85fab.png)

**Comment by kieferrm** [comment] 2016-06-30 22:18
Steps to reproduce:
1. open a markdown file whose preview is larger than the editor window
1. open markdown preview to the side
1. make a change in the markdown file

**Comment by jrieken** [comment] 2016-07-13 11:55
Seems to be caused by our scroll bar customisation. When I remove that things are working

**Comment by jrieken** [comment] 2016-07-25 13:09
This is an upstream issue but I haven't boiled it down to a small repo yet...

**Comment by Huachao** [comment] 2016-08-05 07:42
repro with extension using 'preview.Html' command

**Comment by Huachao** [comment] 2016-09-18 11:27
@jrieken @bpasero any updates on this, depending on electron?

**Comment by bpasero** [comment] 2016-09-18 12:30
@Huachao you can try to repro from our insiders release where we since updated Electron: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Huachao** [comment] 2016-09-18 13:22
@bpasero it seems the latest version didn't solve the issue at least for me

**Comment by Huachao** [comment] 2016-10-13 16:51
@bpasero the electron update doesn't work, any updates, thanks

**Comment by mjbvz** [comment] 2017-01-31 19:38
I believe that this was fixed by #19394, which worked around an upstream chrome issue where updating iFrame content could cause the scrollbar to disappear: https://bugs.chromium.org/p/chromium/issues/detail?id=678821

Also see #17617

Please try VSCode 1.9 and let me know if you still see this

Thanks

**Closed by mjbvz** 2017-01-31 19:38 UTC
Labels: bug, upstream, webview
