### ISSUE TITLE
Can't Install any extensions 

### ISSUE THREAD

**Issue by hashmachine07** [Microsoft/vscode#21605] opened 2017-03-01 07:04 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
 Just started with VS Code today. I am not able to install any extensions. Tried opening some C# files, it recommends me to use a C# extension. Clicked on "Install" button, nothing happens.. Its the same case with other extensions.

**Comment by joaomoreno** [comment] 2017-03-01 09:11
Closing as duplicate of #18103

**Closed by joaomoreno** 2017-03-01 09:11 UTC
