### ISSUE TITLE
enter new line not working after update

### ISSUE THREAD

**Issue by RioBoy** [microsoft/vscode#178865] opened 2023-04-01 02:45 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.0
- OS Version:  Windows 11 Home

Type: Bug

After updating my VS Code, I cannot use enter to a new line, can anyone help me, I have tried many ways and got stuck.

**Comment by rheech22** [comment] 2023-04-01 10:43
In my case, It works after deleting this keyboard shortcut below.

Setting Menu > Keyboard Shortcuts
<img width="252" alt="스크린샷 2023-04-01 오후 7 39 40" src="https://user-images.githubusercontent.com/57756798/229282476-73955215-a625-47fc-9331-532af5ce3a4c.png">

logged in [Troubleshooting keybindings](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings)
<img width="1783" alt="스크린샷 2023-04-01 오후 7 30 48" src="https://user-images.githubusercontent.com/57756798/229281917-33818a54-f42d-416a-938d-7e63f982c512.png">

**Comment by tamuratak** [comment] 2023-04-02 11:17
Might be duplicate of https://github.com/microsoft/vscode/issues/178788#issuecomment-1492663441 or https://github.com/microsoft/vscode/issues/178782#issuecomment-1492651359

**Comment by RioBoy** [comment] 2023-04-08 00:49
> In my case, It works after deleting this keyboard shortcut below.
> 
> Setting Menu > Keyboard Shortcuts <img alt="스크린샷 2023-04-01 오후 7 39 40" width="252" src="https://user-images.githubusercontent.com/57756798/229282476-73955215-a625-47fc-9331-532af5ce3a4c.png">
> 
> logged in [Troubleshooting keybindings](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) <img alt="스크린샷 2023-04-01 오후 7 30 48" width="1783" src="https://user-images.githubusercontent.com/57756798/229281917-33818a54-f42d-416a-938d-7e63f982c512.png">

Thanks @rheech22 , i actually find the answer in this comment https://github.com/microsoft/vscode/issues/178782 it works find for me.

**Closed** 2023-04-08 00:52 UTC
Labels: info-needed
