### ISSUE TITLE
sticky TabMovesFocus config

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9705] opened 2016-07-25 14:40 UTC
### Steps to Reproduce (1/2)

* enable workbench tab (`showTabs`)
* have two editor columns, editors in each
* run the `Keyboard Shortcuts` config action
* select `Cmd+1` to focus column #1
* select a different writable editor in that column
* 💥 tab moves focus

### Steps to Reproduce (2/2)

1. Have a 2 pane layout.
2. Hit <kbd>Cmd ,</kbd> to open user settings.
3. Hit <kbd>Cmd 1</kbd> to focus the first pane.
4. Use quick open to switch to an editable file.
5. Hit <kbd>Cmd 2</kbd> to focus the user settings and make any **valid** change there.
6. Hit <kbd>Cmd 1</kbd> to focus the first pane.

<kbd>Tab</kbd> will now focus away from the editor instead of inserting a `TAB`.

**Comment by joaomoreno** [comment] 2016-07-25 14:47
Yeah today I was in a state in which <kbd>Tab</kbd> was moving focus instead of indenting. I couldn't reproduce though. I know I didn't have tabs enabled, too.

**Comment by jrieken** [comment] 2016-07-25 15:18
@alexandrudima I have pushed https://github.com/Microsoft/vscode/commit/da56a2cd4084fcb88069ba553e4b5b5f859b697c to 'fix' this cos I could see [this event](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commonCodeEditor.ts#L169) wasn't fired after the `upateOptions` call. Unsure what the underlying issue is.

**Comment by jrieken** [comment] 2016-07-25 15:20
@joaomoreno Can you check with my steps from above without tabs? Also can you check that my change fixes this?

**Comment by joaomoreno** [comment] 2016-07-25 15:43
Can't repro, so that's good. 👍

**Comment by joaomoreno** [comment] 2016-07-25 15:44
Yup! I can repro before your change but not after it. 👍

**Comment by jrieken** [comment] 2016-07-26 12:02
When the <kbd>Cmd+,</kbd> command happens a third editor is created and leaked. That editor is readonly and somehow interferes with another editor...

**Comment by jrieken** [comment] 2016-07-27 09:57
@bpasero Please check the changes in https://github.com/Microsoft/vscode/commit/3f446e49d214c8486b7b8e63cf3742227b98c755. The issue is like this:

* editors in a single column/pane share the same keybinding context
* editor inputs that are somehow [different](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorPart.ts#L274) cause multiple code editor widgets to be created for one column (which then share the same kb context)
* when an editor is invisible it still listens to configuration change events and updates its editor widget (respectively its context cause this), editors don't seem to be disposed ever

**Comment by joaomoreno** [comment] 2016-07-28 09:58
I hit another problem which led me to realise that *all* editor settings are affected. I've updated the initial comment with more generalised repro steps.

**Comment by jrieken** [comment] 2016-07-28 10:51
bummer - that's likely due to the change @aeschli and I made. Invisible editors don't listen to config changes anymore tho probably should update when becoming visible...

**Comment by jrieken** [comment] 2016-07-28 11:00
We must do something about this...

**Comment by jrieken** [comment] 2016-07-28 11:02
@joaomoreno I have moved the issue you described in #9892 cos it's a regression from not listening to config change event anymore

**Comment by joaomoreno** [comment] 2016-07-28 12:43
Got it, thought it to be exactly the same. Sorry about that.

**Comment by bpasero** [comment] 2016-08-05 15:14
@jrieken we can have more than 3 code editor widgets easily once we show the diff editor. So typically you can have 6 editors lying around (3 code editors and 3 diff editors).

There is no specific reason why a second code editor instance is being created for some inputs (readonly) and the one we have for files not being reused. This could probably be changed, but given the diff editor challenge, we might need a better solution to handle that case as well.

**Comment by jrieken** [comment] 2016-08-08 07:21
How about disposing?

**Comment by bpasero** [comment] 2016-08-08 07:25
@jrieken yes I can do that. @alexandrudima objections?

**Comment by alexandrudima** [comment] 2016-08-08 14:11
Not optimal, but disposing editors should be fine: there is some start-up time (in the range of a few millis) that is spent mostly instantiating contributions, but it might be non-noticeable.

**Comment by bpasero** [comment] 2016-08-08 14:17
@jrieken @alexandrudima I am also fine to have API to call to indicate to the editor that it is hidden, in fact I am already calling `onHide()` on the editor when this happens: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts#L3564

**Comment by alexandrudima** [comment] 2016-08-08 14:21
I'm sorry I don't have the time to go through all editor contributions and adopt in each and every one of them that they don't touch context keys unless the editor is visible. It is also a solution that does not guarantee bug-free new contributions.

Moreover, a pointer to the keybinding service can be grabbed by any editor client and a context key can be set outside editor contributions.

**Comment by bpasero** [comment] 2016-08-08 14:27
Ok I think I need more background on the issue, since I am not on the same page since I was on vacation. Somehow I thought this issue was coming from our use of keybinding service but I probably got that wrong.

Note that we have hidden editors since the beginning so I am not sure what recent change causes the editor config to get wrong.

**Comment by alexandrudima** [comment] 2016-08-08 16:17
Well, an example always helps. Consider the context key `findWidgetVisible`.

The `FindController` (that is an editor contribution) manages this context key. Specifically:
* when the find controller comes up, it sets the key to `false`.
* when the find widget gets shown, it sets the key to `true`.
* when the find widget gets hidden, it sets the key to `false`.

Now consider two editors that each have their own `FindController` working on the same keybinding service (which is what happens now). Now, there will be two instances of the `FindController` and they will both write to the `findWidgetVisible` key in the keybinding service.

Most times, the first one maybe has sufficient time to stop itself (via `setModel(null)` on the editor perhaps that leads to the find widget closing, that leads to the key being set to `false`) and the second one runs after the first one (via `setModel(model)` on the second editor that leads to the find controller restoring its previous state, that might lead to the key being set to `true`.

Now, if the timing is not spotless or if there are other conditions, the "hidden" find controller might interfere with the "visible" find controller and set the `findWidgetVisible` context key to an unexpected value.

**Comment by bpasero** [comment] 2016-08-08 16:24
@alexandrudima yeah I see the issue but is that not https://github.com/Microsoft/vscode/issues/10122 ?

I am asking because this issue is about `sticky TabMovesFocus config`. Is it the same issue?

**Comment by alexandrudima** [comment] 2016-08-09 09:05
They might all have the same root cause. Context keys might end up with incorrect values when multiple editor instances try to drive them.

**Comment by bpasero** [comment] 2016-08-09 09:09
Joh explained to me, I got it now. All related. We decided to start to dispose() hidden editors.

@alexandrudima is there a difference between dispose() and destroy() in your world?

**Comment by alexandrudima** [comment] 2016-08-09 10:36
I left `destroy()` in for compatibility purposes (simply calls `dispose()`), `dispose()` is preferred.

**Comment by bpasero** [comment] 2016-08-09 18:30
Merging into https://github.com/Microsoft/vscode/issues/10358

**Closed by bpasero** 2016-08-09 18:30 UTC
Labels: bug, important
