### ISSUE TITLE
Run Without Debugging (Nodejs) stopped working

### ISSUE THREAD

**Issue by toja83** [microsoft/vscode#206524] opened 2024-02-29 11:49 UTC
Type: <b>Bug</b>

After updating Visual Studio code to the latest version this morning my command "_Run Without Debugging_" stopped working.

I am on a Mac Book Pro M2.
My Visual Studio Code runs Version: 1.87.0 (_Universal_).
My project is a normal Nodejs project running a Nextjs app.
I am currently running Node version v18.19.1 (_LTS_).

My launch config looks like this:
```
{
  "name": "Run yarn dev",
  "type": "node-terminal",
  "request": "launch",
  "command": "yarn dev",
  "timeout": 30000
}
```

For the past years and up until this morning I have been able to start my app by both "_Start Debugging_" or "_Run Without Debugging_" command, which both launched a debug terminal and attached the "_Debug console_".

Since this morning after upgrading to the latest version, suddenly "_Run Without Debugging_" stopped working. I often use the "_play button_" on my Mac Touch bar, but starting with ^F5 or via menu "_Run > Run Without Debugging_" is not working either.

It does something, but not starting correctly, this is the only output I see in the terminal:
> yarn dev
> % yarn dev
> Debugger attached.

It does not start the server or anything after this, not showing anything in the Debug console. Although the "_debug bar_" is shown. The Nextjs server that should be served at localhost:3000 is also not available.
Also if I close the terminal, the debug bar stays like it is still running.
If I press stop in the debug bar it stopps, but it takes 5-10 seconds, usually stopes in ms.

NOTE!
Running "_Start Debugging_" remains working fine without no issues and behaves the same way as it used to!

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (0.84GB free)|
|Process Argv|--crash-reporter-id feb12229-107f-4ef9-8a0e-9ea5d41389a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
project-manager|ale|12.7.0
swagger-viewer|Arj|3.1.2
atlascode|atl|3.0.10
vscode-tailwindcss|bra|0.10.5
gitignore|cod|0.9.0
auto-dark-mode-windows|dan|1.0.11
dart-code|Dar|3.82.0
flutter|Dar|3.82.0
binary-plist|dni|0.11.3
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|14.8.2
vscode-html-css|ecm|2.0.9
search-node-modules|jas|1.3.0
svg|joc|1.5.3
vscolors|kev|0.0.6
git-graph|mhu|1.30.0
vscode-exec-node|mir|0.5.6
mongodb-vscode|mon|1.5.0
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vsliveshare|ms-|1.0.5905
vsliveshare-pack|ms-|0.4.0
back-n-forth|nic|3.1.1
vscode-thunder-client|ran|2.18.0
vscode-yaml|red|1.14.0
mongo-snippets-for-node-js|roe|1.3.12
partial-diff|ryu|1.4.3
code-spell-checker|str|3.0.1
code-spell-checker-swedish|str|1.3.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
gitblame|wad|10.9.0
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
pydisww2:30959801
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
e3gdj431:30958358
ccp2r3:30958157
dsvsc020:30973508
666c4381:30973075

```

</details>

**Comment by leosdad** [comment] 2024-02-29 13:38
Same thing here. Just updated to 1.87 and _Run without debugging_ stopped working. I use Windows 10, though.

**Comment by ilambrev** [comment] 2024-02-29 13:43
After update to version 1.87.0, I have the same problem too - Run without debugging stopped working properly. My OS is Ubuntu 22.04.4 LTS.

**Comment by connor4312** [comment] 2024-02-29 18:23
Thanks for the issue, this will be fixed in today's nightly debugger build https://github.com/microsoft/vscode-js-debug#nightly-extension

**Closed** 2024-02-29 18:38 UTC
Labels: bug, debug, new release

**Comment by Eyewais** [comment] 2024-03-21 18:04
> Thanks for the issue, this will be fixed in today's nightly debugger build https://github.com/microsoft/vscode-js-debug#nightly-extension

Thank you so much, I have been scratching my head due to this for almost a month now.

**Comment by borizoto** [comment] 2024-03-25 21:18
The problem is still present, i've tried reinstalling both node and vscode, also tried with older versions of node but nothing seems to be working.

**Comment by connor4312** [comment] 2024-03-25 21:21
@borizoto please see my previous comment

**Comment by borizoto** [comment] 2024-03-26 08:14
@connor4312 my bad, I didn't see it. So basically I should download this nightly debugger that is an extension and not use the already incorporated default debugger that I've been using for months? 
Have a nice day and thanks is advance!
