### ISSUE TITLE
#17605  should not be closed!

### ISSUE THREAD

**Issue by stefanaerts** [Microsoft/vscode#17826] opened 2016-12-26 10:01 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open multiple vscode projects
2. There is no list with the open windows in the 'window' menu.It says only 'bring all to front'.
![image](https://cloud.githubusercontent.com/assets/3684599/21480115/64d19f62-cb5a-11e6-8b23-e74aa747c8c7.png)

The answer from egamma is not correct,there is no list with open windows in the doc menu,it shows only a list of previous opened projects,not the current open projects.
![image](https://cloud.githubusercontent.com/assets/3684599/21480149/a53bee68-cb5a-11e6-9cc9-5b7ebafa1b03.png)

**Comment by mrmlnc** [comment] 2016-12-26 10:12
Instead of creating a duplicate Issue, you should write comments on existing Issues.

Duplicate of #17605

**Comment by egamma** [comment] 2016-12-26 14:50
@stefanaerts thanks for the additional feedback, as suggested by @mrmlnc let continue the discussion in #17605

**Closed by egamma** 2016-12-26 14:50 UTC
