### ISSUE TITLE
vsc no respond when save large json file which pasted from another vsc window

### ISSUE THREAD

**Issue by RookieDay** [Microsoft/vscode#17859] opened 2016-12-27 17:02 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-html-css|ecmel|0.0.30|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.1|

---

Steps to Reproduce:
I always have this issue when save large json file and repro steps as below: 
1. open two vsc window
2. open a.json file which i used and copy a.json
3. create empty b.json file in anohter vsc window and paste
4. **save** b.json file 
5. vsc window is no responding when **save** b.json file and i can`t click any other tabs and can`t do anything
6. you can get a.json file and repro detail steps from [https://github.com/RookieDay/TempIssue](url)  --select JsonIssue folder then u can find a.json file

  - a.json      ->file
  - 01.gif      ->repro detail steps
  - 02.png    ->respond from vsc
6. as the below screenshot showed, when i click "keep waiting" ,vsc sometimes woks again 

#15885 

![01](https://cloud.githubusercontent.com/assets/19630825/21535238/2473d868-cdad-11e6-9520-fa5ccfc4550e.gif)

![02](https://cloud.githubusercontent.com/assets/19630825/21504037/a2826570-cc96-11e6-98ea-ed3aa0f2cf3b.png)

**Comment by King66** [comment] 2016-12-30 03:36
I think this was caused by the plugin "JS-CSS-HTML Formatter" by lonefy.
VSCode freeze when saving file..

**Comment by RookieDay** [comment] 2016-12-30 13:48
@King66 
Thanks for your response,it seems works when i disable all extensions, but why issue caused by "JS-CSS-HTML Formatter" extension? maybe this extension have some issues /bugs?

**Comment by aeschli** [comment] 2016-12-30 18:37
Closing issue.

**Closed by aeschli** 2016-12-30 18:37 UTC

**Comment by aeschli** [comment] 2016-12-31 01:18
This issue was moved to Lonefy/vscode-JS-CSS-HTML-formatter#43
