### ISSUE TITLE
Improve Markdown preview panel behavior

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/vscode#91401] opened 2020-02-25 15:15 UTC
While "open preview to the side" does create a Markdown preview panel that follows the selected tab, it currently stays open for tabs that don't contain Markdown, which is a bit odd.

I'd like to suggest two minor changes to improve this experience:

1. Make the Markdown preview panel follow the opened file only: so the Markdown preview would be tab-dependent by default, meaning you can open/close it as you please, per tab, and if it's open/closed for a specific tab, it stays open/closed when you switch tabs.

2. Add a "pin" button to the Markdown preview panel: this would make the Markdown preview stay open when you switch tabs or open new files - somewhat like the current behavior, but with the panel only showing when the active tab actually contains Markdown.

**Comment by mindplay-dk** [comment] 2020-02-25 15:22
Somewhat related: two extension authors have attempted to make the Markdown preview stay open [here](https://marketplace.visualstudio.com/items?itemName=hnw.vscode-auto-open-markdown-preview) (170K installs, unmaintained, not working) and a fork [here](https://marketplace.visualstudio.com/items?itemName=timgreen.vscode-auto-open-markdown-preview-enhanced&ssr=false#review-details) which didn't work for me either - an obvious option (the "pin" described above) in the UI would probably satisfy most of these users.

**Comment by mjbvz** [comment] 2020-02-25 18:59
Duplicate of #66132  #54776 #2766

**Closed by mjbvz** 2020-02-25 18:59 UTC

**Comment by mindplay-dk** [comment] 2020-02-26 07:57
@mjbvz apologies for the duplicate issue! I did a pretty careful search and looked at many issues before opening this - I also looked at the "possible duplicates" before posting and don't think any of these were in there.

The number of open issues is quite overwhelming and GitHub's issue search doesn't seem to order results by relevance at all. (Maybe you could talk to the GitHub team about improving this?)

**Comment by mindplay-dk** [comment] 2020-02-26 08:00
For the record, not a single one of these comes up on page 1 in a search - there's no option to sort by relevance, so this really doesn't work well for a repository with this level of activity...

![image](https://user-images.githubusercontent.com/103348/75324041-614c5880-5876-11ea-8354-b63567f4b8ee.png)

**Comment by mjbvz** [comment] 2020-02-27 00:07
No problem! Just wanted to let you know this is already something we are aware of and investigating
