### ISSUE TITLE
Ctrl+L Failure

### ISSUE THREAD

**Issue by robynTekside** [microsoft/vscode#79508] opened 2019-08-20 13:30 UTC
In the terminal, the keyboard shortcut Ctrl+L to clear the terminal window is not working properly.  Using the shortcut will clear the window temporarily, but it will revert back when you begin typing another command.

**Comment by RMacfarlane** [comment] 2019-08-20 23:25
/needsMoreInfo please include the version of VSCode you're using and what OS you're on

**Comment by robynTekside** [comment] 2019-08-22 15:47
Version: 1.37.1
OS: Windows_NT x64 10.0.17763

Extensions:  
- Debugger for Chrome
- Beautify
- Docker
- Rainbow CSV

Reproducible steps:
1. Open a terminal 
2. ls 
3. Ctrl + L 
4. type anything

What you expected to see, versus what you actually saw:
Expected screen to stay cleared, and not view the previous results 
What actually happened was the terminal window did not stay cleared

**Comment by RMacfarlane** [comment] 2019-08-23 20:54
Thanks! This looks like a duplicate of https://github.com/microsoft/vscode/issues/75141

**Closed by RMacfarlane** 2019-08-23 20:54 UTC
Labels: needs more info
