### ISSUE TITLE
Using Input variable inside task `Command` breaks path by prepending CWD

### ISSUE THREAD

**Issue by ThaDaVos** [microsoft/vscode#206412] opened 2024-02-28 08:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows_NT X64 10.0.26063

Steps to Reproduce:

1. Add below snippet as `tasks.json`
2. Run `Do Something with Path from PickString` and select `C:\Temp`
3. See the current directory being appended to the path, resulting in `{CWD}\C:\Temp\DoSomething.exe` being called, instead of the expected `C:\Tempt\DoSomething.exe`

I first thought this was an issue with an extension I was using: https://github.com/rioj7/command-variable/issues/83

*Tasks.json*:
```json
{
  "version": "2.0.0",
  "inputs": [
    {
      "id": "selectDirectory",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Deploy to where?",
        "options": [
          ["Use previous directory", "${remember:deployDirectory}"],
          ["Pick directory", "${openDialog:deployDirectory}"]
        ],
        "default": null,
        "openDialog": {
          "deployDirectory": {
            "description": "Which directory?",
            "canSelect": "folders",
            "defaultUri": "C:\\temp",
            "keyRemember": "deployDirectory"
          }
        }
      }
    },
    {
      "id": "pickADirectory",
      "type": "pickString",
      "description": "Pick a directory to use",
      "options": [
        "C:\\Temp"
      ]
    }
  ],
  "tasks": [
    {
        "label": "Task A",
        "command": "Write-Output",
        "type": "shell",
        "args": [
            "Selected '${input:selectDirectory}' for A"
        ]
    },
    {
      "label": "Do Something with Path",
      "command": "${input:selectDirectory}\\DoSomething.exe",
    },
    {
      "label": "Do Something with Path in workspace",
      "command": "${workspaceFolder}\\DoSomething.exe",
    },
    {
      "label": "Do Something with Path from PickString",
      "command": "${input:pickADirectory}\\DoSomething.exe",
    }
  ]
}
```

**Comment by meganrogge** [comment] 2024-02-28 15:17
Based on your configuration, this is working as designed since you include the workspace folder variable

**Comment by ThaDaVos** [comment] 2024-02-28 15:27
> Why are you using input here if it's just one option?

It was a small reproducable setup - the one I ran into the issue in, is way longer so I created the smallest reproducable I could think off

But the issue is, that the CWD is being appended if the `command` contains a variable through `input` - if you use `${workspaceFolder}` it does not - so `Do Something with Path from PickString` goes wrong

**Comment by meganrogge** [comment] 2024-12-11 18:17
closing as I cannot reproduce the issue

<img width="883" alt="Image" src="https://github.com/user-attachments/assets/1270eb6c-f68a-4945-ba0b-5167b99a9aa9" />

**Closed by meganrogge** 2024-12-11 18:17 UTC
Labels: tasks, confirmation-pending
