### ISSUE TITLE
Notebook scrolls too far when running a cell with Shift+enter, the cell that was ran moves out of sight

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#121871] opened 2021-04-21 21:14 UTC
@randomQQQ commented on [Sat Apr 17 2021](https://github.com/microsoft/vscode-jupyter/issues/5542)

## Environment data

VS Code version: Code - Insiders 1.56.0-insider (ce791d2, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.19042

## Expected behaviour

![jp](https://user-images.githubusercontent.com/63656568/115127896-c024e200-9fe2-11eb-8f93-f5bf2554be2d.gif)

## Actual behaviour

![vscode](https://user-images.githubusercontent.com/63656568/115127903-cb780d80-9fe2-11eb-8225-e8215354b34f.gif)

---

@DavidKutu commented on [Mon Apr 19 2021](https://github.com/microsoft/vscode-jupyter/issues/5542#issuecomment-822646287)

Thanks for the bug @randomQQQ. How are you running the cell? Is it `shift + enter`?

---

@randomQQQ commented on [Mon Apr 19 2021](https://github.com/microsoft/vscode-jupyter/issues/5542#issuecomment-822651721)

Yes 

---

@DavidKutu commented on [Mon Apr 19 2021](https://github.com/microsoft/vscode-jupyter/issues/5542#issuecomment-822838460)

The scrolling looks like default VS code behavior, its from the command `notebook.cell.executeAndSelectBelow`.
I'll bring it up in our next triage meeting.

**Comment by rebornix** [comment] 2021-08-05 19:03
/duplicate of https://github.com/microsoft/vscode/issues/121723

**Closed by rebornix** 2021-08-05 19:03 UTC
Labels: bug, *duplicate, notebook
