### ISSUE TITLE
Reactivating terminals

### ISSUE THREAD

**Issue by Cristi192005** [microsoft/vscode#233171] opened 2024-11-06 07:04 UTC
Type: <b>Bug</b>

I can't run the code. All it say's its just reactivating terminals over and over again. Like how am I supposed to work like this. I can't get my work done. Please fix it ASAP

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.86GB (3.50GB free)|
|Process Argv|--crash-reporter-id bf0fd76d-e752-4cbe-b708-2850eeb2e347|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.4.53
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by karthiknadig** [comment] 2024-11-08 17:05
Duplicate of https://github.com/microsoft/vscode-python/issues/23922

Add this to your user settings and reload VS Code:
```
"python.experiments.optOutFrom": ["pythonTerminalEnvVarActivation"],
```

**Closed by karthiknadig** 2024-11-08 17:05 UTC
