### ISSUE TITLE
Manually adding cursors in html tags can interfere with mirrorCursorOnMatchingTag

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89577] opened 2020-01-29 00:01 UTC
Issue Type: <b>Bug</b>

From https://github.com/microsoft/vscode/issues/86978#issuecomment-565740856

**repo**
For the html:

```html
<div>1</div>
<div>1</div>
<div>1</div>
<div>1</div>
```

1. Start with cursor at the end of opening tag on first line. This should create a matching tag on the closing tag
1. Now click to add another cursor on the next line to try adding an addtribute in multiple locations

**Bug**
This results in 3 cursors which prevents correctly adding the attribute

![Error](https://user-images.githubusercontent.com/22962322/70852960-17bfb480-1ea8-11ea-85bf-59cd30b7ee70.gif)

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.54GB free)|
|Process Argv|-psn_0_1913299|
|Screen Reader|no|
|VM|15%|
</details>

**Comment by octref** [comment] 2020-01-30 19:18
Duplicate of #88127

**Closed by octref** 2020-01-30 19:18 UTC
