### ISSUE TITLE
Visual Studio Code Breaks Links in Django Templates upon File Save 

### ISSUE THREAD

**Issue by qtakabg** [Microsoft/vscode#44342] opened 2018-02-24 20:38 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.15.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gc-excelviewer|Gra|2.0.19
vscode-devskim|MS-|0.2.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-faker|dee|1.2.1
jquerysnippets|don|0.0.1
gitlens|eam|8.0.0
prettier-vscode|esb|1.1.3
auto-close-tag|for|0.5.6
rest-client|hum|0.17.0
docthis|joe|0.6.0
fuzzy-definitions|jri|0.0.3
python|ms-|2018.1.0
debugger-for-chrome|msj|4.1.0
vscode-css-peek|pra|2.1.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.20.0
vscode-djaneiro|the|1.3.0

---

Steps to Reproduce:

1. Create new html file with the following line in it:
 <img src="{% static "images/image-name.jpg" %}"
             alt="Image" />
2. Save the file.
Result:
Spaces are added between the image path and the quotes, thus breaking the link in Django routing:
 " images/image-name.jpg " 
Furthermore, the tag is formatted into one line which is not very nice for long lines.

Reproduces without extensions: Yes

**Comment by 199621** [comment] 2018-02-25 10:45
i like to thank each and ever one of you i no nothing about code and now i feel like im dumb as a coal bucket next to yall ole boy that sent these pics he stole from me and thanks to yall i have most of them back he used lts file and i think a co that makes bad code to hide files but thank you for every thing that yall done i would not have what i do if not for yall now she is gone never to return and i will be gone as well this is where and when it all started and i guess we all have to wait to see how it ends thank you again you made a hill billy happy  
 Received: from HE1EUR02HT199.eop-EUR02.prod.protection.outlook.com
 (10.164.143.25) by DM5PR03MB3353.namprd03.prod.outlook.com with HTTPS via
 DM5PR08CA0036.NAMPRD08.PROD.OUTLOOK.COM; Sun, 24 Dec 2017 00:35:00 +0000
Received: from HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
 (10.152.10.57) by HE1EUR02HT199.eop-EUR02.prod.protection.outlook.com
 (10.152.11.91) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.20.302.6; Sun, 24
 Dec 2017 00:34:59 +0000
Authentication-Results: spf=pass (sender IP is 40.92.7.18)
 smtp.mailfrom=hotmail.com; hotmail.com; dkim=pass (signature was verified)
 header.d=hotmail.com;hotmail.com; dmarc=pass action=none
 header.from=hotmail.com;
Received-SPF: Pass (protection.outlook.com: domain of hotmail.com designates
 40.92.7.18 as permitted sender) receiver=protection.outlook.com;
 client-ip=40.92.7.18; helo=NAM03-CO1-obe.outbound.protection.outlook.com;
Received: from NAM03-CO1-obe.outbound.protection.outlook.com (40.92.7.18) by
 HE1EUR02FT055.mail.protection.outlook.com (10.152.11.101) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.20.302.6 via Frontend Transport; Sun, 24 Dec 2017 00:34:59 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:E316788E2F838C59081909DEA45BDFED11F2D9E016796D83BF6780FE40DFCBFD;UpperCasedChecksum:E0BE175F3A71DAD60B08411AD774806AA3ACA5557A92CBF94630EC7A44940C77;SizeAsReceived:4974;Count:38
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
 s=selector1; h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=CXNhvup2nD1lADH614RWXcdf8uEHcFFWemepon+dtNI=;
 b=SbxjWdTEODIIoBzxPPYoTDpI7QNgH1P/6Te9tSzahywA6NCA/ZRr10Cg5uorTguh632OZy0LQbyp3om2hIqHtNYSqBVu5H7Bm9M/D6B1CRBrY5zi6WwEiVczglypIS+U4FP7KrJIFw0RAZ6jRAVhEMR4G1TBoGt/VPAIprIGgnXbeX5IzU9jBcvT+bO5a2Tfjz3tMi8mZrK1q8QGsTIxuwKTYFbbET0abzC8CuGm9RTNt2jpXQMf+7XC1cMFUjRe95D3F8BeoPWp1FFsFkBqxtyYO8o+kYKgJKY5g4PGqegQrxpXAuLnlIO5QxjR8Q1STnLskPyzbx7kJTbBksb3LA==
Received: from BY2NAM03FT030.eop-NAM03.prod.protection.outlook.com
 (10.152.84.53) by BY2NAM03HT058.eop-NAM03.prod.protection.outlook.com
 (10.152.85.227) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.20.345.12; Sun, 24
 Dec 2017 00:34:53 +0000
Received: from DM5PR03MB3353.namprd03.prod.outlook.com (10.152.84.58) by
 BY2NAM03FT030.mail.protection.outlook.com (10.152.84.214) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id
 15.20.345.12 via Frontend Transport; Sun, 24 Dec 2017 00:34:53 +0000
Received: from DM5PR03MB3353.namprd03.prod.outlook.com ([10.174.241.150]) by
 DM5PR03MB3353.namprd03.prod.outlook.com ([10.174.241.150]) with mapi id
 15.20.0345.013; Sun, 24 Dec 2017 00:34:52 +0000
From: phillip matthews <onekid69@hotmail.com>
To: phillip matthews <onekid69@hotmail.com>
Subject:
Thread-Index: AQHTfE8D+KDjUfjbf06Wpc4Gq8PSyg==
Date: Sun, 24 Dec 2017 00:34:52 +0000
Message-ID: <DM5PR03MB335332A6770F1800F09824C9C2000@DM5PR03MB3353.namprd03.prod.outlook.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-incomingtopheadermarker: OriginalChecksum:BC4C325ED0A3C22B9FDB067CEB9BEA0305FAA3C4FFD587F0E8AC7026307D15C1;UpperCasedChecksum:4BF90BF76947D329813530D33D350E407469FBA1F3E00BCCB28C034C18E56963;SizeAsReceived:6738;Count:43
x-ms-exchange-messagesentrepresentingtype: 1
x-tmn: [ds0EDlq/GYbugDK4FyhkYSFRJrmDe+zL]
x-ms-publictraffictype: Email
X-Microsoft-Exchange-Diagnostics-untrusted: 1;BY2NAM03HT058;6:9rRoQ63+ov+ryyCB+R5eJsIWsWA84PvB7aKM+LtuTBtuZmF40wwz5PyETw9i8Ay/g7LRXaxc+eQL9ReIxad8WrGQlP6jwzKTd3axXLRQHpbV4+9NMz1ly7VKS2asfFI5ZVYL70E25ECLH/EZapFiD+EzWb4GIINGfdGsk9d55s3k6GZ/GIkqEeP34XQ8hoqOseViYW1QIvm+xhh3wzrGVmnH/E7X3s61UtAuA4NHAJHAO+scIhGgJ6igIcLvXupZeulCs76f1oHOphroPpn81FZtJcgrpkjYRkxdTbgfYzu3Sh+sG9syIBtGvKNFzese4atZwJzWJHc9jBMuJh0x3uV9qgA9/gOgj422GSUFGw0=;5:AiGla2sisA1oCDDgUNysrWX0Ob64NJQh0grxP5eS7UoxsMNdv0iYCpddwGns0LAkvrrngUhZ4L/VzVN2GyTjr5TW7wnuHrrsG5+udSyXN/6+fWWE3rZmDACfZDqjnhqMLPcMyqvCXKNn1Z0gLauZxN77CHWjyAzvU4XX08QGvZ8=;24:guqOJYvfzQ5p4JzAJpApJ5DOYAocEZeYLHwZ8XpS1XICxurttvRaTDM3wg3wLQNXCIB3PSuk1IN8RqCEg0gBM3kYWIVhDyhQksj4v245/Vk=;7:ju7J4wzxjiNd1jWx07Id43oUegb5QqG6kq/XvhlJuJeM+CGqDVj2dD0LMIqi3lfszNAf0EPFCFRdn6qc18uhvkcmfNEZ99VqWswjVx//eqOMGL5xw0DjHqFTrznLUb4/s2u7XIIDEZMTJ21Ec+ElOHjKH6D+aeogfRAInEffguLLelgvxplmvPM1rkII+Ckof7Q/DQlsOaCdwh1i5UCfCAG6nqiKMc0l/l2NNz8YM6VhQpgCpswziGFEfLhwv7DH
x-incomingheadercount: 43
x-eopattributedmessage: 1
X-Microsoft-Antispam-Untrusted: UriScan:;BCL:0;PCL:0;RULEID:(7020020)(201702061074)(5061506573)(5061507331)(1603103135)(2017031320274)(2017031324274)(2017031323274)(201702181274)(2017031322404)(1601125374)(1603101448)(1701031045);SRVR:BY2NAM03HT058;
x-ms-exchange-slblob-mailprops: o2C/200ZYyEEAaZYu0BX0fgsXGFHsoTg7nZyQZxhFEmmyM6+ZbpItfWA9bUw9tduWkZc/LJzooi8AtYt7lymIr2loxRgbA2PC0b92Q9OelDUYkAAn7fH6IsMPYWoOGVd8LF/g3TLemE0Qb5JDfr4H4arLvBIJ35sl7/woa507YYVLX3r/1zfQ92MREmYPti4td3ubEXIADtQK/I5tGQeJDQ3LuEpkHrVOxK4OdtXi/sOsXHaZEAtooeyHRfDqmeJJKuZ8X/+jTE7CsLTlZIO6csg0ZFNs7ZeDnnup/rOmTH7g+bpoOdjLcY+ult5cXKZc1QT2/0WMIC6TX9G7QDMCtPsZ1SSWry+F2MddZZ2JQa9iS12PgqWeJMkrThoQEWg+oCAIYW5kGYJ+PmRfE0fKgD+TibXuW6EWUVojQMXZEOVB2ZaSjci+CwT6+o2hja11GKUKgM9HyTQLrbxp31RJ9+1w1k6imxGaYpAt0Y5NU+lBCNmjkS16AzMeYqtmlhR8MZI/qWv8CxaVBWX8LivUNHp0XATiJo4hYRkIZ4+X+k=
X-MS-TrafficTypeDiagnostic: BY2NAM03HT058:|HE1EUR02HT199:
X-MS-Office365-Filtering-Correlation-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
x-exchange-antispam-report-cfa-test: BCL:0;PCL:0;RULEID:(444000031);SRVR:BY2NAM03HT058;BCL:0;PCL:0;RULEID:(100000803101)(100110400095);SRVR:BY2NAM03HT058;BCL:0;PCL:0;RULEID:(444111537)(595095)(82015058);SRVR:HE1EUR02HT199;BCL:0;PCL:0;RULEID:(100000803101)(100110400095);SRVR:HE1EUR02HT199;
x-forefront-prvs: 05315CBE52
X-Forefront-Antispam-Report-Untrusted: SFV:NSPM;SFS:(7070007)(98901004);DIR:OUT;SFP:1901;SCL:1;SRVR:BY2NAM03HT058;H:DM5PR03MB3353.namprd03.prod.outlook.com;FPR:;SPF:None;LANG:;
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
Content-Type: multipart/alternative;
    boundary="_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_"
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BY2NAM03HT058
X-IncomingHeaderCount: 38
Return-Path: onekid69@hotmail.com
X-MS-Exchange-Organization-Network-Message-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-Exchange-Transport-CrossTenantHeadersStripped: HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02FT055;1:qiOlFUKhlNvJy+MTWg3xI9IxLzHpj5ZFJZgv1omUPeHowLR0vOIeiol5uCtV/IlD54LKM4L8DzQTRElloeRN/i7Ez2txYlTqNhvYcbkdSWARDXxXSAAs+6zjB6r4lA/a
X-Forefront-Antispam-Report: EFV:NLI;SFV:NSPM;SFS:(98901004);DIR:INB;SFP:;SCL:1;SRVR:HE1EUR02HT199;H:NAM03-CO1-obe.outbound.protection.outlook.com;FPR:;SPF:None;LANG:;
X-MS-Exchange-Organization-AuthSource: HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-Microsoft-Antispam: BCL:0;PCL:0;RULEID:(5000109)(4604075)(4605076)(610169)(650170)(651021)(8291501071);SRVR:HE1EUR02HT199;
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;3:DYemr0KOFvEMFZcq+cBKD/NtzJAu5WxRVAJZxHQwxEEqlFk+doq4kKJLStm4H08DXlC6DNUdoIPNAoI6dXzJ34d9rdNT2ytDo6QfSshNI3Ut1hPE5XbUnL6p/I0npexdp//kTLmw6CpIbvHsHfbs0GBmK0rHA+UwwJGx1uqfT3TIQh8zHjQ3gxmXJMxul6iUkIIoyqFeq3egwurUkGIHTeC1jW0X/ekBRmbvKVfSdkdJeSZQQhQf12Ex+hwmfrxftHE9OKWzxjxnPf6cCj8N9MTWw7vd/u/VyN5kTHOvzzRUM1GtqMoEpSX8lwxLhg1M;25:jOY8aO9wTOd5RVVFHC00QX3TssCejoAdoC7QucD5nUzj/+2rn1eSI+e+DHVNfWl0vAUMn+26RZUU1sGBeU1KfMizMSPZwMVubdjf5eQD9nX3SiJO/O1Rcq+9CIdKfeQaKkO0XDBCaQo2iT2YkVUD9Zwx4Tgjf96QBJHGngzsXYLwYd513XG4JKe8hKHosH2LWGc7TwBn2zfk+HLL7WX/38YQfH13raqoyvkxybv70vrn1/HdTFBOqAnYuj/8VHiS3NfsDNvgtrZtakMjUqJQH09VvnN2ddYWmF1ZvXJIubTnJeJrebTIS3Te9FfCfdE0zDA2iKLOvf4Y5l6KYyRicQ==;31:fnemzE0H0MUaSRYEhZTQ6AeOuT9o91m6a9FJn5YbWZKu6Qeujw/lXzsU/y8D0oxW0i0ZlUIUIYljXHE7rkjiWEe4GztlV/pCEzcLqlzbkj6RVODas7+e5Jk+bgnpEPhb569vnwJ0tHeXdL3L5WNWVHp8sG16dWXgeFODtcUa9N08uzvNq+mxtfxTrbzXKVctInuzM0lO62bsJHDJlvPXV2MNroPgDtSdUXmSiclGiTY=
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 40.92.7.18
X-SID-PRA: ONEKID69@HOTMAIL.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2
X-Exchange-Antispam-Report-Test: UriScan:(111885846020525)(81439100147899);
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;4:HUJYXnHFPOgg+faPuz4CnULJbcdzvRuM4ZZ9T8tOYLXliUIY9iErneA49XRbYXaMzjMpNB0PTLNBC/tJFzw+nE9/s58FptaPRnsoqQ1geB5V3ecUXdacC7vAgsayBGcnxwY/DCU87qvci0Irhvuh5pnAi1+rowPIYjpk7UF6ez78bFYoCTIqnWzslDWhY4U7+r2FMNSC+WvHQx9rjf8mKMF/0yv+N8vqgzG8nrg7UOl2BtODnKDxdlcHwKb53KGQ+GU7ZC4zbuLUpqzcFwrlm9vm7kC+BbahncMoM5L4ybCWjC9Mmbssd4IgCnDLbXvCEsL0WPMvA4AYclU1fviYrjbfe+cX2LcUXSgUX/60acc=;23:axD9XGRQ6P3en751G1yCjK/fSbyL88GGQ9dz4PHoFhee2psiYt+K+hLN2iwexNEjVUMy+u5/+kwG2F1P/Cgwp75Kpk4FCtzrzKGslYl3nqxBxN9NEKtuI4vWBQo3tihxdBulc200z+FkzqIfuPqRWrNqO4eTGMKgnOjG17gs64U=;6:cxyTMPdhpAZQThyhl/JZUAjoEd9RnROsjnJHujRmNEy4RxDA9z2RQOfNI/33lnNnqtF1WQdcEap0NrnrFv6za/ChJBvCZQwur09Yw4nWuIEihWG6qjz1ExMfIO2RjMGanIllW28ZDRnZFKk5o/nwSELGFdDq/t+xRNul+y9uxJdoVbshZOLENUZSllqnNaTFdPSqEIGJ0/xvt6i2BOyeqoYi3VRhdwI8uAGJx5pASxqTvRWQ7g3ObcNAPNdpcxEmKWe0O5Jobgsa4FYTX9yg1GUig3FtsxDqjYxMZL6Y7Pq8nrxZyq7JOiDNeFVgDR4yxk6IYdPIcPjCyE7K+x2AhdtVR+5U4rhm3819JGKvyiM=
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Antispam-Message-Info: k5NNCdVLBm5geBpop/jZ/rGIMRmL5oIw2oXPK916bcM0/Amd2tPjzGu31X6IaF2cJOkujREOvfjPuXViTb3NSh3FcncNbIRv24O8H9LQmho=
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;5:qla/f5SollR7mM3fI4Xo4GU9U6kpcCiyp9jKnp4L9YdLvvyGmyKxJFylOe899HNvKvNrkEGrxUwq7vkDft+ieLd9BTmAyPf4x308nuW6IY9Ls6Zi4jkXeACfV194TteKuzr35vxc4Wx0Qo1Btyceyn9xDF8LSObjmrzhj6aGggM=;24:EypPdNKWDVb2vN+kS5UJy5CNVf2QkOBaUfF1U+z6Su+NFXpU4pB6VBhR0BAEpyjRs8z2QgyI0IOe+avfoVUnzmnO1cLZGayjXnbTW0a78m4=;7:5eO+b/yrVgXqaSk4AqFEr46SE3zdqnwesDc5UEpMuZwz1QUH9oAhAx5GY47PE1dvdfbd1zz8CcgPeorVyEWmm4uJvHdVAok1xhMW9rofZAHA4lByoHNyBWuJYgr8rbJHloi+1mC/qK73RQGcDuGwW99dxdHMVyeRROZBiuXybcL+JcxL/wL094t++seAIJTy0744yDlLdktdVi96fyoZKeKyN3VbLR9RPKR4/jickFkHl5KdNLvATLtzn3RdkIOc
X-OriginatorOrg: hotmail.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 24 Dec 2017 00:34:59.4680
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: HE1EUR02HT199
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.2446163
X-MS-Exchange-Processed-By-BccFoldering: 15.20.0345.013
X-Microsoft-Exchange-Diagnostics:
    1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
    dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
    5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
    4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY
MIME-Version: 1.0

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
X-Microsoft-Exchange-Diagnostics:
    1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
    dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
    5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
    4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY



Get Outlook for iOS<https://aka.ms/o0ukef>

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
X-Microsoft-Exchange-Diagnostics:
    1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
    dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
    5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
    4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY

<html=
><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
</head>
<body>
<div id=3D"compose-container" style=3D"direction: ltr" itemscope=3D"" itemt=
ype=3D"https://schema.org/EmailMessage">
<span itemprop=3D"creator" itemscope=3D"" itemtype=3D"https://schema.org/Or=
ganization"><span itemprop=3D"name" content=3D"Outlook Mobile for iOS"></sp=
an></span>
<div>
<div><br>
</div>
<div><br>
</div>
<div class=3D"acompli_signature">Get <a href=3D"https://aka.ms/o0ukef">Outl=
ook for iOS</a></div>
</div>
</div>
</body>
</html>

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_--



    On Saturday, February 24, 2018, 3:39:38 PM EST, qtakabg <notifications@github.com> wrote:  
 
    
   - VSCode Version: Code 1.19.0 (816be67, 2017-12-14T09:56:48.842Z)
   - OS Version: Linux x64 4.15.4-1-ARCH
   - Extensions:

| Extension | Author (truncated) | Version |
| xml | Dot | 1.9.2 |
| gc-excelviewer | Gra | 2.0.19 |
| vscode-devskim | MS- | 0.2.0 |
| path-intellisense | chr | 1.4.2 |
| regex | chr | 0.1.0 |
| vscode-faker | dee | 1.2.1 |
| jquerysnippets | don | 0.0.1 |
| gitlens | eam | 8.0.0 |
| prettier-vscode | esb | 1.1.3 |
| auto-close-tag | for | 0.5.6 |
| rest-client | hum | 0.17.0 |
| docthis | joe | 0.6.0 |
| fuzzy-definitions | jri | 0.0.3 |
| python | ms- | 2018.1.0 |
| debugger-for-chrome | msj | 4.1.0 |
| vscode-css-peek | pra | 2.1.0 |
| view-in-browser | qin | 0.0.5 |
| vscode-icons | rob | 7.20.0 |
| vscode-djaneiro | the | 1.3.0 |


Steps to Reproduce:
   
   - Create new html file with the following line in it:   
<img src="{% static "images/image-name.jpg" %}"   
alt="Image" />
   - Save the file.   
Result:   
Spaces are added between the image path and the quotes, thus breaking the link in Django routing:   
" images/image-name.jpg "   
Furthermore, the tag is formatted into one line which is not very nice for long lines.

Reproduces without extensions: Yes

**Comment by qtakabg** [comment] 2018-02-27 06:58
Sure, here are my custom settings, though I was able to reproduce it on a newly installed vscode without any custom settings on both Arch Linux and Windows:
{
    "workbench.iconTheme": "vscode-icons",
    "workbench.statusBar.visible": true,
    "workbench.activityBar.visible": true,
    "editor.fontSize": 14,
    "files.autoSave": "afterDelay",
    "editor.minimap.enabled": false,
    "terminal.integrated.fontSize": 16,
    "window.menuBarVisibility": "default",
    "workbench.panel.location": "bottom",
    "workbench.editor.tabSizing": "shrink",
    "editor.stablePeek": true,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "git.autofetch": true,
    "workbench.startupEditor": "newUntitledFile"
}

**Comment by RMacfarlane** [comment] 2018-02-27 18:26
Ok, interesting. I haven't been able to reproduce it yet. I assume when you tested with a newly installed version, it was the latest version (1.20) and without extensions?

**Comment by qtakabg** [comment] 2018-02-27 20:03
I had the chance to test on two machines tonight:
1. Windows 10 Home
- VSCode 1.20.1
- Disabled all extensions
Result:
Not reproducible

2. Arch Linux
- VSCode 1.19 (update hasn't reached it yet I guess)
- Disabled all extensions
Result:
Reproducible

It seems that extensions do affect the behavior, because last time I was able to reproduce on Windows as well. However, the extensions were enabled and there are a lot of them, I guess we all use many extensions. Unfortunately, my main environment is Linux.

**Comment by RMacfarlane** [comment] 2018-02-27 22:45
Since the behavior still happens on Alt+Shift+F with no extensions, I think this is being caused by the default HTML formatter. Can you check that it doesn't reproduce after adding `"html.format.enable": false` to your settings?

**Comment by qtakabg** [comment] 2018-03-01 19:57
Your assumption seems to be correct. Setting "html.format.enable" to "false" helps. However, it disables automatic html formatting.

**Comment by aeschli** [comment] 2018-03-26 15:38
duplicate of #46468

**Closed by aeschli** 2018-03-26 15:38 UTC
Labels: html
