### ISSUE TITLE
[Feature request] Add an option to display errors inline

### ISSUE THREAD

**Issue by nchevobbe** [Microsoft/vscode#27703] opened 2017-05-31 08:31 UTC
# Issue

At the moment, errors are underlined with a wavy red line:

<img width="1116" alt="screen shot 2017-05-31 at 09 57 57" src="https://cloud.githubusercontent.com/assets/578107/26622290/328409f4-45ea-11e7-8a62-a8ce57eca598.png">

And you have 3 ways to see what the error is : 
1. hover the line with the mouse
2. navigate the cursor to the error and hit <key>ctrl</key>+<key>k</key> and then <key>ctrl</key>+<key>i</key>
3. hit <key>F8</key> until you navigate to the errors

Those all work great but need some extra-work
1. You have to quit the keyboard
2. you have to navigate to the error, and then remember the 2 key shortcuts
3. if there are may errors, you might have to loop through a bunch of them before getting the one you're interested in

Of course you also could have the "Errors" panel open, but again, if you have many errors the one you interested in might be buried below what's visible without scrolling.

# Request

It would be nice if there was an option to display errors next to the line containing those errors, so they'll show up without any user-interaction.
Here's what it could look like : 

<img width="1354" alt="screen shot 2017-05-31 at 10 05 13" src="https://cloud.githubusercontent.com/assets/578107/26622592/356f8f16-45eb-11e7-855f-569337b2f977.png">

# Challenges 

- The line might be a long one, and the error message would then not be visible
- In case there are multiple errors on a same line, how do you display it

The errors could be displayed on the next line instead, but from what I saw inspecting the app, it might be tricky to do since the "decorators" are positioned absolutely beneath the actual line of code.

**Comment by nchevobbe** [comment] 2017-05-31 08:33
If this feature request sounds legit, I can try to work on it.

**Comment by hoovercj** [comment] 2017-05-31 08:41
Alternative approach:

Add an option that keeps all errors visible using the current "f8" behavior of showing the errors below the line. The screenshot below shows one error below the line. The configuration option could make it such that these are always visible, and multple errors will display on multiple lines.

![image](https://cloud.githubusercontent.com/assets/2957173/26623217/5012c1d8-45ed-11e7-9d0f-775c0e42af2f.png)

**Comment by nchevobbe** [comment] 2017-05-31 08:44
@hoovercj this would be great, and easier to implement I guess

**Comment by jrieken** [comment] 2017-05-31 09:02
dupe of https://github.com/Microsoft/vscode/issues/19749

**Closed by jrieken** 2017-05-31 09:02 UTC
