### ISSUE TITLE
[Settings Sync] Cannot resolve merge conflicts

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#104626] opened 2020-08-14 07:32 UTC
Issue Type: <b>Bug</b>

---

#### GIF

![sync](https://user-images.githubusercontent.com/7588612/90222488-bab53d80-de3e-11ea-9674-90b921f6371a.gif)

---

#### Steps

I'm using the stable build so this was my first attempt on the _Settings Sync_ feature.

1. I turned on _Settings Sync_ on my desktop PC. **✓**
2. I opened my laptop and turned on _Settings Sync_, and then selected "Manually merge" then I got 5 merge conflicts to resolve. **✓**
3. When I opened the third file `markdown.json` **for the first time**, I saw it was empty in the left tab (i.e. Remote tab) and there was one snippet in the right tab.
4. So I clicked "Merge" button and deleted the snippet in the right tab.
5. Then I clicked "Accept Merge" and saw an error similar to that in above GIF.
6. I could not proceed but only cancelled _Settings Sync_. Now as a result, if I try to turn on _Settings Sync_, both sides of `markdown.json` are empty and there is no way to resolve the conflict(?).

(Now both sides of `python.json` are also empty. I didn't touch it on my first attempt. But they shouldn't be empty to my memory, no matter "Local" or "Remote".)

Looks to be similar to #104622, although here it is about snippets (not keybinding) and my snippet files are not empty.

---

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
log-wrapper-for-vscode|chr|1.0.2
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
vscode-highlight|fab|1.4.1
vscode-open-in-application|fab|1.0.5
latex-workshop|Jam|8.11.1
regexp-preview|Lou|0.1.5
git-graph|mhu|1.25.0
python|ms-|2020.8.101144
vscode-pylance|ms-|2020.8.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
numbermonger|sof|0.5.0
gitmoji-vscode|Vtr|0.2.1
dictionary-completion|yzh|0.9.2
find-word-at-cursor|yzh|0.1.1
markdown-all-in-one|yzh|3.2.0

(1 theme extensions excluded)

</details>

**Comment by yzhang-gh** [comment] 2020-08-14 07:43
Tried on a different PC.

There is no conflict on `markdown.json` (not listed in the conflicts). But `python.json` is still blocking the Sync. It shows nothing on both sides (Remote and Local) while apparently at least the local file is not empty.

**Comment by yzhang-gh** [comment] 2020-09-03 15:43
Thanks.

I just managed to resolve this issue (although have seen some strange things). Here is some information.

- I checked the PC on which I turned on Settings Sync first. Everything is fine. The 3 snippets files (`{latex,markdown,python}.json`) are in `%USERHOME%/AppData/Roaming/Code/User/snippets/`
- I checked my laptop and found there is no file in the above folder, but there were 2 (`{markdown,python}.json`) in an extra folder `snippetsBackup`. (I guess it was created by the Settings Sync feature?)
- I moved the 2 files back to `snippets` and deleted `snippetsBackup` and `sync` folders in the same directory.
- Then I tried to turn on Settings Sync on my laptop (Merge Manually):
  - `latex.json` diff shows blank tabs on both sides. Clicking "merge" results in an empty "(Preview)" tab.
  - `{markdown,python}.json` diff shows correctly(?) empty on left hand side and some snippets on the right hand side. Also, clicking "merge" results in an empty "(Preview)" tab.
  - Resolved all other conflicts and turned Sync on

Except for those confusing blank tabs, the sync seems to be working now.

Hope it helps.

**Comment by sandy081** [comment] 2020-09-04 11:55
- I do not think Settings Sync feature has created `snippetsBackup` folder. Did you use different settings sync extension before?
- Are (`{latex,markdown,python}.json`) empty (no contents) on your PC?
- What happened when you used `Accept Local` action?

**Comment by yzhang-gh** [comment] 2020-09-04 13:51
> * I do not think Settings Sync feature has created `snippetsBackup` folder. Did you use different settings sync extension before?

I have used [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) by Shan Khan before but haven't performed a sync for a long time (auto sync was disabled).

> * Are (`{latex,markdown,python}.json`) empty (no contents) on your PC?
> * What happened when you used `Accept Local` action?

Well, I cannot remember all the details. But with the latest version of VSCode, I no longer have this issue and have 3 devices successfully synced now. Probably we can just close this if no one else still have this issue.

**Comment by sandy081** [comment] 2020-09-04 14:05
Ok, thanks for the info.

Will close this for now as you are not seeing this issue anymore. Please reopen it with requested info if you see it again.

**Comment by fireattack** [comment] 2020-09-23 03:27
I encountered this issue today.

My "machine A" is GitHub codespace. My "machine B" is my local computer that I'm trying to enable sync.
When go through "Merge manually", 
1. It shows both python.json as empty despite the fact my local one isn't
2. I can't even "Accept Local" (click no response).

I didn't do any workaround as mentioned in https://github.com/microsoft/vscode/issues/104626#issuecomment-686580165 because I want to preserve this status to help debug further (users shouldn't need to manually fix things anyway). I just cancelled the sync for now.

Please reopen this issue let me know what you need from me.

**Comment by sandy081** [comment] 2020-09-29 21:14
I am not able to reproduce it. I can see the local python file content. Are there any errors in the shared process console (Use command `Toggle Shared Process` or settings sync log in output view?

**Comment by fireattack** [comment] 2020-09-30 01:18
There are.

Shared process console:
```
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/Context.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/Channel.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/SamplingTelemetryProcessor.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/Sender.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/EnvelopeFactory.js.map: 
bootstrap-window.js:216 [uncaught exception]: Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\Code\clp\6c3ed5e6192fbbfa4e14c5b119c0f3c1.zh-cn'

Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\Code\clp\6c3ed5e6192fbbfa4e14c5b119c0f3c1.zh-cn'
r @ bootstrap-window.js:9
(anonymous) @ bootstrap-window.js:9
emit @ events.js:223
window.onerror @ electron/js2c/renderer_init.js:138
bootstrap-window.js:219 Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\Code\clp\6c3ed5e6192fbbfa4e14c5b119c0f3c1.zh-cn'

Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\Code\clp\6c3ed5e6192fbbfa4e14c5b119c0f3c1.zh-cn'
    at errors.ts:26
r @ bootstrap-window.js:9
(anonymous) @ bootstrap-window.js:9
emit @ events.js:223
window.onerror @ electron/js2c/renderer_init.js:138
```

Log (Shared):

```
[2020-09-29 20:15:03.236] [sharedprocess] [info] main {"machineId":"a7e9cdba9a341e33d1fd18f2b85285e770a4275dee341105ee3bcf74223988c3","windowId":2}
[2020-09-29 20:15:05.952] [sharedprocess] [info] Installing extension: ms-python.python
[2020-09-29 20:15:09.443] [sharedprocess] [info] Downloaded extension: ms-python.python c:\Users\Administrator\AppData\Roaming\Code\CachedExtensionVSIXs\ms-python.python-2020.9.112786
[2020-09-29 20:15:12.854] [sharedprocess] [info] Extracted extension to c:\Users\Administrator\.vscode\extensions\.ms-python.python-2020.9.112786: ms-python.python
[2020-09-29 20:15:12.859] [sharedprocess] [info] Renamed to c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.9.112786
[2020-09-29 20:15:12.864] [sharedprocess] [info] Installation completed. ms-python.python
[2020-09-29 20:15:12.895] [sharedprocess] [info] Extensions installed successfully: ms-python.python
[2020-09-29 20:15:43.530] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-09-29 20:16:48.886] [sharedprocess] [error] Error: Invalid Resource: vscode-userdata-sync://local/c%3A/Users/Administrator/AppData/Roaming/Code/User/sync/snippets/preview/python.json
    at p.getAcceptResult (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:496:300)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:440:690
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:441:597
    at Object.a [as createCancelablePromise] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:51:611)
    at p.updateSyncResourcePreview (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:441:513)
    at async p.accept (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:440:622)
    at async _.performAction (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:547:804)
    at async s.call (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:513:536)
[2020-09-29 20:16:49.995] [sharedprocess] [error] Error: Invalid Resource: vscode-userdata-sync://local/c%3A/Users/Administrator/AppData/Roaming/Code/User/sync/snippets/preview/python.json
    at p.getAcceptResult (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:496:300)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:440:690
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:441:597
    at Object.a [as createCancelablePromise] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:51:611)
    at p.updateSyncResourcePreview (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:441:513)
    at async p.accept (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:440:622)
    at async _.performAction (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:547:804)
    at async s.call (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:513:536)

```

Log (Setting Sync) has nothing strange.

```
[2020-09-29 20:15:03.617] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-09-29 20:15:03.617] [userDataSync] [info] Auto Sync is disabled.
[2020-09-29 20:16:04.125] [userDataSync] [info] Did reset the local sync state.

```

**Comment by sandy081** [comment] 2020-09-30 08:07
I suspect this issue is because of path case sensitivity. I do not know how to reproduce it but if you can help me providing some info it would be great.

**Comment by fireattack** [comment] 2020-09-30 08:21
Sure, let me know what you need.

By the way, the "[sharedprocess] [error] Error: Invalid Resource" error happens when I click the "accept X" button. So the issue that it doesn't be able to load my local python snippet into preview happened before that (the preview file is created at this pah but empty). My original file is at `C:\Users\Administrator\AppData\Roaming\Code\User\snippets\python.json`.

**Comment by fireattack** [comment] 2020-09-30 08:36
As for the error in console, I don't have `C:\Users\Administrator\AppData\Roaming\Code\clp\6c3ed5e6192fbbfa4e14c5b119c0f3c1.zh-cn` file. actually, I don't have any files in `\clp\` at all. Not sure why it tried to read something from there.

**Comment by sandy081** [comment] 2020-09-30 08:55
I would come up with a fix and share the build that has the fix. Let me know if you can help us in validating it?

**Comment by fireattack** [comment] 2020-09-30 08:56
Yeah I can

**Comment by sandy081** [comment] 2020-10-01 11:18
Can you please try with latest insiders and let me know if you still see the issue?

**Comment by tolgabalci** [comment] 2020-10-03 02:03
I don't have a way of reproducing this under the insiders addition, but I had the same exact issue when performing a manual merge.  However when I did a "Merge" to begin and it failed to merge due to conflicts the table of files that showed up when I continued with Manual merge already had a check box next to all the empty files, so all I had to do was fix the two files I had merge conflicts in (simple, I just took local) and it allowed me to continue with the Settings Sync.

**Comment by fireattack** [comment] 2020-10-10 06:10
> Can you please try with latest insiders and let me know if you still see the issue?

![image](https://user-images.githubusercontent.com/4130991/95647478-62449a00-0a95-11eb-8af2-892c948dfaf4.png)

Seems to be working in Insiders.

Version: 1.51.0-insider
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:54.647Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by sandy081** [comment] 2020-10-28 18:51
Thanks for confirming.

**Closed by sandy081** 2020-10-28 18:51 UTC
Labels: bug, settings-sync
