### ISSUE TITLE
certain drags show an unstyled text selection highlight over code

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#42225] opened 2018-01-26 21:47 UTC
- VSCode Version: 1.19.3 and 1.20.0-insider
- OS Version: Windows 7 and 8.1

sorry if the title sucks

Steps to Reproduce:

it's hard to explain with just words so i took a screenshot:

![screenshot](https://user-images.githubusercontent.com/35741439/35461304-fcde6d6c-02ef-11e8-9a20-37382811bf60.png)

- where a red line/arrow starts, the left/primary mouse button is pressed down and the arrow is followed using the mouse while the button is held down
- when the cursor is on a yellow part, the blue "native" text highlight is visible
- you might have to click something and try again if it doesn't work at first

if i disable these css rules using the dev tools, the bug disappears and normal selections still work normally:

https://github.com/Microsoft/vscode/blob/2e2b47a4944ad1dfc7bbc58756c91aa3188cfa04/src/vs/editor/browser/viewParts/lines/viewLines.css#L17-L26

i couldn't find a reason for adding them in the history of the file, they've been moved from another file but they were first added in a [big initial commit](https://github.com/Microsoft/vscode/commit/8f35cc4768393b25468416829e980d7550619fb1) that doesn't explain why/if they're needed

Does this issue occur when all extensions are disabled?: Yes, also with default settings

**Comment by alexandrudima** [comment] 2018-04-25 21:17
Duplicate of #44517

**Closed by alexandrudima** 2018-04-25 21:17 UTC
Labels: bug, editor-rendering
