### ISSUE TITLE
Opened pdf in VSC tab cannot be closed with shortcut CTRL+f4

### ISSUE THREAD

**Issue by nitramwin** [microsoft/vscode#108797] opened 2020-10-16 12:35 UTC
Issue Type: <b>Bug</b>

Open a PDF (although officially unsupported) in a tab of VSC and then try closing the tab with the typical close tab shortcut. This doesnt work although it works for other non pdf tabs. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.69GB free)|
|Process Argv|--crash-reporter-id 3cf169ba-2689-49fc-8c8c-7acdd2a3a07d|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
texlab|efo|2.2.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.1
mdmath|goe|2.5.1
beautify|Hoo|1.5.0
r|Iku|1.5.0
r-pack|Iku|0.0.2
latex-workshop|Jam|8.13.2
restructuredtext|lex|129.0.0
rainbow-csv|mec|1.7.1
git-graph|mhu|1.26.0
ampl|mic|0.0.3
r|Mik|0.0.15
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.0
pandocciter|not|0.7.0
vscode-bookdown|not|0.0.6
indent-rainbow|ode|7.4.0
bib|phr|0.3.0
vscode-xml|red|0.13.0
r-lsp|REd|0.1.11
luacheck|rog|1.0.0
lua|sum|0.21.3
ayu|tea|0.20.1
html-preview-vscode|tht|0.2.5
local-lua-debugger-vscode|tom|0.2.0
latex-support|tor|3.3.1
txt-syntax|xsh|0.1.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-10-27 00:58
Closing as duplicate of # #109147

**Closed by mjbvz** 2020-10-27 00:58 UTC
Labels: custom-editors, keybindings
