### ISSUE TITLE
Intellisense within log points doesn't suggest local variables

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#46739] opened 2018-03-27 18:06 UTC
Testing #45962

When typing within `{}` in a log point, the suggestions don't seem to include local variables.

![log_message_intellisense](https://user-images.githubusercontent.com/3672607/37985793-9b712946-31ae-11e8-9be9-5b5b3a666c9f.gif)

**Comment by isidorn** [comment] 2018-03-28 15:02
Good catch, but I only now saw this which is a duplicate of https://github.com/Microsoft/vscode/issues/46824

**Closed by isidorn** 2018-03-28 15:02 UTC
