### ISSUE TITLE
Word wrap algorithm behaves differently around punctuation

### ISSUE THREAD

**Issue by sheljohn** [microsoft/vscode#33366] opened 2017-08-29 09:54 UTC
Versions:

- VSCode Version: 1.15.1 (commit 41abd21afdf7424c89319ee7cb0445cc6f376959)
- OS Version: `Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017`

Steps to Reproduce:

1. Open new file.
2. Type normal text (with spaces, eg `chick en`) until word wrap is reached, **the last character on the line should be a letter [a-z], and it should be AT the word-wrap length**. That is, if the cursor is right past the last letter, the column number should be equal to `editor.wordWrapColumn`.
3. Now add a comma `,`; the comma is not wrapped, despite the fact that it is past the last column. This is great, and not necessarily unexpected to treat punctuation specially.
4. Remove the comma, and instead type `),`: now the comma is wrapped but not the parenthesis. This is unexpected; I would either expect both not to be wrapped, or else the entire word with punctuation to be wrapped.

Reproduces without extensions: Yes

---

I think that punctuation should either:

 - not be wrapped for up to 2 chars beyond `editor.wordWrapColumn` (eg to allow things like `last word).` or `last word),`); 
 - or that the entire word with punctuation should be wrapped together instead of just the punctuation (eg `word).` should be wrapped instead of just `.` presently).

It also seems that commas `,` have a special treatment with regards to word wrapping. So the simplest might be either to remove this special treatment, or include parentheses and brackets to it.

**Comment by sheljohn** [comment] 2017-09-12 14:44
@alexandrudima Any news on this side?

**Comment by Neutrino-Sunset** [comment] 2017-09-18 16:13
I'm going to tack a related issue onto this as I think both need addressing together.

With config

"editor.wordWrapColumn": 120

Enter a line of any unbroken text except make the last character at the wordWrapColumn length a comma and follow with a space then more text. E.g.

bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
 b

The bug is that a space following punctuation on the last column is displayed at the first column on the next line.

What should happen is that the space needs to be saved as part of the text stream, but it should not be displayed when at the first column position, i.e. all lines should be displayed left justified.

**Comment by amaau** [comment] 2019-10-22 16:34
bug still there, any news?

**Comment by alexandrudima** [comment] 2019-10-22 20:39
@sheljohn @amaau I can no longer reproduce this.

Here I am using the following settings:
```
"editor.wordWrapColumn": 80,
"editor.wordWrap": "wordWrapColumn",
"editor.rulers": [80],
```

That means that 80 characters should be displayed and the 81st character should wrap. So the column in the status bar should go from column 1 to column 81.

Everything appears to work normally for me:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/67330512-c258ce00-f51c-11e9-8426-6bec6a20c92a.gif)

**Comment by amaau** [comment] 2019-10-22 21:49
Issue is still there, last version of VSCode, windows 10, same settings as yours.
For some reason I can't attach a gif, "something went really wrong and we can't process that file",
so uploaded here -
https://gifyu.com/image/kVOz

**Comment by alexandrudima** [comment] 2019-10-22 22:35
@amaau I am looking at your gif but I am sorry I still don't understand, what do you think is a bug?

Can you please toggle render all whitespace.

There is one space character which either fits on the first line or does not. When it does not fit on the first line, it goes at the beginning of the next line:

whitespace character fits:
![image](https://user-images.githubusercontent.com/5047891/67340049-d3114000-f52c-11e9-8b16-d98a2b36a724.png)

typing one more letter makes the whitespace character go to the next line:

![image](https://user-images.githubusercontent.com/5047891/67340073-e58b7980-f52c-11e9-85f2-89e65647be49.png)

**Comment by amaau** [comment] 2019-10-22 22:56
@alexandrudima 
In your second picture, the whitespace at the beginning of the second line should not be visible at all, it should stay on the first line or be otherwise hidden / swallowed between the lines.
Which is what happens when there's no coma at the end of the first line.

**Comment by alexandrudima** [comment] 2019-10-23 09:58
> In your second picture, the whitespace at the beginning of the second line should not be visible at all, it should stay on the first line or be otherwise hidden / swallowed between the lines. **Which is what happens when there's no coma at the end of the first line.**

I cannot reproduce any difference between ending with a comma or a letter:
![image](https://user-images.githubusercontent.com/5047891/67381535-58780d00-f58c-11e9-9281-b0beca9d237f.png)

Are you trying on the latest VS Code version?

**Comment by amaau** [comment] 2019-10-23 10:33
I am using latest version.
In your latest picture, the first line is 1 whole word without any spaces, so it cannot break before the end of the line. 

your example:
1st line is single word, so it can't break, and space is pushed to second line. 
![2019-10-23-12-20-06](https://user-images.githubusercontent.com/25984726/67383643-d38ef280-f58f-11e9-8dda-271296375e07.png)
This is also a bug -
There should never be a situation where a line starts with a space, unless there are several spaces in a row.

Here, one character on 1st line replaced with space, line breaks, whitespace goes to end of 1st line:
![2019-10-23-12-20-41](https://user-images.githubusercontent.com/25984726/67383685-f1f4ee00-f58f-11e9-8853-536de699d892.png)

Here the last character of the aaaaaae word is replaced with a coma, now for some reason word "fits" into first line again, whitespace is pushed to second line, bug.
![2019-10-23-12-21-35](https://user-images.githubusercontent.com/25984726/67384373-5bc1c780-f591-11e9-88f3-7386b850f3dd.png)

**Comment by alexandrudima** [comment] 2019-10-25 08:47
Thanks for your patience @amaau !

Ok, here are complete steps to reproduce the difference between `,` and letters:

* create a file with the following content (those two lines differ only in the change that `,` is replaced with `s`):
```
this is a line of text, text that sits on a line
this is a line of texts text that sits on a line
```

* use the following settings:
```
   "editor.wordWrapColumn": 23,
   "editor.rulers": [23],
   "editor.wordWrap": "wordWrapColumn",
```

Observe that the wrapping computation treats the `,` different than the `s`:
![image](https://user-images.githubusercontent.com/5047891/67556533-a66b4d00-f713-11e9-9760-148210703448.png)

**Comment by amaau** [comment] 2019-10-29 12:20
thanks @alexandrudima 
That's exactly what I mean. Do you know if it's like to be resolved in the near future? It is an important feature for people that would like to use vscode for writing anything other than code.
Thanks

**Closed** 2020-01-10 09:49 UTC
Labels: editor-wrapping, feature-request

**Comment by dbaeumer** [comment] 2020-01-29 10:41
![capture](https://user-images.githubusercontent.com/1931590/73349852-3a593180-428c-11ea-86bd-e672c6b61a17.png)
