### ISSUE TITLE
[macOS] Properly handle Window Restoration during Sudden Termination (for Spaces)

### ISSUE THREAD

**Issue by ericdrobinson** [Microsoft/vscode#16991] opened 2016-12-09 17:07 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|debugger-for-chrome|msjsdiag|2.3.2|

---

### Steps to Reproduce:

1. [Create multiple Spaces](https://support.apple.com/kb/PH21872) for the current User.
2. Open Visual Studio Code on macOS (any version 10.7+).
3. Open a Folder (or new window) multiple times: once, at least, in each Space you created in Step 1.
    - Ensure you have the `window.reopenFolders` [setting](https://code.visualstudio.com/docs/editor/codebasics#_window-management) set to `all`.
4. Perform one of the following [_Sudden Termination_](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW22) actions:
    1. **Logout** of the current User. Log back into the same user.
    2. **Shut Down** the computer. Turn the computer back on.
    3. **Restart** the computer.

### Expected Results:

Visual Studio Code's windows restore to the Spaces they were in when the action in Step 4 took place.

### Actual Results:

Visual Studio Code restores all windows to the current Space (typically "Desktop 1") when the user is properly logged back in. They must be manually reassigned to the previous spaces.

### Errata:

- Compare Visual Studio Code's results with that of Apple's built-in applications: all windows of Apple-built apps correctly restore to the Space they existed in prior to the `Sudden Termination` event.
- Apple _does_ offer the ability to [**Assign apps to Spaces**](https://support.apple.com/kb/PH21872). However, this only adjusts what Space the Windows start in. If a user intentionally moves the windows to different Spaces then all Windows would recollect to _that_ space upon restart instead of the previously assigned Space (as expected). In short, this is not a solution to the problem.
- **Use Case:** A developer creates three Spaces and opens a folder in a unique Visual Studio Code window on each Space. These Spaces serve different development contexts for the developer. When restarting (say from OS update), the developer expects the windows to restore to the previously used Space.
- According to _Apple Developer Relations_, apps that wish to support this feature must "use NSWindow’s [encodeRestorableStateWithCoder:](https://developer.apple.com/reference/appkit/nsresponder/1526236-encoderestorablestatewithcoder) and [restoreStateWithCoder:](https://developer.apple.com/reference/appkit/nsresponder/1526253-restorestatewithcoder)" (those APIs are part of [NSResponder](https://developer.apple.com/reference/appkit/nsresponder)). This is also somewhat outlined [here](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26).

**Comment by bpasero** [comment] 2016-12-12 11:05
Duplicate of https://github.com/Microsoft/vscode/issues/979 (but I copied your nice description over).

**Closed by bpasero** 2016-12-12 11:05 UTC
