### ISSUE TITLE
The front part of file paths on debug console are ignored

### ISSUE THREAD

**Issue by dyong0** [Microsoft/vscode#26309] opened 2017-05-09 12:50 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.8.0-51-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.7.0|
|theme-dracula|dracula-theme|1.15.0|
|tslint|eg2|0.14.0|;

---

Steps to Reproduce:

1. Run `Start Debug`, which runs mocha tests and prints test results with file paths on `DEBUG CONSOLE`
![screenshot from 2017-05-09 21-31-48](https://cloud.githubusercontent.com/assets/7734590/25851206/d258171e-34ff-11e7-80d4-0645ef99fc1e.png)
2. Click a file path on `DEBUG CONSOLE`
![screenshot from 2017-05-09 21-40-12](https://cloud.githubusercontent.com/assets/7734590/25851269/1b3272fe-3500-11e7-9bf4-6d2ee6377f1b.png)

---

I think that the parser should search words backward after detecting a file path in debug console, so that it doesn't ignore the front part of relative paths. Currently the parser seems to only look forward when searching using regular expressions.

**Comment by isidorn** [comment] 2017-05-09 13:38
I think it is fine when clicking on a false positive that it shows up with an error.
However what I do not understand is why our link detector does not detect `src/` as part of the link. Thus forwarding to @michelkaporin

**Comment by michelkaporin** [comment] 2017-05-09 14:14
This is a duplicate of #15760, and has been fixed in #24451.

**Closed by michelkaporin** 2017-05-09 14:14 UTC
Labels: bug
