### ISSUE TITLE
[C/C++] syntax highlight after calling macro without semicolon

### ISSUE THREAD

**Issue by bumbar1** [Microsoft/vscode#15457] opened 2016-11-14 11:29 UTC
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a macro that doesn't / can't end with a semicolon
2. Next line after calling said macro won't be syntactically highlighted

Example:
```
#define BEGIN_NAMESPACE(name) namespace name {

BEGIN_NAMESPACE(test)
class Test {}; // won't be colored, regardless of whitespace (newlines) in between
```

**Comment by aeschli** [comment] 2016-11-23 21:38
duplicate of https://github.com/atom/language-c/issues/173

**Closed by aeschli** 2016-11-23 21:38 UTC
