### ISSUE TITLE
Extension Host is now responsive. 

### ISSUE THREAD

**Issue by edithMadisson** [Microsoft/vscode#60380] opened 2018-10-09 19:14 UTC
- Extension Name: emmet
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by mjbvz** [comment] 2018-10-09 22:43
Duplicate of #60379

**Closed by mjbvz** 2018-10-09 22:43 UTC
Labels: extensions

**Comment by egamma** [comment] 2018-10-10 07:58
pls see https://github.com/Microsoft/vscode/issues/60318
