### ISSUE TITLE
Scrolling hover text more than there is text scrolls the editor

### ISSUE THREAD

**Issue by hasezoey** [microsoft/vscode#113586] opened 2020-12-30 12:30 UTC
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|31.37GB (4.34GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id fb1ec7a8-4c43-4d80-892c-5c665893c507|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

---

Steps to Reproduce:

1. open editor
2. write some wrong code (tested using rust & typescript)
3. try to hover over an wrong element (with lengthy documentation)
4. try to scroll (with middle mouse / touchpad) up or down past the limit of the scrollbar of the hover

Does this issue occur when all extensions are disabled?: Yes

---

For about 1 to 3 versions the hover text (where problems with specific lines are shown) is scroll (up or down) more than the in-hover scroll bar allows, scrolls the editor behind it
-> this is an problem when only having an touchpad (like on an laptop) or just fast-scrolling to see the problem after an lengthy documentation

does this have something to do with the hover not being focused anymore? (if i manually click on the hover to focus it, the problem still exists)

Edit: Video Showcase of the problem https://www.youtube.com/watch?v=bGQ66j7Ay-s

**Comment by hasezoey** [comment] 2020-12-30 12:31
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

none of those are related

**Comment by alexdima** [comment] 2020-12-30 14:11
Duplicate of #112373

**Closed by alexdima** 2020-12-30 14:11 UTC

**Comment by hasezoey** [comment] 2020-12-30 14:58
@alexdima thanks, i tried searching for duplicates, but didnt know how to describe it (and so found no other issues)
