### ISSUE TITLE
Shift + Click does not create a selection

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119605] opened 2021-03-23 14:06 UTC
Testing #119118

* on macOS
* click on a markdown cell
* shift+click on another markdown cell
* I would have expected this to create a selection, like it does in Finder.
* I think right now I must use the keyboard to do multiple selections

**Comment by rebornix** [comment] 2021-03-24 00:57
Tested that it doesn't reproduce with builtin markdown with `"notebook.experimental.useMarkdownRenderer": false` in settings.

**Comment by mjbvz** [comment] 2021-03-25 02:42
Duplicate of #119515 I believe

**Closed by mjbvz** 2021-03-25 02:42 UTC
Labels: bug, notebook-markdown
