### ISSUE TITLE
Markdown Preview does not split to side

### ISSUE THREAD

**Issue by cbluth** [microsoft/vscode#88143] opened 2020-01-06 15:35 UTC
- VSCode Version:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic
```
- OS Version: ubuntu 19.10

Context:
- I want to edit a markdown file **AND** see the preview at the same time in a split pane to the right.

Steps to Reproduce:
1. open a markdown formatted file
2. use CTRL+SHIFT+V to show the markdown preview
3. right-click preview tab, and use "Split Right"
4. the result is a funky empty pane on the right

![image](https://user-images.githubusercontent.com/6709636/71828309-6543d180-30a2-11ea-8c5d-cc80c4e9d956.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-01-06 23:53
This is currently expected because markdown previews are implemented using web views based editors (which do not support splitting)

Marking as a feature request

**Comment by mjbvz** [comment] 2021-05-06 01:18
Duplicate of #80038

**Closed by mjbvz** 2021-05-06 01:18 UTC
Labels: feature-request, markdown
