### ISSUE TITLE
Undo/redo does not play well with IMEs

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#9389] opened 2016-07-16 16:52 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10 Build 14388

Steps to Reproduce:
1. Switch to some IME, in my case Sogou Chinese keyboard or Microsoft Chinese keyboard.
2. Type something and undo/redo.

It takes many unnecessary undo/redo operations before I can get to the point of document I want, even if some of them does not seem to change the content of document at all.

**Comment by alexandrudima** [comment] 2016-08-09 09:20
Related #9675

**Comment by rebornix** [comment] 2017-04-19 17:57
This issue is obsolete and I can't reproduce any more. It should be fixed via https://github.com/Microsoft/vscode/commit/374c4e3e995dfa984a418f161bef3a908cb61e42 already.

**Closed by rebornix** 2017-04-19 17:57 UTC
Labels: bug
