### ISSUE TITLE
allow explorer to float without being attached to the side bar 

### ISSUE THREAD

**Issue by octopusoctopusoctopus** [microsoft/vscode#225070] opened 2024-08-07 16:37 UTC
Currently the explorer is tied to the side bar. It would be great to be able to make it float as a separate window and allow it to be a tab in the editor.

**Comment by gjsjohnmurray** [comment] 2024-08-07 17:13
/duplicate of https://github.com/microsoft/vscode/issues/193267#issuecomment-2247699028

**Closed** 2024-08-07 17:14 UTC
Labels: *duplicate, triage-needed
