### ISSUE TITLE
Add clickable colour swatches that show the colour picker when clicked on

### ISSUE THREAD

**Issue by Brandon-Gui123** [microsoft/vscode#75136] opened 2019-06-08 14:52 UTC
Typically to open the colour picker in VS Code when doing CSS, you simply hover your cursor over the colour value and let it show up. However, if you hover or click on the colour swatch to the left of the colour value, it will do nothing other than positioning the cursor next to it.

In Visual Studio Code's Interactive Playground, the CSS tip below the first small editor window mentioned: "These swatches also act as colour pickers that allow you to easily change a colour value." However, the swatches do nothing other than to show colour. If that is the case, wouldn't it be better to say that "these swatches preview colour..."?

So, I would suggest allowing the colour picker to be shown when clicking the colour swatches (also would suggest using the "Link Select" (or the hand) cursor to indicate something clickable).
The same colour picker can still be shown when hovering above the colour value, since hovering over stuff should show quick info.

**Comment by rebornix** [comment] 2019-10-24 00:10
/duplicate of https://github.com/microsoft/vscode/issues/40634

**Closed** 2019-10-24 00:10 UTC
Labels: *duplicate, editor-color-picker, feature-request
