### ISSUE TITLE
The terminal can't input Chinese, it can only input English. Before, it was OK. It has been using the vscode terminal to submit GIT

### ISSUE THREAD

**Issue by git-guining** [microsoft/vscode#116069] opened 2021-02-08 02:40 UTC
版本: 1.53.0 (user setup)
提交: 8490d3dde47c57ba65ec40dd192d014fd2113496
日期: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

The terminal can't input Chinese, it can only input English. Before, it was OK. It has been using the vscode terminal to submit GIT

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment] 2021-02-08 05:36
Duplicate of #115814

**Comment by Lyun92** [comment] 2021-02-09 07:30
SAME Q

**Closed** 2021-02-09 08:39 UTC
Labels: *duplicate, *english-please, needs more info, translation-required-chinese-simplified
