### ISSUE TITLE
many, many rg processes

### ISSUE THREAD

**Issue by fusengine** [Microsoft/vscode#63131] opened 2018-11-14 14:20 UTC
when starts vscode ca free my iMac pro
I watch the process and rg is duplicate 20 times.

- VSCode Version: latest
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. I start vscode
2. freezes iMac pro until forced restart

Does this issue occur when all extensions are disabled?: No

**Comment by filipesilva** [comment] 2018-11-14 14:58
This issue seems to be a duplicate of https://github.com/Microsoft/vscode/issues/62970. A suggested workaround is to always clear notifications.

**Comment by filipesilva** [comment] 2018-11-14 15:56
Sorry about that @jrieken, I was looking for the hanging issue and got tunnel vision. My bad.

**Comment by roblourens** [comment] 2018-11-14 16:02
Are you opening a workspace with many folders?

**Comment by fusengine** [comment] 2018-11-15 09:09
No juste project folder

**Comment by fusengine** [comment] 2018-11-15 09:09
You dont test that?

**Comment by roblourens** [comment] 2018-11-15 18:41
Does this happen if you start with `--disable-extensions`?

**Comment by gmainguet** [comment] 2018-11-22 15:05
Same here. I have 7 folders full of C++ files (100k+) and rg just hangs, probably because of the number of rg processes (launched with the same cmd line it appears) - and this with the --disable-extensions option.
It happens when I trigger my own tasks (that basically call some powershell scripts). VSCode/rg eats up the cpu before even launching my tasks...
Hope it'll help you guys.

**Comment by roblourens** [comment] 2018-11-26 23:01
@gmainguet can you explain exactly what you are doing, and what you see? Does this happen when you do file search/text search? What is the command line of those processes?

Does the window stop responding? Are the rg processes using high CPU?

What OS?

**Comment by gmainguet** [comment] 2018-11-27 13:05
Hi Rob,
Thanks for following up.
Basically, whenever i trigger the "quick open" window (Ctrl+P), there's the rg process that kicks in and uses high CPU, even if i don't type anything in the search box. I'm assuming it scans all files in the workspace (its command line is: "%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/tsconfig*.json -g !**/node_modules/** -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !/.hg* -g !**/.cquery -g !**/out -g !**/.vscode -g !**/*.xml -g !**/*.scn -g !**/*.xsd -g !**/*.db --no-ignore --follow --no-config
So this command line is the same for any rg process that cause problems*

In my workspace setup, I have custom tasks. Some powershell scripts are therefore called after I trigger these tasks (either from quick open window or keyboard shortcut e.g. Ctrl+Shift+B). So whenever I do this, there are 2 rg processes launched (and in vs code's status bar, it says "Fetching build tasks..."). Those 2 processes eats up all CPU. After they terminate, the powershell script is called. And indeed, if I look for a file in the meantime, a 3rd rg process is launched and my whole machine becomes veeery slow.

I'm on an up-to-date Windows 10.

Should there not be some sort of caching of the rg results rather than launching the same process all the time?

*: I don't refer to the rg process used during the global search (Ctrl+Shift+F) as obviously this one is expected to intensively use the CPU

**Comment by roblourens** [comment] 2018-11-29 22:20
Can you try downloading the Insiders' build and tell me whether it happens there? I fixed an issue that may be related. https://code.visualstudio.com/insiders

**Closed** 2018-11-30 17:03 UTC
Labels: needs more info
