### ISSUE TITLE
Bad display

### ISSUE THREAD

**Issue by Pierre-Thibault** [microsoft/vscode#112623] opened 2020-12-16 04:26 UTC
Issue Type: <b>Bug</b>

I am on the page Extension: Remote - Containers. When I scroll the text, the text scroll but the original text stays in place so it creates like phantom text effect.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 25259f0c-709f-4d1c-9241-d97f2c0d0a3d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment] 2020-12-16 08:29
@Pierre-Thibault Could you attach a screenshot?

**Comment by Pierre-Thibault** [comment] 2020-12-16 13:55
I don't know how to attach an image. And I am also unable to reproduce the bug.

**Comment by mjbvz** [comment] 2020-12-16 18:11
Seems like a duplicate of #107104 to me

Let us know if you see this again in VS Code 1.52+

**Closed by mjbvz** 2020-12-16 18:11 UTC

**Comment by Pierre-Thibault** [comment] 2020-12-16 18:20
Maybe it is related to the fact that I moved the window from one display to another having a different DPI.
