### ISSUE TITLE
Comments API: highlight range associated to a comment

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#127464] opened 2021-06-29 13:22 UTC
When creating a [CommentThread](https://code.visualstudio.com/api/references/vscode-api#CommentThread), we need to specify a range:

> The range the comment thread is located within the document. The thread icon will be shown at the first line of the range.

However, the range is not shown to the end-user. So it can be difficult to understand what the comment refers to exactly.
Have you considered highlighting the corresponding text range in the editor? In my experience, the best would be to highlight the range only when the comment thread is selected (or on mouse hover).

It could be enough to expose events in the API: when a comment gets expanded/collapsed, when a comment is selected/unselected (and let the extension developer do the highlighting).

**Comment by alexr00** [comment] 2022-06-14 14:11
Duplicate of https://github.com/microsoft/vscode/issues/146510, which is already completed. I missed this issue when I created https://github.com/microsoft/vscode/issues/146510.

**Closed by alexr00** 2022-06-14 14:11 UTC
Labels: feature-request, comments
