### ISSUE TITLE
cursor keys not working for filtering in File Explorer

### ISSUE THREAD

**Issue by alexlamsl** [microsoft/vscode#115922] opened 2021-02-05 19:41 UTC
Issue Type: <b>Bug</b>

https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree

Before the latest update, after typing in File Explorer, the tree will scroll to the first match, and up/down key will jump between matches.

With the latest version, none of the above would happen.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz (12 x 3602)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.94GB (58.64GB free)|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment] 2021-02-05 21:37
Are you sure that focus is on an item in the tree when you start typing?

**Comment by alexlamsl** [comment] 2021-02-05 21:46
The brown filter text box appears and displays what I'm typing the same way as before, so yes I am pretty sure the focus is correct.

The only thing missing is the scrolling and the subsequent ability to navigate with arrow keys on the keyboard in the latest version.

**Comment by alexlamsl** [comment] 2021-02-05 21:52
To clarify, the "Filter on Type" is off, i.e. files items won't disappear while I type, merely highlighting the matching items and allowing me to jump between them using up/down keys.

And that is what works previously but not so in the latest version.

**Comment by gjsjohnmurray** [comment] 2021-02-05 21:57
/confirm

Thanks for the additional information. One of the dev team now needs to investigate when the regression occurred.

**Comment by jeanp413** [comment] 2021-02-07 00:04
This is a regression from 37a4b96ae1820d21d215b460006e0baab471d6cc where the `FuzzyScore.isDefault` wasn't updated.
Created a PR #116005 fixing it

**Comment by isidorn** [comment] 2021-02-08 09:00
@jeanp413 thanks a lot for fixing!
Assigning this one to @jrieken since his commit caused the regression it seems

**Comment by jrieken** [comment] 2021-02-08 09:11
@isidorn your call whether this is severe enough to be a recovery candidate or not

**Closed** 2021-02-08 09:27 UTC
Labels: confirmed, new release

**Comment by isidorn** [comment] 2021-02-08 12:59
@jrieken I think it is fine not to do this as part of recovery, since I think most users are not aware of this feature (it is a bit hidden).
Having a fix in insiders is great, so if somebody is reliying on this behavior he or she can switch to insiders.
Thus assigning to February milestone.

**Comment by gjsjohnmurray** [comment] 2021-02-09 04:29
@isidorn #116162 just came in from another user affected by this regression. I think the fix should go into the upcoming recovery release.

**Comment by isidorn** [comment] 2021-02-09 08:36
@gjsjohnmurray thanks for letting us know. I try to be very strict when it comes to choosing what goes in the recovery release - I usually only pick regressions in highly used features, data loss or big ux glitches. Since this is none of those I still prefer to not ship it as part of the recovery.

**Comment by Defcon0** [comment] 2021-02-09 09:56
I'd appreciate if it would be fixed asap since it's very annoying that it doesn't work :-) If you don't prioritize it very high, I understand that though ;-)
