### ISSUE TITLE
Hot Save Restores Only File Content

### ISSUE THREAD

**Issue by fisenkodv** [Microsoft/vscode#17402] opened 2016-12-16 16:37 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|xml|DotJoshJohnson|1.6.0|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|vs-code-xml-format|fabianlauer|0.1.4|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|1.0.2|
|mssql|ms-mssql|0.1.5|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|typescript-javascript-grammar|ms-vscode|0.0.12|
|annotator|ryu1kn|0.10.1|
|Spell|seanmcbreen|0.9.1|
|code-settings-sync|Shan|2.3.8|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:
Note: Hot save is enabled

1. Create a new file
2. Set language
3. Close VS Code
4. Open VS Code
Expected: VS Code hot save should restore not only file content, selected language as well
Actual: VS Code restores only file content

**Comment by kieferrm** [comment] 2016-12-16 22:08
Duplicate of #17319.

**Closed by kieferrm** 2016-12-16 22:08 UTC
