### ISSUE TITLE
Column selection has unexpected behavior when I type to replace selection

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#4229] opened 2016-03-15 07:06 UTC
#4092
- VSCode Version: 10.12 Alpha
- OS Version: Mac

Steps to Reproduce:

1. Select multiple lines of HTML with column select so that last character of each line of your selection ends with the a `<`
2. Type a `<` to replace the selection with this character
3. Note that the selection is not merely replaced with `<`, but unexpectedly it leaves in spaces and adds an extra `<` at the end of the selection, changing the last `<` to a `<>`
4. This actually also happens regardless if the `<` is the last character (as long as it's in the selection somewhere), and it also happens if a `>` is in the selection.

This does not happen with unrelated characters to the last character in the selection.
![broken rectangle select](https://cloud.githubusercontent.com/assets/11839736/13770009/550bae74-ea41-11e5-965b-bb8c844d5d6c.gif)

**Comment by joaomoreno** [comment] 2016-03-15 08:54
When selecting text and typing <kbd>&lt;</kbd> in HTML, the selected `text` will become `<text>`.

Not relevant to column selection. Certainly not for March.

**Comment by joaomoreno** [comment] 2016-07-06 09:53
Closing as designed, due to brackets.

**Closed by joaomoreno** 2016-07-06 09:53 UTC
Labels: brackets, bug
