### ISSUE TITLE
Visual Studio Code won't save any file

### ISSUE THREAD

**Issue by insight47** [Microsoft/vscode#59431] opened 2018-09-26 05:36 UTC
Issue Type: <b>Bug</b>

Working with Visual Studio Code 1.27.2 on a Mac OS High Sierra 10.13.6.

For the last 30 minutes, I've been unable to save any file in VSC.

If I reboot, the unsaved file has persisted in VSC, and I can save that file.

However, if I open a different file and edit that file, the symptom reappears, and a reboot will be required.

I've not installed any VSC plugins, extra apps, or system updates since yesterday when VSC was working fine.

Help appreciated.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (3.69GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_49164|
|Screen Reader|no|
|VM|40%|

</details>Extensions: none

**Comment by bpasero** [comment] 2018-09-26 05:46
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment] 2018-09-27 05:45
@insight47 it should work if you do this:

![image](https://user-images.githubusercontent.com/900690/46125411-40b74380-c229-11e8-96f2-57c19df4cbf0.png)

**Comment by insight47** [comment] 2018-09-27 05:58
Thanks again. Where do I type >install in ? I don't see a field to type that into.

**Comment by insight47** [comment] 2018-09-27 06:29
That's great, thanks Dick.

@bpasero I receive the following when running "code --verbose" in the Mac terminal:

[main 14:28:38] Sending env to running instance...
[main 14:28:38] Sent env to running instance. Terminating...
[main 14:28:38] Lifecycle#kill()

**Comment by DickvdBrink** [comment] 2018-09-27 07:55
And when you have VSCode open and you open the developer tools?
Help -> Toggle Developer tools
Switch to the "Console" tab
When you have the issue, do you see any weird output?

**Comment by insight47** [comment] 2018-09-27 08:44
Hi @DickvdBrink, yes in developer tools console, I see:

INFO no standard startup: not just one text editor /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276

[Extension Host] Git installation not found.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:291

[node.js fs] fdatasync is now disabled for this session because it failed:  Error: EBADF: bad file descriptor, fdatasync
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:291

**Comment by bpasero** [comment] 2018-09-27 08:52
@insight47 interesting, so the error seems to be this: `EBADF: bad file descriptor, fdatasync`

Is there anything special about your environment? Is there a network drive involved maybe?

**Comment by insight47** [comment] 2018-09-28 01:53
Hi @bpasero yes there is a network drive involved. 

The folder I am working with is saved on the network drive.

There is no problem opening files though, and I have read/write access on the network drive.

**Comment by bpasero** [comment] 2018-09-28 04:37
@insight47 would you be willing to conduct a small experiment and install node.js (8.x) on your system to run some code to test if you can save with node.js (that is the library VSCode is using)?

**Comment by insight47** [comment] 2018-09-28 04:40
Yes, that's fine @bpasero

**Comment by bpasero** [comment] 2018-09-28 04:46
@insight47 cool, so install node.js from [here](https://nodejs.org/dist/v8.12.0/node-v8.12.0.pkg), then:
* create a text file on that network drive so that you can write to it and remember the path
* open a terminal
* run `node`
* type `fs.writeFileSync(<pathToFile>, "Hello World")`

Does that work or produce errors?

**Comment by insight47** [comment] 2018-09-28 05:00
Hi @bpasero, I receive "undefined".

> fs.writeFileSync("/Volumes/DESIGN WIP/Steve's WIP @ 6.8.18/test.txt", "Hello World")
undefined

**Comment by bpasero** [comment] 2018-09-28 05:02
@insight47 and did the contents of the file change, can you check?

**Comment by insight47** [comment] 2018-09-28 05:03
Yes they did @bpasero

**Comment by bpasero** [comment] 2018-09-28 05:12
Weird, so it seems like it is possible to save, just not with that VSCode version.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by insight47** [comment] 2018-09-28 05:16
Hi @bpasero , the nightly build has the same problem. Cheers.

**Comment by bpasero** [comment] 2018-09-28 09:06
@insight47 ok need some more things to try, can you:
* open vscode
* open the console (F12 > Toggle Developer Tools)
* open a file from that remote disk
* save it by writing some content to it
* I would now expect you to see the error console
* open the file with another window to see if your changes have been written to it
* save it again
* I would not expect to see another error in the console

**Comment by insight47** [comment] 2018-10-01 01:16
Hi @bpasero , I was able to open the remote text file, edit it, and save it without trouble, and with no console errors.

I followed the same process with a CSS file, and received the following in the development console:

> extfs.ts:453 [node.js fs] fdatasync is now disabled for this session because it failed:  Error: EBADF: bad file

**Comment by insight47** [comment] 2018-10-01 01:18
If I open the same file in Dreamweaver, make a change, and save it, I receive "access denied".

If I try to save it a second time, it saves okay.

**Comment by bpasero** [comment] 2018-10-01 05:14
@insight47 then it seems like this is something VSCode cannot fix if other tools have the same issue. I suggest you check the file permissions. I will close this issue.

**Closed by bpasero** 2018-10-01 05:14 UTC
Labels: needs more info

**Comment by insight47** [comment] 2018-10-01 05:18
@bpasero if the file permissions were not correct, I wouldn't be able to save the file on the 2nd attempt. I've checked the same file again, and there is no file permission issue.
