### ISSUE TITLE
⌘-key combos no longer work with alternate keyboard layout (eg Dvorak)

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/vscode#4619] opened 2016-03-23 16:10 UTC
- VSCode Version: 0.10.11 (f291f4ad600767626b24a4b15816b04bee9a3049)
- OS Version: OSX 10.11.3

Steps to Reproduce:
1. In System Preferences -> Keyboard, switch to something other than US english
2. Try to change zoom level with ⌘-+ or open settings file with ⌘-,

In earlier release of VSCode, this worked. Did you switch from reading OS-mapped keypress to raw scancodes for input? Maybe a Chromium or Electron bug?

**Comment by mathiasvr** [comment] 2016-06-28 00:23
Probably duplicate of #1492.

**Comment by alexandrudima** [comment] 2017-03-24 10:05
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24288943/8f2ce4dc-107f-11e7-8f48-162d2ea3a0aa.png)

![screen shot 2017-03-24 at 11 02 42](https://cloud.githubusercontent.com/assets/5047891/24289412/7ef1cee6-1081-11e7-87a5-d45f2466a962.png)
![screen shot 2017-03-24 at 11 04 27](https://cloud.githubusercontent.com/assets/5047891/24289466/ad1ae9d8-1081-11e7-9ab5-538c740d8373.png)

I have validated that the shortcuts for zooming and opening user settings work as advertised (using the OSX Keyboard Viewer)

**Closed by alexandrudima** 2017-03-24 10:05 UTC
Labels: bug, keybindings, keyboard-layout, mac
