### ISSUE TITLE
Search editor go to doesn't work

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#198243] opened 2023-11-14 20:03 UTC
Type: <b>Bug</b>

```
ERR Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
    at new h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:4419)
    at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:5935)
    at x (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/search-result/dist/extension.js:1:4597)
    at Object.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/search-result/dist/extension.js:1:2860)
    at u.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:41177)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:66963
    at be.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:65353)
    at be.$provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:66952)
    at n.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10836)
    at n.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10602)
    at n.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9647)
    at n.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
    at h.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
    at c.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14047)
    at h.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7918)
    at c.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14047)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6198)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

```
mainThreadExtensionService.ts:81 [vscode.search-result]Illegal argument: line must be non-negative
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
```

```
 ERR Illegal value for `line`: Error: Illegal value for `line`
    at p.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:961)
    at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:90)
    at M0.provideGenerateUsingCopilotCodeAction (/Users/svipas/.vscode/extensions/github.copilot-chat-0.10.1/dist/extension.js:1261:1912)
    at M0.provideCodeActions (/Users/svipas/.vscode/extensions/github.copilot-chat-0.10.1/dist/extension.js:1261:1717)
    at z.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:43865)
```

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:57.054Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|19, 10, 6|
|Memory (System)|32.00GB (4.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.1
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
copilot|Git|1.135.0
copilot-chat|Git|0.10.1
vscode-graphql|Gra|0.8.19
vscode-graphql-syntax|Gra|1.2.2
symbols|mig|0.0.15
vscode-react-native|msj|1.12.1
vscode-thunder-client|ran|2.15.3
vscode-fileutils|sle|3.10.3
vim|vsc|1.26.2
quokka-vscode|Wal|1.0.578

(1 theme extensions excluded)

</details>

**Comment by svipas** [comment] 2023-11-14 20:05
Very easy to repro, reload window, open search editor, search for something, you will see duplicate lines and it wouldn't work if you click on any line to jump.

<img width="595" alt="image" src="https://github.com/microsoft/vscode/assets/10441177/e5fd8221-3263-4fea-96a6-5eae3560627c">

**Comment by andreamah** [comment] 2023-11-17 19:43
duplicate of https://github.com/microsoft/vscode/issues/192113

**Closed by andreamah** 2023-11-17 19:43 UTC
