### ISSUE TITLE
Changing case of folder breaks automatic import addition and symbol renaming

### ISSUE THREAD

**Issue by richardpenny** [microsoft/vscode#71735] opened 2019-04-04 18:47 UTC
Issue Type: <b>Bug</b>

1) Rename a folder, changing only the case - e.g. "app" becomes "App"

2) In a file within the renamed folder, try an auto module import using intellisense or an F2 symbol rename. Another copy of the same file with the casing as the original folder is opened to take the new import / renamed symbol.

3) Auto formatting the edited file then appears broken and sometimes cuts off the start of some lines. Errors remain underlined, even after correction, and are only reset on closing and re-opening the file (as if it is referring to the version in the old-cased folder)

This is reproducible with all extensions disabled.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (3.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
tt-processor|ais|0.8.0
xml|Dot|2.4.0
vsc-material-theme|Equ|2.8.2
gc-excelviewer|Gra|2.1.29
rest-client|hum|0.21.2
classic-asp|ili|0.0.4
code-beautifier|mic|2.2.1
vscode-html-format|moh|0.0.3
vscode-less|mrm|0.6.3
csharp|ms-|1.18.0
debugger-for-chrome|msj|4.11.3
better-less|rad|0.5.0
html-to-jsx|ria|0.0.1
imba|scr|0.4.0
t4-support|zbe|0.4.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-09-26 23:40
Duplicate of #71990

**Closed by mjbvz** 2019-09-26 23:40 UTC
