### ISSUE TITLE
"Unreachable code" after JS IIFE

### ISSUE THREAD

**Issue by fnoot** [microsoft/vscode#92311] opened 2020-03-10 04:33 UTC
Issue Type: <b>Bug</b>

After today's update Code is reporting all code after an IIFE that returns within try and catch blocks as unreachable.

Demonstration:

```
const asdf = (() => {
	try {
		// do stuff
		return 1;
	} catch (e) {
		return 0;
	}
})(); // everything after this line is "unreachable"

let a = 1;
let b = 2;
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-40-generic

**Comment by IllusionMH** [comment] 2020-03-10 13:49
/duplicate of https://github.com/microsoft/TypeScript/issues/36828

**Closed** 2020-03-10 13:50 UTC
Labels: *duplicate, new release

**Comment by IllusionMH** [comment] 2020-03-10 13:58
In meantime you can use nightly builds of TS where this problem was resolved.
Easiest way - [JavaScript and TypeScript Nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
