### ISSUE TITLE
Quick fix for eslint(@typescript-eslint/explicit-function-return-type) has no code actions

### ISSUE THREAD

**Issue by stevenfowler16** [microsoft/vscode#78528] opened 2019-08-05 20:27 UTC
Not sure if I'm supposed to drop this in Typescript, Typescript-Eslint or here so I'm going to start with here and let me know if I need to move the issue. 

- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Set the rule for `"@typescript-eslint/explicit-function-return-type": "error"`
2. Create a function without an explicit return type in a .ts file
3. Try a quick fix -no code action available
4. Typescript knows what the return type of this function is even if it isn't explicitly defined. A quick fix should be able to place the return type for the function. 

Does this issue occur when all extensions are disabled?: Yes/No
No eslint needs to be running for this to occur.

**Comment by IllusionMH** [comment] 2019-08-06 09:08
In this case quick fixes should be provided by extension.

Could you check if this one is duplicate of https://github.com/microsoft/vscode-eslint/issues/609 in ESLint extension for VS Code.

**Comment by stevenfowler16** [comment] 2019-08-06 11:57
So I went and added in the line from the referenced issue but these are the options that are now displayed on quick fix 
![image](https://user-images.githubusercontent.com/12255820/62537833-68027800-b81f-11e9-8a6f-31b54000bec2.png)
None of which actually fix the problem. 

If I hover over the function name you can see that the editor knows what the return type is 
![image](https://user-images.githubusercontent.com/12255820/62537965-ad26aa00-b81f-11e9-9537-370b64409b13.png)
and it would be great if eslint could quick fix this and put the return type automatically with this rule enabled.

**Comment by IllusionMH** [comment] 2019-08-06 13:50
Are you sure that there is fix for this rule then? Fixes should be provided by rules.
In this case I can't find any code that should fix this lint error: [explicit-function-return-type.ts](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/explicit-function-return-type.ts)

Probably is isn't implemented. Have you tried to use CLI with `--fix` flag and see if it fixes problem?

Looks like developer should specify expected type so TS will perform check if function return type is correct. Lets imagine the function should only return strings, but developer forgot `return` statement in one of conditional blocks. In this case auto-fix will add type `string | undefined`, but this was't initial function intent. It is dangerous to add return type blindly and might lead to unexpected consequences.

So if auto-fix does't work in CLI all further conversation should be in repo with rule.

**Comment by octref** [comment] 2019-08-06 16:14
You should open issues in here https://github.com/Microsoft/vscode-typescript-tslint-plugin or https://github.com/Microsoft/vscode-tslint, depending on which ext you are using.

**Closed by octref** 2019-08-06 16:14 UTC
