### ISSUE TITLE
Notebook: clicking on a problem does not open notebook

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96443] opened 2020-04-28 16:18 UTC
Refs: #91987

I clicked on a problem and was seeing the actual text document of the cell, not the cell in the notebook itself:

![Screenshot 2020-04-28 at 18 18 27](https://user-images.githubusercontent.com/900690/80511663-b0992d00-897c-11ea-90ef-4b24298f765d.png)

**Comment by jrieken** [comment] 2020-04-29 06:34
Something is broken, @weinand report a similar issue...

**Comment by jrieken** [comment] 2020-04-29 06:52
/duplicate of https://github.com/microsoft/vscode/issues/96439

**Closed** 2020-04-29 06:53 UTC
Labels: *duplicate, bug, notebook
