### ISSUE TITLE
Intellisense suggestions are awful. Unintuitive ordering, poor completions, and tons of irrelevant snippets.

### ISSUE THREAD

**Issue by zakdances** [Microsoft/vscode#17796] opened 2016-12-24 11:41 UTC
- VSCode Version:
1.8.1

- OS Version:
MacOS Sierra

Steps to Reproduce:

I've been frustrated with VSCode's suggestions for a while now, but I've been assuming it was my own ignorance of the feature. After reading [the docs](https://code.visualstudio.com/docs/editor/intellisense), however, I still don't understand why my suggestions are so awful.

For example, in my TypeScript files I have MANY instances of the word `this` but when I type `t` the highlighted suggestion is `to` despite the fact that `to` is used absolutely nowhere in my file. I have many instances of `console.log` but I have to type `conso` to even get a `console` suggestion and even then it NEVER offers the appropriate `console.log` as a snippet. When I type `log` I get a `log()` function snippet despite no usage of that function by itself.

I type `c` and the highlighted suggestion is `col` for no apparent reason. Again, I have zero instances of `col`. If I type `con` why is stuff like `ConstrainDOMString` (which I don't use) prioritized before `console.log`?

I type `a` and I see obscure terms like `AssignedNodesOptions` but no `Array`! I have to scroll the suggestion list to see `Array`.

You're probably getting the picture now. There's so many irrelevant completions and snippets that popup that I often just manually type my variable names. Intellisense feels broken like it's not intelligently doing anything but a simply context-free dictionary lookup. Sublime Text 3 had better "intellisense".

Here's a simplified example of this issue:
<img width="902" alt="no intellissnse" src="https://cloud.githubusercontent.com/assets/1066961/21466756/990fbdca-c99a-11e6-942e-193087e10873.png">

`col` is NOT an intelligent suggestion in that context.

**Comment by kumarharsh** [comment] 2016-12-29 08:10
While using Flow, many times, the intellisense dropdown has random words<sup>1</sup> focussed instead of types, even though the types and function names come on the top of the list, the focussed word is somewhere in the middle of the list, and almost never right. I end up typing the whole word 90% of the time.

![image](https://cloud.githubusercontent.com/assets/760112/21539370/5f3f0a02-cdcc-11e6-9543-6c0010f43a82.png)

---

<sup>1</sup>*words*: denotes words in code which are neither types nor literals, just strings

**Comment by waderyan** [comment] 2017-01-03 22:35
This is helpful feedback. Thank you for opening this issue.

**Comment by zakdances** [comment] 2017-01-05 22:18
And intellisense doesn't just fail when it comes to an open document - it also fails with the command panel:

<img width="601" alt="screen shot" src="https://cloud.githubusercontent.com/assets/1066961/21699634/412552ec-d362-11e6-9085-cd691cfc104e.png">

I've used `Extensions: Install Extensions` many times. I've used `Extensions: Disable All Installed Extensions` exactly 0 times. And yet VSCode has chosen the latter as it's default highlighted suggestion. Why?

**Comment by jchook** [comment] 2017-01-20 03:52
As a Sublime user trying out VS Code, this issue alone will keep me from switching.

**Comment by heeefei** [comment] 2017-02-07 08:42
Is there any plan to solve this issue?

**Comment by DmitryEfimenko** [comment] 2017-02-22 18:04
Huge +1.
My biggest issue is that when constructing an object of a known type (typescript), and attempting to get a suggestion for its property, the suggestions does not show the type's properties **on top**, but rather mixed up with other things making you hunt for these based on icon. Just fixing this ordering issue would improve usability tremendously.
![vsc - suggestions issue](https://cloud.githubusercontent.com/assets/2098175/23225213/59bb6c36-f8ee-11e6-8813-32779a3f8a5b.jpg)

**Comment by mjbvz** [comment] 2017-04-12 00:00
Adding @jrieken since he looked into improving suggestion ordering with #22153. As far as I can tell, the TypeScript extension does provide correctly ordered results in many of these cases, but once filtering kicks in, we sometimes end up showing items that were originally weighted lower first in the list

I believe that @bpasero has also been investigating improving file quick open filtering with  #21019, #12095, and #17443

**Comment by jrieken** [comment] 2017-04-12 07:37
Problem is like this: Suggestions can come from multiple providers that don't know each other. The consequence is that there is no way a local sort order from one provider applies globally. 

Because of that we sort alphabetically when no filter text is given (the text left of the cursor). As soon as something is being typed we sort/filter completions based on how well they match against the text left of the cursor. The latter part is *new* and will ship with the April release (https://github.com/Microsoft/vscode/issues/23643). Try it out in insiders today. The behaviour should be very sublime-fuzzy-like.

![apr-12-2017 09-37-04](https://cloud.githubusercontent.com/assets/1794099/24946572/aed15244-1f63-11e7-91cc-c7c23b9262d7.gif)

**Comment by jrieken** [comment] 2017-04-12 07:39
> col is NOT an intelligent suggestion in that context.

@zakdances Yes, it's a snippet and there is a setting to not show snippet in IntelliSense: `"editor.snippetSuggestions": "none"`

**Comment by jrieken** [comment] 2017-04-12 07:40
I'd say this issue is a dupe of https://github.com/Microsoft/vscode/issues/16109 and https://github.com/Microsoft/vscode/issues/23643

**Comment by mjbvz** [comment] 2017-04-12 23:00
Ok, closing as a duplicate of those issues.  Please give the latest VSCode insiders a try and let us know how the new suggestion ordering works

**Closed by mjbvz** 2017-04-12 23:00 UTC
Labels: duplicate, intellisense, typescript

**Comment by hefei00** [comment] 2017-04-13 09:37
![](http://om7r90s26.bkt.clouddn.com/QQ20170413-170507.png)
It looks better in VSCode insiders. Can't wait for the next update.

**Comment by aight8** [comment] 2017-04-23 01:17
Totally agree with this. It should be possible to order / group the suggestions and make it more context aware.
