### ISSUE TITLE
Add backreference from problem list to task output

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode#44573] opened 2018-02-27 13:39 UTC
Some tasks, like c++ compilers generate extra information, e.g. fix suggestions or detailed explanation.
It would be nice if problem matcher could navigate not only to the source file where error is, but also to the task output, where message was parsed.

Although maybe it's possible to implement via an extension.

**Comment by dbaeumer** [comment] 2018-02-28 10:25
We are actually discussing ways how we could annotate problems with additional problems so that this information can be shown in the problems view.

**Comment by alexr00** [comment] 2020-05-15 08:45
duplicate of https://github.com/microsoft/vscode/issues/39920

**Closed by alexr00** 2020-05-15 08:45 UTC
Labels: feature-request, tasks
