### ISSUE TITLE
JS `var` syntax highlighting leaks

### ISSUE THREAD

**Issue by markbrouch** [Microsoft/vscode#5174] opened 2016-04-11 21:39 UTC
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.3

JS syntax highlighting for `var` and `let` leaks into some words that contain these patterns:
![image](https://cloud.githubusercontent.com/assets/5997332/14443263/0773c3c8-fff3-11e5-9f7d-70fea8387e71.png)

Steps to Reproduce:

1. Create a file using either `JavaScript` or `JavaScript React` syntax highlighting.
2. Use `Dark (Visual Studio)` theme, or any theme with `var` and `let` highlighting.
3. Observe the following code's syntax highlighting:
```
var // correct

variable // incorrect

var
variable // incorrect

var // random comment
variable // correct

var;
variable // incorrect

const // correct
constant // correct

let // correct

lettuce // incorrect

let // random comment
lettuce // correct

let;
lettuce // incorrect

sublet // correct
```

**Comment by kumarharsh** [comment] 2016-04-12 05:24
Duplicate of https://github.com/Microsoft/vscode/issues/4620

**Comment by egamma** [comment] 2016-04-12 13:32
Thanks @kumarharsh closing as duplicate.

**Closed by egamma** 2016-04-12 13:32 UTC
