### ISSUE TITLE
Markdown preview size is off when editor zoom is not the default

### ISSUE THREAD

**Issue by zbendefy** [Microsoft/vscode#21123] opened 2017-02-22 12:09 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. Open VS Code, open a new file
2. Type the following: * Hello world!
3. Save the file as Test.md
4. Press Ctrl+P, and use the following command: Markdown: Open preview to the side. This opens a preview of the markdown on the right side.
5. Zoom in the editor with CTRL + NUMPAD_PLUS, and zoom out with CTRL + NUMPAD_MINUS
The markdown preview will be off. If you zoom in, the content area will be smaller that it could be, and if you zoom out, the content area is off the screen.

**Comment by eighteyes** [comment] 2017-02-23 00:07
Also seeing this behavior on the extension install screens.

**Comment by mjbvz** [comment] 2017-02-23 19:56
Thanks for the report. This is a duplicate of #5745 . That bug affects all webviews, not just the markdown preview

**Closed by mjbvz** 2017-02-23 19:56 UTC
Labels: duplicate, webview
