### ISSUE TITLE
editorIndentGuide.activeBackground disappears when the cursor is above the viewport

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49072] opened 2018-05-02 18:13 UTC
The line will disappear when the cursor is above the viewport, it works fine when the cursor is below the viewport though.

My setting:

```
"editorIndentGuide.activeBackground": "#535a6b"
```

**Comment by usernamehw** [comment] 2018-05-13 17:52
Duplicate of #49173

**Closed** 2018-05-13 19:13 UTC
Labels: *duplicate, bug
