### ISSUE TITLE
Unnecessary empty space beside the scroll bar of the Markdwon Preview panel

### ISSUE THREAD

**Issue by lian860911** [Microsoft/vscode#24171] opened 2017-04-07 05:34 UTC
- VSCode Version: 1.11.1
- OS Version: Win10 64bit

Steps to Reproduce:

1. Open a .md file, file has some contents.
2. Press Ctrl+K,V to open the Markdown Preview panel.

Will see a big padding(empty space) on the right of the scroll bar of the Preview panel.

![preview](https://cloud.githubusercontent.com/assets/6336245/24786813/df456454-1b96-11e7-8f65-489de08541e0.png)

**Comment by Pixelmixer** [comment] 2017-04-07 15:52
Just to add a bit of information to this one as well. I see the same problem and its more pronounced on very long Markdown files.

You can see in this screenshot that the markdown view doesn't expand to use the entire window size. Its cut off partially down the available window space about 2/3 the available height and its horizontally cut off about 2/3 of the available width. The rest of the space on the right and bottom is just blank space not being used. I've only seen this happen on markdown file previews (including the update Release Notes).

![screen shot 2017-04-07 at 11 49 49 am](https://cloud.githubusercontent.com/assets/347311/24808014/5ec354e8-1b88-11e7-9231-1c9afed4d67d.png)

**Comment by mjbvz** [comment] 2017-04-07 15:57
I believe this a duplicate of #5745

**Closed by mjbvz** 2017-04-07 15:57 UTC
Labels: duplicate, webview
