### ISSUE TITLE
AutoComplete enhancement: press enter on selecting suggestion.

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#27701] opened 2017-05-31 07:53 UTC
- VSCode Version: 1.12.2 (1.12.2)
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Enter some words, like `toLowerCase`.
2. Suggestion will show up.

<img width="814" alt="2017-05-31 3 43 59" src="https://cloud.githubusercontent.com/assets/8279858/26621238/ad4fed64-4618-11e7-95a1-6d12a104bf0d.png">

If I press enter, and I have `acceptSuggestionOnEnter` enabled, `"editor.acceptSuggestionOnEnter": true,`. The current behavior is it will create a newline, but I think since we are selecting the suggestion, the correct behavior should be dismiss the suggestions ( which this is Sublime's default behavior).

**Comment by jrieken** [comment] 2017-05-31 08:59
dupe of #24420

**Closed by jrieken** 2017-05-31 08:59 UTC
