### ISSUE TITLE
Proposed FileSystemProvider API doesn't support multiple workspace folders per provider

### ISSUE THREAD

**Issue by khimaros** [Microsoft/vscode#36837] opened 2017-10-24 17:05 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:25:22.140Z)
- OS Version: Linux x64 4.9.0-4-amd64

I would like to support multiple folders for a given FileSystemProvider in a single workspace.

As an example, a user's code-workspace might be configured as follows:

```
{
  "folders": [
    {
      "uri": "sftp://user1@host1/path/1"
    },
    {
      "uri": "sftp://user2@host2/path/2"
    }
  ]
}
```

I've attempted to accomplish this in a number of different ways, but it seems that the API, as currently implemented, doesn't support this use case.

With the current implementation, it appears that the `authority` passed to `vscode.workspace.registerFileSystemProvider()` must match precisely the scheme of the folder URI in order for the `onFileSystemAccess` activation to be properly dispatched. Only the first provider registered for a given authority will receive dispatches.

Additionally, the `root` field must be a single `vscode.Uri` to match the FileSystemProvider interface, so it is not possible to manually handle dispatching to separate backends in a single FileSystemProvider instance.

**Comment by khimaros** [comment] 2017-10-24 17:06
@jrieken who seems to be working on this proposed API.

**Comment by siegebell** [comment] 2017-10-24 17:39
See also #36177.

**Comment by jrieken** [comment] 2017-10-24 18:00
Yeah, closing this as a dupe of #36177

**Closed by jrieken** 2017-10-24 18:00 UTC
Labels: api, duplicate, remote
