### ISSUE TITLE
Clearing the terminal leads to strange behavior

### ISSUE THREAD

**Issue by yungkevster** [microsoft/vscode#179615] opened 2023-04-10 17:10 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1
- OS Version: Windows 11

I am using the Powershell terminal!

Steps to Reproduce:

1. Add the following code to the keybindings.json file and save it:

```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+k",
        "command": "workbench.action.terminal.clear",
        "when": "terminalFocus"
    }
]
```
2. Type something in the terminal, preferably something that will generate errors. What you want to do next is to press `ctrl+k` which is the newly implemented keybind, which will clear the terminal and the buffer.

3. Once the terminal is clear, type something. If you have the same issue as me, it will let you type two characters on the first row and then jump down to the last row where you will continue what you were writing. This seems like a bug and is an extremely weird behavior.

Only work-around I've found is to do `ctrl+l` or type `clear` in the terminal before pressing `ctrl+k`.

Here is a picture for reference:

![image](https://user-images.githubusercontent.com/113138995/230953290-f70e21ed-ccdb-4f9b-bedf-2f1f3a45a81b.png)

**Comment by meganrogge** [comment] 2023-04-11 15:19
/duplicate of https://github.com/microsoft/vscode/issues/75141

**Closed by meganrogge** 2023-04-11 15:19 UTC

**Comment by yungkevster** [comment] 2023-04-11 15:55
> /duplicate of #75141

Not really a duplicate when the post is 4 years old and has no solution.
