### ISSUE TITLE
New gradient snippet has incorrect syntax

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1219] opened 2015-12-12 11:28 UTC
A gradient snippet was recently added to the CSS snippets.

This has an incorrect syntax for the unprefixed version. When it was standardised the angles were changed so that the old "top" keyword (as used in the snippet) maps to "to bottom" in the standard syntax. "left" becomes to right, and so on.

The current code will create a gradient that is flipped for browsers that use the unprefixed version.

**Comment by aeschli** [comment] 2015-12-16 10:33
duplicate of #1220

**Closed** 2015-12-16 10:32 UTC
Labels: bug, css-less-sass
