### ISSUE TITLE
The used $path differs between the Shell task and the terminal.

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27185] opened 2017-05-24 08:17 UTC
When executing a ShellTask from the API like this:
```typescript
new vscode.ShellTask(`echo path`, `echo $path`)
```
Then you get this output:
```
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /usr/local/go/bin /Users
/egamma/.nvm/versions/node/v5.10.1/bin
```

When running `echo $path` from the terminal then the path differs:
```
echo $path
/Users/egamma/.nvm/versions/node/v5.10.1/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /us
r/local/share/dotnet /usr/local/go/bin
```

Notice that the `.nvm` path appears first, which means this node version will be executed. The node version executed by the `ShellTask` is the one in `/usr/local/bin`.

//CC @dbaeumer

**Comment by egamma** [comment] 2017-05-24 11:12
I'm using `zsh` in the terminal, one explanation is that different shells are used?

**Comment by Tyriar** [comment] 2017-05-24 17:42
@egamma I think this is to do with `~/.bashrc` not being sourced when running using `-c`, I believe @dbaeumer has run into this before.

**Comment by Tyriar** [comment] 2017-05-26 16:14
@dbaeumer it happens for me on Linux after a quick test by adding an echo on to `~/.bashrc` then running `bash -c "echo 'something else'"`

**Comment by dbaeumer** [comment] 2017-05-29 09:06
@Tyriar you are correct. I did some more investigation and if you start bash -c they don't source .bashrc on purpose since it might override the environment set up by the one calling bash -c. However you can force the sourcing of .bashrc by using bash -i -c. I tested this under Windows and Linux. @Tyriar can you confirm this behavior on the Mac.

@egamma how did you start vscode on the Mac. I think we need to find out why the path is reordered in your case. 

I am against starting a shell command with -i to source the rc file again since it might override the environment again. Node doesn't do that either when running shell commands using child_process.exit

**Comment by egamma** [comment] 2017-05-30 13:55
@dbaeumer I'm pretty sure that I've started VS Code from the dock.

**Comment by dbaeumer** [comment] 2017-05-30 21:16
@egamma in this case we have special code to read the env by starting the shell and printing the environment and carrying it over to VS Code. Can you reproduce this when starting code from the zsh shell directly ?

@joaomoreno knows more about this.

**Comment by Tyriar** [comment] 2017-05-30 21:35
There are chunks of code at the start of a lot of `~/.bashrc` files that exit early when the shell is non-interactive:

```bash
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac
```

```bash
[ -z "$PS1" ] && return
```

https://unix.stackexchange.com/a/170499/115410

Running interactively seems like it would make sense for tasks.

**Comment by dbaeumer** [comment] 2017-05-31 05:23
@Tyriar but this will source in the .*rc files which might reset the env which someone carefully crafted with the options. So I am a little lost here.

**Comment by Tyriar** [comment] 2017-05-31 19:48
@dbaeumer I am a little confused still as well, this issue says to be that the shell isn't inheriting the environment from VS Code, however I can see GOOGLE_API_KEY for example which is created by Electron when I `env` in a regular terminal session. It looks like the code in terminalTaskSystem.ts that does the environment cloning should work fine too.

**Comment by dbaeumer** [comment] 2017-06-01 06:51
Best will be that I look with Erich on a Mac into this. What I was trying to explain is the following: under Mac when started from the dock we do tricks to get the environment of the shell passed to VS Code since a Mac app starting from the dock doesn't get it automatically (to my knowledge we spawn the configured shell and execute a node app in it to print the env to the console)

Since the path is correct but reordered I guess something might happen there. 

The code in terminalTaskSystem.ts simple copies the process.env into a new map and then takes user specified env and assigns it to the same map. No value magic :-). 

@egamma do you set an env in the task?

**Comment by egamma** [comment] 2017-06-01 09:20
>do you set an env in the task?

@dbaeumer no, I don't

**Comment by dbaeumer** [comment] 2017-06-01 10:01
@egamma does it reproduce when you start code from the zsh.

**Comment by Tyriar** [comment] 2017-06-01 16:26
@egamma does `/Users/egamma/.nvm/versions/node/v5.10.1/bin` come up in devtools when you run `process.env`?

**Comment by dbaeumer** [comment] 2017-11-09 11:24
The problem here is that the shell is started without `-i` the therefore no profile is applied. I am working on letting users control the shell args to use even for contributed tasks which will fix this. Closing as dup of #36342

**Closed by dbaeumer** 2017-11-09 11:24 UTC
Labels: integrated-terminal, tasks, under-discussion
