### ISSUE TITLE
[Accessibility]A11y_VSCode_StatusBar_Screenreader: Voiceover is not reading the selected item name of "StatusBar".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51981] opened 2018-06-15 08:30 UTC
**Environment Details:**
VSCode Version : 1.24.0
OS Version : MAC OS HighSierra10.13.5

**Additional Details:**
ScreenReader,Voicover,MAS1.3.1

**Repro Steps:**
1.Launch VS Code while Voiceover is ON.
2.Navigate to "Status Bar" at bottom of the screen after login.
3.Navigate to item list of "Status Bar" such as "Error,Warning,ScreenReaderOptimized".
4.Observed that,Voiceover is not reading the selected/clickable item name.

**Actual:**
While reading through the screenreader such as Voiceover, it is not reading the selected item name of status bar "Error,Warning,ScreenReaderOptimized,Spaces:4,Plain Text,Tweet Feedback,Notification" items.
Here,Voiceover is only reading the placeholder value.

**Expected:**
Voiceover should reads the name of each selected item name of "Status Bar"
Instead of reading only the placeholder value.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will not understand which item is selected from thr "StatusBar".

**MAS Reference:**
MAS1.3.1- [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_StatusBar_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2105331/Accessibility.A11y_VSCode_StatusBar_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-06-16 05:35
Duplicate of https://github.com/Microsoft/vscode/issues/51977

**Closed by bpasero** 2018-06-16 05:35 UTC
Labels: accessibility, workbench-status
