### ISSUE TITLE
Allow to change the background color of menu bar (Windows & some Linux)

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#16363] opened 2016-12-02 08:59 UTC
The menu bar is inconsistent with the dark theme in particular.

**Comment by martinsuchan** [comment] 2017-03-25 10:39
To get the idea, Visual Studio Code is at the top, full Visual Studio 2015 at the bottom.
![aa8ea206-f2ac-11e6-8cd9-650d4ed5e722](https://cloud.githubusercontent.com/assets/3041397/24321562/88340694-114f-11e7-8f6d-52fd44486687.PNG)
![d6f54dae-f2ac-11e6-9cc5-73524b61eb7d](https://cloud.githubusercontent.com/assets/3041397/24321563/91e11952-114f-11e7-8578-e9603ddf0774.png)

**Comment by Stanzilla** [comment] 2017-03-27 21:06
Those would have to be rewritten in JS then and the default Windows controls hidden

**Comment by EMLVIRUS** [comment] 2017-08-15 09:40
Totally agreed with @be5invis

**Comment by jens1o** [comment] 2017-08-15 10:25
Question: Why this issue hasn't a milestone included?

**Comment by EMLVIRUS** [comment] 2017-08-15 10:30
I guess they haven't look into this yet

**Comment by martinsuchan** [comment] 2017-08-15 11:40
Electron runs inside standard Windows window. There is a Win32 API for changing window colors and fonts. I think the discusssion should not be "is it possible?" but rather "how to do it".

**Comment by TJFadness** [comment] 2017-09-04 09:40
The issue is the menu bar (File, Edit, Selection, ...), which is provided by Electron, not the title bar, provided by Windows. 

See [this Electron issue](https://github.com/electron/electron/issues/1250), which shows it isn't directly possible at the moment. The suggestion is to re-implement the menu bar.

**Comment by mrmckeb** [comment] 2017-12-02 08:39
It might make sense to re-implement the menu bar for Windows. With upcoming "Sets" feature in Windows 10, a custom menu would make VSCode look the part in Windows 10.

**Comment by 1st** [comment] 2017-12-03 22:21
For MacOS it's implemented for atom/atom#11790 already. Can you back-port this change to VSCode?

**Comment by mjkramer** [comment] 2018-02-08 06:52
On Linux, this should be fixed by the upcoming Electron 1.9, which will be based on Chromium 61 + GTK3. See https://github.com/electron/electron/pull/10213 and https://github.com/electron/electron/issues/10836.

**Comment by thedonquixotic** [comment] 2018-05-27 14:52
Just wanted to add that I would like to see this change made also.

**Comment by Benjmhart** [comment] 2018-05-28 00:29
+1 for making this chnge

**Comment by mohouyizme** [comment] 2018-06-13 02:52
### It's not the best solution but it works fine for me:
Since all lists of the menu bar are available on the command palette `ctrl+shift+p` , I set `"window.menuBarVisibility"` to `"hidden"` and I changed the Windows 10 color via Settings based on my vscode theme background and this is the result:

![screenshot_3](https://user-images.githubusercontent.com/23297439/41327846-9844cd84-6eb4-11e8-9122-0bb018536c3c.png)

**Comment by jrnail23** [comment] 2018-06-13 19:40
I was referred here from [Make it easier to distinguish between multiple VS Code windows #51710](https://github.com/Microsoft/vscode/issues/51710)...

in case anyone else comes across this issue, the following (in my workspace settings file) did exactly what I wanted:
```json
{
	"workbench.colorCustomizations": {
		"statusBar.background": "#666666",
		"sideBar.background": "#444444"
	}
}
```
Here are the docs for those color customizations: https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by teejayen** [comment] 2018-06-30 21:55
Using a custom colour in Windows 10 and selecting to show the accent colour on **Title bars** will achieve the desired result.

![Windows 10 Colour Settings](https://user-images.githubusercontent.com/12872656/42129284-1bbe5eb6-7d04-11e8-9080-b07e6cd5d8a1.png)

**Comment by teejayen** [comment] 2018-06-30 23:28
@thedonquixotic, my mistake.. should have read the thread more thoroughly.

**Comment by thedonquixotic** [comment] 2018-07-02 17:53
Hey guys, I think I might actually have a solution though this might be a bad suggestion on my part. 

I've recently been fiddling around with editing the Windows theme using registry editing. It's.... probably not super recommended, and I can't tell you how right at this moment (uh... because in the process I also totally borked my install of Windows 10), but from what I've been learning (or breaking) recently it should be possible, and relatively easy to put into a bat script. I'll let you guys know when I figure more out.

**Comment by mohouyizme** [comment] 2018-07-03 14:32
@fl3x1324 Good news! but I think it's not enough since the menu bar colors should be customizable within the themes.

**Comment by Emeryao** [comment] 2018-07-04 02:50
Hey guys, take a look at [what](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md#custom-title-bar-and-menus-for-windowslinux) I just found 😝 

```json
{
  "window.titleBarStyle": "custom"
}
```

**Comment by mohouyizme** [comment] 2018-07-04 16:41
@Emeryao It's available just in insiders version, hope it will be available in the next stable update, although it still needs some work.

**Comment by PawelekS** [comment] 2018-07-05 21:14
@mohouyizme You was right ^^
1.25 has it

@Emeryao <3

**Comment by mohouyizme** [comment] 2018-07-05 22:07
@PawelekS Good news! it is now in the stable version which is 1.25.0.

**Comment by Wiredframe** [comment] 2018-07-19 11:52
Really great to see that dark menu and title bar have been added, thanks! I just noticed that touch input doesn't work as expected in the menu. 😆

**Comment by istvandesign** [comment] 2018-07-20 07:50
Also in Windows if you have the taskbar on the top you will get a white line and misalignment every second time you minime and maximize the window.

![vscode-titlebar](https://user-images.githubusercontent.com/39516661/42990207-bfab2d32-8c0a-11e8-9471-f733f28d0976.png)

**Comment by Logerfo** [comment] 2018-08-16 20:49
I use to hide native title bars on windows by unsetting the `0xC00000` flag. While the custom title bar is great by making both the menu bar and context menus follow the dark theme, it makes the title bar unhideable. I wish there was a mixed setting: use custom menus, but use the native title bar.

**Closed** 2018-08-21 07:36 UTC
Labels: feature-request, themes, workbench-menu
