### ISSUE TITLE
NLS attempts to load messages from uninstalled extension

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#65476] opened 2018-12-20 10:46 UTC
Seen on dev.

Steps:

1. Add marketplace settings to dev, such that you can install an extension in dev
2. Install Python 2018.12.1, Reload
4. There is an NLS error, so far so good
5. Uninstall it, reload
100. The NLS error still appears:

![image](https://user-images.githubusercontent.com/22350/50280435-cb849480-044c-11e9-8b14-6f7eddd81ac0.png)

cc @sandy081

**Comment by dbaeumer** [comment] 2019-10-16 10:57
Retested with latest and was not able to reproduce. Closing.

**Closed by dbaeumer** 2019-10-16 10:57 UTC
Labels: bug, i18n
