### ISSUE TITLE
'format document' produces a very ugly document, say html document.

### ISSUE THREAD

**Issue by aisakeniudun** [Microsoft/vscode#17869] opened 2016-12-28 08:59 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|speech|bierner|0.0.1|
|scala|daltonjorge|0.0.4|
|vscode-markdownlint|DavidAnson|0.6.0|
|vscode-instant-markdown|dbankier|0.2.1|
|glslx-vscode|evanw|0.0.8|
|Theme-HotDogStand|gerane|0.0.2|
|theme-microsoft-graph|martellaj|0.0.2|
|easy-less|mrcrowl|1.3.4|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vshaxe|nadako|1.0.1|
|sass-indented|robinbentley|1.3.0|
|preview-vscode|searKing|1.1.1|
|shader|slevesque|0.2.2|
|shader-toy|stevensona|0.1.8|
|ActionScript3|yopsolo|0.0.1|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. new a html document segment
2. contextmenu, format document

**Comment by jaseonline** [comment] 2017-01-03 09:01
@aeschli I'll provide an example:

If I enter the following (and format myself):

<!doctype html>
<html lang="en-us">
    <head>
        <title></title>
    </head>
    <body>
        
    </body>
</html>

And then right-click anywhere in the editor and select Format Document, it then mangles all of the text to make it look like this:

<!doctype html>
<html lang="en-us">

<head>
    <title></title>
</head>

<body>

</body>

</html>

Which is absolutely horrible.

I don't have any extensions installed other than the ones that come with VS Code. My version is 1.9.0 and I'm on Windows 10.

**Comment by aeschli** [comment] 2017-01-04 00:37
duplicate of #17849

**Comment by jaseonline** [comment] 2017-01-04 04:40
@aeschli I don't believe this to be a duplicate. The Issue you linked to relies on the HTML having style tags in it. If not then might I suggest including extra information in the original issue stating that style tags are not required to reproduce this issue?

**Comment by aeschli** [comment] 2017-01-07 22:06
@jaseonline Maybe not a exact duplicate but both issues are cause by the same bug. I fixed it an and you can try out the fix in the latest [insider build](https://code.visualstudio.com/insiders).

**Comment by aeschli** [comment] 2017-01-07 22:11
@jaseonline Sorry, you are absolutly right, not a duplicate. What you see is the way how the _jsbeautify_ formatter works. But, you can control this behaviour by using the following setting
`"html.format.indentInnerHtml": true'`.

**Closed by aeschli** 2017-01-07 22:11 UTC
