### ISSUE TITLE
Long branch name disappears on small window sizes

### ISSUE THREAD

**Issue by notseenee** [Microsoft/vscode#66127] opened 2019-01-07 06:25 UTC
- VSCode Version: 1.30.1
- OS Version: macOS Mojave

Steps to Reproduce:
1. Create a git repo with a long branch name
2. Make the window smaller

Screenshot:
![image](https://user-images.githubusercontent.com/27017118/50752151-1b62b880-12a1-11e9-8887-0f4f2dc54213.png)
![image](https://user-images.githubusercontent.com/27017118/50752154-20276c80-12a1-11e9-9430-4d22dd7a613d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment] 2019-01-07 16:40
Marking as duplicate of #6651, #35744, #3874

**Closed by bpasero** 2019-01-07 16:40 UTC
