### ISSUE TITLE
Ambiguous error message when extension API is incompatible

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#225639] opened 2024-08-14 19:27 UTC
1. Download the [vsix for copilot chat 0.18.2 ](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=287846&view=artifacts&pathAsName=false&type=publishedArtifacts).
2. On v1.93 insiders, download the vsix.
3. See an error message that doesn't make it clear what went wrong :bug:

This is when it failed on a codespace, but @joyceerhl also saw it on desktop insiders.
 
![Image](https://github.com/user-attachments/assets/60520814-9042-4d4a-a06b-d5abbf94d767)

@roblourens suspected that this is due to incompatible API version.

**Comment by sandy081** [comment] 2024-12-10 15:47
Sorry that for getting on to this after a long time. I no longer able to access the linked artifacts. Can you please let me know if you are still able to repro this? If so can you please update the steps?

**Comment by andreamah** [comment] 2024-12-10 17:39
I also can't access since I'm not on the team anymore 😅  maybe you can try downloading an old version of copilot chat that has an incompatible API version and see whether this repros.

**Comment by sandy081** [comment] 2024-12-12 08:58
Cannot reproduce anymore. Closing.

**Closed by sandy081** 2024-12-12 08:58 UTC
Labels: info-needed
