### ISSUE TITLE
"Refactoring via Extraction" in the "Interactive Playground" doesn't work

### ISSUE THREAD

**Issue by robert-lewon** [Microsoft/vscode#41619] opened 2018-01-15 11:43 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-25-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.2.5
python|ms-|0.9.1
code-spell-checker|str|1.6.2
twig|wha|1.0.2

---

It's impossible to "play" with the "Refactoring via Extraction" in the "Interactive Playground" document. The CTRL+. shortcut doesn't work as well as the light bulb. However, the feature works fine in *.js files. I assumed that it works fine in typescript documents as well.

Steps to Reproduce:

1. Enter the "Interactive Playground" document (with or without the "directory" context).
2. Go to "Refactoring via Extraction" section.
3. Try to follow the guide from this section to use the feature.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment] 2018-01-16 10:52
Could be @40915.

**Comment by mjbvz** [comment] 2018-01-23 02:37
Duplicate of #40915

**Closed by mjbvz** 2018-01-23 02:37 UTC
Labels: bug, workbench-welcome
