### ISSUE TITLE
Allow a native way to "Run Code" from any file

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#56268] opened 2018-08-13 17:57 UTC
It would be great if there was a native way to "Run Code" on any file, [similar to this extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). Would be great if there was an easy way to switch between this mode and "Debugging". 

Xcode and VS for Mac use this concept:

![image](https://user-images.githubusercontent.com/35271042/44048869-7b93ecb6-9ee7-11e8-92d9-cd43b0d14a9e.png)

![image](https://user-images.githubusercontent.com/35271042/44048889-8613206c-9ee7-11e8-8ffd-79d2efe0f1d2.png)

**Comment by weinand** [comment] 2018-08-14 09:12
VS Code cannot do this "natively" because there is no generic way to "run" an arbitrary file.

The knowledge for how to debug (or run without debugging) comes from debug extensions.
They can implement a feature to debug (or run) the active file in the editor and some of the debug extensions actually do this.

The problem is that this functionality is only available as a fallback if no launch configs are defined.

**Comment by misolori** [comment] 2018-08-14 17:38
So it looks like our current implementation of "Start without Debugging" could very well solve the issue at hand from a technical standpoint. This does exactly what I would expect 👍.

From a UX perspective, users who are not familiar with debugging don't know where to look and wouldn't think to look in "debugging". We could solve this problem by re-phrasing the action (something either like "Run" or "Start"). 

Secondly, because users would expect to be able to "Run" any file, the "Run" button can't be hidden in the debug panel. This is probably one that will require more discussion with the wider team if we decide to go that route. It's very reasonable to expect to see a "Run" button that is outside of the panel/sidebar and possible in the workbench.

**Comment by isidorn** [comment] 2018-08-15 16:06
@misolori I am glad you touched upon this subject as I would be also very interested in tryign to reduce the complexity of the initial start debug experience.
Let's assign this also to myself and to On-Deck so we look into this once we find time.

@misolori we could start with a ux discussion in a call

**Comment by qubitron** [comment] 2018-08-31 17:54
@misolori agreed that renaming the "Start without Debugging" command to the "Run" would provide a better match to what user's expect. 

Though I find it odd that the start without debugging puts Code into "debug mode" with the debug toolbar and orange status bar appearing at the bottom. IMO it should work like Visual Studio, where start without debugging just launches the app and the VS IDE doesn't enter debug mode.

**Comment by weinand** [comment] 2018-08-31 19:00
Since VS Code is an editor, it just doesn't know how to "launch an app". It does not even know what an app is. So the functionality to "launch an app" must come from somewhere. 
Until we have found a generic way to "launch an app" we are "repurposing" the debugger's "launching a program in debug mode" for the similar functionality to "run a program".
The advantage of this approach is that the user can reuse a launch config for both debugging and running.
If you know a better approach, please let us know.

**Comment by qubitron** [comment] 2018-09-04 13:52
No push-back on using start without debugging to launch the file, I like this approach.

I was making a (perhaps off topic) comment that VS Code's "run without debugging" behavior looks a lot like debug mode and users may get confused between run and debug modes. This can be discussed a separate issue, though.

**Comment by qubitron** [comment] 2019-02-11 20:18
I noticed that Terminal -> Run Active File was added, but this just invokes the file from the command line, which means it doesn't use the correct Python interpreter to run.

It would be great if this could Ctrl+F5 the application, we would then use this in favor of our "Run Python File in Terminal" command.

**Closed** 2019-10-08 10:43 UTC
Labels: *out-of-scope, debug, feature-request
