### ISSUE TITLE
React-dnd feature is broken within vscode when files are drag and dropped

### ISSUE THREAD

**Issue by Uma19** [microsoft/vscode#96770] opened 2020-05-01 11:21 UTC
Version of vscode 
from **1.40 to 1.44.2 versions**. The below issue is reproducible

**Issue description:**
Its not allowing me to drop the file and giving me overlay effect, while dragging the files within vscode and dropping within the editor section, that contains my code related with "React-dnd" library.

**Steps to repro**

Taken sample code from vscode =>  webView Sample 
I have modified the code to pick "react-dnd" code within "iframe".
 
<iframe height="500vh" width="100%" sandbox="allow-scripts" nonce="${nonce}" src="${iframesrc}"></iframe>

And now on top of that when I try to drag any file within vscode , it doesnt allow me to drop and gives me some overlay effect

Also attaching the Screenshot of the same
![react-dnd-failes](https://user-images.githubusercontent.com/10219453/80801967-8f7a4b80-8bcb-11ea-9f64-e73de24e8891.png)

expected result should be like below. Allowing files to drop
![expected-result](https://user-images.githubusercontent.com/10219453/80802080-e54ef380-8bcb-11ea-971b-598969bc09cf.png)

let me know if any other information is needed regarding the same

**Comment by Uma19** [comment] 2020-05-01 11:27
@egamma : Hi Erich
I had raised one more issue regarding the same on which you had asked me to provide some more input . Sorry I couldnt able to reply to your comment at that time and the issue got auto closed.
So again had created one more issue with some more details
Also find the existing issue reported 
https://github.com/microsoft/vscode/issues/85030

**Comment by Uma19** [comment] 2020-05-01 11:42
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Unable to drag and drop files from Explorer to VSCode when running as different user (#38999)](https://www.github.com/microsoft/vscode/issues/38999)

Hi Team,
This is not the same issue
As mine is mainly associated with application that is using react-dnd library and is getting loaded within vscode

**Comment by sbatten** [comment] 2020-05-01 17:37
@mjbvz I don't think this is related to my changes as I've never touched the editor's drag and drop handler.

**Comment by mjbvz** [comment] 2020-05-02 02:36
This has never been supported as far as I know. I'm closing this as a duplicate of #8794

**Closed by mjbvz** 2020-05-02 02:36 UTC

**Comment by Uma19** [comment] 2020-05-02 09:10
Hi @mjbvz 
This feature **was supported till 1.39.2 version** of vscode and then later onwards this stopped working

**In 1.44.2 version**
Please find the below suspected codes that is responsible for the issue that I am raising. and the same code doesn't exist in 1.39.2 where my functionality was working 

**From the below code => it seems to be it creates an overlay within editor part**
**https://github.com/microsoft/vscode/blob/1.44.2/src/vs/workbench/browser/parts/editor/editorPart.ts**
//#region TODO@matt this should move into some kind of service

	createEditorDropTarget(container: HTMLElement, delegate: EditorDropTargetDelegate): IDisposable {
		return this.instantiationService.createInstance(EditorDropTarget, this, container, delegate);
	}

	//#endregion

**https://github.com/microsoft/vscode/blob/1.44.2/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts**

windowDidDragStart(): void {
		// Webview break drag and droping around the main window (no events are generated when you are over them)
		// Work around this by disabling pointer events during the drag.
		// https://github.com/electron/electron/issues/18226
		if (this.element) {
			this.element.style.pointerEvents = 'none';
		}
	}

	windowDidDragEnd(): void {
		if (this.element) {
			this.element.style.pointerEvents = '';
		}
	}

**https://github.com/microsoft/vscode/blob/1.44.2/src/vs/workbench/contrib/webview/browser/dynamicWebviewEditorOverlay.ts**

windowDidDragStart() {
		this.withWebview(webview => webview.windowDidDragStart());
	}

	windowDidDragEnd() {
		this.withWebview(webview => webview.windowDidDragEnd());
	}

**And in 1.39.2 version you will NOT find the similar kind of codes exist in the respective file**

https://github.com/microsoft/vscode/blob/1.39.2/src/vs/workbench/browser/parts/editor/editorPart.ts
https://github.com/microsoft/vscode/blob/1.39.2/src/vs/workbench/contrib/webview/browser/dynamicWebviewEditorOverlay.ts

And the one that I have raised is different than the one that you have mentioned as duplicated issue
https://github.com/microsoft/vscode/issues/8794

As in this , the user is trying to drag the button within the webview itself , whereas in my case I am trying to drag the items that is part of VSCODE menu items to the EDITOR panel
