### ISSUE TITLE
Context menu will disappear when there is new text appeneded in Output Channel

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#59001] opened 2018-09-20 02:04 UTC
Issue Type: <b>Bug</b>

I could confirm this bug only repro when `window.titlebarStyle` is `custom`

![bug](https://user-images.githubusercontent.com/1050213/45791482-705fcc00-bcbc-11e8-9249-49d7f930750f.gif)

VS Code version: Code - Insiders 1.28.0-insider (45986ca7abf63460dc96409a61fb2f0c98ba0b70, 2018-09-19T09:34:25.276Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.4
azure-account|ms-|0.4.3
azure-iot-toolkit|vsc|1.4.0

</details>

**Comment by sbatten** [comment] 2018-09-21 16:38
duplicate of #54594

**Closed by sbatten** 2018-09-21 16:38 UTC
Labels: insiders
