### ISSUE TITLE
Can you let vscode read .vscode/extensions from both global and in project folder?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#687] opened 2015-11-26 05:05 UTC
Sometimes we may want to create extension only for project to share with our team and don't need to have them install extension. It should be easy to just send whole project folder contains .vscode/extensions folder to them

**Comment by joaomoreno** [comment] 2015-11-26 09:46
Duplicate of #347

**Closed by joaomoreno** 2015-11-26 09:46 UTC
