### ISSUE TITLE
[json] Request textDocument/* failed with message: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by code-d** [Microsoft/vscode#39344] opened 2017-11-30 01:50 UTC
Output of "JSON Language Server" always show following error:

```
[Error - 09:34:46] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'version' of undefined
  Code: -32603 
```

```
[Error - 09:45:08] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'version' of undefined
  Code: -32603 
```

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: none
---

Steps to Reproduce:

1. open any *.json file 
2a. double-click anywhere in the document
2b. ctrl+space

**Comment by aeschli** [comment] 2017-12-04 14:19
@code-d I'm not able to reproduce.

Can you add the following setting:
- `"json.trace.server": "verbose",`
- open the output view, go to the 'JSON language server tab'
![image](https://user-images.githubusercontent.com/6461412/33557076-733ea260-d906-11e7-9881-16bb28d3d6d8.png)

- reload VSCode (command `reload windows`)
- open the problematic file
- attach the content of the `JSON language server' tab

**Comment by code-d** [comment] 2017-12-06 01:06
@aeschli from my colleagues (i can't reproduce the error myself):
[win.txt](https://github.com/Microsoft/vscode/files/1533501/win.txt)
[mac.txt](https://github.com/Microsoft/vscode/files/1533502/mac.txt)

**Comment by aeschli** [comment] 2017-12-06 10:16
@code-d Thanks a lot!

What's strange is that there is no notification 'textDocument/didOpen' for `pc-boss-frontend/typings.json` sent.
- can you confirm that when you restart, that file is open in the editor
- what does the editor status bar show as mode? 'JSON'?
- is there anything special with this file, is it excluded e.g. with the `"files.exclude"` settings

@dbaeumer Assigning to you, looks like an issue in the language client.

**Comment by dbaeumer** [comment] 2017-12-06 13:00
@aeschli are you sure: the trace shows a hover request for tsconfig.json. Not sure who is triggering this. The protocol states that the server can receive requests for files that are not open in the editor. So the request is in principal valid. 

@code-d Would be cool to know if the file tsconfig.json is open in the editor when this happens. 

@aeschli assigning you as well since this might be a problem of the JSON language server as well.

**Comment by dbaeumer** [comment] 2017-12-06 13:05
@code-d can you reproduce this with all extensions disabled. E.g start code form a terminal with `--disable-extensions`

**Comment by code-d** [comment] 2017-12-07 05:37
@dbaeumer tried run from terminal with `code --disable-extensions` and the issue remains...
@aeschli @dbaeumer 
* it happens when *.json file is open in the editor.
* status bar shows 'JSON'.
* all *.json files are valid and nothing special.
[trace.txt](https://github.com/Microsoft/vscode/files/1537917/trace.txt)
[trace2.txt](https://github.com/Microsoft/vscode/files/1537918/trace2.txt)

**Comment by code-d** [comment] 2017-12-07 08:20
hi, after hard debugging, i think i've found the cause of the issue: 
the issue related to json.schemastore.org
sometimes response data from http://json.schemastore.org are **malformed**. (maybe its my country's network env problem...)
<img width="857" alt="malformed-json-schema-reponse" src="https://user-images.githubusercontent.com/6970719/33704870-1f1126a8-db69-11e7-83dd-517ff1edd540.png">

my temporary workaround:
edit `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/server/out/jsonServerMain.js`
line#99~103
```js
    var headers = { 'Accept-Encoding': 'gzip, deflate' };
    return request_light_1.xhr({ url: uri, followRedirects: 5, headers: headers }).then(function (response) {
        return response.responseText;
    }, function (error) {
        return Promise.reject(error.responseText || request_light_1.getErrorStatusDescription(error.status) || error.toString());
    });
```
change to
```js
    var headers = { }; //if use gzip, the corrupted xhr response may never finish??
    return request_light_1.xhr({ url: uri, followRedirects: 5, headers: headers }).then(function (response) {
        // try {
            JSON.parse(response.responseText); //try parse now, throw error if response data is corrupted
        // } catch (e) {
            // throw e;
        // }
        return response.responseText;
    }, function (error) {
        return Promise.reject(error.responseText || request_light_1.getErrorStatusDescription(error.status) || error.toString());
    });
```

**Comment by dbaeumer** [comment] 2017-12-07 08:43
The second trace has a hint why this is happening. For some reason the JSON server crashes and is not restarted correctly. Would be good to know why it is crashing / the connection is closed

```
[Error - 12:02:04] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/main.js:819:25)
	at Object.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/main.js:87:15)
	at closeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/main.js:215:26)
	at CallbackList.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/events.js:135:36)
```

**Comment by dbaeumer** [comment] 2017-12-07 08:45
@code-d very nice analysis. Thanks for the hard debugging. This explains why the server is crashing and not restarting.

**Comment by dbaeumer** [comment] 2017-12-07 08:48
@aeschli this means even if the LSP client would restart the server it would crash 5 times and then would be dead as well. 

Open https://github.com/Microsoft/vscode-languageserver-node/issues/286 to handle this better in the client. However there is additional work in the JSON server necessary. Leaving this work in this item.

**Comment by dbaeumer** [comment] 2017-12-07 09:30
Publish 4.0.0-next.3 of the client which contains a fix for the exception handling. But please note that this version will not fix the underlying problem of the server crashing.

**Comment by aeschli** [comment] 2017-12-07 10:01
@dbaeumer Any chance the error message sent to the client (`Request textDocument/completion failed with message: Cannot read property 'version' of undefined Code: -32603`) could include the stacktrace?

**Comment by dbaeumer** [comment] 2017-12-07 11:52
@aeschli  Currently I implement the JSON RPC spec (http://www.jsonrpc.org/specification#error_object). We could add a stack to the data property or add an additional property. But both would be LSP specific and clients would need to know about this.

**Comment by aeschli** [comment] 2017-12-18 16:53
@code-d Thanks for your investigations and findings.
I added code to catch all errors and log the full stack trace in the JSON output to 1.19. It should be  no longer be possible to crash the whole server with a malformed response.

- Can you try again in 1.19 (just released)?
- Can you send me the content one of the malformed response?

**Comment by code-d** [comment] 2017-12-20 01:06
@aeschli still receive the error message in 1.19

[trace-1.19.txt](https://github.com/Microsoft/vscode/files/1573792/trace-1.19.txt)
[malformed-tsconfig.json.txt](https://github.com/Microsoft/vscode/files/1573795/malformed-tsconfig.json.txt)

**Comment by code-d** [comment] 2017-12-20 03:23
@aeschli hi, i finally found out the issue is related to your 'request-light' module:
when gzip encoding is used, and the response is malformed/corrupted, it will crash whole node process. so `Promise.catch` is not work
see [Response stream need error handling #2](https://github.com/Microsoft/node-request-light/issues/2)

**Closed** 2017-12-21 10:06 UTC
Labels: bug, json

**Comment by aeschli** [comment] 2017-12-21 10:07
Thanks a lot @code-d, that's a great help. I made a fix, this should be in tomorrows build. It would be great if you can verify if the fix works for you.

**Comment by aeschli** [comment] 2018-02-05 16:19
@code-d Were you able to verify that this fix in one of the latest [insider builds](https://code.visualstudio.com/insiders/)?

**Comment by ramya-rao-a** [comment] 2018-02-05 17:57
@aeschli How do you recommend we go around verifying this?

**Comment by octref** [comment] 2018-02-05 22:44
@aeschli The conversation is locked...Even if @code-d wanted he could not comment.

**Comment by code-d** [comment] 2018-02-06 01:41
@aeschli hi, i've tested. the error is gone.. i think it has been fixed

ps. strictly speaking: i can't verify the case of malformed schema/response data, because the responses from `json.schemastore.org` are all valid for the time being.

**Comment by aeschli** [comment] 2018-02-07 09:12
Thanks @code-d, that's good enough, we mark it as verified.
